include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-7-1]]

^<<v58-7-1,1>>^ Pois este Melquisedeque, rei de Salém e sacerdote do Deus Altíssimo, foi ao encontro de Abraão que voltava da matança dos reis, e abençoou-o,

[[v58-7-2]]

^<<v58-7-2,2>>^ e Abraão deu-lhe^&#42;1^ um décimo de tudo. Em primeiro lugar o seu nome, traduzido, significa “rei da justiça”, e além disso ele é rei de Salém, isto é, “rei da paz”.

[NOTE]
====
. Lit.: “repartiu”.
====

[[v58-7-3]]

^<<v58-7-3,3>>^ Sem pai, sem mãe, sem genealogia, sem princípio de dias nem fim de vida, mas feito semelhante ao Filho de Deus, permanece sacerdote para sempre.^&#42;1^

[NOTE]
====
. Ou: “perpetuamente”.
====

[[v58-7-4]]

^<<v58-7-4,4>>^ Vejam a grandeza deste homem, a quem Abraão, o patriarca,^&#42;1^ deu um décimo dos melhores despojos.

[NOTE]
====
. Ou: “chefe de família”.
====

[[v58-7-5]]

^<<v58-7-5,5>>^ É verdade que, segundo a Lei, aqueles entre os filhos de Levi que recebem o sacerdócio têm o mandamento de cobrar dízimos ao povo, isto é, aos seus irmãos, embora estes sejam descendentes^&#42;1^ de Abraão.

[NOTE]
====
. Lit.: “tenham saído dos lombos”.
====

[[v58-7-6]]

^<<v58-7-6,6>>^ Esse homem, porém, que não era da linhagem deles, recebeu dízimos de Abraão e abençoou aquele a quem as promessas foram feitas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Não se pode negar que aquele que abençoa é maior do que aquele que é abençoado.

[[v58-7-8]]

^<<v58-7-8,8>>^ E, no primeiro caso, os que recebem dízimos são homens que morrem, mas, no outro caso, é alguém sobre quem se dá testemunho de que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ E pode dizer-se que, por meio de Abraão, até mesmo Levi, que recebe dízimos, pagou dízimos,

[[v58-7-10]]

^<<v58-7-10,10>>^ porque ainda era um futuro descendente^&#42;1^ do seu antepassado quando Melquisedeque o encontrou.

[NOTE]
====
. Lit.: “ainda estava nos lombos”.
====

[[v58-7-11]]

^<<v58-7-11,11>>^ Se, então, fosse possível alcançar a perfeição por meio do sacerdócio levítico (pois este era um aspeto da Lei dada ao povo), que necessidade ainda haveria de surgir outro sacerdote, do qual se diz “à maneira de Melquisedeque”, e não “à maneira de Arão”?

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois, quando se muda o sacerdócio, torna-se necessário mudar também a Lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Porque o homem de quem se dizem estas coisas veio de outra tribo, da qual ninguém oficiou no altar.

[[v58-7-14]]

^<<v58-7-14,14>>^ Pois é claro que o nosso Senhor era descendente de Judá, mas Moisés não disse nada sobre sacerdotes virem daquela tribo.

[[v58-7-15]]

^<<v58-7-15,15>>^ E isto fica ainda mais claro quando surge outro sacerdote, semelhante a Melquisedeque,

[[v58-7-16]]

^<<v58-7-16,16>>^ que se tornou sacerdote não por uma exigência legal que depende da linhagem,^&#42;1^ mas pelo poder de uma vida indestrutível.

[NOTE]
====
. Ou: “carne”.
====

[[v58-7-17]]

^<<v58-7-17,17>>^ Pois sobre ele se testifica: “Tu és sacerdote para sempre à maneira de Melquisedeque.”

[[v58-7-18]]

^<<v58-7-18,18>>^ Assim, o mandamento anterior é anulado porque é fraco e ineficaz.

[[v58-7-19]]

^<<v58-7-19,19>>^ Pois a Lei não tornou nada perfeito, mas a introdução de uma esperança melhor fez isso, e através desta aproximamo-nos de Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ Também, visto que isso não foi feito sem um juramento solene

[[v58-7-21]]

^<<v58-7-21,21>>^ (pois é verdade que há homens que se tornaram sacerdotes sem um juramento solene, mas este tornou-se sacerdote através de um juramento solene a seu respeito, feito por Aquele que disse: “Jeová^&#42;1^ jurou, e não voltará atrás:^&#42;2^ ‘Tu és sacerdote para sempre’”),

[NOTE]
====
. Veja o Ap. A5.
. Ou: “não lamentará”.
====

[[v58-7-22]]

^<<v58-7-22,22>>^ Jesus tornou-se, portanto, a garantia^&#42;1^ de um pacto melhor.

[NOTE]
====
. Ou: “aquele que foi dado como penhor”.
====

[[v58-7-23]]

^<<v58-7-23,23>>^ Além disso, era necessário haver muitos sacerdotes em sucessão, porque a morte os impedia de continuar como tais;

[[v58-7-24]]

^<<v58-7-24,24>>^ mas, visto que ele continua vivo para sempre, o seu sacerdócio não tem sucessores.

[[v58-7-25]]

^<<v58-7-25,25>>^ Assim, ele também é capaz de salvar completamente os que se aproximam de Deus por meio dele, porque está sempre vivo para interceder por eles.

[[v58-7-26]]

^<<v58-7-26,26>>^ Pois é apropriado que tenhamos um sumo sacerdote assim: leal, inocente, sem mancha, separado dos pecadores e elevado acima dos céus.

[[v58-7-27]]

^<<v58-7-27,27>>^ Ao contrário daqueles sumos sacerdotes, ele não precisa de oferecer sacrifícios diariamente, primeiro pelos seus próprios pecados e depois pelos do povo, porque fez isso de uma vez para sempre quando se ofereceu a si mesmo.

[[v58-7-28]]

^<<v58-7-28,28>>^ Pois a Lei designa como sumos sacerdotes homens que têm fraquezas, mas a palavra do juramento solene feito depois da Lei designa um Filho, que foi aperfeiçoado para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]