include::./index.adoc[]

[[v58-11-0]]
=== Hebreus, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-11-1]]

^<<v58-11-1,1>>^ A fé é a firme confiança de que virá o que se espera, a demonstração clara^&#42;1^ de realidades que não se veem.

[NOTE]
====
. Ou: “prova convincente”.
====

[[v58-11-2]]

^<<v58-11-2,2>>^ Pois, por meio dela, os homens dos tempos antigos^&#42;1^ receberam testemunho.^&#42;2^

[NOTE]
====
. Ou: “os nossos ancestrais”.
. Ou: “receberam evidências da aprovação de Deus”.
====

[[v58-11-3]]

^<<v58-11-3,3>>^ Pela fé, percebemos que os sistemas de coisas foram postos^&#42;1^ em ordem pela palavra de Deus, de modo que aquilo que se vê veio a existir de coisas que não são visíveis.

[NOTE]
====
. Ou: “as épocas foram postas”. Veja o Glossário.
====

[[v58-11-4]]

^<<v58-11-4,4>>^ Pela fé, Abel ofereceu a Deus um sacrifício de maior valor do que o de Caim. Por meio dessa fé recebeu o testemunho de que era justo, pois Deus aprovou^&#42;1^ as suas dádivas. E, embora esteja morto, ainda fala por meio da sua fé.

[NOTE]
====
. Ou: “deu testemunho por reconhecer”.
====

[[v58-11-5]]

^<<v58-11-5,5>>^ Pela fé, Enoque foi transferido para não ver a morte, e não foi encontrado em lado nenhum, porque Deus o transferira; pois, antes de ser transferido, recebeu o testemunho de que agradara a Deus.

[[v58-11-6]]

^<<v58-11-6,6>>^ Além disso, sem fé é impossível agradar a Deus, pois quem se aproxima de Deus tem de crer que ele existe e que se torna o recompensador dos que o procuram seriamente.

[[v58-11-7]]

^<<v58-11-7,7>>^ Pela fé, Noé, depois de receber aviso divino de coisas que ainda não se viam, mostrou temor de Deus e construiu uma arca para a salvação da sua família; e, por meio desta fé, condenou o mundo e tornou-se herdeiro da justiça que resulta da fé.

[[v58-11-8]]

^<<v58-11-8,8>>^ Pela fé, Abraão, quando chamado, obedeceu, por partir para um lugar que receberia como herança; ele partiu, embora não soubesse para onde ia.

[[v58-11-9]]

^<<v58-11-9,9>>^ Pela fé, viveu como estrangeiro na terra da promessa, como se estivesse numa terra estrangeira, a morar em tendas com Isaque e Jacó, herdeiros com ele da mesma promessa.

[[v58-11-10]]

^<<v58-11-10,10>>^ Pois aguardava a cidade que tem verdadeiros alicerces, que foi projetada e construída por Deus.^&#42;1^

[NOTE]
====
. Ou: “cujo arquiteto e construtor é Deus”.
====

[[v58-11-11]]

^<<v58-11-11,11>>^ Também pela fé, Sara, embora já tivesse passado da idade, recebeu poder para conceber um descendente,^&#42;1^ visto que considerava fiel^&#42;2^ Aquele que fizera a promessa.

[NOTE]
====
. Lit.: “semente”.
. Ou: “confiável”.
====

[[v58-11-12]]

^<<v58-11-12,12>>^ Por isso, de um só homem que já estava como que morto, nasceram filhos tão numerosos como as estrelas do céu e tão incontáveis como os grãos de areia à beira-mar.

[[v58-11-13]]

^<<v58-11-13,13>>^ Todos estes morreram com fé, embora não recebessem as coisas prometidas; mas viram-nas de longe e aceitaram-nas com alegria, e declararam publicamente que eram estrangeiros e residentes temporários naquela terra.

[[v58-11-14]]

^<<v58-11-14,14>>^ Os que falam assim demonstram que procuram seriamente um lugar para si mesmos.

[[v58-11-15]]

^<<v58-11-15,15>>^ Contudo, se continuassem a lembrar-se do lugar de onde tinham saído, teriam tido a oportunidade de voltar.

[[v58-11-16]]

^<<v58-11-16,16>>^ Mas o facto é que tais pessoas procuram alcançar um lugar melhor, isto é, um lugar que pertence ao céu. Portanto, Deus não se envergonha delas, de ser chamado seu Deus, pois preparou-lhes uma cidade.

[[v58-11-17]]

^<<v58-11-17,17>>^ Pela fé, Abraão, quando foi provado, praticamente ofereceu Isaque — o homem que recebera alegremente as promessas tentou oferecer o seu único filho^&#42;1^ —,

[NOTE]
====
. Lit.: “filho unigénito”.
====

[[v58-11-18]]

^<<v58-11-18,18>>^ embora lhe tivesse sido dito: “O que será chamado tua descendência^&#42;1^ virá por meio de Isaque.”

[NOTE]
====
. Lit.: “semente”.
====

[[v58-11-19]]

^<<v58-11-19,19>>^ Mas ele concluiu que Deus era capaz de levantar Isaque até mesmo dentre os mortos; e recebeu-o da morte em sentido ilustrativo.

[[v58-11-20]]

^<<v58-11-20,20>>^ Também pela fé, Isaque abençoou Jacó e Esaú a respeito de coisas futuras.

[[v58-11-21]]

^<<v58-11-21,21>>^ Pela fé, Jacó, quando estava para morrer, abençoou cada um dos filhos de José e adorou a Deus, apoiando-se na extremidade do seu bastão.

[[v58-11-22]]

^<<v58-11-22,22>>^ Pela fé, José, perto do seu fim, falou do êxodo dos filhos de Israel, e deu instruções^&#42;1^ a respeito dos seus ossos.^&#42;2^

[NOTE]
====
. Ou: “uma ordem”.
. Ou: “do seu sepultamento”.
====

[[v58-11-23]]

^<<v58-11-23,23>>^ Pela fé, Moisés foi escondido pelos seus pais durante três meses depois de ter nascido, porque viram que a criança era bela e não temeram a ordem do rei.

[[v58-11-24]]

^<<v58-11-24,24>>^ Pela fé, Moisés, quando se tornou adulto, recusou-se a ser chamado filho da filha do Faraó,

[[v58-11-25]]

^<<v58-11-25,25>>^ escolhendo ser maltratado com o povo de Deus em vez de desfrutar os prazeres temporários do pecado,

[[v58-11-26]]

^<<v58-11-26,26>>^ porque considerava a desonra do Cristo como uma riqueza maior do que os tesouros do Egito, pois olhava atentamente para o pagamento da recompensa.

[[v58-11-27]]

^<<v58-11-27,27>>^ Pela fé, deixou o Egito, mas sem temer a ira do rei, porque permanecia firme como se visse Aquele que é invisível.

[[v58-11-28]]

^<<v58-11-28,28>>^ Pela fé, celebrou a Páscoa e fez a aspersão do sangue, para que o destruidor não tocasse nos primogénitos deles.

[[v58-11-29]]

^<<v58-11-29,29>>^ Pela fé, o povo atravessou o mar Vermelho como em terra seca; mas, quando os egípcios tentaram fazer o mesmo, foram engolidos pelo mar.

[[v58-11-30]]

^<<v58-11-30,30>>^ Pela fé, os muros de Jericó caíram, depois de o povo ter marchado à volta deles durante sete dias.

[[v58-11-31]]

^<<v58-11-31,31>>^ Pela fé, Raabe, a prostituta, não morreu com os que foram desobedientes, porque recebeu os espiões de modo pacífico.

[[v58-11-32]]

^<<v58-11-32,32>>^ E o que mais direi? Pois iria faltar-me tempo se eu falasse também sobre Gideão, Baraque, Sansão, Jefté, David, bem como Samuel e os outros profetas.

[[v58-11-33]]

^<<v58-11-33,33>>^ Pela fé, eles derrotaram reinos, estabeleceram a justiça, obtiveram promessas, fecharam a boca de leões,

[[v58-11-34]]

^<<v58-11-34,34>>^ apagaram a força do fogo, escaparam do fio da espada, de um estado fraco foram feitos fortes, tornaram-se poderosos na guerra, derrotaram exércitos invasores.

[[v58-11-35]]

^<<v58-11-35,35>>^ Mulheres receberam os seus mortos pela ressurreição, mas outros foram torturados porque não aceitaram um livramento,^&#42;1^ para poderem alcançar uma ressurreição melhor.

[NOTE]
====
. Ou: “livramento por meio de algum resgate”.
====

[[v58-11-36]]

^<<v58-11-36,36>>^ Sim, outros foram provados por serem ridicularizados e açoitados; de facto, mais do que isso, por serem acorrentados e presos.

[[v58-11-37]]

^<<v58-11-37,37>>^ Foram apedrejados, provados, serrados ao meio,^&#42;1^ mortos à espada, andavam vestidos de peles de ovelhas e de peles de cabras, passando necessidades, sofrendo aflições, sendo maltratados;

[NOTE]
====
. Ou: “serrados em pedaços”.
====

[[v58-11-38]]

^<<v58-11-38,38>>^ e o mundo não era digno deles. Vagueavam pelos desertos, pelas montanhas, pelas cavernas e pelas grutas da terra.

[[v58-11-39]]

^<<v58-11-39,39>>^ Contudo, embora todos estes tenham recebido testemunho favorável por causa da sua fé, não obtiveram o cumprimento da promessa,

[[v58-11-40]]

^<<v58-11-40,40>>^ porque Deus tinha previsto algo melhor para nós, a fim de que eles, sem nós, não se tornassem perfeitos.

'''

xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[Próximo Capítulo &#62;]