include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-8-1]]

^<<v58-8-1,1>>^ Este é o ponto principal do que estamos a dizer: nós temos um sumo sacerdote como esse, e ele sentou-se à direita do trono da Majestade nos céus;

[[v58-8-2]]

^<<v58-8-2,2>>^ ele é servo^&#42;1^ no lugar santo e na verdadeira tenda, que Jeová^&#42;2^ erigiu, e não o homem.

[NOTE]
====
. Ou: “servidor público; ministro”.
. Veja o Ap. A5.
====

[[v58-8-3]]

^<<v58-8-3,3>>^ Pois todo o sumo sacerdote é designado para oferecer tanto dádivas como sacrifícios, portanto era necessário que este sumo sacerdote também tivesse algo para oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Se ele estivesse na terra, não seria sacerdote, visto que já existem homens que oferecem as dádivas segundo a Lei.

[[v58-8-5]]

^<<v58-8-5,5>>^ Esses homens prestam serviço sagrado como uma cópia e uma sombra das coisas celestiais, conforme demonstrado pela ordem divina que Moisés recebeu quando estava para construir a tenda. Pois Ele disse: “Tem o cuidado de fazer todas as coisas segundo o modelo que te foi mostrado no monte.”

[[v58-8-6]]

^<<v58-8-6,6>>^ No entanto, Jesus obteve agora um serviço^&#42;1^ mais excelente, porque também é o mediador de um pacto correspondentemente melhor, que foi estabelecido legalmente com base em promessas melhores.

[NOTE]
====
. Ou: “serviço público; ministério”.
====

[[v58-8-7]]

^<<v58-8-7,7>>^ Se aquele primeiro pacto não tivesse defeitos, não teria havido necessidade de um segundo.

[[v58-8-8]]

^<<v58-8-8,8>>^ Porque ele vê defeitos no povo quando diz: “‘Vejam! Estão a chegar os dias’, diz Jeová,^&#42;1^ ‘em que farei um novo pacto com a casa de Israel e com a casa de Judá.

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-8-9]]

^<<v58-8-9,9>>^ Não será como o pacto que fiz com os seus antepassados no dia em que os agarrei pela mão para tirá-los da terra do Egito, porque eles não permaneceram no meu pacto, e por isso deixei de me importar com eles’, diz Jeová.”^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-8-10]]

^<<v58-8-10,10>>^ “‘Pois este é o pacto que farei com a casa de Israel depois desses dias’, diz Jeová.^&#42;1^ ‘Porei as minhas leis na sua mente e irei escrevê-las no seu coração. E eu irei tornar-me o seu Deus, e eles irão tornar-se o meu povo.

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-8-11]]

^<<v58-8-11,11>>^ “‘E não continuarão a ensinar cada um ao seu concidadão e cada um ao seu irmão, dizendo: “Conhece a Jeová!”^&#42;1^ Porque todos eles me conhecerão, desde o menor até ao maior.

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-8-12]]

^<<v58-8-12,12>>^ Pois serei misericordioso em relação às suas ações injustas e não me voltarei a lembrar dos seus pecados.’”

[[v58-8-13]]

^<<v58-8-13,13>>^ Ao dizer “um novo pacto”, ele tornou o anterior obsoleto. E o que é obsoleto e fica velho está prestes a desaparecer.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]