include::./index.adoc[]

[[v58-13-0]]
=== Hebreus, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-13-1]]

^<<v58-13-1,1>>^ Que o vosso amor fraternal continue.

[[v58-13-2]]

^<<v58-13-2,2>>^ Não se esqueçam da hospitalidade,^&#42;1^ porque graças a ela alguns, sem o saberem, receberam anjos.

[NOTE]
====
. Ou: “bondade a estranhos”.
====

[[v58-13-3]]

^<<v58-13-3,3>>^ Lembrem-se dos que estão presos,^&#42;1^ como se estivessem presos com eles, e dos que estão a ser maltratados, visto que vocês mesmos também estão no corpo.^&#42;2^

[NOTE]
====
. Lit.: “dos acorrentados; dos em correntes”.
. Ou, possivelmente: “como se estivessem a sofrer com eles”.
====

[[v58-13-4]]

^<<v58-13-4,4>>^ O casamento seja honroso entre todos, e o leito conjugal mantido puro,^&#42;1^ porque Deus julgará os que praticam a imoralidade sexual^&#42;2^ e os adúlteros.

[NOTE]
====
. Ou: “imaculado”.
. Veja o Glossário.
====

[[v58-13-5]]

^<<v58-13-5,5>>^ Que o vosso modo de vida esteja livre do amor ao dinheiro, ao passo que ficam satisfeitos com as coisas que têm.^&#42;1^ Pois ele disse: “Nunca te deixarei e nunca te abandonarei.”

[NOTE]
====
. Ou: “coisas atuais”.
====

[[v58-13-6]]

^<<v58-13-6,6>>^ Para que fiquemos cheios de coragem e digamos: “Jeová^&#42;1^ é quem me ajuda; não terei medo. O que me pode fazer o homem?”

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-13-7]]

^<<v58-13-7,7>>^ Lembrem-se dos que exercem liderança^&#42;1^ no vosso meio, os que vos transmitiram a palavra de Deus, e, ao observarem os resultados da sua conduta, imitem a sua fé.

[NOTE]
====
. Ou: “tomam a dianteira”.
====

[[v58-13-8]]

^<<v58-13-8,8>>^ Jesus Cristo é o mesmo, ontem, hoje e para sempre.

[[v58-13-9]]

^<<v58-13-9,9>>^ Não sejam desencaminhados por ensinamentos variados e estranhos, pois é melhor que o coração seja fortalecido pela bondade imerecida do que por alimentos,^&#42;1^ que não beneficiam os que se preocupam com eles.

[NOTE]
====
. Isto é, por regras sobre alimentos.
====

[[v58-13-10]]

^<<v58-13-10,10>>^ Nós temos um altar do qual os que prestam serviço sagrado na tenda não têm o direito de^&#42;1^ comer.

[NOTE]
====
. Lit.: “não têm autoridade para”.
====

[[v58-13-11]]

^<<v58-13-11,11>>^ Pois os corpos daqueles animais cujo sangue é levado para dentro do lugar santo pelo sumo sacerdote, como oferta pelo pecado, são queimados fora do acampamento.

[[v58-13-12]]

^<<v58-13-12,12>>^ Portanto, Jesus também sofreu fora do portão da cidade para santificar o povo com o seu próprio sangue.

[[v58-13-13]]

^<<v58-13-13,13>>^ Assim, vamos ao seu encontro, fora do acampamento, levando a desonra que ele levou,

[[v58-13-14]]

^<<v58-13-14,14>>^ pois não temos aqui uma cidade que permaneça, mas procuramos seriamente aquela que vem.

[[v58-13-15]]

^<<v58-13-15,15>>^ Por meio dele, ofereçamos sempre a Deus um sacrifício de louvor, isto é, o fruto dos nossos lábios, que fazem declaração pública do seu nome.

[[v58-13-16]]

^<<v58-13-16,16>>^ Além disso, não se esqueçam de fazer o bem e de partilhar com outros o que têm, pois Deus agrada-se de tais sacrifícios.

[[v58-13-17]]

^<<v58-13-17,17>>^ Sejam obedientes aos que exercem liderança^&#42;1^ no vosso meio e sejam submissos, pois eles vigiam sobre vocês,^&#42;2^ como quem há de prestar contas, para que o façam com alegria, e não com suspiros, porque isso vos seria prejudicial.

[NOTE]
====
. Ou: “tomam a dianteira”.
. Ou: “as vossas almas”.
====

[[v58-13-18]]

^<<v58-13-18,18>>^ Continuem a orar por nós, pois estamos certos de que temos uma boa consciência,^&#42;1^ visto que nos queremos comportar honestamente em todas as coisas.

[NOTE]
====
. Ou: “uma consciência honesta”.
====

[[v58-13-19]]

^<<v58-13-19,19>>^ Mas exorto-vos especialmente a orar para que eu vos seja restituído mais depressa.

[[v58-13-20]]

^<<v58-13-20,20>>^ Que o Deus de paz, que com o sangue de um pacto eterno levantou dentre os mortos o grande pastor das ovelhas, o nosso Senhor Jesus,

[[v58-13-21]]

^<<v58-13-21,21>>^ vos equipe com todas as coisas boas para fazerem a sua vontade, e realize em nós, por meio de Jesus Cristo, aquilo que é agradável aos seus olhos; a ele seja dada a glória para todo o sempre. Amém.

[[v58-13-22]]

^<<v58-13-22,22>>^ Exorto-vos, irmãos, a ouvirem com paciência estas palavras de encorajamento, pois escrevi-vos uma breve carta.

[[v58-13-23]]

^<<v58-13-23,23>>^ Quero que saibam que o nosso irmão Timóteo foi libertado. Se ele vier em breve, irei com ele ver-vos.

[[v58-13-24]]

^<<v58-13-24,24>>^ Transmitam as minhas saudações a todos os que exercem liderança^&#42;1^ no vosso meio e a todos os santos. Os irmãos de Itália mandam-vos saudações.

[NOTE]
====
. Ou: “tomam a dianteira”.
====

[[v58-13-25]]

^<<v58-13-25,25>>^ A bondade imerecida esteja convosco.

'''

xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[&#60; Capítulo Anterior] | <<v58-13-0,Topo>> | xref:059-tiago/059-tiago-001.adoc#v59-1-0[Próximo Capítulo &#62;]