include::./index.adoc[]

[[v58-1-0]]
=== Hebreus, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-1-1]]

^<<v58-1-1,1>>^ Há muito tempo, Deus falou aos nossos antepassados por meio dos profetas, em muitas ocasiões e de muitas maneiras.

[[v58-1-2]]

^<<v58-1-2,2>>^ Agora, no fim destes dias, falou-nos por meio de um Filho, a quem designou herdeiro de todas as coisas e por meio de quem fez os sistemas de coisas.^&#42;1^

[NOTE]
====
. Ou: “as épocas”. Veja o Glossário.
====

[[v58-1-3]]

^<<v58-1-3,3>>^ Ele é o reflexo da glória de Deus e a representação exata do seu ser, e sustenta todas as coisas pela sua poderosa palavra. E, depois de ter feito uma purificação dos nossos pecados, sentou-se à direita da Majestade nas alturas.

[[v58-1-4]]

^<<v58-1-4,4>>^ Assim, tornou-se superior aos anjos, visto que herdou um nome mais excelente do que o deles.

[[v58-1-5]]

^<<v58-1-5,5>>^ Por exemplo, a qual dos anjos disse Deus alguma vez: “Tu és meu filho; hoje, tornei-me teu pai”? E novamente: “Eu vou tornar-me seu pai e ele vai tornar-se meu filho”?

[[v58-1-6]]

^<<v58-1-6,6>>^ Mas, ao trazer novamente o seu Primogénito à terra habitada, ele diz: “Que todos os anjos de Deus lhe prestem homenagem.”^&#42;1^

[NOTE]
====
. Ou: “se curvem diante dele”.
====

[[v58-1-7]]

^<<v58-1-7,7>>^ Além disso, ele diz a respeito dos anjos: “Ele faz dos seus anjos espíritos, e dos seus servos^&#42;1^ uma chama de fogo.”

[NOTE]
====
. Ou: “servidores públicos”.
====

[[v58-1-8]]

^<<v58-1-8,8>>^ Mas a respeito do Filho ele diz: “Deus é o teu trono para todo o sempre, e o cetro do teu Reino é o cetro da retidão.^&#42;1^

[NOTE]
====
. Ou: “justiça”.
====

[[v58-1-9]]

^<<v58-1-9,9>>^ Tu amaste a justiça^&#42;1^ e odiaste o que é contra a lei. Foi por isso que Deus, o teu Deus, te ungiu com óleo de alegria mais do que aos teus companheiros.”

[NOTE]
====
. Veja o Glossário.
====

[[v58-1-10]]

^<<v58-1-10,10>>^ E: “Ó Senhor, no princípio lançaste os alicerces da terra, e os céus são obra das tuas mãos.

[[v58-1-11]]

^<<v58-1-11,11>>^ Eles deixarão de existir, mas tu permanecerás; eles hão de gastar-se como uma peça de roupa,

[[v58-1-12]]

^<<v58-1-12,12>>^ e tu hás de enrolá-los assim como um manto, como uma peça de roupa, e serão trocados. Tu, porém, és o mesmo, e os teus anos nunca chegarão ao fim.”

[[v58-1-13]]

^<<v58-1-13,13>>^ Mas a respeito de qual dos anjos disse ele alguma vez: “Senta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés”?^&#42;1^

[NOTE]
====
. Ou: “inimigos como escabelo para os teus pés”.
====

[[v58-1-14]]

^<<v58-1-14,14>>^ Não são todos eles espíritos que prestam serviço sagrado,^&#42;1^ enviados para servir os que vão herdar a salvação?

[NOTE]
====
. Ou: “serviço público”.
====

'''

xref:057-filemon/057-filemon-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[Próximo Capítulo &#62;]