include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-3-1]]

^<<v58-3-1,1>>^ Portanto, santos irmãos, participantes da chamada^&#42;1^ celestial, considerem aquele que reconhecemos como^&#42;2^ apóstolo e sumo sacerdote — Jesus.

[NOTE]
====
. Ou: “do convite”.
. Ou: “confessamos”.
====

[[v58-3-2]]

^<<v58-3-2,2>>^ Ele foi fiel Àquele que o designou, assim como Moisés também o foi em toda a casa d’Aquele.

[[v58-3-3]]

^<<v58-3-3,3>>^ Pois ele^&#42;1^ é considerado digno de maior glória do que Moisés, visto que quem constrói uma casa tem mais honra do que a própria casa.

[NOTE]
====
. Isto é, Jesus.
====

[[v58-3-4]]

^<<v58-3-4,4>>^ Naturalmente, toda a casa é construída por alguém, mas quem construiu todas as coisas foi Deus.

[[v58-3-5]]

^<<v58-3-5,5>>^ Moisés foi fiel como assistente em toda a casa d’Aquele, o que serviu de testemunho das coisas de que se falaria depois,

[[v58-3-6]]

^<<v58-3-6,6>>^ mas Cristo foi fiel como filho sobre a casa de Deus. Nós somos a casa d’Ele, desde que de facto nos apeguemos firmemente, até ao fim, à nossa confiança no falar^&#42;1^ e à esperança de que nos orgulhamos.

[NOTE]
====
. Ou: “liberdade no falar”.
====

[[v58-3-7]]

^<<v58-3-7,7>>^ Portanto, como diz o espírito santo: “Hoje, se escutarem a sua voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçam o coração como na ocasião em que se provocou ira amarga, como no dia da provação no deserto,^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v58-3-9]]

^<<v58-3-9,9>>^ onde os vossos antepassados me puseram à prova e me desafiaram, embora tivessem visto as minhas obras por 40 anos.

[[v58-3-10]]

^<<v58-3-10,10>>^ É por isso que me indignei com esta geração e disse: ‘Eles perdem-se sempre no seu coração, e não chegaram a conhecer os meus caminhos.’

[[v58-3-11]]

^<<v58-3-11,11>>^ Então, jurei na minha ira: ‘Não entrarão no meu descanso.’”

[[v58-3-12]]

^<<v58-3-12,12>>^ Cuidado, irmãos, para que nunca se desenvolva em nenhum de vocês um coração mau e sem fé, por se afastarem do Deus vivente;

[[v58-3-13]]

^<<v58-3-13,13>>^ mas continuem a encorajar-se uns aos outros cada dia, enquanto durar o tempo a que se chama “hoje”, para que nenhum de vocês fique endurecido pelo poder enganoso do pecado.

[[v58-3-14]]

^<<v58-3-14,14>>^ Porque nós só nos tornaremos realmente participantes do^&#42;1^ Cristo se nos apegarmos firmemente até ao fim à confiança que tivemos no princípio.

[NOTE]
====
. Ou: “só temos uma parceria (participação) com”.
====

[[v58-3-15]]

^<<v58-3-15,15>>^ É como se diz: “Hoje, se escutarem a sua voz, não endureçam o coração como na ocasião em que se provocou ira amarga.”

[[v58-3-16]]

^<<v58-3-16,16>>^ Pois quem foram os que ouviram e ainda assim provocaram Deus à ira amarga? Não foram, de facto, todos os que tinham saído do Egito sob Moisés?

[[v58-3-17]]

^<<v58-3-17,17>>^ Além disso, com quem é que Deus ficou indignado durante 40 anos? Não foi com aqueles que pecaram, cujos cadáveres caíram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E a quem é que ele jurou que não entrariam no seu descanso? Não foi aos que agiram de modo desobediente?

[[v58-3-19]]

^<<v58-3-19,19>>^ Vemos assim que não puderam entrar porque não tiveram fé.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]