include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-6-1]]

^<<v58-6-1,1>>^ Portanto, agora que deixámos para trás a doutrina básica acerca do Cristo, avancemos à madureza, sem lançar novamente um alicerce, a saber, o arrependimento de obras mortas e a fé em Deus,

[[v58-6-2]]

^<<v58-6-2,2>>^ o ensinamento sobre batismos e a imposição das mãos, a ressurreição dos mortos e o julgamento eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ E isso faremos, se Deus o permitir.

[[v58-6-4]]

^<<v58-6-4,4>>^ Pois, no que se refere àqueles que já foram esclarecidos, que provaram a dádiva^&#42;1^ celestial, que se tornaram participantes do espírito santo

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v58-6-5]]

^<<v58-6-5,5>>^ e que provaram a boa palavra de Deus e os poderes do futuro sistema de coisas,^&#42;1^

[NOTE]
====
. Ou: “da época futura”. Veja o Glossário.
====

[[v58-6-6]]

^<<v58-6-6,6>>^ mas que se desviaram, é impossível que sejam novamente levados ao arrependimento; porque eles pregam outra vez para si mesmos o Filho de Deus na estaca e expõem-no à desonra pública.

[[v58-6-7]]

^<<v58-6-7,7>>^ Pois o solo recebe uma bênção de Deus quando absorve a chuva que frequentemente cai sobre ele, e então produz vegetação útil àqueles para quem é cultivado.

[[v58-6-8]]

^<<v58-6-8,8>>^ Mas, se produz espinhos e abrolhos, é rejeitado e está prestes a ser amaldiçoado e por fim será queimado.

[[v58-6-9]]

^<<v58-6-9,9>>^ No entanto, amados, embora estejamos a falar desta maneira, estamos convencidos de coisas melhores no vosso caso, coisas relacionadas com a salvação.

[[v58-6-10]]

^<<v58-6-10,10>>^ Pois Deus não é injusto para se esquecer da vossa obra e do amor que mostraram pelo seu nome, por servirem os santos e continuarem a servi-los.

[[v58-6-11]]

^<<v58-6-11,11>>^ Mas desejamos que cada um de vocês mostre a mesma diligência, para ter a plena certeza da esperança até ao fim,

[[v58-6-12]]

^<<v58-6-12,12>>^ para que não se tornem preguiçosos, mas sejam imitadores daqueles que pela fé e pela paciência herdam as promessas.

[[v58-6-13]]

^<<v58-6-13,13>>^ Pois, quando Deus fez a sua promessa a Abraão, como não podia jurar por ninguém maior, jurou por si mesmo,

[[v58-6-14]]

^<<v58-6-14,14>>^ dizendo: “Certamente te abençoarei e certamente te multiplicarei.”

[[v58-6-15]]

^<<v58-6-15,15>>^ Assim Abraão, depois de ter mostrado paciência, obteve esta promessa.

[[v58-6-16]]

^<<v58-6-16,16>>^ Porque os homens juram por alguém maior, e o seu juramento é o fim de toda a controvérsia, visto que para eles é uma garantia legal.

[[v58-6-17]]

^<<v58-6-17,17>>^ Da mesma maneira, quando Deus decidiu demonstrar mais claramente aos herdeiros da promessa que o seu propósito^&#42;1^ era imutável, ele garantiu-o^&#42;2^ com um juramento,

[NOTE]
====
. Ou: “conselho”.
. Ou: “ele interveio”. Lit.: “ele mediou”.
====

[[v58-6-18]]

^<<v58-6-18,18>>^ para que, por meio de duas coisas imutáveis, nas quais é impossível que Deus minta, nós, os que fugimos para o refúgio, recebamos forte encorajamento para nos apegarmos firmemente à esperança que nos é apresentada.

[[v58-6-19]]

^<<v58-6-19,19>>^ Temos esta esperança como uma âncora para a alma,^&#42;1^ tanto segura como firme, e ela entra até ao interior, atrás da cortina,

[NOTE]
====
. Ou: “para a nossa vida”.
====

[[v58-6-20]]

^<<v58-6-20,20>>^ onde um precursor entrou em nosso benefício: Jesus, que se tornou sumo sacerdote para sempre à maneira de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]