include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-12-1]]

^<<v58-12-1,1>>^ Portanto, visto que estamos rodeados de uma nuvem tão grande de testemunhas, livremo-nos também de todo o peso e do pecado que facilmente nos enlaça, e corramos com perseverança a corrida que se nos apresenta,

[[v58-12-2]]

^<<v58-12-2,2>>^ olhando atentamente para o Agente Principal e Aperfeiçoador da nossa fé, Jesus. Pela alegria que lhe foi apresentada, ele suportou a morte numa estaca de tortura,^&#42;1^ desprezando a vergonha, e sentou-se à direita do trono de Deus.

[NOTE]
====
. Veja o Glossário.
====

[[v58-12-3]]

^<<v58-12-3,3>>^ De facto, considerem de perto aquele que suportou tantas palavras hostis da parte de pecadores que agiam contra os seus próprios interesses, para que não se cansem nem desistam.^&#42;1^

[NOTE]
====
. Ou: “nem desanimem nas vossas almas”.
====

[[v58-12-4]]

^<<v58-12-4,4>>^ Na vossa luta contra esse pecado, ainda não resistiram até ao ponto de o vosso sangue ser derramado.

[[v58-12-5]]

^<<v58-12-5,5>>^ E esqueceram-se totalmente da exortação que vos é dirigida como a filhos: “Meu filho, não menosprezes a disciplina da parte de Jeová^&#42;1^ nem desanimes quando és corrigido por ele.

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-12-6]]

^<<v58-12-6,6>>^ Pois Jeová^&#42;1^ disciplina aqueles a quem ama; de facto, açoita^&#42;2^ a cada um a quem recebe como filho.”

[NOTE]
====
. Veja o Ap. A5.
. Ou: “castiga”.
====

[[v58-12-7]]

^<<v58-12-7,7>>^ Como parte da vossa disciplina,^&#42;1^ precisam de perseverar. Deus trata-vos como filhos. Pois qual é o filho que não é disciplinado pelo pai?

[NOTE]
====
. Ou: “do vosso treino”.
====

[[v58-12-8]]

^<<v58-12-8,8>>^ Mas, se nem todos vocês recebem esta disciplina, então são realmente filhos ilegítimos, e não filhos verdadeiros.

[[v58-12-9]]

^<<v58-12-9,9>>^ Além disso, os nossos pais humanos^&#42;1^ disciplinavam-nos, e nós os respeitávamos. Não nos deveríamos sujeitar com mais prontidão ao Pai da nossa vida espiritual para vivermos?

[NOTE]
====
. Lit.: “os pais da nossa carne”.
====

[[v58-12-10]]

^<<v58-12-10,10>>^ Pois eles disciplinaram-nos por pouco tempo, segundo o que lhes parecia bem, mas ele fá-lo para o nosso benefício, para participarmos da sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ É verdade que nenhuma disciplina parece, no momento, ser motivo de alegria, mas de dor;^&#42;1^ depois, porém, a disciplina dá o fruto pacífico da justiça aos que têm sido treinados por ela.

[NOTE]
====
. Ou: “tristeza”.
====

[[v58-12-12]]

^<<v58-12-12,12>>^ Portanto, fortaleçam as mãos caídas e os joelhos enfraquecidos,

[[v58-12-13]]

^<<v58-12-13,13>>^ e continuem a endireitar os caminhos para os vossos pés, para que o aleijado não fique pior,^&#42;1^ mas, em vez disso, para que sare.

[NOTE]
====
. Ou: “para que não fique desconjuntado o que é aleijado”.
====

[[v58-12-14]]

^<<v58-12-14,14>>^ Empenhem-se pela paz com todos e pela santificação,^&#42;1^ sem a qual nenhum homem verá o Senhor.

[NOTE]
====
. Ou: “santidade”.
====

[[v58-12-15]]

^<<v58-12-15,15>>^ Prestem cuidadosa atenção para que ninguém deixe de obter a bondade imerecida de Deus, para que nenhuma raiz venenosa brote para causar dificuldades, e muitos sejam contaminados por ela;

[[v58-12-16]]

^<<v58-12-16,16>>^ e prestem atenção para que não haja no vosso meio alguém que pratique imoralidade sexual^&#42;1^ nem alguém que não estime as coisas sagradas, como Esaú, que abdicou dos seus direitos de primogénito em troca de uma só refeição.

[NOTE]
====
. Veja o Glossário.
====

[[v58-12-17]]

^<<v58-12-17,17>>^ Pois vocês sabem que mais tarde, quando ele quis herdar a bênção, foi rejeitado; porque, embora tentasse insistentemente, com lágrimas, que houvesse uma mudança de decisão,^&#42;1^ não o conseguiu.^&#42;2^

[NOTE]
====
. Isto é, da decisão do seu pai.
. Lit.: “não encontrou lugar para isso”.
====

[[v58-12-18]]

^<<v58-12-18,18>>^ Pois vocês não se aproximaram de algo palpável, que tenha ficado em chamas, nem de uma nuvem escura, de densa escuridão, de uma tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ nem do som duma trombeta e da voz que falou. Ao ouvi-la, o povo implorou que não se lhes falasse mais nada.

[[v58-12-20]]

^<<v58-12-20,20>>^ Pois não podiam suportar a ordem: “Se até mesmo um animal tocar no monte, deve ser apedrejado.”

[[v58-12-21]]

^<<v58-12-21,21>>^ Também, a cena era tão atemorizante que Moisés disse: “Estou a tremer de medo.”

[[v58-12-22]]

^<<v58-12-22,22>>^ Mas vocês aproximaram-se de um monte Sião e de uma cidade do Deus vivente, a Jerusalém celestial, e de miríades^&#42;1^ de anjos

[NOTE]
====
. Ou: “dezenas de milhares”.
====

[[v58-12-23]]

^<<v58-12-23,23>>^ em assembleia geral, e da congregação dos primogénitos que foram inscritos nos céus, e de Deus, o Juiz de todos, e da vida espiritual dos justos que já foram aperfeiçoados,

[[v58-12-24]]

^<<v58-12-24,24>>^ e de Jesus, o mediador de um novo pacto, e do sangue aspergido, que fala melhor do que o sangue de Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Cuidado, não se recusem a ouvir^&#42;1^ aquele que está a falar. Porque, se os que se recusaram a ouvir aquele que dava o aviso divino na terra não escaparam, muito menos escaparemos nós, se nos desviarmos daquele que fala desde os céus!

[NOTE]
====
. Ou: “não deem desculpas para deixar de ouvir; não ignorem”.
====

[[v58-12-26]]

^<<v58-12-26,26>>^ Naquele tempo, a sua voz abalou a terra, mas agora ele prometeu: “Mais uma vez farei tremer não só a terra, mas também o céu.”

[[v58-12-27]]

^<<v58-12-27,27>>^ A expressão “mais uma vez” indica a remoção das coisas que serão abaladas, as coisas feitas, para que permaneçam as coisas que não serão abaladas.

[[v58-12-28]]

^<<v58-12-28,28>>^ Portanto, já que receberemos um Reino que não pode ser abalado, continuemos a receber bondade imerecida, através da qual podemos prestar a Deus serviço sagrado de modo aceitável, com temor^&#42;1^ e reverência.

[NOTE]
====
. Ou: “temor de Deus”.
====

[[v58-12-29]]

^<<v58-12-29,29>>^ Pois o nosso Deus é um fogo consumidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]