include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v58-2-1]]

^<<v58-2-1,1>>^ É por isso que é necessário prestarmos mais atenção do que é costume às coisas que ouvimos, para que nunca nos desviemos.^&#42;1^

[NOTE]
====
. Ou: “para nunca andarmos à deriva”.
====

[[v58-2-2]]

^<<v58-2-2,2>>^ Pois, se a palavra falada por meio de anjos se mostrou certa, e toda a transgressão e desobediência recebeu a justa punição,

[[v58-2-3]]

^<<v58-2-3,3>>^ como é que escaparemos se negligenciarmos uma salvação tão grandiosa? Pois ela começou a ser anunciada por meio do nosso Senhor e foi-nos confirmada por aqueles que o ouviram,

[[v58-2-4]]

^<<v58-2-4,4>>^ ao passo que Deus se juntou a eles em dar testemunho por meio de sinais, milagres,^&#42;1^ várias obras poderosas e dons do espírito santo distribuídos segundo a sua vontade.

[NOTE]
====
. Ou: “portentos”.
====

[[v58-2-5]]

^<<v58-2-5,5>>^ Pois não foi a anjos que ele sujeitou a futura terra habitada, da qual estamos a falar.

[[v58-2-6]]

^<<v58-2-6,6>>^ Mas em certa passagem uma testemunha disse: “O que é o homem, para que te lembres dele, ou o filho do homem, para que cuides dele?

[[v58-2-7]]

^<<v58-2-7,7>>^ Fizeste-o um pouco menor do que os anjos; coroaste-o de glória e honra, e deste-lhe domínio sobre as obras das tuas mãos.

[[v58-2-8]]

^<<v58-2-8,8>>^ Sujeitaste-lhe todas as coisas debaixo dos pés.” Ao sujeitar-lhe todas as coisas, Deus não deixou nada que não lhe ficasse sujeito. Agora, porém, ainda não vemos que todas as coisas lhe estejam sujeitas.

[[v58-2-9]]

^<<v58-2-9,9>>^ Mas vemos Jesus, que foi feito um pouco menor do que os anjos, agora coroado de glória e honra por ter sofrido a morte, para que, pela bondade imerecida de Deus, provasse a morte por todos.

[[v58-2-10]]

^<<v58-2-10,10>>^ Pois era apropriado que aquele para quem e por meio de quem todas as coisas existem, ao trazer muitos filhos à glória, aperfeiçoasse por sofrimentos o Agente Principal da salvação deles.

[[v58-2-11]]

^<<v58-2-11,11>>^ Porque tanto aquele que santifica como os que estão a ser santificados provêm todos de um só, e por esse motivo ele não se envergonha de lhes chamar irmãos,

[[v58-2-12]]

^<<v58-2-12,12>>^ dizendo: “Vou declarar o teu nome aos meus irmãos e louvar-te com cânticos no meio da congregação.”

[[v58-2-13]]

^<<v58-2-13,13>>^ E também: “Porei nele a minha confiança.” E ainda: “Vejam! Eu e as crianças que Jeová^&#42;1^ me deu.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v58-2-14]]

^<<v58-2-14,14>>^ Portanto, visto que as “crianças” são participantes de sangue e carne, ele também participou das mesmas coisas, para que, pela sua morte, reduzisse a nada aquele que tem os meios de causar a morte, isto é, o Diabo,

[[v58-2-15]]

^<<v58-2-15,15>>^ e para que libertasse^&#42;1^ todos os que, por medo da morte, passaram toda a vida sujeitos à escravidão.

[NOTE]
====
. Ou: “emancipasse”.
====

[[v58-2-16]]

^<<v58-2-16,16>>^ Pois não é realmente a anjos que ele auxilia, mas auxilia a descendência^&#42;1^ de Abraão.

[NOTE]
====
. Lit.: “semente”.
====

[[v58-2-17]]

^<<v58-2-17,17>>^ Por isso, teve de se tornar igual aos seus “irmãos” em todos os sentidos, para se tornar um sumo sacerdote misericordioso e fiel nas coisas referentes a Deus, a fim de oferecer um sacrifício propiciatório^&#42;1^ pelos pecados do povo.

[NOTE]
====
. Ou: “oferecer um sacrifício de expiação; fazer expiação”.
====

[[v58-2-18]]

^<<v58-2-18,18>>^ Visto que ele mesmo sofreu ao ser posto à prova, pode vir em auxílio daqueles que estão a ser postos à prova.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]