include::./index.adoc[]

[[v63-1-0]]
=== 2 João, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v63-1-1]]

^<<v63-1-1,1>>^ O homem idoso,^&#42;1^ à senhora escolhida e aos seus filhos, a quem eu amo verdadeiramente — e não somente eu, mas também todos os que conhecem a verdade —

[NOTE]
====
. Ou: “O ancião”.
====

[[v63-1-2]]

^<<v63-1-2,2>>^ por causa da verdade que permanece em nós e que estará connosco para sempre.

[[v63-1-3]]

^<<v63-1-3,3>>^ A bondade imerecida, a misericórdia e a paz da parte de Deus, o Pai, e da parte de Jesus Cristo, o Filho do Pai, com a verdade e o amor, estarão connosco.

[[v63-1-4]]

^<<v63-1-4,4>>^ Fiquei muito feliz de saber que alguns dos teus filhos andam na verdade, conforme o mandamento que recebemos da parte do Pai.

[[v63-1-5]]

^<<v63-1-5,5>>^ E agora, senhora, eu peço-te que nos amemos uns aos outros. (Estou a escrever-te, não um novo mandamento, mas um que temos desde o princípio.)

[[v63-1-6]]

^<<v63-1-6,6>>^ E o amor significa o seguinte: que continuemos a andar segundo os seus mandamentos. Este é o mandamento, conforme ouviram desde o princípio: devem continuar a andar no amor.

[[v63-1-7]]

^<<v63-1-7,7>>^ Pois muitos enganadores saíram pelo mundo fora, aqueles que não reconhecem que Jesus Cristo veio na carne. Eles são o enganador e o anticristo.

[[v63-1-8]]

^<<v63-1-8,8>>^ Tenham cuidado para que não percam as coisas que trabalhámos para produzir; em vez disso, que obtenham uma plena recompensa.

[[v63-1-9]]

^<<v63-1-9,9>>^ Todo aquele que vai além dos ensinamentos do Cristo e não permanece neles não tem Deus. Quem permanece nestes ensinamentos é quem tem tanto o Pai como o Filho.

[[v63-1-10]]

^<<v63-1-10,10>>^ Se alguém vier ter convosco e não trouxer estes ensinamentos, não o recebam na vossa casa, nem o cumprimentem.

[[v63-1-11]]

^<<v63-1-11,11>>^ Pois quem o cumprimenta participa das suas obras más.

[[v63-1-12]]

^<<v63-1-12,12>>^ Embora eu tenha muitas coisas para vos escrever, não quero fazê-lo com papel e tinta, mas espero visitar-vos e falar convosco pessoalmente, para que a vossa alegria seja plena.

[[v63-1-13]]

^<<v63-1-13,13>>^ Os filhos da tua irmã, a escolhida, mandam-te saudações.

'''

xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[Próximo Capítulo &#62;]