include::./index.adoc[]

[[v53-2-0]]
=== 2 Tessalonicenses, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v53-2-1]]

^<<v53-2-1,1>>^ No entanto, irmãos, a respeito da presença do nosso Senhor Jesus Cristo e a sermos reunidos com ele, pedimos

[[v53-2-2]]

^<<v53-2-2,2>>^ que não percam facilmente o bom senso, nem fiquem assustados, quer por uma declaração inspirada,^&#42;1^ quer por uma mensagem falada, quer por uma carta aparentemente vinda de nós, que afirme que o dia de Jeová^&#42;2^ já chegou.

[NOTE]
====
. Ou: “por um espírito”. Veja o Glossário, “Espírito”.
. Veja o Ap. A5.
====

[[v53-2-3]]

^<<v53-2-3,3>>^ Que ninguém vos desencaminhe,^&#42;1^ de maneira nenhuma, porque esse dia não virá sem que primeiro venha a apostasia e seja revelado o homem que é contra a lei, o filho da destruição.

[NOTE]
====
. Ou: “seduza”.
====

[[v53-2-4]]

^<<v53-2-4,4>>^ Ele é um opositor e exalta-se acima de tudo o que se chama deus ou que é objeto de adoração,^&#42;1^ de modo que se senta no templo de Deus, exibindo-se como um deus.

[NOTE]
====
. Ou: “reverência”.
====

[[v53-2-5]]

^<<v53-2-5,5>>^ Não se lembram de que, quando eu ainda estava convosco, costumava dizer-vos estas coisas?

[[v53-2-6]]

^<<v53-2-6,6>>^ E, agora, vocês sabem o que está a agir como restrição, de modo que ele será revelado no tempo devido.

[[v53-2-7]]

^<<v53-2-7,7>>^ É verdade que o mistério desta violação da lei já está em ação, mas apenas até que aquele que, neste momento, age como restrição esteja fora do caminho.

[[v53-2-8]]

^<<v53-2-8,8>>^ Então, realmente, será revelado aquele que é contra a lei, a quem o Senhor Jesus eliminará com o espírito da sua boca e reduzirá a nada pela manifestação da sua presença.

[[v53-2-9]]

^<<v53-2-9,9>>^ Mas a presença daquele que é contra a lei deve-se à atuação de Satanás, com toda a obra poderosa, com sinais e milagres^&#42;1^ falsos

[NOTE]
====
. Ou: “portentos”.
====

[[v53-2-10]]

^<<v53-2-10,10>>^ e com todo o engano injusto para os que estão a caminho da destruição,^&#42;1^ em retribuição por não aceitarem o amor à verdade para que fossem salvos.

[NOTE]
====
. Ou: “estão a perecer”.
====

[[v53-2-11]]

^<<v53-2-11,11>>^ É por isso que Deus deixa que uma influência enganadora os desencaminhe para que acreditem na mentira,

[[v53-2-12]]

^<<v53-2-12,12>>^ a fim de que todos eles sejam julgados porque não acreditaram na verdade, mas tiveram prazer na injustiça.

[[v53-2-13]]

^<<v53-2-13,13>>^ No entanto, temos a obrigação de agradecer sempre a Deus por vocês, irmãos amados por Jeová,^&#42;1^ porque, desde o princípio, Deus vos escolheu para a salvação, por vos santificar com o seu espírito e pela vossa fé na verdade.

[NOTE]
====
. Veja o Ap. A5.
====

[[v53-2-14]]

^<<v53-2-14,14>>^ Foi para isto que ele vos chamou por meio das boas novas que declaramos, a fim de que obtenham a glória do nosso Senhor Jesus Cristo.

[[v53-2-15]]

^<<v53-2-15,15>>^ Assim, irmãos, mantenham-se firmes e apegados às tradições que vos foram ensinadas, quer tenha sido por uma mensagem falada, quer por uma carta nossa.

[[v53-2-16]]

^<<v53-2-16,16>>^ Além disso, que o próprio Jesus Cristo, nosso Senhor, e que Deus, nosso Pai, que nos amou e deu consolo eterno e boa esperança por meio da bondade imerecida,

[[v53-2-17]]

^<<v53-2-17,17>>^ consolem o vosso coração e vos tornem firmes^&#42;1^ em toda a boa ação e palavra.

[NOTE]
====
. Ou: “vos fortaleçam”.
====

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[&#60; Capítulo Anterior] | <<v53-2-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[Próximo Capítulo &#62;]