include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, persistam em orar por nós, para que a palavra de Jeová^&#42;1^ continue a espalhar-se rapidamente e a ser glorificada, assim como acontece convosco,

[NOTE]
====
. Veja o Ap. A5.
====

[[v53-3-2]]

^<<v53-3-2,2>>^ e que sejamos livrados de pessoas más e perversas, pois a fé não é propriedade de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas o Senhor é fiel, e ele vai fortalecer-vos e proteger-vos do Maligno.

[[v53-3-4]]

^<<v53-3-4,4>>^ Além disso, no que vos diz respeito, temos confiança no Senhor de que estão a seguir e continuarão a seguir as nossas instruções.

[[v53-3-5]]

^<<v53-3-5,5>>^ Que o Senhor continue a guiar com êxito o vosso coração ao amor a Deus e à perseverança pelo Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ Estamos a dar-vos instruções, irmãos, em nome do nosso Senhor Jesus Cristo, para que se afastem de qualquer irmão que ande de modo indisciplinado e não segundo a tradição^&#42;1^ que vocês^&#42;2^ receberam de nós.

[NOTE]
====
. Ou: “instrução”.
. Ou, possivelmente: “eles”.
====

[[v53-3-7]]

^<<v53-3-7,7>>^ Pois vocês sabem como nos devem imitar, porque não nos comportámos de modo indisciplinado no vosso meio,

[[v53-3-8]]

^<<v53-3-8,8>>^ nem comemos de graça^&#42;1^ o alimento de ninguém. Pelo contrário, trabalhávamos arduamente e com grande esforço, noite e dia, para não sermos um peso financeiro para nenhum de vocês.

[NOTE]
====
. Ou: “sem pagar”.
====

[[v53-3-9]]

^<<v53-3-9,9>>^ Não é que não tenhamos o direito de receber algo,^&#42;1^ mas queríamos apresentar-nos como um exemplo para imitarem.

[NOTE]
====
. Lit.: “não tenhamos autoridade”.
====

[[v53-3-10]]

^<<v53-3-10,10>>^ De facto, quando estávamos convosco, costumávamos dar-vos esta ordem: “Se alguém não quiser trabalhar, também não coma.”

[[v53-3-11]]

^<<v53-3-11,11>>^ Pois ouvimos dizer que alguns estão a andar de modo indisciplinado no vosso meio; não trabalham, e ainda se intrometem no que não lhes diz respeito.

[[v53-3-12]]

^<<v53-3-12,12>>^ A tais pessoas ordenamos e exortamos no Senhor Jesus Cristo que trabalhem tranquilamente e comam o alimento que elas mesmas ganham.

[[v53-3-13]]

^<<v53-3-13,13>>^ Quanto a vocês, irmãos, não desistam de fazer o que é bom.

[[v53-3-14]]

^<<v53-3-14,14>>^ Mas, se alguém não for obediente ao que dizemos nesta carta, tomem nota dele e parem de se associar com ele, para que fique envergonhado.

[[v53-3-15]]

^<<v53-3-15,15>>^ Contudo, não o considerem como inimigo, mas continuem a aconselhá-lo como a um irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ Que o Senhor da paz vos dê constantemente a paz, de todas as maneiras. Que o Senhor esteja convosco.

[[v53-3-17]]

^<<v53-3-17,17>>^ Aqui está a minha saudação, a de Paulo, pela minha própria mão, o que é um sinal em todas as cartas; é assim que eu escrevo.

[[v53-3-18]]

^<<v53-3-18,18>>^ Que a bondade imerecida do nosso Senhor Jesus Cristo esteja convosco.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]