include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v55-4-1]]

^<<v55-4-1,1>>^ Ordeno-te solenemente perante Deus e Cristo Jesus, que julgará os vivos e os mortos, pela sua manifestação e pelo seu Reino:

[[v55-4-2]]

^<<v55-4-2,2>>^ Prega a palavra; faz isso com urgência, em tempos favoráveis e em tempos difíceis; repreende, censura, exorta, com toda a paciência e arte de ensino.

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois haverá um tempo em que não vão suportar o ensinamento sadio,^&#42;1^ mas, de acordo com os seus próprios desejos, vão rodear-se de instrutores que lhes façam cócegas nos ouvidos.^&#42;2^

[NOTE]
====
. Ou: “salutar; benéfico”.
. Ou: “lhes digam o que querem ouvir”.
====

[[v55-4-4]]

^<<v55-4-4,4>>^ Desviarão os ouvidos da verdade e darão atenção a histórias falsas.

[[v55-4-5]]

^<<v55-4-5,5>>^ Tu, porém, mantém os sentidos em todas as coisas, suporta as dificuldades, faz a obra de um evangelizador,^&#42;1^ realiza plenamente o teu ministério.

[NOTE]
====
. Ou: “continua a pregar as boas novas”.
====

[[v55-4-6]]

^<<v55-4-6,6>>^ Pois eu já estou a ser derramado como oferta de bebida, e a hora da minha libertação está próxima.

[[v55-4-7]]

^<<v55-4-7,7>>^ Travei a boa luta, terminei a corrida, vivi de acordo com a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ De agora em diante, está-me reservada a coroa da justiça, que o Senhor, o justo juiz, me dará como recompensa no dia que há de vir; e não somente a mim, mas também a todos os que anseiam^&#42;1^ a sua manifestação.

[NOTE]
====
. Ou: “amam”.
====

[[v55-4-9]]

^<<v55-4-9,9>>^ Faz todos os possíveis para me visitares em breve.

[[v55-4-10]]

^<<v55-4-10,10>>^ Pois Demas abandonou-me, porque amava este mundo;^&#42;1^ ele foi para Tessalónica, Crescente para a Galácia, e Tito para a Dalmácia.

[NOTE]
====
. Ou: “o atual sistema de coisas; a época atual”. Veja o Glossário.
====

[[v55-4-11]]

^<<v55-4-11,11>>^ Apenas Lucas está comigo. Traz Marcos contigo, porque ele me é útil no ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Enviei Tíquico para Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando vieres, traz a capa que deixei em Tróade com Carpo, e também os rolos, especialmente os pergaminhos.^&#42;1^

[NOTE]
====
. Isto é, os rolos de couro.
====

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o fundidor de cobre, prejudicou-me muito. Jeová^&#42;1^ há de retribuir-lhe segundo as suas ações.

[NOTE]
====
. Veja o Ap. A5.
====

[[v55-4-15]]

^<<v55-4-15,15>>^ Tu também deves ter cuidado com ele, dado que ele se opôs fortemente à nossa mensagem.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na minha primeira defesa, ninguém ficou do meu lado, mas todos me abandonaram — que isto não lhes seja levado em conta.

[[v55-4-17]]

^<<v55-4-17,17>>^ No entanto, o Senhor ficou ao meu lado e fortaleceu-me, para que, por meu intermédio, se realizasse plenamente a pregação, e todas as nações a ouvissem; e fui salvo da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ O Senhor vai livrar-me de todo o mal e levar-me a salvo para o seu Reino celestial. A ele seja dada a glória para todo o sempre. Amém.

[[v55-4-19]]

^<<v55-4-19,19>>^ Transmite as minhas saudações a Prisca e a Áquila, e à família de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto, mas deixei Trófimo doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Faz todos os possíveis para chegar aqui antes do inverno.
Êubulo manda-te saudações, e também Pudente, Lino, Cláudia e todos os irmãos.

[[v55-4-22]]

^<<v55-4-22,22>>^ Que o Senhor esteja com o espírito que mostras. Que a bondade imerecida dele esteja convosco.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]