include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v55-3-1]]

^<<v55-3-1,1>>^ Porém, fica a saber que, nos últimos dias, haverá tempos críticos, difíceis de suportar.

[[v55-3-2]]

^<<v55-3-2,2>>^ Pois os homens serão extremamente egoístas,^&#42;1^ afeiçoados ao dinheiro, presunçosos, arrogantes, blasfemadores, desobedientes aos pais, ingratos, desleais,

[NOTE]
====
. Ou: “só gostarão de si mesmos”.
====

[[v55-3-3]]

^<<v55-3-3,3>>^ desnaturados,^&#42;1^ não estarão dispostos a acordos, serão caluniadores, sem autodomínio, ferozes, odiarão o que é bom,

[NOTE]
====
. Ou: “sem afeição natural”.
====

[[v55-3-4]]

^<<v55-3-4,4>>^ serão traidores, teimosos, cheios de orgulho, amarão os prazeres em vez de a Deus

[[v55-3-5]]

^<<v55-3-5,5>>^ e manterão uma aparência de devoção a Deus, mas rejeitarão o poder dessa devoção. Destes, afasta-te.

[[v55-3-6]]

^<<v55-3-6,6>>^ Dentre eles surgem homens que se introduzem ardilosamente nas famílias e seduzem mulheres fracas, sobrecarregadas de pecados, movidas por vários desejos,

[[v55-3-7]]

^<<v55-3-7,7>>^ as quais estão sempre a aprender, sem nunca conseguir chegar a um conhecimento exato da verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ Assim como Janes e Jambres se opuseram a Moisés, estes também continuam a opor-se à verdade. Estes homens têm a mente completamente corrompida e são reprovados quanto à fé.

[[v55-3-9]]

^<<v55-3-9,9>>^ Contudo, não vão muito longe, pois a sua tolice^&#42;1^ será bem evidente perante todos, como no caso daqueles dois homens.

[NOTE]
====
. Ou: “insensatez”.
====

[[v55-3-10]]

^<<v55-3-10,10>>^ Contudo, tu seguiste atentamente os meus ensinamentos, o meu proceder na vida, o meu propósito, a minha fé, a minha paciência, o meu amor, a minha perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ as minhas perseguições e os meus sofrimentos, como os que enfrentei em Antioquia, em Icónio, em Listra. Eu suportei estas perseguições, e o Senhor livrou-me de todas elas.

[[v55-3-12]]

^<<v55-3-12,12>>^ De facto, todos os que desejarem levar uma vida de devoção a Deus, em união com Cristo Jesus, também serão perseguidos.

[[v55-3-13]]

^<<v55-3-13,13>>^ No entanto, as pessoas más e os impostores vão tornar-se cada vez piores, enganando e sendo enganados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Tu, porém, continua nas coisas que aprendeste e foste persuadido a crer, pois sabes de quem as aprendeste

[[v55-3-15]]

^<<v55-3-15,15>>^ e que, desde a infância, conheces os escritos sagrados, que podem tornar-te sábio para a salvação, por meio da fé em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda a Escritura é inspirada por Deus e benéfica para ensinar, para repreender, para endireitar as coisas,^&#42;1^ para disciplinar em justiça,

[NOTE]
====
. Ou: “corrigir”.
====

[[v55-3-17]]

^<<v55-3-17,17>>^ a fim de que o homem de Deus seja plenamente competente, completamente equipado para toda a boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]