include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, segundo a promessa da vida que vem por meio de Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ a Timóteo, filho amado:
Que tenhas bondade imerecida, misericórdia e paz da parte de Deus, o Pai, e de Cristo Jesus, nosso Senhor.

[[v55-1-3]]

^<<v55-1-3,3>>^ Estou grato a Deus, a quem presto serviço sagrado como os meus antepassados e com uma consciência limpa, e nunca deixo de me lembrar de ti nas minhas súplicas, noite e dia.

[[v55-1-4]]

^<<v55-1-4,4>>^ Ao lembrar-me das tuas lágrimas, fico ansioso por te ver para me encher de alegria.

[[v55-1-5]]

^<<v55-1-5,5>>^ Pois recordo-me da tua fé sem hipocrisia, fé que houve primeiro na tua avó Loide e na tua mãe, Eunice, e que, com certeza, também há em ti.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por esta razão, quero lembrar-te de que atices, como um fogo, o dom de Deus que recebeste pela imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Pois Deus não nos deu um espírito de cobardia, mas de poder, de amor e de bom senso.

[[v55-1-8]]

^<<v55-1-8,8>>^ Assim, não te envergonhes do testemunho sobre o nosso Senhor, nem de mim, prisioneiro por causa dele. Porém, confiante no poder de Deus, participa em suportar sofrimentos pelas boas novas.

[[v55-1-9]]

^<<v55-1-9,9>>^ Ele salvou-nos e chamou-nos com uma chamada santa, não por causa das nossas obras, mas por causa do seu propósito e da sua bondade imerecida. Esta foi-nos concedida em Cristo Jesus antes dos tempos antigos,

[[v55-1-10]]

^<<v55-1-10,10>>^ mas agora tornou-se claramente evidente pela manifestação do nosso Salvador, Cristo Jesus. Ele aboliu a morte e, por meio das boas novas, lançou luz sobre a vida e a incorrupção.

[[v55-1-11]]

^<<v55-1-11,11>>^ Destas boas novas, fui designado pregador, apóstolo e instrutor.

[[v55-1-12]]

^<<v55-1-12,12>>^ É por isso que eu também sofro estas coisas, mas não me envergonho. Pois conheço Aquele em quem creio e estou confiante de que ele é capaz de guardar o que entreguei ao seu cuidado, até ao dia que há de vir.

[[v55-1-13]]

^<<v55-1-13,13>>^ Apega-te ao padrão^&#42;1^ de palavras sadias^&#42;2^ que ouviste de mim, com a fé e o amor que resultam da união com Cristo Jesus.

[NOTE]
====
. Ou: “esboço”.
. Ou: “salutares; benéficas”.
====

[[v55-1-14]]

^<<v55-1-14,14>>^ Guarda, por meio do espírito santo que mora em nós, esse precioso bem que te foi confiado.

[[v55-1-15]]

^<<v55-1-15,15>>^ Tu sabes que todos na província da Ásia se afastaram de mim, incluindo Figelo e Hermógenes.

[[v55-1-16]]

^<<v55-1-16,16>>^ Que o Senhor conceda misericórdia à família de Onesíforo, pois ele reanimou-me muitas vezes e não se envergonhou por eu estar preso.^&#42;1^

[NOTE]
====
. Ou: “das minhas correntes”.
====

[[v55-1-17]]

^<<v55-1-17,17>>^ Pelo contrário, quando ele esteve em Roma, procurou-me diligentemente e encontrou-me.

[[v55-1-18]]

^<<v55-1-18,18>>^ Que o Senhor lhe conceda encontrar misericórdia da parte de Jeová^&#42;1^ no dia que há de vir. E sabes bem quantos serviços ele prestou em Éfeso.

[NOTE]
====
. Veja o Ap. A5.
====

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]