include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras orava e fazia confissão, chorando prostrado diante da casa do verdadeiro Deus, uma grande multidão de israelitas — homens, mulheres e crianças — reuniu-se à sua volta; e o povo chorava muito.

[[v15-10-2]]

^<<v15-10-2,2>>^ Em vista disso, Secanias, filho de Jeiel, dos filhos de Elão, disse a Esdras: “Fomos infiéis ao nosso Deus, casando-nos com^&#42;1^ mulheres estrangeiras dos povos das terras ao redor. Apesar disso, ainda há esperança para Israel.

[NOTE]
====
. Ou: “acolhendo nas nossas casas”.
====

[[v15-10-3]]

^<<v15-10-3,3>>^ Agora, façamos um pacto com o nosso Deus para mandar embora todas as esposas e os seus filhos, conforme a orientação de Jeová e dos que temem o^&#42;1^ mandamento do nosso Deus. Vamos agir de acordo com a Lei.

[NOTE]
====
. Lit.: “tremem diante do”.
====

[[v15-10-4]]

^<<v15-10-4,4>>^ Levanta-te, pois este assunto é da tua responsabilidade, e nós vamos apoiar-te. Sê forte e age.”

[[v15-10-5]]

^<<v15-10-5,5>>^ Então, Esdras levantou-se e fez com que os chefes dos sacerdotes, os levitas e todo o Israel jurassem que agiriam de acordo com o que tinha sido dito. Assim, fizeram o juramento.

[[v15-10-6]]

^<<v15-10-6,6>>^ Esdras retirou-se de diante da casa do verdadeiro Deus e foi à sala^&#42;1^ de Jeoanã, filho de Eliasibe. Apesar de lá ir, não comeu pão nem bebeu água, em sinal de luto por causa da infidelidade do povo que tinha voltado do exílio.

[NOTE]
====
. Ou: “ao refeitório”.
====

[[v15-10-7]]

^<<v15-10-7,7>>^ De seguida, fizeram uma proclamação em Judá e Jerusalém para que todos os que tinham voltado do exílio se reunissem em Jerusalém;

[[v15-10-8]]

^<<v15-10-8,8>>^ e, segundo a decisão dos príncipes e dos anciãos, quem não chegasse no prazo de três dias teria todos os bens confiscados^&#42;1^ e seria expulso da congregação do povo que tinha voltado do exílio.

[NOTE]
====
. Ou: “postos sob interdição”.
====

[[v15-10-9]]

^<<v15-10-9,9>>^ Portanto, em três dias, isto é, no dia 20 do nono mês, todos os homens de Judá e de Benjamim se reuniram em Jerusalém. Todo o povo ficou sentado no pátio da casa do verdadeiro Deus, a tremer por causa daquele assunto e por causa da forte chuva.

[[v15-10-10]]

^<<v15-10-10,10>>^ Depois disso, Esdras, o sacerdote, levantou-se e disse-lhes: “Agiram de modo infiel, por se terem casado com mulheres estrangeiras, e assim aumentaram a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, confessem o vosso erro a Jeová, o Deus dos vossos antepassados, e façam a sua vontade. Separem-se dos povos das terras em vosso redor e das esposas estrangeiras.”

[[v15-10-12]]

^<<v15-10-12,12>>^ Em resposta, toda a congregação disse em voz alta: “Temos a obrigação de fazer exatamente o que está a dizer.

[[v15-10-13]]

^<<v15-10-13,13>>^ No entanto, há muita gente aqui e estamos na estação das chuvas. Não é possível ficar do lado de fora, e o assunto não será resolvido num dia ou dois, pois fomos muito rebeldes nesta questão.

[[v15-10-14]]

^<<v15-10-14,14>>^ Portanto, por favor, deixe que os nossos príncipes representem toda a congregação; e que todos os que estão nas nossas cidades que se tenham casado com mulheres estrangeiras se apresentem num dia determinado, com os anciãos e os juízes de cada cidade, até fazermos recuar a ira ardente do nosso Deus, causada por este assunto.”

[[v15-10-15]]

^<<v15-10-15,15>>^ No entanto, Jonatã, filho de Asael, e Jazeías, filho de Ticvá, opuseram-se, e os levitas Mesulão e Sabetai apoiaram-nos.

[[v15-10-16]]

^<<v15-10-16,16>>^ Porém, os que tinham voltado do exílio fizeram o que estava combinado; e Esdras, o sacerdote, e os cabeças das casas paternas, todos designados por nome, reuniram-se à parte, no primeiro dia do décimo mês, para investigar o assunto.

[[v15-10-17]]

^<<v15-10-17,17>>^ E, no primeiro dia do primeiro mês, terminaram de resolver todos os casos de homens que se tinham casado com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ E descobriu-se que alguns dos filhos dos sacerdotes se tinham casado com mulheres estrangeiras; dos filhos de Jesua, filho de Jeozadaque, e dos seus irmãos: Maaseias, Eliézer, Jaribe e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ Contudo, eles prometeram que mandariam^&#42;1^ embora as suas esposas e que, por serem culpados, ofereceriam um carneiro do rebanho pela sua culpa.

[NOTE]
====
. Lit.: “deram as suas mãos para mandar”.
====

[[v15-10-20]]

^<<v15-10-20,20>>^ Dos filhos de Imer, havia Hanani e Zebadias;

[[v15-10-21]]

^<<v15-10-21,21>>^ dos filhos de Harim: Maaseias, Elias, Semaías, Jeiel e Uzias;

[[v15-10-22]]

^<<v15-10-22,22>>^ e dos filhos de Pasur: Elioenai, Maaseias, Ismael, Netanel, Jozabade e Eleasá.

[[v15-10-23]]

^<<v15-10-23,23>>^ Dos levitas, havia Jozabade, Simei e Quelaías (isto é, Quelita), Petaías, Judá e Eliézer;

[[v15-10-24]]

^<<v15-10-24,24>>^ dos cantores: Eliasibe; e dos porteiros: Salum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ E dos israelitas, dos filhos de Parós, havia Ramias, Izias, Malquias, Miamim, Eleazar, Malquias e Benaia;

[[v15-10-26]]

^<<v15-10-26,26>>^ dos filhos de Elão: Matanias, Zacarias, Jeiel, Abdi, Jeremote e Elias;

[[v15-10-27]]

^<<v15-10-27,27>>^ dos filhos de Zatu: Elioenai, Eliasibe, Matanias, Jeremote, Zabade e Aziza;

[[v15-10-28]]

^<<v15-10-28,28>>^ dos filhos de Bebai: Jeoanã, Hananias, Zabai e Atlai;

[[v15-10-29]]

^<<v15-10-29,29>>^ dos filhos de Bani: Mesulão, Maluque, Adaías, Jasube, Seal e Jeremote;

[[v15-10-30]]

^<<v15-10-30,30>>^ dos filhos de Paate-Moabe: Adna, Quelal, Benaia, Maaseias, Matanias, Bezalel, Binui e Manassés;

[[v15-10-31]]

^<<v15-10-31,31>>^ dos filhos de Harim: Eliézer, Issias, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque e Semarias;

[[v15-10-33]]

^<<v15-10-33,33>>^ dos filhos de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei;

[[v15-10-34]]

^<<v15-10-34,34>>^ dos filhos de Bani: Maadai, Anrão, Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaia, Bedeias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matenai e Jaasu;

[[v15-10-38]]

^<<v15-10-38,38>>^ dos filhos de Binui: Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadebai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azarel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José;

[[v15-10-43]]

^<<v15-10-43,43>>^ e dos filhos de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos estes tinham tomado esposas estrangeiras, e eles mandaram-nas embora, a elas e aos filhos.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]