include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v15-1-1]]

^<<v15-1-1,1>>^ No primeiro ano de Ciro, rei da Pérsia, a fim de que se cumprisse a palavra de Jeová transmitida por Jeremias, Jeová despertou o espírito de Ciro, rei da Pérsia, para que ele fizesse em todo o seu reino uma proclamação, que ele também registou por escrito. Dizia o seguinte:

[[v15-1-2]]

^<<v15-1-2,2>>^ “Assim diz Ciro, rei da Pérsia: ‘Jeová, o Deus dos céus, deu-me todos os reinos da terra, e designou-me para lhe construir uma casa em Jerusalém, que fica em Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Quem dentre vocês pertencer ao seu povo, que o seu Deus esteja com ele. Portanto, que suba a Jerusalém, em Judá, e reconstrua a casa que ficava em Jerusalém, a casa de Jeová,^&#42;1^ o Deus de Israel, o verdadeiro Deus.

[NOTE]
====
. Ou, possivelmente: “reconstrua a casa de Jeová, aquele que está em Jerusalém”.
====

[[v15-1-4]]

^<<v15-1-4,4>>^ Que todo aquele que reside como estrangeiro, seja onde for, receba dos seus vizinhos^&#42;1^ prata, ouro, bens e animais, juntamente com a oferta voluntária para a casa do verdadeiro Deus, que ficava em Jerusalém.’”

[NOTE]
====
. Lit.: “dos homens do seu lugar”.
====

[[v15-1-5]]

^<<v15-1-5,5>>^ Então, os cabeças das casas paternas de Judá e de Benjamim, bem como os sacerdotes e os levitas — todos aqueles cujo espírito tinha sido despertado pelo verdadeiro Deus —, prepararam-se para ir reconstruir a casa de Jeová, que ficava em Jerusalém.

[[v15-1-6]]

^<<v15-1-6,6>>^ Todos os seus vizinhos os ajudaram, fornecendo-lhes^&#42;1^ utensílios de prata, de ouro, bens, animais e coisas valiosas, além de todas as ofertas voluntárias.

[NOTE]
====
. Lit.: “fortaleceram as suas mãos com”.
====

[[v15-1-7]]

^<<v15-1-7,7>>^ O rei Ciro também mandou que fossem buscar os utensílios da casa de Jeová que Nabucodonosor tinha tirado de Jerusalém e colocado na casa do seu deus.

[[v15-1-8]]

^<<v15-1-8,8>>^ Ciro, rei da Pérsia, colocou sob a supervisão de Mitredate, o tesoureiro, a tarefa de retirar os utensílios, e este fez um inventário de todos os objetos e entregou-os a Sesbazar,^&#42;1^ o maioral de Judá.

[NOTE]
====
. Possivelmente Zorobabel em Esdras 2:2; 3:8.
====

[[v15-1-9]]

^<<v15-1-9,9>>^ Este foi o inventário dos objetos: 30 recipientes de ouro em forma de cesto, 1000 recipientes de prata em forma de cesto e 29 recipientes sobresselentes,

[[v15-1-10]]

^<<v15-1-10,10>>^ além de 30 tigelas de ouro, 410 tigelas de prata e 1000 outros utensílios.

[[v15-1-11]]

^<<v15-1-11,11>>^ Todos os utensílios de ouro e de prata totalizaram 5400. Sesbazar levou tudo isto consigo quando os exilados saíram de Babilónia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]