include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v15-8-1]]

^<<v15-8-1,1>>^ Estes foram os cabeças das casas paternas e dos que foram alistados com eles, por família, que saíram comigo de Babilónia durante o reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ dos filhos de Fineias: Gérson; dos filhos de Itamar: Daniel; dos filhos de David: Hatus;

[[v15-8-3]]

^<<v15-8-3,3>>^ dos filhos de Secanias, dos filhos de Parós: Zacarias, e com ele 150 homens alistados;

[[v15-8-4]]

^<<v15-8-4,4>>^ dos filhos de Paate-Moabe: Elioenai, filho de Zeraías, e com ele 200 homens;

[[v15-8-5]]

^<<v15-8-5,5>>^ dos filhos de Zatu: Secanias, filho de Jaaziel, e com ele 300 homens;

[[v15-8-6]]

^<<v15-8-6,6>>^ dos filhos de Adim: Ebede, filho de Jonatã, e com ele 50 homens;

[[v15-8-7]]

^<<v15-8-7,7>>^ dos filhos de Elão: Jesaías, filho de Atalias, e com ele 70 homens;

[[v15-8-8]]

^<<v15-8-8,8>>^ dos filhos de Sefatias: Zebadias, filho de Micael, e com ele 80 homens;

[[v15-8-9]]

^<<v15-8-9,9>>^ dos filhos de Joabe: Obadias, filho de Jeiel, e com ele 218 homens;

[[v15-8-10]]

^<<v15-8-10,10>>^ dos filhos de Bani: Selomite, filho de Josifias, e com ele 160 homens;

[[v15-8-11]]

^<<v15-8-11,11>>^ dos filhos de Bebai: Zacarias, filho de Bebai, e com ele 28 homens;

[[v15-8-12]]

^<<v15-8-12,12>>^ dos filhos de Azgade: Joanã, filho de Hacatã, e com ele 110 homens;

[[v15-8-13]]

^<<v15-8-13,13>>^ dos filhos de Adonicão, os nomes dos que foram os últimos a voltar eram: Elifelete, Jeiel e Semaías, e com eles 60 homens;

[[v15-8-14]]

^<<v15-8-14,14>>^ e dos filhos de Bigvai: Utai e Zabude, e com eles 70 homens.

[[v15-8-15]]

^<<v15-8-15,15>>^ Reuni-os junto ao rio que corre para Aava, onde acampámos três dias. No entanto, quando inspecionei o povo e os sacerdotes, não encontrei nenhum levita.

[[v15-8-16]]

^<<v15-8-16,16>>^ Assim, mandei chamar Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, homens da liderança, e Joiaribe e Elnatã, que eram instrutores.

[[v15-8-17]]

^<<v15-8-17,17>>^ De seguida, enviei-os a Ido, o líder do lugar chamado Casifia. Eu disse-lhes para pedirem a Ido e aos seus irmãos, os servos do templo^&#42;1^ que estavam em Casifia, que nos trouxessem servos para a casa do nosso Deus.

[NOTE]
====
. Ou: “os netineus”. Lit.: “os que foram dados”.
====

[[v15-8-18]]

^<<v15-8-18,18>>^ Visto que a boa mão do nosso Deus estava sobre nós, trouxeram-nos um homem de bom critério^&#42;1^ dos filhos de Mali, neto de Levi, filho de Israel, a saber, Serebias, com os seus filhos e os seus irmãos, 18 homens;

[NOTE]
====
. Ou: “homem prudente”.
====

[[v15-8-19]]

^<<v15-8-19,19>>^ e também Hasabias, e com ele Jesaías, dos meraritas, com os seus irmãos e respetivos filhos, 20 homens.

[[v15-8-20]]

^<<v15-8-20,20>>^ E havia 220 servos do templo,^&#42;1^ que David e os príncipes deram para ajudar os levitas no seu serviço, todos designados por nome.

[NOTE]
====
. Ou: “netineus”. Lit.: “os que foram dados”.
====

[[v15-8-21]]

^<<v15-8-21,21>>^ Então, proclamei um jejum, junto ao rio Aava, para nos humilharmos diante do nosso Deus e para lhe pedirmos orientação para a viagem que faríamos com os nossos filhos e com todos os nossos bens.

[[v15-8-22]]

^<<v15-8-22,22>>^ Tive vergonha de pedir ao rei que providenciasse soldados e cavaleiros que nos protegessem dos inimigos pelo caminho, visto que tínhamos dito ao rei: “A boa mão do nosso Deus está sobre todos os que o procuram, mas a sua força e a sua ira estão contra todos os que o abandonam.”

[[v15-8-23]]

^<<v15-8-23,23>>^ Por isso, jejuámos e fizemos pedidos a este respeito ao nosso Deus, e ele ouviu as nossas súplicas.

[[v15-8-24]]

^<<v15-8-24,24>>^ Dentre os chefes dos sacerdotes, escolhi 12: Serebias, Hasabias e dez dos seus irmãos.

[[v15-8-25]]

^<<v15-8-25,25>>^ Pesei-lhes a prata, o ouro e os utensílios — a contribuição que o rei, os seus conselheiros, os seus príncipes e todos os israelitas que lá estavam tinham feito para a casa do nosso Deus.

[[v15-8-26]]

^<<v15-8-26,26>>^ Pesei e entreguei-lhes 650 talentos^&#42;1^ de prata, 100 utensílios de prata que pesavam 2 talentos, 100 talentos de ouro,

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v15-8-27]]

^<<v15-8-27,27>>^ além de 20 tigelas de ouro que valiam 1000 daricos^&#42;1^ e dois utensílios de cobre refinado, com brilho vermelho, preciosos como o ouro.

[NOTE]
====
. O darico era uma moeda persa de ouro. Veja o Ap. B14.
====

[[v15-8-28]]

^<<v15-8-28,28>>^ Eu disse-lhes então: “Vocês são santos para Jeová, e os utensílios são sagrados, e a prata e o ouro são uma oferta voluntária a Jeová, o Deus dos vossos antepassados.

[[v15-8-29]]

^<<v15-8-29,29>>^ Cuidem bem destas coisas até que as pesem nas salas^&#42;1^ da casa de Jeová, perante os chefes dos sacerdotes e dos levitas, e perante os príncipes das casas paternas de Israel, em Jerusalém.”

[NOTE]
====
. Ou: “nos refeitórios”.
====

[[v15-8-30]]

^<<v15-8-30,30>>^ E os sacerdotes e os levitas receberam a prata, o ouro e os utensílios que tinham sido pesados, a fim de levá-los para Jerusalém, para a casa do nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ Por fim, no dia 12 do primeiro mês, partimos do rio Aava para Jerusalém. A mão do nosso Deus estava sobre nós, e ele livrou-nos das mãos dos inimigos e das emboscadas pelo caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ Chegámos então a Jerusalém, onde permanecemos durante três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ E, no quarto dia, pesámos a prata, o ouro e os utensílios na casa do nosso Deus, e entregámo-los ao sacerdote Meremote, filho de Urias. Com ele estavam Eleazar, filho de Fineias, e os levitas Jozabade, filho de Jesua, e Noadias, filho de Binui.

[[v15-8-34]]

^<<v15-8-34,34>>^ Tudo foi contado e pesado, e o peso total foi registado.

[[v15-8-35]]

^<<v15-8-35,35>>^ Os que saíram do cativeiro, que retornaram do exílio, apresentaram sacrifícios queimados ao Deus de Israel: 12 novilhos por todo o Israel, 96 carneiros, 77 cordeiros e 12 bodes como oferta pelo pecado — tudo como oferta queimada a Jeová.

[[v15-8-36]]

^<<v15-8-36,36>>^ Então, entregámos os decretos do rei aos sátrapas^&#42;1^ do rei e aos governadores da região a oeste do rio Eufrates,^&#42;2^ e eles deram apoio ao povo e à casa do verdadeiro Deus.

[NOTE]
====
. Título que significa “protetores do reino”, aqui usado para se referir aos governadores das províncias no Império Persa.
. Ou: “região Além do Rio; região do Transeufrates”.
====

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]