include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v39-1-1]]

^<<v39-1-1,1>>^ Proclamação:
Esta é a palavra de Jeová a Israel por meio de Malaquias:^&#42;1^

[NOTE]
====
. Que significa “meu mensageiro”.
====

[[v39-1-2]]

^<<v39-1-2,2>>^ “Eu mostrei-vos amor”, diz Jeová.
Porém, vocês dizem: “Como é que nos mostraste amor?”
“Não era Esaú irmão de Jacó?”, diz Jeová. “No entanto, eu amei Jacó

[[v39-1-3]]

^<<v39-1-3,3>>^ e odiei Esaú; e fiz com que os seus montes ficassem desolados e entreguei a sua herança aos chacais do deserto.”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v39-1-4]]

^<<v39-1-4,4>>^ “Embora Edom diga: ‘Fomos arrasados, mas voltaremos e reconstruiremos as ruínas’, Jeová dos exércitos diz: ‘Eles construirão, mas eu derrubarei, e hão de chamar-lhes “território da maldade” e “o povo que Jeová condenou para sempre”.

[[v39-1-5]]

^<<v39-1-5,5>>^ Verão isso com os vossos próprios olhos e dirão: “Que Jeová seja magnificado sobre o território de Israel.”’”

[[v39-1-6]]

^<<v39-1-6,6>>^ “‘O filho honra o pai; e o servo, o seu senhor. Portanto, se eu sou o pai, onde está a honra que me devem? E, se eu sou o senhor,^&#42;1^ onde está o temor^&#42;2^ que me devem?’, diz-vos Jeová dos exércitos, a vocês, sacerdotes, que desprezam o meu nome.
“‘Contudo, vocês dizem: “Como é que desprezámos o teu nome?”’

[NOTE]
====
. Ou: “grandioso senhor”.
. Ou: “respeito”.
====

[[v39-1-7]]

^<<v39-1-7,7>>^ “‘Por apresentarem alimento^&#42;1^ impuro no meu altar.’
“‘E dizem: “Como é que te tornámos impuro?”’
“‘Por dizerem: “A mesa de Jeová é desprezível.”

[NOTE]
====
. Lit.: “pão”.
====

[[v39-1-8]]

^<<v39-1-8,8>>^ E, quando apresentam um animal cego como sacrifício, dizem: “Não faz mal.” E, quando apresentam um animal coxo ou doente, dizem: “Não faz mal.”’”
“Por favor, tenta apresentá-los ao teu governador. Será que ele vai ficar satisfeito contigo ou receber-te com favor?”, diz Jeová dos exércitos.

[[v39-1-9]]

^<<v39-1-9,9>>^ “E agora, por favor, apelem a^&#42;1^ Deus, para que ele nos mostre favor. Com essas ofertas das vossas mãos, será que ele receberá algum de vocês com favor?”, diz Jeová dos exércitos.

[NOTE]
====
. Ou: “abrandem a face de”.
====

[[v39-1-10]]

^<<v39-1-10,10>>^ “E quem entre vocês é que está disposto a fechar as portas?^&#42;1^ Pois vocês nem sequer acendem o meu altar sem cobrar por isso. Não me agrado de vocês”, diz Jeová dos exércitos, “nem tenho prazer em nenhuma oferta das vossas mãos”.

[NOTE]
====
. Pelos vistos, refere-se à tarefa de fechar as portas do templo.
====

[[v39-1-11]]

^<<v39-1-11,11>>^ “Pois o meu nome será grande entre as nações, desde o nascente até ao poente.^&#42;1^ Em todo o lado, irão queimar-se sacrifícios e fazer-se ofertas ao meu nome, como uma dádiva pura, porque o meu nome será grande entre as nações”, diz Jeová dos exércitos.

[NOTE]
====
. Ou: “de leste a oeste”.
====

[[v39-1-12]]

^<<v39-1-12,12>>^ “Porém, vocês profanam-no^&#42;1^ quando dizem: ‘A mesa de Jeová é impura, e as ofertas nela,^&#42;2^ o seu alimento, são desprezíveis.’

[NOTE]
====
. Ou, possivelmente: “profanam-me”.
. Ou: “e o seu fruto”.
====

[[v39-1-13]]

^<<v39-1-13,13>>^ Vocês também dizem: ‘Que cansativo!’ e mostram desprezo^&#42;1^ por ela”, diz Jeová dos exércitos. “E trazem animais roubados, coxos e doentes. Sim, trazem-nos como dádiva! Será que eu devo aceitá-la das vossas mãos?”, diz Jeová.

[NOTE]
====
. Lit.: “fungam”.
====

[[v39-1-14]]

^<<v39-1-14,14>>^ “Maldito seja aquele que é astuto, que tem no seu rebanho um animal macho sadio, mas faz um voto e sacrifica a Jeová um animal defeituoso. Pois eu sou um grande Rei”, diz Jeová dos exércitos, “e o meu nome inspirará temor entre as nações”.

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]