include::./index.adoc[]

[[v39-3-0]]
=== Malaquias, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v39-3-1]]

^<<v39-3-1,1>>^ “Vejam! Enviarei o meu mensageiro, e ele preparará^&#42;1^ o caminho diante de mim. E, de repente, o verdadeiro Senhor, a quem vocês procuram, virá ao Seu templo; e o mensageiro do pacto, de quem vocês se agradam, virá. Ele certamente virá”, diz Jeová dos exércitos.

[NOTE]
====
. Ou: “desobstruirá”.
====

[[v39-3-2]]

^<<v39-3-2,2>>^ “Porém, quem suportará o dia da sua vinda, e quem conseguirá manter-se de pé quando ele aparecer? Pois ele será como o fogo do refinador e como a barrela^&#42;1^ dos lavadeiros.

[NOTE]
====
. Ou: “o sabão”.
====

[[v39-3-3]]

^<<v39-3-3,3>>^ E ele irá sentar-se como um refinador e purificador de prata, e purificará os filhos de Levi; e irá depurá-los^&#42;1^ como o ouro e como a prata, e eles certamente irão tornar-se para Jeová pessoas que apresentam uma oferta em justiça.

[NOTE]
====
. Ou: “refiná-los”.
====

[[v39-3-4]]

^<<v39-3-4,4>>^ E a oferta de Judá e de Jerusalém será realmente agradável para Jeová, como nos dias do passado e como nos tempos antigos.

[[v39-3-5]]

^<<v39-3-5,5>>^ “Eu vou aproximar-me de vocês para vos julgar e darei prontamente testemunho contra os feiticeiros, contra os adúlteros, contra os que juram falsamente, contra os que defraudam o trabalhador contratado, a viúva e o órfão,^&#42;1^ e contra os que se recusam a ajudar o^&#42;2^ estrangeiro. Estes não me temem”, diz Jeová dos exércitos.

[NOTE]
====
. Ou: “órfão de pai”.
. Ou: “que negam os direitos do”.
====

[[v39-3-6]]

^<<v39-3-6,6>>^ “Pois eu sou Jeová; eu não mudo.^&#42;1^ E vocês são filhos de Jacó; ainda não chegaram ao vosso fim.

[NOTE]
====
. Ou: “não mudei”.
====

[[v39-3-7]]

^<<v39-3-7,7>>^ Desde os dias dos vossos antepassados, vocês têm-se desviado dos meus decretos e não os têm guardado. Voltem para mim, e eu voltarei para vocês”, diz Jeová dos exércitos.
Porém, vocês dizem: “Como é que havemos de voltar?”

[[v39-3-8]]

^<<v39-3-8,8>>^ “Será que um simples humano pode roubar a Deus? No entanto, vocês estão a roubar-me.”
E vocês dizem: “Como é que te roubámos?”
“Nos dízimos^&#42;1^ e nas contribuições.

[NOTE]
====
. Ou: “Nas décimas partes”.
====

[[v39-3-9]]

^<<v39-3-9,9>>^ Com certeza, vocês são amaldiçoados,^&#42;1^ pois estão a roubar-me — sim, a nação inteira está a fazer isso.

[NOTE]
====
. Ou, possivelmente: “Vocês estão a amaldiçoar-me com uma maldição”.
====

[[v39-3-10]]

^<<v39-3-10,10>>^ Tragam todos os dízimos^&#42;1^ ao depósito para que haja alimento na minha casa; e, por favor, ponham-me à prova neste respeito”, diz Jeová dos exércitos, “e vejam se eu não vos abrirei as comportas dos céus e se não derramarei^&#42;2^ sobre vocês uma bênção até que não falte mais nada”.

[NOTE]
====
. Ou: “todas as décimas partes”.
. Lit.: “esvaziarei”.
====

[[v39-3-11]]

^<<v39-3-11,11>>^ “E vou censurar o devorador,^&#42;1^ e ele não destruirá o fruto da vossa terra; e a videira no vosso campo não será infrutífera”, diz Jeová dos exércitos.

[NOTE]
====
. Aparentemente, refere-se a pragas de insetos.
====

[[v39-3-12]]

^<<v39-3-12,12>>^ “Todas as nações dirão que vocês são felizes, porque se tornarão uma terra de prazer”, diz Jeová dos exércitos.

[[v39-3-13]]

^<<v39-3-13,13>>^ “As vossas palavras contra mim foram fortes”, diz Jeová.
E vocês dizem: “Como é que falámos contra ti?”

[[v39-3-14]]

^<<v39-3-14,14>>^ “Vocês dizem: ‘É inútil servir a Deus. Qual é a vantagem de cumprirmos as nossas obrigações para com ele e de andarmos abatidos perante Jeová dos exércitos?

[[v39-3-15]]

^<<v39-3-15,15>>^ Agora, consideramos felizes os que são arrogantes. Além disso, os que praticam o que é mau são bem-sucedidos. Eles atrevem-se a pôr Deus à prova e conseguem safar-se.’”

[[v39-3-16]]

^<<v39-3-16,16>>^ Então, os que temiam a Jeová falavam uns com os outros, cada um com o seu próximo, e Jeová prestava atenção e escutava. E, perante ele, foi escrito um livro de recordação para os que temiam a Jeová e para os que meditavam no^&#42;1^ seu nome.

[NOTE]
====
. Ou: “pensavam no”. Ou, possivelmente: “entesouravam o”.
====

[[v39-3-17]]

^<<v39-3-17,17>>^ “Eles serão meus”, diz Jeová dos exércitos, “no dia em que eu produzir uma propriedade especial.^&#42;1^ Terei compaixão deles assim como um homem tem compaixão do seu filho, que o serve.

[NOTE]
====
. Ou: “estimada”.
====

[[v39-3-18]]

^<<v39-3-18,18>>^ E vocês verão novamente a diferença entre uma pessoa justa e uma pessoa má, entre quem serve a Deus e quem não o serve”.

'''

xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[Próximo Capítulo &#62;]