include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v39-2-1]]

^<<v39-2-1,1>>^ “E agora, ó sacerdotes, este mandamento é para vocês.

[[v39-2-2]]

^<<v39-2-2,2>>^ Se não escutarem e não levarem a sério o dever de glorificar o meu nome”, diz Jeová dos exércitos, “enviarei contra vocês a maldição e transformarei as vossas bênçãos em maldições. Sim, já transformei as bênçãos em maldições, porque vocês não levam isto a sério”.

[[v39-2-3]]

^<<v39-2-3,3>>^ “Vejam! Por vossa causa, destruirei^&#42;1^ a semente plantada, e espalharei esterco no vosso rosto, o esterco das vossas festividades; e vocês serão levados até ele.^&#42;2^

[NOTE]
====
. Lit.: “censurarei”.
. Isto é, até ao lugar onde o esterco dos sacrifícios era colocado.
====

[[v39-2-4]]

^<<v39-2-4,4>>^ Então, saberão que vos dei este mandamento para que o meu pacto com Levi continuasse em vigor”, diz Jeová dos exércitos.

[[v39-2-5]]

^<<v39-2-5,5>>^ “O meu pacto com ele foi um pacto de vida e paz, que lhe dei para que tivesse temor.^&#42;1^ Ele teve temor de mim, sim, teve reverência pelo meu nome.

[NOTE]
====
. Ou: “respeito; reverência”.
====

[[v39-2-6]]

^<<v39-2-6,6>>^ A lei^&#42;1^ da verdade estava na sua boca, e não havia injustiça nos seus lábios. Ele andava comigo em paz e retidão, e fez com que muitos recuassem do erro.

[NOTE]
====
. Ou: “instrução”.
====

[[v39-2-7]]

^<<v39-2-7,7>>^ Pois os lábios do sacerdote devem guardar o conhecimento, e da sua boca as pessoas devem procurar a lei,^&#42;1^ porque ele é o mensageiro de Jeová dos exércitos.

[NOTE]
====
. Ou: “instrução”.
====

[[v39-2-8]]

^<<v39-2-8,8>>^ “Contudo, vocês desviaram-se do caminho. Fizeram muitos tropeçar no que se refere à lei.^&#42;1^ Corromperam o pacto de Levi”, diz Jeová dos exércitos.

[NOTE]
====
. Ou, possivelmente: “por causa da vossa instrução”.
====

[[v39-2-9]]

^<<v39-2-9,9>>^ “Portanto, farei com que sejam desprezados e rebaixados diante de todo o povo, visto que não guardaram os meus caminhos, mas mostraram parcialidade ao aplicar a lei.”

[[v39-2-10]]

^<<v39-2-10,10>>^ “Não temos todos nós um só pai? Não foi um só Deus que nos criou? Então, porque é que somos traiçoeiros uns para com os outros, profanando o pacto dos nossos antepassados?

[[v39-2-11]]

^<<v39-2-11,11>>^ Judá agiu traiçoeiramente, e fez-se uma coisa detestável em Israel e em Jerusalém; porque Judá profanou a santidade^&#42;1^ de Jeová, a qual Ele ama, e casou-se com a filha de um deus estrangeiro.

[NOTE]
====
. Ou, possivelmente: “o santuário”.
====

[[v39-2-12]]

^<<v39-2-12,12>>^ Jeová eliminará das tendas de Jacó todo aquele que faz isso — não importa quem seja^&#42;1^ — mesmo que ele apresente uma oferta a Jeová dos exércitos.”

[NOTE]
====
. Lit.: “aquele que está desperto e aquele que responde”.
====

[[v39-2-13]]

^<<v39-2-13,13>>^ “E vocês fazem outra^&#42;1^ coisa que deixa o altar de Jeová coberto de lágrimas, de choro e de suspiros, de modo que ele já não dá atenção à vossa oferta nem olha com favor para nada que venha das vossas mãos.

[NOTE]
====
. Lit.: “uma segunda”.
====

[[v39-2-14]]

^<<v39-2-14,14>>^ E dizem: ‘Por que razão?’ Porque Jeová é testemunha entre ti e a esposa da tua juventude, com quem foste traiçoeiro, embora ela fosse tua companheira e tua esposa por meio de um pacto.^&#42;1^

[NOTE]
====
. Ou: “por lei”.
====

[[v39-2-15]]

^<<v39-2-15,15>>^ No entanto, houve um que não fez isso, visto que tinha o que restava do espírito. E o que é que ele visava? A descendência^&#42;1^ de Deus. Portanto, estejam atentos ao vosso espírito e não ajam traiçoeiramente com a esposa da vossa juventude.

[NOTE]
====
. Lit.: “semente”.
====

[[v39-2-16]]

^<<v39-2-16,16>>^ Pois eu odeio^&#42;1^ o divórcio”, diz Jeová, o Deus de Israel, “e também aquele que cobre a sua roupa com violência”,^&#42;2^ diz Jeová dos exércitos. “Estejam atentos ao vosso espírito e não ajam traiçoeiramente.

[NOTE]
====
. Lit.: “ele odeia”.
. Ou: “que se envolve em violência”.
====

[[v39-2-17]]

^<<v39-2-17,17>>^ “Vocês cansam a Jeová com as vossas palavras. Contudo, dizem: ‘Como é que o cansamos?’ Por dizerem: ‘Todo aquele que faz o mal é bom aos olhos de Jeová, e ele agrada-se dele’; ou por dizerem: ‘Onde é que está o Deus da justiça?’”

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]