include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_א &#91;álefe&#93;^&#42;1^_

[[v25-1-1]]

^<<v25-1-1,1>>^ Como ela está solitária, a cidade que antes estava tão cheia de gente!
Aquela que era populosa entre as nações tornou-se como uma viúva.
Aquela que era princesa entre as províncias^&#42;1^ foi sujeita a trabalhos forçados.

[NOTE]
====
. Ou: “os distritos jurisdicionais”.
====

_ב &#91;bete&#93;_

[[v25-1-2]]

^<<v25-1-2,2>>^ Ela chora muito durante a noite, e as suas lágrimas correm-lhe pelo rosto.
De todos os seus amantes, não ficou nenhum para consolá-la.
Todos os seus companheiros a traíram; tornaram-se seus inimigos.

_ג &#91;guímel&#93;_

[[v25-1-3]]

^<<v25-1-3,3>>^ Judá foi para o exílio debaixo de aflição e de dura escravidão.
Ela tem de morar entre as nações; não encontra nenhum lugar de descanso.
Todos os seus perseguidores a alcançaram quando ela estava aflita.

_ד &#91;dálete&#93;_

[[v25-1-4]]

^<<v25-1-4,4>>^ As estradas para Sião estão de luto, porque ninguém vem às festividades.
Todos os seus portões ficaram desolados; os seus sacerdotes gemem.
As suas moças^&#42;1^ estão desconsoladas, e ela sofre amargamente.

[NOTE]
====
. Lit.: “virgens”.
====

_ה &#91;hê&#93;_

[[v25-1-5]]

^<<v25-1-5,5>>^ Os seus adversários são agora o seu senhor;^&#42;1^ os seus inimigos estão despreocupados.
Pois Jeová trouxe-lhe pesar por causa das suas muitas transgressões.
As suas crianças foram para o cativeiro diante do adversário.

[NOTE]
====
. Lit.: “cabeça”.
====

_ו &#91;vau&#93;_

[[v25-1-6]]

^<<v25-1-6,6>>^ Todo o esplendor da filha de Sião desapareceu.
Os seus príncipes são como veados que não têm pasto
E caminham exaustos diante do perseguidor.

_ז &#91;zaine&#93;_

[[v25-1-7]]

^<<v25-1-7,7>>^ Nestes dias, em que está aflita e sem lar, Jerusalém lembra-se
De todas as coisas preciosas que eram suas nos tempos antigos.
Quando o seu povo caiu nas mãos do adversário e ninguém a veio ajudar,
Os adversários viram-na e riram-se da^&#42;1^ sua queda.

[NOTE]
====
. Ou: “e alegraram-se com a”.
====

_ח &#91;hete&#93;_

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalém pecou gravemente.
Por isso, tornou-se uma coisa abominável.
Todos os que a honravam tratam-na agora com desprezo, pois viram a sua nudez.
Ela própria geme e afasta-se, envergonhada.

_ט &#91;tete&#93;_

[[v25-1-9]]

^<<v25-1-9,9>>^ A sua impureza está nas suas saias.
Ela não pensou no seu futuro.
A sua queda foi espantosa; ela não tem quem a console.
Ó Jeová, vê a minha aflição, pois o inimigo enalteceu-se.

_י &#91;iode&#93;_

[[v25-1-10]]

^<<v25-1-10,10>>^ O adversário deitou as mãos a todos os seus tesouros.
Ela viu nações a entrarem no seu santuário,
As quais proibiste de entrar na tua congregação.

_כ &#91;cafe&#93;_

[[v25-1-11]]

^<<v25-1-11,11>>^ Todo o seu povo geme; estão à procura de pão.
Deram as suas coisas preciosas em troca de algo para comer, só para continuarem vivos.^&#42;1^
Olha, Jeová, e vê como me tornei uma mulher^&#42;2^ sem valor.

[NOTE]
====
. Ou: “para restaurarem a alma”.
. Personificação de Jerusalém.
====

_ל &#91;lâmede&#93;_

[[v25-1-12]]

^<<v25-1-12,12>>^ Será que isso não significa nada para nenhum de vocês que passam pela estrada?
Olhem e vejam!
Existe alguma dor igual à dor com que fui punida,
A dor que Jeová me fez sentir no dia da sua ira ardente?

_מ &#91;meme&#93;_

[[v25-1-13]]

^<<v25-1-13,13>>^ Do alto ele enviou um fogo para dentro dos meus ossos, e domina cada um deles.
Estendeu uma rede para os meus pés; forçou-me a voltar para trás.
Fez de mim uma mulher abandonada.
Estou doente o dia inteiro.

_נ &#91;nune&#93;_

[[v25-1-14]]

^<<v25-1-14,14>>^ As minhas transgressões estão amarradas como um jugo, atadas pelas suas mãos.
Foram-me colocadas ao pescoço, e as minhas forças esgotaram-se.
Jeová entregou-me nas mãos daqueles a quem não posso vencer.

_ס &#91;sâmeque&#93;_

[[v25-1-15]]

^<<v25-1-15,15>>^ Jeová lançou para fora todos os guerreiros que havia no meu meio.
Convocou uma multidão contra mim para esmagar os meus jovens.
Jeová pisou a filha virgem de Judá no lagar de vinho.

_ע &#91;aine&#93;_

[[v25-1-16]]

^<<v25-1-16,16>>^ Choro por causa destas coisas; escorrem-me lágrimas dos olhos.
Pois está longe de mim quem me poderia consolar ou reanimar.^&#42;1^
Os meus filhos ficaram desolados, pois o inimigo venceu.

[NOTE]
====
. Ou: “ou reanimar a minha alma”.
====

_פ &#91;pê&#93;_

[[v25-1-17]]

^<<v25-1-17,17>>^ Sião estendeu as mãos; ela não tem quem a console.
Jeová mandou contra Jacó todos os adversários ao seu redor.
Jerusalém tornou-se uma coisa abominável para eles.

_צ &#91;tsadê&#93;_

[[v25-1-18]]

^<<v25-1-18,18>>^ Jeová é justo, pois foi contra as suas ordens^&#42;1^ que eu me rebelei.
Ouçam, todos os povos, e vejam a minha dor.
As minhas moças^&#42;2^ e os meus rapazes foram para o cativeiro.

[NOTE]
====
. Lit.: “a sua boca”.
. Lit.: “virgens”.
====

_ק &#91;cofe&#93;_

[[v25-1-19]]

^<<v25-1-19,19>>^ Chamei os meus amantes, mas eles traíram-me.
Os meus sacerdotes e os meus anciãos morreram na cidade,
Enquanto procuravam alimento para permanecerem vivos.^&#42;1^

[NOTE]
====
. Ou: “para restaurarem a alma”.
====

_ר &#91;rexe&#93;_

[[v25-1-20]]

^<<v25-1-20,20>>^ Vê, ó Jeová, como estou em grande aflição.
As minhas entranhas^&#42;1^ estão em alvoroço.
O meu coração ficou angustiado no meu íntimo, pois fui muito rebelde.
Do lado de fora, a espada mata; dentro de casa, é como a morte.

[NOTE]
====
. Lit.: “Os meus intestinos”.
====

_ש &#91;chim&#93;_

[[v25-1-21]]

^<<v25-1-21,21>>^ As pessoas ouvem os meus gemidos; não há quem me console.
Todos os meus inimigos ouviram falar da minha calamidade.
Eles estão alegres, porque tu a causaste.
Mas tu farás chegar o dia por ti proclamado em que eles ficarão como eu.

_ת &#91;tau&#93;_

[[v25-1-22]]

^<<v25-1-22,22>>^ Que toda a sua maldade chegue à tua presença, e que tu os trates com severidade,
Assim como me trataste com severidade por causa de todas as minhas transgressões.
Pois muitos são os meus gemidos, e o meu coração está doente.

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]