include::./index.adoc[]

[[v25-4-0]]
=== Lamentações, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_א &#91;álefe&#93;_

[[v25-4-1]]

^<<v25-4-1,1>>^ Como ficou baço o ouro brilhante, o ouro puro!
As pedras do santuário^&#42;1^ estão espalhadas em todas as esquinas.^&#42;2^

[NOTE]
====
. Ou: “pedras sagradas”.
. Lit.: “na cabeça de todas as ruas”.
====

_ב &#91;bete&#93;_

[[v25-4-2]]

^<<v25-4-2,2>>^ Os filhos preciosos de Sião, que valiam o seu peso em^&#42;1^ ouro refinado,
São tratados como vasos de barro,
Trabalho das mãos de um oleiro!

[NOTE]
====
. Ou: “que eram preciosos como”.
====

_ג &#91;guímel&#93;_

[[v25-4-3]]

^<<v25-4-3,3>>^ Até mesmo os chacais dão de mamar às suas crias.
Mas a filha do meu povo tornou-se cruel, como as avestruzes no deserto.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

_ד &#91;dálete&#93;_

[[v25-4-4]]

^<<v25-4-4,4>>^ A língua da criança de peito está pegada ao céu da boca por causa da sede.
As crianças imploram por pão, mas ninguém lhes dá nada.

_ה &#91;hê&#93;_

[[v25-4-5]]

^<<v25-4-5,5>>^ Os que comiam iguarias caem de fome^&#42;1^ pelas ruas.
Os que cresceram a vestir roupas finas^&#42;2^ deitam-se em montes de cinzas.

[NOTE]
====
. Lit.: “estão desolados”.
. Lit.: “cresceram em escarlate”.
====

_ו &#91;vau&#93;_

[[v25-4-6]]

^<<v25-4-6,6>>^ A punição^&#42;1^ da filha do meu povo é maior do que a punição pelo pecado de Sodoma,
Que foi destruída num instante, sem que ninguém lhe desse a mão para ajudá-la.

[NOTE]
====
. Lit.: “O erro”.
====

_ז &#91;zaine&#93;_

[[v25-4-7]]

^<<v25-4-7,7>>^ Os seus nazireus eram mais puros do que a neve, mais brancos do que o leite.
Eram mais corados do que corais; eram como safiras polidas.

_ח &#91;hete&#93;_

[[v25-4-8]]

^<<v25-4-8,8>>^ A sua aparência ficou mais escura do que a fuligem.^&#42;1^
São irreconhecíveis nas ruas.
A sua pele enrugou-se sobre os seus ossos; ficou seca como lenha.

[NOTE]
====
. Lit.: “o negrume”.
====

_ט &#91;tete&#93;_

[[v25-4-9]]

^<<v25-4-9,9>>^ Os mortos pela espada estão melhor do que os mortos pela fome,
Os que morrem lentamente, vítimas da^&#42;1^ falta do alimento produzido nos campos.

[NOTE]
====
. Ou: “trespassados pela”.
====

_י &#91;iode&#93;_

[[v25-4-10]]

^<<v25-4-10,10>>^ As mãos de mulheres compassivas cozinharam os seus próprios filhos.
Eles tornaram-se o seu alimento^&#42;1^ durante a ruína da filha do meu povo.

[NOTE]
====
. Ou: “o seu pão de luto”.
====

_כ &#91;cafe&#93;_

[[v25-4-11]]

^<<v25-4-11,11>>^ Jeová expressou o seu furor;
Derramou a sua ira ardente.
E ele acende um fogo em Sião, que consome os seus alicerces.

_ל &#91;lâmede&#93;_

[[v25-4-12]]

^<<v25-4-12,12>>^ Os reis da terra e todos os seus habitantes^&#42;1^ não acreditavam
Que o adversário e o inimigo entrariam pelos portões de Jerusalém.

[NOTE]
====
. Ou: “habitantes da terra produtiva”.
====

_מ &#91;meme&#93;_

[[v25-4-13]]

^<<v25-4-13,13>>^ Isto aconteceu por causa dos pecados dos seus profetas e dos erros dos seus sacerdotes,
Que derramaram o sangue dos justos no meio dela.

_נ &#91;nune&#93;_

[[v25-4-14]]

^<<v25-4-14,14>>^ Eles vagueiam pelas ruas como cegos.
O sangue deixou-os impuros,
De modo que ninguém lhes pode tocar nas roupas.

_ס &#91;sâmeque&#93;_

[[v25-4-15]]

^<<v25-4-15,15>>^ “Vão-se embora! Impuros!”, gritam-lhes. “Vão-se embora! Vão-se embora! Não nos toquem!”
Pois ficaram sem lar e vagueiam.
As pessoas das nações disseram: “Eles não podem ficar aqui connosco.^&#42;1^

[NOTE]
====
. Ou: “morar aqui como estrangeiros”.
====

_פ &#91;pê&#93;_

[[v25-4-16]]

^<<v25-4-16,16>>^ A face de Jeová espalhou-os;
Ele não voltará a olhar para eles com favor.
Os homens não terão respeito pelos sacerdotes, nem mostrarão favor aos anciãos.”

_ע &#91;aine&#93;_

[[v25-4-17]]

^<<v25-4-17,17>>^ Os nossos olhos continuam cansados de procurar ajuda em vão.
Procurámos e procurámos ajuda de uma nação que não nos podia salvar.

_צ &#91;tsadê&#93;_

[[v25-4-18]]

^<<v25-4-18,18>>^ Cada passo nosso era vigiado, de modo que não podíamos andar nas nossas praças.
O nosso fim está próximo; os nossos dias terminaram, pois chegou o nosso fim.

_ק &#91;cofe&#93;_

[[v25-4-19]]

^<<v25-4-19,19>>^ Os nossos perseguidores eram mais velozes do que as águias do céu.
Eles perseguiam-nos pelos montes; armavam-nos emboscadas no deserto.

_ר &#91;rexe&#93;_

[[v25-4-20]]

^<<v25-4-20,20>>^ O ungido de Jeová, o fôlego das nossas narinas, foi capturado na grande cova deles;
Dizíamos a seu respeito: “À sua sombra, viveremos entre as nações.”

_ש &#91;sim&#93;_

[[v25-4-21]]

^<<v25-4-21,21>>^ Exulta e alegra-te, ó filha de Edom, que moras na terra de Uz.
No entanto, tu também receberás o cálice, ficarás embriagada e exporás a tua nudez.

_ת &#91;tau&#93;_

[[v25-4-22]]

^<<v25-4-22,22>>^ A punição pelo teu erro, ó filha de Sião, chegou ao fim.
Deus não te levará novamente para o exílio.
Porém, ele voltará a sua atenção para o teu erro, ó filha de Edom.
Ele exporá os teus pecados.

'''

xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[Próximo Capítulo &#62;]