include::./index.adoc[]

[[v5-18-0]]
=== Deuteronómio, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-18-1]]

^<<v5-18-1,1>>^ “Nem os sacerdotes levíticos nem mesmo a inteira tribo de Levi receberão uma porção ou uma herança com Israel. Comerão das ofertas feitas por fogo a Jeová, que são a herança dele.

[[v5-18-2]]

^<<v5-18-2,2>>^ Por isso, não devem ter nenhuma herança no meio dos seus irmãos. Jeová é a sua herança, assim como lhes disse.

[[v5-18-3]]

^<<v5-18-3,3>>^ “Isto é o que os sacerdotes terão o direito de receber do povo: quem fizer um sacrifício, quer seja um touro, quer seja uma ovelha, deve dar ao sacerdote a espádua, as mandíbulas e o bucho.

[[v5-18-4]]

^<<v5-18-4,4>>^ Deves dar-lhe as primícias dos teus cereais, do teu vinho novo e do teu azeite, e a primeira lã tosquiada do teu rebanho.

[[v5-18-5]]

^<<v5-18-5,5>>^ Jeová, teu Deus, escolheu-o a ele e aos seus filhos dentre todas as tuas tribos para servir em nome de Jeová para sempre.

[[v5-18-6]]

^<<v5-18-6,6>>^ “Mas, se um levita sair de uma das cidades de Israel onde estava a morar e ele^&#42;1^ quiser ir ao lugar que Jeová escolher,^&#42;2^

[NOTE]
====
. Ou: “a sua alma”.
. Isto é, o lugar que Jeová escolher como centro de adoração.
====

[[v5-18-7]]

^<<v5-18-7,7>>^ poderá servir ali em nome de Jeová, seu Deus, assim como todos os seus irmãos, os levitas, que estiverem ali perante Jeová.

[[v5-18-8]]

^<<v5-18-8,8>>^ Receberá uma porção de alimento igual à deles, além do que receber com a venda dos bens dos seus antepassados.

[[v5-18-9]]

^<<v5-18-9,9>>^ “Quando tiveres entrado na terra que Jeová, teu Deus, te dá, não deves aprender a imitar as práticas detestáveis dessas nações.

[[v5-18-10]]

^<<v5-18-10,10>>^ Não se deve encontrar no teu meio alguém que queime o seu filho ou a sua filha no fogo,^&#42;1^ ou que empregue adivinhação, ou que pratique magia, ou que procure presságios,^&#42;2^ ou um feiticeiro,

[NOTE]
====
. Lit.: “faça o seu filho ou filha passar pelo fogo”.
. Ou: “sinais”.
====

[[v5-18-11]]

^<<v5-18-11,11>>^ ou alguém que prenda outros com encantamento, ou que consulte quem invoca espíritos, ou um adivinho, ou alguém que consulte os mortos.

[[v5-18-12]]

^<<v5-18-12,12>>^ Pois quem faz estas coisas é detestável para Jeová, e é por causa destas práticas detestáveis que Jeová, teu Deus, expulsa estas nações de diante de ti.

[[v5-18-13]]

^<<v5-18-13,13>>^ Deves mostrar-te irrepreensível perante Jeová, teu Deus.

[[v5-18-14]]

^<<v5-18-14,14>>^ “Pois estas nações que vais expulsar escutam os que praticam magia e adivinhação, mas Jeová, teu Deus, não te permitiu fazer nada disso.

[[v5-18-15]]

^<<v5-18-15,15>>^ Jeová, teu Deus, escolherá para ti, dentre os teus irmãos, um profeta semelhante a mim; vocês devem escutá-lo.

[[v5-18-16]]

^<<v5-18-16,16>>^ Pois foi isto que pediste a Jeová, teu Deus, em Horebe, no dia em que a assembleia estava reunida,^&#42;1^ quando disseste: ‘Que eu não volte a ouvir a voz de Jeová, meu Deus, nem volte a ver este grande fogo, para que não morra.’

[NOTE]
====
. Ou: “no dia da congregação”.
====

[[v5-18-17]]

^<<v5-18-17,17>>^ Então, Jeová disse-me: ‘O que eles disseram é bom.

[[v5-18-18]]

^<<v5-18-18,18>>^ Farei com que lhes surja, dentre os seus irmãos, um profeta semelhante a ti, e porei as minhas palavras na sua boca, e ele irá transmitir-vos tudo o que eu mandar.

[[v5-18-19]]

^<<v5-18-19,19>>^ De facto, exigirei uma prestação de contas do homem que não escutar as minhas palavras, que ele disser em meu nome.

[[v5-18-20]]

^<<v5-18-20,20>>^ “‘Se um profeta presunçosamente disser em meu nome alguma palavra que eu não lhe mandei dizer ou falar em nome de outros deuses, esse profeta morrerá.

[[v5-18-21]]

^<<v5-18-21,21>>^ Mas talvez digas no teu coração: “Como é que saberemos que Jeová não disse essas palavras?”

[[v5-18-22]]

^<<v5-18-22,22>>^ Quando o profeta falar em nome de Jeová e o que ele disser não acontecer nem se cumprir, então, Jeová não proferiu tais palavras. O profeta proferiu-as presunçosamente. Não deves ficar com medo dele.’

'''

xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[Próximo Capítulo &#62;]