include::./index.adoc[]

[[v5-14-0]]
=== Deuteronómio, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-14-1]]

^<<v5-14-1,1>>^ “Vocês são filhos de Jeová, vosso Deus. Não se cortem, nem rapem a parte da frente da cabeça^&#42;1^ por causa de um morto.

[NOTE]
====
. Lit.: “não ponham (façam) calvície entre os vossos olhos”.
====

[[v5-14-2]]

^<<v5-14-2,2>>^ Pois tu és um povo santo para Jeová, teu Deus; Jeová escolheu-te para te tornares o seu povo, a sua propriedade especial^&#42;1^ dentre todos os povos que há na face da terra.

[NOTE]
====
. Ou: “estimada”.
====

[[v5-14-3]]

^<<v5-14-3,3>>^ “Não comas nada que seja detestável.

[[v5-14-4]]

^<<v5-14-4,4>>^ Estes são os animais que podem comer: o boi, a ovelha, a cabra,

[[v5-14-5]]

^<<v5-14-5,5>>^ o veado, a gazela, o corço, a cabra-montesa, o antílope, a ovelha selvagem e a ovelha-montesa.

[[v5-14-6]]

^<<v5-14-6,6>>^ Podem comer qualquer animal de casco fendido, dividido em dois, e que rumina.

[[v5-14-7]]

^<<v5-14-7,7>>^ Contudo, não comam os seguintes animais que ruminam ou têm o casco fendido: o camelo, a lebre e o procávia,^&#42;1^ porque são ruminantes, mas não têm o casco fendido. São impuros para vocês.

[NOTE]
====
. Animal semelhante ao coelho e que vive em lugares rochosos. Também é chamado hírace (hírax) ou damão.
====

[[v5-14-8]]

^<<v5-14-8,8>>^ Também o porco, porque tem o casco fendido, mas não rumina. É impuro para vocês. Não comam a carne desses animais, nem toquem nos seus cadáveres.

[[v5-14-9]]

^<<v5-14-9,9>>^ “De tudo o que vive nas águas, podem comer o seguinte: podem comer tudo o que tem barbatanas e escamas.

[[v5-14-10]]

^<<v5-14-10,10>>^ Mas não comam nada que não tenha barbatanas ou escamas. São impuros para vocês.

[[v5-14-11]]

^<<v5-14-11,11>>^ “Podem comer qualquer ave pura.

[[v5-14-12]]

^<<v5-14-12,12>>^ Mas não comam as seguintes: a águia, a águia-pesqueira, o abutre-preto,

[[v5-14-13]]

^<<v5-14-13,13>>^ o milhafre-real, o milhafre-preto e todas as outras espécies^&#42;1^ de milhafre,

[NOTE]
====
. Ou: “todos os outros tipos”.
====

[[v5-14-14]]

^<<v5-14-14,14>>^ toda a espécie^&#42;1^ de corvos,

[NOTE]
====
. Ou: “todo o tipo”.
====

[[v5-14-15]]

^<<v5-14-15,15>>^ a avestruz, a coruja, a gaivota, toda a espécie^&#42;1^ de falcões,

[NOTE]
====
. Ou: “todo o tipo”.
====

[[v5-14-16]]

^<<v5-14-16,16>>^ o mocho-galego, o bufo-pequeno, o cisne,

[[v5-14-17]]

^<<v5-14-17,17>>^ o pelicano, o abutre, o corvo-marinho,

[[v5-14-18]]

^<<v5-14-18,18>>^ a cegonha, toda a espécie^&#42;1^ de garças, a poupa e o morcego.

[NOTE]
====
. Ou: “todo o tipo”.
====

[[v5-14-19]]

^<<v5-14-19,19>>^ Todas as pequenas criaturas voadoras que fervilham sobre a terra^&#42;1^ também são impuras para vocês. Não devem ser comidas.

[NOTE]
====
. Ou: “Todos os insetos”.
====

[[v5-14-20]]

^<<v5-14-20,20>>^ Mas podem comer qualquer criatura voadora pura.

[[v5-14-21]]

^<<v5-14-21,21>>^ “Não comam nenhum animal encontrado morto. Podes dá-lo ao residente estrangeiro que mora nas tuas cidades,^&#42;1^ e ele pode comê-lo; ou podes vendê-lo a um estrangeiro. Pois és um povo santo para Jeová, teu Deus.
“Não cozinhes o cabrito no leite da própria mãe.

[NOTE]
====
. Ou: “nos teus portões”.
====

[[v5-14-22]]

^<<v5-14-22,22>>^ “Sem falta, deves dar um décimo^&#42;1^ de tudo o que a tua semente produzir no campo, ano após ano.

[NOTE]
====
. Ou: “dízimo”.
====

[[v5-14-23]]

^<<v5-14-23,23>>^ Comerás a décima parte dos teus cereais, do teu vinho novo e do teu azeite, e os primogénitos da tua manada e do teu rebanho perante Jeová, teu Deus, no lugar que ele escolher para ali fazer residir o seu nome, para que aprendas a temer a Jeová, teu Deus, para sempre.

[[v5-14-24]]

^<<v5-14-24,24>>^ “Mas, se a viagem for demasiado longa, e não puderes carregar todas essas coisas para o lugar que Jeová, teu Deus, escolher para ali colocar o seu nome, visto que o lugar fica muito distante (pois Jeová, teu Deus, te abençoará),

[[v5-14-25]]

^<<v5-14-25,25>>^ então, podes convertê-las em dinheiro e viajar com o dinheiro na mão para o lugar que Jeová, teu Deus, escolher.

[[v5-14-26]]

^<<v5-14-26,26>>^ E, com o dinheiro, podes comprar tudo o que tu desejares:^&#42;1^ bois, ovelhas, cabras, vinho e outras bebidas alcoólicas, e tudo o que quiseres;^&#42;2^ e comerás ali perante Jeová, teu Deus, e irás alegrar-te, tu e os da tua casa.

[NOTE]
====
. Ou: “a tua alma desejar”.
. Ou: “tudo o que a tua alma pedir de ti”.
====

[[v5-14-27]]

^<<v5-14-27,27>>^ E não negligencies o levita que está dentro das tuas cidades, pois ele não recebeu uma porção ou uma herança contigo.

[[v5-14-28]]

^<<v5-14-28,28>>^ “Ao fim de cada três anos, deves trazer todas as décimas partes dos teus produtos daquele ano e depositá-las dentro das tuas cidades.

[[v5-14-29]]

^<<v5-14-29,29>>^ Então, o levita, que não recebeu uma porção ou uma herança contigo, o residente estrangeiro, o órfão^&#42;1^ e a viúva que estão nas tuas cidades virão e comerão até ficarem satisfeitos, para que Jeová, teu Deus, te abençoe em tudo o que fizeres.

[NOTE]
====
. Ou: “órfão de pai”.
====

'''

xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[Próximo Capítulo &#62;]