include::./index.adoc[]

[[v5-32-0]]
=== Deuteronómio, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-32-1]]

^<<v5-32-1,1>>^ “Deem ouvidos, ó céus, e eu vou falar;
E que a terra ouça as palavras da minha boca.

[[v5-32-2]]

^<<v5-32-2,2>>^ O meu ensinamento cairá como a chuva;
As minhas palavras descerão como o orvalho,
Como chuvas suaves sobre a relva
E como chuvas abundantes sobre a vegetação.

[[v5-32-3]]

^<<v5-32-3,3>>^ Pois declararei o nome de Jeová.
Falem sobre a grandeza do nosso Deus!

[[v5-32-4]]

^<<v5-32-4,4>>^ A Rocha — tudo o que ele faz é perfeito,
Pois todos os seus caminhos são justos.
Deus de fidelidade, que nunca é injusto;
Justo e reto é ele.

[[v5-32-5]]

^<<v5-32-5,5>>^ Eles é que agiram corruptamente;
Não são seus filhos, o defeito é deles.
São uma geração pervertida e corrompida!

[[v5-32-6]]

^<<v5-32-6,6>>^ É assim que devem tratar a Jeová,
Ó povo tolo e insensato?
Não é ele o teu Pai, que te trouxe à existência,
Aquele que te fez e que te estabeleceu firmemente?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembra-te dos tempos antigos;
Considerem os anos de gerações passadas.
Pergunta ao teu pai, e ele irá contar-te,
Aos anciãos no teu meio, e eles irão informar-te.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo deu a cada nação uma herança,
Quando separou os filhos de Adão^&#42;1^ uns dos outros,
Ele estabeleceu os limites dos povos,
Segundo o número dos filhos de Israel.

[NOTE]
====
. Ou, possivelmente: “a raça humana”.
====

[[v5-32-9]]

^<<v5-32-9,9>>^ Pois o povo de Jeová é a sua porção,
Jacó é a sua herança.

[[v5-32-10]]

^<<v5-32-10,10>>^ Ele encontrou-o numa terra deserta,
Num deserto vazio, cheio de uivos.
Cercou-o para o resguardar, cuidou dele,
E protegeu-o como a menina do seu olho.

[[v5-32-11]]

^<<v5-32-11,11>>^ Assim como a águia ensina a ninhada a voar,
Paira sobre os seus filhotes
E estende as asas para os apanhar,
Carregando-os nas suas penas,

[[v5-32-12]]

^<<v5-32-12,12>>^ Apenas Jeová o^&#42;1^ guiava;
Nenhum deus estrangeiro estava com ele.

[NOTE]
====
. Isto é, Jacó.
====

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele fê-lo cavalgar sobre os lugares altos da terra,
De modo que comeu os produtos do campo.
E alimentou-o com mel de um rochedo
E azeite de uma rocha,^&#42;1^

[NOTE]
====
. Ou: “rocha de pederneira”.
====

[[v5-32-14]]

^<<v5-32-14,14>>^ Manteiga das vacas e leite das ovelhas,
Juntamente com as melhores^&#42;1^ ovelhas,
E carneiros de Basã, e bodes,
Juntamente com o melhor^&#42;2^ trigo;
E do sangue^&#42;3^ das uvas bebeste vinho.

[NOTE]
====
. Lit.: “com a gordura das”.
. Lit.: “com a gordura dos rins do”.
. Ou: “sumo”.
====

[[v5-32-15]]

^<<v5-32-15,15>>^ Quando Jesurum^&#42;1^ engordou, rebelou-se e deu coices.
Sim, tu engordaste, ficaste forte, ficaste empanturrado.
Por isso, ele abandonou a Deus, que o fez,
E desprezou a Rocha da sua salvação.

[NOTE]
====
. Que significa “aquele que é reto”; título honorífico de Israel.
====

[[v5-32-16]]

^<<v5-32-16,16>>^ Provocaram a fúria dele por causa de deuses estrangeiros;
Ofendiam-no com coisas detestáveis.

[[v5-32-17]]

^<<v5-32-17,17>>^ Ofereciam sacrifícios a demónios, não a Deus,
A deuses que não conheciam,
Novos, que surgiram recentemente,
Deuses que os vossos antepassados não conheciam.

[[v5-32-18]]

^<<v5-32-18,18>>^ Esqueceste-te da Rocha que te gerou,
E não te lembraste do Deus que te deu à luz.

[[v5-32-19]]

^<<v5-32-19,19>>^ Quando Jeová viu isso, rejeitou-os
Porque os seus filhos e as suas filhas o ofenderam.

[[v5-32-20]]

^<<v5-32-20,20>>^ Portanto, ele disse: ‘Esconderei deles o meu rosto,
Verei o que lhes acontecerá.
Pois são uma geração perversa,
Filhos em quem não há fidelidade.

[[v5-32-21]]

^<<v5-32-21,21>>^ Provocaram a minha fúria^&#42;1^ por causa daquilo que não é deus;
Ofenderam-me com os seus ídolos que não valem nada.
Portanto, irei provocar-lhes ciúme com aquilo que não é povo;
Irei ofendê-los com uma nação insensata.

[NOTE]
====
. Ou: “o meu ciúme”.
====

[[v5-32-22]]

^<<v5-32-22,22>>^ Pois a minha ira acendeu um fogo
Que arderá até às profundezas da Sepultura,^&#42;1^
Consumirá a terra e a sua produção,
E incendiará os alicerces dos montes.

[NOTE]
====
. Ou: “do Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v5-32-23]]

^<<v5-32-23,23>>^ Aumentarei as suas calamidades;
Usarei todas as minhas flechas contra eles.

[[v5-32-24]]

^<<v5-32-24,24>>^ Ficarão esgotados de fome
E serão consumidos pela febre ardente e pela destruição amarga.
Enviarei contra eles dentes de feras
E veneno de répteis que rastejam no pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Do lado de fora, a espada matará os seus filhos;
Do lado de dentro, haverá pavor
Para o rapaz e para a rapariga,^&#42;1^
Para a criança e para o homem de cabelos brancos.

[NOTE]
====
. Ou: “virgem”.
====

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu teria dito: “Vou espalhá-los;
Farei desaparecer a memória que há deles dentre os homens”,

[[v5-32-27]]

^<<v5-32-27,27>>^ Se não fosse pelo medo da reação dos inimigos,
Porque os adversários poderiam entender mal.
Poderiam dizer: “O nosso poder triunfou;
Não foi Jeová quem fez tudo isto.”

[[v5-32-28]]

^<<v5-32-28,28>>^ Pois são uma nação que não tem bom senso,^&#42;1^
E entre eles não há entendimento.

[NOTE]
====
. Ou, possivelmente: “que não ouve conselhos”.
====

[[v5-32-29]]

^<<v5-32-29,29>>^ Quem me dera que fossem sábios! Eles meditariam sobre isto.
Pensariam no que lhes aconteceria.

[[v5-32-30]]

^<<v5-32-30,30>>^ Como é que um poderia perseguir mil,
E dois fazerem fugir dez mil?
Não poderiam, a não ser que a sua Rocha os tivesse vendido,
Que Jeová os tivesse entregado aos seus inimigos.

[[v5-32-31]]

^<<v5-32-31,31>>^ (Pois a rocha deles não é como a nossa Rocha;
Até mesmo os nossos inimigos reconhecem isso.)

[[v5-32-32]]

^<<v5-32-32,32>>^ Pois a sua vinha é da vinha de Sodoma
E dos socalcos de Gomorra.
As suas uvas são uvas venenosas,
Os seus cachos são amargos.

[[v5-32-33]]

^<<v5-32-33,33>>^ O seu vinho é a peçonha de serpentes,
O veneno cruel de najas.

[[v5-32-34]]

^<<v5-32-34,34>>^ Não está isto guardado comigo,
Selado no meu depósito?

[[v5-32-35]]

^<<v5-32-35,35>>^ Minha é a vingança e a retribuição,
No tempo determinado em que o seu pé escorregar,
Pois está perto o dia do seu desastre,
E o que os aguarda virá depressa.’

[[v5-32-36]]

^<<v5-32-36,36>>^ Jeová julgará o seu povo
E terá pena^&#42;1^ dos seus servos,
Quando vir que a força deles diminuiu
E que apenas ficou o desamparado e o fraco.

[NOTE]
====
. Ou: “lástima”.
====

[[v5-32-37]]

^<<v5-32-37,37>>^ Então, ele dirá: ‘Onde estão os deuses deles,
A rocha em quem procuraram refúgio,

[[v5-32-38]]

^<<v5-32-38,38>>^ Que comiam a gordura dos seus sacrifícios,^&#42;1^
E bebiam o vinho das suas ofertas de bebida?
Que venham ajudar-vos.
Que se tornem o vosso refúgio.

[NOTE]
====
. Ou: “comiam os seus melhores sacrifícios”.
====

[[v5-32-39]]

^<<v5-32-39,39>>^ Vejam agora que eu, sim, eu sou Deus,^&#42;1^
E não há outros deuses além de mim.
Eu entrego à morte, e eu dou vida.
Eu firo, e eu curarei,
E não há quem consiga livrar alguém das minhas mãos.

[NOTE]
====
. Lit.: “ele”.
====

[[v5-32-40]]

^<<v5-32-40,40>>^ Pois levanto a minha mão para o céu
E juro, dizendo: “Tão certo como eu vivo para sempre”,

[[v5-32-41]]

^<<v5-32-41,41>>^ Quando eu afiar a minha espada brilhante
E preparar a minha mão para o julgamento,
Irei vingar-me dos meus adversários
E retribuirei aos que me odeiam.

[[v5-32-42]]

^<<v5-32-42,42>>^ Embriagarei as minhas flechas com sangue,
E a minha espada comerá carne:
O sangue dos que foram mortos e dos cativos,
As cabeças dos líderes do inimigo.’

[[v5-32-43]]

^<<v5-32-43,43>>^ Alegrem-se, nações, com o Seu povo,
Pois ele vingará o sangue dos seus servos,
Trará vingança sobre os seus adversários
E fará expiação pela^&#42;1^ terra do seu povo.”

[NOTE]
====
. Ou: “E purificará a”.
====

[[v5-32-44]]

^<<v5-32-44,44>>^ Assim, Moisés veio e recitou todas as palavras deste cântico diante do povo, ele e Oseias,^&#42;1^ filho de Num.

[NOTE]
====
. O nome original de Josué. Oseias é a forma reduzida de Osaías, que significa “salvo por Jah; Jah salvou”.
====

[[v5-32-45]]

^<<v5-32-45,45>>^ Depois de Moisés ter acabado de dizer todas estas palavras a todo o Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ disse-lhes: “Reflitam em todas as palavras do aviso que hoje vos dou, para que ordenem aos vossos filhos que cumpram todas as palavras desta Lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Pois não são palavras sem valor para vocês, mas significam a vossa vida, e, por meio destas palavras, poderão viver por muito tempo na terra de que tomarão posse ao atravessar o Jordão.”

[[v5-32-48]]

^<<v5-32-48,48>>^ Jeová disse a Moisés naquele mesmo dia:

[[v5-32-49]]

^<<v5-32-49,49>>^ “Sobe a este monte da região de Abarim, o monte Nebo, que fica na terra de Moabe, em frente a Jericó, e vê a terra de Canaã, que dou aos israelitas como propriedade.

[[v5-32-50]]

^<<v5-32-50,50>>^ Então, morrerás no monte ao qual subirás, e serás reunido aos teus antepassados,^&#42;1^ assim como Arão, teu irmão, morreu no monte Hor e foi reunido ao seu povo,

[NOTE]
====
. Expressão poética que se refere à morte.
====

[[v5-32-51]]

^<<v5-32-51,51>>^ porque ambos me foram infiéis entre os israelitas, junto às águas de Meribá de Cades, no deserto de Zim, porque não me santificaram diante do povo de Israel.

[[v5-32-52]]

^<<v5-32-52,52>>^ Verás a terra à distância, mas não entrarás na terra que dou ao povo de Israel.”

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]