include::./index.adoc[]

[[v5-20-0]]
=== Deuteronómio, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-20-1]]

^<<v5-20-1,1>>^ “Se fores à guerra contra os teus inimigos e vires que os cavalos, os carros de guerra e as tropas deles são mais numerosos do que os teus, não tenhas medo deles, pois Jeová, teu Deus, que te tirou da terra do Egito, está contigo.

[[v5-20-2]]

^<<v5-20-2,2>>^ Quando estiverem para entrar em batalha, o sacerdote deve aproximar-se e falar ao povo.

[[v5-20-3]]

^<<v5-20-3,3>>^ Deve dizer-lhes: ‘Ouve, ó Israel, vocês estão prestes a entrar em batalha contra os vossos inimigos. Não desanimem. Não tenham medo, nem fiquem apavorados, nem tremam por causa deles,

[[v5-20-4]]

^<<v5-20-4,4>>^ pois Jeová, vosso Deus, está a marchar convosco para lutar por vocês contra os vossos inimigos e para vos salvar.’

[[v5-20-5]]

^<<v5-20-5,5>>^ “Os oficiais também devem dizer ao povo: ‘Quem construiu uma casa nova e não a inaugurou? Retorne à sua casa. Senão, poderá morrer na batalha e outro homem irá inaugurá-la.

[[v5-20-6]]

^<<v5-20-6,6>>^ E quem plantou uma vinha e ainda não colheu os seus frutos? Retorne à sua casa. Senão, poderá morrer na batalha e outro homem colherá os seus frutos.

[[v5-20-7]]

^<<v5-20-7,7>>^ E quem ficou noivo de uma mulher e ainda não se casou com ela? Retorne à sua casa. Senão, poderá morrer na batalha e outro homem irá casar-se com ela.’

[[v5-20-8]]

^<<v5-20-8,8>>^ Os oficiais também devem perguntar ao povo: ‘Quem está com medo e desanimado? Retorne à sua casa, para que não deixe os seus irmãos desanimados assim como ele está.’^&#42;1^

[NOTE]
====
. Ou: “não faça o coração dos seus irmãos derreter-se como o seu próprio coração”.
====

[[v5-20-9]]

^<<v5-20-9,9>>^ Quando os oficiais acabarem de falar ao povo, devem designar os chefes dos exércitos para liderar o povo.

[[v5-20-10]]

^<<v5-20-10,10>>^ “Se te aproximares de uma cidade para lutar contra ela, deves anunciar-lhe termos de paz.

[[v5-20-11]]

^<<v5-20-11,11>>^ Se ela te der uma resposta pacífica e te abrir os portões, todo o povo que se encontra ali se tornará teu para trabalhos forçados, e eles irão servir-te.

[[v5-20-12]]

^<<v5-20-12,12>>^ No entanto, se ela se recusar a fazer a paz e guerrear contra ti, deves sitiá-la,

[[v5-20-13]]

^<<v5-20-13,13>>^ e Jeová, teu Deus, certamente a entregará nas tuas mãos. Mata com a espada todos os homens que lá houver.

[[v5-20-14]]

^<<v5-20-14,14>>^ Mas as mulheres, as crianças, os animais e tudo o que houver na cidade, todo o despojo, podes saquear. E comerás do despojo dos teus inimigos, que Jeová, teu Deus, te entregou.

[[v5-20-15]]

^<<v5-20-15,15>>^ “Farás isso a todas as cidades que estiverem bem longe de ti, que não forem cidades das nações que estão perto de ti.

[[v5-20-16]]

^<<v5-20-16,16>>^ Mas não permitas que nada que respira continue vivo nas cidades destes povos, as quais Jeová, teu Deus, te dá como herança.

[[v5-20-17]]

^<<v5-20-17,17>>^ Deves entregá-los à destruição^&#42;1^ — os hititas, os amorreus, os cananeus, os perizeus, os heveus e os jebuseus — assim como Jeová, teu Deus, te ordenou,

[NOTE]
====
. Ou: “devotá-los à destruição”. Veja o Glossário.
====

[[v5-20-18]]

^<<v5-20-18,18>>^ para que não vos ensinem a imitar todas as coisas detestáveis que eles fazem para os seus deuses, levando-vos a pecar contra Jeová, vosso Deus.

[[v5-20-19]]

^<<v5-20-19,19>>^ “Se sitiares uma cidade para a tomares e já estiveres a lutar contra ela há muitos dias, não deves destruir as suas árvores, por ergueres um machado contra elas. Podes comer delas, mas não as deves cortar. Pois, será que deverias sitiar uma árvore do campo assim como o farias a um homem?

[[v5-20-20]]

^<<v5-20-20,20>>^ Podes destruir apenas a árvore que souberes que não serve para alimento. Podes cortá-la para construir obras de cerco contra a cidade que guerreia contra ti, até que caia.

'''

xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[&#60; Capítulo Anterior] | <<v5-20-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[Próximo Capítulo &#62;]