include::./index.adoc[]

[[v5-33-0]]
=== Deuteronómio, 33
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-33-1]]

^<<v5-33-1,1>>^ Esta é a bênção que Moisés, o homem do verdadeiro Deus, proferiu aos israelitas antes da sua morte.

[[v5-33-2]]

^<<v5-33-2,2>>^ Ele disse:
“Jeová — do Sinai ele veio,
E brilhou sobre eles desde Seir.
Resplandeceu em glória desde a região montanhosa de Parã,
E com ele estavam santas miríades,^&#42;1^
À sua direita estavam os seus guerreiros.

[NOTE]
====
. Ou: “dezenas de milhares de santos”.
====

[[v5-33-3]]

^<<v5-33-3,3>>^ Ele amou o seu povo;
Todos os santos do povo estão na tua mão.
Eles estavam sentados aos teus pés,
Começaram a escutar as tuas palavras.

[[v5-33-4]]

^<<v5-33-4,4>>^ (Moisés deu-nos uma ordem, uma lei,
Como propriedade da congregação de Jacó.)

[[v5-33-5]]

^<<v5-33-5,5>>^ E Ele tornou-se rei em Jesurum^&#42;1^
Quando os cabeças do povo se reuniram
Com todas as tribos de Israel.

[NOTE]
====
. Que significa “aquele que é reto”; título honorífico de Israel.
====

[[v5-33-6]]

^<<v5-33-6,6>>^ Que Rúben viva e não morra,
E que os seus homens não se tornem poucos.”

[[v5-33-7]]

^<<v5-33-7,7>>^ E ele proferiu esta bênção a Judá:
“Ouve, ó Jeová, a voz de Judá,
E que tu o tragas de volta ao seu povo.
Os seus braços defenderam o^&#42;1^ que lhe pertence,
E que tu o ajudes contra os seus adversários.”

[NOTE]
====
. Ou: “lutaram pelo”.
====

[[v5-33-8]]

^<<v5-33-8,8>>^ A respeito de Levi, ele disse:
“O teu Tumim e o teu Urim pertencem ao homem que te é leal,
A quem puseste à prova em Massá.
Começaste a discutir com ele junto às águas de Meribá,

[[v5-33-9]]

^<<v5-33-9,9>>^ Com o homem que disse do seu pai e da sua mãe: ‘Não tenho consideração por eles.’
Ele nem reconheceu os seus irmãos,
E ignorou os seus próprios filhos.
Pois guardaram a tua palavra,
E observaram o teu pacto.

[[v5-33-10]]

^<<v5-33-10,10>>^ Que eles instruam Jacó nas tuas decisões judiciais,
E Israel na tua Lei.
Que te^&#42;1^ ofereçam incenso como aroma agradável
E uma oferta inteira no teu altar.

[NOTE]
====
. Lit.: “ao teu nariz”.
====

[[v5-33-11]]

^<<v5-33-11,11>>^ Abençoa, ó Jeová, a sua força,
E que tenhas prazer no trabalho das suas mãos.
Parte as pernas^&#42;1^ dos que se levantam contra ele,
Para que aqueles que o odeiam nunca mais se levantem.”

[NOTE]
====
. Ou: “as ancas”.
====

[[v5-33-12]]

^<<v5-33-12,12>>^ A respeito de Benjamim, ele disse:
“Que o amado de Jeová resida em segurança ao pé dele;
Enquanto o abriga o dia inteiro,
Ele residirá entre os seus ombros.”

[[v5-33-13]]

^<<v5-33-13,13>>^ A respeito de José, ele disse:
“Seja a sua terra abençoada por Jeová
Com as coisas seletas do céu,
Com orvalho e com as águas das fontes abaixo da terra,

[[v5-33-14]]

^<<v5-33-14,14>>^ Com as coisas seletas que o sol faz crescer
E com as safras seletas, a cada mês,

[[v5-33-15]]

^<<v5-33-15,15>>^ Com as coisas mais seletas procedentes das montanhas antigas^&#42;1^
E com as coisas seletas dos montes eternos,

[NOTE]
====
. Ou, possivelmente: “montanhas do leste”.
====

[[v5-33-16]]

^<<v5-33-16,16>>^ Com as coisas seletas da terra e do que a enche,
E com a aprovação d’Aquele que apareceu no espinheiro.
Que venham sobre a cabeça de José,
Sobre o alto da cabeça do escolhido dentre os seus irmãos.

[[v5-33-17]]

^<<v5-33-17,17>>^ O seu esplendor é como o de um touro primogénito,
E os seus chifres são os chifres de um touro selvagem.
Com eles empurrará^&#42;1^ povos,
Todos juntos, até aos confins da terra.
Eles são as dezenas de milhares de Efraim,
E os milhares de Manassés.”

[NOTE]
====
. Ou: “marrará”.
====

[[v5-33-18]]

^<<v5-33-18,18>>^ A respeito de Zebulão, ele disse:
“Alegra-te, ó Zebulão, nos teus empreendimentos;^&#42;1^
E tu, Issacar, nas tuas tendas.

[NOTE]
====
. Lit.: “na tua saída”.
====

[[v5-33-19]]

^<<v5-33-19,19>>^ Eles convocarão povos ao monte.
Ali oferecerão sacrifícios em justiça.
Pois extrairão a riqueza abundante^&#42;1^ dos mares
E os tesouros ocultos da areia.”

[NOTE]
====
. Lit.: “sugarão a abundância”.
====

[[v5-33-20]]

^<<v5-33-20,20>>^ A respeito de Gade, ele disse:
“Bendito é aquele que amplia o território de Gade.
Deita-se como um leão,
Pronto para dilacerar o braço, sim, a cabeça da sua presa.

[[v5-33-21]]

^<<v5-33-21,21>>^ Escolherá para si a primeira parte,
Pois ali se reserva a porção de um legislador.
Os cabeças do povo vão juntar-se.
Ele executará a justiça de Jeová
E as suas decisões judiciais para com Israel.”

[[v5-33-22]]

^<<v5-33-22,22>>^ A respeito de Dã, ele disse:
“Dã é uma cria de leão.
Ele saltará de Basã.”

[[v5-33-23]]

^<<v5-33-23,23>>^ A respeito de Naftali, ele disse:
“Naftali está satisfeito com a aprovação de Jeová
E cheio da sua bênção.
Toma posse do oeste e do sul.”

[[v5-33-24]]

^<<v5-33-24,24>>^ A respeito de Aser, ele disse:
“Aser é abençoado com filhos.
Que seja favorecido pelos seus irmãos
E que mergulhe^&#42;1^ os seus pés em azeite.

[NOTE]
====
. Ou: “lave”.
====

[[v5-33-25]]

^<<v5-33-25,25>>^ Ferro e cobre são as trancas dos teus portões,
E tu ficarás seguro todos os teus dias.^&#42;1^

[NOTE]
====
. Lit.: “E como os teus dias será a tua força”.
====

[[v5-33-26]]

^<<v5-33-26,26>>^ Não há ninguém como o verdadeiro Deus de Jesurum,
Que cavalga pelo céu para te ajudar
E que cavalga sobre as nuvens em majestade.

[[v5-33-27]]

^<<v5-33-27,27>>^ Deus é um refúgio desde os tempos antigos,
Os seus braços eternos estão por baixo de ti.
Ele expulsará o inimigo de diante de ti
E dirá: ‘Destrói-os!’

[[v5-33-28]]

^<<v5-33-28,28>>^ Israel residirá em segurança,
E a fonte de Jacó correrá sozinha
Numa terra de cereais e vinho novo,
Cujos céus gotejarão orvalho.

[[v5-33-29]]

^<<v5-33-29,29>>^ Feliz és tu, ó Israel!
Quem é semelhante a ti,
Um povo cuja salvação vem de Jeová,
O teu escudo protetor
E a tua espada majestosa?
Os teus inimigos ficarão encolhidos de medo diante de ti,
E tu pisarás as costas^&#42;1^ deles.”

[NOTE]
====
. Ou, possivelmente: “nos lugares altos”.
====

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]