include::./index.adoc[]

[[v5-11-0]]
=== Deuteronómio, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-11-1]]

^<<v5-11-1,1>>^ “Ama a Jeová, teu Deus, e cumpre sempre a tua obrigação para com ele, os seus decretos, as suas decisões judiciais e os seus mandamentos.

[[v5-11-2]]

^<<v5-11-2,2>>^ Sabem que hoje me dirijo a vocês, não aos vossos filhos, que não conheceram nem viram a disciplina de Jeová, vosso Deus, nem a sua grandeza, a sua mão poderosa e o seu braço estendido.

[[v5-11-3]]

^<<v5-11-3,3>>^ Eles não viram os sinais e os atos que ele realizou no Egito contra o Faraó, rei do Egito, e contra toda a sua terra,

[[v5-11-4]]

^<<v5-11-4,4>>^ nem o que fez aos exércitos do Egito, aos cavalos e aos carros de guerra do Faraó, que foram engolidos pelas águas do mar Vermelho quando vos perseguiam, e Jeová destruiu-os de uma vez para sempre.^&#42;1^

[NOTE]
====
. Ou: “até ao dia de hoje”.
====

[[v5-11-5]]

^<<v5-11-5,5>>^ Eles não viram o que ele fez por vocês^&#42;1^ no deserto, até chegarem a este lugar,

[NOTE]
====
. Ou: “vos fez”.
====

[[v5-11-6]]

^<<v5-11-6,6>>^ nem o que fez a Datã e Abirão, filhos de Eliabe, filho de Rúben, quando a terra se abriu diante dos olhos de todo o Israel e os engoliu, a eles e aos da sua casa, bem como às suas tendas e a todas as pessoas e animais que estavam com eles.

[[v5-11-7]]

^<<v5-11-7,7>>^ Foram os vossos próprios olhos que viram todos os grandes atos que Jeová realizou.

[[v5-11-8]]

^<<v5-11-8,8>>^ “Guardem todos os mandamentos que hoje vos dou, para que se tornem fortes e atravessem para a terra, a fim de tomar posse dela,

[[v5-11-9]]

^<<v5-11-9,9>>^ e para que vivam por muito tempo na terra que Jeová jurou dar aos vossos antepassados e à descendência^&#42;1^ deles, uma terra que mana leite e mel.

[NOTE]
====
. Lit.: “semente”.
====

[[v5-11-10]]

^<<v5-11-10,10>>^ “A terra da qual vais tomar posse não é como a terra do Egito, de onde saíram, onde semeavas a semente e irrigavas com o pé,^&#42;1^ como uma horta.

[NOTE]
====
. Ou: “regavas com o pé”, isto é, usando os pés de alguma maneira, quer para mover uma roda d’água, quer para formar e abrir canais de água.
====

[[v5-11-11]]

^<<v5-11-11,11>>^ Mas a terra para a qual estão prestes a atravessar e da qual tomarão posse é uma terra de montes e vales.^&#42;1^ Ela bebe a água da chuva dos céus,

[NOTE]
====
. Lit.: “planícies de vale”.
====

[[v5-11-12]]

^<<v5-11-12,12>>^ é uma terra da qual Jeová, teu Deus, está a cuidar. Os olhos de Jeová, teu Deus, estão sempre sobre ela, do início do ano até ao fim do ano.

[[v5-11-13]]

^<<v5-11-13,13>>^ “E, se obedecerem cuidadosamente aos mandamentos que hoje vos ordeno, amarem a Jeová, vosso Deus, e o servirem de todo o vosso coração e de toda a vossa alma,^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v5-11-14]]

^<<v5-11-14,14>>^ então, no tempo determinado, darei chuva à vossa terra, a chuva do outono e a chuva da primavera, e recolherás os teus cereais, o teu vinho novo e o teu azeite.

[[v5-11-15]]

^<<v5-11-15,15>>^ E, nos teus campos, darei vegetação para o teu gado, e tu comerás e ficarás satisfeito.

[[v5-11-16]]

^<<v5-11-16,16>>^ Tenham cuidado para que o vosso coração não seja tentado a desviar-se, a adorar outros deuses e a curvar-se diante deles.

[[v5-11-17]]

^<<v5-11-17,17>>^ Senão, a ira de Jeová acender-se-á contra vocês, e ele fechará os céus, de modo que não choverá e a terra não dará a sua produção, e vocês desaparecerão depressa da boa terra que Jeová vos dá.

[[v5-11-18]]

^<<v5-11-18,18>>^ “Gravem estas minhas palavras no vosso coração e na vossa alma,^&#42;1^ e atem-nas como uma recordação à vossa mão, e elas devem ser como uma faixa na vossa testa.^&#42;2^

[NOTE]
====
. Veja o Glossário.
. Lit.: “entre os vossos olhos”.
====

[[v5-11-19]]

^<<v5-11-19,19>>^ Ensinem-nas aos vossos filhos, falando delas sentado na tua casa, ao andares pela estrada, quando te deitares e quando te levantares.

[[v5-11-20]]

^<<v5-11-20,20>>^ Escreve-as nas ombreiras da entrada^&#42;1^ da tua casa e nos teus portões,

[NOTE]
====
. Isto é, “em cada peça lateral da porta”.
====

[[v5-11-21]]

^<<v5-11-21,21>>^ para que vocês e os vossos filhos vivam por muito tempo na terra que Jeová jurou dar aos vossos antepassados, pelo tempo em que os céus cobrirem a terra.

[[v5-11-22]]

^<<v5-11-22,22>>^ “Se obedecerem fielmente a estes mandamentos que vos dou e se os cumprirem, por amarem a Jeová, vosso Deus, por andarem sempre nos seus caminhos e por se apegarem a ele,

[[v5-11-23]]

^<<v5-11-23,23>>^ Jeová expulsará todas estas nações da vossa frente, e vocês tomarão posse da terra de nações maiores e mais numerosas do que vocês.

[[v5-11-24]]

^<<v5-11-24,24>>^ Todos os lugares em que pisarem irão tornar-se vossos: desde o deserto até ao Líbano, e desde o rio, o rio Eufrates, até ao mar ocidental.^&#42;1^ Estes serão os limites do vosso território.

[NOTE]
====
. Isto é, o Grande Mar, o Mediterrâneo.
====

[[v5-11-25]]

^<<v5-11-25,25>>^ Ninguém vos resistirá. Jeová, vosso Deus, espalhará o pavor e medo que terão de vocês em toda a terra por onde andarem, assim como vos prometeu.

[[v5-11-26]]

^<<v5-11-26,26>>^ “Vejam, hoje, ponho à vossa frente uma bênção e uma maldição:

[[v5-11-27]]

^<<v5-11-27,27>>^ a bênção, caso obedeçam aos mandamentos de Jeová, vosso Deus, que hoje vos ordeno;

[[v5-11-28]]

^<<v5-11-28,28>>^ e a maldição, caso não obedeçam aos mandamentos de Jeová, vosso Deus, e se desviem do caminho que hoje vos ordeno, e sigam deuses que não conhecem.

[[v5-11-29]]

^<<v5-11-29,29>>^ “Quando Jeová, teu Deus, te fizer entrar na terra da qual vais tomar posse, profere^&#42;1^ a bênção junto ao monte Gerizim e a maldição junto ao monte Ebal.

[NOTE]
====
. Ou: “dá”.
====

[[v5-11-30]]

^<<v5-11-30,30>>^ Estes montes estão do outro lado do Jordão, a oeste,^&#42;1^ na terra dos cananeus que moram no Arabá, em frente a Gilgal, perto das árvores grandes de Moré.

[NOTE]
====
. Ou: “poente”.
====

[[v5-11-31]]

^<<v5-11-31,31>>^ Pois vocês vão atravessar o Jordão para entrarem na terra que Jeová, vosso Deus, vos dá e para tomarem posse dela. Quando tomarem posse dela e estiverem a morar nela,

[[v5-11-32]]

^<<v5-11-32,32>>^ tenham o cuidado de cumprir todos os decretos e as decisões judiciais que hoje vos apresento.

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]