include::./index.adoc[]

[[v5-24-0]]
=== Deuteronómio, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-24-1]]

^<<v5-24-1,1>>^ “Se um homem se casar com uma mulher, mas ela não lhe agradar por causa de alguma coisa indecente que ele descobriu a respeito dela, então, ele deve escrever-lhe um certificado de divórcio, dar-lhe o certificado e mandá-la embora da sua casa.

[[v5-24-2]]

^<<v5-24-2,2>>^ Depois de sair da casa dele, ela poderá tornar-se esposa de outro homem.

[[v5-24-3]]

^<<v5-24-3,3>>^ Se o segundo homem a odiar,^&#42;1^ escrever um certificado de divórcio e o der a ela, e a mandar embora da sua casa, ou se o segundo homem que se casou com ela morrer,

[NOTE]
====
. Ou: “a rejeitar”.
====

[[v5-24-4]]

^<<v5-24-4,4>>^ então, o primeiro marido, que a tinha mandado embora, não poderá voltar a tomá-la como esposa depois de ela se ter tornado impura, pois isso é algo detestável para Jeová. Não tragas pecado sobre a terra que Jeová, teu Deus, te dá por herança.

[[v5-24-5]]

^<<v5-24-5,5>>^ “Um homem recém-casado não deverá servir no exército nem receber nenhuma outra responsabilidade. Deverá ficar isento por um ano, permanecer em casa e alegrar a sua esposa.

[[v5-24-6]]

^<<v5-24-6,6>>^ “Ninguém deve exigir um moinho manual ou a sua pedra superior como garantia de um empréstimo,^&#42;1^ pois estaria a tirar o meio de vida^&#42;2^ de alguém como garantia.

[NOTE]
====
. Ou: “como penhor”.
. Ou: “a tirar a vida; a tirar a alma”.
====

[[v5-24-7]]

^<<v5-24-7,7>>^ “Se for descoberto que alguém raptou um^&#42;1^ dos seus irmãos israelitas, e o maltratou e vendeu, o raptor tem de morrer. Elimina o mal do teu meio.

[NOTE]
====
. Ou: “a alma de um”.
====

[[v5-24-8]]

^<<v5-24-8,8>>^ “Quando surgir um surto de lepra,^&#42;1^ tem muito cuidado para seguires todas as instruções que os sacerdotes levíticos vos derem. Tenham o cuidado de fazer exatamente como lhes ordenei.

[NOTE]
====
. A palavra hebraica traduzida “lepra” tem sentido abrangente e pode incluir várias doenças de pele contagiosas. Também pode incluir certas contaminações encontradas em peças de roupa e em casas.
====

[[v5-24-9]]

^<<v5-24-9,9>>^ Lembra-te do que Jeová, teu Deus, fez a Miriam no caminho, quando vocês saíam do Egito.

[[v5-24-10]]

^<<v5-24-10,10>>^ “Se fizeres qualquer tipo de empréstimo ao teu próximo, não entres na casa dele para lhe tirar o que ele ofereceu como garantia.

[[v5-24-11]]

^<<v5-24-11,11>>^ Deves ficar do lado de fora, e o homem que recebeu o empréstimo deve trazer para fora o que te ofereceu como garantia.

[[v5-24-12]]

^<<v5-24-12,12>>^ E, se o homem estiver a passar necessidades, não te deves deitar tendo contigo o que ele te deu como garantia.

[[v5-24-13]]

^<<v5-24-13,13>>^ Assim que o sol se puser, sem falta, deves devolver-lhe o que ele deu como garantia, e ele irá deitar-se com o seu manto e abençoar-te; assim, serás considerado justo perante Jeová, teu Deus.

[[v5-24-14]]

^<<v5-24-14,14>>^ “Não defraudes o trabalhador contratado que estiver a passar necessidades e que for pobre, quer seja um dos teus irmãos, quer seja um residente estrangeiro na tua terra, dentro das tuas cidades.^&#42;1^

[NOTE]
====
. Ou: “dos teus portões”.
====

[[v5-24-15]]

^<<v5-24-15,15>>^ Deves dar-lhe o seu salário no mesmo dia, antes de o sol se pôr, porque ele está a passar necessidades e a sua vida^&#42;1^ depende do salário. Senão, ele clamará a Jeová contra ti, e tu irás tornar-te culpado de pecado.

[NOTE]
====
. Ou: “alma”.
====

[[v5-24-16]]

^<<v5-24-16,16>>^ “Os pais não devem ser mortos por causa das ações dos filhos, e os filhos não devem ser mortos por causa das ações dos pais. A pessoa só deve ser morta pelo seu próprio pecado.

[[v5-24-17]]

^<<v5-24-17,17>>^ “Não deves perverter o julgamento do residente estrangeiro nem do órfão,^&#42;1^ nem exigir o manto de uma viúva como garantia de um empréstimo.^&#42;2^

[NOTE]
====
. Ou: “órfão de pai”.
. Ou: “como penhor”.
====

[[v5-24-18]]

^<<v5-24-18,18>>^ Lembra-te de que te tornaste escravo no Egito e que Jeová, teu Deus, te resgatou de lá. É por isso que te dou esta ordem.

[[v5-24-19]]

^<<v5-24-19,19>>^ “Quando fizeres a colheita do teu campo e te tiveres esquecido dum feixe no campo, não voltes para o apanhar. Deixa-o para o residente estrangeiro, para o órfão e para a viúva, a fim de que Jeová, teu Deus, te abençoe em tudo o que fizeres.

[[v5-24-20]]

^<<v5-24-20,20>>^ “Quando sacudires os galhos da tua oliveira, não repitas o processo. O que restar deve ficar para o residente estrangeiro, para o órfão e para a viúva.

[[v5-24-21]]

^<<v5-24-21,21>>^ “Quando colheres as uvas da tua vinha, não deves voltar para colher as sobras. Devem ser deixadas para o residente estrangeiro, para o órfão e para a viúva.

[[v5-24-22]]

^<<v5-24-22,22>>^ Lembra-te de que te tornaste escravo na terra do Egito. É por isso que te dou esta ordem.

'''

xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[Próximo Capítulo &#62;]