include::./index.adoc[]

[[v5-27-0]]
=== Deuteronómio, 27
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-27-1]]

^<<v5-27-1,1>>^ Então, Moisés, juntamente com os anciãos de Israel, ordenou ao povo: “Obedeçam a cada mandamento que hoje vos dou.

[[v5-27-2]]

^<<v5-27-2,2>>^ E, no dia em que atravessarem o Jordão para a terra que Jeová, vosso Deus, vos dá, ergam grandes pedras e cubram-nas com reboco.^&#42;1^

[NOTE]
====
. Ou: “pintem-nas com cal”.
====

[[v5-27-3]]

^<<v5-27-3,3>>^ E, quando tiveres atravessado o Jordão, escreve nelas todas as palavras desta Lei, para que entres na terra que Jeová, teu Deus, te dá, uma terra que mana leite e mel, assim como Jeová, o Deus dos teus antepassados, te prometeu.

[[v5-27-4]]

^<<v5-27-4,4>>^ Quando tiverem atravessado o Jordão, devem erguer estas pedras no monte Ebal e cobri-las com reboco,^&#42;1^ assim como hoje vos ordeno.

[NOTE]
====
. Ou: “pintá-las com cal”.
====

[[v5-27-5]]

^<<v5-27-5,5>>^ Deves também construir ali um altar a Jeová, teu Deus, um altar de pedras. Não deves usar instrumentos de ferro nas pedras.

[[v5-27-6]]

^<<v5-27-6,6>>^ Deves construir o altar de Jeová, teu Deus, com pedras inteiras e fazer sobre ele ofertas queimadas a Jeová, teu Deus.

[[v5-27-7]]

^<<v5-27-7,7>>^ Deves oferecer sacrifícios de participação em comum e comê-los ali, e irás alegrar-te perante Jeová, teu Deus.

[[v5-27-8]]

^<<v5-27-8,8>>^ E escreve claramente sobre as pedras todas as palavras desta Lei.”

[[v5-27-9]]

^<<v5-27-9,9>>^ E Moisés e os sacerdotes levíticos disseram a todo o Israel: “Fica em silêncio e escuta, ó Israel. Hoje, tornaste-te o povo de Jeová, teu Deus.

[[v5-27-10]]

^<<v5-27-10,10>>^ Escuta a voz de Jeová, teu Deus, e cumpre os seus mandamentos e os seus decretos, que hoje te ordeno.”

[[v5-27-11]]

^<<v5-27-11,11>>^ Naquele dia, Moisés ordenou ao povo:

[[v5-27-12]]

^<<v5-27-12,12>>^ “Quando tiverem atravessado o Jordão, as seguintes tribos ficarão de pé no monte Gerizim para abençoar o povo: Simeão, Levi, Judá, Issacar, José e Benjamim.

[[v5-27-13]]

^<<v5-27-13,13>>^ E as seguintes ficarão de pé no monte Ebal para proferir a maldição: Rúben, Gade, Aser, Zebulão, Dã e Naftali.

[[v5-27-14]]

^<<v5-27-14,14>>^ E os levitas dirão em voz bem alta a todos os homens de Israel:

[[v5-27-15]]

^<<v5-27-15,15>>^ “‘Maldito o homem que fizer uma imagem esculpida ou uma estátua de metal^&#42;1^ — uma coisa detestável para Jeová, trabalho das mãos de um artesão^&#42;2^ —, e que a esconder.’ (E todo o povo dirá: ‘Amém!’^&#42;3^)

[NOTE]
====
. Ou: “estátua fundida”.
. Ou: “trabalhador em madeira e metal”.
. Ou: “Assim seja!”
====

[[v5-27-16]]

^<<v5-27-16,16>>^ “‘Maldito aquele que tratar o seu pai ou a sua mãe com desprezo.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-17]]

^<<v5-27-17,17>>^ “‘Maldito aquele que mudar de lugar os marcos divisórios do terreno do seu vizinho.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-18]]

^<<v5-27-18,18>>^ “‘Maldito aquele que fizer um cego perder-se no caminho.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-19]]

^<<v5-27-19,19>>^ “‘Maldito aquele que perverter o julgamento de um residente estrangeiro, de um órfão^&#42;1^ ou de uma viúva.’ (E todo o povo dirá: ‘Amém!’)

[NOTE]
====
. Ou: “órfão de pai”.
====

[[v5-27-20]]

^<<v5-27-20,20>>^ “‘Maldito aquele que se deitar com a esposa do seu pai, pois desonra o seu pai.’^&#42;1^ (E todo o povo dirá: ‘Amém!’)

[NOTE]
====
. Lit.: “remove a saia do seu pai”.
====

[[v5-27-21]]

^<<v5-27-21,21>>^ “‘Maldito aquele que se deitar com um animal.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-22]]

^<<v5-27-22,22>>^ “‘Maldito aquele que se deitar com a sua irmã, filha do seu pai ou filha da sua mãe.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-23]]

^<<v5-27-23,23>>^ “‘Maldito aquele que se deitar com a sua sogra.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-24]]

^<<v5-27-24,24>>^ “‘Maldito aquele que ficar de emboscada e matar o seu próximo.’ (E todo o povo dirá: ‘Amém!’)

[[v5-27-25]]

^<<v5-27-25,25>>^ “‘Maldito aquele que aceitar suborno para matar^&#42;1^ uma pessoa inocente.’^&#42;2^ (E todo o povo dirá: ‘Amém!’)

[NOTE]
====
. Ou: “golpear”.
. Ou: “uma alma de sangue inocente”.
====

[[v5-27-26]]

^<<v5-27-26,26>>^ “‘Maldito aquele que não obedecer às palavras desta Lei, deixando de as cumprir.’ (E todo o povo dirá: ‘Amém!’)

'''

xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[&#60; Capítulo Anterior] | <<v5-27-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[Próximo Capítulo &#62;]