include::./index.adoc[]

[[v5-3-0]]
=== Deuteronómio, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v5-3-1]]

^<<v5-3-1,1>>^ “Depois, mudámos de direção e subimos pelo Caminho de Basã. E Ogue, rei de Basã, veio ao nosso encontro com todo o seu exército para batalhar em Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Portanto, Jeová disse-me: ‘Não tenhas medo dele, pois irei entregá-lo nas tuas mãos, com todo o seu povo e a sua terra. Farás com ele o mesmo que fizeste com Síon, rei dos amorreus, que morava em Hésbon.’

[[v5-3-3]]

^<<v5-3-3,3>>^ Assim, Jeová, nosso Deus, também nos entregou Ogue, rei de Basã, nas nossas mãos, e todo o seu povo, e nós matámo-los até que não sobreviveu ninguém do seu povo.

[[v5-3-4]]

^<<v5-3-4,4>>^ Então, tomámos todas as suas cidades. Não houve cidade que não lhes tirássemos. Foram 60 cidades, toda a região de Argobe, o reino de Ogue em Basã.

[[v5-3-5]]

^<<v5-3-5,5>>^ Todas estas cidades eram fortificadas com muralhas altas, portões e trancas. Também havia muitas aldeias.

[[v5-3-6]]

^<<v5-3-6,6>>^ No entanto, entregámo-las à destruição,^&#42;1^ assim como tínhamos feito a Síon, rei de Hésbon, entregando todas as cidades à destruição, incluindo homens, mulheres e crianças.

[NOTE]
====
. Ou: “devotámo-las à destruição”. Veja o Glossário.
====

[[v5-3-7]]

^<<v5-3-7,7>>^ E tomámos para nós todo o gado e o despojo das cidades.

[[v5-3-8]]

^<<v5-3-8,8>>^ “Naquela ocasião, conquistámos a terra dos dois reis amorreus que ocupavam a região do Jordão, desde o vale do Arnom^&#42;1^ até ao monte Hermom

[NOTE]
====
. Ou: “uádi Arnom”.
====

[[v5-3-9]]

^<<v5-3-9,9>>^ (monte a que os sidónios chamavam Siriom, e os amorreus chamavam Senir).

[[v5-3-10]]

^<<v5-3-10,10>>^ Conquistámos todas as cidades do planalto,^&#42;1^ todo o Gileade e todo o Basã, até Salcá e Edrei, as cidades do reino de Ogue em Basã.

[NOTE]
====
. Ou: “da achada”.
====

[[v5-3-11]]

^<<v5-3-11,11>>^ Pois Ogue, rei de Basã, era o último que restava dos refains. (O seu sarcófago^&#42;1^ de ferro^&#42;2^ ainda está em Rabá dos amonitas. Tem nove côvados^&#42;3^ de comprimento e quatro côvados de largura, segundo o côvado-padrão.)

[NOTE]
====
. Ou: “esquife; caixão”.
. Ou, possivelmente: “basalto negro”.
. Um côvado equivalia a 44,5 cm. Veja o Ap. B14.
====

[[v5-3-12]]

^<<v5-3-12,12>>^ Naquela ocasião, tomámos posse desta terra: a terra a partir de Aroer, que fica junto ao vale do Arnom,^&#42;1^ e metade da região montanhosa de Gileade. Aos rubenitas e aos gaditas dei as cidades desta terra.

[NOTE]
====
. Ou: “uádi Arnom”.
====

[[v5-3-13]]

^<<v5-3-13,13>>^ E o restante de Gileade e todo o Basã, que fazia parte do reino de Ogue, dei à meia tribo de Manassés. Toda a região de Argobe, que pertence a Basã, era conhecida como a terra dos refains.

[[v5-3-14]]

^<<v5-3-14,14>>^ “Jair, filho de Manassés, tomou toda a região de Argobe até ao limite do território dos gesuritas e dos maacatitas, e deu às aldeias de Basã o seu próprio nome, Havote-Jair,^&#42;1^ como são chamadas até ao dia de hoje.

[NOTE]
====
. Que significa “aldeias de tendas de Jair”.
====

[[v5-3-15]]

^<<v5-3-15,15>>^ E dei Gileade a Maquir.

[[v5-3-16]]

^<<v5-3-16,16>>^ E aos rubenitas e aos gaditas dei a região desde Gileade até ao vale do Arnom^&#42;1^ (o meio do vale é o limite) e até ao Jaboque, o vale que é o limite do território dos amonitas.

[NOTE]
====
. Ou: “uádi Arnom”.
====

[[v5-3-17]]

^<<v5-3-17,17>>^ Dei o Arabá, o rio Jordão e a sua margem, desde o Quinerete até ao mar do Arabá, o mar Salgado,^&#42;1^ no sopé das encostas do Pisga, que fica a leste.

[NOTE]
====
. Isto é, o mar Morto.
====

[[v5-3-18]]

^<<v5-3-18,18>>^ “Então, dei-vos a seguinte ordem: ‘Jeová, vosso Deus, deu-vos esta terra, para que tomem posse dela. Todos os vossos homens valentes irão armar-se e atravessar o Jordão diante dos vossos irmãos israelitas.

[[v5-3-19]]

^<<v5-3-19,19>>^ Apenas as vossas esposas, as vossas crianças e o vosso gado (sei que têm muito gado) continuarão a morar nas cidades que vos dei

[[v5-3-20]]

^<<v5-3-20,20>>^ até que Jeová dê descanso aos vossos irmãos, assim como vos deu a vocês, e que eles também tenham tomado posse da terra que Jeová, vosso Deus, lhes dará do outro lado do Jordão. Então, vocês voltarão, cada um à propriedade que vos dei.’

[[v5-3-21]]

^<<v5-3-21,21>>^ “Naquele tempo, dei a seguinte ordem a Josué: ‘Viste com os teus próprios olhos o que Jeová, teu Deus, fez a estes dois reis. Jeová fará o mesmo a todos os reinos, por onde irás passar.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não tenham medo deles, pois Jeová, vosso Deus, é quem luta por vocês.’

[[v5-3-23]]

^<<v5-3-23,23>>^ “Naquele tempo, implorei a Jeová, dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ ‘Ó Soberano Senhor Jeová, começaste a mostrar ao teu servo a tua grandeza e o teu braço poderoso, pois que deus há nos céus ou na terra que realize atos poderosos como tu?

[[v5-3-25]]

^<<v5-3-25,25>>^ Por favor, deixa-me atravessar para o outro lado do Jordão e ver a boa terra, esta boa região montanhosa e o Líbano.’

[[v5-3-26]]

^<<v5-3-26,26>>^ Mas Jeová ainda estava furioso comigo por vossa causa e não me escutou. Em vez disso, Jeová disse-me: ‘Já chega! Nunca mais fales comigo sobre esse assunto.

[[v5-3-27]]

^<<v5-3-27,27>>^ Sobe ao cimo do Pisga e olha para o oeste, para o norte, para o sul e para o leste, e vê a terra com os teus olhos, pois não atravessarás o Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Designa Josué como líder, encoraja-o e fortalece-o, porque é ele quem atravessará diante deste povo e é ele quem os fará herdar a terra que verás.’

[[v5-3-29]]

^<<v5-3-29,29>>^ Tudo isto aconteceu enquanto morávamos no vale em frente a Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]