include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v34-3-1]]

^<<v34-3-1,1>>^ Ai da cidade de derramamento de sangue!
Está repleta de falsidade e de roubo.
Nunca fica sem presa.

[[v34-3-2]]

^<<v34-3-2,2>>^ O estalo dos chicotes, o barulho das rodas,
O galope dos cavalos, os solavancos dos carros de guerra.

[[v34-3-3]]

^<<v34-3-3,3>>^ Cavaleiros montados, espadas brilhantes, lanças reluzentes,
Inúmeros mortos, montes de cadáveres
— Os corpos não têm fim.
Tropeça-se nos mortos.

[[v34-3-4]]

^<<v34-3-4,4>>^ Isto deve-se aos muitos atos de prostituição da prostituta;
Ela é atraente e sedutora, senhora de feitiçarias,
Enlaça nações com a sua prostituição e famílias com as suas feitiçarias.

[[v34-3-5]]

^<<v34-3-5,5>>^ “Vê! Estou contra ti”,^&#42;1^ diz Jeová dos exércitos.
“Levantarei a tua saia até que cubra o teu rosto.
Farei com que as nações vejam a tua nudez;
E os reinos, a tua desonra.

[NOTE]
====
. Isto é, Nínive.
====

[[v34-3-6]]

^<<v34-3-6,6>>^ E vou lançar imundície sobre ti,
E tornar-te desprezível;
Farei de ti um espetáculo público.

[[v34-3-7]]

^<<v34-3-7,7>>^ Todos os que te virem fugirão e dirão:
‘Nínive foi devastada!
Quem é que terá compaixão dela?’
Onde é que vou encontrar quem te console?

[[v34-3-8]]

^<<v34-3-8,8>>^ Será que és melhor do que Nó-Amom,^&#42;1^ que ficava junto aos canais do Nilo?
Havia águas ao seu redor;
A sua riqueza era o mar, e a sua muralha era o mar.

[NOTE]
====
. Isto é, Tebes.
====

[[v34-3-9]]

^<<v34-3-9,9>>^ A Etiópia era a sua fonte de força ilimitada, bem como o Egito.
Pute e os líbios eram os teus ajudadores.

[[v34-3-10]]

^<<v34-3-10,10>>^ Contudo, até ela foi exilada;
Ela foi para o cativeiro.
As suas crianças também foram despedaçadas em todas as esquinas.^&#42;1^
Lançaram sortes sobre os seus homens de destaque,
E todos os seus homens importantes foram presos com correntes.

[NOTE]
====
. Lit.: “na cabeça de todas as ruas”.
====

[[v34-3-11]]

^<<v34-3-11,11>>^ Também ficarás bêbeda;
Terás de esconder-te.
Procurarás refúgio do inimigo.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as tuas fortificações são como figueiras com os primeiros frutos maduros;
Basta sacudi-las e os frutos caem na boca dos devoradores.

[[v34-3-13]]

^<<v34-3-13,13>>^ Vê! As tuas tropas são como mulheres no teu meio.
Os portões da tua terra ficarão totalmente abertos para os teus inimigos.
O fogo consumirá as trancas dos teus portões.

[[v34-3-14]]

^<<v34-3-14,14>>^ Tira água para quando fores sitiada.
Reforça as tuas fortificações.
Entra na lama e pisa a argila;
Segura a forma para fazer tijolos.

[[v34-3-15]]

^<<v34-3-15,15>>^ Até mesmo ali o fogo irá consumir-te.
A espada irá eliminar-te.
Ela vai devorar-te como fazem os gafanhotos jovens.
Torna-te tão numerosa como os gafanhotos jovens!
Sim, torna-te tão numerosa como os gafanhotos!

[[v34-3-16]]

^<<v34-3-16,16>>^ Multiplicaste os teus comerciantes, tornando-os mais numerosos do que as estrelas dos céus.
Os gafanhotos jovens mudam de pele e voam para longe.

[[v34-3-17]]

^<<v34-3-17,17>>^ Os teus guardas são como gafanhotos,
E os teus oficiais são como uma nuvem de gafanhotos.
Em dias de frio, eles refugiam-se nas brechas dos muros,^&#42;1^
Mas, quando o sol brilha, eles voam para longe;
Ninguém sabe para onde vão.

[NOTE]
====
. Ou: “nos currais de pedra”.
====

[[v34-3-18]]

^<<v34-3-18,18>>^ Os teus pastores estão sonolentos, ó rei da Assíria;
Os teus nobres permanecem nas suas residências.
O teu povo foi espalhado sobre os montes,
E não há quem o reúna.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há alívio para a tua catástrofe.
O teu ferimento é incurável.
Todos os que ouvirem as notícias a teu respeito baterão palmas,
Pois quem é que não sofreu por causa da tua implacável crueldade?”

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]