include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó gálatas insensatos! Quem vos sujeitou a esta má influência, a vocês que receberam uma explicação tão clara sobre a morte de Jesus Cristo na estaca?

[[v48-3-2]]

^<<v48-3-2,2>>^ Há uma coisa que vos quero perguntar:^&#42;1^ Será que vocês receberam o espírito através de obras exigidas por lei, ou foi por causa da fé no que ouviram?

[NOTE]
====
. Lit.: “quero aprender de vocês”.
====

[[v48-3-3]]

^<<v48-3-3,3>>^ Será que são assim tão insensatos? Depois de terem começado num caminho espiritual,^&#42;1^ estão a terminar num caminho carnal?^&#42;2^

[NOTE]
====
. Lit.: “começado em espírito”.
. Lit.: “a ser completados na carne”.
====

[[v48-3-4]]

^<<v48-3-4,4>>^ Será que foi em vão que sofreram tantas coisas? Tenho a certeza de que não foi em vão!

[[v48-3-5]]

^<<v48-3-5,5>>^ Portanto, será que aquele que vos fornece o espírito e realiza obras poderosas no vosso meio o faz por causa das vossas obras exigidas por lei, ou por causa da vossa fé no que ouviram?

[[v48-3-6]]

^<<v48-3-6,6>>^ É tal como aconteceu com Abraão: ele “depositou fé em Jeová,^&#42;1^ e isso foi-lhe creditado como justiça”.^&#42;2^

[NOTE]
====
. Veja o Ap. A5.
. Ou: “e foi considerado justo”.
====

[[v48-3-7]]

^<<v48-3-7,7>>^ Certamente sabem que os que têm^&#42;1^ fé é que são filhos de Abraão.

[NOTE]
====
. Ou: “aderem à”.
====

[[v48-3-8]]

^<<v48-3-8,8>>^ Certa passagem das Escrituras, prevendo que Deus declararia justas as pessoas das nações através da fé, declarou com antecedência as boas novas a Abraão, dizendo: “Por meio de ti, todas as nações serão abençoadas.”

[[v48-3-9]]

^<<v48-3-9,9>>^ Portanto, os que têm^&#42;1^ fé são abençoados com Abraão, que tinha fé.

[NOTE]
====
. Ou: “aderem à”.
====

[[v48-3-10]]

^<<v48-3-10,10>>^ Todos os que confiam nas obras exigidas por lei estão sob uma maldição, pois está escrito: “Maldito é todo aquele que não continua em todas as coisas escritas no rolo da Lei, deixando de as fazer.”

[[v48-3-11]]

^<<v48-3-11,11>>^ Além disso, é evidente que, por lei, ninguém é declarado justo perante Deus, pois “o justo viverá pela fé”.

[[v48-3-12]]

^<<v48-3-12,12>>^ Ora, a Lei não se baseia na fé. Em vez disso, “quem fizer estas coisas viverá por meio delas”.

[[v48-3-13]]

^<<v48-3-13,13>>^ Cristo comprou-nos, livrando-nos da maldição da Lei por se tornar maldição em nosso lugar, pois está escrito: “Maldito é todo aquele que é pendurado num madeiro.”

[[v48-3-14]]

^<<v48-3-14,14>>^ Isto aconteceu para que a bênção de Abraão se estendesse às nações por meio de Cristo Jesus, para que recebêssemos o espírito prometido por meio da nossa fé.

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, ao falar convosco, uso uma ilustração humana: uma vez que um pacto é validado, nem que seja apenas por um homem, ninguém o anula nem lhe faz acréscimos.

[[v48-3-16]]

^<<v48-3-16,16>>^ Ora, as promessas foram feitas a Abraão e ao seu descendente.^&#42;1^ As Escrituras não dizem “e aos teus descendentes”,^&#42;2^ como se fossem muitos. Em vez disso, dizem “e ao teu descendente”,^&#42;3^ indicando um só, que é Cristo.

[NOTE]
====
. Lit.: “à sua semente”.
. Lit.: “às sementes”.
. Lit.: “à tua semente”.
====

[[v48-3-17]]

^<<v48-3-17,17>>^ Além disso, digo o seguinte: A Lei, que veio à existência 430 anos depois, não invalida o pacto anteriormente feito por Deus, de modo a anular a promessa.

[[v48-3-18]]

^<<v48-3-18,18>>^ Pois, se a herança se baseia numa lei, já não se baseia numa promessa; mas Deus deu-a bondosamente a Abraão através de uma promessa.

[[v48-3-19]]

^<<v48-3-19,19>>^ Porquê, então, a Lei? Ela foi acrescentada para tornar conhecidas as transgressões, até que chegasse o descendente^&#42;1^ a quem a promessa tinha sido feita; e ela foi transmitida por meio de anjos, pela mão de um mediador.

[NOTE]
====
. Lit.: “a semente”.
====

[[v48-3-20]]

^<<v48-3-20,20>>^ Ora, não há mediador quando está envolvida apenas uma pessoa, mas Deus é apenas um.

[[v48-3-21]]

^<<v48-3-21,21>>^ Será que, então, a Lei é contra as promessas de Deus? De maneira nenhuma! Pois, se tivesse sido dada uma lei que fosse capaz de dar vida, a justiça teria realmente vindo por meio da lei.

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas as Escrituras entregaram tudo à custódia do pecado, para que a promessa resultante da fé em Jesus Cristo fosse dada aos que exercessem fé.

[[v48-3-23]]

^<<v48-3-23,23>>^ No entanto, antes de chegar a fé, estávamos a ser guardados debaixo da lei, entregues à custódia, aguardando a fé que havia de ser revelada.

[[v48-3-24]]

^<<v48-3-24,24>>^ A Lei, portanto, tornou-se o nosso tutor,^&#42;1^ conduzindo a Cristo, para que fôssemos declarados justos através da fé.

[NOTE]
====
. Ou: “guardião”.
====

[[v48-3-25]]

^<<v48-3-25,25>>^ Mas, agora que chegou a fé, já não estamos sujeitos a um tutor.^&#42;1^

[NOTE]
====
. Ou: “guardião”.
====

[[v48-3-26]]

^<<v48-3-26,26>>^ Todos vocês são, de facto, filhos de Deus, por meio da vossa fé em Cristo Jesus.

[[v48-3-27]]

^<<v48-3-27,27>>^ Pois todos vocês, que foram batizados em Cristo, revestiram-se de Cristo.

[[v48-3-28]]

^<<v48-3-28,28>>^ Não há nem judeu nem grego, nem escravo nem homem livre, nem homem nem mulher; pois todos vocês são um só em união com Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ Além disso, se pertencem a Cristo, são realmente a descendência^&#42;1^ de Abraão, herdeiros segundo uma promessa.

[NOTE]
====
. Lit.: “semente”.
====

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]