include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v48-5-1]]

^<<v48-5-1,1>>^ Foi para tal liberdade que Cristo nos libertou. Portanto, mantenham-se firmes e não se deixem submeter novamente a um jugo de escravidão.

[[v48-5-2]]

^<<v48-5-2,2>>^ Prestem atenção! Eu, Paulo, digo-vos que, se forem circuncidados, Cristo não vos será de nenhum valor.

[[v48-5-3]]

^<<v48-5-3,3>>^ A todo o homem que se submete à circuncisão, declaro novamente que ele está sob a obrigação de cumprir toda a Lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Vocês que tentam ser declarados justos por meio da lei estão separados de Cristo; excluíram-se^&#42;1^ da sua bondade imerecida.

[NOTE]
====
. Ou: “decaíram”.
====

[[v48-5-5]]

^<<v48-5-5,5>>^ Quanto a nós, por espírito, aguardamos ansiosamente a esperada justiça que resulta da fé.

[[v48-5-6]]

^<<v48-5-6,6>>^ Pois, em união com Cristo Jesus, nem a circuncisão nem a incircuncisão são de valor algum, mas sim a fé que age por meio do amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vocês estavam a correr bem. Quem vos impediu de continuar a obedecer à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Este tipo de persuasão não vem d’Aquele que vos chama.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda a massa toda.

[[v48-5-10]]

^<<v48-5-10,10>>^ Estou confiante de que vocês que estão em união com o Senhor não pensarão de outra maneira; mas aquele que vos perturba, não importa quem seja, terá o julgamento que merece.

[[v48-5-11]]

^<<v48-5-11,11>>^ Quanto a mim, irmãos, se eu ainda prego a circuncisão, porque é que ainda estou a ser perseguido? Nesse caso, a pedra de tropeço da estaca^&#42;1^ foi eliminada.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v48-5-12]]

^<<v48-5-12,12>>^ Eu queria que os homens que vos tentam perturbar se castrassem a si mesmos.^&#42;1^

[NOTE]
====
. Ou: “se tornassem eunucos”, e assim ficassem desqualificados para cumprir a lei que defendiam.
====

[[v48-5-13]]

^<<v48-5-13,13>>^ Vocês foram chamados à liberdade, irmãos. Só não usem esta liberdade como uma oportunidade para procurarem os desejos da carne; pelo contrário, através do amor, trabalhem como escravos uns para os outros.

[[v48-5-14]]

^<<v48-5-14,14>>^ Pois toda a Lei se cumpre^&#42;1^ num só mandamento: “Ama o teu próximo como a ti mesmo.”

[NOTE]
====
. Ou, possivelmente: “resume”.
====

[[v48-5-15]]

^<<v48-5-15,15>>^ Se vocês, porém, se continuarem a morder e a devorar uns aos outros, cuidado para não serem destruídos uns pelos outros.

[[v48-5-16]]

^<<v48-5-16,16>>^ Mas eu digo: Continuem a andar por espírito, e não executarão nenhum desejo carnal.

[[v48-5-17]]

^<<v48-5-17,17>>^ Pois a carne é contra o espírito no seu desejo, e o espírito contra a carne; eles opõem-se um ao outro. É por isso que vocês não fazem as coisas que querem fazer.

[[v48-5-18]]

^<<v48-5-18,18>>^ Além disso, se vocês são conduzidos pelo espírito, não estão debaixo de lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ As obras da carne são claramente vistas. Elas são as seguintes: imoralidade sexual,^&#42;1^ impureza, conduta insolente,^&#42;2^

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
. Ou: “conduta desavergonhada”. Em grego, asélgeia. Veja o Glossário.
====

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria, ocultismo,^&#42;1^ inimizades, conflitos, ciúme, acessos de ira, discórdias, divisões, formação de seitas,

[NOTE]
====
. Ou: “feitiçaria; espiritismo”. Veja o Glossário.
====

[[v48-5-21]]

^<<v48-5-21,21>>^ inveja, embriaguez, festas descontroladas^&#42;1^ e coisas como estas. Estou a advertir-vos a respeito destas coisas, do mesmo modo como já vos adverti: os que praticam tais coisas não herdarão o Reino de Deus.

[NOTE]
====
. Ou: “festanças”.
====

[[v48-5-22]]

^<<v48-5-22,22>>^ Por outro lado, o fruto do espírito é: amor, alegria, paz, paciência,^&#42;1^ bondade, benignidade, fé,

[NOTE]
====
. Ou: “longanimidade”.
====

[[v48-5-23]]

^<<v48-5-23,23>>^ brandura, autodomínio. Contra tais coisas não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ Além disso, os que pertencem a Cristo Jesus pregaram na estaca a carne com as suas paixões e desejos.

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos por espírito, continuemos também a andar^&#42;1^ de acordo com o espírito.

[NOTE]
====
. Ou: “a andar ordeiramente”.
====

[[v48-5-26]]

^<<v48-5-26,26>>^ Não nos tornemos presunçosos, atiçando competição uns contra os outros, invejando-nos uns aos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]