include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, mesmo que um homem, sem se aperceber, dê um passo em falso, vocês que têm qualificações espirituais tentem reajustar tal homem num espírito de brandura. Mas que cada um olhe para si mesmo, para que não seja tentado também.

[[v48-6-2]]

^<<v48-6-2,2>>^ Continuem a levar os fardos uns dos outros e, desta maneira, cumprirão a lei do Cristo.

[[v48-6-3]]

^<<v48-6-3,3>>^ Pois, se alguém acha que é alguma coisa, quando não é nada, engana-se a si mesmo.

[[v48-6-4]]

^<<v48-6-4,4>>^ Mas que cada um examine as suas próprias ações, e então terá motivo para se alegrar apenas com respeito a si mesmo, e não em comparação com os outros.

[[v48-6-5]]

^<<v48-6-5,5>>^ Pois cada um levará a sua própria carga.^&#42;1^

[NOTE]
====
. Ou: “carga de responsabilidade”.
====

[[v48-6-6]]

^<<v48-6-6,6>>^ Além disso, que todo aquele a quem a palavra estiver a ser ensinada^&#42;1^ partilhe todas as coisas boas com quem o ensina.^&#42;2^

[NOTE]
====
. Ou: “ensinada oralmente”.
. Ou: “ensina oralmente”.
====

[[v48-6-7]]

^<<v48-6-7,7>>^ Não se enganem: com Deus não se brinca. Pois o que a pessoa semear, isso também colherá;

[[v48-6-8]]

^<<v48-6-8,8>>^ porque aquele que semeia visando a carne colherá da carne destruição,^&#42;1^ mas aquele que semeia visando o espírito colherá do espírito vida eterna.

[NOTE]
====
. Lit.: “corrupção”.
====

[[v48-6-9]]

^<<v48-6-9,9>>^ Assim, não desistamos de fazer o que é bom, pois colheremos no tempo devido, se não desanimarmos.^&#42;1^

[NOTE]
====
. Ou: “desistirmos”.
====

[[v48-6-10]]

^<<v48-6-10,10>>^ Então, enquanto tivermos oportunidade,^&#42;1^ façamos o bem a todos, mas especialmente aos que fazem parte da nossa família na fé.

[NOTE]
====
. Lit.: “tempo determinado”.
====

[[v48-6-11]]

^<<v48-6-11,11>>^ Vejam com que grandes letras vos escrevi com a minha própria mão.

[[v48-6-12]]

^<<v48-6-12,12>>^ Aqueles que querem causar uma boa impressão segundo padrões humanos^&#42;1^ são os que vos tentam obrigar a ser circuncidados, e eles fazem-no apenas para não serem perseguidos por causa da estaca^&#42;2^ do Cristo.

[NOTE]
====
. Lit.: “mostrar uma boa aparência na carne”.
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v48-6-13]]

^<<v48-6-13,13>>^ Pois mesmo os que se submetem à circuncisão não cumprem a Lei, mas querem que vocês sejam circuncidados para que eles tenham motivos para se gabar do vosso corpo.^&#42;1^

[NOTE]
====
. Lit.: “na vossa carne”.
====

[[v48-6-14]]

^<<v48-6-14,14>>^ No entanto, que eu nunca me gabe de nada, a não ser da estaca^&#42;1^ do nosso Senhor Jesus Cristo; por meio dele, o mundo, para mim, está morto,^&#42;2^ e eu estou morto para o mundo.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
. Ou: “foi morto na estaca”.
====

[[v48-6-15]]

^<<v48-6-15,15>>^ Pois o que importa não é a circuncisão nem a incircuncisão, mas sim uma nova criação.

[[v48-6-16]]

^<<v48-6-16,16>>^ Que haja paz e misericórdia sobre todos os que vivem^&#42;1^ de acordo com esta regra de conduta, sim, sobre o Israel de Deus.

[NOTE]
====
. Ou: “andam ordeiramente”.
====

[[v48-6-17]]

^<<v48-6-17,17>>^ De agora em diante, que ninguém me cause dificuldades, pois trago no corpo as marcas de um escravo de Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ Que a bondade imerecida do nosso Senhor Jesus Cristo esteja com o espírito que mostram, irmãos. Amém.

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]