include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v48-4-1]]

^<<v48-4-1,1>>^ Digo, porém, que, enquanto o herdeiro é uma criança, não difere em nada de um escravo, embora seja senhor de tudo,

[[v48-4-2]]

^<<v48-4-2,2>>^ mas está sujeito a supervisores e administradores até ao dia marcado com antecedência pelo seu pai.

[[v48-4-3]]

^<<v48-4-3,3>>^ Da mesma forma, quando éramos crianças, também estávamos escravizados às coisas elementares do mundo.

[[v48-4-4]]

^<<v48-4-4,4>>^ Mas, quando se completou o tempo, Deus enviou o seu Filho, que nasceu de uma mulher e estava debaixo de lei,

[[v48-4-5]]

^<<v48-4-5,5>>^ para livrar por meio de uma compra os debaixo de lei, para que recebêssemos a adoção como filhos.

[[v48-4-6]]

^<<v48-4-6,6>>^ Assim, visto que vocês são filhos, Deus enviou o espírito do seu Filho aos nossos corações, e o espírito clama: “Aba,^&#42;1^ Pai!”

[NOTE]
====
. Palavra hebraica ou aramaica que significa “ó Pai!”
====

[[v48-4-7]]

^<<v48-4-7,7>>^ Portanto, já não és escravo, mas filho; e, se és filho, então, Deus também te fez herdeiro.

[[v48-4-8]]

^<<v48-4-8,8>>^ Contudo, quando não conheciam a Deus, eram escravos dos que não são realmente deuses.

[[v48-4-9]]

^<<v48-4-9,9>>^ No entanto, agora que conhecem a Deus, ou melhor, que são conhecidos por Deus, como é que voltam novamente às coisas elementares, fracas e mesquinhas, e querem novamente ser escravos delas?

[[v48-4-10]]

^<<v48-4-10,10>>^ Vocês guardam rigorosamente dias, meses, épocas e anos.

[[v48-4-11]]

^<<v48-4-11,11>>^ Temo por vocês, que de alguma maneira os meus esforços para convosco tenham sido em vão.

[[v48-4-12]]

^<<v48-4-12,12>>^ Irmãos, suplico-vos: Tornem-se como eu, porque eu também era como vocês. Vocês não me fizeram mal nenhum.

[[v48-4-13]]

^<<v48-4-13,13>>^ Mas sabem que foi por causa de uma doença que tive a primeira oportunidade de vos declarar as boas novas.

[[v48-4-14]]

^<<v48-4-14,14>>^ E, embora a minha condição física tenha sido uma provação para vocês, não me trataram com desprezo nem com repugnância;^&#42;1^ mas receberam-me como a um anjo de Deus, como a Cristo Jesus.

[NOTE]
====
. Ou: “nem me cuspiram”.
====

[[v48-4-15]]

^<<v48-4-15,15>>^ Onde está aquela felicidade que tinham? Pois eu tenho a certeza de que, se tivesse sido possível, até teriam arrancado os vossos olhos e os teriam dado a mim.

[[v48-4-16]]

^<<v48-4-16,16>>^ Será que, porventura, me tornei vosso inimigo por vos dizer a verdade?

[[v48-4-17]]

^<<v48-4-17,17>>^ Eles procuram zelosamente ganhar-vos, mas não com boas intenções; querem afastar-vos de mim, para que vocês se dediquem a segui-los.

[[v48-4-18]]

^<<v48-4-18,18>>^ Na verdade, é sempre bom que alguém vos procure ganhar zelosamente com boas intenções, e não só quando estou na vossa presença,

[[v48-4-19]]

^<<v48-4-19,19>>^ meus queridos filhos, pelos quais estou novamente com dores de parto até que Cristo seja formado^&#42;1^ em vocês.

[NOTE]
====
. Ou: “tome forma”.
====

[[v48-4-20]]

^<<v48-4-20,20>>^ Como gostaria de estar agora aí convosco e falar-vos de modo diferente, pois estou perplexo por vossa causa.

[[v48-4-21]]

^<<v48-4-21,21>>^ Digam-me, vocês que querem estar debaixo de lei: Não dão ouvidos à Lei?

[[v48-4-22]]

^<<v48-4-22,22>>^ Por exemplo, está escrito que Abraão teve dois filhos, um com a serva e o outro com a livre;

[[v48-4-23]]

^<<v48-4-23,23>>^ mas o filho da serva foi gerado de maneira natural,^&#42;1^ e o outro, o filho da livre, por meio de uma promessa.

[NOTE]
====
. Lit.: “segundo a carne”.
====

[[v48-4-24]]

^<<v48-4-24,24>>^ Estas coisas são um drama simbólico; pois estas mulheres representam dois pactos, um do monte Sinai, que gera filhos para a escravidão, e que é Agar.

[[v48-4-25]]

^<<v48-4-25,25>>^ Agar representa o Sinai, um monte na Arábia, e corresponde à Jerusalém atual, pois está em escravidão com os seus filhos.

[[v48-4-26]]

^<<v48-4-26,26>>^ Mas a Jerusalém de cima é livre, e ela é a nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Pois está escrito: “Alegra-te, ó mulher estéril, que não dás à luz; grita de alegria, ó mulher que não tens dores de parto; pois os filhos da mulher abandonada são mais numerosos do que os daquela que tem marido.”

[[v48-4-28]]

^<<v48-4-28,28>>^ Vocês, irmãos, são filhos da promessa, assim como Isaque foi.

[[v48-4-29]]

^<<v48-4-29,29>>^ Mas, assim como naquele tempo o gerado de maneira natural^&#42;1^ começou a perseguir o gerado por meio do espírito, assim acontece agora.

[NOTE]
====
. Lit.: “segundo a carne”.
====

[[v48-4-30]]

^<<v48-4-30,30>>^ Contudo, o que dizem as Escrituras? “Expulsa a serva e o seu filho, pois o filho da serva não será, de maneira nenhuma, herdeiro com o filho da livre.”

[[v48-4-31]]

^<<v48-4-31,31>>^ Portanto, irmãos, não somos filhos de uma serva, mas da mulher livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]