include::./index.adoc[]

[[v21-10-0]]
=== Eclesiastes, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v21-10-1]]

^<<v21-10-1,1>>^ Assim como moscas mortas fazem com que o óleo do perfumista se estrague e cheire mal, assim também uma pequena tolice pesa mais do que a sabedoria e a glória.

[[v21-10-2]]

^<<v21-10-2,2>>^ O coração do sábio guia-o no caminho certo,^&#42;1^ mas o coração do tolo guia-o no caminho errado.^&#42;2^

[NOTE]
====
. Lit.: “está à sua direita”.
. Lit.: “está à sua esquerda”.
====

[[v21-10-3]]

^<<v21-10-3,3>>^ Seja qual for o caminho em que ande, o tolo age sem bom senso^&#42;1^ e mostra a todos que é um tolo.

[NOTE]
====
. Lit.: “o seu coração é falto”.
====

[[v21-10-4]]

^<<v21-10-4,4>>^ Se a ira^&#42;1^ de um governante se acender contra ti, não deixes o teu lugar, pois a calma abranda grandes pecados.

[NOTE]
====
. Lit.: “o espírito; o fôlego”.
====

[[v21-10-5]]

^<<v21-10-5,5>>^ Há algo aflitivo que vi debaixo do sol, o tipo de erro que é cometido pelos que estão no poder:

[[v21-10-6]]

^<<v21-10-6,6>>^ os tolos são postos em^&#42;1^ muitas posições elevadas, mas os ricos^&#42;2^ continuam em posições inferiores.

[NOTE]
====
. Ou: “a tolice ocupa”.
. Ou: “os hábeis”.
====

[[v21-10-7]]

^<<v21-10-7,7>>^ Vi servos a andar a cavalo, mas príncipes a andar a pé como se fossem servos.

[[v21-10-8]]

^<<v21-10-8,8>>^ Quem cava um buraco pode cair nele; e quem derruba um muro de pedras pode ser picado por uma cobra.

[[v21-10-9]]

^<<v21-10-9,9>>^ Quem extrai pedras, pode ferir-se com elas, e quem racha lenha expõe-se ao perigo.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “deve ter cuidado com ela”.
====

[[v21-10-10]]

^<<v21-10-10,10>>^ Se uma ferramenta deixar de cortar e não for afiada, será preciso fazer muito esforço. Porém, a sabedoria ajuda a obter sucesso.

[[v21-10-11]]

^<<v21-10-11,11>>^ Se a serpente picar antes de ser encantada, não haverá vantagem para o encantador hábil.^&#42;1^

[NOTE]
====
. Lit.: “o mestre da língua”.
====

[[v21-10-12]]

^<<v21-10-12,12>>^ As palavras que saem da boca do sábio trazem favor, mas os lábios do tolo são a sua ruína:

[[v21-10-13]]

^<<v21-10-13,13>>^ as suas primeiras palavras são tolice, e as últimas são uma loucura desastrosa.

[[v21-10-14]]

^<<v21-10-14,14>>^ Contudo, o tolo continua a falar.
O homem não sabe o que vai acontecer; quem é que pode informá-lo do que virá depois dele?

[[v21-10-15]]

^<<v21-10-15,15>>^ O trabalho árduo do tolo esgota-o, pois ele nem sequer sabe encontrar o caminho para a cidade.

[[v21-10-16]]

^<<v21-10-16,16>>^ Que desastroso é para um país quando o seu rei é uma criança e os seus príncipes começam a banquetear-se de manhã!

[[v21-10-17]]

^<<v21-10-17,17>>^ Como é feliz o país cujo rei é filho de nobres e cujos príncipes se alimentam no tempo certo, para recuperar as forças, e não apenas para se embriagarem!

[[v21-10-18]]

^<<v21-10-18,18>>^ Por causa da extrema preguiça, as vigas do telhado cedem e, por causa das mãos ociosas, a casa tem goteiras.

[[v21-10-19]]

^<<v21-10-19,19>>^ O pão^&#42;1^ é feito para dar alegria, e o vinho torna a vida prazerosa; mas o dinheiro satisfaz todas as necessidades.

[NOTE]
====
. Ou: “alimento”.
====

[[v21-10-20]]

^<<v21-10-20,20>>^ Não amaldiçoes^&#42;1^ o rei, nem sequer em pensamento,^&#42;2^ e não amaldiçoes o rico no teu quarto; pois um pássaro^&#42;3^ pode levar as tuas palavras,^&#42;4^ e uma ave pode contar o que disseste.

[NOTE]
====
. Ou: “invoques o mal sobre”.
. Ou, possivelmente: “na tua cama”.
. Lit.: “uma criatura voadora dos céus”.
. Ou: “a mensagem”.
====

'''

xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]