include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v21-1-1]]

^<<v21-1-1,1>>^ As palavras do congregante,^&#42;1^ filho de David, rei em Jerusalém.

[NOTE]
====
. Ou: “daquele que reúne (convoca)”.
====

[[v21-1-2]]

^<<v21-1-2,2>>^ “A maior das vaidades!”,^&#42;1^ diz o congregante,
“A maior das vaidades! Tudo é vão!”

[NOTE]
====
. Ou: “futilidades”.
====

[[v21-1-3]]

^<<v21-1-3,3>>^ O que é que o homem ganha com todo o seu trabalho árduo,
Pelo qual tanto se esforça debaixo do sol?

[[v21-1-4]]

^<<v21-1-4,4>>^ Uma geração vai e outra geração vem,
Mas a terra permanece^&#42;1^ para sempre.

[NOTE]
====
. Lit.: “está de pé”.
====

[[v21-1-5]]

^<<v21-1-5,5>>^ O sol nasce^&#42;1^ e o sol põe-se;
Depois, volta depressa^&#42;2^ ao lugar onde nasce novamente.

[NOTE]
====
. Ou: “brilha”.
. Ou: “ofegante”.
====

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento sopra para o sul e gira para o norte;
Dá voltas e mais voltas, girando continuamente; o vento continua a dar as suas voltas.

[[v21-1-7]]

^<<v21-1-7,7>>^ Todos os rios^&#42;1^ correm para o mar; mesmo assim, o mar não se enche.
Os rios voltam para o lugar de onde saíram, a fim de correrem novamente.

[NOTE]
====
. Ou: “Todas as torrentes de inverno; Todas as torrentes sazonais”.
====

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas as coisas são cansativas,
Mais do que se pode dizer.
O olho não se satisfaz com o que vê,
Nem o ouvido se sacia com o que ouve.

[[v21-1-9]]

^<<v21-1-9,9>>^ O que foi é o que há de ser,
E o que foi feito há de ser feito novamente;
Não há nada de novo debaixo do sol.

[[v21-1-10]]

^<<v21-1-10,10>>^ Será que há alguma coisa da qual se possa dizer: “Olha, isto é novo”?
Tudo já existe há muito tempo;
Já existia antes da nossa época.

[[v21-1-11]]

^<<v21-1-11,11>>^ Ninguém se lembra dos que viveram nos tempos antigos;
E ninguém se lembrará dos que vierem depois;
Nem estes serão lembrados pelos que vierem depois deles.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o congregante, tornei-me rei sobre Israel, em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ Empenhei-me em estudar e investigar com sabedoria tudo o que se faz debaixo dos céus — a ocupação penosa que Deus deu aos filhos dos homens, que os mantém ocupados.

[[v21-1-14]]

^<<v21-1-14,14>>^ Vi tudo o que se faz debaixo do sol,
E concluí que tudo é vão, é correr atrás do vento.

[[v21-1-15]]

^<<v21-1-15,15>>^ Não se pode endireitar o que é torto,
Nem se pode enumerar o que está em falta.

[[v21-1-16]]

^<<v21-1-16,16>>^ Eu disse no meu coração: “Bem, adquiri grande sabedoria, mais do que qualquer outro antes de mim em Jerusalém, e o meu coração obteve muita sabedoria e conhecimento.”

[[v21-1-17]]

^<<v21-1-17,17>>^ Dediquei-me a conhecer a sabedoria, a conhecer a loucura^&#42;1^ e a conhecer a tolice — e isto também é correr atrás do vento.

[NOTE]
====
. Ou: “tolice extrema”.
====

[[v21-1-18]]

^<<v21-1-18,18>>^ Porque muita sabedoria traz muita frustração,
De modo que aquele que aumenta o seu conhecimento aumenta a sua dor.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]