include::./index.adoc[]

[[v21-9-0]]
=== Eclesiastes, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v21-9-1]]

^<<v21-9-1,1>>^ Assim, refleti sobre tudo isto e concluí que os justos e os sábios, bem como as suas obras, estão nas mãos do verdadeiro Deus. Os homens não se apercebem do amor nem do ódio que houve antes deles.

[[v21-9-2]]

^<<v21-9-2,2>>^ Todos têm o mesmo fim: o justo e o injusto, o bom e puro e o impuro, aqueles que oferecem sacrifícios e aqueles que não oferecem sacrifícios. O bom é igual ao pecador; quem faz juramentos é igual àquele que pensa antes de fazer um juramento.

[[v21-9-3]]

^<<v21-9-3,3>>^ Uma coisa aflitiva que acontece debaixo do sol é a seguinte: visto que todos têm o mesmo fim, o coração dos humanos está cheio de maldade; há loucura no seu coração durante a sua vida e, depois, eles morrem!^&#42;1^

[NOTE]
====
. Lit.: “e depois disso — aos mortos”.
====

[[v21-9-4]]

^<<v21-9-4,4>>^ Há esperança para aquele que está entre os vivos, porque mais vale um cão vivo do que um leão morto.

[[v21-9-5]]

^<<v21-9-5,5>>^ Pois os vivos sabem^&#42;1^ que morrerão, mas os mortos não sabem absolutamente nada, nem têm mais nenhuma recompensa,^&#42;2^ porque qualquer recordação deles caiu no esquecimento.

[NOTE]
====
. Ou: “têm consciência de”.
. Ou: “salário”.
====

[[v21-9-6]]

^<<v21-9-6,6>>^ Também o seu amor, o seu ódio e o seu ciúme já não existem, e eles já não participam em nada do que se faz debaixo do sol.

[[v21-9-7]]

^<<v21-9-7,7>>^ Vai, come o teu alimento com alegria e bebe o teu vinho com o coração alegre, pois o verdadeiro Deus já se agradou das tuas obras.

[[v21-9-8]]

^<<v21-9-8,8>>^ Sejam sempre brancas as tuas roupas,^&#42;1^ e não deixes de pôr óleo sobre a tua cabeça.

[NOTE]
====
. Isto é, roupas claras, refletindo uma disposição alegre, e não roupas de luto.
====

[[v21-9-9]]

^<<v21-9-9,9>>^ Goza a vida com a tua amada esposa todos os dias da tua vida vã, que Ele te deu debaixo do sol, sim, durante todos os teus dias vãos. Pois esta é a tua porção na vida e no teu trabalho árduo, no qual tanto te esforças debaixo do sol.

[[v21-9-10]]

^<<v21-9-10,10>>^ Tudo o que te vier à mão para fazer, fá-lo com toda a tua força, pois não há trabalho, nem planeamento, nem conhecimento, nem sabedoria na Sepultura,^&#42;1^ o lugar para onde vais.

[NOTE]
====
. Ou: “no Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v21-9-11]]

^<<v21-9-11,11>>^ E vi ainda outra coisa debaixo do sol: os velozes nem sempre vencem a corrida, e nem sempre os fortes vencem a batalha; os sábios nem sempre têm alimento, os inteligentes nem sempre têm riquezas, os que têm conhecimento nem sempre têm sucesso; porque o tempo e o imprevisto sobrevêm-lhes a todos.

[[v21-9-12]]

^<<v21-9-12,12>>^ Pois o homem não sabe a sua hora. Assim como os peixes são apanhados numa rede cruel e os pássaros são apanhados numa armadilha, assim também os filhos dos homens são enlaçados na hora da desgraça,^&#42;1^ quando esta lhes sobrevém de repente.

[NOTE]
====
. Ou: “calamidade”.
====

[[v21-9-13]]

^<<v21-9-13,13>>^ Também vi, debaixo do sol, este exemplo de sabedoria, que me impressionou:

[[v21-9-14]]

^<<v21-9-14,14>>^ havia uma pequena cidade, com poucos homens. Um rei poderoso veio contra ela e sitiou-a, e construiu grandes obras de cerco contra ela.

[[v21-9-15]]

^<<v21-9-15,15>>^ Havia ali um homem pobre, mas sábio, e ele salvou a cidade com a sua sabedoria. No entanto, ninguém se lembrou daquele homem pobre.

[[v21-9-16]]

^<<v21-9-16,16>>^ E eu disse para comigo: “A sabedoria é melhor do que a força; apesar disso, a sabedoria do pobre é desprezada e as suas palavras não são ouvidas.”

[[v21-9-17]]

^<<v21-9-17,17>>^ É melhor ouvir as palavras calmas dos sábios do que os gritos de quem governa entre os tolos.

[[v21-9-18]]

^<<v21-9-18,18>>^ A sabedoria é melhor do que armas de guerra, mas um único pecador pode destruir muitas coisas boas.

'''

xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[&#60; Capítulo Anterior] | <<v21-9-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[Próximo Capítulo &#62;]