include::./index.adoc[]

[[v6-4-0]]
=== Josué, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-4-1]]

^<<v6-4-1,1>>^ Assim que toda a nação acabou de atravessar o Jordão, Jeová disse a Josué:

[[v6-4-2]]

^<<v6-4-2,2>>^ “Escolham 12 homens dentre o povo, um homem de cada tribo,

[[v6-4-3]]

^<<v6-4-3,3>>^ e deem-lhes a seguinte ordem: ‘Peguem em 12 pedras do meio do Jordão, do lugar onde os pés dos sacerdotes ficaram parados; levem-nas convosco e coloquem-nas no lugar onde passarão a noite.’”

[[v6-4-4]]

^<<v6-4-4,4>>^ Então, Josué chamou os 12 homens que tinha designado dentre os israelitas, um homem de cada tribo,

[[v6-4-5]]

^<<v6-4-5,5>>^ e Josué disse-lhes: “Passem à frente da Arca de Jeová, vosso Deus, até ao meio do Jordão, e cada um de vocês deve pôr uma pedra ao ombro, segundo o número das tribos dos israelitas,

[[v6-4-6]]

^<<v6-4-6,6>>^ para servir de sinal no vosso meio. Se mais tarde os vossos filhos vos perguntarem: ‘Porque é que estas pedras estão aqui?’

[[v6-4-7]]

^<<v6-4-7,7>>^ têm de lhes responder: ‘É porque as águas do Jordão foram interrompidas diante da Arca do Pacto de Jeová. Quando ela atravessou o Jordão, as águas do Jordão foram interrompidas. Estas pedras servirão de recordação^&#42;1^ permanente para o povo de Israel.’”

[NOTE]
====
. Ou: “lembrete”.
====

[[v6-4-8]]

^<<v6-4-8,8>>^ Portanto, os israelitas fizeram como Josué tinha ordenado. Pegaram em 12 pedras do meio do Jordão, assim como Jeová tinha instruído Josué, uma para cada tribo dos israelitas. Levaram-nas para o lugar onde passariam a noite e colocaram-nas ali.

[[v6-4-9]]

^<<v6-4-9,9>>^ Josué também colocou de pé 12 pedras no meio do Jordão, no lugar onde tinham ficado os pés dos sacerdotes que carregaram a Arca do Pacto, e as pedras continuam lá até ao dia de hoje.

[[v6-4-10]]

^<<v6-4-10,10>>^ Os sacerdotes que carregavam a Arca permaneceram parados no meio do Jordão até que se fez tudo o que Jeová tinha ordenado ao povo por meio de Josué, em harmonia com tudo o que Moisés tinha ordenado a Josué. Enquanto isso, o povo atravessava apressadamente.

[[v6-4-11]]

^<<v6-4-11,11>>^ Assim que todo o povo tinha acabado de atravessar, a Arca de Jeová e os sacerdotes atravessaram à vista do povo.

[[v6-4-12]]

^<<v6-4-12,12>>^ E os rubenitas, os gaditas e a meia tribo de Manassés atravessaram em formação de batalha à frente dos outros israelitas, assim como Moisés os tinha instruído.

[[v6-4-13]]

^<<v6-4-13,13>>^ Cerca de 40 000 soldados armados para a batalha atravessaram diante de Jeová rumo às planícies desérticas de Jericó.

[[v6-4-14]]

^<<v6-4-14,14>>^ Naquele dia, Jeová enalteceu Josué aos olhos de todo o Israel. E eles respeitaram-no profundamente^&#42;1^ durante todos os dias da sua vida, assim como tinham respeitado profundamente Moisés.

[NOTE]
====
. Lit.: “eles temeram-no”.
====

[[v6-4-15]]

^<<v6-4-15,15>>^ Então, Jeová disse a Josué:

[[v6-4-16]]

^<<v6-4-16,16>>^ “Ordena aos sacerdotes que carregam a Arca do Testemunho que saiam do Jordão.”

[[v6-4-17]]

^<<v6-4-17,17>>^ Portanto, Josué ordenou aos sacerdotes: “Saiam do Jordão.”

[[v6-4-18]]

^<<v6-4-18,18>>^ Quando os sacerdotes que carregavam a Arca do Pacto de Jeová saíram do meio do Jordão, e os pés dos sacerdotes pisaram terra seca, as águas do Jordão retomaram o seu curso e inundaram as margens, assim como antes.

[[v6-4-19]]

^<<v6-4-19,19>>^ O povo saiu do Jordão no dia dez do primeiro mês e acampou em Gilgal, na fronteira leste de Jericó.

[[v6-4-20]]

^<<v6-4-20,20>>^ Quanto às 12 pedras que tinham tirado do Jordão, Josué colocou-as de pé em Gilgal.

[[v6-4-21]]

^<<v6-4-21,21>>^ Então, ele disse aos israelitas: “No futuro, quando os filhos perguntarem aos pais: ‘O que é que significam estas pedras?’,

[[v6-4-22]]

^<<v6-4-22,22>>^ vocês explicarão aos vossos filhos: ‘Israel atravessou o Jordão em terra seca

[[v6-4-23]]

^<<v6-4-23,23>>^ quando Jeová, vosso Deus, secou as águas do Jordão diante deles até que o tivessem atravessado, assim como Jeová, vosso Deus, tinha feito com o mar Vermelho quando o secou diante de nós até que o tivéssemos atravessado.

[[v6-4-24]]

^<<v6-4-24,24>>^ Ele fez isso para que todos os povos da terra saibam como a mão de Jeová é poderosa, e para que vocês temam sempre a Jeová, vosso Deus.’”

'''

xref:006-josue/006-josue-003.adoc#v6-3-0[&#60; Capítulo Anterior] | <<v6-4-0,Topo>> | xref:006-josue/006-josue-005.adoc#v6-5-0[Próximo Capítulo &#62;]