include::./index.adoc[]

[[v6-6-0]]
=== Josué, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-6-1]]

^<<v6-6-1,1>>^ Jericó estava completamente fechada por causa dos israelitas; ninguém saía e ninguém entrava.

[[v6-6-2]]

^<<v6-6-2,2>>^ Então, Jeová disse a Josué: “Olha, entreguei-te Jericó, o seu rei e os seus guerreiros valentes.

[[v6-6-3]]

^<<v6-6-3,3>>^ Todos vocês, homens de guerra, devem marchar à volta da cidade, contornando a cidade uma vez. Devem fazer isso durante seis dias.

[[v6-6-4]]

^<<v6-6-4,4>>^ Providencia sete sacerdotes para carregar sete buzinas de chifre de carneiro à frente da Arca. Mas, no sétimo dia, vocês devem marchar sete vezes à volta da cidade, e os sacerdotes devem tocar as buzinas.

[[v6-6-5]]

^<<v6-6-5,5>>^ Quando se tocarem as buzinas de chifre de carneiro, assim que vocês ouvirem o som^&#42;1^ das buzinas, todo o povo deve dar um grande grito de guerra. Então, a muralha da cidade cairá por terra, e o povo deve avançar, cada um em direção à cidade.”

[NOTE]
====
. Ou: “toque prolongado”.
====

[[v6-6-6]]

^<<v6-6-6,6>>^ Assim, Josué, filho de Num, reuniu os sacerdotes e disse-lhes: “Peguem na Arca do Pacto, e sete sacerdotes devem carregar sete buzinas de chifre de carneiro à frente da Arca de Jeová.”

[[v6-6-7]]

^<<v6-6-7,7>>^ Então, ele disse ao povo: “Vão e marchem à volta da cidade, e os soldados armados devem ir à frente da Arca de Jeová.”

[[v6-6-8]]

^<<v6-6-8,8>>^ Assim como Josué tinha dito ao povo, os sete sacerdotes que carregavam as sete buzinas de chifre de carneiro diante de Jeová passaram à frente e tocaram as buzinas, e a Arca do Pacto de Jeová seguia-os.

[[v6-6-9]]

^<<v6-6-9,9>>^ E os soldados armados iam à frente dos sacerdotes que tocavam as buzinas, e os que iam na retaguarda seguiam a Arca, ao passo que se tocavam continuamente as buzinas.

[[v6-6-10]]

^<<v6-6-10,10>>^ Josué tinha ordenado ao povo: “Não gritem nem deixem que a vossa voz seja ouvida. Não deve sair nenhuma palavra da vossa boca até ao dia em que eu vos disser: ‘Gritem!’ Então, gritem.”

[[v6-6-11]]

^<<v6-6-11,11>>^ Ele fez a Arca de Jeová dar uma volta completa à cidade, contornando-a uma vez. Depois, eles voltaram para o acampamento e passaram lá a noite.

[[v6-6-12]]

^<<v6-6-12,12>>^ Na manhã seguinte, Josué levantou-se cedo, e os sacerdotes pegaram na Arca de Jeová.

[[v6-6-13]]

^<<v6-6-13,13>>^ E os sete sacerdotes que carregavam as sete buzinas de chifre de carneiro iam à frente da Arca de Jeová, tocando continuamente as buzinas. Os homens armados iam à frente deles, e os que iam na retaguarda seguiam a Arca de Jeová, ao passo que se tocavam continuamente as buzinas.

[[v6-6-14]]

^<<v6-6-14,14>>^ No segundo dia, eles marcharam uma vez à volta da cidade e depois voltaram para o acampamento. Fizeram isso durante seis dias.

[[v6-6-15]]

^<<v6-6-15,15>>^ No sétimo dia, levantaram-se cedo, assim que amanheceu, e marcharam da mesma maneira sete vezes à volta da cidade. Foi apenas naquele dia que marcharam sete vezes à volta da cidade.

[[v6-6-16]]

^<<v6-6-16,16>>^ Na sétima vez, quando os sacerdotes tocaram as buzinas, Josué disse ao povo: “Gritem, pois Jeová entregou-vos a cidade!

[[v6-6-17]]

^<<v6-6-17,17>>^ A cidade e tudo o que há nela devem ser entregues à destruição,^&#42;1^ pois pertencem a Jeová. Somente Raabe, a prostituta, pode continuar a viver, ela e todos os que estiverem com ela na casa dela, pois ela escondeu os mensageiros que enviámos.

[NOTE]
====
. Ou: “devotados à destruição”. Veja o Glossário.
====

[[v6-6-18]]

^<<v6-6-18,18>>^ Mas mantenham-se afastados daquilo que está condenado à destruição,^&#42;1^ para que não desejem algo que está condenado à destruição e o tirem. Isso faria o acampamento de Israel tornar-se algo condenado à destruição, trazendo-lhe calamidade.^&#42;2^

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
. Ou: “dificuldade; ostracismo”, isto é, exclusão.
====

[[v6-6-19]]

^<<v6-6-19,19>>^ Mas toda a prata, todo o ouro e todos os objetos de cobre e de ferro são algo sagrado que pertence a Jeová. Devem ser levados para o tesouro de Jeová.”

[[v6-6-20]]

^<<v6-6-20,20>>^ Então, quando se tocaram as buzinas, o povo gritou. Assim que o povo ouviu o som das buzinas e deu um grande grito de guerra, a muralha desabou. Depois disso, o povo avançou, cada um em direção à cidade, e capturou a cidade.

[[v6-6-21]]

^<<v6-6-21,21>>^ Entregaram à destruição^&#42;1^ pela espada tudo o que havia na cidade, homens e mulheres, jovens e idosos, touros, ovelhas e jumentos.

[NOTE]
====
. Ou: “Devotaram à destruição”. Veja o Glossário.
====

[[v6-6-22]]

^<<v6-6-22,22>>^ Josué disse aos dois homens que tinham espiado a terra: “Entrem na casa da prostituta e tragam-na para fora, tanto a ela como a todos os que lhe pertencem, assim como lhe juraram.”

[[v6-6-23]]

^<<v6-6-23,23>>^ Portanto, os jovens espiões entraram e trouxeram para fora Raabe com o seu pai, a sua mãe, os seus irmãos e todos os que lhe pertenciam. Trouxeram para fora toda a sua família, e levaram-nos em segurança para um local fora do acampamento de Israel.

[[v6-6-24]]

^<<v6-6-24,24>>^ Então, queimaram com fogo a cidade e tudo o que havia nela. Contudo, a prata, o ouro, e os objetos de cobre e de ferro, entregaram para o tesouro da casa de Jeová.

[[v6-6-25]]

^<<v6-6-25,25>>^ Apenas Raabe, a prostituta, os da casa do seu pai e todos os que lhe pertenciam foram poupados por Josué; e ela mora em Israel até ao dia de hoje, porque escondeu os mensageiros que Josué tinha enviado para espiar Jericó.

[[v6-6-26]]

^<<v6-6-26,26>>^ Naquela ocasião, Josué fez o seguinte juramento:^&#42;1^ “Maldito seja o homem perante Jeová que se empenhar em reconstruir esta cidade, Jericó. Ele lançará os alicerces dela, pagando com a perda do seu primogénito, e colocará as suas portas, pagando com a perda do seu filho mais novo.”

[NOTE]
====
. Ou, possivelmente: “fez o povo prestar este juramento”.
====

[[v6-6-27]]

^<<v6-6-27,27>>^ Assim, Jeová estava com Josué, e a fama dele espalhou-se por toda a terra.

'''

xref:006-josue/006-josue-005.adoc#v6-5-0[&#60; Capítulo Anterior] | <<v6-6-0,Topo>> | xref:006-josue/006-josue-007.adoc#v6-7-0[Próximo Capítulo &#62;]