include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-8-1]]

^<<v6-8-1,1>>^ Jeová disse então a Josué: “Não tenhas medo nem fiques apavorado. Leva contigo todos os homens de guerra e sobe contra Ai. Olha, entreguei-te o rei de Ai, o seu povo, a sua cidade e a sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Faz a Ai e ao seu rei o mesmo que fizeste a Jericó e ao seu rei, com a diferença de que podem ficar com o seu despojo e os seus animais. Arma uma emboscada por detrás da cidade.”

[[v6-8-3]]

^<<v6-8-3,3>>^ Assim, Josué e todos os homens de guerra subiram contra Ai. Josué escolheu 30 000 guerreiros valentes e enviou-os de noite.

[[v6-8-4]]

^<<v6-8-4,4>>^ Deu-lhes a seguinte ordem: “Fiquem de emboscada atrás da cidade. Não se afastem muito da cidade, e estejam prontos.

[[v6-8-5]]

^<<v6-8-5,5>>^ Eu e todo o povo que está comigo vamos aproximar-nos da cidade, e, quando eles vierem contra nós, assim como fizeram antes, fugiremos deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ Quando vierem atrás de nós, iremos atraí-los para longe da cidade, pois dirão: ‘Estão a fugir de nós como fizeram antes.’ Assim, fugiremos deles.

[[v6-8-7]]

^<<v6-8-7,7>>^ Então, vocês devem sair da emboscada e tomar a cidade; Jeová, vosso Deus, vo-la entregará.

[[v6-8-8]]

^<<v6-8-8,8>>^ Assim que tomarem a cidade, devem incendiá-la. Devem fazer segundo a palavra de Jeová. Estas são as ordens que vos dou.”

[[v6-8-9]]

^<<v6-8-9,9>>^ A seguir, Josué enviou-os, e eles foram para o local da emboscada; posicionaram-se entre Betel e Ai, a oeste de Ai, enquanto Josué passou aquela noite com o restante do povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ Depois de Josué se ter levantado de manhã cedo e reunido^&#42;1^ as tropas, ele e os anciãos de Israel conduziram-nas a Ai.

[NOTE]
====
. Ou: “ajuntado”.
====

[[v6-8-11]]

^<<v6-8-11,11>>^ Todos os homens de guerra que estavam com ele subiram e avançaram até à parte da frente da cidade. Acamparam a norte de Ai, com o vale entre eles e Ai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Entretanto, ele tinha escolhido cerca de 5000 homens e tinha-os colocado de emboscada entre Betel e Ai, a oeste da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ Assim, o povo montou o acampamento principal a norte da cidade, e os que estavam na retaguarda ficaram a oeste da cidade. Naquela noite, Josué foi até ao meio do vale.^&#42;1^

[NOTE]
====
. Ou: “da planície”.
====

[[v6-8-14]]

^<<v6-8-14,14>>^ E, assim que o rei de Ai viu isto, ele e os homens da cidade apressaram-se e saíram logo de manhã cedo para enfrentar Israel em batalha, num lugar que ficava de frente para a planície desértica. O rei, porém, não sabia que havia uma emboscada contra ele atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Quando os homens de Ai atacaram, Josué e todo o Israel fugiram pela estrada em direção ao deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Então, todo o povo que estava na cidade foi convocado para os perseguir. E, ao perseguirem Josué, foram atraídos para longe da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Não restou nenhum homem em Ai e em Betel que não fosse atrás de Israel. Deixaram a cidade desprotegida e perseguiram Israel.

[[v6-8-18]]

^<<v6-8-18,18>>^ Jeová disse então a Josué: “Estende a lança que tens na mão em direção a Ai, pois vou entregá-la nas tuas mãos.” Assim, Josué estendeu a lança que tinha na mão em direção à cidade.

[[v6-8-19]]

^<<v6-8-19,19>>^ No momento em que ele estendeu a mão, os homens da emboscada saíram rapidamente do lugar onde estavam, correram para a cidade e tomaram-na. Incendiaram imediatamente a cidade.

[[v6-8-20]]

^<<v6-8-20,20>>^ Quando os homens de Ai se viraram para trás e viram o fumo da cidade a subir para o céu, não tiveram forças para fugir em nenhuma direção. Então, o povo que estava a fugir para o deserto voltou-se contra os perseguidores.

[[v6-8-21]]

^<<v6-8-21,21>>^ Quando Josué e todo o Israel viram que os homens da emboscada tinham tomado a cidade e que subia fumo da cidade, deram meia-volta e atacaram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ E os que tinham tomado a cidade saíram ao seu encontro, de modo que os homens de Ai ficaram encurralados no meio, com israelitas de um lado e do outro. Os israelitas mataram-nos, até que não restou nenhum sobrevivente nem fugitivo.

[[v6-8-23]]

^<<v6-8-23,23>>^ No entanto, capturaram o rei de Ai vivo e levaram-no a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Depois de Israel acabar de matar todos os habitantes de Ai que estavam no campo, no deserto onde os tinham perseguido, e o último deles ter caído pela espada, então todo o Israel voltou a Ai e golpeou-a com a espada.

[[v6-8-25]]

^<<v6-8-25,25>>^ Todos os que caíram naquele dia, tanto homens como mulheres, foram 12 000, todos os habitantes de Ai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Josué manteve a mão estendida com a lança até ter entregue à destruição^&#42;1^ todos os habitantes de Ai.

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-8-27]]

^<<v6-8-27,27>>^ No entanto, Israel ficou com os animais e o despojo da cidade para si, segundo as ordens que Jeová tinha dado a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Josué queimou então Ai e reduziu-a para sempre a um monte de ruínas, como está até ao dia de hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Pendurou o rei de Ai num madeiro^&#42;1^ até ao anoitecer. Quando o sol estava para se pôr, Josué ordenou que retirassem o cadáver do madeiro. Lançaram-no então na entrada do portão da cidade e levantaram sobre ele um grande monte de pedras, que permanece ali até ao dia de hoje.

[NOTE]
====
. Ou: “numa árvore”.
====

[[v6-8-30]]

^<<v6-8-30,30>>^ Foi então que Josué construiu no monte Ebal um altar a Jeová, o Deus de Israel,

[[v6-8-31]]

^<<v6-8-31,31>>^ assim como Moisés, o servo de Jeová, tinha ordenado aos israelitas e assim como está escrito no livro da Lei de Moisés: “Um altar de pedras inteiras, nas quais não se usou nenhum instrumento de ferro.” Sobre ele fizeram ofertas queimadas a Jeová bem como sacrifícios de participação em comum.

[[v6-8-32]]

^<<v6-8-32,32>>^ Então, ele escreveu nas pedras uma cópia da Lei que Moisés tinha escrito perante os israelitas.

[[v6-8-33]]

^<<v6-8-33,33>>^ Todo o Israel, os anciãos, os oficiais e os juízes estavam de pé de ambos os lados da Arca, diante dos sacerdotes levíticos que carregavam a Arca do Pacto de Jeová. Estavam lá tanto os residentes estrangeiros como os israelitas de nascimento. Metade deles estava diante do monte Gerizim e a outra metade diante do monte Ebal (assim como Moisés, o servo de Jeová, tinha ordenado anteriormente), para que o povo de Israel fosse abençoado.

[[v6-8-34]]

^<<v6-8-34,34>>^ Depois disso, ele leu em voz alta todas as palavras da Lei, as bênçãos e as maldições, segundo tudo o que está escrito no livro da Lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Não houve nenhuma palavra, de tudo o que Moisés tinha ordenado, que Josué não lesse em voz alta diante de toda a congregação de Israel, incluindo as mulheres, as crianças e os residentes estrangeiros que moravam^&#42;1^ no seu meio.

[NOTE]
====
. Lit.: “andavam”.
====

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]