include::./index.adoc[]

[[v6-2-0]]
=== Josué, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-2-1]]

^<<v6-2-1,1>>^ Então, Josué, filho de Num, enviou secretamente de Sitim dois homens como espiões. Ele disse-lhes: “Vão e inspecionem a terra, especialmente Jericó.” Assim, eles foram e chegaram à casa de uma prostituta chamada Raabe, e ficaram ali.

[[v6-2-2]]

^<<v6-2-2,2>>^ O rei de Jericó foi informado: “Homens israelitas vieram aqui esta noite para espiar a terra.”

[[v6-2-3]]

^<<v6-2-3,3>>^ Em vista disso, o rei de Jericó mandou dizer a Raabe: “Traz para fora os homens que vieram e que estão na tua casa, pois eles vieram para espiar toda a terra.”

[[v6-2-4]]

^<<v6-2-4,4>>^ No entanto, a mulher levou os dois homens e escondeu-os. Então, ela disse: “É verdade, os homens vieram ter comigo, mas eu não sabia de onde eram.

[[v6-2-5]]

^<<v6-2-5,5>>^ Ao escurecer, quando o portão da cidade estava para ser fechado, os homens foram-se embora. Não sei para onde foram, mas, se forem depressa atrás deles, vão alcançá-los.”

[[v6-2-6]]

^<<v6-2-6,6>>^ (Mas ela tinha-os levado para o terraço e tinha-os escondido entre as fileiras de hastes de linho que estavam no terraço.)

[[v6-2-7]]

^<<v6-2-7,7>>^ Assim, os homens foram atrás deles em direção aos pontos de travessia do Jordão, e o portão da cidade foi fechado assim que os perseguidores saíram.

[[v6-2-8]]

^<<v6-2-8,8>>^ Antes de os espiões se deitarem para dormir, ela foi ter com eles ao terraço.

[[v6-2-9]]

^<<v6-2-9,9>>^ Ela disse-lhes: “Sei que Jeová vos dará esta terra e que estamos com medo de vocês. Todos os habitantes desta terra estão desanimados por vossa causa.

[[v6-2-10]]

^<<v6-2-10,10>>^ Pois, soubemos como Jeová secou as águas do mar Vermelho à vossa frente, quando saíram do Egito, e o que fizeram aos dois reis dos amorreus, Síon e Ogue, que vocês entregaram à destruição^&#42;1^ do outro lado^&#42;2^ do Jordão.

[NOTE]
====
. Ou: “devotaram à destruição”. Veja o Glossário.
. Isto é, do lado leste.
====

[[v6-2-11]]

^<<v6-2-11,11>>^ Quando soubemos disso, ficámos desanimados;^&#42;1^ perdemos a coragem^&#42;2^ por vossa causa, pois Jeová, vosso Deus, é Deus nos céus, em cima, e na terra, em baixo.

[NOTE]
====
. Lit.: “os nossos corações derreteram-se”.
. Lit.: “e nunca mais se levantou espírito num homem”.
====

[[v6-2-12]]

^<<v6-2-12,12>>^ Agora, por favor, jurem-me por Jeová que, por eu ter demonstrado bondade^&#42;1^ para convosco, vocês também demonstrarão bondade^&#42;2^ para com os da casa do meu pai. Deem-me um sinal de que agirão de boa-fé.^&#42;3^

[NOTE]
====
. Ou: “amor leal”.
. Ou: “amor leal”.
. Ou: “um sinal confiável”.
====

[[v6-2-13]]

^<<v6-2-13,13>>^ Poupem a vida do meu pai, da minha mãe, dos meus irmãos, das minhas irmãs e de todos os que lhes pertencem; e livrem-nos^&#42;1^ da morte.”

[NOTE]
====
. Ou: “livrem as nossas almas”.
====

[[v6-2-14]]

^<<v6-2-14,14>>^ Diante disso, os homens disseram-lhe: “Daremos a nossa vida pela vossa!^&#42;1^ Se não disseres nada sobre a nossa missão, nós demonstraremos bondade^&#42;2^ e fidelidade para contigo quando Jeová nos der a terra.”

[NOTE]
====
. Ou: “As nossas almas morrerão no vosso lugar!”
. Ou: “amor leal”.
====

[[v6-2-15]]

^<<v6-2-15,15>>^ A seguir, ela fê-los descer por uma corda pela janela, pois a sua casa ficava num dos lados da muralha da cidade. Na verdade, ela morava no alto da muralha.

[[v6-2-16]]

^<<v6-2-16,16>>^ Então, ela disse-lhes: “Vão para a região montanhosa e escondam-se lá durante três dias, para que aqueles que vos perseguem não vos encontrem. Depois, quando os perseguidores tiverem voltado, podem seguir o vosso caminho.”

[[v6-2-17]]

^<<v6-2-17,17>>^ Os homens disseram-lhe: “Estaremos livres de culpa por este juramento que nos impuseste

[[v6-2-18]]

^<<v6-2-18,18>>^ se, quando entrarmos nesta terra, não tiveres atado esta corda de fio escarlate à janela pela qual nos fizeste descer. Deves reunir na tua casa o teu pai, a tua mãe, os teus irmãos e todos os da casa do teu pai.

[[v6-2-19]]

^<<v6-2-19,19>>^ Então, se alguém sair para fora da tua casa, o seu sangue recairá sobre a sua cabeça, e nós estaremos livres de culpa. Mas, se acontecer alguma coisa má a^&#42;1^ alguém que estiver contigo em casa, o seu sangue recairá sobre a nossa cabeça.

[NOTE]
====
. Ou: “se uma mão vier sobre”.
====

[[v6-2-20]]

^<<v6-2-20,20>>^ Mas, se denunciares a nossa missão, estaremos livres de culpa pelo juramento que nos impuseste.”

[[v6-2-21]]

^<<v6-2-21,21>>^ Ela respondeu: “Seja segundo as vossas palavras.”
Com isso, mandou-os embora, e eles seguiram caminho. Mais tarde, ela atou a corda escarlate à janela.

[[v6-2-22]]

^<<v6-2-22,22>>^ Eles partiram para a região montanhosa e ficaram lá durante três dias, até os perseguidores voltarem. Os perseguidores procuraram-nos em todas as estradas, mas não os encontraram.

[[v6-2-23]]

^<<v6-2-23,23>>^ Os dois homens desceram então da região montanhosa, atravessaram o rio e foram ter com Josué, filho de Num. Contaram-lhe todas as coisas que lhes tinham acontecido.

[[v6-2-24]]

^<<v6-2-24,24>>^ Então, disseram a Josué: “Jeová entregou-nos toda esta terra. De facto, todos os habitantes desta terra estão desanimados por nossa causa.”

'''

xref:006-josue/006-josue-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-josue/006-josue-003.adoc#v6-3-0[Próximo Capítulo &#62;]