include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-10-1]]

^<<v6-10-1,1>>^ Assim que Adoni-Zedeque, rei de Jerusalém, ouviu dizer que Josué tinha tomado Ai e a tinha entregado à destruição,^&#42;1^ fazendo a Ai e ao seu rei o mesmo que tinha feito a Jericó e ao seu rei, e que os habitantes de Gibeão tinham feito paz com Israel e permaneciam entre eles,

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-10-2]]

^<<v6-10-2,2>>^ ele ficou apavorado, porque Gibeão era uma cidade grande, como uma das cidades reais. Era maior do que Ai, e todos os seus homens eram guerreiros.

[[v6-10-3]]

^<<v6-10-3,3>>^ Por isso, Adoni-Zedeque, rei de Jerusalém, mandou a seguinte mensagem a Hoão, rei de Hébron, a Pirão, rei de Jarmute, a Jafia, rei de Laquis, e a Debir, rei de Eglom:

[[v6-10-4]]

^<<v6-10-4,4>>^ “Venham ajudar-me a atacar Gibeão, visto que ela fez paz com Josué e com os israelitas.”

[[v6-10-5]]

^<<v6-10-5,5>>^ Com isso, os cinco reis dos amorreus — o rei de Jerusalém, o rei de Hébron, o rei de Jarmute, o rei de Laquis e o rei de Eglom — juntaram-se e, com os seus exércitos, foram e acamparam para atacar Gibeão.

[[v6-10-6]]

^<<v6-10-6,6>>^ Então, os homens de Gibeão mandaram dizer a Josué, que estava no acampamento em Gilgal: “Não abandones os^&#42;1^ teus escravos. Vem depressa! Salva-nos e ajuda-nos! Todos os reis dos amorreus da região montanhosa uniram-se contra nós.”

[NOTE]
====
. Lit.: “Não deixes a tua mão abaixar-se dos”.
====

[[v6-10-7]]

^<<v6-10-7,7>>^ Assim, Josué partiu de Gilgal com todos os homens de guerra e os guerreiros valentes.

[[v6-10-8]]

^<<v6-10-8,8>>^ Jeová disse então a Josué: “Não tenhas medo deles, pois entreguei-os a ti. Nenhum deles te poderá resistir.”

[[v6-10-9]]

^<<v6-10-9,9>>^ Josué atacou-os de surpresa, depois de ter marchado durante toda a noite desde Gilgal.

[[v6-10-10]]

^<<v6-10-10,10>>^ Jeová lançou-os em confusão diante de Israel, e Israel causou-lhes uma grande matança em Gibeão, perseguindo-os na subida de Bete-Horom e matando-os por todo o caminho até Azeca e Maquedá.

[[v6-10-11]]

^<<v6-10-11,11>>^ Enquanto fugiam de Israel e estavam na descida de Bete-Horom, Jeová lançou do céu grandes pedras de granizo sobre eles, até Azeca, e eles morreram. De facto, morreram mais pessoas por causa do granizo do que pela espada dos israelitas.

[[v6-10-12]]

^<<v6-10-12,12>>^ No dia em que Jeová derrotou os amorreus diante dos olhos dos israelitas, Josué disse a Jeová diante de Israel:
“Sol, fica parado sobre Gibeão,
E lua, sobre o vale^&#42;1^ de Aijalom!”

[NOTE]
====
. Ou: “a planície”.
====

[[v6-10-13]]

^<<v6-10-13,13>>^ Assim, o sol ficou parado e a lua não se moveu até que a nação se pôde vingar dos seus inimigos. Não está isto escrito no livro de Jasar? O sol ficou parado no meio do céu e não teve pressa em se pôr durante quase um dia inteiro.

[[v6-10-14]]

^<<v6-10-14,14>>^ Nunca houve um dia igual àquele, nem antes nem depois, quando Jeová escutou a voz de um homem, pois Jeová estava a lutar por Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ Depois disso, Josué voltou com todo o Israel ao acampamento em Gilgal.

[[v6-10-16]]

^<<v6-10-16,16>>^ Entretanto, os cinco reis fugiram e esconderam-se na caverna de Maquedá.

[[v6-10-17]]

^<<v6-10-17,17>>^ Então, foi dito a Josué: “Os cinco reis foram encontrados escondidos na caverna de Maquedá.”

[[v6-10-18]]

^<<v6-10-18,18>>^ Portanto, Josué disse: “Rolem grandes pedras até à entrada da caverna e coloquem homens ali para os vigiar.

[[v6-10-19]]

^<<v6-10-19,19>>^ Mas os que restarem de vocês não devem parar. Persigam os vossos inimigos e golpeiem-nos pela retaguarda. Não os deixem entrar nas suas cidades, pois Jeová, vosso Deus, entregou-os nas vossas mãos.”

[[v6-10-20]]

^<<v6-10-20,20>>^ Josué e os israelitas causaram-lhes uma grande matança, a ponto de os eliminar, com exceção de alguns sobreviventes que escaparam e entraram nas cidades fortificadas.

[[v6-10-21]]

^<<v6-10-21,21>>^ Então, todo o povo retornou são e salvo a Josué, ao acampamento em Maquedá. E ninguém ousou dizer uma palavra^&#42;1^ contra os israelitas.

[NOTE]
====
. Lit.: “afiou a sua língua”.
====

[[v6-10-22]]

^<<v6-10-22,22>>^ Depois, Josué disse: “Abram a entrada da caverna e tragam-me para fora os cinco reis.”

[[v6-10-23]]

^<<v6-10-23,23>>^ Assim, tiraram estes cinco reis da caverna: o rei de Jerusalém, o rei de Hébron, o rei de Jarmute, o rei de Laquis e o rei de Eglom.

[[v6-10-24]]

^<<v6-10-24,24>>^ Quando levaram estes reis até Josué, ele convocou todos os homens de Israel e disse aos comandantes dos homens de guerra que tinham ido com ele: “Aproximem-se. Coloquem os pés sobre a nuca destes reis.” Então, eles aproximaram-se e colocaram os pés sobre a nuca deles.

[[v6-10-25]]

^<<v6-10-25,25>>^ Em seguida, Josué disse-lhes: “Não tenham medo nem fiquem apavorados. Sejam corajosos e fortes, pois é isto o que Jeová fará a todos os vossos inimigos, contra quem lutarem.”

[[v6-10-26]]

^<<v6-10-26,26>>^ Depois, Josué golpeou-os e matou-os, e pendurou-os em cinco madeiros;^&#42;1^ e eles ficaram pendurados nos madeiros até ao fim da tarde.

[NOTE]
====
. Ou: “árvores”.
====

[[v6-10-27]]

^<<v6-10-27,27>>^ Ao pôr do sol, Josué ordenou que fossem retirados dos madeiros e lançados na caverna em que se tinham escondido. Depois, foram colocadas grandes pedras à entrada da caverna que permanecem lá até ao dia de hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ Naquele dia, Josué tomou Maquedá e golpeou-a com a espada, entregando à destruição^&#42;1^ o seu rei e todos os^&#42;2^ que lá havia, sem deixar nenhum sobrevivente. Ele fez ao rei de Maquedá o mesmo que tinha feito ao rei de Jericó.

[NOTE]
====
. Ou: “devotando à destruição”. Veja o Glossário.
. Ou: “toda a alma”.
====

[[v6-10-29]]

^<<v6-10-29,29>>^ Então, Josué foi com todo o Israel de Maquedá até Libna, e lutou contra Libna.

[[v6-10-30]]

^<<v6-10-30,30>>^ Jeová também entregou aquela cidade e o seu rei nas mãos de Israel, e eles golpearam com a espada tanto a ela como a todos os^&#42;1^ que lá havia, sem deixar nenhum sobrevivente. Assim, fizeram com o seu rei o mesmo que tinham feito com o rei de Jericó.

[NOTE]
====
. Ou: “toda a alma”.
====

[[v6-10-31]]

^<<v6-10-31,31>>^ A seguir, Josué foi com todo o Israel de Libna até Laquis, e ali acampou e lutou contra ela.

[[v6-10-32]]

^<<v6-10-32,32>>^ Jeová entregou Laquis nas mãos de Israel, e eles tomaram-na no segundo dia. Golpearam com a espada tanto a ela como a todos os^&#42;1^ que lá havia, assim como tinham feito a Libna.

[NOTE]
====
. Ou: “toda a alma”.
====

[[v6-10-33]]

^<<v6-10-33,33>>^ Horão, rei de Gezer, subiu então para ajudar Laquis, mas Josué golpeou-o a ele e ao seu povo até não restar nenhum sobrevivente.

[[v6-10-34]]

^<<v6-10-34,34>>^ Então, Josué foi com todo o Israel de Laquis até Eglom, e ali acampou e lutou contra ela.

[[v6-10-35]]

^<<v6-10-35,35>>^ Tomaram-na naquele dia e golpearam-na com a espada. Naquele dia, entregaram à destruição todos os^&#42;1^ que lá havia, assim como tinham feito a Laquis.

[NOTE]
====
. Ou: “toda a alma”.
====

[[v6-10-36]]

^<<v6-10-36,36>>^ Depois, Josué foi com todo o Israel de Eglom até Hébron e lutou contra ela.

[[v6-10-37]]

^<<v6-10-37,37>>^ Tomaram-na e golpearam-na com a espada, tanto ao seu rei como aos seus povoados e a todos os^&#42;1^ que nela havia, sem deixar nenhum sobrevivente. Assim como tinha feito a Eglom, assim ele entregou à destruição,^&#42;2^ tanto a ela como a todos os^&#42;3^ que lá havia.

[NOTE]
====
. Ou: “toda a alma”.
. Ou: “devotou à destruição”. Veja o Glossário.
. Ou: “toda a alma”.
====

[[v6-10-38]]

^<<v6-10-38,38>>^ Por fim, Josué foi com todo o Israel até Debir, e lutou contra ela.

[[v6-10-39]]

^<<v6-10-39,39>>^ Tomou tanto a ela como ao seu rei e a todos os seus povoados, e golpearam-nos com a espada, entregando à destruição todos os^&#42;1^ que lá havia, sem deixar nenhum sobrevivente. Ele fez a Debir e ao seu rei assim como tinha feito a Hébron, e a Libna e ao seu rei.

[NOTE]
====
. Ou: “toda a alma”.
====

[[v6-10-40]]

^<<v6-10-40,40>>^ Josué conquistou toda a terra — a região montanhosa, o Neguebe, a Sefelá e as encostas — e todos os seus reis, sem deixar nenhum sobrevivente. Ele entregou à destruição tudo o que respirava, assim como Jeová, o Deus de Israel, tinha ordenado.

[[v6-10-41]]

^<<v6-10-41,41>>^ Josué conquistou-os desde Cades-Barneia até Gaza, e toda a terra de Gósen, e até Gibeão.

[[v6-10-42]]

^<<v6-10-42,42>>^ Josué capturou todos estes reis e a sua terra numa só campanha militar, porque era Jeová, o Deus de Israel, quem estava a lutar por Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ Então, Josué voltou com todo o Israel para o acampamento em Gilgal.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]