include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-5-1]]

^<<v6-5-1,1>>^ Todos os reis dos amorreus que estavam do lado oeste^&#42;1^ do Jordão e todos os reis dos cananeus que estavam ao pé do mar ouviram dizer que Jeová tinha secado as águas do Jordão diante dos israelitas até que tivessem atravessado. Assim que souberam disso, ficaram desanimados^&#42;2^ e perderam toda a coragem^&#42;3^ por causa dos israelitas.

[NOTE]
====
. Lit.: “do lado que dá para o mar”.
. Lit.: “os seus corações derreteram-se”.
. Lit.: “e já não havia mais espírito neles”.
====

[[v6-5-2]]

^<<v6-5-2,2>>^ Naquela ocasião, Jeová disse a Josué: “Faz facas de pedra^&#42;1^ e faz novamente a circuncisão dos homens de Israel.”

[NOTE]
====
. Ou: “de pederneira”.
====

[[v6-5-3]]

^<<v6-5-3,3>>^ Portanto, Josué fez facas de pedra^&#42;1^ e circuncidou os homens de Israel em Gibeate-Aralote.^&#42;2^

[NOTE]
====
. Ou: “de pederneira”.
. Que significa “monte dos prepúcios”.
====

[[v6-5-4]]

^<<v6-5-4,4>>^ Foi por este motivo que Josué os circuncidou: todos os homens do povo que saíram do Egito, os homens de guerra,^&#42;1^ tinham morrido no deserto, na jornada que fizeram ao sair do Egito.

[NOTE]
====
. Ou: “os homens em idade militar”.
====

[[v6-5-5]]

^<<v6-5-5,5>>^ Todos os que saíram do Egito já eram circuncidados, mas todos os que nasceram no deserto durante a jornada que fizeram depois de terem saído do Egito não eram circuncidados.

[[v6-5-6]]

^<<v6-5-6,6>>^ Os israelitas tinham andado 40 anos no deserto até toda a nação ter morrido, isto é, os homens de guerra que saíram do Egito e que não obedeceram à voz de Jeová. Jeová jurou-lhes que nunca os deixaria ver a terra a qual Jeová tinha jurado aos seus antepassados que nos daria, uma terra que mana leite e mel.

[[v6-5-7]]

^<<v6-5-7,7>>^ Assim, no lugar deles colocou os seus filhos, a quem Josué circuncidou; eles eram incircuncisos porque não tinham sido circuncidados durante a jornada.

[[v6-5-8]]

^<<v6-5-8,8>>^ Depois de toda a nação ter sido circuncidada, eles ficaram nos seus lugares no acampamento até se recuperarem.

[[v6-5-9]]

^<<v6-5-9,9>>^ Então, Jeová disse a Josué: “Hoje retirei de vocês a humilhação do Egito.” Por isso, chama-se àquele lugar Gilgal^&#42;1^ até ao dia de hoje.

[NOTE]
====
. Que significa “rolar; rolar para longe”.
====

[[v6-5-10]]

^<<v6-5-10,10>>^ Os israelitas permaneceram acampados em Gilgal e, no dia 14 do mês, ao anoitecer, celebraram a Páscoa nas planícies desérticas de Jericó.

[[v6-5-11]]

^<<v6-5-11,11>>^ E no dia a seguir à Páscoa, nesse mesmo dia, começaram a comer dos produtos da terra, pães sem fermento e grãos torrados.

[[v6-5-12]]

^<<v6-5-12,12>>^ O maná parou no dia em que eles comeram alguns dos produtos da terra. Já não havia mais maná para os israelitas, mas, naquele ano, eles passaram a comer dos produtos da terra de Canaã.

[[v6-5-13]]

^<<v6-5-13,13>>^ Quando Josué estava perto de Jericó, levantou os olhos e viu à sua frente um homem de pé, com uma espada desembainhada na mão. Josué aproximou-se dele e perguntou: “Estás do nosso lado ou do lado dos nossos adversários?”

[[v6-5-14]]

^<<v6-5-14,14>>^ Ele respondeu: “Eu^&#42;1^ estou aqui como príncipe^&#42;2^ do exército de Jeová.” Em vista disso, Josué prostrou-se, lançando-se com o rosto por terra, e disse-lhe: “O que é que o meu senhor tem a dizer ao seu servo?”

[NOTE]
====
. Lit.: “Não, mas eu”.
. Ou: “chefe”.
====

[[v6-5-15]]

^<<v6-5-15,15>>^ O príncipe do exército de Jeová disse a Josué: “Tira as sandálias dos pés, porque o lugar que estás a pisar é santo.” Josué fez isso imediatamente.

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]