include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-22-1]]

^<<v6-22-1,1>>^ Então, Josué convocou os rubenitas, os gaditas e a meia tribo de Manassés,

[[v6-22-2]]

^<<v6-22-2,2>>^ e disse-lhes: “Fizeram tudo o que Moisés, o servo de Jeová, vos ordenou e obedeceram à minha voz em tudo o que vos ordenei.

[[v6-22-3]]

^<<v6-22-3,3>>^ Não abandonaram os vossos irmãos durante todo este tempo, até ao dia de hoje, e cumpriram o mandamento de Jeová, vosso Deus.

[[v6-22-4]]

^<<v6-22-4,4>>^ Agora Jeová, vosso Deus, deu descanso aos vossos irmãos, assim como lhes prometeu. Portanto, podem voltar para as vossas tendas na terra que Moisés, o servo de Jeová, vos deu como propriedade no outro lado^&#42;1^ do Jordão.

[NOTE]
====
. Isto é, no lado leste.
====

[[v6-22-5]]

^<<v6-22-5,5>>^ Apenas cumpram cuidadosamente os mandamentos e a Lei que Moisés, o servo de Jeová, vos deu, por amarem a Jeová, vosso Deus, por andarem em todos os seus caminhos, por guardarem os seus mandamentos, por se apegarem a ele e por o servirem de todo o vosso coração e de toda a vossa alma.”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v6-22-6]]

^<<v6-22-6,6>>^ Então, Josué abençoou-os e dispensou-os, e eles voltaram para as suas tendas.

[[v6-22-7]]

^<<v6-22-7,7>>^ À meia tribo de Manassés, Moisés tinha dado uma herança em Basã, e à outra meia tribo, Josué deu terras no lado oeste do Jordão, junto dos seus irmãos. E, quando Josué os mandou de volta para as suas tendas, ele abençoou-os

[[v6-22-8]]

^<<v6-22-8,8>>^ e disse-lhes: “Voltem às vossas tendas com muitas riquezas e com muitíssimos animais, com prata, ouro, cobre, ferro e roupas em grande quantidade. Repartam com os vossos irmãos o despojo dos vossos inimigos.”

[[v6-22-9]]

^<<v6-22-9,9>>^ Depois disso, os rubenitas, os gaditas e a meia tribo de Manassés deixaram os outros israelitas em Silo, na terra de Canaã, e voltaram para a terra de Gileade, a terra que receberam para tomar posse e se estabelecer, segundo a ordem de Jeová por meio de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ Quando chegaram à região do Jordão na terra de Canaã, os rubenitas, os gaditas e a meia tribo de Manassés construíram ali um altar, perto do Jordão, um altar grande e impressionante.

[[v6-22-11]]

^<<v6-22-11,11>>^ Mais tarde, os outros israelitas ouviram dizer: “Vejam! Os rubenitas, os gaditas e a meia tribo de Manassés construíram um altar na fronteira da terra de Canaã, na região do Jordão, no lado que pertence aos israelitas.”

[[v6-22-12]]

^<<v6-22-12,12>>^ Quando os israelitas ouviram isso, toda a assembleia de Israel se reuniu em Silo para guerrear contra eles.

[[v6-22-13]]

^<<v6-22-13,13>>^ A seguir, os israelitas enviaram Fineias, filho de Eleazar, o sacerdote, aos rubenitas, aos gaditas e à meia tribo de Manassés, na terra de Gileade,

[[v6-22-14]]

^<<v6-22-14,14>>^ e dez maiorais foram com ele, um maioral de cada casa paterna de todas as tribos de Israel, cada um deles sendo cabeça da sua casa paterna entre os milhares^&#42;1^ de Israel.

[NOTE]
====
. Ou: “clãs”.
====

[[v6-22-15]]

^<<v6-22-15,15>>^ Quando chegaram aos rubenitas, aos gaditas e à meia tribo de Manassés, na terra de Gileade, disseram-lhes:

[[v6-22-16]]

^<<v6-22-16,16>>^ “Assim diz toda a assembleia de Jeová: ‘Porque é que vocês cometeram este ato de infidelidade contra o Deus de Israel? Hoje, deixaram de seguir a Jeová, por construírem para vocês um altar e se rebelarem contra Jeová.

[[v6-22-17]]

^<<v6-22-17,17>>^ Não nos bastou o erro cometido em Peor? Até hoje, não nos purificámos dele, apesar de uma praga ter vindo sobre a assembleia de Jeová.

[[v6-22-18]]

^<<v6-22-18,18>>^ E agora vocês querem deixar de seguir a Jeová? Se hoje se rebelarem contra Jeová, então, amanhã, ele ficará indignado com toda a assembleia de Israel.

[[v6-22-19]]

^<<v6-22-19,19>>^ Agora, se é porque a terra que receberam como propriedade é impura, atravessem para o outro lado, para a terra que pertence a Jeová, onde fica o tabernáculo de Jeová, e estabeleçam-se no nosso meio, mas não se rebelem contra Jeová nem nos tornem rebeldes por construírem um altar além do altar de Jeová, nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Quando Acã, filho de Zerá, cometeu um ato de infidelidade em relação ao que era condenado à destruição,^&#42;1^ não houve indignação contra toda a assembleia de Israel? E ele não foi o único homem a morrer por causa do seu erro.’”

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-22-21]]

^<<v6-22-21,21>>^ Então, os rubenitas, os gaditas e a meia tribo de Manassés disseram em resposta aos cabeças dos milhares^&#42;1^ de Israel:

[NOTE]
====
. Ou: “clãs”.
====

[[v6-22-22]]

^<<v6-22-22,22>>^ “O Deus dos deuses, Jeová!^&#42;1^ O Deus dos deuses, Jeová! Ele sabe, e Israel também saberá. Se fomos rebeldes e infiéis a Jeová, que ele não nos poupe neste dia.

[NOTE]
====
. Ou: “O Divino, Deus, Jeová.”
====

[[v6-22-23]]

^<<v6-22-23,23>>^ Se construímos um altar para deixarmos de seguir a Jeová e para fazermos nele ofertas queimadas, ofertas de cereais e sacrifícios de participação em comum, Jeová exigirá punição.

[[v6-22-24]]

^<<v6-22-24,24>>^ Não, nós fizemo-lo por receio de que, no futuro, os vossos filhos digam aos nossos filhos: ‘O que é que têm a ver com Jeová, o Deus de Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ Jeová pôs o Jordão como limite entre nós e vocês, os rubenitas e os gaditas. Vocês não têm nada a ver com Jeová.’ E os vossos filhos impedirão os nossos filhos de adorar^&#42;1^ a Jeová.”

[NOTE]
====
. Lit.: “temer”.
====

[[v6-22-26]]

^<<v6-22-26,26>>^ “Por isso dissemos: ‘Construamos sem falta um altar, não para ofertas queimadas nem para sacrifícios,

[[v6-22-27]]

^<<v6-22-27,27>>^ mas para ser testemunha entre nós e vocês, e entre os nossos descendentes e os vossos descendentes,^&#42;1^ de que realizaremos o nosso serviço a Jeová perante ele com as nossas ofertas queimadas, os nossos sacrifícios de participação em comum e outros sacrifícios, para que os vossos filhos não digam aos nossos filhos no futuro: “Vocês não têm nada a ver com Jeová.”’

[NOTE]
====
. Ou: “e entre as nossas gerações”.
====

[[v6-22-28]]

^<<v6-22-28,28>>^ Por causa disso dissemos: ‘Caso nos digam isso a nós e aos nossos descendentes,^&#42;1^ no futuro, então diremos: “Vejam a réplica do altar de Jeová feita pelos nossos antepassados, não para ofertas queimadas nem para sacrifícios, mas para ser testemunha entre nós e vocês.”’

[NOTE]
====
. Lit.: “às nossas gerações”.
====

[[v6-22-29]]

^<<v6-22-29,29>>^ É impensável rebelarmo-nos contra Jeová ou deixarmos hoje de seguir a Jeová, por construirmos um altar para ofertas queimadas, ofertas de cereais e sacrifícios, além do altar de Jeová, nosso Deus, que está diante do seu tabernáculo!”

[[v6-22-30]]

^<<v6-22-30,30>>^ Quando o sacerdote Fineias, os maiorais da assembleia e os cabeças dos milhares^&#42;1^ de Israel que estavam com ele ouviram as palavras ditas pelos descendentes de Rúben, de Gade e de Manassés, ficaram satisfeitos.

[NOTE]
====
. Ou: “clãs”.
====

[[v6-22-31]]

^<<v6-22-31,31>>^ Assim, Fineias, filho de Eleazar, o sacerdote, disse aos descendentes de Rúben, de Gade e de Manassés: “Hoje sabemos que Jeová está no nosso meio, porque vocês não cometeram esse ato de infidelidade contra Jeová. Agora, vocês livraram os israelitas das mãos de Jeová.”

[[v6-22-32]]

^<<v6-22-32,32>>^ Depois, Fineias, filho de Eleazar, o sacerdote, e os maiorais deixaram os rubenitas e os gaditas na terra de Gileade e regressaram à terra de Canaã, levando a informação aos outros israelitas.

[[v6-22-33]]

^<<v6-22-33,33>>^ E os israelitas ficaram satisfeitos com o relatório. A seguir, os israelitas louvaram a Deus e não voltaram a falar em guerrear contra os rubenitas e os gaditas, para destruir a terra em que eles moravam.

[[v6-22-34]]

^<<v6-22-34,34>>^ Então, os rubenitas e os gaditas deram um nome ao altar,^&#42;1^ porque “ele é testemunha entre nós de que Jeová é o verdadeiro Deus”.

[NOTE]
====
. Em vista da explicação dada, provavelmente chamou-se ao altar Testemunha.
====

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]