include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-7-1]]

^<<v6-7-1,1>>^ Contudo, os israelitas foram infiéis em relação ao que tinha sido condenado à destruição,^&#42;1^ pois Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá, tirou algumas coisas daquilo que tinha sido condenado à destruição. Em vista disso, a ira de Jeová acendeu-se contra os israelitas.

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-7-2]]

^<<v6-7-2,2>>^ Josué enviou então homens de Jericó a Ai, que fica perto de Bete-Áven e a leste de Betel, e disse-lhes: “Vão e espiem a terra.” Portanto, os homens foram e espiaram Ai.

[[v6-7-3]]

^<<v6-7-3,3>>^ Quando voltaram a Josué, disseram-lhe: “Não é necessário que todo o povo vá. Cerca de 2000 ou 3000 homens são suficientes para derrotar Ai. Não canses todo o povo por os mandares ir, pois os habitantes de lá são poucos.”

[[v6-7-4]]

^<<v6-7-4,4>>^ Assim, cerca de 3000 homens foram para lá, mas eles tiveram de fugir dos homens de Ai.

[[v6-7-5]]

^<<v6-7-5,5>>^ Os homens de Ai mataram 36 homens; perseguiram os israelitas desde o lado de fora do portão até Sebarim,^&#42;1^ matando-os na descida. Por isso, o coração^&#42;2^ do povo derreteu-se e tornou-se como água.

[NOTE]
====
. Que significa “pedreiras”.
. Ou: “a coragem”.
====

[[v6-7-6]]

^<<v6-7-6,6>>^ Em vista disso, Josué rasgou as suas roupas e prostrou-se com o rosto por terra diante da Arca de Jeová até ao anoitecer, ele e os anciãos de Israel, e atiraram pó sobre a cabeça.

[[v6-7-7]]

^<<v6-7-7,7>>^ Josué disse: “Ai, Soberano Senhor Jeová, porque é que fizeste este povo atravessar o Jordão? Foi para nos entregares aos amorreus, para sermos destruídos? Quem me dera que nos tivéssemos contentado em permanecer do outro lado^&#42;1^ do Jordão!

[NOTE]
====
. Isto é, do lado leste.
====

[[v6-7-8]]

^<<v6-7-8,8>>^ Perdão, ó Jeová, o que posso dizer, agora que Israel fugiu^&#42;1^ dos seus inimigos?

[NOTE]
====
. Ou: “virou as costas diante”.
====

[[v6-7-9]]

^<<v6-7-9,9>>^ Quando os cananeus e todos os habitantes desta terra ouvirem falar disto, eles irão cercar-nos e apagar o nosso nome da terra, e o que é que tu farás em relação ao teu grande nome?”

[[v6-7-10]]

^<<v6-7-10,10>>^ Jeová respondeu a Josué: “Levanta-te! Porque é que estás prostrado com o rosto por terra?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel pecou; eles violaram o pacto que lhes ordenei que guardassem. Tiraram algumas coisas daquilo que tinha sido condenado à destruição,^&#42;1^ furtando-as e colocando-as secretamente entre os seus próprios bens.

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-7-12]]

^<<v6-7-12,12>>^ Por isso, os israelitas não poderão resistir aos seus inimigos. Virarão as costas para fugir dos seus inimigos, visto que se tornaram algo condenado à destruição.^&#42;1^ Não estarei mais convosco, a menos que eliminem do vosso meio o que foi condenado à destruição.

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-7-13]]

^<<v6-7-13,13>>^ Levanta-te e santifica o povo! Diz-lhes: ‘Santifiquem-se para amanhã, pois assim diz Jeová, o Deus de Israel: “Há algo condenado à destruição^&#42;1^ no teu meio, ó Israel. Vocês não poderão resistir aos vossos inimigos até que removam do vosso meio o que está condenado à destruição.

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v6-7-14]]

^<<v6-7-14,14>>^ Devem apresentar-se de manhã, tribo por tribo; a tribo que Jeová selecionar vai aproximar-se, família por família; a família que Jeová selecionar vai aproximar-se, casa por casa; e a casa que Jeová selecionar vai aproximar-se, homem por homem.

[[v6-7-15]]

^<<v6-7-15,15>>^ E aquele que for apanhado com a coisa condenada à destruição^&#42;1^ será queimado no fogo, ele e tudo o que for dele, porque violou o pacto de Jeová e porque cometeu um ato vergonhoso em Israel.”’”

[NOTE]
====
. Ou: “devotada à destruição”. Veja o Glossário.
====

[[v6-7-16]]

^<<v6-7-16,16>>^ Na manhã seguinte, Josué levantou-se cedo e fez Israel apresentar-se, tribo por tribo, e a tribo de Judá foi selecionada.

[[v6-7-17]]

^<<v6-7-17,17>>^ Fez as famílias de Judá apresentarem-se e a família dos zeraítas foi selecionada. Depois, fez a família dos zeraítas apresentar-se, homem por homem, e Zabdi foi selecionado.

[[v6-7-18]]

^<<v6-7-18,18>>^ Por fim, fez os da casa de Zabdi apresentarem-se, homem por homem, e Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá, foi selecionado.

[[v6-7-19]]

^<<v6-7-19,19>>^ Josué disse então a Acã: “Meu filho, por favor, honra a Jeová, o Deus de Israel, e confessa-te a ele. Por favor, diz-me o que fizeste. Não me escondas nada.”

[[v6-7-20]]

^<<v6-7-20,20>>^ Acã disse a Josué: “De facto, fui eu que pequei contra Jeová, o Deus de Israel, e o que fiz foi o seguinte:

[[v6-7-21]]

^<<v6-7-21,21>>^ quando vi no meio do despojo um belo manto oficial de Sinear, 200 siclos^&#42;1^ de prata e uma barra de ouro de 50 siclos, desejei-os e tirei-os. Estão escondidos na minha tenda, enterrados no chão, com o dinheiro por baixo.”

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v6-7-22]]

^<<v6-7-22,22>>^ Josué enviou imediatamente mensageiros, e eles foram a correr até à tenda; lá, na tenda, estava escondido o manto, com o dinheiro por baixo.

[[v6-7-23]]

^<<v6-7-23,23>>^ Assim, tiraram as coisas da tenda e levaram-nas a Josué e a todos os israelitas, e puseram-nas diante de Jeová.

[[v6-7-24]]

^<<v6-7-24,24>>^ Então, Josué e todo o Israel com ele agarraram Acã, filho de Zerá, assim como a prata, o manto oficial, a barra de ouro, os seus filhos, as suas filhas, os seus touros, os seus jumentos, as suas ovelhas, a sua tenda e tudo o que era seu, e levaram-nos para o vale^&#42;1^ de Acor.

[NOTE]
====
. Ou: “a planície”.
====

[[v6-7-25]]

^<<v6-7-25,25>>^ Josué disse: “Porque é que trouxeste calamidade^&#42;1^ sobre nós? Hoje, Jeová trará calamidade sobre ti.” Então, todo o Israel o apedrejou; depois disso queimou-os a todos no fogo. Assim, foram todos apedrejados.

[NOTE]
====
. Ou: “dificuldade; ostracismo”, isto é, exclusão.
====

[[v6-7-26]]

^<<v6-7-26,26>>^ E levantaram sobre ele um grande monte de pedras, que permanece até ao dia de hoje. Em vista disso, a ira ardente de Jeová diminuiu. É por isso que se chama àquele lugar vale de Acor^&#42;1^ até ao dia de hoje.

[NOTE]
====
. Que significa “calamidade; ostracismo”, isto é, exclusão.
====

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]