include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-11-1]]

^<<v6-11-1,1>>^ Assim que Jabim, rei de Hazor, ouviu dizer isso, enviou mensageiros a Jobabe, rei de Madom, ao rei de Sinrom, ao rei de Acsafe,

[[v6-11-2]]

^<<v6-11-2,2>>^ aos reis da região montanhosa do norte, aos das planícies^&#42;1^ a sul de Quinerete, aos da Sefelá, aos das encostas de Dor a oeste,

[NOTE]
====
. Ou: “do Arabá”.
====

[[v6-11-3]]

^<<v6-11-3,3>>^ aos cananeus a leste e a oeste, aos amorreus, aos hititas, aos perizeus, aos jebuseus na região montanhosa, e aos heveus no sopé do Hermom, na terra de Mispá.

[[v6-11-4]]

^<<v6-11-4,4>>^ Portanto, todos estes reis saíram com os seus exércitos, uma enorme multidão tão numerosa como os grãos de areia à beira-mar, com muitíssimos cavalos e carros de guerra.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos estes reis concordaram em reunir-se e foram acampar juntos, perto das águas de Merom, para lutar contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ Perante isto, Jeová disse a Josué: “Não tenhas medo por causa deles, pois amanhã, por volta desta hora, entregarei todos eles, mortos, a Israel. Corta os tendões dos seus cavalos e queima os seus carros no fogo.”

[[v6-11-7]]

^<<v6-11-7,7>>^ Josué e todos os homens de guerra fizeram então um ataque-surpresa contra eles junto às águas de Merom.

[[v6-11-8]]

^<<v6-11-8,8>>^ Jeová entregou-os nas mãos de Israel, e eles derrotaram-nos e perseguiram-nos até Sídon, a Grande, e Misrefote-Maim, e o vale de Mispa, a leste, e eles mataram-nos sem deixar nenhum sobrevivente.

[[v6-11-9]]

^<<v6-11-9,9>>^ E Josué fez-lhes assim como Jeová lhe tinha dito: cortou os tendões dos seus cavalos e queimou os seus carros no fogo.

[[v6-11-10]]

^<<v6-11-10,10>>^ Josué voltou então e tomou Hazor, e matou o seu rei com a espada, visto que anteriormente Hazor tinha sido a cidade principal de todos esses reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ Eles mataram com a espada todos os^&#42;1^ que lá havia, entregando-os à destruição.^&#42;2^ Não sobrou nada que respirasse. Então, ele queimou Hazor com fogo.

[NOTE]
====
. Ou: “toda a alma”.
. Ou: “devotando-os à destruição”. Veja o Glossário.
====

[[v6-11-12]]

^<<v6-11-12,12>>^ Josué tomou todas as cidades desses reis e derrotou todos os seus reis, golpeando-os com a espada. Ele entregou-os à destruição,^&#42;1^ assim como Moisés, o servo de Jeová, tinha ordenado.

[NOTE]
====
. Ou: “devotou-os à destruição”. Veja o Glossário.
====

[[v6-11-13]]

^<<v6-11-13,13>>^ Contudo, Israel não queimou nenhuma das cidades que ficavam sobre montes, com exceção de Hazor, que foi a única que Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ Os israelitas saquearam para si todo o despojo e os animais dessas cidades, mas golpearam com a espada todos os humanos até exterminarem cada um deles. Não deixaram sobrar ninguém que respirasse.

[[v6-11-15]]

^<<v6-11-15,15>>^ Assim como Jeová tinha ordenado a Moisés, seu servo, assim Moisés ordenou a Josué, e Josué assim o fez. Ele não deixou de cumprir nada de tudo o que Jeová tinha ordenado a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Josué conquistou toda esta terra, a região montanhosa, todo o Neguebe, toda a terra de Gósen, a Sefelá, o Arabá e a região montanhosa de Israel com a sua Sefelá,^&#42;1^

[NOTE]
====
. Ou: “os seus contrafortes”.
====

[[v6-11-17]]

^<<v6-11-17,17>>^ desde o monte Halaque, que se eleva em direção a Seir, até Baal-Gade, no vale do Líbano, no sopé do monte Hermom; ele capturou todos os seus reis, derrotou-os e matou-os.

[[v6-11-18]]

^<<v6-11-18,18>>^ Josué guerreou contra todos estes reis durante muito tempo.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não houve nenhuma cidade que fizesse paz com os israelitas, exceto os heveus que moravam em Gibeão. Eles conquistaram todas as outras através de guerra.

[[v6-11-20]]

^<<v6-11-20,20>>^ Foi Jeová quem permitiu que os seus corações ficassem obstinados para guerrearem contra Israel, a fim de que ele os entregasse à destruição^&#42;1^ sem ter compaixão. Eles deveriam ser exterminados, assim como Jeová tinha ordenado a Moisés.

[NOTE]
====
. Ou: “devotasse à destruição”. Veja o Glossário.
====

[[v6-11-21]]

^<<v6-11-21,21>>^ Naquela altura, Josué eliminou os anaquins da região montanhosa, de Hébron, de Debir e de Anabe, bem como de toda a região montanhosa de Judá e de toda a região montanhosa de Israel. Josué entregou-os à destruição,^&#42;1^ tanto a eles como às suas cidades.

[NOTE]
====
. Ou: “devotou-os à destruição”. Veja o Glossário.
====

[[v6-11-22]]

^<<v6-11-22,22>>^ Não sobrou nenhum anaquim na terra dos israelitas. Só ficaram alguns em Gaza, em Gate e em Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ Assim, Josué assumiu o controlo de toda a terra, conforme Jeová tinha prometido a Moisés. Então, Josué deu-a como herança a Israel, para a repartir entre as suas tribos, conforme a porção devida a cada tribo. E a terra teve descanso da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]