include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-17-1]]

^<<v6-17-1,1>>^ Então, a sorte caiu à tribo de Manassés, pois era o primogénito de José. Visto que Maquir, primogénito de Manassés e pai de Gileade, era um homem de guerra, recebeu Gileade e Basã.

[[v6-17-2]]

^<<v6-17-2,2>>^ E a sorte caiu ao restante dos descendentes de Manassés, segundo as suas famílias: os filhos de Abiezer, os filhos de Heleque, os filhos de Asriel, os filhos de Siquém, os filhos de Hefer e os filhos de Semida. Estes eram os descendentes de Manassés, filho de José, os homens segundo as suas famílias.

[[v6-17-3]]

^<<v6-17-3,3>>^ Contudo, Zelofeade, filho de Hefer, filho de Gileade, filho de Maquir, filho de Manassés, não teve filhos, só filhas; e os nomes das suas filhas eram: Maala, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Por isso, elas compareceram perante Eleazar, o sacerdote, Josué, filho de Num, e os maiorais, e disseram: “Foi Jeová quem ordenou a Moisés que nos desse uma herança entre os nossos irmãos.” Assim, por ordem de Jeová, ele deu-lhes uma herança entre os irmãos do seu pai.

[[v6-17-5]]

^<<v6-17-5,5>>^ E dez partes couberam a Manassés, além da terra de Gileade e de Basã, que ficava do outro lado^&#42;1^ do Jordão,

[NOTE]
====
. Isto é, do lado leste.
====

[[v6-17-6]]

^<<v6-17-6,6>>^ pois as filhas de Manassés receberam uma herança juntamente com os filhos dele. E a terra de Gileade tornou-se propriedade dos outros descendentes de Manassés.

[[v6-17-7]]

^<<v6-17-7,7>>^ E o limite do território de Manassés ia desde Aser até Micmetate, que fica em frente a Siquém, e o limite continuava em direção ao sul,^&#42;1^ até à terra onde moravam os habitantes de En-Tapua.

[NOTE]
====
. Lit.: “ia para a direita”.
====

[[v6-17-8]]

^<<v6-17-8,8>>^ A terra de Tapua tornou-se de Manassés, mas a cidade de Tapua, no limite do território de Manassés, pertencia aos descendentes de Efraim.

[[v6-17-9]]

^<<v6-17-9,9>>^ E o limite descia para o sul até ao vale^&#42;1^ de Caná, até ao sul do vale. Havia cidades de Efraim entre as cidades de Manassés; e o limite do território de Manassés ficava a norte do vale e terminava no mar.

[NOTE]
====
. Ou: “uádi”.
====

[[v6-17-10]]

^<<v6-17-10,10>>^ O território a sul pertencia a Efraim, e o território a norte pertencia a Manassés, e o mar era o seu limite. E o território de Manassés chegava^&#42;1^ até Aser, a norte, e até Issacar, a leste.

[NOTE]
====
. Lit.: “E eles chegavam”.
====

[[v6-17-11]]

^<<v6-17-11,11>>^ Nos territórios de Issacar e de Aser, Manassés ficou com Bete-Seã e as suas aldeias dependentes,^&#42;1^ Ibleão e as suas aldeias dependentes, os habitantes de Dor e as suas aldeias dependentes, os habitantes de En-Dor e as suas aldeias dependentes, os habitantes de Taanaque e as suas aldeias dependentes, e os habitantes de Megido e as suas aldeias dependentes, sendo três delas regiões de colinas.

[NOTE]
====
. Ou: “ao redor”.
====

[[v6-17-12]]

^<<v6-17-12,12>>^ Mas os descendentes de Manassés não conseguiram tomar posse destas cidades, pois os cananeus persistiam em morar nesta região.

[[v6-17-13]]

^<<v6-17-13,13>>^ Quando os israelitas ficaram fortes, sujeitaram os cananeus a trabalhos forçados, mas não os expulsaram^&#42;1^ completamente.

[NOTE]
====
. Ou: “desapossaram”.
====

[[v6-17-14]]

^<<v6-17-14,14>>^ Os descendentes de José disseram a Josué: “Porque é que nos^&#42;1^ deste como herança apenas um lote, uma parte da terra? Somos um povo numeroso, pois Jeová abençoou-nos até agora.”

[NOTE]
====
. Lit.: “me”.
====

[[v6-17-15]]

^<<v6-17-15,15>>^ Josué respondeu-lhes: “Se são um povo tão numeroso, vão à floresta e limpem uma área para vocês na terra dos perizeus e dos refains, visto que a região montanhosa de Efraim é demasiado apertada para vocês.”

[[v6-17-16]]

^<<v6-17-16,16>>^ Então, os descendentes de José disseram: “A região montanhosa não é suficiente para nós, e todos os cananeus que moram na terra do vale^&#42;1^ têm carros de guerra com foices de ferro,^&#42;2^ tanto os que moram em Bete-Seã e nas suas aldeias dependentes^&#42;3^ como os que moram no vale^&#42;4^ de Jezreel.”

[NOTE]
====
. Ou: “da planície”.
. Lit.: “carros de ferro”.
. Ou: “ao redor”.
. Ou: “na planície”.
====

[[v6-17-17]]

^<<v6-17-17,17>>^ Portanto, Josué disse o seguinte à casa de José, isto é, a Efraim e Manassés: “Vocês são um povo numeroso, e grande é o vosso poder. Não receberão apenas uma parte,

[[v6-17-18]]

^<<v6-17-18,18>>^ mas a região montanhosa também será vossa. Embora seja uma floresta, vocês irão limpá-la, e ela será a extremidade do vosso território. Expulsarão os cananeus, apesar de eles serem fortes e terem carros de guerra com foices de ferro.”^&#42;1^

[NOTE]
====
. Lit.: “carros de ferro”.
====

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]