include::./index.adoc[]

[[v6-16-0]]
=== Josué, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-16-1]]

^<<v6-16-1,1>>^ E a terra que coube por sortes^&#42;1^ aos descendentes de José ia desde o Jordão, perto de Jericó, até às águas a leste de Jericó, e estendia-se pelo deserto que sobe de Jericó e ia até à região montanhosa de Betel.

[NOTE]
====
. Ou: “que foi distribuída”.
====

[[v6-16-2]]

^<<v6-16-2,2>>^ Estendia-se desde Betel, que pertence a Luz, e continuava até ao limite do território dos arquitas, em Atarote.

[[v6-16-3]]

^<<v6-16-3,3>>^ Então, descia na direção oeste, para o limite do território dos jafletitas, até ao limite de Bete-Horom Baixa e Gezer, e terminava no mar.

[[v6-16-4]]

^<<v6-16-4,4>>^ Assim, Manassés e Efraim, descendentes de José, tomaram posse das suas terras.

[[v6-16-5]]

^<<v6-16-5,5>>^ Este era o limite do território dos descendentes de Efraim, segundo as suas famílias: o limite leste da sua herança ia de Atarote-Adar até Bete-Horom Alta,

[[v6-16-6]]

^<<v6-16-6,6>>^ e o limite estendia-se até ao mar. Micmetate ficava a norte; e o limite virava para o leste, até Taanate-Silo, e seguia na direção leste até Janoa.

[[v6-16-7]]

^<<v6-16-7,7>>^ Então, descia de Janoa para Atarote e Naará, chegava a Jericó e estendia-se até ao Jordão.

[[v6-16-8]]

^<<v6-16-8,8>>^ De Tapua, o limite continuava em direção ao oeste até ao vale^&#42;1^ de Caná e terminava no mar. Esta foi a herança da tribo de Efraim, segundo as suas famílias.

[NOTE]
====
. Ou: “uádi”.
====

[[v6-16-9]]

^<<v6-16-9,9>>^ A herança também incluía todas as cidades e povoados que os descendentes de Efraim tinham no meio da herança dos filhos de Manassés.

[[v6-16-10]]

^<<v6-16-10,10>>^ Eles, porém, não expulsaram os cananeus que moravam em Gezer, e os cananeus continuam a morar no meio de Efraim até ao dia de hoje, sujeitos a trabalhos forçados.

'''

xref:006-josue/006-josue-015.adoc#v6-15-0[&#60; Capítulo Anterior] | <<v6-16-0,Topo>> | xref:006-josue/006-josue-017.adoc#v6-17-0[Próximo Capítulo &#62;]