include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-9-1]]

^<<v6-9-1,1>>^ Quando a notícia chegou a todos os reis que estavam do lado oeste do Jordão, os que estavam na região montanhosa, na Sefelá, ao longo de toda a costa do Grande Mar^&#42;1^ e em frente ao Líbano — os hititas, os amorreus, os cananeus, os perizeus, os heveus e os jebuseus —,

[NOTE]
====
. Isto é, o Mediterrâneo.
====

[[v6-9-2]]

^<<v6-9-2,2>>^ eles formaram uma aliança para lutar contra Josué e Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ Os habitantes de Gibeão também ouviram dizer o que Josué tinha feito a Jericó e a Ai.

[[v6-9-4]]

^<<v6-9-4,4>>^ Por isso, agiram com astúcia: colocaram provisões em sacas velhas e puseram-nas sobre os seus jumentos, juntamente com odres de vinho rebentados e remendados.

[[v6-9-5]]

^<<v6-9-5,5>>^ Puseram também sandálias gastas e remendadas nos pés, e vestiram roupas gastas. Todo o pão que levavam estava seco e desfazia-se.

[[v6-9-6]]

^<<v6-9-6,6>>^ Depois, foram ter com Josué ao acampamento em Gilgal e disseram-lhe a ele e aos homens de Israel: “Viemos de uma terra distante. Agora, façam um pacto connosco.”

[[v6-9-7]]

^<<v6-9-7,7>>^ Contudo, os homens de Israel disseram aos heveus: “Talvez vocês morem perto de nós. Então, como é que podemos fazer um pacto convosco?”

[[v6-9-8]]

^<<v6-9-8,8>>^ Eles responderam a Josué: “Somos teus servos.”^&#42;1^
Em seguida, Josué perguntou-lhes: “Quem são vocês e de onde vieram?”

[NOTE]
====
. Ou: “escravos”.
====

[[v6-9-9]]

^<<v6-9-9,9>>^ Eles responderam: “Os teus servos vieram de uma terra bem distante por causa do nome de Jeová, teu Deus, pois ouvimos falar da sua fama e de tudo o que ele fez no Egito,

[[v6-9-10]]

^<<v6-9-10,10>>^ e de tudo o que fez aos dois reis dos amorreus do outro lado^&#42;1^ do Jordão, a Síon, rei de Hésbon, e a Ogue, rei de Basã, que morava em Astarote.

[NOTE]
====
. Isto é, do lado leste.
====

[[v6-9-11]]

^<<v6-9-11,11>>^ Por isso, os nossos anciãos e todos os habitantes da nossa terra disseram-nos: ‘Tomem provisões para a viagem e vão ter com eles. Digam-lhes: “Seremos os vossos servos; por isso, façam um pacto connosco.”’

[[v6-9-12]]

^<<v6-9-12,12>>^ Este pão que trouxemos como provisão para nós ainda estava quente no dia em que saímos das nossas casas para vir ter convosco. Agora, podes ver que está seco e a desfazer-se.

[[v6-9-13]]

^<<v6-9-13,13>>^ E estes odres de vinho estavam novos quando os enchemos, mas agora já rebentaram. E as nossas roupas e sandálias ficaram gastas por causa da viagem muito longa.”

[[v6-9-14]]

^<<v6-9-14,14>>^ Em vista disso, os homens de Israel pegaram em^&#42;1^ algumas das provisões deles, mas não consultaram a Jeová.

[NOTE]
====
. Ou: “examinaram”.
====

[[v6-9-15]]

^<<v6-9-15,15>>^ Assim, Josué fez paz com eles e um pacto para que continuassem a viver, e os maiorais da assembleia confirmaram isso com um juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ Três dias depois de terem feito um pacto com eles, ficaram a saber que moravam perto deles, na vizinhança.

[[v6-9-17]]

^<<v6-9-17,17>>^ Os israelitas partiram então e chegaram às cidades deles no terceiro dia; as suas cidades eram Gibeão, Quefira, Beerote e Quiriate-Jearim.

[[v6-9-18]]

^<<v6-9-18,18>>^ Mas os israelitas não os atacaram, visto que os maiorais da assembleia lhes tinham feito um juramento por Jeová, o Deus de Israel. Por isso, toda a assembleia começou a queixar-se dos maiorais.

[[v6-9-19]]

^<<v6-9-19,19>>^ Em vista disso, todos os maiorais disseram a toda a assembleia: “Visto que nós lhes fizemos um juramento por Jeová, o Deus de Israel, não podemos fazer nada contra eles.

[[v6-9-20]]

^<<v6-9-20,20>>^ Faremos o seguinte: vamos deixá-los viver, para que não haja indignação contra nós por causa do juramento que lhes fizemos.”

[[v6-9-21]]

^<<v6-9-21,21>>^ E os maiorais acrescentaram: “Que eles vivam, mas que se tornem cortadores de lenha e tiradores de água para toda a assembleia.” Foi isto o que os maiorais lhes prometeram.

[[v6-9-22]]

^<<v6-9-22,22>>^ Josué chamou-os então e perguntou-lhes: “Porque é que nos enganaram, dizendo: ‘Somos de um lugar muito distante’, quando na verdade moram mesmo no nosso meio?

[[v6-9-23]]

^<<v6-9-23,23>>^ De agora em diante, são amaldiçoados, e serão sempre escravos, trabalhando como cortadores de lenha e tiradores de água para a casa do meu Deus.”

[[v6-9-24]]

^<<v6-9-24,24>>^ Eles disseram a Josué: “Agimos assim porque se disse claramente a nós, teus servos, que Jeová, teu Deus, tinha ordenado a Moisés, seu servo, que vos desse toda esta terra e eliminasse todos os habitantes dela da vossa frente. Por isso, tememos pelas nossas vidas,^&#42;1^ por vossa causa, e é por isso que agimos assim.

[NOTE]
====
. Ou: “almas”.
====

[[v6-9-25]]

^<<v6-9-25,25>>^ Agora, estamos nas tuas mãos. Faz connosco o que achares bom e justo.”

[[v6-9-26]]

^<<v6-9-26,26>>^ E foi isto o que Josué fez: livrou-os das mãos dos israelitas, e eles não os mataram.

[[v6-9-27]]

^<<v6-9-27,27>>^ No entanto, naquele dia, Josué fez deles cortadores de lenha e tiradores de água para a assembleia e para o altar de Jeová no lugar que Ele escolhesse, e eles continuam a fazer isso até ao dia de hoje.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]