include::./index.adoc[]

[[v6-1-0]]
=== Josué, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v6-1-1]]

^<<v6-1-1,1>>^ Depois da morte de Moisés, o servo de Jeová, Jeová disse a Josué,^&#42;1^ filho de Num, ajudante de Moisés:

[NOTE]
====
. Que significa “Jeová é salvação”.
====

[[v6-1-2]]

^<<v6-1-2,2>>^ “Moisés, o meu servo, morreu. Agora prepara-te, atravessa o Jordão, tu e todo este povo, e vai para a terra que darei ao povo de Israel.

[[v6-1-3]]

^<<v6-1-3,3>>^ Vou dar-vos todos os lugares em que pisarem, assim como prometi a Moisés.

[[v6-1-4]]

^<<v6-1-4,4>>^ O vosso território vai estender-se desde o deserto até ao Líbano e ao grande rio, o rio Eufrates — toda a terra dos hititas — e até ao Grande Mar,^&#42;1^ a oeste.^&#42;2^

[NOTE]
====
. Isto é, o Mediterrâneo.
. Ou: “na direção do pôr do sol”.
====

[[v6-1-5]]

^<<v6-1-5,5>>^ Ninguém te poderá resistir enquanto viveres. Estarei contigo, assim como estive com Moisés. Não te desampararei nem te abandonarei.

[[v6-1-6]]

^<<v6-1-6,6>>^ Sê corajoso e forte, pois és tu que farás este povo herdar a terra que lhes darei, conforme jurei aos seus antepassados.

[[v6-1-7]]

^<<v6-1-7,7>>^ “Apenas sê corajoso e muito forte, e obedece cuidadosamente a toda a Lei que Moisés, o meu servo, te ordenou. Não te desvies dela nem para a direita nem para a esquerda, a fim de agires sabiamente por onde quer que vás.

[[v6-1-8]]

^<<v6-1-8,8>>^ Este livro da Lei não se deve afastar da tua boca; lê-o em voz baixa^&#42;1^ dia e noite, para cumprires cuidadosamente tudo o que está escrito nele. Assim, o teu caminho será bem-sucedido, e agirás sabiamente.

[NOTE]
====
. Ou: “medita nele”.
====

[[v6-1-9]]

^<<v6-1-9,9>>^ Não te ordenei que fosses corajoso e forte? Não fiques apavorado nem tenhas medo, pois Jeová, teu Deus, estará contigo por onde quer que vás.”

[[v6-1-10]]

^<<v6-1-10,10>>^ Então, Josué ordenou aos oficiais do povo:

[[v6-1-11]]

^<<v6-1-11,11>>^ “Percorram todo o acampamento e deem esta ordem ao povo: ‘Preparem provisões, porque em três dias atravessarão o Jordão para tomar posse da terra que Jeová, vosso Deus, vos dá como propriedade.’”

[[v6-1-12]]

^<<v6-1-12,12>>^ E aos rubenitas, aos gaditas e à meia tribo de Manassés, Josué disse:

[[v6-1-13]]

^<<v6-1-13,13>>^ “Lembrem-se do que Moisés, o servo de Jeová, vos ordenou: ‘Jeová, vosso Deus, dá-vos descanso; ele deu-vos esta terra.

[[v6-1-14]]

^<<v6-1-14,14>>^ As vossas esposas, os vossos filhos e os vossos animais morarão na terra que Moisés vos deu deste lado^&#42;1^ do Jordão. Mas todos vocês, guerreiros valentes, devem atravessar em formação de batalha à frente dos vossos irmãos. Têm de os ajudar

[NOTE]
====
. Isto é, do lado leste.
====

[[v6-1-15]]

^<<v6-1-15,15>>^ até que Jeová dê descanso aos vossos irmãos, assim como vos deu, e eles também tomem posse da terra que Jeová, vosso Deus, lhes dá. Então, voltem à terra que receberam para ocupar e tomem posse dela, a terra que Moisés, o servo de Jeová, vos deu do lado leste do Jordão.’”

[[v6-1-16]]

^<<v6-1-16,16>>^ Eles responderam a Josué: “Faremos tudo o que nos ordenaste e iremos onde quer que nos envies.

[[v6-1-17]]

^<<v6-1-17,17>>^ Assim como escutámos tudo o que Moisés disse, também te escutaremos. Acima de tudo, que Jeová, teu Deus, esteja contigo assim como esteve com Moisés.

[[v6-1-18]]

^<<v6-1-18,18>>^ Qualquer homem que se rebelar contra as tuas ordens e que não obedecer a tudo o que lhe ordenares será morto. Apenas sê corajoso e forte.”

'''

xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-josue/006-josue-002.adoc#v6-2-0[Próximo Capítulo &#62;]