include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-136-1]]

^<<v19-136-1,1>>^ Agradeçam a Jeová, pois ele é bom;
O seu amor leal dura para sempre.

[[v19-136-2]]

^<<v19-136-2,2>>^ Agradeçam ao Deus dos deuses,
Pois o seu amor leal dura para sempre.

[[v19-136-3]]

^<<v19-136-3,3>>^ Agradeçam ao Senhor dos senhores,
Pois o seu amor leal dura para sempre.

[[v19-136-4]]

^<<v19-136-4,4>>^ Só ele é que faz grandes maravilhas,
Pois o seu amor leal dura para sempre.

[[v19-136-5]]

^<<v19-136-5,5>>^ Ele fez os céus com perícia,^&#42;1^
Pois o seu amor leal dura para sempre.

[NOTE]
====
. Ou: “entendimento”.
====

[[v19-136-6]]

^<<v19-136-6,6>>^ Estendeu a terra sobre as águas,
Pois o seu amor leal dura para sempre.

[[v19-136-7]]

^<<v19-136-7,7>>^ Fez as grandes luzes,
Pois o seu amor leal dura para sempre,

[[v19-136-8]]

^<<v19-136-8,8>>^ O sol para dominar o dia,
Pois o seu amor leal dura para sempre,

[[v19-136-9]]

^<<v19-136-9,9>>^ A lua e as estrelas para dominarem a noite,
Pois o seu amor leal dura para sempre.

[[v19-136-10]]

^<<v19-136-10,10>>^ Ele matou os primogénitos do Egito,
Pois o seu amor leal dura para sempre.

[[v19-136-11]]

^<<v19-136-11,11>>^ Tirou Israel do seu meio,
Pois o seu amor leal dura para sempre,

[[v19-136-12]]

^<<v19-136-12,12>>^ Com mão poderosa e com braço estendido,
Pois o seu amor leal dura para sempre.

[[v19-136-13]]

^<<v19-136-13,13>>^ Ele dividiu o mar Vermelho em dois,^&#42;1^
Pois o seu amor leal dura para sempre.

[NOTE]
====
. Lit.: “em pedaços”.
====

[[v19-136-14]]

^<<v19-136-14,14>>^ Fez com que Israel passasse através dele,
Pois o seu amor leal dura para sempre.

[[v19-136-15]]

^<<v19-136-15,15>>^ Ele desembaraçou-se do Faraó e do seu exército no mar Vermelho,
Pois o seu amor leal dura para sempre.

[[v19-136-16]]

^<<v19-136-16,16>>^ Conduziu o seu povo pelo deserto,
Pois o seu amor leal dura para sempre.

[[v19-136-17]]

^<<v19-136-17,17>>^ Derrotou grandes reis,
Pois o seu amor leal dura para sempre.

[[v19-136-18]]

^<<v19-136-18,18>>^ Matou reis poderosos,
Pois o seu amor leal dura para sempre,

[[v19-136-19]]

^<<v19-136-19,19>>^ Síon, rei dos amorreus,
Pois o seu amor leal dura para sempre,

[[v19-136-20]]

^<<v19-136-20,20>>^ E Ogue, rei de Basã,
Pois o seu amor leal dura para sempre.

[[v19-136-21]]

^<<v19-136-21,21>>^ Ele deu a terra deles como herança,
Pois o seu amor leal dura para sempre,

[[v19-136-22]]

^<<v19-136-22,22>>^ Como herança a Israel, seu servo,
Pois o seu amor leal dura para sempre.

[[v19-136-23]]

^<<v19-136-23,23>>^ Ele lembrou-se de nós na nossa humilhação,
Pois o seu amor leal dura para sempre.

[[v19-136-24]]

^<<v19-136-24,24>>^ Ele livrava-nos sempre dos nossos adversários,
Pois o seu amor leal dura para sempre.

[[v19-136-25]]

^<<v19-136-25,25>>^ Ele dá alimento a todos os seres vivos,^&#42;1^
Pois o seu amor leal dura para sempre.

[NOTE]
====
. Lit.: “toda a carne”.
====

[[v19-136-26]]

^<<v19-136-26,26>>^ Agradeçam ao Deus dos céus,
Pois o seu amor leal dura para sempre.

'''

xref:019-salmo/019-salmo-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmo/019-salmo-137.adoc#v19-137-0[Próximo Capítulo &#62;]