include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente; com a melodia de Os Lírios. De David._

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus, porque as águas ameaçam a minha vida.^&#42;1^

[NOTE]
====
. Ou: “chegaram à minha alma”.
====

[[v19-69-2]]

^<<v19-69-2,2>>^ Afundei-me num lamaçal profundo e não há onde firmar o pé.
Entrei em águas profundas,
E a forte corrente arrastou-me.

[[v19-69-3]]

^<<v19-69-3,3>>^ Estou exausto de tanto clamar,
A minha voz está rouca.
Os meus olhos enfraquecem enquanto espero pelo meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ Os que me odeiam sem motivo
São mais numerosos do que os cabelos da minha cabeça.
Os que querem matar-me,
Os meus traiçoeiros inimigos,^&#42;1^ tornaram-se muitos.
Fui forçado a devolver o que não tinha roubado.

[NOTE]
====
. Ou: “Os meus inimigos sem motivo”.
====

[[v19-69-5]]

^<<v19-69-5,5>>^ Ó Deus, tu conheces a minha tolice,
E a minha culpa não te está oculta.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não sejam envergonhados por minha causa os que esperam em ti,
Ó Soberano Senhor, Jeová dos exércitos.
Não sejam humilhados por minha causa os que te procuram,
Ó Deus de Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ Sofro insultos por tua causa,
A humilhação cobre o meu rosto.

[[v19-69-8]]

^<<v19-69-8,8>>^ Tornei-me um estranho para os meus irmãos,
Um estrangeiro para os filhos da minha mãe.

[[v19-69-9]]

^<<v19-69-9,9>>^ O zelo pela tua casa consome-me;
Os insultos daqueles que te insultam caem sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Quando me humilhei^&#42;1^ com jejum,^&#42;2^
Fui insultado por causa disso.

[NOTE]
====
. Ou: “humilhei a minha alma”.
. Ou, possivelmente: “Quando chorei e jejuei”.
====

[[v19-69-11]]

^<<v19-69-11,11>>^ Quando me vesti de serapilheira,^&#42;1^
Tornei-me motivo de gozo^&#42;2^ para eles.

[NOTE]
====
. Veja o Glossário.
. Lit.: “um provérbio”.
====

[[v19-69-12]]

^<<v19-69-12,12>>^ Os que se sentam no portão da cidade falam de mim,
E os bêbados fazem de mim o assunto das suas canções.

[[v19-69-13]]

^<<v19-69-13,13>>^ Mas que a minha oração chegue até ti
Num tempo aceitável, ó Jeová.
No teu imenso amor leal, Ó Deus,
Responde-me com os teus infalíveis atos de salvação.

[[v19-69-14]]

^<<v19-69-14,14>>^ Livra-me do lamaçal,
Não permitas que eu me afunde.
Livra-me dos que me odeiam
E das águas profundas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não permitas que as fortes águas torrenciais me arrastem,
Nem que as profundezas me devorem,
Nem que o poço^&#42;1^ feche a sua boca sobre mim.

[NOTE]
====
. Ou: “a cova”.
====

[[v19-69-16]]

^<<v19-69-16,16>>^ Responde-me, ó Jeová, pois o teu amor leal é bom.
Segundo a tua imensa misericórdia, volta-te para mim,

[[v19-69-17]]

^<<v19-69-17,17>>^ E não escondas a tua face do teu servo.
Responde-me depressa, pois estou em aflição.

[[v19-69-18]]

^<<v19-69-18,18>>^ Aproxima-te de mim e livra-me,^&#42;1^
Resgata-me por causa dos meus inimigos.

[NOTE]
====
. Ou: “Aproxima-te da minha alma e reivindica-a”.
====

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu conheces a minha desonra, a minha vergonha e a minha humilhação.
Vês todos os meus inimigos.

[[v19-69-20]]

^<<v19-69-20,20>>^ A desonra quebrantou-me o coração e a ferida é incurável.^&#42;1^
Esperei por compaixão, mas não havia nenhuma;
Por consoladores, mas não encontrei nenhum.

[NOTE]
====
. Ou: “e eu estou desesperado”.
====

[[v19-69-21]]

^<<v19-69-21,21>>^ Como alimento, deram-me veneno^&#42;1^
E, para matar a minha sede, ofereceram-me vinagre para beber.

[NOTE]
====
. Ou: “uma planta venenosa”.
====

[[v19-69-22]]

^<<v19-69-22,22>>^ Que a sua mesa se torne uma armadilha para eles;
E a sua prosperidade, um laço.

[[v19-69-23]]

^<<v19-69-23,23>>^ Que os seus olhos se escureçam para que não consigam ver,
E que faças com que as suas pernas^&#42;1^ tremam sem parar.

[NOTE]
====
. Lit.: “as suas ancas”.
====

[[v19-69-24]]

^<<v19-69-24,24>>^ Derrama sobre eles a tua indignação,^&#42;1^
E que a tua ira ardente os alcance.

[NOTE]
====
. Ou: “fúria”.
====

[[v19-69-25]]

^<<v19-69-25,25>>^ Que o seu acampamento^&#42;1^ fique desolado,
Que não haja habitantes nas suas tendas.

[NOTE]
====
. Ou: “acampamento murado”.
====

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois eles perseguem aquele que golpeaste
E continuam a falar sobre as dores daqueles que feriste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Acrescenta ainda mais culpa à sua culpa;
Que eles não tenham nenhuma parte na tua justiça.

[[v19-69-28]]

^<<v19-69-28,28>>^ Que sejam apagados do livro dos vivos^&#42;1^
E que não sejam inscritos entre os justos.

[NOTE]
====
. Ou: “livro da vida”.
====

[[v19-69-29]]

^<<v19-69-29,29>>^ Eu estou aflito e sinto dores.
Que o teu poder salvador me proteja, ó Deus.

[[v19-69-30]]

^<<v19-69-30,30>>^ Vou cantar louvores ao nome de Deus
E vou magnificá-lo com agradecimentos.

[[v19-69-31]]

^<<v19-69-31,31>>^ Isso agradará mais a Jeová do que um touro,
Mais do que um novilho com chifres e cascos.

[[v19-69-32]]

^<<v19-69-32,32>>^ Os mansos irão vê-lo e alegrar-se.
Vocês, os que buscam a Deus, que se reanime o vosso coração.

[[v19-69-33]]

^<<v19-69-33,33>>^ Pois Jeová escuta os pobres
E não desprezará o seu povo cativo.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no o céu e a terra,
Os mares e tudo o que neles se move.

[[v19-69-35]]

^<<v19-69-35,35>>^ Pois Deus salvará Sião
E reconstruirá as cidades de Judá;
E eles hão de lá morar e possuí-la.^&#42;1^

[NOTE]
====
. Isto é, possuir a terra.
====

[[v19-69-36]]

^<<v19-69-36,36>>^ Os descendentes dos seus servos irão herdá-la,
E os que amam o seu nome residirão nela.

'''

xref:019-salmo/019-salmo-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmo/019-salmo-070.adoc#v19-70-0[Próximo Capítulo &#62;]