include::./index.adoc[]

[[v19-36-0]]
=== Salmos, 36
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente. Do servo de Jeová, David._

[[v19-36-1]]

^<<v19-36-1,1>>^ No fundo do coração do perverso, a transgressão fala-lhe;
Não há temor de Deus diante dos seus olhos.

[[v19-36-2]]

^<<v19-36-2,2>>^ Pois, aos seus próprios olhos, ele é tão importante
Que não percebe nem odeia o seu erro.

[[v19-36-3]]

^<<v19-36-3,3>>^ As palavras da sua boca ferem e enganam;
Ele não tem entendimento^&#42;1^ para fazer o bem.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v19-36-4]]

^<<v19-36-4,4>>^ Até na sua cama faz planos maldosos.
Ele decidiu-se por um caminho que não é bom;
Não rejeita o mal.

[[v19-36-5]]

^<<v19-36-5,5>>^ Ó Jeová, o teu amor leal alcança os céus;
A tua fidelidade, as nuvens.

[[v19-36-6]]

^<<v19-36-6,6>>^ A tua justiça é como montanhas majestosas;^&#42;1^
Os teus julgamentos são como vastas águas profundas.
Preservas^&#42;2^ o homem e o animal, ó Jeová.

[NOTE]
====
. Lit.: “como montanhas de Deus”.
. Ou: “Salvas”.
====

[[v19-36-7]]

^<<v19-36-7,7>>^ Como é precioso o teu amor leal, ó Deus!
Os filhos dos homens refugiam-se na sombra das tuas asas.

[[v19-36-8]]

^<<v19-36-8,8>>^ Saciam-se da fartura^&#42;1^ da tua casa,
E tu fazes com que bebam da torrente das tuas delícias.

[NOTE]
====
. Lit.: “gordura”.
====

[[v19-36-9]]

^<<v19-36-9,9>>^ Contigo está a fonte da vida;
Graças à tua luz, podemos ver a luz.

[[v19-36-10]]

^<<v19-36-10,10>>^ Continua a mostrar o teu amor leal aos que te conhecem,
E a tua justiça aos retos de coração.

[[v19-36-11]]

^<<v19-36-11,11>>^ Não deixes que os pés dos arrogantes me pisem;
Nem que as mãos dos maus me expulsem.

[[v19-36-12]]

^<<v19-36-12,12>>^ Ali estão os malfeitores, caídos;
Foram derrubados e não se podem levantar.

'''

xref:019-salmo/019-salmo-035.adoc#v19-35-0[&#60; Capítulo Anterior] | <<v19-36-0,Topo>> | xref:019-salmo/019-salmo-037.adoc#v19-37-0[Próximo Capítulo &#62;]