include::./index.adoc[]

[[v19-40-0]]
=== Salmos, 40
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente. Salmo de David._

[[v19-40-1]]

^<<v19-40-1,1>>^ Esperei confiantemente em^&#42;1^ Jeová,
E ele inclinou-me o seu ouvido^&#42;2^ e escutou o meu clamor por ajuda.

[NOTE]
====
. Ou: “Esperei pacientemente por”.
. Ou: “abaixou-se para me ouvir”.
====

[[v19-40-2]]

^<<v19-40-2,2>>^ Ele tirou-me de um poço de águas ruidosas,
Do charco lamacento,
E pôs os meus pés sobre um rochedo;
Deu firmeza aos meus passos.

[[v19-40-3]]

^<<v19-40-3,3>>^ Então, pôs na minha boca um novo cântico,
Um louvor ao nosso Deus.
Muitos observarão admirados
E porão a sua confiança em Jeová.

[[v19-40-4]]

^<<v19-40-4,4>>^ Feliz o homem que confia em Jeová
E não recorre aos insolentes nem aos falsos.^&#42;1^

[NOTE]
====
. Ou: “mentirosos”.
====

[[v19-40-5]]

^<<v19-40-5,5>>^ Quantas coisas fizeste,
Ó Jeová, meu Deus,
Muitos são os teus atos maravilhosos e os teus pensamentos a nosso favor.
Não há quem se compare a ti.
Se eu fosse narrá-los e falar deles,
Seriam demasiados para relatar!

[[v19-40-6]]

^<<v19-40-6,6>>^ Não desejaste^&#42;1^ sacrifícios e ofertas,
Mas abriste os meus ouvidos para eu escutar.
Não pediste ofertas queimadas nem ofertas pelo pecado.

[NOTE]
====
. Ou: “Não te agradaste de”.
====

[[v19-40-7]]

^<<v19-40-7,7>>^ Então, eu disse: “Aqui estou.^&#42;1^
No rolo^&#42;2^ está escrito a meu respeito.

[NOTE]
====
. Lit.: “Eis que eu vim.”
. Lit.: “rolo do livro”.
====

[[v19-40-8]]

^<<v19-40-8,8>>^ Fazer a tua vontade, ó meu Deus, é o meu prazer,^&#42;1^
E a tua lei está no meu íntimo.

[NOTE]
====
. Ou: “desejo”.
====

[[v19-40-9]]

^<<v19-40-9,9>>^ Proclamo as boas novas de justiça na grande congregação.
Não refreio os meus lábios,
Ó Jeová, como tu sabes muito bem.

[[v19-40-10]]

^<<v19-40-10,10>>^ Não escondo dentro do meu coração a tua justiça.
Declaro a tua fidelidade e a tua salvação.
Não oculto o teu amor leal e a tua verdade na grande congregação.”

[[v19-40-11]]

^<<v19-40-11,11>>^ Ó Jeová, não me negues a tua misericórdia.
Que o teu amor leal e a tua verdade me protejam sempre.

[[v19-40-12]]

^<<v19-40-12,12>>^ As calamidades que me cercam são demasiadas para serem contadas.
São tantos os meus erros que me esmagam que nem consigo ver o meu caminho;
São mais numerosos do que os cabelos da minha cabeça.
E eu fiquei desanimado.

[[v19-40-13]]

^<<v19-40-13,13>>^ Por favor, ó Jeová, agrada-te em salvar-me.
Ó Jeová, vem depressa ajudar-me.

[[v19-40-14]]

^<<v19-40-14,14>>^ Que todos os que querem tirar-me a vida^&#42;1^
Sejam envergonhados e desonrados.
Que os que têm prazer na minha calamidade
Batam em retirada, humilhados.

[NOTE]
====
. Ou: “procuram a minha alma”.
====

[[v19-40-15]]

^<<v19-40-15,15>>^ Que os que gozam comigo, dizendo: “Ah! Ah!”
Fiquem chocados por causa da sua própria vergonha.

[[v19-40-16]]

^<<v19-40-16,16>>^ Mas que aqueles que te procuram
Exultem e se alegrem em ti.
Que os que amam os teus atos de salvação digam sempre:
“Magnificado seja Jeová.”

[[v19-40-17]]

^<<v19-40-17,17>>^ Mas eu estou desamparado e pobre.
Que Jeová me preste atenção.
Tu és o meu ajudador e o meu libertador;
Ó meu Deus, não demores.

'''

xref:019-salmo/019-salmo-039.adoc#v19-39-0[&#60; Capítulo Anterior] | <<v19-40-0,Topo>> | xref:019-salmo/019-salmo-041.adoc#v19-41-0[Próximo Capítulo &#62;]