include::./index.adoc[]

[[v19-13-0]]
=== Salmos, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente. Salmo de David._

[[v19-13-1]]

^<<v19-13-1,1>>^ Ó Jeová, até quando é que te esquecerás de mim? Para sempre?
Até quando é que esconderás de mim a tua face?

[[v19-13-2]]

^<<v19-13-2,2>>^ Até quando terei^&#42;1^ ansiedades e preocupações,
Tristeza no meu coração todos os dias?
Até quando é que o meu inimigo triunfará sobre mim?

[NOTE]
====
. Ou: “a minha alma terá”.
====

[[v19-13-3]]

^<<v19-13-3,3>>^ Olha para mim e responde-me, ó Jeová, meu Deus.
Ilumina os meus olhos, para que eu não adormeça na morte,

[[v19-13-4]]

^<<v19-13-4,4>>^ Para que o meu inimigo não diga: “Derrotei-o!”
Não permitas que os meus opositores se alegrem com a minha queda.

[[v19-13-5]]

^<<v19-13-5,5>>^ Eu, porém, confio no teu amor leal;
O meu coração vai alegrar-se com os teus atos de salvação.

[[v19-13-6]]

^<<v19-13-6,6>>^ Vou cantar a Jeová, pois ele recompensa-me ricamente.^&#42;1^

[NOTE]
====
. Ou: “ele lida comigo de modo recompensador”.
====

'''

xref:019-salmo/019-salmo-012.adoc#v19-12-0[&#60; Capítulo Anterior] | <<v19-13-0,Topo>> | xref:019-salmo/019-salmo-014.adoc#v19-14-0[Próximo Capítulo &#62;]