include::./index.adoc[]

[[v19-143-0]]
=== Salmos, 143
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Salmo de David._

[[v19-143-1]]

^<<v19-143-1,1>>^ Ó Jeová, escuta a minha oração,
Ouve a minha súplica por ajuda.
Responde-me segundo a tua fidelidade e a tua justiça.

[[v19-143-2]]

^<<v19-143-2,2>>^ Não entres em juízo com o teu servo,
Pois ninguém que esteja vivo pode ser justo diante de ti.

[[v19-143-3]]

^<<v19-143-3,3>>^ Porque o inimigo persegue-me,^&#42;1^
Esmagou-me a vida contra o chão.
Obrigou-me a morar na escuridão, como os que já morreram há muito tempo.

[NOTE]
====
. Ou: “persegue a minha alma”.
====

[[v19-143-4]]

^<<v19-143-4,4>>^ O meu espírito^&#42;1^ está a desfalecer;
O meu coração está entorpecido dentro de mim.

[NOTE]
====
. Ou: “A minha força”.
====

[[v19-143-5]]

^<<v19-143-5,5>>^ Lembro-me dos tempos antigos;
Medito em todos os teus atos;
Reflito no^&#42;1^ trabalho das tuas mãos com vivo interesse.

[NOTE]
====
. Ou: “Estudo o”.
====

[[v19-143-6]]

^<<v19-143-6,6>>^ Estendo as minhas mãos para ti;
Sou^&#42;1^ como uma terra ressequida, sedenta de ti. (Selá)

[NOTE]
====
. Ou: “A minha alma é”.
====

[[v19-143-7]]

^<<v19-143-7,7>>^ Responde-me depressa, ó Jeová;
As minhas forças chegaram^&#42;1^ ao fim.
Não me escondas a tua face,
Senão eu serei como os que descem à cova.^&#42;2^

[NOTE]
====
. Lit.: “O meu espírito chegou”.
. Ou: “sepultura”.
====

[[v19-143-8]]

^<<v19-143-8,8>>^ Faz-me ouvir o teu amor leal pela manhã,
Pois confio em ti.
Faz-me saber o caminho em que devo andar,
Pois é a ti que recorro.^&#42;1^

[NOTE]
====
. Ou: “Pois elevo-te a minha alma”.
====

[[v19-143-9]]

^<<v19-143-9,9>>^ Livra-me dos meus inimigos, ó Jeová.
Eu procuro a tua proteção.

[[v19-143-10]]

^<<v19-143-10,10>>^ Ensina-me a fazer a tua vontade,
Porque tu és o meu Deus.
O teu espírito é bom;
Que ele me guie em terreno plano.^&#42;1^

[NOTE]
====
. Ou: “na terra da retidão”.
====

[[v19-143-11]]

^<<v19-143-11,11>>^ Por causa do teu nome, ó Jeová, preserva-me vivo.
Na tua justiça, livra-me^&#42;1^ da aflição.

[NOTE]
====
. Ou: “livra a minha alma”.
====

[[v19-143-12]]

^<<v19-143-12,12>>^ No teu amor leal, põe fim aos^&#42;1^ meus inimigos;
Destrói todos os que me hostilizam,^&#42;2^
Porque sou teu servo.

[NOTE]
====
. Lit.: “silencia os”.
. Ou: “hostilizam a minha alma”.
====

'''

xref:019-salmo/019-salmo-142.adoc#v19-142-0[&#60; Capítulo Anterior] | <<v19-143-0,Topo>> | xref:019-salmo/019-salmo-144.adoc#v19-144-0[Próximo Capítulo &#62;]