include::./index.adoc[]

[[v19-66-0]]
=== Salmos, 66
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente. Cântico. Salmo._

[[v19-66-1]]

^<<v19-66-1,1>>^ Aclamem triunfantemente a Deus, toda a terra.

[[v19-66-2]]

^<<v19-66-2,2>>^ Cantem louvores^&#42;1^ ao seu nome glorioso.
Deem-lhe glória e louvor.

[NOTE]
====
. Ou: “Façam música”.
====

[[v19-66-3]]

^<<v19-66-3,3>>^ Digam a Deus: “Como são espantosas as tuas obras!
Por causa do teu grande poder,
Os teus inimigos irão encolher-se de temor diante de ti.

[[v19-66-4]]

^<<v19-66-4,4>>^ Toda a terra irá curvar-se diante de ti;
Irão cantar-te louvores;
Cantarão louvores ao teu nome.” (Selá)

[[v19-66-5]]

^<<v19-66-5,5>>^ Venham e vejam as obras de Deus.
Os seus atos a favor dos filhos dos homens inspiram temor.

[[v19-66-6]]

^<<v19-66-6,6>>^ Ele transformou o mar em terra seca;
Eles atravessaram o rio a pé.
Ali, alegrámo-nos nele.

[[v19-66-7]]

^<<v19-66-7,7>>^ Ele governa para sempre com o seu poder.
Os seus olhos vigiam as nações.
Que os obstinados não se exaltem a si mesmos. (Selá)

[[v19-66-8]]

^<<v19-66-8,8>>^ Louvem o nosso Deus, ó povos,
Que seja ouvido o som do seu louvor.

[[v19-66-9]]

^<<v19-66-9,9>>^ Ele preserva-nos vivos;^&#42;1^
Ele não permite que o nosso pé tropece.^&#42;2^

[NOTE]
====
. Ou: “põe a nossa alma em vida”.
. Ou: “cambaleie”.
====

[[v19-66-10]]

^<<v19-66-10,10>>^ Pois examinaste-nos, ó Deus;
Refinaste-nos assim como se refina a prata.

[[v19-66-11]]

^<<v19-66-11,11>>^ Fizeste-nos entrar numa rede de caça;
Puseste sobre nós^&#42;1^ um fardo esmagador.

[NOTE]
====
. Lit.: “sobre as nossas ancas”.
====

[[v19-66-12]]

^<<v19-66-12,12>>^ Deixaste o homem mortal cavalgar sobre nós;^&#42;1^
Passámos pelo fogo e pela água;
Então, tu trouxeste-nos a um lugar de descanso.

[NOTE]
====
. Lit.: “a nossa cabeça”.
====

[[v19-66-13]]

^<<v19-66-13,13>>^ Entrarei na tua casa com ofertas queimadas,
Cumprirei os votos que te fiz,

[[v19-66-14]]

^<<v19-66-14,14>>^ Aquilo que os meus lábios prometeram,
Que a minha boca disse quando eu estava em aflição.

[[v19-66-15]]

^<<v19-66-15,15>>^ Vou fazer-te ofertas queimadas de animais gordos,
Com o fumo sacrificial de carneiros.
Oferecerei touros e bodes. (Selá)

[[v19-66-16]]

^<<v19-66-16,16>>^ Venham e ouçam, todos vocês, os que temem a Deus,
E eu vou contar-vos o que ele tem feito por mim.^&#42;1^

[NOTE]
====
. Ou: “pela minha alma”.
====

[[v19-66-17]]

^<<v19-66-17,17>>^ Invoquei-o com a minha boca
E glorifiquei-o com a minha língua.

[[v19-66-18]]

^<<v19-66-18,18>>^ Se eu tivesse guardado alguma maldade no coração,
Jeová não me teria ouvido.

[[v19-66-19]]

^<<v19-66-19,19>>^ Mas Deus realmente ouviu,
Prestou atenção à minha oração.

[[v19-66-20]]

^<<v19-66-20,20>>^ Louvado seja Deus, que não rejeitou a minha oração
Nem me negou o seu amor leal.

'''

xref:019-salmo/019-salmo-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-salmo/019-salmo-067.adoc#v19-67-0[Próximo Capítulo &#62;]