include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-115-1]]

^<<v19-115-1,1>>^ Não a nós, ó Jeová, não a nós,^&#42;1^
Mas ao teu nome, dá glória,
Por causa do teu amor leal e da tua fidelidade.

[NOTE]
====
. Ou: “Nada nos pertence, ó Jeová, nada nos pertence”.
====

[[v19-115-2]]

^<<v19-115-2,2>>^ Porque é que as nações haveriam de dizer:
“Onde está o Deus deles?”

[[v19-115-3]]

^<<v19-115-3,3>>^ O nosso Deus está nos céus;
Ele faz tudo o que lhe agrada.

[[v19-115-4]]

^<<v19-115-4,4>>^ Os ídolos deles são prata e ouro,
Trabalho de mãos humanas.

[[v19-115-5]]

^<<v19-115-5,5>>^ Têm boca, mas não podem falar;
Olhos, mas não podem ver.

[[v19-115-6]]

^<<v19-115-6,6>>^ Têm orelhas, mas não podem ouvir;
Nariz, mas não podem cheirar.

[[v19-115-7]]

^<<v19-115-7,7>>^ Têm mãos, mas não podem apalpar;
Pés, mas não podem andar.
Não fazem nenhum som com a garganta.

[[v19-115-8]]

^<<v19-115-8,8>>^ As pessoas que os fazem ficarão iguais a eles,
Assim como todos os que neles confiam.

[[v19-115-9]]

^<<v19-115-9,9>>^ Ó Israel, confia em Jeová:
Ele é a tua ajuda e o teu escudo.

[[v19-115-10]]

^<<v19-115-10,10>>^ Ó casa de Arão, confia em Jeová:
Ele é a tua ajuda e o teu escudo.

[[v19-115-11]]

^<<v19-115-11,11>>^ Vocês, os que temem a Jeová, confiem em Jeová:
Ele é a vossa ajuda e o vosso escudo.

[[v19-115-12]]

^<<v19-115-12,12>>^ Jeová lembra-se de nós e abençoará:
Abençoará a casa de Israel;
Abençoará a casa de Arão.

[[v19-115-13]]

^<<v19-115-13,13>>^ Abençoará os que temem a Jeová,
Os pequenos e os grandes.

[[v19-115-14]]

^<<v19-115-14,14>>^ Jeová fará com que se tornem muitos,
Vocês e os vossos filhos.

[[v19-115-15]]

^<<v19-115-15,15>>^ Que sejam abençoados por Jeová,
Aquele que fez o céu e a terra.

[[v19-115-16]]

^<<v19-115-16,16>>^ Quanto aos céus, eles pertencem a Jeová,
Mas a terra ele deu aos filhos dos homens.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos não louvam a Jah;
Nem os que descem ao silêncio da morte.^&#42;1^

[NOTE]
====
. Lit.: “ao silêncio”.
====

[[v19-115-18]]

^<<v19-115-18,18>>^ Nós, porém, louvaremos a Jah
Agora e para sempre.
Louvem a Jah!^&#42;1^

[NOTE]
====
. Ou: “Aleluia!” “Jah” é uma forma reduzida do nome Jeová.
====

'''

xref:019-salmo/019-salmo-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmo/019-salmo-116.adoc#v19-116-0[Próximo Capítulo &#62;]