include::./index.adoc[]

[[v19-132-0]]
=== Salmos, 132
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Cântico das Subidas._

[[v19-132-1]]

^<<v19-132-1,1>>^ Ó Jeová, lembra-te de David
E de todo o seu sofrimento,

[[v19-132-2]]

^<<v19-132-2,2>>^ De como ele jurou a Jeová
E fez um voto ao Poderoso de Jacó:

[[v19-132-3]]

^<<v19-132-3,3>>^ “Não entrarei na minha tenda, na minha casa.
Não me deitarei no meu leito, na minha cama;

[[v19-132-4]]

^<<v19-132-4,4>>^ Não deixarei os meus olhos dormirem
Nem as minhas pálpebras descansarem,

[[v19-132-5]]

^<<v19-132-5,5>>^ Até que eu encontre um lugar para Jeová,
Uma morada excelente^&#42;1^ para o Poderoso de Jacó.”

[NOTE]
====
. Ou: “Um grandioso tabernáculo”.
====

[[v19-132-6]]

^<<v19-132-6,6>>^ Ouvimos falar dela^&#42;1^ em Efrata;
Encontrámo-la na região da floresta.^&#42;2^

[NOTE]
====
. Aparentemente, refere-se à Arca.
. Ou: “nos campos da floresta”.
====

[[v19-132-7]]

^<<v19-132-7,7>>^ Entremos na sua morada;^&#42;1^
Curvemo-nos diante do apoio para os seus pés.

[NOTE]
====
. Ou: “no grandioso tabernáculo”.
====

[[v19-132-8]]

^<<v19-132-8,8>>^ Levanta-te, ó Jeová, e vem para o teu lugar de descanso,
Tu e a Arca do teu poder.

[[v19-132-9]]

^<<v19-132-9,9>>^ Que os teus sacerdotes se vistam de justiça,
E que os teus leais gritem de alegria.

[[v19-132-10]]

^<<v19-132-10,10>>^ Por causa de David, teu servo,
Não rejeites o^&#42;1^ teu ungido.

[NOTE]
====
. Lit.: “Não voltes para trás a face do”.
====

[[v19-132-11]]

^<<v19-132-11,11>>^ Jeová jurou a David;
Ele certamente não voltará atrás na sua palavra:
“Porei no teu trono
Um dos teus descendentes.^&#42;1^

[NOTE]
====
. Lit.: “do fruto do teu ventre”.
====

[[v19-132-12]]

^<<v19-132-12,12>>^ Se os teus filhos guardarem o meu pacto
E acatarem as advertências^&#42;1^ que lhes ensino,
Os filhos deles também
Se sentarão no teu trono para sempre.”

[NOTE]
====
. Ou: “os preceitos”.
====

[[v19-132-13]]

^<<v19-132-13,13>>^ Pois Jeová escolheu Sião,
Ele desejou-a como sua morada, e disse:

[[v19-132-14]]

^<<v19-132-14,14>>^ “Este é o meu lugar de descanso para sempre;
Aqui habitarei, pois este é o meu desejo.

[[v19-132-15]]

^<<v19-132-15,15>>^ Vou abençoá-la grandemente com provisões;
Fartarei de pão os seus pobres.

[[v19-132-16]]

^<<v19-132-16,16>>^ Vestirei os seus sacerdotes de salvação;
E os seus leais gritarão de alegria.

[[v19-132-17]]

^<<v19-132-17,17>>^ Ali farei crescer o poder^&#42;1^ de David.
Preparei uma lâmpada para o meu ungido.

[NOTE]
====
. Lit.: “chifre”.
====

[[v19-132-18]]

^<<v19-132-18,18>>^ Vestirei de vergonha os inimigos dele;
Mas, na sua cabeça, a coroa^&#42;1^ florescerá.”

[NOTE]
====
. Ou: “o diadema”.
====

'''

xref:019-salmo/019-salmo-131.adoc#v19-131-0[&#60; Capítulo Anterior] | <<v19-132-0,Topo>> | xref:019-salmo/019-salmo-133.adoc#v19-133-0[Próximo Capítulo &#62;]