include::./index.adoc[]

[[v19-137-0]]
=== Salmos, 137
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-137-1]]

^<<v19-137-1,1>>^ Sentados junto aos rios de Babilónia,
Chorámos quando nos lembrámos de Sião.

[[v19-137-2]]

^<<v19-137-2,2>>^ Nos choupos que lá^&#42;1^ havia,
Pendurámos as nossas harpas.

[NOTE]
====
. Isto é, em Babilónia.
====

[[v19-137-3]]

^<<v19-137-3,3>>^ Pois ali os nossos captores pediram-nos uma canção;
Os que gozavam connosco queriam que os divertíssemos:
“Cantem-nos uma das canções de Sião.”

[[v19-137-4]]

^<<v19-137-4,4>>^ Como é que podemos cantar a canção de Jeová
Em solo estrangeiro?

[[v19-137-5]]

^<<v19-137-5,5>>^ Se eu me esquecer de ti, ó Jerusalém,
Que a minha mão direita se esqueça da sua destreza.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “se seque”.
====

[[v19-137-6]]

^<<v19-137-6,6>>^ Que a minha língua se pegue ao céu da boca
Se eu não me lembrar de ti,
Se eu não puser Jerusalém
Acima dos meus maiores motivos de alegria.

[[v19-137-7]]

^<<v19-137-7,7>>^ Lembra-te, ó Jeová,
Do que os edomitas disseram no dia em que Jerusalém caiu:
“Arrasem-na! Arrasem-na até aos seus alicerces!”

[[v19-137-8]]

^<<v19-137-8,8>>^ Ó filha de Babilónia, que em breve será devastada,
Feliz é aquele que te retribuir
Com o mesmo tratamento com que tu nos trataste.

[[v19-137-9]]

^<<v19-137-9,9>>^ Feliz será aquele que agarrar os teus filhos
E os despedaçar contra as rochas.

'''

xref:019-salmo/019-salmo-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-salmo/019-salmo-138.adoc#v19-138-0[Próximo Capítulo &#62;]