include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_De David._

_א &#91;álefe&#93;_

[[v19-25-1]]

^<<v19-25-1,1>>^ A ti, ó Jeová, eu recorro.^&#42;1^

[NOTE]
====
. Ou: “elevo a minha alma”.
====

_ב &#91;bete&#93;_

[[v19-25-2]]

^<<v19-25-2,2>>^ Meu Deus, confio em ti;
Não permitas que eu seja envergonhado.
Não permitas que os meus inimigos se alegrem às minhas custas.

_ג &#91;guímel&#93;_

[[v19-25-3]]

^<<v19-25-3,3>>^ Certamente, ninguém que espera em ti será envergonhado;
Envergonhados serão aqueles que, sem motivo, agem traiçoeiramente.

_ד &#91;dálete&#93;_

[[v19-25-4]]

^<<v19-25-4,4>>^ Faz-me saber os teus caminhos, ó Jeová;
Ensina-me as tuas veredas.

_ה &#91;hê&#93;_

[[v19-25-5]]

^<<v19-25-5,5>>^ Faz-me andar na tua verdade e ensina-me,
Pois tu és o Deus da minha salvação.

_ו &#91;vau&#93;_

Espero em ti o dia inteiro.

_ז &#91;zaine&#93;_

[[v19-25-6]]

^<<v19-25-6,6>>^ Lembra-te da tua misericórdia, ó Jeová, e do teu amor leal,
Os quais sempre tens demonstrado.^&#42;1^

[NOTE]
====
. Ou: “Que são desde os tempos antigos”.
====

_ח &#91;hete&#93;_

[[v19-25-7]]

^<<v19-25-7,7>>^ Não te lembres dos pecados da minha juventude e das minhas transgressões.
Lembra-te de mim de acordo com o teu amor leal,
Por causa da tua bondade, ó Jeová.

_ט &#91;tete&#93;_

[[v19-25-8]]

^<<v19-25-8,8>>^ Bom e reto é Jeová.
É por isso que ele instrui os pecadores no caminho a seguir.

_י &#91;iode&#93;_

[[v19-25-9]]

^<<v19-25-9,9>>^ Guiará os mansos no que é certo,^&#42;1^
E ensinará aos mansos o Seu caminho.

[NOTE]
====
. Lit.: “em julgamento”.
====

_כ &#91;cafe&#93;_

[[v19-25-10]]

^<<v19-25-10,10>>^ Todas as veredas de Jeová são amor leal e fidelidade
Para os que guardam o seu pacto e as suas advertências.^&#42;1^

[NOTE]
====
. “Advertência” refere-se a um lembrete do que é necessário fazer.
====

_ל &#91;lâmede&#93;_

[[v19-25-11]]

^<<v19-25-11,11>>^ Por causa do teu nome, ó Jeová,
Perdoa o meu erro, embora ele seja grande.

_מ &#91;meme&#93;_

[[v19-25-12]]

^<<v19-25-12,12>>^ Quem é o homem que teme a Jeová?
Ele vai instruí-lo acerca do caminho que deve escolher.

_נ &#91;nune&#93;_

[[v19-25-13]]

^<<v19-25-13,13>>^ Ele^&#42;1^ experimentará coisas boas,
E os seus descendentes tomarão^&#42;2^ posse da terra.

[NOTE]
====
. Ou: “A sua alma”.
. Lit.: “a sua semente tomará”.
====

_ס &#91;sâmeque&#93;_

[[v19-25-14]]

^<<v19-25-14,14>>^ A amizade íntima com Jeová pertence aos que o temem,
E ele dá-lhes a conhecer o seu pacto.

_ע &#91;aine&#93;_

[[v19-25-15]]

^<<v19-25-15,15>>^ Os meus olhos estão sempre voltados para Jeová,
Pois ele libertará os meus pés da rede.

_פ &#91;pê&#93;_

[[v19-25-16]]

^<<v19-25-16,16>>^ Volta a tua face para mim e mostra-me favor,
Pois estou sozinho e desamparado.

_צ &#91;tsadê&#93;_

[[v19-25-17]]

^<<v19-25-17,17>>^ As aflições do meu coração multiplicaram-se;
Liberta-me da minha angústia.

_ר &#91;rexe&#93;_

[[v19-25-18]]

^<<v19-25-18,18>>^ Vê a minha aflição e o meu sofrimento,
E perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Vê como são numerosos os meus inimigos
E como é grande o seu ódio por mim.

_ש &#91;chim&#93;_

[[v19-25-20]]

^<<v19-25-20,20>>^ Guarda a minha vida^&#42;1^ e salva-me.
Não permitas que eu seja envergonhado, pois tenho-me refugiado em ti.

[NOTE]
====
. Ou: “alma”.
====

_ת &#91;tau&#93;_

[[v19-25-21]]

^<<v19-25-21,21>>^ Que a integridade e a retidão me protejam,
Pois a minha esperança está em ti.

[[v19-25-22]]

^<<v19-25-22,22>>^ Ó Deus, livra^&#42;1^ Israel de todas as suas aflições.

[NOTE]
====
. Lit.: “resgata”.
====

'''

xref:019-salmo/019-salmo-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmo/019-salmo-026.adoc#v19-26-0[Próximo Capítulo &#62;]