include::./index.adoc[]

[[v19-21-0]]
=== Salmos, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente. Salmo de David._

[[v19-21-1]]

^<<v19-21-1,1>>^ Ó Jeová, o rei alegra-se na tua força;
Como é grande a sua alegria nos teus atos de salvação!

[[v19-21-2]]

^<<v19-21-2,2>>^ Concedeste-lhe o desejo do seu coração
E não negaste o pedido dos seus lábios. (Selá)

[[v19-21-3]]

^<<v19-21-3,3>>^ Pois vais ao seu encontro com ricas bênçãos;
Colocas na sua cabeça uma coroa de ouro fino.^&#42;1^

[NOTE]
====
. Ou: “refinado”.
====

[[v19-21-4]]

^<<v19-21-4,4>>^ Ele pediu-te vida, e vida lhe deste,
Uma vida longa,^&#42;1^ eterna, sem fim.

[NOTE]
====
. Lit.: “Longura de dias”.
====

[[v19-21-5]]

^<<v19-21-5,5>>^ Os teus atos de salvação trazem-lhe grande glória.
Tu conferes-lhe honra e esplendor.

[[v19-21-6]]

^<<v19-21-6,6>>^ Tu fazes com que ele seja abençoado para sempre
E que se encha de alegria com a tua presença.^&#42;1^

[NOTE]
====
. Lit.: “face”.
====

[[v19-21-7]]

^<<v19-21-7,7>>^ Pois o rei confia em Jeová;
Por causa do amor leal do Altíssimo, nunca será abalado.^&#42;1^

[NOTE]
====
. Ou: “nunca cambaleará”.
====

[[v19-21-8]]

^<<v19-21-8,8>>^ A tua mão encontrará todos os teus inimigos;
A tua mão direita encontrará os que te odeiam.

[[v19-21-9]]

^<<v19-21-9,9>>^ Farás deles uma fornalha ardente no dia^&#42;1^ em que voltares a atenção para eles.
Jeová vai engoli-los na sua ira, e um fogo há de consumi-los.

[NOTE]
====
. Ou: “tempo determinado”.
====

[[v19-21-10]]

^<<v19-21-10,10>>^ Eliminarás da terra os seus descendentes,^&#42;1^
E dentre os filhos dos homens a sua posteridade.

[NOTE]
====
. Lit.: “o seu fruto”.
====

[[v19-21-11]]

^<<v19-21-11,11>>^ Pois pensaram em fazer o que é mau contra ti;
Fizeram planos que não terão sucesso.

[[v19-21-12]]

^<<v19-21-12,12>>^ Porque tu os farás bater em retirada,
Quando lhes^&#42;1^ apontares o teu arco.^&#42;2^

[NOTE]
====
. Lit.: “às faces deles”.
. Lit.: “as tuas cordas de arco”.
====

[[v19-21-13]]

^<<v19-21-13,13>>^ Ó Jeová, levanta-te na tua força.
Cantaremos louvores^&#42;1^ ao teu poder.

[NOTE]
====
. Lit.: “Cantaremos e faremos música”.
====

'''

xref:019-salmo/019-salmo-020.adoc#v19-20-0[&#60; Capítulo Anterior] | <<v19-21-0,Topo>> | xref:019-salmo/019-salmo-022.adoc#v19-22-0[Próximo Capítulo &#62;]