include::./index.adoc[]

[[v19-89-0]]
=== Salmos, 89
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Masquil.^&#42;1^ De Etã, o ezraíta._

[[v19-89-1]]

^<<v19-89-1,1>>^ Cantarei para sempre sobre o amor leal de Jeová.
Com a minha boca, tornarei conhecida a tua fidelidade a todas as gerações.

[[v19-89-2]]

^<<v19-89-2,2>>^ Sim, eu disse: “O amor leal ficará edificado^&#42;1^ para sempre,
E tu estabeleceste firmemente nos céus a tua fidelidade.”

[NOTE]
====
. Ou: “durará”.
====

[[v19-89-3]]

^<<v19-89-3,3>>^ “Fiz um pacto com o meu escolhido;
Jurei a David, meu servo:

[[v19-89-4]]

^<<v19-89-4,4>>^ ‘Estabelecerei firmemente a tua descendência^&#42;1^ para sempre,
E vou edificar o teu trono por todas as gerações.’” (Selá)

[NOTE]
====
. Lit.: “semente”.
====

[[v19-89-5]]

^<<v19-89-5,5>>^ Os céus louvam as tuas maravilhas, ó Jeová,
Sim, a tua fidelidade na congregação dos santos.

[[v19-89-6]]

^<<v19-89-6,6>>^ Pois quem nos céus pode ser comparado a Jeová?
Quem entre os filhos de Deus é semelhante a Jeová?

[[v19-89-7]]

^<<v19-89-7,7>>^ Deus é reverenciado na assembleia^&#42;1^ dos santos;
Ele é grandioso e inspira temor em todos os que estão à sua volta.

[NOTE]
====
. Ou: “no conselho”.
====

[[v19-89-8]]

^<<v19-89-8,8>>^ Ó Jeová, Deus dos exércitos,
Quem é poderoso como tu, ó Jah?
A tua fidelidade está ao teu redor.

[[v19-89-9]]

^<<v19-89-9,9>>^ Tu dominas sobre a fúria do mar;
Tu acalmas as suas ondas, quando elas se levantam.

[[v19-89-10]]

^<<v19-89-10,10>>^ Tu esmagaste Raabe, sim, deixaste-a como morta.
Com o teu braço forte espalhaste os teus inimigos.

[[v19-89-11]]

^<<v19-89-11,11>>^ Os céus são teus, e a terra é tua;
A terra produtiva e tudo o que nela há — foste tu que os formaste.

[[v19-89-12]]

^<<v19-89-12,12>>^ O norte e o sul — foste tu que os criaste;
O Tabor e o Hermom louvam alegremente o teu nome.

[[v19-89-13]]

^<<v19-89-13,13>>^ O teu braço é poderoso;
A tua mão é forte;
A tua mão direita é enaltecida.

[[v19-89-14]]

^<<v19-89-14,14>>^ A retidão e a justiça são a base do teu trono;
O amor leal e a fidelidade estão diante de ti.

[[v19-89-15]]

^<<v19-89-15,15>>^ Feliz o povo que sabe o que é gritar de alegria.
Ó Jeová, eles andam na luz da tua face.

[[v19-89-16]]

^<<v19-89-16,16>>^ Alegram-se no teu nome o dia inteiro,
E pela tua justiça são enaltecidos.

[[v19-89-17]]

^<<v19-89-17,17>>^ Pois tu és a glória da sua força,
E com o teu favor o nosso poder^&#42;1^ aumenta.

[NOTE]
====
. Lit.: “chifre”.
====

[[v19-89-18]]

^<<v19-89-18,18>>^ Pois o nosso escudo pertence a Jeová,
O nosso rei pertence ao Santo de Israel.

[[v19-89-19]]

^<<v19-89-19,19>>^ Naquela ocasião, falaste numa visão aos teus leais, e disseste:
“Dei força a um valente guerreiro;
Enalteci aquele que escolhi dentre o povo.

[[v19-89-20]]

^<<v19-89-20,20>>^ Encontrei David, o meu servo;
Ungi-o com o meu óleo sagrado.

[[v19-89-21]]

^<<v19-89-21,21>>^ A minha mão vai sustentá-lo,
E o meu braço vai fortalecê-lo.

[[v19-89-22]]

^<<v19-89-22,22>>^ Nenhum inimigo o obrigará a pagar tributo;
E nenhum homem injusto o oprimirá.

[[v19-89-23]]

^<<v19-89-23,23>>^ Despedaçarei os seus adversários diante dele
E matarei os que o odeiam.

[[v19-89-24]]

^<<v19-89-24,24>>^ A minha fidelidade e o meu amor leal estão com ele,
E o seu poder^&#42;1^ aumentará por meio do meu nome.

[NOTE]
====
. Lit.: “chifre”.
====

[[v19-89-25]]

^<<v19-89-25,25>>^ Colocarei a sua mão^&#42;1^ sobre o mar
E a sua mão direita sobre os rios.

[NOTE]
====
. Ou: “autoridade”.
====

[[v19-89-26]]

^<<v19-89-26,26>>^ Ele há de chamar-me, dizendo: ‘Tu és o meu Pai,
O meu Deus e a Rocha da minha salvação.’

[[v19-89-27]]

^<<v19-89-27,27>>^ E eu farei dele o primogénito,
O maior dos reis da terra.

[[v19-89-28]]

^<<v19-89-28,28>>^ Manterei para sempre o meu amor leal por ele,
E o pacto que fiz com ele nunca acabará.

[[v19-89-29]]

^<<v19-89-29,29>>^ Estabelecerei a sua descendência^&#42;1^ para sempre
E farei o seu trono tão duradouro como os céus.

[NOTE]
====
. Lit.: “semente”.
====

[[v19-89-30]]

^<<v19-89-30,30>>^ Se os seus filhos abandonarem a minha lei
E não andarem em harmonia com as minhas decisões judiciais,^&#42;1^

[NOTE]
====
. Ou: “os meus julgamentos”.
====

[[v19-89-31]]

^<<v19-89-31,31>>^ Se violarem os meus decretos
E não guardarem os meus mandamentos,

[[v19-89-32]]

^<<v19-89-32,32>>^ Então, punirei a sua desobediência^&#42;1^ com uma vara,
E o seu erro com açoites.

[NOTE]
====
. Ou: “rebelião”.
====

[[v19-89-33]]

^<<v19-89-33,33>>^ Mas nunca abandonarei o meu amor leal por ele
Nem serei desleal à minha promessa.^&#42;1^

[NOTE]
====
. Lit.: “Nem serei falso para com a minha fidelidade”.
====

[[v19-89-34]]

^<<v19-89-34,34>>^ Não violarei o meu pacto
Nem mudarei o que os meus lábios disseram.

[[v19-89-35]]

^<<v19-89-35,35>>^ Na minha santidade, jurei de uma vez para sempre;
Não vou mentir a David.

[[v19-89-36]]

^<<v19-89-36,36>>^ A sua descendência^&#42;1^ permanecerá para sempre;
O seu trono durará como o sol diante de mim.

[NOTE]
====
. Lit.: “semente”.
====

[[v19-89-37]]

^<<v19-89-37,37>>^ Assim como a lua, será firmemente estabelecido para sempre
Como fiel testemunha nos céus.” (Selá)

[[v19-89-38]]

^<<v19-89-38,38>>^ Mas foste tu mesmo que o abandonaste e rejeitaste;
Ficaste furioso com o teu ungido.

[[v19-89-39]]

^<<v19-89-39,39>>^ Rejeitaste o pacto com o teu servo;
Profanaste a sua coroa, atirando-a^&#42;1^ ao chão.

[NOTE]
====
. Ou: “Profanaste o seu diadema, atirando-o”.
====

[[v19-89-40]]

^<<v19-89-40,40>>^ Derrubaste todos os seus muros^&#42;1^ de pedra,
Reduziste as suas fortificações a ruínas.

[NOTE]
====
. Ou: “os seus abrigos”.
====

[[v19-89-41]]

^<<v19-89-41,41>>^ Todos os que passam saqueiam os seus bens;
Ele é alvo do desprezo dos seus vizinhos.

[[v19-89-42]]

^<<v19-89-42,42>>^ Deste a vitória aos seus adversários;^&#42;1^
Fizeste com que todos os seus inimigos se alegrassem.

[NOTE]
====
. Lit.: “Ergueste a mão direita dos seus adversários”.
====

[[v19-89-43]]

^<<v19-89-43,43>>^ Também fizeste recuar a espada dele
E fizeste com que ele perdesse terreno na batalha.

[[v19-89-44]]

^<<v19-89-44,44>>^ Puseste fim ao seu esplendor
E derrubaste o seu trono por terra.

[[v19-89-45]]

^<<v19-89-45,45>>^ Abreviaste os dias da sua juventude;
Cobriste-o de vergonha. (Selá)

[[v19-89-46]]

^<<v19-89-46,46>>^ Até quando te esconderás, ó Jeová? Será para sempre?
Será que o teu furor vai continuar a arder como um fogo?

[[v19-89-47]]

^<<v19-89-47,47>>^ Lembra-te de como é curta a minha vida!
Será que criaste todos os humanos para nada?

[[v19-89-48]]

^<<v19-89-48,48>>^ Que homem pode viver e nunca ver a morte?
Pode alguém salvar-se^&#42;1^ do poder da Sepultura?^&#42;2^ (Selá)

[NOTE]
====
. Ou: “salvar a sua alma”.
. Lit.: “da mão do Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v19-89-49]]

^<<v19-89-49,49>>^ Onde é que estão os teus antigos atos de amor leal ó Jeová,
Que juraste a David, na tua fidelidade?

[[v19-89-50]]

^<<v19-89-50,50>>^ Lembra-te, ó Jeová, dos insultos lançados contra os teus servos,
De como eu tenho de suportar^&#42;1^ os insultos de todos os povos;

[NOTE]
====
. Lit.: “carregar no meu peito”.
====

[[v19-89-51]]

^<<v19-89-51,51>>^ Lembra-te, ó Jeová, de como os teus inimigos lançaram insultos,
De como insultaram cada passo do teu ungido.

[[v19-89-52]]

^<<v19-89-52,52>>^ Louvado seja Jeová para sempre. Amém e amém.

'''

xref:019-salmo/019-salmo-088.adoc#v19-88-0[&#60; Capítulo Anterior] | <<v19-89-0,Topo>> | xref:019-salmo/019-salmo-090.adoc#v19-90-0[Próximo Capítulo &#62;]