include::./index.adoc[]

[[v19-31-0]]
=== Salmos, 31
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente. Salmo de David._

[[v19-31-1]]

^<<v19-31-1,1>>^ Refugiei-me em ti, ó Jeová.
Que eu nunca seja envergonhado.
Livra-me por causa da tua justiça.

[[v19-31-2]]

^<<v19-31-2,2>>^ Inclina-me o teu ouvido.^&#42;1^
Vem depressa livrar-me.
Torna-te para mim uma fortaleza na montanha,
Um lugar fortificado para me salvar.

[NOTE]
====
. Ou: “Abaixa-te e ouve-me.”
====

[[v19-31-3]]

^<<v19-31-3,3>>^ Pois tu és o meu rochedo e a minha fortaleza;
Por causa do teu nome, tu irás guiar-me e conduzir-me.

[[v19-31-4]]

^<<v19-31-4,4>>^ Tu irás livrar-me da rede que esconderam para me apanhar,
Pois tu és a minha fortaleza.

[[v19-31-5]]

^<<v19-31-5,5>>^ Às tuas mãos confio o meu espírito.
Tu resgataste-me, ó Jeová, Deus da verdade.^&#42;1^

[NOTE]
====
. Ou: “o Deus fiel”.
====

[[v19-31-6]]

^<<v19-31-6,6>>^ Odeio os que se devotam a ídolos vãos, fúteis;
Eu, porém, confio em Jeová.

[[v19-31-7]]

^<<v19-31-7,7>>^ Terei grande alegria com o teu amor leal,
Pois tu vês a minha aflição;
Tu conheces a minha profunda angústia.^&#42;1^

[NOTE]
====
. Ou: “as aflições da minha alma”.
====

[[v19-31-8]]

^<<v19-31-8,8>>^ Não me entregaste nas mãos do inimigo,
Mas colocaste-me num lugar seguro.^&#42;1^

[NOTE]
====
. Ou: “espaçoso”.
====

[[v19-31-9]]

^<<v19-31-9,9>>^ Mostra-me favor, ó Jeová, pois estou em aflição.
A angústia enfraqueceu os meus olhos e também todo o meu corpo.^&#42;1^

[NOTE]
====
. Ou: “também a minha alma e o meu ventre”.
====

[[v19-31-10]]

^<<v19-31-10,10>>^ A minha vida consome-se em tristeza,
E os meus anos em gemidos.
As minhas forças esgotam-se por causa do meu erro;
Os meus ossos ficam fracos.

[[v19-31-11]]

^<<v19-31-11,11>>^ Todos os meus adversários gozam comigo,
Principalmente os meus vizinhos.
E os meus conhecidos têm pavor de mim;
Quando me veem em público, fogem.

[[v19-31-12]]

^<<v19-31-12,12>>^ Eu fui tirado do coração^&#42;1^ deles e fui esquecido, como se estivesse morto;
Sou como um vaso despedaçado.

[NOTE]
====
. Ou: “da mente”.
====

[[v19-31-13]]

^<<v19-31-13,13>>^ Ouvi as coisas más que muitos estão a dizer;
O terror rodeia-me.
Quando se reúnem contra mim,
Tramam tirar-me a vida.^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v19-31-14]]

^<<v19-31-14,14>>^ Eu, porém, confio em ti, ó Jeová.
E declaro: “Tu és o meu Deus.”

[[v19-31-15]]

^<<v19-31-15,15>>^ Os meus dias^&#42;1^ estão nas tuas mãos.
Livra-me das mãos dos meus inimigos e dos que me perseguem.

[NOTE]
====
. Lit.: “tempos”.
====

[[v19-31-16]]

^<<v19-31-16,16>>^ Faz a tua face brilhar sobre o teu servo.
Salva-me através do teu amor leal.

[[v19-31-17]]

^<<v19-31-17,17>>^ Ó Jeová, que eu não seja envergonhado ao invocar-te.
Que os maus sejam envergonhados;
Que sejam silenciados na Sepultura.^&#42;1^

[NOTE]
====
. Ou: “no Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v19-31-18]]

^<<v19-31-18,18>>^ Fiquem mudos os lábios mentirosos,
Lábios que falam contra o justo de modo insolente, com arrogância e desprezo.

[[v19-31-19]]

^<<v19-31-19,19>>^ Como é grande a tua bondade!
Tu reservaste-a para os que te temem,
E demonstraste-a diante de todos os homens, em favor dos que se refugiam em ti.

[[v19-31-20]]

^<<v19-31-20,20>>^ No lugar secreto da tua presença, tu irás escondê-los
Das intrigas dos homens;
No teu abrigo, tu irás protegê-los
De críticas maldosas.^&#42;1^

[NOTE]
====
. Lit.: “Das línguas que discutem”.
====

[[v19-31-21]]

^<<v19-31-21,21>>^ Jeová seja louvado,
Pois, de uma maneira maravilhosa, mostrou-me amor leal numa cidade sitiada.

[[v19-31-22]]

^<<v19-31-22,22>>^ Quanto a mim, entrei em pânico e disse:
“Serei eliminado de diante de ti.”
Mas tu ouviste as minhas súplicas quando clamei a ti por ajuda.

[[v19-31-23]]

^<<v19-31-23,23>>^ Amem a Jeová, todos os que lhe são leais!
Jeová protege os fiéis,
Mas retribui severamente àquele que é arrogante.

[[v19-31-24]]

^<<v19-31-24,24>>^ Sejam corajosos, e que o vosso coração seja forte,
Todos vocês, os que esperam em Jeová.

'''

xref:019-salmo/019-salmo-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-salmo/019-salmo-032.adoc#v19-32-0[Próximo Capítulo &#62;]