include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Salmo de Asafe._

[[v19-50-1]]

^<<v19-50-1,1>>^ O Deus dos deuses, Jeová,^&#42;1^ fala;
Ele convoca a terra
Desde o nascente até ao poente.^&#42;2^

[NOTE]
====
. Ou: “O Divino, Deus, Jeová”.
. Ou: “De leste a oeste”.
====

[[v19-50-2]]

^<<v19-50-2,2>>^ De Sião, a perfeição da beleza, Deus resplandece.

[[v19-50-3]]

^<<v19-50-3,3>>^ O nosso Deus chegará e não ficará calado.
Perante ele, há um fogo devorador,
E, ao seu redor, uma violenta tempestade.

[[v19-50-4]]

^<<v19-50-4,4>>^ Ele convoca os altos céus e a terra,
Pois vai julgar o seu povo:

[[v19-50-5]]

^<<v19-50-5,5>>^ “Reúnam-me os que me são leais,
Os que fazem um pacto comigo por meio de sacrifício.”

[[v19-50-6]]

^<<v19-50-6,6>>^ Os céus proclamam a sua justiça,
Pois o próprio Deus é Juiz. (Selá)

[[v19-50-7]]

^<<v19-50-7,7>>^ “Escuta, ó povo meu, pois vou falar;
Israel, darei testemunho contra ti.
Eu sou Deus, o teu Deus.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não te repreendo por causa dos teus sacrifícios,
Nem por causa das tuas ofertas queimadas que estão constantemente diante de mim.

[[v19-50-9]]

^<<v19-50-9,9>>^ Não preciso de novilhos da tua casa,
Nem de bodes dos teus currais.

[[v19-50-10]]

^<<v19-50-10,10>>^ Pois todos os animais da floresta são meus,
Até mesmo os animais sobre mil montanhas.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço todas as aves dos montes;
Os incontáveis animais do campo são meus.

[[v19-50-12]]

^<<v19-50-12,12>>^ Se eu tivesse fome, não to diria,
Pois meu é o solo produtivo e tudo o que há nele.

[[v19-50-13]]

^<<v19-50-13,13>>^ Será que comerei a carne de touros
Ou beberei o sangue de bodes?

[[v19-50-14]]

^<<v19-50-14,14>>^ Oferece agradecimentos como sacrifício a Deus,
E cumpre os teus votos feitos ao Altíssimo;

[[v19-50-15]]

^<<v19-50-15,15>>^ Invoca-me no dia da aflição.
Eu irei livrar-te e tu irás glorificar-me.”

[[v19-50-16]]

^<<v19-50-16,16>>^ Porém, a quem é mau, Deus dirá:
“Que direito tens tu de recitar as minhas leis
E de falar do meu pacto?

[[v19-50-17]]

^<<v19-50-17,17>>^ Pois odeias a disciplina^&#42;1^
E viras as costas às minhas palavras.^&#42;2^

[NOTE]
====
. Ou: “instrução”.
. Lit.: “lanças as minhas palavras para trás de ti”.
====

[[v19-50-18]]

^<<v19-50-18,18>>^ Quando vês um ladrão, dás-lhe a tua aprovação;^&#42;1^
E andas com os adúlteros.

[NOTE]
====
. Ou, possivelmente: “juntas-te a ele”.
====

[[v19-50-19]]

^<<v19-50-19,19>>^ Usas a boca para divulgar o que é mau,
E a falsidade está presa à tua língua.

[[v19-50-20]]

^<<v19-50-20,20>>^ Sentas-te para falar mal do teu irmão;
Revelas as falhas do^&#42;1^ filho da tua própria mãe.

[NOTE]
====
. Ou: “Difamas o”.
====

[[v19-50-21]]

^<<v19-50-21,21>>^ Quando fizeste estas coisas, eu fiquei calado;
Então, pensaste que eu seria como tu.
Agora, porém, vou repreender-te
E vou apresentar a minha causa contra ti.

[[v19-50-22]]

^<<v19-50-22,22>>^ Por favor, considerem isto, vocês, os que se esquecem de Deus,
Senão, vou dilacerar-vos, e não haverá quem vos livre.

[[v19-50-23]]

^<<v19-50-23,23>>^ Quem oferece agradecimentos como sacrifício glorifica-me;
E quanto àquele que segue o caminho determinado,
Vou fazer com que veja a salvação da parte de Deus.”

'''

xref:019-salmo/019-salmo-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmo/019-salmo-051.adoc#v19-51-0[Próximo Capítulo &#62;]