include::./index.adoc[]

[[v19-43-0]]
=== Salmos, 43
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-43-1]]

^<<v19-43-1,1>>^ Julga-me, ó Deus,
Defende a minha causa contra uma nação desleal.
Livra-me dos homens mentirosos e perversos.

[[v19-43-2]]

^<<v19-43-2,2>>^ Pois tu és o meu Deus, a minha fortaleza.
Porque é que me rejeitaste?
Porque haveria eu de andar triste por causa da opressão do meu inimigo?

[[v19-43-3]]

^<<v19-43-3,3>>^ Envia a tua luz e a tua verdade.
Que elas me conduzam;
Que elas me guiem ao teu santo monte e ao teu grandioso tabernáculo.

[[v19-43-4]]

^<<v19-43-4,4>>^ Então, irei ao altar de Deus,
A Deus, a minha plena alegria.
E vou louvar-te com a harpa, ó Deus, meu Deus.

[[v19-43-5]]

^<<v19-43-5,5>>^ Porque é que estou em desespero?^&#42;1^
Porque é que estou tão agitado?
Esperarei em Deus,
Porque ainda vou louvá-lo como o meu Grandioso Salvador e o meu Deus.

[NOTE]
====
. Ou: “a minha alma se desespera”.
====

'''

xref:019-salmo/019-salmo-042.adoc#v19-42-0[&#60; Capítulo Anterior] | <<v19-43-0,Topo>> | xref:019-salmo/019-salmo-044.adoc#v19-44-0[Próximo Capítulo &#62;]