include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_ל &#91;lâmede&#93;_

[[v19-10-1]]

^<<v19-10-1,1>>^ Ó Jeová, porque é que ficas tão longe?
Porque é que te escondes em tempos de aflição?

[[v19-10-2]]

^<<v19-10-2,2>>^ Aquele que é mau, na sua arrogância, persegue o desamparado,
Mas será apanhado nas ciladas que planeia.

[[v19-10-3]]

^<<v19-10-3,3>>^ Pois quem é mau gaba-se dos seus desejos egoístas^&#42;1^
E abençoa o ganancioso;^&#42;2^

[NOTE]
====
. Ou: “do desejo da sua alma”.
. Ou, possivelmente: “O ganancioso abençoa-se a si mesmo”.
====

_נ &#91;nune&#93;_

Ele desrespeita a Jeová.

[NOTE]
====
. Ou: “do desejo da sua alma”.
. Ou, possivelmente: “O ganancioso abençoa-se a si mesmo”.
====

[[v19-10-4]]

^<<v19-10-4,4>>^ Na sua arrogância, aquele que é mau nada pesquisa;
Todos os seus pensamentos são: “Não há Deus.”

[[v19-10-5]]

^<<v19-10-5,5>>^ Os seus caminhos continuam a prosperar,
Mas os teus julgamentos estão além da sua compreensão;
Ele goza com^&#42;1^ todos os seus adversários.

[NOTE]
====
. Ou: “sopra com força contra”.
====

[[v19-10-6]]

^<<v19-10-6,6>>^ Ele diz no coração: “Nunca serei abalado;^&#42;1^
Geração após geração,
Nunca sofrerei calamidade.”

[NOTE]
====
. Ou: “Nunca cambalearei”.
====

_פ &#91;pê&#93;_

[[v19-10-7]]

^<<v19-10-7,7>>^ A sua boca está cheia de maldições, mentiras e ameaças;
Debaixo da sua língua há desgraça e maldade.

[[v19-10-8]]

^<<v19-10-8,8>>^ Ele fica de emboscada perto dos povoados;
Do seu esconderijo mata o inocente.

_ע &#91;aine&#93;_

Os seus olhos estão à procura de alguma vítima.

[[v19-10-9]]

^<<v19-10-9,9>>^ Ele espera no seu esconderijo como um leão no seu covil.^&#42;1^
Fica à espera para apanhar o indefeso.
Apanha o indefeso quando fecha a sua rede.

[NOTE]
====
. Ou: “na sua moita”.
====

[[v19-10-10]]

^<<v19-10-10,10>>^ A vítima é esmagada e lançada por terra;
O infeliz cai nas suas garras.

[[v19-10-11]]

^<<v19-10-11,11>>^ Ele diz no coração: “Deus esqueceu-se.
Virou a sua face.
Nunca vê nada.”

_ק &#91;cofe&#93;_

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, ó Jeová. Ó Deus, ergue a tua mão.
Não te esqueças dos desamparados.

[[v19-10-13]]

^<<v19-10-13,13>>^ Porque é que o mau desrespeitou Deus?
Ele diz no coração: “Não me farás prestar contas.”

_ר &#91;rexe&#93;_

[[v19-10-14]]

^<<v19-10-14,14>>^ Mas tu vês a desgraça e a aflição.
Observas e tomas em mãos o assunto.
A vítima desafortunada volta-se para ti;
Tu és o ajudador do órfão.^&#42;1^

[NOTE]
====
. Ou: “órfão de pai”.
====

_ש &#91;chim&#93;_

[[v19-10-15]]

^<<v19-10-15,15>>^ Parte o braço ao homem mau e perverso,
Para que, ao procurares a sua maldade,
Já não a encontres.

[[v19-10-16]]

^<<v19-10-16,16>>^ Jeová é Rei para todo o sempre.
As nações desapareceram da terra.

_ת &#91;tau&#93;_

[[v19-10-17]]

^<<v19-10-17,17>>^ Mas tu ouvirás o pedido dos mansos, ó Jeová.
Vais fortalecer o seu coração e dar-lhes muita atenção.

[[v19-10-18]]

^<<v19-10-18,18>>^ Farás justiça aos órfãos e aos oprimidos,
A fim de que o homem mortal da terra não volte a amedrontá-los.

'''

xref:019-salmo/019-salmo-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmo/019-salmo-011.adoc#v19-11-0[Próximo Capítulo &#62;]