include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-116-1]]

^<<v19-116-1,1>>^ Eu amo a Jeová,
Porque ele ouve^&#42;1^ a minha voz, as minhas súplicas por ajuda.

[NOTE]
====
. Ou, possivelmente: “Eu amo, porque Jeová ouve”.
====

[[v19-116-2]]

^<<v19-116-2,2>>^ Pois ele inclina-me o seu ouvido,^&#42;1^
E vou invocá-lo enquanto eu viver.^&#42;2^

[NOTE]
====
. Ou: “abaixa-se para me ouvir”.
. Lit.: “nos meus dias”.
====

[[v19-116-3]]

^<<v19-116-3,3>>^ Cercaram-me as cordas da morte;
A Sepultura apoderou-se de mim.^&#42;1^
Fui dominado pela aflição e pela tristeza.

[NOTE]
====
. Lit.: “As aflições do Seol encontraram-me”.
====

[[v19-116-4]]

^<<v19-116-4,4>>^ No entanto, invoquei o nome de Jeová:
“Ó Jeová, livra-me!”^&#42;1^

[NOTE]
====
. Ou: “livra a minha alma”.
====

[[v19-116-5]]

^<<v19-116-5,5>>^ Jeová é compassivo^&#42;1^ e justo;
O nosso Deus é misericordioso.

[NOTE]
====
. Ou: “benevolente”.
====

[[v19-116-6]]

^<<v19-116-6,6>>^ Jeová guarda os inexperientes.
Eu estava sem forças, e ele salvou-me.

[[v19-116-7]]

^<<v19-116-7,7>>^ Que a minha alma^&#42;1^ descanse novamente,
Pois Jeová agiu bondosamente comigo.

[NOTE]
====
. Veja o Glossário.
====

[[v19-116-8]]

^<<v19-116-8,8>>^ Tu livraste-me^&#42;1^ da morte;
Livraste os meus olhos das lágrimas, o meu pé do tropeço.

[NOTE]
====
. Ou: “Tu livraste a minha alma”.
====

[[v19-116-9]]

^<<v19-116-9,9>>^ Andarei diante de Jeová na terra dos vivos.

[[v19-116-10]]

^<<v19-116-10,10>>^ Tive fé, portanto falei;
Eu estava muito aflito.

[[v19-116-11]]

^<<v19-116-11,11>>^ Entrei em pânico e disse:
“Todos os homens são mentirosos.”

[[v19-116-12]]

^<<v19-116-12,12>>^ Como é que vou retribuir a Jeová
Todo o bem que me tem feito?

[[v19-116-13]]

^<<v19-116-13,13>>^ Levantarei o cálice da salvação,^&#42;1^
E invocarei o nome de Jeová.

[NOTE]
====
. Ou: “grandiosa salvação”.
====

[[v19-116-14]]

^<<v19-116-14,14>>^ Cumprirei os meus votos a Jeová
Na presença de todo o seu povo.

[[v19-116-15]]

^<<v19-116-15,15>>^ Dolorosa^&#42;1^ aos olhos de Jeová
É a morte dos que lhe são leais.

[NOTE]
====
. Lit.: “Preciosa”.
====

[[v19-116-16]]

^<<v19-116-16,16>>^ Suplico-te, ó Jeová,
Pois sou teu servo.
Sou teu servo, filho da tua escrava.
Soltaste-me das minhas correntes.

[[v19-116-17]]

^<<v19-116-17,17>>^ Irei oferecer-te o sacrifício de agradecimento;
Invocarei o nome de Jeová.

[[v19-116-18]]

^<<v19-116-18,18>>^ Cumprirei os meus votos a Jeová
Na presença de todo o seu povo,

[[v19-116-19]]

^<<v19-116-19,19>>^ Nos pátios da casa de Jeová,
No teu meio, ó Jerusalém.
Louvem a Jah!^&#42;1^

[NOTE]
====
. Ou: “Aleluia!” “Jah” é uma forma reduzida do nome Jeová.
====

'''

xref:019-salmo/019-salmo-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmo/019-salmo-117.adoc#v19-117-0[Próximo Capítulo &#62;]