include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente; de Jedutum.^&#42;1^ Salmo de David._

[[v19-62-1]]

^<<v19-62-1,1>>^ Somente em Deus espero^&#42;1^ silenciosamente.
Dele vem a minha salvação.

[NOTE]
====
. Ou: “a minha alma espera”.
====

[[v19-62-2]]

^<<v19-62-2,2>>^ Só ele é a minha rocha e a minha salvação, o meu refúgio seguro;^&#42;1^
Nunca serei completamente abalado.

[NOTE]
====
. Ou: “refúgio num lugar alto”.
====

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando atacarão um homem para o matarem?
Vocês são todos tão perigosos como uma parede que está a cair, como uma parede de pedras prestes a desmoronar-se.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Vocês todos, como se ele fosse uma parede que está a cair, um muro de pedras prestes a desmoronar-se.”
====

[[v19-62-4]]

^<<v19-62-4,4>>^ Eles conspiram para derrubá-lo da sua posição elevada;^&#42;1^
Têm prazer em mentir.
Abençoam com a boca, mas amaldiçoam no íntimo. (Selá)

[NOTE]
====
. Ou: “sua dignidade”.
====

[[v19-62-5]]

^<<v19-62-5,5>>^ Somente em Deus espero silenciosamente,^&#42;1^
Porque dele vem a minha esperança.

[NOTE]
====
. Ou: “espera silenciosamente, ó minha alma”.
====

[[v19-62-6]]

^<<v19-62-6,6>>^ Só ele é a minha rocha e a minha salvação, o meu refúgio seguro;
Nunca serei abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ De Deus depende a minha salvação e a minha glória.
Deus é a minha forte rocha, o meu refúgio.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confia sempre nele, ó povo.
Derramem o coração diante dele.
Deus é um refúgio para nós. (Selá)

[[v19-62-9]]

^<<v19-62-9,9>>^ Os filhos do homem são apenas um sopro,
Os filhos da humanidade são uma ilusão.
Colocados juntos na balança, são mais leves do que um sopro.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confiem na extorsão
Nem ponham falsas esperanças no roubo.
Se a vossa riqueza aumentar, não fixem nela o coração.

[[v19-62-11]]

^<<v19-62-11,11>>^ Deus disse uma vez, e duas vezes eu ouvi:
A força pertence a Deus.

[[v19-62-12]]

^<<v19-62-12,12>>^ O amor leal também te pertence, ó Jeová,
Pois retribuis a cada um segundo as suas ações.

'''

xref:019-salmo/019-salmo-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmo/019-salmo-063.adoc#v19-63-0[Próximo Capítulo &#62;]