include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Masquil.^&#42;1^ De Asafe._

[[v19-78-1]]

^<<v19-78-1,1>>^ Escuta a minha lei,^&#42;1^ ó meu povo;
Presta atenção^&#42;2^ às palavras da minha boca.

[NOTE]
====
. Ou: “instrução”.
. Ou: “Inclina o teu ouvido”.
====

[[v19-78-2]]

^<<v19-78-2,2>>^ Abrirei a minha boca para dizer um provérbio.
Proferirei enigmas dos tempos antigos.

[[v19-78-3]]

^<<v19-78-3,3>>^ As coisas que ouvimos e conhecemos,
Que os nossos pais nos contaram,

[[v19-78-4]]

^<<v19-78-4,4>>^ Não esconderemos dos seus descendentes;
Contaremos à geração futura
Os atos louváveis de Jeová e a sua força,
As coisas maravilhosas que ele tem feito.

[[v19-78-5]]

^<<v19-78-5,5>>^ Ele estabeleceu um testemunho^&#42;1^ em Jacó
E instituiu uma lei em Israel;
Ele ordenou aos nossos antepassados
Que dessem a conhecer essas coisas aos seus filhos,

[NOTE]
====
. Ou: “uma advertência”.
====

[[v19-78-6]]

^<<v19-78-6,6>>^ Para que a geração seguinte as soubesse,
Os filhos que ainda nasceriam.
Eles, por sua vez, iriam relatá-las aos seus filhos.

[[v19-78-7]]

^<<v19-78-7,7>>^ Assim, estes poriam a sua confiança em Deus.
Não se esqueceriam dos atos de Deus,
Mas obedeceriam aos seus mandamentos.

[[v19-78-8]]

^<<v19-78-8,8>>^ Desse modo, não seriam como os seus antepassados,
Uma geração obstinada e rebelde,
Uma geração de coração inconstante,^&#42;1^
E cujo espírito não foi fiel a Deus.

[NOTE]
====
. Lit.: “despreparado”.
====

[[v19-78-9]]

^<<v19-78-9,9>>^ Os efraimitas estavam armados com os seus arcos,
Mas bateram em retirada no dia da batalha.

[[v19-78-10]]

^<<v19-78-10,10>>^ Não guardaram o pacto de Deus
E recusaram-se a andar na sua lei.

[[v19-78-11]]

^<<v19-78-11,11>>^ Também se esqueceram do que ele tinha feito,
Os seus atos maravilhosos, que lhes mostrou.

[[v19-78-12]]

^<<v19-78-12,12>>^ Ele fez coisas esplêndidas à vista dos seus antepassados,
Na terra do Egito, a região de Zoã.

[[v19-78-13]]

^<<v19-78-13,13>>^ Dividiu o mar para que o atravessassem
E fez com que as águas se erguessem como uma barragem.^&#42;1^

[NOTE]
====
. Ou: “um muro”.
====

[[v19-78-14]]

^<<v19-78-14,14>>^ Guiou-os de dia com uma nuvem
E, durante toda a noite, com a luz de um fogo.

[[v19-78-15]]

^<<v19-78-15,15>>^ Partiu rochas no deserto
E deu-lhes de beber até se saciarem, como se fosse de águas profundas.

[[v19-78-16]]

^<<v19-78-16,16>>^ Fez sair correntes de água de um rochedo
E fez com que águas fluíssem como rios.

[[v19-78-17]]

^<<v19-78-17,17>>^ Mas eles continuaram a pecar contra ele,
Rebelando-se contra o Altíssimo no deserto.

[[v19-78-18]]

^<<v19-78-18,18>>^ Desafiaram^&#42;1^ a Deus no coração,
Exigindo o alimento que desejavam intensamente.^&#42;2^

[NOTE]
====
. Lit.: “Testaram”.
. Ou: “alimento para a sua alma”.
====

[[v19-78-19]]

^<<v19-78-19,19>>^ Então, falaram contra Deus;
Disseram: “Será que Deus pode preparar uma mesa no deserto?”

[[v19-78-20]]

^<<v19-78-20,20>>^ Foi ele que bateu numa rocha
De modo que fluíram águas e jorraram torrentes.
“Será que ele também nos pode dar pão
Ou providenciar carne para o seu povo?”

[[v19-78-21]]

^<<v19-78-21,21>>^ Quando Jeová os ouviu, ficou furioso;
Acendeu-se um fogo contra Jacó
E a sua ira levantou-se contra Israel

[[v19-78-22]]

^<<v19-78-22,22>>^ Porque não tiveram fé em Deus;
Não confiaram na sua capacidade de salvá-los.

[[v19-78-23]]

^<<v19-78-23,23>>^ Então, ele deu uma ordem às nuvens lá em cima,
Abriu as portas do céu.

[[v19-78-24]]

^<<v19-78-24,24>>^ Fez chover maná, para que comessem;
Deu-lhes o cereal do céu.

[[v19-78-25]]

^<<v19-78-25,25>>^ Homens comeram o pão dos poderosos;^&#42;1^
Ele forneceu o necessário para satisfazê-los.

[NOTE]
====
. Ou: “dos anjos”.
====

[[v19-78-26]]

^<<v19-78-26,26>>^ Levantou um vento leste nos céus
E, com o seu poder, fez soprar um vento sul.

[[v19-78-27]]

^<<v19-78-27,27>>^ E fez chover carne sobre eles, como se fosse pó,
Aves como a areia da praia.

[[v19-78-28]]

^<<v19-78-28,28>>^ Ele fez com que caíssem no meio do Seu acampamento,
Em volta das Suas tendas.

[[v19-78-29]]

^<<v19-78-29,29>>^ E eles comeram e empanturraram-se;
Ele deu-lhes o que desejavam.

[[v19-78-30]]

^<<v19-78-30,30>>^ Mas, antes de terem satisfeito plenamente o seu desejo,
Enquanto a comida ainda estava na sua boca,

[[v19-78-31]]

^<<v19-78-31,31>>^ A ira de Deus levantou-se contra eles.
Ele matou os homens mais fortes entre eles;
Derrubou os jovens de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ Apesar disso, pecaram ainda mais,
E não tiveram fé nos Seus atos maravilhosos.

[[v19-78-33]]

^<<v19-78-33,33>>^ Portanto, ele acabou com os seus dias como se fossem apenas um sopro,
E acabou com os seus anos por meio de um terror repentino.

[[v19-78-34]]

^<<v19-78-34,34>>^ Mas, sempre que causava morte entre eles, procuravam-no;
Voltavam atrás e procuravam por Deus,

[[v19-78-35]]

^<<v19-78-35,35>>^ Lembrando-se de que Deus era a sua Rocha
E de que o Deus Altíssimo era o seu Redentor.^&#42;1^

[NOTE]
====
. Ou: “Vingador”.
====

[[v19-78-36]]

^<<v19-78-36,36>>^ No entanto, tentaram enganá-lo com a sua boca
E mentiram-lhe com a sua língua.

[[v19-78-37]]

^<<v19-78-37,37>>^ O seu coração não era firme para com ele;
Eles não eram fiéis ao Seu pacto.

[[v19-78-38]]

^<<v19-78-38,38>>^ Mas ele era misericordioso;
Perdoava-lhes^&#42;1^ o erro e não os destruía.
Muitas vezes, conteve a sua ira,
Em vez de dar vazão a todo o seu furor.

[NOTE]
====
. Lit.: “Cobria-lhes”.
====

[[v19-78-39]]

^<<v19-78-39,39>>^ Pois lembrava-se de que eles eram carne,
Um vento que passa e não retorna.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “De que o espírito sai e não volta”.
====

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes se rebelaram contra ele no ermo
E fizeram-no sentir-se magoado no deserto!

[[v19-78-41]]

^<<v19-78-41,41>>^ Vez após vez, puseram Deus à prova
E entristeceram o^&#42;1^ Santo de Israel.

[NOTE]
====
. Ou: “causaram dor ao”.
====

[[v19-78-42]]

^<<v19-78-42,42>>^ Não se lembraram do Seu poder,^&#42;1^
Do dia em que ele os livrou^&#42;2^ do adversário,

[NOTE]
====
. Lit.: “da Sua mão”.
. Ou: “resgatou”.
====

[[v19-78-43]]

^<<v19-78-43,43>>^ De como ele mostrou os seus sinais no Egito
E os seus milagres na região de Zoã

[[v19-78-44]]

^<<v19-78-44,44>>^ E de como transformou em sangue os canais do Nilo,
De modo que não puderam beber das suas correntes de água.

[[v19-78-45]]

^<<v19-78-45,45>>^ Ele enviou enxames de moscões para os devorarem
E rãs para os arruinarem.

[[v19-78-46]]

^<<v19-78-46,46>>^ Deu as suas safras aos gafanhotos vorazes,
O fruto do seu trabalho árduo aos enxames de gafanhotos.

[[v19-78-47]]

^<<v19-78-47,47>>^ Destruiu as suas videiras com granizo
E as suas figueiras^&#42;1^ com chuva de pedra.

[NOTE]
====
. Ou: “os seus sicómoros”.
====

[[v19-78-48]]

^<<v19-78-48,48>>^ Entregou os seus animais de carga ao granizo
E atingiu o seu gado com raios.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “com febre ardente”.
====

[[v19-78-49]]

^<<v19-78-49,49>>^ Lançou sobre eles a sua ira ardente,
Fúria, indignação e aflição;
Enviou exércitos de anjos para trazer calamidade.

[[v19-78-50]]

^<<v19-78-50,50>>^ Ele abriu caminho para a sua ira.
Não os poupou^&#42;1^ da morte
E entregou-os^&#42;2^ à peste.

[NOTE]
====
. Ou: “Não poupou a alma deles”.
. Lit.: “entregou a vida deles”.
====

[[v19-78-51]]

^<<v19-78-51,51>>^ Por fim, matou todos os primogénitos do Egito;
Os primeiros frutos da sua faculdade reprodutiva, nas tendas de Cã.

[[v19-78-52]]

^<<v19-78-52,52>>^ Depois, fez o seu povo sair como um rebanho
E conduziu-os como ovelhas no deserto.

[[v19-78-53]]

^<<v19-78-53,53>>^ Guiou-os em segurança,
E eles não sentiram medo;
O mar cobriu os inimigos deles.

[[v19-78-54]]

^<<v19-78-54,54>>^ E ele trouxe-os para o Seu território santo,
Esta região montanhosa que a sua mão direita conquistou.

[[v19-78-55]]

^<<v19-78-55,55>>^ Expulsou as nações de diante deles;
Com a corda de medir, repartiu uma herança entre eles;
Estabeleceu as tribos de Israel nos seus lares.

[[v19-78-56]]

^<<v19-78-56,56>>^ Mas eles continuaram a desafiar^&#42;1^ a Deus, o Altíssimo, e a rebelar-se contra ele;
Não prestaram atenção às suas advertências.^&#42;2^

[NOTE]
====
. Lit.: “testar”.
. “Advertência” refere-se a um lembrete do que é necessário fazer.
====

[[v19-78-57]]

^<<v19-78-57,57>>^ Desviaram-se e foram tão traiçoeiros como os seus antepassados.
Não eram dignos de confiança, tal como um arco frouxo.

[[v19-78-58]]

^<<v19-78-58,58>>^ Eles ofendiam-no com os seus altos sagrados
E provocaram a fúria^&#42;1^ dele com as suas imagens esculpidas.

[NOTE]
====
. Ou: “o ciúme”.
====

[[v19-78-59]]

^<<v19-78-59,59>>^ Deus ouviu e enfureceu-se,
Por isso, rejeitou Israel totalmente.

[[v19-78-60]]

^<<v19-78-60,60>>^ Por fim, abandonou o tabernáculo de Silo,
A tenda onde tinha residido entre os homens.

[[v19-78-61]]

^<<v19-78-61,61>>^ Ele deixou que o símbolo da Sua força fosse para o cativeiro;
Que o Seu esplendor caísse nas mãos do adversário.

[[v19-78-62]]

^<<v19-78-62,62>>^ Ele entregou o seu povo à espada
E ficou furioso com a sua herança.

[[v19-78-63]]

^<<v19-78-63,63>>^ O fogo consumiu os seus jovens,
E para as suas moças^&#42;1^ não houve canções de casamento.^&#42;2^

[NOTE]
====
. Ou: “virgens”.
. Lit.: “E as suas virgens não foram louvadas”.
====

[[v19-78-64]]

^<<v19-78-64,64>>^ Os seus sacerdotes caíram pela espada,
E as suas viúvas não choraram por eles.

[[v19-78-65]]

^<<v19-78-65,65>>^ Então, Jeová acordou como que de um sono,
Como um guerreiro que acorda do efeito do vinho.

[[v19-78-66]]

^<<v19-78-66,66>>^ E pôs os seus adversários em fuga;
Entregou-os à desonra permanente.

[[v19-78-67]]

^<<v19-78-67,67>>^ Ele rejeitou a tenda de José,
Não escolheu a tribo de Efraim.

[[v19-78-68]]

^<<v19-78-68,68>>^ Mas escolheu a tribo de Judá,
O monte Sião, que ele ama.

[[v19-78-69]]

^<<v19-78-69,69>>^ Ele fez o seu santuário tão duradouro como os céus;^&#42;1^
Como a terra, que ele estabeleceu para sempre.

[NOTE]
====
. Lit.: “Ele construiu o seu santuário como as alturas”.
====

[[v19-78-70]]

^<<v19-78-70,70>>^ Escolheu David, seu servo,
E tirou-o dos currais das ovelhas,

[[v19-78-71]]

^<<v19-78-71,71>>^ De cuidar das ovelhas que amamentavam;
Ele tornou-o pastor de Jacó, o seu povo,
E de Israel, a sua herança.

[[v19-78-72]]

^<<v19-78-72,72>>^ Ele pastoreou-os com integridade de coração,
E conduziu-os com mãos hábeis.

'''

xref:019-salmo/019-salmo-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmo/019-salmo-079.adoc#v19-79-0[Próximo Capítulo &#62;]