include::./index.adoc[]

[[v19-91-0]]
=== Salmos, 91
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-91-1]]

^<<v19-91-1,1>>^ Quem morar no lugar secreto do Altíssimo
Encontrará abrigo na sombra do Todo-Poderoso.

[[v19-91-2]]

^<<v19-91-2,2>>^ Vou dizer a Jeová: “Tu és o meu refúgio e a minha fortaleza;
O meu Deus, em quem confio.”

[[v19-91-3]]

^<<v19-91-3,3>>^ Pois ele há de livrar-te da armadilha do passarinheiro,
Da peste destrutiva.

[[v19-91-4]]

^<<v19-91-4,4>>^ Ele há de cobrir-te^&#42;1^ com as Suas plumas,
E tu hás de refugiar-te debaixo das Suas asas.
A sua fidelidade  será um grande escudo e um muro protetor.^&#42;2^

[NOTE]
====
. Ou: “impedirá o acesso a ti”.
. Ou: “um baluarte”.
====

[[v19-91-5]]

^<<v19-91-5,5>>^ Não terás medo dos terrores da noite,
Nem da flecha que voa de dia,

[[v19-91-6]]

^<<v19-91-6,6>>^ Nem da pestilência que ronda nas trevas,
Nem da destruição que devasta ao meio-dia.

[[v19-91-7]]

^<<v19-91-7,7>>^ Mil cairão ao teu lado,
E dez mil à tua direita;
Mas nada te atingirá.

[[v19-91-8]]

^<<v19-91-8,8>>^ Apenas o verás com os teus olhos,
Serás testemunha da punição dos^&#42;1^ maus.

[NOTE]
====
. Lit.: “retribuição aos”.
====

[[v19-91-9]]

^<<v19-91-9,9>>^ Visto que disseste: “Jeová é o meu refúgio”,
Fizeste do Altíssimo a tua morada;^&#42;1^

[NOTE]
====
. Ou, possivelmente: “a tua fortaleza; o teu refúgio”.
====

[[v19-91-10]]

^<<v19-91-10,10>>^ Nenhum desastre te sobrevirá,
E nenhuma praga se aproximará da tua tenda.

[[v19-91-11]]

^<<v19-91-11,11>>^ Pois ele dará aos Seus anjos uma ordem referente a ti,
Para proteger-te em todos os teus caminhos.

[[v19-91-12]]

^<<v19-91-12,12>>^ Eles irão carregar-te nas mãos,
Para que não batas com o pé numa pedra.

[[v19-91-13]]

^<<v19-91-13,13>>^ Pisarás o leão novo e a naja;
Espezinharás o leão jubado e a cobra grande.

[[v19-91-14]]

^<<v19-91-14,14>>^ Deus disse: “Visto que ele me ama,^&#42;1^ vou livrá-lo.
Vou protegê-lo porque ele conhece^&#42;2^ o meu nome.

[NOTE]
====
. Lit.: “ele se uniu a mim”.
. Ou: “reconhece”.
====

[[v19-91-15]]

^<<v19-91-15,15>>^ Ele vai invocar-me, e eu vou responder-lhe.
Estarei com ele nos momentos de aflição.
Vou livrá-lo e glorificá-lo.

[[v19-91-16]]

^<<v19-91-16,16>>^ Vou saciá-lo com uma vida longa
E fazer com que veja os meus atos de salvação.”^&#42;1^

[NOTE]
====
. Ou: “veja a salvação da minha parte”.
====

'''

xref:019-salmo/019-salmo-090.adoc#v19-90-0[&#60; Capítulo Anterior] | <<v19-91-0,Topo>> | xref:019-salmo/019-salmo-092.adoc#v19-92-0[Próximo Capítulo &#62;]