include::./index.adoc[]

[[v19-22-0]]
=== Salmos, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Ao regente; com a melodia de A Corça da Aurora.^&#42;1^ Salmo de David._

[[v19-22-1]]

^<<v19-22-1,1>>^ Deus meu, Deus meu, porque me abandonaste?
Porque é que estás longe de me salvar,
Longe dos meus gritos de aflição?

[[v19-22-2]]

^<<v19-22-2,2>>^ Meu Deus, clamo durante o dia, e tu não respondes;
E, durante a noite, não há silêncio da minha parte.

[[v19-22-3]]

^<<v19-22-3,3>>^ Mas tu és santo,
Estás rodeado pelos^&#42;1^ louvores de Israel.

[NOTE]
====
. Ou: “entronizado entre (sobre) os”.
====

[[v19-22-4]]

^<<v19-22-4,4>>^ Em ti, os nossos pais punham a sua confiança;
Eles confiavam e tu os livravas.

[[v19-22-5]]

^<<v19-22-5,5>>^ Clamavam a ti, e eram salvos;
Confiavam em ti, e não ficavam dececionados.^&#42;1^

[NOTE]
====
. Ou: “não eram envergonhados”.
====

[[v19-22-6]]

^<<v19-22-6,6>>^ Mas eu sou um verme, não um homem,
Ridicularizado pelos^&#42;1^ homens e desprezado pelo povo.

[NOTE]
====
. Ou: “Uma vergonha para os”.
====

[[v19-22-7]]

^<<v19-22-7,7>>^ Todos os que me veem gozam comigo;
Fazem pouco caso e abanam a cabeça com desprezo:

[[v19-22-8]]

^<<v19-22-8,8>>^ “Ele entregou-se a Jeová. Que Ele o livre!
Que Ele o salve, se o ama assim tanto!”

[[v19-22-9]]

^<<v19-22-9,9>>^ Foste tu que me tiraste do ventre,
Que me fizeste sentir seguro, aos seios da minha mãe.

[[v19-22-10]]

^<<v19-22-10,10>>^ Fui entregue ao teu cuidado^&#42;1^ desde que nasci;
Desde o ventre da minha mãe, tens sido o meu Deus.

[NOTE]
====
. Lit.: “lançado sobre ti”.
====

[[v19-22-11]]

^<<v19-22-11,11>>^ Não fiques longe de mim, pois a aflição está perto,
E não há mais ninguém para me ajudar.

[[v19-22-12]]

^<<v19-22-12,12>>^ Cercam-me muitos novilhos;
Rodeiam-me fortes touros de Basã.

[[v19-22-13]]

^<<v19-22-13,13>>^ Abrem a boca contra mim,
Como um leão que ruge e dilacera a sua presa.

[[v19-22-14]]

^<<v19-22-14,14>>^ Sou derramado como água;
Todos os meus ossos estão desconjuntados.
O meu coração tornou-se como cera,
Derrete-se no meu íntimo.

[[v19-22-15]]

^<<v19-22-15,15>>^ A minha força secou-se como um caco de barro;
A minha língua pegou-se ao céu da boca.
Trazes-me ao pó da morte.

[[v19-22-16]]

^<<v19-22-16,16>>^ Pois os cães rodeiam-me;
Eles cercam-me como um bando de malfeitores.
Como um leão, atacam as minhas mãos e os meus pés.

[[v19-22-17]]

^<<v19-22-17,17>>^ Posso contar todos os meus ossos.
Eles observam-me e fixam o seu olhar em mim.

[[v19-22-18]]

^<<v19-22-18,18>>^ Repartem as minhas roupas entre si
E lançam sortes sobre a minha vestimenta.

[[v19-22-19]]

^<<v19-22-19,19>>^ Tu, porém, ó Jeová, não fiques longe.
Tu és a minha força; vem depressa ajudar-me.

[[v19-22-20]]

^<<v19-22-20,20>>^ Salva-me^&#42;1^ da espada,
Livra a minha preciosa vida^&#42;2^ das patas^&#42;3^ dos cães;

[NOTE]
====
. Ou: “Salva a minha alma”.
. Lit.: “a minha única”, referindo-se à sua alma, ou vida.
. Lit.: “da mão”.
====

[[v19-22-21]]

^<<v19-22-21,21>>^ Salva-me da boca do leão e dos chifres de touros selvagens;
Responde-me e salva-me.

[[v19-22-22]]

^<<v19-22-22,22>>^ Vou declarar o teu nome aos meus irmãos
E louvar-te no meio da congregação.

[[v19-22-23]]

^<<v19-22-23,23>>^ Vocês, os que temem a Jeová, louvem-no!
Que toda a descendência^&#42;1^ de Jacó o glorifique!
Que toda a descendência^&#42;2^ de Israel o reverencie.

[NOTE]
====
. Lit.: “semente”.
. Lit.: “semente”.
====

[[v19-22-24]]

^<<v19-22-24,24>>^ Pois ele não desprezou nem repudiou o sofrimento do oprimido;
Não lhe escondeu a face.
Quando ele clamou por ajuda, ele ouviu-o.

[[v19-22-25]]

^<<v19-22-25,25>>^ Vou louvar-te na grande congregação;
Cumprirei os meus votos diante dos que O temem.

[[v19-22-26]]

^<<v19-22-26,26>>^ Os mansos comerão e ficarão satisfeitos;
Os que procuram a Jeová hão de louvá-lo.
Que vocês vivam^&#42;1^ para sempre.

[NOTE]
====
. Lit.: “Que o vosso coração viva”.
====

[[v19-22-27]]

^<<v19-22-27,27>>^ Todos os confins da terra vão lembrar-se de Jeová e voltar-se para ele.
Todas as famílias das nações vão curvar-se diante de ti.

[[v19-22-28]]

^<<v19-22-28,28>>^ Pois o reinado pertence a Jeová;
Ele governa as nações.

[[v19-22-29]]

^<<v19-22-29,29>>^ Todos os prósperos^&#42;1^ da terra hão de comer e curvar-se,
Todos os que descem ao pó hão de ajoelhar-se perante ele;
Nenhum deles pode preservar a sua vida.^&#42;2^

[NOTE]
====
. Lit.: “gordos”.
. Ou: “alma”.
====

[[v19-22-30]]

^<<v19-22-30,30>>^ Os descendentes deles irão servi-lo;^&#42;1^
A próxima geração ouvirá falar sobre Jeová.

[NOTE]
====
. Lit.: “Uma semente vai servi-lo”.
====

[[v19-22-31]]

^<<v19-22-31,31>>^ Eles chegarão e declararão a Sua justiça.
Ao povo que ainda está para nascer, contarão o que ele tem feito.

'''

xref:019-salmo/019-salmo-021.adoc#v19-21-0[&#60; Capítulo Anterior] | <<v19-22-0,Topo>> | xref:019-salmo/019-salmo-023.adoc#v19-23-0[Próximo Capítulo &#62;]