include::./index.adoc[]

[[v19-71-0]]
=== Salmos, 71
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v19-71-1]]

^<<v19-71-1,1>>^ Refugiei-me em ti, ó Jeová.
Que eu nunca seja envergonhado.

[[v19-71-2]]

^<<v19-71-2,2>>^ Salva-me e livra-me, pois tu és justo.
Inclina-me o teu ouvido^&#42;1^ e salva-me.

[NOTE]
====
. Ou: “Abaixa-te e ouve-me”.
====

[[v19-71-3]]

^<<v19-71-3,3>>^ Torna-te para mim uma fortificação na rocha,
Onde eu possa sempre abrigar-me.
Dá a ordem para que eu seja salvo,
Pois tu és o meu rochedo e a minha fortaleza.

[[v19-71-4]]

^<<v19-71-4,4>>^ Ó meu Deus, livra-me da mão dos maus,
Do poder do opressor injusto.

[[v19-71-5]]

^<<v19-71-5,5>>^ Pois tu és a minha esperança, ó Soberano Senhor Jeová;
Confio em ti^&#42;1^ desde a minha juventude.

[NOTE]
====
. Ou: “Tu és a minha confiança”.
====

[[v19-71-6]]

^<<v19-71-6,6>>^ Em ti me amparo desde que nasci;
Foste tu que me tiraste do ventre da minha mãe.
Louvo-te sem cessar.

[[v19-71-7]]

^<<v19-71-7,7>>^ Para muitos, tornei-me como um milagre,
Mas tu és o meu forte refúgio.

[[v19-71-8]]

^<<v19-71-8,8>>^ A minha boca está cheia do teu louvor;
Falo do teu esplendor o dia inteiro.

[[v19-71-9]]

^<<v19-71-9,9>>^ Não me rejeites na minha velhice;
Não me abandones quando me faltarem as forças.

[[v19-71-10]]

^<<v19-71-10,10>>^ Os meus inimigos falam contra mim,
E os que procuram tirar-me a vida^&#42;1^ conspiram,

[NOTE]
====
. Ou: “procuram a minha alma”.
====

[[v19-71-11]]

^<<v19-71-11,11>>^ Dizendo: “Deus abandonou-o.
Persigam-no e agarrem-no, pois não há quem o salve.”

[[v19-71-12]]

^<<v19-71-12,12>>^ Ó Deus, não fiques longe de mim.
Ó meu Deus, vem depressa ajudar-me.

[[v19-71-13]]

^<<v19-71-13,13>>^ Que os que se opõem a mim^&#42;1^
Sejam envergonhados e eliminados.
Que os que procuram a minha calamidade
Fiquem cobertos de desonra e de humilhação.

[NOTE]
====
. Ou: “à minha alma”.
====

[[v19-71-14]]

^<<v19-71-14,14>>^ Mas, quanto a mim, continuarei à espera;
Vou louvar-te cada vez mais.

[[v19-71-15]]

^<<v19-71-15,15>>^ A minha boca relatará a tua justiça,
Os teus atos de salvação, o dia inteiro,
Apesar de serem tantos que estão além da minha compreensão.^&#42;1^

[NOTE]
====
. Ou: “que não os posso enumerar”.
====

[[v19-71-16]]

^<<v19-71-16,16>>^ Irei e falarei sobre os teus atos poderosos,
Ó Soberano Senhor Jeová;
Falarei sobre a tua justiça, somente a tua.

[[v19-71-17]]

^<<v19-71-17,17>>^ Ó Deus, ensinaste-me desde a minha juventude
E, até agora, continuo a declarar os teus atos maravilhosos.

[[v19-71-18]]

^<<v19-71-18,18>>^ Mesmo quando eu for velho e de cabelos brancos, ó Deus, não me abandones.
Que eu fale sobre a tua força^&#42;1^ à próxima geração,
E sobre o teu poder a todos os que ainda virão.

[NOTE]
====
. Lit.: “o teu braço”.
====

[[v19-71-19]]

^<<v19-71-19,19>>^ A tua justiça, ó Deus, chega às alturas;
Fizeste coisas grandiosas;
Ó Deus, quem é semelhante a ti?

[[v19-71-20]]

^<<v19-71-20,20>>^ Embora me tenhas feito passar por muitas aflições e calamidades,
Dá-me vida novamente;
Faz-me subir das profundezas^&#42;1^ da terra.

[NOTE]
====
. Ou: “águas profundas”.
====

[[v19-71-21]]

^<<v19-71-21,21>>^ Aumenta a minha dignidade,
Cerca-me com a tua proteção e consola-me.

[[v19-71-22]]

^<<v19-71-22,22>>^ Então, hei de louvar-te com um instrumento de cordas
Por causa da tua fidelidade, ó meu Deus.
Vou cantar-te louvores^&#42;1^ com a harpa,
Ó Santo de Israel.

[NOTE]
====
. Ou: “Vou fazer-te música”.
====

[[v19-71-23]]

^<<v19-71-23,23>>^ Os meus lábios gritarão de alegria quando eu te cantar louvores,
Pois salvaste-me a vida.^&#42;1^

[NOTE]
====
. Ou: “resgataste a minha alma”.
====

[[v19-71-24]]

^<<v19-71-24,24>>^ A minha língua falará^&#42;1^ sobre a tua justiça o dia inteiro,
Pois os que desejam a minha destruição serão envergonhados e desonrados.

[NOTE]
====
. Ou: “meditará”.
====

'''

xref:019-salmo/019-salmo-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-salmo/019-salmo-072.adoc#v19-72-0[Próximo Capítulo &#62;]