include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Salmo de David. Cântico para a inauguração da casa._

[[v19-30-1]]

^<<v19-30-1,1>>^ Eu vou exaltar-te, ó Jeová, porque tu me levantaste;^&#42;1^
Não deixaste que os meus inimigos se alegrassem com o meu mal.

[NOTE]
====
. Ou: “puxaste para cima”.
====

[[v19-30-2]]

^<<v19-30-2,2>>^ Ó Jeová, meu Deus, clamei a ti por ajuda, e tu curaste-me.

[[v19-30-3]]

^<<v19-30-3,3>>^ Ó Jeová, tu ergueste-me^&#42;1^ da Sepultura.^&#42;2^
Mantiveste-me vivo; poupaste-me de descer à cova.^&#42;3^

[NOTE]
====
. Ou: “tu ergueste a minha alma”.
. Ou: “do Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. Ou: “sepultura”.
====

[[v19-30-4]]

^<<v19-30-4,4>>^ Cantem louvores^&#42;1^ a Jeová, vocês, os que lhe são leais;
Deem graças ao seu santo nome;^&#42;2^

[NOTE]
====
. Ou: “Façam música”.
. Lit.: “à recordação da sua santidade”.
====

[[v19-30-5]]

^<<v19-30-5,5>>^ Estar sob a sua ira dura apenas um instante,
Mas ser favorecido por ele^&#42;1^ é para toda a vida.
Ao anoitecer, talvez irrompa o choro, mas, de manhã, há gritos de alegria.

[NOTE]
====
. Ou: “pela sua boa vontade”.
====

[[v19-30-6]]

^<<v19-30-6,6>>^ Quando me senti seguro, disse:
“Nunca serei abalado.”^&#42;1^

[NOTE]
====
. Ou: “Nunca cambalearei.”
====

[[v19-30-7]]

^<<v19-30-7,7>>^ Ó Jeová, quando eu tinha o teu favor,^&#42;1^ tornaste-me tão forte como um monte.
Mas, quando escondeste a tua face, fiquei apavorado.

[NOTE]
====
. Ou: “a tua boa vontade”.
====

[[v19-30-8]]

^<<v19-30-8,8>>^ A ti, ó Jeová, eu clamava;
E a Jeová suplicava favor.

[[v19-30-9]]

^<<v19-30-9,9>>^ Que lucro haverá na minha morte,^&#42;1^ se eu descer à cova?^&#42;2^
Será que o pó te louvará? Será que declarará a tua fidelidade?

[NOTE]
====
. Lit.: “no meu sangue”.
. Ou: “sepultura”.
====

[[v19-30-10]]

^<<v19-30-10,10>>^ Ouve, ó Jeová, e mostra-me favor.
Ó Jeová, torna-te o meu ajudador.

[[v19-30-11]]

^<<v19-30-11,11>>^ Transformaste o meu luto em dança;
Tiraste-me a serapilheira^&#42;1^ e vestiste-me de alegria,

[NOTE]
====
. Veja o Glossário.
====

[[v19-30-12]]

^<<v19-30-12,12>>^ Para que eu^&#42;1^ cante o teu louvor, e não fique calado.
Ó Jeová, meu Deus, vou louvar-te para sempre.

[NOTE]
====
. Ou: “a minha glória”.
====

'''

xref:019-salmo/019-salmo-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmo/019-salmo-031.adoc#v19-31-0[Próximo Capítulo &#62;]