include::./index.adoc[]

[[v19-17-0]]
=== Salmos, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_Oração de David._

[[v19-17-1]]

^<<v19-17-1,1>>^ Ouve o meu apelo por justiça, ó Jeová;
Presta atenção ao meu clamor por ajuda;
Escuta a minha oração, feita sem falsidade.

[[v19-17-2]]

^<<v19-17-2,2>>^ Que tomes uma decisão justa a meu favor;
Que os teus olhos vejam o que é direito.

[[v19-17-3]]

^<<v19-17-3,3>>^ Sondaste o meu coração, examinaste-me à noite;
Tu refinaste-me;
Descobrirás que não tramei nada de mal,
E a minha boca não transgrediu.

[[v19-17-4]]

^<<v19-17-4,4>>^ Quanto às atividades dos homens,
Conforme a palavra dos teus lábios, evito os caminhos dos homens violentos.^&#42;1^

[NOTE]
====
. Ou: “do ladrão”.
====

[[v19-17-5]]

^<<v19-17-5,5>>^ Que os meus passos permaneçam nos teus caminhos,
Para que os meus pés não tropecem.

[[v19-17-6]]

^<<v19-17-6,6>>^ Invoco-te a ti, porque tu me responderás, ó Deus.
Inclina-me o teu ouvido.^&#42;1^ Ouve as minhas palavras.

[NOTE]
====
. Ou: “Abaixa-te e ouve-me.”
====

[[v19-17-7]]

^<<v19-17-7,7>>^ Mostra o teu amor leal de uma forma maravilhosa,
Ó Salvador daqueles que, à tua direita, procuram proteção
Dos que se revoltam contra ti.

[[v19-17-8]]

^<<v19-17-8,8>>^ Guarda-me como a menina dos teus olhos;
Esconde-me na sombra das tuas asas.

[[v19-17-9]]

^<<v19-17-9,9>>^ Guarda-me dos maus que me atacam,
Dos meus inimigos mortais^&#42;1^ que me rodeiam.

[NOTE]
====
. Ou: “meus inimigos contra a alma”.
====

[[v19-17-10]]

^<<v19-17-10,10>>^ Eles ficaram insensíveis,^&#42;1^
Com a sua boca, falam de modo arrogante.

[NOTE]
====
. Ou: “Eles estão encerrados na sua própria gordura”.
====

[[v19-17-11]]

^<<v19-17-11,11>>^ Agora, eles cercam-nos;
Estão atentos a uma oportunidade para causar a nossa queda.^&#42;1^

[NOTE]
====
. Ou: “derrubar-nos no chão”.
====

[[v19-17-12]]

^<<v19-17-12,12>>^ Ele é como um leão ávido por dilacerar a sua presa,
Como um leão novo agachado de emboscada.

[[v19-17-13]]

^<<v19-17-13,13>>^ Levanta-te, ó Jeová, a fim de enfrentá-lo e derrubá-lo;
Livra-me,^&#42;1^ com a tua espada, daquele que é mau;

[NOTE]
====
. Ou: “Livra a minha alma”.
====

[[v19-17-14]]

^<<v19-17-14,14>>^ Livra-me com a tua mão, ó Jeová,
Dos homens deste mundo,^&#42;1^ cuja porção está nesta vida,
Aqueles a quem enches com as tuas boas provisões
E que deixam uma herança para os seus muitos filhos.

[NOTE]
====
. Ou: “sistema de coisas”.
====

[[v19-17-15]]

^<<v19-17-15,15>>^ Mas, quanto a mim, verei a tua face em retidão;
Fico satisfeito ao acordar na tua presença.^&#42;1^

[NOTE]
====
. Ou: “ao ver a tua forma”.
====

'''

xref:019-salmo/019-salmo-016.adoc#v19-16-0[&#60; Capítulo Anterior] | <<v19-17-0,Topo>> | xref:019-salmo/019-salmo-018.adoc#v19-18-0[Próximo Capítulo &#62;]