include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_De David._

[[v19-35-1]]

^<<v19-35-1,1>>^ Ó Jeová, defende a minha causa contra os meus opositores;
Luta contra os que lutam contra mim.

[[v19-35-2]]

^<<v19-35-2,2>>^ Pega nos escudos, no pequeno^&#42;1^ e no grande,
E vem defender-me.

[NOTE]
====
. Ou: “broquel”, pequeno escudo geralmente usado por arqueiros.
====

[[v19-35-3]]

^<<v19-35-3,3>>^ Ergue a tua lança e o teu machado de guerra^&#42;1^ contra os que me perseguem.
Diz-me:^&#42;2^ “Sou a tua salvação.”

[NOTE]
====
. Ou: “a tua acha bipene”.
. Ou: “Diz à minha alma”.
====

[[v19-35-4]]

^<<v19-35-4,4>>^ Sejam desonrados e humilhados os que querem tirar-me a vida.^&#42;1^
Que recuem envergonhados os que tramam a minha destruição.

[NOTE]
====
. Ou: “alma”.
====

[[v19-35-5]]

^<<v19-35-5,5>>^ Tornem-se como a palha^&#42;1^ levada pelo vento;
Que o anjo de Jeová os expulse.

[NOTE]
====
. Ou: “pragana”.
====

[[v19-35-6]]

^<<v19-35-6,6>>^ Que o caminho deles seja escuro e escorregadio,
Quando o anjo de Jeová os perseguir.

[[v19-35-7]]

^<<v19-35-7,7>>^ Pois, sem motivo, esconderam uma rede para me apanhar;
Sem motivo, abriram uma cova para mim.^&#42;1^

[NOTE]
====
. Ou: “a minha alma”.
====

[[v19-35-8]]

^<<v19-35-8,8>>^ Que o desastre lhes sobrevenha de surpresa;
Sejam apanhados pela própria rede que esconderam;
Caiam nela e sejam destruídos.

[[v19-35-9]]

^<<v19-35-9,9>>^ Mas eu vou alegrar-me^&#42;1^ em Jeová,
Exultarei nos seus atos de salvação.

[NOTE]
====
. Ou: “a minha alma vai alegrar-se”.
====

[[v19-35-10]]

^<<v19-35-10,10>>^ Todos os meus ossos dirão:
“Ó Jeová, quem é semelhante a ti?
Tu livras o desamparado daqueles que são mais fortes,
O desamparado e o pobre daqueles que os roubam.”

[[v19-35-11]]

^<<v19-35-11,11>>^ Apresentam-se testemunhas maldosas,
Perguntando-me coisas de que nada sei.

[[v19-35-12]]

^<<v19-35-12,12>>^ Retribuem-me o bem com o mal,
Fazendo-me sentir desolado.^&#42;1^

[NOTE]
====
. Ou: “Fazendo a minha alma sentir-se desolada”.
====

[[v19-35-13]]

^<<v19-35-13,13>>^ No entanto, quando estavam doentes, eu vestia-me de serapilheira;^&#42;1^
Eu afligia-me^&#42;2^ com jejum,
E, quando a minha oração retornava sem resposta,^&#42;3^

[NOTE]
====
. Veja o Glossário.
. Ou: “Eu afligia a minha alma”.
. Ou: “voltava sobre o meu peito”.
====

[[v19-35-14]]

^<<v19-35-14,14>>^ Andava a chorar, como se fosse por um amigo ou um irmão;
Eu encurvava-me de tristeza, como alguém que está de luto pela mãe.

[[v19-35-15]]

^<<v19-35-15,15>>^ Mas, quando eu tropecei, eles alegraram-se e uniram-se.
Uniram-se para me atacar numa emboscada;
Dilaceraram-me e não ficaram calados.

[[v19-35-16]]

^<<v19-35-16,16>>^ Os ímpios ridicularizam-me com desprezo;^&#42;1^
Rangem os dentes contra mim.

[NOTE]
====
. Ou, possivelmente: “Os ímpios gozam por um pão”.
====

[[v19-35-17]]

^<<v19-35-17,17>>^ Ó Jeová, até quando é que ficarás apenas a olhar?
Livra-me^&#42;1^ dos seus ataques,
Livra a minha preciosa vida^&#42;2^ dos leões novos.^&#42;3^

[NOTE]
====
. Ou: “Livra a minha alma”.
. Lit.: “a minha única”, refere-se à sua alma, ou vida.
. Ou: “leões novos jubados”.
====

[[v19-35-18]]

^<<v19-35-18,18>>^ Então, hei de agradecer-te na grande congregação;
Vou louvar-te no meio das multidões.

[[v19-35-19]]

^<<v19-35-19,19>>^ Não permitas que aqueles que são meus inimigos sem razão se alegrem com a minha desgraça,
Não permitas que os que me odeiam sem motivo pisquem os olhos maldosamente.

[[v19-35-20]]

^<<v19-35-20,20>>^ Pois não proferem palavras de paz;
Mas, com falsidade, tramam contra os pacíficos da terra.

[[v19-35-21]]

^<<v19-35-21,21>>^ Abrem a boca para me acusar,
Dizendo: “Ah! Ah! Vimos com os nossos próprios olhos.”

[[v19-35-22]]

^<<v19-35-22,22>>^ Tu bem o viste, ó Jeová. Não fiques calado.
Ó Jeová, não fiques longe de mim.

[[v19-35-23]]

^<<v19-35-23,23>>^ Desperta e vem em minha defesa,
Ó meu Deus Jeová, defende a minha causa.

[[v19-35-24]]

^<<v19-35-24,24>>^ Julga-me de harmonia com a tua justiça, ó Jeová, meu Deus;
Não permitas que se alegrem com a minha desgraça.

[[v19-35-25]]

^<<v19-35-25,25>>^ Que nunca digam para si mesmos: “Ah! Conseguimos o que queríamos.”^&#42;1^
Que nunca digam: “Nós devorámo-lo.”

[NOTE]
====
. Ou: “Ah! A nossa alma.”
====

[[v19-35-26]]

^<<v19-35-26,26>>^ Que todos eles sejam envergonhados e desonrados,
Os que se alegram com a minha calamidade.
Que se vistam de vergonha e humilhação os que me tratam com arrogância.

[[v19-35-27]]

^<<v19-35-27,27>>^ Mas gritem de alegria os que se agradam da minha retidão;
Que digam sempre:
“Magnificado seja Jeová, aquele que se agrada da paz do seu servo.”

[[v19-35-28]]

^<<v19-35-28,28>>^ Então, a minha língua vai falar sobre a^&#42;1^ tua justiça
E louvar-te o dia inteiro.

[NOTE]
====
. Ou: “vai meditar na”.
====

'''

xref:019-salmo/019-salmo-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmo/019-salmo-036.adoc#v19-36-0[Próximo Capítulo &#62;]