include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v50-2-1]]

^<<v50-2-1,1>>^ Se há, pois, algum encorajamento em Cristo, algum consolo de amor, algum companheirismo espiritual,^&#42;1^ algum terno sentimento e compaixão,

[NOTE]
====
. Lit.: “alguma partilha de espírito”.
====

[[v50-2-2]]

^<<v50-2-2,2>>^ encham-me de alegria por terem o mesmo modo de pensar e o mesmo amor, estando completamente unidos,^&#42;1^ tendo o mesmo pensamento.

[NOTE]
====
. Ou: “sendo ajuntados na alma”.
====

[[v50-2-3]]

^<<v50-2-3,3>>^ Não façam nada por rivalidade nem por presunção; mas, com humildade,^&#42;1^ considerem os outros superiores a vocês,

[NOTE]
====
. Ou: “humildade mental”.
====

[[v50-2-4]]

^<<v50-2-4,4>>^ procurando não apenas os vossos próprios interesses, mas também os interesses dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Mantenham a mesma atitude mental que Cristo Jesus teve:

[[v50-2-6]]

^<<v50-2-6,6>>^ embora existisse em forma de Deus, nem sequer chegou a pensar na ideia de tentar ser igual a Deus.

[[v50-2-7]]

^<<v50-2-7,7>>^ Pelo contrário, ele abdicou de tudo o que tinha,^&#42;1^ assumiu a forma de escravo e tornou-se humano.^&#42;2^

[NOTE]
====
. Ou: “ele esvaziou-se”.
. Lit.: “veio a ser na semelhança de homens”.
====

[[v50-2-8]]

^<<v50-2-8,8>>^ Mais do que isso, quando veio como homem,^&#42;1^ humilhou-se e tornou-se obediente a ponto de enfrentar a morte, sim, morte numa estaca.^&#42;2^

[NOTE]
====
. Lit.: “quando se encontrou na aparência de homem”.
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v50-2-9]]

^<<v50-2-9,9>>^ Por esta mesma razão, Deus enalteceu-o a uma posição superior e deu-lhe bondosamente o nome que está acima de todos os outros nomes,

[[v50-2-10]]

^<<v50-2-10,10>>^ a fim de que, diante do nome de Jesus, se dobre todo o joelho — dos que estão no céu, na terra e debaixo da terra —

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda a língua reconheça abertamente que Jesus Cristo é Senhor, para a glória de Deus, o Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ Portanto, meus amados, assim como sempre obedeceram, não apenas durante a minha presença, mas agora muito mais prontamente durante a minha ausência, persistam em produzir a vossa própria salvação com temor e tremor.

[[v50-2-13]]

^<<v50-2-13,13>>^ Pois Deus é aquele que, segundo o que lhe agrada, atua em vocês e que vos dá tanto o desejo como o poder para agir.

[[v50-2-14]]

^<<v50-2-14,14>>^ Continuem a fazer todas as coisas sem queixas nem discussões,

[[v50-2-15]]

^<<v50-2-15,15>>^ para que venham a ser irrepreensíveis e inocentes, filhos de Deus sem defeito no meio de uma geração pervertida e corrompida, no meio da qual brilham como iluminadores no mundo,

[[v50-2-16]]

^<<v50-2-16,16>>^ mantendo-se firmemente agarrados à palavra da vida. Então, terei motivos para me alegrar no dia de Cristo, por saber que não corri em vão nem me esforcei tanto em vão.

[[v50-2-17]]

^<<v50-2-17,17>>^ Contudo, mesmo que eu seja derramado como oferta de bebida sobre o sacrifício e o serviço sagrado^&#42;1^ que provém da vossa fé,^&#42;2^ alegro-me e partilho a minha alegria com todos vocês.

[NOTE]
====
. Ou: “serviço público”.
. Ou: “serviço sagrado a que a vossa fé vos conduziu”.
====

[[v50-2-18]]

^<<v50-2-18,18>>^ Do mesmo modo, vocês também se devem alegrar e partilhar a vossa alegria comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Espero no Senhor Jesus enviar-vos em breve Timóteo, para que eu fique encorajado ao receber notícias vossas.

[[v50-2-20]]

^<<v50-2-20,20>>^ Pois não tenho ninguém com uma disposição igual à dele, que cuidará genuinamente de vocês.

[[v50-2-21]]

^<<v50-2-21,21>>^ Pois todos os outros procuram os seus próprios interesses, não os de Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas vocês conhecem a prova que ele deu de si mesmo, que ele trabalhou comigo como escravo na promoção das boas novas, como um filho com o pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ Portanto, é a ele que eu espero enviar assim que souber o que me vai acontecer.

[[v50-2-24]]

^<<v50-2-24,24>>^ De facto, estou confiante no Senhor de que eu mesmo também irei em breve.

[[v50-2-25]]

^<<v50-2-25,25>>^ Mas, agora, acho necessário enviar-vos Epafrodito, meu irmão, colaborador e companheiro de luta, aquele que enviaram para me servir nas minhas necessidades pessoais,

[[v50-2-26]]

^<<v50-2-26,26>>^ visto que ele deseja muito ver-vos a todos e está deprimido por terem ouvido que ele ficou doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ De facto, ele adoeceu quase a ponto de morrer. Mas Deus teve misericórdia dele; na verdade, não só dele, mas também de mim, para que eu não tivesse uma tristeza após outra.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso envio-o com a maior urgência, para que, quando o virem, se alegrem novamente, e eu fique menos ansioso.

[[v50-2-29]]

^<<v50-2-29,29>>^ Portanto, acolham-no como é costume no Senhor, com toda a alegria, e continuem a prezar homens como ele,

[[v50-2-30]]

^<<v50-2-30,30>>^ porque ele quase morreu por causa da obra de Cristo,^&#42;1^ arriscando a sua vida^&#42;2^ para compensar o facto de não estarem aqui para me prestar serviço.

[NOTE]
====
. Ou, possivelmente: “do Senhor”.
. Ou: “expondo a sua alma ao perigo”.
====

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]