include::./index.adoc[]

[[v31-1-0]]
=== Obadias, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v31-1-1]]

^<<v31-1-1,1>>^ A visão de Obadias:^&#42;1^
Assim diz o Soberano Senhor Jeová a respeito de Edom:
“Ouvimos uma notícia da parte de Jeová,
Enviou-se um mensageiro para dizer às nações:
‘Levantem-se, vamos preparar-nos para a batalha contra ela.’”

[NOTE]
====
. Que significa “servo de Jeová”.
====

[[v31-1-2]]

^<<v31-1-2,2>>^ “Vê! Tornei-te insignificante entre as nações;
Tu és muito desprezado.

[[v31-1-3]]

^<<v31-1-3,3>>^ A arrogância do teu coração enganou-te,
Tu, que resides nos refúgios do rochedo,
Que moras nas alturas, que dizes no teu coração:
‘Quem é que me fará descer para a terra?’

[[v31-1-4]]

^<<v31-1-4,4>>^ Mesmo que fizesses a tua morada no alto^&#42;1^ como a águia,
Ou que colocasses o teu ninho entre as estrelas,
Eu fazia-te descer de lá”, diz Jeová.

[NOTE]
====
. Ou, possivelmente: “voasses alto”.
====

[[v31-1-5]]

^<<v31-1-5,5>>^ “Se viessem até ti ladrões, saqueadores à noite,
Não levariam apenas o que quisessem?
Ou, se viessem até ti vindimadores,
Não deixariam sobrar algumas uvas para respigar?
(Tu serás totalmente destruído!)^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Quanto é que eles destruiriam?”
====

[[v31-1-6]]

^<<v31-1-6,6>>^ Como Esaú foi vasculhado!
Como foram procurados os seus tesouros escondidos!

[[v31-1-7]]

^<<v31-1-7,7>>^ Forçaram-te a ir para a fronteira.
Todos os teus aliados^&#42;1^ te enganaram.
Os homens que estavam em paz contigo derrotaram-te.
Os que comem pão contigo armarão uma rede para te apanhar,
Mas tu não te aperceberás disso.

[NOTE]
====
. Ou: “os que tinham um pacto contigo”.
====

[[v31-1-8]]

^<<v31-1-8,8>>^ Nesse dia”, diz Jeová,
“Não acabarei eu com os sábios de Edom
E com o discernimento da região montanhosa de Esaú?

[[v31-1-9]]

^<<v31-1-9,9>>^ E os teus guerreiros ficarão apavorados, ó Temã,
Visto que cada um deles, na região montanhosa de Esaú, será destruído na matança.

[[v31-1-10]]

^<<v31-1-10,10>>^ Por causa da violência praticada contra o teu irmão Jacó,
A vergonha irá cobrir-te,
E desaparecerás para sempre.

[[v31-1-11]]

^<<v31-1-11,11>>^ No dia em que ficaste só a ver,
No dia em que estranhos levaram o exército de Jacó para o cativeiro,
Quando estrangeiros lhe entraram pelo portão e lançaram sortes sobre Jerusalém,
Tu agiste como um deles.

[[v31-1-12]]

^<<v31-1-12,12>>^ Não te devias alegrar no dia do teu irmão, no dia da sua desgraça,
Não te devias alegrar por causa do povo de Judá, no dia da sua ruína,
E não devias falar tão arrogantemente no dia da sua aflição.

[[v31-1-13]]

^<<v31-1-13,13>>^ Não devias entrar pelo portão do meu povo no dia em que lhes sobreveio o desastre,
Não te devias alegrar com a calamidade do meu povo no dia do seu desastre,
E não te devias apoderar da sua riqueza no dia em que lhes sobreveio o desastre.

[[v31-1-14]]

^<<v31-1-14,14>>^ Não devias ficar nos cruzamentos das estradas para matar os fugitivos,
E não devias entregar os sobreviventes no dia da aflição.

[[v31-1-15]]

^<<v31-1-15,15>>^ Pois está próximo o dia de Jeová contra todas as nações.
Assim como fizeste, assim se fará contigo.
O tratamento que dispensaste a outros retornará sobre a tua própria cabeça.

[[v31-1-16]]

^<<v31-1-16,16>>^ Pois, assim como vocês beberam sobre o meu santo monte,
Todas as nações beberão continuamente.
Beberão e engolirão,
E ficarão como se nunca tivessem existido.

[[v31-1-17]]

^<<v31-1-17,17>>^ No entanto, no monte Sião, estarão os que escaparem,
E ele será sagrado;
E a casa de Jacó recuperará as coisas que lhes pertencem.

[[v31-1-18]]

^<<v31-1-18,18>>^ A casa de Jacó irá tornar-se um fogo,
A casa de José uma chama,
E a casa de Esaú a palha;
Eles irão incendiá-la e consumi-la,
E não haverá nenhum sobrevivente da casa de Esaú,
Pois o próprio Jeová o disse.

[[v31-1-19]]

^<<v31-1-19,19>>^ Eles tomarão posse do Neguebe e da região montanhosa de Esaú,
Da Sefelá e da terra dos filisteus.
Tomarão posse do território de Efraim e do território de Samaria;
E Benjamim tomará posse de Gileade.

[[v31-1-20]]

^<<v31-1-20,20>>^ Aos exilados desta fortificação,^&#42;1^
Ao povo de Israel pertencerá a terra dos cananeus até Sarefá.
E os exilados de Jerusalém que estavam em Sefarade possuirão as cidades do Neguebe.

[NOTE]
====
. Ou: “escarpa”.
====

[[v31-1-21]]

^<<v31-1-21,21>>^ E hão de subir salvadores ao monte Sião
Para julgar a região montanhosa de Esaú;
E o reinado passará a pertencer a Jeová.”

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonas/032-jonas-001.adoc#v32-1-0[Próximo Capítulo &#62;]