include::./index.adoc[]

[[v64-1-0]]
=== 3 João, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v64-1-1]]

^<<v64-1-1,1>>^ O homem idoso,^&#42;1^ a Gaio, o amado, a quem eu amo verdadeiramente.

[NOTE]
====
. Ou: “O Ancião”.
====

[[v64-1-2]]

^<<v64-1-2,2>>^ Amado, oro para que tudo continue a correr bem contigo e que tu tenhas^&#42;1^ boa saúde, assim como tens agora.

[NOTE]
====
. Ou: “a tua alma tenha”.
====

[[v64-1-3]]

^<<v64-1-3,3>>^ Pois alegrei-me muito quando os irmãos vieram e deram testemunho de que te apegas à verdade, de que continuas a andar na verdade.

[[v64-1-4]]

^<<v64-1-4,4>>^ Não tenho alegria^&#42;1^ maior do que esta: ouvir que os meus filhos continuam a andar na verdade.

[NOTE]
====
. Ou, possivelmente: “causa de gratidão”.
====

[[v64-1-5]]

^<<v64-1-5,5>>^ Amado, mostras a tua fidelidade naquilo que fazes pelos irmãos, mesmo que não os conheças.

[[v64-1-6]]

^<<v64-1-6,6>>^ Eles deram testemunho do teu amor perante a congregação. Por favor, encaminha-os na sua viagem de uma maneira digna de Deus.

[[v64-1-7]]

^<<v64-1-7,7>>^ Porque foi a favor do seu nome que saíram, sem receber nada das pessoas das nações.

[[v64-1-8]]

^<<v64-1-8,8>>^ Portanto, temos a obrigação de mostrar hospitalidade a irmãos como esses, para que nos tornemos colaboradores na verdade.

[[v64-1-9]]

^<<v64-1-9,9>>^ Escrevi algo à congregação, mas Diótrefes, que gosta de ocupar o primeiro lugar entre eles, não aceita nada da nossa parte com respeito.

[[v64-1-10]]

^<<v64-1-10,10>>^ É por isso que, se eu for aí, trarei à atenção as coisas que ele tem feito, as calúnias que tem espalhado sobre nós.^&#42;1^ Não satisfeito com isso, ele recusa-se a receber os irmãos com respeito e tenta impedir e expulsar da congregação aqueles que os querem receber.

[NOTE]
====
. Lit.: “tem feito, tagarelando sobre nós com palavras maldosas”.
====

[[v64-1-11]]

^<<v64-1-11,11>>^ Amado, não imites o que é mau, mas imita o que é bom. Quem faz o bem origina-se de Deus. Quem faz o mal não viu a Deus.

[[v64-1-12]]

^<<v64-1-12,12>>^ Todos eles falam bem de Demétrio, inclusive a própria verdade. De facto, nós também testemunhamos a seu favor, e tu sabes que o testemunho que damos é verdadeiro.

[[v64-1-13]]

^<<v64-1-13,13>>^ Eu tinha muitas coisas para te escrever, mas não quero continuar a escrever com pena e tinta.

[[v64-1-14]]

^<<v64-1-14,14>>^ Porém, espero ver-te em breve, e falaremos pessoalmente.
Que a paz esteja contigo.
Os amigos mandam-te saudações. Dá as minhas saudações aos amigos, um por um.^&#42;1^

[NOTE]
====
. Ou: “aos amigos, por nome”.
====

'''

xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-judas/065-judas-001.adoc#v65-1-0[Próximo Capítulo &#62;]