include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-39-1]]

^<<v26-39-1,1>>^ “Filho do homem, profetiza o seguinte contra Gogue: ‘Assim diz o Soberano Senhor Jeová: “Eu estou contra ti, Gogue, maioral-chefe^&#42;1^ de Meseque e Tubal.

[NOTE]
====
. Ou: “príncipe supremo”.
====

[[v26-39-2]]

^<<v26-39-2,2>>^ Farei com que dês meia-volta e vou conduzir-te, fazer com que venhas das partes mais distantes do norte e chegues aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ Derrubarei o arco da tua mão esquerda e farei cair as flechas da tua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Cairás nos montes de Israel, tu e todas as tuas tropas e os povos que te acompanharem. Vou dar-te como comida a todo o tipo de aves de rapina e aos animais selvagens.”’

[[v26-39-5]]

^<<v26-39-5,5>>^ “‘Cairás em campo aberto, pois eu mesmo falei’, diz o Soberano Senhor Jeová.

[[v26-39-6]]

^<<v26-39-6,6>>^ “‘E vou enviar fogo contra Magogue e contra os que moram em segurança nas ilhas, e terão de saber que eu sou Jeová.

[[v26-39-7]]

^<<v26-39-7,7>>^ Tornarei conhecido o meu santo nome entre o meu povo Israel e nunca mais deixarei o meu santo nome ser profanado, e as nações terão de saber que eu sou Jeová, o Santo em Israel.’

[[v26-39-8]]

^<<v26-39-8,8>>^ “‘Sim, isso virá, e vai cumprir-se’, diz o Soberano Senhor Jeová. ‘Esse é o dia de que falei.

[[v26-39-9]]

^<<v26-39-9,9>>^ Os habitantes das cidades de Israel sairão e farão fogueiras com as armas — os escudos grandes e os pequenos,^&#42;1^ os arcos e as flechas, as clavas de guerra^&#42;2^ e as lanças. E eles vão usá-las para fazer fogueiras durante sete anos.

[NOTE]
====
. Ou: “broquéis”, pequenos escudos geralmente usados por arqueiros.
. Ou, possivelmente: “lanças longas”.
====

[[v26-39-10]]

^<<v26-39-10,10>>^ Não precisarão de ir buscar gravetos ao campo, nem de apanhar lenha nas florestas, pois usarão as armas para fazer fogueiras.’
“‘Despojarão aqueles que os despojaram e saquearão aqueles que os saquearam’, diz o Soberano Senhor Jeová.

[[v26-39-11]]

^<<v26-39-11,11>>^ “‘Nesse dia, darei a Gogue uma sepultura lá em Israel, no vale dos que viajam a leste do mar, e ele^&#42;1^ bloqueará o caminho dos que passam. É lá que enterrarão Gogue e todas as suas multidões, e chamarão ao lugar vale de Hamom-Gogue.^&#42;2^

[NOTE]
====
. Isto é, o vale.
. Ou: “vale das Multidões de Gogue”.
====

[[v26-39-12]]

^<<v26-39-12,12>>^ A casa de Israel levará sete meses a enterrá-los, a fim de purificar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Todo o povo desta terra participará em enterrá-los, e isso vai trazer-lhes fama no dia em que eu me glorificar’, diz o Soberano Senhor Jeová.

[[v26-39-14]]

^<<v26-39-14,14>>^ “‘Homens serão designados para percorrer continuamente a terra e enterrar os corpos que tiverem sobrado sobre a superfície da terra, a fim de a purificar. Eles continuarão a busca durante sete meses.

[[v26-39-15]]

^<<v26-39-15,15>>^ Quando aqueles que estiverem a percorrer a terra virem um osso humano, colocarão um marco ao lado dele. Então os designados para fazer o enterro vão enterrá-lo no vale de Hamom-Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ Também haverá ali uma cidade chamada Hamoná.^&#42;1^ E eles purificarão a terra.’

[NOTE]
====
. Que significa “multidões”.
====

[[v26-39-17]]

^<<v26-39-17,17>>^ “Filho do homem, assim diz o Soberano Senhor Jeová: ‘Diz a todos os tipos de aves e a todos os animais selvagens: “Reúnam-se e venham. Ajuntem-se à volta do sacrifício que vos vou preparar, um grande sacrifício nos montes de Israel. Vocês comerão carne e beberão sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comerão a carne dos poderosos e beberão o sangue dos maiorais da terra — carneiros, cordeiros, bodes e touros — todos os animais gordos de Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ Vão empanturrar-se de gordura e vão beber sangue até ficarem bêbados, do sacrifício que vos vou preparar.”’

[[v26-39-20]]

^<<v26-39-20,20>>^ “‘À minha mesa, ficarão saciados com cavalos e condutores de carros, com homens valentes e todo o tipo de guerreiros’, diz o Soberano Senhor Jeová.

[[v26-39-21]]

^<<v26-39-21,21>>^ “‘Vou manifestar a minha glória entre as nações, e todas as nações verão a execução do meu julgamento e a demonstração do meu poder^&#42;1^ entre elas.

[NOTE]
====
. Lit.: “e a minha mão que coloquei”.
====

[[v26-39-22]]

^<<v26-39-22,22>>^ Desse dia em diante, a casa de Israel terá de saber que eu sou Jeová, seu Deus.

[[v26-39-23]]

^<<v26-39-23,23>>^ E as nações terão de saber que a casa de Israel foi para o exílio por causa do seu próprio erro, por me terem sido infiéis. Por isso, escondi deles a minha face e entreguei-os aos seus inimigos, e todos eles caíram pela espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Agi com eles conforme a sua impureza e as suas transgressões, e escondi deles a minha face.’

[[v26-39-25]]

^<<v26-39-25,25>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Trarei de volta os cativos de Jacó e terei misericórdia de toda a casa de Israel, e vou defender zelosamente o^&#42;1^ meu santo nome.

[NOTE]
====
. Lit.: “mostrar devoção exclusiva pelo”.
====

[[v26-39-26]]

^<<v26-39-26,26>>^ Depois de terem sido humilhados por toda a sua infidelidade contra mim, eles morarão na sua terra em segurança, sem que ninguém os faça ter medo.

[[v26-39-27]]

^<<v26-39-27,27>>^ Quando eu os trouxer de volta dentre os povos e os reunir das terras dos seus inimigos, também me santificarei entre eles diante dos olhos de muitas nações.’

[[v26-39-28]]

^<<v26-39-28,28>>^ “‘E terão de saber que eu sou Jeová, o seu Deus, quando eu os enviar para o exílio entre as nações e depois os reunir de volta na sua terra, sem deixar nenhum deles para trás.

[[v26-39-29]]

^<<v26-39-29,29>>^ Nunca mais esconderei deles a minha face, pois derramarei o meu espírito sobre a casa de Israel’, diz o Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]