include::./index.adoc[]

[[v26-31-0]]
=== Ezequiel, 31
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-31-1]]

^<<v26-31-1,1>>^ No décimo primeiro ano, no terceiro mês, no primeiro dia do mês, recebi novamente a palavra de Jeová:

[[v26-31-2]]

^<<v26-31-2,2>>^ “Filho do homem, diz ao Faraó, rei do Egito, e às suas multidões:
‘A quem te comparas em grandeza?

[[v26-31-3]]

^<<v26-31-3,3>>^ Havia um assírio, um cedro do Líbano,
Com belos ramos, semelhante a um bosque que dá sombra, de grande altura;
O seu topo estava entre as nuvens.

[[v26-31-4]]

^<<v26-31-4,4>>^ As águas fizeram-no crescer muito, fontes profundas fizeram-no ficar alto.
Correntes de água cercavam o lugar em que estava plantado;
Canais regavam todas as árvores do campo.

[[v26-31-5]]

^<<v26-31-5,5>>^ Por isso, ele ficou mais alto do que todas as outras árvores do campo.
Os seus galhos multiplicaram-se e os seus ramos estenderam-se,
Por causa do grande volume das suas correntes de água.

[[v26-31-6]]

^<<v26-31-6,6>>^ Todas as aves do céu faziam ninhos nos seus galhos,
Todos os animais selvagens tinham crias debaixo dos seus ramos,
E todas as nações populosas moravam na sua sombra.

[[v26-31-7]]

^<<v26-31-7,7>>^ Ele ficou majestoso em beleza e no tamanho dos seus ramos,
Pois as suas raízes desciam até às águas abundantes.

[[v26-31-8]]

^<<v26-31-8,8>>^ Nenhum outro cedro no jardim de Deus se lhe podia comparar.
Nenhum junípero tinha galhos semelhantes aos dele,
E nenhum plátano tinha ramos como os dele.
Nenhuma outra árvore no jardim de Deus se lhe podia igualar em beleza.

[[v26-31-9]]

^<<v26-31-9,9>>^ Fi-lo belo, com vasta folhagem,
E todas as outras árvores do Éden, o jardim do verdadeiro Deus, o invejavam.’

[[v26-31-10]]

^<<v26-31-10,10>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Visto que ele ficou^&#42;1^ tão alto, com o seu topo entre as nuvens, e visto que o seu coração ficou arrogante por causa da sua altura,

[NOTE]
====
. Lit.: “tu ficaste”.
====

[[v26-31-11]]

^<<v26-31-11,11>>^ eu vou entregá-lo nas mãos do poderoso governante das nações. Este, sem falta, agirá contra ele, e eu vou rejeitá-lo por causa da sua maldade.

[[v26-31-12]]

^<<v26-31-12,12>>^ E estrangeiros, a mais cruel das nações, irão derrubá-lo e abandoná-lo nos montes. A sua folhagem cairá em todos os vales, e os seus ramos partidos ficarão caídos por todos os rios do país. Todos os povos da terra sairão da sua sombra e o abandonarão.

[[v26-31-13]]

^<<v26-31-13,13>>^ Todas as aves do céu residirão sobre o seu tronco caído, e todos os animais selvagens viverão sobre os seus ramos.

[[v26-31-14]]

^<<v26-31-14,14>>^ Isto é para que nenhuma árvore perto das águas fique tão alta ou faça o seu topo subir até às nuvens, e para que nenhuma árvore bem regada alcance a altura destas. Pois todas as árvores serão entregues à morte, às profundezas da terra,^&#42;1^ com os filhos da humanidade, que descem à cova.’^&#42;2^

[NOTE]
====
. Ou: “à terra das profundezas”.
. Ou: “sepultura”.
====

[[v26-31-15]]

^<<v26-31-15,15>>^ “Assim diz o Soberano Senhor Jeová: ‘No dia em que ele descer à Sepultura,^&#42;1^ eu farei com que as pessoas fiquem de luto. Por isso, taparei as águas profundas e bloquearei as suas correntes, para que as águas abundantes fiquem retidas. Vou escurecer o Líbano por causa dele, e todas as árvores do campo murcharão.

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v26-31-16]]

^<<v26-31-16,16>>^ Farei tremer as nações com o estrondo da queda dele, quando eu o fizer descer à Sepultura^&#42;1^ com todos os que descem à cova.^&#42;2^ E todas as árvores do Éden, as mais belas e melhores do Líbano, todas as bem regadas, serão consoladas nas profundezas da terra.^&#42;3^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. Ou: “sepultura”.
. Ou: “na terra das profundezas”.
====

[[v26-31-17]]

^<<v26-31-17,17>>^ Elas desceram com ele à Sepultura,^&#42;1^ aos que foram mortos pela espada, juntamente com os apoiantes dele, que moravam^&#42;2^ na sua sombra entre as nações.’

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. Lit.: “o braço dele, que morava”.
====

[[v26-31-18]]

^<<v26-31-18,18>>^ “‘Qual das árvores do Éden se comparava contigo em glória e grandeza? No entanto, certamente serás levado para baixo, com as árvores do Éden, até às profundezas da terra.^&#42;1^ Irás deitar-te entre os incircuncisos, com os mortos pela espada. Isto é o que acontecerá com o Faraó e com todas as suas multidões’, diz o Soberano Senhor Jeová.”

[NOTE]
====
. Ou: “à terra das profundezas”.
====

'''

xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]