include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-8-1]]

^<<v26-8-1,1>>^ No sexto ano, no sexto mês, no dia cinco do mês, quando eu estava sentado na minha casa e os anciãos de Judá estavam sentados à minha frente, a mão do Soberano Senhor Jeová veio ali sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ Enquanto eu observava, vi uma figura que parecia ter o aspeto de fogo; do que parecia ser a sua cintura para baixo havia fogo, e da cintura para cima a sua aparência era resplandecente, como a de um metal brilhante.^&#42;1^

[NOTE]
====
. Ou: “como o brilho do eletro”, isto é, uma liga brilhante de ouro e prata.
====

[[v26-8-3]]

^<<v26-8-3,3>>^ Então, ele estendeu o que parecia ser uma mão e agarrou-me pelo cabelo, e um espírito carregou-me entre a terra e os céus, e levou-me a Jerusalém, por meio das visões da parte de Deus, até à entrada do portão interno que dá para o norte, onde se encontrava o símbolo^&#42;1^ idólatra do ciúme, que provoca o ciúme.

[NOTE]
====
. Ou: “a imagem”.
====

[[v26-8-4]]

^<<v26-8-4,4>>^ E eu vi ali a glória do Deus de Israel, semelhante à que eu tinha visto no vale.^&#42;1^

[NOTE]
====
. Lit.: “na planície de vale”.
====

[[v26-8-5]]

^<<v26-8-5,5>>^ Depois, ele disse-me: “Filho do homem, por favor, levanta os olhos para o norte.” Portanto, levantei os olhos para o norte, e ali, a norte do portão do altar, na entrada, estava aquele símbolo^&#42;1^ do ciúme.

[NOTE]
====
. Ou: “aquela imagem”.
====

[[v26-8-6]]

^<<v26-8-6,6>>^ E ele disse-me: “Filho do homem, estás a ver as coisas terríveis e detestáveis que a casa de Israel está a fazer aqui, coisas que me fazem afastar do meu santuário? Mas tu verás coisas detestáveis ainda mais terríveis.”

[[v26-8-7]]

^<<v26-8-7,7>>^ A seguir, ele levou-me até à entrada do pátio. Quando eu olhei, vi um buraco na parede.

[[v26-8-8]]

^<<v26-8-8,8>>^ Ele disse-me: “Filho do homem, por favor, aumenta esse buraco na parede.” Eu aumentei o buraco e vi uma entrada.

[[v26-8-9]]

^<<v26-8-9,9>>^ Ele disse-me: “Entra e vê as coisas más e detestáveis que estão a fazer ali.”

[[v26-8-10]]

^<<v26-8-10,10>>^ Assim, entrei e olhei, e vi ali todo o tipo de imagens de animais rasteiros e de animais repugnantes e todos os ídolos repugnantes^&#42;1^ da casa de Israel; eles estavam esculpidos na parede, a toda a volta.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-8-11]]

^<<v26-8-11,11>>^ Diante deles, estavam 70 dos anciãos da casa de Israel, entre os quais estava Jaazanias, filho de Safã. Cada um tinha o seu incensário na mão, e a nuvem perfumada do incenso subia.

[[v26-8-12]]

^<<v26-8-12,12>>^ Ele disse-me: “Filho do homem, vês o que os anciãos da casa de Israel estão a fazer na escuridão, cada um nos aposentos internos onde os seus ídolos estão expostos?^&#42;1^ Pois estão a dizer: ‘Jeová não nos vê. Jeová abandonou o país.’”

[NOTE]
====
. Ou: “nos aposentos internos da sua peça de exibição?”.
====

[[v26-8-13]]

^<<v26-8-13,13>>^ E ele acrescentou: “Verás coisas detestáveis ainda mais terríveis que eles estão a fazer.”

[[v26-8-14]]

^<<v26-8-14,14>>^ Então, ele levou-me até à entrada do portão norte da casa de Jeová, e vi ali mulheres sentadas, a chorarem pelo deus Tamuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ Ele disse-me também: “Estás a ver isto, filho do homem? Verás coisas detestáveis ainda mais terríveis do que estas.”

[[v26-8-16]]

^<<v26-8-16,16>>^ Portanto, ele levou-me ao pátio interno da casa de Jeová. Ali na entrada do templo de Jeová, entre o pórtico e o altar, havia cerca de 25 homens de costas para o templo de Jeová e com o rosto virado para o leste; eles estavam a curvar-se para o sol, no leste.

[[v26-8-17]]

^<<v26-8-17,17>>^ Ele disse-me: “Estás a ver isto, filho do homem? Será que não basta a casa de Judá fazer estas coisas detestáveis, encher o país de violência e continuar a ofender-me? Eles estão a estender o ramo^&#42;1^ ao meu nariz.

[NOTE]
====
. Aparentemente, um ramo usado na adoração idólatra.
====

[[v26-8-18]]

^<<v26-8-18,18>>^ Portanto, agirei com furor. O meu olho não terá dó, nem terei compaixão. Mesmo que clamem bem alto aos meus ouvidos, não os ouvirei.”

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]