include::./index.adoc[]

[[v26-38-0]]
=== Ezequiel, 38
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-38-1]]

^<<v26-38-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-38-2]]

^<<v26-38-2,2>>^ “Filho do homem, vira o teu rosto contra Gogue da terra de Magogue, o maioral-chefe^&#42;1^ de Meseque e Tubal, e profetiza contra ele.

[NOTE]
====
. Ou: “príncipe supremo”.
====

[[v26-38-3]]

^<<v26-38-3,3>>^ Diz: ‘Assim diz o Soberano Senhor Jeová: “Eu estou contra ti, ó Gogue, maioral-chefe^&#42;1^ de Meseque e Tubal.

[NOTE]
====
. Ou: “príncipe supremo”.
====

[[v26-38-4]]

^<<v26-38-4,4>>^ Farei com que dês meia-volta, porei ganchos nas tuas mandíbulas e farei com que saias com toda a tua força militar, cavalos e cavaleiros, todos vestidos de esplendor, um exército numeroso com escudos grandes e pequenos,^&#42;1^ todos eles armados com espadas.

[NOTE]
====
. Ou: “broquéis”, pequenos escudos geralmente usados por arqueiros.
====

[[v26-38-5]]

^<<v26-38-5,5>>^ A Pérsia, a Etiópia e Pute estão com eles, todos com escudos e capacetes;

[[v26-38-6]]

^<<v26-38-6,6>>^ também Gomer e todas as suas tropas, a casa de Togarma, das partes mais distantes do norte, com todas as suas tropas — sim, muitos povos estão contigo.

[[v26-38-7]]

^<<v26-38-7,7>>^ “‘“Aprontem-se, estejam preparados, tu e todos os exércitos que se juntaram a ti, e tu serás o comandante^&#42;1^ deles.

[NOTE]
====
. Lit.: “guarda”.
====

[[v26-38-8]]

^<<v26-38-8,8>>^ “‘“Receberás atenção^&#42;1^ depois de muitos dias. No fim dos anos, invadirás a terra cujo povo foi restabelecido da devastação da espada, que foi reunido dentre muitos povos e trazido aos montes de Israel, os quais tinham ficado devastados durante muito tempo. Os habitantes desta terra foram trazidos de volta dentre as nações e todos eles moram em segurança.

[NOTE]
====
. Ou: “Serás convocado”.
====

[[v26-38-9]]

^<<v26-38-9,9>>^ Virás contra eles como uma tempestade e cobrirás a terra como as nuvens, tu, todas as tuas tropas e os muitos povos que te acompanham.”’

[[v26-38-10]]

^<<v26-38-10,10>>^ “Assim diz o Soberano Senhor Jeová: ‘Nesse dia, surgirão ideias no teu coração e planearás uma trama perversa.

[[v26-38-11]]

^<<v26-38-11,11>>^ Dirás: “Invadirei a terra de povoados desprotegidos.^&#42;1^ Irei contra os que vivem em segurança, sem perturbação; todos eles moram em povoados sem muralhas, trancas ou portões.”

[NOTE]
====
. Ou: “do campo aberto, da zona rural”.
====

[[v26-38-12]]

^<<v26-38-12,12>>^ O teu objetivo será tomar muito despojo e espólio, atacar os lugares devastados agora repovoados e um povo que foi reunido dentre as nações e que está a acumular riquezas e bens, a morar no meio da terra.

[[v26-38-13]]

^<<v26-38-13,13>>^ “‘Sabá e Dedã, os mercadores de Társis e todos os seus guerreiros^&#42;1^ irão dizer-te: “Por acaso, farás esta invasão para tomares muito despojo e espólio? Reuniste os teus exércitos para levares prata e ouro, para saqueares riquezas e bens, para tomares um enorme despojo?”’

[NOTE]
====
. Ou: “leões novos jubados”.
====

[[v26-38-14]]

^<<v26-38-14,14>>^ “Portanto, filho do homem, profetiza o seguinte a Gogue: ‘Assim diz o Soberano Senhor Jeová: “Nesse dia, quando o meu povo Israel estiver a morar em segurança, será que não o saberás?

[[v26-38-15]]

^<<v26-38-15,15>>^ Virás do teu lugar, das partes mais distantes do norte, acompanhado de muitos povos, todos montados em cavalos, um grande exército, uma numerosa força militar.

[[v26-38-16]]

^<<v26-38-16,16>>^ Virás contra o meu povo Israel como nuvens que cobrem a terra. Na parte final dos dias, vou trazer-te contra a minha terra, para que as nações me conheçam quando eu me santificar diante dos seus olhos por meio de ti, ó Gogue.”’

[[v26-38-17]]

^<<v26-38-17,17>>^ “Assim diz o Soberano Senhor Jeová: ‘Não és tu aquele de quem falei no passado por meio dos meus servos, os profetas de Israel, que durante muitos anos profetizaram que serias trazido contra eles?’

[[v26-38-18]]

^<<v26-38-18,18>>^ “‘Nesse dia, o dia em que Gogue invadir a terra de Israel’, diz o Soberano Senhor Jeová, ‘o meu grande furor irá acender-se.

[[v26-38-19]]

^<<v26-38-19,19>>^ No meu zelo, no fogo da minha fúria, eu falarei; e, nesse dia, ocorrerá um grande terramoto na terra de Israel.

[[v26-38-20]]

^<<v26-38-20,20>>^ Por minha causa, tremerão os peixes do mar, as aves do céu, os animais selvagens, todos os répteis que rastejam sobre o solo e todos os homens na superfície da terra. Os montes serão derrubados, os penhascos irão desmoronar-se, e todas as muralhas cairão por terra.’

[[v26-38-21]]

^<<v26-38-21,21>>^ “‘Vou convocar contra Gogue uma espada em todas as minhas montanhas’, diz o Soberano Senhor Jeová. ‘A espada de cada um será contra o seu próprio irmão.

[[v26-38-22]]

^<<v26-38-22,22>>^ Vou trazer o meu julgamento^&#42;1^ contra ele com peste e derramamento de sangue. Farei cair uma chuva torrencial, pedras de granizo, fogo e enxofre sobre ele, sobre as suas tropas e sobre os muitos povos que o acompanham.

[NOTE]
====
. Ou: “Vou entrar em juízo”.
====

[[v26-38-23]]

^<<v26-38-23,23>>^ Certamente, vou magnificar-me, santificar-me e dar-me a conhecer diante dos olhos de muitas nações; e terão de saber que eu sou Jeová.’

'''

xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]