include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-17-1]]

^<<v26-17-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-17-2]]

^<<v26-17-2,2>>^ “Filho do homem, propõe um enigma e conta uma parábola^&#42;1^ sobre a casa de Israel.

[NOTE]
====
. Ou: “um provérbio”.
====

[[v26-17-3]]

^<<v26-17-3,3>>^ Diz: ‘Assim diz o Soberano Senhor Jeová: “A grande águia, com grandes asas, penas compridas e plumagem abundante e colorida, chegou ao Líbano e tirou o topo do cedro.

[[v26-17-4]]

^<<v26-17-4,4>>^ Arrancou o seu rebento mais alto, levou-o para a terra dos comerciantes^&#42;1^ e plantou-o numa cidade de comerciantes.

[NOTE]
====
. Lit.: “terra de Canaã”.
====

[[v26-17-5]]

^<<v26-17-5,5>>^ Então, pegou numa semente da terra e plantou-a num campo fértil. Plantou-a como um salgueiro à beira de muitas águas.

[[v26-17-6]]

^<<v26-17-6,6>>^ Portanto, ela brotou e tornou-se uma videira baixa e viçosa, com a folhagem virada para dentro e as raízes a crescerem debaixo dela. Assim, tornou-se uma videira, produziu rebentos e lançou ramos.

[[v26-17-7]]

^<<v26-17-7,7>>^ “‘“E surgiu outra grande águia, com grandes asas e longas penas. Em seguida, a videira estendeu-lhe avidamente as suas raízes, para longe dos canteiros em que estava plantada, e estendeu-lhe a sua folhagem, a fim de que ela a regasse.

[[v26-17-8]]

^<<v26-17-8,8>>^ Ela já tinha sido plantada num bom campo, perto de muitas águas, para que produzisse ramos, desse fruto e se tornasse uma videira majestosa.”’

[[v26-17-9]]

^<<v26-17-9,9>>^ “Diz: ‘Assim diz o Soberano Senhor Jeová: “Será que ela vai vingar? Não lhe vão arrancar as raízes, fazer o seu fruto apodrecer e os seus rebentos murcharem? Ela vai ficar tão seca que não será necessário um braço forte nem muita gente para a arrancar pelas raízes.

[[v26-17-10]]

^<<v26-17-10,10>>^ Embora transplantada, será que vai vingar? Não se secará completamente quando o vento leste soprar sobre ela? Ela vai secar-se no canteiro em que brotou.”’”

[[v26-17-11]]

^<<v26-17-11,11>>^ E recebi novamente a palavra de Jeová:

[[v26-17-12]]

^<<v26-17-12,12>>^ “Por favor, diz à casa rebelde: ‘Não percebem o que estas coisas significam?’ Diz o seguinte: ‘Vejam! O rei de Babilónia foi a Jerusalém, pegou no seu rei e nos seus príncipes, e trouxe-os consigo para Babilónia.

[[v26-17-13]]

^<<v26-17-13,13>>^ Além disso, escolheu alguém da descendência^&#42;1^ real, fez um pacto com ele e pô-lo sob um juramento. Depois, levou os homens de destaque do país,

[NOTE]
====
. Lit.: “semente”.
====

[[v26-17-14]]

^<<v26-17-14,14>>^ para que o reino fosse rebaixado e não se conseguisse erguer, de modo que só continuaria a existir se guardasse o pacto que tinha feito.

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas o rei,^&#42;1^ finalmente, rebelou-se contra ele,^&#42;2^ enviando os seus mensageiros ao Egito, para obter cavalos e um grande exército. Será bem-sucedido? Escapará da punição aquele que está a fazer estas coisas? Será que ele pode violar o pacto e ainda assim escapar?’

[NOTE]
====
. Isto é, Zedequias.
. Isto é, Nabucodonosor.
====

[[v26-17-16]]

^<<v26-17-16,16>>^ “‘“Tão certo como eu vivo”, diz o Soberano Senhor Jeová, “ele^&#42;1^ morrerá em Babilónia, onde mora o rei^&#42;2^ que o fez reinar, aquele cujo juramento ele desprezou e cujo pacto violou.

[NOTE]
====
. Isto é, Zedequias.
. Isto é, Nabucodonosor.
====

[[v26-17-17]]

^<<v26-17-17,17>>^ O grande exército e as numerosas tropas do Faraó não serão de ajuda na guerra, quando se levantarem rampas de ataque e se construírem muros de cerco para destruir muitas vidas.^&#42;1^

[NOTE]
====
. Ou: “almas”.
====

[[v26-17-18]]

^<<v26-17-18,18>>^ Ele desprezou um juramento e violou um pacto. Apesar de ter feito uma promessa,^&#42;1^ fez todas estas coisas. Por isso, ele não escapará.”’

[NOTE]
====
. Lit.: “dado a sua mão”.
====

[[v26-17-19]]

^<<v26-17-19,19>>^ “‘Portanto, assim diz o Soberano Senhor Jeová: “Tão certo como eu vivo, farei recair sobre a sua própria cabeça as consequências de ter desprezado o meu juramento e de ter violado o meu pacto.

[[v26-17-20]]

^<<v26-17-20,20>>^ Lançarei sobre ele a minha rede, e ele será apanhado na minha rede de caça. Vou trazê-lo para Babilónia e entrarei ali em juízo contra ele por causa da infidelidade que cometeu contra mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ Todos os fugitivos das suas tropas cairão pela espada, e os que restarem serão espalhados em todas as direções.^&#42;1^ Então, vocês terão de saber que fui eu, Jeová, que falei.”’

[NOTE]
====
. Lit.: “a todo o vento”.
====

[[v26-17-22]]

^<<v26-17-22,22>>^ “‘Assim diz o Soberano Senhor Jeová: “Tirarei um rebento do topo do alto cedro e irei plantá-lo; dentre os seus raminhos que estão no topo, arrancarei um rebento tenro e eu mesmo o plantarei num monte alto e elevado.

[[v26-17-23]]

^<<v26-17-23,23>>^ Eu irei plantá-lo num alto monte de Israel; os seus ramos crescerão, ele dará fruto e irá tornar-se um cedro majestoso. E aves de todo o tipo morarão debaixo dele e residirão à sombra da sua folhagem.

[[v26-17-24]]

^<<v26-17-24,24>>^ E todas as árvores do campo terão de saber que fui eu, Jeová, que rebaixei a árvore alta e enalteci a árvore baixa; sequei a árvore viçosa e fiz florescer a árvore seca. Fui eu, Jeová, que falei e fiz isso.”’”

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]