include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-43-1]]

^<<v26-43-1,1>>^ Então, ele levou-me ao portão que dá para o leste.

[[v26-43-2]]

^<<v26-43-2,2>>^ Ali eu vi a glória do Deus de Israel vindo do leste, e a sua voz era como o som de fortes águas; e a terra ficou iluminada pela sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ O que vi era como a visão que tive quando vim^&#42;1^ para arruinar a cidade,^&#42;2^ como o que eu tinha visto perto do rio Quebar; e prostrei-me com o rosto por terra.

[NOTE]
====
. Ou, possivelmente: “ele veio”.
. Pelos vistos, por profetizar a sua destruição.
====

[[v26-43-4]]

^<<v26-43-4,4>>^ Em seguida, a glória de Jeová entrou no templo^&#42;1^ pelo portão que dava para o leste.

[NOTE]
====
. Lit.: “na casa”.
====

[[v26-43-5]]

^<<v26-43-5,5>>^ E um espírito levantou-me e levou-me ao pátio interno, e eu vi que o templo tinha ficado cheio da glória de Jeová.

[[v26-43-6]]

^<<v26-43-6,6>>^ Então, ouvi alguém falar comigo de dentro do templo, e o homem veio e ficou ao meu lado.

[[v26-43-7]]

^<<v26-43-7,7>>^ Ele disse-me:
“Filho do homem, este é o lugar do meu trono e o lugar para a planta dos meus pés, onde residirei entre o povo de Israel para sempre. A casa de Israel não voltará a profanar o meu santo nome, nem eles nem os seus reis, com a sua prostituição espiritual e com os cadáveres dos seus reis mortos.^&#42;1^

[NOTE]
====
. Lit.: “na morte deles”.
====

[[v26-43-8]]

^<<v26-43-8,8>>^ Eles colocaram o limiar destes ao pé do meu limiar e as ombreiras destes ao lado das minhas ombreiras, com apenas uma parede entre mim e eles, profanando assim o meu santo nome com as coisas detestáveis que fizeram, de modo que os exterminei na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora, que afastem de mim a sua prostituição espiritual e os cadáveres dos seus reis, e eu residirei entre eles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ “Filho do homem, descreve o templo à casa de Israel, para que se envergonhem dos erros que cometeram; e eles devem estudar a sua planta.^&#42;1^

[NOTE]
====
. Lit.: “medir o modelo”.
====

[[v26-43-11]]

^<<v26-43-11,11>>^ Se eles se envergonharem de tudo o que fizeram, informa-os sobre a planta do templo, a disposição das suas partes, as suas saídas e as suas entradas. Mostra-lhes todas as suas plantas e os seus estatutos, as suas plantas e as suas leis. Põe isso tudo por escrito diante dos seus olhos, para que observem toda a sua planta e cumpram os seus estatutos.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei do templo: toda a área à volta do cume do monte é santíssima. Sim, esta é a lei do templo.

[[v26-43-13]]

^<<v26-43-13,13>>^ “Estas são as medidas do altar em côvados (cada côvado tinha uma largura da mão a mais).^&#42;1^ A altura da base é de um côvado, e a largura do seu contorno é de um côvado. Em todo o seu contorno, há uma borda de um palmo^&#42;2^ de largura. Esta é a base do altar.

[NOTE]
====
. Isto refere-se a côvados longos. Veja o Ap. B14.
. Cerca de 22,2 cm. Veja o Ap. B14.
====

[[v26-43-14]]

^<<v26-43-14,14>>^ Desde a base, que está no chão, até ao topo da plataforma inferior são dois côvados, e a largura do seu contorno é de um côvado. Desta plataforma menor até ao topo da plataforma maior, são quatro côvados, e a largura do seu contorno é de um côvado.

[[v26-43-15]]

^<<v26-43-15,15>>^ O braseiro do altar tem quatro côvados de altura, e os quatro chifres projetam-se do braseiro do altar para cima.

[[v26-43-16]]

^<<v26-43-16,16>>^ O braseiro do altar é quadrado, com 12 côvados de comprimento e 12 côvados de largura.

[[v26-43-17]]

^<<v26-43-17,17>>^ Cada um dos quatro lados da plataforma^&#42;1^ mede 14 côvados, em comprimento e em largura; a borda à volta tem meio côvado, e a sua base tem um côvado em todos os lados.
“E os degraus do altar estão virados para o leste.”

[NOTE]
====
. Isto é, da “plataforma maior” mencionada no v. 14.
====

[[v26-43-18]]

^<<v26-43-18,18>>^ Então, ele disse-me: “Filho do homem, assim diz o Soberano Senhor Jeová: ‘Estas são as instruções a seguir quando o altar for construído, para se oferecerem sobre ele ofertas queimadas e se aspergir sangue sobre ele.’

[[v26-43-19]]

^<<v26-43-19,19>>^ “‘Deves dar um novilho do rebanho como oferta pelo pecado aos sacerdotes levíticos descendentes de Zadoque, que se aproximam de mim para me servir’, diz o Soberano Senhor Jeová.

[[v26-43-20]]

^<<v26-43-20,20>>^ ‘Deves pegar num pouco do seu sangue e colocá-lo sobre os quatro chifres do altar, sobre os quatro cantos da plataforma e sobre a borda a toda a volta, a fim de o purificar de pecado e fazer expiação por ele.

[[v26-43-21]]

^<<v26-43-21,21>>^ Depois, pega no novilho da oferta pelo pecado para o queimar no lugar do templo determinado para isso, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ No segundo dia, oferecerás um bode sadio como oferta pelo pecado, e o altar será purificado de pecado, assim como foi purificado de pecado com o novilho.’

[[v26-43-23]]

^<<v26-43-23,23>>^ “‘Quando acabares de o purificar de pecado, oferecerás um novilho sadio da manada e um carneiro sadio do rebanho.

[[v26-43-24]]

^<<v26-43-24,24>>^ Deves apresentá-los a Jeová, e os sacerdotes devem deitar-lhes sal e oferecê-los como oferta queimada a Jeová.

[[v26-43-25]]

^<<v26-43-25,25>>^ Durante sete dias, oferecerás um bode por dia como oferta pelo pecado, assim como um novilho da manada e um carneiro do rebanho; oferecerás animais sem defeito.^&#42;1^

[NOTE]
====
. Ou: “perfeitos”.
====

[[v26-43-26]]

^<<v26-43-26,26>>^ Eles devem fazer expiação pelo altar durante sete dias, e devem purificá-lo e inaugurá-lo.

[[v26-43-27]]

^<<v26-43-27,27>>^ Depois de terminarem esses dias, do oitavo dia em diante, os sacerdotes oferecerão no altar as suas ofertas queimadas^&#42;1^ e os seus sacrifícios de participação em comum, e eu irei agradar-me de vocês’, diz o Soberano Senhor Jeová.”

[NOTE]
====
. Isto é, as ofertas queimadas do povo.
====

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]