include::./index.adoc[]

[[v26-1-0]]
=== Ezequiel, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-1-1]]

^<<v26-1-1,1>>^ No trigésimo ano, no quarto mês, no dia cinco do mês, quando eu estava entre o povo exilado ao pé do rio Quebar, os céus abriram-se e comecei a ter visões de Deus.

[[v26-1-2]]

^<<v26-1-2,2>>^ No dia cinco do mês, no quinto ano de exílio do rei Joaquim,

[[v26-1-3]]

^<<v26-1-3,3>>^ Ezequiel,^&#42;1^ filho do sacerdote Buzi, recebeu a palavra de Jeová ao pé do rio Quebar, na terra dos caldeus. Ali, a mão de Jeová veio sobre ele.

[NOTE]
====
. Que significa “Deus fortalece”.
====

[[v26-1-4]]

^<<v26-1-4,4>>^ Enquanto eu olhava, vi um vento tempestuoso a vir do norte, e havia uma nuvem enorme e fogo relampejante^&#42;1^ com uma forte luz ao redor, e no meio do fogo havia o que parecia ser um metal brilhante.^&#42;2^

[NOTE]
====
. Ou: “e relâmpagos”.
. Ou: “eletro”, isto é, uma liga brilhante de ouro e prata.
====

[[v26-1-5]]

^<<v26-1-5,5>>^ Dentro do fogo havia o que pareciam ser quatro criaturas viventes, e cada uma delas tinha a aparência de um homem.

[[v26-1-6]]

^<<v26-1-6,6>>^ Cada uma tinha quatro faces e quatro asas.

[[v26-1-7]]

^<<v26-1-7,7>>^ Os seus pés eram retos, e a planta dos seus pés era como as de um bezerro, e eles brilhavam como cobre polido.

[[v26-1-8]]

^<<v26-1-8,8>>^ Elas tinham mãos humanas debaixo das suas asas, em todos os quatro lados. As quatro tinham faces e asas.

[[v26-1-9]]

^<<v26-1-9,9>>^ As suas asas tocavam umas nas outras. Quando avançavam, não se viravam; cada uma delas ia diretamente para a frente.

[[v26-1-10]]

^<<v26-1-10,10>>^ As suas faces tinham a seguinte aparência: cada uma das quatro tinha uma face de homem, com uma face de leão à direita e uma face de touro à esquerda, e cada uma tinha uma face de águia.

[[v26-1-11]]

^<<v26-1-11,11>>^ Assim eram as suas faces. As suas asas ficavam estendidas acima delas. Cada uma tinha duas asas que se tocavam e duas asas que lhes cobriam o corpo.

[[v26-1-12]]

^<<v26-1-12,12>>^ Cada uma delas ia diretamente para a frente, para onde quer que o espírito as impelisse. Quando avançavam, não se viravam.

[[v26-1-13]]

^<<v26-1-13,13>>^ As criaturas viventes pareciam brasas de fogo. Algo que parecia ser tochas de fogo ardente movia-se para lá e para cá entre as criaturas viventes, e do fogo saíam relâmpagos.

[[v26-1-14]]

^<<v26-1-14,14>>^ E, quando as criaturas viventes iam e vinham, elas movimentavam-se como relâmpagos.

[[v26-1-15]]

^<<v26-1-15,15>>^ Enquanto eu observava as criaturas viventes, vi no chão uma roda ao lado de cada uma das criaturas viventes de quatro faces.

[[v26-1-16]]

^<<v26-1-16,16>>^ As rodas e a sua estrutura pareciam brilhar como o crisólito, e as quatro pareciam iguais. A sua aparência e estrutura eram como se uma roda estivesse dentro de outra.^&#42;1^

[NOTE]
====
. Possivelmente, eram rodas com o mesmo diâmetro, atravessadas uma no meio da outra em ângulo reto.
====

[[v26-1-17]]

^<<v26-1-17,17>>^ Quando se moviam, podiam ir em qualquer uma das quatro direções, sem se virarem enquanto avançavam.

[[v26-1-18]]

^<<v26-1-18,18>>^ Os seus aros tinham uma altura impressionante, e os aros das quatro estavam cheios de olhos em toda a volta.

[[v26-1-19]]

^<<v26-1-19,19>>^ Sempre que as criaturas viventes se moviam, as rodas moviam-se com elas; quando as criaturas viventes se elevavam do chão, as rodas também se elevavam.

[[v26-1-20]]

^<<v26-1-20,20>>^ Elas iam para onde o espírito as impelia, para onde quer que o espírito fosse. As rodas também se elevavam com elas, pois o espírito que agia nas criaturas viventes^&#42;1^ também estava nas rodas.

[NOTE]
====
. Lit.: “o espírito da criatura vivente”.
====

[[v26-1-21]]

^<<v26-1-21,21>>^ Quando elas se moviam, as rodas moviam-se; quando paravam, as rodas paravam; e, quando se elevavam do chão, as rodas também se elevavam com elas, pois o espírito que agia nas criaturas viventes também estava nas rodas.

[[v26-1-22]]

^<<v26-1-22,22>>^ Acima da cabeça das criaturas viventes, havia o que parecia ser uma superfície cintilante e impressionante como gelo, estendida acima da cabeça delas.

[[v26-1-23]]

^<<v26-1-23,23>>^ Por baixo da superfície, as suas asas eram retas,^&#42;1^ uma em direção à outra. Cada uma tinha duas asas para cobrir um lado do corpo e duas para cobrir o outro lado.

[NOTE]
====
. Ou, possivelmente: “estendiam-se em linha reta”.
====

[[v26-1-24]]

^<<v26-1-24,24>>^ Quando ouvi o som das suas asas, era como o som de fortes águas, como a voz do Todo-Poderoso. Quando elas avançavam, o barulho era semelhante ao de um exército. Quando paravam, baixavam as asas.

[[v26-1-25]]

^<<v26-1-25,25>>^ Uma voz vinha de cima da superfície que havia acima da cabeça delas. (Quando elas paravam, baixavam as asas.)

[[v26-1-26]]

^<<v26-1-26,26>>^ Sobre a superfície que estava acima da cabeça delas, havia algo semelhante a uma pedra de safira, que parecia um trono. Sentado no trono, no alto, estava alguém que parecia um homem.

[[v26-1-27]]

^<<v26-1-27,27>>^ Vi algo a reluzir como um metal brilhante, como um fogo que irradiava do que parecia ser a sua cintura para cima; e, da sua cintura para baixo, vi algo semelhante a fogo. Havia uma luz resplandecente em todo o seu redor,

[[v26-1-28]]

^<<v26-1-28,28>>^ como a de um arco-íris, numa nuvem, num dia chuvoso. Essa era a aparência da luz resplandecente à sua volta. Parecia a glória de Jeová. Ao ver isso, prostrei-me com o rosto por terra e comecei a ouvir a voz de alguém a falar.

'''

xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]