include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-5-1]]

^<<v26-5-1,1>>^ “Filho do homem, pega numa espada afiada e usa-a como navalha de barbeiro. Rapa a tua cabeça e a tua barba, e, depois, pesa o cabelo e a barba numa balança e divide-os em porções.

[[v26-5-2]]

^<<v26-5-2,2>>^ Quando terminarem os dias do cerco, queimarás uma terça parte deles no fogo, dentro da cidade. Então pegarás em outra terça parte e irás golpeá-la com a espada ao redor da cidade,^&#42;1^ e a última terça parte espalharás ao vento, e eu puxarei da espada para os perseguir.

[NOTE]
====
. Lit.: “dela”.
====

[[v26-5-3]]

^<<v26-5-3,3>>^ “Pega também em alguns fios e guarda-os nas dobras^&#42;1^ da tua roupa.

[NOTE]
====
. Ou: “saias”.
====

[[v26-5-4]]

^<<v26-5-4,4>>^ E pega em mais alguns fios, lança-os no fogo e queima-os. Este fogo irá espalhar-se por toda a casa de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ “Assim diz o Soberano Senhor Jeová: ‘Isto é Jerusalém. Eu coloquei-a no meio das nações, com países ao seu redor.

[[v26-5-6]]

^<<v26-5-6,6>>^ Contudo, ela rebelou-se contra as minhas decisões judiciais e contra os meus decretos, agindo pior do que as nações e os países ao seu redor. Pois eles rejeitaram as minhas decisões judiciais e não andaram nos meus decretos.’

[[v26-5-7]]

^<<v26-5-7,7>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Visto que foram mais indisciplinados do que as nações ao vosso redor, e não andaram nos meus decretos nem cumpriram as minhas decisões judiciais, mas, em vez disso, seguiram as decisões judiciais das nações ao vosso redor,

[[v26-5-8]]

^<<v26-5-8,8>>^ assim diz o Soberano Senhor Jeová: “Estou contra ti, ó cidade, e eu mesmo vou executar o julgamento no teu meio, diante dos olhos das nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ Vou fazer contigo o que nunca fiz antes, nem nunca mais voltarei a fazer, por causa de todas as tuas práticas detestáveis.

[[v26-5-10]]

^<<v26-5-10,10>>^ “‘“Assim, os pais que estiverem no teu meio comerão os próprios filhos, e os filhos comerão os seus pais. E eu executarei no teu meio o julgamento, e o que restar de ti espalharei em todas as direções.”’^&#42;1^

[NOTE]
====
. Lit.: “a todo o vento”.
====

[[v26-5-11]]

^<<v26-5-11,11>>^ “‘Portanto, tão certo como eu vivo’, diz o Soberano Senhor Jeová, ‘visto que profanaste o meu santuário com todos os teus ídolos repugnantes e todas as tuas práticas detestáveis, eu vou rejeitar-te;^&#42;1^ o meu olho não terá dó, nem terei compaixão.

[NOTE]
====
. Ou: “diminuir-te”.
====

[[v26-5-12]]

^<<v26-5-12,12>>^ Um terço dos teus habitantes morrerá de peste^&#42;1^ ou perecerá no teu meio por causa da fome. Outro terço cairá pela espada ao teu redor. E o último terço espalharei em todas as direções,^&#42;2^ e puxarei da espada para os perseguir.

[NOTE]
====
. Ou: “doença”.
. Lit.: “a todo o vento”.
====

[[v26-5-13]]

^<<v26-5-13,13>>^ Então, a minha ira chegará ao fim, o meu furor contra eles desaparecerá, e ficarei satisfeito. E eles terão de saber que eu, Jeová, falei por causa da minha insistência em devoção exclusiva, quando eu terminar de dar vazão ao meu furor contra eles.

[[v26-5-14]]

^<<v26-5-14,14>>^ “‘Farei de ti um lugar devastado e um alvo de desprezo entre as nações ao teu redor e aos olhos de todos os que passarem por ti.

[[v26-5-15]]

^<<v26-5-15,15>>^ Irás tornar-te objeto de desprezo e de gozo, exemplo de aviso e motivo de pavor para as nações ao teu redor, quando eu executar o julgamento contra ti com ira, furor e severas punições. Fui eu, Jeová, que falei.

[[v26-5-16]]

^<<v26-5-16,16>>^ “‘Atirarei contra eles as flechas mortais da fome para os destruir. As flechas que atiro acabarão convosco. Agravarei a vossa fome por cortar o vosso suprimento de alimento.^&#42;1^

[NOTE]
====
. Lit.: “quebrar o vosso bastão de pão”. Possivelmente, refere-se aos bastões em que se penduravam pães em forma de anel.
====

[[v26-5-17]]

^<<v26-5-17,17>>^ Enviarei contra vocês fome e animais ferozes, e irão deixar-vos sem filhos. A peste e o derramamento de sangue irão arrasar-te, e trarei contra ti a espada. Fui eu, Jeová, que falei.’”

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]