include::./index.adoc[]

[[v26-9-0]]
=== Ezequiel, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-9-1]]

^<<v26-9-1,1>>^ Então, ele clamou em voz alta aos meus ouvidos: “Convoquem os que trarão punição sobre a cidade, cada um com a sua arma de destruição na mão!”

[[v26-9-2]]

^<<v26-9-2,2>>^ Eu vi seis homens a virem da direção do portão superior que dá para o norte, cada um com a sua arma esmagadora na mão; e havia entre eles um homem vestido de linho, com um tinteiro de secretário^&#42;1^ à cintura. Eles entraram e ficaram ao pé do altar de cobre.

[NOTE]
====
. Ou: “estojo de escriba”.
====

[[v26-9-3]]

^<<v26-9-3,3>>^ A seguir, a glória do Deus de Israel elevou-se de onde estava, acima dos querubins, e foi para a soleira da entrada da casa. E ele chamou o homem vestido de linho, que tinha o tinteiro de secretário à cintura.

[[v26-9-4]]

^<<v26-9-4,4>>^ Jeová disse-lhe: “Percorre a cidade, percorre Jerusalém, e marca com um sinal a testa dos homens que suspiram e gemem por causa de todas as coisas detestáveis que estão a ser feitas na cidade.”

[[v26-9-5]]

^<<v26-9-5,5>>^ E, aos outros, ouvi-o dizer: “Percorram a cidade atrás dele e golpeiem as pessoas. Não deixem o vosso olho ter dó, nem tenham compaixão.

[[v26-9-6]]

^<<v26-9-6,6>>^ Devem matar todos os idosos, os rapazes, as raparigas,^&#42;1^ as mulheres e as crianças. Mas não se aproximem de ninguém que tenha o sinal. Devem começar pelo meu santuário.” Portanto, eles começaram pelos anciãos que estavam à frente da casa.

[NOTE]
====
. Ou: “virgens”.
====

[[v26-9-7]]

^<<v26-9-7,7>>^ Depois, ele disse-lhes: “Profanem a casa e encham os pátios de mortos. Vão!” Assim, eles saíram e começaram a matar os habitantes da cidade.

[[v26-9-8]]

^<<v26-9-8,8>>^ Enquanto matavam as pessoas, só eu sobrei, e, então, prostrei-me com o rosto por terra e clamei: “Ai, Soberano Senhor Jeová! Vais destruir todos os que restam de Israel, derramando o teu furor sobre Jerusalém?”

[[v26-9-9]]

^<<v26-9-9,9>>^ Então, ele respondeu-me: “O erro da casa de Israel e de Judá é muito, muito grande. O país está cheio de derramamento de sangue, e a cidade está cheia de corrupção. Pois eles dizem: ‘Jeová abandonou o país, Jeová não está a ver.’

[[v26-9-10]]

^<<v26-9-10,10>>^ Quanto a mim, o meu olho não terá dó, nem terei compaixão. Farei as consequências do seu proceder recair sobre a sua própria cabeça.”

[[v26-9-11]]

^<<v26-9-11,11>>^ Em seguida, vi o homem vestido de linho, que tinha o tinteiro à cintura, voltar e dizer: “Fiz exatamente como me ordenaste.”

'''

xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[&#60; Capítulo Anterior] | <<v26-9-0,Topo>> | xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[Próximo Capítulo &#62;]