include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-12-1]]

^<<v26-12-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-12-2]]

^<<v26-12-2,2>>^ “Filho do homem, estás a morar numa casa rebelde. Eles têm olhos para ver, mas não veem, e ouvidos para ouvir, mas não ouvem, pois são uma casa rebelde.

[[v26-12-3]]

^<<v26-12-3,3>>^ Quanto a ti, filho do homem, prepara a tua bagagem para ires para o exílio. Então, vai para o exílio durante o dia, enquanto eles estiverem a observar. Vai para o exílio, da tua casa para outro lugar, enquanto estiverem a observar. Talvez eles prestem atenção, embora sejam uma casa rebelde.

[[v26-12-4]]

^<<v26-12-4,4>>^ Durante o dia, enquanto estiverem a observar, leva a tua bagagem para fora, a fim de ires para o exílio. Depois, ao anoitecer, enquanto estiverem a observar, deves sair como quem está a ser levado para o exílio.

[[v26-12-5]]

^<<v26-12-5,5>>^ “Enquanto estiverem a observar, abre um buraco na parede e leva os teus pertences para fora através dele.

[[v26-12-6]]

^<<v26-12-6,6>>^ Enquanto estiverem a observar, põe os teus pertences aos ombros e leva-os para fora, no escuro. Cobre o rosto para não veres o chão, pois vou fazer de ti um sinal para a casa de Israel.”

[[v26-12-7]]

^<<v26-12-7,7>>^ Fiz exatamente o que me tinha sido ordenado. Durante o dia, levei para fora a minha bagagem, como se fosse a bagagem de quem vai para o exílio. Ao anoitecer, fiz com as mãos um buraco na parede. Quando já estava escuro, levei os meus pertences para fora, carregando-os aos ombros, mesmo à frente dos seus olhos.

[[v26-12-8]]

^<<v26-12-8,8>>^ De manhã, recebi novamente a palavra de Jeová:

[[v26-12-9]]

^<<v26-12-9,9>>^ “Filho do homem, não te perguntou a casa de Israel, a casa rebelde: ‘O que estás a fazer?’

[[v26-12-10]]

^<<v26-12-10,10>>^ Diz-lhes: ‘Assim diz o Soberano Senhor Jeová: “Esta proclamação refere-se ao maioral em Jerusalém e a toda a casa de Israel que está na cidade.”’

[[v26-12-11]]

^<<v26-12-11,11>>^ “Diz: ‘Eu sirvo-vos de sinal. Assim como eu fiz, assim lhes será feito. Eles irão para o exílio, para o cativeiro.

[[v26-12-12]]

^<<v26-12-12,12>>^ O maioral que está no meio deles sairá no escuro a carregar os seus pertences aos ombros. Abrirá um buraco na muralha e levará os seus pertences para fora através dele. Ele cobrirá o rosto para não ver o chão.’

[[v26-12-13]]

^<<v26-12-13,13>>^ Eu lançarei a minha rede sobre ele, e ele será apanhado na minha rede de caça. Então, vou levá-lo para Babilónia, a terra dos caldeus, mas ele não a verá; e ali morrerá.

[[v26-12-14]]

^<<v26-12-14,14>>^ E todos os que estiverem à sua volta, os seus ajudantes e as suas tropas, eu espalharei em todas as direções, e puxarei da espada para os perseguir.

[[v26-12-15]]

^<<v26-12-15,15>>^ E terão de saber que eu sou Jeová quando os dispersar pelas nações e os espalhar pelas terras.

[[v26-12-16]]

^<<v26-12-16,16>>^ Mas pouparei alguns deles da espada, da fome e da peste, a fim de que falem, entre as nações para as quais irão, sobre todas as suas práticas detestáveis; e eles terão de saber que eu sou Jeová.”

[[v26-12-17]]

^<<v26-12-17,17>>^ Então, recebi novamente a palavra de Jeová:

[[v26-12-18]]

^<<v26-12-18,18>>^ “Filho do homem, deves comer o teu pão com tremor e beber a tua água com inquietação e ansiedade.

[[v26-12-19]]

^<<v26-12-19,19>>^ Diz ao povo da terra: ‘Assim diz o Soberano Senhor Jeová aos habitantes de Jerusalém que estão na terra de Israel: “Eles comerão o seu pão com ansiedade e beberão a sua água com pavor, pois a sua terra ficará completamente desolada por causa da violência de todos os que lá moram.

[[v26-12-20]]

^<<v26-12-20,20>>^ As cidades habitadas serão devastadas, e a terra irá tornar-se um deserto; e vocês terão de saber que eu sou Jeová.”’”

[[v26-12-21]]

^<<v26-12-21,21>>^ Então recebi novamente a palavra de Jeová:

[[v26-12-22]]

^<<v26-12-22,22>>^ “Filho do homem, que provérbio é este que têm em Israel: ‘Os dias passam, mas as visões não se cumprem’?

[[v26-12-23]]

^<<v26-12-23,23>>^ Portanto, diz-lhes: ‘Assim diz o Soberano Senhor Jeová: “Porei fim a este provérbio, e ele já não será usado em Israel.”’ Contudo, diz-lhes: ‘Os dias estão a chegar, e todas as visões se cumprirão.’

[[v26-12-24]]

^<<v26-12-24,24>>^ Pois não haverá mais nenhuma visão falsa nem adivinhação bajuladora^&#42;1^ na casa de Israel.

[NOTE]
====
. Ou: “enganosa”.
====

[[v26-12-25]]

^<<v26-12-25,25>>^ ‘“Pois eu, Jeová, falarei. Todas as palavras que eu disser irão cumprir-se sem mais demora. Nos vossos dias, ó casa rebelde, direi a palavra e irei cumpri-la”, diz o Soberano Senhor Jeová.’”

[[v26-12-26]]

^<<v26-12-26,26>>^ Recebi novamente a palavra de Jeová:

[[v26-12-27]]

^<<v26-12-27,27>>^ “Filho do homem, isto é o que o povo^&#42;1^ de Israel está a dizer: ‘A visão que ele tem é para daqui a muito tempo; ele está a profetizar sobre o futuro distante.’

[NOTE]
====
. Lit.: “a casa”.
====

[[v26-12-28]]

^<<v26-12-28,28>>^ Por isso, diz-lhes: ‘Assim diz o Soberano Senhor Jeová: “‘Nenhuma das minhas palavras será adiada; tudo o que eu disser irá cumprir-se’, diz o Soberano Senhor Jeová.”’”

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]