include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-28-1]]

^<<v26-28-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-28-2]]

^<<v26-28-2,2>>^ “Filho do homem, diz ao líder de Tiro: ‘Assim diz o Soberano Senhor Jeová:
“Visto que o teu coração se tornou arrogante, tu estás a dizer: ‘Sou um deus.
Estou sentado no trono de um deus, no coração do mar.’
Mas tu és apenas um homem, não um deus,
Embora no coração penses que és um deus.

[[v26-28-3]]

^<<v26-28-3,3>>^ Achas que és mais sábio do que Daniel,
Que nenhum segredo pode ser escondido de ti.

[[v26-28-4]]

^<<v26-28-4,4>>^ Enriqueceste com a tua sabedoria e com o teu discernimento
E continuas a acumular ouro e prata nos teus tesouros.

[[v26-28-5]]

^<<v26-28-5,5>>^ A tua habilidade nos negócios deixou-te muito rico
E o teu coração ficou arrogante por causa da tua riqueza.”’

[[v26-28-6]]

^<<v26-28-6,6>>^ “‘Portanto, assim diz o Soberano Senhor Jeová:
“Visto que tu, no teu coração, pensas que és um deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ Trarei contra ti estrangeiros, a mais cruel das nações,
E eles vão puxar das suas espadas contra as belas coisas adquiridas com a tua sabedoria
E vão profanar o teu glorioso esplendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ Farão com que desças à cova,^&#42;1^
E terás uma morte violenta no coração do alto-mar.

[NOTE]
====
. Ou: “sepultura”.
====

[[v26-28-9]]

^<<v26-28-9,9>>^ Será que ainda dirás: ‘Sou um deus’ àquele que te vai matar?
Serás apenas um homem, não um deus, nas mãos daqueles que te profanarão.”’

[[v26-28-10]]

^<<v26-28-10,10>>^ ‘Às mãos de estrangeiros, sofrerás a morte dos incircuncisos,
Pois eu mesmo falei’, diz o Soberano Senhor Jeová.”

[[v26-28-11]]

^<<v26-28-11,11>>^ Então, recebi novamente a palavra de Jeová:

[[v26-28-12]]

^<<v26-28-12,12>>^ “Filho do homem, canta uma lamentação a respeito do rei de Tiro. Diz-lhe: ‘Assim diz o Soberano Senhor Jeová:
“Tu eras o modelo da perfeição,^&#42;1^
Cheio de sabedoria e perfeito em beleza.

[NOTE]
====
. Lit.: “selavas o padrão”.
====

[[v26-28-13]]

^<<v26-28-13,13>>^ Estavas no Éden, o jardim de Deus.
Estavas adornado com todo o tipo de pedras preciosas:
Rubi, topázio, jaspe,
crisólito, ónix, jade, safira, turquesa e esmeralda;
E os engastes e suportes delas eram feitos de ouro.
Tudo isto foi preparado no dia em que foste criado.

[[v26-28-14]]

^<<v26-28-14,14>>^ Designei-te como o querubim protetor, o ungido.
Estavas no monte santo de Deus e andavas por entre pedras de fogo.

[[v26-28-15]]

^<<v26-28-15,15>>^ Eras íntegro nos teus caminhos, desde o dia em que foste criado
Até que se encontrou injustiça em ti.

[[v26-28-16]]

^<<v26-28-16,16>>^ Por causa do teu grande volume de negócios,
Ficaste cheio de violência e começaste a pecar.
Por isso, irei expulsar-te do monte de Deus como alguém profano e eliminar-te,
Ó querubim protetor, do meio das pedras de fogo.

[[v26-28-17]]

^<<v26-28-17,17>>^ O teu coração tornou-se arrogante por causa da tua beleza.
Corrompeste a tua sabedoria por causa do teu glorioso esplendor.
Vou lançar-te por terra.
Farei de ti um espetáculo diante de reis.

[[v26-28-18]]

^<<v26-28-18,18>>^ Por causa da tua grande culpa e dos teus negócios desonestos, profanaste os teus santuários.
Farei irromper um fogo no teu meio que te devorará.
Irei reduzir-te a cinzas sobre a terra, diante de todos os que te observam.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todos os que te conheciam dentre os povos olharão para ti espantados.
O teu fim será repentino e terrível,
E deixarás de existir para sempre.”’”

[[v26-28-20]]

^<<v26-28-20,20>>^ E recebi novamente a palavra de Jeová:

[[v26-28-21]]

^<<v26-28-21,21>>^ “Filho do homem, vira-te para Sídon e profetiza contra ela.

[[v26-28-22]]

^<<v26-28-22,22>>^ Deves dizer: ‘Assim diz o Soberano Senhor Jeová:
“Estou contra ti, ó Sídon, e serei glorificado no teu meio;
E as pessoas terão de saber que eu sou Jeová, quando executar nela o julgamento e for santificado por meio dela.

[[v26-28-23]]

^<<v26-28-23,23>>^ Vou enviar a peste contra ela, e sangue correrá pelas suas ruas.
Os mortos cairão no seu meio quando a espada a atacar por todos os lados,
E terão de saber que eu sou Jeová.

[[v26-28-24]]

^<<v26-28-24,24>>^ “‘“Então, a casa de Israel nunca mais será cercada por abrolhos nocivos e espinhos dolorosos, aqueles que a tratam com desprezo; e as pessoas terão de saber que eu sou o Soberano Senhor Jeová.”’

[[v26-28-25]]

^<<v26-28-25,25>>^ “‘Assim diz o Soberano Senhor Jeová: “Quando eu reunir a casa de Israel dentre os povos pelos quais eles foram espalhados, serei santificado entre eles aos olhos das nações. E eles morarão na sua própria terra, a qual dei ao meu servo Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ Morarão nela em segurança, construirão casas e plantarão vinhas. Sim, eles morarão em segurança quando eu executar o julgamento em todos ao seu redor que os tratam com desprezo, e eles terão de saber que eu sou Jeová, seu Deus.”’”

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]