include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-24-1]]

^<<v26-24-1,1>>^ No nono ano, no décimo mês, no dia dez do mês, recebi novamente a palavra de Jeová:

[[v26-24-2]]

^<<v26-24-2,2>>^ “Filho do homem, regista esta data,^&#42;1^ a data de hoje. Exatamente neste dia, o rei de Babilónia começou o seu ataque contra Jerusalém.

[NOTE]
====
. Lit.: “o nome do dia”.
====

[[v26-24-3]]

^<<v26-24-3,3>>^ E conta uma parábola^&#42;1^ a respeito da casa rebelde. Diz a respeito deles:
“‘Assim diz o Soberano Senhor Jeová:
“Põe a panela,^&#42;2^ põe a panela ao lume e despeja água para dentro dela.

[NOTE]
====
. Ou: “um provérbio”.
. Ou: “o caldeirão”.
====

[[v26-24-4]]

^<<v26-24-4,4>>^ Põe nela pedaços de carne, todos os pedaços bons,
A coxa e a espádua; enche-a com ossos de boa qualidade.

[[v26-24-5]]

^<<v26-24-5,5>>^ Pega na melhor ovelha do rebanho e empilha lenha debaixo da panela, à sua volta.
Ferve os pedaços e cozinha os ossos dentro dela.”’

[[v26-24-6]]

^<<v26-24-6,6>>^ “Portanto, assim diz o Soberano Senhor Jeová:
‘Ai da cidade de derramamento de sangue, da panela enferrujada, cuja ferrugem não foi removida!
Tira todos os pedaços de dentro dela, um por um; não lances sortes para os escolher.

[[v26-24-7]]

^<<v26-24-7,7>>^ Pois o seu sangue está nela; ela^&#42;1^ derramou-o sobre a rocha lisa.
Não o derramou sobre a terra, para o cobrir com pó.

[NOTE]
====
. Ou: “a cidade”.
====

[[v26-24-8]]

^<<v26-24-8,8>>^ A fim de despertar furor e executar vingança,
Deixei o seu sangue sobre a rocha lisa
Para que não fosse coberto.’

[[v26-24-9]]

^<<v26-24-9,9>>^ “Portanto, assim diz o Soberano Senhor Jeová:
‘Ai da cidade de derramamento de sangue!
Eu farei uma grande pilha de lenha.

[[v26-24-10]]

^<<v26-24-10,10>>^ Empilhem a lenha e acendam o lume,
Cozinhem bem a carne, despejem o caldo e deixem queimar os ossos.

[[v26-24-11]]

^<<v26-24-11,11>>^ Ponham a panela vazia sobre as brasas, para que aqueça
Até o cobre ficar incandescente.
A sua impureza irá derreter-se dentro dela, e a sua ferrugem será consumida.

[[v26-24-12]]

^<<v26-24-12,12>>^ Mas isto é frustrante e exaustivo,
Pois a grande quantidade de ferrugem não sai.
Lancem no lume a panela e a sua ferrugem!’

[[v26-24-13]]

^<<v26-24-13,13>>^ “‘Ficaste impura por causa da tua conduta obscena. Eu tentei purificar-te, mas não ficaste purificada da tua impureza. Não ficarás limpa até que desapareça o meu furor contra ti.

[[v26-24-14]]

^<<v26-24-14,14>>^ Fui eu, Jeová, que falei. Isto acontecerá. Agirei sem me refrear, sem dó e sem voltar atrás. Eles irão julgar-te conforme os teus caminhos e as tuas ações’, diz o Soberano Senhor Jeová.”

[[v26-24-15]]

^<<v26-24-15,15>>^ E recebi novamente a palavra de Jeová:

[[v26-24-16]]

^<<v26-24-16,16>>^ “Filho do homem, estou prestes a tirar-te, com um só golpe, aquela que tu amas. Não deves lamentar,^&#42;1^ nem chorar, nem derramar lágrimas.

[NOTE]
====
. Ou: “bater no peito”.
====

[[v26-24-17]]

^<<v26-24-17,17>>^ Geme em silêncio e não guardes o luto habitual pelos mortos. Põe o turbante e calça as sandálias. Não deves cobrir a boca,^&#42;1^ nem comer o pão trazido por outros.”^&#42;2^

[NOTE]
====
. Ou: “o bigode; o lábio superior”.
. Lit.: “o pão de homens”.
====

[[v26-24-18]]

^<<v26-24-18,18>>^ Então, eu falei ao povo de manhã, e a minha esposa morreu à noite. E, na manhã seguinte, fiz exatamente o que me tinha sido ordenado.

[[v26-24-19]]

^<<v26-24-19,19>>^ As pessoas perguntavam-me: “Não nos vais contar o que é que estas coisas que estás a fazer têm a ver connosco?”

[[v26-24-20]]

^<<v26-24-20,20>>^ Respondi-lhes: “Recebi a seguinte palavra de Jeová:

[[v26-24-21]]

^<<v26-24-21,21>>^ ‘Diz à casa de Israel: “Assim diz o Soberano Senhor Jeová: ‘Estou prestes a profanar o meu santuário, o motivo do vosso grande orgulho, aquilo que amam e o desejo do vosso coração.^&#42;1^ Os vossos filhos e as vossas filhas, que deixaram para trás, cairão pela espada.

[NOTE]
====
. Ou: “a compaixão da vossa alma”.
====

[[v26-24-22]]

^<<v26-24-22,22>>^ Então, vocês terão de fazer exatamente o que eu fiz. Não cobrirão a boca^&#42;1^ nem comerão o pão trazido por outros.

[NOTE]
====
. Ou: “o bigode; o lábio superior”.
====

[[v26-24-23]]

^<<v26-24-23,23>>^ Estarão com o turbante na cabeça e as sandálias nos pés. Não lamentarão nem chorarão. Em vez disso, apodrecerão nos vossos erros e gemerão uns para os outros.

[[v26-24-24]]

^<<v26-24-24,24>>^ Ezequiel tornou-se um sinal para vocês. Farão exatamente como ele fez. Quando isso acontecer, terão de saber que eu sou o Soberano Senhor Jeová.’”’”

[[v26-24-25]]

^<<v26-24-25,25>>^ “Quanto a ti, filho do homem, no dia em que eu lhes tirar a fortaleza — o seu belo motivo de alegria, aquilo que eles amam e o desejo do seu coração^&#42;1^ — e também os seus filhos e as suas filhas,

[NOTE]
====
. Ou: “da sua alma”.
====

[[v26-24-26]]

^<<v26-24-26,26>>^ serás informado disso por alguém que escapar.

[[v26-24-27]]

^<<v26-24-27,27>>^ Nesse dia abrirás a boca e falarás com aquele que escapou, e já não ficarás mudo. Serás um sinal para eles, e terão de saber que eu sou Jeová.”

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]