include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-33-1]]

^<<v26-33-1,1>>^ E recebi a seguinte palavra de Jeová:

[[v26-33-2]]

^<<v26-33-2,2>>^ “Filho do homem, diz o seguinte aos filhos do teu povo:
“‘Suponhamos que eu traga a espada contra uma terra, e que todos os habitantes dessa terra escolham um homem e o designem como vigia.

[[v26-33-3]]

^<<v26-33-3,3>>^ Ele, ao ver a espada chegar sobre a terra, toca a buzina e avisa o povo.

[[v26-33-4]]

^<<v26-33-4,4>>^ Se alguém ouve o som da buzina, mas não acata o aviso, e a espada vem e tira-lhe a vida,^&#42;1^ o seu sangue recairá sobre a sua própria cabeça.

[NOTE]
====
. Lit.: “leva-o embora”.
====

[[v26-33-5]]

^<<v26-33-5,5>>^ Ele ouviu o som da buzina, mas não acatou o aviso. O seu sangue recairá sobre ele mesmo. Se tivesse acatado o aviso, a sua vida^&#42;1^ teria sido salva.

[NOTE]
====
. Ou: “alma”.
====

[[v26-33-6]]

^<<v26-33-6,6>>^ “‘No entanto, se o vigia, ao ver a espada chegar, não toca a buzina, de modo que o povo não recebe nenhum aviso, e a espada vem e tira a vida^&#42;1^ de um deles, essa pessoa morrerá por causa do seu próprio erro, mas o sangue dela exigirei do vigia.’^&#42;2^

[NOTE]
====
. Ou: “alma”.
. Ou: “mas farei o vigia prestar contas pelo sangue dela”.
====

[[v26-33-7]]

^<<v26-33-7,7>>^ “Quanto a ti, filho do homem, eu designei-te como vigia para a casa de Israel. Quando ouvires uma palavra da minha boca, deves transmitir-lhes o meu aviso.

[[v26-33-8]]

^<<v26-33-8,8>>^ Se eu disser àquele que é mau: ‘Tu certamente morrerás!’, mas tu não lhe disseres nada a fim de o avisares para mudar de proceder, ele morrerá como alguém mau por causa do seu próprio erro, mas o sangue dele exigirei de ti.

[[v26-33-9]]

^<<v26-33-9,9>>^ No entanto, se avisares aquele que é mau para que recue do seu caminho, e ele se recusar a mudar de proceder, ele morrerá por causa do seu erro, mas tu certamente salvarás a tua própria vida.^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v26-33-10]]

^<<v26-33-10,10>>^ “Filho do homem, diz à casa de Israel: ‘Vocês disseram: “A nossa rebeldia e os nossos pecados são um grande peso para nós e fazem-nos definhar. Como é que continuaremos vivos?”’

[[v26-33-11]]

^<<v26-33-11,11>>^ Diz-lhes: ‘“Tão certo como eu vivo”, diz o Soberano Senhor Jeová, “não tenho prazer na morte de quem é mau, mas sim em que a pessoa má mude o seu caminho e continue viva. Recuem, recuem dos vossos maus caminhos. Afinal, porque é que deveriam morrer, ó casa de Israel?”’

[[v26-33-12]]

^<<v26-33-12,12>>^ “Filho do homem, diz aos filhos do teu povo: ‘A justiça do homem justo não o salvará quando ele se rebelar; e a maldade daquele que é mau não o fará tropeçar quando ele abandonar a sua maldade. O justo não será preservado vivo pela sua justiça no dia em que pecar.

[[v26-33-13]]

^<<v26-33-13,13>>^ Se eu disser a um justo: “Tu certamente continuarás vivo”, e ele confiar na sua justiça e fizer o que é errado,^&#42;1^ nenhum dos seus atos justos será lembrado; ele morrerá por causa do que fez de errado.

[NOTE]
====
. Ou: “fizer injustiça”.
====

[[v26-33-14]]

^<<v26-33-14,14>>^ “‘E, se eu disser àquele que é mau: “Tu certamente morrerás”, e ele abandonar o seu pecado, fizer o que é justo e certo,

[[v26-33-15]]

^<<v26-33-15,15>>^ restituir o que recebeu como garantia de um empréstimo, devolver o que roubou e andar nos decretos que dão vida, por não fazer o que é errado, ele certamente continuará vivo. Não morrerá.

[[v26-33-16]]

^<<v26-33-16,16>>^ Não terá de responder por nenhum dos pecados que cometeu.^&#42;1^ Por ter feito o que é justo e certo, ele certamente continuará vivo.’

[NOTE]
====
. Ou: “Nenhum dos pecados que cometeu será lembrado contra ele.”
====

[[v26-33-17]]

^<<v26-33-17,17>>^ “Contudo, o teu povo disse: ‘O caminho de Jeová é injusto’; quando, na verdade, é o caminho deles que é injusto.

[[v26-33-18]]

^<<v26-33-18,18>>^ “Se um justo abandonar a sua justiça e fizer o que é errado, ele terá de morrer por causa disso.

[[v26-33-19]]

^<<v26-33-19,19>>^ Porém, se aquele que é mau abandonar a sua maldade e fizer o que é justo e certo, ele continuará vivo por fazer isso.

[[v26-33-20]]

^<<v26-33-20,20>>^ “Todavia, vocês disseram: ‘O caminho de Jeová é injusto.’ Eu julgarei a cada um conforme os seus caminhos, ó casa de Israel.”

[[v26-33-21]]

^<<v26-33-21,21>>^ Por fim, no décimo segundo ano do nosso exílio, no décimo mês, no dia cinco do mês, um homem que tinha escapado de Jerusalém veio ter comigo e disse: “A cidade foi conquistada!”

[[v26-33-22]]

^<<v26-33-22,22>>^ Na noite anterior à chegada do homem que tinha escapado, a mão de Jeová veio sobre mim, e Ele abriu-me a boca antes de o homem ter chegado de manhã. Assim, a minha boca já tinha sido aberta, e eu já não estava mudo.

[[v26-33-23]]

^<<v26-33-23,23>>^ Então, recebi a seguinte palavra de Jeová:

[[v26-33-24]]

^<<v26-33-24,24>>^ “Filho do homem, os habitantes daquelas ruínas estão a dizer a respeito da terra de Israel: ‘Abraão era um só, e, mesmo assim, tomou posse desta terra. Nós somos muitos; esta terra certamente nos foi dada como propriedade.’

[[v26-33-25]]

^<<v26-33-25,25>>^ “Portanto, diz-lhes: ‘Assim diz o Soberano Senhor Jeová: “Vocês comem carne com sangue, erguem os olhos para os vossos ídolos repugnantes^&#42;1^ e continuam a derramar sangue. Portanto, porque é que deveriam possuir esta terra?

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-33-26]]

^<<v26-33-26,26>>^ Confiam na vossa espada, praticam coisas detestáveis e cada um desonra a esposa do próximo. Portanto, porque é que deveriam possuir esta terra?”’

[[v26-33-27]]

^<<v26-33-27,27>>^ “Tu deves dizer-lhes o seguinte: ‘Assim diz o Soberano Senhor Jeová: “Tão certo como eu vivo, os que moram nas ruínas cairão pela espada, os que estão em campo aberto darei aos animais selvagens como comida, e os que estão nas fortalezas e nas cavernas morrerão de doença.

[[v26-33-28]]

^<<v26-33-28,28>>^ Farei desta terra um deserto completamente desolado, e o seu orgulho arrogante terá fim. Os montes de Israel ficarão desolados, sem que ninguém passe por eles.

[[v26-33-29]]

^<<v26-33-29,29>>^ E eles terão de saber que eu sou Jeová, quando eu fizer desta terra um deserto completamente desolado por causa de todas as coisas detestáveis que eles fizeram.”’

[[v26-33-30]]

^<<v26-33-30,30>>^ “Quanto a ti, filho do homem, o teu povo está a conversar entre si a teu respeito, junto aos muros e nas portas das casas. Eles dizem uns aos outros, cada um ao seu irmão: ‘Venham, ouçamos a palavra que vem de Jeová.’

[[v26-33-31]]

^<<v26-33-31,31>>^ Vão ajuntar-se em grande número para se sentarem perante ti como meu povo; eles ouvirão as tuas palavras, mas não as porão em prática. Pois, com a boca, bajulam-te,^&#42;1^ mas o coração deles deseja ganho desonesto.

[NOTE]
====
. Ou: “falam de maneira apaixonada”.
====

[[v26-33-32]]

^<<v26-33-32,32>>^ Tu és para eles como uma canção de amor, cantada com uma voz bonita e bem tocada num instrumento de cordas. Eles ouvirão as tuas palavras, mas ninguém agirá de harmonia com elas.

[[v26-33-33]]

^<<v26-33-33,33>>^ E, quando tudo se cumprir — e vai cumprir-se —, eles terão de saber que havia um profeta entre eles.”

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]