include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-3-1]]

^<<v26-3-1,1>>^ Então, ele disse-me: “Filho do homem, come o que está à tua frente.^&#42;1^ Come este rolo e depois vai, fala à casa de Israel.”

[NOTE]
====
. Lit.: “come o que encontrares”.
====

[[v26-3-2]]

^<<v26-3-2,2>>^ Assim, abri a boca, e ele fez-me comer o rolo.

[[v26-3-3]]

^<<v26-3-3,3>>^ Ele acrescentou: “Filho do homem, come este rolo que te dou e enche o estômago com ele.” Portanto, comecei a comê-lo, e, na minha boca, ele era doce como o mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ Ele disse-me: “Filho do homem, entra no meio da casa de Israel e diz-lhes as minhas palavras.

[[v26-3-5]]

^<<v26-3-5,5>>^ Pois não estás a ser enviado a um povo de idioma incompreensível ou de língua desconhecida, mas à casa de Israel.

[[v26-3-6]]

^<<v26-3-6,6>>^ Não estás a ser enviado a muitos povos de idioma incompreensível ou de língua desconhecida, cujas palavras não consegues entender. Se eu te enviasse a tais, eles iriam escutar-te.

[[v26-3-7]]

^<<v26-3-7,7>>^ Contudo, a casa de Israel não te vai querer escutar, pois não me querem escutar a mim. Todos os da casa de Israel são de cabeça dura e de coração obstinado.

[[v26-3-8]]

^<<v26-3-8,8>>^ Pois bem, eu fiz o teu rosto tão duro como o rosto deles e a tua testa tão dura como a testa deles.

[[v26-3-9]]

^<<v26-3-9,9>>^ Fiz a tua testa igual a um diamante, mais dura do que uma pedra.^&#42;1^ Não tenhas medo deles, nem fiques apavorado por causa da expressão do rosto deles, pois são uma casa rebelde.”

[NOTE]
====
. Ou: “rocha de pederneira”.
====

[[v26-3-10]]

^<<v26-3-10,10>>^ Ele continuou a dizer-me: “Filho do homem, aceita no coração e escuta todas as palavras que te digo.

[[v26-3-11]]

^<<v26-3-11,11>>^ Entra no meio dos exilados do teu povo^&#42;1^ e fala com eles. Diz-lhes: ‘Assim diz o Soberano Senhor Jeová’, quer escutem, quer se recusem a escutar.”

[NOTE]
====
. Lit.: “dos exilados dos filhos do teu povo”.
====

[[v26-3-12]]

^<<v26-3-12,12>>^ Em seguida, um espírito levou-me, e ouvi atrás de mim uma voz estrondosa, que disse: “Louvada seja a glória de Jeová desde o seu lugar.”

[[v26-3-13]]

^<<v26-3-13,13>>^ Ouvi também o som das asas das criaturas viventes a tocarem umas nas outras, o som das rodas que estavam ao lado delas e um grande estrondo.

[[v26-3-14]]

^<<v26-3-14,14>>^ O espírito levantou-me e tirou-me dali. E eu fui, amargurado e com o espírito indignado, e a mão de Jeová era forte sobre mim.

[[v26-3-15]]

^<<v26-3-15,15>>^ Então, dirigi-me ao povo exilado que morava em Tel-Abibe, junto ao rio Quebar, e fiquei onde eles moravam; fiquei ali durante sete dias, pasmado no meio deles.

[[v26-3-16]]

^<<v26-3-16,16>>^ Ao fim dos sete dias, recebi a seguinte palavra de Jeová:

[[v26-3-17]]

^<<v26-3-17,17>>^ “Filho do homem, eu designei-te como vigia para a casa de Israel. Quando ouvires uma palavra da minha boca, deves transmitir-lhes o meu aviso.

[[v26-3-18]]

^<<v26-3-18,18>>^ Se eu disser àquele que é mau: ‘Tu certamente morrerás’, mas tu não o avisares — se não falares com aquele que é mau a fim de o avisares para que ele abandone o seu mau proceder e continue vivo —, ele morrerá por causa do seu erro, por ser alguém mau, mas exigirei de ti o sangue dele.^&#42;1^

[NOTE]
====
. Ou: “mas irei fazer-te prestar contas pelo sangue dele”.
====

[[v26-3-19]]

^<<v26-3-19,19>>^ No entanto, se avisares aquele que é mau, e ele não recuar da sua maldade e do seu mau proceder, ele morrerá por causa do seu erro, mas tu certamente salvarás a tua própria vida.^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v26-3-20]]

^<<v26-3-20,20>>^ Também, se um justo abandonar a sua justiça e fizer o que é errado,^&#42;1^ porei diante dele uma pedra de tropeço e ele morrerá. Se tu não o avisares, ele morrerá por causa do seu pecado e os atos justos dele não serão lembrados, mas exigirei de ti o sangue dele.^&#42;2^

[NOTE]
====
. Ou: “fizer injustiça”.
. Ou: “mas irei fazer-te prestar contas pelo sangue dele”.
====

[[v26-3-21]]

^<<v26-3-21,21>>^ No entanto, se avisares o justo para que ele não peque, e ele não pecar, ele certamente continuará vivo por ter sido avisado, e tu salvarás a tua própria vida.”^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v26-3-22]]

^<<v26-3-22,22>>^ Ali, a mão de Jeová veio sobre mim, e ele disse-me: “Levanta-te, vai até ao vale^&#42;1^ e lá eu falarei contigo.”

[NOTE]
====
. Lit.: “à planície de vale”.
====

[[v26-3-23]]

^<<v26-3-23,23>>^ Assim, levantei-me, fui ao vale e vi ali a glória de Jeová, igual à glória que eu tinha visto junto ao rio Quebar, e prostrei-me com o rosto por terra.

[[v26-3-24]]

^<<v26-3-24,24>>^ A seguir, espírito entrou em mim e fez-me ficar de pé, e Ele disse-me:
“Vai para a tua casa e fica lá trancado.

[[v26-3-25]]

^<<v26-3-25,25>>^ Filho do homem, eles porão cordas sobre ti e irão amarrar-te com elas, para que não consigas ir para o meio deles.

[[v26-3-26]]

^<<v26-3-26,26>>^ Farei com que a tua língua se pegue ao céu da boca, e ficarás mudo, incapaz de os repreender, pois são uma casa rebelde.

[[v26-3-27]]

^<<v26-3-27,27>>^ Todavia, quando eu falar contigo, abrirei a tua boca e irás dizer-lhes: ‘Assim diz o Soberano Senhor Jeová.’ Quem quiser ouvir, ouça; quem não quiser ouvir, não ouça, pois são uma casa rebelde.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]