include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-21-1]]

^<<v26-21-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-21-2]]

^<<v26-21-2,2>>^ “Filho do homem, vira-te para Jerusalém, faz uma proclamação contra os lugares santos e profetiza contra a terra de Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ Diz à terra de Israel: ‘Assim diz Jeová: “Eu estou contra ti; vou puxar a minha espada da bainha e eliminar do teu meio tanto os justos como os maus.

[[v26-21-4]]

^<<v26-21-4,4>>^ Visto que eliminarei do teu meio os justos e os maus, vou puxar a minha espada da bainha contra todos,^&#42;1^ do sul ao norte.

[NOTE]
====
. Lit.: “toda a carne”.
====

[[v26-21-5]]

^<<v26-21-5,5>>^ Todos terão de saber que eu mesmo, Jeová, puxei a minha espada da bainha. Ela já não voltará mais para lá.”’

[[v26-21-6]]

^<<v26-21-6,6>>^ “E tu, filho do homem, suspira enquanto tremes^&#42;1^ de medo, sim, suspira amargurado diante deles.

[NOTE]
====
. Ou: “as tuas ancas tremem”.
====

[[v26-21-7]]

^<<v26-21-7,7>>^ Se te perguntarem: ‘Porque é que estás a suspirar?’, tu responderás: ‘Por causa de uma notícia.’ Pois ela certamente virá, e todos os corações se derreterão de medo, todas as mãos ficarão caídas, todos os ânimos ficarão abatidos^&#42;1^ e de todos os joelhos pingará água.^&#42;2^ ‘Vejam! Ela certamente virá; ela irá cumprir-se’, diz o Soberano Senhor Jeová.”

[NOTE]
====
. Lit.: “todo o espírito ficará abatido”.
. Isto é, pingará urina devido ao medo.
====

[[v26-21-8]]

^<<v26-21-8,8>>^ Recebi novamente a palavra de Jeová:

[[v26-21-9]]

^<<v26-21-9,9>>^ “Filho do homem, profetiza o seguinte: ‘Assim diz Jeová: “Diz: ‘Uma espada! Uma espada está afiada e polida.

[[v26-21-10]]

^<<v26-21-10,10>>^ Ela está afiada para realizar uma grande matança; está polida para brilhar como um relâmpago.’”’”
“Não nos devemos alegrar?”
“‘Será que ela^&#42;1^ rejeitará o cetro do meu próprio filho, como rejeita todas as árvores?

[NOTE]
====
. Isto é, a espada de Jeová.
====

[[v26-21-11]]

^<<v26-21-11,11>>^ “‘Foi dada para ser polida e para ser empunhada. Esta espada está afiada e polida, para ser posta na mão de um executor.

[[v26-21-12]]

^<<v26-21-12,12>>^ “‘Clama e lamenta, filho do homem, pois ela veio contra o meu povo; ela está contra todos os maiorais de Israel. Eles serão vítimas da espada juntamente com o meu povo. Por isso, bate na coxa, de pesar.

[[v26-21-13]]

^<<v26-21-13,13>>^ Pois foi feita uma inspeção, e o que acontecerá se a espada rejeitar o cetro? Ele deixará de existir’, diz o Soberano Senhor Jeová.

[[v26-21-14]]

^<<v26-21-14,14>>^ “Agora, filho do homem, profetiza, bate as mãos e repete três vezes: ‘Uma espada!’ É a espada que faz vítimas, a espada da grande matança, a espada que os cerca.

[[v26-21-15]]

^<<v26-21-15,15>>^ Os seus corações irão derreter-se de medo e muitos cairão nos portões das suas cidades; vou causar uma matança com a espada. Sim, ela brilha como um relâmpago e está polida para a matança!

[[v26-21-16]]

^<<v26-21-16,16>>^ Espada afiada, corta à direita! Golpeia à esquerda! Vai para onde quer que a tua lâmina seja direcionada!

[[v26-21-17]]

^<<v26-21-17,17>>^ Eu também baterei as minhas mãos e saciarei o meu furor. Fui eu, Jeová, que falei.”

[[v26-21-18]]

^<<v26-21-18,18>>^ E recebi novamente a palavra de Jeová:

[[v26-21-19]]

^<<v26-21-19,19>>^ “Filho do homem, traça dois caminhos para a espada do rei de Babilónia passar. Os dois começarão na mesma terra, e um sinal^&#42;1^ deve ser colocado onde a estrada se divide em direção às duas cidades.

[NOTE]
====
. Lit.: “uma mão”.
====

[[v26-21-20]]

^<<v26-21-20,20>>^ Deves indicar um caminho para a espada ir contra Rabá dos amonitas e outro para ir contra a fortificada cidade de Jerusalém, em Judá.

[[v26-21-21]]

^<<v26-21-21,21>>^ Pois o rei de Babilónia para a fim de empregar a adivinhação na bifurcação da estrada, onde os dois caminhos se dividem. Ele sacode as flechas. Consulta os seus ídolos;^&#42;1^ examina o fígado.

[NOTE]
====
. Lit.: “os terafins”.
====

[[v26-21-22]]

^<<v26-21-22,22>>^ A resposta da adivinhação na sua mão direita aponta para Jerusalém. Ele deve preparar os aríetes, ordenar a matança, dar o grito de guerra, posicionar os aríetes na frente dos portões, levantar uma rampa de ataque e construir um muro de cerco.

[[v26-21-23]]

^<<v26-21-23,23>>^ Contudo, ela parecerá uma adivinhação falsa aos olhos daqueles^&#42;1^ que lhes tinham feito juramentos. No entanto, ele lembra-se da culpa deles e irá capturá-los.

[NOTE]
====
. Isto é, dos habitantes de Jerusalém.
====

[[v26-21-24]]

^<<v26-21-24,24>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Fizeram com que a vossa própria culpa fosse lembrada ao exporem as vossas transgressões e tornarem evidentes os vossos pecados em todas as vossas ações. Agora que vocês foram lembrados, serão tomados à força.’^&#42;1^

[NOTE]
====
. Lit.: “pela mão”.
====

[[v26-21-25]]

^<<v26-21-25,25>>^ “No entanto, o teu dia chegou, perverso maioral de Israel, mortalmente ferido. Chegou o tempo da tua punição final.

[[v26-21-26]]

^<<v26-21-26,26>>^ Assim diz o Soberano Senhor Jeová: ‘Remove o turbante e retira a coroa. As coisas nunca mais serão como dantes. Enaltece o rebaixado e rebaixa o enaltecido.

[[v26-21-27]]

^<<v26-21-27,27>>^ Uma ruína! Uma ruína! Farei dela uma ruína! E ela não será de ninguém até que chegue aquele que tem o direito legal; eu irei dá-la a ele.’

[[v26-21-28]]

^<<v26-21-28,28>>^ “E tu, filho do homem, profetiza o seguinte: ‘Assim diz o Soberano Senhor Jeová a respeito dos amonitas e dos seus insultos.’ Diz: ‘Uma espada! Uma espada está desembainhada para a matança, está polida para devorar e brilhar como um relâmpago.

[[v26-21-29]]

^<<v26-21-29,29>>^ Apesar das visões falsas e adivinhações mentirosas a teu respeito, serás empilhada sobre os que foram mortos,^&#42;1^ os homens perversos para os quais chegou o dia, o tempo da sua punição final.

[NOTE]
====
. Lit.: “os pescoços dos que foram mortos”.
====

[[v26-21-30]]

^<<v26-21-30,30>>^ Põe a espada de volta na bainha. Irei julgar-te no lugar em que foste criada,^&#42;1^ na terra da tua origem.

[NOTE]
====
. Ou: “no lugar de onde vieste”.
====

[[v26-21-31]]

^<<v26-21-31,31>>^ Vou derramar sobre ti a minha indignação. Soprarei sobre ti o fogo da minha fúria e vou entregar-te nas mãos de homens brutais, peritos em causar destruição.

[[v26-21-32]]

^<<v26-21-32,32>>^ Irás tornar-te combustível para o fogo; o teu próprio sangue será derramado na tua terra, e nunca mais serás lembrada, pois fui eu, Jeová, que falei.’”

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]