include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-25-1]]

^<<v26-25-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-25-2]]

^<<v26-25-2,2>>^ “Filho do homem, vira-te para os amonitas e profetiza contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ Diz aos amonitas: ‘Ouçam a palavra do Soberano Senhor Jeová. Assim diz o Soberano Senhor Jeová: “Visto que tu^&#42;1^ gozaste, dizendo: ‘Ah!’ contra o meu santuário quando foi profanado, contra a terra de Israel quando foi desolada, e contra a casa de Judá quando foi para o exílio,

[NOTE]
====
. Refere-se a Amom como país.
====

[[v26-25-4]]

^<<v26-25-4,4>>^ vou entregar-te como propriedade aos orientais. Eles montarão os seus acampamentos^&#42;1^ no teu meio e ali armarão as suas tendas. Comerão os teus frutos e beberão o teu leite.

[NOTE]
====
. Ou: “acampamentos murados”.
====

[[v26-25-5]]

^<<v26-25-5,5>>^ Transformarei Rabá numa pastagem para camelos, e a terra dos amonitas num lugar de descanso para ovelhas; e vocês terão de saber que eu sou Jeová.”’”

[[v26-25-6]]

^<<v26-25-6,6>>^ “Pois assim diz o Soberano Senhor Jeová: ‘Visto que bateste palmas, bateste os pés no chão e te alegraste^&#42;1^ com a calamidade da terra de Israel com tão profundo desprezo,

[NOTE]
====
. Ou: “e a tua alma se alegrou”.
====

[[v26-25-7]]

^<<v26-25-7,7>>^ estenderei a mão contra ti para te entregar como despojo às nações. Vou eliminar-te dentre os povos e destruir-te dentre as terras. Vou aniquilar-te, e terás de saber que eu sou Jeová.’

[[v26-25-8]]

^<<v26-25-8,8>>^ “Assim diz o Soberano Senhor Jeová: ‘Visto que Moabe e Seir disseram: “Vejam! A casa de Judá é igual a todas as outras nações”,

[[v26-25-9]]

^<<v26-25-9,9>>^ vou deixar exposto o flanco^&#42;1^ de Moabe, onde ficam as cidades da sua fronteira, que são a beleza^&#42;2^ do país — Bete-Jesimote, Baal-Meom, e até Quiriataim.

[NOTE]
====
. Ou: “exposta a encosta”.
. Ou: “o ornamento”.
====

[[v26-25-10]]

^<<v26-25-10,10>>^ Eu irei dá-lo,^&#42;1^ juntamente com os amonitas, como propriedade aos orientais, para que os amonitas não sejam lembrados entre as nações.

[NOTE]
====
. Isto é, darei o flanco de Moabe.
====

[[v26-25-11]]

^<<v26-25-11,11>>^ E vou executar o julgamento contra Moabe, e terão de saber que eu sou Jeová.’

[[v26-25-12]]

^<<v26-25-12,12>>^ “Assim diz o Soberano Senhor Jeová: ‘Edom foi vingativo contra a casa de Judá e incorreu em grande culpa ao vingar-se deles;

[[v26-25-13]]

^<<v26-25-13,13>>^ por isso, assim diz o Soberano Senhor Jeová: “Também estenderei a mão contra Edom e eliminarei dele tanto homens como animais, fazendo o país ficar desolado. Desde Temã até Dedã, eles cairão pela espada.

[[v26-25-14]]

^<<v26-25-14,14>>^ ‘Vou-me vingar de Edom pelas mãos do meu povo Israel. Eles trarão sobre Edom a minha ira e o meu furor, para que Edom sinta a minha vingança’, diz o Soberano Senhor Jeová.”’

[[v26-25-15]]

^<<v26-25-15,15>>^ “Assim diz o Soberano Senhor Jeová: ‘Por causa da sua ferrenha hostilidade, os filisteus procuraram trazer vingança e destruição, cheios de más intenções.^&#42;1^

[NOTE]
====
. Ou: “com desprezo na alma”.
====

[[v26-25-16]]

^<<v26-25-16,16>>^ Por isso, assim diz o Soberano Senhor Jeová: “Vou estender a mão contra os filisteus, vou eliminar os queretitas e destruir os habitantes da costa marítima que restarem.

[[v26-25-17]]

^<<v26-25-17,17>>^ Vou executar contra eles grandes atos de vingança com furiosas punições, e terão de saber que eu sou Jeová quando trouxer sobre eles a minha vingança.”’”

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]