include::./index.adoc[]

[[v26-13-0]]
=== Ezequiel, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-13-1]]

^<<v26-13-1,1>>^ Então, recebi novamente a palavra de Jeová:

[[v26-13-2]]

^<<v26-13-2,2>>^ “Filho do homem, profetiza contra os profetas de Israel e diz aos que inventam as suas próprias profecias:^&#42;1^ ‘Ouçam a palavra de Jeová.

[NOTE]
====
. Ou: “que profetizam do seu próprio coração”.
====

[[v26-13-3]]

^<<v26-13-3,3>>^ Assim diz o Soberano Senhor Jeová: “Ai dos profetas insensatos que seguem as suas próprias ideias,^&#42;1^ sem terem visto nada!

[NOTE]
====
. Lit.: “o seu próprio espírito”.
====

[[v26-13-4]]

^<<v26-13-4,4>>^ Ó Israel, os teus profetas tornaram-se como raposas entre as ruínas.

[[v26-13-5]]

^<<v26-13-5,5>>^ Vocês não irão às brechas das muralhas de pedras a fim de as reconstruírem para a casa de Israel, para que Israel se mantenha firme na batalha no dia de Jeová.”

[[v26-13-6]]

^<<v26-13-6,6>>^ “Eles têm visões falsas e predizem uma mentira; estão a dizer: ‘Esta é a palavra de Jeová’, apesar de Jeová não os ter enviado, e ainda esperam que a palavra deles se cumpra.

[[v26-13-7]]

^<<v26-13-7,7>>^ Por acaso não são falsas as visões que vocês têm, e não é uma mentira o que predizem? Dizem: ‘Esta é a palavra de Jeová’, apesar de eu não ter dito nada.”’

[[v26-13-8]]

^<<v26-13-8,8>>^ “‘Portanto, assim diz o Soberano Senhor Jeová: “‘Visto que proclamam falsidades e as vossas visões são uma mentira, eu estou contra vocês’, diz o Soberano Senhor Jeová.”

[[v26-13-9]]

^<<v26-13-9,9>>^ A minha mão está contra os profetas que têm visões falsas e predizem uma mentira. Não estarão entre os meus confidentes, nem serão inscritos no registo da casa de Israel, nem voltarão à terra de Israel; e vocês terão de saber que eu sou o Soberano Senhor Jeová.

[[v26-13-10]]

^<<v26-13-10,10>>^ Tudo isto porque eles desencaminham o meu povo, dizendo: “Há paz!”, quando não há paz. Quando alguém constrói uma parede frágil, eles revestem-na de cal.’^&#42;1^

[NOTE]
====
. Isto é, alguém constrói uma parede frágil, e eles tentam fazê-la parecer forte, revestindo-a de cal.
====

[[v26-13-11]]

^<<v26-13-11,11>>^ “Diz aos que revestem a parede de cal que ela cairá. Ocorrerá uma chuva torrencial, cairão pedras de granizo,^&#42;1^ e fortes vendavais irão derrubá-la.

[NOTE]
====
. Ou: “uma chuva torrencial, e vocês, pedras de granizo, cairão”.
====

[[v26-13-12]]

^<<v26-13-12,12>>^ E, quando a parede cair, as pessoas irão perguntar-vos: ‘Onde está o revestimento de cal que tinham feito?’

[[v26-13-13]]

^<<v26-13-13,13>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘No meu furor, farei irromper fortes vendavais, na minha ira enviarei uma chuva torrencial, e na minha fúria destruidora farei cair pedras de granizo.

[[v26-13-14]]

^<<v26-13-14,14>>^ Farei desabar a parede que revestiram de cal; eu irei derrubá-la, e o seu alicerce ficará exposto. Quando a cidade cair, vocês morrerão dentro dela; e terão de saber que eu sou Jeová.’

[[v26-13-15]]

^<<v26-13-15,15>>^ “‘Quando eu der vazão a todo o meu furor contra aquela parede e contra os que a revestiram de cal, irei dizer-vos: “A parede já não existe, nem aqueles que a revestiram de cal.

[[v26-13-16]]

^<<v26-13-16,16>>^ Os profetas de Israel já não existem, aqueles que profetizavam a Jerusalém e que tinham visões de paz para ela, quando não havia paz”’, diz o Soberano Senhor Jeová.

[[v26-13-17]]

^<<v26-13-17,17>>^ “Quanto a ti, filho do homem, vira o teu rosto contra as filhas do teu povo que inventam as suas próprias profecias, e profetiza contra elas.

[[v26-13-18]]

^<<v26-13-18,18>>^ Diz-lhes: ‘Assim diz o Soberano Senhor Jeová: “Ai das mulheres que costuram fitas para todos os braços^&#42;1^ e fazem véus para a cabeça de pessoas de todas as estaturas, a fim de caçarem a vida^&#42;2^ das pessoas! Por acaso acham que podem caçar a vida^&#42;3^ do meu povo e ainda preservar a vossa própria vida?^&#42;4^

[NOTE]
====
. Isto é, fitas mágicas usadas à volta do cotovelo ou do pulso.
. Ou: “alma”.
. Ou: “alma”.
. Ou: “alma”.
====

[[v26-13-19]]

^<<v26-13-19,19>>^ Profanam-me entre o meu povo em troca de punhados de cevada e de migalhas de pão, entregando à morte os^&#42;1^ que não deviam morrer e preservando vivos os^&#42;2^ que não deviam viver, ao contarem mentiras ao meu povo, que dá ouvidos às vossas mentiras!”’

[NOTE]
====
. Ou: “as almas”.
. Ou: “as almas”.
====

[[v26-13-20]]

^<<v26-13-20,20>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Ó mulheres, vou tomar ação contra as vossas fitas, que usam para caçar pessoas^&#42;1^ como se fossem pássaros. Irei arrancá-las dos vossos braços e soltar as pessoas que vocês caçam como se fossem pássaros.

[NOTE]
====
. Ou: “almas”.
====

[[v26-13-21]]

^<<v26-13-21,21>>^ Arrancarei os vossos véus e livrarei o meu povo das vossas mãos. Eles nunca mais serão uma presa para vocês caçarem, e terão de saber que eu sou Jeová.

[[v26-13-22]]

^<<v26-13-22,22>>^ Pois desanimaram o justo com a vossa falsidade, sem que eu lhe tivesse causado aflição,^&#42;1^ e fortaleceram aquele que é mau, de modo que ele não recua do seu mau caminho para continuar vivo.

[NOTE]
====
. Ou: “dor”.
====

[[v26-13-23]]

^<<v26-13-23,23>>^ Por isso, vocês não terão mais visões falsas nem farão mais adivinhações. Eu vou livrar o meu povo das vossas mãos, e terão de saber que eu sou Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[&#60; Capítulo Anterior] | <<v26-13-0,Topo>> | xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[Próximo Capítulo &#62;]