include::./index.adoc[]

[[v26-32-0]]
=== Ezequiel, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-32-1]]

^<<v26-32-1,1>>^ No décimo segundo ano, no décimo segundo mês, no primeiro dia do mês, recebi novamente a palavra de Jeová:

[[v26-32-2]]

^<<v26-32-2,2>>^ “Filho do homem, canta uma lamentação a respeito do Faraó, rei do Egito, dizendo-lhe:
‘Tu eras como um leão jovem e forte^&#42;1^ das nações,
Mas foste silenciado.
Parecias um monstro marinho, agitando-te nos teus rios,
Turvando a água com os pés e sujando os rios.’^&#42;2^

[NOTE]
====
. Ou: “leão novo jubado”.
. Lit.: “os rios deles”.
====

[[v26-32-3]]

^<<v26-32-3,3>>^ Assim diz o Soberano Senhor Jeová:
‘Através de um grupo de muitas nações, lançarei a minha rede sobre ti,
E elas irão apanhar-te na minha rede de arrasto.

[[v26-32-4]]

^<<v26-32-4,4>>^ Vou abandonar-te em terra;
Vou lançar-te em campo aberto.
Farei com que todas as aves do céu pousem sobre ti,
E com a tua carne saciarei a fome dos animais selvagens de toda a terra.

[[v26-32-5]]

^<<v26-32-5,5>>^ Atirarei a tua carne sobre os montes
E encherei os vales com os restos da tua carcaça.

[[v26-32-6]]

^<<v26-32-6,6>>^ Vou encharcar a terra até às montanhas com o sangue que jorrar de ti,
E ele encherá os rios.’^&#42;1^

[NOTE]
====
. Lit.: “E os leitos ficarão cheios de ti (contigo)”.
====

[[v26-32-7]]

^<<v26-32-7,7>>^ ‘Quando fores destruído,^&#42;1^ cobrirei os céus e escurecerei as suas estrelas.
Encobrirei o sol com nuvens,
E a lua não dará a sua luz.

[NOTE]
====
. Ou: “Quando a tua luz for extinta”.
====

[[v26-32-8]]

^<<v26-32-8,8>>^ Por tua causa, escurecerei todos os luzeiros que brilham nos céus
E cobrirei de escuridão a tua terra’, diz o Soberano Senhor Jeová.

[[v26-32-9]]

^<<v26-32-9,9>>^ ‘Afligirei o coração de muitos povos, quando levar o teu povo cativo para outras nações,
Para terras que não conheces.

[[v26-32-10]]

^<<v26-32-10,10>>^ Farei muitos povos ficarem espantados,
E os seus reis vão tremer de pavor por tua causa, quando eu usar a minha espada diante deles.
Vão tremer sem parar, cada um temendo pela sua própria vida,
No dia da tua queda.’

[[v26-32-11]]

^<<v26-32-11,11>>^ Pois assim diz o Soberano Senhor Jeová:
‘A espada do rei de Babilónia virá sobre ti.

[[v26-32-12]]

^<<v26-32-12,12>>^ Farei as tuas multidões caírem pela espada de guerreiros valentes,
Os mais cruéis das nações, todos eles.
Rebaixarão o orgulho do Egito, e todas as suas multidões serão aniquiladas.

[[v26-32-13]]

^<<v26-32-13,13>>^ Vou destruir todos os seus animais que pastam junto às suas águas abundantes;
Nem pés de homens nem cascos de animais voltarão a turvá-las.’

[[v26-32-14]]

^<<v26-32-14,14>>^ ‘Nesse tempo, limparei as suas águas
E farei os seus rios fluírem como azeite’, diz o Soberano Senhor Jeová.

[[v26-32-15]]

^<<v26-32-15,15>>^ ‘Quando eu fizer do Egito um deserto desolado, uma terra despojada de tudo o que nela há,
Quando golpear todos os seus habitantes,
Então, eles terão de saber que eu sou Jeová.

[[v26-32-16]]

^<<v26-32-16,16>>^ Esta é uma lamentação, e as pessoas certamente a cantarão;
As filhas das nações vão cantá-la.
Vão cantá-la a respeito do Egito e de todas as suas multidões’, diz o Soberano Senhor Jeová.”

[[v26-32-17]]

^<<v26-32-17,17>>^ Então, no décimo segundo ano, no dia 15 do mês, recebi a seguinte palavra de Jeová:

[[v26-32-18]]

^<<v26-32-18,18>>^ “Filho do homem, lamenta as multidões do Egito e manda-a^&#42;1^ para baixo, para as profundezas da terra,^&#42;2^ tanto a ela como às filhas de nações poderosas, com os que descem à cova.^&#42;3^

[NOTE]
====
. Isto é, a nação do Egito.
. Ou: “para a terra das profundezas”.
. Ou: “sepultura”.
====

[[v26-32-19]]

^<<v26-32-19,19>>^ “‘Por acaso és mais belo do que os outros? Desce, e deita-te com os incircuncisos!’

[[v26-32-20]]

^<<v26-32-20,20>>^ “‘Eles cairão entre os mortos pela espada. Ela^&#42;1^ foi entregue à espada; levem-na, com todas as suas multidões.

[NOTE]
====
. Isto é, a nação do Egito.
====

[[v26-32-21]]

^<<v26-32-21,21>>^ “‘Das profundezas da Sepultura,^&#42;1^ os guerreiros mais valentes falarão com ele e com os que o apoiam. Eles certamente descerão e irão deitar-se como os incircuncisos, mortos pela espada.

[NOTE]
====
. Ou: “do Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v26-32-22]]

^<<v26-32-22,22>>^ A Assíria está lá com todas as suas multidões. As suas sepulturas estão ao seu^&#42;1^ redor; todos eles caíram pela espada.

[NOTE]
====
. Possivelmente, refere-se ao rei da Assíria.
====

[[v26-32-23]]

^<<v26-32-23,23>>^ As suas sepulturas estão nas profundezas da cova,^&#42;1^ e as suas multidões estão ao redor da sua sepultura, todos eles mortos pela espada, pois causavam terror na terra dos vivos.

[NOTE]
====
. Ou: “sepultura”.
====

[[v26-32-24]]

^<<v26-32-24,24>>^ “‘Elão está lá com todas as suas multidões ao redor da sua sepultura; todos eles caíram pela espada. Desceram incircuncisos às profundezas da terra^&#42;1^ — os que causavam terror na terra dos vivos. Agora, carregarão a sua vergonha com os que descem à cova.^&#42;2^

[NOTE]
====
. Ou: “à terra das profundezas”.
. Ou: “sepultura”.
====

[[v26-32-25]]

^<<v26-32-25,25>>^ No meio dos mortos, foi preparado um leito para ela,^&#42;1^ com todas as suas multidões ao redor das suas sepulturas. Todos eles são incircuncisos; foram mortos pela espada, pois causavam terror na terra dos vivos. Eles carregarão a sua vergonha com os que descem à cova.^&#42;2^ Ele foi colocado no meio dos mortos.

[NOTE]
====
. Isto é, para a nação de Elão.
. Ou: “sepultura”.
====

[[v26-32-26]]

^<<v26-32-26,26>>^ “‘Lá estão Meseque e Tubal, e todas as suas multidões. As suas sepulturas estão ao seu^&#42;1^ redor. Todos eles são incircuncisos; foram mortos pela espada, pois causavam terror na terra dos vivos.

[NOTE]
====
. Possivelmente, refere-se ao rei de Meseque e Tubal.
====

[[v26-32-27]]

^<<v26-32-27,27>>^ Por acaso, não se deitarão com os valentes guerreiros incircuncisos que caíram, que desceram à Sepultura^&#42;1^ com as suas armas de guerra? As suas espadas serão colocadas debaixo das suas cabeças,^&#42;2^ e os seus pecados sobre os seus ossos, pois estes guerreiros valentes aterrorizavam a terra dos vivos.

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. Talvez seja uma referência a guerreiros enterrados com a sua espada, com honras militares.
====

[[v26-32-28]]

^<<v26-32-28,28>>^ Mas, quanto a ti, serás esmagado entre os incircuncisos, e irás deitar-te com os que foram mortos pela espada.

[[v26-32-29]]

^<<v26-32-29,29>>^ “‘Edom está lá, com os seus reis e todos os seus maiorais. Apesar da sua valentia, eles foram deitados entre os mortos pela espada. Eles também se deitarão com os incircuncisos e com os que descem à cova.^&#42;1^

[NOTE]
====
. Ou: “sepultura”.
====

[[v26-32-30]]

^<<v26-32-30,30>>^ “‘Lá estão todos os príncipes^&#42;1^ do norte, com todos os sidónios, que desceram humilhados com os que foram mortos, apesar do terror que causavam com a sua valentia. Irão deitar-se incircuncisos com os que foram mortos pela espada, e carregarão a sua vergonha com os que descem à cova.^&#42;2^

[NOTE]
====
. Ou: “líderes”.
. Ou: “sepultura”.
====

[[v26-32-31]]

^<<v26-32-31,31>>^ “‘O Faraó verá todos estes e irá sentir-se consolado pelo que aconteceu às suas multidões; o Faraó e todo o seu exército serão mortos pela espada’, diz o Soberano Senhor Jeová.

[[v26-32-32]]

^<<v26-32-32,32>>^ “‘Visto que ele causou terror na terra dos vivos, o Faraó e todas as suas multidões serão deitados com os incircuncisos, com os mortos pela espada’, diz o Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]