include::./index.adoc[]

[[v26-42-0]]
=== Ezequiel, 42
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-42-1]]

^<<v26-42-1,1>>^ Então, ele levou-me ao lado norte do pátio externo. E levou-me ao conjunto dos refeitórios que ficava próximo do espaço livre, a norte do edifício vizinho.

[[v26-42-2]]

^<<v26-42-2,2>>^ O seu comprimento (onde ficava a entrada norte) era de 100 côvados,^&#42;1^ e tinha 50 côvados de largura.

[NOTE]
====
. Isto é, côvados longos. Veja o Ap. B14.
====

[[v26-42-3]]

^<<v26-42-3,3>>^ Ficava entre o pátio interno, que tinha 20 côvados de largura, e o pavimento do pátio externo. As suas galerias ficavam uma de frente para a outra, e tinham três andares de altura.

[[v26-42-4]]

^<<v26-42-4,4>>^ Em frente aos refeitórios,^&#42;1^ havia uma passagem interna de 10 côvados de largura e 100 côvados de comprimento,^&#42;2^ e as entradas dos refeitórios estavam viradas para o norte.

[NOTE]
====
. Ou: “às salas”.
. Segundo a Septuaginta grega: “100 côvados de comprimento”. O texto hebraico diz: “uma passagem de um côvado”. Veja o Ap. B14.
====

[[v26-42-5]]

^<<v26-42-5,5>>^ Os refeitórios do andar superior do edifício eram mais estreitos do que os do andar inferior e os do andar do meio, pois as galerias tiravam-lhes uma parte maior do espaço.

[[v26-42-6]]

^<<v26-42-6,6>>^ Pois eles ficavam em três andares, mas não tinham colunas como as dos pátios. Por isso é que era tirado mais espaço do andar superior do que do andar inferior e do andar do meio.

[[v26-42-7]]

^<<v26-42-7,7>>^ O muro externo de pedra próximo dos refeitórios que ficavam junto ao pátio externo e de frente para os outros refeitórios tinha 50 côvados de comprimento.

[[v26-42-8]]

^<<v26-42-8,8>>^ Pois o comprimento dos refeitórios^&#42;1^ que ficavam junto ao pátio externo era de 50 côvados, mas o dos refeitórios do lado do santuário era de 100 côvados.

[NOTE]
====
. Isto é, o comprimento do conjunto dos refeitórios.
====

[[v26-42-9]]

^<<v26-42-9,9>>^ Os refeitórios tinham uma entrada do lado leste, que lhes dava acesso a partir do pátio externo.

[[v26-42-10]]

^<<v26-42-10,10>>^ Também havia refeitórios atrás^&#42;1^ do muro de pedra do pátio, que dava para o leste, perto do espaço livre e do edifício.

[NOTE]
====
. Lit.: “na largura”.
====

[[v26-42-11]]

^<<v26-42-11,11>>^ Diante deles, havia uma passagem, igual à dos refeitórios do lado norte. Tinham o mesmo comprimento e a mesma largura, e tinham as mesmas saídas e a mesma disposição. As suas entradas

[[v26-42-12]]

^<<v26-42-12,12>>^ eram iguais às entradas dos refeitórios do lado sul. Havia uma entrada no início da passagem, em frente ao muro de pedra adjacente que dava para o leste, por onde se podia entrar.

[[v26-42-13]]

^<<v26-42-13,13>>^ Então, ele disse-me: “Os refeitórios do norte e os refeitórios do sul que ficam perto do espaço livre são os refeitórios sagrados, onde os sacerdotes que se aproximam de Jeová comem as ofertas santíssimas. Ali eles colocam as ofertas santíssimas, a oferta de cereais, a oferta pelo pecado e a oferta pela culpa, pois o lugar é sagrado.

[[v26-42-14]]

^<<v26-42-14,14>>^ Quando os sacerdotes entrarem, não deverão sair do lugar santo para o pátio externo sem antes tirar as vestes que usam para servir, pois elas são sagradas. Eles porão outras vestes para se aproximarem das áreas abertas ao povo.”

[[v26-42-15]]

^<<v26-42-15,15>>^ Quando terminou de medir a área interna do templo,^&#42;1^ ele levou-me para fora pelo portão que dá para o leste e mediu toda a área.

[NOTE]
====
. Lit.: “a casa interna”.
====

[[v26-42-16]]

^<<v26-42-16,16>>^ Ele mediu o lado leste com a cana^&#42;1^ de medir. Segundo a cana de medir, eram 500 canas de um lado ao outro.

[NOTE]
====
. Veja o Ap. B14.
====

[[v26-42-17]]

^<<v26-42-17,17>>^ Mediu o lado norte: segundo a cana de medir, eram 500 canas.

[[v26-42-18]]

^<<v26-42-18,18>>^ Mediu o lado sul: segundo a cana de medir, eram 500 canas.

[[v26-42-19]]

^<<v26-42-19,19>>^ Deu a volta para o lado oeste. Mediu 500 canas com a cana de medir.

[[v26-42-20]]

^<<v26-42-20,20>>^ Ele mediu os quatro lados. Havia uma muralha à volta, de 500 canas de comprimento e 500 canas de largura, para separar o que é santo do que é para uso comum.

'''

xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[&#60; Capítulo Anterior] | <<v26-42-0,Topo>> | xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[Próximo Capítulo &#62;]