include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-7-1]]

^<<v26-7-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-7-2]]

^<<v26-7-2,2>>^ “Filho do homem, assim diz o Soberano Senhor Jeová à terra de Israel: ‘O fim! Chegou o fim sobre os quatro cantos do país.

[[v26-7-3]]

^<<v26-7-3,3>>^ Agora chegou o teu fim. Darei vazão à minha ira contra ti, vou julgar-te conforme os teus caminhos e ajustar contas contigo por todas as tuas ações detestáveis.

[[v26-7-4]]

^<<v26-7-4,4>>^ O meu olho não terá dó de ti, nem terei compaixão, pois trarei sobre ti os efeitos dos teus próprios caminhos, e sofrerás as consequências das tuas ações detestáveis. E vocês terão de saber que eu sou Jeová.’

[[v26-7-5]]

^<<v26-7-5,5>>^ “Assim diz o Soberano Senhor Jeová: ‘Vejam! Está a chegar uma calamidade, uma calamidade sem igual.

[[v26-7-6]]

^<<v26-7-6,6>>^ O fim está a chegar. O fim chegará; ele vai levantar-se^&#42;1^ contra ti. Vê! Ele está a chegar.

[NOTE]
====
. Lit.: “despertou”.
====

[[v26-7-7]]

^<<v26-7-7,7>>^ Chegou a tua vez,^&#42;1^ ó habitante do país. Está a chegar o momento, o dia está próximo. Há pânico nos montes, não gritos de alegria.

[NOTE]
====
. Ou, possivelmente: “a grinalda”.
====

[[v26-7-8]]

^<<v26-7-8,8>>^ “‘Muito em breve, derramarei sobre ti o meu furor e darei vazão a toda a minha ira contra ti. Vou julgar-te conforme os teus caminhos e ajustar contas contigo por todas as tuas ações detestáveis.

[[v26-7-9]]

^<<v26-7-9,9>>^ O meu olho não terá dó, nem terei compaixão. Trarei sobre ti os efeitos dos teus caminhos e sofrerás as consequências das tuas próprias ações detestáveis. E vocês terão de saber que eu, Jeová, vos estou a golpear.

[[v26-7-10]]

^<<v26-7-10,10>>^ “‘Vejam, o dia! Vejam, está a chegar! Chegou a tua vez;^&#42;1^ a vara já brotou e a insolência já floresceu.

[NOTE]
====
. Ou, possivelmente: “a grinalda”.
====

[[v26-7-11]]

^<<v26-7-11,11>>^ A violência cresceu e tornou-se uma vara de maldade. Nem eles, nem a sua riqueza, nem as suas multidões, nem a sua fama sobreviverão.

[[v26-7-12]]

^<<v26-7-12,12>>^ O tempo virá, o dia chegará. Que o comprador não se alegre e o vendedor não se lamente, porque há furor contra toda a sua multidão.^&#42;1^

[NOTE]
====
. Isto é, nem os que compram uma propriedade nem os que a vendem irão beneficiar-se, visto que a destruição virá sobre todos.
====

[[v26-7-13]]

^<<v26-7-13,13>>^ Porque o vendedor não voltará à propriedade que vendeu, mesmo que a sua vida seja poupada, pois a visão é contra toda a multidão. Ninguém voltará. Por causa do seu erro,^&#42;1^ ninguém preservará a sua própria vida.

[NOTE]
====
. Ou, possivelmente: “Por meios injustos”.
====

[[v26-7-14]]

^<<v26-7-14,14>>^ “‘Tocaram a trombeta e todos estão prontos, mas ninguém vai à batalha, pois o meu furor é contra toda a multidão.

[[v26-7-15]]

^<<v26-7-15,15>>^ Do lado de fora está a espada, e do lado de dentro há peste e fome. Quem estiver no campo morrerá pela espada, e quem estiver na cidade será devorado pela fome e pela peste.

[[v26-7-16]]

^<<v26-7-16,16>>^ Os seus sobreviventes que conseguirem escapar irão para os montes; como as pombas dos vales, cada um gemerá por causa do seu próprio erro.

[[v26-7-17]]

^<<v26-7-17,17>>^ Todas as mãos ficarão caídas, e pingará água de todos os joelhos.^&#42;1^

[NOTE]
====
. Isto é, pingará urina devido ao medo.
====

[[v26-7-18]]

^<<v26-7-18,18>>^ Vestiram-se de serapilheira,^&#42;1^ e um tremor tomou conta deles.^&#42;2^ Todos serão envergonhados, e todas as cabeças ficarão calvas.^&#42;3^

[NOTE]
====
. Veja o Glossário.
. Lit.: “cobriu-os”.
. Isto é, as suas cabeças serão rapadas em sinal de luto.
====

[[v26-7-19]]

^<<v26-7-19,19>>^ “‘Lançarão a sua prata nas ruas e abominarão o seu ouro. Nem a sua prata nem o seu ouro os poderá salvar no dia da fúria de Jeová. Eles não ficarão satisfeitos^&#42;1^ nem encherão o seu estômago, pois a sua prata e o seu ouro hão de tornar-se uma pedra de tropeço, causando o seu erro.

[NOTE]
====
. Ou: “As suas almas não ficarão satisfeitas”.
====

[[v26-7-20]]

^<<v26-7-20,20>>^ Eles orgulharam-se da beleza dos seus enfeites, e com eles^&#42;1^ fizeram as suas imagens detestáveis, os seus ídolos repugnantes. É por isso que vou fazer com que a sua prata e o seu ouro se tornem abomináveis para eles.

[NOTE]
====
. Isto é, com os seus objetos de ouro e de prata.
====

[[v26-7-21]]

^<<v26-7-21,21>>^ Vou entregá-los^&#42;1^ como despojo nas mãos de estrangeiros, como espólio nas mãos dos perversos da terra, e eles irão profaná-los.

[NOTE]
====
. Isto é, a sua prata e o seu ouro usados para fazer ídolos.
====

[[v26-7-22]]

^<<v26-7-22,22>>^ “‘Desviarei deles a minha face, e eles profanarão o meu lugar escondido;^&#42;1^ ladrões entrarão lá e irão profaná-lo.

[NOTE]
====
. Aparentemente, refere-se à parte mais interna do santuário de Jeová.
====

[[v26-7-23]]

^<<v26-7-23,23>>^ “‘Faz as correntes,^&#42;1^ pois o país está cheio de julgamentos sangrentos, e a cidade está cheia de violência.

[NOTE]
====
. Isto é, correntes para prender cativos.
====

[[v26-7-24]]

^<<v26-7-24,24>>^ Vou trazer a pior das nações, e hão de apossar-se das suas casas. Porei fim ao orgulho dos fortes, e os seus santuários serão profanados.

[[v26-7-25]]

^<<v26-7-25,25>>^ Quando chegar a angústia, eles procurarão a paz, mas ela não existirá.

[[v26-7-26]]

^<<v26-7-26,26>>^ Virá um desastre após outro, e uma notícia após outra. As pessoas recorrerão a um profeta em busca de uma visão, mas a lei^&#42;1^ dos sacerdotes e o conselho dos anciãos deixarão de existir.

[NOTE]
====
. Ou: “instrução”.
====

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei ficará de luto, o maioral estará vestido de desespero,^&#42;1^ e as mãos do povo da terra tremerão de pavor. Vou tratá-los conforme os seus caminhos e vou julgá-los da mesma maneira que eles julgaram outros. E eles terão de saber que eu sou Jeová.’”

[NOTE]
====
. Ou: “desolação”.
====

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]