include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-40-1]]

^<<v26-40-1,1>>^ No vigésimo quinto ano do nosso exílio, no começo do ano, no dia dez do mês, no décimo quarto ano depois da queda da cidade, nesse mesmo dia, a mão de Jeová esteve sobre mim, e ele levou-me à cidade.

[[v26-40-2]]

^<<v26-40-2,2>>^ Nas visões da parte de Deus, ele levou-me à terra de Israel e pôs-me sobre um monte muito alto, onde havia, a sul, uma estrutura semelhante a uma cidade.

[[v26-40-3]]

^<<v26-40-3,3>>^ Quando ele me levou para lá, eu vi um homem que parecia ter o aspeto de cobre. Ele tinha na mão uma corda de linho e uma cana^&#42;1^ de medir, e estava de pé no portão.

[NOTE]
====
. Veja o Ap. B14.
====

[[v26-40-4]]

^<<v26-40-4,4>>^ O homem disse-me: “Filho do homem, olha bem, escuta atentamente e presta atenção^&#42;1^ a tudo o que eu te mostrar, pois foi por isso que foste trazido até aqui. Conta à casa de Israel tudo o que vires.”

[NOTE]
====
. Lit.: “fixa o teu coração”.
====

[[v26-40-5]]

^<<v26-40-5,5>>^ Eu vi uma muralha à volta da área externa do templo.^&#42;1^ Na mão do homem, havia uma cana de medir de seis côvados (cada côvado tinha uma largura da mão a mais).^&#42;2^ Ele começou a medir a muralha: a sua espessura era de uma cana e a sua altura era de uma cana.

[NOTE]
====
. Lit.: “da casa”. Esta palavra é traduzida “templo” nos capítulos 40-48, quando se refere ao complexo do templo ou ao próprio edifício do templo.
. Lit.: “uma cana de medir de seis côvados, um côvado e uma largura da mão”. Isto refere-se a côvados longos. Veja o Ap. B14.
====

[[v26-40-6]]

^<<v26-40-6,6>>^ Então, ele foi até ao portão que dava para o leste e subiu os degraus. Mediu o limiar do portão: tinha uma cana de largura, e o outro limiar também tinha uma cana de largura.

[[v26-40-7]]

^<<v26-40-7,7>>^ Cada sala da guarda media uma cana de comprimento e uma cana de largura, e havia cinco côvados entre as salas da guarda. O limiar do portão que ficava ao pé do pórtico do portão, que dava para o lado de dentro, media uma cana.

[[v26-40-8]]

^<<v26-40-8,8>>^ Ele mediu o pórtico do portão, que dava para o lado de dentro: uma cana.

[[v26-40-9]]

^<<v26-40-9,9>>^ Em seguida, mediu o pórtico do portão: oito côvados, e mediu as suas colunas laterais: dois côvados. O pórtico do portão dava para o lado de dentro.

[[v26-40-10]]

^<<v26-40-10,10>>^ Havia três salas da guarda de cada lado do portão leste. As três tinham o mesmo tamanho, e as colunas laterais que havia de cada lado tinham o mesmo tamanho.

[[v26-40-11]]

^<<v26-40-11,11>>^ A seguir, ele mediu a largura da entrada do portão: 10 côvados, e a extensão^&#42;1^ do portão^&#42;2^ era de 13 côvados.

[NOTE]
====
. Lit.: “o comprimento”.
. Ou: “da entrada do portão”.
====

[[v26-40-12]]

^<<v26-40-12,12>>^ A área murada em frente às salas da guarda que havia dos dois lados media um côvado. As salas da guarda que havia dos dois lados mediam seis côvados.

[[v26-40-13]]

^<<v26-40-13,13>>^ Depois, ele mediu o portão desde o teto de uma sala da guarda^&#42;1^ até ao teto da outra: eram 25 côvados de largura; a entrada de uma ficava de frente para a entrada da outra.

[NOTE]
====
. Possivelmente, refere-se ao alto da parede da sala da guarda.
====

[[v26-40-14]]

^<<v26-40-14,14>>^ Então, mediu as colunas laterais, que tinham 60 côvados de altura, assim como as colunas laterais dos portões ao redor do pátio.

[[v26-40-15]]

^<<v26-40-15,15>>^ Desde a frente da entrada do portão até à frente do pórtico, na parte do portão que dava para dentro, havia 50 côvados.

[[v26-40-16]]

^<<v26-40-16,16>>^ Dentro do portão, nas salas da guarda e nas suas colunas laterais, nos dois lados, havia janelas de vãos que se estreitavam.^&#42;1^ O interior dos pórticos também tinha janelas nos dois lados, e havia figuras de palmeiras nas colunas laterais.

[NOTE]
====
. Ou: “janelas chanfradas”.
====

[[v26-40-17]]

^<<v26-40-17,17>>^ Depois, ele levou-me ao pátio externo, e eu vi refeitórios^&#42;1^ e um pavimento à volta do pátio. Havia 30 refeitórios no pavimento.

[NOTE]
====
. Ou: “salas”.
====

[[v26-40-18]]

^<<v26-40-18,18>>^ O pavimento ficava ao lado dos portões e a sua largura correspondia ao comprimento dos portões — este era o pavimento inferior.

[[v26-40-19]]

^<<v26-40-19,19>>^ A seguir, ele mediu a distância^&#42;1^ desde o portão inferior até ao início do pátio interno. Era de 100 côvados do lado leste e do lado norte.

[NOTE]
====
. Lit.: “largura”.
====

[[v26-40-20]]

^<<v26-40-20,20>>^ O pátio externo tinha um portão que dava para o norte, e ele mediu o seu comprimento e a sua largura.

[[v26-40-21]]

^<<v26-40-21,21>>^ Havia três salas da guarda de cada lado. As colunas laterais e o pórtico dele tinham o mesmo tamanho que os do primeiro portão. Ele media 50 côvados de comprimento e 25 côvados de largura.

[[v26-40-22]]

^<<v26-40-22,22>>^ As suas janelas, o seu pórtico e as suas figuras de palmeiras tinham o mesmo tamanho que os do portão leste. Podia-se entrar nele por subir sete degraus, e o seu pórtico ficava depois deles.

[[v26-40-23]]

^<<v26-40-23,23>>^ No pátio interno havia um portão em frente ao portão norte e um em frente ao portão leste. Ele mediu a distância entre um portão e o outro: 100 côvados.

[[v26-40-24]]

^<<v26-40-24,24>>^ Então, ele levou-me para o sul, e eu vi ali um portão no lado sul. Ele mediu as suas colunas laterais e o seu pórtico: tinham o mesmo tamanho que os outros.

[[v26-40-25]]

^<<v26-40-25,25>>^ Havia janelas nos dois lados do portão e do seu pórtico, iguais às outras janelas. Ele media 50 côvados de comprimento e 25 côvados de largura.

[[v26-40-26]]

^<<v26-40-26,26>>^ Havia sete degraus que lhe davam acesso, e o seu pórtico ficava depois deles. Ele tinha figuras de palmeiras nas suas colunas laterais, uma de cada lado.

[[v26-40-27]]

^<<v26-40-27,27>>^ O pátio interno também tinha um portão que dava para o sul; ele mediu a distância entre os dois portões que davam para o sul: 100 côvados.

[[v26-40-28]]

^<<v26-40-28,28>>^ A seguir, ele levou-me ao pátio interno pelo portão sul e mediu o portão sul: tinha o mesmo tamanho que os outros.

[[v26-40-29]]

^<<v26-40-29,29>>^ As suas salas da guarda, as suas colunas laterais e o seu pórtico tinham o mesmo tamanho que os outros. Havia janelas nos dois lados do portão e do seu pórtico. Ele media 50 côvados de comprimento e 25 côvados de largura.

[[v26-40-30]]

^<<v26-40-30,30>>^ Havia pórticos a toda a volta; mediam 25 côvados de comprimento e 5 côvados de largura.

[[v26-40-31]]

^<<v26-40-31,31>>^ O pórtico do portão sul dava para o pátio externo, e tinha figuras de palmeiras nas suas colunas laterais, e oito degraus davam-lhe acesso.

[[v26-40-32]]

^<<v26-40-32,32>>^ Ele levou-me do lado leste ao pátio interno e mediu o portão: tinha o mesmo tamanho que os outros.

[[v26-40-33]]

^<<v26-40-33,33>>^ As suas salas da guarda, as suas colunas laterais e o seu pórtico tinham o mesmo tamanho que os outros, e havia janelas nos dois lados do portão e do seu pórtico. Ele media 50 côvados de comprimento e 25 côvados de largura.

[[v26-40-34]]

^<<v26-40-34,34>>^ O seu pórtico dava para o pátio externo, e tinha figuras de palmeiras nas suas duas colunas laterais, e oito degraus davam-lhe acesso.

[[v26-40-35]]

^<<v26-40-35,35>>^ A seguir, ele levou-me ao portão norte e mediu-o: tinha o mesmo tamanho que os outros.

[[v26-40-36]]

^<<v26-40-36,36>>^ As suas salas da guarda, as suas colunas laterais e o seu pórtico tinham o mesmo tamanho que os outros. Ele tinha janelas nos dois lados. Media 50 côvados de comprimento e 25 côvados de largura.

[[v26-40-37]]

^<<v26-40-37,37>>^ As suas colunas laterais davam para o pátio externo, e havia figuras de palmeiras nas suas duas colunas laterais, e oito degraus davam-lhe acesso.

[[v26-40-38]]

^<<v26-40-38,38>>^ Perto das colunas laterais dos portões, havia um refeitório com uma entrada, onde eram lavadas as ofertas queimadas.

[[v26-40-39]]

^<<v26-40-39,39>>^ De cada lado do pórtico do portão,^&#42;1^ havia duas mesas onde se abatiam as ofertas queimadas, as ofertas pelo pecado e as ofertas pela culpa.

[NOTE]
====
. Isto é, do portão norte.
====

[[v26-40-40]]

^<<v26-40-40,40>>^ Do lado de fora da entrada, por onde se sobe para o portão norte, havia duas mesas. E também havia duas mesas do outro lado do pórtico do portão.

[[v26-40-41]]

^<<v26-40-41,41>>^ Havia quatro mesas de cada lado do portão — oito mesas ao todo —, nas quais se abatiam os sacrifícios.

[[v26-40-42]]

^<<v26-40-42,42>>^ As quatro mesas para as ofertas queimadas eram de pedras talhadas. Tinham um côvado e meio de comprimento, um côvado e meio de largura e um côvado de altura. Sobre elas eram mantidos os utensílios para abater as ofertas queimadas e os sacrifícios.

[[v26-40-43]]

^<<v26-40-43,43>>^ Havia prateleiras da largura da mão presas nas paredes internas, em toda a volta, e sobre as mesas era posta a carne das ofertas.

[[v26-40-44]]

^<<v26-40-44,44>>^ Do lado de fora do portão interno, havia os refeitórios dos cantores; eles ficavam no pátio interno, perto do portão norte, de frente para o sul. Havia outro refeitório perto do portão leste, de frente para o norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ Ele disse-me: “Este refeitório que dá para o sul é para os sacerdotes responsáveis pelos serviços no templo.

[[v26-40-46]]

^<<v26-40-46,46>>^ O refeitório que dá para o norte é para os sacerdotes responsáveis pelo serviço do altar. São os filhos de Zadoque, aqueles dentre os levitas que são designados para se aproximarem de Jeová, a fim de o servirem.”

[[v26-40-47]]

^<<v26-40-47,47>>^ A seguir, ele mediu o pátio interno: era quadrado, com 100 côvados de comprimento e 100 côvados de largura. O altar ficava em frente ao templo.

[[v26-40-48]]

^<<v26-40-48,48>>^ Depois, ele levou-me ao pórtico do templo e mediu as colunas laterais do pórtico: a de um lado tinha cinco côvados e a do outro lado tinha cinco côvados. A largura do portão^&#42;1^ era de três côvados de um lado e de três côvados do outro lado.

[NOTE]
====
. Ou: “da coluna”.
====

[[v26-40-49]]

^<<v26-40-49,49>>^ O pórtico media 20 côvados de largura e 11^&#42;1^ côvados de profundidade. Para se chegar até lá, subia-se os degraus. E havia pilares ao lado das colunas laterais, uma de cada lado.

[NOTE]
====
. Ou, possivelmente: “12”.
====

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]