include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-16-1]]

^<<v26-16-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-16-2]]

^<<v26-16-2,2>>^ “Filho do homem, expõe a Jerusalém as suas práticas detestáveis.

[[v26-16-3]]

^<<v26-16-3,3>>^ Diz: ‘Assim diz o Soberano Senhor Jeová a Jerusalém: “A tua origem e o teu nascimento foram na terra dos cananeus. O teu pai era amorreu, e a tua mãe era hitita.

[[v26-16-4]]

^<<v26-16-4,4>>^ Quanto ao teu nascimento, no dia em que nasceste, não te cortaram o cordão umbilical, nem te lavaram com água para te deixar limpa, nem te esfregaram com sal, nem te enrolaram em panos.

[[v26-16-5]]

^<<v26-16-5,5>>^ Ninguém teve dó de ti a ponto de te fazer alguma destas coisas. Ninguém teve compaixão de ti. Pelo contrário, foste atirada para campo aberto, pois tu foste^&#42;1^ odiada no dia em que nasceste.

[NOTE]
====
. Ou: “a tua alma foi”.
====

[[v26-16-6]]

^<<v26-16-6,6>>^ “‘“Quando passei por ali, vi-te a espernear no teu próprio sangue e, enquanto estavas ali deitada no teu sangue, eu disse: ‘Continua a viver!’ Sim, disse-te enquanto estavas ali deitada no teu sangue: ‘Continua a viver!’

[[v26-16-7]]

^<<v26-16-7,7>>^ Fiz de ti uma multidão muito grande, como as plantas que brotam no campo. Tu cresceste, desenvolveste-te e passaste a usar os enfeites mais belos. Os teus seios ficaram firmes e os teus cabelos cresceram, mas tu ainda estavas nua e exposta.”’

[[v26-16-8]]

^<<v26-16-8,8>>^ “‘Quando eu passei e te vi, notei que já tinhas idade para expressões de amor. Por isso, estendi a minha roupa^&#42;1^ sobre ti e cobri a tua nudez, fiz um juramento e entrei num pacto contigo’, diz o Soberano Senhor Jeová, ‘e tu tornaste-te minha.

[NOTE]
====
. Ou: “saia”.
====

[[v26-16-9]]

^<<v26-16-9,9>>^ Além disso, lavei-te com água, limpei o teu sangue e pus-te óleo na pele.

[[v26-16-10]]

^<<v26-16-10,10>>^ Então, vesti-te com uma roupa bordada e dei-te sandálias de couro da melhor qualidade.^&#42;1^ Envolvi-te com linho fino e vesti-te com roupas caras.

[NOTE]
====
. Ou: “sandálias de pele de foca”.
====

[[v26-16-11]]

^<<v26-16-11,11>>^ Enfeitei-te com adornos, coloquei pulseiras nos teus braços^&#42;1^ e um colar no teu pescoço.

[NOTE]
====
. Ou: “nas tuas mãos”.
====

[[v26-16-12]]

^<<v26-16-12,12>>^ Também te coloquei uma argola no nariz, brincos nas orelhas e uma bela coroa na cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ Enfeitavas-te com ouro e prata, e vestias-te com linho fino, tecidos caros e uma roupa bordada. A tua comida era farinha fina, mel e azeite. Tornaste-te extremamente bela, e estavas pronta para te tornares rainha.’”^&#42;1^

[NOTE]
====
. Ou: “pronta para uma posição real”.
====

[[v26-16-14]]

^<<v26-16-14,14>>^ “‘A tua fama^&#42;1^ começou a espalhar-se pelas nações por causa da tua beleza, pois era perfeita devido ao meu esplendor, que eu tinha posto sobre ti’, diz o Soberano Senhor Jeová.”

[NOTE]
====
. Lit.: “O teu nome”.
====

[[v26-16-15]]

^<<v26-16-15,15>>^ “‘Mas começaste a confiar na tua beleza, e tornaste-te prostituta devido à tua fama. Prostituíste-te fartamente com todos os que passavam, e a tua beleza tornou-se deles.

[[v26-16-16]]

^<<v26-16-16,16>>^ Pegaste em algumas das tuas roupas e fizeste com elas altos sagrados coloridos, onde te prostituías. Tais coisas não deveriam ocorrer; nem nunca deveriam acontecer.

[[v26-16-17]]

^<<v26-16-17,17>>^ Além disso, pegaste nas belas joias^&#42;1^ de ouro e de prata que eu te tinha dado, fizeste com elas imagens de homens e prostituíste-te com elas.

[NOTE]
====
. Ou: “nos belos ornamentos”.
====

[[v26-16-18]]

^<<v26-16-18,18>>^ Pegaste nas tuas roupas bordadas e cobriste-as^&#42;1^ com elas, e ofereceste-lhes o meu óleo e o meu incenso.

[NOTE]
====
. Isto é, as imagens de homens.
====

[[v26-16-19]]

^<<v26-16-19,19>>^ E o pão que eu te tinha dado — feito de farinha fina, azeite e mel, que eu te tinha dado para comeres — tu também lhes ofereceste como aroma agradável.^&#42;1^ Foi exatamente isso o que aconteceu’, diz o Soberano Senhor Jeová.”

[NOTE]
====
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v26-16-20]]

^<<v26-16-20,20>>^ “‘Pegaste nos filhos e nas filhas que me tinhas gerado e sacrificaste-os a imagens para que fossem consumidos — não bastavam os teus atos de prostituição?

[[v26-16-21]]

^<<v26-16-21,21>>^ Mataste os meus filhos e ofereceste-os como sacrifício, queimando-os no fogo.^&#42;1^

[NOTE]
====
. Ou: “fazendo-os passar pelo fogo”.
====

[[v26-16-22]]

^<<v26-16-22,22>>^ Enquanto fazias todas estas coisas detestáveis e te prostituías, não te lembravas dos dias da tua juventude, quando estavas nua e exposta, e esperneavas no teu próprio sangue.

[[v26-16-23]]

^<<v26-16-23,23>>^ Depois de cometeres toda esta maldade, ai, ai de ti!’, diz o Soberano Senhor Jeová.

[[v26-16-24]]

^<<v26-16-24,24>>^ ‘Construíste uma elevação e fizeste um alto sagrado em cada praça.

[[v26-16-25]]

^<<v26-16-25,25>>^ Construíste os teus altos sagrados no lugar mais destacado de cada rua e fizeste da tua beleza algo detestável, oferecendo-te^&#42;1^ a todos os que passavam, multiplicando os teus atos de prostituição.

[NOTE]
====
. Lit.: “abrindo as tuas pernas”.
====

[[v26-16-26]]

^<<v26-16-26,26>>^ Prostituíste-te com os filhos do Egito, os teus vizinhos devassos,^&#42;1^ e ofendeste-me com os teus incontáveis atos de prostituição.

[NOTE]
====
. Lit.: “os teus vizinhos grandes de carne”.
====

[[v26-16-27]]

^<<v26-16-27,27>>^ Por isso, estenderei a mão contra ti e reduzirei a tua porção de comida. Vou entregar-te à mercê^&#42;1^ daquelas que te odeiam, as filhas dos filisteus, que ficaram chocadas com a tua conduta obscena.

[NOTE]
====
. Ou: “alma”.
====

[[v26-16-28]]

^<<v26-16-28,28>>^ “‘Visto que não te conseguias satisfazer, prostituíste-te com os filhos da Assíria. Mas, mesmo depois de te prostituíres com eles, ainda não ficaste satisfeita.

[[v26-16-29]]

^<<v26-16-29,29>>^ Então, aumentaste a tua prostituição, estendendo-a à terra dos comerciantes^&#42;1^ e aos caldeus, mas nem assim ficaste satisfeita.

[NOTE]
====
. Lit.: “terra de Canaã”.
====

[[v26-16-30]]

^<<v26-16-30,30>>^ Como estava doente^&#42;1^ o teu coração’,^&#42;2^ diz o Soberano Senhor Jeová, ‘quando fizeste todas estas coisas, agindo como uma prostituta descarada!

[NOTE]
====
. Ou: “fraco”.
. Ou, possivelmente: “Como estou furioso contigo”.
====

[[v26-16-31]]

^<<v26-16-31,31>>^ Mas, quando construíste a tua elevação no lugar mais destacado de cada rua e fizeste o teu alto sagrado em cada praça, não agias como uma prostituta, pois não querias receber nenhum pagamento.

[[v26-16-32]]

^<<v26-16-32,32>>^ És uma esposa adúltera, que recebe estranhos em vez do seu marido!

[[v26-16-33]]

^<<v26-16-33,33>>^ Todas as prostitutas recebem presentes, mas, no teu caso, és tu que dás presentes a todos os que te desejam ardentemente. Tu suborna-los para que venham de todas as partes até ti, para que te prostituas com eles.

[[v26-16-34]]

^<<v26-16-34,34>>^ Tu és o oposto das outras mulheres que se prostituem. Ninguém se prostitui como tu! Tu pagas aos outros, em vez de eles te pagarem a ti. Fazes justamente o contrário.’

[[v26-16-35]]

^<<v26-16-35,35>>^ “Portanto, ó prostituta, ouve a palavra de Jeová.

[[v26-16-36]]

^<<v26-16-36,36>>^ Assim diz o Soberano Senhor Jeová: ‘Excedeste-te na tua paixão ardente e expuseste a tua nudez na tua prostituição com os teus amantes e com todos os teus ídolos detestáveis e repugnantes,^&#42;1^ aos quais até mesmo sacrificaste o sangue dos teus filhos.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-16-37]]

^<<v26-16-37,37>>^ Portanto, vou reunir todos os teus amantes, aos quais davas prazer, todos os que amaste e todos os que odiaste. Vou reuni-los contra ti de todas as partes, vou expor-lhes a tua nudez e eles irão ver-te completamente nua.

[[v26-16-38]]

^<<v26-16-38,38>>^ “‘E vou aplicar-te a punição que cabe às mulheres adúlteras e às que derramam sangue, e o teu sangue será derramado com furor e ciúme.

[[v26-16-39]]

^<<v26-16-39,39>>^ Vou entregar-te nas suas mãos, e eles derrubarão as tuas elevações e demolirão os teus altos sagrados. Arrancarão as tuas roupas, tirarão as tuas belas joias^&#42;1^ e irão deixar-te nua e exposta.

[NOTE]
====
. Ou: “os teus belos ornamentos”.
====

[[v26-16-40]]

^<<v26-16-40,40>>^ Eles trarão contra ti uma multidão, irão apedrejar-te e matar-te com as suas espadas.

[[v26-16-41]]

^<<v26-16-41,41>>^ Queimarão as tuas casas com fogo e executarão em ti o julgamento diante dos olhos de muitas mulheres. Porei fim à tua prostituição, e tu vais parar de lhes pagar.

[[v26-16-42]]

^<<v26-16-42,42>>^ Saciarei o meu furor contra ti, e a minha indignação irá desviar-se de ti. Vou acalmar-me e nunca mais me sentirei ofendido.’

[[v26-16-43]]

^<<v26-16-43,43>>^ “‘Visto que não te lembraste dos dias da tua juventude e me enfureceste com tudo o que fizeste, eu farei as consequências do teu proceder recaírem sobre a tua própria cabeça’, diz o Soberano Senhor Jeová, ‘e tu já não continuarás na tua conduta obscena e nas tuas práticas detestáveis.

[[v26-16-44]]

^<<v26-16-44,44>>^ “‘Todos os que citam provérbios aplicarão este provérbio a ti: “Tal mãe, tal filha!”

[[v26-16-45]]

^<<v26-16-45,45>>^ És mesmo filha da tua mãe, que desprezava o marido e os filhos. E és mesmo irmã das tuas irmãs, que desprezavam o marido e os filhos. A vossa mãe era hitita, e o vosso pai era amorreu.’”

[[v26-16-46]]

^<<v26-16-46,46>>^ “‘A tua irmã mais velha é Samaria, que mora a norte de ti^&#42;1^ com as suas filhas,^&#42;2^ e a tua irmã mais nova é Sodoma, que mora a sul de ti^&#42;3^ com as suas filhas.

[NOTE]
====
. Lit.: “à tua esquerda”.
. Provavelmente, refere-se a aldeias dependentes.
. Lit.: “à tua direita”.
====

[[v26-16-47]]

^<<v26-16-47,47>>^ Não só andaste nos seus caminhos e imitaste as suas práticas detestáveis, mas, em pouco tempo, corrompeste-te ainda mais do que elas em toda a tua conduta.

[[v26-16-48]]

^<<v26-16-48,48>>^ Tão certo como eu vivo’, diz o Soberano Senhor Jeová, ‘a tua irmã Sodoma e as suas filhas nunca fizeram o que tu e as tuas filhas fizeram.

[[v26-16-49]]

^<<v26-16-49,49>>^ Este foi o erro da tua irmã Sodoma: ela e as suas filhas eram orgulhosas, tinham fartura de comida e viviam despreocupadas, mas não ajudaram os oprimidos e os pobres.

[[v26-16-50]]

^<<v26-16-50,50>>^ Elas continuaram arrogantes e praticaram coisas detestáveis diante de mim, de modo que achei necessário eliminá-las.

[[v26-16-51]]

^<<v26-16-51,51>>^ “‘Samaria também não cometeu nem metade dos teus pecados. Fizeste muito mais coisas detestáveis do que as tuas irmãs, a ponto de as fazeres parecerem justas por causa de todas as tuas práticas detestáveis.

[[v26-16-52]]

^<<v26-16-52,52>>^ Agora, suporta a tua humilhação, pois justificaste a conduta das tuas irmãs.^&#42;1^ Em vista do teu pecado, ao agires de maneira mais detestável do que elas, elas são mais justas do que tu. Então, agora, envergonha-te e suporta a humilhação de fazeres as tuas irmãs parecerem justas.’

[NOTE]
====
. Ou: “intercedeste pelas tuas irmãs”.
====

[[v26-16-53]]

^<<v26-16-53,53>>^ “‘E vou reunir os cativos delas: os cativos de Sodoma e das suas filhas e os cativos de Samaria e das suas filhas; vou reunir também os teus cativos, juntamente com eles,

[[v26-16-54]]

^<<v26-16-54,54>>^ para que suportes a tua humilhação; tu irás sentir-te humilhada por causa do que fizeste, que lhes serviu de consolo.

[[v26-16-55]]

^<<v26-16-55,55>>^ Quanto às tuas próprias irmãs, Sodoma e as suas filhas voltarão a ser como antes, e Samaria e as suas filhas voltarão a ser como antes. Tu e as tuas filhas também voltarão a ser como antes.

[[v26-16-56]]

^<<v26-16-56,56>>^ A tua irmã Sodoma não era digna de ser mencionada por ti na altura em que eras orgulhosa,

[[v26-16-57]]

^<<v26-16-57,57>>^ antes de a tua própria maldade ser exposta. Agora, as filhas da Síria e as suas vizinhas insultam-te, e as filhas dos filisteus, todos à tua volta, tratam-te com desprezo.

[[v26-16-58]]

^<<v26-16-58,58>>^ Sofrerás as consequências da tua conduta obscena e das tuas práticas detestáveis’, diz Jeová.”

[[v26-16-59]]

^<<v26-16-59,59>>^ “Pois assim diz o Soberano Senhor Jeová: ‘Agora, farei contigo exatamente o que fizeste, porque desprezaste o juramento, violando o meu pacto.

[[v26-16-60]]

^<<v26-16-60,60>>^ Mas eu irei lembrar-me do pacto que fiz contigo nos dias da tua juventude e estabelecerei contigo um pacto permanente.

[[v26-16-61]]

^<<v26-16-61,61>>^ Irás lembrar-te da tua conduta e irás sentir-te humilhada ao acolheres as tuas irmãs, tanto as mais velhas como as mais novas; e eu irei dar-tas como filhas, mas não por causa do pacto feito contigo.’

[[v26-16-62]]

^<<v26-16-62,62>>^ “‘E eu vou estabelecer contigo o meu pacto, e terás de saber que eu sou Jeová.

[[v26-16-63]]

^<<v26-16-63,63>>^ Então, quando eu fizer expiação em teu favor, apesar de todas as coisas que fizeste, irás lembrar-te destas coisas e ficarás tão envergonhada que nem abrirás a boca por causa da tua humilhação’, diz o Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]