include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo ano, no décimo mês, no dia 12 do mês, recebi a seguinte palavra de Jeová:

[[v26-29-2]]

^<<v26-29-2,2>>^ “Filho do homem, vira-te para o Faraó, rei do Egito, e profetiza contra ele e contra todo o Egito.

[[v26-29-3]]

^<<v26-29-3,3>>^ Diz estas palavras: ‘Assim diz o Soberano Senhor Jeová:
“Eu estou contra ti, Faraó, rei do Egito,
O grande monstro marinho que está deitado entre os canais do seu Nilo,^&#42;1^
Aquele que disse: ‘O rio Nilo é meu;
Eu fi-lo para mim.’

[NOTE]
====
. Nesta ocorrência e nas próximas, a palavra “Nilo” refere-se ao rio e aos seus canais de irrigação.
====

[[v26-29-4]]

^<<v26-29-4,4>>^ Contudo, porei ganchos nas tuas mandíbulas e farei com que os peixes do teu Nilo se agarrem às tuas escamas.
Vou tirar-te do teu Nilo, com todos os peixes do Nilo que se agarrarem às tuas escamas.

[[v26-29-5]]

^<<v26-29-5,5>>^ Vou abandonar-te no deserto, a ti e a todos os peixes do teu Nilo.
Cairás em campo aberto e ficarás no chão; não serás recolhido.
Vou dar-te como comida aos animais selvagens da terra e às aves do céu.

[[v26-29-6]]

^<<v26-29-6,6>>^ Então, todos os habitantes do Egito terão de saber que eu sou Jeová,
Pois eles, como apoio, não passaram de uma haste seca^&#42;1^ para a casa de Israel.

[NOTE]
====
. Lit.: “uma cana”.
====

[[v26-29-7]]

^<<v26-29-7,7>>^ Quando te agarraram a mão, partiste-te,
E o ombro deles rasgou-se.
Quando se apoiaram em ti, despedaçaste-te
E fizeste as suas pernas^&#42;1^ vacilarem.”

[NOTE]
====
. Lit.: “as suas ancas”.
====

[[v26-29-8]]

^<<v26-29-8,8>>^ “‘Portanto, assim diz o Soberano Senhor Jeová: “Trarei sobre ti uma espada, e eliminarei de ti tanto homens como animais.

[[v26-29-9]]

^<<v26-29-9,9>>^ A terra do Egito irá tornar-se um lugar desolado e devastado, e eles terão de saber que eu sou Jeová, pois tu disseste:^&#42;1^ ‘O rio Nilo é meu; fui eu que o fiz.’

[NOTE]
====
. Lit.: “ele disse”.
====

[[v26-29-10]]

^<<v26-29-10,10>>^ Portanto, estou contra ti e contra o teu Nilo, e farei com que a terra do Egito fique devastada e seca, um deserto desolado, desde Migdol até Siene, até à fronteira com a Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Nem homem nem animal passará por lá a pé, e não será habitada durante 40 anos.

[[v26-29-12]]

^<<v26-29-12,12>>^ Farei da terra do Egito a mais desolada das terras, e as suas cidades serão as mais desoladas das cidades durante 40 anos; e vou espalhar os egípcios pelas nações e dispersá-los pelas terras.”

[[v26-29-13]]

^<<v26-29-13,13>>^ “‘Pois assim diz o Soberano Senhor Jeová: “Depois de 40 anos, reunirei os egípcios dentre os povos pelos quais foram espalhados;

[[v26-29-14]]

^<<v26-29-14,14>>^ trarei de volta os cativos egípcios para a terra de Patros, a sua terra de origem, e ali se tornarão um reino insignificante.

[[v26-29-15]]

^<<v26-29-15,15>>^ O Egito irá tornar-se inferior aos outros reinos e nunca mais dominará as outras nações. Eu irei diminuí-los tanto que eles já não conseguirão conquistar outras nações.

[[v26-29-16]]

^<<v26-29-16,16>>^ O Egito nunca mais será um motivo de confiança para a casa de Israel; servirá apenas para a lembrar do seu erro por ter recorrido à ajuda deles. E terão de saber que eu sou o Soberano Senhor Jeová.”’”

[[v26-29-17]]

^<<v26-29-17,17>>^ No vigésimo sétimo ano, no primeiro mês, no primeiro dia do mês, recebi a seguinte palavra de Jeová:

[[v26-29-18]]

^<<v26-29-18,18>>^ “Filho do homem, Nabucodonosor,^&#42;1^ o rei de Babilónia, impôs ao seu exército uma dura campanha contra Tiro. Todas as cabeças ficaram calvas e todos os ombros foram esfolados. Todavia, ele e o seu exército não receberam nenhum salário pela campanha que ele realizou em Tiro.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v26-29-19]]

^<<v26-29-19,19>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Vou dar a terra do Egito a Nabucodonosor,^&#42;1^ rei de Babilónia, e ele levará a sua riqueza e tirará dela muito despojo e espólio; e isso servirá como salário para o seu exército.’

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v26-29-20]]

^<<v26-29-20,20>>^ “‘Vou dar-lhe a terra do Egito como pagamento pela sua campanha contra ela,^&#42;1^ visto que trabalharam para mim’, diz o Soberano Senhor Jeová.

[NOTE]
====
. Isto é, contra Tiro.
====

[[v26-29-21]]

^<<v26-29-21,21>>^ “Nesse dia, farei surgir um poderoso para a^&#42;1^ casa de Israel, e vou dar-te uma oportunidade para falares no meio deles; e eles terão de saber que eu sou Jeová.”

[NOTE]
====
. Ou: “darei força à”. Lit.: “farei brotar um chifre para a”.
====

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]