include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-37-1]]

^<<v26-37-1,1>>^ A mão de Jeová estava sobre mim, e, através do seu espírito, Jeová levantou-me e pôs-me no meio de um vale^&#42;1^ que estava cheio de ossos.

[NOTE]
====
. Lit.: “uma planície de vale”.
====

[[v26-37-2]]

^<<v26-37-2,2>>^ Ele fez-me andar à volta deles, e notei que havia uma enorme quantidade de ossos no vale, e que eles estavam muito secos.

[[v26-37-3]]

^<<v26-37-3,3>>^ Ele perguntou-me: “Filho do homem, será que estes ossos podem voltar a viver?” Eu respondi: “Soberano Senhor Jeová, tu é que sabes.”

[[v26-37-4]]

^<<v26-37-4,4>>^ Então, ele disse-me: “Profetiza a respeito destes ossos. Diz-lhes: ‘Ossos secos, ouçam a palavra de Jeová:

[[v26-37-5]]

^<<v26-37-5,5>>^ “‘Assim diz o Soberano Senhor Jeová a estes ossos: “Farei entrar fôlego em vocês, e voltarão a viver.

[[v26-37-6]]

^<<v26-37-6,6>>^ Vou pôr-vos tendões e carne, revestir-vos de pele e porei fôlego em vocês, e voltarão a viver; e terão de saber que eu sou Jeová.”’”

[[v26-37-7]]

^<<v26-37-7,7>>^ Então, profetizei conforme me tinha sido ordenado. Assim que profetizei, começou um barulho, um ruído de estalos, e os ossos começaram a juntar-se uns aos outros, osso com osso.

[[v26-37-8]]

^<<v26-37-8,8>>^ De seguida, vi tendões e carne aparecerem sobre eles, e eles foram revestidos de pele. Contudo, ainda não havia fôlego neles.

[[v26-37-9]]

^<<v26-37-9,9>>^ Depois, ele disse-me: “Profetiza ao vento. Profetiza, filho do homem, e diz ao vento: ‘Assim diz o Soberano Senhor Jeová: “Ó vento,^&#42;1^ vem dos quatro ventos e sopra sobre estes que foram mortos, para que voltem a viver.”’”

[NOTE]
====
. Ou: “fôlego; espírito”.
====

[[v26-37-10]]

^<<v26-37-10,10>>^ Portanto, profetizei assim como ele me ordenou, e entrou fôlego^&#42;1^ neles, e eles começaram a viver e puseram-se de pé, formando um exército extremamente grande.

[NOTE]
====
. Ou: “espírito”.
====

[[v26-37-11]]

^<<v26-37-11,11>>^ Em seguida, ele disse-me: “Filho do homem, estes ossos são toda a casa de Israel. Eles estão a dizer: ‘Os nossos ossos estão secos e a nossa esperança acabou. Fomos completamente eliminados.’

[[v26-37-12]]

^<<v26-37-12,12>>^ Portanto, profetiza-lhes o seguinte: ‘Assim diz o Soberano Senhor Jeová: “Vou abrir as vossas sepulturas e vou levantar-vos das vossas sepulturas, ó meu povo, e vou levar-vos à terra de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ E terão de saber que eu sou Jeová, quando eu abrir as vossas sepulturas e vos levantar das vossas sepulturas, ó meu povo.”’

[[v26-37-14]]

^<<v26-37-14,14>>^ ‘Porei em vocês o meu espírito, e voltarão a viver, e eu vou estabelecer-vos na vossa terra; e terão de saber que fui eu, Jeová, que falei e fiz isso’, diz Jeová.”

[[v26-37-15]]

^<<v26-37-15,15>>^ Recebi novamente a palavra de Jeová:

[[v26-37-16]]

^<<v26-37-16,16>>^ “Filho do homem, pega num bastão e escreve nele: ‘Para Judá e para os do povo de Israel que estão com ele.’^&#42;1^ Depois, pega noutro bastão e escreve nele: ‘Para José — bastão de Efraim — e para todos os da casa de Israel que estão com ele.’^&#42;2^

[NOTE]
====
. Ou: “que são seus companheiros”.
. Ou: “que são seus companheiros”.
====

[[v26-37-17]]

^<<v26-37-17,17>>^ A seguir, junta os dois bastões para que se tornem um só na tua mão.

[[v26-37-18]]

^<<v26-37-18,18>>^ Quando o teu povo te perguntar:^&#42;1^ ‘Não nos contarás o que significam estas coisas?’,

[NOTE]
====
. Lit.: “os filhos do teu povo te disserem”.
====

[[v26-37-19]]

^<<v26-37-19,19>>^ responde-lhes: ‘Assim diz o Soberano Senhor Jeová: “Vou pegar no bastão de José — que está na mão de Efraim — e nas tribos de Israel que estão com ele, e vou juntá-los ao bastão de Judá. E farei deles um só bastão; vão tornar-se um só na minha mão.”’

[[v26-37-20]]

^<<v26-37-20,20>>^ Os bastões em que escreverás deverão estar na tua mão para que eles os vejam.

[[v26-37-21]]

^<<v26-37-21,21>>^ “Então, diz-lhes: ‘Assim diz o Soberano Senhor Jeová: “Vou tirar os israelitas dentre as nações para as quais foram, vou reuni-los de todas as direções e trazê-los à sua terra.

[[v26-37-22]]

^<<v26-37-22,22>>^ Farei deles uma só nação naquela terra, sobre os montes de Israel, e um só rei irá governá-los a todos. Nunca mais serão duas nações, nem ficarão divididos em dois reinos.

[[v26-37-23]]

^<<v26-37-23,23>>^ Nunca mais se contaminarão com os seus ídolos repugnantes,^&#42;1^ nem com as suas práticas detestáveis, nem com nenhuma das suas transgressões. Eu vou livrá-los de toda a infidelidade com que pecaram e vou purificá-los. Eles serão o meu povo, e eu mesmo serei o seu Deus.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-37-24]]

^<<v26-37-24,24>>^ “‘“O meu servo David será o seu rei, e todos eles terão um só pastor. Eles andarão nas minhas decisões judiciais e obedecerão cuidadosamente aos meus decretos.

[[v26-37-25]]

^<<v26-37-25,25>>^ Morarão na terra que dei ao meu servo Jacó, a terra onde os vossos antepassados moraram. Morarão lá para sempre, eles, os seus filhos e os filhos dos seus filhos; e David, meu servo, será o seu maioral^&#42;1^ para sempre.

[NOTE]
====
. Ou: “príncipe”.
====

[[v26-37-26]]

^<<v26-37-26,26>>^ “‘“E farei com eles um pacto de paz; será um pacto eterno com eles. Vou estabelecê-los e fazê-los numerosos, e porei o meu santuário entre eles para sempre.

[[v26-37-27]]

^<<v26-37-27,27>>^ A minha tenda^&#42;1^ estará com^&#42;2^ eles, e eu serei o seu Deus, e eles serão o meu povo.

[NOTE]
====
. Ou: “morada, casa”.
. Ou: “sobre”.
====

[[v26-37-28]]

^<<v26-37-28,28>>^ E as nações terão de saber que eu, Jeová, santifico Israel, quando o meu santuário estiver no meio deles para sempre.”’”

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]