include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-35-1]]

^<<v26-35-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-35-2]]

^<<v26-35-2,2>>^ “Filho do homem, vira-te na direção da região montanhosa de Seir e profetiza contra ela.

[[v26-35-3]]

^<<v26-35-3,3>>^ Diz-lhe: ‘Assim diz o Soberano Senhor Jeová: “Eu estou contra ti, região montanhosa de Seir; estenderei a mão contra ti e farei de ti um deserto desolado.

[[v26-35-4]]

^<<v26-35-4,4>>^ Reduzirei as tuas cidades a ruínas, e vais tornar-te um deserto desolado; e terás de saber que eu sou Jeová.

[[v26-35-5]]

^<<v26-35-5,5>>^ Pois demonstraste ferrenha hostilidade contra os israelitas e entregaste-os à espada no tempo do seu desastre, no tempo da sua punição final.”’

[[v26-35-6]]

^<<v26-35-6,6>>^ “‘Portanto, tão certo como eu vivo’, diz o Soberano Senhor Jeová, ‘vou entregar-te ao derramamento de sangue, e o derramamento de sangue vai perseguir-te. Visto que foi o sangue que odiaste, o derramamento de sangue vai perseguir-te.

[[v26-35-7]]

^<<v26-35-7,7>>^ Farei da região montanhosa de Seir um deserto desolado, e eliminarei dela todos os que passam por lá, na ida ou na volta.

[[v26-35-8]]

^<<v26-35-8,8>>^ Cobrirei de mortos os seus montes; os mortos com a espada cairão nas tuas colinas, nos teus vales e em todas as tuas correntes de água.

[[v26-35-9]]

^<<v26-35-9,9>>^ Farei de ti uma desolação permanente, e as tuas cidades nunca mais serão habitadas. E vocês terão de saber que eu sou Jeová’.

[[v26-35-10]]

^<<v26-35-10,10>>^ “Tu disseste: ‘Estas duas nações e estas duas terras vão tornar-se minhas; tomaremos posse delas’, embora o próprio Jeová estivesse ali.

[[v26-35-11]]

^<<v26-35-11,11>>^ ‘Portanto, tão certo como eu vivo’, diz o Soberano Senhor Jeová, ‘agirei com a mesma ira e ciúme que demonstraste no teu ódio contra elas, e vou dar-me a conhecer entre elas quando te julgar.

[[v26-35-12]]

^<<v26-35-12,12>>^ Então, terás de saber que eu mesmo, Jeová, ouvi todas as ofensas que dirigiste contra os montes de Israel, quando disseste: “Foram desolados e foram-nos entregues para que os devoremos.”^&#42;1^

[NOTE]
====
. Lit.: “como alimento”.
====

[[v26-35-13]]

^<<v26-35-13,13>>^ Falaram arrogantemente contra mim e multiplicaram contra mim as vossas palavras. Eu ouvi tudo’.

[[v26-35-14]]

^<<v26-35-14,14>>^ “Assim diz o Soberano Senhor Jeová: ‘Toda a terra se alegrará quando eu fizer de ti um deserto desolado.

[[v26-35-15]]

^<<v26-35-15,15>>^ Assim como te alegraste quando a herança da casa de Israel foi desolada, assim te farei. Serás reduzida a ruínas desoladas, ó região montanhosa de Seir, sim, todo o Edom; e terão de saber que eu sou Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]