include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-18-1]]

^<<v26-18-1,1>>^ Então, recebi novamente a palavra de Jeová:

[[v26-18-2]]

^<<v26-18-2,2>>^ “O que querem dizer com este provérbio que citam na terra de Israel: ‘Os pais comeram uvas azedas, mas foram os filhos que ficaram com o gosto azedo na boca’?^&#42;1^

[NOTE]
====
. Lit.: “mas os dentes dos filhos ficaram embotados”.
====

[[v26-18-3]]

^<<v26-18-3,3>>^ “‘Tão certo como eu vivo’, diz o Soberano Senhor Jeová, ‘vocês nunca mais citarão este provérbio em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Pois todas as almas^&#42;1^ me pertencem. Tanto a alma do pai como a alma do filho me pertencem. A alma^&#42;2^ que pecar é a que morrerá.

[NOTE]
====
. Ou: “vidas”. Veja o Glossário, “Alma”.
. Ou: “pessoa”. Veja o Glossário, “Alma”.
====

[[v26-18-5]]

^<<v26-18-5,5>>^ “‘Suponhamos que um homem seja justo e faça o que é justo e certo.

[[v26-18-6]]

^<<v26-18-6,6>>^ Ele não come sacrifícios idólatras nos montes; não ergue os olhos para os ídolos repugnantes^&#42;1^ da casa de Israel; não comete adultério com^&#42;2^ a esposa do próximo nem tem relações com uma mulher menstruada;

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
. Lit.: “não avilta”.
====

[[v26-18-7]]

^<<v26-18-7,7>>^ não maltrata ninguém; em vez disso, devolve o que toma dos seus devedores como garantia; não rouba ninguém; em vez disso, dá a sua própria comida aos famintos e veste os que não têm roupa;

[[v26-18-8]]

^<<v26-18-8,8>>^ não cobra juros nem visa o lucro quando empresta; em vez disso, recusa-se a agir com injustiça; julga com justiça as questões entre dois indivíduos;

[[v26-18-9]]

^<<v26-18-9,9>>^ anda sempre nos meus decretos e obedece às minhas decisões judiciais, para agir com fidelidade. Tal homem é justo e de certeza que continuará vivo’, diz o Soberano Senhor Jeová.

[[v26-18-10]]

^<<v26-18-10,10>>^ “‘Mas suponhamos que ele tenha um filho que é ladrão, assassino,^&#42;1^ ou faz alguma destas outras coisas

[NOTE]
====
. Lit.: “derramador de sangue”.
====

[[v26-18-11]]

^<<v26-18-11,11>>^ (apesar de o pai nunca ter feito nada disso). Ele come sacrifícios idólatras nos montes, comete adultério com^&#42;1^ a esposa do próximo,

[NOTE]
====
. Lit.: “avilta”.
====

[[v26-18-12]]

^<<v26-18-12,12>>^ maltrata o necessitado e o pobre, rouba, não devolve o que toma dos seus devedores como garantia, ergue os olhos para os ídolos repugnantes, pratica coisas detestáveis

[[v26-18-13]]

^<<v26-18-13,13>>^ e cobra juros e visa o lucro quando empresta. Esse filho não continuará vivo. Por causa de todas estas coisas detestáveis que ele fez, de certeza que será morto. O seu sangue recairá sobre si próprio.

[[v26-18-14]]

^<<v26-18-14,14>>^ “‘Por outro lado, suponhamos que um pai tenha um filho que vê todos os pecados que o seu pai comete e, apesar de os ver, não faz tais coisas.

[[v26-18-15]]

^<<v26-18-15,15>>^ Ele não come sacrifícios idólatras nos montes, não ergue os olhos para os ídolos repugnantes da casa de Israel, não comete adultério com^&#42;1^ a esposa do próximo,

[NOTE]
====
. Lit.: “não avilta”.
====

[[v26-18-16]]

^<<v26-18-16,16>>^ não maltrata ninguém, não se apodera do que toma dos seus devedores como garantia, não rouba, dá a sua própria comida aos famintos e veste os que não têm roupa,

[[v26-18-17]]

^<<v26-18-17,17>>^ não oprime os pobres e não cobra juros nem visa o lucro quando empresta, cumpre as minhas decisões judiciais e anda nos meus decretos. Tal homem não morrerá por causa do erro do seu pai. Com certeza, ele continuará vivo.

[[v26-18-18]]

^<<v26-18-18,18>>^ Porém, visto que o seu pai cometeu fraudes, roubou o seu irmão e fez o que é errado no meio do seu povo, morrerá por causa do seu erro.

[[v26-18-19]]

^<<v26-18-19,19>>^ “‘Mas vocês perguntarão: “Porque é que o filho não leva a culpa pelo erro do pai?” Visto que o filho fez o que é justo e certo, guardou todos os meus decretos e os cumpriu, com certeza, ele continuará vivo.

[[v26-18-20]]

^<<v26-18-20,20>>^ A alma^&#42;1^ que pecar é a que morrerá. O filho não levará a culpa pelo erro do pai, e o pai não levará a culpa pelo erro do filho. A justiça daquele que é justo será contada apenas a favor dele mesmo, e a maldade daquele que é mau será contada apenas contra ele mesmo.

[NOTE]
====
. Ou: “pessoa”.
====

[[v26-18-21]]

^<<v26-18-21,21>>^ “‘Agora, se aquele que é mau abandonar todos os pecados que cometeu, guardar todos os meus decretos e fizer o que é justo e certo, com certeza, ele continuará vivo. Não morrerá.

[[v26-18-22]]

^<<v26-18-22,22>>^ Ele não terá de responder por nenhuma das transgressões que cometeu.^&#42;1^ Ele continuará vivo por fazer o que é justo.’

[NOTE]
====
. Ou: “Nenhuma das transgressões que cometeu será lembrada contra ele.”
====

[[v26-18-23]]

^<<v26-18-23,23>>^ “‘Por acaso, tenho algum prazer na morte de uma pessoa má?’, diz o Soberano Senhor Jeová. ‘Não prefiro que ele abandone os seus caminhos e continue vivo?’

[[v26-18-24]]

^<<v26-18-24,24>>^ “‘Por outro lado, se um justo abandonar a sua justiça e fizer o que é errado,^&#42;1^ fazendo todas as coisas detestáveis que os maus fazem, será que vai continuar vivo? Nenhum dos seus atos justos será lembrado. Por causa da sua infidelidade e do seu pecado, ele morrerá.

[NOTE]
====
. Ou: “fizer injustiça”.
====

[[v26-18-25]]

^<<v26-18-25,25>>^ “‘Mas vocês dirão: “O caminho de Jeová é injusto.” Escutem, por favor, ó casa de Israel! Será que é o meu caminho que é injusto? Não são os vossos caminhos que são injustos?

[[v26-18-26]]

^<<v26-18-26,26>>^ “‘Se um justo abandonar a sua justiça, fizer o que é errado e morrer, será por causa do seu próprio erro que ele morrerá.

[[v26-18-27]]

^<<v26-18-27,27>>^ “‘E, se aquele que é mau abandonar a maldade que praticou e passar a fazer o que é justo e certo, ele preservará a sua própria vida.^&#42;1^

[NOTE]
====
. Ou: “alma”. Veja o Glossário, “Alma”.
====

[[v26-18-28]]

^<<v26-18-28,28>>^ Se ele se aperceber de todas as transgressões que cometeu e as abandonar, com certeza, ele continuará vivo. Não morrerá.

[[v26-18-29]]

^<<v26-18-29,29>>^ “‘No entanto, a casa de Israel dirá: “O caminho de Jeová é injusto.” São realmente os meus caminhos que são injustos, ó casa de Israel? Não são os vossos caminhos que são injustos?’

[[v26-18-30]]

^<<v26-18-30,30>>^ “‘Portanto, julgarei cada um conforme os seus caminhos, ó casa de Israel’, diz o Soberano Senhor Jeová. ‘Abandonem, sim, abandonem completamente todas as vossas transgressões, para que elas não sejam uma pedra de tropeço, trazendo culpa sobre vocês.

[[v26-18-31]]

^<<v26-18-31,31>>^ Livrem-se de todas as transgressões que cometeram, e desenvolvam^&#42;1^ um coração novo e um espírito novo. Afinal, porque é que deveriam morrer, ó casa de Israel?’

[NOTE]
====
. Lit.: “façam para vocês”.
====

[[v26-18-32]]

^<<v26-18-32,32>>^ “‘Não tenho prazer na morte de ninguém’, diz o Soberano Senhor Jeová. ‘Portanto, deem meia-volta e vivam.’”

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]