include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-11-1]]

^<<v26-11-1,1>>^ E um espírito levantou-me e levou-me até ao portão leste da casa de Jeová, o portão que dá para o leste. Ali, à entrada do portão, vi 25 homens, e no meio deles estavam Jaazanias, filho de Azur, e Pelatias, filho de Benaia, príncipes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ Então, Ele disse-me: “Filho do homem, estes são os homens que tramam o mal e dão conselhos perversos nesta^&#42;1^ cidade.

[NOTE]
====
. Ou: “contra esta”.
====

[[v26-11-3]]

^<<v26-11-3,3>>^ Eles dizem: ‘Não é este o tempo de construir casas? A cidade^&#42;1^ é uma panela,^&#42;2^ e nós somos a carne.’

[NOTE]
====
. Lit.: “Ela”, isto é, a cidade de Jerusalém, onde os judeus pensavam que estariam protegidos.
. Ou: “um caldeirão”.
====

[[v26-11-4]]

^<<v26-11-4,4>>^ “Portanto, profetiza contra eles. Profetiza, filho do homem.”

[[v26-11-5]]

^<<v26-11-5,5>>^ Em seguida, o espírito de Jeová veio sobre mim, e ele disse-me: “Diz: ‘Assim diz Jeová: “O que vocês dizem está certo, ó casa de Israel, e eu sei o que estão a pensar.^&#42;1^

[NOTE]
====
. Ou: “as coisas que surgem no vosso espírito”.
====

[[v26-11-6]]

^<<v26-11-6,6>>^ Vocês causaram a morte de muitas pessoas nesta cidade e encheram as suas ruas de mortos.”’”

[[v26-11-7]]

^<<v26-11-7,7>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Os cadáveres que espalharam pela cidade são a carne, e a cidade é a panela. Mas vocês serão tirados dela.’”

[[v26-11-8]]

^<<v26-11-8,8>>^ “‘Vocês temem a espada, e é a espada que trarei contra vocês’, diz o Soberano Senhor Jeová.

[[v26-11-9]]

^<<v26-11-9,9>>^ ‘Eu hei de tirar-vos da cidade e entregar-vos nas mãos de estrangeiros, e executarei em vocês o julgamento.

[[v26-11-10]]

^<<v26-11-10,10>>^ Vocês cairão pela espada. Na fronteira de Israel, irei julgar-vos, e terão de saber que eu sou Jeová.

[[v26-11-11]]

^<<v26-11-11,11>>^ A cidade não vos servirá de panela, e vocês não serão a carne dentro dela. Na fronteira de Israel, irei julgar-vos,

[[v26-11-12]]

^<<v26-11-12,12>>^ e terão de saber que eu sou Jeová. Pois não andaram nos meus decretos nem cumpriram as minhas decisões judiciais, mas agiram conforme as decisões judiciais das nações ao vosso redor.’”

[[v26-11-13]]

^<<v26-11-13,13>>^ Assim que acabei de profetizar, morreu Pelatias, filho de Benaia. Então, eu prostrei-me com o rosto por terra e clamei com voz alta: “Ai, Soberano Senhor Jeová! Vais exterminar os que restam de Israel?”

[[v26-11-14]]

^<<v26-11-14,14>>^ Recebi novamente a palavra de Jeová:

[[v26-11-15]]

^<<v26-11-15,15>>^ “Filho do homem, foi aos teus irmãos, os teus irmãos que têm o direito de resgate, e a toda a casa de Israel, que os habitantes de Jerusalém disseram: ‘Mantenham-se longe de Jeová. Esta terra é nossa; ela foi-nos dada como propriedade.’

[[v26-11-16]]

^<<v26-11-16,16>>^ Portanto, diz: ‘Assim diz o Soberano Senhor Jeová: “Embora eu os tenha removido para longe entre as nações e os tenha espalhado pelas terras, por um pouco de tempo serei para eles um santuário nas terras para onde foram.”’

[[v26-11-17]]

^<<v26-11-17,17>>^ “Portanto, diz: ‘Assim diz o Soberano Senhor Jeová: “Vou reunir-vos dentre os povos e ajuntar-vos dentre as terras pelas quais foram espalhados, e vou dar-vos a terra de Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ Eles voltarão para lá e removerão dela todas as coisas repugnantes e todas as práticas detestáveis.

[[v26-11-19]]

^<<v26-11-19,19>>^ Eu irei dar-lhes um coração unificado^&#42;1^ e pôr neles um espírito novo. Tirarei do seu corpo o coração de pedra e irei dar-lhes um coração de carne,^&#42;2^

[NOTE]
====
. Lit.: “um só coração”.
. Isto é, recetivo à orientação de Deus.
====

[[v26-11-20]]

^<<v26-11-20,20>>^ para que andem nos meus decretos, guardem as minhas decisões judiciais e lhes obedeçam. Assim, eles hão de tornar-se o meu povo, e eu hei de tornar-me o seu Deus.”’

[[v26-11-21]]

^<<v26-11-21,21>>^ “‘“Mas, quanto àqueles que estão com o coração determinado a continuar nas suas coisas repugnantes e nas suas práticas detestáveis, farei as consequências do seu proceder recaírem sobre a sua própria cabeça”, diz o Soberano Senhor Jeová.’”

[[v26-11-22]]

^<<v26-11-22,22>>^ Então, os querubins levantaram as asas, e as rodas estavam perto deles, e por cima deles estava a glória do Deus de Israel.

[[v26-11-23]]

^<<v26-11-23,23>>^ E a glória de Jeová subiu da cidade e parou sobre o monte que fica a leste da cidade.

[[v26-11-24]]

^<<v26-11-24,24>>^ E um espírito levantou-me — na visão que tive através do espírito de Deus — e trouxe-me até ao povo exilado na Caldeia. Em seguida, a visão que eu tivera retirou-se de mim.

[[v26-11-25]]

^<<v26-11-25,25>>^ E comecei a dizer ao povo exilado todas as coisas que Jeová me tinha mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]