include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-47-1]]

^<<v26-47-1,1>>^ Então, ele levou-me de volta à entrada do templo, e eu vi ali água que saía de debaixo do limiar do templo, que ia para leste, pois a frente do templo dava para leste. A água saía de debaixo do lado direito do templo e passava a sul do altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ A seguir, ele levou-me para fora pelo portão norte e fez-me dar a volta por fora até ao portão externo que dava para leste, e eu vi a água a escorrer desde o lado direito.

[[v26-47-3]]

^<<v26-47-3,3>>^ Quando o homem saiu para o leste com a corda de medir na mão, mediu 1000 côvados^&#42;1^ e fez-me atravessar a água; a água dava-me pelos tornozelos.

[NOTE]
====
. Isto é, côvados longos. Veja o Ap. B14.
====

[[v26-47-4]]

^<<v26-47-4,4>>^ Depois, mediu mais 1000 côvados e fez-me atravessar a água, e ela dava-me pelos joelhos.
Mediu outros 1000 côvados e fez-me atravessar, e a água dava-me pela cintura.

[[v26-47-5]]

^<<v26-47-5,5>>^ Quando mediu mais 1000 côvados, era uma torrente que eu não conseguia atravessar a pé, pois a água era tão funda que era necessário nadar; era uma torrente impossível de se atravessar a pé.

[[v26-47-6]]

^<<v26-47-6,6>>^ Ele perguntou-me: “Viste isto, filho do homem?”
Então, ele fez-me andar e regressar à margem da corrente de água.

[[v26-47-7]]

^<<v26-47-7,7>>^ Quando voltei, vi que nas duas margens da corrente de água havia muitíssimas árvores.

[[v26-47-8]]

^<<v26-47-8,8>>^ A seguir, ele disse-me: “Esta água corre em direção à região oriental, desce pelo Arabá^&#42;1^ e desemboca no mar. Quando entrar no mar, a sua água será curada.

[NOTE]
====
. Ou: “pela planície desértica”.
====

[[v26-47-9]]

^<<v26-47-9,9>>^ Multidões de criaturas vivas^&#42;1^ poderão viver por onde quer que as águas^&#42;2^ passem. Haverá uma grande quantidade de peixes, pois esta água correrá para lá. A água do mar será curada e tudo viverá por onde quer que a corrente de água passe.

[NOTE]
====
. Ou: “almas”.
. Lit.: “as duas correntes”.
====

[[v26-47-10]]

^<<v26-47-10,10>>^ “Os pescadores ficarão na sua margem desde En-Gedi até En-Eglaim, onde haverá um lugar para secar redes de arrasto. Haverá uma grande quantidade de peixes, de muitos tipos, como os peixes do Grande Mar.^&#42;1^

[NOTE]
====
. Isto é, o mar Mediterrâneo.
====

[[v26-47-11]]

^<<v26-47-11,11>>^ “Ali haverá charcos e pântanos, mas não serão curados. Serão abandonados ao sal.

[[v26-47-12]]

^<<v26-47-12,12>>^ “Todo o tipo de árvores para alimento crescerá nas duas margens da corrente de água. As suas folhas não murcharão, e as árvores não deixarão de dar frutos. Produzirão novos frutos todos os meses, porque são regadas pela água que sai do santuário. Os seus frutos servirão de alimento, e as suas folhas, de cura.”

[[v26-47-13]]

^<<v26-47-13,13>>^ Assim diz o Soberano Senhor Jeová: “Este é o território que repartirão como herança da terra das 12 tribos de Israel, e José terá duas partes.

[[v26-47-14]]

^<<v26-47-14,14>>^ Irão herdá-la e receberão partes iguais.^&#42;1^ Jurei dar esta terra aos vossos antepassados, e agora ela é repartida entre^&#42;2^ vocês como herança.

[NOTE]
====
. Lit.: “Irão herdá-la, cada um como o seu irmão”.
. Lit.: “cai para”.
====

[[v26-47-15]]

^<<v26-47-15,15>>^ “Este é o limite da terra do lado norte: começa no Grande Mar, passa pela estrada para Hetlom, em direção a Zedade,

[[v26-47-16]]

^<<v26-47-16,16>>^ Hamate, Berota e Sibraim, que fica entre os territórios de Damasco e de Hamate, e segue até Hazer-Haticom, que fica ao pé do limite de Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ Portanto, o limite vai do mar até Hazar-Enom, ao longo do limite de Damasco, a norte, e do limite de Hamate. Esta é a fronteira norte.

[[v26-47-18]]

^<<v26-47-18,18>>^ “O lado leste passa entre Haurã e Damasco, e segue ao longo do rio Jordão, entre Gileade e a terra de Israel. Devem medir a distância desde o limite^&#42;1^ até ao mar oriental.^&#42;2^ Esta é a fronteira leste.

[NOTE]
====
. Isto é, o limite norte.
. Isto é, o mar Morto.
====

[[v26-47-19]]

^<<v26-47-19,19>>^ “A fronteira sul^&#42;1^ irá estender-se desde Tamar até às águas de Meribate-Cades, dali até à Torrente^&#42;2^ e até ao Grande Mar. Esta é a fronteira sul.^&#42;3^

[NOTE]
====
. Lit.: “O lado sul em direção ao sul”.
. Isto é, a torrente do Egito.
. Lit.: “Este é o lado sul em direção ao sul.”
====

[[v26-47-20]]

^<<v26-47-20,20>>^ “Do lado oeste, fica o Grande Mar, desde o limite^&#42;1^ até um lugar em frente a Lebo-Hamate.^&#42;2^ Esta é a fronteira oeste.”

[NOTE]
====
. Isto é, o limite sul.
. Ou: “à entrada de Hamate”.
====

[[v26-47-21]]

^<<v26-47-21,21>>^ “Devem repartir esta terra entre vocês, entre as 12 tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ Devem distribuí-la como herança entre vocês e entre os estrangeiros que moram convosco, os que tiveram filhos no vosso meio; eles serão para vocês iguais aos israelitas de nascimento. Receberão uma herança convosco entre as tribos de Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ Devem dar ao residente estrangeiro uma herança no território da tribo em que ele tiver fixado residência”, diz o Soberano Senhor Jeová.

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]