include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-30-1]]

^<<v26-30-1,1>>^ Então, recebi novamente a palavra de Jeová:

[[v26-30-2]]

^<<v26-30-2,2>>^ “Filho do homem, profetiza o seguinte: ‘Assim diz o Soberano Senhor Jeová:
“Lamentem, dizendo: ‘Ai, o dia está a chegar!’

[[v26-30-3]]

^<<v26-30-3,3>>^ Pois o dia está próximo, sim, o dia de Jeová está próximo.
Será um dia de nuvens, um tempo determinado para as nações.

[[v26-30-4]]

^<<v26-30-4,4>>^ Uma espada virá contra o Egito e o pânico tomará conta da Etiópia quando os mortos caírem no Egito,
Quando a sua riqueza lhe for tirada e os seus alicerces forem destruídos.

[[v26-30-5]]

^<<v26-30-5,5>>^ Etiópia, Pute, Lude e todos os diferentes povos entre eles,^&#42;1^
Também Cube e os filhos da terra do pacto,^&#42;2^
Todos cairão pela espada.”’

[NOTE]
====
. Ou: “todos os de outras nações”.
. Talvez se refira a israelitas que se aliaram ao Egito.
====

[[v26-30-6]]

^<<v26-30-6,6>>^ Assim diz Jeová:
‘Os apoiantes do Egito também cairão,
E o seu poder arrogante será rebaixado.’
“‘Desde Migdol até Siene, cairão pela espada naquela terra’, diz o Soberano Senhor Jeová.

[[v26-30-7]]

^<<v26-30-7,7>>^ ‘Eles serão a mais desolada das terras, e as suas cidades serão as mais devastadas das cidades.

[[v26-30-8]]

^<<v26-30-8,8>>^ Eles terão de saber que eu sou Jeová quando eu deitar fogo ao Egito e todos os que o apoiam forem esmagados.

[[v26-30-9]]

^<<v26-30-9,9>>^ Nesse dia, enviarei mensageiros em navios para fazer tremer a autoconfiante Etiópia; o pânico tomará conta deles no dia que está a chegar sobre o Egito, pois o dia certamente vai chegar.’

[[v26-30-10]]

^<<v26-30-10,10>>^ “Assim diz o Soberano Senhor Jeová: ‘Porei fim às multidões do Egito pelas mãos de Nabucodonosor,^&#42;1^ rei de Babilónia.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e as suas tropas, a mais cruel das nações, serão trazidos para destruir o país. Eles puxarão das suas espadas contra o Egito e encherão o país de mortos.

[[v26-30-12]]

^<<v26-30-12,12>>^ Vou transformar os canais do Nilo em terra seca e vou entregar^&#42;1^ o país nas mãos de homens perversos. Vou fazer com que o país e tudo que há nele sejam desolados pelas mãos de estrangeiros. Fui eu, Jeová, que falei.’

[NOTE]
====
. Lit.: “vender”.
====

[[v26-30-13]]

^<<v26-30-13,13>>^ “Assim diz o Soberano Senhor Jeová: ‘Também destruirei os ídolos repugnantes^&#42;1^ e porei fim aos deuses de Nofe,^&#42;2^ que não valem nada. Já não haverá mais nenhum príncipe^&#42;3^ procedente da terra do Egito, e porei medo na terra do Egito.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
. Ou: “Mênfis”.
. Ou: “maioral”.
====

[[v26-30-14]]

^<<v26-30-14,14>>^ Desolarei Patros, porei fogo a Zoã e executarei o julgamento em Nô.^&#42;1^

[NOTE]
====
. Isto é, Tebes.
====

[[v26-30-15]]

^<<v26-30-15,15>>^ Derramarei o meu furor sobre Sim, a fortaleza do Egito, e destruirei a população de Nô.

[[v26-30-16]]

^<<v26-30-16,16>>^ Deitarei fogo ao Egito; o terror tomará conta de Sim, abrirão brechas em Nô, e Nofe^&#42;1^ será atacada em pleno dia!

[NOTE]
====
. Ou: “Mênfis”.
====

[[v26-30-17]]

^<<v26-30-17,17>>^ Os jovens de Om^&#42;1^ e de Pi-Besete cairão pela espada, e os habitantes das cidades irão para o cativeiro.

[NOTE]
====
. Isto é, Heliópolis.
====

[[v26-30-18]]

^<<v26-30-18,18>>^ O dia ficará escuro em Tafnes, quando eu quebrar ali o jugo do Egito. O seu poder arrogante chegará ao fim, ela ficará coberta de nuvens, e os habitantes das suas cidades irão para o cativeiro.

[[v26-30-19]]

^<<v26-30-19,19>>^ Executarei o julgamento contra o Egito, e eles terão de saber que eu sou Jeová.’”

[[v26-30-20]]

^<<v26-30-20,20>>^ E no décimo primeiro ano, no primeiro mês, no dia sete do mês, recebi a seguinte palavra de Jeová:

[[v26-30-21]]

^<<v26-30-21,21>>^ “Filho do homem, parti o braço do Faraó, rei do Egito; ele não será tratado para que sare, nem será enfaixado com ligaduras para ficar suficientemente forte para usar a espada.”

[[v26-30-22]]

^<<v26-30-22,22>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Estou contra o Faraó, rei do Egito; vou partir-lhe os braços, tanto o bom como o que já está partido, e vou fazer com que a espada lhe caia da mão.

[[v26-30-23]]

^<<v26-30-23,23>>^ Então, vou espalhar os egípcios pelas nações e dispersá-los pelas terras.

[[v26-30-24]]

^<<v26-30-24,24>>^ Fortalecerei os braços^&#42;1^ do rei de Babilónia e porei a minha espada na sua mão. Vou partir os braços do Faraó, e ele gemerá em voz alta diante dele,^&#42;2^ como um homem que está a morrer.

[NOTE]
====
. Ou: “Aumentarei o poder”.
. Isto é, diante do rei de Babilónia.
====

[[v26-30-25]]

^<<v26-30-25,25>>^ Fortalecerei os braços do rei de Babilónia, mas os braços do Faraó ficarão caídos; e eles terão de saber que eu sou Jeová, quando eu puser a minha espada na mão do rei de Babilónia, e ele a usar contra a terra do Egito.

[[v26-30-26]]

^<<v26-30-26,26>>^ Vou espalhar os egípcios pelas nações e dispersá-los pelas terras, e eles terão de saber que eu sou Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]