include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-22-1]]

^<<v26-22-1,1>>^ E recebi novamente a palavra de Jeová:

[[v26-22-2]]

^<<v26-22-2,2>>^ “Filho do homem, estás pronto para proferir a sentença da^&#42;1^ cidade culpada de sangue e expor-lhe todas as suas coisas detestáveis?

[NOTE]
====
. Lit.: “vais julgar, vais julgar a”.
====

[[v26-22-3]]

^<<v26-22-3,3>>^ Deves dizer: ‘Assim diz o Soberano Senhor Jeová: “Ó cidade que derrama sangue dentro de si mesma, cujo tempo está a chegar, que faz ídolos repugnantes^&#42;1^ para se contaminar;

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-22-4]]

^<<v26-22-4,4>>^ o sangue que derramaste tornou-te culpada, e os teus ídolos repugnantes tornaram-te impura. Apressaste o fim dos teus dias, e o fim dos teus anos chegou. É por isso que farei de ti alvo de insultos para as nações e motivo de gozo para todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ Tanto as terras próximas como as distantes gozarão contigo, que estás com o nome manchado e que estás cheia de confusão.

[[v26-22-6]]

^<<v26-22-6,6>>^ Vê! Todos os maiorais de Israel no teu meio usam a sua autoridade para derramar sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ No teu meio, pai e mãe são desprezados, o residente estrangeiro é defraudado, o órfão^&#42;1^ e a viúva são maltratados.”’”

[NOTE]
====
. Ou: “órfão de pai”.
====

[[v26-22-8]]

^<<v26-22-8,8>>^ “‘Desprezas os meus lugares santos e profanas os meus sábados.

[[v26-22-9]]

^<<v26-22-9,9>>^ No teu meio, há caluniadores decididos a derramar sangue. No teu meio, as pessoas comem sacrifícios sobre os montes e, no teu meio, agem de forma obscena.

[[v26-22-10]]

^<<v26-22-10,10>>^ No teu meio, as pessoas desonram a cama do pai^&#42;1^ e têm relações sexuais com mulheres durante a sua impureza menstrual.

[NOTE]
====
. Lit.: “expõem a nudez do seu pai”.
====

[[v26-22-11]]

^<<v26-22-11,11>>^ No teu meio, um homem age de maneira detestável com a esposa do próximo, outro desonra a própria nora, agindo de maneira obscena, e ainda outro viola a irmã, a filha do seu próprio pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ No teu meio, aceitam suborno para derramar sangue. Cobras juros e visas o lucro^&#42;1^ quando emprestas e extorques dinheiro do teu próximo. Sim, esqueceste-te totalmente de mim’, diz o Soberano Senhor Jeová.

[NOTE]
====
. Ou: “e tomas usura”.
====

[[v26-22-13]]

^<<v26-22-13,13>>^ “‘Pois bem, bato as mãos em sinal de repulsa pelo teu lucro desonesto e pelo derramamento de sangue no teu meio.

[[v26-22-14]]

^<<v26-22-14,14>>^ Será que ainda terás coragem^&#42;1^ e as tuas mãos continuarão fortes nos dias em que eu agir contra ti? Eu mesmo, Jeová, falei e vou agir.

[NOTE]
====
. Lit.: “coração”.
====

[[v26-22-15]]

^<<v26-22-15,15>>^ Vou espalhar-te pelas nações e dispersar-te pelas terras, e porei fim à tua impureza.

[[v26-22-16]]

^<<v26-22-16,16>>^ Serás desonrada diante das nações, e terás de saber que eu sou Jeová.’”

[[v26-22-17]]

^<<v26-22-17,17>>^ E recebi novamente a palavra de Jeová:

[[v26-22-18]]

^<<v26-22-18,18>>^ “Filho do homem, a casa de Israel tornou-se para mim inútil como a escória. Todos eles são cobre, estanho, ferro e chumbo dentro de um forno de fundição. Tornaram-se a escória da prata.

[[v26-22-19]]

^<<v26-22-19,19>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Visto que todos se tornaram inúteis como a escória, vou ajuntar-vos dentro de Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Assim como se ajunta prata, cobre, ferro, chumbo e estanho dentro do forno de fundição a fim de se soprar sobre eles o fogo para os derreter, assim irei ajuntar-vos com ira e furor, e soprarei sobre vocês para fazer com que se derretam.

[[v26-22-21]]

^<<v26-22-21,21>>^ Vou ajuntar-vos e soprar sobre vocês o fogo da minha fúria, e irão derreter-se dentro dela.

[[v26-22-22]]

^<<v26-22-22,22>>^ Assim como a prata se derrete dentro de um forno de fundição, assim vocês irão derreter-se dentro dela; e terão de saber que eu mesmo, Jeová, derramei sobre vocês o meu furor.’”

[[v26-22-23]]

^<<v26-22-23,23>>^ Então, recebi novamente a palavra de Jeová:

[[v26-22-24]]

^<<v26-22-24,24>>^ “Filho do homem, diz-lhe: ‘Tu és uma terra que não será purificada nem receberá chuva no dia da indignação.

[[v26-22-25]]

^<<v26-22-25,25>>^ Os seus profetas fazem uma conspiração dentro dela, como leões que rugem e dilaceram a presa. Eles devoram pessoas.^&#42;1^ Apoderam-se de tesouros e de coisas preciosas. Fazem muitas viúvas dentro dela.

[NOTE]
====
. Ou: “almas”.
====

[[v26-22-26]]

^<<v26-22-26,26>>^ Os seus sacerdotes violam a minha lei e profanam os meus lugares santos. Não fazem nenhuma distinção entre o que é santo e o que é comum, nem ensinam a diferença entre o que é impuro e o que é puro. Recusam-se a guardar os meus sábados, e eu sou profanado entre eles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Os seus príncipes no seu meio são como lobos que dilaceram a presa; eles derramam sangue e matam pessoas^&#42;1^ para obter lucro desonesto.

[NOTE]
====
. Ou: “almas”.
====

[[v26-22-28]]

^<<v26-22-28,28>>^ Contudo, os seus profetas cobrem tudo isso com cal. Eles têm visões falsas, fazem adivinhações mentirosas e dizem: “Assim diz o Soberano Senhor Jeová”, apesar de o próprio Jeová não ter dito nada.

[[v26-22-29]]

^<<v26-22-29,29>>^ O povo da terra defrauda e rouba, maltrata o necessitado e o pobre, defrauda o residente estrangeiro e nega-lhe a justiça.’

[[v26-22-30]]

^<<v26-22-30,30>>^ “‘Procurei entre eles um homem que pudesse consertar a muralha de pedras ou colocar-se diante de mim na brecha da muralha a favor desta terra, para que não fosse destruída, mas não encontrei nenhum.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso, derramarei sobre eles a minha indignação e irei exterminá-los com o fogo da minha fúria. Vou fazer as consequências do seu caminho recaírem sobre a sua própria cabeça’, diz o Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]