include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-23-1]]

^<<v26-23-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-23-2]]

^<<v26-23-2,2>>^ “Filho do homem, havia duas mulheres que eram filhas da mesma mãe.

[[v26-23-3]]

^<<v26-23-3,3>>^ Elas tornaram-se prostitutas no Egito; prostituíram-se desde a juventude. Lá, os seus peitos foram apertados, os seus seios virgens foram acariciados.

[[v26-23-4]]

^<<v26-23-4,4>>^ O nome da mais velha era Oolá^&#42;1^ e o da sua irmã, Oolibá.^&#42;2^ Elas tornaram-se minhas e deram à luz filhos e filhas. Quanto aos seus nomes, Oolá é Samaria e Oolibá é Jerusalém.

[NOTE]
====
. Que significa “a sua tenda”.
. Que significa “a minha tenda está nela”.
====

[[v26-23-5]]

^<<v26-23-5,5>>^ “Oolá prostituiu-se enquanto me pertencia. Ela desejava ardentemente os seus amantes, os assírios, os seus vizinhos.

[[v26-23-6]]

^<<v26-23-6,6>>^ Eles eram governadores vestidos de azul e subgovernadores, todos jovens atraentes, montados em cavalos.

[[v26-23-7]]

^<<v26-23-7,7>>^ Ela continuou a prostituir-se com toda a elite dos filhos da Assíria e contaminou-se com os ídolos repugnantes^&#42;1^ daqueles a quem desejava ardentemente.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-23-8]]

^<<v26-23-8,8>>^ Ela não abandonou a prostituição que praticava no Egito, pois tinham-se deitado com ela na sua juventude, tinham acariciado os seus seios virgens e derramado a sua paixão ardente^&#42;1^ sobre ela.

[NOTE]
====
. Ou: “as suas relações imorais”.
====

[[v26-23-9]]

^<<v26-23-9,9>>^ Por isso, entreguei-a nas mãos dos seus amantes, os filhos da Assíria, os quais ela desejava ardentemente.

[[v26-23-10]]

^<<v26-23-10,10>>^ Eles expuseram a nudez dela, capturaram os seus filhos e as suas filhas e mataram-na com a espada. Ela tornou-se mal-afamada entre as mulheres, e eles executaram o julgamento contra ela.

[[v26-23-11]]

^<<v26-23-11,11>>^ “Quando a sua irmã Oolibá viu isso, a sua paixão tornou-se ainda mais depravada e a sua prostituição tornou-se pior do que a da sua irmã.

[[v26-23-12]]

^<<v26-23-12,12>>^ Ela desejava ardentemente os seus vizinhos, os filhos da Assíria, governadores e subgovernadores, homens vestidos com esplendor, montados em cavalos, todos eles jovens atraentes.

[[v26-23-13]]

^<<v26-23-13,13>>^ Quando ela se tornou impura, vi que as duas tinham seguido o mesmo caminho.

[[v26-23-14]]

^<<v26-23-14,14>>^ Contudo, ela ainda foi mais longe na sua prostituição. Ela viu homens esculpidos na parede, imagens esculpidas de caldeus pintadas de vermelho,

[[v26-23-15]]

^<<v26-23-15,15>>^ com cintos na cintura e turbantes esvoaçantes na cabeça, com a aparência de guerreiros, todos eles representavam babilónios, nascidos na terra dos caldeus.

[[v26-23-16]]

^<<v26-23-16,16>>^ Quando ela os viu, começou a desejá-los ardentemente e enviou-lhes mensageiros à Caldeia.

[[v26-23-17]]

^<<v26-23-17,17>>^ Assim, os filhos de Babilónia vinham ter relações com ela na sua cama, e tornaram-na impura com a sua paixão ardente.^&#42;1^ Depois de ter ficado impura por causa deles, ela^&#42;2^ ficou com aversão a eles e afastou-se.

[NOTE]
====
. Ou: “as suas relações imorais”.
. Ou: “a sua alma”.
====

[[v26-23-18]]

^<<v26-23-18,18>>^ “Quando ela continuou a prostituir-se descaradamente e a expor a sua nudez, eu fiquei^&#42;1^ com aversão dela e afastei-me, assim como tinha ficado com aversão da sua irmã e me tinha afastado dela.

[NOTE]
====
. Ou: “a minha alma ficou”.
====

[[v26-23-19]]

^<<v26-23-19,19>>^ E ela passou a prostituir-se cada vez mais, fazendo lembrar os dias da sua juventude, quando se prostituía na terra do Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ Ela desejava ardentemente os seus amantes, como as concubinas de homens cujo membro viril é como o de um jumento, cujo órgão genital é como o de um cavalo.

[[v26-23-21]]

^<<v26-23-21,21>>^ Tiveste saudades da conduta obscena da tua juventude no Egito, quando te acariciavam os seios, os peitos da tua juventude.

[[v26-23-22]]

^<<v26-23-22,22>>^ “Portanto, Oolibá, assim diz o Soberano Senhor Jeová: ‘Vou atiçar os teus amantes, de quem tu^&#42;1^ sentiste aversão e te afastaste, e vou trazê-los contra ti de todas as direções,

[NOTE]
====
. Ou: “a tua alma”.
====

[[v26-23-23]]

^<<v26-23-23,23>>^ os filhos de Babilónia e todos os caldeus, os homens de Pecode, de Soa e de Coa, e todos os filhos da Assíria com eles. Todos eles são jovens atraentes, governadores e subgovernadores, guerreiros e homens escolhidos,^&#42;1^ todos montados em cavalos.

[NOTE]
====
. Lit.: “convocados”.
====

[[v26-23-24]]

^<<v26-23-24,24>>^ Eles irão atacar-te com estrondosos carros de guerra e as suas rodas, com muitas tropas, com escudos grandes e pequenos,^&#42;1^ e com capacetes. Irão cercar-te por todos os lados; eu vou encarregá-los do teu julgamento, e eles irão julgar-te conforme acharem melhor.

[NOTE]
====
. Ou: “broquéis”, pequenos escudos geralmente usados por arqueiros.
====

[[v26-23-25]]

^<<v26-23-25,25>>^ Vou expressar a minha indignação contra ti e eles irão tratar-te com furor. Deceparão o teu nariz e as tuas orelhas, e os que restarem de ti cairão pela espada. Eles levarão os teus filhos e as tuas filhas, e os que restarem de ti serão consumidos pelo fogo.

[[v26-23-26]]

^<<v26-23-26,26>>^ Irão arrancar-te as tuas roupas e tirar-te as tuas belas joias.^&#42;1^

[NOTE]
====
. Ou: “os teus belos ornamentos”.
====

[[v26-23-27]]

^<<v26-23-27,27>>^ Porei fim à tua conduta obscena e à tua prostituição, que começaram na terra do Egito. Vais parar de olhar para eles, e nunca mais te lembrarás do Egito.’

[[v26-23-28]]

^<<v26-23-28,28>>^ “Pois assim diz o Soberano Senhor Jeová: ‘Estou prestes a entregar-te nas mãos daqueles que odeias, aqueles de quem tu^&#42;1^ sentiste aversão e te afastaste.

[NOTE]
====
. Ou: “a tua alma”.
====

[[v26-23-29]]

^<<v26-23-29,29>>^ Eles irão tratar-te com ódio, levar todos os frutos do teu trabalho árduo, e deixar-te nua e exposta. Será exposta a nudez vergonhosa da tua imoralidade, a tua conduta obscena e a tua prostituição.

[[v26-23-30]]

^<<v26-23-30,30>>^ Sofrerás estas coisas por teres perseguido as nações como uma prostituta, por te teres contaminado com os seus ídolos repugnantes.

[[v26-23-31]]

^<<v26-23-31,31>>^ Seguiste o mesmo caminho que a tua irmã, e eu porei o seu cálice na tua mão.’

[[v26-23-32]]

^<<v26-23-32,32>>^ “Assim diz o Soberano Senhor Jeová:
‘Beberás o cálice grande e fundo da tua irmã,
E irás tornar-te motivo de riso e de gozo, dos quais o cálice está cheio.

[[v26-23-33]]

^<<v26-23-33,33>>^ Serás dominada pela^&#42;1^ embriaguez e pela tristeza
— Um cálice de pavor e de desolação,
O cálice de Samaria, tua irmã.

[NOTE]
====
. Lit.: “Ficarás cheia de”.
====

[[v26-23-34]]

^<<v26-23-34,34>>^ Terás de o beber até o esvaziares, roer os seus cacos
E depois arrancar os próprios seios.
“Pois eu mesmo falei”, diz o Soberano Senhor Jeová.’

[[v26-23-35]]

^<<v26-23-35,35>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Visto que te esqueceste de mim e me desconsideraste completamente,^&#42;1^ sofrerás as consequências da tua conduta obscena e da tua prostituição.’”

[NOTE]
====
. Lit.: “me lançaste para trás das tuas costas”.
====

[[v26-23-36]]

^<<v26-23-36,36>>^ Depois, Jeová disse-me: “Filho do homem, vais proferir a sentença de Oolá e de Oolibá e confrontá-las com as suas práticas repugnantes?

[[v26-23-37]]

^<<v26-23-37,37>>^ Elas cometeram adultério,^&#42;1^ e há sangue nas suas mãos. Não só cometeram adultério com os seus ídolos repugnantes, mas também queimaram no fogo^&#42;2^ os filhos que me tinham gerado, oferecendo-os como alimento aos seus ídolos.

[NOTE]
====
. Isto é, adultério espiritual.
. Ou: “fizeram passar pelo fogo”.
====

[[v26-23-38]]

^<<v26-23-38,38>>^ E ainda me fizeram o seguinte: profanaram o meu santuário naquele dia e profanaram os meus sábados.

[[v26-23-39]]

^<<v26-23-39,39>>^ Naquele mesmo dia, depois de terem matado os seus filhos como sacrifício aos seus ídolos repugnantes, elas entraram no meu santuário para o profanar. Foi isso o que elas fizeram dentro da minha própria casa.

[[v26-23-40]]

^<<v26-23-40,40>>^ Elas até enviaram um mensageiro para chamar homens de longe. Quando eles estavam a chegar, tu^&#42;1^ lavaste-te, pintaste os olhos e enfeitaste-te com adornos.

[NOTE]
====
. Pelos vistos, refere-se a Oolibá.
====

[[v26-23-41]]

^<<v26-23-41,41>>^ E sentaste-te num divã luxuoso, diante do qual havia uma mesa posta, e puseste sobre ela o meu incenso e o meu óleo.

[[v26-23-42]]

^<<v26-23-42,42>>^ Ali se ouvia o som de uma multidão de homens despreocupados, entre os quais estavam beberrões trazidos do deserto. Eles puseram pulseiras nos braços das mulheres e belas coroas na cabeça delas.

[[v26-23-43]]

^<<v26-23-43,43>>^ “Então, eu disse a respeito daquela que já estava esgotada de tanto cometer adultério: ‘Agora, ela vai continuar a prostituir-se.’

[[v26-23-44]]

^<<v26-23-44,44>>^ Assim, eles continuaram a ir ter com ela, como se vai ter com uma prostituta. Desse modo, foram ao encontro de Oolá e de Oolibá, as mulheres de conduta obscena.

[[v26-23-45]]

^<<v26-23-45,45>>^ Mas homens justos irão aplicar-lhe a punição prescrita para o adultério e o derramamento de sangue, pois adúlteras é o que elas são, e há sangue nas suas mãos.

[[v26-23-46]]

^<<v26-23-46,46>>^ “Pois assim diz o Soberano Senhor Jeová: ‘Um exército será trazido contra elas, para fazer delas um motivo de terror e vítimas de saque.

[[v26-23-47]]

^<<v26-23-47,47>>^ O exército vai atirar-lhes pedras e vai executá-las com espadas. Matarão os seus filhos e as suas filhas, e queimarão as suas casas com fogo.

[[v26-23-48]]

^<<v26-23-48,48>>^ Porei fim à conduta obscena no país, e todas as mulheres aprenderão uma lição e não imitarão a vossa conduta obscena.

[[v26-23-49]]

^<<v26-23-49,49>>^ Farão recair sobre vocês as consequências da vossa conduta obscena e dos pecados que cometeram com os vossos ídolos repugnantes; e vocês terão de saber que eu sou o Soberano Senhor Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]