include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-4-1]]

^<<v26-4-1,1>>^ “Filho do homem, pega num tijolo, põe-no à tua frente e grava nele uma cidade — Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ Cerca a cidade, constrói à sua volta um muro de cerco, levanta contra ela uma rampa de ataque, monta acampamentos contra ela e coloca aríetes à sua volta.

[[v26-4-3]]

^<<v26-4-3,3>>^ Pega numa assadeira de ferro e coloca-a como se fosse um muro de ferro entre ti e a cidade. Então, vira o teu rosto contra ela, e ela estará cercada; sim, cerca-a. Isto será um sinal para a casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ “Depois, deita-te sobre o teu lado esquerdo e põe a culpa da casa de Israel sobre ti mesmo.^&#42;1^ Carregarás a culpa deles durante todos os dias em que ficares deitado sobre o teu lado.

[NOTE]
====
. Lit.: “ele”, isto é, o lado esquerdo de Ezequiel.
====

[[v26-4-5]]

^<<v26-4-5,5>>^ E irei impor-te 390 dias, o equivalente aos anos da culpa deles, e carregarás a culpa da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ E terás de cumprir esse período.
“A seguir, irás deitar-te novamente, desta vez sobre o teu lado direito, e carregarás a culpa da casa de Judá durante 40 dias. Para cada dia um ano, para cada dia um ano, é o que te impus.

[[v26-4-7]]

^<<v26-4-7,7>>^ E virarás o teu rosto para o cerco de Jerusalém, com o teu braço descoberto, e terás de profetizar contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ “Escuta: vou amarrar-te com cordas para que não te possas virar de um lado para o outro até cumprires os dias do teu cerco.

[[v26-4-9]]

^<<v26-4-9,9>>^ “E deves pegar em trigo, cevada, favas, lentilhas, painço e espelta, colocá-los numa vasilha e fazer o teu pão. Vais comê-lo durante todos os dias em que estiveres deitado sobre o teu lado, durante 390 dias.

[[v26-4-10]]

^<<v26-4-10,10>>^ Pesarás e comerás 20 siclos^&#42;1^ de comida por dia. Vais comê-la em horários determinados.

[NOTE]
====
. Cerca de 230 g. Veja o Ap. B14.
====

[[v26-4-11]]

^<<v26-4-11,11>>^ “E beberás água por medida, um sexto de um him.^&#42;1^ Vais bebê-la em horários determinados.

[NOTE]
====
. Cerca de 0,6 l. Veja o Ap. B14.
====

[[v26-4-12]]

^<<v26-4-12,12>>^ “Comerás o teu pão como se fosse um pão redondo de cevada. Deves cozê-lo diante dos olhos deles, usando fezes humanas secas como combustível.”

[[v26-4-13]]

^<<v26-4-13,13>>^ E Jeová acrescentou: “Da mesma forma, os israelitas comerão um pão impuro entre as nações pelas quais os espalharei.”

[[v26-4-14]]

^<<v26-4-14,14>>^ Então eu disse: “Isso não, Soberano Senhor Jeová! Desde a minha juventude até agora nunca fiquei impuro^&#42;1^ por comer a carne de um animal encontrado morto ou de um animal dilacerado, nem entrou carne impura^&#42;2^ na minha boca.”

[NOTE]
====
. Ou: “a minha alma nunca ficou impura”.
. Ou: “imunda”.
====

[[v26-4-15]]

^<<v26-4-15,15>>^ Então ele disse-me: “Está bem, vou deixar-te usar estrume de boi em vez de fezes humanas para cozeres o teu pão.”

[[v26-4-16]]

^<<v26-4-16,16>>^ Depois, ele disse-me: “Filho do homem, vou cortar o suprimento de alimento^&#42;1^ em Jerusalém, e o povo, angustiado, comerá pão racionado por peso, e, apavorado, beberá água racionada por medida.

[NOTE]
====
. Lit.: “quebrar o bastão de pão”. Possivelmente, refere-se aos bastões em que se penduravam pães em forma de anel.
====

[[v26-4-17]]

^<<v26-4-17,17>>^ Isto acontecerá para que, sem terem pão nem água, olhem chocados uns para os outros e definhem por causa do seu erro.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]