include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-36-1]]

^<<v26-36-1,1>>^ “Filho do homem, profetiza o seguinte aos montes de Israel: ‘Montes de Israel, ouçam a palavra de Jeová.

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim diz o Soberano Senhor Jeová: “O inimigo gozou convosco, dizendo: ‘Ah! Até os montes antigos se tornaram nossa propriedade!’”’

[[v26-36-3]]

^<<v26-36-3,3>>^ “Portanto, profetiza o seguinte: ‘Assim diz o Soberano Senhor Jeová: “Visto que eles vos devastaram e vos atacaram de todas as direções, para que se tornassem propriedade dos sobreviventes^&#42;1^ dentre as nações, e visto que as pessoas não param de falar de vocês e de vos caluniar,

[NOTE]
====
. Lit.: “do restante; dos que restaram”.
====

[[v26-36-4]]

^<<v26-36-4,4>>^ por isso, ó montes de Israel, ouçam a palavra do Soberano Senhor Jeová! Assim diz o Soberano Senhor Jeová aos montes e às colinas, aos rios e aos vales, às ruínas que foram desoladas e às cidades abandonadas que foram saqueadas e ridicularizadas pelos sobreviventes das nações à sua volta;

[[v26-36-5]]

^<<v26-36-5,5>>^ a estes, o Soberano Senhor Jeová diz: ‘Vou falar no fogo do meu zelo contra os sobreviventes das nações e contra todo o Edom, os que com grande alegria e profundo desprezo^&#42;1^ afirmam que a minha terra é deles, para se apoderarem das suas pastagens e para a saquearem.’”’

[NOTE]
====
. Ou: “desprezo na alma”.
====

[[v26-36-6]]

^<<v26-36-6,6>>^ “Portanto, profetiza a respeito da terra de Israel, e diz aos montes e às colinas, aos rios e aos vales: ‘Assim diz o Soberano Senhor Jeová: “Ouçam! Vou falar no meu zelo e no meu furor, por causa da humilhação que sofreram da parte das nações.”’

[[v26-36-7]]

^<<v26-36-7,7>>^ “Portanto, assim diz o Soberano Senhor Jeová: ‘Eu mesmo ergo a minha mão e juro que as nações vizinhas também sofrerão a sua própria vergonha.

[[v26-36-8]]

^<<v26-36-8,8>>^ Vocês, porém, montes de Israel, produzirão ramos e darão frutos para o meu povo Israel, pois eles voltarão em breve.

[[v26-36-9]]

^<<v26-36-9,9>>^ Pois eu estou convosco e voltarei a minha atenção para vocês, e serão cultivados e semeados.

[[v26-36-10]]

^<<v26-36-10,10>>^ Multiplicarei o teu povo — toda a casa de Israel, toda ela —, as cidades serão habitadas e as ruínas serão reconstruídas.

[[v26-36-11]]

^<<v26-36-11,11>>^ Sim, multiplicarei o teu povo e o teu gado; eles aumentarão e vão tornar-se muitos. Farei com que sejam habitados como dantes, e vou fazer-vos prosperar mais do que no passado; e terão de saber que eu sou Jeová.

[[v26-36-12]]

^<<v26-36-12,12>>^ Farei com que pessoas — o meu povo Israel — andem sobre vocês, e eles tomarão posse de vocês. Vocês vão tornar-se a herança deles e nunca mais os deixarão sem filhos.’”

[[v26-36-13]]

^<<v26-36-13,13>>^ “Assim diz o Soberano Senhor Jeová: ‘Visto que vos estão a dizer: “És uma terra que devora as pessoas e deixas as tuas nações sem filhos”,

[[v26-36-14]]

^<<v26-36-14,14>>^ por isso, nunca mais devorarás as pessoas e nunca mais deixarás as tuas nações sem filhos’, diz o Soberano Senhor Jeová.

[[v26-36-15]]

^<<v26-36-15,15>>^ ‘Não te sujeitarei a mais nenhum insulto da parte das nações nem te farei suportar as ofensas da parte das pessoas, e nunca mais farás as tuas nações tropeçarem’, diz o Soberano Senhor Jeová.”

[[v26-36-16]]

^<<v26-36-16,16>>^ E recebi novamente a palavra de Jeová:

[[v26-36-17]]

^<<v26-36-17,17>>^ “Filho do homem, quando a casa de Israel estava a morar na terra deles, tornaram-na impura com os seus caminhos e com as suas ações. Os seus caminhos eram para mim como a impureza menstrual.

[[v26-36-18]]

^<<v26-36-18,18>>^ Então, despejei sobre eles o meu furor por causa do sangue que tinham derramado sobre a terra e por terem tornado a terra impura com os seus ídolos repugnantes.^&#42;1^

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-36-19]]

^<<v26-36-19,19>>^ Por isso, espalhei-os entre as nações e dispersei-os entre as terras. Julguei-os conforme os seus caminhos e as suas ações.

[[v26-36-20]]

^<<v26-36-20,20>>^ Contudo, quando eles chegaram àquelas nações, as pessoas profanaram o meu santo nome, dizendo a respeito deles: ‘Este é o povo de Jeová, mas eles tiveram de sair da terra dele.’

[[v26-36-21]]

^<<v26-36-21,21>>^ Por isso, terei consideração pelo meu santo nome, que a casa de Israel profanou entre as nações para as quais foram.”

[[v26-36-22]]

^<<v26-36-22,22>>^ “Portanto, diz à casa de Israel: ‘Assim diz o Soberano Senhor Jeová: “Não é por vossa causa que vou agir, ó casa de Israel, mas é pelo meu santo nome, que vocês profanaram entre as nações para as quais foram.”’

[[v26-36-23]]

^<<v26-36-23,23>>^ ‘Eu certamente santificarei o meu grande nome, que foi profanado entre as nações, que vocês profanaram entre elas; e as nações terão de saber que eu sou Jeová’, diz o Soberano Senhor Jeová, ‘quando eu for santificado no vosso meio diante dos olhos delas.

[[v26-36-24]]

^<<v26-36-24,24>>^ Vou tirar-vos dentre as nações e reunir-vos dentre todas as terras, e vou levar-vos de volta à vossa terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ Aspergirei água limpa sobre vocês, e ficarão puros; vou purificar-vos de toda a vossa impureza e de todos os vossos ídolos repugnantes.

[[v26-36-26]]

^<<v26-36-26,26>>^ Vou dar-vos um coração novo e porei no vosso íntimo um espírito novo. Tirarei do vosso corpo o coração de pedra e vou dar-vos um coração de carne.^&#42;1^

[NOTE]
====
. Isto é, um que seja sensível à orientação de Deus.
====

[[v26-36-27]]

^<<v26-36-27,27>>^ Porei o meu espírito no vosso íntimo e farei com que andem nos meus decretos, e obedecerão e cumprirão as minhas decisões judiciais.

[[v26-36-28]]

^<<v26-36-28,28>>^ Então, morarão na terra que dei aos vossos antepassados e serão o meu povo, e eu serei o vosso Deus.’

[[v26-36-29]]

^<<v26-36-29,29>>^ “‘Vou livrar-vos de toda a vossa impureza. Vou dizer aos cereais que produzam abundantemente, e não trarei fome sobre vocês.

[[v26-36-30]]

^<<v26-36-30,30>>^ Tornarei abundantes os frutos das árvores e os produtos dos campos, para que nunca mais sofram a vergonha de passar fome entre as nações.

[[v26-36-31]]

^<<v26-36-31,31>>^ Então, vão lembrar-se dos vossos maus caminhos e das vossas más ações, e sentirão nojo de vocês próprios por causa da vossa culpa e das vossas práticas detestáveis.

[[v26-36-32]]

^<<v26-36-32,32>>^ No entanto, saibam o seguinte: não é por vossa causa que faço isto’, diz o Soberano Senhor Jeová. ‘Pelo contrário, envergonhem-se e sintam-se humilhados por causa dos vossos caminhos, ó casa de Israel.’

[[v26-36-33]]

^<<v26-36-33,33>>^ “Assim diz o Soberano Senhor Jeová: ‘No dia em que eu vos purificar de toda a vossa culpa, farei com que as cidades sejam habitadas e as ruínas sejam reconstruídas.

[[v26-36-34]]

^<<v26-36-34,34>>^ A terra desolada, que estava desolada à vista de todos os que passavam, será cultivada.

[[v26-36-35]]

^<<v26-36-35,35>>^ E as pessoas dirão: “A terra desolada tornou-se como o jardim do Éden, e as cidades que estavam em ruínas, desoladas e derrubadas, agora estão fortificadas e habitadas.”

[[v26-36-36]]

^<<v26-36-36,36>>^ E as nações que restarem à vossa volta terão de saber que fui eu, Jeová, que reconstruí o que estava derrubado e plantei o que estava desolado. Fui eu, Jeová, que falei e fiz isso.’

[[v26-36-37]]

^<<v26-36-37,37>>^ “Assim diz o Soberano Senhor Jeová: ‘Além disso, permitirei que a casa de Israel me peça para fazer isto por eles: multiplicarei a sua população como um rebanho.

[[v26-36-38]]

^<<v26-36-38,38>>^ Como o rebanho dos santificados, como o rebanho de Jerusalém^&#42;1^ nas suas festividades, as cidades que estavam em ruínas ficarão cheias de rebanhos de pessoas; e terão de saber que eu sou Jeová.’”

[NOTE]
====
. Ou, possivelmente: “Como os rebanhos de ovelhas em Jerusalém destinados aos sacrifícios”.
====

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]