include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-26-1]]

^<<v26-26-1,1>>^ No décimo primeiro ano, no primeiro dia do mês, recebi a seguinte palavra de Jeová:

[[v26-26-2]]

^<<v26-26-2,2>>^ “Filho do homem, Tiro gozou com Jerusalém, dizendo: ‘Ah! A porta dos povos foi deitada abaixo! Tudo será meu e eu ficarei rica, agora que ela foi devastada.’

[[v26-26-3]]

^<<v26-26-3,3>>^ Por isso, assim diz o Soberano Senhor Jeová: ‘Estou contra ti, ó Tiro, e levantarei muitas nações contra ti, assim como o mar levanta as suas ondas.

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão as muralhas de Tiro e derrubarão as suas torres. Rasparei o seu solo e farei dela uma rocha lisa.

[[v26-26-5]]

^<<v26-26-5,5>>^ Ela irá tornar-se um lugar para secar redes de arrasto no meio do mar.’
“‘Pois eu mesmo falei’, diz o Soberano Senhor Jeová, ‘e ela irá tornar-se despojo para as nações.

[[v26-26-6]]

^<<v26-26-6,6>>^ Os seus povoados^&#42;1^ no continente serão massacrados com a espada, e as pessoas terão de saber que eu sou Jeová’.

[NOTE]
====
. Lit.: “As suas filhas”.
====

[[v26-26-7]]

^<<v26-26-7,7>>^ “Pois assim diz o Soberano Senhor Jeová: ‘Vou trazer Nabucodonosor,^&#42;1^ rei de Babilónia, desde o norte contra Tiro; ele é rei de reis, com cavalos, carros de guerra, cavaleiros e um exército de muitos soldados.^&#42;2^

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
. Lit.: “povos”.
====

[[v26-26-8]]

^<<v26-26-8,8>>^ Ele destruirá com a espada os seus povoados no continente, construirá à tua volta um muro de cerco, levantará contra ti uma rampa de ataque e erguerá contra ti um grande escudo.

[[v26-26-9]]

^<<v26-26-9,9>>^ Golpeará as tuas muralhas com um aríete^&#42;1^ e demolirá as tuas torres com machados.^&#42;2^

[NOTE]
====
. Ou: “uma máquina de guerra”.
. Ou: “espadas”.
====

[[v26-26-10]]

^<<v26-26-10,10>>^ Os seus cavalos serão tantos que a sua poeira irá cobrir-te. O som da cavalaria, das rodas e dos carros de guerra fará tremer as tuas muralhas quando ele entrar pelos teus portões, como homens que invadem uma cidade com as muralhas abertas por brechas.

[[v26-26-11]]

^<<v26-26-11,11>>^ Os cascos dos seus cavalos calcarão todas as tuas ruas; ele matará o teu povo com a espada, e as tuas fortes colunas cairão por terra.

[[v26-26-12]]

^<<v26-26-12,12>>^ Eles irão despojar-te dos teus recursos, saquear as tuas mercadorias, derrubar as tuas muralhas e demolir as tuas belas casas; então, lançarão na água as tuas pedras, as tuas madeiras e o teu solo.’

[[v26-26-13]]

^<<v26-26-13,13>>^ “‘Porei fim ao barulho das tuas canções, e nunca mais se ouvirá o som das tuas harpas.

[[v26-26-14]]

^<<v26-26-14,14>>^ Vou fazer de ti uma rocha lisa, e irás tornar-te um lugar para secar redes de arrasto. Nunca serás reconstruída, pois fui eu, Jeová, que falei’, diz o Soberano Senhor Jeová.

[[v26-26-15]]

^<<v26-26-15,15>>^ “Assim diz o Soberano Senhor Jeová a Tiro: ‘Não tremerão as ilhas com o som da tua queda, quando os mortalmente feridos^&#42;1^ gemerem e quando houver um massacre no teu meio?

[NOTE]
====
. Lit.: “os que foram mortos”.
====

[[v26-26-16]]

^<<v26-26-16,16>>^ Todos os príncipes^&#42;1^ do mar descerão dos tronos, tirarão as túnicas^&#42;2^ e irão despir-se das vestes bordadas, e serão tomados^&#42;3^ de tremor. Eles irão sentar-se no chão, tremer sem parar e olhar espantados para ti.

[NOTE]
====
. Ou: “maiorais”.
. Ou: “túnicas sem mangas”.
. Lit.: “vestidos”.
====

[[v26-26-17]]

^<<v26-26-17,17>>^ E cantarão uma lamentação a teu respeito, dizendo-te:
“Como ficaste destruída, tu que eras habitada por homens dos mares, a cidade louvada;
Tu^&#42;1^ e os teus habitantes eram poderosos no mar,
E espalhavam terror por todos os habitantes da terra!

[NOTE]
====
. Lit.: “Ela”.
====

[[v26-26-18]]

^<<v26-26-18,18>>^ As ilhas tremerão no dia da tua queda;
As ilhas do mar ficarão apavoradas com o teu fim.”’

[[v26-26-19]]

^<<v26-26-19,19>>^ “Pois assim diz o Soberano Senhor Jeová: ‘Quando eu te devastar, tornando-te igual às cidades desabitadas, quando eu te inundar com as águas turbulentas e fores coberta pelas fortes águas,

[[v26-26-20]]

^<<v26-26-20,20>>^ vou levar-te, a ti e aos que descem à cova^&#42;1^ contigo, para onde estão as pessoas dos tempos antigos. Vou fazer com que mores no lugar mais profundo, como os lugares antigos já devastados, ao lado dos que descem à cova, para que não sejas habitada. Então, vou glorificar^&#42;2^ a terra dos vivos.

[NOTE]
====
. Ou: “sepultura”.
. Ou: “ornamentar”.
====

[[v26-26-21]]

^<<v26-26-21,21>>^ “‘Trarei sobre ti uma calamidade repentina, e deixarás de existir. Irão procurar-te, mas nunca mais serás encontrada’, diz o Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]