include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v26-6-1]]

^<<v26-6-1,1>>^ Recebi novamente a palavra de Jeová:

[[v26-6-2]]

^<<v26-6-2,2>>^ “Filho do homem, vira-te para os montes de Israel e profetiza contra eles.

[[v26-6-3]]

^<<v26-6-3,3>>^ Diz: ‘Ó montes de Israel, ouçam a palavra do Soberano Senhor Jeová: Assim diz o Soberano Senhor Jeová aos montes, às colinas, aos rios e aos vales: “Vejam! Vou trazer contra vocês uma espada e vou destruir os vossos altos sagrados.

[[v26-6-4]]

^<<v26-6-4,4>>^ Os vossos altares serão demolidos, os vossos altares de incenso serão destroçados, e lançarei os vossos mortos diante dos vossos ídolos repugnantes.^&#42;1^

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v26-6-5]]

^<<v26-6-5,5>>^ Lançarei os cadáveres do povo de Israel diante dos seus ídolos repugnantes e espalharei os vossos ossos ao redor dos vossos altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Em todas as regiões em que moram, as cidades serão devastadas, e os altos sagrados serão demolidos e ficarão devastados. Os vossos altares serão demolidos e destroçados, os vossos ídolos repugnantes serão destruídos, os vossos altares de incenso serão derrubados, e as vossas obras serão eliminadas.

[[v26-6-7]]

^<<v26-6-7,7>>^ E os mortos cairão no vosso meio, e vocês terão de saber que eu sou Jeová.

[[v26-6-8]]

^<<v26-6-8,8>>^ “‘“Eu, porém, vou deixar um restante, pois alguns de vocês escaparão da espada entre as nações quando forem espalhados pelas terras.

[[v26-6-9]]

^<<v26-6-9,9>>^ E aqueles que escaparem irão lembrar-se de mim entre as nações para onde serão levados cativos. Hão de aperceber-se de como fiquei triste por causa do seu coração infiel^&#42;1^ que se desviou de mim e por causa dos seus olhos que desejam ardentemente^&#42;2^ os seus ídolos repugnantes. Eles ficarão envergonhados e terão nojo de todas as coisas más e detestáveis que fizeram.

[NOTE]
====
. Ou: “imoral; promíscuo”.
. Ou: “seguem de maneira imoral”.
====

[[v26-6-10]]

^<<v26-6-10,10>>^ Eles terão de saber que eu sou Jeová e que as minhas ameaças de lhes trazer esta calamidade não eram em vão.”’

[[v26-6-11]]

^<<v26-6-11,11>>^ “Assim diz o Soberano Senhor Jeová: ‘Bate as mãos, bate com os pés no chão e lamenta todas as coisas más e detestáveis cometidas pela casa de Israel, pois eles cairão mortos pela espada, pela fome e pela peste.

[[v26-6-12]]

^<<v26-6-12,12>>^ Quem estiver longe morrerá pela peste, quem estiver perto cairá pela espada, e todo aquele que escapar destas coisas e restar morrerá pela fome. Vou dar vazão a todo o meu furor contra eles.

[[v26-6-13]]

^<<v26-6-13,13>>^ E vocês terão de saber que eu sou Jeová, quando os seus mortos estiverem caídos entre os seus ídolos repugnantes, ao redor dos seus altares, sobre todas as colinas elevadas, no cume de todos os montes, debaixo de todas as árvores frondosas e debaixo dos galhos de grandes árvores onde eles faziam ofertas de aroma agradável^&#42;1^ para apaziguar todos os seus ídolos repugnantes.

[NOTE]
====
. Ou: “ofereciam aromas agradáveis”.
====

[[v26-6-14]]

^<<v26-6-14,14>>^ Vou estender a mão contra eles e farei o país ficar desolado, e todos os lugares onde eles moram ficarão mais desolados do que o deserto^&#42;1^ perto de Dibla. E terão de saber que eu sou Jeová.’”

[NOTE]
====
. Veja o Glossário.
====

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]