include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v61-2-1]]

^<<v61-2-1,1>>^ No entanto, houve também falsos profetas entre o povo, assim como haverá falsos instrutores entre vocês. Estes introduzirão subtilmente seitas destrutivas e negarão até mesmo o dono que os comprou, trazendo sobre si próprios uma destruição rápida.

[[v61-2-2]]

^<<v61-2-2,2>>^ Além disso, muitos seguirão a sua conduta insolente,^&#42;1^ e, por causa deles, as pessoas falarão mal do caminho da verdade.

[NOTE]
====
. Ou: “os seus atos de conduta desavergonhada”. Plural da palavra grega asélgeia. Veja o Glossário.
====

[[v61-2-3]]

^<<v61-2-3,3>>^ Também, movidos por ganância, eles irão explorar-vos com palavras enganosas. Contudo, a sua condenação, decretada há muito tempo, não tardará, e a sua destruição não está a dormir.

[[v61-2-4]]

^<<v61-2-4,4>>^ De facto, Deus não se refreou de punir os anjos que pecaram, mas lançou-os no Tártaro,^&#42;1^ acorrentando-os em^&#42;2^ densa escuridão e reservando-os para o julgamento.

[NOTE]
====
. Veja o Glossário.
. Ou, possivelmente: “colocando-os em covas de”.
====

[[v61-2-5]]

^<<v61-2-5,5>>^ Ele também não se refreou de punir um mundo antigo, mas preservou Noé, pregador da justiça, juntamente com mais sete, quando trouxe um dilúvio sobre um mundo de pessoas ímpias.

[[v61-2-6]]

^<<v61-2-6,6>>^ E ele condenou as cidades de Sodoma e Gomorra, reduzindo-as a cinzas, estabelecendo para as pessoas ímpias um padrão das coisas que hão de vir.

[[v61-2-7]]

^<<v61-2-7,7>>^ Mas ele livrou o justo Ló, que se sentia muito aflito por causa da conduta insolente^&#42;1^ dos transgressores.

[NOTE]
====
. Ou: “conduta desavergonhada”. Em grego, asélgeia. Veja o Glossário.
====

[[v61-2-8]]

^<<v61-2-8,8>>^ (Porque, enquanto esse homem justo morava entre eles, dia após dia, a sua alma^&#42;1^ justa era atormentada por ver e ouvir aquelas ações contra a lei.)

[NOTE]
====
. Veja o Glossário.
====

[[v61-2-9]]

^<<v61-2-9,9>>^ Portanto, Jeová^&#42;1^ sabe livrar da provação os que lhe têm devoção, mas reservar os injustos para serem destruídos^&#42;2^ no dia do julgamento,

[NOTE]
====
. Veja o Ap. A5.
. Lit.: “decepados”.
====

[[v61-2-10]]

^<<v61-2-10,10>>^ especialmente os que procuram aviltar a carne de outros e desprezam a autoridade.^&#42;1^
Atrevidos e obstinados, não têm medo de falar mal dos gloriosos,

[NOTE]
====
. Ou: “menosprezam o senhorio”.
====

[[v61-2-11]]

^<<v61-2-11,11>>^ ao passo que os anjos, embora sejam maiores em força e poder, não os acusam com insultos, por respeito a^&#42;1^ Jeová.^&#42;2^

[NOTE]
====
. Ou: “diante de”.
. Veja o Ap. A5.
====

[[v61-2-12]]

^<<v61-2-12,12>>^ Estes homens, porém, tal como animais irracionais que agem por instinto e nascem^&#42;1^ para serem apanhados e destruídos, falam mal das coisas que desconhecem. Eles sofrerão a destruição trazida pelo seu próprio proceder destrutivo,

[NOTE]
====
. Ou: “nascem naturalmente”.
====

[[v61-2-13]]

^<<v61-2-13,13>>^ sofrendo o mal como retribuição pelo mal que fizeram.
Sentem prazer em entregar-se a uma vida de excessos, em pleno dia. Eles são manchas e defeitos, e deleitam-se nos^&#42;1^ seus ensinamentos enganosos enquanto se banqueteiam convosco.

[NOTE]
====
. Ou: “entregam-se com prazer irrestrito aos”.
====

[[v61-2-14]]

^<<v61-2-14,14>>^ Os seus olhos estão cheios de adultério e são incapazes de parar de pecar, e eles seduzem os que são^&#42;1^ instáveis. O seu coração foi treinado na ganância. São filhos amaldiçoados.

[NOTE]
====
. Ou: “as almas”.
====

[[v61-2-15]]

^<<v61-2-15,15>>^ Abandonaram o caminho reto e desviaram-se. Seguiram o caminho do filho de Beor, Balaão, que amou a recompensa de fazer injustiça,

[[v61-2-16]]

^<<v61-2-16,16>>^ mas foi repreendido por violar aquilo que era certo. Um animal de carga, mudo, falando com uma voz humana, refreou o proceder louco do profeta.

[[v61-2-17]]

^<<v61-2-17,17>>^ Estes homens são fontes sem água e neblinas impelidas por uma violenta tempestade, e foi-lhes reservada a mais profunda escuridão.

[[v61-2-18]]

^<<v61-2-18,18>>^ Eles fazem declarações pomposas, mas vazias. Apelando aos desejos da carne e com conduta insolente,^&#42;1^ seduzem os que acabaram de escapar dos que vivem no erro.

[NOTE]
====
. Ou: “atos de conduta desavergonhada”. Plural da palavra grega asélgeia. Veja o Glossário.
====

[[v61-2-19]]

^<<v61-2-19,19>>^ Embora prometam liberdade a essas pessoas, eles próprios são escravos da corrupção; pois todo aquele que é vencido por alguém torna-se seu escravo.^&#42;1^

[NOTE]
====
. Ou: “é vencido por algo torna-se escravo disso”.
====

[[v61-2-20]]

^<<v61-2-20,20>>^ Certamente, se eles, depois de escaparem das contaminações do mundo pelo conhecimento exato do Senhor e Salvador Jesus Cristo, ficam novamente envolvidos nestas mesmas coisas e são vencidos, o seu estado final é pior do que o inicial.

[[v61-2-21]]

^<<v61-2-21,21>>^ Teria sido melhor para eles que não tivessem conhecido de modo exato o caminho da justiça, do que, depois de o terem conhecido, desviarem-se do mandamento santo que receberam.

[[v61-2-22]]

^<<v61-2-22,22>>^ Com eles, aconteceu o que diz o provérbio verdadeiro: “O cão voltou ao seu próprio vómito, e a porca, depois de lavada, voltou a revolver-se na lama.”

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]