include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v61-3-1]]

^<<v61-3-1,1>>^ Amados, esta é agora a segunda carta que vos escrevo, e nela, como na minha primeira, desperto, por meio de um lembrete, a vossa capacidade de pensar de modo claro,

[[v61-3-2]]

^<<v61-3-2,2>>^ para que se lembrem das declarações feitas anteriormente^&#42;1^ pelos santos profetas e do mandamento do Senhor e Salvador, transmitido por meio dos vossos apóstolos.

[NOTE]
====
. Ou: “das coisas preditas”.
====

[[v61-3-3]]

^<<v61-3-3,3>>^ Antes de mais nada, saibam que nos últimos dias surgirão ridicularizadores com as suas expressões de gozo, agindo segundo os seus próprios desejos.

[[v61-3-4]]

^<<v61-3-4,4>>^ Eles dirão: “Onde é que está essa prometida presença dele? Ora, desde o tempo em que os nossos antepassados adormeceram na morte, todas as coisas continuam exatamente como eram desde o princípio da criação.”

[[v61-3-5]]

^<<v61-3-5,5>>^ Pois eles ignoram propositadamente este facto: há muito tempo, existiam céus e uma terra firmemente situada fora da água e no meio da água pela palavra de Deus;

[[v61-3-6]]

^<<v61-3-6,6>>^ e, por meio dessas coisas, o mundo daquele tempo sofreu destruição ao ser inundado pela água.

[[v61-3-7]]

^<<v61-3-7,7>>^ No entanto, pela mesma palavra, os céus e a terra que agora existem estão reservados para o fogo e a ser guardados até ao dia do julgamento e da destruição das pessoas ímpias.

[[v61-3-8]]

^<<v61-3-8,8>>^ Contudo, não despercebam o seguinte, amados: para Jeová,^&#42;1^ um dia é como mil anos, e mil anos são como um dia.

[NOTE]
====
. Veja o Ap. A5.
====

[[v61-3-9]]

^<<v61-3-9,9>>^ Jeová^&#42;1^ não é vagaroso com respeito à sua promessa, como alguns pensam,^&#42;2^ mas ele é paciente convosco, porque não deseja que ninguém seja destruído, mas deseja que todos alcancem o arrependimento.

[NOTE]
====
. Veja o Ap. A5.
. Ou: “como alguns consideram a vagarosidade”.
====

[[v61-3-10]]

^<<v61-3-10,10>>^ O dia de Jeová,^&#42;1^ porém, virá como um ladrão e, nesse dia, os céus passarão com um estrondo,^&#42;2^ e os elementos, estando intensamente quentes, serão dissolvidos, e a terra e as obras que nela existem serão expostas.

[NOTE]
====
. Veja o Ap. A5.
. Isto é, com o som de um objeto que passa rápido.
====

[[v61-3-11]]

^<<v61-3-11,11>>^ Visto que todas estas coisas serão assim dissolvidas, pensem no tipo de pessoas que devem ser. Devem ser pessoas de conduta santa e praticar atos de devoção a Deus,

[[v61-3-12]]

^<<v61-3-12,12>>^ enquanto aguardam e têm bem em mente^&#42;1^ a presença do dia de Jeová,^&#42;2^ pelo qual os céus serão destruídos em chamas, e os elementos se derreterão com o calor intenso.

[NOTE]
====
. Ou: “e desejam ansiosamente”. Lit.: “apressam”.
. Veja o Ap. A5.
====

[[v61-3-13]]

^<<v61-3-13,13>>^ Mas há novos céus e uma nova terra que aguardamos segundo a sua promessa, e nestes há de morar a justiça.

[[v61-3-14]]

^<<v61-3-14,14>>^ Portanto, amados, visto que aguardam estas coisas, façam o máximo para que ele finalmente vos encontre sem mancha e sem defeito, e em paz.

[[v61-3-15]]

^<<v61-3-15,15>>^ Além disso, considerem a paciência do nosso Senhor como salvação, assim como também o nosso amado irmão Paulo vos escreveu, segundo a sabedoria que lhe foi dada,

[[v61-3-16]]

^<<v61-3-16,16>>^ falando destas coisas, tal como o faz em todas as suas cartas. No entanto, algumas coisas que nelas se encontram são difíceis de entender, e os ignorantes^&#42;1^ e instáveis estão a distorcê-las, assim como fazem também com o restante das Escrituras, para a sua própria destruição.

[NOTE]
====
. Ou: “os não ensinados”.
====

[[v61-3-17]]

^<<v61-3-17,17>>^ Portanto, amados, sabendo disto com antecedência, tenham cuidado para não serem desviados pelo erro dos transgressores e para não caírem da vossa posição firme.^&#42;1^

[NOTE]
====
. Ou: “vossa estabilidade”.
====

[[v61-3-18]]

^<<v61-3-18,18>>^ Pelo contrário, continuem a crescer na bondade imerecida e no conhecimento do nosso Senhor e Salvador Jesus Cristo. A ele seja dada a glória tanto agora como até ao dia da eternidade. Amém.

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]