include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-7-1]]

^<<v38-7-1,1>>^ E, no quarto ano do rei Dario, Zacarias recebeu a palavra de Jeová, no dia quatro do nono mês, isto é, o mês de quisleu.^&#42;1^

[NOTE]
====
. Veja o Ap. B15.
====

[[v38-7-2]]

^<<v38-7-2,2>>^ O povo de Betel enviou Sarezer e Regem-Meleque com os seus homens, para suplicarem o favor^&#42;1^ de Jeová,

[NOTE]
====
. Ou: “abrandarem a face”.
====

[[v38-7-3]]

^<<v38-7-3,3>>^ dizendo aos sacerdotes da casa^&#42;1^ de Jeová dos exércitos e aos profetas: “Será que devo chorar no quinto mês e jejuar, assim como tenho feito durante tantos anos?”

[NOTE]
====
. Ou: “do templo”.
====

[[v38-7-4]]

^<<v38-7-4,4>>^ Recebi novamente a palavra de Jeová dos exércitos:

[[v38-7-5]]

^<<v38-7-5,5>>^ “Diz a todo o povo desta terra e aos sacerdotes: ‘Quando jejuavam e se lamentavam no quinto e no sétimo mês, durante 70 anos, era realmente para mim que jejuavam?

[[v38-7-6]]

^<<v38-7-6,6>>^ E, quando comiam e bebiam, não era para vocês mesmos que comiam e bebiam?

[[v38-7-7]]

^<<v38-7-7,7>>^ Não deviam obedecer às palavras que Jeová proclamou por meio dos antigos profetas, enquanto Jerusalém e as cidades ao seu redor estavam habitadas e em paz, e enquanto o Neguebe e a Sefelá estavam habitados?’”

[[v38-7-8]]

^<<v38-7-8,8>>^ Zacarias recebeu novamente a palavra de Jeová:

[[v38-7-9]]

^<<v38-7-9,9>>^ “Assim diz Jeová dos exércitos: ‘Julguem com verdadeira justiça e tratem-se uns aos outros com amor leal e misericórdia.

[[v38-7-10]]

^<<v38-7-10,10>>^ Não defraudem a viúva nem o órfão,^&#42;1^ nem o estrangeiro nem o pobre; e não tramem no coração o mal uns contra os outros.’

[NOTE]
====
. Ou: “órfão de pai”.
====

[[v38-7-11]]

^<<v38-7-11,11>>^ No entanto, eles recusavam-se a prestar atenção; de modo obstinado, viraram as costas e taparam os ouvidos para não ouvirem.

[[v38-7-12]]

^<<v38-7-12,12>>^ Endureceram o coração como um diamante^&#42;1^ e não obedeceram à lei^&#42;2^ e às palavras que Jeová dos exércitos tinha enviado por meio do seu espírito, usando os antigos profetas. Por isso, houve grande indignação da parte de Jeová dos exércitos.”

[NOTE]
====
. Ou, possivelmente: “uma pedra dura”, como uma pedra de esmeril.
. Ou: “instrução”.
====

[[v38-7-13]]

^<<v38-7-13,13>>^ “‘Assim como eles não escutavam quando eu^&#42;1^ os chamava, eu também não escutava quando eles me chamavam’, diz Jeová dos exércitos.

[NOTE]
====
. Lit.: “ele”.
====

[[v38-7-14]]

^<<v38-7-14,14>>^ ‘Com uma tempestade, espalhei-os por todas as nações que eles não conheciam, e a terra que eles deixaram para trás ficou desolada, sem ninguém que passasse por ela ou voltasse para lá; pois eles fizeram da terra desejável um motivo de terror.’”

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]