include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-1-1]]

^<<v38-1-1,1>>^ No segundo ano de Dario, no oitavo mês, o profeta Zacarias,^&#42;1^ filho de Berequias, filho de Ido, recebeu a seguinte palavra de Jeová:

[NOTE]
====
. Que significa “Jeová lembrou-se”.
====

[[v38-1-2]]

^<<v38-1-2,2>>^ “Jeová ficou extremamente indignado com os vossos pais.

[[v38-1-3]]

^<<v38-1-3,3>>^ “Diz-lhes: ‘Assim diz Jeová dos exércitos: “‘Voltem para mim’, diz Jeová dos exércitos, ‘e eu voltarei para vocês’, diz Jeová dos exércitos.”’

[[v38-1-4]]

^<<v38-1-4,4>>^ “‘Não se tornem como os vossos pais, a quem os profetas anteriores proclamaram: “Assim diz Jeová dos exércitos: ‘Por favor, afastem-se^&#42;1^ dos vossos maus caminhos e das vossas más ações.’”’
“‘Contudo, eles não me escutaram nem me prestaram atenção’, diz Jeová.

[NOTE]
====
. Ou: “retornem”.
====

[[v38-1-5]]

^<<v38-1-5,5>>^ “‘Onde é que os vossos pais estão agora? E será que os profetas viveram para sempre?

[[v38-1-6]]

^<<v38-1-6,6>>^ No entanto, as minhas palavras e os meus decretos, que ordenei aos meus servos, os profetas, alcançaram os vossos pais, não alcançaram?’ Então, eles voltaram para mim e disseram: ‘Jeová dos exércitos lidou connosco de acordo com os nossos caminhos e as nossas ações, assim como tinha decidido.’”

[[v38-1-7]]

^<<v38-1-7,7>>^ No dia 24 do décimo primeiro mês, isto é, o mês de sebate,^&#42;1^ no segundo ano de Dario, o profeta Zacarias, filho de Berequias, filho de Ido, recebeu a palavra de Jeová:

[NOTE]
====
. Veja o Ap. B15.
====

[[v38-1-8]]

^<<v38-1-8,8>>^ “Tive uma visão de noite. Havia um homem montado num cavalo vermelho, e ele estava parado entre as murtas no desfiladeiro; e atrás dele havia cavalos vermelhos, castanhos e brancos.”

[[v38-1-9]]

^<<v38-1-9,9>>^ Então, perguntei: “Quem são estes, meu senhor?”
O anjo que falava comigo respondeu: “Vou mostrar-te quem são eles.”

[[v38-1-10]]

^<<v38-1-10,10>>^ E o homem que estava parado entre as murtas disse: “Estes são os que Jeová enviou para percorrer a terra.”

[[v38-1-11]]

^<<v38-1-11,11>>^ E eles disseram ao anjo de Jeová que estava entre as murtas: “Percorremos a terra e vimos que toda a terra está tranquila e em paz.”

[[v38-1-12]]

^<<v38-1-12,12>>^ Em vista disso, o anjo de Jeová disse: “Ó Jeová dos exércitos, até quando é que negarás a tua misericórdia a Jerusalém e às cidades de Judá, com as quais ficaste indignado durante estes setenta anos?”

[[v38-1-13]]

^<<v38-1-13,13>>^ Com palavras bondosas e consoladoras, Jeová respondeu ao anjo que falava comigo.

[[v38-1-14]]

^<<v38-1-14,14>>^ De seguida, o anjo que falava comigo disse-me: “Proclama: ‘Assim diz Jeová dos exércitos: “Tenho zelo de Jerusalém e de Sião, um grande zelo.

[[v38-1-15]]

^<<v38-1-15,15>>^ Estou indignado, muito indignado com as nações que se sentem seguras; pois, quando me indignei apenas um pouco, elas aumentaram a calamidade.”’

[[v38-1-16]]

^<<v38-1-16,16>>^ “Portanto, assim diz Jeová: ‘“Voltarei a Jerusalém com misericórdia, e a minha casa será reconstruída nela”, diz Jeová dos exércitos, “e a corda de medir será estendida sobre Jerusalém”.’

[[v38-1-17]]

^<<v38-1-17,17>>^ “Proclama ainda: ‘Assim diz Jeová dos exércitos: “As minhas cidades transbordarão novamente de coisas boas; e Jeová voltará a consolar Sião e a escolher Jerusalém.”’”

[[v38-1-18]]

^<<v38-1-18,18>>^ Depois disso, levantei os olhos e vi quatro chifres.

[[v38-1-19]]

^<<v38-1-19,19>>^ E perguntei ao anjo que falava comigo: “O que são estes chifres?” Ele respondeu: “Estes são os chifres que dispersaram Judá, Israel e Jerusalém.”

[[v38-1-20]]

^<<v38-1-20,20>>^ A seguir, Jeová mostrou-me quatro ferreiros.^&#42;1^

[NOTE]
====
. Ou: “artesãos”.
====

[[v38-1-21]]

^<<v38-1-21,21>>^ Eu perguntei: “O que é que estes ferreiros vêm fazer?”
Ele disse: “Estes são os chifres que dispersaram Judá a ponto de ninguém poder levantar a cabeça. Estes ferreiros virão para aterrorizá-los, para derrubar os chifres das nações que levantaram os seus chifres contra a terra de Judá, a fim de dispersar os seus habitantes.”

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]