include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-2-1]]

^<<v38-2-1,1>>^ E levantei os olhos e vi um homem com uma corda de medir na mão.

[[v38-2-2]]

^<<v38-2-2,2>>^ Perguntei-lhe, então: “Onde é que vais?”
Ele respondeu: “Vou medir Jerusalém para ver qual é a sua largura e o seu comprimento.”

[[v38-2-3]]

^<<v38-2-3,3>>^ Então, o anjo que falava comigo saiu, e outro anjo veio ao seu encontro.

[[v38-2-4]]

^<<v38-2-4,4>>^ Ele disse-lhe: “Corre até lá e diz àquele jovem: ‘“Jerusalém será habitada como uma cidade sem muralhas,^&#42;1^ por causa de todos os homens e animais no seu interior.

[NOTE]
====
. Ou: “terra campestre”.
====

[[v38-2-5]]

^<<v38-2-5,5>>^ E eu”, diz Jeová, “vou tornar-me uma muralha de fogo ao seu redor, e serei a glória no seu meio”.’”

[[v38-2-6]]

^<<v38-2-6,6>>^ “Venham! Venham! Fujam da terra do norte”, diz Jeová.
“Pois eu espalhei-vos pelos quatro ventos dos céus”, diz Jeová.

[[v38-2-7]]

^<<v38-2-7,7>>^ “Vem, Sião! Foge, tu que moras com a filha de Babilónia.

[[v38-2-8]]

^<<v38-2-8,8>>^ Pois assim diz Jeová dos exércitos, aquele que, depois de ter sido glorificado,^&#42;1^ me enviou às nações que vos saqueavam: ‘Aquele que toca em vocês, toca na menina do meu olho.^&#42;2^

[NOTE]
====
. Lit.: “depois da glória”.
. Ou: “toca no meu globo ocular”.
====

[[v38-2-9]]

^<<v38-2-9,9>>^ Pois, agora, agitarei o punho^&#42;1^ contra eles, e eles hão de tornar-se despojo para os seus próprios escravos.’ E vocês certamente saberão que foi Jeová dos exércitos que me enviou.

[NOTE]
====
. Ou: “levantarei a mão”.
====

[[v38-2-10]]

^<<v38-2-10,10>>^ “Grita de alegria, ó filha de Sião; pois vou chegar e residir no teu meio”, diz Jeová.

[[v38-2-11]]

^<<v38-2-11,11>>^ “Nesse dia, muitas nações se unirão a Jeová e se tornarão meu povo; e eu vou residir contigo.” E terás de saber que Jeová dos exércitos me enviou até ti.

[[v38-2-12]]

^<<v38-2-12,12>>^ Jeová tomará posse de Judá como sua porção no solo sagrado, e ele voltará a escolher Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Que toda a humanidade^&#42;1^ fique em silêncio perante Jeová, porque é da sua santa morada que ele atua.

[NOTE]
====
. Lit.: “toda a carne”.
====

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]