include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-8-1]]

^<<v38-8-1,1>>^ Recebi novamente a palavra de Jeová dos exércitos:

[[v38-8-2]]

^<<v38-8-2,2>>^ “Assim diz Jeová dos exércitos: ‘Terei zelo de Sião, um grande zelo, e, com grande furor, terei zelo dela.’”

[[v38-8-3]]

^<<v38-8-3,3>>^ “Assim diz Jeová: ‘Voltarei para Sião e residirei em Jerusalém. E Jerusalém será chamada cidade da verdade;^&#42;1^ e o monte de Jeová dos exércitos, monte santo.’”

[NOTE]
====
. Ou: “fidelidade”.
====

[[v38-8-4]]

^<<v38-8-4,4>>^ “Assim diz Jeová dos exércitos: ‘Homens e mulheres idosos voltarão a sentar-se nas praças de Jerusalém, cada um com o seu bastão na mão por causa da idade avançada.^&#42;1^

[NOTE]
====
. Lit.: “por causa da abundância de dias”.
====

[[v38-8-5]]

^<<v38-8-5,5>>^ E as praças da cidade irão encher-se de meninos e meninas a brincar.’”

[[v38-8-6]]

^<<v38-8-6,6>>^ “Assim diz Jeová dos exércitos: ‘Embora isto possa parecer demasiado difícil para o restante deste povo nesses dias, será que também deve parecer demasiado difícil para mim?’, diz Jeová dos exércitos.”

[[v38-8-7]]

^<<v38-8-7,7>>^ “Assim diz Jeová dos exércitos: ‘Vou salvar o meu povo, tirando-o das terras do leste e do oeste.^&#42;1^

[NOTE]
====
. Ou: “da terra do nascente e da terra do poente”.
====

[[v38-8-8]]

^<<v38-8-8,8>>^ E vou trazê-los de volta e eles morarão em Jerusalém; eles vão tornar-se o meu povo, e eu vou tornar-me o seu Deus em verdade^&#42;1^ e justiça.’”

[NOTE]
====
. Ou: “fidelidade”.
====

[[v38-8-9]]

^<<v38-8-9,9>>^ “Assim diz Jeová dos exércitos: ‘Fortaleçam as mãos,^&#42;1^ vocês que agora ouvem estas palavras da boca dos profetas, as mesmas palavras ditas no dia em que se lançou o alicerce da casa de Jeová dos exércitos para se construir o templo.

[NOTE]
====
. Ou: “Tenham coragem”.
====

[[v38-8-10]]

^<<v38-8-10,10>>^ Pois, antes daquele tempo, não se pagava pelo trabalho dos homens nem dos animais; e, por causa do inimigo, não havia segurança para ir e vir, pois eu tinha posto todos os homens uns contra os outros.’

[[v38-8-11]]

^<<v38-8-11,11>>^ “‘Mas, agora, não tratarei o restante deste povo como tratei no passado’, diz Jeová dos exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ ‘Pois será semeada a semente da paz; a videira produzirá os seus frutos, a terra dará a sua produção, e os céus darão o seu orvalho; e eu farei com que o restante deste povo herde tudo isto.

[[v38-8-13]]

^<<v38-8-13,13>>^ E assim como vocês se tornaram um exemplo a ser citado em maldições entre as nações, ó casa de Judá e casa de Israel, assim vos salvarei, e hão de tornar-se uma bênção. Não tenham medo! Que as vossas mãos sejam fortes.’^&#42;1^

[NOTE]
====
. Ou: “Tenham coragem.”
====

[[v38-8-14]]

^<<v38-8-14,14>>^ “Pois assim diz Jeová dos exércitos: ‘“Assim como decidi trazer-vos calamidade quando os vossos antepassados me deixaram indignado”, diz Jeová dos exércitos, “e não o lamentei,

[[v38-8-15]]

^<<v38-8-15,15>>^ agora, estou decidido a fazer o bem a Jerusalém e à casa de Judá. Não tenham medo!”’

[[v38-8-16]]

^<<v38-8-16,16>>^ “‘Estas são as coisas que devem fazer: digam a verdade uns aos outros, e os julgamentos nos vossos portões devem promover a verdade e a paz.

[[v38-8-17]]

^<<v38-8-17,17>>^ Não tramem no coração o mal uns contra os outros nem amem juramentos falsos; pois eu odeio todas essas coisas’, diz Jeová.”

[[v38-8-18]]

^<<v38-8-18,18>>^ Recebi novamente a palavra de Jeová dos exércitos:

[[v38-8-19]]

^<<v38-8-19,19>>^ “Assim diz Jeová dos exércitos: ‘O jejum do quarto mês, o jejum do quinto mês, o jejum do sétimo mês e o jejum do décimo mês serão ocasiões de exultação e alegria para a casa de Judá — festividades alegres. Portanto, amem a verdade e a paz.’

[[v38-8-20]]

^<<v38-8-20,20>>^ “Assim diz Jeová dos exércitos: ‘Vai chegar o dia em que povos e habitantes de muitas cidades virão;

[[v38-8-21]]

^<<v38-8-21,21>>^ e os habitantes de uma cidade irão ter com os de outra e dirão: “Vamos! Vamos suplicar o favor^&#42;1^ de Jeová e procurar a Jeová dos exércitos. Eu também irei.”

[NOTE]
====
. Ou: “abrandar a face”.
====

[[v38-8-22]]

^<<v38-8-22,22>>^ E muitos povos e poderosas nações virão procurar a Jeová dos exércitos em Jerusalém e suplicar o favor^&#42;1^ de Jeová.’

[NOTE]
====
. Ou: “abrandar a face”.
====

[[v38-8-23]]

^<<v38-8-23,23>>^ “Assim diz Jeová dos exércitos: ‘Nesses dias, dez homens de todas as línguas das nações agarrarão, sim, agarrarão firmemente a túnica^&#42;1^ de um judeu,^&#42;2^ dizendo: “Queremos ir convosco, pois ouvimos dizer que Deus está convosco.”’”

[NOTE]
====
. Ou: “barra da veste”.
. Lit.: “um homem judeu”.
====

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]