include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-5-1]]

^<<v38-5-1,1>>^ Levantei novamente os olhos e vi um rolo a voar.

[[v38-5-2]]

^<<v38-5-2,2>>^ E o anjo perguntou-me: “O que é que vês?”
Eu respondi: “Vejo um rolo a voar. Tem 20 côvados^&#42;1^ de comprimento e 10 côvados de largura.”

[NOTE]
====
. Um côvado equivalia a 44,5 cm. Veja o Ap. B14.
====

[[v38-5-3]]

^<<v38-5-3,3>>^ Então, ele disse-me: “Esta é a maldição que se estende pela face de toda a terra, porque todo aquele que furta, como está escrito num dos lados do rolo, tem ficado impune; e todo aquele que jura falsamente, como está escrito no outro lado do rolo, tem ficado impune.

[[v38-5-4]]

^<<v38-5-4,4>>^ ‘Eu enviei-a’, diz Jeová dos exércitos, ‘e ela entrará na casa do ladrão e na casa daquele que jura falsamente em meu nome; ficará dentro dessa casa e consumirá a casa, o seu madeiramento e as suas pedras’.”

[[v38-5-5]]

^<<v38-5-5,5>>^ De seguida, o anjo que falava comigo aproximou-se e disse-me: “Levanta os olhos, por favor, e vê o que está a surgir.”

[[v38-5-6]]

^<<v38-5-6,6>>^ E eu perguntei: “O que é aquilo?”
Ele respondeu: “É o recipiente de uma efa^&#42;1^ que está a surgir.” E acrescentou: “Esta é a sua aparência em toda a terra.”^&#42;2^

[NOTE]
====
. Lit.: “a efa”, referindo-se aqui a um recipiente ou cesto usado para medir uma efa, que equivalia a 22 l. Veja o Ap. B14.
. Ou: “esta terra”.
====

[[v38-5-7]]

^<<v38-5-7,7>>^ Então, vi que a tampa redonda de chumbo tinha sido levantada, e havia uma mulher sentada dentro do recipiente.

[[v38-5-8]]

^<<v38-5-8,8>>^ Ele disse: “Esta é a Maldade.” E empurrou-a novamente para dentro do recipiente e, depois, tapou a boca do recipiente com força, com o peso de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ Depois disso, levantei os olhos e vi duas mulheres que se aproximavam, e elas voavam alto com o vento. Tinham asas como as asas da cegonha. E levantaram o recipiente entre a terra e o céu.

[[v38-5-10]]

^<<v38-5-10,10>>^ Eu perguntei ao anjo que falava comigo: “Para onde é que elas estão a levar o recipiente?”

[[v38-5-11]]

^<<v38-5-11,11>>^ Ele respondeu: “Para a terra de Sinear,^&#42;1^ onde vão construir uma casa para a mulher; e, quando a casa ficar pronta, a mulher será lá colocada, no seu devido lugar.”

[NOTE]
====
. Isto é, Babilónia.
====

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]