include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-4-1]]

^<<v38-4-1,1>>^ O anjo que tinha falado comigo voltou e despertou-me, assim como se desperta alguém do sono.

[[v38-4-2]]

^<<v38-4-2,2>>^ Então, ele perguntou-me: “O que é que vês?”
E eu respondi: “Vejo um candelabro, todo de ouro, com uma tigela em cima. Tem sete lâmpadas, sim, sete; e as lâmpadas, no seu topo, têm sete tubos.

[[v38-4-3]]

^<<v38-4-3,3>>^ E há duas oliveiras ao seu lado, uma à direita da tigela e outra à esquerda.”

[[v38-4-4]]

^<<v38-4-4,4>>^ De seguida, perguntei ao anjo que falava comigo: “O que significam estas coisas, meu senhor?”

[[v38-4-5]]

^<<v38-4-5,5>>^ E o anjo que falava comigo respondeu: “Não sabes o que significam estas coisas?”
Eu disse: “Não, meu senhor.”

[[v38-4-6]]

^<<v38-4-6,6>>^ E ele disse-me: “Esta é a palavra de Jeová a Zorobabel: ‘“Não por força militar nem por poder, mas pelo meu espírito”, diz Jeová dos exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ Quem és tu, ó grande montanha? Diante de Zorobabel, irás tornar-te uma planície. E ele trará a pedra de remate entre gritos: “Que maravilha! Que maravilha!”’”

[[v38-4-8]]

^<<v38-4-8,8>>^ Recebi novamente a palavra de Jeová:

[[v38-4-9]]

^<<v38-4-9,9>>^ “Foram as mãos de Zorobabel que lançaram o alicerce desta casa, e serão as suas mãos que a terminarão. E terás de saber que Jeová dos exércitos me enviou até vocês.

[[v38-4-10]]

^<<v38-4-10,10>>^ Quem desprezou o dia de pequenos começos?^&#42;1^ Pois eles irão alegrar-se e verão o prumo^&#42;2^ na mão de Zorobabel. Estes sete são os olhos de Jeová, que percorrem toda a terra.”

[NOTE]
====
. Ou: “das coisas pequenas”.
. Lit.: “a pedra, o estanho”.
====

[[v38-4-11]]

^<<v38-4-11,11>>^ Então, perguntei-lhe: “O que representam estas duas oliveiras, uma à direita e outra à esquerda do candelabro?”

[[v38-4-12]]

^<<v38-4-12,12>>^ Perguntei também: “O que representam os dois feixes de ramos^&#42;1^ das oliveiras que derramam o líquido dourado por meio dos dois tubos de ouro?”

[NOTE]
====
. Isto é, os ramos da árvore carregados de frutos.
====

[[v38-4-13]]

^<<v38-4-13,13>>^ De seguida, ele perguntou-me: “Não sabes o que estas coisas representam?”
Eu respondi: “Não, meu senhor.”

[[v38-4-14]]

^<<v38-4-14,14>>^ Ele disse: “Estes são os dois ungidos que estão de pé ao lado do Senhor de toda a terra.”

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]