include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-12-1]]

^<<v38-12-1,1>>^ Proclamação:
“Esta é a palavra de Jeová a respeito de Israel”, diz Jeová,
Aquele que estendeu os céus,
Que lançou o alicerce da terra
E que formou o espírito^&#42;1^ do homem dentro dele.

[NOTE]
====
. Ou: “fôlego”.
====

[[v38-12-2]]

^<<v38-12-2,2>>^ “Farei de Jerusalém um cálice^&#42;1^ que fará cambalear todos os povos ao redor; e haverá um cerco contra Judá e também contra Jerusalém.

[NOTE]
====
. Ou: “uma tigela”.
====

[[v38-12-3]]

^<<v38-12-3,3>>^ Nesse dia, farei de Jerusalém uma pedra pesada^&#42;1^ para todos os povos. Sem falta, todos os que a levantarem ficarão gravemente feridos; e todas as nações da terra serão ajuntadas contra ela.

[NOTE]
====
. Ou: “de carga”.
====

[[v38-12-4]]

^<<v38-12-4,4>>^ Nesse dia”, diz Jeová, “atingirei todos os cavalos com pânico e os seus cavaleiros com loucura. Manterei os meus olhos sobre a casa de Judá, mas atingirei todos os cavalos dos povos com cegueira.

[[v38-12-5]]

^<<v38-12-5,5>>^ E os chefes^&#42;1^ de Judá dirão no coração: ‘Os habitantes de Jerusalém são a nossa força, por meio de Jeová dos exércitos, seu Deus.’

[NOTE]
====
. Ou: “xeques”.
====

[[v38-12-6]]

^<<v38-12-6,6>>^ Nesse dia, tornarei os chefes de Judá como um braseiro no meio da lenha e como uma tocha acesa entre os feixes de cereais, e eles consumirão todos os povos ao redor, à direita e à esquerda; e Jerusalém será novamente habitada no seu lugar,^&#42;1^ em Jerusalém.

[NOTE]
====
. Ou: “lugar legítimo”.
====

[[v38-12-7]]

^<<v38-12-7,7>>^ “E Jeová salvará primeiro as tendas de Judá, para que a beleza^&#42;1^ da casa de David e a beleza^&#42;2^ dos habitantes de Jerusalém não sejam demasiado grandes em comparação com Judá.

[NOTE]
====
. Ou: “o esplendor”.
. Ou: “o esplendor”.
====

[[v38-12-8]]

^<<v38-12-8,8>>^ Nesse dia, Jeová será uma defesa ao redor dos habitantes de Jerusalém. Nesse dia, quem tropeçar^&#42;1^ entre eles será como David, e a casa de David será como Deus, como o anjo de Jeová que vai à sua frente.

[NOTE]
====
. Ou: “o mais fraco”.
====

[[v38-12-9]]

^<<v38-12-9,9>>^ E, nesse dia, certamente aniquilarei todas as nações que vierem contra Jerusalém.

[[v38-12-10]]

^<<v38-12-10,10>>^ “Derramarei sobre a casa de David e sobre os habitantes de Jerusalém o espírito de favor e de súplica; e eles olharão para aquele que trespassaram e irão lamentá-lo como se lamenta um filho único; e chorarão amargamente por ele como se chora por um filho primogénito.

[[v38-12-11]]

^<<v38-12-11,11>>^ Nesse dia, será grande o lamento em Jerusalém, como o lamento em Hadadrimom, na planície de Megido.

[[v38-12-12]]

^<<v38-12-12,12>>^ E esta terra lamentará, cada família lamentará sozinha: a família da casa de David sozinha, e as suas mulheres sozinhas; a família da casa de Natã sozinha, e as suas mulheres sozinhas;

[[v38-12-13]]

^<<v38-12-13,13>>^ a família da casa de Levi sozinha, e as suas mulheres sozinhas; a família dos simeítas sozinha, e as suas mulheres sozinhas;

[[v38-12-14]]

^<<v38-12-14,14>>^ todas as famílias restantes, cada família sozinha, e as suas mulheres sozinhas.

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]