include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-10-1]]

^<<v38-10-1,1>>^ “Peçam chuva a Jeová na época da chuva da primavera.
É Jeová que faz as nuvens de tempestade,
Que dá chuva abundante aos homens
E vegetação do campo a todos.

[[v38-10-2]]

^<<v38-10-2,2>>^ Pois os ídolos domésticos^&#42;1^ dizem mentiras;^&#42;2^
E os adivinhos têm visões enganosas.
Eles falam de sonhos sem valor
E tentam consolar em vão.
É por isso que as pessoas vaguearão como ovelhas.
Sofrerão, por não terem pastor.

[NOTE]
====
. Ou: “deuses domésticos”. Lit.: “terafins”.
. Ou: “o que é sinistro; o que é místico”.
====

[[v38-10-3]]

^<<v38-10-3,3>>^ A minha ira arde contra os pastores,
E eu vou ajustar contas com os líderes opressivos,^&#42;1^
Pois Jeová dos exércitos voltou a atenção para o seu rebanho, a casa de Judá,
E ele tornou-os como o seu majestoso cavalo na batalha.

[NOTE]
====
. Lit.: “os bodes”.
====

[[v38-10-4]]

^<<v38-10-4,4>>^ Dela vem o homem-chave,^&#42;1^
Dela vem o governante sustentador,^&#42;2^
Dela vem o arco de guerra;
Dela saem todos os superintendentes,^&#42;3^ todos juntos.

[NOTE]
====
. Lit.: “a torre angular”, figura aplicada a um homem vital ou importante; um chefe.
. Ou: “o prego”, figura aplicada a alguém que dá sustentação; um governante.
. Ou: “feitores”.
====

[[v38-10-5]]

^<<v38-10-5,5>>^ E eles irão tornar-se como guerreiros
Que pisam a lama das ruas na batalha.
Guerrearão, pois Jeová está com eles;
E os que montam cavalos serão envergonhados.

[[v38-10-6]]

^<<v38-10-6,6>>^ Tornarei a casa de Judá superior
E salvarei a casa de José.
Eu irei restabelecê-los,
Pois terei misericórdia deles;
Eles serão como se eu nunca os tivesse rejeitado;
Pois eu sou Jeová, seu Deus, e vou responder-lhes.

[[v38-10-7]]

^<<v38-10-7,7>>^ Os de Efraim irão tornar-se como um guerreiro valente,
E o seu coração irá alegrar-se como se fosse por causa do vinho.
Os seus filhos hão de ver isso e alegrar-se,
O seu coração exultará em Jeová.

[[v38-10-8]]

^<<v38-10-8,8>>^ ‘Vou assobiar-lhes e reuni-los;
Pois vou resgatá-los, e eles hão de tornar-se muitos,
E continuarão a ser muitos.

[[v38-10-9]]

^<<v38-10-9,9>>^ Embora eu os espalhe como sementes entre os povos,
Eles irão lembrar-se de mim nos lugares distantes;
Com os seus filhos, serão reanimados e voltarão.

[[v38-10-10]]

^<<v38-10-10,10>>^ Vou trazê-los de volta da terra do Egito,
E reuni-los da Assíria;
Vou levá-los à terra de Gileade e do Líbano,
E não haverá espaço suficiente para eles.

[[v38-10-11]]

^<<v38-10-11,11>>^ Ele atravessará o mar, causando^&#42;1^ aflição;
E golpeará as ondas do mar;
Todas as profundezas do rio Nilo se secarão.
O orgulho da Assíria será rebaixado,
E o cetro do Egito será removido.

[NOTE]
====
. Ou: “com”.
====

[[v38-10-12]]

^<<v38-10-12,12>>^ Vou torná-los superiores em Jeová,
E eles andarão no seu nome’, diz Jeová.”

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]