include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-6-1]]

^<<v38-6-1,1>>^ Então, levantei novamente os olhos e vi quatro carros de guerra que vinham do meio de dois montes, e os montes eram de cobre.

[[v38-6-2]]

^<<v38-6-2,2>>^ O primeiro carro era puxado por cavalos vermelhos, e o segundo carro por cavalos pretos.

[[v38-6-3]]

^<<v38-6-3,3>>^ O terceiro carro era puxado por cavalos brancos, e o quarto carro por cavalos com manchas e malhados.

[[v38-6-4]]

^<<v38-6-4,4>>^ Perguntei ao anjo que falava comigo: “O que são estes, meu senhor?”

[[v38-6-5]]

^<<v38-6-5,5>>^ O anjo respondeu-me: “Estes são os quatro espíritos dos céus que avançam depois de terem tomado a sua posição perante o Senhor de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ Aquele^&#42;1^ com os cavalos pretos avança para a terra do norte; os cavalos brancos avançam para além-mar; e os cavalos com manchas avançam para a terra do sul.

[NOTE]
====
. Isto é, o carro.
====

[[v38-6-7]]

^<<v38-6-7,7>>^ E os malhados estavam ansiosos para avançar e percorrer a terra.” Então, ele disse: “Avancem, percorram a terra.” E eles começaram a percorrer a terra.

[[v38-6-8]]

^<<v38-6-8,8>>^ De seguida, ele chamou-me e disse: “Vê, os que saem para a terra do norte fizeram o espírito de Jeová descansar na terra do norte.”

[[v38-6-9]]

^<<v38-6-9,9>>^ Recebi novamente a palavra de Jeová:

[[v38-6-10]]

^<<v38-6-10,10>>^ “Aceita de Heldai, Tobias e Jedaías o que eles trouxeram do povo que está no exílio; e, nesse dia, vai à casa de Josias, filho de Sofonias, juntamente com esses que vieram de Babilónia.

[[v38-6-11]]

^<<v38-6-11,11>>^ Deves receber a prata e o ouro, fazer uma coroa^&#42;1^ e colocá-la na cabeça do sumo sacerdote Josué, filho de Jeozadaque.

[NOTE]
====
. Ou: “uma coroa grandiosa”.
====

[[v38-6-12]]

^<<v38-6-12,12>>^ E diz-lhe:
“‘Assim diz Jeová dos exércitos: “Aqui está o homem cujo nome é Renovo. Ele brotará do seu próprio lugar e construirá o templo de Jeová.

[[v38-6-13]]

^<<v38-6-13,13>>^ É ele que construirá o templo de Jeová e é ele que assumirá a majestade. Ele irá sentar-se no seu trono e governará, e será também sacerdote no seu trono, e haverá um acordo pacífico entre os dois.^&#42;1^

[NOTE]
====
. Isto é, entre os seus papéis de governante e de sacerdote.
====

[[v38-6-14]]

^<<v38-6-14,14>>^ E a coroa^&#42;1^ ficará no templo de Jeová em memória^&#42;2^ de Helém, Tobias, Jedaías e Hem, filho de Sofonias.

[NOTE]
====
. Ou: “coroa grandiosa”.
. Ou: “como recordação”.
====

[[v38-6-15]]

^<<v38-6-15,15>>^ E os que estão longe virão para participar na construção do templo de Jeová.” E vocês terão de saber que Jeová dos exércitos me enviou até vocês. Isto acontecerá, se realmente escutarem a voz de Jeová, vosso Deus.’”

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]