include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-11-1]]

^<<v38-11-1,1>>^ “Abre as tuas portas, ó Líbano,
Para que um fogo consuma os teus cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Lamenta, ó junípero, pois o cedro caiu;
As árvores majestosas foram destruídas!
Lamentem, carvalhos de Basã,
Pois a densa floresta foi derrubada!

[[v38-11-3]]

^<<v38-11-3,3>>^ Escutem! Os pastores lamentam-se,
Pois a sua majestade foi devastada.
Escutem! Os leões novos^&#42;1^ rugem,
Pois os densos bosques ao longo do Jordão foram destruídos.

[NOTE]
====
. Ou: “leões novos jubados”.
====

[[v38-11-4]]

^<<v38-11-4,4>>^ “Assim diz Jeová, meu Deus: ‘Pastoreia o rebanho de ovelhas que está destinado à matança.

[[v38-11-5]]

^<<v38-11-5,5>>^ Os seus compradores matam-nas, mas não são considerados culpados. E os que as vendem dizem: “Louvado seja Jeová, pois vou ficar rico.” E os seus pastores não têm nenhuma compaixão delas.’

[[v38-11-6]]

^<<v38-11-6,6>>^ “‘Pois eu deixarei de ter compaixão pelos habitantes desta terra’, diz Jeová. ‘Entregarei cada homem nas mãos do seu próximo e do seu rei; e eles despedaçarão esta terra, e eu não os livrarei das mãos deles.’”

[[v38-11-7]]

^<<v38-11-7,7>>^ E, em vosso benefício, ó oprimidos do rebanho, passei a pastorear o rebanho que estava destinado à matança. Então, peguei em dois bastões, e chamei Bondade^&#42;1^ a um e União a outro, e comecei a pastorear o rebanho.

[NOTE]
====
. Ou: “Agradabilidade”.
====

[[v38-11-8]]

^<<v38-11-8,8>>^ E mandei embora três pastores num só mês, pois fiquei^&#42;1^ impaciente com eles; e eles também me detestavam.^&#42;2^

[NOTE]
====
. Ou: “a minha alma ficou”.
. Ou: “a alma deles também me detestava”.
====

[[v38-11-9]]

^<<v38-11-9,9>>^ E eu disse: “Não continuarei a pastorear-vos. Que morra aquela que está para morrer, e que seja eliminada aquela que está para ser eliminada. Quanto às que restarem, que devorem a carne umas das outras.”

[[v38-11-10]]

^<<v38-11-10,10>>^ Portanto, peguei no meu bastão chamado Bondade^&#42;1^ e cortei-o em pedaços, anulando o pacto que eu tinha feito com todos os povos.

[NOTE]
====
. Ou: “Agradabilidade”.
====

[[v38-11-11]]

^<<v38-11-11,11>>^ Então, ele foi anulado naquele dia e, assim, os oprimidos do rebanho que me observavam entenderam que isso era a palavra de Jeová.

[[v38-11-12]]

^<<v38-11-12,12>>^ E eu disse-lhes: “Se acharem melhor assim, paguem-me o salário; mas, caso contrário, não o paguem.” E eles pagaram-me^&#42;1^ o meu salário, 30 peças de prata.

[NOTE]
====
. Lit.: “pesaram-me”.
====

[[v38-11-13]]

^<<v38-11-13,13>>^ Por conseguinte, Jeová disse-me: “Deita-o no tesouro — o grandioso valor com que me avaliaram.” Portanto, peguei nas 30 peças de prata e deitei-as no tesouro da casa de Jeová.

[[v38-11-14]]

^<<v38-11-14,14>>^ Depois, cortei em pedaços o meu segundo bastão, chamado União, rompendo assim a fraternidade entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ E Jeová disse-me: “Agora, pega no equipamento de um pastor inútil.

[[v38-11-16]]

^<<v38-11-16,16>>^ Pois deixarei surgir um pastor nesta terra. Ele não cuidará das ovelhas que estão a morrer; não procurará a cria, nem curará a ovelha ferida, nem alimentará a saudável. Em vez disso, ele devorará a carne da gorda e arrancará os cascos das ovelhas.

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do meu pastor imprestável, que abandona o rebanho!
Uma espada atingirá o seu braço e o seu olho direito.
O seu braço irá secar-se completamente,
E o seu olho direito ficará totalmente cego.”^&#42;1^

[NOTE]
====
. Lit.: “turvo”.
====

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]