include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v38-9-1]]

^<<v38-9-1,1>>^ Proclamação:
“A palavra de Jeová é contra a terra de Hadraque,
E Damasco é o seu alvo^&#42;1^
— Porque os olhos de Jeová estão sobre a humanidade
E sobre todas as tribos de Israel —,

[NOTE]
====
. Lit.: “lugar de descanso”.
====

[[v38-9-2]]

^<<v38-9-2,2>>^ E contra Hamate, que faz fronteira com ela;
E contra Tiro e Sídon, por serem tão sábias.

[[v38-9-3]]

^<<v38-9-3,3>>^ Tiro construiu defesas^&#42;1^ para si.
Acumulou prata como pó,
E ouro como a sujidade das ruas.

[NOTE]
====
. Ou: “uma escarpa”.
====

[[v38-9-4]]

^<<v38-9-4,4>>^ Vejam! Jeová levará os seus bens
E destruirá o seu exército, atirando-o ao mar;^&#42;1^
E ela será consumida no fogo.

[NOTE]
====
. Ou, possivelmente: “destruirá o seu exército no mar”.
====

[[v38-9-5]]

^<<v38-9-5,5>>^ Ao ver isso, Ascalom ficará com medo;
Gaza sentirá muita angústia,
Assim como Ecrom, porque a sua esperança será envergonhada.
Gaza perderá o seu rei,
E Ascalom ficará desabitada.

[[v38-9-6]]

^<<v38-9-6,6>>^ Um filho ilegítimo irá estabelecer-se em Asdode,
E eu acabarei com o orgulho do filisteu.

[[v38-9-7]]

^<<v38-9-7,7>>^ Vou tirar-lhe o sangue^&#42;1^ da boca,
E os alimentos repugnantes dentre os dentes,
E ele ficará como restante para o nosso Deus.
E irá tornar-se como um chefe^&#42;2^ em Judá,
E Ecrom como o jebuseu.

[NOTE]
====
. Ou: “as coisas manchadas de sangue”.
. Ou: “xeque”.
====

[[v38-9-8]]

^<<v38-9-8,8>>^ Eu acamparei como um guarda^&#42;1^ para defender a minha casa
Contra quem vai e contra quem vem;
E nenhum feitor^&#42;2^ voltará a passar por lá,
Pois, agora, eu vi-o^&#42;3^ com os meus próprios olhos.

[NOTE]
====
. Ou: “posto avançado”.
. Ou: “opressor”.
. Pelos vistos, a aflição do seu povo.
====

[[v38-9-9]]

^<<v38-9-9,9>>^ Alegra-te muito, ó filha de Sião.
Grita em triunfo, ó filha de Jerusalém.
Olha! O teu rei vem a ti.
Ele é justo e traz salvação,^&#42;1^
É humilde e vem montado num jumento,
Num jumentinho, na cria de uma jumenta.

[NOTE]
====
. Ou: “e vitorioso; e salvo”.
====

[[v38-9-10]]

^<<v38-9-10,10>>^ Removerei de Efraim os carros de guerra,
E de Jerusalém os cavalos.
Os arcos de guerra serão removidos.
E ele proclamará paz às nações;
O seu domínio será de mar a mar,
E desde o rio^&#42;1^ até aos confins da terra.

[NOTE]
====
. Isto é, o rio Eufrates.
====

[[v38-9-11]]

^<<v38-9-11,11>>^ Quanto a ti, ó mulher, pelo sangue do teu pacto,
Libertarei os teus prisioneiros do poço que não tem água.

[[v38-9-12]]

^<<v38-9-12,12>>^ Voltem à fortaleza, prisioneiros com esperança.
Eu digo-te hoje:
‘Vou recompensar-te a dobrar, ó mulher.

[[v38-9-13]]

^<<v38-9-13,13>>^ Pois curvarei^&#42;1^ Judá como meu arco.
Efraim será a flecha do arco,
E eu despertarei os teus filhos, ó Sião,
Contra os teus filhos, ó Grécia,
E vou tornar-te como a espada de um guerreiro.’

[NOTE]
====
. Lit.: “pisarei”.
====

[[v38-9-14]]

^<<v38-9-14,14>>^ Jeová será visto sobre eles,
E a sua flecha será lançada como um raio.
O Soberano Senhor Jeová tocará a buzina
E avançará com os vendavais do sul.

[[v38-9-15]]

^<<v38-9-15,15>>^ Jeová dos exércitos irá defendê-los,
E eles devorarão e pisarão as pedras^&#42;1^ atiradas contra eles.
Beberão e ficarão agitados, como se fosse por causa do vinho;
E ficarão cheios como a tigela,
Como os cantos do altar.

[NOTE]
====
. Ou: “pedras de funda”.
====

[[v38-9-16]]

^<<v38-9-16,16>>^ Jeová, o seu Deus, irá salvá-los nesse dia
Como seu rebanho, seu povo;
Pois eles serão como as pedras preciosas de uma coroa^&#42;1^ que brilha sobre a terra dele.

[NOTE]
====
. Ou: “um diadema”.
====

[[v38-9-17]]

^<<v38-9-17,17>>^ Como é grande a sua bondade,
E como é grande a sua beleza!
O cereal dará vigor aos jovens,
E o vinho novo às moças.”^&#42;1^

[NOTE]
====
. Ou: “virgens”.
====

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]