include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-11-1]]

^<<v27-11-1,1>>^ “Eu, da minha parte, no primeiro ano de Dario, o medo, levantei-me para o fortalecer e proteger.^&#42;1^

[NOTE]
====
. Ou: “e como uma fortaleza para ele”.
====

[[v27-11-2]]

^<<v27-11-2,2>>^ O que eu te vou dizer agora é a verdade:
“Mais três reis se hão de levantar^&#42;1^ na Pérsia, e o quarto acumulará mais riquezas do que todos os outros. Quando ele se tornar forte por meio das suas riquezas, incitará todos^&#42;2^ contra o reino da Grécia.

[NOTE]
====
. Ou: “surgirão”.
. Ou: “tudo”.
====

[[v27-11-3]]

^<<v27-11-3,3>>^ “E há de levantar-se um rei poderoso, que reinará com domínio extenso e fará tudo o que quiser.

[[v27-11-4]]

^<<v27-11-4,4>>^ No entanto, quando ele se tiver levantado, o seu reino será partido e dividido pelos quatro ventos dos céus, mas não passará para os seus descendentes^&#42;1^ e não será como o domínio que ele exerceu, pois o seu reino será desarraigado e passará para outros, não para estes.

[NOTE]
====
. Ou: “a sua posteridade”.
====

[[v27-11-5]]

^<<v27-11-5,5>>^ “E o rei do sul, isto é, um dos seus príncipes, irá tornar-se forte. Porém, haverá outro mais forte do que ele, que reinará com domínio extenso, com maior autoridade do que a dele.

[[v27-11-6]]

^<<v27-11-6,6>>^ “Depois de alguns anos, eles farão uma aliança, e a filha do rei do sul virá ao rei do norte para fazer um acordo.^&#42;1^ Contudo, ela não manterá o poder do seu braço. E ele não se manterá de pé, nem o seu braço; e ela será entregue, assim como os que a trouxeram, aquele que causou o seu nascimento e aquele que a tornou forte naqueles tempos.

[NOTE]
====
. Ou: “acordo equitativo”.
====

[[v27-11-7]]

^<<v27-11-7,7>>^ No seu lugar, há de levantar-se um^&#42;1^ rebento das raízes dela, e ele irá ao exército, irá contra a fortaleza do rei do norte, agirá contra eles e vencerá.

[NOTE]
====
. Ou: “levantar-se alguém procedente do”.
====

[[v27-11-8]]

^<<v27-11-8,8>>^ Também chegará ao Egito com os seus deuses, com as suas imagens de metal,^&#42;1^ com os seus objetos preciosos^&#42;2^ de prata e de ouro e com cativos. Durante alguns anos, irá manter-se longe do rei do norte,

[NOTE]
====
. Ou: “estátuas fundidas”.
. Ou: “desejáveis”.
====

[[v27-11-9]]

^<<v27-11-9,9>>^ que irá contra o reino do rei do sul, mas retornará à sua própria terra.

[[v27-11-10]]

^<<v27-11-10,10>>^ “No que se refere aos seus filhos, irão preparar-se para a guerra e reunir um exército grande e numeroso. Ele certamente avançará e arrasará tudo como uma inundação. Porém, ele retornará, e guerreará até chegar à sua fortaleza.

[[v27-11-11]]

^<<v27-11-11,11>>^ “E o rei do sul ficará furioso e sairá para lutar contra ele, isto é, contra o rei do norte. Este reunirá uma grande multidão, mas a multidão será entregue nas mãos do outro.

[[v27-11-12]]

^<<v27-11-12,12>>^ E a multidão será levada. O coração dele irá enaltecer-se, e ele fará cair dezenas de milhares; mas não usará a sua forte posição.

[[v27-11-13]]

^<<v27-11-13,13>>^ “E o rei do norte voltará e reunirá uma multidão maior do que a primeira; e no fim dos tempos, depois de alguns anos, ele certamente chegará com um grande exército e com muitos recursos.

[[v27-11-14]]

^<<v27-11-14,14>>^ Nesses tempos, muitos se levantarão contra o rei do sul.
“E os homens violentos^&#42;1^ do teu povo hão de levantar-se para tentar fazer que uma visão se torne realidade, mas tropeçarão.

[NOTE]
====
. Ou: “os filhos dos ladrões”.
====

[[v27-11-15]]

^<<v27-11-15,15>>^ “E o rei do norte chegará e levantará uma rampa de ataque, e capturará uma cidade fortificada. E os braços^&#42;1^ do sul não se manterão de pé, nem os seus melhores homens; eles não terão poder para se manterem de pé.

[NOTE]
====
. Ou: “os exércitos”.
====

[[v27-11-16]]

^<<v27-11-16,16>>^ Aquele que virá contra ele fará tudo o que quiser, e ninguém se manterá de pé diante dele. Ficará de pé na Terra Gloriosa^&#42;1^ e, na sua mão, haverá a capacidade de exterminar.

[NOTE]
====
. Ou: “da Beleza”.
====

[[v27-11-17]]

^<<v27-11-17,17>>^ Ele estará determinado a^&#42;1^ vir com toda a força do seu reino, e haverá^&#42;2^ um acordo^&#42;3^ com ele; e ele agirá com eficiência. Quanto à filha de mulher, ser-lhe-á concedido que ele a arruíne. E ela não se manterá de pé e não continuará a pertencer-lhe.

[NOTE]
====
. Lit.: “fixará a sua face para”.
. Ou: “ele fará”.
. Ou: “termos equitativos”.
====

[[v27-11-18]]

^<<v27-11-18,18>>^ Ele voltará a sua atenção^&#42;1^ para as terras litorâneas e capturará muitas delas. Contudo, um comandante fará cessar a humilhação que sofreu às suas mãos, e essa humilhação acabará. Fará com que a humilhação volte sobre ele.

[NOTE]
====
. Ou: “face”.
====

[[v27-11-19]]

^<<v27-11-19,19>>^ Então, ele voltará a sua atenção para as fortalezas da sua própria terra; tropeçará e cairá, e não será encontrado.

[[v27-11-20]]

^<<v27-11-20,20>>^ “No seu lugar, há de levantar-se alguém que fará um exator^&#42;1^ passar pelo reino esplêndido. No entanto, em poucos dias, ele será destroçado, mas não em ira nem em guerra.

[NOTE]
====
. Possivelmente, um cobrador de impostos. Ou: “feitor”.
====

[[v27-11-21]]

^<<v27-11-21,21>>^ “E, no seu lugar, há de levantar-se um desprezado,^&#42;1^ a quem não darão a majestade do reino; e ele chegará durante um tempo de segurança^&#42;2^ e tomará posse do reino por meio de engano.^&#42;3^

[NOTE]
====
. Ou: “desprezível”.
. Ou, possivelmente: “sem avisar”.
. Ou: “intriga”.
====

[[v27-11-22]]

^<<v27-11-22,22>>^ E os braços^&#42;1^ da inundação serão arrastados por causa dele e serão destroçados; e o Líder do pacto também será destroçado.

[NOTE]
====
. Ou: “os exércitos”.
====

[[v27-11-23]]

^<<v27-11-23,23>>^ E, devido à aliança que farão com ele, ele irá usar de engano, erguer-se e tornar-se forte por meio de uma pequena nação.

[[v27-11-24]]

^<<v27-11-24,24>>^ Durante um tempo de segurança,^&#42;1^ ele entrará nas partes mais ricas^&#42;2^ da província^&#42;3^ e fará o que não fizeram os seus pais nem os pais dos seus pais. Distribuirá entre o povo despojo, espólio e bens; e planeará as suas tramas contra lugares fortificados, mas apenas por um tempo.

[NOTE]
====
. Ou, possivelmente: “sem avisar”.
. Lit.: “na gordura”.
. Ou: “do distrito jurisdicional”.
====

[[v27-11-25]]

^<<v27-11-25,25>>^ “E ele reunirá a sua força e a sua coragem^&#42;1^ contra o rei do sul, com um grande exército, e o rei do sul irá preparar-se para a guerra com um exército extremamente grande e poderoso. E não se manterá de pé, porque planearão tramá-lo.

[NOTE]
====
. Lit.: “o seu coração”.
====

[[v27-11-26]]

^<<v27-11-26,26>>^ Aqueles que comem as suas iguarias causarão a sua ruína.
“Quanto ao seu exército, será arrasado,^&#42;1^ e muitos cairão mortos.

[NOTE]
====
. Ou: “levado pela inundação”.
====

[[v27-11-27]]

^<<v27-11-27,27>>^ “No que se refere a estes dois reis, o seu coração irá inclinar-se para fazer o que é mau; eles irão sentar-se à mesma mesa e mentir um ao outro. Todavia, nada será bem-sucedido, porque o fim ainda é para o tempo determinado.

[[v27-11-28]]

^<<v27-11-28,28>>^ “E ele voltará à sua terra com uma grande quantidade de bens, e o seu coração será contra o pacto sagrado. Ele agirá com eficiência e voltará à sua terra.

[[v27-11-29]]

^<<v27-11-29,29>>^ “No tempo determinado, ele retornará e irá contra o sul. No entanto, esta vez não será como a anterior,

[[v27-11-30]]

^<<v27-11-30,30>>^ pois os navios de Quitim virão contra ele, e ele será humilhado.
“Ele voltará e despejará a sua fúria^&#42;1^ contra o pacto sagrado, e agirá com eficiência; e voltará e dará atenção aos que abandonam o pacto sagrado.

[NOTE]
====
. Ou: “condenação”.
====

[[v27-11-31]]

^<<v27-11-31,31>>^ E dele procedem braços^&#42;1^ que irão levantar-se e profanar o santuário, a fortaleza, e remover o sacrifício constante.^&#42;2^
“E estabelecerão a coisa repugnante que causa desolação.

[NOTE]
====
. Ou: “exércitos”.
. Ou: “regular”.
====

[[v27-11-32]]

^<<v27-11-32,32>>^ “Por meio de palavras enganosas,^&#42;1^ ele levará à apostasia os que violam^&#42;2^ o pacto. Porém, o povo que conhece o seu Deus vencerá e agirá com eficiência.

[NOTE]
====
. Ou: “bajulação; hipocrisia”.
. Lit.: “agem de modo mau contra”.
====

[[v27-11-33]]

^<<v27-11-33,33>>^ E os que têm discernimento^&#42;1^ entre o povo darão entendimento a muitos. E tropeçarão, caindo vítimas da espada e do fogo, do cativeiro e do saque, por alguns dias.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v27-11-34]]

^<<v27-11-34,34>>^ Contudo, quando tropeçarem, receberão um pouco de ajuda; e muitos se juntarão a eles por meio de declarações enganosas.^&#42;1^

[NOTE]
====
. Ou: “bajulação; hipocrisia”.
====

[[v27-11-35]]

^<<v27-11-35,35>>^ E alguns dos que têm discernimento^&#42;1^ serão levados a tropeçar, para que seja feita uma obra de refinamento por causa deles e para que seja feita uma purificação e um embranquecimento até ao tempo do fim; porque isso ainda é para o tempo determinado.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v27-11-36]]

^<<v27-11-36,36>>^ “O rei fará tudo o que quiser, e há de enaltecer-se e magnificar-se acima de todos os deuses; e dirá coisas chocantes contra o Deus dos deuses. E será bem-sucedido até acabar a fúria;^&#42;1^ porque o que foi determinado acontecerá.

[NOTE]
====
. Ou: “condenação”.
====

[[v27-11-37]]

^<<v27-11-37,37>>^ Ele não terá consideração pelo Deus dos seus pais; e não terá consideração pelo desejo de mulheres, nem por nenhum outro deus, pois há de magnificar-se acima de todos.

[[v27-11-38]]

^<<v27-11-38,38>>^ Em vez disso,^&#42;1^ dará glória ao deus das fortalezas. Dará glória a um deus que os seus pais não conheceram, por meio de ouro, prata, pedras preciosas e coisas valiosas.^&#42;2^

[NOTE]
====
. Ou: “No lugar dele”.
. Ou: “desejáveis”.
====

[[v27-11-39]]

^<<v27-11-39,39>>^ Com^&#42;1^ um deus estrangeiro, agirá com eficiência contra as fortalezas mais poderosas. Ele dará grande glória aos que lhe derem reconhecimento^&#42;2^ e fará com que governem entre muitos. E repartirá^&#42;3^ a terra por um preço.

[NOTE]
====
. Ou: “Ajudado por”.
. Ou, possivelmente: “a quem ele reconhecer”.
. Ou: “distribuirá”.
====

[[v27-11-40]]

^<<v27-11-40,40>>^ “No tempo do fim, o rei do sul vai envolver-se com ele numa troca de empurrões,^&#42;1^ e o rei do norte virá sobre ele como uma tempestade, com carros de guerra, cavaleiros e muitos navios; ele entrará nas terras e arrasará tudo como uma inundação.

[NOTE]
====
. Ou: “marradas”.
====

[[v27-11-41]]

^<<v27-11-41,41>>^ Também entrará na Terra Gloriosa,^&#42;1^ e muitas terras serão levadas a tropeçar. No entanto, estes são os que escaparão da sua mão: Edom, Moabe e a parte principal dos amonitas.

[NOTE]
====
. Ou: “da Beleza”.
====

[[v27-11-42]]

^<<v27-11-42,42>>^ Ele continuará a estender a mão contra as terras; quanto à terra do Egito, não escapará.

[[v27-11-43]]

^<<v27-11-43,43>>^ E ele reinará sobre os tesouros ocultos de ouro e de prata e sobre todas as coisas preciosas^&#42;1^ do Egito. E os líbios e os etíopes acompanharão os seus passos.^&#42;2^

[NOTE]
====
. Ou: “desejáveis”.
. Ou: “irão segui-lo”.
====

[[v27-11-44]]

^<<v27-11-44,44>>^ “Contudo, haverá notícias procedentes do leste^&#42;1^ e do norte que o perturbarão, e ele sairá com grande furor para aniquilar e entregar muitos à destruição.^&#42;2^

[NOTE]
====
. Ou: “nascente”.
. Ou: “devotar muitos à destruição”. Veja o Glossário.
====

[[v27-11-45]]

^<<v27-11-45,45>>^ Armará as suas tendas reais^&#42;1^ entre o grande mar e o monte santo da Terra Gloriosa;^&#42;2^ e chegará ao seu fim, e não haverá quem o ajude.

[NOTE]
====
. Ou: “palaciais”.
. Ou: “da Beleza”.
====

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]