include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-6-1]]

^<<v27-6-1,1>>^ Dario achou por bem designar 120 sátrapas para administrar todo o reino.

[[v27-6-2]]

^<<v27-6-2,2>>^ Acima deles, havia três altos funcionários, um dos quais era Daniel; os sátrapas deviam prestar-lhes contas, para que o rei não sofresse nenhum prejuízo.

[[v27-6-3]]

^<<v27-6-3,3>>^ E Daniel destacava-se entre os altos funcionários e os sátrapas, visto que havia nele um espírito extraordinário, e o rei pretendia designá-lo sobre todo o reino.

[[v27-6-4]]

^<<v27-6-4,4>>^ Naquele tempo, os altos funcionários e os sátrapas procuravam um motivo para acusar Daniel a respeito de questões de Estado,^&#42;1^ mas não conseguiam encontrar nenhuma base para acusação, nem nada corrupto, pois ele era digno de confiança, e não era culpado de nenhuma negligência ou corrupção.

[NOTE]
====
. Lit.: “do reino”.
====

[[v27-6-5]]

^<<v27-6-5,5>>^ Portanto, estes homens disseram: “Não encontraremos nenhum motivo para acusar Daniel, a não ser que seja algo relacionado com a lei do seu Deus.”

[[v27-6-6]]

^<<v27-6-6,6>>^ Por conseguinte, estes altos funcionários e sátrapas foram todos juntos à presença do rei e disseram-lhe: “Ó rei Dario, viva para sempre!

[[v27-6-7]]

^<<v27-6-7,7>>^ Todos os funcionários reais, os superintendentes, os sátrapas, os conselheiros reais e os governadores reuniram-se e concordaram que seja emitido um decreto real a impor uma proibição:^&#42;1^ durante 30 dias, todo aquele que fizer uma petição a qualquer deus ou homem sem ser a si, ó rei, deve ser lançado na cova dos leões.

[NOTE]
====
. Ou: “uma interdição”.
====

[[v27-6-8]]

^<<v27-6-8,8>>^ Agora, ó rei, estabeleça o decreto e assine-o, para que não seja mudado, segundo a lei dos medos e dos persas, que não pode ser anulada.”

[[v27-6-9]]

^<<v27-6-9,9>>^ Então, o rei Dario assinou o decreto com a proibição.

[[v27-6-10]]

^<<v27-6-10,10>>^ Assim que Daniel soube que o decreto tinha sido assinado, foi para a sua casa, que tinha as janelas do quarto de terraço abertas na direção de Jerusalém. E ele ajoelhou-se, orou e louvou o seu Deus, assim como fazia regularmente antes disso, três vezes por dia.

[[v27-6-11]]

^<<v27-6-11,11>>^ De repente, aqueles homens entraram e encontraram Daniel a fazer petições e a suplicar favor perante o seu Deus.

[[v27-6-12]]

^<<v27-6-12,12>>^ E eles foram falar com o rei e lembraram-no da proibição real: “O senhor não assinou uma proibição a estabelecer que, durante 30 dias, todo o homem que fizesse uma petição a qualquer deus ou homem sem ser ao senhor, ó rei, fosse lançado na cova dos leões?” O rei respondeu: “A questão está bem estabelecida segundo a lei dos medos e dos persas, que não pode ser anulada.”

[[v27-6-13]]

^<<v27-6-13,13>>^ Eles disseram imediatamente ao rei: “Daniel, que é um dos exilados de Judá, não fez caso do senhor, ó rei, nem da proibição que o senhor assinou; ele ora três vezes por dia.”

[[v27-6-14]]

^<<v27-6-14,14>>^ Quando o rei ouviu isso, ficou muito aflito, e tentou pensar numa maneira de livrar Daniel. Até ao pôr do sol, fez de tudo para salvá-lo.

[[v27-6-15]]

^<<v27-6-15,15>>^ Por fim, aqueles homens foram juntos falar com o rei; eles disseram ao rei: “Ó rei, lembre-se de que, segundo a lei dos medos e dos persas, não se pode mudar nenhuma proibição ou decreto emitidos pelo rei.”

[[v27-6-16]]

^<<v27-6-16,16>>^ Portanto, o rei deu a ordem, e trouxeram Daniel e lançaram-no na cova dos leões. O rei disse a Daniel: “O teu Deus, a quem serves incessantemente, há de livrar-te.”

[[v27-6-17]]

^<<v27-6-17,17>>^ Depois, trouxeram uma pedra e colocaram-na sobre a entrada^&#42;1^ da cova, e o rei selou-a com o seu anel de sinete e com o anel de sinete dos seus nobres, para que nada pudesse ser mudado no caso de Daniel.

[NOTE]
====
. Lit.: “boca”.
====

[[v27-6-18]]

^<<v27-6-18,18>>^ De seguida, o rei foi para o palácio. Passou a noite a jejuar e não aceitou nenhum divertimento;^&#42;1^ e não conseguia dormir.^&#42;2^

[NOTE]
====
. Ou, possivelmente: “não lhe foram trazidos músicos”.
. Lit.: “o seu sono fugia-lhe”.
====

[[v27-6-19]]

^<<v27-6-19,19>>^ Finalmente, quando o dia começou a clarear, o rei levantou-se e foi rapidamente à cova dos leões.

[[v27-6-20]]

^<<v27-6-20,20>>^ Ao chegar perto da cova, chamou por Daniel com voz triste. O rei perguntou a Daniel: “Ó Daniel, servo do Deus vivente, será que o teu Deus, a quem serves incessantemente, foi capaz de livrar-te dos leões?”

[[v27-6-21]]

^<<v27-6-21,21>>^ Daniel respondeu imediatamente ao rei: “Ó rei, viva para sempre!

[[v27-6-22]]

^<<v27-6-22,22>>^ O meu Deus enviou o seu anjo e fechou a boca dos leões, e eles não me fizeram mal, pois fui considerado inocente diante dele; e também não fiz nada contra o senhor, ó rei.”

[[v27-6-23]]

^<<v27-6-23,23>>^ O rei ficou muito alegre e ordenou que Daniel fosse tirado da cova. Quando Daniel foi tirado da cova, viram que não tinha sofrido qualquer dano, porque ele tinha confiado no seu Deus.

[[v27-6-24]]

^<<v27-6-24,24>>^ Seguidamente, o rei ordenou que trouxessem os homens que tinham acusado^&#42;1^ Daniel, e eles foram lançados na cova dos leões, com os seus filhos e as suas esposas. Antes de atingirem o fundo da cova, os leões atacaram-nos e despedaçaram todos os seus ossos.

[NOTE]
====
. Ou: “caluniado”.
====

[[v27-6-25]]

^<<v27-6-25,25>>^ Então, o rei Dario escreveu a todos os povos, nações e línguas, que moravam em toda a terra: “Que tenham grande paz!

[[v27-6-26]]

^<<v27-6-26,26>>^ Emito a ordem de que, em toda a extensão do meu reino, as pessoas tremam de temor diante do Deus de Daniel. Pois ele é o Deus vivente e permanece para sempre. O seu reino nunca será destruído, e o seu domínio é eterno.^&#42;1^

[NOTE]
====
. Ou: “a sua soberania é eterna”.
====

[[v27-6-27]]

^<<v27-6-27,27>>^ Ele livra, salva e realiza sinais e milagres nos céus e na terra, pois livrou Daniel das garras dos leões.”

[[v27-6-28]]

^<<v27-6-28,28>>^ Assim, Daniel prosperou no reino de Dario e no reino de Ciro, o persa.

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]