include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-8-1]]

^<<v27-8-1,1>>^ No terceiro ano do reinado do rei Belsazar, eu, Daniel, tive uma visão, depois daquela que tivera anteriormente.

[[v27-8-2]]

^<<v27-8-2,2>>^ Eu tive a visão e, enquanto observava, eu estava na fortaleza^&#42;1^ de Susã,^&#42;2^ que fica na província^&#42;3^ de Elão; tive a visão, e estava junto ao curso de água do Ulai.

[NOTE]
====
. Ou: “na cidadela; no palácio”.
. Ou: “Susa”.
. Ou: “no distrito jurisdicional”.
====

[[v27-8-3]]

^<<v27-8-3,3>>^ Quando levantei os olhos, vi um carneiro de pé diante do curso de água, e ele tinha dois chifres. Os dois chifres eram compridos, porém, um era mais comprido do que o outro, e o mais comprido surgiu depois.

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi o carneiro a dar marradas para o oeste, para o norte e para o sul, e nenhum animal selvagem conseguia permanecer de pé diante dele, e ninguém era capaz de livrar o que estivesse em seu poder.^&#42;1^ Ele fazia tudo o que queria e engrandecia-se.

[NOTE]
====
. Lit.: “na sua mão”.
====

[[v27-8-5]]

^<<v27-8-5,5>>^ Enquanto eu observava, apareceu um bode que vinha do oeste,^&#42;1^ atravessando toda a superfície da terra sem tocar no chão. E o bode tinha um chifre notável entre os olhos.

[NOTE]
====
. Ou: “poente”.
====

[[v27-8-6]]

^<<v27-8-6,6>>^ Ele vinha em direção ao carneiro de dois chifres, que eu tinha visto de pé diante do curso de água; corria na sua direção com toda a fúria.

[[v27-8-7]]

^<<v27-8-7,7>>^ Vi-o a aproximar-se do carneiro, cheio de fúria contra ele. Ele atacou o carneiro e partiu-lhe os dois chifres, e o carneiro não teve forças para lhe resistir. Ele derrubou o carneiro e pisou-o, e não houve quem o livrasse do seu poder.^&#42;1^

[NOTE]
====
. Lit.: “da sua mão”.
====

[[v27-8-8]]

^<<v27-8-8,8>>^ Depois, o bode engrandeceu-se extraordinariamente, mas, assim que se tornou poderoso, o grande chifre foi partido; então, no seu lugar, surgiram quatro chifres notáveis, em direção aos quatro ventos dos céus.

[[v27-8-9]]

^<<v27-8-9,9>>^ De um deles saiu outro chifre, pequeno, e cresceu até ficar muito grande, em direção ao sul, em direção ao leste^&#42;1^ e em direção à Terra Gloriosa.^&#42;2^

[NOTE]
====
. Ou: “nascente”.
. Ou: “à Beleza”.
====

[[v27-8-10]]

^<<v27-8-10,10>>^ Cresceu tanto que alcançou o exército dos céus, e fez cair para a terra alguns do exército e algumas das estrelas, e espezinhou-os.

[[v27-8-11]]

^<<v27-8-11,11>>^ Ele engrandeceu-se até mesmo contra o Príncipe do exército, e o sacrifício constante^&#42;1^ foi-Lhe tirado, e o lugar estabelecido do Seu santuário foi derrubado.

[NOTE]
====
. Ou: “regular”.
====

[[v27-8-12]]

^<<v27-8-12,12>>^ E foi entregue um exército, com o sacrifício constante,^&#42;1^ por causa da transgressão; e o chifre continuou a lançar a verdade por terra, e agiu e foi bem-sucedido.

[NOTE]
====
. Ou: “regular”.
====

[[v27-8-13]]

^<<v27-8-13,13>>^ E ouvi um santo a falar, e outro santo perguntou ao que estava a falar: “Quanto tempo é que durará a visão sobre o sacrifício constante^&#42;1^ e sobre a transgressão que causa desolação, para fazer do lugar santo e do exército coisas a serem espezinhadas?”

[NOTE]
====
. Ou: “regular”.
====

[[v27-8-14]]

^<<v27-8-14,14>>^ E ele disse-me: “Até terem passado 2300 noites e manhãs. E o lugar santo certamente será restabelecido na sua condição correta.”

[[v27-8-15]]

^<<v27-8-15,15>>^ Enquanto eu, Daniel, estava a ter a visão e procurava entendê-la, de repente, vi à minha frente alguém que parecia um homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi a voz de um homem, vinda do meio do Ulai; ele gritou: “Gabriel, faz com que ele entenda o que viu.”

[[v27-8-17]]

^<<v27-8-17,17>>^ Portanto, ele aproximou-se de onde eu estava. Mas, quando chegou, fiquei tão apavorado que me prostrei com o rosto por terra. Ele disse-me: “Compreende, ó filho do homem, que a visão é para o tempo do fim.”

[[v27-8-18]]

^<<v27-8-18,18>>^ No entanto, enquanto ele falava comigo, adormeci profundamente com o rosto no chão. Então, ele tocou-me e pôs-me de pé onde eu estava,

[[v27-8-19]]

^<<v27-8-19,19>>^ e disse: “Vou mostrar-te o que acontecerá na parte final do tempo da fúria,^&#42;1^ porque a visão é para o tempo determinado do fim.

[NOTE]
====
. Ou: “condenação”.
====

[[v27-8-20]]

^<<v27-8-20,20>>^ “O carneiro de dois chifres que viste representa os reis da Média e da Pérsia.

[[v27-8-21]]

^<<v27-8-21,21>>^ O bode peludo representa o rei da Grécia, e o chifre grande que havia entre os seus olhos representa o primeiro rei.

[[v27-8-22]]

^<<v27-8-22,22>>^ Quanto ao chifre que foi partido, de modo a que quatro se levantassem no seu lugar, haverá quatro reinos procedentes da sua nação que se levantarão, mas não com o seu poder.

[[v27-8-23]]

^<<v27-8-23,23>>^ “E na parte final desses reinos, quando os transgressores completarem as suas ações,^&#42;1^ há de levantar-se um rei de aparência feroz, que entende declarações ambíguas.^&#42;2^

[NOTE]
====
. Ou: “chegarem ao seu limite”.
. Ou: “que é hábil em intrigas”.
====

[[v27-8-24]]

^<<v27-8-24,24>>^ Ele irá tornar-se muito poderoso, mas não pelo seu próprio poder. Causará destruição de um modo extraordinário,^&#42;1^ e será bem-sucedido e agirá com eficiência. Ele arruinará poderosos, bem como o povo composto dos santos.

[NOTE]
====
. Ou: “Causará devastação terrível”.
====

[[v27-8-25]]

^<<v27-8-25,25>>^ E, com a sua astúcia, usará de falsidade para ser bem-sucedido; irá enaltecer-se no coração e, durante um período de segurança,^&#42;1^ arruinará muitos. Há de levantar-se até mesmo contra o Príncipe dos príncipes, mas será destroçado sem intervenção de mão humana.

[NOTE]
====
. Ou, possivelmente: “e, sem avisar”.
====

[[v27-8-26]]

^<<v27-8-26,26>>^ “O que foi dito na visão a respeito das noites e das manhãs é verdade, mas deves manter a visão em segredo, uma vez que se refere a dias que estão muito à frente.”^&#42;1^

[NOTE]
====
. Ou: “se refere ao futuro distante”.
====

[[v27-8-27]]

^<<v27-8-27,27>>^ Eu, Daniel, estava exausto e fiquei doente por alguns dias. Depois, levantei-me e fui cuidar do serviço do rei; mas eu estava atordoado por causa da visão, e ninguém conseguia entendê-la.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]