include::./index.adoc[]

[[v27-9-0]]
=== Daniel, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-9-1]]

^<<v27-9-1,1>>^ No primeiro ano de Dario, que era filho de Assuero, descendente dos medos, e que tinha sido feito rei sobre o reino dos caldeus,

[[v27-9-2]]

^<<v27-9-2,2>>^ sim, no primeiro ano do seu reinado, eu, Daniel, por meio dos livros,^&#42;1^ compreendi o número de anos para se cumprir a desolação de Jerusalém, conforme mencionado na palavra de Jeová dirigida ao profeta Jeremias; seriam 70 anos.

[NOTE]
====
. Isto é, pelos livros sagrados.
====

[[v27-9-3]]

^<<v27-9-3,3>>^ Então, recorri a^&#42;1^ Jeová, o verdadeiro Deus, suplicando-lhe em oração e jejuando, vestido de serapilheira^&#42;2^ e em cinzas.

[NOTE]
====
. Ou: “voltei a minha face para”.
. Veja o Glossário.
====

[[v27-9-4]]

^<<v27-9-4,4>>^ Orei a Jeová, meu Deus, e fiz uma confissão, dizendo-lhe:
“Ó Jeová, o verdadeiro Deus, o Grande, que inspira temor, aquele que guarda o seu pacto e demonstra amor leal aos que o amam e aos que guardam os seus mandamentos:

[[v27-9-5]]

^<<v27-9-5,5>>^ pecámos, fizemos o que é errado e o que é mau e rebelámo-nos; desviámo-nos dos teus mandamentos e das tuas decisões judiciais.

[[v27-9-6]]

^<<v27-9-6,6>>^ Não demos ouvidos aos teus servos, aos profetas, que falaram em teu nome aos nossos reis, aos nossos príncipes, aos nossos antepassados e a todo o povo.^&#42;1^

[NOTE]
====
. Lit.: “povo da terra”.
====

[[v27-9-7]]

^<<v27-9-7,7>>^ A ti, ó Jeová, pertence a justiça, mas hoje a vergonha^&#42;1^ pertence-nos a nós — aos homens de Judá, aos habitantes de Jerusalém e a todo o Israel, os de perto e os de longe, em todas as terras pelas quais os espalhaste, porque agiram de modo infiel para contigo.

[NOTE]
====
. Lit.: “vergonha de rosto”.
====

[[v27-9-8]]

^<<v27-9-8,8>>^ “Ó Jeová, é a nós que pertence a vergonha^&#42;1^ — aos nossos reis, aos nossos príncipes e aos nossos antepassados, porque pecámos contra ti.

[NOTE]
====
. Lit.: “vergonha de rosto”.
====

[[v27-9-9]]

^<<v27-9-9,9>>^ A Jeová, nosso Deus, pertencem a misericórdia e o perdão, pois rebelámo-nos contra ele.

[[v27-9-10]]

^<<v27-9-10,10>>^ Não obedecemos à voz de Jeová, nosso Deus; não seguimos as suas leis, que ele pôs diante de nós por meio dos seus servos, os profetas.

[[v27-9-11]]

^<<v27-9-11,11>>^ Todo o Israel transgrediu a tua Lei e desviou-se, desobedecendo à tua voz, de modo que derramaste sobre nós a maldição e o juramento escrito na Lei de Moisés, o servo do verdadeiro Deus, pois pecámos contra Ele.

[[v27-9-12]]

^<<v27-9-12,12>>^ Ele cumpriu as palavras que tinha dito contra nós e contra os nossos governantes, que nos governavam,^&#42;1^ e trouxe sobre nós uma grande calamidade. Debaixo de todo o céu, nunca se fez nada parecido com o que foi feito a Jerusalém.

[NOTE]
====
. Lit.: “os nossos juízes que nos julgavam”.
====

[[v27-9-13]]

^<<v27-9-13,13>>^ Assim como está escrito na Lei de Moisés, toda esta calamidade nos sobreveio. Mesmo assim, não procurámos o favor^&#42;1^ de Jeová, nosso Deus, por nos afastarmos do nosso erro e mostrarmos que compreendemos a tua verdade.^&#42;2^

[NOTE]
====
. Ou: “não abrandámos a face”.
. Ou: “fidelidade”.
====

[[v27-9-14]]

^<<v27-9-14,14>>^ “Assim, Jeová manteve-se atento e trouxe calamidade sobre nós, pois Jeová, nosso Deus, é justo em tudo o que faz; contudo, nós não obedecemos à sua voz.

[[v27-9-15]]

^<<v27-9-15,15>>^ “Ó Jeová, nosso Deus, agora que tiraste o teu povo da terra do Egito com mão poderosa e fizeste para ti um nome que perdura até hoje, nós pecámos e fizemos o que é mau.

[[v27-9-16]]

^<<v27-9-16,16>>^ Por favor, ó Jeová, segundo todos os teus atos justos, faz com que a tua ira e o teu furor se afastem da tua cidade, Jerusalém, o teu santo monte; pois, por causa dos nossos pecados e dos erros dos nossos antepassados, Jerusalém e o teu povo são alvo de desprezo para todos ao nosso redor.

[[v27-9-17]]

^<<v27-9-17,17>>^ E agora, ó nosso Deus, escuta a oração do teu servo e as suas súplicas, e, por tua própria causa, ó Jeová, faz a tua face brilhar sobre o teu santuário, que está desolado.

[[v27-9-18]]

^<<v27-9-18,18>>^ Inclina o teu ouvido, ó meu Deus, e ouve! Abre os olhos e vê a nossa condição desolada e a cidade que leva o teu nome; pois fazemos-te súplicas, não por causa dos nossos atos justos, mas por causa da tua grande misericórdia.

[[v27-9-19]]

^<<v27-9-19,19>>^ Ó Jeová, ouve. Ó Jeová, perdoa. Ó Jeová, presta atenção e atua! Não demores, por tua própria causa, ó meu Deus, pois a tua cidade e o teu povo levam o teu nome.”

[[v27-9-20]]

^<<v27-9-20,20>>^ Enquanto eu ainda falava, orava e confessava o meu pecado e o pecado do meu povo Israel, e fazia o meu pedido diante de Jeová, o meu Deus, em favor do santo monte do meu Deus,

[[v27-9-21]]

^<<v27-9-21,21>>^ sim, enquanto eu ainda falava em oração, Gabriel, o homem que eu tinha visto anteriormente na visão, aproximou-se de mim quando eu estava completamente exausto, por volta da hora da oferta do anoitecer.

[[v27-9-22]]

^<<v27-9-22,22>>^ E ele deu-me entendimento, dizendo:
“Ó Daniel, agora, vim para te dar compreensão^&#42;1^ e entendimento.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v27-9-23]]

^<<v27-9-23,23>>^ Quando começaste a fazer a tua súplica, foi emitida uma mensagem, que eu vim comunicar-te, porque és muito precioso.^&#42;1^ Portanto, considera o assunto e entende a visão.

[NOTE]
====
. Ou: “muito desejável; muito estimado”.
====

[[v27-9-24]]

^<<v27-9-24,24>>^ “Foram determinadas setenta semanas^&#42;1^ para o teu povo e para a tua cidade santa, a fim de terminar a transgressão, acabar com o pecado, fazer expiação do erro, trazer justiça eterna, selar a visão e a profecia,^&#42;2^ e ungir o Santo dos Santos.^&#42;3^

[NOTE]
====
. Isto é, semanas de anos.
. Lit.: “o profeta”.
. Ou: “o Santíssimo”.
====

[[v27-9-25]]

^<<v27-9-25,25>>^ Deves saber e entender o seguinte: desde o momento em que se emitir a ordem para restaurar e reconstruir Jerusalém, até à vinda do Messias,^&#42;1^ o Líder, haverá 7 semanas e, também, 62 semanas. Ela será restaurada e reconstruída, com praça pública e fosso, mas em tempos de aflição.

[NOTE]
====
. Ou: “do Ungido”.
====

[[v27-9-26]]

^<<v27-9-26,26>>^ “Depois das 62 semanas, o Messias será eliminado,^&#42;1^ sem nada para si.
“E o povo de um líder vindouro destruirá a cidade e o lugar santo. E o seu fim será pela inundação. Até ao fim, haverá guerra; o que foi determinado são desolações.

[NOTE]
====
. Ou: “decepado; morto”.
====

[[v27-9-27]]

^<<v27-9-27,27>>^ “Quanto ao pacto para muitos, ele vai mantê-lo em vigor por uma semana; e, na metade da semana, fará cessar o sacrifício e a oferta.
“E aquele que causa desolação virá na asa de coisas repugnantes; e o que foi determinado será derramado também sobre aquele que é desolado, até à exterminação.”

'''

xref:027-daniel/027-daniel-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-daniel/027-daniel-010.adoc#v27-10-0[Próximo Capítulo &#62;]