include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-7-1]]

^<<v27-7-1,1>>^ No primeiro ano de Belsazar, rei de Babilónia, Daniel teve um sonho, e passaram-lhe visões pela mente enquanto estava deitado na sua cama. Então, ele escreveu o sonho, e fez um registo completo do assunto.

[[v27-7-2]]

^<<v27-7-2,2>>^ Daniel declarou:
“Nas minhas visões durante a noite, vi que os quatro ventos dos céus agitavam o vasto mar.

[[v27-7-3]]

^<<v27-7-3,3>>^ E quatro animais enormes saíam do mar; eram diferentes uns dos outros.

[[v27-7-4]]

^<<v27-7-4,4>>^ “O primeiro era parecido com um leão e tinha asas de águia. Observei-o até que as asas lhe foram arrancadas, e ele foi levantado da terra e posto sobre dois pés como um homem, e recebeu um coração de homem.

[[v27-7-5]]

^<<v27-7-5,5>>^ “E apareceu outro animal, um segundo, parecido com um urso. Erguia-se sobre um dos lados e tinha na boca, entre os dentes, três costelas; e foi-lhe dito: ‘Levanta-te, come muita carne.’

[[v27-7-6]]

^<<v27-7-6,6>>^ “Depois disso, continuei a observar, e apareceu outro animal, parecido com um leopardo, mas, nas costas, ele tinha quatro asas, como as de uma ave. O animal tinha quatro cabeças; e ele recebeu autoridade para governar.

[[v27-7-7]]

^<<v27-7-7,7>>^ “Depois disso, nas visões da noite, continuei a observar, e vi um quarto animal, assustador, medonho e extremamente forte, e ele tinha grandes dentes de ferro. Devorava, triturava e, o que sobrava, ele espezinhava. Era diferente de todos os outros animais que o antecederam, e tinha dez chifres.

[[v27-7-8]]

^<<v27-7-8,8>>^ Enquanto eu observava os chifres com atenção, entre eles, surgiu outro chifre, pequeno, diante do qual três dos primeiros chifres foram arrancados. E vi que, neste chifre, havia olhos que pareciam olhos humanos e uma boca que falava de modo arrogante.^&#42;1^

[NOTE]
====
. Ou: “orgulhoso”.
====

[[v27-7-9]]

^<<v27-7-9,9>>^ “Continuei a observar até que foram colocados tronos, e o Antigo de Dias sentou-se. A sua roupa era branca como a neve, e os seus cabelos eram como a lã pura. O seu trono eram chamas de fogo, e as rodas do trono eram fogo ardente.

[[v27-7-10]]

^<<v27-7-10,10>>^ Um rio de fogo corria, saindo de diante dele. Mil vezes mil serviam-no,^&#42;1^ e dez mil vezes dez mil estavam de pé diante dele. O Tribunal iniciou a sessão, e abriram-se livros.

[NOTE]
====
. Ou: “ministravam-lhe”.
====

[[v27-7-11]]

^<<v27-7-11,11>>^ “Então, continuei a observar, por causa do som das palavras arrogantes^&#42;1^ ditas pelo chifre; observei, até que o animal foi morto e o seu corpo foi destruído e entregue para ser queimado no fogo.

[NOTE]
====
. Ou: “orgulhosas”.
====

[[v27-7-12]]

^<<v27-7-12,12>>^ Quanto aos outros animais, foi-lhes tirado o domínio, e a sua vida foi prolongada por um tempo e uma época.

[[v27-7-13]]

^<<v27-7-13,13>>^ “Continuei a observar nas visões da noite e vi alguém parecido com um filho de homem que vinha com as nuvens dos céus; ele obteve acesso ao Antigo de Dias e foi conduzido à sua presença.

[[v27-7-14]]

^<<v27-7-14,14>>^ E foi-lhe dado domínio, honra e um reino, para que os povos, nações e línguas o servissem. O seu domínio é um domínio eterno, que jamais terminará, e o seu reino não será destruído.

[[v27-7-15]]

^<<v27-7-15,15>>^ “Quanto a mim, Daniel, o meu espírito ficou aflito dentro de mim, porque as visões que me passaram pela mente amedrontaram-me.

[[v27-7-16]]

^<<v27-7-16,16>>^ Aproximei-me de um dos que ali estavam de pé, para perguntar o que aquilo realmente significava. De seguida, ele respondeu e revelou-me a interpretação daquelas coisas:

[[v27-7-17]]

^<<v27-7-17,17>>^ “‘Estes animais enormes, quatro ao todo, são quatro reis que se erguerão da terra.

[[v27-7-18]]

^<<v27-7-18,18>>^ No entanto, os santos do Supremo receberão o reino, e eles possuirão o reino para sempre, sim, para todo o sempre.’

[[v27-7-19]]

^<<v27-7-19,19>>^ “Então, eu quis saber mais sobre o quarto animal, que era diferente de todos os outros. Ele era extremamente assustador, tinha dentes de ferro e garras de cobre; ele devorava, triturava e, o que sobrava, ele espezinhava.

[[v27-7-20]]

^<<v27-7-20,20>>^ Também quis saber mais sobre os dez chifres que havia na sua cabeça e sobre o outro chifre que surgiu, diante do qual caíram três, o chifre que tinha olhos e uma boca que falava de modo arrogante,^&#42;1^ e que parecia ser maior do que os outros.

[NOTE]
====
. Ou: “orgulhoso”.
====

[[v27-7-21]]

^<<v27-7-21,21>>^ “Continuei a observar enquanto este chifre guerreava contra os santos e os vencia,

[[v27-7-22]]

^<<v27-7-22,22>>^ até que veio o Antigo de Dias, e proferiu-se o julgamento a favor dos santos do Supremo, e chegou o tempo determinado para os santos tomarem posse do reino.

[[v27-7-23]]

^<<v27-7-23,23>>^ “Ele disse o seguinte: ‘Quanto ao quarto animal, representa um quarto reino que haverá na terra. Ele será diferente de todos os outros reinos; irá devorar toda a terra e espezinhá-la e triturá-la.

[[v27-7-24]]

^<<v27-7-24,24>>^ Quanto aos dez chifres, surgirão dez reis daquele reino; e, depois deles, surgirá ainda outro, que será diferente dos primeiros e humilhará três reis.

[[v27-7-25]]

^<<v27-7-25,25>>^ Ele dirá palavras contra o Altíssimo e hostilizará continuamente os santos do Supremo. Tentará mudar tempos e lei, e eles serão entregues nas suas mãos por um tempo, tempos e metade de um tempo.^&#42;1^

[NOTE]
====
. Isto é, três tempos e meio.
====

[[v27-7-26]]

^<<v27-7-26,26>>^ Contudo, o Tribunal iniciou a sessão, e tiraram-lhe o seu domínio, a fim de aniquilá-lo e destruí-lo completamente.

[[v27-7-27]]

^<<v27-7-27,27>>^ “‘E o reino, o domínio e a grandeza dos reinos debaixo de todos os céus foram entregues ao povo que são os santos do Supremo. O reino deles é um reino eterno, e todos os domínios hão de servi-los e obedecer-lhes.’

[[v27-7-28]]

^<<v27-7-28,28>>^ “Aqui termina o assunto. Quanto a mim, Daniel, os meus pensamentos deixaram-me tão perplexo que fiquei pálido.^&#42;1^ Porém, guardei estas coisas no coração.”

[NOTE]
====
. Ou: “a minha aparência mudou”.
====

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]