include::./index.adoc[]

[[v27-3-0]]
=== Daniel, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-3-1]]

^<<v27-3-1,1>>^ O rei Nabucodonosor fez uma imagem^&#42;1^ de ouro, de 60 côvados^&#42;2^ de altura e seis côvados^&#42;3^ de largura. Erigiu-a na planície de Dura, na província^&#42;4^ de Babilónia.

[NOTE]
====
. Ou: “estátua”.
. Cerca de 27 m. Veja o Ap. B14.
. Cerca de 2,7 m. Veja o Ap. B14.
. Ou: “no distrito jurisdicional”.
====

[[v27-3-2]]

^<<v27-3-2,2>>^ Depois, o rei Nabucodonosor mandou reunir os sátrapas, os superintendentes, os governadores, os conselheiros, os tesoureiros, os juízes, os magistrados e todos os administradores das províncias, para a inauguração da imagem erigida pelo rei Nabucodonosor.

[[v27-3-3]]

^<<v27-3-3,3>>^ Então, os sátrapas, os superintendentes, os governadores, os conselheiros, os tesoureiros, os juízes, os magistrados e todos os administradores das províncias reuniram-se para a inauguração da imagem erigida pelo rei Nabucodonosor, e permaneceram de pé diante da imagem erigida por Nabucodonosor.

[[v27-3-4]]

^<<v27-3-4,4>>^ O arauto proclamou em voz alta: “Povos, nações e línguas, ordena-se

[[v27-3-5]]

^<<v27-3-5,5>>^ que, quando ouvirem o som da buzina, da flauta, da cítara, da harpa triangular, do instrumento de cordas, da gaita de foles e de todos os outros instrumentos musicais, todos se prostrem e adorem a imagem de ouro que o rei Nabucodonosor erigiu.

[[v27-3-6]]

^<<v27-3-6,6>>^ Quem não se prostrar e não adorar será imediatamente lançado na fornalha ardente.”

[[v27-3-7]]

^<<v27-3-7,7>>^ Assim, quando ouviram o som da buzina, da flauta, da cítara, da harpa triangular, do instrumento de cordas e de todos os outros instrumentos musicais, todos os povos, nações e línguas prostraram-se e adoraram a imagem de ouro que o rei Nabucodonosor tinha erigido.

[[v27-3-8]]

^<<v27-3-8,8>>^ Nesse momento, alguns caldeus apresentaram-se e acusaram^&#42;1^ os judeus.

[NOTE]
====
. Ou: “caluniaram”.
====

[[v27-3-9]]

^<<v27-3-9,9>>^ Eles disseram ao rei Nabucodonosor: “Ó rei, viva para sempre!

[[v27-3-10]]

^<<v27-3-10,10>>^ O senhor deu a ordem, ó rei, de que todo o homem que ouvisse o som da buzina, da flauta, da cítara, da harpa triangular, do instrumento de cordas, da gaita de foles e de todos os outros instrumentos musicais teria de se prostrar e adorar a imagem de ouro;

[[v27-3-11]]

^<<v27-3-11,11>>^ e de que aquele que não se prostrasse e não adorasse fosse lançado na fornalha ardente.

[[v27-3-12]]

^<<v27-3-12,12>>^ No entanto, há alguns judeus, que o senhor encarregou da administração da província de Babilónia, que não fizeram caso do senhor, ó rei: Sadraque, Mesaque e Abednego. Esses homens não servem os deuses do senhor e recusam-se a adorar a imagem de ouro que erigiu.”

[[v27-3-13]]

^<<v27-3-13,13>>^ Então, Nabucodonosor, muito furioso, mandou trazer Sadraque, Mesaque e Abednego. E estes homens foram levados perante o rei.

[[v27-3-14]]

^<<v27-3-14,14>>^ Nabucodonosor disse-lhes: “Sadraque, Mesaque e Abednego, é verdade que vocês não servem os meus deuses e que se recusam a adorar a imagem de ouro que erigi?

[[v27-3-15]]

^<<v27-3-15,15>>^ Se, agora, ao ouvirem o som da buzina, da flauta, da cítara, da harpa triangular, do instrumento de cordas, da gaita de foles e de todos os outros instrumentos musicais, vocês se dispuserem a prostrar-se e a adorar a imagem que fiz, muito bem. Mas, caso se recusem a adorá-la, serão imediatamente lançados na fornalha ardente. Que deus é que vos pode salvar das minhas mãos?”

[[v27-3-16]]

^<<v27-3-16,16>>^ Sadraque, Mesaque e Abednego responderam ao rei: “Ó Nabucodonosor, não temos necessidade nenhuma de lhe dar uma resposta a este respeito.

[[v27-3-17]]

^<<v27-3-17,17>>^ Se tiver de ser assim, o nosso Deus, a quem servimos, pode salvar-nos da fornalha ardente e pode salvar-nos da sua mão, ó rei.

[[v27-3-18]]

^<<v27-3-18,18>>^ Mas, mesmo que ele não o faça, saiba, ó rei, que nós não serviremos os seus deuses nem adoraremos a imagem de ouro que erigiu.”

[[v27-3-19]]

^<<v27-3-19,19>>^ Por conseguinte, Nabucodonosor ficou tão furioso com Sadraque, Mesaque e Abednego que a expressão do seu rosto mudou^&#42;1^ em relação a eles, e ele ordenou que se aquecesse a fornalha sete vezes mais do que o normal.

[NOTE]
====
. Ou: “que a sua atitude mudou completamente”.
====

[[v27-3-20]]

^<<v27-3-20,20>>^ Depois disso, mandou que alguns homens valentes do seu exército amarrassem Sadraque, Mesaque e Abednego e os lançassem na fornalha ardente.

[[v27-3-21]]

^<<v27-3-21,21>>^ Desse modo, estes homens foram amarrados, ainda vestidos com os seus mantos, túnicas, turbantes e todas as outras roupas, e foram lançados na fornalha ardente.

[[v27-3-22]]

^<<v27-3-22,22>>^ Como a ordem do rei tinha sido muito severa e a fornalha estava extraordinariamente quente, os homens que levaram Sadraque, Mesaque e Abednego foram os que morreram por causa das chamas da fornalha.

[[v27-3-23]]

^<<v27-3-23,23>>^ Contudo, os três homens, Sadraque, Mesaque e Abednego, caíram amarrados dentro da fornalha ardente.

[[v27-3-24]]

^<<v27-3-24,24>>^ Então, o rei Nabucodonosor, com medo, levantou-se rapidamente e perguntou aos seus altos funcionários: “Não foram três os homens que amarrámos e lançámos no fogo?” Eles responderam ao rei: “Sim, ó rei.”

[[v27-3-25]]

^<<v27-3-25,25>>^ Ele disse: “Olhem! Estou a ver quatro homens a andar livremente no meio do fogo, e eles não sofrem qualquer dano, e o quarto homem parece um filho dos deuses.”

[[v27-3-26]]

^<<v27-3-26,26>>^ Nabucodonosor aproximou-se da porta da fornalha ardente e disse: “Sadraque, Mesaque e Abednego, servos do Deus Altíssimo, saiam e venham cá!” E Sadraque, Mesaque e Abednego saíram do meio do fogo.

[[v27-3-27]]

^<<v27-3-27,27>>^ Os sátrapas, os superintendentes, os governadores e os altos funcionários do rei que estavam ali reunidos viram que o fogo não tivera nenhum efeito no^&#42;1^ corpo daqueles homens. Nem um fio do seu cabelo tinha sido chamuscado, os seus mantos estavam intactos, e nem sequer cheiravam a fumo.

[NOTE]
====
. Ou: “nenhum poder sobre o”.
====

[[v27-3-28]]

^<<v27-3-28,28>>^ De seguida, Nabucodonosor declarou: “Louvado seja o Deus de Sadraque, Mesaque e Abednego, que enviou o seu anjo e salvou os seus servos. Eles confiaram nele e não obedeceram à ordem do rei, e estavam dispostos a morrer^&#42;1^ em vez de servir e adorar qualquer outro deus que não fosse o seu próprio Deus.

[NOTE]
====
. Ou: “e entregaram os seus corpos”.
====

[[v27-3-29]]

^<<v27-3-29,29>>^ Por isso, dou a ordem de que qualquer pessoa, seja qual for o seu povo, nação ou língua, que diga alguma coisa contra o Deus de Sadraque, Mesaque e Abednego seja cortada em pedaços, e que a sua casa seja transformada numa latrina pública;^&#42;1^ pois não há outro deus que possa salvar como este.”

[NOTE]
====
. Ou, possivelmente: “depósito de lixo; monte de esterco”.
====

[[v27-3-30]]

^<<v27-3-30,30>>^ Depois disso, o rei promoveu^&#42;1^ Sadraque, Mesaque e Abednego na província de Babilónia.

[NOTE]
====
. Lit.: “fez prosperar”.
====

'''

xref:027-daniel/027-daniel-002.adoc#v27-2-0[&#60; Capítulo Anterior] | <<v27-3-0,Topo>> | xref:027-daniel/027-daniel-004.adoc#v27-4-0[Próximo Capítulo &#62;]