include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-10-1]]

^<<v27-10-1,1>>^ No terceiro ano de Ciro, rei da Pérsia, Daniel, que era chamado Beltessazar, recebeu uma revelação. A mensagem era verdadeira; era sobre um grande conflito. Ele entendeu a mensagem e recebeu compreensão daquilo que viu.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naqueles dias, eu, Daniel, estive de luto por três semanas inteiras.

[[v27-10-3]]

^<<v27-10-3,3>>^ Não comi comida saborosa, não entrou nem carne nem vinho na minha boca e não apliquei óleo no meu corpo por três semanas inteiras.

[[v27-10-4]]

^<<v27-10-4,4>>^ No dia 24 do primeiro mês, enquanto eu estava na margem do grande rio, o Tigre,^&#42;1^

[NOTE]
====
. Lit.: “Hídequel”.
====

[[v27-10-5]]

^<<v27-10-5,5>>^ levantei os olhos e vi um homem vestido de linho, e ele tinha um cinto de ouro de Ufaz na cintura.

[[v27-10-6]]

^<<v27-10-6,6>>^ O seu corpo era como crisólito, o seu rosto parecia um relâmpago, os seus olhos eram como tochas acesas, os seus braços e os seus pés pareciam cobre polido, e o som das suas palavras era como o som de uma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ Eu, Daniel, fui o único que teve a visão; os homens que estavam comigo não a viram. No entanto, eles começaram a tremer muito, e fugiram para se esconderem.

[[v27-10-8]]

^<<v27-10-8,8>>^ Então, fiquei sozinho e, quando tive esta grande visão, não me restou energia; a minha aparência ficou deplorável,^&#42;1^ e eu perdi totalmente as forças.

[NOTE]
====
. Ou: “a minha aparência digna deixou-me”.
====

[[v27-10-9]]

^<<v27-10-9,9>>^ E ouvi o som das suas palavras; mas, quando eu o ouvi falar, caí num sono profundo, com o rosto por terra.

[[v27-10-10]]

^<<v27-10-10,10>>^ De seguida, houve uma mão que me tocou; sacudiu-me e fez-me ficar de joelhos, apoiado sobre as minhas mãos.

[[v27-10-11]]

^<<v27-10-11,11>>^ E ele disse-me:
“Ó Daniel, homem muito precioso,^&#42;1^ dá atenção às palavras que te vou dizer. Agora, levanta-te, pois fui enviado até ti.”
Quando ele me disse isto, levantei-me, a tremer.

[NOTE]
====
. Ou: “muito desejável; muito estimado”.
====

[[v27-10-12]]

^<<v27-10-12,12>>^ Ele disse-me então: “Não tenhas medo, Daniel. As tuas palavras foram ouvidas desde o primeiro dia em que te dedicaste a procurar o entendimento e a humilhares-te perante o teu Deus, e eu vim por causa das tuas palavras.

[[v27-10-13]]

^<<v27-10-13,13>>^ No entanto, o príncipe do reino da Pérsia opôs-se a mim por 21 dias. Então, Miguel,^&#42;1^ um dos príncipes mais importantes,^&#42;2^ veio ajudar-me; e eu permaneci ali com os reis da Pérsia.

[NOTE]
====
. Que significa “Quem é semelhante a Deus?”
. Ou: “um príncipe de primeira categoria”.
====

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora, vim para te fazer entender o que acontecerá ao teu povo na parte final dos dias, porque é uma visão para os dias que ainda virão.”

[[v27-10-15]]

^<<v27-10-15,15>>^ Enquanto ele me dizia estas palavras, virei o rosto para o chão e fiquei sem fala.

[[v27-10-16]]

^<<v27-10-16,16>>^ De seguida, alguém com a aparência de um homem tocou-me nos lábios, de modo que abri a boca e disse àquele que estava de pé à minha frente: “Meu senhor, estou a tremer por causa da visão e já não tenho forças.

[[v27-10-17]]

^<<v27-10-17,17>>^ Portanto, como é que eu, seu servo, posso falar consigo? Pois, agora, estou sem forças e completamente sem fôlego.”

[[v27-10-18]]

^<<v27-10-18,18>>^ Aquele que tinha a aparência de um homem voltou a tocar-me e fortaleceu-me.

[[v27-10-19]]

^<<v27-10-19,19>>^ Então, disse-me: “Não tenhas medo, ó homem muito precioso.^&#42;1^ Que a paz esteja contigo. Sê forte, sim, sê forte!” Quando ele falou comigo, senti-me mais forte e disse: “Que o meu senhor fale, uma vez que me fortaleceu.”

[NOTE]
====
. Ou: “muito desejável; muito estimado”.
====

[[v27-10-20]]

^<<v27-10-20,20>>^ Portanto, ele disse: “Sabes porque é que vim ao teu encontro? Agora, voltarei para lutar com o príncipe da Pérsia. Quando eu partir, chegará o príncipe da Grécia.

[[v27-10-21]]

^<<v27-10-21,21>>^ No entanto, vou dizer-te as coisas registadas no livro da verdade. Não há ninguém que me dê um forte apoio em tudo isto, a não ser Miguel, o vosso príncipe.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]