include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v27-5-1]]

^<<v27-5-1,1>>^ O rei Belsazar deu um grande banquete a mil dos seus nobres, e bebia vinho à frente deles.

[[v27-5-2]]

^<<v27-5-2,2>>^ Sob o efeito do vinho, Belsazar mandou trazer as taças de ouro e de prata que o seu pai, Nabucodonosor, tinha tirado do templo em Jerusalém, para que o rei, os seus nobres, as suas concubinas e as suas esposas secundárias bebessem nelas.

[[v27-5-3]]

^<<v27-5-3,3>>^ Então, trouxeram as taças de ouro que tinham sido tiradas do templo da casa de Deus em Jerusalém, e o rei, os seus nobres, as suas concubinas e as suas esposas secundárias beberam nelas.

[[v27-5-4]]

^<<v27-5-4,4>>^ Beberam vinho e louvaram os deuses de ouro e de prata, e os de cobre, de ferro, de madeira e de pedra.

[[v27-5-5]]

^<<v27-5-5,5>>^ Nesse mesmo instante, apareceram dedos de uma mão humana e começaram a escrever no reboco da parede, no palácio do rei, em frente ao candelabro. E o rei conseguia ver a mão^&#42;1^ a escrever.

[NOTE]
====
. Ou: “as costas da mão”.
====

[[v27-5-6]]

^<<v27-5-6,6>>^ Nisto, o rei ficou pálido^&#42;1^ e os seus pensamentos apavoraram-no; as suas ancas tremiam e os seus joelhos batiam um no outro.

[NOTE]
====
. Ou: “a aparência do rei mudou”.
====

[[v27-5-7]]

^<<v27-5-7,7>>^ O rei, aos gritos, mandou convocar os adivinhos,^&#42;1^ os caldeus^&#42;2^ e os astrólogos. O rei disse aos sábios de Babilónia: “Qualquer homem que leia esta escrita e que me dê a sua interpretação será vestido de púrpura, com um colar de ouro ao pescoço, e governará como o terceiro no reino.”

[NOTE]
====
. Ou: “encantadores”.
. Isto é, uma seita de pessoas que se consideravam peritas em adivinhação e astrologia.
====

[[v27-5-8]]

^<<v27-5-8,8>>^ Vieram, então, todos os sábios do rei, mas não foram capazes de ler a escrita nem de revelar a sua interpretação ao rei.

[[v27-5-9]]

^<<v27-5-9,9>>^ Por isso, o rei Belsazar ficou muito amedrontado e o seu rosto ficou pálido. Os seus nobres ficaram perplexos.

[[v27-5-10]]

^<<v27-5-10,10>>^ Em vista das palavras do rei e dos seus nobres, a rainha entrou na sala do banquete. A rainha disse: “Ó rei, viva para sempre! Não permita que os seus pensamentos o apavorem, nem fique pálido.

[[v27-5-11]]

^<<v27-5-11,11>>^ No seu reino, existe um homem^&#42;1^ que tem o espírito de deuses santos. Nos dias do seu pai, acharam-se nele esclarecimento, entendimento^&#42;2^ e sabedoria como a sabedoria de deuses. O rei Nabucodonosor, seu pai, designou-o como chefe dos sacerdotes-magos, dos adivinhos, dos caldeus e dos astrólogos; foi o seu pai que o fez, ó rei.

[NOTE]
====
. Ou: “um homem capaz”.
. Ou: “perspicácia”.
====

[[v27-5-12]]

^<<v27-5-12,12>>^ Pois Daniel, a quem o rei deu o nome de Beltessazar, tinha um espírito extraordinário, conhecimento e entendimento^&#42;1^ para interpretar sonhos, solucionar enigmas e resolver problemas difíceis.^&#42;2^ Agora, que Daniel seja convocado, e ele há de dar-lhe a interpretação.”

[NOTE]
====
. Ou: “perspicácia”.
. Lit.: “desatar nós”.
====

[[v27-5-13]]

^<<v27-5-13,13>>^ Assim, trouxeram Daniel à presença do rei. O rei perguntou a Daniel: “Tu é que és Daniel, dos exilados de Judá, que o meu pai, o rei, trouxe de Judá?

[[v27-5-14]]

^<<v27-5-14,14>>^ Ouvi dizer que o espírito de deuses está em ti e que em ti se acharam esclarecimento, entendimento^&#42;1^ e sabedoria extraordinária.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v27-5-15]]

^<<v27-5-15,15>>^ Os sábios e os adivinhos foram trazidos à minha presença para ler esta escrita e revelar-me a sua interpretação, mas não são capazes de dar a interpretação da mensagem.

[[v27-5-16]]

^<<v27-5-16,16>>^ No entanto, ouvi dizer que és capaz de fornecer interpretações e resolver problemas difíceis.^&#42;1^ Portanto, se conseguires ler a escrita e me revelares a sua interpretação, serás vestido de púrpura, com um colar de ouro ao pescoço, e governarás como o terceiro no reino.”

[NOTE]
====
. Lit.: “desatar nós”.
====

[[v27-5-17]]

^<<v27-5-17,17>>^ Daniel respondeu ao rei: “O senhor pode ficar com os seus presentes e dar as recompensas a outros. No entanto, vou ler a escrita ao rei e revelar-lhe a sua interpretação.

[[v27-5-18]]

^<<v27-5-18,18>>^ Ó rei, o Deus Altíssimo concedeu a Nabucodonosor, seu pai, o reino, a grandeza, a honra e a majestade.

[[v27-5-19]]

^<<v27-5-19,19>>^ Por causa da grandeza que Ele lhe deu, todos os povos, nações e línguas tremiam de medo diante dele. Ele matava ou deixava viver quem quisesse, enaltecia ou humilhava quem quisesse.

[[v27-5-20]]

^<<v27-5-20,20>>^ Porém, quando o seu coração ficou arrogante e o seu espírito se endureceu, de modo a ele agir presunçosamente, foi derrubado do trono do seu reino, e foi-lhe tirada a dignidade.

[[v27-5-21]]

^<<v27-5-21,21>>^ Ele foi expulso do meio da humanidade, o seu coração foi tornado semelhante ao de um animal, e ele morava com os jumentos selvagens. Recebia vegetação para comer, como os touros, e o seu corpo ficou molhado com o orvalho dos céus, até que reconheceu que o Altíssimo é Governante no reino da humanidade, sobre o qual ele estabelece quem quiser.

[[v27-5-22]]

^<<v27-5-22,22>>^ “Mas o senhor não humilhou o seu coração, ó Belsazar, filho de Nabucodonosor, embora soubesse tudo isto.

[[v27-5-23]]

^<<v27-5-23,23>>^ Pelo contrário, enalteceu-se em desafio ao Senhor dos céus, e ordenou que lhe trouxessem as taças da sua casa. Depois, o senhor, os seus nobres, as suas concubinas e as suas esposas secundárias beberam vinho nelas, e louvaram os deuses de prata e ouro, de cobre, de ferro, de madeira e de pedra, deuses que não veem, não ouvem nem sabem nada. Contudo, o senhor não glorificou o Deus em cujas mãos está o seu fôlego e todos os seus caminhos.

[[v27-5-24]]

^<<v27-5-24,24>>^ Por isso, a mão foi enviada por ele, e estas palavras foram escritas.

[[v27-5-25]]

^<<v27-5-25,25>>^ E estas são as palavras que foram escritas: MENE, MENE, TEQUEL e PARSIM.

[[v27-5-26]]

^<<v27-5-26,26>>^ “Esta é a interpretação das palavras: MENE: Deus contou os dias do seu reino e fê-lo chegar ao fim.

[[v27-5-27]]

^<<v27-5-27,27>>^ “TEQUEL: o senhor foi pesado na balança e considerado insuficiente.

[[v27-5-28]]

^<<v27-5-28,28>>^ “PERES: o seu reino foi dividido e dado aos medos e aos persas.”

[[v27-5-29]]

^<<v27-5-29,29>>^ Então, Belsazar deu a ordem, e vestiram Daniel de púrpura, colocaram-lhe um colar de ouro ao pescoço e proclamaram que ele se tornaria o terceiro governante no reino.

[[v27-5-30]]

^<<v27-5-30,30>>^ Naquela mesma noite, Belsazar, o rei caldeu, foi morto.

[[v27-5-31]]

^<<v27-5-31,31>>^ E Dario, o medo, recebeu o reino; ele tinha cerca de 62 anos de idade.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]