include::./index.adoc[]

[[v13-21-0]]
=== 1 Crónicas, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-21-1]]

^<<v13-21-1,1>>^ Então, Satanás^&#42;1^ levantou-se contra Israel e instigou David a recensear Israel.

[NOTE]
====
. Ou, possivelmente: “um opositor”.
====

[[v13-21-2]]

^<<v13-21-2,2>>^ Portanto, David disse a Joabe e aos chefes do povo: “Vão, contem Israel desde Berseba até Dã, e tragam-me um relatório para que eu saiba quantos são.”

[[v13-21-3]]

^<<v13-21-3,3>>^ No entanto, Joabe disse: “Que Jeová multiplique cem vezes o Seu povo. Meu senhor, o rei, já não são todos eles servos do meu senhor? Porque é que o meu senhor quer fazer isto? Por que trazer culpa sobre Israel?”

[[v13-21-4]]

^<<v13-21-4,4>>^ Contudo, a palavra do rei prevaleceu sobre a de Joabe. Portanto, Joabe foi e percorreu Israel, e depois voltou para Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ Por conseguinte, Joabe entregou a David o número dos que foram registados. Todo o Israel tinha 1 100 000 homens armados com espadas, e em Judá havia 470 000 homens armados com espadas.

[[v13-21-6]]

^<<v13-21-6,6>>^ No entanto, as tribos de Levi e de Benjamim não foram incluídas no recenseamento, porque a ordem do rei era detestável para Joabe.

[[v13-21-7]]

^<<v13-21-7,7>>^ Isto desagradou muito ao verdadeiro Deus, por isso ele puniu Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ David disse então ao verdadeiro Deus: “Cometi um pecado grave ao fazer isto. E agora, por favor, perdoa o pecado do teu servo, pois agi de modo muito insensato.”

[[v13-21-9]]

^<<v13-21-9,9>>^ A seguir, Jeová disse a Gade, vidente^&#42;1^ de David:

[NOTE]
====
. Veja o Glossário.
====

[[v13-21-10]]

^<<v13-21-10,10>>^ “Vai e diz a David: ‘Assim diz Jeová: “Dou-te três opções. Escolhe qual delas é que devo executar contra ti.”’”

[[v13-21-11]]

^<<v13-21-11,11>>^ Então, Gade compareceu perante David e disse-lhe: “Assim diz Jeová: ‘Escolhe o que preferes:

[[v13-21-12]]

^<<v13-21-12,12>>^ três anos de fome; três meses de derrota diante dos teus inimigos, sendo atingido pela espada deles; ou três dias de punição da parte da espada de Jeová, isto é, peste no país, com o anjo de Jeová a causar destruição em todo o território de Israel.’ Agora, pensa e diz-me que resposta devo dar Àquele que me enviou.”

[[v13-21-13]]

^<<v13-21-13,13>>^ De seguida, David disse a Gade: “Isso é muito aflitivo para mim. Que eu caia nas mãos de Jeová, pois a Sua misericórdia é muito grande, mas que eu não caia nas mãos dos homens.”

[[v13-21-14]]

^<<v13-21-14,14>>^ Portanto, Jeová enviou uma peste sobre Israel, de modo que 70 000 pessoas morreram em Israel.

[[v13-21-15]]

^<<v13-21-15,15>>^ Além disso, o verdadeiro Deus enviou um anjo para destruir Jerusalém. Contudo, quando ele estava para fazer isso, Jeová viu, lamentou a^&#42;1^ calamidade e disse ao anjo que causava a destruição: “Já chega! Abaixa a mão.” O anjo de Jeová estava perto da eira de Ornã, o jebuseu.

[NOTE]
====
. Ou: “sentiu pesar por causa da”.
====

[[v13-21-16]]

^<<v13-21-16,16>>^ Quando David levantou os olhos, viu o anjo de Jeová entre a terra e os céus, com a espada desembainhada na mão, estendida contra Jerusalém. Então, David e os anciãos, cobertos com serapilheira,^&#42;1^ lançaram-se imediatamente com o rosto por terra.

[NOTE]
====
. Veja o Glossário.
====

[[v13-21-17]]

^<<v13-21-17,17>>^ David disse ao verdadeiro Deus: “Não fui eu que mandei fazer o recenseamento do povo? Fui eu que pequei, eu é que cometi este erro. Mas o que é que estas ovelhas fizeram? Ó Jeová, meu Deus, por favor, que a tua mão venha sobre mim e sobre a casa do meu pai, mas não tragas este flagelo sobre o teu povo.”

[[v13-21-18]]

^<<v13-21-18,18>>^ Então, o anjo de Jeová mandou Gade dizer a David que subisse à eira de Ornã, o jebuseu, e construísse ali um altar a Jeová.

[[v13-21-19]]

^<<v13-21-19,19>>^ Portanto, David agiu segundo a palavra de Gade, que ele tinha falado em nome de Jeová.

[[v13-21-20]]

^<<v13-21-20,20>>^ Enquanto isso, Ornã voltou-se e viu o anjo, e os seus quatro filhos que estavam com ele esconderam-se. Ornã estava a debulhar o trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ Quando David se aproximou, Ornã viu David, saiu imediatamente da eira e curvou-se diante de David com o rosto por terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ David disse a Ornã: “Vende-me^&#42;1^ o terreno desta eira, para que eu construa nele um altar a Jeová. Vende-mo pelo seu valor total, para que cesse o flagelo sobre o povo.”

[NOTE]
====
. Lit.: “Dá-me”.
====

[[v13-21-23]]

^<<v13-21-23,23>>^ Porém, Ornã disse a David: “Fique com ele, meu senhor, o rei, e faça com ele o que quiser.^&#42;1^ Aqui estão os bois para as ofertas queimadas, o trenó de debulha para servir de lenha e o trigo para uma oferta de cereais. Dou-lhe tudo.”

[NOTE]
====
. Lit.: “o que for bom aos seus olhos”.
====

[[v13-21-24]]

^<<v13-21-24,24>>^ No entanto, o rei David disse a Ornã: “Não, de maneira nenhuma! Eu compro-te o terreno pelo seu pleno valor, pois não te tirarei o que é teu para dar a Jeová, nem oferecerei sacrifícios queimados que não me custem nada.”

[[v13-21-25]]

^<<v13-21-25,25>>^ Assim, David deu a Ornã o peso de 600 siclos^&#42;1^ de ouro pelo terreno.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v13-21-26]]

^<<v13-21-26,26>>^ David construiu ali um altar a Jeová e ofereceu sacrifícios queimados e sacrifícios de participação em comum. Invocou a Jeová, que lhe respondeu enviando fogo dos céus sobre o altar da oferta queimada.

[[v13-21-27]]

^<<v13-21-27,27>>^ A seguir, Jeová ordenou ao anjo que guardasse a espada na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Quando David viu que Jeová lhe tinha respondido na eira de Ornã, o jebuseu, continuou a oferecer sacrifícios naquele lugar.

[[v13-21-29]]

^<<v13-21-29,29>>^ No entanto, o tabernáculo de Jeová, que Moisés tinha feito no deserto, e o altar da oferta queimada estavam naquela época no alto sagrado que havia em Gibeão.

[[v13-21-30]]

^<<v13-21-30,30>>^ Contudo, David não conseguia ir até lá para consultar a Deus, porque estava apavorado por causa da espada do anjo de Jeová.

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]