include::./index.adoc[]

[[v13-14-0]]
=== 1 Crónicas, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-14-1]]

^<<v13-14-1,1>>^ Hirão, rei de Tiro, enviou mensageiros a David, com madeiras de cedro, pedreiros^&#42;1^ e carpinteiros, para lhe construir uma casa.^&#42;2^

[NOTE]
====
. Ou: “construtores de muros”.
. Ou: “um palácio”.
====

[[v13-14-2]]

^<<v13-14-2,2>>^ E David percebeu que Jeová o tinha estabelecido firmemente como rei sobre Israel, pois Ele tinha exaltado grandemente o seu reinado por causa do Seu povo Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ David tomou mais esposas em Jerusalém e tornou-se pai de mais filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ Estes são os nomes dos seus filhos que nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibar, Elisua, Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ Nogá, Nefegue, Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ Elisama, Beeliada e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ Quando os filisteus souberam que David tinha sido ungido rei sobre todo o Israel, todos eles foram à procura de David. Ao saber disso, David saiu para lutar contra eles.

[[v13-14-9]]

^<<v13-14-9,9>>^ Então, os filisteus vieram e começaram a atacar o vale^&#42;1^ de Refaim.

[NOTE]
====
. Ou: “a planície”.
====

[[v13-14-10]]

^<<v13-14-10,10>>^ David consultou a Deus: “Será que devo atacar os filisteus? Será que os vais entregar nas minhas mãos?” Jeová respondeu a David: “Vai, e eu certamente os entregarei nas tuas mãos.”

[[v13-14-11]]

^<<v13-14-11,11>>^ Portanto, David foi a Baal-Perazim e golpeou-os. Por isso, David disse: “Por meio das minhas mãos, o verdadeiro Deus rompeu as fileiras dos meus inimigos, como águas que abrem uma brecha.” Foi por isso que deram àquele lugar o nome de Baal-Perazim.^&#42;1^

[NOTE]
====
. Que significa “senhor das brechas”.
====

[[v13-14-12]]

^<<v13-14-12,12>>^ Os filisteus abandonaram ali os seus deuses, e quando David deu a ordem, foram queimados no fogo.

[[v13-14-13]]

^<<v13-14-13,13>>^ Mais tarde, os filisteus atacaram novamente o vale.^&#42;1^

[NOTE]
====
. Ou: “a planície”.
====

[[v13-14-14]]

^<<v13-14-14,14>>^ David consultou a Deus mais uma vez, mas o verdadeiro Deus disse-lhe: “Não os ataques pela frente. Dá a volta por trás deles e ataca-os em frente aos balsameiros.

[[v13-14-15]]

^<<v13-14-15,15>>^ Quando ouvires o som de marcha nas copas dos balsameiros, ataca, pois o verdadeiro Deus terá ido à tua frente para golpear o exército dos filisteus.”

[[v13-14-16]]

^<<v13-14-16,16>>^ Portanto, David fez exatamente como o verdadeiro Deus lhe ordenou, e eles golpearam o exército filisteu desde Gibeão até Gezer.

[[v13-14-17]]

^<<v13-14-17,17>>^ Assim, a fama de David espalhou-se por todas as terras, e Jeová fez com que todas as nações o temessem.

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]