include::./index.adoc[]

[[v13-17-0]]
=== 1 Crónicas, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-17-1]]

^<<v13-17-1,1>>^ Quando David já morava na sua casa,^&#42;1^ ele disse a Natã, o profeta: “Vê, moro numa casa de cedros, enquanto a Arca do Pacto de Jeová está numa tenda.”

[NOTE]
====
. Ou: “no seu palácio”.
====

[[v13-17-2]]

^<<v13-17-2,2>>^ Natã disse a David: “Faça tudo o que o seu coração desejar, pois o verdadeiro Deus está consigo.”

[[v13-17-3]]

^<<v13-17-3,3>>^ Naquela mesma noite, Natã recebeu a seguinte palavra de Deus:

[[v13-17-4]]

^<<v13-17-4,4>>^ “Vai e diz ao meu servo David: ‘Assim diz Jeová: “Não serás tu quem construirá uma casa para eu morar.

[[v13-17-5]]

^<<v13-17-5,5>>^ Eu nunca morei numa casa desde o dia em que tirei Israel do Egito até hoje, mas fui de tenda em tenda, de tabernáculo em tabernáculo.^&#42;1^

[NOTE]
====
. Que possivelmente significa “de um lugar onde a tenda era montada para outro, e de um lugar de morada para outro”.
====

[[v13-17-6]]

^<<v13-17-6,6>>^ Durante todo o tempo em que andei com todo o Israel, será que alguma vez perguntei a algum dos juízes de Israel, a quem designei para pastorear o meu povo: ‘Porque é que não me construíram uma casa de cedros?’”’

[[v13-17-7]]

^<<v13-17-7,7>>^ “Agora, diz o seguinte ao meu servo David: ‘Assim diz Jeová dos exércitos: “Tirei-te das pastagens, de trás do rebanho, para que te tornasses líder do meu povo Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ Estarei contigo por onde quer que andares e vou eliminar^&#42;1^ todos os teus inimigos de diante de ti. E farei um nome para ti, igual ao nome dos grandes homens da terra.

[NOTE]
====
. Lit.: “decepar”.
====

[[v13-17-9]]

^<<v13-17-9,9>>^ Vou designar um lugar para o meu povo Israel e estabelecê-lo lá. Eles viverão nesse lugar e não voltarão a ser perturbados; os maus não voltarão a oprimi-los^&#42;1^ como fizeram no passado,

[NOTE]
====
. Lit.: “esgotá-los”.
====

[[v13-17-10]]

^<<v13-17-10,10>>^ desde o dia em que designei juízes sobre o meu povo Israel. Vou derrotar todos os teus inimigos. Além disso, digo-te: ‘Jeová edificará uma casa^&#42;1^ para ti.’

[NOTE]
====
. Ou: “dinastia”.
====

[[v13-17-11]]

^<<v13-17-11,11>>^ “‘“Quando chegar o fim dos teus dias e te juntares aos teus antepassados, farei surgir o teu descendente,^&#42;1^ um dos teus filhos, e estabelecerei firmemente o seu reinado.

[NOTE]
====
. Lit.: “a tua semente”.
====

[[v13-17-12]]

^<<v13-17-12,12>>^ É ele quem construirá uma casa para mim, e eu estabelecerei firmemente o seu trono para sempre.

[[v13-17-13]]

^<<v13-17-13,13>>^ Eu vou tornar-me seu pai e ele vai tornar-se meu filho. Não retirarei dele o meu amor leal, assim como o retirei daquele que reinou antes de ti.

[[v13-17-14]]

^<<v13-17-14,14>>^ Vou estabelecê-lo na minha casa e no meu reinado para sempre, e o seu trono durará para sempre.”’”

[[v13-17-15]]

^<<v13-17-15,15>>^ Natã transmitiu a David todas estas palavras e toda esta visão.

[[v13-17-16]]

^<<v13-17-16,16>>^ Em vista disso, o rei David entrou e sentou-se diante de Jeová, e disse: “Quem sou eu, ó Jeová Deus? E o que é a minha casa, para que me tenhas feito chegar até aqui?

[[v13-17-17]]

^<<v13-17-17,17>>^ Como se isso não bastasse, ó Deus, também me dizes que a casa do teu servo permanecerá até um tempo distante no futuro; tu tratas-me como se eu devesse ser ainda mais enaltecido,^&#42;1^ ó Jeová Deus.

[NOTE]
====
. Ou: “eu fosse um homem nobre”.
====

[[v13-17-18]]

^<<v13-17-18,18>>^ O que é que eu, o teu servo David, te posso dizer mais sobre a honra que me dás, visto que conheces o teu servo tão bem?

[[v13-17-19]]

^<<v13-17-19,19>>^ Ó Jeová, por causa do teu servo e de acordo com o teu coração,^&#42;1^ fizeste todas estas grandes coisas por revelar a tua grandeza.

[NOTE]
====
. Ou: “em harmonia com a tua vontade”.
====

[[v13-17-20]]

^<<v13-17-20,20>>^ Ó Jeová, não há ninguém igual a ti, e não há Deus além de ti; tudo o que já ouvimos confirma isso.

[[v13-17-21]]

^<<v13-17-21,21>>^ Que outra nação na terra é como o teu povo Israel? O verdadeiro Deus resgatou-os como seu povo. Fizeste um nome para ti por realizar coisas grandes e atemorizantes, expulsando nações de diante do teu povo, que resgataste do Egito.

[[v13-17-22]]

^<<v13-17-22,22>>^ Fizeste do teu povo Israel o teu próprio povo para sempre; e tu, ó Jeová, tornaste-te o seu Deus.

[[v13-17-23]]

^<<v13-17-23,23>>^ Agora, ó Jeová, que a promessa que fizeste a respeito do teu servo e da sua casa se mostre fiel para sempre, e que o faças assim como prometeste.

[[v13-17-24]]

^<<v13-17-24,24>>^ Que o teu nome permaneça^&#42;1^ e seja enaltecido para sempre, para que as pessoas digam: ‘Jeová dos exércitos, o Deus de Israel, é Deus para Israel’, e que a casa do teu servo David seja firmemente estabelecida diante de ti.

[NOTE]
====
. Ou: “se mostre fiel”.
====

[[v13-17-25]]

^<<v13-17-25,25>>^ Pois tu, meu Deus, revelaste ao teu servo o propósito de lhe edificar uma casa.^&#42;1^ Por isso é que o teu servo se sente confiante para te fazer esta oração.

[NOTE]
====
. Ou: “dinastia”.
====

[[v13-17-26]]

^<<v13-17-26,26>>^ Ó Jeová, tu és o verdadeiro Deus e prometeste estas coisas boas a respeito do teu servo.

[[v13-17-27]]

^<<v13-17-27,27>>^ Portanto, que seja do teu agrado abençoar a casa do teu servo e que ela permaneça para sempre diante de ti, pois tu a abençoaste, ó Jeová, e ela será abençoada para sempre.”

'''

xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[Próximo Capítulo &#62;]