include::./index.adoc[]

[[v13-23-0]]
=== 1 Crónicas, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-23-1]]

^<<v13-23-1,1>>^ Quando David já era idoso e estava perto do fim da sua vida,^&#42;1^ fez de Salomão, seu filho, rei sobre Israel.

[NOTE]
====
. Lit.: “idoso e cheio de dias”.
====

[[v13-23-2]]

^<<v13-23-2,2>>^ Depois, reuniu todos os príncipes de Israel, os sacerdotes e os levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ E foi feita a contagem dos levitas de 30 anos de idade para cima; o seu número, o total da contagem um por um, foi de 38 000 homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ Destes, 24 000 serviam como supervisores da obra da casa de Jeová, 6000 eram oficiais e juízes;

[[v13-23-5]]

^<<v13-23-5,5>>^ havia 4000 porteiros, e 4000 louvavam a Jeová com os instrumentos musicais sobre os quais David disse: “Fi-los para dar louvor.”

[[v13-23-6]]

^<<v13-23-6,6>>^ Então, David organizou-os^&#42;1^ em turmas, de acordo com os filhos de Levi: Gérson, Coate e Merari.

[NOTE]
====
. Ou: “dividiu-os”.
====

[[v13-23-7]]

^<<v13-23-7,7>>^ Dos gersonitas havia Ladã e Simei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Os filhos de Ladã foram Jeiel, o cabeça, Zetão e Joel, três.

[[v13-23-9]]

^<<v13-23-9,9>>^ Os filhos de Simei foram Selomote, Haziel e Harã, três. Estes foram os cabeças das casas paternas de Ladã.

[[v13-23-10]]

^<<v13-23-10,10>>^ Os filhos de Simei foram Jaate, Zina, Jeús e Berias. Estes quatro foram os filhos de Simei.

[[v13-23-11]]

^<<v13-23-11,11>>^ Jaate era o cabeça, e Zizá o segundo. Contudo, visto que Jeús e Berias não tiveram muitos filhos, foram contados como uma única casa paterna que cuidava da mesma responsabilidade.

[[v13-23-12]]

^<<v13-23-12,12>>^ Os filhos de Coate foram Anrão, Izar, Hébron e Uziel, quatro.

[[v13-23-13]]

^<<v13-23-13,13>>^ Os filhos de Anrão foram Arão e Moisés. No entanto, Arão e os seus filhos foram permanentemente separados, a fim de santificarem o Santíssimo, oferecerem sacrifícios perante Jeová, servirem-no e proferirem bênçãos em Seu nome para sempre.

[[v13-23-14]]

^<<v13-23-14,14>>^ Quanto a Moisés, o homem do verdadeiro Deus, os seus filhos foram considerados parte da tribo dos levitas.

[[v13-23-15]]

^<<v13-23-15,15>>^ Os filhos de Moisés foram Gérson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ Dos filhos de Gérson, Sebuel era o cabeça.

[[v13-23-17]]

^<<v13-23-17,17>>^ Dos descendentes^&#42;1^ de Eliézer, Reabias era o cabeça. Eliézer não teve outros filhos, mas Reabias teve muitíssimos.

[NOTE]
====
. Lit.: “filhos”.
====

[[v13-23-18]]

^<<v13-23-18,18>>^ Dos filhos de Izar, Selomite era o cabeça.

[[v13-23-19]]

^<<v13-23-19,19>>^ Os filhos de Hébron foram Jerias, o cabeça; Amarias, o segundo; Jaaziel, o terceiro; e Jecameão, o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Os filhos de Uziel foram Mica, o cabeça; e Issias, o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Os filhos de Merari foram Mali e Musi. Os filhos de Mali foram Eleazar e Quis.

[[v13-23-22]]

^<<v13-23-22,22>>^ Eleazar morreu sem ter filhos, ele só teve filhas. Por isso, os filhos de Quis, que eram parentes^&#42;1^ delas, casaram-se com elas.

[NOTE]
====
. Lit.: “irmãos”.
====

[[v13-23-23]]

^<<v13-23-23,23>>^ Os filhos de Musi foram Mali, Éder e Jeremote, três.

[[v13-23-24]]

^<<v13-23-24,24>>^ Estes foram os filhos de Levi, de acordo com as suas casas paternas, de acordo com os cabeças das casas paternas. Eles foram registados, contados e alistados por nome, e realizavam o serviço da casa de Jeová a partir dos 20 anos de idade.

[[v13-23-25]]

^<<v13-23-25,25>>^ Pois David tinha dito: “Jeová, o Deus de Israel, deu descanso ao seu povo e residirá em Jerusalém para sempre.

[[v13-23-26]]

^<<v13-23-26,26>>^ Da mesma forma, os levitas já não terão de carregar o tabernáculo nem o seu equipamento usado na adoração.”

[[v13-23-27]]

^<<v13-23-27,27>>^ De acordo com as últimas instruções de David, os levitas de 20 anos de idade para cima foram contados.

[[v13-23-28]]

^<<v13-23-28,28>>^ A função deles era ajudar os filhos de Arão no serviço da casa de Jeová e cuidar dos pátios, dos refeitórios, da purificação de todas as coisas sagradas e de todo o serviço necessário na casa do verdadeiro Deus.

[[v13-23-29]]

^<<v13-23-29,29>>^ Ajudavam a cuidar dos pães da proposição,^&#42;1^ da farinha fina para a oferta de cereais, dos pães achatados sem fermento, dos pães feitos na assadeira, da massa misturada com azeite e de todos os pesos e medidas.

[NOTE]
====
. Ou: “pães dispostos em pilhas”.
====

[[v13-23-30]]

^<<v13-23-30,30>>^ Deviam apresentar-se todas as manhãs para agradecer e louvar a Jeová, e fazer o mesmo ao anoitecer.

[[v13-23-31]]

^<<v13-23-31,31>>^ Eles ajudavam sempre que os sacrifícios queimados eram oferecidos a Jeová nos sábados, nas luas novas e durante as épocas festivas, segundo o número que as regras exigiam, e faziam isso regularmente perante Jeová.

[[v13-23-32]]

^<<v13-23-32,32>>^ Também cuidavam das suas responsabilidades relacionadas com a tenda de reunião, com o lugar santo e com os filhos de Arão, seus irmãos, no serviço da casa de Jeová.

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]