include::./index.adoc[]

[[v13-29-0]]
=== 1 Crónicas, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-29-1]]

^<<v13-29-1,1>>^ O rei David disse então a toda a congregação: “O meu filho Salomão, a quem Deus escolheu, é jovem e inexperiente,^&#42;1^ e a obra é grande, pois o templo^&#42;2^ não é para um homem, mas para Jeová Deus.

[NOTE]
====
. Ou: “frágil”.
. Ou: “a cidadela; o palácio”.
====

[[v13-29-2]]

^<<v13-29-2,2>>^ Assim, não medi esforços em fazer preparativos para a construção da casa do meu Deus, por providenciar o ouro para os trabalhos de ouro, a prata para os trabalhos de prata, o cobre para os trabalhos de cobre, o ferro para os trabalhos de ferro, a madeira para os trabalhos de madeira, bem como pedras de ónix, pedras para incrustar com argamassa, pedrinhas de mosaico, todo o tipo de pedras preciosas, e pedras de alabastro em grande quantidade.

[[v13-29-3]]

^<<v13-29-3,3>>^ E, visto que eu amo a casa do meu Deus, além de tudo o que já providenciei para a casa santa, dou também o meu próprio tesouro de ouro e prata para a casa do meu Deus,

[[v13-29-4]]

^<<v13-29-4,4>>^ incluindo 3000 talentos^&#42;1^ de ouro de Ofir e 7000 talentos de prata refinada, para o revestimento das paredes dos diversos compartimentos,^&#42;2^

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
. Lit.: “paredes das casas”.
====

[[v13-29-5]]

^<<v13-29-5,5>>^ para os trabalhos de ouro e para os trabalhos de prata, e para todo o trabalho a ser feito pelos artesãos. E hoje, quem é que se oferece para trazer uma dádiva a Jeová?”

[[v13-29-6]]

^<<v13-29-6,6>>^ Então, os príncipes das casas paternas, os príncipes das tribos de Israel, os chefes de mil, os chefes de cem e os encarregados dos assuntos do rei apresentaram-se voluntariamente.

[[v13-29-7]]

^<<v13-29-7,7>>^ Deram para a obra da casa do verdadeiro Deus 5000 talentos de ouro, 10 000 daricos,^&#42;1^ 10 000 talentos de prata, 18 000 talentos de cobre e 100 000 talentos de ferro.

[NOTE]
====
. O darico era uma moeda persa de ouro. Veja o Ap. B14.
====

[[v13-29-8]]

^<<v13-29-8,8>>^ Quem tinha pedras preciosas deu-as para o tesouro da casa de Jeová, que estava aos cuidados de Jeiel, o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ O povo alegrou-se de fazer estas ofertas voluntárias, pois faziam as ofertas voluntárias a Jeová de pleno coração. O rei David também se alegrou muito.

[[v13-29-10]]

^<<v13-29-10,10>>^ Depois, David louvou a Jeová diante de toda a congregação. Ele disse: “Que sejas louvado, ó Jeová, Deus de Israel, nosso pai, por toda a eternidade.^&#42;1^

[NOTE]
====
. Ou: “de eternidade a eternidade”.
====

[[v13-29-11]]

^<<v13-29-11,11>>^ Teus, ó Jeová, são a grandeza, o poder, a glória, o esplendor e a majestade;^&#42;1^ pois tudo o que há nos céus e na terra te pertence. Teu é o reino, ó Jeová. Tu elevas-te como cabeça acima de todos.

[NOTE]
====
. Ou: “dignidade”.
====

[[v13-29-12]]

^<<v13-29-12,12>>^ As riquezas e a glória vêm de ti, e tu dominas sobre tudo. Nas tuas mãos há força e poder, e nas tuas mãos há a capacidade para engrandecer e para dar força a todos.

[[v13-29-13]]

^<<v13-29-13,13>>^ E agora, ó nosso Deus, agradecemos-te e louvamos o teu belo nome.

[[v13-29-14]]

^<<v13-29-14,14>>^ “No entanto, quem sou eu, e quem é o meu povo, para que façamos estas ofertas voluntárias? Pois tudo vem de ti, e nós apenas te demos o que vem das tuas mãos.

[[v13-29-15]]

^<<v13-29-15,15>>^ Diante de ti somos residentes estrangeiros e colonos, assim como todos os nossos antepassados. Pois os nossos dias sobre a terra são como uma sombra — sem esperança.

[[v13-29-16]]

^<<v13-29-16,16>>^ Ó Jeová, nosso Deus, toda esta riqueza que juntámos para construir uma casa para o teu santo nome vem das tuas próprias mãos, e tudo te pertence.

[[v13-29-17]]

^<<v13-29-17,17>>^ Eu bem sei, ó meu Deus, que tu examinas o coração e te agradas da integridade.^&#42;1^ Na sinceridade^&#42;2^ do meu coração, ofereci voluntariamente todas estas coisas, e alegro-me muito de ver o teu povo aqui presente a fazer-te ofertas voluntárias.

[NOTE]
====
. Ou: “retidão”.
. Ou: “retidão”.
====

[[v13-29-18]]

^<<v13-29-18,18>>^ Ó Jeová, Deus de Abraão, de Isaque e de Israel, nossos antepassados, conserva para sempre no coração do teu povo esta disposição e pensamento, e dirige o seu coração para ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ E dá a Salomão, meu filho, um coração pleno,^&#42;1^ para que ele obedeça aos teus mandamentos, às tuas advertências^&#42;2^ e aos teus decretos; para que ele faça tudo isso e construa o templo^&#42;3^ para o qual fiz preparativos.”

[NOTE]
====
. Ou: “plenamente devotado”.
. Ou: “aos teus lembretes”.
. Ou: “a cidadela; o palácio”.
====

[[v13-29-20]]

^<<v13-29-20,20>>^ Em seguida, David disse a toda a congregação: “Agora louvem a Jeová, vosso Deus.” E toda a congregação louvou a Jeová, o Deus dos seus antepassados, curvou-se e prostrou-se diante de Jeová e diante do rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ E no dia seguinte ofereceram sacrifícios a Jeová e fizeram ofertas queimadas a Jeová: mil novilhos, mil carneiros, mil cordeiros e as correspondentes ofertas de bebida. Fizeram sacrifícios em grande quantidade para todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ Naquele dia, eles comeram e beberam diante de Jeová com grande alegria. E pela segunda vez proclamaram rei a Salomão, filho de David. Ungiram-no perante Jeová como líder, e também ungiram Zadoque como sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ E Salomão sentou-se no trono de Jeová como rei no lugar de David, seu pai. Ele foi bem-sucedido e todos os israelitas lhe obedeciam.

[[v13-29-24]]

^<<v13-29-24,24>>^ Todos os príncipes, os guerreiros valentes e também todos os filhos do rei David se sujeitaram ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ Jeová engrandeceu Salomão de maneira extraordinária perante todo o Israel e deu-lhe uma majestade real tal como nenhum rei de Israel teve antes dele.

[[v13-29-26]]

^<<v13-29-26,26>>^ Assim, David, filho de Jessé, reinou sobre todo o Israel,

[[v13-29-27]]

^<<v13-29-27,27>>^ e a duração^&#42;1^ do seu reinado sobre Israel foi de 40 anos. Em Hébron, ele reinou durante 7 anos, e em Jerusalém reinou durante 33 anos.

[NOTE]
====
. Lit.: “os dias”.
====

[[v13-29-28]]

^<<v13-29-28,28>>^ E morreu numa boa velhice, satisfeito por ter tido uma vida longa,^&#42;1^ riquezas e glória; e Salomão, seu filho, tornou-se rei no seu lugar.

[NOTE]
====
. Lit.: “saciado de dias”.
====

[[v13-29-29]]

^<<v13-29-29,29>>^ A história do rei David, do início ao fim, está registada nos escritos de Samuel, o vidente,^&#42;1^ de Natã, o profeta, e de Gade, o vidente.^&#42;2^

[NOTE]
====
. Veja o Glossário.
. Veja o Glossário.
====

[[v13-29-30]]

^<<v13-29-30,30>>^ Estes escritos falam sobre todo o seu reinado, o seu poder e as coisas que na sua época lhe aconteceram a ele, a Israel e a todos os reinos ao redor.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]