include::./index.adoc[]

[[v13-18-0]]
=== 1 Crónicas, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-18-1]]

^<<v13-18-1,1>>^ Algum tempo depois, David derrotou os filisteus e subjugou-os, e tomou Gate e as suas aldeias dependentes^&#42;1^ das mãos dos filisteus.

[NOTE]
====
. Ou: “ao redor”.
====

[[v13-18-2]]

^<<v13-18-2,2>>^ Em seguida, derrotou Moabe, e os moabitas tornaram-se servos de David e passaram a pagar-lhe tributo.

[[v13-18-3]]

^<<v13-18-3,3>>^ David derrotou Hadadezer, rei de Zobá, perto de Hamate, quando este ia estabelecer o seu domínio sobre a região do rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ David capturou 1000 carros de Hadadezer, 7000 cavaleiros e 20 000 soldados a pé. Então, David cortou os tendões de todos os cavalos dos carros de guerra, à exceção de 100 deles.

[[v13-18-5]]

^<<v13-18-5,5>>^ Quando os sírios de Damasco vieram ajudar Hadadezer, rei de Zobá, David matou 22 000 sírios.

[[v13-18-6]]

^<<v13-18-6,6>>^ Por conseguinte, David manteve tropas na Síria de Damasco; e os sírios tornaram-se servos de David e passaram a pagar-lhe tributo. Jeová dava vitórias^&#42;1^ a David onde quer que ele fosse.

[NOTE]
====
. Ou: “salvação”.
====

[[v13-18-7]]

^<<v13-18-7,7>>^ Além disso, David pegou nos escudos^&#42;1^ de ouro dos servos de Hadadezer e trouxe-os para Jerusalém.

[NOTE]
====
. Ou: “escudos redondos”.
====

[[v13-18-8]]

^<<v13-18-8,8>>^ David trouxe também uma grande quantidade de cobre de Tibate e de Cum, cidades de Hadadezer. Salomão usou esse cobre para fazer o Mar de cobre, as colunas e os utensílios de cobre.

[[v13-18-9]]

^<<v13-18-9,9>>^ Quando Toú, rei de Hamate, soube que David tinha derrotado todo o exército de Hadadezer, rei de Zobá,

[[v13-18-10]]

^<<v13-18-10,10>>^ enviou imediatamente Hadorão, seu filho, ao rei David, a fim de cumprimentá-lo e dar-lhe os parabéns por ele ter derrotado Hadadezer, pois Hadadezer estava sempre a guerrear contra Toú. Hadorão levou a David todo o tipo de objetos de ouro, de prata e de cobre,

[[v13-18-11]]

^<<v13-18-11,11>>^ os quais o rei David santificou para Jeová, juntamente com a prata e o ouro que tinha saqueado de todas as nações: Edom, Moabe, os amonitas, os filisteus e os amalequitas.

[[v13-18-12]]

^<<v13-18-12,12>>^ Abisai, filho de Zeruia, matou 18 000 edomitas no vale do Sal.

[[v13-18-13]]

^<<v13-18-13,13>>^ Ele manteve tropas em Edom, e todos os edomitas se tornaram servos de David. Jeová dava vitórias^&#42;1^ a David onde quer que ele fosse.

[NOTE]
====
. Ou: “salvação”.
====

[[v13-18-14]]

^<<v13-18-14,14>>^ David reinava sobre todo o Israel, e governava com justiça e retidão em benefício de todo o seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joabe, filho de Zeruia, era chefe do exército; Jeosafá, filho de Ailude, era cronista;

[[v13-18-16]]

^<<v13-18-16,16>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes; e Savsa era secretário.

[[v13-18-17]]

^<<v13-18-17,17>>^ Benaia, filho de Jeoiada, comandava os queretitas e os peletitas. E os filhos de David eram os principais oficiais do rei.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]