include::./index.adoc[]

[[v13-11-0]]
=== 1 Crónicas, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v13-11-1]]

^<<v13-11-1,1>>^ Com o tempo, todos os israelitas se juntaram a David, em Hébron, e disseram-lhe: “Somos do mesmo sangue.^&#42;1^

[NOTE]
====
. Lit.: “o teu osso e a tua carne”.
====

[[v13-11-2]]

^<<v13-11-2,2>>^ No passado, quando Saul era rei, era o senhor que liderava Israel nas suas campanhas militares.^&#42;1^ E Jeová, seu Deus, disse-lhe: ‘Pastorearás o meu povo Israel e irás tornar-te líder do meu povo Israel.’”

[NOTE]
====
. Lit.: “eras aquele que fazia sair e aquele que fazia entrar Israel”.
====

[[v13-11-3]]

^<<v13-11-3,3>>^ Assim, todos os anciãos de Israel foram ter com o rei David em Hébron, e David fez um pacto com eles em Hébron, perante Jeová. Depois, ungiram David como rei sobre Israel, conforme Jeová tinha ordenado por meio de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Mais tarde, David e todo o Israel foram a Jerusalém, isto é, Jebus, na região onde moravam os jebuseus.

[[v13-11-5]]

^<<v13-11-5,5>>^ Os habitantes de Jebus fizeram pouco de David, dizendo: “Tu nunca entrarás aqui!” No entanto, David apoderou-se da fortaleza de Sião, que hoje é a Cidade de David.

[[v13-11-6]]

^<<v13-11-6,6>>^ David disse: “Quem for o primeiro a golpear os jebuseus há de tornar-se chefe^&#42;1^ e príncipe.” Joabe, filho de Zeruia, foi o primeiro a subir e tornou-se chefe.

[NOTE]
====
. Lit.: “cabeça”.
====

[[v13-11-7]]

^<<v13-11-7,7>>^ Então, David passou a morar na fortaleza. Por isso, chamaram àquele lugar Cidade de David.

[[v13-11-8]]

^<<v13-11-8,8>>^ Ele fez construções por toda a cidade, do Aterro^&#42;1^ até aos arredores, e Joabe reconstruiu o restante da cidade.

[NOTE]
====
. Ou: “de Milo”. Termo hebraico que significa “encher”.
====

[[v13-11-9]]

^<<v13-11-9,9>>^ Assim, David tornou-se cada vez mais poderoso, e Jeová dos exércitos estava com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ Estes foram os chefes dos guerreiros valentes de David que, com todo o Israel, apoiaram firmemente o seu reinado e ajudaram a fazê-lo rei, conforme a palavra de Jeová a respeito de Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ Esta é a lista dos guerreiros valentes de David: Jasobeão, filho de um hacmonita, o chefe dos três. Numa ocasião, ele matou 300 homens com a sua lança.

[[v13-11-12]]

^<<v13-11-12,12>>^ Depois dele vinha Eleazar, filho de Dodo, o aoíta. Era um dos três guerreiros valentes.

[[v13-11-13]]

^<<v13-11-13,13>>^ Ele estava com David em Pas-Damim, onde os filisteus se tinham reunido para a guerra. Havia ali uma plantação de cevada, e os soldados tinham^&#42;1^ fugido por causa dos filisteus.

[NOTE]
====
. Ou: “o povo tinha”.
====

[[v13-11-14]]

^<<v13-11-14,14>>^ Contudo, ele posicionou-se no meio da plantação e defendeu-a, matando os filisteus, de modo que Jeová lhes deu uma grande vitória.^&#42;1^

[NOTE]
====
. Ou: “salvação”.
====

[[v13-11-15]]

^<<v13-11-15,15>>^ Três dos 30 chefes foram até à rocha para se encontrarem com David na caverna de Adulão, enquanto o exército filisteu estava acampado no vale^&#42;1^ de Refaim.

[NOTE]
====
. Ou: “na planície”.
====

[[v13-11-16]]

^<<v13-11-16,16>>^ Nessa época, David estava no seu refúgio, e um grupo de soldados filisteus estava em Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ David expressou o seguinte desejo: “Quem me dera beber da água da cisterna que fica junto ao portão de Belém!”

[[v13-11-18]]

^<<v13-11-18,18>>^ Em vista disso, os três invadiram o acampamento dos filisteus, tiraram água da cisterna que fica junto ao portão de Belém e trouxeram-na a David. David, porém, não a quis beber e derramou-a para Jeová.

[[v13-11-19]]

^<<v13-11-19,19>>^ Ele disse: “Por respeito ao meu Deus, eu nunca faria tal coisa! Como é que eu poderia beber o sangue dos homens que arriscaram a vida?^&#42;1^ Pois eles arriscaram a vida^&#42;2^ para trazê-la.” Assim, ele não a quis beber. Estas foram as façanhas dos três guerreiros valentes de David.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v13-11-20]]

^<<v13-11-20,20>>^ Abisai, irmão de Joabe, tornou-se o chefe de outro grupo de três. Ele matou 300 homens com a sua lança e era tão famoso como os três primeiros.

[[v13-11-21]]

^<<v13-11-21,21>>^ Desses outros três, ele destacava-se mais do que os seus dois companheiros, e era o chefe deles, mas não chegou à categoria dos três primeiros.

[[v13-11-22]]

^<<v13-11-22,22>>^ Benaia, filho de Jeoiada, era um homem corajoso^&#42;1^ que realizou muitas façanhas em Cabzeel. Ele matou os dois filhos de Ariel, de Moabe; desceu a uma cisterna num dia em que nevou, e matou um leão.

[NOTE]
====
. Lit.: “o filho de um homem de valor”.
====

[[v13-11-23]]

^<<v13-11-23,23>>^ Além disso, ele matou um egípcio de tamanho extraordinário, de cinco côvados^&#42;1^ de altura. Embora o egípcio tivesse na mão uma lança que parecia o cilindro dos tecelões, Benaia enfrentou-o com uma vara. Ele arrancou a lança da mão do egípcio e matou-o com ela.

[NOTE]
====
. Ele tinha cerca de 2,23 m. Veja o Ap. B14.
====

[[v13-11-24]]

^<<v13-11-24,24>>^ Estas foram as façanhas de Benaia, filho de Jeoiada. Ele era tão famoso como os três guerreiros valentes.

[[v13-11-25]]

^<<v13-11-25,25>>^ Embora se destacasse ainda mais do que os 30, não chegou à categoria dos três. No entanto, David designou-o sobre a sua guarda pessoal.

[[v13-11-26]]

^<<v13-11-26,26>>^ Os guerreiros valentes das forças militares eram Asael, irmão de Joabe; Elanã, filho de Dodo, de Belém;

[[v13-11-27]]

^<<v13-11-27,27>>^ Samote, o harorita; Helez, o pelonita;

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira, filho de Iques, o tecoíta; Abiezer, o anatotita;

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibecai, o husatita; Ilai, o aoíta;

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai, o netofatita; Helede, filho de Baaná, o netofatita;

[[v13-11-31]]

^<<v13-11-31,31>>^ Itai, filho de Ribai, de Gibeá dos benjaminitas; Benaia, o piratonita;

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai, dos vales^&#42;1^ de Gaás; Abiel, o arbatita;

[NOTE]
====
. Ou: “uádis”. Veja o Glossário.
====

[[v13-11-33]]

^<<v13-11-33,33>>^ Azmavete, o baarumita; Eliaba, o saalbonita;

[[v13-11-34]]

^<<v13-11-34,34>>^ os filhos de Hasém, o gizonita; Jonatã, filho de Sage, o hararita;

[[v13-11-35]]

^<<v13-11-35,35>>^ Aião, filho de Sacar, o hararita; Elifal, filho de Ur;

[[v13-11-36]]

^<<v13-11-36,36>>^ Hefer, o mequeratita; Aías, o pelonita;

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezro, o carmelita; Naarai, filho de Ezbai;

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natã; Mibar, filho de Hagri;

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeleque, o amonita; Naarai, o berotita, escudeiro de Joabe, filho de Zeruia;

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira, o itrita; Garebe, o itrita;

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias, o hitita; Zabade, filho de Alai;

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina, filho de Siza, o rubenita, e chefe dos rubenitas, com quem havia 30 homens;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanã, filho de Maacá; Josafá, o mitnita;

[[v13-11-44]]

^<<v13-11-44,44>>^ Uzia, o asteratita; Sama e Jeiel, filhos de Hotão, o aroerita;

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediael, filho de Sinri; Joa, seu irmão, o tizita;

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel, o maavita; Jeribai e Josavias, filhos de Elnaão; Itma, o moabita;

[[v13-11-47]]

^<<v13-11-47,47>>^ Eliel; Obede; e Jaasiel, o mezobaíta.

'''

xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]