include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, será que se estão a apegar à fé no nosso glorioso Senhor Jesus Cristo, ao mesmo tempo que demonstram favoritismo?

[[v59-2-2]]

^<<v59-2-2,2>>^ Pois, se um homem com anéis de ouro nos dedos e com roupa magnífica entrar na vossa reunião, mas também entrar um pobre, com roupa imunda,

[[v59-2-3]]

^<<v59-2-3,3>>^ será que olham com favor para aquele que usa roupa magnífica e dizem: “Sente-se aqui, num lugar de honra”, mas dizem ao pobre: “Fica de pé”, ou: “Senta-te ali no chão, ao lado do apoio para os meus pés”?

[[v59-2-4]]

^<<v59-2-4,4>>^ Se isso acontece, não é verdade que estão a fazer distinções de classes entre vocês e que se tornaram juízes que tomam decisões perversas?

[[v59-2-5]]

^<<v59-2-5,5>>^ Escutem, meus amados irmãos. Não é verdade que Deus escolheu os que são pobres aos olhos do mundo para serem ricos na fé e herdeiros do Reino que ele prometeu aos que o amam?

[[v59-2-6]]

^<<v59-2-6,6>>^ Vocês, porém, desonram o pobre. Não são os ricos que vos oprimem e que vos arrastam perante os tribunais?

[[v59-2-7]]

^<<v59-2-7,7>>^ Não são eles que blasfemam o nome honroso que vocês levam?

[[v59-2-8]]

^<<v59-2-8,8>>^ Se cumprem a lei régia,^&#42;1^ segundo a passagem das Escrituras: “Ama o teu próximo como a ti mesmo”, fazem muito bem.

[NOTE]
====
. Ou: “real”.
====

[[v59-2-9]]

^<<v59-2-9,9>>^ Mas, se continuam a mostrar favoritismo, estão a cometer um pecado e são condenados^&#42;1^ pela lei como transgressores.

[NOTE]
====
. Ou: “repreendidos”.
====

[[v59-2-10]]

^<<v59-2-10,10>>^ Pois se alguém cumpre toda a Lei, mas dá um passo em falso num só ponto, torna-se infrator de toda a Lei.

[[v59-2-11]]

^<<v59-2-11,11>>^ Pois aquele que disse: “Não cometas adultério” disse também: “Não assassines.” Portanto, se tu não cometes adultério, mas assassinas, tornas-te transgressor da Lei.

[[v59-2-12]]

^<<v59-2-12,12>>^ Falem e comportem-se como pessoas que serão julgadas pela lei de um povo livre.^&#42;1^

[NOTE]
====
. Lit.: “lei da liberdade”.
====

[[v59-2-13]]

^<<v59-2-13,13>>^ Pois quem não pratica a misericórdia será julgado sem misericórdia. A misericórdia triunfa sobre o julgamento.

[[v59-2-14]]

^<<v59-2-14,14>>^ De que adianta, meus irmãos, alguém dizer que tem fé, se não tem obras? Será que essa fé pode salvá-lo?

[[v59-2-15]]

^<<v59-2-15,15>>^ Se um irmão ou uma irmã não tem o que vestir,^&#42;1^ nem alimento suficiente para o dia,

[NOTE]
====
. Lit.: “Se um irmão ou uma irmã estiver nu”.
====

[[v59-2-16]]

^<<v59-2-16,16>>^ e um de vocês lhe diz: “Vai em paz; mantém-te aquecido e bem alimentado”, mas não lhe dá o que necessita para o corpo, de que é que isso adianta?

[[v59-2-17]]

^<<v59-2-17,17>>^ Assim também a fé, por si só, sem obras, está morta.

[[v59-2-18]]

^<<v59-2-18,18>>^ Contudo, alguém dirá: “Tu tens fé e eu tenho obras. Mostra-me a tua fé sem as obras, e eu vou mostrar-te a minha fé pelas minhas obras.”

[[v59-2-19]]

^<<v59-2-19,19>>^ Crês que há um só Deus? Fazes muito bem. Contudo, os demónios creem e estremecem.

[[v59-2-20]]

^<<v59-2-20,20>>^ Mas queres ver, ó homem vão, como a fé sem obras é inútil?

[[v59-2-21]]

^<<v59-2-21,21>>^ Não foi Abraão, nosso pai, declarado justo por obras depois de ter oferecido Isaque, seu filho, no altar?

[[v59-2-22]]

^<<v59-2-22,22>>^ Repara que a sua fé agiu em conjunto com as suas obras e que a sua fé se tornou perfeita pelas suas obras,

[[v59-2-23]]

^<<v59-2-23,23>>^ e cumpriu-se a passagem das Escrituras que diz: “Abraão depositou fé em Jeová,^&#42;1^ e isso foi-lhe creditado como justiça”, e ele veio a ser chamado amigo de Jeová.^&#42;2^

[NOTE]
====
. Veja o Ap. A5.
. Veja o Ap. A5.
====

[[v59-2-24]]

^<<v59-2-24,24>>^ Vejam que o homem será declarado justo por obras, e não apenas pela fé.

[[v59-2-25]]

^<<v59-2-25,25>>^ Da mesma maneira, não foi também Raabe, a prostituta, declarada justa por obras, depois de receber hospitaleiramente os mensageiros e de mandá-los embora por outro caminho?

[[v59-2-26]]

^<<v59-2-26,26>>^ Realmente, assim como o corpo sem espírito^&#42;1^ está morto, assim também a fé sem obras está morta.

[NOTE]
====
. Ou: “fôlego”.
====

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]