include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v59-1-1]]

^<<v59-1-1,1>>^ Tiago, escravo de Deus e do Senhor Jesus Cristo, às 12 tribos que estão espalhadas:
Saudações!

[[v59-1-2]]

^<<v59-1-2,2>>^ Meus irmãos, considerem como motivo de verdadeira alegria o facto de enfrentarem diversas provações,

[[v59-1-3]]

^<<v59-1-3,3>>^ visto que sabem que a qualidade provada da vossa fé produz perseverança.

[[v59-1-4]]

^<<v59-1-4,4>>^ Todavia, deixem que a perseverança complete a sua obra, para que sejam completos e sãos em todos os sentidos, sem vos faltar nada.

[[v59-1-5]]

^<<v59-1-5,5>>^ Portanto, se alguém tem falta de sabedoria, que persista em pedi-la a Deus — pois ele dá a todos generosamente, sem censurar^&#42;1^ —, e esta vai ser-lhe dada.

[NOTE]
====
. Ou: “recriminar”.
====

[[v59-1-6]]

^<<v59-1-6,6>>^ No entanto, que persista em pedir com fé, sem duvidar de nada, pois quem duvida é semelhante a uma onda do mar, que o vento leva de um lado para o outro.

[[v59-1-7]]

^<<v59-1-7,7>>^ De facto, essa pessoa não deve esperar receber alguma coisa de Jeová;^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-1-8]]

^<<v59-1-8,8>>^ ela é indecisa, instável em todos os seus caminhos.

[[v59-1-9]]

^<<v59-1-9,9>>^ Que o irmão humilde, porém, se alegre^&#42;1^ por causa do seu enaltecimento,

[NOTE]
====
. Lit.: “fale com orgulho”.
====

[[v59-1-10]]

^<<v59-1-10,10>>^ e o rico por causa da sua humilhação; porque o rico passará como a flor do campo.

[[v59-1-11]]

^<<v59-1-11,11>>^ Pois o sol levanta-se com o seu calor abrasador, faz a planta secar, então, a sua flor cai e a sua beleza desaparece. Assim também o rico desaparecerá no meio dos seus empreendimentos.

[[v59-1-12]]

^<<v59-1-12,12>>^ Feliz aquele que continua a perseverar em provação, porque ao ser aprovado receberá a coroa da vida, que Jeová^&#42;1^ prometeu aos que continuam a amá-lo.

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-1-13]]

^<<v59-1-13,13>>^ Quando alguém estiver sob provação, que não diga: “Estou a ser provado por Deus.” Pois, com coisas más, Deus não pode ser provado, nem prova ele a ninguém.

[[v59-1-14]]

^<<v59-1-14,14>>^ No entanto, cada um é provado ao ser atraído e seduzido^&#42;1^ pelo seu próprio desejo.

[NOTE]
====
. Ou: “e apanhado como que com um isco”.
====

[[v59-1-15]]

^<<v59-1-15,15>>^ Então, o desejo, quando se torna fértil,^&#42;1^ dá à luz o pecado; e o pecado, quando consumado, produz a morte.

[NOTE]
====
. Lit.: “quando concebe”.
====

[[v59-1-16]]

^<<v59-1-16,16>>^ Não se enganem, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda a boa dádiva e todo o presente perfeito vem de cima, desce do Pai das luzes celestes, o qual não muda como as sombras inconstantes.^&#42;1^

[NOTE]
====
. Ou: “com quem não há variação da virada da sombra”.
====

[[v59-1-18]]

^<<v59-1-18,18>>^ Foi da sua vontade produzir-nos por meio da palavra da verdade, para que fôssemos, de certa forma, primícias das suas criaturas.

[[v59-1-19]]

^<<v59-1-19,19>>^ Tenham isto em mente, meus amados irmãos: todos devem estar prontos para ouvir, mas não devem precipitar-se em falar, nem irritar-se com facilidade;

[[v59-1-20]]

^<<v59-1-20,20>>^ pois a ira do homem não produz a justiça de Deus.

[[v59-1-21]]

^<<v59-1-21,21>>^ Portanto, abandonem toda a imundície e todo o vestígio de maldade,^&#42;1^ e aceitem com brandura a implantação da palavra que é capaz de vos salvar.^&#42;2^

[NOTE]
====
. Ou, possivelmente: “e a abundância de maldade”.
. Ou: “de salvar as vossas almas”.
====

[[v59-1-22]]

^<<v59-1-22,22>>^ Contudo, tornem-se cumpridores da palavra, e não apenas ouvintes, enganando-se com raciocínios falsos.

[[v59-1-23]]

^<<v59-1-23,23>>^ Porque, se alguém é ouvinte da palavra e não cumpridor, é semelhante a um homem que vê o seu próprio rosto^&#42;1^ num espelho.

[NOTE]
====
. Ou: “o seu rosto natural”.
====

[[v59-1-24]]

^<<v59-1-24,24>>^ Pois ele olha para si mesmo, vai-se embora e esquece-se logo de como é.

[[v59-1-25]]

^<<v59-1-25,25>>^ Aquele, porém, que examina com cuidado a lei perfeita que pertence à liberdade, e continua nela, torna-se não um ouvinte que facilmente se esquece, mas um cumpridor da obra; e ele será feliz no que faz.

[[v59-1-26]]

^<<v59-1-26,26>>^ Se alguém acha que adora a Deus,^&#42;1^ mas não domina^&#42;2^ a língua, está a enganar o seu próprio coração, e a sua adoração é fútil.

[NOTE]
====
. Ou: “é religioso”.
. Ou: “não refreia”.
====

[[v59-1-27]]

^<<v59-1-27,27>>^ A forma de adoração^&#42;1^ que é pura e imaculada do ponto de vista do nosso Deus e Pai é esta: cuidar dos órfãos e das viúvas nas suas dificuldades, e manter-se sem mancha do mundo.

[NOTE]
====
. Ou: “A religião”.
====

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]