include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v59-3-1]]

^<<v59-3-1,1>>^ Não devia haver muitos entre vocês a tornarem-se instrutores, meus irmãos, pois sabem que nós receberemos um julgamento mais pesado.^&#42;1^

[NOTE]
====
. Ou: “rigoroso”.
====

[[v59-3-2]]

^<<v59-3-2,2>>^ Pois todos nós tropeçamos^&#42;1^ muitas vezes. Se alguém não tropeça em palavra, é homem perfeito, capaz de refrear também todo o seu corpo.

[NOTE]
====
. Ou: “cometemos erros”.
====

[[v59-3-3]]

^<<v59-3-3,3>>^ Se colocamos freios na boca dos cavalos para que nos obedeçam, guiamos também todo o seu corpo.

[[v59-3-4]]

^<<v59-3-4,4>>^ Vejam também os navios: embora sejam grandes e impelidos por ventos fortes, são dirigidos por um leme muito pequeno, para onde o timoneiro deseja ir.

[[v59-3-5]]

^<<v59-3-5,5>>^ Do mesmo modo, a língua é uma parte pequena do corpo, mas gaba-se de grandes coisas. Vejam como basta uma simples centelha para incendiar uma grande floresta!

[[v59-3-6]]

^<<v59-3-6,6>>^ A língua também é um fogo. A língua representa um mundo de injustiça entre os membros do nosso corpo, pois contamina todo o corpo e incendeia por inteiro o curso da vida;^&#42;1^ as suas chamas vêm da Geena.^&#42;2^

[NOTE]
====
. Lit.: “a roda do nascimento (da origem)”.
. Veja o Glossário.
====

[[v59-3-7]]

^<<v59-3-7,7>>^ Pois toda a espécie de animais selvagens, de aves, de répteis^&#42;1^ e de animais marinhos pode ser domada e tem sido domada pelos humanos.

[NOTE]
====
. Ou: “animais rasteiros”.
====

[[v59-3-8]]

^<<v59-3-8,8>>^ Contudo, nenhum humano consegue domar a língua. Ela é indisciplinada e prejudicial, cheia de veneno mortífero.

[[v59-3-9]]

^<<v59-3-9,9>>^ É com ela que louvamos a Jeová,^&#42;1^ o Pai, e é com ela que amaldiçoamos homens que vieram a existir “à semelhança de Deus”.

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-3-10]]

^<<v59-3-10,10>>^ Da mesma boca saem bênçãos e maldições.
Meus irmãos, não é correto que as coisas sejam assim.

[[v59-3-11]]

^<<v59-3-11,11>>^ Será que uma fonte faz brotar pela mesma abertura água doce e água amarga?

[[v59-3-12]]

^<<v59-3-12,12>>^ Meus irmãos, será que a figueira produz azeitonas, ou a videira figos? Assim também a fonte de água salgada não pode produzir água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Quem é sábio e entendido entre vocês? Que ele mostre, pela sua boa conduta, obras realizadas com a brandura que vem da sabedoria.

[[v59-3-14]]

^<<v59-3-14,14>>^ No entanto, se têm no coração ciúme amargo e rivalidade,^&#42;1^ não se gabem, não mintam contra a verdade.

[NOTE]
====
. Ou, possivelmente: “ambição egoísta”.
====

[[v59-3-15]]

^<<v59-3-15,15>>^ Essa não é a sabedoria que desce de cima; é terrena, animal, demoníaca.

[[v59-3-16]]

^<<v59-3-16,16>>^ Porque onde houver ciúme e rivalidade,^&#42;1^ ali haverá também desordem e toda a espécie de coisas más.

[NOTE]
====
. Ou, possivelmente: “ambição egoísta”.
====

[[v59-3-17]]

^<<v59-3-17,17>>^ Porém, a sabedoria de cima é primeiramente pura, depois pacífica, razoável, pronta para obedecer, cheia de misericórdia e de bons frutos, imparcial, sem hipocrisia.

[[v59-3-18]]

^<<v59-3-18,18>>^ Além disso, o fruto da justiça é semeado em condições pacíficas para os^&#42;1^ pacificadores.

[NOTE]
====
. Ou, possivelmente: “pelos”.
====

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]