include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v59-5-1]]

^<<v59-5-1,1>>^ Agora, ricos, escutem! Chorem e lamentem por causa das desgraças que vos sobrevirão.

[[v59-5-2]]

^<<v59-5-2,2>>^ As vossas riquezas apodreceram e as vossas roupas foram roídas pela traça.

[[v59-5-3]]

^<<v59-5-3,3>>^ O vosso ouro e a vossa prata foram consumidos pela ferrugem, e a ferrugem deles servirá de testemunho contra vocês e consumirá a vossa carne. O que acumularam será como um fogo nos últimos dias.

[[v59-5-4]]

^<<v59-5-4,4>>^ Vejam! O salário que deixaram de pagar aos trabalhadores que colheram os vossos campos está a clamar, e os clamores por ajuda da parte dos ceifeiros chegaram aos ouvidos de Jeová^&#42;1^ dos exércitos.

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-5-5]]

^<<v59-5-5,5>>^ Vocês tiveram na terra uma vida de luxo, entregue aos prazeres. Engordaram o coração no dia da matança.

[[v59-5-6]]

^<<v59-5-6,6>>^ Condenaram, assassinaram o justo. Será que ele não se opõe a vocês?

[[v59-5-7]]

^<<v59-5-7,7>>^ Portanto, sejam pacientes, irmãos, até à presença do Senhor. Vejam como o lavrador fica à espera do precioso fruto da terra, aguardando-o com paciência até chegarem as primeiras e as últimas chuvas.

[[v59-5-8]]

^<<v59-5-8,8>>^ Também vocês, exerçam paciência; fortaleçam o coração, porque se aproxima a presença do Senhor.

[[v59-5-9]]

^<<v59-5-9,9>>^ Não resmunguem^&#42;1^ uns contra os outros, irmãos, para que não sejam julgados. Vejam! O Juiz está às portas.

[NOTE]
====
. Ou: “Não gemam; Não reclamem”. Lit.: “Não soltem suspiros”.
====

[[v59-5-10]]

^<<v59-5-10,10>>^ Irmãos, no que se refere a suportar sofrimentos e a exercer paciência, tomem como modelo os profetas, que falaram em nome de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-5-11]]

^<<v59-5-11,11>>^ Vejam, consideramos felizes^&#42;1^ os que perseveraram. Ouviram falar da perseverança de Jó e viram o resultado que Jeová^&#42;2^ proporcionou; viram que Jeová^&#42;3^ tem grande compaixão^&#42;4^ e é misericordioso.

[NOTE]
====
. Ou: “abençoados”.
. Veja o Ap. A5.
. Veja o Ap. A5.
. Ou: “é muito terno em afeição”.
====

[[v59-5-12]]

^<<v59-5-12,12>>^ Acima de tudo, meus irmãos, parem de jurar, quer pelo céu, quer pela terra, e parem de fazer qualquer outro juramento. No entanto, que o vosso “sim” signifique sim, e o vosso “não”, não, para que não estejam sujeitos a julgamento.

[[v59-5-13]]

^<<v59-5-13,13>>^ Há alguém a sofrer entre vocês? Que ele persista em orar. Há alguém animado? Que ele cante salmos.

[[v59-5-14]]

^<<v59-5-14,14>>^ Há alguém doente entre vocês? Que ele chame os anciãos da congregação, e que orem por ele, ungindo-o com óleo^&#42;1^ em nome de Jeová.^&#42;2^

[NOTE]
====
. Ou: “azeite”.
. Veja o Ap. A5.
====

[[v59-5-15]]

^<<v59-5-15,15>>^ E a oração de fé fará com que o doente^&#42;1^ fique bom, e Jeová^&#42;2^ irá levantá-lo. Além disso, se ele tiver cometido pecados, será perdoado.

[NOTE]
====
. Ou, possivelmente: “cansado”.
. Veja o Ap. A5.
====

[[v59-5-16]]

^<<v59-5-16,16>>^ Portanto, confessem abertamente os vossos pecados uns aos outros e orem uns pelos outros, para que sejam curados. A súplica do justo tem um efeito poderoso.^&#42;1^

[NOTE]
====
. Lit.: “tem muita força quando age”.
====

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era um homem com sentimentos iguais aos nossos; contudo, quando ele orou com fervor para que não chovesse, não choveu naquela terra por três anos e seis meses.

[[v59-5-18]]

^<<v59-5-18,18>>^ Então, ele orou novamente, e o céu deu chuva, e a terra produziu frutos.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se alguém entre vocês for desencaminhado da verdade e outro fizer com que ele volte,

[[v59-5-20]]

^<<v59-5-20,20>>^ saibam que quem fizer um pecador voltar do seu caminho errado vai salvá-lo^&#42;1^ da morte e cobrir uma multidão de pecados.

[NOTE]
====
. Ou: “salvar a alma dele”.
====

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]