include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v59-4-1]]

^<<v59-4-1,1>>^ De onde vêm as vossas guerras e lutas? Não vêm dos vossos desejos carnais, que travam um combate no vosso íntimo?^&#42;1^

[NOTE]
====
. Lit.: “nos vossos membros”.
====

[[v59-4-2]]

^<<v59-4-2,2>>^ Vocês desejam, mas não têm. Continuam a assassinar e a cobiçar, mas não conseguem obter o que querem. Continuam a lutar e a guerrear. Não têm porque não pedem.

[[v59-4-3]]

^<<v59-4-3,3>>^ Quando pedem, não recebem, porque pedem com o objetivo errado, para gastar nos vossos desejos carnais.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adúlteras,^&#42;1^ não sabem que a amizade com o mundo é inimizade com Deus? Portanto, quem quer ser amigo do mundo torna-se inimigo de Deus.

[NOTE]
====
. Ou: “Infiéis”.
====

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou acham que é sem motivo que as Escrituras dizem: “O espírito que passou a morar em nós continua cheio de desejos invejosos”?

[[v59-4-6]]

^<<v59-4-6,6>>^ No entanto, a bondade imerecida que Ele concede é maior. Por isso, as Escrituras dizem: “Deus opõe-se aos arrogantes, mas concede bondade imerecida aos humildes.”

[[v59-4-7]]

^<<v59-4-7,7>>^ Portanto, sujeitem-se a Deus; mas oponham-se ao Diabo, e ele fugirá de vocês.

[[v59-4-8]]

^<<v59-4-8,8>>^ Acheguem-se a Deus, e ele vai achegar-se a vocês. Limpem as mãos, ó pecadores, e purifiquem o coração, ó indecisos.

[[v59-4-9]]

^<<v59-4-9,9>>^ Fiquem tristes, lamentem e chorem. Que o vosso riso se transforme em choro, e a vossa alegria em tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhem-se aos olhos de Jeová,^&#42;1^ e ele vai enaltecer-vos.

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-4-11]]

^<<v59-4-11,11>>^ Parem de falar uns contra os outros, irmãos. Quem fala contra um irmão ou julga o seu irmão fala contra a lei e julga a lei. Ora, se julgas a lei, não és cumpridor da lei, mas juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Há somente um que é Legislador e Juiz, aquele que é capaz de salvar e de destruir. Mas tu, quem és tu para julgar o teu próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ Agora escutem, vocês, os que dizem: “Hoje ou amanhã, viajaremos para aquela cidade, passaremos lá um ano, negociaremos e ganharemos dinheiro”,

[[v59-4-14]]

^<<v59-4-14,14>>^ embora nem sequer saibam como será a vossa vida amanhã. Porque são uma neblina que aparece por um instante e depois desaparece.

[[v59-4-15]]

^<<v59-4-15,15>>^ Em vez disso, deviam dizer: “Se Jeová^&#42;1^ quiser, viveremos e faremos isto ou aquilo.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v59-4-16]]

^<<v59-4-16,16>>^ Mas o que acontece é que se orgulham das vossas arrogantes pretensões. Todo esse orgulho é mau.

[[v59-4-17]]

^<<v59-4-17,17>>^ Portanto, se alguém sabe fazer o que é certo e ainda assim não o faz, está a pecar.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]