include::./index.adoc[]

[[v56-3-0]]
=== Tito, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v56-3-1]]

^<<v56-3-1,1>>^ Continua a lembrar-lhes que estejam sujeitos e sejam obedientes a governos e autoridades, que estejam prontos para toda a boa obra,

[[v56-3-2]]

^<<v56-3-2,2>>^ que não digam mal de ninguém, que não sejam conflituosos, mas que sejam razoáveis, demonstrando toda a brandura para com todos os homens.

[[v56-3-3]]

^<<v56-3-3,3>>^ Pois, antes, nós também éramos insensatos, desobedientes, tínhamos sido desviados, éramos escravos de vários desejos e prazeres, vivíamos em maldade e inveja, éramos detestáveis, odiávamo-nos uns aos outros.

[[v56-3-4]]

^<<v56-3-4,4>>^ No entanto, quando se manifestou a bondade do nosso Salvador, Deus, e o seu amor à humanidade,

[[v56-3-5]]

^<<v56-3-5,5>>^ ele salvou-nos (não por causa de obras justas que tivéssemos realizado, mas por causa da sua misericórdia) por meio do banho que nos trouxe à vida e por nos renovar pelo espírito santo.

[[v56-3-6]]

^<<v56-3-6,6>>^ Ele derramou ricamente^&#42;1^ esse espírito sobre nós por meio de Jesus Cristo, nosso Salvador,

[NOTE]
====
. Ou: “generosamente”.
====

[[v56-3-7]]

^<<v56-3-7,7>>^ a fim de que, depois de sermos declarados justos por meio da sua bondade imerecida, nos tornássemos herdeiros segundo uma esperança de vida eterna.

[[v56-3-8]]

^<<v56-3-8,8>>^ Estas palavras são dignas de confiança, e eu desejo que continues a enfatizar estas coisas, a fim de que aqueles que creram em Deus mantenham a mente concentrada em praticar boas obras. Estas coisas são excelentes e benéficas para os homens.

[[v56-3-9]]

^<<v56-3-9,9>>^ No entanto, não te envolvas, de modo algum, em controvérsias tolas, genealogias, brigas e discussões sobre a Lei, porque são inúteis e vãs.

[[v56-3-10]]

^<<v56-3-10,10>>^ Quanto ao homem que promove uma seita, rejeita-o depois de o aconselhares com firmeza^&#42;1^ uma primeira e uma segunda vez,

[NOTE]
====
. Ou: “de o avisares”.
====

[[v56-3-11]]

^<<v56-3-11,11>>^ sabendo que ele se desviou do caminho, está a pecar e condena-se a si mesmo.

[[v56-3-12]]

^<<v56-3-12,12>>^ Quando eu te enviar Ártemas ou Tíquico, faz o máximo para me visitares em Nicópolis, pois foi ali que decidi passar o inverno.

[[v56-3-13]]

^<<v56-3-13,13>>^ Providencia tudo o que for necessário para a viagem de Zenas, que é perito na Lei, e de Apolo, para que não lhes falte nada.

[[v56-3-14]]

^<<v56-3-14,14>>^ E que os nossos também aprendam a empenhar-se em boas obras, a fim de ajudar em casos de necessidade urgente, para que não sejam improdutivos.^&#42;1^

[NOTE]
====
. Lit.: “infrutíferos”.
====

[[v56-3-15]]

^<<v56-3-15,15>>^ Todos os que estão comigo mandam-te saudações. Transmite as minhas saudações aos que nos amam na fé.
Que a bondade imerecida esteja com todos vocês.

'''

xref:056-tito/056-tito-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-filemon/057-filemon-001.adoc#v57-1-0[Próximo Capítulo &#62;]