include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v56-1-1]]

^<<v56-1-1,1>>^ Paulo, escravo de Deus e apóstolo de Jesus Cristo, em harmonia com a fé dos escolhidos de Deus e com o conhecimento exato da verdade, que está de acordo com a devoção a Deus

[[v56-1-2]]

^<<v56-1-2,2>>^ e que se baseia numa esperança de vida eterna que Deus, que não pode mentir, prometeu há muito tempo

[[v56-1-3]]

^<<v56-1-3,3>>^ — mas, no seu devido tempo, tornou a sua palavra conhecida por meio da pregação que me foi confiada, de acordo com a ordem do nosso Salvador, Deus —,

[[v56-1-4]]

^<<v56-1-4,4>>^ a Tito, filho genuíno, segundo a fé que temos em comum:
Que tenhas bondade imerecida e paz da parte de Deus, o Pai, e de Cristo Jesus, nosso Salvador.

[[v56-1-5]]

^<<v56-1-5,5>>^ Deixei-te em Creta para que corrigisses as coisas que precisavam de ser endireitadas^&#42;1^ e fizesses designações de anciãos em cada cidade, conforme as instruções que te dei:

[NOTE]
====
. Ou: “coisas deficientes”.
====

[[v56-1-6]]

^<<v56-1-6,6>>^ o ancião deve estar livre de acusação, ser marido de uma só esposa e ter filhos crentes que não sejam acusados de devassidão^&#42;1^ nem de rebeldia.

[NOTE]
====
. Ou: “desregramento”.
====

[[v56-1-7]]

^<<v56-1-7,7>>^ Porque, como administrador designado por Deus, um superintendente tem de estar livre de acusação, não deve ser obstinado, nem alguém que se ire com facilidade, nem beberrão, nem violento,^&#42;1^ nem ávido de ganho desonesto,

[NOTE]
====
. Ou: “espancador”.
====

[[v56-1-8]]

^<<v56-1-8,8>>^ mas deve ser hospitaleiro, amar o que é bom, ser sensato,^&#42;1^ justo, leal, ter autodomínio,

[NOTE]
====
. Ou: “alguém que tenha bom juízo (bom critério)”.
====

[[v56-1-9]]

^<<v56-1-9,9>>^ apegar-se firmemente à palavra fiel^&#42;1^ com respeito à sua arte de ensino, para que possa encorajar^&#42;2^ por meio do ensinamento sadio,^&#42;3^ assim como repreender os que o contradizem.

[NOTE]
====
. Ou: “mensagem confiável”.
. Ou: “exortar”.
. Ou: “salutar; benéfico”.
====

[[v56-1-10]]

^<<v56-1-10,10>>^ Pois há muitos homens rebeldes, faladores fúteis e enganadores, especialmente os que se apegam à circuncisão.

[[v56-1-11]]

^<<v56-1-11,11>>^ É preciso calar-lhes a boca, porque esses homens persistem em arruinar famílias inteiras, por ensinarem coisas que não devem, visando ganho desonesto.

[[v56-1-12]]

^<<v56-1-12,12>>^ Um deles, o seu próprio profeta, disse: “Os cretenses são sempre mentirosos, animais ferozes, glutões preguiçosos.”

[[v56-1-13]]

^<<v56-1-13,13>>^ Este testemunho é verdadeiro. Por esta razão, continua a repreendê-los com severidade, para que sejam sãos na fé

[[v56-1-14]]

^<<v56-1-14,14>>^ e não prestem atenção a fábulas judaicas e a mandamentos de homens que se desviam da verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Todas as coisas são puras para os puros; mas, para os impuros e sem fé, nada é puro, pois tanto a sua mente como a sua consciência estão contaminadas.

[[v56-1-16]]

^<<v56-1-16,16>>^ Eles declaram publicamente que conhecem a Deus, mas negam-no pelas suas obras, porque são detestáveis, desobedientes e não são aprovados para qualquer tipo de boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]