include::./index.adoc[]

[[v62-3-0]]
=== 1 João, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v62-3-1]]

^<<v62-3-1,1>>^ Vejam com que amor o Pai nos amou, a ponto de sermos chamados filhos de Deus! E é isso que nós somos. É por isso que o mundo não nos conhece, porque não chegou a conhecê-lo.

[[v62-3-2]]

^<<v62-3-2,2>>^ Amados, agora somos filhos de Deus, mas ainda não foi revelado o que seremos. Sabemos que, quando ele for manifestado, seremos semelhantes a ele, porque o veremos assim como ele é.

[[v62-3-3]]

^<<v62-3-3,3>>^ E todo aquele que tem esta esperança nele purifica-se, assim como ele é puro.

[[v62-3-4]]

^<<v62-3-4,4>>^ Todo aquele que pratica o pecado pratica também o que é contra a lei, e o pecado é aquilo que é contra a lei.

[[v62-3-5]]

^<<v62-3-5,5>>^ Vocês também sabem que ele foi manifestado para tirar os nossos pecados, e nele não há pecado.

[[v62-3-6]]

^<<v62-3-6,6>>^ Todo aquele que permanece em união com ele não pratica o pecado; ninguém que pratica o pecado o viu, nem chegou a conhecê-lo.

[[v62-3-7]]

^<<v62-3-7,7>>^ Filhinhos, que ninguém vos desencaminhe. Quem pratica a justiça é justo, assim como ele é justo.

[[v62-3-8]]

^<<v62-3-8,8>>^ Quem pratica o pecado origina-se do Diabo, porque o Diabo tem estado a pecar desde o princípio.^&#42;1^ Com este objetivo, o Filho de Deus foi manifestado: para desfazer^&#42;2^ as obras do Diabo.

[NOTE]
====
. Ou: “desde quando começou”.
. Ou: “destruir”.
====

[[v62-3-9]]

^<<v62-3-9,9>>^ Todo aquele que nasceu de Deus não pratica o pecado, pois a Sua semente^&#42;1^ permanece nele, e ele não pode praticar o pecado, pois nasceu de Deus.

[NOTE]
====
. Isto é, semente capaz de reproduzir, ou de dar fruto.
====

[[v62-3-10]]

^<<v62-3-10,10>>^ Sabemos quem são os filhos de Deus e quem são os filhos do Diabo da seguinte forma: aquele que não pratica a justiça não se origina de Deus, nem aquele que não ama o seu irmão.

[[v62-3-11]]

^<<v62-3-11,11>>^ Porque esta é a mensagem que ouviram desde o princípio: devemos amar-nos uns aos outros;

[[v62-3-12]]

^<<v62-3-12,12>>^ não como Caim, que se originou do Maligno e matou o seu irmão. E por que motivo o matou? Porque as suas próprias obras eram más, mas as do seu irmão eram justas.

[[v62-3-13]]

^<<v62-3-13,13>>^ Não se admirem, irmãos, de o mundo vos odiar.

[[v62-3-14]]

^<<v62-3-14,14>>^ Nós sabemos que passámos da morte para a vida porque amamos os irmãos. Quem não ama permanece na morte.

[[v62-3-15]]

^<<v62-3-15,15>>^ Todo aquele que odeia o seu irmão é assassino,^&#42;1^ e vocês sabem que a vida eterna não permanece em nenhum assassino.

[NOTE]
====
. Ou: “homicida”.
====

[[v62-3-16]]

^<<v62-3-16,16>>^ Por meio disto, chegámos a conhecer o amor: ele entregou a vida^&#42;1^ por nós, e nós temos a obrigação de entregar a vida^&#42;2^ pelos nossos irmãos.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v62-3-17]]

^<<v62-3-17,17>>^ No entanto, se alguém tem os bens deste mundo e vê o seu irmão a passar necessidade e, ainda assim, recusa-se a mostrar-lhe compaixão, de que modo é que o amor de^&#42;1^ Deus permanece nele?

[NOTE]
====
. Ou: “a”.
====

[[v62-3-18]]

^<<v62-3-18,18>>^ Filhinhos, devemos amar não em palavras nem com a língua, mas em ações e em verdade.

[[v62-3-19]]

^<<v62-3-19,19>>^ Por meio disto, saberemos que nos originamos da verdade e tranquilizaremos^&#42;1^ o nosso coração diante dele,

[NOTE]
====
. Ou: “persuadiremos; convenceremos”.
====

[[v62-3-20]]

^<<v62-3-20,20>>^ sempre que o nosso coração nos condenar, porque Deus é maior do que o nosso coração e sabe todas as coisas.

[[v62-3-21]]

^<<v62-3-21,21>>^ Amados, se o nosso coração não nos condena, temos confiança ao falar com Deus,

[[v62-3-22]]

^<<v62-3-22,22>>^ e recebemos dele tudo o que pedimos, porque obedecemos aos seus mandamentos e fazemos o que é agradável aos seus olhos.

[[v62-3-23]]

^<<v62-3-23,23>>^ Realmente, este é o seu mandamento: que tenhamos fé no nome do seu Filho, Jesus Cristo, e que nos amemos uns aos outros, assim como ele nos deu um mandamento.

[[v62-3-24]]

^<<v62-3-24,24>>^ Além disso, quem obedece aos seus mandamentos permanece em união com ele, e ele em união com esse. E, pelo espírito que ele nos deu, sabemos que ele permanece em união connosco.

'''

xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[Próximo Capítulo &#62;]