include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v62-1-1]]

^<<v62-1-1,1>>^ O que era desde o princípio, que ouvimos, que vimos com os nossos olhos, que observámos e que as nossas mãos apalparam, com respeito à palavra da vida

[[v62-1-2]]

^<<v62-1-2,2>>^ (sim, a vida foi revelada, e nós vimos, e estamos a dar testemunho e a relatar-vos a vida eterna que estava com o Pai e que nos foi revelada),

[[v62-1-3]]

^<<v62-1-3,3>>^ o que vimos e ouvimos estamos, também, a relatar-vos, para que também possam estar unidos^&#42;1^ connosco. E nós estamos unidos com o Pai e com o seu Filho, Jesus Cristo.

[NOTE]
====
. Ou: “tenham uma parceria (participação)”.
====

[[v62-1-4]]

^<<v62-1-4,4>>^ Escrevemos estas coisas para que a nossa alegria seja completa.

[[v62-1-5]]

^<<v62-1-5,5>>^ Esta é a mensagem que ouvimos dele e que vos anunciamos: Deus é luz, e não há nenhuma escuridão nele.^&#42;1^

[NOTE]
====
. Ou: “em união com ele”.
====

[[v62-1-6]]

^<<v62-1-6,6>>^ Se fazemos a declaração: “Estamos unidos^&#42;1^ com ele”, mas continuamos a andar na escuridão, estamos a mentir e não estamos a praticar a verdade.

[NOTE]
====
. Ou: “Temos uma parceria”.
====

[[v62-1-7]]

^<<v62-1-7,7>>^ No entanto, se andamos na luz assim como ele próprio está na luz, estamos unidos^&#42;1^ uns com os outros, e o sangue de Jesus, seu Filho, purifica-nos de todo o pecado.

[NOTE]
====
. Ou: “temos uma parceria”.
====

[[v62-1-8]]

^<<v62-1-8,8>>^ Se fazemos a declaração: “Não temos pecado”, enganamo-nos a nós mesmos e a verdade não está em nós.

[[v62-1-9]]

^<<v62-1-9,9>>^ Se confessamos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e purificar-nos de toda a injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se fazemos a declaração: “Nós não pecámos”, fazemos dele um mentiroso, e a sua palavra não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]