include::./index.adoc[]

[[v62-2-0]]
=== 1 João, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v62-2-1]]

^<<v62-2-1,1>>^ Meus filhinhos, escrevo-vos estas coisas para que não cometam um pecado. Contudo, se alguém cometer um pecado, temos um ajudador^&#42;1^ junto ao Pai: Jesus Cristo, um justo.

[NOTE]
====
. Ou: “advogado”.
====

[[v62-2-2]]

^<<v62-2-2,2>>^ E ele é um sacrifício propiciatório^&#42;1^ pelos nossos pecados; contudo, não apenas pelos nossos, mas também pelos do mundo inteiro.

[NOTE]
====
. Ou: “sacrifício de expiação; meio de pacificação”.
====

[[v62-2-3]]

^<<v62-2-3,3>>^ É por meio disto que sabemos que o conhecemos: se continuarmos a obedecer aos seus mandamentos.

[[v62-2-4]]

^<<v62-2-4,4>>^ Quem diz: “Eu conheço-o”, e, ainda assim, não obedece aos seus mandamentos, é mentiroso, e a verdade não está nele.

[[v62-2-5]]

^<<v62-2-5,5>>^ No entanto, se alguém obedece à sua palavra, nele, o amor de^&#42;1^ Deus foi verdadeiramente aperfeiçoado. Por meio disto, sabemos que estamos em união com ele.

[NOTE]
====
. Ou: “a”.
====

[[v62-2-6]]

^<<v62-2-6,6>>^ Quem diz que permanece em união com ele está, ele mesmo, sob a obrigação de continuar a andar assim como ele andou.

[[v62-2-7]]

^<<v62-2-7,7>>^ Amados, escrevo-vos, não um novo mandamento, mas um mandamento antigo, que já têm desde o princípio. Este mandamento antigo é a palavra que vocês ouviram.

[[v62-2-8]]

^<<v62-2-8,8>>^ Contudo, escrevo-vos um novo mandamento, algo que é verdadeiro no caso dele e no vosso, porque a escuridão está a passar e a verdadeira luz já está a brilhar.

[[v62-2-9]]

^<<v62-2-9,9>>^ Quem diz que está na luz, mas odeia o seu irmão, ainda está na escuridão.

[[v62-2-10]]

^<<v62-2-10,10>>^ Quem ama o seu irmão permanece na luz, e nele não há motivo para tropeço.

[[v62-2-11]]

^<<v62-2-11,11>>^ Contudo, quem odeia o seu irmão está na escuridão e está a andar na escuridão, e não sabe para onde vai, porque a escuridão lhe cegou os olhos.

[[v62-2-12]]

^<<v62-2-12,12>>^ Escrevo-vos, filhinhos, porque os vossos pecados foram perdoados por causa do seu nome.

[[v62-2-13]]

^<<v62-2-13,13>>^ Escrevo-vos, pais, porque conhecem aquele que existe desde o princípio. Escrevo-vos, jovens, porque venceram o Maligno. Escrevo-vos, filhinhos, porque conhecem o Pai.

[[v62-2-14]]

^<<v62-2-14,14>>^ Escrevo-vos, pais, porque conhecem aquele que existe desde o princípio. Escrevo-vos, jovens, porque são fortes, e a palavra de Deus permanece em vocês, e vocês venceram o Maligno.

[[v62-2-15]]

^<<v62-2-15,15>>^ Não amem nem o mundo, nem as coisas no mundo. Se alguém ama o mundo, o amor do^&#42;1^ Pai não está nele;

[NOTE]
====
. Ou: “ao”.
====

[[v62-2-16]]

^<<v62-2-16,16>>^ porque tudo o que há no mundo — o desejo da carne, o desejo dos olhos e a ostentação^&#42;1^ de posses — não se origina do Pai, mas origina-se do mundo.

[NOTE]
====
. Ou: “o gabar-se”.
====

[[v62-2-17]]

^<<v62-2-17,17>>^ Além disso, o mundo está a passar, assim como o seu desejo, mas quem faz a vontade de Deus permanece para sempre.

[[v62-2-18]]

^<<v62-2-18,18>>^ Filhinhos, esta é a última hora e, assim como ouviram que o anticristo virá, já surgiram agora muitos anticristos. Por causa disso, sabemos que esta é a última hora.

[[v62-2-19]]

^<<v62-2-19,19>>^ Eles saíram do nosso meio, mas não eram dos nossos,^&#42;1^ pois, se fossem dos nossos, teriam permanecido connosco. Mas saíram para que se mostrasse que nem todos são dos nossos.

[NOTE]
====
. Ou: “não nos pertenciam”.
====

[[v62-2-20]]

^<<v62-2-20,20>>^ E vocês têm uma unção que receberam daquele que é santo e todos vocês têm conhecimento.

[[v62-2-21]]

^<<v62-2-21,21>>^ Escrevo-vos, não porque não conhecem a verdade, mas porque a conhecem, e porque nenhuma mentira se origina da verdade.

[[v62-2-22]]

^<<v62-2-22,22>>^ Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Esse é o anticristo, aquele que nega o Pai e o Filho.

[[v62-2-23]]

^<<v62-2-23,23>>^ Todo aquele que nega o Filho não tem também o Pai. Mas quem reconhece o Filho tem também o Pai.

[[v62-2-24]]

^<<v62-2-24,24>>^ No vosso caso, aquilo que ouviram desde o princípio deve permanecer em vocês. Se aquilo que ouviram desde o princípio permanecer em vocês, também permanecerão em união com o Filho e em união com o Pai.

[[v62-2-25]]

^<<v62-2-25,25>>^ De igual modo, foi isto que ele mesmo nos prometeu: a vida eterna.

[[v62-2-26]]

^<<v62-2-26,26>>^ Escrevo-vos estas coisas a respeito dos que estão a tentar desencaminhar-vos.

[[v62-2-27]]

^<<v62-2-27,27>>^ E, no vosso caso, a unção que receberam dele permanece em vocês, e não precisam de que alguém vos ensine. No entanto, a unção da parte dele, que é verdadeira e não é nenhuma mentira, ensina-vos todas as coisas. Assim como ela vos ensinou, permaneçam em união com ele.

[[v62-2-28]]

^<<v62-2-28,28>>^ Assim, filhinhos, permaneçam em união com ele, para que, quando ele for manifestado, possamos falar com confiança e não nos afastemos dele, envergonhados, durante a sua presença.

[[v62-2-29]]

^<<v62-2-29,29>>^ Se sabem que ele é justo, também sabem que todo aquele que pratica a justiça nasceu dele.

'''

xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[Próximo Capítulo &#62;]