include::./index.adoc[]

[[v16-4-0]]
=== Neemias, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v16-4-1]]

^<<v16-4-1,1>>^ Assim que Sambalá soube que estávamos a reconstruir a muralha, ficou furioso e muito aborrecido,^&#42;1^ e começou a fazer pouco dos judeus.

[NOTE]
====
. Ou: “ofendido”.
====

[[v16-4-2]]

^<<v16-4-2,2>>^ E ele disse na presença dos seus irmãos e do exército de Samaria: “O que é que estes judeus fracos estão a fazer? Acham eles que vão fazer isto sozinhos? Será que vão oferecer sacrifícios? Pensam que vão terminar a obra num só dia? Vão fazer renascer as pedras queimadas dentre os montes de escombros poeirentos?”

[[v16-4-3]]

^<<v16-4-3,3>>^ Tobias, o amonita, estava ao seu lado e disse: “Até uma raposa que subisse esta muralha de pedras que estão a construir conseguiria derrubá-la.”

[[v16-4-4]]

^<<v16-4-4,4>>^ Ouve, ó nosso Deus, porque estamos a ser tratados com desprezo; faz com que a afronta deles recaia sobre as suas próprias cabeças, e que sejam levados cativos como despojo para uma terra estrangeira.

[[v16-4-5]]

^<<v16-4-5,5>>^ Não ignores a sua culpa nem deixes que o seu pecado seja apagado de diante de ti, pois eles insultaram os construtores.

[[v16-4-6]]

^<<v16-4-6,6>>^ Então, continuámos a construir a muralha. Fechámos todas as brechas e reconstruímo-la até metade da sua altura. E o povo continuou a empenhar-se de coração no trabalho.

[[v16-4-7]]

^<<v16-4-7,7>>^ Assim que Sambalá, Tobias, os árabes, os amonitas e os asdoditas souberam que o conserto das muralhas de Jerusalém estava a avançar e que as brechas estavam a ser fechadas, ficaram muito zangados.

[[v16-4-8]]

^<<v16-4-8,8>>^ Todos eles conspiraram para vir lutar contra Jerusalém e causar confusão.

[[v16-4-9]]

^<<v16-4-9,9>>^ No entanto, orámos ao nosso Deus e colocámos guardas de vigia, de dia e de noite, para nos protegermos contra eles.

[[v16-4-10]]

^<<v16-4-10,10>>^ No entanto, alguns entre o povo de Judá diziam: “Os trabalhadores^&#42;1^ estão esgotados, e há demasiado entulho; nunca conseguiremos reconstruir a muralha.”

[NOTE]
====
. Ou: “carregadores”.
====

[[v16-4-11]]

^<<v16-4-11,11>>^ E os nossos inimigos diziam: “Antes que eles se apercebam ou que nos vejam, entraremos no seu meio; vamos matá-los e parar a obra.”

[[v16-4-12]]

^<<v16-4-12,12>>^ Sempre que os judeus que moravam perto deles entravam na cidade, eles diziam-nos, vez após vez:^&#42;1^ “Eles vão atacar-nos de todos os lados.”

[NOTE]
====
. Lit.: “dez vezes”.
====

[[v16-4-13]]

^<<v16-4-13,13>>^ Por conseguinte, coloquei guardas nas partes mais baixas e desprotegidas, atrás da muralha; posicionei-os, divididos por famílias, armados com espadas, lanças e arcos.

[[v16-4-14]]

^<<v16-4-14,14>>^ Quando percebi que estavam com medo, fui imediatamente dizer aos nobres, aos subgovernadores e ao restante do povo: “Não tenham medo deles. Lembrem-se de Jeová, que é grande e inspira temor, e lutem pelos vossos irmãos, filhos e filhas, esposas e lares.”

[[v16-4-15]]

^<<v16-4-15,15>>^ Depois de os nossos inimigos saberem que tínhamos descoberto o que eles estavam a fazer, e que o verdadeiro Deus tinha frustrado os seus planos, todos nós voltámos a trabalhar na muralha.

[[v16-4-16]]

^<<v16-4-16,16>>^ Daquele dia em diante, metade dos meus homens trabalhava na obra, enquanto a outra metade ficava de guarda com lanças, escudos, arcos e cotas de malha. E os príncipes apoiavam^&#42;1^ todos os da casa de Judá,

[NOTE]
====
. Lit.: “estavam atrás de”.
====

[[v16-4-17]]

^<<v16-4-17,17>>^ que reconstruíam a muralha. Os carregadores faziam o trabalho com uma das mãos, e com a outra seguravam uma arma.^&#42;1^

[NOTE]
====
. Ou: “arma de arremesso”.
====

[[v16-4-18]]

^<<v16-4-18,18>>^ Cada um dos construtores tinha uma espada à cintura enquanto trabalhava, e o homem que tocava a buzina ficava ao meu lado.

[[v16-4-19]]

^<<v16-4-19,19>>^ Então, eu disse aos nobres, aos subgovernadores e ao restante do povo: “A obra é grande e extensa, e estamos espalhados ao longo da muralha, muito longe uns dos outros.

[[v16-4-20]]

^<<v16-4-20,20>>^ Quando ouvirem o som da buzina, juntem-se a nós onde estivermos. O nosso Deus lutará por nós.”

[[v16-4-21]]

^<<v16-4-21,21>>^ Assim, continuávamos a trabalhar enquanto a outra metade ficava com as lanças na mão, desde o raiar do dia até aparecerem as estrelas.

[[v16-4-22]]

^<<v16-4-22,22>>^ Naquele tempo, eu disse ao povo: “Que todos os homens e os seus ajudantes passem a noite em Jerusalém. À noite, eles servirão como guardas para nós e, durante o dia, trabalharão na obra.”

[[v16-4-23]]

^<<v16-4-23,23>>^ Por isso é que eu, os meus irmãos, os meus ajudantes e os guardas que me seguiam nunca tirávamos as vestes. Cada um mantinha a sua arma na mão direita.

'''

xref:016-neemias/016-neemias-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-neemias/016-neemias-005.adoc#v16-5-0[Próximo Capítulo &#62;]