include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v16-1-1]]

^<<v16-1-1,1>>^ As palavras de Neemias,^&#42;1^ filho de Hacalias: No mês de quisleu,^&#42;2^ no vigésimo ano, eu estava na fortaleza^&#42;3^ de Susã.^&#42;4^

[NOTE]
====
. Que significa “Jah consola”.
. Veja o Ap. B15.
. Ou: “na cidadela; no palácio”.
. Ou: “Susa”.
====

[[v16-1-2]]

^<<v16-1-2,2>>^ Chegou então Hanani, um dos meus irmãos, com outros homens de Judá, e eu perguntei-lhes pelo restante dos judeus que tinha sobrevivido ao cativeiro e também por Jerusalém.

[[v16-1-3]]

^<<v16-1-3,3>>^ Eles responderam: “Os que restaram e permanecem na província^&#42;1^ e que sobreviveram ao cativeiro estão a enfrentar grandes dificuldades e humilhação. As muralhas de Jerusalém estão em ruínas e os seus portões foram queimados com fogo.”

[NOTE]
====
. Ou: “no distrito jurisdicional”, possivelmente o de Judá.
====

[[v16-1-4]]

^<<v16-1-4,4>>^ Assim que ouvi estas palavras, sentei-me, comecei a chorar e fiquei de luto durante muitos dias. Jejuei e orei perante o Deus dos céus

[[v16-1-5]]

^<<v16-1-5,5>>^ e disse-lhe: “Ó Jeová, Deus dos céus, o Deus grande e que inspira temor, que guarda o seu pacto e demonstra amor leal aos que o amam e aos que guardam os seus mandamentos,

[[v16-1-6]]

^<<v16-1-6,6>>^ por favor, que os teus olhos estejam abertos e os teus ouvidos atentos à oração do teu servo, que hoje faço perante ti. Oro a ti, dia e noite, pelos teus servos, os israelitas, e confesso os pecados que o povo de Israel cometeu contra ti. Pecámos, tanto eu como a casa do meu pai.

[[v16-1-7]]

^<<v16-1-7,7>>^ Sem dúvida, agimos de modo corrupto contra ti por não obedecermos aos mandamentos, aos decretos e às decisões judiciais que deste ao teu servo Moisés.

[[v16-1-8]]

^<<v16-1-8,8>>^ “Por favor, lembra-te da palavra que ordenaste^&#42;1^ ao teu servo Moisés: ‘Se agirem de modo infiel, vou espalhar-vos entre os povos.

[NOTE]
====
. Ou: “da advertência que deste”.
====

[[v16-1-9]]

^<<v16-1-9,9>>^ Mas, se retornarem a mim, cumprirem os meus mandamentos e os guardarem, mesmo que o vosso povo tenha sido espalhado até aos confins da terra, eu hei de reuni-los onde quer que estejam e trazê-los ao lugar que escolhi para fazer residir o meu nome.’

[[v16-1-10]]

^<<v16-1-10,10>>^ Eles são os teus servos e o teu povo, que resgataste com o teu grande poder e com a tua mão poderosa.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ó Jeová, por favor, que os teus ouvidos estejam atentos à oração deste teu servo e às orações dos teus servos, que se agradam em temer o teu nome. Por favor, faz com que, hoje, este teu servo seja bem-sucedido e que este homem^&#42;1^ tenha compaixão de mim.”
Nessa época, eu era copeiro do rei.

[NOTE]
====
. Isto é, o rei.
====

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]