include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v16-2-1]]

^<<v16-2-1,1>>^ No mês de nisã,^&#42;1^ no vigésimo ano do rei Artaxerxes, colocou-se vinho diante dele, e, como de costume, peguei no vinho e servi-o ao rei. No entanto, eu nunca tinha estado abatido na sua presença.

[NOTE]
====
. Veja o Ap. B15.
====

[[v16-2-2]]

^<<v16-2-2,2>>^ Por isso, o rei disse-me: “Porque é que estás tão abatido se não estás doente? Isso só pode ser tristeza de coração.” Nisto, fiquei com muito medo.

[[v16-2-3]]

^<<v16-2-3,3>>^ Então, eu disse ao rei: “Vida longa ao rei! Como é que eu não hei de estar abatido se a cidade onde os meus antepassados foram sepultados está em ruínas e os seus portões foram consumidos pelo fogo?”

[[v16-2-4]]

^<<v16-2-4,4>>^ O rei respondeu-me: “O que é que queres pedir?” Orei imediatamente ao Deus dos céus.

[[v16-2-5]]

^<<v16-2-5,5>>^ Eu disse então ao rei: “Se for do agrado do rei, e se o seu servo tiver achado favor diante do senhor, envie-me a Judá, à cidade onde estão sepultados os meus antepassados, para que eu a reconstrua.”

[[v16-2-6]]

^<<v16-2-6,6>>^ Por conseguinte, o rei, tendo a rainha^&#42;1^ sentada ao seu lado, perguntou-me: “Quanto tempo durará a tua viagem, e quando é que voltarás?” Assim, o rei teve agrado em enviar-me e eu informei-o a respeito do tempo que passaria fora.

[NOTE]
====
. Ou: “consorte real”.
====

[[v16-2-7]]

^<<v16-2-7,7>>^ E eu disse ao rei: “Se for do agrado do rei, sejam-me dadas cartas para entregar aos governadores da região a oeste do rio Eufrates,^&#42;1^ para que me deixem passar em segurança até chegar a Judá,

[NOTE]
====
. Ou: “região Além do Rio; região do Transeufrates”.
====

[[v16-2-8]]

^<<v16-2-8,8>>^ e também uma carta para Asafe, guarda do Parque Real,^&#42;1^ para que me forneça madeira para as vigas dos portões da Fortaleza da Casa,^&#42;2^ das muralhas da cidade e da casa em que vou ficar.” Portanto, o rei deu-me as cartas, visto que a boa mão do meu Deus estava sobre mim.

[NOTE]
====
. Ou: “da floresta do rei”.
. Ou: “do Templo”.
====

[[v16-2-9]]

^<<v16-2-9,9>>^ Por fim, cheguei à região a oeste do rio Eufrates^&#42;1^ e dei as cartas do rei aos governadores. O rei também tinha enviado comigo chefes militares e cavaleiros.

[NOTE]
====
. Ou: “região Além do Rio; região do Transeufrates”.
====

[[v16-2-10]]

^<<v16-2-10,10>>^ Quando Sambalá, o horonita, e Tobias, o oficial^&#42;1^ amonita, souberam disso, ficaram muito aborrecidos com a chegada de alguém para fazer alguma coisa a favor do povo de Israel.

[NOTE]
====
. Lit.: “servo”.
====

[[v16-2-11]]

^<<v16-2-11,11>>^ Finalmente, cheguei a Jerusalém, onde fiquei durante três dias.

[[v16-2-12]]

^<<v16-2-12,12>>^ Então, levantei-me de noite, eu e alguns homens, mas não contei a ninguém o que o meu Deus tinha posto no meu coração para eu fazer por Jerusalém; e não levei nenhum outro animal comigo além daquele que eu montava.

[[v16-2-13]]

^<<v16-2-13,13>>^ Saí de noite pelo Portão do Vale, passei em frente à Fonte da Cobra Grande e fui até ao Portão dos Montes de Cinzas. Inspecionei as muralhas de Jerusalém, que estavam em ruínas, e os portões, que tinham sido consumidos pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ Segui caminho até ao Portão da Fonte e ao Reservatório de Água do Rei, e não havia espaço suficiente para o animal que eu montava passar.

[[v16-2-15]]

^<<v16-2-15,15>>^ No entanto, continuei a subir o vale^&#42;1^ durante a noite, a inspecionar a muralha; depois, retornei e entrei pelo Portão do Vale, e assim voltei.

[NOTE]
====
. Ou: “uádi”.
====

[[v16-2-16]]

^<<v16-2-16,16>>^ Os subgovernadores não sabiam onde é que eu tinha ido nem o que eu estava a fazer, pois eu ainda não tinha dito nada aos judeus, nem aos sacerdotes, nem aos nobres, nem aos subgovernadores, nem aos outros trabalhadores.

[[v16-2-17]]

^<<v16-2-17,17>>^ Finalmente, disse-lhes: “Vejam como é difícil a situação em que nos encontramos. Jerusalém está em ruínas e os seus portões foram queimados com fogo. Venham, vamos reconstruir as muralhas de Jerusalém, para pôr fim a esta humilhação.”

[[v16-2-18]]

^<<v16-2-18,18>>^ De seguida, contei-lhes como a boa mão do meu Deus estava sobre mim e o que o rei me tinha dito. Perante isto, eles disseram: “Vamos começar imediatamente a reconstrução!” Portanto, encorajaram-se uns aos outros^&#42;1^ para realizar essa boa obra.

[NOTE]
====
. Lit.: “fortaleceram as suas mãos”.
====

[[v16-2-19]]

^<<v16-2-19,19>>^ Quando Sambalá, o horonita, Tobias, o oficial^&#42;1^ amonita, e Gesém, o árabe, souberam disso, começaram a gozar connosco e a tratar-nos com desprezo, dizendo: “O que é que estão a fazer? Estão a rebelar-se contra o rei?”

[NOTE]
====
. Lit.: “servo”.
====

[[v16-2-20]]

^<<v16-2-20,20>>^ Porém, eu respondi: “O Deus dos céus é quem fará com que sejamos bem-sucedidos, e nós, os seus servos, vamos começar a reconstrução; mas vocês não têm participação, nem direitos, nem história^&#42;1^ em Jerusalém.”

[NOTE]
====
. Ou: “privilégios”.
====

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]