include::./index.adoc[]

[[v16-13-0]]
=== Neemias, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v16-13-1]]

^<<v16-13-1,1>>^ Naquele dia, o livro de Moisés foi lido na presença do povo. Estava lá escrito que os amonitas e os moabitas nunca deveriam fazer parte da congregação do verdadeiro Deus,

[[v16-13-2]]

^<<v16-13-2,2>>^ pois não tinham ido ao encontro dos israelitas com pão e água; mas, em vez disso, tinham contratado Balaão para amaldiçoá-los. No entanto, o nosso Deus transformou a maldição numa bênção.

[[v16-13-3]]

^<<v16-13-3,3>>^ Assim que ouviram a Lei, começaram a separar de Israel todos os de descendência estrangeira.^&#42;1^

[NOTE]
====
. Ou: “descendência mista”.
====

[[v16-13-4]]

^<<v16-13-4,4>>^ Antes disso, o sacerdote encarregado dos depósitos^&#42;1^ da casa^&#42;2^ do nosso Deus era Eliasibe, parente de Tobias.

[NOTE]
====
. Ou: “refeitórios”.
. Ou: “do templo”.
====

[[v16-13-5]]

^<<v16-13-5,5>>^ Ele tinha colocado à disposição de Tobias um grande depósito^&#42;1^ no lugar onde antes se costumava guardar a oferta de cereais, o olíbano, os utensílios, o décimo^&#42;2^ dos cereais, do vinho novo e do azeite, que, de direito, cabe aos levitas, aos cantores e aos porteiros, bem como a contribuição para os sacerdotes.

[NOTE]
====
. Ou: “refeitório”.
. Ou: “dízimo”.
====

[[v16-13-6]]

^<<v16-13-6,6>>^ Durante todo esse tempo, eu não estava em Jerusalém, pois tinha voltado ao rei no trigésimo segundo ano de Artaxerxes, rei de Babilónia. Algum tempo depois, pedi ao rei para me ausentar.

[[v16-13-7]]

^<<v16-13-7,7>>^ Cheguei então a Jerusalém e vi o terrível mal que Eliasibe tinha feito. Ele tinha beneficiado Tobias, cedendo-lhe um depósito no pátio da casa do verdadeiro Deus.

[[v16-13-8]]

^<<v16-13-8,8>>^ Fiquei muito indignado com aquilo e, por isso, atirei todos os móveis de Tobias para fora do depósito.^&#42;1^

[NOTE]
====
. Ou: “refeitório”.
====

[[v16-13-9]]

^<<v16-13-9,9>>^ Depois, ordenei que purificassem os depósitos,^&#42;1^ onde voltei a colocar os utensílios da casa do verdadeiro Deus, com a oferta de cereais e o olíbano.

[NOTE]
====
. Ou: “refeitórios”.
====

[[v16-13-10]]

^<<v16-13-10,10>>^ Soube também que os levitas não estavam a receber as suas porções, de modo que os levitas e os cantores que faziam o serviço se tinham ido embora, cada um para o seu campo.

[[v16-13-11]]

^<<v16-13-11,11>>^ Então, comecei a repreender os subgovernadores, dizendo-lhes: “Porque é que a casa do verdadeiro Deus está a ser negligenciada?” Assim, reuni os levitas e designei-os novamente aos seus postos.

[[v16-13-12]]

^<<v16-13-12,12>>^ E todo o Judá trouxe o décimo dos cereais, do vinho novo e do azeite aos depósitos.

[[v16-13-13]]

^<<v16-13-13,13>>^ Então, designei Selemias, o sacerdote, Zadoque, o copista,^&#42;1^ e Pedaías, um dos levitas, como responsáveis pelos depósitos, e, como assistente, designei-lhes Hanã, filho de Zacur, filho de Matanias, pois eram considerados homens de confiança. Eles tinham a responsabilidade de fazer a distribuição de provisões pelos seus irmãos.

[NOTE]
====
. Ou: “escriba”.
====

[[v16-13-14]]

^<<v16-13-14,14>>^ Lembra-te de mim, ó meu Deus, pelo que fiz, e não apagues os atos de amor leal que realizei pela casa do meu Deus e pelos serviços que se fazem nela.^&#42;1^

[NOTE]
====
. Ou: “e ao cuidar dela”.
====

[[v16-13-15]]

^<<v16-13-15,15>>^ Naqueles dias, em Judá, vi pessoas a pisar uvas em lagares de vinho no sábado, a recolher montes de cereais e a carregar os cereais em jumentos. Eles traziam vinho, uvas, figos e todo o tipo de cargas a Jerusalém no dia de sábado. Eu adverti-os para que não vendessem provisões naquele dia.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “adverti-os naquele dia para que não vendessem provisões”.
====

[[v16-13-16]]

^<<v16-13-16,16>>^ E os tírios que moravam na cidade traziam peixe e todo o tipo de mercadorias e vendiam-nos, no sábado, ao povo de Judá em Jerusalém.

[[v16-13-17]]

^<<v16-13-17,17>>^ Então, repreendi os nobres de Judá, dizendo: “Que mal é este que estão a fazer, ao profanarem o dia de sábado?

[[v16-13-18]]

^<<v16-13-18,18>>^ Não foi isso o que os vossos antepassados fizeram, de modo que o nosso Deus trouxe toda esta calamidade sobre nós e sobre esta cidade? Agora, vocês estão a aumentar ainda mais a ira ardente contra Israel, ao profanarem o sábado.”

[[v16-13-19]]

^<<v16-13-19,19>>^ Portanto, assim que as sombras começaram a cobrir os portões de Jerusalém antes do sábado, eu ordenei que fechassem as portas. Também mandei que não as abrissem até depois do sábado, e coloquei alguns dos meus próprios ajudantes junto aos portões, para que não deixassem entrar nenhuma carga no dia de sábado.

[[v16-13-20]]

^<<v16-13-20,20>>^ Por isso, os comerciantes e os vendedores de todo o tipo de mercadorias passaram a noite fora de Jerusalém, uma ou duas vezes.

[[v16-13-21]]

^<<v16-13-21,21>>^ Por conseguinte, adverti-os, dizendo: “Porque é que estão a passar a noite junto à muralha? Se voltarem a fazer isso, vou remover-vos à força.” Daí em diante, eles nunca mais voltaram no sábado.

[[v16-13-22]]

^<<v16-13-22,22>>^ E eu disse aos levitas que se purificassem regularmente e que viessem guardar os portões, a fim de que o dia de sábado fosse tratado como sagrado. Lembra-te também disso a meu favor, ó meu Deus, e tem misericórdia de mim segundo o teu grande amor leal.

[[v16-13-23]]

^<<v16-13-23,23>>^ Naqueles dias, vi, também, judeus que se tinham casado com^&#42;1^ mulheres asdoditas, amonitas e moabitas.

[NOTE]
====
. Ou: “tinham levado para casa”.
====

[[v16-13-24]]

^<<v16-13-24,24>>^ Metade dos seus filhos falava asdodita e a outra metade falava outras línguas estrangeiras, mas nenhum deles sabia falar o idioma dos judeus.

[[v16-13-25]]

^<<v16-13-25,25>>^ Então, repreendi-os e amaldiçoei-os, espanquei alguns deles e arranquei-lhes os cabelos, e obriguei-os a jurar em nome de Deus, e disse: “Não devem dar as vossas filhas aos filhos deles, nem devem aceitar nenhuma das filhas deles para os vossos filhos ou para vocês mesmos.

[[v16-13-26]]

^<<v16-13-26,26>>^ Não foi por causa delas que Salomão, rei de Israel, pecou? Entre as muitas nações, não havia rei igual a ele; e ele era amado pelo seu Deus, de modo que Deus fez dele rei sobre todo o Israel. Porém, até mesmo ele pecou por causa das esposas estrangeiras.

[[v16-13-27]]

^<<v16-13-27,27>>^ Como é que foram capazes de cometer esta terrível maldade, agindo de modo infiel contra o nosso Deus por se casarem com mulheres estrangeiras?”

[[v16-13-28]]

^<<v16-13-28,28>>^ Um dos filhos de Joiada, filho de Eliasibe, o sumo sacerdote, tinha-se tornado genro de Sambalá, o horonita; por isso, expulsei-o para longe de mim.

[[v16-13-29]]

^<<v16-13-29,29>>^ Lembra-te deles, ó meu Deus, por terem profanado o sacerdócio e também o pacto do sacerdócio e dos levitas.

[[v16-13-30]]

^<<v16-13-30,30>>^ Assim, purifiquei-os de toda a impureza estrangeira e designei deveres aos sacerdotes e aos levitas, a cada um o seu serviço;

[[v16-13-31]]

^<<v16-13-31,31>>^ também tomei providências quanto ao suprimento de lenha nas épocas determinadas e quanto aos primeiros frutos maduros.
Lembra-te de mim com favor,^&#42;1^ ó meu Deus.

[NOTE]
====
. Ou: “para o meu bem”.
====

'''

xref:016-neemias/016-neemias-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-ester/017-ester-001.adoc#v17-1-0[Próximo Capítulo &#62;]