include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v16-5-1]]

^<<v16-5-1,1>>^ Entretanto, os homens e as suas esposas levantaram um grande clamor contra os seus irmãos judeus.

[[v16-5-2]]

^<<v16-5-2,2>>^ Alguns diziam: “Nós, os nossos filhos e as nossas filhas somos muitos. Precisamos de conseguir cereais para comermos e continuarmos vivos.”

[[v16-5-3]]

^<<v16-5-3,3>>^ Outros diziam: “Estamos a dar os nossos campos, as nossas vinhas e as nossas casas como garantia para conseguir cereais por causa da falta de alimentos.”

[[v16-5-4]]

^<<v16-5-4,4>>^ Ainda outros diziam: “Pedimos dinheiro emprestado para pagar o tributo do rei, dando os nossos campos e as nossas vinhas como garantia.

[[v16-5-5]]

^<<v16-5-5,5>>^ Ora, nós e os nossos irmãos somos da mesma carne e do mesmo sangue,^&#42;1^ e os nossos filhos são como os filhos deles, mas, ainda assim, temos de sujeitar os nossos filhos e as nossas filhas à escravidão, e algumas das nossas filhas já são escravas. E nada podemos fazer para impedi-lo, porque os nossos campos e as nossas vinhas já pertencem a outros.”

[NOTE]
====
. Lit.: “como a carne dos nossos irmãos é a nossa carne”.
====

[[v16-5-6]]

^<<v16-5-6,6>>^ Ao ouvir o seu clamor e estas palavras, fiquei muito zangado.

[[v16-5-7]]

^<<v16-5-7,7>>^ Então, refleti com cuidado sobre este assunto e comecei a repreender os nobres e os subgovernadores, dizendo: “Todos vocês estão a exigir juros^&#42;1^ dos vossos próprios irmãos.”
Além disso, convoquei uma grande assembleia por causa deles.

[NOTE]
====
. Ou: “usura”.
====

[[v16-5-8]]

^<<v16-5-8,8>>^ Eu disse-lhes: “Na medida do possível, nós voltámos a comprar os nossos irmãos judeus que tinham sido vendidos às nações. Mas agora vocês vão vender os vossos próprios irmãos? Será que também vamos ter de comprá-los outra vez?” Diante disso, ficaram calados, sem saber o que dizer.

[[v16-5-9]]

^<<v16-5-9,9>>^ De seguida, eu disse-lhes: “O que vocês estão a fazer não é correto. Não deviam andar no temor do nosso Deus para que as nações, os nossos inimigos, não gozem connosco?

[[v16-5-10]]

^<<v16-5-10,10>>^ Eu, os meus irmãos e os meus ajudantes também lhes emprestamos dinheiro e cereais. Por favor, vamos parar de emprestar a juros.

[[v16-5-11]]

^<<v16-5-11,11>>^ Por favor, devolvam-lhes, ainda hoje, os seus campos, vinhas, olivais e casas, bem como o centésimo^&#42;1^ do dinheiro, dos cereais, do vinho novo e do azeite que estão a exigir deles como juros.”

[NOTE]
====
. Ou: “um por cento”, isto é, por mês.
====

[[v16-5-12]]

^<<v16-5-12,12>>^ Então, eles responderam: “Nós vamos devolver-lhes essas coisas e não lhes exigiremos nada. Faremos exatamente o que disse.” Chamei, portanto, os sacerdotes e fiz com que aqueles homens jurassem que cumpririam a promessa.

[[v16-5-13]]

^<<v16-5-13,13>>^ Depois, sacudi as dobras da minha roupa^&#42;1^ e disse: “De igual modo, que o verdadeiro Deus sacuda para fora das suas casas e das suas propriedades todos aqueles que não cumprirem esta promessa e que, desta maneira, sejam sacudidos e fiquem sem nada.” Então, toda a congregação disse: “Amém!”^&#42;2^ e louvaram a Jeová. E o povo cumpriu o que prometeu.

[NOTE]
====
. Lit.: “sacudi o meu colo”.
. Ou: “Assim seja!”
====

[[v16-5-14]]

^<<v16-5-14,14>>^ Além disso, desde o dia em que ele^&#42;1^ me nomeou governador na terra de Judá, do vigésimo ano ao trigésimo segundo ano do rei Artaxerxes, isto é, por 12 anos, nem eu nem os meus irmãos comemos o pão a que o governador tem direito.

[NOTE]
====
. Isto é, o rei.
====

[[v16-5-15]]

^<<v16-5-15,15>>^ Contudo, os governadores antes de mim tinham sobrecarregado o povo e, todos os dias, exigiam-lhes 40 siclos^&#42;1^ de prata para comprarem pão e vinho. Até os seus ajudantes oprimiam o povo. No entanto, eu não agi assim por temor de Deus.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v16-5-16]]

^<<v16-5-16,16>>^ Além disso, participei na obra desta muralha, e nós não adquirimos nenhum campo; todos os meus ajudantes estavam ali reunidos para a obra.

[[v16-5-17]]

^<<v16-5-17,17>>^ Havia 150 judeus e subgovernadores que comiam à minha mesa, além dos que vinham das nações vizinhas.

[[v16-5-18]]

^<<v16-5-18,18>>^ Todos os dias, eram preparados para mim^&#42;1^ um touro, seis das melhores ovelhas, e aves; e a cada dez dias tínhamos todo o tipo de vinho em abundância. Apesar de tudo isso, não exigi o pão a que o governador tem direito, porque o povo já estava sobrecarregado com o trabalho.

[NOTE]
====
. Ou: “por minha conta”.
====

[[v16-5-19]]

^<<v16-5-19,19>>^ Lembra-te de mim com favor,^&#42;1^ ó meu Deus, por tudo o que fiz em benefício deste povo.

[NOTE]
====
. Ou: “para o meu bem”.
====

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]