include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v16-6-1]]

^<<v16-6-1,1>>^ Assim que Sambalá, Tobias, Gesém, o árabe, e os nossos outros inimigos foram informados de que eu tinha reconstruído a muralha e que já não havia nenhuma brecha nela (embora eu ainda não lhe tivesse colocado as portas nas entradas),

[[v16-6-2]]

^<<v16-6-2,2>>^ Sambalá e Gesém mandaram-me imediatamente a seguinte mensagem: “Vem, marquemos encontro num dos vilarejos do vale^&#42;1^ de Ono.” Na verdade, eles estavam a tramar fazer-me mal.

[NOTE]
====
. Lit.: “na planície de vale”.
====

[[v16-6-3]]

^<<v16-6-3,3>>^ Portanto, enviei mensageiros para que lhes dissessem: “Estou envolvido numa grande obra e não posso ir. Porque é que a obra havia de ser interrompida enquanto eu me ausento para ir ter convosco?”

[[v16-6-4]]

^<<v16-6-4,4>>^ Eles enviaram-me a mesma mensagem quatro vezes, e eu dei-lhes sempre a mesma resposta.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então, Sambalá enviou-me o seu ajudante com a mesma mensagem, pela quinta vez, com uma carta aberta na mão,

[[v16-6-6]]

^<<v16-6-6,6>>^ na qual estava escrito: “Ouviu-se dizer entre as nações, e Gesém também o confirma, que tu e os judeus estão a tramar uma rebelião — é por isso que estão a reconstruir a muralha. E, segundo o que se diz, tu serás o rei deles.

[[v16-6-7]]

^<<v16-6-7,7>>^ Além disso, designaste profetas para proclamarem em toda a cidade de Jerusalém a teu respeito: ‘Há um rei em Judá!’ Ora, estas coisas serão comunicadas ao rei. Portanto, vem para conversarmos sobre o assunto.”

[[v16-6-8]]

^<<v16-6-8,8>>^ No entanto, eu enviei-lhe a seguinte resposta: “Não aconteceu nada disso que estás a dizer; tudo isso é invenção tua.”^&#42;1^

[NOTE]
====
. Lit.: “vem do teu coração”.
====

[[v16-6-9]]

^<<v16-6-9,9>>^ Pois todos eles tentavam amedrontar-nos, e diziam: “As suas mãos vão cansar-se da obra, e ela não será concluída.” Por isso, ó Deus, fortalece as minhas mãos!

[[v16-6-10]]

^<<v16-6-10,10>>^ De seguida, fui à casa de Semaías, filho de Delaías, filho de Meetabel, que estava ali confinado. Ele disse: “Marquemos encontro na casa do verdadeiro Deus, dentro do templo, e fechemos as portas do templo, pois virão para te matar. Eles virão de noite com o objetivo de te matar.”

[[v16-6-11]]

^<<v16-6-11,11>>^ Contudo, eu disse: “Será que um homem como eu deve fugir? Será que um homem como eu pode entrar no templo e continuar vivo? Não entrarei!”

[[v16-6-12]]

^<<v16-6-12,12>>^ Assim, percebi que Deus não o tinha enviado, mas que Tobias e Sambalá o tinham contratado para declarar esta profecia contra mim.

[[v16-6-13]]

^<<v16-6-13,13>>^ Ele tinha sido contratado para me amedrontar e para me fazer pecar. Desse modo, eles teriam um motivo para manchar a minha reputação e humilhar-me.

[[v16-6-14]]

^<<v16-6-14,14>>^ Ó meu Deus, lembra-te de Tobias e de Sambalá, bem como das suas ações, e também de Noadias, a profetisa, e dos outros profetas que, vez após vez, tentaram amedrontar-me.

[[v16-6-15]]

^<<v16-6-15,15>>^ A muralha foi concluída em 52 dias, no dia 25 de elul.^&#42;1^

[NOTE]
====
. Veja o Ap. B15.
====

[[v16-6-16]]

^<<v16-6-16,16>>^ Quando os nossos inimigos souberam disso e todas as nações ao redor o viram, sentiram-se muito humilhados^&#42;1^ e reconheceram que foi com a ajuda do nosso Deus que a obra tinha sido feita.

[NOTE]
====
. Ou: “decaíram muito aos seus próprios olhos”.
====

[[v16-6-17]]

^<<v16-6-17,17>>^ Naqueles dias, os nobres de Judá enviavam muitas cartas a Tobias, e Tobias respondia.

[[v16-6-18]]

^<<v16-6-18,18>>^ Havia muitos em Judá que lhe tinham jurado fidelidade, pois ele era genro de Secanias, filho de Ará, e Jeoanã, filho de Tobias, tinha-se casado com a filha de Mesulão, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Além disso, falavam-me sempre bem dele e relatavam-lhe o que eu dizia. Então, Tobias enviava cartas para me amedrontar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]