include::./index.adoc[]

[[v4-25-0]]
=== Números, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-25-1]]

^<<v4-25-1,1>>^ Quando Israel morava em Sitim, o povo começou a cometer imoralidade sexual com as filhas de Moabe.

[[v4-25-2]]

^<<v4-25-2,2>>^ As mulheres convidaram o povo para os sacrifícios aos seus deuses, e o povo começou a comer e a curvar-se diante dos seus deuses.

[[v4-25-3]]

^<<v4-25-3,3>>^ Assim, Israel começou a adorar^&#42;1^ Baal de Peor, e Jeová ficou furioso com Israel.

[NOTE]
====
. Ou: “ligou-se a”.
====

[[v4-25-4]]

^<<v4-25-4,4>>^ Jeová disse a Moisés: “Reúne todos os líderes^&#42;1^ deste povo, mata-os e pendura-os perante Jeová em plena luz do dia,^&#42;2^ para que a ira ardente de Jeová recue de Israel.”

[NOTE]
====
. Lit.: “cabeças”.
. Lit.: “em frente ao sol”.
====

[[v4-25-5]]

^<<v4-25-5,5>>^ Moisés disse então aos juízes de Israel: “Cada um de vocês deve matar os seus homens que começaram a adorar^&#42;1^ Baal de Peor.”

[NOTE]
====
. Ou: “a ligar-se a”.
====

[[v4-25-6]]

^<<v4-25-6,6>>^ Contudo, precisamente naquele instante, um dos israelitas trouxe para o meio dos seus irmãos uma midianita, perante os olhos de Moisés e de toda a assembleia de Israel, enquanto eles choravam à entrada da tenda de reunião.

[[v4-25-7]]

^<<v4-25-7,7>>^ Vendo isso, Fineias, filho de Eleazar, filho de Arão, o sacerdote, levantou-se imediatamente do meio da assembleia e pegou numa lança.

[[v4-25-8]]

^<<v4-25-8,8>>^ E foi atrás do homem de Israel para dentro da tenda e trespassou ambos, o homem de Israel e a mulher, pelas partes genitais dela. Com isso, o flagelo sobre os israelitas parou.

[[v4-25-9]]

^<<v4-25-9,9>>^ Os que morreram por causa do flagelo somaram 24 000.

[[v4-25-10]]

^<<v4-25-10,10>>^ Jeová disse então a Moisés:

[[v4-25-11]]

^<<v4-25-11,11>>^ “Fineias, filho de Eleazar, filho de Arão, o sacerdote, afastou o meu furor do povo de Israel, porque não tolerou nenhuma infidelidade^&#42;1^ para comigo entre eles. Assim, não exterminei os israelitas na minha insistência em devoção exclusiva.

[NOTE]
====
. Ou: “rivalidade”.
====

[[v4-25-12]]

^<<v4-25-12,12>>^ Portanto, diz-lhe que faço com ele o meu pacto de paz.

[[v4-25-13]]

^<<v4-25-13,13>>^ E este será um pacto para um sacerdócio permanente para ele e para a sua descendência, porque ele não tolerou infidelidade^&#42;1^ para com o seu Deus e fez expiação pelo povo de Israel.”

[NOTE]
====
. Ou: “rivalidade”.
====

[[v4-25-14]]

^<<v4-25-14,14>>^ A propósito, o nome do israelita que foi morto com a midianita era Zinri, filho de Salu, maioral de uma casa paterna dos simeonitas.

[[v4-25-15]]

^<<v4-25-15,15>>^ O nome da midianita que foi morta era Cosbi, filha de Zur; ele era líder dos clãs de uma casa paterna em Midiã.

[[v4-25-16]]

^<<v4-25-16,16>>^ Mais tarde, Jeová disse a Moisés:

[[v4-25-17]]

^<<v4-25-17,17>>^ “Hostilizem os midianitas e matem-nos,

[[v4-25-18]]

^<<v4-25-18,18>>^ porque eles hostilizaram-vos com as ações astutas que praticaram contra vocês no caso de Peor e de Cosbi, filha de um maioral de Midiã e irmã deles, que foi morta no dia do flagelo ocorrido no caso de Peor.”

'''

xref:004-numeros/004-numeros-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numeros/004-numeros-026.adoc#v4-26-0[Próximo Capítulo &#62;]