include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-23-1]]

^<<v4-23-1,1>>^ Então, Balaão disse a Balaque: “Construa aqui sete altares e prepare-me sete novilhos e sete carneiros.”

[[v4-23-2]]

^<<v4-23-2,2>>^ Balaque fez imediatamente como Balaão lhe tinha dito. Balaque e Balaão ofereceram um novilho e um carneiro em cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Balaão disse então a Balaque: “Fique aqui, junto à sua oferta queimada, enquanto eu vou até ali. Talvez Jeová entre em contacto comigo. Vou contar-lhe tudo o que ele me revelar.” Assim, ele foi a uma colina sem árvores.

[[v4-23-4]]

^<<v4-23-4,4>>^ Então, Deus entrou em contacto com Balaão, que lhe disse: “Preparei^&#42;1^ os sete altares e ofereci um novilho e um carneiro em cada altar.”

[NOTE]
====
. Ou: “Enfileirei”.
====

[[v4-23-5]]

^<<v4-23-5,5>>^ Jeová pôs as seguintes palavras na boca de Balaão: “Volta a Balaque, e isto é o que deves dizer.”

[[v4-23-6]]

^<<v4-23-6,6>>^ Por conseguinte, ele voltou e viu Balaque e todos os príncipes de Moabe de pé junto à sua oferta queimada.

[[v4-23-7]]

^<<v4-23-7,7>>^ Proferiu então a seguinte expressão proverbial:
“Balaque, rei de Moabe, trouxe-me desde Arã,
Desde as montanhas do Oriente:
‘Vem e amaldiçoa Jacó por mim.
Sim, vem para condenar Israel.’

[[v4-23-8]]

^<<v4-23-8,8>>^ Como poderia eu amaldiçoar aqueles a quem Deus não amaldiçoou?
E como poderia eu condenar aqueles a quem Jeová não condenou?

[[v4-23-9]]

^<<v4-23-9,9>>^ Vejo-os do cume das rochas,
E vejo-os das colinas.
São um povo que reside ali sozinho;
Não se incluem entre as nações.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem é que pode contar as partículas de pó de Jacó
Ou até a quarta parte de Israel?
Que eu^&#42;1^ morra a morte dos justos,
E que o meu fim seja igual ao deles.”

[NOTE]
====
. Ou: “a minha alma”.
====

[[v4-23-11]]

^<<v4-23-11,11>>^ Então, Balaque disse a Balaão: “O que é que me fizeste? Trouxe-te para amaldiçoar os meus inimigos, mas tu só os abençoaste.”

[[v4-23-12]]

^<<v4-23-12,12>>^ Ele respondeu: “Será que não devo dizer tudo o que Jeová põe na minha boca?”

[[v4-23-13]]

^<<v4-23-13,13>>^ Balaque disse-lhe: “Por favor, vem comigo a outro lugar de onde poderás vê-los. Verás apenas uma parte deles, não os verás a todos. Amaldiçoa-os por mim a partir de lá.”

[[v4-23-14]]

^<<v4-23-14,14>>^ Assim, Balaque levou-o ao campo de Zofim, no alto do Pisga, construiu sete altares e ofereceu um novilho e um carneiro em cada altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ Balaão disse então a Balaque: “Fique aqui junto à sua oferta queimada, enquanto eu entro ali em contacto com Ele.”

[[v4-23-16]]

^<<v4-23-16,16>>^ E Jeová entrou em contacto com Balaão e pôs-lhe a seguinte palavra na boca: “Volta a Balaque, e isto é o que deves dizer-lhe.”

[[v4-23-17]]

^<<v4-23-17,17>>^ Assim, foi até ele e viu-o à espera junto à sua oferta queimada, e os príncipes de Moabe estavam com ele. Balaque perguntou-lhe: “O que é que Jeová disse?”

[[v4-23-18]]

^<<v4-23-18,18>>^ Em resposta, ele proferiu a seguinte expressão proverbial:
“Prepare-se, Balaque, e escute.
Ouça-me, ó filho de Zipor.

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é um homem para mentir,
Nem um filho de homem para mudar de ideias.^&#42;1^
Quando ele diz algo, será que não o faz?
Quando ele fala, será que não o cumpre?

[NOTE]
====
. Ou: “lamentar”.
====

[[v4-23-20]]

^<<v4-23-20,20>>^ Veja! Fui trazido para abençoar;
Ele abençoou, e eu não posso mudar isso.

[[v4-23-21]]

^<<v4-23-21,21>>^ Ele não tolera nenhum poder mágico contra Jacó,
Nem permite qualquer desgraça contra Israel.
Jeová, seu Deus, está com eles,
E é aclamado como rei entre eles.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus está a trazê-los do Egito.
Ele é para eles como os chifres de um touro selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Pois contra Jacó não há maus presságios,^&#42;1^
Nem adivinhação contra Israel.
Agora, pode-se dizer a respeito de Jacó e Israel:
‘Vejam o que Deus fez!’

[NOTE]
====
. Ou: “sinais”.
====

[[v4-23-24]]

^<<v4-23-24,24>>^ Este é um povo que se levantará como um leão,
E, como o leão, irá erguer-se.
Não se deitará antes de comer uma presa
E de beber o sangue dos que foram mortos.”

[[v4-23-25]]

^<<v4-23-25,25>>^ Então, Balaque disse a Balaão: “Se não podes amaldiçoá-lo, também não deves abençoá-lo.”

[[v4-23-26]]

^<<v4-23-26,26>>^ Balaão respondeu a Balaque: “Eu não lhe disse que faria tudo o que Jeová dissesse?”

[[v4-23-27]]

^<<v4-23-27,27>>^ Balaque disse a Balaão: “Por favor, vem e deixa-me levar-te ainda a outro lugar. Talvez seja correto aos olhos do verdadeiro Deus que o amaldiçoes por mim, a partir dali.”

[[v4-23-28]]

^<<v4-23-28,28>>^ Assim, Balaque levou Balaão ao cume de Peor, de onde se avista Jesimom.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “o deserto”.
====

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse então a Balaque: “Construa aqui sete altares e prepare-me sete novilhos e sete carneiros.”

[[v4-23-30]]

^<<v4-23-30,30>>^ Portanto, Balaque fez exatamente como Balaão tinha dito e ofereceu um novilho e um carneiro em cada altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]