include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-11-1]]

^<<v4-11-1,1>>^ Então, o povo começou a queixar-se amargamente perante Jeová. Quando Jeová ouviu isso, acendeu-se a sua ira, e um fogo da parte de Jeová começou a arder entre eles e a consumir alguns nas extremidades do acampamento.

[[v4-11-2]]

^<<v4-11-2,2>>^ Quando o povo clamou a Moisés, ele suplicou a Jeová, e o fogo apagou-se.

[[v4-11-3]]

^<<v4-11-3,3>>^ Por isso, aquele lugar recebeu o nome de Taberá,^&#42;1^ porque se tinha acendido contra eles um fogo da parte de Jeová.

[NOTE]
====
. Que significa “queima”, isto é, uma conflagração; um incêndio.
====

[[v4-11-4]]

^<<v4-11-4,4>>^ Então, os estrangeiros^&#42;1^ que estavam no seu meio expressaram desejos egoístas, e os israelitas começaram a chorar novamente e a dizer: “Quem é que nos dará carne para comer?

[NOTE]
====
. Ou: “a multidão mista”. Aparentemente, refere-se aos não israelitas entre eles.
====

[[v4-11-5]]

^<<v4-11-5,5>>^ Sentimos tanta falta dos peixes que comíamos de graça no Egito, também dos pepinos, das melancias, dos alhos-porros, das cebolas e dos alhos!

[[v4-11-6]]

^<<v4-11-6,6>>^ Mas agora estamos^&#42;1^ a definhar. Não vemos nada a não ser maná.”

[NOTE]
====
. Ou: “as nossas almas estão”.
====

[[v4-11-7]]

^<<v4-11-7,7>>^ A propósito, o maná era como a semente de coentro e parecia resina bdélio.

[[v4-11-8]]

^<<v4-11-8,8>>^ O povo espalhava-se, apanhava-o e moía-o em moinhos manuais ou triturava-o num almofariz. Depois, cozinhavam-no em panelas ou faziam dele pães redondos; e tinha o sabor de um bolo feito com azeite.

[[v4-11-9]]

^<<v4-11-9,9>>^ Quando o orvalho se formava sobre o acampamento durante a noite, o maná também caía sobre ele.

[[v4-11-10]]

^<<v4-11-10,10>>^ Moisés ouviu todas as famílias do povo a chorar, cada homem à entrada da sua tenda. E Jeová ficou muito irado, e Moisés também ficou muito aborrecido.

[[v4-11-11]]

^<<v4-11-11,11>>^ Então, Moisés disse a Jeová: “Porque é que causaste aflição ao teu servo? Porque é que não achei favor aos teus olhos, de modo que puseste sobre mim o fardo de todo este povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Fui eu que concebi todo este povo? Fui eu que os dei à luz, de modo a que me digas: ‘Leva-os ao colo, assim como um servo^&#42;1^ carrega a criança de peito’, até à terra que juraste dar aos antepassados deles?

[NOTE]
====
. Ou: “aio”.
====

[[v4-11-13]]

^<<v4-11-13,13>>^ Onde é que eu vou encontrar carne para dar a todo este povo? Pois continuam a chorar diante de mim, dizendo: ‘Dá-nos carne para comer!’

[[v4-11-14]]

^<<v4-11-14,14>>^ Sozinho, não consigo suportar todo este povo; é demais para mim.

[[v4-11-15]]

^<<v4-11-15,15>>^ Se é assim que vais continuar a tratar-me, por favor, mata-me agora mesmo. Se achei favor aos teus olhos, não me faças ver mais nenhuma calamidade.”

[[v4-11-16]]

^<<v4-11-16,16>>^ Jeová disse a Moisés: “Reúne-me 70 homens dos anciãos de Israel, homens que reconheces como^&#42;1^ anciãos e oficiais do povo, leva-os à tenda de reunião e faz com que eles fiquem lá contigo.

[NOTE]
====
. Ou: “que sabes que são; que são conhecidos por ti como”.
====

[[v4-11-17]]

^<<v4-11-17,17>>^ Descerei e falarei ali contigo, tirarei um pouco do espírito que há sobre ti e irei colocá-lo sobre eles. E eles vão ajudar-te a levar o fardo do povo, para que não tenhas de levá-lo sozinho.

[[v4-11-18]]

^<<v4-11-18,18>>^ Deves dizer ao povo: ‘Santifiquem-se para amanhã, visto que certamente comerão carne, porque choraram aos ouvidos de Jeová e disseram: “Quem é que nos dará carne para comer? Estávamos melhor no Egito!” Jeová certamente vos dará carne e vocês comerão.

[[v4-11-19]]

^<<v4-11-19,19>>^ Hão de comer, não durante um dia, nem dois dias, nem cinco dias, nem dez dias, nem vinte dias,

[[v4-11-20]]

^<<v4-11-20,20>>^ mas durante um mês inteiro, até que vos saia pelas narinas e se torne algo nojento para vocês, pois rejeitaram a Jeová, que está no vosso meio, e choraram diante dele, dizendo: “Porque é que saímos do Egito?”’”

[[v4-11-21]]

^<<v4-11-21,21>>^ Então, Moisés disse: “Este povo, no meio do qual estou, são 600 000 homens a pé, e ainda assim dizes: ‘Vou dar-lhes carne suficiente para comerem durante um mês inteiro!’

[[v4-11-22]]

^<<v4-11-22,22>>^ Mesmo que se abatessem manadas e rebanhos inteiros, será que seria suficiente para eles? Ou, mesmo que todos os peixes do mar fossem apanhados, será que seria suficiente para eles?”

[[v4-11-23]]

^<<v4-11-23,23>>^ Jeová disse então a Moisés: “Será que a mão de Jeová é demasiado curta? Agora verás se o que eu digo vai ou não vai acontecer.”

[[v4-11-24]]

^<<v4-11-24,24>>^ Portanto, Moisés saiu e transmitiu ao povo as palavras de Jeová. E reuniu 70 homens dos anciãos do povo e fez com que eles ficassem à volta da tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ Jeová desceu então numa nuvem e falou com ele, e tirou um pouco do espírito que havia sobre ele e pô-lo sobre cada um dos 70 anciãos. E, assim que o espírito veio sobre eles, começaram a comportar-se como profetas,^&#42;1^ mas só o fizeram naquela vez.

[NOTE]
====
. Ou: “começaram a profetizar”.
====

[[v4-11-26]]

^<<v4-11-26,26>>^ Dois desses homens ainda estavam no acampamento. Chamavam-se Eldade e Medade. E o espírito veio sobre eles — encontravam-se entre os alistados, mas não tinham ido à tenda —, e começaram a comportar-se como profetas no acampamento.

[[v4-11-27]]

^<<v4-11-27,27>>^ E um jovem foi a correr e contou a Moisés: “Eldade e Medade estão a comportar-se como profetas no acampamento!”

[[v4-11-28]]

^<<v4-11-28,28>>^ Em vista disso, Josué, filho de Num, que desde jovem era ajudante de Moisés, disse: “Meu senhor Moisés, manda-os parar!”

[[v4-11-29]]

^<<v4-11-29,29>>^ No entanto, Moisés disse-lhe: “Eu não tenho ciúmes e tu é que os vais ter? Quem me dera que todo o povo de Jeová fosse profeta e que Jeová pusesse o seu espírito sobre eles!”

[[v4-11-30]]

^<<v4-11-30,30>>^ Mais tarde, Moisés voltou para o acampamento com os anciãos de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ Então, Jeová fez soprar um vento que começou a trazer codornizes desde o mar e a fazê-las cair à volta do acampamento, formando uma camada de cerca de dois côvados^&#42;1^ sobre o chão e cobrindo uma extensão de cerca de um dia de viagem para cada lado, à volta do acampamento.

[NOTE]
====
. Um côvado equivalia a 44,5 cm. Veja o Ap. B14.
====

[[v4-11-32]]

^<<v4-11-32,32>>^ Assim, o povo ficou acordado e recolheu as codornizes durante todo aquele dia, toda aquela noite e todo o dia seguinte. Ninguém recolheu menos de dez hómeres,^&#42;1^ e eles estendiam-nas à volta do acampamento.^&#42;2^

[NOTE]
====
. Um hómer equivalia a 220 l. Veja o Ap. B14.
. Talvez o tenham feito para secar a carne.
====

[[v4-11-33]]

^<<v4-11-33,33>>^ Contudo, enquanto a carne ainda estava entre os seus dentes, sem ter sido mastigada, acendeu-se a ira de Jeová contra o povo, e Jeová atingiu o povo com uma matança muito grande.

[[v4-11-34]]

^<<v4-11-34,34>>^ Assim, deram àquele lugar o nome de Quibrote-Ataavá,^&#42;1^ porque ali foram enterrados os que tiveram desejos egoístas.

[NOTE]
====
. Que significa “sepulturas do desejo”.
====

[[v4-11-35]]

^<<v4-11-35,35>>^ O povo partiu de Quibrote-Ataavá para Hazerote, e permaneceram em Hazerote.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]