include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-24-1]]

^<<v4-24-1,1>>^ Quando Balaão viu que Jeová se agradava em^&#42;1^ abençoar Israel, não se afastou novamente à procura de maus presságios,^&#42;2^ mas voltou o rosto para o deserto.

[NOTE]
====
. Lit.: “que era bom aos olhos de Jeová”.
. Ou: “sinais”.
====

[[v4-24-2]]

^<<v4-24-2,2>>^ E, quando Balaão levantou os olhos e viu Israel acampado segundo as suas tribos, veio sobre ele o espírito de Deus.

[[v4-24-3]]

^<<v4-24-3,3>>^ Proferiu então a seguinte expressão proverbial:
“A declaração de Balaão, filho de Beor,
A declaração de um homem cujos olhos foram abertos,

[[v4-24-4]]

^<<v4-24-4,4>>^ A declaração daquele que ouve as palavras de Deus,
Que teve uma visão do Todo-Poderoso,
Que se curvou com os olhos desvendados:

[[v4-24-5]]

^<<v4-24-5,5>>^ Como são belas as tuas tendas, ó Jacó,
As tuas barracas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Estendem-se como vales,^&#42;1^
Como jardins junto ao rio,
Como aloés plantados por Jeová,
Como cedros junto às águas.

[NOTE]
====
. Ou: “uádis”.
====

[[v4-24-7]]

^<<v4-24-7,7>>^ Água transborda dos seus dois baldes de couro,
E a sua semente^&#42;1^ está plantada junto a muitas águas.
Além disso, o seu rei será maior do que Agague,
E o seu reino será exaltado.

[NOTE]
====
. Ou: “descendência”.
====

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus está a trazê-lo do Egito;
Ele é para eles como os chifres de um touro selvagem.
Ele devorará as nações, os seus opressores,
Vai roer os seus ossos e parti-los com as suas flechas.

[[v4-24-9]]

^<<v4-24-9,9>>^ Ele agachou-se, deitou-se como um leão,
E, como no caso de um leão, quem é que se atreve a acordá-lo?
Os que o abençoam são abençoados,
E os que o amaldiçoam são amaldiçoados.”

[[v4-24-10]]

^<<v4-24-10,10>>^ Então, Balaque ficou furioso com Balaão. Balaque bateu palmas com desprezo e disse a Balaão: “Foi para amaldiçoar os meus inimigos que te chamei, mas, nestas três vezes, só os abençoaste.

[[v4-24-11]]

^<<v4-24-11,11>>^ Volta já para casa. Eu pretendia honrar-te grandemente, mas Jeová negou-te a honra.”

[[v4-24-12]]

^<<v4-24-12,12>>^ Balaão disse a Balaque: “Eu já tinha dito aos seus mensageiros:

[[v4-24-13]]

^<<v4-24-13,13>>^ ‘Mesmo que Balaque me desse a sua casa cheia de prata e ouro, por minha própria vontade,^&#42;1^ eu não poderia fazer coisa alguma, boa ou má, que fosse para além da ordem de Jeová. Eu direi apenas o que Jeová me transmitir’.

[NOTE]
====
. Lit.: “do meu coração”.
====

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora, vou-me embora para o meu povo. Mas, antes, deixe-me avisá-lo a respeito daquilo que este povo fará ao seu povo no futuro.”^&#42;1^

[NOTE]
====
. Ou: “no fim dos dias”.
====

[[v4-24-15]]

^<<v4-24-15,15>>^ Assim, proferiu a seguinte expressão proverbial:
“A declaração de Balaão, filho de Beor,
A declaração de um homem cujos olhos foram abertos,

[[v4-24-16]]

^<<v4-24-16,16>>^ A declaração daquele que ouve as palavras de Deus,
E daquele que tem o conhecimento do Altíssimo.
Ele teve uma visão do Todo-Poderoso,
Ao curvar-se com os olhos desvendados:

[[v4-24-17]]

^<<v4-24-17,17>>^ Vou vê-lo, mas não por agora;
Vou observá-lo, mas não em breve.
Uma estrela sairá de Jacó,
E vai levantar-se um cetro de Israel.
E ele certamente rachará a testa de Moabe^&#42;1^
E o crânio de todos os guerreiros violentos.

[NOTE]
====
. Ou: “as têmporas da cabeça de Moabe”.
====

[[v4-24-18]]

^<<v4-24-18,18>>^ E Edom vai tornar-se uma propriedade;
Sim, Seir, a propriedade dos seus inimigos,
Ao passo que Israel demonstrará a sua coragem.

[[v4-24-19]]

^<<v4-24-19,19>>^ E, da parte de Jacó, alguém dominará,
E destruirá qualquer sobrevivente da cidade.”

[[v4-24-20]]

^<<v4-24-20,20>>^ Quando olhou para Amaleque, continuou a sua expressão proverbial, dizendo:
“Amaleque foi a primeira das nações,
Mas, no final, sofrerá destruição.”

[[v4-24-21]]

^<<v4-24-21,21>>^ Quando olhou para os queneus, continuou a sua expressão proverbial, dizendo:
“Segura é a sua habitação, e firme no rochedo está a sua moradia.

[[v4-24-22]]

^<<v4-24-22,22>>^ Mas alguém consumirá os queneus^&#42;1^ com fogo.
Quando é que a Assíria vai levá-los cativos?”

[NOTE]
====
. Lit.: “Caim”.
====

[[v4-24-23]]

^<<v4-24-23,23>>^ E ele continuou a sua expressão proverbial, dizendo:
“Ai! Quem é que sobreviverá quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ Navios virão da costa de Quitim
E afligirão a Assíria,
E afligirão Éber.
Mas ele também será completamente destruído.”

[[v4-24-25]]

^<<v4-24-25,25>>^ Então, Balaão foi-se embora e voltou para o seu lugar. E Balaque também seguiu o seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]