include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-20-1]]

^<<v4-20-1,1>>^ No primeiro mês, toda a assembleia de Israel chegou ao deserto de Zim e passou a morar em Cades. Foi lá que Miriam morreu e foi enterrada.

[[v4-20-2]]

^<<v4-20-2,2>>^ Não havia água para a assembleia, e eles juntaram-se contra Moisés e Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ O povo discutia com Moisés, dizendo: “Quem nos dera que tivéssemos morrido quando os nossos irmãos morreram diante de Jeová!

[[v4-20-4]]

^<<v4-20-4,4>>^ Porque é que trouxeram a congregação de Jeová a este deserto, para que nós e os nossos animais morrêssemos aqui?

[[v4-20-5]]

^<<v4-20-5,5>>^ E porque é que nos tiraram do Egito e nos trouxeram a este lugar horrível? Não é um lugar para semear, nem é um lugar de figos, nem de videiras, nem de romãs, e não há água para beber.”

[[v4-20-6]]

^<<v4-20-6,6>>^ Moisés e Arão saíram então da presença da congregação. Foram à entrada da tenda de reunião e prostraram-se com o rosto por terra, e a glória de Jeová começou a aparecer-lhes.

[[v4-20-7]]

^<<v4-20-7,7>>^ Então, Jeová disse a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ “Pega no bastão e reúne a assembleia, tu e Arão, teu irmão, e falem ao rochedo diante dos olhos deles, para que saia água; e vocês tirarão água do rochedo e darão de beber ao povo e aos seus animais.”

[[v4-20-9]]

^<<v4-20-9,9>>^ Assim, Moisés pegou no bastão que estava perante Jeová, conforme ele lhe tinha ordenado.

[[v4-20-10]]

^<<v4-20-10,10>>^ Por conseguinte, Moisés e Arão convocaram a congregação para comparecer em frente ao rochedo, e ele disse-lhes: “Ouçam agora, rebeldes! Querem que façamos sair água deste rochedo para vocês?”

[[v4-20-11]]

^<<v4-20-11,11>>^ Nisto, Moisés ergueu a mão e golpeou o rochedo duas vezes com o seu bastão. Então, começou a jorrar muita água, e a assembleia e os seus animais começaram a beber.

[[v4-20-12]]

^<<v4-20-12,12>>^ Mais tarde, Jeová disse a Moisés e a Arão: “Visto que vocês não mostraram fé em mim e não me santificaram diante dos olhos do povo de Israel, não levarão esta congregação à terra que lhes darei.”

[[v4-20-13]]

^<<v4-20-13,13>>^ Estas são as águas de Meribá,^&#42;1^ onde os israelitas discutiram com Jeová, de modo que ele foi santificado entre eles.

[NOTE]
====
. Que significa “discussão”.
====

[[v4-20-14]]

^<<v4-20-14,14>>^ De seguida, Moisés enviou mensageiros ao rei de Edom, a partir de Cades, para lhe dizerem: “Assim diz o seu irmão Israel: ‘O senhor bem sabe de todas as dificuldades que passámos.

[[v4-20-15]]

^<<v4-20-15,15>>^ Os nossos antepassados foram para o Egito, e nós morámos no Egito por muitos anos;^&#42;1^ e os egípcios maltrataram-nos a nós e aos nossos antepassados.

[NOTE]
====
. Lit.: “dias”.
====

[[v4-20-16]]

^<<v4-20-16,16>>^ Por fim, clamámos a Jeová, e ele ouviu-nos, de modo que enviou um anjo e tirou-nos do Egito; e aqui estamos, em Cades, uma cidade na fronteira do seu território.

[[v4-20-17]]

^<<v4-20-17,17>>^ Por favor, deixe-nos passar pela sua terra. Não passaremos através de nenhum campo ou vinhedo nem beberemos água de nenhum poço. Iremos pela estrada real e não nos desviaremos nem para a direita nem para a esquerda, até termos passado pelo seu território.’”

[[v4-20-18]]

^<<v4-20-18,18>>^ No entanto, Edom disse-lhe: “Não podes passar pelo nosso território. Se o fizeres, irei ao teu encontro com a espada.”

[[v4-20-19]]

^<<v4-20-19,19>>^ Então, os israelitas disseram-lhe: “Iremos pela estrada e, se nós e o nosso gado bebermos da sua água, pagaremos por ela. Apenas queremos passar a pé, nada mais.”

[[v4-20-20]]

^<<v4-20-20,20>>^ Contudo, ele disse: “Não podes passar.” Com isso, Edom saiu ao encontro dele com um exército grande e poderoso.^&#42;1^

[NOTE]
====
. Lit.: “com povo pesado e mão forte”.
====

[[v4-20-21]]

^<<v4-20-21,21>>^ Assim, Edom não permitiu que Israel passasse pelo seu território. Portanto, Israel desviou-se dele.

[[v4-20-22]]

^<<v4-20-22,22>>^ Toda a assembleia dos israelitas partiu de Cades e chegou ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ Jeová disse então o seguinte a Moisés e a Arão no monte Hor, na fronteira da terra de Edom:

[[v4-20-24]]

^<<v4-20-24,24>>^ “Arão irá juntar-se ao seu povo.^&#42;1^ Não entrará na terra que darei aos israelitas, porque vocês se rebelaram contra a minha ordem no que diz respeito às águas de Meribá.

[NOTE]
====
. Expressão poética que se refere à morte.
====

[[v4-20-25]]

^<<v4-20-25,25>>^ Leva Arão e Eleazar, seu filho, para cima, ao monte Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ Tira as vestes de Arão e põe-nas em Eleazar, seu filho; e Arão morrerá ali.”^&#42;1^

[NOTE]
====
. Lit.: “será reunido e morrerá ali”.
====

[[v4-20-27]]

^<<v4-20-27,27>>^ Portanto, Moisés fez exatamente como Jeová tinha ordenado. Eles subiram ao monte Hor diante dos olhos de toda a assembleia.

[[v4-20-28]]

^<<v4-20-28,28>>^ Moisés tirou então as vestes de Arão e vestiu-as a Eleazar, filho deste. Depois, Arão morreu ali no cume do monte. E Moisés e Eleazar desceram do monte.

[[v4-20-29]]

^<<v4-20-29,29>>^ Quando toda a assembleia viu que Arão tinha morrido, toda a casa de Israel chorou por Arão durante 30 dias.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]