include::./index.adoc[]

[[v4-8-0]]
=== Números, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-8-1]]

^<<v4-8-1,1>>^ Jeová disse a Moisés:

[[v4-8-2]]

^<<v4-8-2,2>>^ “Diz a Arão: ‘Quando acenderes as lâmpadas, as sete lâmpadas devem iluminar a área à frente do candelabro.’”

[[v4-8-3]]

^<<v4-8-3,3>>^ Então, Arão fez o seguinte: acendeu as lâmpadas para iluminar a área à frente do candelabro, assim como Jeová tinha ordenado a Moisés.

[[v4-8-4]]

^<<v4-8-4,4>>^ O candelabro era feito de ouro batido a martelo; da haste até às flores, era feito de ouro batido a martelo. O candelabro foi feito segundo o que Jeová tinha mostrado a Moisés na visão.

[[v4-8-5]]

^<<v4-8-5,5>>^ Jeová disse ainda a Moisés:

[[v4-8-6]]

^<<v4-8-6,6>>^ “Separa os levitas dentre os israelitas e purifica-os.

[[v4-8-7]]

^<<v4-8-7,7>>^ É assim que deves purificá-los: Faz aspersão da água purificadora do pecado sobre eles, e eles devem rapar o corpo inteiro com uma navalha, lavar as suas roupas e purificar-se.

[[v4-8-8]]

^<<v4-8-8,8>>^ Então, eles pegarão num novilho e na correspondente oferta de cereais de farinha fina misturada com azeite, e tu pegarás noutro novilho como oferta pelo pecado.

[[v4-8-9]]

^<<v4-8-9,9>>^ E deves apresentar os levitas diante da tenda de reunião e reunir toda a assembleia de Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ Quando apresentares os levitas perante Jeová, os israelitas devem pôr as mãos sobre os levitas.

[[v4-8-11]]

^<<v4-8-11,11>>^ E Arão oferecerá^&#42;1^ os levitas perante Jeová como uma oferta movida dos israelitas, e os levitas realizarão o serviço de Jeová.

[NOTE]
====
. Lit.: “moverá”, isto é, fará mover para a frente e para trás.
====

[[v4-8-12]]

^<<v4-8-12,12>>^ “Então, os levitas porão as mãos sobre a cabeça dos novilhos. Depois, oferecerão um deles como oferta pelo pecado e o outro como oferta queimada a Jeová, a fim de fazer expiação pelos levitas.

[[v4-8-13]]

^<<v4-8-13,13>>^ Deves fazer com que os levitas fiquem diante de Arão e dos seus filhos, e oferecê-los^&#42;1^ como oferta movida a Jeová.

[NOTE]
====
. Lit.: “movê-los”, isto é, fazê-los mover para a frente e para trás.
====

[[v4-8-14]]

^<<v4-8-14,14>>^ Deves separar os levitas dentre os israelitas, e os levitas passarão a pertencer-me.

[[v4-8-15]]

^<<v4-8-15,15>>^ Depois, os levitas entrarão para servir junto à tenda de reunião. É assim que deves purificá-los e oferecê-los^&#42;1^ como oferta movida.

[NOTE]
====
. Lit.: “movê-los”, isto é, fazê-los mover para a frente e para trás.
====

[[v4-8-16]]

^<<v4-8-16,16>>^ Pois eles são os que me foram dados como dádivas dentre os israelitas. Vou tomá-los para mim em vez de todos os primogénitos^&#42;1^ dos israelitas.

[NOTE]
====
. Ou: “todos os primogénitos que abrem o ventre”.
====

[[v4-8-17]]

^<<v4-8-17,17>>^ Pois todo o primogénito dos israelitas, tanto de homens como de animais, é meu. Santifiquei-os para mim no dia em que matei todos os primogénitos na terra do Egito.

[[v4-8-18]]

^<<v4-8-18,18>>^ Tomarei os levitas em vez de todos os primogénitos dos israelitas.

[[v4-8-19]]

^<<v4-8-19,19>>^ Darei os levitas a Arão e aos seus filhos como dádivas dentre os israelitas, para realizarem o serviço em benefício dos israelitas na tenda de reunião e fazerem expiação por eles, para que não ocorra nenhuma praga entre os israelitas se o povo de Israel se aproximar do lugar santo.”

[[v4-8-20]]

^<<v4-8-20,20>>^ Moisés, Arão e toda a assembleia de Israel assim fizeram com os levitas. Os israelitas fizeram com os levitas tudo o que Jeová tinha ordenado a Moisés em relação aos levitas.

[[v4-8-21]]

^<<v4-8-21,21>>^ Portanto, os levitas purificaram-se e lavaram as suas roupas. Depois, Arão ofereceu-os^&#42;1^ como oferta movida perante Jeová. Arão fez então expiação por eles, para purificá-los.

[NOTE]
====
. Lit.: “moveu-os”, isto é, fê-los mover para a frente e para trás.
====

[[v4-8-22]]

^<<v4-8-22,22>>^ Depois, os levitas entraram para realizar o seu serviço na tenda de reunião diante de Arão e dos seus filhos. Assim como Jeová tinha ordenado a Moisés em relação aos levitas, assim fizeram com eles.

[[v4-8-23]]

^<<v4-8-23,23>>^ Jeová disse então a Moisés:

[[v4-8-24]]

^<<v4-8-24,24>>^ “Isto aplica-se aos levitas: dos 25 anos de idade para cima, um homem irá juntar-se ao grupo dos que servem na tenda de reunião.

[[v4-8-25]]

^<<v4-8-25,25>>^ Contudo, depois dos 50 anos de idade, ele irá retirar-se do grupo de serviço e não fará mais nenhum serviço.

[[v4-8-26]]

^<<v4-8-26,26>>^ Ele pode servir os seus irmãos, que cuidam das responsabilidades na tenda de reunião, mas não deve fazer lá nenhum serviço. É assim que deves fazer em relação aos levitas e às suas responsabilidades.”

'''

xref:004-numeros/004-numeros-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numeros/004-numeros-009.adoc#v4-9-0[Próximo Capítulo &#62;]