include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-4-1]]

^<<v4-4-1,1>>^ Jeová disse então a Moisés e a Arão:

[[v4-4-2]]

^<<v4-4-2,2>>^ “Deve-se fazer um recenseamento dos filhos de Coate dentre os filhos de Levi, segundo as suas famílias e segundo as suas casas paternas,

[[v4-4-3]]

^<<v4-4-3,3>>^ de todos os que têm entre 30 e 50 anos de idade e que fazem parte do grupo designado para trabalhar na tenda de reunião.

[[v4-4-4]]

^<<v4-4-4,4>>^ “Este é o serviço dos filhos de Coate na tenda de reunião. É algo santíssimo.

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando o acampamento estiver prestes a partir, Arão e os seus filhos entrarão, tirarão a cortina de separação e cobrirão a Arca do Testemunho com ela.

[[v4-4-6]]

^<<v4-4-6,6>>^ Porão sobre ela uma cobertura de pele de foca, estenderão por cima um pano azul e irão colocar-lhe os varais para carregá-la.

[[v4-4-7]]

^<<v4-4-7,7>>^ “Também estenderão um pano azul sobre a mesa dos pães da proposição e porão sobre ela os pratos, as taças, as tigelas e as jarras das ofertas de bebida; os pães que são oferecidos regularmente devem permanecer sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Estenderão um pano escarlate sobre eles, porão sobre a mesa uma cobertura de pele de foca e irão colocar-lhe os varais para carregá-la.

[[v4-4-9]]

^<<v4-4-9,9>>^ Depois, pegarão num pano azul e cobrirão o candelabro usado para iluminação, e também as lâmpadas, os apagadores,^&#42;1^ os braseiros e todos os recipientes de óleo usados para mantê-lo aceso.

[NOTE]
====
. Ou: “as tenazes”.
====

[[v4-4-10]]

^<<v4-4-10,10>>^ Embrulharão o candelabro e todos os seus utensílios numa cobertura de pele de foca, e irão colocá-lo numa barra para ser carregado.

[[v4-4-11]]

^<<v4-4-11,11>>^ E estenderão um pano azul sobre o altar de ouro, porão sobre ele uma cobertura de pele de foca e irão colocar-lhe os varais para carregá-lo.

[[v4-4-12]]

^<<v4-4-12,12>>^ Então, pegarão em todos os utensílios que usam regularmente quando servem no lugar santo e irão colocá-los num pano azul; porão uma cobertura de pele de foca sobre eles e irão colocá-los numa barra para serem carregados.

[[v4-4-13]]

^<<v4-4-13,13>>^ “Devem retirar as cinzas^&#42;1^ do altar e estender sobre ele um pano de lã roxa.

[NOTE]
====
. Ou: “cinzas gordurosas”, isto é, cinzas impregnadas da gordura dos sacrifícios.
====

[[v4-4-14]]

^<<v4-4-14,14>>^ Porão sobre ele todos os utensílios que usam ao servir junto ao altar: os braseiros, os garfos, as pás e as tigelas — todos os utensílios do altar. E devem estender sobre ele uma cobertura de pele de foca e colocar nele os varais para carregá-lo.

[[v4-4-15]]

^<<v4-4-15,15>>^ “Quando o acampamento estiver prestes a partir, Arão e os seus filhos terminarão de cobrir o lugar santo e todo o equipamento do lugar santo. Então, os filhos de Coate entrarão para carregá-los, mas não devem tocar nas coisas do lugar santo, senão morrerão. Esta é a responsabilidade^&#42;1^ dos filhos de Coate em relação à tenda de reunião.

[NOTE]
====
. Lit.: “carga”.
====

[[v4-4-16]]

^<<v4-4-16,16>>^ “Eleazar, filho de Arão, o sacerdote, é responsável por supervisionar o óleo de iluminação, o incenso perfumado, a oferta de cereais que é feita regularmente e o óleo de unção. Ele supervisiona todo o tabernáculo e tudo o que há nele, incluindo o lugar santo e os seus utensílios.”

[[v4-4-17]]

^<<v4-4-17,17>>^ Jeová disse ainda a Moisés e a Arão:

[[v4-4-18]]

^<<v4-4-18,18>>^ “Não deixem a tribo das famílias dos coatitas ser eliminada dentre os levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ No entanto, façam-lhes o seguinte, de modo a que continuem vivos e não morram por se aproximarem das coisas santíssimas: Arão e os seus filhos entrarão e designarão a cada um deles o seu serviço e as coisas que cada um deles carregará.

[[v4-4-20]]

^<<v4-4-20,20>>^ Eles não devem entrar e ver as coisas sagradas nem por um instante, senão morrerão.”

[[v4-4-21]]

^<<v4-4-21,21>>^ Jeová disse então a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ “Deve-se fazer um recenseamento dos filhos de Gérson, segundo as suas casas paternas e as suas famílias.

[[v4-4-23]]

^<<v4-4-23,23>>^ Deves registar todos os que têm entre 30 e 50 anos de idade e que fazem parte do grupo designado para servir na tenda de reunião.

[[v4-4-24]]

^<<v4-4-24,24>>^ Isto é o que as famílias dos gersonitas estão designadas para fazer e para carregar:

[[v4-4-25]]

^<<v4-4-25,25>>^ carregarão os panos do tabernáculo, a tenda de reunião, a sua cobertura e a cobertura de pele de foca que há por cima dela, a cortina^&#42;1^ da entrada da tenda de reunião,

[NOTE]
====
. Ou: “o reposteiro”.
====

[[v4-4-26]]

^<<v4-4-26,26>>^ os cortinados do pátio, a cortina^&#42;1^ da entrada do pátio que cerca o tabernáculo e o altar, as suas cordas de fixação, todos os seus utensílios e tudo o que é usado nesse serviço. Esta é a sua designação.

[NOTE]
====
. Ou: “o reposteiro”.
====

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o serviço dos gersonitas e tudo o que eles tiverem de carregar deve ser supervisionado por Arão e pelos seus filhos. Designarão como responsabilidade deles todas estas coisas que eles terão de carregar.

[[v4-4-28]]

^<<v4-4-28,28>>^ Este é o serviço que as famílias dos gersonitas devem realizar na tenda de reunião; e as suas responsabilidades estão sob a direção de Itamar, filho de Arão, o sacerdote.

[[v4-4-29]]

^<<v4-4-29,29>>^ “Quanto aos filhos de Merari, deves registá-los segundo as suas famílias e segundo a sua casa paterna.

[[v4-4-30]]

^<<v4-4-30,30>>^ Registarás os que têm entre 30 e 50 anos de idade, todos os que fazem parte do grupo designado para servir na tenda de reunião.

[[v4-4-31]]

^<<v4-4-31,31>>^ Isto é o que eles têm a responsabilidade de carregar como seu serviço na tenda de reunião: as armações do tabernáculo, as suas travessas, as suas colunas, as suas bases com encaixe;

[[v4-4-32]]

^<<v4-4-32,32>>^ as colunas do pátio ao redor, as suas bases com encaixe, as suas estacas e as suas cordas de fixação com todo o seu equipamento e tudo o que está relacionado com esse serviço. E vocês irão designar-lhes por nome o equipamento que eles têm a responsabilidade de carregar.

[[v4-4-33]]

^<<v4-4-33,33>>^ É assim que as famílias dos filhos de Merari devem servir na tenda de reunião, sob a direção de Itamar, filho de Arão, o sacerdote.”

[[v4-4-34]]

^<<v4-4-34,34>>^ Então, Moisés, Arão e os maiorais da assembleia registaram os filhos dos coatitas segundo as suas famílias e segundo a sua casa paterna,

[[v4-4-35]]

^<<v4-4-35,35>>^ todos os que tinham entre 30 e 50 anos de idade e que faziam parte do grupo designado para servir na tenda de reunião.

[[v4-4-36]]

^<<v4-4-36,36>>^ O total dos registados segundo as suas famílias foi de 2750.

[[v4-4-37]]

^<<v4-4-37,37>>^ Estes foram os registados das famílias dos coatitas, todos os que serviam na tenda de reunião. Moisés e Arão registaram-nos segundo a ordem de Jeová dada por meio de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Os filhos de Gérson foram registados segundo as suas famílias e segundo a sua casa paterna,

[[v4-4-39]]

^<<v4-4-39,39>>^ todos os que tinham entre 30 e 50 anos de idade e que faziam parte do grupo designado para servir na tenda de reunião.

[[v4-4-40]]

^<<v4-4-40,40>>^ O total dos registados segundo as suas famílias e segundo a sua casa paterna foi de 2630.

[[v4-4-41]]

^<<v4-4-41,41>>^ Este foi o registo das famílias dos filhos de Gérson, todos os que serviam na tenda de reunião. Moisés e Arão registaram-nos segundo a ordem de Jeová.

[[v4-4-42]]

^<<v4-4-42,42>>^ Os filhos de Merari foram registados segundo as suas famílias e segundo a sua casa paterna,

[[v4-4-43]]

^<<v4-4-43,43>>^ todos os que tinham entre 30 e 50 anos de idade que faziam parte do grupo designado para servir na tenda de reunião.

[[v4-4-44]]

^<<v4-4-44,44>>^ O total dos seus registados segundo as suas famílias foi de 3200.

[[v4-4-45]]

^<<v4-4-45,45>>^ Este foi o registo das famílias dos filhos de Merari, os quais Moisés e Arão registaram segundo a ordem de Jeová dada por meio de Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Moisés, Arão e os maiorais de Israel registaram todos estes levitas segundo as suas famílias e segundo as suas casas paternas;

[[v4-4-47]]

^<<v4-4-47,47>>^ eles tinham entre 30 e 50 anos de idade, e todos foram designados para prestar serviço e carregar as coisas relacionadas com a tenda de reunião.

[[v4-4-48]]

^<<v4-4-48,48>>^ O total dos registados foi de 8580.

[[v4-4-49]]

^<<v4-4-49,49>>^ Foram registados segundo a ordem de Jeová dada por meio de Moisés, cada um segundo o seu serviço designado e o que devia carregar; foram registados assim como Jeová tinha ordenado a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]