include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-16-1]]

^<<v4-16-1,1>>^ Então, Corá, filho de Izar, filho de Coate, filho de Levi, juntou-se a Datã e Abirão, filhos de Eliabe, e a Om, filho de Pelete, dos filhos de Rúben.

[[v4-16-2]]

^<<v4-16-2,2>>^ Eles levantaram-se contra Moisés, juntamente com 250 israelitas, maiorais da assembleia, escolhidos da congregação, homens de destaque.

[[v4-16-3]]

^<<v4-16-3,3>>^ Uniram-se, portanto, contra Moisés e Arão, e disseram-lhes: “Estamos fartos de vocês! Toda a assembleia é santa, todos eles, e Jeová está no seu meio. Então, porque é que vocês se deviam colocar acima da congregação de Jeová?”

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando Moisés ouviu isto, prostrou-se imediatamente com o rosto por terra.

[[v4-16-5]]

^<<v4-16-5,5>>^ De seguida, ele disse a Corá e a todos os que o apoiavam: “Pela manhã, Jeová mostrará quem lhe pertence, e quem é santo, e quem se deve aproximar dele. Aquele que ele escolher há de se aproximar dele.

[[v4-16-6]]

^<<v4-16-6,6>>^ Façam o seguinte, Corá e todos os que o apoiam: Peguem em incensários

[[v4-16-7]]

^<<v4-16-7,7>>^ e amanhã ponham-lhes brasas e incenso perante Jeová; e o homem que Jeová escolher é o santo. Vocês foram longe demais, filhos de Levi!”

[[v4-16-8]]

^<<v4-16-8,8>>^ Depois, Moisés disse a Corá: “Escutem, por favor, filhos de Levi.

[[v4-16-9]]

^<<v4-16-9,9>>^ Acham pouco que o Deus de Israel vos tenha separado dentre a assembleia de Israel e que vos tenha permitido aproximar-se dele para executar o serviço do tabernáculo de Jeová e ficar diante do povo para servi-los?

[[v4-16-10]]

^<<v4-16-10,10>>^ Ele fez com que te aproximasses dele com todos os teus irmãos, os filhos de Levi. Agora, vocês querem também obter o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ Por esta razão, tu e todos os que te apoiam, que se encontram reunidos, estão contra Jeová. Quanto a Arão, quem é ele para que se queixem contra ele?”

[[v4-16-12]]

^<<v4-16-12,12>>^ Mais tarde, Moisés mandou chamar Datã e Abirão, filhos de Eliabe, mas eles disseram: “Não iremos!

[[v4-16-13]]

^<<v4-16-13,13>>^ Achas pouco que nos tenhas tirado de uma terra que mana leite e mel para nos fazer morrer no deserto? Agora, queres também ser um governante supremo sobre nós?^&#42;1^

[NOTE]
====
. Ou: “queres dominar sobre nós”.
====

[[v4-16-14]]

^<<v4-16-14,14>>^ O facto é que não nos trouxeste a uma terra que mana leite e mel, nem nos deste campos e vinhas como herança. Queres cegar os olhos destes homens? Não iremos!”

[[v4-16-15]]

^<<v4-16-15,15>>^ Então, Moisés ficou muito furioso e disse a Jeová: “Não olhes para a oferta de cereais deles. Não lhes tirei um único jumento, nem os prejudiquei, a nenhum deles.”

[[v4-16-16]]

^<<v4-16-16,16>>^ Seguidamente, Moisés disse a Corá: “Comparece amanhã perante Jeová com todos os que te apoiam. Tu, eles e Arão devem comparecer.

[[v4-16-17]]

^<<v4-16-17,17>>^ Cada um deve pegar no seu incensário e colocar-lhe incenso, e cada um apresentará o seu incensário — 250 incensários — perante Jeová, juntamente contigo e com Arão, cada um com o seu incensário.”

[[v4-16-18]]

^<<v4-16-18,18>>^ Assim, cada um pegou no seu incensário, pôs-lhe brasas e incenso, e ficaram de pé à entrada da tenda de reunião, com Moisés e Arão.

[[v4-16-19]]

^<<v4-16-19,19>>^ Corá reuniu contra eles todos os que o apoiavam, à entrada da tenda de reunião. Foi então que a glória de Jeová apareceu a toda a assembleia.

[[v4-16-20]]

^<<v4-16-20,20>>^ Portanto, Jeová disse a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ “Separem-se deste grupo, para que eu os extermine num instante.”

[[v4-16-22]]

^<<v4-16-22,22>>^ Em vista disso, prostraram-se com o rosto por terra e disseram: “Ó Deus, o Deus do espírito de todas as pessoas,^&#42;1^ ficarás indignado com toda a assembleia por causa do pecado de um só homem?”

[NOTE]
====
. Lit.: “dos espíritos de toda a carne”.
====

[[v4-16-23]]

^<<v4-16-23,23>>^ Então, Jeová disse a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ “Diz à assembleia: ‘Afastem-se das tendas de Corá, Datã e Abirão!’”

[[v4-16-25]]

^<<v4-16-25,25>>^ De seguida, Moisés levantou-se e foi até Datã e Abirão; e os anciãos de Israel foram com ele.

[[v4-16-26]]

^<<v4-16-26,26>>^ Moisés disse à assembleia: “Por favor, afastem-se das tendas destes homens maus e não toquem em nada que lhes pertença, para que não sejam destruídos por causa do pecado deles.”

[[v4-16-27]]

^<<v4-16-27,27>>^ Eles afastaram-se imediatamente das tendas de Corá, Datã e Abirão. E Datã e Abirão saíram das suas tendas e ficaram à entrada, com as suas esposas, os seus filhos e as suas crianças.

[[v4-16-28]]

^<<v4-16-28,28>>^ Moisés disse então: “Será do seguinte modo que vocês ficarão a saber que foi Jeová quem me enviou para realizar todas estas coisas e que elas não procedem do meu coração:^&#42;1^

[NOTE]
====
. Ou: “da minha própria iniciativa”.
====

[[v4-16-29]]

^<<v4-16-29,29>>^ Se estes tiverem uma morte natural, assim como todos os homens, e se a punição que sofrerem for a mesma de todos os homens, não foi Jeová que me enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Contudo, se Jeová fizer algo extraordinário com eles, e a terra se abrir^&#42;1^ e os engolir a eles e a tudo o que lhes pertence, e eles descerem vivos à Sepultura,^&#42;2^ vocês certamente saberão que estes homens trataram a Jeová sem respeito.”

[NOTE]
====
. Lit.: “abrir a sua boca”.
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v4-16-31]]

^<<v4-16-31,31>>^ Assim que ele acabou de dizer todas estas palavras, abriu-se o chão debaixo deles.

[[v4-16-32]]

^<<v4-16-32,32>>^ A terra abriu-se^&#42;1^ e engoliu-os, juntamente com os das suas casas, todos os que pertenciam a Corá e todos os seus bens.

[NOTE]
====
. Lit.: “abriu a sua boca”.
====

[[v4-16-33]]

^<<v4-16-33,33>>^ Assim, eles e todos os que lhes pertenciam desceram vivos à Sepultura,^&#42;1^ e a terra cobriu-os, de modo que desapareceram do meio da congregação.

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v4-16-34]]

^<<v4-16-34,34>>^ Perante os seus gritos, todos os israelitas ao seu redor fugiram, dizendo: “Temos medo de que a terra também nos engula!”

[[v4-16-35]]

^<<v4-16-35,35>>^ Saiu então fogo da parte de Jeová e consumiu os 250 homens que ofereciam incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ Assim, Jeová disse a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ “Diz a Eleazar, filho de Arão, o sacerdote, que retire os incensários do fogo, porque são sagrados. Diz-lhe também que espalhe as cinzas longe dali.

[[v4-16-38]]

^<<v4-16-38,38>>^ Os incensários dos homens que pecaram, pagando com as suas próprias vidas,^&#42;1^ devem ser transformados em lâminas de metal para revestir o altar, porque foram apresentados perante Jeová e tornaram-se sagrados. Devem servir de sinal para os israelitas.”

[NOTE]
====
. Ou: “pecaram contra as suas próprias almas”.
====

[[v4-16-39]]

^<<v4-16-39,39>>^ Portanto, Eleazar, o sacerdote, pegou nos incensários de cobre, apresentados por aqueles que foram queimados, e transformou-os em lâminas para revestir o altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ conforme Jeová lhe tinha ordenado por meio de Moisés. Isso servia de recordação para os israelitas de que nenhuma pessoa não autorizada,^&#42;1^ que não fosse da descendência de Arão, se devia aproximar para queimar incenso perante Jeová, e de que ninguém se devia tornar igual a Corá e aos que o apoiavam.

[NOTE]
====
. Lit.: “nenhum estranho”.
====

[[v4-16-41]]

^<<v4-16-41,41>>^ Logo no dia seguinte, toda a assembleia de Israel começou a queixar-se contra Moisés e Arão, dizendo: “Foram vocês os dois que mataram o povo de Jeová.”

[[v4-16-42]]

^<<v4-16-42,42>>^ Quando a assembleia se ajuntou contra Moisés e Arão, olharam para a tenda de reunião e viram que a nuvem a tinha coberto, e a glória de Jeová começou a aparecer.

[[v4-16-43]]

^<<v4-16-43,43>>^ Moisés e Arão foram para a frente da tenda de reunião,

[[v4-16-44]]

^<<v4-16-44,44>>^ e Jeová disse a Moisés:

[[v4-16-45]]

^<<v4-16-45,45>>^ “Saiam do meio desta assembleia, para que eu os extermine num instante.” Em vista disso, prostraram-se com o rosto por terra.

[[v4-16-46]]

^<<v4-16-46,46>>^ Moisés disse então a Arão: “Pega no incensário e põe-lhe brasas do altar e incenso, e vai depressa à assembleia e faz expiação por eles, porque Jeová ficou indignado. A praga já começou!”

[[v4-16-47]]

^<<v4-16-47,47>>^ Arão pegou imediatamente no incensário, de acordo com o que Moisés tinha dito, e correu para o meio da congregação, mas a praga já tinha começado entre o povo. Pôs assim o incenso no incensário e começou a fazer expiação pelo povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ Ficou de pé entre os mortos e os vivos, e o flagelo finalmente parou.

[[v4-16-49]]

^<<v4-16-49,49>>^ Os que morreram por causa do flagelo foram 14 700, além dos que morreram por causa de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ Quando Arão, por fim, voltou a Moisés, à entrada da tenda de reunião, o flagelo tinha parado.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]