include::./index.adoc[]

[[v4-21-0]]
=== Números, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v4-21-1]]

^<<v4-21-1,1>>^ Quando o rei cananeu de Arade, que morava no Neguebe, ouviu que Israel tinha vindo pelo caminho de Atarim, atacou Israel e levou alguns deles cativos.

[[v4-21-2]]

^<<v4-21-2,2>>^ Assim, Israel fez o seguinte voto a Jeová: “Se tu entregares este povo nas minhas mãos, sem falta, entregarei as suas cidades à destruição.”^&#42;1^

[NOTE]
====
. Ou: “devotarei as suas cidades à destruição”. Veja o Glossário.
====

[[v4-21-3]]

^<<v4-21-3,3>>^ Por conseguinte, Jeová ouviu a voz de Israel e entregou-lhes os cananeus, e Israel destruiu-os,^&#42;1^ tanto a eles como às suas cidades. Por isso, aquele lugar passou a chamar-se Hormá.^&#42;2^

[NOTE]
====
. Ou: “devotou-os à destruição”. Veja o Glossário.
. Que significa “devotamento à destruição”.
====

[[v4-21-4]]

^<<v4-21-4,4>>^ Enquanto continuavam a viagem, depois de terem partido do monte Hor pelo caminho do mar Vermelho para contornar a terra de Edom, o povo ficou cansado^&#42;1^ da viagem.

[NOTE]
====
. Ou: “a alma do povo ficou cansada”.
====

[[v4-21-5]]

^<<v4-21-5,5>>^ E o povo falava contra Deus e Moisés: “Porque é que nos tiraram do Egito para morrermos no deserto? Aqui não há comida nem água, e nós detestamos^&#42;1^ este pão desprezível.”

[NOTE]
====
. Ou: “as nossas almas abominam”.
====

[[v4-21-6]]

^<<v4-21-6,6>>^ Então, Jeová enviou serpentes venenosas^&#42;1^ contra o povo e elas picaram-nos, de modo que muitos israelitas morreram.

[NOTE]
====
. Ou: “ardentes”.
====

[[v4-21-7]]

^<<v4-21-7,7>>^ De seguida, o povo foi ter com Moisés e disse: “Pecámos ao falar contra Jeová e contra ti. Intercede junto de Jeová para que tire as serpentes do nosso meio.” E Moisés intercedeu pelo povo.

[[v4-21-8]]

^<<v4-21-8,8>>^ Por conseguinte, Jeová disse a Moisés: “Faz uma réplica de uma cobra venenosa^&#42;1^ e coloca-a num poste. Quando alguém for picado, terá de olhar para ela de modo a permanecer vivo.”

[NOTE]
====
. Ou: “ardente”.
====

[[v4-21-9]]

^<<v4-21-9,9>>^ Moisés fez imediatamente uma serpente de cobre e colocou-a num poste; e, sempre que uma serpente picava um homem e ele olhava para a serpente de cobre, continuava vivo.

[[v4-21-10]]

^<<v4-21-10,10>>^ Depois, os israelitas partiram e acamparam em Obote.

[[v4-21-11]]

^<<v4-21-11,11>>^ Partiram então de Obote e acamparam em Ijé-Abarim, no deserto que fica em frente a Moabe, ao leste.

[[v4-21-12]]

^<<v4-21-12,12>>^ Partiram dali e acamparam junto ao vale^&#42;1^ de Zerede.

[NOTE]
====
. Ou: “uádi”.
====

[[v4-21-13]]

^<<v4-21-13,13>>^ De seguida, partiram e acamparam na região do Arnom, que fica no deserto que se estende desde a fronteira dos amorreus, pois o Arnom é o limite do território de Moabe, entre Moabe e os amorreus.

[[v4-21-14]]

^<<v4-21-14,14>>^ É por isso que o Livro das Guerras de Jeová menciona: “Vaebe, em Sufá, os vales^&#42;1^ do Arnom

[NOTE]
====
. Ou: “uádis”.
====

[[v4-21-15]]

^<<v4-21-15,15>>^ e a descida^&#42;1^ dos vales,^&#42;2^ que vai em direção à cidade de Ar e fica ao lado da fronteira de Moabe.”

[NOTE]
====
. Lit.: “boca”.
. Ou: “uádis”.
====

[[v4-21-16]]

^<<v4-21-16,16>>^ A seguir, foram para Beer. Este é o poço a respeito do qual Jeová disse a Moisés: “Ajunta o povo para que eu lhes dê água.”

[[v4-21-17]]

^<<v4-21-17,17>>^ Naquele tempo, Israel cantou o seguinte cântico:
“Brota água, ó poço! Respondam-lhe!^&#42;1^

[NOTE]
====
. Ou: “Cantem para ele!”
====

[[v4-21-18]]

^<<v4-21-18,18>>^ O poço que príncipes cavaram, que nobres do povo escavaram,
Com um bastão de governante e com os seus próprios bastões.”
Então, foram do deserto para Mataná,

[[v4-21-19]]

^<<v4-21-19,19>>^ de Mataná para Naaliel, e de Naaliel para Bamote.

[[v4-21-20]]

^<<v4-21-20,20>>^ Foram de Bamote para o vale que fica no território^&#42;1^ de Moabe, no alto do Pisga, de onde se avista Jesimom.^&#42;2^

[NOTE]
====
. Lit.: “campo”.
. Ou, possivelmente: “o deserto”.
====

[[v4-21-21]]

^<<v4-21-21,21>>^ Israel enviou então mensageiros para dizer a Síon, rei dos amorreus:

[[v4-21-22]]

^<<v4-21-22,22>>^ “Deixe-nos passar pela sua terra. Não nos desviaremos para nenhum campo nem vinha. Não beberemos água de nenhum poço. Iremos pela estrada real até termos passado pelo seu território.”

[[v4-21-23]]

^<<v4-21-23,23>>^ Contudo, Síon não deixou Israel passar pelo seu território. Em vez disso, Síon reuniu todo o seu exército e foi ao encontro de Israel, no deserto. Quando chegou a Jaaz, começou a lutar contra Israel.

[[v4-21-24]]

^<<v4-21-24,24>>^ Porém, Israel derrotou-o com a espada e tomou posse da sua terra, desde o Arnom até ao Jaboque, perto dos amonitas, pois Jazer faz fronteira com o território dos amonitas.

[[v4-21-25]]

^<<v4-21-25,25>>^ Israel tomou assim todas estas cidades e passou a morar em todas as cidades dos amorreus, em Hésbon e em todas as suas aldeias dependentes.^&#42;1^

[NOTE]
====
. Ou: “ao redor”.
====

[[v4-21-26]]

^<<v4-21-26,26>>^ Pois Hésbon era a cidade de Síon, rei dos amorreus, que tinha lutado contra o rei de Moabe e tomado dele toda a sua terra até ao Arnom.

[[v4-21-27]]

^<<v4-21-27,27>>^ Foi isso que deu origem ao provérbio irónico:
“Venham a Hésbon.
Que a cidade de Síon seja edificada e firmemente estabelecida.

[[v4-21-28]]

^<<v4-21-28,28>>^ Pois de Hésbon saiu um fogo; da cidade de Síon, uma chama.
Consumiu Ar de Moabe, os senhores dos lugares altos do Arnom.

[[v4-21-29]]

^<<v4-21-29,29>>^ Ai de ti, Moabe! Vocês serão destruídos, ó povo de Quemós!
Ele faz dos seus filhos fugitivos; e das suas filhas, cativas de Síon, rei dos amorreus.

[[v4-21-30]]

^<<v4-21-30,30>>^ Vamos atacá-los;
Hésbon será destruída até Díbon;
Vamos desolá-la até Nofá;
O fogo há de se espalhar até Medeba.”

[[v4-21-31]]

^<<v4-21-31,31>>^ Assim, Israel passou a morar na terra dos amorreus.

[[v4-21-32]]

^<<v4-21-32,32>>^ Moisés enviou então homens para espiar Jazer. Eles tomaram as suas aldeias dependentes^&#42;1^ e expulsaram os amorreus que lá havia.

[NOTE]
====
. Ou: “ao redor”.
====

[[v4-21-33]]

^<<v4-21-33,33>>^ Depois, mudaram de direção e subiram pelo Caminho de Basã. E Ogue, rei de Basã, saiu com todo o seu exército ao encontro deles para batalhar em Edrei.

[[v4-21-34]]

^<<v4-21-34,34>>^ Jeová disse a Moisés: “Não tenhas medo dele, pois vou entregá-lo nas tuas mãos, com todo o seu povo e a sua terra. Farás com ele o mesmo que fizeste com Síon, rei dos amorreus, que morava em Hésbon.”

[[v4-21-35]]

^<<v4-21-35,35>>^ Por fim, mataram-no, tanto a ele como aos seus filhos e a todo o seu povo, até que não sobreviveu ninguém do seu povo; e tomaram posse da sua terra.

'''

xref:004-numeros/004-numeros-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numeros/004-numeros-022.adoc#v4-22-0[Próximo Capítulo &#62;]