include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-18-1]]

^<<v11-18-1,1>>^ Depois de algum tempo, no terceiro ano, Elias recebeu a seguinte palavra de Jeová: “Vai, apresenta-te a Acabe, e eu farei chover sobre o solo.”

[[v11-18-2]]

^<<v11-18-2,2>>^ Assim, Elias foi apresentar-se a Acabe; enquanto a fome era severa em Samaria.

[[v11-18-3]]

^<<v11-18-3,3>>^ Entretanto, Acabe chamou Obadias, que era o encarregado da casa. (Obadias temia muito a Jeová,

[[v11-18-4]]

^<<v11-18-4,4>>^ e, quando Jezabel estava a eliminar^&#42;1^ os profetas de Jeová, Obadias levou cem profetas e manteve-os escondidos em cavernas, em grupos de 50, e sustentou-os com pão e água.)

[NOTE]
====
. Lit.: “decepar”.
====

[[v11-18-5]]

^<<v11-18-5,5>>^ Acabe disse a Obadias: “Percorre todo o país e vai a todas as fontes de água e a todos os vales.^&#42;1^ Talvez encontremos pastagem suficiente para manter vivos os cavalos e as mulas, para que os nossos animais não morram todos.”

[NOTE]
====
. Ou: “uádis”.
====

[[v11-18-6]]

^<<v11-18-6,6>>^ Então, dividiram entre si a terra que iam percorrer. Acabe foi sozinho por um caminho, e Obadias foi sozinho por outro caminho.

[[v11-18-7]]

^<<v11-18-7,7>>^ Quando Obadias seguia o seu caminho, Elias veio ao seu encontro. Obadias reconheceu-o imediatamente e prostrou-se com o rosto por terra, e perguntou: “É o senhor, meu senhor Elias?”

[[v11-18-8]]

^<<v11-18-8,8>>^ Ele respondeu-lhe: “Sou eu. Vai e diz ao teu senhor, o rei: ‘Elias está aqui.’”

[[v11-18-9]]

^<<v11-18-9,9>>^ Obadias, porém, disse: “Que pecado cometi eu, para o senhor querer entregar o seu servo a Acabe para ele me matar?

[[v11-18-10]]

^<<v11-18-10,10>>^ Tão certo como vive Jeová, seu Deus, não há nação nem reino em que o meu senhor, o rei, não o tenha mandado procurar. Quando diziam: ‘Ele não está aqui’, o rei fazia cada reino e cada nação jurar que não o tinha conseguido encontrar.

[[v11-18-11]]

^<<v11-18-11,11>>^ Agora, o senhor diz: ‘Vai e diz ao teu senhor, o rei: “Elias está aqui.”’

[[v11-18-12]]

^<<v11-18-12,12>>^ Quando eu me for embora, o espírito de Jeová irá levá-lo para um lugar que eu não saberei. E, quando eu informar Acabe e ele não o encontrar, com certeza vai matar-me. No entanto, o seu servo tem temido a Jeová desde a juventude.

[[v11-18-13]]

^<<v11-18-13,13>>^ Não informaram o meu senhor sobre o que eu fiz quando Jezabel estava a matar os profetas de Jeová? Como eu escondi em cavernas cem profetas de Jeová em grupos de 50, e os sustentei com pão e água?

[[v11-18-14]]

^<<v11-18-14,14>>^ Todavia, agora o senhor está a dizer: ‘Vai e diz ao teu senhor, o rei: “Elias está aqui.”’ Ele com certeza vai matar-me.”

[[v11-18-15]]

^<<v11-18-15,15>>^ Contudo, Elias disse: “Tão certo como vive Jeová dos exércitos, a quem sirvo,^&#42;1^ hoje vou apresentar-me a Acabe.”

[NOTE]
====
. Lit.: “perante quem estou de pé”.
====

[[v11-18-16]]

^<<v11-18-16,16>>^ Por conseguinte, Obadias foi ter com Acabe e avisou-o. E Acabe foi ter com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ Assim que viu Elias, Acabe disse: “És tu? Aquele que está a causar esta grande desgraça em^&#42;1^ Israel?”

[NOTE]
====
. Ou: “a trazer ostracismo [isto é, exclusão] a”.
====

[[v11-18-18]]

^<<v11-18-18,18>>^ Então, ele respondeu: “Não fui eu que causei esta desgraça em Israel; o culpado é o senhor e a casa do seu pai, porque abandonaram os mandamentos de Jeová e seguiram os baalins.

[[v11-18-19]]

^<<v11-18-19,19>>^ E agora, convoque todo o Israel ao monte Carmelo, e também os 450 profetas de Baal e os 400 profetas do poste sagrado,^&#42;1^ que comem à mesa de Jezabel.”

[NOTE]
====
. Veja o Glossário.
====

[[v11-18-20]]

^<<v11-18-20,20>>^ Assim, Acabe mandou mensageiros a todo o povo de Israel e reuniu os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Depois, Elias aproximou-se de todo o povo e disse: “Até quando ficarão indecisos^&#42;1^ entre duas opiniões diferentes? Se Jeová é o verdadeiro Deus, sigam-no! Mas se é Baal, sigam-no!” O povo, porém, não lhe disse nenhuma palavra em resposta.

[NOTE]
====
. Lit.: “a coxear”.
====

[[v11-18-22]]

^<<v11-18-22,22>>^ Elias disse então ao povo: “Eu sou o único profeta de Jeová que restou, mas há 450 profetas de Baal.

[[v11-18-23]]

^<<v11-18-23,23>>^ Que eles tragam dois novilhos. Que escolham um novilho, cortem-no em pedaços e coloquem-no sobre a lenha. No entanto, eles não lhe devem deitar fogo. Eu vou preparar o outro novilho e colocá-lo sobre a lenha, mas não lhe vou deitar fogo.

[[v11-18-24]]

^<<v11-18-24,24>>^ Depois, invoquem o nome do vosso deus, e eu invocarei o nome de Jeová. O Deus que responder por enviar fogo mostrará que é o verdadeiro Deus.” E todo o povo respondeu: “O que disseste é bom.”

[[v11-18-25]]

^<<v11-18-25,25>>^ Elias disse aos profetas de Baal: “Escolham um novilho e preparem-no primeiro, visto que são a maioria. Depois, invoquem o nome do vosso deus, mas não deitem fogo ao novilho.”

[[v11-18-26]]

^<<v11-18-26,26>>^ Assim, pegaram no novilho que lhes tinha sido trazido, prepararam-no e invocaram o nome de Baal desde a manhã até ao meio-dia, dizendo: “Ó Baal, responde-nos!” Contudo, não se ouvia nenhuma voz; ninguém respondia. Eles continuaram a dançar, coxeando em volta do altar que tinham feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ Por volta do meio-dia, Elias começou a gozar com eles e a dizer: “Gritem o mais que puderem! Afinal, ele é um deus! Talvez esteja entretido com os seus pensamentos ou tenha ido fazer as suas necessidades.^&#42;1^ Ou talvez esteja a dormir e alguém precisa de o acordar!”

[NOTE]
====
. Ou, possivelmente: “tenha ido numa viagem”.
====

[[v11-18-28]]

^<<v11-18-28,28>>^ Eles gritavam ao máximo da sua voz e faziam cortes em si mesmos com punhais e com lanças, segundo o seu costume, até ficarem cobertos de sangue.

[[v11-18-29]]

^<<v11-18-29,29>>^ Passou do meio-dia, e eles continuaram em delírio^&#42;1^ até à hora de se apresentar a oferta de cereais do anoitecer, mas não se ouvia nenhuma voz, ninguém respondia; ninguém prestava atenção.

[NOTE]
====
. Ou: “a comportar-se como profetas”.
====

[[v11-18-30]]

^<<v11-18-30,30>>^ Por fim, Elias disse a todo o povo: “Aproximem-se de mim.” Assim, todo o povo se aproximou dele, e ele restaurou o altar de Jeová que tinha sido derrubado.

[[v11-18-31]]

^<<v11-18-31,31>>^ Elias pegou então em 12 pedras, conforme o número das tribos dos filhos de Jacó, o qual tinha recebido a seguinte palavra de Jeová: “Israel será o teu nome.”

[[v11-18-32]]

^<<v11-18-32,32>>^ Com as pedras, Elias construiu um altar em nome de Jeová. Depois fez em volta do altar uma vala, suficientemente grande para se semear dois seás^&#42;1^ de semente.

[NOTE]
====
. Um seá equivalia a 7,33 l. Veja o Ap. B14.
====

[[v11-18-33]]

^<<v11-18-33,33>>^ Em seguida, dispôs a lenha, cortou o novilho em pedaços e pô-lo sobre a lenha, e disse: “Encham quatro cântaros grandes com água e despejem-na sobre a oferta queimada e sobre a lenha.”

[[v11-18-34]]

^<<v11-18-34,34>>^ Então, ele disse: “Façam isso outra vez.” E eles fizeram-no outra vez. Depois, ele disse: “Façam isso pela terceira vez.” E eles fizeram-no pela terceira vez.

[[v11-18-35]]

^<<v11-18-35,35>>^ A água corria por todo o altar, e ele também encheu a vala com água.

[[v11-18-36]]

^<<v11-18-36,36>>^ Por volta da hora de se apresentar a oferta de cereais do anoitecer, Elias, o profeta, aproximou-se do altar e disse: “Ó Jeová, Deus de Abraão, de Isaque e de Israel, saiba-se hoje que tu és Deus em Israel, que eu sou o teu servo e que foi segundo a tua ordem que fiz todas estas coisas.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, ó Jeová! Responde-me, para que este povo saiba que tu, Jeová, és o verdadeiro Deus e que tu estás a fazer o coração deles voltar para ti.”

[[v11-18-38]]

^<<v11-18-38,38>>^ Então, desceu fogo de Jeová e consumiu a oferta queimada, a lenha, as pedras e o pó, e secou a água que havia na vala.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando o povo viu isso, todos se prostraram imediatamente com o rosto por terra e disseram: “Jeová é o verdadeiro Deus! Jeová é o verdadeiro Deus!”

[[v11-18-40]]

^<<v11-18-40,40>>^ Então, Elias disse-lhes: “Agarrem os profetas de Baal! Não deixem escapar nenhum deles!” Agarraram-nos imediatamente, e Elias fê-los descer ao rio^&#42;1^ Quisom e matou-os ali.

[NOTE]
====
. Ou: “uádi”.
====

[[v11-18-41]]

^<<v11-18-41,41>>^ Elias disse a Acabe: “Vá, coma e beba, pois já se ouve o barulho de uma chuva forte.”

[[v11-18-42]]

^<<v11-18-42,42>>^ Então, Acabe foi comer e beber, enquanto Elias subiu ao cume do Carmelo, ajoelhou-se no chão e ficou com o rosto entre os joelhos.

[[v11-18-43]]

^<<v11-18-43,43>>^ A seguir, ele disse ao seu ajudante: “Por favor, sobe e olha na direção do mar.” Portanto ele subiu, olhou e disse: “Não há absolutamente nada.” E Elias disse sete vezes: “Volta e olha outra vez.”

[[v11-18-44]]

^<<v11-18-44,44>>^ Na sétima vez o ajudante disse: “Olha! Uma nuvem pequena do tamanho da mão de um homem está a subir do mar.” Elias disse então: “Vai, diz a Acabe: ‘Prepare o seu carro de guerra! Desça para que a chuva não o detenha!’”

[[v11-18-45]]

^<<v11-18-45,45>>^ Entretanto, o céu começou a ficar cheio de nuvens escuras, o vento começou a soprar e caiu uma chuva forte. Acabe seguia no seu carro de guerra para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ E a mão de Jeová veio sobre Elias; e ele prendeu^&#42;1^ a sua veste na cintura e correu à frente de Acabe até Jezreel.

[NOTE]
====
. Ou: “cingiu”.
====

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]