include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquela altura, Abias, filho de Jeroboão, adoeceu.

[[v11-14-2]]

^<<v11-14-2,2>>^ Assim, Jeroboão disse à sua esposa: “Por favor, disfarça-te, para que ninguém saiba que és a esposa de Jeroboão, e então vai a Silo. Aías, o profeta, está lá. Foi ele que disse que eu me tornaria rei deste povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leva contigo dez pães, bolos^&#42;1^ e um frasco de mel, e apresenta-te a ele. Ele vai dizer-te o que acontecerá ao rapaz.”^&#42;2^

[NOTE]
====
. Ou: “bolos polvilhados”.
. Ou: “jovem”.
====

[[v11-14-4]]

^<<v11-14-4,4>>^ A esposa de Jeroboão fez o que ele disse. Ela levantou-se e foi a Silo, e chegou à casa de Aías. Os olhos de Aías não se mexiam; ele não conseguia ver por causa da idade.

[[v11-14-5]]

^<<v11-14-5,5>>^ Contudo, Jeová tinha dito a Aías: “A esposa de Jeroboão chegará para te perguntar sobre o filho dela, pois ele está doente. Eu vou dizer-te o que lhe deves dizer.^&#42;1^ Quando ela chegar, estará disfarçada.”

[NOTE]
====
. Ou: “Deves dizer-lhe assim e assim.”
====

[[v11-14-6]]

^<<v11-14-6,6>>^ Assim que Aías ouviu os passos dela na entrada, disse: “Entra, esposa de Jeroboão. Porque é que estás disfarçada? Fui designado para te transmitir uma dura mensagem.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai, diz a Jeroboão: ‘Assim diz Jeová, o Deus de Israel: “Eu levantei-te do meio do teu povo para te fazer líder do meu povo Israel.

[[v11-14-8]]

^<<v11-14-8,8>>^ Arranquei o reino da casa de David e dei-to. Mas tu não tens sido igual ao meu servo David, que guardou os meus mandamentos e que me seguiu de todo o coração, fazendo apenas o que era certo aos meus olhos.

[[v11-14-9]]

^<<v11-14-9,9>>^ Fizeste pior do que todos os que reinaram antes de ti; fizeste para ti outro deus e imagens de metal^&#42;1^ para me ofender, e foi a mim que viraste as costas.

[NOTE]
====
. Ou: “estátuas fundidas”.
====

[[v11-14-10]]

^<<v11-14-10,10>>^ Por essa razão, trarei uma calamidade sobre a casa de Jeroboão; eliminarei^&#42;1^ em Israel todos os do sexo masculino^&#42;2^ da casa de Jeroboão, incluindo o desamparado e o fraco, e vou varrer a casa de Jeroboão, assim como se varre o esterco até não sobrar nada!

[NOTE]
====
. Lit.: “deceparei”.
. Lit.: “todo aquele que urina contra o muro”. Expressão hebraica que indica desprezo e se refere a homens.
====

[[v11-14-11]]

^<<v11-14-11,11>>^ Os da casa de Jeroboão que morrerem na cidade serão devorados pelos cães; e os que morrerem no campo serão comidos pelas aves dos céus, pois Jeová disse isso.”’

[[v11-14-12]]

^<<v11-14-12,12>>^ “Agora, levanta-te, vai para casa. Assim que puseres os pés na cidade, o rapaz^&#42;1^ morrerá.

[NOTE]
====
. Ou: “jovem”.
====

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel o lamentará e o enterrará. Da família de Jeroboão só ele será colocado numa sepultura, porque ele é o único da casa de Jeroboão em quem Jeová, o Deus de Israel, encontrou algo de bom.

[[v11-14-14]]

^<<v11-14-14,14>>^ A partir desse dia, Jeová fará surgir para si um rei sobre Israel que eliminará^&#42;1^ a casa de Jeroboão. De facto, isso já está a acontecer.

[NOTE]
====
. Lit.: “decepará”.
====

[[v11-14-15]]

^<<v11-14-15,15>>^ Jeová golpeará Israel, como uma cana que balança na água, e desarraigará Israel desta terra boa que ele deu aos seus antepassados e irá espalhá-los para o outro lado do rio Eufrates,^&#42;1^ por terem feito os postes sagrados,^&#42;2^ ofendendo a Jeová.

[NOTE]
====
. Lit.: “do Rio”.
. Veja o Glossário.
====

[[v11-14-16]]

^<<v11-14-16,16>>^ E ele abandonará Israel por causa dos pecados que Jeroboão cometeu e levou Israel a cometer.”

[[v11-14-17]]

^<<v11-14-17,17>>^ Então, a esposa de Jeroboão levantou-se e foi-se embora, e voltou para Tirza. Quando chegou à entrada da casa, o rapaz^&#42;1^ morreu.

[NOTE]
====
. Ou: “jovem”.
====

[[v11-14-18]]

^<<v11-14-18,18>>^ Assim, eles enterraram-no, e todo o Israel o lamentou, segundo a palavra que Jeová tinha falado por meio do seu servo Aías, o profeta.

[[v11-14-19]]

^<<v11-14-19,19>>^ E os outros acontecimentos da história de Jeroboão, como ele guerreou e como reinou, estão escritos no livro da história da época dos reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ A duração^&#42;1^ do reinado de Jeroboão foi de 22 anos. Depois, ele descansou com os seus antepassados; e Nadabe, seu filho, tornou-se rei no seu lugar.

[NOTE]
====
. Lit.: “Os dias”.
====

[[v11-14-21]]

^<<v11-14-21,21>>^ Entretanto, Roboão, filho de Salomão, tinha-se tornado rei em Judá. Roboão tinha 41 anos de idade quando se tornou rei, e reinou durante 17 anos em Jerusalém, a cidade que Jeová tinha escolhido dentre todas as tribos de Israel como o lugar para pôr o seu nome. O nome da mãe de Roboão era Naamá, a amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ Judá fazia o que era mau aos olhos de Jeová, e, pelos pecados que cometeram, provocaram-no mais do que todos os seus antepassados.

[[v11-14-23]]

^<<v11-14-23,23>>^ Eles também construíam para si altos sagrados, colunas sagradas e postes sagrados^&#42;1^ em toda a colina elevada e debaixo de toda a árvore frondosa.

[NOTE]
====
. Veja o Glossário.
====

[[v11-14-24]]

^<<v11-14-24,24>>^ Havia também no país prostitutos de templo. Faziam todas as coisas detestáveis das nações que Jeová tinha expulsado de diante dos israelitas.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do rei Roboão, Sisaque, rei do Egito, veio contra Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ Ele levou os tesouros da casa de Jeová e os tesouros da casa^&#42;1^ do rei. Levou tudo, incluindo todos os escudos de ouro que Salomão tinha feito.

[NOTE]
====
. Ou: “do palácio”.
====

[[v11-14-27]]

^<<v11-14-27,27>>^ Por isso, o rei Roboão fez escudos de cobre para os substituir e entregou-os aos chefes da guarda,^&#42;1^ que vigiavam a entrada da casa do rei.

[NOTE]
====
. Lit.: “dos corredores”.
====

[[v11-14-28]]

^<<v11-14-28,28>>^ Sempre que o rei ia à casa de Jeová, os guardas carregavam os escudos e depois devolviam-nos à sala dos guardas.

[[v11-14-29]]

^<<v11-14-29,29>>^ Quanto aos outros acontecimentos da história de Roboão, tudo o que ele fez, não estão escritos no livro da história da época dos reis de Judá?

[[v11-14-30]]

^<<v11-14-30,30>>^ Houve sempre guerra entre Roboão e Jeroboão.

[[v11-14-31]]

^<<v11-14-31,31>>^ Por fim, Roboão descansou com os seus antepassados e foi enterrado com os seus antepassados na Cidade de David. O nome da sua mãe era Naamá, a amonita. E o filho dele, Abião,^&#42;1^ tornou-se rei no seu lugar.

[NOTE]
====
. Também chamado Abias.
====

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]