include::./index.adoc[]

[[v11-15-0]]
=== 1 Reis, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-15-1]]

^<<v11-15-1,1>>^ No décimo oitavo ano do rei Jeroboão, filho de Nebate, Abião^&#42;1^ tornou-se rei sobre Judá.

[NOTE]
====
. Também chamado Abias.
====

[[v11-15-2]]

^<<v11-15-2,2>>^ Ele reinou durante três anos em Jerusalém. O nome da sua mãe era Maacá, neta de Absalão.^&#42;1^

[NOTE]
====
. Lit.: “Abissalão”, grafia variante.
====

[[v11-15-3]]

^<<v11-15-3,3>>^ Abião cometeu os mesmos pecados que o seu pai cometeu antes dele e o seu coração não era pleno para com^&#42;1^ Jeová, seu Deus, assim como era o coração de David, seu antepassado.

[NOTE]
====
. Ou: “plenamente devotado a”.
====

[[v11-15-4]]

^<<v11-15-4,4>>^ Contudo, por causa de David, Jeová, seu Deus, deu-lhe uma lâmpada em Jerusalém, suscitando-lhe o filho como sucessor e assegurando a existência de Jerusalém.

[[v11-15-5]]

^<<v11-15-5,5>>^ Pois David fez o que era certo aos olhos de Jeová e, durante todos os dias da sua vida, não se desviou de nada que ele lhe ordenou, a não ser no caso de Urias, o hitita.

[[v11-15-6]]

^<<v11-15-6,6>>^ E houve guerra entre Roboão e Jeroboão durante todos os dias da sua vida.

[[v11-15-7]]

^<<v11-15-7,7>>^ Quanto aos outros acontecimentos da história de Abião, tudo o que ele fez, não estão escritos no livro da história da época dos reis de Judá? Também houve guerra entre Abião e Jeroboão.

[[v11-15-8]]

^<<v11-15-8,8>>^ Por fim, Abião descansou com os seus antepassados, e enterraram-no na Cidade de David; e Asa, seu filho, tornou-se rei no seu lugar.

[[v11-15-9]]

^<<v11-15-9,9>>^ No vigésimo ano de Jeroboão, rei de Israel, Asa começou a reinar em Judá.

[[v11-15-10]]

^<<v11-15-10,10>>^ Ele reinou durante 41 anos em Jerusalém. O nome da sua avó era Maacá, neta de Absalão.^&#42;1^

[NOTE]
====
. Lit.: “Abissalão”, grafia variante.
====

[[v11-15-11]]

^<<v11-15-11,11>>^ Asa fez o que era certo aos olhos de Jeová, assim como David, seu antepassado.

[[v11-15-12]]

^<<v11-15-12,12>>^ Ele expulsou do país os prostitutos de templo e removeu todos os ídolos repugnantes^&#42;1^ que os seus antepassados tinham feito.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v11-15-13]]

^<<v11-15-13,13>>^ Asa até mesmo removeu a sua avó Maacá da posição de rainha-mãe,^&#42;1^ porque ela tinha feito um ídolo obsceno para a adoração do poste sagrado.^&#42;2^ Ele derrubou o ídolo obsceno dela e queimou-o no vale do Cédron.

[NOTE]
====
. Ou: “de senhora”.
. Veja o Glossário.
====

[[v11-15-14]]

^<<v11-15-14,14>>^ Porém, não removeu os altos sagrados. No entanto, o coração de Asa foi pleno para com^&#42;1^ Jeová durante toda a sua vida.^&#42;2^

[NOTE]
====
. Ou: “plenamente devotado a”.
. Lit.: “todos os seus dias”.
====

[[v11-15-15]]

^<<v11-15-15,15>>^ E ele levou para dentro da casa de Jeová as coisas que ele e o seu pai tinham tornado sagradas: prata, ouro e diversos utensílios.

[[v11-15-16]]

^<<v11-15-16,16>>^ Houve sempre guerra entre Asa e Baasa, rei de Israel.

[[v11-15-17]]

^<<v11-15-17,17>>^ Assim, Baasa, rei de Israel, veio contra Judá e começou a fortificar^&#42;1^ Ramá, para não deixar ninguém sair nem entrar no território de^&#42;2^ Asa, rei de Judá.

[NOTE]
====
. Ou: “reconstruir”.
. Lit.: “sair ou entrar até”.
====

[[v11-15-18]]

^<<v11-15-18,18>>^ Em vista disso, Asa pegou em toda a prata e ouro que tinham sobrado no tesouro da casa de Jeová e no tesouro da casa^&#42;1^ do rei e entregou-os aos seus servos. Depois, o rei Asa enviou-os a Ben-Hadade, filho de Tabrimom, filho de Heziom, rei da Síria, que morava em Damasco, com a seguinte mensagem:

[NOTE]
====
. Ou: “do palácio”.
====

[[v11-15-19]]

^<<v11-15-19,19>>^ “Há um acordo^&#42;1^ entre mim e ti, e entre o meu pai e o teu pai. Envio-te prata e ouro como presente. Desfaz o teu acordo^&#42;2^ com Baasa, rei de Israel, para que ele se retire do meu território.”

[NOTE]
====
. Ou: “pacto”.
. Ou: “pacto”.
====

[[v11-15-20]]

^<<v11-15-20,20>>^ Ben-Hadade escutou o rei Asa e enviou os chefes dos seus exércitos contra as cidades de Israel, e eles atacaram Ijom, Dã, Abel-Bete-Maacá, todo o Quinerete e toda a terra de Naftali.

[[v11-15-21]]

^<<v11-15-21,21>>^ Assim que Baasa soube disso, parou de fortificar^&#42;1^ Ramá e continuou a morar em Tirza.

[NOTE]
====
. Ou: “reconstruir”.
====

[[v11-15-22]]

^<<v11-15-22,22>>^ Então, o rei Asa convocou todo o Judá — ninguém ficou isento —, e eles levaram as pedras e as madeiras de Ramá, com as quais Baasa estava a construir, e com elas o rei Asa fortificou^&#42;1^ Geba, em Benjamim, e Mispá.

[NOTE]
====
. Ou: “reconstruiu”.
====

[[v11-15-23]]

^<<v11-15-23,23>>^ Quanto a todos os outros acontecimentos da história de Asa, todos os seus atos poderosos, tudo o que ele fez e as cidades que construiu,^&#42;1^ não estão escritos no livro da história da época dos reis de Judá? Contudo, na sua velhice ele sofreu de uma doença nos pés.

[NOTE]
====
. Ou: “fortificou; reconstruiu”.
====

[[v11-15-24]]

^<<v11-15-24,24>>^ Por fim, Asa descansou com os seus antepassados e foi enterrado com eles na Cidade de David, seu antepassado; e Jeosafá, seu filho, tornou-se rei no seu lugar.

[[v11-15-25]]

^<<v11-15-25,25>>^ Nadabe, filho de Jeroboão, tornou-se rei sobre Israel no segundo ano de Asa, rei de Judá, e reinou sobre Israel durante dois anos.

[[v11-15-26]]

^<<v11-15-26,26>>^ Ele fazia o que era mau aos olhos de Jeová e andava no caminho do seu pai e no pecado dele, que ele tinha levado Israel a cometer.

[[v11-15-27]]

^<<v11-15-27,27>>^ Baasa, filho de Aías, da casa de Issacar, conspirou contra Nadabe, e Baasa matou-o em Gibetom, que pertencia aos filisteus, enquanto Nadabe e todo o Israel cercavam Gibetom.

[[v11-15-28]]

^<<v11-15-28,28>>^ Assim, Baasa matou-o no terceiro ano de Asa, rei de Judá, e tornou-se rei no seu lugar.

[[v11-15-29]]

^<<v11-15-29,29>>^ E, assim que ele se tornou rei, matou todos os da casa de Jeroboão. Não deixou ninguém^&#42;1^ da casa de Jeroboão escapar; eliminou-os a todos, segundo a palavra que Jeová tinha falado por meio do seu servo Aías, o silonita.

[NOTE]
====
. Ou: “ninguém que respirasse”. Lit.: “nenhum fôlego”.
====

[[v11-15-30]]

^<<v11-15-30,30>>^ Isso aconteceu por causa dos pecados que Jeroboão tinha cometido e levado Israel a cometer, e porque tinha ofendido muito a Jeová, o Deus de Israel.

[[v11-15-31]]

^<<v11-15-31,31>>^ Quanto aos outros acontecimentos da história de Nadabe, tudo o que ele fez, não estão escritos no livro da história da época dos reis de Israel?

[[v11-15-32]]

^<<v11-15-32,32>>^ E houve sempre guerra entre Asa e Baasa, rei de Israel.

[[v11-15-33]]

^<<v11-15-33,33>>^ No terceiro ano de Asa, rei de Judá, Baasa, filho de Aías, tornou-se rei em Tirza sobre todo o Israel, e reinou durante 24 anos.

[[v11-15-34]]

^<<v11-15-34,34>>^ Todavia, ele fazia o que era mau aos olhos de Jeová e andava no caminho de Jeroboão e no pecado dele, que ele tinha levado Israel a cometer.

'''

xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[Próximo Capítulo &#62;]