include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-9-1]]

^<<v11-9-1,1>>^ Assim que Salomão terminou de construir a casa de Jeová, a casa^&#42;1^ do rei e tudo o que Salomão queria fazer,

[NOTE]
====
. Ou: “o palácio”.
====

[[v11-9-2]]

^<<v11-9-2,2>>^ Jeová apareceu a Salomão uma segunda vez, assim como lhe tinha aparecido em Gibeão.

[[v11-9-3]]

^<<v11-9-3,3>>^ Jeová disse-lhe: “Ouvi a tua oração e o pedido de favor que fizeste diante de mim. Santifiquei esta casa que construíste, pondo nela o meu nome de modo permanente, e os meus olhos e o meu coração estarão sempre nela.

[[v11-9-4]]

^<<v11-9-4,4>>^ Se tu andares diante de mim assim como andou David, teu pai, com um coração íntegro e com retidão, fazendo tudo o que te ordenei, e, se obedeceres aos meus decretos e às minhas decisões judiciais,

[[v11-9-5]]

^<<v11-9-5,5>>^ então, estabelecerei o trono do teu reino sobre Israel para sempre, assim como prometi a David, teu pai, dizendo: ‘Haverá sempre um descendente teu sentado no trono de Israel.’

[[v11-9-6]]

^<<v11-9-6,6>>^ Contudo, se vocês e os vossos filhos deixarem de me seguir e não guardarem os mandamentos e os decretos que coloquei à vossa frente, e forem servir outros deuses e se curvarem diante deles,

[[v11-9-7]]

^<<v11-9-7,7>>^ eu eliminarei Israel da superfície da terra que lhes dei, e lançarei para longe da minha vista a casa que santifiquei para o meu nome, e Israel irá tornar-se alvo de desprezo^&#42;1^ e motivo de riso entre todos os povos.

[NOTE]
====
. Ou: “irá tornar-se um provérbio”.
====

[[v11-9-8]]

^<<v11-9-8,8>>^ E esta casa irá tornar-se um montão de ruínas. Todo aquele que passar por ela olhará espantado, assobiará e perguntará: ‘Porque é que Jeová fez isto a esta terra e a esta casa?’

[[v11-9-9]]

^<<v11-9-9,9>>^ Então, responderão: ‘Foi porque abandonaram a Jeová, seu Deus, que tirou os seus antepassados da terra do Egito, e apegaram-se a outros deuses, curvaram-se diante deles e serviram-nos. Foi por isso que Jeová lhes trouxe toda esta calamidade.’”

[[v11-9-10]]

^<<v11-9-10,10>>^ Ao fim dos 20 anos que Salomão levou a construir as duas casas, a casa de Jeová e a casa^&#42;1^ do rei,

[NOTE]
====
. Ou: “o palácio”.
====

[[v11-9-11]]

^<<v11-9-11,11>>^ Hirão, rei de Tiro, tinha fornecido a Salomão madeira de cedro e de junípero, e todo o ouro que ele quis, por isso, o rei Salomão deu a Hirão 20 cidades na terra da Galileia.

[[v11-9-12]]

^<<v11-9-12,12>>^ Assim, Hirão veio de Tiro para ver as cidades que Salomão lhe tinha dado, mas não ficou contente com elas.^&#42;1^

[NOTE]
====
. Lit.: “elas não eram direitas aos seus olhos”.
====

[[v11-9-13]]

^<<v11-9-13,13>>^ Ele disse: “Que cidades são estas que me deste, meu irmão?” E elas são chamadas Terra de Cabul^&#42;1^ até ao dia de hoje.

[NOTE]
====
. Ou, possivelmente: “Terra Que não Vale Nada”.
====

[[v11-9-14]]

^<<v11-9-14,14>>^ Entretanto, Hirão enviou ao rei 120 talentos^&#42;1^ de ouro.

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v11-9-15]]

^<<v11-9-15,15>>^ Este é o relato sobre aqueles que o rei Salomão convocou para trabalhos forçados, a fim de construir a casa de Jeová, a sua própria casa,^&#42;1^ o Aterro,^&#42;2^ a muralha de Jerusalém, Hazor, Megido e Gezer.

[NOTE]
====
. Ou: “o seu próprio palácio”.
. Ou: “Milo”. Termo hebraico que significa “encher”.
====

[[v11-9-16]]

^<<v11-9-16,16>>^ (O Faraó, rei do Egito, tinha atacado e tomado Gezer, queimando-a com fogo e matando os cananeus que moravam nessa cidade. Depois ele deu-a como presente de despedida^&#42;1^ à sua filha, a esposa de Salomão.)

[NOTE]
====
. Ou: “presente de casamento; dote”.
====

[[v11-9-17]]

^<<v11-9-17,17>>^ Salomão construiu^&#42;1^ Gezer, Bete-Horom Baixa,

[NOTE]
====
. Ou: “fortificou”.
====

[[v11-9-18]]

^<<v11-9-18,18>>^ Baalate, Tamar, no deserto do país,

[[v11-9-19]]

^<<v11-9-19,19>>^ assim como todas as cidades-armazém de Salomão, as cidades dos carros de guerra, as cidades para os cavaleiros e tudo o que Salomão desejou construir em Jerusalém, no Líbano e em todas as terras sob o seu domínio.

[[v11-9-20]]

^<<v11-9-20,20>>^ Quanto a todos os que tinham restado dos amorreus, dos hititas, dos perizeus, dos heveus e dos jebuseus, que não faziam parte do povo de Israel

[[v11-9-21]]

^<<v11-9-21,21>>^ — isto é, os descendentes desses povos que restaram no país e que os israelitas não conseguiram entregar à destruição^&#42;1^ —, foram recrutados por Salomão para trabalhos forçados, e eles são escravos até hoje.

[NOTE]
====
. Ou: “devotar à destruição”. Veja o Glossário.
====

[[v11-9-22]]

^<<v11-9-22,22>>^ Contudo, Salomão não fez nenhum dos israelitas servir como escravo, pois eles eram os seus guerreiros, servos, príncipes, oficiais e chefes dos seus condutores de carros de guerra e dos cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Havia 550 chefes dos encarregados, que supervisionavam a obra de Salomão. Eles eram os capatazes dos trabalhadores.

[[v11-9-24]]

^<<v11-9-24,24>>^ A filha do Faraó subiu da Cidade de David para a sua casa, que Salomão lhe tinha construído; depois ele construiu o Aterro.^&#42;1^

[NOTE]
====
. Ou: “Milo”. Termo hebraico que significa “encher”.
====

[[v11-9-25]]

^<<v11-9-25,25>>^ Três vezes por ano, Salomão oferecia sacrifícios queimados e sacrifícios de participação em comum no altar que tinha construído para Jeová. Ele também fazia fumo sacrificial no altar, que ficava perante Jeová. Assim, ele acabou a casa.

[[v11-9-26]]

^<<v11-9-26,26>>^ O rei Salomão também fez uma frota de navios em Eziom-Geber, que fica perto de Elote, à beira do mar Vermelho, na terra de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ Com a frota de navios, Hirão enviou os seus servos, marinheiros experientes, para trabalhar com os servos de Salomão.

[[v11-9-28]]

^<<v11-9-28,28>>^ Eles foram a Ofir e trouxeram de lá 420 talentos de ouro, e levaram-nos ao rei Salomão.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]