include::./index.adoc[]

[[v11-17-0]]
=== 1 Reis, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-17-1]]

^<<v11-17-1,1>>^ E Elias,^&#42;1^ o tisbita, habitante de Gileade, disse a Acabe: “Tão certo como vive Jeová, o Deus de Israel, a quem sirvo,^&#42;2^ não haverá nem orvalho nem chuva durante estes anos, a não ser que eu ordene!”

[NOTE]
====
. Que significa “o meu Deus é Jeová”.
. Lit.: “perante quem estou de pé”.
====

[[v11-17-2]]

^<<v11-17-2,2>>^ Elias recebeu a seguinte palavra de Jeová:

[[v11-17-3]]

^<<v11-17-3,3>>^ “Sai deste lugar, vai para o leste e esconde-te no vale de Querite,^&#42;1^ que fica a leste do Jordão.

[NOTE]
====
. Ou: “uádi Querite”.
====

[[v11-17-4]]

^<<v11-17-4,4>>^ Deves beber água do ribeiro, e eu ordenarei aos corvos que te deem ali de comer.”

[[v11-17-5]]

^<<v11-17-5,5>>^ Ele foi imediatamente e fez de acordo com a palavra de Jeová; ele foi e ficou no vale de Querite,^&#42;1^ a leste do Jordão.

[NOTE]
====
. Ou: “uádi Querite”.
====

[[v11-17-6]]

^<<v11-17-6,6>>^ E os corvos traziam-lhe pão e carne de manhã, e pão e carne ao anoitecer, e ele bebia água do ribeiro.

[[v11-17-7]]

^<<v11-17-7,7>>^ Contudo, depois de alguns dias, o ribeiro secou, porque não chovia no país.

[[v11-17-8]]

^<<v11-17-8,8>>^ Então, ele recebeu a seguinte palavra de Jeová:

[[v11-17-9]]

^<<v11-17-9,9>>^ “Vai imediatamente a Sarefá, no território de Sídon, e fica lá. Mandarei que uma viúva de lá te dê de comer.”

[[v11-17-10]]

^<<v11-17-10,10>>^ Assim, ele levantou-se e foi para Sarefá. Quando chegou à entrada da cidade, encontrou uma viúva que juntava gravetos. Ele chamou-a e disse: “Por favor, traz-me um pouco de água para eu beber.”

[[v11-17-11]]

^<<v11-17-11,11>>^ Quando ela estava a ir buscar a água, ele chamou-a e disse: “Por favor, traz-me um pedaço de pão.”

[[v11-17-12]]

^<<v11-17-12,12>>^ Então ela disse: “Tão certo como vive Jeová, seu Deus, não tenho pão, só tenho um punhado de farinha num jarro grande e um pouco de azeite num jarro pequeno. Estou a juntar uns gravetos e vou para casa fazer alguma coisa para mim e para o meu filho. Vamos comer e depois morreremos.”

[[v11-17-13]]

^<<v11-17-13,13>>^ Então, Elias disse-lhe: “Não tenhas medo. Vai para casa e faz o que disseste. Mas primeiro faz-me um pequeno pão redondo com o que tens e traz-mo. Depois podes preparar alguma coisa para ti e para o teu filho.

[[v11-17-14]]

^<<v11-17-14,14>>^ Pois assim diz Jeová, o Deus de Israel: ‘A farinha no jarro grande não se esgotará, e o azeite no jarro pequeno não acabará, até ao dia em que Jeová fizer chover sobre o solo.’”

[[v11-17-15]]

^<<v11-17-15,15>>^ Portanto, ela foi e fez o que Elias disse; e ela, o profeta e a família dela tiveram o que comer por muitos dias.

[[v11-17-16]]

^<<v11-17-16,16>>^ A farinha no jarro grande não se esgotou, e o azeite no jarro pequeno não acabou, segundo a palavra que Jeová tinha falado por meio de Elias.

[[v11-17-17]]

^<<v11-17-17,17>>^ Depois disso, o filho da dona da casa ficou doente, e a sua doença agravou-se tanto que ele morreu.^&#42;1^

[NOTE]
====
. Lit.: “não sobrou nele fôlego”.
====

[[v11-17-18]]

^<<v11-17-18,18>>^ De seguida, ela disse a Elias: “O que é que tem contra mim,^&#42;1^ ó homem do verdadeiro Deus? Veio à minha casa para me lembrar dos meus pecados e para matar o meu filho?”

[NOTE]
====
. Ou: “O que é que eu tenho a ver contigo”.
====

[[v11-17-19]]

^<<v11-17-19,19>>^ Porém, ele disse-lhe: “Dá-me o teu filho.” Então tirou-o dos braços dela e levou-o para cima, para o quarto de terraço onde estava hospedado, e deitou-o na sua própria cama.

[[v11-17-20]]

^<<v11-17-20,20>>^ Ele clamou a Jeová: “Ó Jeová, meu Deus, será que também estás a causar calamidade à viúva que me hospedou, matando-lhe o filho?”

[[v11-17-21]]

^<<v11-17-21,21>>^ E estendeu-se três vezes sobre o menino e clamou a Jeová: “Ó Jeová, meu Deus, por favor, que a vida^&#42;1^ deste menino volte a ele.”

[NOTE]
====
. Ou: “alma”.
====

[[v11-17-22]]

^<<v11-17-22,22>>^ Jeová escutou o pedido de Elias; a vida^&#42;1^ do menino voltou a ele, e ele voltou a viver.

[NOTE]
====
. Ou: “alma”.
====

[[v11-17-23]]

^<<v11-17-23,23>>^ Elias pegou no menino, desceu do quarto de terraço para a casa e entregou-o à sua mãe. E Elias disse: “Vê! O teu filho está vivo!”

[[v11-17-24]]

^<<v11-17-24,24>>^ Então a mulher disse a Elias: “Agora sei que o senhor é mesmo um homem de Deus e que a palavra que fala da parte de Jeová é verdade.”

'''

xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[&#60; Capítulo Anterior] | <<v11-17-0,Topo>> | xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[Próximo Capítulo &#62;]