include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-1-1]]

^<<v11-1-1,1>>^ O rei David era idoso, de idade muito avançada,^&#42;1^ e embora o tapassem com roupa, ele não se conseguia aquecer.

[NOTE]
====
. Lit.: “avançado em dias”.
====

[[v11-1-2]]

^<<v11-1-2,2>>^ Então, os seus servos disseram-lhe: “Vamos procurar uma jovem, uma virgem, para o meu senhor, o rei, e ela servirá o rei como sua enfermeira. Ela irá deitar-se nos seus braços para que o meu senhor, o rei, se aqueça.”

[[v11-1-3]]

^<<v11-1-3,3>>^ Assim, eles procuraram em todo o território de Israel uma jovem bonita e encontraram Abisague, a sunamita, e levaram-na ao rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ A jovem era extremamente bela; e tornou-se a enfermeira do rei e servia-o, mas o rei não teve relações sexuais com ela.

[[v11-1-5]]

^<<v11-1-5,5>>^ Entretanto, Adonias, filho de Hagite, enaltecia-se, dizendo: “Eu serei o rei!” Ele mandou fazer para si um carro real, com cavaleiros e 50 homens para correrem à sua frente.

[[v11-1-6]]

^<<v11-1-6,6>>^ Contudo, o seu pai nunca o tinha confrontado,^&#42;1^ dizendo: “Porque é que fazes isto?” Ele também era muito bonito, e a sua mãe tinha-o dado à luz depois de Absalão.

[NOTE]
====
. Ou: “nunca lhe tinha ferido os sentimentos; nunca o tinha censurado”.
====

[[v11-1-7]]

^<<v11-1-7,7>>^ Adonias conversou com Joabe, filho de Zeruia, e com Abiatar, o sacerdote, e eles ofereceram-lhe ajuda e apoio.

[[v11-1-8]]

^<<v11-1-8,8>>^ Todavia, Zadoque, o sacerdote, Benaia, filho de Jeoiada, Natã, o profeta, Simei, Reí e os guerreiros valentes de David não apoiaram Adonias.

[[v11-1-9]]

^<<v11-1-9,9>>^ Por fim, Adonias ofereceu sacrifícios de ovelhas, de bois e de bezerros gordos,^&#42;1^ ao pé da pedra de Zoelete, que fica perto de En-Rogel. Ele convidou todos os seus irmãos, os filhos do rei, e todos os homens de Judá, os servos do rei.

[NOTE]
====
. Ou: “animais cevados”.
====

[[v11-1-10]]

^<<v11-1-10,10>>^ Porém, não convidou Natã, o profeta, nem Benaia e os guerreiros valentes, nem o seu irmão Salomão.

[[v11-1-11]]

^<<v11-1-11,11>>^ Então, Natã disse a Bate-Seba, mãe de Salomão: “Não ouviste dizer que Adonias, filho de Hagite, se tornou rei e que o nosso senhor David não sabe nada acerca disso?

[[v11-1-12]]

^<<v11-1-12,12>>^ Portanto, agora escuta-me, por favor; e deixa-me aconselhar-te, para poderes salvar a tua vida e a vida^&#42;1^ do teu filho Salomão.

[NOTE]
====
. Ou: “a tua alma e a alma”.
====

[[v11-1-13]]

^<<v11-1-13,13>>^ Vai ter com o rei David, e diz-lhe: ‘Não foi o meu senhor, o rei, que jurou à sua serva: “O teu filho Salomão vai tornar-se rei depois de mim, e é ele quem se sentará no meu trono”? Então, porque é que Adonias se tornou rei?’

[[v11-1-14]]

^<<v11-1-14,14>>^ Enquanto ainda estiveres a falar com o rei, eu entrarei e confirmarei as tuas palavras.”

[[v11-1-15]]

^<<v11-1-15,15>>^ Assim, Bate-Seba entrou no quarto do rei. O rei era muito idoso, e Abisague, a sunamita, servia o rei.

[[v11-1-16]]

^<<v11-1-16,16>>^ Bate-Seba curvou-se e prostrou-se perante o rei. O rei perguntou: “Qual é o teu pedido?”

[[v11-1-17]]

^<<v11-1-17,17>>^ Ela respondeu: “Foi o meu senhor que jurou à sua serva por Jeová, seu Deus: ‘O teu filho Salomão vai tornar-se rei depois de mim, e é ele que se sentará no meu trono.’

[[v11-1-18]]

^<<v11-1-18,18>>^ Mas, agora, Adonias tornou-se rei, e o meu senhor, o rei, não sabe nada acerca disso.

[[v11-1-19]]

^<<v11-1-19,19>>^ Ele sacrificou touros, bezerros gordos^&#42;1^ e ovelhas, em grande quantidade, e convidou todos os filhos do rei, e também Abiatar, o sacerdote, e Joabe, o chefe do exército; mas não convidou Salomão, seu servo.

[NOTE]
====
. Ou: “animais cevados”.
====

[[v11-1-20]]

^<<v11-1-20,20>>^ E agora, meu senhor, o rei, os olhos de todo o Israel estão voltados para si, para que lhes diga quem se sentará no seu trono, como sucessor do meu senhor, o rei.

[[v11-1-21]]

^<<v11-1-21,21>>^ Caso contrário, assim que o meu senhor, o rei, for descansar com os seus antepassados, eu e o meu filho Salomão seremos considerados traidores.”

[[v11-1-22]]

^<<v11-1-22,22>>^ Enquanto ela ainda estava a falar com o rei, chegou Natã, o profeta.

[[v11-1-23]]

^<<v11-1-23,23>>^ Imediatamente informaram o rei: “O profeta Natã está aqui!” Ele entrou perante o rei e prostrou-se diante do rei com o rosto por terra.

[[v11-1-24]]

^<<v11-1-24,24>>^ Natã perguntou: “Meu senhor, o rei, por acaso disse: ‘Adonias vai tornar-se rei depois de mim, e é ele que se sentará no meu trono’?

[[v11-1-25]]

^<<v11-1-25,25>>^ Pois, hoje, ele foi sacrificar touros, bezerros gordos^&#42;1^ e ovelhas, em grande quantidade, e convidou todos os filhos do rei, os chefes do exército e Abiatar, o sacerdote. Eles estão lá a comer e a beber com ele, e estão a dizer: ‘Viva o rei Adonias!’

[NOTE]
====
. Ou: “animais cevados”.
====

[[v11-1-26]]

^<<v11-1-26,26>>^ Mas ele não me convidou a mim, seu servo, nem a Zadoque, o sacerdote, nem a Benaia, filho de Jeoiada, nem a Salomão, seu servo.

[[v11-1-27]]

^<<v11-1-27,27>>^ Por acaso, o meu senhor, o rei, autorizou isso sem dizer ao seu servo quem se deve sentar no seu trono como sucessor do meu senhor, o rei?”

[[v11-1-28]]

^<<v11-1-28,28>>^ Em vista disso, o rei David disse: “Chamem Bate-Seba.” Então, ela entrou e ficou de pé perante o rei.

[[v11-1-29]]

^<<v11-1-29,29>>^ E o rei fez o seguinte juramento: “Tão certo como vive Jeová, aquele que me livrou^&#42;1^ de todas as aflições,

[NOTE]
====
. Ou: “que resgatou a minha alma”.
====

[[v11-1-30]]

^<<v11-1-30,30>>^ assim como te jurei por Jeová, o Deus de Israel, dizendo: ‘O teu filho Salomão vai tornar-se rei depois de mim, e é ele que se sentará no meu trono no meu lugar!’, assim farei neste dia.”

[[v11-1-31]]

^<<v11-1-31,31>>^ Então, Bate-Seba curvou-se e prostrou-se com o rosto por terra perante o rei, e disse: “Que o meu senhor, o rei David, viva para sempre!”

[[v11-1-32]]

^<<v11-1-32,32>>^ O rei David disse imediatamente: “Chamem Zadoque, o sacerdote, Natã, o profeta, e Benaia, filho de Jeoiada.” Então, eles apresentaram-se perante o rei.

[[v11-1-33]]

^<<v11-1-33,33>>^ O rei disse-lhes: “Levem convosco os servos do vosso senhor, e façam o meu filho Salomão montar na minha mula e conduzam-no para baixo, a Giom.

[[v11-1-34]]

^<<v11-1-34,34>>^ Lá, Zadoque, o sacerdote, e Natã, o profeta, vão ungi-lo rei sobre Israel. Depois toquem a buzina e digam: ‘Viva o rei Salomão!’

[[v11-1-35]]

^<<v11-1-35,35>>^ Então, sigam-no de volta, e ele virá e irá sentar-se no meu trono. Ele será rei no meu lugar, e eu irei designá-lo como líder de Israel e de Judá.”

[[v11-1-36]]

^<<v11-1-36,36>>^ Em vista disso, Benaia, filho de Jeoiada, disse imediatamente ao rei: “Amém! Que Jeová, o Deus do meu senhor, o rei, o confirme.

[[v11-1-37]]

^<<v11-1-37,37>>^ Assim como Jeová esteve com o meu senhor, o rei, esteja também com Salomão, e que Ele faça o trono de Salomão maior do que o trono do meu senhor, o rei David.”

[[v11-1-38]]

^<<v11-1-38,38>>^ Então, Zadoque, o sacerdote, Natã, o profeta, Benaia, filho de Jeoiada, e os queretitas e os peletitas desceram e fizeram Salomão montar na mula que pertencia ao rei David, e conduziram-no a Giom.

[[v11-1-39]]

^<<v11-1-39,39>>^ E Zadoque, o sacerdote, trouxe da tenda o chifre com o óleo e ungiu Salomão; então começaram a tocar a buzina, e todo o povo começou a gritar: “Viva o rei Salomão!”

[[v11-1-40]]

^<<v11-1-40,40>>^ Depois, todo o povo subiu atrás dele, a tocar flautas e a alegrar-se muito, de modo que a terra tremia^&#42;1^ com o barulho deles.

[NOTE]
====
. Lit.: “fendeu-se”.
====

[[v11-1-41]]

^<<v11-1-41,41>>^ Ao acabarem de comer, Adonias e todos os seus convidados ouviram o barulho. Assim que Joabe ouviu o som da buzina, disse: “O que é que significa este alvoroço na cidade?”

[[v11-1-42]]

^<<v11-1-42,42>>^ Enquanto ainda falava, chegou Jonatã, filho de Abiatar, o sacerdote. Então, Adonias disse: “Entra, pois és um homem bom^&#42;1^ e deves trazer boas notícias.”

[NOTE]
====
. Ou: “de valor”.
====

[[v11-1-43]]

^<<v11-1-43,43>>^ Jonatã, porém, disse a Adonias: “Pelo contrário. O nosso senhor, o rei David, fez Salomão rei.

[[v11-1-44]]

^<<v11-1-44,44>>^ O rei enviou Zadoque, o sacerdote, Natã, o profeta, Benaia, filho de Jeoiada, e também os queretitas e os peletitas para acompanharem Salomão, e fizeram-no montar na mula que pertence ao rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ A seguir, Zadoque, o sacerdote, e Natã, o profeta, ungiram-no rei em Giom. Depois subiram de lá, alegrando-se, e a cidade está em alvoroço. Esse foi o barulho que vocês ouviram.

[[v11-1-46]]

^<<v11-1-46,46>>^ Além disso, Salomão sentou-se no trono real.

[[v11-1-47]]

^<<v11-1-47,47>>^ Outra coisa, os servos do rei foram dar os parabéns ao nosso senhor, o rei David, dizendo: ‘Que o seu Deus faça o nome de Salomão mais glorioso do que o seu nome, senhor, e que faça o trono dele maior do que o seu trono!’ Então, o rei curvou-se sobre a cama.

[[v11-1-48]]

^<<v11-1-48,48>>^ E o rei também disse: ‘Louvado seja Jeová, o Deus de Israel, que hoje providenciou alguém para se sentar no meu trono e permitiu que os meus próprios olhos vissem isso!’”

[[v11-1-49]]

^<<v11-1-49,49>>^ E todos os convidados de Adonias ficaram apavorados; levantaram-se e foram-se embora.

[[v11-1-50]]

^<<v11-1-50,50>>^ Adonias também ficou com medo por causa de Salomão. Por isso levantou-se e foi agarrar-se aos chifres do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ Então, informaram o rei Salomão: “Adonias ficou com medo do rei Salomão e agarrou-se aos chifres do altar, dizendo: ‘Que o rei Salomão primeiro me jure que não entregará o seu servo à morte pela espada.’”

[[v11-1-52]]

^<<v11-1-52,52>>^ Diante disso, Salomão disse: “Se ele se comportar de modo digno, nem sequer um fio de cabelo seu cairá no chão; mas, se se encontrar nele o que é mau, terá de morrer.”

[[v11-1-53]]

^<<v11-1-53,53>>^ Portanto, o rei Salomão mandou que o fizessem descer do altar. Ele entrou então e curvou-se perante o rei Salomão, e Salomão disse-lhe: “Vai para a tua casa.”

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]