include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-19-1]]

^<<v11-19-1,1>>^ Depois, Acabe contou a Jezabel tudo o que Elias tinha feito e como ele tinha matado todos os profetas com a espada.

[[v11-19-2]]

^<<v11-19-2,2>>^ Em vista disso, Jezabel enviou um mensageiro a Elias para lhe dizer: “Que os deuses me castiguem, e que o façam severamente, se amanhã, a esta hora, eu não te fizer o mesmo que fizeste a cada um^&#42;1^ daqueles profetas!”

[NOTE]
====
. Ou: “não fizer à tua alma o mesmo que fizeste à alma de cada um”.
====

[[v11-19-3]]

^<<v11-19-3,3>>^ Então, ele ficou com medo. Por isso, levantou-se e fugiu para salvar a sua vida.^&#42;1^ Ele chegou a Berseba, que fica em Judá, e deixou ali o seu ajudante.

[NOTE]
====
. Ou: “alma”.
====

[[v11-19-4]]

^<<v11-19-4,4>>^ Em seguida, entrou no deserto e caminhou durante um dia. Ao encontrar uma giesta-das-vassouras, sentou-se debaixo dela e pediu para morrer.^&#42;1^ Ele disse: “Já chega! Agora, ó Jeová, tira-me a vida,^&#42;2^ pois não sou melhor do que os meus antepassados.”

[NOTE]
====
. Ou: “para a sua alma morrer”.
. Ou: “alma”.
====

[[v11-19-5]]

^<<v11-19-5,5>>^ Depois, deitou-se e adormeceu debaixo da giesta-das-vassouras. De repente, um anjo tocou-lhe e disse-lhe: “Levanta-te e come.”

[[v11-19-6]]

^<<v11-19-6,6>>^ Quando ele olhou, junto à sua cabeça havia um pão redondo sobre pedras aquecidas e um jarro de água. Ele comeu, bebeu e deitou-se novamente.

[[v11-19-7]]

^<<v11-19-7,7>>^ Mais tarde, o anjo de Jeová veio pela segunda vez, tocou-lhe e disse: “Levanta-te e come, senão não aguentarás a viagem.”

[[v11-19-8]]

^<<v11-19-8,8>>^ Assim, ele levantou-se, comeu e bebeu, e, fortalecido por aquela comida, andou 40 dias e 40 noites até chegar a Horebe, o monte do verdadeiro Deus.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali, ele entrou numa caverna, onde passou a noite; de repente, veio a ele a palavra de Jeová, dizendo: “O que é que estás aqui a fazer, Elias?”

[[v11-19-10]]

^<<v11-19-10,10>>^ E ele respondeu: “Tenho sido muito zeloso por Jeová, o Deus dos exércitos, pois o povo de Israel abandonou o teu pacto, derrubou os teus altares e matou os teus profetas com a espada, e eu fui o único que sobrou. Agora, eles estão a tentar tirar-me a vida.”^&#42;1^

[NOTE]
====
. Ou: “estão à procura da minha alma”.
====

[[v11-19-11]]

^<<v11-19-11,11>>^ Ele, porém, disse: “Sai e fica de pé no monte, diante de Jeová.” E Jeová estava a passar, e um vento muito forte partia montes e despedaçava rochedos diante de Jeová, mas Jeová não estava no vento. Depois do vento houve um terramoto, mas Jeová não estava no terramoto.

[[v11-19-12]]

^<<v11-19-12,12>>^ Depois do terramoto houve um fogo, mas Jeová não estava no fogo. Depois do fogo ouviu-se uma voz calma, baixa.

[[v11-19-13]]

^<<v11-19-13,13>>^ Assim que Elias ouviu essa voz, cobriu o rosto com o seu manto oficial, saiu e ficou de pé à entrada da caverna. Então, uma voz perguntou-lhe: “O que é que estás aqui a fazer, Elias?”

[[v11-19-14]]

^<<v11-19-14,14>>^ E ele respondeu: “Tenho sido muito zeloso por Jeová, o Deus dos exércitos, pois o povo de Israel abandonou o teu pacto, derrubou os teus altares e matou os teus profetas com a espada, e eu fui o único que sobrou. Agora, eles estão a tentar tirar-me a vida.”^&#42;1^

[NOTE]
====
. Ou: “estão à procura da minha alma”.
====

[[v11-19-15]]

^<<v11-19-15,15>>^ Jeová disse-lhe: “Volta, e vai até ao deserto de Damasco. Ao chegares, deves ungir Hazael para ser rei da Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ E deves ungir Jeú, neto de Ninsi, para ser rei de Israel, e deves ungir Eliseu,^&#42;1^ filho de Safate, de Abel-Meolá, para ser profeta no teu lugar.

[NOTE]
====
. Que significa “Deus é salvação”.
====

[[v11-19-17]]

^<<v11-19-17,17>>^ Quem escapar da espada de Hazael, Jeú matará; e quem escapar da espada de Jeú, Eliseu matará.

[[v11-19-18]]

^<<v11-19-18,18>>^ E ainda tenho 7000 em Israel, todos os que não se ajoelharam diante de Baal e que não o beijaram.”

[[v11-19-19]]

^<<v11-19-19,19>>^ Assim, Elias partiu dali e encontrou Eliseu, filho de Safate. Eliseu estava a lavrar a terra, e tinha 12 pares de touros à sua frente; Eliseu estava com o décimo segundo par. Então, Elias foi ter com ele e pôs sobre ele o seu manto oficial.

[[v11-19-20]]

^<<v11-19-20,20>>^ Em vista disso, Eliseu deixou os touros, correu atrás de Elias e disse: “Por favor, deixa-me beijar o meu pai e a minha mãe. Depois irei seguir-te.” Ele disse-lhe: “Podes ir, pois o que fiz eu para te impedir?”

[[v11-19-21]]

^<<v11-19-21,21>>^ Portanto, ele voltou, pegou em dois touros e ofereceu-os em sacrifício. Com a madeira do arado e do jugo cozinhou a carne e deu-a ao povo, e eles comeram. Depois, ele seguiu Elias e começou a servi-lo.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]