include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-21-1]]

^<<v11-21-1,1>>^ Depois disso, aconteceu o caso da vinha que pertencia a Nabote, o jezreelita. Essa vinha ficava em Jezreel, ao lado do palácio de Acabe, rei de Samaria.

[[v11-21-2]]

^<<v11-21-2,2>>^ Acabe disse a Nabote: “Dá-me a tua vinha para eu fazer uma horta, pois fica perto da minha casa. Vou dar-te em troca uma vinha melhor. Ou, se preferires, vou dar-te o seu valor em dinheiro.”

[[v11-21-3]]

^<<v11-21-3,3>>^ Contudo, Nabote disse a Acabe: “É impensável, por respeito a Jeová, dar-lhe a herança dos meus antepassados.”

[[v11-21-4]]

^<<v11-21-4,4>>^ Portanto, Acabe entrou na sua casa, contrariado e abatido porque Nabote, o jezreelita, lhe tinha dito: “Não te darei a herança dos meus antepassados.” Então, ele deitou-se na sua cama, virou a cara e não quis comer nada.

[[v11-21-5]]

^<<v11-21-5,5>>^ Jezabel, sua esposa, foi falar com ele e perguntou-lhe: “Porque é que tu estás^&#42;1^ tão triste a ponto de não quereres comer?”

[NOTE]
====
. Lit.: “o teu espírito está”.
====

[[v11-21-6]]

^<<v11-21-6,6>>^ Ele respondeu-lhe: “Porque eu disse a Nabote, o jezreelita: ‘Vende-me a tua vinha. Ou, se preferires, deixa-me dar-te outra vinha em troca.’ Contudo, ele disse: ‘Não lhe darei a minha vinha.’”

[[v11-21-7]]

^<<v11-21-7,7>>^ Jezabel, sua esposa, disse-lhe: “Não és tu o rei de Israel? Levanta-te, come alguma coisa, e que o teu coração se alegre. Vou dar-te a vinha de Nabote, o jezreelita.”

[[v11-21-8]]

^<<v11-21-8,8>>^ Assim, ela escreveu cartas em nome de Acabe, selou-as com o selo dele e enviou as cartas aos anciãos e aos nobres que moravam na cidade de Nabote.

[[v11-21-9]]

^<<v11-21-9,9>>^ Ela escreveu nas cartas: “Proclamem um jejum e façam Nabote sentar-se diante do povo.

[[v11-21-10]]

^<<v11-21-10,10>>^ E façam dois homens imprestáveis sentar-se à frente dele e testemunhar contra ele, dizendo: ‘Amaldiçoaste a Deus e o rei!’ Depois, levem-no para fora da cidade e apedrejem-no até à morte.”

[[v11-21-11]]

^<<v11-21-11,11>>^ Portanto, os homens da cidade de Nabote, os anciãos e os nobres que moravam naquela cidade, fizeram exatamente como estava escrito nas cartas que Jezabel lhes tinha enviado.

[[v11-21-12]]

^<<v11-21-12,12>>^ Proclamaram um jejum e fizeram Nabote sentar-se diante do povo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então, dois homens imprestáveis vieram, sentaram-se à frente de Nabote e testemunharam contra ele perante o povo, dizendo: “Nabote amaldiçoou a Deus e o rei!” Depois, levaram-no para fora da cidade e apedrejaram-no até à morte.

[[v11-21-14]]

^<<v11-21-14,14>>^ Então, mandaram dizer a Jezabel: “Nabote foi apedrejado e está morto.”

[[v11-21-15]]

^<<v11-21-15,15>>^ Assim que Jezabel soube que Nabote tinha sido apedrejado até à morte, ela disse a Acabe: “Levanta-te, toma posse da vinha que Nabote, o jezreelita, não te quis vender, pois Nabote já não está vivo. Ele está morto.”

[[v11-21-16]]

^<<v11-21-16,16>>^ Quando Acabe soube que Nabote estava morto, desceu imediatamente à vinha de Nabote, o jezreelita, para tomar posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Todavia, Elias, o tisbita, recebeu a seguinte palavra de Jeová:

[[v11-21-18]]

^<<v11-21-18,18>>^ “Levanta-te e vai depressa ter com Acabe, rei de Israel, que está em Samaria. Ele está na vinha de Nabote, pois foi até lá para tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ Diz-lhe: ‘Assim diz Jeová: “Assassinaste um homem e também ficaste com o seu terreno?”’^&#42;1^ Diz-lhe também: ‘Assim diz Jeová: “No lugar onde os cães lamberam o sangue de Nabote, os cães lamberão o teu próprio sangue.”’”

[NOTE]
====
. Lit.: “tomaste posse do seu terreno”.
====

[[v11-21-20]]

^<<v11-21-20,20>>^ Acabe disse a Elias: “Então, meu inimigo, encontraste-me!” Ele respondeu: “Encontrei-o. Deus disse: ‘Visto que estás determinado^&#42;1^ a fazer o que é mau aos olhos de Jeová,

[NOTE]
====
. Lit.: “te vendeste”.
====

[[v11-21-21]]

^<<v11-21-21,21>>^ trarei uma calamidade sobre ti, e vou exterminar-te^&#42;1^ e eliminar em Israel todos os do sexo masculino^&#42;2^ da casa de Acabe, incluindo o desamparado e o fraco.

[NOTE]
====
. Ou: “varrer-te”.
. Lit.: “todo aquele que urina contra o muro”. Expressão hebraica que indica desprezo e se refere a homens.
====

[[v11-21-22]]

^<<v11-21-22,22>>^ E farei à tua casa o mesmo que fiz à casa de Jeroboão, filho de Nebate, e à casa de Baasa, filho de Aías, pois provocaste a minha ira e fizeste Israel pecar.’

[[v11-21-23]]

^<<v11-21-23,23>>^ Jeová também falou a respeito de Jezabel: ‘Os cães devorarão Jezabel no terreno de Jezreel.

[[v11-21-24]]

^<<v11-21-24,24>>^ Os da casa de Acabe que morrerem na cidade serão devorados pelos cães; e os que morrerem no campo serão comidos pelas aves dos céus.

[[v11-21-25]]

^<<v11-21-25,25>>^ Certamente, nunca houve ninguém tão determinado^&#42;1^ a fazer o que é mau aos olhos de Jeová como Acabe, que foi instigado por Jezabel, sua esposa.

[NOTE]
====
. Lit.: “que se vendeu”.
====

[[v11-21-26]]

^<<v11-21-26,26>>^ Ele agiu da maneira mais detestável possível, seguindo ídolos repugnantes,^&#42;1^ como faziam todos os amorreus, que Jeová tinha expulsado de diante dos israelitas.’”

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v11-21-27]]

^<<v11-21-27,27>>^ Assim que Acabe ouviu estas palavras, rasgou as suas roupas, cobriu o corpo com serapilheira^&#42;1^ e começou a jejuar; ele deitava-se na serapilheira e andava abatido.

[NOTE]
====
. Veja o Glossário.
====

[[v11-21-28]]

^<<v11-21-28,28>>^ Então, Elias, o tisbita, recebeu a seguinte palavra de Jeová:

[[v11-21-29]]

^<<v11-21-29,29>>^ “Viste como é que Acabe se humilhou por minha causa? Visto que se humilhou diante de mim, não trarei a calamidade durante a sua vida. Trarei a calamidade sobre a casa dele nos dias do seu filho.”

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]