include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-3-1]]

^<<v11-3-1,1>>^ Salomão aliou-se por casamento ao Faraó, rei do Egito. Ele casou-se com^&#42;1^ a filha do Faraó. Ele levou-a para a Cidade de David até que acabasse a construção da sua própria casa e da casa de Jeová, e da muralha à volta de Jerusalém.

[NOTE]
====
. Ou: “tomou”.
====

[[v11-3-2]]

^<<v11-3-2,2>>^ Contudo, o povo ainda oferecia sacrifícios nos altos sagrados, porque até àquela época ainda não se tinha construído uma casa para o nome de Jeová.

[[v11-3-3]]

^<<v11-3-3,3>>^ Salomão continuava a amar a Jeová, por andar nos decretos de David, seu pai, só que oferecia sacrifícios e queimava ofertas nos altos sagrados.

[[v11-3-4]]

^<<v11-3-4,4>>^ O rei foi a Gibeão para oferecer sacrifícios, pois aquele era o alto sagrado mais destacado.^&#42;1^ Salomão ofereceu mil sacrifícios queimados naquele altar.

[NOTE]
====
. Lit.: “o grande alto”.
====

[[v11-3-5]]

^<<v11-3-5,5>>^ Em Gibeão, Jeová apareceu de noite a Salomão num sonho. Deus disse-lhe: “Pede-me o que gostarias que eu te desse.”

[[v11-3-6]]

^<<v11-3-6,6>>^ Então, Salomão disse: “Tu demonstraste grande amor leal ao teu servo David, meu pai, pois ele andou diante de ti de modo fiel e justo, e com um coração reto. E tu continuas a demonstrar-lhe este grande amor leal até ao dia de hoje, dando-lhe um filho para se sentar no seu trono.

[[v11-3-7]]

^<<v11-3-7,7>>^ E agora, Jeová, meu Deus, tu fizeste o teu servo rei no lugar de David, meu pai, embora eu seja apenas um jovem inexperiente.^&#42;1^

[NOTE]
====
. Lit.: “e eu sou um rapazinho, e não sei sair nem entrar”.
====

[[v11-3-8]]

^<<v11-3-8,8>>^ O teu servo está entre o povo que escolheste, um povo tão grande que não pode ser contado nem enumerado.

[[v11-3-9]]

^<<v11-3-9,9>>^ Portanto, concede ao teu servo um coração obediente para julgar o teu povo, para discernir entre o bem e o mal, pois quem é que pode julgar este teu povo, que é tão numeroso?”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “difícil”. Lit.: “pesado”.
====

[[v11-3-10]]

^<<v11-3-10,10>>^ O pedido que Salomão fez agradou a Jeová.

[[v11-3-11]]

^<<v11-3-11,11>>^ Então Deus disse-lhe: “Visto que pediste isso, e não pediste uma vida longa,^&#42;1^ nem riquezas, nem a morte^&#42;2^ dos teus inimigos, mas pediste entendimento para ouvir questões judiciais,

[NOTE]
====
. Lit.: “muitos dias”.
. Ou: “alma”.
====

[[v11-3-12]]

^<<v11-3-12,12>>^ farei o que tu pediste. Vou dar-te um coração sábio e entendido, de modo que nunca existiu nem existirá ninguém igual a ti.

[[v11-3-13]]

^<<v11-3-13,13>>^ Além disso, vou dar-te também o que não pediste, tanto riquezas como glória, de modo que não existirá nenhum outro rei igual a ti, durante a tua vida.^&#42;1^

[NOTE]
====
. Lit.: “todos os teus dias”.
====

[[v11-3-14]]

^<<v11-3-14,14>>^ E, se tu andares nos meus caminhos, por guardares os meus decretos e os meus mandamentos, assim como fez David, teu pai, também te vou dar uma vida longa.”^&#42;1^

[NOTE]
====
. Lit.: “prolongar os teus dias”.
====

[[v11-3-15]]

^<<v11-3-15,15>>^ Quando Salomão acordou, percebeu que tinha sido um sonho. Voltou então para Jerusalém, ficou de pé diante da Arca do Pacto de Jeová e ofereceu sacrifícios queimados e ofertas de participação em comum. Fez também um banquete para todos os seus servos.

[[v11-3-16]]

^<<v11-3-16,16>>^ Naqueles dias, duas prostitutas foram ter com o rei e ficaram de pé diante dele.

[[v11-3-17]]

^<<v11-3-17,17>>^ Uma das mulheres disse: “Por favor, meu senhor, eu e esta mulher moramos na mesma casa, e eu dei à luz enquanto ela estava em casa.

[[v11-3-18]]

^<<v11-3-18,18>>^ Três dias depois de eu ter dado à luz, esta mulher também deu à luz. Estávamos juntas, só nós as duas; não havia mais ninguém connosco em casa.

[[v11-3-19]]

^<<v11-3-19,19>>^ Durante a noite, o filho desta mulher morreu, porque ela se deitou sobre ele.

[[v11-3-20]]

^<<v11-3-20,20>>^ Então, ela levantou-se a meio da noite, enquanto eu, a escrava do meu senhor, dormia, e tirou o meu filho do meu lado e colocou-o ao lado^&#42;1^ dela; e colocou o filho dela, que estava morto, nos meus braços.

[NOTE]
====
. Ou: “nos braços”. Lit.: “no seio”.
====

[[v11-3-21]]

^<<v11-3-21,21>>^ Quando me levantei de manhã para amamentar o meu filho, percebi que estava morto. Assim, olhei bem para ele e vi que não era o filho que eu tinha dado à luz.”

[[v11-3-22]]

^<<v11-3-22,22>>^ Contudo, a outra mulher disse: “Não! O meu filho é o vivo, e o teu filho é o morto!” E a primeira mulher dizia: “Não! O teu filho é o morto, e o meu filho é o vivo!” E assim discutiam perante o rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Por fim, o rei disse: “Uma diz: ‘O meu filho é o que está vivo, e o teu filho é o que está morto!’ e a outra diz: ‘Não! O teu filho é o morto, e o meu filho é o vivo!’”

[[v11-3-24]]

^<<v11-3-24,24>>^ O rei disse: “Tragam-me uma espada.” Assim, trouxeram uma espada ao rei.

[[v11-3-25]]

^<<v11-3-25,25>>^ E o rei disse: “Cortem o menino vivo em dois, e deem metade a uma mulher e metade à outra.”

[[v11-3-26]]

^<<v11-3-26,26>>^ Imediatamente, a mulher cujo filho era o vivo, movida pela compaixão pelo seu filho, implorou ao rei: “Por favor, meu senhor! Deem-lhe o menino vivo! Não o matem!” A outra mulher, porém, dizia: “Ele não será nem meu nem teu! Podem cortá-lo em dois!”

[[v11-3-27]]

^<<v11-3-27,27>>^ Então, o rei disse: “Deem o menino vivo à primeira mulher, não o matem! Ela é a mãe.”

[[v11-3-28]]

^<<v11-3-28,28>>^ E todo o Israel soube da decisão judicial que o rei tinha proferido, e ficaram impressionados^&#42;1^ com o rei, pois viram que a sabedoria de Deus estava com ele para executar a justiça.

[NOTE]
====
. Lit.: “atemorizados”.
====

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]