include::./index.adoc[]

[[v11-12-0]]
=== 1 Reis, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-12-1]]

^<<v11-12-1,1>>^ Roboão foi a Siquém, pois todo o Israel tinha ido a Siquém para o fazer rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ E Jeroboão, filho de Nebate, soube disso (ele ainda estava no Egito, pois tinha fugido por causa do rei Salomão e estava a morar no Egito).

[[v11-12-3]]

^<<v11-12-3,3>>^ Então, mandaram chamá-lo. Depois, Jeroboão e toda a congregação de Israel foram ter com Roboão e disseram:

[[v11-12-4]]

^<<v11-12-4,4>>^ “O seu pai tornou duro o nosso jugo. Mas, se o senhor aliviar o serviço duro e tornar mais leve o jugo pesado^&#42;1^ que o seu pai colocou sobre nós, iremos servi-lo.”

[NOTE]
====
. Ou: “opressivo”.
====

[[v11-12-5]]

^<<v11-12-5,5>>^ Em vista disso, ele disse-lhes: “Vão-se embora, e venham ter comigo daqui a três dias.” Portanto, o povo foi-se embora.

[[v11-12-6]]

^<<v11-12-6,6>>^ Depois, o rei Roboão consultou os homens mais velhos^&#42;1^ que tinham servido como conselheiros de Salomão, seu pai, durante a sua vida. Ele perguntou: “O que é que me aconselham a responder a este povo?”

[NOTE]
====
. Ou: “anciãos”.
====

[[v11-12-7]]

^<<v11-12-7,7>>^ Eles responderam-lhe: “Se hoje o senhor se tornar servo deste povo, atender ao seu pedido e lhes der uma resposta favorável, eles serão sempre seus servos.”

[[v11-12-8]]

^<<v11-12-8,8>>^ No entanto, ele rejeitou o conselho dos homens mais velhos^&#42;1^ e consultou os jovens que tinham crescido com ele e que agora eram seus assistentes.

[NOTE]
====
. Ou: “anciãos”.
====

[[v11-12-9]]

^<<v11-12-9,9>>^ Ele perguntou-lhes: “Que conselho me dão? Como é que devemos responder a este povo que me disse: ‘Torne mais leve o jugo que o seu pai colocou sobre nós’?”

[[v11-12-10]]

^<<v11-12-10,10>>^ Os jovens que tinham crescido com ele responderam-lhe: “A este povo que lhe disse: ‘O seu pai tornou pesado o nosso jugo, mas o senhor deve torná-lo mais leve para nós’, o senhor deve dizer o seguinte: ‘O meu dedo mínimo será mais grosso do que a cintura do meu pai.

[[v11-12-11]]

^<<v11-12-11,11>>^ O meu pai impôs-vos um jugo pesado, mas eu vou torná-lo ainda mais pesado. O meu pai castigou-vos com chicotes, mas eu vou castigar-vos com chicotes farpados.’”

[[v11-12-12]]

^<<v11-12-12,12>>^ Jeroboão e todo o povo foram ter com Roboão no terceiro dia, assim como o rei tinha dito: “Venham ter comigo daqui a três dias.”

[[v11-12-13]]

^<<v11-12-13,13>>^ Contudo, o rei deu uma resposta dura ao povo, rejeitando o conselho dos homens mais velhos.^&#42;1^

[NOTE]
====
. Ou: “anciãos”.
====

[[v11-12-14]]

^<<v11-12-14,14>>^ Seguindo o conselho dos jovens, ele disse: “O meu pai tornou pesado o vosso jugo, mas eu vou torná-lo ainda mais pesado. O meu pai castigou-vos com chicotes, mas eu vou castigar-vos com chicotes farpados.”

[[v11-12-15]]

^<<v11-12-15,15>>^ Portanto, o rei não escutou o povo, porque o que estava a acontecer era da parte de Jeová, para que se cumprisse a palavra que Jeová tinha transmitido por meio de Aías, o silonita, a Jeroboão, filho de Nebate.

[[v11-12-16]]

^<<v11-12-16,16>>^ Quando todo o Israel viu que o rei não os quis escutar, o povo disse ao rei: “Que parte temos nós com David? Não temos herança com o filho de Jessé! Vão para os vossos deuses, ó Israel. Agora, cuide da sua própria casa, ó David!” Com isso os israelitas voltaram para as suas casas.^&#42;1^

[NOTE]
====
. Lit.: “tendas”.
====

[[v11-12-17]]

^<<v11-12-17,17>>^ Porém, Roboão continuou a reinar sobre os israelitas que moravam nas cidades de Judá.

[[v11-12-18]]

^<<v11-12-18,18>>^ A seguir, o rei Roboão enviou-lhes Adorão, que supervisionava os convocados para trabalho obrigatório, mas todo o Israel o apedrejou até à morte. O rei Roboão conseguiu subir para o seu carro de guerra e fugiu para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ E os israelitas rebelaram-se contra a casa de David e continuam assim até ao dia de hoje.

[[v11-12-20]]

^<<v11-12-20,20>>^ Assim que todo o Israel ouviu que Jeroboão tinha voltado, mandaram chamá-lo à assembleia e fizeram-no rei sobre todo o Israel. Ninguém apoiou a casa de David, a não ser a tribo de Judá.

[[v11-12-21]]

^<<v11-12-21,21>>^ Quando Roboão chegou a Jerusalém, reuniu imediatamente toda a casa de Judá e a tribo de Benjamim, 180 000 guerreiros treinados,^&#42;1^ a fim de lutar contra a casa de Israel e restituir o reinado a Roboão, filho de Salomão.

[NOTE]
====
. Lit.: “escolhidos”.
====

[[v11-12-22]]

^<<v11-12-22,22>>^ Então, Semaías, o homem do verdadeiro Deus, recebeu a seguinte palavra do verdadeiro Deus:

[[v11-12-23]]

^<<v11-12-23,23>>^ “Diz a Roboão, filho de Salomão e rei de Judá, e a toda a casa de Judá, de Benjamim e ao restante do povo:

[[v11-12-24]]

^<<v11-12-24,24>>^ ‘Assim diz Jeová: “Não vão à guerra contra os vossos irmãos israelitas. Volte cada um para a sua casa, pois fui eu que fiz isto acontecer.”’” Eles obedeceram à palavra de Jeová e voltaram para casa, assim como Jeová lhes tinha ordenado.

[[v11-12-25]]

^<<v11-12-25,25>>^ E Jeroboão construiu^&#42;1^ Siquém na região montanhosa de Efraim, e ficou ali a morar. Depois saiu de Siquém e construiu^&#42;2^ Penuel.

[NOTE]
====
. Ou: “fortificou”.
. Ou: “fortificou”.
====

[[v11-12-26]]

^<<v11-12-26,26>>^ Jeroboão disse no seu coração: “Agora o reino voltará para a casa de David.

[[v11-12-27]]

^<<v11-12-27,27>>^ Se este povo continuar a subir a Jerusalém para oferecer sacrifícios na casa de Jeová, o coração deste povo voltará para o seu senhor, Roboão, rei de Judá. Sim, eles irão matar-me e voltarão para Roboão, rei de Judá.”

[[v11-12-28]]

^<<v11-12-28,28>>^ Depois de se aconselhar, o rei fez dois bezerros de ouro e disse ao povo: “É muito difícil para vocês subir a Jerusalém. Aqui está o teu Deus, ó Israel, que te tirou da terra do Egito.”

[[v11-12-29]]

^<<v11-12-29,29>>^ Então, colocou um bezerro em Betel e o outro em Dã.

[[v11-12-30]]

^<<v11-12-30,30>>^ E isto fez o povo pecar; eles iam até Dã para adorar o bezerro que lá estava.

[[v11-12-31]]

^<<v11-12-31,31>>^ Ele fez santuários nos altos sagrados e designou como sacerdotes homens do povo que não eram levitas.

[[v11-12-32]]

^<<v11-12-32,32>>^ Jeroboão também instituiu uma festividade no décimo quinto dia do oitavo mês, igual à festividade que se realizava em Judá. No altar que fez em Betel, ele oferecia sacrifícios aos bezerros que tinha feito; e em Betel designou sacerdotes para os altos sagrados que tinha feito.

[[v11-12-33]]

^<<v11-12-33,33>>^ E no décimo quinto dia do oitavo mês, no mês que ele mesmo tinha escolhido, começou a fazer ofertas sobre o altar que tinha feito em Betel. Ele instituiu uma festividade para o povo de Israel e subiu ao altar para fazer ofertas e fumo sacrificial.

'''

xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]