include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-2-1]]

^<<v11-2-1,1>>^ Quando se aproximou a morte de David, ele deu as seguintes instruções ao seu filho Salomão:

[[v11-2-2]]

^<<v11-2-2,2>>^ “Estou quase a morrer.^&#42;1^ Portanto, sê forte e sê um homem.

[NOTE]
====
. Lit.: “Estou a ir no caminho de toda a terra.”
====

[[v11-2-3]]

^<<v11-2-3,3>>^ Cumpre a tua obrigação para com Jeová, teu Deus, por andares nos seus caminhos e obedeceres aos seus decretos, aos seus mandamentos, às suas decisões judiciais e às suas advertências,^&#42;1^ conforme estão escritos na Lei de Moisés. Assim, serás bem-sucedido^&#42;2^ em tudo o que fizeres e onde quer que fores.

[NOTE]
====
. Ou: “aos seus lembretes”.
. Ou: “agirás com sabedoria”.
====

[[v11-2-4]]

^<<v11-2-4,4>>^ E Jeová cumprirá a promessa que fez a meu respeito: ‘Se os teus filhos prestarem atenção ao caminho deles, por andarem fielmente diante de mim, de todo o coração e de toda a alma,^&#42;1^ haverá sempre um descendente teu^&#42;2^ sentado no trono de Israel.’

[NOTE]
====
. Veja o Glossário.
. Lit.: “não será decepado de ti um homem”.
====

[[v11-2-5]]

^<<v11-2-5,5>>^ “Além disso, bem sabes o que me fez Joabe, filho de Zeruia, o que ele fez aos dois chefes dos exércitos de Israel, Abner, filho de Ner, e Amasa, filho de Jeter. Ele matou-os, derramando sangue de guerra em tempo de paz e manchou com sangue de guerra o cinto que tinha na cintura e as sandálias que tinha nos pés.

[[v11-2-6]]

^<<v11-2-6,6>>^ Age segundo a tua sabedoria e não deixes que os seus cabelos brancos desçam em paz à Sepultura.^&#42;1^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v11-2-7]]

^<<v11-2-7,7>>^ “Mas deves demonstrar amor leal aos filhos de Barzilai, o gileadita; eles devem estar entre os que comem à tua mesa, pois ficaram do meu lado quando fugi do teu irmão Absalão.

[[v11-2-8]]

^<<v11-2-8,8>>^ “Perto de ti vive Simei, filho de Gera, benjaminita de Baurim. Foi ele quem me amaldiçoou com uma terrível maldição no dia em que fui a Maanaim; mas, quando ele desceu ao meu encontro no Jordão, eu jurei-lhe por Jeová: ‘Não te entregarei à morte pela espada.’

[[v11-2-9]]

^<<v11-2-9,9>>^ Agora não o deixes impune, pois tu és um homem sábio e sabes o que deves fazer com ele. Faz os seus cabelos brancos descer com sangue à Sepultura.”^&#42;1^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v11-2-10]]

^<<v11-2-10,10>>^ Então, David descansou com os seus antepassados e foi enterrado na Cidade de David.

[[v11-2-11]]

^<<v11-2-11,11>>^ A duração^&#42;1^ do reinado de David sobre Israel foi de 40 anos. Em Hébron, ele reinou durante 7 anos, e em Jerusalém reinou durante 33 anos.

[NOTE]
====
. Lit.: “Os dias”.
====

[[v11-2-12]]

^<<v11-2-12,12>>^ Salomão sentou-se então no trono de David, seu pai. Aos poucos, o seu reinado ficou firmemente estabelecido.

[[v11-2-13]]

^<<v11-2-13,13>>^ Passado algum tempo, Adonias, filho de Hagite, foi falar com Bate-Seba, mãe de Salomão. Ela perguntou: “A tua vinda é pacífica?” Ele respondeu: “É pacífica.”

[[v11-2-14]]

^<<v11-2-14,14>>^ Então, ele disse: “Tenho algo para lhe dizer.” Ela disse: “Diz.”

[[v11-2-15]]

^<<v11-2-15,15>>^ Ele continuou: “A senhora bem sabe que o reinado ia tornar-se meu, e todo o Israel esperava^&#42;1^ que eu fosse rei; mas o reinado escapou das minhas mãos e passou a ser do meu irmão, pois era da vontade de Jeová que ele fosse rei.

[NOTE]
====
. Lit.: “tinha fixado as suas faces em”.
====

[[v11-2-16]]

^<<v11-2-16,16>>^ Mas agora, tenho apenas um pedido para lhe fazer. Não me recuse esse pedido.” Portanto, ela disse-lhe: “Diz.”

[[v11-2-17]]

^<<v11-2-17,17>>^ Ele disse então: “Por favor, peça a Salomão, o rei, que me dê Abisague, a sunamita, como esposa. Ele não lhe recusará esse pedido.”

[[v11-2-18]]

^<<v11-2-18,18>>^ Então Bate-Seba disse: “Está bem! Eu falarei por ti ao rei.”

[[v11-2-19]]

^<<v11-2-19,19>>^ Assim, Bate-Seba compareceu perante o rei Salomão para falar com ele a favor de Adonias. O rei levantou-se imediatamente para ir ter com ela e curvou-se diante dela. Depois, sentou-se no seu trono e mandou colocar um trono para a mãe do rei, para que ela se sentasse à sua direita.

[[v11-2-20]]

^<<v11-2-20,20>>^ E ela disse: “Tenho um pequeno pedido para lhe fazer. Não me recuse esse pedido.” Então o rei respondeu: “Faça-o, minha mãe, pois não recusarei o seu pedido.”

[[v11-2-21]]

^<<v11-2-21,21>>^ Ela disse: “Dê Abisague, a sunamita, como esposa ao seu irmão Adonias.”

[[v11-2-22]]

^<<v11-2-22,22>>^ Em resposta, o rei Salomão disse à sua mãe: “Porque é que está a pedir Abisague, a sunamita, para Adonias? Só lhe falta pedir também o reinado para ele, pois ele é o meu irmão mais velho, e tem o apoio de Abiatar, o sacerdote, e de Joabe, filho de Zeruia.”

[[v11-2-23]]

^<<v11-2-23,23>>^ Com isso, o rei Salomão jurou por Jeová: “Que Deus me castigue, e que o faça severamente, se Adonias não pagar com a própria vida^&#42;1^ por ter feito esse pedido.

[NOTE]
====
. Ou: “alma”.
====

[[v11-2-24]]

^<<v11-2-24,24>>^ E agora, tão certo como vive Jeová, aquele que me estabeleceu firmemente e me colocou no trono de David, meu pai, e que edificou uma casa^&#42;1^ para mim, assim como prometeu, hoje, Adonias será morto.”

[NOTE]
====
. Ou: “dinastia”.
====

[[v11-2-25]]

^<<v11-2-25,25>>^ O rei Salomão enviou imediatamente Benaia, filho de Jeoiada, que foi e atacou^&#42;1^ Adonias, e ele morreu.

[NOTE]
====
. Ou: “se lançou sobre”.
====

[[v11-2-26]]

^<<v11-2-26,26>>^ Ao sacerdote Abiatar, o rei disse: “Vai para os teus campos em Anatote! Tu mereces morrer, mas neste dia não te matarei, porque carregaste a Arca do Soberano Senhor Jeová diante de David, meu pai, e compartilhaste todas as dificuldades que o meu pai passou.”

[[v11-2-27]]

^<<v11-2-27,27>>^ Portanto, Salomão removeu Abiatar do sacerdócio de Jeová, para que se cumprisse a palavra de Jeová contra a casa de Eli, em Silo.

[[v11-2-28]]

^<<v11-2-28,28>>^ Quando a notícia chegou a Joabe — pois Joabe tinha apoiado Adonias, embora não tivesse apoiado Absalão —, Joabe fugiu para a tenda de Jeová e agarrou-se aos chifres do altar.

[[v11-2-29]]

^<<v11-2-29,29>>^ Então, informaram o rei Salomão: “Joabe fugiu para a tenda de Jeová e está ao lado do altar.” Assim, Salomão enviou Benaia, filho de Jeoiada, dizendo: “Vai, mata-o!”

[[v11-2-30]]

^<<v11-2-30,30>>^ Por isso, Benaia foi à tenda de Jeová e disse-lhe: “O rei diz: ‘Vem para fora!’” Contudo, ele respondeu: “Não! Vou morrer aqui.” Então, Benaia levou a informação de volta ao rei: “Foi assim que Joabe falou, foi assim que me respondeu.”

[[v11-2-31]]

^<<v11-2-31,31>>^ Em vista disso, o rei disse-lhe: “Faz como ele mesmo disse, mata-o e enterra-o; remove de mim e da casa do meu pai o sangue inocente que Joabe derramou.

[[v11-2-32]]

^<<v11-2-32,32>>^ Jeová fará o sangue que ele derramou recair sobre a sua própria cabeça, pois sem o conhecimento do meu pai, David, ele atacou e matou com a espada dois homens mais justos e melhores do que ele: Abner, filho de Ner e chefe do exército de Israel, e Amasa, filho de Jeter e chefe do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ O sangue deles recairá sobre a cabeça de Joabe e sobre a cabeça da sua descendência^&#42;1^ para sempre; mas, para David, a sua descendência,^&#42;2^ a sua casa e o seu trono, que haja paz da parte de Jeová para sempre.”

[NOTE]
====
. Ou: “dos seus descendentes”.
. Ou: “os seus descendentes”.
====

[[v11-2-34]]

^<<v11-2-34,34>>^ Então Benaia, filho de Jeoiada, subiu, atacou Joabe e matou-o; e ele foi enterrado na sua casa, no deserto.

[[v11-2-35]]

^<<v11-2-35,35>>^ Depois o rei designou Benaia, filho de Jeoiada, sobre o exército, no lugar de Joabe; e o rei designou Zadoque, o sacerdote, no lugar de Abiatar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Então, o rei mandou chamar Simei e disse-lhe: “Constrói uma casa em Jerusalém e fica a morar ali; não saias da cidade para nenhum lugar.

[[v11-2-37]]

^<<v11-2-37,37>>^ No dia em que saíres e atravessares o vale do Cédron, podes ter a certeza de que morrerás. O teu sangue recairá sobre a tua própria cabeça.”

[[v11-2-38]]

^<<v11-2-38,38>>^ Simei disse ao rei: “O que o senhor disse é justo. O seu servo fará assim como o meu senhor, o rei, falou.” E Simei ficou ainda bastante tempo em Jerusalém.

[[v11-2-39]]

^<<v11-2-39,39>>^ Todavia, três anos depois, dois escravos de Simei fugiram e procuraram refúgio junto de Aquis, filho de Maacá e rei de Gate. Quando contaram a Simei: “Os teus escravos estão em Gate”,

[[v11-2-40]]

^<<v11-2-40,40>>^ Simei selou imediatamente o seu jumento e foi ter com Aquis, a Gate, à procura dos seus escravos. Quando Simei voltou de Gate com os seus escravos,

[[v11-2-41]]

^<<v11-2-41,41>>^ informaram Salomão: “Simei saiu de Jerusalém, foi a Gate e voltou.”

[[v11-2-42]]

^<<v11-2-42,42>>^ Em vista disso, o rei mandou chamar Simei e disse-lhe: “Não te pus sob juramento por Jeová e não te avisei: ‘No dia em que saíres daqui e fores para qualquer outro lugar, podes ter a certeza de que morrerás’? E tu não me disseste: ‘O que o senhor está a dizer é justo, eu obedecerei’?

[[v11-2-43]]

^<<v11-2-43,43>>^ Então, porque é que não cumpriste o juramento que fizeste perante Jeová e a ordem que te dei?”

[[v11-2-44]]

^<<v11-2-44,44>>^ O rei disse então a Simei: “No teu coração tu sabes muito bem todo o mal que fizeste a David, meu pai; e Jeová fará o mal que causaste recair sobre a tua própria cabeça.

[[v11-2-45]]

^<<v11-2-45,45>>^ Mas o rei Salomão será abençoado, e o trono de David ficará firmemente estabelecido perante Jeová para sempre.”

[[v11-2-46]]

^<<v11-2-46,46>>^ Com isso, o rei deu ordem a Benaia, filho de Jeoiada, que saiu e atacou Simei, e ele morreu.
Assim, o reino ficou firmemente estabelecido nas mãos de Salomão.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]