include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-13-1]]

^<<v11-13-1,1>>^ Por ordem de Jeová, um homem de Deus foi de Judá até Betel e chegou quando Jeroboão estava junto ao altar para fazer fumo sacrificial.

[[v11-13-2]]

^<<v11-13-2,2>>^ Então, por ordem de Jeová, o homem proclamou contra o altar: “Ó altar, altar! Assim diz Jeová: ‘Na casa de David nascerá um filho que se chamará Josias. Ele sacrificará sobre ti os sacerdotes dos altos sagrados, os que fazem fumo sacrificial sobre ti, e queimará sobre ti ossos de homens.’”

[[v11-13-3]]

^<<v11-13-3,3>>^ Naquele dia o homem de Deus deu um sinal,^&#42;1^ dizendo: “Este é o sinal^&#42;2^ que Jeová declarou: ‘O altar irá rachar-se, e as cinzas^&#42;3^ que estão sobre ele serão derramadas.’”

[NOTE]
====
. Ou: “portento”.
. Ou: “portento”.
. Ou: “cinzas gordurosas”, isto é, cinzas impregnadas da gordura dos sacrifícios.
====

[[v11-13-4]]

^<<v11-13-4,4>>^ Assim que o rei Jeroboão ouviu o que o homem do verdadeiro Deus tinha proclamado contra o altar em Betel, retirou a mão do altar e, apontando para o homem, disse: “Agarrem-no!” Imediatamente a mão que ele tinha estendido contra o homem ficou paralisada,^&#42;1^ e ele já não a conseguia mexer.

[NOTE]
====
. Ou: “ressequida”.
====

[[v11-13-5]]

^<<v11-13-5,5>>^ A seguir, o altar rachou-se, e as cinzas do altar derramaram-se, conforme o sinal^&#42;1^ que o homem do verdadeiro Deus tinha dado por ordem de Jeová.

[NOTE]
====
. Ou: “portento”.
====

[[v11-13-6]]

^<<v11-13-6,6>>^ Em vista disso, o rei disse ao homem do verdadeiro Deus: “Por favor, implora o favor^&#42;1^ de Jeová, teu Deus, e ora por mim para que a minha mão seja restabelecida.” Então, o homem do verdadeiro Deus implorou o favor de Jeová, e a mão do rei voltou a ser como dantes.

[NOTE]
====
. Ou: “abranda a face”.
====

[[v11-13-7]]

^<<v11-13-7,7>>^ Depois, o rei disse ao homem do verdadeiro Deus: “Vem comigo à minha casa para comeres alguma coisa, e eu vou dar-te um presente.”

[[v11-13-8]]

^<<v11-13-8,8>>^ Contudo, o homem do verdadeiro Deus disse ao rei: “Mesmo que me desse metade da sua casa, eu não iria consigo, nem comeria pão, nem beberia água neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ Pois recebi a seguinte ordem de Jeová: ‘Não comas pão nem bebas água, e não voltes pelo caminho por onde vieste.’”

[[v11-13-10]]

^<<v11-13-10,10>>^ Assim, ele partiu por outro caminho e não voltou pelo caminho por onde tinha ido a Betel.

[[v11-13-11]]

^<<v11-13-11,11>>^ Havia um profeta idoso que morava em Betel. Os seus filhos foram para casa e contaram-lhe tudo o que o homem do verdadeiro Deus tinha feito naquele dia em Betel e as palavras que ele tinha falado ao rei. Depois de contarem tudo ao seu pai,

[[v11-13-12]]

^<<v11-13-12,12>>^ o pai perguntou-lhes: “Por que caminho foi ele?” Portanto, os seus filhos indicaram-lhe o caminho pelo qual o homem do verdadeiro Deus, de Judá, tinha seguido.

[[v11-13-13]]

^<<v11-13-13,13>>^ Ele disse aos seus filhos: “Selem-me o jumento.” Eles selaram o jumento, e ele montou nele.

[[v11-13-14]]

^<<v11-13-14,14>>^ Ele foi atrás do homem do verdadeiro Deus e encontrou-o sentado debaixo de uma grande árvore. Então, perguntou-lhe: “És tu o homem do verdadeiro Deus que veio de Judá?” Ele respondeu: “Sou.”

[[v11-13-15]]

^<<v11-13-15,15>>^ O profeta idoso disse-lhe: “Vem comigo à minha casa e come pão.”

[[v11-13-16]]

^<<v11-13-16,16>>^ Contudo, ele disse: “Não posso voltar consigo nem aceitar o seu convite, e não posso comer pão nem beber água consigo neste lugar.

[[v11-13-17]]

^<<v11-13-17,17>>^ Pois recebi a seguinte ordem de Jeová: ‘Não comas pão nem bebas água ali. Não voltes pelo caminho por onde vieste.’”

[[v11-13-18]]

^<<v11-13-18,18>>^ A isso, o profeta idoso disse-lhe: “Eu também sou profeta como tu, e, por ordem de Jeová, um anjo disse-me: ‘Fá-lo voltar contigo à tua casa, para que coma pão e beba água.’” (Ele enganou-o.)

[[v11-13-19]]

^<<v11-13-19,19>>^ Portanto, voltou com ele para comer pão e beber água na sua casa.

[[v11-13-20]]

^<<v11-13-20,20>>^ Enquanto estavam sentados à mesa, o profeta que o tinha feito voltar recebeu a palavra de Jeová

[[v11-13-21]]

^<<v11-13-21,21>>^ e clamou ao homem do verdadeiro Deus, de Judá, dizendo: “Assim diz Jeová: ‘Visto que te rebelaste contra a ordem de Jeová e não guardaste o mandamento que Jeová, teu Deus, te deu,

[[v11-13-22]]

^<<v11-13-22,22>>^ mas voltaste para comer pão e beber água no lugar sobre o qual te disseram: “Não comas pão nem bebas água ali”, o teu cadáver não será colocado no túmulo dos teus antepassados.’”

[[v11-13-23]]

^<<v11-13-23,23>>^ Depois de o homem do verdadeiro Deus ter comido e bebido, o profeta idoso selou o jumento para o profeta que ele tinha feito voltar.

[[v11-13-24]]

^<<v11-13-24,24>>^ Então, o homem foi-se embora, mas na estrada um leão atacou-o e matou-o. O seu cadáver ficou estendido na estrada, e o jumento ficou parado ao seu lado; o leão também ficou parado ao lado do cadáver.

[[v11-13-25]]

^<<v11-13-25,25>>^ Alguns homens passaram e viram o cadáver estendido na estrada e o leão parado ao lado do cadáver. Eles entraram na cidade onde o profeta idoso morava e contaram o que tinham visto.

[[v11-13-26]]

^<<v11-13-26,26>>^ Quando o profeta que tinha feito o homem voltar da estrada soube o que tinha acontecido, disse imediatamente: “É o homem do verdadeiro Deus que se rebelou contra a ordem de Jeová; por isso Jeová entregou-o ao leão, para que o dilacerasse e matasse, segundo a palavra que Jeová lhe tinha falado.”

[[v11-13-27]]

^<<v11-13-27,27>>^ A seguir, ele disse aos seus filhos: “Selem o meu jumento.” E eles selaram-no.

[[v11-13-28]]

^<<v11-13-28,28>>^ Então, ele foi e encontrou o cadáver estendido na estrada, com o jumento e o leão parados ao seu lado. O leão não tinha devorado o cadáver nem dilacerado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ O profeta pegou no cadáver do homem do verdadeiro Deus, colocou-o sobre o jumento e trouxe-o de volta para a sua própria cidade para o lamentar e enterrar.

[[v11-13-30]]

^<<v11-13-30,30>>^ Assim, ele colocou o cadáver no seu próprio túmulo, e choraram por ele, dizendo: “Ai, meu irmão!”

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois de o ter enterrado, ele disse aos seus filhos: “Quando eu morrer, enterrem-me no lugar onde o homem do verdadeiro Deus está enterrado. Coloquem os meus ossos ao lado dos seus ossos.

[[v11-13-32]]

^<<v11-13-32,32>>^ O que ele proclamou, por ordem de Jeová, contra o altar em Betel e contra todos os santuários dos altos sagrados nas cidades de Samaria certamente se cumprirá.”

[[v11-13-33]]

^<<v11-13-33,33>>^ Mesmo depois destes acontecimentos, Jeroboão não recuou do seu mau caminho, mas continuou a designar homens do povo em geral para serem sacerdotes dos altos sagrados. Ele ordenava como sacerdote^&#42;1^ todo aquele que assim o desejasse, dizendo: “Que ele se torne um dos sacerdotes para os altos sagrados.”

[NOTE]
====
. Lit.: “enchia a mão de”.
====

[[v11-13-34]]

^<<v11-13-34,34>>^ Esse pecado da casa de Jeroboão resultou na sua destruição e na sua eliminação da face da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]