include::./index.adoc[]

[[v11-6-0]]
=== 1 Reis, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-6-1]]

^<<v11-6-1,1>>^ No quadringentésimo octogésimo ano depois da saída dos israelitas^&#42;1^ da terra do Egito, no quarto ano do reinado de Salomão sobre Israel, no mês de zive^&#42;2^ (isto é, o segundo mês), ele começou a construir a casa de Jeová.^&#42;3^

[NOTE]
====
. Lit.: “filhos de Israel”.
. Veja o Ap. B15.
. Veja o Ap. B8.
====

[[v11-6-2]]

^<<v11-6-2,2>>^ A casa que o rei Salomão construiu para Jeová tinha 60 côvados^&#42;1^ de comprimento, 20 côvados de largura e 30 côvados de altura.

[NOTE]
====
. Um côvado equivalia a 44,5 cm. Veja o Ap. B14.
====

[[v11-6-3]]

^<<v11-6-3,3>>^ O pórtico na parte da frente do templo^&#42;1^ tinha a mesma largura da casa: 20 côvados.^&#42;2^ O pórtico acrescentava 10 côvados ao comprimento da casa.

[NOTE]
====
. Lit.: “templo da casa”.
. Ou: “tinha 20 côvados de comprimento, que correspondia à largura da casa”.
====

[[v11-6-4]]

^<<v11-6-4,4>>^ Ele fez as janelas da casa com vãos que se estreitavam.^&#42;1^

[NOTE]
====
. Ou: “janelas chanfradas para a casa”.
====

[[v11-6-5]]

^<<v11-6-5,5>>^ Além disso, encostado às paredes da casa, ele construiu um anexo que acompanhava as paredes da casa — as do templo^&#42;1^ e do compartimento interno. E fez salas laterais ao redor da casa.

[NOTE]
====
. Aqui se refere ao Santo.
====

[[v11-6-6]]

^<<v11-6-6,6>>^ O andar inferior de salas laterais tinha cinco côvados de largura, o andar do meio tinha seis côvados de largura e o andar superior tinha sete côvados de largura, pois ele deixou recuos^&#42;1^ nas paredes ao redor de toda a casa, para que as vigas não precisassem de ser inseridas nas paredes da casa.

[NOTE]
====
. Ou: “reentrâncias”.
====

[[v11-6-7]]

^<<v11-6-7,7>>^ A casa foi construída com pedras já talhadas na pedreira, de modo que não se ouviam martelos, machados nem nenhum outro instrumento de ferro na casa durante a construção.

[[v11-6-8]]

^<<v11-6-8,8>>^ A entrada do andar inferior de salas laterais ficava no lado sul^&#42;1^ da casa, e havia uma escada em caracol para subir até ao andar do meio, e do andar do meio até ao andar superior.

[NOTE]
====
. Lit.: “direito”.
====

[[v11-6-9]]

^<<v11-6-9,9>>^ Ele continuou a construir a casa e terminou-a; ele cobriu a casa com vigas de cedro e filas de tábuas de cedro.

[[v11-6-10]]

^<<v11-6-10,10>>^ Construiu as salas laterais ao redor de toda a casa, cada uma com cinco côvados de altura, e elas estavam ligadas à casa por madeiras de cedro.

[[v11-6-11]]

^<<v11-6-11,11>>^ Entretanto, Salomão recebeu a seguinte palavra de Jeová:

[[v11-6-12]]

^<<v11-6-12,12>>^ “Quanto a esta casa que estás a construir, se andares nos meus decretos, cumprires as minhas decisões judiciais e obedeceres a todos os meus mandamentos, por andares segundo eles, eu cumprirei a promessa que fiz a David, teu pai, a respeito de ti,

[[v11-6-13]]

^<<v11-6-13,13>>^ residirei entre os israelitas e não abandonarei o meu povo Israel.”

[[v11-6-14]]

^<<v11-6-14,14>>^ Salomão continuou a construir a casa para a terminar.

[[v11-6-15]]

^<<v11-6-15,15>>^ Ele cobriu^&#42;1^ as paredes interiores da casa com tábuas de cedro. Revestiu as paredes interiores de madeira, desde o chão da casa até às vigas do teto; e revestiu o chão da casa com tábuas de junípero.

[NOTE]
====
. Lit.: “construiu”.
====

[[v11-6-16]]

^<<v11-6-16,16>>^ E ele construiu uma secção que media 20 côvados na parte de trás da casa, com tábuas de cedro, do chão até às vigas; assim, ele construiu dentro dela^&#42;1^ o compartimento interno, o Santíssimo.

[NOTE]
====
. Isto é, dentro da casa.
====

[[v11-6-17]]

^<<v11-6-17,17>>^ E o templo^&#42;1^ — a parte da casa em frente a ele — tinha 40 côvados.

[NOTE]
====
. Isto é, o Santo, que ficava na parte da frente do Santíssimo.
====

[[v11-6-18]]

^<<v11-6-18,18>>^ A madeira de cedro no interior da casa era entalhada com figuras de cabaças e de flores abertas. Era tudo de cedro; não se via nenhuma pedra.

[[v11-6-19]]

^<<v11-6-19,19>>^ E ele preparou o compartimento interno dentro da casa para colocar ali a Arca do Pacto de Jeová.

[[v11-6-20]]

^<<v11-6-20,20>>^ O compartimento interno tinha 20 côvados de comprimento, 20 côvados de largura e 20 côvados de altura; ele revestiu-o de ouro puro, e o altar ele revestiu de cedro.

[[v11-6-21]]

^<<v11-6-21,21>>^ Salomão revestiu o interior da casa com ouro puro e colocou correntes de ouro diante do compartimento interno, que era revestido de ouro.

[[v11-6-22]]

^<<v11-6-22,22>>^ Revestiu completamente a casa de ouro, toda a casa; e também revestiu o altar todo de ouro, que estava perto do compartimento interno.

[[v11-6-23]]

^<<v11-6-23,23>>^ No compartimento interno fez dois querubins de madeira de pinho,^&#42;1^ cada um com dez côvados de altura.

[NOTE]
====
. Lit.: “madeira oleaginosa”, possivelmente o pinheiro-de-alepo.
====

[[v11-6-24]]

^<<v11-6-24,24>>^ Uma asa do querubim tinha cinco côvados, e a outra asa tinha cinco côvados. Da ponta de uma asa até à ponta da outra asa eram dez côvados.

[[v11-6-25]]

^<<v11-6-25,25>>^ O segundo querubim também tinha dez côvados. Os dois querubins tinham o mesmo tamanho e a mesma forma.

[[v11-6-26]]

^<<v11-6-26,26>>^ Um querubim tinha dez côvados de altura, e o outro querubim tinha a mesma altura.

[[v11-6-27]]

^<<v11-6-27,27>>^ A seguir, ele pôs os querubins dentro do compartimento interno.^&#42;1^ As asas dos querubins estavam estendidas, de modo que a asa de um querubim tocava numa parede e a asa do outro querubim tocava na outra parede, e as outras asas estendiam-se para o centro do compartimento, e assim tocavam uma na outra.

[NOTE]
====
. Isto é, do Santíssimo.
====

[[v11-6-28]]

^<<v11-6-28,28>>^ Ele também revestiu os querubins com ouro.

[[v11-6-29]]

^<<v11-6-29,29>>^ E, em todas as paredes da casa, tanto ao redor do compartimento interno como do externo,^&#42;1^ ele entalhou figuras de querubins, de palmeiras e de flores abertas.

[NOTE]
====
. Lit.: “dentro e fora”.
====

[[v11-6-30]]

^<<v11-6-30,30>>^ Ele revestiu de ouro o soalho da casa, tanto no compartimento interno como no externo.

[[v11-6-31]]

^<<v11-6-31,31>>^ E para a entrada do compartimento interno ele fez portas de madeira de pinho, colunas laterais e ombreiras, como uma quinta parte.^&#42;1^

[NOTE]
====
. Talvez se refira à estrutura onde se encaixavam as portas ou ao tamanho das portas.
====

[[v11-6-32]]

^<<v11-6-32,32>>^ As duas portas eram de madeira de pinho, e nelas ele entalhou querubins, palmeiras e flores abertas, e revestiu-as de ouro; cobriu os querubins e as palmeiras com ouro batido a martelo.

[[v11-6-33]]

^<<v11-6-33,33>>^ Para a entrada do templo,^&#42;1^ ele fez as ombreiras de madeira de pinho da mesma maneira, que pertenciam a uma quarta parte.^&#42;2^

[NOTE]
====
. Aqui se refere ao Santo.
. Talvez se refira à estrutura onde se encaixavam as portas ou ao tamanho das portas.
====

[[v11-6-34]]

^<<v11-6-34,34>>^ E ele fez duas portas de madeira de junípero. Uma porta tinha duas folhas que giravam por meio de pivôs, e a outra porta tinha duas folhas que também giravam por meio de pivôs.

[[v11-6-35]]

^<<v11-6-35,35>>^ Nelas entalhou figuras de querubins, palmeiras e flores abertas, e folheou com ouro as figuras.

[[v11-6-36]]

^<<v11-6-36,36>>^ Ele construiu o muro do pátio interno com três filas de pedras talhadas e uma fila de madeira de cedro.

[[v11-6-37]]

^<<v11-6-37,37>>^ No quarto ano, no mês de zive,^&#42;1^ lançou-se o alicerce da casa de Jeová;

[NOTE]
====
. Veja o Ap. B15.
====

[[v11-6-38]]

^<<v11-6-38,38>>^ e no décimo primeiro ano, no mês de bul^&#42;1^ (isto é, no oitavo mês), a casa foi concluída com todos os pormenores, conforme o projeto. Assim, ele levou sete anos para a construir.

[NOTE]
====
. Veja o Ap. B15.
====

'''

xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[&#60; Capítulo Anterior] | <<v11-6-0,Topo>> | xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[Próximo Capítulo &#62;]