include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v11-20-1]]

^<<v11-20-1,1>>^ Ben-Hadade, rei da Síria, reuniu todo o seu exército e também outros 32 reis, com os seus cavalos e carros de guerra. Ele subiu a Samaria, cercou-a e atacou-a.

[[v11-20-2]]

^<<v11-20-2,2>>^ Então, ele enviou mensageiros à cidade, a Acabe, rei de Israel, para lhe dizer: “Assim diz Ben-Hadade:

[[v11-20-3]]

^<<v11-20-3,3>>^ ‘A tua prata e o teu ouro são meus, e, das tuas esposas e dos teus filhos, os melhores são meus.’”

[[v11-20-4]]

^<<v11-20-4,4>>^ Em vista disso, o rei de Israel disse: “Que seja conforme a sua palavra, meu senhor, o rei. Eu sou seu, com tudo o que me pertence.”

[[v11-20-5]]

^<<v11-20-5,5>>^ Mais tarde, os mensageiros voltaram a Acabe e disseram: “Assim diz Ben-Hadade: ‘Eu mandei dizer-te: “Tu irás dar-me a tua prata, o teu ouro, as tuas esposas e os teus filhos.”

[[v11-20-6]]

^<<v11-20-6,6>>^ Todavia, amanhã, por volta desta hora, irei enviar-te os meus servos, e eles farão uma busca cuidadosa na tua casa e nas casas dos teus servos, e tirarão e levarão tudo o que te for precioso.’”

[[v11-20-7]]

^<<v11-20-7,7>>^ Em vista disso, o rei de Israel convocou todos os anciãos do país e disse: “Prestem atenção, por favor. Vejam como este homem está decidido a causar-nos calamidade, pois ele exigiu que eu lhe entregasse as minhas esposas, os meus filhos, a minha prata e o meu ouro, e eu não lhe neguei nada disso.”

[[v11-20-8]]

^<<v11-20-8,8>>^ E todos os anciãos e todo o povo lhe disseram: “Não obedeça, não aceite isso.”

[[v11-20-9]]

^<<v11-20-9,9>>^ Portanto, ele disse aos mensageiros de Ben-Hadade: “Digam ao meu senhor, o rei: ‘Farei tudo o que exigiu do seu servo da primeira vez, mas não posso fazer o que me pede agora.’” Com isso os mensageiros foram-se embora e levaram essa informação a Ben-Hadade.

[[v11-20-10]]

^<<v11-20-10,10>>^ Então, Ben-Hadade mandou dizer-lhe: “Que os deuses me castiguem, e o façam severamente, se o pó que sobrar de Samaria for suficiente para dar um punhado a cada um dos homens que estão comigo!”

[[v11-20-11]]

^<<v11-20-11,11>>^ O rei de Israel respondeu: “Digam-lhe: ‘Que aquele que veste a armadura não se gabe como se já a estivesse a tirar.’”

[[v11-20-12]]

^<<v11-20-12,12>>^ Assim que Ben-Hadade ouviu isto, enquanto ele e os reis bebiam nas suas tendas,^&#42;1^ disse aos seus servos: “Preparem-se para atacar!” Então, eles prepararam-se para atacar a cidade.

[NOTE]
====
. Ou: “barracas”.
====

[[v11-20-13]]

^<<v11-20-13,13>>^ No entanto, um profeta aproximou-se de Acabe, rei de Israel, e disse: “Assim diz Jeová: ‘Estás a ver toda esta multidão? Hoje, irei entregá-la nas tuas mãos, e então, saberás que eu sou Jeová.’”

[[v11-20-14]]

^<<v11-20-14,14>>^ Acabe perguntou: “Por meio de quem?” O profeta respondeu: “Assim diz Jeová: ‘Por meio dos ajudantes dos príncipes das províncias.’”^&#42;1^ Então, Acabe perguntou: “Quem é que começará a batalha?” O profeta respondeu: “O senhor!”

[NOTE]
====
. Ou: “dos distritos jurisdicionais”.
====

[[v11-20-15]]

^<<v11-20-15,15>>^ Acabe contou então os ajudantes dos príncipes das províncias: eram 232; depois contou todos os homens de Israel: 7000.

[[v11-20-16]]

^<<v11-20-16,16>>^ Eles saíram ao meio-dia, enquanto Ben-Hadade estava nas tendas^&#42;1^ a embriagar-se com os 32 reis que o ajudavam.

[NOTE]
====
. Ou: “barracas”.
====

[[v11-20-17]]

^<<v11-20-17,17>>^ Os ajudantes dos príncipes das províncias saíram primeiro. Ben-Hadade enviou imediatamente uma patrulha, que o informou: “Saíram homens de Samaria.”

[[v11-20-18]]

^<<v11-20-18,18>>^ Por conseguinte, ele disse: “Se eles vieram para a paz, apanhem-nos vivos; se vieram para a guerra, apanhem-nos vivos na mesma.”

[[v11-20-19]]

^<<v11-20-19,19>>^ Contudo, quando os ajudantes dos príncipes das províncias e as tropas que os seguiam saíram da cidade,

[[v11-20-20]]

^<<v11-20-20,20>>^ cada um deles matou o seu adversário. Então, os sírios fugiram, e Israel foi atrás deles, mas Ben-Hadade, rei da Síria, escapou a cavalo, com alguns dos cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ O rei de Israel, porém, saiu e atacou os cavalos e os carros de guerra, e causou uma grande derrota^&#42;1^ aos sírios.

[NOTE]
====
. Ou: “matança”.
====

[[v11-20-22]]

^<<v11-20-22,22>>^ Mais tarde, o profeta aproximou-se do rei de Israel e disse-lhe: “Vá, fortaleça as suas defesas e pense bem no que vai fazer, pois no início do próximo ano^&#42;1^ o rei da Síria subirá contra si.”

[NOTE]
====
. Isto é, na próxima primavera.
====

[[v11-20-23]]

^<<v11-20-23,23>>^ Os servos do rei da Síria disseram-lhe: “O Deus deles é um Deus de montanhas. É por isso que eles nos venceram. Mas, se lutarmos contra eles na planície, nós iremos vencê-los.

[[v11-20-24]]

^<<v11-20-24,24>>^ Além disso, faça o seguinte: remova todos os reis das suas funções e substitua-os por governadores.

[[v11-20-25]]

^<<v11-20-25,25>>^ Depois, reúna^&#42;1^ um exército igual ao que perdeu, com o mesmo número de cavalos e carros de guerra. Lutemos contra eles na planície e nós certamente os venceremos.” Ele escutou o conselho deles e fez exatamente assim.

[NOTE]
====
. Lit.: “enumera”.
====

[[v11-20-26]]

^<<v11-20-26,26>>^ No início do ano,^&#42;1^ Ben-Hadade reuniu os sírios e foi a Afeque para combater Israel.

[NOTE]
====
. Isto é, na primavera.
====

[[v11-20-27]]

^<<v11-20-27,27>>^ O povo de Israel também foi reunido e recebeu provisões, e foi ao encontro deles. Quando o povo de Israel se acampou diante deles, pareciam dois pequenos rebanhos de cabras, ao passo que os sírios enchiam toda a região.

[[v11-20-28]]

^<<v11-20-28,28>>^ Então, o homem do verdadeiro Deus aproximou-se do rei de Israel e disse: “Assim diz Jeová: ‘Visto que os sírios disseram: “Jeová é um Deus de montanhas, não um Deus de planícies”, entregarei nas tuas mãos toda esta multidão, e vocês certamente saberão que eu sou Jeová.’”

[[v11-20-29]]

^<<v11-20-29,29>>^ Os dois exércitos continuaram acampados um em frente ao outro durante sete dias, e, no sétimo dia, a batalha começou. Num só dia, o povo de Israel matou 100 000 soldados^&#42;1^ sírios.

[NOTE]
====
. Ou: “soldados a pé”.
====

[[v11-20-30]]

^<<v11-20-30,30>>^ E o restante fugiu para Afeque e entrou na cidade. No entanto, a muralha caiu sobre 27 000 dos homens que tinham restado. Ben-Hadade também fugiu para dentro da cidade e escondeu-se num quarto recôndito de uma casa.

[[v11-20-31]]

^<<v11-20-31,31>>^ Assim, os seus servos disseram-lhe: “Escute, ó rei, ouvimos dizer que os reis da casa de Israel são reis misericordiosos.^&#42;1^ Por favor, vamos apresentar-nos ao rei de Israel com serapilheira^&#42;2^ na cintura e cordas à volta da cabeça.^&#42;3^ Talvez ele lhe poupe a vida.”^&#42;4^

[NOTE]
====
. Ou: “de amor leal”.
. Veja o Glossário.
. Ou: “do pescoço”.
. Ou: “alma”.
====

[[v11-20-32]]

^<<v11-20-32,32>>^ Portanto, colocaram serapilheira^&#42;1^ na cintura e cordas à volta da cabeça,^&#42;2^ e foram ter com o rei de Israel e disseram: “O seu servo Ben-Hadade disse: ‘Por favor, deixa-me^&#42;3^ viver.’” O rei disse: “Ele ainda está vivo? Ele é meu irmão.”

[NOTE]
====
. Veja o Glossário.
. Ou: “do pescoço”.
. Ou: “deixa a minha alma”.
====

[[v11-20-33]]

^<<v11-20-33,33>>^ Os homens encararam isso como um bom sinal e, aproveitando o que ele disse, afirmaram: “Sim, Ben-Hadade é seu irmão.” Então ele disse: “Vão, tragam-no.” Consequentemente, Ben-Hadade entregou-se ao rei, e Acabe fê-lo subir para o seu carro de guerra.

[[v11-20-34]]

^<<v11-20-34,34>>^ Ben-Hadade disse-lhe: “Devolverei as cidades que o meu pai tomou do teu pai; e poderás estabelecer mercados^&#42;1^ em Damasco, assim como o meu pai fez em Samaria.”
Acabe disse: “Se fizermos este acordo,^&#42;2^ eu deixo-te ir embora.”
Portanto, fez um acordo com ele e deixou-o ir.

[NOTE]
====
. Ou: “designar ruas”.
. Ou: “pacto”.
====

[[v11-20-35]]

^<<v11-20-35,35>>^ Por ordem de Jeová, um dos filhos dos profetas^&#42;1^ disse a um companheiro: “Por favor, golpeia-me.” O homem, porém, negou-se a golpeá-lo.

[NOTE]
====
. “Filhos dos profetas” parece referir-se a uma escola de instrução para profetas ou a uma associação de profetas.
====

[[v11-20-36]]

^<<v11-20-36,36>>^ Por isso, ele disse-lhe: “Visto que não escutaste a voz de Jeová, assim que te fores embora um leão irá matar-te.”^&#42;1^ Quando ele se foi embora, um leão atacou-o e matou-o.

[NOTE]
====
. Ou: “golpear-te”.
====

[[v11-20-37]]

^<<v11-20-37,37>>^ O profeta encontrou outro homem e disse: “Por favor, golpeia-me.” Então, o homem golpeou-o e feriu-o.

[[v11-20-38]]

^<<v11-20-38,38>>^ Depois, o profeta foi até à estrada e ficou à espera do rei. Disfarçou-se, tapando os olhos com uma venda.

[[v11-20-39]]

^<<v11-20-39,39>>^ Quando o rei ia a passar, ele chamou o rei aos gritos e disse: “O seu servo estava no meio da batalha quando um homem veio com um prisioneiro e disse: ‘Vigia este homem. Se ele escapar, será a tua vida pela vida dele,^&#42;1^ ou então terás de pagar um talento^&#42;2^ de prata.’

[NOTE]
====
. Ou: “a tua alma ficará no lugar da alma dele”.
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v11-20-40]]

^<<v11-20-40,40>>^ E, enquanto o seu servo estava ocupado com outras coisas, o prisioneiro desapareceu.” O rei de Israel disse-lhe: “É essa a tua sentença; Tu mesmo a pronunciaste.”

[[v11-20-41]]

^<<v11-20-41,41>>^ Então, ele removeu rapidamente a venda dos olhos, e o rei de Israel reconheceu-o como um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ Ele disse ao rei: “Assim diz Jeová: ‘Visto que deixaste escapar das tuas mãos o homem que eu disse que devia ser morto, será a tua vida pela vida dele,^&#42;1^ e o teu povo pelo povo dele.’”

[NOTE]
====
. Ou: “a tua alma ficará no lugar da alma dele”.
====

[[v11-20-43]]

^<<v11-20-43,43>>^ Em vista disso, o rei de Israel foi-se embora para a sua casa em Samaria, contrariado e abatido.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]