include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-15-1]]

^<<v42-15-1,1>>^ Todos os cobradores de impostos e os pecadores juntavam-se à volta dele para o ouvir.

[[v42-15-2]]

^<<v42-15-2,2>>^ E tanto os fariseus como os escribas resmungavam: “Este homem acolhe pecadores e come com eles.”

[[v42-15-3]]

^<<v42-15-3,3>>^ Então, ele contou-lhes a seguinte ilustração:

[[v42-15-4]]

^<<v42-15-4,4>>^ “Qual é o homem dentre vocês que, tendo 100 ovelhas e perdendo uma delas, não deixa as 99 para trás no deserto e vai em busca da perdida, até a encontrar?

[[v42-15-5]]

^<<v42-15-5,5>>^ E, quando a encontra, ele põe-na aos ombros e alegra-se.

[[v42-15-6]]

^<<v42-15-6,6>>^ E, ao chegar a casa, reúne os amigos e os vizinhos, e diz-lhes: ‘Alegrem-se comigo, porque encontrei a minha ovelha que estava perdida.’

[[v42-15-7]]

^<<v42-15-7,7>>^ Digo-vos que, da mesma forma, haverá mais alegria no céu por causa de um pecador que se arrepende do que por causa de 99 justos que não precisam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ “Ou que mulher, tendo dez dracmas^&#42;1^ e perdendo uma dracma, não acende uma lâmpada, varre a casa e procura cuidadosamente até a encontrar?

[NOTE]
====
. Veja o Ap. B14.
====

[[v42-15-9]]

^<<v42-15-9,9>>^ E, quando a encontra, ela reúne as suas amigas e vizinhas, e diz: ‘Alegrem-se comigo, porque encontrei a dracma^&#42;1^ que tinha perdido.’

[NOTE]
====
. Veja o Ap. B14.
====

[[v42-15-10]]

^<<v42-15-10,10>>^ Digo-vos que, da mesma forma, há alegria entre os anjos de Deus por causa de um pecador que se arrepende.”

[[v42-15-11]]

^<<v42-15-11,11>>^ Em seguida, ele disse: “Um homem tinha dois filhos.

[[v42-15-12]]

^<<v42-15-12,12>>^ E o mais novo disse ao pai: ‘Pai, dá-me a parte dos bens a que tenho direito.’ Então, ele dividiu os bens entre eles.

[[v42-15-13]]

^<<v42-15-13,13>>^ Poucos dias depois, o filho mais novo juntou tudo o que tinha e viajou para um país distante. Ali, esbanjou os seus bens, levando uma vida devassa.^&#42;1^

[NOTE]
====
. Ou: “de desperdício; irresponsável”.
====

[[v42-15-14]]

^<<v42-15-14,14>>^ Depois de ter gasto tudo, ocorreu uma fome severa em todo aquele país, e ele começou a passar necessidades.

[[v42-15-15]]

^<<v42-15-15,15>>^ Ele até mesmo se colocou ao serviço de um dos cidadãos daquele país, que o enviou aos seus campos para cuidar de porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ E ele desejava matar a fome com as alfarrobas que os porcos comiam, mas ninguém lhe dava nada.

[[v42-15-17]]

^<<v42-15-17,17>>^ “Quando caiu em si, ele disse: ‘Quantos empregados do meu pai têm fartura de pão, enquanto eu estou aqui a morrer de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Vou-me embora e voltarei para a casa do meu pai, e vou dizer-lhe: “Pai, pequei contra o céu e contra ti.

[[v42-15-19]]

^<<v42-15-19,19>>^ Já não sou digno de ser chamado teu filho. Trata-me como um dos teus empregados.”’

[[v42-15-20]]

^<<v42-15-20,20>>^ Assim, levantou-se e foi ao encontro do seu pai. Enquanto ele ainda estava longe, o pai avistou-o e teve pena; então, correu, e abraçou-o^&#42;1^ e beijou-o ternamente.

[NOTE]
====
. Lit.: “lançou-se ao seu pescoço”.
====

[[v42-15-21]]

^<<v42-15-21,21>>^ O filho disse-lhe então: ‘Pai, pequei contra o céu e contra ti. Já não sou digno de ser chamado teu filho.’

[[v42-15-22]]

^<<v42-15-22,22>>^ Mas o pai disse aos seus escravos: ‘Depressa! Tragam uma veste comprida, a melhor, e vistam-no com ela, e ponham-lhe um anel na mão e sandálias nos pés.

[[v42-15-23]]

^<<v42-15-23,23>>^ Tragam também o bezerro gordo, abatam-no, e vamos comer e festejar,

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto e voltou a viver, estava perdido e foi encontrado.’ E começaram a festejar.

[[v42-15-25]]

^<<v42-15-25,25>>^ “O filho mais velho estava no campo e, ao voltar, quando se aproximava da casa, ouviu o som de música e dança.

[[v42-15-26]]

^<<v42-15-26,26>>^ Por isso, chamou um dos servos e perguntou o que estava a acontecer.

[[v42-15-27]]

^<<v42-15-27,27>>^ Este disse-lhe: ‘O seu irmão chegou, e o seu pai abateu o bezerro gordo porque o recebeu de volta com boa saúde.’^&#42;1^

[NOTE]
====
. Ou: “em segurança”.
====

[[v42-15-28]]

^<<v42-15-28,28>>^ Mas ele ficou zangado e recusou-se a entrar. Então, o pai saiu e começou a suplicar-lhe que entrasse.

[[v42-15-29]]

^<<v42-15-29,29>>^ Em resposta, ele disse ao pai: ‘Trabalhei tantos anos como escravo para ti e nunca desobedeci às tuas ordens. Mesmo assim, nem uma vez me deste um cabrito para eu festejar com os meus amigos.

[[v42-15-30]]

^<<v42-15-30,30>>^ Mas, assim que chegou esse teu filho, que esbanjou^&#42;1^ os teus bens com as prostitutas, abateste o bezerro gordo para ele.’

[NOTE]
====
. Lit.: “devorou”.
====

[[v42-15-31]]

^<<v42-15-31,31>>^ E ele respondeu-lhe: ‘Meu filho, tu sempre estiveste comigo e todas as minhas coisas são tuas.

[[v42-15-32]]

^<<v42-15-32,32>>^ Mas nós simplesmente tivemos de festejar e de nos alegrar, porque o teu irmão estava morto e voltou a viver, estava perdido e foi encontrado.’”

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]