include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-18-1]]

^<<v42-18-1,1>>^ Depois, contou-lhes uma ilustração a respeito da necessidade de orarem sempre e de nunca desistirem,

[[v42-18-2]]

^<<v42-18-2,2>>^ dizendo: “Em certa cidade, havia um juiz que não temia a Deus nem respeitava ninguém.

[[v42-18-3]]

^<<v42-18-3,3>>^ Havia também naquela cidade uma viúva, e ela persistia em ir ter com ele e dizia-lhe: ‘Faça-me justiça contra o meu adversário.’

[[v42-18-4]]

^<<v42-18-4,4>>^ Durante algum tempo, ele não estava disposto a fazer isso, mas, depois, disse para consigo: ‘Eu não temo a Deus nem respeito nenhum homem,

[[v42-18-5]]

^<<v42-18-5,5>>^ mas, visto que esta viúva anda a incomodar-me, vou fazer-lhe justiça para que não continue a vir importunar-me com o seu pedido, até que eu já não o suporte mais.’”^&#42;1^

[NOTE]
====
. Ou: “pedido, esmurrando-me até ao fim”.
====

[[v42-18-6]]

^<<v42-18-6,6>>^ O Senhor disse então: “Ouçam o que o juiz, embora injusto, disse!

[[v42-18-7]]

^<<v42-18-7,7>>^ Certamente, então, será que Deus não providenciará que seja feita justiça aos seus escolhidos, que lhe imploram dia e noite, enquanto é paciente com eles?

[[v42-18-8]]

^<<v42-18-8,8>>^ Digo-vos: Ele providenciará que, rapidamente, lhes seja feita justiça. Contudo, quando o Filho do Homem chegar, encontrará realmente esta fé^&#42;1^ na terra?”

[NOTE]
====
. Ou: “este tipo de fé”. Lit.: “a fé”.
====

[[v42-18-9]]

^<<v42-18-9,9>>^ Ele também contou a seguinte ilustração a alguns que confiavam na sua própria justiça e não tinham nenhuma consideração pelos outros:

[[v42-18-10]]

^<<v42-18-10,10>>^ “Dois homens subiram ao templo para orar: um era fariseu e o outro era cobrador de impostos.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu ficou de pé e começou a orar no íntimo o seguinte: ‘Ó Deus, agradeço-te porque não sou como todos os outros: extorsores, injustos, adúlteros; nem mesmo como este cobrador de impostos.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes por semana, dou o décimo de tudo o que adquiro.’

[[v42-18-13]]

^<<v42-18-13,13>>^ Mas o cobrador de impostos, parado à distância, nem sequer queria levantar os olhos para o céu, mas batia no peito, dizendo: ‘Ó Deus, tem misericórdia de mim,^&#42;1^ um pecador.’

[NOTE]
====
. Ou: “sê benevolente comigo”.
====

[[v42-18-14]]

^<<v42-18-14,14>>^ Digo-vos: Este homem voltou para casa mais justo do que aquele fariseu. Porque todo aquele que se enaltecer será humilhado, mas quem se humilhar será enaltecido.”

[[v42-18-15]]

^<<v42-18-15,15>>^ As pessoas também lhe traziam as suas crianças de colo, para que lhes tocasse; mas, quando viram isso, os discípulos começaram a repreender as pessoas.

[[v42-18-16]]

^<<v42-18-16,16>>^ No entanto, Jesus mandou trazer a si as crianças de colo, dizendo: “Deixem as criancinhas vir a mim e não tentem impedi-las, pois o Reino de Deus pertence aos que são como elas.

[[v42-18-17]]

^<<v42-18-17,17>>^ Digo-vos a verdade: Quem não receber o Reino de Deus como uma criancinha, de modo algum entrará nele.”

[[v42-18-18]]

^<<v42-18-18,18>>^ E um dos líderes dos judeus perguntou-lhe: “Bom Instrutor, o que devo fazer para herdar a vida eterna?”

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus disse-lhe: “Porque é que me chamas bom? Ninguém é bom, a não ser um só, Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Tu conheces os mandamentos: ‘Não cometas adultério, não assassines, não furtes, não dês falso testemunho, honra o teu pai e a tua mãe.’”

[[v42-18-21]]

^<<v42-18-21,21>>^ E o homem disse: “Tenho-os cumprido a todos desde bem jovem.”

[[v42-18-22]]

^<<v42-18-22,22>>^ Ao ouvir isto, Jesus disse-lhe: “Ainda te falta fazer uma coisa: vende tudo o que tens e distribui o dinheiro pelos pobres, e terás um tesouro nos céus; e vem ser meu seguidor.”

[[v42-18-23]]

^<<v42-18-23,23>>^ Quando ele ouviu isto, ficou profundamente triste, porque era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ Jesus olhou para ele e disse: “Como será difícil para os que têm dinheiro entrar no Reino de Deus!

[[v42-18-25]]

^<<v42-18-25,25>>^ De facto, é mais fácil um camelo passar pelo buraco de uma agulha de costura, do que um rico entrar no Reino de Deus.”

[[v42-18-26]]

^<<v42-18-26,26>>^ Os que ouviram isto disseram: “Quem é que pode ser salvo?”

[[v42-18-27]]

^<<v42-18-27,27>>^ Ele disse: “As coisas impossíveis para os homens são possíveis para Deus.”

[[v42-18-28]]

^<<v42-18-28,28>>^ Mas Pedro disse: “Olha, deixámos tudo o que tínhamos e seguimos-te.”

[[v42-18-29]]

^<<v42-18-29,29>>^ Ele disse-lhes: “Eu garanto-vos: Não há ninguém que tenha deixado casa, esposa, irmãos, pais ou filhos por causa do Reino de Deus

[[v42-18-30]]

^<<v42-18-30,30>>^ que não receba muitas vezes mais neste tempo e, no futuro sistema de coisas,^&#42;1^ a vida eterna.”

[NOTE]
====
. Ou: “na época futura”. Veja o Glossário.
====

[[v42-18-31]]

^<<v42-18-31,31>>^ Então, ele chamou os Doze à parte e disse-lhes: “Escutem, estamos a subir para Jerusalém, e todas as coisas escritas por meio dos profetas a respeito do Filho do Homem vão cumprir-se.^&#42;1^

[NOTE]
====
. Ou: “completar-se”.
====

[[v42-18-32]]

^<<v42-18-32,32>>^ Por exemplo, ele será entregue a homens das nações, e vão ridicularizá-lo, maltratá-lo e cuspir-lhe.

[[v42-18-33]]

^<<v42-18-33,33>>^ E, depois de o açoitarem, vão matá-lo, mas, no terceiro dia, ele será levantado.”

[[v42-18-34]]

^<<v42-18-34,34>>^ No entanto, eles não compreenderam o significado de nada disto, pois o sentido destas palavras era-lhes escondido, e eles não entenderam o que foi dito.

[[v42-18-35]]

^<<v42-18-35,35>>^ Quando Jesus se aproximava de Jericó, um cego estava sentado à beira da estrada, a mendigar.

[[v42-18-36]]

^<<v42-18-36,36>>^ Ao ouvir uma multidão a passar, ele perguntou o que estava a acontecer.

[[v42-18-37]]

^<<v42-18-37,37>>^ Disseram-lhe: “Jesus, o Nazareno, vai a passar!”

[[v42-18-38]]

^<<v42-18-38,38>>^ Em vista disso, ele gritou: “Jesus, Filho de David, tenha misericórdia de mim!”

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que estavam à frente começaram a censurá-lo, mandando-o calar-se, mas ele gritava ainda mais: “Filho de David, tenha misericórdia de mim!”

[[v42-18-40]]

^<<v42-18-40,40>>^ Jesus parou, então, e mandou que lhe trouxessem o homem. Depois de ele se ter aproximado, Jesus perguntou-lhe:

[[v42-18-41]]

^<<v42-18-41,41>>^ “O que é que queres que eu faça por ti?” Ele disse: “Senhor, deixe-me recuperar a visão.”

[[v42-18-42]]

^<<v42-18-42,42>>^ Então, Jesus disse-lhe: “Recupera a visão. A tua fé curou-te.”

[[v42-18-43]]

^<<v42-18-43,43>>^ E ele recuperou instantaneamente a visão e começou a segui-lo, glorificando a Deus. De igual modo, todas as pessoas, ao verem isto, deram louvor a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]