include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso, o Senhor designou mais 70 e enviou-os dois a dois, à sua frente, a todas as cidades e lugares aonde ele estava para ir.

[[v42-10-2]]

^<<v42-10-2,2>>^ Ele disse-lhes então: “A colheita, realmente, é grande, mas os trabalhadores são poucos. Por isso, peçam ao Senhor da colheita que mande trabalhadores para a Sua colheita.

[[v42-10-3]]

^<<v42-10-3,3>>^ Vão! Envio-vos como cordeiros no meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não levem bolsa de dinheiro, nem alforge,^&#42;1^ nem sandálias, e não cumprimentem ninguém^&#42;2^ ao longo da estrada.

[NOTE]
====
. Ou: “bolsa de alimentos”.
. Ou: “não abracem ninguém em cumprimento”.
====

[[v42-10-5]]

^<<v42-10-5,5>>^ Em qualquer casa onde entrem, digam primeiro: ‘Haja paz nesta casa.’

[[v42-10-6]]

^<<v42-10-6,6>>^ E, se houver ali um amigo da paz, a vossa paz descansará sobre ele. Mas, se não houver, ela voltará para vocês.

[[v42-10-7]]

^<<v42-10-7,7>>^ Assim, fiquem naquela casa, a comer e a beber as coisas que vos oferecerem, porque o trabalhador é digno do seu salário. Não andem a mudar de uma casa para a outra.

[[v42-10-8]]

^<<v42-10-8,8>>^ “Além disso, onde quer que entrem numa cidade e as pessoas vos recebam, comam o que for colocado à vossa frente,

[[v42-10-9]]

^<<v42-10-9,9>>^ curem os doentes que nela houver e digam-lhes: ‘O Reino de Deus está próximo de vocês.’

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas, onde quer que entrem numa cidade e as pessoas não vos recebam, saiam para as ruas principais e digam:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Nós sacudiremos até mesmo o pó da vossa cidade que se agarrou aos nossos pés, em testemunho contra vocês. Contudo, saibam o seguinte: o Reino de Deus está próximo.’

[[v42-10-12]]

^<<v42-10-12,12>>^ Digo-vos que, nesse dia, será mais suportável para Sodoma do que para essa cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ “Ai de ti, Corazim! Ai de ti, Betsaida! Porque, se as obras poderosas que ocorreram em vocês tivessem ocorrido em Tiro e Sídon, estas ter-se-iam arrependido há muito tempo, sentadas em serapilheira^&#42;1^ e em cinzas.

[NOTE]
====
. Veja o Glossário.
====

[[v42-10-14]]

^<<v42-10-14,14>>^ Por isso, no julgamento, será mais suportável para Tiro e Sídon do que para vocês.

[[v42-10-15]]

^<<v42-10-15,15>>^ E tu, Cafarnaum, serás, por acaso, enaltecida ao céu? Descerás até à Sepultura!^&#42;1^

[NOTE]
====
. Ou: “ao Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v42-10-16]]

^<<v42-10-16,16>>^ “Quem vos escuta escuta-me a mim. E quem vos desconsidera também me desconsidera a mim. Além disso, quem me desconsidera, desconsidera também Aquele que me enviou.”

[[v42-10-17]]

^<<v42-10-17,17>>^ Os 70 voltaram então com alegria, dizendo: “Senhor, até mesmo os demónios nos obedecem pelo uso do teu nome.”

[[v42-10-18]]

^<<v42-10-18,18>>^ Em vista disso, ele disse-lhes: “Já vejo Satanás caído como relâmpago do céu.

[[v42-10-19]]

^<<v42-10-19,19>>^ Escutem: Eu dei-vos autoridade para pisarem serpentes e escorpiões, e sobre todo o poder do inimigo, e absolutamente nada vos fará mal.

[[v42-10-20]]

^<<v42-10-20,20>>^ Contudo, não se alegrem porque os espíritos vos estão a ser sujeitos, mas alegrem-se porque os vossos nomes foram escritos nos céus.”

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquele preciso momento, ele ficou cheio de alegria por meio do espírito santo e disse: “Eu louvo-te publicamente, Pai, Senhor do céu e da terra, porque escondeste cuidadosamente estas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos. Sim, ó Pai, porque tu te agradaste em fazer as coisas desta maneira.

[[v42-10-22]]

^<<v42-10-22,22>>^ Tudo me foi entregue pelo meu Pai. E ninguém sabe quem o Filho é, exceto o Pai; e ninguém sabe quem o Pai é, exceto o Filho e aquele a quem o Filho o quiser revelar.”

[[v42-10-23]]

^<<v42-10-23,23>>^ Com isso, ele virou-se para os discípulos e disse-lhes em particular: “Felizes são os olhos que veem as coisas que vocês estão a ver.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu vos digo: Muitos profetas e reis desejaram ver as coisas que vocês estão a observar, mas não as viram, e ouvir as coisas que vocês estão a ouvir, mas não as ouviram.”

[[v42-10-25]]

^<<v42-10-25,25>>^ Então, um homem perito na Lei levantou-se para o provar e perguntou-lhe: “Instrutor, o que devo fazer para herdar a vida eterna?”

[[v42-10-26]]

^<<v42-10-26,26>>^ Ele disse-lhe: “O que está escrito na Lei? Como é que lês?”

[[v42-10-27]]

^<<v42-10-27,27>>^ Em resposta, ele disse: “‘Ama a Jeová,^&#42;1^ teu Deus, de todo o teu coração, de toda a tua alma,^&#42;2^ de toda a tua força e de toda a tua mente’ e ‘o teu próximo como a ti mesmo’.”

[NOTE]
====
. Veja o Ap. A5.
. Veja o Glossário.
====

[[v42-10-28]]

^<<v42-10-28,28>>^ Ele disse-lhe: “Respondeste corretamente; persiste em fazer isso e obterás a vida.”

[[v42-10-29]]

^<<v42-10-29,29>>^ Mas, querendo mostrar-se justo, o homem perguntou a Jesus: “Quem é realmente o meu próximo?”

[[v42-10-30]]

^<<v42-10-30,30>>^ Em resposta, Jesus disse: “Um homem descia de Jerusalém para Jericó e caiu nas mãos de assaltantes, que o despiram, espancaram e foram-se embora, deixando-o quase morto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Por coincidência, um sacerdote descia por aquela estrada, mas, quando o viu, passou pelo lado oposto.

[[v42-10-32]]

^<<v42-10-32,32>>^ Do mesmo modo, um levita, quando chegou àquele lugar e o viu, passou pelo lado oposto.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas certo samaritano, viajando pela estrada, encontrou-o e, ao vê-lo, teve pena.

[[v42-10-34]]

^<<v42-10-34,34>>^ Por conseguinte, aproximou-se dele e enfaixou os seus ferimentos, derramando sobre eles azeite e vinho. Então, pô-lo no seu próprio animal, levou-o a uma hospedaria e cuidou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte, tirou dois denários,^&#42;1^ deu-os ao hospedeiro e disse: ‘Cuida dele e, tudo o que gastares além disto, pago-te quando voltar.’

[NOTE]
====
. Veja o Ap. B14.
====

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual destes três achas que mostrou ser o próximo do homem que caiu nas mãos dos assaltantes?”

[[v42-10-37]]

^<<v42-10-37,37>>^ Ele respondeu: “Aquele que agiu com misericórdia para com ele.” Jesus disse-lhe então: “Vai e faz o mesmo.”

[[v42-10-38]]

^<<v42-10-38,38>>^ Ao prosseguirem, ele entrou numa certa aldeia. Ali, uma mulher chamada Marta recebeu-o como hóspede na sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Ela tinha também uma irmã, chamada Maria, que se sentou aos pés do Senhor e ficou a escutar o que ele dizia.^&#42;1^

[NOTE]
====
. Lit.: “a sua palavra”.
====

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, por outro lado, estava distraída, a cuidar de muitos afazeres. Assim, ela aproximou-se dele e disse: “Senhor, não te importas que a minha irmã me deixe sozinha para cuidar das coisas? Diz-lhe que me venha ajudar.”

[[v42-10-41]]

^<<v42-10-41,41>>^ Em resposta, o Senhor disse-lhe: “Marta, Marta, estás ansiosa e preocupada com muitas coisas.

[[v42-10-42]]

^<<v42-10-42,42>>^ Mas poucas coisas são necessárias, ou apenas uma. Maria, por sua vez, escolheu a boa porção,^&#42;1^ e esta não lhe será tirada.”

[NOTE]
====
. Ou: “melhor parte”.
====

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]