include::./index.adoc[]

[[v42-20-0]]
=== Lucas, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-20-1]]

^<<v42-20-1,1>>^ Num daqueles dias, enquanto ele ensinava o povo no templo e declarava as boas novas, os principais sacerdotes e os escribas, com os anciãos, vieram

[[v42-20-2]]

^<<v42-20-2,2>>^ e disseram-lhe: “Diz-nos, com que autoridade é que fazes estas coisas? E quem é que te deu esta autoridade?”

[[v42-20-3]]

^<<v42-20-3,3>>^ Ele respondeu-lhes: “Eu também vos vou fazer uma pergunta, e vocês, respondam-me:

[[v42-20-4]]

^<<v42-20-4,4>>^ O batismo de João era do céu ou dos homens?”^&#42;1^

[NOTE]
====
. Ou: “de origem humana”.
====

[[v42-20-5]]

^<<v42-20-5,5>>^ Tiraram então conclusões entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Porque é que não acreditaram nele?’

[[v42-20-6]]

^<<v42-20-6,6>>^ Mas, se dissermos: ‘Dos homens’, todo o povo nos apedrejará, pois estão convencidos de que João era profeta.”

[[v42-20-7]]

^<<v42-20-7,7>>^ Por conseguinte, responderam que não sabiam de onde se originou.

[[v42-20-8]]

^<<v42-20-8,8>>^ Jesus disse-lhes: “Então, eu também não vos digo com que autoridade faço estas coisas.”

[[v42-20-9]]

^<<v42-20-9,9>>^ A seguir, ele começou a contar ao povo a seguinte ilustração: “Um homem plantou um vinhedo e arrendou-o a lavradores, e viajou para fora, por bastante tempo.

[[v42-20-10]]

^<<v42-20-10,10>>^ Na época devida, enviou um escravo aos lavradores, para que lhe dessem alguns dos frutos do vinhedo. Os lavradores, porém, depois de o espancarem, mandaram-no embora de mãos vazias.

[[v42-20-11]]

^<<v42-20-11,11>>^ Mas ele enviou-lhes outro escravo. A esse, também o espancaram, humilharam^&#42;1^ e mandaram embora de mãos vazias.

[NOTE]
====
. Ou: “desonraram”.
====

[[v42-20-12]]

^<<v42-20-12,12>>^ Ele mandou ainda um terceiro, mas também o feriram e expulsaram.

[[v42-20-13]]

^<<v42-20-13,13>>^ Em vista disso, o dono do vinhedo disse: ‘O que farei? Enviarei o meu filho, o amado. É provável que o respeitem.’

[[v42-20-14]]

^<<v42-20-14,14>>^ Quando os lavradores o viram, raciocinaram entre si, dizendo: ‘Este é o herdeiro. Vamos matá-lo, para que a herança se torne nossa.’

[[v42-20-15]]

^<<v42-20-15,15>>^ Assim, atiraram-no para fora do vinhedo e mataram-no. O que lhes fará então o dono do vinhedo?

[[v42-20-16]]

^<<v42-20-16,16>>^ Voltará e matará esses lavradores, e entregará o vinhedo a outros.”
Ao ouvirem isto, eles disseram: “Que isso nunca aconteça!”

[[v42-20-17]]

^<<v42-20-17,17>>^ Mas ele olhou-os fixamente e disse: “O que, então, significa isto que está escrito: ‘A pedra que os construtores rejeitaram, esta tornou-se a principal pedra angular’?^&#42;1^

[NOTE]
====
. Lit.: “a cabeça da esquina”.
====

[[v42-20-18]]

^<<v42-20-18,18>>^ Todo aquele que cair sobre esta pedra será despedaçado. Quanto àquele sobre quem ela cair, será esmagado.”

[[v42-20-19]]

^<<v42-20-19,19>>^ Os escribas e os principais sacerdotes procuraram então agarrá-lo naquele preciso momento, porque perceberam que ele tinha contado esta ilustração a pensar neles. Mas tinham medo do povo.

[[v42-20-20]]

^<<v42-20-20,20>>^ E, depois de o observar com atenção, eles enviaram homens que tinham contratado secretamente para fingirem ser justos, a fim de o apanharem nas suas palavras, e, assim, entregá-lo ao governo e à autoridade do governador.

[[v42-20-21]]

^<<v42-20-21,21>>^ E eles perguntaram-lhe: “Instrutor, sabemos que falas e ensinas corretamente, e não mostras parcialidade, mas ensinas o caminho de Deus em harmonia com a verdade:

[[v42-20-22]]

^<<v42-20-22,22>>^ É lícito^&#42;1^ ou não pagarmos impostos a César?”

[NOTE]
====
. Ou: “permitido; certo”.
====

[[v42-20-23]]

^<<v42-20-23,23>>^ Mas ele percebeu a astúcia deles, e disse-lhes:

[[v42-20-24]]

^<<v42-20-24,24>>^ “Mostrem-me um denário.^&#42;1^ De quem é esta imagem e inscrição?” Responderam: “De César.”

[NOTE]
====
. Veja o Ap. B14.
====

[[v42-20-25]]

^<<v42-20-25,25>>^ Ele disse-lhes: “Sem falta, então, paguem a César o que é de César, mas a Deus o que é de Deus.”

[[v42-20-26]]

^<<v42-20-26,26>>^ Assim, não foram capazes de o apanhar no que ele disse perante o povo, mas, espantados com a sua resposta, ficaram calados.

[[v42-20-27]]

^<<v42-20-27,27>>^ No entanto, alguns dos saduceus, os quais dizem não haver ressurreição, aproximaram-se e perguntaram-lhe:

[[v42-20-28]]

^<<v42-20-28,28>>^ “Instrutor, Moisés escreveu-nos: ‘Se um homem morre e deixa a esposa, mas não deixa filhos, o irmão dele deve casar-se com a viúva para dar descendência ao seu irmão.’

[[v42-20-29]]

^<<v42-20-29,29>>^ Acontece que havia sete irmãos. O primeiro casou-se, mas morreu sem filhos,

[[v42-20-30]]

^<<v42-20-30,30>>^ de modo que o segundo

[[v42-20-31]]

^<<v42-20-31,31>>^ e o terceiro se casaram com a viúva. O mesmo aconteceu com todos os sete; morreram sem deixar filhos.

[[v42-20-32]]

^<<v42-20-32,32>>^ Por fim, morreu também a mulher.

[[v42-20-33]]

^<<v42-20-33,33>>^ Assim, na ressurreição, de qual deles é que ela se tornará esposa? Pois os sete tiveram-na como esposa.”

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus disse-lhes: “Os filhos deste sistema de coisas^&#42;1^ casam-se e são dados em casamento,

[NOTE]
====
. Ou: “desta época”. Veja o Glossário.
====

[[v42-20-35]]

^<<v42-20-35,35>>^ mas os que são considerados dignos de ganhar o vindouro sistema de coisas e a ressurreição dentre os mortos não se casam nem são dados em casamento.

[[v42-20-36]]

^<<v42-20-36,36>>^ De facto, eles já nem podem morrer, porque são como os anjos, e são filhos de Deus por serem filhos da ressurreição.

[[v42-20-37]]

^<<v42-20-37,37>>^ Mas, que os mortos são levantados, até mesmo Moisés o revelou no relato sobre o espinheiro, quando ele chama a Jeová^&#42;1^ ‘o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’.

[NOTE]
====
. Veja o Ap. A5.
====

[[v42-20-38]]

^<<v42-20-38,38>>^ Ele é Deus, não de mortos, mas de vivos, pois, para ele,^&#42;1^ todos eles vivem.”

[NOTE]
====
. Ou: “do ponto de vista dele”.
====

[[v42-20-39]]

^<<v42-20-39,39>>^ Em resposta, alguns dos escribas disseram: “Instrutor, falou bem.”

[[v42-20-40]]

^<<v42-20-40,40>>^ Pois eles já não tinham coragem de lhe fazer uma única pergunta.

[[v42-20-41]]

^<<v42-20-41,41>>^ Em seguida, ele perguntou-lhes: “Como é que dizem que o Cristo é filho de David?

[[v42-20-42]]

^<<v42-20-42,42>>^ Porque o próprio David diz no livro dos Salmos: ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita,

[NOTE]
====
. Veja o Ap. A5.
====

[[v42-20-43]]

^<<v42-20-43,43>>^ até que eu ponha os teus inimigos debaixo dos teus pés.”’^&#42;1^

[NOTE]
====
. Ou: “como escabelo para os teus pés”.
====

[[v42-20-44]]

^<<v42-20-44,44>>^ Portanto, David chama-lhe Senhor. Então, como é que ele é seu filho?”

[[v42-20-45]]

^<<v42-20-45,45>>^ E, enquanto todo o povo escutava, ele disse aos discípulos:

[[v42-20-46]]

^<<v42-20-46,46>>^ “Cuidado com os escribas, que gostam de andar de vestes compridas e gostam muito dos cumprimentos nas praças públicas, dos primeiros^&#42;1^ assentos nas sinagogas e dos lugares mais destacados nos banquetes,

[NOTE]
====
. Ou: “melhores”.
====

[[v42-20-47]]

^<<v42-20-47,47>>^ que devoram as casas^&#42;1^ das viúvas e, para impressionar,^&#42;2^ fazem longas orações. Eles receberão um julgamento mais severo.”^&#42;3^

[NOTE]
====
. Ou: “os bens”.
. Ou: “e, como pretexto”.
. Ou: “pesado”.
====

'''

xref:042-lucas/042-lucas-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-lucas/042-lucas-021.adoc#v42-21-0[Próximo Capítulo &#62;]