include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-11-1]]

^<<v42-11-1,1>>^ Numa ocasião, ele estava em certo lugar a orar e, quando parou, um dos seus discípulos disse-lhe: “Senhor, ensina-nos a orar, assim como João ensinou os discípulos dele.”

[[v42-11-2]]

^<<v42-11-2,2>>^ Ele disse-lhes: “Sempre que orarem, digam: ‘Pai, santificado^&#42;1^ seja o teu nome. Venha o teu Reino.

[NOTE]
====
. Ou: “tido como sagrado; tratado como santo”.
====

[[v42-11-3]]

^<<v42-11-3,3>>^ Dá-nos, cada dia, o nosso pão, segundo as nossas necessidades diárias.

[[v42-11-4]]

^<<v42-11-4,4>>^ E perdoa-nos os nossos pecados, pois nós também perdoamos a todo aquele que está em dívida para connosco; e não nos leves à tentação.’”

[[v42-11-5]]

^<<v42-11-5,5>>^ Então, ele disse-lhes: “Digamos que um de vocês tenha um amigo e vá procurá-lo à meia-noite, e lhe diga: ‘Amigo, empresta-me três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ porque um amigo meu acaba de chegar de uma viagem e eu não tenho nada para lhe oferecer.’

[[v42-11-7]]

^<<v42-11-7,7>>^ Mas ele responde lá de dentro: ‘Não me incomodes mais. A porta já está trancada e os meus filhos estão comigo na cama. Não posso levantar-me e dar-te alguma coisa.’

[[v42-11-8]]

^<<v42-11-8,8>>^ Digo-vos: Ele certamente se levantará para lhe dar tudo o que necessita, não por ser seu amigo, mas por causa da sua persistência e ousadia.

[[v42-11-9]]

^<<v42-11-9,9>>^ Portanto, digo-vos: Persistam em pedir, e ser-vos-á dado; persistam em procurar, e encontrarão; persistam em bater, e ser-vos-á aberto.

[[v42-11-10]]

^<<v42-11-10,10>>^ Pois todo aquele que pede, recebe; e todo aquele que procura, encontra; e a todo aquele que bater, abrir-se-á.

[[v42-11-11]]

^<<v42-11-11,11>>^ Realmente, qual é o pai entre vocês que, se o filho lhe pedir um peixe, lhe entregará uma serpente em vez de um peixe?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou, se lhe pedir também um ovo, lhe entregará um escorpião?

[[v42-11-13]]

^<<v42-11-13,13>>^ Portanto, se vocês, embora maus, sabem dar coisas boas aos vossos filhos, quanto mais o Pai, no céu, dará espírito santo aos que lhe pedirem!”

[[v42-11-14]]

^<<v42-11-14,14>>^ Mais tarde, ele expulsou de um homem um demónio mudo. Depois de o demónio sair, o mudo falou, e as multidões ficaram maravilhadas.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas alguns disseram: “Ele expulsa os demónios por meio de Belzebu,^&#42;1^ o governante dos demónios.”

[NOTE]
====
. Um nome usado para Satanás.
====

[[v42-11-16]]

^<<v42-11-16,16>>^ E outros, para o testarem, começaram a pedir-lhe um sinal do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ Conhecendo os pensamentos deles, ele disse-lhes: “Todo o reino dividido contra si mesmo cai em ruína, e uma casa dividida contra si mesma cai.

[[v42-11-18]]

^<<v42-11-18,18>>^ Da mesma forma, se Satanás também está dividido contra si mesmo, como é que o seu reino ficará de pé? Pois vocês dizem que eu expulso os demónios por meio de Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ Se eu expulso os demónios por meio de Belzebu, por meio de quem é que os vossos filhos os expulsam? É por isso que eles vos julgarão.

[[v42-11-20]]

^<<v42-11-20,20>>^ Mas, se é por meio do dedo de Deus que eu expulso os demónios, o Reino de Deus, realmente, alcançou-vos.

[[v42-11-21]]

^<<v42-11-21,21>>^ Quando um homem forte, bem armado, guarda o seu palácio, os seus bens ficam seguros.

[[v42-11-22]]

^<<v42-11-22,22>>^ Mas, quando alguém mais forte do que ele o ataca e vence, tira-lhe todas as armas em que confiava e reparte as coisas que lhe tirou.

[[v42-11-23]]

^<<v42-11-23,23>>^ Quem não está do meu lado está contra mim, e quem comigo não ajunta, espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ “Quando um espírito impuro sai de um homem, ele passa por lugares áridos à procura de onde descansar e, quando não encontra nenhum, diz: ‘Voltarei para a minha casa, da qual me mudei.’

[[v42-11-25]]

^<<v42-11-25,25>>^ E, ao chegar, encontra a casa varrida e decorada.

[[v42-11-26]]

^<<v42-11-26,26>>^ Então, ele vai e traz consigo outros sete espíritos, ainda piores do que ele, e, depois de entrarem, ficam lá a morar. Assim, a situação final deste homem torna-se pior do que no início.”

[[v42-11-27]]

^<<v42-11-27,27>>^ Enquanto ele dizia isto, uma mulher da multidão disse-lhe bem alto: “Feliz o ventre que te carregou e os seios que te amamentaram!”

[[v42-11-28]]

^<<v42-11-28,28>>^ Contudo, ele disse: “Não, em vez disso, felizes os que ouvem a palavra de Deus e a põem em prática!”

[[v42-11-29]]

^<<v42-11-29,29>>^ Enquanto as multidões se aglomeravam, ele começou a dizer: “Esta geração é uma geração má. Procura um sinal, mas nenhum sinal lhe será dado, exceto o sinal de Jonas.

[[v42-11-30]]

^<<v42-11-30,30>>^ Pois, assim como Jonas foi um sinal para os ninivitas, assim será o Filho do Homem para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do sul será levantada no julgamento com os homens desta geração e irá condená-los, porque ela veio dos confins da terra para ouvir a sabedoria de Salomão. Mas, agora, está aqui alguém maior do que Salomão.

[[v42-11-32]]

^<<v42-11-32,32>>^ Os homens de Nínive irão levantar-se no julgamento com esta geração e condená-la, porque se arrependeram com o que Jonas pregou. Porém, agora, está aqui alguém maior do que Jonas.

[[v42-11-33]]

^<<v42-11-33,33>>^ Depois de acenderem uma lâmpada, as pessoas colocam-na não num lugar oculto nem debaixo de um cesto,^&#42;1^ mas em cima de um suporte, para que os que entram possam ver a luz.

[NOTE]
====
. Ou: “cesto de medida”.
====

[[v42-11-34]]

^<<v42-11-34,34>>^ A lâmpada do corpo é o olho. Quando o teu olho está focado,^&#42;1^ todo o teu corpo também é luminoso;^&#42;2^ mas, quando é invejoso,^&#42;3^ o teu corpo também é escuro.

[NOTE]
====
. Ou: “claro”. Lit.: “singelo”.
. Ou: “cheio de luz”.
. Lit.: “mau; perverso”.
====

[[v42-11-35]]

^<<v42-11-35,35>>^ Por isso, tem cuidado para que a luz que há em ti não seja escuridão.

[[v42-11-36]]

^<<v42-11-36,36>>^ Portanto, se todo o teu corpo for luminoso, sem nenhuma parte escura, todo ele será tão luminoso como uma lâmpada que te ilumina com a sua luz.”

[[v42-11-37]]

^<<v42-11-37,37>>^ Depois de ter dito isto, um fariseu pediu-lhe que comesse com ele. Por conseguinte, entrou e recostou-se à mesa.

[[v42-11-38]]

^<<v42-11-38,38>>^ No entanto, o fariseu ficou surpreso quando viu que ele não se lavou^&#42;1^ antes da refeição.

[NOTE]
====
. Isto é, não se purificou cerimonialmente.
====

[[v42-11-39]]

^<<v42-11-39,39>>^ Mas o Senhor disse-lhe: “Ora, vocês, fariseus, limpam por fora o copo e o prato, mas, por dentro, estão cheios de ganância e de maldade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Insensatos! Aquele que fez o exterior também fez o interior, não fez?

[[v42-11-41]]

^<<v42-11-41,41>>^ Portanto, deem aos pobres^&#42;1^ do que está no íntimo, e, então, tudo a vosso respeito será limpo.

[NOTE]
====
. Ou: “façam dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v42-11-42]]

^<<v42-11-42,42>>^ Mas ai de vocês, fariseus, porque dão o décimo da hortelã, da arruda e de todas as outras ervas,^&#42;1^ mas desconsideram a justiça e o amor a Deus! Tinham a obrigação de fazer estas coisas, mas sem desconsiderar as outras.

[NOTE]
====
. Ou: “hortaliças”.
====

[[v42-11-43]]

^<<v42-11-43,43>>^ Ai de vocês, fariseus, porque gostam muito dos primeiros^&#42;1^ assentos nas sinagogas e dos cumprimentos nas praças públicas!

[NOTE]
====
. Ou: “melhores”.
====

[[v42-11-44]]

^<<v42-11-44,44>>^ Ai de vocês, porque são como aquelas sepulturas^&#42;1^ que não são facilmente vistas,^&#42;2^ e os homens andam sobre elas sem saber!”

[NOTE]
====
. Ou: “aqueles túmulos memoriais”.
. Ou: “que não são assinaladas”.
====

[[v42-11-45]]

^<<v42-11-45,45>>^ Em resposta, um dos peritos na Lei disse-lhe: “Instrutor, ao dizeres estas coisas, também nos insultas.”

[[v42-11-46]]

^<<v42-11-46,46>>^ Ele disse então: “Ai de vocês também, peritos na Lei, porque põem sobre os homens cargas difíceis de levar, mas vocês mesmos não tocam nas cargas nem com um só dedo!

[[v42-11-47]]

^<<v42-11-47,47>>^ “Ai de vocês, porque constroem os túmulos^&#42;1^ dos profetas, mas os vossos antepassados mataram-nos!

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v42-11-48]]

^<<v42-11-48,48>>^ Certamente, vocês são testemunhas das ações dos vossos antepassados e, mesmo assim, aprovam-nas, pois eles mataram os profetas, mas vocês constroem os túmulos deles.

[[v42-11-49]]

^<<v42-11-49,49>>^ Foi por isso que a sabedoria de Deus também disse: ‘Vou enviar-lhes profetas e apóstolos, e eles matarão e perseguirão alguns deles,

[[v42-11-50]]

^<<v42-11-50,50>>^ para que o sangue de todos os profetas, derramado desde a fundação do mundo, seja cobrado^&#42;1^ desta geração,

[NOTE]
====
. Ou: “exigido”.
====

[[v42-11-51]]

^<<v42-11-51,51>>^ desde o sangue de Abel até ao sangue de Zacarias, que foi morto entre o altar e a casa.’^&#42;1^ Sim, digo-vos, será cobrado^&#42;2^ desta geração.

[NOTE]
====
. Ou: “o templo”.
. Ou: “exigido”.
====

[[v42-11-52]]

^<<v42-11-52,52>>^ “Ai de vocês, peritos na Lei, porque se apoderaram da chave do conhecimento. Vocês próprios não entraram e tentam impedir os que estão a entrar!”

[[v42-11-53]]

^<<v42-11-53,53>>^ Assim, quando saiu dali, os escribas e os fariseus começaram a pressioná-lo fortemente e a fazer-lhe muitas outras perguntas,

[[v42-11-54]]

^<<v42-11-54,54>>^ armando ciladas para o apanhar nalguma coisa que dissesse.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]