include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-22-1]]

^<<v42-22-1,1>>^ Aproximava-se então a Festividade dos Pães sem Fermento, a chamada Páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ E os principais sacerdotes e os escribas estavam à procura da melhor maneira de se livrarem dele, porque tinham medo do povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Então, Satanás entrou em Judas, o chamado Iscariotes, que era contado entre os Doze,

[[v42-22-4]]

^<<v42-22-4,4>>^ e este dirigiu-se aos principais sacerdotes e aos capitães do templo para falar com eles sobre como o poderia entregar.^&#42;1^

[NOTE]
====
. Ou: “o trair”.
====

[[v42-22-5]]

^<<v42-22-5,5>>^ Eles alegraram-se com isso e concordaram em dar-lhe dinheiro de prata.

[[v42-22-6]]

^<<v42-22-6,6>>^ Por isso, ele aceitou e começou a procurar uma boa oportunidade para o entregar^&#42;1^ a eles sem que ninguém desse por isso.^&#42;2^

[NOTE]
====
. Ou: “o trair”.
. Ou: “houvesse uma multidão à volta”.
====

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou o dia da Festividade dos Pães sem Fermento, em que se tem de oferecer o sacrifício pascoal;

[[v42-22-8]]

^<<v42-22-8,8>>^ então, Jesus enviou Pedro e João, dizendo: “Vão e preparem a refeição pascoal para que a comamos.”

[[v42-22-9]]

^<<v42-22-9,9>>^ Disseram-lhe: “Onde é que queres que a preparemos?”

[[v42-22-10]]

^<<v42-22-10,10>>^ Ele disse-lhes: “Escutem: Ao entrarem na cidade, um homem que leva um cântaro com água virá ao vosso encontro. Sigam-no para dentro da casa em que ele entrar.

[[v42-22-11]]

^<<v42-22-11,11>>^ E digam ao proprietário da casa: ‘O Instrutor mandou dizer-te: “Onde é a sala dos hóspedes, para que eu tome a refeição pascoal com os meus discípulos?”’

[[v42-22-12]]

^<<v42-22-12,12>>^ E esse homem irá mostrar-vos uma grande sala mobilada no andar de cima. Preparem-na ali.”

[[v42-22-13]]

^<<v42-22-13,13>>^ Eles foram então, e encontraram tudo assim como ele lhes tinha dito, e prepararam a refeição pascoal.

[[v42-22-14]]

^<<v42-22-14,14>>^ Quando chegou a hora, ele recostou-se à mesa com os apóstolos.

[[v42-22-15]]

^<<v42-22-15,15>>^ E disse-lhes: “Tenho desejado muito comer esta refeição pascoal convosco antes de eu sofrer,

[[v42-22-16]]

^<<v42-22-16,16>>^ pois digo-vos: Não voltarei a comê-la até que ela se cumpra no Reino de Deus.”

[[v42-22-17]]

^<<v42-22-17,17>>^ E ele recebeu um cálice, deu graças e disse: “Tomem este cálice e passem-no entre todos,

[[v42-22-18]]

^<<v42-22-18,18>>^ pois digo-vos: De agora em diante, não voltarei a beber do produto da videira até que venha o Reino de Deus.”

[[v42-22-19]]

^<<v42-22-19,19>>^ Ele tomou também um pão, deu graças, partiu-o e deu-lhes, dizendo: “Isto representa o meu corpo, que será dado em vosso benefício. Persistam em fazer isto em memória de mim.”

[[v42-22-20]]

^<<v42-22-20,20>>^ Ele fez o mesmo com o cálice, depois de terem tomado a refeição, dizendo: “Este cálice representa o novo pacto com base no meu sangue, que será derramado em vosso benefício.

[[v42-22-21]]

^<<v42-22-21,21>>^ “Mas saibam que a mão daquele que me trai está comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ De facto, o Filho do Homem vai-se embora, segundo o que foi determinado; porém, ai daquele que o trai!”

[[v42-22-23]]

^<<v42-22-23,23>>^ Assim, começaram a perguntar uns aos outros qual deles realmente estaria prestes a fazer isso.

[[v42-22-24]]

^<<v42-22-24,24>>^ No entanto, eles também começaram uma discussão acalorada sobre qual deles era o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Mas ele disse-lhes: “Os reis das nações dominam sobre elas, e os que têm autoridade sobre elas são chamados ‘benfeitores’.

[[v42-22-26]]

^<<v42-22-26,26>>^ Vocês, porém, não devem ser assim. Mas que o maior entre vocês se torne como o mais jovem, e o que lidera, como aquele que serve.^&#42;1^

[NOTE]
====
. Ou: “ministra”.
====

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois quem é maior: aquele que está^&#42;1^ à mesa ou aquele que serve?^&#42;2^ Não é quem está^&#42;3^ à mesa? Mas eu estou no vosso meio como quem serve.^&#42;4^

[NOTE]
====
. Ou: “se recosta”.
. Ou: “ministra”.
. Ou: “se recosta”.
. Ou: “ministra”.
====

[[v42-22-28]]

^<<v42-22-28,28>>^ “No entanto, vocês são os que ficaram comigo nas minhas provações;

[[v42-22-29]]

^<<v42-22-29,29>>^ e eu faço convosco um pacto para um reino, assim como o meu Pai fez um pacto comigo,

[[v42-22-30]]

^<<v42-22-30,30>>^ a fim de que comam e bebam à minha mesa, no meu Reino, e se sentem em tronos para julgar as 12 tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ “Simão, Simão, escuta: Satanás exigiu que todos vocês fossem peneirados como trigo.

[[v42-22-32]]

^<<v42-22-32,32>>^ Mas tenho feito súplicas por ti para que a tua fé não fraqueje; e tu, quando tiveres voltado, fortalece os teus irmãos.”

[[v42-22-33]]

^<<v42-22-33,33>>^ Então, ele disse-lhe: “Senhor, estou pronto para ir contigo tanto para a prisão como para a morte.”

[[v42-22-34]]

^<<v42-22-34,34>>^ Mas ele disse: “Digo-te, Pedro: Hoje, o galo não cantará até que tu tenhas negado três vezes que me conheces.”

[[v42-22-35]]

^<<v42-22-35,35>>^ Ele disse-lhes também: “Quando vos enviei sem bolsa de dinheiro, sem alforge^&#42;1^ e sem sandálias, será que vos faltou alguma coisa?” Eles disseram: “Não!”

[NOTE]
====
. Ou: “bolsa de alimentos”.
====

[[v42-22-36]]

^<<v42-22-36,36>>^ Então, ele disse-lhes: “Mas, agora, quem tiver bolsa de dinheiro, leve-a consigo, e também um alforge;^&#42;1^ e quem não tiver espada, venda a sua capa e compre uma.

[NOTE]
====
. Ou: “bolsa de alimentos”.
====

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois digo-vos que tem de se cumprir em mim aquilo que foi escrito: ‘Ele foi contado entre os transgressores.’ Sim, isso está a cumprir-se em mim.”

[[v42-22-38]]

^<<v42-22-38,38>>^ Então, disseram: “Senhor, temos aqui duas espadas.” Ele disse-lhes: “É o suficiente.”

[[v42-22-39]]

^<<v42-22-39,39>>^ Ao sair, ele foi, como de costume, para o monte das Oliveiras, e os discípulos também o seguiram.

[[v42-22-40]]

^<<v42-22-40,40>>^ Quando chegaram lá, ele disse-lhes: “Persistam em orar, para que não caiam em tentação.”

[[v42-22-41]]

^<<v42-22-41,41>>^ E ele afastou-se deles à distância de um tiro de pedra,^&#42;1^ ajoelhou-se e começou a orar,

[NOTE]
====
. Ou: “a uma curta distância”.
====

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: “Pai, se tu quiseres, afasta de mim este cálice. Contudo, ocorra não a minha vontade, mas a tua.”

[[v42-22-43]]

^<<v42-22-43,43>>^ Apareceu-lhe então um anjo do céu e fortaleceu-o.

[[v42-22-44]]

^<<v42-22-44,44>>^ Mas ele ficou tão angustiado que orou ainda mais intensamente; e o seu suor tornou-se como gotas de sangue que caíam no chão.

[[v42-22-45]]

^<<v42-22-45,45>>^ Quando se levantou depois de orar e se dirigiu aos discípulos, encontrou-os a dormir, exaustos de tristeza.

[[v42-22-46]]

^<<v42-22-46,46>>^ Ele disse-lhes: “Porque é que estão a dormir? Levantem-se e continuem a orar, para que não caiam em tentação.”

[[v42-22-47]]

^<<v42-22-47,47>>^ Enquanto ele ainda falava, chegou uma multidão, e o homem chamado Judas, um dos Doze, liderava-os, e aproximou-se de Jesus para o beijar.

[[v42-22-48]]

^<<v42-22-48,48>>^ No entanto, Jesus disse-lhe: “Judas, estás a trair o Filho do Homem com um beijo?”

[[v42-22-49]]

^<<v42-22-49,49>>^ Quando os que estavam à sua volta viram o que ia acontecer, disseram: “Senhor, devemos atacá-los com a espada?”

[[v42-22-50]]

^<<v42-22-50,50>>^ Um deles até mesmo atacou o escravo do sumo sacerdote, cortando-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus disse, em resposta: “Basta!” E tocou na orelha e curou-o.

[[v42-22-52]]

^<<v42-22-52,52>>^ Jesus disse então aos principais sacerdotes, aos capitães do templo e aos anciãos que tinham ido lá buscá-lo: “Vieram com espadas e bastões, como se eu fosse um bandido?

[[v42-22-53]]

^<<v42-22-53,53>>^ Enquanto eu estava convosco no templo, dia após dia, não me tentaram prender. Mas esta é a vossa hora e a autoridade da escuridão.”

[[v42-22-54]]

^<<v42-22-54,54>>^ Então, prenderam-no e levaram-no para a casa do sumo sacerdote. Mas Pedro seguia-os à distância.

[[v42-22-55]]

^<<v42-22-55,55>>^ Quando acenderam uma fogueira no meio do pátio e se sentaram juntos, Pedro sentou-se entre eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Todavia, uma serva, vendo-o sentado à luz da fogueira, olhou atentamente para ele e disse: “Este homem também estava com ele.”

[[v42-22-57]]

^<<v42-22-57,57>>^ Contudo, ele negou, dizendo: “Não o conheço, mulher.”

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco tempo depois, outra pessoa viu-o e disse: “Tu também és um deles.” Pedro, porém, disse: “Homem, não sou.”

[[v42-22-59]]

^<<v42-22-59,59>>^ E, depois de passar cerca de uma hora, outro homem começou a insistir: “Este homem, com certeza, também estava com ele, pois, de facto, é galileu!”

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro disse: “Homem, não sei do que estás a falar.” E, naquele instante, enquanto ainda falava, um galo cantou.

[[v42-22-61]]

^<<v42-22-61,61>>^ Com isso, o Senhor virou-se e olhou diretamente para Pedro, e Pedro lembrou-se da declaração do Senhor, que lhe tinha dito: “Hoje, antes de o galo cantar, vais negar-me três vezes.”

[[v42-22-62]]

^<<v42-22-62,62>>^ Então, ele saiu dali e chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que detinham Jesus começaram então a ridicularizá-lo, batendo-lhe;

[[v42-22-64]]

^<<v42-22-64,64>>^ e, depois de lhe cobrirem o rosto, diziam: “Profetiza! Quem é que te bateu?”

[[v42-22-65]]

^<<v42-22-65,65>>^ E diziam muitas outras blasfémias contra ele.

[[v42-22-66]]

^<<v42-22-66,66>>^ Quando o dia amanheceu, reuniu-se a assembleia dos anciãos do povo, tanto os principais sacerdotes como os escribas; eles levaram-no para o Sinédrio e disseram:

[[v42-22-67]]

^<<v42-22-67,67>>^ “Se tu és o Cristo, diz-nos.” Contudo, ele disse-lhes: “Mesmo que eu vos dissesse, de modo algum acreditariam.

[[v42-22-68]]

^<<v42-22-68,68>>^ Além disso, se eu vos fizesse perguntas, não me responderiam.

[[v42-22-69]]

^<<v42-22-69,69>>^ No entanto, de agora em diante, o Filho do Homem estará sentado à direita do Deus poderoso.”

[[v42-22-70]]

^<<v42-22-70,70>>^ Em vista disso, todos perguntaram: “Então, tu és o Filho de Deus?” Ele respondeu-lhes: “Vocês é que dizem que eu o sou.”

[[v42-22-71]]

^<<v42-22-71,71>>^ Eles disseram: “Porque é que precisamos de mais testemunho? Pois nós mesmos ouvimo-lo da sua própria boca.”

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]