include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-24-1]]

^<<v42-24-1,1>>^ No primeiro dia da semana, porém, elas chegaram bem cedo ao túmulo,^&#42;1^ levando os aromas que tinham preparado.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-2]]

^<<v42-24-2,2>>^ Mas viram que a pedra da entrada do túmulo^&#42;1^ tinha sido rolada

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-3]]

^<<v42-24-3,3>>^ e, quando entraram, não encontraram o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ Enquanto estavam perplexas com isto, dois homens de roupa brilhante apareceram ao lado delas.

[[v42-24-5]]

^<<v42-24-5,5>>^ As mulheres ficaram com medo e mantiveram a cabeça virada para o chão; então, os homens disseram-lhes: “Porque procuram entre os mortos aquele que está vivo?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui, mas foi levantado. Lembrem-se de que, enquanto ainda estava na Galileia, ele disse-vos

[[v42-24-7]]

^<<v42-24-7,7>>^ que o Filho do Homem tinha de ser entregue a pecadores, ser morto na estaca e, no terceiro dia, ser levantado.”

[[v42-24-8]]

^<<v42-24-8,8>>^ E elas lembraram-se das palavras dele;

[[v42-24-9]]

^<<v42-24-9,9>>^ então, voltaram do túmulo^&#42;1^ e contaram todas estas coisas aos Onze e a todos os demais.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-10]]

^<<v42-24-10,10>>^ Elas eram Maria Madalena, Joana e Maria, mãe de Tiago. Também as outras mulheres com elas contaram estas coisas aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ No entanto, estas declarações pareciam-lhes não fazer sentido, e eles recusavam-se a acreditar nas mulheres.

[[v42-24-12]]

^<<v42-24-12,12>>^ Mas Pedro levantou-se e correu para o túmulo;^&#42;1^ e, inclinando-se para a frente, só viu os panos de linho. Assim, foi-se embora, perguntando-se o que teria ocorrido.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-13]]

^<<v42-24-13,13>>^ Mas, naquele mesmo dia, dois deles viajavam para uma aldeia chamada Emaús, a cerca de 11 quilómetros^&#42;1^ de Jerusalém,

[NOTE]
====
. Lit.: “60 estádios”. Um estádio equivalia a 185 m. Veja o Ap. B14.
====

[[v42-24-14]]

^<<v42-24-14,14>>^ e conversavam sobre todas as coisas que tinham acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto conversavam e discutiam estas coisas, o próprio Jesus aproximou-se e começou a andar com eles,

[[v42-24-16]]

^<<v42-24-16,16>>^ mas os olhos deles foram impedidos de o reconhecer.

[[v42-24-17]]

^<<v42-24-17,17>>^ Ele perguntou-lhes: “Sobre o que é que estão a conversar^&#42;1^ enquanto caminham?” E eles pararam, com um ar triste.

[NOTE]
====
. Ou: “a discutir”.
====

[[v42-24-18]]

^<<v42-24-18,18>>^ Em resposta, aquele chamado Cléopas disse-lhe: “Será que és um estrangeiro que vive sozinho em Jerusalém e não sabes^&#42;1^ das coisas que lá ocorreram nestes dias?”

[NOTE]
====
. Ou, possivelmente: “Será que és o único visitante em Jerusalém que não sabe”.
====

[[v42-24-19]]

^<<v42-24-19,19>>^ Ele perguntou-lhes: “Que coisas?” Responderam: “As coisas a respeito de Jesus, o Nazareno, que foi um profeta poderoso em ações e palavras perante Deus e todo o povo;

[[v42-24-20]]

^<<v42-24-20,20>>^ e os nossos principais sacerdotes e os nossos líderes entregaram-no para ser condenado à morte e pregaram-no na estaca.

[[v42-24-21]]

^<<v42-24-21,21>>^ Mas nós esperávamos que este homem fosse aquele que livraria Israel. E, além de tudo isto, este já é o terceiro dia desde que estas coisas ocorreram.

[[v42-24-22]]

^<<v42-24-22,22>>^ Além disso, algumas mulheres entre nós deixaram-nos pasmados, porque foram cedo ao túmulo^&#42;1^

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-23]]

^<<v42-24-23,23>>^ e, quando não encontraram o corpo dele, voltaram, dizendo que tinham tido também uma visão sobrenatural de anjos, que disseram que ele está vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Então, alguns dos que estavam connosco foram ao túmulo^&#42;1^ e encontraram tudo exatamente como as mulheres tinham dito, mas não o viram.”

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-25]]

^<<v42-24-25,25>>^ Assim, ele disse-lhes: “Como vocês são insensatos e demoram a^&#42;1^ crer em todas as coisas faladas pelos profetas!

[NOTE]
====
. Ou: “e lentos de coração para”.
====

[[v42-24-26]]

^<<v42-24-26,26>>^ Não era necessário que o Cristo sofresse estas coisas e entrasse na sua glória?”

[[v42-24-27]]

^<<v42-24-27,27>>^ E, começando por Moisés e por todos os Profetas, interpretou-lhes as coisas a respeito de si mesmo em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ Por fim, aproximaram-se da aldeia para a qual iam, e ele agiu como se fosse para mais longe.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas insistiram que ele ficasse com eles, dizendo: “Fica connosco, porque já está a anoitecer e o dia está quase a terminar.” Em vista disso, entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ E, enquanto comia^&#42;1^ com eles, pegou no pão, deu graças,^&#42;2^ partiu-o e começou a dá-lo a eles.

[NOTE]
====
. Ou: “se recostava à mesa”.
. Ou: “ abençoou-o”.
====

[[v42-24-31]]

^<<v42-24-31,31>>^ Com isso, os olhos deles abriram-se plenamente e reconheceram-no; mas ele desapareceu.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um ao outro: “Não nos ardia o coração, dentro de nós, quando ele nos falava na estrada, ao abrir-nos plenamente^&#42;1^ as Escrituras?”

[NOTE]
====
. Ou: “explicar-nos claramente”.
====

[[v42-24-33]]

^<<v42-24-33,33>>^ Eles levantaram-se naquele preciso momento, voltaram a Jerusalém e encontraram os Onze e os que estavam reunidos com eles;

[[v42-24-34]]

^<<v42-24-34,34>>^ e diziam: “De facto, o Senhor foi levantado e apareceu a Simão!”

[[v42-24-35]]

^<<v42-24-35,35>>^ Então, eles contaram o que tinha acontecido na estrada e como o reconheceram quando ele partiu o pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto ainda falavam destas coisas, o próprio Jesus apareceu no meio deles e disse-lhes: “Que a paz esteja convosco.”

[[v42-24-37]]

^<<v42-24-37,37>>^ Mas eles, espantados e com medo, pensaram que estavam a ver um espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ Portanto, ele disse-lhes: “Porque é que estão aflitos e porque é que surgem dúvidas no vosso coração?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vejam as minhas mãos e os meus pés, que sou eu mesmo. Toquem-me e vejam, pois um espírito não tem carne nem ossos, assim como veem que eu tenho.”

[[v42-24-40]]

^<<v42-24-40,40>>^ E, ao dizer isso, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ Mas eles ainda não acreditavam, de tanta alegria e surpresa. Então, ele disse-lhes: “Têm aqui alguma coisa para comer?”

[[v42-24-42]]

^<<v42-24-42,42>>^ Deram-lhe um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ e ele aceitou-o e comeu diante dos olhos deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ Depois, ele disse-lhes: “Estas são as minhas palavras, que vos transmiti enquanto ainda estava convosco, que todas as coisas escritas a meu respeito na Lei de Moisés, nos Profetas e nos Salmos têm de se cumprir.”

[[v42-24-45]]

^<<v42-24-45,45>>^ Então, ele abriu-lhes a mente para que compreendessem o significado das Escrituras

[[v42-24-46]]

^<<v42-24-46,46>>^ e disse-lhes: “Está escrito que o Cristo sofreria e, no terceiro dia, seria levantado dentre os mortos,

[[v42-24-47]]

^<<v42-24-47,47>>^ e que, em seu nome, se pregaria arrependimento para o perdão de pecados em todas as nações, começando por Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vocês serão testemunhas destas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ E saibam que vos enviarei o que foi prometido pelo meu Pai. Contudo, permaneçam na cidade até serem revestidos de poder vindo do alto.”

[[v42-24-50]]

^<<v42-24-50,50>>^ A seguir, ele levou-os para fora, até Betânia, ergueu as mãos e abençoou-os.

[[v42-24-51]]

^<<v42-24-51,51>>^ Enquanto os abençoava, foi separado deles e levado para o céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ E curvaram-se diante dele^&#42;1^ e voltaram para Jerusalém com grande alegria.

[NOTE]
====
. Ou: “prestaram-lhe homenagem”.
====

[[v42-24-53]]

^<<v42-24-53,53>>^ E estavam constantemente no templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]