include::./index.adoc[]

[[v42-14-0]]
=== Lucas, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-14-1]]

^<<v42-14-1,1>>^ Noutra ocasião, ele foi comer à casa de um líder dos fariseus, no sábado, e eles observavam-no atentamente.

[[v42-14-2]]

^<<v42-14-2,2>>^ E à frente dele estava um homem que sofria de hidropisia.^&#42;1^

[NOTE]
====
. Ou: “edema”, uma acumulação excessiva de líquido no corpo.
====

[[v42-14-3]]

^<<v42-14-3,3>>^ Em vista disso, Jesus perguntou aos peritos na Lei e aos fariseus: “É permitido ou não curar no sábado?”

[[v42-14-4]]

^<<v42-14-4,4>>^ Mas eles ficaram calados. Assim, ele tocou no homem, curou-o e mandou-o embora.

[[v42-14-5]]

^<<v42-14-5,5>>^ Então, disse-lhes: “Qual de vocês não tirará imediatamente o seu filho ou o seu touro de um poço, se ele lá cair no dia de sábado?”

[[v42-14-6]]

^<<v42-14-6,6>>^ E eles ficaram sem resposta.

[[v42-14-7]]

^<<v42-14-7,7>>^ A seguir, ele contou aos convidados uma ilustração, quando reparou que eles escolhiam os lugares mais destacados. Disse-lhes:

[[v42-14-8]]

^<<v42-14-8,8>>^ “Quando alguém te convidar para uma festa de casamento, não te recostes no lugar mais destacado. Talvez uma pessoa com mais destaque do que tu também tenha sido convidada.

[[v42-14-9]]

^<<v42-14-9,9>>^ Então, aquele que convidou ambos vai chegar e dizer-te: ‘Dá o teu lugar a este homem.’ Então, irás, envergonhado, ocupar o último lugar.

[[v42-14-10]]

^<<v42-14-10,10>>^ Mas, quando fores convidado, recosta-te no último lugar, para que, quando chegar o homem que te convidou, ele te diga: ‘Amigo, passa para um lugar mais importante.’ Então, terás honra à frente de todos os outros convidados.

[[v42-14-11]]

^<<v42-14-11,11>>^ Porque todo aquele que se enaltecer será humilhado, e aquele que se humilhar será enaltecido.”

[[v42-14-12]]

^<<v42-14-12,12>>^ A seguir, ele disse também ao homem que o tinha convidado: “Quando ofereceres um almoço ou um jantar, não chames os teus amigos, nem os teus irmãos, nem os teus parentes, nem os teus vizinhos ricos. Pois eles, por sua vez, também poderiam convidar-te, e isso seria uma retribuição para ti.

[[v42-14-13]]

^<<v42-14-13,13>>^ Mas, quando ofereceres um banquete, convida os pobres, os aleijados, os coxos, os cegos;

[[v42-14-14]]

^<<v42-14-14,14>>^ e serás feliz, porque eles não têm nada com que te recompensar. Pois serás recompensado na ressurreição dos justos.”

[[v42-14-15]]

^<<v42-14-15,15>>^ Ao ouvir estas coisas, um dos outros convidados disse-lhe: “Feliz é aquele que participa do banquete^&#42;1^ no Reino de Deus.”

[NOTE]
====
. Lit.: “come pão”.
====

[[v42-14-16]]

^<<v42-14-16,16>>^ Jesus disse-lhe: “Um homem convidou muitas pessoas para um grande banquete.^&#42;1^

[NOTE]
====
. Ou: “uma grande ceia”.
====

[[v42-14-17]]

^<<v42-14-17,17>>^ À hora do banquete,^&#42;1^ enviou o seu escravo, para dizer aos convidados: ‘Venham, porque já está tudo pronto.’

[NOTE]
====
. Ou: “da ceia”.
====

[[v42-14-18]]

^<<v42-14-18,18>>^ Mas todos, sem exceção, começaram a desculpar-se. O primeiro disse: ‘Comprei um campo, e tenho de ir vê-lo. Peço-te que me desculpes.’

[[v42-14-19]]

^<<v42-14-19,19>>^ E outro disse: ‘Comprei cinco juntas^&#42;1^ de bois e vou examiná-las. Peço-te que me desculpes.’

[NOTE]
====
. Ou: “pares”.
====

[[v42-14-20]]

^<<v42-14-20,20>>^ Ainda outro disse: ‘Acabei de me casar e por isso não posso ir.’

[[v42-14-21]]

^<<v42-14-21,21>>^ Assim, o escravo voltou e contou estas coisas ao seu senhor. O dono da casa ficou furioso e disse ao escravo: ‘Vai depressa às ruas principais e aos becos da cidade, e traz para aqui os pobres, os aleijados, os cegos e os coxos.’

[[v42-14-22]]

^<<v42-14-22,22>>^ Mais tarde, o escravo disse: ‘Senhor, foi feito o que ordenou, mas ainda há lugares.’

[[v42-14-23]]

^<<v42-14-23,23>>^ Então, o senhor disse ao escravo: ‘Vai para as estradas e para os caminhos, e obriga-os a entrar, a fim de que a minha casa fique cheia.

[[v42-14-24]]

^<<v42-14-24,24>>^ Pois eu vos digo: Nenhum daqueles homens que foram convidados provará o meu banquete.’”^&#42;1^

[NOTE]
====
. Ou: “a minha ceia”.
====

[[v42-14-25]]

^<<v42-14-25,25>>^ Grandes multidões viajavam com ele, e ele virou-se e disse-lhes:

[[v42-14-26]]

^<<v42-14-26,26>>^ “Se alguém vem a mim e não odeia^&#42;1^ o pai, a mãe, a esposa, os filhos, os irmãos, as irmãs, sim, e até mesmo a própria vida,^&#42;2^ não pode ser meu discípulo.

[NOTE]
====
. Ou: “não ama menos”.
. Ou: “alma”.
====

[[v42-14-27]]

^<<v42-14-27,27>>^ Quem não carrega a sua estaca de tortura^&#42;1^ e não me segue, não pode ser meu discípulo.

[NOTE]
====
. Veja o Glossário.
====

[[v42-14-28]]

^<<v42-14-28,28>>^ Por exemplo, quem de vocês, querendo construir uma torre, não se senta primeiro e calcula a despesa, para ver se tem o suficiente para a completar?

[[v42-14-29]]

^<<v42-14-29,29>>^ Senão, ele lançará o alicerce, mas não a conseguirá terminar, e todos os observadores começarão a rir-se dele,

[[v42-14-30]]

^<<v42-14-30,30>>^ dizendo: ‘Este homem começou a construir, mas não conseguiu terminar.’

[[v42-14-31]]

^<<v42-14-31,31>>^ Ou que rei, antes de marchar para guerrear contra outro rei, não se senta e se aconselha para ver se consegue, com 10 000 soldados, enfrentar o que vem contra ele com 20 000?

[[v42-14-32]]

^<<v42-14-32,32>>^ De facto, se ele vir que não consegue, envia um grupo de embaixadores e propõe um acordo de paz, enquanto o outro ainda está longe.

[[v42-14-33]]

^<<v42-14-33,33>>^ Da mesma forma, estejam certos de que nenhum de vocês que não se despedir^&#42;1^ de todos os seus bens poderá ser meu discípulo.

[NOTE]
====
. Ou: “não abdicar”.
====

[[v42-14-34]]

^<<v42-14-34,34>>^ “O sal, certamente, é bom. Mas, se o sal perder a sua força, como se recuperará o seu sabor?

[[v42-14-35]]

^<<v42-14-35,35>>^ Não serve nem para o solo, nem para o estrume. As pessoas deitam-no fora. Quem tem ouvidos para ouvir, ouça.”

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]