include::./index.adoc[]

[[v42-23-0]]
=== Lucas, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-23-1]]

^<<v42-23-1,1>>^ Assim, toda a multidão se levantou, e levaram-no a Pilatos.

[[v42-23-2]]

^<<v42-23-2,2>>^ Então, começaram a acusá-lo, dizendo: “Encontrámos este homem a desencaminhar a nossa nação, a proibir o pagamento de impostos a César e a dizer que ele mesmo é Cristo, um rei.”

[[v42-23-3]]

^<<v42-23-3,3>>^ Pilatos perguntou-lhe então: “És tu o Rei dos judeus?” Em resposta, ele disse: “É o senhor que o está a dizer.”

[[v42-23-4]]

^<<v42-23-4,4>>^ A seguir, Pilatos disse aos principais sacerdotes e à multidão: “Não encontro razão para condenar este homem.”

[[v42-23-5]]

^<<v42-23-5,5>>^ Mas eles insistiram, dizendo: “Ele atiça o povo ao ensinar em toda a Judeia, desde a Galileia até aqui.”

[[v42-23-6]]

^<<v42-23-6,6>>^ Ao ouvir isso, Pilatos perguntou se o homem era galileu.

[[v42-23-7]]

^<<v42-23-7,7>>^ Ao saber que ele estava sob a jurisdição de Herodes, enviou-o a Herodes, que também estava em Jerusalém naqueles dias.

[[v42-23-8]]

^<<v42-23-8,8>>^ Quando Herodes viu Jesus, alegrou-se muito. Há bastante tempo que queria ver Jesus, porque tinha ouvido falar muito dele, e esperava ver algum sinal realizado por ele.

[[v42-23-9]]

^<<v42-23-9,9>>^ Começou então a fazer-lhe muitas perguntas, mas ele não lhe deu resposta nenhuma.

[[v42-23-10]]

^<<v42-23-10,10>>^ No entanto, os principais sacerdotes e os escribas levantavam-se e acusavam-no vigorosamente.

[[v42-23-11]]

^<<v42-23-11,11>>^ Então, Herodes, juntamente com os seus soldados, tratou-o com desprezo e ridicularizou-o, vestindo-o com uma roupa esplêndida, e, depois, mandou-o de volta a Pilatos.

[[v42-23-12]]

^<<v42-23-12,12>>^ Naquele mesmo dia, Herodes e Pilatos, que antes eram inimigos, tornaram-se amigos.

[[v42-23-13]]

^<<v42-23-13,13>>^ Pilatos convocou então os principais sacerdotes, os líderes e o povo,

[[v42-23-14]]

^<<v42-23-14,14>>^ e disse-lhes: “Trouxeram-me este homem como se fosse alguém que incita o povo à revolta. Pois bem, eu interroguei-o à vossa frente, mas não encontrei neste homem base para as acusações que vocês levantam contra ele.

[[v42-23-15]]

^<<v42-23-15,15>>^ De facto, nem Herodes encontrou, pois mandou-o de volta para nós. Como podem ver, ele não fez nada que mereça a morte.

[[v42-23-16]]

^<<v42-23-16,16>>^ Portanto, vou castigá-lo e soltá-lo.”

[[v42-23-17]]

^<<v42-23-17,17>>^ ^&#42;1^——

[NOTE]
====
. Veja o Ap. A3.
====

[[v42-23-18]]

^<<v42-23-18,18>>^ Contudo, toda a multidão gritou: “Mate esse homem^&#42;1^ e solte Barrabás!”

[NOTE]
====
. Lit.: “Leve-o embora”.
====

[[v42-23-19]]

^<<v42-23-19,19>>^ (Este homem tinha sido mandado para a prisão por causa de uma sedição^&#42;1^ ocorrida na cidade e por assassinato.)

[NOTE]
====
. Ou: “revolta; perturbação da ordem pública”.
====

[[v42-23-20]]

^<<v42-23-20,20>>^ Pilatos falou com eles novamente, porque queria soltar Jesus.

[[v42-23-21]]

^<<v42-23-21,21>>^ E começaram a gritar: “Para a estaca com ele! Para a estaca com ele!”^&#42;1^

[NOTE]
====
. Ou: “Executem-no na estaca! Executem-no na estaca!”
====

[[v42-23-22]]

^<<v42-23-22,22>>^ Ele disse-lhes pela terceira vez: “Porquê? O que é que este homem fez de mal? Não encontrei nele nada que mereça a morte. Portanto, vou castigá-lo e soltá-lo.”

[[v42-23-23]]

^<<v42-23-23,23>>^ Em vista disso, começaram a insistir, exigindo aos gritos que ele fosse executado,^&#42;1^ e a voz deles prevaleceu.

[NOTE]
====
. Ou: “executado na estaca”.
====

[[v42-23-24]]

^<<v42-23-24,24>>^ Então, Pilatos decidiu atender ao pedido deles.

[[v42-23-25]]

^<<v42-23-25,25>>^ Ele soltou o homem que pediam, que tinha sido mandado para a prisão por sedição^&#42;1^ e assassinato, mas entregou-lhes Jesus, segundo a vontade deles.

[NOTE]
====
. Ou: “revolta; perturbação da ordem pública”.
====

[[v42-23-26]]

^<<v42-23-26,26>>^ Enquanto o levavam, agarraram num certo Simão de Cirene, que vinha do campo, e puseram a estaca^&#42;1^ sobre ele para que a carregasse atrás de Jesus.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v42-23-27]]

^<<v42-23-27,27>>^ Um grande número de pessoas seguia-o, incluindo mulheres que batiam no peito de pesar e que se lamentavam por ele.

[[v42-23-28]]

^<<v42-23-28,28>>^ Jesus virou-se para as mulheres e disse: “Filhas de Jerusalém, parem de chorar por mim. Em vez disso, chorem por vocês mesmas e pelos vossos filhos;

[[v42-23-29]]

^<<v42-23-29,29>>^ pois saibam que virão dias em que as pessoas dirão: ‘Felizes as mulheres estéreis, os ventres que não deram à luz e os peitos que não amamentaram!’

[[v42-23-30]]

^<<v42-23-30,30>>^ Então, começarão a dizer às montanhas: ‘Caiam sobre nós!’, e às colinas: ‘Cubram-nos!’

[[v42-23-31]]

^<<v42-23-31,31>>^ Se eles fazem isto quando a árvore está verde, o que ocorrerá quando estiver seca?”

[[v42-23-32]]

^<<v42-23-32,32>>^ Dois outros homens, criminosos, também estavam a ser levados para serem executados com ele.

[[v42-23-33]]

^<<v42-23-33,33>>^ E, quando chegaram ao lugar chamado Caveira, pregaram-no na estaca ao lado dos criminosos, um à sua direita e outro à sua esquerda.

[[v42-23-34]]

^<<v42-23-34,34>>^ Mas Jesus dizia: “Pai, perdoa-lhes, pois não sabem o que fazem.” Além disso, lançaram sortes para repartir as roupas dele.

[[v42-23-35]]

^<<v42-23-35,35>>^ E o povo ficou parado, a olhar. Mas os líderes gozavam e diziam: “Ele salvou outros; que se salve a si mesmo, se é o Cristo de Deus, o Escolhido.”

[[v42-23-36]]

^<<v42-23-36,36>>^ Até mesmo os soldados fizeram pouco dele, aproximando-se e oferecendo-lhe vinho acre,

[[v42-23-37]]

^<<v42-23-37,37>>^ e dizendo: “Se tu és o Rei dos judeus, salva-te a ti mesmo.”

[[v42-23-38]]

^<<v42-23-38,38>>^ Havia também uma inscrição por cima dele: “Este é o Rei dos judeus.”

[[v42-23-39]]

^<<v42-23-39,39>>^ Então, um dos criminosos que estavam pendurados começou a insultá-lo, dizendo: “Tu não és o Cristo? Salva-te a ti mesmo e a nós também!”

[[v42-23-40]]

^<<v42-23-40,40>>^ Em resposta, o outro censurou-o, dizendo: “Tu não tens nenhum temor de Deus, agora que recebeste o mesmo julgamento?

[[v42-23-41]]

^<<v42-23-41,41>>^ E, no nosso caso, é justo, pois estamos a receber o que merecemos pelas coisas que fizemos. Mas este homem não fez nada de errado.”

[[v42-23-42]]

^<<v42-23-42,42>>^ Então, ele disse: “Jesus, lembra-te de mim quando entrares no teu Reino.”

[[v42-23-43]]

^<<v42-23-43,43>>^ E ele disse-lhe: “Em verdade, digo-te hoje: Estarás comigo no Paraíso.”

[[v42-23-44]]

^<<v42-23-44,44>>^ Já era por volta da sexta hora;^&#42;1^ contudo, caiu uma escuridão sobre toda aquela terra, até à nona hora,^&#42;2^

[NOTE]
====
. Isto é, por volta do meio-dia.
. Isto é, por volta das 3 h da tarde.
====

[[v42-23-45]]

^<<v42-23-45,45>>^ porque a luz do sol falhou. Então, a cortina do santuário rasgou-se ao meio.

[[v42-23-46]]

^<<v42-23-46,46>>^ E Jesus clamou em voz alta e disse: “Pai, às tuas mãos confio o meu espírito.” Depois de dizer isto, ele morreu.^&#42;1^

[NOTE]
====
. Ou: “expirou; deu o seu último suspiro”.
====

[[v42-23-47]]

^<<v42-23-47,47>>^ Ao ver o que estava a acontecer, o oficial do exército começou a glorificar a Deus, dizendo: “Realmente, este homem era justo.”

[[v42-23-48]]

^<<v42-23-48,48>>^ E toda a multidão que se tinha reunido para este espetáculo viu o que estava a acontecer; então, voltaram para casa, a bater no peito de pesar.

[[v42-23-49]]

^<<v42-23-49,49>>^ Todos os conhecidos dele estavam parados à distância. Além disso, mulheres que o tinham acompanhado desde a Galileia estavam lá e viram estas coisas.

[[v42-23-50]]

^<<v42-23-50,50>>^ Havia um homem chamado José, membro do Conselho, que era um homem bom e justo.

[[v42-23-51]]

^<<v42-23-51,51>>^ (Este homem não tinha votado em apoio da trama e da ação deles.) Ele era de Arimateia, uma cidade da Judeia, e aguardava o Reino de Deus.

[[v42-23-52]]

^<<v42-23-52,52>>^ Este homem compareceu perante Pilatos e pediu o corpo de Jesus.

[[v42-23-53]]

^<<v42-23-53,53>>^ Então, tirou-o de lá, enrolou-o em linho fino e colocou-o num túmulo^&#42;1^ escavado na rocha, onde ainda ninguém tinha sido sepultado.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-23-54]]

^<<v42-23-54,54>>^ Era o dia da Preparação, e o sábado estava prestes a começar.

[[v42-23-55]]

^<<v42-23-55,55>>^ No entanto, as mulheres que tinham vindo com ele desde a Galileia foram também até lá e viram o túmulo^&#42;1^ e como o corpo dele tinha sido colocado ali;

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-23-56]]

^<<v42-23-56,56>>^ e voltaram para preparar aromas e óleos perfumados. Contudo, naturalmente, descansaram no sábado, segundo o mandamento.

'''

xref:042-lucas/042-lucas-022.adoc#v42-22-0[&#60; Capítulo Anterior] | <<v42-23-0,Topo>> | xref:042-lucas/042-lucas-024.adoc#v42-24-0[Próximo Capítulo &#62;]