include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-9-1]]

^<<v42-9-1,1>>^ Então, ele convocou os Doze e deu-lhes poder e autoridade sobre todos os demónios, e também para curar doenças.

[[v42-9-2]]

^<<v42-9-2,2>>^ E enviou-os para pregar o Reino de Deus e para curar,

[[v42-9-3]]

^<<v42-9-3,3>>^ e disse-lhes: “Não levem nada para a viagem: nem bastão, nem alforge,^&#42;1^ nem pão, nem dinheiro;^&#42;2^ nem tenham roupa extra.^&#42;3^

[NOTE]
====
. Ou: “bolsa de alimentos”.
. Lit.: “prata”.
. Lit.: “duas túnicas”.
====

[[v42-9-4]]

^<<v42-9-4,4>>^ Mas, em qualquer casa em que entrarem, fiquem lá até partirem.

[[v42-9-5]]

^<<v42-9-5,5>>^ E onde quer que não vos recebam, ao saírem daquela cidade, sacudam o pó dos vossos pés em testemunho contra eles.”

[[v42-9-6]]

^<<v42-9-6,6>>^ Então, eles partiram e percorreram o território, de aldeia em aldeia, declarando as boas novas e realizando curas em toda a parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ E Herodes,^&#42;1^ o governador distrital,^&#42;2^ ouviu falar de tudo o que estava a acontecer e ficou muito perplexo, porque alguns diziam que João tinha sido levantado dentre os mortos,

[NOTE]
====
. Isto é, Herodes Antipas. Veja o Glossário.
. Lit.: “o tetrarca”.
====

[[v42-9-8]]

^<<v42-9-8,8>>^ mas outros diziam que Elias tinha aparecido, e ainda outros que um dos antigos profetas se tinha levantado.

[[v42-9-9]]

^<<v42-9-9,9>>^ Herodes disse: “Eu decapitei João. Então, quem é este de quem ouço dizer estas coisas?” Por conseguinte, procurava vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ Quando voltaram, os apóstolos contaram a Jesus tudo o que tinham feito. A seguir, levando-os consigo, ele retirou-se para uma cidade chamada Betsaida, a fim de ficarem sozinhos.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões, ao saberem disso, seguiram-no. E ele recebeu-as bondosamente, e começou a falar-lhes do Reino de Deus, e curou os que precisavam de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ Chegando o fim do dia, os Doze aproximaram-se dele e disseram-lhe: “Dispensa a multidão, para que possam ir às aldeias e à zona rural ao redor, a fim de conseguirem hospedagem e algo para comer, porque, aqui, estamos num lugar isolado.”

[[v42-9-13]]

^<<v42-9-13,13>>^ Mas ele disse-lhes: “Deem-lhes vocês algo para comer.” Eles disseram: “Não temos nada mais do que cinco pães e dois peixes, a menos que, talvez, nós mesmos vamos e compremos comida para todas estas pessoas.”

[[v42-9-14]]

^<<v42-9-14,14>>^ De facto, havia ali cerca de 5000 homens. Mas ele disse aos discípulos: “Mandem-nos sentar-se em grupos de cerca de 50 pessoas.”

[[v42-9-15]]

^<<v42-9-15,15>>^ E eles fizeram-no e mandaram que todos se sentassem.

[[v42-9-16]]

^<<v42-9-16,16>>^ Pegando então nos cinco pães e nos dois peixes, ele olhou para o céu e deu graças.^&#42;1^ Depois, partiu-os e começou a dá-los aos discípulos, para que os servissem à multidão.

[NOTE]
====
. Ou: “e abençoou-os”.
====

[[v42-9-17]]

^<<v42-9-17,17>>^ Assim, todos comeram e ficaram satisfeitos; e eles recolheram os pedaços que sobraram, 12 cestos.

[[v42-9-18]]

^<<v42-9-18,18>>^ Mais tarde, enquanto estava a orar sozinho, os discípulos aproximaram-se dele, e ele perguntou-lhes: “Quem dizem as multidões que eu sou?”

[[v42-9-19]]

^<<v42-9-19,19>>^ Em resposta, eles disseram: “João Batista; mas outros dizem que és Elias; e ainda outros dizem que um dos antigos profetas se levantou.”

[[v42-9-20]]

^<<v42-9-20,20>>^ Então, ele perguntou-lhes: “E vocês, quem dizem que eu sou?” Pedro respondeu: “O Cristo de Deus.”

[[v42-9-21]]

^<<v42-9-21,21>>^ Depois, numa conversa séria com eles, ordenou-lhes que não contassem isso a ninguém,

[[v42-9-22]]

^<<v42-9-22,22>>^ mas disse: “O Filho do Homem tem de sofrer muitas coisas e ser rejeitado pelos anciãos, pelos principais sacerdotes e pelos escribas, e tem de ser morto e, no terceiro dia, ser levantado.”

[[v42-9-23]]

^<<v42-9-23,23>>^ Então, ele também disse a todos: “Se alguém quer ser meu seguidor, negue-se a si mesmo, apanhe a sua estaca de tortura,^&#42;1^ dia após dia, e siga-me sempre.

[NOTE]
====
. Veja o Glossário.
====

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem quiser salvar a sua vida^&#42;1^ vai perdê-la; mas quem perder a sua vida^&#42;2^ por minha causa é quem a salvará.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v42-9-25]]

^<<v42-9-25,25>>^ Realmente, de que adianta a um homem ganhar o mundo inteiro, se ele perder a sua vida ou causar a sua própria ruína?

[[v42-9-26]]

^<<v42-9-26,26>>^ Pois quem se envergonhar de mim e das minhas palavras, dessa pessoa o Filho do Homem também se envergonhará quando vier na sua glória e na glória do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Mas eu digo-vos a verdade: Há alguns dos que estão aqui que de modo algum provarão a morte antes de verem o Reino de Deus.”

[[v42-9-28]]

^<<v42-9-28,28>>^ Na realidade, cerca de oito dias depois de dizer estas palavras, ele levou consigo Pedro, João e Tiago, e subiu ao monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ E, enquanto orava, a aparência do seu rosto mudou e a sua roupa tornou-se de um branco cintilante.

[[v42-9-30]]

^<<v42-9-30,30>>^ E apareceram dois homens a conversar com ele: eram Moisés e Elias.

[[v42-9-31]]

^<<v42-9-31,31>>^ Estes apareceram com glória e começaram a falar sobre a partida dele, que ele estava prestes a cumprir em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e os que estavam com ele tinham sido vencidos pelo sono, mas, quando despertaram completamente, viram a glória dele e os dois homens de pé com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ E, enquanto esses se afastavam dele, Pedro disse a Jesus: “Instrutor, é bom estarmos aqui. Vamos armar, então, três tendas: uma para ti, uma para Moisés e uma para Elias.” Ele não se apercebia do que estava a dizer.

[[v42-9-34]]

^<<v42-9-34,34>>^ Mas, enquanto o dizia, formou-se uma nuvem e começou a cobri-los. Quando a nuvem os envolveu, ficaram com medo.

[[v42-9-35]]

^<<v42-9-35,35>>^ Então, uma voz saiu da nuvem, dizendo: “Este é o meu Filho, aquele que foi escolhido. Escutem-no.”

[[v42-9-36]]

^<<v42-9-36,36>>^ No momento em que a voz se ouviu, Jesus ficou sozinho. Mas eles ficaram calados e não contaram a ninguém, naqueles dias, nenhuma das coisas que viram.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, quando desceram do monte, uma grande multidão foi ao encontro dele.

[[v42-9-38]]

^<<v42-9-38,38>>^ E um homem gritou dentre a multidão: “Instrutor, imploro-lhe que veja o meu filho, porque ele é o meu único filho.

[[v42-9-39]]

^<<v42-9-39,39>>^ Há um espírito que vem e se apodera dele, e, de repente, ele grita, e o espírito lança-o em convulsões e ele espuma pela boca; só com dificuldade é que o espírito o deixa, depois de o magoar.

[[v42-9-40]]

^<<v42-9-40,40>>^ Supliquei aos seus discípulos que expulsassem o espírito, mas eles não conseguiram.”

[[v42-9-41]]

^<<v42-9-41,41>>^ Em resposta, Jesus disse: “Ó geração sem fé e pervertida, até quando é que terei de continuar convosco e de vos suportar? Traz-me cá o teu filho.”

[[v42-9-42]]

^<<v42-9-42,42>>^ E, enquanto o menino se aproximava, o demónio lançou-o no chão e causou-lhe violentas convulsões. Mas Jesus censurou o espírito impuro e curou o menino, e entregou-o ao pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos ficaram assombrados com o poder majestoso de Deus.
Enquanto todos se maravilhavam com tudo o que fazia, ele disse aos discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ “Ouçam atentamente e lembrem-se destas palavras: O Filho do Homem será entregue^&#42;1^ às mãos dos homens.”

[NOTE]
====
. Ou: “traído”.
====

[[v42-9-45]]

^<<v42-9-45,45>>^ Mas não entenderam o que ele dizia. De facto, isso foi-lhes escondido para que não compreendessem, e tinham medo de lhe perguntar sobre esta declaração.

[[v42-9-46]]

^<<v42-9-46,46>>^ Então, surgiu entre eles uma discussão sobre qual deles era o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Jesus, conhecendo os raciocínios do coração deles, pegou numa criança, colocou-a ao seu lado

[[v42-9-48]]

^<<v42-9-48,48>>^ e disse-lhes: “Quem recebe esta criancinha em meu nome recebe-me também a mim; e quem me recebe, recebe também Aquele que me enviou. Pois quem se comporta como menor entre todos vocês, esse é que é grande.”

[[v42-9-49]]

^<<v42-9-49,49>>^ Em resposta, João disse: “Instrutor, vimos alguém a expulsar demónios em teu nome e tentámos impedi-lo, porque ele não te segue connosco.”

[[v42-9-50]]

^<<v42-9-50,50>>^ Mas Jesus disse-lhe: “Não o tentem impedir, pois quem não é contra vocês é a vosso favor.”

[[v42-9-51]]

^<<v42-9-51,51>>^ Aproximando-se^&#42;1^ o tempo de ser levado para cima, ele partiu resolutamente^&#42;2^ para Jerusalém.

[NOTE]
====
. Lit.: “Completando-se”.
. Lit.: “fixou a sua face”.
====

[[v42-9-52]]

^<<v42-9-52,52>>^ E enviou mensageiros à sua frente, que foram e entraram numa aldeia de samaritanos, para fazer os preparativos para ele.

[[v42-9-53]]

^<<v42-9-53,53>>^ Mas os samaritanos não o receberam, porque ele estava determinado a ir^&#42;1^ para Jerusalém.

[NOTE]
====
. Lit.: “a sua face estava direcionada”.
====

[[v42-9-54]]

^<<v42-9-54,54>>^ Quando os discípulos Tiago e João viram isto, disseram: “Senhor, queres que mandemos que desça fogo do céu e os destrua?”

[[v42-9-55]]

^<<v42-9-55,55>>^ Ele, porém, virou-se e censurou-os.

[[v42-9-56]]

^<<v42-9-56,56>>^ Assim, foram para outra aldeia.

[[v42-9-57]]

^<<v42-9-57,57>>^ Enquanto caminhavam pela estrada, alguém lhe disse: “Eu vou segui-lo para onde quer que vá.”

[[v42-9-58]]

^<<v42-9-58,58>>^ Porém, Jesus disse-lhe: “As raposas têm tocas e as aves do céu têm ninhos, mas o Filho do Homem não tem onde deitar a cabeça.”

[[v42-9-59]]

^<<v42-9-59,59>>^ Então, ele disse a outro: “Sê meu seguidor.” O homem disse: “Senhor, permita-me ir primeiro enterrar o meu pai.”

[[v42-9-60]]

^<<v42-9-60,60>>^ No entanto, ele disse-lhe: “Deixa que os mortos enterrem os seus mortos, mas tu, vai e divulga o Reino de Deus.”

[[v42-9-61]]

^<<v42-9-61,61>>^ E ainda outro disse: “Eu vou segui-lo, Senhor, mas permita-me primeiro despedir-me da minha família.”

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus disse-lhe: “Ninguém que tenha posto a mão num arado e olhe para trás está apto para o Reino de Deus.”

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]