include::./index.adoc[]

[[v42-13-0]]
=== Lucas, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-13-1]]

^<<v42-13-1,1>>^ Naquela ocasião, alguns dos que estavam presentes falaram-lhe sobre os galileus cujo sangue Pilatos tinha misturado com os sacrifícios deles.

[[v42-13-2]]

^<<v42-13-2,2>>^ Ele disse-lhes em resposta: “Acham que esses galileus eram mais pecadores do que todos os outros galileus, porque sofreram estas coisas?

[[v42-13-3]]

^<<v42-13-3,3>>^ Digo-vos que não; mas, a menos que se arrependam, todos vocês serão destruídos do mesmo modo.

[[v42-13-4]]

^<<v42-13-4,4>>^ Ou aqueles 18 sobre os quais caiu a torre de Siloé, matando-os — acham que eles eram mais culpados do que todos os outros homens que moram em Jerusalém?

[[v42-13-5]]

^<<v42-13-5,5>>^ Digo-vos que não; mas, a menos que se arrependam, todos vocês serão destruídos, tal como eles foram.”

[[v42-13-6]]

^<<v42-13-6,6>>^ Então, contou a seguinte ilustração: “Um homem tinha uma figueira plantada na sua vinha e foi ver se ela tinha frutos, mas não encontrou nenhum.

[[v42-13-7]]

^<<v42-13-7,7>>^ Ele disse então ao homem que cuidava da vinha: ‘Há já três anos que venho ver se há frutos nesta figueira, mas não encontrei nenhum. Corta-a! Porque devia ela ocupar inutilmente o solo?’

[[v42-13-8]]

^<<v42-13-8,8>>^ Em resposta, o homem disse-lhe: ‘Senhor, deixe-a por mais um ano. Eu vou cavar à volta dela e pôr estrume;

[[v42-13-9]]

^<<v42-13-9,9>>^ se, no futuro, ela produzir frutos, muito bem, mas, senão, pode cortá-la.’”

[[v42-13-10]]

^<<v42-13-10,10>>^ Ele estava a ensinar numa das sinagogas, no sábado.

[[v42-13-11]]

^<<v42-13-11,11>>^ E estava lá uma mulher que tinha um espírito de fraqueza^&#42;1^ há 18 anos; ela estava encurvada e não se conseguia endireitar de maneira nenhuma.

[NOTE]
====
. Ou: “um espírito incapacitante”.
====

[[v42-13-12]]

^<<v42-13-12,12>>^ Quando a viu, Jesus dirigiu-lhe a palavra, dizendo: “Mulher, estás livre da tua fraqueza.”

[[v42-13-13]]

^<<v42-13-13,13>>^ E ele pôs as mãos sobre ela, e ela endireitou-se instantaneamente e começou a glorificar a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ Em vista disso, porém, o presidente da sinagoga, indignado porque Jesus tinha feito a cura no sábado, disse à multidão: “Há seis dias em que se deve trabalhar; portanto, venham nesses dias e sejam curados, e não no dia de sábado.”

[[v42-13-15]]

^<<v42-13-15,15>>^ O Senhor, porém, respondeu-lhe: “Hipócritas! Cada um de vocês, no sábado, não desprende o seu touro ou o seu jumento e não o leva para beber água?

[[v42-13-16]]

^<<v42-13-16,16>>^ Não deveria esta mulher, que é filha de Abraão e a quem Satanás manteve presa durante 18 anos, ser libertada desta prisão no dia de sábado?”

[[v42-13-17]]

^<<v42-13-17,17>>^ Quando ele disse isto, todos os seus opositores ficaram envergonhados, mas toda a multidão se alegrava com todas as coisas gloriosas que ele fazia.

[[v42-13-18]]

^<<v42-13-18,18>>^ Assim, ele acrescentou: “A que se assemelha o Reino de Deus, e a que posso compará-lo?

[[v42-13-19]]

^<<v42-13-19,19>>^ Ele é semelhante a um grão de mostarda em que um homem pegou e lançou na sua horta; o grão cresceu e tornou-se uma árvore, e as aves do céu fizeram ninhos nos seus ramos.”

[[v42-13-20]]

^<<v42-13-20,20>>^ E, novamente, ele disse: “A que posso comparar o Reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ Ele é semelhante ao fermento em que uma mulher pegou e misturou com três grandes medidas^&#42;1^ de farinha, até que toda a massa ficou fermentada.”

[NOTE]
====
. Lit.: “três seás”. Um seá equivalia a 7,33 l. Veja o Ap. B14.
====

[[v42-13-22]]

^<<v42-13-22,22>>^ E ele viajava de cidade em cidade e de aldeia em aldeia, ensinando e caminhando para Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ Então, um homem disse-lhe: “Senhor, são poucos os que estão a ser salvos?” Ele disse-lhes:

[[v42-13-24]]

^<<v42-13-24,24>>^ “Esforcem-se vigorosamente para entrar pela porta estreita, pois digo-vos que muitos tentarão entrar, mas não poderão.

[[v42-13-25]]

^<<v42-13-25,25>>^ Quando o dono da casa se tiver levantado e trancado a porta, vocês ficarão do lado de fora, a bater à porta e a dizer: ‘Senhor, abra-nos’; mas ele irá responder-vos: ‘Não sei de onde são.’

[[v42-13-26]]

^<<v42-13-26,26>>^ Então, vocês começarão a dizer: ‘Comemos e bebemos na sua presença, e o senhor ensinou-nos nas nossas ruas principais.’

[[v42-13-27]]

^<<v42-13-27,27>>^ Mas ele irá dizer-vos: ‘Não sei de onde são. Afastem-se de mim, todos vocês que fazem o que é injusto!’

[[v42-13-28]]

^<<v42-13-28,28>>^ É lá que ocorrerá o vosso choro e o ranger dos vossos dentes, quando virem Abraão, Isaque, Jacó e todos os profetas no Reino de Deus, mas vocês mesmos lançados fora.

[[v42-13-29]]

^<<v42-13-29,29>>^ Além disso, virão pessoas do leste e do oeste, do norte e do sul, e hão de se recostar à mesa no Reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ Escutem: Há últimos que serão primeiros, e há primeiros que serão últimos.”

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquele preciso momento, alguns fariseus aproximaram-se e disseram-lhe: “Sai e vai-te embora daqui, porque Herodes quer matar-te.”

[[v42-13-32]]

^<<v42-13-32,32>>^ E ele disse-lhes: “Vão dizer àquela raposa: ‘Olha, estou a expulsar demónios e a curar pessoas, hoje e amanhã, e, no terceiro dia, terei terminado.’

[[v42-13-33]]

^<<v42-13-33,33>>^ Contudo, tenho de continuar hoje, amanhã e no dia seguinte, porque é inadmissível^&#42;1^ que um profeta seja morto fora de Jerusalém.

[NOTE]
====
. Ou: “inconcebível”.
====

[[v42-13-34]]

^<<v42-13-34,34>>^ Jerusalém, Jerusalém, que mata os profetas e apedreja os que lhe são enviados . . . Quantas vezes eu quis juntar os teus filhos, assim como a galinha junta a sua ninhada de pintainhos debaixo das asas! Mas vocês não quiseram.

[[v42-13-35]]

^<<v42-13-35,35>>^ Agora, a vossa casa ficará abandonada. Digo-vos: De modo algum me verão, até que digam: ‘Bendito é aquele que vem em nome de Jeová!’”^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]