include::./index.adoc[]

[[v20-6-0]]
=== Provérbios, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v20-6-1]]

^<<v20-6-1,1>>^ Meu filho, se te tornaste fiador do^&#42;1^ teu próximo,
Se apertaste a mão^&#42;2^ a um estranho,

[NOTE]
====
. Ou: “prestaste fiança ao”.
. Isto é, assumindo um compromisso.
====

[[v20-6-2]]

^<<v20-6-2,2>>^ Se foste enlaçado pela tua própria promessa,
Se foste apanhado pelas palavras da tua própria boca,

[[v20-6-3]]

^<<v20-6-3,3>>^ Meu filho, faz o seguinte para te livrares,
Pois caíste nas mãos do teu próximo:
Vai humilhar-te e suplica imediatamente ao teu próximo.

[[v20-6-4]]

^<<v20-6-4,4>>^ Não feches os olhos para dormir,
Nem deixes as tuas pálpebras descansar.

[[v20-6-5]]

^<<v20-6-5,5>>^ Livra-te como a gazela se livra das mãos do caçador,
Como o pássaro das mãos do passarinheiro.

[[v20-6-6]]

^<<v20-6-6,6>>^ Aprende com a formiga, preguiçoso;
Observa os seus caminhos e torna-te sábio.

[[v20-6-7]]

^<<v20-6-7,7>>^ Embora não tenha comandante, chefe ou governante,

[[v20-6-8]]

^<<v20-6-8,8>>^ Prepara as suas provisões no verão;
Recolhe o seu alimento durante a colheita.

[[v20-6-9]]

^<<v20-6-9,9>>^ Até quando vais ficar aí deitado, preguiçoso?
Quando é que te levantarás do teu sono?

[[v20-6-10]]

^<<v20-6-10,10>>^ Um pouco de sono, um pouco de cochilo,
Um pouco de cruzar os braços para descansar,

[[v20-6-11]]

^<<v20-6-11,11>>^ E a tua pobreza chegará como um ladrão,
E a tua carência como um homem armado.

[[v20-6-12]]

^<<v20-6-12,12>>^ O homem que é mau e imprestável anda sempre a dizer mentiras;^&#42;1^

[NOTE]
====
. Ou: “palavras perversas”.
====

[[v20-6-13]]

^<<v20-6-13,13>>^ Pisca o olho, faz sinais com o pé e gestos com os dedos.

[[v20-6-14]]

^<<v20-6-14,14>>^ Com um coração perverso,
Está sempre a tramar o mal e a semear discórdias.

[[v20-6-15]]

^<<v20-6-15,15>>^ Por isso, a sua desgraça chegará de repente;
Num instante será arruinado, e não haverá remédio.

[[v20-6-16]]

^<<v20-6-16,16>>^ Há seis coisas que Jeová odeia,
Sim, sete coisas que ele^&#42;1^ detesta:

[NOTE]
====
. Ou: “a sua alma”.
====

[[v20-6-17]]

^<<v20-6-17,17>>^ Olhos arrogantes, língua mentirosa, mãos que derramam sangue inocente,

[[v20-6-18]]

^<<v20-6-18,18>>^ O coração que planeia tramas perversas, pés que correm rapidamente para a maldade,

[[v20-6-19]]

^<<v20-6-19,19>>^ A testemunha falsa que só diz mentiras
E todo aquele que semeia discórdias entre irmãos.

[[v20-6-20]]

^<<v20-6-20,20>>^ Meu filho, obedece ao mandamento do teu pai
E não abandones a instrução^&#42;1^ da tua mãe.

[NOTE]
====
. Ou: “lei”.
====

[[v20-6-21]]

^<<v20-6-21,21>>^ Ata-os sempre ao coração;
Coloca-os à volta do pescoço.

[[v20-6-22]]

^<<v20-6-22,22>>^ Quando andares, irão guiar-te;
Quando te deitares, irão vigiar-te;
E, quando acordares, falarão contigo.^&#42;1^

[NOTE]
====
. Ou: “irão instruir-te”.
====

[[v20-6-23]]

^<<v20-6-23,23>>^ Pois o mandamento é uma lâmpada,
E a lei é uma luz,
E as repreensões da disciplina são o caminho para a vida.

[[v20-6-24]]

^<<v20-6-24,24>>^ Irão proteger-te da mulher má,
Da língua sedutora da mulher imoral.^&#42;1^

[NOTE]
====
. Lit.: “estrangeira”. Veja Provérbios 2:16.
====

[[v20-6-25]]

^<<v20-6-25,25>>^ Não desejes no coração a sua beleza,
Nem te deixes seduzir pelos seus olhos provocantes,

[[v20-6-26]]

^<<v20-6-26,26>>^ Pois a prostituta deixa o homem reduzido a um pedaço de pão,
Ao passo que a adúltera^&#42;1^ caça uma vida^&#42;2^ preciosa.

[NOTE]
====
. Ou: “a esposa de outro homem”.
. Ou: “alma”.
====

[[v20-6-27]]

^<<v20-6-27,27>>^ Será que um homem pode juntar brasas no seu peito sem queimar a roupa?

[[v20-6-28]]

^<<v20-6-28,28>>^ Será que alguém pode andar sobre brasas sem queimar os pés?

[[v20-6-29]]

^<<v20-6-29,29>>^ O mesmo acontece com aquele que tem relações com a esposa do seu próximo;
Ninguém que tocar nela ficará impune.

[[v20-6-30]]

^<<v20-6-30,30>>^ As pessoas não tratam o ladrão com desprezo
Se ele rouba para se saciar^&#42;1^ quando está com fome.

[NOTE]
====
. Ou: “encher a sua alma”.
====

[[v20-6-31]]

^<<v20-6-31,31>>^ Mesmo assim, quando descoberto, devolverá sete vezes mais;
Entregará todas as coisas valiosas da sua casa.

[[v20-6-32]]

^<<v20-6-32,32>>^ Quem comete adultério com uma mulher não tem bom senso;^&#42;1^
Aquele que o faz arruína-se a si mesmo.^&#42;2^

[NOTE]
====
. Lit.: “não tem coração”.
. Ou: “arruína a sua alma”.
====

[[v20-6-33]]

^<<v20-6-33,33>>^ Só encontrará ferimentos e desonra;
A sua humilhação nunca se apagará.

[[v20-6-34]]

^<<v20-6-34,34>>^ Pois o ciúme deixa o marido furioso;
Ele não terá compaixão quando se vingar.

[[v20-6-35]]

^<<v20-6-35,35>>^ Não aceitará nenhuma compensação;^&#42;1^
Não se conformará, por mais valioso que seja o presente que ofereceres.

[NOTE]
====
. Ou: “nenhum resgate”.
====

'''

xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[&#60; Capítulo Anterior] | <<v20-6-0,Topo>> | xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[Próximo Capítulo &#62;]