include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v20-24-1]]

^<<v20-24-1,1>>^ Não invejes os maus,
Nem desejes a sua companhia,

[[v20-24-2]]

^<<v20-24-2,2>>^ Pois o seu coração trama^&#42;1^ violência,
E os seus lábios falam de coisas más.

[NOTE]
====
. Ou: “medita em”.
====

[[v20-24-3]]

^<<v20-24-3,3>>^ Pela sabedoria edifica-se uma casa,^&#42;1^
E pelo discernimento ela é firmada.

[NOTE]
====
. Ou: “os da casa”.
====

[[v20-24-4]]

^<<v20-24-4,4>>^ Pelo conhecimento os seus aposentos ficam cheios
De todo o tipo de tesouros preciosos e agradáveis.

[[v20-24-5]]

^<<v20-24-5,5>>^ O homem sábio é forte,
E com o conhecimento o homem aumenta a sua força.

[[v20-24-6]]

^<<v20-24-6,6>>^ É com orientação perita^&#42;1^ que travarás a tua guerra,
E com muitos conselheiros há vitória.^&#42;2^

[NOTE]
====
. Ou: “sábia”.
. Ou: “sucesso; salvação”.
====

[[v20-24-7]]

^<<v20-24-7,7>>^ A verdadeira sabedoria é inalcançável para o tolo;
Ele não tem nada a dizer no portão da cidade.

[[v20-24-8]]

^<<v20-24-8,8>>^ Quem trama o mal
Será chamado mestre de intrigas.

[[v20-24-9]]

^<<v20-24-9,9>>^ Tramas tolas^&#42;1^ são pecado,
E as pessoas detestam o ridicularizador.

[NOTE]
====
. Ou: “As tramas do tolo”.
====

[[v20-24-10]]

^<<v20-24-10,10>>^ Se ficares desanimado no dia da aflição,^&#42;1^
A tua força será escassa.

[NOTE]
====
. Ou: “em tempos de aflição”.
====

[[v20-24-11]]

^<<v20-24-11,11>>^ Livra os que estão a ser levados para a morte;
Salva os que estão a cambalear para a matança.

[[v20-24-12]]

^<<v20-24-12,12>>^ Se disseres: “Mas não sabíamos de nada”,
Será que Aquele que examina os corações^&#42;1^ não o discernirá?
Sim, Aquele que te observa^&#42;2^ saberá
E retribuirá a cada homem segundo as suas ações.

[NOTE]
====
. Ou: “as motivações”.
. Ou: “que observa a tua alma”.
====

[[v20-24-13]]

^<<v20-24-13,13>>^ Meu filho, come mel, porque é bom;
O mel dos favos é doce para o paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Da mesma maneira, fica a saber que a sabedoria é boa para ti.^&#42;1^
Se a encontrares, terás um bom futuro,
E a tua esperança não te será tirada.^&#42;2^

[NOTE]
====
. Ou: “é doce para a tua alma”.
. Ou: “decepada”.
====

[[v20-24-15]]

^<<v20-24-15,15>>^ Não te ponhas de emboscada, como um homem perverso, perto da casa do justo;
Não destruas o seu lugar de descanso.

[[v20-24-16]]

^<<v20-24-16,16>>^ Pois, mesmo que o justo caia sete vezes, irá levantar-se outra vez;
Mas os maus tropeçarão por causa da calamidade.

[[v20-24-17]]

^<<v20-24-17,17>>^ Quando o teu inimigo cair, não te alegres;
E, quando tropeçar, não deixes o teu coração exultar-se;

[[v20-24-18]]

^<<v20-24-18,18>>^ Caso contrário, Jeová verá isso e não ficará satisfeito,
E fará a sua ira recuar dele.^&#42;1^

[NOTE]
====
. Isto é, do inimigo.
====

[[v20-24-19]]

^<<v20-24-19,19>>^ Não fiques aborrecido^&#42;1^ por causa dos malfeitores;
Não invejes os maus.

[NOTE]
====
. Ou: “Não te mostres acalorado”.
====

[[v20-24-20]]

^<<v20-24-20,20>>^ Pois não há futuro para os malfeitores;
A lâmpada dos maus será apagada.

[[v20-24-21]]

^<<v20-24-21,21>>^ Meu filho, teme a Jeová e ao rei,
E não te envolvas com dissidentes,^&#42;1^

[NOTE]
====
. Ou: “os que estão a favor de uma mudança”.
====

[[v20-24-22]]

^<<v20-24-22,22>>^ Pois o seu desastre ocorrerá repentinamente.
Quem sabe que ruína é que os dois^&#42;1^ trarão sobre eles?

[NOTE]
====
. Isto é, Jeová e o rei.
====

[[v20-24-23]]

^<<v20-24-23,23>>^ Estas declarações também são dos sábios:
Não é bom mostrar parcialidade no julgamento.

[[v20-24-24]]

^<<v20-24-24,24>>^ Quem disser àquele que é mau: “Tu és justo”,
Será amaldiçoado pelos povos e condenado pelas nações.

[[v20-24-25]]

^<<v20-24-25,25>>^ Mas, os que o repreendem irão sair-se bem
E serão abençoados com coisas boas.

[[v20-24-26]]

^<<v20-24-26,26>>^ As pessoas beijarão os lábios daquele que dá uma resposta sincera.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Responder de forma direta é como dar um beijo.”
====

[[v20-24-27]]

^<<v20-24-27,27>>^ Prepara o teu trabalho lá fora e deixa tudo pronto no campo;
Depois constrói a tua casa.^&#42;1^

[NOTE]
====
. Ou: “estabelece a tua família”.
====

[[v20-24-28]]

^<<v20-24-28,28>>^ Não testemunhes contra o teu próximo se não tiveres base para isso,
Não uses os teus lábios para enganar outros.

[[v20-24-29]]

^<<v20-24-29,29>>^ Não digas: “Vou fazer-lhe o mesmo que ele me fez;
Vou retribuir-lhe pelo que ele fez.”^&#42;1^

[NOTE]
====
. Ou: “Vou vingar-me dele”.
====

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei pelo campo do preguiçoso,
Pela vinha do homem que não tem bom senso.^&#42;1^

[NOTE]
====
. Lit.: “não tem coração”.
====

[[v20-24-31]]

^<<v20-24-31,31>>^ Vi que estava cheio de ervas daninhas;
O solo estava coberto de urtigas,
E o seu muro de pedras estava em ruínas.

[[v20-24-32]]

^<<v20-24-32,32>>^ Observei isto e pensei;
Vi e aprendi a seguinte lição:^&#42;1^

[NOTE]
====
. Lit.: “aceitei a disciplina”.
====

[[v20-24-33]]

^<<v20-24-33,33>>^ Um pouco de sono, um pouco de cochilo,
Um pouco de cruzar os braços para descansar,

[[v20-24-34]]

^<<v20-24-34,34>>^ E a tua pobreza chegará como um ladrão,
E a tua carência como um homem armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]