include::./index.adoc[]

[[v20-5-0]]
=== Provérbios, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v20-5-1]]

^<<v20-5-1,1>>^ Meu filho, presta atenção à minha sabedoria.
Escuta atentamente o^&#42;1^ meu discernimento,

[NOTE]
====
. Ou: “Inclina o teu ouvido ao”.
====

[[v20-5-2]]

^<<v20-5-2,2>>^ Para que protejas o teu raciocínio
E resguardes o conhecimento com os teus lábios.

[[v20-5-3]]

^<<v20-5-3,3>>^ Pois os lábios da mulher imoral^&#42;1^ gotejam como um favo de mel,
E a sua boca é mais suave do que o azeite.

[NOTE]
====
. Lit.: “estranha”. Veja Provérbios 2:16.
====

[[v20-5-4]]

^<<v20-5-4,4>>^ Mas, no fim, ela é tão amarga como o absinto
E tão afiada como uma espada de dois gumes.

[[v20-5-5]]

^<<v20-5-5,5>>^ Os seus pés descem para a morte.
Os seus passos levam diretamente à Sepultura.^&#42;1^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v20-5-6]]

^<<v20-5-6,6>>^ Ela não dá atenção ao caminho da vida.
Anda sem rumo, sem saber para onde vai.

[[v20-5-7]]

^<<v20-5-7,7>>^ Agora, meus filhos, escutem-me,
E não se desviem do que eu digo.

[[v20-5-8]]

^<<v20-5-8,8>>^ Fica longe dela;
Não te aproximes da entrada da sua casa,

[[v20-5-9]]

^<<v20-5-9,9>>^ Para que não dês a tua dignidade a outros,
Nem tenhas anos de sofrimento;^&#42;1^

[NOTE]
====
. Lit.: “E os teus anos ao que é cruel”.
====

[[v20-5-10]]

^<<v20-5-10,10>>^ Para que os estranhos não esgotem os teus recursos,^&#42;1^
E o fruto do teu trabalho árduo não acabe na casa de um estrangeiro.

[NOTE]
====
. Ou: “o teu poder”.
====

[[v20-5-11]]

^<<v20-5-11,11>>^ Caso contrário, vais gemer no fim da tua vida,
Quando a tua carne e o teu corpo se definharem,

[[v20-5-12]]

^<<v20-5-12,12>>^ E disseres: “Como eu odiei a disciplina!
Como o meu coração desprezou a repreensão!

[[v20-5-13]]

^<<v20-5-13,13>>^ Não escutei a voz dos meus instrutores,
Nem prestei atenção aos meus mestres.

[[v20-5-14]]

^<<v20-5-14,14>>^ Quase caí em completa ruína
À vista de toda a congregação.”^&#42;1^

[NOTE]
====
. Lit.: “No meio da assembleia e da congregação”.
====

[[v20-5-15]]

^<<v20-5-15,15>>^ Bebe a água da tua própria cisterna
E a água que sai^&#42;1^ do teu próprio poço.

[NOTE]
====
. Ou: “água fresca”.
====

[[v20-5-16]]

^<<v20-5-16,16>>^ Deveriam as tuas fontes derramar-se pelas ruas,
As tuas correntes de água nas praças?

[[v20-5-17]]

^<<v20-5-17,17>>^ Que elas sejam só para ti
E não repartidas com estranhos.

[[v20-5-18]]

^<<v20-5-18,18>>^ Seja abençoada a tua própria fonte,
E alegra-te com a esposa da tua juventude,

[[v20-5-19]]

^<<v20-5-19,19>>^ Amável corça, graciosa cabra-montesa.^&#42;1^
Que os seus seios te satisfaçam^&#42;2^ todo o tempo.
Que o seu amor sempre te extasie.

[NOTE]
====
. Também conhecida como íbex.
. Ou: “inebriem”.
====

[[v20-5-20]]

^<<v20-5-20,20>>^ Então, meu filho, por que razão te deixarias extasiar por uma mulher devassa,^&#42;1^
Ou abraçarias o peito de uma mulher imoral?^&#42;2^

[NOTE]
====
. Lit.: “estranha”. Veja Provérbios 2:16.
. Lit.: “estrangeira”. Veja Provérbios 2:16.
====

[[v20-5-21]]

^<<v20-5-21,21>>^ Pois os caminhos do homem estão diante dos olhos de Jeová;
Ele examina todas as suas veredas.

[[v20-5-22]]

^<<v20-5-22,22>>^ Quem é mau é enlaçado pelos seus próprios erros,
E será apanhado nas cordas do seu próprio pecado.

[[v20-5-23]]

^<<v20-5-23,23>>^ Morrerá por falta de disciplina
E irá perder-se na sua imensa tolice.

'''

xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[&#60; Capítulo Anterior] | <<v20-5-0,Topo>> | xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[Próximo Capítulo &#62;]