include::./index.adoc[]

[[v40-5-0]]
=== Mateus, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-5-1]]

^<<v40-5-1,1>>^ Quando ele viu as multidões, subiu ao monte e, depois de se sentar, os seus discípulos aproximaram-se dele.

[[v40-5-2]]

^<<v40-5-2,2>>^ Ele abriu então a boca e começou a ensiná-los, dizendo:

[[v40-5-3]]

^<<v40-5-3,3>>^ “Felizes os que têm consciência da sua necessidade espiritual,^&#42;1^ porque a eles pertence o Reino dos céus.

[NOTE]
====
. Ou: “os que mendigam o espírito”.
====

[[v40-5-4]]

^<<v40-5-4,4>>^ “Felizes os que choram, porque serão consolados.

[[v40-5-5]]

^<<v40-5-5,5>>^ “Felizes os de temperamento brando,^&#42;1^ porque herdarão a terra.

[NOTE]
====
. Ou: “os mansos”.
====

[[v40-5-6]]

^<<v40-5-6,6>>^ “Felizes os que têm fome e sede de justiça, porque serão saciados.^&#42;1^

[NOTE]
====
. Ou: “satisfeitos”.
====

[[v40-5-7]]

^<<v40-5-7,7>>^ “Felizes os misericordiosos, porque serão tratados com misericórdia.

[[v40-5-8]]

^<<v40-5-8,8>>^ “Felizes os puros de coração, porque verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ “Felizes os pacificadores,^&#42;1^ porque serão chamados filhos de Deus.

[NOTE]
====
. Ou: “pacíficos”.
====

[[v40-5-10]]

^<<v40-5-10,10>>^ “Felizes os que são perseguidos por causa da justiça, porque a eles pertence o Reino dos céus.

[[v40-5-11]]

^<<v40-5-11,11>>^ “Felizes sejam quando as pessoas vos insultarem e perseguirem, e, mentindo, disserem todo o tipo de coisas más contra vocês, por minha causa.

[[v40-5-12]]

^<<v40-5-12,12>>^ Alegrem-se e fiquem cheios de alegria, porque a vossa recompensa é grande nos céus; pois assim perseguiram os profetas que viveram antes de vocês.

[[v40-5-13]]

^<<v40-5-13,13>>^ “Vocês são o sal da terra. Mas, se o sal perder a sua força, como é que a sua salinidade será restaurada? Já não presta para nada, a não ser para se deitar fora, a fim de ser pisado pelos homens.

[[v40-5-14]]

^<<v40-5-14,14>>^ “Vocês são a luz do mundo. Não se pode esconder uma cidade situada sobre um monte.

[[v40-5-15]]

^<<v40-5-15,15>>^ As pessoas acendem uma lâmpada e colocam-na, não debaixo de um cesto,^&#42;1^ mas em cima de um suporte, e ela brilha sobre todos na casa.

[NOTE]
====
. Ou: “cesto de medida”.
====

[[v40-5-16]]

^<<v40-5-16,16>>^ Do mesmo modo, deixem brilhar a vossa luz perante os homens, para que vejam as vossas boas obras e deem glória ao vosso Pai, que está nos céus.

[[v40-5-17]]

^<<v40-5-17,17>>^ “Não pensem que vim destruir a Lei ou os Profetas. Não vim destruir, mas cumprir.

[[v40-5-18]]

^<<v40-5-18,18>>^ Garanto-vos que será mais fácil que o céu e a terra passem do que passar a menor letra ou um só traço de uma letra da Lei, sem que tudo se cumpra.

[[v40-5-19]]

^<<v40-5-19,19>>^ Portanto, quem violar o menor destes mandamentos e ensinar outros a fazer o mesmo será chamado menor em relação ao Reino dos céus. Contudo, quem os cumprir e ensinar será chamado grande em relação ao Reino dos céus.

[[v40-5-20]]

^<<v40-5-20,20>>^ Pois eu vos digo que, se a vossa justiça não for maior do que a dos escribas e dos fariseus, de modo algum entrarão no Reino dos céus.

[[v40-5-21]]

^<<v40-5-21,21>>^ “Ouviram o que se disse aos dos tempos antigos: ‘Não assassines, e quem cometer um assassinato prestará contas ao tribunal de justiça.’

[[v40-5-22]]

^<<v40-5-22,22>>^ No entanto, digo-vos que todo aquele que continuar furioso com o seu irmão terá de prestar contas ao tribunal de justiça; e quem se dirigir ao seu irmão com uma palavra imprópria de desprezo terá de prestar contas ao Supremo Tribunal; ao passo que quem disser: ‘Tolo imprestável!’ estará sujeito à Geena^&#42;1^ ardente.

[NOTE]
====
. Lugar onde se queimava lixo fora de Jerusalém. Veja o Glossário, “Geena”.
====

[[v40-5-23]]

^<<v40-5-23,23>>^ “Portanto, se levares a tua dádiva ao altar e ali te lembrares de que o teu irmão tem algo contra ti,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixa a tua dádiva em frente ao altar e vai. Faz primeiro as pazes com o teu irmão e, então, volta e oferece a tua dádiva.

[[v40-5-25]]

^<<v40-5-25,25>>^ “Resolve rapidamente as questões com o teu adversário, enquanto estás com ele a caminho do tribunal, para que não aconteça que o teu adversário te entregue ao juiz, e o juiz ao oficial de justiça, e tu sejas mandado para a prisão.

[[v40-5-26]]

^<<v40-5-26,26>>^ Digo-te categoricamente: De modo algum sairás de lá até pagares a tua última pequena moeda.^&#42;1^

[NOTE]
====
. Lit.: “o último quadrante”. Veja o Ap. B14.
====

[[v40-5-27]]

^<<v40-5-27,27>>^ “Ouviram o que se disse: ‘Não cometas adultério.’

[[v40-5-28]]

^<<v40-5-28,28>>^ Mas digo-vos que todo aquele que persiste em olhar para uma mulher, a ponto de sentir paixão por ela, já cometeu no coração adultério com ela.

[[v40-5-29]]

^<<v40-5-29,29>>^ Por isso, se o teu olho direito te faz tropeçar, arranca-o e atira-o para longe de ti, porque é melhor que percas um dos teus membros do que todo o teu corpo ser lançado na Geena.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v40-5-30]]

^<<v40-5-30,30>>^ Também, se a tua mão direita te faz tropeçar, corta-a e atira-a para longe de ti, porque é melhor que percas um dos teus membros do que todo o teu corpo acabar na Geena.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v40-5-31]]

^<<v40-5-31,31>>^ “Além disso, foi dito: ‘Quem se divorcia da sua esposa dê-lhe um certificado de divórcio.’

[[v40-5-32]]

^<<v40-5-32,32>>^ No entanto, digo-vos que todo aquele que se divorcia da sua esposa, a não ser por causa de imoralidade sexual,^&#42;1^ expõe-na ao adultério, e quem se casa com uma mulher divorciada comete adultério.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v40-5-33]]

^<<v40-5-33,33>>^ “Também, ouviram o que se disse aos dos tempos antigos: ‘Não jures sem cumprir, mas cumpre os teus votos feitos a Jeová.’^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v40-5-34]]

^<<v40-5-34,34>>^ No entanto, digo-vos: Não jurem de modo algum, nem pelo céu, pois é o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, pois é o apoio para os seus pés; nem por Jerusalém, pois é a cidade do grande Rei.

[[v40-5-36]]

^<<v40-5-36,36>>^ Não jures pela tua própria cabeça, porque não podes tornar branco ou preto um só fio de cabelo.

[[v40-5-37]]

^<<v40-5-37,37>>^ Deixem simplesmente que a vossa palavra “sim” signifique sim, e o vosso “não”, não; pois tudo o que for além disso é do Maligno.

[[v40-5-38]]

^<<v40-5-38,38>>^ “Ouviram o que se disse: ‘Olho por olho e dente por dente.’

[[v40-5-39]]

^<<v40-5-39,39>>^ No entanto, digo-vos: Não resistam àquele que é mau, mas a quem te der uma bofetada na face direita, oferece também a outra.

[[v40-5-40]]

^<<v40-5-40,40>>^ E, se alguém te quiser levar perante o tribunal para te tirar a túnica, deixa-o ficar também com a tua capa.

[[v40-5-41]]

^<<v40-5-41,41>>^ E, se alguém com autoridade te obrigar a prestar serviço por uma milha,^&#42;1^ vai com ele por duas milhas.

[NOTE]
====
. Veja o Glossário.
====

[[v40-5-42]]

^<<v40-5-42,42>>^ Dá a quem te pedir e não te desvies de quem te deseja pedir emprestado^&#42;1^.

[NOTE]
====
. Isto é, pedir emprestado sem juros.
====

[[v40-5-43]]

^<<v40-5-43,43>>^ “Ouviram o que se disse: ‘Ama o teu próximo e odeia o teu inimigo.’

[[v40-5-44]]

^<<v40-5-44,44>>^ No entanto, digo-vos: Continuem a amar os vossos inimigos e a orar pelos que vos perseguem,

[[v40-5-45]]

^<<v40-5-45,45>>^ para que vocês mostrem ser filhos do vosso Pai, que está nos céus, visto que ele faz o seu sol levantar-se sobre os maus e sobre os bons, e faz chover sobre os justos e sobre os injustos.

[[v40-5-46]]

^<<v40-5-46,46>>^ Pois, se vocês amarem os que vos amam, que recompensa terão? Não fazem a mesma coisa os cobradores de impostos?

[[v40-5-47]]

^<<v40-5-47,47>>^ E, se cumprimentarem somente os vossos irmãos, o que fazem de extraordinário? Não fazem a mesma coisa as pessoas das nações?

[[v40-5-48]]

^<<v40-5-48,48>>^ Portanto, sejam perfeitos,^&#42;1^ assim como o vosso Pai celestial é perfeito.

[NOTE]
====
. Ou: “completos”.
====

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]