include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-8-1]]

^<<v40-8-1,1>>^ Depois de ele ter descido do monte, grandes multidões seguiram-no.

[[v40-8-2]]

^<<v40-8-2,2>>^ Então, aproximou-se um leproso e curvou-se diante dele,^&#42;1^ dizendo: “Senhor, se apenas quiser, pode purificar-me.”

[NOTE]
====
. Ou: “e prestou-lhe homenagem”.
====

[[v40-8-3]]

^<<v40-8-3,3>>^ Assim, ele estendeu a mão e tocou no homem, dizendo: “Eu quero! Sê purificado.” De imediato, ele foi purificado da lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Jesus disse-lhe então: “Tem cuidado para não contares nada a ninguém, mas vai, mostra-te ao sacerdote e oferece a dádiva que Moisés determinou, para que lhes sirva de testemunho.”

[[v40-8-5]]

^<<v40-8-5,5>>^ Quando entrou em Cafarnaum, aproximou-se dele um oficial do exército, suplicando

[[v40-8-6]]

^<<v40-8-6,6>>^ e dizendo-lhe: “Senhor, o meu servo está de cama em casa, com paralisia, e sofre terrivelmente.”

[[v40-8-7]]

^<<v40-8-7,7>>^ Ele disse-lhe: “Quando eu lá chegar, vou curá-lo.”

[[v40-8-8]]

^<<v40-8-8,8>>^ O oficial do exército respondeu: “Senhor, não sou digno de o receber debaixo do meu teto, mas diga apenas a palavra e o meu servo será curado.

[[v40-8-9]]

^<<v40-8-9,9>>^ Pois eu também sou um homem sujeito a autoridade e tenho soldados sob as minhas ordens, e digo a um: ‘Vai!’ e ele vai, e a outro: ‘Vem!’ e ele vem, e ao meu escravo: ‘Faz isto!’ e ele faz.”

[[v40-8-10]]

^<<v40-8-10,10>>^ Quando Jesus ouviu isto, ficou admirado e disse aos que o seguiam: “Digo-vos a verdade: Em Israel, não encontrei ninguém com tamanha fé.

[[v40-8-11]]

^<<v40-8-11,11>>^ Mas digo-vos que muitos virão do leste e do oeste e irão recostar-se à mesa com Abraão, Isaque e Jacó, no Reino dos céus,

[[v40-8-12]]

^<<v40-8-12,12>>^ ao passo que os filhos do Reino serão lançados na escuridão lá fora. É lá que ocorrerá o seu choro e o ranger dos seus dentes.”

[[v40-8-13]]

^<<v40-8-13,13>>^ Jesus disse então ao oficial do exército: “Vai. Que te aconteça segundo a fé que mostraste.” E o servo foi curado naquela hora.

[[v40-8-14]]

^<<v40-8-14,14>>^ Ao entrar na casa de Pedro, Jesus viu a sogra deste de cama e com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ Então, tocou-lhe na mão e a febre deixou-a, e ela levantou-se e começou a servi-lo.

[[v40-8-16]]

^<<v40-8-16,16>>^ Depois de anoitecer, levaram-lhe muitas pessoas possessas; e ele expulsou os espíritos com uma palavra e curou todos os que estavam doentes,

[[v40-8-17]]

^<<v40-8-17,17>>^ para que se cumprissem as palavras de Isaías, o profeta: “Foi ele que levou as nossas doenças e carregou as nossas enfermidades.”

[[v40-8-18]]

^<<v40-8-18,18>>^ Quando Jesus viu uma multidão ao seu redor, ordenou aos discípulos que passassem para a outra margem.

[[v40-8-19]]

^<<v40-8-19,19>>^ E um escriba aproximou-se e disse-lhe: “Instrutor, vou segui-lo para onde quer que vá.”

[[v40-8-20]]

^<<v40-8-20,20>>^ Porém, Jesus disse-lhe: “As raposas têm tocas e as aves do céu têm ninhos, mas o Filho do Homem não tem onde deitar a cabeça.”

[[v40-8-21]]

^<<v40-8-21,21>>^ Então, outro discípulo disse-lhe: “Senhor, permita-me ir primeiro enterrar o meu pai.”

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus disse-lhe: “Continua a seguir-me e deixa que os mortos enterrem os seus mortos.”

[[v40-8-23]]

^<<v40-8-23,23>>^ Ele entrou num barco e os seus discípulos seguiram-no.

[[v40-8-24]]

^<<v40-8-24,24>>^ Levantou-se então uma grande tempestade no mar, de modo que o barco estava a ser coberto pelas ondas; mas ele estava a dormir.

[[v40-8-25]]

^<<v40-8-25,25>>^ E eles foram acordá-lo, dizendo: “Senhor, salva-nos, pois estamos prestes a morrer!”

[[v40-8-26]]

^<<v40-8-26,26>>^ No entanto, ele disse-lhes: “Porque é que estão com tanto medo,^&#42;1^ homens de pouca fé?” Então, levantou-se e censurou os ventos e o mar, e houve uma grande calmaria.

[NOTE]
====
. Ou: “são tão inseguros”.
====

[[v40-8-27]]

^<<v40-8-27,27>>^ Por conseguinte, os homens ficaram espantados e disseram: “Que homem é este? Até mesmo os ventos e o mar lhe obedecem.”

[[v40-8-28]]

^<<v40-8-28,28>>^ Quando chegou à outra margem, à região dos gadarenos, dois homens possessos saíram dentre os túmulos^&#42;1^ e foram ao seu encontro. Eles eram extremamente ferozes, de modo que ninguém tinha coragem de passar por aquela estrada.

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v40-8-29]]

^<<v40-8-29,29>>^ E começaram a gritar: “O que é que queres de nós,^&#42;1^ Filho de Deus? Vieste aqui atormentar-nos antes do tempo determinado?”

[NOTE]
====
. Ou: “O que temos nós a ver contigo”.
====

[[v40-8-30]]

^<<v40-8-30,30>>^ Bem longe dali, havia uma grande vara de porcos a pastar.

[[v40-8-31]]

^<<v40-8-31,31>>^ Assim, os demónios começaram a suplicar, dizendo-lhe: “Se nos expulsares, manda-nos para a vara de porcos.”

[[v40-8-32]]

^<<v40-8-32,32>>^ E ele disse-lhes: “Vão!” Eles saíram então e entraram nos porcos, e todos os porcos se atiraram pelo despenhadeiro^&#42;1^ abaixo, para dentro do mar, e morreram nas águas.

[NOTE]
====
. Ou: “pela encosta íngreme”.
====

[[v40-8-33]]

^<<v40-8-33,33>>^ Os que cuidavam dos porcos fugiram, entraram na cidade e contaram tudo, inclusivamente o que tinha acontecido com os homens possessos.

[[v40-8-34]]

^<<v40-8-34,34>>^ Então, toda a cidade saiu e foi ao encontro de Jesus e, ao vê-lo, suplicaram-lhe que se fosse embora daquela região.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]