include::./index.adoc[]

[[v40-26-0]]
=== Mateus, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-26-1]]

^<<v40-26-1,1>>^ Então, quando Jesus acabou de dizer todas estas coisas, ele disse aos seus discípulos:

[[v40-26-2]]

^<<v40-26-2,2>>^ “Vocês sabem que daqui a dois dias é a Páscoa, e o Filho do Homem será entregue para ser morto na estaca.”

[[v40-26-3]]

^<<v40-26-3,3>>^ Nessa ocasião, os principais sacerdotes e os anciãos do povo reuniram-se no pátio do sumo sacerdote, que se chamava Caifás,

[[v40-26-4]]

^<<v40-26-4,4>>^ e fizeram planos para, com astúcia,^&#42;1^ prender^&#42;2^ Jesus e matá-lo.

[NOTE]
====
. Ou: “por meio de uma trama”.
. Ou: “apanhar”.
====

[[v40-26-5]]

^<<v40-26-5,5>>^ No entanto, diziam: “Não durante a festividade, para que não haja um alvoroço entre o povo.”

[[v40-26-6]]

^<<v40-26-6,6>>^ Enquanto Jesus estava em Betânia, na casa de Simão, o leproso,

[[v40-26-7]]

^<<v40-26-7,7>>^ aproximou-se dele uma mulher com um frasco de alabastro que continha óleo perfumado muito caro, e ela começou a derramá-lo sobre a cabeça dele, enquanto ele comia.^&#42;1^

[NOTE]
====
. Ou: “estava recostado à mesa”.
====

[[v40-26-8]]

^<<v40-26-8,8>>^ Ao verem isso, os discípulos ficaram indignados e disseram: “Porquê este desperdício?

[[v40-26-9]]

^<<v40-26-9,9>>^ Pois isto podia ter sido vendido por uma grande soma, e o dinheiro dado aos pobres.”

[[v40-26-10]]

^<<v40-26-10,10>>^ Percebendo isto, Jesus disse-lhes: “Porque é que estão a perturbar a mulher? Ela fez-me uma coisa muito boa.

[[v40-26-11]]

^<<v40-26-11,11>>^ Porque vocês têm sempre convosco os pobres, mas nem sempre me terão a mim.

[[v40-26-12]]

^<<v40-26-12,12>>^ Quando esta mulher derramou este óleo perfumado sobre o meu corpo, fez isso a fim de me preparar para o sepultamento.

[[v40-26-13]]

^<<v40-26-13,13>>^ Digo-vos a verdade: Onde quer que se preguem as boas novas em todo o mundo, o que esta mulher fez também será relatado, em sua memória.”

[[v40-26-14]]

^<<v40-26-14,14>>^ Então, um dos Doze, o chamado Judas Iscariotes, dirigiu-se aos principais sacerdotes

[[v40-26-15]]

^<<v40-26-15,15>>^ e disse: “O que é que me darão para que eu o entregue^&#42;1^ a vocês?” Estipularam-lhe 30 moedas de prata.

[NOTE]
====
. Ou: “traia”.
====

[[v40-26-16]]

^<<v40-26-16,16>>^ Por isso, daquele momento em diante, ele procurava uma boa oportunidade para traí-lo.

[[v40-26-17]]

^<<v40-26-17,17>>^ No primeiro dia da Festividade dos Pães sem Fermento, os discípulos aproximaram-se de Jesus e perguntaram: “Onde é que queres que façamos os preparativos para a refeição pascoal?”

[[v40-26-18]]

^<<v40-26-18,18>>^ Ele disse: “Vão à cidade, a um certo homem, e digam-lhe: ‘O Instrutor diz: “Está próximo o meu tempo determinado; celebrarei a Páscoa com os meus discípulos na tua casa.”’”

[[v40-26-19]]

^<<v40-26-19,19>>^ Assim, os discípulos fizeram conforme as instruções de Jesus e prepararam a refeição pascoal.

[[v40-26-20]]

^<<v40-26-20,20>>^ Quando anoiteceu, ele estava recostado à mesa com os 12 discípulos.

[[v40-26-21]]

^<<v40-26-21,21>>^ Enquanto comiam, ele disse: “Digo-vos a verdade: Um de vocês vai trair-me.”

[[v40-26-22]]

^<<v40-26-22,22>>^ Eles ficaram muito tristes com isso, e cada um começou a perguntar-lhe: “Senhor, por acaso sou eu?”

[[v40-26-23]]

^<<v40-26-23,23>>^ Em resposta, ele disse: “Aquele que mete a mão na tigela comigo é o que me vai trair.

[[v40-26-24]]

^<<v40-26-24,24>>^ É verdade, o Filho do Homem vai-se embora, assim como está escrito a seu respeito, mas ai daquele que trai o Filho do Homem! Seria melhor para esse homem que não tivesse nascido.”

[[v40-26-25]]

^<<v40-26-25,25>>^ Judas, que estava prestes a traí-lo, perguntou: “Por acaso sou eu, Rabi?” Jesus respondeu-lhe: “Tu mesmo o estás a dizer.”

[[v40-26-26]]

^<<v40-26-26,26>>^ Ao continuarem a comer, Jesus pegou num pão e, depois de proferir uma bênção, partiu-o e deu-o aos discípulos, dizendo: “Tomem, comam. Isto representa o meu corpo.”

[[v40-26-27]]

^<<v40-26-27,27>>^ E, pegando num cálice, deu graças e deu-o aos discípulos, dizendo: “Bebam dele, todos vocês,

[[v40-26-28]]

^<<v40-26-28,28>>^ pois isto representa o meu ‘sangue do pacto’, que será derramado em benefício de muitos, para o perdão de pecados.

[[v40-26-29]]

^<<v40-26-29,29>>^ Digo-vos, porém: De modo algum beberei novamente deste produto da videira até ao dia em que beberei convosco vinho novo, no Reino do meu Pai.”

[[v40-26-30]]

^<<v40-26-30,30>>^ Por fim, depois de cantarem louvores,^&#42;1^ foram para o monte das Oliveiras.

[NOTE]
====
. Ou: “hinos; salmos”.
====

[[v40-26-31]]

^<<v40-26-31,31>>^ Jesus disse-lhes então: “Esta noite, todos vocês tropeçarão em relação a mim, pois está escrito: ‘Ferirei o pastor, e as ovelhas do rebanho serão espalhadas.’

[[v40-26-32]]

^<<v40-26-32,32>>^ Mas, depois de eu ser levantado, irei à vossa frente para a Galileia.”

[[v40-26-33]]

^<<v40-26-33,33>>^ No entanto, Pedro disse-lhe em resposta: “Ainda que todos os outros tropecem em relação a ti, eu nunca tropeçarei!”

[[v40-26-34]]

^<<v40-26-34,34>>^ Jesus disse-lhe: “Digo-te a verdade: Esta noite, antes de o galo cantar, vais negar-me três vezes.”

[[v40-26-35]]

^<<v40-26-35,35>>^ Pedro disse-lhe: “Mesmo que eu tenha de morrer contigo, de modo algum te negarei.” Todos os outros discípulos disseram a mesma coisa.

[[v40-26-36]]

^<<v40-26-36,36>>^ Jesus chegou então com eles a um lugar chamado Getsémani e disse aos discípulos: “Sentem-se aqui enquanto eu vou ali para orar.”

[[v40-26-37]]

^<<v40-26-37,37>>^ E, levando consigo Pedro e os dois filhos de Zebedeu, começou a ficar triste e muito aflito.

[[v40-26-38]]

^<<v40-26-38,38>>^ Disse-lhes então: “Estou^&#42;1^ profundamente triste, a ponto de morrer. Fiquem aqui e mantenham-se vigilantes comigo.”

[NOTE]
====
. Ou: “A minha alma está”.
====

[[v40-26-39]]

^<<v40-26-39,39>>^ E, indo um pouco mais adiante, prostrou-se com o rosto por terra e orou: “Meu Pai, se for possível, deixa que este cálice se afaste de mim. Contudo, que não seja como eu quero, mas sim como tu queres.”

[[v40-26-40]]

^<<v40-26-40,40>>^ Ele voltou aos discípulos e encontrou-os a dormir, e disse a Pedro: “Não conseguiram manter-se vigilantes comigo nem mesmo por uma hora?

[[v40-26-41]]

^<<v40-26-41,41>>^ Mantenham-se vigilantes e orem continuamente para que não caiam em tentação. Naturalmente, o espírito está disposto,^&#42;1^ mas a carne é fraca.”

[NOTE]
====
. Ou: “pronto”.
====

[[v40-26-42]]

^<<v40-26-42,42>>^ Novamente, pela segunda vez, afastou-se e orou: “Meu Pai, se não é possível que isto se afaste de mim sem que eu o beba, seja feita a tua vontade.”

[[v40-26-43]]

^<<v40-26-43,43>>^ E voltou novamente e encontrou-os a dormir, pois estavam com os olhos pesados.

[[v40-26-44]]

^<<v40-26-44,44>>^ Portanto, deixando-os, afastou-se novamente e orou pela terceira vez, repetindo as mesmas palavras.

[[v40-26-45]]

^<<v40-26-45,45>>^ Voltou então aos discípulos e disse-lhes: “Numa ocasião como esta, vocês estão a dormir e a descansar! Vejam! Aproxima-se a hora de o Filho do Homem ser entregue^&#42;1^ às mãos de pecadores.

[NOTE]
====
. Ou: “traído”.
====

[[v40-26-46]]

^<<v40-26-46,46>>^ Levantem-se, vamos embora. Olhem! Aquele que me trai está a chegar.”

[[v40-26-47]]

^<<v40-26-47,47>>^ Naquele momento, enquanto ele ainda falava, aproximou-se Judas, um dos Doze, acompanhado de uma grande multidão com espadas e bastões. Eles tinham sido enviados pelos principais sacerdotes e pelos anciãos do povo.

[[v40-26-48]]

^<<v40-26-48,48>>^ O traidor tinha-lhes dado um sinal, dizendo: “Aquele a quem eu beijar é ele; prendam-no.”

[[v40-26-49]]

^<<v40-26-49,49>>^ E, dirigindo-se diretamente a Jesus, disse: “Olá, Rabi!” e beijou-o ternamente.

[[v40-26-50]]

^<<v40-26-50,50>>^ No entanto, Jesus disse-lhe: “Amigo, com que objetivo é que estás aqui?” Então, eles avançaram, agarraram Jesus e prenderam-no.

[[v40-26-51]]

^<<v40-26-51,51>>^ Contudo, de repente, um dos que estavam com Jesus estendeu a mão, puxou da espada e atacou o escravo do sumo sacerdote, decepando-lhe a orelha.

[[v40-26-52]]

^<<v40-26-52,52>>^ Jesus disse-lhe então: “Devolve a espada ao seu lugar, pois todos os que usarem a espada morrerão pela espada.

[[v40-26-53]]

^<<v40-26-53,53>>^ Ou pensas que não posso apelar ao meu Pai, para que ele me forneça, neste momento, mais de 12 legiões de anjos?

[[v40-26-54]]

^<<v40-26-54,54>>^ Nesse caso, como é que se cumpririam as Escrituras que dizem que as coisas têm de acontecer deste modo?”

[[v40-26-55]]

^<<v40-26-55,55>>^ Jesus disse à multidão, naquela hora: “Vieram prender-me com espadas e bastões, como se eu fosse um bandido? Dia após dia, eu ficava sentado no templo a ensinar; contudo, vocês não me prenderam.

[[v40-26-56]]

^<<v40-26-56,56>>^ Mas tudo isto aconteceu para que se cumprissem os escritos^&#42;1^ dos profetas.” Então, todos os discípulos o abandonaram e fugiram.

[NOTE]
====
. Ou: “as Escrituras”.
====

[[v40-26-57]]

^<<v40-26-57,57>>^ Os que prenderam Jesus levaram-no a Caifás, o sumo sacerdote, onde estavam reunidos os escribas e os anciãos.

[[v40-26-58]]

^<<v40-26-58,58>>^ Todavia, Pedro seguiu-o, mantendo uma boa distância, até ao pátio do sumo sacerdote, e, depois de entrar, sentou-se com os criados para ver o que ia acontecer.

[[v40-26-59]]

^<<v40-26-59,59>>^ Os principais sacerdotes e todo o Sinédrio estavam à procura de falsos testemunhos contra Jesus, para entregá-lo à morte.

[[v40-26-60]]

^<<v40-26-60,60>>^ Porém, não encontraram nenhum, embora muitas testemunhas falsas se apresentassem. Mais tarde, apresentaram-se duas

[[v40-26-61]]

^<<v40-26-61,61>>^ e disseram: “Este homem disse: ‘Eu posso derrubar o templo de Deus e reconstruí-lo em três dias.’”

[[v40-26-62]]

^<<v40-26-62,62>>^ Em vista disso, o sumo sacerdote levantou-se e disse-lhe: “Não dizes nada em resposta? O que é que tens a dizer do testemunho destes homens contra ti?”

[[v40-26-63]]

^<<v40-26-63,63>>^ No entanto, Jesus continuou calado. Então, o sumo sacerdote disse-lhe: “Pelo Deus vivente, ponho-te sob juramento para que nos digas se tu és o Cristo, o Filho de Deus!”

[[v40-26-64]]

^<<v40-26-64,64>>^ Jesus disse-lhe: “És tu que o estás a dizer. Contudo, digo-vos: De agora em diante, vocês verão o Filho do Homem sentado à direita do poder e a vir nas nuvens do céu.”

[[v40-26-65]]

^<<v40-26-65,65>>^ O sumo sacerdote rasgou então as suas vestes, dizendo: “Ele blasfemou! Que necessidade temos ainda de testemunhas? Vejam! Agora, ouviram a blasfémia.

[[v40-26-66]]

^<<v40-26-66,66>>^ Qual é a vossa opinião?” Eles responderam: “Ele merece morrer.”

[[v40-26-67]]

^<<v40-26-67,67>>^ Cuspiram-lhe então no rosto e esmurraram-no. Outros esbofetearam-no,

[[v40-26-68]]

^<<v40-26-68,68>>^ dizendo: “Profetiza-nos, ó Cristo. Quem é que te bateu?”

[[v40-26-69]]

^<<v40-26-69,69>>^ Pedro estava sentado do lado de fora, no pátio, e uma serva aproximou-se dele e disse: “Tu também estavas com Jesus, o galileu!”

[[v40-26-70]]

^<<v40-26-70,70>>^ Contudo, ele negou-o perante todos, dizendo: “Não sei de que estás a falar.”

[[v40-26-71]]

^<<v40-26-71,71>>^ Quando ele saiu para a entrada do pátio, outra jovem notou-o e disse aos que ali estavam: “Este homem estava com Jesus, o Nazareno.”

[[v40-26-72]]

^<<v40-26-72,72>>^ Ele negou novamente, com um juramento: “Não conheço esse homem!”

[[v40-26-73]]

^<<v40-26-73,73>>^ Pouco depois, os que lá estavam aproximaram-se e disseram a Pedro: “Com certeza, tu também és um deles, pois, de facto, o teu dialeto^&#42;1^ denuncia-te.”

[NOTE]
====
. Ou: “sotaque”.
====

[[v40-26-74]]

^<<v40-26-74,74>>^ Então, ele começou a amaldiçoar-se a si mesmo e a jurar: “Eu não conheço esse homem!” E imediatamente um galo cantou.

[[v40-26-75]]

^<<v40-26-75,75>>^ E Pedro lembrou-se do que Jesus tinha dito: “Antes de o galo cantar, vais negar-me três vezes.” Então, ele saiu dali e chorou amargamente.

'''

xref:040-mateus/040-mateus-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-mateus/040-mateus-027.adoc#v40-27-0[Próximo Capítulo &#62;]