include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando se aproximaram de Jerusalém e chegaram a Betfagé, no monte das Oliveiras, Jesus enviou dois discípulos,

[[v40-21-2]]

^<<v40-21-2,2>>^ dizendo-lhes: “Vão à aldeia que está ao alcance da vista e logo encontrarão uma jumenta amarrada e, com ela, um jumentinho. Desamarrem-nos e tragam-nos até mim.

[[v40-21-3]]

^<<v40-21-3,3>>^ Se vos disserem alguma coisa, digam: ‘O Senhor precisa deles.’ Com isso, vão deixar que os tragam de imediato.”

[[v40-21-4]]

^<<v40-21-4,4>>^ Isto aconteceu para que se cumprissem as palavras do profeta, que disse:

[[v40-21-5]]

^<<v40-21-5,5>>^ “Digam à filha de Sião: ‘Olha! O teu rei vem até ti, de temperamento brando e montado num jumento, sim, num jumentinho, filho de um animal de carga.’”

[[v40-21-6]]

^<<v40-21-6,6>>^ Os discípulos foram então e fizeram conforme Jesus lhes tinha ordenado.

[[v40-21-7]]

^<<v40-21-7,7>>^ Trouxeram a jumenta e o seu jumentinho, colocaram sobre eles as suas capas, e ele sentou-se sobre elas.

[[v40-21-8]]

^<<v40-21-8,8>>^ A maior parte da multidão estendeu as suas capas na estrada, enquanto outros cortavam ramos das árvores e espalhavam-nos pela estrada.

[[v40-21-9]]

^<<v40-21-9,9>>^ Além disso, as multidões que iam à sua frente e as que o seguiam gritavam: “Salva, rogamos, o Filho de David! Bendito é aquele que vem em nome de Jeová!^&#42;1^ Salva-o, rogamos, nas maiores alturas!”

[NOTE]
====
. Veja o Ap. A5.
====

[[v40-21-10]]

^<<v40-21-10,10>>^ Quando ele entrou em Jerusalém, toda a cidade ficou em alvoroço, e diziam: “Quem é este?”

[[v40-21-11]]

^<<v40-21-11,11>>^ As multidões respondiam: “Este é o profeta Jesus, de Nazaré da Galileia!”

[[v40-21-12]]

^<<v40-21-12,12>>^ Jesus entrou no templo, expulsou todos os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ E disse-lhes: “Está escrito: ‘A minha casa será chamada casa de oração’, mas vocês fazem dela um covil de ladrões.”

[[v40-21-14]]

^<<v40-21-14,14>>^ Também, cegos e coxos aproximaram-se dele no templo, e ele curou-os.

[[v40-21-15]]

^<<v40-21-15,15>>^ Quando os principais sacerdotes e os escribas viram as coisas maravilhosas que ele fazia e os meninos que gritavam no templo: “Salva, rogamos, o Filho de David!”, ficaram indignados

[[v40-21-16]]

^<<v40-21-16,16>>^ e disseram-lhe: “Estás a ouvir o que eles estão a dizer?” Jesus disse-lhes: “Sim. Nunca leram o seguinte: ‘Da boca de crianças e de bebés fizeste sair louvor’?”

[[v40-21-17]]

^<<v40-21-17,17>>^ E, deixando-os para trás, saiu da cidade para Betânia e passou lá a noite.

[[v40-21-18]]

^<<v40-21-18,18>>^ Ao voltar à cidade de manhã cedo, sentiu fome.

[[v40-21-19]]

^<<v40-21-19,19>>^ Ele viu uma figueira à beira da estrada e dirigiu-se a ela, mas não encontrou nada, a não ser folhas, e disse-lhe: “Nunca mais produzas nenhum fruto.” E a figueira secou-se instantaneamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ Quando os discípulos viram isto, ficaram admirados e disseram: “Como é que a figueira se secou instantaneamente?”

[[v40-21-21]]

^<<v40-21-21,21>>^ Em resposta, Jesus disse-lhes: “Digo-vos a verdade: Se tiverem fé e não duvidarem, não só farão o que eu fiz à figueira, mas até mesmo se disserem a este monte: ‘Levanta-te e atira-te ao mar’, isso acontecerá.

[[v40-21-22]]

^<<v40-21-22,22>>^ E tudo o que pedirem em oração, tendo fé, receberão.”

[[v40-21-23]]

^<<v40-21-23,23>>^ Depois de ele entrar no templo, os principais sacerdotes e os anciãos do povo aproximaram-se dele, enquanto ensinava, e perguntaram-lhe: “Com que autoridade é que fazes estas coisas? E quem é que te deu esta autoridade?”

[[v40-21-24]]

^<<v40-21-24,24>>^ Jesus disse-lhes em resposta: “Eu também vos vou perguntar uma coisa. Se me responderem, então vou dizer-vos com que autoridade faço estas coisas:

[[v40-21-25]]

^<<v40-21-25,25>>^ O batismo de João, de onde é que se originou? Do céu ou dos homens?”^&#42;1^ Contudo, eles começaram a raciocinar entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Então, porque é que não acreditaram nele?’

[NOTE]
====
. Ou: “de origem humana”.
====

[[v40-21-26]]

^<<v40-21-26,26>>^ Mas, se dissermos: ‘Dos homens’, temos a multidão para temer, porque todos eles consideram João como profeta.”

[[v40-21-27]]

^<<v40-21-27,27>>^ Assim, responderam a Jesus: “Não sabemos.” Ele, por sua vez, disse-lhes: “Então, eu também não vos digo com que autoridade faço estas coisas.

[[v40-21-28]]

^<<v40-21-28,28>>^ “O que é que vocês acham? Um homem tinha dois filhos. Dirigindo-se ao primeiro, disse: ‘Filho, vai trabalhar hoje no vinhedo.’

[[v40-21-29]]

^<<v40-21-29,29>>^ Em resposta, este disse-lhe: ‘Não irei’, mas depois arrependeu-se e foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ Aproximando-se do segundo, o pai disse a mesma coisa. Esse respondeu: ‘Sim, senhor’, mas não foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois é que fez a vontade do pai?” Eles disseram: “O primeiro.” Jesus disse-lhes: “Garanto-vos que os cobradores de impostos e as prostitutas entrarão antes de vocês no Reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio até vocês num caminho de justiça, mas vocês não acreditaram nele. No entanto, os cobradores de impostos e as prostitutas acreditaram nele; e, nem mesmo depois de verem isso, vocês se arrependeram a ponto de acreditar nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ “Ouçam outra ilustração: havia um homem, um proprietário, que plantou um vinhedo, pôs uma cerca à sua volta, cavou um lagar de vinho e ergueu uma torre; então, arrendou o vinhedo a lavradores e viajou para fora.

[[v40-21-34]]

^<<v40-21-34,34>>^ Quando chegou a estação dos frutos, enviou os seus escravos aos lavradores, para receber os seus frutos.

[[v40-21-35]]

^<<v40-21-35,35>>^ No entanto, os lavradores apanharam os escravos dele, e a um espancaram, a outro mataram e a outro apedrejaram.

[[v40-21-36]]

^<<v40-21-36,36>>^ Enviou novamente outros escravos, em maior número do que no primeiro grupo, mas fizeram-lhes o mesmo.

[[v40-21-37]]

^<<v40-21-37,37>>^ Por fim, enviou-lhes o seu filho, dizendo: ‘Respeitarão o meu filho.’

[[v40-21-38]]

^<<v40-21-38,38>>^ Ao verem o filho, os lavradores disseram entre si: ‘Este é o herdeiro. Venham, vamos matá-lo e ficar com a sua herança!’

[[v40-21-39]]

^<<v40-21-39,39>>^ Assim, eles agarraram-no, atiraram-no para fora do vinhedo e mataram-no.

[[v40-21-40]]

^<<v40-21-40,40>>^ Portanto, quando o dono do vinhedo voltar, o que fará ele com aqueles lavradores?”

[[v40-21-41]]

^<<v40-21-41,41>>^ Disseram-lhe: “Por serem maus, trará sobre eles uma destruição terrível e arrendará o vinhedo a outros lavradores, que lhe darão os frutos no seu tempo devido.”

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus disse-lhes: “Nunca leram nas Escrituras: ‘A pedra que os construtores rejeitaram, esta tornou-se a principal pedra angular.^&#42;1^ Isto procede de Jeová^&#42;2^ e é maravilhoso aos nossos olhos’?

[NOTE]
====
. Lit.: “a cabeça da esquina”.
. Veja o Ap. A5.
====

[[v40-21-43]]

^<<v40-21-43,43>>^ É por isso que vos digo: O Reino de Deus ser-vos-á tirado e será dado a uma nação que produza os seus frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ Também, quem cair sobre essa pedra será despedaçado. Quanto àquele sobre quem ela cair, será esmagado.”

[[v40-21-45]]

^<<v40-21-45,45>>^ Quando os principais sacerdotes e os fariseus ouviram as ilustrações dele, sabiam que falava deles.

[[v40-21-46]]

^<<v40-21-46,46>>^ Embora quisessem prendê-lo,^&#42;1^ tinham medo das multidões, porque estas consideravam-no como um profeta.

[NOTE]
====
. Ou: “apanhá-lo”.
====

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]