include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-28-1]]

^<<v40-28-1,1>>^ Depois do sábado, enquanto amanhecia o primeiro dia da semana, Maria Madalena e a outra Maria foram ver a sepultura.

[[v40-28-2]]

^<<v40-28-2,2>>^ Um grande terramoto tinha ocorrido, pois o anjo de Jeová^&#42;1^ tinha descido do céu, chegado ao túmulo e rolado a pedra, e ele estava sentado sobre ela.

[NOTE]
====
. Veja o Ap. A5.
====

[[v40-28-3]]

^<<v40-28-3,3>>^ A sua aparência era como a de um relâmpago e a sua roupa era branca como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ Com medo dele, os vigias tremeram e ficaram como se estivessem mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ No entanto, o anjo disse às mulheres: “Não tenham medo, pois eu sei que estão à procura de Jesus, que foi morto na estaca.

[[v40-28-6]]

^<<v40-28-6,6>>^ Ele não está aqui, pois foi levantado, assim como ele tinha dito. Venham, vejam o lugar onde ele estava deitado.

[[v40-28-7]]

^<<v40-28-7,7>>^ Depois, vão depressa e digam aos discípulos dele: ‘Ele foi levantado dentre os mortos e, agora, vai à vossa frente para a Galileia. É lá que o verão.’ Isto é o que eu vos vim dizer.”

[[v40-28-8]]

^<<v40-28-8,8>>^ Assim, deixando rapidamente o túmulo memorial, com temor e grande alegria, correram para contar tudo aos discípulos dele.

[[v40-28-9]]

^<<v40-28-9,9>>^ Nisto, Jesus foi ao encontro delas e disse: “Bom dia!” Elas aproximaram-se, agarraram-se aos pés dele e prestaram-lhe homenagem.^&#42;1^

[NOTE]
====
. Ou: “curvaram-se diante dele”.
====

[[v40-28-10]]

^<<v40-28-10,10>>^ Jesus disse-lhes então: “Não tenham medo! Vão, relatem isto aos meus irmãos, para que eles se dirijam para a Galileia, e ali me verão.”

[[v40-28-11]]

^<<v40-28-11,11>>^ Enquanto elas estavam a caminho, alguns guardas foram à cidade e comunicaram aos principais sacerdotes tudo o que tinha acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ Depois de estes se terem reunido com os anciãos para decidir o que fazer, deram aos soldados uma boa quantidade de moedas de prata

[[v40-28-13]]

^<<v40-28-13,13>>^ e disseram: “Digam: ‘Os discípulos dele vieram de noite e roubaram-no enquanto estávamos a dormir.’

[[v40-28-14]]

^<<v40-28-14,14>>^ E, se isto chegar aos ouvidos do governador, nós vamos dar-lhe explicações,^&#42;1^ e vocês não precisarão de se preocupar.”

[NOTE]
====
. Lit.: “persuadi-lo”.
====

[[v40-28-15]]

^<<v40-28-15,15>>^ Assim, eles pegaram nas moedas de prata e fizeram conforme lhes mandaram, e esta história tem-se espalhado entre os judeus até ao dia de hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ No entanto, os 11 discípulos foram para a Galileia, para o monte que Jesus lhes tinha indicado.

[[v40-28-17]]

^<<v40-28-17,17>>^ Quando o viram, curvaram-se diante dele,^&#42;1^ mas alguns duvidaram.

[NOTE]
====
. Ou: “prestaram-lhe homenagem”.
====

[[v40-28-18]]

^<<v40-28-18,18>>^ Jesus aproximou-se e disse-lhes: “Foi-me dada toda a autoridade no céu e na terra.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto, vão e façam discípulos de pessoas de todas as nações, batizando-as em nome do Pai, e do Filho, e do espírito santo,

[[v40-28-20]]

^<<v40-28-20,20>>^ ensinando-as a obedecer a todas as coisas que vos ordenei. E saibam que eu estou convosco todos os dias, até ao final do sistema de coisas.”^&#42;1^

[NOTE]
====
. Ou: “final da época”. Veja o Glossário, “Sistema de coisas”.
====

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]