include::./index.adoc[]

[[v40-20-0]]
=== Mateus, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-20-1]]

^<<v40-20-1,1>>^ “Pois o Reino dos céus é semelhante a um proprietário,^&#42;1^ que saiu de manhã cedo para contratar trabalhadores para o seu vinhedo.

[NOTE]
====
. Ou: “dono de uma casa”.
====

[[v40-20-2]]

^<<v40-20-2,2>>^ Depois de ter feito um acordo de um denário^&#42;1^ por dia com os trabalhadores, mandou-os ao seu vinhedo.

[NOTE]
====
. Veja o Ap. B14.
====

[[v40-20-3]]

^<<v40-20-3,3>>^ Por volta da terceira hora,^&#42;1^ ao sair novamente, viu outros que estavam na praça principal sem trabalhar,

[NOTE]
====
. Isto é, por volta das 9 h da manhã.
====

[[v40-20-4]]

^<<v40-20-4,4>>^ e disse-lhes: ‘Vão também vocês ao vinhedo, e eu vou dar-vos o que for justo.’

[[v40-20-5]]

^<<v40-20-5,5>>^ Portanto, eles foram. Ele saiu novamente por volta da sexta hora^&#42;1^ e da nona hora,^&#42;2^ e fez o mesmo.

[NOTE]
====
. Isto é, por volta do meio-dia.
. Isto é, por volta das 3 h da tarde.
====

[[v40-20-6]]

^<<v40-20-6,6>>^ Finalmente, por volta da décima primeira hora,^&#42;1^ ele saiu e encontrou outros ali parados, e perguntou-lhes: ‘Porque é que ficaram aqui o dia todo sem trabalhar?’

[NOTE]
====
. Isto é, por volta das 5 h da tarde.
====

[[v40-20-7]]

^<<v40-20-7,7>>^ Eles responderam: ‘Porque ninguém nos contratou.’ Disse-lhes: ‘Vão também ao vinhedo.’

[[v40-20-8]]

^<<v40-20-8,8>>^ “Quando anoiteceu, o dono do vinhedo disse ao seu administrador: ‘Chama os trabalhadores e paga-lhes o seu salário, começando com os últimos e terminando com os primeiros.’

[[v40-20-9]]

^<<v40-20-9,9>>^ Quando os homens da décima primeira hora chegaram, cada um deles recebeu um denário.^&#42;1^

[NOTE]
====
. Veja o Ap. B14.
====

[[v40-20-10]]

^<<v40-20-10,10>>^ Então, quando os primeiros chegaram, concluíram que receberiam mais, mas eles também receberam o pagamento de um denário^&#42;1^ cada um.

[NOTE]
====
. Veja o Ap. B14.
====

[[v40-20-11]]

^<<v40-20-11,11>>^ Após recebê-lo, começaram a reclamar contra o proprietário

[[v40-20-12]]

^<<v40-20-12,12>>^ e disseram: ‘Estes últimos homens só trabalharam uma hora; ainda assim o senhor igualou-os a nós, que suportámos o fardo do dia e o calor intenso!’

[[v40-20-13]]

^<<v40-20-13,13>>^ No entanto, ele disse, em resposta, a um deles: ‘Amigo, não te faço nenhuma injustiça. Não fizeste comigo um acordo de um denário?^&#42;1^

[NOTE]
====
. Veja o Ap. B14.
====

[[v40-20-14]]

^<<v40-20-14,14>>^ Pega no que é teu e vai. Eu quero dar a este último o mesmo que a ti.

[[v40-20-15]]

^<<v40-20-15,15>>^ Não tenho o direito de fazer o que eu quero com as minhas próprias coisas? Ou ficaste com inveja^&#42;1^ porque fui bom^&#42;2^ com eles?’

[NOTE]
====
. Lit.: “Ou o teu olho é mau (perverso)”.
. Ou: “generoso”.
====

[[v40-20-16]]

^<<v40-20-16,16>>^ Deste modo, os últimos serão os primeiros; e os primeiros, os últimos.”

[[v40-20-17]]

^<<v40-20-17,17>>^ Ao subir para Jerusalém, Jesus chamou os 12 discípulos à parte e disse-lhes na estrada:

[[v40-20-18]]

^<<v40-20-18,18>>^ “Escutem, estamos a subir para Jerusalém, e o Filho do Homem será entregue aos principais sacerdotes e aos escribas. Eles vão condená-lo à morte

[[v40-20-19]]

^<<v40-20-19,19>>^ e entregá-lo a homens das nações para que o ridicularizem, o açoitem e o matem na estaca; e, no terceiro dia, ele será levantado.”

[[v40-20-20]]

^<<v40-20-20,20>>^ Então, aproximou-se dele a mãe dos filhos de Zebedeu com os seus filhos e, curvando-se diante dele,^&#42;1^ pediu-lhe algo.

[NOTE]
====
. Ou: “prestando-lhe homenagem”.
====

[[v40-20-21]]

^<<v40-20-21,21>>^ Ele perguntou-lhe: “O que queres?” Ela respondeu: “Declara que estes meus dois filhos se sentem um à tua direita e outro à tua esquerda, no teu Reino.”

[[v40-20-22]]

^<<v40-20-22,22>>^ Jesus disse em resposta: “Não sabem o que estão a pedir. Será que podem beber o cálice que eu estou prestes a beber?” Disseram-lhe: “Podemos.”

[[v40-20-23]]

^<<v40-20-23,23>>^ Ele disse-lhes: “De facto, vocês beberão o meu cálice, mas não me cabe a mim conceder que se sentem à minha direita e à minha esquerda. Esses lugares pertencem àqueles para quem o meu Pai os preparou.”

[[v40-20-24]]

^<<v40-20-24,24>>^ Quando os outros dez souberam disso, ficaram indignados com os dois irmãos.

[[v40-20-25]]

^<<v40-20-25,25>>^ Porém, Jesus chamou-os e disse-lhes: “Sabem que os governantes dominam sobre as nações e que os grandes homens exercem autoridade sobre elas.

[[v40-20-26]]

^<<v40-20-26,26>>^ Não deve ser assim entre vocês; mas quem quiser tornar-se grande entre vocês tem de ser o vosso servo,^&#42;1^

[NOTE]
====
. Ou: “ministro”.
====

[[v40-20-27]]

^<<v40-20-27,27>>^ e quem quiser ser o primeiro entre vocês tem de ser o vosso escravo,

[[v40-20-28]]

^<<v40-20-28,28>>^ assim como o Filho do Homem veio, não para ser servido, mas para servir^&#42;1^ e dar a sua vida^&#42;2^ como resgate em troca de muitos.”

[NOTE]
====
. Ou: “ministrar”.
. Ou: “alma”.
====

[[v40-20-29]]

^<<v40-20-29,29>>^ Ao saírem de Jericó, uma grande multidão seguiu-o.

[[v40-20-30]]

^<<v40-20-30,30>>^ Então, dois cegos sentados à beira da estrada ouviram que Jesus estava a passar por ali e gritaram: “Senhor, Filho de David, tenha misericórdia de nós!”

[[v40-20-31]]

^<<v40-20-31,31>>^ Todavia, a multidão censurou-os, mandando-os ficar calados. Contudo, gritaram ainda mais alto, dizendo: “Senhor, Filho de David, tenha misericórdia de nós!”

[[v40-20-32]]

^<<v40-20-32,32>>^ Então, Jesus parou, chamou-os e perguntou: “O que é que querem que eu faça por vocês?”

[[v40-20-33]]

^<<v40-20-33,33>>^ Responderam-lhe: “Senhor, faça com que os nossos olhos se abram.”

[[v40-20-34]]

^<<v40-20-34,34>>^ Jesus teve pena e tocou nos olhos deles, e eles recuperaram imediatamente a visão e seguiram-no.

'''

xref:040-mateus/040-mateus-019.adoc#v40-19-0[&#60; Capítulo Anterior] | <<v40-20-0,Topo>> | xref:040-mateus/040-mateus-021.adoc#v40-21-0[Próximo Capítulo &#62;]