include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-12-1]]

^<<v40-12-1,1>>^ Naquela ocasião, Jesus passou pelos campos de cereais no sábado. Os seus discípulos ficaram com fome e começaram a arrancar espigas e a comer.

[[v40-12-2]]

^<<v40-12-2,2>>^ Vendo isso, os fariseus disseram-lhe: “Vê! Os teus discípulos estão a fazer o que não é permitido fazer no sábado.”

[[v40-12-3]]

^<<v40-12-3,3>>^ Ele disse-lhes: “Não leram o que David fez quando ele e os seus homens ficaram com fome?

[[v40-12-4]]

^<<v40-12-4,4>>^ Não leram sobre como ele entrou na casa de Deus, e eles comeram os pães da apresentação,^&#42;1^ algo que não era permitido comer, nem a ele nem aos que estavam com ele, mas apenas aos sacerdotes?

[NOTE]
====
. Ou: “proposição”.
====

[[v40-12-5]]

^<<v40-12-5,5>>^ Ou não leram também na Lei que, nos sábados, os sacerdotes no templo violam o sábado e permanecem sem culpa?

[[v40-12-6]]

^<<v40-12-6,6>>^ Mas digo-vos que está aqui algo maior do que o templo.

[[v40-12-7]]

^<<v40-12-7,7>>^ No entanto, se tivessem entendido o que significa: ‘Quero misericórdia e não sacrifício’, não teriam condenado os inocentes.

[[v40-12-8]]

^<<v40-12-8,8>>^ Porque o Filho do Homem é Senhor do sábado.”

[[v40-12-9]]

^<<v40-12-9,9>>^ Depois de partir daquele lugar, entrou na sinagoga deles,

[[v40-12-10]]

^<<v40-12-10,10>>^ e havia lá um homem com a mão atrofiada.^&#42;1^ Assim, para que pudessem acusá-lo, perguntaram-lhe: “É permitido curar no sábado?”

[NOTE]
====
. Ou: “paralisada”.
====

[[v40-12-11]]

^<<v40-12-11,11>>^ Ele disse-lhes: “Se um de vocês tiver uma ovelha, e essa ovelha cair num buraco no sábado, será que ele não vai agarrá-la e tirá-la de lá?

[[v40-12-12]]

^<<v40-12-12,12>>^ Quanto mais vale um homem do que uma ovelha! Por isso, é permitido fazer algo bom no sábado.”

[[v40-12-13]]

^<<v40-12-13,13>>^ Disse então ao homem: “Estende a mão.” Ele estendeu-a, e ela foi restabelecida e ficou boa como a outra mão.

[[v40-12-14]]

^<<v40-12-14,14>>^ Porém, os fariseus saíram e começaram a conspirar contra ele, para o matarem.

[[v40-12-15]]

^<<v40-12-15,15>>^ Ao saber disso, Jesus retirou-se. Muitos o seguiram, também, e ele curou-os a todos,

[[v40-12-16]]

^<<v40-12-16,16>>^ mas ordenou-lhes com firmeza que não dissessem a outros quem ele era,

[[v40-12-17]]

^<<v40-12-17,17>>^ para que se cumprissem as palavras de Isaías, o profeta, que disse:

[[v40-12-18]]

^<<v40-12-18,18>>^ “Vejam o meu servo a quem escolhi, o meu amado, a quem aprovo!^&#42;1^ Porei sobre ele o meu espírito, e ele esclarecerá às nações o que é a justiça.

[NOTE]
====
. Ou: “a quem minha alma aprova”.
====

[[v40-12-19]]

^<<v40-12-19,19>>^ Não discutirá, nem gritará, e ninguém ouvirá a sua voz nas ruas principais.

[[v40-12-20]]

^<<v40-12-20,20>>^ Não esmagará nenhuma cana partida, nem apagará um pavio que ainda esteja a fumegar, até trazer a justiça com êxito.

[[v40-12-21]]

^<<v40-12-21,21>>^ Realmente, as nações esperarão no seu nome.”

[[v40-12-22]]

^<<v40-12-22,22>>^ Levaram-lhe então um homem possesso, que era cego e mudo, e ele curou-o, de modo que o mudo pôde falar e ver.

[[v40-12-23]]

^<<v40-12-23,23>>^ Ora, todas as multidões ficaram maravilhadas e começaram a dizer: “Não será este o Filho de David?”

[[v40-12-24]]

^<<v40-12-24,24>>^ Ouvindo isso, os fariseus disseram: “Este homem não expulsa os demónios senão por meio de Belzebu,^&#42;1^ o governante dos demónios.”

[NOTE]
====
. Um nome usado para Satanás.
====

[[v40-12-25]]

^<<v40-12-25,25>>^ Conhecendo os pensamentos deles, ele disse-lhes: “Todo o reino dividido contra si mesmo cai em ruína, e toda a cidade ou casa dividida contra si mesma não ficará de pé.

[[v40-12-26]]

^<<v40-12-26,26>>^ Do mesmo modo, se Satanás expulsa Satanás, ele ficou dividido contra si mesmo. Então, como é que o seu reino ficará de pé?

[[v40-12-27]]

^<<v40-12-27,27>>^ Além disso, se eu expulso os demónios por meio de Belzebu, por meio de quem é que os vossos filhos os expulsam? É por isso que eles vos julgarão.

[[v40-12-28]]

^<<v40-12-28,28>>^ Contudo, se é por meio do espírito de Deus que eu expulso os demónios, o Reino de Deus, realmente, alcançou-vos.

[[v40-12-29]]

^<<v40-12-29,29>>^ Ou como é que alguém pode invadir a casa de um homem forte e apoderar-se dos seus bens, a menos que amarre primeiro o homem forte? Só então é que poderá roubar-lhe a casa.

[[v40-12-30]]

^<<v40-12-30,30>>^ Quem não está do meu lado está contra mim, e quem comigo não ajunta, espalha.

[[v40-12-31]]

^<<v40-12-31,31>>^ “Por esta razão, digo-vos: Todo o tipo de pecados e blasfémias será perdoado aos homens, mas a blasfémia contra o espírito não será perdoada.

[[v40-12-32]]

^<<v40-12-32,32>>^ Por exemplo, quem disser uma palavra contra o Filho do Homem será perdoado; mas quem falar contra o espírito santo não será perdoado, não, nem neste sistema de coisas,^&#42;1^ nem no que há de vir.

[NOTE]
====
. Ou: “nesta época”. Veja o Glossário.
====

[[v40-12-33]]

^<<v40-12-33,33>>^ “Se cultivarem uma^&#42;1^ árvore boa, o fruto será bom; se cultivarem uma^&#42;2^ árvore má,^&#42;3^ o fruto será mau.^&#42;4^ Pois é pelo fruto que se conhece a árvore.

[NOTE]
====
. Ou: “tornarem a”.
. Ou: “tornarem a”.
. Ou: “podre”.
. Ou: “podre”.
====

[[v40-12-34]]

^<<v40-12-34,34>>^ Descendência de víboras, como é que vocês podem dizer coisas boas se são maus? Pois a boca fala do que o coração está cheio.

[[v40-12-35]]

^<<v40-12-35,35>>^ O homem bom faz sair coisas boas do seu bom tesouro, ao passo que o homem mau faz sair coisas más do seu mau tesouro.

[[v40-12-36]]

^<<v40-12-36,36>>^ Digo-vos que os homens prestarão contas no Dia do Julgamento por toda a declaração sem valor que fizerem;

[[v40-12-37]]

^<<v40-12-37,37>>^ pois pelas tuas palavras serás declarado justo e pelas tuas palavras serás condenado.”

[[v40-12-38]]

^<<v40-12-38,38>>^ Em vista disso, alguns escribas e fariseus disseram: “Instrutor, queremos ver um sinal da tua parte.”

[[v40-12-39]]

^<<v40-12-39,39>>^ Em resposta, ele disse-lhes: “Uma geração má e adúltera^&#42;1^ persiste em procurar um sinal, mas nenhum sinal lhe será dado, exceto o sinal de Jonas, o profeta.

[NOTE]
====
. Ou: “infiel”.
====

[[v40-12-40]]

^<<v40-12-40,40>>^ Porque, assim como Jonas esteve três dias e três noites no ventre do enorme peixe, assim também o Filho do Homem estará três dias e três noites no coração da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ Homens de Nínive irão levantar-se no julgamento com esta geração e condená-la, porque se arrependeram com o que Jonas pregou. Porém, agora, está aqui alguém maior do que Jonas.

[[v40-12-42]]

^<<v40-12-42,42>>^ A rainha do sul será levantada no julgamento com esta geração e vai condená-la, porque ela veio dos confins da terra para ouvir a sabedoria de Salomão. Mas, agora, está aqui alguém maior do que Salomão.

[[v40-12-43]]

^<<v40-12-43,43>>^ “Quando um espírito impuro sai de um homem, ele passa por lugares áridos à procura de onde descansar e não encontra nada.

[[v40-12-44]]

^<<v40-12-44,44>>^ Por isso, diz: ‘Voltarei para a minha casa, da qual me mudei’; e, ao chegar, encontra a casa desocupada, varrida e decorada.

[[v40-12-45]]

^<<v40-12-45,45>>^ Então, ele vai e traz consigo outros sete espíritos, ainda piores do que ele, e, depois de entrarem, ficam lá a morar; e a situação final deste homem torna-se pior do que no início. É assim que acontecerá também com esta geração má.”

[[v40-12-46]]

^<<v40-12-46,46>>^ Enquanto ainda falava às multidões, a sua mãe e os seus irmãos ficaram parados do lado de fora, querendo falar com ele.

[[v40-12-47]]

^<<v40-12-47,47>>^ Portanto, alguém lhe disse: “Olhe! A sua mãe e os seus irmãos estão lá fora e querem falar consigo.”

[[v40-12-48]]

^<<v40-12-48,48>>^ Ele respondeu a quem lhe falou: “Quem é a minha mãe e quem são os meus irmãos?”

[[v40-12-49]]

^<<v40-12-49,49>>^ E, estendendo a mão para os seus discípulos, disse: “Aqui estão a minha mãe e os meus irmãos!

[[v40-12-50]]

^<<v40-12-50,50>>^ Pois quem faz a vontade do meu Pai, que está no céu, esse é meu irmão, minha irmã e minha mãe.”

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]