include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquela hora, os discípulos aproximaram-se de Jesus e perguntaram: “Quem é realmente o maior no Reino dos céus?”

[[v40-18-2]]

^<<v40-18-2,2>>^ Então, ele chamou uma criança, colocou-a no meio deles

[[v40-18-3]]

^<<v40-18-3,3>>^ e disse: “Digo-vos a verdade: A menos que deem meia-volta^&#42;1^ e se tornem como criancinhas, de modo algum entrarão no Reino dos céus.

[NOTE]
====
. Ou: “mudem”.
====

[[v40-18-4]]

^<<v40-18-4,4>>^ Por isso, quem se humilha, como esta criança, é aquele que é o maior no Reino dos céus;

[[v40-18-5]]

^<<v40-18-5,5>>^ e quem recebe em meu nome uma criança como esta, também me recebe a mim.

[[v40-18-6]]

^<<v40-18-6,6>>^ Mas quem fizer tropeçar um destes pequenos que têm fé em mim, seria melhor para ele que lhe pendurassem ao pescoço uma pedra de moinho, daquelas que o jumento faz girar, e que fosse afundado em alto-mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ “Ai do mundo por causa das suas pedras de tropeço! Claro, é inevitável que venham as pedras de tropeço, mas ai do homem por meio de quem vem a pedra de tropeço!

[[v40-18-8]]

^<<v40-18-8,8>>^ Então, se a tua mão ou o teu pé te faz tropeçar, corta-o e atira-o para longe. É melhor para ti entrares na vida aleijado ou coxo do que seres lançado com as duas mãos ou os dois pés no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ Também, se o teu olho te faz tropeçar, arranca-o e atira-o para longe de ti. É melhor para ti entrares na vida só com um olho do que seres lançado com os dois olhos na Geena^&#42;1^ ardente.

[NOTE]
====
. Veja o Glossário.
====

[[v40-18-10]]

^<<v40-18-10,10>>^ Tenham cuidado para não desprezar um destes pequenos, pois eu vos digo que os seus anjos no céu estão sempre a ver a face do meu Pai, que está no céu.

[[v40-18-11]]

^<<v40-18-11,11>>^ ^&#42;1^——

[NOTE]
====
. Veja o Ap. A3.
====

[[v40-18-12]]

^<<v40-18-12,12>>^ “O que é que acham? Se um homem tiver 100 ovelhas e uma delas se perder, não deixará ele as 99 nos montes e irá à procura daquela que se perdeu?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se a encontrar, certamente vos digo que se alegrará mais com ela do que com as 99 que não se perderam.

[[v40-18-14]]

^<<v40-18-14,14>>^ Do mesmo modo, o meu Pai,^&#42;1^ que está no céu, não deseja que se perca nem sequer um destes pequenos.

[NOTE]
====
. Ou, possivelmente: “o vosso Pai”.
====

[[v40-18-15]]

^<<v40-18-15,15>>^ “Além disso, se o teu irmão cometer um pecado, vai e mostra-lhe o seu erro,^&#42;1^ somente entre ti e ele. Se ele te ouvir, ganhaste o teu irmão.

[NOTE]
====
. Lit.: “repreende-o”.
====

[[v40-18-16]]

^<<v40-18-16,16>>^ Porém, se não te ouvir, leva contigo mais um ou dois, para que, com base no depoimento^&#42;1^ de duas ou três testemunhas, toda a questão seja estabelecida.

[NOTE]
====
. Lit.: “na boca”.
====

[[v40-18-17]]

^<<v40-18-17,17>>^ Se ele não os ouvir, comunica-o à congregação. Se não ouvir nem mesmo a congregação, seja ele para ti apenas como um homem das nações e como um cobrador de impostos.

[[v40-18-18]]

^<<v40-18-18,18>>^ “Digo-vos a verdade: Tudo o que amarrarem na terra já terá sido amarrado no céu, e tudo o que soltarem na terra já terá sido solto no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ Também vos digo esta verdade: Se dois de vocês, na terra, concordarem em pedir qualquer coisa importante, esta ser-vos-á concedida pelo meu Pai, que está no céu.

[[v40-18-20]]

^<<v40-18-20,20>>^ Pois, onde há dois ou três reunidos em meu nome, ali estou eu no meio deles.”

[[v40-18-21]]

^<<v40-18-21,21>>^ Pedro aproximou-se então e perguntou-lhe: “Senhor, quantas vezes devo perdoar o meu irmão se ele pecar contra mim? Até sete vezes?”

[[v40-18-22]]

^<<v40-18-22,22>>^ Jesus respondeu: “Eu não te digo até sete vezes, mas até 77 vezes.

[[v40-18-23]]

^<<v40-18-23,23>>^ “É por isso que o Reino dos céus pode ser comparado a um rei que queria ajustar contas com os seus escravos.

[[v40-18-24]]

^<<v40-18-24,24>>^ Quando começou a ajustá-las, trouxeram-lhe um homem que lhe devia 10 000 talentos.^&#42;1^

[NOTE]
====
. O valor de 10 000 talentos de prata equivalia a 60 000 000 de denários. Veja o Ap. B14.
====

[[v40-18-25]]

^<<v40-18-25,25>>^ Mas, visto que este não tinha meios para pagar, o seu senhor mandou que ele, a esposa dele, os filhos dele e tudo o que tivesse fossem vendidos e fosse feito o pagamento.

[[v40-18-26]]

^<<v40-18-26,26>>^ Então, o escravo prostrou-se e prestou-lhe homenagem,^&#42;1^ dizendo: ‘Tenha paciência comigo, e eu vou pagar-lhe tudo.’

[NOTE]
====
. Ou: “e curvou-se diante dele”.
====

[[v40-18-27]]

^<<v40-18-27,27>>^ Com pena dele, o senhor daquele escravo deixou-o ir e cancelou a sua dívida.

[[v40-18-28]]

^<<v40-18-28,28>>^ Contudo, aquele escravo saiu e encontrou um dos seus coescravos, que lhe devia 100 denários.^&#42;1^ Ele agarrou-o e começou a estrangulá-lo, dizendo: ‘Paga o que me deves.’

[NOTE]
====
. Veja o Ap. B14.
====

[[v40-18-29]]

^<<v40-18-29,29>>^ O seu coescravo prostrou-se então e suplicou-lhe: ‘Tem paciência comigo, que eu vou pagar-te.’

[[v40-18-30]]

^<<v40-18-30,30>>^ No entanto, ele não quis. Em vez disso, mandou-o para a prisão, até que pagasse o que devia.

[[v40-18-31]]

^<<v40-18-31,31>>^ Quando os seus coescravos viram o que tinha acontecido, ficaram muito tristes e foram contar ao senhor tudo o que tinha acontecido.

[[v40-18-32]]

^<<v40-18-32,32>>^ O senhor convocou-o então e disse-lhe: ‘Escravo mau, eu cancelei-te toda aquela dívida quando me suplicaste.

[[v40-18-33]]

^<<v40-18-33,33>>^ Não devias tu também ter tido misericórdia do teu coescravo, assim como eu tive misericórdia de ti?’

[[v40-18-34]]

^<<v40-18-34,34>>^ Com isso, o seu senhor, furioso, entregou-o aos carcereiros, até que pagasse tudo o que devia.

[[v40-18-35]]

^<<v40-18-35,35>>^ O meu Pai celestial vai tratar-vos da mesma forma, se cada um de vocês não perdoar de coração o seu irmão.”

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]