include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-16-1]]

^<<v40-16-1,1>>^ Ali, aproximaram-se dele os fariseus e os saduceus e, para o testarem, pediram-lhe que lhes mostrasse um sinal do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Em resposta, ele disse-lhes: “Ao cair da noite, vocês dizem: ‘Vai estar bom tempo, pois o céu está vermelho’,

[[v40-16-3]]

^<<v40-16-3,3>>^ e, de manhã: ‘Hoje o tempo vai estar frio e chuvoso, pois o céu está vermelho, mas sombrio.’ Vocês sabem interpretar a aparência do céu, mas não conseguem interpretar os sinais dos tempos.

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração má e adúltera^&#42;1^ persiste em procurar um sinal, mas nenhum sinal lhe será dado, exceto o sinal de Jonas.” Com isso, afastou-se, deixando-os para trás.

[NOTE]
====
. Ou: “infiel”.
====

[[v40-16-5]]

^<<v40-16-5,5>>^ Os discípulos passaram então para a outra margem, mas esqueceram-se de levar pães.

[[v40-16-6]]

^<<v40-16-6,6>>^ Jesus disse-lhes: “Mantenham os olhos abertos e tenham cuidado com o fermento dos fariseus e dos saduceus.”

[[v40-16-7]]

^<<v40-16-7,7>>^ Assim, começaram a raciocinar entre si, dizendo: “Não trouxemos pães.”

[[v40-16-8]]

^<<v40-16-8,8>>^ Sabendo disso, Jesus disse: “Homens de pouca fé, porque é que estão a conversar sobre o facto de não terem pães?

[[v40-16-9]]

^<<v40-16-9,9>>^ Ainda não compreendem a questão, e não se lembram dos cinco pães, no caso dos 5000, e de quantos cestos recolheram?

[[v40-16-10]]

^<<v40-16-10,10>>^ Ou dos sete pães, no caso dos 4000, e de quantos cestos grandes^&#42;1^ recolheram?

[NOTE]
====
. Ou: “cestos de provisões”.
====

[[v40-16-11]]

^<<v40-16-11,11>>^ Como é que não compreendem que não vos falei de pão? Eu disse-vos para terem cuidado com o fermento dos fariseus e dos saduceus.”

[[v40-16-12]]

^<<v40-16-12,12>>^ Compreenderam então que ele dizia para terem cuidado, não com o fermento de pão, mas com os ensinamentos dos fariseus e dos saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Quando chegou à região de Cesareia de Filipe, Jesus perguntou aos seus discípulos: “Segundo o que os homens dizem, quem é o Filho do Homem?”

[[v40-16-14]]

^<<v40-16-14,14>>^ Responderam: “Alguns dizem João Batista; outros, Elias; e ainda outros, Jeremias ou um dos profetas.”

[[v40-16-15]]

^<<v40-16-15,15>>^ Ele perguntou-lhes: “E vocês, quem dizem que eu sou?”

[[v40-16-16]]

^<<v40-16-16,16>>^ Simão Pedro respondeu: “Tu és o Cristo, o Filho do Deus vivente.”

[[v40-16-17]]

^<<v40-16-17,17>>^ Jesus disse-lhe então: “Feliz és tu, Simão, filho de Jonas, porque isso não te foi revelado por homens,^&#42;1^ mas pelo meu Pai, que está nos céus.

[NOTE]
====
. Lit.: “carne e sangue”.
====

[[v40-16-18]]

^<<v40-16-18,18>>^ Digo-te, também: Tu és Pedro, e sobre esta rocha construirei a minha congregação, e os portões da Sepultura^&#42;1^ não a vencerão.

[NOTE]
====
. Ou: “do Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v40-16-19]]

^<<v40-16-19,19>>^ Dar-te-ei as chaves do Reino dos céus, e tudo o que amarrares na terra já terá sido amarrado nos céus, e tudo o que soltares na terra já terá sido solto nos céus.”

[[v40-16-20]]

^<<v40-16-20,20>>^ Então, ele ordenou com firmeza aos discípulos que não dissessem a ninguém que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Daquele tempo em diante, Jesus começou a explicar aos seus discípulos que ele tinha de ir a Jerusalém e sofrer muitas coisas por parte dos anciãos, dos principais sacerdotes e dos escribas, e que tinha de ser morto e, no terceiro dia, ser levantado.

[[v40-16-22]]

^<<v40-16-22,22>>^ Em vista disso, Pedro levou-o à parte e começou a censurá-lo, dizendo: “Tem compaixão de ti mesmo, Senhor! Isso de modo algum te acontecerá.”

[[v40-16-23]]

^<<v40-16-23,23>>^ No entanto, ele virou as costas para Pedro e disse-lhe: “Para trás de mim, Satanás! Tu és uma pedra de tropeço para mim, porque não tens os pensamentos de Deus, mas os de homens.”

[[v40-16-24]]

^<<v40-16-24,24>>^ Jesus disse então aos seus discípulos: “Se alguém quiser ser meu seguidor, negue-se a si mesmo, apanhe a sua estaca de tortura^&#42;1^ e siga-me sempre.

[NOTE]
====
. Veja o Glossário.
====

[[v40-16-25]]

^<<v40-16-25,25>>^ Pois quem quiser salvar a sua vida^&#42;1^ vai perdê-la, mas quem perder a sua vida^&#42;2^ por minha causa vai encontrá-la.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v40-16-26]]

^<<v40-16-26,26>>^ Realmente, de que adianta ao homem ganhar o mundo inteiro, se ele perder a sua vida?^&#42;1^ Ou o que dará o homem em troca da sua vida?^&#42;2^

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v40-16-27]]

^<<v40-16-27,27>>^ Porque o Filho do Homem há de vir na glória do seu Pai, com os seus anjos, e então retribuirá a cada um segundo o seu comportamento.

[[v40-16-28]]

^<<v40-16-28,28>>^ Digo-vos a verdade: Há alguns dos que estão aqui que de modo algum provarão a morte antes de verem o Filho do Homem vir no seu Reino.”

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]