include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-27-1]]

^<<v40-27-1,1>>^ Quando amanheceu, todos os principais sacerdotes e os anciãos do povo reuniram-se para decidir como entregar Jesus à morte.

[[v40-27-2]]

^<<v40-27-2,2>>^ Depois de o amarrarem, levaram-no e entregaram-no a Pilatos, o governador.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então, Judas, que tinha traído Jesus, vendo que este tinha sido condenado, sentiu remorsos e devolveu as 30 moedas de prata aos principais sacerdotes e aos anciãos,

[[v40-27-4]]

^<<v40-27-4,4>>^ dizendo: “Pequei quando traí sangue inocente.” Eles disseram: “O que é que nós temos a ver com isso? Isso é lá contigo!”^&#42;1^

[NOTE]
====
. Ou: “Esse problema é teu!”
====

[[v40-27-5]]

^<<v40-27-5,5>>^ Assim, ele lançou as moedas de prata dentro do templo e saiu. De seguida, retirou-se e enforcou-se.

[[v40-27-6]]

^<<v40-27-6,6>>^ Todavia, os principais sacerdotes apanharam as moedas de prata e disseram: “Não é permitido colocá-las no tesouro sagrado, porque são o preço de sangue.”

[[v40-27-7]]

^<<v40-27-7,7>>^ Depois de se consultarem uns aos outros, usaram o dinheiro para comprar o campo do oleiro, como lugar para sepultar estranhos.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso, aquele campo é chamado Campo de Sangue até ao dia de hoje.

[[v40-27-9]]

^<<v40-27-9,9>>^ Deste modo, cumpriram-se as palavras de Jeremias, o profeta: “E apanharam as 30 moedas^&#42;1^ de prata, o preço que foi definido para o homem, aquele em quem alguns dos filhos de Israel puseram um preço,

[NOTE]
====
. Ou: “peças”.
====

[[v40-27-10]]

^<<v40-27-10,10>>^ e deram-nas pelo campo do oleiro, segundo o que Jeová^&#42;1^ me tinha ordenado.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus estava então perante o governador, e o governador perguntou-lhe: “És tu o Rei dos judeus?” Jesus respondeu: “É o senhor que o está a dizer.”

[[v40-27-12]]

^<<v40-27-12,12>>^ Porém, ele não deu nenhuma resposta enquanto estava a ser acusado pelos principais sacerdotes e pelos anciãos.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então, Pilatos perguntou-lhe: “Não estás a ouvir quantas coisas testemunham contra ti?”

[[v40-27-14]]

^<<v40-27-14,14>>^ Contudo, ele não lhe respondeu, não, nem com uma só palavra, de modo que o governador ficou muito surpreendido.

[[v40-27-15]]

^<<v40-27-15,15>>^ Por ocasião da festividade, era costume do governador soltar um preso, aquele que a multidão quisesse.

[[v40-27-16]]

^<<v40-27-16,16>>^ Eles tinham então um preso chamado Barrabás, um criminoso muito conhecido.

[[v40-27-17]]

^<<v40-27-17,17>>^ Portanto, quando estavam reunidos, Pilatos disse-lhes: “Qual deles é que vocês querem que eu solte: Barrabás ou Jesus, o chamado Cristo?”

[[v40-27-18]]

^<<v40-27-18,18>>^ Pois Pilatos sabia que o tinham entregado por inveja.

[[v40-27-19]]

^<<v40-27-19,19>>^ Além disso, enquanto estava sentado no tribunal, a sua esposa mandou-lhe o seguinte recado: “Não tenhas nada a ver com esse homem justo, pois hoje eu sofri muito, num sonho, por causa dele.”

[[v40-27-20]]

^<<v40-27-20,20>>^ No entanto, os principais sacerdotes e os anciãos persuadiram as multidões a pedir Barrabás e a fazer com que Jesus fosse morto.

[[v40-27-21]]

^<<v40-27-21,21>>^ Por conseguinte, o governador disse-lhes: “Qual dos dois é que querem que eu solte?” Disseram: “Barrabás!”

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilatos disse-lhes: “Então, o que é que eu devo fazer com Jesus, o chamado Cristo?” Todos disseram: “Para a estaca com ele!”^&#42;1^

[NOTE]
====
. Ou: “Execute-o na estaca!”
====

[[v40-27-23]]

^<<v40-27-23,23>>^ Ele disse: “Porquê? O que é que ele fez de mal?” Contudo, gritaram ainda mais: “Para a estaca com ele!”

[[v40-27-24]]

^<<v40-27-24,24>>^ Vendo que não adiantava, mas, pelo contrário, que se criava um alvoroço, Pilatos pegou em água e lavou as mãos diante da multidão, dizendo: “Eu sou inocente do sangue deste homem. Isso é convosco.”

[[v40-27-25]]

^<<v40-27-25,25>>^ Todo o povo disse em resposta: “Que o sangue dele caia sobre nós e sobre os nossos filhos.”

[[v40-27-26]]

^<<v40-27-26,26>>^ Ele soltou então Barrabás. Porém, mandou chicotear Jesus e entregou-o para ser morto na estaca.

[[v40-27-27]]

^<<v40-27-27,27>>^ Os soldados do governador levaram Jesus para a residência do governador e reuniram à volta dele todo o grupo de soldados.

[[v40-27-28]]

^<<v40-27-28,28>>^ Depois de o despirem, cobriram-no com um manto escarlate;^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v40-27-29]]

^<<v40-27-29,29>>^ entrançaram uma coroa de espinhos e puseram-na sobre a cabeça dele, e colocaram uma cana na sua mão direita. E, ajoelhando-se diante dele, ridicularizaram-no, dizendo: “Salve, Rei dos judeus!”

[[v40-27-30]]

^<<v40-27-30,30>>^ Então, cuspiram nele, pegaram na cana e começaram a bater-lhe na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Por fim, depois de o terem ridicularizado, tiraram-lhe o manto e voltaram a pôr-lhe as suas roupas, e levaram-no para ser pregado na estaca.

[[v40-27-32]]

^<<v40-27-32,32>>^ Ao saírem, encontraram um homem de Cirene chamado Simão. Obrigaram esse homem a prestar serviço, carregando a estaca.^&#42;1^

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v40-27-33]]

^<<v40-27-33,33>>^ Quando chegaram ao lugar chamado Gólgota, isto é, Lugar da Caveira,

[[v40-27-34]]

^<<v40-27-34,34>>^ deram-lhe vinho misturado com fel^&#42;1^ para beber; mas, depois de o provar, ele recusou-se a beber.

[NOTE]
====
. Um líquido amargo.
====

[[v40-27-35]]

^<<v40-27-35,35>>^ Depois de o pregarem na estaca, repartiram as suas roupas, lançando sortes,

[[v40-27-36]]

^<<v40-27-36,36>>^ e ficaram ali sentados, a vigiá-lo.

[[v40-27-37]]

^<<v40-27-37,37>>^ Também colocaram por cima da sua cabeça, por escrito, a seguinte acusação contra ele: “Este é Jesus, o Rei dos judeus.”

[[v40-27-38]]

^<<v40-27-38,38>>^ Dois ladrões foram então pendurados em estacas ao seu lado, um à sua direita e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que passavam insultavam-no, abanando a cabeça

[[v40-27-40]]

^<<v40-27-40,40>>^ e dizendo: “Tu que ias derrubar o templo e construí-lo em três dias, salva-te a ti mesmo! Se tu és o filho de Deus, desce da estaca!”^&#42;1^

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v40-27-41]]

^<<v40-27-41,41>>^ Do mesmo modo, também os principais sacerdotes, juntamente com os escribas e os anciãos, começaram a ridicularizá-lo, dizendo:

[[v40-27-42]]

^<<v40-27-42,42>>^ “Ele salvou outros, mas não se pode salvar a si mesmo! Ele é Rei de Israel; que desça agora da estaca,^&#42;1^ e nós acreditaremos nele.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v40-27-43]]

^<<v40-27-43,43>>^ Depositou a sua confiança em Deus; que Ele o salve agora, se Ele se agrada dele, pois disse: ‘Sou Filho de Deus.’”

[[v40-27-44]]

^<<v40-27-44,44>>^ Do mesmo modo, até os ladrões, que estavam nas estacas ao seu lado, o insultavam.

[[v40-27-45]]

^<<v40-27-45,45>>^ Da sexta hora^&#42;1^ em diante, caiu uma escuridão sobre toda aquela terra, até à nona hora.^&#42;2^

[NOTE]
====
. Isto é, por volta do meio-dia.
. Isto é, por volta das 3 h da tarde.
====

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta da nona hora, Jesus clamou em voz alta: “Eli, Eli, lama sabactâni?”, isto é: “Deus meu, Deus meu, porque me abandonaste?”

[[v40-27-47]]

^<<v40-27-47,47>>^ Ouvindo isto, alguns dos que ali estavam disseram: “Este homem está a chamar por Elias.”

[[v40-27-48]]

^<<v40-27-48,48>>^ E um deles correu imediatamente, pegou numa esponja, ensopou-a em vinho acre, colocou-a numa cana e deu-lha para ele beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ No entanto, os demais disseram: “Deixa-o! Vamos ver se Elias vem salvá-lo.”

[[v40-27-50]]

^<<v40-27-50,50>>^ Novamente, Jesus clamou em voz alta e entregou o seu espírito.^&#42;1^

[NOTE]
====
. Ou: “e expirou; e deu o seu último suspiro”.
====

[[v40-27-51]]

^<<v40-27-51,51>>^ Naquele momento, a cortina do santuário rasgou-se em duas, de alto a baixo, a terra tremeu e as rochas partiram-se.

[[v40-27-52]]

^<<v40-27-52,52>>^ Os túmulos^&#42;1^ abriram-se e muitos corpos dos santos que tinham adormecido foram levantados

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v40-27-53]]

^<<v40-27-53,53>>^ (e pessoas, que saíram dentre os túmulos depois de ele ter sido levantado, entraram na cidade santa), e eles tornaram-se visíveis para muitas pessoas.

[[v40-27-54]]

^<<v40-27-54,54>>^ Porém, quando o oficial do exército e os que estavam com ele a vigiar Jesus viram o terramoto e as coisas que aconteciam, ficaram com muito medo e disseram: “Certamente este era o Filho de Deus.”

[[v40-27-55]]

^<<v40-27-55,55>>^ E havia ali muitas mulheres a observar a uma certa distância. Elas tinham acompanhado Jesus desde a Galileia, para o servirem.

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre elas estavam Maria Madalena, também Maria, mãe de Tiago e de Josés, e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Então, visto que a tarde estava avançada, chegou um homem rico de Arimateia, chamado José, que também se tinha tornado discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Este homem aproximou-se de Pilatos e pediu o corpo de Jesus. Pilatos ordenou então que o mesmo lhe fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ José pegou no corpo, enrolou-o em puro linho fino

[[v40-27-60]]

^<<v40-27-60,60>>^ e colocou-o no seu túmulo^&#42;1^ novo, que tinha aberto na rocha. E, depois de rolar uma grande pedra até à entrada do túmulo,^&#42;2^ foi-se embora.

[NOTE]
====
. Ou: “túmulo memorial”.
. Ou: “túmulo memorial”.
====

[[v40-27-61]]

^<<v40-27-61,61>>^ No entanto, Maria Madalena e a outra Maria permaneceram ali, sentadas diante da sepultura.

[[v40-27-62]]

^<<v40-27-62,62>>^ No outro dia, o dia seguinte ao da Preparação, os principais sacerdotes e os fariseus reuniram-se perante Pilatos

[[v40-27-63]]

^<<v40-27-63,63>>^ e disseram: “Senhor, lembramo-nos de que, enquanto ainda estava vivo, aquele impostor dizia: ‘Depois de três dias, eu serei levantado.’

[[v40-27-64]]

^<<v40-27-64,64>>^ Portanto, ordene que se mantenha a sepultura em segurança até ao terceiro dia, para que não venham os discípulos dele e o roubem, e digam ao povo: ‘Ele foi levantado dentre os mortos!’ Em tal caso, esta última mentira seria ainda pior do que a primeira.”

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilatos disse-lhes: “Podem levar soldados. Vão, mantenham a sepultura tão segura quanto puderem.”

[[v40-27-66]]

^<<v40-27-66,66>>^ Por conseguinte, foram manter a sepultura em segurança, lacrando a pedra e colocando os soldados de guarda.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]