include::./index.adoc[]

[[v40-22-0]]
=== Mateus, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-22-1]]

^<<v40-22-1,1>>^ Jesus falou-lhes novamente com ilustrações, dizendo:

[[v40-22-2]]

^<<v40-22-2,2>>^ “O Reino dos céus pode ser comparado a um rei que fez uma festa de casamento para o seu filho.

[[v40-22-3]]

^<<v40-22-3,3>>^ Ele mandou os seus escravos chamar os convidados para a festa de casamento, mas estes não quiseram vir.

[[v40-22-4]]

^<<v40-22-4,4>>^ Mandou novamente outros escravos, dizendo: ‘Digam aos convidados: “Já preparei o banquete; os meus touros e os meus animais gordos já foram abatidos e está tudo pronto. Venham à festa de casamento.”’

[[v40-22-5]]

^<<v40-22-5,5>>^ No entanto, os convidados, indiferentes, foram-se embora, um para o seu próprio campo, outro para o seu negócio;

[[v40-22-6]]

^<<v40-22-6,6>>^ e os outros agarraram os escravos dele, maltrataram-nos e mataram-nos.

[[v40-22-7]]

^<<v40-22-7,7>>^ “O rei ficou furioso e enviou os seus exércitos, matou aqueles assassinos e queimou a cidade deles.

[[v40-22-8]]

^<<v40-22-8,8>>^ Depois, disse aos seus escravos: ‘A festa de casamento está pronta, mas os convidados não eram dignos.

[[v40-22-9]]

^<<v40-22-9,9>>^ Portanto, vão às estradas que saem da cidade e convidem qualquer um que encontrem para a festa de casamento.’

[[v40-22-10]]

^<<v40-22-10,10>>^ Então, esses escravos foram às estradas e reuniram todos os que encontraram, tanto maus como bons, e a sala para a cerimónia do casamento ficou cheia de convidados.^&#42;1^

[NOTE]
====
. Ou: “de pessoas recostadas à mesa”.
====

[[v40-22-11]]

^<<v40-22-11,11>>^ “Quando o rei entrou para verificar os convidados, viu um homem que não estava a usar roupa de casamento.

[[v40-22-12]]

^<<v40-22-12,12>>^ Disse-lhe, portanto: ‘Amigo, como é que entraste aqui sem roupa de casamento?’ Ele ficou sem fala.

[[v40-22-13]]

^<<v40-22-13,13>>^ O rei disse então aos seus servos: ‘Amarrem-lhe as mãos e os pés, e lancem-no na escuridão lá fora. É lá que ocorrerá o seu choro e o ranger dos seus dentes.’

[[v40-22-14]]

^<<v40-22-14,14>>^ “Porque há muitos convidados, mas poucos escolhidos.”

[[v40-22-15]]

^<<v40-22-15,15>>^ Então, os fariseus foram-se embora e fizeram planos para apanhá-lo nas suas palavras.

[[v40-22-16]]

^<<v40-22-16,16>>^ Depois, enviaram-lhe discípulos seus, juntamente com partidários de Herodes, para lhe dizer: “Instrutor, sabemos que és verdadeiro e que ensinas o caminho de Deus em verdade, e que não procuras agradar a homens, pois não olhas para a aparência das pessoas.

[[v40-22-17]]

^<<v40-22-17,17>>^ Diz-nos, então: O que achas? É lícito^&#42;1^ ou não pagar a César o imposto por cabeça?”

[NOTE]
====
. Ou: “permitido; certo”.
====

[[v40-22-18]]

^<<v40-22-18,18>>^ Contudo, Jesus, conhecendo a maldade deles, disse: “Hipócritas, porque é que me põem à prova?

[[v40-22-19]]

^<<v40-22-19,19>>^ Mostrem-me a moeda do imposto.” Trouxeram-lhe um denário.^&#42;1^

[NOTE]
====
. Veja o Ap. B14.
====

[[v40-22-20]]

^<<v40-22-20,20>>^ Ele perguntou-lhes: “De quem é esta imagem e inscrição?”

[[v40-22-21]]

^<<v40-22-21,21>>^ Responderam-lhe: “De César.” Então ele disse-lhes: “Portanto, paguem a César o que é de César, mas a Deus o que é de Deus.”

[[v40-22-22]]

^<<v40-22-22,22>>^ Quando ouviram isso, ficaram maravilhados e, deixando-o, foram-se embora.

[[v40-22-23]]

^<<v40-22-23,23>>^ Naquele dia, os saduceus, que dizem não haver ressurreição, aproximaram-se e perguntaram-lhe:

[[v40-22-24]]

^<<v40-22-24,24>>^ “Instrutor, Moisés disse: ‘Se um homem morrer sem deixar filhos, o irmão dele deve casar-se com a viúva para dar descendência ao seu irmão.’

[[v40-22-25]]

^<<v40-22-25,25>>^ Acontece que havia connosco sete irmãos. O primeiro casou-se e morreu, e, visto que não tinha descendente, deixou a sua esposa para o seu irmão.

[[v40-22-26]]

^<<v40-22-26,26>>^ O mesmo aconteceu com o segundo e com o terceiro, e assim com todos os sete.

[[v40-22-27]]

^<<v40-22-27,27>>^ Por último, morreu a mulher.

[[v40-22-28]]

^<<v40-22-28,28>>^ Assim, na ressurreição, de qual dos sete será ela esposa? Pois todos a tiveram como esposa.”

[[v40-22-29]]

^<<v40-22-29,29>>^ Em resposta, Jesus disse-lhes: “Estão enganados, porque não conhecem nem as Escrituras, nem o poder de Deus;

[[v40-22-30]]

^<<v40-22-30,30>>^ pois, na ressurreição, os homens não se casam, nem as mulheres são dadas em casamento, mas são como os anjos no céu.

[[v40-22-31]]

^<<v40-22-31,31>>^ A respeito da ressurreição dos mortos, não leram o que vos foi declarado por Deus, que disse:

[[v40-22-32]]

^<<v40-22-32,32>>^ ‘Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’? Ele é o Deus, não de mortos, mas de vivos.”

[[v40-22-33]]

^<<v40-22-33,33>>^ Ouvindo isso, as multidões ficaram maravilhadas com o seu ensino.

[[v40-22-34]]

^<<v40-22-34,34>>^ Depois de os fariseus ouvirem dizer que ele tinha silenciado os saduceus, reuniram-se num só grupo.

[[v40-22-35]]

^<<v40-22-35,35>>^ E um deles, perito na Lei, pô-lo à prova com uma pergunta:

[[v40-22-36]]

^<<v40-22-36,36>>^ “Instrutor, qual é o maior mandamento da Lei?”

[[v40-22-37]]

^<<v40-22-37,37>>^ Ele disse-lhe: “‘Ama a Jeová,^&#42;1^ teu Deus, de todo o teu coração, de toda a tua alma^&#42;2^ e de toda a tua mente.’

[NOTE]
====
. Veja o Ap. A5.
. Veja o Glossário.
====

[[v40-22-38]]

^<<v40-22-38,38>>^ Este é o maior e primeiro mandamento.

[[v40-22-39]]

^<<v40-22-39,39>>^ O segundo, semelhante a este, é: ‘Ama o teu próximo como a ti mesmo.’

[[v40-22-40]]

^<<v40-22-40,40>>^ Destes dois mandamentos dependem toda a Lei e os Profetas.”

[[v40-22-41]]

^<<v40-22-41,41>>^ Então, enquanto os fariseus estavam reunidos, Jesus perguntou-lhes:

[[v40-22-42]]

^<<v40-22-42,42>>^ “O que pensam do Cristo? De quem é ele filho?” Disseram-lhe: “De David.”

[[v40-22-43]]

^<<v40-22-43,43>>^ Ele perguntou-lhes: “Como é, então, que David, sob inspiração, lhe chama Senhor, dizendo:

[[v40-22-44]]

^<<v40-22-44,44>>^ ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés”’?

[NOTE]
====
. Veja o Ap. A5.
====

[[v40-22-45]]

^<<v40-22-45,45>>^ Então, se David lhe chama Senhor, como é que ele é seu filho?”

[[v40-22-46]]

^<<v40-22-46,46>>^ E ninguém foi capaz de lhe dizer uma só palavra em resposta e, daquele dia em diante, ninguém se atreveu a fazer-lhe mais perguntas.

'''

xref:040-mateus/040-mateus-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-mateus/040-mateus-023.adoc#v40-23-0[Próximo Capítulo &#62;]