include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-11-1]]

^<<v40-11-1,1>>^ Quando acabou de dar instruções aos seus 12 discípulos, Jesus partiu daquele lugar para ensinar e pregar nas cidades deles.

[[v40-11-2]]

^<<v40-11-2,2>>^ Porém, na cadeia, tendo ouvido falar das obras do Cristo, João enviou os seus próprios discípulos

[[v40-11-3]]

^<<v40-11-3,3>>^ para lhe perguntarem: “És Aquele Que Vem, ou devemos esperar outro?”

[[v40-11-4]]

^<<v40-11-4,4>>^ Jesus disse-lhes em resposta: “Vão, contem a João o que estão a ouvir e a ver:

[[v40-11-5]]

^<<v40-11-5,5>>^ os cegos agora veem, os coxos estão a andar, os leprosos estão a ser purificados, os surdos estão a ouvir, os mortos estão a ser levantados e as boas novas estão a ser anunciadas aos pobres.

[[v40-11-6]]

^<<v40-11-6,6>>^ Feliz é aquele que não encontra em mim nenhuma causa para tropeço.”

[[v40-11-7]]

^<<v40-11-7,7>>^ Enquanto eles partiam, Jesus começou a falar às multidões sobre João: “O que é que foram ver ao deserto? Uma cana sacudida pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ Então, o que é que foram ver? Um homem vestido de roupas finas? Ora, os que usam roupas finas estão nos palácios dos reis.

[[v40-11-9]]

^<<v40-11-9,9>>^ Realmente, então, porque é que foram lá? Para ver um profeta? Sim, digo-vos eu, e muito mais do que um profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Este é aquele a respeito de quem se escreveu: ‘Vê! Enviarei o meu mensageiro à tua frente,^&#42;1^ o qual preparará o teu caminho diante de ti!’

[NOTE]
====
. Lit.: “diante da tua face”.
====

[[v40-11-11]]

^<<v40-11-11,11>>^ Digo-vos a verdade: Entre os nascidos de mulheres, não surgiu ninguém maior do que João Batista; mas aquele que é menor no Reino dos céus é maior do que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias de João Batista até agora, o Reino dos céus é o alvo para o qual os homens avançam vigorosamente, e os que avançam vigorosamente apoderam-se dele.

[[v40-11-13]]

^<<v40-11-13,13>>^ Pois todos, os Profetas e a Lei, profetizaram até João.

[[v40-11-14]]

^<<v40-11-14,14>>^ E, se vocês quiserem aceitar, ele é ‘Elias, que há de vir’.

[[v40-11-15]]

^<<v40-11-15,15>>^ Quem tem ouvidos, ouça.

[[v40-11-16]]

^<<v40-11-16,16>>^ “Com quem é que compararei esta geração? Ela é semelhante a crianças sentadas nas praças,^&#42;1^ que gritam para os seus colegas:

[NOTE]
====
. Áreas abertas usadas como centro de compras e vendas e como local de reuniões públicas.
====

[[v40-11-17]]

^<<v40-11-17,17>>^ ‘Nós tocámos flauta para vocês, mas vocês não dançaram; nós lamentámos, mas vocês não bateram no peito de pesar.’

[[v40-11-18]]

^<<v40-11-18,18>>^ Da mesma maneira, João veio sem comer e sem beber, mas as pessoas dizem: ‘Ele tem um demónio.’

[[v40-11-19]]

^<<v40-11-19,19>>^ O Filho do Homem veio, comendo e bebendo, mas elas dizem: ‘Vejam! Um homem glutão e dado a beber vinho, amigo de cobradores de impostos e de pecadores.’ No entanto, a sabedoria prova-se justa^&#42;1^ pelas suas obras.”^&#42;2^

[NOTE]
====
. Ou: “é vindicada”.
. Ou: “pelos seus resultados”.
====

[[v40-11-20]]

^<<v40-11-20,20>>^ Ele começou então a censurar as cidades nas quais se realizou a maioria das suas obras poderosas, pois não se arrependeram:

[[v40-11-21]]

^<<v40-11-21,21>>^ “Ai de ti, Corazim! Ai de ti, Betsaida! Porque, se as obras poderosas que ocorreram em vocês tivessem ocorrido em Tiro e Sídon, estas ter-se-iam arrependido há muito tempo em serapilheira^&#42;1^ e em cinzas.

[NOTE]
====
. Veja o Glossário.
====

[[v40-11-22]]

^<<v40-11-22,22>>^ Contudo, digo-vos: No Dia do Julgamento, será mais suportável para Tiro e Sídon do que para vocês.

[[v40-11-23]]

^<<v40-11-23,23>>^ E tu, Cafarnaum, serás, por acaso, enaltecida até ao céu? Descerás até à Sepultura.^&#42;1^ Porque, se as obras poderosas que ocorreram em ti tivessem ocorrido em Sodoma, esta teria permanecido até ao dia de hoje.

[NOTE]
====
. Ou: “ao Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v40-11-24]]

^<<v40-11-24,24>>^ Digo-vos, porém: No Dia do Julgamento, será mais suportável para a terra de Sodoma do que para ti.”

[[v40-11-25]]

^<<v40-11-25,25>>^ Em vista disso, naquela ocasião, Jesus disse: “Eu louvo-te publicamente, Pai, Senhor do céu e da terra, porque escondeste estas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, ó Pai, porque tu te agradaste em fazer as coisas desta maneira.

[[v40-11-27]]

^<<v40-11-27,27>>^ Tudo me foi entregue pelo meu Pai. E ninguém conhece plenamente o Filho, exceto o Pai; e ninguém conhece plenamente o Pai, exceto o Filho e aquele a quem o Filho quiser revelá-lo.

[[v40-11-28]]

^<<v40-11-28,28>>^ Venham a mim, todos vocês que estão a trabalhar arduamente e que estão sobrecarregados, e eu vou reanimar-vos.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomem sobre vocês o meu jugo e aprendam de mim, pois sou de temperamento brando e humilde de coração, e encontrarão revigoramento para vocês mesmos.^&#42;1^

[NOTE]
====
. Ou: “a vossa alma”.
====

[[v40-11-30]]

^<<v40-11-30,30>>^ Pois o meu jugo é suave^&#42;1^ e a minha carga é leve.”

[NOTE]
====
. Ou: “fácil de carregar”.
====

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]