include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v17-9-1]]

^<<v17-9-1,1>>^ No dia 13 do décimo segundo mês, isto é, o mês de adar,^&#42;1^ quando a ordem do rei e o seu decreto deveriam ser cumpridos, no dia em que os inimigos dos judeus esperavam dominá-los, aconteceu o contrário: foram os judeus que derrotaram os que os odiavam.

[NOTE]
====
. Veja o Ap.Ap. B15.
====

[[v17-9-2]]

^<<v17-9-2,2>>^ Os judeus reuniram-se nas suas cidades em todas as províncias^&#42;1^ do rei Assuero para atacar os que procuravam fazer-lhes mal. Ninguém lhes conseguiu resistir, pois todos os povos tinham ficado com muito medo deles.

[NOTE]
====
. Ou: “todos os distritos jurisdicionais”.
====

[[v17-9-3]]

^<<v17-9-3,3>>^ E todos os príncipes das províncias, os sátrapas, os governadores e os que cuidavam dos negócios do rei apoiaram os judeus, pois tinham ficado com medo de Mordecai.

[[v17-9-4]]

^<<v17-9-4,4>>^ Mordecai tinha-se tornado poderoso na casa^&#42;1^ do rei, e a sua fama espalhava-se por todas as províncias, visto que ele se tornava cada vez mais poderoso.

[NOTE]
====
. Ou: “no palácio”.
====

[[v17-9-5]]

^<<v17-9-5,5>>^ Os judeus golpearam com a espada todos os seus inimigos, matando-os e destruindo-os; fizeram o que quiseram com os que os odiavam.

[[v17-9-6]]

^<<v17-9-6,6>>^ E, na fortaleza^&#42;1^ de Susã,^&#42;2^ os judeus mataram e destruíram 500 homens.

[NOTE]
====
. Ou: “na cidadela; no palácio”.
. Ou: “Susa”.
====

[[v17-9-7]]

^<<v17-9-7,7>>^ Também mataram Parsandata, Dalfom, Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ Porata, Adalia, Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ Parmasta, Arisai, Aridai e Vaizata,

[[v17-9-10]]

^<<v17-9-10,10>>^ os dez filhos de Hamã, o inimigo dos judeus, filho de Hamedata. Contudo, não lhes saquearam os bens depois de os matarem.

[[v17-9-11]]

^<<v17-9-11,11>>^ Naquele mesmo dia, foi relatado ao rei o número de mortos na fortaleza^&#42;1^ de Susã.^&#42;2^

[NOTE]
====
. Ou: “na cidadela; no palácio”.
. Ou: “Susa”.
====

[[v17-9-12]]

^<<v17-9-12,12>>^ O rei disse à rainha Ester: “Se só na fortaleza^&#42;1^ de Susã^&#42;2^ os judeus mataram e destruíram 500 homens e os dez filhos de Hamã, o que será que fizeram nas outras províncias do rei? E agora, tens mais algum pedido? Ele ser-te-á concedido. Tens mais alguma solicitação? Ela ser-te-á atendida.”

[NOTE]
====
. Ou: “na cidadela; no palácio”.
. Ou: “Susa”.
====

[[v17-9-13]]

^<<v17-9-13,13>>^ Ester respondeu: “Se for do agrado do rei, que os judeus em Susã^&#42;1^ recebam autorização para agir outra vez amanhã, conforme o decreto emitido para hoje, e que os dez filhos de Hamã sejam pendurados no madeiro.”

[NOTE]
====
. Ou: “Susa”.
====

[[v17-9-14]]

^<<v17-9-14,14>>^ Portanto, o rei ordenou que isso fosse feito. O decreto foi proclamado em Susã,^&#42;1^ e os dez filhos de Hamã foram pendurados no madeiro.

[NOTE]
====
. Ou: “Susa”.
====

[[v17-9-15]]

^<<v17-9-15,15>>^ Os judeus em Susã^&#42;1^ reuniram-se novamente no dia 14 do mês de adar e mataram 300 homens em Susã,^&#42;2^ mas não lhes saquearam os bens.

[NOTE]
====
. Ou: “Susa”.
. Ou: “Susa”.
====

[[v17-9-16]]

^<<v17-9-16,16>>^ Os outros judeus, que moravam nas províncias do rei, também se reuniram e defenderam as suas vidas.^&#42;1^ Eles livraram-se dos seus inimigos e mataram 75 000 dos que os odiavam, mas não lhes saquearam os bens.

[NOTE]
====
. Ou: “e se mantiveram firmes pelas suas almas”.
====

[[v17-9-17]]

^<<v17-9-17,17>>^ Isto aconteceu no dia 13 do mês de adar. No dia 14, eles descansaram, e fizeram dessa data um dia de banquetes e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Quanto aos judeus em Susã,^&#42;1^ eles reuniram-se^&#42;2^ no dia 13 e no dia 14 do mês de adar. No dia 15, eles descansaram, e fizeram dessa data um dia de banquetes e de alegria.

[NOTE]
====
. Ou: “Susa”.
. Isto é, para se defenderem.
====

[[v17-9-19]]

^<<v17-9-19,19>>^ Foi por isso que os judeus que moravam nas cidades dos distritos fora da capital fizeram do dia 14 do mês de adar um dia de alegria, de banquetes e de comemoração, uma ocasião para enviarem porções de comida uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ Mordecai registou estes eventos e enviou cartas oficiais a todos os judeus em todas as províncias do rei Assuero, tanto às próximas como às distantes.

[[v17-9-21]]

^<<v17-9-21,21>>^ Ele ordenou-lhes que celebrassem anualmente os dias 14 e 15 do mês de adar,

[[v17-9-22]]

^<<v17-9-22,22>>^ pois, nesses dias, os judeus descansaram dos seus inimigos, e, nesse mês, a sua tristeza transformou-se em alegria, e o seu luto em comemoração. Eles deveriam celebrar essas datas como dias de banquetes e de alegria, como ocasião para enviarem porções de comida uns aos outros e dar presentes aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ E os judeus concordaram em adotar como costume a comemoração que tinham começado e em fazer o que Mordecai lhes escreveu.

[[v17-9-24]]

^<<v17-9-24,24>>^ Pois Hamã, o inimigo de todos os judeus, filho de Hamedata, o agagita, tinha tramado destruir os judeus e tinha lançado “pur”, isto é, a sorte, para os deixar em pânico e para os destruir.

[[v17-9-25]]

^<<v17-9-25,25>>^ Todavia, quando Ester compareceu perante o rei, ele ordenou por escrito: “Que o seu plano maligno contra os judeus recaia sobre a sua própria cabeça.” E ele e os seus filhos foram pendurados no madeiro.

[[v17-9-26]]

^<<v17-9-26,26>>^ Foi por isso que chamaram a esses dias Purim, que vem da palavra “pur”.^&#42;1^ Assim, em vista de tudo o que estava escrito na carta, do que tinham visto e do que lhes tinha acontecido,

[NOTE]
====
. “Pur” significa “sorte”. O plural, “purim”, passou a ser o nome da festividade judaica celebrada no décimo segundo mês do calendário sagrado. Veja o Ap. B15.
====

[[v17-9-27]]

^<<v17-9-27,27>>^ os judeus impuseram a si mesmos, aos seus descendentes e a todos os que se lhes juntassem a obrigação de comemorar esses dois dias e de fazer o que estava escrito a respeito deles, na época determinada, todos os anos.

[[v17-9-28]]

^<<v17-9-28,28>>^ Esses eram dias para serem lembrados e celebrados por todas as gerações, por todas as famílias, em todas as províncias e em todas as cidades. Esses dias de Purim não deveriam ser descontinuados entre os judeus, e essa comemoração não deveria ter fim entre os seus descendentes.

[[v17-9-29]]

^<<v17-9-29,29>>^ Mais tarde, uma segunda carta foi escrita a respeito dos dias de Purim, e a rainha Ester, filha de Abiail, e Mordecai, o judeu, confirmaram-na com toda a autoridade.

[[v17-9-30]]

^<<v17-9-30,30>>^ Ele enviou cartas oficiais a todos os judeus nas 127 províncias do reino de Assuero, com palavras de paz e fidelidade,

[[v17-9-31]]

^<<v17-9-31,31>>^ para confirmar a celebração dos dias de Purim na época determinada, assim como Mordecai, o judeu, e a rainha Ester lhes tinham ordenado, e assim como eles tinham imposto a si mesmos^&#42;1^ e aos seus descendentes, incluindo jejuns e súplicas.

[NOTE]
====
. Ou: “às suas almas”.
====

[[v17-9-32]]

^<<v17-9-32,32>>^ E a ordem de Ester confirmou esses assuntos referentes aos dias de Purim, e isso foi registado num livro.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]