include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v17-2-1]]

^<<v17-2-1,1>>^ Depois destes acontecimentos, quando o rei Assuero já se tinha acalmado do seu furor, ele lembrou-se do que Vasti tinha feito e do que tinha decidido contra ela.

[[v17-2-2]]

^<<v17-2-2,2>>^ Então, os assistentes pessoais do rei disseram: “Procurem-se para o rei jovens virgens e belas.

[[v17-2-3]]

^<<v17-2-3,3>>^ Que o rei designe representantes em todas as províncias^&#42;1^ do seu reino, para que tragam todas as jovens virgens e belas à fortaleza^&#42;2^ de Susã,^&#42;3^ à casa das mulheres.^&#42;4^ Elas ficarão aos cuidados de Hegai, eunuco do rei e responsável pelas mulheres, e receberão tratamentos de beleza.^&#42;5^

[NOTE]
====
. Ou: “todos os distritos jurisdicionais”.
. Ou: “à cidadela; ao palácio”.
. Ou: “Susa”.
. Ou: “ao harém”.
. Ou: “receberão massagens”.
====

[[v17-2-4]]

^<<v17-2-4,4>>^ E a jovem que mais agradar ao rei será rainha no lugar de Vasti.” A sugestão agradou ao rei, e foi isso que ele fez.

[[v17-2-5]]

^<<v17-2-5,5>>^ Na fortaleza^&#42;1^ de Susã,^&#42;2^ havia um judeu chamado Mordecai, filho de Jair, filho de Simei, filho de Quis, um benjaminita.

[NOTE]
====
. Ou: “Na cidadela; No palácio”.
. Ou: “Susa”.
====

[[v17-2-6]]

^<<v17-2-6,6>>^ Ele tinha sido exilado de Jerusalém com o povo que foi deportado com Jeconias,^&#42;1^ rei de Judá, o qual foi levado para o exílio por Nabucodonosor, rei de Babilónia.

[NOTE]
====
. Chamado Joaquim em 2 Reis 24:8.
====

[[v17-2-7]]

^<<v17-2-7,7>>^ Ele criou^&#42;1^ Hadassa,^&#42;2^ isto é, Ester, filha do seu tio paterno, porque ela não tinha nem pai nem mãe. Ela era uma jovem bonita e atraente, e Mordecai tinha-a adotado como filha depois de o pai e a mãe dela terem morrido.

[NOTE]
====
. Ou: “era o tutor de”.
. Que significa “murta”.
====

[[v17-2-8]]

^<<v17-2-8,8>>^ Quando a ordem do rei e o seu decreto foram proclamados, e muitas jovens foram trazidas à fortaleza^&#42;1^ de Susã^&#42;2^ e deixadas aos cuidados de Hegai, Ester também foi levada à casa^&#42;3^ do rei e ficou aos cuidados de Hegai, o responsável pelas mulheres.

[NOTE]
====
. Ou: “à cidadela; ao palácio”.
. Ou: “Susa”.
. Ou: “ao palácio”.
====

[[v17-2-9]]

^<<v17-2-9,9>>^ A jovem agradou a Hegai e ganhou o seu favor,^&#42;1^ e ele apressou-se a providenciar que ela recebesse tratamentos de beleza^&#42;2^ e alimentação especial, e designou-lhe sete das melhores criadas da casa do rei. Além disso, transferiu-a, a ela e às criadas, para o melhor lugar na casa das mulheres.^&#42;3^

[NOTE]
====
. Ou: “amor leal”.
. Ou: “massagens”.
. Ou: “no harém”.
====

[[v17-2-10]]

^<<v17-2-10,10>>^ Ester não disse nada acerca do seu povo e dos seus parentes, pois Mordecai tinha-lhe ordenado que não comentasse isso com ninguém.

[[v17-2-11]]

^<<v17-2-11,11>>^ Todos os dias, Mordecai passava em frente ao pátio da casa das mulheres^&#42;1^ para saber como Ester estava e o que lhe acontecia.

[NOTE]
====
. Ou: “pátio do harém”.
====

[[v17-2-12]]

^<<v17-2-12,12>>^ Antes de chegar a sua vez de se apresentar ao rei Assuero, todas as jovens recebiam o tratamento de 12 meses prescrito para as mulheres. E o tratamento de beleza^&#42;1^ que elas tinham de fazer era o seguinte: seis meses com óleo de mirra e seis meses com óleo de bálsamo e outros óleos para tratamento de beleza.^&#42;2^

[NOTE]
====
. Ou: “as massagens”.
. Ou: “e com massagens das mulheres”.
====

[[v17-2-13]]

^<<v17-2-13,13>>^ Então, a jovem estava pronta para se apresentar ao rei, e ela recebia tudo o que pedisse para levar consigo da casa das mulheres^&#42;1^ para a casa do rei.

[NOTE]
====
. Ou: “consigo do harém”.
====

[[v17-2-14]]

^<<v17-2-14,14>>^ Ela entrava na casa do rei ao anoitecer, e, na manhã seguinte, ia para a segunda casa das mulheres,^&#42;1^ aos cuidados de Saasgaz, eunuco do rei, responsável pelas concubinas. Ela não voltava mais à presença do rei, a menos que o rei se tivesse agradado especialmente dela e a mandasse chamar por nome.

[NOTE]
====
. Ou: “o segundo harém”.
====

[[v17-2-15]]

^<<v17-2-15,15>>^ Quando chegou a sua vez de se apresentar ao rei, Ester — filha de Abiail, tio de Mordecai, que a tinha adotado como filha — não solicitou nada além do que foi recomendado por Hegai, eunuco do rei e responsável pelas mulheres. (Durante todo aquele tempo, Ester ganhava o favor de todos os que a viam.)

[[v17-2-16]]

^<<v17-2-16,16>>^ Ester foi levada ao rei Assuero, na sua casa real, no décimo mês, isto é, no mês de tebete,^&#42;1^ no sétimo ano do seu reinado.

[NOTE]
====
. Veja o Ap. B15.
====

[[v17-2-17]]

^<<v17-2-17,17>>^ E o rei amou mais Ester do que todas as outras mulheres, e ela ganhou o seu favor e a sua aprovação,^&#42;1^ mais do que qualquer outra das virgens. Por isso, ele colocou-lhe o turbante^&#42;2^ real na cabeça e fez dela rainha no lugar de Vasti.

[NOTE]
====
. Ou: “o seu amor leal”.
. Ou: “toucado”.
====

[[v17-2-18]]

^<<v17-2-18,18>>^ O rei deu então um grande banquete — o banquete de Ester — para todos os seus príncipes e servos. Também concedeu amnistia às províncias e distribuiu presentes conforme só o rei tinha condições de fazer.

[[v17-2-19]]

^<<v17-2-19,19>>^ Quando virgens^&#42;1^ foram trazidas pela segunda vez, Mordecai estava sentado no portão do rei.

[NOTE]
====
. Ou: “jovens”.
====

[[v17-2-20]]

^<<v17-2-20,20>>^ Ester não dizia nada acerca dos seus parentes e do seu povo, conforme Mordecai a tinha orientado. Ester continuava a obedecer às instruções de Mordecai, assim como fazia quando estava aos cuidados dele.

[[v17-2-21]]

^<<v17-2-21,21>>^ Naqueles dias, quando Mordecai se sentava no portão do rei, Bigtã e Teres, dois oficiais da corte do rei, porteiros, ficaram furiosos e planearam matar o^&#42;1^ rei Assuero.

[NOTE]
====
. Lit.: “deitar a mão ao”.
====

[[v17-2-22]]

^<<v17-2-22,22>>^ Contudo, Mordecai soube da trama e informou imediatamente a rainha Ester. Ela, por sua vez, contou isso ao rei em nome de Mordecai.

[[v17-2-23]]

^<<v17-2-23,23>>^ O assunto foi investigado e comprovado, de modo que os dois homens foram pendurados num madeiro, e tudo isto foi escrito perante o rei no livro dos registos históricos.

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]