include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-1-1]]

^<<v3-1-1,1>>^ E, da tenda de reunião, Jeová chamou Moisés e disse-lhe:

[[v3-1-2]]

^<<v3-1-2,2>>^ “Diz aos israelitas:^&#42;1^ ‘Se algum de vocês apresentar a Jeová uma oferta dentre os animais domésticos, a vossa oferta deve ser dentre a manada ou dentre o rebanho.

[NOTE]
====
. Lit.: “filhos de Israel”.
====

[[v3-1-3]]

^<<v3-1-3,3>>^ “‘Se ele oferecer uma oferta queimada dentre a manada, deve apresentar um macho sadio. Deve apresentá-lo de sua própria vontade perante Jeová, à entrada da tenda de reunião.

[[v3-1-4]]

^<<v3-1-4,4>>^ Deve pôr a mão sobre a cabeça do animal para a oferta queimada, e a oferta será aceite em seu favor, para fazer expiação por ele.

[[v3-1-5]]

^<<v3-1-5,5>>^ “‘Então, o novilho terá de ser abatido perante Jeová; e os filhos de Arão, os sacerdotes, apresentarão o sangue e aspergirão o sangue em todos os lados do altar, que está à entrada da tenda de reunião.

[[v3-1-6]]

^<<v3-1-6,6>>^ Deve-se esfolar a oferta queimada e cortar o animal em pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ Os filhos de Arão, os sacerdotes, devem pôr fogo sobre o altar e dispor a lenha sobre o fogo.

[[v3-1-8]]

^<<v3-1-8,8>>^ E os filhos de Arão, os sacerdotes, disporão os pedaços da oferta, com a cabeça e a gordura,^&#42;1^ sobre a lenha que está no fogo do altar.

[NOTE]
====
. Ou: “a gordura à volta dos rins”.
====

[[v3-1-9]]

^<<v3-1-9,9>>^ Os intestinos e as pernas^&#42;1^ serão lavados com água. O sacerdote queimará^&#42;2^ tudo no altar, como oferta queimada. É uma oferta feita por fogo, de aroma agradável^&#42;3^ para Jeová.

[NOTE]
====
. Isto é, a parte inferior das pernas.
. Ou: “fará fumegar”.
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v3-1-10]]

^<<v3-1-10,10>>^ “‘Se ele oferecer como oferta queimada um animal do rebanho, dentre os carneirinhos ou dentre as cabras, deve apresentar um macho sadio.

[[v3-1-11]]

^<<v3-1-11,11>>^ O animal deve ser abatido no lado norte do altar, perante Jeová, e os filhos de Arão, os sacerdotes, aspergirão o sangue em todos os lados do altar.

[[v3-1-12]]

^<<v3-1-12,12>>^ Ele cortará o animal em pedaços, e o sacerdote irá dispô-los, com a cabeça e a gordura,^&#42;1^ em cima da lenha que está no fogo do altar.

[NOTE]
====
. Ou: “a gordura à volta dos rins”.
====

[[v3-1-13]]

^<<v3-1-13,13>>^ Ele lavará os intestinos e as pernas^&#42;1^ com água. O sacerdote apresentará tudo e irá queimá-lo no altar. É uma oferta queimada, uma oferta feita por fogo, de aroma agradável^&#42;2^ para Jeová.

[NOTE]
====
. Isto é, a parte inferior das pernas.
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v3-1-14]]

^<<v3-1-14,14>>^ “‘No entanto, se ele oferecer aves como oferta queimada a Jeová, apresentará a sua oferta dentre as rolas ou dentre os pombos novos.

[[v3-1-15]]

^<<v3-1-15,15>>^ O sacerdote irá apresentá-la no altar. Cortará o pescoço da ave com a unha, e irá queimá-la no altar; mas deixará que o sangue escorra pelo lado do altar.

[[v3-1-16]]

^<<v3-1-16,16>>^ Deve tirar o papo e as penas e lançá-los ao lado do altar, a leste, onde ficam as cinzas.^&#42;1^

[NOTE]
====
. Ou: “cinzas gordurosas”, isto é, cinzas impregnadas da gordura dos sacrifícios.
====

[[v3-1-17]]

^<<v3-1-17,17>>^ Ele abrirá a ave entre as asas, sem a dividir em duas partes. Então, o sacerdote irá queimá-la no altar, sobre a lenha que está no fogo. É uma oferta queimada, uma oferta feita por fogo, de aroma agradável^&#42;1^ para Jeová.

[NOTE]
====
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]