include::./index.adoc[]

[[v3-9-0]]
=== Levítico, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-9-1]]

^<<v3-9-1,1>>^ No oitavo dia, Moisés convocou Arão e os seus filhos, e os anciãos de Israel.

[[v3-9-2]]

^<<v3-9-2,2>>^ Ele disse a Arão: “Pega num bezerro como oferta pelo pecado e num carneiro como oferta queimada, ambos sadios, e apresenta-os perante Jeová.

[[v3-9-3]]

^<<v3-9-3,3>>^ Contudo, dirás aos israelitas: ‘Peguem num bode para a oferta pelo pecado, num bezerro e num carneirinho, ambos de um ano e sadios, para a oferta queimada,

[[v3-9-4]]

^<<v3-9-4,4>>^ num touro e num carneiro para os sacrifícios de participação em comum, a fim de os sacrificar perante Jeová, e numa oferta de cereais misturada com azeite, pois hoje Jeová vos aparecerá.’”

[[v3-9-5]]

^<<v3-9-5,5>>^ Assim, levaram para diante da tenda de reunião aquilo que Moisés tinha ordenado. Então, toda a assembleia se aproximou e ficou de pé perante Jeová.

[[v3-9-6]]

^<<v3-9-6,6>>^ E Moisés disse: “Isto é o que Jeová ordenou que fizessem, para que vos apareça a glória de Jeová.”

[[v3-9-7]]

^<<v3-9-7,7>>^ A seguir, Moisés disse a Arão: “Aproxima-te do altar e apresenta a tua oferta pelo pecado e a tua oferta queimada, e faz expiação por ti mesmo e pela tua casa. Depois, apresenta a oferta do povo e faz expiação por eles, assim como Jeová ordenou.”

[[v3-9-8]]

^<<v3-9-8,8>>^ Arão aproximou-se imediatamente do altar e abateu o bezerro da oferta pelos seus próprios pecados.

[[v3-9-9]]

^<<v3-9-9,9>>^ Então, os filhos de Arão apresentaram-lhe o sangue. Ele mergulhou o dedo no sangue, pô-lo sobre os chifres do altar e derramou o restante do sangue junto à base do altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ Queimou no altar a gordura, os rins e a membrana gordurosa do fígado do animal oferecido como sacrifício pelo pecado, assim como Jeová tinha ordenado a Moisés.

[[v3-9-11]]

^<<v3-9-11,11>>^ E queimou a carne e o couro com fogo, fora do acampamento.

[[v3-9-12]]

^<<v3-9-12,12>>^ Em seguida, abateu a oferta queimada e os filhos de Arão entregaram-lhe o sangue. E ele aspergiu-o em todos os lados do altar.

[[v3-9-13]]

^<<v3-9-13,13>>^ Eles entregaram-lhe os pedaços da oferta queimada juntamente com a cabeça e ele queimou-os no altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ Além disso, lavou os intestinos e as pernas^&#42;1^ do animal, e queimou-os sobre a oferta queimada, no altar.

[NOTE]
====
. Isto é, a parte inferior das pernas.
====

[[v3-9-15]]

^<<v3-9-15,15>>^ Arão apresentou então a oferta do povo: pegou no bode da oferta pelos pecados do povo, abateu-o e fez com ele uma oferta pelo pecado, assim como tinha feito com o primeiro animal.

[[v3-9-16]]

^<<v3-9-16,16>>^ E apresentou a oferta queimada e ofereceu-a segundo o procedimento normal.

[[v3-9-17]]

^<<v3-9-17,17>>^ A seguir, apresentou a oferta de cereais. Encheu a mão com uma porção da oferta e queimou-a no altar, além da oferta queimada da manhã.

[[v3-9-18]]

^<<v3-9-18,18>>^ Depois, abateu o touro e o carneiro do sacrifício de participação em comum, que era para o povo. Então, os filhos de Arão entregaram-lhe o sangue, e ele aspergiu-o em todos os lados do altar.

[[v3-9-19]]

^<<v3-9-19,19>>^ Quanto aos pedaços de gordura do touro, a cauda gorda do carneiro, a gordura que envolve os órgãos internos, os rins e a membrana gordurosa do fígado,

[[v3-9-20]]

^<<v3-9-20,20>>^ eles colocaram todos esses pedaços de gordura sobre o peito dos animais. Depois disso, ele queimou os pedaços de gordura no altar.

[[v3-9-21]]

^<<v3-9-21,21>>^ Todavia, o peito e a perna direita dos animais Arão moveu para a frente e para trás como oferta movida perante Jeová, assim como Moisés tinha ordenado.

[[v3-9-22]]

^<<v3-9-22,22>>^ Então, Arão levantou as mãos para o povo, abençoou-os e desceu depois de ter feito a oferta pelo pecado, a oferta queimada e os sacrifícios de participação em comum.

[[v3-9-23]]

^<<v3-9-23,23>>^ Por fim, Moisés e Arão entraram na tenda de reunião; depois, saíram e abençoaram o povo.
De seguida, a glória de Jeová apareceu a todo o povo,

[[v3-9-24]]

^<<v3-9-24,24>>^ saiu fogo da parte de Jeová e consumiu a oferta queimada e os pedaços de gordura no altar. Quando todo o povo viu isso, começou a gritar e prostrou-se com o rosto por terra.

'''

xref:003-levitico/003-levitico-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-levitico/003-levitico-010.adoc#v3-10-0[Próximo Capítulo &#62;]