include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-3-1]]

^<<v3-3-1,1>>^ “‘Se alguém oferecer um sacrifício de participação em comum^&#42;1^ e se o apresentar dentre a manada, quer seja macho, quer seja fêmea, deve apresentar um animal sadio perante Jeová.

[NOTE]
====
. Ou: “um sacrifício de ofertas de paz”.
====

[[v3-3-2]]

^<<v3-3-2,2>>^ Deve pôr a mão sobre a cabeça da sua oferta e esta será abatida à entrada da tenda de reunião. E os filhos de Arão, os sacerdotes, aspergirão o sangue em todos os lados do altar.

[[v3-3-3]]

^<<v3-3-3,3>>^ Ele apresentará parte do sacrifício de participação em comum como oferta feita por fogo a Jeová: a gordura que envolve os intestinos, toda a gordura que adere aos intestinos,

[[v3-3-4]]

^<<v3-3-4,4>>^ e os dois rins com a gordura que há sobre eles, na região lombar. Ele também removerá a membrana gordurosa do fígado juntamente com os rins.

[[v3-3-5]]

^<<v3-3-5,5>>^ Os filhos de Arão queimarão todas estas coisas no altar, por cima da oferta queimada colocada sobre a lenha que está no fogo. É uma oferta feita por fogo, de aroma agradável^&#42;1^ para Jeová.

[NOTE]
====
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v3-3-6]]

^<<v3-3-6,6>>^ “‘Se a sua oferta a Jeová como sacrifício de participação em comum for dentre o rebanho, apresentará um animal sadio, macho ou fêmea.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se apresentar um carneirinho como oferta, irá apresentá-lo perante Jeová.

[[v3-3-8]]

^<<v3-3-8,8>>^ Porá a mão sobre a cabeça da sua oferta e ela será abatida diante da tenda de reunião. Os filhos de Arão aspergirão o sangue dela em todos os lados do altar.

[[v3-3-9]]

^<<v3-3-9,9>>^ Ele apresentará a gordura do sacrifício de participação em comum como oferta feita por fogo a Jeová. Removerá toda a cauda gorda, perto da espinha, a gordura que envolve os intestinos, toda a gordura que adere aos intestinos,

[[v3-3-10]]

^<<v3-3-10,10>>^ e os dois rins com a gordura que há sobre eles, na região lombar. Também removerá a membrana gordurosa do fígado juntamente com os rins.

[[v3-3-11]]

^<<v3-3-11,11>>^ E o sacerdote queimará todas estas coisas no altar como alimento,^&#42;1^ uma oferta feita por fogo a Jeová.

[NOTE]
====
. Lit.: “pão”, isto é, como a porção do sacrifício de participação em comum que cabe a Deus.
====

[[v3-3-12]]

^<<v3-3-12,12>>^ “‘Se a sua oferta for uma cabra, ele irá apresentá-la perante Jeová.

[[v3-3-13]]

^<<v3-3-13,13>>^ Porá a mão sobre a cabeça da sua oferta e esta será abatida diante da tenda de reunião. E os filhos de Arão terão de aspergir o sangue em todos os lados do altar.

[[v3-3-14]]

^<<v3-3-14,14>>^ A parte que ele apresentará como oferta feita por fogo a Jeová é a gordura que envolve os intestinos, toda a gordura que adere aos intestinos,

[[v3-3-15]]

^<<v3-3-15,15>>^ e os dois rins com a gordura que há sobre eles, na região lombar. Ele também removerá a membrana gordurosa do fígado juntamente com os rins.

[[v3-3-16]]

^<<v3-3-16,16>>^ O sacerdote queimará todas estas coisas no altar como alimento,^&#42;1^ uma oferta feita por fogo, de aroma agradável.^&#42;2^ Toda a gordura pertence a Jeová.

[NOTE]
====
. Lit.: “pão”, isto é, como a porção do sacrifício de participação em comum que cabe a Deus.
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v3-3-17]]

^<<v3-3-17,17>>^ “‘Este é um decreto permanente para todas as vossas gerações, onde quer que morarem: não comam nenhuma gordura nem nenhum sangue.’”

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]