include::./index.adoc[]

[[v3-19-0]]
=== Levítico, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-19-1]]

^<<v3-19-1,1>>^ Jeová continuou a falar com Moisés:

[[v3-19-2]]

^<<v3-19-2,2>>^ “Diz a toda a assembleia de Israel: ‘Devem ser santos, porque eu, Jeová, vosso Deus, sou santo.

[[v3-19-3]]

^<<v3-19-3,3>>^ “‘Cada um de vocês deve respeitar^&#42;1^ a sua mãe e o seu pai, e deve guardar os meus sábados. Eu sou Jeová, vosso Deus.

[NOTE]
====
. Lit.: “temer”.
====

[[v3-19-4]]

^<<v3-19-4,4>>^ Não recorram a deuses que nada valem, nem façam para vocês deuses de metal fundido. Eu sou Jeová, vosso Deus.

[[v3-19-5]]

^<<v3-19-5,5>>^ “‘Se oferecerem a Jeová um sacrifício de participação em comum, devem sacrificá-lo de modo a ganharem aprovação.

[[v3-19-6]]

^<<v3-19-6,6>>^ Deve ser comido no dia em que o sacrificarem e no dia seguinte, mas o que sobrar até ao terceiro dia deve ser queimado no fogo.

[[v3-19-7]]

^<<v3-19-7,7>>^ Contudo, se alguma parte dele for comida no terceiro dia, isso será algo ofensivo; não será aceite.

[[v3-19-8]]

^<<v3-19-8,8>>^ Quem o comer responderá pelo seu erro, porque profanou uma coisa sagrada de Jeová. Essa pessoa^&#42;1^ será eliminada do povo.^&#42;2^

[NOTE]
====
. Ou: “alma”.
. Isto é, será morta.
====

[[v3-19-9]]

^<<v3-19-9,9>>^ “‘Quando for feita a colheita da tua terra, não colhas completamente a extremidade do campo nem apanhes as sobras^&#42;1^ da tua colheita.

[NOTE]
====
. Ou: “a respiga”.
====

[[v3-19-10]]

^<<v3-19-10,10>>^ Além disso, não recolhas as sobras da tua vinha nem apanhes as uvas espalhadas da tua vinha. Deves deixá-las para o pobre^&#42;1^ e para o residente estrangeiro. Eu sou Jeová, teu Deus.

[NOTE]
====
. Ou: “atribulado”.
====

[[v3-19-11]]

^<<v3-19-11,11>>^ “‘Não furtem, não enganem, não sejam falsos uns com os outros.

[[v3-19-12]]

^<<v3-19-12,12>>^ Não jurem falsamente em meu nome, profanando assim o nome do vosso Deus. Eu sou Jeová.

[[v3-19-13]]

^<<v3-19-13,13>>^ Não defraudes o teu próximo nem roubes. Não deves ficar com o salário de um trabalhador contratado toda a noite, até à manhã seguinte.

[[v3-19-14]]

^<<v3-19-14,14>>^ “‘Não amaldiçoes^&#42;1^ um surdo nem ponhas um obstáculo diante de um cego; tem temor do teu Deus. Eu sou Jeová.

[NOTE]
====
. Ou: “Não invoques o mal sobre”.
====

[[v3-19-15]]

^<<v3-19-15,15>>^ “‘Não façam injustiça no julgamento. Não mostres parcialidade a favor do pobre nem favoreças o rico. Deves julgar o teu próximo com justiça.

[[v3-19-16]]

^<<v3-19-16,16>>^ “‘Não andes entre o teu povo a espalhar calúnias. Não te levantes contra a vida^&#42;1^ do teu próximo.^&#42;2^ Eu sou Jeová.

[NOTE]
====
. Lit.: “o sangue”.
. Ou, possivelmente: “Não fiques parado quando a vida do teu próximo está em perigo.”
====

[[v3-19-17]]

^<<v3-19-17,17>>^ “‘Não odeies o teu irmão no coração. Sem falta, deves repreender o teu próximo, para não seres culpado de pecado juntamente com ele.

[[v3-19-18]]

^<<v3-19-18,18>>^ “‘Não te vingues dos filhos do teu povo nem lhes guardes ressentimento. Ama o teu próximo como a ti mesmo. Eu sou Jeová.

[[v3-19-19]]

^<<v3-19-19,19>>^ “‘Vocês devem guardar os meus decretos. Não cruzes dois tipos de animais domésticos. Não semeies dois tipos de sementes no teu campo, nem te vistas com roupa de dois tipos de fios mesclados.

[[v3-19-20]]

^<<v3-19-20,20>>^ “‘Se um homem se deitar com uma mulher e tiver relações com ela, e ela for uma serva prometida a outro homem, mas não tiver sido remida nem tiver recebido liberdade, deve haver punição. No entanto, eles não devem ser mortos, pois ela ainda não tinha sido posta em liberdade.

[[v3-19-21]]

^<<v3-19-21,21>>^ Ele deve trazer a Jeová a sua oferta pela culpa à entrada da tenda de reunião, um carneiro como oferta pela culpa.

[[v3-19-22]]

^<<v3-19-22,22>>^ O sacerdote fará expiação por ele perante Jeová com o carneiro da oferta pela culpa, pelo pecado que cometeu, e ele receberá o perdão pelo pecado que cometeu.

[[v3-19-23]]

^<<v3-19-23,23>>^ “‘Quando vocês entrarem na terra e plantarem qualquer árvore frutífera, considerarão os seus frutos impuros e proibidos.^&#42;1^ Por três anos, estes ser-vos-ão proibidos.^&#42;2^ Não devem ser comidos.

[NOTE]
====
. Lit.: “como o seu prepúcio”.
. Lit.: “incircuncisos”.
====

[[v3-19-24]]

^<<v3-19-24,24>>^ Todavia, no quarto ano, todos os seus frutos se tornarão santos, para que haja alegria perante Jeová.

[[v3-19-25]]

^<<v3-19-25,25>>^ Então, no quinto ano, poderão comer dos seus frutos, e assim acrescentarão os seus frutos à vossa colheita. Eu sou Jeová, vosso Deus.

[[v3-19-26]]

^<<v3-19-26,26>>^ “‘Não comam nada com sangue.
“‘Não procurem presságios,^&#42;1^ nem pratiquem magia.

[NOTE]
====
. Ou: “sinais”.
====

[[v3-19-27]]

^<<v3-19-27,27>>^ “‘Não rapem^&#42;1^ o cabelo dos lados da cabeça, nem aparem a barba de forma a desfigurá-la.

[NOTE]
====
. Ou: “Não aparem; Não cortem”.
====

[[v3-19-28]]

^<<v3-19-28,28>>^ “‘Não façam cortes no corpo por causa de uma pessoa morta,^&#42;1^ nem façam tatuagens. Eu sou Jeová.

[NOTE]
====
. Ou: “uma alma”. Aqui a palavra hebraica néfesh refere-se a uma pessoa morta.
====

[[v3-19-29]]

^<<v3-19-29,29>>^ “‘Não desonres a tua filha por fazeres dela uma prostituta, para que a terra não cometa prostituição e se encha de devassidão.

[[v3-19-30]]

^<<v3-19-30,30>>^ “‘Guardem os meus sábados e tenham reverência^&#42;1^ pelo meu santuário. Eu sou Jeová.

[NOTE]
====
. Ou: “admiração”. Lit.: “temor”.
====

[[v3-19-31]]

^<<v3-19-31,31>>^ “‘Não recorram aos que invocam espíritos nem consultem adivinhos, tornando-vos impuros por meio deles. Eu sou Jeová, vosso Deus.

[[v3-19-32]]

^<<v3-19-32,32>>^ “‘Levanta-te diante do cabelo branco, honra o homem idoso e tem temor do teu Deus. Eu sou Jeová.

[[v3-19-33]]

^<<v3-19-33,33>>^ “‘Se um estrangeiro morar no vosso meio, na vossa terra, não o maltratem.

[[v3-19-34]]

^<<v3-19-34,34>>^ O estrangeiro que mora no vosso meio deve tornar-se para vocês como um israelita. Ama-o como a ti mesmo, pois vocês foram residentes estrangeiros na terra do Egito. Eu sou Jeová, vosso Deus.

[[v3-19-35]]

^<<v3-19-35,35>>^ “‘Não usem medidas desonestas ao medirem o comprimento, o peso ou o volume.

[[v3-19-36]]

^<<v3-19-36,36>>^ Devem usar balanças exatas, pesos exatos, uma medida exata para secos^&#42;1^ e uma medida exata para líquidos.^&#42;2^ Eu sou Jeová, vosso Deus, que vos tirou da terra do Egito.

[NOTE]
====
. Lit.: “uma efa exata”. Veja o Ap. B14.
. Lit.: “um him exato”. Veja o Ap. B14.
====

[[v3-19-37]]

^<<v3-19-37,37>>^ Por isso, guardem todos os meus decretos e todas as minhas decisões judiciais, e cumpram-nos. Eu sou Jeová.’”

'''

xref:003-levitico/003-levitico-018.adoc#v3-18-0[&#60; Capítulo Anterior] | <<v3-19-0,Topo>> | xref:003-levitico/003-levitico-020.adoc#v3-20-0[Próximo Capítulo &#62;]