include::./index.adoc[]

[[v3-24-0]]
=== Levítico, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-24-1]]

^<<v3-24-1,1>>^ Jeová continuou a dizer a Moisés:

[[v3-24-2]]

^<<v3-24-2,2>>^ “Ordena aos israelitas que te tragam azeite puro para a iluminação, para manter as lâmpadas sempre acesas.

[[v3-24-3]]

^<<v3-24-3,3>>^ Arão deve providenciar que as lâmpadas fiquem continuamente acesas diante de Jeová na tenda de reunião, do lado de fora da cortina do Testemunho, desde o anoitecer até à manhã seguinte. É um decreto permanente para todas as vossas gerações.

[[v3-24-4]]

^<<v3-24-4,4>>^ Ele deve manter as lâmpadas do candelabro de ouro puro sempre em ordem perante Jeová.

[[v3-24-5]]

^<<v3-24-5,5>>^ “Pegarás em farinha fina e farás 12 pães em forma de anel. Cada pão deve ter dois décimos de uma efa.^&#42;1^

[NOTE]
====
. Dois décimos de uma efa equivaliam a 4,4 l. Veja o Ap. B14.
====

[[v3-24-6]]

^<<v3-24-6,6>>^ Irás colocá-los em duas pilhas sobre a mesa de ouro puro perante Jeová, cada pilha com seis pães.

[[v3-24-7]]

^<<v3-24-7,7>>^ Deves pôr olíbano puro sobre cada pilha; este servirá como representação da oferta inteira de pães;^&#42;1^ será uma oferta feita por fogo a Jeová.

[NOTE]
====
. Ou: “como porção memorial da oferta”.
====

[[v3-24-8]]

^<<v3-24-8,8>>^ Em cada dia de sábado, ele deve colocar os pães em ordem perante Jeová regularmente. É um pacto permanente com os israelitas.

[[v3-24-9]]

^<<v3-24-9,9>>^ Serão de Arão e dos seus filhos, e eles irão comê-los num lugar santo, porque são uma porção santíssima que lhe pertence das ofertas feitas por fogo a Jeová. É um decreto permanente.”

[[v3-24-10]]

^<<v3-24-10,10>>^ Entre os israelitas, havia um filho de uma israelita e de um egípcio, e houve uma briga entre ele e um israelita no acampamento.

[[v3-24-11]]

^<<v3-24-11,11>>^ O filho da israelita começou a insultar o Nome^&#42;1^ e a amaldiçoá-lo. Por isso, levaram-no a Moisés. A propósito, a sua mãe era Selomite, filha de Dibri, da tribo de Dã.

[NOTE]
====
. Isto é, o nome Jeová, conforme indicado pelos vv. 15 e 16.
====

[[v3-24-12]]

^<<v3-24-12,12>>^ Puseram-no em detenção até que a decisão de Jeová lhes fosse revelada.

[[v3-24-13]]

^<<v3-24-13,13>>^ Então, Jeová disse a Moisés:

[[v3-24-14]]

^<<v3-24-14,14>>^ “Leva para fora do acampamento aquele que proferiu a maldição, e todos os que o ouviram porão as mãos sobre a cabeça dele, e toda a assembleia o apedrejará.

[[v3-24-15]]

^<<v3-24-15,15>>^ E deves dizer aos israelitas: ‘Se algum homem amaldiçoar o seu Deus, responderá pelo seu pecado.

[[v3-24-16]]

^<<v3-24-16,16>>^ Assim, quem insultar o nome de Jeová, sem falta, deve ser morto. Toda a assembleia, sem falta, deve apedrejá-lo. O residente estrangeiro, assim como o israelita, deve ser morto por insultar o Nome.

[[v3-24-17]]

^<<v3-24-17,17>>^ “‘Se um homem tirar uma vida humana,^&#42;1^ sem falta, deve ser morto.

[NOTE]
====
. Ou: “golpear fatalmente qualquer alma humana”.
====

[[v3-24-18]]

^<<v3-24-18,18>>^ Quem ferir e matar um animal doméstico^&#42;1^ deve dar compensação por ele, vida por vida.^&#42;2^

[NOTE]
====
. Ou: “E quem golpear fatalmente a alma de um animal”.
. Ou: “alma por alma”.
====

[[v3-24-19]]

^<<v3-24-19,19>>^ Se um homem ferir o seu próximo, o que ele fez deverá ser-lhe feito a ele.

[[v3-24-20]]

^<<v3-24-20,20>>^ Fratura por fratura, olho por olho, dente por dente; o mesmo tipo de ferimento que ele causar é o que se deve causar a ele.

[[v3-24-21]]

^<<v3-24-21,21>>^ Quem ferir e matar um animal deve dar compensação por ele, mas quem ferir e matar um homem deve ser morto.

[[v3-24-22]]

^<<v3-24-22,22>>^ “‘Uma só decisão judicial vos será aplicada, tanto ao residente estrangeiro como ao israelita, porque eu sou Jeová, vosso Deus.’”

[[v3-24-23]]

^<<v3-24-23,23>>^ Moisés falou então com os israelitas, e eles levaram para fora do acampamento aquele que tinha proferido a maldição e apedrejaram-no. Desse modo, os israelitas fizeram assim como Jeová tinha ordenado a Moisés.

'''

xref:003-levitico/003-levitico-023.adoc#v3-23-0[&#60; Capítulo Anterior] | <<v3-24-0,Topo>> | xref:003-levitico/003-levitico-025.adoc#v3-25-0[Próximo Capítulo &#62;]