include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-25-1]]

^<<v3-25-1,1>>^ Jeová disse ainda a Moisés no monte Sinai:

[[v3-25-2]]

^<<v3-25-2,2>>^ “Diz aos israelitas: ‘Quando por fim entrarem na terra que vos dou, a terra guardará um sábado para Jeová.

[[v3-25-3]]

^<<v3-25-3,3>>^ Durante seis anos, deves semear o teu campo, e, durante seis anos, deves podar as tuas vinhas, e colherás os produtos da terra.

[[v3-25-4]]

^<<v3-25-4,4>>^ Contudo, o sétimo ano deve ser um sábado de completo descanso para a terra, um sábado para Jeová. Não deves semear o teu campo, nem podar as tuas vinhas.

[[v3-25-5]]

^<<v3-25-5,5>>^ Não deves colher o que crescer espontaneamente dos grãos caídos durante a última colheita, nem as uvas da tua videira não podada. Deve haver um ano de completo descanso para a terra.

[[v3-25-6]]

^<<v3-25-6,6>>^ No entanto, poderão comer o alimento que a terra produzir durante o sábado. Tu, o teu escravo, a tua escrava, o teu trabalhador contratado e os colonos que moram no teu meio poderão comê-lo.

[[v3-25-7]]

^<<v3-25-7,7>>^ Os animais domésticos e os animais selvagens que há na tua terra também o poderão comer. Podem comer tudo o que a terra produzir.

[[v3-25-8]]

^<<v3-25-8,8>>^ “‘Contarás sete anos sabáticos, sete vezes sete anos, e os dias dos sete anos sabáticos somarão 49 anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então, vocês farão a buzina soar alto no sétimo mês, no dia dez do mês; no Dia da Expiação, devem fazer com que o som da buzina seja ouvido em toda a vossa terra.

[[v3-25-10]]

^<<v3-25-10,10>>^ Santifiquem o quinquagésimo ano e proclamem liberdade na vossa terra, a todos os habitantes. Esse ano irá tornar-se um jubileu para vocês, e cada um retornará à sua propriedade, e cada um retornará à sua família.

[[v3-25-11]]

^<<v3-25-11,11>>^ O quinquagésimo ano irá tornar-se um jubileu para vocês. Não semearão, nem colherão o que crescer espontaneamente dos grãos caídos na terra, nem colherão as uvas das videiras não podadas.

[[v3-25-12]]

^<<v3-25-12,12>>^ Pois é um jubileu. Deve ser sagrado para vocês. Só podem comer do que a terra produzir espontaneamente.

[[v3-25-13]]

^<<v3-25-13,13>>^ “‘No ano do jubileu, cada um deve retornar à sua propriedade.

[[v3-25-14]]

^<<v3-25-14,14>>^ Se venderem alguma coisa ao vosso próximo, ou se lhe comprarem alguma coisa, não se explorem um ao outro.

[[v3-25-15]]

^<<v3-25-15,15>>^ O que comprares ao teu próximo será avaliado de acordo com o número de anos decorridos desde o jubileu; o que ele te vender será avaliado de acordo com o número de anos das safras que ainda restarem.

[[v3-25-16]]

^<<v3-25-16,16>>^ Se ainda restarem muitos anos, ele poderá aumentar o preço, e, se restarem poucos anos, deve reduzir o preço, porque é o número de safras a serem produzidas que ele te está a vender.

[[v3-25-17]]

^<<v3-25-17,17>>^ Ninguém no vosso meio deve explorar o seu próximo. Tem temor do teu Deus, pois eu sou Jeová, o vosso Deus.

[[v3-25-18]]

^<<v3-25-18,18>>^ Por cumprirem os meus decretos e guardarem as minhas decisões judiciais, morarão em segurança na terra.

[[v3-25-19]]

^<<v3-25-19,19>>^ A terra dará os seus frutos, e vocês comerão à vontade e morarão nela em segurança.

[[v3-25-20]]

^<<v3-25-20,20>>^ “‘Contudo, se disserem: “O que comeremos no sétimo ano, se não podemos semear, nem recolher as nossas safras?”,

[[v3-25-21]]

^<<v3-25-21,21>>^ saibam que vos enviarei a minha bênção no sexto ano, e a terra dará uma safra suficiente para três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ Então, vocês semearão no oitavo ano e comerão da safra antiga até ao nono ano. Comerão da safra antiga até à chegada dessa safra.

[[v3-25-23]]

^<<v3-25-23,23>>^ “‘A terra não deve ser vendida definitivamente, porque a terra é minha. Pois, do meu ponto de vista, vocês são residentes estrangeiros e colonos.

[[v3-25-24]]

^<<v3-25-24,24>>^ Em toda a terra que vos pertence devem conceder o direito de resgate da terra.

[[v3-25-25]]

^<<v3-25-25,25>>^ “‘Se o teu irmão ficar pobre e tiver de vender parte da sua propriedade, um resgatador que seja seu parente próximo deve vir e resgatar o que o teu irmão vendeu.

[[v3-25-26]]

^<<v3-25-26,26>>^ Se alguém não tiver resgatador, mas se tornar próspero e obtiver recursos para a resgatar,

[[v3-25-27]]

^<<v3-25-27,27>>^ deve calcular o valor correspondente aos anos que se passaram desde que a vendeu e devolverá a diferença ao homem que a comprou. Então, ele poderá retornar à sua propriedade.

[[v3-25-28]]

^<<v3-25-28,28>>^ “‘Mas, se ele não obtiver recursos para realizar o resgate, o que ele vendeu continuará com o comprador até ao ano do jubileu e ser-lhe-á devolvido no jubileu, e ele retornará à sua propriedade.

[[v3-25-29]]

^<<v3-25-29,29>>^ “‘Se um homem vender uma casa numa cidade com muralhas, o seu direito de a resgatar vigorará até se completar um ano desde a sua venda. O direito de a resgatar vigorará durante um ano inteiro.

[[v3-25-30]]

^<<v3-25-30,30>>^ Mas, se não for resgatada dentro do prazo de um ano inteiro, a casa que está na cidade com muralhas irá tornar-se propriedade permanente do seu comprador por todas as suas gerações. Não deve ser devolvida no jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ No entanto, as casas dos povoados sem muralhas devem ser consideradas como parte dos campos do país. O direito de resgate da casa deve continuar a vigorar e esta deve ser devolvida no jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ “‘Quanto às casas dos levitas nas suas cidades, os levitas terão o direito permanente de as resgatar.

[[v3-25-33]]

^<<v3-25-33,33>>^ Se um levita não resgatar a casa que vendeu, essa casa que vendeu na cidade que lhes pertence será devolvida no jubileu, porque as casas das cidades dos levitas são propriedade deles entre os israelitas.

[[v3-25-34]]

^<<v3-25-34,34>>^ Além disso, os campos de pastagem ao redor das suas cidades não podem ser vendidos, pois são propriedade permanente deles.

[[v3-25-35]]

^<<v3-25-35,35>>^ “‘Se o teu irmão que mora no teu meio ficar pobre e não se conseguir sustentar, terás de o ajudar como farias com um residente estrangeiro ou com um colono, para que continue vivo no vosso meio.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não lhe cobres juros, nem obtenhas lucro^&#42;1^ dele. Tem temor do teu Deus, e o teu irmão ficará vivo no vosso meio.

[NOTE]
====
. Ou: “nem cobres usura”.
====

[[v3-25-37]]

^<<v3-25-37,37>>^ Não lhe emprestes dinheiro a juros, nem lhe dês comida visando o lucro.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou Jeová, vosso Deus, que vos tirou da terra do Egito para vos dar a terra de Canaã, para ser o vosso Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ “‘Se o teu irmão que mora no teu meio ficar pobre e tiver de se vender a ti, não o forces a trabalhar como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Deve ser tratado como um trabalhador contratado, como um colono. Deve servir-te até ao ano do jubileu.

[[v3-25-41]]

^<<v3-25-41,41>>^ Depois, ele partirá, juntamente com os seus filhos, e retornará à sua família. Deve voltar à propriedade dos seus antepassados.

[[v3-25-42]]

^<<v3-25-42,42>>^ Pois eles são meus escravos, que tirei da terra do Egito. Não se devem vender assim como se vende um escravo.

[[v3-25-43]]

^<<v3-25-43,43>>^ Não o trates com crueldade; tem temor do teu Deus.

[[v3-25-44]]

^<<v3-25-44,44>>^ O teu escravo e a tua escrava devem vir das nações que há à vossa volta. Delas podem comprar um escravo ou uma escrava.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também podem comprar escravos dentre os filhos dos colonos que moram no vosso meio — dentre eles e dentre as famílias que eles formaram na vossa terra —, e eles irão tornar-se vossa propriedade.

[[v3-25-46]]

^<<v3-25-46,46>>^ Poderão dá-los aos vossos filhos como herança, como propriedade a ser herdada permanentemente. Podem usá-los como trabalhadores, mas não sujeitem os vossos irmãos israelitas a tratamento cruel.

[[v3-25-47]]

^<<v3-25-47,47>>^ “‘Mas, se um residente estrangeiro ou um colono no teu meio enriquecer, e o teu irmão israelita que vive no teu meio ficar pobre e tiver de se vender ao residente estrangeiro ou ao colono, ou a um membro da família do residente estrangeiro,

[[v3-25-48]]

^<<v3-25-48,48>>^ ele continuará a ter o direito de ser resgatado depois de se ter vendido. Um dos seus irmãos pode resgatá-lo,

[[v3-25-49]]

^<<v3-25-49,49>>^ ou o seu tio ou o filho do seu tio pode resgatá-lo, ou qualquer parente próximo,^&#42;1^ alguém da sua família, pode resgatá-lo.
“‘Ou, se ele mesmo tiver enriquecido, pode resgatar-se a si mesmo.

[NOTE]
====
. Ou: “parente consanguíneo”.
====

[[v3-25-50]]

^<<v3-25-50,50>>^ Deve calcular com aquele que o comprou o tempo desde o ano em que se vendeu a ele até ao ano do jubileu, e o preço de venda corresponderá ao número de anos. O valor dos seus dias de trabalho durante esse tempo será calculado com base no salário de um trabalhador contratado.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se faltarem muitos anos, ele deve pagar o resgate proporcional aos anos que ainda restarem.

[[v3-25-52]]

^<<v3-25-52,52>>^ Contudo, se restarem apenas alguns anos até ao ano do jubileu, deve fazer para si um cálculo e pagar um resgate proporcional aos anos restantes.

[[v3-25-53]]

^<<v3-25-53,53>>^ Ele deve servir ao comprador como trabalhador contratado ano após ano, e não deves permitir que o comprador o trate com crueldade.

[[v3-25-54]]

^<<v3-25-54,54>>^ No entanto, se ele não puder resgatar-se a si mesmo nestes termos, será libertado no ano do jubileu, ele e os seus filhos.

[[v3-25-55]]

^<<v3-25-55,55>>^ “‘Pois os israelitas são meus escravos. Eles são os meus escravos, que tirei da terra do Egito. Eu sou Jeová, vosso Deus.

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]