include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-20-1]]

^<<v3-20-1,1>>^ Jeová disse a Moisés:

[[v3-20-2]]

^<<v3-20-2,2>>^ “Deves dizer aos israelitas: ‘Qualquer homem de Israel ou qualquer estrangeiro que mora em Israel que der um dos seus descendentes a Moloque, sem falta, deve ser morto. O povo da terra deve apedrejá-lo até à morte.

[[v3-20-3]]

^<<v3-20-3,3>>^ Eu mesmo me voltarei^&#42;1^ contra esse homem, e vou eliminá-lo dentre o povo,^&#42;2^ porque deu um dos seus descendentes a Moloque, profanou o meu lugar santo e profanou o meu santo nome.

[NOTE]
====
. Lit.: “porei a minha face”.
. Isto é, vou matá-lo.
====

[[v3-20-4]]

^<<v3-20-4,4>>^ Se o povo da terra fechar deliberadamente os olhos à ação desse homem, quando ele der um descendente a Moloque, e não o matarem,

[[v3-20-5]]

^<<v3-20-5,5>>^ então, certamente, eu mesmo me voltarei^&#42;1^ contra esse homem e a sua família. Eliminarei dentre o povo^&#42;2^ tanto a ele como a todos os que se juntarem a ele em se prostituírem a Moloque.

[NOTE]
====
. Lit.: “porei a minha face”.
. Isto é, matarei.
====

[[v3-20-6]]

^<<v3-20-6,6>>^ “‘Quanto à pessoa^&#42;1^ que recorrer aos que invocam espíritos e aos adivinhos, por cometer prostituição espiritual com eles, eu certamente me voltarei contra essa pessoa^&#42;2^ e vou eliminá-la dentre o povo.^&#42;3^

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
. Isto é, vou matá-la.
====

[[v3-20-7]]

^<<v3-20-7,7>>^ “‘Santifiquem-se e tornem-se santos, porque eu sou Jeová, vosso Deus.

[[v3-20-8]]

^<<v3-20-8,8>>^ Guardem os meus decretos e cumpram-nos. Eu sou Jeová, que vos santifico.

[[v3-20-9]]

^<<v3-20-9,9>>^ “‘Se houver um homem que amaldiçoe^&#42;1^ o seu pai ou a sua mãe, sem falta, deve ser morto. Visto que amaldiçoou o seu pai ou a sua mãe, o seu próprio sangue está sobre ele.

[NOTE]
====
. Ou: “invoque o mal sobre”.
====

[[v3-20-10]]

^<<v3-20-10,10>>^ “‘O homem que cometer adultério com a esposa de outro homem, sim, aquele que cometer adultério com a esposa do seu próximo, sem falta, deve ser morto, tanto o adúltero como a adúltera.

[[v3-20-11]]

^<<v3-20-11,11>>^ O homem que tem relações sexuais com a esposa do seu pai expõe o pai à vergonha.^&#42;1^ Sem falta, ambos devem ser mortos. O seu próprio sangue está sobre eles.

[NOTE]
====
. Lit.: “expõe a nudez do pai”.
====

[[v3-20-12]]

^<<v3-20-12,12>>^ Se um homem tem relações sexuais com a sua nora, sem falta, ambos devem ser mortos. Violaram aquilo que é natural. O seu próprio sangue está sobre eles.

[[v3-20-13]]

^<<v3-20-13,13>>^ “‘Se um homem tem relações sexuais com outro homem, assim como se tem relações com uma mulher, ambos fazem algo detestável. Sem falta, devem ser mortos. O seu próprio sangue está sobre eles.

[[v3-20-14]]

^<<v3-20-14,14>>^ “‘Se um homem toma uma mulher e a mãe dela, isso é um ato obsceno.^&#42;1^ Tanto ele como elas devem ser queimados no fogo, para que a conduta obscena não continue no vosso meio.

[NOTE]
====
. Ou: “conduta vergonhosa; indecência”.
====

[[v3-20-15]]

^<<v3-20-15,15>>^ “‘Se um homem tiver relações sexuais com um animal, sem falta, ele deve ser morto, e vocês devem matar o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ Se uma mulher se aproximar de algum animal para ter relações sexuais, matem a mulher e o animal. Sem falta devem ser mortos. O seu próprio sangue está sobre eles.

[[v3-20-17]]

^<<v3-20-17,17>>^ “‘Se um homem tem relações sexuais com a sua irmã, a filha do seu pai ou da sua mãe, e vê a nudez dela, e ela vê a nudez dele, é algo vergonhoso. Eles serão eliminados^&#42;1^ diante dos olhos dos filhos do seu povo. Ele expôs a sua irmã à vergonha.^&#42;2^ Deve responder pelo seu erro.

[NOTE]
====
. Ou: “mortos”.
. Lit.: “expôs a nudez da sua irmã”.
====

[[v3-20-18]]

^<<v3-20-18,18>>^ “‘Se um homem se deita com uma mulher menstruada e tem relações sexuais com ela, tanto ele como ela expuseram o fluxo de sangue dela. Ambos serão eliminados dentre o povo.^&#42;1^

[NOTE]
====
. Isto é, serão mortos.
====

[[v3-20-19]]

^<<v3-20-19,19>>^ “‘Não tenhas relações sexuais com a irmã da tua mãe nem com a irmã do teu pai, porque isso exporia uma parente consanguínea à vergonha. Ambos devem responder pelo seu erro.

[[v3-20-20]]

^<<v3-20-20,20>>^ O homem que tem relações sexuais com a esposa do seu tio expõe o tio à vergonha.^&#42;1^ Eles devem responder pelo seu pecado. Devem morrer sem filhos.

[NOTE]
====
. Lit.: “expõe a nudez do seu tio”.
====

[[v3-20-21]]

^<<v3-20-21,21>>^ Se um homem toma a esposa do seu irmão, isso é algo abominável. Ele expôs o seu irmão à vergonha.^&#42;1^ Devem ficar sem filhos.

[NOTE]
====
. Lit.: “expôs a nudez do seu irmão”.
====

[[v3-20-22]]

^<<v3-20-22,22>>^ “‘Guardem todos os meus decretos e todas as minhas decisões judiciais, e cumpram-nos, para que não sejam vomitados pela terra à qual vos levo para lá morarem.

[[v3-20-23]]

^<<v3-20-23,23>>^ Não andem nos decretos das nações que expulso da vossa frente, pois elas fizeram todas estas coisas, e eu abomino-as.

[[v3-20-24]]

^<<v3-20-24,24>>^ Por isso, eu disse-vos: “Tomarão posse da terra delas, e eu vou dar-vos a terra como vossa propriedade — uma terra que mana leite e mel. Eu sou Jeová, vosso Deus, que vos separei dos outros povos.”

[[v3-20-25]]

^<<v3-20-25,25>>^ Façam distinção entre o animal puro e o impuro, e entre a ave impura e a pura. Não se tornem^&#42;1^ repugnantes por meio dos animais, das aves e das coisas que rastejam sobre o solo, os quais separei para que os considerem impuros.

[NOTE]
====
. Ou: “Não tornem as vossas almas”.
====

[[v3-20-26]]

^<<v3-20-26,26>>^ Sejam santos para mim, porque eu, Jeová, sou santo; e estou a separar-vos dos outros povos para se tornarem meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ “‘Qualquer homem ou mulher que invocar espíritos ou que for adivinho,^&#42;1^ sem falta, deve ser morto. O povo deve apedrejá-los até à morte. O próprio sangue deles está sobre eles.’”

[NOTE]
====
. Ou: “que tiver um espírito de predição”.
====

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]