include::./index.adoc[]

[[v3-16-0]]
=== Levítico, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v3-16-1]]

^<<v3-16-1,1>>^ Jeová falou com Moisés depois da morte dos dois filhos de Arão que morreram por se terem aproximado de Jeová.

[[v3-16-2]]

^<<v3-16-2,2>>^ Jeová disse a Moisés: “Diz ao teu irmão Arão que ele não pode entrar a qualquer hora no lugar santo, atrás da cortina, diante da tampa sobre a Arca, para que não morra, pois aparecerei numa nuvem por cima da tampa.

[[v3-16-3]]

^<<v3-16-3,3>>^ “Isto é o que Arão deve trazer ao entrar no lugar santo: um novilho como oferta pelo pecado e um carneiro como oferta queimada.

[[v3-16-4]]

^<<v3-16-4,4>>^ Deve usar a veste sagrada de linho, e os calções^&#42;1^ de linho devem cobrir a sua nudez.^&#42;2^ Deve atar a faixa de linho à cintura e enrolar o turbante de linho na cabeça. São vestes sagradas. Ele irá banhar-se em água e vesti-las.

[NOTE]
====
. Ou: “a roupa interior”.
. Ou: “a carne que está exposta”.
====

[[v3-16-5]]

^<<v3-16-5,5>>^ “Deve receber da assembleia de Israel dois cabritos como oferta pelo pecado e um carneiro como oferta queimada.

[[v3-16-6]]

^<<v3-16-6,6>>^ “Então, Arão terá de apresentar o novilho da oferta pelos seus próprios pecados, e fará expiação por si mesmo e pela sua casa.

[[v3-16-7]]

^<<v3-16-7,7>>^ “Ele pegará então nos dois bodes e fará com que fiquem perante Jeová, à entrada da tenda de reunião.

[[v3-16-8]]

^<<v3-16-8,8>>^ Arão lançará sortes sobre os dois bodes, uma sorte para Jeová e a outra sorte para Azazel.^&#42;1^

[NOTE]
====
. Que possivelmente significa “bode que desaparece”.
====

[[v3-16-9]]

^<<v3-16-9,9>>^ Arão apresentará o bode que for designado por sorte para Jeová e fará dele uma oferta pelo pecado.

[[v3-16-10]]

^<<v3-16-10,10>>^ Mas o bode designado por sorte para Azazel deve ser trazido vivo perante Jeová para se fazer expiação sobre ele, a fim de que seja enviado para o deserto, para Azazel.

[[v3-16-11]]

^<<v3-16-11,11>>^ “Arão apresentará o novilho da oferta pelos seus próprios pecados e fará expiação por si mesmo e pela sua casa. Então, abaterá o novilho da oferta pelos seus próprios pecados.

[[v3-16-12]]

^<<v3-16-12,12>>^ “Pegará então no incensário cheio de brasas tiradas do altar, que está perante Jeová, e em dois punhados de incenso perfumado em pó, e irá levá-los para trás da cortina.

[[v3-16-13]]

^<<v3-16-13,13>>^ Porá o incenso sobre as brasas perante Jeová e a nuvem do incenso envolverá a tampa da Arca do Testemunho, para que ele não morra.

[[v3-16-14]]

^<<v3-16-14,14>>^ “E pegará num pouco do sangue do novilho e irá aspergi-lo com o dedo em frente à tampa, no lado leste. Aspergirá um pouco do sangue com o dedo sete vezes diante da tampa.

[[v3-16-15]]

^<<v3-16-15,15>>^ “Ele abaterá então o bode da oferta pelo pecado do povo. Levará o sangue para trás da cortina e fará com o sangue o mesmo que fez com o sangue do novilho; ele deve aspergi-lo em direção à tampa, diante da tampa.

[[v3-16-16]]

^<<v3-16-16,16>>^ “Ele terá de fazer expiação pelo lugar santo por causa das impurezas cometidas pelos israelitas e por causa das transgressões e dos pecados deles; isso é o que ele deve fazer pela tenda de reunião, que fica entre eles, no meio dos seus atos impuros.

[[v3-16-17]]

^<<v3-16-17,17>>^ “Nenhum outro homem deve estar na tenda de reunião desde a hora em que ele entra para fazer expiação no lugar santo até à hora em que ele sai. Ele fará expiação por si mesmo, pela sua casa e por toda a congregação de Israel.

[[v3-16-18]]

^<<v3-16-18,18>>^ “Então, ele terá de sair e dirigir-se ao altar, que está perante Jeová, e fazer expiação pelo altar. Pegará num pouco do sangue do novilho e do sangue do bode e irá colocá-lo sobre os chifres do altar em todos os lados.

[[v3-16-19]]

^<<v3-16-19,19>>^ Também aspergirá um pouco do sangue com o dedo sete vezes sobre o altar e irá purificá-lo e santificá-lo dos atos impuros dos israelitas.

[[v3-16-20]]

^<<v3-16-20,20>>^ “Quando tiver acabado de fazer expiação pelo lugar santo, pela tenda de reunião e pelo altar, ele apresentará o bode vivo.

[[v3-16-21]]

^<<v3-16-21,21>>^ Arão porá ambas as mãos sobre a cabeça do bode vivo e confessará sobre ele todos os erros dos israelitas, todas as transgressões e todos os pecados deles. Ele irá pô-los sobre a cabeça do bode e enviá-lo para o deserto pela mão de um homem designado para isso.^&#42;1^

[NOTE]
====
. Ou: “um homem que está de prontidão”.
====

[[v3-16-22]]

^<<v3-16-22,22>>^ O bode levará sobre si todos os erros deles para uma região desabitada. Ele enviará o bode para o deserto.

[[v3-16-23]]

^<<v3-16-23,23>>^ “Arão entrará então na tenda de reunião e tirará as vestes de linho que pôs para entrar no lugar santo, e ali as deixará.

[[v3-16-24]]

^<<v3-16-24,24>>^ Terá de se banhar^&#42;1^ em água num lugar santo e pôr as vestes. Depois, sairá e oferecerá a sua oferta queimada e a oferta queimada do povo, fazendo expiação por si mesmo e pelo povo.

[NOTE]
====
. Lit.: “de banhar a sua carne”.
====

[[v3-16-25]]

^<<v3-16-25,25>>^ Ele queimará a gordura da oferta pelo pecado no altar.

[[v3-16-26]]

^<<v3-16-26,26>>^ “O homem que enviou o bode para Azazel deve lavar a sua roupa e banhar-se em água. Depois, poderá entrar no acampamento.

[[v3-16-27]]

^<<v3-16-27,27>>^ “E o novilho da oferta pelo pecado e o bode da oferta pelo pecado, cujo sangue foi levado para dentro do lugar santo a fim de fazer expiação, serão levados para fora do acampamento. A pele, a carne e o excremento desses animais serão queimados no fogo.

[[v3-16-28]]

^<<v3-16-28,28>>^ Aquele que os queimar deve lavar a sua roupa e banhar-se em água. Depois, poderá entrar no acampamento.

[[v3-16-29]]

^<<v3-16-29,29>>^ “Isto irá servir-vos de decreto permanente: no sétimo mês, no dia dez do mês, devem afligir-se a vocês mesmos^&#42;1^ e não devem fazer nenhum trabalho, quer o israelita, quer o estrangeiro que mora no vosso meio.

[NOTE]
====
. Ou: “afligir a vossa alma”. Entende-se que, em geral, a expressão “afligir-se a si mesmo” refere-se a várias formas de abnegação, incluindo o jejum.
====

[[v3-16-30]]

^<<v3-16-30,30>>^ Nesse dia, irá fazer-se expiação por vocês, para vos declarar puros. Ficarão puros de todos os vossos pecados perante Jeová.

[[v3-16-31]]

^<<v3-16-31,31>>^ É um sábado de completo descanso para vocês e devem afligir-se a vocês mesmos.^&#42;1^ É um decreto permanente.

[NOTE]
====
. Ou: “ afligir a vossa alma”.
====

[[v3-16-32]]

^<<v3-16-32,32>>^ “O sacerdote que for ungido e ordenado^&#42;1^ para servir como sacerdote no lugar do seu pai fará expiação e usará as vestes de linho, as vestes sagradas.

[NOTE]
====
. Lit.: “cuja mão for enchida”.
====

[[v3-16-33]]

^<<v3-16-33,33>>^ Ele fará expiação pelo santuário sagrado, pela tenda de reunião e pelo altar; e fará expiação pelos sacerdotes e por todo o povo da congregação.

[[v3-16-34]]

^<<v3-16-34,34>>^ Isto irá servir-vos de decreto permanente, para se fazer expiação pelos israelitas, uma vez por ano, por causa de todos os seus pecados.”
E ele fez assim como Jeová tinha ordenado a Moisés.

'''

xref:003-levitico/003-levitico-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-levitico/003-levitico-017.adoc#v3-17-0[Próximo Capítulo &#62;]