include::./index.adoc[]

[[v28-4-0]]
=== Oseias, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-4-1]]

^<<v28-4-1,1>>^ Ouçam a palavra de Jeová, ó povo de Israel,
Pois Jeová tem uma causa contra os habitantes desta terra,
Porque não há verdade, nem amor leal, nem conhecimento de Deus nesta terra.

[[v28-4-2]]

^<<v28-4-2,2>>^ Juramentos falsos, mentiras, assassinatos,
Roubos e adultérios espalharam-se;
E há atos de derramamento de sangue, um após outro.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso, esta terra ficará de luto,
E todos os seus habitantes hão de definhar-se;
Os animais selvagens, as aves dos céus
E até os peixes do mar morrerão.

[[v28-4-4]]

^<<v28-4-4,4>>^ “No entanto, que ninguém discuta nem repreenda,
Pois o teu povo é como os que discutem com um sacerdote.

[[v28-4-5]]

^<<v28-4-5,5>>^ Por isso, tropeçarás em plena luz do dia,
E o profeta tropeçará contigo como se fosse noite.
E silenciarei^&#42;1^ a tua mãe.

[NOTE]
====
. Ou: “destruirei”.
====

[[v28-4-6]]

^<<v28-4-6,6>>^ O meu povo será silenciado,^&#42;1^ pois não há conhecimento.
Visto que rejeitaste o conhecimento,
Eu também te rejeitarei, para que deixes de servir como meu sacerdote;
E, visto que te esqueceste da lei^&#42;2^ do teu Deus,
Eu também me esquecerei dos teus filhos.

[NOTE]
====
. Ou: “destruído”.
. Ou: “instrução”.
====

[[v28-4-7]]

^<<v28-4-7,7>>^ Quanto mais aumentavam em número, mais pecavam contra mim.
Transformarei a glória deles em desonra.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Trocaram a minha própria glória pela desonra.”
====

[[v28-4-8]]

^<<v28-4-8,8>>^ Eles alimentam-se do pecado do meu povo,
E anseiam pelo^&#42;1^ seu erro.

[NOTE]
====
. Ou: “elevam a sua alma ao”. Veja o Glossário, “Alma”.
====

[[v28-4-9]]

^<<v28-4-9,9>>^ Acontecerá o mesmo ao povo e ao sacerdote;
Ajustarei contas com eles por causa dos seus caminhos,
E farei com que sofram as consequências das suas ações.

[[v28-4-10]]

^<<v28-4-10,10>>^ Eles comerão, mas não ficarão satisfeitos.
Serão promíscuos,^&#42;1^ mas não aumentarão em número,
Porque não fizeram caso de Jeová.

[NOTE]
====
. Ou: “Serão crassamente imorais; Eles irão prostituir-se”.
====

[[v28-4-11]]

^<<v28-4-11,11>>^ A prostituição,^&#42;1^ o vinho e o vinho novo
Tiram a motivação para fazer o que é certo.^&#42;2^

[NOTE]
====
. Ou: “imoralidade; promiscuidade”.
. Lit.: “Tiram coração”.
====

[[v28-4-12]]

^<<v28-4-12,12>>^ O meu povo consulta ídolos de madeira,
E faz o que o seu bastão^&#42;1^ lhes diz;
Pois o espírito de prostituição^&#42;2^ faz com que se desviem
E, por causa da sua prostituição,^&#42;3^ recusam-se a sujeitar-se ao seu Deus.

[NOTE]
====
. Ou: “a sua vara de adivinhação”.
. Ou: “imoralidade; promiscuidade”.
. Ou: “imoralidade; promiscuidade”.
====

[[v28-4-13]]

^<<v28-4-13,13>>^ Oferecem sacrifícios nos cumes dos montes
E queimam sacrifícios nas colinas,
Debaixo do carvalho, do estoraque e de toda a árvore grande,
Porque a sua sombra é boa.
É por isso que as suas filhas se prostituem^&#42;1^
E as suas noras cometem adultério.

[NOTE]
====
. Ou: “se envolvem em imoralidade (promiscuidade)”.
====

[[v28-4-14]]

^<<v28-4-14,14>>^ Não ajustarei contas com as vossas filhas por se prostituírem^&#42;1^
Nem com as vossas noras por cometerem adultério,
Pois os homens retiram-se com as prostitutas
E oferecem sacrifícios com as prostitutas de templo.
Um povo assim, sem entendimento, será arruinado.

[NOTE]
====
. Ou: “se envolverem em imoralidade (promiscuidade)”.
====

[[v28-4-15]]

^<<v28-4-15,15>>^ Embora te prostituas,^&#42;1^ Israel,
Que Judá não se torne culpado.
Não vão a Gilgal nem a Bete-Áven,
Nem jurem: ‘Tão certo como Jeová vive!’

[NOTE]
====
. Ou: “te envolvas em imoralidade (promiscuidade)”.
====

[[v28-4-16]]

^<<v28-4-16,16>>^ Pois Israel ficou tão obstinado como uma vaca teimosa.
Será que, agora, Jeová os pastoreará como a um carneirinho em campo aberto?^&#42;1^

[NOTE]
====
. Lit.: “num lugar espaçoso”.
====

[[v28-4-17]]

^<<v28-4-17,17>>^ Efraim apegou-se a ídolos.
Deixa-o sozinho!

[[v28-4-18]]

^<<v28-4-18,18>>^ Quando a sua cerveja^&#42;1^ acaba,
Eles tornam-se promíscuos.^&#42;2^
Os governantes dela^&#42;3^ amam profundamente a desonra.

[NOTE]
====
. Ou: “cerveja de trigo”.
. Ou: “tornam-se crassamente imorais; prostituem-se”.
. Lit.: “escudos dela”. Possivelmente, refere-se a Efraim.
====

[[v28-4-19]]

^<<v28-4-19,19>>^ O vento vai envolvê-la^&#42;1^ nas suas asas,
E eles hão de envergonhar-se dos seus sacrifícios.”

[NOTE]
====
. Ou: “levá-la”.
====

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]