include::./index.adoc[]

[[v28-3-0]]
=== Oseias, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-3-1]]

^<<v28-3-1,1>>^ Então, Jeová disse-me: “Vai mais uma vez, ama a mulher que é amada por outro homem e que comete adultério, assim como Jeová ama o povo de Israel enquanto eles se voltam para outros deuses e amam bolos de passas.”^&#42;1^

[NOTE]
====
. Isto é, os usados na adoração falsa.
====

[[v28-3-2]]

^<<v28-3-2,2>>^ Assim, comprei-a para mim por 15 peças de prata e um hómer^&#42;1^ e meio de cevada.

[NOTE]
====
. Um hómer equivalia a 220 l. Veja o Ap. B14.
====

[[v28-3-3]]

^<<v28-3-3,3>>^ De seguida, eu disse-lhe: “Continuarás a ser minha por muitos dias. Não te prostituas^&#42;1^ e não tenhas relações com outro homem, e eu agirei da mesma maneira contigo.”^&#42;2^

[NOTE]
====
. Ou: “Não te envolvas em imoralidade (promiscuidade)”.
. Ou: “eu não terei relações contigo”.
====

[[v28-3-4]]

^<<v28-3-4,4>>^ Pois o povo de Israel viverá por muito tempo^&#42;1^ sem rei, sem príncipe, sem sacrifícios, sem colunas sagradas, e sem éfode e ídolos domésticos.^&#42;2^

[NOTE]
====
. Lit.: “muitos dias”.
. Ou: “deuses domésticos”. Lit.: “terafins”.
====

[[v28-3-5]]

^<<v28-3-5,5>>^ Depois, o povo de Israel voltará e procurará a Jeová, seu Deus, e a David, seu rei; e voltarão a tremer para Jeová e para a sua bondade na parte final dos dias.

'''

xref:028-oseias/028-oseias-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-oseias/028-oseias-004.adoc#v28-4-0[Próximo Capítulo &#62;]