include::./index.adoc[]

[[v28-2-0]]
=== Oseias, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-2-1]]

^<<v28-2-1,1>>^ “Digam aos vossos irmãos: ‘Meu povo!’^&#42;1^
E às vossas irmãs: ‘Ó mulher de quem se teve misericórdia!’^&#42;2^

[NOTE]
====
. Veja Oseias 1:9 n.
. Veja Oseias 1:6 n.
====

[[v28-2-2]]

^<<v28-2-2,2>>^ Acusem a vossa mãe; acusem-na,
Pois ela não é minha esposa e eu não sou seu marido.
Ela deve afastar de si a sua prostituição^&#42;1^
E dentre os seus seios o seu adultério.

[NOTE]
====
. Ou: “imoralidade; promiscuidade”.
====

[[v28-2-3]]

^<<v28-2-3,3>>^ Senão, vou despi-la e deixá-la nua, como no dia em que nasceu,
Farei dela um deserto,^&#42;1^
Irei reduzi-la a uma terra árida,
E matá-la à sede.

[NOTE]
====
. Veja o Glossário.
====

[[v28-2-4]]

^<<v28-2-4,4>>^ E não terei misericórdia dos seus filhos,
Pois são filhos de prostituição.^&#42;1^

[NOTE]
====
. Ou: “imoralidade; promiscuidade”.
====

[[v28-2-5]]

^<<v28-2-5,5>>^ Pois a sua mãe prostituiu-se.^&#42;1^
Aquela que os deu à luz agiu vergonhosamente, pois disse:
‘Irei atrás dos meus amantes,
Aqueles que me dão o meu pão e a minha água,
A minha lã e o meu linho, o meu azeite e a minha bebida.’

[NOTE]
====
. Ou: “envolveu-se em imoralidade (promiscuidade)”.
====

[[v28-2-6]]

^<<v28-2-6,6>>^ Por isso, vou bloquear-lhe o caminho com uma cerca de espinhos;
Vou levantar um muro de pedras contra ela,
De modo a que não encontre as suas veredas.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela correrá atrás dos seus amantes, mas não os alcançará;
Procurará por eles, mas não os encontrará.
Então, dirá: ‘Voltarei para o meu marido,^&#42;1^
Pois a minha situação naquele tempo era melhor do que agora.’

[NOTE]
====
. Ou: “o meu marido, o primeiro”.
====

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela não reconheceu que era eu quem lhe dava o cereal, o vinho novo e o azeite,
E era eu quem lhe dava prata em abundância
E também ouro, os quais eles usavam na adoração de Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ ‘Por isso, vou voltar e tirar-lhe o meu cereal no tempo da colheita
E o meu vinho novo na sua época,
E vou arrancar-lhe a minha lã e o meu linho, que serviam para lhe cobrir a nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ Agora, exporei as suas partes íntimas mesmo à frente dos seus amantes,
E nenhum homem a livrará da minha mão.

[[v28-2-11]]

^<<v28-2-11,11>>^ Porei fim a toda a sua alegria,
As suas festividades, as suas luas novas, os seus sábados e todas as suas épocas festivas.

[[v28-2-12]]

^<<v28-2-12,12>>^ E vou arruinar as suas videiras e as suas figueiras, sobre as quais ela disse:
“São o pagamento que recebi dos meus amantes.”
Vou fazer delas um matagal,
E os animais selvagens hão de devorá-las.

[[v28-2-13]]

^<<v28-2-13,13>>^ Vou ajustar contas com ela pelos dias em que oferecia sacrifícios às imagens de Baal,
Quando se enfeitava com os seus brincos e as suas joias, e ia atrás dos seus amantes,
E era de mim que ela se esquecia’, diz Jeová.

[[v28-2-14]]

^<<v28-2-14,14>>^ ‘Portanto, vou persuadi-la,
Vou conduzi-la para o deserto
E vou falar-lhe ao coração.

[[v28-2-15]]

^<<v28-2-15,15>>^ Dali em diante, vou devolver-lhe as suas vinhas,
E farei do vale^&#42;1^ de Acor uma porta de esperança;
Ali, ela irá responder-me como nos dias da sua juventude,
Como no tempo^&#42;2^ em que saiu da terra do Egito.

[NOTE]
====
. Ou: “da planície”.
. Ou: “dia”.
====

[[v28-2-16]]

^<<v28-2-16,16>>^ E nesse dia’, diz Jeová,
‘Irás chamar-me “meu marido”, e não continuarás a chamar-me “meu dono”’.^&#42;1^

[NOTE]
====
. Ou: “meu Baal”.
====

[[v28-2-17]]

^<<v28-2-17,17>>^ ‘Vou remover da sua boca os nomes das imagens de Baal,
E o nome delas nunca mais será lembrado.

[[v28-2-18]]

^<<v28-2-18,18>>^ Nesse dia, farei em favor deles um pacto com os animais selvagens,
E com as aves dos céus e os animais rasteiros;
Livrarei esta terra do arco, da espada e da guerra;
E vou fazer com que se deitem^&#42;1^ em segurança.

[NOTE]
====
. Ou: “vou deixá-los viver”.
====

[[v28-2-19]]

^<<v28-2-19,19>>^ Vou tomar-te como noiva para sempre;
Vou tomar-te como noiva em retidão e justiça,
Em amor leal e misericórdia.

[[v28-2-20]]

^<<v28-2-20,20>>^ Vou tomar-te como noiva em fidelidade,
E certamente conhecerás a Jeová.’

[[v28-2-21]]

^<<v28-2-21,21>>^ ‘Nesse dia, eu responderei’, diz Jeová,
‘Responderei aos céus,
E eles responderão à terra;

[[v28-2-22]]

^<<v28-2-22,22>>^ E a terra responderá ao cereal, ao vinho novo e ao azeite;
E eles responderão a Jezreel.^&#42;1^

[NOTE]
====
. Que significa “Deus semeará”.
====

[[v28-2-23]]

^<<v28-2-23,23>>^ Vou semeá-la para mim na terra,
Vou ter misericórdia daquela de quem não se teve misericórdia;^&#42;1^
Vou dizer aos que não são do meu povo:^&#42;2^ “Vocês são o meu povo”,
E eles dirão: “Tu és o meu Deus.”’”

[NOTE]
====
. Veja Oseias 1:6 n.
. Veja Oseias 1:9 n.
====

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]