include::./index.adoc[]

[[v28-13-0]]
=== Oseias, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-13-1]]

^<<v28-13-1,1>>^ “Quando Efraim falava, causava tremor;
Ele era importante em Israel.
Porém, tornou-se culpado por adorar Baal e morreu.

[[v28-13-2]]

^<<v28-13-2,2>>^ Agora, pecam ainda mais
E, com a sua prata, fazem estátuas de metal;^&#42;1^
Fazem ídolos com habilidade, sendo todos estes trabalho de artesãos.
E dizem: ‘Que os homens que oferecem sacrifícios beijem os bezerros.’

[NOTE]
====
. Ou: “estátuas fundidas”.
====

[[v28-13-3]]

^<<v28-13-3,3>>^ Por isso, irão tornar-se como a neblina da manhã,
Como o orvalho que cedo desaparece,
Como a palha^&#42;1^ levada da eira por um vendaval,
E como o fumo que sai pela chaminé.

[NOTE]
====
. Ou: “pragana”.
====

[[v28-13-4]]

^<<v28-13-4,4>>^ Todavia, eu sou Jeová, teu Deus, desde a terra do Egito.
Não conheceste outro Deus além de mim,
E não há outro salvador, a não ser eu.

[[v28-13-5]]

^<<v28-13-5,5>>^ Conheci-te no deserto, na terra da seca.

[[v28-13-6]]

^<<v28-13-6,6>>^ Eles ficaram satisfeitos com os seus pastos,
Ficaram satisfeitos e o seu coração ficou orgulhoso.
E assim se esqueceram de mim.

[[v28-13-7]]

^<<v28-13-7,7>>^ Serei para eles como um leão novo,
Como um leopardo à espreita à beira do caminho.

[[v28-13-8]]

^<<v28-13-8,8>>^ Vou atacá-los como uma ursa que perdeu as crias,
E vou rasgar-lhes o peito.^&#42;1^
Ali os devorarei como um leão;
Um animal selvagem há de dilacerá-los.

[NOTE]
====
. Lit.: “o envoltório do seu coração”.
====

[[v28-13-9]]

^<<v28-13-9,9>>^ Visto que te voltaste contra mim, teu ajudador,
Isso será a tua destruição, Israel.

[[v28-13-10]]

^<<v28-13-10,10>>^ Então, onde é que está o teu rei, para salvar-te em todas as tuas cidades,
E os teus governantes,^&#42;1^ sobre os quais disseste:
‘Dá-me um rei e príncipes’?

[NOTE]
====
. Lit.: “juízes”.
====

[[v28-13-11]]

^<<v28-13-11,11>>^ Dei-te um rei na minha ira,
E, na minha fúria, irei tirar-to.

[[v28-13-12]]

^<<v28-13-12,12>>^ O erro de Efraim está guardado;^&#42;1^
O seu pecado está armazenado.

[NOTE]
====
. Ou: “embrulhado; preservado”.
====

[[v28-13-13]]

^<<v28-13-13,13>>^ Hão de chegar-lhe as dores de parto.
Porém, ele é um filho insensato;
Não se apresenta quando é hora de nascer.

[[v28-13-14]]

^<<v28-13-14,14>>^ Vou livrá-los do poder da Sepultura;^&#42;1^
Vou resgatá-los da morte.
Onde é que estão os teus aguilhões, ó Morte?
Onde é que está o teu poder de destruição, ó Sepultura?
A compaixão ficará escondida dos meus olhos.

[NOTE]
====
. Ou: “do Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v28-13-15]]

^<<v28-13-15,15>>^ Mesmo que ele floresça entre os juncos,
Virá um vento leste, o vento de Jeová;
Virá do deserto para secar a sua fonte e esgotar a sua nascente.
Ele saqueará o seu tesouro, todas as suas coisas preciosas.

[[v28-13-16]]

^<<v28-13-16,16>>^ Samaria será considerada culpada, pois rebelou-se contra o seu Deus.
Eles cairão pela espada.
Os seus filhos serão despedaçados,
E o ventre das mulheres grávidas será rasgado.”

'''

xref:028-oseias/028-oseias-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-oseias/028-oseias-014.adoc#v28-14-0[Próximo Capítulo &#62;]