include::./index.adoc[]

[[v28-10-0]]
=== Oseias, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-10-1]]

^<<v28-10-1,1>>^ “Israel é uma videira degenerada,^&#42;1^ que produz os seus frutos.
Quanto mais frutos dá, mais multiplica os seus altares.
Quanto melhores são as colheitas da sua terra, mais esplêndidas são as suas colunas sagradas.

[NOTE]
====
. Ou, possivelmente: “frondosa”.
====

[[v28-10-2]]

^<<v28-10-2,2>>^ O seu coração é hipócrita;^&#42;1^
Agora, serão condenados.
Alguém despedaçará os seus altares e destruirá as suas colunas sagradas.

[NOTE]
====
. Lit.: “escorregadio; liso”.
====

[[v28-10-3]]

^<<v28-10-3,3>>^ Agora, vão dizer: ‘Não temos rei, pois não tememos a Jeová.
E o que poderia um rei fazer por nós?’

[[v28-10-4]]

^<<v28-10-4,4>>^ Eles dizem palavras vazias, juram falsamente e fazem pactos;
Por isso, o julgamento é como ervas venenosas que crescem nos campos lavrados.

[[v28-10-5]]

^<<v28-10-5,5>>^ Os residentes de Samaria temerão pelo deus-bezerro de Bete-Áven.
O povo chorará por ele,
Bem como os sacerdotes de deuses estrangeiros, que se alegravam por causa dele e da sua glória,
Pois ele irá para o exílio, para longe deles.

[[v28-10-6]]

^<<v28-10-6,6>>^ Ele será levado para a Assíria como presente para um grande rei.
Efraim será envergonhado,
E Israel irá envergonhar-se do conselho que seguiu.

[[v28-10-7]]

^<<v28-10-7,7>>^ Certamente, Samaria e o seu rei serão eliminados,^&#42;1^
Como um raminho partido na superfície das águas.

[NOTE]
====
. Lit.: “silenciados”.
====

[[v28-10-8]]

^<<v28-10-8,8>>^ Os altos sagrados de Bete-Áven, que são o pecado de Israel, serão aniquilados.
Espinhos e abrolhos crescerão nos seus altares.
As pessoas dirão às montanhas: ‘Cubram-nos!’
E às colinas: ‘Caiam sobre nós!’

[[v28-10-9]]

^<<v28-10-9,9>>^ Pecas desde os dias de Gibeá, ó Israel.
Nisso,^&#42;1^ eles têm persistido.
A guerra não alcançou^&#42;2^ os filhos da injustiça em Gibeá.

[NOTE]
====
. Ou: “Ali”.
. Ou: “não destruiu completamente”.
====

[[v28-10-10]]

^<<v28-10-10,10>>^ Quando for da minha vontade, irei discipliná-los.
E os povos irão ajuntar-se contra eles,
Quando tiverem de puxar a carga dos seus dois erros.^&#42;1^

[NOTE]
====
. Isto é, quando eles tiverem de suportar a sua punição como se fosse um jugo.
====

[[v28-10-11]]

^<<v28-10-11,11>>^ Efraim era uma novilha ensinada que gostava de trilhar grãos,
Por isso, eu poupava o seu belo pescoço.
Agora, porei arreios^&#42;1^ em Efraim.
Judá vai lavrar; Jacó vai aplanar para outro.

[NOTE]
====
. Ou: “farei alguém montar”.
====

[[v28-10-12]]

^<<v28-10-12,12>>^ Semeiem segundo a justiça e colham amor leal.
Passem o arado nas terras que não foram cultivadas,
Enquanto há tempo para procurar a Jeová,
Até que ele venha e vos ensine segundo a justiça.

[[v28-10-13]]

^<<v28-10-13,13>>^ Contudo, vocês cultivaram maldade,
Colheram injustiça,
E comeram o fruto da mentira;
Pois confiaste no teu próprio caminho,
No grande número dos teus guerreiros.

[[v28-10-14]]

^<<v28-10-14,14>>^ Irromperá um tumulto contra o teu povo,
E as tuas cidades fortificadas serão todas devastadas,
Assim como Salmã devastou a casa de Arbel
No dia da batalha, quando as mães foram despedaçadas com os seus filhos.

[[v28-10-15]]

^<<v28-10-15,15>>^ É isso que será feito convosco, ó Betel, por causa da vossa enorme maldade.
Ao raiar do dia, o rei de Israel certamente será eliminado.”^&#42;1^

[NOTE]
====
. Lit.: “silenciado”.
====

'''

xref:028-oseias/028-oseias-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-oseias/028-oseias-011.adoc#v28-11-0[Próximo Capítulo &#62;]