include::./index.adoc[]

[[v28-12-0]]
=== Oseias, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-12-1]]

^<<v28-12-1,1>>^ “Efraim alimenta-se de vento.
Corre atrás do vento leste o dia inteiro.
Multiplica mentiras e violência.
Fazem um pacto com a Assíria e levam azeite ao Egito.

[[v28-12-2]]

^<<v28-12-2,2>>^ Jeová tem uma causa contra Judá;
Ajustará contas com Jacó segundo os seus caminhos,
E vai retribuir-lhe segundo as suas ações.

[[v28-12-3]]

^<<v28-12-3,3>>^ No ventre, ele agarrou o seu irmão pelo calcanhar
E, com o seu vigor, lutou com Deus.

[[v28-12-4]]

^<<v28-12-4,4>>^ Lutou com um anjo e saiu vencedor.
Chorou e implorou o seu favor.”
Ele^&#42;1^ encontrou-o em Betel, e ali Ele falou connosco.

[NOTE]
====
. Isto é, Deus.
====

[[v28-12-5]]

^<<v28-12-5,5>>^ Jeová, o Deus dos exércitos,
Jeová é o nome pelo qual Ele é lembrado.^&#42;1^

[NOTE]
====
. Ou: “é o seu nome memorial”.
====

[[v28-12-6]]

^<<v28-12-6,6>>^ “Portanto, volta ao teu Deus,
Demonstra amor leal e justiça,
E espera sempre no teu Deus.

[[v28-12-7]]

^<<v28-12-7,7>>^ No entanto, o comerciante^&#42;1^ tem na mão balanças enganosas;
Ele gosta de defraudar.

[NOTE]
====
. Ou: “mercador”.
====

[[v28-12-8]]

^<<v28-12-8,8>>^ Efraim diz: ‘Eu realmente fiquei rico;
Adquiri riquezas.
Porém, não encontrarão nenhum erro nem pecado em todo o meu trabalho árduo.’

[[v28-12-9]]

^<<v28-12-9,9>>^ Contudo, eu sou Jeová, teu Deus, desde a terra do Egito.
Farei com que mores novamente em tendas,
Como nos dias de um tempo determinado.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “uma festividade”.
====

[[v28-12-10]]

^<<v28-12-10,10>>^ Eu falava aos profetas,
Multiplicava-lhes as visões
E contava-lhes parábolas por meio dos profetas.

[[v28-12-11]]

^<<v28-12-11,11>>^ Em Gileade, há mentira^&#42;1^ e falsidade.
Em Gilgal, sacrificam touros.
E os seus altares são como montões de pedras em campos lavrados.

[NOTE]
====
. Ou: “magia; misticismo”.
====

[[v28-12-12]]

^<<v28-12-12,12>>^ Jacó fugiu para o território^&#42;1^ de Arã,^&#42;2^
Israel serviu lá por uma esposa,
E por uma esposa cuidou de ovelhas.

[NOTE]
====
. Lit.: “campo”.
. Ou: “da Síria”.
====

[[v28-12-13]]

^<<v28-12-13,13>>^ Por meio de um profeta, Jeová tirou Israel do Egito;
E, por meio de um profeta, cuidou dele.

[[v28-12-14]]

^<<v28-12-14,14>>^ Efraim ofendeu a Deus amargamente;
A sua culpa de sangue permanece sobre ele.
O seu Senhor irá retribuir-lhe a desonra que ele causou.”

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]