include::./index.adoc[]

[[v28-9-0]]
=== Oseias, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v28-9-1]]

^<<v28-9-1,1>>^ “Não te alegres, Israel.
Não exultes como os povos.
Pois, com a tua prostituição,^&#42;1^ afastaste-te do teu Deus.
Amaste o salário da prostituição em todas as eiras de cereais.

[NOTE]
====
. Ou: “imoralidade; promiscuidade”.
====

[[v28-9-2]]

^<<v28-9-2,2>>^ Contudo, a eira e o lagar não os alimentarão,
E o vinho novo causará a sua deceção.

[[v28-9-3]]

^<<v28-9-3,3>>^ Não continuarão a morar na terra de Jeová;
Em vez disso, Efraim voltará ao Egito,
E na Assíria comerão o que é impuro.

[[v28-9-4]]

^<<v28-9-4,4>>^ Não voltarão a derramar ofertas de vinho para Jeová;
Os sacrifícios deles não lhe agradarão.
São como o pão servido quando há luto;
Todos os que o comem ficam impuros.
Pois o seu pão servirá apenas para eles próprios;^&#42;1^
Não entrará na casa de Jeová.

[NOTE]
====
. Ou: “para a sua própria alma”.
====

[[v28-9-5]]

^<<v28-9-5,5>>^ O que é que vocês farão no dia de se reunirem,^&#42;1^
No dia da festividade de Jeová?

[NOTE]
====
. Ou: “da vossa festividade”.
====

[[v28-9-6]]

^<<v28-9-6,6>>^ Vejam! Eles terão de fugir por causa da destruição.
O Egito irá ajuntá-los, e Mênfis irá sepultá-los.
Urtigas tomarão conta dos seus preciosos objetos de prata,
E espinheiros crescerão nas suas tendas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Os dias do ajuste de contas chegarão,
Os dias da retribuição virão.
E Israel saberá disso.
O seu profeta revelará ser um tolo, e o homem de expressões inspiradas ficará louco;
Visto que o teu erro é abundante, a hostilidade contra vocês é abundante.”

[[v28-9-8]]

^<<v28-9-8,8>>^ O vigia de Efraim estava com o meu Deus.
Agora, porém, todos os caminhos dos seus profetas são como as armadilhas de um passarinheiro;
Há hostilidade na casa do seu Deus.

[[v28-9-9]]

^<<v28-9-9,9>>^ Ficaram profundamente corrompidos, como nos dias de Gibeá.
Ele irá lembrar-se do seu erro e punir os seus pecados.

[[v28-9-10]]

^<<v28-9-10,10>>^ “Quando encontrei Israel, foi como encontrar uvas no deserto.
Quando vi os vossos antepassados, foi como ver os primeiros figos temporãos numa figueira.
No entanto, eles dirigiram-se a Baal de Peor;
Dedicaram-se a essa coisa vergonhosa^&#42;1^
E tornaram-se tão repugnantes como o objeto do seu amor.

[NOTE]
====
. Ou: “esse deus vergonhoso”.
====

[[v28-9-11]]

^<<v28-9-11,11>>^ A glória de Efraim voa para longe como uma ave;
Não há nascimento, nem gravidez, nem conceção.

[[v28-9-12]]

^<<v28-9-12,12>>^ Mesmo que criem filhos,
Vou tirar-lhos até que não sobre nenhum.
Sim, ai deles quando eu me afastar deles!

[[v28-9-13]]

^<<v28-9-13,13>>^ Efraim, plantado num pasto, era para mim como Tiro;
Agora, Efraim terá de entregar os seus filhos para a matança.”

[[v28-9-14]]

^<<v28-9-14,14>>^ Ó Jeová, dá-lhes o que deves dar:
Um ventre que aborta e peitos secos.^&#42;1^

[NOTE]
====
. Ou: “murchos”.
====

[[v28-9-15]]

^<<v28-9-15,15>>^ “Toda a sua maldade estava em Gilgal; foi lá que passei a odiá-los.
Vou expulsá-los da minha casa por causa das suas más ações.
Nunca mais os amarei;
Todos os seus príncipes são obstinados.

[[v28-9-16]]

^<<v28-9-16,16>>^ Efraim será ferido.
A sua raiz irá secar-se, e eles não produzirão nenhum fruto.
Mesmo que deem à luz, vou entregar os seus queridos filhos à morte.”

[[v28-9-17]]

^<<v28-9-17,17>>^ O meu Deus irá rejeitá-los,
Pois não lhe deram ouvidos;
E eles irão tornar-se fugitivos entre as nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]