include::./index.adoc[]

[[v41-3-0]]
=== Marcos, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-3-1]]

^<<v41-3-1,1>>^ Novamente ele entrou numa sinagoga, e estava ali um homem com a mão atrofiada.^&#42;1^

[NOTE]
====
. Ou: “paralisada”.
====

[[v41-3-2]]

^<<v41-3-2,2>>^ Assim, observavam-no atentamente para ver se curaria o homem no sábado, a fim de o acusarem.

[[v41-3-3]]

^<<v41-3-3,3>>^ Ele disse ao homem com a mão atrofiada:^&#42;1^ “Levanta-te e vem para o centro.”

[NOTE]
====
. Ou: “paralisada”.
====

[[v41-3-4]]

^<<v41-3-4,4>>^ A seguir, perguntou-lhes: “É permitido, no sábado, fazer o bem ou fazer o mal, salvar uma vida^&#42;1^ ou matar?” Mas eles continuaram calados.

[NOTE]
====
. Ou: “alma”.
====

[[v41-3-5]]

^<<v41-3-5,5>>^ Depois de olhar para os que estavam à sua volta, com indignação e profundamente triste com a insensibilidade do coração deles, ele disse ao homem: “Estende a mão.” Ele estendeu-a, e a mão foi restabelecida.

[[v41-3-6]]

^<<v41-3-6,6>>^ Então, os fariseus saíram e imediatamente começaram a conspirar^&#42;1^ com os partidários de Herodes contra Jesus, para o matarem.

[NOTE]
====
. Ou: “reunir-se em conselho”.
====

[[v41-3-7]]

^<<v41-3-7,7>>^ Mas Jesus foi para o mar com os discípulos, e seguia-o uma grande multidão da Galileia e da Judeia.

[[v41-3-8]]

^<<v41-3-8,8>>^ Ao ouvir falar de quantas coisas ele fazia, uma grande multidão foi ao seu encontro, até mesmo de Jerusalém, da Idumeia, do outro lado do Jordão e dos arredores de Tiro e de Sídon.

[[v41-3-9]]

^<<v41-3-9,9>>^ E ele disse aos discípulos que mantivessem um pequeno barco à disposição dele, para que a multidão não o apertasse.

[[v41-3-10]]

^<<v41-3-10,10>>^ Visto que ele curava muitos, todos os que tinham doenças graves aglomeravam-se à sua volta para lhe tocarem.

[[v41-3-11]]

^<<v41-3-11,11>>^ Até mesmo os espíritos impuros, sempre que o viam, prostravam-se diante dele, gritavam e diziam: “Tu és o Filho de Deus.”

[[v41-3-12]]

^<<v41-3-12,12>>^ Muitas vezes, porém, ele ordenou-lhes com firmeza que não dissessem a outros quem ele era.

[[v41-3-13]]

^<<v41-3-13,13>>^ Ele subiu a um monte e convocou os que ele quis, e eles dirigiram-se a ele.

[[v41-3-14]]

^<<v41-3-14,14>>^ Formou^&#42;1^ então um grupo de 12, a quem deu o nome de apóstolos, aqueles que o acompanhariam e que ele enviaria para pregar,

[NOTE]
====
. Ou: “Designou”.
====

[[v41-3-15]]

^<<v41-3-15,15>>^ com autoridade para expulsar demónios.

[[v41-3-16]]

^<<v41-3-16,16>>^ E no grupo dos Doze que ele formou^&#42;1^ estavam Simão (a quem também deu o nome de Pedro),

[NOTE]
====
. Ou: “designou”.
====

[[v41-3-17]]

^<<v41-3-17,17>>^ Tiago, filho de Zebedeu, João, irmão de Tiago (ele também lhes deu o nome de Boanerges, que significa “filhos do trovão”),

[[v41-3-18]]

^<<v41-3-18,18>>^ André, Filipe, Bartolomeu, Mateus, Tomé, Tiago, filho de Alfeu, Tadeu, Simão, o Cananita,^&#42;1^

[NOTE]
====
. Ou: “o zeloso”.
====

[[v41-3-19]]

^<<v41-3-19,19>>^ e Judas Iscariotes, que mais tarde o traiu.
Então, ele entrou numa casa,

[[v41-3-20]]

^<<v41-3-20,20>>^ e novamente a multidão se ajuntou, de modo que não podiam sequer tomar uma refeição.

[[v41-3-21]]

^<<v41-3-21,21>>^ Mas, quando os seus parentes souberam o que estava a acontecer, saíram para o apanhar, pois diziam: “Ele perdeu o juízo.”

[[v41-3-22]]

^<<v41-3-22,22>>^ Também os escribas que desceram de Jerusalém diziam: “Ele está dominado por Belzebu^&#42;1^ e expulsa os demónios por meio do governante dos demónios.”

[NOTE]
====
. Um nome usado para Satanás.
====

[[v41-3-23]]

^<<v41-3-23,23>>^ Portanto, depois de os chamar, falou-lhes com ilustrações: “Como é que Satanás pode expulsar Satanás?

[[v41-3-24]]

^<<v41-3-24,24>>^ Se um reino fica dividido contra si mesmo, tal reino não pode ficar de pé,

[[v41-3-25]]

^<<v41-3-25,25>>^ e, se uma casa fica dividida contra si mesma, tal casa não poderá ficar de pé.

[[v41-3-26]]

^<<v41-3-26,26>>^ Também, se Satanás se levantou contra si mesmo e ficou dividido, não pode ficar de pé, mas está a chegar ao fim.

[[v41-3-27]]

^<<v41-3-27,27>>^ De facto, ninguém que entre na casa de um homem forte é capaz de lhe roubar os bens, a menos que amarre primeiro o homem forte. Só então é que poderá roubar-lhe a casa.

[[v41-3-28]]

^<<v41-3-28,28>>^ Digo-vos a verdade: Todas as coisas serão perdoadas aos filhos dos homens, não importa que pecados cometam e que blasfémias digam.

[[v41-3-29]]

^<<v41-3-29,29>>^ No entanto, quem blasfema contra o espírito santo nunca terá perdão, mas é culpado de pecado eterno.”

[[v41-3-30]]

^<<v41-3-30,30>>^ Jesus disse isto porque diziam: “Ele está com um espírito impuro.”

[[v41-3-31]]

^<<v41-3-31,31>>^ Em seguida, a sua mãe e os seus irmãos chegaram e, ficando do lado de fora, mandaram alguém chamá-lo.

[[v41-3-32]]

^<<v41-3-32,32>>^ Como estava uma multidão sentada à sua volta, disseram-lhe: “Olhe! A sua mãe e os seus irmãos estão lá fora à sua procura.”

[[v41-3-33]]

^<<v41-3-33,33>>^ Mas ele respondeu-lhes: “Quem são a minha mãe e os meus irmãos?”

[[v41-3-34]]

^<<v41-3-34,34>>^ Então, ele olhou para os que estavam sentados ao seu redor e disse: “Aqui estão a minha mãe e os meus irmãos!

[[v41-3-35]]

^<<v41-3-35,35>>^ Quem faz a vontade de Deus, esse é meu irmão, minha irmã e minha mãe.”

'''

xref:041-marcos/041-marcos-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-marcos/041-marcos-004.adoc#v41-4-0[Próximo Capítulo &#62;]