include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-11-1]]

^<<v41-11-1,1>>^ Então, quando estavam a chegar perto de Jerusalém, de Betfagé e de Betânia, no monte das Oliveiras, ele enviou dois dos seus discípulos

[[v41-11-2]]

^<<v41-11-2,2>>^ e disse-lhes: “Vão à aldeia que está ao alcance da vista e, assim que lá entrarem, encontrarão um jumentinho amarrado, o qual ainda ninguém montou. Desamarrem-no e tragam-no aqui.

[[v41-11-3]]

^<<v41-11-3,3>>^ E, se alguém vos perguntar: ‘Porque é que estão a fazer isso?’, digam: ‘O Senhor precisa dele, e logo o mandará de volta.’”

[[v41-11-4]]

^<<v41-11-4,4>>^ Assim, partiram e encontraram o jumentinho amarrado a uma porta, do lado de fora, na rua, e desamarraram-no.

[[v41-11-5]]

^<<v41-11-5,5>>^ No entanto, alguns dos que estavam ali perguntaram-lhes: “O que é que estão a fazer, a desamarrar o jumentinho?”

[[v41-11-6]]

^<<v41-11-6,6>>^ Disseram-lhes o que Jesus tinha dito, e eles deixaram-nos ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ Trouxeram então a Jesus o jumentinho, colocaram sobre este as suas capas, e ele sentou-se nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Também, muitos estenderam as suas capas na estrada, mas outros cortaram ramos dos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ E os que iam à frente e os que vinham atrás gritavam: “Salva, rogamos! Bendito é aquele que vem em nome de Jeová!^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito é o Reino que virá, do nosso pai David! Salva, rogamos, nas maiores alturas!”

[[v41-11-11]]

^<<v41-11-11,11>>^ E ele entrou em Jerusalém, foi ao templo e observou tudo em volta, mas, visto que já era tarde, saiu com os Doze para Betânia.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, quando estavam a sair de Betânia, ele sentiu fome.

[[v41-11-13]]

^<<v41-11-13,13>>^ A certa distância, viu uma figueira que tinha folhas e foi ver se encontrava alguma coisa nela. Mas, ao chegar perto dela, não encontrou nada, exceto folhas, pois não era a estação dos figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ Então, ele disse-lhe: “Nunca mais ninguém coma do teu fruto.” E os discípulos estavam a ouvir.

[[v41-11-15]]

^<<v41-11-15,15>>^ Chegaram então a Jerusalém. Ali, ele entrou no templo e começou a expulsar os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas;

[[v41-11-16]]

^<<v41-11-16,16>>^ e não deixava ninguém carregar nenhum utensílio através do templo.

[[v41-11-17]]

^<<v41-11-17,17>>^ Ele ensinava, dizendo-lhes: “Não está escrito: ‘A minha casa será chamada casa de oração para todas as nações’? Mas vocês fizeram dela um covil de ladrões.”

[[v41-11-18]]

^<<v41-11-18,18>>^ Os principais sacerdotes e os escribas ouviram isto, e começaram a procurar uma maneira de o matar, pois tinham medo dele, porque toda a multidão estava maravilhada com o seu ensino.

[[v41-11-19]]

^<<v41-11-19,19>>^ Quando se fez tarde no dia, saíram da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ Mas, de manhã cedo, ao passarem pela figueira, viram que ela estava seca desde as raízes.

[[v41-11-21]]

^<<v41-11-21,21>>^ Pedro lembrou-se e disse-lhe: “Rabi, olha! A figueira que amaldiçoaste secou-se.”

[[v41-11-22]]

^<<v41-11-22,22>>^ Jesus disse-lhe em resposta: “Tenham fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Digo-vos a verdade: Quem disser a este monte: ‘Levanta-te e atira-te ao mar’, e não duvidar no coração, mas tiver fé de que aquilo que diz vai acontecer, assim acontecerá.

[[v41-11-24]]

^<<v41-11-24,24>>^ É por isso que vos digo: Todas as coisas que pedirem em oração, tenham fé em que já as receberam, e irão tê-las.

[[v41-11-25]]

^<<v41-11-25,25>>^ E, quando estiverem de pé, a orar, perdoem o que tiverem contra alguém, para que o vosso Pai, que está nos céus, também vos perdoe as vossas falhas.”

[[v41-11-26]]

^<<v41-11-26,26>>^ ^&#42;1^——

[NOTE]
====
. Veja o Ap. A3.
====

[[v41-11-27]]

^<<v41-11-27,27>>^ Chegaram novamente a Jerusalém. E enquanto ele andava pelo templo, os principais sacerdotes, os escribas e os anciãos vieram

[[v41-11-28]]

^<<v41-11-28,28>>^ e perguntaram-lhe: “Com que autoridade é que fazes estas coisas? E quem é que te deu autoridade para fazer estas coisas?”

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus disse-lhes: “Vou fazer-vos uma pergunta. Respondam-me, e eu vou dizer-vos com que autoridade faço estas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu ou dos homens?^&#42;1^ Respondam-me.”

[NOTE]
====
. Ou: “de origem humana”.
====

[[v41-11-31]]

^<<v41-11-31,31>>^ Então, eles começaram a raciocinar entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Então, porque é que não acreditaram nele?’

[[v41-11-32]]

^<<v41-11-32,32>>^ Mas atrevemo-nos a dizer: ‘Dos homens’?” Eles tinham medo da multidão, pois todos achavam que João realmente tinha sido um profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Assim, responderam a Jesus: “Não sabemos.” Jesus disse-lhes: “Então, eu também não vos digo com que autoridade faço estas coisas.”

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]