include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-12-1]]

^<<v41-12-1,1>>^ Então, ele começou a falar-lhes com ilustrações: “Um homem plantou um vinhedo, pôs uma cerca à sua volta, cavou um tanque como lagar de vinho e ergueu uma torre; então, arrendou o vinhedo a lavradores e viajou para fora.

[[v41-12-2]]

^<<v41-12-2,2>>^ Na época devida, enviou um escravo aos lavradores, para receber deles alguns dos frutos do vinhedo.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas eles agarraram-no, espancaram-no, e mandaram-no embora de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ Enviou-lhes outro escravo, e eles bateram-lhe na cabeça e humilharam-no.

[[v41-12-5]]

^<<v41-12-5,5>>^ Então, enviou outro, e eles mataram-no; e enviou muitos outros: a uns espancaram, a outros mataram.

[[v41-12-6]]

^<<v41-12-6,6>>^ Ele tinha mais um, um filho amado. Por fim, enviou-lhes esse, dizendo: ‘Respeitarão o meu filho.’

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas aqueles lavradores disseram entre si: ‘Este é o herdeiro. Venham, vamos matá-lo, e a herança será nossa.’

[[v41-12-8]]

^<<v41-12-8,8>>^ Assim, eles agarraram-no, mataram-no e atiraram-no para fora do vinhedo.

[[v41-12-9]]

^<<v41-12-9,9>>^ O que é que o dono do vinhedo fará? Voltará e matará os lavradores, e entregará o vinhedo a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Vocês nunca leram esta passagem das Escrituras: ‘A pedra que os construtores rejeitaram, esta tornou-se a principal pedra angular.^&#42;1^

[NOTE]
====
. Lit.: “a cabeça da esquina”.
====

[[v41-12-11]]

^<<v41-12-11,11>>^ Isto procede de Jeová^&#42;1^ e é maravilhoso aos nossos olhos’?”

[NOTE]
====
. Veja o Ap. A5.
====

[[v41-12-12]]

^<<v41-12-12,12>>^ Em vista disso, quiseram prendê-lo,^&#42;1^ porque sabiam que ele contara a ilustração a pensar neles. Contudo, tinham medo da multidão, de modo que o deixaram e foram-se embora.

[NOTE]
====
. Ou: “apanhá-lo”.
====

[[v41-12-13]]

^<<v41-12-13,13>>^ A seguir, enviaram-lhe alguns dos fariseus e dos partidários de Herodes, para o apanhar nas suas palavras.

[[v41-12-14]]

^<<v41-12-14,14>>^ Ao chegarem, eles disseram-lhe: “Instrutor, sabemos que és verdadeiro e que não procuras agradar a homens, pois não olhas para a aparência das pessoas, mas ensinas o caminho de Deus em harmonia com a verdade. É lícito^&#42;1^ ou não pagar a César o imposto por cabeça?

[NOTE]
====
. Ou: “permitido; certo”.
====

[[v41-12-15]]

^<<v41-12-15,15>>^ Devemos pagar ou não devemos pagar?” Percebendo a hipocrisia deles, ele disse-lhes: “Porque é que me põem à prova? Tragam-me um denário^&#42;1^ para eu ver.”

[NOTE]
====
. Veja o Ap. B14.
====

[[v41-12-16]]

^<<v41-12-16,16>>^ Trouxeram-lhe um, e ele perguntou-lhes: “De quem é esta imagem e inscrição?” Responderam-lhe: “De César.”

[[v41-12-17]]

^<<v41-12-17,17>>^ Jesus disse então: “Paguem a César o que é de César, mas a Deus o que é de Deus.” E ficaram maravilhados com ele.

[[v41-12-18]]

^<<v41-12-18,18>>^ Então, os saduceus, que dizem não haver ressurreição, aproximaram-se e perguntaram-lhe:

[[v41-12-19]]

^<<v41-12-19,19>>^ “Instrutor, Moisés escreveu-nos que, se alguém morre e deixa esposa, mas não deixa filhos, o irmão dele deve casar-se com a viúva para dar descendência ao seu irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Havia sete irmãos. O primeiro casou-se, mas morreu sem deixar descendente.

[[v41-12-21]]

^<<v41-12-21,21>>^ E o segundo casou-se com a viúva, mas morreu sem deixar descendente, e o mesmo aconteceu com o terceiro.

[[v41-12-22]]

^<<v41-12-22,22>>^ E nenhum dos sete deixou descendente. Por último, morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, de qual deles é que ela será esposa? Pois os sete tiveram-na como esposa.”

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus disse-lhes: “Não é por isto que vocês estão enganados, por não conhecerem nem as Escrituras, nem o poder de Deus?

[[v41-12-25]]

^<<v41-12-25,25>>^ Pois, quando se levantarem dentre os mortos, os homens não se casam, nem as mulheres são dadas em casamento, mas são como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Quanto aos mortos serem levantados, não leram no livro de Moisés, no relato sobre o espinheiro, que Deus lhe disse: ‘Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ele é Deus, não de mortos, mas de vivos. Vocês estão muito enganados.”

[[v41-12-28]]

^<<v41-12-28,28>>^ Um dos escribas, que se tinha aproximado e ouvido a discussão, ao ver que ele lhes tinha respondido bem, perguntou-lhe: “Qual é o primeiro^&#42;1^ mandamento de todos?”

[NOTE]
====
. Ou: “mais importante”.
====

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus respondeu: “O primeiro é: ‘Ouve, ó Israel: Jeová,^&#42;1^ o nosso Deus, é um só Jeová.^&#42;2^

[NOTE]
====
. Veja o Ap. A5.
. Veja o Ap. A5.
====

[[v41-12-30]]

^<<v41-12-30,30>>^ Ama a Jeová,^&#42;1^ teu Deus, de todo o teu coração, de toda a tua alma,^&#42;2^ de toda a tua mente e de toda a tua força.’

[NOTE]
====
. Veja o Ap. A5.
. Veja o Glossário.
====

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é: ‘Ama o teu próximo como a ti mesmo.’ Não há outro mandamento maior do que estes.”

[[v41-12-32]]

^<<v41-12-32,32>>^ O escriba disse-lhe: “Instrutor, falaste bem, em harmonia com a verdade: ‘Ele é um só, e não há outro além dele’;

[[v41-12-33]]

^<<v41-12-33,33>>^ e amá-lo de todo o coração, de todo o entendimento e de toda a força, e amar o próximo como a si mesmo vale muito mais do que todas as ofertas queimadas e sacrifícios.”

[[v41-12-34]]

^<<v41-12-34,34>>^ Com isso, Jesus, percebendo que ele tinha respondido de modo inteligente, disse-lhe: “Não estás longe do Reino de Deus.” No entanto, ninguém teve coragem de lhe fazer mais perguntas.

[[v41-12-35]]

^<<v41-12-35,35>>^ No entanto, ao continuar a ensinar no templo, Jesus disse: “Como é que os escribas dizem que o Cristo é filho de David?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio David disse, pelo espírito santo: ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés.”’

[NOTE]
====
. Veja o Ap. A5.
====

[[v41-12-37]]

^<<v41-12-37,37>>^ O próprio David lhe chama Senhor, e então, como é que ele pode ser seu filho?”
E a grande multidão escutava-o com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ E ele ensinava, dizendo: “Cuidado com os escribas, que querem andar de vestes compridas e querem cumprimentos nas praças públicas,

[[v41-12-39]]

^<<v41-12-39,39>>^ os primeiros^&#42;1^ assentos nas sinagogas e os lugares mais destacados nos banquetes.

[NOTE]
====
. Ou: “melhores”.
====

[[v41-12-40]]

^<<v41-12-40,40>>^ Eles devoram as casas^&#42;1^ das viúvas e, para impressionar,^&#42;2^ fazem longas orações. Eles receberão um julgamento mais severo.”^&#42;3^

[NOTE]
====
. Ou: “os bens”.
. Ou: “e, como pretexto”.
. Ou: “pesado”.
====

[[v41-12-41]]

^<<v41-12-41,41>>^ E ele sentou-se, com os cofres^&#42;1^ do tesouro à vista, e começou a observar como a multidão punha dinheiro nos cofres do tesouro, e muitos ricos punham neles muitas moedas.

[NOTE]
====
. Ou: “as caixas”.
====

[[v41-12-42]]

^<<v41-12-42,42>>^ Chegou então uma viúva pobre e pôs neles duas pequenas moedas de pouquíssimo valor.^&#42;1^

[NOTE]
====
. Lit.: “dois léptons, que é um quadrante”. Veja o Ap. B14.
====

[[v41-12-43]]

^<<v41-12-43,43>>^ Ele chamou então os discípulos e disse-lhes: “Digo-vos a verdade: Esta viúva pobre pôs nos cofres do tesouro mais do que todos os outros.

[[v41-12-44]]

^<<v41-12-44,44>>^ Pois todos eles puseram do que lhes sobrava, mas ela, da sua carência,^&#42;1^ pôs tudo o que possuía, tudo o que tinha para viver.”

[NOTE]
====
. Ou: “pobreza”.
====

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]