include::./index.adoc[]

[[v41-2-0]]
=== Marcos, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-2-1]]

^<<v41-2-1,1>>^ No entanto, passados alguns dias, ele entrou novamente em Cafarnaum, e a notícia de que ele estava em casa espalhou-se.

[[v41-2-2]]

^<<v41-2-2,2>>^ Então, ajuntaram-se tantas pessoas que já não havia lugar, nem mesmo perto da porta, e ele começou a declarar-lhes a palavra.

[[v41-2-3]]

^<<v41-2-3,3>>^ E trouxeram-lhe um paralítico, carregado por quatro homens.

[[v41-2-4]]

^<<v41-2-4,4>>^ Contudo, eles não conseguiam levá-lo diretamente a Jesus por causa da multidão; assim, removeram o telhado por cima de onde Jesus estava e, depois de fazerem uma abertura, baixaram a maca em que o paralítico estava deitado.

[[v41-2-5]]

^<<v41-2-5,5>>^ Quando Jesus viu a fé que tinham, disse ao paralítico: “Filho, os teus pecados estão perdoados.”

[[v41-2-6]]

^<<v41-2-6,6>>^ Porém, alguns escribas estavam ali sentados e raciocinavam no coração:

[[v41-2-7]]

^<<v41-2-7,7>>^ “Porque é que este homem fala desta maneira? Ele está a blasfemar. Quem é que pode perdoar pecados a não ser um só, Deus?”

[[v41-2-8]]

^<<v41-2-8,8>>^ Todavia, Jesus discerniu imediatamente no seu espírito que estavam a raciocinar desse modo entre eles e disse-lhes: “Porque é que estão a raciocinar essas coisas no coração?

[[v41-2-9]]

^<<v41-2-9,9>>^ O que é mais fácil de dizer ao paralítico: ‘Os teus pecados estão perdoados’, ou: ‘Levanta-te, apanha a tua maca e anda’?

[[v41-2-10]]

^<<v41-2-10,10>>^ Mas, a fim de que saibam que o Filho do Homem tem autoridade para perdoar pecados na terra . . .”, ele disse ao paralítico:

[[v41-2-11]]

^<<v41-2-11,11>>^ “Digo-te: Levanta-te, apanha a tua maca e vai para casa.”

[[v41-2-12]]

^<<v41-2-12,12>>^ Com isso, ele levantou-se, apanhou imediatamente a sua maca e saiu, andando à frente de todos. Assim, todos ficaram maravilhados e glorificaram a Deus, dizendo: “Nunca vimos nada igual.”

[[v41-2-13]]

^<<v41-2-13,13>>^ Novamente, ele foi para a beira-mar; toda a multidão ia ao seu encontro, e ele começou a ensiná-los.

[[v41-2-14]]

^<<v41-2-14,14>>^ Enquanto caminhava, viu Levi, filho de Alfeu, sentado na coletoria,^&#42;1^ e disse-lhe: “Sê meu seguidor.” Então, ele levantou-se e seguiu-o.

[NOTE]
====
. Isto é, repartição pública onde se pagam os impostos.
====

[[v41-2-15]]

^<<v41-2-15,15>>^ Mais tarde, Jesus estava a comer^&#42;1^ na casa de Levi, e muitos cobradores de impostos e pecadores estavam a comer^&#42;2^ com Jesus e os seus discípulos, pois muitos deles seguiam-no.

[NOTE]
====
. Ou: “recostado à mesa”.
. Ou: “recostados à mesa”.
====

[[v41-2-16]]

^<<v41-2-16,16>>^ Mas, quando os escribas dos fariseus viram que ele comia com os pecadores e os cobradores de impostos, perguntaram aos discípulos: “Ele come com cobradores de impostos e pecadores?”

[[v41-2-17]]

^<<v41-2-17,17>>^ Ao ouvir isso, Jesus disse-lhes: “Os que têm saúde não precisam de médico, mas sim os doentes. Eu não vim chamar os justos, mas os pecadores.”

[[v41-2-18]]

^<<v41-2-18,18>>^ Os discípulos de João e os fariseus praticavam o jejum. Assim, aproximaram-se de Jesus e perguntaram-lhe: “Porque é que os discípulos de João e os discípulos dos fariseus praticam o jejum, mas os teus discípulos não praticam o jejum?”

[[v41-2-19]]

^<<v41-2-19,19>>^ Então, Jesus disse-lhes: “Será que os amigos do noivo têm motivo para jejuar enquanto o noivo está com eles? Enquanto eles têm o noivo consigo, não podem jejuar.

[[v41-2-20]]

^<<v41-2-20,20>>^ Contudo, virão dias em que o noivo lhes será tirado, e então, nesse dia, jejuarão.

[[v41-2-21]]

^<<v41-2-21,21>>^ Ninguém põe um remendo de pano novo^&#42;1^ numa peça de roupa velha. Se fizer isso, o remendo de pano novo repuxará a roupa velha, e o rasgão ficará pior.

[NOTE]
====
. Ou: “pano não pré-encolhido”.
====

[[v41-2-22]]

^<<v41-2-22,22>>^ De igual modo, ninguém põe vinho novo em odres velhos. Se alguém fizer isso, o vinho rebentará os odres, e tanto o vinho como os odres serão perdidos. No entanto, põe-se vinho novo em odres novos.”

[[v41-2-23]]

^<<v41-2-23,23>>^ Ele estava a passar pelos campos de cereais no sábado, e os discípulos começaram a arrancar espigas enquanto caminhavam.

[[v41-2-24]]

^<<v41-2-24,24>>^ Por conseguinte, os fariseus disseram-lhe: “Vê! Porque é que eles estão a fazer o que não é permitido no sábado?”

[[v41-2-25]]

^<<v41-2-25,25>>^ Mas ele disse-lhes: “Nunca leram o que David fez quando se viu em necessidade, quando ele e os seus homens ficaram com fome?

[[v41-2-26]]

^<<v41-2-26,26>>^ Como, no relato sobre Abiatar, o principal sacerdote, ele entrou na casa de Deus e comeu dos pães da apresentação,^&#42;1^ os quais não é permitido a ninguém comer, a não ser aos sacerdotes, e deu também deles aos homens que estavam com ele?”

[NOTE]
====
. Ou: “proposição”.
====

[[v41-2-27]]

^<<v41-2-27,27>>^ E acrescentou: “O sábado veio à existência por causa do homem, e não o homem por causa do sábado.

[[v41-2-28]]

^<<v41-2-28,28>>^ Portanto, o Filho do Homem é Senhor até mesmo do sábado.”

'''

xref:041-marcos/041-marcos-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-marcos/041-marcos-003.adoc#v41-3-0[Próximo Capítulo &#62;]