include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-13-1]]

^<<v41-13-1,1>>^ Quando ele estava a sair do templo, um dos seus discípulos disse-lhe: “Instrutor, vê que pedras e que edifícios maravilhosos!”

[[v41-13-2]]

^<<v41-13-2,2>>^ No entanto, Jesus disse-lhe: “Vês estes grandes edifícios? De modo algum ficará aqui pedra sobre pedra sem ser derrubada.”

[[v41-13-3]]

^<<v41-13-3,3>>^ Quando ele estava sentado no monte das Oliveiras, com o templo à vista, Pedro, Tiago, João e André perguntaram-lhe em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ “Diz-nos: Quando é que acontecerão estas coisas e qual será o sinal de que todas estas coisas estão prestes a chegar a um fim?”

[[v41-13-5]]

^<<v41-13-5,5>>^ Assim, Jesus começou a dizer-lhes: “Tenham cuidado para que ninguém vos engane.

[[v41-13-6]]

^<<v41-13-6,6>>^ Muitos virão em meu nome, dizendo: ‘Sou eu’, e enganarão muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ Além disso, quando ouvirem falar de guerras e notícias de guerras, não fiquem apavorados. Estas coisas têm de acontecer, mas ainda não é o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ “Porque nação se levantará contra nação e reino contra reino; haverá terramotos num lugar após outro; também haverá falta de alimentos. Estas coisas são um começo das dores de aflição.

[[v41-13-9]]

^<<v41-13-9,9>>^ “Quanto a vocês, tomem cuidado. As pessoas irão entregar-vos aos tribunais locais, e serão espancados nas sinagogas, e serão postos diante de governadores e reis, por minha causa, para lhes darem testemunho.

[[v41-13-10]]

^<<v41-13-10,10>>^ Também, em todas as nações, as boas novas têm de ser pregadas primeiro.

[[v41-13-11]]

^<<v41-13-11,11>>^ E, quando vos levarem para vos entregar, não fiquem preocupados^&#42;1^ com o que dizer, mas digam o que vos for dado nessa hora. Pois quem fala não são vocês, mas é o espírito santo.

[NOTE]
====
. Ou: “ansiosos antecipadamente”.
====

[[v41-13-12]]

^<<v41-13-12,12>>^ Além disso, irmão entregará irmão à morte, e o pai entregará o filho, e os filhos irão levantar-se contra os pais e farão com que sejam mortos.

[[v41-13-13]]

^<<v41-13-13,13>>^ E vocês serão odiados por todos, por causa do meu nome. Mas quem perseverar^&#42;1^ até ao fim será salvo.

[NOTE]
====
. Ou: “persevera”.
====

[[v41-13-14]]

^<<v41-13-14,14>>^ “No entanto, quando virem a coisa repugnante que causa desolação estar^&#42;1^ num lugar onde não devia (que o leitor use de discernimento), então, os que estiverem na Judeia fujam para os montes.

[NOTE]
====
. Ou: “estar de pé”.
====

[[v41-13-15]]

^<<v41-13-15,15>>^ O homem que estiver no terraço não desça, nem entre para tirar algo da sua casa,

[[v41-13-16]]

^<<v41-13-16,16>>^ e o homem que estiver no campo não volte ao que deixou atrás, para apanhar a sua capa.

[[v41-13-17]]

^<<v41-13-17,17>>^ Ai das mulheres grávidas e das que amamentarem nesses dias!

[[v41-13-18]]

^<<v41-13-18,18>>^ Persistam em orar para que isso não ocorra no inverno;

[[v41-13-19]]

^<<v41-13-19,19>>^ pois esses dias serão dias de tribulação, como nunca ocorreu desde o princípio da criação, que Deus criou, até agora,^&#42;1^ nem ocorrerá de novo.

[NOTE]
====
. Ou: “até esse tempo”.
====

[[v41-13-20]]

^<<v41-13-20,20>>^ De facto, se Jeová^&#42;1^ não tivesse abreviado os dias, ninguém seria salvo. Mas, por causa dos escolhidos, que ele escolheu, abreviou os dias.

[NOTE]
====
. Veja o Ap. A5.
====

[[v41-13-21]]

^<<v41-13-21,21>>^ “Então, também, se alguém vos disser: ‘Vejam! Aqui está o Cristo!’ ou ‘Vejam! Ali está ele!’, não acreditem.

[[v41-13-22]]

^<<v41-13-22,22>>^ Porque surgirão falsos cristos e falsos profetas, e farão sinais e milagres a fim de desencaminhar, se possível, os escolhidos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Portanto, sejam vigilantes. Eu disse-vos tudo antecipadamente.

[[v41-13-24]]

^<<v41-13-24,24>>^ “Mas, nesses dias, depois dessa tribulação, o sol escurecerá, a lua não dará a sua luz,

[[v41-13-25]]

^<<v41-13-25,25>>^ as estrelas cairão do céu, e os poderes que estão nos céus serão abalados.

[[v41-13-26]]

^<<v41-13-26,26>>^ E, então, verão o Filho do Homem vir nas nuvens, com grande poder e glória.

[[v41-13-27]]

^<<v41-13-27,27>>^ E então ele enviará os anjos e reunirá os seus escolhidos desde os quatro ventos, desde a extremidade da terra até à extremidade do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ “Aprendam desta ilustração sobre a figueira: assim que os ramos novos ficam tenros e brotam folhas, vocês sabem que o verão está próximo.

[[v41-13-29]]

^<<v41-13-29,29>>^ Do mesmo modo, quando virem estas coisas a acontecer, saibam que ele^&#42;1^ está próximo, às portas.

[NOTE]
====
. Isto é, o Filho do Homem.
====

[[v41-13-30]]

^<<v41-13-30,30>>^ Eu garanto-vos que esta geração de modo algum passará até que todas estas coisas aconteçam.

[[v41-13-31]]

^<<v41-13-31,31>>^ O céu e a terra passarão, mas as minhas palavras de modo algum passarão.

[[v41-13-32]]

^<<v41-13-32,32>>^ “A respeito desse dia ou dessa hora ninguém sabe, nem os anjos no céu, nem o Filho, mas somente o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ Sejam vigilantes, mantenham-se despertos, pois não sabem quando é o tempo determinado.

[[v41-13-34]]

^<<v41-13-34,34>>^ É semelhante a um homem que, ao viajar para fora, deixou a sua casa e deu autoridade aos seus escravos, a cada um o seu trabalho, e ordenou ao porteiro que se mantivesse vigilante.

[[v41-13-35]]

^<<v41-13-35,35>>^ Portanto, mantenham-se vigilantes, pois não sabem quando é que virá o senhor da casa, quer tarde no dia, quer à meia-noite, quer antes do amanhecer,^&#42;1^ quer de manhã cedo,

[NOTE]
====
. Lit.: “quando o galo canta”.
====

[[v41-13-36]]

^<<v41-13-36,36>>^ a fim de que, quando ele vier de repente, não vos encontre a dormir.

[[v41-13-37]]

^<<v41-13-37,37>>^ Contudo, o que eu vos digo, digo a todos: Mantenham-se vigilantes.”

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]