include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-5-1]]

^<<v41-5-1,1>>^ Chegaram então à outra margem do mar, à região dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ E, assim que Jesus saiu do barco, um homem sob o poder de um espírito impuro saiu dentre os túmulos^&#42;1^ e foi ao seu encontro.

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v41-5-3]]

^<<v41-5-3,3>>^ Ele vivia entre os túmulos, e, até àquele momento, absolutamente ninguém tinha sido capaz de o manter preso, nem mesmo com uma corrente.

[[v41-5-4]]

^<<v41-5-4,4>>^ Muitas vezes tinha sido preso com correntes nos pés e nas mãos, mas rebentava as correntes das mãos e despedaçava as dos pés; e ninguém tinha força para dominá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ E, incessantemente, noite e dia, ele gritava entre os túmulos e pelos montes, e cortava-se com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Mas, ao avistar Jesus a certa distância, correu e curvou-se diante dele.

[[v41-5-7]]

^<<v41-5-7,7>>^ Então, gritou, em voz bem alta: “O que é que queres de mim,^&#42;1^ Jesus, Filho do Deus Altíssimo? Jura por Deus que não me atormentarás.”

[NOTE]
====
. Ou: “O que é que eu tenho a ver contigo”.
====

[[v41-5-8]]

^<<v41-5-8,8>>^ Pois Jesus tinha-lhe dito: “Sai do homem, espírito impuro!”

[[v41-5-9]]

^<<v41-5-9,9>>^ Mas Jesus perguntou-lhe: “Qual é o teu nome?” E ele respondeu: “O meu nome é Legião, porque somos muitos.”

[[v41-5-10]]

^<<v41-5-10,10>>^ E suplicava a Jesus que não mandasse os espíritos para fora daquela região.

[[v41-5-11]]

^<<v41-5-11,11>>^ Havia uma grande vara de porcos a pastar no monte.

[[v41-5-12]]

^<<v41-5-12,12>>^ Por isso os espíritos suplicaram-lhe: “Manda-nos para os porcos, para que entremos neles.”

[[v41-5-13]]

^<<v41-5-13,13>>^ E ele deu-lhes permissão. Assim, os espíritos impuros saíram e entraram nos porcos; e os porcos atiraram-se pelo despenhadeiro^&#42;1^ abaixo, para o mar, cerca de 2000 deles, e afogaram-se no mar.

[NOTE]
====
. Ou: “pela encosta íngreme”.
====

[[v41-5-14]]

^<<v41-5-14,14>>^ Mas os que cuidavam dos porcos fugiram e contaram isso na cidade e na zona rural, e as pessoas foram ver o que tinha acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Assim, aproximaram-se de Jesus e viram o homem possesso, que tivera a legião, sentado, vestido e em perfeito juízo; e ficaram com medo.

[[v41-5-16]]

^<<v41-5-16,16>>^ Também, os que tinham visto tudo aquilo contaram-lhes o que tinha acontecido com o homem possesso e com os porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ Assim, começaram a suplicar a Jesus que saísse daquela região.

[[v41-5-18]]

^<<v41-5-18,18>>^ Quando ele estava a entrar no barco, o homem que tinha estado possesso suplicou-lhe que o deixasse ir com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ No entanto, ele não deixou, mas disse-lhe: “Vai para casa, para os teus parentes, e conta-lhes tudo o que Jeová^&#42;1^ fez por ti e a misericórdia que te demonstrou.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v41-5-20]]

^<<v41-5-20,20>>^ O homem foi-se embora e começou a proclamar em Decápolis^&#42;1^ tudo o que Jesus tinha feito por ele; e todos ficavam admirados.

[NOTE]
====
. Ou: “na região das Dez Cidades”.
====

[[v41-5-21]]

^<<v41-5-21,21>>^ Depois de Jesus ter passado novamente, no barco, para a margem oposta, juntou-se a ele uma grande multidão, e ele estava à beira-mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Chegou então um dos presidentes da sinagoga, chamado Jairo, e, ao vê-lo, prostrou-se aos seus pés.

[[v41-5-23]]

^<<v41-5-23,23>>^ Ele suplicou-lhe muitas vezes: “A minha filhinha está gravemente doente.^&#42;1^ Por favor, vem e põe as mãos sobre ela, para que fique boa e viva.”

[NOTE]
====
. Ou: “está a morrer”.
====

[[v41-5-24]]

^<<v41-5-24,24>>^ Assim, Jesus foi com ele, e uma grande multidão seguia-o e apertava-o.

[[v41-5-25]]

^<<v41-5-25,25>>^ E havia uma mulher que já por 12 anos sofria de um fluxo de sangue.

[[v41-5-26]]

^<<v41-5-26,26>>^ Ela tinha sofrido muito^&#42;1^ às mãos de muitos médicos, e gastara todos os seus recursos, sem ter melhorado, mas, em vez disso, tinha ficado pior.

[NOTE]
====
. Ou: “tinha sido submetida a muitas dores”.
====

[[v41-5-27]]

^<<v41-5-27,27>>^ Tendo ouvido falar de Jesus, ela aproximou-se por trás dele, entre a multidão, e tocou na sua roupa,

[[v41-5-28]]

^<<v41-5-28,28>>^ pois dizia: “Se eu apenas tocar na sua roupa, ficarei boa.”

[[v41-5-29]]

^<<v41-5-29,29>>^ E o fluxo de sangue secou imediatamente, e ela sentiu no corpo que tinha sido curada daquela doença aflitiva.

[[v41-5-30]]

^<<v41-5-30,30>>^ Imediatamente, Jesus percebeu que tinha saído poder dele. Então, virou-se no meio da multidão e perguntou: “Quem é que tocou na minha roupa?”

[[v41-5-31]]

^<<v41-5-31,31>>^ Os seus discípulos disseram-lhe: “Vês que a multidão te aperta, e ainda perguntas: ‘Quem é que me tocou?’”

[[v41-5-32]]

^<<v41-5-32,32>>^ Contudo, ele estava a olhar em volta para ver quem é que tinha feito isso.

[[v41-5-33]]

^<<v41-5-33,33>>^ A mulher, tremendo de medo, sabendo o que lhe tinha acontecido, aproximou-se e prostrou-se diante dele, e disse-lhe toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ Ele disse-lhe: “Filha, a tua fé fez-te ficar boa. Vai em paz e fica curada da tua doença aflitiva.”

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto ele ainda falava, chegaram alguns homens da casa do presidente da sinagoga e disseram: “A tua filha morreu! Porque incomodar mais o Instrutor?”

[[v41-5-36]]

^<<v41-5-36,36>>^ Mas Jesus ouviu as palavras deles e disse ao presidente da sinagoga: “Não tenhas medo,^&#42;1^ apenas exerce fé.”

[NOTE]
====
. Ou: “Para de ter medo”.
====

[[v41-5-37]]

^<<v41-5-37,37>>^ Então, não deixou que ninguém o acompanhasse, a não ser Pedro, Tiago e João, irmão de Tiago.

[[v41-5-38]]

^<<v41-5-38,38>>^ Assim, chegaram à casa do presidente da sinagoga, e ele viu o alvoroço e os que choravam e lamentavam em voz alta.

[[v41-5-39]]

^<<v41-5-39,39>>^ Depois de entrar, disse-lhes: “Porque é que estão a chorar e em alvoroço? A menina não morreu; ela está a dormir.”

[[v41-5-40]]

^<<v41-5-40,40>>^ Em vista disso, começaram a rir-se dele com desprezo. Mas, depois de mandar que todos saíssem, levou consigo o pai e a mãe da menina e os que estavam com ele, e entrou onde a menina estava.

[[v41-5-41]]

^<<v41-5-41,41>>^ Então, pegou na mão da menina, e disse-lhe: “Talita cumi”, que traduzido significa: “Menina, digo-te: Levanta-te!”

[[v41-5-42]]

^<<v41-5-42,42>>^ E a menina levantou-se imediatamente e começou a andar. (Ela tinha 12 anos de idade.) Com isso, eles não conseguiram conter-se de tanta alegria.

[[v41-5-43]]

^<<v41-5-43,43>>^ Mas ele ordenou-lhes vez após vez^&#42;1^ que não deixassem ninguém saber do sucedido, e mandou que dessem à menina algo para comer.

[NOTE]
====
. Ou: “com firmeza”.
====

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]