include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-1-1]]

^<<v41-1-1,1>>^ O princípio das boas novas^&#42;1^ a respeito de Jesus Cristo, o Filho de Deus.

[NOTE]
====
. Ou: “do evangelho”.
====

[[v41-1-2]]

^<<v41-1-2,2>>^ Conforme está escrito em Isaías, o profeta: “(Vê! Enviarei o meu mensageiro à tua frente,^&#42;1^ o qual preparará o teu caminho.)

[NOTE]
====
. Lit.: “diante da tua face”.
====

[[v41-1-3]]

^<<v41-1-3,3>>^ A voz de alguém clama no deserto:^&#42;1^ ‘Preparem o caminho para Jeová!^&#42;2^ Endireitem as suas estradas.’”

[NOTE]
====
. Veja o Glossário.
. Veja o Ap. A5.
====

[[v41-1-4]]

^<<v41-1-4,4>>^ João, o Batizador, estava no deserto, a pregar o batismo em símbolo de arrependimento para o perdão de pecados.

[[v41-1-5]]

^<<v41-1-5,5>>^ E todo o território da Judeia e todos os habitantes de Jerusalém iam ao seu encontro e eram batizados^&#42;1^ por ele no rio Jordão, confessando abertamente os seus pecados.

[NOTE]
====
. Ou: “mergulhados; imersos”.
====

[[v41-1-6]]

^<<v41-1-6,6>>^ João usava roupa de pelo de camelo e um cinto de couro na cintura, e comia gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ Ele pregava: “Alguém mais forte do que eu vem depois de mim, e não sou digno de me abaixar e desatar o cordão das suas sandálias.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu batizei-vos com água, mas ele vai batizar-vos com espírito santo.”

[[v41-1-9]]

^<<v41-1-9,9>>^ No decorrer daqueles dias, Jesus chegou de Nazaré, da Galileia, e foi batizado por João no Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ Imediatamente, ao sair da água, viu os céus a abrirem-se e o espírito descer como pomba sobre ele.

[[v41-1-11]]

^<<v41-1-11,11>>^ E uma voz saiu dos céus: “Tu és o meu Filho, o amado; eu aprovo-te.”

[[v41-1-12]]

^<<v41-1-12,12>>^ E o espírito impeliu-o imediatamente a ir para o deserto.

[[v41-1-13]]

^<<v41-1-13,13>>^ Assim, ficou no deserto 40 dias, e foi tentado por Satanás. Ele estava com os animais selvagens, e os anjos serviam-no.

[[v41-1-14]]

^<<v41-1-14,14>>^ Então, depois de João ter sido preso, Jesus entrou na Galileia, pregando as boas novas de Deus

[[v41-1-15]]

^<<v41-1-15,15>>^ e dizendo: “Chegou o tempo determinado, e o Reino de Deus está próximo. Arrependam-se e tenham fé nas boas novas.”

[[v41-1-16]]

^<<v41-1-16,16>>^ Enquanto andava à beira do mar da Galileia, ele viu Simão e André, irmão de Simão, a lançar as redes ao mar, pois eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ Portanto, Jesus disse-lhes: “Sigam-me, e eu farei de vocês pescadores de homens.”^&#42;1^

[NOTE]
====
. Ou: “pessoas”.
====

[[v41-1-18]]

^<<v41-1-18,18>>^ E eles abandonaram imediatamente as suas redes e seguiram-no.

[[v41-1-19]]

^<<v41-1-19,19>>^ Depois, um pouco mais à frente, ele viu Tiago, filho de Zebedeu, e o seu irmão João, que estavam no barco a consertar as redes,

[[v41-1-20]]

^<<v41-1-20,20>>^ e sem demora chamou-os. Então, eles deixaram o seu pai, Zebedeu, no barco com os empregados e seguiram-no.

[[v41-1-21]]

^<<v41-1-21,21>>^ E entraram em Cafarnaum.
Assim que chegou o sábado, ele entrou na sinagoga e começou a ensinar.

[[v41-1-22]]

^<<v41-1-22,22>>^ E as pessoas ficaram maravilhadas com o seu modo de ensinar, pois ele ensinava-as como quem tinha autoridade, e não como os escribas.

[[v41-1-23]]

^<<v41-1-23,23>>^ Naquele momento, estava na sinagoga um homem sob o poder de um espírito impuro, e ele gritou:

[[v41-1-24]]

^<<v41-1-24,24>>^ “O que queres de nós,^&#42;1^ Jesus Nazareno? Vieste para nos destruir? Eu sei exatamente quem tu és: o Santo de Deus!”

[NOTE]
====
. Ou: “O que é que nós temos a ver contigo”.
====

[[v41-1-25]]

^<<v41-1-25,25>>^ Mas Jesus censurou-o, dizendo: “Cala-te e sai dele!”

[[v41-1-26]]

^<<v41-1-26,26>>^ E o espírito impuro, depois de lançar o homem em convulsão e gritar ao máximo da sua voz, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ Ora, todos ficaram tão pasmados que começaram a discutir o que tinha acontecido, dizendo: “O que é isto? Um novo ensinamento! Ele dá ordens com autoridade até mesmo aos espíritos impuros, e eles obedecem-lhe.”

[[v41-1-28]]

^<<v41-1-28,28>>^ Assim, o relato sobre ele espalhou-se rapidamente em todas as direções, por toda a região da Galileia.

[[v41-1-29]]

^<<v41-1-29,29>>^ Depois, saíram da sinagoga e foram à casa de Simão e André, com Tiago e João.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão estava de cama, com febre, e imediatamente, falaram dela a Jesus.

[[v41-1-31]]

^<<v41-1-31,31>>^ Ele dirigiu-se a ela, pegou-lhe na mão e levantou-a. A febre deixou-a, e ela começou a servi-los.

[[v41-1-32]]

^<<v41-1-32,32>>^ Ao anoitecer, após o pôr do sol, as pessoas levaram até ele todos os doentes e os possessos;

[[v41-1-33]]

^<<v41-1-33,33>>^ e toda a cidade estava reunida em frente à porta.

[[v41-1-34]]

^<<v41-1-34,34>>^ Assim, ele curou muitos que sofriam de várias doenças e expulsou muitos demónios, mas não deixava os demónios falarem, pois sabiam que ele era Cristo.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “sabiam quem ele era”.
====

[[v41-1-35]]

^<<v41-1-35,35>>^ De manhã cedo, quando ainda estava escuro, levantou-se, saiu e foi para um lugar isolado, e ali começou a orar.

[[v41-1-36]]

^<<v41-1-36,36>>^ No entanto, Simão e os que estavam com ele foram à sua procura.

[[v41-1-37]]

^<<v41-1-37,37>>^ Ao encontrá-lo, disseram-lhe: “Todos estão à tua procura.”

[[v41-1-38]]

^<<v41-1-38,38>>^ Mas ele disse-lhes: “Vamos a outro lugar, às cidades vizinhas, para que eu também pregue lá, pois foi para isso que vim.”

[[v41-1-39]]

^<<v41-1-39,39>>^ E ele foi por toda a Galileia, pregando nas sinagogas deles, e expulsando os demónios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Aproximou-se dele também um leproso, suplicando-lhe até de joelhos: “Se apenas quiser, pode purificar-me.”

[[v41-1-41]]

^<<v41-1-41,41>>^ Em vista disso, ele teve pena; e estendeu a mão, tocou no homem e disse-lhe: “Eu quero! Sê purificado.”

[[v41-1-42]]

^<<v41-1-42,42>>^ Imediatamente a lepra desapareceu, e ele ficou purificado.

[[v41-1-43]]

^<<v41-1-43,43>>^ Então, Jesus mandou-o logo embora, depois de lhe ordenar com firmeza:

[[v41-1-44]]

^<<v41-1-44,44>>^ “Cuidado para não contares nada a ninguém, mas vai, mostra-te ao sacerdote e oferece pela tua purificação o que Moisés determinou, para que lhes sirva de testemunho.”

[[v41-1-45]]

^<<v41-1-45,45>>^ Mas, depois de se afastar, o homem começou a proclamar e a divulgar amplamente o acontecido, de modo que Jesus já não podia entrar abertamente numa cidade, mas ficava fora, em lugares isolados. Contudo, pessoas de toda a parte continuavam a vir ao encontro dele.

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]