include::./index.adoc[]

[[v43-14-0]]
=== João, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-14-1]]

^<<v43-14-1,1>>^ “Não se aflija o vosso coração. Exerçam fé em Deus; exerçam fé também em mim.

[[v43-14-2]]

^<<v43-14-2,2>>^ Na casa do meu Pai há muitas moradas. Se não fosse assim, eu vos teria dito, pois vou-me embora para vos preparar um lugar.

[[v43-14-3]]

^<<v43-14-3,3>>^ Também, depois de me ir embora e vos preparar um lugar, virei novamente e irei levar-vos comigo, para que, onde eu estiver, vocês também estejam.

[[v43-14-4]]

^<<v43-14-4,4>>^ E vocês sabem o caminho para onde vou.”

[[v43-14-5]]

^<<v43-14-5,5>>^ Tomé disse-lhe: “Senhor, não sabemos para onde vais. Como é que podemos saber o caminho?”

[[v43-14-6]]

^<<v43-14-6,6>>^ Jesus respondeu-lhe: “Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai senão por mim.

[[v43-14-7]]

^<<v43-14-7,7>>^ Se vocês me conhecessem, conheceriam também o meu Pai. De agora em diante vocês conhecem-no e têm-no visto.”

[[v43-14-8]]

^<<v43-14-8,8>>^ Filipe disse-lhe: “Senhor, mostra-nos o Pai, e isso é suficiente para nós.”

[[v43-14-9]]

^<<v43-14-9,9>>^ Jesus respondeu-lhe: “Já estou convosco há tanto tempo, e ainda não me conheces, Filipe? Quem me vê, vê também o Pai. Como é que tu dizes: ‘Mostra-nos o Pai’?

[[v43-14-10]]

^<<v43-14-10,10>>^ Não acreditas que eu estou em união com o Pai e que o Pai está em união comigo? O que eu vos digo não se origina de mim, mas o Pai, que permanece em união comigo, está a fazer as Suas obras.

[[v43-14-11]]

^<<v43-14-11,11>>^ Acreditem em mim quando digo que estou em união com o Pai e o Pai está em união comigo; ou senão, acreditem por causa das próprias obras.

[[v43-14-12]]

^<<v43-14-12,12>>^ Digo-vos com toda a certeza: Quem exercer fé em mim fará também as obras que eu faço. E ele fará obras maiores do que estas, porque me vou embora para o Pai.

[[v43-14-13]]

^<<v43-14-13,13>>^ Também, tudo o que vocês pedirem em meu nome, eu irei fazê-lo, para que o Pai seja glorificado por meio do Filho.

[[v43-14-14]]

^<<v43-14-14,14>>^ Qualquer coisa que pedirem em meu nome, eu irei fazê-lo.

[[v43-14-15]]

^<<v43-14-15,15>>^ “Se vocês me amam, obedecerão aos meus mandamentos.

[[v43-14-16]]

^<<v43-14-16,16>>^ E eu pedirei ao Pai, e ele irá dar-vos outro ajudador^&#42;1^ para estar convosco para sempre:

[NOTE]
====
. Ou: “consolador”.
====

[[v43-14-17]]

^<<v43-14-17,17>>^ o espírito da verdade, que o mundo não pode receber, porque não o vê nem o conhece. Vocês conhecem-no, porque permanece convosco e está em vocês.

[[v43-14-18]]

^<<v43-14-18,18>>^ Não vos deixarei abandonados.^&#42;1^ Eu virei ter convosco.

[NOTE]
====
. Ou: “órfãos”.
====

[[v43-14-19]]

^<<v43-14-19,19>>^ Em breve o mundo não me verá mais, mas vocês irão ver-me, porque eu vivo e vocês viverão.

[[v43-14-20]]

^<<v43-14-20,20>>^ Nesse dia, vocês saberão que eu estou em união com o meu Pai, e que vocês estão em união comigo, e que eu estou em união convosco.

[[v43-14-21]]

^<<v43-14-21,21>>^ Quem aceita os meus mandamentos e os cumpre é o que me ama. Por sua vez, quem me ama será amado pelo meu Pai, e eu irei amá-lo e irei mostrar-me claramente a ele.”

[[v43-14-22]]

^<<v43-14-22,22>>^ Judas, não o Iscariotes, perguntou-lhe: “Senhor, o que é que aconteceu para que pretendas mostrar-te claramente a nós e não ao mundo?”

[[v43-14-23]]

^<<v43-14-23,23>>^ Jesus respondeu-lhe: “Se alguém me amar, obedecerá à minha palavra, e o meu Pai irá amá-lo, e nós iremos até ele e faremos a nossa morada com ele.

[[v43-14-24]]

^<<v43-14-24,24>>^ Quem não me ama não obedece às minhas palavras. A palavra que ouves não é minha, mas pertence ao Pai, que me enviou.

[[v43-14-25]]

^<<v43-14-25,25>>^ “Digo-vos estas coisas enquanto ainda estou convosco.

[[v43-14-26]]

^<<v43-14-26,26>>^ Mas o ajudador, o espírito santo, que o Pai enviará em meu nome, irá ensinar-vos todas as coisas e fazer-vos lembrar de todas as coisas que eu vos disse.

[[v43-14-27]]

^<<v43-14-27,27>>^ Deixo-vos a paz; dou-vos a minha paz. Não a dou a vocês do modo como o mundo a dá. Não se aflija o vosso coração, nem fiquem com medo.

[[v43-14-28]]

^<<v43-14-28,28>>^ Ouviram que eu vos disse: ‘Vou-me embora e voltarei para vocês.’ Se me amassem, iriam alegrar-se de que vou para o Pai, pois o Pai é maior do que eu.

[[v43-14-29]]

^<<v43-14-29,29>>^ Disse-vos isto antes que ocorra, para que acreditem quando ocorrer.

[[v43-14-30]]

^<<v43-14-30,30>>^ Já não falarei muito mais convosco, pois o governante do mundo está a chegar, e ele não tem nenhum poder sobre mim.

[[v43-14-31]]

^<<v43-14-31,31>>^ Mas, para que o mundo saiba que eu amo o Pai, faço assim como o Pai me ordenou. Levantem-se, vamos embora daqui.

'''

xref:043-joao/043-joao-013.adoc#v43-13-0[&#60; Capítulo Anterior] | <<v43-14-0,Topo>> | xref:043-joao/043-joao-015.adoc#v43-15-0[Próximo Capítulo &#62;]