include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-8-12]]

^<<v43-8-12,12>>^ Então, Jesus dirigiu-se novamente a eles e disse: “Eu sou a luz do mundo. Quem me segue de modo algum andará na escuridão, mas terá a luz da vida.”

[[v43-8-13]]

^<<v43-8-13,13>>^ Os fariseus disseram-lhe então: “Tu dás testemunho de ti mesmo; o teu testemunho não é verdadeiro.”

[[v43-8-14]]

^<<v43-8-14,14>>^ Jesus respondeu-lhes: “Mesmo que eu dê testemunho de mim mesmo, o meu testemunho é verdadeiro, porque eu sei de onde vim e para onde vou. Mas vocês não sabem de onde eu vim nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vocês julgam segundo a carne;^&#42;1^ eu não julgo ninguém.

[NOTE]
====
. Ou: “segundo padrões humanos”.
====

[[v43-8-16]]

^<<v43-8-16,16>>^ Contudo, mesmo que eu julgue, o meu julgamento é verdadeiro, porque não estou sozinho, mas o Pai, que me enviou, está comigo.

[[v43-8-17]]

^<<v43-8-17,17>>^ Também, na vossa própria Lei está escrito: ‘O testemunho de dois homens é verdadeiro.’

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu sou um que dá testemunho de mim mesmo, e o Pai, que me enviou, dá testemunho de mim.”

[[v43-8-19]]

^<<v43-8-19,19>>^ Então, eles perguntaram-lhe: “Onde é que está o teu Pai?” Jesus respondeu: “Vocês não me conhecem, nem a mim nem ao meu Pai. Se me conhecessem, conheceriam também o meu Pai.”

[[v43-8-20]]

^<<v43-8-20,20>>^ Ele disse estas palavras no local onde ficavam os cofres do tesouro, enquanto ensinava no templo. Mas ninguém o prendeu, pois a sua hora ainda não tinha chegado.

[[v43-8-21]]

^<<v43-8-21,21>>^ Novamente, ele disse-lhes: “Eu vou-me embora, e vocês irão procurar-me, contudo morrerão nos vossos pecados. Para onde eu vou, vocês não podem ir.”

[[v43-8-22]]

^<<v43-8-22,22>>^ Então, os judeus começaram a dizer: “Será que ele se vai matar? Porque diz: ‘Para onde eu vou, vocês não podem ir.’”

[[v43-8-23]]

^<<v43-8-23,23>>^ E ele acrescentou: “Vocês são dos domínios de baixo; eu sou dos domínios de cima. Vocês são deste mundo; eu não sou deste mundo.

[[v43-8-24]]

^<<v43-8-24,24>>^ É por isso que eu vos disse: Vocês morrerão nos vossos pecados. Pois, se não acreditarem em quem eu sou, morrerão nos vossos pecados.”

[[v43-8-25]]

^<<v43-8-25,25>>^ Perguntaram-lhe então: “Quem és tu?” Jesus disse-lhes em resposta: “Porque é que eu ainda estou a falar convosco?

[[v43-8-26]]

^<<v43-8-26,26>>^ Tenho muitas coisas para dizer a vosso respeito e para julgar. De facto, Aquele que me enviou é verdadeiro, e aquilo que ouvi dele eu digo ao mundo.”

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles não compreenderam que lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Então, Jesus disse-lhes: “Depois de terem erguido o Filho do Homem, então saberão que eu sou ele e que não faço nada da minha própria iniciativa, mas digo aquilo que o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ E Aquele que me enviou está comigo; ele não me deixou só, porque faço sempre o que lhe agrada.”

[[v43-8-30]]

^<<v43-8-30,30>>^ Quando ele disse estas coisas, muitos depositaram fé nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Então, Jesus disse aos judeus que acreditaram nele: “Se permanecerem nas minhas palavras, são realmente meus discípulos,

[[v43-8-32]]

^<<v43-8-32,32>>^ e conhecerão a verdade, e a verdade irá libertar-vos.”

[[v43-8-33]]

^<<v43-8-33,33>>^ Responderam-lhe: “Somos descendentes de Abraão e nunca fomos escravos de ninguém. Como é que dizes: ‘Vocês ficarão livres’?”

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus respondeu-lhes: “Digo-vos com toda a certeza: Todo aquele que pratica o pecado é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ Além disso, o escravo não permanece na casa para sempre; o filho permanece para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Portanto, se o Filho vos libertar, serão realmente livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Sei que são descendentes de Abraão. Mas procuram matar-me, porque não aceitam as minhas palavras.^&#42;1^

[NOTE]
====
. Ou: “porque a minha palavra não progride entre vocês”.
====

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo do que vi enquanto estava com o meu Pai, mas vocês fazem o que ouviram do vosso pai.”

[[v43-8-39]]

^<<v43-8-39,39>>^ Em resposta, eles disseram-lhe: “O nosso pai é Abraão.” Jesus disse-lhes: “Se fossem filhos de Abraão, fariam as obras de Abraão.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas o facto é que procuram matar-me, a mim, um homem que vos disse a verdade que ouviu de Deus. Abraão não agiu assim.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vocês fazem as obras do vosso pai.” Eles disseram-lhe: “Não nascemos de imoralidade.^&#42;1^ Temos um só Pai, Deus.”

[NOTE]
====
. Ou: “imoralidade sexual”. Em grego, porneía. Veja o Glossário.
====

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus disse-lhes: “Se Deus fosse o vosso Pai, iriam amar-me, pois vim de Deus e estou aqui. Eu não vim da minha própria iniciativa, mas foi ele que me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Porque é que não entendem o que estou a dizer? Porque são incapazes de ouvir as minhas palavras.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vocês são filhos do vosso pai, o Diabo, e querem satisfazer os desejos do vosso pai. Ele foi um assassino quando começou,^&#42;1^ e não permaneceu na verdade, porque não há nele verdade. Quando ele mente, faz o que lhe é próprio, porque é um mentiroso e o pai da mentira.

[NOTE]
====
. Ou: “desde o princípio”.
====

[[v43-8-45]]

^<<v43-8-45,45>>^ Por outro lado, visto que eu vos digo a verdade, não acreditam em mim.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem de vocês me declara culpado de pecado? Se eu digo a verdade, porque é que não acreditam em mim?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus escuta as declarações de Deus. É por isso que vocês não escutam, porque não são de Deus.”

[[v43-8-48]]

^<<v43-8-48,48>>^ Em resposta, os judeus disseram-lhe: “Não temos nós razão em dizer que tu és samaritano e tens um demónio?”

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: “Eu não tenho nenhum demónio, mas honro o meu Pai, e vocês desonram-me.

[[v43-8-50]]

^<<v43-8-50,50>>^ Mas não procuro glória para mim mesmo; há Alguém que a procura, e ele julga.

[[v43-8-51]]

^<<v43-8-51,51>>^ Digo-vos com toda a certeza: Se alguém obedecer às minhas palavras, nunca jamais verá a morte.”

[[v43-8-52]]

^<<v43-8-52,52>>^ Os judeus disseram-lhe: “Agora sabemos que tens um demónio. Abraão morreu, os profetas também, mas tu dizes: ‘Se alguém obedecer às minhas palavras, nunca jamais provará a morte.’

[[v43-8-53]]

^<<v43-8-53,53>>^ Será que tu és maior do que o nosso pai Abraão, que morreu? Os profetas também morreram. Quem é que tu pensas que és?”

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus respondeu: “Se eu me glorificar a mim mesmo, a minha glória não é nada. É o meu Pai quem me glorifica, aquele que vocês dizem ser o vosso Deus.

[[v43-8-55]]

^<<v43-8-55,55>>^ No entanto, vocês não o conhecem, mas eu conheço-o. E, se eu dissesse que não o conheço, seria um mentiroso, como vocês. Mas eu conheço-o e obedeço à sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, o vosso pai, alegrou-se muito com a perspetiva de ver o meu dia, e ele viu-o e alegrou-se.”

[[v43-8-57]]

^<<v43-8-57,57>>^ Então, os judeus disseram-lhe: “Tu ainda nem tens 50 anos, e ainda assim viste Abraão?”

[[v43-8-58]]

^<<v43-8-58,58>>^ Jesus disse-lhes: “Digo-vos com toda a certeza: Antes de Abraão vir à existência, eu já existia.”

[[v43-8-59]]

^<<v43-8-59,59>>^ Assim, apanharam pedras para lhe atirarem, mas Jesus escondeu-se e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]