include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-15-1]]

^<<v43-15-1,1>>^ “Eu sou a verdadeira videira, e o meu Pai é o lavrador.

[[v43-15-2]]

^<<v43-15-2,2>>^ Ele tira todos os ramos que em mim não dão fruto, e limpa todos os ramos que dão fruto, para que deem mais fruto.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vocês já estão limpos, por causa da palavra que vos declarei.

[[v43-15-4]]

^<<v43-15-4,4>>^ Permaneçam em união comigo, e eu permanecerei em união convosco. Assim como um ramo não pode dar fruto por si mesmo a menos que permaneça na videira, vocês também não podem dar fruto a menos que permaneçam em união comigo.

[[v43-15-5]]

^<<v43-15-5,5>>^ Eu sou a videira; vocês são os ramos. Quem permanece em união comigo, e eu em união com ele, esse dá muito fruto, pois separados de mim vocês não podem fazer nada.

[[v43-15-6]]

^<<v43-15-6,6>>^ Se alguém não permanece em união comigo, é lançado fora como um ramo, e seca. Esses ramos são ajuntados, lançados no fogo e queimados.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se vocês permanecerem em união comigo e as minhas declarações permanecerem em vocês, peçam o que quiserem e assim vos acontecerá.

[[v43-15-8]]

^<<v43-15-8,8>>^ Isto glorifica o meu Pai: que persistam em dar muito fruto e mostrem que são meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Assim como o Pai me ama, eu também vos amo; permaneçam no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se obedecerem aos meus mandamentos, permanecerão no meu amor, assim como eu obedeço aos mandamentos do Pai e permaneço no seu amor.

[[v43-15-11]]

^<<v43-15-11,11>>^ “Disse-vos estas coisas para que sintam a mesma alegria que eu,^&#42;1^ e a vossa alegria se torne plena.

[NOTE]
====
. Ou: “para que a minha alegria esteja em vocês”.
====

[[v43-15-12]]

^<<v43-15-12,12>>^ Este é o meu mandamento: Amem-se uns aos outros, assim como eu vos amei.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que aquele que dá a sua vida^&#42;1^ pelos seus amigos.

[NOTE]
====
. Ou: “alma”.
====

[[v43-15-14]]

^<<v43-15-14,14>>^ Vocês são meus amigos se fizerem o que vos mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Já não vos chamo escravos, porque o escravo não sabe o que o seu senhor faz. Mas chamo-vos amigos, porque vos revelei tudo o que ouvi do meu Pai.

[[v43-15-16]]

^<<v43-15-16,16>>^ Vocês não me escolheram, mas eu vos escolhi, e designei-vos para irem e continuarem a dar fruto, fruto que permaneça, para que, não importa o que peçam ao Pai em meu nome, ele vo-lo dê.

[[v43-15-17]]

^<<v43-15-17,17>>^ “Ordeno-vos estas coisas para que se amem uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Se o mundo vos odeia, sabem^&#42;1^ que me odiou a mim antes de vos odiar.

[NOTE]
====
. Ou: “saibam”.
====

[[v43-15-19]]

^<<v43-15-19,19>>^ Se fizessem parte do mundo, o mundo iria amar-vos por lhe pertencerem. Agora, visto que não fazem parte do mundo, mas eu vos escolhi do mundo, por isso é que o mundo vos odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrem-se do que eu vos disse: O escravo não é maior do que o seu senhor. Se me perseguiram a mim, também vos perseguirão; se obedeceram às minhas palavras, também obedecerão às vossas.

[[v43-15-21]]

^<<v43-15-21,21>>^ Mas farão todas estas coisas contra vocês por causa do meu nome, porque não conhecem Aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não tivesse vindo e falado com eles, não seriam culpados de pecado. Mas, agora, eles não têm desculpa para o seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Quem me odeia, também odeia o meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse feito entre eles as obras que mais ninguém fez, não seriam culpados de pecado; mas, agora, eles viram-me e odiaram-me a mim e ao meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas isto aconteceu para que se cumprissem as palavras escritas na Lei deles: ‘Odiaram-me sem motivo.’

[[v43-15-26]]

^<<v43-15-26,26>>^ Quando vier o ajudador que eu vos enviarei da parte do Pai, o espírito da verdade, que vem do Pai, esse dará testemunho de mim;

[[v43-15-27]]

^<<v43-15-27,27>>^ e vocês, por vossa vez, darão testemunho, porque estiveram comigo desde o começo.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]