include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-18-1]]

^<<v43-18-1,1>>^ Depois de dizer estas coisas, Jesus saiu com os seus discípulos para o outro lado do vale^&#42;1^ do Cédron; havia ali um jardim, onde ele e os seus discípulos entraram.

[NOTE]
====
. Ou: “da torrente de inverno”.
====

[[v43-18-2]]

^<<v43-18-2,2>>^ Judas, aquele que o estava a trair, também conhecia o lugar, porque Jesus se tinha reunido ali muitas vezes com os seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Assim, Judas, trazendo o destacamento de soldados e os guardas^&#42;1^ enviados pelos principais sacerdotes e pelos fariseus, chegou ali com tochas, lâmpadas e armas.

[NOTE]
====
. Ou: “guardas do templo”.
====

[[v43-18-4]]

^<<v43-18-4,4>>^ Então, Jesus, sabendo tudo o que lhe ia acontecer, deu um passo em frente e disse-lhes: “Quem é que procuram?”

[[v43-18-5]]

^<<v43-18-5,5>>^ Responderam-lhe: “Jesus, o Nazareno.” Ele disse-lhes: “Sou eu.” Judas, o traidor, também estava com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ No entanto, quando Jesus lhes disse: “Sou eu”, eles recuaram e caíram no chão.

[[v43-18-7]]

^<<v43-18-7,7>>^ Então, perguntou-lhes novamente: “Quem é que procuram?” Disseram: “Jesus, o Nazareno.”

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus respondeu: “Disse-vos que sou eu. Então, se é a mim que procuram, deixem estes homens irem-se embora.”

[[v43-18-9]]

^<<v43-18-9,9>>^ Isto aconteceu para que se cumprisse o que ele tinha dito: “Não perdi nem sequer um daqueles que me deste.”

[[v43-18-10]]

^<<v43-18-10,10>>^ Então, Simão Pedro puxou da espada que tinha, e atacou o escravo do sumo sacerdote, cortando-lhe a orelha direita. O nome do escravo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Mas Jesus disse a Pedro: “Põe a espada na bainha. Não devo eu beber o cálice que o Pai me deu?”

[[v43-18-12]]

^<<v43-18-12,12>>^ Então, os soldados, o comandante militar e os guardas dos judeus prenderam Jesus e amarraram-no.

[[v43-18-13]]

^<<v43-18-13,13>>^ Eles levaram-no primeiro a Anás, por ser sogro de Caifás, o sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ De facto, Caifás é que tinha dito aos judeus que era para o bem deles que um só homem morresse a favor do povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro, assim como outro discípulo, seguia Jesus. Este discípulo era conhecido do sumo sacerdote e entrou com Jesus no pátio do sumo sacerdote,

[[v43-18-16]]

^<<v43-18-16,16>>^ mas Pedro ficou do lado de fora, à porta.^&#42;1^ Portanto, o outro discípulo, que era conhecido do sumo sacerdote, saiu, falou com a porteira e levou Pedro para dentro.

[NOTE]
====
. Ou: “entrada”.
====

[[v43-18-17]]

^<<v43-18-17,17>>^ A serva, que era a porteira, perguntou então a Pedro: “Não és tu também um dos discípulos desse homem?” Ele respondeu: “Não sou.”

[[v43-18-18]]

^<<v43-18-18,18>>^ Os escravos e os guardas estavam à volta de um braseiro que tinham acendido, porque estava frio, e aqueciam-se. Pedro também estava com eles e aquecia-se.

[[v43-18-19]]

^<<v43-18-19,19>>^ Então, o principal sacerdote interrogou Jesus sobre os seus discípulos e sobre os seus ensinamentos.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus respondeu-lhe: “Falei publicamente ao mundo. Sempre ensinei nas sinagogas e no templo, onde todos os judeus se reúnem, e não disse nada em segredo.

[[v43-18-21]]

^<<v43-18-21,21>>^ Porque é que me interroga? Interrogue os que ouviram o que eu lhes disse. Eles certamente sabem o que eu disse.”

[[v43-18-22]]

^<<v43-18-22,22>>^ Depois de Jesus ter dito isto, um dos guardas que estava lá deu-lhe uma bofetada e disse: “É assim que respondes ao principal sacerdote?”

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus respondeu-lhe: “Se disse algo errado, diga-me^&#42;1^ o que foi que eu disse de errado; mas, se o que eu disse está certo, porque é que me bate?”

[NOTE]
====
. Ou: “testifique”.
====

[[v43-18-24]]

^<<v43-18-24,24>>^ Então, Anás mandou-o amarrado para Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Simão Pedro estava ali e aquecia-se. Então, perguntaram-lhe: “Não és tu também um dos discípulos dele?” Ele negou, dizendo: “Não sou.”

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos escravos do sumo sacerdote, parente do homem cuja orelha Pedro tinha cortado, perguntou: “Não te vi eu no jardim com ele?”

[[v43-18-27]]

^<<v43-18-27,27>>^ No entanto, Pedro negou-o outra vez, e imediatamente cantou um galo.

[[v43-18-28]]

^<<v43-18-28,28>>^ Então, levaram Jesus de Caifás para a residência do governador. Já era de manhã cedo. Mas eles mesmos não entraram na residência do governador, para que não ficassem impuros, mas pudessem comer a refeição pascoal.

[[v43-18-29]]

^<<v43-18-29,29>>^ Portanto, Pilatos foi ao encontro deles e perguntou: “Que acusação levantam contra este homem?”

[[v43-18-30]]

^<<v43-18-30,30>>^ Responderam-lhe: “Se este homem não fosse um criminoso,^&#42;1^ não o teríamos entregado a si.”

[NOTE]
====
. Ou: “malfeitor”.
====

[[v43-18-31]]

^<<v43-18-31,31>>^ Assim, Pilatos disse-lhes: “Levem-no vocês mesmos e julguem-no segundo a vossa lei.” Os judeus disseram-lhe: “Não nos é permitido matar ninguém.”

[[v43-18-32]]

^<<v43-18-32,32>>^ Isto aconteceu para que se cumprissem as palavras que Jesus tinha dito, indicando o tipo de morte que estava para sofrer.

[[v43-18-33]]

^<<v43-18-33,33>>^ Então, Pilatos entrou novamente na residência do governador, chamou Jesus e perguntou-lhe: “És tu o Rei dos judeus?”

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus disse: “É da sua própria iniciativa que o pergunta, ou foram outros que lhe falaram sobre mim?”

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilatos respondeu: “Por acaso, sou judeu? A tua própria nação e os principais sacerdotes entregaram-te a mim. O que é que fizeste?”

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus respondeu: “O meu Reino não faz parte deste mundo. Se o meu Reino fizesse parte deste mundo, os meus assistentes teriam lutado para que eu não fosse entregue aos judeus. Mas o facto é que o meu Reino não é desta fonte.”

[[v43-18-37]]

^<<v43-18-37,37>>^ Então, Pilatos perguntou-lhe: “Mas, então, és tu rei?” Jesus respondeu: “É o senhor que está a dizer que eu sou rei. Para isto nasci e para isto vim ao mundo: para dar testemunho da verdade. Todo aquele que está do lado da verdade escuta a minha voz.”

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilatos disse-lhe: “O que é verdade?”
Depois de dizer isto, foi novamente ter com os judeus e disse-lhes: “Não vejo motivo para o acusar.

[[v43-18-39]]

^<<v43-18-39,39>>^ Além disso, vocês têm o costume de que eu liberte um homem na altura da Páscoa. Portanto, querem que eu solte o Rei dos judeus?”

[[v43-18-40]]

^<<v43-18-40,40>>^ Eles gritaram outra vez: “Este homem não; queremos Barrabás!” Ora, Barrabás era um bandido.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]