include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disto, Jesus apareceu novamente aos discípulos junto ao mar de Tiberíades. Ele apareceu do seguinte modo:

[[v43-21-2]]

^<<v43-21-2,2>>^ estavam juntos Simão Pedro, Tomé (que era chamado Gémeo), Natanael, de Caná da Galileia, os filhos de Zebedeu e mais dois dos seus discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simão Pedro disse-lhes: “Vou pescar.” Eles disseram-lhe: “Nós vamos contigo.” Assim, foram e entraram no barco, mas durante aquela noite não apanharam nada.

[[v43-21-4]]

^<<v43-21-4,4>>^ Ao amanhecer, Jesus estava na praia, mas os discípulos não perceberam que era Jesus.

[[v43-21-5]]

^<<v43-21-5,5>>^ Então, Jesus perguntou-lhes: “Filhos, têm alguma coisa^&#42;1^ para comer?” Eles responderam: “Não.”

[NOTE]
====
. Ou: “algum peixe”.
====

[[v43-21-6]]

^<<v43-21-6,6>>^ Ele disse-lhes: “Lancem a rede do lado direito do barco e encontrarão alguma coisa.” Assim, eles lançaram-na, mas não a conseguiam recolher, por causa da grande quantidade de peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Então, o discípulo a quem Jesus amava disse a Pedro: “É o Senhor!” Ao ouvir que era o Senhor, Simão Pedro vestiu a^&#42;1^ sua roupa, pois estava nu,^&#42;2^ e lançou-se ao mar.

[NOTE]
====
. Ou: “cingiu-se da”.
. Ou: “pouco vestido”.
====

[[v43-21-8]]

^<<v43-21-8,8>>^ Mas os outros discípulos vieram no pequeno barco, arrastando a rede cheia de peixes, pois não estavam longe da terra, a apenas cerca de 90 metros.^&#42;1^

[NOTE]
====
. Lit.: “cerca de 200 côvados”. Veja o Ap. B14.
====

[[v43-21-9]]

^<<v43-21-9,9>>^ Quando desembarcaram, viram ali um fogo, com peixe sobre as brasas, e pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus disse-lhes: “Tragam alguns dos peixes que acabaram de apanhar.”

[[v43-21-11]]

^<<v43-21-11,11>>^ Então, Simão Pedro subiu a bordo e puxou a rede para a terra; ela estava cheia de peixes, 153 peixes grandes. Embora houvesse tantos, a rede não se rompeu.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus disse-lhes: “Venham comer.” Nenhum dos discípulos tinha coragem de lhe perguntar quem ele era, porque sabiam que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Jesus foi, pegou no pão e deu-lhes, e fez o mesmo com o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ Esta foi a terceira vez que Jesus apareceu aos discípulos depois de ter sido levantado dentre os mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Quando acabaram de comer, Jesus perguntou a Simão Pedro: “Simão, filho de João, amas-me mais do que a estes?” Ele respondeu-lhe: “Sim, Senhor, tu sabes que eu te amo.”^&#42;1^ Ele disse-lhe: “Alimenta os meus cordeiros.”

[NOTE]
====
. Ou: “que eu tenho afeição por ti”.
====

[[v43-21-16]]

^<<v43-21-16,16>>^ Perguntou-lhe novamente, pela segunda vez: “Simão, filho de João, amas-me?” Ele respondeu-lhe: “Sim, Senhor, tu sabes que eu te amo.”^&#42;1^ Ele disse-lhe: “Pastoreia as minhas ovelhinhas.”

[NOTE]
====
. Ou: “que eu tenho afeição por ti”.
====

[[v43-21-17]]

^<<v43-21-17,17>>^ Ele perguntou-lhe pela terceira vez: “Simão, filho de João, amas-me?”^&#42;1^ Pedro ficou triste por ele lhe perguntar pela terceira vez: “Amas-me?”^&#42;2^ Por isso, ele disse-lhe: “Senhor, tu sabes todas as coisas. Sabes que eu te amo.”^&#42;3^ Jesus disse-lhe: “Alimenta as minhas ovelhinhas.

[NOTE]
====
. Ou: “tens afeição por mim”.
. Ou: “Tens afeição por mim?”.
. Ou: “que eu tenho afeição por ti”.
====

[[v43-21-18]]

^<<v43-21-18,18>>^ Digo-te com toda a certeza: Quando eras mais jovem, vestias-te e andavas por onde querias. Mas, quando envelheceres, estenderás as mãos, e outro homem te vestirá e te levará para onde tu não queres.”

[[v43-21-19]]

^<<v43-21-19,19>>^ Disse isto para indicar com que tipo de morte ele glorificaria a Deus. Depois de dizer isto, disse-lhe: “Continua a seguir-me.”

[[v43-21-20]]

^<<v43-21-20,20>>^ Pedro virou-se e viu que o discípulo que Jesus amava os seguia, aquele que na refeição se tinha encostado ao peito dele e dito: “Senhor, quem é que te trai?”

[[v43-21-21]]

^<<v43-21-21,21>>^ Portanto, quando o viu, Pedro disse a Jesus: “Senhor, e o que acontecerá a este homem?”

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus disse-lhe: “Se eu quiser que ele permaneça até eu vir, o que é que isso te importa? Continua tu a seguir-me.”

[[v43-21-23]]

^<<v43-21-23,23>>^ Assim, espalhou-se entre os irmãos que esse discípulo não ia morrer. No entanto, Jesus não lhe disse que ele não ia morrer, mas disse: “Se eu quiser que ele permaneça até eu vir, o que é que isso te importa?”

[[v43-21-24]]

^<<v43-21-24,24>>^ Esse é o discípulo que dá testemunho destas coisas e que escreveu estas coisas, e nós sabemos que o seu testemunho é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ De facto, há também muitas outras coisas que Jesus fez. Se fossem escritas em todos os pormenores, suponho que o próprio mundo não poderia conter os rolos escritos.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]