include::./index.adoc[]

[[v43-17-0]]
=== João, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-17-1]]

^<<v43-17-1,1>>^ Jesus disse estas coisas e, levantando os olhos para o céu, orou: “Pai, chegou a hora. Glorifica o teu filho, para que o teu filho te glorifique,

[[v43-17-2]]

^<<v43-17-2,2>>^ assim como lhe deste autoridade sobre todas as pessoas,^&#42;1^ para que ele dê vida eterna a todos aqueles que lhe deste.

[NOTE]
====
. Ou: “toda a humanidade”. Lit.: “toda a carne”.
====

[[v43-17-3]]

^<<v43-17-3,3>>^ Isto significa vida eterna: que te conheçam a ti,^&#42;1^ o único Deus verdadeiro, e àquele que tu enviaste, Jesus Cristo.

[NOTE]
====
. Ou: “que assimilem conhecimento de ti”. O verbo grego indica ação contínua.
====

[[v43-17-4]]

^<<v43-17-4,4>>^ Glorifiquei-te na terra e terminei a obra que me deste para fazer.

[[v43-17-5]]

^<<v43-17-5,5>>^ E agora, Pai, glorifica-me ao teu lado com a glória que eu tive junto de ti antes de o mundo existir.

[[v43-17-6]]

^<<v43-17-6,6>>^ “Tornei o teu nome conhecido aos homens que me deste do mundo. Eles eram teus, e tu deste-mos a mim, e eles obedeceram à tua palavra.

[[v43-17-7]]

^<<v43-17-7,7>>^ Agora, eles sabem que todas as coisas que me deste vêm de ti,

[[v43-17-8]]

^<<v43-17-8,8>>^ porque eu lhes transmiti as declarações que me deste, e eles aceitaram-nas e certamente sabem que vim como teu representante, e acreditam que tu me enviaste.

[[v43-17-9]]

^<<v43-17-9,9>>^ Peço-te por eles; peço-te, não pelo mundo, mas por aqueles que me deste, porque eles são teus;

[[v43-17-10]]

^<<v43-17-10,10>>^ e todas as minhas coisas são tuas, e as tuas são minhas, e eu fui glorificado entre eles.

[[v43-17-11]]

^<<v43-17-11,11>>^ “Já não estou no mundo, mas eles estão no mundo, e eu vou para ti. Santo Pai, vigia sobre eles por causa do teu nome, o nome que me deste, para que sejam um,^&#42;1^ assim como nós somos um.^&#42;2^

[NOTE]
====
. Ou: “estejam em união”.
. Ou: “estamos em união”.
====

[[v43-17-12]]

^<<v43-17-12,12>>^ Quando eu estava com eles, vigiava sobre eles por causa do teu nome, o nome que me deste; e protegi-os, e nenhum deles se perdeu,^&#42;1^ exceto o filho da destruição, para que se cumprisse a passagem das Escrituras.

[NOTE]
====
. Ou: “está destruído”.
====

[[v43-17-13]]

^<<v43-17-13,13>>^ Mas agora eu vou para ti e digo estas coisas no mundo, para que eles sintam plenamente a minha alegria.

[[v43-17-14]]

^<<v43-17-14,14>>^ Dei-lhes a tua palavra, mas o mundo odeia-os, porque não fazem parte do mundo, assim como eu não faço parte do mundo.

[[v43-17-15]]

^<<v43-17-15,15>>^ “Não te peço que os tires do mundo, mas que vigies sobre eles, por causa do Maligno.

[[v43-17-16]]

^<<v43-17-16,16>>^ Eles não fazem parte do mundo, assim como eu não faço parte do mundo.

[[v43-17-17]]

^<<v43-17-17,17>>^ Santifica-os^&#42;1^ por meio da verdade; a tua palavra é a verdade.

[NOTE]
====
. Ou: “Coloca-os à parte; Torna-os santos”.
====

[[v43-17-18]]

^<<v43-17-18,18>>^ Assim como tu me enviaste ao mundo, eu também os enviei ao mundo.

[[v43-17-19]]

^<<v43-17-19,19>>^ E santifico-me em seu benefício, para que eles também sejam santificados por meio da verdade.

[[v43-17-20]]

^<<v43-17-20,20>>^ “Peço-te não somente por estes, mas também por aqueles que depositem fé em mim por meio das palavras deles,

[[v43-17-21]]

^<<v43-17-21,21>>^ para que todos sejam um, assim como tu, Pai, estás em união comigo e eu estou em união contigo, para que eles também estejam em união connosco, a fim de que o mundo acredite que tu me enviaste.

[[v43-17-22]]

^<<v43-17-22,22>>^ Dei-lhes a glória que tu me deste, a fim de que eles sejam um, assim como nós somos um.

[[v43-17-23]]

^<<v43-17-23,23>>^ Eu em união com eles, e tu em união comigo, a fim de que estejam perfeitamente unidos,^&#42;1^ para que o mundo saiba que tu me enviaste e que os amaste assim como me amaste.

[NOTE]
====
. Ou: “sejam aperfeiçoados em um”.
====

[[v43-17-24]]

^<<v43-17-24,24>>^ Pai, quero que aqueles que me deste estejam comigo onde eu estiver, para que vejam a glória que me deste, porque me amaste antes da fundação do mundo.

[[v43-17-25]]

^<<v43-17-25,25>>^ Justo Pai, o mundo realmente não te conhece, mas eu conheço-te, e estes sabem que tu me enviaste.

[[v43-17-26]]

^<<v43-17-26,26>>^ Eu dei-lhes a conhecer o teu nome, e hei de dá-lo a conhecer, para que o amor com que me amaste esteja neles, e eu em união com eles.”

'''

xref:043-joao/043-joao-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-joao/043-joao-018.adoc#v43-18-0[Próximo Capítulo &#62;]