include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana, Maria Madalena chegou cedo ao túmulo,^&#42;1^ enquanto ainda estava escuro, e viu que a pedra já tinha sido retirada do túmulo.^&#42;2^

[NOTE]
====
. Ou: “túmulo memorial”.
. Ou: “túmulo memorial”.
====

[[v43-20-2]]

^<<v43-20-2,2>>^ Assim, ela foi a correr ter com Simão Pedro e com o outro discípulo, a quem Jesus amava,^&#42;1^ e disse-lhes: “Retiraram o Senhor do túmulo, e não sabemos onde o colocaram.”

[NOTE]
====
. Ou: “tinha afeição”.
====

[[v43-20-3]]

^<<v43-20-3,3>>^ Então, Pedro e o outro discípulo partiram em direção ao túmulo.

[[v43-20-4]]

^<<v43-20-4,4>>^ Os dois começaram a correr juntos, mas o outro discípulo correu mais rápido do que Pedro e chegou primeiro ao túmulo.

[[v43-20-5]]

^<<v43-20-5,5>>^ Inclinando-se para a frente, ele viu os panos de linho deixados ali, mas não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Depois, Simão Pedro, que o seguia, também chegou, entrou no túmulo e viu os panos de linho deixados ali.

[[v43-20-7]]

^<<v43-20-7,7>>^ O pano que tinha sido posto na cabeça dele já não estava ali com as outras faixas, mas estava enrolado num lugar à parte.

[[v43-20-8]]

^<<v43-20-8,8>>^ Então, o outro discípulo, que tinha chegado primeiro ao túmulo, também entrou, viu e acreditou.

[[v43-20-9]]

^<<v43-20-9,9>>^ Porque eles ainda não entendiam a passagem das Escrituras que dizia que ele tinha de ser levantado dentre os mortos.

[[v43-20-10]]

^<<v43-20-10,10>>^ Assim, os discípulos voltaram para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria, porém, ficou a chorar do lado de fora, perto do túmulo. Enquanto chorava, ela inclinou-se para a frente a fim de olhar para dentro do túmulo

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos de branco sentados no lugar onde o corpo de Jesus tinha sido colocado, um à cabeceira e outro aos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ Eles perguntaram-lhe: “Mulher, porque é que está a chorar?” Ela respondeu-lhes: “Levaram o meu Senhor, e não sei onde o colocaram.”

[[v43-20-14]]

^<<v43-20-14,14>>^ Depois de dizer isto, ela virou-se e viu Jesus ali, de pé, mas não percebeu que era Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Jesus perguntou-lhe: “Mulher, porque é que estás a chorar? A quem procuras?” Pensando que fosse o jardineiro, ela disse-lhe: “Se o senhor o tirou daqui, diga-me onde o colocou, e eu irei levá-lo.”

[[v43-20-16]]

^<<v43-20-16,16>>^ Jesus disse-lhe: “Maria!” Voltando-se para ele, ela disse em hebraico: “Raboni!” (que significa: “Instrutor!”).

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus disse-lhe: “Para de me agarrar, porque ainda não subi para o Pai. Mas vai ter com os meus irmãos e diz-lhes: ‘Eu vou subir para o meu Pai e vosso Pai, para o meu Deus e vosso Deus.’”

[[v43-20-18]]

^<<v43-20-18,18>>^ Maria Madalena foi e levou a notícia aos discípulos: “Eu vi o Senhor!” E contou-lhes o que ele lhe tinha dito.

[[v43-20-19]]

^<<v43-20-19,19>>^ Já era tarde naquele dia, o primeiro dia da semana, e as portas do lugar onde os discípulos se encontravam estavam trancadas, por medo dos judeus. Jesus apareceu então no meio deles e disse-lhes: “Que a paz esteja convosco.”

[[v43-20-20]]

^<<v43-20-20,20>>^ Depois de dizer isto, ele mostrou-lhes as suas mãos e o seu lado. Então, os discípulos alegraram-se ao ver o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Jesus disse-lhes novamente: “Que a paz esteja convosco. Assim como o Pai me enviou, eu também vos envio.”

[[v43-20-22]]

^<<v43-20-22,22>>^ Depois de dizer isto, soprou sobre eles e disse-lhes: “Recebam espírito santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se vocês perdoarem os pecados de alguém, eles estão perdoados; se não perdoarem os pecados de alguém, eles não estão perdoados.”

[[v43-20-24]]

^<<v43-20-24,24>>^ Mas Tomé, um dos Doze, que era chamado Gémeo, não estava com eles quando Jesus apareceu.

[[v43-20-25]]

^<<v43-20-25,25>>^ Então, os outros discípulos disseram-lhe: “Nós vimos o Senhor!” Mas ele disse-lhes: “Se eu não vir nas suas mãos a marca dos pregos, não puser o dedo na marca dos pregos e não puser a mão no seu lado, de modo algum acreditarei.”

[[v43-20-26]]

^<<v43-20-26,26>>^ Oito dias depois, os seus discípulos estavam novamente reunidos, e Tomé estava com eles. Embora as portas estivessem trancadas, Jesus apareceu no meio deles e disse: “Que a paz esteja convosco.”

[[v43-20-27]]

^<<v43-20-27,27>>^ Depois, disse a Tomé: “Coloca aqui o teu dedo e vê as minhas mãos; estende a mão e coloca-a no meu lado. Para de duvidar^&#42;1^ e acredita.”

[NOTE]
====
. Lit.: “ser incrédulo”.
====

[[v43-20-28]]

^<<v43-20-28,28>>^ Em resposta Tomé disse-lhe: “Meu Senhor e meu Deus!”

[[v43-20-29]]

^<<v43-20-29,29>>^ Jesus disse-lhe: “Acreditaste porque me viste? Felizes os que não viram, mas mesmo assim acreditam.”

[[v43-20-30]]

^<<v43-20-30,30>>^ Certamente, Jesus realizou muitos outros sinais diante dos discípulos, os quais não estão escritos neste rolo.

[[v43-20-31]]

^<<v43-20-31,31>>^ Mas estes foram escritos para que vocês creiam que Jesus é o Cristo, o Filho de Deus, e para que, por crerem, tenham vida por meio do seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]