include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-10-1]]

^<<v43-10-1,1>>^ “Digo-vos com toda a certeza: Quem não entra no aprisco das ovelhas pela porta, mas sobe por outro lugar, é um ladrão e um saqueador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Mas quem entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ A este o porteiro abre-a, e as ovelhas escutam a sua voz. Ele chama as suas ovelhas por nome e leva-as para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de retirar todas as suas ovelhas, ele vai à frente delas, e elas seguem-no, porque conhecem a sua voz.

[[v43-10-5]]

^<<v43-10-5,5>>^ De modo algum seguirão um estranho, mas fugirão dele, porque não conhecem a voz de estranhos.”

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus fez esta comparação, mas eles não entenderam o que ele lhes disse.

[[v43-10-7]]

^<<v43-10-7,7>>^ Por isso, Jesus disse novamente: “Digo-vos com toda a certeza: Eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos os que vieram em meu lugar são ladrões e saqueadores; mas as ovelhas não os escutaram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta. Quem entrar por mim será salvo, entrará e sairá, e encontrará pastagem.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão só vem para roubar, matar e destruir. Eu vim para que tivessem vida e a tivessem na mais plena medida.

[[v43-10-11]]

^<<v43-10-11,11>>^ Eu sou o bom pastor; o bom pastor dá a sua vida^&#42;1^ pelas ovelhas.

[NOTE]
====
. Ou: “alma”.
====

[[v43-10-12]]

^<<v43-10-12,12>>^ O empregado, que não é pastor e a quem não pertencem as ovelhas, quando vê o lobo chegar, abandona as ovelhas e foge, e o lobo ataca-as e espalha-as;

[[v43-10-13]]

^<<v43-10-13,13>>^ ele foge porque é um empregado e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor. Conheço as minhas ovelhas, e as minhas ovelhas conhecem-me,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece e eu conheço o Pai; e eu dou a minha vida^&#42;1^ pelas ovelhas.

[NOTE]
====
. Ou: “alma”.
====

[[v43-10-16]]

^<<v43-10-16,16>>^ “E tenho outras ovelhas, que não são deste aprisco; a essas também tenho de trazer, e elas escutarão a minha voz e irão tornar-se um só rebanho, com um só pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ É por isso que o Pai me ama, porque entrego a minha vida,^&#42;1^ para a receber de novo.

[NOTE]
====
. Ou: “alma”.
====

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém ma tira de mim, mas eu entrego-a de minha própria iniciativa. Tenho o direito^&#42;1^ de a entregar e tenho o direito^&#42;2^ de a receber outra vez. Recebi este mandamento do meu Pai.”

[NOTE]
====
. Lit.: “autoridade”.
. Lit.: “autoridade”.
====

[[v43-10-19]]

^<<v43-10-19,19>>^ Surgiu novamente uma divisão entre os judeus por causa destas palavras.

[[v43-10-20]]

^<<v43-10-20,20>>^ Muitos deles diziam: “Ele tem um demónio e está louco. Porque é que o escutam?”

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros diziam: “Estas não são declarações de um homem possesso. Será que um demónio pode abrir os olhos aos cegos?”

[[v43-10-22]]

^<<v43-10-22,22>>^ Ocorreu então a Festividade da Dedicação em Jerusalém. Era inverno,

[[v43-10-23]]

^<<v43-10-23,23>>^ e Jesus estava a andar pelo templo, no Pórtico^&#42;1^ de Salomão.

[NOTE]
====
. Ou: “na Colunata”.
====

[[v43-10-24]]

^<<v43-10-24,24>>^ Então, os judeus rodearam-no e disseram-lhe: “Até quando nos deixarás^&#42;1^ na dúvida? Se tu és o Cristo, diz-nos claramente.”

[NOTE]
====
. Ou: “quando deixarás as nossas almas”.
====

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus respondeu-lhes: “Eu disse-vos, e mesmo assim vocês não acreditam. As obras que eu faço em nome do meu Pai dão testemunho de mim.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vocês não acreditam porque não são minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas escutam a minha voz; eu conheço-as, e elas seguem-me.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu dou-lhes vida eterna, e elas jamais serão destruídas, e ninguém as arrancará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ O que o meu Pai me deu é maior do que todas as outras coisas, e ninguém as pode arrancar da mão do Pai.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.”^&#42;1^

[NOTE]
====
. Ou: “estamos em união”.
====

[[v43-10-31]]

^<<v43-10-31,31>>^ Mais uma vez, os judeus apanharam pedras para o apedrejar.

[[v43-10-32]]

^<<v43-10-32,32>>^ Então, Jesus disse-lhes: “Mostrei-vos muitas obras boas da parte do Pai. Por qual dessas obras me vão apedrejar?”

[[v43-10-33]]

^<<v43-10-33,33>>^ Os judeus responderam-lhe: “Nós não te vamos apedrejar por uma boa obra, mas por blasfémia; pois tu, embora sejas um homem, fazes-te um deus.”

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus respondeu-lhes: “Não está escrito na vossa Lei: ‘Eu disse: “Vocês são deuses”’?^&#42;1^

[NOTE]
====
. Ou: “seres divinos”.
====

[[v43-10-35]]

^<<v43-10-35,35>>^ Se ele chamou ‘deuses’ àqueles contra quem se dirigiu a palavra de Deus — e as Escrituras não podem ser anuladas —,

[[v43-10-36]]

^<<v43-10-36,36>>^ vocês dizem-me a mim, a quem o Pai santificou e enviou ao mundo: ‘Tu blasfemas’, porque eu disse: ‘Sou Filho de Deus’?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras do meu Pai, não acreditem em mim.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se eu as faço, mesmo que não acreditem em mim, acreditem nas obras, para que saibam e acreditem que o Pai está em união comigo e eu em união com o Pai.”

[[v43-10-39]]

^<<v43-10-39,39>>^ Então, mais uma vez tentaram prendê-lo, mas ele escapou.

[[v43-10-40]]

^<<v43-10-40,40>>^ E ele retirou-se novamente para o outro lado do Jordão, para o lugar onde João batizava no princípio, e ficou ali.

[[v43-10-41]]

^<<v43-10-41,41>>^ Muitos foram ao encontro dele, e diziam: “João não realizou nenhum sinal, mas todas as coisas que João disse a respeito deste homem eram verdadeiras.”

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali depositaram fé nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]