include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-13-1]]

^<<v43-13-1,1>>^ Antes da Festividade da Páscoa, Jesus sabia que tinha chegado a hora de deixar este mundo e ir para o Pai. Assim, tendo amado os seus que estavam no mundo, amou-os até ao fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Eles estavam a tomar a refeição,^&#42;1^ e o Diabo já tinha posto no coração de Judas Iscariotes, filho de Simão, a ideia de o trair.

[NOTE]
====
. Ou: “ceia”, referindo-se à Páscoa.
====

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus sabia que o Pai tinha entregado todas as coisas nas suas mãos e que tinha vindo de Deus e ia para Deus;

[[v43-13-4]]

^<<v43-13-4,4>>^ assim, ele levantou-se da mesa e tirou a sua capa.^&#42;1^ Pegou então numa toalha e atou-a à cintura.^&#42;2^

[NOTE]
====
. Ou: “as suas roupas exteriores”.
. Ou: “e cingiu-se”.
====

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois, colocou água numa bacia e começou a lavar os pés dos discípulos e a enxugá-los com a toalha que tinha à cintura.^&#42;1^

[NOTE]
====
. Ou: “toalha da qual estava cingido”.
====

[[v43-13-6]]

^<<v43-13-6,6>>^ Então, chegou a Simão Pedro. Este disse-lhe: “Senhor, tu vais lavar-me os pés?”

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus respondeu-lhe: “O que estou a fazer, não o entendes agora, mas entenderás depois destas coisas.”

[[v43-13-8]]

^<<v43-13-8,8>>^ Pedro disse-lhe: “Tu nunca me lavarás os pés.” Jesus respondeu-lhe: “Se eu não te lavar, não tens parte comigo.”

[[v43-13-9]]

^<<v43-13-9,9>>^ Simão Pedro respondeu-lhe: “Senhor, então lava-me não só os pés, mas também as mãos e a cabeça.”

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus disse-lhe: “Quem tomou banho está completamente limpo e não precisa de lavar nada senão os pés. E vocês estão limpos, mas nem todos.”

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem o estava a trair. Foi por isso que disse: “Nem todos vocês estão limpos.”

[[v43-13-12]]

^<<v43-13-12,12>>^ Então, depois de lhes lavar os pés e pôr a sua capa,^&#42;1^ ele recostou-se novamente à mesa e disse-lhes: “Compreendem o que eu vos fiz?

[NOTE]
====
. Ou: “as suas roupas exteriores”.
====

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês chamam-me ‘Instrutor’ e ‘Senhor’, e estão certos, pois eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Portanto, se eu, o Senhor e Instrutor, lavei os vossos pés, vocês também devem^&#42;1^ lavar os pés uns dos outros.

[NOTE]
====
. Ou: “também têm a obrigação de”.
====

[[v43-13-15]]

^<<v43-13-15,15>>^ Pois estabeleci-vos o modelo, a fim de que, assim como eu vos fiz, vocês também o façam.

[[v43-13-16]]

^<<v43-13-16,16>>^ Digo-vos com toda a certeza: O escravo não é maior do que o seu senhor, nem o enviado é maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Se sabem estas coisas, felizes serão se as praticarem.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não me refiro a todos vocês; conheço os que eu escolhi. Mas é para que se cumpra esta passagem das Escrituras: ‘Aquele que comia do meu pão voltou-se contra mim.’^&#42;1^

[NOTE]
====
. Lit.: “levantou o seu calcanhar contra mim”.
====

[[v43-13-19]]

^<<v43-13-19,19>>^ Digo-vos isto agora, antes que ocorra, para que, quando ocorrer, acreditem em quem eu sou.

[[v43-13-20]]

^<<v43-13-20,20>>^ Digo-vos com toda a certeza: Quem recebe a qualquer um que eu envio também me recebe a mim, e quem me recebe, recebe também Aquele que me enviou.”

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer isto, Jesus ficou profundamente angustiado, e declarou:^&#42;1^ “Digo-vos com toda a certeza: Um de vocês vai trair-me.”

[NOTE]
====
. Ou: “e deu testemunho, dizendo”.
====

[[v43-13-22]]

^<<v43-13-22,22>>^ Os discípulos começaram a olhar uns para os outros, sem saber sobre qual deles ele estava a falar.

[[v43-13-23]]

^<<v43-13-23,23>>^ Um dos seus discípulos, aquele a quem Jesus amava, estava recostado perto^&#42;1^ de Jesus.

[NOTE]
====
. Lit.: “ao seio”.
====

[[v43-13-24]]

^<<v43-13-24,24>>^ Portanto, Simão Pedro acenou com a cabeça para esse discípulo e disse-lhe: “Diz-nos a respeito de quem ele está a falar.”

[[v43-13-25]]

^<<v43-13-25,25>>^ Assim, ele encostou-se ao peito de Jesus e perguntou-lhe: “Senhor, quem é?”

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu: “É aquele a quem eu der o pedaço de pão que vou molhar na tigela.” Então, depois de molhar o pão, ele deu-o a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ Depois de Judas ter pegado no pedaço de pão, Satanás entrou nele. Então, Jesus disse-lhe: “O que estás a fazer, fá-lo mais depressa.”

[[v43-13-28]]

^<<v43-13-28,28>>^ Mas nenhum dos que se recostavam à mesa entendeu por que motivo lhe disse isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ De facto, visto que Judas cuidava da caixa do dinheiro, alguns pensavam que Jesus lhe estava a dizer: “Compra o que precisamos para a festividade”, ou que devia dar alguma coisa aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Assim, depois de receber o pedaço de pão, saiu imediatamente. Era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Portanto, depois de ele ter saído, Jesus disse: “Agora o Filho do Homem é glorificado, e Deus é glorificado por meio dele.

[[v43-13-32]]

^<<v43-13-32,32>>^ O próprio Deus o glorificará, e irá glorificá-lo imediatamente.

[[v43-13-33]]

^<<v43-13-33,33>>^ Meus queridos filhos, estou convosco mais um pouco. Vocês vão procurar-me e, assim como disse aos judeus, agora também vos digo: ‘Para onde eu vou, vocês não podem ir.’

[[v43-13-34]]

^<<v43-13-34,34>>^ Dou-vos um novo mandamento: Que se amem uns aos outros; assim como eu vos amei, amem-se também uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Por meio disto todos saberão que são meus discípulos: se tiverem amor entre vocês.”

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro disse-lhe: “Senhor, para onde vais?” Jesus respondeu: “Para onde eu vou, tu não me podes seguir agora, mas vais seguir-me depois.”

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro disse-lhe: “Senhor, porque é que não te posso seguir agora? Por ti darei a minha vida.”^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus respondeu: “Darás a tua vida^&#42;1^ por mim? Digo-te com toda a certeza: O galo de modo algum cantará até que tu me tenhas negado três vezes.”

[NOTE]
====
. Ou: “alma”.
====

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]