include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-1-1]]

^<<v43-1-1,1>>^ No princípio era a Palavra, e a Palavra estava com Deus, e a Palavra era um deus.^&#42;1^

[NOTE]
====
. Ou: “era divina”.
====

[[v43-1-2]]

^<<v43-1-2,2>>^ Ele estava no princípio com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Todas as coisas vieram a existir por meio dele, e sem ele nem mesmo uma só coisa veio a existir.
O que veio a existir

[[v43-1-4]]

^<<v43-1-4,4>>^ por meio dele foi a vida, e a vida era a luz dos homens.

[[v43-1-5]]

^<<v43-1-5,5>>^ A luz está a brilhar na escuridão, mas a escuridão não a venceu.

[[v43-1-6]]

^<<v43-1-6,6>>^ Surgiu um homem enviado como representante de Deus; o seu nome era João.

[[v43-1-7]]

^<<v43-1-7,7>>^ Este homem veio como testemunha, a fim de dar testemunho da luz, para que todo o tipo de pessoas cresse por meio dele.

[[v43-1-8]]

^<<v43-1-8,8>>^ Ele não era essa luz, mas veio para dar testemunho dessa luz.

[[v43-1-9]]

^<<v43-1-9,9>>^ Estava para vir ao mundo a verdadeira luz, que ilumina^&#42;1^ todo o tipo de pessoas.

[NOTE]
====
. Ou: “que dá luz a”.
====

[[v43-1-10]]

^<<v43-1-10,10>>^ Ele estava no mundo, e o mundo veio a existir por meio dele, mas o mundo não o conheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Ele veio para o seu próprio povo, mas eles não o aceitaram.

[[v43-1-12]]

^<<v43-1-12,12>>^ No entanto, a todos os que o receberam, ele deu autoridade para se tornarem filhos de Deus, porque exerciam fé no seu nome.

[[v43-1-13]]

^<<v43-1-13,13>>^ E eles nasceram, não do sangue, nem da vontade carnal, nem da vontade do homem, mas de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ Portanto, a Palavra tornou-se carne e residiu entre nós, e nós vimos a sua glória, uma glória como a de um filho unigénito de um pai; ele estava cheio de favor divino^&#42;1^ e de verdade.

[NOTE]
====
. Ou: “de bondade imerecida”.
====

[[v43-1-15]]

^<<v43-1-15,15>>^ (João deu testemunho dele, sim, ele clamou: “Este é aquele de quem eu disse: ‘Aquele que vem atrás de mim avançou à minha frente, pois existia antes de mim.’”)

[[v43-1-16]]

^<<v43-1-16,16>>^ Pois todos nós recebemos da sua plenitude, até mesmo bondade imerecida sobre bondade imerecida.

[[v43-1-17]]

^<<v43-1-17,17>>^ Porque a Lei foi dada por meio de Moisés; a bondade imerecida e a verdade vieram a existir por meio de Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Nunca nenhum homem viu a Deus; o deus unigénito, que está ao lado do Pai,^&#42;1^ é quem O revelou.

[NOTE]
====
. Ou: “na posição junto ao seio do Pai”. Isto refere-se a uma posição de favor especial.
====

[[v43-1-19]]

^<<v43-1-19,19>>^ Este é o testemunho que João deu quando os judeus enviaram sacerdotes e levitas de Jerusalém para lhe perguntar: “Quem és tu?”

[[v43-1-20]]

^<<v43-1-20,20>>^ Ele não se recusou a responder; de facto, ele admitiu: “Eu não sou o Cristo.”

[[v43-1-21]]

^<<v43-1-21,21>>^ Eles perguntaram-lhe: “Então, quem és tu? És Elias?” Ele respondeu: “Não sou.” “És o Profeta?” Ele respondeu: “Não!”

[[v43-1-22]]

^<<v43-1-22,22>>^ Portanto, disseram-lhe: “Quem és tu? Diz-nos, para podermos dar uma resposta aos que nos enviaram. O que é que dizes a respeito de ti mesmo?”

[[v43-1-23]]

^<<v43-1-23,23>>^ Ele disse: “Eu sou a voz de alguém que clama no deserto:^&#42;1^ ‘Endireitem o caminho para Jeová’,^&#42;2^ conforme disse Isaías, o profeta.”

[NOTE]
====
. Veja o Glossário.
. Veja o Ap. A5.
====

[[v43-1-24]]

^<<v43-1-24,24>>^ Os que tinham sido enviados eram dos fariseus.

[[v43-1-25]]

^<<v43-1-25,25>>^ Perguntaram-lhe ainda: “Então, porque é que batizas, se não és o Cristo, nem Elias, nem o Profeta?”

[[v43-1-26]]

^<<v43-1-26,26>>^ João respondeu-lhes: “Eu batizo em água. Entre vocês, há alguém que não conhecem,

[[v43-1-27]]

^<<v43-1-27,27>>^ aquele que vem atrás de mim, e eu não sou digno de desatar o cordão das suas sandálias.”

[[v43-1-28]]

^<<v43-1-28,28>>^ Estas coisas ocorreram em Betânia, do outro lado do Jordão, onde João estava a batizar.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte, ele viu que Jesus vinha ao seu encontro e disse: “Vejam o Cordeiro de Deus, que tira o pecado do mundo!

[[v43-1-30]]

^<<v43-1-30,30>>^ Este é aquele a respeito de quem eu disse: ‘Atrás de mim vem um homem que avançou à minha frente, pois existia antes de mim.’

[[v43-1-31]]

^<<v43-1-31,31>>^ Nem eu próprio o conhecia, mas foi por esta razão que eu vim batizar em água: para que ele se tornasse conhecido em Israel.”

[[v43-1-32]]

^<<v43-1-32,32>>^ João também deu o seguinte testemunho: “Observei o espírito descer do céu como uma pomba e permanecer sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Nem eu próprio o conhecia, mas Aquele que me enviou para batizar em água disse-me: ‘Aquele sobre quem vires o espírito descer e permanecer, esse é quem batiza em espírito santo.’

[[v43-1-34]]

^<<v43-1-34,34>>^ E eu vi isso e dei testemunho de que este é o Filho de Deus.”

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte, João estava lá outra vez, com dois dos seus discípulos,

[[v43-1-36]]

^<<v43-1-36,36>>^ e, ao ver Jesus a caminhar, disse: “Vejam o Cordeiro de Deus!”

[[v43-1-37]]

^<<v43-1-37,37>>^ Quando os dois discípulos o ouviram dizer isso, seguiram Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Jesus virou-se então e, vendo que eles o seguiam, disse-lhes: “O que é que procuram?” Eles disseram-lhe: “Rabi (que traduzido quer dizer “instrutor”), onde é que estás hospedado?”

[[v43-1-39]]

^<<v43-1-39,39>>^ Ele disse-lhes: “Venham, e verão.” Então, eles foram e viram onde estava hospedado, e ficaram com ele naquele dia. Era por volta da décima hora.^&#42;1^

[NOTE]
====
. Isto é, por volta das 4 h da tarde.
====

[[v43-1-40]]

^<<v43-1-40,40>>^ André, irmão de Simão Pedro, foi um dos dois que ouviram as palavras de João e seguiram Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ Ele encontrou primeiro o seu irmão, Simão, e disse-lhe: “Encontrámos o Messias” (que traduzido quer dizer Cristo),

[[v43-1-42]]

^<<v43-1-42,42>>^ e então levou-o a Jesus. Quando Jesus olhou para ele, disse: “Tu és Simão, filho de João. Serás chamado Cefas” (que traduzido é Pedro).

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte, Jesus quis partir para a Galileia. Então, ele encontrou Filipe e disse-lhe: “Sê meu seguidor.”

[[v43-1-44]]

^<<v43-1-44,44>>^ Filipe era de Betsaida, a cidade de André e de Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe encontrou Natanael e disse-lhe: “Encontrámos aquele sobre quem Moisés escreveu na Lei, e sobre quem os Profetas também escreveram: Jesus, filho de José, de Nazaré.”

[[v43-1-46]]

^<<v43-1-46,46>>^ Porém, Natanael disse-lhe: “Será que pode sair alguma coisa boa de Nazaré?” Filipe respondeu: “Vem e vê.”

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus viu Natanael aproximar-se e disse a respeito dele: “Aí vem um verdadeiro israelita, em quem não há falsidade.”

[[v43-1-48]]

^<<v43-1-48,48>>^ Natanael perguntou-lhe: “Como é que me conhece?” Jesus respondeu-lhe: “Antes de Filipe te chamar, enquanto estavas debaixo da figueira, eu vi-te.”

[[v43-1-49]]

^<<v43-1-49,49>>^ Natanael disse-lhe: “Rabi, o senhor é o Filho de Deus, é o Rei de Israel.”

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus respondeu-lhe: “É por eu te ter dito que te vi debaixo da figueira que tu acreditas? Verás coisas maiores do que estas.”

[[v43-1-51]]

^<<v43-1-51,51>>^ Então, ele disse-lhe: “Digo-vos com toda a certeza:^&#42;1^ Vocês verão o céu aberto e os anjos de Deus a subir e a descer para o Filho do Homem.”

[NOTE]
====
. Ou: “em toda a verdade”. Lit.: “Amém, amém”.
====

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]