include::./index.adoc[]

[[v43-16-0]]
=== João, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-16-1]]

^<<v43-16-1,1>>^ “Disse-vos estas coisas para que não tropecem.

[[v43-16-2]]

^<<v43-16-2,2>>^ Os homens irão expulsar-vos da sinagoga. De facto, vem a hora em que quem vos matar pensará que está a prestar um serviço sagrado a Deus.

[[v43-16-3]]

^<<v43-16-3,3>>^ Mas farão estas coisas porque não conhecem nem o Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Contudo, disse-vos estas coisas para que, quando chegar a hora de acontecerem, se lembrem de que vos falei delas.
“Não vos disse estas coisas no princípio porque estava convosco.

[[v43-16-5]]

^<<v43-16-5,5>>^ Mas agora vou para Aquele que me enviou; mesmo assim, nenhum de vocês me pergunta: ‘Para onde vais?’

[[v43-16-6]]

^<<v43-16-6,6>>^ Pelo contrário, o vosso coração está cheio de tristeza porque eu vos disse estas coisas.

[[v43-16-7]]

^<<v43-16-7,7>>^ Contudo, digo-vos a verdade: É em vosso benefício que me vou embora. Pois, se eu não me for embora, o ajudador não virá ter convosco; mas, se eu for, eu vo-lo enviarei.

[[v43-16-8]]

^<<v43-16-8,8>>^ E, quando ele vier, dará ao mundo provas convincentes do pecado, da justiça e do julgamento:

[[v43-16-9]]

^<<v43-16-9,9>>^ primeiro, do pecado, porque eles não exercem fé em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ depois, da justiça, porque vou para o Pai e vocês não me verão mais;

[[v43-16-11]]

^<<v43-16-11,11>>^ então, do julgamento, porque o governante deste mundo foi julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ “Ainda tenho muitas coisas para vos dizer, mas agora não são capazes de as suportar.

[[v43-16-13]]

^<<v43-16-13,13>>^ No entanto, quando ele^&#42;1^ vier, o espírito da verdade, ele irá guiar-vos a toda a verdade, pois não falará da sua própria iniciativa, mas falará o que ouvir e irá declarar-vos as coisas que virão.

[NOTE]
====
. “Ele”, tanto no v. 13 como no v. 14, refere-se ao “ajudador” mencionado no v. 7. Jesus usou “o ajudador” (que é do género masculino em grego) como personificação do espírito santo, uma força impessoal, que é do género neutro em grego.
====

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele irá glorificar-me, porque receberá do que é meu e vo-lo declarará.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo o que o Pai tem é meu. É por isso que eu disse que ele receberá do que é meu e vo-lo declarará.

[[v43-16-16]]

^<<v43-16-16,16>>^ Em breve deixarão de me ver; e também em breve me verão.”

[[v43-16-17]]

^<<v43-16-17,17>>^ Em vista disso, alguns dos seus discípulos disseram uns aos outros: “O que é que ele quer dizer com: ‘Em breve deixarão de me ver; e também em breve me verão’ e ‘porque vou para o Pai’?”

[[v43-16-18]]

^<<v43-16-18,18>>^ Eles diziam: “O que é que ele quer dizer com: ‘Em breve’? Não sabemos do que é que ele está a falar.”

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus sabia que eles lhe queriam fazer perguntas, de modo que lhes disse: “Estão a perguntar isso uns aos outros porque vos disse: ‘Em breve deixarão de me ver; e também em breve me verão’?

[[v43-16-20]]

^<<v43-16-20,20>>^ Digo-vos com toda a certeza: Vocês irão chorar e lamentar-se, mas o mundo irá alegrar-se; vocês irão ficar tristes, mas a vossa tristeza irá transformar-se em alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ Quando uma mulher está a dar à luz, ela sofre porque chegou a sua hora; mas, quando o bebé nasce, ela já não se lembra da aflição, por causa da alegria de um ser humano ter vindo ao mundo.

[[v43-16-22]]

^<<v43-16-22,22>>^ Da mesma maneira, agora vocês estão tristes; mas eu voltarei a ver-vos, e o vosso coração irá alegrar-se, e ninguém vos tirará a vossa alegria.

[[v43-16-23]]

^<<v43-16-23,23>>^ Nesse dia, vocês não me farão absolutamente nenhuma pergunta. Digo-vos com toda a certeza: Se pedirem ao Pai qualquer coisa em meu nome, ele vo-la dará.

[[v43-16-24]]

^<<v43-16-24,24>>^ Até agora vocês não pediram nem uma única coisa em meu nome. Peçam e receberão, para que a vossa alegria seja completa.

[[v43-16-25]]

^<<v43-16-25,25>>^ “Disse-vos estas coisas usando comparações. Vem a hora em que já não vos falarei por meio de comparações, mas irei falar-vos claramente a respeito do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Nesse dia pedirão ao Pai em meu nome. Não quero dizer com isto que pedirei por vocês.

[[v43-16-27]]

^<<v43-16-27,27>>^ Pois o próprio Pai ama-vos,^&#42;1^ porque vocês me amam e acreditam que eu vim como representante de Deus.

[NOTE]
====
. Ou: “tem afeição por vocês”.
====

[[v43-16-28]]

^<<v43-16-28,28>>^ Vim como representante do Pai e entrei no mundo. Agora, deixo o mundo e vou para o Pai.”

[[v43-16-29]]

^<<v43-16-29,29>>^ Os seus discípulos disseram: “Agora, sim, estás a falar claramente e não por meio de comparações.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora sabemos que sabes todas as coisas e não precisas de que te façam perguntas. Por isso acreditamos que vieste de Deus.”

[[v43-16-31]]

^<<v43-16-31,31>>^ Jesus respondeu-lhes: “Agora acreditam?

[[v43-16-32]]

^<<v43-16-32,32>>^ Escutem: Vem a hora — realmente já veio — em que vocês serão espalhados, cada um para a sua própria casa, e irão deixar-me sozinho. Mas eu não estou sozinho, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Disse-vos estas coisas para que, por meio de mim, tenham paz. No mundo terão tribulação, mas coragem! Eu venci o mundo.”

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]