include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v36-1-1]]

^<<v36-1-1,1>>^ Esta é a palavra de Jeová que Sofonias,^&#42;1^ filho de Cusi, filho de Gedalias, filho de Amarias, filho de Ezequias, recebeu nos dias de Josias, filho de Amom e rei de Judá:

[NOTE]
====
. Que significa “Jeová escondeu (entesourou)”.
====

[[v36-1-2]]

^<<v36-1-2,2>>^ “Destruirei completamente tudo o que há na face da terra”, diz Jeová.

[[v36-1-3]]

^<<v36-1-3,3>>^ “Destruirei o homem e o animal.
Destruirei as aves do céu e os peixes do mar,
E as pedras de tropeço^&#42;1^ juntamente com os maus;
E eliminarei os homens da face da terra”, diz Jeová.

[NOTE]
====
. Aparentemente, refere-se a atividades ou objetos relacionados com idolatria.
====

[[v36-1-4]]

^<<v36-1-4,4>>^ “Vou estender a mão contra Judá
E contra todos os habitantes de Jerusalém,
E vou eliminar deste lugar tudo o que restar^&#42;1^ de Baal,
O nome dos sacerdotes de deuses estrangeiros juntamente com os sacerdotes,

[NOTE]
====
. Ou: “todos os vestígios”.
====

[[v36-1-5]]

^<<v36-1-5,5>>^ Os que se curvam nos terraços diante do exército dos céus,
Os que se curvam e juram lealdade a Jeová
Ao mesmo tempo que juram lealdade a Malcã,

[[v36-1-6]]

^<<v36-1-6,6>>^ E os que deixam de seguir a Jeová,
Que não procuram a Jeová nem o consultam.”

[[v36-1-7]]

^<<v36-1-7,7>>^ Fiquem em silêncio diante do Soberano Senhor Jeová, pois o dia de Jeová está próximo.
Jeová preparou um sacrifício; ele santificou os seus convidados.

[[v36-1-8]]

^<<v36-1-8,8>>^ “No dia do sacrifício de Jeová, ajustarei contas com os príncipes,
Com os filhos do rei e com todos os que usam roupas estrangeiras.

[[v36-1-9]]

^<<v36-1-9,9>>^ Nesse dia, ajustarei contas com todos os que sobem ao estrado,^&#42;1^
Os que enchem a casa do seu senhor com violência e engano.

[NOTE]
====
. Ou: “ao pódio; à soleira”. Possivelmente, refere-se à plataforma onde ficava o trono do rei.
====

[[v36-1-10]]

^<<v36-1-10,10>>^ Nesse dia”, diz Jeová,
“Haverá um clamor vindo do Portão do Peixe,
Um lamento vindo da Cidade Nova,^&#42;1^
E um grande estrondo vindo dos montes.

[NOTE]
====
. Ou: “do segundo bairro”.
====

[[v36-1-11]]

^<<v36-1-11,11>>^ Lamentem, habitantes de Mactés,^&#42;1^
Pois todos os comerciantes^&#42;2^ foram eliminados;^&#42;3^
Todos os que pesavam a prata foram destruídos.

[NOTE]
====
. Aparentemente, trata-se de um setor de Jerusalém perto do Portão do Peixe.
. Ou: “mercadores”.
. Lit.: “silenciados”.
====

[[v36-1-12]]

^<<v36-1-12,12>>^ Nesse tempo, vasculharei Jerusalém com lâmpadas
E ajustarei contas com os acomodados,^&#42;1^ que dizem no coração:
‘Jeová não fará nem o bem nem o mal.’

[NOTE]
====
. Lit.: “os que se engrossam sobre as suas borras”, como num barril de vinho.
====

[[v36-1-13]]

^<<v36-1-13,13>>^ A sua riqueza será saqueada, e as suas casas serão devastadas.
Construirão casas, mas não as ocuparão;
Plantarão vinhas, mas não beberão o vinho.

[[v36-1-14]]

^<<v36-1-14,14>>^ O grande dia de Jeová está próximo!
Está próximo e aproxima-se com grande rapidez!^&#42;1^
O ruído do dia de Jeová é amargo.
Nesse dia, até o guerreiro dá um grito.

[NOTE]
====
. Ou: “apressa-se rapidamente”.
====

[[v36-1-15]]

^<<v36-1-15,15>>^ Esse dia é um dia de fúria,
Um dia de aflição e de angústia,
Um dia de tempestade e de desolação,
Um dia de escuridão e de trevas,
Um dia de nuvens e de densas trevas,

[[v36-1-16]]

^<<v36-1-16,16>>^ Um dia de toque de buzina e de grito de guerra,
Contra as cidades fortificadas e contra as altas torres angulares.

[[v36-1-17]]

^<<v36-1-17,17>>^ Vou causar aflição aos homens,
E eles andarão como cegos,
Porque foi contra Jeová que pecaram.
O seu sangue será derramado como pó,
E os seus intestinos^&#42;1^ como fezes.

[NOTE]
====
. Ou: “a sua carne”.
====

[[v36-1-18]]

^<<v36-1-18,18>>^ Nem a sua prata nem o seu ouro poderão salvá-los no dia da fúria de Jeová.
Toda a terra será consumida pelo fogo do seu zelo,
Porque ele fará uma exterminação, sim, uma exterminação terrível, de todos os habitantes da terra.”

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]