include::./index.adoc[]

[[v36-3-0]]
=== Sofonias, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v36-3-1]]

^<<v36-3-1,1>>^ Ai da cidade rebelde, impura, opressiva!

[[v36-3-2]]

^<<v36-3-2,2>>^ Ela não obedece a nenhuma voz, nem aceita nenhuma disciplina.
Não confia em Jeová, nem se achega ao seu Deus.

[[v36-3-3]]

^<<v36-3-3,3>>^ No meio dela, os seus príncipes são leões que rugem.
Os seus juízes são lobos da noite;
Não deixam um único osso para roer no dia seguinte.

[[v36-3-4]]

^<<v36-3-4,4>>^ Os seus profetas são insolentes, traidores.
Os seus sacerdotes profanam o que é santo;
Eles são violentos para com a lei.

[[v36-3-5]]

^<<v36-3-5,5>>^ Jeová é justo e está no meio dela; ele não faz o que é errado.
Manhã após manhã, ele torna conhecidas as suas decisões judiciais,
Sem falhar, como a luz do dia.
Mas o injusto não se envergonha.

[[v36-3-6]]

^<<v36-3-6,6>>^ “Eu destruí nações; as suas torres angulares ficaram desoladas.
Devastei as suas ruas, e já ninguém passa por elas.
As suas cidades ficaram em ruínas, sem ninguém, sem habitantes.

[[v36-3-7]]

^<<v36-3-7,7>>^ Eu disse-lhe: ‘Certamente, irás temer-me e aceitar a disciplina’,^&#42;1^
Para que a sua morada não seja destruída,
Pois, por todas estas coisas, ajustarei contas com ela.^&#42;2^
Contudo, eles estavam ainda mais ansiosos para agir de modo corrupto.

[NOTE]
====
. Ou: “correção”.
. Ou: “irei puni-la”.
====

[[v36-3-8]]

^<<v36-3-8,8>>^ ‘Portanto, fiquem à minha espera’,^&#42;1^ diz Jeová,
‘Até ao dia em que eu me levantar para levar despojo,^&#42;2^
Pois a minha decisão judicial é ajuntar nações e reunir reinos,
Para derramar sobre eles a minha indignação, toda a minha ira ardente;
Pois toda a terra será consumida pelo fogo do meu zelo.

[NOTE]
====
. Ou: “esperem pacientemente por mim”.
. Ou, possivelmente: “me levantar como testemunha”.
====

[[v36-3-9]]

^<<v36-3-9,9>>^ Nesse tempo, mudarei a língua dos povos para uma língua pura,
Para que todos eles possam invocar o nome de Jeová,
A fim de servi-lo ombro a ombro.’^&#42;1^

[NOTE]
====
. Ou: “adorá-lo em união”.
====

[[v36-3-10]]

^<<v36-3-10,10>>^ Os que me suplicam, a filha do meu povo espalhado,
Vão trazer-me uma dádiva desde a região dos rios da Etiópia.

[[v36-3-11]]

^<<v36-3-11,11>>^ Nesse dia, não serás envergonhada
Por causa de todos os teus atos de rebeldia contra mim,
Porque removerei do teu meio os orgulhosos arrogantes,
E nunca mais serás arrogante no meu santo monte.

[[v36-3-12]]

^<<v36-3-12,12>>^ Deixarei restar um povo humilde e modesto no teu meio,
E eles irão refugiar-se no nome de Jeová.

[[v36-3-13]]

^<<v36-3-13,13>>^ Os que restarem de Israel não farão o que é mau;
Não dirão mentiras, nem terão na boca uma língua falsa;
Eles irão alimentar-se^&#42;1^ e deitar-se, sem que ninguém os faça ter medo.”

[NOTE]
====
. Ou: “pastar”.
====

[[v36-3-14]]

^<<v36-3-14,14>>^ Grita de júbilo, ó filha de Sião!
Grita triunfantemente, ó Israel!
Alegra-te e exulta de todo o coração, ó filha de Jerusalém!

[[v36-3-15]]

^<<v36-3-15,15>>^ Jeová removeu os julgamentos contra ti.
Fez o teu inimigo recuar.
O Rei de Israel, Jeová, está no teu meio.
Não voltarás a temer nenhuma calamidade.

[[v36-3-16]]

^<<v36-3-16,16>>^ Nesse dia, será dito a Jerusalém:
“Não tenhas medo, ó Sião.
Não deixes que as tuas mãos se abaixem.

[[v36-3-17]]

^<<v36-3-17,17>>^ Jeová, teu Deus, está no teu meio.
Como um valente guerreiro, ele salvará.
Por tua causa, ele exultará com grande alegria.
Ele ficará em silêncio^&#42;1^ no seu próprio amor.
Jubilará por tua causa com gritos de alegria.

[NOTE]
====
. Ou: “tranquilo; sossegado; satisfeito”.
====

[[v36-3-18]]

^<<v36-3-18,18>>^ Reunirei os que estão tristes por estarem ausentes das tuas festividades;
Eles ficaram longe de ti enquanto suportavam desonra por causa dela.

[[v36-3-19]]

^<<v36-3-19,19>>^ Nesse tempo, agirei contra todos os que te oprimem;
Salvarei os que coxeiam
E reunirei os que estão espalhados.
Farei deles um motivo de louvor e fama^&#42;1^
Em toda a terra, onde foram envergonhados.

[NOTE]
====
. Lit.: “um nome”.
====

[[v36-3-20]]

^<<v36-3-20,20>>^ Nesse tempo, vou trazer-vos de volta,
No tempo em que eu vos reunir.
Pois farei de vocês um motivo de fama^&#42;1^ e louvor entre todos os povos da terra,
Quando eu trouxer de volta os vossos cativos perante os vossos olhos”, diz Jeová.

[NOTE]
====
. Lit.: “um nome”.
====

'''

xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-ageu/037-ageu-001.adoc#v37-1-0[Próximo Capítulo &#62;]