include::./index.adoc[]

[[v32-2-0]]
=== Jonas, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v32-2-1]]

^<<v32-2-1,1>>^ Então, Jonas orou a Jeová, seu Deus, do ventre do peixe,

[[v32-2-2]]

^<<v32-2-2,2>>^ dizendo:
“Na minha aflição, clamei a Jeová e ele respondeu-me.
Das profundezas^&#42;1^ da Sepultura,^&#42;2^ clamei por ajuda.
Ouviste a minha voz.

[NOTE]
====
. Lit.: “Do ventre”.
. Ou: “do Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v32-2-3]]

^<<v32-2-3,3>>^ Quando me lançaste nas profundezas, no coração do alto-mar,
As correntezas engoliram-me.
Todas as tuas ondas poderosas passaram sobre mim.

[[v32-2-4]]

^<<v32-2-4,4>>^ E eu disse: ‘Fui expulso de diante dos teus olhos!
Como é que olharei novamente para o teu santo templo?’

[[v32-2-5]]

^<<v32-2-5,5>>^ As águas engoliram-me e ameaçaram a minha vida;^&#42;1^
As águas profundas cercaram-me.
As algas enrolaram-se na minha cabeça.

[NOTE]
====
. Ou: “As águas cercaram-me até à alma”.
====

[[v32-2-6]]

^<<v32-2-6,6>>^ Afundei-me até à base dos montes.
As trancas da terra estavam a fechar-se sobre mim para sempre.
Porém, fizeste com que a minha vida subisse da cova, ó Jeová, meu Deus.

[[v32-2-7]]

^<<v32-2-7,7>>^ Quando a minha vida^&#42;1^ se desvanecia, foi de Jeová que me lembrei.
Então, a minha oração chegou até ti, dentro do teu santo templo.

[NOTE]
====
. Ou: “alma”.
====

[[v32-2-8]]

^<<v32-2-8,8>>^ Os que dão devoção a ídolos que nada valem abandonam a Fonte do amor leal.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “a sua lealdade”.
====

[[v32-2-9]]

^<<v32-2-9,9>>^ Mas, quanto a mim, vou oferecer-te sacrifícios com expressões de agradecimento.
O que votei, vou cumprir.
A salvação vem de Jeová.”

[[v32-2-10]]

^<<v32-2-10,10>>^ Então, Jeová deu a ordem ao peixe, e ele vomitou Jonas em terra seca.

'''

xref:032-jonas/032-jonas-001.adoc#v32-1-0[&#60; Capítulo Anterior] | <<v32-2-0,Topo>> | xref:032-jonas/032-jonas-003.adoc#v32-3-0[Próximo Capítulo &#62;]