include::./index.adoc[]

[[v32-4-0]]
=== Jonas, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v32-4-1]]

^<<v32-4-1,1>>^ No entanto, isto desagradou muito a Jonas e deixou-o muito zangado.

[[v32-4-2]]

^<<v32-4-2,2>>^ Por isso, ele orou a Jeová: “Ó Jeová, não era esta a minha preocupação quando eu estava na minha terra? Foi por isso que tentei fugir para Társis na primeira vez, pois sabia que és um Deus compassivo^&#42;1^ e misericordioso, paciente^&#42;2^ e cheio de amor leal, e que fica muito triste com a calamidade.

[NOTE]
====
. Ou: “benevolente”.
. Ou: “vagaroso em irar-se”.
====

[[v32-4-3]]

^<<v32-4-3,3>>^ Agora, ó Jeová, por favor, tira-me a vida,^&#42;1^ pois, para mim, é melhor morrer do que viver.”

[NOTE]
====
. Ou: “alma”.
====

[[v32-4-4]]

^<<v32-4-4,4>>^ Jeová perguntou: “Achas bem ficares tão zangado?”

[[v32-4-5]]

^<<v32-4-5,5>>^ Jonas saiu então da cidade e sentou-se a leste da cidade. De seguida, fez para si um abrigo e sentou-se à sua sombra para ver o que aconteceria à cidade.

[[v32-4-6]]

^<<v32-4-6,6>>^ Então, Jeová Deus fez com que um cabaceiro^&#42;1^ crescesse sobre Jonas para lhe fazer sombra sobre a cabeça e para o aliviar da sua aflição. E Jonas ficou muito contente com o cabaceiro.

[NOTE]
====
. Ou, possivelmente: “uma planta de rícino”.
====

[[v32-4-7]]

^<<v32-4-7,7>>^ Contudo, ao raiar o dia seguinte, o verdadeiro Deus fez com que um verme atacasse o cabaceiro, e este secou-se.

[[v32-4-8]]

^<<v32-4-8,8>>^ Quando o sol começou a brilhar, Deus também fez soprar um vento leste abrasador, e o sol castigava a cabeça de Jonas, e ele estava quase a desmaiar. Ele pedia para morrer^&#42;1^ e dizia: “Para mim, é melhor morrer do que viver.”

[NOTE]
====
. Ou: “que a sua alma morresse”.
====

[[v32-4-9]]

^<<v32-4-9,9>>^ Deus perguntou a Jonas: “Achas bem ficares tão zangado por causa do cabaceiro?”
E ele respondeu: “Eu tenho motivos para ficar zangado, tão zangado que quero morrer.”

[[v32-4-10]]

^<<v32-4-10,10>>^ No entanto, Jeová disse: “Tiveste pena do cabaceiro, que não cultivaste nem fizeste crescer; ele cresceu numa noite e morreu numa noite.

[[v32-4-11]]

^<<v32-4-11,11>>^ Será que eu também não deveria ter pena de Nínive, a grande cidade, em que há mais de 120 000 homens que nem sequer sabem a diferença entre o certo e o errado,^&#42;1^ além dos seus muitos animais?”

[NOTE]
====
. Ou: “não sabem a diferença entre a sua direita e a sua esquerda”.
====

'''

xref:032-jonas/032-jonas-003.adoc#v32-3-0[&#60; Capítulo Anterior] | <<v32-4-0,Topo>> | xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[Próximo Capítulo &#62;]