include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v32-1-1]]

^<<v32-1-1,1>>^ Jonas,^&#42;1^ filho de Amitai, recebeu a seguinte palavra de Jeová:

[NOTE]
====
. Que significa “pomba”.
====

[[v32-1-2]]

^<<v32-1-2,2>>^ “Levanta-te e vai a Nínive, a grande cidade, e profere uma sentença contra ela, pois tomei conhecimento da sua maldade.”

[[v32-1-3]]

^<<v32-1-3,3>>^ No entanto, Jonas resolveu fugir de Jeová e ir para Társis; ele desceu a Jope e encontrou um navio que ia para Társis. Pagou então a passagem e embarcou, a fim de ir com os que estavam no navio para Társis, para longe de Jeová.

[[v32-1-4]]

^<<v32-1-4,4>>^ Então, Jeová lançou um forte vento sobre o mar, e houve uma tempestade tão violenta no mar que o navio estava prestes a naufragar.

[[v32-1-5]]

^<<v32-1-5,5>>^ Os marinheiros ficaram com tanto medo que cada um começou a clamar ao seu deus por socorro. E começaram a atirar ao mar os objetos que havia no navio, para deixá-lo mais leve. Contudo, Jonas tinha descido ao porão do navio,^&#42;1^ onde se deitou, e dormia profundamente.

[NOTE]
====
. Ou: “navio com convés”.
====

[[v32-1-6]]

^<<v32-1-6,6>>^ O capitão do navio aproximou-se dele e disse: “Porque é que estás a dormir? Levanta-te, clama ao teu deus! Talvez o verdadeiro Deus mostre que se importa connosco. Nesse caso, não morreremos.”

[[v32-1-7]]

^<<v32-1-7,7>>^ De seguida, disseram uns aos outros: “Venham, vamos lançar sortes para descobrir quem é o culpado por esta calamidade.” Assim, lançaram sortes, e a sorte caiu em Jonas.

[[v32-1-8]]

^<<v32-1-8,8>>^ Eles disseram-lhe: “Diz-nos, por favor: de quem é a culpa por esta calamidade que nos aconteceu? Qual é o teu trabalho, e de onde vens? Qual é o teu país, e a que povo pertences?”

[[v32-1-9]]

^<<v32-1-9,9>>^ Ele respondeu: “Sou hebreu e temo^&#42;1^ a Jeová, o Deus dos céus, aquele que fez o mar e a terra seca.”

[NOTE]
====
. Ou: “adoro”.
====

[[v32-1-10]]

^<<v32-1-10,10>>^ Então, os homens ficaram ainda com mais medo e perguntaram-lhe: “O que é que fizeste?” (Os homens sabiam que ele ia a fugir de Jeová, porque ele já lhes tinha contado isso.)

[[v32-1-11]]

^<<v32-1-11,11>>^ E perguntaram-lhe: “O que é que devemos fazer contigo para que o mar se acalme?” Pois o mar estava a ficar cada vez mais agitado.

[[v32-1-12]]

^<<v32-1-12,12>>^ Ele respondeu: “Peguem em mim e atirem-me ao mar, e o mar ficará calmo; porque sei que é por minha causa que esta violenta tempestade vos sobreveio.”

[[v32-1-13]]

^<<v32-1-13,13>>^ Contudo, os homens remaram com força^&#42;1^ para levar o navio de volta a terra seca, mas não conseguiram, porque o mar estava cada vez mais agitado à sua volta.

[NOTE]
====
. Ou: “tentaram atravessar a tempestade”.
====

[[v32-1-14]]

^<<v32-1-14,14>>^ Por conseguinte, eles clamaram a Jeová: “Ó Jeová, por favor, não nos deixes morrer por causa deste homem!^&#42;1^ Não nos consideres responsáveis por derramar sangue inocente, visto que agiste conforme a tua vontade, ó Jeová!”

[NOTE]
====
. Ou: “por causa da alma deste homem”.
====

[[v32-1-15]]

^<<v32-1-15,15>>^ Então, pegaram em Jonas e atiraram-no ao mar, e o mar acalmou-se.

[[v32-1-16]]

^<<v32-1-16,16>>^ Em vista disso, os homens ficaram cheios de temor de Jeová, e ofereceram um sacrifício a Jeová e fizeram votos.

[[v32-1-17]]

^<<v32-1-17,17>>^ E Jeová enviou um grande peixe para engolir Jonas, de modo que Jonas ficou três dias e três noites no ventre do peixe.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]