include::./index.adoc[]

[[v47-5-0]]
=== 2 Coríntios, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-5-1]]

^<<v47-5-1,1>>^ Pois sabemos que, se a nossa casa terrena, esta tenda, for destruída,^&#42;1^ teremos um edifício da parte de Deus, uma casa eterna nos céus, que não foi feita por mãos humanas.

[NOTE]
====
. Ou: “dissolvida”.
====

[[v47-5-2]]

^<<v47-5-2,2>>^ Pois de facto gememos nesta casa,^&#42;1^ desejando ansiosamente revestir-nos daquela que é para nós,^&#42;2^ a do céu,^&#42;3^

[NOTE]
====
. Ou: “morada”.
. Ou: “revestirmo-nos da nossa morada, que é”.
. Ou: “a nossa morada celestial”.
====

[[v47-5-3]]

^<<v47-5-3,3>>^ para que, quando nos revestirmos dela, não sejamos encontrados nus.

[[v47-5-4]]

^<<v47-5-4,4>>^ Na verdade, nós, os que estamos nesta tenda, gememos oprimidos, pois não nos queremos despir dela, mas queremos revestir-nos da outra, para que aquilo que é mortal seja consumido^&#42;1^ pela vida.

[NOTE]
====
. Ou: “engolido”.
====

[[v47-5-5]]

^<<v47-5-5,5>>^ Quem nos preparou para isto foi Deus, que nos deu o espírito como garantia daquilo que virá.^&#42;1^

[NOTE]
====
. Ou: “entrada (sinal); penhor daquilo que virá”.
====

[[v47-5-6]]

^<<v47-5-6,6>>^ Assim, estamos sempre confiantes e sabemos que, enquanto morarmos^&#42;1^ no corpo, estamos longe do Senhor,

[NOTE]
====
. Lit.: “enquanto tivermos o nosso lar”.
====

[[v47-5-7]]

^<<v47-5-7,7>>^ pois andamos pela fé, não pela vista.

[[v47-5-8]]

^<<v47-5-8,8>>^ Mas estamos cheios de confiança e preferimos estar longe do corpo e morar com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ Assim, quer moremos com ele, quer estejamos longe dele, temos por alvo agradar-lhe.

[[v47-5-10]]

^<<v47-5-10,10>>^ Pois todos nós compareceremos^&#42;1^ perante o tribunal do Cristo, para que cada um receba a sua retribuição de acordo com as coisas que fez enquanto esteve no corpo, sejam boas ou sejam más.^&#42;2^

[NOTE]
====
. Ou: “seremos manifestados”.
. Ou: “repugnantes”.
====

[[v47-5-11]]

^<<v47-5-11,11>>^ Portanto, visto que conhecemos o temor do Senhor, continuamos a persuadir homens, mas somos plenamente conhecidos por^&#42;1^ Deus. No entanto, espero que também sejamos plenamente conhecidos pela^&#42;2^ vossa consciência.

[NOTE]
====
. Ou: “manifestos a”.
. Ou: “manifestos à”.
====

[[v47-5-12]]

^<<v47-5-12,12>>^ Não nos estamos a recomendar novamente a vocês, mas estamos a dar-vos um incentivo para que falem de nós com orgulho, a fim de que sejam capazes de responder aos que se orgulham da aparência, e não do que há no coração.

[[v47-5-13]]

^<<v47-5-13,13>>^ Pois, se perdemos o juízo, foi para Deus; se temos juízo, é para vocês.

[[v47-5-14]]

^<<v47-5-14,14>>^ Pois o amor do Cristo impele-nos, porque nós concluímos o seguinte: um só homem morreu por todos — de facto, todos tinham morrido.

[[v47-5-15]]

^<<v47-5-15,15>>^ E ele morreu por todos para que os que vivem não continuassem a viver para si mesmos, mas para aquele que morreu por eles e foi levantado.

[[v47-5-16]]

^<<v47-5-16,16>>^ Assim, de agora em diante já não conhecemos ninguém de um ponto de vista carnal. Mesmo que antes tenhamos conhecido Cristo segundo a carne, certamente já não o conhecemos assim.

[[v47-5-17]]

^<<v47-5-17,17>>^ Portanto, se alguém está em união com Cristo, é uma nova criação. As coisas antigas passaram. Vejam! Coisas novas vieram à existência.

[[v47-5-18]]

^<<v47-5-18,18>>^ Mas tudo isto vem de Deus, que nos reconciliou consigo mesmo por meio de Cristo e nos deu o ministério da reconciliação

[[v47-5-19]]

^<<v47-5-19,19>>^ — isto é, que Deus, por meio de Cristo, estava a reconciliar um mundo consigo mesmo, sem lhes imputar os seus pecados; e ele confiou-nos a mensagem da reconciliação.

[[v47-5-20]]

^<<v47-5-20,20>>^ Somos, portanto, embaixadores, substituindo Cristo, como se Deus fizesse um apelo por nosso intermédio. Como substitutos de Cristo, suplicamos: “Sejam reconciliados com Deus.”

[[v47-5-21]]

^<<v47-5-21,21>>^ Àquele que não conheceu pecado, ele tornou-o pecado^&#42;1^ por nós, para que, por meio dele, nós nos tornássemos justiça de Deus.

[NOTE]
====
. Ou: “oferta pelo pecado”.
====

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]