include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-8-1]]

^<<v47-8-1,1>>^ Agora, irmãos, queremos que saibam da bondade imerecida de Deus que foi concedida às congregações da Macedónia.

[[v47-8-2]]

^<<v47-8-2,2>>^ Mesmo sob aflição durante uma grande prova, a imensa alegria e a extrema pobreza deles fizeram transbordar^&#42;1^ as riquezas da sua generosidade.

[NOTE]
====
. Ou: “tornaram abundantes”.
====

[[v47-8-3]]

^<<v47-8-3,3>>^ Pois o que eles fizeram foi segundo os seus recursos, sim, sou testemunha de que foi até além dos seus recursos;

[[v47-8-4]]

^<<v47-8-4,4>>^ eles, de sua própria iniciativa, suplicavam-nos insistentemente, pelo privilégio de dar bondosamente, para participarem no serviço^&#42;1^ de ajuda aos santos.

[NOTE]
====
. Ou: “ministério”.
====

[[v47-8-5]]

^<<v47-8-5,5>>^ E fizeram mais do que esperávamos, visto que se entregaram primeiro ao Senhor e a nós, pela vontade de Deus.

[[v47-8-6]]

^<<v47-8-6,6>>^ Assim, incentivámos Tito a terminar a coleta da vossa dádiva bondosa, visto que ele tinha iniciado esta obra no vosso meio.

[[v47-8-7]]

^<<v47-8-7,7>>^ Portanto, assim como vocês são ricos em tudo — em fé, em palavra, em conhecimento, em toda a diligência e no nosso amor por vocês —, sejam ricos também no que se refere a esta dádiva bondosa.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não digo isto como uma ordem, mas para vos informar da diligência de outros e para pôr à prova a sinceridade do vosso amor.

[[v47-8-9]]

^<<v47-8-9,9>>^ Pois vocês conhecem a bondade imerecida do nosso Senhor Jesus Cristo: embora fosse rico, tornou-se pobre por vossa causa, para que se tornassem ricos por meio da sua pobreza.

[[v47-8-10]]

^<<v47-8-10,10>>^ E a este respeito dou a minha opinião: isto é para o vosso próprio bem, visto que já faz um ano que não só iniciaram esta obra, mas também mostraram o desejo de a fazer.

[[v47-8-11]]

^<<v47-8-11,11>>^ Agora, então, terminem o que começaram, de modo que a vossa prontidão para agir seja completada segundo os recursos que têm à disposição.

[[v47-8-12]]

^<<v47-8-12,12>>^ Pois, se já existe prontidão, a dádiva é especialmente aceitável segundo o que uma pessoa tem, não segundo o que uma pessoa não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Porque não quero aliviar outros e sobrecarregar-vos a vocês;

[[v47-8-14]]

^<<v47-8-14,14>>^ mas, por meio de uma compensação,^&#42;1^ que o excedente que agora têm supra a necessidade deles, a fim de que o excedente deles também supra a vossa carência, e desse modo haja uma compensação.^&#42;2^

[NOTE]
====
. Ou: “reciprocidade”.
. Ou: “reciprocidade”.
====

[[v47-8-15]]

^<<v47-8-15,15>>^ Assim como está escrito: “Quem tinha muito não teve de mais, e quem tinha pouco não teve de menos.”

[[v47-8-16]]

^<<v47-8-16,16>>^ Graças sejam dadas a Deus por ter colocado no coração de Tito a mesma preocupação sincera que temos convosco,

[[v47-8-17]]

^<<v47-8-17,17>>^ porque ele não só correspondeu ao nosso incentivo, mas, como tem muito boa vontade, vai visitar-vos por iniciativa própria.

[[v47-8-18]]

^<<v47-8-18,18>>^ Porém, enviamos com ele o irmão que tem sido elogiado em todas as congregações por causa do que tem feito pelas boas novas.

[[v47-8-19]]

^<<v47-8-19,19>>^ Não só isso, mas ele também foi designado pelas congregações para ser nosso companheiro de viagem ao cuidarmos desta^&#42;1^ bondosa dádiva para a glória do Senhor e como prova da nossa prontidão em ajudar.

[NOTE]
====
. Ou: “administrarmos esta”.
====

[[v47-8-20]]

^<<v47-8-20,20>>^ Assim evitamos que alguém nos critique em relação a esta contribuição generosa da qual cuidamos.^&#42;1^

[NOTE]
====
. Ou: “que administramos”.
====

[[v47-8-21]]

^<<v47-8-21,21>>^ Pois ‘cuidamos de tudo honestamente, não somente à vista de Jeová,^&#42;1^ mas também à vista dos homens’.

[NOTE]
====
. Veja o Ap. A5.
====

[[v47-8-22]]

^<<v47-8-22,22>>^ Além disso, enviamos com eles o nosso irmão, cuja diligência comprovámos muitas vezes e em muitos assuntos; mas ele agora mostra-se ainda mais diligente por causa da grande confiança que tem em vocês.

[[v47-8-23]]

^<<v47-8-23,23>>^ No entanto, se houver qualquer dúvida quanto a Tito, ele é meu companheiro^&#42;1^ e colaborador a favor dos vossos interesses; ou, se houver dúvidas quanto aos nossos irmãos, eles são enviados^&#42;2^ de congregações e uma glória para Cristo.

[NOTE]
====
. Lit.: “parceiro”.
. Ou: “apóstolos”.
====

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, deem-lhes provas do vosso amor e mostrem às congregações o motivo de falarmos com orgulho a vosso respeito.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]