include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-7-1]]

^<<v47-7-1,1>>^ Portanto, amados, visto que temos estas promessas, purifiquemo-nos de toda a imundície da carne e do espírito, aperfeiçoando a santidade no temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Deem-nos um lugar no vosso coração. Não cometemos injustiças para com ninguém, não corrompemos ninguém, não nos aproveitámos de ninguém.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não digo isto para vos condenar. Pois eu já vos disse que estão no nosso coração, para morrer connosco e para viver connosco.

[[v47-7-4]]

^<<v47-7-4,4>>^ Falo com muita franqueza convosco. Orgulho-me muito de vocês. Estou plenamente consolado; estou a transbordar de alegria em toda a nossa aflição.

[[v47-7-5]]

^<<v47-7-5,5>>^ De facto, quando chegámos à Macedónia, não tivemos^&#42;1^ descanso, mas continuámos a ser afligidos de todos os modos — havia lutas por fora, temores por dentro.

[NOTE]
====
. Lit.: “a nossa carne não teve”.
====

[[v47-7-6]]

^<<v47-7-6,6>>^ Mas Deus, que consola os desanimados, consolou-nos com a presença de Tito;

[[v47-7-7]]

^<<v47-7-7,7>>^ e não somente com a sua presença, mas também com o consolo que ele recebeu por vossa causa, pois ele falou-nos do vosso desejo de me ver, da vossa profunda tristeza, da vossa sincera preocupação comigo;^&#42;1^ de modo que me alegrei ainda mais.

[NOTE]
====
. Lit.: “do vosso zelo por mim”.
====

[[v47-7-8]]

^<<v47-7-8,8>>^ Pois, mesmo que eu vos tenha entristecido com a minha carta, não o lamento. Embora a princípio eu o tenha lamentado (porque vejo que a carta vos entristeceu, ainda que por pouco tempo),

[[v47-7-9]]

^<<v47-7-9,9>>^ agora alegro-me, não porque ficaram entristecidos, mas porque a vossa tristeza vos levou ao arrependimento. Pois ficaram entristecidos segundo a vontade de Deus,^&#42;1^ e assim não foram prejudicados em nada por nossa causa.

[NOTE]
====
. Ou: “entristecidos de modo piedoso”.
====

[[v47-7-10]]

^<<v47-7-10,10>>^ Porque a tristeza segundo a vontade de Deus^&#42;1^ produz o arrependimento que leva à salvação, da qual ninguém se lamentará; mas a tristeza do mundo produz a morte.

[NOTE]
====
. Ou: “tristeza piedosa”.
====

[[v47-7-11]]

^<<v47-7-11,11>>^ Pois vejam a diligência que a vossa tristeza segundo a vontade de Deus^&#42;1^ produziu em vocês: fez com que se reabilitassem, que ficassem indignados, que tivessem temor, desejo sincero e zelo, que corrigissem o erro! Demonstraram em todos os sentidos que são puros^&#42;2^ neste assunto.

[NOTE]
====
. Ou: “tristeza piedosa”.
. Ou: “castos; inocentes”.
====

[[v47-7-12]]

^<<v47-7-12,12>>^ Embora eu vos tenha escrito, não o fiz por causa daquele que cometeu o erro, nem daquele contra quem se cometeu o erro, mas para que a vossa diligência em nos obedecer fosse evidente entre vocês, à vista de Deus.

[[v47-7-13]]

^<<v47-7-13,13>>^ É por isso que fomos consolados.
Mas, além do consolo que recebemos, nós alegrámo-nos ainda mais por causa da alegria de Tito, porque todos vocês reanimaram o seu espírito.

[[v47-7-14]]

^<<v47-7-14,14>>^ Pois, se eu falei com ele a vosso respeito com orgulho, não fiquei envergonhado; mas, assim como tudo o que vos dissemos era verdade, também se mostrou verdadeiro o que dissemos com orgulho a Tito.

[[v47-7-15]]

^<<v47-7-15,15>>^ Além disso, os seus ternos sentimentos para convosco aumentam quando ele se lembra da vossa obediência, de como o receberam com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Alegro-me porque em tudo posso ter confiança em vocês.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “posso ter bom ânimo por vossa causa”.
====

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]