include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-6-1]]

^<<v47-6-1,1>>^ Cooperando com ele, também vos exortamos a não aceitarem a bondade imerecida de Deus e perderem de vista o seu objetivo.

[[v47-6-2]]

^<<v47-6-2,2>>^ Pois ele diz: “Num tempo aceitável ouvi-te e num dia de salvação ajudei-te.” Vejam, agora é o tempo especialmente aceitável. Vejam, agora é o dia de salvação!

[[v47-6-3]]

^<<v47-6-3,3>>^ De modo algum damos motivos para tropeço, para que o nosso ministério não seja criticado;

[[v47-6-4]]

^<<v47-6-4,4>>^ mas recomendamo-nos de todos os modos como ministros de Deus, por perseverarmos em muitas provações, em tribulações, em tempos de privação, em dificuldades,

[[v47-6-5]]

^<<v47-6-5,5>>^ em espancamentos, em prisões, em tumultos, em trabalho árduo, em noites sem dormir, em ocasiões sem comer;

[[v47-6-6]]

^<<v47-6-6,6>>^ pela pureza, pelo conhecimento, pela paciência, pela bondade, pelo espírito santo, pelo amor sem hipocrisia,

[[v47-6-7]]

^<<v47-6-7,7>>^ por palavras verdadeiras, pelo poder de Deus; por meio das armas da justiça na mão direita^&#42;1^ e na esquerda,^&#42;2^

[NOTE]
====
. Talvez para ataque.
. Talvez para defesa.
====

[[v47-6-8]]

^<<v47-6-8,8>>^ por meio de glória e de desonra, por meio de difamação e de boa fama. Somos considerados como enganadores, embora sejamos verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos, embora reconhecidos; como prestes a morrer,^&#42;1^ mas, ainda assim, vivos; como castigados,^&#42;2^ embora não entregues à morte;

[NOTE]
====
. Ou: “considerados merecedores da morte”.
. Ou: “disciplinados”.
====

[[v47-6-10]]

^<<v47-6-10,10>>^ como tristes, mas sempre alegres; como pobres, mas enriquecendo a muitos; como não tendo nada, e ainda assim possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Falámos abertamente^&#42;1^ convosco, coríntios, e abrimos amplamente o nosso coração.

[NOTE]
====
. Ou: “Abrimos a nossa boca para falar”.
====

[[v47-6-12]]

^<<v47-6-12,12>>^ Não estamos a limitar o^&#42;1^ nosso afeto por vocês, mas vocês estão a limitar o vosso afeto por nós.

[NOTE]
====
. Ou: “Não estamos apertados quanto ao espaço no”.
====

[[v47-6-13]]

^<<v47-6-13,13>>^ Assim, como retribuição — falo como se fossem meus filhos —, abram também amplamente o vosso coração.^&#42;1^

[NOTE]
====
. Ou: “alarguem-se também”.
====

[[v47-6-14]]

^<<v47-6-14,14>>^ Não se ponham em jugo desigual com^&#42;1^ descrentes. Pois que afinidade tem a justiça com o que é contra a lei? Ou o que é que a luz tem em comum com a escuridão?

[NOTE]
====
. Ou: “Não se unam a”.
====

[[v47-6-15]]

^<<v47-6-15,15>>^ Além disso, que harmonia há entre Cristo e Belial?^&#42;1^ Ou o que é que o crente^&#42;2^ tem em comum^&#42;3^ com o descrente?

[NOTE]
====
. Derivado de uma palavra hebraica que significa “imprestável”. É uma referência a Satanás.
. Ou: “fiel”.
. Ou: “que parte tem o crente”.
====

[[v47-6-16]]

^<<v47-6-16,16>>^ E que acordo há entre o templo de Deus e os ídolos? Pois nós somos templo de um Deus vivente, como Deus disse: “Residirei entre eles e andarei entre eles, e eu serei o seu Deus, e eles serão o meu povo.”

[[v47-6-17]]

^<<v47-6-17,17>>^ “‘Portanto, saiam do meio deles e separem-se’, diz Jeová,^&#42;1^ ‘e parem de tocar em coisas impuras’”; “‘e eu irei acolher-vos’”.

[NOTE]
====
. Veja o Ap. A5.
====

[[v47-6-18]]

^<<v47-6-18,18>>^ “‘E eu irei tornar-me um pai para vocês, e vocês irão tornar-se filhos e filhas para mim’, diz Jeová,^&#42;1^ o Todo-Poderoso.”

[NOTE]
====
. Veja o Ap. A5.
====

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]