include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-11-1]]

^<<v47-11-1,1>>^ Eu gostaria que me suportassem numa pequena insensatez. Mas, de facto, vocês estão a suportar-me!

[[v47-11-2]]

^<<v47-11-2,2>>^ Pois tenho ciúmes de vocês, um ciúme semelhante ao de Deus,^&#42;1^ porque vos prometi pessoalmente em casamento a um só marido, para vos apresentar como virgem casta^&#42;2^ ao Cristo.

[NOTE]
====
. Lit.: “um zelo de Deus”.
. Ou: “pura”.
====

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas tenho medo de que, assim como a serpente seduziu Eva pela sua astúcia, a vossa mente seja de algum modo corrompida, afastando-se da sinceridade e da castidade^&#42;1^ que devemos ao Cristo.

[NOTE]
====
. Ou: “pureza”.
====

[[v47-11-4]]

^<<v47-11-4,4>>^ Pois, de facto, se alguém chega e prega um Jesus diferente do que nós pregámos, ou se vocês recebem um espírito diferente do que receberam, ou boas novas diferentes das que aceitaram, facilmente o suportam.

[[v47-11-5]]

^<<v47-11-5,5>>^ Pois não me considero inferior aos vossos superapóstolos em nada.

[[v47-11-6]]

^<<v47-11-6,6>>^ Mas, mesmo que eu não seja perito no falar, certamente o sou no conhecimento; de facto, deixámos isso claro para vocês de todos os modos e em todas as coisas.

[[v47-11-7]]

^<<v47-11-7,7>>^ Ou será que cometi um pecado por me humilhar para que fossem enaltecidos, ao declarar-vos de boa vontade as boas novas de Deus sem custo?

[[v47-11-8]]

^<<v47-11-8,8>>^ Despojei^&#42;1^ outras congregações por aceitar provisões^&#42;2^ delas para vos servir.

[NOTE]
====
. Lit.: “Roubei”.
. Ou: “apoio”.
====

[[v47-11-9]]

^<<v47-11-9,9>>^ Contudo, quando estive convosco e passei necessidade, não me tornei um fardo para ninguém, pois os irmãos que vieram da Macedónia supriram abundantemente as minhas necessidades. Sim, tive cuidado para não me tornar um fardo para vocês em nenhum sentido, e continuarei a fazê-lo.

[[v47-11-10]]

^<<v47-11-10,10>>^ Tão certo como a verdade de Cristo estar em mim, não deixarei de falar sobre isso com orgulho nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Porquê? Porque não vos amo? Deus sabe que vos amo.

[[v47-11-12]]

^<<v47-11-12,12>>^ Mas o que estou a fazer, vou continuar a fazer, para eliminar o pretexto daqueles que procuram um motivo^&#42;1^ para serem considerados iguais a nós nas coisas das quais^&#42;2^ se gabam.

[NOTE]
====
. Ou: “pretexto”.
. Ou: “no cargo do qual”.
====

[[v47-11-13]]

^<<v47-11-13,13>>^ Pois tais homens são falsos apóstolos, trabalhadores enganosos, disfarçados de apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E não é de admirar, pois o próprio Satanás disfarça-se de anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não nos surpreende que os servos^&#42;1^ dele também se disfarcem de servos^&#42;2^ da justiça. Mas o fim deles será segundo as suas obras.

[NOTE]
====
. Ou: “ministros”.
. Ou: “ministros”.
====

[[v47-11-16]]

^<<v47-11-16,16>>^ Digo novamente: Que ninguém pense que sou insensato. Mas, se pensam isso, então aceitem-me como um insensato, para que eu também me gabe um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ O que digo agora, não digo seguindo o exemplo do Senhor, mas como alguém insensato, com a autoconfiança de quem se gaba.

[[v47-11-18]]

^<<v47-11-18,18>>^ Já que muitos se gabam segundo a carne,^&#42;1^ eu também me vou gabar.

[NOTE]
====
. Isto é, por motivos humanos.
====

[[v47-11-19]]

^<<v47-11-19,19>>^ Vocês, que são tão “sensatos”, suportam de boa vontade os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ De facto, suportam a quem quer que vos escravize, quem quer que devore os vossos bens, quem quer que vos tire o que têm, quem quer que se enalteça sobre vocês, quem quer que vos bata no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ É uma desonra para nós dizê-lo, pois pode parecer que fomos fracos.
Mas, se outros agem com ousadia — falo como insensato —, eu também ajo com ousadia.

[[v47-11-22]]

^<<v47-11-22,22>>^ São eles hebreus? Eu também sou. São israelitas? Eu também sou. São descendência^&#42;1^ de Abraão? Eu também sou.

[NOTE]
====
. Lit.: “semente”.
====

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? Respondo como um louco: ainda mais destacadamente o sou — trabalhei mais, fui preso mais vezes, sofri incontáveis golpes e muitas vezes corri perigo de morte;

[[v47-11-24]]

^<<v47-11-24,24>>^ cinco vezes recebi dos judeus 40 golpes menos um,

[[v47-11-25]]

^<<v47-11-25,25>>^ três vezes fui espancado com varas, uma vez fui apedrejado, três vezes naufraguei, uma noite e um dia passei em alto-mar;

[[v47-11-26]]

^<<v47-11-26,26>>^ em muitas viagens, em perigos de rios, em perigos de ladrões, em perigos da parte do meu próprio povo, em perigos da parte das nações, em perigos na cidade, em perigos no deserto,^&#42;1^ em perigos no mar, em perigos entre falsos irmãos,

[NOTE]
====
. Veja o Glossário.
====

[[v47-11-27]]

^<<v47-11-27,27>>^ em grande esforço e trabalho árduo, em muitas noites sem dormir, em fome e sede, frequentemente sem ter o que comer, em frio e sem ter o que vestir.^&#42;1^

[NOTE]
====
. Lit.: “e em nudez”.
====

[[v47-11-28]]

^<<v47-11-28,28>>^ Além de todas estas coisas exteriores, há o que pesa sobre mim diariamente:^&#42;1^ a ansiedade por todas as congregações.

[NOTE]
====
. Ou: “há a pressão diária que enfrento”.
====

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem está fraco, sem que eu também me sinta fraco? Quem tropeça, sem que eu fique enfurecido?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se tenho de me gabar, vou gabar-me das coisas que mostram a minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, Aquele que tem de ser louvado para sempre, sabe que não estou a mentir.

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o governador sob o rei Aretas pôs guardas na cidade dos damascenos para me prenderem,

[[v47-11-33]]

^<<v47-11-33,33>>^ mas desceram-me num cesto^&#42;1^ por uma janela na muralha da cidade, e escapei das mãos dele.

[NOTE]
====
. Ou: “cesto de vime”.
====

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]