include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-9-1]]

^<<v47-9-1,1>>^ Quanto ao serviço^&#42;1^ a favor dos santos, já não é preciso escrever-vos,

[NOTE]
====
. Ou: “ministério”.
====

[[v47-9-2]]

^<<v47-9-2,2>>^ pois conheço a vossa prontidão e falo dela com orgulho aos macedónios, dizendo que a Acaia já está pronta há um ano, e o vosso zelo estimulou a maioria deles.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas estou a enviar os irmãos, para que o orgulho que temos em vocês neste respeito não se mostre infundado, e para que estejam realmente prontos, assim como eu disse que estariam.

[[v47-9-4]]

^<<v47-9-4,4>>^ Senão, se os macedónios fossem comigo e não vos encontrassem prontos, nós — para não dizer vocês — ficaríamos envergonhados por termos tido confiança em vocês.

[[v47-9-5]]

^<<v47-9-5,5>>^ Por isso achei necessário incentivar os irmãos a visitar-vos primeiro e a preparar com antecedência a vossa prometida dádiva generosa, para que estivesse pronta como algo dado com generosidade, e não à força.

[[v47-9-6]]

^<<v47-9-6,6>>^ Mas, quanto a isto, quem semear parcimoniosamente^&#42;1^ colherá também parcimoniosamente,^&#42;2^ e quem semear generosamente colherá também generosamente.

[NOTE]
====
. Ou: “de uma forma moderada ou escassa”.
. Ou: “de uma forma moderada ou escassa”.
====

[[v47-9-7]]

^<<v47-9-7,7>>^ Faça cada um conforme resolveu no coração, não a contragosto^&#42;1^ nem por obrigação, pois Deus ama quem dá com alegria.

[NOTE]
====
. Ou: “não com relutância”.
====

[[v47-9-8]]

^<<v47-9-8,8>>^ Além disso, Deus é capaz de vos dar abundantemente toda a Sua bondade imerecida, para que sejam sempre plenamente autossuficientes em tudo, e também para que tenham bastante para toda a boa obra.

[[v47-9-9]]

^<<v47-9-9,9>>^ (Assim como está escrito: “Ele distribui amplamente;^&#42;1^ dá aos pobres. A sua justiça permanece para sempre.”

[NOTE]
====
. Ou: “generosamente”.
====

[[v47-9-10]]

^<<v47-9-10,10>>^ Aquele que fornece abundantemente semente ao semeador e pão como alimento também fornecerá e multiplicará a semente para semearem e aumentará a colheita da vossa justiça.)

[[v47-9-11]]

^<<v47-9-11,11>>^ Em tudo estão a ser enriquecidos para praticar todo o tipo de generosidade, a qual produz por nosso intermédio agradecimentos a Deus;

[[v47-9-12]]

^<<v47-9-12,12>>^ porque o ministério deste serviço público não somente suprirá adequadamente as necessidades dos santos, mas também se tornará uma abundante fonte de agradecimentos a Deus.

[[v47-9-13]]

^<<v47-9-13,13>>^ Eles glorificam a Deus, pois este serviço de ajuda^&#42;1^ prova que vocês são submissos às boas novas a respeito do Cristo, conforme declararam publicamente, e que são generosos na vossa contribuição para eles e para todos.

[NOTE]
====
. Ou: “este ministério”.
====

[[v47-9-14]]

^<<v47-9-14,14>>^ E, com súplicas a vosso favor, eles expressam que vos amam, por causa da extraordinária bondade imerecida de Deus para convosco.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças sejam dadas a Deus pela Sua indescritível dádiva.^&#42;1^

[NOTE]
====
. Ou: “dádiva gratuita”.
====

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]