include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-12-1]]

^<<v47-12-1,1>>^ Tenho de me gabar. Não há nada a ganhar com isso, mas passarei às visões sobrenaturais e revelações da parte do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em união com Cristo que, há 14 anos — quer no corpo, quer fora do corpo, não sei; Deus sabe —, foi arrebatado ao terceiro céu.

[[v47-12-3]]

^<<v47-12-3,3>>^ Sim, conheço esse homem que — quer no corpo, quer separado do corpo, não sei; Deus sabe —

[[v47-12-4]]

^<<v47-12-4,4>>^ foi arrebatado para o paraíso e ouviu palavras que não podem ser ditas e que não se permite ao homem falar.

[[v47-12-5]]

^<<v47-12-5,5>>^ Vou-me gabar de tal homem, mas não me gabarei de mim mesmo, a não ser das minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, mesmo que me quisesse gabar, não seria insensato, porque diria a verdade. Mas evito fazê-lo para que ninguém me dê crédito por algo além do que vê em mim ou do que ouve de mim,

[[v47-12-7]]

^<<v47-12-7,7>>^ só porque recebo tais revelações extraordinárias.
Para impedir que eu ficasse enaltecido demais, foi-me dado um espinho na carne, um anjo de Satanás, para me esbofetear^&#42;1^ continuamente, a fim de que eu não me enaltecesse demais.

[NOTE]
====
. Ou: “espancar”.
====

[[v47-12-8]]

^<<v47-12-8,8>>^ Três vezes supliquei ao Senhor pedindo que o afastasse de mim.

[[v47-12-9]]

^<<v47-12-9,9>>^ Mas ele disse-me: “A minha bondade imerecida é suficiente para ti, pois o meu poder está a ser aperfeiçoado na fraqueza.” Com muita alegria, então, vou-me gabar das minhas fraquezas, para que o poder do Cristo permaneça sobre mim como uma tenda.

[[v47-12-10]]

^<<v47-12-10,10>>^ Assim, tenho prazer em fraquezas, em insultos, em privações, em perseguições e dificuldades, por Cristo. Pois, quando estou fraco, então é que sou poderoso.

[[v47-12-11]]

^<<v47-12-11,11>>^ Tornei-me insensato. Vocês obrigaram-me a isso, porque me deveriam ter recomendado. Pois não me mostrei em nada inferior aos vossos superapóstolos, embora eu não seja nada.

[[v47-12-12]]

^<<v47-12-12,12>>^ De facto, os sinais que identificam um apóstolo foram produzidos entre vocês com grande perseverança, e por sinais, milagres^&#42;1^ e obras poderosas.

[NOTE]
====
. Ou: “portentos”.
====

[[v47-12-13]]

^<<v47-12-13,13>>^ Pois em que é que vocês foram menos favorecidos do que as outras congregações, a não ser no facto de que eu mesmo não me tornei um fardo para vocês? Perdoem-me bondosamente esta injustiça.

[[v47-12-14]]

^<<v47-12-14,14>>^ Vejam, esta é a terceira vez que estou pronto para ir visitar-vos, e não me tornarei um fardo. Pois procuro não os vossos bens, mas a vocês; porque não se espera que os filhos acumulem para os pais, mas sim os pais para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Quanto a mim, de muito boa vontade gastarei tudo e serei completamente gasto a vosso favor.^&#42;1^ Se vos amo tanto, deveria eu ser amado menos?

[NOTE]
====
. Ou: “a favor das vossas almas”.
====

[[v47-12-16]]

^<<v47-12-16,16>>^ Mas, seja como for, não vos sobrecarreguei. No entanto, vocês dizem que fui “ardiloso” e que vos apanhei “com astúcia”.

[[v47-12-17]]

^<<v47-12-17,17>>^ Será que me aproveitei de vocês por meio de algum daqueles que vos enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Insisti com Tito para que vos visitasse e enviei o irmão com ele. Será que Tito se aproveitou de vocês? Por acaso não andámos no mesmo espírito, e nas mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Será que pensaram durante esse tempo todo que estávamos a fazer a nossa defesa perante vocês? É perante Deus que estamos a falar, em união com Cristo. Mas, amados, tudo o que fazemos é para vos edificar.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois receio que, quando chegar aí, talvez não vos encontre como eu queria, e eu não seja como queriam, mas, em vez disso, talvez encontre brigas, ciúmes, acessos de ira, discórdias, calúnias, mexericos,^&#42;1^ demonstrações de orgulho e desordens.

[NOTE]
====
. Ou: “tagarelice”.
====

[[v47-12-21]]

^<<v47-12-21,21>>^ Talvez, quando eu voltar, o meu Deus me humilhe diante de vocês, e eu tenha de chorar por muitos que anteriormente pecaram e não se arrependeram da impureza, da imoralidade sexual^&#42;1^ e da conduta insolente^&#42;2^ que praticaram.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
. Ou: “conduta desavergonhada”. Em grego, asélgeia. Veja o Glossário.
====

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]