include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-10-1]]

^<<v10-10-1,1>>^ Algum tempo depois, o rei dos amonitas morreu, e o seu filho Hanum tornou-se rei no seu lugar.

[[v10-10-2]]

^<<v10-10-2,2>>^ Então, David disse: “Demonstrarei amor leal a Hanum, filho de Naás, assim como o seu pai demonstrou amor leal para comigo.” Portanto, David enviou os seus servos para consolá-lo pela morte do seu pai. Contudo, quando os servos de David chegaram à terra dos amonitas,

[[v10-10-3]]

^<<v10-10-3,3>>^ os príncipes dos amonitas disseram a Hanum, seu senhor: “Acha que foi para honrar o seu pai que David lhe enviou consoladores? David enviou os seus servos para fazer o reconhecimento da cidade, espiá-la e destruí-la.”

[[v10-10-4]]

^<<v10-10-4,4>>^ Seguidamente, Hanum agarrou os servos de David, rapou-lhes metade da barba, cortou-lhes as roupas pela metade, à altura das nádegas, e, depois, mandou-os embora.

[[v10-10-5]]

^<<v10-10-5,5>>^ Quando contaram isto a David, ele enviou imediatamente homens ao encontro dos seus servos, porque eles tinham sido muito humilhados. O rei disse-lhes: “Fiquem em Jericó e voltem quando a vossa barba tiver crescido.”

[[v10-10-6]]

^<<v10-10-6,6>>^ Com o tempo, os amonitas perceberam que tinham despertado o ódio de^&#42;1^ David. Então, os amonitas enviaram mensageiros para contratar 20 000 soldados^&#42;2^ sírios de Bete-Reobe e de Zobá. Contrataram também o rei de Maacá, com 1000 homens, e 12 000 homens de Istobe.^&#42;3^

[NOTE]
====
. Ou: “se tinham tornado um mau cheiro para”.
. Ou: “soldados a pé”.
. Ou: “homens de Tobe”.
====

[[v10-10-7]]

^<<v10-10-7,7>>^ Quando David soube disso, enviou Joabe e todo o exército, incluindo os guerreiros mais valentes.

[[v10-10-8]]

^<<v10-10-8,8>>^ E os amonitas saíram e puseram-se em formação de batalha à entrada do portão da cidade, ao passo que os sírios de Zobá e de Reobe, juntamente com Istobe^&#42;1^ e Maacá, se posicionaram à parte, em campo aberto.

[NOTE]
====
. Ou: “homens de Tobe”.
====

[[v10-10-9]]

^<<v10-10-9,9>>^ Quando Joabe viu que as forças de ataque vinham contra ele pela frente e pela retaguarda, escolheu alguns dos melhores soldados de Israel e colocou-os em formação de batalha para enfrentar os sírios.

[[v10-10-10]]

^<<v10-10-10,10>>^ Ele deixou o restante dos homens sob o comando^&#42;1^ do seu irmão Abisai, a fim de colocá-los em formação de batalha para enfrentar os amonitas.

[NOTE]
====
. Lit.: “na mão”.
====

[[v10-10-11]]

^<<v10-10-11,11>>^ Então, Joabe disse: “Se os sírios se tornarem demasiado fortes para mim, vem ajudar-me; mas, se os amonitas se tornarem demasiado fortes para ti, eu vou ajudar-te.

[[v10-10-12]]

^<<v10-10-12,12>>^ Temos de ser fortes e lutar com coragem pelo nosso povo e pelas cidades do nosso Deus, e Jeová fará o que for bom aos Seus olhos.”

[[v10-10-13]]

^<<v10-10-13,13>>^ Assim, Joabe e os seus homens avançaram para lutar contra os sírios, e estes fugiram de diante dele.

[[v10-10-14]]

^<<v10-10-14,14>>^ Quando os amonitas viram que os sírios tinham fugido, eles fugiram de Abisai e entraram na cidade. Depois dessa batalha contra os amonitas, Joabe voltou a Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Quando os sírios viram que tinham sido derrotados por Israel, reagruparam-se.

[[v10-10-16]]

^<<v10-10-16,16>>^ De seguida, Hadadezer convocou os sírios que estavam na região do rio Eufrates,^&#42;1^ e eles vieram a Helão, comandados por Sobaque, o chefe do exército de Hadadezer.

[NOTE]
====
. Lit.: “do Rio”.
====

[[v10-10-17]]

^<<v10-10-17,17>>^ Ao ser informado disso, David reuniu imediatamente todo o Israel, atravessou o Jordão e chegou a Helão. Os sírios puseram-se então em formação de batalha para enfrentar David e lutaram contra ele.

[[v10-10-18]]

^<<v10-10-18,18>>^ No entanto, os sírios fugiram de Israel. David matou 700 condutores de carros de guerra e 40 000 cavaleiros sírios, e feriu Sobaque, chefe do exército deles, que morreu ali mesmo.

[[v10-10-19]]

^<<v10-10-19,19>>^ Quando todos os reis, servos de Hadadezer, viram que tinham sido derrotados por Israel, fizeram imediatamente paz com Israel e tornaram-se seus súbditos. E os sírios ficaram com medo de ajudar novamente os amonitas.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]