include::./index.adoc[]

[[v10-23-0]]
=== 2 Samuel, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-23-1]]

^<<v10-23-1,1>>^ Estas são as últimas palavras de David:
“Palavras de David, filho de Jessé,
Palavras do homem que foi exaltado,
O ungido do Deus de Jacó,
O agradável cantor^&#42;1^ dos cânticos de Israel.

[NOTE]
====
. Ou: “O agradável”.
====

[[v10-23-2]]

^<<v10-23-2,2>>^ O espírito de Jeová falou por meio de mim;
A sua palavra estava na minha língua.

[[v10-23-3]]

^<<v10-23-3,3>>^ O Deus de Israel falou;
A Rocha de Israel disse-me:
‘Quando aquele que governa a humanidade é justo
E governa no temor de Deus,

[[v10-23-4]]

^<<v10-23-4,4>>^ O seu governo é como a luz da manhã, quando o sol brilha
Numa manhã sem nuvens.
É como a claridade depois da chuva,
Que faz a relva brotar da terra.’

[[v10-23-5]]

^<<v10-23-5,5>>^ Não é assim a minha casa perante Deus?
Pois ele fez comigo um pacto eterno,
Bem definido em cada pormenor e seguro.
Visto que este significa toda a minha salvação e todo o meu prazer,
Não é por esse motivo que ele o fará florescer?

[[v10-23-6]]

^<<v10-23-6,6>>^ Mas todos os homens maus são como espinheiros que se deitam fora,
Que não podem ser arrancados com as mãos.

[[v10-23-7]]

^<<v10-23-7,7>>^ O homem que lhes toca
Precisa de armar-se com ferro e com o cabo de uma lança,
E eles devem ser completamente queimados com fogo onde quer que estiverem.”

[[v10-23-8]]

^<<v10-23-8,8>>^ Estes são os nomes dos guerreiros valentes de David: Josebe-Bassebete, um taquemonita, chefe dos três. Numa ocasião, ele matou 800 homens com a sua lança.

[[v10-23-9]]

^<<v10-23-9,9>>^ Depois dele, vinha Eleazar, filho de Dodo, filho de Aoí. Ele era um dos três guerreiros valentes que estavam com David quando desafiaram os filisteus. Os filisteus tinham-se reunido para a batalha, e, quando os homens de Israel recuaram,

[[v10-23-10]]

^<<v10-23-10,10>>^ ele manteve a sua posição e golpeou os filisteus até o seu braço ficar cansado e a sua mão ficar dura de tanto segurar a espada. Assim, Jeová deu-lhes naquele dia uma grande vitória;^&#42;1^ e os soldados voltaram^&#42;2^ depois de Eleazar, para recolher o despojo dos cadáveres.

[NOTE]
====
. Ou: “salvação”.
. Ou: “o povo voltou”.
====

[[v10-23-11]]

^<<v10-23-11,11>>^ Depois dele, vinha Samá, filho de Agé, o hararita. Quando os filisteus se reuniram em Leí, onde havia uma plantação de lentilhas, os soldados fugiram^&#42;1^ por causa dos filisteus.

[NOTE]
====
. Ou: “o povo fugiu”.
====

[[v10-23-12]]

^<<v10-23-12,12>>^ Contudo, ele posicionou-se no meio da plantação e defendeu-a, matando os filisteus, de modo que Jeová lhes deu uma grande vitória.^&#42;1^

[NOTE]
====
. Ou: “salvação”.
====

[[v10-23-13]]

^<<v10-23-13,13>>^ Três dos 30 chefes foram encontrar-se com David na caverna de Adulão durante a colheita, enquanto um grupo de soldados filisteus^&#42;1^ estava acampado no vale^&#42;2^ de Refaim.

[NOTE]
====
. Ou: “uma aldeia de tendas dos filisteus”.
. Ou: “na planície”.
====

[[v10-23-14]]

^<<v10-23-14,14>>^ Nessa época, David estava no seu refúgio e havia um posto avançado dos filisteus em Belém.

[[v10-23-15]]

^<<v10-23-15,15>>^ David expressou o seguinte desejo: “Quem me dera beber da água da cisterna que fica junto ao portão de Belém!”

[[v10-23-16]]

^<<v10-23-16,16>>^ Em vista disso, os três guerreiros valentes invadiram o acampamento dos filisteus, tiraram água da cisterna que fica junto ao portão de Belém e trouxeram-na a David. Porém, ele não a quis beber e derramou-a para Jeová.

[[v10-23-17]]

^<<v10-23-17,17>>^ Ele disse: “Eu nunca faria tal coisa, ó Jeová! Como é que eu poderia beber o sangue dos homens que arriscaram a sua vida?”^&#42;1^ Assim, ele não a quis beber. Estas foram as façanhas dos três guerreiros valentes de David.

[NOTE]
====
. Ou: “alma”.
====

[[v10-23-18]]

^<<v10-23-18,18>>^ Abisai, irmão de Joabe, filho de Zeruia, era o chefe de outro grupo de três. Ele matou 300 homens com a sua lança e era tão famoso como os três primeiros.

[[v10-23-19]]

^<<v10-23-19,19>>^ Embora fosse o que se destacava mais entre os três do grupo e apesar de ser o chefe deles, não chegou à categoria dos três primeiros.

[[v10-23-20]]

^<<v10-23-20,20>>^ Benaia, filho de Jeoiada, era um homem corajoso^&#42;1^ que realizou muitas façanhas em Cabzeel. Ele matou os dois filhos de Ariel, de Moabe; desceu a uma cisterna num dia em que nevou, e matou um leão.

[NOTE]
====
. Lit.: “o filho de um homem de valor”.
====

[[v10-23-21]]

^<<v10-23-21,21>>^ Além disso, ele matou um egípcio de tamanho extraordinário. Embora o egípcio tivesse uma lança na mão, Benaia enfrentou-o com uma vara. Ele arrancou a lança da mão do egípcio e matou-o com ela.

[[v10-23-22]]

^<<v10-23-22,22>>^ Estas foram as façanhas de Benaia, filho de Jeoiada. Ele era tão famoso como os três guerreiros valentes.

[[v10-23-23]]

^<<v10-23-23,23>>^ Embora se destacasse ainda mais do que os 30, não chegou à categoria dos três. No entanto, David designou-o sobre a sua guarda pessoal.

[[v10-23-24]]

^<<v10-23-24,24>>^ Asael, irmão de Joabe, estava entre os 30: Elanã, filho de Dodo, de Belém;

[[v10-23-25]]

^<<v10-23-25,25>>^ Samá, o harodita; Elica, o harodita;

[[v10-23-26]]

^<<v10-23-26,26>>^ Helez, o paltita; Ira, filho de Iques, o tecoíta;

[[v10-23-27]]

^<<v10-23-27,27>>^ Abiezer, o anatotita; Mebunai, o husatita;

[[v10-23-28]]

^<<v10-23-28,28>>^ Zalmom, o aoíta; Maarai, o netofatita;

[[v10-23-29]]

^<<v10-23-29,29>>^ Helebe, filho de Baaná, o netofatita; Itai, filho de Ribai, de Gibeá dos benjaminitas;

[[v10-23-30]]

^<<v10-23-30,30>>^ Benaia, piratonita; Hidai, dos vales^&#42;1^ de Gaás;

[NOTE]
====
. Ou: “uádis”. Veja o Glossário.
====

[[v10-23-31]]

^<<v10-23-31,31>>^ Abi-Albom, o arbatita; Azmavete, o barumita;

[[v10-23-32]]

^<<v10-23-32,32>>^ Eliaba, o saalbonita; os filhos de Jásen; Jonatã;

[[v10-23-33]]

^<<v10-23-33,33>>^ Samá, o hararita; Aião, filho de Sarar, o hararita;

[[v10-23-34]]

^<<v10-23-34,34>>^ Elifelete, filho de Aasbai, filho do maacatita; Elião, filho de Aitofel, o gilonita;

[[v10-23-35]]

^<<v10-23-35,35>>^ Hezro, o carmelita; Paarai, o arbita;

[[v10-23-36]]

^<<v10-23-36,36>>^ Igal, filho de Natã, de Zobá; Bani, o gadita;

[[v10-23-37]]

^<<v10-23-37,37>>^ Zeleque, o amonita; Naarai, o beerotita, escudeiro de Joabe, filho de Zeruia;

[[v10-23-38]]

^<<v10-23-38,38>>^ Ira, o itrita; Garebe, o itrita;

[[v10-23-39]]

^<<v10-23-39,39>>^ e Urias, o hitita — 37 ao todo.

'''

xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[&#60; Capítulo Anterior] | <<v10-23-0,Topo>> | xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[Próximo Capítulo &#62;]