include::./index.adoc[]

[[v10-1-0]]
=== 2 Samuel, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-1-1]]

^<<v10-1-1,1>>^ Depois da morte de Saul, quando David retornou após derrotar^&#42;1^ os amalequitas, David permaneceu dois dias em Ziclague.

[NOTE]
====
. Ou: “golpear”.
====

[[v10-1-2]]

^<<v10-1-2,2>>^ No terceiro dia, veio um homem do acampamento de Saul, com as roupas rasgadas e com terra na cabeça. Quando ele se aproximou de David, prostrou-se, lançando-se por terra.

[[v10-1-3]]

^<<v10-1-3,3>>^ David perguntou-lhe: “De onde vens?” Ele respondeu: “Escapei do acampamento de Israel.”

[[v10-1-4]]

^<<v10-1-4,4>>^ David perguntou-lhe: “O que é que aconteceu? Conta-me, por favor.” Ele disse: “Os soldados fugiram^&#42;1^ da batalha, e muitos foram feridos e morreram. Até mesmo Saul e o seu filho Jonatã morreram.”

[NOTE]
====
. Ou: “O povo fugiu”.
====

[[v10-1-5]]

^<<v10-1-5,5>>^ David perguntou ao homem que lhe trouxe a notícia: “Como é que sabes que Saul e o seu filho Jonatã morreram?”

[[v10-1-6]]

^<<v10-1-6,6>>^ O homem respondeu: “Eu, por acaso, estava no monte Gilboa, e vi Saul a apoiar-se na sua lança, e os carros de guerra e os cavaleiros estavam a aproximar-se dele.

[[v10-1-7]]

^<<v10-1-7,7>>^ Quando olhou para trás, viu-me e chamou-me. Eu disse-lhe: ‘Estou aqui!’

[[v10-1-8]]

^<<v10-1-8,8>>^ Ele perguntou-me: ‘Quem és tu?’ Eu respondi: ‘Sou amalequita.’

[[v10-1-9]]

^<<v10-1-9,9>>^ Então, ele disse: ‘Anda cá e mata-me, pois estou em grande agonia, mas ainda estou vivo.’^&#42;1^

[NOTE]
====
. Ou: “porque toda a minha alma ainda está em mim”.
====

[[v10-1-10]]

^<<v10-1-10,10>>^ Por isso, fui até ele e matei-o, porque sabia que ele não conseguiria sobreviver depois de ter sido gravemente ferido. Então, tirei-lhe a coroa^&#42;1^ da cabeça e o bracelete do seu braço e trouxe-os até aqui, ao meu senhor.”

[NOTE]
====
. Ou: “o diadema”.
====

[[v10-1-11]]

^<<v10-1-11,11>>^ Em vista disso, David agarrou as suas roupas e rasgou-as, e todos os homens que estavam com ele fizeram o mesmo.

[[v10-1-12]]

^<<v10-1-12,12>>^ Eles lamentaram, choraram e jejuaram até ao anoitecer, por Saul, pelo seu filho Jonatã, pelo povo de Jeová e pela casa de Israel, porque tinham caído pela espada.

[[v10-1-13]]

^<<v10-1-13,13>>^ David perguntou ao homem que lhe trouxe a notícia: “De onde és?” Ele respondeu: “Sou filho de um residente estrangeiro amalequita.”

[[v10-1-14]]

^<<v10-1-14,14>>^ David disse-lhe: “Porque é que não temeste levantar a mão para matar o ungido de Jeová?”

[[v10-1-15]]

^<<v10-1-15,15>>^ Então, David chamou um dos seus homens e ordenou-lhe: “Vem até aqui e mata-o!” Portanto, o homem golpeou-o e ele morreu.

[[v10-1-16]]

^<<v10-1-16,16>>^ David disse-lhe: “Que o teu sangue recaia sobre a tua cabeça, porque foi a tua própria boca que te condenou, quando disse: ‘Eu matei o ungido de Jeová.’”

[[v10-1-17]]

^<<v10-1-17,17>>^ Então, David cantou um cântico fúnebre por Saul e pelo seu filho Jonatã,

[[v10-1-18]]

^<<v10-1-18,18>>^ e disse que se devia ensiná-lo ao povo de Judá. Esse cântico, chamado “O Arco”, está escrito no livro de Jasar e diz:

[[v10-1-19]]

^<<v10-1-19,19>>^ “A tua beleza, ó Israel, pereceu sobre os montes.
Como caíram os valentes!

[[v10-1-20]]

^<<v10-1-20,20>>^ Não o relatem em Gate;
Não o anunciem nas ruas de Ascalom,
Para que não se alegrem as filhas dos filisteus,
Para que não exultem as filhas dos incircuncisos.

[[v10-1-21]]

^<<v10-1-21,21>>^ Ó montes de Gilboa,
Não haja orvalho ou chuva sobre vocês,
Nem campos que produzam contribuições sagradas,
Porque ali foi profanado o escudo dos valentes,
O escudo de Saul já não está ungido com óleo.

[[v10-1-22]]

^<<v10-1-22,22>>^ Do sangue dos que eram mortos, da gordura dos valentes,
O arco de Jonatã não recuava,
E a espada de Saul não voltava sem êxito.

[[v10-1-23]]

^<<v10-1-23,23>>^ Saul e Jonatã, tão amados e queridos^&#42;1^ durante a sua vida,
Nem na morte foram separados.
Eram mais velozes do que as águias
E mais fortes do que os leões.

[NOTE]
====
. Ou: “e agradáveis”.
====

[[v10-1-24]]

^<<v10-1-24,24>>^ Ó filhas de Israel, chorem por Saul,
Que vos vestiu de escarlate e com adornos,
Que colocou enfeites de ouro na vossa roupa.

[[v10-1-25]]

^<<v10-1-25,25>>^ Como caíram os valentes na batalha!
Jonatã está morto sobre os montes!

[[v10-1-26]]

^<<v10-1-26,26>>^ Estou aflito por ti, meu irmão Jonatã;
Eras um amigo muito querido.
Para mim, o teu amor era superior ao amor das mulheres.

[[v10-1-27]]

^<<v10-1-27,27>>^ Como caíram os valentes,
E pereceram as armas de guerra!”

'''

xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[&#60; Capítulo Anterior] | <<v10-1-0,Topo>> | xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[Próximo Capítulo &#62;]