include::./index.adoc[]

[[v10-2-0]]
=== 2 Samuel, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-2-1]]

^<<v10-2-1,1>>^ Depois disso, David consultou a Jeová: “Devo ir para uma das cidades de Judá?” Jeová respondeu-lhe: “Vai.” David perguntou: “Para onde devo ir?” Ele respondeu: “Para Hébron.”

[[v10-2-2]]

^<<v10-2-2,2>>^ Então, David dirigiu-se para lá com as suas duas esposas: Ainoã, de Jezreel, e Abigail, viúva de Nabal, o carmelita.

[[v10-2-3]]

^<<v10-2-3,3>>^ David levou também os seus homens, cada um com os da sua casa, e eles estabeleceram-se nas cidades ao redor de Hébron.

[[v10-2-4]]

^<<v10-2-4,4>>^ De seguida, vieram os homens de Judá e ali ungiram David rei sobre a casa de Judá.
Eles disseram a David: “Foram os homens de Jabes-Gileade que enterraram Saul.”

[[v10-2-5]]

^<<v10-2-5,5>>^ Assim, David enviou mensageiros aos homens de Jabes-Gileade para lhes dizer: “Que Jeová vos abençoe, porque demonstraram amor leal para com Saul, vosso senhor, enterrando-o.

[[v10-2-6]]

^<<v10-2-6,6>>^ E que Jeová demonstre amor leal e fidelidade para convosco. Eu também demonstrarei bondade convosco pelo que fizeram.

[[v10-2-7]]

^<<v10-2-7,7>>^ Agora, fortaleçam as vossas mãos e sejam corajosos, pois o vosso senhor Saul está morto, e a casa de Judá ungiu-me rei sobre eles.”

[[v10-2-8]]

^<<v10-2-8,8>>^ No entanto, Abner, filho de Ner, chefe do exército de Saul, levou Is-Bosete, filho de Saul, a Maanaim, que fica do outro lado do rio,

[[v10-2-9]]

^<<v10-2-9,9>>^ e fez dele rei sobre Gileade, sobre os asuritas, sobre Jezreel, sobre Efraim, sobre Benjamim e sobre todo o Israel.

[[v10-2-10]]

^<<v10-2-10,10>>^ Is-Bosete, filho de Saul, tinha 40 anos de idade quando se tornou rei de Israel e reinou por dois anos. Porém, a casa de Judá apoiava David.

[[v10-2-11]]

^<<v10-2-11,11>>^ O tempo^&#42;1^ durante o qual David reinou sobre a casa de Judá, em Hébron, foi de sete anos e seis meses.

[NOTE]
====
. Lit.: “O número de dias”.
====

[[v10-2-12]]

^<<v10-2-12,12>>^ Depois de algum tempo, Abner, filho de Ner, e os servos de Is-Bosete, filho de Saul, foram de Maanaim para Gibeão.

[[v10-2-13]]

^<<v10-2-13,13>>^ Joabe, filho de Zeruia, e os servos de David também saíram e encontraram-se no reservatório de água de Gibeão. Um grupo ficou de um lado do reservatório, e o outro, do lado oposto.

[[v10-2-14]]

^<<v10-2-14,14>>^ Por fim, Abner disse a Joabe: “Que os homens se preparem e lutem^&#42;1^ diante de nós.” Joabe respondeu: “Que eles se preparem.”

[NOTE]
====
. Ou: “participem numa competição”.
====

[[v10-2-15]]

^<<v10-2-15,15>>^ Então, eles apresentaram-se e atravessaram para lutar. Foram escolhidos 12 benjaminitas do grupo de Is-Bosete, filho de Saul, e 12 servos de David.

[[v10-2-16]]

^<<v10-2-16,16>>^ Eles agarraram-se mutuamente pela cabeça, cada um enfiou a espada no lado do seu adversário e todos caíram mortos ao mesmo tempo. Por isso, chamou-se Helcate-Hazurim àquele lugar, que fica em Gibeão.

[[v10-2-17]]

^<<v10-2-17,17>>^ A batalha que se seguiu naquele dia foi muito violenta. Por fim, Abner e os homens de Israel foram derrotados pelos servos de David.

[[v10-2-18]]

^<<v10-2-18,18>>^ Os três filhos de Zeruia — Joabe, Abisai e Asael — estavam lá. Asael era capaz de correr como uma gazela em campo aberto.

[[v10-2-19]]

^<<v10-2-19,19>>^ Asael começou a perseguir Abner. Ele corria atrás de Abner sem se desviar nem para a direita nem para a esquerda.

[[v10-2-20]]

^<<v10-2-20,20>>^ Quando Abner olhou para trás, perguntou: “És tu, Asael?” Ele respondeu: “Sim, sou eu.”

[[v10-2-21]]

^<<v10-2-21,21>>^ Abner disse-lhe então: “Desvia-te para a direita ou para a esquerda, apanha um destes homens e fica com as coisas dele.” Contudo, Asael não quis parar de persegui-lo.

[[v10-2-22]]

^<<v10-2-22,22>>^ Abner disse novamente a Asael: “Para de me perseguir, senão, serei obrigado a matar-te. Depois disso, como é que eu poderia encarar o teu irmão Joabe?”

[[v10-2-23]]

^<<v10-2-23,23>>^ Todavia, Asael não parou. Então, Abner golpeou-o na barriga com a parte de trás da lança, de modo que esta lhe saiu pelas costas, e ele caiu e morreu ali onde estava. Todos os que passavam pelo lugar onde Asael tinha caído e morrido paravam.

[[v10-2-24]]

^<<v10-2-24,24>>^ Depois disso, Joabe e Abisai foram atrás de Abner. Ao pôr do sol, chegaram à colina de Amá, que fica em frente a Gia, no caminho para o deserto^&#42;1^ de Gibeão.

[NOTE]
====
. Veja o Glossário.
====

[[v10-2-25]]

^<<v10-2-25,25>>^ E os benjaminitas juntaram-se a Abner; eles formaram um só grupo de soldados, tomando posição no cume de uma colina.

[[v10-2-26]]

^<<v10-2-26,26>>^ Então, Abner gritou para Joabe: “Até quando é que a espada vai devorar? Não sabes que as consequências serão amargas? Quando é que vais ordenar aos teus homens^&#42;1^ que parem de perseguir os seus irmãos?”

[NOTE]
====
. Ou: “ao povo”.
====

[[v10-2-27]]

^<<v10-2-27,27>>^ Joabe respondeu: “Tão certo como o verdadeiro Deus vive, se não tivesses falado, os homens só iriam parar de perseguir os seus irmãos pela manhã.”

[[v10-2-28]]

^<<v10-2-28,28>>^ De seguida, Joabe tocou a buzina e os seus homens pararam de perseguir Israel; e a batalha terminou.

[[v10-2-29]]

^<<v10-2-29,29>>^ Durante toda aquela noite, Abner e os seus homens caminharam através do Arabá, atravessaram o Jordão, passaram por todo o vale^&#42;1^ e, por fim, chegaram a Maanaim.

[NOTE]
====
. Ou, possivelmente: “por todo o Bitrom”.
====

[[v10-2-30]]

^<<v10-2-30,30>>^ Depois de parar de perseguir Abner, Joabe reuniu todo o povo. Além de Asael, faltavam 19 dos servos de David.

[[v10-2-31]]

^<<v10-2-31,31>>^ No entanto, os servos de David tinham derrotado os benjaminitas e os homens de Abner — 360 deles tinham morrido.

[[v10-2-32]]

^<<v10-2-32,32>>^ Eles levaram Asael e enterraram-no no túmulo do seu pai, em Belém. Depois, Joabe e os seus homens caminharam durante toda a noite e chegaram a Hébron ao amanhecer.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]