include::./index.adoc[]

[[v10-17-0]]
=== 2 Samuel, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-17-1]]

^<<v10-17-1,1>>^ Aitofel disse então a Absalão: “Por favor, deixa-me escolher 12 000 homens e ir atrás de David, esta noite.

[[v10-17-2]]

^<<v10-17-2,2>>^ Vou atacá-lo quando ele estiver cansado e sem forças,^&#42;1^ e vou fazer com que ele entre em pânico. Todos os que estão com ele fugirão e eu matarei apenas o rei.

[NOTE]
====
. Ou: “e fraco em ambas as mãos”.
====

[[v10-17-3]]

^<<v10-17-3,3>>^ Depois, farei com que todo o povo volte para ti, mas isso vai depender do que acontecer com o homem que procuras. E todo o povo ficará em paz.”

[[v10-17-4]]

^<<v10-17-4,4>>^ A proposta era boa aos olhos de Absalão e de todos os anciãos de Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ No entanto, Absalão disse: “Chamem também Husai, o arquita, e ouçamos o que ele tem a dizer.”

[[v10-17-6]]

^<<v10-17-6,6>>^ Portanto, Husai compareceu perante Absalão. E Absalão disse-lhe: “Este foi o conselho de Aitofel. Devemos seguir o seu conselho? Se achares que não, diz tu o que devemos fazer.”

[[v10-17-7]]

^<<v10-17-7,7>>^ De seguida, Husai disse a Absalão: “Desta vez, o conselho dado por Aitofel não é bom.”

[[v10-17-8]]

^<<v10-17-8,8>>^ Husai disse ainda: “Sabes muito bem que o teu pai e os seus homens são valentes e que estão desesperados,^&#42;1^ como uma ursa que perdeu as crias no campo. Além disso, o teu pai é um guerreiro e não passará a noite com o povo.

[NOTE]
====
. Ou: “com a alma amargurada”.
====

[[v10-17-9]]

^<<v10-17-9,9>>^ Neste exato momento, ele deve estar escondido numa caverna^&#42;1^ ou noutro lugar qualquer. Se ele atacar primeiro, quem souber disso dirá: ‘Os apoiantes de Absalão foram derrotados!’

[NOTE]
====
. Ou: “cova; ravina”.
====

[[v10-17-10]]

^<<v10-17-10,10>>^ E até mesmo o homem corajoso, que tem um coração de leão, ficará fraco de tanto medo, porque todo o Israel sabe que o teu pai é um guerreiro valente, e que os homens que estão com ele são corajosos.

[[v10-17-11]]

^<<v10-17-11,11>>^ O meu conselho é o seguinte: reúne todos os homens de Israel, desde Dã até Berseba, tantos como os grãos de areia à beira-mar; e deves comandá-los na batalha.

[[v10-17-12]]

^<<v10-17-12,12>>^ Nós vamos atacá-lo onde quer que ele esteja. Cairemos sobre ele assim como o orvalho cai sobre a terra, e nenhum deles sobreviverá, nem ele nem os seus homens.

[[v10-17-13]]

^<<v10-17-13,13>>^ Se ele se esconder numa cidade, todo o Israel levará cordas até àquela cidade, e nós vamos arrastá-lo para o vale até não sobrar nem sequer uma única pequena pedra.”

[[v10-17-14]]

^<<v10-17-14,14>>^ Seguidamente, Absalão e todos os homens de Israel disseram: “O conselho de Husai, o arquita, é melhor do que o conselho de Aitofel!” Pois Jeová tinha decidido^&#42;1^ frustrar o bom conselho de Aitofel. Jeová fez isso para trazer calamidade sobre Absalão.

[NOTE]
====
. Ou: “ordenado”.
====

[[v10-17-15]]

^<<v10-17-15,15>>^ Mais tarde, Husai disse aos sacerdotes Zadoque e Abiatar: “Foi assim que Aitofel aconselhou Absalão e os anciãos de Israel, e foi assim que eu os aconselhei.

[[v10-17-16]]

^<<v10-17-16,16>>^ Agora, enviem rapidamente o seguinte aviso a David: ‘Não passes a noite nos pontos de travessia^&#42;1^ junto ao deserto, mas, sem falta, atravessa o rio, senão o rei e todo o seu povo poderão ser exterminados.’”^&#42;2^

[NOTE]
====
. Ou, possivelmente: “nas planícies desérticas”.
. Lit.: “engolidos”.
====

[[v10-17-17]]

^<<v10-17-17,17>>^ Jonatã e Aimaás estavam à espera em En-Rogel; uma serva levou-lhes o recado, e eles foram contar ao rei David, pois não quiseram correr o risco de serem vistos a entrar na cidade.

[[v10-17-18]]

^<<v10-17-18,18>>^ Contudo, um jovem viu-os e contou a Absalão. Então, eles partiram depressa e chegaram à casa de um homem em Baurim que tinha um poço no pátio da sua casa. Eles esconderam-se dentro dele,

[[v10-17-19]]

^<<v10-17-19,19>>^ e a esposa do homem colocou uma cobertura sobre a boca do poço e pôs grãos triturados sobre a mesma; ninguém soube disso.

[[v10-17-20]]

^<<v10-17-20,20>>^ Os servos de Absalão foram à casa da mulher e perguntaram-lhe: “Onde é que estão Aimaás e Jonatã?” A mulher respondeu-lhes: “Eles foram em direção às águas.” Então, os homens procuraram-nos, mas não os encontraram. Assim, voltaram a Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ Depois de os homens se terem ido embora, os dois saíram do poço e foram informar o rei David. Eles disseram-lhe: “Vão! Atravessem depressa o rio, porque foi isto que Aitofel disse contra vocês.”

[[v10-17-22]]

^<<v10-17-22,22>>^ Imediatamente, David e todo o povo que estava com ele começaram a atravessar o Jordão. Ao amanhecer, não havia ninguém que não tivesse atravessado o Jordão.

[[v10-17-23]]

^<<v10-17-23,23>>^ Quando Aitofel viu que o seu conselho não tinha sido seguido, selou um jumento e foi para casa, na sua cidade. Depois, deu instruções aos da sua casa e enforcou-se. Assim, ele morreu e foi enterrado na sepultura dos seus antepassados.

[[v10-17-24]]

^<<v10-17-24,24>>^ Entretanto, David foi a Maanaim e Absalão atravessou o Jordão com todos os homens de Israel.

[[v10-17-25]]

^<<v10-17-25,25>>^ Absalão colocou Amasa no lugar de Joabe para comandar o exército. Amasa era filho de um homem chamado Itra, o israelita, que teve relações com Abigail; ela era filha de Naás e irmã de Zeruia, mãe de Joabe.

[[v10-17-26]]

^<<v10-17-26,26>>^ Absalão e os homens de Israel acamparam-se na terra de Gileade.

[[v10-17-27]]

^<<v10-17-27,27>>^ Assim que David chegou a Maanaim, Sobi, filho de Naás, de Rabá dos amonitas, e Maquir, filho de Amiel, de Lo-Debar, e Barzilai, o gileadita de Rogelim,

[[v10-17-28]]

^<<v10-17-28,28>>^ trouxeram camas, bacias, panelas de barro, trigo, cevada, farinha, grãos torrados, favas, lentilhas e sementes tostadas,

[[v10-17-29]]

^<<v10-17-29,29>>^ além de mel, manteiga, ovelhas e queijo.^&#42;1^ Trouxeram tudo isto para que David e o povo que estava com ele comessem, pois disseram: “O povo está faminto, com sede e cansado no deserto.”

[NOTE]
====
. Lit.: “coalhada de gado”.
====

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]