include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-13-1]]

^<<v10-13-1,1>>^ Absalão, filho de David, tinha uma bela irmã chamada Tamar, e Amnom, filho de David, apaixonou-se por ela.

[[v10-13-2]]

^<<v10-13-2,2>>^ Amnom estava tão desesperado que ficou doente por causa de Tamar, sua irmã, pois ela era virgem e parecia impossível a Amnom fazer-lhe alguma coisa.

[[v10-13-3]]

^<<v10-13-3,3>>^ Amnom tinha um amigo chamado Jonadabe, filho de Simeia, irmão de David. Jonadabe era um homem muito esperto.

[[v10-13-4]]

^<<v10-13-4,4>>^ Portanto, Jonadabe perguntou-lhe: “Porque é que tu, filho do rei, andas, todos os dias, tão deprimido? Porque é que não me contas?” Amnom respondeu-lhe: “Estou apaixonado por Tamar, irmã do meu irmão Absalão.”

[[v10-13-5]]

^<<v10-13-5,5>>^ Jonadabe disse-lhe: “Deita-te na cama e finge que estás doente. Quando o teu pai vier visitar-te, diz-lhe: ‘Por favor, deixa que a minha irmã Tamar venha e me dê algo para comer. Se ela me preparar uma comida para doentes^&#42;1^ à minha frente, eu comerei das suas mãos.’”

[NOTE]
====
. Ou: “o pão de consolo”.
====

[[v10-13-6]]

^<<v10-13-6,6>>^ Assim, Amnom deitou-se e fingiu que estava doente; e o rei foi visitá-lo. Amnom disse então ao rei: “Por favor, deixa que a minha irmã Tamar venha e faça dois pães em forma de coração, aqui na minha presença, para que eu coma das suas mãos.”

[[v10-13-7]]

^<<v10-13-7,7>>^ Então, David mandou dizer a Tamar, na casa: “Por favor, vai à casa do teu irmão Amnom e prepara algo^&#42;1^ para ele comer.”

[NOTE]
====
. Ou: “o pão de consolo”.
====

[[v10-13-8]]

^<<v10-13-8,8>>^ Assim, Tamar foi à casa do seu irmão Amnom, onde ele estava deitado. Ela pegou na farinha, amassou-a, preparou os pães à frente dele e cozeu-os.

[[v10-13-9]]

^<<v10-13-9,9>>^ De seguida, ela pegou na panela e serviu-o. No entanto, Amnom recusou-se a comer e disse: “Mandem todos sair da minha presença!” E todos se retiraram.

[[v10-13-10]]

^<<v10-13-10,10>>^ Amnom disse então a Tamar: “Traz o pão^&#42;1^ ao meu quarto, para que eu coma das tuas mãos.” Assim, Tamar pegou nos pães em forma de coração que tinha feito e levou-os ao seu irmão Amnom, ao quarto.

[NOTE]
====
. Ou: “o pão de consolo”.
====

[[v10-13-11]]

^<<v10-13-11,11>>^ Quando ela lhe trouxe os pães para comer, ele agarrou-a e disse: “Vem, deita-te comigo, minha irmã.”

[[v10-13-12]]

^<<v10-13-12,12>>^ Porém, ela disse-lhe: “Não, meu irmão! Não me humilhes, pois não se faz uma coisa destas em Israel. Não cometas este ato vergonhoso.

[[v10-13-13]]

^<<v10-13-13,13>>^ Como é que eu me ia livrar da minha vergonha? Também tu serias considerado um homem desprezível em Israel. Por favor, fala com o rei, porque ele não se vai opor a que eu seja tua esposa.”

[[v10-13-14]]

^<<v10-13-14,14>>^ Contudo, Amnom não quis dar-lhe ouvidos. Então, ele dominou-a à força e humilhou-a, violando-a.

[[v10-13-15]]

^<<v10-13-15,15>>^ Depois, Amnom começou a odiá-la intensamente; o seu ódio por ela tornou-se maior do que o amor que tinha sentido. Ele disse-lhe: “Levanta-te; vai-te embora!”

[[v10-13-16]]

^<<v10-13-16,16>>^ E ela disse: “Não, meu irmão, pois mandar-me embora agora é pior do que aquilo que fizeste comigo!” No entanto, ele não quis ouvi-la.

[[v10-13-17]]

^<<v10-13-17,17>>^ Então, ele chamou o jovem que o servia e disse-lhe: “Tira esta pessoa da minha presença e tranca a porta!”

[[v10-13-18]]

^<<v10-13-18,18>>^ (Tamar estava a usar uma túnica especial,^&#42;1^ pois as filhas virgens do rei usavam esse tipo de roupa.) Portanto, o servo dele levou-a para fora e trancou a porta.

[NOTE]
====
. Ou: “enfeitada”.
====

[[v10-13-19]]

^<<v10-13-19,19>>^ Assim, Tamar pôs cinzas sobre a cabeça e rasgou a túnica que estava a usar; ela foi-se embora a chorar em voz alta, com as mãos na cabeça.

[[v10-13-20]]

^<<v10-13-20,20>>^ Depois disso, o seu irmão Absalão perguntou-lhe: “Foi o teu irmão Amnom que te fez isso? Não digas nada a ninguém, minha irmã. Ele é teu irmão. Não te aflijas por causa disso.” Por conseguinte, Tamar ficou a morar na casa do seu irmão Absalão sem ter contacto com outras pessoas.

[[v10-13-21]]

^<<v10-13-21,21>>^ Quando o rei David soube de tudo isto, ficou furioso. No entanto, não queria ferir os sentimentos de Amnom, seu filho, porque o amava, visto que ele era o seu primogénito.

[[v10-13-22]]

^<<v10-13-22,22>>^ E Absalão não disse nem uma palavra a Amnom, nem boa nem má, pois ficou com ódio a Amnom por ele ter humilhado a sua irmã Tamar.

[[v10-13-23]]

^<<v10-13-23,23>>^ Dois anos depois, os tosquiadores de ovelhas de Absalão estavam em Baal-Hazor, perto de Efraim, e Absalão convidou todos os filhos do rei para irem até lá.

[[v10-13-24]]

^<<v10-13-24,24>>^ Assim, Absalão compareceu perante o rei e disse: “O seu servo está a tosquiar as ovelhas. Por favor, que o rei e os seus servos venham comigo.”

[[v10-13-25]]

^<<v10-13-25,25>>^ O rei disse, porém, a Absalão: “Não, meu filho. Se formos todos, seremos um peso para ti.” Embora Absalão insistisse, o rei não quis ir, mas abençoou-o.

[[v10-13-26]]

^<<v10-13-26,26>>^ Absalão disse então: “Se não quer ir, deixe o meu irmão Amnom ir connosco.” O rei perguntou-lhe: “Porque deveria ele ir contigo?”

[[v10-13-27]]

^<<v10-13-27,27>>^ Contudo, Absalão insistiu; por isso, o rei mandou Amnom e todos os filhos do rei com ele.

[[v10-13-28]]

^<<v10-13-28,28>>^ E Absalão ordenou aos seus ajudantes: “Fiquem atentos, e, quando o coração de Amnom estiver alegre por causa do vinho, eu vou dizer-vos: ‘Matem Amnom!’ Então, devem matá-lo. Não tenham medo; sou eu que estou a dar a ordem. Sejam fortes e corajosos.”

[[v10-13-29]]

^<<v10-13-29,29>>^ E os ajudantes de Absalão fizeram a Amnom exatamente o que Absalão tinha ordenado. Então, os outros filhos do rei levantaram-se, montaram as suas mulas e fugiram.

[[v10-13-30]]

^<<v10-13-30,30>>^ Enquanto estavam a caminho, chegou a David a seguinte notícia: “Absalão matou todos os filhos do rei; nenhum deles sobreviveu.”

[[v10-13-31]]

^<<v10-13-31,31>>^ Em vista disso, o rei levantou-se, rasgou as suas roupas e atirou-se para o chão. E todos os servos que estavam com ele também rasgaram as suas roupas.

[[v10-13-32]]

^<<v10-13-32,32>>^ No entanto, Jonadabe, filho de Simeia, irmão de David, disse: “Não pense, meu senhor, que todos os jovens, os filhos do rei, foram mortos, pois foi apenas Amnom que morreu. Isso aconteceu por ordem de Absalão, que tinha decidido fazer isso desde o dia em que Amnom humilhou a irmã dele, Tamar.

[[v10-13-33]]

^<<v10-13-33,33>>^ Portanto, meu senhor, o rei, não dê atenção à^&#42;1^ informação de que todos os filhos do rei morreram; foi apenas Amnom que morreu.”

[NOTE]
====
. Lit.: “não tome ao seu coração a”.
====

[[v10-13-34]]

^<<v10-13-34,34>>^ Entretanto, Absalão fugiu. Mais tarde, o vigia da cidade viu que muitas pessoas vinham pela estrada atrás dele, perto da montanha.

[[v10-13-35]]

^<<v10-13-35,35>>^ Então, Jonadabe disse ao rei: “Veja! Os filhos do rei voltaram. Aconteceu exatamente o que o seu servo disse.”

[[v10-13-36]]

^<<v10-13-36,36>>^ Assim que ele acabou de falar, entraram os filhos do rei, a chorar em voz alta. O rei e todos os seus servos também choraram muito.

[[v10-13-37]]

^<<v10-13-37,37>>^ Absalão, porém, fugiu para junto de Talmai, filho de Amiúde e rei de Gesur. David chorou a morte do seu filho por muitos dias.

[[v10-13-38]]

^<<v10-13-38,38>>^ Depois de Absalão fugir para Gesur, ficou lá três anos.

[[v10-13-39]]

^<<v10-13-39,39>>^ Por fim, o rei David desejou muito ir ver Absalão, pois já se tinha conformado com a^&#42;1^ morte de Amnom.

[NOTE]
====
. Ou: “tinha encontrado consolo pela”.
====

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]