include::./index.adoc[]

[[v10-24-0]]
=== 2 Samuel, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-24-1]]

^<<v10-24-1,1>>^ A ira de Jeová acendeu-se novamente contra Israel quando David foi instigado a agir contra eles, com as palavras: “Vai, faz um recenseamento de Israel e de Judá.”

[[v10-24-2]]

^<<v10-24-2,2>>^ Portanto, o rei disse a Joabe, o chefe do exército, que estava consigo: “Percorre todas as tribos de Israel, desde Dã até Berseba, e registem o povo, para que eu saiba quantos são.”

[[v10-24-3]]

^<<v10-24-3,3>>^ No entanto, Joabe disse ao rei: “Que Jeová, seu Deus, multiplique cem vezes o povo, e que o meu senhor, o rei, o veja com os seus próprios olhos. Mas porque é que o meu senhor, o rei, quer fazer tal coisa?”

[[v10-24-4]]

^<<v10-24-4,4>>^ Contudo, a palavra do rei prevaleceu sobre a de Joabe e a dos chefes do exército. Portanto, Joabe e os chefes do exército saíram da presença do rei para registar o povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Atravessaram o Jordão e acamparam em Aroer, à direita^&#42;1^ da cidade que fica no meio do vale,^&#42;2^ e foram em direção aos gaditas, e, de lá, a Jazer.

[NOTE]
====
. Ou: “a sul”.
. Ou: “uádi”.
====

[[v10-24-6]]

^<<v10-24-6,6>>^ Depois disso, foram a Gileade e à terra de Tatim-Hodchi; a partir dali, dirigiram-se para Dã-Jaã e foram a Sídon.

[[v10-24-7]]

^<<v10-24-7,7>>^ Foram então à fortaleza de Tiro e a todas as cidades dos heveus e dos cananeus, e, por fim, chegaram a Berseba, que fica no Neguebe de Judá.

[[v10-24-8]]

^<<v10-24-8,8>>^ Percorreram, assim, todo o país e voltaram a Jerusalém depois de nove meses e vinte dias.

[[v10-24-9]]

^<<v10-24-9,9>>^ Por conseguinte, Joabe entregou ao rei o número dos que foram registados: Israel tinha 800 000 guerreiros armados com espadas; e Judá, 500 000 homens.

[[v10-24-10]]

^<<v10-24-10,10>>^ Todavia, o coração^&#42;1^ de David encheu-se de remorsos depois de ter mandado contar o povo. David disse então a Jeová: “Cometi um pecado grave ao fazer isto. E agora, Jeová, por favor, perdoa o pecado do teu servo, pois agi de modo muito insensato.”

[NOTE]
====
. Ou: “a consciência”.
====

[[v10-24-11]]

^<<v10-24-11,11>>^ Quando David se levantou de manhã, o profeta Gade, vidente^&#42;1^ de David, recebeu a seguinte mensagem de Jeová:

[NOTE]
====
. Veja o Glossário.
====

[[v10-24-12]]

^<<v10-24-12,12>>^ “Vai e diz a David: ‘Assim diz Jeová: “Dou-te três opções. Escolhe qual delas é que devo executar contra ti.”’”

[[v10-24-13]]

^<<v10-24-13,13>>^ Então, Gade compareceu perante David e perguntou-lhe: “O que é que prefere? Sete anos de fome no seu país? Passar três meses a fugir dos seus inimigos, enquanto o perseguem? Ou três dias de peste no seu país? Agora, pense bem e diga-me que resposta devo dar Àquele que me enviou.”

[[v10-24-14]]

^<<v10-24-14,14>>^ De seguida, David disse a Gade: “Isso é muito aflitivo para mim. Que nós caiamos nas mãos de Jeová, pois a Sua misericórdia é grande, mas que eu não caia nas mãos dos homens.”

[[v10-24-15]]

^<<v10-24-15,15>>^ Portanto, Jeová enviou uma peste sobre Israel, desde a manhã até ao tempo determinado, de modo que 70 000 pessoas morreram, de Dã a Berseba.

[[v10-24-16]]

^<<v10-24-16,16>>^ Quando o anjo estendeu a mão para destruir Jerusalém, Jeová lamentou a^&#42;1^ calamidade e disse ao anjo que causava a destruição entre o povo: “Já chega! Abaixa a mão.” O anjo de Jeová estava perto da eira de Araúna, o jebuseu.

[NOTE]
====
. Ou: “sentiu pesar por causa da”.
====

[[v10-24-17]]

^<<v10-24-17,17>>^ Ao ver o anjo que golpeava o povo, David disse a Jeová: “Fui eu que pequei, eu é que cometi este erro. Mas o que é que estas ovelhas fizeram? Por favor, que a tua mão venha sobre mim e sobre a casa do meu pai.”

[[v10-24-18]]

^<<v10-24-18,18>>^ Naquele mesmo dia, Gade compareceu perante David e disse-lhe: “Sobe à eira de Araúna, o jebuseu, e constrói lá um altar a Jeová.”

[[v10-24-19]]

^<<v10-24-19,19>>^ Portanto, David agiu segundo a palavra de Gade, conforme Jeová tinha ordenado.

[[v10-24-20]]

^<<v10-24-20,20>>^ Quando Araúna viu o rei e os seus servos a virem na sua direção, Araúna saiu imediatamente e curvou-se diante do rei com o rosto por terra.

[[v10-24-21]]

^<<v10-24-21,21>>^ Araúna perguntou: “Porque veio o meu senhor, o rei, até ao seu servo?” David respondeu: “Vim comprar a tua eira, a fim de construir aqui um altar a Jeová, para que cesse o flagelo sobre o povo.”

[[v10-24-22]]

^<<v10-24-22,22>>^ Porém, Araúna disse a David: “Fique com ela, meu senhor, o rei, e ofereça o que quiser.^&#42;1^ Aqui estão os bois para a oferta queimada, bem como o trenó de debulha e o jugo dos bois, para servir de lenha.

[NOTE]
====
. Lit.: “o que for bom aos seus olhos”.
====

[[v10-24-23]]

^<<v10-24-23,23>>^ Dou^&#42;1^ tudo isto ao senhor, ó rei.” E Araúna disse ao rei: “Que Jeová, seu Deus, lhe mostre favor.”

[NOTE]
====
. Lit.: “Araúna dá”.
====

[[v10-24-24]]

^<<v10-24-24,24>>^ No entanto, o rei disse a Araúna: “Não, de maneira nenhuma! Eu compro-a. Não oferecerei a Jeová, meu Deus, sacrifícios queimados que não me custem nada.” Assim, David comprou a eira e os bois por 50 siclos^&#42;1^ de prata.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v10-24-25]]

^<<v10-24-25,25>>^ David construiu ali um altar a Jeová e ofereceu sacrifícios queimados e sacrifícios de participação em comum. Então, Jeová ouviu as súplicas a favor do país e o flagelo sobre Israel cessou.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]