include::./index.adoc[]

[[v10-20-0]]
=== 2 Samuel, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-20-1]]

^<<v10-20-1,1>>^ Havia ali um homem desordeiro chamado Seba, filho de Bicri, um benjaminita. Ele tocou a buzina e disse: “Não partilhamos nada com David, nenhuma herança com o filho de Jessé. Voltem todos aos seus deuses,^&#42;1^ ó Israel!”

[NOTE]
====
. Ou, possivelmente: “às suas tendas”.
====

[[v10-20-2]]

^<<v10-20-2,2>>^ Em vista disso, todos os homens de Israel deixaram de seguir David para seguir Seba, filho de Bicri, mas os homens de Judá, desde o Jordão até Jerusalém, permaneceram com o seu rei.

[[v10-20-3]]

^<<v10-20-3,3>>^ Quando chegou à sua casa^&#42;1^ em Jerusalém, o rei David colocou numa casa à parte, sob guarda, as dez concubinas que tinha deixado a tomar conta da sua casa. Ele providenciou-lhes alimento, mas não voltou a ter relações com elas. Elas continuaram confinadas até ao dia da sua morte, vivendo como viúvas, embora tivessem marido.

[NOTE]
====
. Ou: “ao seu palácio”.
====

[[v10-20-4]]

^<<v10-20-4,4>>^ O rei disse então a Amasa: “Convoca os homens de Judá e apresenta-te aqui com eles dentro de três dias.”

[[v10-20-5]]

^<<v10-20-5,5>>^ Portanto, Amasa foi convocar Judá, mas não voltou no prazo que lhe tinha sido estabelecido.

[[v10-20-6]]

^<<v10-20-6,6>>^ Então, David disse a Abisai: “É possível que Seba, filho de Bicri, nos prejudique mais do que Absalão. Leva os meus servos^&#42;1^ e vai atrás dele, para que não encontre cidades fortificadas e nos escape.”

[NOTE]
====
. Lit.: “os servos do teu senhor”.
====

[[v10-20-7]]

^<<v10-20-7,7>>^ Assim, os homens de Joabe, os queretitas, os peletitas e todos os homens valentes saíram com ele de Jerusalém e foram atrás de Seba, filho de Bicri.

[[v10-20-8]]

^<<v10-20-8,8>>^ Quando se aproximaram da pedra grande em Gibeão, Amasa veio ao seu encontro. Joabe estava a usar o seu traje militar e tinha uma espada na bainha, presa à cintura. Quando ele se aproximou de Amasa, a espada caiu.

[[v10-20-9]]

^<<v10-20-9,9>>^ Joabe disse a Amasa: “Está tudo bem contigo, meu irmão?” Então, com a mão direita, Joabe agarrou a barba de Amasa, como se fosse beijá-lo.

[[v10-20-10]]

^<<v10-20-10,10>>^ Amasa não se preveniu contra a espada na mão de Joabe, de modo que Joabe o golpeou no abdómen, derramando os seus intestinos no chão. Não foi necessário um segundo golpe, dado que um bastou para matá-lo. De seguida, Joabe e o seu irmão Abisai foram atrás de Seba, filho de Bicri.

[[v10-20-11]]

^<<v10-20-11,11>>^ Um dos jovens que estavam com Joabe ficou ao lado do corpo de Amasa e dizia: “Quem estiver do lado de Joabe e apoiar David siga Joabe!”

[[v10-20-12]]

^<<v10-20-12,12>>^ Entretanto, Amasa ainda se revolvia no sangue, no meio da estrada. Quando o homem viu que todos paravam ali, removeu o corpo de Amasa da estrada para o campo. Depois, cobriu-o com um manto, pois viu que todos os que se aproximavam dele paravam.

[[v10-20-13]]

^<<v10-20-13,13>>^ Depois de o corpo ter sido retirado da estrada, todos os homens seguiram Joabe na perseguição a Seba, filho de Bicri.

[[v10-20-14]]

^<<v10-20-14,14>>^ Seba passou por todas as tribos de Israel e foi a Abel de Bete-Maacá. Os bicritas reuniram-se e seguiram-no para dentro da cidade.

[[v10-20-15]]

^<<v10-20-15,15>>^ Joabe e os seus homens^&#42;1^ vieram e cercaram-no em Abel de Bete-Maacá. Fizeram uma rampa para atacar a cidade, visto que esta ficava dentro de uma fortificação. E todos os homens que estavam com Joabe cavaram por baixo da muralha, a fim de derrubá-la.

[NOTE]
====
. Lit.: “Eles”.
====

[[v10-20-16]]

^<<v10-20-16,16>>^ Nisto, uma mulher sábia gritou da cidade: “Ouçam, homens, ouçam! Por favor, digam a Joabe que venha até aqui para que eu fale com ele.”

[[v10-20-17]]

^<<v10-20-17,17>>^ Quando ele se aproximou, a mulher perguntou-lhe: “O senhor é que é Joabe?” Ele respondeu: “Sou.” Ela disse-lhe: “Ouça as palavras da sua serva.” “Estou a ouvir”, disse ele.

[[v10-20-18]]

^<<v10-20-18,18>>^ Ela continuou: “No passado, costumava-se dizer: ‘Peçam conselhos em Abel e a questão será resolvida.’

[[v10-20-19]]

^<<v10-20-19,19>>^ Eu represento os pacíficos e fiéis de Israel. Está a tentar destruir uma cidade que é como uma mãe em Israel. Porque é que quer arruinar^&#42;1^ a herança de Jeová?”

[NOTE]
====
. Lit.: “engolir”.
====

[[v10-20-20]]

^<<v10-20-20,20>>^ Joabe respondeu: “Eu nunca arruinaria e destruiria esta cidade!

[[v10-20-21]]

^<<v10-20-21,21>>^ A questão não é essa. Acontece que um homem chamado Seba, filho de Bicri, da região montanhosa de Efraim, rebelou-se^&#42;1^ contra o rei David. Se me entregarem esse homem, eu retiro-me da cidade.” A mulher disse então a Joabe: “A cabeça dele ser-lhe-á atirada por cima da muralha!”

[NOTE]
====
. Lit.: “levantou a sua mão”.
====

[[v10-20-22]]

^<<v10-20-22,22>>^ Imediatamente, a mulher sábia foi falar com todo o povo. Em consequência disso, eles cortaram a cabeça a Seba, filho de Bicri, e lançaram-na a Joabe. Em vista disso, ele tocou a buzina e os homens deixaram a cidade, voltando cada um para a sua casa; e Joabe voltou a Jerusalém, ao rei.

[[v10-20-23]]

^<<v10-20-23,23>>^ Joabe comandava todo o exército de Israel; Benaia, filho de Jeoiada, comandava os queretitas e os peletitas.

[[v10-20-24]]

^<<v10-20-24,24>>^ Adorão era o responsável pelos convocados para trabalho obrigatório; Jeosafá, filho de Ailude, era o cronista.

[[v10-20-25]]

^<<v10-20-25,25>>^ Seva era o secretário; Zadoque e Abiatar eram sacerdotes.

[[v10-20-26]]

^<<v10-20-26,26>>^ E Ira, o jairita, também se tornou um dos ministros principais^&#42;1^ de David.

[NOTE]
====
. Lit.: “se tornou um sacerdote”.
====

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]