include::./index.adoc[]

[[v10-12-0]]
=== 2 Samuel, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-12-1]]

^<<v10-12-1,1>>^ Então, Jeová enviou Natã a David. Natã foi ter com ele e disse-lhe: “Havia dois homens que moravam na mesma cidade; um era rico e o outro era pobre.

[[v10-12-2]]

^<<v10-12-2,2>>^ O homem rico tinha uma grande quantidade de ovelhas e bois,

[[v10-12-3]]

^<<v10-12-3,3>>^ mas o homem pobre tinha apenas uma cordeirinha que tinha comprado. Ele cuidava dela, e ela cresceu com ele e com os seus filhos. Ela comia do pouco alimento que ele tinha, bebia do seu copo e dormia nos seus braços. Ela tornou-se como uma filha para ele.

[[v10-12-4]]

^<<v10-12-4,4>>^ Certo dia, o homem rico recebeu um visitante, mas não quis abater nenhuma das suas ovelhas ou bois para preparar uma refeição para o viajante que tinha vindo até ele. Em vez disso, tirou a cordeira ao homem pobre e preparou-a para o visitante.”

[[v10-12-5]]

^<<v10-12-5,5>>^ Nisto, David ficou furioso com o homem e disse a Natã: “Tão certo como Jeová vive, o homem que fez isso merece morrer!

[[v10-12-6]]

^<<v10-12-6,6>>^ E ele deve pagar quatro vezes o valor da cordeira, porque fez isso e não teve compaixão.”

[[v10-12-7]]

^<<v10-12-7,7>>^ Então, Natã disse a David: “Esse homem é o senhor! Assim diz Jeová, o Deus de Israel: ‘Eu próprio te ungi rei sobre Israel e livrei-te das mãos de Saul.

[[v10-12-8]]

^<<v10-12-8,8>>^ Eu estava disposto a dar-te a casa do teu senhor e a pôr as suas esposas nos teus braços, e dei-te a casa de Israel e de Judá. E, como se isso não bastasse, eu estava disposto a fazer muito mais por ti.

[[v10-12-9]]

^<<v10-12-9,9>>^ Porque é que desprezaste a palavra de Jeová, fazendo o que é mau aos seus olhos? Mataste Urias, o hitita, com a espada! E, depois de o teres matado com a espada dos amonitas, casaste-te com a esposa dele.

[[v10-12-10]]

^<<v10-12-10,10>>^ Portanto, a espada nunca se afastará da tua casa, porque me desprezaste, ao te apoderares da esposa de Urias, o hitita, como tua esposa.’

[[v10-12-11]]

^<<v10-12-11,11>>^ Assim diz Jeová: ‘Trarei sobre ti uma calamidade vinda da tua própria casa. Vou tomar as tuas esposas diante dos teus olhos e dá-las a outro homem,^&#42;1^ e ele há de deitar-se com elas em plena luz do dia.^&#42;2^

[NOTE]
====
. Ou: “ao teu próximo”.
. Lit.: “aos olhos deste sol”.
====

[[v10-12-12]]

^<<v10-12-12,12>>^ Agiste às escondidas, mas eu vou fazer isto perante todo o Israel e em plena luz do dia.’”^&#42;1^

[NOTE]
====
. Lit.: “e diante do sol”.
====

[[v10-12-13]]

^<<v10-12-13,13>>^ David disse então a Natã: “Pequei contra Jeová.” Natã disse a David em resposta: “Jeová perdoa o seu pecado;^&#42;1^ o senhor não morrerá.

[NOTE]
====
. Ou: “deixa passar o seu pecado”.
====

[[v10-12-14]]

^<<v10-12-14,14>>^ Mas, visto que mostrou tanto desrespeito por Jeová neste assunto, o seu filho que acabou de nascer certamente morrerá.”

[[v10-12-15]]

^<<v10-12-15,15>>^ Depois, Natã foi para casa.
E Jeová atingiu o filho que a esposa de Urias tinha dado a David, e ele ficou doente.

[[v10-12-16]]

^<<v10-12-16,16>>^ David suplicou ao verdadeiro Deus a favor do menino e fez um jejum rigoroso. David entrava no seu quarto e passava a noite deitado no chão.

[[v10-12-17]]

^<<v10-12-17,17>>^ Os anciãos da sua casa ficavam ao pé dele e tentavam fazê-lo levantar-se do chão, mas ele recusava-se e não queria comer com eles.

[[v10-12-18]]

^<<v10-12-18,18>>^ No sétimo dia, o menino morreu. No entanto, os servos de David ficaram com medo de lhe contar que o menino tinha morrido. Eles disseram: “Enquanto o menino estava vivo, nós falámos com o rei, mas ele não nos deu ouvidos. Assim sendo, como é que lhe podemos contar que o menino morreu? Ele pode cometer uma loucura.”

[[v10-12-19]]

^<<v10-12-19,19>>^ Quando David viu os seus servos a cochichar entre si, percebeu que o menino tinha morrido. David perguntou aos seus servos: “O menino morreu?” Eles responderam: “Morreu.”

[[v10-12-20]]

^<<v10-12-20,20>>^ Por conseguinte, David levantou-se do chão, tomou banho, pôs óleo perfumado no corpo e trocou de roupa. De seguida, foi à casa de Jeová e prostrou-se. Depois, voltou para casa,^&#42;1^ pediu que lhe trouxessem algo para comer, e comeu.

[NOTE]
====
. Ou: “o palácio”.
====

[[v10-12-21]]

^<<v10-12-21,21>>^ Os seus servos perguntaram-lhe: “O que significa isto? Enquanto o menino estava vivo, o senhor jejuou e chorou; mas, assim que o menino morreu, o senhor levantou-se e comeu.”

[[v10-12-22]]

^<<v10-12-22,22>>^ Ele respondeu: “Enquanto o menino estava vivo, eu jejuei e chorei, pois pensava: ‘Quem sabe se Jeová me vai mostrar favor e deixar o menino viver?’

[[v10-12-23]]

^<<v10-12-23,23>>^ Mas agora que ele morreu, porquê jejuar? Será que posso trazê-lo de volta? Eu vou juntar-me a ele, mas ele não voltará a mim.”

[[v10-12-24]]

^<<v10-12-24,24>>^ Então, David consolou a sua esposa Bate-Seba. Ele deitou-se com ela, e eles tiveram relações. Com o tempo, ela deu-lhe um filho, que recebeu o nome de Salomão.^&#42;1^ Jeová amava-o,

[NOTE]
====
. Derivado de uma palavra hebraica que significa “paz”.
====

[[v10-12-25]]

^<<v10-12-25,25>>^ e, por meio de Natã, o profeta, disse que deviam chamar-lhe Jedidias,^&#42;1^ dado que Jeová o amava.^&#42;2^

[NOTE]
====
. Que significa “amado de Jah”.
. Ou: “por causa de Jeová”.
====

[[v10-12-26]]

^<<v10-12-26,26>>^ Joabe continuou a lutar contra Rabá dos amonitas e apoderou-se da cidade real.^&#42;1^

[NOTE]
====
. Ou: “da cidade do reino”.
====

[[v10-12-27]]

^<<v10-12-27,27>>^ Portanto, Joabe enviou mensageiros a David e disse-lhe: “Lutei contra Rabá e apoderei-me da cidade das águas.^&#42;1^

[NOTE]
====
. Possivelmente, refere-se aos recursos hídricos da cidade.
====

[[v10-12-28]]

^<<v10-12-28,28>>^ Agora, reúne o restante dos soldados, cerca a cidade e captura-a, para que não seja eu a capturá-la e a receber o crédito por isso.”^&#42;1^

[NOTE]
====
. Lit.: “e o meu nome seja invocado sobre ela”.
====

[[v10-12-29]]

^<<v10-12-29,29>>^ Portanto, David reuniu todos os soldados e foi a Rabá, lutou contra ela e capturou-a.

[[v10-12-30]]

^<<v10-12-30,30>>^ Então, ele retirou a coroa da cabeça de Malcã.^&#42;1^ Ela pesava um talento^&#42;2^ de ouro, juntamente com as pedras preciosas, e foi colocada na cabeça de David. Ele também levou uma grande quantidade do despojo da cidade.

[NOTE]
====
. Possivelmente um deus-ídolo dos amonitas; noutro lugar, também chamado Moloque ou Milcom.
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v10-12-31]]

^<<v10-12-31,31>>^ Capturou as pessoas que lá estavam e colocou-as a serrar pedras, a trabalhar com ferramentas de ferro afiadas e com machados de ferro, e a fabricar tijolos. Ele fez isso com todas as cidades dos amonitas. Por fim, David e todos os soldados voltaram para Jerusalém.

'''

xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[&#60; Capítulo Anterior] | <<v10-12-0,Topo>> | xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[Próximo Capítulo &#62;]