include::./index.adoc[]

[[v10-15-0]]
=== 2 Samuel, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-15-1]]

^<<v10-15-1,1>>^ Depois disso, Absalão providenciou um carro com cavalos e 50 homens para correr à sua frente.

[[v10-15-2]]

^<<v10-15-2,2>>^ Absalão levantava-se cedo e ficava ao lado da estrada que dá para o portão da cidade. Sempre que alguém tinha uma causa para apresentar ao rei para julgamento, Absalão chamava-o e perguntava-lhe: “De que cidade é que tu és?” Ele respondia: “O seu servo é de uma das tribos de Israel.”

[[v10-15-3]]

^<<v10-15-3,3>>^ Absalão dizia-lhe: “Olha, a tua solicitação é justa e legítima, mas não há ninguém da parte do rei para ouvir a tua causa.”

[[v10-15-4]]

^<<v10-15-4,4>>^ Absalão dizia: “Quem me dera ser designado juiz no país! Então, todo aquele que tivesse uma causa ou uma questão judicial poderia vir até mim, e eu trataria de que lhe fosse feita justiça.”

[[v10-15-5]]

^<<v10-15-5,5>>^ E, quando alguém se aproximava para se curvar diante dele, Absalão estendia a mão, segurava-o e beijava-o.

[[v10-15-6]]

^<<v10-15-6,6>>^ Absalão fazia isso com todos os israelitas que vinham até ao rei para pedir justiça; assim, Absalão conquistava a lealdade^&#42;1^ dos homens de Israel.

[NOTE]
====
. Ou: “furtava o coração”.
====

[[v10-15-7]]

^<<v10-15-7,7>>^ Ao fim de quatro anos,^&#42;1^ Absalão disse ao rei: “Por favor, deixe-me ir a Hébron para cumprir o voto que fiz a Jeová.

[NOTE]
====
. Ou, possivelmente: “quarenta anos”.
====

[[v10-15-8]]

^<<v10-15-8,8>>^ Pois o seu servo fez o seguinte voto solene quando morava em Gesur, na Síria: ‘Se Jeová me deixar voltar a Jerusalém, eu apresentarei uma oferta^&#42;1^ a Jeová.’”

[NOTE]
====
. Ou: “adorarei”. Lit.: “prestarei serviço”.
====

[[v10-15-9]]

^<<v10-15-9,9>>^ O rei disse-lhe então: “Vai em paz.” Assim, ele saiu e foi para Hébron.

[[v10-15-10]]

^<<v10-15-10,10>>^ De seguida, Absalão enviou espiões a todas as tribos de Israel para dizer: “Assim que ouvirem o som da buzina, anunciem: ‘Absalão tornou-se rei em Hébron!’”

[[v10-15-11]]

^<<v10-15-11,11>>^ E 200 homens de Jerusalém tinham ido para lá com Absalão. Eles tinham sido convidados e foram sem suspeitar de nada, sem saber o que estava a acontecer.

[[v10-15-12]]

^<<v10-15-12,12>>^ Além disso, quando ofereceu os sacrifícios, Absalão mandou que fossem buscar Aitofel, o gilonita, conselheiro de David, à sua cidade, Gilo. A conspiração foi ganhando força, e o número dos que apoiavam Absalão continuou a aumentar.

[[v10-15-13]]

^<<v10-15-13,13>>^ Então, alguém informou David: “Os homens de Israel passaram para o lado de Absalão.”

[[v10-15-14]]

^<<v10-15-14,14>>^ Imediatamente, David disse a todos os seus servos que estavam com ele em Jerusalém: “Vamos fugir, pois nenhum de nós escapará de Absalão! Apressem-se, senão ele vai alcançar-nos e trazer calamidade sobre nós, golpeando a cidade com a espada!”

[[v10-15-15]]

^<<v10-15-15,15>>^ Os servos do rei disseram: “Aquilo que decidir, ó rei, os seus servos estão dispostos a fazer.”

[[v10-15-16]]

^<<v10-15-16,16>>^ Portanto, o rei saiu acompanhado de todos os da sua casa, mas deixou dez concubinas para tomarem conta da casa.^&#42;1^

[NOTE]
====
. Ou: “do palácio”.
====

[[v10-15-17]]

^<<v10-15-17,17>>^ O rei partiu com todo o povo atrás dele, e pararam em Bete-Meraque.

[[v10-15-18]]

^<<v10-15-18,18>>^ Todos os servos que partiram com ele^&#42;1^ e todos os queretitas, os peletitas e os geteus, 600 homens que o tinham seguido desde Gate, iam passando enquanto o rei os inspecionava.^&#42;2^

[NOTE]
====
. Ou: “atravessaram ao seu lado”.
. Ou: “iam atravessando diante da face do rei”.
====

[[v10-15-19]]

^<<v10-15-19,19>>^ O rei disse então a Itai, o geteu: “Porque é que também vens connosco? Volta e fica com o novo rei, pois és estrangeiro, um exilado da tua terra.

[[v10-15-20]]

^<<v10-15-20,20>>^ Chegaste ontem. Será que, hoje, eu já te deveria fazer vaguear connosco, indo quando eu tiver de ir e para onde eu tiver de ir? Volta e leva os teus irmãos contigo, e que Jeová te demonstre amor leal e fidelidade!”

[[v10-15-21]]

^<<v10-15-21,21>>^ No entanto, Itai disse ao rei: “Tão certo como Jeová vive, e tão certo como o meu senhor, o rei, vive, não importa onde esteja, lá estará também o seu servo, quer seja para morrer, quer seja para viver!”

[[v10-15-22]]

^<<v10-15-22,22>>^ Em vista disso, David disse a Itai: “Então, vai, atravessa.” Assim, Itai, o geteu, atravessou o vale com todos os homens e as crianças que estavam com ele.

[[v10-15-23]]

^<<v10-15-23,23>>^ Todos os que moravam na região choravam em voz alta, enquanto todo o povo fazia a travessia; e o rei estava parado junto ao vale do Cédron. Todo o povo atravessava em direção à estrada que dá para o deserto.

[[v10-15-24]]

^<<v10-15-24,24>>^ Zadoque também estava lá com todos os levitas, levando a Arca do Pacto do verdadeiro Deus, e eles colocaram a Arca do verdadeiro Deus no chão. E Abiatar chegou enquanto todo o povo saía da cidade e atravessava o vale.

[[v10-15-25]]

^<<v10-15-25,25>>^ Contudo, o rei disse a Zadoque: “Leva a Arca do verdadeiro Deus para a cidade. Se eu achar favor aos olhos de Jeová, ele vai fazer-me voltar e deixar-me ver a Arca e o lugar onde ela está.

[[v10-15-26]]

^<<v10-15-26,26>>^ No entanto, se ele disser: ‘Já não me agradas’, então, que ele faça comigo o que for bom aos seus olhos.”

[[v10-15-27]]

^<<v10-15-27,27>>^ O rei disse a Zadoque, o sacerdote: “Tu não és vidente?^&#42;1^ Volta em paz à cidade. Levem convosco os vossos filhos: Aimaás, teu filho, e Jonatã, filho de Abiatar.

[NOTE]
====
. Veja o Glossário.
====

[[v10-15-28]]

^<<v10-15-28,28>>^ Ficarei à espera nos pontos de travessia junto ao deserto, até que me mandem informações.”

[[v10-15-29]]

^<<v10-15-29,29>>^ Portanto, Zadoque e Abiatar levaram a Arca do verdadeiro Deus novamente para Jerusalém e permaneceram lá.

[[v10-15-30]]

^<<v10-15-30,30>>^ Enquanto subia o monte^&#42;1^ das Oliveiras, David chorava ao caminhar; ele estava descalço e com a cabeça coberta. Todos os que estavam com ele também cobriram a cabeça e subiam o monte a chorar.

[NOTE]
====
. Ou: “a subida”.
====

[[v10-15-31]]

^<<v10-15-31,31>>^ Disseram então a David: “Aitofel está entre os que conspiram com Absalão.” David disse: “Ó Jeová, por favor, transforma em tolice o conselho de Aitofel!”

[[v10-15-32]]

^<<v10-15-32,32>>^ Quando David chegou ao cume do monte, onde o povo costumava adorar a^&#42;1^ Deus, Husai, o arquita, estava à espera dele, com a sua veste comprida rasgada e com terra na cabeça.

[NOTE]
====
. Ou: “curvar-se diante de”.
====

[[v10-15-33]]

^<<v10-15-33,33>>^ No entanto, David disse-lhe: “Se fores comigo, serás um peso para mim.

[[v10-15-34]]

^<<v10-15-34,34>>^ Mas, se voltares à cidade e disseres a Absalão: ‘Sou seu servo, ó rei. Fui servo do seu pai no passado, mas agora sou seu servo’, então, poderás frustrar o conselho de Aitofel por mim.

[[v10-15-35]]

^<<v10-15-35,35>>^ Os sacerdotes Zadoque e Abiatar estarão lá contigo. Conta a Zadoque e a Abiatar tudo o que ouvires na casa do rei.

[[v10-15-36]]

^<<v10-15-36,36>>^ Eles e os seus dois filhos, Aimaás, filho de Zadoque, e Jonatã, filho de Abiatar, estão lá. Por meio deles, mandem-me informações sobre tudo o que ouvirem.”

[[v10-15-37]]

^<<v10-15-37,37>>^ Assim, Husai, amigo^&#42;1^ de David, chegou a Jerusalém quando Absalão estava a entrar na cidade.

[NOTE]
====
. Ou: “confidente”.
====

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]