include::./index.adoc[]

[[v10-11-0]]
=== 2 Samuel, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-11-1]]

^<<v10-11-1,1>>^ No início do ano,^&#42;1^ altura em que os reis saem em campanhas militares, David enviou Joabe com os seus servos e todo o exército de Israel para destruir os amonitas, e eles cercaram Rabá. No entanto, David ficou em Jerusalém.

[NOTE]
====
. Isto é, na primavera.
====

[[v10-11-2]]

^<<v10-11-2,2>>^ Certo dia, ao anoitecer,^&#42;1^ David levantou-se da cama e foi passear pelo terraço da casa^&#42;2^ do rei. A partir do terraço, ele viu uma mulher a tomar banho, e a mulher era muito bonita.

[NOTE]
====
. Ou: “no final da tarde”.
. Ou: “do palácio”.
====

[[v10-11-3]]

^<<v10-11-3,3>>^ David mandou alguém descobrir quem era a mulher. Disseram-lhe: “É Bate-Seba, filha de Elião, esposa de Urias, o hitita.”

[[v10-11-4]]

^<<v10-11-4,4>>^ De seguida, David enviou mensageiros para que a trouxessem até ele. Então, ela veio, e ele deitou-se com ela. (Isto aconteceu quando ela estava a purificar-se da sua impureza.^&#42;1^) Depois, ela voltou para casa.

[NOTE]
====
. Possivelmente, a sua impureza menstrual.
====

[[v10-11-5]]

^<<v10-11-5,5>>^ A mulher ficou grávida e mandou dizer a David: “Estou grávida.”

[[v10-11-6]]

^<<v10-11-6,6>>^ Em vista disso, David mandou a seguinte mensagem a Joabe: “Envia-me Urias, o hitita.” Por conseguinte, Joabe enviou Urias a David.

[[v10-11-7]]

^<<v10-11-7,7>>^ Quando Urias chegou, David perguntou-lhe como estava Joabe, como estavam os soldados e como ia a guerra.

[[v10-11-8]]

^<<v10-11-8,8>>^ David disse então a Urias: “Vai para casa e descansa um pouco.”^&#42;1^ Assim que Urias saiu da casa do rei, foi-lhe enviado um presente de cortesia da parte do rei.^&#42;2^

[NOTE]
====
. Lit.: “lava os teus pés”.
. Ou: “a porção do rei”, isto é, a porção enviada pelo anfitrião ao convidado honrado.
====

[[v10-11-9]]

^<<v10-11-9,9>>^ No entanto, Urias não foi para casa, mas dormiu à entrada da casa do rei com todos os outros servos do seu senhor.

[[v10-11-10]]

^<<v10-11-10,10>>^ Então, disseram a David: “Urias não foi para casa.” Em vista disso, David disse a Urias: “Não acabaste de chegar de viagem? Porque é que não foste para casa?”

[[v10-11-11]]

^<<v10-11-11,11>>^ Urias disse a David: “A Arca e os homens de Israel e de Judá estão em abrigos temporários, e o meu chefe Joabe e os servos do meu senhor estão acampados em campo aberto. Como poderia eu ir para casa, comer e beber, e deitar-me com a minha esposa? Tão certo como o senhor vive,^&#42;1^ não farei tal coisa!”

[NOTE]
====
. Ou: “como o senhor vive e a sua alma vive”.
====

[[v10-11-12]]

^<<v10-11-12,12>>^ Seguidamente, David disse a Urias: “Fica aqui por mais um dia e amanhã mando-te de volta.” Assim, Urias ficou em Jerusalém naquele dia e no dia seguinte.

[[v10-11-13]]

^<<v10-11-13,13>>^ David convidou-o para comer e beber com ele, e embriagou-o. Contudo, Urias saiu ao anoitecer para dormir na sua cama, com os servos do seu senhor, mas não foi para casa.

[[v10-11-14]]

^<<v10-11-14,14>>^ De manhã, David escreveu uma carta a Joabe e enviou-a por meio de Urias.

[[v10-11-15]]

^<<v10-11-15,15>>^ Ele escreveu na carta: “Coloquem Urias na linha da frente, onde o combate for mais violento. Depois, recuem e deixem-no sozinho, para que ele seja ferido e morra.”

[[v10-11-16]]

^<<v10-11-16,16>>^ Joabe já tinha estado a observar atentamente a cidade, e colocou Urias onde ele sabia que estavam os guerreiros mais valentes.

[[v10-11-17]]

^<<v10-11-17,17>>^ Quando os homens da cidade saíram e lutaram contra Joabe, alguns dos servos de David foram mortos. Urias, o hitita, estava entre os que morreram.

[[v10-11-18]]

^<<v10-11-18,18>>^ Então, Joabe informou David de tudo o que estava a acontecer na guerra.

[[v10-11-19]]

^<<v10-11-19,19>>^ Ele disse ao mensageiro: “Quando tiveres acabado de dar ao rei todas as notícias da guerra,

[[v10-11-20]]

^<<v10-11-20,20>>^ pode ser que o rei fique furioso e pergunte: ‘Porque é que foram lutar para tão perto da cidade? Não sabiam que eles atacariam do alto da muralha?

[[v10-11-21]]

^<<v10-11-21,21>>^ Quem é que matou Abimeleque, filho de Jerubesete? Não foi uma mulher que atirou uma pedra de moinho do alto da muralha para cima dele, matando-o em Tebes? Porque é que se aproximaram tanto da muralha?’ Nesse caso, diz: ‘O seu servo Urias, o hitita, também morreu.’”

[[v10-11-22]]

^<<v10-11-22,22>>^ Assim, o mensageiro foi e contou a David tudo o que Joabe tinha ordenado.

[[v10-11-23]]

^<<v10-11-23,23>>^ O mensageiro disse a David: “Os inimigos foram mais fortes do que nós e saíram para lutar contra nós em campo aberto. Porém, nós fizemos com que eles recuassem até à entrada do portão da cidade.

[[v10-11-24]]

^<<v10-11-24,24>>^ Então, do alto da muralha, os arqueiros atiraram contra os seus servos, e alguns dos servos do rei morreram. O seu servo Urias, o hitita, também morreu.”

[[v10-11-25]]

^<<v10-11-25,25>>^ David disse então ao mensageiro: “Diz o seguinte a Joabe: ‘Não te preocupes com isso, pois a espada devora qualquer um. Intensifica o ataque contra a cidade e conquista-a.’ Além disso, encoraja-o.”

[[v10-11-26]]

^<<v10-11-26,26>>^ Quando a esposa de Urias soube que o seu marido tinha morrido, começou a chorar por ele.

[[v10-11-27]]

^<<v10-11-27,27>>^ Assim que terminou o período de luto, David mandou trazê-la para a sua casa; ela tornou-se sua esposa e deu-lhe um filho. No entanto, o que David tinha feito desagradou muito a^&#42;1^ Jeová.

[NOTE]
====
. Lit.: “era mau aos olhos de”.
====

'''

xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]