include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-6-1]]

^<<v10-6-1,1>>^ David reuniu novamente todos os melhores soldados de Israel, 30 000 homens.

[[v10-6-2]]

^<<v10-6-2,2>>^ Então, David e todos os homens que estavam com ele foram a Baal-Judá buscar a Arca do verdadeiro Deus, diante da qual se invoca o nome de Jeová dos exércitos, que está sentado no seu trono acima dos^&#42;1^ querubins.

[NOTE]
====
. Ou, possivelmente: “entre os”.
====

[[v10-6-3]]

^<<v10-6-3,3>>^ No entanto, eles colocaram a Arca do verdadeiro Deus numa carroça nova a fim de levá-la da casa de Abinadabe, que ficava na colina. Uzá e Aiô, filhos de Abinadabe, conduziam a carroça.

[[v10-6-4]]

^<<v10-6-4,4>>^ Assim, eles levaram a Arca do verdadeiro Deus da casa de Abinadabe, que ficava na colina. Aiô caminhava à frente da Arca.

[[v10-6-5]]

^<<v10-6-5,5>>^ David e toda a casa de Israel festejavam perante Jeová com todo o tipo de instrumentos de madeira de junípero, com harpas e outros instrumentos de cordas, com pandeiretas, com chocalhos e com címbalos.

[[v10-6-6]]

^<<v10-6-6,6>>^ Contudo, quando chegaram à eira de Nacom, Uzá estendeu a mão e segurou a Arca do verdadeiro Deus, pois os bois quase a derrubaram.

[[v10-6-7]]

^<<v10-6-7,7>>^ Então, a ira de Jeová acendeu-se contra Uzá, e o verdadeiro Deus executou-o ali mesmo pelo seu ato irreverente, e ele morreu ali, ao lado da Arca do verdadeiro Deus.

[[v10-6-8]]

^<<v10-6-8,8>>^ No entanto, David ficou indignado^&#42;1^ porque a ira de Jeová tinha irrompido contra Uzá. E, até hoje, chamam Peres-Uzá^&#42;2^ àquele lugar.

[NOTE]
====
. Ou: “aborrecido”.
. Que significa “brecha contra Uzá”.
====

[[v10-6-9]]

^<<v10-6-9,9>>^ Naquele dia, David ficou com medo de Jeová e disse: “Como é que poderei levar a Arca de Jeová para a minha cidade?”

[[v10-6-10]]

^<<v10-6-10,10>>^ David já não quis levar a Arca de Jeová para onde ele estava, na Cidade de David. Em vez disso, David ordenou que a levassem para a casa de Obede-Edom, o geteu.

[[v10-6-11]]

^<<v10-6-11,11>>^ A Arca de Jeová ficou durante três meses na casa de Obede-Edom, o geteu. Jeová abençoava Obede-Edom e todos os da sua casa.

[[v10-6-12]]

^<<v10-6-12,12>>^ Relatou-se ao rei David: “Jeová abençoou a casa de Obede-Edom e tudo o que lhe pertence por causa da Arca do verdadeiro Deus.” Então, David, com alegria, foi à casa de Obede-Edom buscar a Arca do verdadeiro Deus, a fim de levá-la para a Cidade de David.

[[v10-6-13]]

^<<v10-6-13,13>>^ Quando os que carregavam a Arca de Jeová tinham dado seis passos, ele sacrificou um touro e um bezerro gordo.^&#42;1^

[NOTE]
====
. Ou: “animal cevado”.
====

[[v10-6-14]]

^<<v10-6-14,14>>^ David estava a dançar perante Jeová com todas as suas forças; e David usava^&#42;1^ um éfode de linho.

[NOTE]
====
. Lit.: “estava cingido com”.
====

[[v10-6-15]]

^<<v10-6-15,15>>^ David e toda a casa de Israel levavam a Arca de Jeová com gritos de alegria e ao som da buzina.

[[v10-6-16]]

^<<v10-6-16,16>>^ Todavia, quando a Arca de Jeová chegou à Cidade de David, Mical, filha de Saul, olhou pela janela e viu o rei David a saltar e a dançar perante Jeová; e ela começou a desprezá-lo no coração.

[[v10-6-17]]

^<<v10-6-17,17>>^ Então, levaram a Arca de Jeová para a tenda que David tinha armado para ela e colocaram-na no seu lugar. Depois, David fez ofertas queimadas e sacrifícios de participação em comum perante Jeová.

[[v10-6-18]]

^<<v10-6-18,18>>^ Quando David acabou de fazer as ofertas queimadas e os sacrifícios de participação em comum, abençoou o povo em nome de Jeová dos exércitos.

[[v10-6-19]]

^<<v10-6-19,19>>^ Além disso, ele distribuiu a todo o povo, a toda a multidão de Israel, a cada homem e a cada mulher, um pão em forma de anel, um bolo de tâmaras e um bolo de passas. Depois, todo o povo partiu, cada um para a sua casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ Quando David voltou para abençoar os da sua casa, Mical, filha de Saul, foi ao seu encontro. Ela disse: “Como se fez glorioso o rei de Israel, no dia de hoje, despindo-se aos olhos das escravas dos seus servos, assim como faz um tolo!”

[[v10-6-21]]

^<<v10-6-21,21>>^ Então, David disse a Mical: “Eu estava a festejar perante Jeová, que me escolheu a mim em vez do teu pai e de todos os da sua casa, e que me designou líder do povo de Jeová, Israel. Por isso, vou festejar perante Jeová,

[[v10-6-22]]

^<<v10-6-22,22>>^ e vou humilhar-me ainda mais e serei rebaixado até mesmo aos meus próprios olhos. Contudo, eu serei glorificado pelas escravas que mencionaste.”

[[v10-6-23]]

^<<v10-6-23,23>>^ Assim, Mical, filha de Saul, não teve nenhum filho até ao dia da sua morte.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]