include::./index.adoc[]

[[v10-19-0]]
=== 2 Samuel, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-19-1]]

^<<v10-19-1,1>>^ Joabe foi informado: “O rei chora e lamenta-se por causa de Absalão.”

[[v10-19-2]]

^<<v10-19-2,2>>^ Por conseguinte, naquele dia, a vitória^&#42;1^ transformou-se em luto para todo o povo, porque souberam que o rei estava a sofrer por causa do seu filho.

[NOTE]
====
. Ou: “salvação”.
====

[[v10-19-3]]

^<<v10-19-3,3>>^ Naquele dia, os soldados voltaram^&#42;1^ em silêncio para a cidade, assim como um exército que está envergonhado por ter fugido da batalha.

[NOTE]
====
. Ou: “o povo voltou”.
====

[[v10-19-4]]

^<<v10-19-4,4>>^ O rei tinha coberto o rosto e continuava a clamar: “Meu filho Absalão! Absalão, meu filho, meu filho!”

[[v10-19-5]]

^<<v10-19-5,5>>^ Então, Joabe entrou na casa onde estava o rei e disse-lhe: “Está a envergonhar todos os seus homens, que hoje salvaram a sua vida,^&#42;1^ a vida^&#42;2^ dos seus filhos e das suas filhas, das suas esposas e das suas concubinas.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v10-19-6]]

^<<v10-19-6,6>>^ O senhor ama os que o odeiam e odeia os que o amam, pois hoje deixou claro que os chefes e os servos que lhe pertencem não significam nada para si. Pois tenho a certeza de que, se Absalão tivesse sido o único a permanecer vivo no dia de hoje e todos nós estivéssemos mortos, estaria tudo bem para si.

[[v10-19-7]]

^<<v10-19-7,7>>^ Agora, levante-se, saia e encoraje os^&#42;1^ seus servos, porque juro por Jeová que, se não o fizer, ninguém ficará consigo esta noite. Isso será pior do que todo o mal que lhe aconteceu desde a sua juventude até agora.”

[NOTE]
====
. Lit.: “fale ao coração dos”.
====

[[v10-19-8]]

^<<v10-19-8,8>>^ Assim, o rei levantou-se e sentou-se no portão da cidade, e todo o povo foi informado: “O rei está sentado no portão.” De seguida, todo o povo compareceu perante o rei.
Porém, os homens de Israel tinham fugido, cada um para a sua casa.

[[v10-19-9]]

^<<v10-19-9,9>>^ Todo o povo, em todas as tribos de Israel, discutia entre si e comentava: “O rei salvou-nos dos nossos inimigos e livrou-nos dos filisteus, mas fugiu do país por causa de Absalão.

[[v10-19-10]]

^<<v10-19-10,10>>^ E Absalão, a quem ungimos rei sobre nós, morreu na batalha. Portanto, porque é que não fazem nada para que o rei volte?”

[[v10-19-11]]

^<<v10-19-11,11>>^ O rei David mandou a seguinte mensagem aos sacerdotes Zadoque e Abiatar: “Digam aos anciãos de Judá: ‘Porque é que haviam de ser os últimos a providenciar o regresso do rei a casa, ao passo que os comentários de todo o Israel já chegaram até onde mora o rei ?

[[v10-19-12]]

^<<v10-19-12,12>>^ Vocês são meus irmãos, somos do mesmo sangue.^&#42;1^ Porque é que haviam de ser os últimos a providenciar o regresso do rei?’

[NOTE]
====
. Lit.: “são o meu osso e a minha carne”.
====

[[v10-19-13]]

^<<v10-19-13,13>>^ Devem dizer a Amasa: ‘Não somos do mesmo sangue?^&#42;1^ Que Deus me castigue, e que o faça severamente, se doravante não te tornares o chefe do meu exército no lugar de Joabe.’”

[NOTE]
====
. Lit.: “Vocês não são o meu osso e a minha carne?”
====

[[v10-19-14]]

^<<v10-19-14,14>>^ Assim, o rei David ganhou^&#42;1^ o coração de todos os homens de Judá, sem exceção, e eles mandaram dizer-lhe: “Volte, com todos os seus servos.”

[NOTE]
====
. Lit.: “inclinou”.
====

[[v10-19-15]]

^<<v10-19-15,15>>^ O rei voltou e chegou ao Jordão, e os homens de Judá chegaram a Gilgal para se encontrarem com o rei, a fim de o acompanharem na travessia do Jordão.

[[v10-19-16]]

^<<v10-19-16,16>>^ Então, Simei, filho de Gera, benjaminita de Baurim, foi rapidamente com os homens de Judá ao encontro do rei David,

[[v10-19-17]]

^<<v10-19-17,17>>^ e com ele estavam 1000 homens de Benjamim. Ziba, ajudante da casa de Saul, com os seus 15 filhos e 20 servos, também foi depressa ao Jordão e chegou lá antes do rei.

[[v10-19-18]]

^<<v10-19-18,18>>^ Ele atravessou^&#42;1^ o rio no seu ponto de travessia para trazer os da casa do rei e fazer tudo o que o rei quisesse. Contudo, quando o rei estava prestes a atravessar o Jordão, Simei, filho de Gera, prostrou-se diante dele.

[NOTE]
====
. Ou, possivelmente: “Eles atravessaram”.
====

[[v10-19-19]]

^<<v10-19-19,19>>^ Ele disse ao rei: “Que o senhor não me considere culpado e não se lembre do mal que o seu servo lhe fez no dia em que o meu senhor, o rei, saiu de Jerusalém. Que o rei não leve isso em conta,

[[v10-19-20]]

^<<v10-19-20,20>>^ pois o seu servo reconhece que pecou. Por isso, hoje, sou o primeiro de toda a casa de José a vir ao encontro do meu senhor, o rei.”

[[v10-19-21]]

^<<v10-19-21,21>>^ Imediatamente, Abisai, filho de Zeruia, disse: “Não deveria Simei ser morto por ter amaldiçoado o ungido de Jeová?”

[[v10-19-22]]

^<<v10-19-22,22>>^ No entanto, David disse: “O que é que têm a ver com isso, filhos de Zeruia? Porque é que agem contra mim? Será que alguém deve ser morto hoje em Israel? Por acaso, não sei eu que, hoje, voltei a ser o rei de Israel?”

[[v10-19-23]]

^<<v10-19-23,23>>^ De seguida, o rei disse a Simei: “Não morrerás.” E o rei confirmou-o com um juramento.

[[v10-19-24]]

^<<v10-19-24,24>>^ Mefibosete, neto de Saul, também foi ao encontro do rei. Ele não tinha cuidado dos pés, nem aparado o bigode, nem lavado as suas roupas, desde o dia em que o rei se tinha ido embora até ao dia em que voltou em paz.

[[v10-19-25]]

^<<v10-19-25,25>>^ Quando chegou a^&#42;1^ Jerusalém para se encontrar com o rei, o rei perguntou-lhe: “Porque é que não foste comigo, Mefibosete?”

[NOTE]
====
. Ou, possivelmente: “de”.
====

[[v10-19-26]]

^<<v10-19-26,26>>^ Ele respondeu: “O meu servo enganou-me, meu senhor, o rei. Visto que sou^&#42;1^ aleijado, eu^&#42;2^ disse-lhe: ‘Vou mandar selar a minha jumenta, a fim de montá-la e ir com o rei.’

[NOTE]
====
. Lit.: “o seu servo é”.
. Lit.: “o seu servo”.
====

[[v10-19-27]]

^<<v10-19-27,27>>^ Mas ele caluniou o seu servo diante do meu senhor, o rei. No entanto, o meu senhor, o rei, é como um anjo do verdadeiro Deus. Assim, faça o que achar melhor.

[[v10-19-28]]

^<<v10-19-28,28>>^ Todos os da casa do meu pai poderiam ter sido mortos pelo meu senhor, o rei. Apesar disso, o senhor pôs o seu servo entre os que comem à sua mesa. Portanto, que direito tenho eu de pedir mais alguma coisa ao rei?”

[[v10-19-29]]

^<<v10-19-29,29>>^ Contudo, o rei disse-lhe: “Não digas mais nada. A minha decisão é que tu e Ziba devem dividir o campo.”

[[v10-19-30]]

^<<v10-19-30,30>>^ A seguir, Mefibosete disse ao rei: “Que ele fique com tudo, já que o meu senhor, o rei, voltou em paz para casa.”

[[v10-19-31]]

^<<v10-19-31,31>>^ Barzilai, o gileadita, veio de Rogelim para o Jordão, a fim de acompanhar o rei até ao Jordão.

[[v10-19-32]]

^<<v10-19-32,32>>^ Barzilai era muito idoso; tinha 80 anos de idade. Foi ele que forneceu alimento ao rei enquanto este ficou em Maanaim, pois era um homem muito rico.

[[v10-19-33]]

^<<v10-19-33,33>>^ O rei disse a Barzilai: “Vem comigo e eu vou dar-te o sustento em Jerusalém.”

[[v10-19-34]]

^<<v10-19-34,34>>^ Todavia, Barzilai disse ao rei: “Quantos anos^&#42;1^ de vida ainda me restam, para que eu vá com o rei a Jerusalém?

[NOTE]
====
. Lit.: “dias de anos”.
====

[[v10-19-35]]

^<<v10-19-35,35>>^ Já tenho 80 anos de idade. Será que consigo distinguir o que é bom do que é mau? Pode o seu servo sentir o gosto do que come e do que bebe, ou ainda escutar a voz de cantores e cantoras? Portanto, porque devia o seu servo ser mais um peso para o meu senhor, o rei?

[[v10-19-36]]

^<<v10-19-36,36>>^ O seu servo já fica satisfeito por acompanhar o rei até ao Jordão. Porque deveria o rei recompensar-me dessa maneira?

[[v10-19-37]]

^<<v10-19-37,37>>^ Por favor, deixe o seu servo voltar e deixe-me morrer na minha cidade, perto da sepultura do meu pai e da minha mãe. No entanto, aqui está o seu servo Quimã. Que ele vá com o meu senhor, o rei. Faça por ele o que achar melhor.”

[[v10-19-38]]

^<<v10-19-38,38>>^ Seguidamente, o rei disse: “Quimã irá comigo, e eu farei por ele o que achares melhor. Farei por ti tudo o que me pedires.”

[[v10-19-39]]

^<<v10-19-39,39>>^ Todo o povo começou então a atravessar o Jordão, e, quando o rei estava prestes a atravessar, beijou Barzilai e abençoou-o; e Barzilai voltou para casa.

[[v10-19-40]]

^<<v10-19-40,40>>^ Quando o rei atravessou e foi a Gilgal, Quimã foi com ele. Todos os homens de Judá e metade dos homens de Israel atravessaram com o rei.

[[v10-19-41]]

^<<v10-19-41,41>>^ Então, todos os homens de Israel dirigiram-se ao rei e perguntaram-lhe: “Porque é que os nossos irmãos, os homens de Judá, foram buscá-lo às escondidas, e fizeram com que o rei e os da sua casa, bem como todos os homens de David, atravessassem o Jordão?”

[[v10-19-42]]

^<<v10-19-42,42>>^ Todos os homens de Judá responderam aos homens de Israel: “Fizemos isso porque o rei é nosso parente. Porque é que estão irritados com isso? Será que comemos às custas do rei ou ganhámos algum presente da sua parte?”

[[v10-19-43]]

^<<v10-19-43,43>>^ No entanto, os homens de Israel responderam aos homens de Judá: “Nós temos dez partes no que se refere ao rei.^&#42;1^ Portanto, temos mais direitos em relação a David do que vocês. Então, porque é que nos desprezaram? Não devíamos ter sido os primeiros a trazer o nosso rei?” Contudo, as palavras dos homens de Judá prevaleceram sobre^&#42;2^ as palavras dos homens de Israel.

[NOTE]
====
. Ou: “do reino”.
. Ou: “foram mais duras do que”.
====

'''

xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[&#60; Capítulo Anterior] | <<v10-19-0,Topo>> | xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[Próximo Capítulo &#62;]