include::./index.adoc[]

[[v10-5-0]]
=== 2 Samuel, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v10-5-1]]

^<<v10-5-1,1>>^ Com o tempo, todas as tribos de Israel foram ter com David, em Hébron, e disseram-lhe: “Somos do mesmo sangue.^&#42;1^

[NOTE]
====
. Lit.: “o seu osso e a sua carne”.
====

[[v10-5-2]]

^<<v10-5-2,2>>^ No passado, quando Saul era o nosso rei, era o senhor que liderava Israel nas suas campanhas militares.^&#42;1^ E Jeová disse-lhe: ‘Pastorearás o meu povo Israel e irás tornar-te líder de Israel.’”

[NOTE]
====
. Lit.: “era aquele que fazia sair e aquele que fazia entrar Israel”.
====

[[v10-5-3]]

^<<v10-5-3,3>>^ Assim, todos os anciãos de Israel foram ter com o rei David em Hébron, e o rei David fez um pacto com eles em Hébron, perante Jeová. Depois, ungiram David como rei sobre Israel.

[[v10-5-4]]

^<<v10-5-4,4>>^ David tinha 30 anos de idade quando se tornou rei e reinou por 40 anos.

[[v10-5-5]]

^<<v10-5-5,5>>^ Em Hébron, ele reinou sobre Judá durante sete anos e seis meses, e em Jerusalém reinou durante 33 anos sobre todo o Israel e Judá.

[[v10-5-6]]

^<<v10-5-6,6>>^ E o rei e os seus homens foram a Jerusalém para lutar contra os jebuseus que moravam naquela região. Eles fizeram pouco de David: “Nunca entrarás aqui! Até os cegos e os coxos te vão expulsar.” Eles pensavam: ‘David nunca entrará aqui.’

[[v10-5-7]]

^<<v10-5-7,7>>^ No entanto, David apoderou-se da fortaleza de Sião, que hoje é a Cidade de David.

[[v10-5-8]]

^<<v10-5-8,8>>^ David disse naquele dia: “Os que atacam os jebuseus devem ir pelo túnel de água para golpear os ‘cegos e coxos’, que David^&#42;1^ odeia!” É por isso que se diz: “Os cegos e os coxos nunca entrarão nesta casa.”

[NOTE]
====
. Ou: “que a alma de David”.
====

[[v10-5-9]]

^<<v10-5-9,9>>^ Então, David passou a morar na fortaleza, que recebeu o nome de^&#42;1^ Cidade de David. E David fez construções em todo o seu redor, do Aterro^&#42;2^ para dentro.

[NOTE]
====
. Ou, possivelmente: “e ele chamou-lhe”.
. Ou: “de Milo”. Termo hebraico que significa “encher”.
====

[[v10-5-10]]

^<<v10-5-10,10>>^ Assim, David tornou-se cada vez mais poderoso, e Jeová, o Deus dos exércitos, estava com ele.

[[v10-5-11]]

^<<v10-5-11,11>>^ Hirão, rei de Tiro, enviou mensageiros a David. Ele mandou também madeiras de cedro, carpinteiros e pedreiros para que erguessem os muros, e eles construíram uma casa^&#42;1^ para David.

[NOTE]
====
. Ou: “um palácio”.
====

[[v10-5-12]]

^<<v10-5-12,12>>^ E David percebeu que Jeová o tinha estabelecido firmemente como rei sobre Israel e que tinha exaltado o seu reino por causa do Seu povo Israel.

[[v10-5-13]]

^<<v10-5-13,13>>^ Depois de se ter mudado de Hébron, David tomou mais concubinas e esposas em Jerusalém; e David teve mais filhos e filhas.

[[v10-5-14]]

^<<v10-5-14,14>>^ Estes são os nomes dos seus filhos que nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v10-5-15]]

^<<v10-5-15,15>>^ Ibar, Elisua, Nefegue, Jafia,

[[v10-5-16]]

^<<v10-5-16,16>>^ Elisama, Eliada e Elifelete.

[[v10-5-17]]

^<<v10-5-17,17>>^ Quando os filisteus souberam que David tinha sido ungido rei sobre Israel, todos eles foram à procura de David. Ao saber disso, David foi para o refúgio.

[[v10-5-18]]

^<<v10-5-18,18>>^ Então, os filisteus vieram e espalharam-se pelo vale^&#42;1^ de Refaim.

[NOTE]
====
. Ou: “pela planície”.
====

[[v10-5-19]]

^<<v10-5-19,19>>^ David consultou a Jeová: “Será que devo atacar os filisteus? Será que os vais entregar nas minhas mãos?” Jeová respondeu a David: “Vai, porque certamente entregarei os filisteus nas tuas mãos.”

[[v10-5-20]]

^<<v10-5-20,20>>^ Portanto, David foi a Baal-Perazim e golpeou-os. Por isso, David disse: “Jeová rompeu as fileiras dos meus inimigos diante de mim, como águas que abrem uma brecha.” Foi por isso que deu àquele lugar o nome de Baal-Perazim.^&#42;1^

[NOTE]
====
. Que significa “senhor das brechas”.
====

[[v10-5-21]]

^<<v10-5-21,21>>^ Os filisteus abandonaram lá os seus ídolos, e David e os seus homens levaram-nos embora.

[[v10-5-22]]

^<<v10-5-22,22>>^ Mais tarde, os filisteus vieram novamente e espalharam-se pelo vale^&#42;1^ de Refaim.

[NOTE]
====
. Ou: “pela planície”.
====

[[v10-5-23]]

^<<v10-5-23,23>>^ David consultou a Jeová, que disse: “Não os ataques pela frente. Dá a volta por trás deles e ataca-os em frente aos balsameiros.

[[v10-5-24]]

^<<v10-5-24,24>>^ Quando ouvires o som de marcha nas copas dos balsameiros, age com determinação, pois Jeová terá ido à tua frente para golpear o exército dos filisteus.”

[[v10-5-25]]

^<<v10-5-25,25>>^ Portanto, David fez exatamente como Jeová lhe ordenou, e ele golpeou os filisteus desde Geba até Gezer.

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]