include::./index.adoc[]

[[v30-4-0]]
=== Amós, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v30-4-1]]

^<<v30-4-1,1>>^ “Ouçam esta palavra, ó vacas de Basã,
Que estão no monte de Samaria;
Vocês, as mulheres que exploram^&#42;1^ os humildes e esmagam os pobres,
Que dizem aos vossos maridos:^&#42;2^ ‘Tragam-nos algo para beber!’

[NOTE]
====
. Ou: “defraudam”.
. Ou: “senhores”.
====

[[v30-4-2]]

^<<v30-4-2,2>>^ O Soberano Senhor Jeová jurou pela sua santidade:
‘“Vejam! Hão de chegar os dias em que vocês serão levantadas com ganchos do homem do talho;
E as que restarem, com anzóis.

[[v30-4-3]]

^<<v30-4-3,3>>^ Sairão pelas brechas da muralha, cada uma pela brecha à sua frente;
E serão expulsas para Harmom”, diz Jeová.’

[[v30-4-4]]

^<<v30-4-4,4>>^ ‘Venham a Betel e cometam transgressões;^&#42;1^
A Gilgal, e cometam ainda mais transgressões!
Tragam os vossos sacrifícios de manhã,
E os vossos dízimos^&#42;2^ no terceiro dia.

[NOTE]
====
. Ou: “rebelem-se”.
. Ou: “as vossas décimas partes”.
====

[[v30-4-5]]

^<<v30-4-5,5>>^ Queimem pão feito com fermento como sacrifício de agradecimento;
Proclamem em voz alta as vossas ofertas voluntárias!
Pois isso é o que gostam de fazer, ó povo de Israel’, diz o Soberano Senhor Jeová.

[[v30-4-6]]

^<<v30-4-6,6>>^ ‘Quanto a mim, fiz com que os vossos dentes ficassem limpos, sem comida,^&#42;1^ em todas as vossas cidades,
E fiz com que faltasse pão em todas as vossas casas;
Mas vocês não voltaram para mim’, diz Jeová.

[NOTE]
====
. Ou: “Quanto a mim, não vos dei o que comer”.
====

[[v30-4-7]]

^<<v30-4-7,7>>^ ‘Também vos privei de chuvas três meses antes da colheita;
Eu fazia chover numa cidade, mas não na outra cidade.
Um campo tinha chuva,
Mas outro campo, que não tinha chuva, secava-se.

[[v30-4-8]]

^<<v30-4-8,8>>^ Pessoas de duas ou três cidades iam a cambalear até outra cidade para beber água
E, mesmo assim, não se saciavam;
Mas vocês não voltaram para mim’, diz Jeová.

[[v30-4-9]]

^<<v30-4-9,9>>^ ‘Atingi as vossas safras^&#42;1^ com um calor abrasador^&#42;2^ e com bolor.
Vocês multiplicavam os vossos jardins e vinhas,
Mas o gafanhoto devorava as vossas figueiras e oliveiras;
Mesmo assim, não voltaram para mim’, diz Jeová.

[NOTE]
====
. Ou: “Atingi-vos”.
. Ou: “crestamento”.
====

[[v30-4-10]]

^<<v30-4-10,10>>^ ‘Enviei uma peste como a do Egito contra vocês.
Com a espada, matei os jovens e capturei os cavalos.
Fiz com que o mau cheiro dos vossos acampamentos vos subisse ao nariz;
Contudo, não voltaram para mim’, diz Jeová.

[[v30-4-11]]

^<<v30-4-11,11>>^ ‘Causei uma devastação entre vocês,
Como a devastação de Sodoma e Gomorra, causada por Deus.
E vocês eram como um pedaço de madeira tirado do fogo;
Mas não voltaram para mim’, diz Jeová.

[[v30-4-12]]

^<<v30-4-12,12>>^ Portanto, é isto que eu te vou fazer, ó Israel.
Visto que o vou fazer,
Prepara-te para te encontrares com o teu Deus, ó Israel.

[[v30-4-13]]

^<<v30-4-13,13>>^ Pois ele é aquele que formou os montes e criou o vento;
Ele diz ao homem quais são os Seus pensamentos,
Transforma a aurora em escuridão
E pisa os lugares altos da terra;
O seu nome é Jeová, o Deus dos exércitos.”

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]