include::./index.adoc[]

[[v30-6-0]]
=== Amós, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v30-6-1]]

^<<v30-6-1,1>>^ “Ai dos autoconfiantes^&#42;1^ de Sião,
Dos que se sentem seguros no monte de Samaria,
Os homens de destaque da mais importante das nações,
Aqueles a quem a casa de Israel recorre!

[NOTE]
====
. Ou: “acomodados”.
====

[[v30-6-2]]

^<<v30-6-2,2>>^ Vão a Calné e vejam;
De lá, vão à Grande Hamate
E desçam a Gate dos filisteus.
Será que eles são melhores do que estes reinos,^&#42;1^
Ou será que o território deles é maior do que o vosso?

[NOTE]
====
. Aparentemente, refere-se aos reinos de Judá e Israel.
====

[[v30-6-3]]

^<<v30-6-3,3>>^ Por acaso, estão a afastar da mente o dia da calamidade
E a trazer um reinado^&#42;1^ de violência?

[NOTE]
====
. Lit.: “assento”.
====

[[v30-6-4]]

^<<v30-6-4,4>>^ Eles deitam-se em camas de marfim e estendem-se em divãs,
Comem os cordeiros do rebanho e os bezerros gordos;^&#42;1^

[NOTE]
====
. Ou: “novilhos”.
====

[[v30-6-5]]

^<<v30-6-5,5>>^ Improvisam canções ao som da harpa^&#42;1^
E, como David, inventam instrumentos musicais;

[NOTE]
====
. Ou: “dos instrumentos de cordas”.
====

[[v30-6-6]]

^<<v30-6-6,6>>^ Bebem vinho em grandes taças
E usam os óleos mais seletos.
Porém, não se importam com a^&#42;1^ catástrofe de José!

[NOTE]
====
. Lit.: “não adoeceram diante da”.
====

[[v30-6-7]]

^<<v30-6-7,7>>^ Portanto, serão os primeiros a ir para o exílio;
E a festança dos que se estendem nos seus divãs chegará ao fim.

[[v30-6-8]]

^<<v30-6-8,8>>^ ‘O Soberano Senhor Jeová jurou por si mesmo’,^&#42;1^ diz Jeová, o Deus dos exércitos:
‘“Detesto o orgulho de Jacó,
Odeio as suas torres fortificadas
E vou entregar a cidade e tudo o que nela há.

[NOTE]
====
. Ou: “pela sua alma”.
====

[[v30-6-9]]

^<<v30-6-9,9>>^ “‘“E, se numa casa sobrarem dez homens, eles também morrerão.

[[v30-6-10]]

^<<v30-6-10,10>>^ Virá um parente^&#42;1^ com o fim de trazê-los para fora e queimá-los um por um. Ele retirará os ossos deles da casa. Então, perguntará a quem estiver nos aposentos internos da casa: ‘Há mais alguém contigo?’ E o outro responderá: ‘Ninguém!’ De seguida, ele dirá: ‘Silêncio! Pois não é tempo de se mencionar o nome de Jeová.’”

[NOTE]
====
. Lit.: “o irmão do pai dele”.
====

[[v30-6-11]]

^<<v30-6-11,11>>^ Pois Jeová dá a ordem,
E ele vai derrubar a casa grande e reduzi-la a escombros,
E a casa pequena a destroços.

[[v30-6-12]]

^<<v30-6-12,12>>^ Será que os cavalos correm sobre um rochedo
Ou será que alguém lavra ali com bois?
Pois vocês transformaram a justiça numa planta venenosa,
E o fruto da retidão em absinto;^&#42;1^

[NOTE]
====
. Ou: “amargura”.
====

[[v30-6-13]]

^<<v30-6-13,13>>^ Alegram-se com o que não tem valor
E dizem: “Não foi pela nossa própria força que nos tornámos poderosos?”^&#42;1^

[NOTE]
====
. Lit.: “tomámos chifres para nós”.
====

[[v30-6-14]]

^<<v30-6-14,14>>^ Portanto, ó casa de Israel, trarei uma nação contra vocês’, diz Jeová, o Deus dos exércitos,
‘E eles hão de oprimir-vos desde Lebo-Hamate^&#42;1^ até ao vale^&#42;2^ do Arabá’.”

[NOTE]
====
. Ou: “a entrada de Hamate”.
. Ou: “uádi”. Veja o Glossário.
====

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]