include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v30-3-1]]

^<<v30-3-1,1>>^ “Ouçam esta palavra que Jeová disse a vosso respeito, ó povo de Israel, a respeito de toda a família que tirei da terra do Egito:

[[v30-3-2]]

^<<v30-3-2,2>>^ ‘Dentre todas as famílias da terra, só vos conheci a vocês.
Por isso, ajustarei contas convosco por todos os vossos erros.

[[v30-3-3]]

^<<v30-3-3,3>>^ Será que duas pessoas viajam^&#42;1^ juntas, a menos que tenham concordado em se encontrar?^&#42;2^

[NOTE]
====
. Ou: “andam”.
. Ou: “se tenham encontrado conforme combinaram”.
====

[[v30-3-4]]

^<<v30-3-4,4>>^ Será que o leão ruge na floresta sem que tenha uma presa?
E o leão novo,^&#42;1^ será que rosna no seu esconderijo sem ter apanhado nada?

[NOTE]
====
. Ou: “leão novo jubado”.
====

[[v30-3-5]]

^<<v30-3-5,5>>^ Será que o pássaro cai numa armadilha colocada no chão, sem que haja um laço para ele?^&#42;1^
E será que a armadilha salta do chão sem ter apanhado nada?

[NOTE]
====
. Ou, possivelmente: “sem que haja nela um isco”.
====

[[v30-3-6]]

^<<v30-3-6,6>>^ Quando a buzina toca na cidade, não tremem as pessoas?
Quando acontece uma calamidade na cidade, não foi Jeová quem agiu?

[[v30-3-7]]

^<<v30-3-7,7>>^ Pois o Soberano Senhor Jeová não fará coisa alguma
Sem ter revelado o seu assunto confidencial^&#42;1^ aos seus servos, os profetas.

[NOTE]
====
. Ou: “o seu segredo”.
====

[[v30-3-8]]

^<<v30-3-8,8>>^ O leão rugiu! Quem é que não terá medo?
O Soberano Senhor Jeová falou! Quem é que não profetizará?’

[[v30-3-9]]

^<<v30-3-9,9>>^ ‘Proclamem o seguinte nas torres fortificadas de Asdode
E nas torres fortificadas da terra do Egito.
Digam: “Reúnam-se contra os montes de Samaria;
Vejam o tumulto que há no seu meio
E as defraudações^&#42;1^ que lá se praticam.

[NOTE]
====
. Ou: “explorações”.
====

[[v30-3-10]]

^<<v30-3-10,10>>^ Pois eles não sabem fazer o que é direito”, diz Jeová,
“Eles, os que acumulam violência e destruição nas suas torres fortificadas.”’

[[v30-3-11]]

^<<v30-3-11,11>>^ Portanto, assim diz o Soberano Senhor Jeová:
‘Um adversário há de cercar esta terra
E arrancar-te o teu poder,
E as tuas torres fortificadas serão saqueadas.’

[[v30-3-12]]

^<<v30-3-12,12>>^ Assim diz Jeová:
‘Assim como o pastor arranca da boca do leão duas pernas ou um pedaço de orelha,
Assim será arrancado o povo de Israel,
Os que agora estão em Samaria, sentados em camas sumptuosas e em divãs de luxo.’^&#42;1^

[NOTE]
====
. Ou: “divãs de Damasco”.
====

[[v30-3-13]]

^<<v30-3-13,13>>^ ‘Ouçam e avisem^&#42;1^ a casa de Jacó’, diz o Soberano Senhor Jeová, o Deus dos exércitos.

[NOTE]
====
. Ou: “deem testemunho contra”.
====

[[v30-3-14]]

^<<v30-3-14,14>>^ ‘Pois, no dia em que eu ajustar contas com Israel por todos os seus atos rebeldes,^&#42;1^
Também ajustarei contas com os altares de Betel;
Os chifres do altar serão cortados e cairão por terra.

[NOTE]
====
. Ou: “crimes”.
====

[[v30-3-15]]

^<<v30-3-15,15>>^ Derrubarei a casa de inverno juntamente com a casa de verão.’
‘As casas de marfim serão destruídas,
E as grandes^&#42;1^ casas chegarão ao seu fim’, diz Jeová.”

[NOTE]
====
. Ou, possivelmente: “E muitas”.
====

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]