include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v30-7-1]]

^<<v30-7-1,1>>^ Isto foi o que o Soberano Senhor Jeová me mostrou: ele formou uma nuvem de gafanhotos quando a safra tardia^&#42;1^ começava a crescer. Era a safra tardia depois de se ter cortado o feno que pertence ao rei.

[NOTE]
====
. Isto é, durante janeiro e fevereiro.
====

[[v30-7-2]]

^<<v30-7-2,2>>^ Quando os gafanhotos acabaram de devorar a vegetação da terra, eu disse: “Ó Soberano Senhor Jeová, por favor, perdoa! Como é que Jacó poderá sobreviver?^&#42;1^ Ele é tão fraco!”

[NOTE]
====
. Lit.: “levantar-se”.
====

[[v30-7-3]]

^<<v30-7-3,3>>^ Então, Jeová reconsiderou a questão.^&#42;1^ “Isso não acontecerá”, disse Jeová.

[NOTE]
====
. Ou: “lamentou-o”.
====

[[v30-7-4]]

^<<v30-7-4,4>>^ Isto foi o que o Soberano Senhor Jeová me mostrou: o Soberano Senhor Jeová ordenou uma punição por fogo. O fogo consumiu as vastas águas profundas e consumiu uma parte da terra.

[[v30-7-5]]

^<<v30-7-5,5>>^ De seguida, eu disse: “Ó Soberano Senhor Jeová, por favor, não faças isso! Como é que Jacó poderá sobreviver?^&#42;1^ Ele é tão fraco!”

[NOTE]
====
. Lit.: “levantar-se”.
====

[[v30-7-6]]

^<<v30-7-6,6>>^ Então, Jeová reconsiderou a questão.^&#42;1^ “Isso também não acontecerá”, disse o Soberano Senhor Jeová.

[NOTE]
====
. Ou: “lamentou-o”.
====

[[v30-7-7]]

^<<v30-7-7,7>>^ Isto foi o que ele me mostrou: eu vi Jeová de pé sobre uma muralha feita a prumo, e ele tinha um fio de prumo na mão.

[[v30-7-8]]

^<<v30-7-8,8>>^ Depois, Jeová perguntou-me: “O que vês, Amós?” Eu respondi: “Um fio de prumo.” Então, Jeová disse: “Vou colocar um fio de prumo no meio do meu povo Israel. Nunca mais lhes perdoarei.

[[v30-7-9]]

^<<v30-7-9,9>>^ Os altos sagrados de Isaque serão desolados, e os santuários de Israel serão devastados; e eu virei com uma espada contra a casa de Jeroboão.”

[[v30-7-10]]

^<<v30-7-10,10>>^ Amazias, o sacerdote de Betel, enviou esta mensagem a Jeroboão, rei de Israel: “Amós conspira contra si no meio da casa de Israel. Esta terra não pode suportar todas as palavras dele.

[[v30-7-11]]

^<<v30-7-11,11>>^ Pois assim diz Amós: ‘Jeroboão morrerá pela espada, e Israel certamente será exilado da sua terra.’”

[[v30-7-12]]

^<<v30-7-12,12>>^ Amazias disse então a Amós: “Ó visionário, vai-te embora! Vai para a terra de Judá; ganha por lá o teu pão^&#42;1^ e, por lá, podes profetizar.

[NOTE]
====
. Lit.: “come por lá o pão”.
====

[[v30-7-13]]

^<<v30-7-13,13>>^ Mas não voltes a profetizar em Betel, pois é o santuário de um rei e o templo^&#42;1^ de um reino.”

[NOTE]
====
. Lit.: “a casa”.
====

[[v30-7-14]]

^<<v30-7-14,14>>^ Seguidamente, Amós respondeu a Amazias: “Eu não era profeta nem filho de um profeta; eu era pastor e cuidava de sicómoros.^&#42;1^

[NOTE]
====
. Ou: “e era riscador de figos de sicómoros”.
====

[[v30-7-15]]

^<<v30-7-15,15>>^ Porém, Jeová tirou-me do trabalho de seguir o rebanho, e Jeová disse-me: ‘Vai, profetiza ao meu povo Israel.’

[[v30-7-16]]

^<<v30-7-16,16>>^ Agora, ouve a palavra de Jeová: ‘Tu dizes: “Não profetizes contra Israel e não pregues contra a casa de Isaque.”

[[v30-7-17]]

^<<v30-7-17,17>>^ Portanto, assim diz Jeová: “A tua esposa vai tornar-se prostituta na cidade, e os teus filhos e as tuas filhas cairão pela espada. Com a corda de medir, as tuas terras serão repartidas, e tu próprio vais morrer numa terra impura; e, certamente, Israel será exilado da sua terra.”’”

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]