include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-5-1]]

^<<v66-5-1,1>>^ Eu vi na mão direita d’Aquele que estava sentado no trono um rolo escrito nas duas faces,^&#42;1^ bem selado com sete selos.

[NOTE]
====
. Lit.: “por dentro e por fora”.
====

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi também um anjo forte a proclamar em voz alta: “Quem é digno de abrir o rolo e de romper os seus selos?”

[[v66-5-3]]

^<<v66-5-3,3>>^ No entanto, ninguém no céu, na terra ou debaixo da terra era capaz de abrir o rolo ou de ver o que lá estava escrito.

[[v66-5-4]]

^<<v66-5-4,4>>^ Eu comecei a chorar muito, porque ninguém tinha sido considerado digno de abrir o rolo ou de ver o que lá estava escrito.

[[v66-5-5]]

^<<v66-5-5,5>>^ Contudo, um dos anciãos disse-me: “Para de chorar. Vê! O Leão da tribo de Judá, a raiz de David, venceu, de modo a abrir o rolo e os seus sete selos.”

[[v66-5-6]]

^<<v66-5-6,6>>^ E eu vi, no meio^&#42;1^ do trono e das quatro criaturas viventes e no meio dos anciãos, um cordeiro de pé, que parecia ter sido morto, e ele tinha sete chifres e sete olhos — os olhos representam os sete espíritos de Deus que foram enviados a toda a terra.

[NOTE]
====
. Ou: “no centro”.
====

[[v66-5-7]]

^<<v66-5-7,7>>^ Imediatamente, ele aproximou-se e retirou o rolo da mão direita d’Aquele que estava sentado no trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ Quando ele pegou no rolo, as quatro criaturas viventes e os 24 anciãos prostraram-se diante do Cordeiro. Cada um deles tinha uma harpa e tigelas de ouro cheias de incenso. (O incenso representa as orações dos santos.)

[[v66-5-9]]

^<<v66-5-9,9>>^ E cantam um novo cântico: “És digno de pegar no rolo e de abrir os seus selos, pois foste morto e, com o teu sangue, compraste pessoas para Deus, de todas as tribos, línguas, povos e nações,

[[v66-5-10]]

^<<v66-5-10,10>>^ e fizeste delas um reino e sacerdotes para o nosso Deus, e elas reinarão sobre a terra.”

[[v66-5-11]]

^<<v66-5-11,11>>^ Olhei e ouvi a voz de muitos anjos ao redor do trono, das criaturas viventes e dos anciãos, e o seu número era de miríades de miríades^&#42;1^ e milhares de milhares,

[NOTE]
====
. Ou: “era de dezenas de milhares vezes dezenas de milhares”.
====

[[v66-5-12]]

^<<v66-5-12,12>>^ e eles diziam em voz alta: “O Cordeiro que foi morto é digno de receber o poder, as riquezas, a sabedoria, a força, a honra, a glória e a bênção.”

[[v66-5-13]]

^<<v66-5-13,13>>^ E eu ouvi todas as criaturas no céu, na terra, debaixo da terra e no mar, sim, tudo o que há neles, a dizer: “Ao que está sentado no trono e ao Cordeiro seja dada a bênção, a honra, a glória e o poder para todo o sempre.”

[[v66-5-14]]

^<<v66-5-14,14>>^ As quatro criaturas viventes diziam: “Amém!” e os anciãos prostraram-se em adoração.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]