include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-3-1]]

^<<v66-3-1,1>>^ “Ao anjo da congregação em Sardes, escreve: Estas coisas diz aquele que tem os sete espíritos de Deus e as sete estrelas: ‘Conheço as tuas ações e sei que tens a reputação^&#42;1^ de estar vivo, mas estás morto.

[NOTE]
====
. Ou: “o nome”.
====

[[v66-3-2]]

^<<v66-3-2,2>>^ Sê vigilante e fortalece o que resta e que estava prestes a morrer, porque vi que as tuas obras não foram plenamente realizadas^&#42;1^ diante do meu Deus.

[NOTE]
====
. Ou: “porque não encontrei as tuas obras completas”.
====

[[v66-3-3]]

^<<v66-3-3,3>>^ Portanto, continua a lembrar-te do que recebeste e ouviste, continua a guardá-lo e arrepende-te. Certamente, a menos que despertes, virei como um ladrão, e de modo algum saberás a hora da minha vinda.

[[v66-3-4]]

^<<v66-3-4,4>>^ “‘Contudo, tens alguns^&#42;1^ em Sardes que não contaminaram as suas vestes, e eles andarão comigo com vestes brancas, porque são dignos.

[NOTE]
====
. Lit.: “alguns nomes”.
====

[[v66-3-5]]

^<<v66-3-5,5>>^ Aquele que vencer estará assim vestido, com vestes brancas, e eu de modo algum apagarei^&#42;1^ o seu nome do livro da vida, mas reconhecerei o seu nome diante do meu Pai e diante dos seus anjos.

[NOTE]
====
. Ou: “removerei”.
====

[[v66-3-6]]

^<<v66-3-6,6>>^ Quem tem ouvidos ouça o que o espírito diz às congregações.’

[[v66-3-7]]

^<<v66-3-7,7>>^ “Ao anjo da congregação em Filadélfia, escreve: Estas coisas diz aquele que é santo, que é verdadeiro, aquele que tem a chave de David e que abre de modo a que ninguém feche e fecha de modo a que ninguém abra:

[[v66-3-8]]

^<<v66-3-8,8>>^ ‘Conheço as tuas ações — vê, coloquei à tua frente uma porta aberta, que ninguém pode fechar. E sei que tens um pouco de poder, que guardaste a minha palavra e não te mostraste desleal para com o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Vê, eu farei com que os da sinagoga de Satanás — que se dizem judeus e não o são, mas que mentem — venham e se curvem^&#42;1^ diante dos vossos pés e vou fazê-los saber que vos amo.

[NOTE]
====
. Ou: “e prestem homenagem”.
====

[[v66-3-10]]

^<<v66-3-10,10>>^ Visto que guardaste a palavra a respeito da minha perseverança,^&#42;1^ eu também te guardarei na hora da provação, que virá sobre toda a terra habitada, para pôr à prova os que moram na terra.

[NOTE]
====
. Ou, possivelmente: “seguiste o meu exemplo de perseverança”.
====

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho depressa. Persiste em apegar-te ao que tens, para que ninguém leve a tua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ “‘Àquele que vencer, vou fazer dele uma coluna no templo do meu Deus, e ele de modo algum sairá de lá. E escreverei sobre ele o nome do meu Deus e o nome da cidade do meu Deus, a Nova Jerusalém, que desce do céu da parte do meu Deus, e o meu próprio novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem tem ouvidos ouça o que o espírito diz às congregações.’

[[v66-3-14]]

^<<v66-3-14,14>>^ “Ao anjo da congregação em Laodiceia, escreve: Estas coisas diz o Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus:

[[v66-3-15]]

^<<v66-3-15,15>>^ ‘Conheço as tuas ações e sei que não és nem frio nem quente. Eu gostaria que fosses frio ou quente.

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, visto que és morno e não és nem quente nem frio, vou vomitar-te da minha boca.

[[v66-3-17]]

^<<v66-3-17,17>>^ Visto que dizes: “Sou rico, adquiri riquezas e não preciso de nada”, mas não sabes que és miserável, coitado, pobre, cego e nu,

[[v66-3-18]]

^<<v66-3-18,18>>^ aconselho-te a comprares de mim ouro refinado pelo fogo, para que fiques rico; vestes brancas, para que fiques vestido e para que não se exponha a vergonha da tua nudez; e colírio^&#42;1^ para aplicares nos olhos, a fim de que possas ver.

[NOTE]
====
. Ou: “unguento”.
====

[[v66-3-19]]

^<<v66-3-19,19>>^ “‘A todos aqueles que amo,^&#42;1^ eu repreendo e disciplino. Portanto, sê zeloso e arrepende-te.

[NOTE]
====
. Ou: “pelos quais tenho afeição”.
====

[[v66-3-20]]

^<<v66-3-20,20>>^ Ouçam! Estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei na sua casa e cearei com ele, e ele comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Àquele que vencer, concederei que se sente comigo no meu trono, assim como eu venci e me sentei com o meu Pai no seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Quem tem ouvidos ouça o que o espírito diz às congregações.’”

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]