include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-12-1]]

^<<v66-12-1,1>>^ Viu-se então um grande sinal no céu: uma mulher estava vestida^&#42;1^ com o sol; a lua estava debaixo dos seus pés, e na sua cabeça havia uma coroa de 12 estrelas.

[NOTE]
====
. Ou: “adornada”.
====

[[v66-12-2]]

^<<v66-12-2,2>>^ Ela estava grávida e clamava nas suas dores e na sua agonia de dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ Viu-se outro sinal no céu: um grande dragão cor de fogo, com sete cabeças e dez chifres, e nas suas cabeças havia sete diademas.^&#42;1^

[NOTE]
====
. Ou: “coroas reais”.
====

[[v66-12-4]]

^<<v66-12-4,4>>^ A sua cauda arrastou um terço das estrelas do céu e lançou-as para baixo, para a terra. O dragão ficou parado diante da mulher que estava prestes a dar à luz, para poder devorar-lhe o filho, assim que ela desse à luz.

[[v66-12-5]]

^<<v66-12-5,5>>^ E ela deu à luz um filho, um menino, que governará^&#42;1^ todas as nações com uma vara de ferro. O seu filho foi-lhe, então, subitamente tirado e levado^&#42;2^ para junto de Deus e do seu trono.

[NOTE]
====
. Lit.: “apascentará”.
. Ou: “foi então arrebatado”.
====

[[v66-12-6]]

^<<v66-12-6,6>>^ E a mulher fugiu para o deserto,^&#42;1^ onde tem um lugar preparado por Deus e onde seria alimentada durante 1260 dias.

[NOTE]
====
. Veja o Glossário.
====

[[v66-12-7]]

^<<v66-12-7,7>>^ Irrompeu uma guerra no céu: Miguel^&#42;1^ e os seus anjos batalharam contra o dragão, e o dragão e os seus anjos batalharam,

[NOTE]
====
. Que significa “Quem é semelhante a Deus?”
====

[[v66-12-8]]

^<<v66-12-8,8>>^ mas não venceram,^&#42;1^ nem continuou a haver lugar para eles no céu.

[NOTE]
====
. Ou, possivelmente: “mas ele [isto é, o dragão] foi derrotado”.
====

[[v66-12-9]]

^<<v66-12-9,9>>^ Assim, foi lançado para baixo o grande dragão, a serpente original, o chamado Diabo e Satanás, que está a enganar toda a terra habitada. Ele foi lançado para baixo, para a terra, e os seus anjos foram lançados para baixo com ele.

[[v66-12-10]]

^<<v66-12-10,10>>^ Ouvi uma voz alta no céu a dizer:
“Agora, realizou-se a salvação, o poder e o Reino do nosso Deus, e a autoridade do seu Cristo, porque foi lançado para baixo o acusador dos nossos irmãos, que os acusa, dia e noite, perante o nosso Deus!

[[v66-12-11]]

^<<v66-12-11,11>>^ Eles venceram-no por causa do sangue do Cordeiro e por causa da palavra do testemunho deles, e não amaram a própria vida,^&#42;1^ nem mesmo ao encarar a morte.

[NOTE]
====
. Ou: “alma”. Veja o Glossário, “Alma”.
====

[[v66-12-12]]

^<<v66-12-12,12>>^ Por esta razão, alegrem-se, ó céus, e vocês, os que residem neles! Ai da terra e do mar, porque o Diabo desceu até vocês com grande ira, pois sabe que lhe resta pouco tempo.”

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando o dragão viu que tinha sido lançado para baixo, para a terra, perseguiu a mulher que tinha dado à luz o filho.^&#42;1^

[NOTE]
====
. Ou: “filho homem”.
====

[[v66-12-14]]

^<<v66-12-14,14>>^ Porém, foram dadas à mulher as duas asas de uma grande águia, para que pudesse voar para o deserto, para o seu lugar, onde seria alimentada por um tempo, tempos e metade de um tempo,^&#42;1^ longe da face da serpente.

[NOTE]
====
. Isto é, três tempos e meio.
====

[[v66-12-15]]

^<<v66-12-15,15>>^ E a serpente vomitou água como um rio atrás da mulher, para que ela se afogasse no rio.

[[v66-12-16]]

^<<v66-12-16,16>>^ No entanto, a terra veio em auxílio da mulher, e a terra abriu a boca e engoliu o rio que o dragão tinha vomitado.

[[v66-12-17]]

^<<v66-12-17,17>>^ Então, o dragão ficou furioso com a mulher e foi travar guerra com o restante da descendência^&#42;1^ dela, os que obedecem aos mandamentos de Deus e têm a obra de dar testemunho de Jesus.

[NOTE]
====
. Lit.: “semente”.
====

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]