include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois disso, vi outro anjo a descer do céu, com grande autoridade, e a terra ficou iluminada com a sua glória.

[[v66-18-2]]

^<<v66-18-2,2>>^ Ele clamou com voz forte: “Caiu! Caiu Babilónia, a Grande, e tornou-se uma morada de demónios e esconderijo de todos os espíritos impuros^&#42;1^ e de todas as aves impuras e odiadas!

[NOTE]
====
. Ou, possivelmente: “todo o fôlego impuro; toda a exalação impura; toda a pronunciação inspirada impura”.
====

[[v66-18-3]]

^<<v66-18-3,3>>^ Pois todas as nações foram vítimas do vinho da paixão^&#42;1^ da sua imoralidade sexual,^&#42;2^ os reis da terra cometeram imoralidade sexual com ela, e os comerciantes^&#42;3^ da terra ficaram ricos por causa do poder do seu luxo desavergonhado.”

[NOTE]
====
. Ou: “ira”.
. Em grego, porneía. Veja o Glossário.
. Ou: “comerciantes viajantes”.
====

[[v66-18-4]]

^<<v66-18-4,4>>^ Ouvi outra voz vinda do céu a dizer: “Saiam dela, meu povo, se não quiserem ser cúmplices dos seus pecados e se não quiserem receber parte das suas pragas.

[[v66-18-5]]

^<<v66-18-5,5>>^ Pois os seus pecados acumularam-se até ao céu, e Deus lembrou-se dos seus atos injustos.^&#42;1^

[NOTE]
====
. Ou: “dos seus crimes”.
====

[[v66-18-6]]

^<<v66-18-6,6>>^ Paguem-lhe na mesma moeda, sim, paguem-lhe em dobro pelo que ela fez; no cálice em que ela preparou a bebida, preparem-lhe uma porção dupla.

[[v66-18-7]]

^<<v66-18-7,7>>^ Na mesma medida em que ela se glorificou e viveu em luxo desavergonhado, deem-lhe tormento e luto. Porque ela diz no coração: ‘Estou sentada como rainha, não sou viúva e nunca hei de ver o luto.’

[[v66-18-8]]

^<<v66-18-8,8>>^ É por isso que as suas pragas — morte, luto e fome — virão num só dia, e ela será completamente queimada no fogo, porque Jeová^&#42;1^ Deus, quem a julga, é forte.

[NOTE]
====
. Veja o Ap. A5.
====

[[v66-18-9]]

^<<v66-18-9,9>>^ “E os reis da terra, que cometeram imoralidade sexual^&#42;1^ com ela e viveram com ela em luxo desavergonhado, chorarão e baterão no peito de pesar por causa dela, quando virem o fumo do seu incêndio.

[NOTE]
====
. Veja o Glossário.
====

[[v66-18-10]]

^<<v66-18-10,10>>^ Ficarão parados à distância, com medo do tormento dela, dizendo: ‘Ai, ai, ó grande cidade, Babilónia, cidade forte, porque numa só hora chegou o teu julgamento!’

[[v66-18-11]]

^<<v66-18-11,11>>^ “Também, os comerciantes da terra irão chorar e lamentar-se por causa dela, porque não haverá mais ninguém para comprar toda a sua mercadoria,

[[v66-18-12]]

^<<v66-18-12,12>>^ todo um carregamento de ouro, prata, pedras preciosas, pérolas, linho fino, púrpura, seda e escarlate; tudo o que é feito de madeira aromática e todo o tipo de objetos feitos de marfim, de madeira preciosa, de cobre, de ferro e de mármore;

[[v66-18-13]]

^<<v66-18-13,13>>^ também canela, especiarias indianas, incenso, óleo perfumado, olíbano, vinho, azeite, farinha fina, trigo, bois, ovelhas, cavalos, carruagens, escravos e vidas^&#42;1^ humanas.

[NOTE]
====
. Ou: “almas”.
====

[[v66-18-14]]

^<<v66-18-14,14>>^ Sim, ó Babilónia, as coisas boas que tu desejaste^&#42;1^ deixaram-te, e todas as tuas iguarias e coisas sumptuosas desapareceram, e nunca mais serão encontradas.

[NOTE]
====
. Ou: “a tua alma desejou”.
====

[[v66-18-15]]

^<<v66-18-15,15>>^ “Os comerciantes destas coisas, que se tornaram ricos graças a ela, ficarão parados à distância com medo do seu tormento, e hão de chorar e lamentar-se,

[[v66-18-16]]

^<<v66-18-16,16>>^ dizendo: ‘Ai, ai, ó grande cidade, vestida de linho fino, púrpura e escarlate, ricamente adornada com enfeites de ouro, pedras preciosas e pérolas,

[[v66-18-17]]

^<<v66-18-17,17>>^ porque, numa só hora, tais grandes riquezas foram devastadas!’
“E todos os capitães de navios, todos os navegantes, os marinheiros e todos os que vivem do mar ficarão parados à distância

[[v66-18-18]]

^<<v66-18-18,18>>^ e, ao ver o fumo do seu incêndio, clamarão: ‘Que cidade é semelhante à grande cidade?’

[[v66-18-19]]

^<<v66-18-19,19>>^ Eles deitarão pó sobre a cabeça e clamarão, chorando e lamentando-se: ‘Ai, ai da grande cidade, cuja riqueza enriqueceu todos os que tinham navios no mar — foi devastada numa só hora!’

[[v66-18-20]]

^<<v66-18-20,20>>^ “Alegra-te por causa dela, ó céu, e também vocês, os santos, os apóstolos e os profetas, porque foi em vosso benefício que Deus pronunciou a sentença contra ela!”

[[v66-18-21]]

^<<v66-18-21,21>>^ Então, um anjo forte levantou uma pedra semelhante a uma grande pedra de moinho e lançou-a ao mar, dizendo: “Assim, com um lance rápido, Babilónia, a grande cidade, será lançada para baixo, e nunca mais será encontrada.

[[v66-18-22]]

^<<v66-18-22,22>>^ Em ti, Babilónia, nunca mais se ouvirá o som de cantores a tocarem as suas harpas, nem o som de músicos, de flautistas e de trombeteiros. Em ti, jamais se encontrará novamente qualquer artesão, de qualquer profissão, e jamais se ouvirá outra vez o som da pedra de moinho.

[[v66-18-23]]

^<<v66-18-23,23>>^ Em ti, jamais brilhará novamente a luz de uma lâmpada e jamais se ouvirá novamente a voz de um noivo e de uma noiva, porque os teus comerciantes eram os grandes da terra e porque enganaste todas as nações com as tuas práticas de ocultismo.^&#42;1^

[NOTE]
====
. Ou: “feitiçarias; práticas espíritas”. Veja o Glossário.
====

[[v66-18-24]]

^<<v66-18-24,24>>^ Sim, nela foi encontrado o sangue dos profetas, dos santos e de todos os que foram mortos na terra.”

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]