include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-17-1]]

^<<v66-17-1,1>>^ Um dos sete anjos que tinham as sete tigelas veio e disse-me: “Vem, vou mostrar-te o julgamento da grande prostituta que está sentada sobre muitas águas.

[[v66-17-2]]

^<<v66-17-2,2>>^ Os reis da terra cometeram imoralidade sexual^&#42;1^ com ela, e os habitantes da terra embriagaram-se com o vinho da imoralidade sexual^&#42;2^ dela.”

[NOTE]
====
. Veja o Glossário.
. Em grego, porneía. Veja o Glossário.
====

[[v66-17-3]]

^<<v66-17-3,3>>^ Ele levou-me no poder do espírito para um deserto. E vi uma mulher sentada numa fera de cor escarlate^&#42;1^ que estava cheia de nomes blasfemos e que tinha sete cabeças e dez chifres.

[NOTE]
====
. Veja o Glossário.
====

[[v66-17-4]]

^<<v66-17-4,4>>^ A mulher estava vestida de púrpura e escarlate, estava adornada de ouro, pedras preciosas e pérolas, e tinha na mão um cálice de ouro cheio de coisas repugnantes e das coisas impuras da sua imoralidade sexual.^&#42;1^

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v66-17-5]]

^<<v66-17-5,5>>^ Na sua testa estava escrito um nome, um mistério: “Babilónia, a Grande, a mãe das prostitutas e das coisas repugnantes da terra.”

[[v66-17-6]]

^<<v66-17-6,6>>^ Vi que a mulher estava embriagada com o sangue dos santos e com o sangue das testemunhas de Jesus.
Ao vê-la, fiquei muito espantado.

[[v66-17-7]]

^<<v66-17-7,7>>^ Assim, o anjo disse-me: “Porque é que ficaste espantado? Vou contar-te o mistério da mulher e da fera de sete cabeças e dez chifres, que a carrega:

[[v66-17-8]]

^<<v66-17-8,8>>^ A fera que viste era, mas não é; no entanto, está prestes a subir do abismo e irá para a destruição. E os habitantes da terra (aqueles que desde a fundação do mundo não tiveram os seus nomes escritos no rolo da vida) ficarão espantados quando virem que a fera era, mas não é, e, no entanto, estará presente.

[[v66-17-9]]

^<<v66-17-9,9>>^ “É nisto que se exige uma mente sábia:^&#42;1^ as sete cabeças representam sete montes, sobre os quais a mulher está sentada.

[NOTE]
====
. Ou: “exige inteligência e sabedoria”.
====

[[v66-17-10]]

^<<v66-17-10,10>>^ E há sete reis: cinco já caíram, um é, e o outro ainda não chegou, mas, quando chegar, terá de permanecer por pouco tempo.

[[v66-17-11]]

^<<v66-17-11,11>>^ E a fera que era, mas não é, ela própria também é um oitavo rei, mas procede dos sete, e vai para a destruição.

[[v66-17-12]]

^<<v66-17-12,12>>^ “Os dez chifres que viste representam dez reis, que ainda não receberam um reino, mas recebem autoridade como reis por uma hora, juntamente com a fera.

[[v66-17-13]]

^<<v66-17-13,13>>^ Eles têm um só pensamento; assim, dão o seu poder e autoridade à fera.

[[v66-17-14]]

^<<v66-17-14,14>>^ Eles batalharão contra o Cordeiro, mas, visto que ele é Senhor dos senhores e Rei dos reis, o Cordeiro irá vencê-los. Os que estão com ele, que são chamados, escolhidos e fiéis, também vencerão.”

[[v66-17-15]]

^<<v66-17-15,15>>^ Ele disse-me: “As águas que viste, onde a prostituta está sentada, representam povos, multidões, nações e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ Os dez chifres que viste e a fera odiarão a prostituta; eles vão deixá-la devastada e nua, comer a sua carne e queimá-la completamente no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque Deus colocou-lhes no coração o desejo de executarem o pensamento dele, sim, de executarem o pensamento único deles, dando à fera o reino que possuem, até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ A mulher que viste representa a grande cidade que tem um reino sobre os reis da terra.”

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]