include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-20-1]]

^<<v66-20-1,1>>^ Vi um anjo descer do céu com a chave do abismo e uma grande corrente na mão.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele agarrou o dragão, a serpente original, que é o Diabo e Satanás, e prendeu-o por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ E lançou-o no abismo, fechou o abismo e selou-o sobre ele, para que não continuasse a enganar mais as nações até que os mil anos tivessem terminado. Depois disso, ele terá de ser solto por pouco tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ Vi tronos, e aos que estavam sentados neles foi dada autoridade para julgar. Sim, vi as almas^&#42;1^ dos que foram executados^&#42;2^ por causa do testemunho que deram de Jesus e por terem falado a respeito de Deus, vi aqueles que não tinham adorado a fera nem a sua imagem e que não tinham recebido a marca na testa e na mão. Voltaram a viver e reinaram com o Cristo por mil anos.

[NOTE]
====
. Veja o Glossário e Ap 6:9 n.
. Lit.: “executados com o machado”.
====

[[v66-20-5]]

^<<v66-20-5,5>>^ (Os outros mortos não voltaram a viver até que os mil anos tivessem terminado.) Esta é a primeira ressurreição.

[[v66-20-6]]

^<<v66-20-6,6>>^ Feliz e santo é todo aquele que tem parte na primeira ressurreição; sobre eles, a segunda morte não tem autoridade, mas serão sacerdotes de Deus e do Cristo, e reinarão com ele durante os mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Assim que os mil anos tiverem terminado, Satanás será solto da sua prisão,

[[v66-20-8]]

^<<v66-20-8,8>>^ e ele sairá para enganar as nações nos quatro cantos da terra — Gogue e Magogue — a fim de reuni-las para a guerra. O seu número é como a areia do mar.

[[v66-20-9]]

^<<v66-20-9,9>>^ E avançaram sobre toda a terra e cercaram o acampamento dos santos e a cidade amada. No entanto, desceu fogo do céu e consumiu-as.

[[v66-20-10]]

^<<v66-20-10,10>>^ E o Diabo, que as enganava, foi lançado no lago de fogo e enxofre, onde já estavam tanto a fera como o falso profeta. Eles serão atormentados^&#42;1^ dia e noite, para todo o sempre.

[NOTE]
====
. Ou: “presos; encarcerados”.
====

[[v66-20-11]]

^<<v66-20-11,11>>^ Vi então um grande trono branco e Aquele que estava sentado nele. A terra e o céu fugiam de diante dele, e não se encontrou nenhum lugar para eles.

[[v66-20-12]]

^<<v66-20-12,12>>^ Vi os mortos, os grandes e os pequenos, em pé diante do trono, e rolos foram abertos. Porém, outro rolo foi aberto: era o rolo da vida. Os mortos foram julgados pelas coisas escritas nos rolos, segundo as suas ações.

[[v66-20-13]]

^<<v66-20-13,13>>^ O mar entregou os mortos que estavam nele, e a morte e a Sepultura^&#42;1^ entregaram os mortos que estavam nelas; e estes foram julgados individualmente segundo as suas ações.

[NOTE]
====
. Ou: “o Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v66-20-14]]

^<<v66-20-14,14>>^ A morte e a Sepultura^&#42;1^ foram lançadas no lago de fogo. O lago de fogo representa a segunda morte.

[NOTE]
====
. Ou: “o Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v66-20-15]]

^<<v66-20-15,15>>^ Além disso, quem não estava inscrito no livro da vida foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]