include::./index.adoc[]

[[v66-13-0]]
=== Apocalipse, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-13-1]]

^<<v66-13-1,1>>^ E ele^&#42;1^ ficou parado na areia do mar.
Então, vi uma fera a subir do mar, com dez chifres e sete cabeças, e nos seus chifres havia dez diademas,^&#42;2^ mas nas suas cabeças havia nomes blasfemos.

[NOTE]
====
. Isto é, o dragão.
. Ou: “coroas reais”.
====

[[v66-13-2]]

^<<v66-13-2,2>>^ A fera que eu vi era semelhante a um leopardo, mas os seus pés eram como os de um urso, e a sua boca era como a boca de um leão. O dragão deu à fera o seu poder, o seu trono e grande autoridade.

[[v66-13-3]]

^<<v66-13-3,3>>^ Vi que uma das suas cabeças parecia ter sido fatalmente ferida, mas essa ferida mortal foi curada, e toda a terra seguia a fera com admiração.

[[v66-13-4]]

^<<v66-13-4,4>>^ Adoravam o dragão porque tinha dado autoridade à fera, e adoravam a fera com as palavras: “Quem é semelhante à fera e quem é que pode batalhar contra ela?”

[[v66-13-5]]

^<<v66-13-5,5>>^ Foi-lhe dada uma boca que dizia coisas arrogantes e blasfemas, e foi-lhe dada autoridade para agir por 42 meses.

[[v66-13-6]]

^<<v66-13-6,6>>^ E ela abriu a sua boca em blasfémias contra Deus, para blasfemar contra o seu nome e contra a sua morada, sim, até mesmo contra os que moram no céu.

[[v66-13-7]]

^<<v66-13-7,7>>^ Foi-lhe permitido travar guerra contra os santos e vencê-los, e foi-lhe dada autoridade sobre todas as tribos, povos, línguas e nações.

[[v66-13-8]]

^<<v66-13-8,8>>^ Todos os que moram na terra irão adorá-la. Desde a fundação do mundo, nem sequer um dos seus nomes foi escrito no rolo da vida do Cordeiro que foi morto.

[[v66-13-9]]

^<<v66-13-9,9>>^ Se alguém tem ouvidos, ouça.

[[v66-13-10]]

^<<v66-13-10,10>>^ Se alguém tiver de ir para o cativeiro, irá para o cativeiro. Se alguém matar com a espada,^&#42;1^ terá de ser morto pela espada. Isto exige perseverança e fé da parte dos santos.

[NOTE]
====
. Ou, possivelmente: “Se alguém tiver de morrer pela espada”.
====

[[v66-13-11]]

^<<v66-13-11,11>>^ Então, vi outra fera a subir da terra, e ela tinha dois chifres semelhantes aos de um cordeiro, mas começou a falar como um dragão.

[[v66-13-12]]

^<<v66-13-12,12>>^ Ela exerce toda a autoridade da primeira fera à vista desta. Faz com que a terra e os seus habitantes adorem a primeira fera, cuja ferida mortal foi curada.

[[v66-13-13]]

^<<v66-13-13,13>>^ E realiza grandes sinais, até mesmo fazendo fogo descer do céu para a terra, à vista da humanidade.

[[v66-13-14]]

^<<v66-13-14,14>>^ Ela engana os que moram na terra, por causa dos sinais que lhe foi permitido realizar à vista da fera, enquanto diz aos que moram na terra que façam uma imagem da fera que sofreu o golpe de espada e, mesmo assim, reviveu.

[[v66-13-15]]

^<<v66-13-15,15>>^ Foi-lhe permitido dar fôlego^&#42;1^ à imagem da fera, para que a imagem da fera falasse e fizesse com que todos os que se recusassem a adorar a imagem da fera fossem mortos.

[NOTE]
====
. Ou: “espírito”.
====

[[v66-13-16]]

^<<v66-13-16,16>>^ Ela põe todas as pessoas, pequenos e grandes, ricos e pobres, livres e escravos, sob a obrigação de receber uma marca na mão direita ou na testa,

[[v66-13-17]]

^<<v66-13-17,17>>^ para que ninguém possa comprar ou vender, exceto aquele que tem a marca, isto é, o nome da fera ou o número do seu nome.

[[v66-13-18]]

^<<v66-13-18,18>>^ É nisto que se exige sabedoria: quem tem discernimento calcule o número da fera, pois é um número humano.^&#42;1^ O seu número é 666.

[NOTE]
====
. Ou: “o número de um homem”.
====

'''

xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[Próximo Capítulo &#62;]