include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-11-1]]

^<<v66-11-1,1>>^ E foi-me dada uma cana semelhante a uma vara,^&#42;1^ enquanto ele me dizia: “Levanta-te para medir o santuário do templo de Deus e o altar, e os que lá estiverem a adorar.

[NOTE]
====
. Ou: “uma vara de medir”.
====

[[v66-11-2]]

^<<v66-11-2,2>>^ Porém, quanto ao pátio exterior do santuário do templo, deixa-o de fora e não o meças, porque foi dado às nações, e estas pisarão a cidade santa por 42 meses.

[[v66-11-3]]

^<<v66-11-3,3>>^ Farei com que as minhas duas testemunhas profetizem durante 1260 dias, vestidas de serapilheira.”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v66-11-4]]

^<<v66-11-4,4>>^ Elas são simbolizadas pelas duas oliveiras e pelos dois candelabros, e estão de pé diante do Senhor da terra.

[[v66-11-5]]

^<<v66-11-5,5>>^ Se alguém quiser causar-lhes dano, sairá fogo das suas bocas e consumirá os seus inimigos. Se alguém quiser causar-lhes dano, é assim que terá de ser morto.

[[v66-11-6]]

^<<v66-11-6,6>>^ Elas têm autoridade para fechar o céu, de modo que não chova durante os dias em que profetizarem, e têm autoridade para transformar as águas em sangue e para ferir a terra com todo o tipo de pragas, tantas vezes quantas quiserem.

[[v66-11-7]]

^<<v66-11-7,7>>^ Quando tiverem terminado de dar o seu testemunho, a fera que sobe do abismo vai guerrear contra elas, vencê-las e matá-las.

[[v66-11-8]]

^<<v66-11-8,8>>^ Os seus cadáveres ficarão na rua principal da grande cidade que, em sentido espiritual, se chama Sodoma e Egito, onde também o seu Senhor foi morto na estaca.

[[v66-11-9]]

^<<v66-11-9,9>>^ Povos, tribos, línguas e nações olharão para os seus cadáveres por três dias e meio e não permitirão que os seus cadáveres sejam colocados num túmulo.

[[v66-11-10]]

^<<v66-11-10,10>>^ E os que moram na terra irão alegrar-se por causa delas, comemorarão e enviarão presentes uns aos outros, porque estes dois profetas atormentavam os que moram na terra.

[[v66-11-11]]

^<<v66-11-11,11>>^ Depois desses três dias e meio, entrou neles espírito de vida da parte de Deus, e eles puseram-se de pé, e os que os viram ficaram com muito medo.

[[v66-11-12]]

^<<v66-11-12,12>>^ Eles ouviram uma voz alta vinda do céu dizer-lhes: “Subam até aqui.” Subiram então ao céu numa nuvem, e os seus inimigos viram-nos.^&#42;1^

[NOTE]
====
. Ou: “e os seus inimigos estavam a olhar”.
====

[[v66-11-13]]

^<<v66-11-13,13>>^ Naquele momento, ocorreu um grande terramoto; caiu um décimo da cidade, 7000 pessoas foram mortas pelo terramoto, e as demais ficaram com medo e deram glória ao Deus do céu.

[[v66-11-14]]

^<<v66-11-14,14>>^ O segundo ai já passou. Atenção! O terceiro ai vem depressa.

[[v66-11-15]]

^<<v66-11-15,15>>^ O sétimo anjo tocou a sua trombeta. E houve vozes altas no céu a dizer: “O reino do mundo tornou-se o Reino do nosso Senhor e do seu Cristo, e Ele reinará para todo o sempre.”

[[v66-11-16]]

^<<v66-11-16,16>>^ Os 24 anciãos que estavam sentados nos seus tronos diante de Deus prostraram-se com o rosto por terra e adoraram a Deus,

[[v66-11-17]]

^<<v66-11-17,17>>^ dizendo: “Agradecemos-te a ti, Jeová^&#42;1^ Deus, o Todo-Poderoso, aquele que é e que era, porque assumiste o teu grande poder e começaste a reinar.

[NOTE]
====
. Veja o Ap. A5.
====

[[v66-11-18]]

^<<v66-11-18,18>>^ Todavia, as nações ficaram furiosas, e veio a tua própria ira, e veio o tempo determinado para os mortos serem julgados e para recompensar os teus escravos, os profetas, bem como os santos e os que temem o teu nome, tanto os pequenos como os grandes, e para arruinar os que arruínam^&#42;1^ a terra.”

[NOTE]
====
. Ou: “destruir os que estão a destruir”.
====

[[v66-11-19]]

^<<v66-11-19,19>>^ Então, o santuário do templo de Deus no céu foi aberto, e viu-se a Arca do seu pacto no santuário do seu templo. E houve relâmpagos, vozes, trovões, um terramoto e forte granizo.

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]