include::./index.adoc[]

[[v66-2-0]]
=== Apocalipse, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-2-1]]

^<<v66-2-1,1>>^ “Ao anjo da congregação em Éfeso, escreve: Estas coisas diz aquele que segura as sete estrelas na mão direita e que anda entre os sete candelabros de ouro:

[[v66-2-2]]

^<<v66-2-2,2>>^ ‘Conheço as tuas ações, o teu trabalho árduo e a tua perseverança, e sei que não toleras homens maus e que puseste à prova os que se dizem apóstolos, mas não o são, e constataste que eles são mentirosos.

[[v66-2-3]]

^<<v66-2-3,3>>^ Mostras perseverança e suportaste muitas coisas por causa do meu nome, sem te cansares.

[[v66-2-4]]

^<<v66-2-4,4>>^ Contudo, tenho algo contra ti: abandonaste o amor que tinhas no princípio.

[[v66-2-5]]

^<<v66-2-5,5>>^ “‘Portanto, pensa no quanto caíste, arrepende-te e pratica as ações que praticavas no início. Senão, virei ter contigo e removerei o teu candelabro do seu lugar, a menos que te arrependas.

[[v66-2-6]]

^<<v66-2-6,6>>^ No entanto, tens algo a teu favor: odeias as ações da seita de Nicolau, as quais eu também odeio.

[[v66-2-7]]

^<<v66-2-7,7>>^ Quem tem ouvidos ouça o que o espírito diz às congregações: Àquele que vencer, vou conceder-lhe que coma da árvore da vida, que está no paraíso de Deus.’

[[v66-2-8]]

^<<v66-2-8,8>>^ “Ao anjo da congregação em Esmirna, escreve: Estas coisas diz ‘o Primeiro e o Último’, aquele que morreu e voltou a viver:

[[v66-2-9]]

^<<v66-2-9,9>>^ ‘Conheço a tua tribulação e pobreza, mas tu és rico. Conheço, também, a blasfémia dos que se dizem judeus, mas que, na verdade, não o são; eles são uma sinagoga de Satanás.

[[v66-2-10]]

^<<v66-2-10,10>>^ Não tenhas medo das coisas que estás prestes a sofrer. O Diabo continuará a mandar alguns de vocês para a prisão, de modo a que sejam plenamente provados, e terão tribulação por dez dias. Mostra-te fiel até à morte, e eu vou dar-te a coroa da vida.

[[v66-2-11]]

^<<v66-2-11,11>>^ Quem tem ouvidos ouça o que o espírito diz às congregações: Àquele que vencer, a segunda morte de modo algum lhe causará dano.’

[[v66-2-12]]

^<<v66-2-12,12>>^ “Ao anjo da congregação em Pérgamo, escreve: Estas coisas diz aquele que tem a longa espada afiada de dois gumes:

[[v66-2-13]]

^<<v66-2-13,13>>^ ‘Sei onde moras, isto é, onde está o trono de Satanás. Contudo, persistes em apegar-te ao meu nome e não negaste a tua fé em mim, mesmo nos dias de Antipas, minha testemunha fiel, que foi morto ao vosso lado, onde Satanás mora.

[[v66-2-14]]

^<<v66-2-14,14>>^ “‘Contudo, tenho algumas coisas contra ti: tens aí os que seguem o ensinamento de Balaão, que ensinou Balaque a pôr uma pedra de tropeço diante dos filhos de Israel, para que comessem coisas sacrificadas a ídolos e cometessem imoralidade sexual.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v66-2-15]]

^<<v66-2-15,15>>^ Da mesma forma, também tens os que seguem o ensinamento da seita de Nicolau.

[[v66-2-16]]

^<<v66-2-16,16>>^ Portanto, arrepende-te. Senão, virei ter contigo depressa e guerrearei contra eles com a longa espada da minha boca.

[[v66-2-17]]

^<<v66-2-17,17>>^ “‘Quem tem ouvidos ouça o que o espírito diz às congregações: Àquele que vencer, vou dar-lhe do maná escondido, e vou dar-lhe uma pequena pedra branca, e na pedra está escrito um novo nome, que ninguém conhece, exceto aquele que a recebe.’

[[v66-2-18]]

^<<v66-2-18,18>>^ “Ao anjo da congregação em Tiatira, escreve: Estas coisas diz o Filho de Deus, aquele cujos olhos são como uma chama ardente e cujos pés são como cobre refinado:

[[v66-2-19]]

^<<v66-2-19,19>>^ ‘Conheço as tuas ações, o teu amor, a tua fé, o teu ministério e a tua perseverança, e sei que as tuas ações recentes são mais numerosas do que as anteriores.

[[v66-2-20]]

^<<v66-2-20,20>>^ “‘Contudo, tenho algo contra ti: toleras aquela mulher, Jezabel, que se diz profetisa e que ensina e desencaminha os meus escravos, induzindo-os a cometer imoralidade sexual^&#42;1^ e a comer coisas sacrificadas a ídolos.

[NOTE]
====
. Veja o Glossário.
====

[[v66-2-21]]

^<<v66-2-21,21>>^ E eu dei-lhe tempo para se arrepender, mas ela não se quer arrepender da sua imoralidade sexual.^&#42;1^

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v66-2-22]]

^<<v66-2-22,22>>^ Portanto, estou prestes a lançá-la num leito de doença e, aos que cometem adultério com ela, em grande tribulação, a menos que se arrependam das ações dela.

[[v66-2-23]]

^<<v66-2-23,23>>^ E vou matar os seus filhos com uma praga mortífera, de modo que todas as congregações saberão que eu sou aquele que examina os pensamentos mais íntimos^&#42;1^ e o coração, e vou pagar-vos individualmente segundo as vossas ações.

[NOTE]
====
. Ou: “as emoções mais profundas”. Lit.: “os rins”.
====

[[v66-2-24]]

^<<v66-2-24,24>>^ “‘No entanto, digo aos que restam em Tiatira, a todos os que não seguem este ensinamento, os que não chegaram a conhecer as chamadas “coisas profundas de Satanás”: Não vos ponho nenhum outro fardo.

[[v66-2-25]]

^<<v66-2-25,25>>^ Contudo, apeguem-se ao que têm até que eu venha.

[[v66-2-26]]

^<<v66-2-26,26>>^ E, àquele que vencer e guardar os meus caminhos até ao fim, eu darei autoridade sobre as nações,

[[v66-2-27]]

^<<v66-2-27,27>>^ e ele irá governá-las^&#42;1^ com uma vara de ferro, de modo que serão despedaçadas como vasos de barro, assim como recebi autoridade do meu Pai.

[NOTE]
====
. Lit.: “apascentá-las”.
====

[[v66-2-28]]

^<<v66-2-28,28>>^ E eu vou dar-lhe a estrela da manhã.

[[v66-2-29]]

^<<v66-2-29,29>>^ Quem tem ouvidos ouça o que o espírito diz às congregações.’

'''

xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[Próximo Capítulo &#62;]