include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-16-1]]

^<<v66-16-1,1>>^ Ouvi então uma voz alta sair do santuário e dizer aos sete anjos: “Vão e derramem sobre a terra as sete tigelas da ira de Deus.”

[[v66-16-2]]

^<<v66-16-2,2>>^ O primeiro foi e derramou a sua tigela sobre a terra. E uma úlcera nociva e maligna afligiu as pessoas que tinham a marca da fera e que adoravam a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ O segundo derramou a sua tigela no mar. E o mar transformou-se em sangue como o de um morto, e morreram todas as criaturas^&#42;1^ viventes que havia no mar.

[NOTE]
====
. Ou: “almas”.
====

[[v66-16-4]]

^<<v66-16-4,4>>^ O terceiro derramou a sua tigela nos rios e nas fontes de água, e estes transformaram-se em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ Eu ouvi o anjo responsável pelas águas dizer: “Tu, Aquele que é e que era, o Leal, és justo, pois decretaste estes julgamentos,

[[v66-16-6]]

^<<v66-16-6,6>>^ pois derramaram o sangue dos santos e dos profetas, e tu deste-lhes sangue para beber; é o que merecem.”

[[v66-16-7]]

^<<v66-16-7,7>>^ E eu ouvi o altar dizer: “Sim, Jeová^&#42;1^ Deus, o Todo-Poderoso, verdadeiros e justos são os teus julgamentos.”^&#42;2^

[NOTE]
====
. Veja o Ap. A5.
. Ou: “as tuas decisões judiciais”.
====

[[v66-16-8]]

^<<v66-16-8,8>>^ O quarto derramou a sua tigela sobre o sol. E concedeu-se ao sol que abrasasse as pessoas com fogo.

[[v66-16-9]]

^<<v66-16-9,9>>^ As pessoas foram então abrasadas pelo grande calor, mas blasfemaram contra o nome de Deus, que tem a autoridade sobre estas pragas, e não se arrependeram nem lhe deram glória.

[[v66-16-10]]

^<<v66-16-10,10>>^ O quinto derramou a sua tigela sobre o trono da fera. E o reino dela ficou em escuridão, e as pessoas começaram a morder a língua de dor,

[[v66-16-11]]

^<<v66-16-11,11>>^ mas blasfemaram contra o Deus do céu por causa das suas dores e das suas úlceras, e não se arrependeram das suas obras.

[[v66-16-12]]

^<<v66-16-12,12>>^ O sexto derramou a sua tigela sobre o grande rio Eufrates, e a sua água secou, a fim de que se preparasse o caminho para os reis do nascente do sol.^&#42;1^

[NOTE]
====
. Ou: “os reis do leste”.
====

[[v66-16-13]]

^<<v66-16-13,13>>^ E vi três expressões inspiradas impuras,^&#42;1^ parecidas com rãs, a saírem da boca do dragão, da boca da fera e da boca do falso profeta.

[NOTE]
====
. Lit.: “espíritos impuros”.
====

[[v66-16-14]]

^<<v66-16-14,14>>^ De facto, são expressões inspiradas por demónios e realizam sinais; vão aos reis de toda a terra habitada, a fim de reuni-los para a guerra do grande dia de Deus, o Todo-Poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ “Escuta: Venho como um ladrão. Feliz é aquele que fica desperto e mantém consigo as suas roupas, para que não ande nu e as pessoas não olhem para a sua vergonha.”

[[v66-16-16]]

^<<v66-16-16,16>>^ E reuniram-nos no lugar que em hebraico se chama Armagedon.^&#42;1^

[NOTE]
====
. Em grego, Har Magedón, derivado de um termo hebraico que significa “monte de Megido”.
====

[[v66-16-17]]

^<<v66-16-17,17>>^ O sétimo derramou a sua tigela no ar. Então, uma voz alta saiu do santuário, desde o trono, e disse: “Está feito!”

[[v66-16-18]]

^<<v66-16-18,18>>^ E houve relâmpagos, vozes e trovões, e houve um grande terramoto, diferente de todos os que já tinham ocorrido desde que os homens vieram a existir na terra, de tão extenso e tão grande que foi o terramoto.

[[v66-16-19]]

^<<v66-16-19,19>>^ A grande cidade fendeu-se em três partes, e as cidades das nações caíram. E Deus lembrou-se de Babilónia, a Grande, para lhe dar o cálice com o vinho do furor da sua ira.

[[v66-16-20]]

^<<v66-16-20,20>>^ Além disso, todas as ilhas fugiram, e os montes desapareceram.

[[v66-16-21]]

^<<v66-16-21,21>>^ Então, grandes pedras de granizo, cada uma com o peso de cerca de um talento,^&#42;1^ caíram do céu sobre as pessoas, e as pessoas blasfemaram contra Deus por causa da praga de granizo, pois a praga era extraordinariamente grande.

[NOTE]
====
. Um talento grego equivalia a 20,4 kg. Veja o Ap. B14.
====

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]