include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v66-21-1]]

^<<v66-21-1,1>>^ Vi um novo céu e uma nova terra, pois o céu anterior e a terra anterior tinham passado, e o mar já não existia.

[[v66-21-2]]

^<<v66-21-2,2>>^ Vi também a cidade santa, a Nova Jerusalém, a descer do céu, da parte de Deus, e preparada como uma noiva adornada para o seu marido.

[[v66-21-3]]

^<<v66-21-3,3>>^ Então, ouvi uma voz alta do trono dizer: “Vê! A tenda de Deus está com a humanidade; ele residirá com eles, e eles serão o seu povo. O próprio Deus estará com eles.

[[v66-21-4]]

^<<v66-21-4,4>>^ Ele enxugará todas as lágrimas dos seus olhos, e não haverá mais morte, nem haverá mais tristeza,^&#42;1^ nem choro, nem dor. As coisas anteriores já passaram.”

[NOTE]
====
. Ou: “luto”.
====

[[v66-21-5]]

^<<v66-21-5,5>>^ Aquele que estava sentado no trono disse: “Vê! Faço novas todas as coisas.” Disse também: “Escreve, pois estas palavras são fiéis^&#42;1^ e verdadeiras.”

[NOTE]
====
. Ou: “confiáveis”.
====

[[v66-21-6]]

^<<v66-21-6,6>>^ E ele disse-me: “Estão cumpridas! Eu sou o Alfa e o Ómega,^&#42;1^ o princípio e o fim. A todo aquele que tiver sede, darei de graça^&#42;2^ da fonte da água da vida.

[NOTE]
====
. Ou: “o A e o Z”. Alfa e Ómega são, respetivamente, a primeira e a última letra do alfabeto grego.
. Ou: “sem custo”.
====

[[v66-21-7]]

^<<v66-21-7,7>>^ Todo aquele que vencer herdará estas coisas; eu serei o seu Deus, e ele será o meu filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ Porém, os cobardes, os que não têm fé, os que são repugnantes na sua sujidade, os assassinos, os que praticam imoralidade sexual,^&#42;1^ os que praticam ocultismo,^&#42;2^ os idólatras e todos os mentirosos terão o seu lugar no lago que queima com fogo e enxofre. Este representa a segunda morte.”

[NOTE]
====
. Veja o Glossário.
. Ou: “feitiçaria; espiritismo”. Veja o Glossário.
====

[[v66-21-9]]

^<<v66-21-9,9>>^ Um dos sete anjos que tinham as sete tigelas cheias das últimas sete pragas veio e disse-me: “Vem, vou mostrar-te a noiva, a esposa do Cordeiro.”

[[v66-21-10]]

^<<v66-21-10,10>>^ Assim, levou-me no poder do espírito para um monte grande e alto, e mostrou-me a cidade santa de Jerusalém a descer do céu, da parte de Deus

[[v66-21-11]]

^<<v66-21-11,11>>^ e com a glória de Deus. O seu brilho era semelhante ao de uma pedra muito preciosa, como uma pedra de jaspe cristalina.

[[v66-21-12]]

^<<v66-21-12,12>>^ Tinha uma muralha grande e alta e tinha 12 portões, e havia 12 anjos junto aos portões, e nos portões estavam escritos os nomes das 12 tribos dos filhos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ A leste havia três portões, a norte havia três portões, a sul havia três portões e a oeste havia três portões.

[[v66-21-14]]

^<<v66-21-14,14>>^ A muralha da cidade também tinha 12 pedras de alicerce, sobre as quais estavam os nomes dos 12 apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ Aquele que falava comigo segurava um instrumento de medida, uma cana de ouro, para medir a cidade, os seus portões e a sua muralha.

[[v66-21-16]]

^<<v66-21-16,16>>^ A cidade era quadrada, o seu comprimento era igual à sua largura. Ele mediu a cidade com a cana: 12 000 estádios.^&#42;1^ O seu comprimento, largura e altura eram iguais.

[NOTE]
====
. Cerca de 2220 km. Um estádio equivalia a 185 m. Veja o Ap. B14.
====

[[v66-21-17]]

^<<v66-21-17,17>>^ Ele mediu também a sua muralha: 144 côvados,^&#42;1^ segundo a medida humana que é, ao mesmo tempo, a medida do anjo.

[NOTE]
====
. Cerca de 64 m. Veja o Ap. B14.
====

[[v66-21-18]]

^<<v66-21-18,18>>^ A muralha era feita de jaspe, e a cidade era de ouro puro, como vidro cristalino.

[[v66-21-19]]

^<<v66-21-19,19>>^ Os alicerces da muralha da cidade eram feitos de todo o tipo de pedras preciosas: o primeiro alicerce era de jaspe; o segundo, de safira; o terceiro, de calcedónia; o quarto, de esmeralda;

[[v66-21-20]]

^<<v66-21-20,20>>^ o quinto, de sardónica; o sexto, de sárdio; o sétimo, de crisólito; o oitavo, de berilo; o nono, de topázio; o décimo, de crisópraso; o décimo primeiro, de jacinto; o décimo segundo, de ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ Também, os 12 portões eram 12 pérolas; cada um dos portões era feito de uma só pérola. E a rua principal da cidade era de ouro puro, como vidro transparente.

[[v66-21-22]]

^<<v66-21-22,22>>^ Não vi lá nenhum templo, pois Jeová^&#42;1^ Deus, o Todo-Poderoso, é o seu templo, e o Cordeiro também o é.

[NOTE]
====
. Veja o Ap. A5.
====

[[v66-21-23]]

^<<v66-21-23,23>>^ A cidade não precisa de que o sol ou a lua brilhem sobre ela, pois a glória de Deus ilumina-a, e a sua lâmpada é o Cordeiro.

[[v66-21-24]]

^<<v66-21-24,24>>^ As nações andarão pela sua luz, e os reis da terra irão levar-lhe a sua glória.

[[v66-21-25]]

^<<v66-21-25,25>>^ Os seus portões nunca se fecharão de dia, pois lá não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ A glória e a honra das nações serão levadas até ela.

[[v66-21-27]]

^<<v66-21-27,27>>^ Porém, nada que seja impuro, e ninguém que faça coisas repugnantes e enganosas, entrará nela, jamais; só entrarão os inscritos no rolo da vida do Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]