include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-7-1]]

^<<v46-7-1,1>>^ Agora, quanto às coisas sobre as quais escreveram, é melhor que o homem não toque numa^&#42;1^ mulher;

[NOTE]
====
. Isto é, não tenha relações sexuais com uma.
====

[[v46-7-2]]

^<<v46-7-2,2>>^ mas, visto que há tanta imoralidade sexual,^&#42;1^ que cada homem tenha a sua própria esposa, e que cada mulher tenha o seu próprio marido.

[NOTE]
====
. Aqui a palavra grega porneía ocorre no plural. Veja o Glossário.
====

[[v46-7-3]]

^<<v46-7-3,3>>^ Que o marido dê à esposa o que lhe é devido, e que a esposa faça o mesmo para com o marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A esposa não tem autoridade sobre o seu próprio corpo, mas sim o marido; do mesmo modo, o marido não tem autoridade sobre o seu próprio corpo, mas sim a esposa.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não se privem um ao outro do que é devido, a não ser por consentimento mútuo, por um tempo determinado, para que dediquem tempo à oração e depois se unam novamente, a fim de que Satanás não vos tente pela vossa falta de autodomínio.

[[v46-7-6]]

^<<v46-7-6,6>>^ No entanto, digo isto como concessão, não como ordem.

[[v46-7-7]]

^<<v46-7-7,7>>^ Mas quem me dera que todos os homens fossem como eu. Apesar disso, cada um tem o seu próprio dom da parte de Deus, um de um modo e outro de outro modo.

[[v46-7-8]]

^<<v46-7-8,8>>^ Agora, digo aos que não são casados e às viúvas que é melhor para eles que permaneçam assim como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Contudo, se não tiverem autodomínio, que se casem, pois é melhor casar-se do que ficar a arder de paixão.

[[v46-7-10]]

^<<v46-7-10,10>>^ Aos casados, ordeno, não eu, mas o Senhor, que a esposa não se separe do marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Mas, se ela se separar, que permaneça sem se casar, ou então que se reconcilie com o marido; e o marido não deve deixar a esposa.

[[v46-7-12]]

^<<v46-7-12,12>>^ Todavia, aos outros, digo eu, sim, eu, não o Senhor: Se algum irmão tem uma esposa descrente, e ela está disposta a viver com ele, que ele não a deixe;

[[v46-7-13]]

^<<v46-7-13,13>>^ e se uma mulher tem um marido descrente, e ele está disposto a viver com ela, que ela não deixe o marido.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois o marido descrente está santificado em relação à esposa, e a esposa descrente está santificada em relação ao irmão; caso contrário, os vossos filhos seriam impuros, mas agora são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ No entanto, se o descrente decidir deixá-la,^&#42;1^ que a deixe; o irmão ou a irmã não estão sob obrigação nessas circunstâncias, mas Deus chamou-vos à paz.

[NOTE]
====
. Ou: “separar-se”.
====

[[v46-7-16]]

^<<v46-7-16,16>>^ Pois, esposa, como é que sabes se vais ou não salvar o teu marido? Ou, marido, como é que sabes se vais ou não salvar a tua esposa?

[[v46-7-17]]

^<<v46-7-17,17>>^ Contudo, que cada um ande conforme a porção que Jeová^&#42;1^ lhe deu, conforme Deus o chamou. E assim dou esta ordem em todas as congregações.

[NOTE]
====
. Veja o Ap. A5.
====

[[v46-7-18]]

^<<v46-7-18,18>>^ Alguém já era circuncidado quando foi chamado? Que não desfaça a circuncisão. Alguém era incircunciso quando foi chamado? Que não seja circuncidado.

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão não significa nada, e a incircuncisão não significa nada; o que importa é a obediência aos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Que cada um permaneça no estado em que foi chamado.

[[v46-7-21]]

^<<v46-7-21,21>>^ Foste chamado quando eras escravo? Não te preocupes com isso; mas, se puderes ficar livre, aproveita a oportunidade.

[[v46-7-22]]

^<<v46-7-22,22>>^ Pois todo aquele que era escravo quando foi chamado no Senhor é agora o liberto que pertence ao Senhor; igualmente, aquele que era livre quando foi chamado é agora escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Vocês foram comprados por um preço; parem de se tornar escravos de homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, que cada um permaneça perante Deus no estado em que foi chamado.

[[v46-7-25]]

^<<v46-7-25,25>>^ Agora, no que se refere aos que são virgens,^&#42;1^ não tenho nenhuma ordem da parte do Senhor, mas dou a minha opinião como alguém que é fiel pela misericórdia do Senhor.

[NOTE]
====
. Ou: “aos que nunca se casaram”.
====

[[v46-7-26]]

^<<v46-7-26,26>>^ Portanto, penso que é melhor o homem continuar como está, em vista das dificuldades atuais.

[[v46-7-27]]

^<<v46-7-27,27>>^ Estás amarrado a uma esposa? Para de tentar ficar livre. Não estás amarrado a uma esposa? Para de procurar uma esposa.

[[v46-7-28]]

^<<v46-7-28,28>>^ Contudo, mesmo que te cases, não cometes pecado. E, se uma pessoa virgem se casa, não comete pecado. No entanto, os que o fizerem terão dificuldades na vida.^&#42;1^ Mas eu estou a tentar poupar-vos disso.

[NOTE]
====
. Lit.: “tribulação na carne”.
====

[[v46-7-29]]

^<<v46-7-29,29>>^ Ademais, digo o seguinte, irmãos: O tempo que resta é reduzido. De agora em diante, aqueles que têm esposa vivam como se não a tivessem;

[[v46-7-30]]

^<<v46-7-30,30>>^ os que choram, como quem não chora; os que se alegram, como quem não se alegra; os que compram, como quem não possui;

[[v46-7-31]]

^<<v46-7-31,31>>^ e os que fazem uso do mundo, como quem não o usa plenamente. Porque a cena deste mundo está a mudar.

[[v46-7-32]]

^<<v46-7-32,32>>^ Realmente, quero que estejam livres de preocupações. O homem que não é casado preocupa-se com as coisas do Senhor, em como pode agradar ao Senhor.

[[v46-7-33]]

^<<v46-7-33,33>>^ Todavia, o homem casado preocupa-se com as coisas do mundo, em como pode agradar à esposa,

[[v46-7-34]]

^<<v46-7-34,34>>^ e está dividido. Além disso, a mulher não casada e a virgem preocupam-se com as coisas do Senhor, para serem santas tanto no corpo como no espírito. No entanto, a mulher casada preocupa-se com as coisas do mundo, em como pode agradar ao marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Digo isto para o vosso próprio bem, não para vos impor restrições,^&#42;1^ mas para induzir-vos a fazer o que é apropriado e a servir constantemente ao Senhor, sem distração.

[NOTE]
====
. Lit.: “para vos armar um laço”.
====

[[v46-7-36]]

^<<v46-7-36,36>>^ Porém, se alguém acha que se está a comportar de modo impróprio por continuar sem se casar,^&#42;1^ e se estiver além da flor da juventude, então, isto é o que deve ocorrer: que ele faça o que quiser; não peca. Que se casem.

[NOTE]
====
. Ou: “com relação à sua virgindade”.
====

[[v46-7-37]]

^<<v46-7-37,37>>^ No entanto, se alguém estiver decidido no coração e não sentir necessidade, mas tiver controlo^&#42;1^ sobre a sua própria vontade e tiver tomado no seu próprio coração a decisão de não se casar,^&#42;2^ ele fará bem.

[NOTE]
====
. Lit.: “autoridade”.
. Ou: “de manter a sua própria virgindade”.
====

[[v46-7-38]]

^<<v46-7-38,38>>^ Assim, também, aquele que se casa^&#42;1^ faz bem, mas aquele que não se casar fará melhor.

[NOTE]
====
. Ou: “que dá a sua virgindade em casamento”.
====

[[v46-7-39]]

^<<v46-7-39,39>>^ A esposa está amarrada ao marido durante todo o tempo em que ele estiver vivo. Contudo, se o seu marido adormecer na morte, ela estará livre para se casar com quem quiser, somente no Senhor.

[[v46-7-40]]

^<<v46-7-40,40>>^ Na minha opinião, porém, ela será mais feliz se permanecer como está; e estou certo de que tenho também o espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]