include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-9-1]]

^<<v46-9-1,1>>^ Não sou livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Não são vocês a minha obra no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Mesmo que eu não seja apóstolo para os outros, com toda a certeza o sou para vocês! Pois vocês são o selo que confirma o meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ A minha defesa perante os que me questionam é a seguinte:

[[v46-9-4]]

^<<v46-9-4,4>>^ Será que não temos o direito de^&#42;1^ comer e beber?

[NOTE]
====
. Lit.: “não temos autoridade para”.
====

[[v46-9-5]]

^<<v46-9-5,5>>^ Será que não temos o direito de ser acompanhados por uma esposa crente,^&#42;1^ assim como os outros apóstolos, os irmãos do Senhor e Cefas?^&#42;2^

[NOTE]
====
. Ou: “uma irmã como esposa”.
. Também chamado Pedro.
====

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que só eu e Barnabé é que não temos o direito de deixar de trabalhar para o nosso sustento?

[[v46-9-7]]

^<<v46-9-7,7>>^ Que soldado é que serve com os seus próprios recursos? Quem é que planta uma vinha e não come do seu fruto? Ou quem é que pastoreia um rebanho e não bebe do leite do rebanho?

[[v46-9-8]]

^<<v46-9-8,8>>^ Será que estou a dizer estas coisas de um ponto de vista humano? Ou será que a Lei também não diz estas coisas?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois está escrito na Lei de Moisés: “Não ponhas um açaime no touro enquanto este debulha o grão.” Será que é com touros que Deus está preocupado?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou não é, de facto, por nossa causa que ele diz isso? Realmente, isso foi escrito por nossa causa, porque o homem que lavra e o homem que debulha devem fazer essas coisas na esperança de receber uma parte.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós semeamos entre vocês coisas espirituais, seria demais colhermos de vocês apoio material?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros homens têm este direito sobre vocês, será que nós não temos este direito muito mais ainda? Contudo, não fizemos uso deste direito,^&#42;1^ mas estamos a suportar tudo para não criar nenhum obstáculo às boas novas a respeito do Cristo.

[NOTE]
====
. Lit.: “desta autoridade”.
====

[[v46-9-13]]

^<<v46-9-13,13>>^ Vocês não sabem que os homens que cumprem deveres sagrados comem das coisas do templo, e que aqueles que servem regularmente diante do altar recebem uma parte do que é oferecido no altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Do mesmo modo, o Senhor ordenou que aqueles que proclamam as boas novas vivam das boas novas.

[[v46-9-15]]

^<<v46-9-15,15>>^ No entanto, eu não tenho feito uso de nem sequer uma única destas coisas. De facto, não escrevi para que se fizesse isto no meu caso, pois seria melhor morrer do que . . . Ninguém me vai tirar o meu motivo de orgulho!

[[v46-9-16]]

^<<v46-9-16,16>>^ Ora, se estou a declarar as boas novas, isso não é motivo para me orgulhar, dado que me é imposta a necessidade. Realmente, ai de mim se eu não declarar as boas novas!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se o faço espontaneamente, tenho uma recompensa; mas, mesmo que o faça contra a minha vontade, ainda assim estou incumbido de uma responsabilidade.^&#42;1^

[NOTE]
====
. Ou: “administração”.
====

[[v46-9-18]]

^<<v46-9-18,18>>^ Então, qual é a minha recompensa? É que, quando eu declarar as boas novas, eu ofereça as boas novas sem custo, para não abusar da minha autoridade^&#42;1^ no que se refere às boas novas.

[NOTE]
====
. Ou: “dos meus direitos”.
====

[[v46-9-19]]

^<<v46-9-19,19>>^ Pois, embora eu esteja livre em relação a todos, fiz-me escravo de todos, para ganhar o maior número possível de pessoas.

[[v46-9-20]]

^<<v46-9-20,20>>^ Para os judeus, tornei-me como judeu, para ganhar os judeus; para os debaixo de lei, tornei-me como debaixo de lei — embora eu mesmo não esteja debaixo de lei —, para ganhar os debaixo de lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Para os sem lei, tornei-me como sem lei — embora eu não esteja sem lei para com Deus, mas esteja debaixo de lei para com Cristo —, para ganhar os sem lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Para os fracos, tornei-me fraco, para ganhar os fracos. Tornei-me todas as coisas para pessoas de todos os tipos, para de todos os modos possíveis salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Mas faço tudo pela causa das boas novas, para compartilhá-las com outros.

[[v46-9-24]]

^<<v46-9-24,24>>^ Não sabem que numa corrida todos os atletas correm, mas apenas um recebe o prémio? Corram de tal modo que consigam ganhá-lo.

[[v46-9-25]]

^<<v46-9-25,25>>^ Todos os que participam numa competição exercem^&#42;1^ autodomínio em todas as coisas. É claro que eles fazem isso para receber uma coroa perecível, mas nós, uma que não é perecível.

[NOTE]
====
. Ou: “Todos os atletas exercem”.
====

[[v46-9-26]]

^<<v46-9-26,26>>^ Portanto, não corro sem rumo; direciono os meus golpes de modo a não golpear o ar;

[[v46-9-27]]

^<<v46-9-27,27>>^ surro^&#42;1^ o meu corpo e conduzo-o como escravo, para que, depois de ter pregado a outros, eu próprio não venha a ser de algum modo reprovado.^&#42;2^

[NOTE]
====
. Ou: “puno; disciplino severamente”.
. Ou: “desqualificado”.
====

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]