include::./index.adoc[]

[[v46-16-0]]
=== 1 Coríntios, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-16-1]]

^<<v46-16-1,1>>^ Agora, quanto à coleta para os santos, vocês podem seguir as orientações que dei às congregações da Galácia.

[[v46-16-2]]

^<<v46-16-2,2>>^ No primeiro dia da semana, cada um de vocês deve pôr algo de parte, de acordo com os seus recursos, para que as coletas não sejam feitas quando eu chegar.

[[v46-16-3]]

^<<v46-16-3,3>>^ No entanto, quando eu aí chegar, enviarei a Jerusalém os homens que vocês aprovarem por cartas, para que levem a vossa bondosa dádiva.

[[v46-16-4]]

^<<v46-16-4,4>>^ Todavia, se parecer apropriado que eu também vá, eles irão comigo.

[[v46-16-5]]

^<<v46-16-5,5>>^ Porém, vou visitar-vos depois de passar pela Macedónia, pois vou passar pela Macedónia;

[[v46-16-6]]

^<<v46-16-6,6>>^ e talvez fique convosco por algum tempo, ou até passe aí o inverno, para que depois me acompanhem durante parte do caminho para onde eu for.

[[v46-16-7]]

^<<v46-16-7,7>>^ Pois, agora, não vos quero ver só de passagem; espero passar algum tempo convosco, se Jeová^&#42;1^ permitir.

[NOTE]
====
. Veja o  Ap. A5.
====

[[v46-16-8]]

^<<v46-16-8,8>>^ No entanto, vou permanecer em Éfeso até à Festividade de Pentecostes,

[[v46-16-9]]

^<<v46-16-9,9>>^ pois abriu-se para mim uma porta ampla para a atividade, mas há muitos opositores.

[[v46-16-10]]

^<<v46-16-10,10>>^ Se Timóteo chegar aí, tomem providências para que ele não tenha nada a temer enquanto estiver no vosso meio, pois ele está a realizar a obra de Jeová,^&#42;1^ assim como eu.

[NOTE]
====
. Veja o Ap. A5.
====

[[v46-16-11]]

^<<v46-16-11,11>>^ Portanto, que ninguém o menospreze. Encaminhem-no em paz na sua viagem, para que venha ao meu encontro, pois eu e os irmãos estamos à espera dele.

[[v46-16-12]]

^<<v46-16-12,12>>^ Quanto a Apolo, nosso irmão, insisti muito para que ele vos fosse visitar com os irmãos. Ele não tem a intenção de ir agora, mas irá quando tiver oportunidade.

[[v46-16-13]]

^<<v46-16-13,13>>^ Fiquem despertos, mantenham-se firmes na fé, sejam corajosos,^&#42;1^ tornem-se poderosos.

[NOTE]
====
. Ou: “ajam como homens”.
====

[[v46-16-14]]

^<<v46-16-14,14>>^ Que tudo o que fizerem seja feito com amor.

[[v46-16-15]]

^<<v46-16-15,15>>^ Tenho uma exortação a dar-vos, irmãos: como sabem, os da casa de Estéfanas são os primeiros frutos da Acaia e eles dedicaram-se a servir os santos.

[[v46-16-16]]

^<<v46-16-16,16>>^ Que também se sujeitem a pessoas como eles e a todos os que cooperam e trabalham arduamente.

[[v46-16-17]]

^<<v46-16-17,17>>^ Contudo, alegro-me com a presença de Estéfanas, de Fortunato e de Acaico, porque compensaram a vossa ausência.

[[v46-16-18]]

^<<v46-16-18,18>>^ Pois eles reanimaram o meu espírito e o vosso. Portanto, reconheçam o valor de homens como eles.

[[v46-16-19]]

^<<v46-16-19,19>>^ As congregações da Ásia mandam-vos saudações. Áquila e Prisca, juntamente com a congregação que se reúne na sua casa, enviam-vos calorosas saudações no Senhor.

[[v46-16-20]]

^<<v46-16-20,20>>^ Todos os irmãos vos enviam saudações. Cumprimentem-se uns aos outros com um beijo santo.

[[v46-16-21]]

^<<v46-16-21,21>>^ Aqui estão as minhas saudações, as de Paulo, pela minha própria mão.

[[v46-16-22]]

^<<v46-16-22,22>>^ Se alguém não amar o Senhor, que seja amaldiçoado. Vem, nosso Senhor!

[[v46-16-23]]

^<<v46-16-23,23>>^ Que a bondade imerecida do Senhor Jesus esteja convosco.

[[v46-16-24]]

^<<v46-16-24,24>>^ Que o meu amor esteja com todos vocês em união com Cristo Jesus.

'''

xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[Próximo Capítulo &#62;]