include::./index.adoc[]

[[v46-4-0]]
=== 1 Coríntios, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-4-1]]

^<<v46-4-1,1>>^ Os homens devem considerar-nos como assistentes do^&#42;1^ Cristo e administradores dos segredos sagrados de Deus.

[NOTE]
====
. Ou: “subordinados ao”.
====

[[v46-4-2]]

^<<v46-4-2,2>>^ Ora, o que se espera dos administradores é que se mostrem fiéis.

[[v46-4-3]]

^<<v46-4-3,3>>^ Quanto a mim, pouco me importa ser examinado por vocês ou por um tribunal humano. Na verdade, nem eu me examino a mim mesmo.

[[v46-4-4]]

^<<v46-4-4,4>>^ Pois não estou ciente de nada contra mim mesmo. Todavia, isto não prova que eu seja justo; quem me examina é Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem nada antes do tempo devido, até que venha o Senhor. Ele trará as coisas secretas da escuridão para a luz e revelará as intenções dos corações, e, então, cada um receberá o seu louvor da parte de Deus.

[[v46-4-6]]

^<<v46-4-6,6>>^ Irmãos, apliquei^&#42;1^ estas coisas a mim mesmo e a Apolo para o vosso bem, a fim de que, por meio do nosso exemplo, aprendam a regra: “Não vão além das coisas que estão escritas”, de modo a que não fiquem cheios de orgulho, tomando o partido de um contra o outro.

[NOTE]
====
. Ou: “transferi”.
====

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois quem é que te torna diferente dos outros? Realmente, o que tens tu que não tenhas recebido? Se tu, de facto, recebeste tudo o que tens, porque é que te gabas como se não o tivesses recebido?

[[v46-4-8]]

^<<v46-4-8,8>>^ Já estão satisfeitos? Já estão ricos? Já começaram a reinar sem nós? Eu realmente queria que vocês já tivessem começado a reinar, para que nós também reinássemos convosco.

[[v46-4-9]]

^<<v46-4-9,9>>^ Pois parece-me que Deus nos pôs a nós, os apóstolos, em exibição por último, como homens condenados à morte, porque nos tornámos um espetáculo teatral para o mundo, para anjos e para homens.

[[v46-4-10]]

^<<v46-4-10,10>>^ Nós somos tolos por causa de Cristo, mas vocês são prudentes em união com Cristo; nós somos fracos, mas vocês são fortes; vocês são honrados, mas nós somos desonrados.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até agora, passamos fome e sede, não temos roupa suficiente,^&#42;1^ somos espancados,^&#42;2^ estamos desabrigados

[NOTE]
====
. Lit.: “e sede, e estando nus”.
. Ou: “maltratados”.
====

[[v46-4-12]]

^<<v46-4-12,12>>^ e trabalhamos arduamente com as nossas próprias mãos. Quando insultados, abençoamos; quando perseguidos, suportamos com paciência;

[[v46-4-13]]

^<<v46-4-13,13>>^ quando caluniados, respondemos com brandura;^&#42;1^ tornámo-nos como o lixo^&#42;2^ do mundo, a escória de todas as coisas, até agora.

[NOTE]
====
. Lit.: “suplicamos”.
. Ou: “refugo”.
====

[[v46-4-14]]

^<<v46-4-14,14>>^ Escrevo estas coisas, não para vos envergonhar, mas para vos instruir como meus filhos amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Pois, embora vocês tenham 10 000 tutores^&#42;1^ em Cristo, certamente, não têm muitos pais; porque fui eu que me tornei vosso pai em Cristo Jesus por meio das boas novas.

[NOTE]
====
. Ou: “guardiões”.
====

[[v46-4-16]]

^<<v46-4-16,16>>^ Assim, exorto-vos: tornem-se meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ É por isso que vos envio Timóteo, porque ele é meu filho amado e fiel no Senhor. Ele vai lembrar-vos dos meus métodos^&#42;1^ em união com Cristo Jesus, assim como estou a ensinar em toda a parte, em todas as congregações.

[NOTE]
====
. Lit.: “dos meus caminhos”.
====

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns estão cheios de orgulho, como se eu não vos fosse visitar.

[[v46-4-19]]

^<<v46-4-19,19>>^ No entanto, vou visitar-vos em breve, se Jeová^&#42;1^ quiser, e tomarei conhecimento não das palavras desses orgulhosos, mas do seu poder.

[NOTE]
====
. Veja o Ap. A5.
====

[[v46-4-20]]

^<<v46-4-20,20>>^ Pois o Reino de Deus não é uma questão de palavras, mas de poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ O que é que preferem? Que eu vos visite com uma vara, ou com amor e brandura de espírito?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]