include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-11-1]]

^<<v46-11-1,1>>^ Tornem-se meus imitadores, assim como eu sou de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Elogio-vos porque se lembram de mim em todas as coisas e apegam-se às tradições conforme as transmiti.

[[v46-11-3]]

^<<v46-11-3,3>>^ No entanto, quero que saibam que o cabeça de todo o homem é o Cristo; o cabeça da mulher é o homem; e o cabeça do Cristo é Deus.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo o homem que ora ou profetiza com algo sobre a cabeça envergonha a sua^&#42;1^ cabeça;

[NOTE]
====
. Ou: “o seu”.
====

[[v46-11-5]]

^<<v46-11-5,5>>^ mas toda a mulher que ora ou profetiza com a cabeça descoberta envergonha a sua^&#42;1^ cabeça, pois é exatamente como se fosse uma mulher com a cabeça rapada.

[NOTE]
====
. Ou: “o seu”.
====

[[v46-11-6]]

^<<v46-11-6,6>>^ Porque, se a mulher não se cobrir, deve cortar o cabelo rente; mas, se é vergonhoso para a mulher cortar o cabelo rente ou rapar a cabeça, ela deve cobrir-se.

[[v46-11-7]]

^<<v46-11-7,7>>^ Pois o homem não deve cobrir a cabeça, visto ser imagem e glória de Deus, mas a mulher é a glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Porque o homem não veio da mulher, mas a mulher veio do homem.

[[v46-11-9]]

^<<v46-11-9,9>>^ E, além disso, o homem não foi criado para a mulher, mas a mulher para o homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ É por isso que a mulher deve ter um sinal de autoridade sobre a cabeça, e por causa dos anjos.

[[v46-11-11]]

^<<v46-11-11,11>>^ Entretanto, no Senhor, nem a mulher existe sem o homem, nem o homem sem a mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ Pois, assim como a mulher procede do homem, assim também o homem vem à existência por meio da mulher; mas todas as coisas procedem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julguem por vocês mesmos: É apropriado para uma mulher orar a Deus com a cabeça descoberta?

[[v46-11-14]]

^<<v46-11-14,14>>^ Não vos ensina a própria natureza que ter cabelo comprido é uma desonra para o homem,

[[v46-11-15]]

^<<v46-11-15,15>>^ mas que, se a mulher tem cabelo comprido, isso é uma glória para ela? Pois o cabelo foi-lhe dado em vez de uma cobertura para a cabeça.

[[v46-11-16]]

^<<v46-11-16,16>>^ No entanto, se alguém quiser argumentar a favor de outro costume, não temos outro, nem o têm as congregações de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Contudo, ao dar estas ordens, não vos elogio, porque não é para o vosso benefício que se reúnem, mas para o vosso prejuízo.

[[v46-11-18]]

^<<v46-11-18,18>>^ Pois, em primeiro lugar, ouço dizer que, quando se reúnem como congregação, existem divisões entre vocês; e, até certo ponto, acredito nisso.

[[v46-11-19]]

^<<v46-11-19,19>>^ Pois certamente haverá seitas^&#42;1^ entre vocês, para que também fique claro quem são os aprovados.

[NOTE]
====
. Ou: “fações”.
====

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando se reúnem, não é realmente para tomar a Ceia do Senhor.

[[v46-11-21]]

^<<v46-11-21,21>>^ Pois, na hora de a tomar, comem primeiro o vosso próprio jantar, de modo que um está com fome, mas outro está embriagado.

[[v46-11-22]]

^<<v46-11-22,22>>^ Será que vocês não têm casa para comer e beber? Ou desprezam a congregação de Deus e envergonham aqueles que não têm nada? O que vos posso dizer? Devo elogiar-vos? Nisso, não vos elogio.

[[v46-11-23]]

^<<v46-11-23,23>>^ Pois recebi do Senhor o que também vos transmiti: que o Senhor Jesus, na noite em que ia ser traído, pegou num pão,

[[v46-11-24]]

^<<v46-11-24,24>>^ e, depois de dar graças, partiu-o e disse: “Isto representa o meu corpo, em vosso benefício. Persistam em fazer isto em memória de mim.”

[[v46-11-25]]

^<<v46-11-25,25>>^ Ele fez o mesmo também com o cálice, depois de terem tomado a refeição,^&#42;1^ dizendo: “Este cálice representa o novo pacto com base no meu sangue. Persistam em fazer isto, sempre que o beberem, em memória de mim.”

[NOTE]
====
. Ou: “ceia”, referindo-se à Páscoa.
====

[[v46-11-26]]

^<<v46-11-26,26>>^ Pois, sempre que comerem este pão e beberem este cálice, estarão a proclamar a morte do Senhor, até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Portanto, quem comer o pão ou beber o cálice do Senhor indignamente será culpado com respeito ao corpo e ao sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Primeiro, que o homem se examine e se aprove a si mesmo, e só então coma do pão e beba do cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Pois quem come e bebe sem discernir o corpo, come e bebe julgamento contra si próprio.

[[v46-11-30]]

^<<v46-11-30,30>>^ É por isso que muitos entre vocês estão fracos e doentes, e um bom número está a dormir na morte.^&#42;1^

[NOTE]
====
. Aparentemente, refere-se à morte espiritual.
====

[[v46-11-31]]

^<<v46-11-31,31>>^ Todavia, se discerníssemos o que nós próprios somos, não seríamos julgados.

[[v46-11-32]]

^<<v46-11-32,32>>^ No entanto, quando somos julgados, somos disciplinados por Jeová,^&#42;1^ para não sermos condenados com o mundo.

[NOTE]
====
. Veja o Ap. A5.
====

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando se reunirem para esta ceia, esperem uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se alguém estiver com fome, que coma em casa, para que, quando se reunirem, isso não resulte em julgamento. Contudo, quanto aos outros assuntos, vou pô-los em ordem quando aí chegar.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]