include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-14-1]]

^<<v46-14-1,1>>^ Empenhem-se pelo amor, mas continuem a esforçar-se pelos^&#42;1^ dons espirituais, de preferência, o de profetizar.

[NOTE]
====
. Ou: “continuem a buscar zelosamente os”.
====

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala em outra língua não fala a homens, mas a Deus, porque ninguém entende, embora ele fale de segredos sagrados pelo espírito.

[[v46-14-3]]

^<<v46-14-3,3>>^ Quem profetiza, contudo, edifica, encoraja e consola homens com as suas palavras.

[[v46-14-4]]

^<<v46-14-4,4>>^ Quem fala em outra língua edifica-se a si mesmo, mas quem profetiza edifica a congregação.

[[v46-14-5]]

^<<v46-14-5,5>>^ Eu gostaria que todos vocês falassem em línguas, mas prefiro que profetizem. Na verdade, quem profetiza é maior do que aquele que fala em línguas, a menos que este interprete,^&#42;1^ para que a congregação seja edificada.

[NOTE]
====
. Ou: “traduza”.
====

[[v46-14-6]]

^<<v46-14-6,6>>^ Mas, irmãos, se eu fosse agora visitar-vos a falar em línguas, que bem é que eu vos faria, a não ser que vos falasse com uma revelação, com conhecimento, com uma profecia ou com um ensinamento?

[[v46-14-7]]

^<<v46-14-7,7>>^ O mesmo acontece com as coisas inanimadas que produzem som, quer seja uma flauta, quer seja uma harpa. Se as notas não forem bem distintas, como é que alguém reconhecerá o que se toca na flauta ou na harpa?

[[v46-14-8]]

^<<v46-14-8,8>>^ Pois, se a trombeta não der um toque claro, quem é que se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Do mesmo modo, se não proferirem com a língua palavras que sejam fáceis de entender, como é que alguém saberá o que se diz? Na verdade, estarão a falar ao vento.

[[v46-14-10]]

^<<v46-14-10,10>>^ Pode ser que se falem muitos idiomas diferentes no mundo, mas não há nenhum que não tenha significado.

[[v46-14-11]]

^<<v46-14-11,11>>^ Pois, se eu não entender o sentido do que se diz, serei um estrangeiro para aquele que fala, e aquele que fala será um estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim, também vocês, visto que desejam tanto ter os dons do espírito, procurem ter em abundância dons que edificarão a congregação.

[[v46-14-13]]

^<<v46-14-13,13>>^ Portanto, quem fala em outra língua ore para que a possa interpretar.^&#42;1^

[NOTE]
====
. Ou: “traduzir”.
====

[[v46-14-14]]

^<<v46-14-14,14>>^ Pois, se eu oro em outra língua, é o meu dom do espírito que ora, mas a minha mente fica improdutiva.

[[v46-14-15]]

^<<v46-14-15,15>>^ O que se deve fazer, então? Orarei com o dom do espírito, mas orarei também com a minha mente. Cantarei louvores com o dom do espírito, mas cantarei louvores também com a minha mente.

[[v46-14-16]]

^<<v46-14-16,16>>^ De outro modo, se deres louvor com um dom do espírito, como é que a pessoa comum que está no vosso meio dirá “amém” aos teus agradecimentos, visto que não sabe o que estás a dizer?

[[v46-14-17]]

^<<v46-14-17,17>>^ É verdade que dás graças de um modo excelente, mas o outro não está a ser edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Agradeço a Deus por falar em mais línguas do que todos vocês.

[[v46-14-19]]

^<<v46-14-19,19>>^ Contudo, numa congregação, prefiro dizer cinco palavras com a minha mente,^&#42;1^ para também instruir^&#42;2^ outros, do que dizer dez mil palavras em outra língua.

[NOTE]
====
. Ou: “com o meu entendimento”.
. Ou: “instruir oralmente”.
====

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não se tornem crianças no vosso entendimento. Sejam crianças quanto à maldade, e tornem-se adultos no vosso entendimento.

[[v46-14-21]]

^<<v46-14-21,21>>^ Está escrito na Lei: “‘Pela língua de estrangeiros e pelos lábios de estranhos falarei a este povo, e mesmo assim irão recusar-se a ouvir-me’, diz Jeová.”^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v46-14-22]]

^<<v46-14-22,22>>^ Portanto, as línguas não servem de sinal para os crentes, mas para os descrentes, ao passo que a profecia não é para os descrentes, mas para os crentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Assim, se toda a congregação se reunir e todos falarem em línguas, e entrarem pessoas comuns ou descrentes, será que não vão dizer que vocês estão loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Porém, se todos vocês estiverem a profetizar e entrar um descrente ou uma pessoa comum, ele será repreendido e cuidadosamente examinado por todos.

[[v46-14-25]]

^<<v46-14-25,25>>^ Os segredos do seu coração serão então revelados, de modo que ele se prostrará com o rosto por terra e adorará a Deus, declarando: “Deus realmente está no vosso meio.”

[[v46-14-26]]

^<<v46-14-26,26>>^ O que deve, então, ser feito, irmãos? Quando se reúnem, um tem um salmo, outro tem um ensinamento, outro tem uma revelação, outro fala em outra língua, e outro tem uma interpretação. Que todas as coisas ocorram para a edificação.

[[v46-14-27]]

^<<v46-14-27,27>>^ E, se alguém falar em outra língua, que isso seja limitado a dois ou, no máximo, três, um de cada vez, e alguém deve interpretar.^&#42;1^

[NOTE]
====
. Ou: “traduzir”.
====

[[v46-14-28]]

^<<v46-14-28,28>>^ Contudo, se não houver intérprete,^&#42;1^ ele deve ficar calado na congregação e falar consigo mesmo e com Deus.

[NOTE]
====
. Ou: “tradutor”.
====

[[v46-14-29]]

^<<v46-14-29,29>>^ Que dois ou três profetas falem, e os outros discirnam o significado.

[[v46-14-30]]

^<<v46-14-30,30>>^ Todavia, se outro recebe uma revelação enquanto está lá sentado, que aquele que estava a falar se cale.

[[v46-14-31]]

^<<v46-14-31,31>>^ Pois todos vocês podem profetizar, um de cada vez, para que todos aprendam e sejam encorajados.

[[v46-14-32]]

^<<v46-14-32,32>>^ E o dom espiritual dos profetas deve ser controlado pelos profetas.

[[v46-14-33]]

^<<v46-14-33,33>>^ Pois Deus não é Deus de desordem, mas de paz.
Como em todas as congregações dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ que as mulheres fiquem caladas nas congregações, pois não lhes é permitido falar. Em vez disso, que estejam em sujeição, como também diz a Lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se elas quiserem aprender algo, perguntem ao marido, em casa, pois é vergonhoso para uma mulher falar na congregação.

[[v46-14-36]]

^<<v46-14-36,36>>^ Foi de vocês que a palavra de Deus se originou? Será que foram vocês os únicos que ela alcançou?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém acha que é profeta ou que tem um dom do espírito, ele deve reconhecer que as coisas que vos estou a escrever são o mandamento do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Mas, se alguém desconsiderar isto, ele será desconsiderado.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “se alguém ignora isto, continuará na ignorância”.
====

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, meus irmãos, continuem a esforçar-se pelo profetizar; contudo, não proíbam o falar em línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ No entanto, que todas as coisas ocorram com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]