include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-1-1]]

^<<v46-1-1,1>>^ Paulo, chamado para ser apóstolo de Cristo Jesus pela vontade de Deus, e Sóstenes, nosso irmão,

[[v46-1-2]]

^<<v46-1-2,2>>^ à congregação de Deus em Corinto, a vocês que foram santificados em união com Cristo Jesus, chamados para serem santos, com todos os que, em toda a parte, invocam o nome do nosso Senhor Jesus Cristo, Senhor deles e nosso:

[[v46-1-3]]

^<<v46-1-3,3>>^ Que tenham bondade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v46-1-4]]

^<<v46-1-4,4>>^ Agradeço sempre ao meu Deus por vocês, em vista da bondade imerecida de Deus que vos foi concedida em Cristo Jesus;

[[v46-1-5]]

^<<v46-1-5,5>>^ porque, em tudo, vocês foram enriquecidos nele, na plena capacidade de falar e no pleno conhecimento,

[[v46-1-6]]

^<<v46-1-6,6>>^ visto que o testemunho a respeito do Cristo foi firmado no vosso meio,

[[v46-1-7]]

^<<v46-1-7,7>>^ de modo que não vos falta nenhum dom enquanto esperam ansiosamente a revelação do nosso Senhor Jesus Cristo.

[[v46-1-8]]

^<<v46-1-8,8>>^ Ele também fará com que sejam firmes até ao fim, para que estejam livres de qualquer acusação no dia do nosso Senhor Jesus Cristo.

[[v46-1-9]]

^<<v46-1-9,9>>^ Deus é fiel, aquele que vos chamou para estarem em união^&#42;1^ com o seu Filho, Jesus Cristo, o nosso Senhor.

[NOTE]
====
. Ou: “para terem uma parceria (participação)”.
====

[[v46-1-10]]

^<<v46-1-10,10>>^ Exorto-vos, irmãos, pelo nome do nosso Senhor Jesus Cristo, que todos falem de acordo e que não haja divisões entre vocês, mas que estejam completamente unidos na mesma mente e na mesma maneira de pensar.

[[v46-1-11]]

^<<v46-1-11,11>>^ Pois alguns da casa de Cloé informaram-me a vosso respeito, meus irmãos, de que existem discórdias entre vocês.

[[v46-1-12]]

^<<v46-1-12,12>>^ O que eu quero dizer é que cada um de vocês diz: “Eu pertenço a Paulo”, “mas eu a Apolo”, “mas eu a Cefas”,^&#42;1^ “mas eu a Cristo”.

[NOTE]
====
. Também chamado Pedro.
====

[[v46-1-13]]

^<<v46-1-13,13>>^ Será que, por acaso, o Cristo está dividido? Será que Paulo foi morto na estaca em vosso favor? Ou, será que vocês foram batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Agradeço a Deus pelo facto de eu não ter batizado nenhum de vocês, a não ser Crispo e Gaio,

[[v46-1-15]]

^<<v46-1-15,15>>^ para que ninguém diga que vocês foram batizados em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ Sim, batizei também os da casa de Estéfanas. Quanto aos outros, não sei se batizei mais alguém.

[[v46-1-17]]

^<<v46-1-17,17>>^ Na verdade, Cristo não me enviou para batizar, mas para declarar as boas novas; e não com sabedoria de palavras,^&#42;1^ a fim de que a estaca^&#42;2^ do Cristo não se torne inútil.

[NOTE]
====
. Ou: “não com palavras inteligentes”.
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v46-1-18]]

^<<v46-1-18,18>>^ De facto, a mensagem a respeito da estaca^&#42;1^ é tolice para os que estão a caminho da destruição,^&#42;2^ mas, para nós, que estamos a ser salvos, é o poder de Deus.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
. Ou: “estão a perecer”.
====

[[v46-1-19]]

^<<v46-1-19,19>>^ Pois está escrito: “Acabarei com a sabedoria dos sábios e rejeitarei^&#42;1^ a inteligência dos intelectuais.”

[NOTE]
====
. Ou: “porei de lado”.
====

[[v46-1-20]]

^<<v46-1-20,20>>^ Onde é que está o sábio? Onde é que está o escriba?^&#42;1^ Onde é que está o argumentador deste sistema de coisas?^&#42;2^ Não tornou Deus tola a sabedoria do mundo?

[NOTE]
====
. Isto é, um perito na Lei.
. Ou: “desta época”. Veja o Glossário.
====

[[v46-1-21]]

^<<v46-1-21,21>>^ Pois, na sabedoria de Deus, o mundo, pela sua sabedoria, não chegou a conhecer a Deus. Portanto, através da tolice do que se prega, Deus agradou-se em salvar os que creem.

[[v46-1-22]]

^<<v46-1-22,22>>^ Enquanto os judeus pedem sinais e os gregos procuram sabedoria,

[[v46-1-23]]

^<<v46-1-23,23>>^ nós proclamamos Cristo morto na estaca, que é motivo de tropeço para os judeus e tolice para as nações.

[[v46-1-24]]

^<<v46-1-24,24>>^ No entanto, para os que são chamados, tanto judeus como gregos, Cristo é o poder de Deus e a sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Porque uma coisa tola de Deus é mais sábia do que os homens, e uma coisa fraca de Deus é mais forte do que os homens.

[[v46-1-26]]

^<<v46-1-26,26>>^ Através da vossa chamada, irmãos, podem ver que, entre os que foram chamados por ele, não há muitos sábios do ponto de vista humano,^&#42;1^ nem muitos poderosos, nem muitos de origem nobre.^&#42;2^

[NOTE]
====
. Lit.: “sábios segundo a carne”.
. Ou: “de famílias importantes”.
====

[[v46-1-27]]

^<<v46-1-27,27>>^ No entanto, Deus escolheu as coisas tolas do mundo para envergonhar os sábios; e Deus escolheu as coisas fracas do mundo para envergonhar as coisas fortes;

[[v46-1-28]]

^<<v46-1-28,28>>^ e Deus escolheu as coisas insignificantes do mundo e as coisas menosprezadas, as coisas que não são, para reduzir a nada as coisas que são,

[[v46-1-29]]

^<<v46-1-29,29>>^ a fim de que ninguém^&#42;1^ se orgulhe à vista de Deus.

[NOTE]
====
. Ou: “nenhuma carne”.
====

[[v46-1-30]]

^<<v46-1-30,30>>^ Contudo, é devido a ele que vocês estão em união com Cristo Jesus, que, para nós, se tornou sabedoria da parte de Deus, bem como justiça,^&#42;1^ santificação e livramento por resgate,

[NOTE]
====
. Veja o Glossário.
====

[[v46-1-31]]

^<<v46-1-31,31>>^ para que seja assim como está escrito: “Quem se orgulhar, orgulhe-se em Jeová.”^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]