include::./index.adoc[]

[[v9-17-0]]
=== 1 Samuel, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-17-1]]

^<<v9-17-1,1>>^ E os filisteus reuniram as suas tropas^&#42;1^ para a guerra. Reuniram-se em Socó, que pertence a Judá, e acamparam entre Socó e Azeca, em Efes-Damim.

[NOTE]
====
. Lit.: “os seus acampamentos”.
====

[[v9-17-2]]

^<<v9-17-2,2>>^ Saul e os homens de Israel reuniram-se e acamparam no vale^&#42;1^ de Elá, e colocaram-se em formação de batalha para enfrentar os filisteus.

[NOTE]
====
. Ou: “na planície”.
====

[[v9-17-3]]

^<<v9-17-3,3>>^ Os filisteus ocuparam o monte de um lado, e os israelitas ocuparam o monte do outro lado. Entre eles, estava o vale.

[[v9-17-4]]

^<<v9-17-4,4>>^ Nisto, saiu do acampamento dos filisteus um guerreiro campeão. O seu nome era Golias, de Gate, e ele tinha seis côvados e um palmo^&#42;1^ de altura.

[NOTE]
====
. Ele tinha cerca de 2,9 m. Veja o Ap. B14.
====

[[v9-17-5]]

^<<v9-17-5,5>>^ Ele usava um capacete de cobre e vestia uma cota de malha com escamas de cobre. A cota de malha pesava 5000 siclos.^&#42;1^

[NOTE]
====
. Cerca de 57 kg. Veja o Ap. B14.
====

[[v9-17-6]]

^<<v9-17-6,6>>^ Ele usava caneleiras de cobre nas pernas e carregava um dardo de cobre às costas.

[[v9-17-7]]

^<<v9-17-7,7>>^ O cabo de madeira da sua lança parecia o cilindro dos tecelões, e a lâmina de ferro da sua lança pesava 600 siclos.^&#42;1^ E o seu escudeiro ia à sua frente.

[NOTE]
====
. Cerca de 6,84 kg. Veja o Ap. B14.
====

[[v9-17-8]]

^<<v9-17-8,8>>^ Golias parou e gritou para o exército de Israel: “Porque é que se estão a colocar em formação de batalha? Não sou eu filisteu e vocês servos de Saul? Escolham um homem para lutar comigo.

[[v9-17-9]]

^<<v9-17-9,9>>^ Se ele conseguir lutar contra mim e me matar, nós seremos vossos escravos. Mas, se eu vencer e o matar, vocês vão tornar-se nossos escravos e servir-nos.”

[[v9-17-10]]

^<<v9-17-10,10>>^ O filisteu acrescentou: “Hoje, desafio o^&#42;1^ exército de Israel. Mandem um homem para lutar comigo!”

[NOTE]
====
. Ou: “insulto o; gozo com o”.
====

[[v9-17-11]]

^<<v9-17-11,11>>^ Quando Saul e todo o exército de Israel ouviram estas palavras do filisteu, ficaram com muito medo, apavorados.

[[v9-17-12]]

^<<v9-17-12,12>>^ David era filho do efratita de Belém de Judá, chamado Jessé, que tinha oito filhos e que, nos dias de Saul, já era idoso.

[[v9-17-13]]

^<<v9-17-13,13>>^ Os três filhos mais velhos de Jessé tinham ido à guerra com Saul. Os nomes dos três filhos que foram à guerra eram Eliabe, o primogénito, Abinadabe, o segundo, e Samá, o terceiro.

[[v9-17-14]]

^<<v9-17-14,14>>^ David era o mais novo; os três mais velhos tinham ido com Saul.

[[v9-17-15]]

^<<v9-17-15,15>>^ David ia ter com Saul e voltava para cuidar das ovelhas do seu pai em Belém.

[[v9-17-16]]

^<<v9-17-16,16>>^ E, durante 40 dias, de manhã e ao anoitecer, o filisteu aproximava-se e tomava a sua posição.

[[v9-17-17]]

^<<v9-17-17,17>>^ Certo dia, Jessé disse a David, seu filho: “Por favor, pega nesta efa^&#42;1^ de cereal torrado e nestes dez pães e leva-os depressa aos teus irmãos no acampamento.

[NOTE]
====
. Cerca de 22 l. Veja o Ap. B14.
====

[[v9-17-18]]

^<<v9-17-18,18>>^ E leva estes dez queijos^&#42;1^ ao chefe dos mil. Vê, também, como é que estão os teus irmãos e traz alguma prova de que eles estão bem.”

[NOTE]
====
. Lit.: “estas dez porções de leite”.
====

[[v9-17-19]]

^<<v9-17-19,19>>^ Eles estavam com Saul e com todos os outros homens de Israel no vale^&#42;1^ de Elá, lutando contra os filisteus.

[NOTE]
====
. Ou: “na planície”.
====

[[v9-17-20]]

^<<v9-17-20,20>>^ David levantou-se de manhã cedo e deixou alguém a cuidar das ovelhas. Preparou as provisões e partiu, assim como Jessé tinha mandado. Quando chegou ao acampamento, o exército estava a sair para o campo de batalha, dando um grito de guerra.

[[v9-17-21]]

^<<v9-17-21,21>>^ Israel e os filisteus posicionaram-se em linha de batalha, frente a frente.

[[v9-17-22]]

^<<v9-17-22,22>>^ David deixou imediatamente a bagagem aos cuidados do guarda da bagagem e correu até à linha de batalha. Ao chegar, perguntou aos seus irmãos se eles estavam bem.

[[v9-17-23]]

^<<v9-17-23,23>>^ Enquanto falava com eles, Golias, o campeão filisteu de Gate, saiu da linha de batalha dos filisteus e repetiu as suas palavras anteriores, e David ouviu-o.

[[v9-17-24]]

^<<v9-17-24,24>>^ Quando viram o homem, todos os israelitas ficaram apavorados e fugiram.

[[v9-17-25]]

^<<v9-17-25,25>>^ Os homens de Israel diziam: “Estão a ver aquele homem que está a sair? Ele está a desafiar^&#42;1^ Israel. Ao homem que o matar, o rei dará muitas riquezas e também a sua própria filha, e isentará de obrigações a casa do seu pai em Israel.”

[NOTE]
====
. Ou: “insultar; gozar com”.
====

[[v9-17-26]]

^<<v9-17-26,26>>^ David perguntou aos homens que estavam perto dele: “O que é que se dará ao homem que matar aquele filisteu e acabar com a humilhação de Israel? Pois, quem é este filisteu incircunciso para desafiar o^&#42;1^ exército do Deus vivente?”

[NOTE]
====
. Ou: “insultar o; gozar com o”.
====

[[v9-17-27]]

^<<v9-17-27,27>>^ Disseram-lhe, então, a mesma coisa que tinham dito antes: “Isto é o que se dará ao homem que o matar.”

[[v9-17-28]]

^<<v9-17-28,28>>^ Quando o ouviu a conversar com os homens, Eliabe, o irmão mais velho de David, zangou-se com David e perguntou-lhe: “Porque é que vieste aqui? E com quem é que deixaste aquelas poucas ovelhas no deserto? Conheço muito bem a tua presunção e as más intenções do teu coração; só vieste para ver a batalha.”

[[v9-17-29]]

^<<v9-17-29,29>>^ David respondeu: “O que é que eu fiz desta vez? Só fiz uma pergunta!”

[[v9-17-30]]

^<<v9-17-30,30>>^ Seguidamente, dirigiu-se a outros, perguntou-lhes a mesma coisa e deram-lhe a mesma resposta.

[[v9-17-31]]

^<<v9-17-31,31>>^ Alguns ouviram as palavras de David e contaram-nas a Saul. Por isso, Saul mandou chamá-lo.

[[v9-17-32]]

^<<v9-17-32,32>>^ David disse a Saul: “Que ninguém fique desanimado^&#42;1^ por causa deste filisteu. O seu servo irá e lutará com ele.”

[NOTE]
====
. Ou: “perca a coragem”.
====

[[v9-17-33]]

^<<v9-17-33,33>>^ No entanto, Saul disse a David: “Tu não podes lutar com este filisteu, pois és apenas um rapazinho, e ele é soldado^&#42;1^ desde a juventude.”

[NOTE]
====
. Ou: “homem de guerra”.
====

[[v9-17-34]]

^<<v9-17-34,34>>^ David disse a Saul: “Meu senhor, sou pastor do rebanho do meu pai. Quando veio um leão (e também um urso) e levou uma ovelha do rebanho,

[[v9-17-35]]

^<<v9-17-35,35>>^ fui atrás dele e ataquei-o, livrando a ovelha da sua boca. Quando ele avançou contra mim, agarrei-o pelo pescoço,^&#42;1^ feri-o e matei-o.

[NOTE]
====
. Ou: “pela mandíbula”. Lit.: “pela sua barba”.
====

[[v9-17-36]]

^<<v9-17-36,36>>^ O seu servo já matou um leão e um urso, e fará o mesmo com este filisteu incircunciso, pois ele desafiou o^&#42;1^ exército do Deus vivente.”

[NOTE]
====
. Ou: “insultou o; gozou com o”.
====

[[v9-17-37]]

^<<v9-17-37,37>>^ E David acrescentou: “Jeová, que me livrou das garras do leão e do urso, também me livrará das mãos deste filisteu.” Então, Saul disse a David: “Vai, e que Jeová esteja contigo.”

[[v9-17-38]]

^<<v9-17-38,38>>^ Então, Saul vestiu David com a sua roupa de combate. Colocou-lhe um capacete de cobre na cabeça e vestiu-o com uma cota de malha.

[[v9-17-39]]

^<<v9-17-39,39>>^ David prendeu a espada sobre a roupa e tentou andar, mas não conseguiu, pois não estava acostumado a tudo aquilo. David disse a Saul: “Não consigo andar com estas coisas, pois não estou acostumado a usá-las.” E David tirou-as.

[[v9-17-40]]

^<<v9-17-40,40>>^ A seguir, ele pegou no seu bastão, escolheu cinco pedras lisas do riacho^&#42;1^ e colocou-as no bolso do seu saco de pastor. De seguida, foi-se aproximando do filisteu, com a funda^&#42;2^ na mão.

[NOTE]
====
. Ou: “uádi”.
. Veja o Glossário.
====

[[v9-17-41]]

^<<v9-17-41,41>>^ O filisteu aproximava-se cada vez mais de David, e o seu escudeiro vinha à sua frente.

[[v9-17-42]]

^<<v9-17-42,42>>^ Quando o filisteu olhou e viu que David era apenas um jovem ruivo e de boa aparência, fez pouco dele com desprezo.

[[v9-17-43]]

^<<v9-17-43,43>>^ O filisteu disse a David: “Por acaso, sou algum cão para que venhas até mim com um pau?” Então, o filisteu amaldiçoou David, invocando os seus deuses.

[[v9-17-44]]

^<<v9-17-44,44>>^ Ele disse a David: “Vem até mim, e eu darei a tua carne às aves dos céus e aos animais selvagens.”

[[v9-17-45]]

^<<v9-17-45,45>>^ David respondeu ao filisteu: “Vens contra mim com espada, lança e dardo, mas eu vou contra ti em nome de Jeová dos exércitos, o Deus dos exércitos de Israel, a quem desafiaste.^&#42;1^

[NOTE]
====
. Ou: “a quem insultaste; com quem gozaste”.
====

[[v9-17-46]]

^<<v9-17-46,46>>^ No dia de hoje, Jeová vai entregar-te nas minhas mãos; e eu vou matar-te e cortar a tua cabeça. E hoje darei os cadáveres do exército dos filisteus às aves dos céus e aos animais selvagens da terra. Deste modo, pessoas de toda a terra saberão que há um Deus em Israel.

[[v9-17-47]]

^<<v9-17-47,47>>^ E todos os que estão aqui reunidos saberão^&#42;1^ que não é com a espada nem com a lança que Jeová salva, porque a batalha é de Jeová, e ele vai entregar-vos a todos nas nossas mãos.”

[NOTE]
====
. Lit.: “toda esta congregação saberá”.
====

[[v9-17-48]]

^<<v9-17-48,48>>^ Então, o filisteu foi-se aproximando cada vez mais para enfrentar David. Por sua vez, David correu para a linha de batalha, a fim de enfrentar o filisteu.

[[v9-17-49]]

^<<v9-17-49,49>>^ David enfiou a mão no saco, tirou uma pedra e atirou-a com a funda. A pedra atingiu o filisteu, penetrando-lhe na testa, e ele caiu com o rosto por terra.

[[v9-17-50]]

^<<v9-17-50,50>>^ Assim, David venceu o filisteu com uma funda e uma pedra. David derrubou o filisteu e matou-o, embora não tivesse nenhuma espada na mão.

[[v9-17-51]]

^<<v9-17-51,51>>^ David correu e colocou-se de pé ao lado do filisteu. Tirou então a espada do filisteu da bainha e acabou de matá-lo, cortando-lhe a cabeça. Vendo que o seu guerreiro valente tinha morrido, os filisteus fugiram.

[[v9-17-52]]

^<<v9-17-52,52>>^ Nisto, os homens de Israel e de Judá começaram a gritar e perseguiram os filisteus desde o vale até aos portões de Ecrom. E os cadáveres dos filisteus ficaram espalhados pela estrada de Saraim, até Gate e Ecrom.

[[v9-17-53]]

^<<v9-17-53,53>>^ Depois de perseguirem implacavelmente os filisteus, os israelitas voltaram e saquearam os seus acampamentos.

[[v9-17-54]]

^<<v9-17-54,54>>^ David pegou na cabeça do filisteu e levou-a para Jerusalém, mas pôs as armas do filisteu na sua tenda.

[[v9-17-55]]

^<<v9-17-55,55>>^ No momento em que Saul viu David a sair para ir ao encontro do filisteu, perguntou a Abner, chefe do exército: “Abner, quem é o pai deste jovem?” Abner respondeu: “Tão certo como o senhor vive,^&#42;1^ ó rei, eu não sei!”

[NOTE]
====
. Ou: “Pela vida da sua alma”.
====

[[v9-17-56]]

^<<v9-17-56,56>>^ O rei disse: “Descobre quem é o pai deste jovem.”

[[v9-17-57]]

^<<v9-17-57,57>>^ Portanto, assim que David voltou, depois de matar o filisteu, Abner levou-o perante Saul, e David tinha a cabeça do filisteu na mão.

[[v9-17-58]]

^<<v9-17-58,58>>^ Saul perguntou-lhe: “És filho de quem, meu jovem?” David respondeu-lhe: “Sou filho do seu servo Jessé, o belemita.”

'''

xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[&#60; Capítulo Anterior] | <<v9-17-0,Topo>> | xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[Próximo Capítulo &#62;]