include::./index.adoc[]

[[v9-7-0]]
=== 1 Samuel, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-7-1]]

^<<v9-7-1,1>>^ Portanto, vieram os homens de Quiriate-Jearim e levaram a Arca de Jeová para a casa de Abinadabe, na colina. E eles santificaram Eleazar, seu filho, para guardar a Arca de Jeová.

[[v9-7-2]]

^<<v9-7-2,2>>^ Passou-se muito tempo, 20 anos ao todo, desde que a Arca chegara a Quiriate-Jearim, e toda a casa de Israel começou a procurar a^&#42;1^ Jeová.

[NOTE]
====
. Ou: “lamentar diante de”.
====

[[v9-7-3]]

^<<v9-7-3,3>>^ Samuel disse então a toda a casa de Israel: “Se é de todo o coração que voltam para Jeová, eliminem do vosso meio os deuses estrangeiros e as imagens de Astorete. Voltem firmemente o vosso coração para Jeová, servindo-o apenas a ele, e ele vai livrar-vos das mãos dos filisteus.”

[[v9-7-4]]

^<<v9-7-4,4>>^ Assim, os israelitas livraram-se das imagens de Baal e de Astorete, e serviram apenas a Jeová.

[[v9-7-5]]

^<<v9-7-5,5>>^ Então, Samuel disse: “Reúnam todo o Israel em Mispá, e eu vou orar a Jeová por vocês.”

[[v9-7-6]]

^<<v9-7-6,6>>^ Assim, reuniram-se em Mispá, tiraram água, derramaram-na perante Jeová e jejuaram naquele dia. Foi ali que disseram: “Pecámos contra Jeová.” E Samuel começou a servir como juiz dos israelitas em Mispá.

[[v9-7-7]]

^<<v9-7-7,7>>^ Quando os filisteus souberam que os israelitas se tinham reunido em Mispá, os governantes dos filisteus subiram contra Israel. Ao saberem disso, os israelitas ficaram com medo dos filisteus.

[[v9-7-8]]

^<<v9-7-8,8>>^ Portanto, os israelitas disseram a Samuel: “Não pares de clamar a Jeová, nosso Deus, para que ele nos ajude e nos salve das mãos dos filisteus.”

[[v9-7-9]]

^<<v9-7-9,9>>^ Então, Samuel pegou num cordeiro que ainda mamava e ofereceu-o inteiro a Jeová como oferta queimada; e Samuel clamou a Jeová por ajuda a favor de Israel, e Jeová respondeu-lhe.

[[v9-7-10]]

^<<v9-7-10,10>>^ Enquanto Samuel fazia a oferta queimada, os filisteus avançaram para lutar contra Israel. Naquele dia, Jeová mandou uma forte trovoada contra os filisteus e lançou-os em confusão, e eles foram derrotados diante de Israel.

[[v9-7-11]]

^<<v9-7-11,11>>^ Em vista disso, os homens de Israel saíram de Mispá e perseguiram os filisteus até à região a sul de Bete-Car, matando-os pelo caminho.

[[v9-7-12]]

^<<v9-7-12,12>>^ Samuel pegou, então, numa pedra e colocou-a entre Mispá e Jesana, e chamou-lhe Ebenezer,^&#42;1^ dizendo: “Até agora, Jeová ajudou-nos.”

[NOTE]
====
. Que significa “pedra de ajuda”.
====

[[v9-7-13]]

^<<v9-7-13,13>>^ Assim, os filisteus foram dominados e não voltaram a invadir o território de Israel; e a mão de Jeová continuou contra os filisteus durante todos os dias de Samuel.

[[v9-7-14]]

^<<v9-7-14,14>>^ Além disso, as cidades que os filisteus tinham tirado a Israel foram devolvidas a Israel, desde Ecrom até Gate, e Israel recuperou o território das mãos dos filisteus.
E também houve paz entre Israel e os amorreus.

[[v9-7-15]]

^<<v9-7-15,15>>^ Samuel continuou a julgar Israel ao longo de toda a sua vida.

[[v9-7-16]]

^<<v9-7-16,16>>^ Todos os anos, ele percorria o circuito de Betel, Gilgal e Mispá, julgando Israel em todos estes lugares.

[[v9-7-17]]

^<<v9-7-17,17>>^ No entanto, voltava a Ramá, porque era lá que ficava a sua casa e era também lá que ele julgava Israel. E, em Ramá, ele construiu um altar a Jeová.

'''

xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[&#60; Capítulo Anterior] | <<v9-7-0,Topo>> | xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[Próximo Capítulo &#62;]