include::./index.adoc[]

[[v9-21-0]]
=== 1 Samuel, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-21-1]]

^<<v9-21-1,1>>^ Mais tarde, David foi a Nobe, a Aimeleque, o sacerdote. Ao encontrar-se com David, Aimeleque começou a tremer de medo e perguntou-lhe: “Porque é que estás sozinho? Porque é que não veio ninguém contigo?”

[[v9-21-2]]

^<<v9-21-2,2>>^ David disse a Aimeleque, o sacerdote: “O rei instruiu-me a fazer algo, mas disse: ‘Não deixes que ninguém saiba nada sobre a missão para a qual te estou a enviar, nem sobre as instruções que te dei.’ Por isso, combinei com os meus homens encontrarmo-nos num determinado lugar.

[[v9-21-3]]

^<<v9-21-3,3>>^ Agora, se o senhor tiver cinco pães ou qualquer outra coisa, entregue-mos.”

[[v9-21-4]]

^<<v9-21-4,4>>^ No entanto, o sacerdote disse a David: “Não tenho pão comum, apenas pão sagrado; podem comê-lo, desde que os teus homens não tenham tido contacto com mulheres.”^&#42;1^

[NOTE]
====
. Ou: “não tenham tido relações sexuais”.
====

[[v9-21-5]]

^<<v9-21-5,5>>^ David disse ao sacerdote: “Pode ter a certeza de que as mulheres foram mantidas longe de nós, assim como das outras vezes, quando saímos em campanhas militares. Se, mesmo quando a missão é comum, os homens se mantêm puros, quanto mais hoje!”

[[v9-21-6]]

^<<v9-21-6,6>>^ Assim, o sacerdote deu-lhe os pães sagrados, pois só havia lá os pães da proposição, que tinham sido tirados da presença de Jeová e substituídos por pão fresco no dia em que se tiravam os pães.

[[v9-21-7]]

^<<v9-21-7,7>>^ Naquele dia, estava lá um dos servos de Saul, retido perante Jeová. O seu nome era Doegue, o edomita, chefe dos pastores de Saul.

[[v9-21-8]]

^<<v9-21-8,8>>^ David perguntou então a Aimeleque: “Não tem aqui, à mão, uma lança ou uma espada? É que eu não trouxe nem a minha espada nem as minhas armas, visto que a missão do rei era urgente.”

[[v9-21-9]]

^<<v9-21-9,9>>^ O sacerdote respondeu: “Tenho a espada de Golias, o filisteu, que mataste no vale^&#42;1^ de Elá. Está aqui, enrolada num pano, atrás do éfode. Se quiseres, podes levá-la, porque é a única que há aqui.” David disse: “Dê-me essa espada, pois não existe outra igual.”

[NOTE]
====
. Ou: “na planície”.
====

[[v9-21-10]]

^<<v9-21-10,10>>^ Naquele mesmo dia, David partiu e continuou a fugir de Saul, e, por fim, chegou ao território de Aquis, rei de Gate.

[[v9-21-11]]

^<<v9-21-11,11>>^ Os servos de Aquis disseram-lhe: “Este não é David, rei da terra de Israel? Não era sobre ele que cantavam nas danças, dizendo:
‘Saul matou milhares,
E David dezenas de milhares’?”

[[v9-21-12]]

^<<v9-21-12,12>>^ Pensando no que eles disseram, David ficou com muito medo de Aquis, rei de Gate.

[[v9-21-13]]

^<<v9-21-13,13>>^ Portanto, na presença deles, disfarçou a sua sanidade e agiu como um louco entre eles.^&#42;1^ Ele rabiscava os portões e deixava escorrer saliva pela barba.

[NOTE]
====
. Lit.: “na mão deles”.
====

[[v9-21-14]]

^<<v9-21-14,14>>^ Por fim, Aquis disse aos seus servos: “Não estão a ver que este homem é louco? Porque é que o trouxeram até mim?

[[v9-21-15]]

^<<v9-21-15,15>>^ Já tenho loucos que me cheguem, e vocês ainda me trazem mais um? Será que este homem devia entrar na minha casa?”

'''

xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[&#60; Capítulo Anterior] | <<v9-21-0,Topo>> | xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[Próximo Capítulo &#62;]