include::./index.adoc[]

[[v9-16-0]]
=== 1 Samuel, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-16-1]]

^<<v9-16-1,1>>^ Por fim, Jeová disse a Samuel: “Até quando é que vais ficar triste por causa de Saul, tendo em conta que eu o rejeitei como rei de Israel? Enche um chifre com óleo e vai. Vou enviar-te a Jessé, o belemita, porque escolhi um dos seus filhos para ser rei.”

[[v9-16-2]]

^<<v9-16-2,2>>^ No entanto, Samuel disse: “Como é que posso ir? Quando Saul souber disso, vai matar-me.” Jeová respondeu: “Leva uma novilha contigo e diz: ‘Vim para oferecer um sacrifício a Jeová.’

[[v9-16-3]]

^<<v9-16-3,3>>^ Convida Jessé para o sacrifício, e eu vou dizer-te o que deves fazer. Deves ungir-me aquele que eu indicar.”

[[v9-16-4]]

^<<v9-16-4,4>>^ Samuel fez o que Jeová disse. Quando chegou a Belém, os anciãos da cidade foram ao seu encontro, a tremer de medo, e disseram-lhe: “A sua visita é de paz?”

[[v9-16-5]]

^<<v9-16-5,5>>^ Ele respondeu: “É de paz. Vim para oferecer um sacrifício a Jeová. Santifiquem-se e venham comigo ao sacrifício.” Então, ele santificou Jessé e os seus filhos. Depois, chamou-os para o sacrifício.

[[v9-16-6]]

^<<v9-16-6,6>>^ Quando entraram e Samuel viu Eliabe, ele disse: ‘Com certeza, este é o ungido de Jeová.’

[[v9-16-7]]

^<<v9-16-7,7>>^ Jeová, contudo, disse a Samuel: “Não olhes para a sua aparência nem para a sua altura, visto que o rejeitei. Porque Deus não vê como o homem vê; o homem vê a aparência, mas Jeová vê o coração.”

[[v9-16-8]]

^<<v9-16-8,8>>^ De seguida, Jessé chamou Abinadabe, fazendo-o passar diante de Samuel, mas ele disse: “Este também não foi escolhido por Jeová.”

[[v9-16-9]]

^<<v9-16-9,9>>^ A seguir, Jessé apresentou Samá, mas ele disse: “Este também não foi aquele que Jeová escolheu.”

[[v9-16-10]]

^<<v9-16-10,10>>^ Assim, Jessé fez com que sete dos seus filhos passassem diante de Samuel, mas Samuel disse a Jessé: “Jeová não escolheu nenhum destes.”

[[v9-16-11]]

^<<v9-16-11,11>>^ Por fim, Samuel perguntou a Jessé: “Estes são todos os filhos que tens?” Ele respondeu: “Ainda falta o mais novo; ele está a pastorear as ovelhas.” Então, Samuel disse a Jessé: “Manda chamá-lo, porque não nos sentaremos para a refeição enquanto ele não chegar.”

[[v9-16-12]]

^<<v9-16-12,12>>^ Portanto, mandou chamá-lo. Ele era ruivo,^&#42;1^ de belos olhos e boa aparência. Jeová disse: “Levanta-te, é este! Deves ungi-lo.”

[NOTE]
====
. Ou: “corado”.
====

[[v9-16-13]]

^<<v9-16-13,13>>^ Seguidamente, Samuel pegou no chifre com óleo e ungiu-o na presença dos seus irmãos. A partir daquele dia, o espírito de Jeová deu poder a David. Mais tarde, Samuel voltou para Ramá.

[[v9-16-14]]

^<<v9-16-14,14>>^ O espírito de Jeová tinha-se retirado de Saul, e um espírito mau da parte de Jeová passou a aterrorizá-lo.

[[v9-16-15]]

^<<v9-16-15,15>>^ Os servos de Saul disseram-lhe: “Um espírito mau da parte de Deus está a aterrorizá-lo.

[[v9-16-16]]

^<<v9-16-16,16>>^ Por favor, ordene aos seus servos aqui presentes que procurem um homem perito em tocar harpa. Quando um espírito mau da parte de Deus vier sobre si, ele tocará, e o senhor irá sentir-se melhor.”

[[v9-16-17]]

^<<v9-16-17,17>>^ Portanto, Saul disse aos seus servos: “Encontrem, por favor, um homem que toque bem, e tragam-mo.”

[[v9-16-18]]

^<<v9-16-18,18>>^ Um dos ajudantes disse: “Sei que um dos filhos de Jessé, o belemita, sabe tocar harpa muito bem, e é um guerreiro corajoso e valente. Ele fala bem, tem boa aparência e Jeová está com ele.”

[[v9-16-19]]

^<<v9-16-19,19>>^ Saul enviou mensageiros a Jessé para lhe dizerem: “Envia-me o teu filho David, que está com o rebanho.”

[[v9-16-20]]

^<<v9-16-20,20>>^ Portanto, juntamente com o seu filho David, Jessé enviou a Saul um jumento carregado de pão, um odre de vinho e um cabrito.

[[v9-16-21]]

^<<v9-16-21,21>>^ Assim, David foi até Saul e começou a servi-lo. Saul passou a gostar muito dele, e ele tornou-se seu escudeiro.

[[v9-16-22]]

^<<v9-16-22,22>>^ Saul mandou dizer a Jessé: “Por favor, deixa David ficar ao meu serviço, pois ele achou favor aos meus olhos.”

[[v9-16-23]]

^<<v9-16-23,23>>^ Quando um espírito mau da parte de Deus vinha sobre Saul, David pegava na harpa e tocava; então, Saul sentia alívio e melhorava, e o espírito mau retirava-se dele.

'''

xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[&#60; Capítulo Anterior] | <<v9-16-0,Topo>> | xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[Próximo Capítulo &#62;]