include::./index.adoc[]

[[v9-13-0]]
=== 1 Samuel, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-13-1]]

^<<v9-13-1,1>>^ Saul tinha . . .^&#42;1^ anos de idade quando se tornou rei e reinou dois anos sobre Israel.

[NOTE]
====
. Falta o número no texto hebraico.
====

[[v9-13-2]]

^<<v9-13-2,2>>^ Saul escolheu 3000 homens de Israel: 2000 ficaram com Saul em Micmás e na região montanhosa de Betel, e 1000 ficaram com Jonatã em Gibeá de Benjamim. Quanto ao restante dos homens, ele mandou-os de volta, cada um para a sua tenda.

[[v9-13-3]]

^<<v9-13-3,3>>^ Então, Jonatã derrotou o grupo de soldados filisteus que havia em Geba, e os filisteus tomaram conhecimento disso. De seguida, Saul mandou tocar a buzina em todo o país, dizendo: “Que os hebreus ouçam!”

[[v9-13-4]]

^<<v9-13-4,4>>^ E todo o Israel ouviu a notícia: “Saul derrotou um grupo de soldados filisteus e, agora, os filisteus ficaram com ódio a Israel.”^&#42;1^ Assim, o povo foi convocado para seguir Saul em Gilgal.

[NOTE]
====
. Ou: “agora, Israel tornou-se um mau cheiro entre os filisteus”.
====

[[v9-13-5]]

^<<v9-13-5,5>>^ Os filisteus também se reuniram para lutar contra Israel, com 30 000 carros de guerra, 6000 cavaleiros e um grupo de soldados tão numeroso como os grãos de areia à beira-mar. Eles subiram e acamparam-se em Micmás, a leste de Bete-Áven.

[[v9-13-6]]

^<<v9-13-6,6>>^ Quando os homens de Israel viram que estavam em apuros, numa situação muito difícil, esconderam-se em cavernas, fendas, rochedos, lugares subterrâneos e cisternas.

[[v9-13-7]]

^<<v9-13-7,7>>^ Alguns hebreus até chegaram a atravessar o Jordão para a terra de Gade e de Gileade. No entanto, Saul ficou em Gilgal, e todos os que o seguiam tremiam de medo.

[[v9-13-8]]

^<<v9-13-8,8>>^ Ele esperou sete dias, até que terminasse o prazo estabelecido por Samuel, mas Samuel não chegava a Gilgal, e os que estavam com Saul começaram a espalhar-se.

[[v9-13-9]]

^<<v9-13-9,9>>^ Por fim, Saul disse: “Tragam-me o sacrifício queimado e os sacrifícios de participação em comum.” E ele ofereceu o sacrifício queimado.

[[v9-13-10]]

^<<v9-13-10,10>>^ Contudo, assim que ele tinha acabado de oferecer o sacrifício queimado, chegou Samuel. Portanto, Saul foi ao seu encontro e cumprimentou-o.

[[v9-13-11]]

^<<v9-13-11,11>>^ E Samuel perguntou-lhe: “O que é que fizeste?” Saul respondeu: “Vi que o povo estava a abandonar-me, que o senhor não chegava no prazo estabelecido e que os filisteus estavam a reunir-se em Micmás.

[[v9-13-12]]

^<<v9-13-12,12>>^ Por isso, eu disse para comigo: ‘Agora, os filisteus vêm contra mim, em Gilgal, e eu não procurei o favor^&#42;1^ de Jeová.’ Portanto, senti-me na obrigação de oferecer o sacrifício queimado.”

[NOTE]
====
. Ou: “não abrandei a face”.
====

[[v9-13-13]]

^<<v9-13-13,13>>^ Samuel disse então a Saul: “Agiste de modo insensato. Não obedeceste à ordem que Jeová, teu Deus, te deu. Se tivesses obedecido, Jeová teria estabelecido para sempre o teu reino sobre Israel.

[[v9-13-14]]

^<<v9-13-14,14>>^ Agora, porém, o teu reino não durará. Jeová encontrará um homem que agrade ao seu coração, e Jeová irá designá-lo como líder do seu povo, porque não obedeceste à ordem que Jeová te deu.”

[[v9-13-15]]

^<<v9-13-15,15>>^ Então, Samuel saiu de Gilgal e foi a Gibeá de Benjamim. E Saul fez a contagem dos homens; os que ainda estavam com ele eram cerca de 600.

[[v9-13-16]]

^<<v9-13-16,16>>^ Saul, o seu filho Jonatã e os homens que ainda estavam com eles ficaram em Geba de Benjamim. Os filisteus tinham-se acampado em Micmás.

[[v9-13-17]]

^<<v9-13-17,17>>^ E as tropas de ataque dos filisteus saíam do acampamento em três grupos. Um grupo ia pela estrada de Ofra, para a terra de Sual,

[[v9-13-18]]

^<<v9-13-18,18>>^ outro ia pela estrada de Bete-Horom, e o terceiro grupo ia pela estrada que vai dar ao limite do território que fica em frente ao vale de Zeboim, na direção do deserto.

[[v9-13-19]]

^<<v9-13-19,19>>^ Em toda a terra de Israel, já não havia nenhum ferreiro, porque os filisteus tinham dito: “Não deixemos os hebreus fabricarem espadas ou lanças.”

[[v9-13-20]]

^<<v9-13-20,20>>^ Por isso, todos os israelitas tinham de ir aos filisteus para afiar as relhas dos seus arados, as suas enxadas, os seus machados e as suas foices.

[[v9-13-21]]

^<<v9-13-21,21>>^ O preço para afiar as relhas de arado, as enxadas, as forquilhas e os machados, bem como para fixar a aguilhada, era de um pim.^&#42;1^

[NOTE]
====
. Um peso antigo de aproximadamente dois terços de um siclo.
====

[[v9-13-22]]

^<<v9-13-22,22>>^ Assim, no dia da batalha, nenhum dos que estavam com Saul e Jonatã tinha espada ou lança; apenas Saul e Jonatã, seu filho, tinham armas.

[[v9-13-23]]

^<<v9-13-23,23>>^ E um grupo de soldados filisteus^&#42;1^ tinha ido para o desfiladeiro de Micmás.

[NOTE]
====
. Ou: “um posto avançado dos filisteus”.
====

'''

xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[&#60; Capítulo Anterior] | <<v9-13-0,Topo>> | xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[Próximo Capítulo &#62;]