include::./index.adoc[]

[[v9-2-0]]
=== 1 Samuel, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-2-1]]

^<<v9-2-1,1>>^ Então, Ana disse em oração:
“O meu coração alegra-se em Jeová;
A minha força aumenta^&#42;1^ em Jeová.
A minha boca abre-se contra os meus inimigos,
Pois alegro-me nos teus atos de salvação.

[NOTE]
====
. Lit.: “O meu chifre é exaltado”. Veja o Glossário, “Chifre”.
====

[[v9-2-2]]

^<<v9-2-2,2>>^ Ninguém é santo como Jeová;
Não há outro além de ti,
E não há rocha igual ao nosso Deus.

[[v9-2-3]]

^<<v9-2-3,3>>^ Não continuem a falar de modo orgulhoso;
Não saiam da vossa boca palavras arrogantes,
Porque Jeová é um Deus de conhecimento,
E ele avalia corretamente as ações.

[[v9-2-4]]

^<<v9-2-4,4>>^ Os arcos dos fortes são partidos,
Mas os que tropeçam são fortalecidos.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os que estavam saciados têm de trabalhar pelo pão,
Mas os que estavam famintos já não passam fome.
A estéril deu à luz sete filhos,
Mas aquela que tinha muitos filhos ficou desolada.^&#42;1^

[NOTE]
====
. Lit.: “definhou”.
====

[[v9-2-6]]

^<<v9-2-6,6>>^ Jeová tira a vida e preserva a vida;^&#42;1^
Ele faz descer à Sepultura^&#42;2^ e dela faz subir.

[NOTE]
====
. Ou: “traz à vida”.
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v9-2-7]]

^<<v9-2-7,7>>^ Jeová faz empobrecer e faz enriquecer;
Ele rebaixa, e ele exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Ele levanta do pó o de condição humilde;
Do monte de cinzas^&#42;1^ ergue o pobre,
Para fazê-los sentar-se com os príncipes,
Dando-lhes um lugar de honra.
A Jeová pertencem os alicerces da terra,
E ele põe o solo produtivo sobre eles.

[NOTE]
====
. Ou, possivelmente: “depósito de lixo”.
====

[[v9-2-9]]

^<<v9-2-9,9>>^ Ele protege os passos dos que lhe são leais,
Mas os maus serão silenciados na escuridão,
Pois o homem não vence pela sua própria força.

[[v9-2-10]]

^<<v9-2-10,10>>^ Jeová destruirá os que lutam contra ele;^&#42;1^
Trovejará contra eles desde os céus.
Jeová julgará até aos confins da terra,
Dará poder ao seu rei
E aumentará a força^&#42;2^ do seu ungido.”

[NOTE]
====
. Ou, possivelmente: “Os que contendem com Jeová ficarão apavorados”.
. Lit.: “o chifre”. Veja o Glossário, “Chifre”.
====

[[v9-2-11]]

^<<v9-2-11,11>>^ Então, Elcana foi para a sua casa em Ramá, mas o menino tornou-se servo de Jeová perante Eli, o sacerdote.

[[v9-2-12]]

^<<v9-2-12,12>>^ Os filhos de Eli eram maus e não respeitavam a Jeová.

[[v9-2-13]]

^<<v9-2-13,13>>^ O que eles faziam com as porções que os sacerdotes tinham o direito de receber do povo era o seguinte: sempre que um homem oferecia um sacrifício, vinha um ajudante do sacerdote com um garfo de três pontas na mão, enquanto se cozinhava a carne,

[[v9-2-14]]

^<<v9-2-14,14>>^ e enfiava-o na panela, no tacho, no caldeirão ou na caçarola. O sacerdote ficava com tudo o que era tirado com o garfo. Era isso que faziam a todos os israelitas que iam a Silo.

[[v9-2-15]]

^<<v9-2-15,15>>^ Além disso, mesmo antes de o homem que oferecia o sacrifício queimar a gordura, vinha um ajudante do sacerdote e dizia-lhe: “Dá carne ao sacerdote para que ele a asse. Ele não aceitará que lhe dês carne cozida, só crua.”

[[v9-2-16]]

^<<v9-2-16,16>>^ Quando o homem lhe respondia: “Primeiro, deixa-os queimar a gordura; depois, leva tudo o que quiseres”,^&#42;1^ o ajudante dizia: “Não, dá-me já a carne; senão, vou tirá-la à força!”

[NOTE]
====
. Ou: “a tua alma desejar”.
====

[[v9-2-17]]

^<<v9-2-17,17>>^ Assim, o pecado dos ajudantes veio a ser muito grande perante Jeová, pois os homens tratavam a oferta de Jeová com desrespeito.

[[v9-2-18]]

^<<v9-2-18,18>>^ No entanto, Samuel prestava serviço perante Jeová, vestindo^&#42;1^ um éfode de linho, embora fosse apenas um menino.

[NOTE]
====
. Lit.: “cingido com”.
====

[[v9-2-19]]

^<<v9-2-19,19>>^ E a sua mãe fazia-lhe uma pequena túnica sem mangas e trazia-a todos os anos, quando subia com o seu marido para oferecer o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ E Eli abençoou Elcana e a sua esposa, e disse: “Que Jeová te conceda um filho por meio desta esposa, no lugar daquele que foi dado^&#42;1^ a Jeová.” E eles voltaram para casa.

[NOTE]
====
. Lit.: “emprestado”.
====

[[v9-2-21]]

^<<v9-2-21,21>>^ Jeová voltou a sua atenção para Ana, a fim de que ela pudesse engravidar; e ela deu à luz mais três filhos e duas filhas. E o menino Samuel continuava a crescer diante de Jeová.

[[v9-2-22]]

^<<v9-2-22,22>>^ Eli era muito idoso e tinha ouvido falar de tudo o que os seus filhos estavam a fazer a todo o Israel e de que eles se deitavam com as mulheres que prestavam serviço à entrada da tenda de reunião.

[[v9-2-23]]

^<<v9-2-23,23>>^ Ele dizia-lhes: “Porque é que continuam a fazer estas coisas? As coisas que ouço o povo dizer a vosso respeito são más.

[[v9-2-24]]

^<<v9-2-24,24>>^ Não, meus filhos, o que eu ouço dizer entre o povo de Jeová não é bom.

[[v9-2-25]]

^<<v9-2-25,25>>^ Se um homem pecar contra outro homem, alguém pode apelar a Jeová a favor dele;^&#42;1^ mas, se um homem pecar contra Jeová, quem é que poderá orar por ele?” Contudo, eles não queriam escutar o seu pai, pois Jeová tinha decidido entregá-los à morte.

[NOTE]
====
. Ou, possivelmente: “Deus arbitrará por ele”.
====

[[v9-2-26]]

^<<v9-2-26,26>>^ Enquanto isso, o menino Samuel continuava a crescer e tornava-se cada vez mais estimado, tanto por Jeová como pelo povo.

[[v9-2-27]]

^<<v9-2-27,27>>^ Um homem de Deus veio até Eli e disse-lhe: “Assim diz Jeová: ‘Por acaso, não me revelei claramente à casa do teu pai, enquanto estavam no Egito como escravos da casa do Faraó?

[[v9-2-28]]

^<<v9-2-28,28>>^ Ele foi escolhido dentre todas as tribos de Israel para servir como meu sacerdote e para subir ao meu altar, a fim de fazer sacrifícios, oferecer incenso^&#42;1^ e usar um éfode perante mim; e eu dei à casa do teu antepassado todas as ofertas feitas por fogo apresentadas pelos israelitas.^&#42;2^

[NOTE]
====
. Ou, possivelmente: “fazer subir fumo sacrificial”.
. Lit.: “filhos de Israel”.
====

[[v9-2-29]]

^<<v9-2-29,29>>^ Porque é que desprezam^&#42;1^ o meu sacrifício e a minha oferta, que ordenei que fossem feitos no meu lugar de morada? Porque é que persistes em honrar mais os teus filhos do que a mim, por se engordarem com as melhores porções de todas as ofertas do meu povo Israel?

[NOTE]
====
. Lit.: “chutam”.
====

[[v9-2-30]]

^<<v9-2-30,30>>^ “‘Por isso, esta é a palavra de Jeová, o Deus de Israel: “De facto, eu disse que a tua casa e a casa do teu antepassado andariam sempre diante de mim.” Agora, porém, Jeová diz: “Isso jamais acontecerá, porque honrarei os que me honrarem, mas os que me desprezarem serão tratados com desprezo.”

[[v9-2-31]]

^<<v9-2-31,31>>^ Estão a chegar os dias em que acabarei com o teu poder e com o poder^&#42;1^ da casa do teu pai, de modo que nenhum homem da tua casa chegará à velhice.

[NOTE]
====
. Lit.: “deceparei o teu braço e o braço”.
====

[[v9-2-32]]

^<<v9-2-32,32>>^ E, entre todo o bem que se faz a Israel, verás um rival na minha morada; nunca mais haverá nenhum homem idoso na tua casa.

[[v9-2-33]]

^<<v9-2-33,33>>^ O teu descendente que não for removido por mim do serviço no meu altar vai fazer com que os teus olhos falhem e vai causar-te desgosto,^&#42;1^ mas a maioria dos da tua casa morrerá pela espada dos homens.

[NOTE]
====
. Ou: “fazer com que a tua alma definhe”.
====

[[v9-2-34]]

^<<v9-2-34,34>>^ E o que acontecerá com os teus dois filhos, Hofni e Fineias, irá servir-te de sinal: ambos morrerão no mesmo dia.

[[v9-2-35]]

^<<v9-2-35,35>>^ Depois, farei surgir para mim um sacerdote fiel. Ele agirá de acordo com o desejo do meu coração.^&#42;1^ Vou edificar-lhe uma casa permanente, e ele andará sempre perante o meu ungido.

[NOTE]
====
. Ou: “com o que estiver no meu coração e na minha alma”.
====

[[v9-2-36]]

^<<v9-2-36,36>>^ Quem restar na casa de Eli há de vir e curvar-se perante ele para obter um pagamento em dinheiro e um pão, e dirá: “Por favor, dê-me um cargo sacerdotal, para que eu tenha um pedaço de pão para comer.”’”

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]