include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-30-1]]

^<<v9-30-1,1>>^ Quando David e os seus homens chegaram a Ziclague, no terceiro dia, os amalequitas tinham invadido o sul^&#42;1^ e Ziclague, e tinham atacado Ziclague, queimando-a com fogo.

[NOTE]
====
. Ou: “o Neguebe”.
====

[[v9-30-2]]

^<<v9-30-2,2>>^ Eles tinham levado as mulheres e todos os que estavam na cidade, desde o menor até ao maior. Foram-se embora e levaram-nos consigo, mas não mataram ninguém.

[[v9-30-3]]

^<<v9-30-3,3>>^ Quando David e os seus homens chegaram à cidade, viram que tinha sido queimada, e que as suas esposas, os seus filhos e as suas filhas tinham sido levados cativos.

[[v9-30-4]]

^<<v9-30-4,4>>^ Então, David e os seus homens começaram a chorar em voz alta, até não terem mais forças para chorar.

[[v9-30-5]]

^<<v9-30-5,5>>^ Também tinham sido levadas cativas as duas esposas de David: Ainoã, de Jezreel, e Abigail, viúva de Nabal, o carmelita.

[[v9-30-6]]

^<<v9-30-6,6>>^ David estava muito aflito, pois todos os homens^&#42;1^ tinham ficado muito amargurados por terem perdido os seus filhos e as suas filhas, e falavam em apedrejá-lo. Porém, David fortaleceu-se em Jeová, seu Deus.

[NOTE]
====
. Ou: “pois as almas de todo o povo”.
====

[[v9-30-7]]

^<<v9-30-7,7>>^ Por conseguinte, David disse a Abiatar, o sacerdote, filho de Aimeleque: “Por favor, traz aqui o éfode.” E Abiatar levou o éfode a David.

[[v9-30-8]]

^<<v9-30-8,8>>^ David consultou a Jeová: “Será que devo ir atrás deste bando de saqueadores? Será que consigo alcançá-los?” Ele respondeu: “Vai atrás deles, pois certamente vais alcançá-los e recuperar tudo o que foi levado.”

[[v9-30-9]]

^<<v9-30-9,9>>^ David e os 600 homens que estavam com ele partiram imediatamente. Quando chegaram ao vale^&#42;1^ de Besor, alguns deles ficaram por lá.

[NOTE]
====
. Ou: “uádi”. Veja o Glossário.
====

[[v9-30-10]]

^<<v9-30-10,10>>^ David continuou a perseguição com 400 homens, mas 200 homens ficaram para trás, pois estavam demasiado cansados para atravessar o vale de Besor.

[[v9-30-11]]

^<<v9-30-11,11>>^ Eles encontraram um egípcio no campo e levaram-no a David. Deram-lhe comida e água,

[[v9-30-12]]

^<<v9-30-12,12>>^ bem como uma fatia de torta de figos prensados e duas tortas de passas. Depois de comer, ele recuperou as forças,^&#42;1^ pois tinha passado três dias e três noites sem comer e sem beber.

[NOTE]
====
. Lit.: “o seu espírito voltou a ele”.
====

[[v9-30-13]]

^<<v9-30-13,13>>^ David perguntou-lhe: “A quem é que pertences e de onde és?” Ele respondeu: “Sou egípcio, escravo de um amalequita, mas o meu senhor abandonou-me, porque fiquei doente há três dias.

[[v9-30-14]]

^<<v9-30-14,14>>^ Nós atacámos o sul^&#42;1^ do território dos queretitas, o território de Judá e o sul^&#42;2^ do território de Caleb, e queimámos Ziclague com fogo.”

[NOTE]
====
. Ou: “o Neguebe”.
. Ou: “o Neguebe”.
====

[[v9-30-15]]

^<<v9-30-15,15>>^ Então, David perguntou-lhe: “Levas-me até esse bando de saqueadores?” Ele respondeu: “Se o senhor jurar por Deus que não me matará nem me entregará nas mãos do meu senhor, eu levo-o até ao bando de saqueadores.”

[[v9-30-16]]

^<<v9-30-16,16>>^ Assim, ele levou David até eles. Os amalequitas estavam espalhados por toda a região, a comer, a beber e a festejar por causa da grande quantidade de despojos que tinham tirado da terra dos filisteus e da terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ Então, David golpeou-os desde a madrugada até ao anoitecer;^&#42;1^ nenhum deles escapou, exceto 400 homens que fugiram montados em camelos.

[NOTE]
====
. Ou: “até ao anoitecer seguinte”.
====

[[v9-30-18]]

^<<v9-30-18,18>>^ David recuperou tudo o que os amalequitas tinham levado e libertou as suas duas esposas.

[[v9-30-19]]

^<<v9-30-19,19>>^ Não ficou a faltar nada nem ninguém, desde o menor até ao maior. Eles recuperaram os filhos, as filhas e o despojo. David recuperou tudo o que tinha sido levado.

[[v9-30-20]]

^<<v9-30-20,20>>^ E David levou todas as ovelhas e bois, e os seus homens conduziram-nos à frente dos seus próprios animais, e disseram: “Este é o despojo de David.”

[[v9-30-21]]

^<<v9-30-21,21>>^ Seguidamente, David retornou aos 200 homens que tinham ficado demasiado cansados para acompanhá-lo e que tinham ficado para trás, junto ao vale de Besor. Eles vieram ao encontro de David e dos que estavam com ele. Ao aproximar-se deles, David perguntou-lhes como estavam.

[[v9-30-22]]

^<<v9-30-22,22>>^ No entanto, alguns homens maus e imprestáveis que tinham ido com David disseram: “Visto que eles não foram connosco, não lhes daremos nada do despojo que recuperámos. Que cada um deles leve apenas a sua esposa e os seus filhos e que se vá embora.”

[[v9-30-23]]

^<<v9-30-23,23>>^ No entanto, David disse: “Meus irmãos, não façam isso com o que Jeová nos deu. Ele protegeu-nos e entregou-nos nas mãos o bando de saqueadores que veio contra nós.

[[v9-30-24]]

^<<v9-30-24,24>>^ Quem é que concordaria com o que vocês estão a dizer? A parte de quem foi à batalha será igual à de quem ficou com a bagagem. Todos receberão uma parte do despojo.”

[[v9-30-25]]

^<<v9-30-25,25>>^ Daquele dia em diante, David estabeleceu isto como um decreto e uma norma para Israel, até hoje.

[[v9-30-26]]

^<<v9-30-26,26>>^ Quando David voltou a Ziclague, enviou parte do despojo aos anciãos de Judá que eram seus amigos, com a seguinte mensagem: “Este é um presente^&#42;1^ para vocês, tirado do despojo dos inimigos de Jeová.”

[NOTE]
====
. Lit.: “Esta é uma bênção”.
====

[[v9-30-27]]

^<<v9-30-27,27>>^ Ele enviou o presente aos que estavam em Betel, em Ramote do Neguebe,^&#42;1^ em Jatir,

[NOTE]
====
. Ou: “do sul”.
====

[[v9-30-28]]

^<<v9-30-28,28>>^ em Aroer, em Sifmote, em Estemoa,

[[v9-30-29]]

^<<v9-30-29,29>>^ em Racal, nas cidades dos jerameelitas, nas cidades dos queneus,

[[v9-30-30]]

^<<v9-30-30,30>>^ em Hormá, em Borasã, em Ataque,

[[v9-30-31]]

^<<v9-30-31,31>>^ em Hébron e em todos os lugares onde David e os seus homens tinham estado.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]