include::./index.adoc[]

[[v9-10-0]]
=== 1 Samuel, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-10-1]]

^<<v9-10-1,1>>^ Samuel pegou, então, num frasco de óleo, derramou-o sobre a cabeça de Saul, beijou-o e disse-lhe: “Jeová ungiu-te como líder sobre a sua herança.

[[v9-10-2]]

^<<v9-10-2,2>>^ Hoje, quando te fores embora, encontrarás dois homens perto do túmulo de Raquel, no território de Benjamim, em Zelza. Eles vão dizer-te: ‘As jumentas de que estavas à procura foram encontradas, mas o teu pai já se esqueceu do assunto das jumentas e, agora, está preocupado convosco. Ele pergunta: “Como é que vou encontrar o meu filho?”’

[[v9-10-3]]

^<<v9-10-3,3>>^ Depois, segue em frente até chegares à árvore grande de Tabor. Lá encontrarás três homens a subir para Betel, a fim de adorar o verdadeiro Deus: um leva três cabritos, outro leva três pães e ainda outro leva um grande odre de vinho.

[[v9-10-4]]

^<<v9-10-4,4>>^ Eles vão cumprimentar-te e dar-te dois pães; aceita os pães que te derem.

[[v9-10-5]]

^<<v9-10-5,5>>^ Depois disso, chegarás à colina do verdadeiro Deus, onde há um grupo de soldados filisteus. Quando chegares à cidade, encontrarás um grupo de profetas a descer do alto sagrado e a profetizar, e, à sua frente, pessoas a tocar instrumentos de cordas, pandeiretas, flautas e harpas.

[[v9-10-6]]

^<<v9-10-6,6>>^ O espírito de Jeová vai dar-te poder, e profetizarás com eles e hás de tornar-te outra pessoa.

[[v9-10-7]]

^<<v9-10-7,7>>^ Quando estes sinais ocorrerem, faz tudo o que puderes, porque o verdadeiro Deus está contigo.

[[v9-10-8]]

^<<v9-10-8,8>>^ A seguir, desce à minha frente até Gilgal. Vou-me encontrar lá contigo para oferecer sacrifícios queimados e sacrifícios de participação em comum. Deves esperar durante sete dias, até que eu chegue. Depois, irei dizer-te o que deves fazer.”

[[v9-10-9]]

^<<v9-10-9,9>>^ Assim que Saul se virou para se afastar de Samuel, Deus começou a mudar o coração de Saul; e, naquele dia, cumpriram-se todos estes sinais.

[[v9-10-10]]

^<<v9-10-10,10>>^ Então, foram dali à colina, e um grupo de profetas veio ao seu encontro. Imediatamente, o espírito de Deus deu-lhe poder, de modo que começou a profetizar entre eles.

[[v9-10-11]]

^<<v9-10-11,11>>^ Quando todos os que o conheciam o viram a profetizar com os profetas, disseram uns aos outros: “O que é que aconteceu ao filho de Quis? Será que Saul também está entre os profetas?”

[[v9-10-12]]

^<<v9-10-12,12>>^ Portanto, um homem local disse: “Mas quem é o pai deles?” Foi assim que surgiu o seguinte ditado:^&#42;1^ “Será que Saul também está entre os profetas?”

[NOTE]
====
. Ou: “provérbio”.
====

[[v9-10-13]]

^<<v9-10-13,13>>^ Quando ele terminou de profetizar, foi até ao alto sagrado.

[[v9-10-14]]

^<<v9-10-14,14>>^ Mais tarde, o irmão do pai de Saul perguntou-lhe a ele e ao ajudante: “Onde é que foram?” Saul respondeu: “Fomos procurar as jumentas, mas não as encontrámos. Por isso, fomos falar com Samuel.”

[[v9-10-15]]

^<<v9-10-15,15>>^ O tio de Saul perguntou-lhe: “O que é que Samuel vos disse? Por favor, digam-me.”

[[v9-10-16]]

^<<v9-10-16,16>>^ Saul respondeu ao seu tio: “Ele disse-nos que as jumentas tinham sido encontradas.” Todavia, Saul não lhe contou o que Samuel tinha dito sobre o assunto do reinado.

[[v9-10-17]]

^<<v9-10-17,17>>^ Então, Samuel reuniu o povo perante Jeová em Mispá

[[v9-10-18]]

^<<v9-10-18,18>>^ e disse aos israelitas: “Assim diz Jeová, o Deus de Israel: ‘Fui eu que tirei Israel do Egito e que vos livrei das mãos do Egito e das mãos de todos os reinos que vos oprimiam.

[[v9-10-19]]

^<<v9-10-19,19>>^ No entanto, hoje, vocês rejeitaram o vosso Deus que vos salvou de todos os vossos males e aflições, e disseram: “Não! Designe um rei sobre nós.” Agora, tomem a vossa posição perante Jeová, segundo as vossas tribos e segundo os vossos milhares.’”^&#42;1^

[NOTE]
====
. Ou: “clãs”.
====

[[v9-10-20]]

^<<v9-10-20,20>>^ Assim, Samuel providenciou que todas as tribos de Israel se aproximassem, e foi escolhida a tribo de Benjamim.

[[v9-10-21]]

^<<v9-10-21,21>>^ De seguida, providenciou que a tribo de Benjamim viesse à frente, segundo as suas famílias, e foi escolhida a família dos matritas. Finalmente, foi escolhido Saul, filho de Quis. Porém, quando foram procurá-lo, não o encontraram em lado nenhum.

[[v9-10-22]]

^<<v9-10-22,22>>^ Por isso, consultaram a Jeová: “O homem já está aqui?” Jeová respondeu: “Está ali, escondido no meio da bagagem.”

[[v9-10-23]]

^<<v9-10-23,23>>^ Assim, foram a correr e trouxeram-no de lá. Quando ele ficou no meio do povo, era o mais alto de todos; os outros só lhe davam pelo ombro.

[[v9-10-24]]

^<<v9-10-24,24>>^ Samuel disse a todo o povo: “Vejam aquele que Jeová escolheu! Não há ninguém igual a ele entre todo o povo.” E todo o povo começou a gritar: “Viva o rei!”

[[v9-10-25]]

^<<v9-10-25,25>>^ Samuel falou ao povo sobre os direitos dos reis e escreveu-os num livro, que colocou perante Jeová. Depois, Samuel mandou que todos voltassem para casa.

[[v9-10-26]]

^<<v9-10-26,26>>^ Saul também foi para a sua casa em Gibeá, acompanhado por guerreiros cujo coração tinha sido tocado por Jeová.

[[v9-10-27]]

^<<v9-10-27,27>>^ No entanto, alguns homens imprestáveis disseram: “Como é que este homem nos vai salvar?” Assim, desprezaram-no e não lhe deram nenhum presente. Contudo, ele não disse nada.^&#42;1^

[NOTE]
====
. Lit.: “E ele era como alguém sem fala.”
====

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]