include::./index.adoc[]

[[v9-19-0]]
=== 1 Samuel, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-19-1]]

^<<v9-19-1,1>>^ Mais tarde, Saul comunicou a sua intenção de matar David a Jonatã, seu filho, e a todos os seus servos.

[[v9-19-2]]

^<<v9-19-2,2>>^ Visto que Jonatã, filho de Saul, gostava muito de David, Jonatã contou-lhe: “Saul, meu pai, quer que sejas morto. Amanhã cedo, tem cuidado; vai para um lugar secreto e esconde-te.

[[v9-19-3]]

^<<v9-19-3,3>>^ Irei com o meu pai ao campo, perto de onde estiveres. Falarei com o meu pai a teu respeito, e, se eu souber de alguma coisa, conto-te depois.”

[[v9-19-4]]

^<<v9-19-4,4>>^ Então, Jonatã falou bem de David a Saul, seu pai. Ele disse-lhe: “O rei não deve pecar contra o seu servo David, pois ele não pecou contra ti. Pelo contrário, o que ele fez por ti foi muito bom.

[[v9-19-5]]

^<<v9-19-5,5>>^ Ele arriscou a vida^&#42;1^ para matar o filisteu, de modo que Jeová deu uma grande vitória^&#42;2^ a todo o Israel. Tu viste isso e ficaste muito contente. Assim, porquê pecar contra sangue inocente, fazendo com que David seja morto sem nenhum motivo?”

[NOTE]
====
. Ou: “pôs a sua alma na mão”.
. Ou: “salvação”.
====

[[v9-19-6]]

^<<v9-19-6,6>>^ Saul escutou Jonatã e jurou: “Tão certo como Jeová vive, ele não será morto.”

[[v9-19-7]]

^<<v9-19-7,7>>^ Depois, Jonatã chamou David e contou-lhe todas estas coisas. Então, Jonatã levou David até Saul, e David voltou a servir Saul, assim como o fazia antes.

[[v9-19-8]]

^<<v9-19-8,8>>^ Com o tempo, houve novamente uma guerra. David saiu para lutar contra os filisteus e matou um grande número deles; e os filisteus fugiram da sua frente.

[[v9-19-9]]

^<<v9-19-9,9>>^ E um espírito mau da parte de Jeová veio sobre Saul. Ele estava sentado em casa com uma lança na mão, enquanto David tocava harpa.

[[v9-19-10]]

^<<v9-19-10,10>>^ Saul tentou espetar David na parede com a lança, mas ele desviou-se, de modo que a lança foi espetar-se na parede. Naquela noite, David fugiu.

[[v9-19-11]]

^<<v9-19-11,11>>^ Mais tarde, Saul enviou mensageiros à casa de David para que a vigiassem e para que o matassem pela manhã, mas Mical, esposa de David, disse-lhe: “Se não fugires^&#42;1^ esta noite, amanhã serás um homem morto.”

[NOTE]
====
. Ou: “Se não deixares a tua alma escapar”.
====

[[v9-19-12]]

^<<v9-19-12,12>>^ Imediatamente, Mical ajudou David a descer pela janela, para que ele pudesse fugir.

[[v9-19-13]]

^<<v9-19-13,13>>^ Mical pegou no ídolo doméstico^&#42;1^ e colocou-o na cama, pôs uma rede de pelos de cabra no lugar onde David deitava a cabeça e cobriu o ídolo com uma roupa.

[NOTE]
====
. Ou: “deus doméstico”. Lit.: “terafim”.
====

[[v9-19-14]]

^<<v9-19-14,14>>^ De seguida, Saul enviou mensageiros para que lhe trouxessem David, mas ela disse: “Ele está doente.”

[[v9-19-15]]

^<<v9-19-15,15>>^ Portanto, Saul enviou os mensageiros de volta para verem David e disse-lhes: “Tragam-no aqui na sua cama, para que ele seja morto.”

[[v9-19-16]]

^<<v9-19-16,16>>^ Ao entrarem, os mensageiros encontraram na cama o ídolo doméstico^&#42;1^ e uma rede de pelos de cabra no lugar onde estaria a cabeça de David.

[NOTE]
====
. Ou: “deus doméstico”. Lit.: “terafim”.
====

[[v9-19-17]]

^<<v9-19-17,17>>^ Em vista disso, Saul perguntou a Mical: “Porque é que me enganaste desta forma e ajudaste o meu inimigo a escapar?” Mical respondeu: “Ele disse-me que me mataria, se eu não o ajudasse a fugir.”

[[v9-19-18]]

^<<v9-19-18,18>>^ Entretanto, David tinha fugido e encontrou-se com Samuel em Ramá. Contou-lhe tudo o que Saul lhe tinha feito. Então, ele e Samuel foram-se embora para Naiote e ficaram por lá.

[[v9-19-19]]

^<<v9-19-19,19>>^ Com o tempo, Saul foi informado: “David está em Naiote, em Ramá.”

[[v9-19-20]]

^<<v9-19-20,20>>^ Saul enviou imediatamente mensageiros para capturarem David. Quando eles viram os profetas mais velhos a profetizar e Samuel a liderá-los, o espírito de Deus veio sobre os mensageiros de Saul, e eles também começaram a comportar-se como profetas.

[[v9-19-21]]

^<<v9-19-21,21>>^ Quando Saul soube disso, enviou imediatamente outros mensageiros, mas eles também começaram a comportar-se como profetas. Então, Saul enviou um terceiro grupo de mensageiros, e eles também começaram a comportar-se como profetas.

[[v9-19-22]]

^<<v9-19-22,22>>^ Por fim, ele foi pessoalmente a Ramá. Quando chegou à grande cisterna em Seco, ele perguntou: “Onde é que estão Samuel e David?” Responderam-lhe: “Em Naiote, em Ramá.”

[[v9-19-23]]

^<<v9-19-23,23>>^ Enquanto Saul ia a caminho de Naiote, em Ramá, o espírito de Deus veio também sobre ele, e ele continuou a andar e a comportar-se como profeta, até chegar a Naiote, em Ramá.

[[v9-19-24]]

^<<v9-19-24,24>>^ Também ele tirou a roupa e comportou-se como profeta perante Samuel, e ficou ali deitado, nu,^&#42;1^ durante todo o dia e toda a noite. É por isso que se diz: “Será que Saul também está entre os profetas?”

[NOTE]
====
. Ou: “pouco vestido”.
====

'''

xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[&#60; Capítulo Anterior] | <<v9-19-0,Topo>> | xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[Próximo Capítulo &#62;]