include::./index.adoc[]

[[v9-3-0]]
=== 1 Samuel, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-3-1]]

^<<v9-3-1,1>>^ Entretanto, o menino Samuel servia a Jeová perante Eli. Contudo, a palavra de Jeová tinha-se tornado rara naqueles dias; as visões não eram frequentes.

[[v9-3-2]]

^<<v9-3-2,2>>^ Certo dia, Eli estava deitado no lugar do costume, e a sua vista já estava fraca; ele não conseguia ver.

[[v9-3-3]]

^<<v9-3-3,3>>^ A lâmpada de Deus ainda não se tinha apagado, e Samuel estava deitado no templo^&#42;1^ de Jeová, onde se encontrava a Arca de Deus.

[NOTE]
====
. Isto é, no tabernáculo.
====

[[v9-3-4]]

^<<v9-3-4,4>>^ Então, Jeová chamou Samuel. Ele respondeu: “Estou aqui.”

[[v9-3-5]]

^<<v9-3-5,5>>^ Ele correu até Eli e disse-lhe: “Estou aqui. Chamou-me?” Ele disse: “Não te chamei. Volta a deitar-te.” Portanto, ele foi e deitou-se.

[[v9-3-6]]

^<<v9-3-6,6>>^ Jeová chamou-o novamente: “Samuel!” Por conseguinte, Samuel levantou-se e foi até Eli, e disse-lhe: “Estou aqui, porque me chamou.” Porém, ele disse: “Não te chamei, meu filho. Volta a deitar-te.”

[[v9-3-7]]

^<<v9-3-7,7>>^ (Samuel ainda não conhecia a Jeová, e a palavra de Jeová ainda não lhe tinha sido revelada.)

[[v9-3-8]]

^<<v9-3-8,8>>^ E, pela terceira vez, Jeová chamou novamente: “Samuel!” Assim, ele levantou-se, foi até Eli e disse-lhe: “Estou aqui, uma vez que me chamou.”
Então, Eli deu-se conta de que era Jeová que estava a chamar o menino.

[[v9-3-9]]

^<<v9-3-9,9>>^ Por isso, Eli disse a Samuel: “Vai-te deitar. Se ele te chamar outra vez, diz: ‘Fala, Jeová, pois o teu servo está a ouvir.’” E Samuel foi deitar-se no seu lugar.

[[v9-3-10]]

^<<v9-3-10,10>>^ Jeová veio, colocou-se ali e chamou-o como das outras vezes: “Samuel, Samuel!” E Samuel disse: “Podes falar, pois o teu servo está a ouvir.”

[[v9-3-11]]

^<<v9-3-11,11>>^ Jeová disse a Samuel: “Vou fazer uma coisa em Israel que fará tinir os ouvidos de^&#42;1^ quem ouvir algo a esse respeito.

[NOTE]
====
. Ou: “que deixará horrorizado”.
====

[[v9-3-12]]

^<<v9-3-12,12>>^ Nesse dia, trarei contra Eli tudo o que disse a respeito da sua casa, do princípio ao fim.

[[v9-3-13]]

^<<v9-3-13,13>>^ Diz-lhe que vou executar um julgamento definitivo contra a sua casa, pelo erro que ele bem sabe qual é, pois os seus filhos estão a amaldiçoar a Deus e ele não os repreende.

[[v9-3-14]]

^<<v9-3-14,14>>^ Foi por isso que jurei à casa de Eli que o erro da casa de Eli nunca será expiado com sacrifícios ou com ofertas.”

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel ficou deitado até de manhã. Abriu, então, as portas da casa de Jeová. Samuel estava com medo de contar a Eli a visão que tinha tido.

[[v9-3-16]]

^<<v9-3-16,16>>^ Contudo, Eli chamou Samuel: “Samuel, meu filho!” Ele respondeu: “Estou aqui.”

[[v9-3-17]]

^<<v9-3-17,17>>^ Eli perguntou: “O que é que ele te disse? Por favor, não me escondas nada. Que Deus te castigue, e que o faça severamente, se me esconderes uma só palavra de tudo o que ele te disse.”

[[v9-3-18]]

^<<v9-3-18,18>>^ Portanto, Samuel contou-lhe tudo e não lhe escondeu nada. Eli disse: “É Jeová. Que ele faça o que for bom aos seus olhos.”

[[v9-3-19]]

^<<v9-3-19,19>>^ Samuel continuou a crescer, e o próprio Jeová estava com ele e não permitiu que nenhuma de todas as suas palavras se deixasse de cumprir.^&#42;1^

[NOTE]
====
. Lit.: “caísse por terra”.
====

[[v9-3-20]]

^<<v9-3-20,20>>^ Todo o Israel, desde Dã até Berseba, percebeu que Samuel tinha sido escolhido como profeta de Jeová.

[[v9-3-21]]

^<<v9-3-21,21>>^ E Jeová continuou a aparecer em Silo, pois foi em Silo que Jeová se revelou a Samuel, por meio da palavra de Jeová.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]