include::./index.adoc[]

[[v9-15-0]]
=== 1 Samuel, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-15-1]]

^<<v9-15-1,1>>^ Samuel disse a Saul: “Jeová enviou-me para ungir-te rei sobre o seu povo, Israel. Agora, escuta o que Jeová tem para dizer.

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim diz Jeová dos exércitos: ‘Ajustarei contas com os amalequitas pelo que fizeram a Israel quando se opuseram aos israelitas no caminho, quando estes saíam do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Vai, agora, derrota os amalequitas e entrega-os à destruição,^&#42;1^ com tudo o que eles têm. Não os poupes;^&#42;2^ mata homens e mulheres, crianças e bebés, bois e ovelhas, camelos e jumentos.’”

[NOTE]
====
. Ou: “devota-os à destruição”. Veja o Glossário.
. Ou: “Não tenhas compaixão deles”.
====

[[v9-15-4]]

^<<v9-15-4,4>>^ Saul convocou o exército^&#42;1^ e contou-o em Telaim: havia 200 000 soldados^&#42;2^ e 10 000 homens de Judá.

[NOTE]
====
. Ou: “povo”.
. Ou: “soldados a pé”.
====

[[v9-15-5]]

^<<v9-15-5,5>>^ Saul avançou até à cidade de Amaleque e armou uma emboscada junto ao vale.^&#42;1^

[NOTE]
====
. Ou: “uádi”.
====

[[v9-15-6]]

^<<v9-15-6,6>>^ Saul disse então aos queneus: “Retirem-se, saiam do meio dos amalequitas, para que eu não vos destrua com eles. Pois vocês demonstraram amor leal para com todo o povo de Israel, quando eles saíram do Egito.” Portanto, os queneus retiraram-se do meio de Amaleque.

[[v9-15-7]]

^<<v9-15-7,7>>^ Depois disso, Saul golpeou os amalequitas desde Havilá até Sur, que fica junto ao Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ Ele capturou vivo Agague, rei de Amaleque, mas entregou o restante do povo à destruição^&#42;1^ com a espada.

[NOTE]
====
. Ou: “devotou...à destruição”. Veja o Glossário.
====

[[v9-15-9]]

^<<v9-15-9,9>>^ No entanto, Saul e o povo pouparam^&#42;1^ Agague e o melhor das ovelhas e dos bois, os mais gordos, e também os carneiros e tudo o que era bom. Não quiseram entregá-los à destruição. Porém, quanto a todos os bens que eram inúteis e indesejáveis, entregaram-nos à destruição.

[NOTE]
====
. Ou: “tiveram compaixão de”.
====

[[v9-15-10]]

^<<v9-15-10,10>>^ De seguida, Samuel recebeu a seguinte palavra de Jeová:

[[v9-15-11]]

^<<v9-15-11,11>>^ “Lamento^&#42;1^ ter feito de Saul rei, pois ele deixou de me seguir e não cumpriu as minhas palavras.” Samuel sentiu-se muito aflito, e clamou a Jeová a noite inteira.

[NOTE]
====
. Ou: “Sinto pesar de”.
====

[[v9-15-12]]

^<<v9-15-12,12>>^ Quando Samuel se levantou de manhã cedo para se encontrar com Saul, foi informado: “Saul foi a Carmelo e construiu lá um monumento em sua própria honra. Depois, partiu e voltou a Gilgal.”

[[v9-15-13]]

^<<v9-15-13,13>>^ Quando Samuel finalmente se encontrou com ele, Saul disse-lhe: “Que Jeová o abençoe. Eu cumpri a ordem de Jeová.”

[[v9-15-14]]

^<<v9-15-14,14>>^ Todavia, Samuel disse: “Então, porque é que estou a ouvir o barulho de ovelhas e de bois?”

[[v9-15-15]]

^<<v9-15-15,15>>^ Saul respondeu: “Foram tirados aos amalequitas, pois o povo poupou o^&#42;1^ melhor dos rebanhos e das manadas para sacrificá-los a Jeová, seu Deus; mas o que sobrou foi entregue à destruição.”^&#42;2^

[NOTE]
====
. Ou: “teve compaixão do”.
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v9-15-16]]

^<<v9-15-16,16>>^ Posto isto, Samuel disse a Saul: “Já chega! Vou dizer-te o que Jeová me disse na noite passada.” E ele disse: “Fale!”

[[v9-15-17]]

^<<v9-15-17,17>>^ Samuel continuou: “Não te consideravas insignificante quando te tornaste cabeça das tribos de Israel e quando Jeová te ungiu rei sobre Israel?

[[v9-15-18]]

^<<v9-15-18,18>>^ Mais tarde, Jeová enviou-te numa missão e disse: ‘Vai, entrega os amalequitas pecadores à destruição. Luta contra eles até os exterminares.’

[[v9-15-19]]

^<<v9-15-19,19>>^ Então, porque é que não obedeceste à voz de Jeová? Em vez de obedeceres, avançaste gananciosamente sobre o despojo e fizeste o que era mau aos olhos de Jeová!”

[[v9-15-20]]

^<<v9-15-20,20>>^ No entanto, Saul disse a Samuel: “Mas eu obedeci à voz de Jeová! Fui na missão para a qual Jeová me enviou, trouxe Agague, rei de Amaleque, e entreguei os amalequitas à destruição.

[[v9-15-21]]

^<<v9-15-21,21>>^ Mas os homens tiraram ovelhas e bois do despojo, o melhor do que tinha sido condenado à destruição, para sacrificarem a Jeová, seu Deus, em Gilgal.”

[[v9-15-22]]

^<<v9-15-22,22>>^ Samuel disse então: “Será que Jeová tem tanto prazer em ofertas queimadas e sacrifícios como em que se obedeça à voz de Jeová? Pois fica a saber que obedecer é melhor do que um sacrifício, e prestar atenção é melhor do que a gordura de carneiros;

[[v9-15-23]]

^<<v9-15-23,23>>^ porque a rebeldia é igual ao pecado da adivinhação, e a presunção é igual ao uso de poder mágico e idolatria.^&#42;1^ Visto que rejeitaste a palavra de Jeová, ele também te rejeitou como rei.”

[NOTE]
====
. Lit.: “terafins”, isto é, deuses domésticos; ídolos.
====

[[v9-15-24]]

^<<v9-15-24,24>>^ De seguida, Saul disse a Samuel: “Pequei, pois desobedeci à ordem de Jeová e às instruções que o senhor me deu, porque fiquei com medo do povo e fiz o que eles queriam.

[[v9-15-25]]

^<<v9-15-25,25>>^ E agora, por favor, perdoe-me o meu pecado e volte comigo, para que eu me curve perante Jeová.”

[[v9-15-26]]

^<<v9-15-26,26>>^ Contudo, Samuel disse a Saul: “Não voltarei contigo, pois rejeitaste a palavra de Jeová, e Jeová rejeitou-te como rei de Israel.”

[[v9-15-27]]

^<<v9-15-27,27>>^ Quando Samuel se virou para se ir embora, Saul agarrou a barra da sua túnica sem mangas, mas esta rasgou-se.

[[v9-15-28]]

^<<v9-15-28,28>>^ Então, Samuel disse-lhe: “Hoje, Jeová arrancou-te o reino de Israel, e ele vai dá-lo ao teu próximo, que é melhor do que tu.

[[v9-15-29]]

^<<v9-15-29,29>>^ Além disso, o Glorioso de Israel não deixará de cumprir a sua palavra nem mudará de ideias,^&#42;1^ pois Ele não é um homem para mudar de ideias.”^&#42;2^

[NOTE]
====
. Ou: “lamentará”.
. Ou: “lamentar”.
====

[[v9-15-30]]

^<<v9-15-30,30>>^ Portanto, ele disse: “Pequei. Mas, por favor, honre-me diante dos anciãos do meu povo e diante de Israel. Volte comigo, e eu vou curvar-me perante Jeová, seu Deus.”

[[v9-15-31]]

^<<v9-15-31,31>>^ Assim, Samuel voltou com Saul, e Saul curvou-se perante Jeová.

[[v9-15-32]]

^<<v9-15-32,32>>^ E Samuel disse: “Tragam-me Agague, rei de Amaleque.” Então, Agague chegou até ele com relutância,^&#42;1^ pois tinha dito para consigo: ‘Com certeza, o risco de^&#42;2^ morte já passou.’

[NOTE]
====
. Ou, possivelmente: “confiança”.
. Lit.: “a amargura da”.
====

[[v9-15-33]]

^<<v9-15-33,33>>^ No entanto, Samuel disse: “Assim como a tua espada deixou muitas mulheres sem filhos, a tua mãe também ficará sem filhos.” De seguida, Samuel cortou Agague aos pedaços perante Jeová, em Gilgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Depois, Samuel foi para Ramá e Saul foi para a sua casa em Gibeá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ Samuel não voltou a ver Saul até ao dia da sua morte, pois Samuel ficou muito triste por causa de Saul. E Jeová lamentou ter feito de Saul rei de Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]