include::./index.adoc[]

[[v9-26-0]]
=== 1 Samuel, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-26-1]]

^<<v9-26-1,1>>^ Com o tempo, os homens de Zife foram até Saul, em Gibeá, e disseram-lhe: “David está escondido na colina de Haquilá, que fica em frente a Jesimom.”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “ao deserto; ao ermo”.
====

[[v9-26-2]]

^<<v9-26-2,2>>^ Então, Saul desceu ao deserto de Zife com 3000 dos melhores soldados de Israel, a fim de procurar David.

[[v9-26-3]]

^<<v9-26-3,3>>^ Saul acampou na colina de Haquilá, que fica em frente a Jesimom, perto da estrada. David estava então a viver no deserto e soube que Saul tinha vindo atrás dele no deserto.

[[v9-26-4]]

^<<v9-26-4,4>>^ Portanto, David enviou espiões para verificar se Saul tinha realmente vindo.

[[v9-26-5]]

^<<v9-26-5,5>>^ Mais tarde, David foi ao lugar onde Saul estava acampado e viu onde Saul e Abner, filho de Ner, chefe do seu exército, estavam a dormir. Saul dormia no acampamento, e os soldados estavam acampados à sua volta.

[[v9-26-6]]

^<<v9-26-6,6>>^ Então, David perguntou a Aimeleque, o hitita, e a Abisai, filho de Zeruia e irmão de Joabe: “Quem é que vai comigo ao acampamento, até Saul?” Abisai respondeu: “Eu vou contigo.”

[[v9-26-7]]

^<<v9-26-7,7>>^ Assim, David e Abisai entraram no acampamento de noite e encontraram Saul a dormir, com a lança espetada no chão perto da sua cabeça; Abner e os soldados estavam deitados à sua volta.

[[v9-26-8]]

^<<v9-26-8,8>>^ Abisai disse então a David: “Hoje, Deus entregou-te o teu inimigo nas tuas mãos. E agora, deixa-me espetá-lo no chão com a lança. Vou dar-lhe um único golpe, não precisarei de outro.”

[[v9-26-9]]

^<<v9-26-9,9>>^ No entanto, David disse a Abisai: “Não lhe faças nenhum mal, pois quem é que pode levantar a mão contra o ungido de Jeová e ficar inocente?”

[[v9-26-10]]

^<<v9-26-10,10>>^ David acrescentou: “Tão certo como Jeová vive, o próprio Jeová há de matá-lo, ou virá o dia em que ele morrerá ou, então, irá para uma batalha e será morto.

[[v9-26-11]]

^<<v9-26-11,11>>^ Por respeito a Jeová, eu jamais levantaria a minha mão contra o ungido de Jeová! Portanto, peguemos agora na lança e na bilha de água que estão junto à sua cabeça e vamos embora.”

[[v9-26-12]]

^<<v9-26-12,12>>^ Assim, David pegou na lança e na bilha de água que estavam junto à cabeça de Saul, e eles foram-se embora. Ninguém os viu nem se apercebeu da sua presença, nem acordou. Todos estavam a dormir, porque Jeová tinha feito com que eles caíssem num sono profundo.

[[v9-26-13]]

^<<v9-26-13,13>>^ Então, David foi para o outro lado e permaneceu de pé no cume do monte, a uma boa distância deles.

[[v9-26-14]]

^<<v9-26-14,14>>^ David gritou aos soldados e a Abner, filho de Ner: “Abner, estás a ouvir-me?” Abner respondeu: “Quem é que está a gritar para o rei?”

[[v9-26-15]]

^<<v9-26-15,15>>^ David disse a Abner: “Não és homem? E quem é que é igual a ti em Israel? Então, porque é que não vigiaste o teu senhor, o rei? Pois um dos soldados entrou no acampamento para matar o teu senhor, o rei.

[[v9-26-16]]

^<<v9-26-16,16>>^ O que fizeste não é bom. Tão certo como Jeová vive, vocês merecem morrer, porque não vigiaram o vosso senhor, o ungido de Jeová. Agora, olha em volta! Onde é que estão a lança do rei e a bilha de água que estavam junto à sua cabeça?”

[[v9-26-17]]

^<<v9-26-17,17>>^ Então, Saul reconheceu a voz de David e perguntou: “És tu, meu filho David?” David respondeu: “Sim, sou eu, meu senhor, o rei.”

[[v9-26-18]]

^<<v9-26-18,18>>^ Ele acrescentou: “Porque é que o senhor está a perseguir o seu servo? O que é que eu fiz? De que é que eu sou culpado?

[[v9-26-19]]

^<<v9-26-19,19>>^ Por favor, meu senhor, o rei, escute as palavras do seu servo: Se foi Jeová quem o instigou contra mim, que ele aceite^&#42;1^ a minha oferta de cereais. Mas, se foram homens que o instigaram, malditos sejam eles perante Jeová, porque me expulsaram, não permitindo que eu participasse da herança de Jeová, e disseram: ‘Vai, serve outros deuses!’

[NOTE]
====
. Lit.: “cheire”.
====

[[v9-26-20]]

^<<v9-26-20,20>>^ E agora, não permita que o meu sangue seja derramado no chão, longe da presença de Jeová, pois o rei de Israel saiu à procura de uma simples pulga, como se estivesse a caçar uma perdiz nos montes.”

[[v9-26-21]]

^<<v9-26-21,21>>^ Então, Saul disse: “Pequei. Volta, meu filho David, não voltarei a fazer-te mal, porque hoje consideraste a minha vida^&#42;1^ preciosa. Eu realmente agi como um tolo e cometi um grande erro.”

[NOTE]
====
. Ou: “alma”.
====

[[v9-26-22]]

^<<v9-26-22,22>>^ David disse: “Aqui está a lança do rei. Mande um dos homens vir buscá-la.

[[v9-26-23]]

^<<v9-26-23,23>>^ Jeová é quem retribuirá a cada um a sua justiça e a sua fidelidade, pois, hoje, Jeová entregou-o nas minhas mãos, mas eu não quis levantar a minha mão contra o ungido de Jeová.

[[v9-26-24]]

^<<v9-26-24,24>>^ Assim como hoje considerei a sua vida^&#42;1^ preciosa, que Jeová também considere a minha vida^&#42;2^ preciosa, e que me livre de toda a aflição.”

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v9-26-25]]

^<<v9-26-25,25>>^ Saul respondeu a David: “Que sejas abençoado, meu filho David. Certamente, farás grandes coisas e serás bem-sucedido.” Depois, David seguiu o seu caminho, e Saul voltou para casa.

'''

xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[&#60; Capítulo Anterior] | <<v9-26-0,Topo>> | xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[Próximo Capítulo &#62;]