include::./index.adoc[]

[[v9-28-0]]
=== 1 Samuel, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-28-1]]

^<<v9-28-1,1>>^ Naqueles dias, os filisteus reuniram as suas tropas para guerrear contra Israel. Então, Aquis disse a David: “Naturalmente, sabes que tu e os teus homens irão comigo à batalha.”

[[v9-28-2]]

^<<v9-28-2,2>>^ David disse a Aquis: “O senhor sabe muito bem o que o seu servo vai fazer.” De seguida, Aquis disse a David: “É por isso que vou designar-te como meu guarda-costas permanente.”^&#42;1^

[NOTE]
====
. Lit.: “como guardião da minha cabeça todos os dias”.
====

[[v9-28-3]]

^<<v9-28-3,3>>^ Samuel tinha morrido, e todo o Israel o tinha lamentado e enterrado em Ramá, a sua cidade natal. E Saul tinha expulsado do país os que invocavam espíritos e os adivinhos.

[[v9-28-4]]

^<<v9-28-4,4>>^ Os filisteus reuniram-se, vieram e acamparam em Suném. Em vista disso, Saul reuniu todo o Israel, e acamparam em Gilboa.

[[v9-28-5]]

^<<v9-28-5,5>>^ Quando Saul viu o acampamento dos filisteus, ficou com medo e o seu coração começou a tremer muito.

[[v9-28-6]]

^<<v9-28-6,6>>^ Embora Saul consultasse a Jeová, Jeová nunca lhe respondia, nem em sonhos, nem pelo Urim, nem por meio dos profetas.

[[v9-28-7]]

^<<v9-28-7,7>>^ Por fim, Saul disse aos seus servos: “Procurem uma mulher que invoque espíritos, para que eu vá consultá-la.” Os seus servos disseram-lhe: “Em En-Dor, há uma mulher que invoca espíritos.”

[[v9-28-8]]

^<<v9-28-8,8>>^ Assim, Saul disfarçou-se, vestindo roupas diferentes, e foi com dois dos seus homens falar com a mulher à noite. Ele disse-lhe: “Por favor, revela-me o futuro, invocando espíritos, e faz subir aquele que eu te indicar.”

[[v9-28-9]]

^<<v9-28-9,9>>^ A mulher, porém, disse-lhe: “Deves saber o que Saul fez, que ele eliminou do país os que invocavam espíritos e os adivinhos. Então, porque é que me armas uma cilada^&#42;1^ para que eu seja morta?”

[NOTE]
====
. Ou: “armas uma cilada para a minha alma”.
====

[[v9-28-10]]

^<<v9-28-10,10>>^ Saul jurou-lhe então por Jeová, dizendo: “Tão certo como Jeová vive, tu não terás culpa nenhuma neste assunto!”

[[v9-28-11]]

^<<v9-28-11,11>>^ De seguida, a mulher perguntou: “Quem é que eu te farei subir?” Ele respondeu: “Faz com que Samuel suba.”

[[v9-28-12]]

^<<v9-28-12,12>>^ Quando a mulher viu “Samuel”,^&#42;1^ deu um grito bem alto e disse a Saul: “Porque é que me enganou? O senhor é Saul!”

[NOTE]
====
. Ou: “o que parecia ser Samuel”.
====

[[v9-28-13]]

^<<v9-28-13,13>>^ O rei disse-lhe: “Não tenhas medo. O que é que vês?” A mulher respondeu a Saul: “Vejo alguém semelhante a um deus a subir da terra.”

[[v9-28-14]]

^<<v9-28-14,14>>^ Imediatamente, ele perguntou: “Como é que é a aparência dele?” Ela respondeu: “É um homem idoso que está a subir, e ele usa uma túnica sem mangas.” Percebendo que se tratava de “Samuel”, Saul curvou-se e prostrou-se com o rosto por terra.

[[v9-28-15]]

^<<v9-28-15,15>>^ Então, “Samuel” disse a Saul: “Porque é que me incomodaste, por me fazeres subir?” Saul respondeu: “Estou numa situação muito difícil. Os filisteus estão a lutar contra mim, e Deus abandonou-me. Ele já não me responde, nem por meio dos profetas, nem em sonhos; foi por isso que o chamei, para que me dissesse o que devo fazer.”

[[v9-28-16]]

^<<v9-28-16,16>>^ Nisto, “Samuel” disse: “Porque é que me consultas, agora que Jeová te abandonou e que se tornou teu inimigo?

[[v9-28-17]]

^<<v9-28-17,17>>^ Jeová fará o que predisse por meu intermédio: Jeová vai arrancar o reino das tuas mãos e dá-lo ao teu próximo, a David.

[[v9-28-18]]

^<<v9-28-18,18>>^ No dia de hoje, Jeová está a fazer isto contigo, porque não obedeceste à voz de Jeová e não eliminaste os amalequitas, que despertaram a ira ardente dele.

[[v9-28-19]]

^<<v9-28-19,19>>^ Além disso, Jeová vai entregar-te a ti e a Israel nas mãos dos filisteus e, amanhã, tu e os teus filhos estarão comigo. Jeová também entregará o exército de Israel nas mãos dos filisteus.”

[[v9-28-20]]

^<<v9-28-20,20>>^ Imediatamente, Saul caiu e ficou estendido no chão com muito medo, por causa das palavras de “Samuel”. E ele estava sem forças, porque não tinha comido nada durante todo o dia e toda a noite.

[[v9-28-21]]

^<<v9-28-21,21>>^ Quando a mulher se aproximou de Saul e viu que ele estava muito perturbado, disse-lhe: “A sua serva obedeceu-lhe; arrisquei a minha vida^&#42;1^ e fiz o que pediu.

[NOTE]
====
. Ou: “pus a minha alma na mão”.
====

[[v9-28-22]]

^<<v9-28-22,22>>^ Agora, por favor, escute o que a sua serva tem a dizer. Deixe-me servir-lhe um bocado de pão para que coma e tenha forças para seguir o seu caminho.”

[[v9-28-23]]

^<<v9-28-23,23>>^ Todavia, ele recusou e disse: “Não vou comer.” Contudo, os seus servos e a mulher continuaram a insistir com ele. Finalmente, ele deu-lhes ouvidos, levantou-se do chão e sentou-se na cama.

[[v9-28-24]]

^<<v9-28-24,24>>^ A mulher foi rapidamente abater^&#42;1^ um bezerro gordo que tinha em casa. Depois, pegou em farinha, amassou-a e cozeu pães sem fermento.

[NOTE]
====
. Ou: “sacrificar”.
====

[[v9-28-25]]

^<<v9-28-25,25>>^ Serviu-os então a Saul e aos seus servos, e eles comeram. De seguida, eles levantaram-se e foram-se embora durante a noite.

'''

xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[&#60; Capítulo Anterior] | <<v9-28-0,Topo>> | xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[Próximo Capítulo &#62;]