include::./index.adoc[]

[[v9-4-0]]
=== 1 Samuel, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-4-1]]

^<<v9-4-1,1>>^ E a palavra de Samuel espalhou-se por todo o Israel.
Então, Israel foi enfrentar os filisteus em batalha. Os israelitas acamparam-se junto a Ebenezer, e os filisteus estavam acampados em Afeque.

[[v9-4-2]]

^<<v9-4-2,2>>^ Os filisteus dispuseram-se em formação de batalha para enfrentar Israel. Contudo, a batalha foi difícil e Israel foi derrotado pelos filisteus, que mataram cerca de 4000 homens no campo de batalha.

[[v9-4-3]]

^<<v9-4-3,3>>^ Quando os soldados voltaram^&#42;1^ ao acampamento, os anciãos de Israel disseram: “Porque é que Jeová permitiu que hoje fôssemos derrotados^&#42;2^ pelos filisteus? Vamos trazer de Silo a Arca do Pacto de Jeová, para que ela esteja connosco e nos salve das mãos dos nossos inimigos.”

[NOTE]
====
. Ou: “o povo voltou”.
. Lit.: “Porque é que Jeová nos derrotou”.
====

[[v9-4-4]]

^<<v9-4-4,4>>^ Portanto, enviaram mensageiros a Silo e trouxeram de lá a Arca do Pacto de Jeová dos exércitos, que está sentado no seu trono acima dos^&#42;1^ querubins. E Hofni e Fineias, os dois filhos de Eli, acompanharam a Arca do Pacto do verdadeiro Deus.

[NOTE]
====
. Ou, possivelmente: “entre os”.
====

[[v9-4-5]]

^<<v9-4-5,5>>^ Assim que a Arca do Pacto de Jeová entrou no acampamento, todos os israelitas começaram a gritar, de modo que a terra tremeu.

[[v9-4-6]]

^<<v9-4-6,6>>^ Quando os filisteus ouviram a gritaria, disseram: “Que gritaria é esta no acampamento dos hebreus?” Por fim, souberam que a Arca de Jeová tinha chegado ao acampamento.

[[v9-4-7]]

^<<v9-4-7,7>>^ Os filisteus ficaram com medo e disseram: “Deus chegou ao acampamento!” Também disseram: “Ai de nós, pois nunca aconteceu nada assim!

[[v9-4-8]]

^<<v9-4-8,8>>^ Ai de nós! Quem é que nos salvará das mãos deste Deus majestoso? Este é o Deus que golpeou o Egito com todo o tipo de pragas no deserto.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v9-4-9]]

^<<v9-4-9,9>>^ Tenham coragem, sejam homens, ó filisteus, para que não sirvam os hebreus assim como eles vos serviram. Sejam homens e lutem!”

[[v9-4-10]]

^<<v9-4-10,10>>^ Assim, os filisteus lutaram e derrotaram os israelitas, que fugiram cada um para a sua tenda. A matança foi muito grande; caíram 30 000 soldados^&#42;1^ de Israel.

[NOTE]
====
. Ou: “soldados a pé”.
====

[[v9-4-11]]

^<<v9-4-11,11>>^ Além disso, a Arca de Deus foi capturada, e Hofni e Fineias, os dois filhos de Eli, morreram.

[[v9-4-12]]

^<<v9-4-12,12>>^ Um homem de Benjamim correu a partir do campo de batalha até Silo, onde chegou nesse mesmo dia, com as roupas rasgadas e com terra na cabeça.

[[v9-4-13]]

^<<v9-4-13,13>>^ Quando o homem chegou, Eli estava sentado numa cadeira à beira da estrada, enquanto vigiava, porque o seu coração tremia por causa da Arca do verdadeiro Deus. O homem entrou na cidade para dar a notícia, de modo que toda a cidade começou a clamar.

[[v9-4-14]]

^<<v9-4-14,14>>^ Quando Eli ouviu o som do clamor, perguntou: “Que tumulto é este?” Então, o homem correu até Eli para lhe dar a notícia.

[[v9-4-15]]

^<<v9-4-15,15>>^ (Eli tinha 98 anos de idade e os seus olhos estavam parados; ele não conseguia ver.)

[[v9-4-16]]

^<<v9-4-16,16>>^ Assim, o homem disse a Eli: “Vim do campo de batalha! Foi justamente hoje que fugi de lá.” Eli perguntou: “O que é que aconteceu, meu filho?”

[[v9-4-17]]

^<<v9-4-17,17>>^ E o homem que trazia a notícia disse: “Israel fugiu dos filisteus e o exército^&#42;1^ sofreu uma grande derrota. Além disso, os seus dois filhos, Hofni e Fineias, morreram, e a Arca do verdadeiro Deus foi capturada.”

[NOTE]
====
. Ou: “povo”.
====

[[v9-4-18]]

^<<v9-4-18,18>>^ No momento em que ele mencionou a Arca do verdadeiro Deus, Eli caiu da cadeira para trás, ao lado do portão, partiu o pescoço e morreu, pois era idoso e pesado. Ele tinha julgado Israel por 40 anos.

[[v9-4-19]]

^<<v9-4-19,19>>^ A sua nora, esposa de Fineias, estava grávida, quase a dar à luz. Quando soube que a Arca do verdadeiro Deus tinha sido capturada e que o seu sogro e o seu marido tinham morrido, ela curvou-se e, de repente, entrou em trabalho de parto e deu à luz.

[[v9-4-20]]

^<<v9-4-20,20>>^ Quando estava prestes a morrer, as mulheres que estavam com ela disseram-lhe: “Não tenhas medo, deste à luz um filho.” Ela não respondeu, nem prestou atenção.^&#42;1^

[NOTE]
====
. Ou: “nem fixou o seu coração nisso”.
====

[[v9-4-21]]

^<<v9-4-21,21>>^ No entanto, deu ao menino o nome de Icabode,^&#42;1^ e disse: “A glória exilou-se de Israel.” Ela disse isto porque a Arca do verdadeiro Deus tinha sido capturada, e porque o seu sogro e o seu marido tinham morrido.

[NOTE]
====
. Que significa “Onde está a glória?”
====

[[v9-4-22]]

^<<v9-4-22,22>>^ Ela disse: “A glória exilou-se de Israel, porque a Arca do verdadeiro Deus foi capturada.”

'''

xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[&#60; Capítulo Anterior] | <<v9-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[Próximo Capítulo &#62;]