include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-18-1]]

^<<v9-18-1,1>>^ Depois da conversa entre David e Saul, surgiu uma grande amizade entre Jonatã e David;^&#42;1^ e Jonatã começou a amá-lo como a si mesmo.^&#42;2^

[NOTE]
====
. Ou: “a alma de Jonatã ficou apegada à alma de David”.
. Ou: “como à sua própria alma”.
====

[[v9-18-2]]

^<<v9-18-2,2>>^ Daquele dia em diante, Saul manteve David consigo e não permitiu que ele voltasse à casa do seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ Jonatã amava David como a si mesmo,^&#42;1^ de modo que ele e David fizeram um pacto.

[NOTE]
====
. Ou: “como à sua própria alma”.
====

[[v9-18-4]]

^<<v9-18-4,4>>^ Jonatã tirou a sua túnica sem mangas e deu-a a David, com a sua roupa de combate, espada, arco e cinto.

[[v9-18-5]]

^<<v9-18-5,5>>^ David começou a sair em campanhas militares e era bem-sucedido^&#42;1^ onde quer que Saul o enviasse. Portanto, Saul encarregou-o dos guerreiros, e isso agradou a todo o povo e aos servos de Saul.

[NOTE]
====
. Ou: “agia sabiamente”.
====

[[v9-18-6]]

^<<v9-18-6,6>>^ Quando David e os soldados voltavam, depois de terem derrotado os filisteus, mulheres de todas as cidades de Israel iam alegremente ao encontro do rei Saul, enquanto cantavam e dançavam com pandeiretas e instrumentos de cordas.

[[v9-18-7]]

^<<v9-18-7,7>>^ As mulheres celebravam e cantavam:
“Saul matou milhares,
E David dezenas de milhares.”

[[v9-18-8]]

^<<v9-18-8,8>>^ Saul não gostou nada do que as mulheres cantavam. Por isso, ficou muito zangado e disse: “A David deram dezenas de milhares, mas a mim deram-me apenas milhares. Agora, só falta que lhe deem o reino!”

[[v9-18-9]]

^<<v9-18-9,9>>^ Daquele dia em diante, Saul passou a olhar sempre com desconfiança para David.

[[v9-18-10]]

^<<v9-18-10,10>>^ No dia seguinte, um espírito mau da parte de Deus tomou conta de Saul, e ele começou a agir de modo estranho^&#42;1^ na sua casa, enquanto David tocava harpa, como de costume. Saul tinha uma lança na mão;

[NOTE]
====
. Ou: “agiu como profeta”.
====

[[v9-18-11]]

^<<v9-18-11,11>>^ ele arremessou a lança, dizendo para consigo: ‘Vou espetar David na parede!’ No entanto, David escapou-lhe duas vezes.

[[v9-18-12]]

^<<v9-18-12,12>>^ Portanto, Saul ficou com medo de David, porque Jeová estava com ele, mas tinha abandonado Saul.

[[v9-18-13]]

^<<v9-18-13,13>>^ Assim, Saul afastou-o da sua presença e nomeou-o chefe de mil, e David liderava o exército nas batalhas.^&#42;1^

[NOTE]
====
. Lit.: “e ele saía e entrava diante do povo”.
====

[[v9-18-14]]

^<<v9-18-14,14>>^ David continuou a ser bem-sucedido^&#42;1^ em tudo o que fazia e Jeová estava com ele.

[NOTE]
====
. Ou: “agir sabiamente”.
====

[[v9-18-15]]

^<<v9-18-15,15>>^ Quando Saul viu que ele era muito bem-sucedido, ficou com medo dele.

[[v9-18-16]]

^<<v9-18-16,16>>^ Contudo, todo o Israel e Judá gostavam de David, dado que ele os liderava nas suas campanhas militares.

[[v9-18-17]]

^<<v9-18-17,17>>^ Mais tarde, Saul disse a David: “Vou dar-te a minha filha mais velha, Merabe, como esposa. No entanto, continua a mostrar-me a tua coragem, por travares as guerras de Jeová.” Pois Saul dizia para consigo: ‘Que ele morra, não pelas minhas mãos, mas pelas mãos dos filisteus.’

[[v9-18-18]]

^<<v9-18-18,18>>^ David disse a Saul: “Quem sou eu e quem são os meus parentes, a família do meu pai em Israel, para que eu me torne genro do rei?”

[[v9-18-19]]

^<<v9-18-19,19>>^ Contudo, quando chegou a época de Merabe, filha de Saul, ser dada em casamento a David, ela já tinha sido dada a Adriel, o meolatita.

[[v9-18-20]]

^<<v9-18-20,20>>^ Mical, filha de Saul, estava apaixonada por David, e Saul ficou contente quando lhe contaram isso.

[[v9-18-21]]

^<<v9-18-21,21>>^ Portanto, Saul pensou: ‘Vou dar-lha para que ela lhe sirva de armadilha, fazendo com que ele caia nas mãos dos filisteus.’ Então, Saul disse a David pela segunda vez: “Hoje, vais tornar-te meu genro.”^&#42;1^

[NOTE]
====
. Ou: “Hoje formarás uma aliança matrimonial comigo.”
====

[[v9-18-22]]

^<<v9-18-22,22>>^ Além disso, Saul ordenou aos seus servos: “Conversem em particular com David e digam-lhe: ‘O rei aprecia-te muito, e todos os seus servos gostam de ti. Portanto, aceita ser genro do^&#42;1^ rei.’”

[NOTE]
====
. Ou: “formar uma aliança matrimonial com o”.
====

[[v9-18-23]]

^<<v9-18-23,23>>^ Quando os servos de Saul disseram isto a David, David disse: “Acham que é fácil para alguém pobre e desprezado como eu tornar-se genro do^&#42;1^ rei?”

[NOTE]
====
. Ou: “formar uma aliança matrimonial com o”.
====

[[v9-18-24]]

^<<v9-18-24,24>>^ De seguida, os servos de Saul contaram ao rei o que David tinha dito.

[[v9-18-25]]

^<<v9-18-25,25>>^ Portanto, Saul disse: “Digam isto a David: ‘Como preço de noiva, o rei só quer cem prepúcios dos filisteus, a fim de se vingar dos inimigos do rei.’” Saul estava a tramar que David fosse morto pelos filisteus.

[[v9-18-26]]

^<<v9-18-26,26>>^ Assim, os seus servos comunicaram essas palavras a David, e a ideia de se tornar genro do^&#42;1^ rei agradou a David. Antes de terminar o prazo estipulado,

[NOTE]
====
. Ou: “formar uma aliança matrimonial com o”.
====

[[v9-18-27]]

^<<v9-18-27,27>>^ David e os seus homens partiram e mataram 200 filisteus. E David levou todos os prepúcios ao rei, a fim de se tornar genro do^&#42;1^ rei. Assim, Saul deu-lhe Mical, sua filha, como esposa.

[NOTE]
====
. Ou: “formar uma aliança matrimonial com o”.
====

[[v9-18-28]]

^<<v9-18-28,28>>^ Saul percebeu que Jeová estava com David, e que a sua filha Mical o amava.

[[v9-18-29]]

^<<v9-18-29,29>>^ Isto fez com que Saul ficasse ainda com mais medo de David, e Saul tornou-se inimigo de David para o resto da sua vida.

[[v9-18-30]]

^<<v9-18-30,30>>^ Os príncipes dos filisteus saíam para a batalha, mas, sempre que isso acontecia, David tinha mais êxito^&#42;1^ do que todos os servos de Saul, e o seu nome era muito respeitado.

[NOTE]
====
. Ou: “agia mais sabiamente”.
====

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]