include::./index.adoc[]

[[v9-1-0]]
=== 1 Samuel, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v9-1-1]]

^<<v9-1-1,1>>^ Havia um homem de Ramataim-Zofim,^&#42;1^ da região montanhosa de Efraim, cujo nome era Elcana. Ele era filho de Jeroão, filho de Eliú, filho de Toú, filho de Zufe, efraimita.

[NOTE]
====
. Ou: “de Ramá, um zufita”.
====

[[v9-1-2]]

^<<v9-1-2,2>>^ Ele tinha duas esposas: uma chamava-se Ana, e a outra, Penina. Penina tinha filhos, mas Ana não tinha nenhum.

[[v9-1-3]]

^<<v9-1-3,3>>^ Todos os anos, este homem subia da sua cidade até Silo para adorar^&#42;1^ e oferecer sacrifícios a Jeová dos exércitos. Era ali que Hofni e Fineias, os dois filhos de Eli, serviam como sacerdotes de Jeová.

[NOTE]
====
. Ou: “curvar-se”.
====

[[v9-1-4]]

^<<v9-1-4,4>>^ Certo dia, quando Elcana ofereceu um sacrifício, deu porções à sua esposa Penina e a todos os filhos e filhas dela,

[[v9-1-5]]

^<<v9-1-5,5>>^ mas a Ana ele deu uma porção especial, porque Ana era quem ele amava. No entanto, Jeová não lhe tinha dado filhos.^&#42;1^

[NOTE]
====
. Lit.: “Jeová tinha fechado o ventre dela”.
====

[[v9-1-6]]

^<<v9-1-6,6>>^ E a sua rival provocava-a continuamente, a fim de fazê-la sentir-se magoada por Jeová não lhe ter dado filhos.

[[v9-1-7]]

^<<v9-1-7,7>>^ Era assim que Penina fazia todos os anos. Sempre que Ana subia à casa de Jeová, a sua rival provocava-a de tal forma, que ela chorava e não comia.

[[v9-1-8]]

^<<v9-1-8,8>>^ Então, Elcana, seu marido, disse-lhe: “Ana, porque é que estás a chorar e porque é que não comes? Porque é que estás tão triste?^&#42;1^ Será que eu não sou para ti melhor do que dez filhos?”

[NOTE]
====
. Ou: “Porque é que o teu coração se sente mal?”
====

[[v9-1-9]]

^<<v9-1-9,9>>^ Depois, Ana levantou-se, assim que terminaram de comer e beber em Silo. E Eli, o sacerdote, estava sentado na cadeira junto à ombreira^&#42;1^ da porta do templo^&#42;2^ de Jeová.

[NOTE]
====
. Ou: “lateral”.
. Isto é, do tabernáculo.
====

[[v9-1-10]]

^<<v9-1-10,10>>^ Ana estava muito angustiada,^&#42;1^ e começou a orar a Jeová e a chorar sem parar.

[NOTE]
====
. Ou: “com a alma amargurada”.
====

[[v9-1-11]]

^<<v9-1-11,11>>^ E ela fez o seguinte voto: “Ó Jeová dos exércitos, se olhares para a aflição da tua serva e te lembrares de mim, e não te esqueceres da tua serva e deres à tua serva um filho, um menino, eu vou entregá-lo a Jeová por todos os dias da sua vida, e não se passará uma navalha na sua cabeça.”

[[v9-1-12]]

^<<v9-1-12,12>>^ Enquanto ela fazia uma longa oração a Jeová, Eli observava os seus lábios.

[[v9-1-13]]

^<<v9-1-13,13>>^ Ana estava a falar no seu coração; somente os seus lábios se mexiam, mas não se ouvia a sua voz. Por isso, Eli achou que ela estava bêbeda,

[[v9-1-14]]

^<<v9-1-14,14>>^ e disse-lhe: “Até quando é que vais ficar embriagada? Para de beber vinho.”

[[v9-1-15]]

^<<v9-1-15,15>>^ Ana respondeu: “Não, meu senhor! Sou uma mulher muito angustiada;^&#42;1^ não bebi vinho nem outra bebida alcoólica, mas derramo a minha alma^&#42;2^ perante Jeová.

[NOTE]
====
. Ou: “muito pressionada no espírito”.
. Veja o Glossário.
====

[[v9-1-16]]

^<<v9-1-16,16>>^ Não pense que a sua serva é uma mulher imprestável, pois tenho estado a orar até agora por estar muito angustiada e aflita.”

[[v9-1-17]]

^<<v9-1-17,17>>^ Então, Eli disse-lhe: “Vai em paz, e que o Deus de Israel te conceda o pedido que lhe fizeste.”

[[v9-1-18]]

^<<v9-1-18,18>>^ Ela respondeu: “Que a sua serva ache favor aos seus olhos.” E a mulher foi-se embora e comeu, e o seu rosto já não estava abatido.

[[v9-1-19]]

^<<v9-1-19,19>>^ Por conseguinte, levantaram-se de manhã cedo e curvaram-se perante Jeová; depois, voltaram à sua casa em Ramá. Elcana teve então relações com a sua esposa Ana, e Jeová voltou a sua atenção para ela.^&#42;1^

[NOTE]
====
. Lit.: “lembrou-se dela”.
====

[[v9-1-20]]

^<<v9-1-20,20>>^ No espaço de um ano,^&#42;1^ Ana ficou grávida, deu à luz um filho e chamou-lhe Samuel,^&#42;2^ porque, como ela disse: “Foi a Jeová que eu o pedi.”

[NOTE]
====
. Ou, possivelmente: “No tempo devido”.
. Que significa “nome de Deus”.
====

[[v9-1-21]]

^<<v9-1-21,21>>^ No devido tempo, Elcana subiu com todos os da sua casa para oferecer o sacrifício anual a Jeová e apresentar a sua oferta em cumprimento de um voto.

[[v9-1-22]]

^<<v9-1-22,22>>^ Contudo, Ana não subiu, pois disse ao seu marido: “Assim que o menino for desmamado, eu vou levá-lo de modo a que ele compareça perante Jeová e fique lá definitivamente.”

[[v9-1-23]]

^<<v9-1-23,23>>^ Então, Elcana, seu marido, disse-lhe: “Faz o que achares melhor.^&#42;1^ Fica em casa até que o tenhas desmamado. Que Jeová cumpra o que disseste.” Assim, a mulher ficou em casa e cuidou do seu filho até o desmamar.

[NOTE]
====
. Lit.: “o que for bom aos teus olhos”.
====

[[v9-1-24]]

^<<v9-1-24,24>>^ Depois de o ter desmamado, levou-o a Silo, com um novilho de três anos, uma efa^&#42;1^ de farinha e um grande odre de vinho, e chegou com o menino à casa de Jeová, em Silo.

[NOTE]
====
. Cerca de 22 l. Veja o Ap. B14.
====

[[v9-1-25]]

^<<v9-1-25,25>>^ De seguida, abateram o novilho e levaram o menino a Eli.

[[v9-1-26]]

^<<v9-1-26,26>>^ Assim, ela disse: “Com licença, meu senhor. Tão certo como o senhor vive,^&#42;1^ eu sou a mulher que esteve aqui consigo, a orar a Jeová.

[NOTE]
====
. Ou: “Pela vida da sua alma”.
====

[[v9-1-27]]

^<<v9-1-27,27>>^ Foi este menino que eu pedi em oração, e Jeová concedeu o meu pedido.

[[v9-1-28]]

^<<v9-1-28,28>>^ Por isso, entrego-o^&#42;1^ a Jeová. Ele pertencerá^&#42;2^ a Jeová por toda a sua vida.”
E ele^&#42;3^ curvou-se ali perante Jeová.

[NOTE]
====
. Lit.: “empresto-o”.
. Ou: “será alguém emprestado”.
. Aparentemente, refere-se a Elcana.
====

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]