include::./index.adoc[]

[[v8-2-0]]
=== Rute, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v8-2-1]]

^<<v8-2-1,1>>^ Noemi tinha um parente muito rico por parte do marido. O nome dele era Boaz, e ele era da família de Elimeleque.

[[v8-2-2]]

^<<v8-2-2,2>>^ Rute, a moabita, disse a Noemi: “Por favor, deixe-me ir ao campo respigar cereal atrás de alguém que me mostre favor.” Portanto, Noemi disse-lhe: “Vai, minha filha.”

[[v8-2-3]]

^<<v8-2-3,3>>^ Então, ela foi e começou a respigar no campo, atrás dos ceifeiros. Por acaso, foi parar a um campo que pertencia a Boaz, que era da família de Elimeleque.

[[v8-2-4]]

^<<v8-2-4,4>>^ Naquele momento, Boaz chegou de Belém e disse aos ceifeiros: “Jeová esteja convosco.” E eles responderam: “Jeová o abençoe.”

[[v8-2-5]]

^<<v8-2-5,5>>^ Boaz perguntou então ao servo encarregado dos ceifeiros: “A que família pertence esta moça?”

[[v8-2-6]]

^<<v8-2-6,6>>^ O servo encarregado dos ceifeiros respondeu: “A moça é uma moabita que voltou com Noemi dos campos de Moabe.

[[v8-2-7]]

^<<v8-2-7,7>>^ Ela disse: ‘Por favor, posso respigar e recolher as espigas cortadas^&#42;1^ que forem deixadas para trás pelos ceifeiros?’ E ela ficou de pé desde que chegou esta manhã; só se sentou agora no abrigo, para descansar um pouco.”

[NOTE]
====
. Ou, possivelmente: “entre os feixes”.
====

[[v8-2-8]]

^<<v8-2-8,8>>^ Então, Boaz disse a Rute: “Escuta, minha filha. Não respigues noutro campo, nem vás para nenhum outro lugar. Fica perto das minhas servas.

[[v8-2-9]]

^<<v8-2-9,9>>^ Fica atenta ao campo que ceifarem e vai com elas. Dei ordem aos servos para que não te incomodem.^&#42;1^ Quando estiveres com sede, vai até aos cântaros e bebe a água que os servos tirarem.”

[NOTE]
====
. Ou: “toquem”.
====

[[v8-2-10]]

^<<v8-2-10,10>>^ Em vista disso, ela prostrou-se com o rosto por terra e perguntou-lhe: “Como é que eu achei favor aos seus olhos, e porque reparou em mim, sendo eu uma estrangeira?”

[[v8-2-11]]

^<<v8-2-11,11>>^ Boaz respondeu-lhe: “Contaram-me tudo o que fizeste pela tua sogra depois da morte do teu marido, e que deixaste o teu pai, a tua mãe e a terra dos teus parentes, e vieste morar com um povo que não conhecias.

[[v8-2-12]]

^<<v8-2-12,12>>^ Que Jeová te recompense pelo que tens feito e que haja para ti um salário perfeito^&#42;1^ da parte de Jeová, o Deus de Israel, debaixo das asas de quem vieste procurar refúgio.”

[NOTE]
====
. Ou: “uma plena recompensa”.
====

[[v8-2-13]]

^<<v8-2-13,13>>^ Então, ela disse: “Que eu ache favor aos seus olhos, meu senhor, visto que me consolou e falou de um modo que tranquilizou esta^&#42;1^ sua serva, embora eu nem seja uma das suas servas.”

[NOTE]
====
. Lit.: “falou ao coração da”.
====

[[v8-2-14]]

^<<v8-2-14,14>>^ Na hora da refeição, Boaz disse-lhe: “Vem comer pão e mergulha o teu pedaço no vinagre.” Então, ela sentou-se junto aos ceifeiros, e ele ofereceu-lhe cereal torrado. Ela comeu e ficou satisfeita, e ainda sobrou.

[[v8-2-15]]

^<<v8-2-15,15>>^ Quando ela se levantou para respigar, Boaz ordenou aos seus servos: “Deixem que ela respigue entre as espigas cortadas,^&#42;1^ e não a incomodem.

[NOTE]
====
. Ou, possivelmente: “os feixes”.
====

[[v8-2-16]]

^<<v8-2-16,16>>^ Além disso, tirem algumas espigas dos feixes e deixem-nas para trás, para que ela as respigue, e não digam nada para a impedir.”

[[v8-2-17]]

^<<v8-2-17,17>>^ Assim, ela continuou a respigar no campo até ao anoitecer. Depois, debulhou o que tinha respigado e deu cerca de uma efa^&#42;1^ de cevada.

[NOTE]
====
. Cerca de 22 l. Veja o Ap. B14.
====

[[v8-2-18]]

^<<v8-2-18,18>>^ Então, apanhou a cevada e entrou na cidade, e a sua sogra viu o que ela tinha respigado. Após comer e ficar satisfeita, Rute também apanhou o alimento que sobrou depois da refeição e deu-o à sua sogra.

[[v8-2-19]]

^<<v8-2-19,19>>^ A sua sogra disse-lhe então: “Onde é que respigaste hoje? Onde é que trabalhaste? Abençoado seja aquele que reparou em ti.” Assim, ela falou à sogra sobre a pessoa com quem tinha trabalhado: “O nome do homem com quem trabalhei hoje é Boaz.”

[[v8-2-20]]

^<<v8-2-20,20>>^ Noemi disse então à nora: “Seja ele abençoado por Jeová, que não falhou em demonstrar amor leal para com os vivos e os mortos.” E Noemi acrescentou: “O homem é nosso parente. Ele é um dos nossos resgatadores.”^&#42;1^

[NOTE]
====
. Ou: “um dos nossos parentes com o direito de resgatar”.
====

[[v8-2-21]]

^<<v8-2-21,21>>^ Então, Rute, a moabita, disse: “Ele disse-me também: ‘Fica perto dos meus servos até que tenham terminado toda a minha colheita.’”

[[v8-2-22]]

^<<v8-2-22,22>>^ Assim, Noemi disse a Rute, sua nora: “Minha filha, é melhor acompanhares as servas dele do que seres incomodada noutro campo.”

[[v8-2-23]]

^<<v8-2-23,23>>^ Assim, ela ficou perto das servas de Boaz e respigou até ao fim da colheita da cevada e da colheita do trigo. E ela continuou a morar com a sogra.

'''

xref:008-rute/008-rute-001.adoc#v8-1-0[&#60; Capítulo Anterior] | <<v8-2-0,Topo>> | xref:008-rute/008-rute-003.adoc#v8-3-0[Próximo Capítulo &#62;]