include::./index.adoc[]

[[v8-1-0]]
=== Rute, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v8-1-1]]

^<<v8-1-1,1>>^ Nos dias em que os juízes administravam a justiça,^&#42;1^ houve uma fome no país. E um homem partiu de Belém, em Judá, para ir morar como estrangeiro nos campos^&#42;2^ de Moabe, juntamente com a esposa e os dois filhos.

[NOTE]
====
. Lit.: “julgavam”.
. Ou: “na região”.
====

[[v8-1-2]]

^<<v8-1-2,2>>^ O nome do homem era Elimeleque,^&#42;1^ o nome da esposa era Noemi,^&#42;2^ e os nomes dos dois filhos eram Malom^&#42;3^ e Quiliom.^&#42;4^ Eles eram efratitas de Belém de Judá. Chegaram aos campos de Moabe e ficaram a morar lá.

[NOTE]
====
. Que significa “o meu Deus é rei”.
. Que significa “minha agradabilidade; minha doçura”.
. Possivelmente derivado de uma palavra hebraica que significa “enfraquecer; adoecer”.
. Que significa “aquele que falha; aquele que chega ao fim”.
====

[[v8-1-3]]

^<<v8-1-3,3>>^ Algum tempo depois, morreu Elimeleque, marido de Noemi, e restaram ela e os dois filhos.

[[v8-1-4]]

^<<v8-1-4,4>>^ Mais tarde, os homens casaram-se com mulheres moabitas: uma chamava-se Orpa e a outra chamava-se Rute. Eles ficaram a morar lá quase dez anos.

[[v8-1-5]]

^<<v8-1-5,5>>^ Depois, morreram também os dois filhos, Malom e Quiliom, e Noemi ficou sem os dois filhos e sem o marido.

[[v8-1-6]]

^<<v8-1-6,6>>^ Então, ela e as suas noras partiram dos campos de Moabe, pois ela tinha ouvido dizer em Moabe que Jeová tinha voltado a atenção para o seu povo, dando-lhes pão.^&#42;1^

[NOTE]
====
. Ou: “alimentos”.
====

[[v8-1-7]]

^<<v8-1-7,7>>^ Ela deixou o lugar onde morava com as suas duas noras. Enquanto caminhavam pela estrada para voltar à terra de Judá,

[[v8-1-8]]

^<<v8-1-8,8>>^ Noemi disse às noras: “Voltem, cada uma para a casa da sua mãe. Que Jeová vos demonstre amor leal, assim como fizeram aos vossos maridos que morreram e a mim.

[[v8-1-9]]

^<<v8-1-9,9>>^ Que Jeová permita^&#42;1^ que cada uma de vocês encontre segurança^&#42;2^ no lar de um marido.” Então, beijou-as, e elas começaram a chorar em voz alta.

[NOTE]
====
. Ou: “conceda a dádiva de”.
. Lit.: “um lugar de descanso”.
====

[[v8-1-10]]

^<<v8-1-10,10>>^ E diziam-lhe: “Não! Nós iremos consigo para o seu povo.”

[[v8-1-11]]

^<<v8-1-11,11>>^ No entanto, Noemi disse: “Voltem, minhas filhas. Porque é que haviam de ir comigo? Será que ainda posso dar à luz filhos que se tornariam vossos maridos?

[[v8-1-12]]

^<<v8-1-12,12>>^ Voltem, minhas filhas. Voltem, pois estou demasiado velha para me casar. Mesmo que eu tivesse esperança de encontrar um marido hoje à noite e pudesse ter filhos,

[[v8-1-13]]

^<<v8-1-13,13>>^ será que vocês esperariam por eles até que crescessem? Ficariam sem se casar à espera deles? Não, minhas filhas. Estou muito amargurada por vos ver nesta situação, pois a mão de Jeová voltou-se contra mim.”

[[v8-1-14]]

^<<v8-1-14,14>>^ Elas choraram novamente em voz alta, e depois Orpa beijou a sogra e partiu. Rute, contudo, insistiu em ficar com ela.

[[v8-1-15]]

^<<v8-1-15,15>>^ Assim, Noemi disse: “Vê, a tua cunhada^&#42;1^ voltou ao seu povo e aos seus deuses. Volta com a tua cunhada.”

[NOTE]
====
. Ou: “cunhada viúva”.
====

[[v8-1-16]]

^<<v8-1-16,16>>^ No entanto, Rute disse: “Não insista comigo para a abandonar, para deixar de a acompanhar; pois, onde for, eu irei, e onde passar a noite, eu passarei a noite. O seu povo será o meu povo, e o seu Deus será o meu Deus.

[[v8-1-17]]

^<<v8-1-17,17>>^ Onde morrer, eu morrerei e lá serei enterrada. Que Jeová me castigue, e que o faça severamente, se outra coisa a não ser a morte me separar de si.”

[[v8-1-18]]

^<<v8-1-18,18>>^ Quando Noemi viu que Rute insistia em acompanhá-la, desistiu de tentar convencê-la.

[[v8-1-19]]

^<<v8-1-19,19>>^ E as duas seguiram viagem até que chegaram a Belém. Assim que chegaram a Belém, toda a cidade ficou agitada por causa delas, e as mulheres perguntavam: “Esta é que é Noemi?”

[[v8-1-20]]

^<<v8-1-20,20>>^ E ela dizia às mulheres: “Não me chamem Noemi.^&#42;1^ Chamem-me Mara,^&#42;2^ pois o Todo-Poderoso tornou a minha vida muito amarga.

[NOTE]
====
. Que significa “minha agradabilidade; minha doçura”.
. Que significa “amarga”.
====

[[v8-1-21]]

^<<v8-1-21,21>>^ Eu tinha tudo quando fui, mas Jeová fez-me voltar de mãos vazias. Porque é que me chamam Noemi, se Jeová se opôs a mim e o Todo-Poderoso me causou calamidade?”

[[v8-1-22]]

^<<v8-1-22,22>>^ Foi assim que Noemi voltou dos campos de Moabe juntamente com Rute, a sua nora moabita. Elas chegaram a Belém no início da colheita da cevada.

'''

xref:007-juizes/007-juizes-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-rute/008-rute-002.adoc#v8-2-0[Próximo Capítulo &#62;]