include::./index.adoc[]

[[v22-4-0]]
=== Cântico de Salomão, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v22-4-1]]

^<<v22-4-1,1>>^ “Como és bela, minha amada!
Como és bela!
Os teus olhos por detrás do véu são como os das pombas.
O teu cabelo é como um rebanho de cabras
Que descem as montanhas de Gileade.

[[v22-4-2]]

^<<v22-4-2,2>>^ Os teus dentes são como um rebanho de ovelhas recém-tosquiadas
Que acabam de ser lavadas;
Todas elas com gémeos,
E nenhuma perdeu a cria.

[[v22-4-3]]

^<<v22-4-3,3>>^ Os teus lábios são como um fio escarlate,
E a tua fala é agradável.
Como as metades de uma romã
São as tuas faces^&#42;1^ por detrás do véu.

[NOTE]
====
. Ou: “têmporas”.
====

[[v22-4-4]]

^<<v22-4-4,4>>^ O teu pescoço é como a torre de David,
Construída com fileiras de pedras,
Na qual se penduram mil escudos,
Todos os escudos redondos dos guerreiros valentes.

[[v22-4-5]]

^<<v22-4-5,5>>^ Os teus seios são como dois filhotes de veado,
Crias gémeas de uma gazela,
Que pastam entre os lírios.”

[[v22-4-6]]

^<<v22-4-6,6>>^ “Antes que sopre a brisa do dia^&#42;1^ e as sombras fujam,
Irei ao monte da mirra
E à colina do olíbano.”

[NOTE]
====
. Lit.: “que o dia respire”.
====

[[v22-4-7]]

^<<v22-4-7,7>>^ “És inteiramente bela, minha amada,
Não há defeito em ti.

[[v22-4-8]]

^<<v22-4-8,8>>^ Desçamos juntos do Líbano, minha noiva,
Desçamos juntos do Líbano.
Desce do cume do Amana,^&#42;1^
Do cume do Senir, do cume do Hermom,
Dos esconderijos dos leões, das montanhas dos leopardos.

[NOTE]
====
. Ou: “Antilíbano”.
====

[[v22-4-9]]

^<<v22-4-9,9>>^ Roubaste o meu coração, minha irmã, minha noiva,
Roubaste o meu coração com apenas um olhar,
Com apenas um pingente do teu colar.

[[v22-4-10]]

^<<v22-4-10,10>>^ Como são belas as tuas expressões de amor, minha irmã, minha noiva!
As tuas expressões de amor são muito melhores do que o vinho;
E a fragrância do teu perfume, do que qualquer especiaria!

[[v22-4-11]]

^<<v22-4-11,11>>^ Os teus lábios, minha noiva, gotejam mel dos favos.
Há mel e leite sob a tua língua,
E a fragrância das tuas roupas é como a fragrância do Líbano.

[[v22-4-12]]

^<<v22-4-12,12>>^ Minha irmã, minha noiva, és como um jardim trancado;
Um jardim trancado, uma fonte fechada.

[[v22-4-13]]

^<<v22-4-13,13>>^ Os teus rebentos são^&#42;1^ um paraíso^&#42;2^ de romãs,
Com os frutos mais seletos, também hena com nardo,

[NOTE]
====
. Ou, possivelmente: “A tua pele é”.
. Ou: “jardim”.
====

[[v22-4-14]]

^<<v22-4-14,14>>^ Nardo e açafrão, cálamo^&#42;1^ e canela,
Com todo o tipo de árvores de olíbano, também mirra e aloés,
Com todos os perfumes mais finos.

[NOTE]
====
. Uma cana aromática.
====

[[v22-4-15]]

^<<v22-4-15,15>>^ Tu és uma fonte de jardim, um poço de água doce,
E riachos vindos do Líbano.

[[v22-4-16]]

^<<v22-4-16,16>>^ Desperta, ó vento norte;
Entra, ó vento sul.
Sopra suavemente no meu jardim,
Para que se espalhem os seus perfumes.”
“Que o meu querido entre no seu jardim
E coma dos seus frutos seletos.”

'''

xref:022-cantico-de-salomao/022-cantico-de-salomao-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-cantico-de-salomao/022-cantico-de-salomao-005.adoc#v22-5-0[Próximo Capítulo &#62;]