include::./index.adoc[]

[[v22-1-0]]
=== Cântico de Salomão, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v22-1-1]]

^<<v22-1-1,1>>^ O cântico dos cânticos,^&#42;1^ de Salomão:

[NOTE]
====
. Ou: “O cântico superlativo”.
====

[[v22-1-2]]

^<<v22-1-2,2>>^ “Beija-me com os beijos dos teus lábios,
Pois as tuas expressões de amor são melhores do que o vinho.

[[v22-1-3]]

^<<v22-1-3,3>>^ Agradável é a fragrância dos teus perfumes;
O teu nome é como óleo aromático derramado.
É por isso que as moças te amam.

[[v22-1-4]]

^<<v22-1-4,4>>^ Leva-me contigo,^&#42;1^ e corramos.
O rei trouxe-me ao seu aposento reservado!
Alegremo-nos e exultemos juntos.
Celebremos^&#42;2^ as tuas expressões de amor, que são melhores do que o vinho.
É com razão que elas^&#42;3^ te amam!

[NOTE]
====
. Lit.: “Arrasta-me atrás de ti”.
. Ou: “Relatemos”.
. Isto é, as moças.
====

[[v22-1-5]]

^<<v22-1-5,5>>^ Sou morena,^&#42;1^ mas bela, ó filhas de Jerusalém,
Como as tendas de Quedar, como os panos da tenda de Salomão.

[NOTE]
====
. Lit.: “preta”.
====

[[v22-1-6]]

^<<v22-1-6,6>>^ Não fiquem a olhar para mim por eu ser morena,
Pois o sol fixou em mim o seu olhar.
Os filhos da minha mãe zangaram-se comigo;
Mandaram-me guardar as vinhas,
Mas eu não pude guardar a minha própria vinha.

[[v22-1-7]]

^<<v22-1-7,7>>^ Diz-me, tu, a quem eu tanto amo,^&#42;1^
Aonde levas o teu rebanho a pastar?
Onde é que o fazes deitar-se ao meio-dia?
Porque deveria eu ser como uma mulher coberta com um véu^&#42;2^
Entre os rebanhos dos teus amigos?”

[NOTE]
====
. Ou: “a minha alma tanto ama”.
. Ou: “um véu de luto”.
====

[[v22-1-8]]

^<<v22-1-8,8>>^ “Se não sabes, ó mais bela das mulheres,
Segue o rasto do rebanho
E leva os teus cabritos a pastar junto às tendas dos pastores.”

[[v22-1-9]]

^<<v22-1-9,9>>^ “Eu comparo-te, minha amada, a uma^&#42;1^ égua dos carros do Faraó.

[NOTE]
====
. Ou: “à minha”.
====

[[v22-1-10]]

^<<v22-1-10,10>>^ Belas são as tuas faces com adornos,^&#42;1^
Também o teu pescoço, com colares de contas.

[NOTE]
====
. Ou, possivelmente: “entre as tranças do teu cabelo”.
====

[[v22-1-11]]

^<<v22-1-11,11>>^ Vamos fazer-te enfeites^&#42;1^ de ouro
Incrustados de prata.”

[NOTE]
====
. Ou: “argolas”.
====

[[v22-1-12]]

^<<v22-1-12,12>>^ “Enquanto o rei está à mesa,
O meu perfume^&#42;1^ exala a sua fragrância.

[NOTE]
====
. Lit.: “nardo”.
====

[[v22-1-13]]

^<<v22-1-13,13>>^ O meu querido é para mim como uma pequena bolsa de mirra perfumada,
Que passa a noite entre os meus seios.

[[v22-1-14]]

^<<v22-1-14,14>>^ O meu querido é para mim como um ramalhete de hena
Entre as vinhas de En-Gedi.”

[[v22-1-15]]

^<<v22-1-15,15>>^ “Como és bela, minha amada!
Como és bela! Os teus olhos são como os das pombas.”

[[v22-1-16]]

^<<v22-1-16,16>>^ “Como és belo, meu querido! Como és encantador!
A nossa cama está entre a folhagem.

[[v22-1-17]]

^<<v22-1-17,17>>^ As vigas da nossa casa^&#42;1^ são cedros,
As traves do nosso telhado são juníperos.

[NOTE]
====
. Ou: “grandiosa casa”.
====

'''

xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-cantico-de-salomao/022-cantico-de-salomao-002.adoc#v22-2-0[Próximo Capítulo &#62;]