include::./index.adoc[]

[[v22-8-0]]
=== Cântico de Salomão, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v22-8-1]]

^<<v22-8-1,1>>^ “Quem me dera que fosses como um irmão meu,
Amamentado aos seios da minha mãe!
Então, se eu te encontrasse lá fora, beijar-te-ia,
E ninguém me desprezaria.

[[v22-8-2]]

^<<v22-8-2,2>>^ Eu iria conduzir-te
E levar-te à casa da minha mãe,
Aquela que me educou.
Dar-te-ia vinho aromatizado para beber
E sumo fresco de romãs.

[[v22-8-3]]

^<<v22-8-3,3>>^ A sua mão esquerda estaria sob a minha cabeça,
E a sua mão direita iria abraçar-me.

[[v22-8-4]]

^<<v22-8-4,4>>^ Ponho-vos sob juramento, ó filhas de Jerusalém:
Não tentem despertar nem suscitar em mim amor até que este o queira.”

[[v22-8-5]]

^<<v22-8-5,5>>^ “Quem é esta que sobe do deserto,
Apoiada no seu querido?”
“Despertei-te debaixo da macieira.
Ali a tua mãe sentiu dores de parto.
Ali te deu à luz com dores de parto.

[[v22-8-6]]

^<<v22-8-6,6>>^ Põe-me como um selo sobre o teu coração,
Como um selo sobre o teu braço,
Pois o amor é tão forte como a morte,
E a devoção exclusiva é tão implacável como a Sepultura.^&#42;1^
As suas chamas são um fogo ardente, a chama de Jah.^&#42;2^

[NOTE]
====
. Ou: “o Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. “Jah” é uma forma reduzida do nome Jeová.
====

[[v22-8-7]]

^<<v22-8-7,7>>^ Águas turbulentas não podem extinguir o amor,
Nem podem os rios levá-lo na correnteza.
Se um homem oferecesse todas as riquezas da sua casa em troca do amor,
Essas seriam completamente desprezadas.”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Ele seria completamente desprezado”.
====

[[v22-8-8]]

^<<v22-8-8,8>>^ “Temos uma irmãzinha,
E ela ainda não tem seios.
O que faremos pela nossa irmã
No dia em que for pedida em casamento?”

[[v22-8-9]]

^<<v22-8-9,9>>^ “Se ela for uma muralha,
Construiremos sobre ela um parapeito de prata;
Mas, se ela for uma porta,
Iremos fechá-la com uma tábua de cedro.”

[[v22-8-10]]

^<<v22-8-10,10>>^ “Sou uma muralha,
E os meus seios são como torres.
Assim, tornei-me aos seus olhos
Como alguém que encontra a paz.

[[v22-8-11]]

^<<v22-8-11,11>>^ Salomão tinha uma vinha em Baal-Hamom.
Ele confiou a vinha a lavradores.^&#42;1^
Cada um deles dava-lhe mil peças de prata pelos seus frutos.

[NOTE]
====
. Ou: “guardiões”.
====

[[v22-8-12]]

^<<v22-8-12,12>>^ Eu tenho a minha própria vinha à minha disposição.
As mil peças de prata^&#42;1^ pertencem-te, ó Salomão,
E duzentas pertencem aos que tomam conta dos teus frutos.”

[NOTE]
====
. Lit.: “Os mil”.
====

[[v22-8-13]]

^<<v22-8-13,13>>^ “Ó tu que moras nos jardins,
Os companheiros prestam atenção à tua voz.
Deixa-me também ouvi-la.”

[[v22-8-14]]

^<<v22-8-14,14>>^ “Corre, meu querido,
Sê veloz como uma gazela
Ou como um filhote de corça
Sobre os montes de bálsamo.”^&#42;1^

[NOTE]
====
. Ou: “especiarias”.
====

'''

xref:022-cantico-de-salomao/022-cantico-de-salomao-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]