include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-13-1]]

^<<v12-13-1,1>>^ No vigésimo terceiro ano de Jeoás, filho de Acazias, rei de Judá, Jeoacaz, filho de Jeú, tornou-se rei sobre Israel, em Samaria, e reinou durante 17 anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ Ele fazia o que era mau aos olhos de Jeová e cometia o mesmo pecado que Jeroboão, filho de Nebate, tinha levado Israel a cometer. Não se desviou dele.

[[v12-13-3]]

^<<v12-13-3,3>>^ Por isso, a ira de Jeová acendeu-se contra Israel, e, durante todos aqueles dias, entregou-os nas mãos de Hazael, rei da Síria, e nas mãos de Ben-Hadade, filho de Hazael.

[[v12-13-4]]

^<<v12-13-4,4>>^ Com o tempo, Jeoacaz implorou o favor^&#42;1^ de Jeová, e Jeová ouviu-o, porque viu a opressão que o rei da Síria causava a Israel.

[NOTE]
====
. Ou: “abrandou a face”.
====

[[v12-13-5]]

^<<v12-13-5,5>>^ Assim, Jeová deu um salvador a Israel, para os livrar das mãos da Síria; e os israelitas puderam morar nos seus lares como dantes.^&#42;1^

[NOTE]
====
. Isto é, em paz e segurança.
====

[[v12-13-6]]

^<<v12-13-6,6>>^ (Contudo, eles não se desviaram do pecado da casa de Jeroboão, que ele tinha levado Israel a cometer. Continuaram a cometer o mesmo pecado,^&#42;1^ e o poste sagrado^&#42;2^ continuava de pé em Samaria.)

[NOTE]
====
. Lit.: “Nele ele andou”.
. Veja o Glossário.
====

[[v12-13-7]]

^<<v12-13-7,7>>^ Jeoacaz ficou com um exército de apenas 50 cavaleiros, dez carros de guerra e 10 000 soldados a pé, porque o rei da Síria os tinha destruído, desfazendo-os como o pó na eira.

[[v12-13-8]]

^<<v12-13-8,8>>^ Quanto aos outros acontecimentos da história de Jeoacaz, tudo o que ele fez e os seus atos poderosos, não estão escritos no livro da história da época dos reis de Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ Por fim, Jeoacaz descansou com os seus antepassados, e enterraram-no em Samaria; e Jeoás, seu filho, tornou-se rei no seu lugar.

[[v12-13-10]]

^<<v12-13-10,10>>^ No trigésimo sétimo ano de Jeoás, rei de Judá, Jeoás, filho de Jeoacaz, tornou-se rei sobre Israel, em Samaria, e reinou durante 16 anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ Ele fazia o que era mau aos olhos de Jeová, não se desviou de todos os pecados que Jeroboão, filho de Nebate, tinha levado Israel a cometer. Continuou a cometer os mesmos pecados.^&#42;1^

[NOTE]
====
. Lit.: “Andou neles.”
====

[[v12-13-12]]

^<<v12-13-12,12>>^ Quanto aos outros acontecimentos da história de Jeoás, tudo o que ele fez, os seus atos poderosos e como lutou contra Amazias, rei de Judá, não estão escritos no livro da história da época dos reis de Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ Por fim, Jeoás descansou com os seus antepassados, e Jeroboão^&#42;1^ sentou-se no seu trono. Jeoás foi enterrado em Samaria, com os reis de Israel.

[NOTE]
====
. Isto é, Jeroboão II.
====

[[v12-13-14]]

^<<v12-13-14,14>>^ Quando Eliseu ficou doente com a doença que por fim o levaria à morte, Jeoás, rei de Israel, foi ter com ele, debruçou-se sobre ele e começou a chorar, dizendo: “Meu pai, meu pai! O carro de guerra de Israel e os seus cavaleiros!”

[[v12-13-15]]

^<<v12-13-15,15>>^ Eliseu disse-lhe: “Pegue num arco e flechas.” E ele pegou num arco e flechas.

[[v12-13-16]]

^<<v12-13-16,16>>^ A seguir, ele disse ao rei de Israel: “Prepare-se para atirar.” Portanto, ele preparou-se para atirar, e Eliseu colocou as suas mãos sobre as mãos do rei.

[[v12-13-17]]

^<<v12-13-17,17>>^ De seguida, ele disse: “Abra a janela que dá para o leste.” Ele abriu-a. Eliseu disse: “Atire!” E ele atirou. Eliseu disse: “A flecha de vitória^&#42;1^ de Jeová, a flecha de vitória sobre^&#42;2^ a Síria! O senhor golpeará^&#42;3^ a Síria em Afeque até acabar com ela.”

[NOTE]
====
. Ou: “salvação”.
. Ou: “salvação contra”.
. Ou: “derrotará”.
====

[[v12-13-18]]

^<<v12-13-18,18>>^ Eliseu acrescentou: “Pegue nas flechas.” E ele pegou nelas. Ele disse ao rei de Israel: “Golpeie o chão.” E ele golpeou o chão três vezes e parou.

[[v12-13-19]]

^<<v12-13-19,19>>^ Em vista disso, o homem do verdadeiro Deus ficou indignado com ele e disse: “O senhor devia ter golpeado o chão cinco ou seis vezes! Então, golpearia a Síria até acabar com ela, mas, agora, apenas golpeará a Síria três vezes.”

[[v12-13-20]]

^<<v12-13-20,20>>^ Depois disso, Eliseu morreu e foi enterrado. Havia bandos de saqueadores moabitas que costumavam vir ao país no início do ano.^&#42;1^

[NOTE]
====
. Lit.: “na entrada do ano”, provavelmente na primavera.
====

[[v12-13-21]]

^<<v12-13-21,21>>^ E aconteceu que algumas pessoas estavam a enterrar um homem quando viram um bando de saqueadores. Por isso, atiraram rapidamente o homem para a sepultura de Eliseu e fugiram. Quando o corpo do homem tocou nos ossos de Eliseu, o homem voltou a viver e ficou de pé.

[[v12-13-22]]

^<<v12-13-22,22>>^ Hazael, rei da Síria, oprimiu Israel durante todos os dias de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ No entanto, Jeová mostrou-lhes favor e misericórdia, e teve consideração por eles por causa do seu pacto com Abraão, Isaque e Jacó. Ele não os quis destruir nem os expulsou da sua presença até ao dia de hoje.

[[v12-13-24]]

^<<v12-13-24,24>>^ Quando Hazael, rei da Síria, morreu, Ben-Hadade, seu filho, tornou-se rei no seu lugar.

[[v12-13-25]]

^<<v12-13-25,25>>^ Jeoás, filho de Jeoacaz, tomou então de Ben-Hadade, filho de Hazael, as cidades que ele tinha tomado de Jeoacaz, seu pai, na guerra. Jeoás golpeou-o^&#42;1^ três vezes e recuperou as cidades de Israel.

[NOTE]
====
. Ou: “derrotou-o”.
====

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]