include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-8-1]]

^<<v12-8-1,1>>^ Eliseu disse à mulher, cujo filho tinha trazido de volta à vida:^&#42;1^ “Levanta-te e vai com os da tua casa e mora como estrangeira onde puderes, pois Jeová declarou que haverá uma fome no país que durará sete anos.”

[NOTE]
====
. Ou: “tinha feito reviver”.
====

[[v12-8-2]]

^<<v12-8-2,2>>^ Portanto, a mulher levantou-se e fez o que o homem do verdadeiro Deus disse. Ela foi com os da sua casa e ficou a morar na terra dos filisteus durante sete anos.

[[v12-8-3]]

^<<v12-8-3,3>>^ Passados sete anos, a mulher voltou da terra dos filisteus e foi pedir ao rei que lhe devolvessem a sua casa e o seu campo.

[[v12-8-4]]

^<<v12-8-4,4>>^ O rei estava a falar com Geazi, o ajudante do homem do verdadeiro Deus, e disse: “Por favor, conta-me todas as coisas grandiosas que Eliseu tem feito.”

[[v12-8-5]]

^<<v12-8-5,5>>^ No preciso momento em que ele contava ao rei como Eliseu tinha feito o morto voltar a viver, chegou a mulher cujo filho ele tinha trazido de volta à vida, pedindo ao rei a sua casa e o seu campo. Geazi disse imediatamente: “Meu senhor, o rei, esta é a mulher e este é o seu filho, que Eliseu trouxe de volta à vida.”

[[v12-8-6]]

^<<v12-8-6,6>>^ Então, o rei perguntou à mulher como é que isso tinha acontecido, e ela contou-lhe a história. E o rei colocou-lhe à disposição um oficial da corte, dizendo-lhe: “Devolve-lhe tudo o que lhe pertence e todo o valor da produção do seu campo, desde o dia em que ela deixou o país até agora.”

[[v12-8-7]]

^<<v12-8-7,7>>^ Eliseu foi a Damasco na mesma altura em que Ben-Hadade, rei da Síria, estava doente. Portanto, informaram-no: “O homem do verdadeiro Deus está aqui.”

[[v12-8-8]]

^<<v12-8-8,8>>^ O rei disse então a Hazael: “Vai ter com o homem do verdadeiro Deus e leva um presente. Consulta a Jeová por meio dele, perguntando: ‘Vou recuperar-me desta doença?’”

[[v12-8-9]]

^<<v12-8-9,9>>^ Hazael foi ter com Eliseu e levou um presente, todo o tipo de coisas boas de Damasco, carregado por 40 camelos. Ele chegou, ficou diante dele e disse: “O seu filho, Ben-Hadade, rei da Síria, enviou-me a si para perguntar: ‘Vou recuperar-me desta doença?’”

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu respondeu-lhe: “Vai e diz-lhe: ‘Certamente se recuperará’; mas Jeová mostrou-me que ele certamente morrerá.”

[[v12-8-11]]

^<<v12-8-11,11>>^ E Eliseu ficou a olhar fixamente para ele, até Hazael ficar constrangido. Depois, o homem do verdadeiro Deus começou a chorar.

[[v12-8-12]]

^<<v12-8-12,12>>^ Hazael perguntou: “Porque é que está a chorar, meu senhor?” Ele respondeu: “Porque sei o mal que farás ao povo de Israel. Incendiarás as suas fortificações, matarás com a espada os melhores homens, despedaçarás as crianças e rasgarás o ventre das mulheres grávidas.”

[[v12-8-13]]

^<<v12-8-13,13>>^ Hazael disse: “Como poderia o seu servo, que não passa de um cão, fazer tais coisas?” Contudo, Eliseu respondeu: “Jeová mostrou-me que tu serás rei sobre a Síria.”

[[v12-8-14]]

^<<v12-8-14,14>>^ A seguir, ele saiu de diante de Eliseu e voltou ao seu senhor, que lhe perguntou: “O que é que Eliseu te disse?” Ele respondeu: “Ele disse-me que o senhor com certeza se recuperará.”

[[v12-8-15]]

^<<v12-8-15,15>>^ No dia seguinte, porém, Hazael pegou numa colcha, mergulhou-a em água e segurou-a^&#42;1^ sobre o rosto do rei até ele morrer. E Hazael tornou-se rei no seu lugar.

[NOTE]
====
. Ou: “colocou-a”.
====

[[v12-8-16]]

^<<v12-8-16,16>>^ No quinto ano de Jeorão, filho de Acabe, rei de Israel — enquanto Jeosafá era rei de Judá —, Jeorão, filho de Jeosafá, rei de Judá, tornou-se rei.

[[v12-8-17]]

^<<v12-8-17,17>>^ Ele tinha 32 anos de idade quando se tornou rei, e reinou durante oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ Ele andava no caminho dos reis de Israel, assim como os da casa de Acabe tinham feito, pois a filha de Acabe tinha-se tornado sua esposa; e ele fazia o que era mau aos olhos de Jeová.

[[v12-8-19]]

^<<v12-8-19,19>>^ Contudo, Jeová não quis destruir Judá, por causa de David, seu servo, visto que lhe tinha prometido dar uma lâmpada, a ele e aos seus filhos, para sempre.

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos dias de Jeorão, Edom rebelou-se contra Judá e estabeleceu o seu próprio rei.

[[v12-8-21]]

^<<v12-8-21,21>>^ Por isso, Jeorão foi a Zair com todos os seus carros de guerra. De noite, ele atacou e derrotou os edomitas que o cercavam, a ele e aos chefes dos carros de guerra; e os soldados fugiram para as suas tendas.

[[v12-8-22]]

^<<v12-8-22,22>>^ No entanto, a revolta de Edom contra Judá continua até ao dia de hoje. Libna também se rebelou naquela altura.

[[v12-8-23]]

^<<v12-8-23,23>>^ Quanto aos outros acontecimentos da história de Jeorão, tudo o que ele fez, não estão escritos no livro da história da época dos reis de Judá?

[[v12-8-24]]

^<<v12-8-24,24>>^ Por fim, Jeorão descansou com os seus antepassados e foi enterrado com os seus antepassados na Cidade de David. E Acazias, seu filho, tornou-se rei no seu lugar.

[[v12-8-25]]

^<<v12-8-25,25>>^ No décimo segundo ano de Jeorão, filho de Acabe, rei de Israel, Acazias, filho de Jeorão, rei de Judá, tornou-se rei.

[[v12-8-26]]

^<<v12-8-26,26>>^ Acazias tinha 22 anos de idade quando se tornou rei, e reinou durante um ano em Jerusalém. O nome da sua mãe era Atalia, neta^&#42;1^ de Onri, rei de Israel.

[NOTE]
====
. Lit.: “filha”.
====

[[v12-8-27]]

^<<v12-8-27,27>>^ Acazias andava no caminho da casa de Acabe e fazia o que era mau aos olhos de Jeová, assim como os da casa de Acabe, pois o seu pai era casado com uma mulher da casa de Acabe.

[[v12-8-28]]

^<<v12-8-28,28>>^ E ele foi com Jeorão, filho de Acabe, guerrear contra Hazael, rei da Síria, em Ramote-Gileade, mas os sírios feriram Jeorão.

[[v12-8-29]]

^<<v12-8-29,29>>^ Portanto, o rei Jeorão regressou a Jezreel para se recuperar dos ferimentos que os sírios lhe causaram em Ramá, quando lutou contra Hazael, rei da Síria. E Acazias, filho de Jeorão, rei de Judá, desceu a Jezreel para visitar Jeorão, filho de Acabe, porque ele estava ferido.^&#42;1^

[NOTE]
====
. Ou: “doente”.
====

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]