include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-6-1]]

^<<v12-6-1,1>>^ Os filhos dos profetas disseram a Eliseu: “Como vê, o lugar em que estamos a morar consigo é demasiado apertado para nós.

[[v12-6-2]]

^<<v12-6-2,2>>^ Por favor, deixe-nos ir até ao Jordão. Cada um tirará dali um tronco e ali faremos um lugar para morar.” Ele respondeu: “Vão.”

[[v12-6-3]]

^<<v12-6-3,3>>^ Um deles disse: “Poderia, por favor, vir com os seus servos?” Ele respondeu: “Eu irei.”

[[v12-6-4]]

^<<v12-6-4,4>>^ Portanto, foi com eles. Ao chegarem ao Jordão, começaram a cortar árvores.

[[v12-6-5]]

^<<v12-6-5,5>>^ Quando um dos profetas estava a cortar uma árvore, o ferro do machado caiu na água, e ele gritou: “Ai, meu senhor, era emprestado!”

[[v12-6-6]]

^<<v12-6-6,6>>^ O homem do verdadeiro Deus perguntou: “Onde é que ele caiu?” Ele mostrou-lhe o lugar. Por conseguinte, Eliseu cortou um pedaço de madeira e atirou-o à água naquele lugar, e fez o ferro do machado flutuar.

[[v12-6-7]]

^<<v12-6-7,7>>^ Ele disse: “Apanha-o.” O homem estendeu a mão e apanhou-o.

[[v12-6-8]]

^<<v12-6-8,8>>^ O rei da Síria foi guerrear contra Israel. Ele consultou os seus servos e disse: “Acamparei convosco em tal lugar.”

[[v12-6-9]]

^<<v12-6-9,9>>^ Então, o homem do verdadeiro Deus mandou dizer ao rei de Israel: “Cuidado, não passe por tal lugar, porque é para lá que os sírios estão a ir.”

[[v12-6-10]]

^<<v12-6-10,10>>^ Portanto, o rei de Israel enviou uma mensagem para o lugar que o homem do verdadeiro Deus lhe tinha mencionado. Eliseu continuou a alertar o rei, e ele mantinha-se afastado desses locais; isto aconteceu em várias ocasiões.^&#42;1^

[NOTE]
====
. Ou: “Isto aconteceu mais do que uma ou duas vezes”.
====

[[v12-6-11]]

^<<v12-6-11,11>>^ Isso deixou o rei^&#42;1^ da Síria furioso, de modo que ele convocou os seus servos e disse-lhes: “Digam-me! Quem dentre nós está do lado do rei de Israel?”

[NOTE]
====
. Lit.: “o coração do rei”.
====

[[v12-6-12]]

^<<v12-6-12,12>>^ Um dos seus servos respondeu: “Nenhum de nós, meu senhor, o rei! É Eliseu, o profeta que está em Israel, que informa o rei de Israel sobre as coisas que o senhor diz no seu quarto.”

[[v12-6-13]]

^<<v12-6-13,13>>^ Ele disse: “Vão e descubram onde ele está, para que eu mande homens para o capturar.” Mais tarde, informaram-no: “Ele está em Dotã.”

[[v12-6-14]]

^<<v12-6-14,14>>^ O rei enviou imediatamente para lá cavalos, carros de guerra e um grande exército; eles chegaram de noite e cercaram a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ Quando o ajudante^&#42;1^ do homem do verdadeiro Deus se levantou cedo e saiu, viu que um exército cercava a cidade com cavalos e carros de guerra. Imediatamente, o ajudante disse-lhe: “Ai, meu senhor! O que é que vamos fazer?”

[NOTE]
====
. Ou: “servo”.
====

[[v12-6-16]]

^<<v12-6-16,16>>^ Ele, porém, respondeu: “Não tenhas medo! Pois os que estão connosco são mais numerosos do que os que estão com eles.”

[[v12-6-17]]

^<<v12-6-17,17>>^ Então, Eliseu começou a orar, dizendo: “Ó Jeová, por favor, abre-lhe os olhos para que veja.” Jeová abriu imediatamente os olhos do ajudante, e ele viu que a região montanhosa estava cheia de cavalos e carros de guerra, de fogo, em volta de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ Quando os sírios desceram na sua direção, Eliseu orou a Jeová, dizendo: “Por favor, atinge esta nação com cegueira.” Por conseguinte, ele atingiu-os com cegueira, assim como Eliseu tinha pedido.

[[v12-6-19]]

^<<v12-6-19,19>>^ Eliseu disse-lhes então: “Este não é o caminho, e esta não é a cidade. Sigam-me, vou levar-vos até ao homem que procuram.” Todavia, ele levou-os até Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Quando eles chegaram a Samaria, Eliseu disse: “Ó Jeová, abre-lhes os olhos para que vejam.” Então, Jeová abriu-lhes os olhos e eles viram que estavam no meio de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ Quando o rei de Israel os viu, perguntou a Eliseu: “Devo matá-los, meu pai? Devo matá-los?”

[[v12-6-22]]

^<<v12-6-22,22>>^ Contudo, ele respondeu: “Não os mate. Por acaso mataria os que tivesse capturado com a espada e com o arco? Dê-lhes pão e água para que comam, bebam e depois voltem para o seu senhor.”

[[v12-6-23]]

^<<v12-6-23,23>>^ Assim, o rei fez-lhes um grande banquete, e eles comeram e beberam; depois, mandou-os embora e voltaram para o seu senhor. E os bandos de saqueadores sírios não voltaram nem mais uma única vez à terra de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Depois disso, Ben-Hadade, rei da Síria, reuniu todo o seu exército,^&#42;1^ subiu até Samaria e cercou-a.

[NOTE]
====
. Lit.: “acampamento”.
====

[[v12-6-25]]

^<<v12-6-25,25>>^ Por isso, houve uma grande fome em Samaria, e os sírios mantiveram o cerco até a cabeça de um jumento valer 80 peças de prata, e um quarto de um cabo^&#42;1^ de esterco de pomba valer cinco peças de prata.

[NOTE]
====
. Um cabo equivalia a 1,22 l. Veja o Ap. B14.
====

[[v12-6-26]]

^<<v12-6-26,26>>^ Enquanto o rei de Israel caminhava em cima da muralha, uma mulher gritou-lhe: “Ajude-nos, ó meu senhor, o rei!”

[[v12-6-27]]

^<<v12-6-27,27>>^ Então, ele disse: “Se Jeová não te ajuda, onde é que eu encontrarei ajuda para ti? Sobrou, por acaso, algo na eira e no lagar de vinho ou de azeite?”

[[v12-6-28]]

^<<v12-6-28,28>>^ O rei perguntou-lhe: “Qual é o teu problema?” Ela respondeu: “Esta mulher disse-me: ‘Dá cá o teu filho para que o comamos hoje, e amanhã comeremos o meu filho.’

[[v12-6-29]]

^<<v12-6-29,29>>^ Assim, cozinhámos o meu filho e comemo-lo. No dia seguinte, eu disse-lhe: ‘Dá cá o teu filho para que o comamos.’ Mas ela escondeu o filho.”

[[v12-6-30]]

^<<v12-6-30,30>>^ Assim que o rei ouviu as palavras da mulher, rasgou a sua roupa. Enquanto caminhava em cima da muralha, o povo viu que ele estava vestido de serapilheira^&#42;1^ por baixo da roupa.^&#42;2^

[NOTE]
====
. Veja o Glossário.
. Ou: “por baixo, junto à pele”.
====

[[v12-6-31]]

^<<v12-6-31,31>>^ Então, ele disse: “Que Deus me castigue, e que o faça severamente, se a cabeça de Eliseu, filho de Safate, continuar hoje sobre ele!”

[[v12-6-32]]

^<<v12-6-32,32>>^ Eliseu estava sentado na sua casa, e os anciãos estavam sentados com ele. O rei enviou um mensageiro à sua frente, mas, antes de ele chegar, Eliseu disse aos anciãos: “Viram como é que este filho de um assassino mandou cortar a minha cabeça? Fiquem atentos. Quando o mensageiro chegar, fechem a porta e segurem-na para que ele não entre. Não estão a ouvir os passos do seu senhor atrás dele?”

[[v12-6-33]]

^<<v12-6-33,33>>^ Enquanto ainda falava com eles, o mensageiro chegou, e o rei disse: “Esta calamidade é da parte de Jeová. Porque é que eu deveria continuar à espera de Jeová?”

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]