include::./index.adoc[]

[[v12-17-0]]
=== 2 Reis, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-17-1]]

^<<v12-17-1,1>>^ No décimo segundo ano de Acaz, rei de Judá, Oseias, filho de Elá, tornou-se rei sobre Israel, em Samaria, e reinou durante nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ Ele fazia o que era mau aos olhos de Jeová, mas não tanto como os reis de Israel que reinaram antes dele.

[[v12-17-3]]

^<<v12-17-3,3>>^ Salmaneser, rei da Assíria, veio contra ele, e Oseias tornou-se seu servo e começou a pagar-lhe tributo.

[[v12-17-4]]

^<<v12-17-4,4>>^ No entanto, o rei da Assíria soube que Oseias estava envolvido numa conspiração, porque ele tinha enviado mensageiros a Só, rei do Egito, e já não levava o tributo ao rei da Assíria, como nos anos anteriores. Por isso, o rei da Assíria manteve-o fechado e amarrado na prisão.

[[v12-17-5]]

^<<v12-17-5,5>>^ O rei da Assíria invadiu todo o país; chegou a Samaria e cercou-a durante três anos.

[[v12-17-6]]

^<<v12-17-6,6>>^ No nono ano de Oseias, o rei da Assíria tomou Samaria. Depois, levou o povo de Israel para o exílio na Assíria, e fê-los morar em Hala e em Habor, ao pé do rio Gozã, e nas cidades dos medos.

[[v12-17-7]]

^<<v12-17-7,7>>^ Isto aconteceu porque o povo de Israel tinha pecado contra Jeová, seu Deus, que os tinha tirado da terra do Egito, do domínio do Faraó, rei do Egito. Eles adoraram^&#42;1^ outros deuses,

[NOTE]
====
. Lit.: “temeram”.
====

[[v12-17-8]]

^<<v12-17-8,8>>^ seguiram os costumes das nações que Jeová tinha expulsado de diante dos israelitas e os costumes que os reis de Israel tinham estabelecido.

[[v12-17-9]]

^<<v12-17-9,9>>^ Os israelitas procuravam coisas que não eram certas aos olhos de Jeová, seu Deus. Construíram altos sagrados em todas as suas cidades, desde a torre de vigia até à cidade fortificada.^&#42;1^

[NOTE]
====
. Isto é, em todos os lugares, tanto nos pouco habitados como nos populosos.
====

[[v12-17-10]]

^<<v12-17-10,10>>^ Eles ergueram para si colunas sagradas e postes sagrados^&#42;1^ em todas as colinas elevadas e debaixo de todas as árvores frondosas;

[NOTE]
====
. Veja o Glossário.
====

[[v12-17-11]]

^<<v12-17-11,11>>^ e, em todos os altos sagrados, faziam fumo sacrificial, assim como fizeram as nações que Jeová tinha expulsado de diante deles. Faziam coisas más para ofender a Jeová.

[[v12-17-12]]

^<<v12-17-12,12>>^ Eles continuaram a servir a ídolos repugnantes,^&#42;1^ sobre os quais Jeová lhes tinha dito: “Não façam isso!”

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v12-17-13]]

^<<v12-17-13,13>>^ Jeová continuou a advertir Israel e Judá por meio de todos os seus profetas e de todos os videntes,^&#42;1^ dizendo: “Recuem dos vossos maus caminhos! Guardem os meus mandamentos e os meus decretos, segundo toda a lei que ordenei aos vossos antepassados e que vos transmiti por meio dos meus servos, os profetas.”

[NOTE]
====
. Veja o Glossário.
====

[[v12-17-14]]

^<<v12-17-14,14>>^ Contudo, eles não escutaram, e continuaram tão obstinados como os^&#42;1^ seus antepassados que não tinham mostrado fé em Jeová, seu Deus.

[NOTE]
====
. Lit.: “endureceram a sua cerviz como a cerviz dos”.
====

[[v12-17-15]]

^<<v12-17-15,15>>^ Eles continuaram a rejeitar os seus decretos, o pacto que ele tinha feito com os seus antepassados e as advertências^&#42;1^ que lhes tinha dado como aviso, e seguiam ídolos inúteis, tornando-se eles mesmos inúteis. Assim, imitaram as nações ao seu redor, que Jeová lhes tinha proibido imitar.

[NOTE]
====
. Ou: “os lembretes”.
====

[[v12-17-16]]

^<<v12-17-16,16>>^ Abandonaram todos os mandamentos de Jeová, seu Deus, fizeram duas estátuas de metal^&#42;1^ em forma de bezerro e um poste sagrado,^&#42;2^ curvaram-se diante de todo o exército dos céus e serviram a Baal.

[NOTE]
====
. Ou: “estátuas fundidas”.
. Veja o Glossário.
====

[[v12-17-17]]

^<<v12-17-17,17>>^ Também queimaram os seus filhos e as suas filhas no fogo,^&#42;1^ praticaram adivinhação, procuraram presságios^&#42;2^ e dedicaram-se^&#42;3^ a fazer o que era mau aos olhos de Jeová, para o ofender.

[NOTE]
====
. Lit.: “fizeram os seus filhos e as suas filhas passar pelo fogo”.
. Ou: “sinais”.
. Lit.: “venderam-se”.
====

[[v12-17-18]]

^<<v12-17-18,18>>^ Por isso, Jeová ficou furioso com Israel e removeu-os da sua vista. Não deixou restar ninguém, apenas a tribo de Judá.

[[v12-17-19]]

^<<v12-17-19,19>>^ Nem mesmo Judá guardou os mandamentos de Jeová, seu Deus; eles também seguiram os costumes que Israel seguiu.

[[v12-17-20]]

^<<v12-17-20,20>>^ Jeová rejeitou todos os descendentes de Israel, humilhou-os e entregou-os nas mãos de saqueadores, até os ter expulsado da sua frente.

[[v12-17-21]]

^<<v12-17-21,21>>^ Ele arrancou Israel da casa de David, e eles fizeram rei a Jeroboão, filho de Nebate. No entanto, Jeroboão levou Israel a desviar-se de seguir a Jeová e a cometer um grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ E o povo de Israel cometeu os mesmos pecados que Jeroboão tinha cometido. Não se desviaram deles,

[[v12-17-23]]

^<<v12-17-23,23>>^ até que Jeová removeu Israel da sua vista, assim como tinha dito por meio de todos os seus servos, os profetas. Portanto, Israel foi levado da sua terra para o exílio na Assíria, onde continuam até ao dia de hoje.

[[v12-17-24]]

^<<v12-17-24,24>>^ Depois, o rei da Assíria trouxe gente de Babilónia, Cuta, Ava, Hamate e Sefarvaim, e estabeleceu-os nas cidades de Samaria, em substituição dos israelitas; eles tomaram posse de Samaria e moraram nas suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ Quando começaram a morar ali, não temiam^&#42;1^ a Jeová. Por isso, Jeová enviou-lhes leões, que mataram alguns deles.

[NOTE]
====
. Ou: “não adoravam”.
====

[[v12-17-26]]

^<<v12-17-26,26>>^ Informaram o rei da Assíria: “As nações que o senhor levou para o exílio e estabeleceu nas cidades de Samaria não sabem como adorar o Deus do país. Por isso, ele está a enviar-lhes leões, que os estão a matar, visto que ninguém sabe como adorar o Deus do país.”

[[v12-17-27]]

^<<v12-17-27,27>>^ Em vista disso, o rei da Assíria ordenou: “Façam com que um dos sacerdotes que levaram de lá para o exílio volte a fim de morar lá e de lhes ensinar como adorar o Deus do país.”

[[v12-17-28]]

^<<v12-17-28,28>>^ Assim, um dos sacerdotes que tinham levado de Samaria para o exílio voltou a morar em Betel, e começou a ensinar-lhes como deviam temer^&#42;1^ a Jeová.

[NOTE]
====
. Ou: “adorar”.
====

[[v12-17-29]]

^<<v12-17-29,29>>^ No entanto, cada nação fez o seu próprio deus,^&#42;1^ e colocaram-nos nos santuários dos altos sagrados que os samaritanos tinham feito; cada nação fez isso nas cidades em que morava.

[NOTE]
====
. Ou: “os seus próprios deuses”.
====

[[v12-17-30]]

^<<v12-17-30,30>>^ Assim, os homens de Babilónia fizeram Sucote-Benote, os homens de Cute fizeram Nergal, os homens de Hamate fizeram Asima

[[v12-17-31]]

^<<v12-17-31,31>>^ e os avitas fizeram Nibaz e Tartaque. Os sefarvitas queimavam os seus filhos no fogo para Adrameleque e Anameleque, deuses de Sefarvaim.

[[v12-17-32]]

^<<v12-17-32,32>>^ Embora eles temessem a Jeová, designaram homens do povo em geral para serem sacerdotes de altos sagrados, e estes oficiavam a favor deles nos santuários dos altos sagrados.

[[v12-17-33]]

^<<v12-17-33,33>>^ Assim, temiam a Jeová, mas adoravam os seus próprios deuses, de acordo com a religião^&#42;1^ das nações de onde tinham sido trazidos.

[NOTE]
====
. Ou: “os costumes religiosos”.
====

[[v12-17-34]]

^<<v12-17-34,34>>^ Até ao dia de hoje, eles seguem as suas religiões^&#42;1^ anteriores. Nenhum deles adora^&#42;2^ a Jeová e ninguém cumpre os seus decretos, as suas decisões judiciais, nem a Lei e o mandamento que Jeová deu aos filhos de Jacó, cujo nome ele mudou para Israel.

[NOTE]
====
. Ou: “os seus costumes religiosos”.
. Lit.: “teme”.
====

[[v12-17-35]]

^<<v12-17-35,35>>^ Quando Jeová fez um pacto com eles, ordenou-lhes: “Não temam outros deuses, e não se curvem diante deles, nem os sirvam, nem lhes ofereçam sacrifícios.

[[v12-17-36]]

^<<v12-17-36,36>>^ Mas é a Jeová que devem temer, aquele que vos tirou da terra do Egito com grande poder e com braço estendido; é diante dele que se devem curvar e é a ele que devem oferecer sacrifícios.

[[v12-17-37]]

^<<v12-17-37,37>>^ E devem sempre cumprir cuidadosamente os decretos, as decisões judiciais, a Lei e o mandamento que ele vos escreveu. Não temam outros deuses.

[[v12-17-38]]

^<<v12-17-38,38>>^ Não se esqueçam do pacto que fiz convosco e não temam outros deuses.

[[v12-17-39]]

^<<v12-17-39,39>>^ Mas é a Jeová, vosso Deus, que devem temer, pois é ele quem vos livrará das mãos de todos os vossos inimigos.”

[[v12-17-40]]

^<<v12-17-40,40>>^ Porém, eles não obedeceram e seguiram a sua religião anterior.^&#42;1^

[NOTE]
====
. Ou: “os seus costumes religiosos anteriores”.
====

[[v12-17-41]]

^<<v12-17-41,41>>^ Assim, estas nações passaram a temer a Jeová, mas também serviam às suas próprias imagens esculpidas. E até ao dia de hoje, tanto os seus filhos como os seus netos continuam a fazer assim como os seus antepassados fizeram.

'''

xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]