include::./index.adoc[]

[[v12-11-0]]
=== 2 Reis, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-11-1]]

^<<v12-11-1,1>>^ Quando Atalia, mãe de Acazias, viu que o seu filho tinha morrido, exterminou toda a linhagem real.^&#42;1^

[NOTE]
====
. Lit.: “toda a semente do reino”.
====

[[v12-11-2]]

^<<v12-11-2,2>>^ No entanto, Jeoseba, filha do rei Jeorão, irmã de Acazias, tirou Jeoás, filho de Acazias, dentre os filhos do rei que iam ser mortos e escondeu-o num quarto com a sua ama. Conseguiram mantê-lo escondido de Atalia, de modo que ele não foi morto.

[[v12-11-3]]

^<<v12-11-3,3>>^ Ele ficou escondido com ela na casa de Jeová durante seis anos, enquanto Atalia reinava sobre o país.

[[v12-11-4]]

^<<v12-11-4,4>>^ No sétimo ano, Jeoiada mandou chamar os chefes de cem da escolta cariana e dos guardas do palácio^&#42;1^ para que viessem ter com ele à casa de Jeová. Ele fez um pacto com eles e fê-los jurar na casa de Jeová; depois mostrou-lhes o filho do rei.

[NOTE]
====
. Lit.: “corredores”.
====

[[v12-11-5]]

^<<v12-11-5,5>>^ Ele ordenou-lhes: “Façam o seguinte: um terço de vocês estará de serviço no sábado e manterá estrita vigilância sobre a casa^&#42;1^ do rei,

[NOTE]
====
. Ou: “o palácio”.
====

[[v12-11-6]]

^<<v12-11-6,6>>^ outro terço ficará no Portão do Alicerce e o outro terço ficará no portão atrás dos guardas do palácio. Irão revezar-se em vigiar a casa.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “o templo”.
====

[[v12-11-7]]

^<<v12-11-7,7>>^ As duas divisões que estariam de folga no sábado manterão rigorosa vigilância sobre a casa de Jeová para proteger o rei.

[[v12-11-8]]

^<<v12-11-8,8>>^ Devem ficar à volta do rei, cada um com as suas armas na mão. Quem atravessar as vossas fileiras será morto. Fiquem com o rei onde quer que ele for.”^&#42;1^

[NOTE]
====
. Lit.: “quando ele sair e quando ele entrar”.
====

[[v12-11-9]]

^<<v12-11-9,9>>^ Os chefes de cem fizeram exatamente o que Jeoiada, o sacerdote, tinha ordenado. Portanto, cada um reuniu os seus homens que estavam de serviço no sábado e os que estavam de folga no sábado, e foram ter com Jeoiada, o sacerdote.

[[v12-11-10]]

^<<v12-11-10,10>>^ O sacerdote deu então aos chefes de cem as lanças e os escudos redondos que tinham pertencido ao rei David e que estavam na casa de Jeová.

[[v12-11-11]]

^<<v12-11-11,11>>^ E os guardas do palácio posicionaram-se, cada um com as suas armas na mão, desde o lado direito da casa até ao lado esquerdo da casa, junto ao altar e junto à casa, à volta do rei.

[[v12-11-12]]

^<<v12-11-12,12>>^ Então, Jeoiada trouxe para fora o filho do rei e pôs-lhe a coroa^&#42;1^ e o Testemunho;^&#42;2^ eles fizeram-no rei e ungiram-no. E começaram a bater palmas e a dizer: “Viva o rei!”

[NOTE]
====
. Ou: “o diadema”.
. Possivelmente um rolo que continha a Lei de Deus.
====

[[v12-11-13]]

^<<v12-11-13,13>>^ Quando Atalia ouviu o barulho do povo a correr, foi imediatamente ter com o povo à casa de Jeová.

[[v12-11-14]]

^<<v12-11-14,14>>^ Então, ela viu o rei de pé junto à coluna, como era costume. Os chefes de cem^&#42;1^ e os que tocavam as trombetas estavam com o rei, e todo o povo^&#42;2^ se alegrava e tocava trombetas. Em vista disso, Atalia rasgou a sua roupa e gritou: “Conspiração! Conspiração!”

[NOTE]
====
. Lit.: “Os chefes”.
. Lit.: “povo da terra”.
====

[[v12-11-15]]

^<<v12-11-15,15>>^ Contudo, Jeoiada, o sacerdote, ordenou aos chefes de cem, os encarregados do exército: “Tirem-na do meio das fileiras, e matem com a espada quem for atrás dela!” Pois o sacerdote tinha dito: “Não a matem dentro da casa de Jeová.”

[[v12-11-16]]

^<<v12-11-16,16>>^ Assim, eles agarraram-na e levaram-na até ao lugar onde os cavalos entram na casa^&#42;1^ do rei; e ali ela foi morta.

[NOTE]
====
. Ou: “no palácio”.
====

[[v12-11-17]]

^<<v12-11-17,17>>^ Então, Jeoiada fez um pacto entre Jeová, o rei e o povo, segundo o qual continuariam a ser o povo de Jeová; e também fez um pacto entre o rei e o povo.

[[v12-11-18]]

^<<v12-11-18,18>>^ Depois disso, todo o povo^&#42;1^ foi à casa^&#42;2^ de Baal e demoliu os seus altares, despedaçou as suas imagens e executou Matã, o sacerdote de Baal, diante dos altares.
A seguir, o sacerdote designou superintendentes sobre a casa de Jeová.

[NOTE]
====
. Lit.: “povo da terra”.
. Ou: “ao templo”.
====

[[v12-11-19]]

^<<v12-11-19,19>>^ Além disso, reuniu os chefes de cem, a escolta cariana, os guardas do palácio e todo o povo,^&#42;1^ para acompanharem o rei da casa de Jeová até à casa^&#42;2^ do rei, pelo caminho do portão da guarda do palácio. Então, ele sentou-se no trono dos reis.

[NOTE]
====
. Lit.: “povo da terra”.
. Ou: “ao palácio”.
====

[[v12-11-20]]

^<<v12-11-20,20>>^ Assim, todo o povo^&#42;1^ se alegrou e a cidade ficou em paz, visto que Atalia tinha sido morta com a espada, junto à casa do rei.

[NOTE]
====
. Lit.: “povo da terra”.
====

[[v12-11-21]]

^<<v12-11-21,21>>^ Jeoás tinha sete anos de idade quando se tornou rei.

'''

xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[Próximo Capítulo &#62;]