include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-2-1]]

^<<v12-2-1,1>>^ Quando Jeová estava prestes a levar Elias para os céus num vendaval, Elias e Eliseu partiram de Gilgal.

[[v12-2-2]]

^<<v12-2-2,2>>^ Elias disse a Eliseu: “Fica aqui, por favor, porque Jeová me enviou a Betel.” Eliseu, porém, disse: “Tão certo como Jeová vive e como o senhor^&#42;1^ vive, não o deixarei.” Portanto, eles desceram até Betel.

[NOTE]
====
. Ou: “a sua alma”.
====

[[v12-2-3]]

^<<v12-2-3,3>>^ Então, os filhos dos profetas^&#42;1^ em Betel foram ter com Eliseu e perguntaram-lhe: “Sabes que hoje Jeová levará embora o teu senhor, aquele que é cabeça sobre ti?” Ele disse: “Eu já sei. Não falem disso.”

[NOTE]
====
. “Filhos dos profetas” parece referir-se a uma escola de instrução para profetas ou a uma associação de profetas.
====

[[v12-2-4]]

^<<v12-2-4,4>>^ Elias disse-lhe então: “Eliseu, por favor, fica aqui, porque Jeová me enviou a Jericó.” Contudo, ele disse: “Tão certo como Jeová vive e como o senhor^&#42;1^ vive, não o deixarei.” Por isso, eles foram até Jericó.

[NOTE]
====
. Ou: “a sua alma”.
====

[[v12-2-5]]

^<<v12-2-5,5>>^ Os filhos dos profetas que estavam em Jericó aproximaram-se de Eliseu e perguntaram-lhe: “Sabes que hoje Jeová levará embora o teu senhor, aquele que é cabeça sobre ti?” Ele disse: “Eu já sei. Não falem disso.”

[[v12-2-6]]

^<<v12-2-6,6>>^ Elias disse-lhe então: “Por favor, fica aqui, porque Jeová me enviou ao Jordão.” Todavia, ele disse: “Tão certo como Jeová vive e como o senhor^&#42;1^ vive, não o deixarei.” Assim, os dois continuaram a caminhar.

[NOTE]
====
. Ou: “a sua alma”.
====

[[v12-2-7]]

^<<v12-2-7,7>>^ E 50 dos filhos dos profetas seguiram-nos e ficaram a olhar de longe quando os dois pararam perto do Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ A seguir, Elias pegou no seu manto oficial, enrolou-o e bateu nas águas, e elas dividiram-se para a esquerda e para a direita, de modo que os dois atravessaram o rio em terra seca.

[[v12-2-9]]

^<<v12-2-9,9>>^ Assim que atravessaram, Elias disse a Eliseu: “Diz-me o que devo fazer por ti antes de eu ser levado embora.” Eliseu disse: “Por favor, será que posso receber uma porção dupla^&#42;1^ do seu espírito?”

[NOTE]
====
. Ou: “duas partes”.
====

[[v12-2-10]]

^<<v12-2-10,10>>^ Ele respondeu: “Pediste uma coisa difícil. Se me vires quando eu for levado embora, acontecerá o que pediste; mas, se não me vires, não acontecerá.”

[[v12-2-11]]

^<<v12-2-11,11>>^ Enquanto andavam e conversavam, de repente, apareceu um carro de fogo e cavalos de fogo que os separaram um do outro; e Elias subiu aos céus no vendaval.

[[v12-2-12]]

^<<v12-2-12,12>>^ Vendo isso, Eliseu gritou: “Meu pai, meu pai! O carro de Israel e os seus cavaleiros!” Quando já não o conseguia ver, pegou nas suas próprias vestes e rasgou-as em duas partes.

[[v12-2-13]]

^<<v12-2-13,13>>^ Depois, pegou no manto oficial de Elias, que lhe tinha caído, voltou para trás e parou à beira do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ Com o manto oficial de Elias, que lhe tinha caído, Eliseu bateu nas águas, dizendo: “Onde está Jeová, o Deus de Elias?” Quando ele bateu nas águas, elas dividiram-se para a esquerda e para a direita, e Eliseu atravessou o rio.

[[v12-2-15]]

^<<v12-2-15,15>>^ Quando os filhos dos profetas em Jericó o viram de longe, disseram: “O espírito de Elias repousou sobre Eliseu.” Portanto, foram ter com ele e curvaram-se por terra diante dele.

[[v12-2-16]]

^<<v12-2-16,16>>^ Eles disseram-lhe: “Estão aqui 50 homens capazes com os teus servos. Por favor, deixa-os ir e procurar o teu senhor. Talvez o espírito^&#42;1^ de Jeová o tenha levado e lançado nalgum monte ou vale.” Porém, ele disse: “Não os enviem.”

[NOTE]
====
. Ou: “vento”.
====

[[v12-2-17]]

^<<v12-2-17,17>>^ No entanto, insistiram tanto que ele ficou constrangido e disse: “Então, enviem-nos.” Assim, enviaram os 50 homens, que o procuraram durante três dias, mas não o encontraram.

[[v12-2-18]]

^<<v12-2-18,18>>^ Quando voltaram para o pé de Eliseu, ele estava em Jericó. Ele disse-lhes: “Eu não vos disse para não irem?”

[[v12-2-19]]

^<<v12-2-19,19>>^ Depois de algum tempo, os homens da cidade disseram a Eliseu: “O meu senhor pode ver que a cidade está bem localizada, mas a água é má e a terra é improdutiva.”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “causa abortos”.
====

[[v12-2-20]]

^<<v12-2-20,20>>^ Portanto, ele disse: “Ponham sal numa tigelinha nova e tragam-ma.” Assim, eles trouxeram-lha.

[[v12-2-21]]

^<<v12-2-21,21>>^ A seguir, ele foi até à nascente da água, deitou-lhe sal e disse: “Assim diz Jeová: ‘Faço esta água ficar boa. Nunca mais causará nem morte nem esterilidade.’”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “abortos”.
====

[[v12-2-22]]

^<<v12-2-22,22>>^ E a água continua boa até ao dia de hoje, conforme a palavra que Eliseu falou.

[[v12-2-23]]

^<<v12-2-23,23>>^ Dali, ele subiu até Betel. Enquanto ia pelo caminho, alguns meninos saíram da cidade e começaram a gozar com ele, dizendo: “Sobe, careca! Sobe, careca!”

[[v12-2-24]]

^<<v12-2-24,24>>^ Por fim, ele virou-se para trás, olhou para eles e amaldiçoou-os em nome de Jeová. Então, duas ursas saíram da floresta e dilaceraram 42 daqueles meninos.

[[v12-2-25]]

^<<v12-2-25,25>>^ Dali, ele foi para o monte Carmelo, e depois voltou para Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]