include::./index.adoc[]

[[v12-12-0]]
=== 2 Reis, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-12-1]]

^<<v12-12-1,1>>^ No sétimo ano de Jeú, Jeoás tornou-se rei e reinou durante 40 anos em Jerusalém. O nome da sua mãe era Zíbia, de Berseba.

[[v12-12-2]]

^<<v12-12-2,2>>^ Jeoás fez o que era certo aos olhos de Jeová durante todos os dias em que Jeoiada, o sacerdote, o instruiu.

[[v12-12-3]]

^<<v12-12-3,3>>^ No entanto, não removeu os altos sagrados e o povo ainda oferecia sacrifícios e fazia fumo sacrificial nos altos sagrados.

[[v12-12-4]]

^<<v12-12-4,4>>^ Jeoás disse aos sacerdotes: “Peguem em todo o dinheiro que se traz à casa de Jeová para as ofertas sagradas: o imposto que cada um deve pagar, o dinheiro recebido como valor estabelecido para uma pessoa^&#42;1^ e todo o dinheiro que o coração de cada um o motivar a trazer à casa de Jeová.

[NOTE]
====
. Ou: “alma”.
====

[[v12-12-5]]

^<<v12-12-5,5>>^ Os sacerdotes irão recebê-lo pessoalmente dos doadores^&#42;1^ e irão usá-lo para reparar a casa, onde quer que esteja danificada.”^&#42;2^

[NOTE]
====
. Ou: “conhecidos”.
. Ou: “onde quer que haja rachas”.
====

[[v12-12-6]]

^<<v12-12-6,6>>^ Por volta do vigésimo terceiro ano do rei Jeoás, os sacerdotes ainda não tinham reparado a casa.

[[v12-12-7]]

^<<v12-12-7,7>>^ Assim, o rei Jeoás chamou Jeoiada, o sacerdote, e os outros sacerdotes, e disse-lhes: “Porque é que não estão a reparar a casa? Portanto, não recebam mais dinheiro dos doadores, a menos que seja usado para reparar a casa.”

[[v12-12-8]]

^<<v12-12-8,8>>^ Então, os sacerdotes concordaram que não receberiam mais dinheiro do povo e que não seriam responsáveis pela reparação da casa.

[[v12-12-9]]

^<<v12-12-9,9>>^ A seguir, Jeoiada, o sacerdote, pegou num cofre e fez um buraco na tampa, e pô-lo ao lado do altar, à direita de quem entra na casa de Jeová. Os sacerdotes que serviam como porteiros colocavam ali todo o dinheiro que se trazia à casa de Jeová.

[[v12-12-10]]

^<<v12-12-10,10>>^ Sempre que viam que havia muito dinheiro no cofre, o secretário do rei e o sumo sacerdote vinham, recolhiam-no^&#42;1^ e contavam o dinheiro que tinha sido trazido à casa de Jeová.

[NOTE]
====
. Ou: “colocavam em sacos”. Lit.: “amarravam”.
====

[[v12-12-11]]

^<<v12-12-11,11>>^ Eles entregavam o dinheiro que tinha sido contado aos que supervisionavam a obra na casa de Jeová. Esses, por sua vez, pagavam aos carpinteiros e aos construtores que trabalhavam na casa de Jeová,

[[v12-12-12]]

^<<v12-12-12,12>>^ assim como aos pedreiros e aos cortadores de pedras. Além disso, compravam madeira e pedras talhadas para a reparação da casa de Jeová, e também usavam o dinheiro para pagar todas as outras despesas com a reparação da casa.

[[v12-12-13]]

^<<v12-12-13,13>>^ No entanto, com o dinheiro que se trazia à casa de Jeová, não se faziam bacias de prata, nem cortadores de pavio, nem tigelas, nem trombetas, nem nenhum objeto de ouro ou de prata para a casa de Jeová.

[[v12-12-14]]

^<<v12-12-14,14>>^ Eles davam o dinheiro apenas aos que faziam a obra, e com ele reparavam a casa de Jeová.

[[v12-12-15]]

^<<v12-12-15,15>>^ Não pediam contas aos homens a quem entregavam o dinheiro a ser dado aos trabalhadores, pois eles eram de confiança.

[[v12-12-16]]

^<<v12-12-16,16>>^ Contudo, o dinheiro para as ofertas pela culpa e o dinheiro para as ofertas pelo pecado não era usado para a casa de Jeová; ele pertencia aos sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Nessa época, Hazael, rei da Síria, foi lutar contra Gate e tomou-a; depois, Hazael resolveu atacar^&#42;1^ Jerusalém.

[NOTE]
====
. Lit.: “Hazael fixou a sua face para subir contra”.
====

[[v12-12-18]]

^<<v12-12-18,18>>^ Em vista disso, Jeoás, rei de Judá, pegou em todas as ofertas sagradas que tinham sido santificadas por Jeosafá, Jeorão e Acazias, seus antepassados, reis de Judá, assim como as suas próprias ofertas sagradas, e todo o ouro que havia no tesouro da casa de Jeová e no tesouro da casa^&#42;1^ do rei, e enviou-os a Hazael, rei da Síria. Assim, ele retirou-se de Jerusalém.

[NOTE]
====
. Ou: “do palácio”.
====

[[v12-12-19]]

^<<v12-12-19,19>>^ Quanto aos outros acontecimentos da história de Jeoás, tudo o que ele fez, não estão escritos no livro da história da época dos reis de Judá?

[[v12-12-20]]

^<<v12-12-20,20>>^ No entanto, os servos de Jeoás uniram-se numa conspiração contra ele e mataram-no junto à casa do Aterro,^&#42;1^ no caminho que desce para Sila.

[NOTE]
====
. Ou: “junto a Bete-Milo”.
====

[[v12-12-21]]

^<<v12-12-21,21>>^ Os que o mataram foram os seus servos Jozacar, filho de Simeate, e Jeozabade, filho de Somer. Ele foi enterrado com os seus antepassados na Cidade de David; e Amazias, seu filho, tornou-se rei no seu lugar.

'''

xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]