include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-9-1]]

^<<v12-9-1,1>>^ Eliseu, o profeta, chamou então um dos filhos dos profetas e disse-lhe: “Prende a tua veste na cintura, leva este frasco de óleo e vai depressa a Ramote-Gileade.

[[v12-9-2]]

^<<v12-9-2,2>>^ Quando lá chegares, procura Jeú, filho de Jeosafá, filho de Ninsi. Entra, fá-lo levantar-se do meio dos seus irmãos e leva-o à sala mais reservada.

[[v12-9-3]]

^<<v12-9-3,3>>^ A seguir, pega no frasco de óleo, derrama-o sobre a sua cabeça e diz: ‘Assim diz Jeová: “Estou a ungir-te como rei sobre Israel.”’ Depois, abre a porta e foge sem demora.”

[[v12-9-4]]

^<<v12-9-4,4>>^ Assim, o ajudante do profeta foi a Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ Quando chegou, os chefes do exército estavam ali sentados. Ele disse: “Chefe, tenho uma mensagem para si.” Jeú perguntou: “Para qual de nós?” Ele respondeu: “Para si, ó chefe.”

[[v12-9-6]]

^<<v12-9-6,6>>^ Portanto, Jeú levantou-se e entrou na casa; o ajudante derramou o óleo sobre a cabeça dele e disse-lhe: “Assim diz Jeová, o Deus de Israel: ‘Estou a ungir-te como rei sobre o povo de Jeová, sobre Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ Mata os da casa de Acabe, teu senhor, e eu vingarei o sangue dos meus servos, os profetas, e de todos os servos de Jeová que morreram às mãos de Jezabel.

[[v12-9-8]]

^<<v12-9-8,8>>^ Todos os da casa de Acabe morrerão; e eliminarei em Israel todos os do sexo masculino^&#42;1^ da casa de Acabe, incluindo o desamparado e o fraco.

[NOTE]
====
. Lit.:“todo aquele que urina contra o muro”. Expressão hebraica que indica desprezo e se refere a homens.
====

[[v12-9-9]]

^<<v12-9-9,9>>^ Vou fazer à casa de Acabe o mesmo que fiz à casa de Jeroboão, filho de Nebate, e à casa de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ Quanto a Jezabel, os cães irão devorá-la no terreno em Jezreel, e ninguém a enterrará.’” Então, ele abriu a porta e fugiu.

[[v12-9-11]]

^<<v12-9-11,11>>^ Quando Jeú voltou para junto dos servos do seu senhor, eles perguntaram-lhe: “Está tudo bem? Porque é que aquele louco veio falar contigo?” Ele respondeu-lhes: “Vocês conhecem esses homens e o tipo de conversa deles.”

[[v12-9-12]]

^<<v12-9-12,12>>^ Contudo, eles disseram: “Tu não estás a dizer a verdade! Conta-nos, por favor.” E ele respondeu: “Foi assim e assim que ele me disse, e acrescentou: ‘Assim diz Jeová: “Estou a ungir-te como rei sobre Israel.”’”

[[v12-9-13]]

^<<v12-9-13,13>>^ Em vista disso, cada um pegou rapidamente no seu manto e estendeu-o nos degraus diante dele. Tocaram a buzina e disseram: “Jeú tornou-se rei!”

[[v12-9-14]]

^<<v12-9-14,14>>^ A seguir, Jeú, filho de Jeosafá, filho de Ninsi, conspirou contra Jeorão.
Jeorão tinha estado em Ramote-Gileade com todo o Israel para a defender de Hazael, rei da Síria.

[[v12-9-15]]

^<<v12-9-15,15>>^ Mais tarde, o rei Jeorão voltou a Jezreel para se recuperar dos ferimentos que os sírios lhe tinham causado quando lutou contra Hazael, rei da Síria.
Jeú disse: “Se vocês^&#42;1^ concordarem, não deixem ninguém escapar da cidade para ir contar isto em Jezreel.”

[NOTE]
====
. Ou: “as vossas almas”.
====

[[v12-9-16]]

^<<v12-9-16,16>>^ Depois, Jeú subiu para o seu carro de guerra e foi a Jezreel, visto que Jeorão estava lá de cama por causa dos seus ferimentos. E Acazias, rei de Judá, tinha ido visitar Jeorão.

[[v12-9-17]]

^<<v12-9-17,17>>^ Quando o vigia que estava na torre em Jezreel viu o grande número de homens de Jeú a aproximar-se, disse imediatamente: “Estou a ver um grande número de homens.” Jeorão disse: “Chama um cavaleiro e envia-o ao encontro deles para perguntar: ‘Vêm em paz?’”

[[v12-9-18]]

^<<v12-9-18,18>>^ Portanto, um cavaleiro foi ao encontro dele e disse: “Assim diz o rei: ‘Vêm em paz?’” No entanto, Jeú respondeu: “O que é que tu tens a ver com a paz? Vai para trás de mim!”
E o vigia informou: “O mensageiro chegou até eles, mas não voltou.”

[[v12-9-19]]

^<<v12-9-19,19>>^ Portanto, o rei enviou um segundo cavaleiro, que, ao chegar ao pé deles, disse: “Assim diz o rei: ‘Vêm em paz?’” Todavia, Jeú respondeu: “O que é que tu tens a ver com a paz? Vai para trás de mim!”

[[v12-9-20]]

^<<v12-9-20,20>>^ E o vigia informou: “O mensageiro chegou até eles, mas não voltou. Pela maneira de guiar o carro de guerra, deve ser Jeú, neto^&#42;1^ de Ninsi, pois ele guia como um louco.”

[NOTE]
====
. Lit.: “filho”.
====

[[v12-9-21]]

^<<v12-9-21,21>>^ Jeorão disse: “Prepara o meu carro de guerra!” Assim, prepararam o seu carro de guerra, e Jeorão, rei de Israel, e Acazias, rei de Judá, saíram, cada um no seu carro de guerra para se encontrarem com Jeú. Eles encontraram-no no terreno de Nabote, o jezreelita.

[[v12-9-22]]

^<<v12-9-22,22>>^ Assim que Jeorão viu Jeú, ele perguntou: “Vens em paz, Jeú?” Ele, porém, respondeu: “Como pode haver paz enquanto continuam a prostituição e as muitas feitiçarias de Jezabel, tua mãe?”

[[v12-9-23]]

^<<v12-9-23,23>>^ Imediatamente Jeorão deu meia-volta com o seu carro de guerra para fugir e disse a Acazias: “É uma traição, Acazias!”

[[v12-9-24]]

^<<v12-9-24,24>>^ Jeú pegou no arco e atirou uma flecha que atingiu Jeorão no meio das costas, de modo que a flecha lhe atravessou o coração, e ele caiu no seu carro de guerra.

[[v12-9-25]]

^<<v12-9-25,25>>^ A seguir, Jeú disse a Bidcar, seu oficial: “Pega nele e atira-o para o campo de Nabote, o jezreelita. Lembra-te de que eu e tu guiávamos carros de guerra^&#42;1^ atrás de Acabe, o pai dele, quando o próprio Jeová proferiu contra ele a seguinte proclamação:

[NOTE]
====
. Lit.: “guiávamos parelhas”.
====

[[v12-9-26]]

^<<v12-9-26,26>>^ ‘“Tão certo como ontem vi o sangue de Nabote e o sangue dos seus filhos”, diz Jeová, “eu hei de retribuir-te neste mesmo terreno o que tu fizeste”, diz Jeová.’ Portanto, pega nele e atira-o para o terreno, segundo a palavra de Jeová.”

[[v12-9-27]]

^<<v12-9-27,27>>^ Quando Acazias, rei de Judá, viu o que estava a acontecer, fugiu pelo caminho da casa do jardim. (Mais tarde, Jeú perseguiu-o e disse: “Matem-no também!” Assim, feriram-no enquanto estava no carro de guerra a subir para Gur, que fica ao pé de Ibleão. Contudo, ele continuou a fugir para Megido e morreu lá.

[[v12-9-28]]

^<<v12-9-28,28>>^ Então, os seus servos levaram-no num carro de guerra até Jerusalém e enterraram-no com os seus antepassados na sua sepultura, na Cidade de David.

[[v12-9-29]]

^<<v12-9-29,29>>^ Foi no décimo primeiro ano de Jeorão, filho de Acabe, que Acazias se tinha tornado rei sobre Judá.)

[[v12-9-30]]

^<<v12-9-30,30>>^ Quando Jeú chegou a Jezreel, Jezabel soube disso. Então ela pintou os olhos de preto,^&#42;1^ arranjou o cabelo e olhou pela janela.

[NOTE]
====
. Ou: “pôs sombra nos olhos”.
====

[[v12-9-31]]

^<<v12-9-31,31>>^ Assim que Jeú entrou pelo portão, ela disse: “Será que Zinri, que matou o seu próprio senhor, se saiu bem?”

[[v12-9-32]]

^<<v12-9-32,32>>^ Ele levantou os olhos para a janela e disse: “Quem é que está do meu lado? Quem?” Imediatamente, dois ou três oficiais da corte olharam para ele, lá em baixo.

[[v12-9-33]]

^<<v12-9-33,33>>^ Ele disse: “Atirem-na daí abaixo!” Então, eles atiraram-na; o sangue dela salpicou a parede e os cavalos, e ele atropelou-a.

[[v12-9-34]]

^<<v12-9-34,34>>^ Depois disso, ele entrou, comeu e bebeu. A seguir, disse: “Peguem nesta maldita e enterrem-na. Afinal, ela é filha de rei.”

[[v12-9-35]]

^<<v12-9-35,35>>^ Porém, quando a foram enterrar, não encontraram nada, a não ser o crânio, os pés e as mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Quando voltaram e lhe contaram isso, ele disse: “Isto cumpre a palavra de Jeová, que ele falou por meio do seu servo Elias, o tisbita: ‘No terreno de Jezreel os cães comerão a carne de Jezabel.

[[v12-9-37]]

^<<v12-9-37,37>>^ E, no terreno de Jezreel, o cadáver de Jezabel irá tornar-se como estrume sobre os campos, para que não se diga: “Esta é Jezabel.”’”

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]