include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-24-1]]

^<<v12-24-1,1>>^ Nos dias de Jeoiaquim, Nabucodonosor, rei de Babilónia, veio contra ele, e Jeoiaquim tornou-se seu servo durante três anos. Contudo, ele voltou-se contra Nabucodonosor e rebelou-se.

[[v12-24-2]]

^<<v12-24-2,2>>^ Então, Jeová começou a enviar contra Jeoiaquim bandos de saqueadores caldeus, sírios, moabitas e amonitas. Continuou a enviá-los para destruir Judá, segundo a palavra que Jeová tinha falado por meio dos seus servos, os profetas.

[[v12-24-3]]

^<<v12-24-3,3>>^ Foi certamente pela ordem de Jeová que isto aconteceu a Judá, para os remover da sua vista por causa de todos os pecados que Manassés tinha cometido,

[[v12-24-4]]

^<<v12-24-4,4>>^ e também por causa do sangue inocente que tinha derramado, pois tinha enchido Jerusalém de sangue inocente. E Jeová não quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ Quanto aos outros acontecimentos da história de Jeoiaquim, tudo o que ele fez, não estão escritos no livro da história da época dos reis de Judá?

[[v12-24-6]]

^<<v12-24-6,6>>^ Por fim, Jeoiaquim descansou com os seus antepassados; e Joaquim, seu filho, tornou-se rei no seu lugar.

[[v12-24-7]]

^<<v12-24-7,7>>^ O rei do Egito nunca mais se arriscou a sair da sua terra, pois o rei de Babilónia tinha tomado tudo o que pertencia ao rei do Egito, desde a torrente^&#42;1^ do Egito até ao rio Eufrates.

[NOTE]
====
. Ou: “o uádi”. Veja o Glossário.
====

[[v12-24-8]]

^<<v12-24-8,8>>^ Joaquim tinha 18 anos de idade quando se tornou rei, e reinou durante três meses em Jerusalém. O nome da sua mãe era Neusta, filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Ele fazia o que era mau aos olhos de Jeová, conforme tudo o que o seu pai tinha feito.

[[v12-24-10]]

^<<v12-24-10,10>>^ Naquele tempo, os servos de Nabucodonosor, rei de Babilónia, subiram contra Jerusalém, e a cidade foi cercada.

[[v12-24-11]]

^<<v12-24-11,11>>^ Nabucodonosor, rei de Babilónia, veio até à cidade enquanto ela estava cercada pelos seus servos.

[[v12-24-12]]

^<<v12-24-12,12>>^ Joaquim, rei de Judá, entregou-se ao rei de Babilónia, com a sua mãe, os seus servos, os seus príncipes e os seus oficiais da corte; e o rei de Babilónia, no oitavo ano do seu reinado, levou-o cativo.

[[v12-24-13]]

^<<v12-24-13,13>>^ Então, ele tirou todos os tesouros da casa de Jeová e os tesouros da casa^&#42;1^ do rei. Cortou em pedaços todos os utensílios de ouro que Salomão, rei de Israel, tinha feito para o templo de Jeová. Isso aconteceu conforme Jeová tinha predito.

[NOTE]
====
. Ou: “do palácio”.
====

[[v12-24-14]]

^<<v12-24-14,14>>^ Ele levou para o exílio toda a Jerusalém — todos os príncipes, todos os guerreiros valentes, e todos os artesãos e ferreiros;^&#42;1^ levou 10 000 para o exílio. Não ficou ninguém, a não ser os mais pobres do povo da terra.

[NOTE]
====
. Ou, possivelmente: “construtores de fortificações”.
====

[[v12-24-15]]

^<<v12-24-15,15>>^ Assim, ele levou Joaquim para o exílio em Babilónia; e também levou exilados, de Jerusalém para Babilónia, a mãe do rei, as esposas do rei, os seus oficiais da corte e os homens mais importantes do país.

[[v12-24-16]]

^<<v12-24-16,16>>^ O rei de Babilónia também levou para o exílio em Babilónia todos os guerreiros, 7000, além de 1000 artesãos e ferreiros,^&#42;1^ todos eles homens valentes e treinados para a guerra.

[NOTE]
====
. Ou, possivelmente: “construtores de fortificações”.
====

[[v12-24-17]]

^<<v12-24-17,17>>^ E o rei de Babilónia fez a Matanias, tio de Joaquim, rei no seu lugar, e mudou o nome dele para Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Zedequias tinha 21 anos de idade quando se tornou rei, e reinou durante 11 anos em Jerusalém. O nome da sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ Ele fazia o que era mau aos olhos de Jeová, conforme tudo o que Jeoiaquim tinha feito.

[[v12-24-20]]

^<<v12-24-20,20>>^ Foi por causa da ira de Jeová que estas coisas aconteceram em Jerusalém e em Judá, até que ele os expulsou da sua vista. E Zedequias rebelou-se contra o rei de Babilónia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]