include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-4-1]]

^<<v12-4-1,1>>^ A esposa de um dos filhos dos profetas clamou a Eliseu, dizendo: “O seu servo, meu marido, morreu, e o senhor bem sabe que o seu servo sempre temeu a Jeová. Agora veio um credor para levar os meus dois filhos como escravos dele.”

[[v12-4-2]]

^<<v12-4-2,2>>^ Por conseguinte, Eliseu disse-lhe: “O que é que eu posso fazer por ti? Diz-me o que tens em casa.” Ela respondeu: “A sua serva não tem nada em casa a não ser um jarro^&#42;1^ com azeite.”

[NOTE]
====
. Ou: “jarro de bico”.
====

[[v12-4-3]]

^<<v12-4-3,3>>^ Então ele disse: “Vai, pede vasilhas vazias a todos os teus vizinhos. Traz quantas puderes.

[[v12-4-4]]

^<<v12-4-4,4>>^ Depois entra em casa e fecha a porta atrás de ti e dos teus filhos. Enche todas as vasilhas de azeite e separa as que estiverem cheias.”

[[v12-4-5]]

^<<v12-4-5,5>>^ Então, ela foi-se embora.
Depois de ela ter fechado a porta atrás de si e dos seus filhos, eles começaram a passar-lhe as vasilhas, e ela enchia-as de azeite.

[[v12-4-6]]

^<<v12-4-6,6>>^ Quando as vasilhas ficaram cheias, ela disse a um dos seus filhos: “Traz-me outra vasilha.” Contudo, ele disse-lhe: “Não há mais nenhuma vasilha.” Nisto o azeite parou de escorrer.

[[v12-4-7]]

^<<v12-4-7,7>>^ Assim, ela foi e contou isso ao homem do verdadeiro Deus, e ele disse: “Vai, vende o azeite e paga as tuas dívidas, e tu e os teus filhos podem viver do que sobrar.”

[[v12-4-8]]

^<<v12-4-8,8>>^ Certo dia, Eliseu foi a Suném, onde havia uma mulher de destaque, e ela insistiu com ele para que tomasse uma refeição ali. Sempre que passava por ali, ele parava para comer.

[[v12-4-9]]

^<<v12-4-9,9>>^ Por isso, ela disse ao marido: “Sei que o homem que passa por aqui regularmente é um homem santo de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Por favor, vamos fazer um pequeno quarto no terraço e pôr lá para ele uma cama, uma mesa, uma cadeira e um candelabro. Assim ele poderá ficar lá sempre que passar por aqui.”

[[v12-4-11]]

^<<v12-4-11,11>>^ Certo dia, ele chegou ali e foi para o quarto no terraço para se deitar.

[[v12-4-12]]

^<<v12-4-12,12>>^ E ele disse a Geazi, seu ajudante: “Chama a sunamita.” Ele chamou-a, e ela foi ter com ele.

[[v12-4-13]]

^<<v12-4-13,13>>^ Eliseu disse a Geazi: “Por favor, diz-lhe: ‘Tiveste este trabalho todo por nossa causa. O que é que se pode fazer por ti? Devo falar com o rei ou com o chefe do exército a teu favor?’” Contudo, ela respondeu: “Não, eu estou bem, a morar entre o meu próprio povo.”

[[v12-4-14]]

^<<v12-4-14,14>>^ Assim, Eliseu perguntou: “Então, o que é que se pode fazer por ela?” Geazi respondeu: “Bem, ela não tem filhos, e o seu marido é idoso.”

[[v12-4-15]]

^<<v12-4-15,15>>^ Ele disse imediatamente: “Chama-a.” E Geazi chamou-a, e ela ficou parada à entrada do quarto.

[[v12-4-16]]

^<<v12-4-16,16>>^ Então, Eliseu disse: “Por esta altura, no ano que vem, estarás com um filho nos braços.” Mas ela disse: “Não, meu senhor, homem do verdadeiro Deus! Não minta à sua serva.”

[[v12-4-17]]

^<<v12-4-17,17>>^ No entanto, a mulher ficou grávida e deu à luz um filho naquela mesma altura, no ano seguinte, assim como Eliseu lhe tinha dito.

[[v12-4-18]]

^<<v12-4-18,18>>^ O menino cresceu e, um dia, foi ter com o pai, que estava com os ceifeiros.

[[v12-4-19]]

^<<v12-4-19,19>>^ Ele dizia ao pai: “Ai, a minha cabeça, a minha cabeça!” Então, o seu pai disse ao ajudante: “Leva-o à mãe.”

[[v12-4-20]]

^<<v12-4-20,20>>^ Portanto, ele levou-o à mãe, e o menino ficou no colo dela até ao meio-dia, e depois morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ A seguir, ela subiu, deitou-o na cama do homem do verdadeiro Deus e saiu, fechando a porta atrás de si.

[[v12-4-22]]

^<<v12-4-22,22>>^ Ela chamou o marido e disse: “Por favor, envia-me um ajudante e um jumento, e deixa-me ir depressa ao homem do verdadeiro Deus e voltar.”

[[v12-4-23]]

^<<v12-4-23,23>>^ Todavia, ele disse: “Porque é que vais vê-lo hoje? Não é lua nova nem sábado.” No entanto, ela respondeu: “Não te preocupes.”

[[v12-4-24]]

^<<v12-4-24,24>>^ Consequentemente, ela selou o jumento e disse ao seu ajudante: “Vai depressa e não diminuas o passo por minha causa, a menos que eu to diga.”

[[v12-4-25]]

^<<v12-4-25,25>>^ Então, ela foi ter com o homem do verdadeiro Deus ao monte Carmelo. Assim que o homem do verdadeiro Deus a viu de longe, disse a Geazi, seu ajudante: “Olha! É a sunamita.

[[v12-4-26]]

^<<v12-4-26,26>>^ Por favor, corre ao seu encontro e pergunta-lhe: ‘Estás bem? O teu marido está bem? E o teu filho?’” E ela respondeu: “Está tudo bem.”

[[v12-4-27]]

^<<v12-4-27,27>>^ Quando ela chegou ao homem do verdadeiro Deus, no monte, agarrou-se aos seus pés. Geazi aproximou-se para a afastar, mas o homem do verdadeiro Deus disse: “Deixa-a em paz, pois ela está amargurada;^&#42;1^ e Jeová ocultou-me o motivo disso e não me disse nada.”

[NOTE]
====
. Ou: “pois a sua alma está amargurada nela”.
====

[[v12-4-28]]

^<<v12-4-28,28>>^ Então ela disse: “Será que eu pedi um filho ao meu senhor? Não disse eu: ‘Não me dê falsas esperanças’?”

[[v12-4-29]]

^<<v12-4-29,29>>^ Eliseu disse imediatamente a Geazi: “Prende a tua veste na cintura, pega no meu bastão e vai. Se encontrares alguém, não o cumprimentes; e, se alguém te cumprimentar, não respondas. Vai e põe o meu bastão sobre o rosto do menino.”

[[v12-4-30]]

^<<v12-4-30,30>>^ Porém, a mãe do menino disse: “Tão certo como Jeová vive e como o senhor^&#42;1^ vive, não o deixarei.” Por isso, Eliseu levantou-se e foi com ela.

[NOTE]
====
. Ou: “a sua alma”.
====

[[v12-4-31]]

^<<v12-4-31,31>>^ Geazi foi à frente deles e pôs o bastão sobre o rosto do menino, mas não houve nenhum som nem reação. Ele voltou ao encontro de Eliseu e disse-lhe: “O menino não acordou.”

[[v12-4-32]]

^<<v12-4-32,32>>^ Quando Eliseu entrou na casa, o menino estava morto, deitado na sua cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Ele entrou no quarto e fechou a porta atrás de ambos, e começou a orar a Jeová.

[[v12-4-34]]

^<<v12-4-34,34>>^ Depois, subiu para a cama e deitou-se por cima do menino. Ele pôs a sua boca sobre a boca do menino, os seus olhos sobre os olhos dele, as palmas das suas mãos sobre as palmas das mãos dele e ficou estendido por cima dele; e o corpo do menino começou a aquecer.

[[v12-4-35]]

^<<v12-4-35,35>>^ Eliseu andou de um lado para o outro na casa, subiu para a cama e estendeu-se novamente por cima do menino. O menino espirrou sete vezes e depois disso abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Eliseu chamou Geazi e disse: “Chama a sunamita.” Assim, ele chamou-a, e ela foi ter com ele. Eliseu disse: “Pega no teu filho.”

[[v12-4-37]]

^<<v12-4-37,37>>^ Ela entrou, lançou-se aos pés de Eliseu e curvou-se por terra diante dele, depois pegou no filho e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ Quando Eliseu regressou a Gilgal, havia fome no país. Os filhos dos profetas estavam sentados diante dele, e ele disse ao seu ajudante: “Põe a panela grande ao lume e faz um guisado para os filhos dos profetas.”

[[v12-4-39]]

^<<v12-4-39,39>>^ Assim, um deles foi ao campo colher malvas, encontrou uma trepadeira silvestre, colheu bagas dela e encheu a sua roupa. Quando voltou, cortou-as em pedaços para dentro da panela do cozido, sem saber o que eram.

[[v12-4-40]]

^<<v12-4-40,40>>^ Mais tarde, serviram o guisado aos homens. No entanto, assim que o comeram, gritaram: “Há morte na panela, homem do verdadeiro Deus!” E não o puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Assim, ele disse: “Tragam um pouco de farinha.” Depois de a deitar na panela, disse: “Sirvam-no aos homens.” E já não havia nada de mal na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ Um homem veio de Baal-Salisa e trouxe ao homem do verdadeiro Deus 20 pães de cevada feitos com os primeiros frutos maduros, e um saco de cereais novos. Então, Eliseu disse: “Dá isto aos homens para comerem.”

[[v12-4-43]]

^<<v12-4-43,43>>^ No entanto, o seu ajudante perguntou: “Como é que eu vou alimentar cem homens com isto?” Ele respondeu: “Dá-o aos homens para comerem, pois, assim diz Jeová: ‘Eles comerão e ainda sobrará.’”

[[v12-4-44]]

^<<v12-4-44,44>>^ Portanto, colocou a comida à frente deles, e, segundo a palavra de Jeová, comeram, e ainda sobrou.

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]