include::./index.adoc[]

[[v12-10-0]]
=== 2 Reis, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-10-1]]

^<<v12-10-1,1>>^ Acabe tinha 70 filhos em Samaria. Portanto, Jeú escreveu cartas e enviou-as para Samaria — aos príncipes de Jezreel, aos anciãos e aos que cuidavam dos filhos de Acabe.^&#42;1^ A carta dizia:

[NOTE]
====
. Lit.: “aos guardiões de Acabe”.
====

[[v12-10-2]]

^<<v12-10-2,2>>^ “Quando receberem esta carta, os filhos do vosso senhor estarão convosco, assim como os carros de guerra, os cavalos, uma cidade fortificada e as armas.

[[v12-10-3]]

^<<v12-10-3,3>>^ Portanto, escolham o melhor e o mais qualificado^&#42;1^ dos filhos do vosso senhor e ponham-no no trono do seu pai. Então, lutem pela casa do vosso senhor.”

[NOTE]
====
. Ou: “reto”.
====

[[v12-10-4]]

^<<v12-10-4,4>>^ Todavia, eles ficaram com muito medo e disseram: “Se nem mesmo dois reis se conseguiram manter de pé diante dele, como é que nós nos manteremos de pé?”

[[v12-10-5]]

^<<v12-10-5,5>>^ Assim, o encarregado do palácio,^&#42;1^ o governador da cidade, os anciãos e os que cuidavam dos filhos de Acabe mandaram dizer a Jeú: “Somos teus servos e faremos tudo o que nos disseres. Não faremos rei a ninguém. Faz o que for bom aos teus olhos.”

[NOTE]
====
. Lit.: “aquele que estava sobre a casa”.
====

[[v12-10-6]]

^<<v12-10-6,6>>^ Então, Jeú escreveu-lhes uma segunda carta, que dizia: “Se estão do meu lado e se me querem obedecer, venham ter comigo amanhã, a esta hora, em Jezreel, e tragam as cabeças dos filhos do vosso senhor.”
Os 70 filhos do rei estavam com os homens de destaque da cidade que os criavam.

[[v12-10-7]]

^<<v12-10-7,7>>^ Assim que receberam a carta, eles pegaram nos 70 filhos do rei, mataram-nos, puseram as cabeças deles em cestos e enviaram-lhas, em Jezreel.

[[v12-10-8]]

^<<v12-10-8,8>>^ O mensageiro veio e disse-lhe: “Trouxeram as cabeças dos filhos do rei.” E ele disse: “Façam com elas dois montes à entrada do portão da cidade, e deixem-nas ali até amanhã de manhã.”

[[v12-10-9]]

^<<v12-10-9,9>>^ Quando ele saiu de manhã, ficou de pé diante de todo o povo e disse: “Vocês são inocentes.^&#42;1^ Fui eu que conspirei contra o meu senhor e o matei, mas quem é que matou todos estes?

[NOTE]
====
. Ou: “justos”.
====

[[v12-10-10]]

^<<v12-10-10,10>>^ Portanto, saibam que nem uma única palavra de Jeová, que Jeová falou contra a casa de Acabe, ficará sem cumprimento;^&#42;1^ e Jeová tem feito o que falou por meio do seu servo Elias.”

[NOTE]
====
. Lit.: “cairá por terra”.
====

[[v12-10-11]]

^<<v12-10-11,11>>^ Além disso, Jeú matou todos os que restavam da casa de Acabe em Jezreel, assim como todos os seus homens de destaque, os seus amigos e os seus sacerdotes, até não lhe deixar nenhum sobrevivente.

[[v12-10-12]]

^<<v12-10-12,12>>^ Depois, ele partiu em direção a Samaria. A casa onde os pastores amarravam as ovelhas^&#42;1^ ficava no caminho.

[NOTE]
====
. Aparentemente, um lugar onde as ovelhas eram amarradas para serem tosquiadas.
====

[[v12-10-13]]

^<<v12-10-13,13>>^ Jeú encontrou ali os irmãos de Acazias, rei de Judá, e perguntou-lhes: “Quem são vocês?” Eles responderam: “Somos os irmãos de Acazias, e estamos a caminho para perguntar se está tudo bem com os filhos do rei e com os filhos da rainha-mãe.”^&#42;1^

[NOTE]
====
. Ou: “da senhora”.
====

[[v12-10-14]]

^<<v12-10-14,14>>^ Ele disse imediatamente: “Apanhem-nos vivos!” Portanto, apanharam-nos vivos e mataram-nos junto à cisterna da casa onde as ovelhas eram amarradas. Eram 42 homens, e ele não deixou nenhum deles sobreviver.

[[v12-10-15]]

^<<v12-10-15,15>>^ Seguindo adiante, Jeú encontrou Jonadabe, filho de Recabe, que vinha ao seu encontro. Jeú cumprimentou-o^&#42;1^ e disse: “Está o teu coração plenamente de acordo^&#42;2^ comigo, assim como o meu coração está com o teu?”
Jonadabe respondeu: “Está!”
“Então, dá-me a mão.”
Ele deu-lhe a mão e Jeú puxou-o para dentro do seu carro de guerra.

[NOTE]
====
. Ou: “abençoou-o”.
. Ou: “É o teu coração reto”.
====

[[v12-10-16]]

^<<v12-10-16,16>>^ Depois disse: “Vem comigo e vê como não tolero infidelidade^&#42;1^ para com^&#42;2^ Jeová.” Assim, Jeú levou-o no seu carro de guerra.

[NOTE]
====
. Ou: “rivalidade”.
. Ou: “vê o meu zelo por”.
====

[[v12-10-17]]

^<<v12-10-17,17>>^ Por fim, Jeú chegou a Samaria e matou todos os que restavam da casa de Acabe em Samaria; eliminou-os a todos, segundo a palavra que Jeová tinha falado a Elias.

[[v12-10-18]]

^<<v12-10-18,18>>^ Além disso, Jeú reuniu todo o povo e disse-lhes: “Acabe adorou pouco a Baal, mas Jeú irá adorá-lo muito mais.

[[v12-10-19]]

^<<v12-10-19,19>>^ Portanto, convoquem todos os profetas de Baal, todos os seus adoradores e todos os seus sacerdotes. Não deixem nenhum deles faltar, porque vou oferecer um grande sacrifício a Baal. Quem faltar não ficará vivo.” Contudo, Jeú estava a agir com astúcia, para destruir os adoradores de Baal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Jeú acrescentou: “Proclamem^&#42;1^ uma assembleia solene para Baal.” Então, proclamaram-na.

[NOTE]
====
. Lit.: “Santifiquem”.
====

[[v12-10-21]]

^<<v12-10-21,21>>^ Depois, Jeú enviou uma mensagem por todo o Israel, e todos os adoradores de Baal vieram. Nenhum deles faltou. Eles entraram na casa^&#42;1^ de Baal, e a casa de Baal ficou completamente cheia.

[NOTE]
====
. Ou: “no templo”.
====

[[v12-10-22]]

^<<v12-10-22,22>>^ Ele disse ao encarregado do vestiário: “Traz vestes para todos os adoradores de Baal.” Portanto, trouxe-lhes as vestes.

[[v12-10-23]]

^<<v12-10-23,23>>^ De seguida, Jeú e Jonadabe, filho de Recabe, entraram na casa de Baal. Jeú disse aos adoradores de Baal: “Façam uma busca cuidadosa e certifiquem-se de que não haja aqui adoradores de Jeová, mas apenas adoradores de Baal.”

[[v12-10-24]]

^<<v12-10-24,24>>^ Por fim, entraram para oferecer sacrifícios e ofertas queimadas. Jeú tinha colocado do lado de fora 80 dos seus homens e tinha dito: “Quem deixar escapar um dos homens que entrego nas vossas mãos, morrerá no lugar dele.”^&#42;1^

[NOTE]
====
. Ou: “dará a sua alma pela alma dele”.
====

[[v12-10-25]]

^<<v12-10-25,25>>^ Assim que ele acabou de fazer a oferta queimada, Jeú disse aos guardas^&#42;1^ e aos oficiais: “Entrem e matem-nos! Não deixem nenhum deles escapar!” Os guardas e os oficiais mataram-nos com a espada e atiraram os corpos para fora, e foram avançando até ao santuário interno^&#42;2^ da casa de Baal.

[NOTE]
====
. Lit.: “corredores”.
. Lit.: “à cidade”, talvez uma estrutura semelhante a uma fortaleza.
====

[[v12-10-26]]

^<<v12-10-26,26>>^ A seguir, levaram para fora as colunas sagradas da casa de Baal e queimaram-nas.

[[v12-10-27]]

^<<v12-10-27,27>>^ Demoliram a coluna sagrada de Baal; demoliram também a casa de Baal e transformaram-na em latrinas, que existem até ao dia de hoje.

[[v12-10-28]]

^<<v12-10-28,28>>^ Assim, Jeú eliminou Baal de Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ Contudo, Jeú não se desviou dos pecados que Jeroboão, filho de Nebate, tinha levado Israel a cometer, no que se refere à adoração dos bezerros de ouro que ficavam em Betel e em Dã.

[[v12-10-30]]

^<<v12-10-30,30>>^ Assim, Jeová disse a Jeú: “Visto que agiste bem e fizeste o que é certo aos meus olhos, fazendo à casa de Acabe segundo tudo o que estava no meu coração, quatro gerações dos teus filhos irão sentar-se no trono de Israel.”

[[v12-10-31]]

^<<v12-10-31,31>>^ No entanto, Jeú não teve o cuidado de andar na Lei de Jeová, o Deus de Israel, de todo o coração. Ele não se desviou dos pecados que Jeroboão tinha levado Israel a cometer.

[[v12-10-32]]

^<<v12-10-32,32>>^ Naqueles dias, Jeová começou a tirar o território de Israel,^&#42;1^ pedaço por pedaço. Hazael continuou a atacá-los em todo o território de Israel,

[NOTE]
====
. Ou: “a reduzir Israel”.
====

[[v12-10-33]]

^<<v12-10-33,33>>^ do Jordão para o leste, toda a terra de Gileade — o território dos gaditas, dos rubenitas e dos manassitas —, que vai desde Aroer, que fica junto ao vale do Arnom,^&#42;1^ até Gileade e Basã.

[NOTE]
====
. Ou: “uádi Arnom”.
====

[[v12-10-34]]

^<<v12-10-34,34>>^ Quanto aos outros acontecimentos da história de Jeú, tudo o que ele fez e todos os seus atos poderosos, não estão escritos no livro da história da época dos reis de Israel?

[[v12-10-35]]

^<<v12-10-35,35>>^ Por fim, Jeú descansou com os seus antepassados, e enterraram-no em Samaria; e Jeoacaz, seu filho, tornou-se rei no seu lugar.

[[v12-10-36]]

^<<v12-10-36,36>>^ A duração^&#42;1^ do reinado de Jeú sobre Israel, em Samaria, foi de 28 anos.

[NOTE]
====
. Lit.: “Os dias”.
====

'''

xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]