include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha 12 anos de idade quando se tornou rei, e reinou durante 55 anos em Jerusalém. O nome da sua mãe era Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ Ele fez o que era mau aos olhos de Jeová, imitando as práticas detestáveis das nações que Jeová tinha expulsado de diante do povo de Israel.

[[v12-21-3]]

^<<v12-21-3,3>>^ Ele reconstruiu os altos sagrados que Ezequias, seu pai, tinha destruído, construiu altares a Baal e fez um poste sagrado,^&#42;1^ assim como Acabe, rei de Israel, tinha feito. Curvou-se diante de todo o exército dos céus e serviu-os.

[NOTE]
====
. Veja o Glossário.
====

[[v12-21-4]]

^<<v12-21-4,4>>^ Também construiu altares na casa de Jeová, a respeito da qual Jeová tinha dito: “Em Jerusalém porei o meu nome.”

[[v12-21-5]]

^<<v12-21-5,5>>^ Além disso, construiu altares a todo o exército dos céus nos dois pátios da casa de Jeová.

[[v12-21-6]]

^<<v12-21-6,6>>^ Ele queimou o seu próprio filho no fogo,^&#42;1^ praticou magia, procurou presságios^&#42;2^ e designou adivinhos e pessoas que invocavam espíritos. Fez em grande escala o que era mau aos olhos de Jeová, para o ofender.

[NOTE]
====
. Lit.: “Fez o seu filho passar pelo fogo”.
. Ou: “sinais”.
====

[[v12-21-7]]

^<<v12-21-7,7>>^ Ele fez uma imagem esculpida do poste sagrado^&#42;1^ e colocou-a na casa sobre a qual Jeová tinha dito a David e a Salomão, seu filho: “Nesta casa e em Jerusalém, que escolhi dentre todas as tribos de Israel, porei permanentemente o meu nome.

[NOTE]
====
. Veja o Glossário.
====

[[v12-21-8]]

^<<v12-21-8,8>>^ E nunca mais farei os pés de Israel vaguearem para longe da terra que dei aos seus antepassados, desde que obedeçam cuidadosamente a tudo o que lhes ordenei, toda a Lei que o meu servo Moisés mandou que seguissem.”

[[v12-21-9]]

^<<v12-21-9,9>>^ Contudo, eles não obedeceram, e Manassés continuou a desencaminhá-los, levando-os a fazer coisas piores do que as nações que Jeová tinha eliminado de diante dos israelitas.

[[v12-21-10]]

^<<v12-21-10,10>>^ Jeová continuou a falar por meio dos seus servos, os profetas, dizendo:

[[v12-21-11]]

^<<v12-21-11,11>>^ “Manassés, rei de Judá, fez todas estas coisas detestáveis; agiu pior do que todos os amorreus antes dele e, com os seus ídolos repugnantes,^&#42;1^ fez Judá pecar.

[NOTE]
====
. O termo hebraico talvez esteja relacionado com uma palavra para “esterco” e é usado como expressão de desprezo.
====

[[v12-21-12]]

^<<v12-21-12,12>>^ Por isso, assim diz Jeová, o Deus de Israel: ‘Trarei sobre Jerusalém e sobre Judá uma calamidade que fará tinir os ouvidos de quem ouvir falar dela.

[[v12-21-13]]

^<<v12-21-13,13>>^ Estenderei sobre Jerusalém a corda de medir usada contra Samaria e utilizarei o nível^&#42;1^ usado contra a casa de Acabe; e vou limpar Jerusalém como se limpa uma tigela, lavando-a e virando-a de cabeça para baixo.

[NOTE]
====
. Ou: “fio de prumo”.
====

[[v12-21-14]]

^<<v12-21-14,14>>^ Abandonarei o restante da minha herança e irei entregá-los nas mãos dos seus inimigos, e eles serão saqueados, tornando-se despojo para todos os seus inimigos,

[[v12-21-15]]

^<<v12-21-15,15>>^ porque fizeram o que é mau aos meus olhos e continuaram a ofender-me, desde o dia em que os seus antepassados saíram do Egito até ao dia de hoje.’”

[[v12-21-16]]

^<<v12-21-16,16>>^ Manassés também derramou muito sangue inocente, até encher Jerusalém de uma ponta à outra. Além disso, ele cometeu o pecado de levar Judá a pecar e fazer o que era mau aos olhos de Jeová.

[[v12-21-17]]

^<<v12-21-17,17>>^ Quanto aos outros acontecimentos da história de Manassés, tudo o que ele fez e os pecados que cometeu, não estão escritos no livro da história da época dos reis de Judá?

[[v12-21-18]]

^<<v12-21-18,18>>^ Por fim, Manassés descansou com os seus antepassados e foi enterrado no jardim da sua casa, no jardim de Uza; e Amom, seu filho, tornou-se rei no seu lugar.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha 22 anos de idade quando se tornou rei, e reinou durante dois anos em Jerusalém. O nome da sua mãe era Mesulemete, filha de Haruz, de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ Ele fazia o que era mau aos olhos de Jeová, assim como Manassés, seu pai, tinha feito.

[[v12-21-21]]

^<<v12-21-21,21>>^ Ele andava em todos os caminhos em que o seu pai tinha andado, e servia e curvava-se diante dos ídolos repugnantes que o seu pai tinha servido.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim, ele abandonou a Jeová, o Deus dos seus antepassados, e não andou no caminho de Jeová.

[[v12-21-23]]

^<<v12-21-23,23>>^ Por fim, os servos do rei Amom conspiraram contra ele e mataram-no na sua própria casa.

[[v12-21-24]]

^<<v12-21-24,24>>^ No entanto, o povo da terra matou todos os que tinham conspirado contra o rei Amom e fizeram de Josias, seu filho, rei no seu lugar.

[[v12-21-25]]

^<<v12-21-25,25>>^ Quanto aos outros acontecimentos da história de Amom, o que ele fez, não estão escritos no livro da história da época dos reis de Judá?

[[v12-21-26]]

^<<v12-21-26,26>>^ Por fim, enterraram-no na sua sepultura no jardim de Uza; e Josias, seu filho, tornou-se rei no seu lugar.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]