include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-1-1]]

^<<v12-1-1,1>>^ Depois da morte de Acabe, Moabe rebelou-se contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ Foi então que Acazias caiu pela janela^&#42;1^ do seu quarto de terraço em Samaria e ficou ferido. Assim, enviou mensageiros e disse-lhes: “Vão, consultem Baal-Zebube, deus de Ecrom, para saber se me recuperarei deste ferimento.”

[NOTE]
====
. Isto é, pela gelosia, uma grade de ripas de madeira colocada na janela.
====

[[v12-1-3]]

^<<v12-1-3,3>>^ Porém, o anjo de Jeová disse a Elias,^&#42;1^ o tisbita: “Levanta-te, vai encontrar-te com os mensageiros do rei de Samaria e diz-lhes: ‘Porque é que vão consultar Baal-Zebube, deus de Ecrom? Será que não há Deus em Israel?

[NOTE]
====
. Que significa “o meu Deus é Jeová”.
====

[[v12-1-4]]

^<<v12-1-4,4>>^ Por isso, assim diz Jeová: “Não sairás da cama em que estás deitado, pois certamente morrerás.”’” Então Elias foi-se embora.

[[v12-1-5]]

^<<v12-1-5,5>>^ Quando os mensageiros voltaram para Acazias, ele perguntou-lhes imediatamente: “Porque é que voltaram?”

[[v12-1-6]]

^<<v12-1-6,6>>^ Eles responderam-lhe: “Um homem veio ao nosso encontro e disse-nos: ‘Voltem ao rei que vos enviou e digam-lhe: “Assim diz Jeová: ‘Porque é que tu mandaste consultar Baal-Zebube, deus de Ecrom? Será que não há Deus em Israel? Por isso, não sairás da cama em que estás deitado, pois certamente morrerás.’”’”

[[v12-1-7]]

^<<v12-1-7,7>>^ Em vista disso, o rei perguntou-lhes: “Como era o homem que veio ter convosco e vos disse estas palavras?”

[[v12-1-8]]

^<<v12-1-8,8>>^ Eles disseram-lhe: “O homem vestia um manto de pelos e tinha um cinto de couro na cintura.” Ele disse imediatamente: “Era Elias, o tisbita.”

[[v12-1-9]]

^<<v12-1-9,9>>^ A seguir, o rei enviou-lhe um chefe de 50 com os seus 50 soldados. Ele foi ter com Elias, que estava sentado no cume do monte, e disse-lhe: “Homem do verdadeiro Deus, o rei diz: ‘Desce.’”

[[v12-1-10]]

^<<v12-1-10,10>>^ Contudo, Elias respondeu ao chefe dos 50 soldados: “Se eu sou homem de Deus, que desça fogo dos céus e te consuma a ti e aos teus 50 soldados.” E desceu fogo dos céus e consumiu-o a ele e aos seus 50 soldados.

[[v12-1-11]]

^<<v12-1-11,11>>^ Portanto, o rei enviou-lhe outro chefe de 50 com os seus 50 soldados. Ele foi e disse a Elias: “Homem do verdadeiro Deus, assim diz o rei: ‘Desce depressa.’”

[[v12-1-12]]

^<<v12-1-12,12>>^ Contudo, Elias respondeu-lhes: “Se eu sou homem do verdadeiro Deus, que desça fogo dos céus e te consuma a ti e aos teus 50 soldados.” E desceu fogo dos céus, da parte de Deus, e consumiu-o a ele e aos seus 50 soldados.

[[v12-1-13]]

^<<v12-1-13,13>>^ Depois, o rei enviou um terceiro chefe de 50 com os seus 50 soldados. Contudo, o terceiro chefe de 50 soldados subiu ao monte, ajoelhou-se diante de Elias e implorou-lhe favor, dizendo: “Homem do verdadeiro Deus, por favor, que a minha vida e a vida^&#42;1^ destes teus 50 servos sejam preciosas aos teus olhos.

[NOTE]
====
. Ou: “que a minha alma e a alma”.
====

[[v12-1-14]]

^<<v12-1-14,14>>^ Os primeiros dois chefes de 50 com os seus 50 soldados foram consumidos pelo fogo que desceu dos céus, mas agora, que a minha vida^&#42;1^ seja preciosa aos teus olhos.”

[NOTE]
====
. Ou: “alma”.
====

[[v12-1-15]]

^<<v12-1-15,15>>^ Por conseguinte, o anjo de Jeová disse a Elias: “Desce com ele. Não tenhas medo dele.” Assim, Elias levantou-se e desceu com o chefe dos soldados ao encontro do rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ Então, Elias disse ao rei: “Assim diz Jeová: ‘Enviaste mensageiros para consultar Baal-Zebube, deus de Ecrom. Por acaso não há Deus em Israel? Porque é que não consultaste a sua palavra? Por isso, tu não sairás da cama em que estás deitado, pois certamente morrerás.’”

[[v12-1-17]]

^<<v12-1-17,17>>^ E Acazias morreu, segundo a palavra de Jeová, que Elias tinha falado. E, visto que ele não tinha nenhum filho, Jeorão^&#42;1^ tornou-se rei no seu lugar, no segundo ano de Jeorão, filho de Jeosafá, rei de Judá.

[NOTE]
====
. Isto é, o irmão de Acazias.
====

[[v12-1-18]]

^<<v12-1-18,18>>^ Quanto aos outros acontecimentos da história de Acazias, o que ele fez, não estão escritos no livro da história da época dos reis de Israel?

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]