include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-3-1]]

^<<v12-3-1,1>>^ Jeorão, filho de Acabe, tornou-se rei sobre Israel, em Samaria, no décimo oitavo ano de Jeosafá, rei de Judá, e reinou durante 12 anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ Ele fazia o que era mau aos olhos de Jeová, mas não tanto como o seu pai e a sua mãe, pois removeu a coluna sagrada de Baal que o seu pai tinha feito.

[[v12-3-3]]

^<<v12-3-3,3>>^ No entanto, ele continuou nos pecados que Jeroboão, filho de Nebate, tinha levado Israel a cometer, e não se afastou deles.

[[v12-3-4]]

^<<v12-3-4,4>>^ Mesa, rei de Moabe, era criador de ovelhas e pagava como tributo ao rei de Israel 100 000 cordeiros e 100 000 carneiros não tosquiados.

[[v12-3-5]]

^<<v12-3-5,5>>^ Assim que Acabe morreu, o rei de Moabe rebelou-se contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Por isso, o rei Jeorão saiu de Samaria e reuniu todo o Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ Além disso, ele mandou dizer a Jeosafá, rei de Judá: “O rei de Moabe rebelou-se contra mim. Vais comigo guerrear contra Moabe?” Ele respondeu: “Vou. Eu estarei contigo. O meu povo estará com o teu povo. Os meus cavalos estarão com os teus cavalos.”

[[v12-3-8]]

^<<v12-3-8,8>>^ E ele perguntou: “Por que caminho subiremos?” Jeorão respondeu: “Pelo caminho do deserto de Edom.”

[[v12-3-9]]

^<<v12-3-9,9>>^ Assim, o rei de Israel partiu com o rei de Judá e o rei de Edom. Depois de viajarem durante sete dias, deixou de haver água para o exército e para os animais que os seguiam.

[[v12-3-10]]

^<<v12-3-10,10>>^ O rei de Israel disse: “Ai de nós! Jeová convocou três reis apenas para os entregar nas mãos de Moabe!”

[[v12-3-11]]

^<<v12-3-11,11>>^ Portanto, Jeosafá perguntou: “Não há aqui nenhum profeta de Jeová para consultarmos a Jeová por meio dele?” Assim, um dos servos do rei de Israel respondeu: “Há Eliseu, filho de Safate, que derramava água nas mãos de Elias.”^&#42;1^

[NOTE]
====
. Ou: “que era servo de Elias”.
====

[[v12-3-12]]

^<<v12-3-12,12>>^ Jeosafá disse: “A palavra de Jeová está com ele.” Portanto, o rei de Israel, Jeosafá e o rei de Edom foram até onde ele estava.

[[v12-3-13]]

^<<v12-3-13,13>>^ Eliseu disse ao rei de Israel: “O que é que eu tenho a ver consigo?^&#42;1^ Vá consultar os profetas do seu pai e os profetas da sua mãe.” Porém, o rei de Israel disse-lhe: “Não, pois foi Jeová quem nos convocou a nós, três reis, para nos entregar nas mãos de Moabe.”

[NOTE]
====
. Lit.: “O que há para mim e para si?”
====

[[v12-3-14]]

^<<v12-3-14,14>>^ Em vista disso, Eliseu disse: “Tão certo como vive Jeová dos exércitos, a quem sirvo,^&#42;1^ se eu não tivesse consideração por Jeosafá, rei de Judá, não olharia para si nem lhe daria atenção.

[NOTE]
====
. Lit.: “perante quem estou de pé”.
====

[[v12-3-15]]

^<<v12-3-15,15>>^ Agora tragam-me um harpista.”^&#42;1^ Assim que o harpista começou a tocar, a mão de Jeová veio sobre Eliseu.

[NOTE]
====
. Ou: “músico”.
====

[[v12-3-16]]

^<<v12-3-16,16>>^ Ele disse: “Assim diz Jeová: ‘Cavem muitas valas neste vale,^&#42;1^

[NOTE]
====
. Ou: “uádi”.
====

[[v12-3-17]]

^<<v12-3-17,17>>^ pois assim diz Jeová: “Não verão vento nem chuva; contudo, este vale^&#42;1^ irá encher-se de água e irão beber dela, vocês, o vosso gado e os vossos animais de carga.”’

[NOTE]
====
. Ou: “uádi”.
====

[[v12-3-18]]

^<<v12-3-18,18>>^ Mas isto não é nada aos olhos de Jeová, pois ele também entregará Moabe nas vossas mãos.

[[v12-3-19]]

^<<v12-3-19,19>>^ Destruam todas as cidades fortificadas e todas as cidades importantes, cortem todas as árvores boas, tapem todas as fontes de água e estraguem com pedras todos os terrenos bons.”

[[v12-3-20]]

^<<v12-3-20,20>>^ E de manhã, à hora da oferta de cereais da manhã, veio de repente água da direção de Edom, e o vale ficou cheio de água.

[[v12-3-21]]

^<<v12-3-21,21>>^ Todos os moabitas souberam que os reis tinham vindo lutar contra eles, por isso convocaram todos os homens que eram capazes de pegar em armas,^&#42;1^ e posicionaram-se na fronteira.

[NOTE]
====
. Ou: “todos os que usavam um cinto”.
====

[[v12-3-22]]

^<<v12-3-22,22>>^ Quando se levantaram de manhã cedo, o sol refletia-se na água, e, para os moabitas, do outro lado, a água parecia vermelha como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ Eles disseram: “É sangue! Com certeza os reis mataram-se uns aos outros com a espada. Então, ao saque, ó Moabe!”

[[v12-3-24]]

^<<v12-3-24,24>>^ Quando eles entraram no acampamento de Israel, os israelitas atacaram e começaram a golpear os moabitas, que fugiram deles. Os israelitas entraram em Moabe e mataram os moabitas à medida que avançavam.

[[v12-3-25]]

^<<v12-3-25,25>>^ Eles destruíram as cidades, e cada um lançou uma pedra em todos os terrenos bons, enchendo-os de pedras; eles taparam todas as fontes de água e cortaram todas as árvores boas. Por fim, apenas as muralhas de pedras de Quir-Haresete ficaram de pé, e os que atiravam com fundas cercaram-na e atacaram-na.

[[v12-3-26]]

^<<v12-3-26,26>>^ Quando o rei de Moabe viu que a batalha estava perdida, levou consigo 700 homens armados com espadas para abrir caminho até ao rei de Edom, mas eles não conseguiram.

[[v12-3-27]]

^<<v12-3-27,27>>^ Por isso, ele pegou no seu filho primogénito, que ia reinar no seu lugar, e ofereceu-o como sacrifício queimado sobre a muralha. Houve então grande indignação contra Israel, de modo que desistiram de lutar contra o rei de Moabe e voltaram para o seu país.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]