include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-18-1]]

^<<v12-18-1,1>>^ No terceiro ano de Oseias, filho de Elá, rei de Israel, Ezequias, filho de Acaz, rei de Judá, tornou-se rei.

[[v12-18-2]]

^<<v12-18-2,2>>^ Ele tinha 25 anos de idade quando se tornou rei, e reinou durante 29 anos em Jerusalém. O nome da sua mãe era Abi,^&#42;1^ filha de Zacarias.

[NOTE]
====
. Forma abreviada de Abias.
====

[[v12-18-3]]

^<<v12-18-3,3>>^ Ele fazia o que era certo aos olhos de Jeová, assim como David, seu antepassado, tinha feito.

[[v12-18-4]]

^<<v12-18-4,4>>^ Foi ele quem removeu os altos sagrados, despedaçou as colunas sagradas e derrubou o poste sagrado.^&#42;1^ Também esmiuçou a serpente de cobre que Moisés tinha feito, pois até àquela altura o povo de Israel oferecia-lhe fumo sacrificial; e chamavam-lhe ídolo-serpente de cobre.^&#42;2^

[NOTE]
====
. Veja o Glossário.
. Ou: “chamavam-lhe Neustã”.
====

[[v12-18-5]]

^<<v12-18-5,5>>^ Ezequias confiou em Jeová, o Deus de Israel; não houve ninguém igual a ele entre todos os reis de Judá, nem antes nem depois dele.

[[v12-18-6]]

^<<v12-18-6,6>>^ Ele apegava-se a Jeová e não deixou de o seguir. Continuou a guardar os mandamentos que Jeová tinha dado a Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ E Jeová estava com ele. Em tudo o que ele fazia, agia com sabedoria. Rebelou-se contra o rei da Assíria e recusou-se a servi-lo.

[[v12-18-8]]

^<<v12-18-8,8>>^ Ele também derrotou os filisteus até Gaza e os seus territórios, desde a torre de vigia até à cidade fortificada.^&#42;1^

[NOTE]
====
. Isto é, em todos os lugares, tanto nos pouco habitados como nos populosos.
====

[[v12-18-9]]

^<<v12-18-9,9>>^ No quarto ano do rei Ezequias, isto é, no sétimo ano de Oseias, filho de Elá, rei de Israel, Salmaneser, rei da Assíria, veio contra Samaria e começou a cercá-la.

[[v12-18-10]]

^<<v12-18-10,10>>^ Eles tomaram-na ao fim de três anos; Samaria foi tomada no sexto ano de Ezequias, que era o nono ano de Oseias, rei de Israel.

[[v12-18-11]]

^<<v12-18-11,11>>^ Depois, o rei da Assíria levou Israel para o exílio na Assíria, e estabeleceu-os em Hala e em Habor, ao pé do rio Gozã, e nas cidades dos medos.

[[v12-18-12]]

^<<v12-18-12,12>>^ Isto aconteceu porque não tinham escutado a voz de Jeová, seu Deus, mas continuaram a violar o seu pacto, tudo o que Moisés, o servo de Jeová, tinha ordenado. Eles não escutaram nem obedeceram.

[[v12-18-13]]

^<<v12-18-13,13>>^ No décimo quarto ano do rei Ezequias, Senaqueribe, rei da Assíria, veio contra todas as cidades fortificadas de Judá e conquistou-as.

[[v12-18-14]]

^<<v12-18-14,14>>^ Portanto, Ezequias, rei de Judá, mandou dizer ao rei da Assíria em Laquis: “Errei. Retira-te da minha terra e eu irei dar-te o que me exigires.” O rei da Assíria exigiu que Ezequias, rei de Judá, pagasse um tributo de 300 talentos^&#42;1^ de prata e 30 talentos de ouro.

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v12-18-15]]

^<<v12-18-15,15>>^ Assim, Ezequias deu toda a prata que havia na casa de Jeová e no tesouro da casa^&#42;1^ do rei.

[NOTE]
====
. Ou: “do palácio”.
====

[[v12-18-16]]

^<<v12-18-16,16>>^ Naquele tempo, Ezequias, rei de Judá, retirou^&#42;1^ as portas do templo de Jeová e as ombreiras que o próprio rei Ezequias tinha revestido,^&#42;2^ e deu-as ao rei da Assíria.

[NOTE]
====
. Lit.: “decepou”.
. Isto é, revestido de ouro.
====

[[v12-18-17]]

^<<v12-18-17,17>>^ Então, de Laquis, o rei da Assíria enviou o Tartã,^&#42;1^ o Rabe-Saris^&#42;2^ e o Rabsaqué^&#42;3^ com um grande exército ao rei Ezequias, em Jerusalém. Eles subiram até Jerusalém e posicionaram-se junto ao aqueduto do reservatório superior, que fica na estrada do campo do lavadeiro.

[NOTE]
====
. Ou: “o comandante”.
. Ou: “o oficial principal da corte”.
. Ou: “o chefe dos copeiros”.
====

[[v12-18-18]]

^<<v12-18-18,18>>^ Quando chamaram o rei para vir até eles, Eliaquim, filho de Hilquias, que era o encarregado da casa,^&#42;1^ Sebna, o secretário, e o cronista Joá, filho de Asafe, foram ao seu encontro.

[NOTE]
====
. Ou: “do palácio”.
====

[[v12-18-19]]

^<<v12-18-19,19>>^ O Rabsaqué disse-lhes: “Digam a Ezequias: ‘Assim diz o grande rei, o rei da Assíria: “Em que é que se baseia a tua confiança?

[[v12-18-20]]

^<<v12-18-20,20>>^ Tu dizes: ‘Tenho uma estratégia e poder para a guerra’, mas isso não passa de palavras ocas. Em quem é que depositaste a tua confiança para teres a ousadia de te rebelares contra mim?

[[v12-18-21]]

^<<v12-18-21,21>>^ Vê, confias na ajuda daquela cana rachada, o Egito, que penetra e fura a palma da mão de quem se apoia nela. Assim é o Faraó, rei do Egito, para todos os que confiam nele.

[[v12-18-22]]

^<<v12-18-22,22>>^ E caso me digam: ‘Nós confiamos em Jeová, nosso Deus’, não são dele os altos sagrados e os altares que Ezequias removeu, dizendo a Judá e a Jerusalém: ‘É diante deste altar em Jerusalém que se devem curvar’?”’

[[v12-18-23]]

^<<v12-18-23,23>>^ Agora, faz uma aposta com o meu senhor, o rei da Assíria: eu irei dar-te 2000 cavalos se conseguires encontrar cavaleiros suficientes para eles.

[[v12-18-24]]

^<<v12-18-24,24>>^ Então, como é que poderias repelir até mesmo um dos governadores menos destacados do meu senhor, se confias nos carros de guerra e nos cavaleiros do Egito?

[[v12-18-25]]

^<<v12-18-25,25>>^ Agora, será que foi sem a autorização de Jeová que vim contra este lugar para o destruir? O próprio Jeová me disse: ‘Vai e destrói essa terra.’”

[[v12-18-26]]

^<<v12-18-26,26>>^ Em vista disso, Eliaquim, filho de Hilquias, Sebna e Joá disseram ao Rabsaqué: “Por favor, fala com os teus servos em aramaico,^&#42;1^ pois entendemos essa língua. Não fales connosco no idioma dos judeus, pois o povo que está sobre a muralha está a ouvir.”

[NOTE]
====
. Ou: “sírio”.
====

[[v12-18-27]]

^<<v12-18-27,27>>^ No entanto, o Rabsaqué disse: “Será que foi apenas ao teu senhor e a ti que o meu senhor me mandou dizer estas palavras? Não foi também aos homens que estão sentados sobre a muralha, que vão comer o seu próprio excremento e beber a sua própria urina convosco?”

[[v12-18-28]]

^<<v12-18-28,28>>^ Então, o Rabsaqué continuou de pé e disse bem alto no idioma dos judeus: “Ouçam as palavras do grande rei, o rei da Assíria.

[[v12-18-29]]

^<<v12-18-29,29>>^ Assim diz o rei: ‘Não deixem que Ezequias vos engane, porque ele não vos pode livrar das minhas mãos.

[[v12-18-30]]

^<<v12-18-30,30>>^ E que Ezequias não vos faça confiar em Jeová, dizendo: “Jeová certamente nos livrará, e esta cidade não será entregue nas mãos do rei da Assíria.”

[[v12-18-31]]

^<<v12-18-31,31>>^ Não escutem Ezequias, pois assim diz o rei da Assíria: “Façam paz comigo e rendam-se,^&#42;1^ e cada um poderá comer da sua própria videira e da sua própria figueira, e beber água da sua própria cisterna,

[NOTE]
====
. Lit.: “Façam uma bênção comigo e saiam a mim”.
====

[[v12-18-32]]

^<<v12-18-32,32>>^ até que eu venha e vos leve a uma terra igual à vossa, uma terra de cereais e de vinho novo, uma terra de pão e de vinhas, uma terra de oliveiras e de mel. Então continuarão vivos, não morrerão. Não escutem Ezequias, pois ele está a enganar-vos, dizendo: ‘Jeová irá livrar-nos.’

[[v12-18-33]]

^<<v12-18-33,33>>^ Será que algum dos deuses das nações livrou a terra delas das mãos do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim, de Hena e de Iva? Será que eles livraram Samaria das minhas mãos?

[[v12-18-35]]

^<<v12-18-35,35>>^ De todos os deuses destas terras, qual deles foi capaz de livrar a sua terra das minhas mãos? Então, será que Jeová livrará Jerusalém das minhas mãos?”’”

[[v12-18-36]]

^<<v12-18-36,36>>^ Contudo, o povo ficou calado e não lhe disse uma palavra em resposta, pois a ordem do rei era: “Não lhe respondam.”

[[v12-18-37]]

^<<v12-18-37,37>>^ Por conseguinte, Eliaquim, filho de Hilquias, que era o encarregado da casa,^&#42;1^ Sebna, o secretário, e o cronista Joá, filho de Asafe, dirigiram-se a Ezequias com as suas roupas rasgadas e contaram-lhe as palavras do Rabsaqué.

[NOTE]
====
. Ou: “do palácio”.
====

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]