include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-7-1]]

^<<v12-7-1,1>>^ Eliseu disse: “Escutem a palavra de Jeová. Assim diz Jeová: ‘Amanhã, por volta desta hora, no portão^&#42;1^ de Samaria, um seá^&#42;2^ de farinha fina valerá um siclo^&#42;3^ e dois seás de cevada valerão um siclo.’”

[NOTE]
====
. Ou: “nos mercados”.
. Um seá equivalia a 7,33 l. Veja o Ap. B14.
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v12-7-2]]

^<<v12-7-2,2>>^ Então, o oficial em quem o rei confiava disse ao homem do verdadeiro Deus: “Mesmo que Jeová abrisse comportas nos céus, será que isso^&#42;1^ poderia acontecer?” Eliseu respondeu: “Verás isso acontecer com os teus próprios olhos, mas não comerás.”

[NOTE]
====
. Lit.: “essa palavra”.
====

[[v12-7-3]]

^<<v12-7-3,3>>^ Havia quatro leprosos à entrada do portão da cidade, e eles disseram uns aos outros: “Porque é que vamos ficar sentados aqui até morrermos?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se entrarmos na cidade, morreremos lá, pois há fome na cidade. Mas, se ficarmos aqui sentados, também morreremos. Então, vamos até ao acampamento dos sírios. Se eles nos pouparem a vida, viveremos; mas, se nos entregarem à morte, morreremos.”

[[v12-7-5]]

^<<v12-7-5,5>>^ Portanto, saíram ao anoitecer e entraram no acampamento dos sírios. Quando chegaram à beira do acampamento dos sírios, não havia lá ninguém.

[[v12-7-6]]

^<<v12-7-6,6>>^ Pois Jeová tinha feito o acampamento dos sírios ouvir o barulho de carros de guerra e de cavalos, o barulho de um enorme exército. De maneira que os sírios disseram uns aos outros: “Vejam! O rei de Israel contratou os reis dos hititas e os reis do Egito para virem contra nós.”

[[v12-7-7]]

^<<v12-7-7,7>>^ Eles fugiram imediatamente ao anoitecer, abandonando as suas tendas, os seus cavalos, os seus jumentos, e deixando o acampamento como estava. Fugiram para salvar a vida.^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v12-7-8]]

^<<v12-7-8,8>>^ Quando os leprosos chegaram à beira do acampamento, entraram numa tenda e começaram a comer e a beber. Tiraram dali prata, ouro e roupas, e foram escondê-los. Depois, voltaram e entraram noutra tenda, também tiraram coisas dali e foram escondê-las.

[[v12-7-9]]

^<<v12-7-9,9>>^ Por fim, disseram uns aos outros: “O que estamos a fazer não está certo. Hoje é um dia de boas notícias! Se ficarmos calados e esperarmos até ao amanhecer, mereceremos ser punidos. Vamos agora mesmo informar a casa do rei.”

[[v12-7-10]]

^<<v12-7-10,10>>^ Então, foram, chamaram os porteiros da cidade e informaram-nos: “Entrámos no acampamento dos sírios, mas não havia lá ninguém, nem ouvimos nenhuma voz. Havia apenas cavalos e jumentos presos, e as tendas estavam como eles as deixaram.”

[[v12-7-11]]

^<<v12-7-11,11>>^ Imediatamente, os porteiros proclamaram a notícia e ela foi anunciada na casa do rei.

[[v12-7-12]]

^<<v12-7-12,12>>^ O rei levantou-se depressa de noite e disse aos seus servos: “Deixem-me dizer-vos o que os sírios fizeram. Eles sabem que estamos com fome, por isso saíram do acampamento para se esconder no campo, dizendo: ‘Eles sairão da cidade, e nós iremos apanhá-los vivos e entraremos na cidade.’”

[[v12-7-13]]

^<<v12-7-13,13>>^ Então, um dos seus servos disse: “Por favor, deixe alguns homens tomarem cinco dos cavalos que sobraram na cidade. Esses homens vão acabar da mesma maneira que toda a multidão de Israel que permanece aqui. Terão o mesmo fim de toda a multidão de Israel que já morreu. Deixe-nos enviá-los para ver o que aconteceu.”

[[v12-7-14]]

^<<v12-7-14,14>>^ Assim, tomaram dois carros de guerra com cavalos, e o rei enviou-os ao acampamento dos sírios e disse: “Vão e vejam.”

[[v12-7-15]]

^<<v12-7-15,15>>^ E eles foram atrás deles até ao Jordão, e todo o caminho estava cheio de roupas e objetos que os sírios tinham deixado para trás ao fugir em pânico. Os mensageiros voltaram e informaram o rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ A seguir, o povo saiu e saqueou o acampamento dos sírios. Assim, um seá de farinha fina chegou a valer um siclo, e dois seás de cevada chegaram a valer um siclo, segundo a palavra de Jeová.

[[v12-7-17]]

^<<v12-7-17,17>>^ O rei tinha encarregado do portão o oficial em quem confiava, mas o povo espezinhou-o no portão, e ele morreu, assim como o homem do verdadeiro Deus disse ao rei quando tinha ido ao seu encontro.

[[v12-7-18]]

^<<v12-7-18,18>>^ Aconteceu exatamente como o homem do verdadeiro Deus tinha dito ao rei: “Amanhã, a esta hora, dois seás de cevada valerão um siclo, e um seá de farinha fina valerá um siclo, no portão de Samaria.”

[[v12-7-19]]

^<<v12-7-19,19>>^ Porém, o oficial tinha dito ao homem do verdadeiro Deus: “Mesmo que Jeová abrisse comportas nos céus, será que uma coisa dessas^&#42;1^ poderia acontecer?” E Eliseu tinha respondido: “Verás isso acontecer com os teus próprios olhos, mas não comerás.”

[NOTE]
====
. Lit.: “tal palavra como essa”.
====

[[v12-7-20]]

^<<v12-7-20,20>>^ Foi exatamente isso que aconteceu com ele, porque o povo o espezinhou no portão e ele morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]