include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v12-5-1]]

^<<v12-5-1,1>>^ Naamã, chefe do exército do rei da Síria, era um homem de destaque que era respeitado pelo seu senhor, pois por meio dele Jeová tinha dado a vitória^&#42;1^ à Síria. Ele era um guerreiro valente, embora fosse leproso.^&#42;2^

[NOTE]
====
. Ou: “salvação”.
. Ou: “tivesse uma doença de pele”.
====

[[v12-5-2]]

^<<v12-5-2,2>>^ Num dos seus ataques contra a terra de Israel, os sírios tinham levado uma menina cativa, que se tornou serva da esposa de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Ela disse à sua senhora: “Se apenas o meu senhor visitasse o profeta que está em Samaria! Ele iria curá-lo da sua lepra.”

[[v12-5-4]]

^<<v12-5-4,4>>^ Por conseguinte, ele^&#42;1^ foi e contou ao seu senhor o que a menina de Israel tinha dito.

[NOTE]
====
. Possivelmente, refere-se a Naamã.
====

[[v12-5-5]]

^<<v12-5-5,5>>^ Então, o rei da Síria disse a Naamã: “Vai agora mesmo! Vou enviar uma carta ao rei de Israel.” Portanto, ele foi, levando consigo dez talentos^&#42;1^ de prata, 6000 peças de ouro e dez mudas de roupa.

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v12-5-6]]

^<<v12-5-6,6>>^ Ele levou ao rei de Israel a carta, que dizia: “Com esta carta, envio-te o meu servo Naamã, para que o cures da sua lepra.”

[[v12-5-7]]

^<<v12-5-7,7>>^ Assim que o rei de Israel leu a carta, rasgou a sua roupa e disse: “Será que eu sou Deus, para matar e para preservar alguém vivo? Ele manda-me este homem e diz-me para o curar da lepra! Vejam como ele está à procura de um conflito comigo.”

[[v12-5-8]]

^<<v12-5-8,8>>^ Porém, quando Eliseu, o homem do verdadeiro Deus, soube que o rei de Israel tinha rasgado a sua roupa, mandou dizer imediatamente ao rei: “Porque é que o senhor rasgou a roupa? Por favor, deixe o homem vir ter comigo, para que ele saiba que há um profeta em Israel.”

[[v12-5-9]]

^<<v12-5-9,9>>^ Portanto, Naamã foi com os seus cavalos e os seus carros de guerra, e ficou de pé à entrada da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ No entanto, Eliseu enviou um mensageiro para lhe dizer: “Vai, lava-te sete vezes no Jordão, e a tua carne será restaurada, e ficarás puro.”

[[v12-5-11]]

^<<v12-5-11,11>>^ Então, Naamã ficou indignado e resolveu ir-se embora, dizendo: “Eu disse a mim mesmo: ‘Ele sairá, ficará de pé à minha frente e invocará o nome de Jeová, seu Deus, movendo a mão para lá e para cá sobre a lepra para a curar.’

[[v12-5-12]]

^<<v12-5-12,12>>^ Não são o Abana e o Farpar, os rios de Damasco, melhores do que todas as águas de Israel? Não me posso lavar neles e ficar puro?” Assim, virou-se e foi-se embora furioso.

[[v12-5-13]]

^<<v12-5-13,13>>^ Os seus servos aproximaram-se e disseram-lhe: “Meu pai, se o profeta lhe tivesse dito para fazer algo muito difícil, não o faria? Quanto mais, então, se ele apenas lhe disse: ‘Lava-te e fica puro.’”

[[v12-5-14]]

^<<v12-5-14,14>>^ Em vista disso, ele foi e mergulhou^&#42;1^ no Jordão sete vezes, segundo a palavra do homem do verdadeiro Deus. A seguir, a sua carne foi restaurada, tornando-se como a de um menino, e ele ficou puro.

[NOTE]
====
. Ou: “imergiu”.
====

[[v12-5-15]]

^<<v12-5-15,15>>^ Depois disso, ele e toda a sua comitiva^&#42;1^ voltaram ao homem do verdadeiro Deus. Ele ficou diante do profeta e disse: “Agora, sei que não há Deus em nenhuma parte da terra a não ser em Israel. Agora, por favor, aceite um presente^&#42;2^ do seu servo.”

[NOTE]
====
. Lit.: “todo o seu acampamento”.
. Lit.: “uma bênção”.
====

[[v12-5-16]]

^<<v12-5-16,16>>^ No entanto, Eliseu disse: “Tão certo como vive Jeová, a quem sirvo,^&#42;1^ não aceitarei o presente.” Naamã insistiu com ele para que o aceitasse, mas ele recusou.

[NOTE]
====
. Lit.: “perante quem estou de pé”.
====

[[v12-5-17]]

^<<v12-5-17,17>>^ Por fim, Naamã disse: “Já que não aceita, por favor, dê ao seu servo um pouco do solo deste país, a carga de um par de mulas, pois o seu servo não fará mais nenhuma oferta queimada nem sacrifício a outros deuses, a não ser a Jeová.

[[v12-5-18]]

^<<v12-5-18,18>>^ Mas que Jeová perdoe o seu servo apenas pelo seguinte: sempre que o meu senhor, o rei, entra na casa^&#42;1^ de Rimom para ali se curvar, ele apoia-se no meu braço, e eu tenho de me curvar na casa de Rimom. Quando eu me curvar na casa de Rimom, por favor, que Jeová perdoe o seu servo por isso.”

[NOTE]
====
. Ou: “no templo”.
====

[[v12-5-19]]

^<<v12-5-19,19>>^ Então Eliseu disse-lhe: “Vai em paz.” Depois de Naamã se ter ido embora e ter percorrido certa distância,

[[v12-5-20]]

^<<v12-5-20,20>>^ Geazi, o ajudante de Eliseu, o homem do verdadeiro Deus, disse a si mesmo: ‘O meu senhor deixou Naamã, este sírio, ir-se embora e não aceitou o que ele trouxe. Tão certo como Jeová vive, correrei atrás dele para que me dê alguma coisa.’

[[v12-5-21]]

^<<v12-5-21,21>>^ Portanto, Geazi correu atrás de Naamã. Quando Naamã viu alguém a correr atrás dele, desceu do seu carro de guerra para ir ter com ele e perguntou: “Está tudo bem?”

[[v12-5-22]]

^<<v12-5-22,22>>^ Ele respondeu: “Tudo bem. O meu senhor enviou-me para dizer: ‘Agora mesmo vieram ter comigo dois jovens dos filhos dos profetas, da região montanhosa de Efraim. Por favor, dá-lhes um talento de prata e duas mudas de roupa.’”

[[v12-5-23]]

^<<v12-5-23,23>>^ Naamã disse: “Toma dois talentos.” Ele insistiu com ele e colocou dois talentos de prata e duas mudas de roupa em dois sacos, e deu-os a dois ajudantes seus, que os carregaram à frente de Geazi.

[[v12-5-24]]

^<<v12-5-24,24>>^ Quando ele chegou a Ofel,^&#42;1^ tirou-lhes os sacos das mãos e colocou-os em casa, e mandou os homens embora. Depois de eles terem partido,

[NOTE]
====
. Um local em Samaria, possivelmente um monte ou uma fortificação.
====

[[v12-5-25]]

^<<v12-5-25,25>>^ ele entrou e apresentou-se ao seu senhor. Então, Eliseu perguntou-lhe: “De onde vieste, Geazi?” Ele respondeu: “O seu servo não foi a lado nenhum.”

[[v12-5-26]]

^<<v12-5-26,26>>^ Eliseu disse-lhe: “Será que o meu coração não estava lá contigo quando o homem desceu do seu carro de guerra para ir ao teu encontro? Será que agora é o momento de aceitar prata ou roupas, olivais ou vinhas, ovelhas ou bois, servos ou servas?

[[v12-5-27]]

^<<v12-5-27,27>>^ Portanto, a lepra de Naamã irá apegar-se a ti e aos teus descendentes para sempre.” Imediatamente, Geazi saiu leproso da presença dele, branco como a neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]