include::./index.adoc[]

[[v1-47-0]]
=== Génesis, 47
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-47-1]]

^<<v1-47-1,1>>^ Assim, José foi comunicar ao Faraó: “O meu pai, os meus irmãos, os seus rebanhos, as suas manadas e tudo o que têm vieram da terra de Canaã e estão na terra de Gósen.”

[[v1-47-2]]

^<<v1-47-2,2>>^ Ele escolheu cinco dos seus irmãos e apresentou-os ao Faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ O Faraó perguntou aos irmãos dele: “Qual é o vosso trabalho?” Eles responderam ao Faraó: “Os seus servos são pastores de ovelhas, assim como os nossos antepassados.”

[[v1-47-4]]

^<<v1-47-4,4>>^ Disseram também ao Faraó: “Viemos morar como estrangeiros no país porque não há pasto para as ovelhas dos seus servos na terra de Canaã, pois a fome lá é severa. Então, por favor, deixe que os seus servos morem na terra de Gósen.”

[[v1-47-5]]

^<<v1-47-5,5>>^ O Faraó disse então a José: “O teu pai e os teus irmãos vieram aqui para ficar contigo.

[[v1-47-6]]

^<<v1-47-6,6>>^ A terra do Egito está à vossa disposição. Faz com que o teu pai e os teus irmãos morem na melhor parte do país. Que morem na terra de Gósen; e, se conheceres homens capazes entre eles, põe-nos como responsáveis pelos meus rebanhos.”

[[v1-47-7]]

^<<v1-47-7,7>>^ Então, José levou Jacó, seu pai, para dentro e apresentou-o ao Faraó, e Jacó abençoou o Faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ O Faraó perguntou a Jacó: “Qual é a tua idade?”

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó respondeu ao Faraó: “Os anos das minhas peregrinações^&#42;1^ são 130. Têm sido poucos e aflitivos os anos da minha vida; não são tantos como os anos de vida dos meus antepassados, das suas peregrinações.”^&#42;2^

[NOTE]
====
. Ou: “anos da minha morada temporária; anos em que resido como estrangeiro”.
. Ou: “da sua morada temporária; em que residiram como estrangeiros”.
====

[[v1-47-10]]

^<<v1-47-10,10>>^ Depois disso, Jacó abençoou o Faraó e retirou-se da sua presença.

[[v1-47-11]]

^<<v1-47-11,11>>^ Assim, José instalou o seu pai e os seus irmãos na terra do Egito e deu-lhes uma propriedade na melhor parte da terra, na terra de Ramessés, como o Faraó ordenara.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José provia alimentos^&#42;1^ ao seu pai, aos seus irmãos e a todos os da casa do seu pai, de acordo com o número de crianças.

[NOTE]
====
. Lit.: “pão”.
====

[[v1-47-13]]

^<<v1-47-13,13>>^ Não havia alimentos^&#42;1^ em toda a região, porque a fome era muito severa; a terra do Egito e a terra de Canaã ficaram esgotadas devido à fome.

[NOTE]
====
. Lit.: “pão”.
====

[[v1-47-14]]

^<<v1-47-14,14>>^ José recolhia todo o dinheiro que havia na terra do Egito e na terra de Canaã, que as pessoas davam em troca dos cereais que compravam, e José levava o dinheiro à casa do Faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Com o tempo, esgotou-se o dinheiro da terra do Egito e da terra de Canaã, e todos os egípcios começaram a ir ter com José, dizendo: “Dê-nos comida! Será que nos vai deixar morrer só porque o nosso dinheiro acabou?”

[[v1-47-16]]

^<<v1-47-16,16>>^ José disse então: “Se o vosso dinheiro acabou, entreguem os vossos rebanhos, e dar-vos-ei comida em troca dos rebanhos.”

[[v1-47-17]]

^<<v1-47-17,17>>^ Assim, começaram a levar o gado a José, e José dava-lhes alimentos em troca dos cavalos, dos rebanhos, das manadas e dos jumentos, e abasteceu-os de alimentos em troca de todo o seu gado durante aquele ano.

[[v1-47-18]]

^<<v1-47-18,18>>^ Quando aquele ano terminou, começaram a ir ter com ele no ano seguinte e a dizer: “Não esconderemos do meu senhor que o dinheiro e os animais domésticos já foram dados ao meu senhor. Não temos mais nada para oferecer ao meu senhor a não ser o nosso corpo e a nossa terra.

[[v1-47-19]]

^<<v1-47-19,19>>^ Será que nos vai deixar morrer, a nós e à nossa terra? Compre-nos a nós e à nossa terra em troca de comida, e nós, e a nossa terra, iremos tornar-nos escravos do Faraó. Dê-nos sementes para que vivamos e não morramos, e para que a nossa terra não fique desolada.”

[[v1-47-20]]

^<<v1-47-20,20>>^ José comprou então toda a terra dos egípcios para o Faraó, porque todos os egípcios venderam os seus campos, pois a fome era muito severa; e a terra passou a pertencer ao Faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ Então, ele transferiu o povo para as cidades, de uma extremidade do território do Egito até à outra extremidade.

[[v1-47-22]]

^<<v1-47-22,22>>^ Só não comprou a terra dos sacerdotes, porque o alimento dos sacerdotes vinha do Faraó, e eles viviam do alimento que o Faraó lhes dava. Foi por isso que não venderam a sua terra.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então, José disse ao povo: “Vejam, hoje, eu comprei-vos para o Faraó, tanto a vocês como à vossa terra. Aqui têm sementes para semearem a terra.

[[v1-47-24]]

^<<v1-47-24,24>>^ Quando a terra produzir, deem um quinto ao Faraó, mas quatro partes serão vossas, para semear o campo e para vos alimentar, a vocês, às vossas crianças e aos das vossas casas.”

[[v1-47-25]]

^<<v1-47-25,25>>^ Assim, disseram: “O senhor preservou a nossa vida. Que achemos favor aos olhos do meu senhor, e nós iremos tornar-nos escravos do Faraó.”

[[v1-47-26]]

^<<v1-47-26,26>>^ Então, José fez disso um decreto, que é válido até hoje em toda a terra do Egito: um quinto da produção pertence ao Faraó. Só a terra dos sacerdotes é que não se tornou do Faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ Israel continuou a morar na terra do Egito, na terra de Gósen, e eles estabeleceram-se nela, tiveram filhos e tornaram-se muito numerosos.

[[v1-47-28]]

^<<v1-47-28,28>>^ Jacó viveu na terra do Egito durante 17 anos, de modo que os dias da vida de Jacó foram 147 anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ Aproximando-se a altura de Israel morrer, ele chamou o seu filho José e disse: “Se achei favor aos teus olhos, por favor, coloca a mão debaixo da minha coxa, e demonstra amor leal e fidelidade para comigo: por favor, não me enterres no Egito.

[[v1-47-30]]

^<<v1-47-30,30>>^ Quando eu morrer,^&#42;1^ leva-me para fora do Egito e enterra-me na sepultura dos meus antepassados.” Portanto, José disse: “Farei o que me pede.”

[NOTE]
====
. Lit.: “me deitar com os meus pais”.
====

[[v1-47-31]]

^<<v1-47-31,31>>^ Então ele disse: “Jura-me.” Por conseguinte, ele jurou-lhe. Nisto, Israel curvou-se junto à cabeceira da sua cama.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]