include::./index.adoc[]

[[v1-2-0]]
=== Génesis, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim foram terminados os céus, a terra e tudo o que há neles.^&#42;1^

[NOTE]
====
. Lit.: “e todo o seu exército”.
====

[[v1-2-2]]

^<<v1-2-2,2>>^ No sétimo dia, Deus tinha terminado a sua obra,^&#42;1^ e passou a descansar, no sétimo dia, de toda a obra que tinha feito.

[NOTE]
====
. Ou: “a obra que tinha estado a fazer”.
====

[[v1-2-3]]

^<<v1-2-3,3>>^ E Deus abençoou o sétimo dia e declarou-o sagrado, pois neste dia Deus tem descansado de toda a obra que criou, de tudo o que ele decidiu fazer.

[[v1-2-4]]

^<<v1-2-4,4>>^ Esta é a história dos céus e da terra no tempo em que foram criados, no dia em que Jeová^&#42;1^ Deus fez a terra e o céu.

[NOTE]
====
. Primeira ocorrência do nome próprio de Deus, יהוה (YHWH). Veja o Ap. A4.
====

[[v1-2-5]]

^<<v1-2-5,5>>^ Ainda não havia nenhum arbusto do campo na terra e nenhuma vegetação do campo tinha começado a brotar, porque Jeová Deus não tinha feito chover sobre a terra e não havia nenhum homem para cultivar o solo.

[[v1-2-6]]

^<<v1-2-6,6>>^ Mas uma neblina subia da terra e regava toda a superfície do solo.

[[v1-2-7]]

^<<v1-2-7,7>>^ E Jeová Deus formou o homem do pó do solo e soprou-lhe nas narinas o fôlego da vida, e o homem tornou-se um ser^&#42;1^ vivente.

[NOTE]
====
. Ou: “uma alma; uma pessoa”. Em hebraico, néfesh, que significa literalmente “uma criatura que respira”. Veja o Glossário, “Alma”.
====

[[v1-2-8]]

^<<v1-2-8,8>>^ Além disso, Jeová Deus plantou um jardim no Éden, no leste, e ali colocou o homem que tinha formado.

[[v1-2-9]]

^<<v1-2-9,9>>^ Então, Jeová Deus fez brotar do solo todo o tipo de árvores de aspeto agradável e boas para alimento, e também a árvore da vida no meio do jardim e a árvore do conhecimento do que é bom e do que é mau.

[[v1-2-10]]

^<<v1-2-10,10>>^ Havia um rio que nascia no Éden para regar o jardim, e dali se dividia em quatro rios.^&#42;1^

[NOTE]
====
. Lit.: “se tornava quatro cabeças”.
====

[[v1-2-11]]

^<<v1-2-11,11>>^ O nome do primeiro é Píson; é aquele que contorna toda a terra de Havilá, onde há ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ O ouro daquela terra é bom. Lá também há bdélio^&#42;1^ e ónix.

[NOTE]
====
. Isto é, uma resina fragrante parecida com a mirra em aspeto.
====

[[v1-2-13]]

^<<v1-2-13,13>>^ O nome do segundo rio é Giom; é aquele que contorna toda a terra de Cuche.

[[v1-2-14]]

^<<v1-2-14,14>>^ O nome do terceiro rio é Hídequel;^&#42;1^ é aquele que vai para o leste da Assíria. E o quarto rio é o Eufrates.

[NOTE]
====
. Ou: “Tigre”.
====

[[v1-2-15]]

^<<v1-2-15,15>>^ Jeová Deus pegou no homem e estabeleceu-o no jardim do Éden, para que o cultivasse e tomasse conta dele.

[[v1-2-16]]

^<<v1-2-16,16>>^ Jeová Deus também deu esta ordem ao homem: “De todas as árvores do jardim, podes comer à vontade.

[[v1-2-17]]

^<<v1-2-17,17>>^ Mas, quanto à árvore do conhecimento do que é bom e do que é mau, não comas dela, porque, no dia em que comeres dela, certamente morrerás.”

[[v1-2-18]]

^<<v1-2-18,18>>^ Então, Jeová Deus disse: “Não é bom que o homem continue sozinho. Vou fazer-lhe uma ajudadora, como seu complemento.”

[[v1-2-19]]

^<<v1-2-19,19>>^ Jeová Deus tinha formado do solo todos os animais selvagens^&#42;1^ e todas as criaturas voadoras dos céus, e começou a levá-los ao homem para ver como é que este chamaria a cada um; e o que o homem chamava a cada criatura^&#42;2^ viva, esse tornava-se o seu nome.

[NOTE]
====
. Lit.: “toda a criatura viva do campo”.
. Ou: “alma”.
====

[[v1-2-20]]

^<<v1-2-20,20>>^ Assim, o homem deu o nome a todos os animais domésticos, às criaturas voadoras dos céus e a todos os animais selvagens, mas o homem não tinha nenhuma ajudadora como seu complemento.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então, Jeová Deus fez o homem adormecer profundamente e, enquanto ele dormia, tirou-lhe uma das costelas e depois fechou a carne naquele lugar.

[[v1-2-22]]

^<<v1-2-22,22>>^ E, da costela que tirara do homem, Jeová Deus fez a mulher e levou-a ao homem.

[[v1-2-23]]

^<<v1-2-23,23>>^ O homem disse então:
“Esta, por fim, é osso dos meus ossos
E carne da minha carne.
Esta será chamada ‘mulher’,
Porque do homem foi tirada.”

[[v1-2-24]]

^<<v1-2-24,24>>^ É por isso que o homem deixará o seu pai e a sua mãe e irá apegar-se à^&#42;1^ sua esposa, e eles irão tornar-se uma só carne.

[NOTE]
====
. Ou: “e permanecerá com a”.
====

[[v1-2-25]]

^<<v1-2-25,25>>^ E ambos continuavam nus, o homem e a sua esposa, contudo, não estavam envergonhados.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]