include::./index.adoc[]

[[v1-27-0]]
=== Génesis, 27
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-27-1]]

^<<v1-27-1,1>>^ Quando Isaque já era idoso e os seus olhos estavam demasiado fracos para ver, chamou Esaú, o seu filho mais velho, e disse-lhe: “Meu filho!” Ele respondeu: “Estou aqui!”

[[v1-27-2]]

^<<v1-27-2,2>>^ E Isaque disse: “Já estou velho. Não sei o dia da minha morte.

[[v1-27-3]]

^<<v1-27-3,3>>^ Portanto, por favor, pega agora nas tuas armas, na tua aljava e no teu arco, e vai ao campo caçar um animal para mim.

[[v1-27-4]]

^<<v1-27-4,4>>^ Depois, faz um prato saboroso, como eu gosto, e traz-mo. Eu vou comê-lo, a fim de te abençoar^&#42;1^ antes de morrer.”

[NOTE]
====
. Ou: “a fim de que a minha alma te abençoe”.
====

[[v1-27-5]]

^<<v1-27-5,5>>^ Rebeca, no entanto, estava a escutar enquanto Isaque falava com Esaú, seu filho. Quando Esaú saiu para o campo, à procura de caça para trazer,

[[v1-27-6]]

^<<v1-27-6,6>>^ Rebeca disse a Jacó, seu filho: “Acabo de ouvir o teu pai dizer a Esaú, teu irmão:

[[v1-27-7]]

^<<v1-27-7,7>>^ ‘Traz-me alguma caça e faz-me um prato saboroso. Então comerei, e, assim, poderei abençoar-te perante Jeová antes da minha morte.’

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora, meu filho, escuta bem e faz o que te digo.

[[v1-27-9]]

^<<v1-27-9,9>>^ Vai, por favor, ao rebanho e traz-me de lá dois dos melhores cabritos, para que eu prepare com eles um prato saboroso para o teu pai, como ele gosta.

[[v1-27-10]]

^<<v1-27-10,10>>^ Depois, leva-o para o teu pai comer, a fim de que ele te abençoe antes de morrer.”

[[v1-27-11]]

^<<v1-27-11,11>>^ Jacó disse a Rebeca, sua mãe: “Mas Esaú, o meu irmão, é um homem peludo, e a minha pele é lisa.

[[v1-27-12]]

^<<v1-27-12,12>>^ E se o meu pai me tocar? Nesse caso, certamente parecerá que eu estou a fazer pouco dele, e trarei sobre mim uma maldição em vez de uma bênção.”

[[v1-27-13]]

^<<v1-27-13,13>>^ A sua mãe respondeu-lhe: “Venha sobre mim a maldição proferida contra ti, meu filho. Faz apenas o que eu digo e vai, traz-mos.”

[[v1-27-14]]

^<<v1-27-14,14>>^ Portanto, ele foi apanhá-los e levou-os à sua mãe, e a mãe preparou um prato saboroso, como o seu pai gostava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois, Rebeca pegou em roupas de Esaú, o seu filho mais velho, as melhores que tinha em casa, e com elas vestiu Jacó, o seu filho mais novo.

[[v1-27-16]]

^<<v1-27-16,16>>^ Ela também lhe cobriu as mãos e a parte sem pelos do pescoço com as peles dos cabritos.

[[v1-27-17]]

^<<v1-27-17,17>>^ E entregou a Jacó, seu filho, o prato saboroso e o pão que tinha preparado.

[[v1-27-18]]

^<<v1-27-18,18>>^ Então, ele entrou onde estava o seu pai e disse: “Meu pai!” E Isaque disse: “Estou aqui! Quem és tu, meu filho?”

[[v1-27-19]]

^<<v1-27-19,19>>^ Jacó respondeu ao seu pai: “Sou Esaú, o seu primogénito. Fiz exatamente como me disse. Por favor, sente-se e coma da minha caça, para que o senhor^&#42;1^ me abençoe.”

[NOTE]
====
. Ou: “a sua alma”.
====

[[v1-27-20]]

^<<v1-27-20,20>>^ Nisso, Isaque disse ao seu filho: “Como é que a encontraste tão depressa, meu filho?” Ele respondeu: “Foi Jeová, seu Deus, que a trouxe até mim.”

[[v1-27-21]]

^<<v1-27-21,21>>^ Isaque disse então a Jacó: “Aproxima-te, por favor, para que eu te toque, meu filho, para saber se és ou não realmente o meu filho Esaú.”

[[v1-27-22]]

^<<v1-27-22,22>>^ Jacó aproximou-se então de Isaque, seu pai, que lhe tocou e depois disse: “A voz é a voz de Jacó, mas as mãos são as mãos de Esaú.”

[[v1-27-23]]

^<<v1-27-23,23>>^ Ele não o reconheceu porque as mãos dele estavam peludas como as mãos de Esaú, seu irmão. Assim, abençoou-o.

[[v1-27-24]]

^<<v1-27-24,24>>^ Depois, Isaque perguntou: “És realmente o meu filho Esaú?” Ele respondeu: “Sou.”

[[v1-27-25]]

^<<v1-27-25,25>>^ Isaque disse-lhe: “Traz-me um pouco da caça para eu comer, meu filho, e então eu irei abençoar-te.”^&#42;1^ E Jacó serviu-o, e ele comeu; levou-lhe vinho, e ele bebeu.

[NOTE]
====
. Ou: “a minha alma irá abençoar-te”.
====

[[v1-27-26]]

^<<v1-27-26,26>>^ Isaque, seu pai, disse-lhe então: “Aproxima-te, por favor, e beija-me, meu filho.”

[[v1-27-27]]

^<<v1-27-27,27>>^ Ele aproximou-se e beijou-o, e o pai sentiu o cheiro das suas roupas. E abençoou-o, dizendo:
“Ah, o cheiro do meu filho é como o cheiro do campo que Jeová abençoou.

[[v1-27-28]]

^<<v1-27-28,28>>^ Que o verdadeiro Deus te dê o orvalho dos céus, e os solos férteis da terra, e fartura de cereais e de vinho novo.

[[v1-27-29]]

^<<v1-27-29,29>>^ Que povos te sirvam, e nações se curvem diante de ti. Torna-te senhor sobre os teus irmãos, e que os filhos da tua mãe se curvem diante de ti. Maldito seja todo aquele que te amaldiçoar e bendito seja todo aquele que te abençoar.”

[[v1-27-30]]

^<<v1-27-30,30>>^ Assim que Isaque acabou de abençoar Jacó, ainda mal Jacó tinha saído da presença do seu pai Isaque, o seu irmão Esaú voltou da caça.

[[v1-27-31]]

^<<v1-27-31,31>>^ Ele também preparou um prato saboroso e levou-o ao seu pai, e disse ao seu pai: “Levante-se, meu pai, e coma da caça do seu filho, para que o senhor^&#42;1^ me abençoe.”

[NOTE]
====
. Ou: “a sua alma”.
====

[[v1-27-32]]

^<<v1-27-32,32>>^ Diante disso, Isaque, seu pai, disse-lhe: “Quem és tu?” Esaú respondeu: “Sou o seu filho, o seu primogénito, Esaú.”

[[v1-27-33]]

^<<v1-27-33,33>>^ E Isaque começou a tremer violentamente, e disse: “Então quem é que foi à procura de caça e ma trouxe? Eu comi-a antes de tu chegares, e abençoei-o. Ele certamente ficará abençoado!”

[[v1-27-34]]

^<<v1-27-34,34>>^ Ao ouvir as palavras do seu pai, Esaú começou a clamar de maneira extremamente alta e amargurada, e disse ao seu pai: “Abençoe-me, abençoe-me também a mim, meu pai!”

[[v1-27-35]]

^<<v1-27-35,35>>^ Mas ele disse: “O teu irmão veio e enganou-me, para obter a bênção que te estava destinada.”

[[v1-27-36]]

^<<v1-27-36,36>>^ Nisso, Esaú disse: “É com razão que o nome dele é Jacó,^&#42;1^ pois suplantou-me duas vezes! Já me tirou o meu direito de primogenitura, e agora tirou-me a minha bênção!” Acrescentou então: “Não reservou uma bênção para mim?”

[NOTE]
====
. Que significa “aquele que agarra o calcanhar; suplantador”.
====

[[v1-27-37]]

^<<v1-27-37,37>>^ Mas Isaque respondeu a Esaú: “Constituí-o senhor sobre ti, dei-lhe todos os teus irmãos como servos e concedi-lhe cereais e vinho novo para o seu sustento. O que é que ainda posso fazer por ti, meu filho?”

[[v1-27-38]]

^<<v1-27-38,38>>^ Esaú disse ao seu pai: “Só tem uma bênção, meu pai? Abençoe-me, abençoe-me também a mim, meu pai!” Com isso, Esaú levantou a sua voz e irrompeu em lágrimas.

[[v1-27-39]]

^<<v1-27-39,39>>^ Então Isaque, seu pai, respondeu-lhe:
“Vê, a tua morada será longe dos solos férteis da terra e longe do orvalho dos céus acima.

[[v1-27-40]]

^<<v1-27-40,40>>^ E viverás pela espada e servirás o teu irmão. Mas, quando já não aguentares,^&#42;1^ certamente tirarás o seu jugo de cima do teu pescoço.”

[NOTE]
====
. Ou: “quando ficares impaciente”.
====

[[v1-27-41]]

^<<v1-27-41,41>>^ No entanto, Esaú guardou rancor de Jacó, por causa da bênção que o seu pai lhe dera, e Esaú dizia no íntimo: “Os dias de luto pelo meu pai estão a chegar. Depois disso, vou matar o meu irmão Jacó.”

[[v1-27-42]]

^<<v1-27-42,42>>^ Quando Rebeca foi informada das palavras de Esaú, o seu filho mais velho, imediatamente mandou chamar Jacó, o seu filho mais novo, e disse-lhe: “Olha, o teu irmão Esaú está a planear matar-te para se vingar.^&#42;1^

[NOTE]
====
. Ou: “está a consolar-se com a ideia de te matar”.
====

[[v1-27-43]]

^<<v1-27-43,43>>^ Então, meu filho, faz o que te digo: foge depressa para a casa de Labão, meu irmão, em Harã.

[[v1-27-44]]

^<<v1-27-44,44>>^ Mora com ele por um tempo, até que se acalme o furor do teu irmão,

[[v1-27-45]]

^<<v1-27-45,45>>^ até que diminua a raiva que o teu irmão tem de ti e esqueça o que tu lhe fizeste. Então mandarei um aviso para que voltes. Porque é que vos haveria de perder aos dois num só dia?”

[[v1-27-46]]

^<<v1-27-46,46>>^ Depois, Rebeca dizia a Isaque: “Odeio a minha vida por causa das filhas de Hete. Se Jacó tomar uma esposa dentre as filhas de Hete, como as filhas desta terra, de que me adianta viver?”

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]