include::./index.adoc[]

[[v1-37-0]]
=== Génesis, 37
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó continuou a morar na terra de Canaã, onde o seu pai tinha vivido como estrangeiro.

[[v1-37-2]]

^<<v1-37-2,2>>^ Esta é a história de Jacó.
Quando o jovem José tinha 17 anos de idade, estava a cuidar das ovelhas com os filhos de Bila e os filhos de Zilpa, esposas do seu pai. E José trouxe um relato mau sobre eles ao seu pai.

[[v1-37-3]]

^<<v1-37-3,3>>^ Ora, Israel amava José, mais do que amava todos os outros filhos, porque era o filho da sua velhice; e mandou fazer-lhe uma túnica especial.^&#42;1^

[NOTE]
====
. Ou: “uma bela veste longa”.
====

[[v1-37-4]]

^<<v1-37-4,4>>^ Quando os seus irmãos viram que o seu pai o amava mais a ele do que a todos os seus irmãos, começaram a odiá-lo e não conseguiam falar pacificamente com ele.

[[v1-37-5]]

^<<v1-37-5,5>>^ Mais tarde, José teve um sonho e contou-o aos seus irmãos, e isso foi mais um motivo para o odiarem.

[[v1-37-6]]

^<<v1-37-6,6>>^ Disse-lhes: “Por favor, ouçam o sonho que tive.

[[v1-37-7]]

^<<v1-37-7,7>>^ Estávamos a amarrar feixes no meio do campo quando o meu feixe se levantou e ficou de pé, e os vossos feixes rodearam-no e curvaram-se diante do meu feixe.”

[[v1-37-8]]

^<<v1-37-8,8>>^ Os seus irmãos disseram-lhe: “Vais, realmente, fazer-te rei sobre nós e dominar-nos?” Assim, foi mais um motivo para o odiarem, por causa dos sonhos e do que disse.

[[v1-37-9]]

^<<v1-37-9,9>>^ Depois disso, ele teve mais um sonho e relatou-o aos seus irmãos: “Tive outro sonho. Desta vez, o sol, a lua e 11 estrelas curvavam-se diante de mim.”

[[v1-37-10]]

^<<v1-37-10,10>>^ Então, contou-o ao seu pai, assim como aos seus irmãos, e o seu pai repreendeu-o, dizendo: “O que significa esse sonho que tiveste? Será que eu, e também a tua mãe e os teus irmãos, realmente viremos a curvar-nos por terra diante de ti?”

[[v1-37-11]]

^<<v1-37-11,11>>^ E os seus irmãos ficaram com ciúmes dele, mas o seu pai guardou na mente a declaração.

[[v1-37-12]]

^<<v1-37-12,12>>^ Então, os seus irmãos foram levar as ovelhas do seu pai a pastar perto de Siquém.

[[v1-37-13]]

^<<v1-37-13,13>>^ Depois, Israel disse a José: “Não estão os teus irmãos a cuidar dos rebanhos perto de Siquém? Vem, vou enviar-te até eles.” Ele disse-lhe: “Estou pronto!”

[[v1-37-14]]

^<<v1-37-14,14>>^ Disse-lhe então: “Por favor, vai ver se os teus irmãos estão bem; vê como está o rebanho e traz-me notícias.” Com isso, enviou-o do vale^&#42;1^ de Hébron, e ele seguiu para Siquém.

[NOTE]
====
. Ou: “da planície”.
====

[[v1-37-15]]

^<<v1-37-15,15>>^ Mais tarde, um homem encontrou-o a vaguear por um campo. O homem perguntou-lhe: “O que procuras?”

[[v1-37-16]]

^<<v1-37-16,16>>^ Ele respondeu: “Estou à procura dos meus irmãos. Diga-me, por favor: Onde é que eles estão a cuidar dos rebanhos?”

[[v1-37-17]]

^<<v1-37-17,17>>^ O homem respondeu: “Eles partiram daqui, pois ouvi-os dizer: ‘Vamos a Dotã.’” Por conseguinte, José foi atrás dos seus irmãos e encontrou-os em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ Eles viram-no de longe e, antes que se aproximasse, começaram a conspirar contra ele para o matar.

[[v1-37-19]]

^<<v1-37-19,19>>^ Então, disseram uns aos outros: “Vejam! Lá vem aquele sonhador.

[[v1-37-20]]

^<<v1-37-20,20>>^ Agora é o momento! Vamos matá-lo e lançá-lo numa das cisternas, e diremos que um animal selvagem o devorou. Vejamos, então, o que será dos sonhos dele.”

[[v1-37-21]]

^<<v1-37-21,21>>^ Quando Rúben ouviu isso, tentou salvá-lo deles, dizendo: “Não lhe tiremos a vida.”^&#42;1^

[NOTE]
====
. Ou: “Não lhe golpeemos a alma.”
====

[[v1-37-22]]

^<<v1-37-22,22>>^ Rúben disse-lhes: “Não derramem sangue. Lancem-no nesta cisterna, aqui no deserto, mas não lhe façam mal.”^&#42;1^ O seu objetivo era salvá-lo deles, a fim de o devolver ao seu pai.

[NOTE]
====
. Ou: “não lhe ponham as mãos”.
====

[[v1-37-23]]

^<<v1-37-23,23>>^ Então, assim que José chegou, os seus irmãos tiraram-lhe a túnica, a túnica especial que usava,

[[v1-37-24]]

^<<v1-37-24,24>>^ e agarraram-no e lançaram-no na cisterna. Naquela altura, a cisterna estava vazia; não tinha água.

[[v1-37-25]]

^<<v1-37-25,25>>^ Depois, sentaram-se para comer. Quando levantaram os olhos, viram uma caravana de ismaelitas que vinha de Gileade. Os seus camelos carregavam resina de ládano, bálsamo e casca resinosa de árvore, e eles estavam a descer para o Egito.

[[v1-37-26]]

^<<v1-37-26,26>>^ Judá disse então aos seus irmãos: “Que lucro haveria se matássemos o nosso irmão e encobríssemos o seu sangue?

[[v1-37-27]]

^<<v1-37-27,27>>^ Vamos vendê-lo aos ismaelitas, mas não lhe façamos mal. Afinal de contas, ele é nosso irmão, nossa carne.” Assim, eles escutaram o seu irmão.

[[v1-37-28]]

^<<v1-37-28,28>>^ E, quando os mercadores midianitas estavam a passar, os irmãos de José puxaram-no para fora da cisterna e venderam-no aos ismaelitas por 20 peças de prata. Estes homens levaram José para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Mais tarde, quando Rúben voltou à cisterna e viu que José não estava na cisterna, rasgou as suas roupas.

[[v1-37-30]]

^<<v1-37-30,30>>^ Quando voltou aos seus irmãos, exclamou: “O menino desapareceu! E eu — o que é que vou fazer?”

[[v1-37-31]]

^<<v1-37-31,31>>^ Então, pegaram na túnica de José, mataram um bode e mergulharam a túnica no sangue.

[[v1-37-32]]

^<<v1-37-32,32>>^ Depois, mandaram a túnica especial ao seu pai com este recado: “Encontrámos isto. Examina, por favor, e vê se é ou não a túnica do teu filho.”

[[v1-37-33]]

^<<v1-37-33,33>>^ Ele examinou-a e exclamou: “É a túnica do meu filho! Um animal selvagem deve tê-lo devorado! José certamente foi dilacerado!”

[[v1-37-34]]

^<<v1-37-34,34>>^ Então, Jacó rasgou as suas roupas e pôs serapilheira^&#42;1^ à volta da cintura, e guardou o luto durante muitos dias pelo seu filho.

[NOTE]
====
. Veja o Glossário.
====

[[v1-37-35]]

^<<v1-37-35,35>>^ Todos os seus filhos e todas as suas filhas tentavam consolá-lo, mas ele recusava-se a ser consolado e dizia: “Descerei à Sepultura^&#42;1^ a chorar pelo meu filho!” E ele continuava a chorar pelo seu filho.

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v1-37-36]]

^<<v1-37-36,36>>^ Entretanto, no Egito, os midianitas venderam José a Potifar, um oficial da corte do Faraó e chefe da guarda.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]