include::./index.adoc[]

[[v1-21-0]]
=== Génesis, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-21-1]]

^<<v1-21-1,1>>^ Jeová voltou a sua atenção para Sara, assim como dissera, e Jeová fez a Sara o que prometera.

[[v1-21-2]]

^<<v1-21-2,2>>^ Então, Sara ficou grávida e deu um filho a Abraão, na velhice dele, na altura que Deus prometera.

[[v1-21-3]]

^<<v1-21-3,3>>^ Abraão deu o nome de Isaque ao seu filho recém-nascido, que Sara lhe deu.

[[v1-21-4]]

^<<v1-21-4,4>>^ E Abraão circuncidou Isaque, seu filho, aos oito dias de idade, assim como Deus lhe mandara.

[[v1-21-5]]

^<<v1-21-5,5>>^ Abraão tinha 100 anos de idade quando se tornou pai de Isaque, seu filho.

[[v1-21-6]]

^<<v1-21-6,6>>^ Sara disse então: “Deus deu-me motivos para rir; todo aquele que souber disto vai rir-se comigo.”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “rir-se-á de mim”.
====

[[v1-21-7]]

^<<v1-21-7,7>>^ E acrescentou: “Quem é que poderia ter dito a Abraão: ‘Sara certamente amamentará filhos’? No entanto, dei-lhe um filho na sua velhice.”

[[v1-21-8]]

^<<v1-21-8,8>>^ O menino cresceu e foi desmamado, e Abraão preparou um grande banquete no dia em que Isaque foi desmamado.

[[v1-21-9]]

^<<v1-21-9,9>>^ Mas Sara notava que o filho que Agar, a egípcia, tinha dado a Abraão, gozava com Isaque.

[[v1-21-10]]

^<<v1-21-10,10>>^ Por isso, disse a Abraão: “Expulsa essa escrava e o seu filho, pois o filho dessa escrava não vai ser herdeiro com o meu filho, Isaque!”

[[v1-21-11]]

^<<v1-21-11,11>>^ Mas o que ela disse sobre Ismael desagradou muito a Abraão.

[[v1-21-12]]

^<<v1-21-12,12>>^ Então, Deus disse a Abraão: “Não te aflijas com o que Sara te diz sobre o rapaz e sobre a tua escrava. Escuta o que ela diz,^&#42;1^ pois o que será chamado tua descendência^&#42;2^ virá por meio de Isaque.

[NOTE]
====
. Lit.: “a voz dela”.
. Lit.: “tua semente”.
====

[[v1-21-13]]

^<<v1-21-13,13>>^ Quanto ao filho da escrava, também farei dele uma nação, por ser teu descendente.”^&#42;1^

[NOTE]
====
. Lit.: “tua semente”.
====

[[v1-21-14]]

^<<v1-21-14,14>>^ Então, Abraão levantou-se de manhã cedo, pegou num pão e num odre de água e deu-os a Agar. Colocou-os ao ombro dela e mandou-a embora com o rapaz. Assim, ela partiu e ficou a vaguear pelo deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Por fim, a água que estava no odre acabou, e ela empurrou o rapaz para debaixo de um arbusto.

[[v1-21-16]]

^<<v1-21-16,16>>^ Então, seguiu adiante e sentou-se sozinha, à distância de um tiro de arco, pois dizia: “Não quero ver o rapaz morrer.” Assim, sentou-se à distância e começou a gritar e a chorar.

[[v1-21-17]]

^<<v1-21-17,17>>^ Deus ouviu a voz do rapaz, e o anjo de Deus chamou Agar desde os céus e disse-lhe: “O que é que tens, Agar? Não tenhas medo, pois Deus ouviu a voz do rapaz, ali onde está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Levanta-te, ergue o rapaz e segura-o com a mão, pois farei dele uma grande nação.”

[[v1-21-19]]

^<<v1-21-19,19>>^ Deus abriu-lhe então os olhos, e ela viu um poço de água. Ela foi até lá e encheu o odre de água, e deu de beber ao rapaz.

[[v1-21-20]]

^<<v1-21-20,20>>^ E Deus estava com o rapaz enquanto ele crescia. Ele morava no deserto e tornou-se arqueiro.

[[v1-21-21]]

^<<v1-21-21,21>>^ Ele passou a morar no deserto de Parã, e a sua mãe tomou para ele uma esposa da terra do Egito.

[[v1-21-22]]

^<<v1-21-22,22>>^ Naquele tempo, Abimeleque, juntamente com Ficol, chefe do seu exército, disse a Abraão: “Deus está contigo em tudo o que fazes.

[[v1-21-23]]

^<<v1-21-23,23>>^ Portanto, jura-me agora aqui, por Deus, que não serás falso comigo nem com os meus filhos e os meus descendentes, e que me tratarás a mim e à terra em que tens morado com o mesmo amor leal que te tenho mostrado.”

[[v1-21-24]]

^<<v1-21-24,24>>^ Portanto, Abraão disse: “Eu juro.”

[[v1-21-25]]

^<<v1-21-25,25>>^ No entanto, Abraão queixou-se a Abimeleque por causa do poço de água que os servos de Abimeleque tinham tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Abimeleque respondeu: “Não sei quem fez isto. Não me contaste nada sobre o assunto, e eu nunca ouvi falar disso até hoje.”

[[v1-21-27]]

^<<v1-21-27,27>>^ Então, Abraão pegou em ovelhas e gado e deu-os a Abimeleque, e os dois fizeram um pacto.

[[v1-21-28]]

^<<v1-21-28,28>>^ Quando Abraão pôs de parte sete cordeiras do rebanho,

[[v1-21-29]]

^<<v1-21-29,29>>^ Abimeleque perguntou a Abraão: “Porque puseste à parte estas sete cordeiras?”

[[v1-21-30]]

^<<v1-21-30,30>>^ Ele respondeu então: “Aceitarás da minha mão as sete cordeiras como testemunho de que cavei este poço.”

[[v1-21-31]]

^<<v1-21-31,31>>^ Foi por isso que ele chamou àquele lugar Berseba,^&#42;1^ porque ali ambos fizeram um juramento.

[NOTE]
====
. Que, possivelmente, significa “poço do juramento” ou “poço de sete”.
====

[[v1-21-32]]

^<<v1-21-32,32>>^ Assim fizeram um pacto em Berseba, e depois Abimeleque e Ficol, chefe do seu exército, voltaram para a terra dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ Depois disso, Abraão plantou uma tamargueira em Berseba e invocou ali o nome de Jeová, o Deus eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E Abraão ficou^&#42;1^ na terra dos filisteus por muito tempo.^&#42;2^

[NOTE]
====
. Ou: “morou como estrangeiro”.
. Lit.: “muitos dias”.
====

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]