include::./index.adoc[]

[[v1-35-0]]
=== Génesis, 35
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-35-1]]

^<<v1-35-1,1>>^ Depois, Deus disse a Jacó: “Vai, sobe a Betel e mora ali, e faz ali um altar ao verdadeiro Deus, que te apareceu quando fugias de Esaú, teu irmão.”

[[v1-35-2]]

^<<v1-35-2,2>>^ Então, Jacó disse aos da sua casa e a todos os que estavam com ele: “Livrem-se dos deuses estrangeiros que há no vosso meio, purifiquem-se e troquem de roupa,

[[v1-35-3]]

^<<v1-35-3,3>>^ e vamos, subamos a Betel. Farei ali um altar ao verdadeiro Deus, que me respondeu no dia da minha aflição e que tem estado comigo em todos os lugares^&#42;1^ por onde tenho andado.”

[NOTE]
====
. Ou: “no caminho”.
====

[[v1-35-4]]

^<<v1-35-4,4>>^ Assim, deram a Jacó todos os deuses estrangeiros que tinham e os brincos que usavam nas orelhas, e Jacó enterrou-os^&#42;1^ debaixo da árvore grande que havia perto de Siquém.

[NOTE]
====
. Ou: “escondeu-os”.
====

[[v1-35-5]]

^<<v1-35-5,5>>^ Quando seguiram viagem, o terror de Deus atingiu as cidades ao seu redor, de modo que não perseguiram os filhos de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Por fim, Jacó chegou a Luz, isto é, Betel, na terra de Canaã, ele e todo o povo que estava com ele.

[[v1-35-7]]

^<<v1-35-7,7>>^ Lá, construiu um altar e chamou ao lugar El-Betel,^&#42;1^ porque era lá que o verdadeiro Deus se tinha revelado a ele quando fugia do seu irmão.

[NOTE]
====
. Que significa “Deus de Betel”.
====

[[v1-35-8]]

^<<v1-35-8,8>>^ Mais tarde, Débora, ama de Rebeca, morreu e foi enterrada no sopé de Betel, debaixo de um carvalho. Por isso, ele deu à árvore o nome de Alom-Bacute.^&#42;1^

[NOTE]
====
. Que significa “carvalho de choro”.
====

[[v1-35-9]]

^<<v1-35-9,9>>^ Deus apareceu mais uma vez a Jacó, enquanto ele voltava de Padã-Arã e abençoou-o.

[[v1-35-10]]

^<<v1-35-10,10>>^ Deus disse-lhe: “O teu nome é Jacó. Mas já não te chamarás Jacó; Israel será o teu nome.” E começou a chamar-lhe Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ Deus acrescentou: “Eu sou o Deus Todo-Poderoso. Tem filhos e torna-te muitos. De ti virão nações e uma congregação de nações, e reis descenderão de ti.^&#42;1^

[NOTE]
====
. Lit.: “sairão dos teus lombos”.
====

[[v1-35-12]]

^<<v1-35-12,12>>^ Quanto à terra que dei a Abraão e a Isaque, vou dar-ta a ti; e à tua descendência^&#42;1^ darei esta terra.”

[NOTE]
====
. Lit.: “semente”.
====

[[v1-35-13]]

^<<v1-35-13,13>>^ Então Deus deixou-o, subindo do lugar onde lhe tinha falado.

[[v1-35-14]]

^<<v1-35-14,14>>^ Assim, Jacó ergueu uma coluna no lugar onde tinha falado com ele, uma coluna de pedra, e derramou uma oferta de bebida sobre ela e derramou óleo sobre ela.

[[v1-35-15]]

^<<v1-35-15,15>>^ E Jacó continuou a chamar Betel ao lugar onde Deus falara com ele.

[[v1-35-16]]

^<<v1-35-16,16>>^ Então, partiram de Betel. Ainda estavam a uma certa distância de Efrate, quando Raquel começou a dar à luz; e o parto foi muito difícil.

[[v1-35-17]]

^<<v1-35-17,17>>^ Porém, enquanto ela lutava para ter a criança, a parteira disse-lhe: “Não tenhas medo, pois também terás este filho.”

[[v1-35-18]]

^<<v1-35-18,18>>^ Nos últimos momentos da sua vida^&#42;1^ (pois estava a morrer), ela deu-lhe o nome de Ben-Oni,^&#42;2^ mas o pai chamou-lhe Benjamim.^&#42;3^

[NOTE]
====
. Ou: “Enquanto a sua alma partia”.
. Que significa “filho do meu luto”.
. Que significa “filho da mão direita”.
====

[[v1-35-19]]

^<<v1-35-19,19>>^ Assim, Raquel morreu e foi enterrada a caminho de Efrate, isto é, Belém.

[[v1-35-20]]

^<<v1-35-20,20>>^ Jacó ergueu uma coluna sobre a sua sepultura; esta é a coluna da sepultura de Raquel até ao dia de hoje.

[[v1-35-21]]

^<<v1-35-21,21>>^ Após isso, Israel partiu e armou a sua tenda depois da torre de Éder.

[[v1-35-22]]

^<<v1-35-22,22>>^ Certa vez, enquanto Israel morava naquela terra, Rúben deitou-se com Bila, concubina do pai, e Israel soube disso.
Os filhos de Jacó eram 12.

[[v1-35-23]]

^<<v1-35-23,23>>^ Os filhos de Lia foram Rúben, o primogénito de Jacó, depois Simeão, Levi, Judá, Issacar e Zebulão.

[[v1-35-24]]

^<<v1-35-24,24>>^ Os filhos de Raquel foram José e Benjamim.

[[v1-35-25]]

^<<v1-35-25,25>>^ Os filhos de Bila, serva de Raquel, foram Dã e Naftali.

[[v1-35-26]]

^<<v1-35-26,26>>^ E os filhos de Zilpa, serva de Lia, foram Gade e Aser. Estes são os filhos de Jacó, que nasceram em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Por fim, Jacó chegou onde estava Isaque, seu pai, em Manre, em Quiriate-Arba, isto é, Hébron, onde Abraão e também Isaque tinham morado como estrangeiros.

[[v1-35-28]]

^<<v1-35-28,28>>^ Isaque viveu 180 anos.

[[v1-35-29]]

^<<v1-35-29,29>>^ Então, Isaque deu o seu último suspiro e morreu, e foi reunido ao seu povo,^&#42;1^ depois de uma vida longa e satisfatória;^&#42;2^ e os seus filhos, Esaú e Jacó, enterraram-no.

[NOTE]
====
. Expressão poética que se refere à morte.
. Lit.: “idoso e cheio de dias”.
====

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]