include::./index.adoc[]

[[v1-19-0]]
=== Génesis, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-19-1]]

^<<v1-19-1,1>>^ Os dois anjos chegaram a Sodoma ao anoitecer, e Ló estava sentado no portão de Sodoma. Quando os viu, Ló levantou-se, foi até eles, e curvou-se com o rosto por terra.

[[v1-19-2]]

^<<v1-19-2,2>>^ E disse: “Por favor, meus senhores, venham, por favor, para a casa do vosso servo e passem ali a noite, e sejam lavados os vossos pés. Depois, poderão levantar-se cedo e seguir o vosso caminho.” Eles responderam: “Não, passaremos a noite na praça.”

[[v1-19-3]]

^<<v1-19-3,3>>^ Mas ele insistiu tanto que foram com ele para a sua casa. Preparou-lhes então um banquete e cozeu pães sem fermento, e eles comeram.

[[v1-19-4]]

^<<v1-19-4,4>>^ Antes de se poderem deitar para dormir, os homens da cidade — os homens de Sodoma, desde os rapazes até aos mais velhos, todos eles — cercaram a casa numa turba.

[[v1-19-5]]

^<<v1-19-5,5>>^ Chamavam Ló e diziam-lhe: “Onde é que estão os homens que vieram ter contigo esta noite? Trá-los cá para fora, a nós, para que tenhamos relações sexuais com eles.”

[[v1-19-6]]

^<<v1-19-6,6>>^ Então, Ló saiu para falar com eles à entrada da casa e fechou a porta atrás de si.

[[v1-19-7]]

^<<v1-19-7,7>>^ Ele disse: “Por favor, meus irmãos, não ajam com perversidade.

[[v1-19-8]]

^<<v1-19-8,8>>^ Por favor, tenho duas filhas que nunca tiveram relações sexuais com um homem. Por favor, deixem-me trazê-las cá para fora, a vocês, para fazerem com elas o que bem entenderem. Mas não façam nada a estes homens, pois vieram abrigar-se debaixo^&#42;1^ do meu teto.”

[NOTE]
====
. Ou: “sob a proteção”. Lit.: “sob a sombra”.
====

[[v1-19-9]]

^<<v1-19-9,9>>^ Com isto, disseram: “Sai da frente!” E acrescentaram: “Este indivíduo é estrangeiro e veio morar aqui, e ainda assim atreve-se a julgar-nos! Agora vamos fazer-te pior do que a eles.” Juntaram-se todos e cercaram^&#42;1^ Ló e avançaram para arrombar a porta.

[NOTE]
====
. Ou: “empurraram com violência”.
====

[[v1-19-10]]

^<<v1-19-10,10>>^ Então, os homens estenderam a mão, puxaram Ló para dentro de casa e fecharam a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ E feriram de cegueira os homens que estavam à entrada da casa, desde o menor até ao maior, de modo que eles ficaram exaustos ao tentar encontrar a porta.

[[v1-19-12]]

^<<v1-19-12,12>>^ Então, os homens disseram a Ló: “Tens mais alguém aqui? Genros, filhos, filhas e todos os que são teus na cidade, leva-os para fora deste lugar!

[[v1-19-13]]

^<<v1-19-13,13>>^ Pois vamos destruir este lugar, porque o clamor contra este povo tornou-se imenso^&#42;1^ perante Jeová; por isso, Jeová enviou-nos para destruir a cidade.”

[NOTE]
====
. Ou: “alto”.
====

[[v1-19-14]]

^<<v1-19-14,14>>^ Assim, Ló saiu e começou a falar com os seus genros, que se iam casar com as suas filhas; dizia-lhes: “Despachem-se! Saiam deste lugar, porque Jeová vai destruir a cidade!” Mas, para os seus genros, parecia que ele estava a brincar.

[[v1-19-15]]

^<<v1-19-15,15>>^ Ao amanhecer, os anjos começaram a insistir com Ló, dizendo: “Despacha-te! Pega na tua esposa e nas tuas duas filhas que estão aqui contigo, para que não sejas eliminado quando vier a punição pelos erros da cidade.”

[[v1-19-16]]

^<<v1-19-16,16>>^ Visto que se demorava, os homens agarraram-no pela mão, a ele, à sua esposa e às suas duas filhas; e tiraram-no dali e deixaram-no fora da cidade, porque Jeová teve compaixão dele.

[[v1-19-17]]

^<<v1-19-17,17>>^ Assim que os tinham levado para os arredores da cidade, um deles^&#42;1^ disse: “Foge, pela tua vida!^&#42;2^ Não olhes para trás e não pares em nenhuma parte do distrito!^&#42;3^ Foge para a região montanhosa, para que não sejas eliminado!”

[NOTE]
====
. Lit.: “ele”.
. Ou: “alma”.
. Pelos vistos, refere-se ao distrito do Jordão.
====

[[v1-19-18]]

^<<v1-19-18,18>>^ Ló disse-lhes então: “Ali não, por favor, Jeová!

[[v1-19-19]]

^<<v1-19-19,19>>^ Por favor, o teu servo achou favor aos teus olhos, e estás a mostrar-me grande bondade,^&#42;1^ preservando-me vivo,^&#42;2^ mas não posso fugir para a região montanhosa, pois tenho medo de que a calamidade me alcance e eu morra.

[NOTE]
====
. Ou: “amor leal”.
. Ou: “preservando viva a minha alma”.
====

[[v1-19-20]]

^<<v1-19-20,20>>^ Por favor, esta cidade fica perto, e posso fugir para lá; é apenas um lugar pequeno. Por favor, posso fugir para lá? É apenas um lugar pequeno. Assim, sobreviverei.”^&#42;1^

[NOTE]
====
. Ou: “a minha alma continuará a viver”.
====

[[v1-19-21]]

^<<v1-19-21,21>>^ Ele disse-lhe então: “Está bem, também te mostrarei consideração por não destruir a cidade de que falas.

[[v1-19-22]]

^<<v1-19-22,22>>^ Depressa! Foge para lá, porque não posso fazer nada até lá chegares!” Foi por isso que deu à cidade o nome de Zoar.^&#42;1^

[NOTE]
====
. Que significa “pequenez”.
====

[[v1-19-23]]

^<<v1-19-23,23>>^ O sol já tinha nascido sobre aquela terra quando Ló chegou a Zoar.

[[v1-19-24]]

^<<v1-19-24,24>>^ Então, Jeová fez chover fogo e enxofre sobre Sodoma e Gomorra — isto procedeu de Jeová, dos céus.

[[v1-19-25]]

^<<v1-19-25,25>>^ Assim, destruiu aquelas cidades, sim, todo o distrito, com todos os habitantes das cidades e a vegetação do solo.

[[v1-19-26]]

^<<v1-19-26,26>>^ Mas a esposa de Ló, que estava atrás dele, começou a olhar para trás, e transformou-se numa coluna de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ E Abraão levantou-se de manhã cedo e foi para o lugar onde tinha estado perante Jeová.

[[v1-19-28]]

^<<v1-19-28,28>>^ Quando olhou para baixo, para Sodoma e Gomorra, e para toda a terra do distrito, viu algo impressionante. Subia da terra um fumo denso, como o fumo denso de uma fornalha!

[[v1-19-29]]

^<<v1-19-29,29>>^ Assim, quando Deus destruiu as cidades do distrito, Deus lembrou-se de Abraão e tirou Ló das cidades que destruiu, as cidades onde Ló morara.

[[v1-19-30]]

^<<v1-19-30,30>>^ Mais tarde, Ló subiu de Zoar com as duas filhas e passou a morar na região montanhosa, porque ficou com medo de morar em Zoar. Assim, foi morar numa caverna com as duas filhas.

[[v1-19-31]]

^<<v1-19-31,31>>^ E a primogénita disse à mais nova: “O nosso pai já é idoso, e não há homens nesta terra para terem relações connosco segundo o costume de toda a terra.

[[v1-19-32]]

^<<v1-19-32,32>>^ Vem, vamos dar vinho ao nosso pai e vamos deitar-nos com ele, e assim preservaremos a linhagem do nosso pai.”

[[v1-19-33]]

^<<v1-19-33,33>>^ Então, naquela noite, embriagaram o pai com vinho; depois, a primogénita entrou e deitou-se com o pai, mas ele não se apercebeu de nada, nem quando ela se deitou nem quando se levantou.

[[v1-19-34]]

^<<v1-19-34,34>>^ No dia seguinte, a primogénita disse à mais nova: “Deitei-me com o pai ontem à noite. Vamos dar-lhe vinho também hoje à noite. Depois entra e deita-te com ele, e assim preservaremos a linhagem do nosso pai.”

[[v1-19-35]]

^<<v1-19-35,35>>^ Naquela noite, embriagaram novamente o pai com vinho; então a mais nova deitou-se com ele, mas ele não se apercebeu de nada, nem quando ela se deitou nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ E ambas as filhas de Ló ficaram grávidas do seu pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ A primogénita teve um filho e deu-lhe o nome de Moabe. Ele é o pai dos atuais moabitas.

[[v1-19-38]]

^<<v1-19-38,38>>^ A mais nova também teve um filho, e ela deu-lhe o nome de Ben-Ami. Ele é o pai dos atuais amonitas.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]