include::./index.adoc[]

[[v1-50-0]]
=== Génesis, 50
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-50-1]]

^<<v1-50-1,1>>^ Então, José lançou-se sobre o seu pai, chorou abraçado a ele e beijou-o.

[[v1-50-2]]

^<<v1-50-2,2>>^ Depois disso, José ordenou aos seus servos, os médicos, que embalsamassem o seu pai. Por conseguinte, os médicos embalsamaram Israel,

[[v1-50-3]]

^<<v1-50-3,3>>^ e levaram 40 dias inteiros a fazê-lo, pois este é o período necessário para o embalsamamento. E os egípcios continuaram a chorar por ele durante 70 dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Quando se passaram os dias de luto por ele, José disse à corte^&#42;1^ do Faraó: “Se achei favor aos vossos olhos, levem esta mensagem ao Faraó:

[NOTE]
====
. Ou: “aos da casa”.
====

[[v1-50-5]]

^<<v1-50-5,5>>^ ‘O meu pai fez-me jurar, quando ele disse: “Vê, vou morrer. Deves enterrar-me na minha sepultura, que escavei na terra de Canaã.” Por favor, deixe-me subir para enterrar o meu pai, e depois voltarei.’”

[[v1-50-6]]

^<<v1-50-6,6>>^ O Faraó respondeu: “Vai e enterra o teu pai, assim como te fez jurar.”

[[v1-50-7]]

^<<v1-50-7,7>>^ Assim, José subiu para enterrar o seu pai, e todos os servos do Faraó foram com ele, os anciãos da corte e todos os anciãos da terra do Egito,

[[v1-50-8]]

^<<v1-50-8,8>>^ e também todos os da casa de José, os seus irmãos e os da casa do seu pai. Deixaram somente as crianças, os rebanhos e as manadas na terra de Gósen.

[[v1-50-9]]

^<<v1-50-9,9>>^ Carros e cavaleiros foram com ele; o grupo era muito numeroso.

[[v1-50-10]]

^<<v1-50-10,10>>^ Chegaram então à eira de Atade, que fica na região do Jordão, e ali realizaram uma grande e amarga lamentação, e ele guardou luto pelo seu pai durante sete dias.

[[v1-50-11]]

^<<v1-50-11,11>>^ Os habitantes daquela terra, os cananeus, viram a lamentação deles na eira de Atade e exclamaram: “Este é um grande luto para os egípcios!” Foi por isso que ao lugar que fica na região do Jordão chamaram Abel-Mizraim.^&#42;1^

[NOTE]
====
. Que significa “luto dos egípcios”.
====

[[v1-50-12]]

^<<v1-50-12,12>>^ Então, os seus filhos fizeram-lhe assim como ele os instruíra.

[[v1-50-13]]

^<<v1-50-13,13>>^ Os seus filhos transportaram-no para a terra de Canaã e enterraram-no na caverna do campo de Macpela, o campo em frente a Manre que Abraão tinha comprado a Efrom, o hitita, como propriedade para servir de sepultura.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois de enterrar o seu pai, José voltou ao Egito com os seus irmãos e todos os que tinham ido com ele enterrar o seu pai.

[[v1-50-15]]

^<<v1-50-15,15>>^ Vendo que o seu pai tinha morrido, os irmãos de José disseram: “Talvez José nos guarde rancor, e vai retribuir-nos todo o mal que lhe fizemos.”

[[v1-50-16]]

^<<v1-50-16,16>>^ Por isso, mandaram dizer a José: “O teu pai deu a seguinte ordem, antes de morrer:

[[v1-50-17]]

^<<v1-50-17,17>>^ ‘Isto é o que devem dizer a José: “Imploro-te: por favor, perdoa a transgressão dos teus irmãos e o pecado que cometeram ao fazer-te tanto mal.”’ Agora, por favor, perdoa a transgressão dos servos do Deus do teu pai.” E José chorou quando falaram com ele.

[[v1-50-18]]

^<<v1-50-18,18>>^ A seguir, vieram também os seus irmãos e prostraram-se diante dele, e disseram: “Aqui estamos como teus escravos!”

[[v1-50-19]]

^<<v1-50-19,19>>^ José disse-lhes: “Não tenham medo. Será que eu estou no lugar de Deus?

[[v1-50-20]]

^<<v1-50-20,20>>^ Embora quisessem fazer-me mal, Deus quis que as coisas acabassem bem e que muitas vidas fossem preservadas; e é o que está a fazer hoje.

[[v1-50-21]]

^<<v1-50-21,21>>^ Agora, não tenham medo. Continuarei a sustentar-vos, a vocês e às vossas crianças.” Assim, consolou-os e, com as suas palavras, tranquilizou-os.

[[v1-50-22]]

^<<v1-50-22,22>>^ José continuou a morar no Egito, ele e os da casa do seu pai, e José viveu 110 anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ José viu a terceira geração dos filhos de Efraim, e também os filhos de Maquir, filho de Manassés. José reconheceu-os como seus próprios filhos.^&#42;1^

[NOTE]
====
. Lit.: “Eles nasceram sobre os joelhos de José.”
====

[[v1-50-24]]

^<<v1-50-24,24>>^ Por fim, José disse aos seus irmãos: “Vou morrer, mas Deus, sem falta, voltará a sua atenção para vocês e certamente vos levará para fora desta terra, para a terra que jurou dar a Abraão, a Isaque e a Jacó.”

[[v1-50-25]]

^<<v1-50-25,25>>^ Por isso, José fez os filhos de Israel jurarem; disse-lhes: “Deus, sem falta, voltará a sua atenção para vocês. Prometam-me que levarão os meus ossos para fora daqui.”

[[v1-50-26]]

^<<v1-50-26,26>>^ E José morreu aos 110 anos de idade; então, mandaram embalsamá-lo, e ele foi posto num caixão,^&#42;1^ no Egito.

[NOTE]
====
. Ou: “ataúde”.
====

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]