include::./index.adoc[]

[[v1-48-0]]
=== Génesis, 48
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-48-1]]

^<<v1-48-1,1>>^ Depois destas coisas, José foi informado: “O seu pai está a ficar fraco.” Então, ele foi vê-lo e levou consigo os seus dois filhos, Manassés e Efraim.

[[v1-48-2]]

^<<v1-48-2,2>>^ Comunicou-se então a Jacó: “O seu filho José veio vê-lo.” Então, Israel reuniu forças e sentou-se na sua cama.

[[v1-48-3]]

^<<v1-48-3,3>>^ E Jacó disse a José:
“O Deus Todo-Poderoso apareceu-me em Luz, na terra de Canaã, e abençoou-me.

[[v1-48-4]]

^<<v1-48-4,4>>^ Ele disse-me: ‘Vou dar-te filhos, fazer-te numeroso, transformar-te numa congregação de povos e dar esta terra à tua descendência^&#42;1^ como uma propriedade permanente.’

[NOTE]
====
. Lit.: “semente”.
====

[[v1-48-5]]

^<<v1-48-5,5>>^ Agora, os teus dois filhos, que nasceram na terra do Egito antes de eu vir para o Egito, são meus. Efraim e Manassés irão tornar-se meus, assim como Rúben e Simeão são meus.

[[v1-48-6]]

^<<v1-48-6,6>>^ Mas os filhos que tiveres depois deles serão teus, e eles receberão a herança sob o nome dos seus irmãos.

[[v1-48-7]]

^<<v1-48-7,7>>^ Quando vinha de Padã, Raquel morreu ao meu lado, na terra de Canaã, enquanto ainda estava a alguma distância de Efrate. Eu enterrei-a lá, no caminho de Efrate, isto é, Belém.”

[[v1-48-8]]

^<<v1-48-8,8>>^ Então, Israel viu os filhos de José e perguntou: “Quem são estes?”

[[v1-48-9]]

^<<v1-48-9,9>>^ José respondeu ao seu pai: “São os meus filhos, que Deus me deu neste lugar.” Então ele disse: “Por favor, traz-mos, para que eu os abençoe.”

[[v1-48-10]]

^<<v1-48-10,10>>^ Os olhos de Israel estavam enfraquecidos por causa da idade, e ele mal podia ver. Por isso, José levou-os para perto dele, e o seu pai beijou-os e abraçou-os.

[[v1-48-11]]

^<<v1-48-11,11>>^ Israel disse a José: “Nunca imaginei que veria o teu rosto, mas Deus deixou-me ver também a tua descendência.”^&#42;1^

[NOTE]
====
. Lit.: “semente”.
====

[[v1-48-12]]

^<<v1-48-12,12>>^ José afastou-os então dos joelhos de Israel e curvou-se com o rosto por terra.

[[v1-48-13]]

^<<v1-48-13,13>>^ Em seguida, José pegou nos dois: Efraim, com a mão direita, para que ficasse à esquerda de Israel, e Manassés, com a mão esquerda, para que ficasse à direita de Israel, e levou-os para perto dele.

[[v1-48-14]]

^<<v1-48-14,14>>^ No entanto, embora Efraim fosse o mais novo, Israel estendeu a mão direita e pô-la sobre a cabeça dele, e pôs a mão esquerda sobre a cabeça de Manassés. Pôs as mãos assim de propósito, embora Manassés fosse o primogénito.

[[v1-48-15]]

^<<v1-48-15,15>>^ Então, abençoou José, e disse:
“O verdadeiro Deus, diante de quem andaram os meus pais, Abraão e Isaque,
O verdadeiro Deus, que me pastoreou durante toda a minha vida até ao dia de hoje,

[[v1-48-16]]

^<<v1-48-16,16>>^ O anjo que me tem livrado de todas as calamidades, abençoe os rapazes.
Que seja perpetuado por meio deles^&#42;1^ o meu nome e o nome dos meus pais, Abraão e Isaque;
Que aumentem até se tornarem uma multidão na terra.”

[NOTE]
====
. Lit.: “Que seja invocado sobre eles”.
====

[[v1-48-17]]

^<<v1-48-17,17>>^ E José viu que o pai mantinha a mão direita sobre a cabeça de Efraim, e não gostou disso, então, tentou pegar na mão do pai para a mudar da cabeça de Efraim para a cabeça de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ José disse ao seu pai: “Assim não, meu pai, porque este é o primogénito. Ponha a mão direita sobre a cabeça dele.”

[[v1-48-19]]

^<<v1-48-19,19>>^ Mas o seu pai recusava-se a fazê-lo, e disse: “Eu sei, meu filho, eu sei. Ele também se tornará um povo e também se tornará grande. No entanto, o seu irmão mais novo irá tornar-se maior do que ele, e a descendência^&#42;1^ de Efraim será suficientemente numerosa para formar nações inteiras.”^&#42;2^

[NOTE]
====
. Lit.: “semente”.
. Lit.: “será a plenitude das nações”.
====

[[v1-48-20]]

^<<v1-48-20,20>>^ Então, continuando a abençoá-los naquele dia, disse:
“Que o povo de Israel te mencione quando proferir bênçãos, dizendo:
‘Que Deus te torne como Efraim e como Manassés.’”
Assim, ele continuou a pôr Efraim à frente de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Depois, Israel disse a José: “Vê, eu vou morrer, mas Deus certamente continuará convosco e irá levar-vos de volta à terra dos vossos antepassados.

[[v1-48-22]]

^<<v1-48-22,22>>^ Quanto a mim, dou-te uma porção de terra^&#42;1^ a mais do que aos teus irmãos, a qual tomei das mãos dos amorreus com a minha espada e o meu arco.”

[NOTE]
====
. Ou: “uma encosta de montanha”. Lit.: “um ombro”.
====

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]