include::./index.adoc[]

[[v1-49-0]]
=== Génesis, 49
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-49-1]]

^<<v1-49-1,1>>^ E Jacó chamou os seus filhos e disse: “Reúnam-se, para que eu vos diga o que vos acontecerá na parte final dos dias.

[[v1-49-2]]

^<<v1-49-2,2>>^ Reúnam-se e escutem, filhos de Jacó, sim, escutem Israel, o vosso pai.

[[v1-49-3]]

^<<v1-49-3,3>>^ “Rúben, tu és o meu primogénito, o meu vigor e o primeiro fruto da minha faculdade reprodutiva, a excelência da dignidade e a excelência da força.

[[v1-49-4]]

^<<v1-49-4,4>>^ Imprudente como águas turbulentas, não sobressairás, pois subiste à cama do teu pai. Naquela ocasião, desonraste^&#42;1^ a minha cama. Ele realmente subiu à cama!

[NOTE]
====
. Ou: “profanaste”.
====

[[v1-49-5]]

^<<v1-49-5,5>>^ “Simeão e Levi são irmãos. As suas armas são instrumentos de violência.

[[v1-49-6]]

^<<v1-49-6,6>>^ Não entres no seu grupo, ó minha alma.^&#42;1^ Não te juntes à sua assembleia, ó minha honra,^&#42;2^ porque, na sua ira, mataram homens, e, por diversão, cortaram os tendões de touros.

[NOTE]
====
. Veja o Glossário.
. Ou, possivelmente: “disposição”.
====

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldita seja a sua ira, porque é cruel, e a sua fúria, porque é impiedosa. Irei dispersá-los pelo território de Jacó e espalhá-los em Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ “Quanto a ti, Judá, os teus irmãos irão louvar-te. A tua mão estará sobre o pescoço dos teus inimigos. Os filhos do teu pai irão curvar-se diante de ti.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá é uma cria de leão. Subirás depois de comer a presa, meu filho. Ele abaixa-se e estica-se como um leão e, como no caso de um leão, quem é que se atreve a acordá-lo?

[[v1-49-10]]

^<<v1-49-10,10>>^ O cetro não se afastará de Judá, nem o bastão de governante de entre os seus pés, até que venha Siló,^&#42;1^ e a ele pertencerá a obediência dos povos.

[NOTE]
====
. Que significa “aquele de quem é; aquele a quem pertence”.
====

[[v1-49-11]]

^<<v1-49-11,11>>^ Ele amarrará o seu jumento a uma videira e o seu jumentinho a uma videira seleta, lavará a sua vestimenta em vinho e a sua roupa no sangue das uvas.

[[v1-49-12]]

^<<v1-49-12,12>>^ Os seus olhos são vermelhos-escuros por causa do vinho, e os seus dentes são brancos por causa do leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ “Zebulão residirá junto à costa marítima, junto à costa onde os navios ficam ancorados, e a sua fronteira estender-se-á na direção de Sídon.

[[v1-49-14]]

^<<v1-49-14,14>>^ “Issacar é um jumento de ossos fortes, deitado debaixo das duas cargas.^&#42;1^

[NOTE]
====
. Ou: “dos dois alforges”.
====

[[v1-49-15]]

^<<v1-49-15,15>>^ Ele verá que o lugar de descanso é bom e que a terra é agradável. Baixará o ombro para levar o fardo e irá sujeitar-se a trabalhos forçados.

[[v1-49-16]]

^<<v1-49-16,16>>^ “Dã julgará o seu povo como uma das tribos de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será uma serpente à beira da estrada, uma víbora-cornuda na berma do caminho, que morde o calcanhar do cavalo, de modo que o cavaleiro cai para trás.

[[v1-49-18]]

^<<v1-49-18,18>>^ Esperarei a salvação que virá de ti, ó Jeová.

[[v1-49-19]]

^<<v1-49-19,19>>^ “Quanto a Gade, um bando de saqueadores irá atacá-lo, mas ele atacará o calcanhar deles.

[[v1-49-20]]

^<<v1-49-20,20>>^ “O pão^&#42;1^ de Aser será abundante,^&#42;2^ e ele fornecerá alimentos próprios de reis.

[NOTE]
====
. Ou: “alimento”.
. Lit.: “gordo”.
====

[[v1-49-21]]

^<<v1-49-21,21>>^ “Naftali é uma corça esbelta. Ele diz palavras elegantes.

[[v1-49-22]]

^<<v1-49-22,22>>^ “José é o ramo de uma árvore frutífera, uma árvore frutífera junto a uma nascente, cujos ramos se estendem por cima do muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Mas os arqueiros hostilizavam-no, atiravam contra ele e guardavam-lhe rancor.

[[v1-49-24]]

^<<v1-49-24,24>>^ Contudo, o seu arco permaneceu no lugar, e as suas mãos continuaram fortes e ágeis. Isto veio das mãos do poderoso de Jacó, do pastor, a pedra de Israel.

[[v1-49-25]]

^<<v1-49-25,25>>^ Ele^&#42;1^ provém do Deus do seu pai, e Deus irá ajudá-lo, e ele está com o Todo-Poderoso, e este irá abençoá-lo com as bênçãos dos céus acima, com as bênçãos das profundezas abaixo, com as bênçãos dos peitos e do ventre.

[NOTE]
====
. Isto é, José.
====

[[v1-49-26]]

^<<v1-49-26,26>>^ As bênçãos do teu pai serão superiores às bênçãos das montanhas eternas, às coisas desejáveis dos montes duradouros. Continuarão sobre a cabeça de José, no alto da cabeça do escolhido dentre os seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ “Benjamim continuará a dilacerar como um lobo. De manhã, comerá a presa e, ao anoitecer, repartirá o despojo.”

[[v1-49-28]]

^<<v1-49-28,28>>^ Destes procedem as 12 tribos de Israel, e isto foi o que o seu pai lhes disse ao abençoá-los. Deu a cada um deles uma bênção apropriada.

[[v1-49-29]]

^<<v1-49-29,29>>^ Depois, deu-lhes estas ordens: “Vou ser reunido ao meu povo.^&#42;1^ Enterrem-me com os meus pais na caverna que fica no campo de Efrom, o hitita,

[NOTE]
====
. Expressão poética que se refere à morte.
====

[[v1-49-30]]

^<<v1-49-30,30>>^ a caverna no campo de Macpela, em frente a Manre, na terra de Canaã, o campo que Abraão comprou a Efrom, o hitita, como propriedade para servir de sepultura.

[[v1-49-31]]

^<<v1-49-31,31>>^ Enterraram lá Abraão e Sara, sua esposa. Enterraram lá Isaque e Rebeca, sua esposa, e lá enterrei Lia.

[[v1-49-32]]

^<<v1-49-32,32>>^ O campo e a caverna que há lá foram comprados aos filhos de Hete.”

[[v1-49-33]]

^<<v1-49-33,33>>^ Assim, Jacó acabou de dar as instruções aos seus filhos. Então, recolheu os pés na cama e deu o seu último suspiro, e foi reunido ao seu povo.^&#42;1^

[NOTE]
====
. Expressão poética que se refere à morte.
====

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]