include::./index.adoc[]

[[v1-36-0]]
=== Génesis, 36
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-36-1]]

^<<v1-36-1,1>>^ Esta é a história de Esaú, isto é, Edom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú tomou esposas dentre as filhas de Canaã: Ada, filha de Elom, o hitita; Oolibama, filha de Aná e neta de Zibeão, o heveu;

[[v1-36-3]]

^<<v1-36-3,3>>^ e Basemate, filha de Ismael e irmã de Nebaiote.

[[v1-36-4]]

^<<v1-36-4,4>>^ Ada deu a Esaú um filho chamado Elifaz, Basemate deu à luz Reuel,

[[v1-36-5]]

^<<v1-36-5,5>>^ e Oolibama deu à luz Jeús, Jalão e Corá.
Estes são os filhos de Esaú, que nasceram na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Depois, Esaú foi para outra terra, longe de Jacó, seu irmão, levando as suas esposas, os seus filhos, as suas filhas, todas as pessoas^&#42;1^ da sua casa, o seu rebanho, todos os outros animais e toda a riqueza que tinha acumulado na terra de Canaã.

[NOTE]
====
. Ou: “almas”.
====

[[v1-36-7]]

^<<v1-36-7,7>>^ Pois os seus bens tinham-se tornado tantos que eles já não podiam morar juntos, e a terra em que estavam a morar^&#42;1^ não era suficiente para eles, por causa dos seus rebanhos.

[NOTE]
====
. Ou: “a viver como estrangeiros”.
====

[[v1-36-8]]

^<<v1-36-8,8>>^ Por isso, Esaú passou a viver na região montanhosa de Seir. Esaú é Edom.

[[v1-36-9]]

^<<v1-36-9,9>>^ Esta é a história de Esaú, o pai de Edom, na região montanhosa de Seir.

[[v1-36-10]]

^<<v1-36-10,10>>^ Estes são os nomes dos filhos de Esaú: Elifaz, filho de Ada, esposa de Esaú; Reuel, filho de Basemate, esposa de Esaú.

[[v1-36-11]]

^<<v1-36-11,11>>^ Os filhos de Elifaz foram Temã, Omar, Zefo, Gatã e Quenaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ Timna tornou-se concubina de Elifaz, filho de Esaú. Ela deu a Elifaz um filho chamado Amaleque. Estes são os filhos de Ada, esposa de Esaú.

[[v1-36-13]]

^<<v1-36-13,13>>^ Estes são os filhos de Reuel: Naate, Zerá, Samá e Mizá. Estes foram os filhos de Basemate, esposa de Esaú.

[[v1-36-14]]

^<<v1-36-14,14>>^ Estes foram os filhos que Oolibama, esposa de Esaú, filha de Aná e neta de Zibeão, deu a Esaú: Jeús, Jalão e Corá.

[[v1-36-15]]

^<<v1-36-15,15>>^ Estes são os chefes tribais^&#42;1^ dentre os descendentes de Esaú. Os filhos de Elifaz, primogénito de Esaú: chefe Temã, chefe Omar, chefe Zefo, chefe Quenaz,

[NOTE]
====
. Ou: “xeques”.
====

[[v1-36-16]]

^<<v1-36-16,16>>^ chefe Corá, chefe Gatã e chefe Amaleque. Estes são os chefes tribais descendentes de Elifaz, na terra de Edom. Estes são os filhos de Ada.

[[v1-36-17]]

^<<v1-36-17,17>>^ Estes são os filhos de Reuel, filho de Esaú: chefe Naate, chefe Zerá, chefe Samá e chefe Mizá. Estes são os chefes tribais descendentes de Reuel, na terra de Edom. Estes são os filhos de Basemate, esposa de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ Por fim, estes são os filhos de Oolibama, esposa de Esaú: chefe Jeús, chefe Jalão e chefe Corá. Estes são os chefes tribais descendentes de Oolibama, filha de Aná, esposa de Esaú.

[[v1-36-19]]

^<<v1-36-19,19>>^ Estes são os filhos de Esaú, e estes são os seus chefes tribais. Ele é Edom.

[[v1-36-20]]

^<<v1-36-20,20>>^ Estes são os filhos de Seir, o horeu, os habitantes daquela terra: Lotã, Sobal, Zibeão, Aná,

[[v1-36-21]]

^<<v1-36-21,21>>^ Disom, Ezer e Disã. Estes são os chefes tribais descendentes dos horeus, os filhos de Seir, na terra de Edom.

[[v1-36-22]]

^<<v1-36-22,22>>^ Os filhos de Lotã foram Hori e Hemã, e a irmã de Lotã era Timna.

[[v1-36-23]]

^<<v1-36-23,23>>^ Estes são os filhos de Sobal: Alvã, Manaate, Ebal, Sefo e Onão.

[[v1-36-24]]

^<<v1-36-24,24>>^ Estes são os filhos de Zibeão: Aiá e Aná. Este é o Aná que encontrou as fontes termais no deserto, enquanto cuidava dos jumentos de Zibeão, seu pai.

[[v1-36-25]]

^<<v1-36-25,25>>^ Estes são os filhos de Aná: Disom e Oolibama, filha de Aná.

[[v1-36-26]]

^<<v1-36-26,26>>^ Estes são os filhos de Disom: Hendã, Esbã, Itrã e Querã.

[[v1-36-27]]

^<<v1-36-27,27>>^ Estes são os filhos de Ezer: Bilã, Zaavã e Acã.

[[v1-36-28]]

^<<v1-36-28,28>>^ Estes são os filhos de Disã: Uz e Arã.

[[v1-36-29]]

^<<v1-36-29,29>>^ Estes são os chefes tribais descendentes dos horeus: chefe Lotã, chefe Sobal, chefe Zibeão, chefe Aná,

[[v1-36-30]]

^<<v1-36-30,30>>^ chefe Disom, chefe Ezer e chefe Disã. Estes são os chefes tribais descendentes dos horeus, segundo os seus chefes, na terra de Seir.

[[v1-36-31]]

^<<v1-36-31,31>>^ E os reis que reinaram na terra de Edom antes de haver qualquer rei sobre os israelitas^&#42;1^ foram os seguintes:

[NOTE]
====
. Lit.: “os filhos de Israel”.
====

[[v1-36-32]]

^<<v1-36-32,32>>^ Bela, filho de Beor, reinou em Edom, e o nome da sua cidade era Dinabá.

[[v1-36-33]]

^<<v1-36-33,33>>^ Quando Bela morreu, Jobabe, filho de Zerá, de Bozra, começou a reinar no seu lugar.

[[v1-36-34]]

^<<v1-36-34,34>>^ Quando Jobabe morreu, Husão, da terra dos temanitas, começou a reinar no seu lugar.

[[v1-36-35]]

^<<v1-36-35,35>>^ Quando Husão morreu, Hadade, filho de Bedade, começou a reinar no seu lugar. Ele derrotou os midianitas no território^&#42;1^ de Moabe, e o nome da sua cidade era Avite.

[NOTE]
====
. Lit.: “campo”.
====

[[v1-36-36]]

^<<v1-36-36,36>>^ Quando Hadade morreu, Samlá, de Masreca, começou a reinar no seu lugar.

[[v1-36-37]]

^<<v1-36-37,37>>^ Quando Samlá morreu, Saul, de Reobote, que fica junto ao rio, começou a reinar no seu lugar.

[[v1-36-38]]

^<<v1-36-38,38>>^ Quando Saul morreu, Baal-Hanã, filho de Acbor, começou a reinar no seu lugar.

[[v1-36-39]]

^<<v1-36-39,39>>^ Quando Baal-Hanã, filho de Acbor, morreu, Hadar começou a reinar no seu lugar. O nome da sua cidade era Paú, e o nome da sua esposa era Meetabel, filha de Matrede, que era filha de Mezaabe.

[[v1-36-40]]

^<<v1-36-40,40>>^ Estes são os nomes dos chefes tribais descendentes de Esaú, segundo as suas famílias e os seus lugares, alistados por nome: chefe Timna, chefe Alva, chefe Jetete,

[[v1-36-41]]

^<<v1-36-41,41>>^ chefe Oolibama, chefe Elá, chefe Pinom,

[[v1-36-42]]

^<<v1-36-42,42>>^ chefe Quenaz, chefe Temã, chefe Mibzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ chefe Magdiel e chefe Irão. Estes são os chefes tribais descendentes de Edom, segundo os seus povoados na terra que lhes pertencia. Este é Esaú, o pai de Edom.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]