include::./index.adoc[]

[[v1-30-0]]
=== Génesis, 30
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-30-1]]

^<<v1-30-1,1>>^ Quando Raquel viu que não tinha dado filhos a Jacó, ficou com ciúmes da sua irmã e começou a dizer a Jacó: “Dá-me filhos, senão morrerei.”

[[v1-30-2]]

^<<v1-30-2,2>>^ Com isto, Jacó enfureceu-se com Raquel e disse: “Por acaso, estou no lugar de Deus, que te impediu de ter filhos?”^&#42;1^

[NOTE]
====
. Ou: “que te negou o fruto do ventre”.
====

[[v1-30-3]]

^<<v1-30-3,3>>^ Então ela disse: “Aqui está a minha escrava Bila. Tem relações com ela, para que ela tenha filhos por mim^&#42;1^ e assim, por meio dela, eu também tenha filhos.”

[NOTE]
====
. Lit.: “dê à luz sobre os meus joelhos”.
====

[[v1-30-4]]

^<<v1-30-4,4>>^ Com isto, deu-lhe Bila, sua serva, como esposa, e Jacó teve relações com ela.

[[v1-30-5]]

^<<v1-30-5,5>>^ Bila ficou grávida e deu um filho a Jacó.

[[v1-30-6]]

^<<v1-30-6,6>>^ Raquel disse então: “Deus agiu como meu juiz e também escutou a minha voz, de modo que me deu um filho.” Foi por isso que lhe deu o nome de Dã.^&#42;1^

[NOTE]
====
. Que significa “juiz”.
====

[[v1-30-7]]

^<<v1-30-7,7>>^ Bila, serva de Raquel, ficou grávida mais uma vez e deu um segundo filho a Jacó.

[[v1-30-8]]

^<<v1-30-8,8>>^ Então, Raquel disse: “Em lutas árduas, lutei com a minha irmã e saí vencedora!” Portanto, deu-lhe o nome de Naftali.^&#42;1^

[NOTE]
====
. Que significa “as minhas lutas”.
====

[[v1-30-9]]

^<<v1-30-9,9>>^ Quando Lia viu que tinha parado de ter filhos, tomou Zilpa, sua serva, e deu-a a Jacó como esposa.

[[v1-30-10]]

^<<v1-30-10,10>>^ E Zilpa, a serva de Lia, deu um filho a Jacó.

[[v1-30-11]]

^<<v1-30-11,11>>^ Lia disse então: “Que sorte!” Por isso, deu-lhe o nome de Gade.^&#42;1^

[NOTE]
====
. Que significa “boa sorte”.
====

[[v1-30-12]]

^<<v1-30-12,12>>^ Depois disso, Zilpa, a serva de Lia deu um segundo filho a Jacó.

[[v1-30-13]]

^<<v1-30-13,13>>^ Lia disse então: “Que felicidade! As mulheres^&#42;1^ certamente dirão que sou feliz.” Portanto, deu-lhe o nome de Aser.^&#42;2^

[NOTE]
====
. Lit.: “filhas”, referindo-se às mulheres daquela terra.
. Que significa “feliz; felicidade”.
====

[[v1-30-14]]

^<<v1-30-14,14>>^ Nos dias da colheita do trigo, Rúben estava a passear pelo campo quando encontrou mandrágoras. Então levou-as a Lia, sua mãe. E Raquel disse a Lia: “Dá-me, por favor, algumas mandrágoras do teu filho.”

[[v1-30-15]]

^<<v1-30-15,15>>^ Mas Lia respondeu: “Achas pouco teres-me tirado o marido? Agora também me queres tirar as mandrágoras do meu filho?” Então Raquel disse: “Pronto, ele vai deitar-se contigo hoje à noite em troca das mandrágoras do teu filho.”

[[v1-30-16]]

^<<v1-30-16,16>>^ Quando Jacó estava a voltar do campo, ao anoitecer, Lia saiu ao seu encontro e disse: “É comigo que terás relações, pois comprei esse direito com as mandrágoras do meu filho.” Assim, ele deitou-se com ela naquela noite.

[[v1-30-17]]

^<<v1-30-17,17>>^ E Deus ouviu e atendeu Lia, e ela ficou grávida e deu um quinto filho a Jacó.

[[v1-30-18]]

^<<v1-30-18,18>>^ Então Lia disse: “Deus deu-me o meu salário,^&#42;1^ porque dei a minha serva ao meu marido.” Portanto, deu-lhe o nome de Issacar.^&#42;2^

[NOTE]
====
. Ou: “o salário de um contratado”.
. Que significa “ele é salário”.
====

[[v1-30-19]]

^<<v1-30-19,19>>^ Lia ficou grávida mais uma vez e deu um sexto filho a Jacó.

[[v1-30-20]]

^<<v1-30-20,20>>^ Lia disse então: “Deus deu-me, sim, deu-me a mim, um bom presente. Finalmente, o meu marido vai tolerar-me, pois dei-lhe seis filhos.” Portanto, deu-lhe o nome de Zebulão.^&#42;1^

[NOTE]
====
. Que significa “tolerância”.
====

[[v1-30-21]]

^<<v1-30-21,21>>^ Depois, ela teve uma filha e deu-lhe o nome de Diná.

[[v1-30-22]]

^<<v1-30-22,22>>^ Finalmente, Deus lembrou-se de Raquel, e Deus ouviu-a e atendeu-a, tornando possível que ficasse grávida.^&#42;1^

[NOTE]
====
. Lit.: “e Deus escutou-a e abriu-lhe o ventre”.
====

[[v1-30-23]]

^<<v1-30-23,23>>^ Ela ficou grávida e teve um filho. Disse então: “Deus tirou-me a minha vergonha!”

[[v1-30-24]]

^<<v1-30-24,24>>^ Portanto, deu-lhe o nome de José,^&#42;1^ dizendo: “Jeová acrescentou-me outro filho.”

[NOTE]
====
. Forma reduzida de Josifias, que significa “que Jah acrescente (aumente)”.
====

[[v1-30-25]]

^<<v1-30-25,25>>^ Depois de Raquel ter dado à luz José, Jacó disse imediatamente a Labão: “Deixe-me partir, para que eu volte para o meu lugar e para a minha terra.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dê-me as minhas esposas e os meus filhos, pelos quais o servi, para que eu me vá embora; pois sabe muito bem como o servi.”

[[v1-30-27]]

^<<v1-30-27,27>>^ Então, Labão disse-lhe: “Se achei favor aos teus olhos, . . . Entendi pelos presságios^&#42;1^ que Jeová está a abençoar-me por tua causa.”

[NOTE]
====
. Ou: “pelos sinais; pelas evidências”.
====

[[v1-30-28]]

^<<v1-30-28,28>>^ E acrescentou: “Estipula o teu salário, e irei dar-to.”

[[v1-30-29]]

^<<v1-30-29,29>>^ Por isso, Jacó disse-lhe: “O senhor sabe como o servi e como os seus rebanhos têm prosperado comigo.

[[v1-30-30]]

^<<v1-30-30,30>>^ Antes de eu vir, era pouco o que o senhor tinha, mas os seus rebanhos aumentaram e multiplicaram-se, e Jeová tem-no abençoado desde que cheguei. Agora, quando é que farei algo para a minha própria família?”

[[v1-30-31]]

^<<v1-30-31,31>>^ Ele perguntou então: “O que é que te devo dar?” E Jacó respondeu: “Não me dará absolutamente nada! Voltarei a pastorear o seu rebanho e a cuidar dele se me fizer o seguinte:

[[v1-30-32]]

^<<v1-30-32,32>>^ hoje, vou passar por todo o seu rebanho. Separe todas as ovelhas com manchas ou malhadas, todos os carneirinhos castanho-escuros e todas as cabras malhadas ou com manchas. De agora em diante, estes serão o meu salário.

[[v1-30-33]]

^<<v1-30-33,33>>^ E a minha retidão^&#42;1^ falará por mim no futuro, no dia em que o senhor vier para inspecionar o meu salário. Se houver comigo alguma cabra que não tenha manchas ou seja malhada, e algum carneirinho que não seja castanho-escuro, será considerado furtado.”

[NOTE]
====
. Ou: “honestidade”.
====

[[v1-30-34]]

^<<v1-30-34,34>>^ Diante disso, Labão disse: “Isso é excelente! Que aconteça segundo a tua palavra.”

[[v1-30-35]]

^<<v1-30-35,35>>^ Então, naquele dia, Labão separou os bodes listrados e os malhados e todas as cabras com manchas e as malhadas, todos aqueles que tinham algo branco e todos os carneirinhos castanho-escuros, e entregou-os aos cuidados dos seus filhos.

[[v1-30-36]]

^<<v1-30-36,36>>^ Depois, estabeleceu uma distância de três dias de viagem entre si e Jacó. E Jacó pastoreava o restante dos rebanhos de Labão.

[[v1-30-37]]

^<<v1-30-37,37>>^ Então, Jacó apanhou varas ainda verdes de estoraque, de amendoeira e de plátano, e, descascando parte das varas, deixou exposta a parte branca do seu interior.

[[v1-30-38]]

^<<v1-30-38,38>>^ Depois, colocou as varas descascadas diante do rebanho, nas calhas, nos bebedouros, onde os rebanhos iam beber água, para que ficassem com cio diante delas quando fossem beber.

[[v1-30-39]]

^<<v1-30-39,39>>^ Assim, os rebanhos acasalavam^&#42;1^ diante das varas, e os rebanhos produziam crias listradas, com manchas e malhadas.

[NOTE]
====
. Ou: “entravam no cio”.
====

[[v1-30-40]]

^<<v1-30-40,40>>^ Então, Jacó separou os cordeiros e colocou os rebanhos de frente para os listrados e de frente para todos os castanho-escuros entre os rebanhos de Labão. Depois, separou os seus próprios rebanhos e não os misturou com os rebanhos de Labão.

[[v1-30-41]]

^<<v1-30-41,41>>^ E, sempre que os animais robustos estavam com cio, Jacó colocava as varas nos bebedouros, diante dos olhos dos rebanhos, para que ficassem com cio perto das varas.

[[v1-30-42]]

^<<v1-30-42,42>>^ Mas, quando os animais eram fracos, não colocava lá as varas. Assim, os fracos ficavam sempre para Labão, mas os robustos para Jacó.

[[v1-30-43]]

^<<v1-30-43,43>>^ E o homem prosperou muito, e passou a ter grandes rebanhos, servas e servos, camelos e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]