include::./index.adoc[]

[[v1-28-0]]
=== Génesis, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-28-1]]

^<<v1-28-1,1>>^ Então, Isaque chamou Jacó e abençoou-o, e ordenou-lhe: “Não tomes uma esposa dentre as filhas de Canaã.

[[v1-28-2]]

^<<v1-28-2,2>>^ Vai para Padã-Arã, à casa de Betuel, pai da tua mãe, e toma de lá como esposa uma das filhas de Labão, irmão da tua mãe.

[[v1-28-3]]

^<<v1-28-3,3>>^ O Deus Todo-Poderoso irá abençoar-te, dar-te filhos e multiplicar-te, e certamente te tornarás uma congregação de povos.

[[v1-28-4]]

^<<v1-28-4,4>>^ E ele irá dar-te a bênção de Abraão, a ti e à tua descendência,^&#42;1^ para que tomes posse da terra em que tens vivido como estrangeiro, a terra que Deus deu a Abraão.”

[NOTE]
====
. Lit.: “semente”.
====

[[v1-28-5]]

^<<v1-28-5,5>>^ Assim, Isaque mandou Jacó embora, e este partiu para Padã-Arã, para ir ter com Labão, filho de Betuel, o arameu, e irmão de Rebeca, mãe de Jacó e de Esaú.

[[v1-28-6]]

^<<v1-28-6,6>>^ Esaú viu que Isaque tinha abençoado Jacó e que o tinha enviado a Padã-Arã, para que tomasse de lá uma esposa, e que, ao abençoá-lo, lhe tinha ordenado: “Não tomes uma esposa dentre as filhas de Canaã”.

[[v1-28-7]]

^<<v1-28-7,7>>^ Também viu que Jacó obedeceu ao pai e à mãe e partiu para Padã-Arã.

[[v1-28-8]]

^<<v1-28-8,8>>^ Então, Esaú percebeu que as filhas de Canaã desagradavam a Isaque, seu pai;

[[v1-28-9]]

^<<v1-28-9,9>>^ por isso, Esaú foi ter com Ismael e, além das esposas que já tinha, tomou como esposa Maalate, irmã de Nebaiote. Maalate era filha de Ismael, filho de Abraão.

[[v1-28-10]]

^<<v1-28-10,10>>^ Jacó saiu de Berseba e seguiu para Harã.

[[v1-28-11]]

^<<v1-28-11,11>>^ Chegando a certo lugar, preparou-se para passar lá a noite, visto que o sol já se tinha posto. Então, pegou numa das pedras daquele lugar e, pondo-a debaixo da cabeça, deitou-se ali mesmo.

[[v1-28-12]]

^<<v1-28-12,12>>^ E teve um sonho: viu uma escada apoiada na terra, e o seu topo chegava aos céus. E anjos de Deus subiam e desciam por ela.

[[v1-28-13]]

^<<v1-28-13,13>>^ Por cima dela estava Jeová, e ele disse:
“Eu sou Jeová, o Deus de Abraão, teu pai, e o Deus de Isaque. Vou dar-te a ti e à tua descendência^&#42;1^ a terra em que estás deitado.

[NOTE]
====
. Lit.: “semente”.
====

[[v1-28-14]]

^<<v1-28-14,14>>^ E a tua descendência^&#42;1^ certamente se tornará como as partículas de pó da terra, e tu irás espalhar-te para o oeste, para o leste, para o norte e para o sul; e todas as famílias da terra certamente serão abençoadas^&#42;2^ por meio de ti e por meio da tua descendência.^&#42;3^

[NOTE]
====
. Lit.: “semente”.
. Ou: “obterão para si uma bênção”.
. Lit.: “semente”.
====

[[v1-28-15]]

^<<v1-28-15,15>>^ Eu estou contigo, vou proteger-te onde quer que vás e vou trazer-te de volta a esta terra. Não te deixarei até que tenha feito o que te prometi.”

[[v1-28-16]]

^<<v1-28-16,16>>^ Então, Jacó acordou do sono e disse: “Jeová realmente está neste lugar, e eu não sabia disso.”

[[v1-28-17]]

^<<v1-28-17,17>>^ E ele ficou com medo e acrescentou: “Este lugar inspira mesmo temor! Só pode ser a casa de Deus, e este é o portão dos céus.”

[[v1-28-18]]

^<<v1-28-18,18>>^ Assim, Jacó levantou-se de manhã cedo, pegou na pedra em que apoiara a cabeça, colocou-a em pé como uma coluna e derramou óleo sobre ela.

[[v1-28-19]]

^<<v1-28-19,19>>^ Então, deu àquele lugar o nome de Betel;^&#42;1^ mas, anteriormente, o nome da cidade era Luz.

[NOTE]
====
. Que significa “casa de Deus”.
====

[[v1-28-20]]

^<<v1-28-20,20>>^ E Jacó fez um voto, dizendo: “Se Deus continuar comigo e me proteger na minha viagem, se me der pão para comer e roupa para vestir,

[[v1-28-21]]

^<<v1-28-21,21>>^ e eu retornar em paz à casa do meu pai, então, certamente Jeová terá mostrado que é o meu Deus.

[[v1-28-22]]

^<<v1-28-22,22>>^ Esta pedra que ergui como coluna irá tornar-se uma casa de Deus; e sem falta te darei um décimo de tudo o que me deres.”

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]