include::./index.adoc[]

[[v1-3-0]]
=== Génesis, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-3-1]]

^<<v1-3-1,1>>^ A serpente era o mais cauteloso^&#42;1^ de todos os animais selvagens que Jeová Deus fizera. Assim, ela disse à mulher: “Foi realmente isso que Deus disse, que não devem comer de todas as árvores do jardim?”

[NOTE]
====
. Ou: “astuto; ardiloso”.
====

[[v1-3-2]]

^<<v1-3-2,2>>^ Então, a mulher disse à serpente: “Podemos comer do fruto das árvores do jardim.

[[v1-3-3]]

^<<v1-3-3,3>>^ Mas, sobre o fruto da árvore que está no meio do jardim, Deus disse: ‘Não comam dele,^&#42;1^ não, nem lhe toquem, senão morrerão.’”

[NOTE]
====
. Ou: “dela”, isto é, da árvore.
====

[[v1-3-4]]

^<<v1-3-4,4>>^ Então, a serpente disse à mulher: “Certamente não morrerão.

[[v1-3-5]]

^<<v1-3-5,5>>^ Pois Deus sabe que, no mesmo dia em que o comerem, os vossos olhos irão abrir-se e vocês serão como Deus, sabendo o que é bom e o que é mau.”

[[v1-3-6]]

^<<v1-3-6,6>>^ Consequentemente, a mulher viu que a árvore era boa para alimento e que era desejável aos olhos, sim, a árvore era agradável de se contemplar. Então, ela apanhou o fruto e começou a comê-lo. Depois, também deu do fruto ao seu marido, quando ele estava com ela, e ele começou a comê-lo.

[[v1-3-7]]

^<<v1-3-7,7>>^ Então abriram-se os olhos de ambos, e eles perceberam que estavam nus. Por isso, costuraram folhas de figueira para cobrir a nudez.^&#42;1^

[NOTE]
====
. Ou: “a área à volta das ancas”.
====

[[v1-3-8]]

^<<v1-3-8,8>>^ Mais tarde, ouviram a voz de Jeová Deus enquanto ele andava pelo jardim, por volta da hora em que a brisa soprava, e o homem e a sua esposa esconderam-se da face de Jeová Deus entre as árvores do jardim.

[[v1-3-9]]

^<<v1-3-9,9>>^ E Jeová Deus chamava o homem e dizia-lhe: “Onde estás?”

[[v1-3-10]]

^<<v1-3-10,10>>^ Por fim, ele respondeu: “Ouvi a tua voz no jardim, mas fiquei com medo porque estava nu, por isso, escondi-me.”

[[v1-3-11]]

^<<v1-3-11,11>>^ Com isso, ele perguntou: “Quem é que te disse que estavas nu? Comeste da árvore que te ordenei que não comesses?”

[[v1-3-12]]

^<<v1-3-12,12>>^ O homem disse: “A mulher que me deste para estar comigo, foi ela que me deu do fruto da árvore, por isso, comi.”

[[v1-3-13]]

^<<v1-3-13,13>>^ Jeová Deus disse então à mulher: “O que é que fizeste?” A mulher respondeu: “A serpente enganou-me, por isso, comi.”

[[v1-3-14]]

^<<v1-3-14,14>>^ Então, Jeová Deus disse à serpente: “Por teres feito isto, és maldita entre todos os animais domésticos e todos os animais selvagens. Rastejarás sobre o teu ventre, e comerás pó todos os dias da tua vida.

[[v1-3-15]]

^<<v1-3-15,15>>^ E porei inimizade^&#42;1^ entre ti e a mulher, e entre o teu descendente^&#42;2^ e o seu descendente.^&#42;3^ Este esmagará^&#42;4^ a tua cabeça,^&#42;5^ e tu ferirás^&#42;6^ o seu calcanhar.”

[NOTE]
====
. Ou: “hostilidade”.
. Lit.: “a tua semente”.
. Lit.: “a semente”.
. Ou: “machucará; golpeará”.
. Isto é, a cabeça da serpente.
. Ou: “machucarás; esmagarás”.
====

[[v1-3-16]]

^<<v1-3-16,16>>^ À mulher ele disse: “Aumentarei muito as dores da tua gravidez; com dores darás à luz filhos, e terás desejo de estar com o teu marido, e ele irá dominar-te.”

[[v1-3-17]]

^<<v1-3-17,17>>^ E a Adão^&#42;1^ ele disse: “Visto que escutaste a voz da tua esposa e comeste da árvore a respeito da qual te dei a ordem: ‘Não comas dela’, maldito é o solo por tua causa. Com dores comerás dos seus produtos todos os dias da tua vida.

[NOTE]
====
. Que significa “homem terreno; humanidade”.
====

[[v1-3-18]]

^<<v1-3-18,18>>^ Irá produzir-te espinhos e abrolhos, e terás de comer a vegetação do campo.

[[v1-3-19]]

^<<v1-3-19,19>>^ No suor do teu rosto comerás pão,^&#42;1^ até que voltes ao solo, pois dele foste tirado; porque tu és pó e ao pó voltarás.”

[NOTE]
====
. Ou: “alimentos”.
====

[[v1-3-20]]

^<<v1-3-20,20>>^ Depois disso, Adão chamou Eva^&#42;1^ à sua esposa, porque ela havia de tornar-se a mãe de todos os viventes.

[NOTE]
====
. Que significa “vivente”.
====

[[v1-3-21]]

^<<v1-3-21,21>>^ E Jeová Deus fez vestes compridas de pele para Adão e para a sua esposa, a fim de os vestir.

[[v1-3-22]]

^<<v1-3-22,22>>^ Jeová Deus disse então: “O homem tornou-se como um de nós, sabendo o que é bom e o que é mau. Agora, para que ele não estenda a mão e também apanhe o fruto da árvore da vida, e coma, e viva para sempre,^&#42;1^ . . .”

[NOTE]
====
. Ou: “por tempo indefinido”.
====

[[v1-3-23]]

^<<v1-3-23,23>>^ Com isso, Jeová Deus expulsou-o do jardim do Éden para cultivar o solo do qual fora tirado.

[[v1-3-24]]

^<<v1-3-24,24>>^ Assim ele expulsou o homem, e colocou a leste do jardim do Éden os querubins e a lâmina ardente de uma espada que girava continuamente, guardando o caminho para a árvore da vida.

'''

xref:001-genesis/001-genesis-002.adoc#v1-2-0[&#60; Capítulo Anterior] | <<v1-3-0,Topo>> | xref:001-genesis/001-genesis-004.adoc#v1-4-0[Próximo Capítulo &#62;]