include::./index.adoc[]

[[v1-43-0]]
=== Génesis, 43
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-43-1]]

^<<v1-43-1,1>>^ A fome era severa na região.

[[v1-43-2]]

^<<v1-43-2,2>>^ Assim, quando se acabaram os cereais que tinham trazido do Egito, o pai disse-lhes: “Voltem e comprem alguns alimentos para nós.”

[[v1-43-3]]

^<<v1-43-3,3>>^ Judá disse-lhe então: “O homem avisou-nos claramente: ‘Não voltem à minha presença,^&#42;1^ a menos que o vosso irmão esteja convosco.’

[NOTE]
====
. Lit.: “Não verão a minha face”.
====

[[v1-43-4]]

^<<v1-43-4,4>>^ Se enviar o nosso irmão connosco, nós iremos lá e compraremos alimentos para si.

[[v1-43-5]]

^<<v1-43-5,5>>^ Mas, se não o deixar ir connosco, não iremos, pois o homem disse-nos: ‘Não voltem à minha presença,^&#42;1^ a menos que o vosso irmão esteja convosco.’”

[NOTE]
====
. Lit.: “Não verão a minha face”.
====

[[v1-43-6]]

^<<v1-43-6,6>>^ E Israel perguntou: “Porque é que me trouxeram dificuldades, contando ao homem que tinham outro irmão?”

[[v1-43-7]]

^<<v1-43-7,7>>^ Eles responderam: “O homem perguntou diretamente sobre nós e sobre os nossos parentes: ‘O vosso pai ainda está vivo? Têm outro irmão?’ E nós demos-lhe estas informações. Como poderíamos saber que ele diria: ‘Tragam cá o vosso irmão’?”

[[v1-43-8]]

^<<v1-43-8,8>>^ Então, Judá insistiu com Israel, seu pai: “Envie o rapaz comigo e deixe-nos ir, para que nós, o senhor e os nossos filhos fiquemos vivos, e não morramos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Garantirei a segurança dele.^&#42;1^ Pode considerar-me responsável por ele. Se falhar em trazê-lo de volta à sua presença, carregarei esse pecado diante de si por toda a minha vida.

[NOTE]
====
. Ou: “serei a fiança por ele”.
====

[[v1-43-10]]

^<<v1-43-10,10>>^ Mas, se não nos tivéssemos demorado, já poderíamos ter ido e voltado duas vezes.”

[[v1-43-11]]

^<<v1-43-11,11>>^ Portanto, Israel, seu pai, disse-lhes: “Se tem de ser assim, então, façam o seguinte: ponham os melhores produtos desta terra nas vossas sacas^&#42;1^ e levem-nos ao homem como presente. Levem um pouco de bálsamo, um pouco de mel, ládano, casca resinosa de árvore, pistácios e amêndoas.

[NOTE]
====
. Ou: “nos vossos recipientes”.
====

[[v1-43-12]]

^<<v1-43-12,12>>^ Levem convosco o dobro do dinheiro, e levem também de volta o dinheiro que foi devolvido na boca das vossas sacas. Talvez tenha sido um engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Levem o vosso irmão e vão, voltem ao homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ Que o Deus Todo-Poderoso vos conceda que o homem tenha compaixão de vocês, de modo que liberte o vosso outro irmão e Benjamim. Quanto a mim, se tiver de ficar sem os meus filhos, ficarei sem os meus filhos!”

[[v1-43-15]]

^<<v1-43-15,15>>^ Assim, depois de pegarem no presente e no dobro do dinheiro, os homens, juntamente com Benjamim, desceram até ao Egito e compareceram novamente perante José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu Benjamim com eles, disse imediatamente ao homem que era encarregado da sua casa: “Leva os homens para casa, abate animais e prepara a refeição, pois comerão comigo ao meio-dia.”

[[v1-43-17]]

^<<v1-43-17,17>>^ O homem fez imediatamente assim como José lhe tinha dito e levou-os para a casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Mas os homens ficaram com medo quando foram levados para a casa de José, e começaram a dizer: “Estamos a ser trazidos para aqui por causa do dinheiro que foi devolvido nas nossas sacas, da última vez. Agora, irão atacar-nos e escravizar-nos, e ficarão com os nossos jumentos!”

[[v1-43-19]]

^<<v1-43-19,19>>^ Por isso, aproximaram-se do homem que era encarregado da casa de José e falaram com ele à entrada da casa.

[[v1-43-20]]

^<<v1-43-20,20>>^ Disseram: “Perdão, meu senhor! Da primeira vez que viemos, descemos para comprar alimentos.

[[v1-43-21]]

^<<v1-43-21,21>>^ Mas, quando chegámos ao lugar onde íamos pernoitar e começámos a abrir as nossas sacas, vimos que o dinheiro de cada um estava na boca da sua saca, o dinheiro na quantia exata. Por isso, gostaríamos de o devolver pessoalmente.

[[v1-43-22]]

^<<v1-43-22,22>>^ E trouxemos mais dinheiro para comprar alimentos. Não sabemos quem colocou o nosso dinheiro nas nossas sacas.”

[[v1-43-23]]

^<<v1-43-23,23>>^ Ele disse então: “Fiquem tranquilos. Não tenham medo. O vosso Deus e o Deus do vosso pai colocou um tesouro nas vossas sacas. Eu recebi o vosso dinheiro.” Depois disso, trouxe-lhes Simeão.

[[v1-43-24]]

^<<v1-43-24,24>>^ Então, o homem trouxe-os para dentro da casa de José, deu-lhes água para lavarem os pés e forragem para os jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ E eles prepararam o presente para a chegada de José ao meio-dia, pois souberam que iriam tomar ali uma refeição.

[[v1-43-26]]

^<<v1-43-26,26>>^ Quando José entrou em casa, trouxeram-lhe o presente e prostraram-se por terra diante dele.

[[v1-43-27]]

^<<v1-43-27,27>>^ Depois disto, ele perguntou se estavam bem e disse: “Como está o vosso velho pai, de quem me falaram? Ainda está vivo?”

[[v1-43-28]]

^<<v1-43-28,28>>^ Eles responderam: “O seu servo, nosso pai, está bem. Ainda está vivo.” Então, curvaram-se e prostraram-se por terra.

[[v1-43-29]]

^<<v1-43-29,29>>^ Quando ele levantou os olhos e viu Benjamim, o seu irmão, filho da sua mãe, disse: “É este o vosso irmão, o mais novo, de quem me falaram?” E acrescentou: “Que Deus te mostre o seu favor, meu filho.”

[[v1-43-30]]

^<<v1-43-30,30>>^ Profundamente emocionado por causa do irmão, José saiu apressadamente à procura de um lugar para chorar. Entrou então num aposento reservado e começou a chorar.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois disso, lavou o rosto e saiu, agora que já se conseguia controlar, e disse: “Sirvam a refeição.”

[[v1-43-32]]

^<<v1-43-32,32>>^ Serviram José à parte e os seus irmãos também à parte, e os egípcios que estavam com ele comeram à parte, pois os egípcios não podiam tomar uma refeição com os hebreus. Isso é algo detestável para os egípcios.

[[v1-43-33]]

^<<v1-43-33,33>>^ Fizeram com que os irmãos^&#42;1^ se sentassem diante dele, desde o primogénito, segundo o seu direito de primogénito, até ao mais jovem, e olhavam uns para os outros pasmados.

[NOTE]
====
. Lit.: “eles”.
====

[[v1-43-34]]

^<<v1-43-34,34>>^ Ele mandava porções de alimentos da sua mesa para a deles, mas aumentava a porção de Benjamim cinco vezes mais do que as porções de todos os outros. Assim, banquetearam-se e beberam fartamente com ele.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]