include::./index.adoc[]

[[v1-4-0]]
=== Génesis, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-4-1]]

^<<v1-4-1,1>>^ Adão teve relações sexuais com Eva, sua esposa, e ela ficou grávida. Quando deu à luz Caim, ela disse: “Tive^&#42;1^ um menino com a ajuda de Jeová.”

[NOTE]
====
. Lit.: “Produzi”.
====

[[v1-4-2]]

^<<v1-4-2,2>>^ Mais tarde, deu novamente à luz e teve Abel, irmão de Caim.
Abel tornou-se pastor de ovelhas, e Caim tornou-se agricultor.

[[v1-4-3]]

^<<v1-4-3,3>>^ Depois de algum tempo, Caim trouxe alguns produtos da terra como oferta para Jeová.

[[v1-4-4]]

^<<v1-4-4,4>>^ Mas Abel trouxe alguns primogénitos do seu rebanho, com a gordura deles. Ao passo que Jeová olhou com favor para Abel e para a sua oferta,

[[v1-4-5]]

^<<v1-4-5,5>>^ não olhou com favor para Caim e para a sua oferta. E Caim ficou furioso e abatido.^&#42;1^

[NOTE]
====
. Lit.: “e a sua face descaiu”.
====

[[v1-4-6]]

^<<v1-4-6,6>>^ Então, Jeová disse a Caim: “Porque é que estás furioso e abatido?

[[v1-4-7]]

^<<v1-4-7,7>>^ Se passares a fazer o bem, não voltarás a ter o meu favor?^&#42;1^ Mas, se não passares a fazer o bem, o pecado está à porta, à espreita, e tem desejo ardente de te dominar; mas será que o conseguirás vencer?”

[NOTE]
====
. Ou: “não haverá enaltecimento”.
====

[[v1-4-8]]

^<<v1-4-8,8>>^ Depois, Caim disse a Abel, seu irmão: “Vamos ao campo.” Enquanto estavam no campo, Caim atacou Abel, seu irmão, e matou-o.

[[v1-4-9]]

^<<v1-4-9,9>>^ Mais tarde, Jeová perguntou a Caim: “Onde está Abel, o teu irmão?” E Caim respondeu: “Não sei. Sou eu o guardião do meu irmão?”

[[v1-4-10]]

^<<v1-4-10,10>>^ Então Ele disse: “O que é que fizeste? Escuta! O sangue do teu irmão está a clamar a mim desde o solo.

[[v1-4-11]]

^<<v1-4-11,11>>^ E agora és maldito e serás banido do solo que abriu a boca para receber da tua mão o sangue do teu irmão.

[[v1-4-12]]

^<<v1-4-12,12>>^ Quando cultivares o solo, ele não te dará os seus produtos.^&#42;1^ Tornar-te-ás errante e fugitivo na terra.”

[NOTE]
====
. Lit.: “o seu poder”.
====

[[v1-4-13]]

^<<v1-4-13,13>>^ Então, Caim disse a Jeová: “A punição pelo meu erro é demasiado pesada para eu a suportar.

[[v1-4-14]]

^<<v1-4-14,14>>^ Hoje expulsas-me desta terra,^&#42;1^ e ficarei escondido da tua face; vou tornar-me errante e fugitivo na terra, e quem me encontrar certamente me matará.”

[NOTE]
====
. Lit.: “da superfície do solo”.
====

[[v1-4-15]]

^<<v1-4-15,15>>^ Então, Jeová disse-lhe: “Por essa razão, quem matar Caim sofrerá vingança sete vezes.”
Assim, Jeová estabeleceu um sinal para Caim, a fim de que ele não fosse morto por quem o encontrasse.

[[v1-4-16]]

^<<v1-4-16,16>>^ Então, Caim foi-se embora de diante de Jeová e passou a morar na terra do Exílio,^&#42;1^ a leste do Éden.

[NOTE]
====
. Ou: “terra de Node”.
====

[[v1-4-17]]

^<<v1-4-17,17>>^ Depois, Caim teve relações sexuais com a sua esposa, e ela ficou grávida e deu à luz Enoque. Então, começou a construir uma cidade e deu à cidade o nome do seu filho Enoque.

[[v1-4-18]]

^<<v1-4-18,18>>^ Mais tarde, Enoque tornou-se pai de Irade. Irade tornou-se pai de Meujael, Meujael tornou-se pai de Metusael, e Metusael tornou-se pai de Lameque.

[[v1-4-19]]

^<<v1-4-19,19>>^ Lameque tomou para si duas esposas. O nome da primeira era Ada e o nome da segunda era Zilá.

[[v1-4-20]]

^<<v1-4-20,20>>^ Ada deu à luz Jabal. Ele foi o pai dos que moram em tendas e têm gado.

[[v1-4-21]]

^<<v1-4-21,21>>^ O nome do seu irmão era Jubal. Ele foi o pai de todos os que tocam harpa e flauta.^&#42;1^

[NOTE]
====
. Ou: “pífaro”.
====

[[v1-4-22]]

^<<v1-4-22,22>>^ Zilá também deu à luz e teve Tubalcaim, que forjava todo o tipo de ferramentas de cobre e de ferro. E a irmã de Tubalcaim era Naamá.

[[v1-4-23]]

^<<v1-4-23,23>>^ Então, Lameque compôs estas palavras para as suas esposas Ada e Zilá:
“Ouçam a minha voz, esposas de Lameque;
Deem ouvidos à minha declaração:
Matei um homem porque ele me feriu,
Sim, um jovem, porque me golpeou.

[[v1-4-24]]

^<<v1-4-24,24>>^ Se Caim deve ser vingado sete vezes,
Então Lameque setenta e sete vezes.”

[[v1-4-25]]

^<<v1-4-25,25>>^ Adão teve novamente relações sexuais com a sua esposa, e ela teve um filho. Ela deu-lhe o nome de Sete^&#42;1^ porque, segundo disse: “Deus designou-me outro descendente^&#42;2^ no lugar de Abel, visto que Caim o matou.”

[NOTE]
====
. Que significa “designado; posto; colocado”.
. Lit.: “outra semente”.
====

[[v1-4-26]]

^<<v1-4-26,26>>^ Sete também se tornou pai de um filho, e deu-lhe o nome de Enos. Naquele tempo, as pessoas começaram a invocar o nome de Jeová.

'''

xref:001-genesis/001-genesis-003.adoc#v1-3-0[&#60; Capítulo Anterior] | <<v1-4-0,Topo>> | xref:001-genesis/001-genesis-005.adoc#v1-5-0[Próximo Capítulo &#62;]