include::./index.adoc[]

[[v1-29-0]]
=== Génesis, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-29-1]]

^<<v1-29-1,1>>^ Depois, Jacó continuou a sua viagem e foi para a terra dos orientais.^&#42;1^

[NOTE]
====
. Isto é, para uma terra a leste de Canaã.
====

[[v1-29-2]]

^<<v1-29-2,2>>^ Então, ele viu um poço no campo, junto ao qual havia três rebanhos de ovelhas deitadas, porque se costumava dar água daquele poço aos rebanhos. Havia uma grande pedra sobre a boca do poço.

[[v1-29-3]]

^<<v1-29-3,3>>^ Quando todos os rebanhos eram ali ajuntados, os pastores rolavam a pedra da boca do poço e davam água aos rebanhos, e depois recolocavam a pedra no lugar, sobre a boca do poço.

[[v1-29-4]]

^<<v1-29-4,4>>^ Então, Jacó perguntou-lhes: “Meus irmãos, de onde é que são?” Eles responderam: “Somos de Harã.”

[[v1-29-5]]

^<<v1-29-5,5>>^ Ele perguntou-lhes: “Conhecem Labão, neto de Naor?” Eles responderam: “Conhecemos.”

[[v1-29-6]]

^<<v1-29-6,6>>^ Em vista disso, ele disse-lhes: “Ele está bem?” Responderam: “Ele está bem. E ali vem Raquel, a sua filha, com as ovelhas!”

[[v1-29-7]]

^<<v1-29-7,7>>^ Então ele disse: “Ainda estamos a meio do dia. Não está na hora de recolher os rebanhos. Deem água às ovelhas e depois levem-nas a pastar.”

[[v1-29-8]]

^<<v1-29-8,8>>^ Assim, disseram: “Não nos é permitido fazê-lo até que todos os rebanhos sejam ajuntados e a pedra seja rolada da boca do poço. Só então damos água às ovelhas.”

[[v1-29-9]]

^<<v1-29-9,9>>^ Enquanto ele ainda estava a falar com eles, Raquel chegou com as ovelhas do seu pai, pois era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ Quando Jacó viu Raquel, filha de Labão, irmão da sua mãe, e as ovelhas de Labão, Jacó aproximou-se imediatamente, rolou a pedra da boca do poço e deu água às ovelhas de Labão, irmão da sua mãe.

[[v1-29-11]]

^<<v1-29-11,11>>^ Então, Jacó beijou Raquel, e levantou a sua voz e irrompeu em lágrimas.

[[v1-29-12]]

^<<v1-29-12,12>>^ Jacó contou a Raquel que era parente^&#42;1^ do seu pai e filho de Rebeca. E ela foi a correr contá-lo ao seu pai.

[NOTE]
====
. Lit.: “irmão”.
====

[[v1-29-13]]

^<<v1-29-13,13>>^ Assim que Labão ouviu a notícia sobre Jacó, filho da sua irmã, veio a correr ao seu encontro. Ele abraçou-o e beijou-o, e levou-o para dentro da sua casa. E Jacó contou a Labão tudo o que lhe tinha acontecido.

[[v1-29-14]]

^<<v1-29-14,14>>^ Labão disse-lhe: “És realmente sangue do meu sangue.”^&#42;1^ Então, Jacó ficou com ele um mês inteiro.

[NOTE]
====
. Ou: “realmente meu parente consanguíneo”. Lit.: “realmente meu osso e minha carne”.
====

[[v1-29-15]]

^<<v1-29-15,15>>^ Labão disse então a Jacó: “Só por seres meu parente,^&#42;1^ vais servir-me de graça? Diz-me, qual será o teu salário?”

[NOTE]
====
. Lit.: “irmão”.
====

[[v1-29-16]]

^<<v1-29-16,16>>^ Ora, Labão tinha duas filhas. O nome da mais velha era Lia e o nome da mais nova era Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Mas os olhos de Lia não tinham brilho, ao passo que Raquel se tinha tornado uma mulher muito bonita e atraente.

[[v1-29-18]]

^<<v1-29-18,18>>^ Jacó tinha-se apaixonado por Raquel, de modo que disse: “Estou disposto a servi-lo sete anos por Raquel, a sua filha mais nova.”

[[v1-29-19]]

^<<v1-29-19,19>>^ Então Labão disse: “É melhor para mim dá-la a ti do que dá-la a outro homem. Continua a morar comigo.”

[[v1-29-20]]

^<<v1-29-20,20>>^ E Jacó serviu sete anos por Raquel, que, aos seus olhos, pareceram apenas alguns dias, por causa do seu amor por ela.

[[v1-29-21]]

^<<v1-29-21,21>>^ Então, Jacó disse a Labão: “Entregue-me a minha esposa, porque terminaram os meus dias, para que eu tenha relações com ela.”

[[v1-29-22]]

^<<v1-29-22,22>>^ Em vista disso, Labão reuniu todos os homens daquele lugar e deu um banquete.

[[v1-29-23]]

^<<v1-29-23,23>>^ Mas, à noite, ele pegou em Lia, a sua filha, e levou-a a Jacó, para que tivesse relações com ela.

[[v1-29-24]]

^<<v1-29-24,24>>^ Labão deu também a sua serva Zilpa, como serva, à sua filha Lia.

[[v1-29-25]]

^<<v1-29-25,25>>^ De manhã, Jacó viu que era Lia! Assim, ele disse a Labão: “O que é que me fez? Não foi por Raquel que o servi? Porque é que me enganou?”

[[v1-29-26]]

^<<v1-29-26,26>>^ Labão respondeu: “Aqui não é costume dar a mais nova antes da primogénita.

[[v1-29-27]]

^<<v1-29-27,27>>^ Celebra a semana desta mulher. Depois receberás também a outra mulher em troca de me servires mais sete anos.”

[[v1-29-28]]

^<<v1-29-28,28>>^ Jacó assim fez e celebrou a semana daquela mulher, e depois Labão deu-lhe a sua filha Raquel como esposa.

[[v1-29-29]]

^<<v1-29-29,29>>^ Além disso, ele deu a sua serva Bila, como serva, à sua filha Raquel.

[[v1-29-30]]

^<<v1-29-30,30>>^ Então, Jacó também teve relações com Raquel. E ele amava Raquel mais do que amava Lia, e serviu Labão por mais sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Quando Jeová viu que Lia não era amada,^&#42;1^ tornou possível que ela ficasse grávida,^&#42;2^ mas Raquel era estéril.

[NOTE]
====
. Lit.: “Lia era odiada”.
. Lit.: “abriu o seu ventre”.
====

[[v1-29-32]]

^<<v1-29-32,32>>^ Então, Lia ficou grávida e teve um filho, e deu-lhe o nome de Rúben,^&#42;1^ pois disse: “É porque Jeová olhou para a minha aflição, pois agora o meu marido começará a amar-me.”

[NOTE]
====
. Que significa “Vê, um filho!”
====

[[v1-29-33]]

^<<v1-29-33,33>>^ Ela ficou novamente grávida e teve um filho, e disse: “É porque Jeová me ouviu, visto que não era amada; assim, também me deu este.” Por isso, deu-lhe o nome de Simeão.^&#42;1^

[NOTE]
====
. Que significa “ouvir”.
====

[[v1-29-34]]

^<<v1-29-34,34>>^ Ela ficou grávida mais uma vez e teve outro filho, e disse: “Agora, o meu marido irá unir-se a mim, porque lhe dei três filhos.” Portanto, ele recebeu o nome de Levi.^&#42;1^

[NOTE]
====
. Que significa “adesão; unido”.
====

[[v1-29-35]]

^<<v1-29-35,35>>^ E, mais uma vez, ela ficou grávida e teve um filho, e disse: “Desta vez, louvarei a Jeová.” Assim, deu-lhe o nome de Judá.^&#42;1^ Depois disso, ela parou de ter filhos.

[NOTE]
====
. Que significa “louvado; objeto de louvor”.
====

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]