include::./index.adoc[]

[[v1-45-0]]
=== Génesis, 45
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-45-1]]

^<<v1-45-1,1>>^ Em vista disso, José já não se conseguiu conter diante de todos os seus servos. Assim, gritou: “Mandem todos sair!” Não estava mais ninguém com José quando ele se revelou aos seus irmãos.

[[v1-45-2]]

^<<v1-45-2,2>>^ E ele começou a chorar tão alto que os egípcios ouviram, e a casa do Faraó ouviu.

[[v1-45-3]]

^<<v1-45-3,3>>^ Finalmente, José disse aos seus irmãos: “Eu sou José. O meu pai ainda está vivo?” Mas os irmãos não lhe conseguiram responder nada, pois ficaram pasmados por causa dele.

[[v1-45-4]]

^<<v1-45-4,4>>^ Então, José disse aos irmãos: “Aproximem-se, por favor.” E aproximaram-se dele.
Ele disse: “Eu sou José, o vosso irmão, que venderam aos egípcios.

[[v1-45-5]]

^<<v1-45-5,5>>^ Mas, agora, não fiquem aflitos nem se censurem uns aos outros por me terem vendido aos egípcios, porque Deus me enviou à vossa frente para preservar vidas.

[[v1-45-6]]

^<<v1-45-6,6>>^ Este é o segundo ano de fome no país, e ainda teremos cinco anos em que não haverá nem lavoura nem colheita.

[[v1-45-7]]

^<<v1-45-7,7>>^ Mas Deus enviou-me à vossa frente, para vos preservar um restante na terra^&#42;1^ e para vos manter vivos através de uma grande libertação.

[NOTE]
====
. Ou: “no país”.
====

[[v1-45-8]]

^<<v1-45-8,8>>^ Assim, não foram vocês que me enviaram para cá, mas foi o verdadeiro Deus, a fim de me designar como principal conselheiro^&#42;1^ do Faraó, senhor de toda a sua casa e governador de toda a terra do Egito.

[NOTE]
====
. Lit.: “como pai”.
====

[[v1-45-9]]

^<<v1-45-9,9>>^ “Voltem depressa ao meu pai e digam-lhe: ‘Assim disse o seu filho José: “Deus designou-me como senhor de todo o Egito. Venha ter comigo. Não se demore.

[[v1-45-10]]

^<<v1-45-10,10>>^ Morará na terra de Gósen, onde estará perto de mim — o senhor, os seus filhos, os seus netos, os seus rebanhos, as suas manadas e tudo o que tem.

[[v1-45-11]]

^<<v1-45-11,11>>^ Ali suprirei as suas necessidades, pois ainda haverá cinco anos de fome. Senão, o senhor, a sua casa e tudo o que tem cairá em pobreza.”’

[[v1-45-12]]

^<<v1-45-12,12>>^ Agora, vocês e o meu irmão Benjamim podem ver, com os vossos próprios olhos, que sou eu mesmo quem está a falar convosco.

[[v1-45-13]]

^<<v1-45-13,13>>^ Assim, contem ao meu pai toda a glória que tenho no Egito e tudo o que viram. Agora, vão depressa e tragam o meu pai para cá.”

[[v1-45-14]]

^<<v1-45-14,14>>^ Então ele abraçou^&#42;1^ Benjamim, o seu irmão, e começou a chorar; e Benjamim chorou abraçado a ele.^&#42;2^

[NOTE]
====
. Lit.: “lançou-se ao pescoço de”.
. Ou: “chorou ao seu pescoço”.
====

[[v1-45-15]]

^<<v1-45-15,15>>^ Ele beijou todos os seus irmãos e chorou abraçado a eles. Depois disso, os seus irmãos falaram com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ A seguinte notícia chegou à casa do Faraó: “Chegaram os irmãos de José!” Isso agradou ao Faraó e aos seus servos.

[[v1-45-17]]

^<<v1-45-17,17>>^ Assim, o Faraó disse a José: “Diz aos teus irmãos: ‘Façam o seguinte: carreguem os vossos animais, vão à terra de Canaã

[[v1-45-18]]

^<<v1-45-18,18>>^ e tragam-me para cá o vosso pai e os das vossas casas. Irei dar-vos as coisas boas da terra do Egito, e comerão^&#42;1^ da parte mais rica^&#42;2^ da terra.’

[NOTE]
====
. Ou: “viverão”.
. Ou: “gorda”.
====

[[v1-45-19]]

^<<v1-45-19,19>>^ Deves dizer-lhes: ‘Façam o seguinte: peguem em carroças da terra do Egito para as vossas crianças e para as vossas esposas, tragam o vosso pai numa delas e venham para cá.

[[v1-45-20]]

^<<v1-45-20,20>>^ Não se preocupem com os vossos pertences, pois o melhor de toda a terra do Egito é vosso.’”

[[v1-45-21]]

^<<v1-45-21,21>>^ Os filhos de Israel assim fizeram, e José deu-lhes carroças segundo as ordens do Faraó e deu-lhes provisões para a viagem.

[[v1-45-22]]

^<<v1-45-22,22>>^ A cada um deles deu uma muda de roupa, mas a Benjamim deu 300 peças de prata e cinco mudas de roupa.

[[v1-45-23]]

^<<v1-45-23,23>>^ E ao pai enviou o seguinte: dez jumentos carregados das coisas boas do Egito e dez jumentas carregadas de cereais, de pão e de outros alimentos para a viagem do pai.

[[v1-45-24]]

^<<v1-45-24,24>>^ Assim, mandou os seus irmãos embora e, ao partirem, disse-lhes: “Não se irritem uns com os outros pelo caminho.”

[[v1-45-25]]

^<<v1-45-25,25>>^ Eles subiram do Egito e chegaram à terra de Canaã, a Jacó, seu pai.

[[v1-45-26]]

^<<v1-45-26,26>>^ Então, informaram-no: “José ainda está vivo, e ele é o governante de toda a terra do Egito!” Mas o coração de Jacó ficou entorpecido, pois não acreditou neles.

[[v1-45-27]]

^<<v1-45-27,27>>^ Quando lhe contaram todas as palavras que José lhes tinha dito, e quando ele viu as carroças que José tinha enviado para o transportar, o espírito de Jacó, seu pai, começou a reanimar-se.

[[v1-45-28]]

^<<v1-45-28,28>>^ Israel exclamou: “Basta! O meu filho José ainda está vivo! Preciso de ir vê-lo antes de morrer!”

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]