include::./index.adoc[]

[[v1-24-0]]
=== Génesis, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-24-1]]

^<<v1-24-1,1>>^ Abraão já era velho, de idade bem avançada, e Jeová tinha abençoado Abraão em tudo.

[[v1-24-2]]

^<<v1-24-2,2>>^ Abraão disse ao seu servo, o mais velho da sua casa, que administrava tudo o que ele possuía: “Por favor, põe a mão debaixo da minha coxa,

[[v1-24-3]]

^<<v1-24-3,3>>^ e irei fazer-te jurar por Jeová, o Deus dos céus e o Deus da terra, que não tomarás para o meu filho uma esposa dentre as filhas dos cananeus, entre os quais estou a morar.

[[v1-24-4]]

^<<v1-24-4,4>>^ Em vez disso, vai à minha terra e toma dentre os meus parentes uma esposa para o meu filho, para Isaque.”

[[v1-24-5]]

^<<v1-24-5,5>>^ No entanto, o servo perguntou-lhe: “E se a mulher não estiver disposta a vir comigo para esta terra? Devo então levar o seu filho à terra de onde o senhor veio?”

[[v1-24-6]]

^<<v1-24-6,6>>^ Abraão respondeu-lhe: “Assegura-te de que não levas o meu filho para lá.

[[v1-24-7]]

^<<v1-24-7,7>>^ Jeová, o Deus dos céus, que me tirou da casa do meu pai e da terra dos meus parentes, e que falou comigo e me jurou: ‘Vou dar esta terra à tua descendência’,^&#42;1^ enviará o seu anjo à tua frente, e certamente tomarás dali uma esposa para o meu filho.

[NOTE]
====
. Lit.: “semente”.
====

[[v1-24-8]]

^<<v1-24-8,8>>^ Se a mulher não estiver disposta a vir contigo, então ficarás livre deste juramento. Mas não leves o meu filho para lá.”

[[v1-24-9]]

^<<v1-24-9,9>>^ Então, o servo pôs a mão debaixo da coxa de Abraão, seu senhor, e jurou-lhe com respeito a esse assunto.

[[v1-24-10]]

^<<v1-24-10,10>>^ Então, o servo pegou em dez camelos do seu senhor e partiu, levando consigo todo o tipo de coisas boas do seu senhor. Viajou para a Mesopotâmia, para a cidade de Naor.

[[v1-24-11]]

^<<v1-24-11,11>>^ Ele fez os camelos ajoelharem-se junto a um poço de água, fora da cidade. Estava a anoitecer, era a hora em que as mulheres vinham para tirar água.

[[v1-24-12]]

^<<v1-24-12,12>>^ Então ele disse: “Jeová, Deus do meu senhor Abraão, por favor, faz com que eu seja bem-sucedido neste dia, e mostra o teu amor leal ao meu senhor Abraão.

[[v1-24-13]]

^<<v1-24-13,13>>^ Estou aqui, de pé junto a uma fonte de água, e as filhas dos homens da cidade vêm para tirar água.

[[v1-24-14]]

^<<v1-24-14,14>>^ Peço-te que a jovem a quem eu disser: ‘Por favor, baixa o teu cântaro de água para que eu beba’, e que responder: ‘Beba, e também darei água aos seus camelos’, seja aquela que escolheste para o teu servo Isaque; e, assim, deixa-me saber que mostraste o teu amor leal ao meu senhor.”

[[v1-24-15]]

^<<v1-24-15,15>>^ Mesmo antes de acabar de falar, Rebeca veio com o seu cântaro ao ombro. Rebeca era filha de Betuel, filho de Milca, que era esposa de Naor, irmão de Abraão.

[[v1-24-16]]

^<<v1-24-16,16>>^ A jovem era muito bonita, era virgem; nenhum homem tivera relações sexuais com ela. Ela desceu até à fonte, encheu o seu cântaro e depois voltou a subir.

[[v1-24-17]]

^<<v1-24-17,17>>^ O servo correu imediatamente até ela e disse: “Por favor, dá-me um gole de água do teu cântaro.”

[[v1-24-18]]

^<<v1-24-18,18>>^ Então ela disse: “Beba, meu senhor.” De seguida, ela baixou depressa o seu cântaro, apoiando-o sobre a mão, e deu-lhe de beber.

[[v1-24-19]]

^<<v1-24-19,19>>^ Depois de lhe dar de beber, ela disse: “Também tirarei água para os seus camelos até que fiquem saciados.”

[[v1-24-20]]

^<<v1-24-20,20>>^ Rapidamente esvaziou o cântaro no bebedouro e correu várias vezes até ao poço para tirar água, e continuou a tirar água para todos os camelos dele.

[[v1-24-21]]

^<<v1-24-21,21>>^ Durante o tempo todo, o homem observava-a admirado e em silêncio, esperando para ver se Jeová tinha tornado a sua viagem bem-sucedida ou não.

[[v1-24-22]]

^<<v1-24-22,22>>^ Quando os camelos acabaram de beber, o homem deu-lhe uma argola de ouro para o nariz, que pesava meio siclo,^&#42;1^ e duas pulseiras de ouro que pesavam 10 siclos,^&#42;2^

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v1-24-23]]

^<<v1-24-23,23>>^ e disse: “Diz-me, por favor, de quem és filha? Há lugar na casa do teu pai para passarmos a noite?”

[[v1-24-24]]

^<<v1-24-24,24>>^ Diante disso, ela disse-lhe: “Sou filha de Betuel, o filho que Milca deu a Naor.”

[[v1-24-25]]

^<<v1-24-25,25>>^ E acrescentou: “Temos tanto palha como muita forragem, e também um lugar para passar a noite.”

[[v1-24-26]]

^<<v1-24-26,26>>^ Então, o homem curvou-se e prostrou-se diante de Jeová,

[[v1-24-27]]

^<<v1-24-27,27>>^ e disse: “Louvado seja Jeová, o Deus do meu senhor Abraão, pois não abandonou o seu amor leal e a sua fidelidade para com o meu senhor. Jeová guiou-me à casa dos irmãos do meu senhor.”

[[v1-24-28]]

^<<v1-24-28,28>>^ E a jovem foi a correr contar estas coisas aos da casa da sua mãe.

[[v1-24-29]]

^<<v1-24-29,29>>^ Rebeca tinha um irmão que se chamava Labão. E Labão correu até ao homem que estava junto à fonte.

[[v1-24-30]]

^<<v1-24-30,30>>^ Quando viu a argola para o nariz e as pulseiras que a sua irmã estava a usar e ouviu as palavras de Rebeca, sua irmã, que dizia: “Foi assim que o homem me disse”; então, Labão foi ter com o homem, que ainda estava parado ao lado dos camelos, junto à fonte.

[[v1-24-31]]

^<<v1-24-31,31>>^ Labão disse imediatamente: “Vem, tu que és abençoado por Jeová. Porque é que continuas parado aqui fora? Preparei a casa e também um lugar para os camelos.”

[[v1-24-32]]

^<<v1-24-32,32>>^ Então, o homem entrou na casa, e ele^&#42;1^ tirou os arreios dos camelos, deu palha e forragem aos camelos e água para lavar os pés do homem e dos que estavam com ele.

[NOTE]
====
. Provavelmente, refere-se a Labão.
====

[[v1-24-33]]

^<<v1-24-33,33>>^ No entanto, quando lhe deram algo para comer, ele disse: “Não comerei até ter dito o que tenho para dizer.” Portanto, Labão disse: “Fala!”

[[v1-24-34]]

^<<v1-24-34,34>>^ Então ele disse: “Sou servo de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ E Jeová tem abençoado muitíssimo o meu senhor e fê-lo ficar muito rico, pois deu-lhe ovelhas e bois, prata e ouro, servos e servas, camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ Além disso, Sara, esposa do meu senhor, deu um filho ao meu senhor depois de ter ficado idosa, e ele irá dar-lhe tudo o que possui.

[[v1-24-37]]

^<<v1-24-37,37>>^ E o meu senhor fez-me jurar, dizendo: ‘Não tomes para o meu filho uma esposa dentre as filhas dos cananeus, em cuja terra estou a morar.

[[v1-24-38]]

^<<v1-24-38,38>>^ Em vez disso, irás à casa do meu pai e da minha família, e tomarás uma esposa para o meu filho.’

[[v1-24-39]]

^<<v1-24-39,39>>^ Mas eu perguntei ao meu senhor: ‘E se a mulher não estiver disposta a vir comigo?’

[[v1-24-40]]

^<<v1-24-40,40>>^ Ele disse-me: ‘Jeová, diante de quem tenho andado, enviará contigo o seu anjo e certamente tornará a tua viagem bem-sucedida. Toma para o meu filho uma esposa dentre a minha família e dentre a casa do meu pai.

[[v1-24-41]]

^<<v1-24-41,41>>^ Ficarás livre do juramento que me fizeste se fores à minha família e eles não ta derem. Assim, ficarás livre do teu juramento.’

[[v1-24-42]]

^<<v1-24-42,42>>^ “Quando cheguei hoje à fonte, disse: ‘Jeová, Deus do meu senhor Abraão, se for da tua vontade que a minha viagem seja bem-sucedida,

[[v1-24-43]]

^<<v1-24-43,43>>^ aqui estou, de pé junto à fonte. Isto é o que tem de acontecer: quando uma jovem vier para tirar água, direi: “Por favor, deixa-me beber um pouco de água do teu cântaro”,

[[v1-24-44]]

^<<v1-24-44,44>>^ e ela irá responder-me: “Beba, e também tirarei água para os seus camelos.” Que essa mulher seja aquela que Jeová escolheu para o filho do meu senhor.’

[[v1-24-45]]

^<<v1-24-45,45>>^ “Antes de acabar de falar no meu íntimo, Rebeca vinha com o seu cântaro ao ombro; ela desceu até à fonte e começou a tirar água. Então, eu disse-lhe: ‘Por favor, dá-me de beber.’

[[v1-24-46]]

^<<v1-24-46,46>>^ E ela rapidamente baixou do ombro o seu cântaro e disse: ‘Beba, e também darei água aos seus camelos.’ Então bebi, e ela também deu água aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ Depois perguntei-lhe: ‘De quem és filha?’ E ela respondeu: ‘Filha de Betuel, o filho que Milca deu a Naor.’ Assim, coloquei a argola na sua narina e as pulseiras nos seus braços.^&#42;1^

[NOTE]
====
. Ou: “nas suas mãos”.
====

[[v1-24-48]]

^<<v1-24-48,48>>^ E curvei-me e prostrei-me perante Jeová e louvei a Jeová, o Deus do meu senhor Abraão, que me tinha guiado no caminho certo, a fim de tomar a filha do irmão do meu senhor para o seu filho.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora, digam-me se desejam mostrar amor leal e fidelidade ao meu senhor; senão, digam-mo também, para que eu saiba que caminho tomar.”^&#42;1^

[NOTE]
====
. Lit.: “eu vire para a mão direita ou para a esquerda”.
====

[[v1-24-50]]

^<<v1-24-50,50>>^ Labão e Betuel responderam então: “Isto vem de Jeová. Não te podemos dizer nem que sim nem que não.^&#42;1^

[NOTE]
====
. Ou: “Não te podemos falar mal nem bem.”
====

[[v1-24-51]]

^<<v1-24-51,51>>^ Aqui está Rebeca diante de ti. Toma-a e vai, e que ela se torne esposa do filho do teu senhor, assim como Jeová disse.”

[[v1-24-52]]

^<<v1-24-52,52>>^ Quando o servo de Abraão ouviu as suas palavras, prostrou-se imediatamente por terra diante de Jeová.

[[v1-24-53]]

^<<v1-24-53,53>>^ E o servo começou a tirar objetos de prata e de ouro e roupas, e deu-os a Rebeca; e deu coisas valiosas ao irmão e à mãe dela.

[[v1-24-54]]

^<<v1-24-54,54>>^ Depois disto, ele e os homens que estavam com ele comeram e beberam, e passaram ali a noite.
Quando ele se levantou de manhã, disse: “Deixem-me voltar para o meu senhor.”

[[v1-24-55]]

^<<v1-24-55,55>>^ Perante isto, o irmão e a mãe dela disseram: “Deixa a jovem ficar connosco pelo menos dez dias. Depois ela pode ir.”

[[v1-24-56]]

^<<v1-24-56,56>>^ Mas ele disse-lhes: “Não me detenham, visto que Jeová tornou a minha viagem bem-sucedida. Deixem-me partir, para que eu vá ter com o meu senhor.”

[[v1-24-57]]

^<<v1-24-57,57>>^ Disseram então: “Chamemos a jovem e perguntemos-lhe.”

[[v1-24-58]]

^<<v1-24-58,58>>^ Chamaram Rebeca e perguntaram-lhe: “Irás com este homem?” Ela respondeu: “Estou disposta a ir.”

[[v1-24-59]]

^<<v1-24-59,59>>^ Assim, deixaram a sua irmã Rebeca partir com a ama,^&#42;1^ o servo de Abraão e os seus homens.

[NOTE]
====
. Isto é, com a sua ama que agora servia como criada.
====

[[v1-24-60]]

^<<v1-24-60,60>>^ E abençoaram Rebeca e disseram-lhe: “Que tu, nossa irmã, te tornes milhares de vezes 10 000,^&#42;1^ e que os teus descendentes tomem^&#42;2^ posse do portão^&#42;3^ dos que os odeiam.”

[NOTE]
====
. Ou: “te tornes a mãe de milhares de miríades”.
. Lit.: “a tua semente tome”.
. Ou: “das cidades”.
====

[[v1-24-61]]

^<<v1-24-61,61>>^ Então, Rebeca e as suas criadas prepararam-se, montaram nos camelos e seguiram o homem. Assim, o servo partiu, levando Rebeca.

[[v1-24-62]]

^<<v1-24-62,62>>^ Ora, Isaque tinha vindo da direção de Beer-Laai-Roi, pois morava na terra do Neguebe.

[[v1-24-63]]

^<<v1-24-63,63>>^ Isaque tinha saído para passear no campo, por volta do anoitecer, para meditar. Quando levantou os olhos, viu que chegavam camelos.

[[v1-24-64]]

^<<v1-24-64,64>>^ E, quando Rebeca levantou os olhos, viu Isaque e desceu rapidamente do camelo.

[[v1-24-65]]

^<<v1-24-65,65>>^ Ela perguntou então ao servo: “Quem é aquele homem que vem ao nosso encontro pelo campo?” E o servo respondeu: “É o meu senhor.” Então ela pegou no seu véu para se cobrir.

[[v1-24-66]]

^<<v1-24-66,66>>^ E o servo contou a Isaque tudo o que tinha feito.

[[v1-24-67]]

^<<v1-24-67,67>>^ Depois disso, Isaque levou-a para a tenda de Sara, sua mãe. Tomou assim Rebeca como esposa; e Isaque apaixonou-se por ela e encontrou consolo depois da perda da mãe.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]