include::./index.adoc[]

[[v1-14-0]]
=== Génesis, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-14-1]]

^<<v1-14-1,1>>^ Naqueles dias, Anrafel era rei de Sinear, Arioque era rei de Elasar, Quedorlaomer era rei de Elão, e Tidal era rei de Goim;

[[v1-14-2]]

^<<v1-14-2,2>>^ estes reis guerrearam contra Bera, rei de Sodoma, Birsa, rei de Gomorra, Sinabe, rei de Admá, Semeber, rei de Zeboim, e o rei de Bela, isto é, Zoar.

[[v1-14-3]]

^<<v1-14-3,3>>^ Todos estes juntaram forças no vale^&#42;1^ de Sidim, isto é, o mar Salgado.^&#42;2^

[NOTE]
====
. Ou: “na planície”.
. Isto é, o mar Morto.
====

[[v1-14-4]]

^<<v1-14-4,4>>^ Eles tinham servido Quedorlaomer durante 12 anos, mas rebelaram-se no décimo terceiro ano.

[[v1-14-5]]

^<<v1-14-5,5>>^ Então, no décimo quarto ano, Quedorlaomer veio com os reis, seus aliados, e derrotaram os refains em Asterote-Carnaim, os zuzins em Hã, os emins em Savé-Quiriataim

[[v1-14-6]]

^<<v1-14-6,6>>^ e os horeus na sua montanha de Seir até El-Parã, situado junto ao deserto.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v1-14-7]]

^<<v1-14-7,7>>^ Depois voltaram e chegaram a En-Mispate, isto é, Cades, e conquistaram todo o território dos amalequitas e também derrotaram os amorreus que moravam em Hazazom-Tamar.

[[v1-14-8]]

^<<v1-14-8,8>>^ Nessa altura, o rei de Sodoma pôs-se em marcha, bem como o rei de Gomorra, o rei de Admá, o rei de Zeboim e o rei de Bela, isto é, Zoar, e puseram-se em formação de batalha contra eles no vale^&#42;1^ de Sidim,

[NOTE]
====
. Ou: “na planície”.
====

[[v1-14-9]]

^<<v1-14-9,9>>^ contra Quedorlaomer, rei de Elão, Tidal, rei de Goim, Anrafel, rei de Sinear, e contra Arioque, rei de Elasar — quatro reis contra os cinco.

[[v1-14-10]]

^<<v1-14-10,10>>^ No vale^&#42;1^ de Sidim havia muitos poços de betume; os reis de Sodoma e Gomorra tentaram escapar e caíram neles, e os que restaram fugiram para a região montanhosa.

[NOTE]
====
. Ou: “Na planície”.
====

[[v1-14-11]]

^<<v1-14-11,11>>^ Então, os vencedores tomaram todos os bens de Sodoma e Gomorra, e todos os seus mantimentos, e seguiram caminho.

[[v1-14-12]]

^<<v1-14-12,12>>^ Também levaram Ló, sobrinho de Abrão que morava em Sodoma, e os seus bens, e seguiram caminho.

[[v1-14-13]]

^<<v1-14-13,13>>^ Depois, um homem que tinha escapado foi contar isso a Abrão, o hebreu. Naquela época, ele morava^&#42;1^ entre as árvores grandes de Manre, o amorreu, irmão de Escol e de Aner. Estes homens eram aliados de Abrão.

[NOTE]
====
. Ou: “morava em tendas”.
====

[[v1-14-14]]

^<<v1-14-14,14>>^ Assim, Abrão ouviu que o seu parente^&#42;1^ tinha sido levado cativo. Em vista disso, mobilizou os seus homens treinados, 318 servos nascidos na sua casa, e perseguiu os inimigos até Dã.

[NOTE]
====
. Lit.: “irmão”.
====

[[v1-14-15]]

^<<v1-14-15,15>>^ Durante a noite, dividiu as forças, e ele e os seus servos atacaram-nos e derrotaram-nos. Ele perseguiu-os até Hobá, que fica a norte de Damasco.

[[v1-14-16]]

^<<v1-14-16,16>>^ Recuperou todos os bens e também resgatou Ló, seu parente, os seus bens, as mulheres e as outras pessoas.

[[v1-14-17]]

^<<v1-14-17,17>>^ Depois de Abrão voltar da vitória sobre Quedorlaomer e os reis que estavam com ele, o rei de Sodoma foi ter com Abrão no vale^&#42;1^ de Savé, isto é, o vale do Rei.

[NOTE]
====
. Ou: “na planície”.
====

[[v1-14-18]]

^<<v1-14-18,18>>^ E Melquisedeque, rei de Salém, trouxe pão e vinho. Ele era sacerdote do Deus Altíssimo.

[[v1-14-19]]

^<<v1-14-19,19>>^ Abençoou-o então e disse:
“Bendito seja Abrão pelo Deus Altíssimo,
Aquele que fez o céu e a terra;

[[v1-14-20]]

^<<v1-14-20,20>>^ E louvado seja o Deus Altíssimo,
Que lhe entregou os seus opressores!”
E Abrão deu-lhe um décimo de tudo.

[[v1-14-21]]

^<<v1-14-21,21>>^ Depois disso, o rei de Sodoma disse a Abrão: “Dá-me as pessoas,^&#42;1^ mas fica com os bens para ti.”

[NOTE]
====
. Ou: “almas”.
====

[[v1-14-22]]

^<<v1-14-22,22>>^ Mas Abrão disse ao rei de Sodoma: “Ergo a minha mão em juramento a Jeová, o Deus Altíssimo, aquele que fez o céu e a terra,

[[v1-14-23]]

^<<v1-14-23,23>>^ de que não ficarei com nada do que é seu, desde um pedaço de linha até um cordão de sandália, para que não diga: ‘Eu enriqueci Abrão.’

[[v1-14-24]]

^<<v1-14-24,24>>^ Não ficarei com nada além do que os jovens já comeram. Quanto à parte que pertence aos homens que foram comigo — Aner, Escol e Manre —, que eles fiquem com a parte deles.”

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]