include::./index.adoc[]

[[v1-39-0]]
=== Génesis, 39
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-39-1]]

^<<v1-39-1,1>>^ José foi levado para baixo, para o Egito, e um egípcio chamado Potifar, que era um oficial da corte do Faraó e chefe da guarda, comprou-o aos ismaelitas que o tinham levado para lá.

[[v1-39-2]]

^<<v1-39-2,2>>^ Mas Jeová estava com José, e, em resultado disso, ele tornou-se um homem bem-sucedido e ficou responsável pela casa do seu senhor, o egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ E o seu senhor viu que Jeová estava com ele e que Jeová tornava bem-sucedido tudo o que ele fazia.

[[v1-39-4]]

^<<v1-39-4,4>>^ José achava favor aos seus olhos e tornou-se o seu servo pessoal. Assim, Potifar encarregou-o da sua casa, e deu-lhe responsabilidade sobre tudo o que era seu.

[[v1-39-5]]

^<<v1-39-5,5>>^ A partir do momento em que o egípcio o encarregou da sua casa e de tudo o que era seu, Jeová abençoou a casa do egípcio por causa de José, e a bênção de Jeová estava sobre tudo o que ele tinha em casa e no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ Por fim, Potifar deixou tudo o que era seu aos cuidados de José, e não se preocupava com nada, a não ser com o que comia. Além disso, José tornou-se bonito e de belo porte.

[[v1-39-7]]

^<<v1-39-7,7>>^ Algum tempo depois, a esposa do seu senhor começou a reparar em José e a dizer: “Deita-te comigo.”

[[v1-39-8]]

^<<v1-39-8,8>>^ Mas ele recusava-se e dizia à esposa do seu senhor: “O meu senhor nem sabe o que há comigo na casa, e tudo o que ele tem entregou ao meu cuidado.

[[v1-39-9]]

^<<v1-39-9,9>>^ Não há ninguém maior do que eu nesta casa, e ele não me negou absolutamente nada, a não ser a si, porque é sua esposa. Portanto, como poderia eu cometer esta grande maldade e realmente pecar contra Deus?”

[[v1-39-10]]

^<<v1-39-10,10>>^ Assim, dia após dia, ela falava com José, mas ele nunca concordou em se deitar com ela nem em estar com ela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Mas, certo dia, quando ele entrou em casa para fazer o seu trabalho, nenhum dos servos da casa estava lá.

[[v1-39-12]]

^<<v1-39-12,12>>^ Então, ela agarrou-o pela roupa e disse: “Deita-te comigo!” Mas ele deixou a roupa nas mãos dela e fugiu para fora.

[[v1-39-13]]

^<<v1-39-13,13>>^ Quando ela viu que ele tinha deixado a roupa nas mãos dela e que tinha fugido,

[[v1-39-14]]

^<<v1-39-14,14>>^ começou a gritar, chamando os homens da sua casa. Dizia-lhes: “Vejam! Este hebreu, que o meu marido nos trouxe, quer fazer de nós motivo de riso. Ele veio procurar-me para se deitar comigo, mas eu comecei a gritar o mais alto que consegui.

[[v1-39-15]]

^<<v1-39-15,15>>^ E, assim que ele me ouviu gritar, deixou a sua roupa ao meu lado e fugiu.”

[[v1-39-16]]

^<<v1-39-16,16>>^ Depois disso, ela deixou a roupa dele ao seu lado até que o seu senhor chegasse a casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Então, ela disse-lhe a mesma coisa: “O servo hebreu que nos trouxeste veio procurar-me para fazer de mim motivo de riso.

[[v1-39-18]]

^<<v1-39-18,18>>^ Mas, assim que comecei a gritar, ele deixou a roupa ao meu lado e fugiu.”

[[v1-39-19]]

^<<v1-39-19,19>>^ Quando o seu senhor ouviu as palavras da esposa: “Foi isto que o teu servo me fez”, ficou furioso.

[[v1-39-20]]

^<<v1-39-20,20>>^ Então, o senhor de José agarrou-o e mandou-o para a prisão, o lugar onde ficavam detidos os prisioneiros do rei, e ele continuou ali na prisão.

[[v1-39-21]]

^<<v1-39-21,21>>^ Mas Jeová continuava com José e demonstrava-lhe amor leal, e concedia-lhe favor aos olhos do carcereiro-chefe.

[[v1-39-22]]

^<<v1-39-22,22>>^ Assim, o carcereiro-chefe encarregou José de todos os prisioneiros que estavam na prisão, e era ele quem administrava tudo o que se fazia ali.

[[v1-39-23]]

^<<v1-39-23,23>>^ O carcereiro-chefe não se preocupava com absolutamente nada do que estava aos cuidados de José, pois Jeová estava com José, e Jeová tornava bem-sucedido tudo o que ele fazia.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]