include::./index.adoc[]

[[v1-42-0]]
=== Génesis, 42
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-42-1]]

^<<v1-42-1,1>>^ Quando Jacó soube que havia cereais no Egito, disse aos seus filhos: “Porque é que estão parados a olhar uns para os outros?”

[[v1-42-2]]

^<<v1-42-2,2>>^ E acrescentou: “Soube que há cereais no Egito. Desçam até lá e comprem cereais para nós, para que fiquemos vivos e não morramos de fome.”

[[v1-42-3]]

^<<v1-42-3,3>>^ Assim, dez dos irmãos de José desceram até ao Egito para comprar cereais.

[[v1-42-4]]

^<<v1-42-4,4>>^ Mas Jacó não enviou Benjamim, irmão de José, com os outros irmãos, pois disse: “Poderia acontecer-lhe um acidente fatal.”

[[v1-42-5]]

^<<v1-42-5,5>>^ Os filhos de Israel foram com os outros que iam comprar mantimentos, porque a fome tinha chegado à terra de Canaã.

[[v1-42-6]]

^<<v1-42-6,6>>^ José era a autoridade sobre o país, e era ele quem vendia os cereais a todo o povo da terra. Por isso, os irmãos de José chegaram e curvaram-se diante dele com o rosto por terra.

[[v1-42-7]]

^<<v1-42-7,7>>^ Quando José viu os seus irmãos, reconheceu-os imediatamente, mas escondeu-lhes a sua identidade. Então, perguntou-lhes rispidamente: “De onde vêm?” Eles responderam: “Da terra de Canaã, para comprar alimentos.”

[[v1-42-8]]

^<<v1-42-8,8>>^ Assim, José reconheceu os seus irmãos, mas eles não o reconheceram.

[[v1-42-9]]

^<<v1-42-9,9>>^ José lembrou-se imediatamente dos sonhos que tivera a respeito deles, e disse-lhes: “Vocês são espiões! Vieram para ver os pontos fracos^&#42;1^ do país!”

[NOTE]
====
. Ou: “a condição debilitada”.
====

[[v1-42-10]]

^<<v1-42-10,10>>^ Disseram-lhe então: “Não, meu senhor, os seus servos vieram para comprar alimentos.

[[v1-42-11]]

^<<v1-42-11,11>>^ Todos nós somos filhos de um único homem. Somos homens honestos. Os seus servos não são espiões.”

[[v1-42-12]]

^<<v1-42-12,12>>^ Mas ele disse-lhes: “Não é verdade! Vocês vieram para ver os pontos fracos do país!”

[[v1-42-13]]

^<<v1-42-13,13>>^ Diante disso, disseram: “Os seus servos são 12 irmãos. Somos filhos de um único homem na terra de Canaã; o mais novo está agora com o nosso pai; quanto ao outro, já não existe.”

[[v1-42-14]]

^<<v1-42-14,14>>^ No entanto, José disse-lhes: “É como eu vos disse: ‘Vocês são espiões!’

[[v1-42-15]]

^<<v1-42-15,15>>^ Serão postos à prova pelo seguinte: tão certo como o Faraó vive, não sairão deste lugar até que o vosso irmão mais novo venha aqui.

[[v1-42-16]]

^<<v1-42-16,16>>^ Mandem um de vocês buscar o vosso irmão enquanto os outros ficam presos. Assim, as vossas palavras serão postas à prova, e saberei se dizem a verdade. Caso contrário, então, tão certo como o Faraó vive, vocês são espiões.”

[[v1-42-17]]

^<<v1-42-17,17>>^ Com isso, colocou-os juntos em detenção durante três dias.

[[v1-42-18]]

^<<v1-42-18,18>>^ No terceiro dia, José disse-lhes: “Façam o seguinte e ficarão vivos, pois eu temo a Deus.

[[v1-42-19]]

^<<v1-42-19,19>>^ Se são homens honestos, que um dos vossos irmãos fique preso nesta casa de detenção; mas os outros podem ir e levar os cereais para matar a fome às vossas famílias.

[[v1-42-20]]

^<<v1-42-20,20>>^ Então, tragam-me o vosso irmão mais novo, para que se prove que as vossas palavras são verdadeiras e não morram.” E eles concordaram em fazer assim.

[[v1-42-21]]

^<<v1-42-21,21>>^ E disseram uns aos outros: “Sem dúvida, estamos a ser punidos por causa do que fizemos ao nosso irmão, porque vimos a sua aflição^&#42;1^ quando nos implorou que tivéssemos compaixão, mas não o escutámos. Foi por isso que nos sobreveio esta aflição.”

[NOTE]
====
. Ou: “a aflição da sua alma”.
====

[[v1-42-22]]

^<<v1-42-22,22>>^ Rúben disse-lhes então: “Eu não vos disse: ‘Não pequem contra o menino’? Mas não me escutaram. Agora, certamente, está a ser exigida uma prestação de contas pelo seu sangue.”

[[v1-42-23]]

^<<v1-42-23,23>>^ Mas eles não sabiam que José estava a perceber, pois falava-lhes por meio de um intérprete.

[[v1-42-24]]

^<<v1-42-24,24>>^ Assim, afastou-se deles e começou a chorar. Quando voltou e falou novamente com eles, escolheu Simeão e amarrou-o diante dos seus olhos.

[[v1-42-25]]

^<<v1-42-25,25>>^ José deu então ordem para que enchessem as suas sacas^&#42;1^ de cereais, devolvessem o dinheiro dos homens à saca de cada um e lhes dessem provisões para a viagem. E isso foi feito.

[NOTE]
====
. Ou: “os seus recipientes”.
====

[[v1-42-26]]

^<<v1-42-26,26>>^ Então, carregaram os seus jumentos com os cereais e partiram.

[[v1-42-27]]

^<<v1-42-27,27>>^ Quando um deles abriu a sua saca para dar forragem ao seu jumento no lugar onde iam pernoitar, viu que o seu dinheiro estava na boca da saca.

[[v1-42-28]]

^<<v1-42-28,28>>^ Nisto, ele disse aos seus irmãos: “O meu dinheiro foi devolvido e está aqui na minha saca!” Então, desfaleceu-lhes o coração e, a tremer, olharam uns para os outros e disseram: “O que é isto que Deus nos fez?”

[[v1-42-29]]

^<<v1-42-29,29>>^ Quando chegaram à terra de Canaã, contaram a Jacó, seu pai, tudo o que lhes tinha acontecido, dizendo:

[[v1-42-30]]

^<<v1-42-30,30>>^ “O homem que é o senhor do país falou rispidamente connosco e acusou-nos de estarmos a espiar o país.

[[v1-42-31]]

^<<v1-42-31,31>>^ Mas nós dissemos-lhe: ‘Somos homens honestos. Não somos espiões.

[[v1-42-32]]

^<<v1-42-32,32>>^ Somos 12 irmãos, filhos do mesmo pai. Um já não existe, e o mais novo está agora com o nosso pai na terra de Canaã.’

[[v1-42-33]]

^<<v1-42-33,33>>^ Mas o homem que é o senhor do país disse-nos: ‘Por meio disto saberei se são homens honestos: deixem comigo um dos vossos irmãos. Então, peguem na comida para matar a fome às vossas famílias e vão.

[[v1-42-34]]

^<<v1-42-34,34>>^ E tragam-me o vosso irmão mais novo, para que eu saiba que não são espiões, mas homens honestos. Vou devolver-vos, então, o vosso irmão, e poderão fazer negócios no país.’”

[[v1-42-35]]

^<<v1-42-35,35>>^ Ao esvaziarem as sacas, a bolsa do dinheiro de cada um estava na sua saca. Quando eles e o pai viram as bolsas do dinheiro, ficaram com medo.

[[v1-42-36]]

^<<v1-42-36,36>>^ Jacó, seu pai, exclamou: “Foi a mim que vocês deixaram sem filhos! José já não existe, e Simeão já não existe, e agora vão levar Benjamim! Eu é que tenho de suportar isto tudo!”

[[v1-42-37]]

^<<v1-42-37,37>>^ Mas Rúben disse ao pai: “Pode matar os meus dois filhos se não lho trouxer de volta. Entregue-o aos meus cuidados, e eu vou devolvê-lo a si.”

[[v1-42-38]]

^<<v1-42-38,38>>^ No entanto, ele disse: “O meu filho não irá convosco, porque o irmão dele está morto, e só me resta ele. Se lhe acontecesse um acidente fatal na viagem, vocês certamente fariam os meus cabelos brancos descer com pesar à Sepultura.”^&#42;1^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]