include::./index.adoc[]

[[v1-44-0]]
=== Génesis, 44
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-44-1]]

^<<v1-44-1,1>>^ Mais tarde, ele ordenou ao homem que era encarregado da sua casa: “Enche as sacas dos homens com alimentos, tanto quanto puderem transportar, e coloca o dinheiro de cada um na boca da sua saca.

[[v1-44-2]]

^<<v1-44-2,2>>^ Mas coloca o meu cálice, o cálice de prata, na boca da saca do mais novo, assim como o dinheiro pelos cereais.” Assim, ele fez o que José ordenara.

[[v1-44-3]]

^<<v1-44-3,3>>^ De manhã, ao clarear, deixaram partir os homens com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Ainda não estavam longe da cidade quando José disse ao encarregado da sua casa: “Depressa! Corre atrás dos homens! Quando os alcançares, diz-lhes: ‘Porque é que pagaram o bem com o mal?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é este o cálice que o meu senhor usa para beber e para interpretar os presságios^&#42;1^ com exatidão? O que fizeram foi muito mau.’”

[NOTE]
====
. Ou: “sinais”.
====

[[v1-44-6]]

^<<v1-44-6,6>>^ Assim, alcançou-os e disse-lhes estas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ Mas eles disseram-lhe: “Porque é que o meu senhor diz isso? Longe dos seus servos fazerem uma coisa destas!

[[v1-44-8]]

^<<v1-44-8,8>>^ Ora, trouxemos-lhe de volta, da terra de Canaã, o dinheiro que encontrámos na boca das nossas sacas. Como poderíamos, então, furtar prata ou ouro da casa do seu senhor?

[[v1-44-9]]

^<<v1-44-9,9>>^ Se o cálice for encontrado com um dos seus escravos, que ele morra, e também nos tornaremos escravos do seu^&#42;1^ senhor.”

[NOTE]
====
. Lit.: “meu”.
====

[[v1-44-10]]

^<<v1-44-10,10>>^ Por conseguinte, ele disse: “Seja como vocês dizem: aquele com quem o cálice for encontrado tornar-se-á meu escravo, mas os outros serão considerados inocentes.”

[[v1-44-11]]

^<<v1-44-11,11>>^ Com isso, cada um deles pôs rapidamente a sua saca no chão e abriu-a.

[[v1-44-12]]

^<<v1-44-12,12>>^ Ele procurou cuidadosamente, começando com o mais velho e terminando com o mais novo. Por fim, o cálice foi encontrado na saca de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Então, rasgaram as suas roupas, e cada um voltou a pôr a sua carga no seu jumento, e voltaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ Quando Judá e os seus irmãos entraram na casa de José, ele ainda ali estava, e eles prostraram-se por terra diante dele.

[[v1-44-15]]

^<<v1-44-15,15>>^ José disse-lhes: “O que é que fizeram? Não sabiam que um homem como eu pode interpretar os presságios^&#42;1^ com exatidão?”

[NOTE]
====
. Ou: “sinais”.
====

[[v1-44-16]]

^<<v1-44-16,16>>^ Diante disso, Judá respondeu: “O que é que podemos dizer ao meu senhor? Como é que falaremos? E como é que podemos provar que somos justos? O verdadeiro Deus descobriu o erro dos seus escravos. Agora, somos escravos do meu senhor, tanto nós como aquele com quem o cálice foi encontrado!”

[[v1-44-17]]

^<<v1-44-17,17>>^ No entanto, ele disse: “Longe de mim fazer isso! O homem com quem o cálice foi encontrado tornar-se-á meu escravo. Quanto a vocês, vão em paz para o vosso pai.”

[[v1-44-18]]

^<<v1-44-18,18>>^ Então, Judá aproximou-se dele e disse: “Imploro-lhe, meu senhor, por favor, deixe o seu escravo falar ao meu senhor, e não fique zangado com o seu escravo, pois o senhor é como o próprio Faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ O meu senhor perguntou aos seus escravos: ‘Vocês têm pai ou mais algum irmão?’

[[v1-44-20]]

^<<v1-44-20,20>>^ Por isso, dissemos ao meu senhor: ‘Temos um pai idoso e um irmão mais novo, nascido na sua velhice. Mas o irmão dele está morto, e ele é o único que resta dos filhos da sua mãe, e o seu pai ama-o muito.’

[[v1-44-21]]

^<<v1-44-21,21>>^ Depois, o senhor disse aos seus escravos: ‘Tragam-no até mim, para que eu o veja.’

[[v1-44-22]]

^<<v1-44-22,22>>^ Mas dissemos ao meu senhor: ‘O rapaz não pode deixar o seu pai. Se o deixasse, o seu pai certamente morreria.’

[[v1-44-23]]

^<<v1-44-23,23>>^ Então, o senhor disse aos seus escravos: ‘A menos que o vosso irmão mais novo venha convosco, não poderão voltar à minha presença.’^&#42;1^

[NOTE]
====
. Lit.: “não verão mais a minha face”.
====

[[v1-44-24]]

^<<v1-44-24,24>>^ “Fomos então ao seu escravo, o meu pai, e contámos-lhe as palavras do meu senhor.

[[v1-44-25]]

^<<v1-44-25,25>>^ Mais tarde, o nosso pai disse: ‘Voltem e comprem-nos alguns alimentos.’

[[v1-44-26]]

^<<v1-44-26,26>>^ Mas nós dissemos: ‘Não podemos voltar. Se o nosso irmão mais novo for connosco, voltaremos, porque não podemos voltar à presença^&#42;1^ do homem a menos que o nosso irmão mais novo esteja connosco.’

[NOTE]
====
. Lit.: “ver a face”.
====

[[v1-44-27]]

^<<v1-44-27,27>>^ Então, o seu escravo, o meu pai, disse-nos: ‘Vocês sabem muito bem que a minha esposa só me deu dois filhos.

[[v1-44-28]]

^<<v1-44-28,28>>^ Mas um deles deixou-me, e eu disse: “Certamente, deve ter sido dilacerado!” E, desde então, nunca mais o vi.

[[v1-44-29]]

^<<v1-44-29,29>>^ Se vocês também levassem este para longe da minha vista e lhe acontecesse um acidente fatal, certamente fariam os meus cabelos brancos descer com aflição à Sepultura.’^&#42;1^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v1-44-30]]

^<<v1-44-30,30>>^ “Agora, se eu voltar ao seu escravo, o meu pai, sem que o rapaz esteja connosco — este rapaz a quem ele é tão apegado^&#42;1^ —,

[NOTE]
====
. Ou: “a sua alma está amarrada à alma dele”.
====

[[v1-44-31]]

^<<v1-44-31,31>>^ assim que ele vir que o rapaz não está connosco, ele morrerá, e os seus escravos realmente farão os cabelos brancos do seu escravo, o nosso pai, descer com pesar à Sepultura.^&#42;1^

[NOTE]
====
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v1-44-32]]

^<<v1-44-32,32>>^ Este seu escravo deu ao meu pai uma garantia pelo rapaz, dizendo: ‘Se eu falhar em trazê-lo de volta, carregarei esse pecado diante de si para sempre.’

[[v1-44-33]]

^<<v1-44-33,33>>^ Portanto, agora, por favor, deixe o seu escravo ficar em lugar do rapaz, como escravo do meu senhor, para que o rapaz possa voltar com os seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Como poderia eu voltar ao meu pai sem que o rapaz estivesse comigo? Não suportaria ver o meu pai ser atingido por tal desgraça!”

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]