include::./index.adoc[]

[[v1-32-0]]
=== Génesis, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v1-32-1]]

^<<v1-32-1,1>>^ Jacó prosseguiu o seu caminho, e os anjos de Deus encontraram-se com ele.

[[v1-32-2]]

^<<v1-32-2,2>>^ Assim que os viu, Jacó exclamou: “Este é o acampamento de Deus!” Por isso, deu àquele lugar o nome de Maanaim.^&#42;1^

[NOTE]
====
. Que significa “dois acampamentos”.
====

[[v1-32-3]]

^<<v1-32-3,3>>^ Então, Jacó enviou mensageiros à sua frente, a Esaú, seu irmão, à terra de Seir, o território^&#42;1^ de Edom,

[NOTE]
====
. Lit.: “campo”.
====

[[v1-32-4]]

^<<v1-32-4,4>>^ e ordenou-lhes: “Dirão o seguinte ao meu senhor Esaú: ‘Assim diz o teu servo Jacó: “Morei^&#42;1^ com Labão por muito tempo, até agora.

[NOTE]
====
. Ou: “Morei como estrangeiro”.
====

[[v1-32-5]]

^<<v1-32-5,5>>^ E adquiri touros, jumentos, ovelhas, servos e servas, e estou a mandar esta mensagem para informar o meu senhor, a fim de achar favor aos seus olhos.”’”

[[v1-32-6]]

^<<v1-32-6,6>>^ Após algum tempo, os mensageiros voltaram a Jacó, dizendo: “Estivemos com o teu irmão Esaú; ele está a vir ao teu encontro, e há 400 homens com ele.”

[[v1-32-7]]

^<<v1-32-7,7>>^ Jacó ficou muito aflito e apavorado. Por isso, dividiu o povo que estava com ele em dois grupos, bem como as ovelhas, os bois e os camelos.

[[v1-32-8]]

^<<v1-32-8,8>>^ Ele disse: “Se Esaú atacar um grupo, o outro grupo poderá escapar.”

[[v1-32-9]]

^<<v1-32-9,9>>^ Depois disso, Jacó disse: “Ó Deus do meu pai Abraão e Deus do meu pai Isaque, ó Jeová, tu que me dizes: ‘Volta à tua terra e aos teus parentes, e eu vou tratar-te bem’,

[[v1-32-10]]

^<<v1-32-10,10>>^ não mereço todo o amor leal e toda a fidelidade que tens demonstrado ao teu servo, pois, quando atravessei este Jordão, tinha apenas o meu bastão, e agora tornei-me em dois grandes grupos.

[[v1-32-11]]

^<<v1-32-11,11>>^ Salva-me, rogo-te, da mão do meu irmão Esaú, pois estou com medo dele, de que venha e me ataque a mim e às mães com os filhos.

[[v1-32-12]]

^<<v1-32-12,12>>^ Foste tu que disseste: ‘Certamente, eu vou tratar-te bem e tornar a tua descendência^&#42;1^ como os grãos de areia do mar, que são numerosos demais para serem contados.’”

[NOTE]
====
. Lit.: “semente”.
====

[[v1-32-13]]

^<<v1-32-13,13>>^ Ele passou ali a noite. Então, daquilo que tinha, separou um presente para Esaú, seu irmão:

[[v1-32-14]]

^<<v1-32-14,14>>^ 200 cabras, 20 bodes, 200 ovelhas, 20 carneiros,

[[v1-32-15]]

^<<v1-32-15,15>>^ 30 camelas que amamentavam e as suas crias, 40 vacas, 10 touros, 20 jumentas e 10 jumentos.

[[v1-32-16]]

^<<v1-32-16,16>>^ Entregou-os aos seus servos, um rebanho após outro, e disse-lhes: “Passem à minha frente, e devem deixar um espaço entre um rebanho e outro.”

[[v1-32-17]]

^<<v1-32-17,17>>^ Ele também ordenou ao primeiro servo: “Caso Esaú, meu irmão, te encontre e pergunte: ‘A quem pertences, para onde vais e a quem pertencem estes animais à tua frente?’,

[[v1-32-18]]

^<<v1-32-18,18>>^ deves dizer: ‘Ao seu servo Jacó. São um presente que ele envia ao meu senhor Esaú, e ele mesmo também vem atrás de nós!’”

[[v1-32-19]]

^<<v1-32-19,19>>^ Ordenou também ao segundo, ao terceiro e a todos os que acompanhavam os rebanhos: “Quando encontrarem Esaú, devem dizer-lhe estas palavras.

[[v1-32-20]]

^<<v1-32-20,20>>^ Também devem dizer: ‘O seu servo Jacó vem atrás de nós.’” Pois dizia para consigo: ‘Se eu o acalmar, mandando um presente à minha frente, talvez ele me receba bem quando o encontrar depois.’

[[v1-32-21]]

^<<v1-32-21,21>>^ Por isso, o presente foi enviado à sua frente, mas ele passou a noite no acampamento.

[[v1-32-22]]

^<<v1-32-22,22>>^ Mais tarde naquela noite, ele levantou-se e, levando as duas esposas, as duas servas e os onze filhos jovens, passou pelo ponto de travessia do Jaboque.

[[v1-32-23]]

^<<v1-32-23,23>>^ Assim, levou-os e fê-los atravessar a corrente^&#42;1^ com tudo o que tinha.

[NOTE]
====
. Ou: “o vale da torrente; o uádi”.
====

[[v1-32-24]]

^<<v1-32-24,24>>^ Finalmente, Jacó ficou sozinho. Então, um homem começou a lutar com ele até ao amanhecer.

[[v1-32-25]]

^<<v1-32-25,25>>^ Quando viu que não tinha vencido Jacó, tocou-lhe na articulação da anca; e a anca de Jacó deslocou-se enquanto lutava com ele.

[[v1-32-26]]

^<<v1-32-26,26>>^ Depois disse: “Deixa-me ir, pois está a amanhecer.” Então, Jacó disse: “Não te deixarei ir, a menos que me abençoes.”

[[v1-32-27]]

^<<v1-32-27,27>>^ Perguntou-lhe, então: “Qual é o teu nome?” Ele respondeu: “Jacó.”

[[v1-32-28]]

^<<v1-32-28,28>>^ E ele disse: “O teu nome já não será Jacó, mas, sim, Israel,^&#42;1^ pois lutaste com Deus e com homens e, por fim, venceste.”

[NOTE]
====
. Que significa “aquele que luta (persevera) com Deus” ou “Deus luta”.
====

[[v1-32-29]]

^<<v1-32-29,29>>^ Jacó disse-lhe: “Diz-me o teu nome, por favor.” No entanto, ele respondeu: “Porque é que me perguntas o meu nome?” Então, abençoou-o ali.

[[v1-32-30]]

^<<v1-32-30,30>>^ Por isso, Jacó deu ao lugar o nome de Peniel,^&#42;1^ pois disse: “Eu vi Deus face a face, e, ainda assim, a minha vida^&#42;2^ foi preservada.”

[NOTE]
====
. Que significa “face de Deus”.
. Ou: “alma”.
====

[[v1-32-31]]

^<<v1-32-31,31>>^ E o sol começou a brilhar sobre ele assim que passou por Penuel,^&#42;1^ mas ele coxeava por causa da anca.

[NOTE]
====
. Ou: “Peniel”.
====

[[v1-32-32]]

^<<v1-32-32,32>>^ É por isso que, até ao dia de hoje, os filhos de Israel não costumam comer o tendão da coxa,^&#42;1^ que fica na articulação da anca, porque ele tocou na articulação da anca de Jacó, no tendão da coxa.

[NOTE]
====
. Lit.: “o tendão do nervo da coxa”.
====

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]