include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v51-1-1]]

^<<v51-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e Timóteo, nosso irmão,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos santos e fiéis irmãos em união com Cristo que estão em Colossos:
Que tenham bondade imerecida e paz da parte de Deus, nosso Pai.

[[v51-1-3]]

^<<v51-1-3,3>>^ Agradecemos sempre a Deus, o Pai do nosso Senhor Jesus Cristo, quando oramos por vocês,

[[v51-1-4]]

^<<v51-1-4,4>>^ pois ouvimos falar da vossa fé em Cristo Jesus e do amor que têm por todos os santos,

[[v51-1-5]]

^<<v51-1-5,5>>^ por causa da esperança que vos está reservada nos céus. Já ouviram falar desta esperança através da mensagem da verdade, as boas novas

[[v51-1-6]]

^<<v51-1-6,6>>^ que chegaram até vocês. Assim como as boas novas estão a dar fruto e a aumentar em todo o mundo, o mesmo acontece também entre vocês, desde o dia em que ouviram e conheceram de modo exato a verdadeira bondade imerecida de Deus.

[[v51-1-7]]

^<<v51-1-7,7>>^ Isto é o que aprenderam do nosso amado coescravo Epafras, ministro fiel do Cristo, que serve no nosso lugar.

[[v51-1-8]]

^<<v51-1-8,8>>^ Ele também nos falou do amor que têm em sentido espiritual.^&#42;1^

[NOTE]
====
. Lit.: “em espírito”.
====

[[v51-1-9]]

^<<v51-1-9,9>>^ É também por essa razão que, desde o dia em que ouvimos isso, não deixámos de orar por vocês e de pedir que fiquem cheios do conhecimento exato da sua vontade, com toda a sabedoria e compreensão espiritual,

[[v51-1-10]]

^<<v51-1-10,10>>^ para andarem de um modo digno de Jeová,^&#42;1^ a fim de lhe agradarem plenamente, enquanto continuam a dar fruto em toda a boa obra e a aumentar no conhecimento exato de Deus.

[NOTE]
====
. Veja o Ap. A5.
====

[[v51-1-11]]

^<<v51-1-11,11>>^ Pedimos também que sejam fortalecidos com todo o poder, segundo o seu poder glorioso, para que possam perseverar plenamente com paciência e alegria,

[[v51-1-12]]

^<<v51-1-12,12>>^ enquanto agradecem ao Pai, que vos habilitou para participar na herança dos santos na luz.

[[v51-1-13]]

^<<v51-1-13,13>>^ Ele livrou-nos da autoridade da escuridão e transferiu-nos para o reino do seu Filho amado,

[[v51-1-14]]

^<<v51-1-14,14>>^ por meio de quem temos o nosso livramento por resgate, o perdão dos nossos pecados.

[[v51-1-15]]

^<<v51-1-15,15>>^ Ele é a imagem do Deus invisível, o primogénito de toda a criação;

[[v51-1-16]]

^<<v51-1-16,16>>^ pois, por meio dele, foram criadas todas as outras coisas nos céus e na terra, as coisas visíveis e as coisas invisíveis, quer sejam tronos, quer domínios, quer governos, quer autoridades. Todas as outras coisas foram criadas por meio dele e para ele.

[[v51-1-17]]

^<<v51-1-17,17>>^ Além disso, ele já existia antes de todas as outras coisas e, por meio dele, todas as outras coisas vieram a existir.

[[v51-1-18]]

^<<v51-1-18,18>>^ E ele é a cabeça do corpo, que é a congregação. Ele é o princípio, o primogénito dentre os mortos, para se tornar aquele que é o primeiro em todas as coisas;

[[v51-1-19]]

^<<v51-1-19,19>>^ porque Deus se agradou de fazer morar nele toda a plenitude

[[v51-1-20]]

^<<v51-1-20,20>>^ e, por meio dele, reconciliar todas as outras coisas consigo mesmo, tanto as coisas na terra como as coisas nos céus, estabelecendo a paz por meio do sangue que ele derramou na estaca.^&#42;1^

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v51-1-21]]

^<<v51-1-21,21>>^ De facto, a vocês, os que antes estavam apartados de Deus e eram seus inimigos porque fixavam a mente em obras más,

[[v51-1-22]]

^<<v51-1-22,22>>^ ele reconciliou agora consigo por meio do corpo carnal daquele que morreu,^&#42;1^ a fim de apresentar-vos santos, sem defeito e livres de qualquer acusação perante si mesmo

[NOTE]
====
. Ou: “do corpo carnal daquele, por meio da morte dele”.
====

[[v51-1-23]]

^<<v51-1-23,23>>^ — desde que, naturalmente, continuem na fé, estabelecidos no alicerce e firmes, sem serem afastados da esperança das boas novas que ouviram e que foram pregadas em toda a criação debaixo do céu. Dessas boas novas, eu, Paulo, tornei-me ministro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Agora, alegro-me pelas coisas que sofro por vocês, e estou a suportar na minha carne o que ainda falta dos sofrimentos do Cristo, a favor do seu corpo, que é a congregação.

[[v51-1-25]]

^<<v51-1-25,25>>^ Tornei-me ministro desta congregação, de acordo com a responsabilidade^&#42;1^ que me foi dada por Deus, para o vosso benefício, de pregar plenamente a palavra de Deus,

[NOTE]
====
. Ou: “administração”.
====

[[v51-1-26]]

^<<v51-1-26,26>>^ o segredo sagrado que estava escondido desde os sistemas de coisas passados^&#42;1^ e as gerações passadas, mas que, agora, tem sido revelado aos Seus santos.

[NOTE]
====
. Ou: “as épocas passadas”. Veja o Glossário.
====

[[v51-1-27]]

^<<v51-1-27,27>>^ Deus agradou-se de lhes dar a conhecer as gloriosas riquezas desse segredo sagrado entre as nações. O segredo sagrado é Cristo em união convosco, a esperança de participar da sua glória.

[[v51-1-28]]

^<<v51-1-28,28>>^ É a ele que proclamamos, advertindo todos e ensinando todos com toda a sabedoria, a fim de apresentarmos todos como pessoas completas em união com Cristo.

[[v51-1-29]]

^<<v51-1-29,29>>^ Com este objetivo é que, de facto, trabalho arduamente, esforçando-me com a sua força, que está a atuar poderosamente em mim.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]