include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v51-2-1]]

^<<v51-2-1,1>>^ Pois quero que se apercebam de como é grande a luta que tenho a vosso favor, a favor dos de Laodiceia e a favor de todos os que não me viram pessoalmente.^&#42;1^

[NOTE]
====
. Lit.: “não viram o meu rosto na carne”.
====

[[v51-2-2]]

^<<v51-2-2,2>>^ O meu objetivo é que o coração deles seja consolado, que eles sejam harmoniosamente unidos em amor e que tenham todas as riquezas que resultam da plena certeza do seu entendimento, a fim de obter um conhecimento exato do segredo sagrado de Deus, a saber, Cristo.

[[v51-2-3]]

^<<v51-2-3,3>>^ Todos os tesouros da sabedoria e do conhecimento encontram-se cuidadosamente ocultos nele.

[[v51-2-4]]

^<<v51-2-4,4>>^ Digo isto para que ninguém vos iluda com argumentos persuasivos.

[[v51-2-5]]

^<<v51-2-5,5>>^ Embora esteja ausente no corpo, estou convosco em espírito, alegrando-me de ver a vossa boa ordem e a firmeza da vossa fé em Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Portanto, assim como aceitaram Cristo Jesus, o Senhor, continuem a andar em união com ele,

[[v51-2-7]]

^<<v51-2-7,7>>^ sendo arraigados e edificados nele, e estabelecidos na fé, como vos foi ensinado, transbordando em agradecimentos.

[[v51-2-8]]

^<<v51-2-8,8>>^ Tenham cuidado para que ninguém vos escravize^&#42;1^ por meio de filosofia e vão engano, que são baseados em tradições humanas, nas coisas elementares do mundo, e não em Cristo;

[NOTE]
====
. Ou: “vos leve embora como despojo”.
====

[[v51-2-9]]

^<<v51-2-9,9>>^ porque é nele que mora corporalmente toda a plenitude da qualidade divina.

[[v51-2-10]]

^<<v51-2-10,10>>^ E vocês adquiriram uma plenitude por meio dele, aquele que é o cabeça de todo o governo e autoridade.

[[v51-2-11]]

^<<v51-2-11,11>>^ Pela vossa relação com ele, vocês também foram circuncidados com uma circuncisão realizada sem mãos, por se despojarem do corpo carnal, isto é, por meio da circuncisão que pertence ao Cristo.

[[v51-2-12]]

^<<v51-2-12,12>>^ Pois foram sepultados com ele no seu batismo e, pela vossa relação com ele, foram também levantados com ele através da vossa fé na atuação poderosa de Deus, que o levantou dentre os mortos.

[[v51-2-13]]

^<<v51-2-13,13>>^ Além disso, embora estivessem mortos por causa das vossas falhas e do estado incircunciso da vossa carne, Deus deu-vos vida com ele. Ele perdoou-nos bondosamente todas as nossas falhas

[[v51-2-14]]

^<<v51-2-14,14>>^ e apagou^&#42;1^ o documento manuscrito que consistia em decretos e que estava contra nós. Ele removeu-o, pregando-o na estaca.^&#42;2^

[NOTE]
====
. Ou: “cancelou”.
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v51-2-15]]

^<<v51-2-15,15>>^ Ele pôs completamente a nu os governos e as autoridades, e exibiu-os publicamente como vencidos, conduzindo-os por meio dela^&#42;1^ num desfile triunfal.

[NOTE]
====
. Ou, possivelmente: “dele”.
====

[[v51-2-16]]

^<<v51-2-16,16>>^ Portanto, não deixem que ninguém vos julgue pelo que comem ou bebem, ou com respeito à celebração de uma festividade, da lua nova ou de um sábado.

[[v51-2-17]]

^<<v51-2-17,17>>^ Estas coisas são uma sombra do que viria, mas a realidade pertence ao Cristo.

[[v51-2-18]]

^<<v51-2-18,18>>^ Que nenhum homem que tenha prazer numa falsa humildade e numa forma de adoração dos anjos vos prive do prémio; tais pessoas insistem^&#42;1^ nas coisas que viram. Na realidade, a sua mentalidade carnal enche-as de orgulho sem nenhum motivo justo,

[NOTE]
====
. Ou: “põem os pés; entram”. Expressão usada em ritos pagãos de mistério (de iniciação).
====

[[v51-2-19]]

^<<v51-2-19,19>>^ e elas não se apegam à cabeça, àquele por meio de quem o corpo inteiro é suprido e harmoniosamente unido mediante as suas juntas e ligamentos, e cresce com o desenvolvimento que vem de Deus.

[[v51-2-20]]

^<<v51-2-20,20>>^ Se morreram com Cristo para as coisas elementares do mundo, porque é que continuam a viver como se fizessem parte do mundo, sujeitando-se ainda aos decretos:

[[v51-2-21]]

^<<v51-2-21,21>>^ “Não pegues, não proves, não toques”,

[[v51-2-22]]

^<<v51-2-22,22>>^ que se referem a coisas que desaparecem com o uso, de acordo com as ordens e os ensinamentos de homens?

[[v51-2-23]]

^<<v51-2-23,23>>^ Estas coisas têm uma aparência de sabedoria numa forma de adoração autoimposta e falsa humildade, um tratamento severo do corpo, mas não são de nenhum valor para combater os desejos da carne.

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]