include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v51-3-1]]

^<<v51-3-1,1>>^ No entanto, se foram levantados com o Cristo, continuem a buscar as coisas de cima, onde o Cristo está sentado à direita de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Mantenham a mente fixa nas coisas de cima, não nas coisas da terra.

[[v51-3-3]]

^<<v51-3-3,3>>^ Pois vocês morreram e a vossa vida está escondida com o Cristo, em união com Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ Quando o Cristo, a nossa vida, for manifestado, então, vocês também serão manifestados com ele em glória.

[[v51-3-5]]

^<<v51-3-5,5>>^ Amorteçam, portanto, os membros do vosso corpo^&#42;1^ com respeito a imoralidade sexual,^&#42;2^ impureza, paixão desenfreada,^&#42;3^ desejos prejudiciais e ganância, que é idolatria.

[NOTE]
====
. Ou: “os vossos membros que estão na terra”.
. Em grego, porneía. Veja o Glossário.
. Ou: “apetite sexual”.
====

[[v51-3-6]]

^<<v51-3-6,6>>^ É por causa destas coisas que vem a ira de Deus.

[[v51-3-7]]

^<<v51-3-7,7>>^ A vossa conduta também era assim,^&#42;1^ no vosso anterior modo de vida.^&#42;2^

[NOTE]
====
. Ou: “É assim que vocês andavam”.
. Ou: “quando vocês viviam daquele modo”.
====

[[v51-3-8]]

^<<v51-3-8,8>>^ Agora, porém, devem abandonar todas estas coisas: a raiva, a ira, a maldade e as palavras ofensivas; e devem eliminar a conversa obscena da vossa boca.

[[v51-3-9]]

^<<v51-3-9,9>>^ Não mintam uns aos outros. Dispam-se da velha personalidade^&#42;1^ com as suas práticas

[NOTE]
====
. Lit.: “do velho homem”.
====

[[v51-3-10]]

^<<v51-3-10,10>>^ e revistam-se da nova personalidade, a qual, por meio do conhecimento exato, é renovada segundo a imagem d’Aquele que a criou.

[[v51-3-11]]

^<<v51-3-11,11>>^ Nessa condição, não há nem grego nem judeu, nem circuncisão nem incircuncisão, nem estrangeiro, cita,^&#42;1^ escravo nem homem livre; mas Cristo é todas as coisas e está em todos.

[NOTE]
====
. “Cita” indicava uma pessoa não civilizada.
====

[[v51-3-12]]

^<<v51-3-12,12>>^ Portanto, como escolhidos de Deus, santos e amados, revistam-se de terna compaixão,^&#42;1^ bondade, humildade,^&#42;2^ brandura e paciência.

[NOTE]
====
. Ou: “ternas afeições de compaixão”.
. Ou: “humildade mental”.
====

[[v51-3-13]]

^<<v51-3-13,13>>^ Continuem a suportar-se uns aos outros e a perdoar-se uns aos outros liberalmente, mesmo que alguém tenha razão para queixa contra outro. Assim como Jeová^&#42;1^ vos perdoou liberalmente, vocês devem fazer o mesmo.

[NOTE]
====
. Veja o Ap. A5.
====

[[v51-3-14]]

^<<v51-3-14,14>>^ Contudo, além de todas estas coisas, revistam-se de amor, pois é o perfeito vínculo de união.

[[v51-3-15]]

^<<v51-3-15,15>>^ Também, que a paz do Cristo reine no vosso coração,^&#42;1^ pois vocês foram chamados a essa paz num só corpo. E mostrem-se gratos.

[NOTE]
====
. Ou: “controle o vosso coração”.
====

[[v51-3-16]]

^<<v51-3-16,16>>^ Que a palavra do Cristo resida ricamente em vocês com toda a sabedoria. Continuem a ensinar e a encorajar-se^&#42;1^ uns aos outros com salmos, louvores a Deus e cânticos espirituais cantados com gratidão.^&#42;2^ Continuem a cantar a Jeová no coração.^&#42;3^

[NOTE]
====
. Ou: “a exortar-se”.
. Ou: “graça”.
. Veja o Ap. A5.
====

[[v51-3-17]]

^<<v51-3-17,17>>^ Façam o que fizerem, em palavras ou em ações, façam-no em nome do Senhor Jesus, agradecendo a Deus, o Pai, através dele.

[[v51-3-18]]

^<<v51-3-18,18>>^ Esposa, sujeita-te ao teu marido, assim como é apropriado no Senhor.

[[v51-3-19]]

^<<v51-3-19,19>>^ Marido, continua a amar a tua esposa e não te ires amargamente^&#42;1^ com ela.

[NOTE]
====
. Ou: “não sejas rude”.
====

[[v51-3-20]]

^<<v51-3-20,20>>^ Filhos, sejam obedientes em tudo aos vossos pais, pois isso é agradável ao Senhor.

[[v51-3-21]]

^<<v51-3-21,21>>^ Pais, não irritem^&#42;1^ os vossos filhos, para que eles não desanimem.^&#42;2^

[NOTE]
====
. Ou: “não provoquem; não exasperem”.
. Ou: “não fiquem desencorajados”.
====

[[v51-3-22]]

^<<v51-3-22,22>>^ Escravos, sejam obedientes em tudo aos vossos senhores humanos,^&#42;1^ não apenas quando estiverem a ser observados,^&#42;2^ só para agradar a homens, mas com sinceridade de coração, com temor a Jeová.^&#42;3^

[NOTE]
====
. Lit.: “carnais”.
. Lit.: “não servindo à vista”.
. Veja o Ap. A5.
====

[[v51-3-23]]

^<<v51-3-23,23>>^ Façam o que fizerem, trabalhem nisso de toda a alma,^&#42;1^ como para Jeová,^&#42;2^ e não para homens,

[NOTE]
====
. Veja o Glossário.
. Veja o Ap. A5.
====

[[v51-3-24]]

^<<v51-3-24,24>>^ pois sabem que é de Jeová^&#42;1^ que receberão a herança como recompensa. Trabalhem como escravos para o Senhor, Cristo.

[NOTE]
====
. Veja o Ap. A5.
====

[[v51-3-25]]

^<<v51-3-25,25>>^ Certamente, quem faz o que é errado terá a retribuição pelo que fez de errado, e não há parcialidade.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]