include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v51-4-1]]

^<<v51-4-1,1>>^ Senhores, tratem os vossos escravos de modo justo e correto, sabendo que vocês também têm um Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Persistam em oração e, ao fazerem isso, permaneçam despertos e deem graças.

[[v51-4-3]]

^<<v51-4-3,3>>^ Ao mesmo tempo, orem também por nós, para que Deus abra uma porta para a palavra, a fim de que possamos declarar o segredo sagrado a respeito do Cristo, pelo qual estou preso com correntes,

[[v51-4-4]]

^<<v51-4-4,4>>^ e para que eu o proclame tão claramente como devo.

[[v51-4-5]]

^<<v51-4-5,5>>^ Prossigam em andar com sabedoria para com os de fora, usando o tempo do melhor modo possível.^&#42;1^

[NOTE]
====
. Lit.: “comprando o tempo determinado”.
====

[[v51-4-6]]

^<<v51-4-6,6>>^ Que as vossas palavras sejam sempre agradáveis, temperadas com sal, de modo que saibam como responder a cada pessoa.

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico, meu amado irmão, fiel ministro e coescravo no Senhor, vai dar-vos todas as notícias a meu respeito.

[[v51-4-8]]

^<<v51-4-8,8>>^ Envio-o a vocês para que saibam como estamos e para que ele console o vosso coração.

[[v51-4-9]]

^<<v51-4-9,9>>^ Ele vai com Onésimo, meu fiel e amado irmão, que é um dos vossos; eles vão informar-vos sobre tudo o que está a acontecer aqui.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, meu companheiro de prisão, manda-vos saudações, e também Marcos, primo de Barnabé (a respeito de Marcos, vocês receberam instruções para o acolher se ele for visitar-vos),

[[v51-4-11]]

^<<v51-4-11,11>>^ e Jesus, que é chamado Justo. Estes são dos circuncisos. Apenas estes são os meus colaboradores a favor do Reino de Deus, e tornaram-se para mim uma fonte de grande consolo.^&#42;1^

[NOTE]
====
. Ou: “um auxílio fortificante”.
====

[[v51-4-12]]

^<<v51-4-12,12>>^ Epafras, que é um dos vossos, escravo de Cristo Jesus, manda-vos saudações. Ele ora sempre por vocês com fervor, para que, por fim, estejam completos e tenham firme convicção quanto a toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ Sou testemunha de que ele trabalha arduamente a vosso favor e a favor dos de Laodiceia e dos de Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Lucas, o médico amado, manda-vos saudações, e também Demas.

[[v51-4-15]]

^<<v51-4-15,15>>^ Transmitam as minhas saudações aos irmãos de Laodiceia, a Ninfa e à congregação que se reúne na sua casa.

[[v51-4-16]]

^<<v51-4-16,16>>^ E, quando esta carta tiver sido lida entre vocês, providenciem que ela também seja lida na congregação dos laodicenses, e que vocês também leiam a de Laodiceia.

[[v51-4-17]]

^<<v51-4-17,17>>^ Digam também a Arquipo: “Dá atenção ao ministério que aceitaste no Senhor, a fim de o cumprires.”

[[v51-4-18]]

^<<v51-4-18,18>>^ Aqui está a minha saudação, a de Paulo, pela minha própria mão. Continuem a lembrar-se das correntes que me prendem. Que a bondade imerecida esteja convosco.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]