include::./index.adoc[]

[[v33-6-0]]
=== Miqueias, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v33-6-1]]

^<<v33-6-1,1>>^ Ouçam, por favor, o que Jeová está a dizer.
Levantem-se, apresentem a vossa causa diante dos montes,
E que as colinas ouçam a vossa voz.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ouçam, ó montes, a causa de Jeová,
E também vocês, sólidos alicerces da terra,
Pois Jeová tem uma causa contra o seu povo;
É contra Israel que ele argumentará:

[[v33-6-3]]

^<<v33-6-3,3>>^ “Meu povo, o que é que eu vos fiz?
Como é que vos cansei?
Testemunhem contra mim.

[[v33-6-4]]

^<<v33-6-4,4>>^ Pois tirei-vos da terra do Egito
E resgatei-vos da terra da escravidão;^&#42;1^
À vossa frente, enviei Moisés, Arão e Miriam.

[NOTE]
====
. Lit.: “casa dos escravos”.
====

[[v33-6-5]]

^<<v33-6-5,5>>^ Meu povo, por favor, lembrem-se do que Balaque, rei de Moabe, propôs
E do que Balaão, filho de Beor, lhe respondeu,
Do que aconteceu de Sitim até Gilgal,
Para que conheçam os atos justos de Jeová.”

[[v33-6-6]]

^<<v33-6-6,6>>^ O que levarei quando comparecer perante Jeová?
O que levarei quando me curvar diante do Deus que mora no alto?
Comparecerei perante ele com ofertas queimadas,
Com bezerros de um ano?

[[v33-6-7]]

^<<v33-6-7,7>>^ Será que Jeová terá prazer em milhares de carneiros,
Em dezenas de milhares de torrentes de azeite?
Darei o meu primogénito pela minha rebeldia,
O fruto do meu corpo pelo meu pecado?^&#42;1^

[NOTE]
====
. Ou: “pelo pecado da minha alma”.
====

[[v33-6-8]]

^<<v33-6-8,8>>^ Ele já te informou, ó homem, sobre o que é bom.
E o que é que Jeová pede^&#42;1^ de ti?
Apenas que pratiques a justiça,^&#42;2^ ames a lealdade^&#42;3^
E andes modestamente com o teu Deus!

[NOTE]
====
. Ou: “exige”.
. Ou: “sejas justo”.
. Ou: “sejas bondoso e leal no teu amor”. Lit.: “ames amor leal”.
====

[[v33-6-9]]

^<<v33-6-9,9>>^ A voz de Jeová clama à cidade
— Os que têm sabedoria prática temerão o teu nome —
Prestem atenção à vara e a quem a designou.

[[v33-6-10]]

^<<v33-6-10,10>>^ Será que na casa de quem é mau ainda existem os tesouros da maldade,
E a efa^&#42;1^ reduzida, que é detestável?

[NOTE]
====
. Veja o Ap. B14.
====

[[v33-6-11]]

^<<v33-6-11,11>>^ Por acaso, posso ser puro^&#42;1^ com uma balança falsa,
Com uma bolsa de pesos de pedra fraudulentos?

[NOTE]
====
. Ou: “inocente”.
====

[[v33-6-12]]

^<<v33-6-12,12>>^ Pois os seus homens ricos estão cheios de violência,
E os seus habitantes dizem mentiras;
Eles têm uma língua falsa na boca.

[[v33-6-13]]

^<<v33-6-13,13>>^ “Portanto, vou golpear-te e ferir-te,
Deixando-te devastado por causa dos teus pecados.

[[v33-6-14]]

^<<v33-6-14,14>>^ Comerás, mas não ficarás satisfeito;
Haverá um vazio dentro de ti.
Tentarás colocar os teus bens num lugar seguro, mas não conseguirás salvá-los;
E o que conseguires levar, eu entregarei à espada.

[[v33-6-15]]

^<<v33-6-15,15>>^ Semearás, mas não colherás.
Pisarás azeitonas, mas não usarás o azeite;
E pisarás uvas, mas não beberás o vinho.

[[v33-6-16]]

^<<v33-6-16,16>>^ Pois vocês seguem os decretos de Onri e todas as práticas da casa de Acabe,
E andam de acordo com os seus conselhos.
É por isso que vou fazer de ti um motivo de terror,
E dos seus habitantes um alvo de assobios;
E vocês suportarão o desprezo dos povos.”

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]