include::./index.adoc[]

[[v33-7-0]]
=== Miqueias, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v33-7-1]]

^<<v33-7-1,1>>^ Ai de mim! Sou como aquele que,
Depois de colher os frutos de verão
E de recolher as uvas que sobram após a colheita,
Não encontra nenhum cacho de uvas para comer,
Nenhum figo temporão que tanto deseja.^&#42;1^

[NOTE]
====
. Ou: “que a minha alma tanto deseja”.
====

[[v33-7-2]]

^<<v33-7-2,2>>^ Desapareceu da terra aquele que é leal;
Não há ninguém que seja reto entre os homens.
Todos eles ficam de emboscada para derramar sangue.
Cada um caça o seu próprio irmão com uma rede.

[[v33-7-3]]

^<<v33-7-3,3>>^ As suas mãos são peritas em fazer o que é mau;
O príncipe faz exigências,
O juiz julga por suborno,
O homem de destaque torna conhecido o que ele quer,^&#42;1^
E eles fazem esses planos juntos.^&#42;2^

[NOTE]
====
. Ou: “o desejo da sua alma”.
. Lit.: “tramam isso juntos”.
====

[[v33-7-4]]

^<<v33-7-4,4>>^ O melhor entre eles é como espinhos,
O mais reto deles é pior do que uma cerca de espinhos.
Chegará o dia anunciado pelos teus vigias e o dia do teu ajuste de contas.
Então, todos entrarão em pânico.

[[v33-7-5]]

^<<v33-7-5,5>>^ Não tenham fé no vosso companheiro
Nem confiem num amigo íntimo.
Tem cuidado com o que dizes àquela que se deita nos teus braços.

[[v33-7-6]]

^<<v33-7-6,6>>^ Pois o filho despreza o pai,
A filha levanta-se contra a mãe,
E a nora contra a sogra;
Os inimigos do homem são os homens da sua própria casa.

[[v33-7-7]]

^<<v33-7-7,7>>^ Mas, quanto a mim, ficarei vigilante à espera de Jeová.
Esperarei pacientemente^&#42;1^ pelo Deus da minha salvação.
O meu Deus irá ouvir-me.

[NOTE]
====
. Ou: “Mostrarei uma atitude de espera”.
====

[[v33-7-8]]

^<<v33-7-8,8>>^ Não te alegres por minha causa, ó inimiga minha.
Embora eu tenha caído, hei de levantar-me;
Embora eu more na escuridão, Jeová será a minha luz.

[[v33-7-9]]

^<<v33-7-9,9>>^ Suportarei o furor de Jeová
— Pois pequei contra ele —
Até que ele defenda a minha causa e me faça justiça.
Ele irá levar-me para a luz;
Verei a sua justiça.

[[v33-7-10]]

^<<v33-7-10,10>>^ A minha inimiga também verá isso,
E a vergonha cobrirá aquela que me disse:
“Onde é que está Jeová, teu Deus?”
Os meus olhos hão de vê-la.
Então, ela será espezinhada como lama nas ruas.

[[v33-7-11]]

^<<v33-7-11,11>>^ Será um dia para se construírem os seus muros de pedra;
Nesse dia, o limite será estendido.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “o decreto estará longe”.
====

[[v33-7-12]]

^<<v33-7-12,12>>^ Nesse dia, virão até ti
Da Assíria e das cidades do Egito,
Desde o Egito até ao rio;^&#42;1^
De mar a mar e de monte a monte.

[NOTE]
====
. Isto é, o rio Eufrates.
====

[[v33-7-13]]

^<<v33-7-13,13>>^ E a terra ficará desolada por causa dos seus habitantes,
Por causa do que eles fizeram.^&#42;1^

[NOTE]
====
. Lit.: “Por causa do fruto das suas ações”.
====

[[v33-7-14]]

^<<v33-7-14,14>>^ Com o teu bastão, pastoreia o teu povo, o rebanho da tua herança,
Que morava sozinho numa floresta, no meio de um pomar.
Que eles pastem em Basã e Gileade como nos tempos antigos.

[[v33-7-15]]

^<<v33-7-15,15>>^ “Como nos dias em que saíste da terra do Egito,
Vou mostrar-te coisas maravilhosas.

[[v33-7-16]]

^<<v33-7-16,16>>^ As nações hão de vê-las e ficar envergonhadas apesar de todo o seu poder.
Porão a mão sobre a boca;
Os seus ouvidos ficarão surdos.

[[v33-7-17]]

^<<v33-7-17,17>>^ Lamberão o pó como as serpentes;
Sairão a tremer dos seus refúgios, como os répteis da terra.
Virão apavoradas a Jeová, nosso Deus,
E terão medo de ti.”

[[v33-7-18]]

^<<v33-7-18,18>>^ Quem é Deus como tu,
Que perdoa o erro e deixa passar a transgressão do restante da sua herança?
Ele não continuará irado para sempre,
Pois tem prazer no amor leal.

[[v33-7-19]]

^<<v33-7-19,19>>^ Ele terá novamente misericórdia de nós; vencerá^&#42;1^ os nossos erros.
Tu lançarás nas profundezas do mar todos os seus pecados.

[NOTE]
====
. Ou: “espezinhará; subjugará”.
====

[[v33-7-20]]

^<<v33-7-20,20>>^ Demonstrarás fidelidade a Jacó,
Amor leal a Abraão,
Assim como juraste aos nossos antepassados desde os tempos antigos.

'''

xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-naum/034-naum-001.adoc#v34-1-0[Próximo Capítulo &#62;]