include::./index.adoc[]

[[v33-4-0]]
=== Miqueias, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v33-4-1]]

^<<v33-4-1,1>>^ Na parte final dos dias,^&#42;1^
O monte da casa de Jeová
Ficará firmemente estabelecido acima do cume dos montes
E será elevado acima das colinas,
E os povos afluirão a ele.

[NOTE]
====
. Ou: “Nos últimos dias”.
====

[[v33-4-2]]

^<<v33-4-2,2>>^ E muitas nações irão e dirão:
“Venham, subamos ao monte de Jeová
E à casa do Deus de Jacó.
Ele irá instruir-nos sobre os seus caminhos,
E nós andaremos nas suas veredas.”
Pois de Sião sairá a lei,^&#42;1^
E de Jerusalém a palavra de Jeová.

[NOTE]
====
. Ou: “instrução”.
====

[[v33-4-3]]

^<<v33-4-3,3>>^ Ele fará julgamento entre muitos povos
E resolverá^&#42;1^ as questões referentes a poderosas nações distantes.
Eles transformarão as suas espadas em relhas de arado,
E as suas lanças em podadeiras.
Nenhuma nação levantará a espada contra outra nação,
Nem aprenderão mais a guerra.

[NOTE]
====
. Ou: “corrigirá”.
====

[[v33-4-4]]

^<<v33-4-4,4>>^ Cada um deles se sentará^&#42;1^ debaixo da sua videira e debaixo da sua figueira,
Sem que ninguém os faça ter medo,
Porque a boca de Jeová dos exércitos o disse.

[NOTE]
====
. Ou: “morará”.
====

[[v33-4-5]]

^<<v33-4-5,5>>^ Pois todos os povos andarão, cada um no nome do seu deus,
Mas nós andaremos no nome de Jeová, nosso Deus, para todo o sempre.

[[v33-4-6]]

^<<v33-4-6,6>>^ “Nesse dia”, diz Jeová,
“Ajuntarei os que coxeavam^&#42;1^
E reunirei os que estavam espalhados,
Juntamente com aqueles que tratei com dureza.

[NOTE]
====
. Lit.: “a que coxeava”.
====

[[v33-4-7]]

^<<v33-4-7,7>>^ Farei dos que coxeavam^&#42;1^ um restante,
E dos que foram mandados para longe uma nação poderosa;
E Jeová reinará sobre eles no monte Sião,
Agora e para sempre.

[NOTE]
====
. Lit.: “da que coxeava”.
====

[[v33-4-8]]

^<<v33-4-8,8>>^ Quanto a ti, ó torre do rebanho,
O monte da filha de Sião,
O primeiro domínio^&#42;1^ voltará, sim, voltará a ti,
O reino que pertence à filha de Jerusalém.

[NOTE]
====
. Ou: “domínio anterior”.
====

[[v33-4-9]]

^<<v33-4-9,9>>^ Porque é que estás a gritar?
Não tens rei?
O teu conselheiro morreu?
Será por isso que se apoderaram de ti dores como as de uma mulher que está a dar à luz?

[[v33-4-10]]

^<<v33-4-10,10>>^ Contorce-te e geme de dor, ó filha de Sião,
Como uma mulher que está a dar à luz,
Pois, agora, sairás da cidade e morarás no campo.
Irás até Babilónia,
E lá serás libertada;
Lá, Jeová irá resgatar-te das mãos dos teus inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Agora, muitas nações serão ajuntadas contra ti;
Elas dirão: ‘Que Sião seja profanada,
E que isso aconteça diante dos nossos olhos.’

[[v33-4-12]]

^<<v33-4-12,12>>^ No entanto, elas não conhecem os pensamentos de Jeová,
Nem entendem o seu propósito;^&#42;1^
Pois ele irá ajuntá-las como feixes de cereais recém-cortados na eira.

[NOTE]
====
. Ou: “conselho”.
====

[[v33-4-13]]

^<<v33-4-13,13>>^ Levanta-te e debulha, ó filha de Sião;
Pois transformarei os teus chifres em chifres de ferro
E os teus cascos em cascos de cobre,
E pulverizarás muitos povos.
Devotarás o seu lucro desonesto a Jeová,
E os seus recursos ao verdadeiro Senhor de toda a terra.”

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]