include::./index.adoc[]

[[v33-5-0]]
=== Miqueias, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v33-5-1]]

^<<v33-5-1,1>>^ “Agora, fazes cortes em ti mesma,
Ó filha que estás sob ataque;
Nós fomos sitiados.
Com uma vara, ferem o rosto do juiz de Israel.

[[v33-5-2]]

^<<v33-5-2,2>>^ E tu, ó Belém Efrata,
Pequena demais para estar entre os milhares^&#42;1^ de Judá,
É de ti que me sairá aquele que será governante em Israel,
Cuja origem é dos tempos antigos, dos dias da antiguidade.

[NOTE]
====
. Ou: “clãs”.
====

[[v33-5-3]]

^<<v33-5-3,3>>^ Portanto, ele irá abandoná-los
Até ao tempo em que aquela que está prestes a dar à luz dê à luz.
E o restante dos seus irmãos retornará ao povo de Israel.

[[v33-5-4]]

^<<v33-5-4,4>>^ Ele irá levantar-se e pastoreará com a força de Jeová,
Com a superioridade do nome de Jeová, seu Deus.
E eles morarão em segurança,
Porque a sua grandeza chegará, então, aos confins da terra.

[[v33-5-5]]

^<<v33-5-5,5>>^ E ele trará paz.
Se o assírio invadir a nossa terra e pisar as nossas torres fortificadas,
Levantaremos contra ele sete pastores, sim, oito príncipes^&#42;1^ da humanidade.

[NOTE]
====
. Ou: “líderes”.
====

[[v33-5-6]]

^<<v33-5-6,6>>^ Eles pastorearão a terra da Assíria com a espada,
E a terra de Ninrode nas suas entradas.
E ele irá livrar-nos do assírio,
Quando este invadir a nossa terra e pisar o nosso território.

[[v33-5-7]]

^<<v33-5-7,7>>^ Os que restarem de Jacó serão, no meio de muitos povos,
Como orvalho da parte de Jeová,
Como chuvas abundantes sobre a vegetação,
Que não depositam a sua esperança no homem
Nem esperam pelos filhos dos homens.

[[v33-5-8]]

^<<v33-5-8,8>>^ Os que restarem de Jacó serão, entre as nações,
No meio de muitos povos,
Como um leão entre os animais da floresta,
Como um leão novo^&#42;1^ entre os rebanhos de ovelhas,
Que passa, ataca e dilacera;
E não há quem os livre.

[NOTE]
====
. Ou: “leão novo jubado”.
====

[[v33-5-9]]

^<<v33-5-9,9>>^ A tua mão há de levantar-se sobre os teus adversários,
E todos os teus inimigos serão destruídos.”

[[v33-5-10]]

^<<v33-5-10,10>>^ “Nesse dia”, diz Jeová,
“Eliminarei os teus cavalos do teu meio e destruirei os teus carros de guerra.

[[v33-5-11]]

^<<v33-5-11,11>>^ Destruirei as cidades da tua terra
E derrubarei todas as tuas fortificações.

[[v33-5-12]]

^<<v33-5-12,12>>^ Acabarei com as feitiçarias que praticas,^&#42;1^
E nenhum praticante de magia continuará no teu meio.

[NOTE]
====
. Lit.: “da tua mão”.
====

[[v33-5-13]]

^<<v33-5-13,13>>^ Eliminarei do teu meio as tuas imagens esculpidas e as tuas colunas sagradas,
E não voltarão a curvar-se diante do trabalho das tuas mãos.

[[v33-5-14]]

^<<v33-5-14,14>>^ Arrancarei do teu meio os teus postes sagrados^&#42;1^
E destruirei as tuas cidades.

[NOTE]
====
. Veja o Glossário.
====

[[v33-5-15]]

^<<v33-5-15,15>>^ Em ira e furor, executarei vingança
Sobre as nações que não obedeceram.”

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]