include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v49-2-1]]

^<<v49-2-1,1>>^ Além disso, Deus deu-vos vida, embora estivessem mortos por causa das vossas falhas e pecados,

[[v49-2-2]]

^<<v49-2-2,2>>^ nos quais andavam antes, segundo o sistema^&#42;1^ deste mundo, segundo o governante da autoridade do ar, o espírito que agora atua nos filhos da desobediência.

[NOTE]
====
. Ou: “proceder”.
====

[[v49-2-3]]

^<<v49-2-3,3>>^ Sim, antes, todos nós nos comportávamos entre eles de acordo com os desejos da nossa carne, satisfazendo a vontade do corpo e da mente,^&#42;1^ e éramos por natureza merecedores^&#42;2^ da ira, assim como os demais.

[NOTE]
====
. Ou: “da carne e dos pensamentos”.
. Ou: “filhos”.
====

[[v49-2-4]]

^<<v49-2-4,4>>^ Mas Deus é rico em misericórdia e, por causa do grande amor com que nos amou,

[[v49-2-5]]

^<<v49-2-5,5>>^ deu-nos vida juntamente com o Cristo, mesmo quando estávamos mortos por causa das nossas falhas —  vocês foram salvos pela bondade imerecida.

[[v49-2-6]]

^<<v49-2-6,6>>^ Além disso, Deus levantou-nos com ele e sentou-nos com ele nos lugares celestiais em união com Cristo Jesus,

[[v49-2-7]]

^<<v49-2-7,7>>^ para que, nos futuros sistemas de coisas,^&#42;1^ ele demonstre as riquezas extraordinárias da sua bondade imerecida através da sua generosidade^&#42;2^ para connosco, em união com Cristo Jesus.

[NOTE]
====
. Ou: “nas épocas futuras”. Veja o Glossário.
. Ou: “do seu favor”.
====

[[v49-2-8]]

^<<v49-2-8,8>>^ Graças a esta bondade imerecida, vocês foram salvos por meio da fé, e isto não é mérito vosso; na verdade, é dádiva de Deus.

[[v49-2-9]]

^<<v49-2-9,9>>^ Não, não é o resultado de obras, a fim de que ninguém tenha razão para se gabar.

[[v49-2-10]]

^<<v49-2-10,10>>^ Nós somos trabalho das mãos de Deus^&#42;1^ e fomos criados em união com Cristo Jesus para realizarmos as boas obras que Deus determinou com antecedência, para que andássemos nelas.

[NOTE]
====
. Ou: “produto do Seu trabalho”.
====

[[v49-2-11]]

^<<v49-2-11,11>>^ Portanto, lembrem-se de que vocês, que por nascimento^&#42;1^ são pessoas das nações, antes eram chamados “incircuncisão” por aqueles chamados “circuncisão”, a qual é feita na carne por mãos humanas.

[NOTE]
====
. Lit.: “em carne”.
====

[[v49-2-12]]

^<<v49-2-12,12>>^ Naquele tempo, estavam sem Cristo, apartados do estado de Israel, estranhos aos pactos da promessa; não tinham esperança e estavam sem Deus no mundo.

[[v49-2-13]]

^<<v49-2-13,13>>^ Mas, em união com Cristo Jesus, vocês, que antes estavam longe, agora estão perto pelo sangue do Cristo.

[[v49-2-14]]

^<<v49-2-14,14>>^ Pois ele é a nossa paz, aquele que de dois grupos fez um só, e que destruiu o muro que havia no meio e que os separava.

[[v49-2-15]]

^<<v49-2-15,15>>^ Por meio da sua carne, ele aboliu a inimizade, a Lei de mandamentos em forma de decretos, para fazer dos dois grupos, que estão em união com ele, um novo homem, e fazer a paz,

[[v49-2-16]]

^<<v49-2-16,16>>^ e para reconciliar plenamente com Deus ambos os povos num só corpo, através da estaca,^&#42;1^ pois ele matou a inimizade por meio de si mesmo.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v49-2-17]]

^<<v49-2-17,17>>^ E ele veio e declarou-vos as boas novas de paz, a vocês que estavam longe, e paz aos que estavam perto;

[[v49-2-18]]

^<<v49-2-18,18>>^ pois, por meio dele, nós, ambos os povos, temos livre acesso ao Pai por um só espírito.

[[v49-2-19]]

^<<v49-2-19,19>>^ Assim, vocês já não são estranhos e estrangeiros, mas são concidadãos dos santos e membros da família de Deus,

[[v49-2-20]]

^<<v49-2-20,20>>^ e foram edificados sobre o alicerce dos apóstolos e dos profetas, sendo o próprio Cristo Jesus a pedra angular de alicerce.

[[v49-2-21]]

^<<v49-2-21,21>>^ Em união com ele, todo o edifício, tendo todas as partes harmoniosamente unidas, está a crescer para se tornar um templo santo para Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v49-2-22]]

^<<v49-2-22,22>>^ Em união com ele, também vocês estão a ser edificados juntamente para se tornarem um lugar para Deus habitar por espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]