include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v49-4-1]]

^<<v49-4-1,1>>^ Portanto eu, o prisioneiro no Senhor, suplico-vos que andem de um modo digno da chamada com que foram chamados,

[[v49-4-2]]

^<<v49-4-2,2>>^ com toda a humildade^&#42;1^ e brandura, com paciência, suportando-se uns aos outros em amor,

[NOTE]
====
. Ou: “humildade mental”.
====

[[v49-4-3]]

^<<v49-4-3,3>>^ esforçando-se diligentemente para manter a unidade do espírito, no vínculo unificador da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há um só corpo e um só espírito, assim como há uma só esperança para a qual foram chamados;

[[v49-4-5]]

^<<v49-4-5,5>>^ há um só Senhor, uma só fé, um só batismo;

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de todos, que é sobre todos, por meio de todos e em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ Cada um de nós recebeu bondade imerecida na proporção em que o Cristo concedeu a dádiva.^&#42;1^

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v49-4-8]]

^<<v49-4-8,8>>^ Pois as Escrituras dizem: “Quando ele subiu ao alto, levou consigo cativos; deu dádivas em homens.”

[[v49-4-9]]

^<<v49-4-9,9>>^ Ora, o que significa a expressão “ele subiu”, senão que também desceu às regiões mais baixas, isto é, à terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ O mesmo que desceu é também aquele que subiu muito acima de todos os céus, para dar plenitude a todas as coisas.

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele deu alguns como apóstolos, alguns como profetas, alguns como evangelizadores,^&#42;1^ alguns como pastores e instrutores,

[NOTE]
====
. Ou: “proclamadores das boas novas”.
====

[[v49-4-12]]

^<<v49-4-12,12>>^ para o reajustamento^&#42;1^ dos santos, para a obra ministerial, para edificar o corpo do Cristo,

[NOTE]
====
. Ou: “treino”.
====

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos alcancemos a unidade^&#42;1^ da fé e do conhecimento exato do Filho de Deus, o estado de homem adulto,^&#42;2^ alcançando a estatura da plenitude do Cristo.

[NOTE]
====
. Ou: “união”.
. Ou: “homem maduro”.
====

[[v49-4-14]]

^<<v49-4-14,14>>^ Então, já não devemos ser crianças, atirados como que por ondas e levados para lá e para cá por todo o vento de ensinamentos, pela esperteza de homens, pela astúcia de artimanhas enganosas.

[[v49-4-15]]

^<<v49-4-15,15>>^ Mas, dizendo a verdade, cresçamos em todas as coisas, por amor, em direção àquele que é a cabeça, Cristo.

[[v49-4-16]]

^<<v49-4-16,16>>^ Por meio dele, todo o corpo é harmoniosamente unido e coordenado mediante as juntas que suprem o que é necessário. Quando cada membro funciona bem, contribui para o desenvolvimento do corpo, à medida que se edifica a si mesmo em amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ Portanto, digo e exorto-vos no Senhor: não continuem a andar como andam as pessoas das nações, na futilidade^&#42;1^ da sua mente.

[NOTE]
====
. Ou: “no vazio; na vaidade”.
====

[[v49-4-18]]

^<<v49-4-18,18>>^ Elas estão mentalmente em escuridão e apartadas da vida que pertence a Deus, por causa da ignorância que há nelas, por causa da insensibilidade^&#42;1^ do seu coração.

[NOTE]
====
. Lit.: “do endurecimento”.
====

[[v49-4-19]]

^<<v49-4-19,19>>^ Tendo perdido todo o senso moral, entregaram-se à conduta insolente^&#42;1^ para praticar com ganância todo o tipo de impureza.

[NOTE]
====
. Ou: “conduta desavergonhada”. Em grego, asélgeia. Veja o Glossário.
====

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas vocês não aprenderam que o Cristo seja assim,

[[v49-4-21]]

^<<v49-4-21,21>>^ se de facto o ouviram e foram ensinados por meio dele, de acordo com a verdade que está em Jesus.

[[v49-4-22]]

^<<v49-4-22,22>>^ Foi-vos ensinado que devem abandonar a velha personalidade, que está em harmonia com o vosso proceder anterior e que se corrompe segundo os desejos enganosos dela.

[[v49-4-23]]

^<<v49-4-23,23>>^ Continuem a renovar a vossa maneira de pensar^&#42;1^

[NOTE]
====
. Ou: “a força que ativa a vossa mente”. Lit.: “o espírito da vossa mente”.
====

[[v49-4-24]]

^<<v49-4-24,24>>^ e revistam-se da nova personalidade, que foi criada segundo a vontade de Deus, em verdadeira justiça^&#42;1^ e lealdade.

[NOTE]
====
. Veja o Glossário.
====

[[v49-4-25]]

^<<v49-4-25,25>>^ Portanto, visto que abandonaram a mentira, digam a verdade, cada um ao seu próximo, pois somos membros que se pertencem uns aos outros.

[[v49-4-26]]

^<<v49-4-26,26>>^ Fiquem furiosos, mas não pequem; não deixem que o sol se ponha enquanto ainda estiverem furiosos;

[[v49-4-27]]

^<<v49-4-27,27>>^ não deem uma oportunidade^&#42;1^ ao Diabo.

[NOTE]
====
. Ou: “nem deem lugar”.
====

[[v49-4-28]]

^<<v49-4-28,28>>^ Quem furta não furte mais; em vez disso, trabalhe arduamente, fazendo um bom trabalho com as mãos, para que tenha o que partilhar com alguém em necessidade.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não saia da vossa boca nenhuma palavra pervertida^&#42;1^, mas apenas o que for bom para a edificação, conforme a necessidade, para transmitir aos ouvintes o que é benéfico.

[NOTE]
====
. Lit.: “podre”.
====

[[v49-4-30]]

^<<v49-4-30,30>>^ E não entristeçam o espírito santo de Deus, com o qual foram selados para um dia de livramento por meio de resgate.

[[v49-4-31]]

^<<v49-4-31,31>>^ Abandonem todo o tipo de ressentimento, ira, raiva, gritaria e palavras ofensivas, assim como toda a maldade.

[[v49-4-32]]

^<<v49-4-32,32>>^ Mas sejam bondosos uns com os outros, ternamente compassivos, perdoando-se liberalmente uns aos outros, assim como Deus vos perdoou liberalmente por Cristo.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]