include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v49-1-1]]

^<<v49-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, aos santos que estão em Éfeso e são fiéis em união com Cristo Jesus:

[[v49-1-2]]

^<<v49-1-2,2>>^ Que tenham bondade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v49-1-3]]

^<<v49-1-3,3>>^ Louvado seja o Deus e Pai do nosso Senhor Jesus Cristo, pois ele nos abençoou em união com Cristo com todo o tipo de bênçãos espirituais nos lugares celestiais,

[[v49-1-4]]

^<<v49-1-4,4>>^ visto que nos escolheu para estarmos em união com ele^&#42;1^ antes da fundação do mundo, para que fôssemos santos e sem defeito diante dele em amor.

[NOTE]
====
. Isto é, com Cristo.
====

[[v49-1-5]]

^<<v49-1-5,5>>^ Pois ele predeterminou que fôssemos adotados como seus filhos por meio de Jesus Cristo, segundo o seu agrado e a sua vontade,

[[v49-1-6]]

^<<v49-1-6,6>>^ para o louvor da sua gloriosa bondade imerecida, que nos concedeu bondosamente por meio do seu Filho amado.

[[v49-1-7]]

^<<v49-1-7,7>>^ Por intermédio dele, temos o livramento pelo resgate, através do sangue dele, sim, o perdão das nossas falhas, segundo as riquezas da sua bondade imerecida.

[[v49-1-8]]

^<<v49-1-8,8>>^ Ele deu-nos abundantemente esta bondade imerecida em toda a sabedoria e entendimento^&#42;1^

[NOTE]
====
. Ou: “bom senso”.
====

[[v49-1-9]]

^<<v49-1-9,9>>^ por nos revelar o segredo sagrado da sua vontade. Segundo o seu agrado, ele mesmo se propôs

[[v49-1-10]]

^<<v49-1-10,10>>^ a estabelecer uma administração^&#42;1^ quando se completassem os tempos determinados, para reunir todas as coisas no Cristo, as coisas nos céus e as coisas na terra. Sim, nele,

[NOTE]
====
. Ou: “administrar as coisas”.
====

[[v49-1-11]]

^<<v49-1-11,11>>^ com quem estamos em união e fomos designados herdeiros, tendo sido predeterminados segundo o propósito daquele que realiza todas as coisas de acordo com o que ele decide segundo a sua vontade,

[[v49-1-12]]

^<<v49-1-12,12>>^ a fim de que servíssemos para o louvor da sua glória, nós, que fomos os primeiros a ter esperança no Cristo.

[[v49-1-13]]

^<<v49-1-13,13>>^ Mas vocês também passaram a ter esperança nele depois de terem ouvido a palavra da verdade, as boas novas a respeito da vossa salvação. Depois de terem crido, Deus, por meio dele, selou-vos^&#42;1^ com o prometido espírito santo,

[NOTE]
====
. Ou: “foram selados”.
====

[[v49-1-14]]

^<<v49-1-14,14>>^ que é uma garantia^&#42;1^ da nossa herança, com o objetivo de livrar a propriedade do próprio Deus por um resgate, para o Seu glorioso louvor.

[NOTE]
====
. Ou: “uma entrada (um sinal); um penhor daquilo que virá”.
====

[[v49-1-15]]

^<<v49-1-15,15>>^ É por isso que eu também, desde que ouvi falar da vossa fé no Senhor Jesus e do amor que demonstram para com todos os santos,

[[v49-1-16]]

^<<v49-1-16,16>>^ nunca deixo de dar graças por vocês. Continuo a mencionar-vos nas minhas orações,

[[v49-1-17]]

^<<v49-1-17,17>>^ para que o Deus do nosso Senhor Jesus Cristo, o Pai glorioso, vos dê um espírito de sabedoria e de revelação, referente ao conhecimento exato dele.

[[v49-1-18]]

^<<v49-1-18,18>>^ Ele iluminou os olhos do vosso coração, para que saibam a que esperança vos chamou, quais são as gloriosas riquezas que ele reserva como herança para os santos

[[v49-1-19]]

^<<v49-1-19,19>>^ e como é extraordinária a grandeza do seu poder em nós, crentes. Essa grandeza é demonstrada na atuação da sua poderosa força,

[[v49-1-20]]

^<<v49-1-20,20>>^ que ele usou para com Cristo quando o levantou dentre os mortos e o sentou à sua direita nos lugares celestiais,

[[v49-1-21]]

^<<v49-1-21,21>>^ muito acima de todo o governo, autoridade, poder, domínio e todo o nome que seja dado, não só neste sistema de coisas,^&#42;1^ mas também no que virá.

[NOTE]
====
. Ou: “nesta época”. Veja o Glossário.
====

[[v49-1-22]]

^<<v49-1-22,22>>^ Ele também lhe sujeitou todas as coisas debaixo dos pés e fê-lo cabeça sobre todas as coisas no que se refere à congregação,

[[v49-1-23]]

^<<v49-1-23,23>>^ que é o seu corpo, a plenitude daquele que em tudo completa todas as coisas.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]