include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v49-3-1]]

^<<v49-3-1,1>>^ Por isso, eu, Paulo, o prisioneiro por causa de Cristo Jesus em vosso benefício, pessoas das nações . . .^&#42;1^

[NOTE]
====
. A frase parece continuar no v. 14.
====

[[v49-3-2]]

^<<v49-3-2,2>>^ Suponho que ouviram dizer que recebi a responsabilidade de administrar a bondade imerecida de Deus em vosso benefício,

[[v49-3-3]]

^<<v49-3-3,3>>^ que o segredo sagrado me foi dado a conhecer por meio de uma revelação, conforme já escrevi resumidamente.

[[v49-3-4]]

^<<v49-3-4,4>>^ Assim, ao lerem isto, podem aperceber-se da compreensão que eu tenho do segredo sagrado do Cristo.

[[v49-3-5]]

^<<v49-3-5,5>>^ Noutras gerações, este segredo não foi dado a conhecer aos filhos dos homens assim como agora foi revelado por espírito aos seus santos apóstolos e profetas:

[[v49-3-6]]

^<<v49-3-6,6>>^ que pessoas das nações seriam, em união com Cristo Jesus e por meio das boas novas, co-herdeiros, membros do mesmo corpo e participantes connosco da promessa.

[[v49-3-7]]

^<<v49-3-7,7>>^ Disto tornei-me ministro segundo a dádiva^&#42;1^ da bondade imerecida de Deus, que me foi concedida por meio da atuação do seu poder.

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v49-3-8]]

^<<v49-3-8,8>>^ A mim, alguém menor do que o menor de todos os santos, foi-me concedida esta bondade imerecida, para que eu declarasse às nações as boas novas a respeito das riquezas insondáveis do Cristo

[[v49-3-9]]

^<<v49-3-9,9>>^ e fizesse com que todos vissem a administração do segredo sagrado que durante muito tempo esteve escondido em Deus, que criou todas as coisas.

[[v49-3-10]]

^<<v49-3-10,10>>^ Isso aconteceu para que, agora, por meio da congregação, se desse a conhecer aos governos e às autoridades nos lugares celestiais a grandemente diversificada sabedoria de Deus.

[[v49-3-11]]

^<<v49-3-11,11>>^ Isto está de acordo com o propósito eterno que ele estabeleceu quanto ao Cristo, nosso Senhor Jesus,

[[v49-3-12]]

^<<v49-3-12,12>>^ por intermédio de quem temos esta liberdade no falar e nos podemos aproximar de Deus livremente^&#42;1^ com confiança, por meio da nossa fé em Cristo.^&#42;2^

[NOTE]
====
. Lit.: “e uma aproximação”.
. Lit.: “nele”.
====

[[v49-3-13]]

^<<v49-3-13,13>>^ Portanto, peço-vos que não desistam devido às tribulações que suporto em vosso benefício, pois significam glória para vocês.

[[v49-3-14]]

^<<v49-3-14,14>>^ Por isso, ajoelho-me diante do Pai,

[[v49-3-15]]

^<<v49-3-15,15>>^ a quem toda a família no céu e na terra deve o seu nome.

[[v49-3-16]]

^<<v49-3-16,16>>^ Oro para que ele, por meio da Sua grande glória, vos conceda serem fortalecidos na pessoa que são no íntimo, com poder, através do seu espírito,

[[v49-3-17]]

^<<v49-3-17,17>>^ e para que, pela vossa fé, o Cristo more no vosso coração com amor. Que sejam arraigados e estabelecidos no alicerce,

[[v49-3-18]]

^<<v49-3-18,18>>^ para que, com todos os santos, sejam plenamente capazes de compreender qual é a largura, o comprimento, a altura e a profundidade,

[[v49-3-19]]

^<<v49-3-19,19>>^ e de conhecer o amor do Cristo, que é superior ao conhecimento, a fim de que fiquem cheios de toda a plenitude que Deus dá.

[[v49-3-20]]

^<<v49-3-20,20>>^ E àquele que, segundo o Seu poder que atua em nós, pode fazer infinitamente mais além de tudo o que peçamos ou imaginemos,

[[v49-3-21]]

^<<v49-3-21,21>>^ a ele seja dada a glória por meio da congregação e de Cristo Jesus, por todas as gerações, para todo o sempre. Amém.

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]