include::./index.adoc[]

[[v49-5-0]]
=== Efésios, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v49-5-1]]

^<<v49-5-1,1>>^ Portanto, tornem-se imitadores de Deus, como filhos amados,

[[v49-5-2]]

^<<v49-5-2,2>>^ e continuem a andar em amor, assim como também o Cristo nos amou^&#42;1^ e se entregou por nós^&#42;2^ como oferta e sacrifício, um aroma agradável para Deus.

[NOTE]
====
. Ou, possivelmente: “vos amou”.
. Ou, possivelmente: “vocês”.
====

[[v49-5-3]]

^<<v49-5-3,3>>^ A imoralidade sexual,^&#42;1^ todo o tipo de impureza e a ganância não sejam sequer mencionadas entre vocês, assim como é próprio de pessoas santas,

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v49-5-4]]

^<<v49-5-4,4>>^ nem conduta vergonhosa, nem conversa tola, nem piadas obscenas — coisas que não são apropriadas —; mas, em vez disso, deem graças.

[[v49-5-5]]

^<<v49-5-5,5>>^ Pois vocês sabem e compreendem plenamente o seguinte: ninguém que pratica imoralidade sexual,^&#42;1^ nenhuma pessoa impura, ou gananciosa — que significa ser idólatra — tem qualquer herança no Reino do Cristo e de Deus.

[NOTE]
====
. Veja o Glossário.
====

[[v49-5-6]]

^<<v49-5-6,6>>^ Que ninguém vos engane com palavras vãs, pois, por causa dessas coisas, a ira de Deus vem sobre os filhos da desobediência.

[[v49-5-7]]

^<<v49-5-7,7>>^ Portanto, não sejam parceiros deles;

[[v49-5-8]]

^<<v49-5-8,8>>^ pois, antes, vocês eram escuridão, mas agora são luz em união com o Senhor. Continuem a andar como filhos da luz,

[[v49-5-9]]

^<<v49-5-9,9>>^ pois o fruto da luz consiste em tudo o que é bom, justo e verdadeiro.

[[v49-5-10]]

^<<v49-5-10,10>>^ Certifiquem-se sempre do que agrada ao Senhor

[[v49-5-11]]

^<<v49-5-11,11>>^ e parem de participar nas obras infrutíferas da escuridão; em vez disso, exponham-nas.

[[v49-5-12]]

^<<v49-5-12,12>>^ Pois as coisas que eles fazem em segredo são vergonhosas até mesmo para se mencionar.

[[v49-5-13]]

^<<v49-5-13,13>>^ Mas todas as coisas que são expostas^&#42;1^ são reveladas pela luz, pois tudo o que é revelado é luz.

[NOTE]
====
. Ou: “reprovadas”.
====

[[v49-5-14]]

^<<v49-5-14,14>>^ Por isso se diz: “Acorda, ó tu que dormes, e levanta-te dentre os mortos, e o Cristo irá iluminar-te.”

[[v49-5-15]]

^<<v49-5-15,15>>^ Assim, estejam bem atentos para não andarem como tolos, mas como sábios,

[[v49-5-16]]

^<<v49-5-16,16>>^ usando o vosso tempo do melhor modo possível,^&#42;1^ porque os dias são maus.

[NOTE]
====
. Lit.: “comprando o tempo determinado”.
====

[[v49-5-17]]

^<<v49-5-17,17>>^ Portanto, parem de ser insensatos, mas compreendam qual é a vontade de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v49-5-18]]

^<<v49-5-18,18>>^ Além disso, não se embriaguem com vinho, no qual há devassidão,^&#42;1^ mas fiquem cheios de espírito.

[NOTE]
====
. Ou: “indisciplina”.
====

[[v49-5-19]]

^<<v49-5-19,19>>^ Falem uns aos outros^&#42;1^ com salmos, louvores a Deus e cânticos espirituais, cantando e louvando a Jeová^&#42;2^ no coração,

[NOTE]
====
. Ou, possivelmente: “consigo mesmos”.
. Veja o Ap. A5.
====

[[v49-5-20]]

^<<v49-5-20,20>>^ dando sempre graças por todas as coisas ao nosso Deus e Pai, em nome do nosso Senhor Jesus Cristo.

[[v49-5-21]]

^<<v49-5-21,21>>^ Estejam sujeitos uns aos outros, no temor de Cristo.

[[v49-5-22]]

^<<v49-5-22,22>>^ A esposa esteja sujeita ao marido, como ao Senhor,

[[v49-5-23]]

^<<v49-5-23,23>>^ porque o marido é cabeça da esposa, assim como o Cristo é cabeça da congregação e salvador deste corpo.

[[v49-5-24]]

^<<v49-5-24,24>>^ De facto, assim como a congregação está sujeita ao Cristo, a esposa também deve estar sujeita ao marido, em tudo.

[[v49-5-25]]

^<<v49-5-25,25>>^ Marido, continua a amar a tua esposa, assim como também o Cristo amou a congregação e se entregou por ela

[[v49-5-26]]

^<<v49-5-26,26>>^ para santificar a congregação, purificando-a com o banho de água através da palavra,

[[v49-5-27]]

^<<v49-5-27,27>>^ a fim de apresentá-la a si mesmo em todo o seu esplendor, sem mancha nem ruga, nem qualquer coisa semelhante, mas santa e sem defeito.

[[v49-5-28]]

^<<v49-5-28,28>>^ Do mesmo modo, o marido deve amar a esposa como o seu próprio corpo. O homem que ama a sua esposa, ama-se a si mesmo,

[[v49-5-29]]

^<<v49-5-29,29>>^ pois nenhum homem jamais odiou o seu próprio corpo;^&#42;1^ antes, alimenta-o e cuida dele,^&#42;2^ assim como o Cristo faz com a congregação,

[NOTE]
====
. Lit.: “a própria carne”.
. Ou: “e acalenta-o”.
====

[[v49-5-30]]

^<<v49-5-30,30>>^ porque somos membros do seu corpo.

[[v49-5-31]]

^<<v49-5-31,31>>^ “Por esta razão, o homem deixará o seu pai e a sua mãe e irá apegar-se à^&#42;1^ sua esposa, e os dois serão uma só carne.”

[NOTE]
====
. Ou: “e permanecerá com a”.
====

[[v49-5-32]]

^<<v49-5-32,32>>^ É grande este segredo sagrado. Digo-o, porém, a respeito de Cristo e da congregação.

[[v49-5-33]]

^<<v49-5-33,33>>^ No entanto, que cada um de vocês ame a sua esposa como a si mesmo; por outro lado, a esposa deve ter profundo respeito pelo seu marido.

'''

xref:049-efesios/049-efesios-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-efesios/049-efesios-006.adoc#v49-6-0[Próximo Capítulo &#62;]