include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v37-1-1]]

^<<v37-1-1,1>>^ No segundo ano do rei Dario, no sexto mês, no primeiro dia do mês, o governador de Judá, Zorobabel, filho de Sealtiel, e o sumo sacerdote Josué, filho de Jeozadaque, receberam a seguinte palavra de Jeová, por meio do profeta Ageu:^&#42;1^

[NOTE]
====
. Que significa “nascido numa festividade”.
====

[[v37-1-2]]

^<<v37-1-2,2>>^ “Assim diz Jeová dos exércitos: ‘Este povo diz: “Ainda não chegou o tempo para se construir^&#42;1^ a casa^&#42;2^ de Jeová.”’”

[NOTE]
====
. Ou: “reconstruir”.
. Ou: “o templo”.
====

[[v37-1-3]]

^<<v37-1-3,3>>^ Então, a palavra de Jeová veio novamente por meio do profeta Ageu:

[[v37-1-4]]

^<<v37-1-4,4>>^ “Será que é tempo de morarem nas vossas casas revestidas de painéis, enquanto esta casa está em ruínas?

[[v37-1-5]]

^<<v37-1-5,5>>^ Agora, assim diz Jeová dos exércitos: ‘Prestem atenção aos^&#42;1^ vossos caminhos.

[NOTE]
====
. Ou: “Fixem o coração nos”.
====

[[v37-1-6]]

^<<v37-1-6,6>>^ Vocês semeiam muita semente, mas colhem pouco. Comem, mas não ficam saciados. Bebem, mas não ficam satisfeitos. Vestem roupa, mas não se aquecem. Quem trabalha guarda o seu salário num saco roto.’”

[[v37-1-7]]

^<<v37-1-7,7>>^ “Assim diz Jeová dos exércitos: ‘Prestem atenção aos^&#42;1^ vossos caminhos.’

[NOTE]
====
. Ou: “Fixem o coração nos”.
====

[[v37-1-8]]

^<<v37-1-8,8>>^ “‘Subam à montanha e tragam madeira. Construam a casa, para que eu tenha prazer nela e seja glorificado’, diz Jeová.”

[[v37-1-9]]

^<<v37-1-9,9>>^ “‘Vocês esperaram muito e obtiveram pouco; e, quando trouxeram esse pouco para dentro de casa, eu espalhei-o com um sopro. Porquê?’, diz Jeová dos exércitos. ‘Porque a minha casa está em ruínas, enquanto cada um de vocês está atarefado a cuidar da sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso, os céus acima de vocês retiveram o seu orvalho, e a terra reteve a sua produção.

[[v37-1-11]]

^<<v37-1-11,11>>^ E eu fiz vir uma seca sobre a terra, sobre os montes, sobre os cereais, sobre o vinho novo, sobre o azeite, sobre o que o solo produzia, sobre os humanos e o gado, e sobre todo o trabalho das vossas mãos.’”

[[v37-1-12]]

^<<v37-1-12,12>>^ E Zorobabel, filho de Sealtiel, e o sumo sacerdote Josué, filho de Jeozadaque, e o restante do povo escutaram a voz de Jeová, seu Deus, e as palavras do profeta Ageu, visto que Jeová, seu Deus, o tinha enviado; e o povo começou a temer a Jeová.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então, Ageu, o mensageiro de Jeová, transmitiu ao povo a seguinte mensagem, cumprindo a comissão que tinha recebido de Jeová: “‘Eu estou convosco’, diz Jeová.”

[[v37-1-14]]

^<<v37-1-14,14>>^ E Jeová despertou o espírito do governador de Judá, Zorobabel, filho de Sealtiel, e o espírito do sumo sacerdote Josué, filho de Jeozadaque, e o espírito do restante do povo; e eles vieram e começaram a trabalhar na casa de Jeová dos exércitos, seu Deus.

[[v37-1-15]]

^<<v37-1-15,15>>^ Isto aconteceu no dia 24 do sexto mês, no segundo ano do rei Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]