include::./index.adoc[]

[[v60-3-0]]
=== 1 Pedro, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v60-3-1]]

^<<v60-3-1,1>>^ Da mesma maneira, tu, esposa, sujeita-te ao teu marido, para que, se ele não for obediente à palavra, seja ganho sem palavras, pela conduta da sua esposa,

[[v60-3-2]]

^<<v60-3-2,2>>^ por ter sido testemunha ocular da tua conduta casta com profundo respeito.

[[v60-3-3]]

^<<v60-3-3,3>>^ Que o teu adorno não sejam as coisas exteriores — cabelos entrançados, o uso de enfeites de ouro ou de roupas finas —

[[v60-3-4]]

^<<v60-3-4,4>>^ mas seja a pessoa secreta do coração com o adorno imperecível do espírito calmo e brando, que é de grande valor aos olhos de Deus.

[[v60-3-5]]

^<<v60-3-5,5>>^ Pois era assim que as santas mulheres do passado que esperavam em Deus se adornavam, sujeitando-se aos seus maridos,

[[v60-3-6]]

^<<v60-3-6,6>>^ como Sara, que obedecia a Abraão, chamando-lhe senhor. Tu serás filha dela, desde que continues a fazer o bem e não te deixes dominar pelo medo.

[[v60-3-7]]

^<<v60-3-7,7>>^ Da mesma maneira, tu, marido, continua a morar com a tua esposa segundo o conhecimento.^&#42;1^ Dá-lhe honra como a um vaso mais frágil, o feminino, visto que ela também é herdeira contigo do favor imerecido da vida, para que as tuas orações não sejam impedidas.

[NOTE]
====
. Ou: “mostrando-lhe consideração; compreendendo-a”.
====

[[v60-3-8]]

^<<v60-3-8,8>>^ Por fim, sejam todos unidos na mente,^&#42;1^ tenham empatia, amor fraternal, terna compaixão e humildade.

[NOTE]
====
. Ou: “pensem todos da mesma maneira”.
====

[[v60-3-9]]

^<<v60-3-9,9>>^ Não paguem o mal com o mal, nem o insulto com o insulto. Em vez disso, retribuam com uma bênção, pois foram chamados para este proceder, a fim de herdarem uma bênção.

[[v60-3-10]]

^<<v60-3-10,10>>^ Pois “aquele que ama a vida e quer ver dias felizes deve resguardar a língua do mal e os lábios de dizer mentiras.

[[v60-3-11]]

^<<v60-3-11,11>>^ Que ele se desvie do mal e faça o bem. Que procure a paz e se empenhe por ela.

[[v60-3-12]]

^<<v60-3-12,12>>^ Porque os olhos de Jeová^&#42;1^ estão sobre os justos, e os seus ouvidos escutam as súplicas deles, mas a face de Jeová^&#42;2^ volta-se contra os que fazem coisas más”.

[NOTE]
====
. Veja o Ap. A5.
. Veja o Ap. A5.
====

[[v60-3-13]]

^<<v60-3-13,13>>^ Realmente, quem vos fará mal, se forem zelosos do que é bom?

[[v60-3-14]]

^<<v60-3-14,14>>^ Porém, mesmo que sofram por causa da justiça, serão felizes. No entanto, não temam o que eles temem^&#42;1^ nem fiquem perturbados.

[NOTE]
====
. Ou, possivelmente: “não temam as ameaças deles”.
====

[[v60-3-15]]

^<<v60-3-15,15>>^ Mas santifiquem o Cristo como Senhor no vosso coração, sempre prontos para fazer uma defesa perante todo aquele que vos exigir uma razão para a vossa esperança, fazendo-o, porém, com brandura e profundo respeito.

[[v60-3-16]]

^<<v60-3-16,16>>^ Mantenham uma boa consciência, para que, sempre que falarem contra vocês, aqueles que o fazem fiquem envergonhados por causa da vossa boa conduta como seguidores de Cristo.

[[v60-3-17]]

^<<v60-3-17,17>>^ Pois é melhor sofrerem por fazer o bem, se for da vontade de Deus permiti-lo, do que por fazer o mal.

[[v60-3-18]]

^<<v60-3-18,18>>^ Pois Cristo morreu de uma vez para sempre pelos pecados, um justo pelos injustos, a fim de vos conduzir a Deus. Ele foi morto na carne, mas recebeu vida no espírito.

[[v60-3-19]]

^<<v60-3-19,19>>^ E assim ele foi e pregou aos espíritos em prisão,

[[v60-3-20]]

^<<v60-3-20,20>>^ que tinham sido desobedientes quando Deus esperava pacientemente^&#42;1^ nos dias de Noé, enquanto se construía a arca, na qual poucas pessoas, isto é, oito,^&#42;2^ foram salvas através da água.

[NOTE]
====
. Lit.: “a paciência de Deus esperava”.
. Ou: “oito almas”.
====

[[v60-3-21]]

^<<v60-3-21,21>>^ O batismo, que corresponde a isso, também vos salva agora (não pela remoção da impureza da carne, mas pela solicitação a Deus de uma boa consciência), através da ressurreição de Jesus Cristo.

[[v60-3-22]]

^<<v60-3-22,22>>^ Ele está à direita de Deus, pois foi para o céu; e anjos, autoridades e poderes foram-lhe sujeitos.

'''

xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[Próximo Capítulo &#62;]