include::./index.adoc[]

[[v60-5-0]]
=== 1 Pedro, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v60-5-1]]

^<<v60-5-1,1>>^ Portanto eu, que também sou ancião, testemunha dos sofrimentos do Cristo e participante na glória que será revelada, faço este apelo^&#42;1^ aos anciãos no vosso meio:

[NOTE]
====
. Ou: “dou esta exortação”.
====

[[v60-5-2]]

^<<v60-5-2,2>>^ pastoreiem o rebanho de Deus, que está aos vossos cuidados, servindo como superintendentes^&#42;1^ não por obrigação, mas de boa vontade perante Deus; não por amor ao ganho desonesto, mas com entusiasmo;

[NOTE]
====
. Ou: “vigiando sobre ele cuidadosamente”.
====

[[v60-5-3]]

^<<v60-5-3,3>>^ não dominando sobre os que são a herança de Deus, mas tornando-se exemplos para o rebanho.

[[v60-5-4]]

^<<v60-5-4,4>>^ E, quando o pastor principal tiver sido manifestado, receberão a imperecível coroa de glória.

[[v60-5-5]]

^<<v60-5-5,5>>^ Da mesma maneira, vocês, homens mais jovens, sujeitem-se aos homens mais velhos.^&#42;1^ Porém, revistam-se^&#42;2^ todos de humildade^&#42;3^ uns para com os outros, porque Deus se opõe aos arrogantes, mas concede bondade imerecida aos humildes.

[NOTE]
====
. Ou: “aos anciãos”.
. Ou: “cinjam-se”.
. Ou: “humildade mental”.
====

[[v60-5-6]]

^<<v60-5-6,6>>^ Portanto, humilhem-se sob a mão poderosa de Deus, para que ele vos enalteça no tempo devido,

[[v60-5-7]]

^<<v60-5-7,7>>^ ao passo que lançam sobre ele toda a vossa ansiedade,^&#42;1^ porque ele cuida de vocês.

[NOTE]
====
. Ou: “todas as vossas inquietações; todas as vossas preocupações”.
====

[[v60-5-8]]

^<<v60-5-8,8>>^ Mantenham os sentidos, sejam vigilantes! O vosso adversário, o Diabo, anda à vossa volta como um leão que ruge, procurando a quem devorar.

[[v60-5-9]]

^<<v60-5-9,9>>^ Mas tomem posição contra ele, firmes na fé, sabendo que a inteira fraternidade^&#42;1^ dos vossos irmãos no mundo está a passar pelos mesmos sofrimentos.

[NOTE]
====
. Ou: “associação”.
====

[[v60-5-10]]

^<<v60-5-10,10>>^ Porém, depois de terem sofrido por um pouco, o próprio Deus de toda a bondade imerecida, que vos chamou à Sua eterna glória em união com Cristo, completará o vosso treino. Ele vos fará firmes, ele vos fará fortes, ele vos porá sobre firmes alicerces.

[[v60-5-11]]

^<<v60-5-11,11>>^ Seja d’Ele o poder para sempre. Amém.

[[v60-5-12]]

^<<v60-5-12,12>>^ Por meio de Silvano,^&#42;1^ que considero um irmão fiel, escrevi-vos em poucas palavras para vos encorajar e vos assegurar de que esta é a verdadeira bondade imerecida de Deus. Mantenham-se firmes nela.

[NOTE]
====
. Também chamado Silas.
====

[[v60-5-13]]

^<<v60-5-13,13>>^ Aquela que está em Babilónia, e que foi escolhida como vocês, manda-vos saudações, e também Marcos, meu filho.

[[v60-5-14]]

^<<v60-5-14,14>>^ Cumprimentem-se uns aos outros com um beijo fraterno.^&#42;1^
Que todos vocês, que estão em união com Cristo, tenham paz.

[NOTE]
====
. Lit.: “beijo de amor”.
====

'''

xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[Próximo Capítulo &#62;]