include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v60-1-1]]

^<<v60-1-1,1>>^ Pedro, apóstolo de Jesus Cristo, aos residentes temporários espalhados por Ponto, Galácia, Capadócia, Ásia e Bitínia, aos escolhidos

[[v60-1-2]]

^<<v60-1-2,2>>^ segundo a presciência de Deus, o Pai, santificados pelo espírito, com o objetivo de serem obedientes e de receberem a aspersão do sangue de Jesus Cristo.
Que tenham cada vez mais bondade imerecida e paz.

[[v60-1-3]]

^<<v60-1-3,3>>^ Louvado seja o Deus e Pai do nosso Senhor Jesus Cristo, pois, segundo a sua grande misericórdia, deu-nos um novo nascimento para uma esperança viva por meio da ressurreição de Jesus Cristo dentre os mortos,

[[v60-1-4]]

^<<v60-1-4,4>>^ para uma herança imperecível,^&#42;1^ sem mancha e que não se apaga. Está reservada nos céus para vocês,

[NOTE]
====
. Ou: “incorruptível”.
====

[[v60-1-5]]

^<<v60-1-5,5>>^ que estão a ser resguardados pelo poder de Deus, por meio da fé, para uma salvação pronta para ser revelada no tempo do fim.

[[v60-1-6]]

^<<v60-1-6,6>>^ Por causa disso, vocês alegram-se muito, ainda que seja necessário, por um tempo, que fiquem aflitos devido a várias provações,

[[v60-1-7]]

^<<v60-1-7,7>>^ para que a qualidade provada da vossa fé, que tem muito mais valor do que o ouro perecível, apesar de ter sido provado^&#42;1^ por fogo, seja considerada razão para louvor, glória e honra na revelação de Jesus Cristo.

[NOTE]
====
. Ou: “refinado”.
====

[[v60-1-8]]

^<<v60-1-8,8>>^ Embora nunca o tenham visto, vocês amam-no. Embora não o vejam agora, exercem fé nele e alegram-se muito com uma alegria indescritível e gloriosa,

[[v60-1-9]]

^<<v60-1-9,9>>^ à medida que alcançam o alvo da vossa fé: a vossa salvação.^&#42;1^

[NOTE]
====
. Ou: “a salvação das vossas almas”.
====

[[v60-1-10]]

^<<v60-1-10,10>>^ Sobre esta salvação, os profetas que profetizaram a respeito da bondade imerecida que vos estava destinada fizeram diligente investigação e cuidadosa pesquisa.

[[v60-1-11]]

^<<v60-1-11,11>>^ Eles procuravam descobrir o tempo específico e as circunstâncias^&#42;1^ que o espírito que estava neles indicava a respeito de Cristo, quando dava testemunho antecipado sobre os sofrimentos que Cristo teria de suportar e sobre a glória que se seguiria.

[NOTE]
====
. Ou: “e a época”.
====

[[v60-1-12]]

^<<v60-1-12,12>>^ Foi-lhes revelado que estavam a servir não a si mesmos, mas a vocês, no que se refere às coisas que agora vos foram anunciadas por aqueles que vos declararam as boas novas com espírito santo enviado do céu. São estas as coisas que os anjos têm grande desejo de entender.^&#42;1^

[NOTE]
====
. Ou: “olhar de perto”.
====

[[v60-1-13]]

^<<v60-1-13,13>>^ Por isso, preparem a mente para atividade intensa; mantenham inteiramente os sentidos; ponham a esperança na bondade imerecida que vos será trazida na revelação de Jesus Cristo.

[[v60-1-14]]

^<<v60-1-14,14>>^ Como filhos obedientes, parem de ser moldados pelos desejos que tinham antes na vossa ignorância,

[[v60-1-15]]

^<<v60-1-15,15>>^ mas, assim como o Santo que vos chamou, tornem-se santos em toda a vossa conduta,

[[v60-1-16]]

^<<v60-1-16,16>>^ pois está escrito: “Sejam santos, porque eu sou santo.”

[[v60-1-17]]

^<<v60-1-17,17>>^ E se invocam o Pai, que julga imparcialmente segundo a obra de cada um, comportem-se com temor durante o tempo em que são residentes temporários.

[[v60-1-18]]

^<<v60-1-18,18>>^ Pois sabem que não foi com coisas perecíveis, com prata ou ouro, que foram libertados^&#42;1^ do vosso modo de vida fútil, que vos foi transmitido pelos vossos antepassados.^&#42;2^

[NOTE]
====
. Lit.: “resgatados; remidos”.
. Ou: “por tradição”.
====

[[v60-1-19]]

^<<v60-1-19,19>>^ Mas foi com sangue precioso, como o de um cordeiro sem defeito e sem mancha, o de Cristo.

[[v60-1-20]]

^<<v60-1-20,20>>^ É verdade que ele foi conhecido antes da fundação do mundo, mas foi manifestado no fim dos tempos por vossa causa.

[[v60-1-21]]

^<<v60-1-21,21>>^ Por meio dele vocês creem em Deus, aquele que o levantou dentre os mortos e lhe deu glória, para que a vossa fé e esperança estejam em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Agora que se purificaram^&#42;1^ pela vossa obediência à verdade, tendo como resultado o amor fraternal sem hipocrisia, amem-se uns aos outros intensamente, de coração.

[NOTE]
====
. Ou: “que purificaram as vossas almas”.
====

[[v60-1-23]]

^<<v60-1-23,23>>^ Pois foi-vos dado um novo nascimento, não por semente perecível, mas por semente imperecível,^&#42;1^ por meio da palavra do Deus vivente, o qual permanece para sempre.

[NOTE]
====
. Isto é, semente capaz de reproduzir, ou de dar fruto.
====

[[v60-1-24]]

^<<v60-1-24,24>>^ Pois “todos os homens são^&#42;1^ como a erva, e toda a sua glória é como a flor do campo; a erva seca e a flor cai,

[NOTE]
====
. Lit.: “toda a carne é”.
====

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a declaração^&#42;1^ de Jeová^&#42;2^ permanece para sempre”. E esta “declaração”^&#42;3^ são as boas novas que vos foram anunciadas.

[NOTE]
====
. Ou: “palavra”.
. Veja o Ap. A5.
. Ou: “palavra”.
====

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]