include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v60-4-1]]

^<<v60-4-1,1>>^ Visto que Cristo sofreu na carne, armem-se também da mesma disposição mental;^&#42;1^ porque a pessoa que sofre na carne abandonou os pecados,

[NOTE]
====
. Ou: “resolução; determinação”.
====

[[v60-4-2]]

^<<v60-4-2,2>>^ a fim de viver o resto do seu tempo na carne não mais para os desejos dos homens, mas para a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ Pois, já bastou o tempo que gastaram no passado a fazer a vontade das nações, quando viviam em conduta insolente,^&#42;1^ em paixões desenfreadas, em embriaguez, em festas descontroladas,^&#42;2^ em bebedeiras e em idolatrias ilícitas.

[NOTE]
====
. Ou: “atos de conduta desavergonhada”. Plural da palavra grega asélgeia. Veja o Glossário.
. Ou: “em festanças”.
====

[[v60-4-4]]

^<<v60-4-4,4>>^ Eles ficam intrigados porque vocês não continuam a correr com eles no mesmo proceder decadente de devassidão, e por isso falam mal de vocês.

[[v60-4-5]]

^<<v60-4-5,5>>^ Mas estas pessoas prestarão contas àquele que está pronto para julgar os vivos e os mortos.

[[v60-4-6]]

^<<v60-4-6,6>>^ De facto, é por isso que as boas novas também foram declaradas aos mortos, para que, embora sejam julgados na carne do ponto de vista dos homens, vivam em harmonia com o espírito do ponto de vista de Deus.

[[v60-4-7]]

^<<v60-4-7,7>>^ Mas está próximo o fim de todas as coisas. Portanto, sejam sensatos e sejam vigilantes^&#42;1^ quanto às orações.

[NOTE]
====
. Ou: “e fiquem alertas; e fiquem despertos”.
====

[[v60-4-8]]

^<<v60-4-8,8>>^ Acima de tudo, tenham intenso amor uns pelos outros, porque o amor cobre uma multidão de pecados.

[[v60-4-9]]

^<<v60-4-9,9>>^ Sejam hospitaleiros uns com os outros, sem resmungar.

[[v60-4-10]]

^<<v60-4-10,10>>^ Conforme cada um recebeu um dom, use-o para servir os outros como bom administrador da bondade imerecida de Deus, que é expressa de vários modos.

[[v60-4-11]]

^<<v60-4-11,11>>^ Se alguém fala, que o faça como quem fala as proclamações de Deus; se alguém serve, que o faça como quem depende da força que Deus fornece; para que, em todas as coisas, Deus seja glorificado por meio de Jesus Cristo. A glória e o poder são dele para todo o sempre. Amém.

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não se surpreendam com as duras^&#42;1^ provações que estão a passar, como se algo estranho vos estivesse a acontecer.

[NOTE]
====
. Ou: “ardentes”.
====

[[v60-4-13]]

^<<v60-4-13,13>>^ Pelo contrário, continuem a alegrar-se na medida em que participam dos sofrimentos do Cristo, para que também se alegrem e fiquem cheios de alegria durante a revelação da sua glória.

[[v60-4-14]]

^<<v60-4-14,14>>^ Se estiverem a ser desonrados^&#42;1^ por causa do nome de Cristo, são felizes, porque o espírito de glória, sim, o espírito de Deus, está a repousar sobre vocês.

[NOTE]
====
. Ou: “insultados”.
====

[[v60-4-15]]

^<<v60-4-15,15>>^ No entanto, que nenhum de vocês sofra como assassino, ladrão, malfeitor ou intrometido nos assuntos dos outros.

[[v60-4-16]]

^<<v60-4-16,16>>^ Mas, se alguém sofre como cristão, não se envergonhe, mas continue a glorificar a Deus ao levar este nome.

[[v60-4-17]]

^<<v60-4-17,17>>^ Pois este é o tempo determinado para o julgamento começar com a casa de Deus. Ora, se começa primeiro connosco, qual será o fim daqueles que não são obedientes às boas novas de Deus?

[[v60-4-18]]

^<<v60-4-18,18>>^ “E, se o justo está a ser salvo com dificuldade, o que acontecerá ao ímpio e ao pecador?”

[[v60-4-19]]

^<<v60-4-19,19>>^ Assim, que aqueles que estão a sofrer em harmonia com a vontade de Deus se entreguem^&#42;1^ aos cuidados de um Criador fiel, ao passo que praticam o bem.

[NOTE]
====
. Ou: “entreguem as suas almas”.
====

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]