include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo a verdade em Cristo; não estou a mentir, visto que a minha consciência dá testemunho comigo, em espírito santo:

[[v45-9-2]]

^<<v45-9-2,2>>^ de que tenho uma grande tristeza e uma dor incessante no coração.

[[v45-9-3]]

^<<v45-9-3,3>>^ Pois desejaria que eu mesmo fosse separado do Cristo como o amaldiçoado em favor dos meus irmãos, os meus parentes segundo a carne,

[[v45-9-4]]

^<<v45-9-4,4>>^ os israelitas. A eles pertencem a adoção como filhos, a glória, os pactos, a concessão da Lei, o serviço sagrado e as promessas.

[[v45-9-5]]

^<<v45-9-5,5>>^ A eles pertencem os patriarcas e deles descendeu o Cristo segundo a carne. Deus, que está sobre tudo, seja louvado para sempre. Amém.

[[v45-9-6]]

^<<v45-9-6,6>>^ No entanto, não é que a palavra de Deus tenha falhado. Pois nem todos os que são descendentes de Israel são realmente “Israel”.

[[v45-9-7]]

^<<v45-9-7,7>>^ Nem todos eles são filhos por serem descendência^&#42;1^ de Abraão; em vez disso: “O que será chamado tua descendência^&#42;2^ virá por meio de Isaque.”

[NOTE]
====
. Lit.: “semente”.
. Lit.: “semente”.
====

[[v45-9-8]]

^<<v45-9-8,8>>^ Quer dizer, os filhos na carne não são realmente os filhos de Deus, mas os filhos da^&#42;1^ promessa é que são considerados a descendência.^&#42;2^

[NOTE]
====
. Ou: “pela”.
. Lit.: “semente”.
====

[[v45-9-9]]

^<<v45-9-9,9>>^ Pois a palavra da promessa era a seguinte: “Nesta altura virei e Sara já terá um filho.”

[[v45-9-10]]

^<<v45-9-10,10>>^ Isto aconteceu não apenas naquela ocasião, mas também quando Rebeca concebeu filhos^&#42;1^ de um só homem, Isaque, nosso antepassado;

[NOTE]
====
. Ou: “gémeos”.
====

[[v45-9-11]]

^<<v45-9-11,11>>^ pois, quando os filhos ainda não tinham nascido nem praticado nada de bom ou de mau — para que o propósito de Deus a respeito da escolha continuasse a depender não de obras, mas d’Aquele que chama —,

[[v45-9-12]]

^<<v45-9-12,12>>^ Deus disse-lhe: “O mais velho será escravo do mais novo.”

[[v45-9-13]]

^<<v45-9-13,13>>^ Assim como está escrito: “Eu amei Jacó, mas odiei Esaú.”

[[v45-9-14]]

^<<v45-9-14,14>>^ O que diremos então? Há injustiça da parte de Deus? Certamente que não!

[[v45-9-15]]

^<<v45-9-15,15>>^ Pois ele diz a Moisés: “Terei misericórdia de quem eu tiver misericórdia, e terei compaixão de quem eu tiver compaixão.”

[[v45-9-16]]

^<<v45-9-16,16>>^ Portanto, isto não depende da vontade da pessoa ou do seu esforço,^&#42;1^ mas de Deus, que tem misericórdia.

[NOTE]
====
. Lit.: “nem daquele que deseja, nem daquele que corre”.
====

[[v45-9-17]]

^<<v45-9-17,17>>^ Pois certa passagem das Escrituras diz ao Faraó: “Foi exatamente por esta razão que te deixei permanecer: para que, no teu caso, eu mostre o meu poder e para que o meu nome seja declarado em toda a terra.”

[[v45-9-18]]

^<<v45-9-18,18>>^ Portanto, ele tem misericórdia de quem quiser, mas deixa ficar obstinado quem quiser.

[[v45-9-19]]

^<<v45-9-19,19>>^ Hás de dizer-me, então: “Porque é que ele ainda encontra falhas nas pessoas? Pois quem pode ir contra a sua vontade?”

[[v45-9-20]]

^<<v45-9-20,20>>^ Mas quem és tu, ó homem, para discutires com Deus? Será que a coisa moldada diz àquele que a moldou: “Porque é que me fizeste assim?”

[[v45-9-21]]

^<<v45-9-21,21>>^ O quê? Será que o oleiro não tem autoridade sobre o barro, para fazer da mesma massa um vaso para uso honroso e outro para uso desonroso?

[[v45-9-22]]

^<<v45-9-22,22>>^ Que diremos, pois, se Deus, mesmo querendo demonstrar a sua ira e dar a conhecer o seu poder, tolerou com muita paciência os vasos da ira, preparados para a destruição?

[[v45-9-23]]

^<<v45-9-23,23>>^ E que dizer se ele o fez para dar a conhecer as riquezas da sua glória nos vasos de misericórdia, que ele preparou antecipadamente para a glória,

[[v45-9-24]]

^<<v45-9-24,24>>^ isto é, em nós, os que ele chamou, não somente dentre os judeus, mas também dentre as nações?

[[v45-9-25]]

^<<v45-9-25,25>>^ É conforme ele também diz em Oseias: “Aos que não são do meu povo, eu chamarei ‘meu povo’; e àquela que não era amada, ‘amada’.

[[v45-9-26]]

^<<v45-9-26,26>>^ E, no lugar onde lhes foi dito: ‘Vocês não são o meu povo’, ali serão chamados ‘filhos do Deus vivente’.”

[[v45-9-27]]

^<<v45-9-27,27>>^ Além disso, Isaías clama a respeito de Israel: “Embora o número dos filhos de Israel seja como a areia do mar, apenas o restante será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Pois Jeová^&#42;1^ exigirá uma prestação de contas dos habitantes da terra, completa e sem demora.”^&#42;2^

[NOTE]
====
. Veja o Ap. A5.
. Ou: “executando-a rapidamente”. Lit.: “concluindo e abreviando”.
====

[[v45-9-29]]

^<<v45-9-29,29>>^ Também, conforme Isaías predisse: “Se Jeová^&#42;1^ dos exércitos não nos tivesse deixado uma descendência,^&#42;2^ teríamos ficado como Sodoma, e iríamos tornar-nos semelhantes a Gomorra.”

[NOTE]
====
. Veja o Ap. A5.
. Lit.: “semente”.
====

[[v45-9-30]]

^<<v45-9-30,30>>^ O que diremos então? Que pessoas das nações, embora não se empenhassem pela justiça, alcançaram a justiça, a justiça que resulta da fé;

[[v45-9-31]]

^<<v45-9-31,31>>^ mas Israel, embora se empenhasse por uma lei de justiça, não alcançou essa lei.

[[v45-9-32]]

^<<v45-9-32,32>>^ Porque não? Porque se empenharam por ela não por meio da fé, mas como se a pudessem alcançar por meio de obras. Tropeçaram na “pedra de tropeço”,

[[v45-9-33]]

^<<v45-9-33,33>>^ conforme está escrito: “Vejam! Ponho em Sião uma pedra de tropeço e uma rocha que faz cair,^&#42;1^ mas quem basear nela a sua fé não ficará dececionado.”

[NOTE]
====
. Ou: “rocha de ofensa”.
====

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]