include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-6-1]]

^<<v45-6-1,1>>^ O que diremos então? Continuaremos no pecado para que a bondade imerecida aumente?

[[v45-6-2]]

^<<v45-6-2,2>>^ Certamente que não! Visto que morremos em relação ao pecado, como é que ainda continuamos a viver nele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Ou não sabem que todos nós, os que fomos batizados em Cristo Jesus, fomos batizados na sua morte?

[[v45-6-4]]

^<<v45-6-4,4>>^ Portanto, fomos sepultados com ele por meio do nosso batismo na sua morte, a fim de que, assim como Cristo foi levantado dentre os mortos pelo poder glorioso^&#42;1^ do Pai, assim também nós vivamos uma vida nova.^&#42;2^

[NOTE]
====
. Lit.: “da glória”.
. Ou: “andemos numa novidade de vida”.
====

[[v45-6-5]]

^<<v45-6-5,5>>^ Se ficámos unidos a ele na semelhança da sua morte, certamente ficaremos também unidos a ele na semelhança da sua ressurreição.

[[v45-6-6]]

^<<v45-6-6,6>>^ Pois sabemos que a nossa velha personalidade foi pregada na estaca com ele a fim de que o nosso corpo pecaminoso perdesse o seu poder, e assim não continuássemos a ser escravos do pecado.

[[v45-6-7]]

^<<v45-6-7,7>>^ Pois quem morreu foi absolvido^&#42;1^ do seu pecado.

[NOTE]
====
. Ou: “livrado; perdoado”.
====

[[v45-6-8]]

^<<v45-6-8,8>>^ Além do mais, se morremos com Cristo, cremos que também viveremos com ele.

[[v45-6-9]]

^<<v45-6-9,9>>^ Pois sabemos que Cristo, agora que foi levantado dentre os mortos, já não morre. A morte já não domina sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ Pois a morte que ele morreu, ele morreu de uma vez para sempre em relação ao pecado,^&#42;1^ mas a vida que ele vive, ele vive em relação a Deus.

[NOTE]
====
. Isto é, para acabar com o pecado.
====

[[v45-6-11]]

^<<v45-6-11,11>>^ Assim também, considerem-se mortos em relação ao pecado, mas vivos em relação a Deus, por meio de Cristo Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Portanto, não deixem que o pecado continue a reinar nos vossos corpos mortais, levando-vos a obedecer aos seus desejos.^&#42;1^

[NOTE]
====
. Isto é, aos desejos do corpo.
====

[[v45-6-13]]

^<<v45-6-13,13>>^ Nem continuem a apresentar os vossos corpos^&#42;1^ ao pecado como armas da injustiça, mas apresentem-se a Deus como pessoas que passaram da morte para a vida. Apresentem também os vossos corpos^&#42;2^ a Deus como armas da justiça.

[NOTE]
====
. Lit.: “membros”.
. Lit.: “membros”.
====

[[v45-6-14]]

^<<v45-6-14,14>>^ Pois o pecado não vos deve dominar, visto que não estão debaixo de lei, mas debaixo de bondade imerecida.

[[v45-6-15]]

^<<v45-6-15,15>>^ O que concluímos então? Cometeremos pecado, já que não estamos debaixo de lei, mas debaixo de bondade imerecida? Certamente que não!

[[v45-6-16]]

^<<v45-6-16,16>>^ Não sabem que, se se apresentam a alguém como escravos, para lhe obedecer, são escravos daquele a quem obedecem — quer do pecado, que leva à morte, quer da obediência, que leva à justiça?

[[v45-6-17]]

^<<v45-6-17,17>>^ Mas graças sejam dadas a Deus, pois, embora no passado vocês tenham sido escravos do pecado, tornaram-se obedientes de coração ao padrão de ensinamento a que foram entregues.

[[v45-6-18]]

^<<v45-6-18,18>>^ Sim, uma vez que foram libertos do pecado, tornaram-se escravos da justiça.

[[v45-6-19]]

^<<v45-6-19,19>>^ Estou a falar em termos humanos por causa da fraqueza da vossa carne; pois, assim como apresentaram os vossos membros como escravos à impureza e ao que é contra a lei, resultando no que é contra a lei, apresentem agora os vossos membros como escravos à justiça, o que levará à santidade.

[[v45-6-20]]

^<<v45-6-20,20>>^ Pois, quando eram escravos do pecado, estavam livres no que toca à justiça.

[[v45-6-21]]

^<<v45-6-21,21>>^ Quais eram então os frutos que produziam naquele tempo? Coisas das quais agora se envergonham. Pois o fim dessas coisas é a morte.

[[v45-6-22]]

^<<v45-6-22,22>>^ No entanto, agora que foram libertos do pecado e se tornaram escravos de Deus, o fruto que estão a produzir é a santidade,^&#42;1^ e o fim será a vida eterna.

[NOTE]
====
. Ou: “estão a produzir fruto ao modo da santidade”.
====

[[v45-6-23]]

^<<v45-6-23,23>>^ Pois o salário pago pelo pecado é a morte, mas a dádiva que Deus dá é a vida eterna por Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]