include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-15-1]]

^<<v45-15-1,1>>^ Mas nós, que somos fortes, devemos suportar as fraquezas dos que não são fortes, e não agradar-nos a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Que cada um de nós agrade ao seu próximo para o seu bem, para o edificar.

[[v45-15-3]]

^<<v45-15-3,3>>^ Pois nem mesmo o Cristo se agradou a si mesmo, mas, assim como está escrito: “Os insultos daqueles que te insultam caem sobre mim.”

[[v45-15-4]]

^<<v45-15-4,4>>^ Pois todas as coisas escritas anteriormente foram escritas para a nossa instrução, para que, por meio da nossa perseverança e pelo consolo das Escrituras, tivéssemos esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ Que o Deus que dá perseverança e consolo vos conceda terem entre vocês a mesma atitude que Cristo Jesus teve,

[[v45-15-6]]

^<<v45-15-6,6>>^ para que, unidos e a uma só voz,^&#42;1^ glorifiquem ao Deus e Pai do nosso Senhor Jesus Cristo.

[NOTE]
====
. Lit.: “boca”.
====

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, acolham-se^&#42;1^ uns aos outros, assim como o Cristo também vos acolheu, visando glória para Deus.

[NOTE]
====
. Ou: “aceitem-se”.
====

[[v45-15-8]]

^<<v45-15-8,8>>^ Pois digo-vos que Cristo se tornou servo^&#42;1^ dos circuncisos para mostrar a veracidade de Deus e confirmar as promessas que Ele fez aos antepassados deles,

[NOTE]
====
. Ou: “ministro”.
====

[[v45-15-9]]

^<<v45-15-9,9>>^ e para que as nações glorificassem a Deus pela Sua misericórdia. Assim como está escrito: “É por isso que te reconhecerei abertamente entre as nações e ao teu nome cantarei louvores.”

[[v45-15-10]]

^<<v45-15-10,10>>^ E ele diz também: “Alegrem-se, nações, com o seu povo.”

[[v45-15-11]]

^<<v45-15-11,11>>^ E ainda: “Louvem a Jeová,^&#42;1^ todas as nações, e que todos os povos o louvem.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v45-15-12]]

^<<v45-15-12,12>>^ E Isaías diz também: “Haverá a raiz de Jessé, aquele que surgirá para governar as nações; nele as nações basearão a sua esperança.”

[[v45-15-13]]

^<<v45-15-13,13>>^ Que o Deus que dá esperança vos encha de toda a alegria e paz por meio da vossa confiança nele, para que transbordem^&#42;1^ de esperança pelo poder do espírito santo.

[NOTE]
====
. Ou: “tenham abundância”.
====

[[v45-15-14]]

^<<v45-15-14,14>>^ Pessoalmente, estou convencido a vosso respeito, meus irmãos, de que vocês mesmos também estão cheios de coisas boas, cheios de todo o conhecimento, e de que são capazes de se aconselharem^&#42;1^ uns aos outros.

[NOTE]
====
. Ou: “instruírem”.
====

[[v45-15-15]]

^<<v45-15-15,15>>^ No entanto, escrevi-vos com bastante franqueza sobre alguns pontos, para que se lembrem deles novamente. Faço-o por causa da bondade imerecida que me foi concedida por Deus

[[v45-15-16]]

^<<v45-15-16,16>>^ para que eu fosse servo^&#42;1^ de Cristo Jesus a favor das nações. Estou ocupado na obra santa das boas novas de Deus, a fim de que as nações sejam uma oferta aceitável, santificada com espírito santo.

[NOTE]
====
. Ou: “servo público”.
====

[[v45-15-17]]

^<<v45-15-17,17>>^ Portanto, tenho motivos para me orgulhar em Cristo Jesus no meu serviço a Deus.^&#42;1^

[NOTE]
====
. Ou: “quanto às coisas referentes a Deus”.
====

[[v45-15-18]]

^<<v45-15-18,18>>^ Pois não me atreverei a falar de coisa alguma a não ser daquilo que Cristo realizou por meu intermédio para que as nações fossem obedientes. Ele agiu através das minhas palavras e ações,

[[v45-15-19]]

^<<v45-15-19,19>>^ pelo poder de sinais e milagres^&#42;1^ e pelo poder do espírito de Deus; assim, desde Jerusalém e por todo o lado^&#42;2^ até ao Ilírico, preguei cabalmente as boas novas acerca do Cristo.

[NOTE]
====
. Ou: “portentos”.
. Ou: “e num circuito”.
====

[[v45-15-20]]

^<<v45-15-20,20>>^ Deste modo, fiz o possível para não declarar as boas novas nos lugares onde o nome de Cristo já fosse conhecido, para não construir sobre o alicerce de outra pessoa;

[[v45-15-21]]

^<<v45-15-21,21>>^ mas, assim como está escrito: “Aqueles que nunca tiveram notícias sobre ele verão, e os que não tinham ouvido entenderão.”

[[v45-15-22]]

^<<v45-15-22,22>>^ É por isso que fui impedido muitas vezes de vos ir visitar.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas, agora, já não tenho território virgem nestas regiões e há muitos^&#42;1^ anos que estou ansioso para ir visitar-vos.

[NOTE]
====
. Ou, possivelmente: “alguns”.
====

[[v45-15-24]]

^<<v45-15-24,24>>^ Por isso, quando eu viajar para Espanha, espero ver-vos e ser acompanhado por vocês durante parte do caminho, depois de primeiro ter desfrutado um pouco da vossa companhia.

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas, agora, estou de partida para Jerusalém para servir os santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Pois os irmãos da Macedónia e os da Acaia partilharam de boa vontade as suas coisas, fazendo uma contribuição para os pobres entre os santos em Jerusalém.

[[v45-15-27]]

^<<v45-15-27,27>>^ Sim, eles fizeram-no de boa vontade, e de facto eram-lhes devedores; pois, se as nações participaram das coisas espirituais deles, elas também têm o dever de os servir com as suas coisas materiais.

[[v45-15-28]]

^<<v45-15-28,28>>^ Assim, depois de ter terminado de fazer isto e de lhes ter entregado esta contribuição^&#42;1^ em segurança, partirei para Espanha e irei visitar-vos no caminho.

[NOTE]
====
. Lit.: “este fruto”.
====

[[v45-15-29]]

^<<v45-15-29,29>>^ Além disso, sei que, quando vos for visitar, chegarei com uma plena medida de bênçãos de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Exorto-vos, irmãos, por meio do nosso Senhor Jesus Cristo e pelo amor do espírito, que se esforcem comigo em orações a Deus por mim,

[[v45-15-31]]

^<<v45-15-31,31>>^ para que eu seja livrado dos descrentes na Judeia e para que o meu serviço^&#42;1^ a favor de Jerusalém seja bem aceite pelos santos.

[NOTE]
====
. Ou: “ministério”.
====

[[v45-15-32]]

^<<v45-15-32,32>>^ Assim, pela vontade de Deus, irei visitar-vos com alegria e serei reanimado convosco.

[[v45-15-33]]

^<<v45-15-33,33>>^ Que o Deus que dá paz esteja convosco. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]