include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-13-1]]

^<<v45-13-1,1>>^ Que todos estejam sujeitos^&#42;1^ às autoridades superiores, pois não há autoridade sem a permissão de Deus; as autoridades existentes foram colocadas por Deus nas suas posições relativas.

[NOTE]
====
. Ou: “Que todas as almas estejam sujeitas”.
====

[[v45-13-2]]

^<<v45-13-2,2>>^ Portanto, quem se opõe à autoridade opõe-se à ordem estabelecida por Deus;^&#42;1^ os que se opõem a ela trarão condenação sobre si mesmos.

[NOTE]
====
. Ou: “ao arranjo de Deus”.
====

[[v45-13-3]]

^<<v45-13-3,3>>^ Pois os governantes não são temidos pelos que praticam boas ações, mas pelos que praticam o que é mau. Queres ficar livre do medo da autoridade? Faz sempre o bem, e receberás o seu louvor;

[[v45-13-4]]

^<<v45-13-4,4>>^ pois ela é serva^&#42;1^ de Deus para ti, para o teu bem. Mas, se fazes o que é mau, fica com medo, porque não é sem motivo que a autoridade traz a espada. Ela está ao serviço^&#42;2^ de Deus, para executar vingança e expressar ira^&#42;3^ contra quem pratica o que é mau.

[NOTE]
====
. Ou: “é ministra”.
. Ou: “é ministra”.
. Ou: “trazer punição”.
====

[[v45-13-5]]

^<<v45-13-5,5>>^ Portanto, é necessário que estejam em sujeição, não só por causa dessa ira, mas também por causa da vossa consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ É por isso que vocês também pagam impostos; porque eles estão ao serviço^&#42;1^ de Deus e prestam constantemente este serviço.

[NOTE]
====
. Ou: “são servos públicos”.
====

[[v45-13-7]]

^<<v45-13-7,7>>^ Deem a todos o que lhes é devido: a quem exigir imposto, o imposto; a quem exigir tributo, o tributo; a quem exigir temor, tal temor; a quem exigir honra, tal honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ Não devam nada a ninguém, a não ser amarem-se uns aos outros, pois quem ama o seu próximo cumpre a Lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois os mandamentos — “não cometas adultério, não assassines, não furtes, não cobices”, e qualquer outro mandamento que exista — resumem-se nestas palavras: “Ama o teu próximo como a ti mesmo.”

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não faz o mal ao próximo; portanto, o amor é o cumprimento da lei.

[[v45-13-11]]

^<<v45-13-11,11>>^ E façam-no porque sabem em que época estamos, que já é hora de despertarem do sono, pois agora a nossa salvação está mais próxima do que quando nos tornámos crentes.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite está bem avançada; o dia está próximo. Portanto, rejeitemos as obras da escuridão e revistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Andemos decentemente, como em pleno dia, não em festas descontroladas^&#42;1^ e bebedeiras, nem em relações sexuais imorais e conduta insolente,^&#42;2^ nem em conflitos e ciúmes.

[NOTE]
====
. Ou: “em festanças”.
. Ou: “atos de conduta desavergonhada”. Plural da palavra grega asélgeia. Veja o Glossário.
====

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas revistam-se do Senhor Jesus Cristo e não premeditem como satisfazer os desejos da carne.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]