include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-3-1]]

^<<v45-3-1,1>>^ Qual é, pois, a vantagem do judeu, ou qual é o valor da circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ É grande, em todos os sentidos. Em primeiro lugar, aos judeus foram confiadas as proclamações sagradas de Deus.

[[v45-3-3]]

^<<v45-3-3,3>>^ O que é que acontece então? Se alguns não tiveram fé, será que a sua falta de fé anulará a fidelidade de Deus?

[[v45-3-4]]

^<<v45-3-4,4>>^ Certamente que não! Mas que Deus seja verdadeiro, mesmo que todos os homens sejam mentirosos, assim como está escrito: “Para que fique provado que és justo nas tuas palavras e venças quando fores julgado.”

[[v45-3-5]]

^<<v45-3-5,5>>^ No entanto, o que diremos, se a nossa injustiça realça a justiça de Deus? Será que Deus é injusto quando expressa a sua ira? (Falo em termos humanos.)

[[v45-3-6]]

^<<v45-3-6,6>>^ É claro que não! Senão, como é que Deus julgará o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Mas, se pela minha mentira a verdade de Deus tem sido ainda mais destacada para a sua glória, então, porque sou eu condenado como pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ E porque não dizer, assim como alguns afirmam falsamente que dizemos: “Façamos coisas más, para que venham coisas boas”? A condenação desses homens está de acordo com a justiça.

[[v45-3-9]]

^<<v45-3-9,9>>^ O que concluímos então? Estamos em melhor situação? De maneira nenhuma! Pois já provámos que tanto judeus como gregos, todos estão debaixo do pecado,

[[v45-3-10]]

^<<v45-3-10,10>>^ assim como está escrito: “Não há nenhum justo, nem sequer um;

[[v45-3-11]]

^<<v45-3-11,11>>^ não há quem tenha entendimento;^&#42;1^ não há quem procure a Deus.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se desviaram, todos eles se tornaram inúteis; não há quem mostre bondade, nem mesmo um só.”

[[v45-3-13]]

^<<v45-3-13,13>>^ “A sua garganta é uma sepultura aberta; enganam com a língua.” “Há veneno de serpente atrás dos seus lábios.”

[[v45-3-14]]

^<<v45-3-14,14>>^ “E a sua boca está cheia de maldições e de amargura.”

[[v45-3-15]]

^<<v45-3-15,15>>^ “Os seus pés são velozes para derramar sangue.”

[[v45-3-16]]

^<<v45-3-16,16>>^ “Há ruína e desgraça nos seus caminhos,

[[v45-3-17]]

^<<v45-3-17,17>>^ e não conhecem o caminho da paz.”

[[v45-3-18]]

^<<v45-3-18,18>>^ “Não há temor de Deus diante dos seus olhos.”

[[v45-3-19]]

^<<v45-3-19,19>>^ Ora, nós sabemos que tudo o que a Lei diz é dirigido aos que estão debaixo da Lei, a fim de que toda a boca se cale, e o mundo inteiro fique sujeito a punição diante de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Portanto, ninguém será declarado justo^&#42;1^ diante dele por obras exigidas por lei, pois o que vem por meio da Lei é a plena consciência^&#42;2^ do pecado.

[NOTE]
====
. Ou: “nenhuma carne será declarada justa”.
. Ou: “o conhecimento exato”.
====

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora, sem depender da lei, foi revelada a justiça de Deus, da qual a Lei e os Profetas dão testemunho,

[[v45-3-22]]

^<<v45-3-22,22>>^ sim, a justiça de Deus por meio da fé em Jesus Cristo, para todos os que têm fé. Porque não há distinção.

[[v45-3-23]]

^<<v45-3-23,23>>^ Pois todos pecaram e não atingem a glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ e é como dádiva^&#42;1^ que são declarados justos pela Sua bondade imerecida, por meio do livramento pelo resgate pago por Cristo Jesus.

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v45-3-25]]

^<<v45-3-25,25>>^ Deus apresentou Cristo como oferta para propiciação^&#42;1^ por meio da fé no seu sangue. Deus fê-lo para demonstrar a sua própria justiça, pois, na sua tolerância,^&#42;2^ estava a perdoar os pecados cometidos no passado.

[NOTE]
====
. Ou: “expiação; reconciliação”.
. Ou: “indulgência”.
====

[[v45-3-26]]

^<<v45-3-26,26>>^ Fê-lo para demonstrar a sua justiça no presente, para que fosse justo mesmo ao declarar justo o homem que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde está, pois, o motivo para orgulho? Foi eliminado. Por meio de que lei? A das obras? Não! Por meio da lei da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Pois nós concluímos que um homem é declarado justo pela fé, sem depender das obras exigidas por lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ Ou será que Deus é apenas Deus dos judeus? Não é também Deus de pessoas das nações? Sim, também de pessoas das nações.

[[v45-3-30]]

^<<v45-3-30,30>>^ Visto que Deus é um só, ele declarará justos os circuncisos em resultado da fé, e os incircuncisos por meio da sua fé.

[[v45-3-31]]

^<<v45-3-31,31>>^ Quer isto dizer que abolimos a lei por meio da nossa fé? De maneira nenhuma! Pelo contrário, confirmamos a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]