include::./index.adoc[]

[[v45-11-0]]
=== Romanos, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-11-1]]

^<<v45-11-1,1>>^ Pergunto, então: Será que Deus rejeitou o seu povo? De maneira nenhuma! Pois eu também sou israelita, da descendência^&#42;1^ de Abraão, da tribo de Benjamim.

[NOTE]
====
. Lit.: “semente”.
====

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou o seu povo, a quem primeiro deu consideração.^&#42;1^ Não sabem o que diz certa passagem das Escrituras sobre Elias, quando ele clamou perante Deus contra Israel?

[NOTE]
====
. Ou: “primeiro reconheceu”.
====

[[v45-11-3]]

^<<v45-11-3,3>>^ “Jeová,^&#42;1^ mataram os teus profetas, derrubaram os teus altares, e só fiquei eu, e agora estão a tentar tirar-me a vida.”^&#42;2^

[NOTE]
====
. Veja o Ap. A5.
. Ou: “alma”.
====

[[v45-11-4]]

^<<v45-11-4,4>>^ No entanto, o que é que lhe disse a proclamação divina? “Ainda tenho 7000 homens que não se ajoelharam diante de Baal.”

[[v45-11-5]]

^<<v45-11-5,5>>^ Da mesma maneira, também na época atual há um restante, segundo uma escolha por meio da bondade imerecida.

[[v45-11-6]]

^<<v45-11-6,6>>^ Ora, se é por bondade imerecida, já não é por meio de obras; senão, a bondade imerecida já não seria bondade imerecida.

[[v45-11-7]]

^<<v45-11-7,7>>^ O que diremos então? Aquilo que Israel tanto procura, não obteve, mas os escolhidos obtiveram. Os outros ficaram insensíveis,

[[v45-11-8]]

^<<v45-11-8,8>>^ assim como está escrito: “Deus deu-lhes um espírito de sono profundo, olhos que não veem e ouvidos que não ouvem, até ao dia de hoje.”

[[v45-11-9]]

^<<v45-11-9,9>>^ Também, David diz: “Que a sua mesa se torne um laço, uma armadilha, uma pedra de tropeço e uma retribuição para eles.

[[v45-11-10]]

^<<v45-11-10,10>>^ Que os seus olhos se escureçam para que não consigam ver, e que lhes encurves continuamente as costas.”

[[v45-11-11]]

^<<v45-11-11,11>>^ Então, pergunto: Será que eles tropeçaram e caíram definitivamente? Certamente que não! Mas por causa do seu passo em falso há salvação para pessoas das nações, para os incitar ao ciúme.

[[v45-11-12]]

^<<v45-11-12,12>>^ Ora, se o seu passo em falso significa riquezas para o mundo, e a sua diminuição significa riquezas para as pessoas das nações, quanto mais riquezas significará o pleno número deles!

[[v45-11-13]]

^<<v45-11-13,13>>^ Agora, falo convosco, os que são pessoas das nações. Visto que sou apóstolo para as nações, glorifico^&#42;1^ o meu ministério

[NOTE]
====
. Ou: “exalto”.
====

[[v45-11-14]]

^<<v45-11-14,14>>^ para ver se de algum modo posso incitar o meu próprio povo^&#42;1^ ao ciúme e salvar alguns deles.

[NOTE]
====
. Lit.: “a minha carne”.
====

[[v45-11-15]]

^<<v45-11-15,15>>^ Pois, se o facto de terem sido rejeitados significa reconciliação para o mundo, o que significará o facto de serem aceites, senão vida para os que estavam mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ Além disso, se a parte da massa considerada como primícias é santa, toda a massa também é santa; e, se a raiz é santa, os ramos também o são.

[[v45-11-17]]

^<<v45-11-17,17>>^ No entanto, se alguns dos ramos foram arrancados, e tu, apesar de seres oliveira brava, foste enxertado entre eles e te tornaste participante da riqueza da raiz da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ não trates os ramos com arrogância.^&#42;1^ Se, porém, os tratares com arrogância,^&#42;2^ lembra-te de que tu não sustentas a raiz, mas a raiz sustenta-te a ti.

[NOTE]
====
. Ou: “não te gabes à custa dos ramos”.
. Ou: “se te gabares à custa deles”.
====

[[v45-11-19]]

^<<v45-11-19,19>>^ Dirás, então: “Alguns ramos foram arrancados para que eu fosse enxertado.”

[[v45-11-20]]

^<<v45-11-20,20>>^ É verdade! Foram arrancados porque não tiveram fé, mas tu estás de pé pela fé. Não sejas arrogante, mas tem temor.

[[v45-11-21]]

^<<v45-11-21,21>>^ Pois, se Deus não poupou os ramos naturais, também não te poupará.

[[v45-11-22]]

^<<v45-11-22,22>>^ Portanto, considera a bondade e a severidade de Deus. Há severidade para com aqueles que caíram, mas para contigo há a bondade de Deus, desde que permaneças na sua bondade; senão, também serás cortado.

[[v45-11-23]]

^<<v45-11-23,23>>^ E eles também, se deixarem de ser pessoas sem fé, serão enxertados, pois Deus é capaz de os enxertar novamente.

[[v45-11-24]]

^<<v45-11-24,24>>^ Pois, se foste cortado da oliveira que é brava por natureza e foste enxertado numa oliveira cultivada, o que é contrário à natureza, quanto mais voltarão os ramos naturais a ser enxertados na sua própria oliveira!

[[v45-11-25]]

^<<v45-11-25,25>>^ Pois não quero, irmãos, que desconheçam este segredo sagrado, para que não se tornem sábios aos vossos próprios olhos: uma parte de Israel ficou insensível até que entrasse o pleno número de pessoas das nações,

[[v45-11-26]]

^<<v45-11-26,26>>^ e desta maneira todo o Israel será salvo. Assim como está escrito: “O libertador^&#42;1^ sairá de Sião e afastará de Jacó as práticas ímpias.

[NOTE]
====
. Ou: “salvador”.
====

[[v45-11-27]]

^<<v45-11-27,27>>^ E este é o pacto que farei com eles quando lhes tirar os pecados.”

[[v45-11-28]]

^<<v45-11-28,28>>^ É verdade que, a respeito das boas novas, eles são inimigos para o vosso benefício; mas, a respeito da escolha de Deus, eles são amados por causa dos seus antepassados.

[[v45-11-29]]

^<<v45-11-29,29>>^ Pois as dádivas e a chamada de Deus são coisas das quais ele não se arrepende.

[[v45-11-30]]

^<<v45-11-30,30>>^ Pois, assim como antes vocês eram desobedientes a Deus, mas agora foram tratados com misericórdia por causa da desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ assim também, agora, eles têm sido desobedientes resultando em misericórdia para vocês, para que agora eles também sejam tratados com misericórdia.

[[v45-11-32]]

^<<v45-11-32,32>>^ Pois Deus tornou-os a todos prisioneiros da desobediência, para os tratar a todos com misericórdia.

[[v45-11-33]]

^<<v45-11-33,33>>^ Como são profundas as riquezas, a sabedoria e o conhecimento de Deus! Como são insondáveis os seus julgamentos, e impenetráveis os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ Pois “quem é que veio a conhecer a mente de Jeová,^&#42;1^ ou quem é que se tornou o seu conselheiro”?

[NOTE]
====
. Veja o Ap. A5.
====

[[v45-11-35]]

^<<v45-11-35,35>>^ Ou “quem é que primeiro lhe deu algo, para que ele lhe deva retribuir”?

[[v45-11-36]]

^<<v45-11-36,36>>^ Porque todas as coisas são dele, e por ele, e para ele. Glória a ele para sempre. Amém.

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]