include::./index.adoc[]

[[v45-16-0]]
=== Romanos, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-16-1]]

^<<v45-16-1,1>>^ Apresento-vos^&#42;1^ a nossa irmã Febe, que é ministra da congregação em Cencreia,

[NOTE]
====
. Ou: “Recomendo-vos”.
====

[[v45-16-2]]

^<<v45-16-2,2>>^ para que a acolham no Senhor de um modo digno dos santos e lhe deem toda a ajuda necessária, pois ela também se mostrou defensora de muitos, de mim inclusive.

[[v45-16-3]]

^<<v45-16-3,3>>^ Transmitam as minhas saudações a Prisca e Áquila, meus colaboradores em Cristo Jesus,

[[v45-16-4]]

^<<v45-16-4,4>>^ que arriscaram o próprio pescoço por mim^&#42;1^ e a quem não só eu, mas também todas as congregações das nações, estamos gratos.

[NOTE]
====
. Ou: “pela minha alma”.
====

[[v45-16-5]]

^<<v45-16-5,5>>^ Saudações também à congregação que se reúne na casa deles. Saudações ao meu amado Epéneto, que é um dos primeiros frutos da Ásia para Cristo.

[[v45-16-6]]

^<<v45-16-6,6>>^ Saudações a Maria, que trabalhou arduamente em vosso favor.

[[v45-16-7]]

^<<v45-16-7,7>>^ Saudações a Andrónico e a Júnias, meus parentes e companheiros de prisão, que são homens bem conhecidos pelos apóstolos e estão em união com Cristo há mais tempo do que eu.

[[v45-16-8]]

^<<v45-16-8,8>>^ Transmitam as minhas saudações a Amplíato, meu amado no Senhor.

[[v45-16-9]]

^<<v45-16-9,9>>^ Saudações a Urbano, nosso colaborador em Cristo, e também ao meu amado Estáquis.

[[v45-16-10]]

^<<v45-16-10,10>>^ Saudações a Apeles, o aprovado em Cristo. Saudações aos da casa de Aristóbulo.

[[v45-16-11]]

^<<v45-16-11,11>>^ Saudações a Herodião, meu parente. Saudações aos da casa de Narciso que estão no Senhor.

[[v45-16-12]]

^<<v45-16-12,12>>^ Saudações a Trifena e Trifosa, mulheres que trabalham arduamente no Senhor. Saudações à nossa amada Pérside, pois ela tem trabalhado arduamente no Senhor.

[[v45-16-13]]

^<<v45-16-13,13>>^ Saudações a Rufo, o escolhido no Senhor, e à sua mãe, que também é minha.

[[v45-16-14]]

^<<v45-16-14,14>>^ Saudações a Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e aos irmãos que estão com eles.

[[v45-16-15]]

^<<v45-16-15,15>>^ Saudações a Filólogo e Júlia, Nereu e sua irmã, e Olimpas, e a todos os santos que estão com eles.

[[v45-16-16]]

^<<v45-16-16,16>>^ Cumprimentem-se uns aos outros com um beijo santo. Todas as congregações do Cristo vos mandam saudações.

[[v45-16-17]]

^<<v45-16-17,17>>^ Exorto-vos agora, irmãos, a que fiquem atentos àqueles que causam divisões e dão motivos para tropeço, contrariando os ensinamentos que vocês aprenderam. Afastem-se deles.

[[v45-16-18]]

^<<v45-16-18,18>>^ Porque homens como esses não são escravos de Cristo, nosso Senhor, mas dos seus próprios desejos,^&#42;1^ e, com conversa suave e bajulação, seduzem o coração dos ingénuos.

[NOTE]
====
. Ou: “do seu próprio ventre”.
====

[[v45-16-19]]

^<<v45-16-19,19>>^ A vossa obediência tornou-se conhecida por todos, e alegro-me por vossa causa. Mas quero que sejam sábios quanto ao que é bom, porém inocentes quanto ao que é mau.

[[v45-16-20]]

^<<v45-16-20,20>>^ O Deus que dá paz em breve esmagará Satanás debaixo dos vossos pés. Que a bondade imerecida do nosso Senhor Jesus esteja convosco.

[[v45-16-21]]

^<<v45-16-21,21>>^ Timóteo, meu colaborador, manda-vos saudações, e também Lúcio, Jasão e Sosípatro, meus parentes.

[[v45-16-22]]

^<<v45-16-22,22>>^ Eu, Tércio, que escrevi esta carta, mando-vos saudações no Senhor.

[[v45-16-23]]

^<<v45-16-23,23>>^ Gaio, que me hospeda a mim e a toda a congregação, envia-vos saudações. Erasto, o tesoureiro^&#42;1^ da cidade, envia-vos saudações, e também Quarto, irmão dele.

[NOTE]
====
. Ou: “mordomo”.
====

[[v45-16-24]]

^<<v45-16-24,24>>^ ^&#42;1^—

[NOTE]
====
. Veja o Ap. A3.
====

[[v45-16-25]]

^<<v45-16-25,25>>^ Àquele que vos pode fazer firmes, de acordo com as boas novas que declaro e com a pregação sobre Jesus Cristo, segundo a revelação do segredo sagrado que foi mantido em silêncio por tempos de longa duração

[[v45-16-26]]

^<<v45-16-26,26>>^ — mas que agora foi revelado^&#42;1^ e dado a conhecer entre todas as nações por meio das Escrituras proféticas, de acordo com a ordem do Deus eterno, para promover a obediência pela fé —,

[NOTE]
====
. Ou: “manifestado”.
====

[[v45-16-27]]

^<<v45-16-27,27>>^ a Deus, que é o único sábio, seja dada a glória por meio de Jesus Cristo para sempre. Amém.

'''

xref:045-romanos/045-romanos-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[Próximo Capítulo &#62;]