include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v52-2-1]]

^<<v52-2-1,1>>^ Certamente sabem, irmãos, que a nossa visita não foi em vão.

[[v52-2-2]]

^<<v52-2-2,2>>^ Pois, embora tivéssemos sofrido e sido maltratados em Filipos, como sabem, reunimos coragem,^&#42;1^ com a ajuda do nosso Deus, para vos transmitir as boas novas de Deus perante muita oposição.^&#42;2^

[NOTE]
====
. Ou: “destemor”.
. Ou, possivelmente: “no meio de muita luta”.
====

[[v52-2-3]]

^<<v52-2-3,3>>^ Pois a exortação que damos não vem de erro nem de impureza, nem é enganosa,

[[v52-2-4]]

^<<v52-2-4,4>>^ mas, visto que Deus nos aprovou para sermos incumbidos das boas novas, assim falamos para agradar não a homens, mas a Deus, que examina o nosso coração.

[[v52-2-5]]

^<<v52-2-5,5>>^ De facto, sabem que nunca bajulámos ninguém, nem usámos de fingimento com intenções gananciosas; Deus é testemunha!

[[v52-2-6]]

^<<v52-2-6,6>>^ Nem estivemos à procura da glória de homens, não, nem da vossa nem da de outros, embora pudéssemos, como apóstolos de Cristo, ter sido um peso financeiro para vocês.

[[v52-2-7]]

^<<v52-2-7,7>>^ Pelo contrário, nós tornámo-nos meigos no vosso meio, como a mãe que amamenta e cuida ternamente dos^&#42;1^ seus filhos.

[NOTE]
====
. Ou: “acalenta os”.
====

[[v52-2-8]]

^<<v52-2-8,8>>^ Assim, tendo terna afeição por vocês, estávamos decididos^&#42;1^ não só a transmitir-vos as boas novas de Deus, mas também a dar-vos tudo de nós,^&#42;2^ porque nós passámos a amar-vos muito.

[NOTE]
====
. Lit.: “contentes”.
. Ou: “dar-vos as nossas almas”.
====

[[v52-2-9]]

^<<v52-2-9,9>>^ Certamente se lembram, irmãos, do nosso grande esforço e trabalho árduo. Nós trabalhávamos noite e dia para não sermos um peso financeiro para nenhum de vocês, ao pregar-vos as boas novas de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vocês são testemunhas, e Deus também é, de como nos comportámos de maneira leal, justa e irrepreensível convosco, crentes.

[[v52-2-11]]

^<<v52-2-11,11>>^ Sabem muito bem que nós exortávamos, consolávamos e aconselhávamos cada um de vocês, assim como um pai faz com os filhos,

[[v52-2-12]]

^<<v52-2-12,12>>^ para que continuassem a andar de um modo digno de Deus, que vos chama ao seu Reino e glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ De facto, é por isso que também agradecemos a Deus incessantemente, porque, quando receberam a palavra de Deus, que ouviram de nós, aceitaram-na não como a palavra de homens, mas pelo que ela realmente é, a palavra de Deus, que também atua em vocês, crentes.

[[v52-2-14]]

^<<v52-2-14,14>>^ Pois vocês, irmãos, tornaram-se imitadores das congregações de Deus na Judeia, que estão em união com Cristo Jesus, porque sofreram às mãos dos vossos próprios conterrâneos as mesmas coisas que eles também estão a sofrer às mãos dos judeus,

[[v52-2-15]]

^<<v52-2-15,15>>^ que até mesmo mataram o Senhor Jesus e os profetas, e nos perseguiram. Além disso, eles não estão a agradar a Deus, mas são contra os interesses de todos os homens,

[[v52-2-16]]

^<<v52-2-16,16>>^ visto que nos tentam impedir de falar às pessoas das nações para que se salvem. Deste modo, eles continuam a encher a medida dos seus pecados. Mas, por fim, a Sua ira alcançou-os.

[[v52-2-17]]

^<<v52-2-17,17>>^ Nós, irmãos, quando fomos separados^&#42;1^ de vocês por pouco tempo (em pessoa, não no coração), tínhamos um grande desejo de vos ver pessoalmente,^&#42;2^ e, assim, esforçámo-nos muito para o conseguir.

[NOTE]
====
. Ou: “privados”.
. Lit.: “ver o vosso rosto”.
====

[[v52-2-18]]

^<<v52-2-18,18>>^ Por esta razão, queríamos ir visitar-vos; sim, eu, Paulo, tentei não apenas uma vez, mas duas, contudo, Satanás bloqueou-nos o caminho.

[[v52-2-19]]

^<<v52-2-19,19>>^ Pois qual é a nossa esperança, alegria ou coroa de exultação perante o nosso Senhor Jesus, na sua presença? Não são realmente vocês?

[[v52-2-20]]

^<<v52-2-20,20>>^ Vocês, certamente, são a nossa glória e alegria.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]