include::./index.adoc[]

[[v52-4-0]]
=== 1 Tessalonicenses, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v52-4-1]]

^<<v52-4-1,1>>^ Finalmente, irmãos, assim como receberam instruções da nossa parte sobre como devem andar para agradar a Deus — e é assim que têm andado —, pedimos e suplicamos, pelo Senhor Jesus, que o continuem a fazer mais plenamente.

[[v52-4-2]]

^<<v52-4-2,2>>^ Pois conhecem as instruções^&#42;1^ que vos demos da parte do^&#42;2^ Senhor Jesus.

[NOTE]
====
. Ou: “ordens”.
. Ou: “por meio do”.
====

[[v52-4-3]]

^<<v52-4-3,3>>^ Pois esta é a vontade de Deus: que sejam santos e se abstenham de imoralidade sexual.^&#42;1^

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v52-4-4]]

^<<v52-4-4,4>>^ Cada um de vocês deve saber controlar o seu próprio corpo^&#42;1^ em santidade e honra,

[NOTE]
====
. Lit.: “vaso”.
====

[[v52-4-5]]

^<<v52-4-5,5>>^ não com paixão desenfreada, ávida,^&#42;1^ como as nações que não conhecem a Deus.

[NOTE]
====
. Ou: “apetite sexual insaciável”.
====

[[v52-4-6]]

^<<v52-4-6,6>>^ Ninguém deve ultrapassar os limites do que é próprio e aproveitar-se do seu irmão neste assunto, pois Jeová^&#42;1^ exige punição por todas estas coisas, assim como vos dissemos antes e também vos advertimos fortemente.

[NOTE]
====
. Veja o Ap. A5.
====

[[v52-4-7]]

^<<v52-4-7,7>>^ Pois Deus chamou-nos, não para a impureza, mas para a santidade.

[[v52-4-8]]

^<<v52-4-8,8>>^ Portanto, quem desconsidera isto não desconsidera o homem, mas a Deus, que vos dá o seu espírito santo.

[[v52-4-9]]

^<<v52-4-9,9>>^ No entanto, no que se refere ao amor fraternal, não precisam que vos escrevamos, pois são ensinados por Deus a amar-se uns aos outros.

[[v52-4-10]]

^<<v52-4-10,10>>^ Realmente, vocês já estão a fazê-lo a todos os irmãos, em toda a Macedónia. Mas queremos exortar-vos, irmãos, a que continuem a fazê-lo cada vez mais.

[[v52-4-11]]

^<<v52-4-11,11>>^ Tenham por objetivo viver em paz, cuidar dos vossos próprios assuntos e trabalhar com as vossas próprias mãos, assim como vos instruímos,

[[v52-4-12]]

^<<v52-4-12,12>>^ a fim de que andem decentemente perante os de fora e não precisem de nada.

[[v52-4-13]]

^<<v52-4-13,13>>^ Além disso, irmãos, não queremos que fiquem na ignorância^&#42;1^ quanto aos que estão a dormir na morte, para que não fiquem pesarosos como os demais, que não têm esperança.

[NOTE]
====
. Ou: “desinformados”.
====

[[v52-4-14]]

^<<v52-4-14,14>>^ Se temos fé em que Jesus morreu e foi levantado, então, também temos fé em que Deus trará com ele aqueles que adormeceram na morte em união com Jesus.

[[v52-4-15]]

^<<v52-4-15,15>>^ Pois, a vocês, nós dizemos o seguinte pela palavra de Jeová:^&#42;1^ nós, os vivos, que sobrevivermos até à presença do Senhor, de modo algum precederemos os que adormeceram na morte;

[NOTE]
====
. Veja o Ap. A5.
====

[[v52-4-16]]

^<<v52-4-16,16>>^ porque o próprio Senhor descerá do céu com uma chamada de comando, com voz de arcanjo e com a trombeta de Deus, e os mortos em união com Cristo irão levantar-se primeiro.

[[v52-4-17]]

^<<v52-4-17,17>>^ Depois, nós, os vivos, que sobrevivermos, seremos arrebatados com eles em nuvens para nos encontrarmos com o Senhor no ar; e assim estaremos sempre com o Senhor.

[[v52-4-18]]

^<<v52-4-18,18>>^ Portanto, continuem a consolar-se uns aos outros com estas palavras.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[Próximo Capítulo &#62;]