include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-13-1]]

^<<v18-13-1,1>>^ “Sim, os meus olhos viram tudo isto,
Os meus ouvidos ouviram e entenderam.

[[v18-13-2]]

^<<v18-13-2,2>>^ O que vocês sabem, eu também sei;
Não sou inferior a vocês.

[[v18-13-3]]

^<<v18-13-3,3>>^ Quanto a mim, eu preferiria falar com o próprio Todo-Poderoso;
Desejo defender a minha causa perante Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vocês, porém, difamam-me com mentiras;
Todos vocês são médicos que não valem nada.

[[v18-13-5]]

^<<v18-13-5,5>>^ Quem me dera que ficassem calados,
Isso mostraria sabedoria da vossa parte.

[[v18-13-6]]

^<<v18-13-6,6>>^ Por favor, escutem os meus argumentos,
E prestem atenção à defesa dos meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Será que falarão injustamente a favor de Deus,
E falarão falsidades em seu benefício?

[[v18-13-8]]

^<<v18-13-8,8>>^ Tomarão o lado^&#42;1^ dele,
Tentarão defender a causa do verdadeiro Deus?

[NOTE]
====
. Ou: “Mostrarão parcialidade a favor”.
====

[[v18-13-9]]

^<<v18-13-9,9>>^ O que seria de vocês se ele vos examinasse?
Será que o enganariam, assim como fariam com um homem mortal?

[[v18-13-10]]

^<<v18-13-10,10>>^ De certeza que ele vos vai repreender,
Se tentarem secretamente mostrar favoritismo.

[[v18-13-11]]

^<<v18-13-11,11>>^ Não vos amedrontará a sua glória,
E não virá o seu pavor sobre vocês?

[[v18-13-12]]

^<<v18-13-12,12>>^ As vossas declarações sábias^&#42;1^ são provérbios de cinzas;
As vossas defesas^&#42;2^ são tão frágeis como o barro.

[NOTE]
====
. Ou: “memoráveis”.
. Lit.: “protuberâncias de escudo”.
====

[[v18-13-13]]

^<<v18-13-13,13>>^ Calem-se, para que eu fale,
Depois, que me aconteça o que tiver de acontecer!

[[v18-13-14]]

^<<v18-13-14,14>>^ Porque é que me coloco em perigo^&#42;1^
E ponho a minha vida^&#42;2^ nas minhas mãos?

[NOTE]
====
. Lit.: “Porque é que carrego a minha carne nos meus dentes”.
. Ou: “alma”.
====

[[v18-13-15]]

^<<v18-13-15,15>>^ Embora ele me possa matar, eu ainda esperarei;
Defenderei a minha causa^&#42;1^ perante ele.^&#42;2^

[NOTE]
====
. Ou: “os meus caminhos”.
. Ou: “perante a sua face”.
====

[[v18-13-16]]

^<<v18-13-16,16>>^ Então, ele irá tornar-se a minha salvação,
Pois nenhum ímpio^&#42;1^ pode comparecer perante ele.

[NOTE]
====
. Ou: “apóstata”.
====

[[v18-13-17]]

^<<v18-13-17,17>>^ Escutem atentamente a minha palavra;
Prestem atenção à minha declaração.

[[v18-13-18]]

^<<v18-13-18,18>>^ Vejam, preparei-me para defender a minha causa;
Sei que tenho razão.

[[v18-13-19]]

^<<v18-13-19,19>>^ Quem é que discutirá comigo?
Eu morreria se ficasse calado!^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Se alguém puder, eu ficarei calado e morrerei.”
====

[[v18-13-20]]

^<<v18-13-20,20>>^ Concede-me apenas duas coisas, ó Deus,^&#42;1^
Para que eu não me esconda de ti:

[NOTE]
====
. Lit.: “Apenas duas coisas não me faças”.
====

[[v18-13-21]]

^<<v18-13-21,21>>^ Afasta para longe de mim a tua mão pesada,
E não permitas que o medo de ti me apavore.

[[v18-13-22]]

^<<v18-13-22,22>>^ Chama, e eu responderei,
Ou deixa-me falar, e responde-me.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quais são os meus erros e pecados?
Mostra-me a minha transgressão e o meu pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Porque é que escondes a tua face
E me consideras teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Tentarás assustar uma folha levada pelo vento
Ou perseguirás a palha seca?

[[v18-13-26]]

^<<v18-13-26,26>>^ Pois continuas a registar acusações amargas contra mim,
E fazes-me responder pelos pecados da minha juventude.

[[v18-13-27]]

^<<v18-13-27,27>>^ Colocas os meus pés no tronco,
Inspecionas todos os meus caminhos,
E examinas cada uma das minhas pegadas.

[[v18-13-28]]

^<<v18-13-28,28>>^ Assim, o homem^&#42;1^ consome-se como algo podre,
Como uma roupa comida pela traça.

[NOTE]
====
. Lit.: “ele”, possivelmente, referindo-se a Jó.
====

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]