include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-4-1]]

^<<v18-4-1,1>>^ Então, Elifaz, o temanita, disse em resposta:

[[v18-4-2]]

^<<v18-4-2,2>>^ “Se alguém tentar falar contigo, ficarás impaciente?
Pois quem é que pode ficar calado?

[[v18-4-3]]

^<<v18-4-3,3>>^ Sim, tu corrigias muitos,
E fortalecias as mãos fracas.

[[v18-4-4]]

^<<v18-4-4,4>>^ As tuas palavras levantavam quem tropeçava,
E tu firmavas os joelhos vacilantes.

[[v18-4-5]]

^<<v18-4-5,5>>^ Contudo, agora que te acontece isto, tu ficas abatido;^&#42;1^
Toca-te a ti, e tu ficas desanimado.

[NOTE]
====
. Lit.: “ficas esgotado”.
====

[[v18-4-6]]

^<<v18-4-6,6>>^ O teu temor de Deus não te dá confiança?
O teu caminho de integridade não te dá esperança?

[[v18-4-7]]

^<<v18-4-7,7>>^ Lembras-te, por acaso, de algum inocente que tenha perecido?
Quando é que os justos foram destruídos?

[[v18-4-8]]

^<<v18-4-8,8>>^ Tenho visto que os que lavram campos de maldade^&#42;1^
E os que semeiam desgraças também as colhem.

[NOTE]
====
. Ou: “tramam a maldade”.
====

[[v18-4-9]]

^<<v18-4-9,9>>^ Morrem pelo sopro de Deus
E chegam ao seu fim numa rajada da Sua ira.

[[v18-4-10]]

^<<v18-4-10,10>>^ O leão ruge, e o leão novo rosna,
Mas até mesmo os dentes de leões fortes^&#42;1^ são partidos.

[NOTE]
====
. Ou: “leões novos jubados”.
====

[[v18-4-11]]

^<<v18-4-11,11>>^ O leão morre por falta de presas,
E as crias do leão são espalhadas.

[[v18-4-12]]

^<<v18-4-12,12>>^ Ora, uma palavra foi-me dita em segredo,
E um sussurro chegou ao meu ouvido.

[[v18-4-13]]

^<<v18-4-13,13>>^ Em pensamentos perturbadores durante as visões da noite,
Quando um sono profundo cai sobre os homens,

[[v18-4-14]]

^<<v18-4-14,14>>^ Um terrível tremor tomou conta de mim,
Enchendo de pavor todos os meus ossos.

[[v18-4-15]]

^<<v18-4-15,15>>^ Um espírito passou pelo meu rosto;
Os pelos do meu corpo^&#42;1^ ficaram arrepiados.

[NOTE]
====
. Ou: “da minha carne”.
====

[[v18-4-16]]

^<<v18-4-16,16>>^ Então, ele parou,
Todavia, não reconheci o seu aspeto.
Havia um vulto diante dos meus olhos;
Houve silêncio, e, em seguida, ouvi uma voz:

[[v18-4-17]]

^<<v18-4-17,17>>^ ‘Será que o homem mortal pode ser mais justo do que Deus?
Será que o homem pode ser mais puro do que Aquele que o fez?’

[[v18-4-18]]

^<<v18-4-18,18>>^ Ele não confia nos seus servos,
E encontra defeitos nos seus anjos.^&#42;1^

[NOTE]
====
. Ou: “mensageiros”.
====

[[v18-4-19]]

^<<v18-4-19,19>>^ Quanto mais nos que moram em casas de barro,
Cujo alicerce está no pó,
Que são esmagados tão facilmente como uma traça!

[[v18-4-20]]

^<<v18-4-20,20>>^ São completamente esmagados do dia para a noite.
Desaparecem para sempre, e ninguém repara.

[[v18-4-21]]

^<<v18-4-21,21>>^ Não são como uma tenda cuja corda é arrancada?
Eles morrem sem sabedoria.

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]