include::./index.adoc[]

[[v18-37-0]]
=== Jó, 37
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-37-1]]

^<<v18-37-1,1>>^ “Por causa disto, o meu coração bate forte
E pula dentro do meu peito.

[[v18-37-2]]

^<<v18-37-2,2>>^ Escutem atentamente o estrondo da sua voz^&#42;1^
E o trovão que sai da sua boca.

[NOTE]
====
. Isto é, de Deus.
====

[[v18-37-3]]

^<<v18-37-3,3>>^ Ele solta-o debaixo de toda a extensão dos céus
E envia os seus relâmpagos até aos confins da terra.

[[v18-37-4]]

^<<v18-37-4,4>>^ Depois, ouve-se um rugido;
Ele troveja com uma voz majestosa,
E não detém os relâmpagos quando se ouve a sua voz.

[[v18-37-5]]

^<<v18-37-5,5>>^ Deus troveja com a sua voz de modo maravilhoso;
Faz coisas grandiosas que estão além da nossa compreensão.

[[v18-37-6]]

^<<v18-37-6,6>>^ Pois ele diz à neve: ‘Cai sobre a terra’,
E à chuva torrencial: ‘Cai com toda a força.’

[[v18-37-7]]

^<<v18-37-7,7>>^ Deus interrompe toda a atividade humana,^&#42;1^
Para que todos os mortais conheçam o Seu trabalho.

[NOTE]
====
. Lit.: “põe um selo na mão de todos os humanos”.
====

[[v18-37-8]]

^<<v18-37-8,8>>^ Os animais selvagens entram nas tocas
E ficam nos esconderijos.

[[v18-37-9]]

^<<v18-37-9,9>>^ O vendaval sai do seu lugar,
E os ventos do norte trazem o frio.

[[v18-37-10]]

^<<v18-37-10,10>>^ Pelo sopro de Deus, produz-se o gelo,
E as grandes extensões de água ficam congeladas.

[[v18-37-11]]

^<<v18-37-11,11>>^ Ele carrega as nuvens com humidade;
Espalha os seus relâmpagos nas nuvens;

[[v18-37-12]]

^<<v18-37-12,12>>^ Elas giram em círculos, guiadas por ele;
Fazem tudo o que ele ordena sobre a superfície da terra habitada.^&#42;1^

[NOTE]
====
. Ou: “do solo produtivo da terra”.
====

[[v18-37-13]]

^<<v18-37-13,13>>^ E ele faz com que isso aconteça, quer para a punição,^&#42;1^ quer para o benefício da terra,
Quer para demonstrar amor leal.

[NOTE]
====
. Lit.: “uma vara”.
====

[[v18-37-14]]

^<<v18-37-14,14>>^ Escuta isto, Jó;
Para e reflete nas obras maravilhosas de Deus.

[[v18-37-15]]

^<<v18-37-15,15>>^ Por acaso, sabes como é que Deus controla as^&#42;1^ nuvens
E como é que faz o relâmpago sair a brilhar da Sua nuvem?

[NOTE]
====
. Ou: “dá ordem às”.
====

[[v18-37-16]]

^<<v18-37-16,16>>^ Sabes como é que as nuvens pairam no ar?
Estas são as obras maravilhosas daquele que é perfeito em conhecimento.

[[v18-37-17]]

^<<v18-37-17,17>>^ Porque é que as tuas roupas ficam quentes
Quando vem uma calmaria sobre a terra por causa do vento sul?

[[v18-37-18]]

^<<v18-37-18,18>>^ Será que tu, juntamente com ele, podes estender^&#42;1^ os céus,
Tão sólidos como um espelho de metal?

[NOTE]
====
. Ou: “achatar”.
====

[[v18-37-19]]

^<<v18-37-19,19>>^ Diz-nos o que lhe devemos dizer;
Não podemos responder, porque estamos em escuridão.

[[v18-37-20]]

^<<v18-37-20,20>>^ Devia alguém dizer-lhe que eu gostaria de falar?
Será que alguém disse alguma coisa que lhe deveria ser comunicada?

[[v18-37-21]]

^<<v18-37-21,21>>^ As pessoas nem sequer conseguem ver a luz,^&#42;1^
Embora esteja a brilhar no céu,
Até que o vento passe e limpe as nuvens.

[NOTE]
====
. Isto é, do sol.
====

[[v18-37-22]]

^<<v18-37-22,22>>^ Do norte vem um esplendor dourado;
A majestade de Deus inspira temor.

[[v18-37-23]]

^<<v18-37-23,23>>^ Entender o Todo-Poderoso está além do nosso alcance;
Ele é grande em poder
E nunca viola a sua justiça e a sua abundante retidão.

[[v18-37-24]]

^<<v18-37-24,24>>^ Portanto, as pessoas devem temê-lo.
Pois ele não mostra favor aos que se consideram sábios.”^&#42;1^

[NOTE]
====
. Lit.: “que são sábios de coração”.
====

'''

xref:018-jo/018-jo-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-jo/018-jo-038.adoc#v18-38-0[Próximo Capítulo &#62;]