include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-33-1]]

^<<v18-33-1,1>>^ “Mas agora, Jó, por favor, ouve as minhas palavras;
Escuta tudo o que eu disser.

[[v18-33-2]]

^<<v18-33-2,2>>^ Presta atenção, vou abrir a minha boca,
A minha língua^&#42;1^ vai falar.

[NOTE]
====
. Lit.: “A minha língua com o meu palato”.
====

[[v18-33-3]]

^<<v18-33-3,3>>^ As minhas palavras declaram a retidão do meu coração,
E os meus lábios dizem com sinceridade o que sei.

[[v18-33-4]]

^<<v18-33-4,4>>^ Foi o espírito de Deus que me fez,
E o fôlego do Todo-Poderoso fez-me viver.

[[v18-33-5]]

^<<v18-33-5,5>>^ Responde-me, se puderes;
Apresenta os teus argumentos diante de mim; prepara-te.

[[v18-33-6]]

^<<v18-33-6,6>>^ Perante o verdadeiro Deus, sou exatamente como tu;
Também fui formado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Por isso, não deves ficar apavorado, com medo de mim,
E nenhuma pressão da minha parte te deve esmagar.

[[v18-33-8]]

^<<v18-33-8,8>>^ Eu, porém, ouvi-te dizer,
Sim, ouvi muitas vezes estas palavras:

[[v18-33-9]]

^<<v18-33-9,9>>^ ‘Sou puro, não cometi nenhuma transgressão;
Estou limpo, não cometi nenhum erro.

[[v18-33-10]]

^<<v18-33-10,10>>^ No entanto, Deus encontra motivos para se opor a mim;
Ele considera-me seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Ele põe os meus pés no tronco;
Inspeciona todos os meus caminhos.’

[[v18-33-12]]

^<<v18-33-12,12>>^ Contudo, não tens razão em dizer isto, por isso, irei responder-te:
Deus é muito maior do que o homem mortal.

[[v18-33-13]]

^<<v18-33-13,13>>^ Porque é que te queixas contra ele?
É porque ele não respondeu a todas as tuas palavras?

[[v18-33-14]]

^<<v18-33-14,14>>^ Pois Deus fala uma, duas vezes,
Mas ninguém presta atenção.

[[v18-33-15]]

^<<v18-33-15,15>>^ Ele fala num sonho, numa visão da noite,
Quando o sono profundo cai sobre os homens,
Enquanto dormem nas suas camas.

[[v18-33-16]]

^<<v18-33-16,16>>^ Então, ele destapa o ouvido deles
E grava^&#42;1^ a sua instrução neles,

[NOTE]
====
. Lit.: “sela”.
====

[[v18-33-17]]

^<<v18-33-17,17>>^ Para afastar o homem de atos maus
E o proteger do orgulho.

[[v18-33-18]]

^<<v18-33-18,18>>^ Deus livra a sua alma^&#42;1^ da cova,^&#42;2^
A sua vida de perecer pela espada.^&#42;3^

[NOTE]
====
. Ou: “vida”.
. Ou: “sepultura”.
. Ou: “por uma arma (arma de arremesso)”.
====

[[v18-33-19]]

^<<v18-33-19,19>>^ O homem também é corrigido pela dor na sua cama
E pela constante aflição nos seus ossos,

[[v18-33-20]]

^<<v18-33-20,20>>^ De modo que o seu próprio ser^&#42;1^ abomina o pão,
E ele^&#42;2^ rejeita até mesmo a boa comida.

[NOTE]
====
. Lit.: “a sua vida”.
. Ou: “a sua alma”.
====

[[v18-33-21]]

^<<v18-33-21,21>>^ A sua carne definha,
E os seus ossos, que não eram vistos, agora estão salientes.^&#42;1^

[NOTE]
====
. Ou: “estão expostos”.
====

[[v18-33-22]]

^<<v18-33-22,22>>^ A sua alma^&#42;1^ aproxima-se da cova;^&#42;2^
A sua vida, dos que causam a morte.

[NOTE]
====
. Ou: “vida”.
. Ou: “sepultura”.
====

[[v18-33-23]]

^<<v18-33-23,23>>^ Se houver um mensageiro^&#42;1^ para ele,
Um defensor entre mil,
Para dizer ao homem o que é justo,

[NOTE]
====
. Ou: “anjo”.
====

[[v18-33-24]]

^<<v18-33-24,24>>^ Deus irá mostrar-lhe favor e dirá:
‘Livra-o de descer à cova!^&#42;1^
Encontrei um resgate!

[NOTE]
====
. Ou: “sepultura”.
====

[[v18-33-25]]

^<<v18-33-25,25>>^ Que a sua carne se torne mais fresca^&#42;1^ do que a de um jovem;
Que ele volte aos dias do vigor da sua juventude.’

[NOTE]
====
. Ou: “saudável”.
====

[[v18-33-26]]

^<<v18-33-26,26>>^ Ele suplicará a Deus, que o aceitará,
Verá a Sua face com gritos de alegria;
E Ele concederá novamente a Sua justiça ao homem mortal.

[[v18-33-27]]

^<<v18-33-27,27>>^ Essa pessoa dirá^&#42;1^ aos homens:
‘Pequei e distorci o que é certo,
Mas não recebi o que merecia.^&#42;2^

[NOTE]
====
. Lit.: “cantará”.
. Ou, possivelmente: “E isso não me beneficiou”.
====

[[v18-33-28]]

^<<v18-33-28,28>>^ Ele livrou-me^&#42;1^ de ir para a cova,^&#42;2^
E eu continuarei a ver^&#42;3^ a luz.’

[NOTE]
====
. Ou: “Ele remiu a minha alma”.
. Ou: “sepultura”.
. Lit.: “a minha vida verá”.
====

[[v18-33-29]]

^<<v18-33-29,29>>^ Realmente, Deus faz todas estas coisas
Duas, três vezes, pelo homem,

[[v18-33-30]]

^<<v18-33-30,30>>^ Para o trazer^&#42;1^ de volta da cova,^&#42;2^
A fim de que seja iluminado com a luz da vida.

[NOTE]
====
. Ou: “trazer a sua alma”.
. Ou: “sepultura”.
====

[[v18-33-31]]

^<<v18-33-31,31>>^ Presta atenção, Jó! Escuta-me!
Fica calado, e eu continuarei a falar.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se tiveres alguma coisa para dizer, responde-me.
Fala, pois eu quero provar que estás certo.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não tiveres nada para dizer, escuta-me;
Fica calado, e eu irei ensinar-te a sabedoria.”

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]