include::./index.adoc[]

[[v18-31-0]]
=== Jó, 31
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-31-1]]

^<<v18-31-1,1>>^ “Fiz um pacto com os meus olhos.
Portanto, como poderia eu dar atenção imprópria a uma virgem?

[[v18-31-2]]

^<<v18-31-2,2>>^ Nesse caso, que porção receberia eu de Deus, lá de cima,
Que herança receberia eu do Todo-Poderoso, lá do alto?

[[v18-31-3]]

^<<v18-31-3,3>>^ Não está reservado o desastre para o malfeitor
E a calamidade para os que praticam a maldade?

[[v18-31-4]]

^<<v18-31-4,4>>^ Por acaso, não vê ele os meus caminhos
E conta todos os meus passos?

[[v18-31-5]]

^<<v18-31-5,5>>^ Será que já andei em falsidade?^&#42;1^
Será que os meus pés se apressaram para enganar?

[NOTE]
====
. Ou, possivelmente: “com homens de falsidade”.
====

[[v18-31-6]]

^<<v18-31-6,6>>^ Que Deus me pese com uma balança exata,
Então, verá que sou íntegro.

[[v18-31-7]]

^<<v18-31-7,7>>^ Se os meus passos se desviaram do caminho,
Se o meu coração seguiu os meus olhos,
Ou se as minhas mãos ficaram impuras,

[[v18-31-8]]

^<<v18-31-8,8>>^ Que eu semeie e outro coma,
E que aquilo que planto seja desarraigado.^&#42;1^

[NOTE]
====
. Ou: “que os meus descendentes sejam desarraigados”.
====

[[v18-31-9]]

^<<v18-31-9,9>>^ Se o meu coração foi seduzido por uma mulher,
E fiquei a vigiar a porta do meu próximo,

[[v18-31-10]]

^<<v18-31-10,10>>^ Que a minha esposa moa cereais para outro homem,
E que outros homens tenham relações sexuais com ela.^&#42;1^

[NOTE]
====
. Lit.: “que outros homens se ajoelhem sobre ela”.
====

[[v18-31-11]]

^<<v18-31-11,11>>^ Pois eu teria cometido um ato de conduta vergonhosa,
Um erro que mereceria a punição dos juízes.

[[v18-31-12]]

^<<v18-31-12,12>>^ Seria um fogo que devoraria e destruiria,^&#42;1^
Consumindo tudo o que tenho até à raiz.^&#42;2^

[NOTE]
====
. Lit.: “comeria (devoraria) até à destruição”.
. Ou: “Desarraigando os meus produtos”.
====

[[v18-31-13]]

^<<v18-31-13,13>>^ Se neguei justiça ao meu servo ou à minha serva
Quando tinham uma queixa^&#42;1^ contra mim,

[NOTE]
====
. Ou: “causa jurídica”.
====

[[v18-31-14]]

^<<v18-31-14,14>>^ O que posso fazer quando Deus me confrontar?^&#42;1^
O que lhe posso responder quando ele exigir uma prestação de contas?

[NOTE]
====
. Lit.: “se levantar”.
====

[[v18-31-15]]

^<<v18-31-15,15>>^ Aquele que me fez no ventre não os fez também a eles?
Não foi o mesmo que nos formou antes de nascermos?^&#42;1^

[NOTE]
====
. Lit.: “no ventre”.
====

[[v18-31-16]]

^<<v18-31-16,16>>^ Se eu negava dar aos pobres o que eles desejavam,
Ou entristecia os olhos da viúva;^&#42;1^

[NOTE]
====
. Lit.: “fazia os olhos da viúva falhar”.
====

[[v18-31-17]]

^<<v18-31-17,17>>^ Se eu comia sozinho a minha porção
Sem a repartir com os órfãos;

[[v18-31-18]]

^<<v18-31-18,18>>^ (Pois desde a minha juventude criei o órfão^&#42;1^ como se fosse o seu pai,
E desde a infância^&#42;2^ ajudo a viúva.^&#42;3^)

[NOTE]
====
. Lit.: “ele cresceu comigo”.
. Lit.: “desde o ventre da minha mãe”.
. Lit.: “eu guio-a”.
====

[[v18-31-19]]

^<<v18-31-19,19>>^ Se vi alguém morrer de frio,
Ou um pobre que não tinha com que se cobrir;

[[v18-31-20]]

^<<v18-31-20,20>>^ Se ele não me agradecia^&#42;1^
Enquanto se aquecia com a lã das minhas ovelhas;

[NOTE]
====
. Lit.: “Se os seus lombos não me abençoavam”.
====

[[v18-31-21]]

^<<v18-31-21,21>>^ Se levantei o punho contra o órfão
Quando precisou da minha ajuda no portão da cidade,^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Quando eu vi que tinha apoio no portão da cidade”.
====

[[v18-31-22]]

^<<v18-31-22,22>>^ Então que o meu braço^&#42;1^ me caia do ombro,
E que o meu braço seja partido no cotovelo.^&#42;2^

[NOTE]
====
. Ou: “a minha omoplata”.
. Ou: “arrancado da sua articulação; arrancado do seu osso superior”.
====

[[v18-31-23]]

^<<v18-31-23,23>>^ Pois eu tinha pavor de sofrer uma calamidade da parte de Deus,
E não poderia ficar de pé diante da sua glória.

[[v18-31-24]]

^<<v18-31-24,24>>^ Se pus a minha confiança no ouro
Ou disse ao ouro puro: ‘Tu és a minha segurança!’;

[[v18-31-25]]

^<<v18-31-25,25>>^ Se me alegrei por ser grande a minha riqueza,
Por causa dos muitos bens que adquiri;

[[v18-31-26]]

^<<v18-31-26,26>>^ Se eu via o sol^&#42;1^ brilhar
Ou a lua mover-se no seu esplendor;

[NOTE]
====
. Lit.: “a luz”.
====

[[v18-31-27]]

^<<v18-31-27,27>>^ E o meu coração foi seduzido em segredo,
E a minha boca beijou a minha mão em adoração a eles,

[[v18-31-28]]

^<<v18-31-28,28>>^ Então, isso seria um erro que mereceria a punição dos juízes,
Pois eu teria negado o verdadeiro Deus de cima.

[[v18-31-29]]

^<<v18-31-29,29>>^ Será que alguma vez me alegrei com a destruição do meu inimigo
Ou fiquei feliz porque o mal o atingiu?

[[v18-31-30]]

^<<v18-31-30,30>>^ Nunca permiti que a minha boca pecasse,
Pedindo que a sua vida lhe fosse tirada^&#42;1^ através de uma maldição.

[NOTE]
====
. Ou: “Pedindo a sua alma”.
====

[[v18-31-31]]

^<<v18-31-31,31>>^ Será que as pessoas da minha tenda não disseram:
‘Quem pode encontrar alguém que não se saciou com a comida^&#42;1^ dele?’

[NOTE]
====
. Lit.: “carne”.
====

[[v18-31-32]]

^<<v18-31-32,32>>^ Nenhum estranho^&#42;1^ teve de passar a noite do lado de fora,
Eu abri as minhas portas para o viajante.

[NOTE]
====
. Ou: “residente estrangeiro”.
====

[[v18-31-33]]

^<<v18-31-33,33>>^ Será que já tentei encobrir as minhas transgressões como fazem outros homens,
Escondendo o meu erro no bolso da minha roupa?

[[v18-31-34]]

^<<v18-31-34,34>>^ Por acaso, temi a reação da multidão,
Ou fiquei aterrorizado com o desprezo de outras famílias,
A ponto de ficar quieto e com medo de ir para fora?

[[v18-31-35]]

^<<v18-31-35,35>>^ Quem me dera que alguém me escutasse!
Eu assinaria por baixo do que eu disse.^&#42;1^
Que o Todo-Poderoso me responda!
Quem me dera que o meu acusador tivesse escrito as acusações num documento!

[NOTE]
====
. Ou: “Aqui está a minha assinatura.”
====

[[v18-31-36]]

^<<v18-31-36,36>>^ Eu iria carregá-las sobre os ombros,
E iria colocá-las na minha cabeça como se fossem uma coroa.

[[v18-31-37]]

^<<v18-31-37,37>>^ Iria prestar-lhe contas de todos os meus passos,
E iria aproximar-me dele confiantemente, como um príncipe.

[[v18-31-38]]

^<<v18-31-38,38>>^ Se o meu solo clamou contra mim,
E todos os seus sulcos choraram;

[[v18-31-39]]

^<<v18-31-39,39>>^ Se comi os seus frutos sem pagar,
Ou se causei desespero aos seus donos,^&#42;1^

[NOTE]
====
. Ou: “à alma dos seus donos”.
====

[[v18-31-40]]

^<<v18-31-40,40>>^ Então, que nasçam para mim espinhos em vez de trigo
E ervas malcheirosas em vez de cevada.”
Aqui terminam as palavras de Jó.

'''

xref:018-jo/018-jo-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-jo/018-jo-032.adoc#v18-32-0[Próximo Capítulo &#62;]