include::./index.adoc[]

[[v18-16-0]]
=== Jó, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-16-1]]

^<<v18-16-1,1>>^ Jó disse em resposta:

[[v18-16-2]]

^<<v18-16-2,2>>^ “Já ouvi muitas coisas como essas.
Em vez de consolarem, vocês causam ainda mais aflição!

[[v18-16-3]]

^<<v18-16-3,3>>^ Será que estas palavras ocas^&#42;1^ não terão fim?
O que é que te leva a falar assim?

[NOTE]
====
. Ou: “de vento”.
====

[[v18-16-4]]

^<<v18-16-4,4>>^ Eu também poderia falar como vocês.
Se estivessem no meu lugar,^&#42;1^
Poderia fazer belos discursos contra vocês
E abanar a cabeça contra vocês.

[NOTE]
====
. Ou: “Se a vossa alma estivesse no lugar da minha alma”.
====

[[v18-16-5]]

^<<v18-16-5,5>>^ Contudo, em vez de fazer isso, iria fortalecer-vos com as palavras da minha boca,
E o consolo dos meus lábios traria alívio.

[[v18-16-6]]

^<<v18-16-6,6>>^ Se falo, a minha dor não alivia,
E, se paro de falar, até que ponto a minha dor diminui?

[[v18-16-7]]

^<<v18-16-7,7>>^ Mas, agora, ele fez-me ficar exausto;
Destruiu todos os da minha casa.^&#42;1^

[NOTE]
====
. Ou: “todos os que se reúnem comigo”.
====

[[v18-16-8]]

^<<v18-16-8,8>>^ Além disso, tu agarras-me, e isso dá testemunho contra mim,
E a minha própria magreza levanta-se e testemunha contra mim.

[[v18-16-9]]

^<<v18-16-9,9>>^ A ira dele dilacerou-me, e ele tem-me rancor.
Ele range os dentes contra mim.
O meu adversário trespassa-me com os olhos.

[[v18-16-10]]

^<<v18-16-10,10>>^ Eles abrem bem a boca para me devorar
E dão-me bofetadas com desprezo;
Unem-se contra mim em grande número.

[[v18-16-11]]

^<<v18-16-11,11>>^ Deus entrega-me a garotos,
E atira-me para as mãos dos maus.

[[v18-16-12]]

^<<v18-16-12,12>>^ Eu estava tranquilo, mas ele despedaçou-me;
Agarrou-me pela nuca e esmagou-me,
E fez de mim o seu alvo.

[[v18-16-13]]

^<<v18-16-13,13>>^ Os seus arqueiros cercam-me;
Ele trespassa-me os rins e não tem compaixão,
Derrama a minha bílis na terra.

[[v18-16-14]]

^<<v18-16-14,14>>^ Avança contra mim, abrindo sucessivas brechas;
Corre contra mim como um guerreiro.

[[v18-16-15]]

^<<v18-16-15,15>>^ Costurei serapilheira^&#42;1^ para cobrir a minha pele,
E enterrei a minha dignidade^&#42;2^ no pó.

[NOTE]
====
. Veja o Glossário.
. Ou: “a minha força”. Lit.: “o meu chifre”.
====

[[v18-16-16]]

^<<v18-16-16,16>>^ O meu rosto está vermelho de tanto chorar,
E há escuridão^&#42;1^ à volta dos meus olhos.

[NOTE]
====
. Ou: “sombra de morte”.
====

[[v18-16-17]]

^<<v18-16-17,17>>^ No entanto, não há violência nas minhas mãos,
E a minha oração é pura.

[[v18-16-18]]

^<<v18-16-18,18>>^ Ó terra, não cubras o meu sangue!
E que não haja nenhum lugar de descanso para o meu clamor!

[[v18-16-19]]

^<<v18-16-19,19>>^ Agora mesmo, a minha testemunha está nos céus;
Aquele que pode testemunhar a meu favor está nas alturas.

[[v18-16-20]]

^<<v18-16-20,20>>^ Os meus amigos ridicularizam-me,
Enquanto os meus olhos derramam lágrimas^&#42;1^ para Deus.

[NOTE]
====
. Ou, possivelmente: “olham sem sono”.
====

[[v18-16-21]]

^<<v18-16-21,21>>^ Que alguém julgue entre um homem e Deus,
Assim como acontece entre um homem e o seu próximo.

[[v18-16-22]]

^<<v18-16-22,22>>^ Pois os anos que restam são poucos,
E vou-me embora pelo caminho que não tem retorno.

'''

xref:018-jo/018-jo-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-jo/018-jo-017.adoc#v18-17-0[Próximo Capítulo &#62;]