include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-2-1]]

^<<v18-2-1,1>>^ Depois disso, chegou o dia em que os filhos do verdadeiro Deus^&#42;1^ foram apresentar-se perante Jeová, e Satanás também foi no meio deles para se apresentar perante Jeová.

[NOTE]
====
. Expressão idiomática hebraica que se refere aos filhos angélicos de Deus.
====

[[v18-2-2]]

^<<v18-2-2,2>>^ Então, Jeová perguntou a Satanás: “De onde vieste?” Satanás respondeu a Jeová: “De percorrer a terra e de andar por ela.”

[[v18-2-3]]

^<<v18-2-3,3>>^ E Jeová disse a Satanás: “Observaste o^&#42;1^ meu servo Jó? Não há ninguém igual a ele na terra. Ele é um homem íntegro^&#42;2^ e justo, que teme a Deus e rejeita o que é mau. Ele ainda se apega à sua integridade, apesar de me tentares pôr contra ele para o destruir^&#42;3^ sem nenhum motivo.”

[NOTE]
====
. Lit.: “fixaste o teu coração no”.
. Ou: “irrepreensível”.
. Lit.: “tragar”.
====

[[v18-2-4]]

^<<v18-2-4,4>>^ Contudo, Satanás disse a Jeová: “Pele por pele. O homem dará tudo o que tem pela sua vida.^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v18-2-5]]

^<<v18-2-5,5>>^ Mas, agora, levanta a mão e atinge os seus ossos e a sua carne, e de certeza que ele te vai amaldiçoar na tua própria face.”

[[v18-2-6]]

^<<v18-2-6,6>>^ Em seguida, Jeová disse a Satanás: “Pois bem, ele está nas tuas mãos.^&#42;1^ Mas não lhe tires a vida!”^&#42;2^

[NOTE]
====
. Ou: “sob o teu controlo”.
. Ou: “alma”.
====

[[v18-2-7]]

^<<v18-2-7,7>>^ Portanto, Satanás retirou-se da presença^&#42;1^ de Jeová e atingiu Jó com furúnculos dolorosos,^&#42;2^ desde a sola dos pés até ao alto da cabeça.

[NOTE]
====
. Lit.: “face”.
. Ou: “feridas graves”.
====

[[v18-2-8]]

^<<v18-2-8,8>>^ E Jó pegou num caco para se raspar e ficou sentado entre as cinzas.

[[v18-2-9]]

^<<v18-2-9,9>>^ Por fim, a sua esposa disse-lhe: “Ainda te apegas à tua integridade? Amaldiçoa a Deus e morre!”

[[v18-2-10]]

^<<v18-2-10,10>>^ Todavia, ele respondeu-lhe: “Estás a falar como uma mulher insensata. Devemos aceitar apenas o que é bom da parte do verdadeiro Deus e não aceitar também o que é mau?” Em tudo isto, Jó não pecou com os seus lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ Três amigos^&#42;1^ de Jó — Elifaz, o temanita, Bildade, o suíta, e Zofar, o naamatita — souberam de todas as desgraças que lhe tinham acontecido e vieram, cada um do seu lugar. Combinaram encontrar-se para demonstrarem solidariedade para com Jó e para o consolarem.

[NOTE]
====
. Ou: “conhecidos”.
====

[[v18-2-12]]

^<<v18-2-12,12>>^ Quando o viram de longe, não o reconheceram. Começaram a chorar em voz alta e a rasgar as suas roupas, e atiraram pó para o ar e sobre as suas cabeças.

[[v18-2-13]]

^<<v18-2-13,13>>^ A seguir, sentaram-se com ele no chão durante sete dias e sete noites. Ninguém lhe disse uma palavra, pois viram que a sua dor era muito grande.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]