include::./index.adoc[]

[[v18-40-0]]
=== Jó, 40
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-40-1]]

^<<v18-40-1,1>>^ Jeová continuou a responder a Jó:

[[v18-40-2]]

^<<v18-40-2,2>>^ “Deve aquele que critica discutir com o Todo-Poderoso?
Responda agora aquele que quer repreender a Deus.”

[[v18-40-3]]

^<<v18-40-3,3>>^ Jó disse em resposta a Jeová:

[[v18-40-4]]

^<<v18-40-4,4>>^ “Sou indigno!
O que é que te posso responder?
Ponho a mão sobre a boca.

[[v18-40-5]]

^<<v18-40-5,5>>^ Falei uma vez, mas não vou voltar a falar;
Duas vezes, mas não vou dizer mais nada.”

[[v18-40-6]]

^<<v18-40-6,6>>^ Então, Jeová respondeu a Jó do meio do vendaval:

[[v18-40-7]]

^<<v18-40-7,7>>^ “Por favor, prepara-te como um homem;
Eu irei fazer-te perguntas, e tu irás informar-me.

[[v18-40-8]]

^<<v18-40-8,8>>^ Questionarás^&#42;1^ a minha justiça?
Vais condenar-me, para teres razão?

[NOTE]
====
. Ou: “Invalidarás”.
====

[[v18-40-9]]

^<<v18-40-9,9>>^ Por acaso, tens um braço tão poderoso como o do verdadeiro Deus?
Ou pode a tua voz trovejar como a dele?

[[v18-40-10]]

^<<v18-40-10,10>>^ Por favor, adorna-te com glória e majestade,
Veste-te com dignidade e esplendor.

[[v18-40-11]]

^<<v18-40-11,11>>^ Dá vazão à tua ira;
Olha para todos os arrogantes e rebaixa-os.

[[v18-40-12]]

^<<v18-40-12,12>>^ Olha para todos os arrogantes e humilha-os,
E esmaga os maus onde eles estão.

[[v18-40-13]]

^<<v18-40-13,13>>^ Esconde-os a todos no pó;
Prende-os^&#42;1^ no lugar escondido,

[NOTE]
====
. Lit.: “Amarra as suas faces”.
====

[[v18-40-14]]

^<<v18-40-14,14>>^ Então, até eu admitirei^&#42;1^
Que a tua mão direita te pode salvar.

[NOTE]
====
. Ou: “te elogiarei”.
====

[[v18-40-15]]

^<<v18-40-15,15>>^ Vê o Beemote,^&#42;1^ que fiz assim como te fiz a ti.
Ele come erva como o touro.

[NOTE]
====
. Possivelmente, o hipopótamo.
====

[[v18-40-16]]

^<<v18-40-16,16>>^ Repara na força das suas ancas
E no poder dos músculos da sua barriga!

[[v18-40-17]]

^<<v18-40-17,17>>^ Ele endurece a cauda como um cedro;
Os tendões das suas coxas estão entrelaçados.

[[v18-40-18]]

^<<v18-40-18,18>>^ Os seus ossos são como tubos de cobre;
Os seus membros são como barras de ferro forjado.

[[v18-40-19]]

^<<v18-40-19,19>>^ Ele ocupa o primeiro lugar^&#42;1^ entre as obras de Deus;
Apenas Aquele que o fez se pode aproximar dele com uma espada.

[NOTE]
====
. Lit.: “É o princípio”.
====

[[v18-40-20]]

^<<v18-40-20,20>>^ O seu alimento é produzido pelos montes,
Onde todos os animais selvagens se divertem.

[[v18-40-21]]

^<<v18-40-21,21>>^ Ele deita-se debaixo dos lótus,
No abrigo dos juncos do pântano.

[[v18-40-22]]

^<<v18-40-22,22>>^ Os lótus cobrem-no com a sua sombra,
E os choupos do vale^&#42;1^ cercam-no.

[NOTE]
====
. Ou: “uádi”.
====

[[v18-40-23]]

^<<v18-40-23,23>>^ Quando o rio fica turbulento, ele não entra em pânico.
Mantém-se confiante, mesmo que as águas do Jordão venham com força contra a sua boca.

[[v18-40-24]]

^<<v18-40-24,24>>^ Será que alguém o pode capturar quando ele está a olhar,
Ou furar-lhe o nariz com um gancho?^&#42;1^

[NOTE]
====
. Lit.: “laço”.
====

'''

xref:018-jo/018-jo-039.adoc#v18-39-0[&#60; Capítulo Anterior] | <<v18-40-0,Topo>> | xref:018-jo/018-jo-041.adoc#v18-41-0[Próximo Capítulo &#62;]