include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-22-1]]

^<<v18-22-1,1>>^ Elifaz, o temanita, disse em resposta:

[[v18-22-2]]

^<<v18-22-2,2>>^ “Pode um homem ser útil para Deus?
Pode alguém com perspicácia ser-lhe de algum proveito?

[[v18-22-3]]

^<<v18-22-3,3>>^ Será que o Todo-Poderoso se importa^&#42;1^ que sejas justo,
Ou será que ele ganha alguma coisa por seres íntegro?

[NOTE]
====
. Ou: “Será que é do agrado do Todo-Poderoso”.
====

[[v18-22-4]]

^<<v18-22-4,4>>^ Por acaso, irá ele punir-te
E entrar em juízo contra ti por o temeres?

[[v18-22-5]]

^<<v18-22-5,5>>^ Não é porque a tua maldade é muito grande
E não há fim dos teus erros?

[[v18-22-6]]

^<<v18-22-6,6>>^ Pois exiges uma garantia dos teus irmãos sem nenhum motivo,
E tiras a roupa dos outros, deixando-os nus.^&#42;1^

[NOTE]
====
. Lit.: “tiras roupas dos nus”.
====

[[v18-22-7]]

^<<v18-22-7,7>>^ Não dás água ao cansado
E negas pão ao faminto.

[[v18-22-8]]

^<<v18-22-8,8>>^ A terra pertence ao homem poderoso,
E quem é favorecido mora nela.

[[v18-22-9]]

^<<v18-22-9,9>>^ Mas tu mandaste as viúvas embora de mãos vazias,
E partiste os braços dos órfãos.^&#42;1^

[NOTE]
====
. Ou: “órfãos de pai”.
====

[[v18-22-10]]

^<<v18-22-10,10>>^ É por isso que estás cercado de armadilhas,^&#42;1^
E que terrores repentinos te assustam;

[NOTE]
====
. Lit.: “armadilhas para pássaros”.
====

[[v18-22-11]]

^<<v18-22-11,11>>^ É por isso que a escuridão não te deixa ver,
E uma enxurrada de água te cobre.

[[v18-22-12]]

^<<v18-22-12,12>>^ Não está Deus no mais alto dos céus?
E vê como estão altas todas as estrelas.

[[v18-22-13]]

^<<v18-22-13,13>>^ No entanto, disseste: ‘O que é que Deus realmente sabe?
Será que pode julgar através de densas trevas?

[[v18-22-14]]

^<<v18-22-14,14>>^ As nuvens encobrem-no para que ele não veja,
Enquanto anda sobre a abóbada^&#42;1^ do céu.’

[NOTE]
====
. Ou: “o círculo”.
====

[[v18-22-15]]

^<<v18-22-15,15>>^ Por acaso, seguirás os caminhos antigos
Por onde andaram os maus,

[[v18-22-16]]

^<<v18-22-16,16>>^ Homens que foram levados^&#42;1^ antes do tempo,
Cujo alicerce foi arrastado por uma enxurrada?^&#42;2^

[NOTE]
====
. Ou: “cujas vidas foram abreviadas”.
. Lit.: “um rio”.
====

[[v18-22-17]]

^<<v18-22-17,17>>^ Eles diziam ao verdadeiro Deus: ‘Deixa-nos em paz!
O que é que o Todo-Poderoso pode fazer contra nós?’

[[v18-22-18]]

^<<v18-22-18,18>>^ Contudo, foi ele quem encheu a casa deles de coisas boas.
(Este pensamento mau está longe de mim.)

[[v18-22-19]]

^<<v18-22-19,19>>^ Os justos verão a destruição deles e irão alegrar-se,
E o inocente irá rir-se deles, dizendo:

[[v18-22-20]]

^<<v18-22-20,20>>^ ‘Os nossos adversários foram destruídos,
E um fogo consumirá o que deles sobrou.’

[[v18-22-21]]

^<<v18-22-21,21>>^ Conhece-O e ficarás em paz,
Assim, hão de sobrevir-te coisas boas.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceita a lei procedente da sua boca,
E guarda as suas declarações no coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se voltares ao Todo-Poderoso, serás restabelecido.
Se afastares a injustiça da tua tenda,

[[v18-22-24]]

^<<v18-22-24,24>>^ Se lançares o teu ouro^&#42;1^ no pó
E o ouro de Ofir entre as rochas dos vales,^&#42;2^

[NOTE]
====
. Ou: “as tuas pepitas de ouro”.
. Ou: “uádis”.
====

[[v18-22-25]]

^<<v18-22-25,25>>^ Então, o Todo-Poderoso será o teu ouro^&#42;1^
E a tua melhor prata.

[NOTE]
====
. Ou: “as tuas pepitas de ouro”.
====

[[v18-22-26]]

^<<v18-22-26,26>>^ Pois irás deleitar-te no Todo-Poderoso
E levantarás o teu rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ Irás fazer-lhe súplicas, e ele irá ouvir-te;
E cumprirás os teus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ O que decidires fazer será bem-sucedido,
E a luz brilhará sobre o teu caminho.

[[v18-22-29]]

^<<v18-22-29,29>>^ Pois, quando falares com arrogância, serás humilhado,
Mas ele salvará o humilde.^&#42;1^

[NOTE]
====
. Ou: “aquele que olha para baixo”.
====

[[v18-22-30]]

^<<v18-22-30,30>>^ Ele salvará os inocentes;
Assim, se as tuas mãos forem limpas, certamente serás salvo.”

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]