include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-36-1]]

^<<v18-36-1,1>>^ Eliú continuou:

[[v18-36-2]]

^<<v18-36-2,2>>^ “Tem um pouco mais de paciência comigo enquanto eu explico,
Pois ainda tenho palavras para dizer a favor de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ Direi tudo o que sei,
E declararei que a justiça pertence Àquele que me fez.

[[v18-36-4]]

^<<v18-36-4,4>>^ De facto, as minhas palavras não são falsas;
E Aquele que é perfeito em conhecimento está aqui, diante de ti.

[[v18-36-5]]

^<<v18-36-5,5>>^ Realmente, Deus é poderoso e não rejeita ninguém;
Ele tem grande entendimento.^&#42;1^

[NOTE]
====
. Ou: “Ele é grande em poder de coração”.
====

[[v18-36-6]]

^<<v18-36-6,6>>^ Não preservará a vida dos maus,
Mas fará justiça aos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Não desvia os seus olhos dos justos.
Ele fá-los sentar em tronos com reis,^&#42;1^ e eles são enaltecidos para sempre.

[NOTE]
====
. Ou, possivelmente: “Ele entroniza reis”.
====

[[v18-36-8]]

^<<v18-36-8,8>>^ No entanto, se eles são presos com correntes
E capturados com cordas de aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ Ele mostra-lhes o que fizeram,
As suas transgressões resultantes do seu orgulho.

[[v18-36-10]]

^<<v18-36-10,10>>^ Abre o ouvido deles para a correção
E diz-lhes para se afastarem do que é mau.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se lhe obedecerem e o servirem,
Terminarão os seus dias na prosperidade,
E os seus anos serão agradáveis.

[[v18-36-12]]

^<<v18-36-12,12>>^ Contudo, se não obedecerem, perecerão pela espada^&#42;1^
E morrerão sem conhecimento.

[NOTE]
====
. Ou: “por uma arma (arma de arremesso)”.
====

[[v18-36-13]]

^<<v18-36-13,13>>^ Os que têm coração ímpio^&#42;1^ guardarão ressentimento.
Não clamam por ajuda, mesmo quando ele os prende.

[NOTE]
====
. Ou: “apóstata”.
====

[[v18-36-14]]

^<<v18-36-14,14>>^ Eles morrem^&#42;1^ enquanto ainda são jovens,
Desperdiçam^&#42;2^ a vida entre os prostitutos de templo.

[NOTE]
====
. Ou: “A alma deles morre”.
. Ou, possivelmente: “Terminam”.
====

[[v18-36-15]]

^<<v18-36-15,15>>^ Deus,^&#42;1^ porém, salva os atribulados durante a sua aflição;
Abre-lhes os ouvidos quando são oprimidos.

[NOTE]
====
. Lit.: “Ele”.
====

[[v18-36-16]]

^<<v18-36-16,16>>^ Ele tira-te das garras da aflição
E leva-te a um lugar amplo, onde não há aperto,
E onde serás consolado com excelente comida na tua mesa.

[[v18-36-17]]

^<<v18-36-17,17>>^ Então, ficarás satisfeito com o julgamento dos maus,
Quando o julgamento for proferido e a justiça prevalecer.

[[v18-36-18]]

^<<v18-36-18,18>>^ Todavia, tem cuidado para que o furor não te leve a agir com rancor,^&#42;1^
E não te deixes desencaminhar por um grande suborno.

[NOTE]
====
. Ou: “bater as mãos com rancor”.
====

[[v18-36-19]]

^<<v18-36-19,19>>^ Será que o teu clamor por ajuda
Ou o teu esforço árduo te livrarão da aflição?

[[v18-36-20]]

^<<v18-36-20,20>>^ Não fiques a desejar que chegue a noite,
Quando as pessoas desaparecem do seu lugar.

[[v18-36-21]]

^<<v18-36-21,21>>^ Tem cuidado para não te voltares para o que é mau,
Escolhendo isto em vez de aceitares a tribulação.

[[v18-36-22]]

^<<v18-36-22,22>>^ Vê! Deus é sublime em poder.
Que instrutor é semelhante a ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem direcionou o^&#42;1^ seu caminho
Ou lhe disse: ‘O que fizeste é errado’?

[NOTE]
====
. Ou, possivelmente: “criticou o; exigiu dele uma prestação de contas pelo”.
====

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembra-te de enaltecer os seus atos,
Sobre os quais os homens cantam.

[[v18-36-25]]

^<<v18-36-25,25>>^ Todos os humanos os veem;
O homem mortal olha para eles de longe.

[[v18-36-26]]

^<<v18-36-26,26>>^ A grandeza de Deus está além da nossa compreensão;
O número dos seus anos foge ao nosso entendimento.^&#42;1^

[NOTE]
====
. Ou: “é insondável”.
====

[[v18-36-27]]

^<<v18-36-27,27>>^ Ele puxa para cima as gotas de água;
O vapor condensa-se para formar a chuva,

[[v18-36-28]]

^<<v18-36-28,28>>^ Então, as nuvens derramam-na,
Despejando-a sobre a humanidade.

[[v18-36-29]]

^<<v18-36-29,29>>^ Será que alguém pode entender as camadas de nuvens,
E os trovões que saem da sua tenda?^&#42;1^

[NOTE]
====
. Lit.: “barraca”.
====

[[v18-36-30]]

^<<v18-36-30,30>>^ Vê como ele estende o seu relâmpago^&#42;1^ sobre ela
E cobre as profundezas^&#42;2^ do mar.

[NOTE]
====
. Lit.: “a sua luz”.
. Lit.: “raízes”.
====

[[v18-36-31]]

^<<v18-36-31,31>>^ Através destas coisas, ele sustenta os^&#42;1^ povos;
Dá-lhes comida em abundância.

[NOTE]
====
. Ou, possivelmente: “defende a causa dos”.
====

[[v18-36-32]]

^<<v18-36-32,32>>^ Nas suas mãos, ele esconde o relâmpago,
E direciona-o contra o alvo.

[[v18-36-33]]

^<<v18-36-33,33>>^ O seu trovão anuncia-o,
Até mesmo o rebanho anuncia quem^&#42;1^ se aproxima.

[NOTE]
====
. Ou, possivelmente: “o que”.
====

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]