include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-15-1]]

^<<v18-15-1,1>>^ E Elifaz, o temanita, disse em resposta:

[[v18-15-2]]

^<<v18-15-2,2>>^ “Será que uma pessoa sábia responderia com argumentos vazios,^&#42;1^
Ou encheria a sua barriga com o vento leste?

[NOTE]
====
. Ou: “com conhecimento vazio como o vento”.
====

[[v18-15-3]]

^<<v18-15-3,3>>^ Argumentar com meras palavras é inútil,
E apenas falar não traz nenhum benefício.

[[v18-15-4]]

^<<v18-15-4,4>>^ Pois tu enfraqueces o temor de Deus
E menosprezas a devoção a Deus.

[[v18-15-5]]

^<<v18-15-5,5>>^ Pois o teu pecado determina o que dizes,^&#42;1^
E tu escolhes palavras astutas.

[NOTE]
====
. Ou: “o teu pecado ensina a tua boca”.
====

[[v18-15-6]]

^<<v18-15-6,6>>^ A tua própria boca te condena, não eu;
Os teus próprios lábios testemunham contra ti.

[[v18-15-7]]

^<<v18-15-7,7>>^ Será que foste o primeiro homem a nascer,
Ou foste dado à luz antes das colinas?

[[v18-15-8]]

^<<v18-15-8,8>>^ Por acaso, ouves a conversa confidencial de Deus,
Ou és só tu que tens sabedoria?

[[v18-15-9]]

^<<v18-15-9,9>>^ O que é que tu sabes que nós não sabemos?
O que é que tu entendes que nós não entendemos?

[[v18-15-10]]

^<<v18-15-10,10>>^ Entre nós estão os de cabelos brancos e os idosos,
Homens muito mais velhos do que o teu pai.

[[v18-15-11]]

^<<v18-15-11,11>>^ Não te são suficientes o consolo de Deus,
Ou as ternas palavras que te dizem?

[[v18-15-12]]

^<<v18-15-12,12>>^ Porque é que o teu coração é tão presunçoso,
E porque é que os teus olhos brilham de raiva?

[[v18-15-13]]

^<<v18-15-13,13>>^ Pois ficas furioso com^&#42;1^ o próprio Deus,
E deixas que palavras como estas saiam da tua própria boca.

[NOTE]
====
. Lit.: “voltas o teu espírito contra”.
====

[[v18-15-14]]

^<<v18-15-14,14>>^ Como é que o homem mortal pode ser puro?
Ou como é que alguém que nasceu de uma mulher pode ser justo?

[[v18-15-15]]

^<<v18-15-15,15>>^ Olha! Ele não confia nos seus santos,^&#42;1^
E nem mesmo os céus são puros aos seus olhos.

[NOTE]
====
. Ou: “anjos”.
====

[[v18-15-16]]

^<<v18-15-16,16>>^ Quanto mais alguém que é detestável e corrupto,
Um homem que bebe injustiça como água!

[[v18-15-17]]

^<<v18-15-17,17>>^ Vou dizer-te uma coisa; escuta-me!
Vou contar o que vi,

[[v18-15-18]]

^<<v18-15-18,18>>^ O que os sábios transmitiram, conforme receberam dos seus pais,
Coisas que eles não esconderam.

[[v18-15-19]]

^<<v18-15-19,19>>^ A terra foi-lhes dada apenas a eles,
E entre eles não passou nenhum estrangeiro.

[[v18-15-20]]

^<<v18-15-20,20>>^ Quem é mau é atormentado todos os dias,
Durante todos os anos reservados para o tirano.

[[v18-15-21]]

^<<v18-15-21,21>>^ Sons assustadores estão nos seus ouvidos;
Em tempos de paz, saqueadores atacam-no.

[[v18-15-22]]

^<<v18-15-22,22>>^ Ele não acredita que escapará da escuridão;
Está destinado à espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Ele vagueia à procura de comida,^&#42;1^ e diz: ‘Onde está?’
Ele sabe muito bem que o dia da escuridão está próximo.

[NOTE]
====
. Lit.: “pão”.
====

[[v18-15-24]]

^<<v18-15-24,24>>^ Aflição e angústia apavoram-no,
Vêm contra ele como um rei pronto para atacar.

[[v18-15-25]]

^<<v18-15-25,25>>^ Pois ele levanta a mão contra o próprio Deus
E tenta desafiar^&#42;1^ o Todo-Poderoso;

[NOTE]
====
. Ou: “tenta prevalecer contra”.
====

[[v18-15-26]]

^<<v18-15-26,26>>^ Corre contra Ele obstinadamente,
Com o seu escudo grosso e resistente;^&#42;1^

[NOTE]
====
. Lit.: “as suas protuberâncias grossas de escudos”.
====

[[v18-15-27]]

^<<v18-15-27,27>>^ O seu rosto está coberto de gordura,
E as suas ancas acumulam gordura.

[[v18-15-28]]

^<<v18-15-28,28>>^ Ele mora em cidades que serão destruídas,
Em casas onde ninguém morará,
Que se tornarão um monte de pedras.

[[v18-15-29]]

^<<v18-15-29,29>>^ Não enriquecerá, e os seus bens não se acumularão,
Nem as suas posses se espalharão pela terra.

[[v18-15-30]]

^<<v18-15-30,30>>^ Não escapará da escuridão;
Uma chama ressecará o seu ramo novo,^&#42;1^
E pelo sopro da boca de Deus^&#42;2^ ele desaparecerá.

[NOTE]
====
. Isto é, qualquer esperança de recuperação.
. Lit.: “sua boca”.
====

[[v18-15-31]]

^<<v18-15-31,31>>^ Ele não se deve desviar nem confiar no que é inútil,
Pois o que é inútil é o que receberá em troca;

[[v18-15-32]]

^<<v18-15-32,32>>^ Isso acontecerá antes de chegar o seu dia,
E os seus ramos nunca florescerão.

[[v18-15-33]]

^<<v18-15-33,33>>^ Será como uma videira cujas uvas verdes caem,
E como uma oliveira que perde as suas flores.

[[v18-15-34]]

^<<v18-15-34,34>>^ Pois o grupo dos ímpios^&#42;1^ é estéril,
E o fogo consumirá as tendas onde há suborno.

[NOTE]
====
. Ou: “apóstatas”.
====

[[v18-15-35]]

^<<v18-15-35,35>>^ Eles concebem desgraça e dão à luz o que é mau,
E o seu ventre produz engano.”

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]