include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-20-1]]

^<<v18-20-1,1>>^ Zofar, o naamatita, disse em resposta:

[[v18-20-2]]

^<<v18-20-2,2>>^ “É por isto que pensamentos inquietantes me obrigam a responder,
Por causa da agitação que sinto.

[[v18-20-3]]

^<<v18-20-3,3>>^ A repreensão que ouvi é um insulto para mim;
E o meu entendimento^&#42;1^ impele-me a responder.

[NOTE]
====
. Lit.: “um espírito do meu entendimento”.
====

[[v18-20-4]]

^<<v18-20-4,4>>^ De certeza que sempre soubeste disto,
Pois tem sido assim desde que o homem foi posto^&#42;1^ na terra,

[NOTE]
====
. Ou: “a humanidade foi posta; Adão foi posto”.
====

[[v18-20-5]]

^<<v18-20-5,5>>^ Que o grito de alegria de quem é mau é passageiro,
E que a alegria do ímpio^&#42;1^ só dura um instante.

[NOTE]
====
. Ou: “apóstata”.
====

[[v18-20-6]]

^<<v18-20-6,6>>^ Embora a sua estatura chegue ao céu,
E a sua cabeça alcance as nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ Ele desaparecerá para sempre, assim como as suas próprias fezes;
Os que o costumavam ver perguntarão: ‘Onde é que ele está?’

[[v18-20-8]]

^<<v18-20-8,8>>^ Voará como um sonho, e não o encontrarão;
Desaparecerá como uma visão da noite.

[[v18-20-9]]

^<<v18-20-9,9>>^ Os olhos que o viram já não o voltarão a ver,
E o lugar onde ele morava não o voltará a ver.

[[v18-20-10]]

^<<v18-20-10,10>>^ Os seus filhos procurarão o favor dos pobres,
E as mãos dele devolverão a sua riqueza.

[[v18-20-11]]

^<<v18-20-11,11>>^ Os seus ossos estavam cheios do vigor da juventude,
No entanto, esse^&#42;1^ irá deitar-se com ele no pó.

[NOTE]
====
. Isto é, o seu vigor.
====

[[v18-20-12]]

^<<v18-20-12,12>>^ Se o que é mau for doce na sua boca,
Se ele o esconder debaixo da língua,

[[v18-20-13]]

^<<v18-20-13,13>>^ Se o saborear e não o largar,
Mas o mantiver na boca,

[[v18-20-14]]

^<<v18-20-14,14>>^ A sua comida azedará dentro dele;
No seu interior, será como o veneno^&#42;1^ de najas.

[NOTE]
====
. Ou: “a bílis”.
====

[[v18-20-15]]

^<<v18-20-15,15>>^ Ele engoliu riqueza, mas irá vomitá-la,
Deus irá eliminá-la da sua barriga.

[[v18-20-16]]

^<<v18-20-16,16>>^ Ele sugará o veneno de najas;
As presas^&#42;1^ de uma víbora irão matá-lo.

[NOTE]
====
. Lit.: “A língua”.
====

[[v18-20-17]]

^<<v18-20-17,17>>^ Ele nunca verá as correntes de água,
As torrentes de mel e de manteiga.

[[v18-20-18]]

^<<v18-20-18,18>>^ Devolverá os seus bens sem os consumir;^&#42;1^
Não usufruirá a riqueza proveniente dos seus negócios.

[NOTE]
====
. Lit.: “e não engolirá”.
====

[[v18-20-19]]

^<<v18-20-19,19>>^ Pois esmagou e abandonou o pobre;
Apoderou-se de uma casa que não construiu.

[[v18-20-20]]

^<<v18-20-20,20>>^ Mas ele não terá paz interior;
A sua riqueza não o ajudará a salvar-se.

[[v18-20-21]]

^<<v18-20-21,21>>^ Não lhe sobrou nada para devorar;
É por isso que a sua prosperidade não durará.

[[v18-20-22]]

^<<v18-20-22,22>>^ Quando a sua riqueza estiver no auge, a ansiedade irá dominá-lo;
A desgraça virá contra ele com toda a força.

[[v18-20-23]]

^<<v18-20-23,23>>^ Quando encher a barriga,
Deus^&#42;1^ irá enviar-lhe a sua ira ardente,
Fazendo-a chover sobre ele, até lhe atingir as vísceras.

[NOTE]
====
. Lit.: “Ele”.
====

[[v18-20-24]]

^<<v18-20-24,24>>^ Quando ele fugir das armas de ferro,
Flechas de um arco de cobre irão trespassá-lo.

[[v18-20-25]]

^<<v18-20-25,25>>^ Ele arranca uma flecha das costas,
Tira uma flecha brilhante do fígado;^&#42;1^
E o terror apodera-se dele.

[NOTE]
====
. Ou: “da bílis”.
====

[[v18-20-26]]

^<<v18-20-26,26>>^ Completa escuridão estará à espera das suas riquezas;
Um fogo que ninguém atiçou irá consumi-lo;
A calamidade espera pelos que restarem na sua tenda.

[[v18-20-27]]

^<<v18-20-27,27>>^ O céu revelará o seu erro;
A terra irá levantar-se contra ele.

[[v18-20-28]]

^<<v18-20-28,28>>^ Uma inundação arrastará a sua casa;
Será uma forte torrente no dia da ira de Deus.^&#42;1^

[NOTE]
====
. Lit.: “dele”.
====

[[v18-20-29]]

^<<v18-20-29,29>>^ Esta é a porção da parte de Deus para aquele que é mau,
A herança que Deus determinou para ele.”

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]