include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-11-1]]

^<<v18-11-1,1>>^ Zofar, o naamatita, disse em resposta:

[[v18-11-2]]

^<<v18-11-2,2>>^ “Será que todas estas palavras ficarão sem resposta,
Ou será que muita conversa faz alguém ter razão?^&#42;1^

[NOTE]
====
. Ou: “será que aquele que se gaba terá razão”.
====

[[v18-11-3]]

^<<v18-11-3,3>>^ Por acaso, a tua conversa vã calará as pessoas?
Ninguém te censurará por causa das tuas palavras de gozo?

[[v18-11-4]]

^<<v18-11-4,4>>^ Pois tu dizes: ‘O que eu ensino é puro,
E sou limpo aos teus olhos.’

[[v18-11-5]]

^<<v18-11-5,5>>^ Quem me dera que Deus falasse
E abrisse os seus lábios para ti!

[[v18-11-6]]

^<<v18-11-6,6>>^ Então, ele iria revelar-te os segredos da sabedoria,
Pois a sabedoria prática tem muitas facetas.
E tu entenderias que Deus esquece alguns dos teus erros.

[[v18-11-7]]

^<<v18-11-7,7>>^ Por acaso podes descobrir as coisas profundas de Deus
Ou descobrir tudo sobre o^&#42;1^ Todo-Poderoso?

[NOTE]
====
. Ou: “encontrar o limite do”.
====

[[v18-11-8]]

^<<v18-11-8,8>>^ Ela^&#42;1^ é mais alta do que o céu. O que é que tu podes fazer?
Ela é mais profunda do que a Sepultura.^&#42;2^ O que é que tu podes saber?

[NOTE]
====
. Isto é, a sabedoria.
. Ou: “o Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v18-11-9]]

^<<v18-11-9,9>>^ É mais extensa do que a terra
E mais ampla do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se ele vem para prender alguém e o leva a tribunal,
Quem o pode impedir?

[[v18-11-11]]

^<<v18-11-11,11>>^ Pois ele sabe quando os homens são falsos.
Quando vê a maldade, será que não presta atenção?

[[v18-11-12]]

^<<v18-11-12,12>>^ Contudo, um homem tolo só entenderá
Quando um jumento selvagem der à luz um homem.^&#42;1^

[NOTE]
====
. Ou: “Quando um jumento selvagem nascer homem”.
====

[[v18-11-13]]

^<<v18-11-13,13>>^ Se apenas preparasses o coração
E lhe estendesses as mãos!

[[v18-11-14]]

^<<v18-11-14,14>>^ Afasta das tuas mãos o que estiveres a fazer de errado,
E não deixes nenhuma injustiça morar nas tuas tendas,

[[v18-11-15]]

^<<v18-11-15,15>>^ Então, poderás erguer a cabeça sem te envergonhares;
Poderás manter-te firme, sem ter medo.

[[v18-11-16]]

^<<v18-11-16,16>>^ Pois, então, irás esquecer-te da tua desgraça,
Irás lembrar-te dela como se fossem águas passadas.

[[v18-11-17]]

^<<v18-11-17,17>>^ A tua vida irá tornar-se mais clara do que o meio-dia;
Até mesmo a escuridão será como a manhã.

[[v18-11-18]]

^<<v18-11-18,18>>^ Estarás confiante porque há esperança,
Olharás em volta e irás deitar-te em segurança.

[[v18-11-19]]

^<<v18-11-19,19>>^ Irás deitar-te sem que ninguém te faça ter medo,
E muitos procurarão ganhar o teu favor.

[[v18-11-20]]

^<<v18-11-20,20>>^ Porém, os olhos dos maus falharão;
Eles não encontrarão nenhum lugar para onde fugir,
E a sua única esperança será a morte.”^&#42;1^

[NOTE]
====
. Ou: “a expiração da alma”.
====

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]