include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-32-1]]

^<<v18-32-1,1>>^ Portanto, os três homens desistiram de responder a Jó, porque ele estava convicto da sua própria justiça.^&#42;1^

[NOTE]
====
. Ou: “porque ele era justo aos seus próprios olhos”.
====

[[v18-32-2]]

^<<v18-32-2,2>>^ Contudo, Eliú, filho de Baraquel, o buzita, da família de Rão, tinha ficado muito zangado. A sua ira acendeu-se contra Jó, porque ele tentou provar que ele^&#42;1^ tinha razão, e não Deus.

[NOTE]
====
. Ou: “a sua alma”.
====

[[v18-32-3]]

^<<v18-32-3,3>>^ Ele também ficou muito zangado com os três amigos de Jó, porque não conseguiram encontrar uma resposta, mas tinham declarado que Deus era culpado.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú tinha esperado para responder a Jó, pois eles eram mais velhos do que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Quando Eliú viu que os três homens não tinham nada para dizer em resposta, a sua ira acendeu-se.

[[v18-32-6]]

^<<v18-32-6,6>>^ Portanto, Eliú, filho de Baraquel, o buzita, começou a falar e disse:
“Eu sou jovem,^&#42;1^
E vocês são idosos.
Por isso, respeitosamente, eu contive-me
E não me atrevi a dizer-vos o que sei.

[NOTE]
====
. Lit.: “pequeno em dias”.
====

[[v18-32-7]]

^<<v18-32-7,7>>^ Eu disse a mim mesmo: ‘Que fale a idade,^&#42;1^
E que a multidão de anos declare a sabedoria.’

[NOTE]
====
. Lit.: “falem os dias”.
====

[[v18-32-8]]

^<<v18-32-8,8>>^ No entanto, é o espírito que está nas pessoas,
O fôlego do Todo-Poderoso, que lhes dá entendimento.

[[v18-32-9]]

^<<v18-32-9,9>>^ A idade em si não torna^&#42;1^ ninguém sábio,
Nem são apenas os idosos que sabem o que é certo.

[NOTE]
====
. Ou: “Muitos dias em si não tornam”.
====

[[v18-32-10]]

^<<v18-32-10,10>>^ Por isso, eu digo: ‘Escuta-me,
E eu também te direi o que sei.’

[[v18-32-11]]

^<<v18-32-11,11>>^ Vejam! Esperei que falassem;
Fiquei a ouvir os vossos raciocínios,
Enquanto procuravam o que dizer.

[[v18-32-12]]

^<<v18-32-12,12>>^ Escutei-vos com muita atenção,
Mas nenhum de vocês conseguiu provar que Jó estava errado,^&#42;1^
Nem responder aos seus argumentos.

[NOTE]
====
. Ou: “repreender Jó”.
====

[[v18-32-13]]

^<<v18-32-13,13>>^ Por isso, não digam: ‘Encontrámos a sabedoria;
É Deus quem o censura, não um homem.’

[[v18-32-14]]

^<<v18-32-14,14>>^ Jó não dirigiu palavras contra mim,
Portanto, não lhe responderei com os mesmos argumentos que vocês.

[[v18-32-15]]

^<<v18-32-15,15>>^ Estão desconcertados, já não têm respostas;
Não têm mais nada a dizer.

[[v18-32-16]]

^<<v18-32-16,16>>^ Espero, mas não continuam a falar;
Ficam aí parados, sem mais nenhuma resposta.

[[v18-32-17]]

^<<v18-32-17,17>>^ Então, eu também darei uma resposta;
Também direi o que sei,

[[v18-32-18]]

^<<v18-32-18,18>>^ Pois tenho muitas palavras para dizer;
O espírito dentro de mim obriga-me a falar.

[[v18-32-19]]

^<<v18-32-19,19>>^ Por dentro, estou como o vinho sem abertura para respirar,
Como odres novos a ponto de estourar.

[[v18-32-20]]

^<<v18-32-20,20>>^ Deixem-me falar, para que eu fique aliviado.
Abrirei os meus lábios e responderei.

[[v18-32-21]]

^<<v18-32-21,21>>^ Não mostrarei parcialidade a favor de ninguém;
Não bajularei^&#42;1^ nenhum homem,

[NOTE]
====
. Ou: “Não conferirei um título honorífico a”.
====

[[v18-32-22]]

^<<v18-32-22,22>>^ Pois não sei bajular;
Se eu o fizesse, Aquele que me fez iria eliminar-me rapidamente.

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]