include::./index.adoc[]

[[v18-14-0]]
=== Jó, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-14-1]]

^<<v18-14-1,1>>^ “O homem, nascido de mulher,
Tem vida curta e está cheio de preocupações.^&#42;1^

[NOTE]
====
. Ou: “empanturrado de agitação”.
====

[[v18-14-2]]

^<<v18-14-2,2>>^ Ele brota como uma flor, e depois murcha;^&#42;1^
Foge como uma sombra e desaparece.

[NOTE]
====
. Ou, possivelmente: “e é cortado”.
====

[[v18-14-3]]

^<<v18-14-3,3>>^ Tu fixas nele o teu olhar,
E leva-lo^&#42;1^ a julgamento contra ti.

[NOTE]
====
. Lit.: “levas-me”.
====

[[v18-14-4]]

^<<v18-14-4,4>>^ Quem pode produzir alguém puro de alguém impuro?
Ninguém!

[[v18-14-5]]

^<<v18-14-5,5>>^ Se os dias dele estão determinados,
O número dos seus meses está sob o teu controlo.
Fixaste-lhe um limite que ele não pode ultrapassar.

[[v18-14-6]]

^<<v18-14-6,6>>^ Desvia dele o teu olhar, para que ele descanse,
Até que cumpra o seu dia, assim como um trabalhador contratado.

[[v18-14-7]]

^<<v18-14-7,7>>^ Pois até mesmo para uma árvore há esperança.
Se for cortada, brotará outra vez
E os seus raminhos continuarão a crescer.

[[v18-14-8]]

^<<v18-14-8,8>>^ Caso a sua raiz envelheça na terra
E o seu toco morra no solo,

[[v18-14-9]]

^<<v18-14-9,9>>^ Ao cheiro da água, brotará,
E produzirá ramos, como se fosse uma planta nova.

[[v18-14-10]]

^<<v18-14-10,10>>^ No entanto, o homem morre e fica impotente;
Quando um humano dá o último suspiro, para onde é que ele vai?

[[v18-14-11]]

^<<v18-14-11,11>>^ As águas desaparecem do mar,
E o rio escoa e seca.

[[v18-14-12]]

^<<v18-14-12,12>>^ Assim também o homem se deita e não se levanta.
Não acordará até que já não haja céu,
Nem será despertado do seu sono.

[[v18-14-13]]

^<<v18-14-13,13>>^ Quem me dera que me escondesses na Sepultura,^&#42;1^
Que me ocultasses até a tua ira passar,
Que me estabelecesses um limite de tempo e então te lembrasses de mim!

[NOTE]
====
. Ou: “no Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v18-14-14]]

^<<v18-14-14,14>>^ Quando um homem morre, pode ele voltar a viver?
Esperarei todos os dias do meu serviço obrigatório,
Até vir a minha libertação.^&#42;1^

[NOTE]
====
. Ou: “a minha substituição”.
====

[[v18-14-15]]

^<<v18-14-15,15>>^ Tu chamarás, e eu irei responder-te.
Terás saudades do^&#42;1^ trabalho das tuas mãos.

[NOTE]
====
. Ou: “Ansiarás o”.
====

[[v18-14-16]]

^<<v18-14-16,16>>^ Mas, agora, estás a contar cada um dos meus passos;
Procuras apenas o meu pecado.

[[v18-14-17]]

^<<v18-14-17,17>>^ A minha transgressão está num saco bem fechado,
E selas o meu erro com cola.

[[v18-14-18]]

^<<v18-14-18,18>>^ Assim como uma montanha se desmorona e desintegra,
E uma rocha se desloca do lugar,

[[v18-14-19]]

^<<v18-14-19,19>>^ Assim como a água desgasta as pedras
E as suas torrentes levam o solo,
Da mesma maneira, tu destróis a esperança do homem mortal.

[[v18-14-20]]

^<<v18-14-20,20>>^ Prevaleces sobre ele até ele morrer;
Mudas-lhe a aparência e manda-lo embora.

[[v18-14-21]]

^<<v18-14-21,21>>^ Os seus filhos são honrados, mas ele não sabe disso;
Tornam-se insignificantes, mas ele não se apercebe disso.

[[v18-14-22]]

^<<v18-14-22,22>>^ Ele só sente a dor do seu próprio corpo;^&#42;1^
Ele^&#42;2^ só chora enquanto está vivo.”

[NOTE]
====
. Ou: “sente dor enquanto a sua carne ainda está nele”.
. Ou: “A sua alma”.
====

'''

xref:018-jo/018-jo-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-jo/018-jo-015.adoc#v18-15-0[Próximo Capítulo &#62;]