include::./index.adoc[]

[[v18-39-0]]
=== Jó, 39
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-39-1]]

^<<v18-39-1,1>>^ “Por acaso, sabes quando nascem os filhos das cabras-montesas?
Já viste as corças darem à luz as suas crias?

[[v18-39-2]]

^<<v18-39-2,2>>^ Contas os meses da sua gestação?
Sabes quando é que vão dar à luz?

[[v18-39-3]]

^<<v18-39-3,3>>^ Elas agacham-se para dar à luz as suas crias,
E as suas dores de parto terminam.

[[v18-39-4]]

^<<v18-39-4,4>>^ As suas crias ficam fortes e crescem nos campos;
Vão-se embora e não voltam mais.

[[v18-39-5]]

^<<v18-39-5,5>>^ Quem pôs o jumento selvagem^&#42;1^ em liberdade,
E quem soltou as cordas do jumento selvagem?

[NOTE]
====
. Ou: “o onagro”.
====

[[v18-39-6]]

^<<v18-39-6,6>>^ Fiz da planície desértica a sua habitação,
E da terra salgada a sua moradia.

[[v18-39-7]]

^<<v18-39-7,7>>^ Ele despreza a agitação da cidade,
Não ouve os gritos do condutor.

[[v18-39-8]]

^<<v18-39-8,8>>^ Vagueia pelas colinas em busca de pasto,
À procura de todo o tipo de plantas verdes.

[[v18-39-9]]

^<<v18-39-9,9>>^ Será que o touro selvagem vai querer servir-te?
Será que ele vai passar a noite no teu estábulo?^&#42;1^

[NOTE]
====
. Ou: “na tua manjedoura”.
====

[[v18-39-10]]

^<<v18-39-10,10>>^ Por acaso, podes prender o touro selvagem ao arado^&#42;1^ com uma corda,
Ou será que ele te seguirá para lavrar^&#42;2^ o vale?

[NOTE]
====
. Lit.: “sulco”.
. Ou: “gradar”.
====

[[v18-39-11]]

^<<v18-39-11,11>>^ Confiarás na sua grande força
E deixarás que faça o trabalho pesado por ti?

[[v18-39-12]]

^<<v18-39-12,12>>^ Por acaso, contarás com ele para que traga a tua colheita^&#42;1^
E a ajunte na tua eira?

[NOTE]
====
. Lit.: “semente”.
====

[[v18-39-13]]

^<<v18-39-13,13>>^ As asas da avestruz batem alegremente,
Mas será que as suas asas e plumagem se comparam às da cegonha?

[[v18-39-14]]

^<<v18-39-14,14>>^ Ela deixa os seus ovos no chão
E mantém-nos aquecidos no pó.

[[v18-39-15]]

^<<v18-39-15,15>>^ Ela esquece-se de que alguém os pode pisar,
Ou que um animal selvagem os pode esmagar.

[[v18-39-16]]

^<<v18-39-16,16>>^ Trata as suas crias com dureza, como se não fossem suas;
Não se importa que o seu trabalho tenha sido em vão.

[[v18-39-17]]

^<<v18-39-17,17>>^ Pois Deus negou-lhe^&#42;1^ sabedoria
E não lhe deu entendimento.

[NOTE]
====
. Lit.: “fê-la esquecer a”.
====

[[v18-39-18]]

^<<v18-39-18,18>>^ Contudo, quando se levanta e bate as asas,
Ri-se do cavalo e do cavaleiro.

[[v18-39-19]]

^<<v18-39-19,19>>^ És tu que dás força ao cavalo,
E vestes o seu pescoço com uma crina esvoaçante?

[[v18-39-20]]

^<<v18-39-20,20>>^ Será que o podes fazer saltar como um gafanhoto?
O seu relinchar^&#42;1^ majestoso é atemorizante.

[NOTE]
====
. Lit.: “bufar”.
====

[[v18-39-21]]

^<<v18-39-21,21>>^ Ele escarva o chão do vale e alegra-se muito;^&#42;1^
Sai a correr para a batalha.^&#42;2^

[NOTE]
====
. Lit.: “alegra-se em poder”.
. Lit.: “Sai para enfrentar armamento”.
====

[[v18-39-22]]

^<<v18-39-22,22>>^ Ele ri-se do medo e não se assusta com nada,
Não recua por causa da espada.

[[v18-39-23]]

^<<v18-39-23,23>>^ Sobre ele a aljava chocalha;
A lança e o dardo brilham.

[[v18-39-24]]

^<<v18-39-24,24>>^ A tremer e agitado, ele sai a galopar,^&#42;1^
Não consegue ficar parado ao^&#42;2^ som da buzina.

[NOTE]
====
. Lit.: “devora o chão (a terra)”.
. Ou, possivelmente: “Ele não acredita no”.
====

[[v18-39-25]]

^<<v18-39-25,25>>^ Ao toque da buzina, ele relincha.
De longe, sente o cheiro da batalha
E ouve os gritos dos comandantes e o grito de guerra.

[[v18-39-26]]

^<<v18-39-26,26>>^ Será que é por causa do teu entendimento que o falcão plana,
Estendendo as suas asas para o sul?

[[v18-39-27]]

^<<v18-39-27,27>>^ Ou é às tuas ordens que a águia voa para cima
E constrói no alto o seu ninho,

[[v18-39-28]]

^<<v18-39-28,28>>^ Passando a noite num rochedo,
Na fortaleza onde vive, num penhasco?^&#42;1^

[NOTE]
====
. Lit.: “no dente de um rochedo”.
====

[[v18-39-29]]

^<<v18-39-29,29>>^ De lá, ela procura alimento,
Os seus olhos veem a uma grande distância.

[[v18-39-30]]

^<<v18-39-30,30>>^ Os seus filhotes bebem sangue;
E onde há mortos, lá está ela.”

'''

xref:018-jo/018-jo-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-jo/018-jo-040.adoc#v18-40-0[Próximo Capítulo &#62;]