include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-18-1]]

^<<v18-18-1,1>>^ Bildade, o suíta, disse em resposta:

[[v18-18-2]]

^<<v18-18-2,2>>^ “Até quando vais continuar a dizer estas coisas?
Mostra algum entendimento, e depois conversamos.

[[v18-18-3]]

^<<v18-18-3,3>>^ Porque é que devíamos ser vistos como animais
E ser considerados tolos^&#42;1^ aos teus olhos?

[NOTE]
====
. Ou, possivelmente: “impuros”.
====

[[v18-18-4]]

^<<v18-18-4,4>>^ Mesmo que te dilaceres^&#42;1^ na tua ira,
Será que a terra vai ser abandonada por tua causa,
Ou as rochas vão mudar de lugar?

[NOTE]
====
. Ou: “dilaceres a tua alma”.
====

[[v18-18-5]]

^<<v18-18-5,5>>^ Sim, a luz de quem é mau será apagada,
E a chama do seu fogo deixará de brilhar.

[[v18-18-6]]

^<<v18-18-6,6>>^ A luz na sua tenda certamente escurecerá,
E a lâmpada por cima dele será apagada.

[[v18-18-7]]

^<<v18-18-7,7>>^ Os seus passos vigorosos serão encurtados,
E os seus próprios planos vão fazê-lo cair.

[[v18-18-8]]

^<<v18-18-8,8>>^ Pois os seus pés vão levá-lo a uma rede de caça,
Ele vagueará e cairá nas suas malhas.

[[v18-18-9]]

^<<v18-18-9,9>>^ Uma armadilha vai prendê-lo pelo calcanhar;
Um laço vai apanhá-lo.

[[v18-18-10]]

^<<v18-18-10,10>>^ Há uma corda escondida para ele no chão,
E há uma armadilha no seu caminho.

[[v18-18-11]]

^<<v18-18-11,11>>^ Terrores assustam-no por todos os lados
E perseguem-no a cada passo.

[[v18-18-12]]

^<<v18-18-12,12>>^ A sua força diminui,
E a desgraça vai fazê-lo cambalear.^&#42;1^

[NOTE]
====
. Ou: “coxear”.
====

[[v18-18-13]]

^<<v18-18-13,13>>^ A sua pele é consumida;
A doença mais mortífera^&#42;1^ devora-lhe os membros.

[NOTE]
====
. Lit.: “O primogénito da morte”.
====

[[v18-18-14]]

^<<v18-18-14,14>>^ Ele é arrancado da segurança da sua tenda
E conduzido ao rei dos terrores.^&#42;1^

[NOTE]
====
. Ou: “a uma morte terrível”.
====

[[v18-18-15]]

^<<v18-18-15,15>>^ Estranhos morarão^&#42;1^ na sua tenda;
Enxofre será espalhado pela sua casa.

[NOTE]
====
. Lit.: “Algo que não é dele morará”.
====

[[v18-18-16]]

^<<v18-18-16,16>>^ As suas raízes vão secar-se por baixo dele,
E, por cima, os seus ramos murcharão.

[[v18-18-17]]

^<<v18-18-17,17>>^ A lembrança que há dele desaparecerá da terra,
E o seu nome será desconhecido^&#42;1^ nas ruas.

[NOTE]
====
. Lit.: “ele não terá nome”.
====

[[v18-18-18]]

^<<v18-18-18,18>>^ Ele será expulso da luz para a escuridão
E será banido da terra produtiva.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não terá filhos nem descendentes entre o seu povo,
E não lhe restará nenhum sobrevivente no lugar onde vive.^&#42;1^

[NOTE]
====
. Ou: “no lugar da sua residência temporária”.
====

[[v18-18-20]]

^<<v18-18-20,20>>^ Quando chegar o seu dia, o povo do Ocidente ficará chocado,
E o povo do Oriente ficará horrorizado.

[[v18-18-21]]

^<<v18-18-21,21>>^ Isto é o que acontece às tendas do malfeitor
E ao lugar de quem não conhece a Deus.”

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]