include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-19-1]]

^<<v18-19-1,1>>^ Jó disse em resposta:

[[v18-19-2]]

^<<v18-19-2,2>>^ “Até quando continuarão a irritar-me,^&#42;1^
Esmagando-me com palavras?

[NOTE]
====
. Ou: “a irritar a minha alma”. Veja o Glossário, “Alma”.
====

[[v18-19-3]]

^<<v18-19-3,3>>^ Já me repreenderam^&#42;1^ dez vezes
E não se envergonham de me tratar de maneira dura.

[NOTE]
====
. Ou: “insultaram”.
====

[[v18-19-4]]

^<<v18-19-4,4>>^ E, se eu realmente cometi um erro,
O meu erro só me interessa a mim.

[[v18-19-5]]

^<<v18-19-5,5>>^ Se insistem em tratar-me com arrogância,
Por dizerem que a minha humilhação é merecida,

[[v18-19-6]]

^<<v18-19-6,6>>^ Saibam que foi Deus que me enganou,
E que me apanhou na sua rede de caça.

[[v18-19-7]]

^<<v18-19-7,7>>^ Ouçam! Eu clamo: ‘Sou alvo de violência!’, mas não obtenho resposta;
Estou a clamar por ajuda, mas não há justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ Ele bloqueia o meu caminho com um muro de pedras, e não consigo passar;
Ele cobriu as minhas veredas com escuridão.

[[v18-19-9]]

^<<v18-19-9,9>>^ Ele despiu-me da minha glória
E tirou-me a coroa da cabeça.

[[v18-19-10]]

^<<v18-19-10,10>>^ Ele quebra-me de todos os lados, até eu perecer;
Arranca-me a esperança como se faz a uma árvore.

[[v18-19-11]]

^<<v18-19-11,11>>^ A sua ira acende-se contra mim,
E ele considera-me seu inimigo.

[[v18-19-12]]

^<<v18-19-12,12>>^ As suas tropas avançam juntas e cercam-me,
E acampam à volta da minha tenda.

[[v18-19-13]]

^<<v18-19-13,13>>^ Ele pôs longe de mim os meus próprios irmãos,
E os que me conhecem afastaram-se de mim.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus amigos íntimos^&#42;1^ deixaram-me,
E os que eu conhecia bem esqueceram-se de mim.

[NOTE]
====
. Ou: “parentes”.
====

[[v18-19-15]]

^<<v18-19-15,15>>^ Os hóspedes na minha casa e as minhas escravas consideram-me um estranho;
Sou um estrangeiro aos seus olhos.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamo o meu servo, mas ele não responde;
Com a minha boca imploro-lhe compaixão.

[[v18-19-17]]

^<<v18-19-17,17>>^ O meu hálito tornou-se nojento para a minha esposa,
E o meu cheiro é repugnante para os meus irmãos.^&#42;1^

[NOTE]
====
. Lit.: “para os filhos do meu ventre”, isto é, do ventre que me deu à luz (o ventre da minha mãe).
====

[[v18-19-18]]

^<<v18-19-18,18>>^ Até as crianças me desprezam;
Quando me levanto, elas começam a fazer pouco de mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os meus amigos íntimos me detestam,
E os que eu amava voltam-se contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ O meu corpo ficou reduzido a pele e osso,
E eu escapo da morte por um fio.^&#42;1^

[NOTE]
====
. Lit.: “com a pele dos meus dentes”.
====

[[v18-19-21]]

^<<v18-19-21,21>>^ Tenham misericórdia de mim, meus amigos, tenham misericórdia de mim,
Pois a mão de Deus tocou-me.

[[v18-19-22]]

^<<v18-19-22,22>>^ Porque é que me continuam a perseguir, assim como Deus,
Atacando-me sem cessar?^&#42;1^

[NOTE]
====
. Lit.: “E não ficam satisfeitos com a minha carne”.
====

[[v18-19-23]]

^<<v18-19-23,23>>^ Quem me dera que as minhas palavras fossem registadas,
Que fossem escritas num livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ Quem me dera que fossem gravadas para sempre na rocha,
Com um instrumento^&#42;1^ de ferro e com chumbo!

[NOTE]
====
. Lit.: “estilo”. Veja o Glossário, “Estilo”.
====

[[v18-19-25]]

^<<v18-19-25,25>>^ Pois bem sei que o meu redentor^&#42;1^ está vivo;
Ele virá depois e levantar-se-á sobre a terra.^&#42;2^

[NOTE]
====
. Ou: “resgatador”.
. Lit.: “o pó”.
====

[[v18-19-26]]

^<<v18-19-26,26>>^ Depois de a minha pele ter sido consumida,
Mesmo assim, ainda neste meu corpo,^&#42;1^ verei a Deus;

[NOTE]
====
. Ou: “na minha carne”.
====

[[v18-19-27]]

^<<v18-19-27,27>>^ Irei vê-lo pessoalmente,
Os meus próprios olhos o verão, não os de outra pessoa.
Mas, no íntimo, sinto-me esmagado.^&#42;1^

[NOTE]
====
. Ou: “Os meus rins falharam no meu íntimo.”
====

[[v18-19-28]]

^<<v18-19-28,28>>^ Vocês dizem: ‘De que modo o estamos a perseguir?’,
Por acharem que eu sou a causa do problema.

[[v18-19-29]]

^<<v18-19-29,29>>^ Vocês é que devem temer a espada,
Pois a espada traz punição a quem comete erros;
Vocês deviam saber que há um juiz.”

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]