include::./index.adoc[]

[[v18-23-0]]
=== Jó, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v18-23-1]]

^<<v18-23-1,1>>^ Jó disse em resposta:

[[v18-23-2]]

^<<v18-23-2,2>>^ “Ainda hoje me queixo de forma obstinada;^&#42;1^
As minhas forças esgotaram-se por causa do meu gemido.

[NOTE]
====
. Ou: “a minha queixa é rebelde”.
====

[[v18-23-3]]

^<<v18-23-3,3>>^ Quem me dera saber onde encontrar a Deus!
Eu iria até ao seu lugar de morada.

[[v18-23-4]]

^<<v18-23-4,4>>^ Apresentaria a minha causa perante ele
E encheria a minha boca de argumentos.

[[v18-23-5]]

^<<v18-23-5,5>>^ Ficaria a saber o que ele me responderia
E prestaria atenção ao que ele me dissesse.

[[v18-23-6]]

^<<v18-23-6,6>>^ Será que ele se oporia a mim com o seu grande poder?
Não, de certeza que ele me ouviria.

[[v18-23-7]]

^<<v18-23-7,7>>^ Ali, o justo resolveria as questões com ele,
E eu seria absolvido de uma vez para sempre pelo meu Juiz.

[[v18-23-8]]

^<<v18-23-8,8>>^ Mas, se vou para o leste, ele não está lá;
E, se volto, não o consigo encontrar.

[[v18-23-9]]

^<<v18-23-9,9>>^ Quando ele está a trabalhar à esquerda, não o consigo ver;
Então, ele desvia-se para a direita, mas, ainda assim, não o vejo.

[[v18-23-10]]

^<<v18-23-10,10>>^ Contudo, ele conhece o caminho em que ando.
Depois de ele me ter testado, sairei como ouro refinado.

[[v18-23-11]]

^<<v18-23-11,11>>^ Os meus pés seguiram fielmente os seus passos;
Guardei o seu caminho sem me desviar.

[[v18-23-12]]

^<<v18-23-12,12>>^ Não me afastei do mandamento dos seus lábios.
Guardei as suas declarações no coração,^&#42;1^ mais do que se exigia de mim.^&#42;2^

[NOTE]
====
. Ou: “Entesourei as suas declarações”.
. Ou: “do que me foi prescrito”.
====

[[v18-23-13]]

^<<v18-23-13,13>>^ Quando ele toma uma decisão, quem o pode impedir?
Quando ele^&#42;1^ quer fazer alguma coisa, ele faz.

[NOTE]
====
. Ou: “a sua alma”.
====

[[v18-23-14]]

^<<v18-23-14,14>>^ Pois ele cumprirá plenamente o que determinou para mim,^&#42;1^
E tem muitas outras coisas semelhantes em reserva.

[NOTE]
====
. Ou: “me prescreveu”.
====

[[v18-23-15]]

^<<v18-23-15,15>>^ É por isso que me sinto perturbado por sua causa;
Quando penso nele, o meu temor aumenta.

[[v18-23-16]]

^<<v18-23-16,16>>^ Deus fez-me ficar desanimado,
E o Todo-Poderoso fez-me ficar com medo.

[[v18-23-17]]

^<<v18-23-17,17>>^ Porém, ainda não fui silenciado pela escuridão
Nem pelas trevas que me cobrem o rosto.

'''

xref:018-jo/018-jo-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-jo/018-jo-024.adoc#v18-24-0[Próximo Capítulo &#62;]