include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v54-5-1]]

^<<v54-5-1,1>>^ Não repreendas severamente um homem idoso. Em vez disso, aconselha-o bondosamente^&#42;1^ como a um pai; aos jovens, como a irmãos;

[NOTE]
====
. Ou: “suplica-lhe”.
====

[[v54-5-2]]

^<<v54-5-2,2>>^ às mulheres idosas, como a mães; às jovens, como a irmãs, com toda a castidade.

[[v54-5-3]]

^<<v54-5-3,3>>^ Mostra consideração pelas^&#42;1^ viúvas que são realmente viúvas.^&#42;2^

[NOTE]
====
. Lit.: “Honra as”.
. Ou: “viúvas que são realmente necessitadas”; isto é, que não têm quem as sustente.
====

[[v54-5-4]]

^<<v54-5-4,4>>^ Porém, se alguma viúva tiver filhos ou netos, que estes aprendam primeiro a praticar a devoção a Deus na sua própria família e a pagar aos seus pais e avós o que lhes é devido, pois isto é agradável à vista de Deus.

[[v54-5-5]]

^<<v54-5-5,5>>^ A viúva que é realmente viúva e desamparada deposita a sua esperança em Deus e persiste em súplicas e orações, noite e dia.

[[v54-5-6]]

^<<v54-5-6,6>>^ Contudo, a que se entrega aos prazeres já está morta, embora esteja viva.

[[v54-5-7]]

^<<v54-5-7,7>>^ Portanto, continua a dar estas instruções,^&#42;1^ para que elas sejam irrepreensíveis.

[NOTE]
====
. Ou: “estes mandamentos”.
====

[[v54-5-8]]

^<<v54-5-8,8>>^ Certamente, se alguém não provê o necessário para os seus, e especialmente para os membros da sua família, renega a fé e é pior do que alguém sem fé.

[[v54-5-9]]

^<<v54-5-9,9>>^ Deve ser colocada na lista a viúva que tenha pelo menos 60 anos de idade, que tenha sido esposa de um só marido,

[[v54-5-10]]

^<<v54-5-10,10>>^ que seja conhecida pelas suas boas obras, que tenha criado filhos, sido hospitaleira, lavado os pés dos santos, ajudado os que estavam em dificuldades e que se tenha dedicado a toda a boa obra.

[[v54-5-11]]

^<<v54-5-11,11>>^ No entanto, não coloques na lista as viúvas mais jovens, pois, quando os seus desejos sexuais se interpõem entre elas e o Cristo, querem casar-se.

[[v54-5-12]]

^<<v54-5-12,12>>^ E elas trazem condenação sobre si mesmas por abandonarem a sua primeira expressão de fé.^&#42;1^

[NOTE]
====
. Ou: “a promessa que tinham feito”.
====

[[v54-5-13]]

^<<v54-5-13,13>>^ Ao mesmo tempo, também se habituam a ficar desocupadas, vadiando pelas casas; e não se tornam apenas desocupadas, mas também tagarelas e intrometidas nos assuntos dos outros, falando de coisas de que não devem.

[[v54-5-14]]

^<<v54-5-14,14>>^ Portanto, desejo que as viúvas mais jovens se casem, tenham filhos e cuidem de uma casa, não dando ao opositor oportunidade para criticar.

[[v54-5-15]]

^<<v54-5-15,15>>^ Na verdade, algumas já se desviaram para seguir Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma mulher crente tem viúvas na família, que ela as ajude, para que não se ponha esse fardo sobre a congregação. Esta poderá então ajudar as viúvas que são realmente viúvas.^&#42;1^

[NOTE]
====
. Ou: “viúvas que são realmente necessitadas”; isto é, que não têm quem as sustente.
====

[[v54-5-17]]

^<<v54-5-17,17>>^ Os anciãos, que presidem bem, sejam considerados dignos de dupla honra, especialmente os que trabalham arduamente no falar e no ensinar.

[[v54-5-18]]

^<<v54-5-18,18>>^ Pois as Escrituras dizem: “Não ponhas um açaime no touro enquanto este debulha o grão”, e também: “O trabalhador é digno do seu salário.”

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceites uma acusação contra um ancião, a não ser com base no testemunho de^&#42;1^ duas ou três pessoas.

[NOTE]
====
. Ou: “na evidência apresentada por”.
====

[[v54-5-20]]

^<<v54-5-20,20>>^ Repreende perante todos os observadores aqueles que praticam pecado, como um aviso para os outros.^&#42;1^

[NOTE]
====
. Lit.: “a fim de que os outros tenham temor”.
====

[[v54-5-21]]

^<<v54-5-21,21>>^ Ordeno-te solenemente, perante Deus, Cristo Jesus e os anjos escolhidos, que sigas estas instruções sem preconceito nem parcialidade.

[[v54-5-22]]

^<<v54-5-22,22>>^ Nunca imponhas as mãos sobre nenhum homem precipitadamente,^&#42;1^ nem participes dos pecados de outros; mantém-te casto.

[NOTE]
====
. Isto é, não tenhas pressa em designar um homem para um cargo.
====

[[v54-5-23]]

^<<v54-5-23,23>>^ Não bebas mais água,^&#42;1^ mas bebe um pouco de vinho por causa do teu estômago e pelo facto de adoeceres frequentemente.

[NOTE]
====
. Ou: “Para de beber apenas água”.
====

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de alguns homens são conhecidos por todos e levam-nos diretamente a julgamento; mas os de outros homens tornam-se evidentes mais tarde.

[[v54-5-25]]

^<<v54-5-25,25>>^ Do mesmo modo, também as boas obras são conhecidas por todos e, mesmo quando não o são, não podem continuar escondidas.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]