include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v54-2-1]]

^<<v54-2-1,1>>^ Portanto, em primeiro lugar, recomendo fortemente que se façam súplicas, orações, intercessões e agradecimentos com respeito a todo o tipo de pessoas,

[[v54-2-2]]

^<<v54-2-2,2>>^ com respeito a reis e a todos os que estão em altos cargos,^&#42;1^ a fim de que continuemos a levar uma vida calma e sossegada, com plena devoção a Deus e seriedade.

[NOTE]
====
. Ou: “em posições de autoridade”.
====

[[v54-2-3]]

^<<v54-2-3,3>>^ Isto é bom e agradável à vista do nosso Salvador, Deus,

[[v54-2-4]]

^<<v54-2-4,4>>^ que deseja que todo o tipo de pessoas sejam salvas e venham a ter um conhecimento exato da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Pois há um só Deus e um só mediador entre Deus e os homens: um homem, Cristo Jesus,

[[v54-2-6]]

^<<v54-2-6,6>>^ que se entregou como resgate correspondente por todos.^&#42;1^ Dar-se-á testemunho disto no tempo devido.

[NOTE]
====
. Ou: “por todo o tipo de pessoas”.
====

[[v54-2-7]]

^<<v54-2-7,7>>^ Foi para dar este testemunho que fui designado pregador e apóstolo — estou a dizer a verdade, não estou a mentir —, instrutor de nações quanto à fé e à verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Portanto, desejo que, em todo o lado, os homens persistam em orar, erguendo mãos leais, sem ira e sem debates.

[[v54-2-9]]

^<<v54-2-9,9>>^ Da mesma forma, as mulheres devem usar roupa decente,^&#42;1^ adornando-se com modéstia e bom critério,^&#42;2^ não com estilos de tranças, nem com ouro ou pérolas, nem com roupa muito cara,

[NOTE]
====
. Ou: “digna”.
. Ou: “bom juízo; sensatez”.
====

[[v54-2-10]]

^<<v54-2-10,10>>^ mas do modo próprio das mulheres que professam devoção a Deus, isto é, com boas obras.

[[v54-2-11]]

^<<v54-2-11,11>>^ Que a mulher aprenda em silêncio,^&#42;1^ com plena submissão.

[NOTE]
====
. Ou: “aprenda com espírito quieto, calmo”.
====

[[v54-2-12]]

^<<v54-2-12,12>>^ Não permito que a mulher ensine ou que exerça autoridade sobre o homem, mas ela deve ficar em silêncio.^&#42;1^

[NOTE]
====
. Ou: “ficar calma; ficar quieta”.
====

[[v54-2-13]]

^<<v54-2-13,13>>^ Pois, primeiro, foi formado Adão e, depois, Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ Além disso, Adão não foi enganado, mas a mulher foi totalmente enganada e tornou-se transgressora.

[[v54-2-15]]

^<<v54-2-15,15>>^ No entanto, ela ficará a salvo, tornando-se mãe, desde que continue^&#42;1^ na fé, no amor e na santidade, tendo bom senso.^&#42;2^

[NOTE]
====
. Lit.: “elas continuem”.
. Ou: “bom juízo; sensatez”.
====

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]