include::./index.adoc[]

[[v54-1-0]]
=== 1 Timóteo, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v54-1-1]]

^<<v54-1-1,1>>^ Paulo, apóstolo de Cristo Jesus por ordem de Deus, nosso Salvador, e de Cristo Jesus, a nossa esperança,

[[v54-1-2]]

^<<v54-1-2,2>>^ a Timóteo,^&#42;1^ filho genuíno na fé:
Que tenhas bondade imerecida, misericórdia e paz da parte de Deus, o Pai, e de Cristo Jesus, nosso Senhor.

[NOTE]
====
. Que significa “aquele que honra a Deus”.
====

[[v54-1-3]]

^<<v54-1-3,3>>^ Assim como te incentivei a ficares em Éfeso quando eu estava prestes a ir à Macedónia, assim o faço agora, para que ordenes a certas pessoas que não ensinem outras doutrinas,

[[v54-1-4]]

^<<v54-1-4,4>>^ nem prestem atenção a histórias falsas e a genealogias. Essas coisas não levam a lado nenhum, mas apenas provocam especulações, em vez de fornecer algo da parte de Deus no que se refere à fé.

[[v54-1-5]]

^<<v54-1-5,5>>^ Realmente, o objetivo desta instrução^&#42;1^ é o amor que vem de um coração puro, de uma boa consciência e de uma fé sem hipocrisia.

[NOTE]
====
. Ou: “deste mandamento; desta ordem”.
====

[[v54-1-6]]

^<<v54-1-6,6>>^ Alguns desviaram-se destas coisas e foram desencaminhados para discussões inúteis.

[[v54-1-7]]

^<<v54-1-7,7>>^ Querem ser instrutores da lei, mas não entendem nem as coisas que dizem, nem as coisas em que insistem tão fortemente.

[[v54-1-8]]

^<<v54-1-8,8>>^ Ora, sabemos que a Lei é boa, se for corretamente^&#42;1^ aplicada,

[NOTE]
====
. Lit.: “licitamente”.
====

[[v54-1-9]]

^<<v54-1-9,9>>^ reconhecendo-se que as leis são feitas não para o justo, mas para os transgressores e rebeldes, ímpios e pecadores, desleais^&#42;1^ e profanadores, para os que assassinam o pai ou a mãe, para os homicidas,

[NOTE]
====
. Ou: “os que não têm amor leal”.
====

[[v54-1-10]]

^<<v54-1-10,10>>^ para os que praticam imoralidade sexual,^&#42;1^ homens que praticam o homossexualismo,^&#42;2^ raptores, mentirosos, para os que juram falsamente,^&#42;3^ e para tudo o que é contrário ao ensinamento sadio,^&#42;4^

[NOTE]
====
. Veja o Glossário.
. Ou: “homens que têm relações sexuais com homens”. Lit.: “homens que se deitam com homens”.
. Ou: “os perjuros”.
. Ou: “salutar; benéfico”.
====

[[v54-1-11]]

^<<v54-1-11,11>>^ o qual está de acordo com as gloriosas boas novas do Deus feliz, que me foram confiadas.

[[v54-1-12]]

^<<v54-1-12,12>>^ Estou grato a Cristo Jesus, nosso Senhor, que me deu poder, porque me considerou fiel, designando-me para um ministério,

[[v54-1-13]]

^<<v54-1-13,13>>^ embora eu antes fosse blasfemador, perseguidor e insolente. Contudo, foi-me concedida misericórdia porque eu agia em ignorância e não tinha fé.

[[v54-1-14]]

^<<v54-1-14,14>>^ Porém, a bondade imerecida do nosso Senhor foi extremamente abundante com a fé e o amor que está em Cristo Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Esta declaração é digna de confiança e merece total aceitação: Cristo Jesus veio ao mundo para salvar pecadores. Destes, eu sou o principal.

[[v54-1-16]]

^<<v54-1-16,16>>^ No entanto, foi-me concedida misericórdia para que, por meio de mim como o principal caso, Cristo Jesus demonstrasse toda a sua paciência, fazendo de mim um exemplo para os que depositarem fé nele para obter vida eterna.

[[v54-1-17]]

^<<v54-1-17,17>>^ Ao Rei da eternidade, imortal,^&#42;1^ invisível, o único Deus, seja dada a honra e a glória para todo o sempre. Amém.

[NOTE]
====
. Lit.: “incorruptível”.
====

[[v54-1-18]]

^<<v54-1-18,18>>^ Confio-te esta instrução,^&#42;1^ Timóteo, meu filho, de harmonia com as profecias que foram feitas a teu respeito, a fim de que, em conformidade com elas, continues a travar o bom combate,

[NOTE]
====
. Ou: “este mandamento; esta ordem”.
====

[[v54-1-19]]

^<<v54-1-19,19>>^ mantendo a fé e uma boa consciência, a qual alguns rejeitaram, o que levou ao naufrágio da sua fé.

[[v54-1-20]]

^<<v54-1-20,20>>^ Himeneu e Alexandre estão entre esses, e eu entreguei-os a Satanás, para que sejam ensinados pela disciplina a não blasfemar.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[Próximo Capítulo &#62;]