include::./index.adoc[]

[[v54-4-0]]
=== 1 Timóteo, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v54-4-1]]

^<<v54-4-1,1>>^ No entanto, a palavra inspirada^&#42;1^ diz claramente que, em tempos posteriores, alguns se desviarão da fé, prestando atenção a enganosas declarações inspiradas^&#42;2^ e a ensinamentos de demónios,

[NOTE]
====
. Lit.: “o espírito”.
. Lit.: “espíritos enganosos”.
====

[[v54-4-2]]

^<<v54-4-2,2>>^ levados pela hipocrisia de homens que dizem mentiras e que têm a consciência marcada como que com ferro em brasa.

[[v54-4-3]]

^<<v54-4-3,3>>^ Eles proíbem o casamento e ordenam que as pessoas se abstenham de alimentos que Deus criou para serem consumidos com agradecimentos pelos que têm fé e conhecem a verdade de modo exato.

[[v54-4-4]]

^<<v54-4-4,4>>^ Pois tudo o que Deus criou é bom, e nada deve ser rejeitado se for recebido com agradecimento,

[[v54-4-5]]

^<<v54-4-5,5>>^ porque é santificado pela palavra de Deus e pela oração.

[[v54-4-6]]

^<<v54-4-6,6>>^ Se deres estes conselhos aos irmãos, serás um bom ministro de Cristo Jesus, nutrido com as palavras da fé e do bom ensinamento que tens seguido fielmente.

[[v54-4-7]]

^<<v54-4-7,7>>^ No entanto, rejeita as histórias falsas que violam o que é santo, como as que são contadas por mulheres velhas. Por outro lado, treina-te com a devoção a Deus por alvo.

[[v54-4-8]]

^<<v54-4-8,8>>^ Pois o exercício^&#42;1^ físico traz algum benefício, mas a devoção a Deus é benéfica para todas as coisas, visto que tem a promessa da vida presente e da vida que há de vir.

[NOTE]
====
. Ou: “treino”.
====

[[v54-4-9]]

^<<v54-4-9,9>>^ Esta declaração é digna de confiança e merece total aceitação.

[[v54-4-10]]

^<<v54-4-10,10>>^ É por isso que trabalhamos arduamente e nos esforçamos, porque baseamos a nossa esperança num Deus vivente, que é Salvador de todo o tipo de pessoas, especialmente de quem é fiel.

[[v54-4-11]]

^<<v54-4-11,11>>^ Persiste em dar estas ordens e em ensiná-las.

[[v54-4-12]]

^<<v54-4-12,12>>^ Nunca deixes que ninguém te menospreze por seres jovem. Em vez disso, torna-te um exemplo para os fiéis no falar, na conduta, no amor, na fé, na castidade.^&#42;1^

[NOTE]
====
. Ou: “pureza”.
====

[[v54-4-13]]

^<<v54-4-13,13>>^ Até eu chegar, continua a aplicar-te à leitura pública, à exortação,^&#42;1^ ao ensino.

[NOTE]
====
. Ou: “ao encorajamento”.
====

[[v54-4-14]]

^<<v54-4-14,14>>^ Não negligencies o dom que há em ti, que te foi dado por meio de uma profecia quando o corpo de anciãos impôs as mãos sobre ti.

[[v54-4-15]]

^<<v54-4-15,15>>^ Medita^&#42;1^ nestas coisas; concentra-te totalmente nelas, para que o teu progresso seja claramente visto por todos.

[NOTE]
====
. Ou: “Reflete”.
====

[[v54-4-16]]

^<<v54-4-16,16>>^ Presta constante atenção a ti mesmo e ao teu ensino. Persevera nestas coisas, pois, por fazeres isso, irás salvar-te tanto a ti mesmo como aos que te escutam.

'''

xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[Próximo Capítulo &#62;]