include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v54-6-1]]

^<<v54-6-1,1>>^ Que aqueles que estão debaixo do jugo da escravidão considerem os seus donos dignos de toda a honra, para que nunca se fale mal do nome de Deus e do seu ensinamento.

[[v54-6-2]]

^<<v54-6-2,2>>^ Além disso, que aqueles que têm donos crentes não lhes faltem ao respeito por serem irmãos. Em vez disso, devem servir com mais prontidão ainda, porque os que se beneficiam do seu bom serviço são crentes e amados.
Persiste em ensinar estas coisas e em dar estas exortações.

[[v54-6-3]]

^<<v54-6-3,3>>^ Se alguém ensina outra doutrina e não concorda com a instrução sadia,^&#42;1^ que vem do nosso Senhor Jesus Cristo, nem com o ensinamento que está de acordo com a devoção a Deus,

[NOTE]
====
. Ou: “salutar; benéfica”.
====

[[v54-6-4]]

^<<v54-6-4,4>>^ está cheio de orgulho e não compreende nada. Está obcecado^&#42;1^ por controvérsias e debates sobre palavras. Estas coisas produzem inveja, conflitos, calúnias,^&#42;2^ suspeitas maldosas,

[NOTE]
====
. Ou: “Tem fascínio doentio”.
. Ou: “palavras ofensivas”.
====

[[v54-6-5]]

^<<v54-6-5,5>>^ constantes discussões sobre questões insignificantes entre homens corrompidos na mente e desprovidos da verdade, que pensam que a devoção a Deus é um meio de ganho.

[[v54-6-6]]

^<<v54-6-6,6>>^ De facto, há grande ganho na devoção a Deus com contentamento.^&#42;1^

[NOTE]
====
. Lit.: “com autossuficiência”.
====

[[v54-6-7]]

^<<v54-6-7,7>>^ Pois não trouxemos nada ao mundo e nada podemos levar connosco.

[[v54-6-8]]

^<<v54-6-8,8>>^ Assim, se tivermos o que comer^&#42;1^ e o que vestir,^&#42;2^ estaremos contentes.

[NOTE]
====
. Ou: “tendo sustento”.
. Ou, possivelmente: “e abrigo”. Lit.: “e cobertura”.
====

[[v54-6-9]]

^<<v54-6-9,9>>^ Contudo, os que estão decididos a ficar ricos caem em tentação, em laço e em muitos desejos insensatos e prejudiciais, que afundam os homens na destruição e na ruína.

[[v54-6-10]]

^<<v54-6-10,10>>^ Porque o amor ao dinheiro é a raiz de todo o tipo de coisas prejudiciais e alguns, por se empenharem por este amor, desviaram-se da fé e causaram a si mesmos^&#42;1^ muitos sofrimentos.

[NOTE]
====
. Ou: “e trespassaram-se inteiramente com”.
====

[[v54-6-11]]

^<<v54-6-11,11>>^ No entanto, tu, homem de Deus, foge destas coisas. Porém, empenha-te pela justiça,^&#42;1^ pela devoção a Deus, pela fé, pelo amor, pela perseverança e pela brandura.

[NOTE]
====
. Veja o Glossário.
====

[[v54-6-12]]

^<<v54-6-12,12>>^ Trava a boa luta da fé. Apega-te firmemente à vida eterna para a qual foste chamado e fizeste a bela declaração pública diante de muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Diante de Deus, que preserva vivas todas as coisas, e de Cristo Jesus, que, como testemunha, fez a bela declaração pública perante Pôncio Pilatos, ordeno-te

[[v54-6-14]]

^<<v54-6-14,14>>^ que obedeças ao mandamento de um modo imaculado e irrepreensível, até à manifestação do nosso Senhor Jesus Cristo,

[[v54-6-15]]

^<<v54-6-15,15>>^ a qual o feliz e único Poderoso Senhor^&#42;1^ fará no tempo determinado para isso. Ele é o Rei dos que reinam e Senhor dos que dominam,

[NOTE]
====
. Ou: “feliz e único Potentado”.
====

[[v54-6-16]]

^<<v54-6-16,16>>^ o único que tem imortalidade, que mora em luz inacessível, a quem nenhum homem viu nem pode ver. A ele seja dada a honra e o poder eterno. Amém.

[[v54-6-17]]

^<<v54-6-17,17>>^ Dá instruções^&#42;1^ aos que são ricos no mundo atual^&#42;2^ para que não sejam arrogantes^&#42;3^ e não baseiem a sua esperança nas riquezas incertas, mas em Deus, que nos proporciona ricamente todas as coisas que nos dão satisfação.

[NOTE]
====
. Ou: “Ordena”.
. Ou: “no atual sistema de coisas; na época atual”. Veja o Glossário.
. Ou: “soberbos”.
====

[[v54-6-18]]

^<<v54-6-18,18>>^ Diz-lhes que pratiquem o bem, que sejam ricos em boas obras, que sejam generosos,^&#42;1^ prontos para partilhar,

[NOTE]
====
. Ou: “liberais”.
====

[[v54-6-19]]

^<<v54-6-19,19>>^ armazenando um tesouro para si,^&#42;1^ um bom alicerce para o futuro. Ao fazerem isso, irão apegar-se firmemente à verdadeira vida.

[NOTE]
====
. Ou: “entesourando de forma segura para si”.
====

[[v54-6-20]]

^<<v54-6-20,20>>^ Timóteo, guarda o que te foi confiado, afastando-te das conversas vãs que violam o que é santo e das contradições do falsamente chamado “conhecimento”.

[[v54-6-21]]

^<<v54-6-21,21>>^ Alguns, por ostentarem esse conhecimento, desviaram-se da fé.
Que a bondade imerecida esteja convosco.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]