include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-9-1]]

^<<v44-9-1,1>>^ Saulo, porém, respirando ainda ameaça e morte contra os discípulos do Senhor, foi ao sumo sacerdote

[[v44-9-2]]

^<<v44-9-2,2>>^ e pediu-lhe cartas dirigidas às sinagogas em Damasco, a fim de que pudesse levar amarrados para Jerusalém todos os que encontrasse e que pertencessem ao Caminho, tanto homens como mulheres.

[[v44-9-3]]

^<<v44-9-3,3>>^ Durante a viagem, quando ele se aproximava de Damasco, de repente, brilhou à sua volta uma luz vinda do céu,

[[v44-9-4]]

^<<v44-9-4,4>>^ e ele caiu ao chão e ouviu uma voz dizer-lhe: “Saulo, Saulo, porque é que me persegues?”

[[v44-9-5]]

^<<v44-9-5,5>>^ Ele perguntou: “Quem é o senhor?” Ele respondeu: “Eu sou Jesus, a quem persegues.

[[v44-9-6]]

^<<v44-9-6,6>>^ Mas levanta-te, entra na cidade, e lá te dirão o que deves fazer.”

[[v44-9-7]]

^<<v44-9-7,7>>^ E os homens que viajavam com ele ficaram parados sem fala e realmente ouviram o som de uma voz, mas não viram ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saulo levantou-se então do chão, e, embora os seus olhos estivessem abertos, não conseguia ver nada. Portanto, levaram-no pela mão e conduziram-no até Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ E, durante três dias, ele não viu nada, não comeu nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ Em Damasco, havia um discípulo chamado Ananias, e o Senhor disse-lhe numa visão: “Ananias!” Ele respondeu: “Aqui estou, Senhor.”

[[v44-9-11]]

^<<v44-9-11,11>>^ O Senhor disse-lhe: “Prepara-te e vai à rua chamada Direita. Na casa de Judas, procura um homem chamado Saulo, de Tarso, pois ele está a orar neste preciso momento

[[v44-9-12]]

^<<v44-9-12,12>>^ e, numa visão, viu um homem chamado Ananias a entrar e a pôr as mãos sobre ele, para que recuperasse a vista.”

[[v44-9-13]]

^<<v44-9-13,13>>^ Contudo, Ananias respondeu: “Senhor, eu ouvi muitos falarem deste homem, de todo o mal que ele fez aos teus santos em Jerusalém.

[[v44-9-14]]

^<<v44-9-14,14>>^ E aqui ele tem autoridade dada pelos principais sacerdotes para prender^&#42;1^ todos os que invocam o teu nome.”

[NOTE]
====
. Lit.: “acorrentar; pôr em correntes”.
====

[[v44-9-15]]

^<<v44-9-15,15>>^ No entanto, o Senhor disse-lhe: “Vai, porque este homem é para mim um vaso escolhido para levar o meu nome às nações, bem como a reis e aos filhos de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ Pois eu vou mostrar-lhe claramente quantas coisas ele terá de sofrer pelo meu nome.”

[[v44-9-17]]

^<<v44-9-17,17>>^ Assim, Ananias foi, entrou na casa, pôs as mãos sobre ele e disse: “Saulo, irmão, o Senhor Jesus, que te apareceu na estrada por onde vinhas, enviou-me para que recuperes a vista e fiques cheio de espírito santo.”

[[v44-9-18]]

^<<v44-9-18,18>>^ Imediatamente, caíram-lhe dos olhos o que pareciam ser escamas, e ele recuperou a vista. Então, ele levantou-se e foi batizado,

[[v44-9-19]]

^<<v44-9-19,19>>^ comeu e recuperou forças.
Ele ficou alguns dias com os discípulos em Damasco

[[v44-9-20]]

^<<v44-9-20,20>>^ e imediatamente, nas sinagogas, começou a pregar sobre Jesus, que ele era o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Mas todos os que o ouviam ficavam pasmados, e diziam: “Não é este o homem que, em Jerusalém, perseguia ferozmente os que invocavam este nome? Não veio ele para cá com o objetivo de os prender e levar^&#42;1^ aos principais sacerdotes?”

[NOTE]
====
. Lit.: “de os levar acorrentados”.
====

[[v44-9-22]]

^<<v44-9-22,22>>^ No entanto, Saulo fortalecia-se cada vez mais e deixava perplexos os judeus que moravam em Damasco, ao provar de forma lógica que Jesus era o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Então, passados muitos dias, os judeus tramaram matá-lo.

[[v44-9-24]]

^<<v44-9-24,24>>^ Todavia, Saulo soube dessa conspiração contra ele. Eles também vigiavam atentamente os portões, dia e noite, a fim de matá-lo.

[[v44-9-25]]

^<<v44-9-25,25>>^ Por conseguinte, os seus discípulos levaram-no e, de noite, desceram-no num cesto por uma abertura na muralha.

[[v44-9-26]]

^<<v44-9-26,26>>^ Ao chegar a Jerusalém, ele tentou juntar-se aos discípulos, mas todos estavam com medo dele, porque não acreditavam que fosse discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Portanto, Barnabé veio em seu auxílio e levou-o aos apóstolos. Então, contou-lhes em pormenor como, na estrada, Saulo tinha visto o Senhor, como o Senhor tinha falado com ele, e como Saulo tinha falado corajosamente no nome de Jesus em Damasco.

[[v44-9-28]]

^<<v44-9-28,28>>^ Depois disso, Saulo permaneceu com eles, andando livremente^&#42;1^ em Jerusalém e falando corajosamente no nome do Senhor.

[NOTE]
====
. Lit.: “entrando e saindo”.
====

[[v44-9-29]]

^<<v44-9-29,29>>^ Ele falava e discutia com os judeus de língua grega, mas estes tentavam matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Quando os irmãos descobriram isso, levaram-no para baixo, até Cesareia, e enviaram-no a Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ Então, a congregação por toda a Judeia, Galileia e Samaria entrou num período de paz, e era edificada. E, como andava no temor de Jeová^&#42;1^ e no consolo do espírito santo, multiplicava-se.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-9-32]]

^<<v44-9-32,32>>^ Visto que Pedro estava a viajar por toda a região, desceu também para visitar os santos que moravam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Encontrou ali um homem chamado Eneias, que já por oito anos estava confinado à cama, pois era paralítico.

[[v44-9-34]]

^<<v44-9-34,34>>^ Pedro disse-lhe: “Eneias, Jesus Cristo cura-te. Levanta-te e faz a tua cama.” Ele levantou-se imediatamente.

[[v44-9-35]]

^<<v44-9-35,35>>^ Quando o viram, todos os que moravam em Lida e na planície de Sarom converteram-se ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Em Jope, havia uma discípula chamada Tabita, nome que traduzido é Dorcas.^&#42;1^ Eram muitas as boas obras que ela fazia e era grande a ajuda que dava aos pobres.^&#42;2^

[NOTE]
====
. Tanto o nome grego Dorcas como o nome aramaico Tabita significam “gazela”.
. Ou: “e eram muitas as suas dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-9-37]]

^<<v44-9-37,37>>^ Naqueles dias, porém, ela adoeceu e morreu. Então, lavaram-na e colocaram-na numa sala do andar de cima.

[[v44-9-38]]

^<<v44-9-38,38>>^ Como Lida ficava perto de Jope e era lá que Pedro se encontrava, ao saberem da sua presença na cidade, os discípulos enviaram-lhe dois homens com o seguinte pedido: “Por favor, vem sem demora.”

[[v44-9-39]]

^<<v44-9-39,39>>^ Em vista disso, Pedro preparou-se e foi com eles. Ao chegar, levaram-no à sala do andar de cima, e todas as viúvas o rodearam. Choravam e mostravam muitas capas^&#42;1^ e outras roupas que Dorcas tinha feito enquanto estava com elas.

[NOTE]
====
. Ou: “roupas exteriores”.
====

[[v44-9-40]]

^<<v44-9-40,40>>^ Pedro mandou então que todos saíssem e, ajoelhando-se, orou. Depois, virou-se para o corpo e disse: “Tabita, levanta-te!” Ela abriu os olhos e, ao ver Pedro, sentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ Pegando-lhe na mão, ele levantou-a, chamou os santos e as viúvas, e apresentou-a viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ Toda a cidade de Jope soube disto, e foram muitos os que se tornaram crentes no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ E ele ficou muitos dias em Jope, com um curtidor chamado Simão.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]