include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-19-1]]

^<<v44-19-1,1>>^ Enquanto Apolo estava em Corinto, Paulo passou pelas regiões do interior e desceu até Éfeso. Lá, encontrou alguns discípulos

[[v44-19-2]]

^<<v44-19-2,2>>^ e perguntou-lhes: “Receberam espírito santo quando se tornaram crentes?” Eles responderam: “Nunca ouvimos dizer que há um espírito santo.”

[[v44-19-3]]

^<<v44-19-3,3>>^ Ele perguntou: “Então, foram batizados em quê?” Eles responderam: “No batismo de João.”

[[v44-19-4]]

^<<v44-19-4,4>>^ Paulo disse: “O batismo de João era o batismo em símbolo de arrependimento; ele dizia às pessoas que cressem naquele que viria depois dele, isto é, em Jesus.”

[[v44-19-5]]

^<<v44-19-5,5>>^ Depois de ouvirem isto, foram batizados em nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ E, quando Paulo lhes impôs as mãos, o espírito santo veio sobre eles, e eles começaram a falar em línguas e a profetizar.

[[v44-19-7]]

^<<v44-19-7,7>>^ Ao todo, havia cerca de 12 homens.

[[v44-19-8]]

^<<v44-19-8,8>>^ Durante três meses, ele foi à sinagoga e falou com coragem, proferindo discursos e raciocinando de forma persuasiva a respeito do Reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ No entanto, visto que alguns se recusavam obstinadamente a crer^&#42;1^ e falavam mal do Caminho perante a multidão, ele deixou-os e separou os discípulos dentre eles; e diariamente proferia discursos no auditório da escola de Tirano.

[NOTE]
====
. Ou: “alguns continuavam a endurecer-se e a não crer”.
====

[[v44-19-10]]

^<<v44-19-10,10>>^ Isto aconteceu por dois anos, até que todos os que moravam na província da Ásia, tanto judeus como gregos, ouviram a palavra do Senhor.

[[v44-19-11]]

^<<v44-19-11,11>>^ Deus realizava extraordinárias obras poderosas pelas mãos de Paulo,

[[v44-19-12]]

^<<v44-19-12,12>>^ de modo que até mesmo panos e aventais que tinham tocado no seu corpo eram levados aos doentes, e as doenças desapareciam e os espíritos maus saíam.

[[v44-19-13]]

^<<v44-19-13,13>>^ Contudo, alguns judeus que viajavam de um lugar para o outro, expulsando demónios, também tentaram invocar o nome do Senhor Jesus sobre aqueles que tinham espíritos maus e diziam: “Ordeno-vos solenemente por Jesus, a respeito de quem Paulo prega, que saiam.”

[[v44-19-14]]

^<<v44-19-14,14>>^ Sete filhos de um dos principais sacerdotes judeus, chamado Ceva, faziam isso.

[[v44-19-15]]

^<<v44-19-15,15>>^ Porém, o espírito mau disse-lhes, em resposta: “Eu conheço Jesus e sei quem é Paulo. Mas quem são vocês?”

[[v44-19-16]]

^<<v44-19-16,16>>^ Assim, o homem que tinha o espírito mau atirou-se a eles, dominou um após outro e prevaleceu contra eles, de modo que fugiram daquela casa nus e feridos.

[[v44-19-17]]

^<<v44-19-17,17>>^ Isto chegou ao conhecimento de todos, tanto dos judeus como dos gregos que moravam em Éfeso; e todos eles ficaram com medo, e o nome do Senhor Jesus continuou a ser magnificado.

[[v44-19-18]]

^<<v44-19-18,18>>^ Muitos dos que se tinham tornado crentes vinham para confessar e declarar abertamente as suas práticas.

[[v44-19-19]]

^<<v44-19-19,19>>^ Na verdade, um bom número dos que tinham praticado artes mágicas juntaram os seus livros e queimaram-nos diante de todos. Ao calcularem o seu valor, viram que valiam 50 000 moedas de prata.

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim, de modo poderoso, a palavra de Jeová^&#42;1^ crescia e prevalecia.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-19-21]]

^<<v44-19-21,21>>^ Depois de tudo isto ter acontecido, Paulo decidiu^&#42;1^ que, após passar pela Macedónia e pela Acaia, viajaria para Jerusalém. Ele disse: “Depois de lá ir, tenho de ir também a Roma.”

[NOTE]
====
. Ou: “decidiu no espírito”.
====

[[v44-19-22]]

^<<v44-19-22,22>>^ Assim, enviou à Macedónia dois dos seus ajudantes, Timóteo e Erasto, mas ele ainda continuou na província da Ásia por algum tempo.

[[v44-19-23]]

^<<v44-19-23,23>>^ Naquela época, houve um grande tumulto por causa do Caminho.

[[v44-19-24]]

^<<v44-19-24,24>>^ Um homem chamado Demétrio, um prateiro que fabricava miniaturas de prata do santuário de Ártemis, dava muito lucro aos artífices.

[[v44-19-25]]

^<<v44-19-25,25>>^ Ele reuniu-os, juntamente com outros que faziam o mesmo tipo de trabalho, e disse: “Homens, vocês sabem muito bem que a nossa prosperidade vem deste negócio.

[[v44-19-26]]

^<<v44-19-26,26>>^ Agora, estão a ver e a ouvir que, não somente em Éfeso, mas em quase toda a província da Ásia, esse tal Paulo persuadiu uma multidão considerável e fez com que mudassem de opinião, dizendo que os deuses feitos por mãos humanas não são deuses verdadeiros.

[[v44-19-27]]

^<<v44-19-27,27>>^ Além disso, não há apenas o perigo de que o nosso negócio caia em descrédito, mas também de que o templo da grande deusa Ártemis passe a ser considerado sem valor, e de que aquela que é adorada em toda a província da Ásia e na terra habitada seja destituída do seu esplendor.”

[[v44-19-28]]

^<<v44-19-28,28>>^ Ao ouvirem isto, os homens ficaram furiosos e começaram a gritar: “Grande é a Ártemis dos efésios!”

[[v44-19-29]]

^<<v44-19-29,29>>^ Então, a confusão espalhou-se pela cidade e todos entraram a correr no teatro, arrastando consigo os macedónios Gaio e Aristarco, companheiros de viagem de Paulo.

[[v44-19-30]]

^<<v44-19-30,30>>^ Paulo queria entrar e apresentar-se ao povo, mas os discípulos não permitiram que ele o fizesse.

[[v44-19-31]]

^<<v44-19-31,31>>^ Até mesmo alguns dos organizadores de festividades e jogos,^&#42;1^ que eram amigáveis com ele, enviaram-lhe uma mensagem, implorando-lhe que não se arriscasse a ir ao teatro.

[NOTE]
====
. Ou: “alguns dos asiarcas”.
====

[[v44-19-32]]

^<<v44-19-32,32>>^ Entretanto, a assembleia estava em confusão: uns gritavam uma coisa, outros gritavam outra, e a maioria nem sabia por que motivo se tinham reunido.

[[v44-19-33]]

^<<v44-19-33,33>>^ Por conseguinte, fizeram Alexandre sair do meio da multidão; os judeus empurraram-no para a frente, e Alexandre fez sinal com a mão, pois queria fazer a sua defesa perante o povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Todavia, quando perceberam que ele era judeu, todos começaram a gritar, a uma só voz, por cerca de duas horas: “Grande é a Ártemis dos efésios!”

[[v44-19-35]]

^<<v44-19-35,35>>^ Por fim, depois de acalmar a multidão, o administrador da cidade^&#42;1^ disse: “Homens de Éfeso, quem da humanidade não sabe realmente que a cidade dos efésios é a guardiã do templo da grande Ártemis e da imagem que caiu do céu?

[NOTE]
====
. Ou: “o escrivão”.
====

[[v44-19-36]]

^<<v44-19-36,36>>^ Visto que estas coisas são indiscutíveis, devem permanecer calmos e não agir precipitadamente.

[[v44-19-37]]

^<<v44-19-37,37>>^ Vocês trouxeram aqui estes homens, que não são nem ladrões de templos nem blasfemadores da nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Assim, se Demétrio e os artífices que estão com ele têm uma queixa contra alguém, há dias nos quais os tribunais se reúnem e há procônsules;^&#42;1^ que apresentem as suas acusações uns contra os outros.

[NOTE]
====
. Procônsul era o governador romano de uma província. Veja o Glossário.
====

[[v44-19-39]]

^<<v44-19-39,39>>^ Mas, se querem algo além disso, a questão tem de ser decidida numa assembleia legal.

[[v44-19-40]]

^<<v44-19-40,40>>^ Porque nós realmente corremos o risco de sermos acusados de sedição^&#42;1^ pelo que aconteceu hoje, pois não há nenhum motivo que possamos apresentar para justificar este tumulto.”

[NOTE]
====
. Ou: “revolta; perturbação da ordem pública”.
====

[[v44-19-41]]

^<<v44-19-41,41>>^ E, depois de dizer isto, dissolveu a assembleia.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]