include::./index.adoc[]

[[v44-15-0]]
=== Atos, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-15-1]]

^<<v44-15-1,1>>^ Alguns homens desceram da Judeia e começaram a ensinar os irmãos: “A menos que sejam circuncidados segundo o costume de Moisés, vocês não podem ser salvos.”

[[v44-15-2]]

^<<v44-15-2,2>>^ Contudo, depois de muita discórdia e discussão de Paulo e Barnabé com eles, decidiu-se que Paulo, Barnabé e alguns outros subiriam a Jerusalém para tratar desta questão^&#42;1^ com os apóstolos e os anciãos.

[NOTE]
====
. Ou: “controvérsia”.
====

[[v44-15-3]]

^<<v44-15-3,3>>^ Assim, depois de a congregação os ter acompanhado durante uma parte do caminho, estes homens seguiram viagem através da Fenícia e de Samaria, contando em pormenor a conversão de pessoas das nações e trazendo grande alegria a todos os irmãos.

[[v44-15-4]]

^<<v44-15-4,4>>^ Ao chegarem a Jerusalém, foram bondosamente recebidos pela congregação, pelos apóstolos e pelos anciãos, e contaram as muitas coisas que Deus tinha feito por meio deles.

[[v44-15-5]]

^<<v44-15-5,5>>^ No entanto, alguns da seita dos fariseus, que se tinham tornado crentes, levantaram-se dos seus assentos e disseram: “É necessário circuncidá-los e ordenar-lhes que cumpram a Lei de Moisés.”

[[v44-15-6]]

^<<v44-15-6,6>>^ Então, os apóstolos e os anciãos reuniram-se para considerar esta questão.

[[v44-15-7]]

^<<v44-15-7,7>>^ Depois de uma longa e intensa discussão, Pedro levantou-se e disse-lhes: “Homens, irmãos, bem sabem que, desde os primeiros dias, Deus escolheu-me dentre vocês para que as pessoas das nações ouvissem da minha boca a palavra das boas novas e cressem.

[[v44-15-8]]

^<<v44-15-8,8>>^ E Deus, que conhece os corações, mostrou que os aprovava,^&#42;1^ dando-lhes o espírito santo assim como também o tinha dado a nós.

[NOTE]
====
. Ou: “deu testemunho”.
====

[[v44-15-9]]

^<<v44-15-9,9>>^ E ele não fez nenhuma distinção entre nós e eles, mas purificou os seus corações pela fé.

[[v44-15-10]]

^<<v44-15-10,10>>^ Portanto, porque é que vocês, agora, põem Deus à prova, colocando no pescoço dos discípulos um jugo que nem os nossos antepassados nem nós fomos capazes de levar?

[[v44-15-11]]

^<<v44-15-11,11>>^ Pelo contrário, temos fé em que somos salvos pela bondade imerecida do Senhor Jesus do mesmo modo que eles.”

[[v44-15-12]]

^<<v44-15-12,12>>^ Em vista disso, todo o grupo ficou calado e começou a ouvir Barnabé e Paulo a relatar os muitos sinais e milagres^&#42;1^ que Deus tinha feito por meio deles entre as nações.

[NOTE]
====
. Ou: “portentos”.
====

[[v44-15-13]]

^<<v44-15-13,13>>^ Depois de acabarem de falar, Tiago tomou a palavra: “Homens, irmãos, ouçam-me.

[[v44-15-14]]

^<<v44-15-14,14>>^ Simeão relatou detalhadamente como Deus, pela primeira vez, voltou a sua atenção para as nações, a fim de tirar delas um povo para o Seu nome.

[[v44-15-15]]

^<<v44-15-15,15>>^ E com isto concordam as palavras dos Profetas, conforme está escrito:

[[v44-15-16]]

^<<v44-15-16,16>>^ ‘Depois disto, voltarei e levantarei novamente a tenda^&#42;1^ de David, que está caída; eu reconstruirei as suas ruínas e irei restaurá-la,

[NOTE]
====
. Ou: “barraca; casa”.
====

[[v44-15-17]]

^<<v44-15-17,17>>^ a fim de que o restante dos homens procure diligentemente a Jeová,^&#42;1^ com pessoas de todas as nações, pessoas que são chamadas pelo meu nome, diz Jeová,^&#42;2^ aquele que faz estas coisas,

[NOTE]
====
. Veja o Ap. A5.
. Veja o Ap. A5.
====

[[v44-15-18]]

^<<v44-15-18,18>>^ conhecidas desde a antiguidade.’

[[v44-15-19]]

^<<v44-15-19,19>>^ Por isso, a minha decisão^&#42;1^ é não causar dificuldades a essas pessoas das nações, que se estão a converter a Deus,

[NOTE]
====
. Ou: “opinião”.
====

[[v44-15-20]]

^<<v44-15-20,20>>^ mas escrever-lhes para que se abstenham de coisas contaminadas por ídolos, de imoralidade sexual,^&#42;1^ do que foi estrangulado^&#42;2^ e de sangue.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
. Ou: “do que foi morto sem ser sangrado”.
====

[[v44-15-21]]

^<<v44-15-21,21>>^ Pois, desde os tempos antigos, Moisés tem os que o pregam em cada cidade, porque ele é lido em voz alta nas sinagogas todos os sábados.”

[[v44-15-22]]

^<<v44-15-22,22>>^ Então, os apóstolos e os anciãos, juntamente com toda a congregação, decidiram enviar a Antioquia homens escolhidos dentre eles, acompanhados por Paulo e Barnabé; enviaram Judas, que era chamado Barsabás, e Silas, homens que tomavam a liderança entre os irmãos.

[[v44-15-23]]

^<<v44-15-23,23>>^ Escreveram esta carta e mandaram-na por meio deles:
“Os apóstolos e os anciãos, vossos irmãos, mandam saudações aos irmãos que são das nações, que estão em Antioquia, na Síria e na Cilícia.

[[v44-15-24]]

^<<v44-15-24,24>>^ Ouvimos dizer que alguns saíram do nosso meio e que vos causaram problemas com o que disseram, e tentaram transtornar-vos;^&#42;1^ nós, porém, não lhes tínhamos dado quaisquer instruções.

[NOTE]
====
. Ou: “transtornar as vossas almas”.
====

[[v44-15-25]]

^<<v44-15-25,25>>^ Por isso, decidimos, de comum acordo, escolher homens e enviá-los a vocês com os nossos amados Barnabé e Paulo,

[[v44-15-26]]

^<<v44-15-26,26>>^ que entregaram a vida^&#42;1^ ao nome do nosso Senhor Jesus Cristo.

[NOTE]
====
. Ou: “alma”.
====

[[v44-15-27]]

^<<v44-15-27,27>>^ Portanto, enviamos Judas e Silas, para relatarem verbalmente estas mesmas coisas.

[[v44-15-28]]

^<<v44-15-28,28>>^ Pois pareceu bem ao espírito santo e a nós próprios não vos impor nenhum fardo além destas coisas necessárias:

[[v44-15-29]]

^<<v44-15-29,29>>^ que persistam em abster-se de coisas sacrificadas a ídolos, de sangue, do que foi estrangulado^&#42;1^ e de imoralidade sexual.^&#42;2^ Se vocês se guardarem cuidadosamente destas coisas, prosperarão. Saudações!”^&#42;3^

[NOTE]
====
. Ou: “do que foi morto sem ser sangrado”.
. Em grego, porneía. Veja o Glossário.
. Ou: “Adeus; Boa saúde para vocês”.
====

[[v44-15-30]]

^<<v44-15-30,30>>^ Assim, depois de serem dispensados, estes homens desceram para Antioquia, reuniram todo o grupo e entregaram-lhes a carta.

[[v44-15-31]]

^<<v44-15-31,31>>^ Estes, depois de lerem a carta, alegraram-se com o encorajamento.

[[v44-15-32]]

^<<v44-15-32,32>>^ Visto que também eram profetas, Judas e Silas encorajaram os irmãos com muitos discursos e fortaleceram-nos.

[[v44-15-33]]

^<<v44-15-33,33>>^ Depois de passarem lá algum tempo, os irmãos mandaram-nos de volta em paz para aqueles que os tinham enviado.

[[v44-15-34]]

^<<v44-15-34,34>>^ ^&#42;1^——

[NOTE]
====
. Veja o Ap. A3.
====

[[v44-15-35]]

^<<v44-15-35,35>>^ No entanto, Paulo e Barnabé ficaram em Antioquia a ensinar e a declarar, com muitos outros, as boas novas da palavra de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-15-36]]

^<<v44-15-36,36>>^ Depois de alguns dias, Paulo disse a Barnabé: “Agora,^&#42;1^ vamos voltar e visitar os irmãos em cada uma das cidades onde proclamámos a palavra de Jeová,^&#42;2^ para ver como estão.”

[NOTE]
====
. Ou, possivelmente: “Sem falta”.
. Veja o Ap. A5.
====

[[v44-15-37]]

^<<v44-15-37,37>>^ Barnabé estava decidido a levar João, que era chamado Marcos.

[[v44-15-38]]

^<<v44-15-38,38>>^ Paulo, no entanto, não concordava em levá-lo, visto que ele se tinha separado deles na Panfília, e não os tinha acompanhado no trabalho.

[[v44-15-39]]

^<<v44-15-39,39>>^ Por isso, tiveram uma forte discussão,^&#42;1^ de modo que se separaram um do outro. Então, Barnabé levou consigo Marcos e navegou para Chipre.

[NOTE]
====
. Ou: “um forte acesso de ira”.
====

[[v44-15-40]]

^<<v44-15-40,40>>^ Paulo escolheu Silas e partiu, depois de os irmãos o entregarem à bondade imerecida de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-15-41]]

^<<v44-15-41,41>>^ Ele passou pela Síria e pela Cilícia, fortalecendo as congregações.

'''

xref:044-atos/044-atos-014.adoc#v44-14-0[&#60; Capítulo Anterior] | <<v44-15-0,Topo>> | xref:044-atos/044-atos-016.adoc#v44-16-0[Próximo Capítulo &#62;]