include::./index.adoc[]

[[v44-25-0]]
=== Atos, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-25-1]]

^<<v44-25-1,1>>^ Então, três dias depois de chegar à província e assumir o governo, Festo subiu de Cesareia até Jerusalém.

[[v44-25-2]]

^<<v44-25-2,2>>^ E os principais sacerdotes e os homens mais importantes dos judeus apresentaram-lhe acusações contra Paulo. Começaram a pedir insistentemente a Festo

[[v44-25-3]]

^<<v44-25-3,3>>^ que lhes fizesse o favor^&#42;1^ de mandar trazer Paulo para Jerusalém. No entanto, eles estavam a armar uma emboscada para o matarem na estrada.

[NOTE]
====
. Lit.: “pedindo um favor contra ele”.
====

[[v44-25-4]]

^<<v44-25-4,4>>^ Contudo, Festo respondeu que Paulo deveria continuar detido em Cesareia e que ele próprio voltaria para lá em breve.

[[v44-25-5]]

^<<v44-25-5,5>>^ “Portanto”, disse ele, “desçam comigo alguns dos vossos líderes e acusem-no, se é que o homem fez alguma coisa errada”.

[[v44-25-6]]

^<<v44-25-6,6>>^ Assim, depois de passar não mais do que oito ou dez dias entre eles, ele desceu até Cesareia e, no dia seguinte, sentou-se no tribunal e mandou que trouxessem Paulo.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo entrou, os judeus que tinham descido de Jerusalém rodearam-no, fazendo muitas acusações graves contra ele, que não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Todavia, Paulo disse em sua defesa: “Não cometi nenhum pecado contra a Lei dos judeus, nem contra o templo, nem contra César.”

[[v44-25-9]]

^<<v44-25-9,9>>^ Festo, querendo ganhar o favor dos judeus, disse a Paulo, em resposta: “Desejas subir até Jerusalém e ser julgado lá, na minha presença, a respeito destas coisas?”

[[v44-25-10]]

^<<v44-25-10,10>>^ Porém, Paulo disse: “Estou perante o tribunal de César, onde devo ser julgado. Não fiz nada de errado contra os judeus, como Vossa Excelência está a perceber muito bem.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se eu realmente sou criminoso e fiz algo que mereça a morte, não me recuso a morrer; mas, se as acusações que estes homens fazem contra mim são infundadas, ninguém tem o direito de me entregar a eles como um favor. Apelo para César!”

[[v44-25-12]]

^<<v44-25-12,12>>^ Então, depois de falar com o grupo de conselheiros, Festo respondeu: “Apelaste para César, para César irás.”

[[v44-25-13]]

^<<v44-25-13,13>>^ Depois de alguns dias, o rei Agripa e Berenice chegaram a Cesareia para fazer uma visita de cortesia a Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Visto que iam lá passar vários dias, Festo apresentou o caso de Paulo ao rei, dizendo:
“Há um homem que Félix deixou como prisioneiro;

[[v44-25-15]]

^<<v44-25-15,15>>^ quando estive em Jerusalém, os principais sacerdotes e os anciãos dos judeus trouxeram-me informações sobre ele e pediram que ele fosse condenado.

[[v44-25-16]]

^<<v44-25-16,16>>^ Mas eu respondi-lhes que não é um procedimento romano entregar um acusado antes de ele se encontrar face a face com os seus acusadores e ter a oportunidade de se defender da acusação.

[[v44-25-17]]

^<<v44-25-17,17>>^ Assim, no dia seguinte, quando cá chegaram, sentei-me no tribunal, sem demora, e mandei que trouxessem o homem.

[[v44-25-18]]

^<<v44-25-18,18>>^ Quando os acusadores se levantaram para falar, não o acusaram de nenhuma das coisas más que eu tinha imaginado.

[[v44-25-19]]

^<<v44-25-19,19>>^ Eles simplesmente tinham divergências com ele sobre a sua própria religião^&#42;1^ e sobre um homem chamado Jesus, que morreu, mas que Paulo insistia que estava vivo.

[NOTE]
====
. Ou: “adoração da divindade”.
====

[[v44-25-20]]

^<<v44-25-20,20>>^ Sem saber como lidar com esta controvérsia, perguntei-lhe se gostaria de ir a Jerusalém para ser julgado a respeito destas questões.

[[v44-25-21]]

^<<v44-25-21,21>>^ Mas, quando Paulo apelou para continuar em detenção e aguardar a decisão do Augusto,^&#42;1^ ordenei que ele ficasse preso até que eu o enviasse a César.”

[NOTE]
====
. Título do imperador romano.
====

[[v44-25-22]]

^<<v44-25-22,22>>^ Então, Agripa disse a Festo: “Eu próprio gostaria de ouvir o homem.” “Amanhã, vai ouvi-lo”, disse ele.

[[v44-25-23]]

^<<v44-25-23,23>>^ Assim, no dia seguinte, Agripa e Berenice chegaram com grande pompa e entraram na sala de audiências, juntamente com comandantes militares e homens importantes da cidade. E, quando Festo deu a ordem, trouxeram Paulo.

[[v44-25-24]]

^<<v44-25-24,24>>^ Festo disse: “Rei Agripa e todos os aqui presentes, vejam este homem a respeito de quem toda a comunidade judaica me fez petições, tanto em Jerusalém como aqui, gritando que ele não deveria continuar a viver.

[[v44-25-25]]

^<<v44-25-25,25>>^ Mas percebi que ele não tinha feito nada que merecesse a morte. Assim, quando ele apelou para o Augusto, decidi enviá-lo.

[[v44-25-26]]

^<<v44-25-26,26>>^ Contudo, não tenho nada definido para escrever ao meu Senhor a respeito dele. Portanto, trouxe-o diante dos senhores, e especialmente de Vossa Majestade, rei Agripa, para que, depois do interrogatório, eu tenha algo para escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Pois não me parece razoável enviar um prisioneiro sem indicar também as acusações contra ele.”

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]