include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-16-1]]

^<<v44-16-1,1>>^ Então ele chegou a Derbe e a Listra. Havia lá um discípulo chamado Timóteo, filho de uma mulher judia crente, mas de pai grego,

[[v44-16-2]]

^<<v44-16-2,2>>^ e os irmãos em Listra e em Icónio falavam bem dele.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo quis que Timóteo o acompanhasse e circuncidou-o por causa dos judeus daqueles lugares, pois todos sabiam que o seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Ao viajarem pelas cidades, transmitiam aos irmãos as decisões tomadas pelos apóstolos e pelos anciãos em Jerusalém, para que obedecessem a esses decretos.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim, as congregações eram fortalecidas na fé e cresciam a cada dia.

[[v44-16-6]]

^<<v44-16-6,6>>^ Eles viajaram pela Frígia e pela região da Galácia, porque o espírito santo os tinha proibido de declarar a palavra na província da Ásia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Além disso, quando desceram à Mísia, tentaram entrar na Bitínia, mas o espírito de Jesus não lhes permitiu fazê-lo.

[[v44-16-8]]

^<<v44-16-8,8>>^ Portanto, passaram pela^&#42;1^ Mísia e desceram até Tróade.

[NOTE]
====
. Ou: “atravessaram a”.
====

[[v44-16-9]]

^<<v44-16-9,9>>^ Durante a noite, Paulo teve uma visão: um macedónio estava de pé e suplicava-lhe: “Vem à Macedónia e ajuda-nos.”

[[v44-16-10]]

^<<v44-16-10,10>>^ Logo depois de ele ter a visão, tentámos ir à Macedónia, concluindo que Deus nos tinha chamado para lhes declarar as boas novas.

[[v44-16-11]]

^<<v44-16-11,11>>^ Assim, embarcámos em Tróade e fomos diretamente para a Samotrácia, mas, no dia seguinte, fomos para Neápolis.

[[v44-16-12]]

^<<v44-16-12,12>>^ A partir de lá, fomos para Filipos, colónia romana e cidade principal da região da Macedónia. Ficámos nessa cidade por alguns dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No dia de sábado, saímos pelo portão da cidade e fomos para a beira de um rio, pois pensávamos que havia lá um lugar de oração. Sentámo-nos e começámos a falar com as mulheres que se tinham reunido ali.

[[v44-16-14]]

^<<v44-16-14,14>>^ Havia uma mulher que estava a ouvir: chamava-se Lídia, era vendedora de púrpura, da cidade de Tiatira, e adoradora de Deus. E Jeová^&#42;1^ abriu-lhe amplamente o coração para prestar atenção ao que Paulo estava a dizer.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-16-15]]

^<<v44-16-15,15>>^ Depois de ela e os da sua casa terem sido batizados, ela insistiu: “Se me consideram fiel a Jeová,^&#42;1^ venham e fiquem na minha casa.” E ela simplesmente fez-nos ir.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-16-16]]

^<<v44-16-16,16>>^ Um dia, quando íamos para o lugar de oração, veio ao nosso encontro uma serva que tinha um espírito, um demónio de adivinhação. Ela dava muito lucro aos seus senhores por adivinhar o futuro.^&#42;1^

[NOTE]
====
. Ou: “praticar a arte da predição”.
====

[[v44-16-17]]

^<<v44-16-17,17>>^ Esta rapariga seguia Paulo e a nós, gritando: “Estes homens são escravos do Deus Altíssimo e estão a proclamar-vos o caminho da salvação.”

[[v44-16-18]]

^<<v44-16-18,18>>^ Ela fez isso durante muitos dias. Por fim, Paulo ficou cansado daquilo, virou-se e disse ao espírito: “Ordeno-te em nome de Jesus Cristo que saias dela.” E o espírito saiu nesse mesmo instante.

[[v44-16-19]]

^<<v44-16-19,19>>^ Quando os senhores dela viram que a sua esperança de lucro tinha acabado, agarraram Paulo e Silas e arrastaram-nos até à praça principal,^&#42;1^ às autoridades.

[NOTE]
====
. Área aberta usada como centro de compras e vendas e como local de reuniões públicas.
====

[[v44-16-20]]

^<<v44-16-20,20>>^ Levaram-nos aos magistrados civis e disseram: “Estes homens estão a perturbar muito a nossa cidade. São judeus

[[v44-16-21]]

^<<v44-16-21,21>>^ e estão a divulgar costumes que não nos é permitido^&#42;1^ adotar ou praticar, visto que somos romanos.”

[NOTE]
====
. Ou: “lícito”.
====

[[v44-16-22]]

^<<v44-16-22,22>>^ E toda a multidão se levantou contra eles. Então, os magistrados civis arrancaram-lhes as roupas e mandaram que fossem espancados com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de lhes baterem muito, mandaram-nos para a prisão e ordenaram ao carcereiro que os guardasse com segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Recebendo essa ordem, ele meteu-os na prisão interior e prendeu-lhes os pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Contudo, por volta da meia-noite, Paulo e Silas estavam a orar e a louvar a Deus com cânticos, e os prisioneiros ouviam-nos.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, houve um terramoto tão grande que os alicerces da cadeia foram abalados. Nesse instante, abriram-se todas as portas e soltaram-se as correntes de todos.

[[v44-16-27]]

^<<v44-16-27,27>>^ Quando o carcereiro acordou e viu que as portas da prisão estavam abertas, puxou da sua espada e ia matar-se, pensando que os prisioneiros tinham escapado.

[[v44-16-28]]

^<<v44-16-28,28>>^ Porém, Paulo gritou: “Não faças nenhum mal a ti próprio, pois estamos todos aqui!”

[[v44-16-29]]

^<<v44-16-29,29>>^ Assim, ele pediu que lhe trouxessem uma luz, entrou a correr e, tremendo, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Ele levou-os para fora e perguntou: “Senhores, o que é que tenho de fazer para ser salvo?”

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: “Crê no Senhor Jesus e serás salvo, tu e os da tua casa.”

[[v44-16-32]]

^<<v44-16-32,32>>^ E falaram-lhe da palavra de Jeová,^&#42;1^ a ele e a todos os da sua casa.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-16-33]]

^<<v44-16-33,33>>^ Ele levou-os consigo àquela hora da noite e lavou-lhes os ferimentos. Então, ele e todos os da sua casa foram batizados sem demora.

[[v44-16-34]]

^<<v44-16-34,34>>^ Ele levou-os à sua casa e pôs a mesa para eles, e ele e todos os da sua casa se alegraram muito por terem crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando amanheceu, os magistrados civis enviaram os guardas^&#42;1^ para dizer ao carcereiro: “Solta esses homens.”

[NOTE]
====
. Ou: “lictores”.
====

[[v44-16-36]]

^<<v44-16-36,36>>^ O carcereiro transmitiu estas palavras a Paulo e disse: “Os magistrados civis mandaram soltar-vos aos dois. Saiam agora e vão em paz.”

[[v44-16-37]]

^<<v44-16-37,37>>^ No entanto, Paulo disse-lhes: “Eles açoitaram-nos publicamente sem termos sido julgados,^&#42;1^ embora sejamos romanos, e meteram-nos na prisão. Agora, mandam-nos embora secretamente? Não! Eles próprios que venham e nos levem para fora.”

[NOTE]
====
. Ou: “sem um processo formal”.
====

[[v44-16-38]]

^<<v44-16-38,38>>^ Os guardas comunicaram, então, estas palavras aos magistrados civis. Estes ficaram com medo quando ouviram que os homens eram romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ Assim, foram até lá e pediram-lhes desculpas, e, depois de levá-los para fora, pediram-lhes que partissem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Todavia, Paulo e Silas, ao saírem da prisão, foram à casa de Lídia. Quando viram os irmãos, encorajaram-nos. Depois disso, partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]