include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-11-1]]

^<<v44-11-1,1>>^ Ora, os apóstolos e os irmãos que estavam na Judeia ouviram dizer que havia pessoas das nações que também tinham aceitado a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ Assim, quando Pedro subiu a Jerusalém, os que apoiavam a circuncisão começaram a criticá-lo,^&#42;1^

[NOTE]
====
. Ou: “discutir com ele”.
====

[[v44-11-3]]

^<<v44-11-3,3>>^ dizendo: “Entraste na casa de homens incircuncisos e comeste com eles.”

[[v44-11-4]]

^<<v44-11-4,4>>^ Em vista disso, Pedro começou a explicar-lhes em pormenor o que tinha acontecido:

[[v44-11-5]]

^<<v44-11-5,5>>^ “Eu estava na cidade de Jope a orar e, num estado de transe, tive uma visão de algo semelhante a um grande lençol de linho a descer do céu, preso pelas suas quatro pontas, e ele veio até perto de mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ Olhei atentamente para dentro dele e vi quadrúpedes da terra, animais selvagens, répteis^&#42;1^ e aves do céu.

[NOTE]
====
. Ou: “animais rasteiros”.
====

[[v44-11-7]]

^<<v44-11-7,7>>^ Também ouvi uma voz dizer-me: ‘Levanta-te, Pedro, mata e come!’

[[v44-11-8]]

^<<v44-11-8,8>>^ Mas eu disse: ‘Nem pensar, Senhor, porque na minha boca nunca entrou nada aviltado ou impuro.’

[[v44-11-9]]

^<<v44-11-9,9>>^ A voz do céu disse então pela segunda vez: ‘Para de chamar impuras as coisas que Deus purificou.’

[[v44-11-10]]

^<<v44-11-10,10>>^ Isto ocorreu pela terceira vez, e tudo foi recolhido de volta para o céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ Além disso, naquele instante, três homens que tinham sido enviados de Cesareia à minha procura chegaram à casa onde estávamos.

[[v44-11-12]]

^<<v44-11-12,12>>^ Então, o espírito disse-me para ir com eles sem hesitar. Estes seis irmãos também foram comigo, e nós entrámos na casa do homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ “Ele contou-nos que tinha visto um anjo aparecer na sua casa e dizer: ‘Envia homens a Jope e manda chamar Simão, que é conhecido como Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ e ele há de dizer-te as coisas pelas quais tu e todos os da tua casa podem ser salvos.’

[[v44-11-15]]

^<<v44-11-15,15>>^ Quando comecei a falar, o espírito santo desceu sobre eles, da mesma forma como tinha descido sobre nós no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Em vista disso, lembrei-me das palavras do Senhor; ele dizia: ‘João batizou com água, mas vocês serão batizados com espírito santo.’

[[v44-11-17]]

^<<v44-11-17,17>>^ Portanto, se Deus lhes deu a mesma dádiva^&#42;1^ que nos deu a nós, que cremos no Senhor Jesus Cristo, quem era eu para poder impedir a Deus?”^&#42;2^

[NOTE]
====
. Ou: “dádiva gratuita”.
. Ou: “me poder opor a Deus”.
====

[[v44-11-18]]

^<<v44-11-18,18>>^ Quando ouviram estas coisas, não apresentaram mais objeções^&#42;1^ e glorificaram a Deus, dizendo: “Então, Deus também concedeu a pessoas das nações o arrependimento que leva à vida.”

[NOTE]
====
. Lit.: “eles ficaram em silêncio”.
====

[[v44-11-19]]

^<<v44-11-19,19>>^ Os que tinham sido espalhados pela perseguição que surgiu por causa de Estêvão foram até à Fenícia, Chipre e Antioquia, mas falavam da palavra apenas aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ No entanto, alguns homens entre eles que eram de Chipre e de Cirene foram a Antioquia e começaram a falar às pessoas de língua grega, declarando as boas novas do Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ E a mão de Jeová^&#42;1^ estava com eles, e muitos se tornaram crentes e converteram-se ao Senhor.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-11-22]]

^<<v44-11-22,22>>^ As notícias sobre eles chegaram aos ouvidos da congregação em Jerusalém, e enviaram então Barnabé a Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Quando ele chegou e viu a bondade imerecida de Deus, alegrou-se e começou a encorajar todos a continuarem no Senhor de coração firme,

[[v44-11-24]]

^<<v44-11-24,24>>^ pois era um homem bom, cheio de espírito santo e de fé. E uma multidão considerável passou a crer no Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ Assim, ele foi a Tarso para procurar cuidadosamente por Saulo.

[[v44-11-26]]

^<<v44-11-26,26>>^ Depois de o encontrar, levou-o a Antioquia. Assim, durante um ano inteiro, reuniram-se com a congregação e ensinaram uma multidão considerável. E foi primeiro em Antioquia que os discípulos, por orientação divina, foram chamados cristãos.

[[v44-11-27]]

^<<v44-11-27,27>>^ Naqueles dias, alguns profetas desceram de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ Um deles, chamado Ágabo, levantou-se e predisse, por meio do espírito, que uma grande fome sobreviria a toda a terra habitada. De facto, esta ocorreu no tempo de Cláudio.

[[v44-11-29]]

^<<v44-11-29,29>>^ Assim, os discípulos resolveram, cada um de acordo com as suas possibilidades, enviar ajuda^&#42;1^ aos irmãos que moravam na Judeia.

[NOTE]
====
. Ou: “uma subministração de socorros”.
====

[[v44-11-30]]

^<<v44-11-30,30>>^ E fizeram isso, enviando-a aos anciãos pelas mãos de Barnabé e de Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]