include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-5-1]]

^<<v44-5-1,1>>^ No entanto, um homem chamado Ananias, com a sua esposa, Safira, vendeu uma propriedade.

[[v44-5-2]]

^<<v44-5-2,2>>^ Porém, ele ficou secretamente com parte do valor, com o conhecimento da sua esposa. Então, pegou no restante e colocou-o aos pés dos apóstolos.

[[v44-5-3]]

^<<v44-5-3,3>>^ Contudo, Pedro disse: “Ananias, como é que Satanás te levou a mentir de forma descarada ao espírito santo e a ficar secretamente com parte do valor do campo?

[[v44-5-4]]

^<<v44-5-4,4>>^ O campo não era teu antes de o venderes? E, depois de ter sido vendido, o valor não ficou sob o teu controlo? Porque é que tramaste no coração fazer uma coisa destas? Mentiste não a homens, mas a Deus.”

[[v44-5-5]]

^<<v44-5-5,5>>^ Ao ouvir estas palavras, Ananias caiu e morreu. E todos os que souberam disso ficaram com muito medo.

[[v44-5-6]]

^<<v44-5-6,6>>^ Então, os mais jovens levantaram-se e enrolaram-no em panos. De seguida, levaram-no dali para fora e enterraram-no.

[[v44-5-7]]

^<<v44-5-7,7>>^ Cerca de três horas depois, a esposa dele entrou, sem saber o que tinha acontecido.

[[v44-5-8]]

^<<v44-5-8,8>>^ Pedro perguntou-lhe: “Diz-me: Foi por esta quantia que vocês os dois venderam o campo?” Ela respondeu: “Sim, foi por esse valor.”

[[v44-5-9]]

^<<v44-5-9,9>>^ Assim, Pedro disse-lhe: “Porque é que os dois concordaram em pôr à prova o espírito de Jeová?^&#42;1^ Os pés daqueles que enterraram o teu marido estão à porta; eles vão levar-te daqui para fora.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-5-10]]

^<<v44-5-10,10>>^ Ela caiu instantaneamente aos pés dele e morreu. Quando os jovens entraram, encontraram-na morta; a seguir, levaram-na para fora e enterraram-na ao lado do marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ Assim, toda a congregação e todos os que ouviram falar sobre isto ficaram com muito medo.

[[v44-5-12]]

^<<v44-5-12,12>>^ Além disso, pelas mãos dos apóstolos, continuavam a ocorrer muitos sinais e milagres^&#42;1^ entre o povo; e todos se reuniam no Pórtico^&#42;2^ de Salomão.

[NOTE]
====
. Ou: “portentos”.
. Ou: “na Colunata”.
====

[[v44-5-13]]

^<<v44-5-13,13>>^ É verdade que nenhum dos outros tinha coragem para se juntar a eles, mas o povo falava muito bem deles.

[[v44-5-14]]

^<<v44-5-14,14>>^ Além disso, era grande o número de homens e de mulheres que passavam a crer no Senhor e que se juntavam a eles.

[[v44-5-15]]

^<<v44-5-15,15>>^ Até mesmo traziam os doentes para fora, para as ruas principais, e deitavam-nos em pequenas camas e em esteiras, para que, quando Pedro passasse, pelo menos a sua sombra tocasse em alguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ Vinham também multidões das cidades vizinhas de Jerusalém, trazendo os doentes e os afligidos por espíritos impuros, e todos eles eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ No entanto, o sumo sacerdote e todos os que estavam com ele, que eram da seita dos saduceus, levantaram-se cheios de ciúme.

[[v44-5-18]]

^<<v44-5-18,18>>^ Então, agarraram^&#42;1^ os apóstolos e meteram-nos na cadeia pública.

[NOTE]
====
. Ou: “prenderam”.
====

[[v44-5-19]]

^<<v44-5-19,19>>^ Porém, durante a noite, o anjo de Jeová^&#42;1^ abriu as portas da prisão, levou-os para fora e disse:

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-5-20]]

^<<v44-5-20,20>>^ “Vão, apresentem-se no templo e continuem a transmitir ao povo toda a mensagem a respeito da vida.”

[[v44-5-21]]

^<<v44-5-21,21>>^ Depois de ouvirem estas palavras, entraram no templo ao amanhecer e começaram a ensinar.
Quando chegaram o sumo sacerdote e os que estavam com ele, convocaram o Sinédrio e toda a assembleia dos anciãos dos filhos de Israel, e mandaram trazer os apóstolos da cadeia.

[[v44-5-22]]

^<<v44-5-22,22>>^ No entanto, quando os guardas^&#42;1^ chegaram à prisão, não os encontraram. Assim, voltaram e relataram o seguinte:

[NOTE]
====
. Ou: “guardas do templo”.
====

[[v44-5-23]]

^<<v44-5-23,23>>^ “Encontrámos a cadeia trancada com toda a segurança, e os guardas estavam parados às portas, mas, quando a abrimos, não estava ninguém lá dentro.”

[[v44-5-24]]

^<<v44-5-24,24>>^ Ao ouvirem isso, o capitão do templo e os principais sacerdotes ficaram perplexos, questionando-se a respeito do que aconteceria a seguir.

[[v44-5-25]]

^<<v44-5-25,25>>^ Contudo, alguém chegou e disse-lhes: “Os homens que vocês meteram na prisão estão no templo, a ensinar o povo!”

[[v44-5-26]]

^<<v44-5-26,26>>^ Então, o capitão foi buscá-los com os seus guardas, mas sem violência, porque tinham medo de ser apedrejados pelo povo.

[[v44-5-27]]

^<<v44-5-27,27>>^ Assim, eles trouxeram-nos e colocaram-nos diante do Sinédrio. E o sumo sacerdote interrogou-os

[[v44-5-28]]

^<<v44-5-28,28>>^ e disse: “Ordenámos expressamente que não ensinassem com base nesse nome, mas, vejam! Vocês encheram Jerusalém com os vossos ensinamentos, e estão decididos a trazer o sangue desse homem sobre nós.”

[[v44-5-29]]

^<<v44-5-29,29>>^ Pedro e os outros apóstolos responderam: “Temos de obedecer a Deus como governante em vez de a homens.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus dos nossos antepassados levantou dentre os mortos Jesus, a quem vocês mataram, pendurando-o num madeiro.^&#42;1^

[NOTE]
====
. Ou: “numa árvore”.
====

[[v44-5-31]]

^<<v44-5-31,31>>^ Deus enalteceu-o à sua direita como Agente Principal e Salvador, para dar arrependimento e perdão de pecados a Israel.

[[v44-5-32]]

^<<v44-5-32,32>>^ Nós somos testemunhas destas coisas, e o espírito santo, que Deus deu aos que lhe obedecem como governante, também o é.”

[[v44-5-33]]

^<<v44-5-33,33>>^ Quando ouviram isto, ficaram furiosos^&#42;1^ e quiseram matá-los.

[NOTE]
====
. Ou: “sentiram-se feridos”.
====

[[v44-5-34]]

^<<v44-5-34,34>>^ No entanto, levantou-se no Sinédrio um fariseu chamado Gamaliel, um instrutor da Lei estimado por todo o povo, e mandou que levassem os homens para fora por um momento.

[[v44-5-35]]

^<<v44-5-35,35>>^ Então, disse-lhes: “Homens de Israel, tenham cuidado com o que vão fazer a estes homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Por exemplo, há algum tempo, apareceu Teudas, dizendo ser alguém, e alguns homens, cerca de 400, juntaram-se a ele. Mas ele foi morto, e todos os que o seguiam dispersaram-se, e os seus planos não deram em nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois dele, nos dias do recenseamento, apareceu Judas, o galileu, e arrastou seguidores atrás de si. Esse homem também morreu, e todos os que o seguiam dispersaram-se.

[[v44-5-38]]

^<<v44-5-38,38>>^ Por isso, perante as circunstâncias, digo-vos: Não se metam com estes homens; deixem-nos em paz. Porque, se este plano ou esta obra for de homens, será derrubada;

[[v44-5-39]]

^<<v44-5-39,39>>^ mas, se for de Deus, vocês não poderão derrubá-los. Senão, pode ser que estejam até mesmo a lutar contra o próprio Deus.”

[[v44-5-40]]

^<<v44-5-40,40>>^ Em vista disso, aceitaram o seu conselho. Mandaram chamar os apóstolos e, depois de os açoitarem,^&#42;1^ ordenaram-lhes que parassem de falar em nome de Jesus e soltaram-nos.

[NOTE]
====
. Ou: “espancarem”.
====

[[v44-5-41]]

^<<v44-5-41,41>>^ Assim, eles saíram do Sinédrio, alegres por terem sido considerados dignos de ser desonrados por causa do nome dele.

[[v44-5-42]]

^<<v44-5-42,42>>^ E todos os dias, no templo e de casa em casa, continuavam, sem parar, a ensinar e a declarar as boas novas a respeito do Cristo, Jesus.

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]