include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-3-1]]

^<<v44-3-1,1>>^ Pedro e João estavam a subir em direção ao templo para a hora da oração, a nona hora,^&#42;1^

[NOTE]
====
. Isto é, por volta das 3 h da tarde.
====

[[v44-3-2]]

^<<v44-3-2,2>>^ enquanto um homem coxo de nascença estava a ser carregado. Todos os dias, ele era colocado perto do portão do templo, que se chamava Portão Belo, para que pudesse pedir esmola^&#42;1^ aos que entravam no templo.

[NOTE]
====
. Ou: “dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-3-3]]

^<<v44-3-3,3>>^ Quando ele viu Pedro e João a entrarem no templo, começou a pedir-lhes uma esmola.

[[v44-3-4]]

^<<v44-3-4,4>>^ Contudo, Pedro e João olharam diretamente para ele, e Pedro disse: “Olha para nós.”

[[v44-3-5]]

^<<v44-3-5,5>>^ Então, ele fixou a sua atenção neles, à espera de receber alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ No entanto, Pedro disse: “Não possuo prata nem ouro, mas o que tenho é o que te dou. Em nome de Jesus Cristo, o Nazareno, anda!”

[[v44-3-7]]

^<<v44-3-7,7>>^ Assim, ele segurou-o pela mão direita e levantou-o. Instantaneamente, os seus pés e os seus tornozelos ficaram firmes,

[[v44-3-8]]

^<<v44-3-8,8>>^ e de um salto ele pôs-se de pé, começou a andar e entrou com eles no templo, a andar, a saltar e a louvar a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ E todos o viram a andar e a louvar a Deus.

[[v44-3-10]]

^<<v44-3-10,10>>^ E eles reconheceram-no como o homem que se sentava à espera de esmolas no Portão Belo do templo, e ficaram admirados e em êxtase com o que lhe tinha acontecido.

[[v44-3-11]]

^<<v44-3-11,11>>^ O homem ainda se agarrava a Pedro e a João quando toda a multidão, extremamente surpreendida, correu ao encontro deles no chamado Pórtico^&#42;1^ de Salomão.

[NOTE]
====
. Ou: “na chamada Colunata”.
====

[[v44-3-12]]

^<<v44-3-12,12>>^ Quando Pedro viu isto, disse à multidão: “Homens de Israel, porque é que estão tão admirados com isto e porque é que estão a olhar para nós como se o tivéssemos feito andar por meio do nosso próprio poder ou da nossa devoção a Deus?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, de Isaque e de Jacó, o Deus dos nossos antepassados, glorificou o seu Servo, Jesus, aquele que vocês entregaram e negaram diante de Pilatos, embora ele tivesse decidido soltá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Sim, vocês negaram aquele homem santo e justo. Pediram que vos fosse entregue um homem que era assassino,

[[v44-3-15]]

^<<v44-3-15,15>>^ e assim mataram o Agente Principal da vida. Mas Deus levantou-o dentre os mortos, e nós somos testemunhas disso.

[[v44-3-16]]

^<<v44-3-16,16>>^ E foi por meio do nome dele, e pela nossa fé no nome dele, que este homem que veem e conhecem ficou forte. A fé que vem por meio de Jesus tornou este homem completamente são diante de todos vocês.

[[v44-3-17]]

^<<v44-3-17,17>>^ E agora, irmãos, sei que agiram em ignorância, assim como os vossos líderes.

[[v44-3-18]]

^<<v44-3-18,18>>^ Porém, deste modo, Deus cumpriu o que anunciou antecipadamente pela boca de todos os profetas: o seu Cristo tinha de sofrer.

[[v44-3-19]]

^<<v44-3-19,19>>^ “Arrependam-se, portanto, e deem meia-volta, a fim de que os vossos pecados sejam apagados, para que venham tempos de refrigério da parte de Jeová^&#42;1^

[NOTE]
====
. Lit.: “da parte da face de Jeová”. Veja o Ap. A5.
====

[[v44-3-20]]

^<<v44-3-20,20>>^ e ele envie o Cristo que vos foi designado, Jesus.

[[v44-3-21]]

^<<v44-3-21,21>>^ O céu tem de retê-lo até ao tempo do restabelecimento de todas as coisas, das quais Deus falou pela boca dos seus santos profetas da antiguidade.

[[v44-3-22]]

^<<v44-3-22,22>>^ Realmente, Moisés disse: ‘Jeová,^&#42;1^ vosso Deus, escolherá para vocês, dentre os vossos irmãos, um profeta semelhante a mim. Escutem tudo o que ele vos disser.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-3-23]]

^<<v44-3-23,23>>^ Sim, todo aquele^&#42;1^ que não escutar esse Profeta será completamente destruído dentre o povo.’

[NOTE]
====
. Ou: “toda a alma”.
====

[[v44-3-24]]

^<<v44-3-24,24>>^ E todos os profetas que falaram, de Samuel em diante, também anunciaram claramente estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vocês são filhos dos profetas e do pacto que Deus fez com os vossos antepassados, quando disse a Abraão: ‘E todas as famílias da terra serão abençoadas por meio do teu descendente.’^&#42;1^

[NOTE]
====
. Lit.: “da tua semente”.
====

[[v44-3-26]]

^<<v44-3-26,26>>^ Depois de fazer aparecer o seu Servo, Deus enviou-o primeiro a vocês para vos abençoar, ao afastar cada um de vocês das suas más ações.”

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]