include::./index.adoc[]

[[v44-20-0]]
=== Atos, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-20-1]]

^<<v44-20-1,1>>^ Quando o alvoroço diminuiu, Paulo mandou chamar os discípulos e, depois de os encorajar e de se despedir deles, partiu em viagem para a Macedónia.

[[v44-20-2]]

^<<v44-20-2,2>>^ Ele percorreu aquelas regiões e disse aos discípulos muitas palavras de encorajamento. Depois, chegou à Grécia.

[[v44-20-3]]

^<<v44-20-3,3>>^ Passou lá três meses, mas, visto que os judeus fizeram uma conspiração contra ele quando estava prestes a navegar para a Síria, resolveu voltar pela Macedónia.

[[v44-20-4]]

^<<v44-20-4,4>>^ Estava acompanhado de Sópater, filho de Pirro, de Bereia; Aristarco e Segundo, dos tessalonicenses; Gaio, de Derbe; Timóteo e, da província da Ásia, Tíquico e Trófimo.

[[v44-20-5]]

^<<v44-20-5,5>>^ Estes homens seguiram viagem e esperaram por nós em Tróade.

[[v44-20-6]]

^<<v44-20-6,6>>^ Nós embarcámos em Filipos, depois dos dias dos Pães sem Fermento, e, cinco dias depois, encontrámo-los em Tróade, onde passámos sete dias.

[[v44-20-7]]

^<<v44-20-7,7>>^ No primeiro dia da semana, quando estávamos reunidos para uma refeição, Paulo começou a falar aos presentes, visto que ia partir no dia seguinte. Ele prolongou o discurso até à meia-noite,

[[v44-20-8]]

^<<v44-20-8,8>>^ de modo que havia várias lâmpadas na sala do andar de cima, onde estávamos reunidos.

[[v44-20-9]]

^<<v44-20-9,9>>^ Um jovem chamado Êutico, que estava sentado à janela, caiu num sono profundo enquanto Paulo falava e, vencido pelo sono, caiu do terceiro andar.^&#42;1^ Quando o levantaram, estava morto.

[NOTE]
====
. Considerando-se o rés-do-chão como o primeiro andar.
====

[[v44-20-10]]

^<<v44-20-10,10>>^ Contudo, Paulo desceu, deitou-se sobre ele, abraçou-o e disse: “Parem com o tumulto, pois ele está vivo.”^&#42;1^

[NOTE]
====
. Ou: “pois a sua alma está nele”.
====

[[v44-20-11]]

^<<v44-20-11,11>>^ Então, Paulo subiu, partiu o pão e comeu. Continuou a conversar por bastante tempo, até ao amanhecer, e depois foi-se embora.

[[v44-20-12]]

^<<v44-20-12,12>>^ De seguida, levaram o rapaz vivo, muito consolados.

[[v44-20-13]]

^<<v44-20-13,13>>^ Nós fomos à frente, até ao navio, e navegámos para Assos, onde iríamos receber Paulo a bordo. Ele tinha-nos instruído a fazer isso, pois pretendia ir para lá a pé.

[[v44-20-14]]

^<<v44-20-14,14>>^ Assim, quando nos alcançou em Assos, recebemo-lo a bordo e fomos a Mitilene.

[[v44-20-15]]

^<<v44-20-15,15>>^ No dia seguinte, navegámos a partir de lá e chegámos perto de Quios. No outro dia, aportámos brevemente em Samos e, no dia seguinte, chegámos a Mileto.

[[v44-20-16]]

^<<v44-20-16,16>>^ Paulo tinha decidido não parar em Éfeso, para não perder tempo na província da Ásia, pois ele tinha pressa de chegar a Jerusalém, se possível, no dia da Festividade de Pentecostes.

[[v44-20-17]]

^<<v44-20-17,17>>^ No entanto, a partir de Mileto, ele mandou chamar os anciãos da congregação de Éfeso.

[[v44-20-18]]

^<<v44-20-18,18>>^ Quando chegaram, ele disse-lhes: “Bem sabem como me comportei entre vocês desde o primeiro dia em que pisei a província da Ásia:

[[v44-20-19]]

^<<v44-20-19,19>>^ trabalhei como escravo para o Senhor, com toda a humildade^&#42;1^ e com lágrimas, sofrendo provações por causa das conspirações dos judeus.

[NOTE]
====
. Ou: “humildade mental”.
====

[[v44-20-20]]

^<<v44-20-20,20>>^ Ao mesmo tempo, não deixei de vos dizer coisa alguma que fosse proveitosa,^&#42;1^ nem de vos ensinar publicamente e de casa em casa.

[NOTE]
====
. Ou: “para o vosso bem”.
====

[[v44-20-21]]

^<<v44-20-21,21>>^ Porém, dei testemunho de forma cabal, tanto a judeus como a gregos, de que deviam arrepender-se e voltar-se para Deus, e ter fé no nosso Senhor Jesus.

[[v44-20-22]]

^<<v44-20-22,22>>^ E agora, compelido^&#42;1^ pelo espírito, viajo para Jerusalém, embora não saiba o que me acontecerá lá.

[NOTE]
====
. Lit.: “amarrado”.
====

[[v44-20-23]]

^<<v44-20-23,23>>^ Só sei que, de cidade em cidade, o espírito santo avisa-me repetidamente de que me aguardam prisões e tribulações.

[[v44-20-24]]

^<<v44-20-24,24>>^ Contudo, não considero que a minha vida^&#42;1^ seja preciosa^&#42;2^ para mim; o importante é que eu possa terminar a minha corrida e o ministério que recebi do Senhor Jesus: dar um testemunho cabal das boas novas a respeito da bondade imerecida de Deus.

[NOTE]
====
. Ou: “alma”.
. Ou: “de valor algum”.
====

[[v44-20-25]]

^<<v44-20-25,25>>^ “Agora, sei que nenhum de vocês, entre os quais preguei o Reino, verá novamente o meu rosto.

[[v44-20-26]]

^<<v44-20-26,26>>^ Portanto, vocês são testemunhas, no dia de hoje, de que estou limpo do sangue de todos os homens,

[[v44-20-27]]

^<<v44-20-27,27>>^ pois não deixei de vos declarar toda a vontade^&#42;1^ de Deus.

[NOTE]
====
. Ou: “todo o propósito; todo o conselho”.
====

[[v44-20-28]]

^<<v44-20-28,28>>^ Prestem atenção a vocês mesmos e a todo o rebanho, sobre o qual o espírito santo vos designou como superintendentes, para pastorearem a congregação de Deus, que ele comprou com o sangue do seu próprio Filho.

[[v44-20-29]]

^<<v44-20-29,29>>^ Sei que, depois de eu me ir embora, entrarão no vosso meio lobos ferozes,^&#42;1^ que não tratarão o rebanho com ternura,

[NOTE]
====
. Ou: “opressivos”.
====

[[v44-20-30]]

^<<v44-20-30,30>>^ e mesmo dentre vocês surgirão homens que dirão coisas deturpadas para arrastar os discípulos atrás de si.

[[v44-20-31]]

^<<v44-20-31,31>>^ “Portanto, mantenham-se despertos e lembrem-se de que durante três anos, noite e dia, não parei de vos exortar, a cada um de vocês, com lágrimas.

[[v44-20-32]]

^<<v44-20-32,32>>^ E agora, entrego-vos aos cuidados de Deus e da palavra a respeito da Sua bondade imerecida, palavra que vos pode edificar e dar a herança entre todos os santificados.

[[v44-20-33]]

^<<v44-20-33,33>>^ Não cobicei a prata, nem o ouro, nem a roupa de ninguém.

[[v44-20-34]]

^<<v44-20-34,34>>^ Vocês mesmos sabem que estas minhas mãos supriram as minhas necessidades e as dos meus companheiros.

[[v44-20-35]]

^<<v44-20-35,35>>^ Em tudo, mostrei-vos que, trabalhando assim, arduamente, devem ajudar os fracos e ter em mente as palavras do Senhor Jesus, que disse: ‘Há mais felicidade em dar do que em receber.’”

[[v44-20-36]]

^<<v44-20-36,36>>^ Depois de dizer estas coisas, ajoelhou-se com todos eles e orou.

[[v44-20-37]]

^<<v44-20-37,37>>^ Todos começaram a chorar muito; então, abraçaram Paulo^&#42;1^ e beijaram-no ternamente,

[NOTE]
====
. Lit.: “lançaram-se sobre o pescoço de Paulo”.
====

[[v44-20-38]]

^<<v44-20-38,38>>^ pois estavam tristes especialmente pelo que ele tinha dito, que eles não voltariam a ver o seu rosto. Depois, acompanharam-no até ao navio.

'''

xref:044-atos/044-atos-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-atos/044-atos-021.adoc#v44-21-0[Próximo Capítulo &#62;]