include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-27-1]]

^<<v44-27-1,1>>^ Como foi decidido que navegaríamos para Itália, Paulo e alguns outros prisioneiros foram entregues a um oficial do exército chamado Júlio, do regimento de Augusto.

[[v44-27-2]]

^<<v44-27-2,2>>^ Embarcámos num navio de Adramítio, que estava prestes a partir para portos ao longo da costa da província da Ásia, e começámos a viagem; Aristarco, um macedónio de Tessalónica, estava connosco.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte, fizemos escala em Sídon; e Júlio tratou Paulo com bondade,^&#42;1^ permitindo-lhe visitar os seus amigos e receber cuidados da parte deles.

[NOTE]
====
. Ou: “humanidade”.
====

[[v44-27-4]]

^<<v44-27-4,4>>^ Partindo, navegámos sob o abrigo de Chipre, porque os ventos eram contrários.

[[v44-27-5]]

^<<v44-27-5,5>>^ Então, atravessámos o mar aberto ao longo da Cilícia e da Panfília, e aportámos em Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Lá, o oficial do exército encontrou um navio de Alexandria que ia para Itália, e fez-nos embarcar.

[[v44-27-7]]

^<<v44-27-7,7>>^ Depois de navegarmos vagarosamente por muitos dias, chegámos com dificuldade a Cnido. Visto que o vento não nos permitia continuar naquela direção, navegámos sob o abrigo de Creta, perto de Salmone.

[[v44-27-8]]

^<<v44-27-8,8>>^ E, navegando junto à costa com dificuldade, chegámos a um lugar chamado Bons Portos, que ficava perto da cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Tinha passado bastante tempo e tornou-se perigoso navegar, porque até o dia do jejum^&#42;1^ já tinha passado. Então, Paulo advertiu-os:

[NOTE]
====
. Isto é, do jejum do Dia da Expiação, que ocorria no mês de tisri, o início da época de chuvas e de mares agitados.
====

[[v44-27-10]]

^<<v44-27-10,10>>^ “Homens, vejo que esta viagem vai resultar em danos e em grandes perdas, não só da carga e do navio, mas também das nossas vidas.”^&#42;1^

[NOTE]
====
. Ou: “almas”.
====

[[v44-27-11]]

^<<v44-27-11,11>>^ No entanto, o oficial do exército, em vez de ouvir o que Paulo dizia, ouviu o piloto e o dono do navio.

[[v44-27-12]]

^<<v44-27-12,12>>^ Visto que o porto não era adequado para se passar o inverno, a maioria foi da opinião de que partissem, para ver se de algum modo conseguiam chegar a Fénix, um porto de Creta que dá para o nordeste e para o sudeste; lá, poderiam passar o inverno.

[[v44-27-13]]

^<<v44-27-13,13>>^ Quando o vento sul soprou suavemente, acharam que o seu objetivo já tinha sido alcançado. De seguida, levantaram âncora e foram navegando ao longo de Creta, perto do litoral.

[[v44-27-14]]

^<<v44-27-14,14>>^ Porém, pouco tempo depois, veio do lado da ilha um vento violento, conhecido como euraquilão,^&#42;1^

[NOTE]
====
. Isto é, um vento nordeste.
====

[[v44-27-15]]

^<<v44-27-15,15>>^ que arrastou o navio com violência, de modo que não era possível manter a proa contra o vento. Assim, desistimos e deixámos que o vento nos levasse.

[[v44-27-16]]

^<<v44-27-16,16>>^ Passámos sob o abrigo de uma pequena ilha chamada Cauda; mesmo assim, mal conseguimos controlar o bote^&#42;1^ que trazíamos a reboque.

[NOTE]
====
. Bote auxiliar que podia servir como bote salva-vidas.
====

[[v44-27-17]]

^<<v44-27-17,17>>^ Depois de o içarem a bordo, começaram a reforçar o casco do navio, amarrando-o. Então, com medo de que o navio encalhasse em Sirte,^&#42;1^ arriaram o aparelho^&#42;2^ e, desse modo, o navio foi levado pelo vento.

[NOTE]
====
. Veja o Glossário.
. Aparentemente, refere-se aos cabos e às vergas usados para levantar e sustentar as velas.
====

[[v44-27-18]]

^<<v44-27-18,18>>^ Como estávamos a ser violentamente sacudidos pela tempestade, no dia seguinte, começaram a atirar a carga ao mar.

[[v44-27-19]]

^<<v44-27-19,19>>^ E, no terceiro dia, lançaram a armação do navio ao mar, com as suas próprias mãos.

[[v44-27-20]]

^<<v44-27-20,20>>^ Por muitos dias, o sol e as estrelas não apareceram, e abatia-se uma violenta^&#42;1^ tempestade sobre nós. Então, por fim, começou a desaparecer toda a esperança de sermos salvos.

[NOTE]
====
. Lit.: “não pequena”.
====

[[v44-27-21]]

^<<v44-27-21,21>>^ Depois de passarem muito tempo sem comer nada, Paulo levantou-se no meio deles e disse: “Homens, certamente deviam ter aceitado o meu conselho e não ter partido de Creta. Se o tivessem feito, não teriam sofrido estes danos e perdas.

[[v44-27-22]]

^<<v44-27-22,22>>^ Ainda assim, neste momento, incentivo-vos a terem coragem, pois nenhum^&#42;1^ de vocês morrerá, apenas se perderá o navio.

[NOTE]
====
. Ou: “nenhuma alma”.
====

[[v44-27-23]]

^<<v44-27-23,23>>^ Na noite passada, um anjo do Deus a quem pertenço e a quem presto serviço sagrado apareceu ao meu lado,

[[v44-27-24]]

^<<v44-27-24,24>>^ e disse: ‘Não tenhas medo, Paulo. Tens de comparecer perante César. Além disso, Deus concedeu-te a vida de todos os que navegam contigo.’

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, homens, tenham coragem, pois eu acredito em Deus, que acontecerá exatamente assim como me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ No entanto, devemos encalhar numa ilha.”

[[v44-27-27]]

^<<v44-27-27,27>>^ Era a décima quarta noite, e nós estávamos a ser atirados de um lado para o outro no mar de Ádria, quando, à meia-noite, os marinheiros começaram a suspeitar de que estávamos a chegar perto de terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ Sondaram a profundidade e descobriram que era de 20 braças.^&#42;1^ Assim, prosseguiram por uma curta distância, sondaram-na de novo e viram que era de 15 braças.^&#42;2^

[NOTE]
====
. Cerca de 36 m. Veja o Ap. B14.
. Cerca de 27 m. Veja o Ap. B14.
====

[[v44-27-29]]

^<<v44-27-29,29>>^ Como estavam com medo de que o navio encalhasse nos rochedos, lançaram quatro âncoras da popa, ansiosos pela chegada do amanhecer.

[[v44-27-30]]

^<<v44-27-30,30>>^ Todavia, quando os marinheiros tentaram escapar do navio e baixaram o bote ao mar, com o pretexto de lançar âncoras da proa,

[[v44-27-31]]

^<<v44-27-31,31>>^ Paulo disse ao oficial do exército e aos soldados: “A menos que estes homens permaneçam no navio, vocês não poderão ser salvos.”

[[v44-27-32]]

^<<v44-27-32,32>>^ Os soldados cortaram então os cabos do bote e deixaram-no cair.

[[v44-27-33]]

^<<v44-27-33,33>>^ Perto do amanhecer, Paulo incentivou todos a se alimentarem, dizendo: “Hoje é o décimo quarto dia em que estão ansiosamente à espera, e ainda não comeram nada.

[[v44-27-34]]

^<<v44-27-34,34>>^ Assim, dou-vos o conselho de que se alimentem; isto é para o vosso próprio bem, pois não se perderá nem sequer um único fio do vosso cabelo.”

[[v44-27-35]]

^<<v44-27-35,35>>^ Depois de dizer isto, ele tomou um pão, deu graças a Deus diante de todos eles, partiu-o e começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Assim, todos ganharam coragem e começaram, também eles, a alimentar-se.

[[v44-27-37]]

^<<v44-27-37,37>>^ Ao todo, éramos 276 pessoas^&#42;1^ no navio.

[NOTE]
====
. Ou: “almas”.
====

[[v44-27-38]]

^<<v44-27-38,38>>^ Depois de comerem o suficiente, aliviaram o navio, lançando o trigo ao mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando amanheceu, não reconheceram a terra, mas viram uma baía com uma praia e decidiram que, se fosse possível, fariam o navio encalhar ali.

[[v44-27-40]]

^<<v44-27-40,40>>^ Assim, cortaram os cabos das âncoras, deixaram-nas cair ao mar e, ao mesmo tempo, soltaram as amarras dos lemes.^&#42;1^ Depois de içarem ao vento a vela da frente, seguiram em direção à praia.

[NOTE]
====
. Ou: “remos que serviam de leme”.
====

[[v44-27-41]]

^<<v44-27-41,41>>^ Então, bateram num banco de areia que era banhado pelo mar de ambos os lados, e o navio encalhou; a proa prendeu-se e ficou imóvel, mas a popa começou a ser despedaçada pelas ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ Com isto, os soldados decidiram matar os prisioneiros para que ninguém fugisse a nado.

[[v44-27-43]]

^<<v44-27-43,43>>^ Contudo, o oficial do exército estava determinado a salvar Paulo e impediu-os de executar o plano. Ele ordenou que os que sabiam nadar saltassem primeiro ao mar para alcançarem a terra

[[v44-27-44]]

^<<v44-27-44,44>>^ e que os demais fossem atrás: alguns em tábuas e outros em destroços do navio. Assim, todos chegaram a terra sãos e salvos.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]