include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-10-1]]

^<<v44-10-1,1>>^ Havia em Cesareia um homem de nome Cornélio, oficial^&#42;1^ do chamado regimento italiano.^&#42;2^

[NOTE]
====
. Ou: “centurião”, comandante de cem soldados.
. Ou: “da chamada coorte italiana”, unidade do exército romano que consistia em 600 soldados.
====

[[v44-10-2]]

^<<v44-10-2,2>>^ Ele era um homem devoto, que temia a Deus com todos os da sua casa. Ajudava muito os pobres^&#42;1^ entre o povo e fazia continuamente súplicas a Deus.

[NOTE]
====
. Ou: “Fazia muitas dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-10-3]]

^<<v44-10-3,3>>^ Por volta da nona hora do dia,^&#42;1^ ele viu claramente numa visão um anjo de Deus a aproximar-se dele e a dizer: “Cornélio!”

[NOTE]
====
. Isto é, por volta das 3 h da tarde.
====

[[v44-10-4]]

^<<v44-10-4,4>>^ Apavorado, Cornélio olhou fixamente para ele e perguntou: “O que foi, Senhor?” Ele disse-lhe: “As tuas orações e a ajuda que dás aos pobres ascenderam como lembrança perante Deus.

[[v44-10-5]]

^<<v44-10-5,5>>^ Portanto, envia agora homens a Jope para trazerem um homem chamado Simão, conhecido como Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Esse homem está hospedado com Simão, um curtidor, que tem uma casa à beira-mar.”

[[v44-10-7]]

^<<v44-10-7,7>>^ Assim que o anjo que falou com ele se foi embora, ele chamou dois dos seus servos e um soldado devoto dentre os seus auxiliares,

[[v44-10-8]]

^<<v44-10-8,8>>^ contou-lhes tudo e enviou-os a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, enquanto viajavam e se aproximavam da cidade, Pedro subiu ao terraço para orar, por volta da sexta hora.^&#42;1^

[NOTE]
====
. Isto é, por volta do meio-dia.
====

[[v44-10-10]]

^<<v44-10-10,10>>^ No entanto, ele ficou com muita fome e quis comer. Enquanto preparavam a refeição, ele entrou em transe;

[[v44-10-11]]

^<<v44-10-11,11>>^ viu o céu aberto e algo semelhante a um grande lençol de linho, preso pelas quatro pontas, a descer para a terra.

[[v44-10-12]]

^<<v44-10-12,12>>^ E nele havia todo o tipo de quadrúpedes e de répteis^&#42;1^ da terra, e de aves do céu.

[NOTE]
====
. Ou: “animais rasteiros”.
====

[[v44-10-13]]

^<<v44-10-13,13>>^ Uma voz disse-lhe então: “Levanta-te, Pedro, mata e come!”

[[v44-10-14]]

^<<v44-10-14,14>>^ Contudo, Pedro respondeu: “Nem pensar, Senhor, porque nunca comi nada aviltado ou impuro.”

[[v44-10-15]]

^<<v44-10-15,15>>^ E a voz falou novamente com ele, pela segunda vez: “Para de chamar impuras às coisas que Deus purificou.”

[[v44-10-16]]

^<<v44-10-16,16>>^ Isto ocorreu pela terceira vez e, imediatamente, o lençol foi recolhido para o céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Pedro estava perplexo, perguntando-se o que poderia significar a visão que tivera. Enquanto isso, os homens enviados por Cornélio perguntaram onde era a casa de Simão e ficaram parados ao portão.

[[v44-10-18]]

^<<v44-10-18,18>>^ Eles chamaram alguém da casa e perguntaram se Simão, conhecido como Pedro, estava lá hospedado.

[[v44-10-19]]

^<<v44-10-19,19>>^ Pedro ainda estava a refletir sobre a visão quando o espírito disse: “Olha, há três homens à tua procura.

[[v44-10-20]]

^<<v44-10-20,20>>^ Levanta-te, desce e vai com eles, sem hesitar, porque fui eu que os enviei.”

[[v44-10-21]]

^<<v44-10-21,21>>^ Por conseguinte, Pedro desceu ao encontro dos homens e disse: “Aqui estou, é a mim que procuram. Porque é que estão aqui?”

[[v44-10-22]]

^<<v44-10-22,22>>^ Disseram-lhe: “Cornélio, oficial do exército, homem justo e temente a Deus, a respeito de quem toda a nação dos judeus fala bem, recebeu instruções divinas por meio de um anjo para chamar o senhor à casa dele, a fim de ouvir o que o senhor tem para dizer.”

[[v44-10-23]]

^<<v44-10-23,23>>^ Assim, Pedro convidou-os a entrar e deu-lhes hospedagem.
No dia seguinte, levantou-se e foi com eles, e alguns dos irmãos de Jope acompanharam-no.

[[v44-10-24]]

^<<v44-10-24,24>>^ Um dia depois, ele entrou em Cesareia. Cornélio, naturalmente, estava à espera deles, e tinha reunido os seus parentes e amigos íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro entrou, Cornélio foi ao seu encontro, prostrou-se aos seus pés e prestou-lhe homenagem.^&#42;1^

[NOTE]
====
. Ou: “curvou-se diante dele”.
====

[[v44-10-26]]

^<<v44-10-26,26>>^ Todavia, Pedro levantou-o, dizendo: “Levanta-te! Eu também sou apenas um homem.”

[[v44-10-27]]

^<<v44-10-27,27>>^ Enquanto conversava com ele, entrou e encontrou muitas pessoas reunidas.

[[v44-10-28]]

^<<v44-10-28,28>>^ Ele disse-lhes: “Sabem muito bem que é proibido que um judeu se relacione ou tenha contacto com um homem de outra raça. Contudo, Deus mostrou-me que eu não devo chamar aviltado ou impuro a nenhum homem.

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso, quando fui chamado, vim sem qualquer objeção. Agora, pergunto por que motivo me mandaram chamar.”

[[v44-10-30]]

^<<v44-10-30,30>>^ Cornélio respondeu: “Há quatro dias, eu estava a orar na minha casa a esta hora, a nona hora,^&#42;1^ quando me apareceu à frente um homem com roupa brilhante;

[NOTE]
====
. Isto é, por volta das 3 h da tarde.
====

[[v44-10-31]]

^<<v44-10-31,31>>^ ele disse: ‘Cornélio, a tua oração foi ouvida, e a ajuda que dás aos pobres foi lembrada diante de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Portanto, envia alguém a Jope para chamar Simão, conhecido como Pedro. Esse homem está hospedado na casa de Simão, um curtidor, à beira-mar.’

[[v44-10-33]]

^<<v44-10-33,33>>^ Mandei chamar-te imediatamente, e tu tiveste a bondade de vir até aqui. Agora estamos todos presentes perante Deus para ouvir todas as coisas que Jeová^&#42;1^ te mandou dizer.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-10-34]]

^<<v44-10-34,34>>^ Portanto, Pedro começou a falar e disse: “Agora entendo claramente que Deus não é parcial,

[[v44-10-35]]

^<<v44-10-35,35>>^ mas, em todas as nações, ele aceita aquele que o teme e faz o que é certo.

[[v44-10-36]]

^<<v44-10-36,36>>^ Ele enviou a sua palavra aos filhos de Israel, declarando-lhes as boas novas de paz por meio de Jesus Cristo — este é Senhor de todos.

[[v44-10-37]]

^<<v44-10-37,37>>^ Vocês sabem qual era o assunto de que se falava em toda a Judeia, a começar pela Galileia, depois do batismo que João pregou:

[[v44-10-38]]

^<<v44-10-38,38>>^ sobre Jesus, que era de Nazaré, como Deus o ungiu com espírito santo e poder; e ele andou por toda a região a fazer o bem e a curar todos os oprimidos pelo Diabo, porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ E nós somos testemunhas de todas as coisas que ele fez tanto na terra dos judeus como em Jerusalém. Mas eles mataram-no, pendurando-o num madeiro.^&#42;1^

[NOTE]
====
. Ou: “numa árvore”.
====

[[v44-10-40]]

^<<v44-10-40,40>>^ Deus levantou-o no terceiro dia e permitiu que ele aparecesse,^&#42;1^

[NOTE]
====
. Ou: “se tornasse visível”.
====

[[v44-10-41]]

^<<v44-10-41,41>>^ não a todo o povo, mas a testemunhas designadas antecipadamente por Deus, a nós, os que comemos e bebemos com ele depois de ter sido levantado dentre os mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ Ele ordenou, também, que pregássemos ao povo e déssemos um testemunho cabal de que é ele o designado por Deus para ser juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ É dele que todos os profetas dão testemunho, de que todo aquele que deposita fé nele recebe perdão de pecados por meio do seu nome.”

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro ainda dizia estas coisas, o espírito santo desceu sobre todos os que ouviam a palavra.

[[v44-10-45]]

^<<v44-10-45,45>>^ E os crentes^&#42;1^ circuncisos que tinham vindo com Pedro ficaram admirados, porque a dádiva^&#42;2^ do espírito santo também estava a ser derramada sobre pessoas das nações.

[NOTE]
====
. Ou: “fiéis”.
. Ou: “dádiva gratuita”.
====

[[v44-10-46]]

^<<v44-10-46,46>>^ Pois eles ouviram-nas a falar em línguas e a magnificar a Deus. Em vista disso, Pedro disse:

[[v44-10-47]]

^<<v44-10-47,47>>^ “Estas pessoas receberam o espírito santo assim como nós. Será que alguém lhes pode negar a água, impedindo que sejam batizadas?”

[[v44-10-48]]

^<<v44-10-48,48>>^ Então, mandou que fossem batizados em nome de Jesus Cristo. E eles pediram-lhe que ficasse ali durante alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]