include::./index.adoc[]

[[v44-23-0]]
=== Atos, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-23-1]]

^<<v44-23-1,1>>^ Olhando atentamente para o Sinédrio, Paulo disse: “Homens, irmãos, até hoje, comportei-me perante Deus com uma consciência perfeitamente limpa.”

[[v44-23-2]]

^<<v44-23-2,2>>^ Em vista disso, o sumo sacerdote Ananias mandou que os que estavam perto dele lhe batessem na boca.

[[v44-23-3]]

^<<v44-23-3,3>>^ Paulo disse-lhe então: “Deus há de te bater, parede caiada.^&#42;1^ Sentas-te para me julgar segundo a Lei e ao mesmo tempo violas a Lei, mandando que me batam?”

[NOTE]
====
. Ou: “a ti, hipócrita”.
====

[[v44-23-4]]

^<<v44-23-4,4>>^ Os que lá estavam disseram: “Estás a insultar o sumo sacerdote de Deus?”

[[v44-23-5]]

^<<v44-23-5,5>>^ E Paulo respondeu: “Irmãos, eu não sabia que ele era o sumo sacerdote. Pois está escrito: ‘Não fales mal de uma autoridade do teu povo.’”

[[v44-23-6]]

^<<v44-23-6,6>>^ Sabendo que uma parte deles era composta por saduceus, mas a outra parte por fariseus, Paulo disse bem alto no Sinédrio: “Homens, irmãos, eu sou fariseu, filho de fariseus. É por causa da esperança da ressurreição dos mortos que estou a ser julgado.”

[[v44-23-7]]

^<<v44-23-7,7>>^ Ao dizer isto, surgiu uma discussão entre os fariseus e os saduceus, e a assembleia ficou dividida.

[[v44-23-8]]

^<<v44-23-8,8>>^ Pois os saduceus dizem que não há ressurreição, nem anjo, nem espírito, mas os fariseus aceitam^&#42;1^ todas essas coisas.

[NOTE]
====
. Ou: “declaram publicamente”.
====

[[v44-23-9]]

^<<v44-23-9,9>>^ Assim, começou uma grande gritaria, e alguns dos escribas do partido dos fariseus levantaram-se e puseram-se a protestar energicamente: “Não vemos nada de errado neste homem; e, se um espírito ou um anjo falou com ele . . .”

[[v44-23-10]]

^<<v44-23-10,10>>^ Então, a discussão intensificou-se, e o comandante militar, com medo de que Paulo fosse despedaçado por eles, mandou que os soldados descessem e o arrancassem do meio deles, e o levassem ao quartel.

[[v44-23-11]]

^<<v44-23-11,11>>^ Todavia, naquela noite, o Senhor apareceu ao seu lado e disse: “Tem coragem! Pois, assim como deste um testemunho cabal sobre mim em Jerusalém, terás de dar testemunho também em Roma.”

[[v44-23-12]]

^<<v44-23-12,12>>^ Quando amanheceu, os judeus formaram uma conspiração e comprometeram-se, sob maldição, a não comer nem beber nada até matarem Paulo.

[[v44-23-13]]

^<<v44-23-13,13>>^ Foram mais de 40 os homens que fizeram tal conspiração sob juramento.

[[v44-23-14]]

^<<v44-23-14,14>>^ Estes homens dirigiram-se aos principais sacerdotes e aos anciãos, e disseram: “Comprometemo-nos solenemente, sob maldição,^&#42;1^ a não comer nada até matarmos Paulo.

[NOTE]
====
. Ou: “juramento”.
====

[[v44-23-15]]

^<<v44-23-15,15>>^ Portanto, vocês, juntamente com o Sinédrio, devem dizer ao comandante militar que o traga para baixo, para comparecer na vossa presença, como se quisessem examinar mais detalhadamente o seu caso. Mas, antes de ele se aproximar, estaremos prontos para matá-lo.”

[[v44-23-16]]

^<<v44-23-16,16>>^ No entanto, o filho da irmã de Paulo soube da emboscada que estavam a planear; ele entrou no quartel e contou tudo a Paulo.

[[v44-23-17]]

^<<v44-23-17,17>>^ Assim, Paulo chamou um dos oficiais do exército e disse: “Leva este jovem ao comandante militar, pois ele tem algo a comunicar-lhe.”

[[v44-23-18]]

^<<v44-23-18,18>>^ Ele levou-o ao comandante militar e disse: “O prisioneiro Paulo chamou-me e pediu-me que lhe trouxesse este jovem, porque ele tem algo para lhe dizer.”

[[v44-23-19]]

^<<v44-23-19,19>>^ O comandante militar agarrou o jovem pela mão, levou-o à parte e perguntou-lhe: “O que é que tens para me contar?”

[[v44-23-20]]

^<<v44-23-20,20>>^ Ele respondeu: “Os judeus combinaram pedir-lhe que faça Paulo descer ao Sinédrio amanhã, como se quisessem saber mais pormenores sobre o caso dele.

[[v44-23-21]]

^<<v44-23-21,21>>^ Mas não os deixe convencê-lo, pois são mais de 40 os que planeiam armar uma emboscada contra Paulo, e eles comprometeram-se, sob maldição,^&#42;1^ a não comer nem beber nada até o matarem. Já estão prontos, à espera de que o senhor aceite o pedido deles.”

[NOTE]
====
. Ou: “juramento”.
====

[[v44-23-22]]

^<<v44-23-22,22>>^ Assim, o comandante militar deixou o jovem ir-se embora, mas antes ordenou-lhe: “Não digas a ninguém que me contaste isto.”

[[v44-23-23]]

^<<v44-23-23,23>>^ Por conseguinte, ele convocou dois oficiais do exército e disse: “Preparem 200 soldados, 70 cavaleiros e 200 lanceiros para irem até Cesareia à terceira hora da noite.^&#42;1^

[NOTE]
====
. Isto é, por volta das 9 h da noite.
====

[[v44-23-24]]

^<<v44-23-24,24>>^ Também, providenciem cavalos para Paulo montar, a fim de levá-lo em segurança a Félix, o governador.”

[[v44-23-25]]

^<<v44-23-25,25>>^ E ele escreveu uma carta que dizia:

[[v44-23-26]]

^<<v44-23-26,26>>^ “De Cláudio Lísias a Sua Excelência, o governador Félix. Saudações!

[[v44-23-27]]

^<<v44-23-27,27>>^ Este homem foi agarrado pelos judeus e estava prestes a ser morto por eles, mas eu vim rapidamente com os meus soldados e resgatei-o, porque soube que ele era romano.

[[v44-23-28]]

^<<v44-23-28,28>>^ Então, querendo descobrir a razão pela qual o acusavam, levei-o ao Sinédrio deles.

[[v44-23-29]]

^<<v44-23-29,29>>^ Verifiquei que ele estava a ser acusado por questões da Lei deles, mas não foi acusado de nem sequer uma única coisa que merecesse morte ou prisão.

[[v44-23-30]]

^<<v44-23-30,30>>^ No entanto, visto que me foi revelada uma conspiração contra o homem, envio-o imediatamente a Vossa Excelência e ordeno que os acusadores digam na sua presença o que têm contra ele.”

[[v44-23-31]]

^<<v44-23-31,31>>^ Assim, segundo as ordens que receberam, os soldados agarraram Paulo e levaram-no de noite até Antipátride.

[[v44-23-32]]

^<<v44-23-32,32>>^ No dia seguinte, deixaram os cavaleiros prosseguir com ele e voltaram para o quartel.

[[v44-23-33]]

^<<v44-23-33,33>>^ Os cavaleiros entraram em Cesareia, entregaram a carta ao governador e também lhe apresentaram Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ Então, o governador leu a carta e perguntou de que província ele era; foi informado de que era da Cilícia.

[[v44-23-35]]

^<<v44-23-35,35>>^ “Eu ouvirei todo o teu caso”, disse ele, “quando chegarem os teus acusadores”. E mandou que ele ficasse detido no palácio^&#42;1^ de Herodes.

[NOTE]
====
. Ou: “pretório”.
====

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]