include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-13-1]]

^<<v44-13-1,1>>^ Em Antioquia, havia profetas e instrutores na congregação local: Barnabé; Simeão, que era chamado Níger; Lúcio, de Cirene; Manaém, que tinha sido educado com Herodes, o governador distrital; e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ Enquanto estavam a servir^&#42;1^ a Jeová^&#42;2^ e a jejuar, o espírito santo disse: “Separem-me Barnabé e Saulo para a obra a que os chamei.”

[NOTE]
====
. Ou: “a prestar serviço público”.
. Veja o Ap. A5.
====

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, depois de jejuar e orar, eles impuseram-lhes as mãos e deixaram-nos ir.

[[v44-13-4]]

^<<v44-13-4,4>>^ Assim, estes homens, enviados pelo espírito santo, desceram até Selêucia e de lá navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ Quando chegaram a Salamina, começaram a proclamar a palavra de Deus nas sinagogas dos judeus. João também estava com eles, como ajudante.^&#42;1^

[NOTE]
====
. Ou: “assistente”.
====

[[v44-13-6]]

^<<v44-13-6,6>>^ Depois de percorrerem toda a ilha até Pafos, encontraram um judeu chamado Barjesus, que era feiticeiro e falso profeta.

[[v44-13-7]]

^<<v44-13-7,7>>^ Ele estava com o procônsul^&#42;1^ Sérgio Paulo, homem inteligente. Este chamou Barnabé e Saulo, pois queria muito ouvir a palavra de Deus.

[NOTE]
====
. Governador romano de uma província. Veja o Glossário.
====

[[v44-13-8]]

^<<v44-13-8,8>>^ Contudo, Elimas, o feiticeiro (pois é assim que se traduz o seu nome), começou a opor-se a eles, tentando desviar o procônsul da fé.

[[v44-13-9]]

^<<v44-13-9,9>>^ Então, Saulo, também chamado Paulo, ficou cheio de espírito santo, olhou atentamente para ele

[[v44-13-10]]

^<<v44-13-10,10>>^ e disse: “Ó homem cheio de todo o tipo de fraude e maldade, ó filho do Diabo, inimigo de tudo o que é justo, não vais parar de distorcer os caminhos retos de Jeová?^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-11]]

^<<v44-13-11,11>>^ Escuta: a mão de Jeová^&#42;1^ está sobre ti, e ficarás cego, sem ver a luz do sol por um tempo.” Instantaneamente, caiu sobre ele uma densa névoa e escuridão, e ele começou a andar à roda, tentando encontrar alguém que o guiasse pela mão.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-12]]

^<<v44-13-12,12>>^ Então, ao ver o que tinha acontecido, o procônsul tornou-se crente, pois ficou impressionado com os ensinamentos de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-13]]

^<<v44-13-13,13>>^ Paulo e os seus companheiros embarcaram então em Pafos e chegaram a Perge, na Panfília. Porém, João deixou-os e voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ No entanto, eles seguiram viagem a partir de Perge e chegaram a Antioquia, na Pisídia. Entraram então na sinagoga no dia de sábado e sentaram-se.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura pública da Lei e dos Profetas, os presidentes da sinagoga mandaram dizer-lhes: “Homens, irmãos, se tiverem alguma palavra de encorajamento para o povo, falem.”

[[v44-13-16]]

^<<v44-13-16,16>>^ Assim, Paulo levantou-se, fez sinal com a mão e disse:
“Homens, israelitas e todos os outros que temem a Deus, escutem!

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus deste povo, o Deus de Israel, escolheu os nossos antepassados; ele enalteceu o povo enquanto moravam como estrangeiros na terra do Egito e tirou-os de lá com braço forte.^&#42;1^

[NOTE]
====
. Lit.: “com braço erguido”.
====

[[v44-13-18]]

^<<v44-13-18,18>>^ E, por cerca de 40 anos, ele suportou-os no deserto.

[[v44-13-19]]

^<<v44-13-19,19>>^ Destruiu sete nações na terra de Canaã e deu a terra delas como herança.

[[v44-13-20]]

^<<v44-13-20,20>>^ Tudo isto aconteceu durante cerca de 450 anos.
“Depois, deu-lhes juízes até Samuel, o profeta.

[[v44-13-21]]

^<<v44-13-21,21>>^ Contudo, exigiram um rei, e Deus deu-lhes Saul, filho de Quis, homem da tribo de Benjamim, por 40 anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ Após removê-lo, elevou-lhes David como rei, a respeito de quem deu testemunho, dizendo: ‘Encontrei David, filho de Jessé, um homem que agrada ao meu coração; ele fará tudo o que desejo.’

[[v44-13-23]]

^<<v44-13-23,23>>^ Segundo a sua promessa, Deus trouxe a Israel um salvador, Jesus, a partir da descendência^&#42;1^ daquele homem.

[NOTE]
====
. Lit.: “semente”.
====

[[v44-13-24]]

^<<v44-13-24,24>>^ Antes da chegada dele, João pregou publicamente a todo o povo de Israel o batismo em símbolo de arrependimento.

[[v44-13-25]]

^<<v44-13-25,25>>^ Todavia, quando estava a terminar a sua missão, João dizia: ‘Quem é que vocês acham que eu sou? Eu não sou ele. Na verdade, depois de mim, vem alguém cujas sandálias não sou digno de desatar.’

[[v44-13-26]]

^<<v44-13-26,26>>^ “Homens, irmãos, descendentes da família de Abraão e todos os outros entre vocês que temem a Deus, esta mensagem de salvação foi-nos enviada.

[[v44-13-27]]

^<<v44-13-27,27>>^ Pois os habitantes de Jerusalém e os seus líderes não reconheceram este salvador, mas, ao agirem como juízes, cumpriram as palavras dos Profetas, que são lidas em voz alta todos os sábados.

[[v44-13-28]]

^<<v44-13-28,28>>^ Embora não encontrassem uma razão para matá-lo, exigiram que Pilatos mandasse executá-lo.

[[v44-13-29]]

^<<v44-13-29,29>>^ E, depois de realizarem todas as coisas escritas a respeito dele, tiraram-no do madeiro^&#42;1^ e colocaram-no num túmulo.^&#42;2^

[NOTE]
====
. Ou: “da árvore”.
. Ou: “túmulo memorial”.
====

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus levantou-o dentre os mortos,

[[v44-13-31]]

^<<v44-13-31,31>>^ e, durante muitos dias, ele apareceu aos que tinham subido com ele da Galileia para Jerusalém. Estes estão agora a dar testemunho dele ao povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ “Assim, nós estamos a declarar-vos as boas novas a respeito da promessa feita aos nossos antepassados.

[[v44-13-33]]

^<<v44-13-33,33>>^ Deus cumpriu-a plenamente para nós, os filhos, ressuscitando Jesus, assim como está escrito no segundo salmo: ‘Tu és meu filho; hoje, tornei-me teu pai.’

[[v44-13-34]]

^<<v44-13-34,34>>^ E o facto de que Deus o ressuscitou dentre os mortos para que ele nunca mais tivesse um corpo perecível, Ele declarou do seguinte modo: ‘Vou dar-vos as fiéis^&#42;1^ expressões de amor leal prometidas a David.’

[NOTE]
====
. Ou: “fidedignas; confiáveis”.
====

[[v44-13-35]]

^<<v44-13-35,35>>^ Por isso, também se diz noutro salmo: ‘Não permitirás que o teu leal conheça a decomposição.’

[[v44-13-36]]

^<<v44-13-36,36>>^ David prestou serviço a Deus^&#42;1^ na sua geração, adormeceu na morte, foi enterrado com os seus antepassados e conheceu a decomposição.

[NOTE]
====
. Ou: “serviu à vontade de Deus”.
====

[[v44-13-37]]

^<<v44-13-37,37>>^ Porém, aquele a quem Deus levantou não conheceu a decomposição.

[[v44-13-38]]

^<<v44-13-38,38>>^ “Portanto, irmãos, saibam que é por meio deste homem que vos é proclamado o perdão de pecados,

[[v44-13-39]]

^<<v44-13-39,39>>^ e que, por meio dele, todo aquele que crê é declarado inocente de todas as coisas das quais não podia ser declarado inocente por meio da Lei de Moisés.

[[v44-13-40]]

^<<v44-13-40,40>>^ Assim, tenham cuidado para que não vos sobrevenha aquilo que se disse nos Profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ ‘Vejam, ridicularizadores, pasmem-se e desapareçam, pois estou a realizar uma obra nos vossos dias, uma obra em que jamais acreditarão, mesmo que vos seja contada em pormenor.’”

[[v44-13-42]]

^<<v44-13-42,42>>^ Quando estavam a sair, as pessoas suplicaram-lhes que falassem destes assuntos no sábado seguinte.

[[v44-13-43]]

^<<v44-13-43,43>>^ Depois de acabar a reunião da sinagoga, muitos judeus e prosélitos que adoravam a Deus seguiram Paulo e Barnabé, que, ao falarem com eles, exortavam-nos a permanecer na bondade imerecida de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, quase toda a cidade se reuniu para ouvir a palavra de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-45]]

^<<v44-13-45,45>>^ Quando os judeus viram as multidões, ficaram cheios de ciúme e começaram a contradizer de modo blasfemo o que Paulo estava a dizer.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então, Paulo e Barnabé disseram-lhes corajosamente: “Era necessário que se transmitisse a palavra de Deus primeiro a vocês. Visto que a rejeitam e não se julgam dignos da vida eterna, vamos agora voltar-nos para as nações.

[[v44-13-47]]

^<<v44-13-47,47>>^ Pois Jeová^&#42;1^ deu-nos esta ordem: ‘Designei-te como luz para as nações, para que leves a salvação até aos confins da terra.’”

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-48]]

^<<v44-13-48,48>>^ Quando as pessoas das nações ouviram isto, alegraram-se e começaram a glorificar a palavra de Jeová,^&#42;1^ e todos os que tinham a disposição correta para com a vida eterna tornaram-se crentes.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-49]]

^<<v44-13-49,49>>^ Além disso, a palavra de Jeová^&#42;1^ era divulgada por toda a região.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-13-50]]

^<<v44-13-50,50>>^ Contudo, os judeus instigaram as mulheres de alta posição que eram tementes a Deus, bem como os homens mais importantes da cidade; incitaram uma perseguição contra Paulo e Barnabé e expulsaram-nos do seu território.

[[v44-13-51]]

^<<v44-13-51,51>>^ Então, estes sacudiram o pó dos seus pés em testemunho contra eles e foram para Icónio.

[[v44-13-52]]

^<<v44-13-52,52>>^ E os discípulos continuavam cheios de alegria e de espírito santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]