include::./index.adoc[]

[[v44-21-0]]
=== Atos, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-21-1]]

^<<v44-21-1,1>>^ Quando finalmente nos conseguimos separar deles e embarcar, navegámos diretamente para Cós. No dia seguinte, fomos para Rodes e, de lá, para Pátara.

[[v44-21-2]]

^<<v44-21-2,2>>^ Quando encontrámos um navio que ia fazer a travessia para a Fenícia, embarcámos e seguimos viagem.

[[v44-21-3]]

^<<v44-21-3,3>>^ Depois de avistarmos e passarmos a ilha de Chipre, à nossa esquerda,^&#42;1^ navegámos para a Síria e fizemos escala em Tiro, onde o navio ia descarregar.

[NOTE]
====
. Ou: “a bombordo”.
====

[[v44-21-4]]

^<<v44-21-4,4>>^ Procurámos os discípulos e encontrámo-los, e permanecemos lá durante sete dias. Contudo, por meio do espírito, eles diziam repetidamente a Paulo que não pusesse os pés em Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Assim, quando terminou a nossa estadia, partimos e continuámos a nossa viagem; e todos eles, juntamente com as mulheres e as crianças, acompanharam-nos até fora da cidade. Então, ajoelhados na praia, orámos

[[v44-21-6]]

^<<v44-21-6,6>>^ e despedimo-nos uns dos outros. Depois, embarcámos no navio e eles voltaram para casa.

[[v44-21-7]]

^<<v44-21-7,7>>^ Completámos assim a viagem, navegando de Tiro até chegarmos a Ptolemaida; cumprimentámos os irmãos e ficámos com eles durante um dia.

[[v44-21-8]]

^<<v44-21-8,8>>^ Partimos no dia seguinte e chegámos a Cesareia; lá, entrámos na casa de Filipe, o evangelizador, que era um dos sete homens, e ficámos com ele.

[[v44-21-9]]

^<<v44-21-9,9>>^ Este homem tinha quatro filhas solteiras^&#42;1^ que profetizavam.

[NOTE]
====
. Lit.: “virgens”.
====

[[v44-21-10]]

^<<v44-21-10,10>>^ Depois de lá ficarmos durante muitos dias, um profeta chamado Ágabo desceu da Judeia.

[[v44-21-11]]

^<<v44-21-11,11>>^ Ele veio ao nosso encontro, pegou no cinto de Paulo, amarrou os seus próprios pés e mãos, e disse: “Assim diz o espírito santo: ‘O homem a quem pertence este cinto será amarrado assim pelos judeus em Jerusalém, e eles vão entregá-lo às mãos de pessoas das nações.’”

[[v44-21-12]]

^<<v44-21-12,12>>^ Quando ouvimos isto, tanto nós como os que lá estavam começámos a implorar-lhe que não subisse a Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Paulo respondeu então: “O que é que estão a fazer, ao chorarem e ao tentarem enfraquecer a minha determinação?^&#42;1^ Estejam certos de que estou pronto não só para ser amarrado, mas também para morrer em Jerusalém pelo nome do Senhor Jesus.”

[NOTE]
====
. Ou: “o meu coração”.
====

[[v44-21-14]]

^<<v44-21-14,14>>^ Como não conseguimos convencê-lo, parámos de insistir^&#42;1^ e dissemos: “Seja feita a vontade de Jeová.”^&#42;2^

[NOTE]
====
. Lit.: “ficámos em silêncio”.
. Veja o Ap. A5.
====

[[v44-21-15]]

^<<v44-21-15,15>>^ Depois daqueles dias, fizemos os preparativos e começámos a viagem para Jerusalém.

[[v44-21-16]]

^<<v44-21-16,16>>^ Alguns dos discípulos de Cesareia foram connosco e levaram-nos à casa de Mnáson, de Chipre, um dos primeiros discípulos, com quem ficaríamos hospedados.

[[v44-21-17]]

^<<v44-21-17,17>>^ Ao chegarmos a Jerusalém, os irmãos receberam-nos com alegria.

[[v44-21-18]]

^<<v44-21-18,18>>^ No dia seguinte, Paulo foi connosco ao encontro de Tiago, e todos os anciãos estavam presentes.

[[v44-21-19]]

^<<v44-21-19,19>>^ Ele cumprimentou-os e fez um relatório detalhado sobre as coisas que Deus tinha feito entre as nações por meio do ministério dele.

[[v44-21-20]]

^<<v44-21-20,20>>^ Depois de ouvirem isto, eles começaram a glorificar a Deus, mas disseram-lhe: “Irmão, tu sabes quantos milhares de judeus se tornaram crentes e que todos eles têm zelo pela Lei.

[[v44-21-21]]

^<<v44-21-21,21>>^ No entanto, eles ouviram rumores de que estás a ensinar todos os judeus que vivem entre as nações a abandonar a Lei de^&#42;1^ Moisés, dizendo-lhes que não circuncidem os seus filhos nem sigam os costumes estabelecidos.

[NOTE]
====
. Ou: “entre as nações uma apostasia contra”.
====

[[v44-21-22]]

^<<v44-21-22,22>>^ O que devemos, então, fazer a respeito disso? Eles certamente ficarão a saber que chegaste.

[[v44-21-23]]

^<<v44-21-23,23>>^ Portanto, faz o que te vamos dizer: Há connosco quatro homens que têm um voto a cumprir.

[[v44-21-24]]

^<<v44-21-24,24>>^ Leva esses homens contigo, purifica-te cerimonialmente com eles e cuida das suas despesas, para que rapem as suas cabeças. Assim, todos saberão que o que se diz sobre ti não é verdade, mas que estás a andar corretamente e também a obedecer à Lei.

[[v44-21-25]]

^<<v44-21-25,25>>^ Quanto aos crentes dentre as nações, enviámos-lhes por escrito a nossa decisão de que se devem abster do que é sacrificado a ídolos, bem como de sangue, do que foi estrangulado^&#42;1^ e de imoralidade sexual.”^&#42;2^

[NOTE]
====
. Ou: “do que foi morto sem ser sangrado”.
. Em grego, porneía. Veja o Glossário.
====

[[v44-21-26]]

^<<v44-21-26,26>>^ Então, no dia seguinte, Paulo levou os homens consigo e purificou-se cerimonialmente com eles. Depois disso, entrou no templo para avisar quando se completariam os dias da purificação cerimonial e quando seria apresentada a oferta a favor de cada um deles.

[[v44-21-27]]

^<<v44-21-27,27>>^ Quando os sete dias estavam a chegar ao fim, ao vê-lo no templo, os judeus da Ásia agitaram toda a multidão e agarraram-no,

[[v44-21-28]]

^<<v44-21-28,28>>^ gritando: “Homens de Israel, ajudem-nos! Este é o homem que ensina a todos, em todo o lado, coisas contra o nosso povo, contra a nossa Lei e contra este lugar. E, além disso, ele até mesmo trouxe gregos ao templo e profanou este lugar santo.”

[[v44-21-29]]

^<<v44-21-29,29>>^ Pois, antes, tinham visto Trófimo, o efésio, na cidade com ele, e pensaram que Paulo o tinha levado ao templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ Toda a cidade ficou em alvoroço e as pessoas vieram a correr em massa, agarraram Paulo, arrastaram-no para fora do templo, e, imediatamente, as portas foram fechadas.

[[v44-21-31]]

^<<v44-21-31,31>>^ Enquanto tentavam matá-lo, o comandante do regimento recebeu a notícia de que toda a cidade de Jerusalém estava em confusão.

[[v44-21-32]]

^<<v44-21-32,32>>^ Imediatamente, reuniu soldados e oficiais do exército, e desceu a correr até à multidão. Quando as pessoas viram o comandante militar e os soldados, pararam de espancar Paulo.

[[v44-21-33]]

^<<v44-21-33,33>>^ Então, o comandante aproximou-se, prendeu-o, e mandou que o amarrassem com duas correntes. De seguida, perguntou quem ele era e o que tinha feito.

[[v44-21-34]]

^<<v44-21-34,34>>^ Todavia, alguns da multidão gritavam uma coisa, e outros gritavam outra. Assim, como não conseguia saber nada ao certo por causa do tumulto, ordenou que o levassem ao quartel.

[[v44-21-35]]

^<<v44-21-35,35>>^ Quando ele chegou às escadas, teve de ser carregado pelos soldados, por causa da violência da multidão,

[[v44-21-36]]

^<<v44-21-36,36>>^ pois havia uma multidão de pessoas que o seguia, gritando: “Matem-no!”

[[v44-21-37]]

^<<v44-21-37,37>>^ Quando estava prestes a ser levado para dentro do quartel, Paulo perguntou ao comandante: “É-me permitido dizer-lhe algo?” Ele disse: “Sabes falar grego?

[[v44-21-38]]

^<<v44-21-38,38>>^ Então, não és o egípcio que há algum tempo atiçou uma sedição^&#42;1^ e levou os 4000 assassinos^&#42;2^ para o deserto?”

[NOTE]
====
. Ou: “revolta; perturbação da ordem pública”.
. Ou: “faquistas”.
====

[[v44-21-39]]

^<<v44-21-39,39>>^ Paulo respondeu: “Na realidade, sou judeu, cidadão de Tarso, uma cidade importante da Cilícia. Portanto, peço-lhe que me permita falar ao povo.”

[[v44-21-40]]

^<<v44-21-40,40>>^ Depois de ele dar permissão, Paulo, de pé nas escadas, fez sinal com a mão para o povo. Fez-se um grande silêncio e, então, ele dirigiu-se a eles no idioma hebraico, dizendo:

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]