include::./index.adoc[]

[[v44-22-0]]
=== Atos, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-22-1]]

^<<v44-22-1,1>>^ “Homens, irmãos e pais, ouçam agora o que vos vou dizer em minha defesa.”

[[v44-22-2]]

^<<v44-22-2,2>>^ Quando o ouviram a falar com eles no idioma hebraico, ficaram ainda mais calados. Então, ele disse:

[[v44-22-3]]

^<<v44-22-3,3>>^ “Eu sou judeu, nascido em Tarso da Cilícia, mas educado nesta cidade, aos pés de Gamaliel. Fui instruído segundo o rigor da Lei dos nossos antepassados, sendo zeloso por Deus, assim como todos vocês o são hoje.

[[v44-22-4]]

^<<v44-22-4,4>>^ Eu perseguia até à morte os seguidores deste Caminho, amarrando e mandando para a prisão tanto homens como mulheres;

[[v44-22-5]]

^<<v44-22-5,5>>^ o sumo sacerdote e toda a assembleia dos anciãos podem testemunhá-lo. Eles também me deram cartas para os irmãos de Damasco, e eu estava a dirigir-me para lá, a fim de trazer para Jerusalém, amarrados, os que lá estavam, de modo a que fossem punidos.

[[v44-22-6]]

^<<v44-22-6,6>>^ “Porém, durante a viagem, por volta do meio-dia, eu estava a chegar perto de Damasco quando, de repente, uma grande luz vinda do céu brilhou ao meu redor,

[[v44-22-7]]

^<<v44-22-7,7>>^ e eu caí ao chão e ouvi uma voz dizer-me: ‘Saulo, Saulo, porque é que me persegues?’

[[v44-22-8]]

^<<v44-22-8,8>>^ Eu respondi: ‘Quem é o senhor?’ E ele disse-me: ‘Eu sou Jesus, o Nazareno, a quem persegues.’

[[v44-22-9]]

^<<v44-22-9,9>>^ E os homens que estavam comigo viram a luz, mas não ouviram a voz daquele que falava comigo.

[[v44-22-10]]

^<<v44-22-10,10>>^ Então, eu perguntei: ‘O que devo fazer, Senhor?’ O Senhor respondeu: ‘Levanta-te, vai a Damasco, e lá serás informado de tudo o que foste designado para fazer.’

[[v44-22-11]]

^<<v44-22-11,11>>^ Mas, como eu não conseguia ver nada por causa do brilho daquela luz, cheguei a Damasco levado pela mão dos que estavam comigo.

[[v44-22-12]]

^<<v44-22-12,12>>^ “Então, um homem chamado Ananias, que era devoto conforme a Lei e a respeito de quem todos os judeus daquele lugar falavam bem,

[[v44-22-13]]

^<<v44-22-13,13>>^ veio procurar-me. Chegou perto de mim e disse-me: ‘Saulo, irmão, recupera a vista!’ E, nesse preciso instante, recuperei a vista^&#42;1^ e vi-o.

[NOTE]
====
. Ou: “levantei os olhos”.
====

[[v44-22-14]]

^<<v44-22-14,14>>^ Ele disse: ‘O Deus dos nossos antepassados escolheu-te para conheceres a sua vontade, para veres o Justo e para ouvires a voz que sai da sua boca,

[[v44-22-15]]

^<<v44-22-15,15>>^ porque serás sua testemunha, perante todos os homens, das coisas que viste e ouviste.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora, de que é que estás à espera? Levanta-te, sê batizado e lava os teus pecados por invocares o nome dele.’

[[v44-22-17]]

^<<v44-22-17,17>>^ “No entanto, depois de voltar a Jerusalém, eu estava a orar no templo quando entrei em transe

[[v44-22-18]]

^<<v44-22-18,18>>^ e vi o Senhor a dizer-me: ‘Depressa, sai já de Jerusalém, porque não aceitarão o teu testemunho a meu respeito.’

[[v44-22-19]]

^<<v44-22-19,19>>^ Então, eu disse: ‘Senhor, eles sabem muito bem que, numa sinagoga após outra, eu prendia e açoitava os que criam em ti.

[[v44-22-20]]

^<<v44-22-20,20>>^ E enquanto se derramava o sangue de Estêvão, tua testemunha, eu estava lá, a aprovar aquilo e a tomar conta das capas dos que o matavam.’

[[v44-22-21]]

^<<v44-22-21,21>>^ Contudo, ele disse-me: ‘Vai, porque vou enviar-te a nações distantes.’”

[[v44-22-22]]

^<<v44-22-22,22>>^ Eles ouviram-no até estas palavras. Depois, levantaram a voz, dizendo: “Eliminem este homem da terra, pois não merece viver!”

[[v44-22-23]]

^<<v44-22-23,23>>^ Visto que gritavam, agitavam as suas capas e lançavam terra para o ar,

[[v44-22-24]]

^<<v44-22-24,24>>^ o comandante militar mandou levar Paulo para dentro do quartel e ordenou que fosse interrogado sob açoites, para saber exatamente por que motivo gritavam assim contra ele.

[[v44-22-25]]

^<<v44-22-25,25>>^ Todavia, depois de o amarrarem para ser chicoteado, Paulo perguntou ao oficial do exército que lá estava: “A lei permite-vos açoitar um romano^&#42;1^ que não foi condenado?”^&#42;2^

[NOTE]
====
. Ou: “cidadão romano”.
. Ou: “julgado”.
====

[[v44-22-26]]

^<<v44-22-26,26>>^ Quando o oficial ouviu isso, foi contar ao comandante e disse-lhe: “O que é que o senhor pretende fazer? Este homem é romano!”

[[v44-22-27]]

^<<v44-22-27,27>>^ Portanto, o comandante aproximou-se dele e disse: “Diz-me, és romano?” Ele respondeu: “Sim.”

[[v44-22-28]]

^<<v44-22-28,28>>^ O comandante disse então: “Eu comprei estes direitos de cidadão com muito dinheiro.” Paulo disse: “Mas eu já nasci com esses direitos.”

[[v44-22-29]]

^<<v44-22-29,29>>^ Com isto, os homens que estavam prestes a interrogá-lo e a torturá-lo recuaram imediatamente. E o comandante ficou com medo ao saber que ele era romano e que o tinha acorrentado.

[[v44-22-30]]

^<<v44-22-30,30>>^ Assim, no dia seguinte, querendo saber ao certo por que motivo ele estava a ser acusado pelos judeus, soltou-o e mandou que os principais sacerdotes e todo o Sinédrio se reunissem. Então, trouxe Paulo para baixo e colocou-o de pé no meio deles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]