include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-12-1]]

^<<v44-12-1,1>>^ Naquela época, o rei Herodes começou a maltratar alguns da congregação.

[[v44-12-2]]

^<<v44-12-2,2>>^ Ele mandou matar Tiago, irmão de João, com a espada.

[[v44-12-3]]

^<<v44-12-3,3>>^ Ao ver que isso agradava aos judeus, prendeu também Pedro. (Isto aconteceu nos dias dos Pães sem Fermento.)

[[v44-12-4]]

^<<v44-12-4,4>>^ Ele deteve-o e mandou-o para a prisão, entregando-o aos cuidados de quatro turnos de soldados, com quatro soldados cada um, com a intenção de apresentá-lo ao^&#42;1^ povo depois da Páscoa.

[NOTE]
====
. Ou: “trazê-lo a julgamento diante do”.
====

[[v44-12-5]]

^<<v44-12-5,5>>^ Por conseguinte, Pedro ficou detido na prisão, mas a congregação orava intensamente a Deus por ele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Herodes estava prestes a apresentar Pedro. Naquela noite, ele estava a dormir, preso com duas correntes, entre dois soldados, e em frente à porta havia guardas que vigiavam a prisão.

[[v44-12-7]]

^<<v44-12-7,7>>^ Mas, de repente, o anjo de Jeová^&#42;1^ apareceu, e uma luz brilhou na cela da prisão. Ele tocou no lado de Pedro e acordou-o, dizendo: “Levanta-te depressa!” E as correntes caíram-lhe das mãos.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-12-8]]

^<<v44-12-8,8>>^ O anjo disse-lhe: “Veste-te^&#42;1^ e calça as sandálias”, e Pedro fez isso. Por fim, ele disse-lhe: “Põe a tua capa e segue-me.”

[NOTE]
====
. Ou: “Cinge-te”.
====

[[v44-12-9]]

^<<v44-12-9,9>>^ Então, ele saiu e seguiu-o, mas não sabia que aquilo que estava a acontecer por meio do anjo era real. Na verdade, ele achou que estava a ter uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Passaram pelo primeiro posto de guarda, pelo segundo, e chegaram ao portão de ferro que dava para a cidade. Este abriu-se sozinho. Depois de saírem, seguiram por uma rua e, de repente, o anjo deixou-o.

[[v44-12-11]]

^<<v44-12-11,11>>^ Percebendo o que estava a acontecer, Pedro disse: “Agora sei, sem dúvida nenhuma, que Jeová^&#42;1^ enviou o seu anjo e livrou-me das mãos de Herodes e de tudo o que o povo judeu esperava que acontecesse.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-12-12]]

^<<v44-12-12,12>>^ Depois de ele ter compreendido isto, foi à casa de Maria, mãe de João, conhecido como Marcos, onde muitos estavam reunidos a orar.

[[v44-12-13]]

^<<v44-12-13,13>>^ Quando bateu ao portão de entrada, uma serva chamada Rode foi atender.

[[v44-12-14]]

^<<v44-12-14,14>>^ Ao reconhecer a voz de Pedro, ficou tão contente que não abriu o portão, mas correu para dentro e foi contar-lhes que Pedro estava no portão.

[[v44-12-15]]

^<<v44-12-15,15>>^ Disseram-lhe: “Estás louca.” Contudo, ela insistia que era verdade. E eles diziam: “É o anjo dele.”

[[v44-12-16]]

^<<v44-12-16,16>>^ No entanto, Pedro continuou ali, a bater. Quando abriram, viram-no e ficaram pasmados.

[[v44-12-17]]

^<<v44-12-17,17>>^ Então ele fez-lhes sinal com a mão para que ficassem calados, contou-lhes em detalhes como Jeová^&#42;1^ o tinha tirado da prisão e disse: “Contem estas coisas a Tiago e aos irmãos.” Assim, ele saiu de lá e foi para outro lugar.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-12-18]]

^<<v44-12-18,18>>^ Quando amanheceu, houve uma grande confusão entre os soldados, que se perguntavam a respeito do que teria acontecido com Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herodes procurou-o cuidadosamente e, como não o encontrou, interrogou os guardas e mandou que fossem levados para serem punidos. Depois, desceu da Judeia para Cesareia e passou lá algum tempo.

[[v44-12-20]]

^<<v44-12-20,20>>^ Ele estava furioso^&#42;1^ com o povo de Tiro e de Sídon. Então, estes foram ao encontro dele de comum acordo e, depois de convencerem Blasto, o administrador da casa do rei,^&#42;2^ pediram termos de paz, porque o país do rei supria a região deles com alimento.

[NOTE]
====
. Ou: “disposto a brigar”.
. Lit.: “aquele que estava sobre o dormitório do rei”.
====

[[v44-12-21]]

^<<v44-12-21,21>>^ Num determinado dia, Herodes vestiu a roupa real, sentou-se no tribunal e começou a fazer um discurso público.

[[v44-12-22]]

^<<v44-12-22,22>>^ Assim, o povo que estava reunido começou a gritar: “É a voz de um deus e não de um homem!”

[[v44-12-23]]

^<<v44-12-23,23>>^ Instantaneamente, o anjo de Jeová^&#42;1^ feriu-o, porque ele não deu glória a Deus. E ele morreu comido por vermes.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-12-24]]

^<<v44-12-24,24>>^ Todavia, a palavra de Jeová^&#42;1^ crescia e espalhava-se.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-12-25]]

^<<v44-12-25,25>>^ Quanto a Barnabé e Saulo, depois de terem terminado o seu trabalho de prestar ajuda em Jerusalém, voltaram e levaram consigo João, que também era conhecido como Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]