include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-2-1]]

^<<v44-2-1,1>>^ Então, durante o dia da Festividade de Pentecostes, todos eles estavam juntos no mesmo lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente, veio do céu um barulho, muito semelhante ao de uma forte rajada de vento, e encheu toda a casa onde estavam sentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E eles começaram a ver o que pareciam ser línguas de fogo, e estas espalharam-se e pousou uma sobre cada um deles;

[[v44-2-4]]

^<<v44-2-4,4>>^ e todos ficaram cheios de espírito santo e começaram a falar em línguas, assim como o espírito os capacitava.

[[v44-2-5]]

^<<v44-2-5,5>>^ Naquela ocasião, estavam em Jerusalém judeus devotos de todas as nações debaixo do céu.

[[v44-2-6]]

^<<v44-2-6,6>>^ Assim, quando se ouviu aquele som, juntou-se uma multidão e ficaram surpreendidos, porque cada um ouvia os discípulos a falar no seu próprio idioma.

[[v44-2-7]]

^<<v44-2-7,7>>^ Realmente, ficaram muito espantados e disseram: “Não são galileus todos estes que estão a falar?

[[v44-2-8]]

^<<v44-2-8,8>>^ Como é que cada um de nós está a ouvir a sua própria língua nativa?^&#42;1^

[NOTE]
====
. Ou: “a língua do seu nascimento”.
====

[[v44-2-9]]

^<<v44-2-9,9>>^ Entre nós há partos, medos e elamitas, habitantes da Mesopotâmia, da Judeia e da Capadócia, de Ponto e da província da Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ da Frígia e da Panfília, do Egito e das regiões da Líbia próximas de Cirene, visitantes vindos de Roma, tanto judeus como prosélitos,

[[v44-2-11]]

^<<v44-2-11,11>>^ cretenses e também árabes. Ouvimo-los falar nas nossas línguas sobre as coisas magníficas de Deus.”

[[v44-2-12]]

^<<v44-2-12,12>>^ Sim, todos ficaram admirados e perplexos, e diziam uns aos outros: “O que é que isto significa?”

[[v44-2-13]]

^<<v44-2-13,13>>^ No entanto, outros faziam pouco deles e diziam: “Estão cheios de vinho doce.”^&#42;1^

[NOTE]
====
. Ou: “vinho novo”.
====

[[v44-2-14]]

^<<v44-2-14,14>>^ Contudo, Pedro pôs-se de pé com os Onze e disse-lhes bem alto: “Homens da Judeia e todos vocês, habitantes de Jerusalém, prestem atenção e ouçam bem as minhas palavras:

[[v44-2-15]]

^<<v44-2-15,15>>^ Na verdade, estas pessoas não estão bêbedas, como vocês supõem, pois é a terceira hora^&#42;1^ do dia.

[NOTE]
====
. Isto é, por volta das 9 h da manhã.
====

[[v44-2-16]]

^<<v44-2-16,16>>^ Pelo contrário, isto é o que foi dito por meio do profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ ‘“Nos últimos dias”, diz Deus, “derramarei do meu espírito sobre todo o tipo de pessoas,^&#42;1^ e os vossos filhos e as vossas filhas profetizarão, os vossos jovens terão visões e os vossos homens idosos terão sonhos,

[NOTE]
====
. Lit.: “sobre toda a carne”.
====

[[v44-2-18]]

^<<v44-2-18,18>>^ e até mesmo sobre os meus escravos e sobre as minhas escravas derramarei do meu espírito nesses dias, e eles profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ E realizarei milagres^&#42;1^ em cima, no céu, e sinais em baixo, na terra: sangue, fogo e nuvens de fumo.

[NOTE]
====
. Ou: “portentos”.
====

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol será transformado em escuridão e a lua em sangue, antes de vir o grande e glorioso dia de Jeová.^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-2-21]]

^<<v44-2-21,21>>^ E todo aquele que invocar o nome de Jeová^&#42;1^ será salvo.”’

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-2-22]]

^<<v44-2-22,22>>^ “Homens de Israel, ouçam estas palavras: Jesus, o Nazareno, foi um homem que Deus aprovou à vossa frente com obras poderosas, milagres^&#42;1^ e sinais que Deus fez por meio dele no vosso meio, conforme sabem.

[NOTE]
====
. Ou: “portentos”.
====

[[v44-2-23]]

^<<v44-2-23,23>>^ Pelas mãos de transgressores, vocês pregaram este homem numa estaca, o qual foi entregue pela estabelecida vontade^&#42;1^ e presciência de Deus, e mataram-no.

[NOTE]
====
. Ou: “pelo estabelecido conselho”.
====

[[v44-2-24]]

^<<v44-2-24,24>>^ Porém, Deus ressuscitou-o, livrando-o dos grilhões^&#42;1^ da morte, porque não era possível que ela o mantivesse preso.

[NOTE]
====
. Ou, possivelmente: “das cordas”.
====

[[v44-2-25]]

^<<v44-2-25,25>>^ Pois David diz a respeito dele: ‘Mantenho Jeová^&#42;1^ constantemente diante de mim,^&#42;2^ pois ele está à minha direita para que eu nunca seja abalado.

[NOTE]
====
. Veja o Ap. A5.
. Ou: “diante dos meus olhos”.
====

[[v44-2-26]]

^<<v44-2-26,26>>^ Por esta razão, o meu coração ficou animado e a minha língua alegrou-se muito. E eu viverei^&#42;1^ em esperança;

[NOTE]
====
. Lit.: “a minha carne morará”.
====

[[v44-2-27]]

^<<v44-2-27,27>>^ porque não me deixarás^&#42;1^ na Sepultura,^&#42;2^ nem permitirás que o teu leal conheça a decomposição.

[NOTE]
====
. Ou: “não deixarás a minha alma”.
. Ou: “no Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v44-2-28]]

^<<v44-2-28,28>>^ Fizeste-me conhecer os caminhos da vida; hás de encher-me de alegria na tua presença.’^&#42;1^

[NOTE]
====
. Ou: “diante da tua face”.
====

[[v44-2-29]]

^<<v44-2-29,29>>^ “Homens, irmãos, permitam-me falar-vos com franqueza sobre o patriarca David: ele morreu e foi enterrado, e o seu túmulo está entre nós até ao dia de hoje.

[[v44-2-30]]

^<<v44-2-30,30>>^ Visto que era profeta e sabia que Deus lhe tinha jurado fazer com que um dos seus descendentes^&#42;1^ se sentasse no seu trono,

[NOTE]
====
. Lit.: “um procedente do fruto dos seus lombos”.
====

[[v44-2-31]]

^<<v44-2-31,31>>^ ele previu a ressurreição do Cristo e falou sobre ela, que ele não seria abandonado na Sepultura^&#42;1^ e que a sua carne não conheceria a decomposição.

[NOTE]
====
. Ou: “no Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v44-2-32]]

^<<v44-2-32,32>>^ Deus ressuscitou este Jesus e todos nós somos testemunhas disso.

[[v44-2-33]]

^<<v44-2-33,33>>^ Portanto, visto que ele foi enaltecido à direita de Deus e recebeu do Pai o prometido espírito santo, derramou o que vocês estão a ver e a ouvir.

[[v44-2-34]]

^<<v44-2-34,34>>^ Pois David não subiu aos céus, mas ele diz: ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita,

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os teus inimigos debaixo dos teus pés.”’^&#42;1^

[NOTE]
====
. Ou: “como escabelo para os teus pés”.
====

[[v44-2-36]]

^<<v44-2-36,36>>^ Portanto, que toda a casa de Israel tenha a plena certeza de que Deus fez deste Jesus, que vocês mataram numa estaca, Senhor e Cristo.”

[[v44-2-37]]

^<<v44-2-37,37>>^ Quando ouviram isto, ficaram com o coração aflito e disseram a Pedro e aos outros apóstolos: “Homens, irmãos, o que é que devemos fazer?”

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro disse-lhes: “Arrependam-se e seja cada um de vocês batizado em nome de Jesus Cristo, para o perdão dos vossos pecados, e receberão a dádiva^&#42;1^ do espírito santo.

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v44-2-39]]

^<<v44-2-39,39>>^ Porque a promessa é para vocês e para os vossos filhos, e para todos os que estão longe, todos os que Jeová,^&#42;1^ nosso Deus, chamar a si.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-2-40]]

^<<v44-2-40,40>>^ E ele dava um testemunho cabal e exortava-os com muitas outras palavras, dizendo: “Sejam salvos desta geração pervertida.”

[[v44-2-41]]

^<<v44-2-41,41>>^ Assim, os que aceitaram com alegria as suas palavras foram batizados, e naquele dia cerca de 3000 pessoas^&#42;1^ juntaram-se a eles.

[NOTE]
====
. Ou: “almas”.
====

[[v44-2-42]]

^<<v44-2-42,42>>^ Dedicavam-se assim aos ensinamentos dos apóstolos, à convivência^&#42;1^ uns com os outros, a tomar refeições juntos e às orações.

[NOTE]
====
. Ou: “a partilhar”.
====

[[v44-2-43]]

^<<v44-2-43,43>>^ Realmente, todos^&#42;1^ ficaram com medo, e começaram a ocorrer muitos milagres^&#42;2^ e sinais por meio dos apóstolos.

[NOTE]
====
. Ou: “todas as almas”.
. Ou: “portentos”.
====

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que se tornaram crentes estavam juntos e compartilhavam todas as coisas;

[[v44-2-45]]

^<<v44-2-45,45>>^ vendiam os seus bens e propriedades, e repartiam o valor recebido entre todos, de acordo com a necessidade de cada um.

[[v44-2-46]]

^<<v44-2-46,46>>^ Estavam constantemente no templo, dia após dia, unidos no mesmo propósito; tomavam as suas refeições nas casas uns dos outros e partilhavam o seu alimento com grande alegria e sinceridade de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ louvando a Deus e granjeando a simpatia de todo o povo. Ao mesmo tempo, Jeová^&#42;1^ continuava diariamente a acrescentar-lhes os que estavam a ser salvos.

[NOTE]
====
. Veja o Ap. A5.
====

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]