include::./index.adoc[]

[[v44-7-0]]
=== Atos, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-7-1]]

^<<v44-7-1,1>>^ No entanto, o sumo sacerdote perguntou: “Isto é verdade?”

[[v44-7-2]]

^<<v44-7-2,2>>^ Estêvão respondeu: “Homens, irmãos e pais, escutem! O Deus glorioso apareceu ao nosso antepassado Abraão enquanto ele estava na Mesopotâmia, antes de ir morar para Harã,

[[v44-7-3]]

^<<v44-7-3,3>>^ e disse-lhe: ‘Deixa a tua terra e os teus parentes e vai para a terra que te mostrarei.’

[[v44-7-4]]

^<<v44-7-4,4>>^ Ele saiu então da terra dos caldeus e foi morar para Harã. E de lá, depois da morte do pai dele, Deus fez com que ele se mudasse para esta terra em que vocês moram agora.

[[v44-7-5]]

^<<v44-7-5,5>>^ Contudo, não lhe deu qualquer herança nela, não, nem mesmo um espaço para pôr o pé; mas prometeu que lha daria como propriedade e, depois dele, à sua descendência,^&#42;1^ embora ele ainda não tivesse filhos.

[NOTE]
====
. Lit.: “semente”.
====

[[v44-7-6]]

^<<v44-7-6,6>>^ Além disso, Deus disse-lhe que os seus descendentes seriam estrangeiros^&#42;1^ numa terra que não era deles, e que o povo iria escravizá-los e afligi-los^&#42;2^ durante 400 anos.

[NOTE]
====
. Lit.: “a sua semente seria estrangeira”.
. Ou: “maltratá-los”.
====

[[v44-7-7]]

^<<v44-7-7,7>>^ ‘E eu julgarei a nação para a qual eles trabalharão como escravos’, disse Deus, ‘e, depois disso, hão de sair e prestar-me serviço sagrado neste lugar’.

[[v44-7-8]]

^<<v44-7-8,8>>^ “Deu-lhe também um pacto de circuncisão, e ele tornou-se pai de Isaque e circuncidou-o no oitavo dia, e Isaque tornou-se pai de^&#42;1^ Jacó, e Jacó dos 12 patriarcas.^&#42;2^

[NOTE]
====
. Ou, possivelmente: “Isaque fez o mesmo com”.
. Ou: “chefes de família”.
====

[[v44-7-9]]

^<<v44-7-9,9>>^ E os patriarcas ficaram com ciúmes de José e venderam-no aos egípcios. Mas Deus estava com ele

[[v44-7-10]]

^<<v44-7-10,10>>^ e livrou-o de todas as suas aflições, e concedeu-lhe favor e sabedoria diante do Faraó, rei do Egito. E este designou-o para governar o Egito e toda a sua casa.

[[v44-7-11]]

^<<v44-7-11,11>>^ Depois houve uma fome em todo o Egito e em Canaã, sim, uma grande aflição, e os nossos antepassados não encontravam nada para comer.

[[v44-7-12]]

^<<v44-7-12,12>>^ Porém, Jacó ouviu dizer que havia mantimentos^&#42;1^ no Egito e enviou para lá, pela primeira vez, os nossos antepassados.

[NOTE]
====
. Ou: “cereais”.
====

[[v44-7-13]]

^<<v44-7-13,13>>^ Na segunda vez, José contou aos seus irmãos quem ele era, e o Faraó conheceu a família de José.

[[v44-7-14]]

^<<v44-7-14,14>>^ Assim, José mandou que fossem buscar o seu pai Jacó e todos os seus parentes, um total de 75 pessoas.^&#42;1^

[NOTE]
====
. Ou: “almas”.
====

[[v44-7-15]]

^<<v44-7-15,15>>^ Então, Jacó desceu ao Egito e ali faleceu, assim como os nossos antepassados.

[[v44-7-16]]

^<<v44-7-16,16>>^ Eles foram levados para Siquém e colocados no túmulo que Abraão tinha comprado aos filhos de Hamor, em Siquém, por uma certa quantia em dinheiro de prata.

[[v44-7-17]]

^<<v44-7-17,17>>^ “À medida que se aproximava o tempo para se cumprir a promessa que Deus tinha feito a Abraão, o povo crescia e multiplicava-se no Egito.

[[v44-7-18]]

^<<v44-7-18,18>>^ Entretanto, surgiu outro rei no Egito, que não sabia nada sobre José.

[[v44-7-19]]

^<<v44-7-19,19>>^ Ele usou de astúcia contra a nossa raça e maltratou os nossos pais, obrigando-os a abandonar os seus bebés para que eles não sobrevivessem.

[[v44-7-20]]

^<<v44-7-20,20>>^ Naquela época, nasceu Moisés e ele era extremamente belo.^&#42;1^ Ele foi criado por três meses na casa do seu pai.

[NOTE]
====
. Ou: “divinamente belo; belo à vista de Deus”.
====

[[v44-7-21]]

^<<v44-7-21,21>>^ Mas, quando foi abandonado,^&#42;1^ a filha do Faraó recolheu-o e criou-o como seu próprio filho.

[NOTE]
====
. Ou: “exposto”.
====

[[v44-7-22]]

^<<v44-7-22,22>>^ Assim, Moisés foi instruído em toda a sabedoria dos egípcios. De facto, ele era poderoso em palavras e em ações.

[[v44-7-23]]

^<<v44-7-23,23>>^ “Então, quando completou 40 anos, decidiu^&#42;1^ visitar^&#42;2^ os seus irmãos, os israelitas.

[NOTE]
====
. Ou: “veio-lhe ao coração”.
. Ou: “inspecionar”.
====

[[v44-7-24]]

^<<v44-7-24,24>>^ Ao ver que um egípcio estava a tratar um deles de forma injusta, ele defendeu o oprimido e vingou-o, matando o egípcio.

[[v44-7-25]]

^<<v44-7-25,25>>^ Ele achava que os seus irmãos compreenderiam que Deus estava a dar-lhes salvação pela mão dele, mas eles não compreenderam isso.

[[v44-7-26]]

^<<v44-7-26,26>>^ No dia seguinte, dirigiu-se a eles quando estavam a lutar e tentou reconciliá-los, dizendo: ‘Homens, vocês são irmãos. Porque é que se estão a maltratar um ao outro?’

[[v44-7-27]]

^<<v44-7-27,27>>^ Todavia, aquele que estava a maltratar o seu próximo empurrou-o, dizendo: ‘Quem é que te designou líder e juiz sobre nós?

[[v44-7-28]]

^<<v44-7-28,28>>^ Será que me queres matar como ontem mataste o egípcio?’

[[v44-7-29]]

^<<v44-7-29,29>>^ Ao ouvir isto, Moisés fugiu e foi morar como estrangeiro na terra de Midiã, onde teve dois filhos.

[[v44-7-30]]

^<<v44-7-30,30>>^ “Depois de se passarem 40 anos, um anjo apareceu-lhe no deserto^&#42;1^ do monte Sinai, na chama de um espinheiro que ardia.

[NOTE]
====
. Veja o Glossário.
====

[[v44-7-31]]

^<<v44-7-31,31>>^ Ao ver aquilo, Moisés ficou maravilhado. Porém, quando se aproximou para observar melhor, ouviu a voz de Jeová:^&#42;1^

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-7-32]]

^<<v44-7-32,32>>^ ‘Eu sou o Deus dos teus antepassados, o Deus de Abraão, de Isaque e de Jacó.’ Moisés começou a tremer e não se atreveu a observar novamente.

[[v44-7-33]]

^<<v44-7-33,33>>^ Jeová^&#42;1^ disse-lhe: ‘Tira as sandálias dos pés, pois o lugar que estás a pisar é solo sagrado.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-7-34]]

^<<v44-7-34,34>>^ Certamente vi a opressão do meu povo, que está no Egito, ouvi o gemido deles e desci para libertá-los. Agora, vem: vou enviar-te ao Egito.’

[[v44-7-35]]

^<<v44-7-35,35>>^ Este mesmo Moisés, que eles rejeitaram, dizendo: ‘Quem é que te designou líder e juiz?’, é aquele a quem Deus enviou como líder e libertador por meio do anjo que lhe apareceu no espinheiro.

[[v44-7-36]]

^<<v44-7-36,36>>^ Este homem conduziu-os para fora, realizando sinais e milagres^&#42;1^ no Egito, no mar Vermelho e no deserto por 40 anos.

[NOTE]
====
. Ou: “portentos”.
====

[[v44-7-37]]

^<<v44-7-37,37>>^ “Este é o Moisés que disse aos filhos de Israel: ‘Deus escolherá para vocês, dentre os vossos irmãos, um profeta semelhante a mim.’

[[v44-7-38]]

^<<v44-7-38,38>>^ Ele é aquele que estava junto à congregação no deserto; ele estava com o anjo que falou com ele no monte Sinai e com os nossos antepassados. Ele recebeu proclamações sagradas, vivas, para nos transmitir.

[[v44-7-39]]

^<<v44-7-39,39>>^ Os nossos antepassados recusaram-se a obedecer-lhe, rejeitaram-no e, no coração, voltaram para o Egito,

[[v44-7-40]]

^<<v44-7-40,40>>^ dizendo a Arão: ‘Faz-nos deuses para irem à nossa frente, pois não sabemos o que aconteceu com este Moisés, que nos tirou da terra do Egito.’

[[v44-7-41]]

^<<v44-7-41,41>>^ Assim, naqueles dias, fizeram um bezerro e levaram um sacrifício ao ídolo, e começaram a alegrar-se com as obras das suas próprias mãos.

[[v44-7-42]]

^<<v44-7-42,42>>^ Portanto, Deus afastou-se deles e entregou-os para prestarem serviço sagrado ao exército do céu,^&#42;1^ assim como está escrito no livro dos Profetas: ‘Por acaso, foi a mim que vocês fizeram ofertas e sacrifícios por 40 anos no deserto, ó casa de Israel?

[NOTE]
====
. Refere-se a corpos celestes.
====

[[v44-7-43]]

^<<v44-7-43,43>>^ Não, vocês ergueram a tenda de Moloque e a estrela do deus Refã, as imagens que fizeram para adorar. Por isso, vou deportar-vos para além de Babilónia.’

[[v44-7-44]]

^<<v44-7-44,44>>^ “Os nossos antepassados tinham a tenda do Testemunho no deserto, conforme ordenou Aquele que falou com Moisés, dizendo-lhe que a fizesse segundo o modelo que tinha visto.

[[v44-7-45]]

^<<v44-7-45,45>>^ E os nossos antepassados receberam-na dos seus pais e trouxeram-na, com Josué, para a terra das nações que Deus expulsou da presença dos nossos antepassados. Ela permaneceu aqui até aos dias de David.

[[v44-7-46]]

^<<v44-7-46,46>>^ Este obteve favor diante de Deus e pediu para ter o privilégio de providenciar uma casa para o Deus de Jacó.

[[v44-7-47]]

^<<v44-7-47,47>>^ Mas foi Salomão quem lhe construiu uma casa.

[[v44-7-48]]

^<<v44-7-48,48>>^ Contudo, o Altíssimo não mora em casas feitas por mãos humanas, como diz o profeta:

[[v44-7-49]]

^<<v44-7-49,49>>^ ‘“O céu é o meu trono e a terra é o apoio para os meus pés. Que tipo de casa é que me construirão?”, diz Jeová.^&#42;1^ “Onde é que seria o meu lugar de descanso?

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-7-50]]

^<<v44-7-50,50>>^ Não foi a minha mão que fez todas estas coisas?”’

[[v44-7-51]]

^<<v44-7-51,51>>^ “Homens obstinados e incircuncisos no coração e nos ouvidos, vocês resistem sempre ao espírito santo. Assim como fizeram os vossos antepassados, vocês também fazem.

[[v44-7-52]]

^<<v44-7-52,52>>^ A qual dos profetas é que os vossos antepassados não perseguiram? Sim, mataram os que anunciaram antecipadamente a vinda do Justo, dos quais vocês se tornaram agora traidores e assassinos,

[[v44-7-53]]

^<<v44-7-53,53>>^ vocês, que receberam a Lei conforme transmitida por anjos, mas não a guardaram.”

[[v44-7-54]]

^<<v44-7-54,54>>^ Quando ouviram estas coisas, ficaram furiosos^&#42;1^ no coração e começaram a ranger os dentes contra ele.

[NOTE]
====
. Ou: “sentiram-se feridos”.
====

[[v44-7-55]]

^<<v44-7-55,55>>^ Ele, porém, cheio de espírito santo, olhou fixamente para o céu e viu a glória de Deus, e Jesus de pé à direita de Deus,

[[v44-7-56]]

^<<v44-7-56,56>>^ e disse: “Estou a ver o céu aberto, e o Filho do homem de pé à direita de Deus.”

[[v44-7-57]]

^<<v44-7-57,57>>^ Então, eles clamaram ao máximo da sua voz e puseram as mãos nos ouvidos, e avançaram todos juntos contra ele.

[[v44-7-58]]

^<<v44-7-58,58>>^ Depois de expulsá-lo da cidade, começaram a apedrejá-lo. As testemunhas deixaram as suas capas aos pés de um jovem chamado Saulo.

[[v44-7-59]]

^<<v44-7-59,59>>^ Enquanto apedrejavam Estêvão, este fez o apelo: “Senhor Jesus, recebe o meu espírito.”

[[v44-7-60]]

^<<v44-7-60,60>>^ Depois, ajoelhando-se, clamou com voz forte: “Jeová,^&#42;1^ não os condenes por este pecado.” E, dizendo isto, adormeceu na morte.

[NOTE]
====
. Veja o Ap. A5.
====

'''

xref:044-atos/044-atos-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-atos/044-atos-008.adoc#v44-8-0[Próximo Capítulo &#62;]