include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-8-1]]

^<<v44-8-1,1>>^ Saulo, por sua vez, aprovava o assassinato dele.
Naquele dia, começou uma grande perseguição contra a congregação em Jerusalém, e todos, exceto os apóstolos, foram espalhados pelas regiões da Judeia e Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ Homens devotos levaram Estêvão para o enterrarem e fizeram grandes lamentações por ele.

[[v44-8-3]]

^<<v44-8-3,3>>^ Todavia, Saulo começou a devastar a congregação. Invadia uma casa após outra, arrastando para fora tanto homens como mulheres e mandando-os para a prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ No entanto, os que tinham sido dispersos declaravam as boas novas da palavra pela região.

[[v44-8-5]]

^<<v44-8-5,5>>^ Filipe desceu à cidade^&#42;1^ de Samaria e começou a pregar-lhes sobre o Cristo.

[NOTE]
====
. Ou, possivelmente: “a uma cidade”.
====

[[v44-8-6]]

^<<v44-8-6,6>>^ As multidões, unanimemente, prestavam atenção ao que Filipe dizia; escutavam-no e viam os sinais que ele realizava.

[[v44-8-7]]

^<<v44-8-7,7>>^ Pois muitos tinham espíritos impuros, e estes gritavam e saíam deles. Além disso, muitos paralíticos e coxos foram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ Por conseguinte, houve muita alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ E na cidade havia um homem chamado Simão que, anteriormente, tinha praticado artes mágicas. Ele tinha deixado a nação de Samaria admirada, por afirmar que era alguém grande.

[[v44-8-10]]

^<<v44-8-10,10>>^ Todos lhe davam atenção, desde o menor até ao maior, e diziam: “Este homem é o Poder de Deus, o chamado Grande Poder.”

[[v44-8-11]]

^<<v44-8-11,11>>^ Davam-lhe atenção porque os tinha impressionado durante muito tempo com as suas artes mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Apesar disso, acreditaram em Filipe quando lhes declarou as boas novas a respeito do Reino de Deus e do nome de Jesus Cristo, e tanto homens como mulheres foram batizados.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão também se tornou crente e, depois de ser batizado, continuou com Filipe. E ele admirava-se ao ver sinais e grandes obras poderosas.

[[v44-8-14]]

^<<v44-8-14,14>>^ Quando os apóstolos em Jerusalém ouviram dizer que Samaria tinha aceitado a palavra de Deus, enviaram-lhes Pedro e João,

[[v44-8-15]]

^<<v44-8-15,15>>^ e estes desceram e oraram para que os samaritanos recebessem espírito santo.

[[v44-8-16]]

^<<v44-8-16,16>>^ Pois o espírito santo ainda não viera sobre nenhum deles, mas eles só tinham sido batizados em nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Então, impuseram-lhes as mãos e eles começaram a receber espírito santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Quando Simão viu que o espírito era dado pela imposição das mãos dos apóstolos, ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: “Deem-me esta autoridade também a mim, para que todo aquele sobre quem eu impuser as mãos receba espírito santo.”

[[v44-8-20]]

^<<v44-8-20,20>>^ No entanto, Pedro disse-lhe: “Que a tua prata pereça contigo, porque pensaste que poderias obter o dom^&#42;1^ de Deus com dinheiro.

[NOTE]
====
. Ou: “a dádiva gratuita”.
====

[[v44-8-21]]

^<<v44-8-21,21>>^ Não podes ter nenhuma participação nisso, porque o teu coração não é justo à vista de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Portanto, arrepende-te dessa tua maldade e suplica a Jeová^&#42;1^ que, se possível, a má intenção do teu coração te seja perdoada,

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-8-23]]

^<<v44-8-23,23>>^ pois vejo que és um veneno amargo^&#42;1^ e um escravo da injustiça.”

[NOTE]
====
. Lit.: “fel de amargura”.
====

[[v44-8-24]]

^<<v44-8-24,24>>^ Simão respondeu-lhes: “Façam súplicas a Jeová^&#42;1^ por mim, para que nenhuma destas coisas que disseram me sobrevenha.”

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-8-25]]

^<<v44-8-25,25>>^ Portanto, depois de darem testemunho de forma cabal e falarem da palavra de Jeová,^&#42;1^ regressaram a Jerusalém, declarando as boas novas a muitas aldeias dos samaritanos.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-8-26]]

^<<v44-8-26,26>>^ No entanto, o anjo de Jeová^&#42;1^ disse a Filipe: “Prepara-te e vai para o sul, para a estrada que desce de Jerusalém até Gaza.” (Esta é a estrada do deserto.)

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-8-27]]

^<<v44-8-27,27>>^ Em vista disso, ele preparou-se e partiu. Encontrou então um eunuco^&#42;1^ etíope, alto funcionário de Candace, rainha dos etíopes, encarregado de todo o tesouro dela. Ele tinha ido a Jerusalém para adorar

[NOTE]
====
. Ou: “oficial da corte”.
====

[[v44-8-28]]

^<<v44-8-28,28>>^ e, enquanto regressava, sentado no seu carro, lia em voz alta o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ Por conseguinte, o espírito disse a Filipe: “Vai, aproxima-te desse carro.”

[[v44-8-30]]

^<<v44-8-30,30>>^ Filipe correu ao lado do carro e ouviu o eunuco a ler o profeta Isaías em voz alta. Perguntou então: “Entende o que está a ler?”

[[v44-8-31]]

^<<v44-8-31,31>>^ Ele respondeu: “Na verdade, como é que posso entender a menos que alguém me oriente?” E pediu que Filipe subisse e se sentasse com ele.

[[v44-8-32]]

^<<v44-8-32,32>>^ A passagem das Escrituras que ele estava a ler em voz alta era: “Como uma ovelha, ele foi levado para o abate e, como um cordeiro que fica em silêncio diante do seu tosquiador, ele não abre a boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Durante a sua humilhação, negaram-lhe a justiça. Quem é que contará os pormenores da sua geração?^&#42;1^ Porque a sua vida é eliminada da terra.”

[NOTE]
====
. Ou: “origem”.
====

[[v44-8-34]]

^<<v44-8-34,34>>^ O eunuco disse então a Filipe: “Por favor, diz-me: De quem é que o profeta está a falar? De si mesmo ou de outro homem?”

[[v44-8-35]]

^<<v44-8-35,35>>^ Filipe começou a falar e, principiando com aquela passagem das Escrituras, declarou-lhe as boas novas a respeito de Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Ao seguirem pela estrada, chegaram a um lugar onde havia água, e o eunuco disse: “Olha! Há aqui água! O que é que me impede de ser batizado?”

[[v44-8-37]]

^<<v44-8-37,37>>^ ^&#42;1^——

[NOTE]
====
. Veja o Ap. A3.
====

[[v44-8-38]]

^<<v44-8-38,38>>^ Assim, mandou parar o carro, e tanto Filipe como o eunuco desceram até à água; e ele batizou-o.

[[v44-8-39]]

^<<v44-8-39,39>>^ Depois de saírem da água, o espírito de Jeová^&#42;1^ rapidamente levou dali Filipe, e o eunuco não voltou a vê-lo, mas seguiu o seu caminho cheio de alegria.

[NOTE]
====
. Veja o Ap. A5.
====

[[v44-8-40]]

^<<v44-8-40,40>>^ Filipe, no entanto, foi parar a Asdode e, ao passar por aquela região, continuou a declarar as boas novas a todas as cidades, até chegar a Cesareia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]