include::./index.adoc[]

[[v14-29-0]]
=== 2 Crónicas, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-29-1]]

^<<v14-29-1,1>>^ Ezequias tornou-se rei aos 25 anos de idade, e reinou durante 29 anos em Jerusalém. O nome da sua mãe era Abias, filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ Ele fazia o que era certo aos olhos de Jeová, assim como David, seu antepassado, tinha feito.

[[v14-29-3]]

^<<v14-29-3,3>>^ No primeiro ano do seu reinado, no primeiro mês, ele abriu as portas da casa de Jeová e consertou-as.

[[v14-29-4]]

^<<v14-29-4,4>>^ Então, ele convocou os sacerdotes e os levitas e reuniu-os na praça, a leste.

[[v14-29-5]]

^<<v14-29-5,5>>^ Disse-lhes: “Escutem-me, levitas. Agora, santifiquem-se a vocês mesmos e santifiquem a casa de Jeová, o Deus dos vossos antepassados, e retirem do lugar santo o que é impuro.

[[v14-29-6]]

^<<v14-29-6,6>>^ Pois os nossos pais foram infiéis e fizeram o que era mau aos olhos de Jeová, nosso Deus. Eles abandonaram-no, desviaram o rosto do tabernáculo de Jeová e voltaram-Lhe as costas.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam as portas do pórtico e apagaram as lâmpadas. Pararam de queimar incenso e de oferecer sacrifícios queimados ao Deus de Israel no lugar santo.

[[v14-29-8]]

^<<v14-29-8,8>>^ Por isso, Jeová ficou indignado com Judá e Jerusalém, de modo que os tornou um motivo de terror, objeto de espanto e alvo de assobios,^&#42;1^ como podem ver com os vossos próprios olhos.

[NOTE]
====
. Ou: “motivo de gozo”.
====

[[v14-29-9]]

^<<v14-29-9,9>>^ Assim, os nossos antepassados caíram pela espada, e os nossos filhos, as nossas filhas e as nossas esposas foram para o cativeiro por causa disso.

[[v14-29-10]]

^<<v14-29-10,10>>^ Agora, o meu desejo de coração é fazer um pacto com Jeová, o Deus de Israel, para que a sua ira ardente se afaste de nós.

[[v14-29-11]]

^<<v14-29-11,11>>^ Meus filhos, agora não é altura de serem negligentes,^&#42;1^ pois Jeová escolheu-vos para ficarem de pé perante ele, para o servirem e para queimarem os seus sacrifícios.”

[NOTE]
====
. Ou: “de descansarem”.
====

[[v14-29-12]]

^<<v14-29-12,12>>^ Então, os seguintes levitas começaram a trabalhar: dos coatitas: Maate, filho de Amasai, e Joel, filho de Azarias; dos meraritas: Quis, filho de Abdi, e Azarias, filho de Jealelel; dos gersonitas: Joá, filho de Zima, e Éden, filho de Joá;

[[v14-29-13]]

^<<v14-29-13,13>>^ dos filhos de Elizafã: Sinri e Jeuel; dos filhos de Asafe: Zacarias e Matanias;

[[v14-29-14]]

^<<v14-29-14,14>>^ dos filhos de Hemã: Jeiel e Simei; e dos filhos de Jedutum: Semaías e Uziel.

[[v14-29-15]]

^<<v14-29-15,15>>^ Reuniram os seus irmãos, santificaram-se e foram purificar a casa de Jeová, conforme o rei tinha ordenado, de acordo com as palavras de Jeová.

[[v14-29-16]]

^<<v14-29-16,16>>^ Em seguida, os sacerdotes entraram na casa de Jeová para fazer a purificação e tiraram todas as coisas impuras que encontraram no templo de Jeová e levaram-nas para o pátio da casa de Jeová. Os levitas, por sua vez, pegaram-lhes e levaram-nas para fora, para o vale do Cédron.

[[v14-29-17]]

^<<v14-29-17,17>>^ Assim, começaram a santificação no primeiro dia do primeiro mês e chegaram ao pórtico de Jeová no dia oito do mês. Santificaram a casa de Jeová durante oito dias e acabaram no dia 16 do primeiro mês.

[[v14-29-18]]

^<<v14-29-18,18>>^ Depois, compareceram perante o rei Ezequias e disseram: “Purificámos toda a casa de Jeová, o altar da oferta queimada e todos os seus utensílios, e a mesa dos pães da proposição^&#42;1^ e todos os seus utensílios.

[NOTE]
====
. Ou: “pães dispostos em pilhas”.
====

[[v14-29-19]]

^<<v14-29-19,19>>^ E preparámos e santificámos todos os utensílios que o rei Acaz removeu durante o seu reinado, quando agiu de modo infiel, e estão diante do altar de Jeová.”

[[v14-29-20]]

^<<v14-29-20,20>>^ E o rei Ezequias levantou-se cedo e reuniu os príncipes da cidade, e eles subiram à casa de Jeová.

[[v14-29-21]]

^<<v14-29-21,21>>^ Trouxeram sete novilhos, sete carneiros, sete cordeiros e sete bodes como oferta pelo pecado, em benefício do reino, do santuário e de Judá. Portanto, ele disse aos sacerdotes, os descendentes de Arão, que os oferecessem no altar de Jeová.

[[v14-29-22]]

^<<v14-29-22,22>>^ Assim, abateram os novilhos, e os sacerdotes pegaram no sangue e aspergiram-no no altar. Depois, abateram os carneiros e aspergiram o sangue no altar; e abateram os cordeiros e aspergiram o sangue no altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ A seguir, trouxeram os bodes da oferta pelo pecado perante o rei e a congregação, e puseram as mãos sobre eles.

[[v14-29-24]]

^<<v14-29-24,24>>^ Os sacerdotes abateram-nos e com o sangue deles fizeram no altar uma oferta pelo pecado, para fazer expiação por todo o Israel, porque o rei tinha dito que a oferta queimada e a oferta pelo pecado deviam ser feitas em benefício de todo o Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ Entretanto, ele tinha colocado os levitas nas suas posições na casa de Jeová, com címbalos, instrumentos de cordas e harpas, de acordo com as ordens de David, de Gade, o vidente^&#42;1^ do rei, e de Natã, o profeta, pois estas ordens tinham sido dadas por Jeová por meio dos seus profetas.

[NOTE]
====
. Veja o Glossário.
====

[[v14-29-26]]

^<<v14-29-26,26>>^ Assim, os levitas estavam de pé com os instrumentos de David, e os sacerdotes com as trombetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ Em seguida, Ezequias ordenou que se oferecesse o sacrifício queimado no altar. Quando se iniciou a oferta queimada, começou o cântico de Jeová e o som das trombetas, a acompanhar os instrumentos de David, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ E toda a congregação se curvava enquanto se cantava o cântico e as trombetas ressoavam — isto continuou até acabar a oferta queimada.

[[v14-29-29]]

^<<v14-29-29,29>>^ E, assim que acabaram de fazer a oferta, o rei e todos os que estavam com ele curvaram-se e prostraram-se.

[[v14-29-30]]

^<<v14-29-30,30>>^ O rei Ezequias e os príncipes ordenaram aos levitas que louvassem a Jeová com as palavras de David e de Asafe, o vidente.^&#42;1^ Por conseguinte, ofereceram louvor com grande alegria, e curvaram-se e prostraram-se.

[NOTE]
====
. Veja o Glossário.
====

[[v14-29-31]]

^<<v14-29-31,31>>^ Depois, Ezequias disse: “Agora que foram separados^&#42;1^ para o serviço de Jeová, venham e tragam sacrifícios e ofertas de agradecimento à casa de Jeová.” Consequentemente, a congregação começou a trazer sacrifícios e ofertas de agradecimento, e todos os de coração disposto trouxeram ofertas queimadas.

[NOTE]
====
. Lit.: “Agora encheram a vossa mão”.
====

[[v14-29-32]]

^<<v14-29-32,32>>^ O número das ofertas queimadas trazidas pela congregação foi de 70 bois, 100 carneiros e 200 cordeiros — todos oferecidos como oferta queimada a Jeová —

[[v14-29-33]]

^<<v14-29-33,33>>^ e o das ofertas sagradas foi de 600 bois e 3000 ovelhas.

[[v14-29-34]]

^<<v14-29-34,34>>^ Contudo, não havia sacerdotes suficientes para tirar a pele de todos os animais das ofertas queimadas. Por isso, os seus irmãos, os levitas, ajudaram-nos até acabarem o serviço e até os sacerdotes se santificarem, pois os levitas foram mais conscienciosos^&#42;1^ em se santificar do que os sacerdotes.

[NOTE]
====
. Lit.: “retos de coração”.
====

[[v14-29-35]]

^<<v14-29-35,35>>^ Também, havia muitas ofertas queimadas, além da gordura dos sacrifícios de participação em comum e das ofertas de bebida que acompanhavam as ofertas queimadas. Assim, o serviço da casa de Jeová foi restaurado.^&#42;1^

[NOTE]
====
. Ou: “preparado”.
====

[[v14-29-36]]

^<<v14-29-36,36>>^ E Ezequias e todo o povo se alegraram por causa do que o verdadeiro Deus tinha feito para o povo, pois tudo isto tinha acontecido muito de repente.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]