include::./index.adoc[]

[[v14-25-0]]
=== 2 Crónicas, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-25-1]]

^<<v14-25-1,1>>^ Amazias tinha 25 anos de idade quando se tornou rei, e reinou durante 29 anos em Jerusalém. O nome da sua mãe era Jeoadã, de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Ele fazia o que era certo aos olhos de Jeová, mas não de pleno coração.

[[v14-25-3]]

^<<v14-25-3,3>>^ Assim que obteve firme controlo do reino, matou os seus servos que tinham matado o rei, seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ Contudo, não matou os filhos deles, pois agiu conforme está escrito na Lei, no livro de Moisés, onde Jeová ordenou: “Os pais não devem morrer por causa dos filhos, e os filhos não devem morrer por causa dos pais; cada um deve morrer por causa do seu próprio pecado.”

[[v14-25-5]]

^<<v14-25-5,5>>^ E Amazias reuniu os homens de Judá e organizou-os segundo as suas casas paternas, de acordo com os chefes de mil e os chefes de cem, para todo o Judá e Benjamim. Registou os de 20 anos de idade para cima e descobriu que havia 300 000 guerreiros treinados^&#42;1^ para servir no exército, capazes de usar a lança e o escudo grande.

[NOTE]
====
. Lit.: “escolhidos”.
====

[[v14-25-6]]

^<<v14-25-6,6>>^ Além disso, contratou de Israel 100 000 guerreiros valentes por 100 talentos^&#42;1^ de prata.

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v14-25-7]]

^<<v14-25-7,7>>^ Todavia, um homem do verdadeiro Deus veio ter com ele e disse: “Ó rei, não deixe o exército de Israel ir consigo, pois Jeová não está com Israel, não está com nenhum dos efraimitas.

[[v14-25-8]]

^<<v14-25-8,8>>^ Vá apenas o senhor; aja e seja corajoso na batalha. Senão, o verdadeiro Deus poderá fazê-lo tropeçar diante de um inimigo, pois Deus tem poder para ajudar e para fazer tropeçar.”

[[v14-25-9]]

^<<v14-25-9,9>>^ Em vista disso, Amazias disse ao homem do verdadeiro Deus: “Mas, e os 100 talentos que dei às tropas de Israel?” O homem do verdadeiro Deus respondeu: “Jeová pode dar-lhe muito mais do que isso.”

[[v14-25-10]]

^<<v14-25-10,10>>^ Portanto, Amazias dispensou as tropas que tinham vindo ter com ele de Efraim, mandando-as de volta para a terra deles. No entanto, eles ficaram muito irritados com Judá e voltaram para a sua terra furiosos.

[[v14-25-11]]

^<<v14-25-11,11>>^ A seguir, Amazias encheu-se de coragem, conduziu o seu próprio exército ao vale do Sal e matou 10 000 homens de Seir.

[[v14-25-12]]

^<<v14-25-12,12>>^ E os homens de Judá capturaram vivos 10 000. Portanto, levaram-nos ao alto do rochedo e atiraram-nos dali a baixo; e todos eles se despedaçaram.

[[v14-25-13]]

^<<v14-25-13,13>>^ Porém, os membros da tropa que Amazias tinha dispensado de irem com ele à guerra atacaram as cidades de Judá, desde Samaria até Bete-Horom; mataram 3000 pessoas e levaram muito despojo.

[[v14-25-14]]

^<<v14-25-14,14>>^ No entanto, quando Amazias voltou, depois de matar os edomitas, trouxe os deuses dos homens de Seir, estabeleceu-os para si como deuses e começou a curvar-se diante deles e a fazer-lhes fumo sacrificial.

[[v14-25-15]]

^<<v14-25-15,15>>^ Por isso, Jeová ficou muito furioso com Amazias e enviou um profeta, que lhe disse: “Porque é que está a seguir os deuses deste povo, que não salvaram o povo deles das suas mãos?”

[[v14-25-16]]

^<<v14-25-16,16>>^ Enquanto falava, o rei disse-lhe: “Por acaso designámos-te como conselheiro do rei? Para de falar! Queres morrer?” Então, o profeta parou, mas acrescentou: “Sei que Deus resolveu destruí-lo por ter feito isto e por não ter escutado o meu conselho.”

[[v14-25-17]]

^<<v14-25-17,17>>^ Depois de consultar os seus conselheiros, Amazias, rei de Judá, enviou a seguinte mensagem a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel: “Vem, enfrentemo-nos numa batalha.”^&#42;1^

[NOTE]
====
. Ou: “encontremo-nos face a face”.
====

[[v14-25-18]]

^<<v14-25-18,18>>^ Jeoás, rei de Israel, mandou dizer a Amazias, rei de Judá: “Um espinheiro no Líbano mandou dizer ao cedro do Líbano: ‘Dá a tua filha ao meu filho como esposa.’ Mas um animal selvagem do Líbano passou por onde estava o espinheiro e pisou-o.

[[v14-25-19]]

^<<v14-25-19,19>>^ Tu disseste: ‘Eu golpeei^&#42;1^ Edom.’ Por isso, o teu coração ficou arrogante e quer receber glória. Mas fica na tua casa.^&#42;2^ Porquê provocar uma desgraça e cair, arrastando Judá contigo?”

[NOTE]
====
. Lit.: “Tu golpeaste”.
. Ou: “no teu palácio”.
====

[[v14-25-20]]

^<<v14-25-20,20>>^ Contudo, Amazias não escutou, pois isso era da vontade do verdadeiro Deus. Ele queria entregá-los nas mãos do inimigo por terem seguido os deuses de Edom.

[[v14-25-21]]

^<<v14-25-21,21>>^ Assim, Jeoás, rei de Israel, pôs-se a caminho; e ele e Amazias, rei de Judá, enfrentaram-se numa batalha em Bete-Semes, uma cidade de Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ Judá foi derrotado por Israel, e cada um fugiu para a sua casa.^&#42;1^

[NOTE]
====
. Lit.: “as suas tendas”.
====

[[v14-25-23]]

^<<v14-25-23,23>>^ Jeoás, rei de Israel, capturou Amazias, rei de Judá, filho de Jeoás, filho de Jeoacaz,^&#42;1^ em Bete-Semes. Depois, levou-o para Jerusalém, e fez uma brecha de 400 côvados^&#42;2^ na muralha de Jerusalém, do Portão de Efraim até ao Portão da Esquina.

[NOTE]
====
. Também chamado Acazias.
. Cerca de 178 m. Veja o Ap. B14.
====

[[v14-25-24]]

^<<v14-25-24,24>>^ Tirou todo o ouro, a prata e todos os objetos que havia na casa do verdadeiro Deus, com^&#42;1^ Obede-Edom, e no tesouro da casa^&#42;2^ do rei, além de capturar reféns. Depois, voltou para Samaria.

[NOTE]
====
. Ou: “aos cuidados de”.
. Ou: “do palácio”.
====

[[v14-25-25]]

^<<v14-25-25,25>>^ Amazias, filho de Jeoás, rei de Judá, ainda viveu 15 anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ Quanto aos outros acontecimentos da história de Amazias, do início ao fim, não estão escritos no Livro dos Reis de Judá e de Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ A partir do momento em que Amazias deixou de seguir a Jeová, conspiraram contra ele em Jerusalém e ele fugiu para Laquis, mas mandaram homens atrás dele até Laquis e mataram-no ali.

[[v14-25-28]]

^<<v14-25-28,28>>^ Então, o seu corpo foi trazido de volta em cima de cavalos e enterraram-no com os seus antepassados na cidade de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]