include::./index.adoc[]

[[v14-35-0]]
=== 2 Crónicas, 35
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-35-1]]

^<<v14-35-1,1>>^ Josias celebrou uma Páscoa para Jeová em Jerusalém, e o sacrifício pascoal foi abatido no dia 14 do primeiro mês.

[[v14-35-2]]

^<<v14-35-2,2>>^ Restabeleceu os sacerdotes nos seus deveres e encorajou-os a realizar o seu serviço na casa de Jeová.

[[v14-35-3]]

^<<v14-35-3,3>>^ Então, disse aos levitas, os instrutores de todo o Israel, os que eram santos para Jeová: “Ponham a Arca sagrada na casa construída por Salomão, filho de David, rei de Israel; já não a devem carregar aos ombros. Agora, sirvam a Jeová, vosso Deus, e o seu povo, Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ E preparem-se para o serviço, de acordo com as vossas casas paternas e as vossas turmas, conforme o que foi escrito por David, rei de Israel, e por Salomão, seu filho.

[[v14-35-5]]

^<<v14-35-5,5>>^ Posicionem-se no lugar santo agrupados de acordo com as casas paternas do povo,^&#42;1^ os vossos irmãos; para cada uma delas deve haver um grupo da casa paterna dos levitas.

[NOTE]
====
. Lit.: “dos filhos do povo”.
====

[[v14-35-6]]

^<<v14-35-6,6>>^ Abatam o sacrifício pascoal, santifiquem-se e façam os preparativos para os vossos irmãos, a fim de cumprirem a palavra de Jeová dada por meio de Moisés.”

[[v14-35-7]]

^<<v14-35-7,7>>^ Josias contribuiu com um total de 30 000 cordeiros e cabritos do rebanho, além de 3000 bois como sacrifícios pascoais para todo o povo que estava presente. Isto foi tirado dos próprios bens do rei.

[[v14-35-8]]

^<<v14-35-8,8>>^ Os seus príncipes também fizeram uma contribuição como oferta voluntária para o povo, os sacerdotes e os levitas. Hilquias, Zacarias e Jeiel, os líderes da casa do verdadeiro Deus, deram aos sacerdotes 2600 sacrifícios pascoais e 300 bois.

[[v14-35-9]]

^<<v14-35-9,9>>^ Conanias e os seus irmãos Semaías e Netanel, assim como Hasabias, Jeiel e Jozabade, os chefes dos levitas, contribuíram para os levitas com 5000 sacrifícios pascoais e 500 bois.

[[v14-35-10]]

^<<v14-35-10,10>>^ O serviço foi preparado, e os sacerdotes posicionaram-se, e os levitas também, segundo as suas turmas, como o rei tinha ordenado.

[[v14-35-11]]

^<<v14-35-11,11>>^ Abateram os sacrifícios pascoais, e os sacerdotes aspergiram o sangue que receberam dos levitas, enquanto estes tiravam a pele dos animais.

[[v14-35-12]]

^<<v14-35-12,12>>^ A seguir, prepararam as ofertas queimadas para as distribuir ao povo, que estava agrupado de acordo com as casas paternas, para que as ofertas fossem apresentadas a Jeová conforme está escrito no livro de Moisés; e fizeram o mesmo com os bois.

[[v14-35-13]]

^<<v14-35-13,13>>^ Cozinharam^&#42;1^ a oferta pascoal sobre o fogo, segundo o costume; e cozinharam as ofertas sagradas em tachos, caldeirões e panelas, depois levaram-nas depressa ao povo.

[NOTE]
====
. Ou, possivelmente: “Assaram”.
====

[[v14-35-14]]

^<<v14-35-14,14>>^ Em seguida, os levitas prepararam a refeição pascoal para si mesmos e para os sacerdotes, porque os sacerdotes, os descendentes de Arão, ficaram a oferecer os sacrifícios queimados e a gordura até ao anoitecer. Assim, os levitas prepararam a refeição pascoal para si mesmos e para os sacerdotes, os descendentes de Arão.

[[v14-35-15]]

^<<v14-35-15,15>>^ Os cantores, os filhos de Asafe, estavam nas suas posições conforme as ordens de David, de Asafe, de Hemã e de Jedutum, vidente^&#42;1^ do rei; e os porteiros estavam nos diversos portões. Não havia necessidade de deixarem o seu serviço, porque os seus irmãos, os levitas, lhes tinham preparado a refeição pascoal.

[NOTE]
====
. Veja o Glossário.
====

[[v14-35-16]]

^<<v14-35-16,16>>^ Portanto, naquele dia, acabaram de preparar tudo o que Jeová lhes ordenou, para se celebrar a Páscoa e para se fazer as ofertas queimadas no altar de Jeová, segundo a ordem do rei Josias.

[[v14-35-17]]

^<<v14-35-17,17>>^ Os israelitas que estavam presentes celebraram a Páscoa naquela ocasião, e a Festividade dos Pães sem Fermento durante sete dias.

[[v14-35-18]]

^<<v14-35-18,18>>^ Desde os dias do profeta Samuel, nunca se tinha celebrado uma Páscoa igual a esta em Israel, e nenhum outro rei de Israel celebrou uma Páscoa igual à celebrada por Josias, pelos sacerdotes, pelos levitas, por todos os de Judá e de Israel que estavam presentes, e pelos habitantes de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ Esta Páscoa foi celebrada no décimo oitavo ano do reinado de Josias.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois de tudo isto, quando Josias tinha restaurado o templo,^&#42;1^ Neco, rei do Egito, foi lutar em Carquemis, junto ao Eufrates. Então, Josias saiu para lutar contra ele.

[NOTE]
====
. Lit.: “a casa”.
====

[[v14-35-21]]

^<<v14-35-21,21>>^ Por isso, ele enviou-lhe mensageiros para dizer: “O que é que tens a ver com isto, rei de Judá? Não venho lutar contra ti hoje, mas a minha luta é contra outro reino,^&#42;1^ e Deus diz que eu me devo apressar. Para o teu próprio bem, para de te opor a Deus, que está comigo, senão ele irá causar-te ruína.”

[NOTE]
====
. Ou: “outra casa”.
====

[[v14-35-22]]

^<<v14-35-22,22>>^ Josias, porém, não desistiu de o enfrentar e disfarçou-se para lutar contra ele; não quis escutar as palavras de Neco, que vinham da boca de Deus. Consequentemente, foi lutar na planície de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ E os arqueiros atingiram o rei Josias e o rei disse aos seus servos: “Tirem-me daqui, pois fui gravemente ferido.”

[[v14-35-24]]

^<<v14-35-24,24>>^ Portanto, os seus servos tiraram-no do carro de guerra e colocaram-no no seu segundo carro, e levaram-no para Jerusalém. Assim, ele morreu e foi enterrado no túmulo dos seus antepassados, e todo o Judá e Jerusalém choraram por Josias.

[[v14-35-25]]

^<<v14-35-25,25>>^ E Jeremias cantou um cântico fúnebre por Josias, e todos os cantores e cantoras cantam sobre Josias nas suas lamentações, até ao dia de hoje; cantá-las tornou-se um costume^&#42;1^ em Israel, e elas estão escritas entre as lamentações.

[NOTE]
====
. Ou: “decreto”.
====

[[v14-35-26]]

^<<v14-35-26,26>>^ Os outros acontecimentos da história de Josias, os seus atos de amor leal, em obediência ao que está escrito na Lei de Jeová,

[[v14-35-27]]

^<<v14-35-27,27>>^ e o que ele fez, do começo ao fim, estão escritos no Livro dos Reis de Israel e de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]