include::./index.adoc[]

[[v14-26-0]]
=== 2 Crónicas, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-26-1]]

^<<v14-26-1,1>>^ Todo o povo de Judá tomou então Uzias, que tinha 16 anos de idade, e fizeram-no rei no lugar do seu pai, Amazias.

[[v14-26-2]]

^<<v14-26-2,2>>^ Ele reconstruiu Elote e restituiu-a a Judá depois de o rei^&#42;1^ ter descansado com os seus antepassados.

[NOTE]
====
. Isto é, o seu pai, Amazias.
====

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias tinha 16 anos de idade quando se tornou rei, e reinou durante 52 anos em Jerusalém. O nome da sua mãe era Jecolia, de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Ele fazia o que era certo aos olhos de Jeová, assim como Amazias, seu pai, tinha feito.

[[v14-26-5]]

^<<v14-26-5,5>>^ Procurava a Deus nos dias de Zacarias, que o ensinou a temer o verdadeiro Deus. Enquanto procurava a Jeová, o verdadeiro Deus fazia-o prosperar.

[[v14-26-6]]

^<<v14-26-6,6>>^ Ele saiu para lutar contra os filisteus e abriu uma brecha na muralha de Gate, na muralha de Jabné e na muralha de Asdode. Então, construiu cidades no território de Asdode e no território dos filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ O verdadeiro Deus continuou a ajudá-lo nas guerras contra os filisteus, contra os árabes que moravam em Gurbaal e contra os meunins.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os amonitas começaram a pagar tributo a Uzias. Por fim, a sua fama chegou até ao Egito, pois ele tornou-se extremamente poderoso.

[[v14-26-9]]

^<<v14-26-9,9>>^ Além disso, Uzias construiu torres em Jerusalém, ao pé do Portão da Esquina, do Portão do Vale e do Contraforte, e reforçou-as.

[[v14-26-10]]

^<<v14-26-10,10>>^ Também construiu torres no deserto e cavou^&#42;1^ muitas cisternas (pois tinha muitos animais); fez o mesmo na Sefelá e na planície.^&#42;2^ Nos montes e no Carmelo, ele tinha lavradores e homens que trabalhavam nos vinhedos, pois amava a agricultura.

[NOTE]
====
. Provavelmente na rocha.
. Ou: “na achada”.
====

[[v14-26-11]]

^<<v14-26-11,11>>^ Uzias também veio a ter um exército preparado para a guerra. Saíam em campanhas militares, organizados em divisões. Foram contados e registados por Jeiel, o secretário, e por Maaseias, o oficial, sob o comando de Hananias, um dos príncipes do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O número total dos cabeças das casas paternas que comandavam estes guerreiros valentes era de 2600.

[[v14-26-13]]

^<<v14-26-13,13>>^ As forças armadas sob o seu comando eram de 307 500 homens prontos para a guerra, uma poderosa força militar para apoiar o rei contra o inimigo.

[[v14-26-14]]

^<<v14-26-14,14>>^ Uzias equipou todo o exército com escudos, lanças, capacetes, cotas de malha, arcos e fundas para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Além disso, fez em Jerusalém máquinas de guerra projetadas por engenheiros; elas foram colocadas nas torres e nas esquinas da muralha e atiravam flechas e pedras grandes. Assim, a sua fama espalhou-se por toda a parte, pois recebeu uma ajuda extraordinária e tornou-se forte.

[[v14-26-16]]

^<<v14-26-16,16>>^ No entanto, assim que se tornou forte, o seu coração ficou arrogante, para a sua própria ruína, e agiu de maneira infiel contra Jeová, seu Deus, por entrar no templo de Jeová para queimar incenso no altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ Imediatamente, Azarias, o sacerdote, e outros 80 sacerdotes de Jeová, homens corajosos, entraram atrás dele.

[[v14-26-18]]

^<<v14-26-18,18>>^ Confrontaram o rei Uzias e disseram-lhe: “Não lhe cabe a si, rei Uzias, queimar incenso a Jeová! Apenas os sacerdotes devem queimar incenso, pois são os descendentes de Arão, os que foram santificados. Saia do santuário, pois agiu de modo infiel, e não receberá glória da parte de Jeová Deus por isto.”

[[v14-26-19]]

^<<v14-26-19,19>>^ Uzias, porém, que estava com um incensário na mão para queimar incenso, ficou enfurecido; e, durante o seu acesso de ira contra os sacerdotes, apareceu-lhe lepra na testa diante dos sacerdotes, na casa de Jeová, ao pé do altar do incenso.

[[v14-26-20]]

^<<v14-26-20,20>>^ Quando Azarias, o principal sacerdote, e todos os sacerdotes olharam para ele, viram que tinha sido atacado de lepra na testa! Por isso, levaram-no rapidamente para fora, e ele mesmo se apressou a sair, porque Jeová o tinha atingido.

[[v14-26-21]]

^<<v14-26-21,21>>^ O rei Uzias continuou leproso até ao dia da sua morte. Como leproso, ele permaneceu numa casa separada, pois tinha sido excluído da casa de Jeová. Jotão, seu filho, ficou encarregado da casa^&#42;1^ do rei, julgando o povo da terra.

[NOTE]
====
. Ou: “do palácio”.
====

[[v14-26-22]]

^<<v14-26-22,22>>^ E os outros acontecimentos da história de Uzias, do início ao fim, foram registados pelo profeta Isaías, filho de Amoz.

[[v14-26-23]]

^<<v14-26-23,23>>^ Por fim, Uzias descansou com os seus antepassados, e enterraram-no com os seus antepassados, mas no campo de sepultura que pertencia aos reis, pois disseram: “Ele é leproso.” E Jotão, seu filho, tornou-se rei no seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]