include::./index.adoc[]

[[v14-18-0]]
=== 2 Crónicas, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-18-1]]

^<<v14-18-1,1>>^ Jeosafá tinha riquezas e glória em abundância, mas formou uma aliança matrimonial com Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ Portanto, depois de alguns anos foi visitar Acabe em Samaria, e Acabe sacrificou uma grande quantidade de ovelhas e de bois para ele e para os que estavam com ele. E insistiu que Jeosafá fosse^&#42;1^ com ele contra Ramote-Gileade.

[NOTE]
====
. Ou: “E convenceu Jeosafá a ir”.
====

[[v14-18-3]]

^<<v14-18-3,3>>^ Acabe, rei de Israel, perguntou a Jeosafá, rei de Judá: “Vais comigo a Ramote-Gileade?” Ele respondeu-lhe: “Eu estarei contigo, o meu povo estará com o teu povo e irá ajudar-te na guerra.”

[[v14-18-4]]

^<<v14-18-4,4>>^ Contudo, Jeosafá disse ao rei de Israel: “Por favor, primeiro tenta saber qual é a palavra de Jeová.”

[[v14-18-5]]

^<<v14-18-5,5>>^ Então, o rei de Israel reuniu os profetas, 400 homens, e perguntou-lhes: “Devemos atacar Ramote-Gileade, ou não?” Eles responderam: “Vá, e o verdadeiro Deus irá entregá-la nas mãos do rei.”

[[v14-18-6]]

^<<v14-18-6,6>>^ Depois, Jeosafá disse: “Será que não há aqui nenhum profeta de Jeová? Vamos também consultar a Deus por meio dele.”

[[v14-18-7]]

^<<v14-18-7,7>>^ Então, o rei de Israel disse a Jeosafá: “Ainda há mais um homem por meio de quem podemos consultar a Jeová, mas eu odeio-o, pois ele nunca profetiza coisas boas a meu respeito, só coisas más. É Micaías, filho de Inlá.” No entanto, Jeosafá disse: “O rei não deve dizer uma coisa dessas!”

[[v14-18-8]]

^<<v14-18-8,8>>^ Portanto, o rei de Israel chamou um oficial da corte e disse: “Depressa, traz Micaías, filho de Inlá.”

[[v14-18-9]]

^<<v14-18-9,9>>^ O rei de Israel e Jeosafá, rei de Judá, estavam sentados, cada um no seu trono, com as suas vestes reais. Eles estavam sentados na eira que ficava à entrada do portão de Samaria, e todos os profetas estavam a profetizar diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ Então, Zedequias, filho de Quenaaná, fez para si chifres de ferro e disse: “Assim diz Jeová: ‘Com estes chifres, golpearás^&#42;1^ os sírios até os exterminares.’”

[NOTE]
====
. Ou: “empurrarás; chifrarás”.
====

[[v14-18-11]]

^<<v14-18-11,11>>^ Todos os outros profetas profetizavam a mesma coisa, dizendo: “Suba a Ramote-Gileade e será bem-sucedido; Jeová irá entregá-la nas mãos do rei.”

[[v14-18-12]]

^<<v14-18-12,12>>^ Assim, o mensageiro que foi chamar Micaías disse-lhe: “Fica a saber que todas as palavras dos profetas são favoráveis ao rei. Por favor, que as tuas palavras sejam iguais às deles, e diz algo favorável.”

[[v14-18-13]]

^<<v14-18-13,13>>^ Contudo, Micaías disse: “Tão certo como Jeová vive, tudo o que o meu Deus disser é o que direi.”

[[v14-18-14]]

^<<v14-18-14,14>>^ Então, ele apresentou-se ao rei, e o rei perguntou-lhe: “Micaías, devemos atacar Ramote-Gileade, ou não?” Ele respondeu imediatamente: “Vá, e será bem-sucedido; eles serão entregues nas suas mãos.”

[[v14-18-15]]

^<<v14-18-15,15>>^ O rei disse-lhe: “Quantas vezes é que te preciso de pôr sob juramento para não me dizeres nada a não ser a verdade em nome de Jeová?”

[[v14-18-16]]

^<<v14-18-16,16>>^ Então, ele respondeu: “Vejo todos os israelitas espalhados pelos montes como ovelhas sem pastor. Jeová disse: ‘Eles não têm dono. Que cada um volte em paz para a sua casa.’”

[[v14-18-17]]

^<<v14-18-17,17>>^ A seguir, o rei de Israel disse a Jeosafá: “Eu não te disse que ele não ia profetizar coisas boas a meu respeito, só coisas más?”

[[v14-18-18]]

^<<v14-18-18,18>>^ Micaías continuou: “Portanto, ouçam a palavra de Jeová! Vi Jeová sentado no seu trono e todo o exército dos céus em pé à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ E Jeová disse: ‘Quem enganará Acabe, rei de Israel, para que ele suba a Ramote-Gileade e morra lá?’ E um dizia uma coisa, ao passo que outro dizia outra coisa.

[[v14-18-20]]

^<<v14-18-20,20>>^ Então, um espírito^&#42;1^ veio, ficou de pé perante Jeová e disse: ‘Eu vou enganá-lo.’ Jeová perguntou-lhe: ‘Como é que farás isso?’

[NOTE]
====
. Ou: “anjo”.
====

[[v14-18-21]]

^<<v14-18-21,21>>^ Ele respondeu: ‘Eu irei e tornar-me-ei um espírito enganoso na boca de todos os seus profetas.’ Então, ele disse: ‘Tu irás enganá-lo e, além disso, serás bem-sucedido. Vai e faz isso.’

[[v14-18-22]]

^<<v14-18-22,22>>^ E agora Jeová pôs um espírito enganoso na boca destes seus profetas, mas Jeová declarou que o senhor sofrerá uma calamidade.”

[[v14-18-23]]

^<<v14-18-23,23>>^ Zedequias, filho de Quenaaná, aproximou-se e deu uma bofetada a Micaías, e disse: “Quer dizer que o espírito de Jeová me deixou^&#42;1^ para falar contigo?”

[NOTE]
====
. Lit.: “Por onde passou o espírito de Jeová de mim”.
====

[[v14-18-24]]

^<<v14-18-24,24>>^ Micaías respondeu: “Terás a certeza disso no dia em que entrares no quarto mais secreto para te esconderes.”

[[v14-18-25]]

^<<v14-18-25,25>>^ Então, o rei de Israel disse: “Levem Micaías e entreguem-no a Amom, chefe da cidade, e a Joás, filho do rei.

[[v14-18-26]]

^<<v14-18-26,26>>^ Digam-lhes: ‘Assim diz o rei: “Ponham este homem na prisão e deem-lhe uma porção reduzida de pão e água, até eu voltar em paz.”’”

[[v14-18-27]]

^<<v14-18-27,27>>^ Contudo, Micaías disse: “Se o senhor realmente voltar em paz, Jeová não falou comigo.” E acrescentou: “Ouçam isto, todos os povos!”

[[v14-18-28]]

^<<v14-18-28,28>>^ Portanto, o rei de Israel e Jeosafá, rei de Judá, subiram a Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ O rei de Israel disse a Jeosafá: “Vou disfarçar-me e entrar na batalha, mas tu deves usar as tuas vestes reais.” Assim, o rei de Israel disfarçou-se, e entraram na batalha.

[[v14-18-30]]

^<<v14-18-30,30>>^ O rei da Síria tinha dado a seguinte ordem aos chefes dos seus carros de guerra: “Não lutem com ninguém, nem com o pequeno nem com o grande, apenas com o rei de Israel.”

[[v14-18-31]]

^<<v14-18-31,31>>^ Por isso, assim que os chefes dos carros de guerra viram Jeosafá, disseram: “É o rei de Israel!” E foram na sua direção para o atacar. Então, Jeosafá começou a gritar por socorro, e Jeová ajudou-o; Deus afastou-os dele imediatamente.

[[v14-18-32]]

^<<v14-18-32,32>>^ Assim que os chefes dos carros de guerra viram que não era o rei de Israel, pararam de o perseguir.

[[v14-18-33]]

^<<v14-18-33,33>>^ Certo homem, porém, atirou ao acaso^&#42;1^ com o seu arco e atingiu o rei de Israel entre as juntas da sua cota de malha. Então o rei disse ao condutor do seu carro de guerra: “Dá a volta e leva-me para fora da batalha,^&#42;2^ pois fui gravemente ferido.”

[NOTE]
====
. Ou: “na sua inocência”.
. Lit.: “do acampamento”.
====

[[v14-18-34]]

^<<v14-18-34,34>>^ A batalha continuou intensa durante aquele dia, e tiveram de manter o rei de Israel em pé no seu carro de guerra, de frente para os sírios, até ao entardecer; e ele morreu ao pôr do sol.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]