include::./index.adoc[]

[[v14-5-0]]
=== 2 Crónicas, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-5-1]]

^<<v14-5-1,1>>^ Assim, Salomão terminou todo o trabalho que tinha de fazer para a casa de Jeová. Depois, Salomão levou para dentro as coisas que David, seu pai, tinha tornado sagradas, e pôs a prata, o ouro e todos os utensílios no tesouro da casa do verdadeiro Deus.

[[v14-5-2]]

^<<v14-5-2,2>>^ Naqueles dias, Salomão reuniu os anciãos de Israel: todos os cabeças das tribos e os maiorais das casas paternas de Israel. Eles vieram até Jerusalém para que a Arca do Pacto de Jeová fosse transferida da Cidade de David, isto é, Sião.

[[v14-5-3]]

^<<v14-5-3,3>>^ Todos os homens de Israel se reuniram diante do rei na festividade^&#42;1^ que se realiza no sétimo mês.

[NOTE]
====
. Isto é, na Festividade das Barracas.
====

[[v14-5-4]]

^<<v14-5-4,4>>^ Portanto, todos os anciãos de Israel vieram, e os levitas levantaram a Arca.

[[v14-5-5]]

^<<v14-5-5,5>>^ Eles carregaram para cima a Arca, a tenda de reunião e todos os utensílios sagrados que havia na tenda. Os sacerdotes e os levitas^&#42;1^ levaram-nos para cima.

[NOTE]
====
. Ou: “Os sacerdotes levíticos”.
====

[[v14-5-6]]

^<<v14-5-6,6>>^ O rei Salomão e toda a assembleia de Israel, que tinha sido convocada para se reunir com ele, estavam diante da Arca; e sacrificaram tantas ovelhas e bois que nem se podiam contar nem enumerar.

[[v14-5-7]]

^<<v14-5-7,7>>^ Depois, os sacerdotes levaram a Arca do Pacto de Jeová para o seu lugar, dentro do compartimento interno da casa, o Santíssimo, e colocaram-na debaixo das asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ Assim, as asas dos querubins ficavam estendidas sobre o lugar onde estava a Arca, de modo que os querubins cobriam a Arca e os seus varais.

[[v14-5-9]]

^<<v14-5-9,9>>^ Os varais eram tão compridos que as suas pontas se podiam ver do Santo, em frente do compartimento interno, mas não se viam de fora. E os varais estão ali até ao dia de hoje.

[[v14-5-10]]

^<<v14-5-10,10>>^ Não havia nada na Arca a não ser as duas tábuas lá colocadas por Moisés, em Horebe, quando Jeová fez um pacto com o povo de Israel ao saírem do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ Depois, os sacerdotes saíram do lugar santo (todos os sacerdotes que estavam presentes tinham-se santificado, independentemente da turma a que pertenciam).

[[v14-5-12]]

^<<v14-5-12,12>>^ E todos os cantores levitas, pertencentes a Asafe, a Hemã, a Jedutum, e aos seus filhos e seus irmãos, estavam de pé a leste do altar vestidos de tecido fino, com címbalos, instrumentos de cordas e harpas; e com eles 120 sacerdotes tocavam as trombetas.

[[v14-5-13]]

^<<v14-5-13,13>>^ Os que tocavam as trombetas e os cantores louvavam e agradeciam a Jeová em uníssono. E o som das trombetas, dos címbalos e dos outros instrumentos musicais ressoava, enquanto louvavam a Jeová, “pois ele é bom, o seu amor leal dura para sempre”. Nesse momento, uma nuvem encheu a casa, a casa de Jeová.

[[v14-5-14]]

^<<v14-5-14,14>>^ Os sacerdotes não puderam ficar lá para realizar o seu serviço por causa da nuvem, pois a glória de Jeová enchia a casa do verdadeiro Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]