include::./index.adoc[]

[[v14-23-0]]
=== 2 Crónicas, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-23-1]]

^<<v14-23-1,1>>^ No sétimo ano, Jeoiada agiu com coragem e fez um pacto com os chefes de cem, a saber, Azarias, filho de Jeroão, Ismael, filho de Jeoanã, Azarias, filho de Obede, Maaseias, filho de Adaías, e Elisafate, filho de Zicri.

[[v14-23-2]]

^<<v14-23-2,2>>^ Depois, percorreram Judá e reuniram os levitas de todas as cidades de Judá, assim como os cabeças das casas paternas de Israel. Quando chegaram a Jerusalém,

[[v14-23-3]]

^<<v14-23-3,3>>^ toda a congregação fez um pacto com o rei na casa do verdadeiro Deus, e depois Jeoiada disse-lhes:
“Vejam! O filho do rei reinará, assim como Jeová prometeu a respeito dos filhos de David.

[[v14-23-4]]

^<<v14-23-4,4>>^ Façam o seguinte: um terço dos sacerdotes e dos levitas que estarão de serviço no sábado servirão como porteiros,

[[v14-23-5]]

^<<v14-23-5,5>>^ outro terço ficará na casa^&#42;1^ do rei, e o outro terço ficará no Portão do Alicerce; e todo o povo ficará nos pátios da casa de Jeová.

[NOTE]
====
. Ou: “no palácio”.
====

[[v14-23-6]]

^<<v14-23-6,6>>^ Não deixem ninguém entrar na casa de Jeová, exceto os sacerdotes e os levitas que estiverem a prestar serviço. Estes poderão entrar porque são um grupo santo, e todo o povo cumprirá a sua obrigação para com Jeová.

[[v14-23-7]]

^<<v14-23-7,7>>^ Os levitas devem ficar à volta do rei, cada um com as suas armas na mão. Quem entrar na casa será morto. Fiquem com o rei onde quer que ele for.”^&#42;1^

[NOTE]
====
. Lit.: “quando ele sair e quando ele entrar”.
====

[[v14-23-8]]

^<<v14-23-8,8>>^ Os levitas e todo o Judá fizeram exatamente o que Jeoiada, o sacerdote, tinha ordenado. Portanto, cada um reuniu os seus homens que estavam de serviço no sábado e os que estavam de folga no sábado, pois Jeoiada, o sacerdote, não tinha dispensado as turmas do seu serviço.

[[v14-23-9]]

^<<v14-23-9,9>>^ Jeoiada, o sacerdote, deu então aos chefes de cem as lanças, os escudos pequenos^&#42;1^ e os escudos redondos que tinham pertencido ao rei David e que estavam na casa do verdadeiro Deus.

[NOTE]
====
. Ou: “broquéis”, pequenos escudos geralmente usados por arqueiros.
====

[[v14-23-10]]

^<<v14-23-10,10>>^ E colocou todos os homens nas suas posições, cada um com a sua arma^&#42;1^ na mão, desde o lado direito da casa até ao lado esquerdo da casa, junto ao altar e junto à casa, à volta do rei.

[NOTE]
====
. Ou: “arma de arremesso”.
====

[[v14-23-11]]

^<<v14-23-11,11>>^ A seguir, trouxeram para fora o filho do rei, puseram-lhe a coroa^&#42;1^ e o Testemunho^&#42;2^ e fizeram-no rei; e Jeoiada e os seus filhos ungiram-no. Depois disseram: “Viva o rei!”

[NOTE]
====
. Ou: “o diadema”.
. Possivelmente um rolo que continha a Lei de Deus.
====

[[v14-23-12]]

^<<v14-23-12,12>>^ Quando Atalia ouviu o barulho do povo a correr e a louvar o rei, foi imediatamente ter com o povo na casa de Jeová.

[[v14-23-13]]

^<<v14-23-13,13>>^ Então, ela viu o rei de pé junto à coluna,^&#42;1^ na entrada. Os príncipes e os que tocavam as trombetas estavam com o rei; e todo o povo^&#42;2^ se alegrava e tocava trombetas, e os cantores, com instrumentos musicais, lideravam^&#42;3^ os louvores. Em vista disso, Atalia rasgou a sua roupa e gritou: “Conspiração! Conspiração!”

[NOTE]
====
. Lit.: “coluna dele”.
. Lit.: “povo da terra”.
. Ou: “davam o sinal para”.
====

[[v14-23-14]]

^<<v14-23-14,14>>^ Contudo, Jeoiada, o sacerdote, enviou os chefes de cem, os encarregados do exército, dizendo: “Tirem-na do meio das fileiras, e matem com a espada quem for atrás dela!” Pois o sacerdote tinha dito: “Não a matem dentro da casa de Jeová.”

[[v14-23-15]]

^<<v14-23-15,15>>^ Assim, eles agarraram-na e levaram-na até à entrada do Portão dos Cavalos, na casa^&#42;1^ do rei; assim que lá chegaram, mataram-na.

[NOTE]
====
. Ou: “no palácio”.
====

[[v14-23-16]]

^<<v14-23-16,16>>^ Então, Jeoiada fez um pacto entre si mesmo, todo o povo e o rei, segundo o qual continuariam a ser o povo de Jeová.

[[v14-23-17]]

^<<v14-23-17,17>>^ Depois disso, todo o povo foi à casa^&#42;1^ de Baal e a demoliu; despedaçaram os seus altares e imagens e executaram Matã, sacerdote de Baal, diante dos altares.

[NOTE]
====
. Ou: “ao templo”.
====

[[v14-23-18]]

^<<v14-23-18,18>>^ A seguir, Jeoiada colocou a supervisão da casa de Jeová nas mãos dos sacerdotes e dos levitas, os quais David tinha organizado em turmas para servirem na casa de Jeová, oferecendo os sacrifícios queimados de Jeová, conforme está escrito na Lei de Moisés, com alegria e com cânticos, segundo as instruções^&#42;1^ de David.

[NOTE]
====
. Lit.: “pelas mãos”.
====

[[v14-23-19]]

^<<v14-23-19,19>>^ Também colocou os porteiros nos portões da casa de Jeová, para que não entrasse ninguém que de algum modo estivesse impuro.

[[v14-23-20]]

^<<v14-23-20,20>>^ Reuniu os chefes de cem, os nobres, os governantes do povo e todo o povo,^&#42;1^ e eles acompanharam o rei da casa de Jeová até à casa^&#42;2^ do rei, pelo portão superior; e fizeram o rei sentar-se no trono real.

[NOTE]
====
. Lit.: “povo da terra”.
. Ou: “o palácio”.
====

[[v14-23-21]]

^<<v14-23-21,21>>^ Assim, todo o povo^&#42;1^ se alegrou e a cidade ficou em paz, visto que Atalia tinha sido morta com a espada.

[NOTE]
====
. Lit.: “povo da terra”.
====

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]