include::./index.adoc[]

[[v14-8-0]]
=== 2 Crónicas, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-8-1]]

^<<v14-8-1,1>>^ Ao fim dos 20 anos que Salomão levou a construir a casa de Jeová e a sua própria casa,^&#42;1^

[NOTE]
====
. Ou: “o seu próprio palácio”.
====

[[v14-8-2]]

^<<v14-8-2,2>>^ Salomão reconstruiu as cidades que Hirão lhe tinha dado e colocou israelitas^&#42;1^ a morar ali.

[NOTE]
====
. Lit.: “filhos de Israel”.
====

[[v14-8-3]]

^<<v14-8-3,3>>^ Além disso, Salomão foi a Hamate-Zobá e conquistou-a.

[[v14-8-4]]

^<<v14-8-4,4>>^ Depois, fortificou^&#42;1^ Tadmor, no deserto, e todas as cidades-armazém que tinha construído em Hamate.

[NOTE]
====
. Ou: “reconstruiu”.
====

[[v14-8-5]]

^<<v14-8-5,5>>^ Ele também construiu^&#42;1^ Bete-Horom Alta e Bete-Horom Baixa, cidades fortificadas com muralhas, portões e trancas,

[NOTE]
====
. Ou: “reconstruiu; fortificou”.
====

[[v14-8-6]]

^<<v14-8-6,6>>^ assim como Baalate e todas as cidades-armazém de Salomão, todas as cidades dos carros de guerra, as cidades para os cavaleiros e tudo o que Salomão desejou construir em Jerusalém, no Líbano e em todas as terras sob o seu domínio.

[[v14-8-7]]

^<<v14-8-7,7>>^ Quanto a todos os que tinham restado dos hititas, dos amorreus, dos perizeus, dos heveus e dos jebuseus, que não faziam parte de Israel

[[v14-8-8]]

^<<v14-8-8,8>>^ — isto é, os descendentes desses povos que restaram no país e que os israelitas não tinham exterminado —, foram recrutados por Salomão para trabalhos forçados e assim continuam até hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Contudo, Salomão não fez nenhum dos israelitas servir como escravo na sua obra, pois eles eram seus guerreiros, chefes dos seus oficiais e chefes dos seus condutores de carros de guerra e dos cavaleiros.

[[v14-8-10]]

^<<v14-8-10,10>>^ Havia 250 chefes dos encarregados da obra do rei Salomão. Eles eram os capatazes dos trabalhadores.

[[v14-8-11]]

^<<v14-8-11,11>>^ E Salomão levou a filha do Faraó da Cidade de David para a casa que lhe tinha construído, pois disse: “Embora ela seja minha esposa, não deve morar na casa de David, o rei de Israel, pois os lugares onde a Arca de Jeová esteve são sagrados.”

[[v14-8-12]]

^<<v14-8-12,12>>^ Em seguida, Salomão ofereceu a Jeová sacrifícios queimados no altar de Jeová, que ele tinha construído em frente ao pórtico.

[[v14-8-13]]

^<<v14-8-13,13>>^ Ele seguia a rotina diária e fazia ofertas de acordo com o mandamento de Moisés para os sábados, as luas novas e as três festividades anuais: a Festividade dos Pães sem Fermento, a Festividade das Semanas e a Festividade das Barracas.^&#42;1^

[NOTE]
====
. Ou: “dos Tabernáculos”.
====

[[v14-8-14]]

^<<v14-8-14,14>>^ Além disso, de acordo com as instruções de David, seu pai, Salomão designou as turmas de sacerdotes para os seus serviços, e os levitas para os seus postos, para darem louvor e servirem diante dos sacerdotes de acordo com a rotina diária. Designou os porteiros nas suas turmas para os diversos portões, pois essas eram as ordens de David, o homem do verdadeiro Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ E não se desviaram do mandamento do rei aos sacerdotes e aos levitas em nenhum assunto, nem no que se refere aos depósitos.

[[v14-8-16]]

^<<v14-8-16,16>>^ Portanto, toda a obra de Salomão foi bem organizada,^&#42;1^ desde o dia em que se lançou o alicerce da casa de Jeová até quando foi terminada. Assim, a casa de Jeová foi concluída.

[NOTE]
====
. Ou: “bem ordenada; completada”.
====

[[v14-8-17]]

^<<v14-8-17,17>>^ Foi nessa altura que Salomão foi a Eziom-Geber e a Elote, à beira-mar, na terra de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ Por meio dos seus servos, Hirão enviou-lhe navios e marinheiros experientes. Eles foram com os servos de Salomão a Ofir e trouxeram de lá 450 talentos^&#42;1^ de ouro, e levaram-nos ao rei Salomão.

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]