include::./index.adoc[]

[[v14-21-0]]
=== 2 Crónicas, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-21-1]]

^<<v14-21-1,1>>^ Por fim, Jeosafá descansou com os seus antepassados e foi enterrado com os seus antepassados na Cidade de David; e Jeorão, seu filho, tornou-se rei no seu lugar.

[[v14-21-2]]

^<<v14-21-2,2>>^ Os irmãos dele, filhos de Jeosafá, foram Azarias, Jeiel, Zacarias, Azarias, Micael e Sefatias; todos estes eram filhos de Jeosafá, rei de Israel.

[[v14-21-3]]

^<<v14-21-3,3>>^ E o seu pai tinha-lhes dado como presente muita prata, ouro e coisas valiosas, além de cidades fortificadas em Judá; mas deu o reino a Jeorão, pois era o primogénito.

[[v14-21-4]]

^<<v14-21-4,4>>^ Quando Jeorão assumiu o controlo do reino do seu pai, fortaleceu a sua posição por matar com a espada todos os seus irmãos e também alguns príncipes de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Jeorão tinha 32 anos de idade quando se tornou rei, e reinou durante oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ Ele andava no caminho dos reis de Israel, assim como os da casa de Acabe tinham feito, pois a filha de Acabe tinha-se tornado sua esposa; e ele fazia o que era mau aos olhos de Jeová.

[[v14-21-7]]

^<<v14-21-7,7>>^ Contudo, Jeová não quis destruir a casa de David, por causa do pacto que tinha feito com David, visto que lhe tinha prometido dar uma lâmpada, a ele e aos seus filhos, para sempre.

[[v14-21-8]]

^<<v14-21-8,8>>^ Nos dias de Jeorão, Edom rebelou-se contra Judá e estabeleceu o seu próprio rei.

[[v14-21-9]]

^<<v14-21-9,9>>^ Por isso, Jeorão e os seus chefes foram para lá com todos os seus carros de guerra. De noite, ele atacou e derrotou os edomitas que o cercavam, a ele e aos chefes dos carros de guerra.

[[v14-21-10]]

^<<v14-21-10,10>>^ No entanto, a revolta de Edom contra Judá continua até ao dia de hoje. Libna também se rebelou contra ele naquela altura, porque ele tinha abandonado a Jeová, o Deus dos seus antepassados.

[[v14-21-11]]

^<<v14-21-11,11>>^ Jeorão também tinha feito altos sagrados nos montes de Judá, para levar os habitantes de Jerusalém a cometerem prostituição espiritual, e ele desencaminhou Judá.

[[v14-21-12]]

^<<v14-21-12,12>>^ Por fim, recebeu uma mensagem escrita do profeta Elias, que dizia: “Assim diz Jeová, o Deus de David, teu antepassado: ‘Tu não andaste nos caminhos de Jeosafá, teu pai, nem nos caminhos de Asa, rei de Judá.

[[v14-21-13]]

^<<v14-21-13,13>>^ Mas andas no caminho dos reis de Israel, e levas Judá e os habitantes de Jerusalém a cometerem prostituição espiritual igual à prostituição da casa de Acabe. Tu até mesmo mataste os teus próprios irmãos, os da casa do teu pai, que eram melhores do que tu.

[[v14-21-14]]

^<<v14-21-14,14>>^ Por isso, Jeová golpeará fortemente o teu povo, os teus filhos, as tuas esposas e todos os teus bens.

[[v14-21-15]]

^<<v14-21-15,15>>^ E terás muitas doenças, incluindo uma doença nos intestinos que piorará dia após dia, até que os teus intestinos saiam do corpo.’”

[[v14-21-16]]

^<<v14-21-16,16>>^ Então, Jeová instigou contra Jeorão os filisteus^&#42;1^ e os árabes que moravam perto dos etíopes.

[NOTE]
====
. Lit.: “o espírito dos filisteus”.
====

[[v14-21-17]]

^<<v14-21-17,17>>^ Atacaram Judá, invadindo o país, e levaram todos os bens que encontraram na casa^&#42;1^ do rei, assim como os seus filhos e as suas esposas; o único filho que sobrou foi Jeoacaz,^&#42;2^ o seu filho mais novo.

[NOTE]
====
. Ou: “no palácio”.
. Também chamado Acazias.
====

[[v14-21-18]]

^<<v14-21-18,18>>^ E, depois de tudo isto, Jeová fez Jeorão sofrer de uma doença incurável nos intestinos.

[[v14-21-19]]

^<<v14-21-19,19>>^ Algum tempo depois, passados dois anos completos, os intestinos saíram-lhe do corpo por causa da doença, e ele morreu enquanto sofria terrivelmente da sua doença. E o seu povo não lhe fez uma queima fúnebre, como tinham feito para os seus antepassados.

[[v14-21-20]]

^<<v14-21-20,20>>^ Ele tinha 32 anos de idade quando se tornou rei, e reinou durante oito anos em Jerusalém. Ninguém lamentou quando ele morreu. Portanto, enterraram-no na Cidade de David, mas não nas sepulturas dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]