include::./index.adoc[]

[[v14-12-0]]
=== 2 Crónicas, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-12-1]]

^<<v14-12-1,1>>^ Assim que o reinado de Roboão ficou firmemente estabelecido e ele se tornou forte, ele abandonou a Lei de Jeová, e todo o Israel fez o mesmo.

[[v14-12-2]]

^<<v14-12-2,2>>^ Visto que tinham sido infiéis a Jeová, Sisaque, rei do Egito, veio contra Jerusalém no quinto ano do rei Roboão.

[[v14-12-3]]

^<<v14-12-3,3>>^ Ele tinha 1200 carros de guerra, 60 000 cavaleiros e inúmeros soldados que vieram com ele do Egito — líbios, suquitas e etíopes.

[[v14-12-4]]

^<<v14-12-4,4>>^ Ele conquistou as cidades fortificadas de Judá e chegou a Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ O profeta Semaías dirigiu-se a Roboão e aos príncipes de Judá, que se tinham reunido em Jerusalém por causa de Sisaque, e disse-lhes: “Assim diz Jeová: ‘Abandonaram-me, por isso eu também vos abandono às mãos de Sisaque.’”

[[v14-12-6]]

^<<v14-12-6,6>>^ Em vista disso, os príncipes de Israel e o rei humilharam-se e disseram: “Jeová é justo.”

[[v14-12-7]]

^<<v14-12-7,7>>^ Quando Jeová viu que se tinham humilhado, Jeová enviou a seguinte palavra a Semaías: “Humilharam-se. Não os vou destruir, mas em breve vou libertá-los. Não derramarei a minha ira sobre Jerusalém por meio de Sisaque.

[[v14-12-8]]

^<<v14-12-8,8>>^ Contudo, eles irão tornar-se servos dele, de modo que saberão a diferença entre servir-me a mim e servir os reis^&#42;1^ de outras terras.”

[NOTE]
====
. Lit.: “reinos”.
====

[[v14-12-9]]

^<<v14-12-9,9>>^ Portanto, Sisaque, rei do Egito, veio contra Jerusalém. Ele levou os tesouros da casa de Jeová e os tesouros da casa^&#42;1^ do rei. Levou tudo, incluindo os escudos de ouro que Salomão tinha feito.

[NOTE]
====
. Ou: “do palácio”.
====

[[v14-12-10]]

^<<v14-12-10,10>>^ Por isso, o rei Roboão fez escudos de cobre para os substituir e entregou-os aos chefes da guarda,^&#42;1^ que vigiavam a entrada da casa do rei.

[NOTE]
====
. Lit.: “dos corredores”.
====

[[v14-12-11]]

^<<v14-12-11,11>>^ Sempre que o rei ia à casa de Jeová, os guardas entravam, carregando os escudos, e depois devolviam-nos à sala dos guardas.

[[v14-12-12]]

^<<v14-12-12,12>>^ Visto que o rei se humilhou, a ira de Jeová afastou-se dele, e ele não os destruiu totalmente. Além disso, ainda havia algumas coisas boas em Judá.

[[v14-12-13]]

^<<v14-12-13,13>>^ O rei Roboão fortaleceu a sua posição em Jerusalém e continuou a reinar. Roboão tinha 41 anos de idade quando se tornou rei, e reinou durante 17 anos em Jerusalém, a cidade que Jeová tinha escolhido dentre todas as tribos de Israel como o lugar para pôr o seu nome. O nome da mãe do rei era Naamá, a amonita.

[[v14-12-14]]

^<<v14-12-14,14>>^ Contudo, ele fez o que era mau, pois não estava determinado no coração a buscar a Jeová.

[[v14-12-15]]

^<<v14-12-15,15>>^ Quanto à história de Roboão, do início ao fim, não está registada nos escritos de Semaías, o profeta, e de Ido, o vidente,^&#42;1^ no registo genealógico? E houve sempre guerras entre Roboão e Jeroboão.

[NOTE]
====
. Veja o Glossário.
====

[[v14-12-16]]

^<<v14-12-16,16>>^ Por fim, Roboão descansou com os seus antepassados e foi enterrado na Cidade de David; e o filho dele, Abias, tornou-se rei no seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]