include::./index.adoc[]

[[v14-33-0]]
=== 2 Crónicas, 33
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-33-1]]

^<<v14-33-1,1>>^ Manassés tinha 12 anos de idade quando se tornou rei, e reinou durante 55 anos em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ Ele fez o que era mau aos olhos de Jeová, imitando as práticas detestáveis das nações que Jeová tinha expulsado de diante do povo de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ Ele reconstruiu os altos sagrados que Ezequias, seu pai, tinha demolido, construiu altares aos baalins e fez postes sagrados.^&#42;1^ Curvou-se diante de todo o exército dos céus e serviu-os.

[NOTE]
====
. Veja o Glossário.
====

[[v14-33-4]]

^<<v14-33-4,4>>^ Também construiu altares na casa de Jeová, a respeito da qual Jeová tinha dito: “O meu nome estará em Jerusalém para sempre.”

[[v14-33-5]]

^<<v14-33-5,5>>^ Além disso, construiu altares a todo o exército dos céus nos dois pátios da casa de Jeová.

[[v14-33-6]]

^<<v14-33-6,6>>^ Ele queimou os seus próprios filhos no fogo,^&#42;1^ no vale do Filho de Hinom, praticou magia, adivinhação e feitiçaria, e designou adivinhos e pessoas que invocavam espíritos. Fez em grande escala o que era mau aos olhos de Jeová, para o ofender.

[NOTE]
====
. Lit.: “fez os seus filhos passarem pelo fogo”.
====

[[v14-33-7]]

^<<v14-33-7,7>>^ Ele fez uma imagem esculpida e colocou-a na casa do verdadeiro Deus, sobre a qual Deus tinha dito a David e a Salomão, seu filho: “Nesta casa e em Jerusalém, que escolhi dentre todas as tribos de Israel, porei permanentemente o meu nome.

[[v14-33-8]]

^<<v14-33-8,8>>^ E nunca mais removerei os pés de Israel da terra que prometi aos seus antepassados, desde que obedeçam cuidadosamente a tudo o que lhes ordenei — toda a Lei, os decretos e as decisões judiciais dados por meio de Moisés.”

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés continuou a desencaminhar Judá e os habitantes de Jerusalém, levando-os a agir pior do que as nações que Jeová tinha eliminado de diante dos israelitas.

[[v14-33-10]]

^<<v14-33-10,10>>^ Jeová falava a Manassés e ao seu povo, mas eles não prestavam atenção.

[[v14-33-11]]

^<<v14-33-11,11>>^ Assim, Jeová trouxe contra eles os chefes do exército do rei da Assíria. Capturaram Manassés com ganchos,^&#42;1^ prenderam-no com duas correntes de cobre e levaram-no para Babilónia.

[NOTE]
====
. Ou, possivelmente: “nas fendas”.
====

[[v14-33-12]]

^<<v14-33-12,12>>^ Na sua aflição, ele implorou o favor^&#42;1^ de Jeová, seu Deus, e humilhou-se profundamente diante do Deus dos seus antepassados.

[NOTE]
====
. Ou: “abrandou a face”.
====

[[v14-33-13]]

^<<v14-33-13,13>>^ Manassés orava a Ele, e Ele comoveu-se com as suas súplicas e o seu pedido de favor, e trouxe-o de volta para Jerusalém, para o seu reinado. Então, Manassés reconheceu que Jeová é o verdadeiro Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Depois, construiu uma muralha externa para a Cidade de David, a oeste de Giom, que fica no vale.^&#42;1^ Construiu-a até ao Portão do Peixe. De lá continuou a construir a muralha, contornando a cidade até Ofel; a muralha era muito alta. Além disso, designou chefes do exército em todas as cidades fortificadas de Judá.

[NOTE]
====
. Ou: “uádi”.
====

[[v14-33-15]]

^<<v14-33-15,15>>^ Em seguida, removeu da casa de Jeová os deuses estrangeiros e o ídolo, assim como todos os altares que tinha construído no monte da casa de Jeová e em Jerusalém, e mandou deitá-los fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Também restaurou o altar de Jeová e começou a oferecer nele sacrifícios de participação em comum e sacrifícios de agradecimento, e disse a Judá que servisse a Jeová, o Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ No entanto, o povo ainda oferecia sacrifícios nos altos sagrados, embora fizessem isso apenas a Jeová, seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Os outros acontecimentos da história de Manassés, a sua oração ao seu Deus e as palavras dos videntes^&#42;1^ que lhe falaram em nome de Jeová, o Deus de Israel, estão registados na história dos reis de Israel.

[NOTE]
====
. Veja o Glossário.
====

[[v14-33-19]]

^<<v14-33-19,19>>^ A sua oração e o modo como a sua súplica foi respondida, todos os seus pecados, a sua infidelidade, os locais onde construiu os altos sagrados e pôs os postes sagrados^&#42;1^ e as imagens esculpidas antes de se humilhar, está tudo registado nos escritos dos seus videntes.^&#42;2^

[NOTE]
====
. Veja o Glossário.
. Veja o Glossário.
====

[[v14-33-20]]

^<<v14-33-20,20>>^ Por fim, Manassés descansou com os seus antepassados, e enterraram-no na sua casa; e Amom, seu filho, tornou-se rei no seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Amom tinha 22 anos de idade quando se tornou rei, e reinou durante dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ Ele fazia o que era mau aos olhos de Jeová, assim como Manassés, seu pai, tinha feito; Amom oferecia sacrifícios a todas as imagens esculpidas que Manassés, seu pai, tinha feito, e servia-as.

[[v14-33-23]]

^<<v14-33-23,23>>^ Todavia, ele não se humilhou diante de Jeová assim como Manassés, seu pai, se tinha humilhado; pelo contrário, Amom aumentou ainda mais a sua culpa.

[[v14-33-24]]

^<<v14-33-24,24>>^ Por fim, os seus servos conspiraram contra ele e mataram-no na sua própria casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ No entanto, o povo da terra matou todos os que tinham conspirado contra o rei Amom e fizeram de Josias, seu filho, rei no seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]