include::./index.adoc[]

[[v14-17-0]]
=== 2 Crónicas, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-17-1]]

^<<v14-17-1,1>>^ Então, Jeosafá, seu filho, tornou-se rei no seu lugar e fortaleceu a sua posição sobre Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ Ele pôs forças militares em todas as cidades fortificadas de Judá e tropas na terra de Judá e nas cidades de Efraim que Asa, seu pai, tinha conquistado.

[[v14-17-3]]

^<<v14-17-3,3>>^ Jeová estava com Jeosafá porque ele andava nos caminhos em que David, seu antepassado, tinha andado nos tempos antigos, e não procurava os baalins.

[[v14-17-4]]

^<<v14-17-4,4>>^ Procurava o Deus do seu pai e seguia o^&#42;1^ Seu mandamento, não as práticas de Israel.

[NOTE]
====
. Lit.: “andava no”.
====

[[v14-17-5]]

^<<v14-17-5,5>>^ Jeová manteve o reino firmemente estabelecido nas mãos de Jeosafá; e todo o Judá lhe dava presentes, de modo que ele teve riquezas e glória em abundância.

[[v14-17-6]]

^<<v14-17-6,6>>^ Ele tornou-se corajoso nos caminhos de Jeová e até mesmo removeu de Judá os altos sagrados e os postes sagrados.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v14-17-7]]

^<<v14-17-7,7>>^ No terceiro ano do seu reinado mandou chamar os seus príncipes, Ben-Hail, Obadias, Zacarias, Netanel e Micaías, para ensinarem nas cidades de Judá.

[[v14-17-8]]

^<<v14-17-8,8>>^ Os seguintes levitas foram com eles: Semaías, Netanias, Zebadias, Asael, Semiramote, Jeonatã, Adonias, Tobias e Tobe-Adonias. Os sacerdotes Elisama e Jeorão também foram.

[[v14-17-9]]

^<<v14-17-9,9>>^ Eles começaram a ensinar em Judá, levando consigo o livro da Lei de Jeová; percorreram todas as cidades de Judá, ensinando o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ E todos os reinos das terras ao redor de Judá ficaram com pavor de Jeová e não lutaram contra Jeosafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ E os filisteus traziam presentes e dinheiro como tributo a Jeosafá. Os árabes trouxeram-lhe 7700 carneiros e 7700 bodes dos seus rebanhos.

[[v14-17-12]]

^<<v14-17-12,12>>^ Jeosafá tornou-se cada vez mais poderoso, e continuou a construir fortalezas e cidades-armazém em Judá.

[[v14-17-13]]

^<<v14-17-13,13>>^ Realizou grandes empreendimentos nas cidades de Judá, e tinha soldados, guerreiros valentes, em Jerusalém.

[[v14-17-14]]

^<<v14-17-14,14>>^ Estes estavam agrupados segundo as suas casas paternas: De Judá, havia os chefes de mil. Havia o chefe Adná, e com ele 300 000 guerreiros valentes.

[[v14-17-15]]

^<<v14-17-15,15>>^ Sob o seu comando estava o chefe Jeoanã, e com ele 280 000 homens.

[[v14-17-16]]

^<<v14-17-16,16>>^ E também sob o seu comando estava Amasias, filho de Zicri, que se tinha apresentado voluntariamente para o serviço de Jeová, e com ele havia 200 000 guerreiros valentes.

[[v14-17-17]]

^<<v14-17-17,17>>^ E de Benjamim havia Eliada, um guerreiro valente, e com ele 200 000 homens armados com arco e escudo.

[[v14-17-18]]

^<<v14-17-18,18>>^ E sob o seu comando estava Jeozabade, e com ele 180 000 homens equipados para a guerra.

[[v14-17-19]]

^<<v14-17-19,19>>^ Estes serviam o rei, além dos que o rei colocou nas cidades fortificadas em todo o Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]