include::./index.adoc[]

[[v14-3-0]]
=== 2 Crónicas, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-3-1]]

^<<v14-3-1,1>>^ Então, Salomão começou a construir a casa de Jeová em Jerusalém, no monte Moriá, onde Jeová tinha aparecido a David, seu pai, no lugar que David tinha preparado, na eira de Ornã, o jebuseu.

[[v14-3-2]]

^<<v14-3-2,2>>^ Começou a construir no dia dois do segundo mês, no quarto ano do seu reinado.

[[v14-3-3]]

^<<v14-3-3,3>>^ E o alicerce que Salomão lançou para a construção da casa do verdadeiro Deus tinha 60 côvados de comprimento e 20 côvados de largura, de acordo com a medida antiga.^&#42;1^

[NOTE]
====
. Um côvado padrão equivalia a 44,5 cm, mas alguns acham que “a medida antiga” se refere ao côvado longo, que equivalia a 51,8 cm. Veja o Ap. B14.
====

[[v14-3-4]]

^<<v14-3-4,4>>^ O pórtico na parte da frente da casa tinha a mesma largura da casa: 20 côvados.^&#42;1^ E a sua altura era de 120;^&#42;2^ e ele revestiu-o por dentro de ouro puro.

[NOTE]
====
. Ou: “tinha 20 côvados de comprimento, que correspondia à largura da casa”.
. A unidade de medida é incerta.
====

[[v14-3-5]]

^<<v14-3-5,5>>^ Colocou painéis de madeira de junípero no compartimento principal, revestiu-o de ouro puro e depois decorou-o com figuras de palmeiras e correntes.

[[v14-3-6]]

^<<v14-3-6,6>>^ Além disso, incrustou a casa com belas pedras preciosas, e o ouro que ele usou era de Parvaim.

[[v14-3-7]]

^<<v14-3-7,7>>^ Revestiu de ouro a casa: as vigas, as soleiras, as paredes e as portas; e nas paredes esculpiu querubins.

[[v14-3-8]]

^<<v14-3-8,8>>^ E fez o compartimento do Santíssimo;^&#42;1^ o seu comprimento era igual à largura da casa, 20 côvados, e a sua largura também era de 20 côvados. Revestiu-o com 600 talentos^&#42;2^ de ouro puro.

[NOTE]
====
. Ou: “a casa Santíssima”.
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v14-3-9]]

^<<v14-3-9,9>>^ O peso do ouro dos pregos era de 50 siclos.^&#42;1^ Revestiu também de ouro os compartimentos superiores.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v14-3-10]]

^<<v14-3-10,10>>^ Depois, fez no compartimento do Santíssimo^&#42;1^ duas esculturas de querubins, e revestiu-as de ouro.

[NOTE]
====
. Ou: “na casa Santíssima”.
====

[[v14-3-11]]

^<<v14-3-11,11>>^ O comprimento total das asas dos querubins era de 20 côvados; uma asa do primeiro querubim tinha cinco côvados e tocava na parede da casa, e a outra asa tinha cinco côvados e tocava numa das asas do outro querubim.

[[v14-3-12]]

^<<v14-3-12,12>>^ E uma asa do outro querubim tinha cinco côvados e tocava na outra parede da casa, e a outra asa tinha cinco côvados e tocava numa das asas do primeiro querubim.

[[v14-3-13]]

^<<v14-3-13,13>>^ As asas destes querubins estendiam-se por 20 côvados; e eles estavam de pé, com a face voltada para dentro.^&#42;1^

[NOTE]
====
. Isto é, para o Santo.
====

[[v14-3-14]]

^<<v14-3-14,14>>^ Também fez a cortina de linha azul, lã roxa, linha escarlate e tecido fino, e bordou-a com figuras de querubins.

[[v14-3-15]]

^<<v14-3-15,15>>^ A seguir, fez na parte da frente da casa duas colunas de 35 côvados de altura, e o capitel no topo de cada coluna tinha cinco côvados.

[[v14-3-16]]

^<<v14-3-16,16>>^ E fez correntes em forma de colar e pô-las no topo das colunas, e fez cem romãs e pô-las nas correntes.

[[v14-3-17]]

^<<v14-3-17,17>>^ Ele ergueu as colunas na parte da frente do templo, uma à direita^&#42;1^ e outra à esquerda;^&#42;2^ à da direita chamou Jaquim^&#42;3^ e à da esquerda Boaz.^&#42;4^

[NOTE]
====
. Ou: “a sul”.
. Ou: “a norte”.
. Que significa “que ele [isto é, Jeová] estabeleça firmemente”.
. Que possivelmente significa “em força”.
====

'''

xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[Próximo Capítulo &#62;]