include::./index.adoc[]

[[v14-2-0]]
=== 2 Crónicas, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-2-1]]

^<<v14-2-1,1>>^ Salomão ordenou então que se construísse uma casa para o nome de Jeová e uma casa^&#42;1^ para o seu próprio reino.

[NOTE]
====
. Ou: “um palácio”.
====

[[v14-2-2]]

^<<v14-2-2,2>>^ Salomão recrutou 70 000 homens como trabalhadores comuns,^&#42;1^ 80 000 como cortadores de pedras nos montes e 3600 como supervisores.

[NOTE]
====
. Ou: “como carregadores”.
====

[[v14-2-3]]

^<<v14-2-3,3>>^ Além disso, Salomão mandou dizer a Hirão, rei de Tiro: “Faz por mim o mesmo que fizeste por David, meu pai, quando lhe forneceste madeira de cedro, para ele construir uma casa^&#42;1^ para morar.

[NOTE]
====
. Ou: “um palácio”.
====

[[v14-2-4]]

^<<v14-2-4,4>>^ Vou construir uma casa para o nome de Jeová, meu Deus, a fim de a santificar para ele, para queimar incenso perfumado diante dele, e também para apresentar regularmente os pães da proposição^&#42;1^ e fazer as ofertas queimadas, de manhã e ao anoitecer, nos sábados, nas luas novas e nas épocas festivas de Jeová, nosso Deus. Isto é uma obrigação permanente para Israel.

[NOTE]
====
. Ou: “pães dispostos em pilhas”.
====

[[v14-2-5]]

^<<v14-2-5,5>>^ A casa que vou construir será grandiosa, pois o nosso Deus é maior do que todos os outros deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ E quem seria capaz de lhe construir uma casa? Pois os céus, o céu dos céus, não o podem conter. Então, quem sou eu para lhe construir uma casa, a não ser que seja apenas um lugar para queimar^&#42;1^ sacrifícios diante dele?

[NOTE]
====
. Ou: “fazer fumegar”.
====

[[v14-2-7]]

^<<v14-2-7,7>>^ Agora, envia-me um artesão especializado em trabalhar o ouro, a prata, o cobre, o ferro, a lã roxa, a linha escarlate e a linha azul, e que saiba entalhar. Ele trabalhará em Judá e em Jerusalém com os meus artesãos especializados, que David, meu pai, providenciou.

[[v14-2-8]]

^<<v14-2-8,8>>^ Além disso, envia-me do Líbano madeira de cedro, de junípero e de sândalo, pois sei muito bem que os teus servos são experientes em cortar as árvores do Líbano. Os meus servos trabalharão com os teus servos

[[v14-2-9]]

^<<v14-2-9,9>>^ para me prepararem grandes quantidades de madeira, pois a casa que vou construir será extraordinariamente grande.

[[v14-2-10]]

^<<v14-2-10,10>>^ Fornecerei comida aos teus servos, os cortadores de madeira que cortam as árvores: 20 000 coros^&#42;1^ de trigo, 20 000 coros de cevada, 20 000 batos^&#42;2^ de vinho e 20 000 batos de azeite.”

[NOTE]
====
. Um coro equivalia a 220 l. Veja o Ap. B14.
. Um bato equivalia a 22 l. Veja o Ap. B14.
====

[[v14-2-11]]

^<<v14-2-11,11>>^ Em vista disso, Hirão, rei de Tiro, enviou por escrito a seguinte mensagem a Salomão: “Visto que Jeová ama o seu povo, fez-te rei sobre eles.”

[[v14-2-12]]

^<<v14-2-12,12>>^ Hirão também disse: “Louvado seja Jeová, o Deus de Israel, que fez os céus e a terra, por ter dado ao rei David um filho sábio, que tem prudência e entendimento, que construirá uma casa para Jeová e uma casa^&#42;1^ para o seu próprio reino.

[NOTE]
====
. Ou: “um palácio”.
====

[[v14-2-13]]

^<<v14-2-13,13>>^ Envio um artesão especializado e entendido, Hirão-Abi,

[[v14-2-14]]

^<<v14-2-14,14>>^ filho de uma mulher danita, e cujo pai era de Tiro. Ele é experiente em trabalhar o ouro, a prata, o cobre, o ferro, as pedras, a madeira, a lã roxa, a linha azul, o tecido fino e a linha escarlate. Ele sabe fazer todo o tipo de entalhes e executar todo o tipo de projetos que lhe forem dados. Ele trabalhará junto com os teus^&#42;1^ artesãos especializados e com os artesãos especializados do meu senhor David, teu pai.

[NOTE]
====
. Isto é, de Salomão.
====

[[v14-2-15]]

^<<v14-2-15,15>>^ E que o meu senhor envie aos seus servos o trigo, a cevada, o azeite e o vinho que prometeu.

[[v14-2-16]]

^<<v14-2-16,16>>^ Nós cortaremos árvores do Líbano, a quantidade que precisares, e vamos mandar-tas como jangadas pelo mar, até Jope; e vais levá-las para Jerusalém.”

[[v14-2-17]]

^<<v14-2-17,17>>^ A seguir, Salomão fez a contagem de todos os homens que eram residentes estrangeiros na terra de Israel, assim como David, seu pai, tinha feito, e o total foi de 153 600.

[[v14-2-18]]

^<<v14-2-18,18>>^ Assim, designou 70 000 deles como trabalhadores comuns,^&#42;1^ 80 000 como cortadores de pedras nos montes e 3600 como supervisores para fazer o povo trabalhar.

[NOTE]
====
. Ou: “como carregadores”.
====

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]