include::./index.adoc[]

[[v14-22-0]]
=== 2 Crónicas, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-22-1]]

^<<v14-22-1,1>>^ Então, os habitantes de Jerusalém fizeram do filho mais novo de Jeorão, Acazias, rei no seu lugar, pois o bando de saqueadores que tinha vindo com os árabes ao acampamento tinha matado todos os filhos mais velhos. Assim, Acazias, filho de Jeorão, começou a reinar em Judá.

[[v14-22-2]]

^<<v14-22-2,2>>^ Acazias tinha 22 anos de idade quando se tornou rei, e reinou durante um ano em Jerusalém. O nome da sua mãe era Atalia, neta^&#42;1^ de Onri.

[NOTE]
====
. Lit.: “filha”.
====

[[v14-22-3]]

^<<v14-22-3,3>>^ Acazias também andava nos caminhos da casa de Acabe, porque a sua mãe o aconselhava a fazer o que era mau.

[[v14-22-4]]

^<<v14-22-4,4>>^ E ele fazia o que era mau aos olhos de Jeová, assim como os da casa de Acabe; pois, tinham-se tornado seus conselheiros, após a morte do seu pai, para a ruína dele.

[[v14-22-5]]

^<<v14-22-5,5>>^ Seguiu o conselho deles e foi com Jeorão, filho de Acabe, rei de Israel, guerrear contra Hazael, rei da Síria, em Ramote-Gileade, onde os arqueiros feriram Jeorão.

[[v14-22-6]]

^<<v14-22-6,6>>^ Jeorão regressou a Jezreel para se recuperar dos ferimentos que lhe causaram em Ramá, quando lutou contra Hazael, rei da Síria.
E Acazias,^&#42;1^ filho de Jeorão, rei de Judá, desceu a Jezreel para visitar Jeorão, filho de Acabe, porque ele estava ferido.^&#42;2^

[NOTE]
====
. Alguns manuscritos hebraicos dizem “Azarias”.
. Ou: “doente”.
====

[[v14-22-7]]

^<<v14-22-7,7>>^ Contudo, através dessa visita a Jeorão, Deus causou a ruína de Acazias. Quando lá chegou, foi com Jeorão ao encontro de Jeú, neto^&#42;1^ de Ninsi, a quem Jeová tinha ungido para eliminar^&#42;2^ a casa de Acabe.

[NOTE]
====
. Lit.: “filho”.
. Lit.: “decepar”.
====

[[v14-22-8]]

^<<v14-22-8,8>>^ Quando Jeú começou a executar o julgamento contra a casa de Acabe, encontrou os príncipes de Judá e os filhos dos irmãos de Acazias, ajudantes de Acazias, e matou-os.

[[v14-22-9]]

^<<v14-22-9,9>>^ Depois, foi à procura de Acazias; os seus homens capturaram-no em Samaria, onde estava escondido, levaram-no a Jeú e mataram-no. A seguir, enterraram-no, pois disseram: “Ele é neto de Jeosafá, que procurou a Jeová de todo o coração.” Não havia ninguém da casa de Acazias que tivesse poder para governar o reino.

[[v14-22-10]]

^<<v14-22-10,10>>^ Quando Atalia, mãe de Acazias, viu que o seu filho tinha morrido, exterminou toda a linhagem real^&#42;1^ da casa de Judá.

[NOTE]
====
. Lit.: “toda a semente do reino”.
====

[[v14-22-11]]

^<<v14-22-11,11>>^ No entanto, Jeosabeate, filha do rei, tirou Jeoás, filho de Acazias, dentre os filhos do rei que iam ser mortos e escondeu-o num quarto com a sua ama. Jeosabeate, filha do rei Jeorão (ela era esposa do sacerdote Jeoiada e irmã de Acazias), conseguiu mantê-lo escondido de Atalia, de modo que ela não o matou.

[[v14-22-12]]

^<<v14-22-12,12>>^ Ele ficou escondido com eles na casa do verdadeiro Deus durante seis anos, enquanto Atalia reinava sobre o país.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]