include::./index.adoc[]

[[v14-32-0]]
=== 2 Crónicas, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois destas coisas e destes atos fiéis de Ezequias, Senaqueribe, rei da Assíria, veio e invadiu Judá. Cercou as cidades fortificadas decidido a invadi-las e a conquistá-las.

[[v14-32-2]]

^<<v14-32-2,2>>^ Quando Ezequias viu que Senaqueribe veio com a intenção de guerrear contra Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ ele decidiu, depois de consultar os seus príncipes e os seus guerreiros, bloquear as fontes de água fora da cidade, e eles apoiaram-no.

[[v14-32-4]]

^<<v14-32-4,4>>^ Foram reunidas muitas pessoas, e bloquearam todas as fontes e o ribeiro que fluía por aquela terra, pois disseram: “Porque é que os reis da Assíria deviam chegar aqui e encontrar uma grande quantidade de água?”

[[v14-32-5]]

^<<v14-32-5,5>>^ Além disso, com determinação, ele reconstruiu toda a muralha que tinha sido derrubada e ergueu torres sobre ela, e por fora construiu outra muralha. Também reparou o Aterro^&#42;1^ da Cidade de David e fabricou uma grande quantidade de armas^&#42;2^ e escudos.

[NOTE]
====
. Ou: “Milo”. Termo hebraico que significa “encher”.
. Ou: “armas de arremesso”.
====

[[v14-32-6]]

^<<v14-32-6,6>>^ Então, designou chefes militares sobre o povo, reuniu-os na praça do portão da cidade e encorajou-os,^&#42;1^ dizendo:

[NOTE]
====
. Lit.: “e falou-lhes ao coração”.
====

[[v14-32-7]]

^<<v14-32-7,7>>^ “Sejam corajosos e fortes. Não tenham medo nem fiquem apavorados por causa do rei da Assíria e de toda a multidão que está com ele, pois os que estão connosco são mais numerosos do que os que estão com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Do lado dele está um braço de carne,^&#42;1^ mas do nosso lado está Jeová, nosso Deus, para nos ajudar e para travar as nossas batalhas.” E o povo foi fortalecido pelas palavras de Ezequias, rei de Judá.

[NOTE]
====
. Ou: “a força humana”.
====

[[v14-32-9]]

^<<v14-32-9,9>>^ Depois disso, enquanto Senaqueribe, rei da Assíria, estava em Laquis com todo o seu exército,^&#42;1^ ele enviou os seus servos a Jerusalém, a Ezequias, rei de Judá, e a todos os de Judá que estavam em Jerusalém, para dizer:

[NOTE]
====
. Ou: “todo o seu poderio militar e esplendor”.
====

[[v14-32-10]]

^<<v14-32-10,10>>^ “Assim diz Senaqueribe, rei da Assíria: ‘Em que é que estão a confiar para permanecerem em Jerusalém enquanto ela está cercada?

[[v14-32-11]]

^<<v14-32-11,11>>^ Não veem que Ezequias vos está a enganar para morrerem à fome e à sede, ao dizer: “Jeová, nosso Deus, irá livrar-nos das mãos do rei da Assíria”?

[[v14-32-12]]

^<<v14-32-12,12>>^ Não foi este mesmo Ezequias quem removeu os altos sagrados e os altares do vosso Deus,^&#42;1^ e disse a Judá e a Jerusalém: “Devem curvar-se diante de um só altar e queimar nele os vossos sacrifícios”?

[NOTE]
====
. Lit.: “os altos sagrados e os altares dele”.
====

[[v14-32-13]]

^<<v14-32-13,13>>^ Não sabem o que eu e os meus antepassados fizemos a todos os povos das outras terras? Será que os deuses das nações dessas terras foram capazes de livrar a sua terra das minhas mãos?

[[v14-32-14]]

^<<v14-32-14,14>>^ Dentre todos os deuses destas nações que os meus antepassados entregaram à destruição,^&#42;1^ qual deles foi capaz de livrar o seu povo das minhas mãos, de modo que o vosso Deus seja capaz de vos livrar das minhas mãos?

[NOTE]
====
. Ou: “devotaram à destruição”. Veja o Glossário.
====

[[v14-32-15]]

^<<v14-32-15,15>>^ Agora, não deixem que Ezequias vos engane e iluda desta maneira! Não acreditem nele, pois nenhum deus de nenhuma nação ou reino foi capaz de livrar o seu povo das minhas mãos e das mãos dos meus antepassados. Quanto menos, então, o vosso Deus há de livrar-vos das minhas mãos!’”

[[v14-32-16]]

^<<v14-32-16,16>>^ Os servos dele falaram ainda mais contra Jeová, o verdadeiro Deus, e contra Ezequias, seu servo.

[[v14-32-17]]

^<<v14-32-17,17>>^ Ele também escreveu cartas para insultar a Jeová, o Deus de Israel, e para falar contra ele, dizendo: “Assim como os deuses das outras nações não foram capazes de livrar o seu povo das minhas mãos, o Deus de Ezequias também não livrará o seu povo das minhas mãos.”

[[v14-32-18]]

^<<v14-32-18,18>>^ Eles falavam em voz bem alta, no idioma dos judeus, ao povo de Jerusalém que estava sobre a muralha, para que ficassem com medo e apavorados, e assim conseguirem conquistar a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ Falavam contra o Deus de Jerusalém assim como falavam contra os deuses dos povos da terra, que são trabalho das mãos do homem.

[[v14-32-20]]

^<<v14-32-20,20>>^ Contudo, o rei Ezequias e o profeta Isaías, filho de Amoz, oravam sobre isto e clamavam aos céus por ajuda.

[[v14-32-21]]

^<<v14-32-21,21>>^ Então, Jeová enviou um anjo e eliminou todos os guerreiros valentes, líderes e chefes no acampamento do rei da Assíria. Por isso, ele voltou desonrado à sua própria terra. Mais tarde, entrou na casa^&#42;1^ do seu deus e ali alguns dos seus próprios filhos mataram-no com a espada.

[NOTE]
====
. Ou: “no templo”.
====

[[v14-32-22]]

^<<v14-32-22,22>>^ Portanto, Jeová salvou Ezequias e os habitantes de Jerusalém das mãos de Senaqueribe, rei da Assíria, e das mãos de todos os outros, e deu-lhes descanso de todos os inimigos ao seu redor.

[[v14-32-23]]

^<<v14-32-23,23>>^ E muitos traziam dádivas a Jeová em Jerusalém e coisas valiosas a Ezequias, rei de Judá, e ele passou a ser muito respeitado por todas as nações depois disso.

[[v14-32-24]]

^<<v14-32-24,24>>^ Naqueles dias, Ezequias ficou doente e estava à beira da morte. Assim, ele orou a Jeová, que lhe respondeu e lhe deu um sinal.^&#42;1^

[NOTE]
====
. Ou: “portento”.
====

[[v14-32-25]]

^<<v14-32-25,25>>^ Ezequias, porém, não demonstrou apreço pelo bem que lhe foi feito, pois o seu coração ficou arrogante, resultando em indignação contra ele e contra Judá e Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ No entanto, Ezequias humilhou-se e abandonou a arrogância do seu coração, ele e os habitantes de Jerusalém, e a indignação de Jeová não veio sobre eles nos dias de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ E Ezequias veio a ter riquezas e glória em abundância. Fez para si depósitos para prata, ouro, pedras preciosas, óleo de bálsamo, escudos e todos os objetos preciosos.

[[v14-32-28]]

^<<v14-32-28,28>>^ Também fez depósitos para as safras de cereais, de vinho novo e de azeite, além de divisórias nos estábulos para todos os tipos de animais de criação e abrigos para os rebanhos.

[[v14-32-29]]

^<<v14-32-29,29>>^ Também construiu cidades e adquiriu muitos animais de criação, ovelhas e bois, pois Deus deu-lhe muitíssimos bens.

[[v14-32-30]]

^<<v14-32-30,30>>^ Foi Ezequias quem bloqueou a nascente superior das águas de Giom e canalizou-as para baixo, para o oeste, até à Cidade de David. E Ezequias foi bem-sucedido em tudo o que fez.

[[v14-32-31]]

^<<v14-32-31,31>>^ No entanto, quando os príncipes de Babilónia enviaram porta-vozes para lhe perguntar acerca do sinal^&#42;1^ que tinha ocorrido no país, o verdadeiro Deus deixou-o agir sozinho, para o pôr à prova e saber tudo o que ele tinha no seu coração.

[NOTE]
====
. Ou: “portento”.
====

[[v14-32-32]]

^<<v14-32-32,32>>^ Os outros acontecimentos da história de Ezequias e os seus atos de amor leal estão escritos na visão do profeta Isaías, filho de Amoz, no Livro dos Reis de Judá e de Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ Por fim, Ezequias descansou com os seus antepassados, e enterraram-no na subida que levava às sepulturas dos filhos de David. Quando morreu, todo o Judá e os habitantes de Jerusalém o honraram. E Manassés, seu filho, tornou-se rei no seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]