include::./index.adoc[]

[[v14-19-0]]
=== 2 Crónicas, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-19-1]]

^<<v14-19-1,1>>^ E Jeosafá, rei de Judá, voltou são e salvo^&#42;1^ para a sua casa^&#42;2^ em Jerusalém.

[NOTE]
====
. Ou: “voltou em paz”.
. Ou: “o seu palácio”.
====

[[v14-19-2]]

^<<v14-19-2,2>>^ Jeú, filho de Hanani, o vidente,^&#42;1^ foi ao encontro do rei Jeosafá e disse-lhe: “É ao mau que o senhor deve ajudar, e é aos que odeiam a Jeová que deve amar? Por causa disso, Jeová está indignado consigo.

[NOTE]
====
. Veja o Glossário.
====

[[v14-19-3]]

^<<v14-19-3,3>>^ No entanto, há coisas boas em si, porque eliminou os postes sagrados^&#42;1^ do país e preparou o seu coração para^&#42;2^ procurar o verdadeiro Deus.”

[NOTE]
====
. Veja o Glossário.
. Ou: “e o seu coração está decidido a”.
====

[[v14-19-4]]

^<<v14-19-4,4>>^ Jeosafá continuou a morar em Jerusalém, e saiu novamente para visitar o povo, desde Berseba até à região montanhosa de Efraim, a fim de os trazer de volta para Jeová, o Deus dos seus antepassados.

[[v14-19-5]]

^<<v14-19-5,5>>^ Ele também designou juízes em todo o país, em cada uma de todas as cidades fortificadas de Judá.

[[v14-19-6]]

^<<v14-19-6,6>>^ E disse aos juízes: “Prestem atenção ao que fazem, pois não julgam para o homem, mas para Jeová; e ele está convosco quando julgam.

[[v14-19-7]]

^<<v14-19-7,7>>^ Agora, tenham temor de Jeová. Tenham cuidado com o que fazem, pois com Jeová, nosso Deus, não há injustiça, nem parcialidade, nem suborno.”

[[v14-19-8]]

^<<v14-19-8,8>>^ Jeosafá também designou em Jerusalém alguns levitas e sacerdotes, e alguns cabeças das casas paternas de Israel, para servirem como juízes para Jeová e para decidirem as causas dos habitantes de Jerusalém.

[[v14-19-9]]

^<<v14-19-9,9>>^ E ordenou-lhes: “Isto é o que devem fazer, com temor de Jeová, com fidelidade e de pleno coração:^&#42;1^

[NOTE]
====
. Ou: “de coração plenamente devotado”.
====

[[v14-19-10]]

^<<v14-19-10,10>>^ sempre que os vossos irmãos que moram em outras cidades trouxerem uma causa que envolva derramamento de sangue ou uma questão sobre uma lei, um mandamento, decretos ou decisões judiciais, devem aconselhá-los para que eles não se tornem culpados perante Jeová; caso contrário, ele ficará indignado convosco e com os vossos irmãos. Isto é o que devem fazer para não se tornarem culpados.

[[v14-19-11]]

^<<v14-19-11,11>>^ Aqui está Amarias, o principal sacerdote, que será o vosso encarregado em todos os assuntos relacionados com o serviço de Jeová. Zebadias, filho de Ismael, será o líder da casa de Judá em todos os assuntos relacionados com o rei. E os levitas irão servir-vos como oficiais. Sejam fortes e ajam, e que Jeová esteja com os que fizerem o que é bom.”^&#42;1^

[NOTE]
====
. Ou: “com o que é bom”.
====

'''

xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[&#60; Capítulo Anterior] | <<v14-19-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[Próximo Capítulo &#62;]