include::./index.adoc[]

[[v14-28-0]]
=== 2 Crónicas, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha 20 anos de idade quando se tornou rei, e reinou durante 16 anos em Jerusalém. Ele não fez o que era certo aos olhos de Jeová, como David, seu antepassado, tinha feito.

[[v14-28-2]]

^<<v14-28-2,2>>^ Em vez disso, andou no caminho dos reis de Israel e fez até mesmo estátuas de metal^&#42;1^ dos baalins.

[NOTE]
====
. Ou: “estátuas fundidas”.
====

[[v14-28-3]]

^<<v14-28-3,3>>^ Também fez fumo sacrificial no vale do Filho de Hinom^&#42;1^ e queimou os seus filhos no fogo, imitando as práticas detestáveis das nações que Jeová tinha expulsado de diante dos israelitas.

[NOTE]
====
. Veja o Glossário, “Geena”.
====

[[v14-28-4]]

^<<v14-28-4,4>>^ Além disso, oferecia sacrifícios e fazia fumo sacrificial nos altos sagrados, nas colinas e debaixo de todas as árvores frondosas.

[[v14-28-5]]

^<<v14-28-5,5>>^ Por isso, Jeová, seu Deus, entregou-o nas mãos do rei da Síria, de modo que o derrotaram e levaram um grande número de cativos para Damasco. Ele também foi entregue nas mãos do rei de Israel, que o atingiu com uma grande matança.

[[v14-28-6]]

^<<v14-28-6,6>>^ Num só dia, Peca, filho de Remalias, matou em Judá 120 000 homens, todos valentes, porque tinham abandonado a Jeová, o Deus dos seus antepassados.

[[v14-28-7]]

^<<v14-28-7,7>>^ E Zicri, um guerreiro efraimita, matou Maaseias, filho do rei, Azricão, o encarregado do palácio,^&#42;1^ e Elcana, o segundo depois do rei.

[NOTE]
====
. Lit.: “da casa”.
====

[[v14-28-8]]

^<<v14-28-8,8>>^ Além disso, os israelitas levaram dentre os seus irmãos 200 000 cativos — mulheres, filhos e filhas —, também se apoderaram de uma grande quantidade de despojo e levaram-no para Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ Contudo, um profeta de Jeová chamado Odede estava lá. Ele foi ao encontro do exército que estava a chegar a Samaria e disse-lhes: “Vejam! Jeová, o Deus dos vossos antepassados, estava zangado com Judá; foi por isso que os entregou nas vossas mãos. Mas vocês mataram-nos com uma fúria que chegou aos céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ E agora pretendem fazer do povo de Judá e de Jerusalém vossos servos e servas. Mas será que vocês também não são culpados diante de Jeová, vosso Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Agora, escutem-me e devolvam os cativos que fizeram entre os vossos irmãos, pois a ira ardente de Jeová está contra vocês.”

[[v14-28-12]]

^<<v14-28-12,12>>^ Em vista disso, alguns dos chefes dos efraimitas, a saber, Azarias, filho de Jeoanã, Berequias, filho de Mesilemote, Jeizquias, filho de Salum, e Amasa, filho de Hadlai, confrontaram os que estavam a chegar da campanha militar,

[[v14-28-13]]

^<<v14-28-13,13>>^ dizendo-lhes: “Não tragam os cativos para cá, pois isso irá tornar-nos culpados diante de Jeová. A nossa culpa já é grande, e há ira ardente contra Israel, mas o que pretendem fazer vai aumentar os nossos pecados e a nossa culpa.”

[[v14-28-14]]

^<<v14-28-14,14>>^ Assim, os soldados armados entregaram os cativos e o despojo aos príncipes e a toda a congregação.

[[v14-28-15]]

^<<v14-28-15,15>>^ A seguir, os homens designados por nome pegaram nos cativos e forneceram roupas do despojo a todos os que estavam nus. Vestiram-nos e deram-lhes sandálias, comida, bebida e óleo para a pele. Além disso, transportaram em jumentos os que estavam fracos e levaram-nos aos seus irmãos em Jericó, a cidade das palmeiras. Depois, voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo, o rei Acaz pediu ajuda aos reis da Assíria.

[[v14-28-17]]

^<<v14-28-17,17>>^ E os edomitas mais uma vez invadiram e atacaram Judá, e levaram consigo cativos.

[[v14-28-18]]

^<<v14-28-18,18>>^ Os filisteus também atacaram as cidades da Sefelá e do Neguebe, em Judá, e tomaram Bete-Semes, Aijalom, Gederote, Soco e as suas aldeias dependentes,^&#42;1^ Timná e as suas aldeias dependentes, e Ginzo e as suas aldeias dependentes; e eles estabeleceram-se ali.

[NOTE]
====
. Ou: “ao redor”.
====

[[v14-28-19]]

^<<v14-28-19,19>>^ Jeová humilhou Judá por causa de Acaz, rei de Israel, pois tinha deixado Judá ficar sem controlo, resultando em muita infidelidade a Jeová.

[[v14-28-20]]

^<<v14-28-20,20>>^ Tilgate-Pilneser, rei da Assíria, em vez de o apoiar, por fim veio contra ele e causou-lhe aflição.

[[v14-28-21]]

^<<v14-28-21,21>>^ Acaz tinha saqueado a casa de Jeová, a casa^&#42;1^ do rei e as casas dos príncipes e dado um presente ao rei da Assíria, mas isso não lhe foi de ajuda.

[NOTE]
====
. Ou: “o palácio”.
====

[[v14-28-22]]

^<<v14-28-22,22>>^ E, durante a sua aflição, o rei Acaz agiu de modo ainda mais infiel com Jeová.

[[v14-28-23]]

^<<v14-28-23,23>>^ Começou a oferecer sacrifícios aos deuses de Damasco, que o tinham derrotado, e disse: “Visto que os deuses dos reis da Síria os ajudam, irei oferecer-lhes sacrifícios para que me ajudem.” Eles, porém, levaram-no a ele e a todo o Israel a tropeçar.

[[v14-28-24]]

^<<v14-28-24,24>>^ Além disso, Acaz juntou os utensílios da casa do verdadeiro Deus e cortou-os em pedaços, depois fechou as portas da casa de Jeová e fez para si altares em cada esquina de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ E, em todas as cidades de Judá, fez altos sagrados para fazer fumo sacrificial a outros deuses, e ofendeu a Jeová, o Deus dos seus antepassados.

[[v14-28-26]]

^<<v14-28-26,26>>^ Os outros acontecimentos da sua história, todas as suas ações, do início ao fim, estão escritos no Livro dos Reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Por fim, Acaz descansou com os seus antepassados, e enterraram-no na cidade, em Jerusalém, pois não o levaram às sepulturas dos reis de Israel. E Ezequias, seu filho, tornou-se rei no seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]