include::./index.adoc[]

[[v14-31-0]]
=== 2 Crónicas, 31
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-31-1]]

^<<v14-31-1,1>>^ Assim que acabaram tudo isto, todos os israelitas que estavam presentes foram às cidades de Judá e despedaçaram as colunas sagradas, cortaram os postes sagrados^&#42;1^ e demoliram os altos sagrados e os altares em todo o Judá e Benjamim, também em Efraim e Manassés, até terem destruído tudo. Depois, todos os israelitas voltaram para as suas cidades, cada um para a sua propriedade.

[NOTE]
====
. Veja o Glossário.
====

[[v14-31-2]]

^<<v14-31-2,2>>^ Então, Ezequias designou os sacerdotes nas suas turmas e os levitas nas suas turmas — sacerdotes e levitas, cada um para o seu serviço — para fazerem as ofertas queimadas e os sacrifícios de participação em comum, para prestarem serviço e para darem graças e louvores nos portões dos pátios^&#42;1^ de Jeová.

[NOTE]
====
. Lit.: “acampamentos”.
====

[[v14-31-3]]

^<<v14-31-3,3>>^ Parte dos próprios bens do rei era dada para as ofertas queimadas, incluindo as ofertas da manhã e do anoitecer, e também as ofertas queimadas dos sábados, das luas novas e das festividades, conforme está escrito na Lei de Jeová.

[[v14-31-4]]

^<<v14-31-4,4>>^ Além disso, ele ordenou ao povo que morava em Jerusalém que desse a porção devida aos sacerdotes e aos levitas, para que se pudessem dedicar integralmente^&#42;1^ à lei de Jeová.

[NOTE]
====
. Ou: “aderir estritamente”.
====

[[v14-31-5]]

^<<v14-31-5,5>>^ Assim que essa ordem foi dada, os israelitas trouxeram uma grande quantidade de primícias dos cereais, do vinho novo, do azeite, do mel e de todos os produtos do campo; trouxeram em abundância a décima parte de tudo.

[[v14-31-6]]

^<<v14-31-6,6>>^ E o povo de Israel e de Judá que morava nas cidades de Judá também trouxe a décima parte dos bois e das ovelhas, e a décima parte das coisas sagradas, que foram santificadas para Jeová, seu Deus. Eles trouxeram-nas e juntaram-nas em muitos montes.

[[v14-31-7]]

^<<v14-31-7,7>>^ No terceiro mês, começaram a amontoar as contribuições e terminaram no sétimo mês.

[[v14-31-8]]

^<<v14-31-8,8>>^ Quando Ezequias e os príncipes chegaram e viram os montes, louvaram a Jeová e abençoaram o seu povo Israel.

[[v14-31-9]]

^<<v14-31-9,9>>^ Ezequias perguntou aos sacerdotes e aos levitas sobre os montes,

[[v14-31-10]]

^<<v14-31-10,10>>^ e Azarias, o principal sacerdote, da casa de Zadoque, respondeu-lhe: “Desde que começaram a trazer as contribuições para a casa de Jeová, o povo tem comido até ficar satisfeito e ainda sobra muito, pois Jeová tem abençoado o seu povo. E sobra esta grande quantidade.”

[[v14-31-11]]

^<<v14-31-11,11>>^ Portanto, Ezequias ordenou-lhes que preparassem depósitos^&#42;1^ na casa de Jeová, e eles prepararam-nos.

[NOTE]
====
. Ou: “refeitórios”.
====

[[v14-31-12]]

^<<v14-31-12,12>>^ Traziam fielmente as contribuições, as décimas partes^&#42;1^ e as coisas sagradas; Conanias, o levita, foi designado como supervisor de todas estas coisas, e o seu irmão Simei, era o segundo depois dele.

[NOTE]
====
. Ou: “os dízimos”.
====

[[v14-31-13]]

^<<v14-31-13,13>>^ Jeiel, Azazias, Naate, Asael, Jerimote, Jozabade, Eliel, Ismaquias, Maate e Benaia eram assistentes de Conanias e de Simei, seu irmão, por ordem do rei Ezequias; e Azarias era o supervisor da casa do verdadeiro Deus.

[[v14-31-14]]

^<<v14-31-14,14>>^ E Coré, filho de Imná, o porteiro levita do lado leste, estava encarregado das ofertas voluntárias do verdadeiro Deus; ele distribuía a contribuição feita para Jeová e as coisas santíssimas.

[[v14-31-15]]

^<<v14-31-15,15>>^ E sob a sua supervisão, nas cidades dos sacerdotes, estavam Éden, Miniamim, Jesua, Semaías, Amarias e Secanias. Eles ocupavam cargos de confiança para distribuir por igual as porções aos seus irmãos nas suas turmas, tanto ao grande como ao pequeno.

[[v14-31-16]]

^<<v14-31-16,16>>^ Além desta distribuição, havia também a distribuição feita aos do sexo masculino que vinham diariamente servir na casa de Jeová e realizar os deveres das suas turmas. O seu registo genealógico incluía os de três anos de idade para cima.

[[v14-31-17]]

^<<v14-31-17,17>>^ O registo genealógico dos sacerdotes era feito segundo as suas casas paternas, assim como o dos levitas de 20 anos de idade para cima, segundo os deveres das suas turmas.

[[v14-31-18]]

^<<v14-31-18,18>>^ O registo genealógico dos levitas incluía todas as suas esposas, filhos e filhas, até mesmo as crianças, toda a sua congregação — pois eles mantinham-se santificados para o que é santo por causa do seu cargo de confiança —,

[[v14-31-19]]

^<<v14-31-19,19>>^ incluía também os descendentes de Arão, os sacerdotes que moravam nos campos de pastagem ao redor das suas cidades. Em todas as cidades, homens tinham sido designados por nome para dar porções a todos os do sexo masculino da família sacerdotal e a todos os incluídos no registo genealógico dos levitas.

[[v14-31-20]]

^<<v14-31-20,20>>^ Ezequias fez isto em todo o Judá, e continuou a fazer o que era bom e certo aos olhos de Jeová, seu Deus, e foi-lhe fiel.

[[v14-31-21]]

^<<v14-31-21,21>>^ E todo o trabalho que realizou para servir^&#42;1^ ao seu Deus, quer no serviço da casa do verdadeiro Deus, quer em relação à Lei e ao mandamento, fez de todo o coração, e foi bem-sucedido.

[NOTE]
====
. Ou: “buscar”.
====

'''

xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[&#60; Capítulo Anterior] | <<v14-31-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[Próximo Capítulo &#62;]