include::./index.adoc[]

[[v14-24-0]]
=== 2 Crónicas, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-24-1]]

^<<v14-24-1,1>>^ Jeoás tinha sete anos de idade quando se tornou rei, e reinou durante 40 anos em Jerusalém. O nome da sua mãe era Zíbia, de Berseba.

[[v14-24-2]]

^<<v14-24-2,2>>^ Jeoás fez o que era certo aos olhos de Jeová durante todos os dias de Jeoiada, o sacerdote.

[[v14-24-3]]

^<<v14-24-3,3>>^ Jeoiada escolheu duas esposas para Jeoás, e ele tornou-se pai de filhos e de filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Depois, Jeoás teve o desejo de coração de restaurar a casa de Jeová.

[[v14-24-5]]

^<<v14-24-5,5>>^ Portanto, reuniu os sacerdotes e os levitas e disse-lhes: “Vão às cidades de Judá e recolham dinheiro de todo o Israel para fazer reparações na casa do vosso Deus, de ano em ano; devem agir depressa a respeito deste assunto.” Os levitas, porém, não agiram depressa.

[[v14-24-6]]

^<<v14-24-6,6>>^ Por isso, o rei chamou Jeoiada, o principal sacerdote, e perguntou-lhe: “Porque é que não exigiste que os levitas trouxessem de Judá e de Jerusalém o imposto sagrado determinado por Moisés, o servo de Jeová, o imposto sagrado da congregação de Israel para a tenda do Testemunho?

[[v14-24-7]]

^<<v14-24-7,7>>^ Pois os filhos de Atalia, aquela mulher má, arrombaram a casa do verdadeiro Deus e usaram todas as coisas sagradas da casa de Jeová na adoração dos baalins.”

[[v14-24-8]]

^<<v14-24-8,8>>^ Então, por ordem do rei, fizeram um cofre e puseram-no do lado de fora do portão da casa de Jeová.

[[v14-24-9]]

^<<v14-24-9,9>>^ Depois, fizeram uma proclamação em todo o Judá e Jerusalém, para que trouxessem a Jeová o imposto sagrado que Moisés, o servo do verdadeiro Deus, tinha determinado a Israel no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Todos os príncipes e todo o povo se alegraram; eles traziam contribuições e colocavam-nas no cofre, até ficar cheio.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “até todos terem dado”.
====

[[v14-24-11]]

^<<v14-24-11,11>>^ Sempre que os levitas traziam o cofre para o entregar ao rei, e viam que havia nele muito dinheiro, o secretário do rei e o assistente do sacerdote principal vinham, esvaziavam o cofre e levavam-no de volta para o seu lugar. Faziam isso todos os dias, e recolhiam muito dinheiro.

[[v14-24-12]]

^<<v14-24-12,12>>^ Em seguida, o rei e Jeoiada davam o dinheiro aos que supervisionavam a obra relacionada com o serviço da casa de Jeová, e estes contratavam cortadores de pedras e artesãos para restaurar a casa de Jeová, assim como trabalhadores em ferro e em cobre para reparar a casa de Jeová.

[[v14-24-13]]

^<<v14-24-13,13>>^ Os que supervisionavam a obra começaram o trabalho, e a obra de restauração avançou sob a sua supervisão; eles restauraram a casa do verdadeiro Deus ao seu estado original e reforçaram-na.

[[v14-24-14]]

^<<v14-24-14,14>>^ E, assim que acabaram, levaram o dinheiro que tinha sobrado ao rei e a Jeoiada, e usaram-no para fazer utensílios para a casa de Jeová, utensílios para o serviço do templo e para fazer ofertas, assim como taças e outros utensílios de ouro e de prata. E sacrifícios queimados eram oferecidos regularmente na casa de Jeová durante todos os dias de Jeoiada.

[[v14-24-15]]

^<<v14-24-15,15>>^ Depois de uma vida longa e satisfatória,^&#42;1^ Jeoiada morreu; ele tinha 130 anos de idade por ocasião da sua morte.

[NOTE]
====
. Lit.: “idoso e cheio de dias”.
====

[[v14-24-16]]

^<<v14-24-16,16>>^ Portanto, enterraram-no na Cidade de David, com os reis, porque tinha feito o bem em Israel, a respeito do verdadeiro Deus e da Sua casa.

[[v14-24-17]]

^<<v14-24-17,17>>^ Após a morte de Jeoiada, os príncipes de Judá vieram e curvaram-se diante do rei, e o rei escutou-os.

[[v14-24-18]]

^<<v14-24-18,18>>^ Eles abandonaram a casa de Jeová, o Deus dos seus antepassados, e começaram a servir os postes sagrados^&#42;1^ e os ídolos, de modo que a ira de Deus veio^&#42;2^ contra Judá e Jerusalém por causa do seu pecado.

[NOTE]
====
. Veja o Glossário.
. Lit.: “houve ira”.
====

[[v14-24-19]]

^<<v14-24-19,19>>^ Ele enviava-lhes profetas para os trazer de volta a Jeová, e os profetas avisavam-nos,^&#42;1^ mas eles recusaram-se a ouvir.

[NOTE]
====
. Ou: “davam testemunho contra eles”.
====

[[v14-24-20]]

^<<v14-24-20,20>>^ O espírito de Deus veio sobre^&#42;1^ Zacarias, filho de Jeoiada, o sacerdote, e ele ficou de pé num lugar mais alto do que o povo e disse-lhes: “Assim diz o verdadeiro Deus: ‘Porque é que estão a violar os mandamentos de Jeová? Vocês não serão bem-sucedidos! Visto que abandonaram a Jeová, ele também vos abandonará.’”

[NOTE]
====
. Lit.: “revestiu”.
====

[[v14-24-21]]

^<<v14-24-21,21>>^ Contudo, conspiraram contra ele e, por ordem do rei, apedrejaram-no no pátio da casa de Jeová.

[[v14-24-22]]

^<<v14-24-22,22>>^ Assim, o rei Jeoás não se lembrou do amor leal que Jeoiada, pai dele,^&#42;1^ lhe tinha demonstrado e matou-lhe o filho, que disse quando estava a morrer: “Que Jeová veja e te faça prestar contas.”

[NOTE]
====
. Isto é, pai de Zacarias.
====

[[v14-24-23]]

^<<v14-24-23,23>>^ No começo do ano,^&#42;1^ o exército sírio veio contra Jeoás, e invadiram Judá e Jerusalém. Então, eliminaram todos os príncipes do povo e enviaram todo o seu despojo ao rei de Damasco.

[NOTE]
====
. Lit.: “Na virada do ano”.
====

[[v14-24-24]]

^<<v14-24-24,24>>^ Embora o exército invasor dos sírios tivesse poucos homens, Jeová entregou-lhes um exército muito grande, porque eles tinham abandonado a Jeová, o Deus dos seus antepassados. Assim, eles^&#42;1^ executaram o julgamento em Jeoás.

[NOTE]
====
. Isto é, os sírios.
====

[[v14-24-25]]

^<<v14-24-25,25>>^ E, quando os sírios se foram embora, deixando-o gravemente ferido,^&#42;1^ os seus próprios servos conspiraram contra ele, porque ele tinha derramado o sangue dos filhos^&#42;2^ de Jeoiada, o sacerdote. Mataram-no na sua própria cama. Portanto, ele morreu e foi enterrado na Cidade de David, mas não o enterraram nas sepulturas dos reis.

[NOTE]
====
. Ou: “com muitas doenças”.
. Ou: “do filho”. Possivelmente o plural indica excelência.
====

[[v14-24-26]]

^<<v14-24-26,26>>^ Os que conspiraram contra Jeoás foram Zabade, filho de Simeate, a amonita, e Jeozabade, filho de Sinrite, a moabita.

[[v14-24-27]]

^<<v14-24-27,27>>^ Tudo o que se refere aos seus filhos, às muitas proclamações contra ele e à restauração^&#42;1^ da casa do verdadeiro Deus está registado nos escritos^&#42;2^ do Livro dos Reis. E Amazias, seu filho, tornou-se rei no seu lugar.

[NOTE]
====
. Lit.: “fundação”.
. Ou: “na explanação; no comentário”.
====

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]