include::./index.adoc[]

[[v14-7-0]]
=== 2 Crónicas, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-7-1]]

^<<v14-7-1,1>>^ Assim que Salomão acabou de orar, desceu fogo dos céus e consumiu a oferta queimada e os sacrifícios; e a glória de Jeová encheu a casa.

[[v14-7-2]]

^<<v14-7-2,2>>^ Os sacerdotes não conseguiram entrar na casa de Jeová, porque a glória de Jeová tinha enchido a casa de Jeová.

[[v14-7-3]]

^<<v14-7-3,3>>^ E todo o povo de Israel estava a olhar quando o fogo desceu e a glória de Jeová ficou sobre a casa, e eles curvaram-se e prostraram-se com o rosto por terra, sobre o pavimento, e agradeceram a Jeová, “pois ele é bom; o seu amor leal dura para sempre”.

[[v14-7-4]]

^<<v14-7-4,4>>^ Então, o rei e todo o povo ofereceram sacrifícios perante Jeová.

[[v14-7-5]]

^<<v14-7-5,5>>^ O rei Salomão apresentou como sacrifício 22 000 bois e 120 000 ovelhas. Assim, o rei e todo o povo inauguraram a casa do verdadeiro Deus.

[[v14-7-6]]

^<<v14-7-6,6>>^ Os sacerdotes estavam de pé nos seus postos, assim como os levitas que tinham os instrumentos musicais usados para acompanhar os cânticos a Jeová. (O rei David tinha feito esses instrumentos para agradecer a Jeová — “pois o seu amor leal dura para sempre” — na época em que David dava louvor com eles.^&#42;1^) E os sacerdotes tocavam alto as trombetas de frente para os levitas, enquanto todos os israelitas estavam de pé.

[NOTE]
====
. Possivelmente, refere-se aos levitas.
====

[[v14-7-7]]

^<<v14-7-7,7>>^ Depois, Salomão santificou o centro do pátio que ficava diante da casa de Jeová, pois teve de oferecer ali as ofertas queimadas e a gordura dos sacrifícios de participação em comum, porque o altar de cobre que Salomão tinha feito não era suficientemente grande para conter os sacrifícios queimados, as ofertas de cereais e a gordura.

[[v14-7-8]]

^<<v14-7-8,8>>^ Naquela ocasião, Salomão realizou a festividade durante sete dias, com todo o Israel, uma congregação muito grande, vinda desde Lebo-Hamate^&#42;1^ até à torrente^&#42;2^ do Egito.

[NOTE]
====
. Ou: “a entrada de Hamate”.
. Ou: “ao uádi”. Veja o Glossário.
====

[[v14-7-9]]

^<<v14-7-9,9>>^ E no oitavo dia^&#42;1^ realizaram uma assembleia solene, depois de terem celebrado a inauguração do altar durante sete dias e a festividade durante sete dias.

[NOTE]
====
. O dia a seguir à festividade, ou o décimo quinto dia.
====

[[v14-7-10]]

^<<v14-7-10,10>>^ No vigésimo terceiro dia do sétimo mês, ele dispensou o povo, e eles foram para as suas casas alegres e com o coração contente, por causa da bondade que Jeová tinha mostrado a David, a Salomão e a Israel, seu povo.

[[v14-7-11]]

^<<v14-7-11,11>>^ Assim, Salomão terminou a casa de Jeová e a casa^&#42;1^ do rei; e Salomão foi bem-sucedido em tudo o que planeou fazer a respeito da casa de Jeová e da sua própria casa.

[NOTE]
====
. Ou: “o palácio”.
====

[[v14-7-12]]

^<<v14-7-12,12>>^ A seguir, Jeová apareceu a Salomão durante a noite e disse-lhe: “Ouvi a tua oração e escolhi este lugar para mim como casa de sacrifícios.

[[v14-7-13]]

^<<v14-7-13,13>>^ Se eu fechar os céus e não houver chuva, se ordenar aos gafanhotos que devorem a vegetação do país, e se enviar uma peste contra o meu povo,

[[v14-7-14]]

^<<v14-7-14,14>>^ então, se o meu povo, que leva o meu nome, se humilhar, orar, procurar a minha face e abandonar os seus maus caminhos, eu ouvirei desde os céus, perdoarei o seu pecado e curarei a sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ Agora, os meus olhos estarão abertos e os meus ouvidos estarão atentos à oração feita neste lugar.

[[v14-7-16]]

^<<v14-7-16,16>>^ Eu escolhi e santifiquei esta casa, para que o meu nome esteja nela de modo permanente, e os meus olhos e o meu coração estarão sempre nela.

[[v14-7-17]]

^<<v14-7-17,17>>^ “Se tu andares diante de mim assim como andou David, teu pai, por fazeres tudo o que te ordenei, e, se obedeceres aos meus decretos e às minhas decisões judiciais,

[[v14-7-18]]

^<<v14-7-18,18>>^ então, estabelecerei o trono do teu reinado, assim como fiz um pacto com David, teu pai, dizendo: ‘Haverá sempre um descendente teu a governar Israel.’

[[v14-7-19]]

^<<v14-7-19,19>>^ Contudo, se vocês se desviarem e abandonarem os decretos e os mandamentos que coloquei à vossa frente, e forem servir outros deuses e se curvarem diante deles,

[[v14-7-20]]

^<<v14-7-20,20>>^ arrancarei Israel da terra que lhes dei, lançarei para longe da minha vista esta casa que santifiquei para o meu nome, e farei dela alvo de desprezo^&#42;1^ e motivo de riso entre todos os povos.

[NOTE]
====
. Lit.: “um provérbio”.
====

[[v14-7-21]]

^<<v14-7-21,21>>^ E esta casa irá tornar-se um montão de ruínas. Todo aquele que passar por ela olhará espantado e perguntará: ‘Porque é que Jeová fez isto a esta terra e a esta casa?’

[[v14-7-22]]

^<<v14-7-22,22>>^ Então, responderão: ‘Foi porque abandonaram a Jeová, o Deus dos seus antepassados, que os tirou da terra do Egito, e apegaram-se a outros deuses, curvaram-se diante deles e serviram-nos. Foi por isso que lhes trouxe toda esta calamidade.’”

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]