include::./index.adoc[]

[[v14-13-0]]
=== 2 Crónicas, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v14-13-1]]

^<<v14-13-1,1>>^ No décimo oitavo ano do rei Jeroboão, Abias tornou-se rei sobre Judá.

[[v14-13-2]]

^<<v14-13-2,2>>^ Ele reinou durante três anos em Jerusalém. O nome da sua mãe era Micaías, filha de Uriel de Gibeá. E houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Assim, Abias foi à guerra com um exército de 400 000 guerreiros valentes e treinados.^&#42;1^ E Jeroboão pôs-se em formação de batalha contra ele com 800 000 homens treinados,^&#42;2^ guerreiros valentes.

[NOTE]
====
. Lit.: “escolhidos”.
. Lit.: “escolhidos”.
====

[[v14-13-4]]

^<<v14-13-4,4>>^ Abias ficou de pé no monte Zemaraim, que fica na região montanhosa de Efraim, e disse: “Ouçam-me, ó Jeroboão e todo o Israel.

[[v14-13-5]]

^<<v14-13-5,5>>^ Não sabem que Jeová, o Deus de Israel, deu a David um reino sobre Israel para sempre, a ele e aos seus filhos, através de um pacto de sal?^&#42;1^

[NOTE]
====
. Isto é, um pacto duradouro e imutável.
====

[[v14-13-6]]

^<<v14-13-6,6>>^ Contudo, Jeroboão, filho de Nebate, servo de Salomão, filho de David, levantou-se e rebelou-se contra o seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ E homens vadios, imprestáveis, juntaram-se a ele. E eles mostraram-se superiores a Roboão, filho de Salomão, pois Roboão era jovem e inseguro, e não lhes pôde resistir.

[[v14-13-8]]

^<<v14-13-8,8>>^ “E agora vocês pensam que se podem sair bem contra o reino de Jeová nas mãos dos filhos de David só porque são uma grande multidão e têm os bezerros de ouro que Jeroboão fez para serem os vossos deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Não foram vocês que expulsaram os sacerdotes de Jeová, os descendentes de Arão, e os levitas, e que designaram os vossos próprios sacerdotes, assim como os povos das outras terras? Qualquer um que chegasse com^&#42;1^ um novilho e sete carneiros podia tornar-se sacerdote de ídolos que não são deuses.

[NOTE]
====
. Lit.: “chegasse para encher a sua mão com”.
====

[[v14-13-10]]

^<<v14-13-10,10>>^ Quanto a nós, Jeová é o nosso Deus, e nós não o abandonámos; nossos sacerdotes, os descendentes de Arão, estão a servir a Jeová, e os levitas ajudam-nos no trabalho.

[[v14-13-11]]

^<<v14-13-11,11>>^ Eles queimam ofertas queimadas a Jeová todos os dias, de manhã e ao anoitecer, e também incenso perfumado. Os pães da proposição^&#42;1^ estão sobre a mesa de ouro puro, e eles acendem sempre o candelabro de ouro e as suas lâmpadas ao anoitecer. Pois nós estamos a cuidar da nossa responsabilidade para com Jeová, nosso Deus, mas vocês abandonaram-no.

[NOTE]
====
. Ou: “pães dispostos em pilhas”.
====

[[v14-13-12]]

^<<v14-13-12,12>>^ Agora vejam! O verdadeiro Deus está connosco, liderando-nos, e também os seus sacerdotes com as trombetas, para dar o toque de guerra contra vocês. Ó homens de Israel, não lutem contra Jeová, o Deus dos vossos antepassados, pois não serão bem-sucedidos!”

[[v14-13-13]]

^<<v14-13-13,13>>^ Contudo, Jeroboão armou uma emboscada atrás deles, de modo que o exército de Jeroboão estava em frente a Judá e os homens da emboscada estavam atrás.

[[v14-13-14]]

^<<v14-13-14,14>>^ Quando os homens de Judá se viraram, perceberam que estavam a ser atacados tanto pela frente como pela retaguarda. Consequentemente, começaram a clamar a Jeová, enquanto os sacerdotes tocavam alto as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ Os homens de Judá deram um grito de guerra. Quando os homens de Judá deram o grito de guerra, o verdadeiro Deus derrotou Jeroboão e todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os israelitas fugiram diante de Judá, e Deus entregou-os nas mãos deles.

[[v14-13-17]]

^<<v14-13-17,17>>^ Abias e os seus homens realizaram uma grande matança, de modo que 500 000 homens treinados^&#42;1^ de Israel morreram.

[NOTE]
====
. Lit.: “escolhidos”.
====

[[v14-13-18]]

^<<v14-13-18,18>>^ Assim, os homens de Israel foram humilhados naquela ocasião, mas os homens de Judá mostraram-se superiores, porque confiaram^&#42;1^ em Jeová, o Deus dos seus antepassados.

[NOTE]
====
. Lit.: “se apoiaram”.
====

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias continuou a perseguir Jeroboão e conquistou-lhe cidades: Betel e as suas aldeias dependentes,^&#42;1^ Jesana e as suas aldeias dependentes, e Efrom e as suas aldeias dependentes.

[NOTE]
====
. Ou: “ao redor”.
====

[[v14-13-20]]

^<<v14-13-20,20>>^ E Jeroboão nunca mais recuperou o seu poder nos dias de Abias; depois Jeová golpeou-o, e ele morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias, porém, ficou mais forte. Com o tempo teve 14 esposas e tornou-se pai de 22 filhos e 16 filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ E os outros acontecimentos da história de Abias, as suas ações e as suas palavras, estão registados nos escritos^&#42;1^ do profeta Ido.

[NOTE]
====
. Ou: “na explanação; no comentário”.
====

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]