include::./index.adoc[]

[[v2-3-0]]
=== Êxodo, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-3-1]]

^<<v2-3-1,1>>^ Moisés tornou-se pastor do rebanho de Jetro, seu sogro, sacerdote de Midiã. Quando estava a conduzir o rebanho para o lado oeste do deserto, chegou a Horebe, o monte do verdadeiro Deus.

[[v2-3-2]]

^<<v2-3-2,2>>^ Então, o anjo de Jeová apareceu-lhe numa chama de fogo no meio de um espinheiro. Enquanto Moisés olhava para o espinheiro, viu que ele estava em chamas, mas não se consumia.

[[v2-3-3]]

^<<v2-3-3,3>>^ Por isso, Moisés disse: “Vou aproximar-me para examinar esta vista incomum e descobrir por que motivo o espinheiro não se queima.”

[[v2-3-4]]

^<<v2-3-4,4>>^ Quando Jeová viu que ele se aproximava para observar, chamou-o do meio do espinheiro e disse: “Moisés! Moisés!” Ele respondeu: “Aqui estou eu.”

[[v2-3-5]]

^<<v2-3-5,5>>^ Então, Deus disse: “Não te aproximes mais. Tira as sandálias dos pés, porque o lugar que estás a pisar é solo sagrado.”

[[v2-3-6]]

^<<v2-3-6,6>>^ Ele continuou: “Eu sou o Deus do teu pai, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó.” Então, Moisés escondeu o rosto, porque estava com medo de olhar para o verdadeiro Deus.

[[v2-3-7]]

^<<v2-3-7,7>>^ Jeová acrescentou: “Certamente vi a aflição do meu povo, que está no Egito, e ouvi o seu clamor por causa daqueles que os obrigam a trabalhar; e sei muito bem o quanto estão a sofrer.

[[v2-3-8]]

^<<v2-3-8,8>>^ Vou descer para libertá-los das mãos dos egípcios e levá-los para fora daquela terra, para uma terra boa e espaçosa, uma terra que mana leite e mel, o território dos cananeus, dos hititas, dos amorreus, dos perizeus, dos heveus e dos jebuseus.

[[v2-3-9]]

^<<v2-3-9,9>>^ Agora, o clamor do povo de Israel chegou até mim, e eu vi também que os egípcios os oprimem cruelmente.

[[v2-3-10]]

^<<v2-3-10,10>>^ Vem, vou enviar-te ao Faraó, e tirarás o meu povo, os israelitas, do Egito.”

[[v2-3-11]]

^<<v2-3-11,11>>^ No entanto, Moisés disse ao verdadeiro Deus: “Quem sou eu para ir até ao Faraó e tirar os israelitas do Egito?”

[[v2-3-12]]

^<<v2-3-12,12>>^ A isto, ele disse: “Estarei contigo e este é, para ti, o sinal de que fui eu quem te enviou: depois de teres tirado o povo do Egito, vocês servirão^&#42;1^ o verdadeiro Deus neste monte.”

[NOTE]
====
. Ou: “adorarão”.
====

[[v2-3-13]]

^<<v2-3-13,13>>^ Moisés, porém, disse ao verdadeiro Deus: “Suponhamos que eu vá ter com os israelitas e lhes diga: ‘O Deus dos vossos antepassados enviou-me a vocês’, e eles me perguntem: ‘Qual é o nome dele?’ O que lhes devo dizer?”

[[v2-3-14]]

^<<v2-3-14,14>>^ Deus disse então a Moisés: “Eu Vou Tornar-Me O Que Eu Me Decidir^&#42;1^ Tornar.”^&#42;2^ E acrescentou: “Isto é o que deves dizer aos israelitas: ‘“Eu Vou Tornar-Me” enviou-me a vocês.’”

[NOTE]
====
. Ou: “Quiser”.
. Ou: “Eu Mostrarei Ser O Que Eu Mostrar Ser.” Veja o Ap. A4.
====

[[v2-3-15]]

^<<v2-3-15,15>>^ Então, Deus disse mais uma vez a Moisés:
“Isto é o que deves dizer aos israelitas: ‘Jeová, o Deus dos vossos antepassados, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó enviou-me a vocês.’ Este é o meu nome para sempre, e é assim que serei lembrado de geração em geração.

[[v2-3-16]]

^<<v2-3-16,16>>^ Agora, vai, reúne os anciãos de Israel e diz-lhes: ‘Jeová, o Deus dos vossos antepassados, o Deus de Abraão, de Isaque e de Jacó, apareceu-me e disse: “Certamente, tenho-vos observado, bem como ao que estão a fazer convosco no Egito.

[[v2-3-17]]

^<<v2-3-17,17>>^ Por isso, digo: Vou tirar-vos da aflição que sofrem às mãos dos egípcios e levar-vos para a terra dos cananeus, dos hititas, dos amorreus, dos perizeus, dos heveus e dos jebuseus, para uma terra que mana leite e mel.”’

[[v2-3-18]]

^<<v2-3-18,18>>^ “Eles certamente escutarão a tua voz e irás ao rei do Egito com os anciãos de Israel. E vocês devem dizer-lhe: ‘Jeová, o Deus dos hebreus, falou connosco. Portanto, por favor, permita-nos fazer uma viagem de três dias pelo deserto para que possamos oferecer sacrifícios a Jeová, o nosso Deus.’

[[v2-3-19]]

^<<v2-3-19,19>>^ Mas sei muito bem que o rei do Egito não vos dará permissão para irem, a menos que uma mão poderosa o obrigue a isso.

[[v2-3-20]]

^<<v2-3-20,20>>^ Portanto, terei de estender a minha mão e golpear o Egito com todos os atos extraordinários que lá farei e, depois disso, ele irá mandar-vos partir.

[[v2-3-21]]

^<<v2-3-21,21>>^ Farei com que este povo seja visto com favor aos olhos dos egípcios e, quando partirem, de modo algum irão de mãos vazias.

[[v2-3-22]]

^<<v2-3-22,22>>^ Cada mulher deve pedir artigos de prata e de ouro, bem como roupas, à sua vizinha e à mulher que estiver hospedada em sua casa, e vocês irão colocá-los nos vossos filhos e nas vossas filhas, e despojarão os egípcios.”

'''

xref:002-exodo/002-exodo-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodo/002-exodo-004.adoc#v2-4-0[Próximo Capítulo &#62;]