include::./index.adoc[]

[[v2-20-0]]
=== Êxodo, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-20-1]]

^<<v2-20-1,1>>^ Então, Deus disse todas estas palavras:

[[v2-20-2]]

^<<v2-20-2,2>>^ “Eu sou Jeová, teu Deus, que te tirou da terra do Egito, a terra da escravidão.^&#42;1^

[NOTE]
====
. Lit.: “casa dos escravos”.
====

[[v2-20-3]]

^<<v2-20-3,3>>^ Não tenhas outros deuses além de mim.^&#42;1^

[NOTE]
====
. Ou: “em oposição a mim”. Lit.: “contra a minha face”.
====

[[v2-20-4]]

^<<v2-20-4,4>>^ “Não faças para ti nenhuma imagem esculpida, nem nenhuma representação de algo que há nos céus, em cima, ou na terra, em baixo, ou nas águas debaixo da terra.

[[v2-20-5]]

^<<v2-20-5,5>>^ Não te curves diante delas nem as sirvas,^&#42;1^ pois eu, Jeová, teu Deus, sou um Deus que exige devoção exclusiva e que traz punição pelo erro dos pais sobre os filhos, sobre a terceira geração e sobre a quarta geração daqueles que me odeiam,

[NOTE]
====
. Ou: “nem sejas induzido a servi-las”.
====

[[v2-20-6]]

^<<v2-20-6,6>>^ mas que demonstra amor leal até pela milésima geração daqueles que me amam e que guardam os meus mandamentos.

[[v2-20-7]]

^<<v2-20-7,7>>^ “Não uses o nome de Jeová, teu Deus, em vão,^&#42;1^ pois Jeová não deixará impune aquele que usar o Seu nome em vão.

[NOTE]
====
. Ou: “de um modo fútil”.
====

[[v2-20-8]]

^<<v2-20-8,8>>^ “Lembra-te de manter sagrado o dia de sábado.

[[v2-20-9]]

^<<v2-20-9,9>>^ Trabalha e faz todas as tuas tarefas durante seis dias,

[[v2-20-10]]

^<<v2-20-10,10>>^ mas o sétimo dia é um sábado para Jeová, teu Deus. Não faças nenhum trabalho, nem tu, nem o teu filho, nem a tua filha, nem o teu escravo, nem a tua escrava, nem o teu animal doméstico, nem o teu residente estrangeiro, que está dentro das tuas cidades.^&#42;1^

[NOTE]
====
. Ou: “dos teus portões”.
====

[[v2-20-11]]

^<<v2-20-11,11>>^ Pois em seis dias Jeová fez os céus, a terra, o mar e tudo o que há neles, e no sétimo dia passou a descansar. Foi por isso que Jeová abençoou o dia de sábado e o tornou sagrado.

[[v2-20-12]]

^<<v2-20-12,12>>^ “Honra o teu pai e a tua mãe, para que vivas por muito tempo na terra que Jeová, teu Deus, te dá.

[[v2-20-13]]

^<<v2-20-13,13>>^ “Não assassines.

[[v2-20-14]]

^<<v2-20-14,14>>^ “Não cometas adultério.

[[v2-20-15]]

^<<v2-20-15,15>>^ “Não furtes.

[[v2-20-16]]

^<<v2-20-16,16>>^ “Não dês falso testemunho ao depor contra o teu próximo.

[[v2-20-17]]

^<<v2-20-17,17>>^ “Não desejes a casa do teu próximo. Não desejes a esposa do teu próximo, nem o seu escravo, nem a sua escrava, nem o seu touro, nem o seu jumento, nem nada que pertença ao teu próximo.”

[[v2-20-18]]

^<<v2-20-18,18>>^ Todo o povo ouviu os trovões e o som da buzina, e viu os relâmpagos e o monte a fumegar. Diante disso, começaram a tremer e ficaram à distância.

[[v2-20-19]]

^<<v2-20-19,19>>^ Por isso, disseram a Moisés: “Fala tu connosco e nós escutaremos, mas não fale Deus connosco, para que não morramos.”

[[v2-20-20]]

^<<v2-20-20,20>>^ Portanto, Moisés disse ao povo: “Não tenham medo, pois o verdadeiro Deus veio para vos pôr à prova e para que continuem a temê-lo, a fim de que não pequem.”

[[v2-20-21]]

^<<v2-20-21,21>>^ Assim, o povo mantinha-se à distância, mas Moisés aproximou-se da nuvem escura onde estava o verdadeiro Deus.

[[v2-20-22]]

^<<v2-20-22,22>>^ Então, Jeová disse a Moisés: “Isto é o que deves dizer aos israelitas: ‘Vocês mesmos viram que falei convosco desde os céus.

[[v2-20-23]]

^<<v2-20-23,23>>^ Não façam deuses de prata para adorá-los além de mim, nem façam deuses de ouro para vocês.

[[v2-20-24]]

^<<v2-20-24,24>>^ Deves fazer-me um altar de terra, e nele sacrificarás as tuas ofertas queimadas e oferecerás os teus sacrifícios de participação em comum,^&#42;1^ as tuas ovelhas e os teus bois. Em todos os lugares onde eu fizer que o meu nome seja lembrado, hei de vir até ti e abençoar-te.

[NOTE]
====
. Ou: “ as tuas ofertas de paz”.
====

[[v2-20-25]]

^<<v2-20-25,25>>^ Se me construíres um altar de pedras, não uses pedras cortadas com ferramentas,^&#42;1^ pois, se usares a talhadeira, irás profaná-lo.

[NOTE]
====
. Ou: “não uses pedras talhadas”.
====

[[v2-20-26]]

^<<v2-20-26,26>>^ E não subas ao meu altar por degraus, para que não exponhas lá as tuas partes íntimas.’^&#42;1^

[NOTE]
====
. Lit.: “a tua nudez”.
====

'''

xref:002-exodo/002-exodo-019.adoc#v2-19-0[&#60; Capítulo Anterior] | <<v2-20-0,Topo>> | xref:002-exodo/002-exodo-021.adoc#v2-21-0[Próximo Capítulo &#62;]