include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-35-1]]

^<<v2-35-1,1>>^ Mais tarde, Moisés reuniu toda a assembleia de Israel e disse: “Isto é o que Jeová ordenou que se fizesse:

[[v2-35-2]]

^<<v2-35-2,2>>^ Podem trabalhar por seis dias, mas o sétimo dia será sagrado para vocês, um sábado de completo descanso dedicado a Jeová. Todo aquele que trabalhar nesse dia será morto.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendam fogo em nenhuma das vossas casas no dia de sábado.”

[[v2-35-4]]

^<<v2-35-4,4>>^ Moisés disse ainda a toda a assembleia de Israel: “Isto é o que Jeová ordenou:

[[v2-35-5]]

^<<v2-35-5,5>>^ ‘Recolham dentre vocês uma contribuição para Jeová. Que todos os de coração disposto tragam uma contribuição para Jeová: ouro, prata, cobre,

[[v2-35-6]]

^<<v2-35-6,6>>^ linha azul, lã roxa, fio escarlate, linho fino, pelos de cabra,

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tingidas de vermelho, peles de foca, madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ óleo para as lâmpadas, bálsamo para fazer o óleo de unção e o incenso perfumado,

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ónix e outras pedras para serem colocadas no éfode e no peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ “‘Venham todos os que forem habilidosos^&#42;1^ dentre vocês e façam tudo o que Jeová ordenou:

[NOTE]
====
. Lit.: “sábios de coração”.
====

[[v2-35-11]]

^<<v2-35-11,11>>^ o tabernáculo com a sua tenda e a sua cobertura, os colchetes e as armações, as travessas, as colunas e as bases com encaixe;

[[v2-35-12]]

^<<v2-35-12,12>>^ a Arca com os seus varais, a tampa e a cortina de separação;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa com os seus varais, todos os seus utensílios e os pães da proposição;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro para a iluminação com os seus utensílios, as suas lâmpadas e o óleo para a iluminação;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar do incenso com os seus varais; o óleo de unção e o incenso perfumado; a cortina^&#42;1^ para a entrada do tabernáculo;

[NOTE]
====
. Ou: “o reposteiro”.
====

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar da oferta queimada com a sua grade de cobre, os seus varais e todos os seus utensílios; a bacia com o seu suporte;

[[v2-35-17]]

^<<v2-35-17,17>>^ os cortinados do pátio, as suas colunas e as suas bases com encaixe, a cortina^&#42;1^ da entrada do pátio;

[NOTE]
====
. Ou: “o reposteiro”.
====

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas de fixação do tabernáculo e as estacas de fixação do pátio com as suas cordas;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes finamente tecidas que serão usadas para servir no santuário, as vestes sagradas para Arão, o sacerdote, e as vestes dos seus filhos, para servirem como sacerdotes.’”

[[v2-35-20]]

^<<v2-35-20,20>>^ Assim, toda a assembleia de Israel se retirou da presença de Moisés.

[[v2-35-21]]

^<<v2-35-21,21>>^ Então, todo aquele cujo coração o impelia e todo aquele cujo espírito o motivava trouxe a contribuição para Jeová até à tenda de reunião, para todo o serviço lá realizado e para as vestes sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Continuaram a vir, homens e mulheres, todo aquele de coração disposto. Trouxeram pregadeiras, brincos, anéis e outras joias, bem como todo o tipo de objetos de ouro. Todos eles apresentaram a Jeová as suas ofertas^&#42;1^ de ouro.

[NOTE]
====
. Ou: “ofertas movidas”.
====

[[v2-35-23]]

^<<v2-35-23,23>>^ E todos os que possuíam linha azul, lã roxa, fio escarlate, linho fino, pelos de cabra, peles de carneiro tingidas de vermelho e peles de foca, trouxeram-nos.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todos os que contribuíram com prata ou com cobre trouxeram essa contribuição para Jeová, e todos os que possuíam madeira de acácia trouxeram-na para as diversas partes da obra.

[[v2-35-25]]

^<<v2-35-25,25>>^ Todas as mulheres habilidosas fiaram com as mãos e trouxeram o que tinham feito: linha azul, lã roxa, fio escarlate e linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ E todas as mulheres habilidosas cujo coração as impelia fiaram os pelos de cabra.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os maiorais trouxeram pedras de ónix e outras pedras para serem colocadas no éfode e no peitoral.

[[v2-35-28]]

^<<v2-35-28,28>>^ Trouxeram também o bálsamo e o óleo para a iluminação, para o óleo de unção e para o incenso perfumado.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todos os homens e mulheres cujo coração os motivava trouxeram algo para a obra que Jeová, por meio de Moisés, tinha ordenado que se fizesse. Os israelitas trouxeram tudo como oferta voluntária para Jeová.

[[v2-35-30]]

^<<v2-35-30,30>>^ Moisés disse então aos israelitas: “Vejam! Jeová escolheu Bezalel, filho de Uri, filho de Hur, da tribo de Judá.

[[v2-35-31]]

^<<v2-35-31,31>>^ Ele encheu-o com o espírito de Deus, dando-lhe sabedoria, entendimento e conhecimento de todo o tipo de artesanato,

[[v2-35-32]]

^<<v2-35-32,32>>^ para elaborar projetos artísticos, para trabalhar com ouro, com prata e com cobre,

[[v2-35-33]]

^<<v2-35-33,33>>^ para lapidar e incrustar pedras, e para fazer todo o tipo de trabalho artístico com madeira.

[[v2-35-34]]

^<<v2-35-34,34>>^ E pôs no coração dele, bem como no de Ooliabe, filho de Aisamaque, da tribo de Dã, a disposição de ensinar.

[[v2-35-35]]

^<<v2-35-35,35>>^ Ele encheu-os de habilidade^&#42;1^ para executarem todo o tipo de trabalho de artesão, de desenhista, de bordador com linha azul, lã roxa, fio escarlate e linho fino, e de tecelão. Estes homens farão todo o tipo de trabalho e elaborarão todo o tipo de projetos.

[NOTE]
====
. Lit.: “sabedoria de coração”.
====

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]