include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-8-1]]

^<<v2-8-1,1>>^ Jeová disse então a Moisés: “Apresenta-te perante o Faraó e diz-lhe: ‘Assim diz Jeová: “Deixa partir o meu povo, para que me sirva.

[[v2-8-2]]

^<<v2-8-2,2>>^ Se continuares a recusar-lhes a sua partida, atingirei todo o teu território com uma praga de rãs.

[[v2-8-3]]

^<<v2-8-3,3>>^ O rio Nilo ficará infestado de rãs, que subirão e entrarão na tua casa e no teu quarto, estarão na tua cama, entrarão nas casas dos teus servos e estarão sobre o teu povo, nos teus fornos e nas tuas amassadeiras.^&#42;1^

[NOTE]
====
. Ou: “tigelas”.
====

[[v2-8-4]]

^<<v2-8-4,4>>^ As rãs virão sobre ti, sobre o teu povo e sobre todos os teus servos.”’”

[[v2-8-5]]

^<<v2-8-5,5>>^ Mais tarde, Jeová disse a Moisés: “Diz a Arão: ‘Estende a mão com o bastão sobre os rios, sobre os canais do Nilo e sobre os pântanos, e faz com que venham rãs sobre a terra do Egito.’”

[[v2-8-6]]

^<<v2-8-6,6>>^ Então, Arão estendeu a mão sobre as águas do Egito e destas saíram rãs, que cobriram a terra do Egito.

[[v2-8-7]]

^<<v2-8-7,7>>^ No entanto, os sacerdotes-magos fizeram a mesma coisa com as suas artes secretas e fizeram com que viessem rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ Então, o Faraó chamou Moisés e Arão, e disse: “Supliquem a Jeová para que afaste estas rãs de mim e do meu povo, visto que quero deixar o povo partir, para que ofereçam sacrifícios a Jeová.”

[[v2-8-9]]

^<<v2-8-9,9>>^ Moisés disse então ao Faraó: “Cabe-lhe a si a honra de decidir quando é que devo fazer súplicas para que o senhor, os seus servos, o seu povo e as suas casas fiquem livres das rãs. Estas ficarão apenas no rio Nilo.”

[[v2-8-10]]

^<<v2-8-10,10>>^ Então, ele disse: “Amanhã.” Portanto, Moisés disse: “Será segundo a sua palavra, para que saiba que não há ninguém como Jeová, o nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ O senhor, as suas casas, os seus servos e o seu povo ficarão livres das rãs. Estas ficarão apenas no Nilo.”

[[v2-8-12]]

^<<v2-8-12,12>>^ Assim, Moisés e Arão retiraram-se da presença do Faraó, e Moisés clamou a Jeová por causa das rãs que Ele tinha enviado contra o Faraó.

[[v2-8-13]]

^<<v2-8-13,13>>^ Então, Jeová atendeu ao pedido de Moisés, e as rãs começaram a morrer nas casas, nos pátios e nos campos.

[[v2-8-14]]

^<<v2-8-14,14>>^ Foram ajuntadas em inúmeros montões, e a terra começou a cheirar mal.

[[v2-8-15]]

^<<v2-8-15,15>>^ Quando o Faraó viu que houve alívio, endureceu o coração e não quis escutá-los, assim como Jeová tinha dito.

[[v2-8-16]]

^<<v2-8-16,16>>^ Jeová disse então a Moisés: “Diz a Arão: ‘Estende o teu bastão e bate no pó da terra, e este irá transformar-se em mosquitos por toda a terra do Egito.’”

[[v2-8-17]]

^<<v2-8-17,17>>^ E assim fizeram. Arão estendeu a mão com o seu bastão e bateu no pó da terra, e vieram mosquitos sobre os homens e sobre os animais. Todo o pó da terra se transformou em mosquitos por toda a terra do Egito.

[[v2-8-18]]

^<<v2-8-18,18>>^ Os sacerdotes-magos tentaram fazer o mesmo e produzir mosquitos com as suas artes secretas, mas não conseguiram. E os mosquitos atingiram os homens e os animais.

[[v2-8-19]]

^<<v2-8-19,19>>^ Então, os sacerdotes-magos disseram ao Faraó: “É o dedo de Deus!” Contudo, o coração do Faraó continuou endurecido, e ele não os escutou, assim como Jeová tinha dito.

[[v2-8-20]]

^<<v2-8-20,20>>^ Então, Jeová disse a Moisés: “Levanta-te de manhã cedo e apresenta-te perante o Faraó. Quando ele estiver a sair para ir ao rio, diz-lhe: ‘Assim disse Jeová: “Deixa partir o meu povo, para que me sirva.

[[v2-8-21]]

^<<v2-8-21,21>>^ Mas, se não deixares o meu povo partir, enviarei moscões^&#42;1^ contra ti, contra os teus servos, contra o teu povo e contra as tuas casas. As casas do Egito ficarão cheias de moscões, e eles cobrirão o chão que os egípcios pisam.

[NOTE]
====
. Uma espécie de mosca que pica.
====

[[v2-8-22]]

^<<v2-8-22,22>>^ Nesse dia, certamente colocarei à parte a terra de Gósen, onde mora o meu povo. Não haverá lá nenhum moscão; e assim saberás que eu, Jeová, estou nesta terra.

[[v2-8-23]]

^<<v2-8-23,23>>^ Farei distinção entre o meu povo e o teu povo. Este sinal ocorrerá amanhã.”’”

[[v2-8-24]]

^<<v2-8-24,24>>^ E Jeová assim fez. Grandes enxames de moscões começaram a invadir a casa do Faraó e as casas dos seus servos, e toda a terra do Egito. O país foi devastado por moscões.

[[v2-8-25]]

^<<v2-8-25,25>>^ Por fim, o Faraó chamou Moisés e Arão, e disse: “Vão, ofereçam sacrifícios ao vosso Deus aqui neste país.”

[[v2-8-26]]

^<<v2-8-26,26>>^ No entanto, Moisés disse: “Não é adequado fazê-lo assim, pois o que queremos oferecer em sacrifício ao nosso Deus, Jeová, é detestável para os egípcios. Se oferecêssemos um sacrifício que é detestável para os egípcios, mesmo à frente dos seus olhos, será que eles não nos apedrejariam?

[[v2-8-27]]

^<<v2-8-27,27>>^ Faremos uma viagem de três dias pelo deserto e lá ofereceremos sacrifícios a Jeová, o nosso Deus, assim como ele nos disse.”

[[v2-8-28]]

^<<v2-8-28,28>>^ O Faraó disse então: “Vou deixar-vos partir, para que ofereçam sacrifícios a Jeová, o vosso Deus, no deserto. Mas não se afastem demasiado. Façam súplicas por mim.”

[[v2-8-29]]

^<<v2-8-29,29>>^ Então, Moisés disse: “Agora, vou retirar-me da sua presença e farei súplicas a Jeová, e amanhã os moscões deixarão o Faraó, os seus servos e o seu povo. Mas que o Faraó não volte a enganar-nos,^&#42;1^ recusando-se a deixar o povo partir para oferecer sacrifícios a Jeová.”

[NOTE]
====
. Ou: “não volte a brincar connosco”.
====

[[v2-8-30]]

^<<v2-8-30,30>>^ Moisés retirou-se então da presença do Faraó e fez súplicas a Jeová.

[[v2-8-31]]

^<<v2-8-31,31>>^ Assim, Jeová fez segundo a palavra de Moisés, e os moscões deixaram o Faraó, os seus servos e o seu povo. Não sobrou nem sequer um moscão.

[[v2-8-32]]

^<<v2-8-32,32>>^ No entanto, o Faraó endureceu novamente o coração e não deixou o povo partir.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]