include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-21-1]]

^<<v2-21-1,1>>^ “Estas são as decisões judiciais que lhes deves comunicar:

[[v2-21-2]]

^<<v2-21-2,2>>^ “Se comprares um escravo hebreu, ele servirá como escravo por seis anos, mas no sétimo ano será libertado sem ter de pagar nada.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se ele chegou sozinho, sairá sozinho. Se for marido de uma esposa, a sua esposa irá com ele.

[[v2-21-4]]

^<<v2-21-4,4>>^ Se o seu senhor lhe der uma esposa, e ela lhe der filhos ou filhas, a esposa e os filhos passarão a pertencer ao senhor dela, e ele sairá sozinho.

[[v2-21-5]]

^<<v2-21-5,5>>^ Contudo, se o escravo insistir e disser: ‘Eu amo o meu senhor, a minha esposa e os meus filhos; não quero ser libertado’,

[[v2-21-6]]

^<<v2-21-6,6>>^ o seu senhor deve levá-lo perante o verdadeiro Deus. Então, deve encostá-lo à porta ou à ombreira,^&#42;1^ e o seu senhor deve furar-lhe a orelha com uma sovela,^&#42;2^ e ele será seu escravo por toda a vida.

[NOTE]
====
. Ou: “à lateral da porta”.
. Instrumento usado para fazer pequenos furos.
====

[[v2-21-7]]

^<<v2-21-7,7>>^ “Se um homem vender a sua filha como escrava, ela não será libertada assim como é libertado um escravo homem.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se o seu senhor não se agradar dela e não a designar como concubina, deve permitir que ela seja comprada,^&#42;1^ mas não terá o direito de a vender a estrangeiros, pois foi desleal para com ela.

[NOTE]
====
. Lit.: “resgatada”.
====

[[v2-21-9]]

^<<v2-21-9,9>>^ Se ele a designar para o seu filho, deve conceder-lhe os direitos de uma filha.

[[v2-21-10]]

^<<v2-21-10,10>>^ Se ele tomar para si outra esposa, não se deve reduzir em nada o que a primeira esposa recebe, no que se refere a alimentação, roupas e direitos conjugais.

[[v2-21-11]]

^<<v2-21-11,11>>^ Se ele não lhe der estas três coisas, ela sairá livre, sem pagar nada.

[[v2-21-12]]

^<<v2-21-12,12>>^ “Quem ferir um homem e causar a sua morte será morto.

[[v2-21-13]]

^<<v2-21-13,13>>^ Porém, se ele fizer isso sem querer, e o verdadeiro Deus permitir que isso aconteça, irei designar-te um lugar para onde ele possa fugir.

[[v2-21-14]]

^<<v2-21-14,14>>^ Se um homem ficar furioso com o seu próximo e o matar deliberadamente, esse homem deve morrer, mesmo que o tenhas de tirar de perto do meu altar.

[[v2-21-15]]

^<<v2-21-15,15>>^ Quem agredir o seu pai ou a sua mãe será morto.

[[v2-21-16]]

^<<v2-21-16,16>>^ “Se alguém raptar um homem e o vender, ou for encontrado com ele em seu poder, será morto.

[[v2-21-17]]

^<<v2-21-17,17>>^ “Quem amaldiçoar^&#42;1^ o seu pai ou a sua mãe será morto.

[NOTE]
====
. Ou: “invocar o mal sobre”.
====

[[v2-21-18]]

^<<v2-21-18,18>>^ “Isto é o que deve acontecer quando dois homens se envolvem numa disputa, e um fere o outro com uma pedra ou com o punho,^&#42;1^ e este não morre, mas fica de cama:

[NOTE]
====
. Ou, possivelmente: “uma ferramenta”.
====

[[v2-21-19]]

^<<v2-21-19,19>>^ se ele se conseguir levantar e andar fora de casa com o auxílio de um bastão, aquele que o feriu ficará livre de punição. Apenas dará indemnização pelo tempo de trabalho que o homem ferido perder até ficar completamente curado.

[[v2-21-20]]

^<<v2-21-20,20>>^ “Se um homem ferir o seu escravo ou a sua escrava com um pau, e o escravo morrer pela sua mão, o escravo será vingado.

[[v2-21-21]]

^<<v2-21-21,21>>^ Contudo, se ele sobreviver um ou dois dias, não deverá ser vingado, porque foi comprado com o dinheiro do seu senhor.

[[v2-21-22]]

^<<v2-21-22,22>>^ “Se homens lutarem entre si e ferirem uma mulher grávida, e ela der à luz prematuramente,^&#42;1^ mas não houver um acidente fatal,^&#42;2^ aquele que causou o acidente pagará a indemnização que lhe for imposta pelo marido da mulher; ele deve pagá-la por meio dos juízes.

[NOTE]
====
. Lit.: “e os seus filhos saírem”.
. Ou: “ferimento grave”.
====

[[v2-21-23]]

^<<v2-21-23,23>>^ Porém, se houver um acidente fatal, dar-se-á vida por vida,^&#42;1^

[NOTE]
====
. Ou: “alma por alma”.
====

[[v2-21-24]]

^<<v2-21-24,24>>^ olho por olho, dente por dente, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferimento por ferimento, pancada por pancada.

[[v2-21-26]]

^<<v2-21-26,26>>^ “Se um homem ferir o olho do seu escravo ou da sua escrava, e o escravo perder o olho, ele deve libertar o escravo em compensação pelo seu olho.

[[v2-21-27]]

^<<v2-21-27,27>>^ E, se fizer cair o dente do seu escravo ou da sua escrava, libertará o escravo em compensação pelo dente.

[[v2-21-28]]

^<<v2-21-28,28>>^ “Se um touro escornar um homem ou uma mulher, e a pessoa morrer, o touro será apedrejado até à morte, e a sua carne não deve ser comida; mas o dono do touro ficará livre de punição.

[[v2-21-29]]

^<<v2-21-29,29>>^ No entanto, se o touro costumava escornar, e o seu dono tiver sido advertido, mas não o tiver mantido preso, e o touro matar um homem ou uma mulher, o touro deve ser apedrejado e o seu dono também deve ser morto.

[[v2-21-30]]

^<<v2-21-30,30>>^ Se lhe for imposto um resgate,^&#42;1^ ele pagará como preço de redenção pela sua vida^&#42;2^ tudo o que lhe for imposto.

[NOTE]
====
. Ou: “for imposta uma reparação”.
. Ou: “alma”.
====

[[v2-21-31]]

^<<v2-21-31,31>>^ Se o touro escornar um menino ou uma menina, deve-se aplicar ao dono do touro esta mesma decisão judicial.

[[v2-21-32]]

^<<v2-21-32,32>>^ Se o touro escornar um escravo ou uma escrava, o dono do touro pagará 30 siclos^&#42;1^ ao senhor do escravo, e o touro será apedrejado até à morte.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v2-21-33]]

^<<v2-21-33,33>>^ “Se um homem deixar um poço aberto ou escavar um poço e não o cobrir, e um touro ou um jumento cair lá dentro,

[[v2-21-34]]

^<<v2-21-34,34>>^ o dono do poço deve pagar uma indemnização. Deve pagar o valor ao dono do animal, e o animal morto passará a pertencer-lhe.

[[v2-21-35]]

^<<v2-21-35,35>>^ Se o touro de um homem ferir o touro de outro, e o touro ferido morrer, então, eles venderão o touro vivo e dividirão entre si o valor pago por ele; devem também dividir entre si o animal morto.

[[v2-21-36]]

^<<v2-21-36,36>>^ Contudo, se já se sabia que o touro costumava escornar, mas o seu dono não o tiver mantido preso, ele dará uma compensação, touro por touro, e o animal morto passará a pertencer-lhe.

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]