include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-34-1]]

^<<v2-34-1,1>>^ Jeová disse então a Moisés: “Talha duas tábuas de pedra iguais às primeiras, e eu escreverei nas tábuas as palavras que estavam nas primeiras tábuas, que tu despedaçaste.

[[v2-34-2]]

^<<v2-34-2,2>>^ Que estejas pronto pela manhã, visto que de manhã vais subir ao monte Sinai e apresentar-te diante de mim, lá no cume do monte.

[[v2-34-3]]

^<<v2-34-3,3>>^ Mas ninguém pode subir contigo, e mais ninguém deve ser visto em nenhuma parte do monte. Nem mesmo os rebanhos ou as manadas deverão pastar diante do monte.”

[[v2-34-4]]

^<<v2-34-4,4>>^ Assim, Moisés talhou duas tábuas de pedra iguais às primeiras. Levantou-se de manhã cedo e subiu ao monte Sinai, conforme Jeová lhe tinha ordenado, levando nas mãos as duas tábuas de pedra.

[[v2-34-5]]

^<<v2-34-5,5>>^ De seguida, Jeová desceu na nuvem e pôs-se ali junto a ele, e declarou o nome de Jeová.

[[v2-34-6]]

^<<v2-34-6,6>>^ Jeová passou diante dele, declarando: “Jeová, Jeová, Deus misericordioso e compassivo,^&#42;1^ paciente^&#42;2^ e cheio de amor leal^&#42;3^ e de verdade,^&#42;4^

[NOTE]
====
. Ou: “benevolente”.
. Ou: “vagaroso em irar-se”.
. Ou: “bondade”.
. Ou: “fidelidade”.
====

[[v2-34-7]]

^<<v2-34-7,7>>^ que demonstra amor leal a milhares, perdoando o erro, a transgressão e o pecado. Mas de modo algum deixará impune o culpado, pois trará punição pelo erro dos pais sobre os filhos e sobre os netos, sobre a terceira geração e sobre a quarta geração.”

[[v2-34-8]]

^<<v2-34-8,8>>^ Moisés curvou-se imediatamente por terra e prostrou-se.

[[v2-34-9]]

^<<v2-34-9,9>>^ Disse então: “Ó Jeová, se eu realmente achei favor aos teus olhos, por favor, Jeová, vem connosco, no nosso meio, embora sejamos um povo obstinado.^&#42;1^ Perdoa o nosso erro e o nosso pecado, e aceita-nos como tua propriedade.”

[NOTE]
====
. Lit.: “de dura cerviz”.
====

[[v2-34-10]]

^<<v2-34-10,10>>^ Ele respondeu: “Passo a fazer um pacto: farei diante de todo o teu povo coisas maravilhosas que nunca foram feitas^&#42;1^ em nenhuma parte da terra, nem entre as nações, e todos os povos entre os quais viveres verão as obras de Jeová, pois o que faço contigo é uma coisa espantosa.

[NOTE]
====
. Ou: “criadas”.
====

[[v2-34-11]]

^<<v2-34-11,11>>^ “Presta atenção ao que te ordeno hoje. Expulsarei de diante de ti os amorreus, os cananeus, os hititas, os perizeus, os heveus e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ Tem o cuidado de não fazer nenhum pacto com os habitantes da terra para a qual estás a ir, para que isso não se torne um laço entre vocês.

[[v2-34-13]]

^<<v2-34-13,13>>^ Mas devem demolir os seus altares, despedaçar as suas colunas sagradas e derrubar os seus postes sagrados.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v2-34-14]]

^<<v2-34-14,14>>^ Não te deves curvar diante de nenhum outro deus, pois Jeová é conhecido por^&#42;1^ exigir devoção exclusiva.^&#42;2^ Sim, ele é um Deus que exige devoção exclusiva.

[NOTE]
====
. Lit.: “Jeová, o seu nome é”.
. Ou: “por não tolerar rivais”.
====

[[v2-34-15]]

^<<v2-34-15,15>>^ Tem o cuidado de não fazer nenhum pacto com os habitantes dessa terra. Pois, quando eles se prostituírem com os seus deuses e lhes oferecerem sacrifícios, alguém te convidará e tu comerás do seu sacrifício.

[[v2-34-16]]

^<<v2-34-16,16>>^ Então, certamente tomarás algumas das filhas deles como esposas para os teus filhos, e as filhas deles irão prostituir-se com os deuses deles e farão com que os teus filhos se prostituam com os deuses deles.

[[v2-34-17]]

^<<v2-34-17,17>>^ “Não faças deuses de metal fundido.

[[v2-34-18]]

^<<v2-34-18,18>>^ “Deves celebrar a Festividade dos Pães sem Fermento; comerás pães sem fermento, assim como te ordenei. Faz isso por sete dias, na época determinada do mês de abibe,^&#42;1^ porque foi no mês de abibe que saíste do Egito.

[NOTE]
====
. Veja o Ap. B15.
====

[[v2-34-19]]

^<<v2-34-19,19>>^ “Todo o primogénito do sexo masculino^&#42;1^ é meu, incluindo todos os primogénitos dos teus animais, seja um bezerro, seja um cordeiro.

[NOTE]
====
. Lit.: “Tudo o que abre o ventre”.
====

[[v2-34-20]]

^<<v2-34-20,20>>^ Deves remir a primeira cria de um jumento com uma ovelha. Mas, se não a remires, parte-lhe a nuca. Deves remir todo o primogénito dos teus filhos. Ninguém poderá comparecer perante mim de mãos vazias.

[[v2-34-21]]

^<<v2-34-21,21>>^ “Deves trabalhar por seis dias, mas no sétimo dia descansarás.^&#42;1^ Descansarás até mesmo na época de lavrar a terra e na época da colheita.

[NOTE]
====
. Ou: “guardarás o sábado”.
====

[[v2-34-22]]

^<<v2-34-22,22>>^ “Celebrarás a Festividade das Semanas com os primeiros frutos maduros da colheita do trigo, e celebrarás a Festividade do Recolhimento^&#42;1^ na transição do ano.

[NOTE]
====
. Também conhecida como Festividade das Barracas (Tendas).
====

[[v2-34-23]]

^<<v2-34-23,23>>^ “Três vezes por ano, todos os homens^&#42;1^ devem comparecer perante o verdadeiro Senhor, Jeová, o Deus de Israel.

[NOTE]
====
. Ou: “indivíduos do sexo masculino”.
====

[[v2-34-24]]

^<<v2-34-24,24>>^ Pois expulsarei as nações de diante de ti e aumentarei o teu território, e ninguém cobiçará a tua terra quando subires três vezes por ano para comparecer perante^&#42;1^ Jeová, teu Deus.

[NOTE]
====
. Lit.: “ver a face de”.
====

[[v2-34-25]]

^<<v2-34-25,25>>^ “Não ofereças o sangue do meu sacrifício com algo que tenha fermento. O sacrifício da Festividade da Páscoa não deve ser guardado da noite para o dia.

[[v2-34-26]]

^<<v2-34-26,26>>^ “Deves levar à casa de Jeová, teu Deus, o melhor dos primeiros frutos maduros da tua terra.
“Não cozinhes o cabrito no leite da própria mãe.”

[[v2-34-27]]

^<<v2-34-27,27>>^ Jeová disse ainda a Moisés: “Deves escrever estas palavras, porque é de acordo com estas palavras que faço um pacto contigo e com Israel.”

[[v2-34-28]]

^<<v2-34-28,28>>^ Ele ficou lá com Jeová durante 40 dias e 40 noites. Não comeu pão nem bebeu água. E Ele escreveu nas tábuas as palavras do pacto, os Dez Mandamentos.^&#42;1^

[NOTE]
====
. Lit.: “as Dez Palavras”. Também conhecidos como o Decálogo.
====

[[v2-34-29]]

^<<v2-34-29,29>>^ Moisés desceu, então, do monte Sinai, e as duas tábuas do Testemunho estavam nas suas mãos. Ao descer do monte, Moisés não sabia que a pele do seu rosto brilhava intensamente, por ter falado com Deus.

[[v2-34-30]]

^<<v2-34-30,30>>^ Quando Arão e todos os israelitas olharam para Moisés, viram que a pele do seu rosto brilhava intensamente e ficaram com medo de se aproximar dele.

[[v2-34-31]]

^<<v2-34-31,31>>^ Contudo, Moisés chamou-os, de modo que Arão e todos os maiorais da assembleia se aproximaram dele, e Moisés falou com eles.

[[v2-34-32]]

^<<v2-34-32,32>>^ Depois disso, todos os israelitas se aproximaram dele, e ele transmitiu-lhes todos os mandamentos que Jeová lhe tinha dado no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Sempre que Moisés acabava de falar com eles, colocava um véu sobre o rosto.

[[v2-34-34]]

^<<v2-34-34,34>>^ Porém, quando Moisés comparecia perante Jeová para falar com ele, tirava o véu até à hora de sair. Depois, ele saía e comunicava aos israelitas os mandamentos que tinha recebido.

[[v2-34-35]]

^<<v2-34-35,35>>^ E os israelitas viam que a pele do rosto de Moisés brilhava intensamente; então, Moisés voltava a colocar o véu sobre o rosto até entrar para falar com Deus.^&#42;1^

[NOTE]
====
. Lit.: “ele”.
====

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]