include::./index.adoc[]

[[v2-7-0]]
=== Êxodo, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-7-1]]

^<<v2-7-1,1>>^ Então, Jeová disse a Moisés: “Vê, fiz-te como Deus^&#42;1^ para o Faraó; e Arão, teu irmão, falará por ti como profeta.

[NOTE]
====
. Lit.: “fiz-te Deus”.
====

[[v2-7-2]]

^<<v2-7-2,2>>^ Dirás tudo o que eu te ordenar; o teu irmão Arão falará com o Faraó, e este deixará os israelitas saírem do país.

[[v2-7-3]]

^<<v2-7-3,3>>^ Quanto a mim, permitirei que o coração do Faraó fique endurecido. Multiplicarei os meus sinais e os meus milagres na terra do Egito,

[[v2-7-4]]

^<<v2-7-4,4>>^ mas o Faraó não vos escutará. Então, porei a minha mão sobre o Egito e tirarei da terra do Egito as multidões que me pertencem,^&#42;1^ o meu povo, os israelitas, com grandes julgamentos.

[NOTE]
====
. Lit.: “os meus exércitos”.
====

[[v2-7-5]]

^<<v2-7-5,5>>^ E os egípcios certamente saberão que eu sou Jeová, quando eu estender a mão contra o Egito e tirar os israelitas do seu meio.”

[[v2-7-6]]

^<<v2-7-6,6>>^ Moisés e Arão fizeram o que Jeová lhes tinha ordenado; fizeram exatamente assim.

[[v2-7-7]]

^<<v2-7-7,7>>^ Moisés tinha 80 anos de idade e Arão tinha 83 anos de idade quando falaram com o Faraó.

[[v2-7-8]]

^<<v2-7-8,8>>^ Jeová disse então a Moisés e a Arão:

[[v2-7-9]]

^<<v2-7-9,9>>^ “Se o Faraó vos disser: ‘Façam um milagre’, diz a Arão: ‘Pega no teu bastão e atira-o ao chão diante do Faraó.’ O bastão irá transformar-se numa cobra grande.”

[[v2-7-10]]

^<<v2-7-10,10>>^ Por conseguinte, Moisés e Arão apresentaram-se perante o Faraó e fizeram exatamente como Jeová tinha ordenado. Arão atirou o seu bastão ao chão diante do Faraó e dos seus servos, e o bastão transformou-se numa cobra grande.

[[v2-7-11]]

^<<v2-7-11,11>>^ No entanto, o Faraó convocou os sábios e os feiticeiros; e os sacerdotes-magos do Egito fizeram a mesma coisa com a sua magia.^&#42;1^

[NOTE]
====
. Ou: “as suas artes mágicas”.
====

[[v2-7-12]]

^<<v2-7-12,12>>^ Cada um deles atirou o seu bastão ao chão e estes transformaram-se em cobras grandes; mas o bastão de Arão engoliu os bastões deles.

[[v2-7-13]]

^<<v2-7-13,13>>^ Ainda assim, o coração do Faraó ficou endurecido, e ele não os escutou, assim como Jeová tinha dito.

[[v2-7-14]]

^<<v2-7-14,14>>^ Então, Jeová disse a Moisés: “O coração do Faraó é insensível. Ele recusou-se a deixar o povo partir.

[[v2-7-15]]

^<<v2-7-15,15>>^ Vai até ao Faraó pela manhã. Quando ele estiver a sair para ir ao rio Nilo, fica à beira da água para te encontrares com ele; e leva contigo o bastão que se transformou numa serpente.

[[v2-7-16]]

^<<v2-7-16,16>>^ Diz-lhe: ‘Jeová, o Deus dos hebreus, enviou-me até si. Ele disse: “Deixa o meu povo partir, para que me sirvam no deserto”, mas o senhor não obedeceu até agora.

[[v2-7-17]]

^<<v2-7-17,17>>^ Assim diz Jeová: “Por meio disto, saberás que eu sou Jeová. Com o bastão que está na minha mão, vou bater na água do rio Nilo e ela irá transformar-se em sangue.

[[v2-7-18]]

^<<v2-7-18,18>>^ Os peixes do Nilo morrerão, o Nilo ficará a cheirar mal, e os egípcios simplesmente não conseguirão beber a água do Nilo.”’”

[[v2-7-19]]

^<<v2-7-19,19>>^ De seguida, Jeová disse a Moisés: “Diz a Arão: ‘Pega no teu bastão e estende a mão sobre as águas do Egito, sobre os rios, sobre os canais,^&#42;1^ sobre os pântanos e sobre todos os reservatórios, para que se transformem em sangue.’ Haverá sangue em toda a terra do Egito, até mesmo nos recipientes de madeira e de pedra.”

[NOTE]
====
. Isto é, os canais do Nilo.
====

[[v2-7-20]]

^<<v2-7-20,20>>^ Moisés e Arão fizeram imediatamente como Jeová lhes tinha ordenado. Ele ergueu o bastão e atingiu a água do rio Nilo diante do Faraó e dos servos dele, e toda a água do rio se transformou em sangue.

[[v2-7-21]]

^<<v2-7-21,21>>^ Os peixes do rio morreram e o rio começou a cheirar mal, de modo que os egípcios não podiam beber a água do Nilo. Havia sangue por toda a terra do Egito.

[[v2-7-22]]

^<<v2-7-22,22>>^ Contudo, os sacerdotes-magos do Egito fizeram a mesma coisa com as suas artes secretas, de modo que o coração do Faraó continuou endurecido, e ele não os escutou, assim como Jeová tinha dito.

[[v2-7-23]]

^<<v2-7-23,23>>^ Então, o Faraó voltou para casa e também não levou isso a sério.

[[v2-7-24]]

^<<v2-7-24,24>>^ Assim, todos os egípcios cavavam ao redor do Nilo em busca de água para beber, porque não podiam beber a água do Nilo.

[[v2-7-25]]

^<<v2-7-25,25>>^ Completaram-se então sete dias depois de Jeová ter atingido o Nilo.

'''

xref:002-exodo/002-exodo-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodo/002-exodo-008.adoc#v2-8-0[Próximo Capítulo &#62;]