include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-30-1]]

^<<v2-30-1,1>>^ “Faz um altar para queimar incenso. Deves fazê-lo com madeira de acácia.

[[v2-30-2]]

^<<v2-30-2,2>>^ Deve ser quadrado, de um côvado^&#42;1^ de comprimento, um côvado de largura e dois côvados de altura. Os seus chifres formarão com ele uma peça única.

[NOTE]
====
. Cerca de 44,5 cm. Veja o Ap. B14.
====

[[v2-30-3]]

^<<v2-30-3,3>>^ Deves revesti-lo de ouro puro: a parte superior, todas as partes laterais e os chifres; e deves fazer uma moldura^&#42;1^ de ouro ao seu redor.

[NOTE]
====
. Ou: “um acabamento”.
====

[[v2-30-4]]

^<<v2-30-4,4>>^ Farás também duas argolas de ouro abaixo da moldura,^&#42;1^ em dois lados opostos; e através delas passarão os varais usados para carregar o altar.

[NOTE]
====
. Ou: “do acabamento”.
====

[[v2-30-5]]

^<<v2-30-5,5>>^ Faz os varais de madeira de acácia e reveste-os de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ Deves colocar o altar à frente da cortina que está junto à Arca do Testemunho, diante da tampa que está sobre o Testemunho, onde me apresentarei perante ti.

[[v2-30-7]]

^<<v2-30-7,7>>^ “Arão queimará incenso perfumado sobre o altar; todas as manhãs, ao cuidar das lâmpadas, fará o incenso fumegar sobre o altar.

[[v2-30-8]]

^<<v2-30-8,8>>^ Arão também queimará o incenso entre o pôr do sol e a noite,^&#42;1^ quando acender as lâmpadas. Será uma oferta de incenso a ser feita regularmente perante Jeová, por todas as vossas gerações.

[NOTE]
====
. Lit.: “entre os dois anoiteceres”.
====

[[v2-30-9]]

^<<v2-30-9,9>>^ Não ofereçam nesse altar nenhum incenso não autorizado, nem oferta queimada, nem oferta de cereais; e não derramem sobre ele nenhuma oferta de bebida.

[[v2-30-10]]

^<<v2-30-10,10>>^ Uma vez por ano, Arão fará expiação sobre os chifres do altar. Com um pouco do sangue da oferta pelo pecado, feita para expiação, ele fará expiação pelo altar uma vez por ano. Isto deve ser feito por todas as vossas gerações. O altar será santíssimo para Jeová.”

[[v2-30-11]]

^<<v2-30-11,11>>^ Então, Jeová disse a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ “Sempre que fizeres um recenseamento e contares os filhos de Israel, cada um dará a Jeová um resgate pela sua vida^&#42;1^ por ocasião do recenseamento. Isto é para que nenhuma praga lhes sobrevenha quando forem registados.

[NOTE]
====
. Ou: “alma”.
====

[[v2-30-13]]

^<<v2-30-13,13>>^ Todos os que forem registados darão meio siclo,^&#42;1^ segundo o siclo-padrão do lugar santo,^&#42;2^ que equivale a 20 geras.^&#42;3^ Meio siclo é a contribuição para Jeová.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
. Ou: “segundo o siclo sagrado”.
. Um gera equivalia a 0,57 g. Veja o Ap. B14.
====

[[v2-30-14]]

^<<v2-30-14,14>>^ Todo aquele que for registado, de 20 anos de idade para cima, dará essa contribuição a Jeová.

[[v2-30-15]]

^<<v2-30-15,15>>^ O rico não deve dar mais nem o pobre deve dar menos do que meio siclo,^&#42;1^ como contribuição para Jeová, de modo a que se faça expiação pela vossa vida.^&#42;2^

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
. Ou: “alma”.
====

[[v2-30-16]]

^<<v2-30-16,16>>^ Deves receber dos israelitas o dinheiro de prata da expiação e entregá-lo em benefício do serviço da tenda de reunião, para que isso sirva de lembrança perante Jeová em favor dos israelitas, a fim de se fazer expiação pela vossa vida.”^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v2-30-17]]

^<<v2-30-17,17>>^ Jeová disse ainda a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ “Faz uma bacia de cobre com um suporte de cobre, para se lavarem; coloca-a, então, entre a tenda de reunião e o altar, e deita-lhe água.

[[v2-30-19]]

^<<v2-30-19,19>>^ Arão e os seus filhos lavarão lá as mãos e os pés.

[[v2-30-20]]

^<<v2-30-20,20>>^ Quando entrarem na tenda de reunião, ou quando se aproximarem do altar para servir e para apresentar ofertas feitas por fogo a Jeová, devem lavar-se para que não morram.

[[v2-30-21]]

^<<v2-30-21,21>>^ Lavarão as mãos e os pés para que não morram; este será um decreto permanente para ele e a sua descendência, por todas as suas gerações.”

[[v2-30-22]]

^<<v2-30-22,22>>^ E Jeová disse a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ “Providencia também os perfumes mais seletos: 500 unidades de mirra solidificada; a metade dessa quantidade, 250 unidades, de canela aromática; 250 unidades de cálamo aromático;

[[v2-30-24]]

^<<v2-30-24,24>>^ também 500 unidades de cássia — tudo segundo o siclo-padrão do lugar santo;^&#42;1^ e um him^&#42;2^ de azeite de oliveira.

[NOTE]
====
. Ou: “segundo o siclo sagrado”.
. Um him equivalia a 3,67 l. Veja o Ap. B14.
====

[[v2-30-25]]

^<<v2-30-25,25>>^ Então, com essas coisas, faz um óleo sagrado de unção, que deve ser preparado com habilidade.^&#42;1^ Deve ser um óleo sagrado de unção.

[NOTE]
====
. Ou: “segundo a arte de um fabricante de perfumes”.
====

[[v2-30-26]]

^<<v2-30-26,26>>^ “Deves usá-lo para ungir a tenda de reunião, a Arca do Testemunho,

[[v2-30-27]]

^<<v2-30-27,27>>^ a mesa com todos os seus utensílios, o candelabro com os seus utensílios, o altar do incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ o altar da oferta queimada com todos os seus utensílios e a bacia com o seu suporte.

[[v2-30-29]]

^<<v2-30-29,29>>^ Santifica-os para que se tornem santíssimos. Todo aquele que lhes tocar deve ser santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ E ungirás Arão e os seus filhos, e deves santificá-los, a fim de que me sirvam como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ “Dirás aos israelitas: ‘Este deve continuar a ser um óleo sagrado de unção para mim, por todas as vossas gerações.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não deve ser aplicado no corpo de ninguém, e não devem fazer nada que tenha a mesma composição. Será algo sagrado. Deve continuar a ser algo sagrado para vocês.

[[v2-30-33]]

^<<v2-30-33,33>>^ Quem fizer um óleo semelhante a este e quem o aplicar numa pessoa não autorizada^&#42;1^ será eliminado do seu povo.’”^&#42;2^

[NOTE]
====
. Lit.: “num estranho”, isto é, um homem que não era da família de Arão.
. Isto é, será morto.
====

[[v2-30-34]]

^<<v2-30-34,34>>^ A seguir, Jeová disse a Moisés: “Pega nos seguintes perfumes em partes iguais: gotas de estoraque, onicha, gálbano perfumado e olíbano puro.

[[v2-30-35]]

^<<v2-30-35,35>>^ Com essas coisas, faz um incenso, uma mistura aromática preparada com habilidade.^&#42;1^ Levará sal, será puro e será sagrado.

[NOTE]
====
. Ou: “segundo a arte de um fabricante de perfumes”.
====

[[v2-30-36]]

^<<v2-30-36,36>>^ Deves triturar parte dele até se tornar pó fino e deves pôr um pouco dele diante do Testemunho, na tenda de reunião, onde me apresentarei a ti. Deve ser santíssimo para vocês.

[[v2-30-37]]

^<<v2-30-37,37>>^ Não faças para o teu próprio uso o incenso que farás com esta composição. Deves considerá-lo como algo sagrado para Jeová.

[[v2-30-38]]

^<<v2-30-38,38>>^ Quem fizer um semelhante a este para sentir o seu aroma será eliminado do seu povo.”^&#42;1^

[NOTE]
====
. Isto é, será morto.
====

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]