include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-18-1]]

^<<v2-18-1,1>>^ Jetro, o sacerdote de Midiã, sogro de Moisés, ouviu falar de tudo o que Deus tinha feito por Moisés e pelo seu povo, Israel, e de como Jeová tinha tirado Israel do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ Jetro, o sogro de Moisés, tinha acolhido Zípora,^&#42;1^ esposa de Moisés. Este tinha-a enviado para a casa do sogro

[NOTE]
====
. Ou: “Séfora”.
====

[[v2-18-3]]

^<<v2-18-3,3>>^ com os dois filhos dela. A um deles chamaram Gérson,^&#42;1^ pois Moisés disse: “Tornei-me um residente estrangeiro numa terra estrangeira.”

[NOTE]
====
. Que significa “residente estrangeiro ali”.
====

[[v2-18-4]]

^<<v2-18-4,4>>^ E ao outro chamaram Eliézer,^&#42;1^ pois ele disse: “O Deus do meu pai é o meu ajudador, que me livrou da espada do Faraó.”

[NOTE]
====
. Que significa “o meu Deus é ajudador”.
====

[[v2-18-5]]

^<<v2-18-5,5>>^ Portanto, Jetro, o sogro de Moisés, juntamente com os filhos e a esposa de Moisés, foram ter com Moisés no deserto, onde ele estava acampado, junto ao monte do verdadeiro Deus.

[[v2-18-6]]

^<<v2-18-6,6>>^ Então, ele mandou dizer a Moisés: “Eu, o teu sogro, Jetro, vou ter contigo. Comigo estão a tua esposa e os teus dois filhos.”

[[v2-18-7]]

^<<v2-18-7,7>>^ Moisés saiu imediatamente ao encontro do seu sogro, curvou-se e beijou-o. Cada um perguntou ao outro como estava, e depois entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ Moisés contou ao sogro tudo o que Jeová tinha feito ao Faraó e ao Egito por causa de Israel, todas as dificuldades que tinham enfrentado pelo caminho e como Jeová os tinha livrado.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro alegrou-se com todo o bem que Jeová tinha feito a Israel, livrando-os do Egito.^&#42;1^

[NOTE]
====
. Lit.: “da mão do Egito”.
====

[[v2-18-10]]

^<<v2-18-10,10>>^ Então, Jetro disse: “Louvado seja Jeová, que vos livrou do Egito e do Faraó, e que livrou o povo do domínio do Egito.

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que Jeová é maior do que todos os outros deuses, por causa do que fez aos egípcios, que agiram de modo arrogante contra o Seu povo.”

[[v2-18-12]]

^<<v2-18-12,12>>^ Então, Jetro, sogro de Moisés, trouxe uma oferta queimada e sacrifícios a Deus; e Arão e todos os anciãos de Israel foram comer uma refeição com o sogro de Moisés, diante do verdadeiro Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte, Moisés sentou-se como de costume para julgar o povo, e o povo ficou diante de Moisés desde a manhã até ao anoitecer.

[[v2-18-14]]

^<<v2-18-14,14>>^ Vendo tudo o que ele fazia pelo povo, o sogro de Moisés disse: “Porque é que estás a fazer isto pelo povo? Porque é que te sentas para julgar sozinho enquanto o povo espera diante de ti desde a manhã até ao anoitecer?”

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés disse ao seu sogro: “É porque o povo vem até mim para consultar a Deus.

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando surge uma questão entre duas pessoas, apresentam-me essa questão para que eu a julgue, e eu torno conhecidas as decisões do verdadeiro Deus e as suas leis.”

[[v2-18-17]]

^<<v2-18-17,17>>^ O sogro de Moisés disse-lhe: “O que estás a fazer não é bom.

[[v2-18-18]]

^<<v2-18-18,18>>^ Certamente, ficarás  esgotado, tanto tu como este povo que está contigo, porque este é um fardo demasiado pesado para levares sozinho.

[[v2-18-19]]

^<<v2-18-19,19>>^ Agora escuta-me. Vou dar-te um conselho e Deus estará contigo. Deves, sim, servir como representante do povo diante do verdadeiro Deus e deves apresentar as questões ao verdadeiro Deus.

[[v2-18-20]]

^<<v2-18-20,20>>^ Deves ensinar-lhes os decretos e as leis, e fazê-los saber o caminho em que devem andar e o trabalho que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ No entanto, deves selecionar dentre o povo homens capazes, que temem a Deus, homens dignos de confiança, que odeiam o lucro desonesto, e designá-los sobre eles como chefes de mil, chefes de cem, chefes de cinquenta e chefes de dez.

[[v2-18-22]]

^<<v2-18-22,22>>^ Eles devem julgar o povo quando surgir uma questão,^&#42;1^ e trarão até ti todas as questões difíceis, mas resolverão todas as questões mais simples. Torna mais leve o teu fardo, deixando que eles o dividam contigo.

[NOTE]
====
. Lit.: “em todo o tempo”.
====

[[v2-18-23]]

^<<v2-18-23,23>>^ Se fizeres isso, e se Deus assim te ordena, poderás aguentar o fardo, e todos voltarão para casa satisfeitos.”

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés escutou imediatamente o seu sogro e fez tudo o que ele disse.

[[v2-18-25]]

^<<v2-18-25,25>>^ Moisés escolheu homens capazes dentre todo o Israel e designou-os como cabeças sobre o povo, como chefes de mil, chefes de cem, chefes de cinquenta e chefes de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ Assim, eles julgavam o povo quando surgia uma questão. Qualquer questão difícil era levada a Moisés, mas eles julgavam todas as questões mais simples.

[[v2-18-27]]

^<<v2-18-27,27>>^ Depois, Moisés despediu-se do seu sogro, que seguiu caminho para a sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]