include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-29-1]]

^<<v2-29-1,1>>^ “Isto é o que deves fazer para santificá-los, a fim de que me sirvam como sacerdotes: pega num novilho e em dois carneiros sem defeito,

[[v2-29-2]]

^<<v2-29-2,2>>^ pães sem fermento, pães em forma de anel feitos com azeite e sem fermento, e pães achatados sem fermento, untados com azeite. Deves fazer os pães com farinha fina de trigo,

[[v2-29-3]]

^<<v2-29-3,3>>^ colocá-los num cesto e apresentá-los dentro do cesto, juntamente com o novilho e os dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ “Deves apresentar Arão e os seus filhos à entrada da tenda de reunião e lavá-los com água.

[[v2-29-5]]

^<<v2-29-5,5>>^ Então, deves pegar nas roupas e vestir Arão com a veste comprida, a túnica sem mangas do éfode, o éfode e o peitoral; e deves atar-lhe à cintura o cinto bordado^&#42;1^ do éfode, com firmeza.

[NOTE]
====
. Ou: “a faixa para a cintura”.
====

[[v2-29-6]]

^<<v2-29-6,6>>^ Colocarás o turbante na sua cabeça e porás o sinal sagrado de dedicação^&#42;1^ no turbante.

[NOTE]
====
. Ou: “o diadema sagrado”.
====

[[v2-29-7]]

^<<v2-29-7,7>>^ Então, deves pegar no óleo de unção e derramá-lo sobre a sua cabeça, ungindo-o.

[[v2-29-8]]

^<<v2-29-8,8>>^ “A seguir, faz com que os seus filhos se aproximem e põe-lhes as vestes compridas.

[[v2-29-9]]

^<<v2-29-9,9>>^ Coloca também as faixas, tanto em Arão como nos seus filhos, e põe-lhes a cobertura para a cabeça. Assim, o sacerdócio passará a ser deles — isto é um decreto permanente. É deste modo que deves fazer a ordenação de Arão e dos seus filhos para servirem como sacerdotes.^&#42;1^

[NOTE]
====
. Lit.: “encher a mão de Arão e a mão dos seus filhos”.
====

[[v2-29-10]]

^<<v2-29-10,10>>^ “Depois, deves apresentar o novilho diante da tenda de reunião, e Arão e os seus filhos porão as mãos sobre a cabeça do novilho.

[[v2-29-11]]

^<<v2-29-11,11>>^ Abate o novilho perante Jeová, à entrada da tenda de reunião.

[[v2-29-12]]

^<<v2-29-12,12>>^ Molha o dedo no sangue do novilho e passa-o nos chifres do altar; e derrama todo o restante do sangue junto à base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ A seguir, pega em toda a gordura que envolve os intestinos, a membrana gordurosa do fígado, os dois rins e a gordura sobre estes, e queima-os, fazendo-os fumegar no altar.

[[v2-29-14]]

^<<v2-29-14,14>>^ No entanto, queimarás com fogo a carne, o couro e o excremento do novilho, fora do acampamento. É uma oferta pelo pecado.

[[v2-29-15]]

^<<v2-29-15,15>>^ “Pega, então, num dos carneiros, e Arão e os seus filhos devem pôr as mãos sobre a cabeça do carneiro.

[[v2-29-16]]

^<<v2-29-16,16>>^ Abate o carneiro, pega no seu sangue e faz aspersão em todos os lados do altar.

[[v2-29-17]]

^<<v2-29-17,17>>^ Corta o carneiro em pedaços, lava os seus intestinos e pernas, e põe os pedaços um ao lado do outro, juntamente com a cabeça.

[[v2-29-18]]

^<<v2-29-18,18>>^ Queima o carneiro inteiro, fazendo-o fumegar no altar. É uma oferta queimada a Jeová, um aroma agradável.^&#42;1^ É uma oferta feita por fogo a Jeová.

[NOTE]
====
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v2-29-19]]

^<<v2-29-19,19>>^ “A seguir, deves pegar no outro carneiro, e Arão e os seus filhos devem pôr as mãos sobre a cabeça do carneiro.

[[v2-29-20]]

^<<v2-29-20,20>>^ Abate o carneiro, pega num pouco do seu sangue e põe-no na ponta da orelha direita de Arão e na ponta da orelha direita dos seus filhos, também no polegar da mão direita e no dedo grande do pé direito deles, e faz aspersão do sangue em todos os lados do altar.

[[v2-29-21]]

^<<v2-29-21,21>>^ Depois, pega num pouco do sangue que está no altar e num pouco do óleo de unção, e usa-os para aspergir Arão e as suas vestes, sobre os seus filhos e as suas vestes, para que ele e as suas vestes, os seus filhos e as vestes deles se tornem santos.

[[v2-29-22]]

^<<v2-29-22,22>>^ “Tira, então, a gordura do carneiro, a sua cauda gorda, a gordura que envolve os intestinos, a membrana gordurosa do fígado, os dois rins e a gordura que há sobre estes, e a perna direita, pois é o carneiro para a ordenação.

[[v2-29-23]]

^<<v2-29-23,23>>^ Do cesto dos pães sem fermento que está perante Jeová, tira também um pão redondo, um pão em forma de anel, feito com azeite, e um pão achatado.

[[v2-29-24]]

^<<v2-29-24,24>>^ Coloca todas estas coisas nas mãos de Arão e nas mãos dos seus filhos, e deves movê-las para a frente e para trás, como oferta movida perante Jeová.

[[v2-29-25]]

^<<v2-29-25,25>>^ Então, deves tirá-las das mãos deles e queimá-las no altar, sobre a oferta queimada, como aroma agradável^&#42;1^ perante Jeová. É uma oferta feita por fogo a Jeová.

[NOTE]
====
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v2-29-26]]

^<<v2-29-26,26>>^ “A seguir, pega no peito do carneiro para a ordenação, que é oferecido em favor de Arão, e move-o para a frente e para trás, como oferta movida perante Jeová; essa será a porção que te caberá.

[[v2-29-27]]

^<<v2-29-27,27>>^ Do carneiro de ordenação oferecido em favor de Arão e dos seus filhos, deves santificar o peito apresentado como oferta movida e a perna apresentada como porção sagrada: o que foi movido e o que foi contribuído.

[[v2-29-28]]

^<<v2-29-28,28>>^ Por serem uma porção sagrada, estas partes passarão a pertencer a Arão e aos seus filhos como um decreto permanente a ser cumprido pelos israelitas, e elas irão tornar-se uma porção sagrada a ser contribuída pelos israelitas. É a porção sagrada deles para Jeová, dos seus sacrifícios de participação em comum.

[[v2-29-29]]

^<<v2-29-29,29>>^ “As vestes sagradas que pertencem a Arão serão depois usadas pelos seus filhos, quando forem ungidos e ordenados como sacerdotes.

[[v2-29-30]]

^<<v2-29-30,30>>^ O sacerdote que lhe suceder dentre os seus filhos e entrar na tenda de reunião para servir no lugar santo usará essas vestes por sete dias.

[[v2-29-31]]

^<<v2-29-31,31>>^ “Pegarás no carneiro para a ordenação e cozinharás a sua carne num lugar santo.

[[v2-29-32]]

^<<v2-29-32,32>>^ Arão e os seus filhos comerão à entrada da tenda de reunião a carne do carneiro e o pão que está no cesto.

[[v2-29-33]]

^<<v2-29-33,33>>^ Devem comer as coisas com as quais se fez expiação para a sua ordenação como sacerdotes^&#42;1^ e para a sua santificação. Porém, uma pessoa não autorizada^&#42;2^ não pode comer delas, pois são sagradas.

[NOTE]
====
. Lit.: “para lhes encher a mão”.
. Lit.: “um estranho”, isto é, um homem que não era da família de Arão.
====

[[v2-29-34]]

^<<v2-29-34,34>>^ Se sobrar algo da carne do sacrifício da ordenação e do pão na manhã seguinte, queima com fogo o que sobrar. Não deve ser comido, pois é algo sagrado.

[[v2-29-35]]

^<<v2-29-35,35>>^ “Deves fazer assim a Arão e aos seus filhos, segundo tudo o que te ordenei. Levarás sete dias a ordená-los como sacerdotes.^&#42;1^

[NOTE]
====
. Lit.: “para lhes encher a mão”.
====

[[v2-29-36]]

^<<v2-29-36,36>>^ Em cada dia, oferecerás um novilho como oferta pelo pecado para fazer expiação e purificarás de pecado o altar, fazendo expiação por ele; deves ungir o altar para santificá-lo.

[[v2-29-37]]

^<<v2-29-37,37>>^ Levarás sete dias a fazer expiação pelo altar; santifica-o para que se torne um altar santíssimo. Quem tocar no altar deve ser santo.

[[v2-29-38]]

^<<v2-29-38,38>>^ “Isto é o que oferecerás regularmente no altar: dois cordeiros de um ano, todos os dias.

[[v2-29-39]]

^<<v2-29-39,39>>^ Oferece um cordeiro pela manhã e o outro cordeiro entre o pôr do sol e a noite.^&#42;1^

[NOTE]
====
. Lit.: “entre os dois anoiteceres”.
====

[[v2-29-40]]

^<<v2-29-40,40>>^ Com o primeiro cordeiro apresentarás a décima parte de uma efa^&#42;1^ de farinha fina, misturada com um quarto de him^&#42;2^ de azeite puro, e uma oferta de bebida de um quarto de him de vinho.

[NOTE]
====
. Uma efa equivalia a 22 l. Veja o Ap. B14.
. Um him equivalia a 3,67 l. Veja o Ap. B14.
====

[[v2-29-41]]

^<<v2-29-41,41>>^ Oferecerás o segundo cordeiro entre o pôr do sol e a noite,^&#42;1^ com uma oferta de cereais e uma oferta de bebida, iguais às da manhã. Deves oferecê-lo como aroma agradável,^&#42;2^ uma oferta feita por fogo a Jeová.

[NOTE]
====
. Lit.: “entre os dois anoiteceres”.
. Ou: “apaziguador; calmante”. Lit.: “repousante”.
====

[[v2-29-42]]

^<<v2-29-42,42>>^ Será uma oferta queimada a ser feita regularmente por todas as vossas gerações perante Jeová, à entrada da tenda de reunião, onde me apresentarei a vocês para falar contigo.

[[v2-29-43]]

^<<v2-29-43,43>>^ “Lá, vou apresentar-me aos israelitas, e aquele lugar será santificado pela minha glória.

[[v2-29-44]]

^<<v2-29-44,44>>^ Vou santificar a tenda de reunião e o altar, e santificarei Arão e os seus filhos, a fim de que me sirvam como sacerdotes.

[[v2-29-45]]

^<<v2-29-45,45>>^ Vou residir entre o povo de Israel e serei o seu Deus.

[[v2-29-46]]

^<<v2-29-46,46>>^ E certamente saberão que eu sou Jeová, seu Deus, que os tirou da terra do Egito para residir no seu meio. Eu sou Jeová, o seu Deus.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]