include::./index.adoc[]

[[v2-22-0]]
=== Êxodo, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-22-1]]

^<<v2-22-1,1>>^ “Se um homem furtar uma ovelha ou um touro e o abater ou vender, deve dar cinco touros em compensação pelo touro e quatro ovelhas pela ovelha.

[[v2-22-2]]

^<<v2-22-2,2>>^ (“Se um ladrão for apanhado a arrombar uma casa, for ferido e morrer, quem o matou não terá culpa de sangue.

[[v2-22-3]]

^<<v2-22-3,3>>^ Mas, se isso acontecer depois do nascer do sol, quem o matou terá culpa de sangue.)
“O ladrão fará uma restituição. Se ele não tiver nada, será vendido para pagar as coisas que furtou.

[[v2-22-4]]

^<<v2-22-4,4>>^ Se o que ele furtou for encontrado vivo em seu poder, seja um touro, seja um jumento, seja uma ovelha, deve restituí-lo em dobro.

[[v2-22-5]]

^<<v2-22-5,5>>^ “Se alguém levar os seus animais para pastar num campo ou numa vinha e permitir que eles pastem no campo de outra pessoa, deve dar em compensação o melhor do seu próprio campo ou o melhor da sua própria vinha.

[[v2-22-6]]

^<<v2-22-6,6>>^ “Se houver um incêndio e este se alastrar pelos espinheiros e consumir feixes colhidos, a plantação de cereais ou todo o campo, aquele que causou o incêndio dará uma indemnização pelo que foi queimado.

[[v2-22-7]]

^<<v2-22-7,7>>^ “Se um homem der dinheiro ou objetos ao seu próximo para guardar, e estes forem roubados da sua casa, se o ladrão for encontrado, restituirá tudo em dobro.

[[v2-22-8]]

^<<v2-22-8,8>>^ Se o ladrão não for encontrado, o dono da casa será levado perante o verdadeiro Deus para se determinar se ele se apoderou dos^&#42;1^ bens do seu próximo.

[NOTE]
====
. Lit.: “pôs as mãos sobre os”.
====

[[v2-22-9]]

^<<v2-22-9,9>>^ Em qualquer caso de posse ilegal de bens que envolva um touro, um jumento, uma ovelha, uma roupa ou qualquer coisa perdida sobre a qual alguém diga: ‘Isto é meu!’, ambas as partes apresentarão a sua causa perante o verdadeiro Deus. Aquele a quem Deus declarar culpado restituirá em dobro ao seu próximo.

[[v2-22-10]]

^<<v2-22-10,10>>^ “Se um homem der ao seu próximo um jumento, um touro, uma ovelha ou qualquer animal doméstico para guardar, e este morrer, ficar aleijado ou for capturado sem que ninguém veja,

[[v2-22-11]]

^<<v2-22-11,11>>^ deve haver entre ambos um juramento perante Jeová, de que o homem não se apoderou dos bens do seu próximo; e o dono do animal deve aceitar isso. O outro não deve fazer uma restituição.

[[v2-22-12]]

^<<v2-22-12,12>>^ Contudo, se o animal foi roubado do homem que o guardava,^&#42;1^ este deve indemnizar o dono.

[NOTE]
====
. Aparentemente, devido a negligência ou a circunstâncias que poderiam ter sido evitadas.
====

[[v2-22-13]]

^<<v2-22-13,13>>^ Se o animal foi dilacerado por um animal selvagem, ele deve levar como prova o animal dilacerado. Não deve dar uma indemnização por algo dilacerado por um animal selvagem.

[[v2-22-14]]

^<<v2-22-14,14>>^ “No entanto, se alguém pedir um animal emprestado ao seu próximo, e o animal ficar aleijado ou morrer na ausência do dono, o homem que o pediu emprestado dará uma indemnização.

[[v2-22-15]]

^<<v2-22-15,15>>^ Se o dono estava presente, não deve dar uma indemnização. Se o animal tinha sido alugado, o preço do aluguer servirá de indemnização.

[[v2-22-16]]

^<<v2-22-16,16>>^ “Se um homem seduzir uma virgem que não esteja prometida em casamento e tiver relações sexuais com ela, pagará o preço de noiva para que ela se torne sua esposa.

[[v2-22-17]]

^<<v2-22-17,17>>^ Se o pai dela se negar terminantemente a dá-la, o homem deve pagar o valor de acordo com o preço de noiva.

[[v2-22-18]]

^<<v2-22-18,18>>^ “Não preserves viva a feiticeira.

[[v2-22-19]]

^<<v2-22-19,19>>^ “Todo aquele que tiver relações sexuais com um animal certamente será morto.

[[v2-22-20]]

^<<v2-22-20,20>>^ “Quem oferecer sacrifícios a qualquer outro deus, e não unicamente a Jeová, deve ser entregue à destruição.^&#42;1^

[NOTE]
====
. Ou: “devotado à destruição”. Veja o Glossário.
====

[[v2-22-21]]

^<<v2-22-21,21>>^ “Não maltrates nem oprimas o residente estrangeiro, pois vocês foram residentes estrangeiros na terra do Egito.

[[v2-22-22]]

^<<v2-22-22,22>>^ “Não aflijam nenhuma viúva nem nenhum órfão.^&#42;1^

[NOTE]
====
. Ou: “órfão de pai”.
====

[[v2-22-23]]

^<<v2-22-23,23>>^ Se os afligires de alguma maneira, e eles clamarem por mim, sem falta ouvirei o seu clamor;

[[v2-22-24]]

^<<v2-22-24,24>>^ e a minha ira há de se acender e irei matar-vos à espada, e as vossas esposas ficarão viúvas, e os vossos filhos ficarão órfãos.

[[v2-22-25]]

^<<v2-22-25,25>>^ “Se emprestares dinheiro a algum pobre^&#42;1^ do meu povo, alguém que vive contigo, não o faças visando o lucro;^&#42;2^ não lhe cobres juros.

[NOTE]
====
. Ou: “atribulado”.
. Ou: “não te tornes um agiota”.
====

[[v2-22-26]]

^<<v2-22-26,26>>^ “Se levares o manto do teu próximo como garantia de um empréstimo,^&#42;1^ deverás devolvê-lo até ao pôr do sol,

[NOTE]
====
. Ou: “como penhor”.
====

[[v2-22-27]]

^<<v2-22-27,27>>^ pois é a única cobertura que ele tem, a roupa que cobre o seu corpo.^&#42;1^ Onde é que ele se deitará para dormir? Quando ele clamar por mim, certamente ouvirei, pois sou compassivo.^&#42;2^

[NOTE]
====
. Lit.: “a sua pele”.
. Ou: “benevolente”.
====

[[v2-22-28]]

^<<v2-22-28,28>>^ “Não amaldiçoes^&#42;1^ a Deus nem amaldiçoes um maioral^&#42;2^ do teu povo.

[NOTE]
====
. Ou: “Não injuries; Não insultes”.
. Ou: “governante”.
====

[[v2-22-29]]

^<<v2-22-29,29>>^ “Não hesites em fazer ofertas da tua abundante produção agrícola e do que transborda dos teus lagares.^&#42;1^ Deves dar-me o primogénito dos teus filhos.

[NOTE]
====
. Isto é, lagares de azeite e de vinho.
====

[[v2-22-30]]

^<<v2-22-30,30>>^ Isto é o que deves fazer com o teu touro e com a tua ovelha: a cria ficará sete dias com a mãe. No oitavo dia, deves dar-me essa cria.

[[v2-22-31]]

^<<v2-22-31,31>>^ “Devem mostrar ser um povo santo para mim; não comam a carne de um animal que tenha sido dilacerado no campo por um animal selvagem. Devem deitá-la aos cães.

'''

xref:002-exodo/002-exodo-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodo/002-exodo-023.adoc#v2-23-0[Próximo Capítulo &#62;]