include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-14-1]]

^<<v2-14-1,1>>^ Jeová disse então a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ “Diz aos israelitas que voltem e acampem diante de Pi-Hairote, entre Migdol e o mar, à vista de Baal-Zefom. Devem acampar junto ao mar, em frente a Baal-Zefom.

[[v2-14-3]]

^<<v2-14-3,3>>^ Então, o Faraó dirá o seguinte a respeito dos israelitas: ‘Eles estão a vaguear confusos pelo país. O deserto encurralou-os.’

[[v2-14-4]]

^<<v2-14-4,4>>^ Permitirei que o coração do Faraó fique endurecido. Ele irá perseguir-vos, e eu irei glorificar-me por meio do Faraó e de todo o seu exército; e os egípcios certamente saberão que eu sou Jeová.” E assim fizeram os israelitas.

[[v2-14-5]]

^<<v2-14-5,5>>^ Mais tarde, comunicou-se ao rei do Egito que o povo tinha fugido. Imediatamente, o Faraó e os seus servos mudaram de ideias a respeito do povo e disseram: “Porque é que fizemos isto? Libertámos os israelitas, os nossos escravos!”

[[v2-14-6]]

^<<v2-14-6,6>>^ Por conseguinte, ele preparou os seus carros de guerra e levou os seus homens consigo.

[[v2-14-7]]

^<<v2-14-7,7>>^ Pegou nos 600 melhores carros de guerra e em todos os outros carros do Egito, com guerreiros em cada um deles.

[[v2-14-8]]

^<<v2-14-8,8>>^ Assim, Jeová permitiu que o coração do Faraó, o rei do Egito, ficasse endurecido, e este foi atrás dos israelitas, enquanto os israelitas saíam confiantes.^&#42;1^

[NOTE]
====
. Lit.: “com mão erguida”.
====

[[v2-14-9]]

^<<v2-14-9,9>>^ Os egípcios perseguiram-nos, e todos os cavalos dos carros de guerra do Faraó, os seus cavaleiros e o seu exército aproximaram-se dos israelitas enquanto estes estavam acampados à beira-mar, junto a Pi-Hairote, em frente a Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ Quando o Faraó se aproximou, os israelitas levantaram os olhos e viram que os egípcios vinham atrás deles. Os israelitas ficaram apavorados e começaram a clamar a Jeová.

[[v2-14-11]]

^<<v2-14-11,11>>^ Eles disseram a Moisés: “É porque não há sepulturas no Egito que nos trouxeste até aqui, para morrermos no deserto? O que é que nos fizeste, ao tirar-nos do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não te dissemos no Egito: ‘Deixa-nos em paz, para servirmos os egípcios’? Pois é melhor servirmos os egípcios do que morrermos no deserto.”

[[v2-14-13]]

^<<v2-14-13,13>>^ Então, Moisés disse ao povo: “Não tenham medo. Mantenham-se firmes e vejam a salvação da parte de Jeová, que ele realizará hoje a vosso favor. Pois nunca mais verão os egípcios que estão a ver hoje.

[[v2-14-14]]

^<<v2-14-14,14>>^ O próprio Jeová lutará por vocês, e vocês ficarão em silêncio.”

[[v2-14-15]]

^<<v2-14-15,15>>^ E Jeová disse a Moisés: “Porque é que persistes em clamar por mim? Diz aos israelitas que levantem o acampamento.

[[v2-14-16]]

^<<v2-14-16,16>>^ Quanto a ti, ergue o teu bastão, estende a mão sobre o mar e divide-o, para que os israelitas passem pelo meio do mar em terra seca.

[[v2-14-17]]

^<<v2-14-17,17>>^ Quanto a mim, permitirei que o coração dos egípcios fique endurecido, de modo que eles entrarão no mar atrás dos israelitas. Assim, vou glorificar-me por meio do Faraó e de todo o seu exército, dos seus carros de guerra e dos seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ E os egípcios certamente saberão que eu sou Jeová, quando eu me glorificar por meio do Faraó, dos seus carros de guerra e dos seus cavaleiros.”

[[v2-14-19]]

^<<v2-14-19,19>>^ Então, o anjo do verdadeiro Deus, que ia à frente do povo de Israel, afastou-se e foi para a retaguarda, e a coluna de nuvem que estava à frente deles moveu-se para a retaguarda e ficou atrás deles.

[[v2-14-20]]

^<<v2-14-20,20>>^ Assim, ela ficou entre o exército dos egípcios e o povo de Israel. De um lado, a nuvem causava escuridão; do outro lado, iluminava a noite. Deste modo, um grupo não chegou perto do outro durante toda a noite.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então, Moisés estendeu a mão sobre o mar, e Jeová fez o mar recuar por meio de um forte vento leste, durante toda a noite, transformando o leito do mar em terra seca, e as águas foram divididas.

[[v2-14-22]]

^<<v2-14-22,22>>^ Assim, os israelitas passaram pelo meio do mar em terra seca, enquanto as águas formavam uma muralha à sua direita e à sua esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios perseguiram-nos, e todos os cavalos do Faraó, os seus carros de guerra e os seus cavaleiros começaram a ir atrás deles para dentro do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ Durante a madrugada,^&#42;1^ Jeová olhou para o exército dos egípcios, a partir da coluna de fogo e de nuvem, e lançou o exército dos egípcios em confusão.

[NOTE]
====
. Ou: “vigília da manhã”, isto é, aproximadamente das 2 h às 6 h da manhã.
====

[[v2-14-25]]

^<<v2-14-25,25>>^ Desprendeu as rodas dos seus carros, de modo que os conduziam com dificuldade. Então, os egípcios disseram: “Vamos fugir dos israelitas, porque Jeová está a lutar por eles contra os egípcios.”

[[v2-14-26]]

^<<v2-14-26,26>>^ Então, Jeová disse a Moisés: “Estende a mão sobre o mar, para que as águas voltem sobre os egípcios, sobre os seus carros de guerra e os seus cavaleiros.”

[[v2-14-27]]

^<<v2-14-27,27>>^ Moisés estendeu imediatamente a mão sobre o mar e, ao amanhecer, o mar voltou ao estado normal. Os egípcios tentaram escapar das águas, mas Jeová desembaraçou-se dos egípcios no meio do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram e cobriram os carros de guerra e os cavaleiros de todo o exército do Faraó, que tinham entrado no mar atrás dos israelitas. Não se deixou sobreviver nem sequer um deles.

[[v2-14-29]]

^<<v2-14-29,29>>^ No entanto, os israelitas andaram em terra seca no leito do mar, e as águas formaram uma muralha à sua direita e à sua esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Assim, naquele dia, Jeová salvou Israel das mãos dos egípcios, e Israel viu os egípcios mortos à beira-mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ Israel viu também o grande poder^&#42;1^ que Jeová usou contra os egípcios, e o povo começou a temer a Jeová e a ter fé em Jeová e no seu servo Moisés.

[NOTE]
====
. Lit.: “a grande mão”.
====

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]