include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-4-1]]

^<<v2-4-1,1>>^ No entanto, Moisés respondeu: “Mas suponhamos que não acreditem em mim e que não escutem a minha voz, pois dirão: ‘Jeová não te apareceu.’”

[[v2-4-2]]

^<<v2-4-2,2>>^ Jeová perguntou-lhe então: “O que é isso que tens na mão?” Ele respondeu: “Um bastão.”

[[v2-4-3]]

^<<v2-4-3,3>>^ Ele disse-lhe: “Atira-o ao chão.” Por conseguinte, atirou o bastão ao chão e este transformou-se numa serpente, e Moisés fugiu dela.

[[v2-4-4]]

^<<v2-4-4,4>>^ Jeová disse então a Moisés: “Estende a mão e agarra-a pela cauda.” Ele estendeu a mão e agarrou-a, e ela transformou-se num bastão na sua mão.

[[v2-4-5]]

^<<v2-4-5,5>>^ Deus disse então: “Isto é para que eles acreditem que Jeová, o Deus dos seus antepassados, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, te apareceu.”

[[v2-4-6]]

^<<v2-4-6,6>>^ Jeová disse-lhe mais uma vez: “Por favor, coloca a mão na dobra superior da tua roupa.” Portanto, ele colocou a mão na dobra da roupa. Quando tirou a mão, esta estava com lepra, branca como a neve!

[[v2-4-7]]

^<<v2-4-7,7>>^ Então, ele disse: “Coloca novamente a mão na dobra superior da tua roupa.” Ele colocou a mão novamente na dobra da roupa. Quando a tirou, estava restabelecida, como o resto do corpo!

[[v2-4-8]]

^<<v2-4-8,8>>^ Ele disse: “Se não acreditarem em ti nem prestarem atenção ao primeiro sinal, certamente prestarão atenção ao segundo sinal.

[[v2-4-9]]

^<<v2-4-9,9>>^ Contudo, mesmo que não acreditem nestes dois sinais e não queiram escutar a tua voz, irás tirar um pouco da água do rio Nilo e derramá-la em terra seca, e a água que fores buscar ao Nilo irá transformar-se em sangue sobre a terra seca.”

[[v2-4-10]]

^<<v2-4-10,10>>^ Moisés disse então a Jeová: “Perdão, Jeová, mas nunca tive facilidade em falar, nem no passado nem depois de falares com o teu servo, pois sou vagaroso na fala^&#42;1^ e vagaroso de língua.”

[NOTE]
====
. Lit.: “pesado de boca”.
====

[[v2-4-11]]

^<<v2-4-11,11>>^ Jeová disse-lhe: “Quem é que deu a boca ao homem? Quem é que o faz ser mudo ou surdo, ter boa visão ou ser cego? Não sou eu, Jeová?

[[v2-4-12]]

^<<v2-4-12,12>>^ Portanto, agora, vai e eu estarei contigo quando falares,^&#42;1^ e irei ensinar-te o que deves dizer.”

[NOTE]
====
. Lit.: “com a tua boca”.
====

[[v2-4-13]]

^<<v2-4-13,13>>^ No entanto, ele disse: “Perdão, Jeová. Por favor, envia qualquer outro que queiras enviar.”

[[v2-4-14]]

^<<v2-4-14,14>>^ Então, acendeu-se a ira de Jeová contra Moisés, e ele disse: “O que me dizes do teu irmão Arão, o levita? Sei que ele fala muito bem. Neste momento, ele está a caminho para vir ao teu encontro. Ao ver-te, o seu coração vai alegrar-se.

[[v2-4-15]]

^<<v2-4-15,15>>^ Portanto, fala com ele e põe-lhe as palavras na boca; e, quando falarem, eu estarei convosco e irei ensinar-vos o que devem fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ Ele falará por ti ao povo; ele será o teu porta-voz e tu irás servir-lhe de Deus.^&#42;1^

[NOTE]
====
. Ou: “tu farás o papel de Deus para ele”.
====

[[v2-4-17]]

^<<v2-4-17,17>>^ E levarás este bastão na mão e, com ele, realizarás os sinais.”

[[v2-4-18]]

^<<v2-4-18,18>>^ Assim, Moisés voltou a Jetro, seu sogro, e disse-lhe: “Por favor, quero voltar aos meus irmãos que estão no Egito, para ver se ainda estão vivos.” Jetro disse a Moisés: “Vai em paz.”

[[v2-4-19]]

^<<v2-4-19,19>>^ Depois, Jeová disse a Moisés em Midiã: “Vai, volta ao Egito, porque todos os homens que te procuravam matar^&#42;1^ estão mortos.”

[NOTE]
====
. Ou: “procuravam a tua alma”.
====

[[v2-4-20]]

^<<v2-4-20,20>>^ Então, Moisés levou a sua esposa e os seus filhos, montou-os num jumento e partiu de volta para a terra do Egito. Além disso, Moisés levou o bastão do verdadeiro Deus na sua mão.

[[v2-4-21]]

^<<v2-4-21,21>>^ De seguida, Jeová disse a Moisés: “Depois de teres voltado ao Egito, trata de realizar perante o Faraó todos os milagres que te dei o poder de realizar. Mas permitirei que o seu coração fique endurecido, e ele não deixará o povo partir.

[[v2-4-22]]

^<<v2-4-22,22>>^ Diz ao Faraó: ‘Assim diz Jeová: “Israel é o meu filho, o meu primogénito.

[[v2-4-23]]

^<<v2-4-23,23>>^ Ordeno-te que deixes o meu filho partir, para que me sirva. Mas, se te recusares a deixá-lo partir, matarei o teu filho, o teu primogénito.”’”

[[v2-4-24]]

^<<v2-4-24,24>>^ Durante a viagem, na hospedaria, Jeová encontrou-o e procurava entregá-lo à morte.

[[v2-4-25]]

^<<v2-4-25,25>>^ Por fim, Zípora^&#42;1^ pegou numa pedra afiada^&#42;2^ e circuncidou o seu filho, e fez com que o prepúcio tocasse nos pés dele, e disse: “É porque és^&#42;3^ para mim um noivo de sangue.”

[NOTE]
====
. Ou: “Séfora”.
. Ou: “faca de pederneira”.
. Ou, possivelmente: “tu és”.
====

[[v2-4-26]]

^<<v2-4-26,26>>^ Assim, Ele deixou-o ir. Ela disse “noivo de sangue” por causa da circuncisão.

[[v2-4-27]]

^<<v2-4-27,27>>^ Então, Jeová disse a Arão: “Vai ao deserto para te encontrares com Moisés.” Assim, ele foi, encontrou-o junto ao monte do verdadeiro Deus, e cumprimentou-o com um beijo.

[[v2-4-28]]

^<<v2-4-28,28>>^ E Moisés contou a Arão todas as palavras de Jeová, que o tinha enviado, e também lhe falou de todos os sinais que Ele lhe tinha mandado realizar.

[[v2-4-29]]

^<<v2-4-29,29>>^ Depois disso, Moisés e Arão foram e reuniram todos os anciãos dos israelitas.

[[v2-4-30]]

^<<v2-4-30,30>>^ Arão contou-lhes todas as palavras que Jeová tinha dito a Moisés, e este realizou os sinais diante do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ Em vista disso, o povo acreditou. Quando ouviram que Jeová tinha voltado a sua atenção para os israelitas e que tinha visto a sua aflição, curvaram-se e prostraram-se.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]