include::./index.adoc[]

[[v2-33-0]]
=== Êxodo, 33
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-33-1]]

^<<v2-33-1,1>>^ Jeová disse ainda a Moisés: “Vai, segue adiante com o povo que tiraste da terra do Egito, para a terra a respeito da qual jurei a Abraão, a Isaque e a Jacó, dizendo: ‘Vou dá-la à vossa descendência.’^&#42;1^

[NOTE]
====
. Lit.: “semente”.
====

[[v2-33-2]]

^<<v2-33-2,2>>^ Enviarei um anjo à vossa frente e expulsarei os cananeus, os amorreus, os hititas, os perizeus, os heveus e os jebuseus.

[[v2-33-3]]

^<<v2-33-3,3>>^ Vai para uma terra que mana leite e mel. No entanto, não irei no vosso meio, pois vocês são um povo obstinado,^&#42;1^ e eu poderia exterminar-vos pelo caminho.”

[NOTE]
====
. Lit.: “de dura cerviz”.
====

[[v2-33-4]]

^<<v2-33-4,4>>^ Quando o povo ouviu estas palavras duras, começou a chorar, e ninguém usou enfeites.

[[v2-33-5]]

^<<v2-33-5,5>>^ Jeová disse a Moisés: “Diz aos israelitas: ‘Vocês são um povo obstinado.^&#42;1^ Num só instante eu poderia passar no vosso meio e exterminar-vos. Agora, permaneçam sem os vossos enfeites, enquanto vejo o que vou fazer convosco.’”

[NOTE]
====
. Lit.: “de dura cerviz”.
====

[[v2-33-6]]

^<<v2-33-6,6>>^ Portanto, a partir do monte Horebe, os israelitas não voltaram a colocar^&#42;1^ os seus enfeites.

[NOTE]
====
. Lit.: “os filhos de Israel arrancaram”.
====

[[v2-33-7]]

^<<v2-33-7,7>>^ Moisés pegou então na sua tenda e armou-a fora do acampamento, a certa distância do acampamento, e chamou-lhe tenda de reunião. Todo aquele que consultava Jeová ia à tenda de reunião, fora do acampamento.

[[v2-33-8]]

^<<v2-33-8,8>>^ Quando Moisés ia à tenda, todo o povo se levantava e ficava à entrada da sua própria tenda, e eles seguiam Moisés com os olhos até que ele entrasse na tenda.

[[v2-33-9]]

^<<v2-33-9,9>>^ Assim que Moisés entrava na tenda, a coluna de nuvem descia e ficava à entrada da tenda, enquanto Deus falava com Moisés.

[[v2-33-10]]

^<<v2-33-10,10>>^ Quando todo o povo via a coluna de nuvem parada à entrada da tenda, cada um se curvava à entrada da sua própria tenda.

[[v2-33-11]]

^<<v2-33-11,11>>^ Jeová falava com Moisés face a face, assim como um homem fala com outro homem. Quando Moisés retornava ao acampamento, Josué, filho de Num, seu servo e ajudante, não saía da tenda.

[[v2-33-12]]

^<<v2-33-12,12>>^ Moisés disse então a Jeová: “Dizes-me: ‘Guia este povo’, mas não me deixaste saber quem enviarás comigo. Além disso, disseste: ‘Conheço-te por nome,^&#42;1^ e achaste favor aos meus olhos.’

[NOTE]
====
. Ou: “Eu escolhi-te”.
====

[[v2-33-13]]

^<<v2-33-13,13>>^ Por favor, se achei favor aos teus olhos, faz-me saber os teus caminhos, para que eu te conheça e continue a achar favor aos teus olhos. Lembra-te também de que esta nação é o teu povo.”

[[v2-33-14]]

^<<v2-33-14,14>>^ Por conseguinte, ele disse: “Eu próprio irei^&#42;1^ contigo e dar-te-ei descanso.”

[NOTE]
====
. Lit.: “A minha face irá”.
====

[[v2-33-15]]

^<<v2-33-15,15>>^ Então, Moisés disse-lhe: “Se tu mesmo não fores^&#42;1^ também connosco, não nos faças partir.

[NOTE]
====
. Lit.: “Se a tua face não for”.
====

[[v2-33-16]]

^<<v2-33-16,16>>^ Como é que se saberá que achei favor aos teus olhos, eu e o teu povo? Não será por ires connosco, para que se veja que eu e o teu povo somos diferentes de qualquer outro povo à face da terra?”

[[v2-33-17]]

^<<v2-33-17,17>>^ Jeová disse a Moisés: “Também farei o que estás a pedir, porque achaste favor aos meus olhos, e eu conheço-te por nome.”

[[v2-33-18]]

^<<v2-33-18,18>>^ Então, Moisés disse: “Por favor, mostra-me a tua glória.”

[[v2-33-19]]

^<<v2-33-19,19>>^ Ele respondeu: “Farei com que toda a minha bondade passe diante de ti^&#42;1^ e vou declarar diante de ti o nome de Jeová. E mostrarei favor a quem eu mostrar favor, e terei misericórdia de quem eu tiver misericórdia.”

[NOTE]
====
. Ou: “diante da tua face”.
====

[[v2-33-20]]

^<<v2-33-20,20>>^ No entanto, acrescentou: “Não podes ver a minha face, pois nenhum homem me pode ver e continuar vivo.”

[[v2-33-21]]

^<<v2-33-21,21>>^ Jeová disse ainda: “Há aqui um lugar junto a mim. Fica em cima da rocha.

[[v2-33-22]]

^<<v2-33-22,22>>^ Quando a minha glória estiver a passar, vou colocar-te numa cavidade da rocha e cobrir-te com a minha mão até que eu tenha passado.

[[v2-33-23]]

^<<v2-33-23,23>>^ Depois, retirarei a minha mão, e verás as minhas costas. Contudo, a minha face não pode ser vista.”

'''

xref:002-exodo/002-exodo-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodo/002-exodo-034.adoc#v2-34-0[Próximo Capítulo &#62;]