include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-25-1]]

^<<v2-25-1,1>>^ Então, Jeová disse a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ “Diz ao povo de Israel que recolha uma contribuição para mim; de todas as pessoas cujo coração as motivar, devem recolher a minha contribuição.

[[v2-25-3]]

^<<v2-25-3,3>>^ Esta é a contribuição que devem aceitar da parte deles: ouro, prata, cobre,

[[v2-25-4]]

^<<v2-25-4,4>>^ linha azul, lã roxa,^&#42;1^ fio escarlate,^&#42;2^ linho fino, pelos de cabra,

[NOTE]
====
. Ou: “lã tingida de roxo”.
. Ou: “fibra carmínea”. Carmim é uma substância vermelho-viva extraída do inseto cochonilha-do-carmim.
====

[[v2-25-5]]

^<<v2-25-5,5>>^ peles de carneiro tingidas de vermelho, peles de foca, madeira de acácia,

[[v2-25-6]]

^<<v2-25-6,6>>^ óleo para as lâmpadas, bálsamo para fazer o óleo de unção e para o incenso perfumado,

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ónix e outras pedras para serem colocadas no éfode e no peitoral.

[[v2-25-8]]

^<<v2-25-8,8>>^ Farão um santuário para mim e eu residirei no seu meio.

[[v2-25-9]]

^<<v2-25-9,9>>^ Devem fazer o tabernáculo e todos os seus móveis e utensílios seguindo exatamente o modelo^&#42;1^ que vos mostrarei.

[NOTE]
====
. Ou: “projeto”.
====

[[v2-25-10]]

^<<v2-25-10,10>>^ “Devem fazer uma arca^&#42;1^ de madeira de acácia, de dois côvados^&#42;2^ e meio de comprimento, um côvado e meio de largura e um côvado e meio de altura.

[NOTE]
====
. Ou: “caixa”.
. Um côvado equivalia a 44,5 cm. Veja o Ap. B14.
====

[[v2-25-11]]

^<<v2-25-11,11>>^ Depois, deves revesti-la de ouro puro. Deves revesti-la por dentro e por fora, e farás uma moldura^&#42;1^ de ouro à sua volta.

[NOTE]
====
. Ou: “um acabamento”.
====

[[v2-25-12]]

^<<v2-25-12,12>>^ E deves fazer-lhe quatro argolas de ouro fundido e fixá-las acima dos quatro pés — duas argolas de um lado e duas argolas do outro lado.

[[v2-25-13]]

^<<v2-25-13,13>>^ Deves fazer varais de madeira de acácia e revesti-los de ouro,

[[v2-25-14]]

^<<v2-25-14,14>>^ e introduzirás os varais nas argolas nas laterais da Arca, para que se carregue a Arca com eles.

[[v2-25-15]]

^<<v2-25-15,15>>^ Os varais ficarão nas argolas da Arca; não devem ser removidos dela.

[[v2-25-16]]

^<<v2-25-16,16>>^ Colocarás dentro da Arca o Testemunho que te darei.

[[v2-25-17]]

^<<v2-25-17,17>>^ “Farás uma tampa de ouro puro, de dois côvados e meio de comprimento e um côvado e meio de largura.

[[v2-25-18]]

^<<v2-25-18,18>>^ Deves fazer dois querubins de ouro. Deves fazê-los de ouro batido a martelo, em ambas as extremidades da tampa.

[[v2-25-19]]

^<<v2-25-19,19>>^ Faz os querubins nas duas extremidades, um querubim em cada extremidade da tampa.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins devem ficar com as duas asas estendidas para cima, usando-as para cobrir a tampa. Ficarão um de frente para o outro; o rosto dos querubins ficará voltado para a tampa.

[[v2-25-21]]

^<<v2-25-21,21>>^ Colocarás a tampa sobre a Arca, e dentro da Arca colocarás o Testemunho que te darei.

[[v2-25-22]]

^<<v2-25-22,22>>^ Irei apresentar-me perante ti e falarei contigo de cima da tampa. De entre os dois querubins que estão sobre a Arca do Testemunho, dar-te-ei todas as ordens a serem transmitidas aos israelitas.

[[v2-25-23]]

^<<v2-25-23,23>>^ “Farás também uma mesa de madeira de acácia, de dois côvados de comprimento, um côvado de largura e um côvado e meio de altura.

[[v2-25-24]]

^<<v2-25-24,24>>^ Deves revesti-la de ouro puro e fazer uma moldura^&#42;1^ de ouro à sua volta.

[NOTE]
====
. Ou: “um acabamento”.
====

[[v2-25-25]]

^<<v2-25-25,25>>^ Farás ao redor da mesa uma borda da largura da mão^&#42;1^ e uma moldura^&#42;2^ de ouro ao redor da borda.

[NOTE]
====
. Cerca de 7,4 cm. Veja o Ap. B14.
. Ou: “um acabamento”.
====

[[v2-25-26]]

^<<v2-25-26,26>>^ Farás quatro argolas de ouro para a mesa e colocarás as argolas nos quatro cantos, onde estão fixados os quatro pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ As argolas devem ficar perto da borda, e através delas passarão os varais usados para carregar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Deves fazer os varais de madeira de acácia e revesti-los de ouro, e com os varais carregarás a mesa.

[[v2-25-29]]

^<<v2-25-29,29>>^ “Farás também os pratos e as taças da mesa, bem como as suas jarras e tigelas, com as quais serão derramadas as ofertas de bebida. Deves fazê-los de ouro puro.

[[v2-25-30]]

^<<v2-25-30,30>>^ E porás regularmente os pães da proposição na mesa diante de mim.

[[v2-25-31]]

^<<v2-25-31,31>>^ “Farás um candelabro de ouro puro. O candelabro deve ser feito de ouro batido a martelo. A base, a haste, os braços, os cálices, os botões e as flores serão uma só peça.

[[v2-25-32]]

^<<v2-25-32,32>>^ Da haste do candelabro sairão seis braços: três braços de um lado e três braços do outro lado.

[[v2-25-33]]

^<<v2-25-33,33>>^ Em cada braço, de um lado, haverá três cálices em forma de flor de amêndoa, alternando-se entre botões e flores; e em cada braço, do outro lado, haverá três cálices em forma de flor de amêndoa, alternando-se entre botões e flores. Assim serão os seis braços que saem da haste do candelabro.

[[v2-25-34]]

^<<v2-25-34,34>>^ Na haste do candelabro haverá quatro cálices em forma de flor de amêndoa, alternando-se entre botões e flores.

[[v2-25-35]]

^<<v2-25-35,35>>^ Debaixo do primeiro par de braços que saem da haste haverá um botão, debaixo do segundo par de braços haverá um botão, e debaixo do último par de braços haverá um botão; será assim para os seis braços que saem da haste.

[[v2-25-36]]

^<<v2-25-36,36>>^ Os botões, os braços e todo o candelabro devem ser uma só peça de ouro puro, batido a martelo.

[[v2-25-37]]

^<<v2-25-37,37>>^ Farás sete lâmpadas para ele; e, quando as lâmpadas estiverem acesas, iluminarão a área à sua frente.

[[v2-25-38]]

^<<v2-25-38,38>>^ Os apagadores^&#42;1^ e os braseiros do candelabro devem ser de ouro puro.

[NOTE]
====
. Ou: “As tenazes”.
====

[[v2-25-39]]

^<<v2-25-39,39>>^ O candelabro e todos estes utensílios devem ser feitos com um talento^&#42;1^ de ouro puro.

[NOTE]
====
. Um talento equivalia a 34,2 kg. Veja o Ap. B14.
====

[[v2-25-40]]

^<<v2-25-40,40>>^ Tem o cuidado de fazê-los segundo o modelo^&#42;1^ que te foi mostrado no monte.

[NOTE]
====
. Ou: “projeto”.
====

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]