include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-32-1]]

^<<v2-32-1,1>>^ Entretanto, ao ver que Moisés tardava a descer do monte, o povo reuniu-se à volta de Arão e disse-lhe: “Vamos! Faz-nos um deus que vá à nossa frente, pois não sabemos o que aconteceu a este Moisés, o homem que nos tirou da terra do Egito.”

[[v2-32-2]]

^<<v2-32-2,2>>^ A isto, Arão disse-lhes: “Tirem os brincos de ouro das orelhas das vossas esposas, dos vossos filhos e das vossas filhas, e tragam-mos.”

[[v2-32-3]]

^<<v2-32-3,3>>^ E assim todo o povo tirou os brincos de ouro das orelhas e levou-os a Arão.

[[v2-32-4]]

^<<v2-32-4,4>>^ Ele pegou então no ouro que trouxeram e moldou-o com uma talhadeira, fazendo com ele uma estátua^&#42;1^ em forma de bezerro. E eles começaram a dizer: “Este é o teu Deus, ó Israel, que te tirou da terra do Egito!”

[NOTE]
====
. Ou: “estátua fundida”.
====

[[v2-32-5]]

^<<v2-32-5,5>>^ Quando Arão viu isso, construiu um altar diante do bezerro. Então, Arão proclamou: “Amanhã haverá uma festividade para Jeová.”

[[v2-32-6]]

^<<v2-32-6,6>>^ Assim, levantaram-se cedo no dia seguinte, fizeram ofertas queimadas e apresentaram sacrifícios de participação em comum. Depois, o povo sentou-se para comer e beber. Então, levantaram-se para se divertirem.

[[v2-32-7]]

^<<v2-32-7,7>>^ Jeová disse a Moisés: “Vai, desce, porque o teu povo, que tiraste da terra do Egito, corrompeu-se.

[[v2-32-8]]

^<<v2-32-8,8>>^ Desviaram-se depressa do caminho que lhes ordenei que seguissem. Fizeram uma estátua^&#42;1^ em forma de bezerro para si, e estão a curvar-se perante ela, oferecendo-lhe sacrifícios e dizendo: ‘Este é o teu Deus, ó Israel, que te tirou da terra do Egito.’”

[NOTE]
====
. Ou: “estátua fundida”.
====

[[v2-32-9]]

^<<v2-32-9,9>>^ Jeová disse ainda a Moisés: “Vejo que este povo é obstinado.^&#42;1^

[NOTE]
====
. Lit.: “de dura cerviz”.
====

[[v2-32-10]]

^<<v2-32-10,10>>^ Portanto, não tentes impedir-me de exterminá-los na minha ira ardente; e farei de ti uma grande nação no seu lugar.”

[[v2-32-11]]

^<<v2-32-11,11>>^ Então, Moisés fez um apelo a^&#42;1^ Jeová, seu Deus, dizendo: “Por que motivo, ó Jeová, voltas a tua ira ardente contra o teu povo, depois de tirá-los da terra do Egito com grande poder e com mão poderosa?

[NOTE]
====
. Lit.: “abrandou a face de”.
====

[[v2-32-12]]

^<<v2-32-12,12>>^ Porque haveriam os egípcios de dizer: ‘Foi com más intenções que ele os tirou do Egito; queria matá-los nas montanhas e exterminá-los da face da terra’? Abandona a tua ira ardente e reconsidera^&#42;1^ a tua decisão de trazer esta calamidade sobre o teu povo.

[NOTE]
====
. Ou: “lamenta”.
====

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembra-te dos teus servos Abraão, Isaque e Israel, a quem juraste por ti mesmo, dizendo: ‘Multiplicarei a vossa descendência^&#42;1^ como as estrelas dos céus e darei à vossa descendência^&#42;2^ toda esta terra que indiquei, para que a recebam como propriedade permanente.’”

[NOTE]
====
. Lit.: “semente”.
. Lit.: “semente”.
====

[[v2-32-14]]

^<<v2-32-14,14>>^ Diante disso, Jeová reconsiderou^&#42;1^ a calamidade que disse que traria sobre o seu povo.

[NOTE]
====
. Ou: “lamentou”.
====

[[v2-32-15]]

^<<v2-32-15,15>>^ Então, Moisés voltou-se e desceu do monte com as duas tábuas do Testemunho nas mãos. As tábuas estavam escritas de ambos os lados — frente e verso.

[[v2-32-16]]

^<<v2-32-16,16>>^ As tábuas eram obra de Deus, e a escrita era a escrita de Deus, gravada nas tábuas.

[[v2-32-17]]

^<<v2-32-17,17>>^ Quando Josué começou a ouvir o barulho do povo a gritar, disse a Moisés: “Há um som de batalha no acampamento.”

[[v2-32-18]]

^<<v2-32-18,18>>^ Contudo, Moisés disse:
“Não é o som de um canto de vitória,^&#42;1^
Nem é o som de lamento por uma derrota;
Ouço o som de outro tipo de canto.”

[NOTE]
====
. Ou: “de uma realização poderosa”.
====

[[v2-32-19]]

^<<v2-32-19,19>>^ Assim que Moisés se aproximou do acampamento e viu o bezerro e as danças, ficou furioso e ele atirou ao chão as tábuas que estavam nas suas mãos, despedaçando-as no sopé do monte.

[[v2-32-20]]

^<<v2-32-20,20>>^ Pegou no bezerro que tinham feito, queimou-o no fogo e triturou-o; espalhou-o, então, sobre a água e fez com que os israelitas a bebessem.

[[v2-32-21]]

^<<v2-32-21,21>>^ E Moisés disse a Arão: “O que é que este povo te fez para que trouxesses tamanho pecado sobre eles?”

[[v2-32-22]]

^<<v2-32-22,22>>^ Arão respondeu: “Não fiques furioso, meu senhor. Sabes muito bem que o povo tem uma inclinação para o mal.

[[v2-32-23]]

^<<v2-32-23,23>>^ Eles disseram-me: ‘Faz-nos um deus que vá à nossa frente, pois não sabemos o que aconteceu a este Moisés, o homem que nos tirou da terra do Egito.’

[[v2-32-24]]

^<<v2-32-24,24>>^ Por isso, eu disse-lhes: ‘Quem tiver enfeites de ouro deve tirá-los e dar-mos.’ Então, atirei o ouro ao fogo e saiu este bezerro.”

[[v2-32-25]]

^<<v2-32-25,25>>^ Moisés viu que o povo estava fora de controlo, porque Arão os tinha deixado sem controlo, e isso deixou-os expostos à vergonha perante os seus inimigos.

[[v2-32-26]]

^<<v2-32-26,26>>^ Então, Moisés pôs-se à entrada do acampamento e disse: “Quem está do lado de Jeová? Que venha até mim!” E todos os levitas se reuniram à sua volta.

[[v2-32-27]]

^<<v2-32-27,27>>^ Ele disse-lhes: “Assim disse Jeová, o Deus de Israel: ‘Ponha cada um de vocês a sua espada na cintura e percorra o acampamento, de entrada a entrada,^&#42;1^ matando o irmão, o vizinho e o amigo.’”

[NOTE]
====
. Lit.: “de portão a portão”.
====

[[v2-32-28]]

^<<v2-32-28,28>>^ Os levitas fizeram o que Moisés tinha ordenado. Assim, naquele dia, cerca de 3000 homens foram mortos.

[[v2-32-29]]

^<<v2-32-29,29>>^ Moisés disse então: “Hoje, ponham-se de parte^&#42;1^ para o serviço de Jeová, pois cada um de vocês agiu contra o seu próprio filho e contra o seu próprio irmão; hoje, ele irá conceder-vos uma bênção.”

[NOTE]
====
. Lit.: “Hoje, encham a vossa mão”.
====

[[v2-32-30]]

^<<v2-32-30,30>>^ Logo no dia seguinte, Moisés disse ao povo: “Cometeram um pecado muito grande e, agora, eu subirei ao encontro de Jeová, para ver se posso reparar o vosso pecado.”

[[v2-32-31]]

^<<v2-32-31,31>>^ Portanto, Moisés voltou a Jeová e disse: “Que grande pecado cometeu este povo! Fizeram para si um deus de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Agora, porém, se for da tua vontade, perdoa-lhes o seu pecado; senão, por favor, apaga-me do livro que escreveste.”

[[v2-32-33]]

^<<v2-32-33,33>>^ No entanto, Jeová disse a Moisés: “Apagarei do meu livro aquele que tiver pecado contra mim.

[[v2-32-34]]

^<<v2-32-34,34>>^ Agora, vai, guia o povo para o lugar de que te falei. O meu anjo irá à tua frente; e, no dia em que eu exigir uma prestação de contas, trarei punição sobre eles por causa do seu pecado.”

[[v2-32-35]]

^<<v2-32-35,35>>^ Então, Jeová começou a atingir o povo com uma praga por terem feito o bezerro — o bezerro que Arão fez.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]