include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-26-1]]

^<<v2-26-1,1>>^ “Deves fazer o tabernáculo com dez panos de linho fino retorcido, linha azul, lã roxa e fio escarlate. Deves fazê-los com querubins bordados.

[[v2-26-2]]

^<<v2-26-2,2>>^ Cada pano terá 28 côvados^&#42;1^ de comprimento e 4 côvados de largura. Todos os panos devem ser do mesmo tamanho.

[NOTE]
====
. Um côvado equivalia a 44,5 cm. Veja o Ap. B14.
====

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco panos devem ser unidos entre si, formando uma sequência, e os outros cinco panos serão unidos entre si, formando outra sequência.

[[v2-26-4]]

^<<v2-26-4,4>>^ Farás pequenas alças de linha azul na borda do pano que fica no fim de uma sequência, e deves fazer o mesmo na borda do pano que fica na extremidade da outra sequência, onde as duas sequências se juntarão.

[[v2-26-5]]

^<<v2-26-5,5>>^ Farás 50 alças num pano e 50 alças na borda do outro pano, de modo a que as alças fiquem umas de frente para as outras onde as duas sequências se juntarão.

[[v2-26-6]]

^<<v2-26-6,6>>^ Deves fazer 50 colchetes de ouro e unir as sequências de panos por meio dos colchetes, e o tabernáculo irá tornar-se uma só unidade.

[[v2-26-7]]

^<<v2-26-7,7>>^ “Farás também panos de pelo de cabra para servirem de tenda por cima do tabernáculo; farás 11 panos.

[[v2-26-8]]

^<<v2-26-8,8>>^ Cada pano terá 30 côvados de comprimento e 4 côvados de largura. Os 11 panos serão do mesmo tamanho.

[[v2-26-9]]

^<<v2-26-9,9>>^ Deves unir cinco desses panos, unir os outros seis panos e dobrar o sexto pano na parte da frente da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ Deves fazer 50 alças na borda do pano que fica na extremidade de uma sequência, e 50 alças na borda do pano que fica na extremidade da outra sequência, onde elas se juntarão.

[[v2-26-11]]

^<<v2-26-11,11>>^ Deves fazer 50 colchetes de cobre e colocar os colchetes nas alças para unir as partes da tenda, e esta irá tornar-se uma só unidade.

[[v2-26-12]]

^<<v2-26-12,12>>^ Os panos da tenda terão um excedente, e o excedente ficará a pender. Metade do pano que sobrar deve ficar a pender para a parte de trás do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ E a parte que sobrar do comprimento dos panos ficará a pender um côvado para cada lado do tabernáculo, e servirá para cobri-lo.

[[v2-26-14]]

^<<v2-26-14,14>>^ “Farás também para a tenda uma cobertura de pele de carneiro tingida de vermelho e, por cima desta, uma cobertura de pele de foca.

[[v2-26-15]]

^<<v2-26-15,15>>^ “Farás armações de madeira de acácia para o tabernáculo, que serão colocadas na posição vertical.

[[v2-26-16]]

^<<v2-26-16,16>>^ Cada armação terá dez côvados de altura e um côvado e meio de largura.

[[v2-26-17]]

^<<v2-26-17,17>>^ Em cada armação haverá duas espigas^&#42;1^ ligadas uma à outra.^&#42;2^ É assim que farás todas as armações do tabernáculo.

[NOTE]
====
. Ou: “peças verticais”.
. Ou: “paralelas uma à outra”.
====

[[v2-26-18]]

^<<v2-26-18,18>>^ Deves fazer 20 armações para o lado sul do tabernáculo, voltadas para o sul.

[[v2-26-19]]

^<<v2-26-19,19>>^ “Farás 40 bases de prata com encaixe para ficarem debaixo dessas 20 armações: duas bases com encaixe para as duas espigas da primeira armação, e duas bases com encaixe para as duas espigas de cada uma das sucessivas armações.

[[v2-26-20]]

^<<v2-26-20,20>>^ Para o outro lado do tabernáculo, o lado norte, faz 20 armações

[[v2-26-21]]

^<<v2-26-21,21>>^ e as suas 40 bases de prata com encaixe — duas bases com encaixe para a primeira armação e duas bases com encaixe para cada uma das sucessivas armações.

[[v2-26-22]]

^<<v2-26-22,22>>^ Para a parte de trás do tabernáculo, a oeste, farás seis armações.

[[v2-26-23]]

^<<v2-26-23,23>>^ E farás duas armações para servirem como duas escoras para os cantos, na parte de trás do tabernáculo.

[[v2-26-24]]

^<<v2-26-24,24>>^ Essas armações devem ser formadas por duas peças, da base até ao topo, até à primeira argola. É assim que ambas devem ser feitas, formando as duas escoras para os cantos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Portanto, haverá oito armações com as suas dezasseis bases de prata com encaixe — duas bases com encaixe sob a primeira armação e duas bases com encaixe sob cada uma das sucessivas armações.

[[v2-26-26]]

^<<v2-26-26,26>>^ “Farás travessas de madeira de acácia: cinco para as armações de um lado do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ cinco para as armações do outro lado do tabernáculo e cinco para as armações do lado oeste do tabernáculo, a parte de trás.

[[v2-26-28]]

^<<v2-26-28,28>>^ A travessa do meio, que ficará a meia altura das armações, deverá ir de uma extremidade à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ “Revestirás de ouro as armações e nelas farás argolas de ouro por onde passarão as travessas, e revestirás de ouro as travessas.

[[v2-26-30]]

^<<v2-26-30,30>>^ Arma o tabernáculo segundo o projeto que te foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ “Deves fazer uma cortina de linha azul, lã roxa, fio escarlate e linho fino retorcido. Esta terá querubins bordados.

[[v2-26-32]]

^<<v2-26-32,32>>^ Pendura-a em quatro colunas de acácia revestidas de ouro. Os ganchos das colunas devem ser de ouro. As colunas serão fixadas sobre quatro bases de prata com encaixe.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendurarás a cortina abaixo dos colchetes e levarás a Arca do Testemunho para dentro, atrás da cortina. A cortina vai servir-vos de separação entre o Santo e o Santíssimo.

[[v2-26-34]]

^<<v2-26-34,34>>^ Põe a tampa sobre a Arca do Testemunho, no Santíssimo.

[[v2-26-35]]

^<<v2-26-35,35>>^ “Porás a mesa do lado de fora da cortina, e o candelabro no lado sul do tabernáculo, em frente à mesa; e porás a mesa no lado norte.

[[v2-26-36]]

^<<v2-26-36,36>>^ Farás para a entrada da tenda uma cortina tecida^&#42;1^ com linha azul, lã roxa, fio escarlate e linho fino retorcido.

[NOTE]
====
. Ou: “um reposteiro tecido”.
====

[[v2-26-37]]

^<<v2-26-37,37>>^ Farás para essa cortina^&#42;1^ cinco colunas de acácia e irás revesti-las de ouro. Os ganchos das colunas devem ser de ouro, e para estas farás cinco bases com encaixe, de cobre fundido.

[NOTE]
====
. Ou: “esse reposteiro”.
====

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]