include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-10-1]]

^<<v2-10-1,1>>^ Então, Jeová disse a Moisés: “Apresenta-te perante o Faraó, pois permiti que o seu coração e o coração dos seus servos ficassem insensíveis, para que eu pudesse mostrar estes meus sinais mesmo à sua frente.

[[v2-10-2]]

^<<v2-10-2,2>>^ E também para que pudesses falar aos teus filhos e aos teus netos sobre a severidade com que lidei com o Egito e sobre os sinais que realizei entre eles. Assim, vocês certamente saberão que eu sou Jeová.”

[[v2-10-3]]

^<<v2-10-3,3>>^ Portanto, Moisés e Arão apresentaram-se perante o Faraó e disseram-lhe: “Assim disse Jeová, o Deus dos hebreus: ‘Até quando te recusarás a sujeitar-te a mim? Deixa o meu povo partir, para que me sirva.

[[v2-10-4]]

^<<v2-10-4,4>>^ Pois, se continuares a recusar a partida do meu povo, amanhã trarei gafanhotos para dentro dos limites do teu território.

[[v2-10-5]]

^<<v2-10-5,5>>^ Eles cobrirão a superfície da terra de modo que não será possível ver o chão. Devorarão o que te restou depois do granizo e comerão todas as árvores que crescem no teu campo.

[[v2-10-6]]

^<<v2-10-6,6>>^ Encherão as tuas casas, as casas de todos os teus servos e as casas de todo o Egito, como os teus pais e os teus avós nunca viram, desde o dia em que nasceram nesta terra até ao dia de hoje.’” Com isso, voltou-se e retirou-se da presença do Faraó.

[[v2-10-7]]

^<<v2-10-7,7>>^ Então, os servos do Faraó disseram-lhe: “Até quando é que este homem continuará a ameaçar-nos?^&#42;1^ Deixe os homens partir, para que sirvam a Jeová, o Deus deles. Não percebe que o Egito está arruinado?”

[NOTE]
====
. Lit.: “será um laço para nós”.
====

[[v2-10-8]]

^<<v2-10-8,8>>^ Assim, Moisés e Arão foram levados de volta ao Faraó, e ele disse-lhes: “Vão, sirvam a Jeová, o vosso Deus. Mas quem é que irá?”

[[v2-10-9]]

^<<v2-10-9,9>>^ Moisés respondeu: “Levaremos os nossos jovens, os nossos idosos, os nossos filhos, as nossas filhas, as nossas ovelhas e o nosso gado, porque realizaremos uma festividade para Jeová.”

[[v2-10-10]]

^<<v2-10-10,10>>^ Ele disse-lhes: “Se um dia eu vos deixar partir com os vossos filhos, é porque Jeová realmente está convosco! É claro que vocês têm más intenções.

[[v2-10-11]]

^<<v2-10-11,11>>^ Não! Só os homens é que podem partir e servir a Jeová, pois foi isso que vocês pediram.” Com isto, eles foram expulsos da presença do Faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ Jeová disse então a Moisés: “Estende a mão sobre a terra do Egito para chamar os gafanhotos, para que venham sobre a terra do Egito e devorem toda a vegetação do país, tudo o que o granizo deixou sobrar.”

[[v2-10-13]]

^<<v2-10-13,13>>^ Moisés estendeu imediatamente o seu bastão sobre a terra do Egito, e Jeová fez soprar um vento leste sobre o país durante todo aquele dia e toda aquela noite. Quando amanheceu, o vento leste trouxe os gafanhotos.

[[v2-10-14]]

^<<v2-10-14,14>>^ E os gafanhotos vieram sobre toda a terra do Egito e desceram sobre todo o território do Egito. A praga foi devastadora. Nunca antes houve uma quantidade tão grande de gafanhotos, nem voltará a haver.

[[v2-10-15]]

^<<v2-10-15,15>>^ Cobriram a superfície do país inteiro, e aquela terra ficou escura por causa deles. Devoraram toda a vegetação e todos os frutos das árvores que o granizo tinha deixado sobrar. Não restou nada de verde nas árvores nem na vegetação do campo, em toda a terra do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ Portanto, o Faraó chamou rapidamente Moisés e Arão, e disse: “Pequei contra Jeová, o vosso Deus, e contra vocês.

[[v2-10-17]]

^<<v2-10-17,17>>^ Agora, por favor, perdoem só mais esta vez o meu pecado e supliquem a Jeová, o vosso Deus, que ao menos afaste de mim esta praga mortífera.”

[[v2-10-18]]

^<<v2-10-18,18>>^ Então, ele^&#42;1^ retirou-se da presença do Faraó e fez súplicas a Jeová.

[NOTE]
====
. Aparentemente, refere-se a Moisés.
====

[[v2-10-19]]

^<<v2-10-19,19>>^ Assim, Jeová mudou a direção do vento, fazendo soprar um forte vento oeste, que levou os gafanhotos embora e os lançou no mar Vermelho. Não sobrou nem um único gafanhoto em todo o território do Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ No entanto, Jeová permitiu que o coração do Faraó ficasse endurecido, e ele não deixou os israelitas partirem.

[[v2-10-21]]

^<<v2-10-21,21>>^ Então, Jeová disse a Moisés: “Estende a mão para os céus, para que haja escuridão sobre a terra do Egito, uma escuridão tão densa que se possa apalpar.”

[[v2-10-22]]

^<<v2-10-22,22>>^ Moisés estendeu imediatamente a mão para os céus e houve uma densa escuridão em toda a terra do Egito, por três dias.

[[v2-10-23]]

^<<v2-10-23,23>>^ Eles não se viam uns aos outros e, por três dias, nenhum deles saiu do lugar onde estava, mas todos os israelitas tinham luz onde moravam.

[[v2-10-24]]

^<<v2-10-24,24>>^ O Faraó chamou então Moisés e disse: “Vai, serve a Jeová. Somente as vossas ovelhas e o vosso gado ficarão. Até os vossos filhos poderão ir convosco.”

[[v2-10-25]]

^<<v2-10-25,25>>^ Contudo, Moisés disse: “Terá, também, de fornecer^&#42;1^ os animais para fazermos sacrifícios e ofertas queimadas, para oferecermos a Jeová, o nosso Deus.

[NOTE]
====
. Ou: “deixar-nos levar”.
====

[[v2-10-26]]

^<<v2-10-26,26>>^ O nosso gado também irá connosco. Não se deixará ficar nem um único animal,^&#42;1^ porque usaremos alguns deles para adorar a Jeová, o nosso Deus, e nós não sabemos o que ofereceremos em adoração a Jeová até lá chegarmos.”

[NOTE]
====
. Lit.: “casco”.
====

[[v2-10-27]]

^<<v2-10-27,27>>^ Então, Jeová permitiu que o coração do Faraó ficasse endurecido, e ele não concordou em deixá-los partir.

[[v2-10-28]]

^<<v2-10-28,28>>^ O Faraó disse-lhe: “Sai da minha presença! Não tentes ver a minha face novamente, pois no dia em que vires a minha face, morrerás.”

[[v2-10-29]]

^<<v2-10-29,29>>^ Diante disso, Moisés disse: “Farei como ordenou. Não tentarei ver a sua face novamente.”

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]