include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-9-1]]

^<<v2-9-1,1>>^ Por isso, Jeová disse a Moisés: “Apresenta-te perante o Faraó e diz-lhe: ‘Assim disse Jeová, o Deus dos hebreus: “Deixa o meu povo partir, para que me sirva.

[[v2-9-2]]

^<<v2-9-2,2>>^ Se te recusares a deixá-los partir e continuares a detê-los,

[[v2-9-3]]

^<<v2-9-3,3>>^ fica a saber que a mão de Jeová virá contra o teu gado que está no campo. Haverá uma praga devastadora que atingirá os cavalos, os jumentos, os camelos, os bois e as ovelhas.

[[v2-9-4]]

^<<v2-9-4,4>>^ Jeová, porém, certamente fará distinção entre o gado de Israel e o gado do Egito, e não morrerá nada do que pertence aos israelitas.”’”

[[v2-9-5]]

^<<v2-9-5,5>>^ Além do mais, Jeová determinou o tempo para isso, dizendo: “Amanhã, Jeová fará isto no país.”

[[v2-9-6]]

^<<v2-9-6,6>>^ E Jeová assim o fez logo no dia seguinte, e começaram a morrer animais de todo o tipo de gado do Egito, mas não morreu nenhum animal do gado de Israel.

[[v2-9-7]]

^<<v2-9-7,7>>^ Quando o Faraó mandou verificar, constatou que nenhum animal do gado de Israel tinha morrido. Apesar disso, o coração do Faraó continuou insensível e ele não deixou o povo partir.

[[v2-9-8]]

^<<v2-9-8,8>>^ Jeová disse então a Moisés e a Arão: “Encham ambas as mãos com cinza de um forno, e Moisés deve atirá-la ao ar, diante do Faraó.

[[v2-9-9]]

^<<v2-9-9,9>>^ Ela irá tornar-se pó sobre toda a terra do Egito e transformar-se em furúnculos com pus nos homens e nos animais, em toda a terra do Egito.”

[[v2-9-10]]

^<<v2-9-10,10>>^ Por conseguinte, apanharam cinza de um forno e apresentaram-se perante o Faraó; Moisés atirou-a ao ar, e esta transformou-se em furúnculos com pus nos homens e nos animais.

[[v2-9-11]]

^<<v2-9-11,11>>^ Os sacerdotes-magos não conseguiam ficar diante de Moisés, pois tinham surgido furúnculos nos sacerdotes-magos e em todos os egípcios.

[[v2-9-12]]

^<<v2-9-12,12>>^ No entanto, Jeová permitiu que o coração do Faraó ficasse endurecido, e ele não escutou Moisés e Arão, assim como Jeová tinha dito a Moisés.

[[v2-9-13]]

^<<v2-9-13,13>>^ Jeová disse então a Moisés: “Levanta-te de manhã cedo, apresenta-te perante o Faraó e diz-lhe: ‘Assim disse Jeová, o Deus dos hebreus: “Deixa o meu povo partir, para que me sirva.

[[v2-9-14]]

^<<v2-9-14,14>>^ Pois agora vou dirigir todos os meus golpes para atingir o teu coração, os teus servos e o teu povo, para que saibas que não há ninguém semelhante a mim em toda a terra.

[[v2-9-15]]

^<<v2-9-15,15>>^ Pois eu já poderia ter estendido a mão para te atingir a ti e ao teu povo com uma praga devastadora, e terias sido eliminado^&#42;1^ da face da terra.

[NOTE]
====
. Ou: “terias desaparecido”.
====

[[v2-9-16]]

^<<v2-9-16,16>>^ Contudo, foi exatamente por esta razão que te deixei vivo: para te mostrar o meu poder e para que o meu nome seja declarado em toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Ainda te comportas de maneira arrogante para com o meu povo, não o deixando partir?

[[v2-9-18]]

^<<v2-9-18,18>>^ Amanhã, por volta desta hora, farei cair uma tempestade de granizo como nunca houve no Egito, desde o dia em que foi fundado até hoje.

[[v2-9-19]]

^<<v2-9-19,19>>^ Portanto, manda recolher todo o teu gado e tudo o que é teu no campo. Todos os homens e animais que estiverem no campo e não tiverem sido recolhidos morrerão quando o granizo cair sobre eles.”’”

[[v2-9-20]]

^<<v2-9-20,20>>^ Entre os servos do Faraó, todos os que temiam a palavra de Jeová recolheram rapidamente os seus próprios servos e o seu gado ao abrigo,

[[v2-9-21]]

^<<v2-9-21,21>>^ mas todos os que não levaram a sério a palavra de Jeová deixaram os seus servos e os seus animais no campo.

[[v2-9-22]]

^<<v2-9-22,22>>^ Jeová disse então a Moisés: “Estende a mão para os céus, a fim de que caia granizo sobre toda a terra do Egito, sobre homens e animais, e sobre toda a vegetação do campo na terra do Egito.”

[[v2-9-23]]

^<<v2-9-23,23>>^ Assim, Moisés estendeu o seu bastão para os céus, e Jeová mandou trovões e granizo; desceu fogo^&#42;1^ sobre a terra, e Jeová fez com que chovesse granizo sobre a terra do Egito.

[NOTE]
====
. Possível descrição de fortes relâmpagos.
====

[[v2-9-24]]

^<<v2-9-24,24>>^ Havia granizo, e havia fogo relampejante no meio do granizo. A chuva de granizo foi muito forte. Nunca ocorrera nenhuma semelhante a esta no país, desde que o Egito se tornara uma nação.

[[v2-9-25]]

^<<v2-9-25,25>>^ O granizo atingiu tudo no campo por toda a terra do Egito, desde homens até animais, atingiu toda a vegetação e destroçou todas as árvores do campo.

[[v2-9-26]]

^<<v2-9-26,26>>^ Somente na terra de Gósen, onde estavam os israelitas, é que não houve granizo.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então o Faraó mandou chamar Moisés e Arão, e disse-lhes: “Desta vez, eu pequei. Jeová é justo, e eu e o meu povo estamos errados.

[[v2-9-28]]

^<<v2-9-28,28>>^ Supliquem a Jeová, para que cessem os trovões e o granizo da parte de Deus. Então, estarei disposto a deixar-vos partir e não permanecerão aqui.”

[[v2-9-29]]

^<<v2-9-29,29>>^ Portanto, Moisés disse-lhe: “Assim que eu sair da cidade, estenderei as mãos diante de Jeová. Os trovões cessarão e o granizo não continuará, a fim de que saiba que a terra pertence a Jeová.

[[v2-9-30]]

^<<v2-9-30,30>>^ Mas, quanto a si e aos seus servos, já sei que nem assim temerão a Jeová Deus.”

[[v2-9-31]]

^<<v2-9-31,31>>^ O linho e a cevada foram destruídos, porque a cevada estava com espigas e o linho estava em flor.

[[v2-9-32]]

^<<v2-9-32,32>>^ Porém, o trigo e a espelta não foram destruídos, porque eram safras tardias.^&#42;1^

[NOTE]
====
. Ou: “amadurecem mais tarde”.
====

[[v2-9-33]]

^<<v2-9-33,33>>^ Assim, Moisés retirou-se da presença do Faraó e saiu da cidade; estendeu as mãos diante de Jeová, e os trovões e o granizo cessaram, e a chuva parou de cair sobre a terra.

[[v2-9-34]]

^<<v2-9-34,34>>^ Quando o Faraó viu que a chuva, o granizo e os trovões tinham parado, pecou novamente e endureceu o coração, tanto ele como os seus servos.

[[v2-9-35]]

^<<v2-9-35,35>>^ O coração do Faraó continuou endurecido, e ele não deixou os israelitas partir, assim como Jeová tinha dito por meio de Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]