include::./index.adoc[]

[[v2-19-0]]
=== Êxodo, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-19-1]]

^<<v2-19-1,1>>^ No terceiro mês após a saída dos israelitas da terra do Egito, no mesmo dia,^&#42;1^ eles chegaram ao deserto do Sinai.

[NOTE]
====
. Aparentemente, esta expressão refere-se ao mesmo dia em que saíram de Refidim.
====

[[v2-19-2]]

^<<v2-19-2,2>>^ Partiram de Refidim, chegaram ao deserto do Sinai e acamparam no deserto. Foi lá que Israel acampou, diante do monte.

[[v2-19-3]]

^<<v2-19-3,3>>^ Então, Moisés subiu ao encontro do verdadeiro Deus. Jeová chamou-o a partir do monte e disse: “Isto é o que deves dizer à casa de Jacó e comunicar aos israelitas:

[[v2-19-4]]

^<<v2-19-4,4>>^ ‘Viram com os vossos próprios olhos o que fiz ao Egito, e como vos carreguei sobre asas de águias e vos trouxe até mim.

[[v2-19-5]]

^<<v2-19-5,5>>^ Agora, se obedecerem fielmente à minha voz e guardarem o meu pacto, certamente se tornarão a minha propriedade especial^&#42;1^ dentre todos os povos, pois toda a terra me pertence.

[NOTE]
====
. Ou: “estimada”.
====

[[v2-19-6]]

^<<v2-19-6,6>>^ Hão de tornar-se para mim um reino de sacerdotes e uma nação santa.’ Estas são as palavras que deves dizer aos israelitas.”

[[v2-19-7]]

^<<v2-19-7,7>>^ Moisés foi então convocar os anciãos do povo, e comunicou-lhes todas estas palavras que Jeová lhe tinha ordenado.

[[v2-19-8]]

^<<v2-19-8,8>>^ E todo o povo respondeu unanimemente: “Estamos dispostos a fazer tudo o que Jeová disse.” Moisés levou imediatamente a resposta do povo a Jeová.

[[v2-19-9]]

^<<v2-19-9,9>>^ E Jeová disse a Moisés: “Vê, virei até ti numa nuvem escura, para que o povo ouça quando eu falar contigo e também para que tenham sempre fé em ti.” Assim, Moisés relatou a Jeová as palavras do povo.

[[v2-19-10]]

^<<v2-19-10,10>>^ Jeová disse a Moisés: “Vai ao povo, santifica-os hoje e amanhã, e eles devem lavar as suas roupas.

[[v2-19-11]]

^<<v2-19-11,11>>^ E devem estar prontos para o terceiro dia, porque no terceiro dia Jeová descerá sobre o monte Sinai perante os olhos de todo o povo.

[[v2-19-12]]

^<<v2-19-12,12>>^ Estabelece limites para o povo ao redor do monte e diz-lhes: ‘Tenham o cuidado de não subir ao monte; nem toquem na sua extremidade. Quem tocar no monte certamente será morto.

[[v2-19-13]]

^<<v2-19-13,13>>^ Ninguém deverá tocar na pessoa culpada: esta será apedrejada ou trespassada.^&#42;1^ Quer seja animal, quer seja homem, não viverá.’ Mas, quando soar a buzina de chifre de carneiro, eles poderão aproximar-se do monte.”

[NOTE]
====
. Talvez trespassada com uma flecha.
====

[[v2-19-14]]

^<<v2-19-14,14>>^ Então, Moisés desceu do monte até onde estava o povo e começou a santificar o povo, e eles lavaram as suas roupas.

[[v2-19-15]]

^<<v2-19-15,15>>^ Ele disse ao povo: “Preparem-se para o terceiro dia. Não tenham relações sexuais.”^&#42;1^

[NOTE]
====
. Lit.: “Não se aproximem de uma mulher.”
====

[[v2-19-16]]

^<<v2-19-16,16>>^ Na manhã do terceiro dia, houve trovões e relâmpagos, uma pesada nuvem cobriu o monte, e ouviu-se um som muito alto de buzina. E todo o povo no acampamento começou a tremer.

[[v2-19-17]]

^<<v2-19-17,17>>^ Moisés levou então o povo para fora do acampamento ao encontro do verdadeiro Deus, e eles posicionaram-se no sopé do monte.

[[v2-19-18]]

^<<v2-19-18,18>>^ Todo o monte Sinai fumegava, porque Jeová tinha descido sobre ele em fogo; e o fumo subia como o fumo de uma fornalha, e todo o monte tremia violentamente.

[[v2-19-19]]

^<<v2-19-19,19>>^ Quando o som da buzina se tornou mais forte, Moisés falou, e o verdadeiro Deus respondeu-lhe.

[[v2-19-20]]

^<<v2-19-20,20>>^ E Jeová desceu sobre o monte Sinai, sobre o cume do monte. Jeová chamou então Moisés ao cume do monte, e Moisés subiu.

[[v2-19-21]]

^<<v2-19-21,21>>^ Jeová disse a Moisés: “Desce e avisa o povo para que não tente ultrapassar os limites a fim de olhar para Jeová; caso contrário, muitos deles morrerão.

[[v2-19-22]]

^<<v2-19-22,22>>^ E que os sacerdotes que se aproximam regularmente de Jeová se santifiquem, para que Jeová não os golpeie.”^&#42;1^

[NOTE]
====
. Lit.: “não irrompa sobre eles”.
====

[[v2-19-23]]

^<<v2-19-23,23>>^ Moisés disse então a Jeová: “O povo não pode subir ao monte Sinai, porque tu já nos avisaste, dizendo: ‘Estabelece limites ao redor do monte e torna-o sagrado.’”

[[v2-19-24]]

^<<v2-19-24,24>>^ No entanto, Jeová disse-lhe: “Vai, desce, e depois sobe novamente com Arão, mas não permitas que os sacerdotes e o povo ultrapassem os limites para subir ao encontro de Jeová, para que ele não os golpeie.”

[[v2-19-25]]

^<<v2-19-25,25>>^ Portanto, Moisés desceu até onde estava o povo e disse-lhes isso.

'''

xref:002-exodo/002-exodo-018.adoc#v2-18-0[&#60; Capítulo Anterior] | <<v2-19-0,Topo>> | xref:002-exodo/002-exodo-020.adoc#v2-20-0[Próximo Capítulo &#62;]