include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v2-28-1]]

^<<v2-28-1,1>>^ “Deves chamar dentre os israelitas o teu irmão Arão, com os seus filhos, para que ele me sirva como sacerdote. Chama Arão e os seus filhos: Nadabe, Abiú, Eleazar e Itamar.

[[v2-28-2]]

^<<v2-28-2,2>>^ Deves fazer vestes sagradas para o teu irmão Arão, para lhe dar glória e beleza.

[[v2-28-3]]

^<<v2-28-3,3>>^ E diz a todas as pessoas habilidosas^&#42;1^ a quem enchi com o espírito de sabedoria que façam as vestes para a santificação de Arão, a fim de que ele me sirva como sacerdote.

[NOTE]
====
. Lit.: “todos os sábios de coração”.
====

[[v2-28-4]]

^<<v2-28-4,4>>^ “Estas são as vestes que farão: um peitoral, um éfode, uma túnica sem mangas, uma veste comprida axadrezada, um turbante e uma faixa. Farão essas vestes sagradas para o teu irmão Arão e para os seus filhos, a fim de que ele me sirva como sacerdote.

[[v2-28-5]]

^<<v2-28-5,5>>^ Os trabalhadores habilidosos usarão o ouro, a linha azul, a lã roxa, o fio escarlate e o linho fino.

[[v2-28-6]]

^<<v2-28-6,6>>^ “Devem fazer o éfode com ouro, linha azul, lã roxa, fio escarlate e linho fino retorcido, e deve ser bordado.

[[v2-28-7]]

^<<v2-28-7,7>>^ Deve ter duas tiras que passem pelos ombros e que sejam unidas nas suas duas extremidades superiores.

[[v2-28-8]]

^<<v2-28-8,8>>^ O cinto bordado,^&#42;1^ que fica preso ao éfode e serve para mantê-lo no lugar, deve ser feito com os mesmos materiais: ouro, linha azul, lã roxa, fio escarlate e linho fino retorcido.

[NOTE]
====
. Ou: “A faixa para a cintura”.
====

[[v2-28-9]]

^<<v2-28-9,9>>^ “Deves pegar em duas pedras de ónix e gravar nelas os nomes dos filhos de Israel:

[[v2-28-10]]

^<<v2-28-10,10>>^ seis nomes numa pedra e os seis nomes restantes na outra, por ordem de nascimento.

[[v2-28-11]]

^<<v2-28-11,11>>^ Um lapidador gravará os nomes dos filhos de Israel nas duas pedras, assim como se grava um selo. Depois, deves mandar colocá-las em engastes de ouro.

[[v2-28-12]]

^<<v2-28-12,12>>^ Deves pôr as duas pedras nas tiras do éfode, que passam pelos ombros, como pedras memoriais para os filhos de Israel; e Arão levará os seus nomes perante Jeová sobre os ombros, como recordação.

[[v2-28-13]]

^<<v2-28-13,13>>^ Deves fazer engastes de ouro

[[v2-28-14]]

^<<v2-28-14,14>>^ e duas pequenas correntes de ouro puro entrelaçadas em forma de cordões, e deves prender as pequenas correntes entrelaçadas nos engastes.

[[v2-28-15]]

^<<v2-28-15,15>>^ “Deves mandar um bordador fazer o peitoral do julgamento. O peitoral deve ser feito como o éfode: com ouro, linha azul, lã roxa, fio escarlate e linho fino retorcido.

[[v2-28-16]]

^<<v2-28-16,16>>^ Quando dobrado, formará um quadrado de um palmo^&#42;1^ de comprimento e um palmo de largura.

[NOTE]
====
. Cerca de 22,2 cm. Veja o Ap. B14.
====

[[v2-28-17]]

^<<v2-28-17,17>>^ Deves colocar nele pedras engastadas, quatro fileiras de pedras. A primeira fileira será de rubi, topázio e esmeralda.

[[v2-28-18]]

^<<v2-28-18,18>>^ A segunda fileira será de turquesa, safira e jaspe.

[[v2-28-19]]

^<<v2-28-19,19>>^ A terceira fileira será de pedra de léshem,^&#42;1^ ágata e ametista.

[NOTE]
====
. Não se sabe qual é a pedra; possivelmente, refere-se a âmbar, jacinto, opala ou turmalina.
====

[[v2-28-20]]

^<<v2-28-20,20>>^ A quarta fileira será de crisólito, ónix e jade. Todas estas pedras devem ser colocadas em engastes de ouro.

[[v2-28-21]]

^<<v2-28-21,21>>^ As pedras corresponderão aos nomes dos 12 filhos de Israel. Cada uma delas deve ser gravada como se grava um selo, cada nome representando uma das 12 tribos.

[[v2-28-22]]

^<<v2-28-22,22>>^ “Deves fazer para o peitoral pequenas correntes entrelaçadas de ouro puro, em forma de cordões.

[[v2-28-23]]

^<<v2-28-23,23>>^ Deves fazer duas argolas de ouro para o peitoral e colocar as duas argolas nas duas extremidades do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ E deves passar os dois cordões de ouro através das duas argolas nas extremidades do peitoral.

[[v2-28-25]]

^<<v2-28-25,25>>^ Deves passar as pontas dos dois cordões pelos dois engastes, e prendê-los nos ombros, nas tiras do éfode, na sua parte frontal.

[[v2-28-26]]

^<<v2-28-26,26>>^ Deves fazer duas argolas de ouro e colocá-las nas duas extremidades do peitoral, na parte de dentro, no lado voltado para o éfode.

[[v2-28-27]]

^<<v2-28-27,27>>^ E deves fazer mais duas argolas de ouro e colocá-las na parte externa do éfode, abaixo das duas tiras que passam pelos ombros, perto do ponto de junção, acima do cinto bordado^&#42;1^ do éfode.

[NOTE]
====
. Ou: “da faixa para a cintura”.
====

[[v2-28-28]]

^<<v2-28-28,28>>^ Para manter o peitoral no lugar, deve-se amarrar as argolas do peitoral às argolas do éfode com um cordão azul. Isso fará com que o peitoral fique no lugar, sobre o éfode, acima do cinto bordado.^&#42;1^

[NOTE]
====
. Ou: “da faixa para a cintura”.
====

[[v2-28-29]]

^<<v2-28-29,29>>^ “Quando entrar no Santo, Arão deve levar os nomes dos filhos de Israel no peitoral do julgamento, sobre o seu coração, como recordação permanente perante Jeová.

[[v2-28-30]]

^<<v2-28-30,30>>^ Colocarás dentro do peitoral do julgamento o Urim e o Tumim,^&#42;1^ e estes ficarão sobre o coração de Arão quando ele entrar na presença de Jeová. Assim, Arão levará sempre sobre o seu coração, perante Jeová, estes instrumentos que servirão para realizar os julgamentos dos israelitas.

[NOTE]
====
. Veja o Glossário, “Urim e Tumim”.
====

[[v2-28-31]]

^<<v2-28-31,31>>^ “Deves fazer a túnica sem mangas do éfode inteiramente de linha azul.

[[v2-28-32]]

^<<v2-28-32,32>>^ Haverá uma abertura na sua parte superior,^&#42;1^ no meio. Ao redor da abertura deve haver um acabamento feito por um tecelão. Será como a abertura de uma cota de malha, para que não se rasgue.

[NOTE]
====
. Ou: “abertura para a cabeça”.
====

[[v2-28-33]]

^<<v2-28-33,33>>^ Deves fazer romãs com linha azul, lã roxa e fio escarlate à volta de toda a barra, intercaladas com sinos de ouro.

[[v2-28-34]]

^<<v2-28-34,34>>^ Deves alternar um sino de ouro com uma romã, um sino de ouro com uma romã, à volta de toda a barra da túnica sem mangas.

[[v2-28-35]]

^<<v2-28-35,35>>^ Arão deve vesti-la para realizar o serviço sacerdotal,^&#42;1^ e o som dos sinos será ouvido quando ele entrar no santuário perante Jeová e quando sair de lá, para que não morra.

[NOTE]
====
. Ou: “para ministrar”.
====

[[v2-28-36]]

^<<v2-28-36,36>>^ “Deves fazer uma lâmina brilhante de ouro puro e, como se grava um selo, gravar nela o seguinte: ‘A santidade pertence a Jeová’.

[[v2-28-37]]

^<<v2-28-37,37>>^ Prende-a ao turbante com um cordão azul. A lâmina deve ficar na parte da frente do turbante.

[[v2-28-38]]

^<<v2-28-38,38>>^ Ficará na testa de Arão, e Arão será responsável caso alguém cometa um erro contra as coisas sagradas que os israelitas santificam quando as oferecem como dádivas sagradas. Ficará sempre na testa de Arão, para que eles obtenham aprovação perante Jeová.

[[v2-28-39]]

^<<v2-28-39,39>>^ “Deves tecer a veste comprida axadrezada de linho fino, fazer um turbante de linho fino e tecer uma faixa.

[[v2-28-40]]

^<<v2-28-40,40>>^ “Farás também vestes compridas, faixas e coberturas para a cabeça dos filhos de Arão, para lhes dar glória e beleza.

[[v2-28-41]]

^<<v2-28-41,41>>^ Vestirás o teu irmão Arão e os seus filhos, e deves ungi-los, ordená-los^&#42;1^ e santificá-los, e eles devem servir-me como sacerdotes.

[NOTE]
====
. Lit.: “encher a mão deles”.
====

[[v2-28-42]]

^<<v2-28-42,42>>^ Faz também calções^&#42;1^ de linho para lhes cobrir a nudez. Estes devem ir das ancas até às coxas.

[NOTE]
====
. Ou: “roupa interior”.
====

[[v2-28-43]]

^<<v2-28-43,43>>^ Arão e os seus filhos devem usá-los quando entrarem na tenda de reunião ou quando se aproximarem do altar para servir no lugar santo, para que não se tornem culpados e morram. Este é um decreto permanente para ele e para a sua descendência.^&#42;1^

[NOTE]
====
. Lit.: “semente”.
====

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]