include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-1-1]]

^<<v7-1-1,1>>^ Após a morte de Josué, os israelitas^&#42;1^ consultaram a Jeová: “Quem de nós subirá primeiro para lutar contra os cananeus?”

[NOTE]
====
. Lit.: “filhos de Israel”.
====

[[v7-1-2]]

^<<v7-1-2,2>>^ Jeová respondeu: “Judá subirá. Vou entregar^&#42;1^ esta terra nas suas mãos.”

[NOTE]
====
. Ou: “Entreguei”.
====

[[v7-1-3]]

^<<v7-1-3,3>>^ Então, Judá disse ao seu irmão Simeão: “Sobe comigo ao território que me foi designado^&#42;1^ para lutarmos contra os cananeus. Depois irei contigo ao território que te foi designado.” Portanto, Simeão foi com ele.

[NOTE]
====
. Lit.: “à minha sorte”.
====

[[v7-1-4]]

^<<v7-1-4,4>>^ Quando Judá subiu, Jeová entregou nas suas mãos os cananeus e os perizeus, e eles derrotaram 10 000 homens em Bezeque.

[[v7-1-5]]

^<<v7-1-5,5>>^ Encontraram Adoni-Bezeque em Bezeque, e ali lutaram contra ele e derrotaram os cananeus e os perizeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Quando Adoni-Bezeque fugiu, perseguiram-no, capturaram-no e amputaram-lhe os polegares das mãos e os dedos grandes dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então, Adoni-Bezeque disse: “Setenta reis, cujos polegares das mãos e dedos grandes dos pés lhes foram amputados, apanham comida debaixo da minha mesa. Assim como fiz, assim me retribuiu Deus.” Depois levaram-no para Jerusalém, e morreu ali.

[[v7-1-8]]

^<<v7-1-8,8>>^ Além disso, os homens de Judá lutaram contra Jerusalém e tomaram-na. Golpearam a cidade com a espada e incendiaram-na.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois, os homens de Judá desceram para lutar contra os cananeus que moravam na região montanhosa, no Neguebe e na Sefelá.

[[v7-1-10]]

^<<v7-1-10,10>>^ Então, Judá avançou contra os cananeus que moravam em Hébron (anteriormente o nome de Hébron era Quiriate-Arba), e mataram Sesai, Aimã e Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali avançaram contra os habitantes de Debir. (Anteriormente o nome de Debir era Quiriate-Sefer.)

[[v7-1-12]]

^<<v7-1-12,12>>^ A seguir, Caleb disse: “Ao homem que golpear Quiriate-Sefer e a tomar, darei a minha filha Acsa como esposa.”

[[v7-1-13]]

^<<v7-1-13,13>>^ E Otniel, filho de Quenaz, irmão mais novo de Caleb, tomou a cidade. Portanto, Caleb deu-lhe a sua filha Acsa como esposa.

[[v7-1-14]]

^<<v7-1-14,14>>^ Enquanto ela ia para casa, insistiu com Otniel para que pedisse ao pai dela um campo. Então, ela desceu do jumento,^&#42;1^ e Caleb perguntou-lhe: “O que é que queres?”

[NOTE]
====
. Ou, possivelmente: “ela bateu as mãos enquanto estava montada no jumento”.
====

[[v7-1-15]]

^<<v7-1-15,15>>^ Ela respondeu: “Por favor, dê-me uma bênção, pois o senhor deu-me um pedaço de terra no sul;^&#42;1^ dê-me também Gulote-Maim.”^&#42;2^ Assim, Caleb deu-lhe Gulote Alta e Gulote Baixa.

[NOTE]
====
. Ou: “no Neguebe”.
. Que significa “bacias (tigelas) de água”.
====

[[v7-1-16]]

^<<v7-1-16,16>>^ E os descendentes do queneu, sogro de Moisés, subiram da cidade das palmeiras com o povo de Judá e foram para o deserto^&#42;1^ de Judá, a sul de Arade. Foram para lá e estabeleceram-se entre o povo.

[NOTE]
====
. Veja o Glossário.
====

[[v7-1-17]]

^<<v7-1-17,17>>^ Mas Judá avançou com o seu irmão Simeão, e eles atacaram os cananeus que moravam em Zefate e entregaram-na à destruição.^&#42;1^ Assim, deram à cidade o nome de Hormá.^&#42;2^

[NOTE]
====
. Ou: “devotaram-na à destruição”. Veja o Glossário.
. Que significa “devotamento à destruição”.
====

[[v7-1-18]]

^<<v7-1-18,18>>^ Então, Judá tomou Gaza e o seu território, Ascalom e o seu território, e Ecrom e o seu território.

[[v7-1-19]]

^<<v7-1-19,19>>^ Jeová estava com Judá, e eles tomaram posse da região montanhosa, mas não conseguiram expulsar os habitantes da planície,^&#42;1^ porque tinham carros de guerra com foices de ferro.^&#42;2^

[NOTE]
====
. Ou: “ do vale”.
. Lit.: “carros de ferro”.
====

[[v7-1-20]]

^<<v7-1-20,20>>^ Deram Hébron a Caleb, assim como Moisés tinha prometido, e ele expulsou dali os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Porém, os benjaminitas não expulsaram os jebuseus que moravam em Jerusalém. Assim, os jebuseus continuam a morar com os benjaminitas em Jerusalém até ao dia de hoje.

[[v7-1-22]]

^<<v7-1-22,22>>^ Entretanto, a casa de José subiu contra Betel, e Jeová estava com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ A casa de José estava a espiar Betel (a propósito, anteriormente o nome da cidade era Luz),

[[v7-1-24]]

^<<v7-1-24,24>>^ e os espiões viram um homem a sair da cidade. Então, disseram-lhe: “Por favor, mostra-nos como entrar na cidade, e nós vamos tratar-te com bondade.”^&#42;1^

[NOTE]
====
. Lit.: “vamos mostrar-te amor leal”.
====

[[v7-1-25]]

^<<v7-1-25,25>>^ Assim, o homem mostrou-lhes como entrar na cidade, e eles golpearam a cidade com a espada, mas deixaram o homem e toda a sua família ir em liberdade.

[[v7-1-26]]

^<<v7-1-26,26>>^ O homem foi para a terra dos hititas, construiu uma cidade e chamou-lhe Luz, e este é o seu nome até ao dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ Manassés não conquistou Bete-Seã e as suas aldeias dependentes,^&#42;1^ nem Taanaque e as suas aldeias dependentes, nem os habitantes de Dor e as suas aldeias dependentes, nem os habitantes de Ibleão e as suas aldeias dependentes, nem os habitantes de Megido e as suas aldeias dependentes. Os cananeus persistiam em morar nessa região.

[NOTE]
====
. Ou: “ao redor”.
====

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando Israel se tornou mais forte, sujeitaram os cananeus a trabalhos forçados, mas não os expulsaram completamente.

[[v7-1-29]]

^<<v7-1-29,29>>^ Efraim também não expulsou os cananeus que moravam em Gezer. Os cananeus continuaram a morar em Gezer, no meio dos efraimitas.

[[v7-1-30]]

^<<v7-1-30,30>>^ Zebulão não expulsou os habitantes de Quitrom, nem os habitantes de Naalol. Os cananeus continuaram a morar no meio deles e foram sujeitos a trabalhos forçados.

[[v7-1-31]]

^<<v7-1-31,31>>^ Aser não expulsou os habitantes de Aco, nem os habitantes de Sídon, de Alabe, de Aczibe, de Helba, de Afeque e de Reobe.

[[v7-1-32]]

^<<v7-1-32,32>>^ Assim, os aseritas continuaram a morar no meio dos cananeus que viviam naquela terra, visto que não os expulsaram.

[[v7-1-33]]

^<<v7-1-33,33>>^ Naftali não expulsou os habitantes de Bete-Semes, nem os habitantes de Bete-Anate, mas eles continuaram a morar no meio dos cananeus que viviam naquela terra. Os habitantes de Bete-Semes e de Bete-Anate passaram a fazer trabalhos forçados para eles.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus confinaram os danitas à região montanhosa, não lhes permitindo descer até à planície.^&#42;1^

[NOTE]
====
. Ou: “ao vale”.
====

[[v7-1-35]]

^<<v7-1-35,35>>^ Os amorreus estavam decididos a morar na montanha de Heres, em Aijalom e em Saalbim. Contudo, quando o poder da casa de José aumentou,^&#42;1^ eles foram sujeitos a trabalhos forçados.

[NOTE]
====
. Lit.: “a mão . . . se tornou pesada”.
====

[[v7-1-36]]

^<<v7-1-36,36>>^ O território dos amorreus começava na subida de Acrabim e em Sela, e ia dali para cima.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]