include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-13-1]]

^<<v7-13-1,1>>^ Os israelitas fizeram novamente o que era mau aos olhos de Jeová, e Jeová entregou-os nas mãos dos filisteus durante 40 anos.

[[v7-13-2]]

^<<v7-13-2,2>>^ Naquela altura, havia um homem de Zorá, da família dos danitas, cujo nome era Manoá. A sua esposa era estéril e não tinha filhos.

[[v7-13-3]]

^<<v7-13-3,3>>^ Certo dia, o anjo de Jeová apareceu à mulher e disse-lhe: “Apesar de seres estéril e não teres filhos, ficarás grávida e darás à luz um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Tem cuidado para não beberes vinho nem outras bebidas alcoólicas, e não comas nada impuro.

[[v7-13-5]]

^<<v7-13-5,5>>^ Ficarás grávida e darás à luz um filho. O cabelo dele nunca deverá ser cortado, porque o menino será um nazireu de Deus desde o nascimento,^&#42;1^ e ele começará a salvar Israel das mãos dos filisteus.”

[NOTE]
====
. Lit.: “desde o ventre”.
====

[[v7-13-6]]

^<<v7-13-6,6>>^ A seguir, a mulher foi contar ao seu marido: “Um homem do verdadeiro Deus veio ter comigo. A sua aparência inspirava muito temor, como a de um anjo do verdadeiro Deus. Não lhe perguntei de onde era, nem ele me disse o seu nome.

[[v7-13-7]]

^<<v7-13-7,7>>^ Mas ele disse-me: ‘Ficarás grávida e darás à luz um filho. Não bebas vinho nem outras bebidas alcoólicas, e não comas nada impuro, porque o menino será um nazireu de Deus desde o nascimento^&#42;1^ até ao dia da sua morte.’”

[NOTE]
====
. Lit.: “desde o ventre”.
====

[[v7-13-8]]

^<<v7-13-8,8>>^ Manoá suplicou a Jeová, dizendo: “Perdão, Jeová. Por favor, deixa que o homem do verdadeiro Deus, que acabas de enviar, venha outra vez para nos instruir sobre o que devemos fazer com o menino que vai nascer.”

[[v7-13-9]]

^<<v7-13-9,9>>^ Assim, o verdadeiro Deus escutou Manoá, e o anjo do verdadeiro Deus veio outra vez ter com a mulher enquanto estava sentada no campo; Manoá, o seu marido, não estava com ela.

[[v7-13-10]]

^<<v7-13-10,10>>^ A mulher foi a correr contar ao marido: “Olha, o homem que veio ter comigo no outro dia apareceu outra vez.”

[[v7-13-11]]

^<<v7-13-11,11>>^ Depois, Manoá levantou-se e foi com a esposa. Chegou até ao homem e perguntou-lhe: “És tu o homem que falou com a minha esposa?” Ele respondeu: “Sou.”

[[v7-13-12]]

^<<v7-13-12,12>>^ Manoá disse então: “Que as tuas palavras se cumpram! Como é que o menino deve ser criado e o que é que ele fará?”

[[v7-13-13]]

^<<v7-13-13,13>>^ O anjo de Jeová disse a Manoá: “A tua esposa deve evitar tudo o que eu lhe disse.

[[v7-13-14]]

^<<v7-13-14,14>>^ Não deve comer nada do que a videira produz, não deve beber vinho nem outras bebidas alcoólicas, e não deve comer nada impuro. Ela deve fazer tudo o que lhe ordenei.”

[[v7-13-15]]

^<<v7-13-15,15>>^ Manoá disse então ao anjo de Jeová: “Por favor, fica, e deixa-nos preparar-te um cabrito.”

[[v7-13-16]]

^<<v7-13-16,16>>^ O anjo de Jeová, porém, disse a Manoá: “Se ficar, não comerei da tua comida; mas, se quiseres apresentar uma oferta queimada a Jeová, podes oferecê-la.” Manoá não sabia que era o anjo de Jeová.

[[v7-13-17]]

^<<v7-13-17,17>>^ Manoá disse então ao anjo de Jeová: “Qual é o teu nome, para que te honremos quando a tua palavra se cumprir?”

[[v7-13-18]]

^<<v7-13-18,18>>^ No entanto, o anjo de Jeová disse-lhe: “Porque é que me perguntas o meu nome, visto que ele é maravilhoso?”

[[v7-13-19]]

^<<v7-13-19,19>>^ Manoá pegou então no cabrito e na oferta de cereais, e ofereceu-os a Jeová sobre a pedra. E Ele fez algo espantoso enquanto Manoá e a sua esposa olhavam.

[[v7-13-20]]

^<<v7-13-20,20>>^ À medida que as chamas subiam do altar para o céu, Manoá e a esposa viram o anjo de Jeová subir nas chamas do altar. Eles prostraram-se imediatamente com o rosto por terra.

[[v7-13-21]]

^<<v7-13-21,21>>^ O anjo de Jeová não voltou a aparecer a Manoá e à sua esposa. Então, Manoá percebeu que era o anjo de Jeová.

[[v7-13-22]]

^<<v7-13-22,22>>^ Por conseguinte, Manoá disse à sua esposa: “De certeza que vamos morrer, pois vimos a Deus.”

[[v7-13-23]]

^<<v7-13-23,23>>^ Contudo, a esposa disse-lhe: “Se Jeová nos quisesse entregar à morte, não teria aceitado a oferta queimada e a oferta de cereais das nossas mãos, não nos teria mostrado todas estas coisas e não nos teria dito nenhuma destas coisas.”

[[v7-13-24]]

^<<v7-13-24,24>>^ Mais tarde, a mulher deu à luz um filho e chamou-lhe Sansão; o menino crescia e Jeová continuava a abençoá-lo.

[[v7-13-25]]

^<<v7-13-25,25>>^ Com o tempo, o espírito de Jeová começou a atuar nele em Maané-Dã, entre Zorá e Estaol.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]