include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-9-1]]

^<<v7-9-1,1>>^ Depois de algum tempo, Abimeleque, filho de Jerubaal, foi ter com os irmãos da sua mãe, em Siquém, e disse-lhes a eles e a toda a família da casa do seu avô:^&#42;1^

[NOTE]
====
. Lit.: “a família da casa do pai da sua mãe”.
====

[[v7-9-2]]

^<<v7-9-2,2>>^ “Por favor, perguntem a todos os líderes^&#42;1^ de Siquém: ‘O que é que vos parece melhor, serem governados por todos os 70 filhos de Jerubaal ou por um só homem? E lembrem-se de que somos do mesmo sangue.’”^&#42;2^

[NOTE]
====
. Ou, possivelmente: “os proprietários de terras”.
. Lit.: “vosso osso e vossa carne”.
====

[[v7-9-3]]

^<<v7-9-3,3>>^ Portanto, os irmãos da sua mãe transmitiram as palavras dele a todos os líderes de Siquém, e o coração deles estava inclinado a seguir Abimeleque, pois disseram: “Ele é nosso irmão.”

[[v7-9-4]]

^<<v7-9-4,4>>^ Então, deram-lhe 70 peças de prata do templo^&#42;1^ de Baal-Berite, e Abimeleque usou-as para contratar homens vadios e insolentes para o acompanharem.

[NOTE]
====
. Ou: “da casa”.
====

[[v7-9-5]]

^<<v7-9-5,5>>^ Depois, foi à casa do seu pai em Ofra e sobre uma pedra matou os seus irmãos, os filhos de Jerubaal, 70 homens. O único que escapou foi Jotão, o filho mais novo de Jerubaal, porque se tinha escondido.

[[v7-9-6]]

^<<v7-9-6,6>>^ De seguida, todos os líderes de Siquém e toda a Bete-Milo reuniram-se e fizeram de Abimeleque rei, perto da árvore grande, perto da coluna que havia em Siquém.

[[v7-9-7]]

^<<v7-9-7,7>>^ Quando se comunicou isso a Jotão, ele foi imediatamente ao cume do monte Gerizim, ficou ali de pé e disse-lhes em voz bem alta: “Escutem-me, ó líderes de Siquém, e Deus vai escutar-vos:

[[v7-9-8]]

^<<v7-9-8,8>>^ “Certo dia, as árvores foram ungir um rei para si. Assim, disseram à oliveira: ‘Reina sobre nós.’

[[v7-9-9]]

^<<v7-9-9,9>>^ A oliveira, porém, disse-lhes: ‘Deveria eu abdicar do meu azeite,^&#42;1^ com o qual se glorifica a Deus e aos homens, para me abanar sobre as outras árvores?’

[NOTE]
====
. Ou: “da minha produtividade”.
====

[[v7-9-10]]

^<<v7-9-10,10>>^ Então as árvores disseram à figueira: ‘Vem e reina sobre nós.’

[[v7-9-11]]

^<<v7-9-11,11>>^ A figueira, porém, disse-lhes: ‘Deveria eu abdicar dos meus frutos bons e doces para me abanar sobre as outras árvores?’

[[v7-9-12]]

^<<v7-9-12,12>>^ A seguir, as árvores disseram à videira: ‘Vem e reina sobre nós.’

[[v7-9-13]]

^<<v7-9-13,13>>^ A videira disse-lhes: ‘Deveria eu abdicar do meu vinho novo, que alegra a Deus e aos homens, para me abanar sobre as árvores?’

[[v7-9-14]]

^<<v7-9-14,14>>^ Por fim, todas as outras árvores disseram ao espinheiro: ‘Vem e reina sobre nós.’

[[v7-9-15]]

^<<v7-9-15,15>>^ Então o espinheiro disse às árvores: ‘Se realmente me estiverem a ungir como vosso rei, venham e refugiem-se debaixo da minha sombra. Contudo, se não, que saia fogo do espinheiro e consuma os cedros do Líbano.’

[[v7-9-16]]

^<<v7-9-16,16>>^ “Agora, será que agiram de modo sincero e honesto ao fazerem Abimeleque rei? Será que demonstraram bondade para com Jerubaal e os da sua casa, e que o trataram conforme ele merecia?

[[v7-9-17]]

^<<v7-9-17,17>>^ Quando o meu pai lutou por vocês, ele arriscou a vida^&#42;1^ para vos livrar das mãos de Midiã.

[NOTE]
====
. Ou: “alma”.
====

[[v7-9-18]]

^<<v7-9-18,18>>^ No entanto, hoje levantaram-se contra os da casa do meu pai e mataram-lhe os filhos, 70 homens, sobre uma pedra. Depois, fizeram Abimeleque, filho da escrava do meu pai, rei sobre os líderes de Siquém, só porque ele é vosso irmão.

[[v7-9-19]]

^<<v7-9-19,19>>^ Sim, se no dia de hoje, estão a agir de modo sincero e honesto para com Jerubaal e os da sua casa, alegrem-se com Abimeleque e que ele também se alegre convosco.

[[v7-9-20]]

^<<v7-9-20,20>>^ Contudo, se não, que saia fogo de Abimeleque e consuma os líderes de Siquém e Bete-Milo, e que saia fogo dos líderes de Siquém e Bete-Milo e consuma Abimeleque.”

[[v7-9-21]]

^<<v7-9-21,21>>^ Então Jotão fugiu para Beer e ficou ali a morar por causa do seu irmão Abimeleque.

[[v7-9-22]]

^<<v7-9-22,22>>^ Abimeleque reinou^&#42;1^ sobre Israel durante três anos.

[NOTE]
====
. Ou: “agiu como príncipe”.
====

[[v7-9-23]]

^<<v7-9-23,23>>^ Então, Deus permitiu que surgisse hostilidade^&#42;1^ entre Abimeleque e os líderes de Siquém, e eles agiram traiçoeiramente com Abimeleque.

[NOTE]
====
. Lit.: “enviou um espírito mau”.
====

[[v7-9-24]]

^<<v7-9-24,24>>^ Isso aconteceu para que a violência praticada contra os 70 filhos de Jerubaal fosse vingada, de modo que a responsabilidade pelo sangue deles recaísse sobre o seu irmão Abimeleque, por os ter matado, e sobre os líderes de Siquém, por o terem ajudado a matar os seus irmãos.

[[v7-9-25]]

^<<v7-9-25,25>>^ Portanto, os líderes de Siquém colocaram homens de emboscada contra ele nos cumes dos montes. E roubavam todos os que passavam por eles na estrada. Com o tempo, relatou-se isso a Abimeleque.

[[v7-9-26]]

^<<v7-9-26,26>>^ Então, Gaal, filho de Ebede, e os seus irmãos foram para Siquém, e os líderes de Siquém confiaram nele.

[[v7-9-27]]

^<<v7-9-27,27>>^ Eles foram para o campo, colheram e pisaram as uvas das suas vinhas, e fizeram uma festa. Depois entraram na casa do seu deus, comeram e beberam, e amaldiçoaram Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ Gaal, filho de Ebede, disse: “Quem é Abimeleque e quem é Siquém para que o devamos servir? Não é ele filho de Jerubaal, e não é Zebul o seu representante? Sirvam os homens de Hamor, pai de Siquém! Porque é que devíamos servir Abimeleque?

[[v7-9-29]]

^<<v7-9-29,29>>^ Quem me dera que eu tivesse este povo sob o meu comando; eu removeria Abimeleque.” Depois, ele disse a Abimeleque: “Reforça o teu exército e vem lutar.”

[[v7-9-30]]

^<<v7-9-30,30>>^ Quando Zebul, príncipe da cidade, ouviu as palavras de Gaal, filho de Ebede, a sua ira acendeu-se.

[[v7-9-31]]

^<<v7-9-31,31>>^ Por isso, enviou secretamente^&#42;1^ mensageiros a Abimeleque para dizer: “Gaal, filho de Ebede, e os seus irmãos estão agora em Siquém, e estão a instigar a cidade contra ti.

[NOTE]
====
. Ou: “astutamente”.
====

[[v7-9-32]]

^<<v7-9-32,32>>^ Agora, vem de noite, tu e os teus homens, e fica de emboscada no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ Assim que o sol nascer, levanta-te cedo e ataca a cidade. Quando Gaal e os seus homens vierem contra ti, faz tudo ao teu alcance para o derrotar.”^&#42;1^

[NOTE]
====
. Ou: “faz-lhe o que a tua mão achar possível”.
====

[[v7-9-34]]

^<<v7-9-34,34>>^ Portanto, Abimeleque e todos os homens que estavam com ele levantaram-se de noite e ficaram de emboscada contra Siquém, em quatro grupos.

[[v7-9-35]]

^<<v7-9-35,35>>^ Quando Gaal, filho de Ebede, saiu e ficou junto ao portão da cidade, Abimeleque e os homens que estavam com ele saíram da emboscada.

[[v7-9-36]]

^<<v7-9-36,36>>^ Quando Gaal viu o povo, disse a Zebul: “Olha! Há pessoas a descer do cume dos montes.” Zebul, porém, disse-lhe: “Estás a confundir a sombra dos montes com homens.”

[[v7-9-37]]

^<<v7-9-37,37>>^ Depois Gaal disse: “Olha! Há pessoas a descer do centro do território e um grupo está a vir pelo caminho da árvore grande de Meonenim.”

[[v7-9-38]]

^<<v7-9-38,38>>^ Zebul disse-lhe: “Onde está agora a tua arrogância, quando disseste: ‘Quem é Abimeleque, para que o devamos servir?’ Não é este o povo que desprezaste? Vai agora e luta contra eles.”

[[v7-9-39]]

^<<v7-9-39,39>>^ Portanto, Gaal saiu à frente dos líderes de Siquém e lutou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Abimeleque perseguiu Gaal, que fugiu dele; e muitos foram mortos ao longo do caminho, até ao portão da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ E Abimeleque continuou a morar em Arumá, e Zebul expulsou de Siquém Gaal e os seus irmãos.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte, o povo foi para o campo, e Abimeleque foi informado disso.

[[v7-9-43]]

^<<v7-9-43,43>>^ Assim, dividiu os seus homens em três grupos e ficou de emboscada no campo. Quando viu o povo a sair da cidade, atacou-os e matou-os.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e os grupos que estavam com ele avançaram e posicionaram-se junto à entrada do portão da cidade, enquanto dois grupos atacaram todos os que estavam no campo e os mataram.

[[v7-9-45]]

^<<v7-9-45,45>>^ Abimeleque lutou contra a cidade durante todo aquele dia e tomou-a. Ele matou o povo que nela havia; depois demoliu a cidade e espalhou sal sobre ela.

[[v7-9-46]]

^<<v7-9-46,46>>^ Quando os líderes da torre de Siquém souberam disso, foram imediatamente para o esconderijo^&#42;1^ do templo^&#42;2^ de El-Berite.

[NOTE]
====
. Ou: “a fortaleza”.
. Ou: “da casa”.
====

[[v7-9-47]]

^<<v7-9-47,47>>^ Assim que se comunicou a Abimeleque que todos os líderes da torre de Siquém se tinham reunido ali,

[[v7-9-48]]

^<<v7-9-48,48>>^ Abimeleque e todos os homens que estavam com ele subiram ao monte Zalmom. Abimeleque pegou num machado, cortou um ramo de uma árvore, colocou-o ao ombro e disse aos seus homens: “Depressa! Façam o mesmo que eu fiz!”

[[v7-9-49]]

^<<v7-9-49,49>>^ E todos os homens também cortaram ramos e seguiram Abimeleque. Então, colocaram os ramos à volta do esconderijo e puseram-lhe fogo. Assim, todos os habitantes da torre de Siquém também morreram, cerca de mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Depois, Abimeleque foi a Tebes; acampou para atacar Tebes e tomou-a.

[[v7-9-51]]

^<<v7-9-51,51>>^ Havia uma torre forte no meio da cidade, e todos os homens e mulheres, e todos os líderes da cidade, fugiram para lá. Trancaram-se dentro da torre e subiram até ao terraço.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimeleque foi até à torre e atacou-a. Ele aproximou-se da entrada da torre para a incendiar.

[[v7-9-53]]

^<<v7-9-53,53>>^ Então, uma das mulheres deixou cair uma pedra de moinho na cabeça de Abimeleque e esmagou-lhe o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Ele chamou logo o ajudante que carregava as suas armas e disse-lhe: “Puxa da tua espada e mata-me, para que não digam a meu respeito: ‘Foi uma mulher que o matou.’” Assim, o seu ajudante trespassou-o e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Quando os homens de Israel viram que Abimeleque estava morto, todos regressaram a casa.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim, Deus retribuiu a Abimeleque todo o mal que ele fizera ao seu pai ao matar os seus 70 irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ Deus também fez com que todo o mal cometido pelos homens de Siquém recaísse sobre as suas cabeças. Assim, sobreveio-lhes a maldição de Jotão, filho de Jerubaal.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]