include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-11-1]]

^<<v7-11-1,1>>^ Jefté, o gileadita, era um guerreiro valente. Ele era filho de uma prostituta, e Gileade era o pai de Jefté.

[[v7-11-2]]

^<<v7-11-2,2>>^ Contudo, a esposa de Gileade também lhe deu filhos. Quando os filhos da sua esposa cresceram, expulsaram Jefté e disseram-lhe: “Não terás herança na casa do nosso pai, porque és filho de outra mulher.”

[[v7-11-3]]

^<<v7-11-3,3>>^ Assim, Jefté fugiu dos seus irmãos e estabeleceu-se na terra de Tobe. E homens vadios juntaram-se a Jefté e seguiram-no.

[[v7-11-4]]

^<<v7-11-4,4>>^ Algum tempo depois, os amonitas lutaram contra Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ E, quando os amonitas começaram a lutar contra Israel, os anciãos de Gileade foram imediatamente buscar Jefté à terra de Tobe.

[[v7-11-6]]

^<<v7-11-6,6>>^ Eles disseram a Jefté: “Vem e serve como nosso comandante, para que lutemos contra os amonitas.”

[[v7-11-7]]

^<<v7-11-7,7>>^ Porém, Jefté disse aos anciãos de Gileade: “Não foram vocês que me odiaram tanto a ponto de me expulsar da casa do meu pai? Porque é que vêm ter comigo agora que estão em aflição?”

[[v7-11-8]]

^<<v7-11-8,8>>^ Então, os anciãos de Gileade disseram a Jefté: “É por isso que agora viemos ter contigo. Se vieres connosco e lutares contra os amonitas, vais tornar-te o nosso líder sobre todos os habitantes de Gileade.”

[[v7-11-9]]

^<<v7-11-9,9>>^ Portanto, Jefté disse aos anciãos de Gileade: “Se me levarem de volta para lutar contra os amonitas e Jeová mos entregar, então certamente me tornarei o vosso líder!”

[[v7-11-10]]

^<<v7-11-10,10>>^ Os anciãos de Gileade disseram a Jefté: “Que Jeová seja testemunha^&#42;1^ entre nós se não fizermos como dizes.”

[NOTE]
====
. Lit.: “aquele que escuta”.
====

[[v7-11-11]]

^<<v7-11-11,11>>^ Assim, Jefté foi com os anciãos de Gileade, e o povo fê-lo seu líder e comandante. E Jefté repetiu em Mispá tudo o que tinha dito perante Jeová.

[[v7-11-12]]

^<<v7-11-12,12>>^ A seguir, Jefté enviou mensageiros ao rei dos amonitas para dizer: “O que é que tu tens contra mim^&#42;1^ para vires atacar a minha terra?”

[NOTE]
====
. Lit.: “O que para mim e para ti”.
====

[[v7-11-13]]

^<<v7-11-13,13>>^ O rei dos amonitas disse aos mensageiros de Jefté: “É porque Israel se apoderou da minha terra quando saiu do Egito, desde o Arnom até ao Jaboque e até ao Jordão. Agora, devolve-a pacificamente.”

[[v7-11-14]]

^<<v7-11-14,14>>^ Contudo, Jefté voltou a enviar mensageiros ao rei dos amonitas

[[v7-11-15]]

^<<v7-11-15,15>>^ para lhe dizer:
“Assim diz Jefté: ‘Israel não tomou a terra dos moabitas, nem a terra dos amonitas,

[[v7-11-16]]

^<<v7-11-16,16>>^ pois, quando saiu do Egito, Israel andou pelo deserto até ao mar Vermelho e chegou a Cades.

[[v7-11-17]]

^<<v7-11-17,17>>^ Depois, Israel enviou mensageiros ao rei de Edom para dizer: “Por favor, deixe-nos passar pela sua terra”, mas o rei de Edom não escutou. Fizeram o mesmo pedido ao rei de Moabe, mas ele não concordou. Por isso, Israel ficou a morar em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ Ao continuarem a andar pelo deserto, contornaram a terra de Edom e a terra de Moabe. Passaram a leste da terra de Moabe e acamparam na região do Arnom; eles não entraram no território de Moabe, pois o Arnom era o limite do território de Moabe.

[[v7-11-19]]

^<<v7-11-19,19>>^ “‘Depois Israel enviou mensageiros a Síon, rei dos amorreus, rei de Hésbon. Israel disse-lhe: “Por favor, deixe-nos passar pela sua terra para irmos para o lugar que nos pertence.”

[[v7-11-20]]

^<<v7-11-20,20>>^ No entanto, Síon não confiou em Israel para o deixar passar pelo seu território. Assim, Síon ajuntou todo o seu povo, acampou em Jaaz e lutou contra Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ Em vista disso, Jeová, o Deus de Israel, entregou Síon e todo o seu povo nas mãos de Israel, de modo que estes os derrotaram, e Israel tomou posse de toda a terra dos amorreus, os habitantes daquela terra.

[[v7-11-22]]

^<<v7-11-22,22>>^ Assim, tomaram posse de todo o território dos amorreus, desde o Arnom até ao Jaboque, e desde o deserto até ao Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ “‘Foi Jeová, o Deus de Israel, quem expulsou os amorreus de diante do seu povo, Israel, e agora tu queres expulsar Israel?

[[v7-11-24]]

^<<v7-11-24,24>>^ Não tomas tu posse de tudo o que o teu deus, Quemós, te dá? Por isso, nós expulsaremos todos os que Jeová, nosso Deus, expulsar da nossa frente.

[[v7-11-25]]

^<<v7-11-25,25>>^ Será que és melhor do que Balaque, filho de Zipor, rei de Moabe? Alguma vez ele entrou em conflito com Israel ou lutou contra eles?

[[v7-11-26]]

^<<v7-11-26,26>>^ Enquanto Israel morava em Hésbon e nas suas aldeias dependentes,^&#42;1^ em Aroer e nas suas aldeias dependentes, e em todas as cidades que ficam nas margens do Arnom, durante 300 anos, porque é que nunca as tentaram recuperar durante esse tempo?

[NOTE]
====
. Ou: “ao redor”.
====

[[v7-11-27]]

^<<v7-11-27,27>>^ Não pequei contra ti, mas tu fazes mal em atacar-me. Que Jeová, o Juiz, julgue, hoje, entre o povo de Israel e o povo de Amom.’”

[[v7-11-28]]

^<<v7-11-28,28>>^ O rei dos amonitas, porém, não quis ouvir a mensagem que Jefté lhe enviou.

[[v7-11-29]]

^<<v7-11-29,29>>^ O espírito de Jeová veio sobre Jefté, e ele atravessou Gileade e Manassés para ir a Mispa de Gileade, e de Mispa de Gileade continuou até aos amonitas.

[[v7-11-30]]

^<<v7-11-30,30>>^ De seguida, Jefté fez um voto a Jeová, dizendo: “Se entregares os amonitas nas minhas mãos,

[[v7-11-31]]

^<<v7-11-31,31>>^ então, aquele que sair da porta da minha casa ao meu encontro, quando eu voltar em paz da guerra contra os amonitas, vai tornar-se de Jeová, e eu vou oferecê-lo como oferta queimada.”

[[v7-11-32]]

^<<v7-11-32,32>>^ Assim, Jefté foi lutar contra os amonitas, e Jeová entregou-os nas suas mãos.

[[v7-11-33]]

^<<v7-11-33,33>>^ Ele atingiu-os com uma matança muito grande, desde Aroer até Minite — 20 cidades — e até Abel-Queramim. Desta maneira, os amonitas foram subjugados diante dos israelitas.

[[v7-11-34]]

^<<v7-11-34,34>>^ Finalmente, Jefté chegou a casa em Mispá, e eis que vinha ao seu encontro a sua filha, a tocar pandeireta e a dançar! Ela era a sua única filha; além dela, ele não tinha nem filhos nem filhas.

[[v7-11-35]]

^<<v7-11-35,35>>^ Quando ele a viu, rasgou as suas roupas e disse: “Ai, minha filha! Partiste-me o coração,^&#42;1^ pois tornaste-te aquela que eu bani. Fiz um voto^&#42;2^ a Jeová e não posso voltar atrás.”

[NOTE]
====
. Lit.: “Deixaste-me prostrado”.
. Lit.: “Abri a minha boca”.
====

[[v7-11-36]]

^<<v7-11-36,36>>^ Todavia, ela disse-lhe: “Meu pai, se fez um voto a Jeová, faça comigo conforme prometeu, visto que Jeová executou para si vingança sobre os seus inimigos, os amonitas.”

[[v7-11-37]]

^<<v7-11-37,37>>^ E ela disse ao pai: “Só lhe peço uma coisa: deixe-me ir para os montes durante dois meses chorar a minha virgindade, apenas eu e as minhas amigas.”^&#42;1^

[NOTE]
====
. Ou: “chorar com as minhas amigas porque nunca me casarei”.
====

[[v7-11-38]]

^<<v7-11-38,38>>^ E ele disse: “Vai!” Assim, deixou-a ir por dois meses; e ela foi para os montes com as suas amigas para chorar a sua virgindade.

[[v7-11-39]]

^<<v7-11-39,39>>^ Ao fim dos dois meses, ela voltou para o pai, e ele cumpriu o voto que tinha feito a respeito dela. Ela nunca teve relações com nenhum homem. E tornou-se costume^&#42;1^ em Israel:

[NOTE]
====
. Ou: “regulamento”.
====

[[v7-11-40]]

^<<v7-11-40,40>>^ de ano em ano, durante quatro dias por ano, as jovens de Israel iam visitar a filha de Jefté, o gileadita, para a elogiar.

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]