include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-6-1]]

^<<v7-6-1,1>>^ Os israelitas, porém, voltaram a fazer o que era mau aos olhos de Jeová. Portanto, Jeová entregou-os nas mãos de Midiã, durante sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ Midiã dominava sobre Israel. Por causa de Midiã, os israelitas fizeram esconderijos^&#42;1^ nos montes, nas cavernas e nos lugares de difícil acesso.

[NOTE]
====
. Ou, possivelmente: “depósitos subterrâneos”.
====

[[v7-6-3]]

^<<v7-6-3,3>>^ Quando Israel semeava, Midiã, Amaleque e os orientais atacavam-nos.

[[v7-6-4]]

^<<v7-6-4,4>>^ Acampavam para os atacar e destruíam os produtos da terra até Gaza; não deixavam nada para Israel comer, e não deixavam ovelhas, nem touros, nem jumentos.

[[v7-6-5]]

^<<v7-6-5,5>>^ Pois vinham com os seus animais e as suas tendas, tão numerosos como gafanhotos, e eles e os seus camelos não podiam ser contados; entravam na terra para a destruir.

[[v7-6-6]]

^<<v7-6-6,6>>^ Por isso, Israel empobreceu muito por causa de Midiã; e os israelitas clamaram a Jeová por ajuda.

[[v7-6-7]]

^<<v7-6-7,7>>^ Quando os israelitas clamaram a Jeová por ajuda, por causa de Midiã,

[[v7-6-8]]

^<<v7-6-8,8>>^ Jeová enviou aos israelitas um profeta, que lhes disse: “Assim diz Jeová, o Deus de Israel: ‘Eu tirei-vos do Egito e assim tirei-vos da terra da escravidão.^&#42;1^

[NOTE]
====
. Lit.: “casa dos escravos”.
====

[[v7-6-9]]

^<<v7-6-9,9>>^ Livrei-vos das mãos do Egito e de todos os vossos opressores, e expulsei-os da vossa frente e dei-vos a terra deles.

[[v7-6-10]]

^<<v7-6-10,10>>^ E disse-vos: “Eu sou Jeová, vosso Deus. Não devem temer os deuses dos amorreus em cuja terra moram.” Mas não me obedeceram.’”^&#42;1^

[NOTE]
====
. Lit.: “não escutaram a minha voz”.
====

[[v7-6-11]]

^<<v7-6-11,11>>^ Mais tarde, o anjo de Jeová veio e sentou-se debaixo da árvore grande que havia em Ofra, que pertencia a Joás, o abiezrita. O seu filho Gideão estava a malhar trigo no lagar de vinho, para o esconder de Midiã.

[[v7-6-12]]

^<<v7-6-12,12>>^ O anjo de Jeová apareceu-lhe e disse: “Jeová está contigo, guerreiro valente.”

[[v7-6-13]]

^<<v7-6-13,13>>^ Gideão respondeu-lhe: “Perdão, meu senhor, mas, se Jeová está connosco, porque é que nos aconteceu tudo isto? Onde estão todos os seus atos maravilhosos que os nossos pais nos contaram, dizendo: ‘Não foi Jeová quem nos tirou do Egito’? Agora Jeová abandonou-nos e entregou-nos nas mãos de Midiã.”

[[v7-6-14]]

^<<v7-6-14,14>>^ Jeová olhou para ele e disse: “Vai com a força que tens, e salvarás Israel das mãos de Midiã. Não sou eu que te estou a enviar?”

[[v7-6-15]]

^<<v7-6-15,15>>^ Gideão respondeu-lhe: “Perdão, Jeová. Como posso salvar Israel? O meu clã^&#42;1^ é o menos importante de Manassés, e eu sou o mais insignificante na casa do meu pai.”

[NOTE]
====
. Lit.: “milhar”.
====

[[v7-6-16]]

^<<v7-6-16,16>>^ Mas Jeová disse-lhe: “Visto que estarei contigo, tu golpearás os midianitas como se fossem apenas um homem.”

[[v7-6-17]]

^<<v7-6-17,17>>^ Então, Gideão disse-lhe: “Se achei favor aos teus olhos, dá-me um sinal de que és tu que falas comigo.

[[v7-6-18]]

^<<v7-6-18,18>>^ Por favor, não te afastes daqui até que eu volte com a minha dádiva e a coloque diante de ti.” Ele respondeu: “Ficarei aqui até voltares.”

[[v7-6-19]]

^<<v7-6-19,19>>^ E Gideão entrou em casa, preparou um cabrito e fez pães sem fermento com uma efa^&#42;1^ de farinha. Ele pôs a carne no cesto e o caldo na panela; então levou-os para fora e serviu-os debaixo da árvore grande.

[NOTE]
====
. Cerca de 22 l. Veja o Ap. B14.
====

[[v7-6-20]]

^<<v7-6-20,20>>^ O anjo do verdadeiro Deus disse-lhe então: “Pega na carne e nos pães sem fermento, coloca-os lá sobre a grande pedra e derrama o caldo.” E Gideão assim fez.

[[v7-6-21]]

^<<v7-6-21,21>>^ Então, o anjo de Jeová estendeu o bastão que tinha na mão e com a ponta tocou na carne e nos pães sem fermento; e saiu fogo da pedra, consumindo a carne e os pães sem fermento. Em seguida, o anjo de Jeová desapareceu da sua vista.

[[v7-6-22]]

^<<v7-6-22,22>>^ Gideão percebeu então que era o anjo de Jeová.
Gideão disse imediatamente: “Ai de mim, Soberano Senhor Jeová, pois vi o anjo de Jeová face a face!”

[[v7-6-23]]

^<<v7-6-23,23>>^ Mas Jeová disse-lhe: “Que a paz esteja contigo. Não tenhas medo; tu não morrerás.”

[[v7-6-24]]

^<<v7-6-24,24>>^ Portanto, Gideão construiu ali um altar para Jeová, que até ao dia de hoje se chama Jeová-Salom^&#42;1^ e que ainda está em Ofra dos abiezritas.

[NOTE]
====
. Que significa “Jeová é paz”.
====

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela noite, Jeová disse-lhe: “Pega no novilho que pertence ao teu pai, o segundo novilho de sete anos. Derruba o altar de Baal que pertence ao teu pai e corta o poste sagrado^&#42;1^ que está ao pé dele.

[NOTE]
====
. Veja o Glossário.
====

[[v7-6-26]]

^<<v7-6-26,26>>^ Depois de construíres um altar para Jeová, teu Deus, no topo desta fortaleza, com pedras enfileiradas, pega no segundo novilho e oferece-o como oferta queimada sobre os pedaços de madeira do poste sagrado^&#42;1^ que cortaste.”

[NOTE]
====
. Veja o Glossário.
====

[[v7-6-27]]

^<<v7-6-27,27>>^ Então, Gideão chamou dez homens dentre os seus servos e fez como Jeová lhe tinha dito. Mas, visto que tinha medo dos da casa do seu pai e dos homens da cidade, ele fez isso de noite, não durante o dia.

[[v7-6-28]]

^<<v7-6-28,28>>^ Na manhã seguinte, quando os homens da cidade se levantaram cedo, viram que o altar de Baal tinha sido demolido, que o poste sagrado^&#42;1^ ao lado dele tinha sido cortado e que o segundo novilho tinha sido oferecido no altar que tinha sido construído.

[NOTE]
====
. Veja o Glossário.
====

[[v7-6-29]]

^<<v7-6-29,29>>^ Perguntaram uns aos outros: “Quem é que fez isto?” Depois de investigarem, disseram: “Foi Gideão, filho de Joás, quem fez isto.”

[[v7-6-30]]

^<<v7-6-30,30>>^ Portanto, os homens da cidade disseram a Joás: “Traz o teu filho para fora, para que seja morto, porque demoliu o altar de Baal e cortou o poste sagrado^&#42;1^ que estava ao lado dele.”

[NOTE]
====
. Veja o Glossário.
====

[[v7-6-31]]

^<<v7-6-31,31>>^ Então, Joás disse a todos os que o confrontavam: “Precisam vocês de defender Baal? Precisam de o salvar? Quem o defender deverá ser morto esta manhã. Se ele é um deus, que se defenda a si mesmo, visto que alguém demoliu o seu altar.”

[[v7-6-32]]

^<<v7-6-32,32>>^ E naquele dia ele deu o nome de Jerubaal^&#42;1^ a Gideão, dizendo: “Que Baal se defenda a si mesmo, pois alguém demoliu o seu altar.”

[NOTE]
====
. Que significa “que Baal defenda a sua própria causa”.
====

[[v7-6-33]]

^<<v7-6-33,33>>^ Todos os midianitas, os amalequitas e os orientais juntaram forças; eles atravessaram o rio e acamparam no vale^&#42;1^ de Jezreel.

[NOTE]
====
. Ou: “na planície”.
====

[[v7-6-34]]

^<<v7-6-34,34>>^ Então, o espírito de Jeová veio sobre^&#42;1^ Gideão e ele tocou a buzina, e os abiezritas seguiram-no.

[NOTE]
====
. Lit.: “revestiu”.
====

[[v7-6-35]]

^<<v7-6-35,35>>^ Ele enviou mensageiros a todo o território da tribo de Manassés, que também se reuniu para o seguir. Ainda enviou mensageiros ao território de Aser, Zebulão e Naftali, e estes foram ao seu encontro.

[[v7-6-36]]

^<<v7-6-36,36>>^ Depois, Gideão disse ao verdadeiro Deus: “Se fores salvar Israel por meio de mim, assim como prometeste,

[[v7-6-37]]

^<<v7-6-37,37>>^ vou colocar uma porção de lã na eira. Se houver orvalho apenas na lã, mas todo o chão à volta ficar seco, então saberei que salvarás Israel por meio de mim, como prometeste.”

[[v7-6-38]]

^<<v7-6-38,38>>^ E foi isso o que aconteceu. No dia seguinte, quando ele se levantou cedo e torceu a lã, saiu da lã orvalho suficiente para encher de água uma grande taça de banquete.

[[v7-6-39]]

^<<v7-6-39,39>>^ No entanto, Gideão disse ao verdadeiro Deus: “Não se acenda a tua ira contra mim, mas deixa-me fazer só mais um pedido. Por favor, deixa-me fazer apenas mais uma prova com a lã. Por favor, que apenas a lã fique seca e haja orvalho em todo o chão.”

[[v7-6-40]]

^<<v7-6-40,40>>^ Portanto, foi isso o que Deus fez naquela noite; só a lã ficou seca, mas todo o chão estava coberto de orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]