include::./index.adoc[]

[[v7-14-0]]
=== Juízes, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-14-1]]

^<<v7-14-1,1>>^ Sansão desceu então até Timná, e foi em Timná que viu uma mulher filisteia.^&#42;1^

[NOTE]
====
. Lit.: “uma mulher das filhas dos filisteus”.
====

[[v7-14-2]]

^<<v7-14-2,2>>^ Por isso, ele voltou e disse ao seu pai e à sua mãe: “Em Timná, uma mulher filisteia chamou a minha atenção; quero que a consigam como minha esposa.”

[[v7-14-3]]

^<<v7-14-3,3>>^ Contudo, o pai e a mãe disseram-lhe: “Será que não podes encontrar uma mulher entre os teus parentes e entre todo o nosso povo? Tens de ir arranjar uma esposa dentre os filisteus incircuncisos?” Sansão, porém, disse ao pai: “Consegue-ma, porque ela é a pessoa certa para mim.”^&#42;1^

[NOTE]
====
. Lit.: “ela é certa aos meus olhos”.
====

[[v7-14-4]]

^<<v7-14-4,4>>^ O pai e a mãe não perceberam que isto era da parte de Jeová, pois Ele estava à procura de uma oportunidade contra os filisteus, visto que naquela altura os filisteus dominavam sobre Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Assim, Sansão desceu até Timná com o seu pai e a sua mãe. Quando chegou às vinhas de Timná, veio um leão^&#42;1^ a rugir ao seu encontro.

[NOTE]
====
. Ou: “leão novo jubado”.
====

[[v7-14-6]]

^<<v7-14-6,6>>^ Então, o espírito de Jeová deu-lhe poder, e, sem nada nas mãos, ele rasgou o leão em dois como se fosse um cabrito. Todavia, não contou nem ao pai nem à mãe o que tinha feito.

[[v7-14-7]]

^<<v7-14-7,7>>^ A seguir, Sansão desceu até Timná e conversou com a mulher, e ela ainda era a pessoa certa aos seus olhos.

[[v7-14-8]]

^<<v7-14-8,8>>^ Mais tarde, quando estava a voltar para a levar para casa, desviou-se para ver o leão morto, e na carcaça do leão havia um enxame de abelhas e mel.

[[v7-14-9]]

^<<v7-14-9,9>>^ Tirou o mel com as mãos e comeu-o enquanto caminhava. Quando alcançou o seu pai e a sua mãe, deu-lhes um pouco para comerem. No entanto, não lhes contou que tinha tirado o mel da carcaça do leão.

[[v7-14-10]]

^<<v7-14-10,10>>^ O seu pai desceu até onde a mulher estava, e Sansão deu ali um banquete, pois era isso que os rapazes costumavam fazer.

[[v7-14-11]]

^<<v7-14-11,11>>^ Quando o viram, trouxeram 30 padrinhos para o acompanhar.

[[v7-14-12]]

^<<v7-14-12,12>>^ Então Sansão disse-lhes: “Por favor, deixem-me contar-vos um enigma. Se durante os sete dias do banquete o decifrarem e me derem a resposta, vou dar-vos 30 vestes de linho e 30 mudas de roupa.

[[v7-14-13]]

^<<v7-14-13,13>>^ Contudo, se não me conseguirem dar a resposta, têm de me dar 30 vestes de linho e 30 mudas de roupa.” Eles disseram: “Conta-nos o teu enigma; queremos ouvi-lo.”

[[v7-14-14]]

^<<v7-14-14,14>>^ E ele disse-lhes:
“Daquele que come saiu algo para comer,
E do forte saiu algo doce.”
Durante três dias, não conseguiram decifrar o enigma.

[[v7-14-15]]

^<<v7-14-15,15>>^ No quarto dia, disseram à esposa de Sansão: “Engana o teu marido para que ele nos dê a resposta do enigma. Senão vamos queimar-te a ti e aos da casa do teu pai com fogo. Foi para ficarem com os nossos bens que nos convidaram para vir até aqui?”

[[v7-14-16]]

^<<v7-14-16,16>>^ Por conseguinte, a esposa de Sansão chorou diante dele e disse: “Tu deves odiar-me! Tu não me amas! Contaste um enigma ao meu povo, mas não me disseste a resposta.” Ele respondeu: “Eu não disse a resposta nem ao meu próprio pai nem à minha própria mãe! Porque é que ta deveria dizer a ti?”

[[v7-14-17]]

^<<v7-14-17,17>>^ Contudo, ela continuou a chorar diante dele durante o resto do tempo do banquete de sete dias. Finalmente, ele contou-lhe no sétimo dia, porque ela o tinha pressionado. Depois, ela disse a resposta do enigma ao seu povo.

[[v7-14-18]]

^<<v7-14-18,18>>^ Assim, no sétimo dia, antes do pôr do sol,^&#42;1^ os homens da cidade disseram-lhe:
“O que é mais doce do que o mel,
E o que é mais forte do que o leão?”
Ele respondeu-lhes:
“Se não tivessem lavrado com a minha novilha,
Não teriam decifrado o meu enigma.”

[NOTE]
====
. Ou, possivelmente: “antes de ele entrar no aposento interior”.
====

[[v7-14-19]]

^<<v7-14-19,19>>^ Então, o espírito de Jeová deu-lhe poder, e ele desceu até Ascalom, matou 30 homens dali, pegou na roupa deles e entregou as mudas de roupa aos que tinham respondido ao enigma. Estava furioso quando voltou para a casa do seu pai.

[[v7-14-20]]

^<<v7-14-20,20>>^ Depois a esposa de Sansão foi dada a um dos padrinhos dele, que o tinha acompanhado.

'''

xref:007-juizes/007-juizes-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-juizes/007-juizes-015.adoc#v7-15-0[Próximo Capítulo &#62;]