include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-4-1]]

^<<v7-4-1,1>>^ Após a morte de Eúde, porém, os israelitas voltaram a fazer o que era mau aos olhos de Jeová.

[[v7-4-2]]

^<<v7-4-2,2>>^ Portanto, Jeová entregou-os^&#42;1^ nas mãos de Jabim, rei de Canaã, que reinava em Hazor. O chefe do seu exército era Sísera, que morava em Harosete das nações.^&#42;2^

[NOTE]
====
. Lit.: “vendeu-os”.
. Ou: “Harosete-Hagoim”.
====

[[v7-4-3]]

^<<v7-4-3,3>>^ Os israelitas clamaram a Jeová, visto que Jabim^&#42;1^ tinha 900 carros de guerra com foices de ferro^&#42;2^ e já há 20 anos que oprimia cruelmente os israelitas.

[NOTE]
====
. Lit.: “ele”.
. Lit.: “carros de ferro”.
====

[[v7-4-4]]

^<<v7-4-4,4>>^ Débora, uma profetisa, esposa de Lapidote, julgava Israel naquela altura.

[[v7-4-5]]

^<<v7-4-5,5>>^ Ela costumava sentar-se debaixo da palmeira de Débora, entre Ramá e Betel, na região montanhosa de Efraim. Os israelitas iam ter com ela para se informarem acerca dos julgamentos de Deus.

[[v7-4-6]]

^<<v7-4-6,6>>^ Ela mandou chamar Baraque, filho de Abinoão, de Quedes-Naftali, e disse-lhe: “Não te dá Jeová, o Deus de Israel, esta ordem? ‘Vai ao^&#42;1^ monte Tabor e leva contigo 10 000 homens de Naftali e de Zebulão.

[NOTE]
====
. Ou: “Posiciona os teus homens no”.
====

[[v7-4-7]]

^<<v7-4-7,7>>^ Irei trazer-te, ao rio^&#42;1^ Quisom, Sísera, chefe do exército de Jabim, com os seus carros de guerra e as suas tropas, e vou entregá-lo nas tuas mãos.’”

[NOTE]
====
. Ou: “uádi”.
====

[[v7-4-8]]

^<<v7-4-8,8>>^ Por conseguinte, Baraque disse-lhe: “Se fores comigo, eu irei; mas, se não fores comigo, eu não irei.”

[[v7-4-9]]

^<<v7-4-9,9>>^ Ela respondeu: “Certamente irei contigo. No entanto, esta campanha militar não te trará glória, pois será nas mãos de uma mulher que Jeová entregará Sísera.” Então, Débora levantou-se e foi com Baraque a Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Baraque convocou Zebulão e Naftali a Quedes, e 10 000 homens seguiram-no. Débora também foi com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ A propósito, Héber, o queneu, tinha-se separado dos queneus, os descendentes de Hobabe, sogro de Moisés, e a sua tenda estava armada perto da árvore grande em Zaananim, que fica em Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ Comunicou-se a Sísera que Baraque, filho de Abinoão, tinha subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ Sísera reuniu imediatamente todos os seus carros de guerra — 900 carros com foices de ferro^&#42;1^ — e todas as suas tropas, para ir de Harosete das nações até ao rio^&#42;2^ Quisom.

[NOTE]
====
. Lit.: “carros de ferro”.
. Ou: “uádi”.
====

[[v7-4-14]]

^<<v7-4-14,14>>^ Débora disse então a Baraque: “Vai, pois este é o dia em que Jeová entregará Sísera nas tuas mãos. Não é Jeová quem vai à tua frente?” E Baraque desceu do monte Tabor seguido por 10 000 homens.

[[v7-4-15]]

^<<v7-4-15,15>>^ A seguir, Jeová lançou em confusão Sísera, todos os seus carros de guerra e todo o seu exército diante da espada de Baraque. Por fim, Sísera desceu do seu carro e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ Baraque perseguiu os carros de guerra e o exército até Harosete das nações. Assim, todo o exército de Sísera caiu pela espada; não restou nem sequer um.

[[v7-4-17]]

^<<v7-4-17,17>>^ Contudo, Sísera fugiu a pé para a tenda de Jael, esposa de Héber, o queneu, pois havia paz entre Jabim, rei de Hazor, e a casa de Héber, o queneu.

[[v7-4-18]]

^<<v7-4-18,18>>^ Jael foi então ao encontro de Sísera e disse-lhe: “Venha, meu senhor, entre aqui. Não tenha medo.” Assim, ele entrou na tenda dela, e ela tapou-o com um cobertor.

[[v7-4-19]]

^<<v7-4-19,19>>^ Então, ele disse-lhe: “Por favor, dá-me um pouco de água para beber, pois estou com sede.” Portanto, ela abriu um odre de leite e deu-lhe de beber; depois tapou-o novamente.

[[v7-4-20]]

^<<v7-4-20,20>>^ Ele disse-lhe: “Fica de pé à entrada da tenda; se alguém vier e te perguntar: ‘Há aqui algum homem?’ diz: ‘Não!’”

[[v7-4-21]]

^<<v7-4-21,21>>^ No entanto, Jael, esposa de Héber, pegou numa estaca de tenda e num martelo. Então, enquanto ele, esgotado, dormia profundamente, ela aproximou-se silenciosamente e cravou-lhe a estaca nas têmporas, martelando-a no chão. E ele morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ Baraque foi até lá em busca de Sísera e Jael foi ao seu encontro e disse: “Venha, e eu vou mostrar-lhe o homem que procura.” Ele entrou com ela e viu Sísera caído morto, com a estaca nas têmporas.

[[v7-4-23]]

^<<v7-4-23,23>>^ Assim, naquele dia Deus subjugou Jabim, rei de Canaã, diante dos israelitas.

[[v7-4-24]]

^<<v7-4-24,24>>^ A mão dos israelitas ficou cada vez mais dura contra Jabim, rei de Canaã, até que destruíram Jabim, rei de Canaã.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]