include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-18-1]]

^<<v7-18-1,1>>^ Naquela altura não havia rei em Israel. E naqueles dias a tribo dos danitas estava à procura de um lugar^&#42;1^ para morar, pois até então não tinham recebido uma herança entre as tribos de Israel.

[NOTE]
====
. Lit.: “uma herança”.
====

[[v7-18-2]]

^<<v7-18-2,2>>^ Os danitas enviaram cinco homens da sua família, homens capazes de Zorá e Estaol, para espiar e explorar a terra. Disseram-lhes: “Vão, explorem a terra.” Quando chegaram à região montanhosa de Efraim, à casa de Mica, passaram ali a noite.

[[v7-18-3]]

^<<v7-18-3,3>>^ Quando estavam perto da casa de Mica, reconheceram a voz^&#42;1^ do jovem levita, por isso foram ter com ele e perguntaram-lhe: “Quem é que te trouxe para cá? O que é que estás a fazer neste lugar? Porque é que continuas aqui?”

[NOTE]
====
. Ou: “o sotaque”.
====

[[v7-18-4]]

^<<v7-18-4,4>>^ Ele respondeu-lhes: “Foi assim e assim que Mica me fez. Ele contratou-me para lhe servir como sacerdote.”

[[v7-18-5]]

^<<v7-18-5,5>>^ Depois, disseram-lhe: “Por favor, pergunta a Deus se a nossa viagem será bem-sucedida.”

[[v7-18-6]]

^<<v7-18-6,6>>^ O sacerdote disse-lhes: “Vão em paz. Jeová estará convosco nesta viagem.”

[[v7-18-7]]

^<<v7-18-7,7>>^ Portanto, os cinco homens partiram e chegaram a Laís. Viram que o povo que lá morava não dependia de ninguém, como os sidónios. Era um povo tranquilo e despreocupado, e naquela terra não havia conquistadores opressivos que os perturbassem. Eles estavam longe dos sidónios e não se davam com ninguém.

[[v7-18-8]]

^<<v7-18-8,8>>^ Quando voltaram aos seus irmãos em Zorá e em Estaol, os irmãos perguntaram-lhes: “Então, como é que correu?”

[[v7-18-9]]

^<<v7-18-9,9>>^ Eles responderam: “Vamos subir contra eles, pois vimos que a terra é muito boa. Porque é que estão a hesitar? Não se demorem a ir tomar posse da terra.

[[v7-18-10]]

^<<v7-18-10,10>>^ Quando lá chegarem, encontrarão um povo despreocupado e uma terra ampla. Deus entregou-a nas vossas mãos, uma terra onde não falta nada.”

[[v7-18-11]]

^<<v7-18-11,11>>^ Portanto, 600 homens da família dos danitas, armados para a batalha, partiram de Zorá e de Estaol.

[[v7-18-12]]

^<<v7-18-12,12>>^ Eles subiram e acamparam perto de Quiriate-Jearim, em Judá. É por isso que aquele lugar, a oeste de Quiriate-Jearim, se chama Maané-Dã^&#42;1^ até ao dia de hoje.

[NOTE]
====
. Que significa “acampamento de Dã”.
====

[[v7-18-13]]

^<<v7-18-13,13>>^ Dali, foram para a região montanhosa de Efraim e chegaram à casa de Mica.

[[v7-18-14]]

^<<v7-18-14,14>>^ Então, os cinco homens que tinham espiado a terra de Laís disseram aos seus irmãos: “Sabiam que nestas casas há um éfode, ídolos domésticos,^&#42;1^ uma imagem esculpida e uma estátua de metal?^&#42;2^ Pensem no que devem fazer.”

[NOTE]
====
. Ou: “deuses domésticos”. Lit.: “terafins”.
. Ou: “estátua fundida”.
====

[[v7-18-15]]

^<<v7-18-15,15>>^ Então, pararam ali e foram à casa do jovem levita, à casa de Mica, e perguntaram-lhe como estava.

[[v7-18-16]]

^<<v7-18-16,16>>^ Entretanto, os 600 homens de Dã, armados para a batalha, ficaram à entrada do portão.

[[v7-18-17]]

^<<v7-18-17,17>>^ Os cinco homens que tinham espiado a terra entraram para tirar a imagem esculpida, o éfode, os ídolos domésticos^&#42;1^ e a imagem de metal.^&#42;2^ (O sacerdote estava à entrada do portão com os 600 homens armados para a batalha.)

[NOTE]
====
. Ou: “deuses domésticos”. Lit.: “terafins”.
. Ou: “estátua fundida”.
====

[[v7-18-18]]

^<<v7-18-18,18>>^ Eles entraram na casa de Mica e tiraram a imagem esculpida, o éfode, os ídolos domésticos^&#42;1^ e a imagem de metal.^&#42;2^ O sacerdote perguntou-lhes: “O que é que estão a fazer?”

[NOTE]
====
. Ou: “deuses domésticos”. Lit.: “terafins”.
. Ou: “estátua fundida”.
====

[[v7-18-19]]

^<<v7-18-19,19>>^ Contudo, eles disseram-lhe: “Silêncio! Não digas nada.^&#42;1^ Vem connosco e serve-nos como pai^&#42;2^ e sacerdote. O que é melhor: seres sacerdote para a casa de um só homem ou tornares-te sacerdote para uma tribo e família em Israel?”

[NOTE]
====
. Lit.: “Põe a tua mão sobre a tua boca.”
. Ou: “conselheiro”.
====

[[v7-18-20]]

^<<v7-18-20,20>>^ O sacerdote ficou satisfeito. Ele pegou no éfode, nos ídolos domésticos^&#42;1^ e na imagem esculpida e foi-se embora com o povo.

[NOTE]
====
. Ou: “deuses domésticos”. Lit.: “terafins”.
====

[[v7-18-21]]

^<<v7-18-21,21>>^ Retomaram, assim, o seu caminho, e colocaram à frente as crianças, os animais e as coisas valiosas.

[[v7-18-22]]

^<<v7-18-22,22>>^ Já estavam a alguma distância da casa de Mica quando os homens que moravam perto da casa de Mica se reuniram e alcançaram os danitas.

[[v7-18-23]]

^<<v7-18-23,23>>^ Quando gritaram pelos danitas, eles voltaram-se e perguntaram a Mica: “O que é que se passa contigo? Porque é que reuniste estas pessoas?”

[[v7-18-24]]

^<<v7-18-24,24>>^ Ele respondeu: “Vocês tiraram os deuses que eu fiz e também levaram o sacerdote. O que é que me resta? Então, como é que me podem perguntar: ‘O que é que se passa contigo?’”

[[v7-18-25]]

^<<v7-18-25,25>>^ Os danitas responderam: “Não nos levantes a voz; senão homens furiosos^&#42;1^ poderiam atacar-vos, e isso iria custar a tua vida^&#42;2^ e a vida^&#42;3^ dos da tua casa.”

[NOTE]
====
. Ou: “homens de alma amargurada”.
. Ou: “alma”.
. Ou: “alma”.
====

[[v7-18-26]]

^<<v7-18-26,26>>^ Assim, os danitas seguiram o seu caminho. E Mica, vendo que eram mais fortes do que ele, virou-se e voltou para casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Depois de os danitas terem tirado as coisas que Mica fizera, bem como o seu sacerdote, foram para Laís, para um povo tranquilo e despreocupado. Eles mataram-nos com a espada e queimaram a cidade com fogo.

[[v7-18-28]]

^<<v7-18-28,28>>^ Não houve quem livrasse a cidade, pois ficava longe de Sídon e eles não se davam com ninguém; ela ficava no vale^&#42;1^ que pertencia a Bete-Reobe. A seguir, os danitas reconstruíram a cidade e estabeleceram-se nela.

[NOTE]
====
. Ou: “na planície”.
====

[[v7-18-29]]

^<<v7-18-29,29>>^ Além disso, chamaram Dã à cidade, segundo o nome do seu pai, Dã, filho de Israel. Contudo, o nome anterior da cidade era Laís.

[[v7-18-30]]

^<<v7-18-30,30>>^ Depois disso, os danitas erigiram para si a imagem esculpida, e Jonatã, filho de Gérson, filho de Moisés, e os seus filhos tornaram-se sacerdotes para a tribo dos danitas até ao dia em que os habitantes do país foram para o exílio.

[[v7-18-31]]

^<<v7-18-31,31>>^ Eles erigiram a imagem esculpida que Mica tinha feito, e ela permaneceu ali todos os dias em que a casa do verdadeiro Deus estava em Silo.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]