include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-7-1]]

^<<v7-7-1,1>>^ Então, Jerubaal, isto é, Gideão, e todo o povo que estava com ele levantaram-se cedo e acamparam junto à nascente de Harode, enquanto o acampamento de Midiã estava a norte de Gideão, junto à colina de Moré, no vale.^&#42;1^

[NOTE]
====
. Ou: “na planície”.
====

[[v7-7-2]]

^<<v7-7-2,2>>^ Jeová disse então a Gideão: “Há homens a mais contigo para eu entregar Midiã nas tuas mãos. Israel poderia gabar-se às minhas custas e dizer: ‘A minha própria mão salvou-me.’

[[v7-7-3]]

^<<v7-7-3,3>>^ Agora, por favor, anuncia na presença do povo: ‘Quem está com medo e a tremer volte para casa.’” Assim, Gideão pô-los à prova. Com isso, 22 000 homens regressaram a casa, e 10 000 permaneceram.

[[v7-7-4]]

^<<v7-7-4,4>>^ Contudo, Jeová disse a Gideão: “Ainda tens homens a mais. Leva-os até à água para que ali eu os ponha à prova para ti. Quando eu disser: ‘Este irá contigo’, ele irá contigo; mas, quando eu disser: ‘Este não irá contigo’, ele não irá contigo.”

[[v7-7-5]]

^<<v7-7-5,5>>^ Então, ele levou o povo até à água.
E Jeová disse a Gideão: “Separa todos os que beberem a água lambendo-a como faz o cão, daqueles que se ajoelharem para beber.”

[[v7-7-6]]

^<<v7-7-6,6>>^ O número dos que lamberam a água, levando a mão à boca, foi de 300 homens. O restante dos homens ajoelhou-se para beber.

[[v7-7-7]]

^<<v7-7-7,7>>^ Jeová disse a Gideão: “Vou salvar-vos com os 300 homens que lamberam a água, levando a mão à boca, e entregarei Midiã nas tuas mãos. No entanto, que todos os outros homens voltem para casa.”

[[v7-7-8]]

^<<v7-7-8,8>>^ Assim, depois de tirarem as provisões e as buzinas ao povo, ele mandou todos os outros homens de Israel regressarem a casa, ficando apenas com os 300 homens. O acampamento de Midiã estava abaixo deles, no vale.^&#42;1^

[NOTE]
====
. Ou: “na planície”.
====

[[v7-7-9]]

^<<v7-7-9,9>>^ Naquela noite, Jeová disse-lhe: “Levanta-te e ataca o acampamento, pois entreguei-o nas tuas mãos.

[[v7-7-10]]

^<<v7-7-10,10>>^ Todavia, se estiveres com medo de atacar, desce até ao acampamento com Pura, teu ajudante.

[[v7-7-11]]

^<<v7-7-11,11>>^ Escuta o que estiverem a dizer, e depois terás coragem^&#42;1^ para atacar o acampamento.” Em vista disso, Gideão e Pura, seu ajudante, desceram até à extremidade do acampamento do exército.

[NOTE]
====
. Lit.: “as tuas mãos ficarão fortes”.
====

[[v7-7-12]]

^<<v7-7-12,12>>^ Midiã, Amaleque e todos os orientais cobriam o vale^&#42;1^ como uma nuvem de gafanhotos; e os seus camelos eram incontáveis, tão numerosos como os grãos de areia à beira-mar.

[NOTE]
====
. Ou: “a planície”.
====

[[v7-7-13]]

^<<v7-7-13,13>>^ Quando Gideão chegou, estava um homem a contar um sonho a um companheiro. Ele dizia: “Este é o sonho que tive. Um pão redondo de cevada rolou para dentro do acampamento de Midiã. Atingiu uma tenda com tanta força que ela caiu. Sim, fez a tenda virar-se ao contrário, e a tenda ficou caída no chão.”

[[v7-7-14]]

^<<v7-7-14,14>>^ Então, o companheiro disse: “Isso só pode ser a espada de Gideão, filho de Joás, homem de Israel. Deus entregou Midiã e todo o acampamento nas suas mãos.”

[[v7-7-15]]

^<<v7-7-15,15>>^ Assim que Gideão ouviu o sonho e a sua interpretação, prostrou-se para adorar. Depois voltou ao acampamento de Israel e disse: “Levantem-se, pois Jeová entregou o acampamento de Midiã nas vossas mãos.”

[[v7-7-16]]

^<<v7-7-16,16>>^ Então, dividiu os 300 homens em três grupos e deu buzinas a todos e cântaros grandes, vazios, com tochas lá dentro.

[[v7-7-17]]

^<<v7-7-17,17>>^ E disse-lhes: “Observem-me e façam exatamente o que eu fizer. Quando eu chegar à extremidade do acampamento, devem fazer como eu fizer.

[[v7-7-18]]

^<<v7-7-18,18>>^ Quando eu e todos os que estiverem comigo tocarmos as buzinas, toquem também as vossas buzinas ao redor de todo o acampamento e gritem: ‘Por Jeová e por Gideão!’”

[[v7-7-19]]

^<<v7-7-19,19>>^ Gideão e os cem homens que estavam com ele chegaram à extremidade do acampamento no início da segunda vigília da noite,^&#42;1^ logo após a mudança da guarda. Tocaram as buzinas e espatifaram os cântaros grandes que tinham nas mãos.

[NOTE]
====
. De cerca das 10 h da noite a cerca das 2 h da madrugada.
====

[[v7-7-20]]

^<<v7-7-20,20>>^ Então, os três grupos tocaram as buzinas e partiram os cântaros grandes. Seguraram as tochas com a mão esquerda, tocaram as buzinas que seguravam com a mão direita e gritaram: “A espada de Jeová e de Gideão!”

[[v7-7-21]]

^<<v7-7-21,21>>^ Cada homem ficou parado no seu lugar ao redor do acampamento, e todo o exército inimigo começou a fugir, a correr e a gritar.

[[v7-7-22]]

^<<v7-7-22,22>>^ Enquanto os 300 tocavam as buzinas, Jeová fez com que a espada de cada um se voltasse contra o outro em todo o acampamento. E o exército inimigo fugiu até Bete-Sita, de lá para Zererá, e até aos arredores de Abel-Meolá, junto a Tabate.

[[v7-7-23]]

^<<v7-7-23,23>>^ E os homens de Israel foram convocados de Naftali, de Aser e de todo o Manassés, e eles perseguiram Midiã.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gideão enviou mensageiros a toda a região montanhosa de Efraim, dizendo: “Desçam para atacar Midiã e apoderem-se dos pontos de travessia até Bete-Bara e até ao Jordão.” Assim foram reunidos todos os homens de Efraim, e apoderaram-se dos pontos de travessia até Bete-Bara e até ao Jordão.

[[v7-7-25]]

^<<v7-7-25,25>>^ Além disso, capturaram os dois príncipes de Midiã, Orebe e Zeebe; mataram Orebe na rocha de Orebe, e mataram Zeebe no lagar de vinho de Zeebe. Continuaram a perseguir Midiã, e levaram a cabeça de Orebe e a de Zeebe a Gideão, na região do Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]