include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-12-1]]

^<<v7-12-1,1>>^ Então, os homens de Efraim foram convocados, e atravessaram para Zafom^&#42;1^ e disseram a Jefté: “Porque é que não nos chamaste para ir contigo quando atravessaste o rio para lutar contra os amonitas? Vamos queimar a tua casa contigo lá dentro.”

[NOTE]
====
. Ou, possivelmente: “atravessaram em direção ao norte”.
====

[[v7-12-2]]

^<<v7-12-2,2>>^ Jefté, porém, disse-lhes: “Eu e o meu povo estávamos envolvidos num grande conflito com os amonitas. Chamei-vos para me ajudarem, mas não me salvaram das mãos deles.

[[v7-12-3]]

^<<v7-12-3,3>>^ Quando vi que não me salvariam, decidi arriscar a vida^&#42;1^ e ir contra os amonitas, e Jeová entregou-mos. Portanto, porque é que hoje vocês vieram lutar contra mim?”

[NOTE]
====
. Ou: “coloquei a minha alma na mão”.
====

[[v7-12-4]]

^<<v7-12-4,4>>^ A seguir, Jefté reuniu todos os homens de Gileade, e eles lutaram contra Efraim; os homens de Gileade derrotaram Efraim, que tinha dito: “Vocês, gileaditas em Efraim e Manassés, são apenas fugitivos de Efraim.”

[[v7-12-5]]

^<<v7-12-5,5>>^ Gileade apoderou-se dos pontos de travessia do Jordão que ficavam em frente a Efraim. Quando um homem de Efraim tentava fugir, dizia: “Deixa-me passar”; e os homens de Gileade perguntavam: “És tu efraimita?” Quando ele respondia: “Não!”

[[v7-12-6]]

^<<v7-12-6,6>>^ eles diziam-lhe: “Por favor, diz xibolete.” Mas ele dizia “sibolete”, pois não conseguia pronunciar a palavra corretamente. Então, agarravam-no e matavam-no junto aos pontos de travessia do Jordão. Assim, naquela ocasião 42 000 efraimitas foram mortos.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté julgou Israel durante seis anos. Depois Jefté, o gileadita, morreu e foi enterrado na sua cidade, em Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ Ibsã, de Belém, julgou Israel depois dele.

[[v7-12-9]]

^<<v7-12-9,9>>^ Ele tinha 30 filhos e 30 filhas. Enviou as suas filhas para casarem com homens fora do seu clã,^&#42;1^ e trouxe 30 mulheres para casarem com os seus filhos. Ele julgou Israel durante sete anos.

[NOTE]
====
. Ou: “da sua família”.
====

[[v7-12-10]]

^<<v7-12-10,10>>^ Por fim, Ibsã morreu e foi enterrado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Depois dele, Elom, o zebulonita, julgou Israel; ele julgou Israel durante dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Por fim, Elom, o zebulonita, morreu e foi enterrado em Aijalom, na terra de Zebulão.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois dele, Abdom, filho de Hilel, o piratonita, julgou Israel.

[[v7-12-14]]

^<<v7-12-14,14>>^ Ele tinha 40 filhos e 30 netos que montavam 70 jumentos. Ele julgou Israel durante oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Por fim, Abdom, filho de Hilel, o piratonita, morreu e foi enterrado em Piratom, na terra de Efraim, no monte do amalequita.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]