include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-16-1]]

^<<v7-16-1,1>>^ Certa vez, Sansão foi a Gaza, viu lá uma prostituta e entrou na casa dela.

[[v7-16-2]]

^<<v7-16-2,2>>^ Disseram aos gazitas: “Sansão está aqui.” Então cercaram-no, armaram-lhe uma emboscada e ficaram toda a noite no portão da cidade. E ficaram quietos toda a noite, a pensar: “Quando amanhecer, vamos matá-lo.”

[[v7-16-3]]

^<<v7-16-3,3>>^ No entanto, Sansão ficou ali deitado até à meia-noite. Depois, levantou-se à meia-noite e agarrou nos portões da cidade, e nas duas ombreiras, e arrancou-os juntamente com a tranca. Ele pô-los aos ombros e carregou-os para cima, até ao cume do monte que fica em frente a Hébron.

[[v7-16-4]]

^<<v7-16-4,4>>^ Depois disso, apaixonou-se por uma mulher do vale^&#42;1^ de Soreque, chamada Dalila.

[NOTE]
====
. Ou: “uádi”.
====

[[v7-16-5]]

^<<v7-16-5,5>>^ Então, os governantes dos filisteus dirigiram-se a ela e disseram: “Engana^&#42;1^ Sansão e descobre o que lhe dá tanta força, e como o podemos dominar, amarrar e vencer. Se o fizeres, cada um de nós te dará 1100 peças de prata.”

[NOTE]
====
. Ou: “Convence”.
====

[[v7-16-6]]

^<<v7-16-6,6>>^ Mais tarde, Dalila disse a Sansão: “Por favor, diz-me de onde vem a tua grande força e o que se pode usar para te amarrar e vencer.”

[[v7-16-7]]

^<<v7-16-7,7>>^ Sansão disse-lhe: “Se me amarrarem com sete cordas de arco novas,^&#42;1^ que ainda não estiverem secas, ficarei tão fraco como um homem comum.”

[NOTE]
====
. Ou: “tendões frescos”.
====

[[v7-16-8]]

^<<v7-16-8,8>>^ Portanto, os governantes dos filisteus trouxeram-lhe sete cordas de arco novas, que ainda não estavam secas, e ela amarrou-o com elas.

[[v7-16-9]]

^<<v7-16-9,9>>^ Os homens armaram uma emboscada no quarto e ela gritou: “Os filisteus estão aqui, Sansão!” Nisso ele rebentou as cordas de arco, com a mesma facilidade com que um fio de linho^&#42;1^ se rompe quando toca no fogo. Assim, o segredo da sua força não foi descoberto.

[NOTE]
====
. Ou: “estopa”.
====

[[v7-16-10]]

^<<v7-16-10,10>>^ Por isso, Dalila disse a Sansão: “Enganaste-me^&#42;1^ e mentiste-me! Agora, por favor, diz-me o que se pode usar para te amarrar.”

[NOTE]
====
. Ou: “Gozaste comigo”.
====

[[v7-16-11]]

^<<v7-16-11,11>>^ Portanto, ele disse-lhe: “Se me amarrarem com cordas novas, que nunca foram usadas, ficarei tão fraco como um homem comum.”

[[v7-16-12]]

^<<v7-16-12,12>>^ Então, Dalila pegou em cordas novas e amarrou-o, e gritou: “Os filisteus estão aqui, Sansão!” (Enquanto isso, os homens estavam de emboscada no quarto.) E ele arrancou as cordas dos braços como se fossem fios.

[[v7-16-13]]

^<<v7-16-13,13>>^ Mais tarde, Dalila disse a Sansão: “Até agora, enganaste-me e mentiste-me. Diz-me o que se pode usar para te amarrar.” E ele disse-lhe: “É só teceres as sete tranças da minha cabeça com o fio da urdidura de um tear.”

[[v7-16-14]]

^<<v7-16-14,14>>^ Assim, ela fixou-as com um pino e gritou: “Os filisteus estão aqui, Sansão!” Ele acordou do sono e arrancou o pino do tear e o fio da urdidura.

[[v7-16-15]]

^<<v7-16-15,15>>^ Consequentemente, ela disse-lhe: “Como é que tu podes dizer que me amas, se não me abres o teu coração? Enganaste-me estas três vezes e não me disseste de onde vem a tua grande força.”

[[v7-16-16]]

^<<v7-16-16,16>>^ Visto que dia após dia ela o importunava e o pressionava, ele ficou tão esgotado^&#42;1^ que já não aguentava mais.

[NOTE]
====
. Ou: “a alma dele ficou esgotada”.
====

[[v7-16-17]]

^<<v7-16-17,17>>^ Por fim, abriu-lhe o coração e disse: “O meu cabelo nunca foi cortado, pois sou um nazireu de Deus desde que nasci.^&#42;1^ Se o meu cabelo for cortado, perderei a força, ficarei fraco e vou tornar-me igual a todos os outros homens.”

[NOTE]
====
. Lit.: “desde o ventre da minha mãe”.
====

[[v7-16-18]]

^<<v7-16-18,18>>^ Quando Dalila viu que ele lhe tinha aberto o coração, mandou chamar imediatamente os governantes filisteus, dizendo: “Venham, pois desta vez, ele abriu-me o seu coração.” Assim, os governantes filisteus foram ter com ela e levaram o dinheiro.

[[v7-16-19]]

^<<v7-16-19,19>>^ Ela adormeceu-o sobre os seus joelhos. A seguir, chamou um homem para lhe cortar as sete tranças da cabeça. Depois, ela passou a dominá-lo, pois ele foi perdendo a força.

[[v7-16-20]]

^<<v7-16-20,20>>^ Então, ela gritou: “Os filisteus estão aqui, Sansão!” Ele acordou do sono e disse: “Vou sair-me bem como das outras vezes e vou livrar-me.” Ele, porém, não sabia que Jeová o tinha deixado.

[[v7-16-21]]

^<<v7-16-21,21>>^ Portanto, os filisteus agarraram-no e furaram-lhe os olhos. Depois levaram-no para baixo, a Gaza, e prenderam-no com duas correntes de cobre, e ele tornou-se moedor de grãos na prisão.

[[v7-16-22]]

^<<v7-16-22,22>>^ Contudo, depois de lhe terem cortado o cabelo, este começou a crescer novamente.

[[v7-16-23]]

^<<v7-16-23,23>>^ Os governantes filisteus reuniram-se para oferecer um grande sacrifício a Dagom, seu deus, e para celebrar, pois diziam: “O nosso deus entregou Sansão, o nosso inimigo, nas nossas mãos!”

[[v7-16-24]]

^<<v7-16-24,24>>^ Quando o povo o viu, louvou o seu deus, dizendo: “O nosso deus entregou nas nossas mãos o nosso inimigo, aquele que devastava a nossa terra e matava muitos dos nossos.”

[[v7-16-25]]

^<<v7-16-25,25>>^ Visto que o coração deles estava alegre, disseram: “Chamem Sansão, para nos entreter.” Por isso, chamaram Sansão da prisão para os divertir; fizeram-no ficar de pé entre as colunas.

[[v7-16-26]]

^<<v7-16-26,26>>^ Depois, Sansão disse ao jovem que o segurava pela mão: “Deixa-me tocar nas colunas que sustentam a casa, para que eu me apoie nelas.”

[[v7-16-27]]

^<<v7-16-27,27>>^ (A propósito, a casa estava cheia de homens e mulheres. Todos os governantes filisteus estavam ali, e no terraço havia cerca de 3000 homens e mulheres que olhavam enquanto se divertiam às custas de Sansão.)

[[v7-16-28]]

^<<v7-16-28,28>>^ Sansão clamou então a Jeová: “Soberano Senhor Jeová, por favor, lembra-te de mim e fortalece-me só desta vez, por favor, ó Deus, e deixa-me vingar-me dos filisteus por um dos meus olhos.”

[[v7-16-29]]

^<<v7-16-29,29>>^ De seguida, Sansão apoiou-se nas duas colunas centrais que sustentavam a casa, numa com a mão direita e na outra com a mão esquerda.

[[v7-16-30]]

^<<v7-16-30,30>>^ Sansão clamou: “Que eu^&#42;1^ morra com os filisteus!” A seguir, ele empurrou as colunas com toda a sua força, e a casa caiu sobre os governantes e todos os que lá estavam. Assim, ao morrer, ele matou mais pessoas do que tinha matado durante a sua vida.

[NOTE]
====
. Ou: “a minha alma”.
====

[[v7-16-31]]

^<<v7-16-31,31>>^ Mais tarde, os seus irmãos e toda a família do seu pai desceram para ir buscar o seu corpo. Levaram-no e enterraram-no entre Zorá e Estaol, na sepultura de Manoá, seu pai. Sansão tinha julgado Israel durante 20 anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]