include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois de Abimeleque, um homem de Issacar chamado Tola, que era filho de Puá, filho de Dodo, levantou-se para salvar Israel. Ele morava em Samir, na região montanhosa de Efraim.

[[v7-10-2]]

^<<v7-10-2,2>>^ Ele julgou Israel durante 23 anos. Depois, morreu e foi enterrado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Depois dele, levantou-se Jair, o gileadita, que julgou Israel durante 22 anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Ele tinha 30 filhos que montavam 30 jumentos, e tinham 30 cidades, que se chamam Havote-Jair até ao dia de hoje e ficam na terra de Gileade.

[[v7-10-5]]

^<<v7-10-5,5>>^ Depois, Jair morreu e foi enterrado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ Os israelitas fizeram novamente o que era mau aos olhos de Jeová e começaram a servir os baalins, as imagens de Astorete, os deuses de Arã,^&#42;1^ os deuses de Sídon, os deuses de Moabe, os deuses dos amonitas e os deuses dos filisteus. Eles abandonaram a Jeová e não o serviram.

[NOTE]
====
. Ou: “da Síria”.
====

[[v7-10-7]]

^<<v7-10-7,7>>^ Nisso acendeu-se a ira de Jeová contra Israel, e ele entregou-os^&#42;1^ nas mãos dos filisteus e dos amonitas.

[NOTE]
====
. Lit.: “vendeu-os”.
====

[[v7-10-8]]

^<<v7-10-8,8>>^ E eles afligiram e oprimiram muito os israelitas naquele ano — durante 18 anos oprimiram todos os israelitas que estavam no lado do Jordão que tinha sido a terra dos amorreus, em Gileade.

[[v7-10-9]]

^<<v7-10-9,9>>^ Os amonitas também atravessavam o Jordão para lutar contra Judá, Benjamim e a casa de Efraim, causando grande aflição a Israel.

[[v7-10-10]]

^<<v7-10-10,10>>^ Então, os israelitas clamaram a Jeová por ajuda, dizendo: “Pecámos contra ti, pois abandonámos o nosso Deus e servimos aos baalins.”

[[v7-10-11]]

^<<v7-10-11,11>>^ Contudo, Jeová disse aos israelitas: “Será que eu não vos livrei do Egito, dos amorreus, dos amonitas, dos filisteus,

[[v7-10-12]]

^<<v7-10-12,12>>^ dos sidónios, de Amaleque e de Midiã quando vos oprimiram? Quando clamaram a mim, livrei-vos das suas mãos.

[[v7-10-13]]

^<<v7-10-13,13>>^ Mas abandonaram-me e serviram outros deuses. É por isso que não vos livrarei mais.

[[v7-10-14]]

^<<v7-10-14,14>>^ Vão ter com os deuses que escolheram e clamem por ajuda. Que eles vos salvem no tempo da vossa aflição.”

[[v7-10-15]]

^<<v7-10-15,15>>^ Mas os israelitas disseram a Jeová: “Pecámos. Faz connosco o que for bom aos teus olhos. Apenas salva-nos hoje, por favor.”

[[v7-10-16]]

^<<v7-10-16,16>>^ E eliminaram os deuses estrangeiros do seu meio e serviram a Jeová, de modo que ele já não suportava mais ver o^&#42;1^ sofrimento de Israel.

[NOTE]
====
. Ou: “e a sua alma ficou impaciente por causa do”.
====

[[v7-10-17]]

^<<v7-10-17,17>>^ Então, os amonitas foram convocados e acamparam em Gileade. Portanto, os israelitas reuniram-se e acamparam em Mispá.

[[v7-10-18]]

^<<v7-10-18,18>>^ O povo e os príncipes de Gileade disseram uns aos outros: “Quem é que nos vai liderar na luta contra os amonitas? Que ele se torne o líder de todos os habitantes de Gileade.”

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]