include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-2-1]]

^<<v7-2-1,1>>^ Então, o anjo de Jeová subiu de Gilgal a Boquim e disse: “Tirei-vos do Egito e trouxe-vos para a terra a respeito da qual jurei aos vossos antepassados. Eu também disse: ‘Nunca quebrarei o meu pacto convosco.

[[v7-2-2]]

^<<v7-2-2,2>>^ Vocês, da vossa parte, não façam nenhum pacto com os habitantes desta terra, e devem demolir os altares deles.’ Mas vocês não obedeceram à minha voz. Porque é que agiram assim?

[[v7-2-3]]

^<<v7-2-3,3>>^ Foi por isso que eu também disse: ‘Não os expulsarei da vossa frente; eles vão tornar-se um laço para vocês, e os seus deuses hão de seduzir-vos.’”

[[v7-2-4]]

^<<v7-2-4,4>>^ Quando o anjo de Jeová disse estas palavras a todos os israelitas, o povo começou a chorar em voz alta.

[[v7-2-5]]

^<<v7-2-5,5>>^ Por isso, deram ao lugar o nome de Boquim,^&#42;1^ e ali ofereceram sacrifícios a Jeová.

[NOTE]
====
. Que significa “chorões”.
====

[[v7-2-6]]

^<<v7-2-6,6>>^ Quando Josué mandou o povo embora, os israelitas foram cada um para a sua herança, a fim de tomarem posse da terra.

[[v7-2-7]]

^<<v7-2-7,7>>^ O povo continuou a servir a Jeová durante todos os dias de Josué e durante todos os dias dos anciãos que continuaram vivos depois de Josué e que tinham visto todos os grandes atos de Jeová a favor de Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Depois, Josué, filho de Num, o servo de Jeová, morreu com 110 anos de idade.

[[v7-2-9]]

^<<v7-2-9,9>>^ Assim, enterraram-no no território da sua herança, em Timnate-Heres, na região montanhosa de Efraim, a norte do monte Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ Toda aquela geração foi reunida aos seus antepassados,^&#42;1^ e depois dela surgiu outra geração que não conhecia a Jeová nem o que ele tinha feito por Israel.

[NOTE]
====
. Expressão poética que se refere à morte.
====

[[v7-2-11]]

^<<v7-2-11,11>>^ Então, os israelitas fizeram o que era mau aos olhos de Jeová e serviram os^&#42;1^ baalins.

[NOTE]
====
. Ou: “adoraram os”.
====

[[v7-2-12]]

^<<v7-2-12,12>>^ Abandonaram a Jeová, o Deus dos seus pais, que os tinha tirado da terra do Egito. E seguiram outros deuses, os deuses dos povos ao seu redor; eles curvaram-se diante deles e ofenderam a Jeová.

[[v7-2-13]]

^<<v7-2-13,13>>^ Abandonaram a Jeová e serviram Baal e as imagens de Astorete.

[[v7-2-14]]

^<<v7-2-14,14>>^ Em vista disso, a ira de Jeová acendeu-se contra Israel, de modo que os entregou aos saqueadores, que os despojaram. Entregou-os^&#42;1^ nas mãos dos inimigos ao redor deles, e eles já não foram capazes de resistir aos seus inimigos.

[NOTE]
====
. Lit.: “Vendeu-os”.
====

[[v7-2-15]]

^<<v7-2-15,15>>^ Aonde quer que fossem, a mão de Jeová estava contra eles, trazendo-lhes calamidades, assim como Jeová tinha dito e assim como Jeová lhes tinha jurado; e eles estavam numa grande aflição.

[[v7-2-16]]

^<<v7-2-16,16>>^ Portanto, Jeová dava-lhes juízes, que os salvavam das mãos dos seus saqueadores.

[[v7-2-17]]

^<<v7-2-17,17>>^ Porém, eles recusaram-se a escutar até mesmo os juízes; prostituíam-se com outros deuses e curvavam-se diante deles. Desviaram-se depressa do caminho em que os seus antepassados andaram, os que tinham obedecido aos mandamentos de Jeová. Eles não agiram da mesma maneira.

[[v7-2-18]]

^<<v7-2-18,18>>^ Sempre que Jeová lhes dava um juiz, Jeová estava com o juiz e salvava-os das mãos dos seus inimigos, durante todos os dias do juiz; pois Jeová compadecia-se dos^&#42;1^ seus gemidos, causados pelos que os oprimiam e os tratavam cruelmente.

[NOTE]
====
. Ou: “Jeová lamentava os”.
====

[[v7-2-19]]

^<<v7-2-19,19>>^ Contudo, quando o juiz morria, eles voltavam a corromper-se ainda mais do que os seus pais, seguindo outros deuses, servindo-os e curvando-se diante deles. Não abandonavam as suas práticas, nem o seu proceder obstinado.

[[v7-2-20]]

^<<v7-2-20,20>>^ Por fim, a ira de Jeová acendeu-se contra Israel, e ele disse: “Visto que esta nação violou o meu pacto, que fiz com os seus antepassados, e me desobedeceu,

[[v7-2-21]]

^<<v7-2-21,21>>^ eu, da minha parte, não expulsarei da sua frente nem mesmo uma das nações que Josué deixou quando morreu.

[[v7-2-22]]

^<<v7-2-22,22>>^ Isto é para provar se Israel guardará o caminho de Jeová, por andar nele assim como os seus antepassados fizeram.”

[[v7-2-23]]

^<<v7-2-23,23>>^ Por isso, Jeová permitiu que estas nações permanecessem. Não as expulsou imediatamente nem as entregou nas mãos de Josué.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]