include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-19-1]]

^<<v7-19-1,1>>^ Naqueles dias, quando não havia rei em Israel, um levita que estava a morar numa parte remota da região montanhosa de Efraim tomou para si uma esposa, uma concubina, que era de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ No entanto, a sua concubina foi-lhe infiel, e deixou-o para ir para a casa do pai dela em Belém de Judá. Ela ficou lá quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ Portanto, o marido foi atrás dela para a convencer a voltar; ele levou consigo o seu ajudante e dois jumentos. Ela recebeu-o na casa do seu pai. Quando o pai dela o viu, ficou contente de o encontrar.

[[v7-19-4]]

^<<v7-19-4,4>>^ Por isso, o seu sogro, o pai da jovem, convenceu-o a ficar com ele três dias; eles comiam e bebiam, e ele passou ali as noites.

[[v7-19-5]]

^<<v7-19-5,5>>^ No quarto dia, quando se levantaram de manhã cedo para partir, o pai da jovem disse ao genro: “Come alguma coisa para te dar forças,^&#42;1^ e depois podem ir.”

[NOTE]
====
. Ou: “revigorar o teu coração”.
====

[[v7-19-6]]

^<<v7-19-6,6>>^ Assim, sentaram-se e comeram e beberam juntos. Depois o pai da jovem disse ao homem: “Por favor, passa a noite aqui e alegra-te.”^&#42;1^

[NOTE]
====
. Ou: “faz o teu coração sentir-se bem”.
====

[[v7-19-7]]

^<<v7-19-7,7>>^ Quando o homem se levantou para partir, o sogro implorou-lhe que ficasse, de modo que passou outra vez ali a noite.

[[v7-19-8]]

^<<v7-19-8,8>>^ No quinto dia, quando se levantou de manhã cedo para partir, o pai da jovem disse: “Por favor, come alguma coisa para te dar forças.”^&#42;1^ Ficaram ali até tarde; e os dois continuaram a comer.

[NOTE]
====
. Ou: “revigorar o teu coração”.
====

[[v7-19-9]]

^<<v7-19-9,9>>^ Quando o homem se levantou para partir com a sua concubina e o seu ajudante, o seu sogro, o pai da jovem, disse-lhe: “Olha, já está a anoitecer. Por favor, fiquem esta noite. O dia está quase a acabar. Passa a noite aqui e alegra-te. Amanhã poderão levantar-se cedo e viajar de volta para casa.”^&#42;1^

[NOTE]
====
. Lit.: “a vossa tenda”.
====

[[v7-19-10]]

^<<v7-19-10,10>>^ No entanto, o homem não quis ficar outra noite, e assim levantou-se e viajou até Jebus, isto é, Jerusalém. Estavam com ele os dois jumentos selados, a sua concubina e o seu ajudante.

[[v7-19-11]]

^<<v7-19-11,11>>^ Quando estavam perto de Jebus, o dia estava quase a acabar. Então, o ajudante perguntou ao seu senhor: “Devemos parar nesta cidade dos jebuseus e passar aqui a noite?”

[[v7-19-12]]

^<<v7-19-12,12>>^ O seu senhor, porém, disse-lhe: “Não devemos parar numa cidade de estrangeiros, cujo povo não é israelita. Vamos continuar até Gibeá.”

[[v7-19-13]]

^<<v7-19-13,13>>^ A seguir, ele disse ao seu ajudante: “Vamos tentar chegar a Gibeá ou a Ramá; passaremos a noite num desses lugares.”

[[v7-19-14]]

^<<v7-19-14,14>>^ Assim, seguiram caminho, e o sol começou a pôr-se quando estavam perto de Gibeá, que pertence a Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Por isso, pararam em Gibeá e entraram ali para passar a noite. Uma vez dentro da cidade, sentaram-se na praça pública, mas ninguém os acolheu em casa para passarem a noite.

[[v7-19-16]]

^<<v7-19-16,16>>^ Finalmente, ao anoitecer, veio um homem idoso do seu trabalho no campo. Ele era da região montanhosa de Efraim e estava a morar por um tempo em Gibeá; mas os moradores da cidade eram benjaminitas.

[[v7-19-17]]

^<<v7-19-17,17>>^ Quando o homem idoso levantou os olhos e viu o viajante na praça pública da cidade, perguntou: “Para onde vais e de onde vens?”

[[v7-19-18]]

^<<v7-19-18,18>>^ Ele respondeu: “Estamos a viajar de Belém de Judá para uma parte remota da região montanhosa de Efraim; eu sou de lá. Fui a Belém de Judá e vou para a casa de Jeová,^&#42;1^ mas ninguém me acolheu em casa.

[NOTE]
====
. Ou, possivelmente: “e sirvo na casa de Jeová”.
====

[[v7-19-19]]

^<<v7-19-19,19>>^ Temos palha e forragem suficientes para os nossos jumentos, e pão e vinho para mim, para a mulher e para o nosso ajudante. Não nos falta nada.”

[[v7-19-20]]

^<<v7-19-20,20>>^ No entanto, o homem idoso disse: “Que a paz esteja contigo! Vou cuidar de tudo o que precisares. Só não passes a noite na praça pública.”

[[v7-19-21]]

^<<v7-19-21,21>>^ Assim, levou-o para a sua casa e deu de comer^&#42;1^ aos jumentos. Depois lavaram os pés e comeram e beberam.

[NOTE]
====
. Ou: “e deu forragem misturada”.
====

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto se alegravam, homens imprestáveis da cidade cercaram a casa e começaram a dar murros na porta, dizendo ao homem idoso, o dono da casa: “Traz cá para fora o homem que veio à tua casa, para que tenhamos relações sexuais com ele.”

[[v7-19-23]]

^<<v7-19-23,23>>^ Em vista disso, o dono da casa saiu e disse-lhes: “Não, meus irmãos, não façam uma maldade dessas. Por favor, este homem é hóspede na minha casa. Não cometam esse ato vergonhoso.

[[v7-19-24]]

^<<v7-19-24,24>>^ A minha filha virgem e a concubina deste homem estão aqui. Deixem-me trazê-las para fora, e podem humilhá-las se tiver de ser.^&#42;1^ Mas não cometam esse ato vergonhoso contra este homem.”

[NOTE]
====
. Ou: “podem abusar delas e fazer o que for bom aos vossos olhos”.
====

[[v7-19-25]]

^<<v7-19-25,25>>^ No entanto, os homens recusaram-se a escutá-lo; por isso, o homem agarrou na sua concubina e levou-a para fora até eles. Eles violaram-na e abusaram dela toda a noite, até de madrugada. Depois mandaram-na embora ao raiar do dia.

[[v7-19-26]]

^<<v7-19-26,26>>^ De manhã bem cedo, a mulher chegou e caiu à entrada da casa do homem onde estava o seu senhor, e ficou ali até o dia clarear.

[[v7-19-27]]

^<<v7-19-27,27>>^ Quando o seu senhor se levantou de manhã e abriu a porta da casa para sair e continuar a viagem, ele viu a mulher, a sua concubina, caída à entrada da casa com as mãos na soleira.

[[v7-19-28]]

^<<v7-19-28,28>>^ Ele disse-lhe: “Levanta-te; vamos embora.” Contudo, não houve resposta. O homem pô-la então sobre o jumento e foi para casa.

[[v7-19-29]]

^<<v7-19-29,29>>^ Quando ele chegou a casa, pegou no cutelo e, segurando a sua concubina, cortou-a membro por membro, em 12 pedaços, e enviou um pedaço para cada território de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ Todos os que viram isso disseram: “Nunca aconteceu nem se viu tal coisa desde o dia em que os israelitas saíram da terra do Egito até ao dia de hoje. Reflitam nisso,^&#42;1^ consultem-se e digam-nos o que fazer.”

[NOTE]
====
. Ou: “Fixem nisso os vossos corações”.
====

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]