include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-21-1]]

^<<v7-21-1,1>>^ Os homens de Israel tinham feito este juramento em Mispá: “Nenhum de nós dará a sua filha como esposa a um homem de Benjamim.”

[[v7-21-2]]

^<<v7-21-2,2>>^ Por isso, o povo foi a Betel e sentou-se ali perante o verdadeiro Deus até ao anoitecer, a clamar e a chorar amargamente.

[[v7-21-3]]

^<<v7-21-3,3>>^ Eles diziam: “Ó Jeová, Deus de Israel, porque é que isto aconteceu em Israel? Porque é que hoje deveria estar a faltar uma tribo em Israel?”

[[v7-21-4]]

^<<v7-21-4,4>>^ E no dia seguinte o povo levantou-se cedo e construiu ali um altar para fazer ofertas queimadas e ofertas de participação em comum.

[[v7-21-5]]

^<<v7-21-5,5>>^ A seguir, o povo de Israel disse: “Qual das tribos de Israel não subiu para se reunir perante Jeová?” Pois tinham feito um juramento solene de que quem não comparecesse perante Jeová em Mispá sem falta seria morto.

[[v7-21-6]]

^<<v7-21-6,6>>^ E o povo de Israel ficou com pena do que tinha acontecido com o seu irmão Benjamim. Eles disseram: “Hoje, foi eliminada uma tribo de Israel.

[[v7-21-7]]

^<<v7-21-7,7>>^ O que é que devemos fazer para conseguir esposas para os que restaram, uma vez que jurámos por Jeová que não lhes daríamos nenhuma das nossas filhas como esposa?”

[[v7-21-8]]

^<<v7-21-8,8>>^ Eles perguntaram: “Quem dentre as tribos de Israel não compareceu perante Jeová em Mispá?” Aconteceu que ninguém de Jabes-Gileade tinha ido ao acampamento onde estava a congregação.

[[v7-21-9]]

^<<v7-21-9,9>>^ Quando contaram o povo, viram que nenhum dos habitantes de Jabes-Gileade estava lá.

[[v7-21-10]]

^<<v7-21-10,10>>^ Portanto, a assembleia enviou para lá 12 000 dos homens mais valentes. Ordenaram-lhes: “Vão e golpeiem com a espada os habitantes de Jabes-Gileade, até mesmo as mulheres e as crianças.

[[v7-21-11]]

^<<v7-21-11,11>>^ Isto é o que devem fazer: Devem entregar à destruição^&#42;1^ todos os homens, bem como todas as mulheres que já tiveram relações sexuais com um homem.”

[NOTE]
====
. Ou: “devotar à destruição”. Veja o Glossário.
====

[[v7-21-12]]

^<<v7-21-12,12>>^ Entre os habitantes de Jabes-Gileade, encontraram 400 jovens que eram virgens, que nunca tinham tido relações sexuais com nenhum homem. Consequentemente, levaram-nas ao acampamento em Silo, na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Depois, toda a assembleia enviou uma mensagem aos benjaminitas no rochedo de Rimom, propondo-lhes paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ Assim, os homens de Benjamim voltaram. Deram-lhes as mulheres que tinham mantido vivas dentre as mulheres de Jabes-Gileade, mas não encontraram mulheres suficientes para todos.

[[v7-21-15]]

^<<v7-21-15,15>>^ E o povo ficou com pena do que tinha acontecido com Benjamim, porque Jeová tinha causado uma divisão entre as tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Os anciãos da assembleia disseram: “O que é que devemos fazer para conseguir esposas para os homens que restaram, visto que todas as mulheres de Benjamim foram eliminadas?”

[[v7-21-17]]

^<<v7-21-17,17>>^ Disseram: “Os sobreviventes de Benjamim devem continuar com a sua herança, para que uma tribo não seja eliminada de Israel.

[[v7-21-18]]

^<<v7-21-18,18>>^ No entanto, não nos é permitido dar-lhes esposas dentre as nossas filhas, porque o povo de Israel jurou: ‘Maldito aquele que der uma esposa a Benjamim.’”

[[v7-21-19]]

^<<v7-21-19,19>>^ Então, disseram: “Todos os anos, há uma festividade para Jeová em Silo, que fica a norte de Betel e a leste da estrada que sobe de Betel a Siquém e a sul de Lebona.”

[[v7-21-20]]

^<<v7-21-20,20>>^ Por conseguinte, ordenaram aos homens de Benjamim: “Vão e armem uma emboscada nas vinhas.

[[v7-21-21]]

^<<v7-21-21,21>>^ Quando virem as jovens^&#42;1^ de Silo saírem para dançar numa roda, cada um de vocês deve sair das vinhas e agarrar uma para esposa dentre as jovens de Silo. Depois, devem voltar para a terra de Benjamim.

[NOTE]
====
. Lit.: “filhas”.
====

[[v7-21-22]]

^<<v7-21-22,22>>^ E, se os pais ou os irmãos delas vierem apresentar queixa contra nós, iremos dizer-lhes: ‘Mostrem-nos favor por causa deles, porque não conseguimos uma esposa para cada um deles na guerra, e vocês não lhes podiam dar uma esposa sem se tornarem culpados.’”

[[v7-21-23]]

^<<v7-21-23,23>>^ Portanto, os homens de Benjamim fizeram isso, e cada um deles tomou uma esposa dentre as mulheres que estavam a dançar. Depois, voltaram à sua herança, reconstruíram as suas cidades e estabeleceram-se nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ E os israelitas foram-se embora, cada um para a sua tribo e para a sua família; partiram, cada um para a sua herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias, não havia rei em Israel. Cada um fazia o que era certo aos seus próprios olhos.^&#42;1^

[NOTE]
====
. Ou: “o que achava ser certo”.
====

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]