include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-15-1]]

^<<v7-15-1,1>>^ Depois de algum tempo, nos dias da colheita do trigo, Sansão foi visitar a esposa, levando um cabrito. Ele disse: “Quero ficar no quarto^&#42;1^ com a minha esposa.” Contudo, o pai dela não o deixou entrar.

[NOTE]
====
. Ou: “aposento interior”.
====

[[v7-15-2]]

^<<v7-15-2,2>>^ O pai dela disse-lhe: “Pensei que a odiavas, por isso dei-a ao teu padrinho. A sua irmã mais nova, não é mais bonita do que ela? Por favor, fica antes com ela.”

[[v7-15-3]]

^<<v7-15-3,3>>^ No entanto, Sansão disse-lhes: “Desta vez os filisteus não me podem culpar por os prejudicar.”

[[v7-15-4]]

^<<v7-15-4,4>>^ Assim, Sansão apanhou 300 raposas. Depois pegou em tochas, atou as raposas de duas em duas pela cauda e colocou uma tocha no meio de cada par de caudas.

[[v7-15-5]]

^<<v7-15-5,5>>^ A seguir, pôs fogo nas tochas e soltou as raposas nos campos de cereais dos filisteus. Ele incendiou tudo, tanto os feixes como os cereais ainda não colhidos, e também as vinhas e os olivais.

[[v7-15-6]]

^<<v7-15-6,6>>^ Os filisteus perguntaram: “Quem é que fez isto?” Disseram-lhes: “Foi Sansão, o genro do timnita, porque este tomou a esposa de Sansão e deu-a ao padrinho dele.” Em vista disso, os filisteus subiram e queimaram a mulher e o seu pai com fogo.

[[v7-15-7]]

^<<v7-15-7,7>>^ E Sansão disse-lhes: “Se é assim que agem, não descansarei até me vingar de vocês.”

[[v7-15-8]]

^<<v7-15-8,8>>^ Então, golpeou-os, um após outro,^&#42;1^ com uma grande matança. Depois, desceu e ficou numa caverna^&#42;2^ do rochedo de Etão.

[NOTE]
====
. Lit.: “golpeou-os perna sobre coxa”.
. Ou: “fenda”.
====

[[v7-15-9]]

^<<v7-15-9,9>>^ Mais tarde, os filisteus subiram e acamparam em Judá, e andaram a percorrer Leí.

[[v7-15-10]]

^<<v7-15-10,10>>^ Os homens de Judá perguntaram-lhes: “Porque é que vieram contra nós?” Os filisteus responderam: “Viemos capturar^&#42;1^ Sansão, para lhe fazer o mesmo que ele nos fez.”

[NOTE]
====
. Ou: “amarrar”.
====

[[v7-15-11]]

^<<v7-15-11,11>>^ Portanto, 3000 homens de Judá desceram até à caverna^&#42;1^ do rochedo de Etão e disseram a Sansão: “Tu não sabes que os filisteus nos estão a dominar? Então porque é que nos fizeste isto?” Ele disse-lhes: “Fiz-lhes o mesmo que eles me fizeram.”

[NOTE]
====
. Ou: “fenda”.
====

[[v7-15-12]]

^<<v7-15-12,12>>^ Eles, porém, disseram-lhe: “Viemos capturar-te^&#42;1^ para te entregar aos filisteus.” Então, Sansão disse-lhes: “Jurem-me que não me atacarão.”

[NOTE]
====
. Ou: “amarrar-te”.
====

[[v7-15-13]]

^<<v7-15-13,13>>^ Eles disseram-lhe: “Não, nós apenas te amarraremos e te entregaremos a eles, mas não te mataremos.”
Por isso, amarraram-no com duas cordas novas e fizeram-no sair do rochedo.

[[v7-15-14]]

^<<v7-15-14,14>>^ Quando chegou a Leí, os filisteus gritaram triunfantemente quando o viram. E o espírito de Jeová deu-lhe poder, e as cordas que tinha nos braços tornaram-se como fios de linho chamuscados pelo fogo e caíram-lhe das mãos.

[[v7-15-15]]

^<<v7-15-15,15>>^ Ele encontrou uma queixada^&#42;1^ de jumento ainda fresca, estendeu a mão e agarrou-a, e com ela matou mil homens.

[NOTE]
====
. Isto é, um maxilar.
====

[[v7-15-16]]

^<<v7-15-16,16>>^ A seguir, Sansão disse:
“Com a queixada de um jumento — um montão, dois montões!
Com a queixada de um jumento matei mil homens.”

[[v7-15-17]]

^<<v7-15-17,17>>^ Quando acabou de falar, deitou fora a queixada e chamou àquele lugar Ramate-Leí.^&#42;1^

[NOTE]
====
. Que significa “lugar elevado da queixada”.
====

[[v7-15-18]]

^<<v7-15-18,18>>^ Depois, ficou com muita sede e clamou a Jeová, dizendo: “Foste tu que deste esta grande salvação ao teu servo. Mas será que agora morrerei de sede e cairei nas mãos dos incircuncisos?”

[[v7-15-19]]

^<<v7-15-19,19>>^ Portanto, Deus abriu uma cavidade que havia em Leí, e dela saiu água. Quando Sansão bebeu, voltaram-lhe as forças^&#42;1^ e ele reanimou-se. Foi por isso que chamou ao lugar En-Hacoré,^&#42;2^ que está em Leí até ao dia de hoje.

[NOTE]
====
. Lit.: “o seu espírito voltou”.
. Que significa “fonte daquele que invoca”.
====

[[v7-15-20]]

^<<v7-15-20,20>>^ E Sansão julgou Israel nos dias dos filisteus durante 20 anos.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]