include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-17-1]]

^<<v7-17-1,1>>^ Havia um homem da região montanhosa de Efraim chamado Mica.

[[v7-17-2]]

^<<v7-17-2,2>>^ Ele disse à sua mãe: “Tenho as 1100 peças de prata que lhe roubaram e sobre as quais a ouvi pronunciar uma maldição. Fui eu que as tirei.” Então a sua mãe disse: “Que Jeová abençoe o meu filho.”

[[v7-17-3]]

^<<v7-17-3,3>>^ Assim, ele devolveu à mãe as 1100 peças de prata, mas a mãe disse-lhe: “Sem falta, santificarei a prata para Jeová, da minha mão para o meu filho, para fazer uma imagem esculpida e uma estátua de metal.^&#42;1^ Agora devolvo-te a prata.”

[NOTE]
====
. Ou: “estátua fundida”.
====

[[v7-17-4]]

^<<v7-17-4,4>>^ Depois de ele ter devolvido a prata à mãe, ela pegou em 200 peças de prata e deu-as ao ourives. Ele fez uma imagem esculpida e uma estátua de metal,^&#42;1^ e estas foram colocadas na casa de Mica.

[NOTE]
====
. Ou: “estátua fundida”.
====

[[v7-17-5]]

^<<v7-17-5,5>>^ Este homem, Mica, tinha uma casa de deuses. Ele fez um éfode e ídolos domésticos,^&#42;1^ e designou^&#42;2^ um dos filhos para lhe servir como sacerdote.

[NOTE]
====
. Ou: “deuses domésticos”. Lit.: “terafins”.
. Lit.: “encheu a mão de”.
====

[[v7-17-6]]

^<<v7-17-6,6>>^ Naqueles dias, não havia rei em Israel. Cada um fazia o que era certo aos seus próprios olhos.^&#42;1^

[NOTE]
====
. Ou: “o que achava ser certo”.
====

[[v7-17-7]]

^<<v7-17-7,7>>^ E havia um jovem de Belém de Judá que era da família de Judá. Era um levita e já morava ali há algum tempo.

[[v7-17-8]]

^<<v7-17-8,8>>^ O jovem saiu da cidade de Belém de Judá à procura de outro lugar para morar. Durante a viagem, chegou à casa de Mica na região montanhosa de Efraim.

[[v7-17-9]]

^<<v7-17-9,9>>^ Mica perguntou-lhe: “De onde vens?” Ele respondeu: “Sou um levita de Belém de Judá, e estou à procura de um lugar para morar.”

[[v7-17-10]]

^<<v7-17-10,10>>^ Por conseguinte, Mica disse-lhe: “Fica comigo e serve-me como pai^&#42;1^ e sacerdote. Vou-te dar dez peças de prata por ano, um conjunto de vestes e comida.” Portanto, o levita entrou.

[NOTE]
====
. Ou: “conselheiro”.
====

[[v7-17-11]]

^<<v7-17-11,11>>^ Assim, o levita concordou em ficar com o homem, e o jovem tornou-se como um dos seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ Além disso, Mica designou o^&#42;1^ levita para lhe servir como sacerdote, e ele ficou a morar na casa de Mica.

[NOTE]
====
. Lit.: “encheu a mão do”.
====

[[v7-17-13]]

^<<v7-17-13,13>>^ Então, Mica disse: “Agora sei que Jeová será bom para mim, pois o levita tornou-se meu sacerdote.”

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]