include::./index.adoc[]

[[v7-3-0]]
=== Juízes, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v7-3-1]]

^<<v7-3-1,1>>^ Estas são as nações que Jeová deixou que permanecessem, para pôr à prova todos os israelitas que não tinham passado por nenhuma das guerras de Canaã

[[v7-3-2]]

^<<v7-3-2,2>>^ (para que as novas gerações dos israelitas passassem pela guerra, os que ainda não tinham passado por tais coisas):

[[v7-3-3]]

^<<v7-3-3,3>>^ os cinco governantes dos filisteus e todos os cananeus, os sidónios e os heveus que moravam nas montanhas do Líbano, desde o monte Baal-Hermom até Lebo-Hamate.^&#42;1^

[NOTE]
====
. Ou: “à entrada de Hamate”.
====

[[v7-3-4]]

^<<v7-3-4,4>>^ Eles serviram para pôr Israel à prova, para saber se Israel obedeceria aos mandamentos que Jeová tinha dado aos seus pais por meio de Moisés.

[[v7-3-5]]

^<<v7-3-5,5>>^ Assim, os israelitas moravam entre os cananeus, os hititas, os amorreus, os perizeus, os heveus e os jebuseus.

[[v7-3-6]]

^<<v7-3-6,6>>^ Eles tomavam as filhas deles como esposas e davam as suas filhas aos filhos deles, e começaram a servir os deuses deles.

[[v7-3-7]]

^<<v7-3-7,7>>^ Assim, os israelitas fizeram o que era mau aos olhos de Jeová; eles esqueceram-se de Jeová, seu Deus, e serviram os baalins e os postes sagrados.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v7-3-8]]

^<<v7-3-8,8>>^ Por isso, a ira de Jeová acendeu-se contra Israel, e ele entregou-os^&#42;1^ nas mãos de Cusã-Risataim, rei da Mesopotâmia.^&#42;2^ Os israelitas serviram Cusã-Risataim durante oito anos.

[NOTE]
====
. Lit.: “vendeu-os”.
. Lit.: “Arã-Naaraim”.
====

[[v7-3-9]]

^<<v7-3-9,9>>^ Quando os israelitas clamaram a Jeová por ajuda, Jeová enviou um salvador para livrar os israelitas: Otniel, filho de Quenaz, irmão mais novo de Caleb.

[[v7-3-10]]

^<<v7-3-10,10>>^ O espírito de Jeová veio sobre ele, e ele tornou-se o juiz de Israel. Quando ele saiu para a batalha, Jeová entregou Cusã-Risataim, rei da Mesopotâmia,^&#42;1^ nas suas mãos, de modo que ele venceu Cusã-Risataim.

[NOTE]
====
. Lit.: “de Arã”.
====

[[v7-3-11]]

^<<v7-3-11,11>>^ Depois a terra teve descanso^&#42;1^ durante 40 anos. Então, Otniel, filho de Quenaz, morreu.

[NOTE]
====
. Ou: “paz”.
====

[[v7-3-12]]

^<<v7-3-12,12>>^ E, mais uma vez, os israelitas começaram a fazer o que era mau aos olhos de Jeová. Por isso, Jeová deixou que Eglom, rei de Moabe, ficasse mais forte do que Israel, porque eles faziam o que era mau aos olhos de Jeová.

[[v7-3-13]]

^<<v7-3-13,13>>^ Além disso, trouxe contra eles os amonitas e os amalequitas. Eles atacaram Israel e tomaram a cidade das palmeiras.

[[v7-3-14]]

^<<v7-3-14,14>>^ Os israelitas serviram Eglom, rei de Moabe, durante 18 anos.

[[v7-3-15]]

^<<v7-3-15,15>>^ Então os israelitas clamaram a Jeová por ajuda, e Jeová enviou-lhes um salvador: Eúde, filho de Gera, benjaminita, que era canhoto. Com o tempo, os israelitas enviaram por meio dele um tributo^&#42;1^ a Eglom, rei de Moabe.

[NOTE]
====
. Isto é, provavelmente um tipo de pagamento de impostos.
====

[[v7-3-16]]

^<<v7-3-16,16>>^ Entretanto, Eúde fez uma espada de dois gumes, de um côvado^&#42;1^ de comprimento, e amarrou-a na coxa direita, debaixo da roupa.

[NOTE]
====
. Talvez um côvado curto, de cerca de 38 cm. Veja o Ap. B14.
====

[[v7-3-17]]

^<<v7-3-17,17>>^ Ele então apresentou o tributo^&#42;1^ a Eglom, rei de Moabe. A propósito, Eglom era um homem muito gordo.

[NOTE]
====
. Isto é, provavelmente um tipo de pagamento de impostos.
====

[[v7-3-18]]

^<<v7-3-18,18>>^ Depois de entregar o tributo,^&#42;1^ Eúde foi-se embora com os homens que tinham carregado o tributo.

[NOTE]
====
. Isto é, provavelmente um tipo de pagamento de impostos.
====

[[v7-3-19]]

^<<v7-3-19,19>>^ No entanto, quando chegou às imagens esculpidas^&#42;1^ em Gilgal, ele voltou e disse: “Tenho uma mensagem secreta para si, ó rei.” Portanto, o rei disse: “Silêncio!” Com isso, todos os seus servos se retiraram.

[NOTE]
====
. Ou, possivelmente: “às pedreiras”.
====

[[v7-3-20]]

^<<v7-3-20,20>>^ Assim, Eúde aproximou-se do rei enquanto ele estava sentado sozinho no quarto fresco do terraço. E Eúde disse: “Tenho uma mensagem de Deus para si.” Em vista disso, o rei levantou-se do seu trono.^&#42;1^

[NOTE]
====
. Ou: “assento”.
====

[[v7-3-21]]

^<<v7-3-21,21>>^ Então, Eúde, com a mão esquerda, puxou da espada que estava na coxa direita e cravou-a na barriga do rei.

[[v7-3-22]]

^<<v7-3-22,22>>^ O cabo entrou com a lâmina, e a gordura fechou-se sobre a lâmina, pois Eúde não lhe retirou a espada da barriga, e as fezes saíram.

[[v7-3-23]]

^<<v7-3-23,23>>^ Eúde saiu pela varanda,^&#42;1^ e ao sair fechou e trancou as portas do quarto do terraço.

[NOTE]
====
. Ou, possivelmente: “abertura de ventilação”.
====

[[v7-3-24]]

^<<v7-3-24,24>>^ Depois de se ter ido embora, os servos do rei regressaram e viram que as portas do quarto do terraço estavam trancadas. Então disseram: “Deve estar a fazer as suas necessidades^&#42;1^ no fresco quarto interior.”

[NOTE]
====
. Lit.: “a cobrir os seus pés”.
====

[[v7-3-25]]

^<<v7-3-25,25>>^ Esperaram até ficarem preocupados. Ao verem que ele ainda não tinha aberto as portas do quarto do terraço, pegaram na chave e abriram-nas. E viram o seu senhor caído no chão,^&#42;1^ morto!

[NOTE]
====
. Lit.: “por terra”.
====

[[v7-3-26]]

^<<v7-3-26,26>>^ Enquanto se demoravam, Eúde escapou. Ele passou pelas imagens esculpidas^&#42;1^ e chegou a salvo a Seirá.

[NOTE]
====
. Ou, possivelmente: “pelas pedreiras”.
====

[[v7-3-27]]

^<<v7-3-27,27>>^ Quando chegou, tocou a buzina na região montanhosa de Efraim; e os israelitas desceram da região montanhosa com ele à frente.

[[v7-3-28]]

^<<v7-3-28,28>>^ E ele disse-lhes: “Sigam-me, porque Jeová entregou nas vossas mãos os vossos inimigos, os moabitas.” Assim, seguiram-no e apoderaram-se dos pontos de travessia do Jordão para impedir a passagem dos moabitas e não deixaram ninguém atravessar.

[[v7-3-29]]

^<<v7-3-29,29>>^ Naquela ocasião, mataram cerca de 10 000 moabitas, todos homens fortes e valentes; não escapou nem sequer um.

[[v7-3-30]]

^<<v7-3-30,30>>^ Assim, naquele dia Moabe foi subjugado às mãos de Israel, e a terra teve descanso^&#42;1^ durante 80 anos.

[NOTE]
====
. Ou: “paz”.
====

[[v7-3-31]]

^<<v7-3-31,31>>^ Depois de Eúde, veio Sangar, filho de Anate, que matou 600 filisteus com uma aguilhada de bois; ele também salvou Israel.

'''

xref:007-juizes/007-juizes-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-juizes/007-juizes-004.adoc#v7-4-0[Próximo Capítulo &#62;]