include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v29-1-1]]

^<<v29-1-1,1>>^ Esta é a palavra de Jeová que Joel,^&#42;1^ filho de Petuel, recebeu:

[NOTE]
====
. Que significa “Jeová é Deus”.
====

[[v29-1-2]]

^<<v29-1-2,2>>^ “Ouçam isto, anciãos,
E prestem atenção, todos vocês, habitantes desta terra.^&#42;1^
Será que aconteceu algo assim nos vossos dias
Ou nos dias dos vossos antepassados?

[NOTE]
====
. Ou: “da terra”.
====

[[v29-1-3]]

^<<v29-1-3,3>>^ Contem-no aos vossos filhos,
E que os vossos filhos o contem aos seus filhos,
E os seus filhos à geração seguinte.

[[v29-1-4]]

^<<v29-1-4,4>>^ O que o gafanhoto devorador deixou sobrar, a nuvem de gafanhotos comeu;
O que a nuvem de gafanhotos deixou sobrar, o gafanhoto sem asas comeu;
E o que o gafanhoto sem asas deixou sobrar, o gafanhoto voraz comeu.

[[v29-1-5]]

^<<v29-1-5,5>>^ “Acordem, beberrões, e chorem!
Lamentem, todos vocês, bebedores de vinho,
Porque o vinho novo^&#42;1^ vos foi tirado da boca.

[NOTE]
====
. Ou: “vinho doce”.
====

[[v29-1-6]]

^<<v29-1-6,6>>^ Pois uma nação subiu à minha terra, poderosa e demasiado numerosa para ser contada.
Os seus dentes são dentes de leão, e as suas mandíbulas são as de um leão.

[[v29-1-7]]

^<<v29-1-7,7>>^ Ela devastou a minha videira e transformou a minha figueira num toco.
Desnudou-as completamente e deitou-as fora,
Deixando brancos os seus ramos novos.

[[v29-1-8]]

^<<v29-1-8,8>>^ Lamenta, assim como faz a virgem^&#42;1^ vestida de serapilheira^&#42;2^
Pela perda do noivo^&#42;3^ da sua juventude.

[NOTE]
====
. Ou: “jovem”.
. Veja o Glossário.
. Ou: “marido”.
====

[[v29-1-9]]

^<<v29-1-9,9>>^ Na casa de Jeová, acabaram-se a oferta de cereais e a oferta de bebida;
Os sacerdotes, servos de Jeová, estão de luto.

[[v29-1-10]]

^<<v29-1-10,10>>^ O campo foi devastado, o solo está de luto;
Pois o cereal foi arruinado, o vinho novo secou, o azeite acabou.

[[v29-1-11]]

^<<v29-1-11,11>>^ Os lavradores estão desalentados, os vinhateiros lamentam,
Por causa do trigo e da cevada;
Pois a colheita do campo foi arruinada.

[[v29-1-12]]

^<<v29-1-12,12>>^ A videira secou-se,
A figueira murchou.
A romãzeira, a palmeira e a macieira,
Secaram-se todas as árvores do campo;
Pois a alegria transformou-se em vergonha entre o povo.

[[v29-1-13]]

^<<v29-1-13,13>>^ “Vistam-se de serapilheira^&#42;1^ e fiquem de luto,^&#42;2^ sacerdotes.
Lamentem, servos do altar.
Entrem e passem a noite vestidos de serapilheira,^&#42;3^ servos do meu Deus;
Pois já ninguém traz ofertas de cereais e ofertas de bebida para a casa do vosso Deus.

[NOTE]
====
. Lit.: “Cinjam-se”. Veja o Glossário, “Serapilheira”.
. Ou: “batam no peito”.
. Veja o Glossário.
====

[[v29-1-14]]

^<<v29-1-14,14>>^ Proclamem^&#42;1^ um jejum; convoquem uma assembleia solene.
Reúnam os anciãos e todos os habitantes desta terra
Na casa de Jeová, vosso Deus, e clamem a Jeová por ajuda.

[NOTE]
====
. Lit.: “Santifiquem”.
====

[[v29-1-15]]

^<<v29-1-15,15>>^ Ai por causa desse dia!
Pois o dia de Jeová está próximo
E virá como destruição da parte do Todo-Poderoso!

[[v29-1-16]]

^<<v29-1-16,16>>^ Não foi o alimento tirado de diante dos nossos próprios olhos;
E a alegria e a exultação, da casa do nosso Deus?

[[v29-1-17]]

^<<v29-1-17,17>>^ As sementes^&#42;1^ murcharam sob as suas pás.
Os depósitos estão desolados.
Os celeiros foram derrubados, pois os cereais secaram-se.

[NOTE]
====
. Ou, possivelmente: “Os figos secos”.
====

[[v29-1-18]]

^<<v29-1-18,18>>^ Até o gado geme!
As manadas vagueiam em confusão, porque não têm pasto!
E os rebanhos sofrem a punição.

[[v29-1-19]]

^<<v29-1-19,19>>^ Clamarei a ti, ó Jeová;
Pois o fogo devorou as pastagens do deserto,^&#42;1^
E as chamas consumiram todas as árvores do campo.

[NOTE]
====
. Veja o Glossário.
====

[[v29-1-20]]

^<<v29-1-20,20>>^ Até os animais selvagens te anseiam,
Porque as correntes de água secaram-se,
E o fogo devorou as pastagens do deserto.”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]