include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v29-3-1]]

^<<v29-3-1,1>>^ “Vejam! Nesses dias e nesse tempo,
Quando eu trouxer os cativos para Judá e para Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ Vou reunir também todas as nações
E fazê-las descer ao vale^&#42;1^ de Jeosafá.^&#42;2^
Ali, vou entrar em juízo com elas
Em favor do meu povo e da minha herança, Israel,
Dado que elas os espalharam entre as nações,
E repartiram a minha terra entre si.

[NOTE]
====
. Ou: “à planície”.
. Que significa “Jeová é juiz”.
====

[[v29-3-3]]

^<<v29-3-3,3>>^ Lançaram sortes sobre o meu povo;
Vendiam um menino para contratar uma prostituta,
E vendiam uma menina por vinho, para beberem.

[[v29-3-4]]

^<<v29-3-4,4>>^ E vocês, o que têm contra mim,
Ó Tiro e Sídon, e todas as regiões da Filístia?
Estão a retribuir-me alguma coisa que eu fiz?
Se me estão a retribuir,
Vou trazer, veloz e rapidamente, a vossa retribuição sobre as vossas cabeças.

[[v29-3-5]]

^<<v29-3-5,5>>^ Visto que levaram a minha prata e o meu ouro,
E levaram os meus tesouros mais preciosos para os vossos templos,

[[v29-3-6]]

^<<v29-3-6,6>>^ E venderam o povo de Judá e de Jerusalém aos gregos,
A fim de os levarem para longe do seu território,

[[v29-3-7]]

^<<v29-3-7,7>>^ Vou despertá-los para que venham do lugar ao qual vocês os venderam,
E trarei a vossa retribuição sobre as vossas cabeças.

[[v29-3-8]]

^<<v29-3-8,8>>^ Vou entregar^&#42;1^ os vossos filhos e as vossas filhas nas mãos do povo de Judá,
E eles hão de entregá-los^&#42;2^ aos homens de Sabá, a uma nação distante;
Pois foi o próprio Jeová que o disse.

[NOTE]
====
. Lit.: “vender”.
. Lit.: “vendê-los”.
====

[[v29-3-9]]

^<<v29-3-9,9>>^ Proclamem isto entre as nações:
‘Preparem-se para^&#42;1^ a guerra! Despertem os poderosos!
Que todos os soldados se aproximem, que avancem!

[NOTE]
====
. Ou: “Santifiquem”.
====

[[v29-3-10]]

^<<v29-3-10,10>>^ Transformem as vossas relhas de arado em espadas e as vossas podadeiras em lanças.
Que o fraco diga: “Sou poderoso.”

[[v29-3-11]]

^<<v29-3-11,11>>^ Venham e ajudem-se umas às outras, vocês, todas as nações ao redor, reúnam-se!’”
Ó Jeová, faz com que os teus poderosos^&#42;1^ desçam até lá.

[NOTE]
====
. Ou: “guerreiros”.
====

[[v29-3-12]]

^<<v29-3-12,12>>^ “Que as nações despertem e venham ao vale^&#42;1^ de Jeosafá,
Pois ali me sentarei para julgar todas as nações ao redor.

[NOTE]
====
. Ou: “à planície”.
====

[[v29-3-13]]

^<<v29-3-13,13>>^ Metam a foice, pois a colheita está madura.
Venham e pisem, pois o lagar de vinho está cheio.
Os lagares transbordam, pois a maldade das nações é muito grande.

[[v29-3-14]]

^<<v29-3-14,14>>^ Multidões e multidões estão no vale^&#42;1^ da decisão,
Pois está próximo o dia de Jeová no vale^&#42;2^ da decisão.

[NOTE]
====
. Ou: “na planície”.
. Ou: “na planície”.
====

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua ficarão escuros,
E as estrelas perderão o brilho.

[[v29-3-16]]

^<<v29-3-16,16>>^ E Jeová rugirá de Sião,
De Jerusalém ele levantará a sua voz.
O céu e a terra tremerão;
Mas Jeová será um refúgio para o seu povo,
Uma fortaleza para o povo de Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ E vocês terão de saber que eu sou Jeová, vosso Deus, que reside em Sião, meu santo monte.
Jerusalém irá tornar-se um lugar santo,
E os estranhos^&#42;1^ não voltarão a passar por ela.

[NOTE]
====
. Ou: “estrangeiros”.
====

[[v29-3-18]]

^<<v29-3-18,18>>^ Nesse dia, os montes gotejarão vinho novo,^&#42;1^
As colinas manarão leite,
E os riachos de Judá fluirão cheios de água.
Da casa de Jeová brotará uma fonte,
Que irrigará o vale^&#42;2^ das Acácias.

[NOTE]
====
. Ou: “vinho doce”.
. Ou: “uádi”.
====

[[v29-3-19]]

^<<v29-3-19,19>>^ Contudo, o Egito ficará desolado,
E Edom irá tornar-se um deserto desolado,
Por causa da violência contra o povo de Judá,
Em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Judá, porém, será sempre habitada;
E Jerusalém, por geração após geração.

[[v29-3-21]]

^<<v29-3-21,21>>^ Vou considerar inocente o seu sangue,^&#42;1^ que eu não tinha considerado inocente;
E Jeová residirá em Sião.”

[NOTE]
====
. Ou: “a culpa de sangue”.
====

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]