include::./index.adoc[]

[[v23-1-0]]
=== Isaías, 1
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-1-1]]

^<<v23-1-1,1>>^ A visão que Isaías,^&#42;1^ filho de Amoz, teve a respeito de Judá e de Jerusalém, nos dias de Uzias, de Jotão, de Acaz e de Ezequias, reis de Judá:

[NOTE]
====
. Que significa “salvação de Jeová”.
====

[[v23-1-2]]

^<<v23-1-2,2>>^ Ouçam, ó céus, e presta atenção, ó terra,
Pois Jeová falou:
“Criei e eduquei filhos,
Mas eles revoltaram-se contra mim.

[[v23-1-3]]

^<<v23-1-3,3>>^ O touro conhece bem o seu dono,
E o jumento, a manjedoura do seu proprietário;
Mas Israel não me conhece,^&#42;1^
O meu próprio povo não se comporta com entendimento.”

[NOTE]
====
. Ou: “não conhece o seu senhor”.
====

[[v23-1-4]]

^<<v23-1-4,4>>^ Ai da nação pecadora,
Povo carregado de erro,
Descendência de malfeitores, filhos corruptos!
Abandonaram a Jeová,
Trataram o Santo de Israel com desrespeito,
Viraram-lhe as costas.

[[v23-1-5]]

^<<v23-1-5,5>>^ Onde mais serão golpeados, visto que continuam a rebelar-se?
A cabeça inteira está doente,
E o coração inteiro está enfermo.

[[v23-1-6]]

^<<v23-1-6,6>>^ Da cabeça aos pés^&#42;1^ não há nada sadio.
Há ferimentos, contusões e feridas abertas
— Não foram tratados,^&#42;2^ nem enfaixados, nem suavizados com óleo.

[NOTE]
====
. Ou: “à sola dos pés”.
. Lit.: “pressionados”.
====

[[v23-1-7]]

^<<v23-1-7,7>>^ A vossa terra está desolada.
As vossas cidades foram queimadas com fogo.
Estrangeiros devoram o vosso solo mesmo à vossa frente.
É como uma terra devastada por inimigos.

[[v23-1-8]]

^<<v23-1-8,8>>^ A filha de Sião foi deixada como um abrigo^&#42;1^ numa vinha,
Como uma cabana numa plantação de pepinos,
Como uma cidade cercada pelos inimigos.

[NOTE]
====
. Ou: “uma barraca”.
====

[[v23-1-9]]

^<<v23-1-9,9>>^ Se Jeová dos exércitos não nos tivesse deixado alguns sobreviventes,
Teríamos ficado como Sodoma,
E iríamos tornar-nos semelhantes a Gomorra.

[[v23-1-10]]

^<<v23-1-10,10>>^ Ouçam a palavra de Jeová, ditadores^&#42;1^ de Sodoma.
Prestem atenção à lei^&#42;2^ do nosso Deus, povo de Gomorra.

[NOTE]
====
. Ou: “governantes”.
. Ou: “instrução”.
====

[[v23-1-11]]

^<<v23-1-11,11>>^ “De que me servem os vossos muitos sacrifícios?”, diz Jeová.
“Estou farto das vossas ofertas queimadas de carneiros e da gordura de animais bem alimentados,
E não me agrado do sangue de novilhos, de cordeiros e de bodes.

[[v23-1-12]]

^<<v23-1-12,12>>^ Quando vêm à minha presença,
Quem é que vos pediu isso,
Que pisassem os meus pátios?

[[v23-1-13]]

^<<v23-1-13,13>>^ Parem de trazer ofertas inúteis de cereais.
O vosso incenso é detestável para mim.
Luas novas, sábados, convocação de congressos
— Não posso tolerar o uso de poder mágico juntamente com as vossas assembleias solenes.

[[v23-1-14]]

^<<v23-1-14,14>>^ Odeio^&#42;1^ as vossas luas novas e as vossas festividades.
Tornaram-se um fardo para mim;
Estou cansado de as suportar.

[NOTE]
====
. Ou: “A minha alma odeia”.
====

[[v23-1-15]]

^<<v23-1-15,15>>^ E, quando estendem as vossas mãos,
Escondo de vocês os meus olhos.
Embora façam muitas orações,
Não escuto;
As vossas mãos estão cheias de sangue.

[[v23-1-16]]

^<<v23-1-16,16>>^ Lavem-se, limpem-se,
Removam a vossa maldade da minha vista;
Parem de fazer o mal.

[[v23-1-17]]

^<<v23-1-17,17>>^ Aprendam a fazer o bem, procurem a justiça,
Corrijam o opressor,
Defendam os direitos do órfão^&#42;1^
E defendam a causa da viúva.”

[NOTE]
====
. Ou: “órfão de pai”.
====

[[v23-1-18]]

^<<v23-1-18,18>>^ “Venham, pois, e resolvamos as questões entre nós”, diz Jeová.
“Embora os vossos pecados sejam como escarlate,^&#42;1^
Serão tornados brancos como a neve;
Embora sejam vermelhos como pano carmesim,
Hão de tornar-se como a lã.

[NOTE]
====
. Veja o Glossário.
====

[[v23-1-19]]

^<<v23-1-19,19>>^ Se estiverem dispostos a escutar,
Comerão as coisas boas desta terra.

[[v23-1-20]]

^<<v23-1-20,20>>^ Caso se recusem e se rebelem,
Serão devorados pela espada,
Pois a boca de Jeová disse isso.”

[[v23-1-21]]

^<<v23-1-21,21>>^ Como a cidade fiel se tornou prostituta!
Ela estava cheia de justiça;
A retidão habitava nela,
Mas agora só há lá assassinos.

[[v23-1-22]]

^<<v23-1-22,22>>^ A tua prata tornou-se escória,
E a tua cerveja^&#42;1^ foi diluída com água.

[NOTE]
====
. Ou: “cerveja de trigo”.
====

[[v23-1-23]]

^<<v23-1-23,23>>^ Os teus príncipes são obstinados e parceiros de ladrões.
Cada um deles ama o suborno e anda atrás de presentes.
Não fazem justiça aos órfãos,
E a causa da viúva nunca chega até eles.

[[v23-1-24]]

^<<v23-1-24,24>>^ Portanto, o verdadeiro Senhor, Jeová dos exércitos,
O Poderoso de Israel, diz:
“Basta! Vou livrar-me dos meus adversários
E vou vingar-me dos meus inimigos.

[[v23-1-25]]

^<<v23-1-25,25>>^ Voltarei a minha mão contra ti,
Vou tirar a tua escória como que com barrela,^&#42;1^
E vou remover todas as tuas impurezas.

[NOTE]
====
. Ou: “potassa”.
====

[[v23-1-26]]

^<<v23-1-26,26>>^ Trarei de volta os teus juízes, como no princípio,
E os teus conselheiros, como no início.
Depois disso, serás chamada Cidade de Justiça, Cidade Fiel.

[[v23-1-27]]

^<<v23-1-27,27>>^ Sião será resgatada com justiça;
E os seus habitantes que retornam, com retidão.

[[v23-1-28]]

^<<v23-1-28,28>>^ Os rebeldes e os pecadores serão destruídos juntos,
E os que abandonam a Jeová chegarão ao seu fim.

[[v23-1-29]]

^<<v23-1-29,29>>^ Pois eles hão de ter vergonha das árvores poderosas que vocês desejaram,
E vocês ficarão envergonhados por causa dos jardins^&#42;1^ que escolheram.

[NOTE]
====
. Aparentemente árvores e jardins relacionados com a adoração idólatra.
====

[[v23-1-30]]

^<<v23-1-30,30>>^ Porque vocês se tornarão como uma árvore grande cujas folhas estão a secar,
E como um jardim sem água.

[[v23-1-31]]

^<<v23-1-31,31>>^ O homem forte irá tornar-se estopa,^&#42;1^
E as suas obras, uma faísca;
Ambos arderão juntos,
Sem ninguém para os apagar.”

[NOTE]
====
. Fibra inflamável semelhante a uma corda.
====

'''

xref:022-cantico-de-salomao/022-cantico-de-salomao-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaias/023-isaias-002.adoc#v23-2-0[Próximo Capítulo &#62;]