include::./index.adoc[]

[[v23-17-0]]
=== Isaías, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-17-1]]

^<<v23-17-1,1>>^ Proclamação contra Damasco:
“Vejam! Damasco deixará de ser cidade
E irá tornar-se um montão de ruínas.

[[v23-17-2]]

^<<v23-17-2,2>>^ As cidades de Aroer serão abandonadas;
Irão tornar-se lugares para os rebanhos se deitarem
Sem que ninguém os faça ter medo.

[[v23-17-3]]

^<<v23-17-3,3>>^ As cidades fortificadas desaparecerão de Efraim,
E o reino desaparecerá de Damasco;
E aos que restarem da Síria
Acontecerá o mesmo que aconteceu à glória dos israelitas”,^&#42;1^ diz Jeová dos exércitos.

[NOTE]
====
. Lit.: “filhos de Israel”.
====

[[v23-17-4]]

^<<v23-17-4,4>>^ “Nesse dia, a glória de Jacó diminuirá,
E o seu corpo saudável^&#42;1^ definhará.

[NOTE]
====
. Lit.: “a gordura da sua carne”.
====

[[v23-17-5]]

^<<v23-17-5,5>>^ Será como quando o ceifeiro colhe os cereais nas plantações
E o seu braço apanha as espigas,
Como quando alguém respiga os cereais no vale^&#42;1^ de Refaim.

[NOTE]
====
. Ou: “na planície”.
====

[[v23-17-6]]

^<<v23-17-6,6>>^ Só haverá sobras para recolher,
Como quando se bate a oliveira:
Ficam só duas ou três azeitonas maduras no ramo mais alto,
Só quatro ou cinco nos seus ramos produtivos”, diz Jeová, o Deus de Israel.

[[v23-17-7]]

^<<v23-17-7,7>>^ Nesse dia, o homem olhará para Aquele que o fez, e os seus olhos irão voltar-se para o Santo de Israel.

[[v23-17-8]]

^<<v23-17-8,8>>^ Não olhará para os altares, trabalho das suas mãos, e não se voltará para aquilo que os seus dedos fizeram, quer os postes sagrados,^&#42;1^ quer os altares de incenso.

[NOTE]
====
. Veja o Glossário.
====

[[v23-17-9]]

^<<v23-17-9,9>>^ Nesse dia, as suas cidades fortificadas irão tornar-se iguais a um lugar abandonado na floresta,
Como um ramo que foi abandonado diante dos israelitas;
Irá tornar-se uma desolação.

[[v23-17-10]]

^<<v23-17-10,10>>^ Pois esqueceste-te do Deus da tua salvação,
Não te lembraste da Rocha da tua fortaleza.
É por isso que cultivas belas^&#42;1^ plantações
E nelas pões o rebento de um estranho.^&#42;2^

[NOTE]
====
. Ou: “agradáveis”.
. Ou: “um deus estrangeiro”.
====

[[v23-17-11]]

^<<v23-17-11,11>>^ De dia, cercas cuidadosamente a tua plantação,
De manhã, fazes a tua semente brotar,
Mas a colheita desaparecerá no dia da doença e da dor incurável.

[[v23-17-12]]

^<<v23-17-12,12>>^ Ouçam! Há muitos povos em comoção,
Estão agitados como os mares!
Há um tumulto de nações,
O seu ruído é como o estrondo de fortes águas!

[[v23-17-13]]

^<<v23-17-13,13>>^ As nações farão um ruído como o estrondo de muitas águas.
Ele irá censurá-las, e elas fugirão para longe,
Serão espalhadas como a palha^&#42;1^ levada pelo vento nos montes,
Como plantas secas levadas^&#42;2^ pelo vendaval.

[NOTE]
====
. Ou: “pragana”.
. Ou: “Como a barrilha-espinhosa levada”.
====

[[v23-17-14]]

^<<v23-17-14,14>>^ Ao anoitecer, há um pavor;
Antes do amanhecer, elas já não existem.
Esta é a recompensa dos que nos saqueiam,
E a porção dos que levam os nossos bens.

'''

xref:023-isaias/023-isaias-016.adoc#v23-16-0[&#60; Capítulo Anterior] | <<v23-17-0,Topo>> | xref:023-isaias/023-isaias-018.adoc#v23-18-0[Próximo Capítulo &#62;]