include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-34-1]]

^<<v23-34-1,1>>^ Aproximem-se para ouvir, nações,
E prestem atenção, povos!
Escute a terra e tudo o que nela há,
O solo e tudo o que nele vive.^&#42;1^

[NOTE]
====
. Ou: “e todos os seus produtos”.
====

[[v23-34-2]]

^<<v23-34-2,2>>^ Pois Jeová está indignado com todas as nações,
E furioso contra todo o exército delas.
Irá entregá-las à destruição^&#42;1^
E levá-las ao abate.

[NOTE]
====
. Ou: “devotá-las à destruição”. Veja o Glossário.
====

[[v23-34-3]]

^<<v23-34-3,3>>^ Os seus mortos serão lançados fora,
E o mau cheiro dos seus cadáveres subirá;
Os montes ficarão encharcados^&#42;1^ do sangue deles.

[NOTE]
====
. Ou: “irão derreter-se por causa”.
====

[[v23-34-4]]

^<<v23-34-4,4>>^ Todo o exército dos céus apodrecerá,
E os céus serão enrolados como um rolo.
Todo o seu exército murchará e cairá,
Como a folha murcha cai da videira
E o figo murcho cai da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ “Pois a minha espada ficará encharcada nos céus.
Descerá sobre Edom em julgamento,
Sobre o povo que condenei à destruição.^&#42;1^

[NOTE]
====
. Ou: “devotei à destruição”. Veja o Glossário.
====

[[v23-34-6]]

^<<v23-34-6,6>>^ Jeová tem uma espada que ficará cheia de sangue.
Ficará coberta de gordura,
Do sangue de carneirinhos e de bodes,
Da gordura dos rins de carneiros.
Porque Jeová preparou um sacrifício em Bozra,
Um grande abate na terra de Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ Os touros selvagens serão abatidos com eles;
Os novilhos, com os poderosos.
A sua terra ficará encharcada de sangue,
E o pó ficará impregnado de gordura.”

[[v23-34-8]]

^<<v23-34-8,8>>^ Pois Jeová tem um dia de vingança,
Um ano de retribuição pela causa jurídica a favor de Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ As suas^&#42;1^ correntes de água irão transformar-se em piche,^&#42;2^
O seu pó em enxofre,
E a sua terra irá tornar-se como piche^&#42;3^ ardente.

[NOTE]
====
. Pelos vistos, refere-se a Bozra, capital de Edom.
. Ou: “pez”.
. Ou: “pez”.
====

[[v23-34-10]]

^<<v23-34-10,10>>^ Não se apagará nem de noite nem de dia;
O seu fumo continuará a subir para sempre.
Ela permanecerá devastada geração após geração;
Ninguém jamais passará por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ O pelicano e o porco-espinho tomarão posse dela,
E as corujas^&#42;1^ e os corvos morarão nela.
Ele estenderá sobre ela a corda de medir da destruição^&#42;2^
E o prumo^&#42;3^ da desolação.

[NOTE]
====
. Ou: “os bufos-pequenos”.
. Ou: “do vazio”.
. Lit.: “as pedras”.
====

[[v23-34-12]]

^<<v23-34-12,12>>^ Nenhum dos seus nobres se tornará rei,
E todos os seus príncipes desaparecerão.

[[v23-34-13]]

^<<v23-34-13,13>>^ Espinhos crescerão nas suas torres fortificadas;
Urtigas e plantas espinhosas nas suas fortalezas.
Ela irá tornar-se covil de chacais,
Morada de avestruzes.

[[v23-34-14]]

^<<v23-34-14,14>>^ Os animais do deserto irão encontrar-se com animais que uivam,
E os bodes selvagens^&#42;1^ chamarão os seus companheiros.
Sim, ali as aves noturnas^&#42;2^ morarão e encontrarão um lugar de descanso.

[NOTE]
====
. Ou, possivelmente: “os demónios caprinos”.
. Ou: “os noitibós”.
====

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali a cobra-cuspideira fará o seu ninho e porá ovos,
E irá chocá-los e ajuntar os filhotes sob a sua proteção.
Sim, ali se reunirão as aves de rapina,^&#42;1^ cada uma com o seu par.

[NOTE]
====
. Ou: “os milhafres”.
====

[[v23-34-16]]

^<<v23-34-16,16>>^ Procurem no livro de Jeová e leiam em voz alta:
Nenhum deles estará a faltar;
Nenhum deles ficará sem o seu par,
Pois foi a boca de Jeová que deu a ordem,
E foi o seu espírito que os reuniu.

[[v23-34-17]]

^<<v23-34-17,17>>^ Foi Ele quem lhes lançou a sorte,
E a sua própria mão mediu o lugar que lhes foi designado.^&#42;1^
Eles irão possuí-lo para sempre;
Habitarão nele por todas as gerações.

[NOTE]
====
. Lit.: “dividiu-o para eles com a corda de medir”.
====

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]