include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-48-1]]

^<<v23-48-1,1>>^ Ouçam isto, ó casa de Jacó,
Vocês que se chamam pelo nome de Israel
E que procederam das águas^&#42;1^ de Judá,
Vocês que juram pelo nome de Jeová
E invocam o Deus de Israel,
Mas não com sinceridade e retidão.

[NOTE]
====
. Ou, possivelmente: “da linhagem”.
====

[[v23-48-2]]

^<<v23-48-2,2>>^ Pois chamam-se a si mesmos pelo nome da cidade santa
E procuram o apoio do Deus de Israel,
Cujo nome é Jeová dos exércitos.

[[v23-48-3]]

^<<v23-48-3,3>>^ “Anunciei-vos há muito tempo as coisas que já aconteceram,^&#42;1^
Saíram da minha própria boca;
Eu divulguei-as.
De repente agi, e elas aconteceram.

[NOTE]
====
. Lit.: “as primeiras coisas”.
====

[[v23-48-4]]

^<<v23-48-4,4>>^ Visto que eu sabia que tu és obstinado,
Que o teu pescoço é um tendão de ferro e que a tua testa é de cobre,

[[v23-48-5]]

^<<v23-48-5,5>>^ Informei-te há muito tempo.
Antes de as coisas acontecerem, eu revelava-as,
Para que não dissesses: ‘Foi o meu ídolo que fez isto;
A minha imagem esculpida e a minha imagem de metal^&#42;1^ ordenaram estas coisas.’

[NOTE]
====
. Ou: “estátua fundida”.
====

[[v23-48-6]]

^<<v23-48-6,6>>^ Ouviste e viste tudo isto;
Não o dirás^&#42;1^ a outros?
De agora em diante anuncio-te coisas novas,
Coisas mantidas em segredo, que tu não sabias.

[NOTE]
====
. Lit.: “dirão”.
====

[[v23-48-7]]

^<<v23-48-7,7>>^ Só agora estão a ser criadas, não foram criadas há muito tempo.
Até hoje, nunca tinhas ouvido falar dessas coisas,
De modo que não podes dizer: ‘Eu já sabia disso!’

[[v23-48-8]]

^<<v23-48-8,8>>^ Não, tu não ouviste, tu não sabias,
E no passado mantiveste os ouvidos fechados.
Pois eu sei que és muito traiçoeiro,
E foste chamado transgressor desde o nascimento.

[[v23-48-9]]

^<<v23-48-9,9>>^ Mas por causa do meu nome controlarei a minha ira;
Para o meu próprio louvor irei refrear-me,
E não te eliminarei.

[[v23-48-10]]

^<<v23-48-10,10>>^ Vê! Eu refinei-te, mas não como se faz com a prata.
Provei-te^&#42;1^ na fornalha da aflição.

[NOTE]
====
. Ou: “Examinei-te”. Ou, possivelmente: “Escolhi-te”.
====

[[v23-48-11]]

^<<v23-48-11,11>>^ Por minha causa, sim, por minha própria causa agirei.
Pois como me poderia eu deixar profanar?
Não dou a minha glória a nenhum outro.^&#42;1^

[NOTE]
====
. Ou: “Não compartilho a minha glória com ninguém.”
====

[[v23-48-12]]

^<<v23-48-12,12>>^ Escuta-me, ó Jacó, e Israel, a quem chamei.
Eu sou o mesmo. Sou o primeiro e também sou o último.

[[v23-48-13]]

^<<v23-48-13,13>>^ A minha própria mão lançou o alicerce da terra,
E a minha mão direita estendeu os céus.
Quando os chamo, todos eles se apresentam.

[[v23-48-14]]

^<<v23-48-14,14>>^ Reúnam-se, todos vocês, e ouçam.
Quem dentre eles^&#42;1^ anunciou estas coisas?
Aquele a quem Jeová amou
Fará a Babilónia o que for do Seu agrado,
E o seu braço virá contra os caldeus.

[NOTE]
====
. Pelos vistos, refere-se a deuses falsos.
====

[[v23-48-15]]

^<<v23-48-15,15>>^ Eu mesmo falei, e chamei-o.
Fi-lo vir, e o seu caminho será bem-sucedido.

[[v23-48-16]]

^<<v23-48-16,16>>^ Aproximem-se e ouçam isto.
Desde o começo, nunca falei em segredo.
Eu estava presente quando as coisas aconteceram.”
E agora, o Soberano Senhor Jeová enviou-me a mim e ao^&#42;1^ seu espírito.

[NOTE]
====
. Ou: “enviou-me a mim juntamente com o”.
====

[[v23-48-17]]

^<<v23-48-17,17>>^ Assim diz Jeová, o teu Resgatador, o Santo de Israel:
“Eu, Jeová, sou o teu Deus,
Aquele que te ensina o que é melhor para ti,^&#42;1^
Aquele que te guia no caminho em que deves andar.

[NOTE]
====
. Ou: “que te ensina a tirar proveito”.
====

[[v23-48-18]]

^<<v23-48-18,18>>^ Como seria bom se prestasses atenção aos meus mandamentos!
Então, a tua paz seria como um rio,
E a tua justiça como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ A tua descendência^&#42;1^ seria como a areia;
Os teus descendentes, tão numerosos como os grãos de areia.
O nome deles jamais seria eliminado nem apagado de diante de mim.”

[NOTE]
====
. Lit.: “semente”.
====

[[v23-48-20]]

^<<v23-48-20,20>>^ Saiam de Babilónia!
Fujam dos caldeus!
Anunciem-no com gritos de alegria! Proclamem-no!
Divulguem-no até aos confins da terra.
Digam: “Jeová resgatou o seu servo Jacó.

[[v23-48-21]]

^<<v23-48-21,21>>^ Eles não passaram sede quando os conduziu através de lugares desertos.
Ele fez água sair da rocha para eles,
Partiu uma rocha e fez jorrar água.”

[[v23-48-22]]

^<<v23-48-22,22>>^ “Não há paz para os que são maus”, diz Jeová.

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]