include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz Jeová:
“Onde está o certificado de divórcio da vossa mãe, a quem mandei embora?
Ou a qual dos meus credores vos vendi?
Vejam, foram vendidos por causa dos vossos próprios erros,
E a vossa mãe foi mandada embora por causa das vossas transgressões.

[[v23-50-2]]

^<<v23-50-2,2>>^ Então, porque é que não encontrei ninguém quando vim?
Porque é que ninguém respondeu quando chamei?
É a minha mão demasiado curta para libertar,
Ou não há poder em mim para livrar?
Vejam! Com a minha censura seco o mar;
Transformo rios em deserto.
Os seus peixes apodrecem por não haver água
E morrem de sede.

[[v23-50-3]]

^<<v23-50-3,3>>^ Visto os céus de escuridão
E cubro-os com serapilheira.”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v23-50-4]]

^<<v23-50-4,4>>^ O Soberano Senhor Jeová deu-me a língua dos instruídos,^&#42;1^
Para que eu soubesse dizer ao cansado^&#42;2^ uma palavra de consolo.^&#42;3^
Ele desperta-me manhã após manhã;
Desperta o meu ouvido para ouvir como os instruídos.

[NOTE]
====
. Ou: “uma língua bem treinada”.
. Ou, possivelmente: “fortalecer o cansado com”.
. Ou: “a palavra certa”. Lit.: “uma palavra”.
====

[[v23-50-5]]

^<<v23-50-5,5>>^ O Soberano Senhor Jeová abriu-me o ouvido,
E eu não fui rebelde.
Não me virei na direção oposta.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci as minhas costas aos que me golpeavam
E o meu rosto aos que me arrancavam a barba.
Não escondi o rosto das humilhações e do cuspo.

[[v23-50-7]]

^<<v23-50-7,7>>^ Mas o Soberano Senhor Jeová irá ajudar-me.
Por isso não me sentirei humilhado.
Por isso fiz o meu rosto duro como pedra^&#42;1^
E sei que não serei envergonhado.

[NOTE]
====
. Ou: “rocha de pederneira”.
====

[[v23-50-8]]

^<<v23-50-8,8>>^ Aquele que me declara justo está perto.
Quem pode fazer acusações contra mim?^&#42;1^
Fiquemos juntos de pé.^&#42;2^
Quem tem uma causa contra mim?
Que se aproxime de mim.

[NOTE]
====
. Ou: “discutir comigo”.
. Ou: “Encaremo-nos um ao outro.”
====

[[v23-50-9]]

^<<v23-50-9,9>>^ Vejam, o Soberano Senhor Jeová irá ajudar-me.
Quem me pode declarar culpado?
Vejam, todos eles se gastarão como uma peça de roupa;
A traça irá consumi-los.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem dentre vocês teme a Jeová
E escuta a voz do Seu servo?
Quem anda em profunda escuridão, sem nenhuma claridade?
Que confie no nome de Jeová e se apoie no seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ “Quanto a vocês que acendem um fogo,
Fazendo as faíscas voarem,
Andem na luz do vosso fogo
Entre as faíscas que acenderam.
Isto é o que receberão da minha mão:
Irão deitar-se em pura dor.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]