include::./index.adoc[]

[[v23-59-0]]
=== Isaías, 59
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-59-1]]

^<<v23-59-1,1>>^ Vejam! A mão de Jeová não é demasiado curta para salvar,
Nem é o seu ouvido tão surdo^&#42;1^ que não possa ouvir.

[NOTE]
====
. Lit.: “pesado”.
====

[[v23-59-2]]

^<<v23-59-2,2>>^ Não, os vossos próprios erros separaram-vos do vosso Deus.
Os vossos pecados fizeram-no esconder a sua face de vocês,
E ele recusa-se a ouvir-vos.

[[v23-59-3]]

^<<v23-59-3,3>>^ Pois as vossas mãos estão manchadas de sangue;
E os vossos dedos, de erro.
Os vossos lábios dizem mentiras, e a vossa língua murmura injustiça.

[[v23-59-4]]

^<<v23-59-4,4>>^ Ninguém clama por justiça
E ninguém diz a verdade quando vai a tribunal.
Confiam em irrealidades^&#42;1^ e dizem coisas sem valor.
Concebem desgraça e dão à luz a maldade.

[NOTE]
====
. Ou: “no que é vão”.
====

[[v23-59-5]]

^<<v23-59-5,5>>^ Chocam ovos de uma cobra venenosa
E tecem teias de aranha.
Quem come os seus ovos morre,
E do ovo partido sai uma víbora.

[[v23-59-6]]

^<<v23-59-6,6>>^ As suas teias não servirão de roupa,
Nem se cobrirão com o que fazem.
As suas obras são más,
E praticam atos de violência com as suas mãos.

[[v23-59-7]]

^<<v23-59-7,7>>^ Os seus pés correm para fazer o mal,
E apressam-se em derramar sangue inocente.
Os seus pensamentos são pensamentos maus;
Há ruína e desgraça nos seus caminhos.

[[v23-59-8]]

^<<v23-59-8,8>>^ Não conhecem o caminho da paz
E não há justiça por onde passam.
Entortam as suas veredas;
Ninguém que andar por elas conhecerá a paz.

[[v23-59-9]]

^<<v23-59-9,9>>^ Por isso a justiça está longe de nós,
E a retidão não nos alcança.
Esperamos pela luz, mas há escuridão;
Pela claridade, mas continuamos a andar em trevas.

[[v23-59-10]]

^<<v23-59-10,10>>^ Apalpamos o muro como cegos;
Continuamos às apalpadelas como os que não têm olhos.
Tropeçamos ao meio-dia como se fosse de noite;
Somos como mortos entre os fortes.

[[v23-59-11]]

^<<v23-59-11,11>>^ Todos bramimos como ursos
E gememos como pombas.
Esperamos pela justiça, mas em vão;
Pela salvação, mas está longe de nós.

[[v23-59-12]]

^<<v23-59-12,12>>^ Pois os nossos atos de rebeldia são muitos diante de ti;
Cada um dos nossos pecados dá testemunho contra nós.
Porque conhecemos bem a nossa rebeldia;
Estamos cientes dos nossos erros.

[[v23-59-13]]

^<<v23-59-13,13>>^ Transgredimos e negámos a Jeová;
Virámos as costas ao nosso Deus.
Falámos de opressão e de revolta,
Concebemos mentiras e murmurámos falsidades procedentes do coração.

[[v23-59-14]]

^<<v23-59-14,14>>^ A justiça é obrigada a afastar-se,
E a retidão fica ao longe;
Pois a verdade^&#42;1^ tropeçou na praça,
E o que é certo não consegue entrar.

[NOTE]
====
. Ou: “honestidade”.
====

[[v23-59-15]]

^<<v23-59-15,15>>^ A verdade^&#42;1^ desapareceu,
E quem se desvia do mal é vítima de saque.
Jeová viu isto e desagradou-lhe,^&#42;2^
Pois não havia justiça.

[NOTE]
====
. Ou: “honestidade”.
. Lit.: “e era mau aos seus olhos”.
====

[[v23-59-16]]

^<<v23-59-16,16>>^ Ele viu que não havia ninguém,
Ficou espantado por ninguém interceder,
De modo que o seu próprio braço trouxe a salvação,^&#42;1^
E a sua própria justiça levou-o a agir.^&#42;2^

[NOTE]
====
. Ou: “vitória para ele”.
. Ou: “sustentou-o”.
====

[[v23-59-17]]

^<<v23-59-17,17>>^ Então, ele vestiu a justiça como se fosse uma cota de malha,
E pôs na cabeça o capacete da salvação.^&#42;1^
Colocou a roupa da vingança
E vestiu-se de zelo como se fosse uma capa.^&#42;2^

[NOTE]
====
. Ou: “vitória”.
. Ou: “túnica sem mangas”.
====

[[v23-59-18]]

^<<v23-59-18,18>>^ Há de retribuir-lhes pelo que fizeram:
Furor aos seus adversários, retribuição aos seus inimigos;
Dará às ilhas o que merecem.

[[v23-59-19]]

^<<v23-59-19,19>>^ Desde o poente o nome de Jeová será temido,
E desde o nascente a sua glória será reverenciada,
Pois ele virá como um rio impetuoso,
Que é impelido pelo espírito de Jeová.

[[v23-59-20]]

^<<v23-59-20,20>>^ “O Resgatador chegará a Sião,
Aos de Jacó que abandonam a transgressão”, diz Jeová.

[[v23-59-21]]

^<<v23-59-21,21>>^ “Este é o pacto que farei com eles”, diz Jeová. “O meu espírito, que está sobre ti, e as minhas palavras, que pus na tua boca, não se afastarão da tua boca, nem da boca dos teus filhos,^&#42;1^ nem da boca dos teus netos”,^&#42;2^ diz Jeová, “agora e para sempre”.

[NOTE]
====
. Lit.: “da tua semente”.
. Lit.: “da semente da tua semente”.
====

'''

xref:023-isaias/023-isaias-058.adoc#v23-58-0[&#60; Capítulo Anterior] | <<v23-59-0,Topo>> | xref:023-isaias/023-isaias-060.adoc#v23-60-0[Próximo Capítulo &#62;]