include::./index.adoc[]

[[v23-36-0]]
=== Isaías, 36
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-36-1]]

^<<v23-36-1,1>>^ No décimo quarto ano do rei Ezequias, Senaqueribe, rei da Assíria, veio contra todas as cidades fortificadas de Judá e conquistou-as.

[[v23-36-2]]

^<<v23-36-2,2>>^ Então, de Laquis, o rei da Assíria enviou o Rabsaqué^&#42;1^ com um grande exército ao rei Ezequias, em Jerusalém. Eles posicionaram-se junto ao aqueduto do reservatório superior, que fica na estrada do campo do lavadeiro.

[NOTE]
====
. Ou: “o chefe dos copeiros”.
====

[[v23-36-3]]

^<<v23-36-3,3>>^ Depois foram ao encontro dele Eliaquim, filho de Hilquias, que era o encarregado da casa,^&#42;1^ Sebna, o secretário, e o cronista Joá, filho de Asafe.

[NOTE]
====
. Ou: “do palácio”.
====

[[v23-36-4]]

^<<v23-36-4,4>>^ O Rabsaqué disse-lhes: “Digam a Ezequias: ‘Assim diz o grande rei, o rei da Assíria: “Em que é que se baseia a tua confiança?

[[v23-36-5]]

^<<v23-36-5,5>>^ Tu dizes: ‘Tenho uma estratégia e poder para a guerra’, mas isso não passa de palavras ocas. Em quem é que depositaste a tua confiança para teres a ousadia de te rebelares contra mim?

[[v23-36-6]]

^<<v23-36-6,6>>^ Vê, confias na ajuda daquela cana rachada, o Egito, que penetra e fura a palma da mão de quem se apoia nela. Assim é o Faraó, rei do Egito, para todos os que confiam nele.

[[v23-36-7]]

^<<v23-36-7,7>>^ E caso me digas: ‘Nós confiamos em Jeová, nosso Deus’, não são dele os altos sagrados e os altares que Ezequias removeu, dizendo a Judá e a Jerusalém: ‘É diante deste altar que se devem curvar’?”’

[[v23-36-8]]

^<<v23-36-8,8>>^ Agora, faz uma aposta com o meu senhor, o rei da Assíria: eu irei dar-te 2000 cavalos se conseguires encontrar cavaleiros suficientes para eles.

[[v23-36-9]]

^<<v23-36-9,9>>^ Então, como é que poderias repelir até mesmo um dos governadores menos destacados do meu senhor, se confias nos carros de guerra e nos cavaleiros do Egito?

[[v23-36-10]]

^<<v23-36-10,10>>^ Agora, será que foi sem a autorização de Jeová que vim contra esta terra para a destruir? O próprio Jeová me disse: ‘Vai e destrói esta terra.’”

[[v23-36-11]]

^<<v23-36-11,11>>^ Em vista disso, Eliaquim, Sebna e Joá disseram ao Rabsaqué: “Por favor, fala com os teus servos em aramaico,^&#42;1^ pois entendemos essa língua. Não fales connosco no idioma dos judeus, pois o povo que está sobre a muralha está a ouvir.”

[NOTE]
====
. Ou: “sírio”.
====

[[v23-36-12]]

^<<v23-36-12,12>>^ No entanto, o Rabsaqué disse: “Será que foi apenas ao teu senhor e a ti que o meu senhor me mandou dizer estas palavras? Não foi também aos homens que estão sentados sobre a muralha, que vão comer o seu próprio excremento e beber a sua própria urina convosco?”

[[v23-36-13]]

^<<v23-36-13,13>>^ Então, o Rabsaqué continuou de pé e disse bem alto no idioma dos judeus: “Ouçam as palavras do grande rei, o rei da Assíria.

[[v23-36-14]]

^<<v23-36-14,14>>^ Assim diz o rei: ‘Não deixem que Ezequias vos engane, porque ele não vos pode livrar.

[[v23-36-15]]

^<<v23-36-15,15>>^ E que Ezequias não vos faça confiar em Jeová, dizendo: “Jeová certamente nos livrará, e esta cidade não será entregue nas mãos do rei da Assíria.”

[[v23-36-16]]

^<<v23-36-16,16>>^ Não escutem Ezequias, pois assim diz o rei da Assíria: “Façam paz comigo e rendam-se,^&#42;1^ e cada um poderá comer da sua própria videira e da sua própria figueira, e beber água da sua própria cisterna,

[NOTE]
====
. Lit.: “Façam comigo uma bênção e venham ter comigo”.
====

[[v23-36-17]]

^<<v23-36-17,17>>^ até que eu venha e vos leve a uma terra igual à vossa, uma terra de cereais e de vinho novo, uma terra de pão e de vinhas.

[[v23-36-18]]

^<<v23-36-18,18>>^ Não deixem que Ezequias vos engane, dizendo: ‘Jeová irá livrar-nos.’ Será que algum dos deuses das nações livrou a terra delas das mãos do rei da Assíria?

[[v23-36-19]]

^<<v23-36-19,19>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim? Será que eles livraram Samaria das minhas mãos?

[[v23-36-20]]

^<<v23-36-20,20>>^ De todos os deuses destas terras, qual deles foi capaz de livrar a sua terra das minhas mãos? Então, será que Jeová livrará Jerusalém das minhas mãos?”’”

[[v23-36-21]]

^<<v23-36-21,21>>^ Contudo, eles ficaram calados e não lhe disseram uma palavra em resposta, pois a ordem do rei era: “Não lhe respondam.”

[[v23-36-22]]

^<<v23-36-22,22>>^ Por conseguinte, Eliaquim, filho de Hilquias, que era o encarregado da casa,^&#42;1^ Sebna, o secretário, e o cronista Joá, filho de Asafe, dirigiram-se a Ezequias com as suas roupas rasgadas e contaram-lhe as palavras do Rabsaqué.

[NOTE]
====
. Ou: “do palácio”.
====

'''

xref:023-isaias/023-isaias-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaias/023-isaias-037.adoc#v23-37-0[Próximo Capítulo &#62;]