include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-16-1]]

^<<v23-16-1,1>>^ Enviem um carneiro ao governante do país,
Desde Sela através do deserto,
Até ao monte da filha de Sião.

[[v23-16-2]]

^<<v23-16-2,2>>^ Como pássaros que foram espantados do seu ninho,
Assim serão as filhas de Moabe nos pontos de travessia do Arnom.

[[v23-16-3]]

^<<v23-16-3,3>>^ “Deem conselhos, executem a decisão.
Torna a tua sombra em pleno meio-dia como a noite.
Esconde os dispersos e não traias os fugitivos.

[[v23-16-4]]

^<<v23-16-4,4>>^ Que os meus dispersos residam no teu meio, ó Moabe.
Torna-te um esconderijo para eles por causa do destruidor.
O opressor chegará ao fim,
A destruição acabará,
E os que pisam os outros desaparecerão da terra.

[[v23-16-5]]

^<<v23-16-5,5>>^ “Então, há de estabelecer-se firmemente um trono em amor leal.
Aquele que se sentar nele na tenda de David será fiel;
Ele julgará com justiça, e prontamente fará o que é certo.”

[[v23-16-6]]

^<<v23-16-6,6>>^ Ouvimos falar do orgulho de Moabe — ele é muito orgulhoso.
Ouvimos falar da sua arrogância, do seu orgulho e da sua fúria,
Mas a sua conversa vã não levará a nada.

[[v23-16-7]]

^<<v23-16-7,7>>^ Por isso Moabe lamentará por Moabe;
Todos lamentarão.
Os que forem golpeados chorarão por causa dos bolos de passas de Quir-Haresete.

[[v23-16-8]]

^<<v23-16-8,8>>^ Pois os campos^&#42;1^ de Hésbon secaram,
A videira de Sibma;
Os governantes das nações esmagaram os seus ramos carregados de uvas vermelhas,^&#42;2^
Que tinham chegado até Jazer
E que se tinham estendido pelo deserto.
Os seus ramos novos tinham-se espalhado e chegado até ao mar.

[NOTE]
====
. Ou: “socalcos”.
. Ou: “seus ramos vermelho-vivo”.
====

[[v23-16-9]]

^<<v23-16-9,9>>^ É por isso que chorarei pela videira de Sibma assim como choro por Jazer.
Vou encharcar-vos com as minhas lágrimas, ó Hésbon e Eleale,
Porque os gritos de alegria por causa dos teus frutos de verão e da tua colheita cessaram.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Porque o grito de guerra veio sobre os teus frutos de verão e a tua colheita”.
====

[[v23-16-10]]

^<<v23-16-10,10>>^ A alegria e o júbilo desapareceram do pomar,
E não há canções de alegria nem exultação nas vinhas.
Já não se pisam uvas nos lagares,
Pois fiz a exultação cessar.

[[v23-16-11]]

^<<v23-16-11,11>>^ É por isso que o meu coração treme por Moabe,
Como as cordas de uma harpa;
E o meu íntimo, por Quir-Haresete.

[[v23-16-12]]

^<<v23-16-12,12>>^ Mesmo que Moabe se canse sobre o alto sagrado e entre no seu santuário para orar, não conseguirá nada.

[[v23-16-13]]

^<<v23-16-13,13>>^ Esta é a palavra que Jeová falou anteriormente a respeito de Moabe.

[[v23-16-14]]

^<<v23-16-14,14>>^ E agora Jeová diz: “Dentro de três anos, como os anos de um trabalhador contratado,^&#42;1^ a glória de Moabe será rebaixada com todo o tipo de agitação, e os que restarem serão muito poucos e insignificantes.”

[NOTE]
====
. Ou: “contados meticulosamente, como faz um trabalhador contratado”; isto é, em exatamente três anos.
====

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]