include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-21-1]]

^<<v23-21-1,1>>^ Proclamação contra o deserto do mar:^&#42;1^
Como os vendavais que varrem o sul, uma calamidade está a chegar,
Do deserto, de uma terra assustadora.

[NOTE]
====
. Aparentemente, refere-se à região da antiga Babilónia.
====

[[v23-21-2]]

^<<v23-21-2,2>>^ Foi-me revelada uma visão dura:
A nação traiçoeira age traiçoeiramente,
E a nação destruidora destrói.
Avança, ó Elão! Fecha o cerco, ó Média!
Porei fim a todos os gemidos que ela causou.

[[v23-21-3]]

^<<v23-21-3,3>>^ Por causa desta visão, estou muito angustiado.^&#42;1^
As dores apoderaram-se de mim,
Como as dores de uma mulher que está a dar à luz.
Estou demasiado aflito para ouvir;
Estou demasiado perturbado para ver.

[NOTE]
====
. Lit.: “as minhas ancas estão cheias de dor”.
====

[[v23-21-4]]

^<<v23-21-4,4>>^ O meu coração palpita; tremo de medo.
O anoitecer, que eu tanto esperava, faz-me tremer.

[[v23-21-5]]

^<<v23-21-5,5>>^ Ponham a mesa e preparem os assentos!
Comam e bebam!
Levantem-se, ó príncipes, unjam o^&#42;1^ escudo!

[NOTE]
====
. Ou: “ponham óleo no”.
====

[[v23-21-6]]

^<<v23-21-6,6>>^ Pois assim me disse Jeová:
“Vai, coloca um vigia para que informe o que vê.”

[[v23-21-7]]

^<<v23-21-7,7>>^ E ele viu um carro de guerra puxado por dois cavalos,
Um carro de guerra puxado por jumentos,
Um carro de guerra puxado por camelos.
Ele prestou atenção, muita atenção.

[[v23-21-8]]

^<<v23-21-8,8>>^ Em seguida, ele clamou como um leão:
“Ó Jeová, sobre a torre de vigia estou de pé continuamente durante o dia,
E estou no meu posto de vigilância todas as noites.

[[v23-21-9]]

^<<v23-21-9,9>>^ Vejam o que está a chegar:
Homens num carro de guerra puxado por dois cavalos!”
Então ele disse:
“Ela caiu! Babilónia caiu!
Todas as imagens esculpidas dos seus deuses estão despedaçadas no chão!”

[[v23-21-10]]

^<<v23-21-10,10>>^ Ó meu povo, que foste debulhado,
Produto^&#42;1^ da minha eira,
Comuniquei-vos o que ouvi da parte de Jeová dos exércitos, o Deus de Israel.

[NOTE]
====
. Lit.: “Filho”.
====

[[v23-21-11]]

^<<v23-21-11,11>>^ Proclamação contra Dumá:^&#42;1^
Alguém me grita desde Seir:
“Vigia, como está a noite?
Vigia, como está a noite?”

[NOTE]
====
. Que significa “silêncio”.
====

[[v23-21-12]]

^<<v23-21-12,12>>^ O vigia diz:
“A manhã está a chegar, e a noite também.
Se quiserem perguntar, perguntem.
Venham outra vez!”

[[v23-21-13]]

^<<v23-21-13,13>>^ Proclamação contra a planície desértica:
Passarão a noite num bosque na planície desértica,
Ó caravanas de Dedã.

[[v23-21-14]]

^<<v23-21-14,14>>^ Ó habitantes da terra de Tema,
Levem água aos sedentos,
E levem pão àqueles que fogem.

[[v23-21-15]]

^<<v23-21-15,15>>^ Pois fugiram da espada, da espada desembainhada,
Do arco pronto para atirar, e da crueldade da guerra.

[[v23-21-16]]

^<<v23-21-16,16>>^ Pois assim me disse Jeová: “Daqui a um ano, como os anos de um trabalhador contratado,^&#42;1^ toda a glória de Quedar chegará ao fim.

[NOTE]
====
. Ou: “contado meticulosamente, como faz um trabalhador contratado”; isto é, em exatamente um ano.
====

[[v23-21-17]]

^<<v23-21-17,17>>^ Os arqueiros que restarem dentre os guerreiros de Quedar serão poucos, pois Jeová, o Deus de Israel, é que falou.”

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]