include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-63-1]]

^<<v23-63-1,1>>^ Quem é este que está a chegar de Edom,
De Bozra, com roupas de cores vivas?^&#42;1^
Quem é este com vestes esplêndidas,
Que marcha com grande poder?
“Sou eu, Aquele que diz o que é justo,
Aquele que tem grande poder para salvar.”

[NOTE]
====
. Ou, possivelmente: “roupas vermelho-vivo”.
====

[[v23-63-2]]

^<<v23-63-2,2>>^ Porque é que a tua roupa está vermelha
E porque é que as tuas vestes estão como as de alguém que pisa o lagar de vinho?

[[v23-63-3]]

^<<v23-63-3,3>>^ “Pisei sozinho o lagar;
Ninguém dentre os povos estava comigo.
Continuei a pisá-los na minha ira
E a esmagá-los no meu furor.
As minhas vestes ficaram salpicadas do sangue deles,
E manchei toda a minha roupa.

[[v23-63-4]]

^<<v23-63-4,4>>^ Porque o dia de vingança está no meu coração,
E chegou o ano de resgatar o meu povo.^&#42;1^

[NOTE]
====
. Ou: “o ano dos meus resgatados”.
====

[[v23-63-5]]

^<<v23-63-5,5>>^ Olhei, mas não havia quem me ajudasse;
Fiquei espantado, pois ninguém me ofereceu apoio.
Portanto, o meu braço trouxe-me a salvação,^&#42;1^
E o meu próprio furor me levou a agir.^&#42;2^

[NOTE]
====
. Ou: “trouxe-me a vitória”.
. Ou: “me sustentou”.
====

[[v23-63-6]]

^<<v23-63-6,6>>^ Esmaguei povos na minha ira;
Fi-los ficarem embriagados com o meu furor
E derramei o seu sangue no chão.”

[[v23-63-7]]

^<<v23-63-7,7>>^ Mencionarei os atos de amor leal de Jeová,
Os atos louváveis de Jeová,
Por causa de tudo o que Jeová fez por nós,
As muitas coisas boas que ele fez para a casa de Israel,
Segundo a sua misericórdia e o seu grande amor leal.

[[v23-63-8]]

^<<v23-63-8,8>>^ Pois ele disse: “Certamente, eles são o meu povo, filhos que não serão desleais.”^&#42;1^
Assim, tornou-se o Salvador deles.

[NOTE]
====
. Ou: “não se mostrarão falsos”.
====

[[v23-63-9]]

^<<v23-63-9,9>>^ Durante toda a aflição deles, ele também ficou aflito.
E o seu mensageiro pessoal^&#42;1^ salvou-os.
Por amor e compaixão, resgatou-os;
E levantou-os e carregou-os todos os dias do passado.

[NOTE]
====
. Ou: “o anjo da sua presença”.
====

[[v23-63-10]]

^<<v23-63-10,10>>^ Mas eles rebelaram-se e entristeceram o seu espírito santo.
Por isso ele transformou-se em inimigo deles
E lutou contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ Então, lembraram-se dos tempos antigos,
Dos dias de Moisés, Seu servo, e perguntaram:
“Onde está Aquele que os fez subir do mar com os pastores do seu rebanho?
Onde está Aquele que pôs nele o Seu espírito santo,

[[v23-63-12]]

^<<v23-63-12,12>>^ Aquele que fez o Seu glorioso braço ir à direita de Moisés,
Aquele que dividiu as águas diante deles
Para fazer para si um nome eterno?

[[v23-63-13]]

^<<v23-63-13,13>>^ Onde está Aquele que os fez andar através de águas turbulentas,^&#42;1^
De modo que andaram sem tropeçar,
Como um cavalo em campo aberto?^&#42;2^

[NOTE]
====
. Ou: “águas profundas”.
. Ou: “no deserto”.
====

[[v23-63-14]]

^<<v23-63-14,14>>^ O espírito de Jeová fê-los descansar,
Assim como quando o rebanho desce até ao vale.”^&#42;1^
Foi assim que conduziste o teu povo,
Para fazeres um nome majestoso^&#42;2^ para ti.

[NOTE]
====
. Lit.: “à planície de vale”.
. Ou: “belo”.
====

[[v23-63-15]]

^<<v23-63-15,15>>^ Olha para baixo desde o céu e vê
Da tua elevada morada, santa e gloriosa.^&#42;1^
Onde estão o teu zelo e o teu poder,
A tua profunda compaixão^&#42;2^ e a tua misericórdia?
Tu retiveste-os de mim.

[NOTE]
====
. Ou: “bela”.
. Lit.: “A agitação das tuas partes internas”.
====

[[v23-63-16]]

^<<v23-63-16,16>>^ Pois tu és o nosso Pai;
Ainda que Abraão não nos conheça
E Israel não nos reconheça,
Tu, ó Jeová, és o nosso Pai.
O teu nome é Nosso Resgatador desde os tempos antigos.

[[v23-63-17]]

^<<v23-63-17,17>>^ Ó Jeová, porque nos deixas^&#42;1^ desviar dos teus caminhos?
Porque deixas^&#42;2^ endurecer o nosso coração para não te temermos?
Volta por causa dos teus servos,
As tribos da tua herança.

[NOTE]
====
. Ou: “nos fazes”.
. Lit.: “fazes”.
====

[[v23-63-18]]

^<<v23-63-18,18>>^ O teu povo santo possuiu a terra por pouco tempo.
Os nossos adversários espezinharam o teu santuário.

[[v23-63-19]]

^<<v23-63-19,19>>^ Por muito tempo tornámo-nos como aqueles que nunca governaste,
Como aqueles que nunca foram chamados pelo teu nome.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]