include::./index.adoc[]

[[v23-44-0]]
=== Isaías, 44
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-44-1]]

^<<v23-44-1,1>>^ “Agora escuta, ó Jacó, meu servo,
E tu, ó Israel, a quem escolhi.

[[v23-44-2]]

^<<v23-44-2,2>>^ Assim diz Jeová,
Aquele que te fez e aquele que te formou,
Que te tem ajudado desde o ventre:^&#42;1^
‘Não tenhas medo, meu servo Jacó,
E tu, Jesurum,^&#42;2^ a quem escolhi.

[NOTE]
====
. Ou: “desde o nascimento”.
. Que significa “aquele que é reto”; título honorífico de Israel.
====

[[v23-44-3]]

^<<v23-44-3,3>>^ Pois derramarei água sobre o sedento^&#42;1^
E farei correr ribeiros sobre a terra seca.
Derramarei o meu espírito sobre a tua descendência^&#42;2^
E a minha bênção sobre os teus descendentes.

[NOTE]
====
. Ou: “a terra sedenta”.
. Lit.: “semente”.
====

[[v23-44-4]]

^<<v23-44-4,4>>^ E eles brotarão como plantas no meio da erva,
Como os choupos junto às correntes de água.

[[v23-44-5]]

^<<v23-44-5,5>>^ Um dirá: “Pertenço a Jeová.”
Outro irá chamar-se a si mesmo pelo nome de Jacó,
E ainda outro escreverá na mão: “Pertencente a Jeová”,
E adotará o nome de Israel.’

[[v23-44-6]]

^<<v23-44-6,6>>^ Assim diz Jeová,
O Rei de Israel e o seu Resgatador, Jeová dos exércitos:
‘Sou o primeiro e sou o último;
Além de mim não há Deus.

[[v23-44-7]]

^<<v23-44-7,7>>^ Quem é semelhante a mim?
Que erga a voz, que o diga e me apresente as provas!
Que diga as coisas que estão para vir
E o que ainda acontecerá,
Assim como tenho feito desde o tempo em que estabeleci o povo antigo.

[[v23-44-8]]

^<<v23-44-8,8>>^ Não fiquem apavorados
Nem fiquem paralisados de medo.
Não vos contei e anunciei isso antecipadamente?
Vocês são as minhas testemunhas.
Existe outro Deus além de mim?
Não, não há nenhuma outra Rocha; não conheço nenhuma.’”

[[v23-44-9]]

^<<v23-44-9,9>>^ Todos os fabricantes de imagens esculpidas não são nada,
E os seus objetos que tanto amam não serão de nenhum proveito.
Como suas testemunhas, elas^&#42;1^ não veem nada nem sabem nada.
Por isso, os que as fizeram serão envergonhados.

[NOTE]
====
. Isto é, as imagens.
====

[[v23-44-10]]

^<<v23-44-10,10>>^ Quem é que faria um deus ou uma imagem de metal^&#42;1^
Que não pode trazer nenhum proveito?

[NOTE]
====
. Ou: “estátua fundida”.
====

[[v23-44-11]]

^<<v23-44-11,11>>^ Vejam! Todos os seus companheiros serão envergonhados.
Os artesãos são apenas humanos.
Que todos se reúnam e se posicionem.
Eles ficarão apavorados e serão envergonhados juntos.

[[v23-44-12]]

^<<v23-44-12,12>>^ O ferreiro trabalha o metal nas brasas com a sua ferramenta.^&#42;1^
Modela-o com o martelo,
Trabalha-o com o seu braço forte.
Então, fica com fome e sem forças;
Por não beber água, fica cansado.

[NOTE]
====
. Ou: “o seu podão”.
====

[[v23-44-13]]

^<<v23-44-13,13>>^ O escultor de madeira estica a corda de medir e faz na madeira um esboço com giz vermelho.
Trabalha-a com o formão e marca-a com o compasso.
Modela-a na forma de um homem,
Na bela figura de um humano,
Para que fique numa casa.^&#42;1^

[NOTE]
====
. Ou: “num santuário”.
====

[[v23-44-14]]

^<<v23-44-14,14>>^ Há um outro que corta cedros.
Ele escolhe um certo tipo de árvore, um carvalho,
E cuida dela para que fique forte entre as árvores da floresta.
Ou planta um loureiro, e as chuvas fazem-no crescer.

[[v23-44-15]]

^<<v23-44-15,15>>^ Então, alguém usa a madeira como combustível para fazer lume.
Pega em parte dela para se aquecer;
Acende uma fogueira e coze pão.
E também faz um deus e adora-o.
Transforma-a numa imagem esculpida e curva-se diante dela.

[[v23-44-16]]

^<<v23-44-16,16>>^ Metade queima no fogo;
Com essa metade assa a carne, come e fica satisfeito.
Também se aquece e diz:
“Ah! Estou a aquecer-me enquanto olho para o fogo.”

[[v23-44-17]]

^<<v23-44-17,17>>^ Mas o resto ele transforma num deus, numa imagem esculpida.
Curva-se diante dele e adora-o.
Ora a ele e diz:
“Salva-me, pois tu és o meu deus.”

[[v23-44-18]]

^<<v23-44-18,18>>^ Eles não sabem nada, não entendem nada,
Porque os seus olhos estão tapados e não podem ver,
E o seu coração não tem perspicácia.

[[v23-44-19]]

^<<v23-44-19,19>>^ Ninguém reflete,
Nem tem conhecimento nem entendimento para dizer:
“Metade da madeira queimei no fogo,
Nas suas brasas cozi pão e assei carne para comer.
Será que devo transformar o que sobrou numa coisa detestável?
Devo adorar um pedaço^&#42;1^ de madeira tirado de uma árvore?”

[NOTE]
====
. Ou: “um pedaço seco”.
====

[[v23-44-20]]

^<<v23-44-20,20>>^ Tal homem alimenta-se de cinzas.
O seu coração foi enganado e desencaminhou-o.
Ele não se consegue salvar a si mesmo,^&#42;1^ nem dizer:
“Não é uma mentira o que tenho na mão direita?”

[NOTE]
====
. Ou: “salvar a sua alma”.
====

[[v23-44-21]]

^<<v23-44-21,21>>^ “Lembra-te destas coisas, ó Jacó, e tu, ó Israel,
Pois tu és o meu servo.
Eu formei-te, e tu és o meu servo.
Ó Israel, não me esquecerei de ti.

[[v23-44-22]]

^<<v23-44-22,22>>^ Apagarei as tuas transgressões como que com uma nuvem,
E os teus pecados como que com uma densa nuvem.
Volta para mim, e vou resgatar-te.

[[v23-44-23]]

^<<v23-44-23,23>>^ Gritem de alegria, ó céus,
Pois Jeová agiu!
Gritem triunfantemente, profundezas da terra!
Gritem de alegria, ó montes,
Ó floresta e todas as tuas árvores!
Porque Jeová resgatou Jacó
E demonstra o seu esplendor em Israel.”

[[v23-44-24]]

^<<v23-44-24,24>>^ Assim diz Jeová, o teu Resgatador,
Que te formou desde o ventre:
“Eu sou Jeová, aquele que fez tudo.
Sozinho estendi os céus,
E estirei a terra.
Quem estava comigo?

[[v23-44-25]]

^<<v23-44-25,25>>^ Frustro os sinais dos falsos profetas^&#42;1^
E sou aquele que faz os adivinhos agirem como tolos;
Sou aquele que confunde os sábios
E transforma o seu conhecimento em tolice;

[NOTE]
====
. Ou: “daqueles que falam o que é vão”.
====

[[v23-44-26]]

^<<v23-44-26,26>>^ Aquele que faz a palavra do seu servo tornar-se realidade,
E que cumpre todas as predições dos seus mensageiros;
Aquele que diz a respeito de Jerusalém: ‘Ela será habitada’,
E das cidades de Judá: ‘Elas serão reconstruídas,
E eu vou restaurar as suas ruínas’;

[[v23-44-27]]

^<<v23-44-27,27>>^ Aquele que diz às águas profundas: ‘Evaporem-se!
Secarei todos os teus rios’;

[[v23-44-28]]

^<<v23-44-28,28>>^ Aquele que diz a respeito de Ciro: ‘Ele é o meu pastor
E realizará tudo o que for da minha vontade’;
Aquele que diz a respeito de Jerusalém: ‘Ela será reconstruída’,
E do templo: ‘O teu alicerce será lançado.’”

'''

xref:023-isaias/023-isaias-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaias/023-isaias-045.adoc#v23-45-0[Próximo Capítulo &#62;]