include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-23-1]]

^<<v23-23-1,1>>^ Proclamação contra Tiro:
Lamentem, navios de Társis!
Pois o porto foi destruído; não é possível lá entrar.
Isto foi-lhes revelado na terra de Quitim.

[[v23-23-2]]

^<<v23-23-2,2>>^ Fiquem sem palavras, ó habitantes do litoral.
Os mercadores de Sídon, que cruzam o mar, enriqueceram-vos.

[[v23-23-3]]

^<<v23-23-3,3>>^ Os cereais^&#42;1^ de Sior^&#42;2^ e a colheita do Nilo
— Os seus rendimentos^&#42;3^ — iam sobre muitas águas,
E traziam o lucro das nações.

[NOTE]
====
. Lit.: “A semente”.
. Isto é, um braço do rio Nilo.
. Isto é, de Tiro.
====

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonha-te, ó Sídon, fortaleza do mar,
Porque o mar disse:
“Não tive dores de parto nem dei à luz,
Não criei filhos nem eduquei filhas.”^&#42;1^

[NOTE]
====
. Lit.: “virgens”.
====

[[v23-23-5]]

^<<v23-23-5,5>>^ Assim como quando ouviram a notícia a respeito do Egito,
As pessoas ficarão aflitas com a notícia acerca de Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Atravessem o mar e vão para Társis!
Lamentem, ó habitantes do litoral!

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta a vossa cidade que estava cheia de alegria desde o passado remoto, desde os tempos antigos?
Os seus pés levavam-na para terras distantes, para ali se estabelecer.

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem é que determinou isto contra Tiro,
Aquela que distribuía coroas,
Cujos mercadores eram príncipes,
Cujos comerciantes eram honrados em toda a terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O próprio Jeová dos exércitos determinou isso,
Para profanar o orgulho que ela tinha por causa de toda a sua beleza,
Para humilhar todos os que eram honrados em toda a terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Atravessa a tua terra como o rio Nilo, ó filha de Társis.
Já não há nenhum estaleiro.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “porto”.
====

[[v23-23-11]]

^<<v23-23-11,11>>^ Ele estendeu a mão sobre o mar;
Fez tremer reinos.
Jeová ordenou que as fortalezas da Fenícia fossem destruídas.

[[v23-23-12]]

^<<v23-23-12,12>>^ E diz: “Tu não te alegrarás mais,
Ó oprimida filha virgem de Sídon.
Levanta-te, atravessa o mar e vai para Quitim.
Nem ali terás descanso.”

[[v23-23-13]]

^<<v23-23-13,13>>^ Vejam, a terra dos caldeus!
Foi este povo, não a Assíria,
Que a transformou num lugar para os animais do deserto.
Ergueram torres de cerco,
Esvaziaram as suas torres fortificadas
E reduziram-na a ruínas.

[[v23-23-14]]

^<<v23-23-14,14>>^ Lamentem, navios de Társis,
Pois a vossa fortaleza foi destruída.

[[v23-23-15]]

^<<v23-23-15,15>>^ Nesse dia, Tiro ficará esquecida durante 70 anos, o tempo de vida^&#42;1^ de um só rei. Ao fim de 70 anos acontecerá a Tiro o que diz a canção de uma prostituta:

[NOTE]
====
. Lit.: “os dias”.
====

[[v23-23-16]]

^<<v23-23-16,16>>^ “Pega numa harpa, percorre a cidade, ó prostituta esquecida!
Toca bem a tua harpa;
Canta muitas canções,
Para que se lembrem de ti.”

[[v23-23-17]]

^<<v23-23-17,17>>^ Ao fim de 70 anos, Jeová voltará a sua atenção para Tiro, e ela voltará à sua atividade,^&#42;1^ prostituindo-se com todos os reinos do mundo que há na face da terra.

[NOTE]
====
. Ou: “renda”.
====

[[v23-23-18]]

^<<v23-23-18,18>>^ Mas o seu lucro e os seus rendimentos irão tornar-se algo sagrado para Jeová. Não serão acumulados, nem serão guardados, porque os seus rendimentos irão para os que moram diante de Jeová, para comerem até ficarem satisfeitos e para se vestirem com roupas elegantes.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]