include::./index.adoc[]

[[v23-60-0]]
=== Isaías, 60
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-60-1]]

^<<v23-60-1,1>>^ “Levanta-te, ó mulher, deixa brilhar a tua luz, pois a tua luz chegou,
A glória de Jeová brilha sobre ti.

[[v23-60-2]]

^<<v23-60-2,2>>^ Olha! A escuridão cobrirá a terra,
E densas trevas, as nações;
Mas Jeová brilhará sobre ti,
E sobre ti a sua glória há de ser vista.

[[v23-60-3]]

^<<v23-60-3,3>>^ Nações virão à tua luz
E reis ao brilho do teu esplendor.^&#42;1^

[NOTE]
====
. Ou: “amanhecer”.
====

[[v23-60-4]]

^<<v23-60-4,4>>^ Levanta os olhos e olha à tua volta!
Todos eles foram reunidos, estão a vir ao teu encontro.
De longe os teus filhos estão a chegar,
E as tuas filhas são trazidas ao colo.^&#42;1^

[NOTE]
====
. Ou: “sobre a anca”.
====

[[v23-60-5]]

^<<v23-60-5,5>>^ Nesse tempo, verás e ficarás radiante,
O teu coração palpitará e transbordará de alegria,
Porque as riquezas do mar te serão trazidas,
Os recursos das nações chegarão a ti.

[[v23-60-6]]

^<<v23-60-6,6>>^ Multidões de camelos cobrirão a tua terra,^&#42;1^
Os camelos novos de Midiã e de Efá.
Todos os de Sabá chegarão,
Trarão ouro e olíbano.
Proclamarão os louvores de Jeová.

[NOTE]
====
. Lit.: “cobrir-te-ão”.
====

[[v23-60-7]]

^<<v23-60-7,7>>^ Todos os rebanhos de Quedar serão reunidos a ti.
Os carneiros de Nebaiote irão servir-te.
Serão oferecidos no meu altar e serão aceites,
E vou embelezar a minha casa gloriosa.^&#42;1^

[NOTE]
====
. Ou: “casa de beleza”.
====

[[v23-60-8]]

^<<v23-60-8,8>>^ Quem são estes que voam como nuvens,
Como pombas para o seu pombal?^&#42;1^

[NOTE]
====
. Ou: “para as aberturas do pombal”.
====

[[v23-60-9]]

^<<v23-60-9,9>>^ Em mim as ilhas terão esperança;
Os navios de Társis vêm à frente,^&#42;1^
Trazendo os teus filhos de longe,
Com a sua prata e o seu ouro,
Para o nome de Jeová, teu Deus, para o Santo de Israel,
Porque ele te glorificará.^&#42;2^

[NOTE]
====
. Ou: “vêm como no começo”.
. Ou: “embelezará”.
====

[[v23-60-10]]

^<<v23-60-10,10>>^ Estrangeiros construirão as tuas muralhas,
E os reis deles irão servir-te;
Pois na minha indignação golpeei-te,
Mas na minha boa vontade^&#42;1^ terei misericórdia de ti.

[NOTE]
====
. Ou: “no meu favor”.
====

[[v23-60-11]]

^<<v23-60-11,11>>^ Os teus portões ficarão sempre abertos,
Não serão fechados nem de dia nem de noite,
Para que entrem os recursos das nações;
E os seus reis estarão na liderança.

[[v23-60-12]]

^<<v23-60-12,12>>^ Porque a nação e o reino que não te servirem serão destruídos,
E as nações serão totalmente devastadas.

[[v23-60-13]]

^<<v23-60-13,13>>^ A glória do Líbano chegará a ti;
Juntos virão o junípero, o freixo e o cipreste,
A fim de embelezar o lugar do meu santuário;
E eu glorificarei o lugar para os meus pés.

[[v23-60-14]]

^<<v23-60-14,14>>^ Os filhos dos que te oprimiram virão e hão de curvar-se diante de ti;
Todos os que te tratam com desrespeito irão dobrar-se aos teus pés
E terão de te chamar cidade de Jeová,
Sião do Santo de Israel.

[[v23-60-15]]

^<<v23-60-15,15>>^ Em vez de estares abandonada e odiada, sem ninguém passar por ti,
Farei de ti um motivo de orgulho para sempre,
Um motivo de alegria por todas as gerações.

[[v23-60-16]]

^<<v23-60-16,16>>^ Beberás o leite das nações,
Mamarás aos peitos dos reis;
E certamente saberás que eu, Jeová, sou o teu Salvador,
E que o Poderoso de Jacó é o teu Resgatador.

[[v23-60-17]]

^<<v23-60-17,17>>^ Em vez do cobre trarei ouro,
E em vez do ferro trarei prata,
Em vez da madeira, cobre,
E em vez das pedras, ferro.
Vou designar a paz como teus superintendentes
E a justiça como teus supervisores.

[[v23-60-18]]

^<<v23-60-18,18>>^ Nunca mais se ouvirá falar de violência na tua terra,
Nem de destruição e ruína dentro dos limites do teu território.
E chamarás às tuas muralhas Salvação e aos teus portões Louvor.

[[v23-60-19]]

^<<v23-60-19,19>>^ O sol já não será para ti a luz do dia,
Nem o brilho da lua te iluminará,
Pois Jeová irá tornar-se para ti uma luz eterna,
E o teu Deus será a tua glória.^&#42;1^

[NOTE]
====
. Ou: “beleza”.
====

[[v23-60-20]]

^<<v23-60-20,20>>^ Nunca mais se porá o teu sol,
Nem a tua lua vai minguar,
Pois o próprio Jeová se tornará para ti uma luz eterna,
E os dias do teu luto terão acabado.

[[v23-60-21]]

^<<v23-60-21,21>>^ E todo o teu povo será justo;
Possuirão esta terra para sempre.
São o rebento que eu plantei,
O trabalho das minhas mãos, para eu ser embelezado.

[[v23-60-22]]

^<<v23-60-22,22>>^ O pequeno irá tornar-se mil;
E o menor, uma nação forte.
Eu, Jeová, apressarei isso no tempo devido.”

'''

xref:023-isaias/023-isaias-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaias/023-isaias-061.adoc#v23-61-0[Próximo Capítulo &#62;]