include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-27-1]]

^<<v23-27-1,1>>^ Nesse dia, Jeová, com a sua espada implacável, grande e forte,
Voltará a atenção para o Leviatã,^&#42;1^ a serpente que desliza,
Para o Leviatã, a serpente sinuosa,
E matará o monstro que está no mar.

[NOTE]
====
. Veja o Glossário.
====

[[v23-27-2]]

^<<v23-27-2,2>>^ Nesse dia, cantem para ela:^&#42;1^
“Uma vinha que produz vinho!^&#42;2^

[NOTE]
====
. Aparentemente, refere-se à nação de Israel, personificada aqui como uma mulher e comparada a uma vinha.
. Ou: “vinho espumante”, isto é, vinho em fermentação.
====

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu, Jeová, cuido dela.
Rego-a a todo instante.
Protejo-a dia e noite,
Para que ninguém lhe faça dano.

[[v23-27-4]]

^<<v23-27-4,4>>^ Já não estou furioso.
Quem me enfrentará com espinheiros e com ervas daninhas na batalha?
Vou pisá-los e queimá-los juntos.

[[v23-27-5]]

^<<v23-27-5,5>>^ Em vez disso, que recorra à minha fortaleza.
Que faça paz comigo;
Faça ele paz comigo.”

[[v23-27-6]]

^<<v23-27-6,6>>^ Nos dias que virão, Jacó lançará raízes,
Israel brotará e florescerá,
E eles encherão a terra de frutos.

[[v23-27-7]]

^<<v23-27-7,7>>^ Terá ele de ser golpeado com o golpe de quem o golpeia?
Ou terá ele de ser morto com a matança dos seus mortos?

[[v23-27-8]]

^<<v23-27-8,8>>^ Entrarás em juízo contra esta nação e irás mandá-la embora com um grito assustador.
Ele irá expulsá-la com o seu sopro violento no dia do vento leste.

[[v23-27-9]]

^<<v23-27-9,9>>^ Portanto, assim se expiará o erro de Jacó,
E este será o resultado^&#42;1^ quando o seu pecado for removido:
Ele fará com que todas as pedras do altar
Fiquem como pedras de cal que foram pulverizadas,
E não restará nenhum poste sagrado^&#42;2^ nem altar de incenso.

[NOTE]
====
. Ou: “o pleno fruto”.
. Veja o Glossário.
====

[[v23-27-10]]

^<<v23-27-10,10>>^ Porque a cidade fortificada ficará vazia;
A pastagem ficará esquecida e abandonada como um deserto.
Ali o bezerro pastará e irá deitar-se,
E comerá os seus ramos.

[[v23-27-11]]

^<<v23-27-11,11>>^ Quando os seus raminhos tiverem secado,
Virão mulheres e irão parti-los,
E farão fogueiras com eles.
Pois este povo não tem entendimento.
É por isso que Aquele que os fez não terá misericórdia deles,
E Aquele que os formou não lhes mostrará favor.

[[v23-27-12]]

^<<v23-27-12,12>>^ Nesse dia, Jeová baterá para derrubar os frutos, desde as correntes do rio Eufrates^&#42;1^ até à torrente^&#42;2^ do Egito, e vocês serão ajuntados um após outro, ó povo de Israel.

[NOTE]
====
. Lit.: “do Rio”.
. Ou: “ao uádi”. Veja o Glossário.
====

[[v23-27-13]]

^<<v23-27-13,13>>^ Nesse dia, irá tocar-se uma grande buzina, e os que estiverem a definhar na terra da Assíria e os que estiverem espalhados na terra do Egito virão e hão de curvar-se diante de Jeová no monte santo em Jerusalém.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]