include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-19-1]]

^<<v23-19-1,1>>^ Proclamação contra o Egito:
Vejam! Jeová está a cavalgar numa nuvem veloz e está a entrar no Egito.
Os deuses do Egito, que não valem nada, tremerão diante dele,
E o coração dos egípcios irá derreter-se no seu íntimo.

[[v23-19-2]]

^<<v23-19-2,2>>^ “Vou instigar egípcios contra egípcios,
E lutarão uns contra os outros,
Cada um contra o seu irmão e contra o seu vizinho,
Cidade contra cidade, reino contra reino.

[[v23-19-3]]

^<<v23-19-3,3>>^ O Egito^&#42;1^ ficará desnorteado no seu íntimo,
E confundirei os seus planos.
Recorrerão aos deuses que não valem nada,
Aos encantadores, aos que invocam espíritos e aos adivinhos.

[NOTE]
====
. Lit.: “O espírito do Egito”.
====

[[v23-19-4]]

^<<v23-19-4,4>>^ Vou entregar o Egito a um senhor cruel,
E um rei impiedoso dominará sobre eles”, diz o verdadeiro Senhor, Jeová dos exércitos.

[[v23-19-5]]

^<<v23-19-5,5>>^ A água do mar secará,
E o rio ficará árido e seco.

[[v23-19-6]]

^<<v23-19-6,6>>^ Os rios vão cheirar mal;
Os canais do Nilo do Egito ficarão rasos e áridos.
As canas e os juncos murcharão.

[[v23-19-7]]

^<<v23-19-7,7>>^ As plantas ao longo do rio Nilo, na foz do rio,
E toda a terra semeada ao longo do Nilo irão secar-se.
Tudo será levado pelo vento, e não existirá mais.

[[v23-19-8]]

^<<v23-19-8,8>>^ E os pescadores ficarão de luto,
Os que lançam anzóis no Nilo lamentarão,
E os que estendem as suas redes nas águas irão tornar-se poucos.

[[v23-19-9]]

^<<v23-19-9,9>>^ Os que trabalham com linho cardado
E os que tecem panos brancos serão envergonhados.

[[v23-19-10]]

^<<v23-19-10,10>>^ Os seus tecelões ficarão arrasados;
Todos os trabalhadores contratados ficarão aflitos.^&#42;1^

[NOTE]
====
. Ou: “ficarão aflitos na alma”.
====

[[v23-19-11]]

^<<v23-19-11,11>>^ Os príncipes de Zoã são tolos.
Os conselheiros mais sábios do Faraó dão conselhos insensatos.
Como é que vocês podem dizer ao Faraó:
“Sou descendente de sábios,
Descendente de antigos reis”?

[[v23-19-12]]

^<<v23-19-12,12>>^ Então, onde estão os teus sábios?
Caso eles saibam, que te digam o que Jeová dos exércitos decidiu a respeito do Egito.

[[v23-19-13]]

^<<v23-19-13,13>>^ Os príncipes de Zoã agiram tolamente;
Os príncipes de Nofe^&#42;1^ foram enganados;
Os chefes das suas tribos desencaminharam o Egito.

[NOTE]
====
. Ou: “Mênfis”.
====

[[v23-19-14]]

^<<v23-19-14,14>>^ Jeová derramou no Egito um espírito de confusão;
E os seus líderes desencaminham o Egito em tudo o que ele faz,
Assim como um bêbado cambaleia sobre o seu vómito.

[[v23-19-15]]

^<<v23-19-15,15>>^ E não haverá nada que o Egito possa fazer,
Quer a cabeça quer a cauda, o rebento ou o junco.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “o ramo de palmeira ou a cana”.
====

[[v23-19-16]]

^<<v23-19-16,16>>^ Nesse dia, os egípcios irão tornar-se como mulheres, tremerão e ficarão apavorados por causa da mão ameaçadora que Jeová dos exércitos levanta contra eles.

[[v23-19-17]]

^<<v23-19-17,17>>^ E a terra de Judá irá tornar-se motivo de terror para o Egito. Ao ouvirem falar dela, os egípcios ficarão apavorados por causa do que Jeová dos exércitos decidiu contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Nesse dia, haverá cinco cidades na terra do Egito, que falarão o idioma de Canaã e jurarão lealdade a Jeová dos exércitos. Uma das cidades irá chamar-se Cidade de Derrubamento.

[[v23-19-19]]

^<<v23-19-19,19>>^ Nesse dia, haverá um altar a Jeová no meio da terra do Egito, e uma coluna a Jeová no limite do seu território.

[[v23-19-20]]

^<<v23-19-20,20>>^ Servirá como sinal e como testemunho a respeito de Jeová dos exércitos na terra do Egito; pois clamarão a Jeová por causa dos opressores, e ele irá enviar-lhes um grandioso salvador, que os salvará.

[[v23-19-21]]

^<<v23-19-21,21>>^ E Jeová irá tornar-se conhecido dos egípcios, e os egípcios conhecerão a Jeová nesse dia; eles oferecerão sacrifícios e dádivas, farão um voto a Jeová e irão cumpri-lo.

[[v23-19-22]]

^<<v23-19-22,22>>^ Jeová golpeará o Egito, irá golpeá-lo e curá-lo; e os egípcios voltarão para Jeová, e ele atenderá às suas súplicas e irá curá-los.

[[v23-19-23]]

^<<v23-19-23,23>>^ Nesse dia, haverá uma estrada que sairá do Egito para a Assíria. Então, os assírios irão até ao Egito, e os egípcios irão até à Assíria; e os egípcios servirão a Deus com os assírios.

[[v23-19-24]]

^<<v23-19-24,24>>^ Nesse dia, Israel será o terceiro, juntamente com o Egito e com a Assíria, uma bênção no meio da terra,

[[v23-19-25]]

^<<v23-19-25,25>>^ porque Jeová dos exércitos o terá abençoado, dizendo: “Bendito seja o meu povo, o Egito, e o trabalho das minhas mãos, a Assíria, e a minha herança, Israel.”

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]