include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-35-1]]

^<<v23-35-1,1>>^ O ermo e a terra árida irão alegrar-se,
A planície desértica exultará e dará flores assim como o açafrão.^&#42;1^

[NOTE]
====
. Ou: “croco”.
====

[[v23-35-2]]

^<<v23-35-2,2>>^ Sem falta dará flores;
Exultará e gritará de alegria.
A glória do Líbano ser-lhe-á dada,
Também o esplendor do Carmelo e de Sarom.
As pessoas verão a glória de Jeová, o esplendor do nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortaleçam as mãos fracas
E firmem os joelhos trémulos.

[[v23-35-4]]

^<<v23-35-4,4>>^ Digam aos de coração ansioso:
“Sejam fortes. Não tenham medo.
Vejam! O vosso Deus virá com vingança,
Deus virá com retribuição.
Virá e irá salvar-vos.”

[[v23-35-5]]

^<<v23-35-5,5>>^ Nesse tempo, irão abrir-se os olhos dos cegos
E destapar-se os ouvidos dos surdos.

[[v23-35-6]]

^<<v23-35-6,6>>^ Nesse tempo, os coxos saltarão como os veados,
E a língua dos mudos gritará de alegria.
Pois águas vão jorrar no ermo,
E torrentes na planície desértica.

[[v23-35-7]]

^<<v23-35-7,7>>^ O solo seco há de tornar-se uma lagoa repleta de juncos;
E a terra sedenta, fontes de água.
Nos covis onde descansavam os chacais
Haverá vegetação verde, juncos e papiro.

[[v23-35-8]]

^<<v23-35-8,8>>^ E ali haverá uma estrada,
Sim, um caminho chamado Caminho de Santidade.
O impuro não passará por ele.
Será apenas para aquele que anda no caminho;
Nenhum tolo vagueará nele.

[[v23-35-9]]

^<<v23-35-9,9>>^ Ali não haverá leões,
E nenhum animal feroz passará por ele.
Não serão vistos ali;
Apenas os resgatados andarão nele.

[[v23-35-10]]

^<<v23-35-10,10>>^ Os remidos por Jeová retornarão e chegarão a Sião com gritos de alegria.
Serão coroados com alegria eterna.
Ficarão cheios de exultação e alegria,
O pesar e o gemido desaparecerão.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]