include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-26-1]]

^<<v23-26-1,1>>^ Nesse dia, irá cantar-se o seguinte cântico na terra de Judá:
“Temos uma cidade forte.
Ele estabelece a salvação como muralhas e escarpas.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abram os portões, para que entre a nação justa,
Uma nação que mantém uma conduta fiel.

[[v23-26-3]]

^<<v23-26-3,3>>^ Protegerás os que confiam plenamente em ti;^&#42;1^
Irás dar-lhes contínua paz,
Porque é em ti que confiam.

[NOTE]
====
. Ou, possivelmente: “os cuja disposição é inabalável”.
====

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiem em Jeová para sempre,
Pois Jah^&#42;1^ Jeová é a Rocha eterna.

[NOTE]
====
. “Jah” é uma forma reduzida do nome Jeová.
====

[[v23-26-5]]

^<<v23-26-5,5>>^ Pois ele humilhou os que moravam nas alturas, na cidade elevada.
Ele rebaixa-a,
Rebaixa-a até à terra;
Lança-a no pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ Ela será pisada
Pelos pés dos pobres, pelos passos dos de condição humilde.”

[[v23-26-7]]

^<<v23-26-7,7>>^ O caminho do justo é reto.^&#42;1^
Visto que tu és reto,
Tornarás plano o caminho do justo.

[NOTE]
====
. Ou: “plano”.
====

[[v23-26-8]]

^<<v23-26-8,8>>^ Ao seguirmos o caminho da tua justiça,^&#42;1^ ó Jeová,
A nossa esperança está em ti.
Ansiamos^&#42;2^ pelo teu nome e pela tua lembrança.^&#42;3^

[NOTE]
====
. Ou: “dos teus julgamentos”.
. Ou: “Com a nossa alma ansiamos”.
. Isto é, que Deus e o seu nome sejam lembrados, divulgados.
====

[[v23-26-9]]

^<<v23-26-9,9>>^ À noite, anseio por ti de todo o meu coração,^&#42;1^
Sim, o meu espírito continua a procurar-te;
Pois, quando julgas a terra,
Os seus habitantes aprendem a justiça.

[NOTE]
====
. Ou: “com a minha alma”.
====

[[v23-26-10]]

^<<v23-26-10,10>>^ Mesmo que se mostre favor ao mau,
Ele não aprenderá a justiça.
Mesmo na terra da retidão^&#42;1^ ele fará o que é mau,
E não verá a glória de Jeová.

[NOTE]
====
. Ou: “do que é direito”.
====

[[v23-26-11]]

^<<v23-26-11,11>>^ Ó Jeová, a tua mão está levantada, mas eles não a veem.
Verão o teu zelo pelo teu povo, e serão envergonhados.
Sim, o fogo reservado para os teus adversários irá consumi-los.

[[v23-26-12]]

^<<v23-26-12,12>>^ Ó Jeová, tu irás dar-nos a paz,
Porque és tu quem realizas
Tudo o que fazemos.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó Jeová, nosso Deus, outros senhores além de ti governaram sobre nós,
Mas louvamos apenas o teu nome.

[[v23-26-14]]

^<<v23-26-14,14>>^ Eles estão mortos; não viverão.
Impotentes na morte, não se levantarão.
Pois voltaste a tua atenção para eles,
A fim de os exterminares e apagares qualquer lembrança deles.

[[v23-26-15]]

^<<v23-26-15,15>>^ Aumentaste a nação, ó Jeová,
Aumentaste a nação;
Glorificaste-te.
Estendeste amplamente todos os limites desta terra.

[[v23-26-16]]

^<<v23-26-16,16>>^ Ó Jeová, durante a aflição, recorreram a ti;
Derramaram a sua oração num sussurro quando os disciplinaste.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como uma mulher grávida que sente dores de parto
E grita de dor quando está prestes a dar à luz,
Assim é a nossa situação por tua causa, ó Jeová.

[[v23-26-18]]

^<<v23-26-18,18>>^ Engravidámos, tivemos dores de parto,
Mas é como se tivéssemos dado à luz o vento.
Não trouxemos salvação para esta terra,
E não nasce ninguém para habitar nela.

[[v23-26-19]]

^<<v23-26-19,19>>^ “Os teus mortos viverão.
Os cadáveres do meu povo irão levantar-se.^&#42;1^
Acordem e gritem de alegria,
Os que residem no pó!
Pois o teu orvalho é como o orvalho da manhã,^&#42;2^
E a terra deixará que os impotentes na morte voltem a viver.^&#42;3^

[NOTE]
====
. Lit.: “Um cadáver meu — eles levantar-se-ão.”
. Ou, possivelmente: “orvalho das ervas (malvas)”.
. Ou: “dará à luz os impotentes na morte”.
====

[[v23-26-20]]

^<<v23-26-20,20>>^ Vai, povo meu, entra nos teus quartos^&#42;1^
E fecha as portas atrás de ti.
Esconde-te por um instante,
Até que passe o furor.^&#42;2^

[NOTE]
====
. Ou: “aposentos internos”.
. Ou: “a indignação”.
====

[[v23-26-21]]

^<<v23-26-21,21>>^ Pois vejam! Jeová está a sair do seu lugar
Para ajustar contas com os habitantes desta terra por causa do seu erro,
E esta terra exporá o seu derramamento de sangue
E não encobrirá mais os seus mortos.”

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]