include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai dos que fazem leis prejudiciais,
Que elaboram sempre decretos opressivos,

[[v23-10-2]]

^<<v23-10-2,2>>^ Para negar aos pobres os seus direitos,
Para privar da justiça os de condição humilde do meu povo,
Tirando os bens às viúvas
E saqueando os órfãos!^&#42;1^

[NOTE]
====
. Ou: “órfãos de pai”.
====

[[v23-10-3]]

^<<v23-10-3,3>>^ O que é que vocês farão no dia do ajuste de contas,^&#42;1^
Quando a destruição vier de longe?
A quem recorrerão em busca de ajuda
E onde deixarão as vossas riquezas?^&#42;2^

[NOTE]
====
. Ou: “da punição”.
. Ou: “a vossa glória”.
====

[[v23-10-4]]

^<<v23-10-4,4>>^ Só vos restará curvar-se entre os presos
Ou cair entre os mortos.
Em vista de tudo isto, a Sua ira não recuou,
A sua mão ainda está estendida para golpear.

[[v23-10-5]]

^<<v23-10-5,5>>^ “Ah! O assírio,
A vara para expressar a minha ira;
E o bastão na sua mão para expressar a minha fúria!^&#42;1^

[NOTE]
====
. Ou: “condenação”.
====

[[v23-10-6]]

^<<v23-10-6,6>>^ Irei enviá-lo contra uma nação apóstata,
Contra o povo que me enfureceu;
Irei dar-lhe a ordem de recolher muito despojo e fazer um grande saque,
E de os calcar como lama nas ruas.

[[v23-10-7]]

^<<v23-10-7,7>>^ Mas ele não terá essa intenção,
E o seu coração não tramará isso;
Porque tem no coração aniquilar,
Destruir muitas nações, não poucas.

[[v23-10-8]]

^<<v23-10-8,8>>^ Pois ele diz:
‘Não são reis todos os meus príncipes?

[[v23-10-9]]

^<<v23-10-9,9>>^ Não é Calno como Carquemis?
Não é Hamate como Arpade?
Não é Samaria como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ A minha mão apoderou-se dos reinos dos deuses que não valem nada,
Cujas imagens esculpidas eram mais numerosas do que as de Jerusalém e de Samaria!

[[v23-10-11]]

^<<v23-10-11,11>>^ Não farei também a Jerusalém e aos seus ídolos
Assim como fiz a Samaria e aos seus deuses que não valem nada?’

[[v23-10-12]]

^<<v23-10-12,12>>^ “Quando Jeová acabar todo o seu trabalho no monte Sião e em Jerusalém, Ele punirá^&#42;1^ o rei da Assíria por causa do seu coração insolente e do seu olhar orgulhoso e arrogante.

[NOTE]
====
. Lit.: “Eu punirei”.
====

[[v23-10-13]]

^<<v23-10-13,13>>^ Pois ele diz:
‘Irei fazê-lo com a força da minha mão
E com a minha sabedoria, pois sou sábio.
Eliminarei os limites dos territórios dos povos
E saquearei os seus tesouros,
E subjugarei os habitantes como um poderoso.

[[v23-10-14]]

^<<v23-10-14,14>>^ Como um homem que alcança um ninho,
A minha mão vai apoderar-se dos recursos dos povos;
E como alguém que junta ovos abandonados,
Vou juntar toda a terra!
Ninguém baterá as asas, nem abrirá a boca, nem dará um pio.’”

[[v23-10-15]]

^<<v23-10-15,15>>^ Será que o machado se eleva acima daquele que corta com ele?
Será que a serra se eleva acima daquele que serra com ela?
Pode uma vara mover aquele que a ergue?
Ou pode um bastão erguer aquele que não é feito de madeira?

[[v23-10-16]]

^<<v23-10-16,16>>^ Por isso, o verdadeiro Senhor, Jeová dos exércitos,
Fará os seus^&#42;1^ homens fortes ficarem fracos,
E sob a sua glória acenderá um fogo ardente.

[NOTE]
====
. Isto é, do “assírio” mencionado nos vv. 5 e 24.
====

[[v23-10-17]]

^<<v23-10-17,17>>^ A Luz de Israel irá tornar-se um fogo,
E o seu Santo uma chama;
E num só dia queimará e consumirá as suas^&#42;1^ ervas daninhas e os seus espinhos.

[NOTE]
====
. Isto é, do “assírio” mencionado nos vv. 5 e 24.
====

[[v23-10-18]]

^<<v23-10-18,18>>^ Acabará totalmente^&#42;1^ com a glória da sua^&#42;2^ floresta e do seu pomar;
Será como quando um doente definha.

[NOTE]
====
. Ou: “da alma até à carne”.
. Isto é, do “assírio” mencionado nos vv. 5 e 24.
====

[[v23-10-19]]

^<<v23-10-19,19>>^ As árvores que restarem da sua floresta
Serão tão poucas que um menino as poderá contar.

[[v23-10-20]]

^<<v23-10-20,20>>^ Nesse dia, os que restarem de Israel
E os sobreviventes da casa de Jacó
Não se apoiarão mais naquele que os golpeava,
Mas irão apoiar-se em Jeová,
O Santo de Israel, com fidelidade.

[[v23-10-21]]

^<<v23-10-21,21>>^ Apenas um restante voltará,
O restante de Jacó, para o Deus Poderoso.

[[v23-10-22]]

^<<v23-10-22,22>>^ Pois embora o teu povo, ó Israel,
Seja como os grãos de areia do mar,
Apenas um restante retornará.
Foi decretado um extermínio,
E a justiça^&#42;1^ irá engoli-los como uma enchente.

[NOTE]
====
. Ou: “punição”.
====

[[v23-10-23]]

^<<v23-10-23,23>>^ Sim, o extermínio decretado pelo Soberano Senhor, Jeová dos exércitos,
Será executado em toda esta terra.

[[v23-10-24]]

^<<v23-10-24,24>>^ Portanto, assim diz o Soberano Senhor, Jeová dos exércitos: “Não tenhas medo, povo meu, que moras em Sião, por causa do assírio que te golpeava com a vara e levantava o bastão contra ti, assim como fazia o Egito.

[[v23-10-25]]

^<<v23-10-25,25>>^ Pois dentro de pouco tempo a minha fúria^&#42;1^ chegará ao fim; a minha ira vai voltar-se contra eles para os destruir.

[NOTE]
====
. Ou: “condenação”.
====

[[v23-10-26]]

^<<v23-10-26,26>>^ Jeová dos exércitos irá castigá-lo com um chicote, como quando ele derrotou Midiã junto à rocha de Orebe. E o seu bastão estará sobre o mar, e ele irá erguê-lo assim como fez no caso do Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ Nesse dia o fardo dele será removido de cima dos teus ombros;^&#42;1^
E o jugo dele, de cima do teu pescoço;
E o jugo será quebrado por causa do óleo.”

[NOTE]
====
. Isto é, dos ombros do povo de Deus.
====

[[v23-10-28]]

^<<v23-10-28,28>>^ Ele chegou a Aiate,
Passou por Migrom,
Deixou a sua bagagem em Micmás.

[[v23-10-29]]

^<<v23-10-29,29>>^ Atravessaram o rio,
Passaram a noite em Geba;
Ramá tremeu, Gibeá de Saul fugiu.

[[v23-10-30]]

^<<v23-10-30,30>>^ Grita estridentemente, ó filha de Galim!
Presta atenção, ó Laísa!
Ó pobre Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Madmena fugiu.
Os habitantes de Gebim procuraram abrigo.

[[v23-10-32]]

^<<v23-10-32,32>>^ Nesse mesmo dia, ele parará em Nobe.
Ele sacode o punho contra o monte da filha de Sião,
A colina de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Vejam! O verdadeiro Senhor, Jeová dos exércitos,
Está a cortar ramos com um estrondo terrível;
As árvores mais altas estão a ser derrubadas,
E as elevadas são rebaixadas.

[[v23-10-34]]

^<<v23-10-34,34>>^ Ele derruba as moitas da floresta com um instrumento de ferro,^&#42;1^
E o Líbano cairá por meio de um poderoso.

[NOTE]
====
. Ou: “um machado”.
====

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]