include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-46-1]]

^<<v23-46-1,1>>^ Bel curva-se, Nebo dobra-se por terra.
As suas imagens são colocadas sobre animais, animais de carga,
Como bagagem que sobrecarrega animais cansados.

[[v23-46-2]]

^<<v23-46-2,2>>^ Juntos, dobram-se por terra e curvam-se;
São incapazes de salvar as cargas,^&#42;1^
E eles mesmos^&#42;2^ vão para o cativeiro.

[NOTE]
====
. Isto é, as imagens colocadas sobre os animais.
. Ou: “as suas almas”.
====

[[v23-46-3]]

^<<v23-46-3,3>>^ “Escuta-me, ó casa de Jacó, e todos os que restam da casa de Israel,
Vocês, a quem sustento desde que nasceram e a quem carrego desde o ventre.

[[v23-46-4]]

^<<v23-46-4,4>>^ Até à vossa velhice, eu serei o mesmo;
Até os vossos cabelos ficarem brancos, continuarei a sustentar-vos.
Assim como tenho feito, irei carregar-vos, sustentar-vos e salvar-vos.

[[v23-46-5]]

^<<v23-46-5,5>>^ A quem é que me vão comparar ou igualar?
Com quem é que me vão assemelhar, como se fôssemos parecidos?

[[v23-46-6]]

^<<v23-46-6,6>>^ Há os que despejam o ouro da sua bolsa;
Pesam a prata na balança.
Contratam um ourives para transformar isso num deus.
Depois, prostram-se e adoram-no.^&#42;1^

[NOTE]
====
. Lit.: “e curvam-se diante dele”.
====

[[v23-46-7]]

^<<v23-46-7,7>>^ Colocam-no aos ombros,
Carregam-no e põem-no no seu lugar, e ali fica.
Não sai do lugar.
Clamam a ele, mas ele não responde;
Não pode salvar ninguém da aflição.

[[v23-46-8]]

^<<v23-46-8,8>>^ Lembrem-se disto e tenham coragem.
Prestem atenção, transgressores.

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrem-se das coisas anteriores,^&#42;1^ que aconteceram há muito tempo,
Que eu sou Deus,^&#42;2^ e não há outro.
Eu sou Deus, e não há ninguém igual a mim.

[NOTE]
====
. Lit.: “primeiras coisas”.
. Ou: “o Divino”.
====

[[v23-46-10]]

^<<v23-46-10,10>>^ Desde o princípio anuncio o final,
E desde os tempos antigos as coisas que ainda não foram feitas.
Digo: ‘A minha decisão^&#42;1^ ficará de pé
E farei tudo o que for do meu agrado.’

[NOTE]
====
. Ou: “O meu propósito; O meu conselho”.
====

[[v23-46-11]]

^<<v23-46-11,11>>^ Desde o nascente^&#42;1^ chamo a ave de rapina,
De uma terra distante, o homem para executar o que decidi.^&#42;2^
Eu falei e realizarei.
Estabeleci o meu propósito e irei cumpri-lo.

[NOTE]
====
. Ou: “leste”.
. Ou: “o meu propósito; o meu conselho”.
====

[[v23-46-12]]

^<<v23-46-12,12>>^ Escutem-me, obstinados^&#42;1^ de coração,
Vocês que estão longe da justiça.

[NOTE]
====
. Lit.: “poderosos”.
====

[[v23-46-13]]

^<<v23-46-13,13>>^ Faço a minha justiça aproximar-se;
Ela não está longe,
E a minha salvação não tardará.
Darei salvação em Sião, o meu esplendor a Israel.”

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]