include::./index.adoc[]

[[v23-47-0]]
=== Isaías, 47
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-47-1]]

^<<v23-47-1,1>>^ Desce e senta-te no pó,
Ó virgem filha de Babilónia.
Senta-te no chão, onde não há nenhum trono,
Ó filha dos caldeus,
Pois as pessoas nunca mais te chamarão delicada e mimada.

[[v23-47-2]]

^<<v23-47-2,2>>^ Pega num moinho manual e mói farinha.
Remove o véu
E tira a saia; descobre as pernas
E atravessa os rios.

[[v23-47-3]]

^<<v23-47-3,3>>^ A tua nudez será exposta.
A tua vergonha será revelada.
Irei vingar-me, e ninguém me impedirá.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “e não me encontrarei bondosamente com ninguém”.
====

[[v23-47-4]]

^<<v23-47-4,4>>^ “O nosso Resgatador,
Cujo nome é Jeová dos exércitos,
É o Santo de Israel.”

[[v23-47-5]]

^<<v23-47-5,5>>^ Senta-te em silêncio, entra na escuridão,
Ó filha dos caldeus;
Nunca mais serás chamada Senhora^&#42;1^ de Reinos.

[NOTE]
====
. Ou: “Rainha”.
====

[[v23-47-6]]

^<<v23-47-6,6>>^ Fiquei indignado com o meu povo.
Profanei a minha herança
E entreguei-os nas tuas mãos.
Mas tu não tiveste misericórdia deles.
Colocaste um jugo pesado até mesmo sobre os idosos.

[[v23-47-7]]

^<<v23-47-7,7>>^ Disseste: “Serei sempre a Senhora,^&#42;1^ eternamente.”
Não deste atenção a estas coisas,
Nem pensaste em como tudo ia acabar.

[NOTE]
====
. Ou: “Rainha”.
====

[[v23-47-8]]

^<<v23-47-8,8>>^ Agora ouve isto, tu que amas os prazeres,
Que estás sentada em segurança, que dizes no coração:
“Eu sou a mais importante, não há ninguém igual a mim.
Não ficarei viúva;
Nunca perderei os meus filhos.”

[[v23-47-9]]

^<<v23-47-9,9>>^ Mas estas duas coisas vão sobrevir-te de repente, num só dia:
A perda de filhos e a viuvez.
Virão sobre ti em plena medida,
Por causa^&#42;1^ das tuas muitas feitiçarias e de todos os teus poderosos encantamentos.

[NOTE]
====
. Ou, possivelmente: “Apesar”.
====

[[v23-47-10]]

^<<v23-47-10,10>>^ Confiaste na tua maldade,
E disseste: “Ninguém me vê.”
A tua sabedoria e o teu conhecimento desencaminharam-te,
E dizes no coração: “Eu sou a mais importante, não há ninguém igual a mim.”

[[v23-47-11]]

^<<v23-47-11,11>>^ Mas serás atingida por uma calamidade
Que nenhum dos teus feitiços poderá impedir.^&#42;1^
Irá acontecer-te uma desgraça; e não a poderás evitar.
Virá sobre ti, repentinamente, uma ruína como nunca viste.

[NOTE]
====
. Ou: “E tu não saberás como a afastar com um feitiço”.
====

[[v23-47-12]]

^<<v23-47-12,12>>^ Continua, então, com os teus encantamentos e com as tuas muitas feitiçarias,
Nas quais te tens empenhado desde a juventude.
Talvez te sejam de proveito;
Talvez consigas impressionar as pessoas.

[[v23-47-13]]

^<<v23-47-13,13>>^ Cansaste-te da multidão dos teus conselheiros.
Que agora se ponham de pé e te salvem,
Os que adoram os céus,^&#42;1^ que observam as estrelas,
Os que fazem predições nas luas novas
A respeito das coisas que virão sobre ti.

[NOTE]
====
. Ou, possivelmente: “Os que dividem os céus; Os astrólogos”.
====

[[v23-47-14]]

^<<v23-47-14,14>>^ Vê! Eles são como a palha.
O fogo vai consumi-los.
Não se podem salvar a si mesmos^&#42;1^ do poder das chamas.
Eles não são brasas para se aquecerem
Nem fogo para se sentarem diante dele.

[NOTE]
====
. Ou: “podem salvar a sua alma”.
====

[[v23-47-15]]

^<<v23-47-15,15>>^ Assim se tornarão para ti os teus encantadores,
Aqueles com quem tens trabalhado arduamente desde a tua juventude.
Eles vaguearão, indo cada um numa direção.^&#42;1^
Não haverá quem te salve.

[NOTE]
====
. Lit.: “para a sua própria região”.
====

'''

xref:023-isaias/023-isaias-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaias/023-isaias-048.adoc#v23-48-0[Próximo Capítulo &#62;]