include::./index.adoc[]

[[v23-41-0]]
=== Isaías, 41
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-41-1]]

^<<v23-41-1,1>>^ “Escutem-me em silêncio,^&#42;1^ ó ilhas;
Que as nações renovem as suas forças.
Que se aproximem e então falem.
Vamos reunir-nos para o julgamento.

[NOTE]
====
. Ou: “Fiquem em silêncio diante de mim”.
====

[[v23-41-2]]

^<<v23-41-2,2>>^ Quem é que fez surgir alguém do nascente,^&#42;1^
Chamando-o em justiça aos Seus pés,^&#42;2^
Para lhe entregar nações
E para o fazer subjugar reis?
Quem é que os reduz a pó diante da sua espada
E os dispersa como palha diante do seu arco?

[NOTE]
====
. Ou: “do leste”.
. Isto é, para O servir.
====

[[v23-41-3]]

^<<v23-41-3,3>>^ Ele persegue-os, avançando sem impedimento
Por caminhos pelos quais os seus pés nunca passaram.

[[v23-41-4]]

^<<v23-41-4,4>>^ Quem é que agiu e fez isso,
Convocando as gerações desde o princípio?
Eu, Jeová, sou o Primeiro,
E sou o mesmo com os últimos.”

[[v23-41-5]]

^<<v23-41-5,5>>^ As ilhas viram isso e ficaram com medo.
Os confins da terra começaram a tremer.
Eles juntam-se e avançam.

[[v23-41-6]]

^<<v23-41-6,6>>^ Cada um ajuda o seu companheiro
E diz ao seu irmão: “Sê forte.”

[[v23-41-7]]

^<<v23-41-7,7>>^ Assim, o artesão incentiva o ourives;
Aquele que alisa com o martelo^&#42;1^
Incentiva o que bate na bigorna.
Ele diz a respeito da soldadura: “Está boa.”
E alguém o^&#42;2^ fixa com pregos para não cair.

[NOTE]
====
. Ou: “malho”.
. Isto é, o ídolo.
====

[[v23-41-8]]

^<<v23-41-8,8>>^ “Mas tu, ó Israel, és meu servo;
Tu, ó Jacó, descendente^&#42;1^ do meu amigo Abraão,
Tu és quem eu escolhi,

[NOTE]
====
. Lit.: “semente”.
====

[[v23-41-9]]

^<<v23-41-9,9>>^ Tu és quem eu trouxe dos confins da terra,
Tu és quem chamei das partes mais distantes.
Eu disse-te: ‘Tu és o meu servo;
Eu escolhi-te, não te rejeitei.

[[v23-41-10]]

^<<v23-41-10,10>>^ Não tenhas medo, pois estou contigo.
Não fiques ansioso, pois eu sou o teu Deus.
Vou fortalecer-te, sim, vou ajudar-te.
Vou segurar-te firmemente com a minha mão direita de justiça.’

[[v23-41-11]]

^<<v23-41-11,11>>^ Vê! Todos os que se enfurecem contra ti serão envergonhados e humilhados.
Os que lutam contra ti serão reduzidos a nada e perecerão.

[[v23-41-12]]

^<<v23-41-12,12>>^ Procurarás os que lutam contra ti, mas não os encontrarás.
Os que guerreiam contra ti irão tornar-se como algo inexistente, como absolutamente nada.

[[v23-41-13]]

^<<v23-41-13,13>>^ Pois eu, Jeová, teu Deus, seguro a tua mão direita;
Sou aquele que te diz: ‘Não tenhas medo. Irei ajudar-te.’

[[v23-41-14]]

^<<v23-41-14,14>>^ Não tenhas medo, ó verme^&#42;1^ Jacó,
Ó homens de Israel, eu vou ajudar-vos”,^&#42;2^ diz Jeová, teu Resgatador, o Santo de Israel.

[NOTE]
====
. Isto é, indefeso e humilde.
. Lit.: “ajudar-te”.
====

[[v23-41-15]]

^<<v23-41-15,15>>^ “Vê! Faço de ti um trenó de debulha,
Um instrumento de debulha novo, com dentes de fio duplo.
Irás pisar e esmagar os montes,
E reduzirás as colinas a palha.^&#42;1^

[NOTE]
====
. Ou: “pragana”.
====

[[v23-41-16]]

^<<v23-41-16,16>>^ Irás atirá-los para cima,^&#42;1^
E o vento irá levá-los;
Um vendaval irá espalhá-los.
Tu hás de alegrar-te em Jeová,
E orgulhar-te por causa do Santo de Israel.”

[NOTE]
====
. Ou: “padejá-los; joeirá-los”.
====

[[v23-41-17]]

^<<v23-41-17,17>>^ “Os necessitados e os pobres estão à procura de água, mas não a encontram.
A sua língua está seca por causa da sede.
Eu, Jeová, vou responder-lhes.
Eu, o Deus de Israel, não os abandonarei.

[[v23-41-18]]

^<<v23-41-18,18>>^ Farei com que haja rios nas colinas áridas
E fontes nos vales.^&#42;1^
Transformarei o deserto numa lagoa repleta de juncos,
E a terra árida em nascentes de água.

[NOTE]
====
. Lit.: “no meio das planícies de vale”.
====

[[v23-41-19]]

^<<v23-41-19,19>>^ Plantarei no deserto o cedro,
A acácia, a murta e o pinheiro.
Na planície desértica plantarei o junípero,
Com o freixo e com o cipreste,

[[v23-41-20]]

^<<v23-41-20,20>>^ Para que todas as pessoas vejam e saibam,
Prestem atenção e compreendam
Que a mão de Jeová fez isso
E que o Santo de Israel o realizou.”

[[v23-41-21]]

^<<v23-41-21,21>>^ “Apresentem a vossa causa”, diz Jeová.
“Exponham os vossos argumentos”, diz o Rei de Jacó.

[[v23-41-22]]

^<<v23-41-22,22>>^ “Apresentem provas e contem-nos as coisas que vão acontecer.
Contem-nos as coisas anteriores,^&#42;1^
Para que reflitamos nelas^&#42;2^ e saibamos o resultado.
Ou revelem-nos as coisas que virão.

[NOTE]
====
. Lit.: “primeiras coisas”.
. Ou: “apliquemos o nosso coração”.
====

[[v23-41-23]]

^<<v23-41-23,23>>^ Contem-nos o que acontecerá no futuro,
Para que saibamos que vocês são deuses.
Sim, façam alguma coisa, boa ou má,
Para que a vejamos e fiquemos admirados.

[[v23-41-24]]

^<<v23-41-24,24>>^ Vejam! Vocês são algo inexistente,
E o que realizam não é nada.
Todo aquele que vos escolhe é detestável.

[[v23-41-25]]

^<<v23-41-25,25>>^ Fiz surgir alguém do norte, e ele virá.
Alguém do nascente do sol,^&#42;1^ que invocará o meu nome.
Ele pisoteará os governantes^&#42;2^ como se fossem barro,
Assim como o oleiro calca a argila húmida.

[NOTE]
====
. Ou: “do leste”.
. Ou: “subgovernadores”.
====

[[v23-41-26]]

^<<v23-41-26,26>>^ Quem anunciou isto desde o princípio, para que o soubéssemos,
Ou desde os tempos passados, para que disséssemos: ‘Ele tem razão’?
Na verdade, ninguém o anunciou,
Ninguém o revelou.
Ninguém ouviu nada de vocês!”

[[v23-41-27]]

^<<v23-41-27,27>>^ Eu fui o primeiro a dizer a Sião: “Vê as coisas que vão acontecer!”
E enviarei a Jerusalém um portador de boas novas.

[[v23-41-28]]

^<<v23-41-28,28>>^ Mas fiquei a olhar, e não havia ninguém;
Não havia ninguém entre eles que desse conselhos.
E continuei a pedir-lhes que respondessem.

[[v23-41-29]]

^<<v23-41-29,29>>^ Vejam, todos eles são uma ilusão.^&#42;1^
Os seus trabalhos não são nada.
As suas imagens de metal^&#42;2^ são vento e algo sem valor.^&#42;3^

[NOTE]
====
. Ou: “algo inexistente”.
. Ou: “estátuas fundidas”.
. Ou: “uma irrealidade”.
====

'''

xref:023-isaias/023-isaias-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaias/023-isaias-042.adoc#v23-42-0[Próximo Capítulo &#62;]