include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-65-1]]

^<<v23-65-1,1>>^ “Tornei-me acessível àqueles^&#42;1^ que não perguntavam por mim;
Deixei-me encontrar por aqueles que não me procuravam.
Eu disse: ‘Estou aqui, estou aqui!’ a uma nação que não invocava o meu nome.

[NOTE]
====
. Ou: “Deixei-me procurar por aqueles”.
====

[[v23-65-2]]

^<<v23-65-2,2>>^ O dia inteiro estendi as mãos a um povo obstinado,
Que anda num caminho que não é bom,
Seguindo as suas próprias ideias;

[[v23-65-3]]

^<<v23-65-3,3>>^ A um povo que constantemente me ofende diante da minha face,
Fazendo sacrifícios em jardins e fumo sacrificial sobre tijolos.

[[v23-65-4]]

^<<v23-65-4,4>>^ Sentam-se entre as sepulturas,
E passam a noite em lugares escondidos,^&#42;1^
A comer carne de porco;
E há caldo de coisas imundas^&#42;2^ nos seus pratos.

[NOTE]
====
. Ou, possivelmente: “em cabanas de vigias”.
. Ou: “impuras”.
====

[[v23-65-5]]

^<<v23-65-5,5>>^ Dizem: ‘Fica onde estás, não te aproximes de mim,
Pois sou mais santo do que tu.’^&#42;1^
Eles são como fumo nas minhas narinas, como fogo que arde o dia inteiro.

[NOTE]
====
. Ou, possivelmente: “Pois irei transmitir-te a minha santidade”.
====

[[v23-65-6]]

^<<v23-65-6,6>>^ Vejam! Está escrito diante de mim;
Não ficarei calado,
Mas vou retribuir-lhes,
Vou retribuir-lhes em plena medida^&#42;1^

[NOTE]
====
. Lit.: “no seu peito”.
====

[[v23-65-7]]

^<<v23-65-7,7>>^ Pelos erros deles e pelos erros dos seus antepassados”, diz Jeová.
“Visto que fizeram fumo sacrificial nos montes
E me insultaram nas colinas,
A primeira coisa que farei será medir-lhes plenamente^&#42;1^ o seu salário.”

[NOTE]
====
. Lit.: “no seu peito”.
====

[[v23-65-8]]

^<<v23-65-8,8>>^ Jeová diz:
“Assim como quando se encontram uvas suculentas, boas para vinho novo,^&#42;1^
E alguém diz: ‘Não as destruas, porque há algo de bom^&#42;2^ nelas’,
Assim farei por causa dos meus servos;
Não os destruirei a todos.

[NOTE]
====
. Ou: “encontra vinho novo num cacho de uvas”.
. Lit.: “uma bênção”.
====

[[v23-65-9]]

^<<v23-65-9,9>>^ Farei sair de Jacó uma descendência,^&#42;1^
E de Judá aquele que herdará os meus montes;
Os meus escolhidos tomarão posse desta terra,
E os meus servos residirão ali.

[NOTE]
====
. Lit.: “semente”.
====

[[v23-65-10]]

^<<v23-65-10,10>>^ Para o meu povo que me procura,
Sarom irá tornar-se pasto para ovelhas,
E o vale^&#42;1^ de Acor um lugar de descanso para o gado.

[NOTE]
====
. Ou: “a planície”.
====

[[v23-65-11]]

^<<v23-65-11,11>>^ Mas vocês estão entre os que abandonam a Jeová,
Os que se esquecem do meu santo monte,
Os que põem a mesa para o deus da boa sorte
E que enchem taças de vinho misturado para o deus do destino.

[[v23-65-12]]

^<<v23-65-12,12>>^ Por isso, vou destinar-vos à espada,
E todos vocês se curvarão para serem abatidos,
Porque vos chamei, mas não me responderam,
Falei, mas não me escutaram;
Continuaram a fazer o que é mau aos meus olhos
E escolheram o que me desagrada.”

[[v23-65-13]]

^<<v23-65-13,13>>^ Portanto, assim diz o Soberano Senhor Jeová:
“Vejam! Os meus servos comerão, mas vocês passarão fome.
Os meus servos beberão, mas vocês passarão sede.
Os meus servos irão alegrar-se, mas vocês passarão vergonha.

[[v23-65-14]]

^<<v23-65-14,14>>^ Os meus servos gritarão de alegria por causa da boa condição de coração,
Mas vocês clamarão por causa da dor de coração
E chorarão por causa do vosso espírito quebrantado.

[[v23-65-15]]

^<<v23-65-15,15>>^ Deixarão um nome que os meus escolhidos usarão em maldições,
E o Soberano Senhor Jeová entregará cada um de vocês à morte,
Mas, aos seus servos, ele chamará por outro nome,

[[v23-65-16]]

^<<v23-65-16,16>>^ Assim, todo aquele que procurar uma bênção para si mesmo na terra
Será abençoado pelo Deus da verdade,^&#42;1^
E todo aquele que fizer um juramento na terra
Jurará pelo Deus da verdade.^&#42;2^
Pois as aflições^&#42;3^ anteriores serão esquecidas,
Ficarão escondidas dos meus olhos.

[NOTE]
====
. Ou: “de fidelidade”. Lit.: “de amém”.
. Ou: “de fidelidade”. Lit.: “de amém”.
. Ou: “dificuldades”.
====

[[v23-65-17]]

^<<v23-65-17,17>>^ Pois vejam! Crio novos céus e uma nova terra;
E as coisas anteriores não serão lembradas,
Nem voltarão ao coração.

[[v23-65-18]]

^<<v23-65-18,18>>^ Portanto, alegrem-se e exultem para sempre no que vou criar.
Pois vejam! Crio Jerusalém como motivo de alegria
E o seu povo como motivo de exultação.

[[v23-65-19]]

^<<v23-65-19,19>>^ Irei alegrar-me com Jerusalém e exultar pelo meu povo;
Nunca mais se ouvirá nela o som de choro nem um grito de aflição.”

[[v23-65-20]]

^<<v23-65-20,20>>^ “Nunca mais haverá ali um bebé que viva apenas poucos dias,
Nem idoso que não viva todos os seus dias;
Pois quem morrer com cem anos será considerado jovem,
E o pecador será amaldiçoado, mesmo que tenha cem anos.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “E aquele que não chegar aos cem será considerado amaldiçoado”.
====

[[v23-65-21]]

^<<v23-65-21,21>>^ Eles construirão casas e morarão nelas;
Plantarão vinhas e comerão os seus frutos.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não construirão para outros morarem,
Nem plantarão para outros comerem.
Pois os dias do meu povo serão como os dias de uma árvore,
E os meus escolhidos tirarão pleno proveito do trabalho das suas mãos.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não trabalharão arduamente em vão,
Nem darão à luz filhos que sofrerão calamidade,^&#42;1^
Porque eles e os seus filhos
São a descendência^&#42;2^ abençoada por Jeová.

[NOTE]
====
. Ou: “filhos para aflição”.
. Lit.: “semente”.
====

[[v23-65-24]]

^<<v23-65-24,24>>^ Mesmo antes de clamarem, eu responderei;
Enquanto ainda estiverem a falar, eu os atenderei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro pastarão juntos,
O leão comerá palha como o touro,
E a serpente há de alimentar-se do pó.
Não farão dano nem causarão ruína em todo o meu santo monte”, diz Jeová.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]