include::./index.adoc[]

[[v23-55-0]]
=== Isaías, 55
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-55-1]]

^<<v23-55-1,1>>^ Venham, todos os que estão com sede, venham à água!
Os que não têm dinheiro, venham, comprem e comam!
Sim, venham, levem^&#42;1^ vinho e leite sem dinheiro e sem custo!

[NOTE]
====
. Ou: “comprem”.
====

[[v23-55-2]]

^<<v23-55-2,2>>^ Por que razão continuam a gastar dinheiro com o que não é pão,
E gastam o vosso salário^&#42;1^ com o que não traz satisfação?
Escutem-me atentamente e comam o que é bom,
E saborearão^&#42;2^ os melhores alimentos.^&#42;3^

[NOTE]
====
. Ou: “vosso dinheiro que ganham arduamente”.
. Ou: “a vossa alma saboreará”.
. Lit.: “a gordura”.
====

[[v23-55-3]]

^<<v23-55-3,3>>^ Escutem^&#42;1^ e venham a mim.
Deem ouvidos, e ficarão vivos,^&#42;2^
E eu sem falta farei convosco um pacto eterno
Em harmonia com as fiéis^&#42;3^ expressões de amor leal a David.

[NOTE]
====
. Ou: “Inclinem o vosso ouvido”.
. Ou: “a vossa alma ficará viva”.
. Ou: “confiáveis”.
====

[[v23-55-4]]

^<<v23-55-4,4>>^ Vejam, fiz dele uma testemunha para as nações,
Um líder e governante para as nações.

[[v23-55-5]]

^<<v23-55-5,5>>^ Tu chamarás uma nação que não conheces,
E pessoas de uma nação que não te conhecem correrão para ti
Por causa de Jeová, teu Deus, o Santo de Israel,
Porque ele te glorificará.

[[v23-55-6]]

^<<v23-55-6,6>>^ Procurem a Jeová enquanto pode ser encontrado.
Chamem-no enquanto está perto.

[[v23-55-7]]

^<<v23-55-7,7>>^ Deixem os maus o seu caminho,
E os malfeitores os seus pensamentos;
Que voltem para Jeová, que terá misericórdia deles,
Para o nosso Deus, porque perdoará amplamente.^&#42;1^

[NOTE]
====
. Ou: “liberalmente”.
====

[[v23-55-8]]

^<<v23-55-8,8>>^ “Pois os meus pensamentos não são os vossos pensamentos,
E os vossos caminhos não são os meus caminhos”, diz Jeová.

[[v23-55-9]]

^<<v23-55-9,9>>^ “Pois, assim como os céus são mais altos do que a terra,
Assim os meus caminhos são mais altos do que os vossos caminhos,
E os meus pensamentos, do que os vossos pensamentos.

[[v23-55-10]]

^<<v23-55-10,10>>^ Pois, assim como a chuva e a neve descem do céu
E não voltam para lá sem antes saturar a terra e fazê-la produzir e brotar,
Dando semente aos que semeiam e pão aos que comem,

[[v23-55-11]]

^<<v23-55-11,11>>^ Assim será^&#42;1^ a palavra que sai da minha boca.
Não voltará a mim sem resultados,
Mas certamente realizará o que for do meu agrado,^&#42;2^
E sem falta cumprirá o objetivo para o qual a enviei.

[NOTE]
====
. Ou: “mostrará ser”.
. Ou: “da minha vontade”.
====

[[v23-55-12]]

^<<v23-55-12,12>>^ Pois vocês sairão com alegria,
E serão trazidos em paz.
Os montes e as colinas ficarão animados à vossa frente com gritos de alegria,
E as árvores do campo baterão palmas.

[[v23-55-13]]

^<<v23-55-13,13>>^ Em vez dos espinheiros crescerá o junípero,
E em vez das urtigas crescerá a murta.
Isto trará glória^&#42;1^ para Jeová,
Será um sinal eterno, que nunca deixará de existir.”

[NOTE]
====
. Ou: “fará um nome”.
====

'''

xref:023-isaias/023-isaias-054.adoc#v23-54-0[&#60; Capítulo Anterior] | <<v23-55-0,Topo>> | xref:023-isaias/023-isaias-056.adoc#v23-56-0[Próximo Capítulo &#62;]