include::./index.adoc[]

[[v23-13-0]]
=== Isaías, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-13-1]]

^<<v23-13-1,1>>^ Proclamação contra Babilónia, que Isaías, filho de Amoz, observou numa visão:

[[v23-13-2]]

^<<v23-13-2,2>>^ “Ergam um sinal^&#42;1^ numa montanha rochosa.
Gritem-lhes, acenem com a mão,
Para que entrem pelos portões dos nobres.

[NOTE]
====
. Ou: “poste de sinal”.
====

[[v23-13-3]]

^<<v23-13-3,3>>^ Dei a ordem àqueles a quem designei.^&#42;1^
Para expressar a minha ira, convoquei os meus guerreiros,
Que se alegram orgulhosamente.

[NOTE]
====
. Lit.: “aos meus santificados”.
====

[[v23-13-4]]

^<<v23-13-4,4>>^ Escutem! Uma multidão nas montanhas;
O seu ruído é como o de um povo numeroso!
Escutem! O tumulto de reinos,
De nações reunidas!
Jeová dos exércitos está a reunir o exército para a guerra.

[[v23-13-5]]

^<<v23-13-5,5>>^ Estão a chegar de uma terra distante,
Desde a extremidade dos céus,
Jeová e as armas da sua ira,
Para arruinar toda a terra.

[[v23-13-6]]

^<<v23-13-6,6>>^ Lamentem, pois o dia de Jeová está próximo!
Virá como uma destruição da parte do Todo-Poderoso.

[[v23-13-7]]

^<<v23-13-7,7>>^ Por isso é que todas as mãos ficarão fracas,
E o coração de todos os homens se derreterá de medo.

[[v23-13-8]]

^<<v23-13-8,8>>^ As pessoas ficam apavoradas.
Contorcem-se e têm dores,
Como uma mulher que está a dar à luz.
Olham aterrorizadas umas para as outras,
Com os rostos refletindo^&#42;1^ angústia.

[NOTE]
====
. Ou: “corados de”.
====

[[v23-13-9]]

^<<v23-13-9,9>>^ Vejam! O dia de Jeová está a chegar,
Cruel, com fúria e com ira ardente,
Para fazer desta terra motivo de terror,
E para exterminar dela os pecadores.

[[v23-13-10]]

^<<v23-13-10,10>>^ Pois as estrelas dos céus e as suas constelações^&#42;1^
Não emitirão a sua luz;
O sol estará escuro ao nascer,
E a lua não dará a sua luz.

[NOTE]
====
. Lit.: “e os seus Quesis”, talvez se referindo a Órion e às constelações à sua volta.
====

[[v23-13-11]]

^<<v23-13-11,11>>^ Ajustarei contas com a terra habitada pela sua maldade,
E com os maus, pelo seu erro.
Porei fim ao orgulho dos presunçosos
E humilharei a arrogância dos tiranos.

[[v23-13-12]]

^<<v23-13-12,12>>^ Farei o homem mortal mais raro do que o ouro refinado,
E os humanos mais raros do que o ouro de Ofir.

[[v23-13-13]]

^<<v23-13-13,13>>^ É por isso que farei tremer os céus,
E a terra será sacudida e sairá do seu lugar
Diante da fúria de Jeová dos exércitos no dia da sua ira ardente.

[[v23-13-14]]

^<<v23-13-14,14>>^ Como uma gazela perseguida e como um rebanho que não tem ninguém para o reunir,
Cada um voltará para o seu próprio povo;
Cada um fugirá para a sua própria terra.

[[v23-13-15]]

^<<v23-13-15,15>>^ Quem for encontrado será trespassado,
E quem for apanhado cairá pela espada.

[[v23-13-16]]

^<<v23-13-16,16>>^ As suas crianças serão despedaçadas diante dos seus olhos,
As suas casas serão saqueadas
E as suas esposas serão violadas.

[[v23-13-17]]

^<<v23-13-17,17>>^ Despertarei contra eles os medos,
Que consideram a prata como nada
E que não se agradam do ouro.

[[v23-13-18]]

^<<v23-13-18,18>>^ Os seus arcos despedaçarão os jovens;
Não terão piedade do fruto do ventre,
Nem misericórdia das crianças.

[[v23-13-19]]

^<<v23-13-19,19>>^ E Babilónia, o mais glorioso^&#42;1^ dos reinos,
A beleza e o orgulho dos caldeus,
Ficará como Sodoma e Gomorra, quando Deus as destruiu.

[NOTE]
====
. Ou: “o ornamento”.
====

[[v23-13-20]]

^<<v23-13-20,20>>^ Nunca mais será habitada,
Nem será povoada de geração em geração.
O árabe não armará ali a sua tenda,
E os pastores não levarão os seus rebanhos para descansar ali.

[[v23-13-21]]

^<<v23-13-21,21>>^ Os animais do deserto irão deitar-se ali;
As suas casas irão encher-se de corujas.^&#42;1^
Ali habitarão avestruzes,
E bodes selvagens^&#42;2^ saltarão por ali.

[NOTE]
====
. Ou: “bufos-reais”.
. Ou, possivelmente: “E demónios caprinos”.
====

[[v23-13-22]]

^<<v23-13-22,22>>^ Animais uivarão nas suas torres,
E chacais nos seus palácios luxuosos.
A hora dela está próxima, e os seus dias não serão prolongados.”

'''

xref:023-isaias/023-isaias-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaias/023-isaias-014.adoc#v23-14-0[Próximo Capítulo &#62;]