include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-29-1]]

^<<v23-29-1,1>>^ “Ai de Ariel,^&#42;1^ Ariel, a cidade onde David acampou!
Continue ano após ano,
Que continue o ciclo de festividades.

[NOTE]
====
. Que possivelmente significa “o braseiro do altar de Deus”, aparentemente se referindo a Jerusalém.
====

[[v23-29-2]]

^<<v23-29-2,2>>^ Eu, porém, causarei aflição a Ariel,
E haverá luto e lamentação;
E ela irá tornar-se para mim como o braseiro do altar de Deus.

[[v23-29-3]]

^<<v23-29-3,3>>^ Acamparei ao teu redor,
E irei cercar-te com estacas pontiagudas
E erguerei contra ti obras de cerco.

[[v23-29-4]]

^<<v23-29-4,4>>^ Serás rebaixada
E falarás desde o chão;
As tuas palavras serão abafadas pelo pó.
A tua voz virá do chão
Como a voz de alguém que invoca espíritos,
E as tuas palavras serão sussurradas^&#42;1^ desde o pó.

[NOTE]
====
. Ou: “chilrarão”.
====

[[v23-29-5]]

^<<v23-29-5,5>>^ A multidão dos teus inimigos^&#42;1^ será como a poeira fina;
A multidão dos tiranos, igual à palha^&#42;2^ que é levada pelo vento.
Isto acontecerá num instante, repentinamente.

[NOTE]
====
. Lit.: “estranhos”.
. Ou: “pragana”.
====

[[v23-29-6]]

^<<v23-29-6,6>>^ Jeová dos exércitos virá em teu auxílio
Com trovões, terramotos e um grande ruído,
Com vendavais, tempestades e as chamas de um fogo consumidor.”

[[v23-29-7]]

^<<v23-29-7,7>>^ Então, a multidão de todas as nações que travam guerra contra Ariel
— Todos os que guerreiam contra ela,
Erguem torres de cerco contra ela
E causam-lhe aflição —
Hão de tornar-se como um sonho, uma visão da noite.

[[v23-29-8]]

^<<v23-29-8,8>>^ Sim, será como quando alguém com fome sonha que está a comer,
Mas acorda com fome;^&#42;1^
E como quando alguém com sede sonha que está a beber,
Mas acorda cansado e com sede.^&#42;2^
Assim acontecerá com a multidão de todas as nações
Que travam guerra contra o monte Sião.

[NOTE]
====
. Ou: “acorda e a sua alma está vazia”.
. Ou: “e a sua alma está seca”.
====

[[v23-29-9]]

^<<v23-29-9,9>>^ Fiquem espantados e perplexos;
Ceguem-se e fiquem cegos.
Eles estão embriagados, mas não com vinho;
Cambaleiam, mas não por causa da bebida alcoólica.

[[v23-29-10]]

^<<v23-29-10,10>>^ Pois Jeová derramou sobre vocês um espírito de sono profundo;
Fechou os vossos olhos, os profetas,
E cobriu as vossas cabeças, os videntes.

[[v23-29-11]]

^<<v23-29-11,11>>^ Todas as visões se tornam para vocês iguais às palavras de um livro selado. Quando o entregam a alguém que sabe ler e lhe pedem: “Lê isto em voz alta, por favor”, ele responde: “Não posso, pois está selado.”

[[v23-29-12]]

^<<v23-29-12,12>>^ E quando entregam o livro a alguém que não sabe ler e lhe pedem: “Lê isto, por favor”, ele diz: “Não sei ler.”

[[v23-29-13]]

^<<v23-29-13,13>>^ Jeová diz: “Este povo aproxima-se de mim com a boca
E honra-me com os lábios,
Mas o seu coração está muito longe de mim;
E a adoração que me prestam^&#42;1^ baseia-se em regras de homens, que lhes foram ensinadas.

[NOTE]
====
. Ou: “E o seu temor de mim”.
====

[[v23-29-14]]

^<<v23-29-14,14>>^ Por isso, mais uma vez farei coisas espantosas com este povo,
Uma coisa espantosa após outra;
A sabedoria dos seus sábios perecerá,
E o entendimento dos seus homens sensatos^&#42;1^ será escondido.”

[NOTE]
====
. Ou: “prudentes”.
====

[[v23-29-15]]

^<<v23-29-15,15>>^ Ai dos que fazem de tudo para esconder os seus planos^&#42;1^ de Jeová.
Praticam os seus atos num lugar escuro
E dizem: “Quem é que nos vê?
Quem é que sabe o que estamos a fazer?”

[NOTE]
====
. Ou: “conselhos”.
====

[[v23-29-16]]

^<<v23-29-16,16>>^ Como vocês distorcem as coisas!^&#42;1^
Deve o oleiro ser considerado igual ao barro?
Deve a coisa feita dizer sobre aquele que a fez:
“Ele não me fez”?
E diz o objeto que foi moldado sobre aquele que o moldou:
“Ele não entende nada”?

[NOTE]
====
. Ou: “Como vocês são perversos!”
====

[[v23-29-17]]

^<<v23-29-17,17>>^ Muito em breve o Líbano será transformado em pomar,
E o pomar será considerado uma floresta.

[[v23-29-18]]

^<<v23-29-18,18>>^ Nesse dia, os surdos ouvirão as palavras do livro;
E, livres das trevas e da escuridão, os olhos dos cegos verão.

[[v23-29-19]]

^<<v23-29-19,19>>^ Os mansos terão grande alegria em Jeová,
E os pobres da terra exultarão no Santo de Israel.

[[v23-29-20]]

^<<v23-29-20,20>>^ Pois o tirano não existirá mais,
O fanfarrão chegará ao seu fim,
E todos os que se mantêm alerta para causar dano serão destruídos:

[[v23-29-21]]

^<<v23-29-21,21>>^ Os que usam palavras falsas para condenar outros,
Que tentam enlaçar aquele que defende^&#42;1^ outros no portão da cidade
E que, com argumentos vazios, negam justiça ao justo.

[NOTE]
====
. Lit.: “repreende”.
====

[[v23-29-22]]

^<<v23-29-22,22>>^ Portanto, isto é o que Jeová, aquele que resgatou Abraão, diz à casa de Jacó:
“Jacó nunca mais se envergonhará,
E o seu rosto nunca mais ficará pálido.^&#42;1^

[NOTE]
====
. Isto é, de vergonha e deceção.
====

[[v23-29-23]]

^<<v23-29-23,23>>^ Pois, ao ver no seu meio os seus filhos,
Trabalho das minhas mãos,
Eles santificarão o meu nome;
Sim, santificarão o Santo de Jacó,
E reverenciarão o Deus de Israel.

[[v23-29-24]]

^<<v23-29-24,24>>^ Os que são rebeldes no espírito vão adquirir entendimento,
E os que se queixam aceitarão instrução.”

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]