include::./index.adoc[]

[[v23-61-0]]
=== Isaías, 61
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-61-1]]

^<<v23-61-1,1>>^ O espírito do Soberano Senhor Jeová está sobre mim,
Porque Jeová me ungiu para declarar boas novas aos mansos.
Enviou-me para curar^&#42;1^ os de coração quebrantado,
Para proclamar liberdade aos cativos
E ampla abertura dos olhos aos presos,

[NOTE]
====
. Lit.: “enfaixar”.
====

[[v23-61-2]]

^<<v23-61-2,2>>^ Para proclamar o ano de boa vontade^&#42;1^ de Jeová
E o dia de vingança do nosso Deus,
Para consolar todos os que choram,

[NOTE]
====
. Ou: “de favor”.
====

[[v23-61-3]]

^<<v23-61-3,3>>^ Para dar aos que choram por Sião
Uma grinalda em vez de cinzas,
O óleo de alegria em vez de luto,
O manto de louvor em vez de um espírito desanimado.
E serão chamados grandes árvores de justiça,
Plantadas por Jeová, para ele ser glorificado.^&#42;1^

[NOTE]
====
. Ou: “embelezado”.
====

[[v23-61-4]]

^<<v23-61-4,4>>^ Reconstruirão as ruínas antigas,
Erguerão os lugares anteriormente desolados
E restaurarão as cidades devastadas,
Os lugares que ficaram desolados de geração em geração.

[[v23-61-5]]

^<<v23-61-5,5>>^ “Estranhos irão oferecer-se e pastorear os vossos rebanhos,
E estrangeiros cuidarão dos vossos campos e das vossas vinhas.

[[v23-61-6]]

^<<v23-61-6,6>>^ Quanto a vocês, serão chamados sacerdotes de Jeová,
Serão chamados servos^&#42;1^ do nosso Deus.
Irão alimentar-se dos recursos das nações
E orgulhar-se da glória^&#42;2^ delas.

[NOTE]
====
. Ou: “ministros”.
. Ou: “das riquezas”.
====

[[v23-61-7]]

^<<v23-61-7,7>>^ Em vez da vergonha, terão uma porção dupla,
E, em vez da humilhação, o meu povo gritará de alegria por causa do que recebeu.
Sim, possuirão uma porção dupla na sua terra.
Hão de alegrar-se para sempre.

[[v23-61-8]]

^<<v23-61-8,8>>^ Pois eu, Jeová, amo a justiça;
Odeio o roubo e a injustiça.
Fielmente lhes darei o seu salário
E farei com eles um pacto eterno.

[[v23-61-9]]

^<<v23-61-9,9>>^ A sua descendência^&#42;1^ será conhecida entre as nações;
E os seus descendentes, entre os povos.
Todos os que os virem reconhecerão
Que eles são a descendência^&#42;2^ que Jeová abençoou.”

[NOTE]
====
. Lit.: “semente”.
. Lit.: “semente”.
====

[[v23-61-10]]

^<<v23-61-10,10>>^ Terei grande alegria em Jeová.
Todo o meu ser^&#42;1^ exultará no meu Deus.
Pois ele vestiu-me com a roupa da salvação;
Cobriu-me com a túnica^&#42;2^ da justiça,
Como um noivo que usa um turbante como o de um sacerdote,
E como uma noiva que se enfeita com os seus adornos.

[NOTE]
====
. Ou: “A minha alma”.
. Ou: “túnica sem mangas”.
====

[[v23-61-11]]

^<<v23-61-11,11>>^ Pois, assim como a terra faz brotar as plantas
E o jardim faz germinar as coisas lá semeadas,
Assim o Soberano Senhor Jeová
Fará brotar a justiça e o louvor diante de todas as nações.

'''

xref:023-isaias/023-isaias-060.adoc#v23-60-0[&#60; Capítulo Anterior] | <<v23-61-0,Topo>> | xref:023-isaias/023-isaias-062.adoc#v23-62-0[Próximo Capítulo &#62;]