include::./index.adoc[]

[[v23-28-0]]
=== Isaías, 28
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-28-1]]

^<<v23-28-1,1>>^ Ai da coroa^&#42;1^ ostentosa^&#42;2^ dos bêbados de Efraim,
E da sua gloriosa beleza, que não passa de uma flor que murcha,
Na cabeça do vale fértil dos que foram vencidos pelo vinho!

[NOTE]
====
. Aparentemente, refere-se à capital, Samaria.
. Ou: “arrogante; orgulhosa”.
====

[[v23-28-2]]

^<<v23-28-2,2>>^ Vejam! Jeová enviará alguém forte e poderoso.
Como um temporal com trovões e granizo, um vendaval destrutivo,
Como uma tempestade que causa fortes inundações,
Ele irá lançá-la com força ao chão.

[[v23-28-3]]

^<<v23-28-3,3>>^ A coroa ostentosa^&#42;1^ dos bêbados de Efraim
Será pisada.

[NOTE]
====
. Ou: “arrogante; orgulhosa”.
====

[[v23-28-4]]

^<<v23-28-4,4>>^ E a sua gloriosa beleza, que não passa de uma flor que murcha,
Na cabeça do vale fértil,
Irá tornar-se como o figo temporão antes do verão.
Quando alguém o vê, devora-o assim que o apanha.

[[v23-28-5]]

^<<v23-28-5,5>>^ Nesse dia, Jeová dos exércitos irá tornar-se uma gloriosa coroa e uma bela grinalda para os que restarem do seu povo.

[[v23-28-6]]

^<<v23-28-6,6>>^ Irá tornar-se um espírito de justiça para aquele que se senta para julgar e uma fonte de força para os que repelem o ataque no portão.

[[v23-28-7]]

^<<v23-28-7,7>>^ Até mesmo estes se perdem por causa do vinho;
As bebidas alcoólicas fazem-nos cambalear.
Sacerdotes e profetas perdem-se por causa do álcool;
O vinho deixa-os confusos,
E cambaleiam por causa da bebida;
Perdem-se nas suas visões,
E cometem erros no julgamento.

[[v23-28-8]]

^<<v23-28-8,8>>^ Pois as suas mesas estão cheias de vómito repugnante
— Não há nenhum lugar limpo.

[[v23-28-9]]

^<<v23-28-9,9>>^ A quem se ensinará,
E a quem se explicará a mensagem?
Aos que acabaram de ser desmamados,
Os que acabaram de ser tirados do peito?

[[v23-28-10]]

^<<v23-28-10,10>>^ Pois são “ordens e mais ordens, ordens e mais ordens,
Regras e mais regras, regras e mais regras,^&#42;1^
Um pouco aqui, um pouco ali”.

[NOTE]
====
. Ou: “Corda de medir sobre corda de medir, corda de medir sobre corda de medir”.
====

[[v23-28-11]]

^<<v23-28-11,11>>^ Assim, por meio dos que gaguejam quando falam^&#42;1^ e por meio de uma língua estrangeira, ele falará a este povo.

[NOTE]
====
. Lit.: “pelo gaguejar de lábio”.
====

[[v23-28-12]]

^<<v23-28-12,12>>^ Ele tinha-lhes dito: “Este é o lugar de descanso. Deixem o cansado descansar; este é o lugar de repouso”, mas não quiseram escutar.

[[v23-28-13]]

^<<v23-28-13,13>>^ Por isso, a palavra de Jeová para eles será:
“Ordens e mais ordens, ordens e mais ordens,
Regras e mais regras, regras e mais regras,^&#42;1^
Um pouco aqui, um pouco ali”,
De modo que, quando andarem,
Tropeçarão e cairão para trás,
E serão quebrados, enlaçados e apanhados.

[NOTE]
====
. Ou: “Corda de medir sobre corda de medir, corda de medir sobre corda de medir”.
====

[[v23-28-14]]

^<<v23-28-14,14>>^ Portanto, ouçam a palavra de Jeová, ó fanfarrões,
Governantes deste povo, que estão em Jerusalém,

[[v23-28-15]]

^<<v23-28-15,15>>^ Pois vocês dizem:
“Fizemos um pacto com a Morte,
E fizemos um acordo^&#42;1^ com a Sepultura.^&#42;2^
Quando vier a forte inundação,
Não nos atingirá,
Pois fizemos da mentira o nosso refúgio
E escondemo-nos na falsidade.”

[NOTE]
====
. Ou, possivelmente: “realizámos uma visão”.
. Ou: “o Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v23-28-16]]

^<<v23-28-16,16>>^ Por isso, assim diz o Soberano Senhor Jeová:
“Vejam! Eu ponho como alicerce em Sião uma pedra provada,
A preciosa pedra angular de um alicerce seguro.
Ninguém que exercer fé entrará em pânico.

[[v23-28-17]]

^<<v23-28-17,17>>^ E vou fazer da justiça a corda de medir,
E da retidão o nível.^&#42;1^
O granizo arrasará o refúgio das mentiras,
E as águas inundarão o esconderijo.

[NOTE]
====
. Ou: “fio de prumo”.
====

[[v23-28-18]]

^<<v23-28-18,18>>^ O vosso pacto com a Morte será desfeito,
E o vosso acordo com a Sepultura^&#42;1^ não ficará de pé.
Quando vier a forte inundação,
Serão arrasados por ela.

[NOTE]
====
. Ou: “o Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v23-28-19]]

^<<v23-28-19,19>>^ Cada vez que vier,
Irá levar-vos embora;
Pois virá manhã após manhã,
Durante o dia e durante a noite.
Só o pavor fará com que entendam a mensagem.”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “Quando entenderem, sentirão puro pavor.”
====

[[v23-28-20]]

^<<v23-28-20,20>>^ Pois a cama é demasiado curta para se deitar nela,
E o lençol é demasiado estreito para se enrolar nele.

[[v23-28-21]]

^<<v23-28-21,21>>^ Porque Jeová se levantará como fez no monte Perazim;
Ficará agitado como no vale^&#42;1^ perto de Gibeão,
Para realizar o seu ato, o seu ato estranho,
E para executar a sua obra, a sua obra incomum.

[NOTE]
====
. Ou: “na planície”.
====

[[v23-28-22]]

^<<v23-28-22,22>>^ Agora, não façam troça,
Para que as vossas correntes não sejam ainda mais apertadas,
Pois ouvi do Soberano Senhor, Jeová dos exércitos,
Que um extermínio foi decretado para toda esta terra.^&#42;1^

[NOTE]
====
. Ou: “toda a terra”.
====

[[v23-28-23]]

^<<v23-28-23,23>>^ Deem ouvidos e escutem a minha voz;
Prestem atenção e escutem o que eu digo.

[[v23-28-24]]

^<<v23-28-24,24>>^ Será que o lavrador passa o tempo todo a lavrar para semear?
Será que ele afofa e aplana o solo sem parar?

[[v23-28-25]]

^<<v23-28-25,25>>^ Depois de aplanar a superfície,
Não espalha o cominho-preto e semeia o cominho,
E não planta o trigo, o painço e a cevada nos lugares certos,
E a espelta nas beiradas?

[[v23-28-26]]

^<<v23-28-26,26>>^ Pois Ele ensina-o^&#42;1^ da maneira certa;
O seu Deus instrui-o.

[NOTE]
====
. Ou: “Ele disciplina-o; Ele castiga-o”.
====

[[v23-28-27]]

^<<v23-28-27,27>>^ Pois não é com o trenó debulhador que se debulha o cominho-preto,
E não se passa a roda de uma carroça sobre o cominho.
Mas é com uma vara que se malha o cominho-preto;
E o cominho, com um pau.

[[v23-28-28]]

^<<v23-28-28,28>>^ Será que alguém tritura os cereais para fazer pão?
Não, ninguém os debulha sem parar;
E quando alguém passa sobre eles o cilindro da carroça com os seus cavalos,
Não os esmaga.

[[v23-28-29]]

^<<v23-28-29,29>>^ Isto também vem da parte de Jeová dos exércitos;
Cujos conselhos^&#42;1^ são maravilhosos
E cujas realizações são grandiosas.^&#42;2^

[NOTE]
====
. Ou: “propósitos”.
. Ou: “E cuja sabedoria prática é grandiosa”.
====

'''

xref:023-isaias/023-isaias-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaias/023-isaias-029.adoc#v23-29-0[Próximo Capítulo &#62;]