include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-7-1]]

^<<v23-7-1,1>>^ Nos dias em que Acaz, filho de Jotão, filho de Uzias, era rei de Judá, Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, vieram guerrear contra Jerusalém, mas eles não a conseguiram^&#42;1^ capturar.

[NOTE]
====
. Ou, possivelmente: “ele não a conseguiu”.
====

[[v23-7-2]]

^<<v23-7-2,2>>^ Informou-se à casa de David: “A Síria uniu-se a Efraim.”
E o coração de Acaz e o coração do seu povo começaram a tremer, assim como as árvores da floresta se agitam com o vento.

[[v23-7-3]]

^<<v23-7-3,3>>^ Então, Jeová disse a Isaías: “Por favor, sai e encontra-te com Acaz, tu e o teu filho Sear-Jasube,^&#42;1^ na extremidade do aqueduto do reservatório^&#42;2^ superior, junto à estrada do campo do lavadeiro.

[NOTE]
====
. Que significa “apenas um restante voltará”.
. Ou: “canal”.
====

[[v23-7-4]]

^<<v23-7-4,4>>^ Diz-lhe: ‘Tem cuidado e mantém-te calmo. Não tenhas medo e não fiques desanimado por causa desses dois pedaços de lenha fumegantes, por causa da ira acesa de Rezim e da Síria, e do filho de Remalias.

[[v23-7-5]]

^<<v23-7-5,5>>^ Pois a Síria, com Efraim e o filho de Remalias, tramou o mal contra ti, dizendo:

[[v23-7-6]]

^<<v23-7-6,6>>^ “Vamos subir contra Judá e despedaçá-lo;^&#42;1^ vamos conquistá-lo^&#42;2^ e designar o filho de Tabeel como seu rei.”

[NOTE]
====
. Ou, possivelmente: “aterrorizá-lo”.
. Ou: “abrir uma brecha nas suas muralhas”. Lit.: “rachá-lo”.
====

[[v23-7-7]]

^<<v23-7-7,7>>^ “‘Assim diz o Soberano Senhor Jeová:
“Isso não será bem-sucedido,
Nem acontecerá.

[[v23-7-8]]

^<<v23-7-8,8>>^ Pois Damasco é a cabeça da Síria,
E Rezim é o cabeça de Damasco;
Em apenas 65 anos
Efraim será despedaçado e deixará de ser povo.

[[v23-7-9]]

^<<v23-7-9,9>>^ Samaria é a cabeça de Efraim,
E o filho de Remalias é o cabeça de Samaria.
A menos que tenham forte fé,
Não permanecerão firmes.”’”

[[v23-7-10]]

^<<v23-7-10,10>>^ Jeová continuou a dizer a Acaz:

[[v23-7-11]]

^<<v23-7-11,11>>^ “Pede um sinal da parte de Jeová, teu Deus; pode ser tão profundo como a Sepultura^&#42;1^ ou tão alto como o céu.”

[NOTE]
====
. Ou: “o Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v23-7-12]]

^<<v23-7-12,12>>^ Acaz, porém, disse: “Não pedirei, nem porei Jeová à prova.”

[[v23-7-13]]

^<<v23-7-13,13>>^ Então Isaías disse: “Escutem-me, por favor, ó casa de David. Não vos basta testarem a paciência dos homens? Também têm de testar a paciência de Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Portanto, o próprio Jeová irá dar-vos um sinal: Vejam! A jovem^&#42;1^ ficará grávida e dará à luz um filho, e irá dar-lhe o nome de Emanuel.^&#42;2^

[NOTE]
====
. Ou: “donzela”.
. Que significa “connosco está Deus”.
====

[[v23-7-15]]

^<<v23-7-15,15>>^ Ele só terá manteiga e mel para comer quando souber rejeitar o que é mau e escolher o que é bom.

[[v23-7-16]]

^<<v23-7-16,16>>^ Pois antes que o menino saiba rejeitar o que é mau e escolher o que é bom, a terra dos dois reis de quem tens medo ficará completamente abandonada.

[[v23-7-17]]

^<<v23-7-17,17>>^ Jeová trará contra ti, contra o teu povo e contra a casa do teu pai um tempo como nunca houve desde o dia em que Efraim se separou de Judá, pois Ele trará o rei da Assíria.

[[v23-7-18]]

^<<v23-7-18,18>>^ “Nesse dia, Jeová assobiará para chamar as moscas dos distantes canais do Nilo, no Egito, e as abelhas na terra da Assíria,

[[v23-7-19]]

^<<v23-7-19,19>>^ e todas elas virão e pousarão nos vales^&#42;1^ escarpados, nas fendas dos rochedos, em todos os espinhos e em todos os bebedouros.

[NOTE]
====
. Ou: “uádis”.
====

[[v23-7-20]]

^<<v23-7-20,20>>^ “Nesse dia, através de uma navalha contratada da região do rio Eufrates^&#42;1^ — por meio do rei da Assíria —, Jeová irá rapar-lhe a cabeça e os pelos das pernas, e com ela também lhe tirará a barba.

[NOTE]
====
. Lit.: “do Rio”.
====

[[v23-7-21]]

^<<v23-7-21,21>>^ “Nesse dia, os homens preservarão vivas uma novilha do rebanho e duas ovelhas.

[[v23-7-22]]

^<<v23-7-22,22>>^ E, por causa da abundância de leite, comerão manteiga, pois todos os que restarem no país só terão manteiga e mel para comer.

[[v23-7-23]]

^<<v23-7-23,23>>^ “Nesse dia, em todo o lugar onde havia mil videiras no valor de 1000 peças de prata, haverá apenas espinhos e ervas daninhas.

[[v23-7-24]]

^<<v23-7-24,24>>^ Homens entrarão lá com arco e flechas, porque todo o país estará coberto de espinhos e ervas daninhas.

[[v23-7-25]]

^<<v23-7-25,25>>^ E, com medo dos espinhos e das ervas daninhas, não te aproximarás dos montes que antes eram cavados com a enxada; eles irão tornar-se um lugar para a pastagem de touros e um lugar pisado por ovelhas.”

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]