include::./index.adoc[]

[[v23-43-0]]
=== Isaías, 43
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-43-1]]

^<<v23-43-1,1>>^ Agora, assim diz Jeová,
O teu Criador, ó Jacó, aquele que te formou, ó Israel:
“Não tenhas medo, porque eu te resgatei.
Chamei-te pelo teu nome.
Tu pertences-me.

[[v23-43-2]]

^<<v23-43-2,2>>^ Quando passares pelas águas, estarei contigo,
E, quando atravessares rios, eles não te cobrirão.
Quando andares pelo fogo, não ficarás chamuscado,
Nem serás queimado pelas chamas.

[[v23-43-3]]

^<<v23-43-3,3>>^ Pois eu sou Jeová, teu Deus,
O Santo de Israel, teu Salvador.
Dei o Egito como teu resgate,
A Etiópia e Sebá em troca de ti.

[[v23-43-4]]

^<<v23-43-4,4>>^ Pois tornaste-te precioso aos meus olhos,
Foste honrado e eu amo-te.
Por isso darei pessoas em teu lugar
E nações em troca da tua vida.^&#42;1^

[NOTE]
====
. Ou: “alma”.
====

[[v23-43-5]]

^<<v23-43-5,5>>^ Não tenhas medo, pois estou contigo.
Do leste trarei a tua descendência^&#42;1^
E do oeste irei reunir-te.

[NOTE]
====
. Lit.: “semente”.
====

[[v23-43-6]]

^<<v23-43-6,6>>^ Direi ao norte: ‘Entrega-os!’
E ao sul: ‘Não os retenhas.
Traz os meus filhos de longe, e as minhas filhas, dos confins da terra,

[[v23-43-7]]

^<<v23-43-7,7>>^ Todo aquele que é chamado pelo meu nome
E que eu criei para a minha glória,
Que eu formei e fiz.’

[[v23-43-8]]

^<<v23-43-8,8>>^ Faz sair um povo que é cego, embora tenham olhos,
E que é surdo, embora tenham ouvidos.

[[v23-43-9]]

^<<v23-43-9,9>>^ Que todas as nações se reúnam num só lugar,
E que os povos sejam reunidos.
Quem dentre eles^&#42;1^ pode anunciar isto?
Quem é que nos pode revelar as primeiras coisas?^&#42;2^
Que apresente as suas testemunhas, para provar que está certo;
Que ouçam e digam: ‘É verdade!’”

[NOTE]
====
. Pelos vistos, refere-se a deuses falsos.
. Possivelmente, refere-se às primeiras coisas que acontecerão no futuro.
====

[[v23-43-10]]

^<<v23-43-10,10>>^ “Vocês são as minhas testemunhas”, diz Jeová,
“Sim, o meu servo a quem escolhi,
Para que me conheçam e tenham fé em mim,^&#42;1^
E entendam que eu sou o mesmo.
Antes de mim não foi formado nenhum Deus
E depois de mim continuou a não haver nenhum.

[NOTE]
====
. Ou: “e confiem em mim”.
====

[[v23-43-11]]

^<<v23-43-11,11>>^ Eu sou Jeová, e além de mim não há salvador.”

[[v23-43-12]]

^<<v23-43-12,12>>^ “Eu anunciei, salvei e divulguei isso
Quando não havia nenhum deus estrangeiro no vosso meio.
Portanto, vocês são as minhas testemunhas”, diz Jeová, “e eu sou Deus.

[[v23-43-13]]

^<<v23-43-13,13>>^ Além disso, sou sempre o mesmo;
E ninguém pode arrancar nada da minha mão.
Quando eu faço algo, quem o pode impedir?”

[[v23-43-14]]

^<<v23-43-14,14>>^ Assim diz Jeová, o vosso Resgatador, o Santo de Israel:
“Por vossa causa enviarei alguém a Babilónia e farei cair todas as trancas dos portões,
E os caldeus, nos seus navios, clamarão de aflição.

[[v23-43-15]]

^<<v23-43-15,15>>^ Eu sou Jeová, o vosso Santo, o Criador de Israel, o vosso Rei.”

[[v23-43-16]]

^<<v23-43-16,16>>^ Assim diz Jeová,
Aquele que abre um caminho através do mar
E uma passagem através de águas agitadas,

[[v23-43-17]]

^<<v23-43-17,17>>^ Aquele que faz sair o carro de guerra e o cavalo,
O exército e os guerreiros valentes:
“Eles cairão e não se levantarão.
Serão extintos, apagados como a chama de um pavio.”

[[v23-43-18]]

^<<v23-43-18,18>>^ “Esqueçam-se das coisas anteriores,
E não fiquem a pensar no passado.

[[v23-43-19]]

^<<v23-43-19,19>>^ Vejam! Farei algo novo;
Já está a acontecer.
Não percebem?
Abrirei um caminho através do ermo
E rios através do deserto.

[[v23-43-20]]

^<<v23-43-20,20>>^ Os animais selvagens irão honrar-me,
Sim, os chacais e as avestruzes,
Porque fornecerei água no ermo,
Rios no deserto,
Para que o meu povo, o meu escolhido, beba,

[[v23-43-21]]

^<<v23-43-21,21>>^ O povo que formei para mim
Para que proclamasse o meu louvor.

[[v23-43-22]]

^<<v23-43-22,22>>^ Mas tu não me invocaste, ó Jacó,
Porque te fartaste de mim, ó Israel.

[[v23-43-23]]

^<<v23-43-23,23>>^ Tu não me trouxeste ovelhas para as ofertas queimadas,
Nem me glorificaste com os teus sacrifícios.
Não te obriguei a trazer-me dádivas,
Nem te cansei exigindo olíbano.

[[v23-43-24]]

^<<v23-43-24,24>>^ Não compraste cálamo^&#42;1^ para mim com o teu dinheiro,
Nem me saciaste com a gordura dos teus sacrifícios.
Pelo contrário, sobrecarregaste-me com os teus pecados
E cansaste-me com os teus erros.

[NOTE]
====
. Uma cana aromática.
====

[[v23-43-25]]

^<<v23-43-25,25>>^ Eu sou aquele que apaga as tuas transgressões^&#42;1^ por minha própria causa,
E não me lembrarei dos teus pecados.

[NOTE]
====
. Ou: “os teus atos rebeldes”.
====

[[v23-43-26]]

^<<v23-43-26,26>>^ Vamos confrontar-nos em julgamento. Lembra-me,
Apresenta os teus argumentos para provar que tens razão.

[[v23-43-27]]

^<<v23-43-27,27>>^ O teu primeiro pai pecou,
E os teus próprios porta-vozes^&#42;1^ rebelaram-se contra mim.

[NOTE]
====
. Possivelmente, refere-se aos instrutores da Lei.
====

[[v23-43-28]]

^<<v23-43-28,28>>^ Portanto, profanarei os príncipes do lugar santo,
E vou entregar Jacó à destruição
E sujeitar Israel a insultos.

'''

xref:023-isaias/023-isaias-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaias/023-isaias-044.adoc#v23-44-0[Próximo Capítulo &#62;]