include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-57-1]]

^<<v23-57-1,1>>^ O justo morre,
Mas ninguém se importa.
Os homens leais estão a perecer;
Mas ninguém discerne que o justo morre
Por causa da^&#42;1^ calamidade.

[NOTE]
====
. Ou, possivelmente: “Para não ver a”.
====

[[v23-57-2]]

^<<v23-57-2,2>>^ Ele entra na paz.
Todo aquele que anda em retidão encontra descanso na sepultura.^&#42;1^

[NOTE]
====
. Lit.: “nas suas camas”.
====

[[v23-57-3]]

^<<v23-57-3,3>>^ “Mas, quanto a vocês, aproximem-se,
Filhos de uma feiticeira,
Filhos de um adúltero e de uma prostituta:

[[v23-57-4]]

^<<v23-57-4,4>>^ De quem é que estão a fazer troça?
De quem é que estão a fazer pouco,^&#42;1^ mostrando a língua?
Não são vocês filhos da transgressão,
Filhos da mentira,

[NOTE]
====
. Ou: “Contra quem é que escancaram a boca”.
====

[[v23-57-5]]

^<<v23-57-5,5>>^ Os que ardem de paixão entre as árvores grandes,
Debaixo de todas as árvores frondosas,
E que assassinam os filhos nos vales,^&#42;1^
Debaixo de penhascos salientes?

[NOTE]
====
. Ou: “uádis”.
====

[[v23-57-6]]

^<<v23-57-6,6>>^ As pedras lisas dos vales^&#42;1^ são a tua porção,
Sim, a parte que te cabe.
Foi sobre elas que derramaste ofertas de bebida e ofereceste dádivas.
Deveria eu ficar satisfeito^&#42;2^ com estas coisas?

[NOTE]
====
. Ou: “uádis”.
. Ou: “consolar-me”.
====

[[v23-57-7]]

^<<v23-57-7,7>>^ Colocaste a tua cama sobre um monte alto e elevado,
E subiste até lá para oferecer sacrifícios.

[[v23-57-8]]

^<<v23-57-8,8>>^ Colocaste o teu símbolo idólatra^&#42;1^ atrás da porta e da ombreira.
Abandonaste-me e despiste-te,
Subiste e ampliaste a tua cama.
Fizeste um pacto com eles.
Gostaste de dividir a cama com eles,
E contemplaste o órgão masculino.^&#42;2^

[NOTE]
====
. Ou: “a tua recordação”.
. Possivelmente, refere-se à adoração idólatra.
====

[[v23-57-9]]

^<<v23-57-9,9>>^ Desceste a Meleque^&#42;1^ com óleo
E com muitos perfumes;
Mandaste os teus mensageiros para longe,
De modo que desceste à Sepultura.^&#42;2^

[NOTE]
====
. Ou, possivelmente: “ao rei”.
. Ou: “ao Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v23-57-10]]

^<<v23-57-10,10>>^ Empenhaste-te em seguir os teus muitos caminhos,
Mas não disseste: ‘Não há esperança!’
Recuperaste as forças;
É por isso que não desistes.^&#42;1^

[NOTE]
====
. Lit.: “não te fatigas”.
====

[[v23-57-11]]

^<<v23-57-11,11>>^ De quem é que tiveste medo e pavor,
De modo que começaste a mentir?
Não te lembraste de mim,
Não fizeste caso.
Não me mantive calado e distante?^&#42;1^
Por isso não demonstraste temor de mim.

[NOTE]
====
. Ou: “e ocultei as coisas”.
====

[[v23-57-12]]

^<<v23-57-12,12>>^ Exporei a tua ‘justiça’ e as tuas obras,
E não te serão de nenhum proveito.

[[v23-57-13]]

^<<v23-57-13,13>>^ Quando gritares por socorro,
Os ídolos que juntaste não te salvarão.
O vento irá levá-los a todos,
Um simples sopro também os levará,
Mas aquele que se refugiar em mim herdará esta terra
E tomará posse do meu santo monte.

[[v23-57-14]]

^<<v23-57-14,14>>^ E há de dizer-se: ‘Construam, construam uma estrada! Preparem o caminho!
Removam todos os obstáculos do caminho do meu povo.’”

[[v23-57-15]]

^<<v23-57-15,15>>^ Pois assim diz o Enaltecido e Elevado,
Que vive^&#42;1^ para sempre e cujo nome é santo:
“Eu resido no lugar alto e santo,
Mas também com os esmagados e humildes de espírito,
Para reanimar o espírito dos humildes
E para reanimar o coração dos que estão a ser esmagados.

[NOTE]
====
. Ou: “reside”.
====

[[v23-57-16]]

^<<v23-57-16,16>>^ Pois não me vou opor a eles eternamente,
Nem ficarei sempre indignado;
Pois por minha causa o espírito do homem enfraqueceria,
E também as criaturas que respiram, que eu criei.

[[v23-57-17]]

^<<v23-57-17,17>>^ Fiquei indignado com o seu pecado, a sua busca por lucro desonesto,
Por isso golpeei-o, escondi a minha face e fiquei indignado.
Mas ele continuou a andar como um rebelde, seguindo o caminho do seu coração.

[[v23-57-18]]

^<<v23-57-18,18>>^ Vi os seus caminhos,
Mas irei curá-lo e guiá-lo,
E irei dar-lhe novamente^&#42;1^ consolo, a ele e aos que choram no seu meio.”

[NOTE]
====
. Ou: “compensá-lo com”.
====

[[v23-57-19]]

^<<v23-57-19,19>>^ “Vou criar o fruto dos lábios.
Darei contínua paz aos que estão longe e aos que estão perto”, diz Jeová,
“E vou curá-los”.

[[v23-57-20]]

^<<v23-57-20,20>>^ “Mas os maus são como o mar agitado que não se acalma,
E as suas águas expelem algas e lama.

[[v23-57-21]]

^<<v23-57-21,21>>^ Não há paz para os que são maus”, diz o meu Deus.

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]