include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-5-1]]

^<<v23-5-1,1>>^ Cantarei para o meu amado
Uma canção sobre o meu amado e a sua vinha:
O meu amado tinha uma vinha numa encosta fértil.

[[v23-5-2]]

^<<v23-5-2,2>>^ Revolveu a terra e tirou-lhe as pedras.
Plantou uma videira seleta de uvas vermelhas,
Construiu uma torre no meio dela
E escavou lá um lagar.
Então, ficou à espera que produzisse uvas boas,
Mas produziu apenas uvas bravas.

[[v23-5-3]]

^<<v23-5-3,3>>^ “E agora, habitantes de Jerusalém e homens de Judá,
Por favor, julguem entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ O que mais poderia eu fazer pela minha vinha
Que eu já não tenha feito?
Porque é que, quando esperei que produzisse uvas boas,
Ela produziu apenas uvas bravas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Agora vou dizer-vos
O que farei à minha vinha:
Vou remover-lhe a cerca,
E será queimada.
Vou derrubar-lhe o muro de pedras,
E será pisada.

[[v23-5-6]]

^<<v23-5-6,6>>^ Farei dela um terreno baldio;
Não será podada nem cavada.
Ficará coberta de espinhos e ervas daninhas,
E darei ordem às nuvens para que não derramem chuva sobre ela.

[[v23-5-7]]

^<<v23-5-7,7>>^ Porque a vinha de Jeová dos exércitos é a casa de Israel;
Os homens de Judá são a plantação de que ele gostava.
Ficou à espera de justiça,
Mas havia injustiça;
Ficou à espera de retidão,
Mas havia gritos de aflição.”

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai dos que juntam uma casa a outra
E dos que anexam um campo a outro
Até não haver mais espaço
E só vocês morarem nesta terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ Eu ouvi Jeová dos exércitos jurar
Que muitas casas, embora grandes e belas,
Irão tornar-se uma ruína que causa medo,
Sem nenhum morador.

[[v23-5-10]]

^<<v23-5-10,10>>^ Pois dez jeiras^&#42;1^ de vinha produzirão apenas um bato^&#42;2^ de vinho,
E um hómer^&#42;3^ de semente produzirá apenas uma efa^&#42;4^ de cereais.

[NOTE]
====
. Lit.: “dez juntas”. Uma jeira equivalia à extensão de terra que uma junta de bois podia arar num dia.
. Veja o Ap. B14.
. Veja o Ap. B14.
. Veja o Ap. B14.
====

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam de manhã cedo para tomar bebidas alcoólicas,
Que ficam até tarde na noite, até que o vinho os deixa exaltados!

[[v23-5-12]]

^<<v23-5-12,12>>^ Nos seus banquetes há harpas, instrumentos de cordas,
Pandeiretas, flautas e vinho;
Mas eles não refletem nos atos de Jeová,
Nem veem o trabalho das Suas mãos.

[[v23-5-13]]

^<<v23-5-13,13>>^ Por isso, o meu povo irá para o exílio
Por falta de conhecimento;
Os seus gloriosos passarão fome,
E todo o povo ficará seco de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Por isso, a Sepultura^&#42;1^ ampliou-se a si mesma^&#42;2^
E escancarou a boca além dos limites;
E certamente descerão até ela
O esplendor^&#42;3^ de Jerusalém, a sua multidão barulhenta e os seus foliões.

[NOTE]
====
. Ou: “o Seol”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. Ou: “ampliou a sua alma”.
. Ou: “Os nobres”.
====

[[v23-5-15]]

^<<v23-5-15,15>>^ E as pessoas serão rebaixadas,
As pessoas serão humilhadas,
E os olhos dos arrogantes serão humilhados.

[[v23-5-16]]

^<<v23-5-16,16>>^ Jeová dos exércitos será enaltecido pelo seu julgamento;^&#42;1^
O verdadeiro Deus, o Santo, irá santificar-se através da justiça.

[NOTE]
====
. Ou: “pela sua justiça”.
====

[[v23-5-17]]

^<<v23-5-17,17>>^ E os cordeiros pastarão ali como se estivessem na sua pastagem;
Os residentes estrangeiros comerão nos lugares desolados onde antes havia animais bem alimentados.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que arrastam a sua culpa com cordas de falsidade
E o seu pecado com cordas de carroça;

[[v23-5-19]]

^<<v23-5-19,19>>^ E dizem: “Que Ele apresse a sua obra,
Que ela chegue rapidamente, para que a vejamos.
Que o propósito^&#42;1^ do Santo de Israel se cumpra,
Para que o conheçamos!”

[NOTE]
====
. Ou: “a decisão; a vontade”.
====

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que dizem que o bom é mau e que o mau é bom,
Os que põem a escuridão no lugar da luz e a luz no lugar da escuridão,
Os que trocam o amargo pelo doce e o doce pelo amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios aos seus próprios olhos
E sensatos^&#42;1^ do seu ponto de vista!

[NOTE]
====
. Ou: “prudentes”.
====

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são fortes para beber vinho
E dos que são mestres em misturar bebidas alcoólicas,

[[v23-5-23]]

^<<v23-5-23,23>>^ Que inocentam o culpado em troca de suborno
E que negam justiça ao justo!

[[v23-5-24]]

^<<v23-5-24,24>>^ Portanto, assim como a labareda de fogo consome a palha,
E a erva seca se desfaz nas chamas,
As suas raízes apodrecerão,
E as suas flores irão espalhar-se como poeira,
Porque rejeitaram a lei^&#42;1^ de Jeová dos exércitos
E desrespeitaram a palavra do Santo de Israel.

[NOTE]
====
. Ou: “instrução”.
====

[[v23-5-25]]

^<<v23-5-25,25>>^ É por isso que a ira de Jeová arde contra o seu povo,
E ele irá estender a mão contra eles e golpeá-los.
Os montes tremerão,
E os seus cadáveres ficarão como lixo nas ruas.
Em vista de tudo isto, a Sua ira não recuou,
A sua mão ainda está estendida para golpear.

[[v23-5-26]]

^<<v23-5-26,26>>^ Ele ergueu um sinal^&#42;1^ para uma nação distante,
Assobiou para que viessem dos confins da terra.
E vejam! Estão a vir velozmente.

[NOTE]
====
. Ou: “poste de sinal”.
====

[[v23-5-27]]

^<<v23-5-27,27>>^ Entre eles não há ninguém que esteja cansado nem que tropece.
Ninguém está sonolento nem dorme.
Os seus cintos não estão frouxos na cintura,
Nem os cordões das suas sandálias estão rebentados.

[[v23-5-28]]

^<<v23-5-28,28>>^ Todas as suas flechas estão afiadas
E todos os seus arcos estão prontos para atirar.
Os cascos dos seus cavalos são como pedra,^&#42;1^
E as suas rodas como um furacão.

[NOTE]
====
. Ou: “pederneira”.
====

[[v23-5-29]]

^<<v23-5-29,29>>^ O seu rugido é como o do leão;
Rugem como leões novos.^&#42;1^
Rugirão e apanharão a presa
E irão levá-la sem ninguém para a salvar.

[NOTE]
====
. Ou: “leões novos jubados”.
====

[[v23-5-30]]

^<<v23-5-30,30>>^ Nesse dia rugirão sobre ela
Como o rugido do mar.
Quem olhar para esta terra verá uma escuridão aflitiva;
Até mesmo a luz terá escurecido por causa das nuvens.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]