include::./index.adoc[]

[[v23-39-0]]
=== Isaías, 39
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-39-1]]

^<<v23-39-1,1>>^ Naquele tempo, o rei de Babilónia, Merodaque-Baladã, filho de Baladã, enviou cartas e um presente a Ezequias, pois ouviu dizer que ele tinha ficado doente, mas já estava recuperado.

[[v23-39-2]]

^<<v23-39-2,2>>^ Ezequias recebeu-os com alegria^&#42;1^ e mostrou-lhes a sua casa do tesouro — a prata, o ouro, o óleo de bálsamo e outros óleos preciosos, todo o seu depósito de armas e tudo o que havia no seu tesouro. Não houve nada que Ezequias não lhes mostrasse na sua casa^&#42;2^ e em todo o seu domínio.

[NOTE]
====
. Lit.: “alegrou-se por causa deles”.
. Ou: “no seu palácio”.
====

[[v23-39-3]]

^<<v23-39-3,3>>^ Depois disso, o profeta Isaías foi ter com o rei Ezequias e perguntou-lhe: “O que é que esses homens disseram e de onde vieram?” Ezequias respondeu: “Vieram de uma terra distante, de Babilónia.”

[[v23-39-4]]

^<<v23-39-4,4>>^ Então, ele perguntou: “O que é que eles viram na tua casa?”^&#42;1^ Ezequias respondeu: “Viram tudo o que há na minha casa.^&#42;2^ Não há nada no meu tesouro que eu não lhes tenha mostrado.”

[NOTE]
====
. Ou: “no teu palácio”.
. Ou: “no meu palácio”.
====

[[v23-39-5]]

^<<v23-39-5,5>>^ Isaías disse então a Ezequias: “Ouve a palavra de Jeová dos exércitos:

[[v23-39-6]]

^<<v23-39-6,6>>^ ‘Vê, virão dias em que tudo o que há na tua casa^&#42;1^ e tudo o que os teus antepassados acumularam até ao dia de hoje será levado para Babilónia. Não sobrará nada’, diz Jeová.

[NOTE]
====
. Ou: “no teu palácio”.
====

[[v23-39-7]]

^<<v23-39-7,7>>^ ‘E alguns dos teus filhos, dos quais te tornarás pai, serão levados cativos e irão tornar-se oficiais da corte no palácio do rei de Babilónia.’”

[[v23-39-8]]

^<<v23-39-8,8>>^ Então, Ezequias disse a Isaías: “A palavra de Jeová que transmitiste é boa.” E acrescentou: “Porque haverá paz e estabilidade^&#42;1^ enquanto eu viver.”^&#42;2^

[NOTE]
====
. Ou: “verdade”.
. Lit.: “nos meus dias”.
====

'''

xref:023-isaias/023-isaias-038.adoc#v23-38-0[&#60; Capítulo Anterior] | <<v23-39-0,Topo>> | xref:023-isaias/023-isaias-040.adoc#v23-40-0[Próximo Capítulo &#62;]