include::./index.adoc[]

[[v23-54-0]]
=== Isaías, 54
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-54-1]]

^<<v23-54-1,1>>^ “Grita de alegria, ó mulher estéril, que não deste à luz!
Fica animada e grita de alegria, tu que nunca tiveste dores de parto,
Pois os filhos da mulher abandonada são mais numerosos
Do que os filhos da mulher que tem marido”,^&#42;1^ diz Jeová.

[NOTE]
====
. Ou: “um senhor”.
====

[[v23-54-2]]

^<<v23-54-2,2>>^ “Aumenta o espaço da tua tenda.
Estende os panos da tua grandiosa tenda.
Não te refreies, alonga as cordas
E fixa bem as estacas.

[[v23-54-3]]

^<<v23-54-3,3>>^ Pois irás expandir-te para a direita e para a esquerda.
Os teus descendentes tomarão posse de nações,
E habitarão as cidades desoladas.

[[v23-54-4]]

^<<v23-54-4,4>>^ Não tenhas medo, pois não serás envergonhada;
E não te sintas humilhada, pois não ficarás desapontada.
Porque te esquecerás da vergonha da tua juventude
E não te lembrarás mais da humilhação da tua viuvez.”

[[v23-54-5]]

^<<v23-54-5,5>>^ “Pois o Grandioso que te fez é como um marido^&#42;1^ para ti,
Jeová dos exércitos é o seu nome.
O Santo de Israel é o teu Resgatador.
Ele será chamado Deus de toda a terra.

[NOTE]
====
. Ou: “senhor”.
====

[[v23-54-6]]

^<<v23-54-6,6>>^ Pois Jeová chamou-te de volta como se fosses uma esposa abandonada e angustiada,^&#42;1^
Como uma esposa que se casou jovem e depois foi rejeitada”, diz o teu Deus.

[NOTE]
====
. Lit.: “de espírito magoado”.
====

[[v23-54-7]]

^<<v23-54-7,7>>^ “Por um breve instante te abandonei,
Mas com grande misericórdia irei trazer-te de volta.

[[v23-54-8]]

^<<v23-54-8,8>>^ Numa onda de indignação escondi de ti a minha face por um instante,
Mas com eterno amor leal terei misericórdia de ti”, diz o teu Resgatador, Jeová.

[[v23-54-9]]

^<<v23-54-9,9>>^ “Para mim, isto é como nos dias de Noé.
Assim como jurei que as águas de Noé nunca mais cobririam a terra,
Juro que nunca mais ficarei indignado contigo nem te censurarei.

[[v23-54-10]]

^<<v23-54-10,10>>^ Pois os montes podem ser removidos,
E as colinas podem ser abaladas,
Mas o meu amor leal não será removido de ti,
Nem o meu pacto de paz será abalado”, diz Jeová, aquele que tem misericórdia de ti.

[[v23-54-11]]

^<<v23-54-11,11>>^ “Ó mulher atribulada, sacudida pela tempestade e não consolada!
Vou assentar as tuas pedras com argamassa
E lançar o teu alicerce com safiras.

[[v23-54-12]]

^<<v23-54-12,12>>^ Vou fazer as tuas ameias de rubis,
Os teus portões, de pedras brilhantes,^&#42;1^
E todos os teus marcos divisórios, de pedras preciosas.

[NOTE]
====
. Ou: “pedras de fogo”.
====

[[v23-54-13]]

^<<v23-54-13,13>>^ Todos os teus filhos serão ensinados por Jeová,
E a paz dos teus filhos será abundante.

[[v23-54-14]]

^<<v23-54-14,14>>^ Serás firmemente alicerçada na justiça.
Estarás bem longe da opressão,
Não temerás nada nem terás motivo para terror,
Porque este não se aproximará de ti.

[[v23-54-15]]

^<<v23-54-15,15>>^ Se alguém te atacar,
Não será às minhas ordens.
Quem te atacar será derrotado por tua causa.”

[[v23-54-16]]

^<<v23-54-16,16>>^ “Eu mesmo criei o ferreiro,^&#42;1^
Que sopra as brasas
E produz uma arma como resultado do seu trabalho.
Também criei o destruidor para trazer ruína.

[NOTE]
====
. Ou: “artesão”.
====

[[v23-54-17]]

^<<v23-54-17,17>>^ Nenhuma arma feita contra ti será bem-sucedida,
E condenarás toda a língua que te acusar num julgamento.
Esta é a herança dos servos de Jeová,
E a justiça deles procede de mim”, diz Jeová.

'''

xref:023-isaias/023-isaias-053.adoc#v23-53-0[&#60; Capítulo Anterior] | <<v23-54-0,Topo>> | xref:023-isaias/023-isaias-055.adoc#v23-55-0[Próximo Capítulo &#62;]