include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-20-1]]

^<<v23-20-1,1>>^ No ano em que o rei Sargão, da Assíria, enviou o Tartã^&#42;1^ a Asdode, este lutou contra Asdode e conquistou-a.

[NOTE]
====
. Ou: “o comandante”.
====

[[v23-20-2]]

^<<v23-20-2,2>>^ Naquele tempo, Jeová disse por meio de Isaías, filho de Amoz: “Vai, tira a serapilheira^&#42;1^ das tuas ancas e tira as sandálias dos teus pés.” Ele assim fez, e passou a andar nu^&#42;2^ e descalço.

[NOTE]
====
. Veja o Glossário.
. Ou: “pouco vestido”.
====

[[v23-20-3]]

^<<v23-20-3,3>>^ Então, Jeová disse: “Assim como o meu servo Isaías tem andado nu e descalço durante três anos como sinal e como aviso do que vai acontecer ao Egito e à Etiópia,

[[v23-20-4]]

^<<v23-20-4,4>>^ da mesma maneira o rei da Assíria conduzirá os cativos egípcios e os exilados da Etiópia, rapazes e homens idosos, nus e descalços, com as nádegas expostas — para a vergonha^&#42;1^ do Egito.

[NOTE]
====
. Lit.: “— a nudez”.
====

[[v23-20-5]]

^<<v23-20-5,5>>^ E os que colocavam a sua esperança na Etiópia e que se orgulhavam^&#42;1^ do Egito ficarão apavorados e envergonhados.

[NOTE]
====
. Ou: “que admiravam a beleza”.
====

[[v23-20-6]]

^<<v23-20-6,6>>^ Os habitantes deste litoral dirão nesse dia: ‘Vê o que aconteceu àquele em quem colocámos a nossa esperança, para quem fugimos em busca de ajuda para sermos livrados do rei da Assíria! Como escaparemos agora?’”

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]