include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-3-1]]

^<<v23-3-1,1>>^ Pois vejam! O verdadeiro Senhor, Jeová dos exércitos,
Vai remover de Jerusalém e de Judá todo o tipo de sustento e apoio,
Todo o sustento de pão e de água,

[[v23-3-2]]

^<<v23-3-2,2>>^ O homem valente e o guerreiro,
O juiz e o profeta, o adivinho e o ancião,

[[v23-3-3]]

^<<v23-3-3,3>>^ O chefe de cinquenta, o governante e o conselheiro,
O perito em artes mágicas e o encantador hábil.

[[v23-3-4]]

^<<v23-3-4,4>>^ Farei com que meninos sejam os seus príncipes,
E os instáveis^&#42;1^ reinarão sobre eles.

[NOTE]
====
. Ou: “inconstantes”.
====

[[v23-3-5]]

^<<v23-3-5,5>>^ As pessoas irão oprimir-se umas às outras,
Cada uma ao seu próximo.
O jovem agredirá o idoso,
E o desprezado desafiará quem é respeitado.

[[v23-3-6]]

^<<v23-3-6,6>>^ Cada um agarrará o seu irmão na casa do seu pai e dirá:
“Tu tens um manto — sê o nosso governante.
Assume o controlo deste monte de ruínas.”

[[v23-3-7]]

^<<v23-3-7,7>>^ Contudo, ele responderá nesse dia:
“Não enfaixarei as tuas feridas;^&#42;1^
Não tenho comida nem roupa na minha casa.
Não me façam governante sobre o povo.”

[NOTE]
====
. Ou: “Não serei o teu médico”.
====

[[v23-3-8]]

^<<v23-3-8,8>>^ Pois Jerusalém tropeçou
E Judá caiu,
Porque em palavras e ações eles são contra Jeová;
Comportam-se com rebeldia na sua gloriosa presença.^&#42;1^

[NOTE]
====
. Lit.: “aos olhos da sua glória”.
====

[[v23-3-9]]

^<<v23-3-9,9>>^ A expressão do rosto deles dá testemunho contra eles.
Proclamam o seu pecado como Sodoma;
Não o tentam esconder.
Ai deles,^&#42;1^ pois estão a trazer desgraça sobre si mesmos!

[NOTE]
====
. Ou: “da sua alma”.
====

[[v23-3-10]]

^<<v23-3-10,10>>^ Digam aos justos que tudo lhes correrá bem;
Serão recompensados pelo que fazem.^&#42;1^

[NOTE]
====
. Lit.: “Comerão o fruto das suas ações”.
====

[[v23-3-11]]

^<<v23-3-11,11>>^ Ai dos maus!
A desgraça virá sobre eles,
Pois o que fizeram com as suas mãos ser-lhes-á feito a eles.

[[v23-3-12]]

^<<v23-3-12,12>>^ O meu povo é oprimido pelos seus feitores,
E mulheres dominam sobre eles.
Ó meu povo, os teus líderes fazem-te vaguear,
E confundem o teu caminho.

[[v23-3-13]]

^<<v23-3-13,13>>^ Jeová toma posição para acusar;
Levanta-se para sentenciar povos.

[[v23-3-14]]

^<<v23-3-14,14>>^ Jeová condenará os anciãos e os príncipes do Seu povo.
“Vocês queimaram a vinha,
E o que roubaram do pobre está nas vossas casas.

[[v23-3-15]]

^<<v23-3-15,15>>^ Como ousam esmagar o meu povo
E esmigalhar o rosto dos pobres no pó?”, diz o Soberano Senhor, Jeová dos exércitos.

[[v23-3-16]]

^<<v23-3-16,16>>^ Jeová diz: “Visto que as filhas de Sião são arrogantes,
Andam de cabeça erguida,^&#42;1^
Seduzem com os olhos, dão passinhos
E fazem um som tilintante com os enfeites dos tornozelos,

[NOTE]
====
. Lit.: “de pescoço (garganta) esticado(a)”.
====

[[v23-3-17]]

^<<v23-3-17,17>>^ Jeová fará a cabeça das filhas de Sião ficar cheia de crostas,
E Jeová exporá a testa delas.

[[v23-3-18]]

^<<v23-3-18,18>>^ Nesse dia, Jeová irá tirar-lhes todos os adornos: as argolas dos tornozelos,
As faixas para a cabeça, os enfeites em forma de meia-lua,

[[v23-3-19]]

^<<v23-3-19,19>>^ Os brincos,^&#42;1^ as pulseiras, os véus,

[NOTE]
====
. Ou: “pingentes”.
====

[[v23-3-20]]

^<<v23-3-20,20>>^ As coberturas para a cabeça, as correntes dos tornozelos, as faixas,^&#42;1^
Os frascos de perfume,^&#42;2^ os amuletos,^&#42;3^

[NOTE]
====
. Ou: “faixas para o busto”.
. Lit.: “As casas da alma”.
. Ou: “as conchas ornamentais que fazem um zumbido”.
====

[[v23-3-21]]

^<<v23-3-21,21>>^ Os anéis, as argolas para o nariz,

[[v23-3-22]]

^<<v23-3-22,22>>^ Os trajes de gala, as capas, os mantos, as bolsas,

[[v23-3-23]]

^<<v23-3-23,23>>^ Os espelhos de mão, as roupas de linho,^&#42;1^
Os turbantes e os véus.

[NOTE]
====
. Ou: “as túnicas”.
====

[[v23-3-24]]

^<<v23-3-24,24>>^ “Em vez de óleo de bálsamo haverá mau cheiro;
Em vez de um cinto, uma corda;
Em vez de belos penteados, calvície;
Em vez de roupa luxuosa, roupa feita de serapilheira;^&#42;1^
E em vez de beleza, uma marca de ferro em brasa.

[NOTE]
====
. Veja o Glossário.
====

[[v23-3-25]]

^<<v23-3-25,25>>^ Os teus homens cairão pela espada;
E os valentes, na batalha.

[[v23-3-26]]

^<<v23-3-26,26>>^ Os portões dela ficarão de luto e expressarão tristeza,
E ela irá sentar-se no chão, desolada.”

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]