include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v23-42-1]]

^<<v23-42-1,1>>^ Vejam o meu servo, a quem apoio!
O meu escolhido, a quem aprovo!^&#42;1^
Pus nele o meu espírito;
Ele trará justiça às nações.

[NOTE]
====
. Ou: “a quem a minha alma aprova”.
====

[[v23-42-2]]

^<<v23-42-2,2>>^ Não gritará nem levantará a voz,
Não fará a sua voz ser ouvida na rua.

[[v23-42-3]]

^<<v23-42-3,3>>^ Não quebrará nenhuma cana esmagada,
Nem apagará um pavio que ainda esteja a fumegar.
Em fidelidade trará a justiça.

[[v23-42-4]]

^<<v23-42-4,4>>^ A sua luz não enfraquecerá e não será esmagado até estabelecer a justiça na terra;
As ilhas esperam pela sua lei.^&#42;1^

[NOTE]
====
. Ou: “instrução”.
====

[[v23-42-5]]

^<<v23-42-5,5>>^ Assim diz o verdadeiro Deus, Jeová,
O Criador dos céus e o Grandioso que os estendeu,
Aquele que estirou a terra e o que ela produz,
Aquele que dá fôlego aos seus habitantes
E espírito aos que andam nela:

[[v23-42-6]]

^<<v23-42-6,6>>^ “Eu, Jeová, chamei-te em justiça;
Peguei-te pela mão.
Irei proteger-te e dar-te como pacto para o povo
E como luz para as nações,

[[v23-42-7]]

^<<v23-42-7,7>>^ Para abrires os olhos dos cegos,
Para tirares o prisioneiro do calabouço,
E da prisão os que estão sentados na escuridão.

[[v23-42-8]]

^<<v23-42-8,8>>^ Eu sou Jeová. Este é o meu nome;
Não dou a minha glória a nenhum outro,^&#42;1^
Nem o meu louvor a imagens esculpidas.

[NOTE]
====
. Ou: “Não compartilho a minha glória com ninguém”.
====

[[v23-42-9]]

^<<v23-42-9,9>>^ Vejam, as primeiras coisas já aconteceram;
Agora, estou a anunciar coisas novas.
Antes que ocorram, revelo-as a vocês.”

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantem a Jeová um novo cântico!
Cantem-lhe louvores desde os confins da terra,
Vocês que navegam no mar e no meio de tudo o que nele existe;
Vocês, ilhas, e os seus habitantes.

[[v23-42-11]]

^<<v23-42-11,11>>^ Que o deserto e as suas cidades levantem a voz,
Também os povoados habitados por Quedar.
Gritem de alegria os habitantes do rochedo;
Gritem do cume dos montes.

[[v23-42-12]]

^<<v23-42-12,12>>^ Deem glória a Jeová
E proclamem nas ilhas o seu louvor.

[[v23-42-13]]

^<<v23-42-13,13>>^ Jeová sairá como um guerreiro.
Despertará o seu zelo como um homem de guerra.
Dará um grito, sim, dará um grito de guerra;
Ele irá mostrar-se mais poderoso do que os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ “Durante muito tempo fiquei quieto.
Fiquei calado e contive-me.
Como uma mulher que está a dar à luz,
Ao mesmo tempo vou gemer, ficar ofegante e perder o fôlego.

[[v23-42-15]]

^<<v23-42-15,15>>^ Devastarei montes e colinas,
E secarei toda a sua vegetação.
Vou transformar os rios em ilhas,^&#42;1^
E secarei as lagoas repletas de juncos.

[NOTE]
====
. Ou: “litorais”.
====

[[v23-42-16]]

^<<v23-42-16,16>>^ Conduzirei os cegos por um caminho que não conhecem,
E farei com que andem por veredas desconhecidas.
Transformarei a escuridão diante deles em luz,
E o terreno acidentado em terra plana.
Isto é o que vou fazer para eles e não os vou abandonar.”

[[v23-42-17]]

^<<v23-42-17,17>>^ Aqueles que confiam em imagens esculpidas
Serão obrigados a retroceder e serão completamente envergonhados,
Aqueles que dizem a estátuas de metal:^&#42;1^ “São os nossos deuses.”

[NOTE]
====
. Ou: “estátuas fundidas”.
====

[[v23-42-18]]

^<<v23-42-18,18>>^ Ouçam, ó surdos;
Olhem e vejam, ó cegos.

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é cego, senão o meu servo,
E tão surdo como o mensageiro que envio?
Quem é tão cego como aquele que foi recompensado,
Tão cego como o servo de Jeová?

[[v23-42-20]]

^<<v23-42-20,20>>^ Tu vês muitas coisas, mas não prestas atenção.
Os teus ouvidos estão abertos, mas não escutas.

[[v23-42-21]]

^<<v23-42-21,21>>^ Jeová, por causa da Sua justiça,
Teve prazer em magnificar a lei^&#42;1^ e torná-la gloriosa.

[NOTE]
====
. Ou: “instrução”.
====

[[v23-42-22]]

^<<v23-42-22,22>>^ Mas este é um povo que foi saqueado e roubado;
Todos estão presos em cavernas e escondidos em prisões.
Foram saqueados, sem que ninguém os livrasse,
Foram roubados, sem que ninguém dissesse: “Tragam-nos de volta!”

[[v23-42-23]]

^<<v23-42-23,23>>^ Quem dentre vocês ouvirá isso?
Quem prestará atenção e escutará, com o futuro em mente?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem entregou Jacó como despojo
E Israel aos saqueadores?
Não foi Jeová, aquele contra quem pecámos?
Eles recusaram-se a andar nos Seus caminhos
E não quiseram obedecer à Sua lei.^&#42;1^

[NOTE]
====
. Ou: “instrução”.
====

[[v23-42-25]]

^<<v23-42-25,25>>^ Portanto, Ele continuou a derramar sobre Israel a sua ira,
A sua indignação e a fúria da guerra.
Consumia tudo ao seu redor, mas ele não fez caso.
Ardia contra ele, mas ele não deu atenção.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]