include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-11-1]]

^<<v24-11-1,1>>^ Jeremias recebeu a seguinte palavra de Jeová:

[[v24-11-2]]

^<<v24-11-2,2>>^ “Ouçam as palavras deste pacto, ó povo!
“Transmite-as^&#42;1^ aos homens de Judá e aos habitantes de Jerusalém.

[NOTE]
====
. Esta ordem parece ser dirigida a Jeremias.
====

[[v24-11-3]]

^<<v24-11-3,3>>^ Diz-lhes: ‘Assim diz Jeová, o Deus de Israel: “Maldito o homem que não obedecer às palavras deste pacto,

[[v24-11-4]]

^<<v24-11-4,4>>^ que fiz com os seus antepassados no dia em que os tirei da terra do Egito, do forno de fundição de ferro, dizendo: ‘Obedeçam à minha voz e façam todas as coisas que vos ordeno, e irão tornar-se o meu povo, e eu serei o vosso Deus.

[[v24-11-5]]

^<<v24-11-5,5>>^ Dessa forma, eu poderei cumprir o juramento que fiz aos vossos antepassados, de dar-lhes a terra que mana leite e mel, como acontece hoje.’”’”
Então, respondi: “Amém,^&#42;1^ ó Jeová.”

[NOTE]
====
. Ou: “Assim seja”.
====

[[v24-11-6]]

^<<v24-11-6,6>>^ E Jeová disse-me: “Proclama todas estas palavras nas cidades de Judá e nas ruas de Jerusalém: ‘Ouçam as palavras deste pacto e cumpram-nas.

[[v24-11-7]]

^<<v24-11-7,7>>^ Pois adverti solenemente os vossos antepassados desde o dia em que os tirei da terra do Egito até hoje, dizendo-lhes vez após vez:^&#42;1^ “Obedeçam à minha voz.”

[NOTE]
====
. Lit.: “levantando-me cedo e advertindo”.
====

[[v24-11-8]]

^<<v24-11-8,8>>^ Contudo, eles não deram ouvidos nem prestaram atenção;^&#42;1^ em vez disso, cada um deles teimou em seguir o seu próprio coração mau. Por isso, trouxe sobre eles todas as palavras deste pacto ao qual lhes mandei obedecer e que eles se recusaram a cumprir.’”

[NOTE]
====
. Ou: “nem inclinaram o seu ouvido”.
====

[[v24-11-9]]

^<<v24-11-9,9>>^ Por conseguinte, Jeová disse-me: “Há uma conspiração entre os homens de Judá e os habitantes de Jerusalém.

[[v24-11-10]]

^<<v24-11-10,10>>^ Eles voltaram aos erros cometidos desde o começo pelos seus antepassados, que se recusaram a obedecer às minhas palavras. Também seguiram outros deuses e serviram-nos. A casa de Israel e a casa de Judá violaram o pacto que fiz com os seus antepassados.

[[v24-11-11]]

^<<v24-11-11,11>>^ Portanto, assim diz Jeová: ‘Vou trazer sobre eles uma calamidade da qual não poderão escapar. Quando clamarem por socorro, eu não os escutarei.

[[v24-11-12]]

^<<v24-11-12,12>>^ Então, as cidades de Judá e os habitantes de Jerusalém recorrerão aos deuses a que oferecem sacrifícios^&#42;1^ e clamarão por socorro, mas estes não os salvarão quando chegar a sua calamidade.

[NOTE]
====
. Ou: “fumo sacrificial”.
====

[[v24-11-13]]

^<<v24-11-13,13>>^ Pois os teus deuses tornaram-se tão numerosos como as tuas cidades, ó Judá; e tão numerosos como as ruas de Jerusalém são os altares que vocês fizeram para a coisa vergonhosa,^&#42;1^ altares para se fazerem sacrifícios a Baal.’

[NOTE]
====
. Ou: “o deus vergonhoso”.
====

[[v24-11-14]]

^<<v24-11-14,14>>^ “Quanto a ti,^&#42;1^ não ores por este povo. Não clames em seu favor nem ores por eles, pois não os ouvirei quando me clamarem por causa da calamidade que lhes há de sobrevir.

[NOTE]
====
. Isto é, Jeremias.
====

[[v24-11-15]]

^<<v24-11-15,15>>^ Que direito tem o meu povo amado^&#42;1^ de estar na minha casa,
Quando muitos agem conforme os seus planos malignos?
Será que, com carne sagrada,^&#42;2^ conseguirão impedir que a calamidade te sobrevenha?
Será que te vais alegrar nessa altura?

[NOTE]
====
. Ou: “a minha amada”.
. Isto é, sacrifícios feitos no templo.
====

[[v24-11-16]]

^<<v24-11-16,16>>^ Jeová chamava-te oliveira frondosa,
Bonita e com belos frutos.
Com um grande estrondo, ele deitou-lhe fogo;
E partiram-lhe os ramos.

[[v24-11-17]]

^<<v24-11-17,17>>^ “Jeová dos exércitos, aquele que te plantou, declarou que te sobrevirá uma calamidade, por causa da maldade cometida pela casa de Israel e pela casa de Judá, que me ofenderam por fazerem sacrifícios a Baal.”

[[v24-11-18]]

^<<v24-11-18,18>>^ Jeová informou-me para que eu soubesse;
Naquele tempo, mostraste-me o que eles estavam a fazer.

[[v24-11-19]]

^<<v24-11-19,19>>^ Eu era como um cordeiro manso que é levado para o abate.
Não sabia que eles conspiravam contra mim, dizendo:
“Vamos destruir a árvore com os seus frutos;
Vamos eliminá-lo da terra dos vivos
Para que o seu nome nunca mais seja lembrado.”

[[v24-11-20]]

^<<v24-11-20,20>>^ Contudo, Jeová dos exércitos julga com justiça;
Ele examina os pensamentos mais íntimos^&#42;1^ e o coração.
Que eu veja a tua vingança contra eles,
Pois foi a ti que confiei a minha causa.

[NOTE]
====
. Ou: “as emoções mais profundas”. Lit.: “os rins”.
====

[[v24-11-21]]

^<<v24-11-21,21>>^ Portanto, assim diz Jeová contra os homens de Anatote, que procuram tirar-me a vida^&#42;1^ e que dizem: “Não profetizes em nome de Jeová, senão vamos matar-te”;

[NOTE]
====
. Lit.: “procuram a tua alma”.
====

[[v24-11-22]]

^<<v24-11-22,22>>^ portanto, assim diz Jeová dos exércitos: “Vou ajustar contas com eles. Os jovens morrerão à espada, e os seus filhos e as suas filhas morrerão de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ Deles, não sobrará nem sequer um restante, porque trarei calamidade sobre os homens de Anatote no ano do ajuste de contas com eles.”

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]