include::./index.adoc[]

[[v24-51-0]]
=== Jeremias, 51
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-51-1]]

^<<v24-51-1,1>>^ Assim diz Jeová:
“Vou levantar um vento devastador
Contra Babilónia e os habitantes de Lebe-Camai.^&#42;1^

[NOTE]
====
. Este parece ser um criptograma para Caldeia.
====

[[v24-51-2]]

^<<v24-51-2,2>>^ Vou enviar a Babilónia homens que a espalharão;^&#42;1^
Irão espalhá-la e deixar a sua terra vazia,
Irão cercá-la por todos os lados no dia da calamidade.

[NOTE]
====
. Ou: “padejarão”.
====

[[v24-51-3]]

^<<v24-51-3,3>>^ Que o arqueiro não arme^&#42;1^ o seu arco.
Que ninguém se levante com a sua cota de malha.
Não tenham compaixão dos seus jovens.
Entreguem todo o seu exército à destruição.^&#42;2^

[NOTE]
====
. Lit.: “não pise”.
. Ou: “Devotem . . . à destruição.” Veja o Glossário.
====

[[v24-51-4]]

^<<v24-51-4,4>>^ Eles serão mortos na terra dos caldeus,
Trespassados nas suas ruas.

[[v24-51-5]]

^<<v24-51-5,5>>^ Pois Israel e Judá não são viúvas do seu Deus, Jeová dos exércitos.
Contudo, a sua terra^&#42;1^ está cheia de culpa do ponto de vista do Santo de Israel.

[NOTE]
====
. Isto é, a terra dos caldeus.
====

[[v24-51-6]]

^<<v24-51-6,6>>^ Fujam do meio de Babilónia
E salvem a vida!^&#42;1^
Não sejam mortos por causa dos erros dela.
Pois este é o tempo para a vingança de Jeová.
Ele vai retribuir-lhe o que ela fez.

[NOTE]
====
. Ou: “alma”.
====

[[v24-51-7]]

^<<v24-51-7,7>>^ Babilónia tem sido um cálice de ouro na mão de Jeová;
Ela embriagou toda a terra.
As nações beberam o seu vinho,
Por isso é que as nações ficaram loucas.

[[v24-51-8]]

^<<v24-51-8,8>>^ De repente, Babilónia caiu e ficou devastada.
Lamentem por ela!
Tragam bálsamo para a sua dor; talvez ela seja curada.”

[[v24-51-9]]

^<<v24-51-9,9>>^ “Tentámos curar Babilónia, mas ela não pôde ser curada.
Deixem-na e vamos, cada um para a sua própria terra.
Pois o seu julgamento chega até aos céus,
Sobe até às nuvens.

[[v24-51-10]]

^<<v24-51-10,10>>^ Jeová trouxe-nos justiça.
Venham, relatemos em Sião os atos de Jeová, nosso Deus.”

[[v24-51-11]]

^<<v24-51-11,11>>^ “Afiem as flechas; peguem nos escudos redondos.^&#42;1^
Jeová despertou o espírito dos reis dos medos,
Porque a sua intenção é destruir Babilónia.
Pois esta é a vingança de Jeová, a vingança pelo seu templo.

[NOTE]
====
. Ou, possivelmente: “encham as aljavas”.
====

[[v24-51-12]]

^<<v24-51-12,12>>^ Ergam um sinal^&#42;1^ contra as muralhas de Babilónia.
Reforcem a guarda, posicionem os vigias.
Ponham homens de emboscada.
Pois Jeová armou uma estratégia,
E ele cumprirá o que prometeu contra os habitantes de Babilónia.”

[NOTE]
====
. Ou: “poste de sinal”.
====

[[v24-51-13]]

^<<v24-51-13,13>>^ “Ó mulher que moras sobre muitas águas,
Rica em tesouros;
Chegou o teu fim, o limite^&#42;1^ do teu lucro.

[NOTE]
====
. Lit.: “a medida”.
====

[[v24-51-14]]

^<<v24-51-14,14>>^ Jeová dos exércitos jurou por si mesmo:^&#42;1^
‘Vou encher-vos de homens, tão numerosos como gafanhotos,
E eles gritarão vitória sobre ti.’

[NOTE]
====
. Ou: “pela sua alma”.
====

[[v24-51-15]]

^<<v24-51-15,15>>^ Ele é Aquele que fez a terra com o seu poder,
Aquele que estabeleceu o solo produtivo com a sua sabedoria,
E que estendeu os céus com o seu entendimento.

[[v24-51-16]]

^<<v24-51-16,16>>^ Quando ele faz ouvir a sua voz,
Agitam-se as águas nos céus,
E ele faz subir nuvens^&#42;1^ desde os confins da terra.
Faz os relâmpagos^&#42;2^ para a chuva
E faz o vento sair dos Seus depósitos.

[NOTE]
====
. Ou: “vapores”.
. Ou, possivelmente: “Faz comportas”.
====

[[v24-51-17]]

^<<v24-51-17,17>>^ Todos os homens agem de modo insensato e sem conhecimento.
Todos os ourives ficarão envergonhados por causa das suas imagens esculpidas,
Pois as suas imagens de metal^&#42;1^ são uma falsidade,
E não há espírito^&#42;2^ nelas.

[NOTE]
====
. Ou: “estátuas fundidas”.
. Ou: “fôlego”.
====

[[v24-51-18]]

^<<v24-51-18,18>>^ São uma ilusão,^&#42;1^ obras dignas de serem ridicularizadas.
Quando chegar o dia do seu ajuste de contas, elas desaparecerão.

[NOTE]
====
. Ou: “futilidade”.
====

[[v24-51-19]]

^<<v24-51-19,19>>^ A Porção de Jacó não é como essas coisas,
Pois foi Ele que formou tudo,
Sim, é o bastão da Sua herança.^&#42;1^
Jeová dos exércitos é o seu nome.”

[NOTE]
====
. Ou, possivelmente: “Pois foi Ele que formou até mesmo o bastão da Sua herança”.
====

[[v24-51-20]]

^<<v24-51-20,20>>^ “És, para mim, uma clava de guerra, uma arma para a batalha,
Pois, contigo, vou despedaçar nações,
Contigo, vou destruir reinos.

[[v24-51-21]]

^<<v24-51-21,21>>^ Contigo, vou despedaçar o cavalo e o seu cavaleiro,
Contigo, vou despedaçar o carro de guerra e o seu condutor.

[[v24-51-22]]

^<<v24-51-22,22>>^ Contigo, vou despedaçar homens e mulheres,
Contigo, vou despedaçar idosos e crianças,
Contigo, vou despedaçar rapazes e raparigas.

[[v24-51-23]]

^<<v24-51-23,23>>^ Contigo, vou despedaçar o pastor e o seu rebanho,
Contigo, vou despedaçar o lavrador e os seus animais de arado,
Contigo, vou despedaçar governadores e subgovernadores.

[[v24-51-24]]

^<<v24-51-24,24>>^ E vou retribuir a Babilónia e a todos os habitantes da Caldeia
Toda a maldade que eles cometeram em Sião diante dos vossos olhos”, diz Jeová.

[[v24-51-25]]

^<<v24-51-25,25>>^ “Eu estou contra ti, ó monte destruidor”, diz Jeová,
“Destruidor de toda a terra.
Vou estender a mão contra ti, vou fazer-te rolar pelo rochedo abaixo
E vou tornar-te um monte queimado”.

[[v24-51-26]]

^<<v24-51-26,26>>^ “Não te retirarão nenhuma pedra angular ou pedra de alicerce,
Pois ficarás desolado para sempre”, diz Jeová.

[[v24-51-27]]

^<<v24-51-27,27>>^ “Ergam um sinal^&#42;1^ na terra.^&#42;2^
Toquem a buzina entre as nações.
Designem^&#42;3^ as nações contra ela.
Convoquem contra ela os reinos de Ararate, de Mini e de Asquenaz.
Designem um oficial de recrutamento contra ela.
Façam vir os cavalos, como gafanhotos jovens.^&#42;4^

[NOTE]
====
. Ou: “poste de sinal”.
. Ou: “no país”.
. Lit.: “Santifiquem”.
. Ou: “eriçados”.
====

[[v24-51-28]]

^<<v24-51-28,28>>^ Designem^&#42;1^ as nações contra ela,
Os reis da Média, os seus governadores e todos os seus subgovernadores,
E todas as terras que eles dominam.

[NOTE]
====
. Lit.: “Santifiquem”.
====

[[v24-51-29]]

^<<v24-51-29,29>>^ A terra irá tremer e estremecer,
Pois os pensamentos de Jeová contra Babilónia serão executados,
Para fazer da terra de Babilónia um motivo de terror e deixá-la sem habitantes.

[[v24-51-30]]

^<<v24-51-30,30>>^ Os guerreiros de Babilónia pararam de lutar.
Estão sentados nas suas fortalezas.
Acabou-se a sua força.
Eles tornaram-se como mulheres.
As casas dela foram incendiadas.
As suas trancas foram destroçadas.

[[v24-51-31]]

^<<v24-51-31,31>>^ Um mensageiro corre para encontrar outro mensageiro,
E um emissário corre para encontrar outro emissário,
Para informar o rei de Babilónia de que a sua cidade foi conquistada a partir de todos os lados,

[[v24-51-32]]

^<<v24-51-32,32>>^ Que os pontos de travessia do rio foram tomados,
Que os barcos de papiro foram queimados com fogo,
E que os soldados estão apavorados.”

[[v24-51-33]]

^<<v24-51-33,33>>^ Pois assim diz Jeová dos exércitos, o Deus de Israel:
“A filha de Babilónia é como uma eira.
Está a chegar a hora de pisá-la duramente.
Muito em breve, o tempo da colheita chegará para ela.”

[[v24-51-34]]

^<<v24-51-34,34>>^ “Nabucodonosor,^&#42;1^ rei de Babilónia, devorou-me;
Ele lançou-me em confusão.
Reduziu-me a um jarro vazio.
Ele, como uma cobra grande, engoliu-me;
Encheu a sua barriga com as minhas coisas boas.
Ele deitou-me fora.^&#42;2^

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
. Ou: “removeu-me com água”.
====

[[v24-51-35]]

^<<v24-51-35,35>>^ ‘Que a violência praticada contra mim e a minha pessoa recaia sobre Babilónia!’, diz a habitante de Sião.
‘E que o meu sangue recaia sobre os habitantes da Caldeia!’, diz Jerusalém.”

[[v24-51-36]]

^<<v24-51-36,36>>^ Portanto, assim diz Jeová:
“Vou defender a tua causa,
E executar vingança a teu favor.
Vou secar o seu mar e os seus poços.

[[v24-51-37]]

^<<v24-51-37,37>>^ E Babilónia irá transformar-se num montão de pedras,
Um esconderijo de chacais,
Um motivo de terror e alvo de assobios,
Onde não haverá habitantes.

[[v24-51-38]]

^<<v24-51-38,38>>^ Todos eles rugirão como leões novos.^&#42;1^
Rosnarão como crias de leão.”

[NOTE]
====
. Ou: “leões novos jubados”.
====

[[v24-51-39]]

^<<v24-51-39,39>>^ “Quando estiverem exaltados, vou preparar-lhes um banquete e embriagá-los,
Para que se alegrem.
Depois, eles dormirão um sono permanente,
Do qual não acordarão”, diz Jeová.

[[v24-51-40]]

^<<v24-51-40,40>>^ “Vou matá-los como cordeiros levados ao abate,
Como carneiros e bodes.”

[[v24-51-41]]

^<<v24-51-41,41>>^ “Ó, como foi conquistada Sesaque!^&#42;1^
Como foi conquistada aquela que era louvada por todos!
Como Babilónia se tornou um motivo de terror entre as nações!

[NOTE]
====
. Este parece ser um criptograma para Babel (Babilónia).
====

[[v24-51-42]]

^<<v24-51-42,42>>^ O mar subiu contra Babilónia.
Cobriu-a com as suas ondas abundantes.

[[v24-51-43]]

^<<v24-51-43,43>>^ As suas cidades tornaram-se um motivo de terror, uma terra árida, um deserto.
Uma terra onde ninguém morará e por onde nenhum homem passará.

[[v24-51-44]]

^<<v24-51-44,44>>^ Voltarei a minha atenção para Bel em Babilónia
E vou tirar-lhe da boca o que ele engoliu.
As nações não voltarão a afluir a ele.
E a muralha de Babilónia cairá.

[[v24-51-45]]

^<<v24-51-45,45>>^ Saiam do meio dela, meu povo!
Salvem a vossa vida^&#42;1^ da ira ardente de Jeová!

[NOTE]
====
. Ou: “alma”.
====

[[v24-51-46]]

^<<v24-51-46,46>>^ Não desanimem nem tenham medo por causa das notícias que se ouvirão no país.
Num ano, chegará uma notícia
E, no ano seguinte, chegará outra notícia,
De violência na terra e de governante contra governante.

[[v24-51-47]]

^<<v24-51-47,47>>^ Portanto, estão a chegar os dias
Em que voltarei a minha atenção para as imagens esculpidas de Babilónia.
Toda a sua terra será envergonhada,
E todos os seus mortos cairão no meio dela.

[[v24-51-48]]

^<<v24-51-48,48>>^ Os céus, a terra e tudo o que há neles,
Gritarão de alegria por causa de Babilónia,
Pois os destruidores virão até ela do norte”, diz Jeová.

[[v24-51-49]]

^<<v24-51-49,49>>^ “Não foram somente os mortos de Israel que Babilónia fez cair,
Mas também caíram em Babilónia os mortos de toda a terra.

[[v24-51-50]]

^<<v24-51-50,50>>^ Vocês, os que escaparem da espada, continuem a andar, não parem!
Lá de longe, lembrem-se de Jeová
E tenham Jerusalém no coração.”

[[v24-51-51]]

^<<v24-51-51,51>>^ “Fomos envergonhados, pois ouvimos insultos.
A humilhação cobriu-nos o rosto,
Pois estrangeiros^&#42;1^ vieram contra os lugares santos da casa de Jeová.”

[NOTE]
====
. Ou: “estranhos”.
====

[[v24-51-52]]

^<<v24-51-52,52>>^ “Portanto, estão a chegar os dias”, diz Jeová,
“Em que voltarei a minha atenção para as suas imagens esculpidas
E, em toda a sua terra, os feridos gemerão”.

[[v24-51-53]]

^<<v24-51-53,53>>^ “Mesmo que Babilónia suba até aos céus,
Mesmo que fortifique as suas enormes fortalezas,
Chegarão até ela os destruidores que enviarei”, diz Jeová.

[[v24-51-54]]

^<<v24-51-54,54>>^ “Escutem! Ouvem-se gritos vindos de Babilónia,
O som de um grande desastre vindo da terra dos caldeus,

[[v24-51-55]]

^<<v24-51-55,55>>^ Pois Jeová está a destruir Babilónia,
Ele silenciará a sua forte voz.
As suas ondas ressoarão como muitas águas,
E ouvir-se-á o som da sua voz.

[[v24-51-56]]

^<<v24-51-56,56>>^ O destruidor virá sobre Babilónia;
Os seus guerreiros serão capturados.
Os seus arcos serão despedaçados,
Pois Jeová é um Deus de retribuição.
Ele retribuirá, sem falta.

[[v24-51-57]]

^<<v24-51-57,57>>^ Vou embriagar os seus príncipes e os seus sábios,
Os seus governadores, os seus subgovernadores e os seus guerreiros,
E eles dormirão um sono permanente,
Do qual não acordarão”, diz o Rei, cujo nome é Jeová dos exércitos.

[[v24-51-58]]

^<<v24-51-58,58>>^ Assim diz Jeová dos exércitos:
“A muralha de Babilónia, embora seja larga, será completamente demolida.
E os seus portões, embora sejam altos, serão queimados com fogo.
Os povos trabalharão arduamente em vão;
As nações hão de cansar-se só para alimentar o fogo.”

[[v24-51-59]]

^<<v24-51-59,59>>^ Esta é a ordem que o profeta Jeremias deu a Seraías, filho de Nerias, filho de Maseias, quando ele foi a Babilónia com Zedequias, rei de Judá, no quarto ano do seu reinado. Seraías era um dos oficiais do rei.^&#42;1^

[NOTE]
====
. Ou: “era o oficial intendente”.
====

[[v24-51-60]]

^<<v24-51-60,60>>^ Jeremias escreveu num livro toda a calamidade que sobreviria a Babilónia, todas estas palavras escritas contra Babilónia.

[[v24-51-61]]

^<<v24-51-61,61>>^ Além disso, Jeremias disse a Seraías: “Quando estiveres a chegar a Babilónia e a avistares, lê em voz alta todas estas palavras.

[[v24-51-62]]

^<<v24-51-62,62>>^ E diz: ‘Ó Jeová, tu disseste que este lugar será destruído e deixado sem habitantes, sem homens nem animais, e que ela ficará desolada para sempre.’

[[v24-51-63]]

^<<v24-51-63,63>>^ E, quando acabares de ler este livro, amarra-lhe uma pedra e atira-o ao rio Eufrates.

[[v24-51-64]]

^<<v24-51-64,64>>^ De seguida, diz: ‘Assim se afundará Babilónia e nunca mais se voltará a levantar, por causa da calamidade que vou trazer sobre ela. E eles ficarão cansados.’”
Aqui terminam as palavras de Jeremias.

'''

xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[Próximo Capítulo &#62;]