include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-2-1]]

^<<v24-2-1,1>>^ Eu recebi a seguinte palavra de Jeová:

[[v24-2-2]]

^<<v24-2-2,2>>^ “Vai e proclama ao^&#42;1^ povo de Jerusalém: ‘Assim diz Jeová:
“Lembro-me bem da dedicação^&#42;2^ que demonstravas quando eras jovem,
Do amor que mostravas quando estavas noiva,
E de como me seguias no deserto,^&#42;3^
Numa terra não semeada.

[NOTE]
====
. Ou: “aos ouvidos do”.
. Ou: “do amor leal”.
. Veja o Glossário.
====

[[v24-2-3]]

^<<v24-2-3,3>>^ Israel era santo para Jeová, as primícias da sua colheita.”’
‘Todos os que o tentassem devorar tornavam-se culpados.
Sofriam calamidades’, diz Jeová.”

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouçam a palavra de Jeová, casa de Jacó
E todas as famílias da casa de Israel.

[[v24-2-5]]

^<<v24-2-5,5>>^ Assim diz Jeová:
“O que é que os vossos antepassados viram de errado em mim
Para que se afastassem tanto de mim,
Seguissem ídolos sem valor e se tornassem eles próprios sem valor?

[[v24-2-6]]

^<<v24-2-6,6>>^ Eles não disseram: ‘Procuremos a Jeová,
Aquele que nos tirou da terra do Egito,
Que nos conduziu pelo ermo,
Por uma terra de desertos e fendas,
Por uma terra sem água e de densas trevas,
Por uma terra por onde não passa nenhum viajante
E onde ninguém mora.’

[[v24-2-7]]

^<<v24-2-7,7>>^ Então, eu trouxe-vos a uma terra de pomares,
Para comerem os seus frutos e as suas coisas boas.
Mas vocês chegaram e profanaram a minha terra;
Fizeram da minha herança algo detestável.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não disseram: ‘Procuremos a Jeová.’
Os que lidam com a Lei não me conheceram,
Os pastores rebelaram-se contra mim,
Os profetas profetizaram em nome de Baal
E seguiram aqueles que não podem ajudar ninguém.

[[v24-2-9]]

^<<v24-2-9,9>>^ ‘Por isso, continuarei a fazer acusações contra vocês’, diz Jeová,
‘E farei acusações contra os filhos dos vossos filhos’.

[[v24-2-10]]

^<<v24-2-10,10>>^ ‘Atravessem o mar até aos litorais^&#42;1^ de Quitim e vejam;
Enviem alguém a Quedar e observem bem;
Vejam se já aconteceu uma coisa destas:

[NOTE]
====
. Ou: “às ilhas”.
====

[[v24-2-11]]

^<<v24-2-11,11>>^ Será que alguma nação já trocou os seus deuses por outros que não são deuses?
No entanto, o meu próprio povo trocou a minha glória por aquilo que é inútil.

[[v24-2-12]]

^<<v24-2-12,12>>^ Olhem espantados para isto, ó céus;
Tremam, horrorizados’, diz Jeová,

[[v24-2-13]]

^<<v24-2-13,13>>^ ‘Pois o meu povo fez duas coisas más:
Abandonaram-me, a mim, a fonte de água viva,
E cavaram^&#42;1^ cisternas,
Cisternas rachadas, que não podem reter água.’

[NOTE]
====
. Provavelmente na rocha.
====

[[v24-2-14]]

^<<v24-2-14,14>>^ ‘Será que Israel é um servo? Ou um escravo nascido na casa?
Então, porque é que está a saque?

[[v24-2-15]]

^<<v24-2-15,15>>^ Leões novos^&#42;1^ rugiram contra ele,
Levantaram a sua voz.
Fizeram da terra dele um motivo de terror.
As suas cidades foram incendiadas e deixadas sem habitantes.

[NOTE]
====
. Ou: “Leões novos jubados”.
====

[[v24-2-16]]

^<<v24-2-16,16>>^ O povo de Nofe^&#42;1^ e de Tafnes rapou o^&#42;2^ alto da tua cabeça.

[NOTE]
====
. Ou: “Mênfis”.
. Ou: “alimentou-se do”.
====

[[v24-2-17]]

^<<v24-2-17,17>>^ Não és tu a culpada pelo que te aconteceu,
Por teres abandonado a Jeová, teu Deus,
Quando ele te conduzia pelo caminho?

[[v24-2-18]]

^<<v24-2-18,18>>^ Agora, porque é que desejas ir para o Egito
E beber as águas de Sior?^&#42;1^
Porque é que desejas ir para a Assíria
E beber as águas do Eufrates?^&#42;2^

[NOTE]
====
. Isto é, um braço do rio Nilo.
. Lit.: “do Rio”.
====

[[v24-2-19]]

^<<v24-2-19,19>>^ A tua maldade devia corrigir-te,
E a tua própria infidelidade devia repreender-te.
Vê e aprende como é mau e amargo
Abandonares a Jeová, teu Deus;
Tu não tens temor de mim’, diz o Soberano Senhor, Jeová dos exércitos.

[[v24-2-20]]

^<<v24-2-20,20>>^ ‘Pois, há muito tempo, despedacei o teu jugo
E destruí as tuas correntes.
Porém, tu disseste: “Não te vou servir”;
De facto, em cada colina elevada e debaixo de cada árvore frondosa,
Tu deitavas-te para te prostituíres.

[[v24-2-21]]

^<<v24-2-21,21>>^ Plantei-te como uma videira seleta de uvas vermelhas, da semente mais pura;
Como é que, então, te degeneraste diante de mim, por te transformares em ramos de uma videira brava?’

[[v24-2-22]]

^<<v24-2-22,22>>^ ‘Mesmo que te lavasses com soda^&#42;1^ e usasses muita barrela,^&#42;2^
A tua culpa continuaria a ser uma mancha diante de mim’, diz o Soberano Senhor Jeová.

[NOTE]
====
. Ou: “alcali”, isto é, carbonato de sódio.
. Ou: “muito sabão”.
====

[[v24-2-23]]

^<<v24-2-23,23>>^ Como é que te atreves a dizer: ‘Não me tornei impura.
Não fui atrás dos baalins’?
Vê como te comportaste no vale.
Considera o que fizeste.
Tu és como uma jovem e veloz fêmea de camelo,
Que corre sem rumo, de um lado para o outro,

[[v24-2-24]]

^<<v24-2-24,24>>^ Uma jumenta selvagem acostumada ao deserto,
Que fareja o vento no seu desejo ardente.^&#42;1^
Quem é que a consegue domar quando ela está no cio?
Nenhum macho precisa de cansar-se por andar atrás dela;
Quando ela estiver no cio,^&#42;2^ eles hão de encontrá-la.

[NOTE]
====
. Ou: “no desejo ardente da sua alma”.
. Lit.: “No seu mês”.
====

[[v24-2-25]]

^<<v24-2-25,25>>^ Não deixes os teus pés ficarem descalços
Nem a tua garganta ficar seca.
No entanto, dizes: ‘Não! Não adianta!
Eu apaixonei-me por estranhos^&#42;1^
E vou correr atrás deles.’

[NOTE]
====
. Ou: “deuses estrangeiros”.
====

[[v24-2-26]]

^<<v24-2-26,26>>^ Assim como o ladrão se envergonha quando é apanhado,
Assim se envergonharam os da casa de Israel,
Eles, os seus reis e os seus príncipes,
Os seus sacerdotes e os seus profetas.

[[v24-2-27]]

^<<v24-2-27,27>>^ Eles dizem a uma árvore: ‘Tu és meu pai’,
E a uma pedra: ‘Tu deste-me à luz.’
No entanto, viram-me as costas, em vez de virarem o rosto para mim.
E, quando chegar a sua calamidade, eles dirão:
‘Levanta-te e salva-nos!’

[[v24-2-28]]

^<<v24-2-28,28>>^ Ora, onde é que estão os deuses que fizeste para ti?
Que eles se levantem, se te puderem salvar quando chegar a tua calamidade.
Pois os teus deuses, ó Judá, tornaram-se tão numerosos como as tuas cidades.

[[v24-2-29]]

^<<v24-2-29,29>>^ ‘Porque é que se queixam contra mim?
Porque é que todos vocês se rebelaram contra mim?’, diz Jeová.

[[v24-2-30]]

^<<v24-2-30,30>>^ Foi em vão que castiguei os vossos filhos.
Eles não aceitaram a disciplina.
A vossa própria espada devorou os vossos profetas,
Como um leão destruidor.

[[v24-2-31]]

^<<v24-2-31,31>>^ Vocês, os que pertencem a esta geração, prestem atenção à palavra de Jeová.
Será que eu me tornei para Israel como um deserto
Ou uma terra de densa escuridão?
Porque é que eles, os do meu povo, disseram: ‘Andamos livremente.
Nunca mais voltaremos para ti’?

[[v24-2-32]]

^<<v24-2-32,32>>^ Será que uma jovem^&#42;1^ se esquece dos seus enfeites,
Ou a noiva das suas faixas?^&#42;2^
No entanto, não é possível contar os dias em que o meu próprio povo se esqueceu de mim.

[NOTE]
====
. Ou: “virgem”.
. Ou: “faixas para o busto”.
====

[[v24-2-33]]

^<<v24-2-33,33>>^ Com que habilidade, ó mulher, preparas o teu caminho para procurares o amor!
Treinaste-te a ti mesma nos caminhos da maldade.

[[v24-2-34]]

^<<v24-2-34,34>>^ Até as tuas roupas^&#42;1^ estão manchadas com o sangue dos pobres e inocentes,^&#42;2^
Apesar de eu não os ter apanhado a arrombar nada.
O sangue deles está em todas as tuas roupas.

[NOTE]
====
. Ou: “saias”.
. Ou: “das almas pobres e inocentes”.
====

[[v24-2-35]]

^<<v24-2-35,35>>^ No entanto, dizes: ‘Sou inocente.
Com certeza, ele já não está zangado comigo.’
Agora, vou trazer o julgamento contra ti,
Pois dizes: ‘Não pequei.’

[[v24-2-36]]

^<<v24-2-36,36>>^ Como é que não vês nada de mais no teu proceder instável?
Também te envergonharás do Egito,
Assim como te envergonhaste da Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ É por esta razão que sairás com as mãos sobre a cabeça:
Porque Jeová rejeitou aqueles em quem depositaste a tua confiança;
Eles não te farão bem-sucedida.”

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]