include::./index.adoc[]

[[v24-19-0]]
=== Jeremias, 19
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-19-1]]

^<<v24-19-1,1>>^ Assim disse Jeová: “Vai comprar um pote de barro a um oleiro. Leva contigo alguns anciãos do povo e alguns anciãos dos sacerdotes,

[[v24-19-2]]

^<<v24-19-2,2>>^ e vai até ao vale do Filho de Hinom, à entrada do Portão dos Cacos. E proclama ali as palavras que eu te disser.

[[v24-19-3]]

^<<v24-19-3,3>>^ Dirás: ‘Ouçam a palavra de Jeová, ó reis de Judá e habitantes de Jerusalém. Assim diz Jeová dos exércitos, o Deus de Israel:
“‘“Estou prestes a trazer sobre este lugar uma calamidade que fará tinir os ouvidos de quem ouvir falar dela.

[[v24-19-4]]

^<<v24-19-4,4>>^ Vou fazer isso porque eles me abandonaram e tornaram este lugar irreconhecível. Nele, estão a oferecer sacrifícios a outros deuses, que nem eles, nem os seus antepassados, nem os reis de Judá conheciam, e encheram este lugar com o sangue dos inocentes.

[[v24-19-5]]

^<<v24-19-5,5>>^ Eles construíram os altos sagrados de Baal para queimarem os seus filhos no fogo, como ofertas a Baal, algo que eu não tinha ordenado nem falado e que nunca me tinha ocorrido no coração.”’^&#42;1^

[NOTE]
====
. Ou: “nunca me tinha passado pela mente”.
====

[[v24-19-6]]

^<<v24-19-6,6>>^ “‘“Portanto, estão a chegar os dias”, diz Jeová, “em que este lugar não voltará a ser chamado Tofete ou vale do Filho de Hinom, mas, antes, vale da Matança.

[[v24-19-7]]

^<<v24-19-7,7>>^ Vou frustrar os planos de Judá e de Jerusalém neste lugar, e vou fazê-los cair pela espada diante dos seus inimigos e às mãos dos que procuram tirar-lhes a vida.^&#42;1^ E vou dar os seus corpos como alimento às aves dos céus e aos animais da terra.

[NOTE]
====
. Ou: “procuram a sua alma”.
====

[[v24-19-8]]

^<<v24-19-8,8>>^ Vou fazer desta cidade um motivo de terror e um alvo de assobios. Todos os que passarem por ela olharão aterrorizados e assobiarão por causa de todas as suas pragas.

[[v24-19-9]]

^<<v24-19-9,9>>^ E vou fazê-los comer a carne dos seus filhos e das suas filhas, e cada um comerá a carne do seu próximo, por causa do cerco e do desespero que sentirão quando estiverem cercados pelos seus inimigos e pelos que procuram tirar-lhes a vida.”’^&#42;1^

[NOTE]
====
. Ou: “procuram a sua alma”.
====

[[v24-19-10]]

^<<v24-19-10,10>>^ “Então, despedaça o pote diante dos olhos dos homens que forem contigo

[[v24-19-11]]

^<<v24-19-11,11>>^ e diz-lhes: ‘Assim diz Jeová dos exércitos: “Vou despedaçar este povo e esta cidade como se despedaça um vaso de barro, que nunca mais pode ser restaurado. E eles enterrarão os mortos em Tofete até que deixe de haver lugar para os enterrar.”’

[[v24-19-12]]

^<<v24-19-12,12>>^ “‘É isso o que eu vou fazer a este lugar’, diz Jeová, ‘e aos seus habitantes, para tornar esta cidade igual a Tofete.

[[v24-19-13]]

^<<v24-19-13,13>>^ E as casas de Jerusalém e as casas dos reis de Judá vão tornar-se impuras como este lugar de Tofete, sim, todas as casas em cujos terraços eles ofereceram sacrifícios a todo o exército dos céus e onde derramaram ofertas de bebida a outros deuses.’”

[[v24-19-14]]

^<<v24-19-14,14>>^ Quando Jeremias voltou de Tofete, onde Jeová o tinha enviado para profetizar, ele pôs-se de pé no pátio da casa de Jeová e disse a todo o povo:

[[v24-19-15]]

^<<v24-19-15,15>>^ “Assim diz Jeová dos exércitos, o Deus de Israel: ‘Vou trazer sobre esta cidade e sobre todos os seus povoados toda a calamidade que decretei contra ela, porque teimaram em^&#42;1^ não obedecer às minhas palavras.’”

[NOTE]
====
. Lit.: “endureceram a sua cerviz para”.
====

'''

xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[Próximo Capítulo &#62;]