include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-4-1]]

^<<v24-4-1,1>>^ “Ó Israel, se voltares”, diz Jeová,
“Se voltares para mim,
E, se removeres os teus ídolos repugnantes da minha frente,
Não continuarás a ser um fugitivo.

[[v24-4-2]]

^<<v24-4-2,2>>^ E, se jurares
Em verdade, justiça e retidão: ‘Tão certo como Jeová vive!’,
Então, as nações obterão uma bênção para si mesmas por meio dele
E irão orgulhar-se dele.”

[[v24-4-3]]

^<<v24-4-3,3>>^ Pois assim diz Jeová aos homens de Judá e a Jerusalém:
“Passem o arado nas terras que não foram cultivadas
E parem de semear entre os espinhos.

[[v24-4-4]]

^<<v24-4-4,4>>^ Circuncidem-se para Jeová
E tirem o prepúcio do vosso coração,
Ó homens de Judá e habitantes de Jerusalém,
Para que o meu furor não se acenda como um fogo
E arda sem que ninguém o possa apagar,
Por causa das vossas más ações.”

[[v24-4-5]]

^<<v24-4-5,5>>^ Anunciem em Judá e façam uma proclamação em Jerusalém.
Gritem e toquem a buzina por todo o país.
Clamem bem alto, dizendo: “Reúnam-se,
E fujamos para as cidades fortificadas.

[[v24-4-6]]

^<<v24-4-6,6>>^ Ergam um sinal^&#42;1^ que indique o caminho para Sião.
Procurem abrigo, não fiquem parados”,
Pois vou trazer uma calamidade desde o norte, uma grande ruína.

[NOTE]
====
. Ou: “poste de sinal”.
====

[[v24-4-7]]

^<<v24-4-7,7>>^ Ele surgiu como um leão que sai da sua moita;
O destruidor de nações pôs-se a caminho.
Ele saiu de onde mora para fazer da vossa terra um motivo de terror.
As vossas cidades serão reduzidas a ruínas e deixadas sem habitantes.

[[v24-4-8]]

^<<v24-4-8,8>>^ Por isso, vistam-se de serapilheira,^&#42;1^
Chorem^&#42;2^ e lamentem,
Pois a ira ardente de Jeová não se afastou de nós.

[NOTE]
====
. Veja o Glossário.
. Ou: “Batam no peito”.
====

[[v24-4-9]]

^<<v24-4-9,9>>^ “Nesse dia”, diz Jeová, “o coração^&#42;1^ do rei fraquejará,
E também o coração^&#42;2^ dos príncipes;
Os sacerdotes ficarão aterrorizados e os profetas ficarão perplexos”.

[NOTE]
====
. Ou: “a coragem”.
. Ou: “a coragem”.
====

[[v24-4-10]]

^<<v24-4-10,10>>^ Então, eu disse: “Ai, Soberano Senhor Jeová! De facto, tu enganas totalmente este povo e Jerusalém, ao dizeres: ‘Vocês terão paz’, quando estamos com a espada na garganta.”^&#42;1^

[NOTE]
====
. Ou: “quando a espada atinge a nossa alma”.
====

[[v24-4-11]]

^<<v24-4-11,11>>^ Nesse tempo, dir-se-á a este povo e a Jerusalém:
“Um vento abrasador vindo das colinas áridas do deserto
Soprará sobre a filha^&#42;1^ do meu povo;
Ele não vem para separar a palha do trigo^&#42;2^ nem para limpar os grãos.

[NOTE]
====
. Personificação poética que talvez expresse pena ou compaixão.
. Ou: “para padejar”.
====

[[v24-4-12]]

^<<v24-4-12,12>>^ O vento vem de lá com toda a força, à minha ordem.
Agora, vou pronunciar julgamentos contra eles.

[[v24-4-13]]

^<<v24-4-13,13>>^ Vejam! O inimigo virá como nuvens de chuva;
Os seus carros de guerra são como um vendaval.
Os seus cavalos são mais velozes do que as águias.
Ai de nós, pois estamos arruinados!

[[v24-4-14]]

^<<v24-4-14,14>>^ Lava a maldade do teu coração, ó Jerusalém, para que sejas salva.
Até quando é que vais alimentar pensamentos errados?

[[v24-4-15]]

^<<v24-4-15,15>>^ Pois uma voz traz notícias a partir de Dã
E proclama calamidade a partir dos montes de Efraim.

[[v24-4-16]]

^<<v24-4-16,16>>^ Falem sobre isso às nações;
Proclamem-no contra Jerusalém.”
“Vão chegar vigias^&#42;1^ de uma terra distante,
Que darão gritos de guerra contra as cidades de Judá.

[NOTE]
====
. Lit.: “observadores”, isto é, os que observavam a cidade para decidir quando atacá-la.
====

[[v24-4-17]]

^<<v24-4-17,17>>^ Eles cercam-na por todos os lados, como os vigias dos campos,
Pois ela rebelou-se contra mim”, diz Jeová.

[[v24-4-18]]

^<<v24-4-18,18>>^ “O teu proceder e as tuas ações recairão sobre ti.
Como é amarga a tua calamidade,
Pois atinge em cheio o teu coração!”

[[v24-4-19]]

^<<v24-4-19,19>>^ Ai, que angústia!^&#42;1^ Que angústia!
Sinto uma dor terrível no coração.^&#42;2^
O meu coração bate com força dentro de mim.
Não posso ficar calado,
Pois ouvi^&#42;3^ o som da buzina,
O toque^&#42;4^ de guerra.

[NOTE]
====
. Lit.: “os meus intestinos”.
. Lit.: “nas paredes do meu coração”.
. Ou: “a minha alma ouviu”.
. Ou, possivelmente: “O som do grito”.
====

[[v24-4-20]]

^<<v24-4-20,20>>^ Relata-se uma calamidade após outra,
Pois o país inteiro está a ser destruído.
De repente, as minhas próprias tendas foram devastadas
E, num instante, os seus panos foram destruídos.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando é que vou continuar a ver o sinal?^&#42;1^
Até quando é que vou continuar a ouvir o som da buzina?

[NOTE]
====
. Ou: “poste de sinal”.
====

[[v24-4-22]]

^<<v24-4-22,22>>^ “Pois o meu povo é tolo;
Não fazem caso de mim.
São filhos insensatos, sem entendimento.
São suficientemente inteligentes^&#42;1^ para fazer o mal,
Mas não sabem fazer o bem.”

[NOTE]
====
. Ou: “sábios”.
====

[[v24-4-23]]

^<<v24-4-23,23>>^ Eu olhei para esta terra, e vi que estava deserta e vazia.
Olhei para os céus, e a sua luz tinha desaparecido.

[[v24-4-24]]

^<<v24-4-24,24>>^ Olhei para os montes, e vi que tremiam,
E as colinas estremeciam.

[[v24-4-25]]

^<<v24-4-25,25>>^ Olhei, e vi que já não havia ninguém,
E todas as aves dos céus tinham fugido.

[[v24-4-26]]

^<<v24-4-26,26>>^ Olhei, e vi que o pomar se tinha transformado num deserto,
E todas as suas cidades tinham sido demolidas.
Foi por causa de Jeová,
Por causa da sua ira ardente.

[[v24-4-27]]

^<<v24-4-27,27>>^ Pois assim diz Jeová: “Toda esta terra ficará desolada,
Mas não farei uma exterminação completa.

[[v24-4-28]]

^<<v24-4-28,28>>^ Por isso, esta terra ficará de luto,
E os céus acima irão escurecer-se.
Pois eu falei, decidi,
E não mudarei de ideias,^&#42;1^ nem voltarei atrás.

[NOTE]
====
. Ou: “não lamentarei”.
====

[[v24-4-29]]

^<<v24-4-29,29>>^ Ao ouvir o ruído dos cavaleiros e dos arqueiros,
A cidade inteira foge.
As pessoas entram nas florestas
E sobem às rochas.
Todas as cidades são abandonadas;
Já não há ninguém a morar nelas.”

[[v24-4-30]]

^<<v24-4-30,30>>^ Agora que estás devastada, o que é que vais fazer?
Costumavas vestir-te com tecidos finos,^&#42;1^
Enfeitar-te com joias de ouro,
E realçar os olhos com tinta^&#42;2^ preta.
Era em vão que te embelezavas.
Pois os teus amantes rejeitaram-te;
Agora, querem tirar-te a vida.^&#42;3^

[NOTE]
====
. Ou: “com escarlate”.
. Ou: “sombra”.
. Ou: “procuram a tua alma”.
====

[[v24-4-31]]

^<<v24-4-31,31>>^ Ouço um gemido como o de uma mulher com dores,^&#42;1^
Um grito, como o de uma mulher a dar à luz o primeiro filho;
A voz da filha de Sião a respirar com dificuldade.
Ela estende as mãos e diz:
“Ai de mim, pois estou^&#42;2^ exausta por causa dos assassinos!”

[NOTE]
====
. Ou, possivelmente: “mulher doente”.
. Ou: “a minha alma está”.
====

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]