include::./index.adoc[]

[[v24-36-0]]
=== Jeremias, 36
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-36-1]]

^<<v24-36-1,1>>^ No quarto ano de Jeoiaquim, filho de Josias e rei de Judá, Jeremias recebeu a seguinte palavra da parte de Jeová:

[[v24-36-2]]

^<<v24-36-2,2>>^ “Pega num rolo^&#42;1^ e escreve todas as palavras que te comuniquei contra Israel, Judá e todas as nações, desde o primeiro dia em que falei contigo, nos dias de Josias, até hoje.

[NOTE]
====
. Lit.: “num rolo de um livro”.
====

[[v24-36-3]]

^<<v24-36-3,3>>^ Talvez, quando os da casa de Judá ouvirem falar de toda a calamidade que pretendo trazer contra eles, eles recuem do seu mau caminho, para que eu perdoe o seu erro e o seu pecado.”

[[v24-36-4]]

^<<v24-36-4,4>>^ Por conseguinte, Jeremias chamou Baruque, filho de Nerias, e Jeremias ditou todas as palavras que Jeová lhe tinha falado, e Baruque escreveu-as no rolo.^&#42;1^

[NOTE]
====
. Lit.: “rolo do livro”.
====

[[v24-36-5]]

^<<v24-36-5,5>>^ Jeremias ordenou então a Baruque: “Estou proibido de entrar na casa de Jeová.

[[v24-36-6]]

^<<v24-36-6,6>>^ Portanto, tu és aquele que deve entrar e ler em voz alta as palavras de Jeová que eu te ditei e que escreveste no rolo. Lê na presença do povo na casa de Jeová, no dia de jejum; assim lerás para todo o povo de Judá que vem das suas cidades.

[[v24-36-7]]

^<<v24-36-7,7>>^ Talvez Jeová ouça o seu pedido de favor, e cada um recue do seu mau caminho, pois foi com grande ira e furor que Jeová falou contra este povo.”

[[v24-36-8]]

^<<v24-36-8,8>>^ Então, Baruque, filho de Nerias, fez tudo o que o profeta Jeremias lhe ordenou e leu em voz alta, na casa de Jeová, as palavras de Jeová que estavam no rolo.^&#42;1^

[NOTE]
====
. Ou: “livro”.
====

[[v24-36-9]]

^<<v24-36-9,9>>^ No quinto ano de Jeoiaquim, filho de Josias e rei de Judá, no nono mês, todo o povo em Jerusalém e todo o povo que tinha vindo a Jerusalém das cidades de Judá proclamaram um jejum diante de Jeová.

[[v24-36-10]]

^<<v24-36-10,10>>^ Depois disso, Baruque leu em voz alta as palavras de Jeremias que estavam no rolo.^&#42;1^ Ele fez a leitura na casa de Jeová, na sala^&#42;2^ de Gemarias, filho do copista^&#42;3^ Safã, no pátio superior, à entrada do portão novo da casa de Jeová, na presença de todo o povo.

[NOTE]
====
. Ou: “livro”.
. Ou: “no refeitório”.
. Ou: “escriba”.
====

[[v24-36-11]]

^<<v24-36-11,11>>^ Quando Micaías, filho de Gemarias, filho de Safã, ouviu todas as palavras de Jeová que estavam no rolo,^&#42;1^

[NOTE]
====
. Ou: “livro”.
====

[[v24-36-12]]

^<<v24-36-12,12>>^ desceu à casa^&#42;1^ do rei e foi à sala do secretário. Todos os príncipes^&#42;2^ estavam lá sentados: Elisama, o secretário; Delaías, filho de Semaías; Elnatã, filho de Acbor; Gemarias, filho de Safã; Zedequias, filho de Hananias; e todos os outros príncipes.

[NOTE]
====
. Ou: “ao palácio”.
. Ou: “oficiais da corte”.
====

[[v24-36-13]]

^<<v24-36-13,13>>^ E Micaías contou-lhes todas as palavras que tinha ouvido quando Baruque leu o rolo^&#42;1^ na presença do povo.

[NOTE]
====
. Ou: “livro”.
====

[[v24-36-14]]

^<<v24-36-14,14>>^ Então, todos os príncipes mandaram Jeudi, filho de Netanias, filho de Selemias, filho de Cusi, dizer a Baruque: “Vem e traz o rolo que leste na presença do povo.” Baruque, filho de Nerias, pegou no rolo e foi até eles.

[[v24-36-15]]

^<<v24-36-15,15>>^ De seguida, disseram-lhe: “Senta-te, por favor, e lê o rolo em voz alta para nós.” Portanto, Baruque leu-lhes o rolo.

[[v24-36-16]]

^<<v24-36-16,16>>^ Assim que ouviram todas as palavras, olharam uns para os outros, apavorados, e disseram a Baruque: “Temos certamente que contar todas estas palavras ao rei.”

[[v24-36-17]]

^<<v24-36-17,17>>^ E perguntaram a Baruque: “Por favor, conta-nos como escreveste todas estas palavras. Foi ele que as ditou?”

[[v24-36-18]]

^<<v24-36-18,18>>^ Baruque respondeu-lhes: “Ele ditou-me todas estas palavras, e eu escrevi-as com tinta neste rolo.”^&#42;1^

[NOTE]
====
. Ou: “livro”.
====

[[v24-36-19]]

^<<v24-36-19,19>>^ Os príncipes disseram a Baruque: “Vão e escondam-se, tu e Jeremias, e não deixem que ninguém saiba onde estão.”

[[v24-36-20]]

^<<v24-36-20,20>>^ Depois disso, eles compareceram perante o rei, no pátio. Guardaram o rolo na sala de Elisama, o secretário, e contaram ao rei tudo o que tinham ouvido.

[[v24-36-21]]

^<<v24-36-21,21>>^ Então, o rei mandou Jeudi ir buscar o rolo, de modo que ele o trouxe da sala de Elisama, o secretário. Jeudi começou a lê-lo na presença do rei e de todos os príncipes que estavam de pé junto ao rei.

[[v24-36-22]]

^<<v24-36-22,22>>^ Era o nono mês,^&#42;1^ e o rei estava sentado na casa de inverno, diante de uma lareira acesa.

[NOTE]
====
. A segunda metade de novembro e a primeira metade de dezembro. Veja o Ap. B15.
====

[[v24-36-23]]

^<<v24-36-23,23>>^ Quando Jeudi acabava de ler três ou quatro colunas, o rei cortava o trecho com uma faca de escriba e atirava-o para o fogo da lareira, até que todo o rolo tivesse sido queimado no fogo da lareira.

[[v24-36-24]]

^<<v24-36-24,24>>^ O rei e os seus servos que ouviram todas aquelas palavras não ficaram com medo nem rasgaram as suas vestes.

[[v24-36-25]]

^<<v24-36-25,25>>^ Embora Elnatã, Delaías e Gemarias suplicassem ao rei que não queimasse o rolo, ele não lhes deu ouvidos.

[[v24-36-26]]

^<<v24-36-26,26>>^ Além disso, o rei ordenou a Jerameel, filho do rei, a Seraías, filho de Azriel, e a Selemias, filho de Abdeel, que prendessem Baruque, o secretário, e o profeta Jeremias. No entanto, Jeová manteve-os escondidos.

[[v24-36-27]]

^<<v24-36-27,27>>^ Depois de o rei queimar o rolo com as palavras que Jeremias tinha ditado a Baruque, Jeremias recebeu novamente a palavra de Jeová:

[[v24-36-28]]

^<<v24-36-28,28>>^ “Vai buscar outro rolo e escreve todas as palavras que estavam no primeiro rolo, que Jeoiaquim, rei de Judá, queimou.

[[v24-36-29]]

^<<v24-36-29,29>>^ E deves dizer contra Jeoiaquim, rei de Judá: ‘Assim diz Jeová: “Queimaste aquele rolo e disseste: ‘Porque é que escreveste: “O rei de Babilónia certamente virá e destruirá esta terra, deixando-a sem homens e animais”?’

[[v24-36-30]]

^<<v24-36-30,30>>^ Portanto, assim diz Jeová contra Jeoiaquim, rei de Judá: ‘Ele não terá nenhum descendente para se sentar no trono de David, e o seu cadáver ficará exposto ao calor do dia e à geada da noite.

[[v24-36-31]]

^<<v24-36-31,31>>^ Vou ajustar contas com ele, com os seus descendentes^&#42;1^ e com os seus servos, por causa do seu erro. E vou trazer sobre eles, sobre os habitantes de Jerusalém e sobre os homens de Judá toda a calamidade que proferi contra eles, sem que eles me escutassem.’”’”

[NOTE]
====
. Lit.: “a sua semente”.
====

[[v24-36-32]]

^<<v24-36-32,32>>^ Assim, Jeremias foi buscar outro rolo e deu-o a Baruque, o secretário, filho de Nerias. À medida que Jeremias ia ditando, ele escrevia no rolo todas as palavras do rolo^&#42;1^ que Jeoiaquim, rei de Judá, tinha queimado no fogo. E foram acrescentadas muitas outras palavras semelhantes.

[NOTE]
====
. Ou: “livro”.
====

'''

xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[Próximo Capítulo &#62;]