include::./index.adoc[]

[[v24-15-0]]
=== Jeremias, 15
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-15-1]]

^<<v24-15-1,1>>^ Então, Jeová disse-me: “Mesmo que Moisés e Samuel comparecessem diante de mim, eu não mostraria favor a^&#42;1^ este povo. Expulsa-os da minha presença. Que saiam.

[NOTE]
====
. Ou: “a minha alma não estaria com”.
====

[[v24-15-2]]

^<<v24-15-2,2>>^ E, se eles te perguntarem: ‘Para onde iremos?’, deves responder-lhes: ‘Assim diz Jeová:
“Quem tiver de ser morto pela praga mortífera, será morto pela praga mortífera!
Quem tiver de ser morto pela espada, será morto pela espada!
Quem tiver de morrer de fome, morrerá de fome!
Quem tiver de ir para o cativeiro, irá para o cativeiro!”’

[[v24-15-3]]

^<<v24-15-3,3>>^ “‘Vou enviar quatro calamidades^&#42;1^ contra eles’, diz Jeová, ‘a espada para matar, os cães para arrastar os seus corpos, as aves dos céus e os animais da terra para devorar e destruir.

[NOTE]
====
. Ou, possivelmente: “quatro tipos de julgamentos”. Lit.: “quatro famílias”.
====

[[v24-15-4]]

^<<v24-15-4,4>>^ E farei deles um motivo de terror para todos os reinos da terra, por causa de Manassés, filho de Ezequias e rei de Judá, pelo que ele fez em Jerusalém.

[[v24-15-5]]

^<<v24-15-5,5>>^ Quem é que vai ter compaixão de ti, Jerusalém?
Quem é que vai ter pena de ti,
E quem vai parar a fim de te perguntar como é que estás?’

[[v24-15-6]]

^<<v24-15-6,6>>^ ‘Abandonaste-me’, diz Jeová.
‘Viras-me as costas.^&#42;1^
Por isso, vou estender a mão contra ti e destruir-te.
Cansei-me de ter pena de ti.^&#42;2^

[NOTE]
====
. Ou, possivelmente: “Andas para trás”.
. Ou: “de sentir lástima”.
====

[[v24-15-7]]

^<<v24-15-7,7>>^ Vou espalhá-los como se fossem palha ao vento^&#42;1^ nos portões desta terra.
Vou deixá-los sem filhos.
Vou destruir o meu povo,
Visto que eles se recusaram a abandonar os seus caminhos.

[NOTE]
====
. Ou: “Vou padejá-los com um forcado”.
====

[[v24-15-8]]

^<<v24-15-8,8>>^ As suas viúvas vão tornar-se mais numerosas diante de mim do que os grãos de areia dos mares.
Trarei o destruidor ao meio-dia contra eles, contra as mães e os jovens.
Trarei sobre eles, de repente, alvoroço e terror.

[[v24-15-9]]

^<<v24-15-9,9>>^ A mulher que deu à luz sete filhos perdeu as forças;
Ela^&#42;1^ tem dificuldade em respirar.
O seu sol pôs-se enquanto ainda era dia,
Causando vergonha e humilhação.’^&#42;2^
‘E os poucos que lhes restarem
Eu entregarei à espada diante dos seus inimigos’, diz Jeová.”

[NOTE]
====
. Ou: “A sua alma”.
. Ou, possivelmente: “Ele ficou envergonhado e constrangido”.
====

[[v24-15-10]]

^<<v24-15-10,10>>^ Ai de mim, minha mãe, por me teres dado à luz.
Sou motivo de discórdias e disputas com toda a terra.
Não emprestei nem pedi emprestado;
Mesmo assim, todos me amaldiçoam.

[[v24-15-11]]

^<<v24-15-11,11>>^ Jeová disse: “Certamente, vou ajudar-te.^&#42;1^
Certamente, vou interceder a teu favor junto ao inimigo
No tempo da calamidade, no tempo da aflição.

[NOTE]
====
. Ou: “vou ministrar-te para o bem”.
====

[[v24-15-12]]

^<<v24-15-12,12>>^ Será que alguém pode despedaçar o ferro,
O ferro que vem do norte, e o cobre?

[[v24-15-13]]

^<<v24-15-13,13>>^ Entregarei os teus recursos e os teus tesouros como despojo,
Não por um preço, mas por causa de todos os pecados que cometeste em todos os teus territórios.

[[v24-15-14]]

^<<v24-15-14,14>>^ Entregarei tais coisas aos teus inimigos
Para que as levem para uma terra que não conheces.
Pois a minha ira acendeu um fogo,
Que arde contra vocês.”

[[v24-15-15]]

^<<v24-15-15,15>>^ Tu sabes de tudo, ó Jeová.
Lembra-te de mim, volta a tua atenção para mim.
Vinga-me dos meus perseguidores.
Não me deixes morrer^&#42;1^ por seres paciente.^&#42;2^
Reconhece que suporto estes insultos por tua causa.

[NOTE]
====
. Lit.: “Não me tires”.
. Ou: “vagaroso em irar-te”.
====

[[v24-15-16]]

^<<v24-15-16,16>>^ Ao encontrar as tuas palavras, comi-as.
E a tua palavra tornou-se a exultação e a alegria do meu coração,
Pois eu levo o teu nome, ó Jeová, Deus dos exércitos.

[[v24-15-17]]

^<<v24-15-17,17>>^ Não me sento com os que só se querem divertir; não me alegro com eles.
Visto que a tua mão está sobre mim, eu sento-me sozinho,
Pois tu encheste-me de indignação.^&#42;1^

[NOTE]
====
. Ou: “de uma mensagem de condenação”.
====

[[v24-15-18]]

^<<v24-15-18,18>>^ Porque é que a minha dor é crónica, e a minha ferida é incurável?
Ela não quer sarar.
Será que te tornarás para mim como um suprimento de água enganoso,
Em que não se pode confiar?

[[v24-15-19]]

^<<v24-15-19,19>>^ Portanto, assim diz Jeová:
“Se voltares, vou restabelecer-te.
Servirás^&#42;1^ diante de mim.
Se separares o que é precioso do que não tem valor,
Serás como a minha boca.^&#42;2^
Eles terão de se voltar para ti,
Mas tu não te voltarás para eles.”

[NOTE]
====
. Lit.: “Ficarás de pé”.
. Ou: “Vais tornar-te o meu porta-voz”.
====

[[v24-15-20]]

^<<v24-15-20,20>>^ “Faço de ti uma forte muralha de cobre para este povo;
Eles certamente lutarão contra ti,
Mas não te vencerão,
Pois eu estou contigo para te salvar e livrar”, diz Jeová.

[[v24-15-21]]

^<<v24-15-21,21>>^ “Vou livrar-te das mãos dos maus
E resgatar-te da palma das mãos dos homens cruéis.”

'''

xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[&#60; Capítulo Anterior] | <<v24-15-0,Topo>> | xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[Próximo Capítulo &#62;]