include::./index.adoc[]

[[v24-40-0]]
=== Jeremias, 40
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-40-1]]

^<<v24-40-1,1>>^ Jeremias recebeu a palavra de Jeová depois de Nebuzaradã, chefe da guarda, o ter libertado em Ramá. Ele tinha levado Jeremias para lá, algemado, e Jeremias estava entre todos os exilados de Jerusalém e de Judá que estavam a ser deportados para Babilónia.

[[v24-40-2]]

^<<v24-40-2,2>>^ O chefe da guarda levou então Jeremias e disse-lhe: “Jeová, teu Deus, predisse esta calamidade contra este lugar,

[[v24-40-3]]

^<<v24-40-3,3>>^ e Jeová trouxe-a, assim como tinha dito, porque vocês pecaram contra Jeová e não obedeceram à sua voz. Por esse motivo é que isto vos aconteceu.

[[v24-40-4]]

^<<v24-40-4,4>>^ Agora, vou libertar-te das algemas que estavam nas tuas mãos. Se achares bem vires comigo para Babilónia, vem, que eu cuidarei de ti. Mas, se não quiseres vir comigo para Babilónia, não venhas. Vê! Tens o país inteiro diante de ti. Vai para onde achares melhor.”

[[v24-40-5]]

^<<v24-40-5,5>>^ Antes de Jeremias se virar para partir, Nebuzaradã disse-lhe: “Volta para junto de Gedalias, filho de Aicão, filho de Safã, a quem o rei de Babilónia designou sobre as cidades de Judá, e fica com ele no meio do povo; ou vai para onde achares melhor.”
Então, o chefe da guarda deu-lhe mantimentos e um presente, e deixou-o ir-se embora.

[[v24-40-6]]

^<<v24-40-6,6>>^ Assim, Jeremias foi para junto de Gedalias, filho de Aicão, em Mispá, e ficou com ele no meio do povo que tinha restado no país.

[[v24-40-7]]

^<<v24-40-7,7>>^ Com o tempo, todos os chefes do exército que estavam no campo com os seus homens ouviram dizer que o rei de Babilónia tinha designado Gedalias, filho de Aicão, sobre o país e que o tinha encarregado dos homens, das mulheres e das crianças pobres do país, que não tinham sido deportados para Babilónia.

[[v24-40-8]]

^<<v24-40-8,8>>^ Portanto, foram ao encontro de Gedalias, em Mispá. Eram eles Ismael, filho de Netanias; Joanã e Jonatã, filhos de Careá; Seraías, filho de Tanumete; os filhos de Efai, o netofatita; e Jezanias, filho do maacatita; juntamente com os seus homens.

[[v24-40-9]]

^<<v24-40-9,9>>^ Gedalias, filho de Aicão, filho de Safã, fez-lhes um juramento, a eles e aos seus homens, dizendo: “Não tenham medo de servir os caldeus. Morem no país e sirvam o rei de Babilónia, e tudo vos correrá bem.

[[v24-40-10]]

^<<v24-40-10,10>>^ Quanto a mim, continuarei em Mispá a representar-vos^&#42;1^ perante os caldeus que vierem até nós. No entanto, vocês devem recolher vinho, frutas de verão e azeite, armazenar essas provisões em recipientes e estabelecer-se nas cidades que ocuparam.”

[NOTE]
====
. Lit.: “ficar de pé”.
====

[[v24-40-11]]

^<<v24-40-11,11>>^ E todos os judeus que estavam em Moabe, em Amom, em Edom e em todos os outros países, também ouviram dizer que o rei de Babilónia tinha deixado um restante ficar em Judá e que tinha designado sobre eles Gedalias, filho de Aicão, filho de Safã.

[[v24-40-12]]

^<<v24-40-12,12>>^ Assim, todos os judeus começaram a regressar de todos os lugares pelos quais tinham sido espalhados. Entraram na terra de Judá e dirigiram-se a Gedalias em Mispá. E recolheram vinho e frutas de verão em quantidade muito grande.

[[v24-40-13]]

^<<v24-40-13,13>>^ Joanã, filho de Careá, e todos os chefes do exército que estavam no campo dirigiram-se a Gedalias em Mispá.

[[v24-40-14]]

^<<v24-40-14,14>>^ Eles disseram-lhe: “O senhor não sabe que Baalis, rei dos amonitas, enviou Ismael, filho de Netanias, para o matar?”^&#42;1^ Contudo, Gedalias, filho de Aicão, não acreditou neles.

[NOTE]
====
. Ou: “para golpear a sua alma”.
====

[[v24-40-15]]

^<<v24-40-15,15>>^ Então, Joanã, filho de Careá, disse secretamente a Gedalias em Mispá: “Quero ir matar Ismael, filho de Netanias, e ninguém vai ficar a saber disso. Porque é que ele havia de matar o senhor?^&#42;1^ Porque é que todo o povo de Judá que se está a juntar a si havia de ser espalhado? E porque é que o restante de Judá havia de ser eliminado?”

[NOTE]
====
. Ou: “golpear a sua alma”.
====

[[v24-40-16]]

^<<v24-40-16,16>>^ Todavia, Gedalias, filho de Aicão, disse a Joanã, filho de Careá: “Não faças isso, pois o que estás a dizer a respeito de Ismael é mentira.”

'''

xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[Próximo Capítulo &#62;]