include::./index.adoc[]

[[v24-22-0]]
=== Jeremias, 22
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-22-1]]

^<<v24-22-1,1>>^ Assim diz Jeová: “Desce até à casa^&#42;1^ do rei de Judá e transmite esta mensagem.

[NOTE]
====
. Ou: “ao palácio”.
====

[[v24-22-2]]

^<<v24-22-2,2>>^ Diz: ‘Ouça a palavra de Jeová, ó rei de Judá, que se senta no trono de David, sim, o senhor, os seus servos e o seu povo, os que entram por estes portões.

[[v24-22-3]]

^<<v24-22-3,3>>^ Assim diz Jeová: “Defendam a justiça e a retidão. Livrem das mãos dos exploradores^&#42;1^ os que são roubados. Não maltratem nenhum residente estrangeiro, nem prejudiquem nenhum órfão^&#42;2^ ou viúva. E não derramem sangue inocente neste lugar.

[NOTE]
====
. Ou: “defraudadores”.
. Ou: “órfão de pai”.
====

[[v24-22-4]]

^<<v24-22-4,4>>^ Pois, se cumprirem cuidadosamente estas palavras, então, os reis que se sentam no trono de David entrarão pelos portões desta casa a andar em carros e a cavalo — eles, com os seus servos e o seu povo.”’

[[v24-22-5]]

^<<v24-22-5,5>>^ “‘Contudo, se não obedecerem a estas palavras, juro por mim mesmo’, diz Jeová, ‘que esta casa se tornará um lugar devastado’.

[[v24-22-6]]

^<<v24-22-6,6>>^ “Pois assim diz Jeová sobre a casa do rei de Judá:
‘És para mim como Gileade,
Como o cume do Líbano.
No entanto, farei de ti um deserto;
Todas as tuas cidades ficarão desabitadas.

[[v24-22-7]]

^<<v24-22-7,7>>^ E vou designar^&#42;1^ destruidores contra ti,
Cada um com as suas armas.
Eles irão derrubar os seus melhores cedros
E lançá-los no fogo.

[NOTE]
====
. Lit.: “santificar”.
====

[[v24-22-8]]

^<<v24-22-8,8>>^ “‘E muitas nações passarão por esta cidade, e as pessoas perguntarão umas às outras: “Porque é que Jeová fez isto a esta grande cidade?”

[[v24-22-9]]

^<<v24-22-9,9>>^ E a resposta será: “Porque eles abandonaram o pacto de Jeová, seu Deus, e curvaram-se diante de outros deuses e serviram-nos.”’

[[v24-22-10]]

^<<v24-22-10,10>>^ Não chorem por aquele que morreu,
Nem sintam pena dele.
Em vez disso, chorem muito por aquele que se vai embora,
Pois ele nunca mais voltará para ver a sua terra natal.

[[v24-22-11]]

^<<v24-22-11,11>>^ “Pois assim diz Jeová a respeito de Salum,^&#42;1^ filho de Josias e rei de Judá, que reina no lugar de Josias, seu pai, e que se foi embora deste lugar: ‘Ele nunca mais voltará.

[NOTE]
====
. Também chamado Jeoacaz.
====

[[v24-22-12]]

^<<v24-22-12,12>>^ Pois ele morrerá no lugar para onde o exilaram e nunca mais verá esta terra.’

[[v24-22-13]]

^<<v24-22-13,13>>^ Ai daquele que constrói a sua casa com injustiça
E os seus aposentos superiores com desonestidade,^&#42;1^
Que faz o seu próximo trabalhar para ele de graça,
Que se recusa a pagar-lhe o salário.

[NOTE]
====
. Ou: “sem retidão”.
====

[[v24-22-14]]

^<<v24-22-14,14>>^ Ele diz: ‘Vou construir para mim uma casa espaçosa,
Com aposentos superiores amplos.
Vou colocar-lhe janelas,
Revesti-la de cedro e pintá-la de vermelhão.’

[[v24-22-15]]

^<<v24-22-15,15>>^ Será que continuarás a reinar por usares mais cedro do que os outros?
O teu pai também comia e bebia,
Mas defendia a justiça e a retidão,
E tudo lhe corria bem.

[[v24-22-16]]

^<<v24-22-16,16>>^ Ele defendia a causa do necessitado e do pobre,
De modo que tudo corria bem.
‘Não é isso o que significa conhecer-me?’, diz Jeová.

[[v24-22-17]]

^<<v24-22-17,17>>^ ‘Mas os teus olhos e o teu coração só querem obter lucro desonesto,
Derramar sangue inocente
E cometer fraude e extorsão.’

[[v24-22-18]]

^<<v24-22-18,18>>^ “Portanto, assim diz Jeová a respeito de Jeoiaquim, filho de Josias e rei de Judá:
‘Ninguém o lamentará:
“Ai, meu irmão! Ai, minha irmã!”
Ninguém o lamentará:
“Ai, senhor! Ai, sua majestade!”

[[v24-22-19]]

^<<v24-22-19,19>>^ O seu enterro será como o enterro de um jumento:
Ele será arrastado e atirado para longe,
Fora dos portões de Jerusalém.’

[[v24-22-20]]

^<<v24-22-20,20>>^ Sobe^&#42;1^ ao Líbano e clama,
Ergue a tua voz em Basã,
E grita de Abarim,
Pois todos os teus amantes foram esmagados.

[NOTE]
====
. Esta ordem parece ser dirigida a Jerusalém.
====

[[v24-22-21]]

^<<v24-22-21,21>>^ Eu falei contigo quando te sentias segura.
Mas tu disseste: ‘Não obedecerei.’
Tens agido assim desde a tua juventude,
Pois nunca obedeceste à minha voz.

[[v24-22-22]]

^<<v24-22-22,22>>^ Um vento pastoreará^&#42;1^ todos os teus pastores,
E os teus amantes irão para o cativeiro.
Então, serás envergonhada e humilhada por causa de toda a tua calamidade.

[NOTE]
====
. Ou: “levará para longe”.
====

[[v24-22-23]]

^<<v24-22-23,23>>^ Ó moradora do Líbano,
Que fazes o teu ninho entre os cedros,
Vais gemer muito quando te sobrevierem as dores,
Uma angústia como a^&#42;1^ da mulher que dá à luz.”

[NOTE]
====
. Lit.: “Dores de parto como as”.
====

[[v24-22-24]]

^<<v24-22-24,24>>^ “‘Tão certo como eu vivo’, diz Jeová, ‘mesmo que tu, Conias,^&#42;1^ filho de Jeoiaquim e rei de Judá, fosses um anel de sinete na minha mão direita, eu iria arrancar-te!

[NOTE]
====
. Também chamado Joaquim e Jeconias.
====

[[v24-22-25]]

^<<v24-22-25,25>>^ Vou entregar-te nas mãos dos que procuram tirar-te a vida,^&#42;1^ nas mãos daqueles de quem tens medo, nas mãos de Nabucodonosor,^&#42;2^ rei de Babilónia, e nas mãos dos caldeus.

[NOTE]
====
. Ou: “procuram a tua alma”.
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-22-26]]

^<<v24-22-26,26>>^ E vou lançar-te, a ti e à tua mãe, aquela que te deu à luz, numa outra terra, onde vocês não nasceram, e é lá que morrerão.

[[v24-22-27]]

^<<v24-22-27,27>>^ Não voltarão à terra da qual terão saudades.^&#42;1^

[NOTE]
====
. Ou: “à terra à qual elevam a sua alma”.
====

[[v24-22-28]]

^<<v24-22-28,28>>^ Será que este homem, Conias, não passa de um pote desprezado e despedaçado,
Um vaso que ninguém quer?
Porque é que ele e os seus descendentes foram lançados para baixo
E atirados para uma terra que não conhecem?’

[[v24-22-29]]

^<<v24-22-29,29>>^ Ó terra,^&#42;1^ terra, terra, ouve a palavra de Jeová!

[NOTE]
====
. Ou: “país”.
====

[[v24-22-30]]

^<<v24-22-30,30>>^ Assim diz Jeová:
‘Registem este homem como alguém sem filhos,
Como alguém que não será bem-sucedido na vida,^&#42;1^
Pois nenhum dos seus descendentes será bem-sucedido
Em sentar-se no trono de David e governar novamente em Judá.’”

[NOTE]
====
. Lit.: “nos seus dias”.
====

'''

xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[Próximo Capítulo &#62;]