include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-8-1]]

^<<v24-8-1,1>>^ “Nesse tempo”, diz Jeová, “os ossos dos reis de Judá, os ossos dos seus príncipes, os ossos dos sacerdotes, os ossos dos profetas e os ossos dos habitantes de Jerusalém serão tirados das sepulturas.

[[v24-8-2]]

^<<v24-8-2,2>>^ Serão espalhados debaixo do sol, da lua e de todo o exército dos céus, aos quais eles amaram, serviram, seguiram e buscaram, e diante dos quais se curvaram. Eles não serão recolhidos nem enterrados. Irão tornar-se como estrume sobre o solo.”

[[v24-8-3]]

^<<v24-8-3,3>>^ “E, em todos os lugares por onde eu os espalhar, o restante que sobreviver dentre essa nação^&#42;1^ má preferirá a morte à vida”, diz Jeová dos exércitos.

[NOTE]
====
. Ou: “família”.
====

[[v24-8-4]]

^<<v24-8-4,4>>^ “Diz-lhes: ‘Assim diz Jeová:
“Será que eles cairão e não voltarão a levantar-se?
Se alguém voltar atrás, será que o outro não voltará atrás também?

[[v24-8-5]]

^<<v24-8-5,5>>^ Porque é que este povo de Jerusalém persiste na sua infidelidade?
Eles apegam-se à falsidade;
Recusam-se a voltar atrás.

[[v24-8-6]]

^<<v24-8-6,6>>^ Eu prestei atenção e fiquei a ouvir, mas o modo como falavam não era correto.
Ninguém se arrependeu da sua maldade nem perguntou: ‘O que é que eu fiz?’
Todos eles voltam sempre a agir como a maioria, como cavalos que se lançam na batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até mesmo a cegonha nos céus conhece as suas estações;^&#42;1^
A rola, o andorinhão e o tordo^&#42;2^ apegam-se ao tempo do seu retorno.^&#42;3^
Porém, o meu próprio povo não entende o julgamento de Jeová.”’

[NOTE]
====
. Ou: “os seus tempos determinados”.
. Ou, possivelmente: “grou”.
. Ou: “da sua migração”.
====

[[v24-8-8]]

^<<v24-8-8,8>>^ ‘Como é que podem dizer: “Somos sábios e temos a lei^&#42;1^ de Jeová”?
Na realidade, a pena^&#42;2^ mentirosa^&#42;3^ dos escribas^&#42;4^ só é usada para a falsidade.

[NOTE]
====
. Ou: “instrução”.
. Lit.: “o estilo”. Veja o Glossário.
. Ou: “falsa”.
. Ou: “secretários”.
====

[[v24-8-9]]

^<<v24-8-9,9>>^ Os sábios foram envergonhados.
Ficaram apavorados e serão apanhados.
Rejeitaram a palavra de Jeová;
Que sabedoria é que eles têm?

[[v24-8-10]]

^<<v24-8-10,10>>^ Por isso, entregarei as suas esposas a outros homens,
E os seus campos a novos donos.
Pois, desde o menor até ao maior, todos eles obtêm lucro desonesto;
Desde o profeta até ao sacerdote, todos cometem fraudes.

[[v24-8-11]]

^<<v24-8-11,11>>^ E tratam superficialmente as feridas^&#42;1^ da filha do meu povo, dizendo:
“Há paz! Há paz!”,
Quando não há paz.

[NOTE]
====
. Ou: “a fratura; o quebrantamento”.
====

[[v24-8-12]]

^<<v24-8-12,12>>^ Será que eles se envergonham das coisas detestáveis que fizeram?
Eles não sentem a mínima vergonha!
Nem sequer sabem o que é sentir vergonha!
Por isso, cairão entre os que já caíram.
Tropeçarão quando eu lhes trouxer a punição’, diz Jeová.

[[v24-8-13]]

^<<v24-8-13,13>>^ ‘Quando os colher, acabarei com eles’, diz Jeová.
‘Não restarão uvas na videira nem figos na figueira, e as folhas murcharão.
E eles perderão as coisas que lhes dei.’”

[[v24-8-14]]

^<<v24-8-14,14>>^ “Porque é que estamos aqui sentados?
Vamos reunir-nos e entrar nas cidades fortificadas, para morrermos ali,
Pois Jeová, nosso Deus, vai eliminar-nos.
Jeová está a dar-nos água envenenada para beber
Porque pecámos contra ele.

[[v24-8-15]]

^<<v24-8-15,15>>^ Esperava-se a paz, mas não veio nada de bom;
Um tempo de cura, mas só há terror!

[[v24-8-16]]

^<<v24-8-16,16>>^ A partir de Dã, consegue-se ouvir os relinchos dos cavalos.
Com o relinchar dos garanhões,
Toda esta terra treme.
Os inimigos entram e devoram esta terra e tudo o que nela há,
A cidade e os seus habitantes.”

[[v24-8-17]]

^<<v24-8-17,17>>^ “Pois, vou mandar-vos serpentes,
Cobras venenosas que não podem ser dominadas com encantamentos
E, certamente, elas irão morder-vos”, diz Jeová.

[[v24-8-18]]

^<<v24-8-18,18>>^ A minha tristeza é incurável;
O meu coração está doente.

[[v24-8-19]]

^<<v24-8-19,19>>^ De uma terra distante vem o grito de socorro
Da filha do meu povo:
“Será que Jeová não está em Sião?
Não está lá o seu rei?”
“Porque é que eles me ofenderam com as suas imagens esculpidas,
Com os seus deuses estrangeiros que não valem nada?”

[[v24-8-20]]

^<<v24-8-20,20>>^ “Já passou a colheita, acabou o verão,
Mas nós ainda não fomos salvos!”

[[v24-8-21]]

^<<v24-8-21,21>>^ Estou arrasado com as feridas^&#42;1^ da filha do meu povo;
Estou muito triste.
O pavor apoderou-se de mim.

[NOTE]
====
. Ou : “o quebrantamento”.
====

[[v24-8-22]]

^<<v24-8-22,22>>^ Será que não há bálsamo^&#42;1^ em Gileade?
Não há lá nenhum médico?^&#42;2^
Porque é que a filha do meu povo não se recuperou?

[NOTE]
====
. Ou: “bálsamo calmante”.
. Ou: “ninguém que cure”.
====

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]