include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-46-1]]

^<<v24-46-1,1>>^ Esta é a palavra de Jeová para o profeta Jeremias a respeito das nações.

[[v24-46-2]]

^<<v24-46-2,2>>^ Para o Egito, a respeito do exército do Faraó Neco, rei do Egito, que estava junto ao rio Eufrates, em Carquemis, quando foi derrotado por Nabucodonosor,^&#42;1^ rei de Babilónia, no quarto ano de Jeoiaquim, filho de Josias e rei de Judá:

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-46-3]]

^<<v24-46-3,3>>^ “Preparem os vossos escudos, o pequeno^&#42;1^ e o grande,
E avancem para a batalha.

[NOTE]
====
. Ou: “broquel”, pequeno escudo geralmente usado por arqueiros.
====

[[v24-46-4]]

^<<v24-46-4,4>>^ Selem os cavalos e montem-nos, ó cavaleiros.
Tomem posição e ponham os capacetes.
Lustrem as lanças e vistam as cotas de malha.

[[v24-46-5]]

^<<v24-46-5,5>>^ ‘Porque é que os vejo apavorados?
Eles estão a recuar, os seus guerreiros foram esmagados.
Estão a fugir em pânico, os seus guerreiros nem sequer olham para trás.
Há terror em toda a parte’, diz Jeová.

[[v24-46-6]]

^<<v24-46-6,6>>^ ‘O veloz não consegue fugir, nem os guerreiros conseguem escapar.
No norte, junto à margem do rio Eufrates,
Eles tropeçam e caem.’

[[v24-46-7]]

^<<v24-46-7,7>>^ Quem é este que sobe como o rio Nilo,
Como rios de águas turbulentas?

[[v24-46-8]]

^<<v24-46-8,8>>^ O Egito sobe como o rio Nilo,
Como rios de águas turbulentas,
E diz: ‘Subirei e cobrirei a terra.
Destruirei a cidade e os seus habitantes.’

[[v24-46-9]]

^<<v24-46-9,9>>^ Subam, ó cavalos;
Avancem loucamente, ó carros!
Que os guerreiros avancem:
Homens de Cuche e de Pute, que usam o escudo,
E os ludins, que armam^&#42;1^ e usam o arco.

[NOTE]
====
. Lit.: “pisam”.
====

[[v24-46-10]]

^<<v24-46-10,10>>^ “Esse dia pertence ao Soberano Senhor, Jeová dos exércitos, é o dia de vingança para ele se vingar dos seus adversários. A espada vai devorar e saciar-se, e matar a sede com o sangue deles, pois o Soberano Senhor, Jeová dos exércitos, preparou um sacrifício^&#42;1^ na terra do norte, junto ao rio Eufrates.

[NOTE]
====
. Ou: “uma matança”.
====

[[v24-46-11]]

^<<v24-46-11,11>>^ Sobe a Gileade e vai buscar bálsamo,
Ó virgem filha do Egito.
Todos os teus remédios são em vão,
Pois não há cura para ti.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram falar da tua desonra,
E o teu clamor encheu a terra.
Pois um guerreiro tropeça noutro guerreiro,
E ambos caem juntos.”

[[v24-46-13]]

^<<v24-46-13,13>>^ Esta é a palavra que Jeová transmitiu ao profeta Jeremias a respeito da vinda de Nabucodonosor,^&#42;1^ rei de Babilónia, para atacar a terra do Egito:

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-46-14]]

^<<v24-46-14,14>>^ “Anunciem-na no Egito e façam uma proclamação em Migdol,
Façam uma proclamação também em Nofe^&#42;1^ e em Tafnes.
Digam: ‘Tomem as vossas posições e preparem-se,
Pois uma espada devorará tudo ao vosso redor.

[NOTE]
====
. Ou: “Mênfis”.
====

[[v24-46-15]]

^<<v24-46-15,15>>^ Porque é que os vossos homens fortes foram eliminados?
Eles não se mantiveram firmes,
Pois Jeová derrubou-os.

[[v24-46-16]]

^<<v24-46-16,16>>^ Eles tropeçam e caem em grande número.
Dizem uns aos outros:
“Vamos! Voltemos imediatamente ao nosso povo e à nossa terra,
Por causa da espada cruel.”’

[[v24-46-17]]

^<<v24-46-17,17>>^ Ali proclamam:
‘O Faraó, rei do Egito, não passa de um barulho insignificante
Que deixou passar a oportunidade.’^&#42;1^

[NOTE]
====
. Lit.: “o tempo determinado”.
====

[[v24-46-18]]

^<<v24-46-18,18>>^ ‘Tão certo como eu vivo’, diz o Rei, cujo nome é Jeová dos exércitos,
‘Ele^&#42;1^ virá como o Tabor, que fica entre os montes,
E como o Carmelo, que fica junto ao mar.

[NOTE]
====
. Isto é, o conquistador do Egito.
====

[[v24-46-19]]

^<<v24-46-19,19>>^ Prepara a tua bagagem para o exílio,
Ó filha e habitante do Egito.
Pois Nofe^&#42;1^ irá tornar-se um motivo de terror;
Será incendiada^&#42;2^ e deixada sem nenhum habitante.

[NOTE]
====
. Ou: “Mênfis”.
. Ou, possivelmente: “Será transformada num deserto”.
====

[[v24-46-20]]

^<<v24-46-20,20>>^ O Egito é como uma bela novilha,
Mas virão mosquitos contra ela desde o norte.

[[v24-46-21]]

^<<v24-46-21,21>>^ Até os seus soldados contratados são como bezerros gordos no seu meio,
Mas eles também deram meia-volta e fugiram juntos.
Não se mantiveram firmes,
Pois chegou o dia da sua calamidade,
O tempo do seu ajuste de contas.’

[[v24-46-22]]

^<<v24-46-22,22>>^ ‘O som dela é como o de uma serpente que desliza,
Pois eles vêm contra ela com força, com machados,
Como homens que derrubam árvores.^&#42;1^

[NOTE]
====
. Ou: “apanham lenha”.
====

[[v24-46-23]]

^<<v24-46-23,23>>^ Eles derrubarão a sua floresta’, diz Jeová, ‘embora pareça impenetrável.
Pois eles são mais numerosos do que gafanhotos; são incontáveis.

[[v24-46-24]]

^<<v24-46-24,24>>^ A filha do Egito será envergonhada.
Será entregue nas mãos do povo do norte.’

[[v24-46-25]]

^<<v24-46-25,25>>^ “Jeová dos exércitos, o Deus de Israel, diz: ‘Agora, vou voltar a minha atenção para Amom de Nó,^&#42;1^ para o Faraó, para o Egito, para os seus deuses e para os seus reis, sim, para o Faraó e para todos os que confiam nele.’

[NOTE]
====
. Isto é, Tebas.
====

[[v24-46-26]]

^<<v24-46-26,26>>^ “‘Vou entregá-los aos que procuram tirar-lhes a vida,^&#42;1^ a Nabucodonosor,^&#42;2^ rei de Babilónia, e aos seus servos. Porém, depois disso, ela^&#42;3^ será novamente habitada, assim como no passado’, diz Jeová.

[NOTE]
====
. Ou: “procuram a sua alma”.
. Lit.: “Nabucodorosor”, grafia variante.
. Isto é, a nação do Egito.
====

[[v24-46-27]]

^<<v24-46-27,27>>^ ‘Quanto a ti, meu servo Jacó, não tenhas medo,
E não fiques apavorado, ó Israel.
Pois vou salvar-te do lugar distante;
E a tua descendência,^&#42;1^ da terra do cativeiro.
Jacó voltará, e viverá tranquilo e em paz,
Sem que ninguém o faça ter medo.

[NOTE]
====
. Lit.: “semente”.
====

[[v24-46-28]]

^<<v24-46-28,28>>^ Não tenhas medo, meu servo Jacó’, diz Jeová, ‘pois eu estou contigo.
Vou exterminar todas as nações por onde te espalhei,
Mas, a ti, não te vou exterminar.
Vou disciplinar-te^&#42;1^ no devido grau;
De modo nenhum te deixarei impune.’”

[NOTE]
====
. Ou: “corrigir-te”.
====

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]