include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-42-1]]

^<<v24-42-1,1>>^ Então, todos os chefes do exército, incluindo Joanã, filho de Careá; Jezanias, filho de Osaías; e todo o povo, desde o menor até ao maior, aproximaram-se

[[v24-42-2]]

^<<v24-42-2,2>>^ e disseram ao profeta Jeremias: “Por favor, ouve o nosso pedido de favor e ora por nós a Jeová, teu Deus, sim, por todo este restante, pois, como vês, de muitos restaram só uns poucos.

[[v24-42-3]]

^<<v24-42-3,3>>^ Que Jeová, teu Deus, nos diga o caminho que devemos seguir e o que devemos fazer.”

[[v24-42-4]]

^<<v24-42-4,4>>^ O profeta Jeremias respondeu-lhes: “Está bem. Vou orar a Jeová, vosso Deus, conforme pediram; e vou contar-vos cada palavra que Jeová me mandar responder-vos. Não vos esconderei nenhuma palavra.”

[[v24-42-5]]

^<<v24-42-5,5>>^ Eles disseram a Jeremias: “Que Jeová seja testemunha verdadeira e fiel contra nós, se não fizermos exatamente como Jeová, teu Deus, nos instruir por meio de ti.

[[v24-42-6]]

^<<v24-42-6,6>>^ Independentemente de a sua palavra ser boa ou má, obedeceremos à voz de Jeová, nosso Deus, a quem te enviamos, para que sejamos bem-sucedidos, visto que obedeceremos à voz de Jeová, nosso Deus.”

[[v24-42-7]]

^<<v24-42-7,7>>^ Dez dias depois, Jeremias recebeu a palavra de Jeová.

[[v24-42-8]]

^<<v24-42-8,8>>^ Então, chamou Joanã, filho de Careá, todos os chefes do exército que estavam com ele, e todo o povo, desde o menor até ao maior,

[[v24-42-9]]

^<<v24-42-9,9>>^ e disse-lhes: “Assim diz Jeová, o Deus de Israel, a quem me enviaram para apresentar o vosso pedido de favor:

[[v24-42-10]]

^<<v24-42-10,10>>^ ‘Se realmente permanecerem nesta terra, vou edificar-vos e não vos derrubarei, e vou plantar-vos e não vos arrancarei, pois lamentarei a^&#42;1^ calamidade que vos causei.

[NOTE]
====
. Ou: “sentirei pesar por causa da”.
====

[[v24-42-11]]

^<<v24-42-11,11>>^ Não tenham medo do rei de Babilónia, a quem temem.’
“‘Não tenham medo dele’, diz Jeová, ‘pois estou convosco para vos salvar e livrar das suas mãos.

[[v24-42-12]]

^<<v24-42-12,12>>^ Vou mostrar-vos misericórdia, e ele terá misericórdia de vocês e fará com que voltem à vossa terra.

[[v24-42-13]]

^<<v24-42-13,13>>^ “‘Contudo, se disserem: “Não, nós não vamos ficar nesta terra!”, e desobedecerem à voz de Jeová, vosso Deus,

[[v24-42-14]]

^<<v24-42-14,14>>^ dizendo: “Não, iremos antes para a terra do Egito, onde não veremos guerras, nem ouviremos o som da buzina, nem passaremos fome; lá é que moraremos”,

[[v24-42-15]]

^<<v24-42-15,15>>^ então, ouçam a palavra de Jeová, ó restante de Judá. Assim diz Jeová dos exércitos, o Deus de Israel: “Se estiverem firmemente decididos a ir para o Egito e forem viver para lá,^&#42;1^

[NOTE]
====
. Ou: “morar lá por um tempo”.
====

[[v24-42-16]]

^<<v24-42-16,16>>^ a mesma espada de que têm medo há de alcançar-vos na terra do Egito, e a mesma fome que temem há de seguir-vos até ao Egito, e lá hão de morrer.

[[v24-42-17]]

^<<v24-42-17,17>>^ E todos os homens que estiverem decididos a ir morar para o Egito morrerão pela espada, pela fome e pela peste.^&#42;1^ Nenhum deles sobreviverá nem escapará da calamidade que lhes vou trazer.”’

[NOTE]
====
. Ou: “doença”.
====

[[v24-42-18]]

^<<v24-42-18,18>>^ “Pois assim diz Jeová dos exércitos, o Deus de Israel: ‘Assim como derramei a minha ira e o meu furor sobre os habitantes de Jerusalém, assim também derramarei sobre vocês o meu furor se forem para o Egito, e hão de tornar-se um objeto de maldição, um motivo de terror, e um alvo de desprezo e de insultos, e nunca mais verão este lugar.’

[[v24-42-19]]

^<<v24-42-19,19>>^ “Jeová falou contra vocês, ó restante de Judá. Não vão para o Egito. Tenham bem em mente que eu vos avisei hoje

[[v24-42-20]]

^<<v24-42-20,20>>^ de que o vosso erro vai custar-vos a vida.^&#42;1^ Pois foram vocês mesmos que me enviaram a Jeová, vosso Deus, dizendo: ‘Ora por nós a Jeová, nosso Deus, e diz-nos tudo o que Jeová, nosso Deus, disser, e nós assim o faremos.’

[NOTE]
====
. Ou: “alma”.
====

[[v24-42-21]]

^<<v24-42-21,21>>^ E, hoje,  disse-vos estas palavras, mas vocês não obedecerão à voz de Jeová, vosso Deus, nem farão nada do que ele me mandou dizer-vos.

[[v24-42-22]]

^<<v24-42-22,22>>^ Por isso, estejam certos de que morrerão pela espada, pela fome e pela peste no lugar para onde desejam ir viver.”

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]