include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-32-1]]

^<<v24-32-1,1>>^ No décimo ano de Zedequias, rei de Judá, isto é, no décimo oitavo ano de Nabucodonosor,^&#42;1^ Jeremias recebeu a palavra de Jeová.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-32-2]]

^<<v24-32-2,2>>^ Naquele tempo, os exércitos do rei de Babilónia cercavam Jerusalém, e o profeta Jeremias estava detido no Pátio da Guarda, na casa^&#42;1^ do rei de Judá.

[NOTE]
====
. Ou: “no palácio”.
====

[[v24-32-3]]

^<<v24-32-3,3>>^ Pois Zedequias, rei de Judá, tinha-o detido, dizendo: “Porque é que profetizas estas coisas? Dizes: ‘Assim diz Jeová: “Entregarei esta cidade nas mãos do rei de Babilónia, e ele irá capturá-la;

[[v24-32-4]]

^<<v24-32-4,4>>^ e Zedequias, rei de Judá, não escapará dos caldeus, pois, sem falta, será entregue nas mãos do rei de Babilónia, e falará com ele face a face, olhos nos olhos.”’

[[v24-32-5]]

^<<v24-32-5,5>>^ ‘Ele levará Zedequias para Babilónia, e este continuará lá até que eu volte a minha atenção para ele’, diz Jeová. ‘Mesmo que vocês continuem a lutar contra os caldeus, não serão bem-sucedidos.’”

[[v24-32-6]]

^<<v24-32-6,6>>^ Jeremias disse: “Recebi a seguinte palavra de Jeová:

[[v24-32-7]]

^<<v24-32-7,7>>^ ‘Hanamel, filho do teu tio^&#42;1^ Salum, virá ter contigo e dirá: “Compra o meu campo em Anatote, pois tens a preferência no direito de resgate.”’”

[NOTE]
====
. Isto é, tio paterno.
====

[[v24-32-8]]

^<<v24-32-8,8>>^ Assim como Jeová tinha dito, Hanamel, filho do meu tio, veio ter comigo no Pátio da Guarda e disse-me: “Por favor, compra o meu campo em Anatote, na terra de Benjamim, pois tens o direito de tomar posse dele e de resgatá-lo. Compra-o para ti.” Então, percebi que era a palavra de Jeová.

[[v24-32-9]]

^<<v24-32-9,9>>^ Portanto, comprei o campo em Anatote a Hanamel, filho do meu tio. Pesei o dinheiro para lhe dar: sete siclos^&#42;1^ e dez peças de prata.

[NOTE]
====
. Um siclo equivalia a 11,4 g. Veja o Ap. B14.
====

[[v24-32-10]]

^<<v24-32-10,10>>^ De seguida, registei-o numa escritura, selei-a, convoquei testemunhas e pesei o dinheiro na balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ Peguei na escritura de compra que estava selada segundo o mandamento e as exigências legais, bem como na que foi deixada sem selo;

[[v24-32-12]]

^<<v24-32-12,12>>^ e entreguei a escritura de compra a Baruque, filho de Nerias, filho de Maseias, na presença de Hanamel, filho do meu tio, das testemunhas que tinham assinado a escritura de compra, e de todos os judeus que estavam sentados no Pátio da Guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ Depois, ordenei a Baruque, diante deles:

[[v24-32-14]]

^<<v24-32-14,14>>^ “Assim diz Jeová dos exércitos, o Deus de Israel: ‘Pega nessas escrituras, na escritura de compra selada e na outra escritura, que foi deixada sem selo, e coloca-as num vaso de barro, para que durem muito tempo.’

[[v24-32-15]]

^<<v24-32-15,15>>^ Pois assim diz Jeová dos exércitos, o Deus de Israel: ‘Nesta terra, serão novamente comprados casas, campos e vinhas .’”

[[v24-32-16]]

^<<v24-32-16,16>>^ Depois de ter dado a escritura de compra a Baruque, filho de Nerias, orei a Jeová, dizendo:

[[v24-32-17]]

^<<v24-32-17,17>>^ “Ai, Soberano Senhor Jeová! Tu fizeste os céus e a terra com o teu grande poder e o teu braço estendido. Nada é impossível para ti,

[[v24-32-18]]

^<<v24-32-18,18>>^ aquele que demonstra amor leal a milhares, mas traz a retribuição dos erros dos pais sobre os^&#42;1^ filhos. Tu és o verdadeiro Deus, o Grande e Poderoso, cujo nome é Jeová dos exércitos.

[NOTE]
====
. Lit.: “ao seio dos”.
====

[[v24-32-19]]

^<<v24-32-19,19>>^ Os teus propósitos são grandiosos,^&#42;1^ e os teus atos são poderosos; os teus olhos observam todos os caminhos dos homens, para retribuir a cada um conforme os seus caminhos e conforme as suas ações.

[NOTE]
====
. Ou: “O teu conselho é grandioso”. Lit.: “Tu és grande em conselho”.
====

[[v24-32-20]]

^<<v24-32-20,20>>^ Tu realizaste sinais e milagres na terra do Egito, que são conhecidos até hoje, e assim fizeste um nome para ti em Israel e entre a humanidade, assim como se vê hoje.

[[v24-32-21]]

^<<v24-32-21,21>>^ E tiraste o teu povo Israel da terra do Egito com sinais, milagres, mão poderosa, braço estendido e atos atemorizantes.

[[v24-32-22]]

^<<v24-32-22,22>>^ “Com o tempo, deste-lhes esta terra, que tinhas jurado dar aos seus antepassados, uma terra que mana leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ E eles entraram e tomaram posse dela, mas não obedeceram à tua voz nem andaram na tua lei. Não fizeram nada do que lhes ordenaste, de modo que trouxeste sobre eles toda esta calamidade.

[[v24-32-24]]

^<<v24-32-24,24>>^ Vê! Já chegaram com rampas de ataque para se apoderarem da cidade, e ela certamente cairá nas mãos dos caldeus que lutam contra ela, por causa da espada, da fome e da peste;^&#42;1^ tudo o que disseste aconteceu, como podes ver.

[NOTE]
====
. Ou: “doença”.
====

[[v24-32-25]]

^<<v24-32-25,25>>^ Mas tu disseste-me, ó Soberano Senhor Jeová: ‘Compra o campo com dinheiro e convoca testemunhas’, embora a cidade, com certeza, venha a ser entregue nas mãos dos caldeus.”

[[v24-32-26]]

^<<v24-32-26,26>>^ Então, Jeremias recebeu a seguinte palavra de Jeová:

[[v24-32-27]]

^<<v24-32-27,27>>^ “Eu sou Jeová, o Deus de toda a humanidade.^&#42;1^ Existe alguma coisa que seja impossível para mim?

[NOTE]
====
. Lit.: “toda a carne”.
====

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto, assim diz Jeová: ‘Vou entregar esta cidade aos caldeus e nas mãos de Nabucodonosor,^&#42;1^ rei de Babilónia, e ele irá apoderar-se dela.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-32-29]]

^<<v24-32-29,29>>^ E os caldeus que lutam contra esta cidade hão de entrar e deitar-lhe fogo. Vão queimá-la com as casas em cujos terraços o povo ofereceu sacrifícios a Baal e derramou ofertas de bebida a outros deuses, a fim de me ofender.’

[[v24-32-30]]

^<<v24-32-30,30>>^ “‘Pois o povo de Israel e de Judá tem feito o que é mau aos meus olhos, desde a sua juventude; o povo de Israel ofende-me com as obras das suas mãos’, diz Jeová.

[[v24-32-31]]

^<<v24-32-31,31>>^ ‘Desde o dia em que foi construída até hoje, esta cidade tem provocado a minha ira e o meu furor, de modo que a removerei de diante da minha face,

[[v24-32-32]]

^<<v24-32-32,32>>^ por causa de toda a maldade que o povo de Israel e de Judá tem feito para me ofender — eles, os seus reis, os seus príncipes, os seus sacerdotes, os seus profetas, os homens de Judá e os habitantes de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ Eles persistiram em virar-me as costas, em vez de virarem o rosto para mim. Embora eu tentasse ensiná-los vez após vez,^&#42;1^ nenhum deles escutava para receber disciplina.

[NOTE]
====
. Lit.: “Embora se lhes ensinasse, levantando cedo e ensinando”.
====

[[v24-32-34]]

^<<v24-32-34,34>>^ E colocaram os seus ídolos repugnantes na casa que leva o meu nome, a fim de profaná-la.

[[v24-32-35]]

^<<v24-32-35,35>>^ Além disso, construíram os altos sagrados de Baal, no vale do Filho de Hinom,^&#42;1^ para queimarem os seus filhos e as suas filhas no fogo^&#42;2^ a Moloque. Eu não lhes tinha ordenado que o fizessem. Nunca me tinha ocorrido no coração^&#42;3^ pedir-lhes que fizessem tal coisa detestável, levando assim Judá a pecar.’

[NOTE]
====
. Veja o Glossário, “Geena”.
. Ou: “fazerem os seus filhos e as suas filhas passar pelo fogo”.
. Ou: “Nunca me tinha passado pela mente”.
====

[[v24-32-36]]

^<<v24-32-36,36>>^ “Portanto, assim diz Jeová, o Deus de Israel, com respeito a esta cidade que vocês dizem que será entregue nas mãos do rei de Babilónia pela espada, pela fome e pela peste:

[[v24-32-37]]

^<<v24-32-37,37>>^ ‘Vou reuni-los dentre todas as terras pelas quais os espalhei com ira, furor e grande indignação, e vou trazê-los a este lugar para viverem em segurança.

[[v24-32-38]]

^<<v24-32-38,38>>^ E eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ E vou dar-lhes um só coração e um só caminho para que me temam sempre, para o bem deles e para o bem dos seus filhos depois deles.

[[v24-32-40]]

^<<v24-32-40,40>>^ E vou fazer um pacto eterno com eles: não deixarei de lhes fazer o bem. Porei no seu coração o temor de mim para que não se desviem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ Vou alegrar-me em fazer-lhes o bem, vou plantá-los firmemente nesta terra, de todo o meu coração e de toda a minha alma.’”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v24-32-42]]

^<<v24-32-42,42>>^ “Pois assim diz Jeová: ‘Assim como eu trouxe sobre este povo toda esta grande calamidade, assim também vou trazer sobre eles todas as coisas boas^&#42;1^ que lhes prometo.

[NOTE]
====
. Ou: “toda a bondade”.
====

[[v24-32-43]]

^<<v24-32-43,43>>^ E hão de se comprar novamente campos nesta terra, embora vocês digam: “Ela está desolada, sem homens nem animais, e foi entregue às mãos dos caldeus.”’

[[v24-32-44]]

^<<v24-32-44,44>>^ “‘Campos serão comprados com dinheiro, escrituras de compra serão registadas e seladas, e testemunhas serão convocadas na terra de Benjamim, nos arredores de Jerusalém, nas cidades de Judá, nas cidades da região montanhosa, nas cidades da planície e nas cidades do sul, pois trarei de volta o seu povo cativo’, diz Jeová.”

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]