include::./index.adoc[]

[[v24-7-0]]
=== Jeremias, 7
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-7-1]]

^<<v24-7-1,1>>^ Jeremias recebeu de Jeová a seguinte palavra:

[[v24-7-2]]

^<<v24-7-2,2>>^ “Põe-te no portão da casa de Jeová e, lá, proclama esta mensagem: ‘Ouçam a palavra de Jeová, todos vocês, os de Judá, que entram por estes portões para se curvarem diante de Jeová.

[[v24-7-3]]

^<<v24-7-3,3>>^ Assim diz Jeová dos exércitos, o Deus de Israel: “Corrijam os vossos caminhos e as vossas ações, e eu permitirei que continuem a morar neste lugar.

[[v24-7-4]]

^<<v24-7-4,4>>^ Não confiem em palavras enganosas nem digam: ‘Este é^&#42;1^ o templo de Jeová, o templo de Jeová, o templo de Jeová!’

[NOTE]
====
. Lit.: “Eles são”, referindo-se a todos os edifícios do complexo do templo.
====

[[v24-7-5]]

^<<v24-7-5,5>>^ Pois, se realmente corrigirem os vossos caminhos e as vossas ações, se realmente defenderem a justiça nas causas entre um homem e o seu próximo,

[[v24-7-6]]

^<<v24-7-6,6>>^ se não oprimirem os residentes estrangeiros, os órfãos^&#42;1^ e as viúvas, se não derramarem sangue inocente neste lugar e se não seguirem outros deuses para o vosso próprio prejuízo,

[NOTE]
====
. Ou: “órfãos de pai”.
====

[[v24-7-7]]

^<<v24-7-7,7>>^ então, permitirei que continuem a morar neste lugar, na terra que dei aos vossos antepassados para sempre.”’”^&#42;1^

[NOTE]
====
. Ou: “de eternidade a eternidade”.
====

[[v24-7-8]]

^<<v24-7-8,8>>^ “Vocês confiam em palavras enganosas, e isso não adiantará absolutamente nada.

[[v24-7-9]]

^<<v24-7-9,9>>^ Será que podem roubar, assassinar, cometer adultério, jurar falsamente, fazer sacrifícios^&#42;1^ a Baal e seguir outros deuses que não conheciam,

[NOTE]
====
. Ou: “fumo sacrificial”.
====

[[v24-7-10]]

^<<v24-7-10,10>>^ e depois comparecer diante de mim nesta casa que leva o meu nome e dizer: ‘Estamos a salvo’, apesar de fazerem todas estas coisas detestáveis?

[[v24-7-11]]

^<<v24-7-11,11>>^ Será que esta casa que leva o meu nome se tornou um covil de ladrões aos vossos olhos? Saibam que eu próprio estou a ver isso”, diz Jeová.

[[v24-7-12]]

^<<v24-7-12,12>>^ “‘Portanto, vão ao meu santuário em Silo, o primeiro lugar onde fiz residir o meu nome, e vejam o que lhe fiz por causa da maldade do meu povo Israel.

[[v24-7-13]]

^<<v24-7-13,13>>^ No entanto, vocês continuaram a fazer todas estas coisas’, diz Jeová, ‘e, embora eu tenha falado convosco vez após vez,^&#42;1^ não me deram ouvidos. Eu chamava-vos continuamente, mas vocês não respondiam.

[NOTE]
====
. Lit.: “convosco, levantando-me cedo e falando”.
====

[[v24-7-14]]

^<<v24-7-14,14>>^ Por isso, vou fazer com a casa que leva o meu nome — a casa em que confiam, o lugar que vos dei a vocês e aos vossos antepassados — o mesmo que fiz com Silo.

[[v24-7-15]]

^<<v24-7-15,15>>^ Vou expulsar-vos da minha presença, assim como expulsei todos os vossos irmãos, todos os descendentes de Efraim.’

[[v24-7-16]]

^<<v24-7-16,16>>^ “Quanto a ti, não ores por esse povo. Não clames, nem ores ou supliques por eles, pois não te vou ouvir.

[[v24-7-17]]

^<<v24-7-17,17>>^ Não vês o que eles fazem nas cidades de Judá e nas ruas de Jerusalém?

[[v24-7-18]]

^<<v24-7-18,18>>^ Os filhos apanham lenha, os pais acendem o fogo, e as esposas batem a massa para fazer bolos de oferenda à Rainha do Céu;^&#42;1^ e eles derramam ofertas de bebida a outros deuses para me ofenderem.

[NOTE]
====
. Título de uma deusa adorada pelos israelitas apóstatas, possivelmente uma deusa da fertilidade.
====

[[v24-7-19]]

^<<v24-7-19,19>>^ ‘Será que é a mim que estão a prejudicar?’,^&#42;1^ diz Jeová. ‘Não é a si mesmos, para a sua própria vergonha?’

[NOTE]
====
. Ou: “ofender; provocar”.
====

[[v24-7-20]]

^<<v24-7-20,20>>^ Portanto, assim diz o Soberano Senhor Jeová: ‘Vejam! A minha ira e o meu furor serão derramados sobre este lugar, sobre os homens e os animais, sobre as árvores do campo e os frutos da terra; ela arderá e não se apagará.’

[[v24-7-21]]

^<<v24-7-21,21>>^ “Assim diz Jeová dos exércitos, o Deus de Israel: ‘Vão em frente, juntem as vossas ofertas queimadas aos vossos outros sacrifícios, e comam a carne.

[[v24-7-22]]

^<<v24-7-22,22>>^ Pois, no dia em que tirei os vossos antepassados da terra do Egito, eu não lhes disse nem ordenei nada a respeito de ofertas queimadas e sacrifícios.

[[v24-7-23]]

^<<v24-7-23,23>>^ Contudo, esta foi a ordem que lhes dei: “Obedeçam à minha voz, e eu vou tornar-me o vosso Deus, e vocês vão tornar-se o meu povo. Andem sempre no caminho que eu vos ordenar, para que tudo vá bem convosco.”’

[[v24-7-24]]

^<<v24-7-24,24>>^ Eles, porém, não deram ouvidos nem prestaram atenção;^&#42;1^ em vez disso, andaram conforme os seus próprios planos,^&#42;2^ teimando em seguir o seu coração mau. Andaram para trás, não para a frente,

[NOTE]
====
. Ou: “nem inclinaram o seu ouvido”.
. Ou: “o seu próprio conselho”.
====

[[v24-7-25]]

^<<v24-7-25,25>>^ desde o dia em que os vossos antepassados saíram da terra do Egito até hoje. Por isso, eu enviava-vos todos os meus servos, os profetas; enviava-os dia após dia, vez após vez.^&#42;1^

[NOTE]
====
. Lit.: “os profetas; diariamente levantando-me cedo e enviando”.
====

[[v24-7-26]]

^<<v24-7-26,26>>^ Esse povo, porém, não me quis ouvir, nem prestou atenção.^&#42;1^ Em vez disso, foram obstinados^&#42;2^ e agiram pior do que os seus antepassados!

[NOTE]
====
. Ou: “nem inclinou o seu ouvido”.
. Lit.: “endureceram a sua cerviz”.
====

[[v24-7-27]]

^<<v24-7-27,27>>^ “Irás dizer-lhes todas estas palavras, mas eles não te darão ouvidos; irás chamá-los, mas eles não te responderão.

[[v24-7-28]]

^<<v24-7-28,28>>^ E irás dizer-lhes: ‘Esta é a nação que não obedeceu à voz de Jeová, seu Deus, nem quis aceitar a disciplina. A fidelidade desapareceu, e não é sequer mencionada entre eles.’^&#42;1^

[NOTE]
====
. Lit.: “e está decepada da sua boca”.
====

[[v24-7-29]]

^<<v24-7-29,29>>^ “Rapa o teu cabelo^&#42;1^ e deita-o fora, e canta uma canção de luto nas colinas sem vegetação, pois Jeová rejeitou e vai abandonar esta geração que o enfureceu.

[NOTE]
====
. Ou: “cabelo não cortado; cabelo dedicado”.
====

[[v24-7-30]]

^<<v24-7-30,30>>^ ‘Pois o povo de Judá fez o que é mau aos meus olhos’, diz Jeová. ‘Colocaram os seus ídolos repugnantes na casa que leva o meu nome, a fim de profaná-la.

[[v24-7-31]]

^<<v24-7-31,31>>^ Construíram os altos sagrados de Tofete, que fica no vale do Filho de Hinom,^&#42;1^ para queimarem os seus filhos e as suas filhas no fogo, algo que eu não tinha ordenado e que nunca me tinha ocorrido no coração.’^&#42;2^

[NOTE]
====
. Veja o Glossário, “Geena”.
. Ou: “nunca me tinha passado pela mente”.
====

[[v24-7-32]]

^<<v24-7-32,32>>^ “‘Portanto, estão a chegar os dias’, diz Jeová, ‘em que este lugar não voltará a ser chamado Tofete ou vale do Filho de Hinom,^&#42;1^ mas, antes, vale da Matança. Eles enterrarão os mortos em Tofete até que já não haja lá lugar.

[NOTE]
====
. Veja o Glossário, “Geena”.
====

[[v24-7-33]]

^<<v24-7-33,33>>^ E os cadáveres deste povo irão tornar-se comida para as aves dos céus e para os animais da terra, e não haverá ninguém para os espantar.

[[v24-7-34]]

^<<v24-7-34,34>>^ Porei fim ao som de exultação e ao som de alegria, à voz do noivo e à voz da noiva, nas cidades de Judá e nas ruas de Jerusalém, pois esta terra será reduzida a ruínas.’”

'''

xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[Próximo Capítulo &#62;]