include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-33-1]]

^<<v24-33-1,1>>^ Enquanto ainda estava detido no Pátio da Guarda, Jeremias recebeu a palavra de Jeová pela segunda vez:

[[v24-33-2]]

^<<v24-33-2,2>>^ “Assim diz Jeová, aquele que fez a terra, Jeová, aquele que a formou e a estabeleceu firmemente; Jeová é o seu nome:

[[v24-33-3]]

^<<v24-33-3,3>>^ ‘Chama por mim, e eu vou responder-te e contar-te prontamente coisas grandes e incompreensíveis, que não sabes.’”

[[v24-33-4]]

^<<v24-33-4,4>>^ “Pois assim diz Jeová, o Deus de Israel, a respeito das casas desta cidade e das casas dos reis de Judá, que estão a ser demolidas para servirem de defesa contra as rampas de ataque e contra a espada,

[[v24-33-5]]

^<<v24-33-5,5>>^ e a respeito dos que vêm para lutar contra os caldeus, enchendo as casas com os corpos daqueles que matei na minha ira e no meu furor, cuja maldade me levou a esconder a minha face desta cidade:

[[v24-33-6]]

^<<v24-33-6,6>>^ ‘Vou restabelecê-la e dar-lhe saúde; vou curá-los e proporcionar-lhes abundância de paz e segurança.^&#42;1^

[NOTE]
====
. Ou: “verdade”.
====

[[v24-33-7]]

^<<v24-33-7,7>>^ Vou trazer de volta o meu povo cativo, Judá e Israel, e vou edificá-los como fiz no princípio.

[[v24-33-8]]

^<<v24-33-8,8>>^ E vou purificá-los de toda a culpa pelos seus pecados contra mim, e vou perdoar toda a culpa pelos seus erros e pelas suas transgressões contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ E ela será a minha fama, a minha alegria, o meu louvor e a minha glória^&#42;1^ diante de todas as nações da terra que ouvirem falar de todas as coisas boas^&#42;2^ que lhes concedo. E as nações ficarão apavoradas e tremerão por causa de todas as coisas boas^&#42;3^ e da paz que lhe concederei.’”

[NOTE]
====
. Ou: “beleza”.
. Ou: “toda a bondade”.
. Ou: “toda a bondade”.
====

[[v24-33-10]]

^<<v24-33-10,10>>^ “Assim diz Jeová: ‘Neste lugar que afirmam ser um deserto, sem homens nem animais, isto é, nas cidades de Judá e nas ruas de Jerusalém, que estão desoladas, sem homens, nem habitantes, nem animais, ali se ouvirá novamente

[[v24-33-11]]

^<<v24-33-11,11>>^ o som de exultação e o som de alegria, a voz do noivo e a voz da noiva, a voz dos que dizem: “Agradeçam a Jeová dos exércitos, pois Jeová é bom; o seu amor leal dura para sempre!”’
“‘Trarão ofertas de agradecimento à casa de Jeová, pois eu trarei de volta os que foram levados cativos desta terra, e eles voltarão a ser como eram no princípio’, diz Jeová.”

[[v24-33-12]]

^<<v24-33-12,12>>^ “Assim diz Jeová dos exércitos: ‘Neste lugar deserto, sem homens nem animais, e em todas as suas cidades, voltará a haver pastagens onde os pastores levarão os seus rebanhos para descansar.’

[[v24-33-13]]

^<<v24-33-13,13>>^ “‘Nas cidades da região montanhosa, nas cidades da planície, nas cidades do sul, na terra de Benjamim, nos arredores de Jerusalém e nas cidades de Judá, os pastores contarão novamente as ovelhas à medida que passarem debaixo das suas mãos’, diz Jeová.”

[[v24-33-14]]

^<<v24-33-14,14>>^ “‘Vejam! Estão a chegar os dias’, diz Jeová, ‘em que cumprirei a boa promessa que fiz a respeito da casa de Israel e da casa de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ Nesses dias e nesse tempo, farei brotar um renovo^&#42;1^ justo para David, e ele defenderá a justiça e a retidão no país.

[NOTE]
====
. Ou: “herdeiro”.
====

[[v24-33-16]]

^<<v24-33-16,16>>^ Nesses dias, Judá será salvo e Jerusalém residirá em segurança. E este será o seu nome: Jeová É a Nossa Justiça.’”

[[v24-33-17]]

^<<v24-33-17,17>>^ “Pois assim diz Jeová: ‘Haverá sempre um descendente de David para se sentar no trono da casa de Israel,

[[v24-33-18]]

^<<v24-33-18,18>>^ e haverá sempre diante de mim um dos sacerdotes levíticos para fazer ofertas queimadas, queimar ofertas de cereais e oferecer sacrifícios.’”

[[v24-33-19]]

^<<v24-33-19,19>>^ E Jeremias recebeu novamente a palavra de Jeová:

[[v24-33-20]]

^<<v24-33-20,20>>^ “Assim diz Jeová: ‘Se pudessem invalidar o meu pacto do dia e o meu pacto da noite, para que não houvesse dia e noite no tempo determinado,

[[v24-33-21]]

^<<v24-33-21,21>>^ só nesse caso é que se poderia invalidar o meu pacto com David, meu servo, para que ele não tivesse um filho a reinar no seu trono, e também o meu pacto com os sacerdotes levíticos, meus servos.^&#42;1^

[NOTE]
====
. Ou: “ministros”.
====

[[v24-33-22]]

^<<v24-33-22,22>>^ Assim como não se pode contar o exército dos céus, nem se pode medir a areia do mar, assim multiplicarei a descendência^&#42;1^ de David, meu servo, e os levitas que me servem.’”

[NOTE]
====
. Lit.: “semente”.
====

[[v24-33-23]]

^<<v24-33-23,23>>^ E Jeremias recebeu novamente a palavra de Jeová:

[[v24-33-24]]

^<<v24-33-24,24>>^ “Não ouviste o que este povo está a dizer: ‘Jeová rejeitará as duas famílias que escolheu’? E eles estão a tratar o meu próprio povo com desrespeito; já não os consideram como uma nação.

[[v24-33-25]]

^<<v24-33-25,25>>^ “Assim diz Jeová: ‘Tão certo como estabeleci o meu pacto do dia e da noite, as leis^&#42;1^ do céu e da terra,

[NOTE]
====
. Ou: “os decretos”.
====

[[v24-33-26]]

^<<v24-33-26,26>>^ nunca rejeitarei a descendência^&#42;1^ de Jacó e de David, meu servo, deixando de escolher dentre a sua descendência^&#42;2^ os governantes sobre os descendentes^&#42;3^ de Abraão, Isaque e Jacó. Pois trarei de volta o seu povo cativo e terei compaixão deles.’”

[NOTE]
====
. Lit.: “semente”.
. Lit.: “semente”.
. Lit.: “a semente”.
====

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]