include::./index.adoc[]

[[v24-24-0]]
=== Jeremias, 24
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-24-1]]

^<<v24-24-1,1>>^ Então, Jeová mostrou-me dois cestos de figos postos diante do templo de Jeová, depois de Nabucodonosor,^&#42;1^ rei de Babilónia, ter levado para o exílio Jeconias,^&#42;2^ filho de Jeoiaquim e rei de Judá, juntamente com os príncipes de Judá, os artesãos e os trabalhadores em metal;^&#42;3^ ele levou-os de Jerusalém para Babilónia.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
. Também chamado Joaquim e Conias.
. Ou, possivelmente: “construtores de fortificações”.
====

[[v24-24-2]]

^<<v24-24-2,2>>^ Um cesto tinha figos muito bons, iguais a figos temporãos, mas o outro cesto tinha figos muito maus, tão maus que nem se podiam comer.

[[v24-24-3]]

^<<v24-24-3,3>>^ Depois, Jeová perguntou-me: “O que é que estás a ver, Jeremias?” E eu respondi: “Figos; os figos bons são muito bons, mas os maus são muito maus, tão maus que nem se podem comer.”

[[v24-24-4]]

^<<v24-24-4,4>>^ De seguida, recebi a seguinte palavra de Jeová:

[[v24-24-5]]

^<<v24-24-5,5>>^ “Isto é o que diz Jeová, o Deus de Israel: ‘Assim como estes figos bons, considerarei bons os exilados de Judá, que mandei embora deste lugar para a terra dos caldeus.

[[v24-24-6]]

^<<v24-24-6,6>>^ Manterei os meus olhos neles para o seu bem e vou fazê-los voltar a esta terra. Vou edificá-los e não os derrubarei; vou plantá-los e não os arrancarei.

[[v24-24-7]]

^<<v24-24-7,7>>^ E vou dar-lhes um coração capaz de me conhecer, de saber que eu sou Jeová. Eles vão tornar-se o meu povo, e eu vou tornar-me o seu Deus, pois voltarão para mim de todo o coração.

[[v24-24-8]]

^<<v24-24-8,8>>^ “‘Porém, quanto aos figos maus, que são tão maus que nem se podem comer, isto é o que diz Jeová: “Assim considerarei Zedequias, rei de Judá, os seus príncipes, o restante de Jerusalém que sobrou nesta terra e os que foram viver para a terra do Egito.

[[v24-24-9]]

^<<v24-24-9,9>>^ Farei deles um motivo de terror e de desgraça para todos os reinos da terra. Serão alvo de insultos, assunto de provérbios, motivo de gozo e exemplo de maldição em todos os lugares por onde eu os espalhar.

[[v24-24-10]]

^<<v24-24-10,10>>^ E vou enviar contra eles a espada, a fome e a peste,^&#42;1^ até que desapareçam da terra que lhes dei, a eles e aos seus antepassados.”’”

[NOTE]
====
. Ou: “doença”.
====

'''

xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[Próximo Capítulo &#62;]