include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-5-1]]

^<<v24-5-1,1>>^ Percorram as ruas de Jerusalém.
Olhem em volta e prestem atenção.
Procurem nas suas praças e vejam
Se conseguem encontrar um homem que pratique a justiça,
Que procure ser fiel,
E eu concederei perdão à cidade.

[[v24-5-2]]

^<<v24-5-2,2>>^ Mesmo que eles dissessem: “Tão certo como Jeová vive!”,
Ainda assim, o seu juramento seria falso.

[[v24-5-3]]

^<<v24-5-3,3>>^ Ó Jeová, não é a fidelidade que os teus olhos procuram?
Tu golpeaste-os, mas isso não os afetou.^&#42;1^
Tu exterminaste-os, mas eles recusaram-se a aceitar a disciplina.
Endureceram o seu rosto, mais do que uma rocha,
E recusaram-se a voltar atrás.

[NOTE]
====
. Lit.: “eles não ficaram fracos”.
====

[[v24-5-4]]

^<<v24-5-4,4>>^ Contudo, eu disse para comigo: “Com certeza, eles são pessoas simples.
Agem de modo tolo porque não conhecem o caminho de Jeová,
A justiça do seu Deus.

[[v24-5-5]]

^<<v24-5-5,5>>^ Vou procurar os homens de destaque e falar com eles,
Pois devem conhecer o caminho de Jeová,
A justiça do seu Deus.
Porém, todos eles partiram o jugo
E romperam as suas amarras.”

[[v24-5-6]]

^<<v24-5-6,6>>^ É por isso que um leão da floresta os ataca,
Que um lobo das planícies desérticas os devasta,
Que um leopardo está à espreita perto das suas cidades.
Todo aquele que sai delas é dilacerado.
Pois as suas transgressões são muitas;
Os seus atos infiéis são numerosos.

[[v24-5-7]]

^<<v24-5-7,7>>^ Como é que te posso perdoar por isto?
Os teus filhos abandonaram-me
E juram por aquilo que não é Deus.
Embora eu suprisse as suas necessidades,
Eles cometiam adultério
E iam em bandos à casa de uma prostituta.

[[v24-5-8]]

^<<v24-5-8,8>>^ Eles são como cavalos excitados, cheios de desejo;
Cada um deles relincha para a mulher do próximo.

[[v24-5-9]]

^<<v24-5-9,9>>^ “Não devia eu ajustar contas com eles por causa destas coisas?”, diz Jeová.
“Não devia eu vingar-me^&#42;1^ de uma nação como esta?”

[NOTE]
====
. Ou: “Não devia a minha alma vingar-se”.
====

[[v24-5-10]]

^<<v24-5-10,10>>^ “Venham contra os socalcos das suas vinhas e causem destruição,
Mas não a exterminem totalmente.
Arranquem-lhe os ramos viçosos,
Porque não pertencem a Jeová.

[[v24-5-11]]

^<<v24-5-11,11>>^ Pois a casa de Israel e a casa de Judá
Foram extremamente traiçoeiras comigo”, diz Jeová.

[[v24-5-12]]

^<<v24-5-12,12>>^ “Negaram a Jeová e dizem:
‘Ele não fará nada.^&#42;1^
Não nos acontecerá nenhuma calamidade;
Não veremos a espada nem a fome.’

[NOTE]
====
. Ou, possivelmente: “Ele não existe.”
====

[[v24-5-13]]

^<<v24-5-13,13>>^ Os profetas estão cheios de vento,
E a palavra^&#42;1^ não está neles.
Que isso lhes aconteça!”^&#42;2^

[NOTE]
====
. Isto é, a palavra de Deus.
. Isto é, que sejam reduzidos a nada, como as suas palavras vazias.
====

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto, assim diz Jeová, o Deus dos exércitos:
“Visto que estes homens estão a dizer isso,
Farei das minhas palavras um fogo na tua boca.^&#42;1^
Este povo será como lenha,
E, certamente, o fogo irá consumi-los.”

[NOTE]
====
. Isto é, na boca de Jeremias.
====

[[v24-5-15]]

^<<v24-5-15,15>>^ “Vou trazer de longe uma nação contra vocês, ó casa de Israel”, diz Jeová.
“É uma nação que existe há muito tempo,
Uma nação antiga.
Uma nação cuja língua não conheces,
E cujas palavras não entendes.

[[v24-5-16]]

^<<v24-5-16,16>>^ A sua aljava é como uma sepultura aberta;
Todos eles são guerreiros.

[[v24-5-17]]

^<<v24-5-17,17>>^ Devorarão a tua colheita e o teu pão.
Devorarão os teus filhos e as tuas filhas.
Devorarão os teus bois e as tuas ovelhas.
Devorarão as tuas videiras e as tuas figueiras.
Destruirão pela espada as tuas cidades fortificadas, nas quais confias.”

[[v24-5-18]]

^<<v24-5-18,18>>^ “No entanto, mesmo nesses dias”, diz Jeová, “não vos exterminarei totalmente.

[[v24-5-19]]

^<<v24-5-19,19>>^ E, quando perguntarem: ‘Porque é que Jeová, nosso Deus, nos fez tudo isto?’, deves responder-lhes: ‘Assim como me abandonaram para servir um deus estrangeiro na vossa própria terra, assim também servirão estrangeiros numa terra que não é vossa.’”

[[v24-5-20]]

^<<v24-5-20,20>>^ Declarem o seguinte na casa de Jacó,
E proclamem isto em Judá:

[[v24-5-21]]

^<<v24-5-21,21>>^ “Ouçam o seguinte, povo tolo e insensato,^&#42;1^
Que tem olhos, mas não vê,
E tem ouvidos, mas não ouve:

[NOTE]
====
. Lit.: “povo tolo, sem coração”.
====

[[v24-5-22]]

^<<v24-5-22,22>>^ ‘Não me temem?’, diz Jeová.
‘Não deviam tremer diante de mim?
Fui eu que pus a areia como limite para o mar,
Um decreto eterno que ele não pode ultrapassar.
As ondas agitam-se, mas não conseguem prevalecer;
Rugem, mas, ainda assim, não são capazes de ultrapassá-lo.

[[v24-5-23]]

^<<v24-5-23,23>>^ No entanto, este povo tem um coração obstinado e rebelde;
Eles desviaram-se e seguiram o seu próprio caminho.

[[v24-5-24]]

^<<v24-5-24,24>>^ Não dizem no coração:
“Temamos a Jeová, nosso Deus,
Aquele que dá as chuvas na sua estação,
A chuva do outono e a chuva da primavera,
Aquele que nos garante as semanas destinadas à colheita.”

[[v24-5-25]]

^<<v24-5-25,25>>^ Os vossos próprios erros impediram que estas coisas acontecessem,
Os vossos próprios pecados privaram-vos do que é bom.

[[v24-5-26]]

^<<v24-5-26,26>>^ Pois há homens perversos entre o meu povo.
Eles estão à espreita como os passarinheiros quando se agacham.
Preparam armadilhas mortais;
É a homens que eles apanham.

[[v24-5-27]]

^<<v24-5-27,27>>^ Como uma gaiola cheia de pássaros,
As suas casas estão cheias de fraude.
Por isso é que ficaram poderosos e ricos.

[[v24-5-28]]

^<<v24-5-28,28>>^ Eles engordaram e a sua pele está lisa.
Transbordam de maldade.
Para serem bem-sucedidos,
Não defendem a causa do órfão,^&#42;1^
E negam a justiça aos pobres.’”

[NOTE]
====
. Ou: “órfão de pai”.
====

[[v24-5-29]]

^<<v24-5-29,29>>^ “Não devia eu ajustar contas com eles por causa destas coisas?”, diz Jeová.
“Não devia eu vingar-me^&#42;1^ de uma nação como esta?

[NOTE]
====
. Ou: “Não devia a minha alma vingar-se”.
====

[[v24-5-30]]

^<<v24-5-30,30>>^ Algo espantoso e terrível está a acontecer no país:

[[v24-5-31]]

^<<v24-5-31,31>>^ Os profetas profetizam mentiras,
Os sacerdotes oprimem as pessoas com a sua autoridade,
E o meu próprio povo gosta disso.
Porém, o que é que vocês farão quando o fim chegar?”

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]