include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-3-1]]

^<<v24-3-1,1>>^ As pessoas dizem: “Se um homem mandar a sua esposa embora e, depois de deixá-lo, ela passar a pertencer a outro homem, será que ele deve voltar para ela?”
Não terá essa terra sido totalmente profanada?
“Tu prostituíste-te com muitos companheiros.
E agora, será que deverias voltar para mim?”, diz Jeová.

[[v24-3-2]]

^<<v24-3-2,2>>^ “Levanta os olhos para as colinas sem vegetação e vê.
Onde é que não foste violada?
Sentavas-te à beira das estradas à espera deles,
Como um nómada^&#42;1^ no deserto.
E continuas a profanar essa terra
Com a tua prostituição e a tua maldade.

[NOTE]
====
. Lit.: “um árabe”.
====

[[v24-3-3]]

^<<v24-3-3,3>>^ Por isso, as chuvas abundantes estão retidas,
E não tem chovido na primavera.
Tens o olhar descarado^&#42;1^ de uma esposa que se prostitui;
Recusas-te a sentir vergonha.

[NOTE]
====
. Lit.: “a testa”.
====

[[v24-3-4]]

^<<v24-3-4,4>>^ Agora, clamas a mim, dizendo:
‘Meu Pai, tu és o meu companheiro desde a minha juventude!

[[v24-3-5]]

^<<v24-3-5,5>>^ Devias tu ficar ressentido eternamente,
Ou guardar rancor para sempre?’
Isso é o que dizes,
Mas continuas a fazer todo o mal de que és capaz.”

[[v24-3-6]]

^<<v24-3-6,6>>^ Nos dias do rei Josias, Jeová disse-me: “‘Viste o que a infiel Israel fez? Ela subiu a cada monte alto e foi para debaixo de cada árvore frondosa para se prostituir.

[[v24-3-7]]

^<<v24-3-7,7>>^ E, mesmo depois de ela ter feito todas estas coisas, eu continuei a dizer-lhe que voltasse para mim, mas ela não voltou; e Judá observava o que a sua irmã traiçoeira fazia.

[[v24-3-8]]

^<<v24-3-8,8>>^ Quando eu vi isso, mandei a infiel Israel embora e dei-lhe um certificado de divórcio por causa do seu adultério. Contudo, a traiçoeira Judá, a sua irmã, não ficou com medo; ela também começou a prostituir-se.

[[v24-3-9]]

^<<v24-3-9,9>>^ Ela^&#42;1^ fez pouco caso da sua prostituição, profanou aquela terra e cometeu adultério com pedras e com árvores.

[NOTE]
====
. Possivelmente, refere-se a Israel.
====

[[v24-3-10]]

^<<v24-3-10,10>>^ Apesar de tudo isso, a sua traiçoeira irmã Judá não voltou para mim de todo o coração, mas sim com fingimento’, diz Jeová.”

[[v24-3-11]]

^<<v24-3-11,11>>^ Então, Jeová disse-me: “A infiel Israel mostrou-se^&#42;1^ mais justa do que a traiçoeira Judá.

[NOTE]
====
. Ou: “Israel mostrou que a sua alma era”.
====

[[v24-3-12]]

^<<v24-3-12,12>>^ Vai e proclama as seguintes palavras ao norte:
“‘“Volta para mim, rebelde Israel”, diz Jeová.’ ‘“Não olharei para vocês com ira,^&#42;1^ pois eu sou leal”, diz Jeová.’ ‘“Não ficarei ressentido para sempre.

[NOTE]
====
. Lit.: “Não farei a minha face cair sobre vocês”.
====

[[v24-3-13]]

^<<v24-3-13,13>>^ Ao menos, reconhece a tua culpa, pois rebelaste-te contra Jeová, teu Deus. Distribuías os teus favores^&#42;1^ a estranhos^&#42;2^ debaixo de cada árvore frondosa. Contudo, vocês não quiseram obedecer à minha voz”, diz Jeová.’”

[NOTE]
====
. Lit.: “caminhos”.
. Ou: “deuses estrangeiros”.
====

[[v24-3-14]]

^<<v24-3-14,14>>^ “Voltem, filhos rebeldes”, diz Jeová. “Pois eu tornei-me o vosso verdadeiro dono.^&#42;1^ Irei buscar-vos, a um de cada cidade e a dois de cada família, e vou trazer-vos a Sião.

[NOTE]
====
. Ou, possivelmente: “o vosso marido”.
====

[[v24-3-15]]

^<<v24-3-15,15>>^ Vou dar-vos pastores que atuem de acordo com a minha vontade,^&#42;1^ e eles hão de alimentar-vos com conhecimento e entendimento.

[NOTE]
====
. Lit.: “o meu coração”.
====

[[v24-3-16]]

^<<v24-3-16,16>>^ Nesses dias, vocês terão filhos e hão de tornar-se muitos no país”, diz Jeová. “As pessoas não voltarão a dizer: ‘A Arca do Pacto de Jeová!’ Não pensarão nela,^&#42;1^ nem se lembrarão dela, nem sentirão a sua falta; e ela não será feita novamente.

[NOTE]
====
. Ou: “Ela não lhes subirá ao coração”.
====

[[v24-3-17]]

^<<v24-3-17,17>>^ Nesse tempo, Jerusalém será chamada trono de Jeová; e todas as nações serão ajuntadas em Jerusalém para louvar o nome de Jeová; não teimarão novamente em seguir o seu próprio coração mau.”

[[v24-3-18]]

^<<v24-3-18,18>>^ “Nesses dias, a casa de Judá e a casa de Israel andarão juntas, lado a lado, e juntas sairão da terra do norte para a terra que dei aos vossos antepassados como herança.

[[v24-3-19]]

^<<v24-3-19,19>>^ Eu pensei: ‘Que alegria foi pôr-te entre os meus filhos e dar-te a terra desejável, a mais bela herança entre as nações!’^&#42;1^ Eu também pensei que vocês me chamariam “meu Pai” e que não deixariam de seguir-me.

[NOTE]
====
. Lit.: “dos exércitos das nações”.
====

[[v24-3-20]]

^<<v24-3-20,20>>^ ‘Mas, de facto, assim como a esposa que trai o marido^&#42;1^ e o abandona, ó casa de Israel, assim vocês me traíram’, diz Jeová.”

[NOTE]
====
. Lit.: “companheiro”.
====

[[v24-3-21]]

^<<v24-3-21,21>>^ Nas colinas sem vegetação ouve-se um som,
O choro e as súplicas do povo de Israel,
Pois eles distorceram o seu caminho;
Eles esqueceram-se de Jeová, seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ “Voltem para mim, filhos rebeldes.
Vou curar-vos da vossa rebeldia.”
“Estamos aqui! Viemos a ti,
Pois tu, ó Jeová, és o nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ De facto, as colinas e o barulho nos montes são uma ilusão.
De facto, em Jeová, nosso Deus, está a salvação de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ Contudo, desde a nossa juventude, a coisa vergonhosa^&#42;1^ tem consumido o fruto do trabalho árduo dos nossos antepassados,
As suas ovelhas e os seus bois,
Os seus filhos e as suas filhas.

[NOTE]
====
. Ou: “o deus vergonhoso”.
====

[[v24-3-25]]

^<<v24-3-25,25>>^ Que nos deitemos na nossa vergonha,
E que nos cubramos com a nossa humilhação,
Pois pecámos contra Jeová, nosso Deus,
Nós e os nossos pais, desde a nossa juventude até hoje,
E não obedecemos à voz de Jeová, nosso Deus.”

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]