include::./index.adoc[]

[[v24-38-0]]
=== Jeremias, 38
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-38-1]]

^<<v24-38-1,1>>^ Sefatias, filho de Matã, Gedalias, filho de Pasur, Jucal, filho de Selemias, e Pasur, filho de Malquias, ouviram as seguintes palavras que Jeremias estava a transmitir a todo o povo:

[[v24-38-2]]

^<<v24-38-2,2>>^ “Assim diz Jeová: ‘Quem permanecer nesta cidade morrerá pela espada, pela fome e pela peste.^&#42;1^ Contudo, quem se render^&#42;2^ aos caldeus continuará vivo; terá a sua vida como despojo^&#42;3^ e viverá.’

[NOTE]
====
. Ou: “doença”.
. Lit.: “quem sair”.
. Ou: “escapará com a sua vida (alma)”.
====

[[v24-38-3]]

^<<v24-38-3,3>>^ Assim diz Jeová: ‘Esta cidade certamente será entregue ao exército do rei de Babilónia, e ele irá capturá-la.’”

[[v24-38-4]]

^<<v24-38-4,4>>^ Os príncipes disseram ao rei: “Por favor, ordene que este homem seja morto, pois, com estas palavras, ele está a desanimar os^&#42;1^ soldados que restam nesta cidade e também todo o povo. Este homem não procura a paz deste povo, mas a sua calamidade.”

[NOTE]
====
. Lit.: “ele enfraquece as mãos dos”.
====

[[v24-38-5]]

^<<v24-38-5,5>>^ O rei Zedequias respondeu: “Ele está nas vossas mãos, pois o rei não pode fazer nada para vos impedir.”

[[v24-38-6]]

^<<v24-38-6,6>>^ Por conseguinte, pegaram em Jeremias e meteram-no na cisterna de Malquias, filho do rei, a qual ficava no Pátio da Guarda. Eles desceram Jeremias por meio de cordas. Não havia água na cisterna, só lama; e Jeremias começou a afundar-se na lama.

[[v24-38-7]]

^<<v24-38-7,7>>^ Ebede-Meleque, o etíope, que era um eunuco^&#42;1^ na casa^&#42;2^ do rei, ouviu dizer que tinham posto Jeremias na cisterna. O rei estava sentado no Portão de Benjamim,

[NOTE]
====
. Ou: “oficial da corte”.
. Ou: “no palácio”.
====

[[v24-38-8]]

^<<v24-38-8,8>>^ quando Ebede-Meleque saiu da casa^&#42;1^ do rei e disse-lhe:

[NOTE]
====
. Ou: “do palácio”.
====

[[v24-38-9]]

^<<v24-38-9,9>>^ “Ó meu senhor, o rei, o que estes homens fizeram ao profeta Jeremias é muito mau! Eles meteram-no na cisterna. Ele vai morrer lá de fome, pois já não há pão na cidade.”

[[v24-38-10]]

^<<v24-38-10,10>>^ O rei ordenou então a Ebede-Meleque, o etíope: “Leva daqui 30 homens contigo e tira o profeta Jeremias da cisterna antes que ele morra.”

[[v24-38-11]]

^<<v24-38-11,11>>^ Assim, Ebede-Meleque levou consigo os homens e entrou na casa^&#42;1^ do rei, num lugar que ficava por baixo da sala do tesouro. Pegaram em alguns trapos e panos velhos, e desceram-nos por meio de cordas até Jeremias, na cisterna.

[NOTE]
====
. Ou: “no palácio”.
====

[[v24-38-12]]

^<<v24-38-12,12>>^ De seguida, Ebede-Meleque, o etíope, disse a Jeremias: “Por favor, coloca os trapos e os panos debaixo dos braços e, depois, as cordas.” Jeremias assim o fez,

[[v24-38-13]]

^<<v24-38-13,13>>^ e puxaram Jeremias com as cordas e tiraram-no da cisterna. E Jeremias permaneceu no Pátio da Guarda.

[[v24-38-14]]

^<<v24-38-14,14>>^ O rei Zedequias mandou trazer o profeta Jeremias até onde ele estava, na terceira entrada, que fica na casa de Jeová. E o rei disse a Jeremias: “Tenho uma pergunta para te fazer. Não me escondas nada.”

[[v24-38-15]]

^<<v24-38-15,15>>^ Jeremias disse então a Zedequias: “Se eu lhe responder, certamente, vai matar-me. E, se eu lhe der um conselho, não me vai dar ouvidos.”

[[v24-38-16]]

^<<v24-38-16,16>>^ Então, o rei Zedequias jurou secretamente a Jeremias, dizendo: “Tão certo como vive Jeová, que nos deu a vida,^&#42;1^ eu não te matarei, nem te entregarei a estes homens que procuram tirar-te a vida.”^&#42;2^

[NOTE]
====
. Ou: “nos fez esta alma”.
. Ou: “procuram a tua alma”.
====

[[v24-38-17]]

^<<v24-38-17,17>>^ Jeremias disse então a Zedequias: “Assim diz Jeová, o Deus dos exércitos, o Deus de Israel: ‘Se te renderes^&#42;1^ aos príncipes do rei de Babilónia, a tua vida será poupada,^&#42;2^ e esta cidade não será queimada com fogo; tu e os da tua casa serão poupados.

[NOTE]
====
. Lit.: “saíres”.
. Ou: “a tua alma continuará viva”.
====

[[v24-38-18]]

^<<v24-38-18,18>>^ Mas, se não te renderes^&#42;1^ aos príncipes do rei de Babilónia, esta cidade será entregue aos caldeus, eles irão queimá-la com fogo, e tu não escaparás das suas mãos.’”

[NOTE]
====
. Lit.: “não saíres”.
====

[[v24-38-19]]

^<<v24-38-19,19>>^ De seguida, o rei Zedequias disse a Jeremias: “Estou com medo dos judeus que desertaram para o lado dos caldeus. Pois, se eu lhes for entregue, talvez me tratem com crueldade.”

[[v24-38-20]]

^<<v24-38-20,20>>^ Contudo, Jeremias disse: “O senhor não lhes será entregue. Obedeça, por favor, à voz de Jeová, por fazer o que lhe digo, e o senhor ficará bem e continuará vivo.^&#42;1^

[NOTE]
====
. Ou: “e a sua alma continuará viva”.
====

[[v24-38-21]]

^<<v24-38-21,21>>^ Porém, caso se recuse a render-se,^&#42;1^ isto é o que Jeová me revelou:

[NOTE]
====
. Lit.: “a sair”.
====

[[v24-38-22]]

^<<v24-38-22,22>>^ Vejo todas as mulheres que restaram na casa^&#42;1^ do rei de Judá a serem levadas para fora aos príncipes do rei de Babilónia, e elas dizem:
‘Os homens em quem confiavas^&#42;2^ enganaram-te e dominaram-te.
Fizeram com que os teus pés se afundassem na lama.
Agora, viraram as costas e fugiram.’

[NOTE]
====
. Ou: “no palácio”.
. Lit.: “Os homens da tua paz”.
====

[[v24-38-23]]

^<<v24-38-23,23>>^ Estão a levar todas as suas esposas e os seus filhos aos caldeus. E o senhor não lhes escapará das mãos, mas será apanhado pelo rei de Babilónia; e será por causa do senhor que esta cidade será queimada com fogo.”

[[v24-38-24]]

^<<v24-38-24,24>>^ Então, Zedequias disse a Jeremias: “Não deixes ninguém saber destas coisas, para que não morras.

[[v24-38-25]]

^<<v24-38-25,25>>^ Se os príncipes souberem que falei contigo e vierem dizer-te: ‘Por favor, conta-nos o que disseste ao rei. Não nos escondas nada, e não te mataremos. E o que é que o rei te disse?’,

[[v24-38-26]]

^<<v24-38-26,26>>^ nesse caso, responde-lhes: ‘Eu estava a fazer um pedido ao rei, para que ele não me mandasse novamente para a casa de Jeonatã, pois morreria lá.’”

[[v24-38-27]]

^<<v24-38-27,27>>^ Com o tempo, todos os príncipes foram até Jeremias e interrogaram-no. Ele disse-lhes tudo o que o rei lhe tinha ordenado. Portanto, não lhe perguntaram mais nada, pois nenhum deles tinha ouvido a conversa.

[[v24-38-28]]

^<<v24-38-28,28>>^ Jeremias permaneceu no Pátio da Guarda até ao dia em que Jerusalém foi conquistada; ele ainda ali estava quando Jerusalém foi conquistada.

'''

xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[&#60; Capítulo Anterior] | <<v24-38-0,Topo>> | xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[Próximo Capítulo &#62;]