include::./index.adoc[]

[[v24-17-0]]
=== Jeremias, 17
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-17-1]]

^<<v24-17-1,1>>^ “O pecado de Judá está escrito com uma pena^&#42;1^ de ferro,
Está gravado com ponta de diamante na tábua do seu coração
E nos chifres dos seus altares.

[NOTE]
====
. Lit.: “um estilo”. Veja o Glossário.
====

[[v24-17-2]]

^<<v24-17-2,2>>^ Até os seus filhos se lembram dos seus altares e dos seus postes sagrados^&#42;1^
Ao lado de uma árvore frondosa, nas colinas elevadas,

[NOTE]
====
. Veja o Glossário.
====

[[v24-17-3]]

^<<v24-17-3,3>>^ Nos montes do campo aberto.
Os teus recursos, todos os teus tesouros, entregarei como despojo;
Sim, os teus altos sagrados, por causa do pecado que cometeram em todos os teus territórios.

[[v24-17-4]]

^<<v24-17-4,4>>^ Vais renunciar, por iniciativa própria, à herança que eu te dei.
Vou fazer com que sirvas os teus inimigos numa terra que não conheces,
Pois vocês acenderam a minha ira como um fogo.^&#42;1^
Ela arderá para sempre.”

[NOTE]
====
. Ou, possivelmente: “Pois, como um fogo, vocês foram acesos na minha ira”.
====

[[v24-17-5]]

^<<v24-17-5,5>>^ Assim diz Jeová:
“Maldito o homem^&#42;1^ que confia em meros humanos,
Que conta com a força dos homens,^&#42;2^
E cujo coração se afasta de Jeová.

[NOTE]
====
. Ou: “homem forte”.
. Lit.: “faz da carne o seu braço”.
====

[[v24-17-6]]

^<<v24-17-6,6>>^ Ele vai tornar-se como uma árvore solitária no deserto.
Não verá quando o que é bom vier,
Mas morará em lugares áridos no deserto,
Numa terra salgada, onde ninguém pode viver.

[[v24-17-7]]

^<<v24-17-7,7>>^ Bendito o homem^&#42;1^ que confia em Jeová,
Cuja esperança^&#42;2^ está em Jeová.

[NOTE]
====
. Ou: “homem forte”.
. Ou: “confiança”.
====

[[v24-17-8]]

^<<v24-17-8,8>>^ Ele há de tornar-se como uma árvore plantada junto às águas,
Que estende as suas raízes até ao curso de água.
Ele não perceberá quando o calor chegar,
Mas as suas folhas estarão sempre viçosas.
No ano da seca, ele não ficará preocupado,
Nem deixará de produzir fruto.

[[v24-17-9]]

^<<v24-17-9,9>>^ O coração é mais traiçoeiro^&#42;1^ do que qualquer outra coisa e está desesperado.^&#42;2^
Quem é que o pode conhecer?

[NOTE]
====
. Ou: “enganoso”.
. Ou, possivelmente: “é incurável”.
====

[[v24-17-10]]

^<<v24-17-10,10>>^ Eu, Jeová, examino o coração,
Sondo os pensamentos mais íntimos,^&#42;1^
Para retribuir a cada um conforme os seus caminhos,
Conforme os frutos das suas obras.

[NOTE]
====
. Ou: “as emoções mais profundas”. Lit.: “os rins”.
====

[[v24-17-11]]

^<<v24-17-11,11>>^ Como a perdiz que choca ovos que não pôs,
Assim é aquele que adquire riquezas de modo desonesto;^&#42;1^
Elas vão deixá-lo a meio da sua vida
E, no fim, ele mostrará ser um insensato.”

[NOTE]
====
. Ou: “riquezas, mas não com justiça”.
====

[[v24-17-12]]

^<<v24-17-12,12>>^ Um trono glorioso, enaltecido desde o princípio,
É o lugar do nosso santuário.

[[v24-17-13]]

^<<v24-17-13,13>>^ Ó Jeová, a esperança de Israel,
Todos os que te abandonam serão envergonhados.
Os que se desviam^&#42;1^ de ti^&#42;2^ terão os seus nomes escritos no pó,
Porque abandonaram a Jeová, a fonte de água viva.

[NOTE]
====
. Ou: “que apostatam”.
. Lit.: “mim”, aparentemente, referindo-se a Jeová.
====

[[v24-17-14]]

^<<v24-17-14,14>>^ Cura-me, ó Jeová, e ficarei curado.
Salva-me, e serei salvo,
Pois tu és aquele a quem louvo.

[[v24-17-15]]

^<<v24-17-15,15>>^ Vê, há alguns que me dizem:
“Onde é que está a palavra de Jeová?
Que ela se cumpra!”

[[v24-17-16]]

^<<v24-17-16,16>>^ No entanto, quanto a mim, não deixei de seguir-te como pastor,
Nem desejei o dia da calamidade.
Tu bem sabes tudo o que os meus lábios disseram;
Tudo se passou diante da tua face.

[[v24-17-17]]

^<<v24-17-17,17>>^ Não sejas um motivo de terror para mim.
Tu és o meu refúgio no dia da calamidade.

[[v24-17-18]]

^<<v24-17-18,18>>^ Que os meus perseguidores sejam envergonhados,
Mas não seja eu envergonhado.
Que eles fiquem apavorados,
Mas não fique eu apavorado.
Traz sobre eles o dia da calamidade,
Esmaga-os e elimina-os completamente.^&#42;1^

[NOTE]
====
. Ou: “elimina-os duas vezes”.
====

[[v24-17-19]]

^<<v24-17-19,19>>^ Assim me disse Jeová: “Vai até ao portão dos filhos do povo, pelo qual os reis de Judá entram e saem, e também a todos os outros portões de Jerusalém.

[[v24-17-20]]

^<<v24-17-20,20>>^ Diz-lhes: ‘Ouçam a palavra de Jeová, ó reis de Judá, todo o povo de Judá e todos os habitantes de Jerusalém, que entram por estes portões.

[[v24-17-21]]

^<<v24-17-21,21>>^ Assim diz Jeová: “Tenham o cuidado de^&#42;1^ não transportar nenhuma carga no dia de sábado nem de entrar com ela pelos portões de Jerusalém.

[NOTE]
====
. Ou: “Cuidem das vossas almas para”.
====

[[v24-17-22]]

^<<v24-17-22,22>>^ Não tragam nenhuma carga de casa no dia de sábado, nem realizem nenhum trabalho. Mantenham sagrado o dia de sábado, assim como ordenei aos vossos antepassados.

[[v24-17-23]]

^<<v24-17-23,23>>^ Porém, eles não ouviram nem prestaram atenção;^&#42;1^ teimaram em^&#42;2^ não obedecer e não aceitar a disciplina.”’

[NOTE]
====
. Ou: “nem inclinaram o seu ouvido”.
. Lit.: “endureceram a sua cerviz para”.
====

[[v24-17-24]]

^<<v24-17-24,24>>^ “‘“No entanto, se me obedecerem fielmente”, diz Jeová, “não entrarem com cargas pelos portões desta cidade no dia de sábado e mantiverem sagrado o dia de sábado, por não realizarem nenhum trabalho,

[[v24-17-25]]

^<<v24-17-25,25>>^ então, os reis e os príncipes que se sentam no trono de David também entrarão pelos portões desta cidade, andando em carros e montados em cavalos — eles e os seus príncipes, os homens de Judá e os habitantes de Jerusalém —, e esta cidade será habitada para sempre.

[[v24-17-26]]

^<<v24-17-26,26>>^ E as pessoas virão das cidades de Judá, dos arredores de Jerusalém, da terra de Benjamim, da planície, da região montanhosa e do Neguebe,^&#42;1^ trazendo ofertas queimadas, sacrifícios, ofertas de cereais, olíbano e sacrifícios de agradecimento à casa de Jeová.

[NOTE]
====
. Ou: “do sul”.
====

[[v24-17-27]]

^<<v24-17-27,27>>^ “‘“Mas, se não me obedecerem e deixarem de manter sagrado o dia de sábado, transportando cargas e entrando com elas pelos portões de Jerusalém no dia de sábado, vou deitar fogo aos seus portões. Este certamente devorará as torres fortificadas de Jerusalém e não se apagará.”’”

'''

xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[Próximo Capítulo &#62;]