include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-29-1]]

^<<v24-29-1,1>>^ Estas são as palavras da carta que o profeta Jeremias enviou de Jerusalém aos anciãos que restaram entre o povo exilado, aos sacerdotes, aos profetas e a todo o povo, a quem Nabucodonosor tinha levado de Jerusalém para o exílio em Babilónia,

[[v24-29-2]]

^<<v24-29-2,2>>^ depois de o rei Jeconias, a rainha-mãe,^&#42;1^ os oficiais da corte, os príncipes de Judá e de Jerusalém, os artesãos e os trabalhadores em metal^&#42;2^ terem saído de Jerusalém.

[NOTE]
====
. Ou: “a senhora”.
. Ou, possivelmente: “construtores de fortificações”.
====

[[v24-29-3]]

^<<v24-29-3,3>>^ Ele enviou a carta pelas mãos de Elasa, filho de Safã, e de Gemarias, filho de Hilquias, os quais Zedequias, rei de Judá, enviou a Babilónia, a Nabucodonosor, rei de Babilónia. Ela dizia:

[[v24-29-4]]

^<<v24-29-4,4>>^ “Assim diz Jeová dos exércitos, o Deus de Israel, a todo o povo exilado, que fiz ser levado de Jerusalém para o exílio em Babilónia:

[[v24-29-5]]

^<<v24-29-5,5>>^ ‘Construam casas e habitem-nas. Plantem pomares e comam os seus frutos.

[[v24-29-6]]

^<<v24-29-6,6>>^ Tomem esposas e tenham filhos e filhas; tomem esposas para os vossos filhos, e deem as vossas filhas em casamento, para que elas também tenham filhos e filhas. Tornem-se muitos, e não diminuam em número.

[[v24-29-7]]

^<<v24-29-7,7>>^ Empenhem-se pela paz da cidade para onde vos exilei, e orem a Jeová a favor dela, pois a sua paz significará a vossa paz.

[[v24-29-8]]

^<<v24-29-8,8>>^ Pois assim diz Jeová dos exércitos, o Deus de Israel: “Não se deixem enganar pelos vossos profetas e pelos vossos adivinhos, que estão no vosso meio, nem deem ouvidos aos sonhos que eles têm.

[[v24-29-9]]

^<<v24-29-9,9>>^ Pois ‘eles profetizam-vos mentiras em meu nome. Eu não os enviei’, diz Jeová.”’”

[[v24-29-10]]

^<<v24-29-10,10>>^ “Pois assim diz Jeová: ‘Quando se completarem 70 anos em Babilónia, voltarei a minha atenção para vocês e cumprirei a minha promessa, trazendo-vos de volta.’

[[v24-29-11]]

^<<v24-29-11,11>>^ “‘Pois sei muito bem o que tenho em mente para vocês’, diz Jeová. ‘Quero que tenham paz, não calamidade. Quero dar-vos um futuro e uma esperança.

[[v24-29-12]]

^<<v24-29-12,12>>^ E hão de chamar-me e vir até mim em oração, e eu vou ouvir-vos.’

[[v24-29-13]]

^<<v24-29-13,13>>^ “‘Hão de procurar-me e encontrar-me, pois irão procurar-me de todo o coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ E eu permitirei que me encontrem’, diz Jeová. ‘E vou ajuntar o vosso povo cativo e reunir-vos dentre todas as nações e lugares pelos quais vos espalhei’, diz Jeová. ‘E vou trazer-vos de volta ao lugar do qual vos exilei.’

[[v24-29-15]]

^<<v24-29-15,15>>^ “No entanto, vocês dizem: ‘Jeová fez-nos surgir profetas em Babilónia.’

[[v24-29-16]]

^<<v24-29-16,16>>^ “Portanto, assim diz Jeová ao rei que está sentado no trono de David e a todo o povo que mora nesta cidade, os vossos irmãos que não foram convosco para o exílio:

[[v24-29-17]]

^<<v24-29-17,17>>^ ‘Assim diz Jeová dos exércitos: “Vou enviar a espada, a fome e a peste^&#42;1^ contra eles, e vou fazer com que fiquem como figos podres,^&#42;2^ tão maus que nem sequer se podem comer.”’

[NOTE]
====
. Ou: “doença”.
. Ou, possivelmente: “rebentados”.
====

[[v24-29-18]]

^<<v24-29-18,18>>^ “‘Vou persegui-los com a espada, a fome e a peste, e vou fazer deles um motivo de terror para todos os reinos da terra, um exemplo de maldição, um motivo de espanto, um alvo de assobios e de insultos entre todas as nações por onde eu os espalhar,

[[v24-29-19]]

^<<v24-29-19,19>>^ visto que não deram ouvidos às minhas palavras’, diz Jeová, ‘que lhes enviei por meio dos meus servos, os profetas; eu enviava-os vez após vez’.^&#42;1^
“‘Mas vocês não escutaram’, diz Jeová.

[NOTE]
====
. Lit.: “os profetas; levantando-me cedo e enviando”.
====

[[v24-29-20]]

^<<v24-29-20,20>>^ “Por isso, ouçam a palavra de Jeová, todos vocês, povo exilado, que mandei embora de Jerusalém para Babilónia.

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz Jeová dos exércitos, o Deus de Israel, a respeito de Acabe, filho de Colaías, e a respeito de Zedequias, filho de Maaseias, que vos profetizam mentiras em meu nome: ‘Vou entregá-los nas mãos de Nabucodonosor,^&#42;1^ rei de Babilónia, e ele irá matá-los diante dos vossos olhos.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-29-22]]

^<<v24-29-22,22>>^ E o que lhes acontecer passará a ser usado como uma maldição por todos os exilados de Judá que estão em Babilónia: “Que Jeová te faça o mesmo que se fez a Zedequias e a Acabe, a quem o rei de Babilónia assou no fogo!”

[[v24-29-23]]

^<<v24-29-23,23>>^ Pois eles agiram de modo vergonhoso em Israel, por cometerem adultério com a esposa do próximo e por dizerem mentiras em meu nome, sem que eu os mandasse falar.
“‘“Eu sei e sou testemunha disso”, diz Jeová.’”

[[v24-29-24]]

^<<v24-29-24,24>>^ “E a Semaías de Neelão dirás:

[[v24-29-25]]

^<<v24-29-25,25>>^ ‘Assim diz Jeová dos exércitos, o Deus de Israel: “Visto que enviaste cartas em teu nome a todo o povo que está em Jerusalém, ao sacerdote Sofonias, filho de Maaseias, e a todos os sacerdotes, cartas essas que diziam:

[[v24-29-26]]

^<<v24-29-26,26>>^ ‘Jeová designou-te como sacerdote no lugar do sacerdote Jeoiada, para seres o superintendente da casa de Jeová, para vigiares qualquer louco que se comporte como um profeta e para o mandares para o tronco.^&#42;1^

[NOTE]
====
. Lit.: “para o cepo e para o tronco”.
====

[[v24-29-27]]

^<<v24-29-27,27>>^ Então, porque é que não repreendeste Jeremias de Anatote, que se comporta como um profeta perante vocês?

[[v24-29-28]]

^<<v24-29-28,28>>^ Pois ele até nos mandou dizer em Babilónia: “Vocês vão ficar aí por muito tempo! Construam casas e habitem-nas. Plantem pomares e comam os seus frutos, . . .”’”’”

[[v24-29-29]]

^<<v24-29-29,29>>^ Quando o sacerdote Sofonias leu esta carta na presença do profeta Jeremias,

[[v24-29-30]]

^<<v24-29-30,30>>^ Jeremias recebeu a seguinte palavra de Jeová:

[[v24-29-31]]

^<<v24-29-31,31>>^ “Manda dizer a todo o povo exilado: ‘Assim diz Jeová a respeito de Semaías de Neelão: “Visto que Semaías vos profetizou sem que eu o tivesse enviado, e tentou fazer-vos acreditar em mentiras,

[[v24-29-32]]

^<<v24-29-32,32>>^ assim diz Jeová: ‘Vou voltar a minha atenção para Semaías de Neelão e os seus descendentes. Ninguém da sua família sobreviverá entre este povo, e ele não verá o bem que vou fazer ao meu povo’, diz Jeová, ‘pois instigou uma rebelião contra Jeová’.”’”

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]