include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-12-1]]

^<<v24-12-1,1>>^ Tu és justo, ó Jeová, quando te apresento a minha queixa,
Quando falo contigo sobre questões de justiça.
Mas porque é que os maus são bem-sucedidos no seu caminho?
E porque é que os traiçoeiros vivem tranquilos?

[[v24-12-2]]

^<<v24-12-2,2>>^ Tu plantaste-os e eles criaram raízes,
Cresceram e produziram frutos.
Tu estás nos seus lábios, mas longe dos seus pensamentos mais íntimos.^&#42;1^

[NOTE]
====
. Ou: “das suas emoções mais profundas”. Lit.: “dos seus rins”.
====

[[v24-12-3]]

^<<v24-12-3,3>>^ Tu, porém, conheces-me bem, ó Jeová, tu vês-me;
Examinaste o meu coração e viste que ele está em união contigo.
Separa-os como ovelhas para o abate
E reserva-os para o dia da matança.

[[v24-12-4]]

^<<v24-12-4,4>>^ Por quanto tempo é que esta terra vai continuar a definhar-se
E a vegetação de todos os campos se vai secar?
Por causa da maldade dos habitantes desta terra,
Os animais e as aves deixaram de existir.
Pois eles disseram: “Ele não vê o que nos vai acontecer.”

[[v24-12-5]]

^<<v24-12-5,5>>^ Se ficas cansado ao correr com homens,
Como é que conseguirás disputar uma corrida contra cavalos?
Mesmo que te sintas confiante na terra de paz,
Como é que te sairás quando estiveres nos densos bosques ao longo do Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Pois até mesmo os teus irmãos, os da casa do teu pai,
Foram traiçoeiros contigo.
Eles gritaram contra ti.
Não confies neles,
Mesmo que te digam coisas boas.

[[v24-12-7]]

^<<v24-12-7,7>>^ “Abandonei a minha casa; deixei a minha herança.
Entreguei a minha amada^&#42;1^ nas mãos dos seus inimigos.

[NOTE]
====
. Ou: “a amada pela minha alma”.
====

[[v24-12-8]]

^<<v24-12-8,8>>^ A minha herança tornou-se para mim como um leão na floresta.
Ela rugiu contra mim.
Por isso, passei a odiá-la.

[[v24-12-9]]

^<<v24-12-9,9>>^ A minha herança é para mim como uma ave de rapina colorida;^&#42;1^
As outras aves de rapina atacam-na de todos os lados.
Venham, ajuntem-se, todos os animais selvagens,
Venham comer.

[NOTE]
====
. Ou: “malhada”.
====

[[v24-12-10]]

^<<v24-12-10,10>>^ A minha vinha foi destruída por muitos pastores;
Eles espezinharam a minha propriedade.
Fizeram da minha preciosa propriedade um deserto desolado.

[[v24-12-11]]

^<<v24-12-11,11>>^ Fizeram dela um deserto.
Ela definhou-se;^&#42;1^
Está desolada diante de mim.
Toda esta terra foi devastada,
Mas ninguém se importa.

[NOTE]
====
. Ou, possivelmente: “está de luto”.
====

[[v24-12-12]]

^<<v24-12-12,12>>^ Os destruidores vieram de todos os caminhos^&#42;1^ que atravessam o deserto,
Pois a espada de Jeová está a devorar esta terra de uma extremidade à outra.
Não há paz para ninguém.^&#42;2^

[NOTE]
====
. Ou: “caminhos de terra batida”.
. Lit.: “para nenhuma carne”.
====

[[v24-12-13]]

^<<v24-12-13,13>>^ Semearam trigo, mas colheram espinhos.
Ficaram exaustos, mas em vão.
Ficarão envergonhados com a sua produção,
Por causa da ira ardente de Jeová.”

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz Jeová contra todos os meus maus vizinhos que tocam na herança que dei ao meu povo Israel como propriedade: “Vou arrancá-los da sua terra, e também vou arrancar a casa de Judá do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ No entanto, depois de arrancá-los, vou novamente ter misericórdia deles e trazer cada um deles de volta à sua herança e à sua terra.”

[[v24-12-16]]

^<<v24-12-16,16>>^ “E, se eles realmente aprenderem os caminhos do meu povo e jurarem pelo meu nome, dizendo: ‘Tão certo como Jeová vive!’ da mesma forma que ensinaram o meu povo a jurar por Baal, eles também serão estabelecidos no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Contudo, se eles se recusarem a obedecer, vou arrancar essa nação; vou arrancá-la e destruí-la”, diz Jeová.

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]