include::./index.adoc[]

[[v24-26-0]]
=== Jeremias, 26
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-26-1]]

^<<v24-26-1,1>>^ No começo do reinado de Jeoiaquim, filho de Josias e rei de Judá, veio a seguinte palavra de Jeová:

[[v24-26-2]]

^<<v24-26-2,2>>^ “Assim diz Jeová: ‘Vai ao pátio da casa de Jeová e, lá, fala a^&#42;1^ todos os habitantes das cidades de Judá que vêm adorar^&#42;2^ na casa de Jeová. Diz-lhes tudo o que eu te ordenar; não omitas nenhuma palavra.

[NOTE]
====
. Ou: “sobre”.
. Ou: “curvar-se”.
====

[[v24-26-3]]

^<<v24-26-3,3>>^ É possível que eles ouçam e que cada um recue do seu mau caminho. Se isso acontecer, voltarei atrás a respeito da^&#42;1^ calamidade que pretendo trazer sobre eles por causa das suas más ações.

[NOTE]
====
. Ou: “lamentarei a”.
====

[[v24-26-4]]

^<<v24-26-4,4>>^ Diz-lhes: “Assim diz Jeová: ‘Se não me obedecerem, por seguirem a minha lei,^&#42;1^ que pus à vossa frente,

[NOTE]
====
. Ou: “instrução”.
====

[[v24-26-5]]

^<<v24-26-5,5>>^ e por escutarem as palavras dos meus servos, os profetas — que eu vos tenho enviado vez após vez,^&#42;1^ mas aos quais não têm dado ouvidos —,

[NOTE]
====
. Lit.: “vos tenho enviado, levantando-me cedo e enviando”.
====

[[v24-26-6]]

^<<v24-26-6,6>>^ nesse caso, eu farei esta casa igual a Silo, e farei desta cidade um exemplo de maldição para todas as nações da terra.’”’”

[[v24-26-7]]

^<<v24-26-7,7>>^ E os sacerdotes, os profetas e todo o povo ouviram Jeremias a dizer estas palavras na casa de Jeová.

[[v24-26-8]]

^<<v24-26-8,8>>^ Quando Jeremias acabou de dizer tudo o que Jeová lhe tinha mandado dizer a todo o povo, então, os sacerdotes, os profetas e todo o povo agarraram-no e disseram-lhe: “Vais morrer de certeza.

[[v24-26-9]]

^<<v24-26-9,9>>^ Porque é que profetizaste em nome de Jeová, dizendo: ‘Esta casa ficará igual a Silo, e esta cidade será devastada e deixada sem habitantes’?” E todo o povo se ajuntou à volta de Jeremias na casa de Jeová.

[[v24-26-10]]

^<<v24-26-10,10>>^ Quando os príncipes de Judá ouviram estas palavras, subiram da casa^&#42;1^ do rei até à casa de Jeová e sentaram-se à entrada do portão novo da casa de Jeová.

[NOTE]
====
. Ou: “do palácio”.
====

[[v24-26-11]]

^<<v24-26-11,11>>^ Os sacerdotes e os profetas disseram aos príncipes e a todo o povo: “Este homem merece a pena de morte, porque profetizou contra esta cidade assim como ouviram com os vossos próprios ouvidos.”

[[v24-26-12]]

^<<v24-26-12,12>>^ Então, Jeremias disse a todos os príncipes e a todo o povo: “Foi Jeová que me enviou para profetizar todas as palavras que ouviram contra esta casa e contra esta cidade.

[[v24-26-13]]

^<<v24-26-13,13>>^ Portanto, corrijam os vossos caminhos e as vossas ações, e obedeçam à voz de Jeová, vosso Deus, e Jeová voltará atrás quanto à^&#42;1^ calamidade que proferiu contra vocês.

[NOTE]
====
. Ou: “lamentará a”.
====

[[v24-26-14]]

^<<v24-26-14,14>>^ Quanto a mim, estou nas vossas mãos. Façam comigo o que for bom e direito aos vossos olhos.

[[v24-26-15]]

^<<v24-26-15,15>>^ No entanto, estejam certos de que, se me matarem, trarão sangue inocente sobre vocês mesmos e sobre esta cidade e os seus habitantes, pois foi realmente Jeová que me enviou para dizer todas estas palavras na vossa presença.”

[[v24-26-16]]

^<<v24-26-16,16>>^ A seguir, os príncipes e todo o povo disseram aos sacerdotes e aos profetas: “Este homem não merece a pena de morte, pois falou-nos em nome de Jeová, nosso Deus.”

[[v24-26-17]]

^<<v24-26-17,17>>^ Além disso, alguns dos anciãos do país levantaram-se e disseram a todo o povo reunido:

[[v24-26-18]]

^<<v24-26-18,18>>^ “Miqueias de Moresete, que profetizava nos dias de Ezequias, rei de Judá, disse a todo o povo de Judá: ‘Assim diz Jeová dos exércitos:
“Sião será lavrada como um campo,
Jerusalém irá tornar-se em montões de ruínas,
E o monte da Casa^&#42;1^ irá tornar-se uma colina coberta de árvores.”’^&#42;2^

[NOTE]
====
. Ou: “do templo”.
. Ou: “como altos numa floresta”.
====

[[v24-26-19]]

^<<v24-26-19,19>>^ “Será que Ezequias, rei de Judá, e todo o Judá o mataram? Não é verdade que ele^&#42;1^ temeu a Jeová e suplicou o favor^&#42;2^ de Jeová, de modo que Jeová voltou atrás a respeito da^&#42;3^ calamidade que tinha proferido contra eles? Portanto, estamos prestes a trazer uma grande calamidade sobre nós mesmos.^&#42;4^

[NOTE]
====
. Isto é, Ezequias.
. Ou: “tentou abrandar a face”.
. Ou: “lamentou a”.
. Ou: “as nossas almas”.
====

[[v24-26-20]]

^<<v24-26-20,20>>^ “Houve também outro homem que profetizava em nome de Jeová: Urias, filho de Semaías, de Quiriate-Jearim, que profetizava contra esta cidade e contra esta terra com palavras semelhantes às de Jeremias.

[[v24-26-21]]

^<<v24-26-21,21>>^ O rei Jeoiaquim, todos os seus guerreiros e todos os príncipes ouviram as suas palavras, e o rei decidiu matá-lo. Assim que Urias soube disso, ficou com medo e fugiu para o Egito.

[[v24-26-22]]

^<<v24-26-22,22>>^ Então, o rei Jeoiaquim enviou Elnatã, filho de Acbor, juntamente com outros homens, ao Egito.

[[v24-26-23]]

^<<v24-26-23,23>>^ Eles trouxeram Urias do Egito e levaram-no ao rei Jeoiaquim, que o matou pela espada e atirou o seu cadáver para o cemitério do povo comum.”

[[v24-26-24]]

^<<v24-26-24,24>>^ Contudo, Aicão, filho de Safã, apoiou Jeremias, de modo que ele não foi entregue nas mãos do povo para ser morto.

'''

xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[&#60; Capítulo Anterior] | <<v24-26-0,Topo>> | xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[Próximo Capítulo &#62;]