include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-49-1]]

^<<v24-49-1,1>>^ Assim diz Jeová a respeito dos amonitas:
“Por acaso, Israel não tem filhos?
Por acaso, não tem herdeiro?
Então, porque é que Malcã se apoderou de Gade?
E porque é que o seu povo está a morar nas cidades de Israel?”

[[v24-49-2]]

^<<v24-49-2,2>>^ “‘Portanto, estão a chegar os dias’, diz Jeová,
‘Em que farei ouvir o toque de guerra^&#42;1^ contra Rabá dos amonitas.
Ela há de tornar-se um montão de ruínas abandonadas,
E as suas aldeias dependentes^&#42;2^ serão incendiadas’.
‘E Israel despojará aqueles que o despojaram’, diz Jeová.

[NOTE]
====
. Ou, possivelmente: “o som do grito de guerra”.
. Ou: “ao redor”.
====

[[v24-49-3]]

^<<v24-49-3,3>>^ ‘Lamenta, ó Hésbon, pois Ai foi destruída!
Clamem, ó aldeias dependentes de Rabá.
Vistam-se de serapilheira.^&#42;1^
Chorem e corram de um lado para o outro entre os currais de pedra,^&#42;2^
Pois Malcã irá para o exílio,
Juntamente com os seus sacerdotes e os seus príncipes.

[NOTE]
====
. Veja o Glossário.
. Ou: “currais de ovelhas”.
====

[[v24-49-4]]

^<<v24-49-4,4>>^ Porque é que te gabas dos teus vales,^&#42;1^
Das tuas planícies bem regadas, ó filha infiel,
Que confia nos seus tesouros
E diz: “Quem é que virá contra mim?”’”

[NOTE]
====
. Ou: “das tuas planícies”.
====

[[v24-49-5]]

^<<v24-49-5,5>>^ “‘Vou trazer algo terrível sobre ti’, diz o Soberano Senhor, Jeová dos exércitos,
‘Da parte de todos à tua volta.
Serás espalhada em todas as direções,
E ninguém reunirá os fugitivos.’”

[[v24-49-6]]

^<<v24-49-6,6>>^ “‘Depois, porém, reunirei o povo cativo dos amonitas’, diz Jeová.”

[[v24-49-7]]

^<<v24-49-7,7>>^ Assim diz Jeová dos exércitos a respeito de Edom:
“Será que já não há sabedoria em Temã?
Deixaram de existir os bons conselhos daqueles que têm entendimento?
Será que a sua sabedoria apodreceu?

[[v24-49-8]]

^<<v24-49-8,8>>^ Deem meia-volta, fujam!
Escondam-se nas profundezas, ó habitantes de Dedã!
Pois vou trazer calamidade sobre Esaú,
Quando chegar o tempo de eu voltar a minha atenção para ele.

[[v24-49-9]]

^<<v24-49-9,9>>^ Se vindimadores viessem até ti,
Não deixariam sobrar algumas uvas para respigar?
Se ladrões viessem à noite,
Não arruinariam eles apenas o que quisessem?

[[v24-49-10]]

^<<v24-49-10,10>>^ Todavia, vou despojar Esaú.
Vou expor os seus esconderijos,
Para que ele não se possa esconder.
Os seus filhos, os seus irmãos e os seus vizinhos serão todos destruídos,
E ele deixará de existir.

[[v24-49-11]]

^<<v24-49-11,11>>^ Deixa os teus órfãos,^&#42;1^
E eu vou preservá-los vivos;
E as tuas viúvas confiarão em mim.”

[NOTE]
====
. Ou: “órfãos de pai”.
====

[[v24-49-12]]

^<<v24-49-12,12>>^ Pois assim diz Jeová: “Vejam! Se aqueles que não foram condenados a beber o cálice da minha ira terão de bebê-lo, será que tu devias ficar completamente impune? Não ficarás impune, pois terás de o beber.”

[[v24-49-13]]

^<<v24-49-13,13>>^ “Pois jurei por mim mesmo”, diz Jeová, “que Bozra se tornará um motivo de terror, um alvo de gozo, um lugar devastado e um exemplo de maldição. E todas as suas cidades hão de tornar-se uma ruína permanente.”

[[v24-49-14]]

^<<v24-49-14,14>>^ Eu ouvi uma notícia da parte de Jeová,
Enviou-se um mensageiro para dizer às nações:
“Reúnam-se e venham contra ela,
Preparem-se para a batalha.”

[[v24-49-15]]

^<<v24-49-15,15>>^ “Vê! Eu tornei-te insignificante entre as nações,
Desprezado entre os homens.

[[v24-49-16]]

^<<v24-49-16,16>>^ O medo que causavas
E a arrogância do teu coração enganaram-te,
Ó tu, que resides nos refúgios do rochedo,
Que ocupas o monte mais alto.
Mesmo que construas o teu ninho no alto, como a águia,
Eu farei com que desças de lá”, diz Jeová.

[[v24-49-17]]

^<<v24-49-17,17>>^ “E Edom irá tornar-se um motivo de terror. Todos os que passarem por lá olharão aterrorizados e assobiarão por causa de todas as suas pragas.

[[v24-49-18]]

^<<v24-49-18,18>>^ Assim como aconteceu na devastação de Sodoma e Gomorra e das suas cidades vizinhas”, diz Jeová, “não morará lá ninguém, nenhum homem se estabelecerá ali.

[[v24-49-19]]

^<<v24-49-19,19>>^ “Vejam! Alguém virá contra as pastagens seguras como um leão que sai dos densos bosques ao longo do Jordão, mas, num instante, vou fazer com que ele^&#42;1^ fuja para longe dela.^&#42;2^ E designarei sobre ela aquele que foi escolhido. Pois quem é igual a mim? Quem é que me desafiará? Qual é o pastor que pode ficar de pé diante de mim?

[NOTE]
====
. Provavelmente, refere-se a Edom.
. Provavelmente, refere-se à terra de Edom.
====

[[v24-49-20]]

^<<v24-49-20,20>>^ Portanto, ó homens, ouçam a decisão^&#42;1^ que Jeová tomou contra Edom e o que ele pretende fazer contra os habitantes de Temã:
Os cordeiros certamente serão arrastados para longe.
Ele desolará as suas pastagens^&#42;2^ por causa deles.

[NOTE]
====
. Ou: “o conselho”.
. Ou: “a sua morada”.
====

[[v24-49-21]]

^<<v24-49-21,21>>^ Com o estrondo da sua queda, a terra tremeu.
Há um clamor!
O som dele ouve-se até no mar Vermelho.

[[v24-49-22]]

^<<v24-49-22,22>>^ Vejam! Como uma águia, ele subirá e mergulhará sobre a presa,
E estenderá as asas sobre Bozra.
Nesse dia, o coração dos guerreiros de Edom
Vai tornar-se como o coração de uma mulher em trabalho de parto.”

[[v24-49-23]]

^<<v24-49-23,23>>^ A respeito de Damasco:
“Hamate e Arpade foram envergonhadas
Por causa das más notícias que ouviram.
Elas estão a derreter-se de medo.
O mar está agitado e não pode ser acalmado.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damasco perdeu a coragem.
Virou-se para fugir, mas o pânico tomou conta dela.
Dores e aflição dominaram-na,
Como acontece com a mulher que está a dar à luz.

[[v24-49-25]]

^<<v24-49-25,25>>^ Como é que a cidade do louvor não foi abandonada,
A cidade da alegria?

[[v24-49-26]]

^<<v24-49-26,26>>^ Pois os seus jovens cairão nas praças,
E todos os soldados morrerão nesse dia”, diz Jeová dos exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ “Deitarei fogo à muralha de Damasco,
Que devorará as torres fortificadas de Ben-Hadade.”

[[v24-49-28]]

^<<v24-49-28,28>>^ Assim diz Jeová a respeito de Quedar e dos reinos de Hazor, conquistados por Nabucodonosor,^&#42;1^ rei de Babilónia:
“Vão! Subam a Quedar
E destruam os filhos do Oriente.

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-49-29]]

^<<v24-49-29,29>>^ Peguem nas suas tendas e nos seus rebanhos,
Nos panos das suas tendas e em todos os seus bens.
Levem os seus camelos.
As pessoas hão de gritar-lhes: ‘Há terror em todo o lado!’”

[[v24-49-30]]

^<<v24-49-30,30>>^ “Fujam, vão para longe!
Escondam-se nas profundezas, ó habitantes de Hazor”, diz Jeová.
“Pois Nabucodonosor,^&#42;1^ rei de Babilónia, traçou uma estratégia contra vocês
E armou um plano contra vocês.”

[NOTE]
====
. Lit.: “Nabucodorosor”, grafia variante.
====

[[v24-49-31]]

^<<v24-49-31,31>>^ “Vão! Subam contra a nação que está em paz,
A morar em segurança!”, diz Jeová.
“Ela não tem portas nem trancas; eles moram isolados.

[[v24-49-32]]

^<<v24-49-32,32>>^ Os seus camelos vão tornar-se despojo;
E o seu gado numeroso, saque.
Espalharei em todas as direções^&#42;1^
Aqueles que cortam o cabelo nas têmporas,
E trarei a sua calamidade de todos os lados”, diz Jeová.

[NOTE]
====
. Lit.: “a todos os ventos”.
====

[[v24-49-33]]

^<<v24-49-33,33>>^ “E Hazor há de tornar-se um esconderijo de chacais,
Uma desolação permanente.
Ninguém morará lá,
E nenhum homem se estabelecerá nela.”

[[v24-49-34]]

^<<v24-49-34,34>>^ No começo do reinado de Zedequias, rei de Judá, o profeta Jeremias recebeu a seguinte palavra de Jeová a respeito de Elão:

[[v24-49-35]]

^<<v24-49-35,35>>^ “Assim diz Jeová dos exércitos: ‘Vou partir o arco de Elão, a fonte^&#42;1^ do seu poder.

[NOTE]
====
. Lit.: “o princípio”.
====

[[v24-49-36]]

^<<v24-49-36,36>>^ Vou trazer os quatro ventos das quatro extremidades dos céus sobre Elão, e vou espalhar os seus habitantes na direção de todos esses ventos. Não haverá nação para onde não sejam levados os que forem espalhados de Elão.’”

[[v24-49-37]]

^<<v24-49-37,37>>^ “Deixarei os elamitas apavorados diante dos seus inimigos e dos que procuram tirar-lhes a vida;^&#42;1^ e vou trazer sobre eles uma calamidade, a minha ira ardente”, diz Jeová. “Vou enviar a espada atrás deles até que os tenha exterminado.”

[NOTE]
====
. Ou: “procuram a sua alma”.
====

[[v24-49-38]]

^<<v24-49-38,38>>^ “E colocarei o meu trono em Elão, e destruirei o seu rei e os seus príncipes”, diz Jeová.

[[v24-49-39]]

^<<v24-49-39,39>>^ “Porém, na parte final dos dias, vou reunir o povo cativo de Elão”, diz Jeová.

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]