include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-48-1]]

^<<v24-48-1,1>>^ Assim diz Jeová dos exércitos, o Deus de Israel, a respeito de Moabe:
“Ai de Nebo, pois foi destruída!
Quiriataim foi envergonhada e conquistada.
O refúgio seguro^&#42;1^ foi envergonhado e despedaçado.

[NOTE]
====
. Ou: “refúgio num lugar alto”.
====

[[v24-48-2]]

^<<v24-48-2,2>>^ Eles já não louvam Moabe.
Em Hésbon tramaram a sua queda:
‘Venham, vamos eliminar esta nação.’
Também tu, ó Madmém, permanece em silêncio.
Pois a espada persegue-te.

[[v24-48-3]]

^<<v24-48-3,3>>^ Ouve-se o som de um clamor que vem de Horonaim,
O som de destruição e grande ruína.

[[v24-48-4]]

^<<v24-48-4,4>>^ Moabe foi arrasada.
As suas crianças choram.

[[v24-48-5]]

^<<v24-48-5,5>>^ As pessoas choram sem parar enquanto sobem a caminho de Luíte.
E, na descida de Horonaim, ouvem-se gritos de aflição por causa da catástrofe.

[[v24-48-6]]

^<<v24-48-6,6>>^ Fujam! Salvem a vossa vida!^&#42;1^
Tornem-se como um junípero no deserto.

[NOTE]
====
. Ou: “alma”.
====

[[v24-48-7]]

^<<v24-48-7,7>>^ Visto que confias nas tuas obras e nos teus tesouros,
Também serás conquistada.
E Quemós irá para o exílio,
Juntamente com os seus sacerdotes e príncipes.

[[v24-48-8]]

^<<v24-48-8,8>>^ O destruidor invadirá todas as cidades,
E nenhuma cidade escapará.
O vale será arruinado,^&#42;1^
E a planície será devastada,^&#42;2^ conforme Jeová disse.

[NOTE]
====
. Ou: “A planície de vale será arruinada”.
. Ou: “o planalto será devastado”.
====

[[v24-48-9]]

^<<v24-48-9,9>>^ Ponham um marco para Moabe,
Pois ela fugirá quando ficar em ruínas,
E as suas cidades irão tornar-se um motivo de terror,
Ficarão sem habitantes.

[[v24-48-10]]

^<<v24-48-10,10>>^ Maldito aquele que cumpre a missão de Jeová com negligência!
Maldito aquele que refreia a sua espada de derramar sangue!

[[v24-48-11]]

^<<v24-48-11,11>>^ Os moabitas estão tranquilos desde a sua juventude,
Como o vinho que repousa sobre a borra.
Eles nunca foram despejados de um jarro para outro,
E nunca foram para o exílio.
É por isso que o seu sabor continua o mesmo,
E o seu aroma não mudou.

[[v24-48-12]]

^<<v24-48-12,12>>^ “‘Portanto, estão a chegar os dias’, diz Jeová, ‘em que vou enviar-lhes homens que os derramarão. Eles irão derramá-los, esvaziar os seus recipientes e despedaçar os seus jarros grandes.

[[v24-48-13]]

^<<v24-48-13,13>>^ E os moabitas irão envergonhar-se de Quemós, assim como a casa de Israel se envergonhou de Betel, que era a sua confiança.

[[v24-48-14]]

^<<v24-48-14,14>>^ Como é que se atrevem a dizer: “Somos guerreiros valentes, prontos para a batalha”?’

[[v24-48-15]]

^<<v24-48-15,15>>^ ‘Moabe foi destruída,
As suas cidades foram invadidas,
E os seus melhores jovens foram mortos’,
Diz o Rei, cujo nome é Jeová dos exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ A calamidade dos moabitas está prestes a chegar;
A sua queda aproxima-se rapidamente.

[[v24-48-17]]

^<<v24-48-17,17>>^ Tenham compaixão deles, todos vocês, seus vizinhos,
Todos os que conhecem o seu nome.
Digam-lhes: ‘Como é possível que a poderosa vara, o belo bastão, se tenha partido?’

[[v24-48-18]]

^<<v24-48-18,18>>^ Desce da tua glória
E senta-te sedenta,^&#42;1^ ó filha e habitante de Díbon,
Pois o destruidor de Moabe veio contra ti,
E arrasará os teus lugares fortificados.

[NOTE]
====
. Ou, possivelmente: “senta-te no solo árido”.
====

[[v24-48-19]]

^<<v24-48-19,19>>^ Para à beira da estrada e observa, habitante de Aroer.
Pergunta ao homem que está a fugir e à mulher que está a escapar: ‘O que é que aconteceu?’

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe foi envergonhada e ficou apavorada.
Lamentem e clamem.
Proclamem em Arnom que Moabe foi destruída.

[[v24-48-21]]

^<<v24-48-21,21>>^ “O julgamento chegou à planície,^&#42;1^ contra Holom, Jaaz e Mefaate;

[NOTE]
====
. Ou: “ao planalto”.
====

[[v24-48-22]]

^<<v24-48-22,22>>^ contra Díbon, Nebo e Bete-Diblataim;

[[v24-48-23]]

^<<v24-48-23,23>>^ contra Quiriataim, Bete-Gamul e Bete-Meom;

[[v24-48-24]]

^<<v24-48-24,24>>^ contra Queriote e Bozra; e contra todas as cidades da terra de Moabe, as distantes e as próximas.

[[v24-48-25]]

^<<v24-48-25,25>>^ ‘O poder^&#42;1^ de Moabe acabou;
O seu braço foi partido’, diz Jeová.

[NOTE]
====
. Lit.: “chifre”.
====

[[v24-48-26]]

^<<v24-48-26,26>>^ ‘Embriaguem-no, pois foi contra Jeová que ele se enalteceu.
Moabe revolve-se no seu vómito,
E é um alvo de gozo.

[[v24-48-27]]

^<<v24-48-27,27>>^ Não era Israel um alvo de gozo para ti?
Será que foi encontrado entre ladrões,
Para que abanasses a cabeça e falasses contra ele?

[[v24-48-28]]

^<<v24-48-28,28>>^ Saiam das cidades e morem nos rochedos, habitantes de Moabe.
E tornem-se como a pomba que faz o seu ninho nas paredes do precipício.’”

[[v24-48-29]]

^<<v24-48-29,29>>^ “Ouvimos falar do orgulho de Moabe; ele é muito arrogante.
Ouvimos falar da sua arrogância, do seu orgulho, da sua prepotência e da altivez do seu coração.”

[[v24-48-30]]

^<<v24-48-30,30>>^ “‘Eu conheço a sua fúria’, diz Jeová,
‘Mas a sua conversa vã não dará em nada;
Eles não farão nada.

[[v24-48-31]]

^<<v24-48-31,31>>^ É por isso que lamentarei por Moabe,
Clamarei por causa de todo o Moabe
E chorarei pelos homens de Quir-Heres.

[[v24-48-32]]

^<<v24-48-32,32>>^ Com mais choro do que por Jazer,
Chorarei por ti, ó videira de Sibma.
Os teus ramos viçosos cruzaram o mar,
Estenderam-se até ao mar, até Jazer.
Foi sobre as tuas frutas de verão e a tua colheita de uvas
Que o destruidor se lançou.

[[v24-48-33]]

^<<v24-48-33,33>>^ A alegria e o júbilo desapareceram do pomar
E da terra de Moabe.
Fiz com que o vinho dos lagares se secasse.
Não haverá mais ninguém a pisar uvas com gritos de alegria.
Haverá gritos, mas não de alegria.’”

[[v24-48-34]]

^<<v24-48-34,34>>^ “‘Há um clamor desde Hésbon até Eleale.
Eles erguem a voz até Jaaz,
Desde Zoar até Horonaim, até Eglate-Selisia.
Até mesmo as águas de Ninrim se esgotarão.

[[v24-48-35]]

^<<v24-48-35,35>>^ Farei desaparecer de Moabe’, diz Jeová,
‘Aqueles que fazem ofertas sobre os altos sagrados
E os que oferecem sacrifícios ao seu deus.

[[v24-48-36]]

^<<v24-48-36,36>>^ Por isso, o meu coração lamentará^&#42;1^ como uma flauta^&#42;2^ por Moabe,
E o meu coração lamentará^&#42;3^ como uma flauta^&#42;4^ pelos homens de Quir-Heres.
Pois a riqueza que ele produziu acabará.

[NOTE]
====
. Ou: “ficará agitado”.
. Isto é, uma flauta tocada em sinal de lamentação num funeral.
. Ou: “ficará agitado”.
. Isto é, uma flauta tocada em sinal de lamentação num funeral.
====

[[v24-48-37]]

^<<v24-48-37,37>>^ Todas as cabeças estão rapadas,
E todas as barbas estão cortadas.
Em todas as mãos há cortes,
E as suas ancas estão cingidas de serapilheira.’”^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v24-48-38]]

^<<v24-48-38,38>>^ “‘Em todos os terraços de Moabe
E em todas as suas praças,
Só há lamentações,
Pois despedacei Moabe,
Como um jarro que se deita fora’, diz Jeová.

[[v24-48-39]]

^<<v24-48-39,39>>^ ‘Como ela está apavorada! Lamentem!
Como Moabe virou as costas, envergonhado!
Moabe tornou-se um alvo de gozo,
Algo que causa terror a todos à sua volta.’”

[[v24-48-40]]

^<<v24-48-40,40>>^ “Pois assim diz Jeová:
‘Vejam! Assim como a águia mergulha sobre a presa,
O inimigo estenderá as asas contra Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ As cidades serão conquistadas,
E as suas fortalezas serão tomadas.
Nesse dia, o coração dos guerreiros de Moabe
Será como o coração de uma mulher em trabalho de parto.’”

[[v24-48-42]]

^<<v24-48-42,42>>^ “‘Moabe será aniquilado e deixará de existir como povo,
Pois foi contra Jeová que ele se enalteceu.

[[v24-48-43]]

^<<v24-48-43,43>>^ O pavor, a cova e a armadilha esperam por ti,
Ó habitante de Moabe’, diz Jeová.

[[v24-48-44]]

^<<v24-48-44,44>>^ ‘Quem fugir do pavor cairá na cova,
E quem sair da cova será apanhado pela armadilha.’
‘Pois trarei sobre Moabe o ano da sua punição’, diz Jeová.

[[v24-48-45]]

^<<v24-48-45,45>>^ ‘À sombra de Hésbon, os fugitivos pararão, exaustos.
De Hésbon sairá um fogo,
E do meio de Síon uma chama
Que devorará a testa de Moabe
E o crânio dos guerreiros violentos.’

[[v24-48-46]]

^<<v24-48-46,46>>^ ‘Ai de ti, Moabe!
O povo de Quemós foi eliminado.
Pois os teus filhos foram levados cativos,
E as tuas filhas foram para o exílio.

[[v24-48-47]]

^<<v24-48-47,47>>^ Contudo, na parte final dos dias, vou ajuntar o povo cativo de Moabe’, diz Jeová.
‘Aqui termina o julgamento de Moabe.’”

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]