include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-14-1]]

^<<v24-14-1,1>>^ Esta é a palavra de Jeová que Jeremias recebeu a respeito das secas:

[[v24-14-2]]

^<<v24-14-2,2>>^ Judá está de luto, e os seus portões estão desolados.
Eles estão abatidos, caídos por terra,
E um clamor sobe de Jerusalém.

[[v24-14-3]]

^<<v24-14-3,3>>^ Os seus senhores mandam os servos^&#42;1^ buscar água.
Eles vão até às cisternas^&#42;2^ e não encontram água.
Voltam com os recipientes vazios.
Envergonhados e desapontados,
Cobrem a cabeça.

[NOTE]
====
. Ou: “os pequenos”.
. Ou: “valas”.
====

[[v24-14-4]]

^<<v24-14-4,4>>^ Visto que o solo está rachado
Por causa da falta de chuva nesta terra,
Os lavradores estão desalentados e cobrem a cabeça.

[[v24-14-5]]

^<<v24-14-5,5>>^ Até mesmo a corça no campo abandona a cria recém-nascida
Porque não há erva verde.

[[v24-14-6]]

^<<v24-14-6,6>>^ Os jumentos selvagens ficam parados nas colinas sem vegetação,
Respiram ofegantes como os chacais;
Os seus olhos falham porque não há alimento.

[[v24-14-7]]

^<<v24-14-7,7>>^ Embora os nossos próprios erros deem testemunho contra nós,
Ó Jeová, age por causa do teu nome.
Pois os nossos atos infiéis são muitos,
E foi contra ti que pecámos.

[[v24-14-8]]

^<<v24-14-8,8>>^ Ó esperança de Israel, o seu Salvador em tempos de aflição,
Porque é que ages como um estrangeiro nesta terra,
Como um viajante que faz uma paragem apenas para passar a noite?

[[v24-14-9]]

^<<v24-14-9,9>>^ Porque é que ages como um homem atordoado,
Como um guerreiro que não pode salvar ninguém?
Pois tu estás no nosso meio, ó Jeová,
E nós levamos o teu nome.
Não nos abandones.

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim diz Jeová a respeito deste povo: “Eles gostam de vaguear; não controlam os pés. Por isso, Jeová não se agrada deles. Agora, ele vai lembrar-se dos erros deles e ajustar contas com eles por causa dos seus pecados.”

[[v24-14-11]]

^<<v24-14-11,11>>^ Então, Jeová disse-me: “Não ores pelo bem deste povo.

[[v24-14-12]]

^<<v24-14-12,12>>^ Quando jejuam, não ouço as suas súplicas; e, quando fazem ofertas queimadas e ofertas de cereais, não me agrado delas, pois vou acabar com eles por meio da espada, da fome e da peste.”^&#42;1^

[NOTE]
====
. Ou: “doença”.
====

[[v24-14-13]]

^<<v24-14-13,13>>^ A isto, eu disse: “Ai, Soberano Senhor Jeová! Os profetas estão a dizer ao povo: ‘Vocês não verão a espada nem passarão fome, mas eu vou dar-vos verdadeira paz neste lugar.’”

[[v24-14-14]]

^<<v24-14-14,14>>^ E Jeová respondeu-me: “Os profetas estão a profetizar mentiras em meu nome. Eu não os enviei, nem lhes dei nenhuma ordem, nem falei com eles. Eles estão a profetizar-vos uma visão falsa, uma adivinhação inútil e a mentira do seu próprio coração.

[[v24-14-15]]

^<<v24-14-15,15>>^ Portanto, isto é o que Jeová diz a respeito dos profetas que profetizam em meu nome sem que eu os tenha enviado, e que dizem que não haverá nem espada nem fome nesta terra: ‘Será pela espada e pela fome que esses profetas morrerão.

[[v24-14-16]]

^<<v24-14-16,16>>^ E os corpos do povo a quem eles profetizam serão lançados nas ruas de Jerusalém, por causa da fome e da espada. E não haverá ninguém para enterrá-los — nem a eles, nem às suas esposas, nem aos seus filhos, nem às suas filhas. Pois vou derramar sobre eles a calamidade que merecem.’

[[v24-14-17]]

^<<v24-14-17,17>>^ “Diz-lhes estas palavras:
‘Que os meus olhos derramem lágrimas, dia e noite, sem parar,
Pois a filha virgem do meu povo foi completamente derrotada e esmagada,
E o seu ferimento é muito grave.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se eu sair para o campo,
Vejo os que foram mortos pela espada.
E, se eu entrar na cidade,
Vejo as doenças causadas pela fome.
Pois tanto o profeta como o sacerdote vagueiam numa terra que não conhecem.’”

[[v24-14-19]]

^<<v24-14-19,19>>^ Será que rejeitaste completamente Judá ou abominaste^&#42;1^ Sião?
Porque é que nos feriste de tal modo que não há cura para nós?
Esperava-se a paz, mas não veio nada de bom;
Um tempo de cura, mas só há terror!

[NOTE]
====
. Ou: “a tua alma abominou”.
====

[[v24-14-20]]

^<<v24-14-20,20>>^ Nós reconhecemos a nossa maldade, ó Jeová,
E o erro dos nossos antepassados,
Pois pecámos contra ti.

[[v24-14-21]]

^<<v24-14-21,21>>^ Por causa do teu nome, não nos rejeites;
Não desprezes o teu trono glorioso.
Lembra-te do teu pacto connosco e não o anules.

[[v24-14-22]]

^<<v24-14-22,22>>^ Será que algum dos ídolos inúteis das nações pode dar chuva?
Ou será que os céus podem, por si mesmos, enviar chuvas abundantes?
Não és tu o único que pode fazer isso, ó Jeová, nosso Deus?
E nós esperamos em ti,
Pois somente tu tens feito todas estas coisas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]