include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-6-1]]

^<<v24-6-1,1>>^ Procurem refúgio longe de Jerusalém, ó filhos de Benjamim;
Toquem a buzina em Tecoa.
Acendam um sinal de fogo sobre Bete-Haquerém,
Pois aproxima-se uma calamidade vinda do norte, uma catástrofe.

[[v24-6-2]]

^<<v24-6-2,2>>^ A filha de Sião parece uma mulher bela e delicada.

[[v24-6-3]]

^<<v24-6-3,3>>^ Virão os pastores e os seus rebanhos.
Armarão as suas tendas ao redor dela,
E cada um levará o seu rebanho a pastar.

[[v24-6-4]]

^<<v24-6-4,4>>^ “Preparem-se para^&#42;1^ a guerra contra ela!
Vamos! Ataquemos ao meio-dia!”
“Que pena! Pois o dia está a chegar ao fim,
E as sombras do anoitecer já se estendem.”

[NOTE]
====
. Lit.: “Santifiquem”.
====

[[v24-6-5]]

^<<v24-6-5,5>>^ “Vamos! Ataquemos durante a noite
E destruamos as suas torres fortificadas.”

[[v24-6-6]]

^<<v24-6-6,6>>^ Pois assim diz Jeová dos exércitos:
“Cortem madeira e levantem uma rampa de ataque contra Jerusalém.
Ela é a cidade que tem de prestar contas.
Só há opressão dentro dela.

[[v24-6-7]]

^<<v24-6-7,7>>^ Assim como a cisterna mantém a água fresca,
Ela também mantém fresca a sua maldade.
Ouve-se nela violência e destruição;
A doença e a praga estão constantemente diante de mim.

[[v24-6-8]]

^<<v24-6-8,8>>^ Acata o aviso, Jerusalém, senão eu irei^&#42;1^ abandonar-te com aversão,
E farei de ti uma terra desolada e desabitada.”

[NOTE]
====
. Ou: “a minha alma irá”.
====

[[v24-6-9]]

^<<v24-6-9,9>>^ Assim diz Jeová dos exércitos:
“Eles respigarão completamente o restante de Israel, assim como se faz com as últimas uvas de uma videira.
Passa a mão nas videiras outra vez, como faz aquele que colhe uvas.”

[[v24-6-10]]

^<<v24-6-10,10>>^ “A quem devo falar e advertir?
Quem é que ouvirá?
Eles estão com os ouvidos tapados;^&#42;1^ por isso, são incapazes de prestar atenção.
A palavra de Jeová tornou-se desprezível para eles;
Não têm prazer nela.

[NOTE]
====
. Lit.: “O seu ouvido é incircunciso”.
====

[[v24-6-11]]

^<<v24-6-11,11>>^ Por isso, o furor de Jeová que está dentro de mim transborda,
Não aguento mais contê-lo.”
“Derrama-o sobre a criança na rua
E sobre os jovens reunidos.
Pois todos serão apanhados: o homem com a sua esposa,
E os idosos com os de idade bem avançada.^&#42;1^

[NOTE]
====
. Lit.: “os cheios de dias”.
====

[[v24-6-12]]

^<<v24-6-12,12>>^ As suas casas serão entregues a outros,
Juntamente com os seus campos e as suas esposas.
Pois estenderei a minha mão contra os habitantes do país”, diz Jeová.

[[v24-6-13]]

^<<v24-6-13,13>>^ “Desde o menor até ao maior, todos eles obtêm lucro desonesto;
Desde o profeta até ao sacerdote, todos cometem fraudes.

[[v24-6-14]]

^<<v24-6-14,14>>^ E tratam superficialmente as feridas^&#42;1^ do meu povo, dizendo:
‘Há paz! Há paz!’,
Quando não há paz.

[NOTE]
====
. Ou: “a fratura; o quebrantamento”.
====

[[v24-6-15]]

^<<v24-6-15,15>>^ Será que eles se envergonham das coisas detestáveis que fizeram?
Eles não sentem a mínima vergonha!
Nem sequer sabem o que é sentir vergonha!
Por isso, cairão entre os que já caíram.
Tropeçarão quando eu lhes trouxer a punição”, diz Jeová.

[[v24-6-16]]

^<<v24-6-16,16>>^ Assim diz Jeová:
“Parem nos cruzamentos das estradas e observem.
Perguntem pelas estradas antigas,
Perguntem onde está o bom caminho e andem nele,
E vocês^&#42;1^ encontrarão descanso.”
Porém, eles dizem: “Não vamos andar nele.”

[NOTE]
====
. Ou: “E as vossas almas”.
====

[[v24-6-17]]

^<<v24-6-17,17>>^ “E eu designei vigias, que disseram:
‘Prestem atenção ao som da buzina!’”,
Mas eles disseram: “Não vamos prestar atenção.”

[[v24-6-18]]

^<<v24-6-18,18>>^ “Portanto, ouçam, ó nações!
E fica a saber, ó assembleia,
O que lhes vai acontecer.

[[v24-6-19]]

^<<v24-6-19,19>>^ Escuta, ó terra!
Vou trazer calamidade sobre este povo,
Como fruto das suas próprias tramas,
Pois eles não prestaram atenção às minhas palavras,
E rejeitaram a minha lei.”^&#42;1^

[NOTE]
====
. Ou: “instrução”.
====

[[v24-6-20]]

^<<v24-6-20,20>>^ “O que é que me importa se trazes olíbano de Sabá
E cálamo^&#42;1^ de uma terra distante?
As tuas ofertas queimadas não são aceitáveis,
E os teus sacrifícios não me agradam.”

[NOTE]
====
. Uma cana aromática.
====

[[v24-6-21]]

^<<v24-6-21,21>>^ Portanto, assim diz Jeová:
“Vou pôr pedras de tropeço diante deste povo,
E eles tropeçarão nelas,
Pais e filhos,
Vizinhos e amigos,
E todos eles morrerão.”

[[v24-6-22]]

^<<v24-6-22,22>>^ Assim diz Jeová:
“Vejam! Vem aí um povo da terra do norte;
Uma grande nação está a ser despertada das partes mais distantes da terra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Eles trarão arcos e lanças.
São cruéis e não terão misericórdia.
A sua voz ressoará como o mar.
Eles vêm montados em cavalos.
Vêm contra ti como guerreiros em formação de batalha, ó filha de Sião.”

[[v24-6-24]]

^<<v24-6-24,24>>^ Ouvimos a notícia a respeito disso.
As nossas mãos enfraqueceram.
Apoderou-se de nós a aflição,
A angústia,^&#42;1^ como a de uma mulher que dá à luz.

[NOTE]
====
. Lit.: “As dores de parto”.
====

[[v24-6-25]]

^<<v24-6-25,25>>^ Não saias para o campo
Nem andes pelas estradas,
Pois o inimigo tem uma espada;
Há terror em toda a parte.

[[v24-6-26]]

^<<v24-6-26,26>>^ Ó filha do meu povo,
Veste-te de serapilheira^&#42;1^ e revolve-te nas cinzas.
Fica de luto e chora amargamente como se tivesses perdido um filho único.
Pois o destruidor virá de repente sobre nós.

[NOTE]
====
. Veja o Glossário.
====

[[v24-6-27]]

^<<v24-6-27,27>>^ “Fiz de ti^&#42;1^ um examinador de metal entre o meu povo,
Alguém que faz uma análise completa;
Presta atenção e avalia o seu caminho.

[NOTE]
====
. Isto é, de Jeremias.
====

[[v24-6-28]]

^<<v24-6-28,28>>^ Eles são os homens mais obstinados que existem,
E estão sempre a espalhar calúnias.
São como o cobre e o ferro;
Todos eles são corruptos.

[[v24-6-29]]

^<<v24-6-29,29>>^ Os foles ficaram chamuscados;
O fogo só produziu chumbo.
O refinador trabalha arduamente em vão,
Pois os maus não foram eliminados.

[[v24-6-30]]

^<<v24-6-30,30>>^ As pessoas vão certamente chamar-lhes prata rejeitada,
Porque Jeová os rejeitou.”

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]