include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-13-1]]

^<<v24-13-1,1>>^ Assim me disse Jeová: “Vai, compra um cinto de linho e coloca-o na cintura, mas não o ponhas na água.”

[[v24-13-2]]

^<<v24-13-2,2>>^ Então, eu comprei o cinto de acordo com a palavra de Jeová e coloquei-o na cintura.

[[v24-13-3]]

^<<v24-13-3,3>>^ Depois, recebi a palavra de Jeová pela segunda vez:

[[v24-13-4]]

^<<v24-13-4,4>>^ “Pega no cinto que compraste e que estás a usar, vai até ao rio Eufrates e esconde-o lá, na fenda de um rochedo.”

[[v24-13-5]]

^<<v24-13-5,5>>^ Por conseguinte, eu fui e escondi-o junto ao Eufrates, assim como Jeová me tinha ordenado.

[[v24-13-6]]

^<<v24-13-6,6>>^ Passados muitos dias, Jeová disse-me: “Vai até ao rio Eufrates e traz de volta o cinto que te mandei esconder lá.”

[[v24-13-7]]

^<<v24-13-7,7>>^ Portanto, fui até ao Eufrates, desenterrei o cinto e tirei-o do lugar onde o tinha escondido. E vi que o cinto estava estragado, já não prestava para nada.

[[v24-13-8]]

^<<v24-13-8,8>>^ Então, recebi a seguinte palavra de Jeová:

[[v24-13-9]]

^<<v24-13-9,9>>^ “Assim diz Jeová: ‘É deste modo que vou acabar com o orgulho de Judá e com o imenso orgulho de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Este povo mau, que se recusa a obedecer às minhas palavras, que teima em seguir o seu próprio coração e que segue outros deuses, servindo-os e curvando-se diante deles, ficará igual a este cinto que já não presta para nada.’

[[v24-13-11]]

^<<v24-13-11,11>>^ ‘Pois, assim como um cinto se apega à cintura do homem, assim fiz com que toda a casa de Israel e toda a casa de Judá se apegassem a mim’, diz Jeová, ‘para que fossem, para mim, um povo, fama, louvor e algo belo, mas eles não obedeceram’.

[[v24-13-12]]

^<<v24-13-12,12>>^ “E também deves transmitir-lhes esta mensagem: ‘Assim diz Jeová, o Deus de Israel: “Devem encher-se todas as talhas grandes com vinho.”’ E eles irão responder-te: ‘Por acaso, já não sabemos que se devem encher todas as talhas grandes com vinho?’

[[v24-13-13]]

^<<v24-13-13,13>>^ Portanto, diz-lhes: ‘Assim diz Jeová: “Farei com que todos os habitantes desta terra, os reis que se sentam no trono de David, os sacerdotes, os profetas e todos os habitantes de Jerusalém fiquem totalmente embriagados.

[[v24-13-14]]

^<<v24-13-14,14>>^ E vou despedaçá-los, batendo uns contra os outros, tanto os pais como os filhos”, diz Jeová. “Não terei compaixão, nem sentirei dó, nem mostrarei misericórdia; nada me impedirá de os destruir.”’

[[v24-13-15]]

^<<v24-13-15,15>>^ Ouçam e prestem atenção.
Não sejam arrogantes, pois Jeová falou.

[[v24-13-16]]

^<<v24-13-16,16>>^ Deem glória a Jeová, vosso Deus,
Antes que ele traga a escuridão
E antes que os vossos pés tropecem nos montes, ao anoitecer.
Vocês esperarão pela luz,
Mas ele trará profunda escuridão;
Ele transformará a luz em densas trevas.

[[v24-13-17]]

^<<v24-13-17,17>>^ Se vocês se recusarem a ouvir,
Eu chorarei^&#42;1^ em segredo por causa do vosso orgulho.
Derramarei muitas lágrimas; dos meus olhos escorrerão lágrimas,
Porque o rebanho de Jeová foi levado cativo.

[NOTE]
====
. Ou: “A minha alma chorará”.
====

[[v24-13-18]]

^<<v24-13-18,18>>^ Diz ao rei e à rainha-mãe:^&#42;1^ ‘Sentem-se no chão,
Pois a vossa bela coroa vai cair-vos da cabeça.’

[NOTE]
====
. Ou: “à senhora”.
====

[[v24-13-19]]

^<<v24-13-19,19>>^ As cidades do sul estão fechadas,^&#42;1^ sem ninguém que as abra.
Todo o povo de Judá foi levado para o exílio; foi levado para o exílio, na sua totalidade.

[NOTE]
====
. Ou: “cercadas”.
====

[[v24-13-20]]

^<<v24-13-20,20>>^ Levanta os olhos e vê os que estão a chegar do norte.
Onde está o rebanho que te foi dado, as tuas belas ovelhas?

[[v24-13-21]]

^<<v24-13-21,21>>^ O que é que dirás quando chegar a tua punição
Da parte daqueles que sempre trataste como amigos íntimos?
Não se apoderarão de ti dores agudas, como as da mulher que dá à luz?

[[v24-13-22]]

^<<v24-13-22,22>>^ Quando disseres no coração: ‘Porque é que estas coisas me aconteceram?’
Fica a saber que foi por causa do teu grande erro que te tiraram a saia
E que os teus calcanhares foram cruelmente tratados.

[[v24-13-23]]

^<<v24-13-23,23>>^ Será que o cuchita^&#42;1^ pode mudar a cor da sua pele, ou o leopardo as suas manchas?
Se assim fosse, vocês, os que são treinados para fazer o mal,
Também poderiam fazer o bem.

[NOTE]
====
. Ou: “etíope”.
====

[[v24-13-24]]

^<<v24-13-24,24>>^ Por isso, vou espalhar-vos como a palha levada pelo vento do deserto.

[[v24-13-25]]

^<<v24-13-25,25>>^ Esta é a parte que te cabe, a porção que separei para ti”, diz Jeová,
“Porque te esqueceste de mim para confiar em mentiras.

[[v24-13-26]]

^<<v24-13-26,26>>^ Portanto, vou levantar-te a saia até cobrir o teu rosto,
E a tua vergonha será exposta,

[[v24-13-27]]

^<<v24-13-27,27>>^ Os teus atos de adultério e a tua paixão,^&#42;1^
A tua prostituição obscena.^&#42;2^
Sobre as colinas, nos campos,
Eu vi o teu comportamento repugnante.
Ai de ti, Jerusalém!
Até quando é que continuarás impura?”

[NOTE]
====
. Ou: “os teus relinchos de paixão”.
. Ou: “vergonhosa”.
====

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]