include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-23-1]]

^<<v24-23-1,1>>^ “Ai dos pastores que destroem e espalham as ovelhas do meu pasto!”, diz Jeová.

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim diz Jeová, o Deus de Israel, contra os pastores que pastoreiam o meu povo: “Vocês espalharam as minhas ovelhas, dispersaram-nas e não voltaram a vossa atenção para elas.”
“Portanto, voltarei a minha atenção para vocês por causa das vossas más ações”, diz Jeová.

[[v24-23-3]]

^<<v24-23-3,3>>^ “Depois, reunirei o restante das minhas ovelhas dentre todas as terras pelas quais as espalhei, e vou trazê-las de volta à sua pastagem, e elas hão de reproduzir-se e tornar-se muitas.

[[v24-23-4]]

^<<v24-23-4,4>>^ E, sobre elas, vou colocar pastores que realmente as pastoreiem. Elas não voltarão a ter medo, nem ficarão apavoradas, e nenhuma delas se perderá”, diz Jeová.

[[v24-23-5]]

^<<v24-23-5,5>>^ “Vejam! Estão a chegar os dias”, diz Jeová, “em que farei surgir para David um renovo^&#42;1^ justo. E um rei reinará; ele mostrará entendimento^&#42;2^ e defenderá a justiça e a retidão no país.^&#42;3^

[NOTE]
====
. Ou: “herdeiro”.
. Ou: “perspicácia”.
. Ou: “na terra”.
====

[[v24-23-6]]

^<<v24-23-6,6>>^ Nos seus dias, Judá será salvo e Israel residirá em segurança. E este é o nome pelo qual ele será chamado: Jeová É a Nossa Justiça.”

[[v24-23-7]]

^<<v24-23-7,7>>^ “Contudo, estão a chegar os dias”, diz Jeová, “em que não voltarão a dizer: ‘Tão certo como vive Jeová, aquele que tirou o povo de Israel da terra do Egito!’,

[[v24-23-8]]

^<<v24-23-8,8>>^ mas dirão: ‘Tão certo como vive Jeová, aquele que tirou e trouxe os descendentes da casa de Israel da terra do norte e de todas as terras pelas quais eu os tinha espalhado’, e eles morarão na sua própria terra.”

[[v24-23-9]]

^<<v24-23-9,9>>^ Sobre os profetas:
O meu coração está quebrantado dentro de mim.
Os meus ossos estão todos a tremer.
Pareço um homem bêbado,
Um homem vencido pelo vinho,
Por causa de Jeová e das suas santas palavras.

[[v24-23-10]]

^<<v24-23-10,10>>^ Pois esta terra está cheia de adúlteros.
Por causa da maldição, esta terra ficou de luto,
E as pastagens do deserto^&#42;1^ secaram-se.
O seu modo de agir é mau, e eles abusam do poder que têm.

[NOTE]
====
. Veja o Glossário.
====

[[v24-23-11]]

^<<v24-23-11,11>>^ “Tanto os profetas como os sacerdotes são impuros.^&#42;1^
Até na minha própria casa encontrei a sua maldade”, diz Jeová.

[NOTE]
====
. Ou: “apóstatas”.
====

[[v24-23-12]]

^<<v24-23-12,12>>^ “Por isso, o seu caminho irá tornar-se escorregadio e escuro;
Eles serão empurrados e cairão.
Pois vou trazer-lhes calamidade
No ano do ajuste de contas”, diz Jeová.

[[v24-23-13]]

^<<v24-23-13,13>>^ “Nos profetas de Samaria, eu vi algo repugnante:
As suas profecias são da parte de Baal,
E eles desencaminham o meu povo Israel.

[[v24-23-14]]

^<<v24-23-14,14>>^ E, nos profetas de Jerusalém, eu vi coisas horríveis:
Eles cometem adultério e vivem na mentira,
Apoiam os^&#42;1^ malfeitores
E não abandonam a sua maldade.
Para mim, todos eles são como Sodoma,
E os seus habitantes são como Gomorra.”

[NOTE]
====
. Lit.: “Fortalecem as mãos dos”.
====

[[v24-23-15]]

^<<v24-23-15,15>>^ Portanto, assim diz Jeová dos exércitos contra os profetas:
“Vou fazê-los comer absinto
E vou dar-lhes água envenenada para beber.
Pois os profetas de Jerusalém espalharam a apostasia por todo o país.”

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim diz Jeová dos exércitos:
“Não deem ouvidos às palavras dos profetas que vos profetizam.
Eles estão a iludir-vos.^&#42;1^
Falam das visões que vêm do seu próprio coração,
Não da boca de Jeová.

[NOTE]
====
. Ou: “Eles estão a encher-vos de esperanças vazias.”
====

[[v24-23-17]]

^<<v24-23-17,17>>^ Dizem, vez após vez, aos que me desrespeitam:
‘Jeová disse: “Terão paz.”’
E a todos os que seguem o seu próprio coração obstinado, eles dizem:
‘Nenhuma calamidade vos sobrevirá.’

[[v24-23-18]]

^<<v24-23-18,18>>^ Mas quem é que faz parte do grupo^&#42;1^ íntimo de Jeová
Para observar e acatar a sua palavra?
Quem é que prestou atenção à sua palavra e lhe obedeceu?

[NOTE]
====
. Ou: “círculo”.
====

[[v24-23-19]]

^<<v24-23-19,19>>^ Vejam! O vendaval da parte de Jeová irromperá com fúria;
Como um tufão, rodopiará sobre a cabeça dos maus.

[[v24-23-20]]

^<<v24-23-20,20>>^ A ira de Jeová não recuará
Até que ele tenha cumprido e executado as intenções do seu coração.
Na parte final dos dias, vocês entenderão isto claramente.

[[v24-23-21]]

^<<v24-23-21,21>>^ Não enviei esses profetas; mesmo assim, eles foram a correr.
Não falei com eles; mesmo assim, profetizaram.

[[v24-23-22]]

^<<v24-23-22,22>>^ Contudo, se eles fizessem parte do meu grupo^&#42;1^ íntimo,
Teriam feito o meu povo ouvir as minhas palavras,
Além de os levarem a recuar do seu mau caminho e das suas más ações.”

[NOTE]
====
. Ou: “círculo”.
====

[[v24-23-23]]

^<<v24-23-23,23>>^ “Será que sou apenas um Deus que está perto”, diz Jeová, “e não também um Deus que está longe?”

[[v24-23-24]]

^<<v24-23-24,24>>^ “Pode algum homem esconder-se num lugar onde eu não o veja?”, diz Jeová.
“Por acaso, não ocupo eu os céus e a terra?”, diz Jeová.

[[v24-23-25]]

^<<v24-23-25,25>>^ “Eu ouvi os profetas que profetizam mentiras em meu nome. Eles dizem: ‘Tive um sonho! Tive um sonho!’

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando continuará no coração dos profetas o profetizar mentiras? Eles profetizam as mentiras do seu próprio coração.

[[v24-23-27]]

^<<v24-23-27,27>>^ Com os sonhos que contam uns aos outros, eles querem que o meu povo se esqueça do meu nome, assim como os seus pais se esqueceram do meu nome por causa de Baal.

[[v24-23-28]]

^<<v24-23-28,28>>^ Que o profeta que tem um sonho conte o seu sonho, mas que aquele que tem a minha palavra fale da minha palavra fielmente.”
“O que tem a palha a ver com o grão?”, diz Jeová.

[[v24-23-29]]

^<<v24-23-29,29>>^ “Não é a minha palavra como um fogo”, diz Jeová, “e como um martelo^&#42;1^ que despedaça o rochedo?”

[NOTE]
====
. Ou: “malho”.
====

[[v24-23-30]]

^<<v24-23-30,30>>^ “Por isso, estou contra os profetas”, diz Jeová, “aqueles que roubam as minhas palavras uns aos outros”.

[[v24-23-31]]

^<<v24-23-31,31>>^ “Eu estou contra os profetas”, diz Jeová, “aqueles que usam a língua para dizer: ‘Assim diz Ele!’”

[[v24-23-32]]

^<<v24-23-32,32>>^ “Eu estou contra os profetas de sonhos falsos”, diz Jeová, “aqueles que os relatam e desencaminham o meu povo com as suas mentiras e a sua arrogância”.
“No entanto, eu não os enviei nem lhes dei qualquer ordem. Portanto, eles não serão de nenhum proveito para este povo”, diz Jeová.

[[v24-23-33]]

^<<v24-23-33,33>>^ “Quando alguém do povo, ou um profeta ou um sacerdote te perguntar: ‘Qual é o fardo^&#42;1^ de Jeová?’, então, responde-lhes: ‘“Vocês é que são o fardo! E eu vou livrar-me de vocês”, diz Jeová.’

[NOTE]
====
. Ou: “a mensagem pesada”. A palavra hebraica tem sentido duplo: “um pronunciamento divino de peso” ou “algo pesado”.
====

[[v24-23-34]]

^<<v24-23-34,34>>^ Quanto ao profeta, ao sacerdote ou a alguém do povo que diz: ‘Este é o fardo^&#42;1^ de Jeová!’, eu vou voltar-me contra esse homem e contra os da sua casa.

[NOTE]
====
. Ou: “Esta é a mensagem pesada”.
====

[[v24-23-35]]

^<<v24-23-35,35>>^ Cada um de vocês pergunta o seguinte ao seu amigo e ao seu irmão: ‘O que é que Jeová respondeu? O que é que Jeová disse?’

[[v24-23-36]]

^<<v24-23-36,36>>^ Contudo, não falem mais sobre o fardo^&#42;1^ de Jeová, pois o fardo^&#42;2^ é a palavra de cada um, e vocês mudaram as palavras do Deus vivente, Jeová dos exércitos, o nosso Deus.

[NOTE]
====
. Ou: “a mensagem pesada”.
. Ou: “a mensagem pesada”.
====

[[v24-23-37]]

^<<v24-23-37,37>>^ “Isto é o que dirás aos profetas: ‘Qual foi a resposta que Jeová te deu? O que é que Jeová disse?

[[v24-23-38]]

^<<v24-23-38,38>>^ E, se continuarem a dizer: “O fardo^&#42;1^ de Jeová!”, assim diz Jeová: “Visto que dizem: ‘Esta palavra é o fardo de Jeová’, depois de eu vos ter ordenado: ‘Não digam: “O fardo^&#42;2^ de Jeová!”’,

[NOTE]
====
. Ou: “A mensagem pesada”.
. Ou: “A mensagem pesada”.
====

[[v24-23-39]]

^<<v24-23-39,39>>^ então, vou levantar-vos e lançar-vos para longe de mim, tanto a vocês como à cidade que vos dei e que dei também aos vossos antepassados.

[[v24-23-40]]

^<<v24-23-40,40>>^ E, sobre vocês, trarei desonra e humilhação eternas, que nunca serão esquecidas.”’”

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]