include::./index.adoc[]

[[v24-44-0]]
=== Jeremias, 44
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-44-1]]

^<<v24-44-1,1>>^ Jeremias recebeu a seguinte palavra para transmitir a todos os judeus que moravam na terra do Egito, os que moravam em Migdol, em Tafnes, em Nofe^&#42;1^ e na terra de Patros:

[NOTE]
====
. Ou: “Mênfis”.
====

[[v24-44-2]]

^<<v24-44-2,2>>^ “Assim diz Jeová dos exércitos, o Deus de Israel: ‘Viram toda a calamidade que eu trouxe sobre Jerusalém e sobre todas as cidades de Judá, e hoje elas estão em ruínas, sem nenhum habitante.

[[v24-44-3]]

^<<v24-44-3,3>>^ Isto aconteceu por causa das coisas más que eles fizeram para me ofender, oferecendo sacrifícios e servindo outros deuses que eles não conheciam, nem vocês, nem os vossos antepassados.

[[v24-44-4]]

^<<v24-44-4,4>>^ Eu enviava-vos todos os meus servos, os profetas; enviava-os vez após vez,^&#42;1^ dizendo: “Por favor, não façam estas coisas detestáveis, que eu odeio.”

[NOTE]
====
. Lit.: “os profetas; levantando-me cedo e enviando”.
====

[[v24-44-5]]

^<<v24-44-5,5>>^ Porém, eles não deram ouvidos nem prestaram atenção^&#42;1^ de modo a recuarem da sua maldade, por deixarem de fazer sacrifícios a outros deuses.

[NOTE]
====
. Ou: “nem inclinaram o seu ouvido”.
====

[[v24-44-6]]

^<<v24-44-6,6>>^ Por isso, derramei o meu furor e a minha ira, que arderam nas cidades de Judá e nas ruas de Jerusalém, e elas tornaram-se em ruínas e desolação, como estão hoje.’

[[v24-44-7]]

^<<v24-44-7,7>>^ “E agora, assim diz Jeová, o Deus dos exércitos, o Deus de Israel: ‘Porque é que trazem uma grande calamidade sobre vocês próprios,^&#42;1^ a ponto de serem eliminados de Judá todos os homens e mulheres, crianças e bebés, sem que sobre sequer um restante?

[NOTE]
====
. Ou: “as vossas almas”.
====

[[v24-44-8]]

^<<v24-44-8,8>>^ Porque é que haviam de ofender-me com as obras das vossas mãos, por fazerem sacrifícios a outros deuses na terra do Egito, terra para a qual foram morar? Vocês vão morrer e tornar-se um objeto de maldição e um alvo de insultos entre todas as nações da terra.

[[v24-44-9]]

^<<v24-44-9,9>>^ Será que se esqueceram das maldades dos vossos antepassados, das maldades dos reis de Judá, das maldades das suas esposas, bem como das vossas próprias maldades e das maldades das vossas esposas, cometidas na terra de Judá e nas ruas de Jerusalém?

[[v24-44-10]]

^<<v24-44-10,10>>^ Até hoje, vocês^&#42;1^ não se humilharam,^&#42;2^ nem demonstraram temor, nem andaram na minha lei e nos meus decretos, que pus diante de vocês e dos vossos antepassados.’

[NOTE]
====
. Lit.: “eles”.
. Ou: “não se sentiram arrasados”.
====

[[v24-44-11]]

^<<v24-44-11,11>>^ “Portanto, assim diz Jeová dos exércitos, o Deus de Israel: ‘Estou decidido a trazer-vos calamidade, a destruir todo o Judá.

[[v24-44-12]]

^<<v24-44-12,12>>^ E vou pegar no restante de Judá, os que estavam decididos a ir morar para a terra do Egito, e todos eles morrerão na terra do Egito. Cairão pela espada e serão eliminados pela fome; desde o menor até ao maior, morrerão pela espada e pela fome. E hão de tornar-se um objeto de maldição, um motivo de terror, e um alvo de desprezo e de insultos.

[[v24-44-13]]

^<<v24-44-13,13>>^ Eu punirei os que moram na terra do Egito, assim como puni Jerusalém com a espada, a fome e a peste.^&#42;1^

[NOTE]
====
. Ou: “doença”.
====

[[v24-44-14]]

^<<v24-44-14,14>>^ E o restante de Judá que foi morar na terra do Egito não escapará nem sobreviverá para voltar para a terra de Judá. Terão um grande desejo de^&#42;1^ voltar a morar lá, mas não voltarão, à exceção de alguns fugitivos.’”

[NOTE]
====
. Ou: “Elevarão a sua alma para”.
====

[[v24-44-15]]

^<<v24-44-15,15>>^ Todos os homens que sabiam que as suas esposas tinham feito sacrifícios a outros deuses, e todas as esposas que lá estavam, formando um grande grupo, bem como todo o povo que morava em Patros, na terra do Egito, responderam a Jeremias:

[[v24-44-16]]

^<<v24-44-16,16>>^ “Não daremos ouvidos à palavra que nos transmitiste em nome de Jeová.

[[v24-44-17]]

^<<v24-44-17,17>>^ Em vez disso, certamente cumpriremos todas as palavras que a nossa boca proferiu: vamos fazer sacrifícios à Rainha do Céu^&#42;1^ e derramar-lhe ofertas de bebida, assim como nós, os nossos antepassados, os nossos reis e os nossos príncipes fizemos nas cidades de Judá e nas ruas de Jerusalém, quando tínhamos fartura de pão e não nos faltava nada, quando não víamos nenhuma calamidade.

[NOTE]
====
. Título de uma deusa adorada pelos israelitas apóstatas, possivelmente uma deusa da fertilidade.
====

[[v24-44-18]]

^<<v24-44-18,18>>^ Depois de deixarmos de fazer sacrifícios à Rainha do Céu^&#42;1^ e de lhe derramarmos ofertas de bebida, começou a faltar-nos tudo, e fomos eliminados pela espada e pela fome.”

[NOTE]
====
. Título de uma deusa adorada pelos israelitas apóstatas, possivelmente uma deusa da fertilidade.
====

[[v24-44-19]]

^<<v24-44-19,19>>^ As mulheres acrescentaram: “E, quando fazíamos sacrifícios à Rainha do Céu^&#42;1^ e lhe derramávamos ofertas de bebida, por acaso, foi sem o consentimento dos nossos maridos que fizemos bolos de oferenda com a forma da imagem dela e que lhe derramámos ofertas de bebida?”

[NOTE]
====
. Título de uma deusa adorada pelos israelitas apóstatas, possivelmente uma deusa da fertilidade.
====

[[v24-44-20]]

^<<v24-44-20,20>>^ Então, Jeremias disse a todo o povo, aos homens, às suas esposas e a todo o povo que falava com ele:

[[v24-44-21]]

^<<v24-44-21,21>>^ “Quanto aos sacrifícios que vocês, os vossos antepassados, os vossos reis, os vossos príncipes e o povo^&#42;1^ fizeram nas cidades de Judá e nas ruas de Jerusalém, Jeová lembrou-se deles; sim, eles vieram-lhe à mente!

[NOTE]
====
. Lit.: “povo da terra”.
====

[[v24-44-22]]

^<<v24-44-22,22>>^ Por fim, Jeová não pôde continuar a suportar as vossas práticas más e as coisas detestáveis que faziam; e a vossa terra tornou-se um lugar devastado, um motivo de terror e um exemplo de maldição, sem habitantes, assim como se vê hoje.

[[v24-44-23]]

^<<v24-44-23,23>>^ Visto que fizeram esses sacrifícios e pecaram contra Jeová, deixando de obedecer à voz de Jeová e de seguir a sua lei, os seus decretos e as suas advertências,^&#42;1^ sobreveio-vos esta calamidade, assim como se vê hoje.”

[NOTE]
====
. Ou: “os seus lembretes”.
====

[[v24-44-24]]

^<<v24-44-24,24>>^ Jeremias continuou a dizer a todo o povo e a todas as mulheres: “Ouçam a palavra de Jeová, todos os de Judá que estão na terra do Egito.

[[v24-44-25]]

^<<v24-44-25,25>>^ Assim diz Jeová dos exércitos, o Deus de Israel: ‘O que vocês e as vossas esposas disseram com a boca, cumpriram com as mãos, pois disseram: “Certamente cumpriremos os nossos votos de fazer sacrifícios à Rainha do Céu^&#42;1^ e de derramar-lhe ofertas de bebida.” Vocês, mulheres, certamente continuarão a cumprir os vossos votos e a fazer o que prometeram.’

[NOTE]
====
. Título de uma deusa adorada pelos israelitas apóstatas, possivelmente uma deusa da fertilidade.
====

[[v24-44-26]]

^<<v24-44-26,26>>^ “Portanto, ouçam a palavra de Jeová, todos os de Judá que moram na terra do Egito: ‘“Eu juro pelo meu grande nome”, diz Jeová, “que, em toda a terra do Egito, nenhum homem de Judá voltará a usar o meu nome num juramento, dizendo: ‘Tão certo como vive o Soberano Senhor Jeová!’

[[v24-44-27]]

^<<v24-44-27,27>>^ Estou atento a eles para trazer calamidade, não algo bom; todos os homens de Judá que estão na terra do Egito serão eliminados pela espada e pela fome, até que deixem de existir.

[[v24-44-28]]

^<<v24-44-28,28>>^ Apenas uns poucos escaparão da espada e voltarão da terra do Egito para a terra de Judá. Então, todo o restante de Judá que veio morar na terra do Egito saberá qual foi a palavra que se cumpriu, se foi a minha ou a deles!”’”

[[v24-44-29]]

^<<v24-44-29,29>>^ “‘E este é o sinal que vos dou’, diz Jeová, ‘de que vos punirei neste lugar, para que saibam que a minha promessa de trazer calamidade contra vocês certamente se cumprirá.

[[v24-44-30]]

^<<v24-44-30,30>>^ Assim diz Jeová: “Vou entregar o Faraó Hofra, rei do Egito, nas mãos dos seus inimigos e dos que procuram tirar-lhe a vida,^&#42;1^ assim como entreguei Zedequias, rei de Judá, nas mãos de Nabucodonosor,^&#42;2^ rei de Babilónia, que era inimigo dele e procurava tirar-lhe a vida.”’”^&#42;3^

[NOTE]
====
. Ou: “procuram a alma dele”.
. Lit.: “Nabucodorosor”, grafia variante.
. Ou: “procurava a alma dele”.
====

'''

xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[Próximo Capítulo &#62;]