include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// nwt 2016, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v24-31-1]]

^<<v24-31-1,1>>^ “Nesse tempo”, diz Jeová, “eu vou tornar-me o Deus de todas as famílias de Israel, e eles vão tornar-se o meu povo”.

[[v24-31-2]]

^<<v24-31-2,2>>^ Assim diz Jeová:
“O povo que sobreviveu à espada obteve favor no deserto,
Enquanto Israel caminhava para o seu lugar de descanso.”

[[v24-31-3]]

^<<v24-31-3,3>>^ Jeová apareceu-me de longe e disse:
“Amo-te com um amor eterno.
Foi por isso que te atraí a mim com amor leal.^&#42;1^

[NOTE]
====
. Ou: “te continuei a mostrar amor leal”.
====

[[v24-31-4]]

^<<v24-31-4,4>>^ Ainda te vou reconstruir, e tu serás reconstruída.
Ó virgem de Israel, pegarás novamente nas tuas pandeiretas
E dançarás alegremente.^&#42;1^

[NOTE]
====
. Ou: “sairás na dança dos que se riem”.
====

[[v24-31-5]]

^<<v24-31-5,5>>^ Voltarás a plantar vinhas nos montes de Samaria;
Os lavradores plantarão e comerão os seus frutos.

[[v24-31-6]]

^<<v24-31-6,6>>^ Pois chegará o dia em que os vigias nos montes de Efraim clamarão:
‘Vamos, subamos a Sião, a Jeová, nosso Deus.’”

[[v24-31-7]]

^<<v24-31-7,7>>^ Pois assim diz Jeová:
“Gritem a Jacó com alegria,
Gritem de júbilo porque estão acima das nações.
Proclamem-no; deem louvor e digam:
‘Ó Jeová, salva o teu povo, o restante de Israel.’

[[v24-31-8]]

^<<v24-31-8,8>>^ Vou trazê-los da terra do norte.
Vou reuni-los das partes mais distantes da terra.
Entre eles, haverá cegos e coxos,
Mulheres grávidas e as que estiverem prestes a dar à luz, todos juntos.
Voltarão como uma grande congregação.

[[v24-31-9]]

^<<v24-31-9,9>>^ Virão a chorar.
Vou guiá-los enquanto suplicam pelo meu favor.
Vou conduzi-los a correntes^&#42;1^ de água,
Por um caminho plano que não os fará tropeçar.
Pois eu sou um Pai para Israel, e Efraim é o meu primogénito.”

[NOTE]
====
. Ou: “uádis”.
====

[[v24-31-10]]

^<<v24-31-10,10>>^ Ouçam a palavra de Jeová, ó nações,
E proclamem-na entre as ilhas distantes:
“Aquele que espalhou Israel é quem o reunirá.
Ele vai protegê-lo^&#42;1^ como o pastor faz com o seu rebanho.

[NOTE]
====
. Ou: “Vigiará sobre ele”.
====

[[v24-31-11]]

^<<v24-31-11,11>>^ Pois Jeová resgatará Jacó
E vai livrá-lo^&#42;1^ das mãos daquele que é mais forte do que ele.

[NOTE]
====
. Ou: “reivindicá-lo”.
====

[[v24-31-12]]

^<<v24-31-12,12>>^ Eles virão e gritarão de alegria no alto de Sião,
E ficarão radiantes com a bondade de^&#42;1^ Jeová,
Com os cereais, o vinho novo e o azeite,
E com as crias do rebanho e da manada.
Eles serão^&#42;2^ como um jardim bem regado,
E nunca mais desfalecerão.”

[NOTE]
====
. Ou: “as coisas boas da parte de”.
. Ou: “A sua alma vai tornar-se”.
====

[[v24-31-13]]

^<<v24-31-13,13>>^ “Nesse tempo, as virgens dançarão alegremente,
Assim como os jovens e os idosos.
Transformarei o seu choro em exultação.
Vou consolá-los e dar-lhes alegria em vez da sua tristeza.

[[v24-31-14]]

^<<v24-31-14,14>>^ Satisfarei os sacerdotes^&#42;1^ com fartura de alimento,^&#42;2^
E o meu povo irá saciar-se com a minha bondade”, diz Jeová.

[NOTE]
====
. Ou: “a alma dos sacerdotes”.
. Lit.: “com gordura”.
====

[[v24-31-15]]

^<<v24-31-15,15>>^ “Assim diz Jeová:
‘Ouve-se uma voz em Ramá, lamentação e choro amargo:
Raquel chora pelos seus filhos.
Ela recusa-se a ser consolada,
Porque eles já não existem.’”

[[v24-31-16]]

^<<v24-31-16,16>>^ Assim diz Jeová:
“‘Não chores mais e enxuga as tuas lágrimas,
Pois há uma recompensa pelo teu trabalho’, diz Jeová.
‘Eles voltarão da terra do inimigo.’

[[v24-31-17]]

^<<v24-31-17,17>>^ ‘Há esperança para o teu futuro’, diz Jeová.
‘Os teus filhos voltarão à sua própria terra.’”

[[v24-31-18]]

^<<v24-31-18,18>>^ “Ouvi claramente o lamento de Efraim:
‘Tu corrigiste-me, e eu fui corrigido,
Como um bezerro que ainda não foi treinado.
Traz-me de volta, e eu voltarei prontamente,
Pois tu és Jeová, meu Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ Depois de voltar atrás, senti remorsos;
Depois de entender, bati na coxa em sinal de lamento.
Senti-me envergonhado e humilhado,
Pois trazia comigo a desonra da minha juventude.’”

[[v24-31-20]]

^<<v24-31-20,20>>^ “Não é Efraim um filho precioso para mim, um filho amado?
Quanto mais falo contra ele, mais me lembro dele.
É por isso que as minhas emoções^&#42;1^ estão agitadas por causa dele.
Certamente, terei compaixão dele”, diz Jeová.

[NOTE]
====
. Lit.: “os meus intestinos”.
====

[[v24-31-21]]

^<<v24-31-21,21>>^ “Põe marcos na estrada,
E ergue sinais nela.
Presta atenção à estrada, ao caminho que terás de percorrer.
Volta, ó virgem de Israel, volta às tuas cidades.

[[v24-31-22]]

^<<v24-31-22,22>>^ Até quando ficarás indecisa, ó filha infiel?
Pois Jeová criou algo novo na terra:
Uma mulher procurará ansiosamente um homem.”

[[v24-31-23]]

^<<v24-31-23,23>>^ Assim diz Jeová dos exércitos, o Deus de Israel: “Estas palavras serão novamente ditas na terra de Judá e nas suas cidades, quando eu trouxer de volta o seu povo cativo: ‘Que Jeová te abençoe, ó morada justa, ó monte santo.’

[[v24-31-24]]

^<<v24-31-24,24>>^ Nela habitarão Judá com todas as suas cidades, os lavradores e aqueles que conduzem os rebanhos.

[[v24-31-25]]

^<<v24-31-25,25>>^ Pois vou satisfazer o cansado^&#42;1^ e saciar aquele^&#42;2^ que estiver a desfalecer.”

[NOTE]
====
. Ou: “a alma cansada”.
. Ou: “a alma”.
====

[[v24-31-26]]

^<<v24-31-26,26>>^ Nisto, acordei e abri os olhos, e o meu sono tinha sido agradável.

[[v24-31-27]]

^<<v24-31-27,27>>^ “Vejam! Estão a chegar os dias”, diz Jeová, “em que vou semear a casa de Israel e a casa de Judá com a semente^&#42;1^ de homens e a semente de animais”.

[NOTE]
====
. Ou: “descendência”.
====

[[v24-31-28]]

^<<v24-31-28,28>>^ “E, assim como fiquei atento a eles para arrancar, demolir, derrubar, destruir e prejudicar, assim também ficarei atento a eles para edificar e plantar”, diz Jeová.

[[v24-31-29]]

^<<v24-31-29,29>>^ “Nesses dias, não se voltará a dizer: ‘Os pais comeram uvas azedas, mas foram os filhos que ficaram com o gosto azedo na boca.’^&#42;1^

[NOTE]
====
. Lit.: “mas os dentes dos filhos ficaram embotados”.
====

[[v24-31-30]]

^<<v24-31-30,30>>^ Em vez disso, cada um morrerá por causa do seu próprio erro. Quem comer uvas azedas é que ficará com o gosto azedo na boca.”

[[v24-31-31]]

^<<v24-31-31,31>>^ “Vejam! Estão a chegar os dias”, diz Jeová, “em que farei um novo pacto com a casa de Israel e com a casa de Judá.

[[v24-31-32]]

^<<v24-31-32,32>>^ Não será como o pacto que fiz com os seus antepassados no dia em que os agarrei pela mão para tirá-los da terra do Egito, ‘pacto meu que eles violaram, embora eu fosse o seu verdadeiro dono’,^&#42;1^ diz Jeová”.

[NOTE]
====
. Ou, possivelmente: “o seu marido”.
====

[[v24-31-33]]

^<<v24-31-33,33>>^ “Pois este é o pacto que farei com a casa de Israel depois desses dias”, diz Jeová. “Porei a minha lei no seu íntimo e irei escrevê-la no seu coração. E eu irei tornar-me o seu Deus, e eles irão tornar-se o meu povo.”

[[v24-31-34]]

^<<v24-31-34,34>>^ “E não continuarão a ensinar cada um ao seu próximo e cada um ao seu irmão, dizendo: ‘Conheçam a Jeová!’ Porque todos eles me conhecerão, desde o menor até ao maior”, diz Jeová. “Pois perdoarei o seu erro e não me voltarei a lembrar do seu pecado.”

[[v24-31-35]]

^<<v24-31-35,35>>^ Assim diz Jeová,
Aquele que dá o sol para iluminar o dia,
As leis^&#42;1^ da lua e das estrelas para iluminar a noite,
Aquele que faz com que o mar fique revolto e que agita as suas ondas,
Cujo nome é Jeová dos exércitos:

[NOTE]
====
. Ou: “Os decretos”.
====

[[v24-31-36]]

^<<v24-31-36,36>>^ “‘Se estas leis falhassem’, diz Jeová,
‘Só então é que a descendência de Israel deixaria de ser uma nação diante de mim para sempre’.”

[[v24-31-37]]

^<<v24-31-37,37>>^ Assim diz Jeová: “‘Se os céus em cima pudessem ser medidos e os alicerces da terra em baixo pudessem ser explorados, só então é que eu poderia rejeitar toda a descendência de Israel por causa de tudo o que fizeram’, diz Jeová.”

[[v24-31-38]]

^<<v24-31-38,38>>^ “Vejam! Estão a chegar os dias”, diz Jeová, “em que a cidade será reconstruída para Jeová, desde a Torre de Hananel até ao Portão da Esquina.

[[v24-31-39]]

^<<v24-31-39,39>>^ E a corda de medir será estendida até à colina de Garebe, e virará em direção a Goa.

[[v24-31-40]]

^<<v24-31-40,40>>^ E todo o vale^&#42;1^ dos cadáveres e das cinzas,^&#42;2^ e todos os socalcos até ao vale do Cédron, sim, até à esquina do Portão dos Cavalos, a leste, serão algo sagrado para Jeová. A cidade nunca mais será arrancada nem derrubada.”

[NOTE]
====
. Ou: “toda a planície”.
. Ou: “cinzas gordurosas”, isto é, cinzas impregnadas da gordura dos sacrifícios.
====

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]